### PR TITLE
adding berrys-theme

### PR DESCRIPTION
**Pull request by vbuzin**
### Brief summary of what the package does

A light, clean and elegant Emacs theme 

### Direct link to the package repository

https://github.com/vbuzin/berrys-theme

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

-- 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
I was expecting something colorful, you know, like berries.  haha  :)

**Comment by vbuzin** [comment]
There're different kinds of berries ;)

**Comment by riscy** [comment]
Looks nice. :)

This is harmless but seems unnecessary given your `Package-Requires`:
```
(unless (>= emacs-major-version 24)
  (error "Berrys theme requires Emacs 24 or later!"))
```

A quick pass over the checklist:

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
berrys-theme.el:0: You should have a section marked ";;; Commentary:"
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191027.20):
```
5 issues found:

1:0: error: Package should have a ;;; Commentary section.
1:0: error: package.el cannot parse this buffer: Package lacks a file header
302:5: error: You should depend on (emacs "24.1") if you need `org-block'.
306:5: error: You should depend on (emacs "24.1") if you need `org-date'.
348:3: warning: Closing parens should not be wrapped onto new lines.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems) (and depend on at least (emacs "24"))
(The following assumes lexical binding is enabled)
No byte-compilation issues! 😎

**Comment by vbuzin** [comment]
fixed the linting stuff

**Comment by riscy** [comment]
Thanks for sticking to the checklist -- I believe there's a `(provide-theme 'berrys)`, and you'll still need your original `provide` to keep the linters happy, so you can end your code with:

```elisp
(provide-theme 'berrys)
(provide 'berrys-theme)

;; Local Variables:
;; no-byte-compile: t
;; indent-tabs-mode: nil
;; End:

;;; berrys-theme.el ends here
```
Once that's added this looks good to merge.

**Comment by vbuzin** [comment]
done

**Comment by riscy** [comment]
Great, thanks!

**Pull request merged**
