### PR TITLE
Add comware-router-mode recipe

### PR DESCRIPTION
**Pull request by daviderestivo**
### Brief summary of what the package does

Major mode for editing Comware routers and switches configuration files.

### Direct link to the package repository

https://github.com/daviderestivo/comware-router-mode

### Your association with the package

I'm the author and current maintainer of this mode.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
A quick pass over the checklist:

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190905.1847):
```
No issues found.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems) (and depend on at least (emacs "24"))
(The following assumes lexical binding is enabled)
```
comware-router-mode.el:168:24:Warning: `beginning-of-buffer' is for
    interactive use only; use `(goto-char (point-min))' instead.
```

Added miscellaneous hints (automated):
- comware-router-mode.el#L259: It looks like you're defining your major-mode in an unusual way -- check out [this](https://www.gnu.org/software/emacs/manual/html_node/elisp/Major-Mode-Conventions.html) section of the elisp manual.
- comware-router-mode.el#L168: Don't quote lambdas; this prevents them from being compiled

**Comment by daviderestivo** [comment]
> M-x byte-compile-file (using Emacs 26.2):
> Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems) (and depend on at least (emacs "24"))
> (The following assumes lexical binding is enabled)

The mode was already depending on  (emacs "24"). I have enabled lexical binding.

> 
> ```
> comware-router-mode.el:168:24:Warning: `beginning-of-buffer' is for
>     interactive use only; use `(goto-char (point-min))' instead.
> ```

Valid point. I have fixed it.

> Added miscellaneous hints (automated):
> 
> * comware-router-mode.el#L259: It looks like you're defining your major-mode in an unusual way -- check out [this](https://www.gnu.org/software/emacs/manual/html_node/elisp/Major-Mode-Conventions.html) section of the elisp manual.
I guess the mode is properly defined using an autoload function.

> * comware-router-mode.el#L168: Don't quote lambdas; this prevents them from being compiled

Fixed it.

Thanks for your review :)

**Comment by riscy** [comment]
Thanks for addressing that first pass.  I'm taking a more in-depth look now:

You probably want to use the `define-derived-mode` macro and derive from `prog-mode` -- I should probably have recommended that in my first comment.  The reason for this is that some users will add hooks to prog-mode to do programming language-specific things, such as enabling line numbers, certain personalized syntax highlighting, etc.  Likely they will want the same for your mode.  I recommend `define-derived-mode` because you have to write less code this way (e.g. you don't have to explicitly run hooks or call `use-local-map` or define `comware-router-mode-hook` and so forth), and so there's less room to make a mistake.  I'd recommend taking a look at a package that is similar to yours (maybe another prog-mode extension).

Both `comware-router-mode-map` and `comware-router-mode-syntax-table` can be defined by wrapping a `let` inside a `defvar` -- it's better to do it this way because you don't want a user's customizations to be clobbered if they reload your feature or re-evaluate the source buffer.  An example of what I mean:
```elisp
(defvar comware-router-mode-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?_ "w" table))
  "Syntax table for comware router mode.")
```

Good work with defining the faces using inherited faces only.

I think once those two (broad) issues above are addressed, this is good to merge!

**Comment by daviderestivo** [comment]
> I think once those two (broad) issues above are addressed, this is good to merge!

@riscy I would like to thank you for having spent your time in reviewing my code. This is very valuable for me so I can improve my elisp coding skills :). 

Btw, I think I have fixed both issues.

**Comment by riscy** [comment]
Wooops, I made a mistake -- I forgot to make sure the `defvar` assigns the value of the eventual table.

```elisp
(defvar comware-router-mode-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?_ "w" table)
    table) ;; <-- forgot
  "Syntax table for comware router mode.")

**Comment by daviderestivo** [comment]
> Wooops, I made a mistake -- I forgot to make sure the `defvar` assigns the value of the eventual table.

Fixed it.

**Comment by riscy** [comment]
One last nag, I promise. :)  You actually need Emacs 24.3 for `setq-local` now that it's been added:

```
;; Package-Requires: ((dash "2.16.0") (emacs "24.3"))
```

**Comment by daviderestivo** [comment]
> ;; Package-Requires: ((dash "2.16.0") (emacs "24.3"))

Fixed it as well 👍

**Comment by riscy** [comment]
Great!

**Pull request merged**
