### PR TITLE
Add djangonaut recipe.

### PR DESCRIPTION
**Pull request by proofit404**
### Brief summary of what the package does

Minor mode to navigate around Django project. It's like rinari for Rails.

### Direct link to the package repository

https://github.com/proofit404/djangonaut

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Couple of quick notes:

- Please remove "Emacs" from the package description line: it's redundant as all emacs packages and minor modes are for Emacs. `package-lint` should have warned about this.
- `C-c r` is a keybinding [reserved for end-user customisation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html), so you must not use it. You might like to provide a prefix keymap and suggest that users bind it to `C-c r`, though. `package-lint` would also have told you about this issue.

**Comment by proofit404** [comment]
I saw those warnings during package publish preparations. But I ignore them since some popular packages do not follow this practice as well. Sorry for the inconvenience.

All fixed as you advice.

**Comment by proofit404** [comment]
Any news?

**Comment by purcell** [comment]
Yep, looks good, but even though it's now (more easily) configurable you should still change the default from `C-c r`, e.g. to `C-c '`.

I also noticed there's a missing package dependency on `s`, which the code uses.

**Comment by proofit404** [comment]
Done. Thanks for review!

**Comment by purcell** [comment]
Great!

**Pull request merged**
