### PR TITLE
Add recipe for indent-control

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

This package combine all indentation into a giant list. So user can manages the indentation for each major mode a bit easier to one interface. Another feature is the package records down the previous edited indentation level and it keeps it to all other buffers.

### Direct link to the package repository

https://github.com/jcs-elpa/indent-control

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi @jcs090218, per some new guidelines in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#waiting-for-reviews-and-taking-feedback-into-account), could you please try to limit your open recipe PRs?

**Comment by jcs090218** [comment]
I think I have close most of my PR and left the priority ones. #7261 #7222 and this PRs. Would 3 be okay? Or just 1? Thanks!

**Comment by riscy** [comment]
Yes, it's fine to occasionally have 3 PRs open. :)  But, if you think you will _consistently_ have 3 PRs open, keeping the queue as full as you can, then I would ask you to limit your recipe PRs to 1 at a time.  When there's more than one recipe PR I have to take active effort to make sure I'm not going some authors more review time.

**Comment by riscy** [comment]
I can see the value in this although the implementation seems needlessly complicated.  To be helpful, here's a couple examples:
- `indent-control--set-indent-level-record-by-mode` and `indent-control--get-indent-level-record-by-mode` are doing linear while-loop scans but could just us something like a hash table
- `indent-control--delta-ensure-valid-tab-width` doesn't appear to need to exist at all -- it's called in one only place and all it does is call another function, making the code look more complicated than it actually is

Some other issues:
- You `(add-hook 'prog-mode-hook #'indent-control--prog-mode-hook)` but you should put such instructions in your `;;; Commentary` rather than execute it automatically
- Same with `(indent-control-continue-with-tab-width-record)` but I think you should be aware of these norms by now
- I think ruby programmers (and ruby-mode itself) generally prefer an indent level of two spaces -- what was your methodology for choosing the defaults?
- It has been a while, but looking at my old config I can see `web-mode` also has `web-mode-sql-indent-offset`

Minor stuff:
- This is not a blocker but a suggestion based on my personal habits: variable names like `tw`, `mn`, `cv`, etc. should be expanded for readability
- Conversely (and I hope it doesn't sound like I'm giving conflicting advice) but some of your function names are so wordy they seem to lose all meaning, for example `indent-control-continue-with-tab-width-record` seems like it could just be `indent-control-apply`, and e.g. `indent-control-inc-indent-level` could just be `indent-control-increase`
- Rather than `(message "[WARNING] Indentation level record not found: %s" mn)` (and the surrounding machinery in `indent-control--no-log-apply`) why not use the builtin `warn` function?  This would let users do things like set `warning-suppress-p` if they don't want to see these
- Instead of `(- 0 indent-control-delta)` you can just `(- indent-control-delta)`
- I'd recommend a quick spellcheck

**Comment by riscy** [comment]
Feel free to ping when ready for another look!

**Comment by jcs090218** [comment]
> * indent-control--set-indent-level-record-by-mode and indent-control--get-indent-level-record-by-mode are doing linear while-loop scans but could just us something like a hash table
> * indent-control--delta-ensure-valid-tab-width doesn't appear to need to exist at all -- it's called in one only place and all it does is call another function, making the code look more complicated than it actually is

These are my mistake! All fixed! Thanks! 

> Some other issues:

> * You (add-hook 'prog-mode-hook #'indent-control--prog-mode-hook) but you should put such instructions in your ;;; Commentary rather than execute it automatically
> * Same with (indent-control-continue-with-tab-width-record) but I think you should be aware of these norms by now

Hmm.. I consider these two points are part of the feature from the package itself. The package should handle the indent data at the very beginning of this module. 😕 

> * I think ruby programmers (and ruby-mode itself) generally prefer an indent level of two spaces -- what was your methodology for choosing the defaults?

I don't have the methodology for this; that is why I have set the variable to `defcustom`. I have set the default to `2` for `ruby-mode`.

> * It has been a while, but looking at my old config I can see web-mode also has web-mode-sql-indent-offset

Added. Thanks!

> Minor stuff:

I should have fixed most the minor issues.

---

Thanks for the review.

**Comment by riscy** [comment]
Thank you, that is a massive improvement.

> Hmm.. I consider these two points are part of the feature from the package itself.

Rather than adding hooks that make modifications when someone loads the package (they may not want the hooks to run) you should create a global minor mode that can be toggled off and on.  If there is an error or an incompatibility, the average Emacs user will have to restart Emacs to unload your package.

> I don't have the methodology for this; that is why I have set the variable to defcustom. I have set the default to 2 for ruby-mode.

Okay, that sounds fine to me.  I appreciate the change to ruby-mode since I'm fairly certain it's their community style, so it's better for the defaults to match whenever possible.  Also minor but non-blocking, "recrods" should be "records".
-

**Comment by jcs090218** [comment]
> Rather than adding hooks that make modifications when someone loads the package (they may not want the hooks to run) you should create a global minor mode that can be toggled off and on. If there is an error or an incompatibility, the average Emacs user will have to restart Emacs to unload your package.

Good idea. I have added the global minor mode `indent-control-mode`.

>  I appreciate the change to ruby-mode since I'm fairly certain it's their community style, so it's better for the defaults to match whenever possible.

Understandable.

> Also minor but non-blocking, "recrods" should be "records".

Oops, I should be more careful about this. Thanks!

**Comment by riscy** [comment]
Looks like a cool package, thanks!

**Pull request merged**
