### PR TITLE
add exunit recipe

### PR DESCRIPTION
**Pull request by ananthakumaran**
### Brief summary of what the package does

A minor mode that provides commands to run [ExUnit](https://hexdocs.pm/ex_unit/ExUnit.html) tests. The output is syntax highlighted and stacktraces are navigatable.

### Direct link to the package repository

https://github.com/ananthakumaran/exunit.el

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

I don't use Elixir, so I can't offer much feedback from that perspective, but I see a lot of functions without docstrings.  Would you mind adding some?  They help other users to understand how your code works and are a significant aid when someone wants to modify it.

**Comment by ananthakumaran** [comment]
Added some more docs, I hope the remaining functions are self-explanatory.

**Comment by alphapapa** [comment]
Curious, why use two lists like this?

```el
(defvar exunit-compilation-error-regexp-alist-alist
  '((elixir-warning "warning: [^\n]*\n +\\([0-9A-Za-z@_./:-]+\\.exs?\\):\\([0-9]+\\)" 1 2 nil 1 1)
    (elixir-error " +\\(\\(?:([0-9A-Za-z_-]*) \\)?[0-9A-Za-z@_./:-]+\\.\\(?:ex\\|exs\\|erl\\)\\):\\([0-9]+\\):?" 1 2 nil 2 1)))
(defvar exunit-compilation-error-regexp-alist
  (mapcar 'car exunit-compilation-error-regexp-alist-alist))
```

**Comment by ananthakumaran** [comment]
```elisp
(defcustom compilation-error-regexp-alist
  (mapcar 'car compilation-error-regexp-alist-alist)
  "Alist that specifies how to match errors in compiler output.
On GNU and Unix, any string is a valid filename, so these
matchers must make some common sense assumptions, which catch
normal cases.  A shorter list will be lighter on resource usage.

Instead of an alist element, you can use a symbol, which is
looked up in `compilation-error-regexp-alist-alist'.  You can see
the predefined symbols and their effects in the file
`etc/compilation.txt' (linked below if you are customizing this).
```
`define-compilation-mode` is doing all the wiring up here

**Comment by alphapapa** [comment]
Yep, I looked that up right after I clicked "Comment," so I deleted mine.  :)  Thanks.

**Comment by purcell** [comment]
Thanks. Quick notes:

- Since you're depending on Emacs 24.3, you can wrap `defvar-local` [here](https://github.com/ananthakumaran/exunit.el/blob/516e71ba6a9e74e64f2a82c124f3a8ffa16743b7/exunit.el#L54-L55). But in any case, you only use it to declare one variable, so just use `defvar-local` plus the  `put` for `permanent-local`.
- The value of a `setq` expression is the variable's new value, so you can delete [this line](https://github.com/ananthakumaran/exunit.el/blob/516e71ba6a9e74e64f2a82c124f3a8ffa16743b7/exunit.el#L71).
- Use `expand-file-name` & co instead of splicing paths together with `/` - it's more portable. When splicing multiple parts, you can either use `f-join` (from the `f` package) or write your own trivial helper using `cl-reduce` and `expand-file-name`:
```el
(defun my-join-paths (&rest args)
  (cl-reduce (lambda (a b) (expand-file-name b a)) args))

(my-join-paths "/some/dir" ".." "subdir") => "/some/subdir"
```
- `exunit-mode` appears unused, and should be removed if so.

Hope that helps!

**Comment by ananthakumaran** [comment]
Thanks for the review, updated now

**Comment by purcell** [comment]
Great, merged - thanks! :tada:

**Pull request merged**
