### PR TITLE
Add recipe for octo-mode

### PR DESCRIPTION
**Pull request by cryon**
### Brief summary of what the package does
Major mode for [Octo](https://github.com/JohnEarnest/Octo) assembly language.

### Direct link to the package repository

https://github.com/cryon/octo-mode

### Your association with the package

I am the creator and current maintainer

### Relevant communications with the upstream package maintainer

None

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi, one suggestion: The keywords field uses specific keywords, described in the info page (`helm-info-emacs` makes it easy to find the right page):

> To make it easier to find packages related to a topic, most packages are associated with one or more "keywords" based on what they do. Type C-h p' (finder-by-keyword') to bring up a list of package keywords, together with a description of what the keywords mean. To view a list of packages for a given keyword, type on that line; this displays the list of packages in a Package Menu buffer (*note Package Menu::).

**Comment by cryon** [comment]
Good catch! I've updated the Keywords field.

**Comment by purcell** [comment]
Thanks!
- Please delete the empty first line
- The `octo-mode-version` var is redundant, and unlikely to ever match the containing package version. :-)
- Consider using `prog-mode` as the parent mode, rather than `fundamental-mode`. You'd need to add a `Package-Requires: ((emacs "24"))` header too.

**Comment by cryon** [comment]
Thanks for the feedback! I agree and have made the changes.

**Pull request merged**
