### PR TITLE
Add a recipe for melpa-check

### PR DESCRIPTION
**Pull request by akirak**
### Brief summary of what the package does

melpa-check is a framework for linting and testing Emacs Lisp packages. Its main goal is to let package authors easily set up continuous integration (CI) before they send PRs to MELPA. It can be run either locally or on CI.

It focuses on reproducibility, ease of configuration, and convenience to run tests.

### Direct link to the package repository

https://github.com/akirak/melpa-check

### Your association with the package

I am the author and the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

As documented in README, it requires quite a few extra dependencies including Nix, and it is supported only on Linux and macOS.

I also plan on integrating extra checks by [melpazoid](https://github.com/riscy/melpazoid). Is it okay?

### CODE REVIEW

**Comment by milkypostman** [comment]
cc: @riscy 

I'm out of the loop a bit. can you let me know about how this fits in with purcell/package-lint?

**Comment by riscy** [comment]
> I'm out of the loop a bit. can you let me know about how this fits in with purcell/package-lint?

Yeah -- looks like something that runs checkers in an ensemble (including purcell/package-lint but also others).  Similar space to some of [my cobbled together scripts](https://github.com/riscy/melpazoid) for running checks.

**Comment by milkypostman** [comment]
It’s be nice to get these things a bit unified or at least collaborate vs
building all these different versions. From reading it seems like there is
another thing that this will eventually integrate with?

So I guess what I’m saying is that if there is interest we could start
something under the melpa org maybe. Will check with @purcell but just
dropping that here to start the discussion.

Sorry for not being clear I’m on mobile and didn’t want to look up all the
names.

**Comment by akirak** [comment]
@milkypostman @riscy 
This is an alternative to @alphapapa's [makem](https://github.com/alphapapa/makem.sh) and @doublep's [eldev](https://github.com/doublep/eldev). There has been a [continuous discussion](https://github.com/alphapapa/makem.sh/issues/3) on this kind of tool.

In the thread, mine was mentioned as `emacs-package-checker`, which was purely written in Nix at that time, but after a huge rewrite in the last few months, it now has a CLI for usability, a Dhall format support for type-safe configuration, and an Emacs frontend for config generation. This is why I am trying to add this program as an Emacs package.

One advantage of `melpa-check` over `makem.sh` and other alternatives is its support for multi-package repositories (https://github.com/purcell/package-lint/issues/172). I thought none of the other tools supported this feature, but `eldev` seems to do. 

Still, `melpa-check` takes a different approach from that tool. For example, it is capable of byte-compiling an Emacs package with multiple versions of Emacs with a single CLI command, thanks to Nix. Nix allows to include non-Emacs dependencies in an OS-agnostic way, so `melpa-check` has a potential to support even more linters than `makem`. It would be possible to incorporate melpazoid, for example.

**Comment by riscy** [comment]
> So I guess what I’m saying is that if there is interest we could start something under the melpa org maybe.

Yeah, I think codifying (literally) the checklist with a GitHub action or similar would be a great move.

**Comment by ericdallo** [comment]
It's a great idea and I pretend to use this package on [emacs-lsp](https://github.com/emacs-lsp) PRs.
I think that use this package as a CI for Melpa PRs could be a great idea too.

**Comment by riscy** [comment]
I didn't spot this:

> I also plan on integrating extra checks by melpazoid. Is it okay?

Of course!  I just consider many of those checks to be very experimental/fragile (and yet things that commonly come up during review), so I wouldn't gate any kind of pass/fail status behind them.

I think the discussion above may go somewhere good, but here's a quick pass in the meantime:

### melpa-check-git.el ###

package-lint-current-buffer (using version 20200419.406):
```
1 issue found:
7:0: error: Package-Requires outside the main file have no effect.
```

### melpa-check-multisel.el ###

byte-compile-file (using Emacs 26.3):
```
melpa-check-multisel.el:74:1:Warning: the following functions are not known to
    be defined: helm, helm-build-sync-source, helm-marked-candidates
```
I think these are because `(declare-function #'helm-build-sync-source "ext:helm")` should be written `(declare-function helm-build-sync-source "ext:helm")`

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200419.406):
```
1 issue found:
7:0: error: Package-Requires outside the main file have no effect.
```

### melpa-check-package.el ###

byte-compile-file (using Emacs 26.3):
```
melpa-check-package.el:234:1:Warning: the following functions are not known to
    be defined: string-remove-suffix, string-empty-p
```
Just a `(require 'subr-x)` for this.

package-lint-current-buffer (using version 20200419.406):
```
1 issue found:
7:0: error: Package-Requires outside the main file have no effect.
```

### melpa-check-verify.el ###

package-lint-current-buffer (using version 20200419.406):
```
1 issue found:
7:0: error: Package-Requires outside the main file have no effect.
```

### melpa-check.el ###

byte-compile-file (using Emacs 26.3):
```
melpa-check.el:725:1:Warning: the function `dhall-format-buffer' is not known
    to be defined.
```

Suggestions/experimental static checks:
- melpa-check.el#L610: It's safer to sharp-quote function names; use `#'`

### Package ###

- Avoid specifying `:branch` except in unusual cases

**Comment by conao3** [comment]
The brand "MELPA" is a big name in the Emacs community and gives the impression to those who are not familiar with this thing that it is an official MELPA tool, developed by MELPA maintainers.
If the purpose of this package name is not to confuse people, @akirak may want to consider a different name.
Or, I suggest you make something similar to this package under MELPA-org as @milkypostman says.

If I'm not mistaken in my understanding, this package only runs a few commands and examines their return values, so it's questionable that it would be such a large package in the first place.

**Comment by akirak** [comment]
@riscy Thank you for the review. I've always wondered why my linter did not produce the same result as yours, but now I think I've fixed the issues (both for the linter and the package itself).

**Comment by akirak** [comment]
@conao3 I understand your point. That's what I was afraid of too, and I have to admit that I was rather bold on the choice of the name. If the authors and maintainers of MELPA are against the name, I won't mind change it to a more neutral, safe name. For now, there are at least two people who are using (or trying to use) this program (i.e. ericdallo and me), and I am using it in only two packages at present, so it won't be too hard to change the name. The sooner the better.

Anyway, the purpose of this program is to reproduce checks currently performed by @riscy for MELPA (candidate) packages. It will ensure quality of packages even after they are added to MELPA, but also it could (hopefully) reduce effort of people who review packages. It is not meant for profit in itself, and neither confusion nor preventing confusion is the primary purpose.

> If I'm not mistaken in my understanding, this package only runs a few commands and examines their return values, so it's questionable that it would be such a large package in the first place.

There are several reasons for the size of the entire repository. It could be reduced to some extent, but the structure was intended to hide Nix, which is not an easy language for those who are new to it. I explained the reason for using Nix. Fortunately, Nix is more maintainable than bash/Makefile, if you are used to it, so it is indeed a good language for building something. And the other parts (i.e. Dhall and PureScript) are strongly typed, so they are much less troublesome to deal with. Nonetheless, it could be simpler if it were written in one language. If anyone could invent a smaller solution which is as capable as this, I will switch to it. It's not available now.

**Comment by conao3** [comment]
The use of Nix, Dhall, and PureScript is a difference in project policy, so I won't comment on that.
The one thing I would advise is that I never think Lintar is going to get a [monkey patch](https://github.com/akirak/melpa-check/blob/8448fe654f12689bd266e1aa5d98f5d80a2e7d64/nix/checkers/package-lint-runner.el#L84-L89) on `package-lint`.
If you don't like the behavior of `package-lint`, you want to send PR.

@riscy, I have one comment related to the `melpazoid`,
I understand that `melpazoid` was a starting point for your personal project.
However, I think some of `melpazoid`'s checkers (such as the fact that lambda doesn't need a function quote `#'`) are universally useful and should be included in `package-lint`.
Inclusion in the `package-lint` prevents an Elisp package developer from finding out about it only after submitting it to MELPA.

**Comment by akirak** [comment]
@conao3 

> The one thing I would advise is that I never think Lintar is going to get a monkey patch on package-lint.

It's used for local dependencies. That is, it handles dependencies in the same repository in multi-package repositories. I wasn't sure if it would be useful in general so didn't send a PR to `package-lint`. Maybe I'll consider that.

**Comment by riscy** [comment]
>  I was rather bold on the choice of the name. If the authors and maintainers of MELPA are against the name, I won't mind changing it to a more neutral, safer name.

I think it would be a good idea if some other MELPA folks weigh in as well as me on this (@purcell, @tarsius).  For example, it would be unfortunate if there were a discrepancy between what MELPA's maintainers ask for and what a package called "melpa-check" suggests.

Ultimately, I think most of these checks should end up in MELPA's CI, which would then be the single source of truth describing what it means to pass the checklist.  It doesn't seem too far off, and we learn a lot from packages like this.

> @riscy, I have one comment related to the melpazoid, I understand that melpazoid was a starting point for your personal project.  However, I think some of melpazoid's checkers (such as the fact that lambda doesn't need a function quote #') are universally useful and should be included in package-lint.  Inclusion in the package-lint prevents an Elisp package developer from finding out about it only after submitting it to MELPA.

Yes, that's a good point.  A lot of the melpazoid checks are sloppy, but some of them (like the one you mention) are foolproof enough, and time-proven enough, that they may be ready to become part of package-lint's warnings.

**Comment by akirak** [comment]
> Ultimately, I think most of these checks should end up in MELPA's CI, which would then be the single source of truth describing what it means to pass the checklist. It doesn't seem too far off, and we learn a lot from packages like this.

I'm also thinking of adding "auto" mode to the program, which takes a recipe file as input and run basic linting for a package with zero configuration (However, it's already implemented in melpazoid, right? Then it would be a redundant effort). If a package had `.melpa-check` directory in its repository, it could also run tests.

Thus the program could be extended to support both centralised and distributed CI, but an initial motivation for the project was to handle complex projects like [this](https://github.com/melpa/melpa/issues/6262) with minimal duplicates in configuration. (He pointed out the issue just before I first started working on this idea. I was thinking about the new idea for CI but not the live status, which apparently caused the rage.) I've wanted to feel safer about my development cycles, and the name of this project is not the most important. 

Perhaps @conao3 is right about the renaming. I have to start out this project humbly and wait for natural growth. I will continue anyway, because it was originally meant to solve my own problems.

**Comment by purcell** [comment]
Sorry I haven't commented on this yet. It's really great to see this work. I have a lot of thoughts, but my head is a bit too cluttered currently to express them.

**Comment by akirak** [comment]
@purcell Thanks for your update. I will welcome your comments no matter what they are about (e.g. the choice of technology, code, license, people, etc.), but there is no hurry, and I am willing to respond to feedback accordingly. Unless there is an explicit disapprobation, I will continue with this project for now.

I also found an interesting case when using Emacs packages from Nixpkgs on older versions of Emacs: https://github.com/akirak/melpa-check/issues/16 This can matter outside of this project, so I filed it in this ticket: https://github.com/NixOS/nixpkgs/issues/66303

**Comment by akirak** [comment]
I am now thinking of changing the name, since it's an experimental project and won't become a standard in the near future. I'll make `melpa-check` free of use by someone who creates a promising solution to the problem.

I haven't come up with a good name for my project yet, so I am accepting ideas in a separate ticket: https://github.com/akirak/melpa-check/issues/18

I'll close this PR to explore a possibility for non-MELPA installation. I think Nix can install both the Emacs package and the executable, and it would be better in terms of version consistency. If you want to talk, you can reopen it, though there are many tickets on similar topics.

Thank you for your attentions (especially to @ericdallo who gave me an extensive feedback).

**Pull request closed without merging**
