### PR TITLE
add recipe for dispwatch

### PR DESCRIPTION
**Pull request by mnp**
### Brief summary of what the package does

This package watches the current display geometry (pixel width and height) and gives your
hook a call if it changes.  Intended use case is plugging/unplugging a monitor.

### Direct link to the package repository

https://github.com/mnp/dispwatch

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick notes:

- Instead of a single-branch `if` and a `progn`, just use `unless` [here](https://github.com/mnp/dispwatch/blob/86905b6f820b1984cf7b9d736348c9bc5bcd8965/dispwatch.el#L90-L93) and elsewhere. (Or `when`, as applicable.)
- Your pair of `enable`/`disable` functions indicate that this is an informal minor mode. Instead, declare a proper global minor mode with `define-minor-mode`.
- It would be preferable to pass the new geometry to hook functions as 2 numeric arguments or a cons cell rather than constructing a geometry string. It's easy enough for the user to call `format` if required, and a cons cell can be compared using `eq`, and passing the dimensions individually makes it easy for hook functions to detect, say, narrow or small displays.
- Even polling every 2 seconds would be minimal overhead, and might be a slightly nicer experience out of the box.

Hope that helps.

**Comment by purcell** [comment]
Ping! :-)

**Comment by mnp** [comment]
Yep, thanks for the reminder, and for the detailed review. Will address all comments.

**Comment by riscy** [comment]
> Ping ACK.

Does this mean you're ready for another pass? :)

**Comment by mnp** [comment]
Yep please have at it.  Thanks again for the kind review.

**Comment by riscy** [comment]
<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
1 issue found:

1:64: warning: You should depend on (emacs "24") if you need lexical-binding.
```
Also on dispwatch.el#L3: This copyright notice may need updating?

Once those are checked, this looks good to merge.

**Comment by mnp** [comment]
Comments addressed.  Thanks!

**Comment by riscy** [comment]
Great thanks!  And, welcome to MELPA. :)

**Pull request merged**
