### PR TITLE
Add recipe for compile-multi

### PR DESCRIPTION
**Pull request by mohkale**
### Brief summary of what the package does

An emacs [multi-compile](https://github.com/ReanGD/emacs-multi-compile) style package that uses a more lisp style configuration and supports dynamically plugging in compilation targets from external tools which also makes it usable as a replacement for [helm-make](https://github.com/abo-abo/helm-make).

I'm about to release a new projectile replacement package I've called [projector](https://github.com/mohkale/projector) (will rename to avoid conflict) and it makes use of this as a dependency.

### Direct link to the package repository

https://github.com/mohkale/compile-multi

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  On a quick first pass --

`compile-multi.el` with package-lint 20221003.1636:
```
1 issue found:
1:0: error: Package should have a Homepage or URL header.
```

**Comment by mohkale** [comment]
Ah, apologies, I thought I'd already fixed this but turns out I added the fix to the PR I had setup for MELPA support. Could you check using the [feat/melpa-support](https://github.com/mohkale/compile-multi/tree/feat/melpa-support) branch please. I'll merge it once this PR is merged as well.

**Comment by riscy** [comment]
For my own reference, I am testing `(compile-multi :fetcher github :repo "mohkale/compile-multi" :branch "feat/melpa-support")`.

This looks good per the checklist.  A couple comments: I think your `;;; Commentary` is too brief; maybe you could pinch some of the stuff in your README to explain why people would want to use this.

`(error "Don't know how to run the command cmd")` -- I think you wanted to interpolate the compile-cmd?

**Comment by mohkale** [comment]
Hi @riscy, I've updated the package now. Please check again at your convenience. Thank you :-).

**Comment by riscy** [comment]
I am still testing `(compile-multi :fetcher github :repo "mohkale/compile-multi" :branch "feat/melpa-support")` but that branch looks good to go for MELPA. :)

**Comment by mohkale** [comment]
Great thanks :-).

**Comment by riscy** [comment]
Just let me know when you've merged that into your default branch and we're good to go.

**Comment by mohkale** [comment]
@riscy 

Ah, I was planning to merge here first then their. Thanks for clarifying what you meant. I've merged that branch now so we should be good here :-).

**Pull request merged**
