### PR TITLE
Add a recipe for the act mode

### PR DESCRIPTION
**Pull request by rafaelcn**
### Brief summary of what the package does

Adds a basic syntax highlight for the act programming language 

### Direct link to the package repository

https://github.com/rafaelcn/act

### Your association with the package

I'm the maintainer of the package

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`proact-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- proact-mode.el#L26: Top-level `setq` should usually be replaced by `defvar` or `defconst`
```

Package and license:
- proact-pkg.el -- consider excluding; MELPA can create one from proact.el
- proact-mode.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by rafaelcn** [comment]
oh, I thought that proact-pkg was something I had to create manually. I copied that format from the go major mode and replaced it with my content.

**Comment by rafaelcn** [comment]
@riscy, I think I had everything fixed. Can you take another look?

**Comment by riscy** [comment]
Hi @rafaelcn - you *can* include a -pkg.el file, but it's not necessary for MELPA.  Unless you have a reason to use one, I'd probably suggest avoiding it.  But it's not a blocker.

After the changes you made, you should name the recipe, and the elisp file, `proact-mode`.  You will still have `proact-` as your prefix namespace.

**Comment by rafaelcn** [comment]
okay, @riscy, the recipe name and the elisp mode file have been renamed.

**Comment by riscy** [comment]
I think you haven't enabled editing your PR so I can't fix on my side, but the recipe is still referring to a `proact` package:

```
(proact
...
```

**Comment by riscy** [comment]
Thank you - recipe appears to be fixed now.

On looking more closely, I notice your boilerplate is inverted - instead of:

```
;;; proact-mode.el --- Major mode for the ACT programming language -*- coding: utf-8; lexical-binding: t; -*-

;;; Commentary:

;; SPDX-License-Identifier: MIT

;; Authors: Rafael Campos Nunes <rcamposnunes@outlook.com>
;; Package-Version: 1.0
;; Package-Requires: ((emacs "26.1"))
;; URL: https://github.com/rafaelcn/proact

;;
;; This file is not part of GNU Emacs.
;;
```
... you should have something closer to:
```elisp
;;; proact-mode.el --- Major mode for the ACT programming language -*- coding: utf-8; lexical-binding: t; -*-

;; Authors: Rafael Campos Nunes <rcamposnunes@outlook.com>
;; Package-Version: 1.0
;; Package-Requires: ((emacs "26.1"))
;; URL: https://github.com/rafaelcn/proact
;; SPDX-License-Identifier: MIT

;; This file is not part of GNU Emacs.

;;; Commentary:

;; <actual commentary here>
```
and currently you lack any real Commentary - one thing you may want to mention, for example, is that this currently only supports syntax highlighting.

It also strikes me that you're naming this `proact-mode` instead of `act-mode` - why is this?  For the vast majority of languages, the major mode is named directly after the language.  e.g. c-mode, javascript-mode, rust-mode, emacs-lisp-mode, etc. - is the "pro" a necessary disambiguator?

**Comment by rafaelcn** [comment]
@riscy, I wanted to leave the prefix `act-` to someone who might implement a good mode for the ACT language (not that I don't want to improve it and I'll shortly). I only intended, at first, to create a basic syntax highlighter while I was learning how to write act code. 

If that bothers you, I can change the mode's name to `act-mode`.

**Comment by riscy** [comment]
That is noble of you, but I think since there is currently only one "act" mode, you may as well use that prefix.

A better way to serve this goal (which I applaud) would just be to make the intention clear in your README and possibly even your `;;; Commentary`.  E.g. "This package strongly welcomes contributions from others.  Moreover, if you write a superior act-mode and don't want to contribute back to this package, I will be more than happy to archive this repository and facilitate updates to any package repositories, e.g. MELPA."

One reason "proact-mode" isn't so good is because some search engines won't pull the "act" token out of "proact", hampering discoverability.

**Comment by rafaelcn** [comment]
okay, I've changed everything to match the name `act`. let met know if there are anything that I can make better.

**Comment by riscy** [comment]
The filename for your recipe has a trailing space on it - I don't have edit access to your PR, otherwise I'd fix.

**Comment by riscy** [comment]
Thanks for that fix! Merging -

**Comment by tarsius** [comment]
@rafaelcn This package currently cannot be published on Melpa Stable because no new release was created since it was renamed. Please create a new release tag.

@riscy Please check for this when a package is being renamed during review. Thanks!

**Comment by tarsius** [comment]
Hm, I had a look at the code and don't think this should have been added.

Most importantly the mode is named `proact-mode`, but the entry added to `auto-mode-alist` is for `act-mode`. `proact-fontlock` is set using a top-level `setq`. Indentation is wrong. The `Commentary` section title is still misplaced and there is no actual commentary (even though you already brought that up above).

**Comment by tarsius** [comment]
But I have another request: Please complete the rename by creating a tag for a commit after the rename.

The issue that is fixed by that, is described in #8691.

**Comment by rafaelcn** [comment]
@tarsius I've created a new tag since the project rename, can you check to make sure everything is alright?

**Comment by tarsius** [comment]
Looks good now. Thanks!

**Comment by riscy** [comment]
> Please check for this when a package is being renamed during review. Thanks!

@tarsius Thanks for catching this!  I'll verify this going forward.

**Comment by riscy** [comment]
> Please complete the rename by creating a tag for a commit after the rename

I'll try to verify *this* rather.  Although now that I re-familiarize myself with this, this looks like it was a brand new package with no history on MELPA when I merged it.  I'll try to check this (and may be able to automate that check, even) but it seems like something major that we should put in CONTRIBUTING.org or similar.

**Comment by riscy** [comment]
Sorry to keep spamming you both with emails, but maybe the guideline here should be:

> if your repository has a history of tagged commits predating MELPA review, please create one more tag after making any major changes

This one should be easy to check for, and this would include renaming and other major patches to their code before it ends up on `stable`.

**Comment by tarsius** [comment]
> ... any major changes,

... such as renaming the package or adding new libraries that are distributed as separate packages.

I'm not sure this should be added to the guidelines. Without further details, authors might very well wonder why they should do that. And with more details, it could get quite noisy. IMO an automated check would be best (and then maybe some canned instructions, that you can copy-paste, when a new tag is actually necessary.)

**Comment by riscy** [comment]
Yes, as I looked through PR's today I was thinking that sort of guidance could be too much (and CONTRIBUTING.org is already quite large as it is).

Right now I've implemented a quick check to see if they are using tags already, and if so provide a reminder:
```python
reminder = f"- Reminder: ensure release {tags[0]['name']} is up-to-date with any changes"
```
and I'll flesh this out and/or add some canned instructions about all the ways in which this is important, including renaming/adding new libraries in the same repo.

**Comment by tarsius** [comment]
While we are at it, even more important is:

If you use both release tags and the `[Package-]Version` header, make sure to tag the commit that bumps the header with the corresponding tag.

If you originally forgot to create the tag, you can fix that by tagging the appropriate commit once you notice the discrepancy.

However, if you only tagged the release commit but forgot to bump the header, then you must create a new release to fix this. If you cannot create a new release just yet, then it is better to leave the defect as-is, instead of trying to fix it. That way different *elpa will provide different "latest" releases, e.g., [Non]GNU Elpa `1.1` and Melpa Stable `1.2`, but it would be much worse if both *elpa provided a `1.2` package, but those packages contained the code from two completely different revisions of the package. The latter is what would happen if you "fixed" the `Version` header in an arbitrary commit *following* the tagged release.

**Pull request merged**
