### PR TITLE
Add new recipe for evil-better-visual-line

### PR DESCRIPTION
**Pull request by YourFin**
### Brief summary of what the package does

Provides an improved experience on `evil-[next/previous]-visual-line` (common stand in j/k) in that it falls back to non-visual line movement in visual line and block mode

### Direct link to the package repository

https://github.com/yourfin/evil-better-visual-line

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

Got the package linting correctly!

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Looks good - merging now! Welcome to MELPA. :tada:

**Comment by tarsius** [comment]
I have renamed this to `evil-better-visual-line` because that is the actual name of the package.

**Comment by tarsius** [comment]
I just spend half an hour on this because Github says "You must be logged in to do that." when it should say "You cannot fork this either because it doesn't exist or because it is private repository, which we you don't have access. (In the latter case we would not want to disclose this information to you, so we have to be a bit fague)". So there I was trying to figure out why all those other things that require authentication work but not forking this. :rage:

**Comment by YourFin** [comment]
Sorry about that; I think I put this together rather late at night and forgot I had changed the name.

**Pull request merged**
