### PR TITLE
Add smithers recipe

### PR DESCRIPTION
**Pull request by mtekman**
### Brief summary of what the package does

This is a recreation of Waylon Smithers' startup message from the The Simpsons of Charles Montgomery Burns.
It depends on espeak to generate the WAV files.

### Direct link to the package repository

https://gitlab.com/mtekman/smithers.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, this looks like fun. :)  `checkdoc` is failing to nag about the long lines (I'm not sure why it's inconsistent about this), but the docstrings should probably be wrapped -- be aware that the Emacs online help does not know where to break words in long docstrings.  The `apropos` functionality likes it when the first line is a complete sentence, too.

Minor:
- smithers.el#L23: Use empty lines instead of `;;` on a line by itself within your Commentary

**Comment by mtekman** [comment]
Thanks - it was fun to make!

I have now `M-q`'d all docstrings and made the first sentence of each a short sentence. I also shifted the main `smithers--data` directory out of the package directory, since I think it will be easier to access and modify.

Hope that's everything -- as always, cheers for the tireless reviews!

**Comment by mtekman** [comment]
Hmm. I now see that I have a problem: the `source.org` file used to generate the media is not actually packaged with the code.

Do you know how I could enforce this?

**Comment by riscy** [comment]
Looks good, thanks!

**Pull request merged**
