### PR TITLE
Play Mode

### PR DESCRIPTION
**Pull request by bomgar**
Adds support for scala play. Currently the routes file is supported.

### CODE REVIEW

**Comment by syohex** [comment]
Your package does not follow Emacs packaging convention. Please read following links.
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Packaging-Basics.html
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Simple-Packages.html
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html

**Comment by bomgar** [comment]
I made some adjustments. Can you please check again?

**Comment by syohex** [comment]
- All variables/functions should start with package prefix, in this case `play-` or `play-mode` for avoiding name conflict. Emacs has only one namespace.
- Use `defvar` instead of `setq` for declaring global variables

**Comment by bomgar** [comment]
I made the changes you suggested. Thanks for your patience.

**Comment by purcell** [comment]
Cool, sent you some fixes in https://github.com/brocode/play-mode/pull/1.

I kinda feel like this package should simply be called `play-routes-mode`.

**Comment by bomgar** [comment]
I renamed the package and the repository. Thank you for your help. I'm new to elisp and trying to learn these things.

**Comment by purcell** [comment]
Awesome, thanks.

**Pull request merged**
