### PR TITLE
transfer ownership of 0x0 namespace

### PR DESCRIPTION
**Pull request by nackjicholson**
### Brief summary of what the package does

Upload files and text clips to https://0x0.st, https://envs.sh, https://ttm.sh, or any other self-hosted null-pointer server.

### Direct link to the package repository

https://gitlab.com/willvaughn/emacs-0x0.git

### Your association with the package
Hello MELPA Friends,

I would like to be the maintainer of this package and recipe. Switching this recipe to my fork of this project which has the same functionality (and a tiny bit more). The original author @phikal and I have spoken on IRC and discussed this transfer breifly.

```
    <nackjicholson> If I wanted this on MELPA do you think they'd let me make a new recipe or since our packages do
                    almost the same thing do you think they'll tell me to make updates to yours?                  [05:41]
             <pkal> From my experience, they are not that intersted in duplicate functionality
             <pkal> But, I was thinking about removing 0x0 from MELPA and adding a more general version to ELPA, so
                    maybe you could take over the 0x0 package name, if you are interested                         [05:42]
    <nackjicholson> Definitely interested!
```

We decided to put in a pull request to melpa in order to start the process and run it by the maintainers for approval. Please advise us on how to proceed.

Warm Regards,
Will

### Relevant communications with the upstream package maintainer

NONE NEEDED

### Checklist

**I will work on these when we know this transfer is moving forward.**

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by phikal** [comment]
Just wanted to confirm that I am ok with this.

**Comment by phikal** [comment]
Also, because you are hosting the package source on the official GitLab instance, you could probably use [`gitlab`](https://github.com/melpa/melpa/blob/master/README.md#recipe-format) as the fetcher type.

**Comment by Boruch-Baum** [comment]
Hi. In browsing the proposed new repository, I see that it includes an INSTALL section with the following snippet.

```
But, this is what I’ve done in my configs to customize my ix.io user credentials,
and set up some convenient key bindings.

(use-package! 0x0
  :config
  (setq 0x0-ixio-basic-auth-creds '(:user "..." :pass "..."))
```

That kind of advice scares me (and doesn't inspire confidence). Emacs has methods of storing secrets so that they don't need to be stored in plain-text or in one's init-file. I've opened an issue on the project's gitlab repository instance with links to two resources.

**Comment by nackjicholson** [comment]
I don't actually do that, I use auth-source gpg. I'll change the docs. Thanks for pointing that out

**Comment by nackjicholson** [comment]
@Boruch-Baum: Again, thank you. I hope this [commit](https://gitlab.com/willvaughn/emacs-0x0/-/commit/8851da1526f3893ec79c2b03e7eefb9b24e35712) will address the issue. Anything else I can do to help move forward?

**Comment by phikal** [comment]
Re-reading the source, I think it would be nice if you continued to support dependency-free upload (i.e. url, if curl is not installed). That was one of my motivations when writing 0x0.el in the first place, and I cannot say if any of its current users also depend on it.

**Comment by Boruch-Baum** [comment]
On 2021-06-28 20:43, Will Vaughn wrote:
>    [1]@Boruch-Baum: Again, thank you. I hope this [2]commit will address
>    the issue. Anything else I can do to help move forward?

I don't know, I'm a participator/contributor but not a judge/maintainer.
I did look at your fix and it does the job. Thank you.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by nackjicholson** [comment]
@phikal Yes I can get the `url` support back in. I removed it because the library currently does not work on any kind of multibyte data (like a PNG, JPG, PDF, etc). Sharing files of those types is my main use of this code, and as is it only works with `curl`. I tried but could not figure out how to make that work with `url-retrieve-synchronously`.

I realize this thread is the wrong place for a discussion about package bugs/features. If you want to talk about it more, get at me on IRC or email. To close the loop though, I'll add that functionality back in and write some documentation in the readme about the known bug / limitation.

**Comment by nackjicholson** [comment]
@phikal Maybe a simpler way to go about this is for me to put a patch with ALL of my changes to your fork, and for us to just keep this under your repo. We've come full circle. You could just make me a contributor to your sourcehut repo. Let me know what you think. If so, we can close this recipe change.

**Comment by phikal** [comment]
I am just brining this up for the sake of backwards compatibility, but you are right, general feature discussions should be held elsewhere.

> Maybe a simpler way to go about this is for me to put a patch with ALL of my changes to your fork, and for us to just keep this under your repo.

If you want to work on the package, there is nothing wrong with you just "forking" my repository, adding your changes, and updating the repo URL, so that you also have control over the issue tracker and the pull requests.

**Comment by nackjicholson** [comment]
@phikal Okay, so let's just keep going with this PR then? Transfer the repo to my fork on gitlab.

**Comment by riscy** [comment]
All looks good here.

**Pull request merged**
