### PR TITLE
Add recipe for nordic-night-theme

### PR DESCRIPTION
**Pull request by ashton314**
### Brief summary of what the package does

A modification (a fairly significant one, imo!) of the lovely Nord theme. This is a much higher-contrast version and employs the Nord palette more liberally for a vibrant development experience. :)

This is my first "real" package. I've tried my very best to follow the instructions—let me know if I'm missing anything though.

### Direct link to the package repository

https://sr.ht/~ashton314/nordic-night/

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

I've temporarily disabled the no-byte-compile flag (don't worry, it's correct to have that flag).  This is just to have the byte-compiler help with some standards:
```
nordic-night-theme.el:41:1: Warning: custom-declare-variable
    `nordic-night-uniform-mode-lines' docstring wider than 80 characters
nordic-night-theme.el:46:7: Warning: assignment to free variable
    `nordic-night-theme--brightened-comments'
nordic-night-theme.el:69:39: Warning: Unused lexical variable
    `nordic-night-lessdark3-3'
nordic-night-theme.el:90:39: Warning: Unused lexical variable
    `nordic-night-escape'
nordic-night-theme.el:613:84: Warning: Unused lexical variable
    `nordic-night-regexp'
nordic-night-theme.el:631:112: Warning: Unused lexical variable
    `nordic-night-region-highlight-foreground'
nordic-night-theme.el:96:64: Warning: Unused lexical variable
    `nordic-night-region-highlight-background'
```
I think the long docstring is easy to solve.  The assignment-to-free-variable should be solved by using `defvar` instead of `setq`.  It is okay that those variables are unused in the context of a theme, but maybe it's informative to know that they aren't being used.  (You can prefix them with a `_` as the standard indication that they're not used.)

Your license indicator inside the file, `;; License: MIT`, is a bit informal. Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to nordic-night-theme.el to fix this.

**Comment by ashton314** [comment]
@riscy I've addressed all the byte-compilation warnings and I've added an SPDX-License-Identifier. Thanks for the tips!

You can see the new source here (for any wishing to browse w/o pulling): https://git.sr.ht/~ashton314/nordic-night/tree/0.2.0

**Comment by riscy** [comment]
Thanks!  Merging.  And, welcome to MELPA. :)

**Comment by ashton314** [comment]
Woohoo! Thank you! It’s an honor!

**Pull request merged**
