### PR TITLE
add flymake-go-staticcheck recipe

### PR DESCRIPTION
**Pull request by s-kostyaev**
### Brief summary of what the package does

Flymake backend for Go using [staticcheck](https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck).

### Direct link to the package repository

https://github.com/s-kostyaev/flymake-go-staticcheck

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Just noticing that `checkdoc` gives me:
```
Warning (emacs): 
flymake-go-staticcheck.el:63: Some lines are over 80 columns wide
Warning (emacs): 
flymake-go-staticcheck.el:87: Some lines are over 80 columns wide
```
In the case of the first, some careful rewriting could make the first line a complete sentence.  In the case of the second, you can just run `M-q` on the docstring.

Here:
```elisp
(add-hook 'flymake-diagnostic-functions 'flymake-go-staticcheck--checker nil t))
```
You can actually sharp-quote the `#'flymake-go-staticcheck` which will make the compiler notice if you ever change the name of that function.

Very minor, but this line [here](https://github.com/s-kostyaev/flymake-go-staticcheck/blob/master/flymake-go-staticcheck.el#L67) could just be
```elisp
    (let (results) ...
```
since all you're after is an empty list (i.e. nil).

Also very minor, maybe it is time we began using `https` to link to gnu.org's licenses (in your frontmatter).  It's not a big deal but I thought I'd start pointing it out to people, since I think everyone copy-pastes this from each other.

**Comment by s-kostyaev** [comment]
@riscy thanks for review. Fixed.

**Comment by riscy** [comment]
- `flymake-go-staticcheck` feels like it's four words, not three -- why not `flymake-go-static-check`?  Or, the `check` is sort of implied.  What about `flymake-go-static`?
- `error` takes a string as an argument [here](https://github.com/s-kostyaev/flymake-go-staticcheck/blob/805e81282e6fd57e7cd564a823a9d797c2eabe8f/flymake-go-staticcheck.el#L59)- no need to wrap that string with `message`.
- You'll want to capitalize that string for checkdoc's sake -- and maybe you should be telling the user to run `customize-variable` instead of `set-variable`?
- `#'flymake-go-staticcheck--checker` is private by convention (contains `--`) but the expectation is to add it to a hook -- it should be a public function.
- Many people using flymake would probably prefer to simply add the hook to their configuration file -- should doing so be added to your documentation? Also, using `flymake-go-staticcheck-enable` in a configuration could cause strange things like flymake being enabled on the *scratch* buffer.  Perhaps leave it up to the user to enable `flycheck-mode` after calling that function?
- I don't know a lot about writing flymakes, but have you considered using [flymake-easy](https://github.com/purcell/flymake-easy)?

**Comment by s-kostyaev** [comment]
staticcheck is the name of the linter.

**Comment by s-kostyaev** [comment]
@riscy thanks for review. Fixed.

**Comment by riscy** [comment]
Awesome, thank you!

**Pull request merged**
