### PR TITLE
Add hidepw recipe.

### PR DESCRIPTION
**Pull request by jekor**
### Brief summary of what the package does

Minor mode for hiding passwords

### Direct link to the package repository

https://github.com/jekor/hidepw

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
I notice a similar package -- https://github.com/juergenhoetzel/password-mode/ -- all of your code looks great, but can you comment on any major differences?

**Comment by jekor** [comment]
Differences:

- Uses font-lock instead of overlays.
- Allows multiple passwords per line (or non-password text on the same line after the password).
- Does not require a special prompt to input passwords (which can be buggy).
- Passwords can be revealed if desired (by deleting a delimiter).

**Comment by riscy** [comment]
Awesome, thanks for making the check -- it may be worthwhile to add the comparison you just made to your README, as a service to users of your package and the community as a whole.

I'll be back for another look soon.

**Comment by jekor** [comment]
Thanks for the suggestion. I've added that to the README.

**Comment by purcell** [comment]
Looks good, thanks - merging now. :-)

Welcome to MELPA, @jekor, enjoyed your haskell videos a few years ago and hope you're doing well.

**Comment by jekor** [comment]
> Looks good, thanks - merging now. :-)
> 
> Welcome to MELPA, @jekor, enjoyed your haskell videos a few years ago and hope you're doing well.

Thanks @purcell . It's been a while for me, but good to see you're still active in the community.

**Pull request merged**
