### PR TITLE
Add recipe for flycheck-languagetool

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Flycheck/Flymake support for LanguageTool.

### Direct link to the package repository

https://github.com/emacs-languagetool/flycheck-languagetool

### Your association with the package

The maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks. Here's a very quick pass over the checklist.

### flycheck-languagetool.el ###

byte-compile (using Emacs 27.1):
```
flycheck-languagetool.el:99:1:Warning: Unused lexical argument `signal'
In flycheck-languagetool--async-shell-command-to-string:
flycheck-languagetool.el:99:81:Warning: `(output-buffer (generate-new-buffer "
    *temp*"))' is a malformed function
flycheck-languagetool.el:109:29:Warning: reference to free variable
    `output-buffer'
flycheck-languagetool.el:114:34:Warning: reference to free variable
    `callback-fun'
In end of data:
flycheck-languagetool.el:209:1:Warning: the following functions are not known
    to be defined: lexical-let, callback-fun
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- flycheck-languagetool.el#L28: Use empty lines instead of `;;` on a line by itself within your Commentary

**Comment by jcs090218** [comment]
> byte-compile (using Emacs 27.1):

Not sure how I resolve these warnings. Would `(require cl)` work?

> * flycheck-languagetool.el#L28: Use empty lines instead of ;; on a line by itself within your Commentary

How did you reproduce the linting result? I cannot see this warning with `package-lint-current-buffer`. 😕

**Comment by riscy** [comment]
> Not sure how I resolve these warnings. Would (require cl) work?

Yes, sorry about that -- I didn't dig too deeply on that first pass, and it seems like you needed a macro brought in if you're compiling with an instance of Emacs that hasn't (yet) brought in that package.  Looks like you made that change and it fixed the issue.

But instead of `(require 'cl)` you should `(require 'cl-lib)` -- here's the latest in that regard:

byte-compile (using Emacs 27.1):
```
flycheck-languagetool.el:35:30:Warning: Package cl is deprecated
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
1 issue found:
35:29: warning: Replace deprecated `cl' with `cl-lib'.  The `cl-libify' package can help with this.
```

> How did you reproduce the linting result?

There's a link in the original comment to [here](https://github.com/riscy/melpazoid), and that's just an additional check I added lately since I noticed many packages weren't following this convention and were rendering with an extra leading newline in the MELPA index.  Probably that's an issue to fix in MELPA, but I thought I'd start hinting it here in the meantime too.

**Comment by jcs090218** [comment]
> But instead of (require 'cl) you should (require 'cl-lib)

I think the issue is `lexical-let` does not appear in `cl-lib` and I could not find cl version of `lexical-let`. Maybe `cl-lexical-let`? 😕 

> There's a link in the original comment to here, and that's just an additional check I added lately since I noticed many packages weren't following this convention and were rendering with an extra leading newline in the MELPA index. Probably that's an issue to fix in MELPA, but I thought I'd start hinting it here in the meantime too.

Ah. okay. I think MELPA should solve this issue. Or else many packages may have to change to fix this issue. 😅

**Comment by riscy** [comment]
> I think the issue is lexical-let does not appear in cl-lib and I could not find cl version of lexical-let

In the first line of your file you set `lexical-binding: t` so it's unclear to me if you need really lexical-let.  I think you may have copied this function from some other source, in a different context where lexical-let was needed, but correct me if I'm wrong.

> Ah. okay. I think MELPA should solve this issue.  Or else many packages may have to change to fix this issue. 😅

Yes it's minor and I wouldn't ask any packages to fix it retroactively, but for your new packages it's an easy fix and tends to be in line with what you see in builtin Emacs sources.

**Comment by jcs090218** [comment]
> In the first line of your file you set lexical-binding: t so it's unclear to me if you need really lexical-let. I think you may have copied this function from some other source, in a different context where lexical-let was needed, but correct me if I'm wrong.

Yes, I copied from [here](https://lists.gnu.org/archive/html/help-gnu-emacs/2008-06/msg00032.html). And I realized that you are right. I can replace `lexical-let` with `let` and it would just work! Sorry for the confusion!

**Comment by riscy** [comment]
All good!  Thanks for this.

**Pull request merged**
