### PR TITLE
Add Japanese Vimtutor adapted to Evil

### PR DESCRIPTION
**Pull request by kenjimyzk**
- Summary: Japanese version of evil-tutor.el
- Link: https://github.com/kenjimyzk/evil-tutor-ja
- Association: I am the author

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR(https://github.com/kenjimyzk/evil-tutor-ja/pull/1) about package format.

And please fix package description(https://github.com/kenjimyzk/evil-tutor-ja/blob/master/evil-tutor-ja.el#L1). It looks copy of `evil-tutor.el`.

**Comment by kenjimyzk** [comment]
Thanks @syohex! I fixed them all.

**Comment by syohex** [comment]
Package description(https://github.com/kenjimyzk/evil-tutor-ja/blob/master/evil-tutor-ja.el#L1 ) is not fixed yet. I think it should contain **Japanese** like "Japanese Vimtutor adapted to Evil and wrapped in a major-mode" etc.

**Comment by kenjimyzk** [comment]
Thanks again, @syohex. I have fixed the first line in evil-tutor-ja.el.

**Comment by syohex** [comment]
Merged

**Pull request merged**
