### PR TITLE
Added a recipe of helm-find-project-files

### PR DESCRIPTION
**Pull request by shishimaru**
### Brief summary of what the package does

This package is like an extension of helm-find by enabling to quickly find files of the current working project by identifying the project root with .git or .svn or .projectroot file.

### Direct link to the package repository

https://github.com/shishimaru/helm-find-project-files.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Very quick first pass --

Emacs 28 added a fun warning:

`helm-find-project-files.el` with byte-compile using Emacs 28.1:
```
helm-find-project-files.el:45:8: Warning: docstring wider than 80 characters
```
This is fairly minor in practice but because it manifests as an actual compiler warning that users will see during install/byte-compile, I'd recommend fixing this.  You could break it up into two sentences or by rephrasing, e.g. `"Recursively search up from DIR to Find the project root."`

**Comment by shishimaru** [comment]
@riscy 
Thank you for checking and give the feeback.
I have fixed the docstring to be narrower than the 80 characters.
Could you review again ?

**Comment by riscy** [comment]
Thanks for accommodating -- there are some minor lints from checkdoc on this version:

`helm-find-project-files.el` with checkdoc 0.6.2:
```
helm-find-project-files.el:46: First line is not a complete sentence
helm-find-project-files.el:56: First line is not a complete sentence
helm-find-project-files.el:73: First line is not a complete sentence
```
which are good to get right because that can help the output of `M-x apropos`, but this is fairly minor.

With the checklist behind us, I was looking at similar packages:

- Have you seen https://melpa.org/#/helm-projectile ?  This seems to achieve all of what you want, albeit with a dependency on projectile
- Alternatively, I notice you are "reinventing" a lot of project-identification functionality e.g. with `helm-find-project-files-project-root-symbols '(".git" ".svn" ".projectroot")` but Emacs comes builtin with its own project.el nowadays, which includes helpful functions like `project-roots`; you should really be using this as a basis.  But that makes me wonder: if a user has helm activated, what happens when a user runs e.g. `project-find-file`?  Does that obviate a function like `helm-find-project-files-find`?

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out.

**Comment by shishimaru** [comment]
@riscy 
I am sorry for my late reply to your feedback.

> Have you seen https://melpa.org/#/helm-projectile ? This seems to achieve all of what you want, albeit with a dependency on projectile

Yes, I used to use it for a long time, but one day I observed my emacs got a terribly slow performance and found the bottleneck came from the projectile itself.
Therefore, my motivation was to create a small and light weight function to find project files with helm.

> Alternatively, I notice you are "reinventing" a lot of project-identification functionality e.g. with helm-find-project-files-project-root-symbols '(".git" ".svn" ".projectroot") but Emacs comes builtin with its own project.el nowadays, which includes helpful functions like project-roots; you should really be using this as a basis. But that makes me wonder: if a user has helm activated, what happens when a user runs e.g. project-find-file? Does that obviate a function like helm-find-project-files-find?

Thank you for the advice, and I understand the project-find-file is enough and my patch is not needed.
When I used the project-find-file with activating helm, it worked with helm interface and the feature was like my plugin.

Until I got your feedback, I didn't know these helpful functions, project-root, project-find-file.
Indeed, they are the ones I wanted !

Therefore, I decided to discard this PR !

**Comment by riscy** [comment]
Thank you very much for the thoughtful response - it's very modest of you and, in my opinion, great for the Emacs package ecosystem to hold back like this.  Appreciated. :)

**Pull request closed without merging**
