### PR TITLE
Add recipe for mu4e-overview

### PR DESCRIPTION
**Pull request by mkcms**
### Brief summary of what the package does

Shows an overview of Maildir using mu4e.

### Direct link to the package repository

https://github.com/mkcms/mu4e-overview

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Just a quick note re: package-lint:
```
9:1: error: Expected (package-name "version-num"), but found cl-lib.
```

**Comment by purcell** [comment]
Yep, just need to do this: https://github.com/mkcms/mu4e-overview/pull/1

This can be merged once that little fix is in.

**Comment by mkcms** [comment]
> Yep, just need to do this: [mkcms/mu4e-overview#1](https://github.com/mkcms/mu4e-overview/pull/1)
> 
> This can be merged once that little fix is in.

Thanks @purcell , I merged your changes.

**Comment by purcell** [comment]
Great, merged now, thanks!

**Pull request merged**
