### PR TITLE
recipes/lpy: Add

### PR DESCRIPTION
**Pull request by abo-abo**
### Brief summary of what the package does

A minimalist IDE for Python with quick navigation, outline and eval support.

### Direct link to the package repository

https://github.com/abo-abo/lpy

### Your association with the package

Maintainer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
I'm excited whenever I see a new package from you. :)  Below is quick pass through the checklist -- are there plans to do the checkdoc checks?



### lpy.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
- No issues! 💯

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs):
lpy.el:81: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:88: All interactive functions should have documentation
Warning (emacs):
lpy.el:116: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:129: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:132: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:136: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:140: All interactive functions should have documentation
Warning (emacs):
lpy.el:144: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:155: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:159: All interactive functions should have documentation
Warning (emacs):
lpy.el:175: All interactive functions should have documentation
Warning (emacs):
lpy.el:226: All interactive functions should have documentation
Warning (emacs):
lpy.el:254: Argument `def' should appear (as DEF) in the doc string
Warning (emacs):
lpy.el:266: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:275: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:298: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:305: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:310: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:315: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:355: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:361: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:370: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:396: All interactive functions should have documentation
Warning (emacs):
lpy.el:403: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:496: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:505: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:513: All interactive functions should have documentation
Warning (emacs):
lpy.el:531: All interactive functions should have documentation
Warning (emacs):
lpy.el:546: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:650: All interactive functions should have documentation
Warning (emacs):
lpy.el:664: All interactive functions should have documentation
Warning (emacs):
lpy.el:687: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:692: All interactive functions should have documentation
Warning (emacs):
lpy.el:741: All interactive functions should have documentation
Warning (emacs):
lpy.el:777: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:781: Argument `arg' should appear (as ARG) in the doc string
Warning (emacs):
lpy.el:816: All interactive functions should have documentation
Warning (emacs):
lpy.el:824: All interactive functions should have documentation
Warning (emacs):
lpy.el:836: All interactive functions should have documentation
Warning (emacs):
lpy.el:863: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:875: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:896: All interactive functions should have documentation
Warning (emacs):
lpy.el:905: All interactive functions should have documentation
Warning (emacs):
lpy.el:922: All interactive functions should have documentation
Warning (emacs):
lpy.el:941: All interactive functions should have documentation
Warning (emacs):
lpy.el:951: All interactive functions should have documentation
Warning (emacs):
lpy.el:967: All interactive functions should have documentation
Warning (emacs):
lpy.el:1028: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:1100: All interactive functions should have documentation
Warning (emacs):
lpy.el:1139: All interactive functions should have documentation
Warning (emacs):
lpy.el:1150: All interactive functions should have documentation
Warning (emacs):
lpy.el:1159: All interactive functions should have documentation
Warning (emacs):
lpy.el:1183: All interactive functions should have documentation
Warning (emacs):
lpy.el:1253: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:1262: All interactive functions should have documentation
Warning (emacs):
lpy.el:1289: All variables and subroutines might as well have a documentation string
Warning (emacs):
lpy.el:1302: All interactive functions should have documentation
Warning (emacs):
lpy.el:1315: All interactive functions should have documentation
Warning (emacs):
lpy.el:1330: All interactive functions should have documentation
Warning (emacs):
lpy.el:1346: All interactive functions should have documentation
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191220.419):
- No issues! 💯

Other static checks/suggestions:
- lpy.el#L237: It's safer to sharp-quote function names; use `#'`
- lpy.el#L1307: It's safer to sharp-quote function names; use `#'`
- lpy.el#L1308: It's safer to sharp-quote function names; use `#'`
- lpy.el#L1285: Consider `unless ...` instead of `when (null ...)`
### soap.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
- Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems)
- Lexical binding has been enabled
- No issues! 💯

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs):
soap.el:85: All interactive functions should have documentation
Warning (emacs):
soap.el:106: Argument `arg' should appear (as ARG) in the doc string
```

(Skipping package-lint on this file)

<details><summary>Misc...</summary>

### Maintainer/license

- PR by abo-abo: https://github.com/abo-abo/lpy
- License appears to be written into individual files
- Package-Requires mismatch in _elisp/soap.el!

### Summary

- (lpy :repo "abo-abo/lpy" :fetcher github) 
- Package-Requires: lispy "0.27.0", emacs "25.1"
- _elisp/soap.el (gpl): Smart Operator a posteriori
- _elisp/lpy.el (gpl): A lispy interface to Python
</details>

**Comment by riscy** [comment]
Hi!  I thought I'd ping you on this one -- your packages are always stunning. :)

I believe the most important checkdocs are to do with adding documentation to the interactive functions in lpy.el.  There's also the question of the package's prefix (should it be soap, or lpy, or are those two el files separate packages?).  No hurry, and please feel free to ping.

**Comment by abo-abo** [comment]
@riscy Thanks, I've fixed the checkdoc issues. Only the `soap-` or `lpy-` prefix issue remains. I'll ping back when it's fixed.

**Comment by tarsius** [comment]
@riscy Could you please explain why you remove the `awaiting-upstream` label in such cases? While we can be much more confident that they will do what is necessary fairly soon, we never-the-less *still* waiting for upstream to do something before we can merge.

**Comment by riscy** [comment]
Yeah, I was too quick on the trigger with that one (and another PR that's currently not awaiting upstream).  I'll set it back to await the ping!

**Comment by riscy** [comment]
Actually, it looks like the prefix issue is resolved -- there is a non-blocking nag from package-lint (more of an fyi):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```
And also a nudge to use a LICENSE file that [common tools](https://github.com/licensee/licensee) can detect (per a recentish change in CONTRIBUTING.org).  But I don't think any of these should be blockers.

**Pull request merged**
