### PR TITLE
Add recipe for journalctl-mode.

### PR DESCRIPTION
**Pull request by SebastianMeisel**
### Brief summary of what the package does

[Please write a quick summary of the package.]

### Direct link to the package repository

https://github.com/SebastianMeisel/journalctl-mode

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This looks good -- here's a first pass:

### journalctl-mode.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
journalctl-mode.el:256: White space found at end of line
```

package-lint-current-buffer (using version 20200419.406):
- No issues!

Some other stuff:
- Be cautious with dispatching `shell-command-to-string` with user-given parameters that haven't been passed through `shell-quote-argument` (for example on line 134).  What will happen if the user inputs a parameter that has shell-interpretable characters in it?
- When you call `read-string`, the prompt should (at least) end with a space so that the input and the output are separate from each other
- journalctl-mode.el#L339: You don't need to setq the major-mode, or the mode-name, or specify the keymap, since you are using `define-derived-mode` -- double check its documentation to see what it will handle automatically for you.
- journalctl-mode.el#L9: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by SebastianMeisel** [comment]
I corrected most of the mentioned problems.

> Be cautious with dispatching shell-command-to-string with user-given parameters that haven't been passed through shell-quote-argument (for example on line 134). What will happen if the user inputs a parameter that has shell-interpretable characters in it?


I can't easily use `shell-quote-argument` because I'd need to process each argument (split the string?). Or am I getting this wrong.
Is that a real threat? Using this function does only make sense when you know the arguments to use.

I'm planning to implement a function to process the parameters and check them for a future version, as this would also allow to easily remove certain options. But that will take sometime.

**Comment by riscy** [comment]
> I can't easily use shell-quote-argument because I'd need to process each argument (split the string?). Or am I getting this wrong.

Yeah, probably it's safe in this case -- if you wanted to do so you could use something like:
```elisp
(defun journalctl (&optional flags chunk)
  "Run journalctl with give FLAGS and present CHUNK of  output in a special buffer."
  (interactive)
  (let* ((param (or flags (read-string "parameter: " "-x -n 1000" nil "-x ")))
         (param (mapconcat #'shell-quote-argument (split-string param) " ")))
   ...
```
I think it's not that big a deal in this case, but it's a small way to prevent users from inadvertently interacting with the shell, and consistently used it can make your programs safer.

I think mostly everything else looks good, but why does `journalctl-mode` derive from `c-mode`?  It seems like `fundamental-mode` would be more appropriate.

**Comment by SebastianMeisel** [comment]
I changed `journalctl-mode` so it derives from `fundamental-mode`. 
I also wrote a simple option parser, that checks that only valid options are given. It doesn't yet check the values gives to options, but it puts all these values in single quotes, so they are not interpreted by the shell. This should address the shell-quote problem.

**Comment by riscy** [comment]
Great, thanks.  You've got one last nag from package-lint, but I don't consider it a blocker:
```
1 issue found:
146:3: warning: Closing parens should not be wrapped onto new lines.
```

I may have missed this the last time around, but usually your mode's name would not include the `mode suffix, so:
```elisp
(define-derived-mode journalctl-mode fundamental-mode "journalctl mode"
```
would more conventionally be
```elisp
(define-derived-mode journalctl-mode fundamental-mode "journalctl"
```
Thanks for this.

**Pull request merged**
