### PR TITLE
Add recipe for simplecov

### PR DESCRIPTION
**Pull request by zenspider**
### Brief summary of what the package does

ruby code coverage display via overlays

### Direct link to the package repository

https://github.com/zenspider/simplecov.el

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for your close adherence to the checklist - the only standout issues I see:

- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee
- Using `->` as a separator is nonstandard and therefore discouraged; I believe the only reason `package-lint` admits these is for `>`'s use in numerics, e.g. something like `floating-point->`
- (Minor): instead of e.g. writing ``` `COVERAGE' ``` in your docstrings, just write `COVERAGE`; the back/front quotes are used to create hyperlinks in the builtin help; they won't do anything in this case since there's no function called COVERAGE, but they're also unnecessary; capitalizing is sufficient

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out!

**Comment by zenspider** [comment]
Added license file and fixed docstrings.

I'm keeping `->` as part of my function names since they're all transformers and it makes me happy to work in a language that allows for truly descriptive names.

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
