### PR TITLE
Add contextual-menubar

### PR DESCRIPTION
**Pull request by aaronjensen**
### Brief summary of what the package does

Displays the menubar if on a graphical display, but hides it if in a terminal.
It works for multiple frames on the same server.

### Direct link to the package repository

https://github.com/aaronjensen/contextual-menubar

### Your association with the package

maintainer

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, this is handy, but you've got references to `eslint_d` in the description line and README, which have presumably been copied from elsewhere. Please ping me here when those are fixed so I can merge.

Also, rather than use `require` to enable this feature, you should probably instead provide an autoloaded command which executes the `add-hook` form. That way people can add that command to their init file or `after-init-hook` etc., or they can (potentially) `require` the library to use `contextual-menubar-show-or-hide-menubar` without it automatically modifying `after-make-frame-functions`.

**Comment by aaronjensen** [comment]
Thanks @purcell. Is there a typical name for an installation command like you mention? Would something like `contextual-menubar-install-hook` be ok?

**Comment by aaronjensen** [comment]
I've updated the repo, please let me know if that looks ok. Thanks!

**Comment by yassinphilip** [comment]
@aaronjensen The header line "baseline" part still is : "use eslint_d to automatically fix js files" when that is not what the package does, it looks like some commit message..?

**Comment by aaronjensen** [comment]
ah, oops. Thanks. Ok, I've searched for eslint and don't see anymore, but please let me know if you see anything else. Sorry 😖

**Comment by yassinphilip** [comment]
> please let me know if you see anything else. 
Yes ; The filename/baseline header line must be on a single line, and not wrapped over two like it is now. Also, Capitalizing the first word would not hurt.
> Sorry
No PB, thanks for contributing!

**Comment by aaronjensen** [comment]
Ok, fixed up. And yes, it did, but I did not rerun it after adding that function. It passes `checkdoc` and `package-lint` now.

**Comment by purcell** [comment]
Thanks. I'll go ahead and merge this now, but I strongly suggest you rename `contextual-menubar-install-hook` to `contextual-menubar-install`.

**Pull request merged**
