### PR TITLE
Add recipe for eshell-outline

### PR DESCRIPTION
**Pull request by jamzattack**
### Brief summary of what the package does

`eshell-outline-mode` defines a few commands to integrate
`outline-minor-mode` into `eshell`.  Some eshell-specific keys have
been rebound so that they have multiple uses.

### Direct link to the package repository

https://git.jamzattack.xyz/eshell-outline

git://jamzattack.xyz/eshell-outline.git

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by jamzattack** [comment]
oops, markdown copy/paste jank, sorry

**Comment by riscy** [comment]
This looks cool.  Just some minor nags:

byte-compile (using Emacs 26.3):
```
eshell-outline.el:62:30:Warning: reference to free variable
    `eshell-prompt-regexp'
In eshell-outline-narrow:
eshell-outline.el:120:34:Warning: reference to free variable
    `eshell-prompt-regexp'
```
Interestingly these aren't brought in when we `(require 'eshell)` but if you `(require 'em-prompt)` or `(defvar em-prompt)` you can clean up the compiler warnings.

**Comment by jamzattack** [comment]
Just pushed an update with dummy variables.

Turns out `eshell-last-input-start` also resulted in a warning in 28,
but not 26.

Cheers

**Comment by riscy** [comment]
Great, thanks - instead of this:
```elisp
(defvar eshell-last-input-start nil)
(defvar eshell-prompt-regexp nil)
```
You should use:
```elisp
(defvar eshell-last-input-start)
(defvar eshell-prompt-regexp)
```
which will prevent the byte-compiler from complaining about giving these values.

**Comment by jamzattack** [comment]
My bad, was a slip of the fingers...

Sorted now, thanks.

**Comment by riscy** [comment]
Great.  Thanks for this, and welcome to MELPA!

**Pull request merged**
