### PR TITLE
Add panda-mode recipe

### PR DESCRIPTION
**Pull request by thechampagne**
### Brief summary of what the package does

Syntax highlighting for the Panda programming language.

### Direct link to the package repository

https://github.com/thechampagne/panda-mode

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Hi @thechampagne - all of these major modes are definitely going to be appreciated by their respective communities, but keep in mind I'm limiting myself to trying to do one review per author per week, so you'll face a growing backlog, at least where my reviews are concerned.

But I would also recommend slowing down and spending more time on each individual language mode.  For a first-time contributor of a major mode, I'd say it's fine to skip implementing an `indent-line-function`, but if you're planning on maintaining many of these recipes you should look into implementing it; you could take inspiration from other major mode recipes.  Since pandas is a C-like jvm language with optional semicolons, you could take a look at [how groovy-mode](https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes/blob/bf732d367b16887f81d404481c11ed1a58671d4e/groovy-mode.el#L832) does it as a start.

**Comment by thechampagne** [comment]
The only thing i care about for now is highlight the syntax.

**Comment by riscy** [comment]
> The only thing i care about for now is highlight the syntax.

I've merged a few more of your major modes in, but (in my opinion) by indexing these in MELPA for other users, you should adopt an attitude where you care about what other typical users would want and expect.

In the case of this recipe, there is unfortunately a namespace clash with the existing https://melpa.org/#/panda -- perhaps a better name for this package would be panda-lang-mode?  (The Panda language itself uses panda-lang in its website URL to disambiguate as well.)

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out.

**Comment by progfolio** [comment]
@thechampagne Are you still interested in submitting this package to MELPA? Do you plan to extend it any more?

**Pull request closed without merging**
