### PR TITLE
Add orgmdb recipe

### PR DESCRIPTION
**Pull request by isamert**
### Brief summary of what the package does

A watchlist/movie-list manager and an [OMDB](http://omdbapi.com/) client for Emacs and org-mode.

### Direct link to the package repository

https://github.com/isamert/orgmdb.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

 **None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`orgmdb.el` with checkdoc 0.6.2:
```
orgmdb.el:203: Argument `title' should appear (as TITLE) in the doc string
orgmdb.el:267: All variables and subroutines might as well have a documentation string
orgmdb.el:345: All variables and subroutines might as well have a documentation string
orgmdb.el:371: All variables and subroutines might as well have a documentation string
orgmdb.el:384: All variables and subroutines might as well have a documentation string
orgmdb.el:451: All variables and subroutines might as well have a documentation string
orgmdb.el:542: All variables and subroutines might as well have a documentation string
orgmdb.el:548: All variables and subroutines might as well have a documentation string
orgmdb.el:613: All variables and subroutines might as well have a documentation string
orgmdb.el:625: All variables and subroutines might as well have a documentation string
orgmdb.el:675: All interactive functions should have documentation
orgmdb.el:691: All variables and subroutines might as well have a documentation string
orgmdb.el:714: All variables and subroutines might as well have a documentation string
```

**Comment by isamert** [comment]
Just copying what I wrote on #8431:
> If possible, I would like to keep _internal_ functions and variables undocumented. Because they tend to change and documentation starts to lag behind which causes confusion for the reader.

**Comment by riscy** [comment]
Noted.  Re: #8431, I try to limit myself to one PR pr author each cycle, but the issues between these two PRs are related (and pending discussion in #8450).

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
