### PR TITLE
Add recipie for liso-theme

### PR DESCRIPTION
**Pull request by caisah**
Dark theme inspired by TangoTango.

### CODE REVIEW

**Comment by milkypostman** [comment]
only think @purcell will have to comment on is the part that changes ansi colors.

https://github.com/caisah/liso-theme/blob/master/liso-theme.el#L309

**Comment by purcell** [comment]
> only think @purcell will have to comment on is the part that changes ansi colors.

Yes, those and the top-level `setq-default` forms are invalid for a theme. You want those variables applied when the theme is enabled, not just the first time it's loaded. So use `custom-theme-set-variables` instead.

**Comment by caisah** [comment]
Thanks! I've made the changes, I hope it's ok now.

**Comment by purcell** [comment]
Super, thanks.

**Pull request merged**
