### PR TITLE
Add meow

### PR DESCRIPTION
**Pull request by DogLooksGood**
### Brief summary of what the package does

Modal Editing On Wheel, for Dvorak and Colemak

### Direct link to the package repository

https://github.com/DogLooksGood/meow

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by DogLooksGood** [comment]
something seems not clear to me, should I add version and dependency to every file? And is it every function should start with a prefix according to its file name? for example, `meow-util--some-util-func`.

**Comment by riscy** [comment]
Thanks for this!

> should I add version and dependency to every file?

Nope, just your "main" file (meow.el in this case) needs to have `Package-Requires`.  You're only required to prefix all your functions/variables in all files with `meow-` -- it doesn't have to be prefixed with the full filename.

In the next comment I'll give you the output of all the checks to refer to.

**Comment by riscy** [comment]
### meow-command.el ###

byte-compile-file (using Emacs 26.3):
```
meow-command.el:27:33:Warning: `(cmd (key-binding (read-kbd-macro
    kbd-macro)))' is a malformed function
meow-command.el:30:25:Warning: reference to free variable `cmd'
In meow--pop-selection:
meow-command.el:34:9:Warning: reference to free variable
    `meow--selection-history'
meow-command.el:35:21:Warning: assignment to free variable
    `meow--selection-history'
In meow--select:
meow-command.el:44:22:Warning: `((sel-type pos mark) selection)' is a
    malformed function
meow-command.el:49:9:Warning: reference to free variable `meow--selection'
meow-command.el:50:31:Warning: reference to free variable
    `meow--selection-history'
meow-command.el:53:13:Warning: assignment to free variable
    `meow--selection-history'
meow-command.el:54:16:Warning: reference to free variable `pos'
meow-command.el:55:11:Warning: reference to free variable `sel-type'
meow-command.el:56:18:Warning: reference to free variable `mark'
meow-command.el:57:13:Warning: assignment to free variable `meow--selection'
In meow--select-without-history:
meow-command.el:59:38:Warning: `((sel-type point mark) selection)' is a
    malformed function
meow-command.el:61:21:Warning: reference to free variable `point'
meow-command.el:63:14:Warning: reference to free variable `sel-type'
meow-command.el:68:18:Warning: reference to free variable `mark'
meow-command.el:69:13:Warning: assignment to free variable `meow--selection'
In meow--cancel-selection:
meow-command.el:73:9:Warning: assignment to free variable
    `meow--selection-history'
meow-command.el:74:9:Warning: assignment to free variable `meow--selection'
In meow-undo:
meow-command.el:84:30:Warning: reference to free variable `meow--kbd-undo'
In meow-backward-word:
meow-command.el:90:4:Warning: `((beg . _) (bounds-of-thing-at-point (quote
    word)))' is a malformed function
meow-command.el:96:28:Warning: reference to free variable `beg'
meow-command.el:99:49:Warning: reference to free variable `n'
meow-command.el:101:51:Warning: assignment to free variable `pos'
meow-command.el:101:51:Warning: reference to free variable `pos'
meow-command.el:101:46:Warning: assignment to free variable `mark'
meow-command.el:101:46:Warning: reference to free variable `mark'
meow-command.el:102:14:Warning: meow--select called with 0 arguments, but
    requires 1
In meow-mark-word:
meow-command.el:107:4:Warning: `((beg . _) (bounds-of-thing-at-point (quote
    word)))' is a malformed function
meow-command.el:114:22:Warning: reference to free variable `beg'
meow-command.el:119:51:Warning: assignment to free variable `pos'
meow-command.el:117:19:Warning: reference to free variable `n'
meow-command.el:119:46:Warning: assignment to free variable `mark'
meow-command.el:119:46:Warning: reference to free variable `mark'
meow-command.el:119:36:Warning: reference to free variable `pos'
meow-command.el:120:14:Warning: meow--select called with 0 arguments, but
    requires 1
In meow-forward-word:
meow-command.el:134:4:Warning: `((_ . end) (bounds-of-thing-at-point (quote
    word)))' is a malformed function
meow-command.el:143:17:Warning: meow--select called with 0 arguments, but
    requires 1
meow-command.el:146:19:Warning: reference to free variable `end'
meow-command.el:151:16:Warning: reference to free variable `n'
meow-command.el:151:16:Warning: assignment to free variable `pos'
meow-command.el:151:16:Warning: reference to free variable `pos'
meow-command.el:154:24:Warning: assignment to free variable `mark'
meow-command.el:154:24:Warning: reference to free variable `mark'
meow-command.el:156:39:Warning: meow--select called with 0 arguments, but
    requires 1
In meow-head-select:
meow-command.el:177:10:Warning: meow--select called with 0 arguments, but
    requires 1
In meow-tail-select:
meow-command.el:195:10:Warning: meow--select called with 0 arguments, but
    requires 1
In meow-prev-line-select:
meow-command.el:210:10:Warning: meow--select called with 0 arguments, but
    requires 1
In meow-next-line-select:
meow-command.el:225:10:Warning: meow--select called with 0 arguments, but
    requires 1
In meow-exp:
meow-command.el:243:4:Warning: `(exchange (< (prefix-numeric-value arg) 0))'
    is a malformed function
meow-command.el:243:4:Warning: `((beg . end) (bounds-of-thing-at-point (quote
    sexp)))' is a malformed function
meow-command.el:247:12:Warning: region-end called with 1 argument, but accepts
    only 0
meow-command.el:255:13:Warning: reference to free variable `exchange'
meow-command.el:257:21:Warning: reference to free variable `end'
meow-command.el:260:50:Warning: reference to free variable `n'
meow-command.el:264:21:Warning: assignment to free variable `pos'
meow-command.el:265:44:Warning: reference to free variable `pos'
meow-command.el:270:15:Warning: assignment to free variable `mark'
meow-command.el:262:34:Warning: reference to free variable `beg'
meow-command.el:278:26:Warning: reference to free variable
    `direction-backward'
meow-command.el:282:7:Warning: reference to free variable `mark'
meow-command.el:287:14:Warning: meow--select called with 0 arguments, but
    requires 1
meow-command.el:287:14:Warning: meow--select called with 0 arguments, but
    requires 1
In meow-line:
meow-command.el:293:4:Warning: `(exchange (< (prefix-numeric-value arg) 0))'
    is a malformed function
meow-command.el:329:33:Warning: reference to free variable `exchange'
meow-command.el:326:14:Warning: assignment to free variable `end'
meow-command.el:323:36:Warning: reference to free variable `n'
meow-command.el:318:20:Warning: assignment to free variable `beg'
meow-command.el:329:14:Warning: reference to free variable
    `direction-backward'
meow-command.el:329:14:Warning: reference to free variable `beg'
meow-command.el:331:20:Warning: reference to free variable `end'
meow-command.el:333:13:Warning: assignment to free variable `pos'
meow-command.el:334:37:Warning: assignment to free variable `mark'
meow-command.el:334:10:Warning: reference to free variable `mark'
meow-command.el:334:10:Warning: reference to free variable `pos'
meow-command.el:335:10:Warning: meow--select called with 0 arguments, but
    requires 1
In meow--block-indent-fallback:
meow-command.el:371:12:Warning: meow--select called with 0 arguments, but
    requires 1
In meow-block:
meow-command.el:375:4:Warning: `((beg . end) (bounds-of-thing-at-point (quote
    list)))' is a malformed function
meow-command.el:394:18:Warning: meow--select called with 0 arguments, but
    requires 1
meow-command.el:391:8:Warning: reference to free variable `beg'
meow-command.el:392:23:Warning: reference to free variable `end'
meow-command.el:392:23:Warning: meow--select called with 0 arguments, but
    requires 1
meow-command.el:395:39:Warning: reference to free variable
    `meow-indent-block-parser-mode-list'
In meow--flip-begin-of-comment:
meow-command.el:413:9:Warning: meow--make-selection called with 2 arguments,
    but requires 3
meow-command.el:414:9:Warning: meow--select called with 0 arguments, but
    requires 1
In meow--flip-end-of-comment:
meow-command.el:420:8:Warning: meow--make-selection called with 2 arguments,
    but requires 3
meow-command.el:421:8:Warning: meow--select called with 0 arguments, but
    requires 1
In meow--flip-begin-of-string:
meow-command.el:429:9:Warning: meow--make-selection called with 2 arguments,
    but requires 3
meow-command.el:430:9:Warning: meow--select called with 0 arguments, but
    requires 1
In meow--flip-end-of-string:
meow-command.el:438:9:Warning: meow--make-selection called with 2 arguments,
    but requires 3
meow-command.el:439:9:Warning: meow--select called with 0 arguments, but
    requires 1
In meow--flip-begin:
meow-command.el:441:8:Warning: `((_ . end) (bounds-of-thing-at-point (quote
    sexp)))' is a malformed function
meow-command.el:449:27:Warning: reference to free variable `end'
meow-command.el:454:9:Warning: meow--make-selection called with 2 arguments,
    but requires 3
meow-command.el:455:9:Warning: meow--select called with 0 arguments, but
    requires 1
In meow--flip-end:
meow-command.el:457:8:Warning: `((beg . _) (bounds-of-thing-at-point (quote
    sexp)))' is a malformed function
meow-command.el:466:23:Warning: reference to free variable `beg'
meow-command.el:471:9:Warning: meow--make-selection called with 2 arguments,
    but requires 3
meow-command.el:472:9:Warning: meow--select called with 0 arguments, but
    requires 1
In meow--toggle-near-far:
meow-command.el:521:12:Warning: meow--select called with 0 arguments, but
    requires 1
meow-command.el:521:12:Warning: meow--select called with 0 arguments, but
    requires 1
In meow--forwarding-comment:
meow-command.el:533:39:Warning: `(pos (re-search-backward "\\s<" nil t 1))' is
    a malformed function
meow-command.el:533:39:Warning: `(pos (re-search-forward "\\s>" nil t 1))' is
    a malformed function
meow-command.el:541:41:Warning: reference to free variable `pos'
In meow-find-ref:
meow-command.el:600:28:Warning: reference to free variable
    `meow--kbd-find-ref'
In meow-pop-marker:
meow-command.el:605:28:Warning: reference to free variable
    `meow--kbd-pop-marker'
In meow-copy:
meow-command.el:619:34:Warning: reference to free variable
    `meow--kbd-kill-ring-save'
In meow-yank:
meow-command.el:625:28:Warning: reference to free variable `meow--kbd-yank'
In meow-yank-pop:
meow-command.el:630:28:Warning: reference to free variable
    `meow--kbd-yank-pop'
In meow-keyboard-quit:
meow-command.el:639:30:Warning: reference to free variable
    `meow--kbd-keyboard-quit'
In meow-comment:
meow-command.el:653:28:Warning: reference to free variable `meow--kbd-comment'
In meow-kill:
meow-command.el:661:32:Warning: reference to free variable
    `meow--kbd-kill-line'
meow-command.el:669:34:Warning: reference to free variable
    `meow--kbd-kill-region'
In meow-join:
meow-command.el:676:28:Warning: reference to free variable
    `meow--kbd-delete-indentation'
In meow-delete:
meow-command.el:681:28:Warning: reference to free variable
    `meow--kbd-delete-char'
In meow-zap:
meow-command.el:688:30:Warning: reference to free variable
    `meow--kbd-kill-region'
meow-command.el:700:44:Warning: reference to free variable
    `meow--kbd-just-one-space'
In meow-insert-replace:
meow-command.el:730:30:Warning: reference to free variable
    `meow--kbd-kill-region'
In meow-insert-exit:
meow-command.el:748:5:Warning: reference to free variable `meow-keypad-mode'
meow-command.el:750:5:Warning: reference to free variable `meow-insert-mode'
In meow-page-up:
meow-command.el:760:28:Warning: reference to free variable
    `meow--kbd-scoll-down'
In meow-page-down:
meow-command.el:765:28:Warning: reference to free variable
    `meow--kbd-scoll-up'
In meow-forward-slurp:
meow-command.el:772:28:Warning: reference to free variable
    `meow--kbd-forward-slurp'
In meow-backward-slurp:
meow-command.el:777:28:Warning: reference to free variable
    `meow--kbd-backward-slurp'
In meow-forward-barf:
meow-command.el:782:28:Warning: reference to free variable
    `meow--kbd-forward-barf'
In meow-backward-barf:
meow-command.el:787:28:Warning: reference to free variable
    `meow--kbd-backward-barf'
In meow-raise-sexp:
meow-command.el:792:28:Warning: reference to free variable
    `meow--kbd-raise-sexp'
In meow-transpose-sexp:
meow-command.el:797:28:Warning: reference to free variable
    `meow--kbd-transpose-sexp'
In meow-split-sexp:
meow-command.el:802:28:Warning: reference to free variable
    `meow--kbd-split-sexp'
In meow-join-sexp:
meow-command.el:807:28:Warning: reference to free variable
    `meow--kbd-join-sexp'
In meow-splice-sexp:
meow-command.el:812:28:Warning: reference to free variable
    `meow--kbd-splice-sexp'
In meow-wrap-round:
meow-command.el:817:28:Warning: reference to free variable
    `meow--kbd-wrap-round'
In meow-wrap-square:
meow-command.el:822:28:Warning: reference to free variable
    `meow--kbd-wrap-square'
In meow-wrap-curly:
meow-command.el:827:28:Warning: reference to free variable
    `meow--kbd-wrap-curly'
In meow-wrap-string:
meow-command.el:832:28:Warning: reference to free variable
    `meow--kbd-wrap-string'
In meow-M-x:
meow-command.el:840:28:Warning: reference to free variable
    `meow--kbd-excute-extended-command'
In meow-back-to-indentation:
meow-command.el:845:28:Warning: reference to free variable
    `meow--kbd-back-to-indentation'
In meow-indent:
meow-command.el:850:28:Warning: reference to free variable
    `meow--kbd-indent-region'
In meow-search:
meow-command.el:854:4:Warning: `((marker-beg marker-end) (match-data))' is a
    malformed function
meow-command.el:858:36:Warning: reference to free variable `meow--last-search'
meow-command.el:862:82:Warning: reference to free variable `marker-end'
meow-command.el:862:53:Warning: reference to free variable `marker-beg'
meow-command.el:863:40:Warning: reference to free variable `beg'
meow-command.el:863:40:Warning: reference to free variable `end'
meow-command.el:864:18:Warning: meow--select called with 0 arguments, but
    requires 1
In meow-visit:
meow-command.el:880:4:Warning: `((marker-beg marker-end) (match-data))' is a
    malformed function
meow-command.el:890:90:Warning: reference to free variable `marker-end'
meow-command.el:890:61:Warning: reference to free variable `marker-beg'
meow-command.el:891:36:Warning: reference to free variable `beg'
meow-command.el:891:36:Warning: reference to free variable `end'
meow-command.el:892:14:Warning: meow--select called with 0 arguments, but
    requires 1
meow-command.el:893:13:Warning: assignment to free variable
    `meow--last-search'
In meow-query-replace:
meow-command.el:899:32:Warning: reference to free variable
    `meow--kbd-query-replace'
meow-command.el:900:30:Warning: reference to free variable
    `meow--kbd-query-replace-regexp'
In meow-escape-or-normal-modal:
meow-command.el:923:5:Warning: reference to free variable `meow-keypad-mode'
meow-command.el:925:5:Warning: reference to free variable `meow-insert-mode'
In meow-space:
meow-command.el:933:9:Warning: reference to free variable
    `meow--space-command'
In meow-eval-last-exp:
meow-command.el:938:28:Warning: reference to free variable
    `meow--kbd-eval-last-exp'
In end of data:
meow-command.el:943:1:Warning: the following functions are not known to be
    defined: when-let, -let, n, pos, ->, meow--selection-type,
    meow--direction-forward, -let*, region-beg, direction-backward,
    meow--direction-backward-p, beg, end, xor, meow--direction-backward,
    meow--get-indent, meow--empty-line-p, meow--in-string-p, ->>,
    meow--in-comment-p, meow--switch-state, company--active-p, company-abort,
    meow-keypad-mode, meow--prompt-symbol-and-words
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
meow-command.el:896: Argument `arg' should appear (as ARG) in the doc string
Warning (emacs): 
meow-command.el:865: Error messages should *not* end with a period
```

package-lint-current-buffer (using version 20200408.203):
- No issues!


### meow-core.el ###

byte-compile-file (using Emacs 26.3):
```
meow-core.el:65:4:Warning: `(sel-type (meow--selection-type))' is a malformed
    function
meow-core.el:83:31:Warning: reference to free variable `sel-type'
In end of data:
meow-core.el:108:1:Warning: the following functions are not known to be
    defined: meow--insert-init, meow--normal-init, meow--keypad-init,
    meow--motion-init, meow--enable, meow--disable,
    meow--keypad-format-prefix, meow--keypad-format-keys,
    meow--direction-backward-p, when-let
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
meow-core.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
meow-core.el:22: You should have a section marked ";;; Code:"
Warning (emacs): 
meow-core.el:65: All interactive functions should have documentation
```

package-lint-current-buffer (using version 20200408.203):
- No issues!


### meow-eldoc.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!


### meow-face.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!


### meow-helpers.el ###

byte-compile-file (using Emacs 26.3):
```
meow-helpers.el:41:25:Warning: reference to free variable
    `meow-leader-base-keymap'
In meow-leader-define-mode-key:
meow-helpers.el:46:48:Warning: `(keymap (meow--get-mode-leader-keymap mode
    t))' is a malformed function
meow-helpers.el:55:27:Warning: reference to free variable `keymap'
In meow-normal-define-key:
meow-helpers.el:68:25:Warning: reference to free variable
    `meow-normal-state-keymap'
In end of data:
meow-helpers.el:75:1:Warning: the function `when-let' is not known to be
    defined.
```

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!


### meow-init.el ###

byte-compile-file (using Emacs 26.3):
```
meow-init.el:29:9:Warning: reference to free variable `meow-normal-mode'
meow-init.el:32:13:Warning: reference to free variable `meow--keymap-loaded'
meow-init.el:34:21:Warning: reference to free variable
    `meow-normal-state-keymap'
meow-init.el:35:21:Warning: assignment to free variable `meow--keymap-loaded'
In meow--insert-init:
meow-init.el:39:9:Warning: reference to free variable `meow-insert-mode'
In meow--motion-init:
meow-init.el:45:9:Warning: reference to free variable `meow-motion-mode'
meow-init.el:48:13:Warning: reference to free variable `meow--keymap-loaded'
meow-init.el:50:21:Warning: reference to free variable
    `meow-motion-state-keymap'
meow-init.el:51:19:Warning: assignment to free variable `meow--keymap-loaded'
In meow--keypad-init:
meow-init.el:55:9:Warning: assignment to free variable `meow--prefix-arg'
meow-init.el:56:9:Warning: assignment to free variable `meow--keypad-keys'
meow-init.el:57:9:Warning: assignment to free variable `meow--use-literal'
meow-init.el:58:9:Warning: assignment to free variable `meow--use-meta'
In meow--enable:
meow-init.el:66:11:Warning: reference to free variable `meow--space-command'
meow-init.el:70:21:Warning: assignment to free variable `meow--space-command'
meow-init.el:71:31:Warning: reference to free variable
    `meow-normal-state-mode-list'
In end of data:
meow-init.el:101:1:Warning: the following functions are not known to be
    defined: meow-insert-mode, meow-motion-mode, meow--get-mode-leader-keymap,
    meow-normal-mode, meow--switch-state, meow--eldoc-setup,
    meow--wgrep-setup, meow--yas-setup
```

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!

Suggestions/experimental static checks:
- meow-init.el#L92: It's safer to sharp-quote function names; use `#'`
- meow-init.el#L97: It's safer to sharp-quote function names; use `#'`

### meow-keymap.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
meow-keymap.el:0: You should have a section marked ";;; Commentary:"
```

package-lint-current-buffer (using version 20200408.203):
- No issues!


### meow-keypad.el ###

byte-compile-file (using Emacs 26.3):
```
meow-keypad.el:50:17:Warning: reference to free variable `meow--prefix-arg'
In meow--keypad-format-keys:
meow-keypad.el:61:51:Warning: reference to free variable `meow--keypad-keys'
meow-keypad.el:62:14:Warning: reverse called with 0 arguments, but requires 1
meow-keypad.el:64:11:Warning: reference to free variable `meow--use-meta'
meow-keypad.el:66:11:Warning: reference to free variable `meow--use-literal'
In meow--keypad-quit:
meow-keypad.el:72:9:Warning: assignment to free variable `meow--keypad-keys'
meow-keypad.el:73:9:Warning: assignment to free variable `meow--use-literal'
meow-keypad.el:74:9:Warning: assignment to free variable `meow--use-meta'
In meow--keypad-try-execute:
meow-keypad.el:81:15:Warning: reference to free variable `meow--use-literal'
meow-keypad.el:82:15:Warning: reference to free variable `meow--use-meta'
meow-keypad.el:96:15:Warning: reference to free variable `meow--prefix-arg'
meow-keypad.el:96:32:Warning: assignment to free variable `meow--prefix-arg'
meow-keypad.el:92:31:Warning: reference to free variable `meow--keypad-keys'
In meow-keypad-undo:
meow-keypad.el:103:5:Warning: reference to free variable `meow--use-literal'
meow-keypad.el:104:11:Warning: assignment to free variable `meow--use-literal'
meow-keypad.el:105:5:Warning: reference to free variable `meow--use-meta'
meow-keypad.el:106:11:Warning: assignment to free variable `meow--use-meta'
meow-keypad.el:108:10:Warning: reference to free variable `meow--keypad-keys'
meow-keypad.el:109:11:Warning: assignment to free variable `meow--keypad-keys'
In meow-keypad-self-insert:
meow-keypad.el:114:4:Warning: `(key (cond ((equal last-input-event (quote
    return)) "RET") ((equal last-input-event (quote tab)) "<tab>")
    ((characterp last-input-event) (string last-input-event)) (t nil)))' is a
    malformed function
meow-keypad.el:122:7:Warning: reference to free variable `meow--use-literal'
meow-keypad.el:124:41:Warning: reference to free variable `key'
meow-keypad.el:127:13:Warning: reference to free variable `meow--keypad-keys'
meow-keypad.el:130:30:Warning: assignment to free variable `meow--keypad-keys'
meow-keypad.el:136:17:Warning: assignment to free variable `meow--use-literal'
meow-keypad.el:141:17:Warning: reference to free variable `meow--use-meta'
meow-keypad.el:139:33:Warning: assignment to free variable `meow--use-meta'
meow-keypad.el:132:30:Warning: reference to free variable
    `meow--keypad-meta-prefix'
meow-keypad.el:135:30:Warning: reference to free variable
    `meow--keypad-literal-prefix'
In end of data:
meow-keypad.el:155:1:Warning: the following functions are not known to be
    defined: thread-first, string-join, meow-keypad-mode, when-let,
    meow--switch-state
```

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!


### meow-tut.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!


### meow-util.el ###

byte-compile-file (using Emacs 26.3):
```
meow-util.el:29:5:Warning: reference to free variable `meow-insert-mode'
meow-util.el:31:5:Warning: reference to free variable `meow-normal-mode'
meow-util.el:33:5:Warning: reference to free variable `meow-motion-mode'
meow-util.el:35:5:Warning: reference to free variable `meow-keypad-mode'
In meow--selection-type:
meow-util.el:70:10:Warning: reference to free variable `meow--selection'
In meow--get-mode-leader-keymap:
meow-util.el:95:53:Warning: `(keymap (plist-get meow--leader-mode-keymaps
    mode))' is a malformed function
meow-util.el:98:13:Warning: reference to free variable `keymap'
meow-util.el:105:7:Warning: reference to free variable
    `meow-leader-base-keymap'
meow-util.el:103:52:Warning: reference to free variable
    `meow--leader-mode-keymaps'
meow-util.el:104:9:Warning: assignment to free variable
    `meow--leader-mode-keymaps'
In meow--auto-switch-mode:
meow-util.el:114:45:Warning: reference to free variable
    `meow-normal-state-mode-list'
meow-util.el:115:37:Warning: reference to free variable
    `meow-auto-switch-exclude-mode-list'
meow-util.el:117:18:Warning: reference to free variable `meow-insert-mode'
meow-util.el:117:35:Warning: reference to free variable `meow-normal-mode'
meow-util.el:121:14:Warning: reference to free variable `meow-motion-mode'
In end of data:
meow-util.el:139:1:Warning: the following functions are not known to be
    defined: meow-insert-mode, meow-normal-mode, meow-motion-mode,
    meow-keypad-mode, if-let
```

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!


### meow-var.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!


### meow-wgrep.el ###

byte-compile-file (using Emacs 26.3):
```
meow-wgrep.el:47:1:Warning: the following functions are not known to be
    defined: meow-normal-mode, meow-motion-mode
```

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!

Suggestions/experimental static checks:
- meow-wgrep.el#L40: It's safer to sharp-quote function names; use `#'`
- meow-wgrep.el#L41: It's safer to sharp-quote function names; use `#'`
- meow-wgrep.el#L42: It's safer to sharp-quote function names; use `#'`
- meow-wgrep.el#L43: It's safer to sharp-quote function names; use `#'`

### meow-yas.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!

Suggestions/experimental static checks:
- meow-yas.el#L29: It's safer to sharp-quote function names; use `#'`

### meow.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!

**Comment by riscy** [comment]
> May I ask how you got this report, is there a script or something. It looks really useful.

Of course, I finally got around to packaging the scripts up a little while ago here https://github.com/riscy/melpazoid/

Also feel free to ping me when ready for another pass, or any followup questions.

**Comment by DogLooksGood** [comment]
@riscy Hi, this is really helpful. 
I opened a PR in melpazoid to check meow.
Now, it looks like it passed CI.

**Comment by riscy** [comment]
Nice!  I'm excited to see you use it.  Even though the build "passed" (which is good, it means the package can be installed) there are still some of the warnings listed above [in the build logs](https://travis-ci.org/github/riscy/melpazoid/builds/675825181) -- check those out.

**Comment by DogLooksGood** [comment]
I've fixed all the byte-compile warnings except this one:

```
meow-command.el:967:1:Warning: the function `xor' is not known to be defined.
```
I can compile meow in a Emacs -Q without any warnings, Emacs version is 27.0.90.

And Emacs tells me `xor` comes from `subr.el`, but I get only find `subr-x` on melpa. So what is this `subr` package?

**Comment by riscy** [comment]
`subr-x` is packaged with Emacs, but I think in this case you just need to `(require 'array)`inside meow-command.el   -- after that, this looks good to merge.

Some minor stuff while I'm here:
- I also see `- _elisp/meow-keymap.el (GPL) -- (no elisp header)` (no elisp header) which I think is because you need three dashes at the top there and then that's everything for the automated checks.
- in meow-helpers.el, specfic -> specific
- in meow-core.el, Indiactor -> Indicator

**Comment by DogLooksGood** [comment]
Got these issue fixed!

**Comment by riscy** [comment]
This one just appeared in the latest:

byte-compile-file (using Emacs 26.3):
```
meow-company.el:35:9:Warning: reference to free variable `company-candidates'
```
This just requires a `defvar` on company-candidates.  I think it is simple enough to fix, and verifiably not a problem, that it's not a blocker, but it's a good idea to fix that so that all your users can enjoy a worry-free byte-compile.  I'm sure it's becoming like whack-a-mole now.  :)

**Pull request merged**
