### PR TITLE
Add recipe for bionic-reading-mode

### PR DESCRIPTION
**Pull request by wavexx**
### Brief summary of what the package does

Highlight word stems in text buffers, thereby providing artificial fixation points to improve speed reading. Inspired by a website of the same name.

### Direct link to the package repository

https://gitlab.com/wavexx/bionic-reading-mode.el

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, this is a neat idea.  Quick first pass --

- Bionic reading is apparently a registered trademark.  And I doubt (?) they're targeting Emacs, but based on their website they're trying to get this available in as many spaces as possible.  Sometimes it's safe to err on the side of caution when naming packages, and just refer to bionic reading as an inspiration rather than the name of the package itself
- I think the summary line `Speed reading minor mode` could be improved to mention the font-locking, e.g. `Syntax highlighting for speed reading` or `Font-locking for to help with speed reading` or something, just to help differentiate it at a glance
- I can see the usefulness of this idea, but the stemming algorithm seems simple to the point of being arbitrary.  But to be fair I get the same (first) impression from the Bionic Reading website
- I think even GitLab is having trouble detecting the repository's license, even though you have a COPYING.txt file; conventionally this file has no .txt extension (i.e. COPYING) but renaming it to LICENSE or similar might help with auto-detection; fyi

**Comment by wavexx** [comment]
> Thanks, this is a neat idea. Quick first pass --
> 
>     * Bionic reading is apparently a registered trademark.  And I doubt (?) they're targeting Emacs, but based on their website they're trying to get this available in as many spaces as possible.  Sometimes it's safe to err on the side of caution when naming packages, and just refer to bionic reading as an inspiration rather than the name of the package itself

Does this apply even though there's no business behind?

But I'm quite open for this. @walseb suggestions?

>     * I can see the usefulness of this idea, but the stemming algorithm seems simple to the point of being arbitrary.  But to be fair I get the same (first) impression from the Bionic Reading website

No need to wonder, it *is* absolutely trivial also in the original JS implementation. I have no shame in saying that I implemented this just to see how this would look line in emacs ;)

**Comment by riscy** [comment]
> Does this apply even though there's no business behind?

I'm not sure, but I think to register the trademark in the first place you have to demonstrate there's a business.

**Comment by wavexx** [comment]
Renamed to stem-reading-mode, removing references to "bionic reading".

Updated the summary. I was already using "Highlight word stems for speed reading" for the mode description, so I updated that everywhere.

Not sure about COPYING. Seems to be picked up correctly and detected as GPLv3 to me (incidentally, renaming to .txt is something I started doing _for_ gitlab/github to please the dumb filetype detection).

**Comment by riscy** [comment]
> Seems to be picked up correctly and detected as GPLv3 to me

I must have not been looking in the right place -- that's on me.  Thanks for being so accommodating re: the naming. :)

**Pull request merged**
