### PR TITLE
Add apt-utils recipe

### PR DESCRIPTION
**Pull request by Sasanidas**
### Brief summary of what the package does

This package can be used to manage apt packages with in emacs, it has a lot of features such as 
get package information, search package with regex and so on.

This package was found in emacswiki.org and slightly modify to work with modern emacs,  there is
still some work to do to optimize the code. 

### Direct link to the package repository

https://gitlab.com/sasanidas/apt-utils

### Your association with the package

Maintainer

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
We used to distribute this package but removed it in #2398, which references #2128, which contains this:

> apt-utils file corrupted on wiki (fixed)
> But more importantly this isn't upstream, the best I could find is http://ftp.de.debian.org/debian/pool/main/a/apt/apt_0.9.7.9+deb7u7.tar.gz but my tools can no longer import tarballs.

But then in #5758 we added the `debian-el` package, which contains `apt-utils.el`. Also see #5449.

This is upstream and therefore what Melpa should distribute. You should probably contribute to that at https://salsa.debian.org/emacsen-team/debian-el.

**Comment by Sasanidas** [comment]
> We used to distribute this package but removed it in #2398, which references #2128, which contains this:
> 
> > apt-utils file corrupted on wiki (fixed)
> > But more importantly this isn't upstream, the best I could find is http://ftp.de.debian.org/debian/pool/main/a/apt/apt_0.9.7.9+deb7u7.tar.gz but my tools can no longer import tarballs.
> 
> But then in #5758 we added the `debian-el` package, which contains `apt-utils.el`. Also see #5449.
> 
> This is upstream and therefore what Melpa should distribute. You should probably contribute to that at https://salsa.debian.org/emacsen-team/debian-el.

Oh I didn't know that, the apt file is more for general apt distributions, that package works with Ubuntu as well?

Thank you.

**Comment by tarsius** [comment]
Seems so: https://packages.ubuntu.com/eoan/debian-el.

**Comment by Sasanidas** [comment]
> Seems so: https://packages.ubuntu.com/eoan/debian-el.

Ok then, no need for this package on Melpa.

Thank you.

**Pull request closed without merging**
