### PR TITLE
Add ddragon recipe

### PR DESCRIPTION
**Pull request by xuchunyang**
### Brief summary of what the package does

Browse League of Legends champions data (such as a champion's abilities and skins) 

### Direct link to the package repository

https://github.com/xuchunyang/ddragon.el

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

The maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

Though it's possible to make checkdoc 100% happy, but it is not worth to address all its suggestions. In my code, `M-x checkdoc` is happy with this config, in other words, I don't want to add docstring to EVERY definitions.

```elisp
(setq checkdoc-force-docstrings-flag nil)
```

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this - here's a quick first pass:

### ddragon.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
ddragon.el:122: All variables and subroutines might as well have a documentation string
Warning (emacs): 
ddragon.el:131: All variables and subroutines might as well have a documentation string
```
I'll nag you to fix these in spite of what you wrote -- I would prefer people try to put forward a clean checkdoc, at least until there is a change to the MELPA checklist. 

package-lint-current-buffer (using version 20200226.2001):
- No issues!

### License ###

- Use a LICENSE file that GitHub can detect (e.g. no markup).
  See: https://github.com/licensee/licensee
- Please add a LICENSE or COPYING file to the repository
- ddragon.el has GPL license text

**Comment by xuchunyang** [comment]
I fixed all the checkdoc warnings, now it's clean.

> Use a LICENSE file that GitHub can detect (e.g. no markup).

I added LICENSE.md, and github can detect markdown.

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.

I cannot find any issues for this package :tada:

**Comment by xuchunyang** [comment]
@conao3 Thank you for the review, not only this, but also my other PRs.

**Comment by riscy** [comment]
I notice you have no keywords, and I think the name of the package and the package summary will hamper its discoverability on MELPA -- so a couple suggestions:

- Add some Keywords (`games`/`hypermedia` from `finder-known-keywords` could be among them)
- Perhaps rename the package to `lol-data-dragon` or `data-dragon` instead of `ddragon`
- "Browse Data Dragon" as a package summary (and `defgroup docstring) could be a bit more descriptive, such as "Browse League of Legends' Data Dragon" or even "Browse Champions of League of Legends on Data Dragon".

Beyond that the checklist looks good -- thanks for being so thorough.

**Comment by xuchunyang** [comment]
> * Add some Keywords (`games`/`hypermedia` from `finder-known-keywords` could be among them)

Done

> * Perhaps rename the package to `lol-data-dragon` or `data-dragon` instead of `ddragon`

I've change the name to lol-data-dragon. The melpa recipe is also updated and I've checked it can be installed with Melpa's package-build.

> * "Browse Data Dragon" as a package summary (and `defgroup docstring) could be a bit more descriptive, such as "Browse League of Legends' Data Dragon" or even "Browse Champions of League of Legends on Data Dragon".

Done.

**Comment by riscy** [comment]
Great, thanks so much. :)

**Pull request merged**
