### PR TITLE
Add recipe for gemtext-mode

### PR DESCRIPTION
**Pull request by arjca**
### Brief summary of what the package does

Major mode for editing Gemtext files.

### Direct link to the package repository

https://git.sr.ht/~arjca/gemtext-mode.el

### Your association with the package

Author & Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

- gemtext-mode.el#L684: Could this point/point-max comparison use `eobp`?
- gemtext-mode.el#L727: Unnecessary if you use `define-derived-mode` (which you are -- just specify the `mode-name` you want in the NAME argument)
- gemtext-mode.el#L594: Loading a package should rarely add hooks (especially since you are in control of this mode already -- just do these things when you activate the mode, e.g. within `gemtext-mode`'s definition write `(if gemtext-mode (outline-minor-mode 1) ...)`; but let me know if I can unpack this more for you
- gemtext-mode.el#L704: Loading a package should rarely add hooks (as above)

**Comment by arjca** [comment]
Hi @riscy,
Thank you for your review!

I did changes to code according to your comments, you can review them here: https://git.sr.ht/~arjca/gemtext-mode.el/commit/431b3b1d7c4310ef09ba16adbc870bc0af2c0e9b.

I'm not used to Emacs mode development, so I have a question about your third point: why would we use `(if gemtext-mode ...)` in this context? As I understand it, the `gemtext-mode` symbol doesn't yet exist in `(define-derived-mode ...)`. So I've added `(outline-minor-mode)` and `(goto-address-mode)` without the `(if...)`.

**Comment by riscy** [comment]
> Why would we use `(if gemtext-mode ...)` in this context?

This is actually my mistake, and I apologize for that - that would be true for a minor mode (which you may already be aware of) but not true for a major/derived mode like you've written.  And of course switching major mode kills local variables (including `outline-minor-mode`) so what you have works exactly as you intend.

This looks good to go -- merging now.  And, welcome to MELPA. :)

**Comment by riscy** [comment]
Obviously I forgot to merge this. :)

**Pull request merged**
