### PR TITLE
Add recipe for zotero

### PR DESCRIPTION
**Pull request by fvdbeek**
### Brief summary of what the package does

Emacs-zotero is a GNU Emacs interface to the [Zotero Web API v3](https://www.zotero.org/support/dev/web_api/v3/start). It provides wrapper functions to access the API, functions to cache and sync emacs-zotero with the Zotero server, and a browser to interact with the cache.

### Direct link to the package repository

https://gitlab.com/fvdbeek/emacs-zotero

### Your association with the package

I am the maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass, mostly automated:

### zotero-arxiv.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210227.314):
```
2 issues found:
37:37: error: `authors' was removed in Emacs version 25.1.
58:15: error: `authors' was removed in Emacs version 25.1.
```
This is a package-lint false positive so I wouldn't insist.  You could just rename the variable to creators to clear it up.

Other [lints](https://github.com/riscy/melpazoid):
- zotero-arxiv.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- zotero-arxiv.el#L35: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-auth.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
zotero-auth.el:99: Disambiguate zotero-auth-token by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
zotero-auth.el:134: Argument `arg' should appear (as ARG) in the doc string
```
The first nag is because that name is being used for a function and a variable, so the online Emacs help doesn't know where to link users when you create a hyperlink out of it.  I'd recommend renaming one of them.

package-lint (using version 20210227.314):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- zotero-auth.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-browser.el ###

byte-compile (using Emacs 27.1):
```
zotero-browser.el:694:1:Warning: variable `_' not left unused
zotero-browser.el:748:1:Warning: variable `_' not left unused
zotero-browser.el:748:1:Warning: variable `_' not left unused
zotero-browser.el:748:1:Warning: variable `_' not left unused
zotero-browser.el:810:1:Warning: variable `_' not left unused
zotero-browser.el:810:1:Warning: variable `_' not left unused
zotero-browser.el:810:1:Warning: variable `_' not left unused
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
zotero-browser.el:1212: Argument `arg' should appear (as ARG) in the doc string
Warning (emacs): 
zotero-browser.el:1394: Argument `arg' should appear (as ARG) in the doc string
Warning (emacs): 
zotero-browser.el:1418: Argument `arg' should appear (as ARG) in the doc string
Warning (emacs): 
zotero-browser.el:1423: Lisp symbol `top-level' should appear in quotes
```
This (and all subsequent `top-level` nags) are usually false positives.  My trick is just to say "top level" instead. :)

package-lint (using version 20210227.314):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- zotero-browser.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-cache.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
zotero-cache.el:299: Some lines are over 80 columns wide
Warning (emacs): 
zotero-cache.el:305: Lisp symbol `top-level' should appear in quotes
Warning (emacs): 
zotero-cache.el:450: Some lines are over 80 columns wide
Warning (emacs): 
zotero-cache.el:456: Lisp symbol `top-level' should appear in quotes
```

package-lint (using version 20210227.314):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- zotero-cache.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-crossref.el ###

byte-compile (using Emacs 27.1):
```
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
zotero-crossref.el:75:1:Warning: variable `_' not left unused
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210227.314):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- zotero-crossref.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- zotero-crossref.el#L189: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-diff.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210227.314):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- zotero-diff.el#L21: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-edit.el ###

byte-compile (using Emacs 27.1):
```
zotero-edit.el:175:1:Warning: variable `_' not left unused
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
zotero-edit.el:78: Disambiguate zotero-edit-text-mode by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
zotero-edit.el:237: `y-or-n-p' argument should end with "? "
```

package-lint (using version 20210227.314):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- zotero-edit.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-fulltext.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210227.314):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- zotero-fulltext.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- zotero-fulltext.el#L95: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-json.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
zotero-json.el:38: Some lines are over 80 columns wide
Warning (emacs): 
zotero-json.el:38: Argument `orig-fun' should appear (as ORIG-FUN) in the doc string
Warning (emacs): 
zotero-json.el:59: Some lines are over 80 columns wide
Warning (emacs): 
zotero-json.el:59: Argument `orig-fun' should appear (as ORIG-FUN) in the doc string
```

package-lint (using version 20210227.314):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- zotero-json.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-lib.el ###

byte-compile (using Emacs 27.1):
```
zotero-lib.el:187:1:Warning: variable `_' not left unused
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
zotero-lib.el:272: Some lines are over 80 columns wide
Warning (emacs): 
zotero-lib.el:282: Some lines are over 80 columns wide
```

package-lint (using version 20210227.314):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- zotero-lib.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-openlibrary.el ###

byte-compile (using Emacs 27.1):
```
zotero-openlibrary.el:44:1:Warning: variable `_' not left unused
zotero-openlibrary.el:44:1:Warning: variable `_' not left unused
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210227.314):
```
1 issue found:
37:43: error: `authors' was removed in Emacs version 25.1.
```

Other [lints](https://github.com/riscy/melpazoid):
- zotero-openlibrary.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-pmid.el ###

byte-compile (using Emacs 27.1):
```
zotero-pmid.el:45:1:Warning: variable `_' not left unused
zotero-pmid.el:45:1:Warning: variable `_' not left unused
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210227.314):
```
1 issue found:
37:36: error: `authors' was removed in Emacs version 25.1.
```

Other [lints](https://github.com/riscy/melpazoid):
- zotero-pmid.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-recognize.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
zotero-recognize.el:124: Some lines are over 80 columns wide
```

package-lint (using version 20210227.314):
```
1 issue found:
116:41: error: `authors' was removed in Emacs version 25.1.
```

Other [lints](https://github.com/riscy/melpazoid):
- zotero-recognize.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero-sync.el ###

byte-compile (using Emacs 27.1):
```
zotero-sync.el:585:1:Warning: Unused lexical variable `default'
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210227.314):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- zotero-sync.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### zotero.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
zotero.el:64: Some lines are over 80 columns wide
Warning (emacs): 
zotero.el:555: Some lines are over 80 columns wide
Warning (emacs): 
zotero.el:559: Lisp symbol `top-level' should appear in quotes
Warning (emacs): 
zotero.el:780: Disambiguate zotero-auth-token by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
zotero.el:719: Lisp symbol `top-level' should appear in quotes
Warning (emacs): 
zotero.el:854: Lisp symbol `top-level' should appear in quotes
Warning (emacs): 
zotero.el:916: Lisp symbol `top-level' should appear in quotes
Warning (emacs): 
zotero.el:934: Lisp symbol `top-level' should appear in quotes
```

package-lint (using version 20210227.314):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- zotero.el#L23: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- zotero.el#L505: `read-string` prompts should often end with a space but this feels like a hack

### Package ###

- Prefer the default recipe or use `:defaults`, if possible.

**Comment by fvdbeek** [comment]
> error: `authors' was removed in Emacs version 25.1.
> This is a package-lint false positive so I wouldn't insist. You could just rename the variable to creators to clear it up.

Left this as is.

> Prefer `https` over `http` if possible

These were about all in the comments, but [http://www.winfield.demon.nl/](http://www.winfield.demon.nl/) doesn't use HTTPS, so is left unchanged.

> Disambiguate zotero-auth-token by preceding w/ function,command,variable,option or symbol.
> The first nag is because that name is being used for a function and a variable, so the online Emacs help doesn't know where to link users when you create a hyperlink out of it. I'd recommend renaming one of them.

Done.

> Argument `arg' should appear (as ARG) in the doc string

Left this as is, because ARG is only used for the `C-u' prefix.  If necessary, I will change it.

> Warning: variable `_' not left unused

This looks like a false positive? I only see unused local variables, and idiomatic "wildcards" in the `pcase' macro.

> Lisp symbol `top-level' should appear in quotes
> This (and all subsequent `top-level` nags) are usually false positives. My trick is just to say "top level" instead. :)

Done.

> Some lines are over 80 columns wide

Left this as is, because of readability.

> Disambiguate zotero-edit-text-mode by preceding w/ function,command,variable,option or symbol.

Left this as is, because `zotero-edit-text-mode' isn't ambigious.

> `y-or-n-p' argument should end with "? "

Left this as is, because the question is followed by another line.

> Argument `orig-fun' should appear (as ORIG-FUN) in the doc string

Left this as is, because it is idiomatic in advices. If necessary, I will change it.

> Disambiguate zotero-auth-token by preceding w/ function,command,variable,option or symbol.

Done.

> `read-string` prompts should often end with a space but this feels like a hack

Done.

> Warning: Unused lexical variable `default'

Fixed.

> Prefer the default recipe or use `:defaults`, if possible.

Done.

**Comment by riscy** [comment]
> This looks like a false positive?

Yes I think so, but those are easy to fix and we should shoot for a clean byte-compile.  In zotero-pmid.el for example you can give those wildcards nonoverlapping names (e.g. `(_has-article (seq-some (lambda (elt) (equal elt "Journal Article")) seq)))`), and not use them to call functions in the middle of a sequence of `let*` declarations (e.g. `(_ (string-match regexp sortpubdate))`).  Sometimes warnings like these point to incorrect use of macros for example, so there's an added benefit to scrubbing them clean.

> If necessary, I will change it.

I'm generally a stickler for checkdoc -- my reason for this is to avoid repeated negotiation of grey areas, even though I agree it's a bit extraneous in this case.  On that note, I disagree that adhering to the the long-lines checkdocs would decrease readability.  For instance here's how your function appears in the (approximately vanilla Emacs) online help right now:

image

the online help doesn't know where it's appropriate to break lines, and so it doesn't.

> the question is followed by another line

From a readability perspective I wonder if it would be better to put the question at the end, but that's fine.

**Comment by fvdbeek** [comment]
> > This looks like a false positive?
> 
> Yes I think so, but those are easy to fix and we should shoot for a clean byte-compile. In zotero-pmid.el for example you can give those wildcards nonoverlapping names (e.g. `(_has-article (seq-some (lambda (elt) (equal elt "Journal Article")) seq)))`), and not use them to call functions in the middle of a sequence of `let*` declarations (e.g. `(_ (string-match regexp sortpubdate))`). Sometimes warnings like these point to incorrect use of macros for example, so there's an added benefit to scrubbing them clean.

That doesn't suppress the warnings:
`variable ‘_has-article’ not left unused`

> > If necessary, I will change it.
> 
> I'm generally a stickler for checkdoc -- my reason for this is to avoid repeated negotiation of grey areas, even though I agree it's a bit extraneous in this case. On that note, I disagree that adhering to the the long-lines checkdocs would decrease readability. [...]
> the online help doesn't know where it's appropriate to break lines, and so it doesn't.

Done

> > the question is followed by another line
> 
> From a readability perspective I wonder if it would be better to put the question at the end, but that's fine.

I really don't think it would, so left it as is.

**Comment by riscy** [comment]
> That doesn't suppress the warnings

My apologies, I didn't fully understand the macroexpansion of when-let when I wrote that -- it makes use of the return value in the conditional part.  If you still want to pack that conditional inside the when-let, here's one way to fix it in zotero-pmid.el:

```elisp
    (when-let ((uids (zotero-lib-plist-get* data :result :uids))
               (uid (unless (seq-empty-p uids) (elt uids 0)))
               (item (zotero-lib-plist-get* data :result (zotero-lib-string->keyword uid)))
               (seq (plist-get item :pubtype))
               (article (seq-some (lambda (elt) (equal elt "Journal Article")) seq)))
...
      (when-let ((source (plist-get item :source))
                 (source-not-publication-title (not (equal source (plist-get result :publicationTitle)))))
```
I think that should put you on the right foot toward the rest of the checklist.

**Comment by fvdbeek** [comment]
Done. But it is a pity that my trick to place conditionals in a `when-let' block results in compiler warnings. Now either the code is less concise with more nesting, or unused variables are not preceded by an underscore.

**Comment by riscy** [comment]
I like your solution of naming that variable `article-p`.  I apologize if that seemed pedantic, but (selfishly) it's easier for me to avoid negotiating the grey areas if I just insist on a clean byte-compile.  In any case, welcome to MELPA. :)

**Pull request merged**
