### PR TITLE
Add package typer-mode to melpa

### PR DESCRIPTION
**Pull request by lordnik22**
### Brief summary of what the package does

Provides a little game which makes the user type random sentences from a file or `view-emacs-news`. It's meant to train your typing skills.

### Direct link to the package repository

https://github.com/lordnik22/typer-mode

### Your association with the package

Not original author. Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Can you describe how this compares to existing [typing practicing packages on MELPA](https://melpa.org/#/?q=typing)?  In the meantime, quick first pass --

`typer-mode.el` with byte-compile using Emacs 28.1:
```
typer-mode.el:90:13: Warning: the function `string-blank-p' is not known to be
    defined.
```

`typer-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- typer-mode.el#L194: It's safer to sharp-quote function names; use `#'`
- typer-mode.el#L207: It's safer to sharp-quote function names; use `#'`
- typer-mode.el#L123: It's safer to sharp-quote function names; use `#'`
- typer-mode.el#L73: It's safer to sharp-quote function names; use `#'`
- typer-mode.el#L74: It's safer to sharp-quote function names; use `#'`
- typer-mode.el#L111: Consider `beginning-of-line`
```

Package and license:
- GNU General Public License v3.0 (via API)
- unknown license -- typer-mode.el: Type till you die
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to typer-mode.el

**Comment by lordnik22** [comment]
Hi Riscy

Thanks for checking the package.

For comparison I made a little table with my observations:
```
| aas                     | is not about training typing                                                                                            |
| dot-mode                | is not about training typing                                                                                            |
| git-commit-insert-issue | is not about training typing                                                                                            |
| key-leap                | is not about training typing                                                                                            |
| monkeytype              | serves same purpose, more complicated, provides nice stats and highlighting, creates .monkeytype-directory in home |
| speed-type              | serves same purpose, similar to monkeytype, Gross wpm/cpm and Net wpm/cpm not displayed,                                |
| typing                  | serves same purpose, minibuffer based, stores file .toe-scores, is a paradoy,                                           |
| typing-game             | serves similar purpse, reaction required, no words only single characters, the characters falling down,                 |
| typit                   | follows a study-program with predefined tests, opens small buffer, reacts only to space, provides no preview of typed characters, only after space the user sees what's effectively typed |
```

"typit", "mokeytype", "speed-type" share the most similarities. In my
opinion "speed-type" is the most similar in terms of features and
complexity.

The main difference is the error handling. In these three mentioned packages all games highlight the character red when falsely typed. In "typer-mode" a new line is added and the cursor dosn’t move past the error. A second difference is that typer-mode isn’t timed. So in a sense it’s endless. The only timer used is for the animation of new lines.

Some features provided by the other packages would fit well with "typer-mode". For example:
- getting the content from gutenberg
- providing some statistical values

To add a time-aspect, a feature could be added for lines that are automatic added. This would "force" the user to keep a certain typing speed which would make it more challenging. But currently I'm focusing to just get a stable version out.

I could imagine that typer-mode may be implemented into speed-type as a secondary mode but havn't really checked the speed-type-code and havn't contacted any of the contributors.

Best regards
lordnik

**Comment by lordnik22** [comment]
Hi Riscy I made a commit fixing your review points.

**Comment by riscy** [comment]
Thank you for taking a thorough look at those.  We try to be about curation at MELPA, and about indexing packages that are meaningfully different from what's already in the index, i.e. not just indexing everything out there (although I admit there are a huge amount of packages already).  I haven't tried any of these typing packages, but do you feel the difference you describe above is meaningful?

> I could imagine that typer-mode may be implemented into speed-type as a secondary mode but havn't really checked the speed-type-code and havn't contacted any of the contributors.

These packages tend to have pretty simple interfaces and that may complicate things beyond what the maintainers of speed-type intend, so I realize this suggestion may not be entirely realistic: but would you consider attempting that route to see how feasible this would be?

**Comment by lordnik22** [comment]
Yes no problem. This will take some time, checking the speed-type-code, coordinating with the maintainers of speed-type and than implementing it into there repo. I will keep this PR-Open until I know more whether it's realistic or not.

**Comment by riscy** [comment]
I'll mark this awaiting-upstream in the meantime, but feel free to reach out!

**Comment by tarsius** [comment]
Friendly ping. :ping_pong:

**Comment by lordnik22** [comment]
Thanks for ping. 
I will close this PR because typer-mode isn't needed in MELPA. I was able to integrate typer-mode into speed-type and opened a PR. My changes are quite big and I haven't found time to write tests. Even now where I tested it on a high level, I had to fix a bug. I'm happy with the current state but see that for a merge is probably more testing needed.
As soon as this is done, I can use speed-type for my purposes and I can get it via MELPA. 
Soooo the plan is set :heart:

**Pull request closed without merging**
