### PR TITLE
Add `sidecar-locals` package

### PR DESCRIPTION
**Pull request by ideasman42**
### Brief summary of what the package does

A flexible out-of-source alternative to dir-locals, see: [More convenient alternative to dir-locals?](https://www.reddit.com/r/emacs/comments/p4pt49) that lists some of the pain-points of using dir-locals.

### Direct link to the package repository

https://gitlab.com/ideasman42/emacs-sidecar-locals

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by Boruch-Baum** [comment]
I've read the reddit thread and don't understand how this solution solves a problem. There, I'm in agreement with the comment of suspiciously-familiar reddit-account-name @alphapapa .

**Comment by ideasman42** [comment]
@Boruch-Baum

In short, this is useful for a similar reason out-of-source builds are useful, I can have my project level configuration outside the projects source tree.

Currently if I have a `.dir-locals.el` in my source tree and I do a `git bisect` that removes a directory containing un-versioned, it causes the bisect to fail.

Keeping source repositories pristine avoids this problem, further, it makes it convenient to version-control the project configuration it's self - without tricks such as symlinking between directories (which would still cause issues with git-bisect).

---

Maybe it's simpler to show what I had do, to use dir-locals out-of-source for multiple projects.

#### Add `.dir-locals.el` in a top-level directory above the versioned code.

#### Add logic to allow `.dir-locals.el` in trusted directories to always run:

    (defvar my-trusted-paths (list "/source/" "/source/my-personal-project/"))
    (defvar my-trusted-paths-prefix (list "/source/all-dir-locals-under-this-directory/"))

    (defun my-trusted-paths-filter (dir-name)
      (catch 'result
        (dolist (p my-trusted-paths)
          (when (string-equal p dir-name)
            (throw 'result t)))
        (dolist (p my-trusted-paths-prefix)
          (when (string-prefix-p p dir-name)
            (throw 'result t)))))

    (advice-add 'hack-local-variables-filter
      :around
      #'
      (lambda (old-fn &rest args)
        (pcase-let ((`(,_variables ,dir-name) args))
          (if (my-trusted-paths-filter dir-name)
            (cl-letf (((symbol-function 'safe-local-variable-p) (lambda (&rest _) t)))
              (apply old-fn args)
              ;; Always accept paths matching.
              t)
            (apply old-fn args)))))


#### Add checks in the dir-locals for which project was loaded.


    ((nil
      . ((eval
          .
          (progn
            (let ((filename (buffer-file-name)))
              (cond
               ((string-prefix-p "/source/my-personal-project/" filename)
               ;; -- snip (project specific configuration) --
               ))))))))

----

It works but it's not at all convenient, and still causes problems from having to have all projects configuration in a single `.dir-locals.el`, versioning could work but would need to use a symlink to avoid multiple nested `.git` repositories.

**Comment by Boruch-Baum** [comment]
It all seems unnecessary to me, and even once I accept as a given that
it is necessary, it still seems like you're insisting on using the wrong
tool for the job. I see two alternative solutions, using just git:

The proposed "second-best" solution has the advantage of being totally
autonomous and invisible to any collaborator. It's "second-best" because
it's not as simple and elegant as the other solution, below.

Presume a directory hierarchy

   projects
   |-project-a
     |-1
       |-1.1
     |-2
   |-project-b

Put directories "project-a" and "project-b" each under separate version
control, with gitignore for the dirlocals files that are kept in their
classic locations. You now have two git repositories.

Put "projects", the parent directory, under separate version control, with
gitignore for everything except your dirlocals. You now have a third
repository containing just your dirlocals.

Does that satisfy all your requirements?

It avoids portability consequences to your insistence on keeping
dirlocals files outside the repository directory, but those consequences
 may not be of interest to you. If at some point you want to restore a
backup of project-b, your solution won't have your dirlocals anymore,
and anywhere to which you may in the future move your projects tree will
need the additional step of installing a melpa package just to use a
feature that already exists in emacs-core.

So much for the "second-best" solution. The solution that I would prefer,
which I think is the way git is intended to be used, does require a very
small bit of cooperation with your upstream. You and your upstream
collaborators and repository copies do absolutely nothing 'unusual'. You
each keep a personal dirlocals file in your project directory as Emacs
intends, even if it is an empty file. All of your dirlocals files are
under version control locally *only*, because .... (sneaky you) ... You
and your upstream have each added a single line to your git-attribute
file:

    dirlocals merge=ours

That's it. So, the drawback of this solution is that you need to ask
your collaborators to add a (possibly empty) dirlocals files to their
copies.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by ideasman42** [comment]
Both solutions you've suggested work on a technical level, although adding a top-level git repository is something I'd rather avoid, it could be confusing if my shell prompt makes it seem as if I have already created a git repo.
It's possible I'd accidentally add a new projects files into the parents git repo which would be annoying to untangle.

The bottom line AFAICS is what you have suggested is fine if directory locals are already working well.

Even if I accept your second (better) solution I still have to:

- Setup non-trivial workarounds to trust certain dir-locals to evaluate code, see: `hack-local-variables-filter` from previous post. This in it's self is more hassle than installing a package.
- Having a heavily intended file that isn't convenient to add code to.
- Have additional files in my source directory (which I could accept but rather avoid if I can help it).

**Comment by Boruch-Baum** [comment]
> Both solutions you've suggested work on a technical level, although adding a top-level git repository is something I'd rather avoid, it could be confusing if my shell prompt makes it seem as if I have already created a git repo.

Yes. However, if you're using Emacs / magit, those operations should have any confusion eliminated.

> It's possible I'd accidentally add a new projects files into the parents git repo which would be annoying to untangle.

I don't see how that's possible. The gitignore of the parent should prevent it.
 
> Even if I accept your second (better) solution I still have to:
> 
>     * Setup non-trivial workarounds to trust certain dir-locals to evaluate code, see: `hack-local-variables-filter` from previous post. This in it's self is more hassle than installing a package.

Why does that ever become necessary? If it's your personal dirlocals file, why wouldn't you trust it? If it isn't your personal dirlocals file, then: a) it shouldn't be there, and you need to figure out how it got there; b) emacs will prompt you on your first access and ask you how to proceed.

>     * Having a heavily intended file that isn't convenient to add code to.

I don't understand this sentence.
 
>     * Have additional files in my source directory (which I could accept but rather avoid if I can help it).

That is the way Emacs is. If it's any consolation, since the file begins with a dot, it's an "invisible" or "hidden" file, so you normally wouldn't notice it unless you explicitly look for "hidden" files, and then you would also be seeing the git directory, etc.

**Comment by ideasman42** [comment]
> > Both solutions you've suggested work on a technical level, although adding a top-level git repository is something I'd rather avoid, it could be confusing if my shell prompt makes it seem as if I have already created a git repo.
>
> Yes. However, if you're using Emacs / magit, those operations should have any confusion eliminated.

I don't use magit, just the command line.

> > It's possible I'd accidentally add a new projects files into the parents git repo which would be annoying to untangle.
>
> I don't see how that's possible. The gitignore of the parent should prevent it.

OK.

> > Even if I accept your second (better) solution I still have to:
> >
> > * Setup non-trivial workarounds to trust certain dir-locals to evaluate code, see: `hack-local-variables-filter` from previous post. This in it's self is more hassle than installing a package.
>
> Why does that ever become necessary? If it's your personal dirlocals file, why wouldn't you trust it? If it isn't your personal dirlocals file, then: a) it shouldn't be there, and you need to figure out how it got there; b) emacs will prompt you on your first access and ask you how to proceed.

It's not necessary, it  just means the entire evaluated block gets  added to `~/.config/emacs.d/custom.el` and any changes require re-assigning trust.

> > * Having a heavily intended file that isn't convenient to add code to.
>
> I don't understand this sentence.

Any logic must be added within a heavily indented block like this:

    ((nil
      . ((eval
          .
          (progn
            (let ((filename (buffer-file-name)))
              (cond
               ((string-prefix-p "/source/my-personal-project/" filename)
               (when (member major-mode '(c-mode c++-mode glsl-mode))
                 ;; -- snip (C/C++ specific configuration) --
               (when (equal major-mode 'org-mode)
                 ;; -- snip (Python specific configuration) --
                 ))))))))))

> > * Have additional files in my source directory (which I could accept but rather avoid if I can help it).
>
> That is the way Emacs is. If it's any consolation, since the file begins with a dot, it's an "invisible" or "hidden" file, so you normally wouldn't notice it unless you explicitly look for "hidden" files, and then you would also be seeing the git directory, etc.

Yes, I see that's the case,
in the past I have both accidentally added files to git, and committed without adding files to git which I should have (breaking the build).
I now use a push hook that only allows pushing when the repository is pristine so I can always be sure whatever I have locally is exactly whats being pushed.

Even making an exception for this additional file, it's not very convenient to version it's contents.
Although as suggested - it's possible.

**Comment by Boruch-Baum** [comment]
On 2021-08-16 21:19, Campbell Barton wrote:
>    It's not necessary, it just means the entire evaluated block gets added
>    to ~/.config/emacs.d/custom.el and any changes require re-assigning
>    trust.

You lost me there. I didn't realize anything relevant was being stored
in custom.el. Is that really true? Also, I'm not following the notion of
"changes require re-assigning trust". I don't think I have anything
further constructive to add here, but I'd welcome anyone else taking up
the task.

>    Any logic must be added within a heavily indented block like this:

A lot of that code seems unnecessary to me, especially once you adopt the
proposed git-only alternative. There's no need to check string-prefix,
or even major-mode; just push one or more elements onto the major-modes'
hook variables, as necessary.

>    Even making an exception for this additional file, it's not very
>    convenient to version it's contents.
>    Although as suggested - it's possible.

It's just another file in your local repository. No more or less
convenient that performing a 'git commit' on any other file there.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by ideasman42** [comment]
> On 2021-08-16 21:19, Campbell Barton wrote: It's not necessary, it just means the entire evaluated block gets added to ~/.config/emacs.d/custom.el and any changes require re-assigning trust.
> You lost me there. I didn't realize anything relevant was being stored in custom.el. Is that really true?

Yes, I double checked a full copy of the evaluated block is duplicated into the `custom.el` for it to be marked as trusted, I'd assume this could cause some noticeable performance degradation if this was done for 100's of lines, with multiple projects.

>  Also, I'm not following the notion of "changes require re-assigning trust". I don't think I have anything further constructive to add here, but I'd welcome anyone else taking up the task.

The evaluated block is marked as trusted (by storing it), any changes cause a mis-match marking it as untrusted, prompting for user import to re-trust.

> Any logic must be added within a heavily indented block like this:
> A lot of that code seems unnecessary to me, especially once you adopt the proposed git-only alternative. There's no need to check string-prefix, or even major-mode; just push one or more elements onto the major-modes' hook variables, as necessary.

The reason I was checking major modes was to allow shared code between C/C++/GLSL, as you say, the file prefix could be removed... it's still reasonably deeply ended.

> Even making an exception for this additional file, it's not very convenient to version it's contents. Although as suggested - it's possible.
> It's just another file in your local repository. No more or less convenient that performing a 'git commit' on any other file there.

In this case it would be the only local file in my git repository, the reason it's inconvenient is I don't want to git-commit it to the public location.

**Comment by Boruch-Baum** [comment]
On 2021-08-17 05:02, Campbell Barton wrote:
>    Yes, I double checked a full copy of the evaluated block is duplicated
>    into the custom.el for it to be marked as trusted,

Thank you. It was a point that I had become confused about.

>    I'd assume this could cause some noticeable performance degradation
>    if this was done for 100's of lines, with multiple projects.

I'm not seeing such a case. What operation are you planning to be
performed that would scale that way?

>    The evaluated block is marked as trusted (by storing it), any changes
>    cause a mis-match marking it as untrusted, prompting for user import to
>    re-trust.

Thanks. I got confused about that point. Would that Emacs prompt be
suppressed using your solution?

>    In this case it would be the only local file in my git repository, the
>    reason it's inconvenient is I don't want to git-commit it to the public
>    location.

My proposal addressed 'git merge' operations. You're raising the good point
of how it would handle 'git push' operations. I'm not sure. For that,
the git solution may be something that I've never personally used:

     git update-index --assume-unchanged FILE

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by ideasman42** [comment]
> > I'd assume this could cause some noticeable performance degradation if this was done for 100's of lines, with multiple projects.
> I'm not seeing such a case. What operation are you planning to be performed that would scale that way?

No, just an assumption that continually adding code to my `custom.el` file which all get compared when loading a file - it seems like it would eventually load down loading. Perhaps it's not all that bad in practice, it just seems unnecessary.

> Thanks. I got confused about that point. Would that Emacs prompt be suppressed using your solution?

Right, by adding advice to `hack-local-variables-filter` can workaround this.

**Comment by Boruch-Baum** [comment]
I just now bothered to go and actually read the emacs Info documentation
for "Directory Variables", and you also might find it worthwhile. From
my reading, it seems that without using git at all, you could replace
your package with...

   Another method of specifying directory-local variables is to define a
   group of variables/value pairs in a “directory class”, using the
   ‘dir-locals-set-class-variables’ function; then, tell Emacs which
   directories correspond to the class by using the
   ‘dir-locals-set-directory-class’ function. These function calls
   normally go in your initialization file (*note Init File::). This
   method is useful when you can’t put ‘.dir-locals.el’ in a directory
   for some reason.

Also, regarding the content of the file, the documentation there
indicates that there shouldn't be a need to specify an `eval` car for a
`progn` cdr to perform checks on a path-name or major-mode. Just write a
car with the mode name or path string and a have its cdr your desired
settings.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by ideasman42** [comment]
I was recently showed me an example of this: https://github.com/angrybacon/dotemacs/blob/edd3786c5edb72c8726fb2ef5a53a941e6017704/dotemacs.org#directory-local-variables

I'd need to double check exactly how this works, from a brief look:

- There is still the issue of  code needing to be in an `eval` block and trusted.
- The configuration can't be entirely outside the users `init.el` file (docs say `These function calls
   normally go in your initialization file (*note Init File::)` -  is it possible to have the code in the directory).

Further my impression is this feature is so complicated it seems almost nobody knows about it or uses it.

The basic steps to use my package are:

- Add a directory `.sidecar-locals` in path above your files.
- Trust the path (in your init  file).
- Add code in that directory that runs on file load (to check the paths used run `sidecar-locals-report` with a file open).

That's not to say anything more complex is bad, just that I've read these docs and am still unsure how I would achieve something roughly like what I'm after makes me think it's either not supported or involves multiple workarounds.

**Comment by Boruch-Baum** [comment]
On 2021-08-18 02:47, Campbell Barton wrote:
>      * The configuration can't be entirely outside the users init.el file

Why is that bad? How is that worse than defining and configuring an
entirely new package in the user's config file?

>	 (docs say These function calls normally go in your initialization
>	 file (*note Init File::) - is it possible to have the code in the
>	 directory).

I thought the whole point of your package was for the data *not* to be
in the directory.

>    Further my impression is this feature is so complicated it seems almost
>    nobody knows about it or uses it.

To my reading it seemed trivially uncomplicated. That "nobody knows
about it or uses it" speaks to it being an obscure corner-case.

>    The basic steps to use my package are:

More complex than either the git solutions or the emacs solutions, IMO.
The package seems to be re-inventing pre-existing functionality to no benefit.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by ideasman42** [comment]
> Why is that bad? How is that worse than defining and configuring an
entirely new package in the user's config file?

Using a package can be quite minimal in the users init file, so I don't consider this much overhead:

```
(use-package sidecar-locals)
(sidecar-locals-mode)
(setq sidecar-locals-paths-allow (list "/my-project-root/"))  ;; could be in custom.el.
```

> I thought the whole point of your package was for the data *not* to be
in the directory.

Yes, I'd like to version this separately (outside my init file too).

> To my reading it seemed trivially uncomplicated. That "nobody knows about it or uses it" speaks to it being an obscure corner-case.

This is the crux of the matter, since I don't see this use case as all that obscure - To run code in a parent directory outside my code-base with a straightforward trust model.

> More complex than either the git solutions or the emacs solutions, IMO.
> The package seems to be re-inventing pre-existing functionality to no benefit.

If I can have matching functionality with built in functionality, that could be OK, from asking here: https://www.reddit.com/r/emacs/comments/p4pt49 - it seems what I'm after isn't possible/straightforward though.

**Comment by riscy** [comment]
Thanks for this, and sorry for the delay on reviewing.  I rarely use dir-locals so the exchange above was extremely helpful (thanks @Boruch-Baum and @ideasman42).

This feels fairly niche but I think it could be useful for keeping editor-specific configuration out of mainline version control in a new way.  I would caution against using this for _project_-specific configuration (like which code formatter to use, as in your reddit post).

- I think the summary line is missing the word `to` in it "alternative _to_ built-in dir-locals"
- Very minor but instead of `(error (message "..." args))` you should just write `(error ("..." args))` to avoid an unnecessary message being printed
- Very minor but lambdas don't need sharp-quotes (e.g. in `sidecar-locals-report`, `sidecar-locals-hook`)
- "to determine the trust setting silence this message" -> "_to_ silence this message"?

**Comment by riscy** [comment]
I can't resist responding to this, too:

> From asking here: https://www.reddit.com/r/emacs/comments/p4pt49 - it seems what I'm after isn't possible/straightforward with currently functionality

I can see that you wrote the code and _then_ you asked whether its very specific features existed, which feels a bit backwards if you truly want to gauge what the community would find useful (which I think is your goal, right?)

**Comment by riscy** [comment]
I think there are no blockers on this one though, merging.

**Comment by ideasman42** [comment]
@riscy applied suggestions, except for this one. Since calling message is intended.

>     * Very minor but instead of `(error (message "..." args))` you should just write `(error ("..." args))` to avoid an unnecessary message being printed

> I can see that you wrote the code and then you asked whether its very specific features existed, which feels a bit backwards if you truly want to gauge what the community would find useful (which I think is your goal, right?)

I wrote the code the day after asking the question - after reading some answers and seeing this wasn't some obvious feature I was missing.

**Comment by riscy** [comment]
I stand corrected, and I apologize for how that came out. :)

**Pull request merged**
