### PR TITLE
Remove .dir-locals.el from packages

### PR DESCRIPTION
**Pull request by yashi**
### Brief summary of what the package does

Remove `.dir-locals.el` from packages.

### Direct link to the package repository

- https://github.com/emacs-ess/ESS
- https://github.com/Sarcasm/irony-mode

### Your association with the package

I'm just a user of these packages.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
  - But it doesn't talk about fixing the recipe.
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
  - I'm not touching .el
- [x] `M-x checkdoc` is happy with my docstrings
  - I'm not touching .el
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

I've also checked the contents of the package by running the following command
```
git checkout origin/master
make ess
tar --to-command=md5sum -xvf packages/ess-20221204.1348.tar | grep -v /$ | paste - - > old
git checkout yashi/remove-dir-locals-from-packages
make ess
tar --to-command=md5sum -xvf packages/ess-20221204.1348.tar | grep -v /$ | paste - - > new
diff -u old new
```
And these are the output
```diff
diff -u old new
--- old	2023-01-26 18:08:39.704212243 +0900
+++ new	2023-01-26 18:09:05.676501247 +0900
@@ -1,4 +1,3 @@
-ess-20221204.1348/.dir-locals.el	c79df97c8c197d00772f819ac3eb159d  -
 ess-20221204.1348/dir	24bd008c418f42fb4d6705c6a4e1fcb1  -
 ess-20221204.1348/ess-bugs-d.el	ffe0c6ffa5b25acc23132490b83b1c39  -
 ess-20221204.1348/ess-bugs-l.el	1b8bbcf9a7d0d6795e7d5584b6f01725  -
```

```diff
diff -u old new                                                                                                    ─╯
--- old	2023-01-26 18:13:25.603310108 +0900
+++ new	2023-01-26 18:13:41.531478187 +0900
@@ -1,4 +1,3 @@
-irony-20220110.849/.dir-locals.el	e94c67ea753fee672831bea79746e1b1  -
 irony-20220110.849/irony-cdb-clang-complete.el	570d26c7c25e2cc8fca035f2291326fe  -
 irony-20220110.849/irony-cdb-json.el	45290e533e521a52692a3839990f47a2  -
 irony-20220110.849/irony-cdb-libclang.el	33c3c7644443eb98dee8d8a7f4f719d4  -
```

### CODE REVIEW

**Comment by progfolio** [comment]
What is the reasoning behind this change?
The reasoning behind including them is to ensure consistency when potential contributors work on the source code.

**Comment by yashi** [comment]
Oops.  Sorry about not explaining it.  I thought it's a norm because we have `.dir-local.el` in `package-build-default-files-spec`.

Anyway, if we have `.dir-local.el` in each package, it takes precedence over the `.emacs.d/elpa/.dir-local.el` which users might put to control how they want.  FWIW, I have the following snippet in it.

```elisp
((emacs-lisp-mode . ((no-byte-compile . t))))
```

> The reason for including them is to ensure consistency when potential contributors work on the source code.

Are you sure?  How many of us using `~/.emacs.d/elpa/` to contribute?  It doesn't even have `.git` to create a commit.  If there is, you are not using the package at all anyway.  Or what am I missing?  Would you please elaborate?

**Comment by riscy** [comment]
I think the right thing to do here is to tag a couple of maintainers and see if they have good reasons for including this file, e.g. @vspinu, @Sarcasm -- what do you think about users *not* receiving the .dir-locals files when they install your package via MELPA?

But I suspect it may be unnecessary to include these; after all, the [default recipe deliberately excludes them](https://github.com/melpa/melpa#recipe-format).  This may in fact be something I should be watching out for, and/or suggesting users apply `:defaults` more often.

**Comment by Sarcasm** [comment]
For irony-mode, the `.dir-local.el` targets collaborators and not users of the projects, so it can safely be removed from the distributed package. :+1:

**Comment by vspinu** [comment]
Shouldn't this be addressed at the build step instead of the package recipe? There are surely more packages affected.

`dir-locals.el` might be used to customize behaviors other than editing. For instance `bug-reference-url-format` or `outline-regexp` which are used in ESS.  But well, no strong opinion on my side. As long as it's generically enforced deleting those doesn't seem to be a big deal.

The OP use case is valid but seems rare to my eye. It is also easy to deal with the issue locally by deleting all dir-locals in elpa dir:

```sh
find . -name ".dir-locals.el" | xargs rm -rf
```

**Comment by riscy** [comment]
> Shouldn't this be addressed at the build step instead of the package recipe?

It's something I'll have to watch out for more carefully, I admit; but people who use `:defaults` or use the default recipe -- both of which I encourage -- do have such files automatically excluded.

**Comment by riscy** [comment]
It looks like we can use `:defaults` in the case of irony, but in the case of ess several additional .texi files end up being added.  For reference I tried this recipe for ess:
```elisp
(ess
 :repo "emacs-ess/ESS"
 :fetcher github
 :files (:defaults
         "etc" "etc/*" "obsolete" "lisp/obsolete/*"
         (:exclude "etc/other")))
```
I'll merge these as-is; this is easy to revisit.

**Pull request merged**
