### PR TITLE
Added auto-virtualenvwrapper recipe

### PR DESCRIPTION
**Pull request by robert-zaremba**
### Brief summary of what the package does

 Automatically activate python virtualenv using virtualenvwrapper.el 

### Direct link to the package repository

https://github.com/robert-zaremba/auto-virtualenvwrapper.el

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR about byte-compile warnings. Please check it.
- https://github.com/robert-zaremba/auto-virtualenvwrapper.el/pull/1

And You should not use melpa package version for `virtualenvwrapper` for other package managers.

**Comment by robert-zaremba** [comment]
Thank you. Merged. I left one comment in the PR.

**Comment by robert-zaremba** [comment]
Can we merge this? Otherwise should I need to do some additional job?

**Comment by syohex** [comment]
https://github.com/robert-zaremba/auto-virtualenvwrapper.el/blob/ac41212a74c6159e9b410a6cef23dc6ffb449199/auto-virtualenvwrapper.el#L9

As I said above, You should not use melpa package version of `virtualenvwrapper`(`20161002.1515`). Other package manager cannot recognize it. You should use  `20151123` or `0` instead of it.

**Comment by robert-zaremba** [comment]
Sorry, I missed somewhere your comment.

I've updated the required version to `0`. How did you come up with `20151123`?

**Comment by syohex** [comment]
> How did you come up with 20151123?

Here. https://github.com/porterjamesj/virtualenvwrapper.el/blob/209938234b9a22344f5ca57c3a01d0913fa3b7e9/virtualenvwrapper.el#L7

**Comment by purcell** [comment]
I feel like you could simplify this a lot if you just unconditionally depended on `projectile`. I think you can use `projectile-project-root` without enabling `projectile-mode`, so it shouldn't affect the user. All that searching for `.git`, `.hg` etc. is a distraction and should be unnecessary.

**Comment by robert-zaremba** [comment]
@purcell - I didn't want to add  explicity dependency for `projectile`. If projectile is there it will be used as one of strategies. The function for getting project root based on _version control_ only takes 5 lines (4 without doc string) - and can be removed in favour of `auto-virtualenvwrapper--project-root-traverse`.
If you want I can remove it (`auto-virtualenvwrapper--project-root-vc`)

**Comment by purcell** [comment]
Sure. You should simply use `vc-root-dir` then, rather than hard-coding the handling of `.hg` and `.git`.

**Comment by robert-zaremba** [comment]
I'm already using `vc-root-dir` (line 78-79). 

Though for avoiding confusions I removed `.hg` and `.git` from `auto-virtualenvwrapper-project-root-files`

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
