### PR TITLE
Update docker images to debian bookworm

### PR DESCRIPTION
**Pull request by alanpearce**
I took the liberty of doing some formatting and optimisation. Feel free to apply only the commits of interest.

### CODE REVIEW

**Comment by riscy** [comment]
Hi @alanpearce - I've labeled this "sysadmin" which I think might be appropriate; in the meantime I think it's worth mentioning there's a merge conflict to resolve.

**Comment by alanpearce** [comment]
Thanks for letting me know about the merge conflict; it's fixed now.

**Comment by milkypostman** [comment]
Is this something we should do? I think we just updated to the latest Debian stable.

**Comment by alanpearce** [comment]
I thought so too, but it was previously one release behind the latest "stable", since I was going by what is available on a mini-pc I have here 🙈 

[Debian Releases](https://www.debian.org/releases/) shows bookworm holds the 'stable' alias right now. It helps with my PR #8584 as miller has a more up-to-date version available in bookworm. When I saw that, I thought it would be a good idea to update all the images :)

**Comment by milkypostman** [comment]
Just so you know I haven't forgotten about this but have to postpone working on this still.

**Comment by alanpearce** [comment]
No problem!

**Comment by tarsius** [comment]
> I think we just updated to the latest Debian stable.

We did update to Debian stable, which at that time was bullseye. A mere few day after that, a new Debian stable was release, named bookworm.

Another reason why we should update is that the version of Mercurial available on Bullseye is to old for `package-build.el`. Building packages that use Mercurial will continue to fail until we update to Bookworm.

(The reason that building with an older Mercurial version broke, is that we have no Mercurial expert on board, who would know that we cannot simply make the, I would say, quite reasonable assumption, that its equivalent of `git clean` has always been part of the default distribution. Turns out that was an experimental feature for more than a decade :scream:. So much for "Mercurial is so much more intuitive than Git".)

**Comment by milkypostman** [comment]
Ok I'll get to this this weekend

**Comment by tarsius** [comment]
@milkypostman Friendly ping! Please update to bookworm.

**Comment by milkypostman** [comment]
On it.

**Comment by milkypostman** [comment]
whoops.

**Comment by milkypostman** [comment]
@alanpearce thank you for your suggestions. I adopted them in my final formatting change and hopefully we've gotten everything. I sincerely apologize for how long it took me to adopt these changes... but they are here now!

**Pull request closed without merging**
