### PR TITLE
Add recipe for project-treemacs

### PR DESCRIPTION
**Pull request by cmccloud**
### Brief summary of what the package does
 Simple Treemacs backend for project.el: 
- Projects in Treemacs map to project.el projects.
- Workspaces in Treemacs map to project.el projects + their external roots.
- `project-find-file`, `project-switch-to-buffer`, `project-find-regexp` et al operate on the current treemacs project.
- `project-or-external-find-file`, `project-or-external-find-regexp` operate on the current treemacs workspace.

### Direct link to the package repository
https://github.com/cmccloud/project-treemacs

### Your association with the package
I'm the author of both the package and the recipe.

### Relevant communications with the upstream package maintainer
None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`project-treemacs.el` with byte-compile using Emacs 28.1:
```
project-treemacs.el:202:14: Warning: the function
    `treemacs--process-file-events@update-cache' is not known to be defined.
```
I am not a regular user of cl-defmethod so I don't know what the problem might be at first glance.  Let me know if this one isn't obvious to you, though, and I can help dig in.

**Comment by cmccloud** [comment]
I think this error was related to how I was defining an advice - the changes I made seem to have cleared it up on my end, let me know if it looks good there.

**Comment by riscy** [comment]
This looks good to merge.  A couple quick notes for you to followup on at your convenience --

- project-treemacs.el#L119: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
- Around line 216, a `progn` isn't necessary for the "else" part of an `if`

**Comment by cmccloud** [comment]
Thanks kindly.

**Pull request merged**
