### PR TITLE
Add Laguna theme

### PR DESCRIPTION
**Pull request by HenryNewcomer**
### Brief summary of what the package does

A custom theme that's easy on the eyes and focuses on importance.

### Direct link to the package repository

https://github.com/HenryNewcomer/laguana-theme

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
These checks are semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd>:
No issues! 💯

<kbd>M-x package-lint</kbd> (using version 20190606.2210):
```
2 issues found:

1:1: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:1: error: package.el cannot parse this buffer: Package lacks a "Version" or "Package-Version" header
```

<kbd>M-x byte-compile-file</kbd>:
Per CONTRIBUTING.org, consider using lexical binding
```
laguna-theme.el:42:1:Warning: Unused lexical variable `Laguna/undefined4'
laguna-theme.el:42:1:Warning: Unused lexical variable `Laguna/undefined1'
laguna-theme.el:42:1:Warning: Unused lexical variable `Laguna/cursor-fg'
```

<kbd>M-x check-declare-file</kbd> (not on the MELPA checklist):
No issues! 🎉

**Comment by HenryNewcomer** [comment]
Thank you. The unused variables have been temporarily commented out and a version was added to the header area. I haven't contributed before so if there are any other changes or steps required, please let me know.

**Comment by purcell** [comment]
Thanks. You can (and should) remove `Laguna/` throughout: those variables are only visible within the `let` block, and don't need any sort of prefix. (And that wouldn't be a prefix compliant with the elisp conventions anyway.) Looks good otherwise, so this will be ready to merge as soon as those names have been tidied up.

**Comment by HenryNewcomer** [comment]
> Thanks. You can (and should) remove `Laguna/` throughout: those variables are only visible within the `let` block, and don't need any sort of prefix. (And that wouldn't be a prefix compliant with the elisp conventions anyway.) Looks good otherwise, so this will be ready to merge as soon as those names have been tidied up.

**Comment by HenryNewcomer** [comment]
Woops, thanks. I just saw this. I'll edit them and post when they're fixed.

Oops #2: I didn't mean to close this, disregard the request.

**Comment by HenryNewcomer** [comment]
I've replaced `Laguna/` with `color-` as I believe it helps to distinguish what the variable is about at a glance.  Would this suffice, or do you want them completely removed, due to them already being within their appropriate scope?

**Comment by riscy** [comment]
I think there is a typo [here](https://github.com/HenryNewcomer/laguna-theme/blob/master/laguna-theme.el#L105) (should be no face-spec-set and no quote).  Otherwise the names looked cleaned up to me.

As a minor nit while I'm here :) it's convention to not break lines on an opening parenthesis, so ideally you should join these two lines [here](https://github.com/HenryNewcomer/laguna-theme/blob/master/laguna-theme.el#L43-L44).

**Comment by purcell** [comment]
Merged now, thanks, but please do fix up that typo that @riscy noted above.

Welcome to MELPA! :tada:

**Pull request merged**
