### PR TITLE
add jack-mode recipe

### PR DESCRIPTION
**Pull request by nverno**
### Brief summary of what the package does

Major mode for Jack programming language files (a language developed in the course From Nand to Tetris
available on Coursera).

### Direct link to the package repository

https://github.com/nverno/jack-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for your patience!  Quick first pass --

`jack-mode.el` with byte-compile using Emacs 28.1:
```
jack-mode.el:175:1: Warning: defvar `jack-mode-error-regexp-alist' docstring
    wider than 80 characters
```
This warning was introduced in Emacs 28 -- it's pretty strict but easy to fix in this case.

`jack-mode.el` with package-lint 20220607.738:
```
1 issue found:
44:0: error: Customization groups should not end in "-mode" unless that name would conflict with their parent group.
```

- `;;;###autoload(add-to-list 'auto-mode-alist '("\\.jack\\'" . jack-mode))` should be broken into two lines (it's just a comment right now)
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by nverno** [comment]
Thanks for the feedback!  I added a license file and made the linting changes.  The autoload line should be fine as is- anything after the autoload cookie will be detected.

**Comment by riscy** [comment]
>  The autoload line should be fine as is- anything after the autoload cookie will be detected.

I was incredulous so I checked.  Neither `eval-buffer` nor loading this package in with `(require 'jack-mode)` will cause that line to eval.  It's just a comment as far as the compimler is concerned.  Please change it to:
```elisp
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.jack\\'" . jack-mode))
```

**Comment by nverno** [comment]
> > The autoload line should be fine as is- anything after the autoload cookie will be detected.
> 
> I was incredulous so I checked. Neither `eval-buffer` nor loading this package in with `(require 'jack-mode)` will cause that line to eval. It's just a comment as far as the compimler is concerned. Please change it to:
> 
> ```emacs-lisp
> ;;;###autoload
> (add-to-list 'auto-mode-alist '("\\.jack\\'" . jack-mode))
> ```

Autoload cookies are parsed by the `autoload` package, so you can put stuff after the cookie you want copied verbatim to the autoloads file.  `eval-buffer` / `require` don't generate autoloads.  Anyway, updated! Thanks

**Comment by riscy** [comment]
Thanks for accommodating, and sorry if I came off as terse.  I didn't realize autoloads could be written as one-liners and learned something there -- although I still think that particular code should be evaluated even if the package wasn't installed with autoload support.

The most important thing I just noticed is that your repository has an "Unlicense" license, but your file has GPL boilerplate, and they're definitely different animals.

And I think you relatively recently added this line:
```
(add-hook 'compilation-mode-hook #'jack-mode-compilation-hook)
```
but I would not delay this, and just explicitly `(require 'compile)` and immediately add to the list when `jack-mode` is loaded in.  It may also be a good idea to add a `jack-mode-unload-function` so that `unload-feature` (q.v.) will be able to clean up this list, but that's definitely an optional extra.

Following those two issues I think this is good to merge.

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out. :)

**Comment by tarsius** [comment]
This pull-request has been open for over half a year. @nverno could you please get this over the finish line soon, or else close it? If you do the latter but still plan to get this into Melpa eventually, then you might want to add a quick message here. You can ask us to reopen this pull-request when you are ready.

**Comment by nverno** [comment]
Sure, Ill close it for now, and hopefully finish it later. Thankyou

**Pull request closed without merging**
