### PR TITLE
Add Recipe for finito.el

### PR DESCRIPTION
**Pull request by LaurenceWarne**
### Brief summary of what the package does

Allows for viewing, searching and saving of books.

### Direct link to the package repository

https://github.com/LaurenceWarne/finito.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback

I've split up the package into different files - `package-lint` doesn't seem to like that, I get a lot of complaints along the lines of `"finito-var" doesn't start with package's prefix "finito-x"` and `You should depend on xyz if you need abc` (since I haven't added `Package Requires` to anything except `finito.el`).  I've based the format of the extra files on existing projects which are also split up into different files - am I doing something wrong here?

Also apologies if I've missed something else, there are a lot of errors like the above :slightly_smiling_face:.

- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings

All is fine except for the doc of `cl-defmethod`s ([link](https://github.com/LaurenceWarne/finito.el/blob/393619ab2c314f6bc9873a8c2fefa3ab84e4eed1/finito-view.el#L98)) that specify `:before`, `:around` or `:after`, for which I get `All variables and subroutines might as well have a documentation string` - I'm unsure why this is :sweat_smile: (bug?)

**Edit:**
:bug: It's been [reported](https://lists.gnu.org/r/bug-gnu-emacs/2021-03/msg00336.html) and patched, no complaints on Emacs 28.0.50 :tada: 

- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by Boruch-Baum** [comment]
I see that package's README.md install instructions include a `use-package` option that I'm not familiar with, something called `quelpa`. I mention it because at this first glance it looks like it's circumventing MELPA curation by directly performing some kind of fetch from a place other than the MELPA copy of the package ( Is that even how things works? MELPA fetches into its own copy and Emacs users fetch from MELPA's copy? ).

I'm not certain that I understand the inter-play; my questions are: Should there be a note in the install about whether this `quelpa` thing should be used by people using MELPA? Does `quelpa` play nicely with packages that were in the past installed by MELPA? Does a user end up with multple copies of the same package, possibly of different versions, with potential for confusion?

I realize these questions aren't core to this PR for package `finito`, but am asking them here per how use of `quelpa` should be described for MELPA-installed packages.

**Comment by LaurenceWarne** [comment]
> I'm not certain that I understand the inter-play; my questions are: Should there be a note in the install about whether this quelpa thing should be used by people using MELPA? Does quelpa play nicely with packages that were in the past installed by MELPA? Does a user end up with multple copies of the same package, possibly of different versions, with potential for confusion?

At the moment I'm just suggesting [quelpa](https://github.com/quelpa/quelpa) since the package is not yet on melpa - so the quelpa option would not be used if someone wanted to install it from melpa.  I see on the README I forgot to mention this requires installation of a couple more packages (linked above and https://github.com/quelpa/quelpa-use-package).  I've updated the README installation instructions: https://github.com/LaurenceWarne/finito.el#installation.  I should have made this clear initially, apologies for the confusion.

**Comment by Boruch-Baum** [comment]
On 2021-08-17 01:54, LaurenceWarne wrote:
>    apologies for the confusion.

No need. This `quelpa` package is something new for me to learn about
and mull over.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
Sorry for the long turnaround on this one.  Regarding package-lint, I think you're fine -- see the documentation for `package-lint-main-file` for more.  One way to make use of this variable is to add the following somewhere in each of your secondary files (just make sure that it isn't inside your `;;; Commentary` block):

```elisp
;; Local variables:
;; package-lint-main-file: "my-main-file.el"
;; end:
```

I think you are right that there's a checkdoc bug re: the docstrings.

And some very minor lints, fyi:
- finito-request.el#L126: You can use `not` or `null`
- finito-buffer.el#L107: `concat` may be unneeded; `insert` can take multiple arguments
- finito-buffer.el#L111: `concat` may be unneeded; `insert` can take multiple arguments
- finito-buffer.el#L116: `concat` may be unneeded; `insert` can take multiple arguments
- finito-buffer.el#L123: `concat` may be unneeded; `insert` can take multiple arguments
- finito-buffer.el#L124: `(-repeat (min rating 100) ?★)` could use the builtin `(make-string (min rating 100) ?★)`
- finito-buffer.el#L133: `concat` may be unneeded; `insert` can take multiple arguments
- finito-buffer.el#L151: `concat` may be unneeded; `insert` can take multiple arguments

**Comment by LaurenceWarne** [comment]
> Sorry for the long turnaround on this one.

No problem, thanks for taking the time!

> Regarding package-lint, I think you're fine -- see the documentation for package-lint-main-file for more. One way to make use of this variable is to add the following somewhere in each of your secondary files (just make sure that it isn't inside your ;;; Commentary block):

Nice, I didn't know this existed.  Thanks for this and the other pointers.

**Comment by Boruch-Baum** [comment]
On 2021-08-29 11:37, Chris Rayner wrote:
>    Sorry for the long turnaround on this one. Regarding package-lint, I
>    think you're fine -- see the documentation for package-lint-main-file
>    for more. One way to make use of this variable is to add the following
>    somewhere in each of your secondary files (just make sure that it isn't
>    inside your ;;; Commentary block):
>
> ;; Local variables:
> ;; package-lint-main-file: "my-main-file.el"
> ;; end:

Glad I was still lurking on this thread. I didn't know about that
variable. A very useful tip, thanks. I've implemented a bit differently,
in the project directory's `.dir-local.el file'. For package w3m, which
weighs in at more than 160 elisp files:

    ((nil . ((package-lint-main-file . "w3m.el")
    	    (indent-tabs-mode . t))))
    ;; Local Variables:
    ;; no-byte-compile: t
    ;; End:

So no need to modify any project files at all.

I have a follow-up question. I don't see an automated method to perform
package-lint on all of a project's files in one go, with output
accumulating in a single buffer. Does such a function exist? If not, I
can contact @purcell with an issue or a patch.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
Using dir-locals is a great tip, I'll jot that down too.

> Does such a function exist?

I wasn't sure, but I found `package-lint-batch-and-exit` which is intended for the command line, but it has a helper function `package-lint-batch-and-exit-1` that looks like it does this.

**Comment by Boruch-Baum** [comment]
On 2021-08-31 19:11, Chris Rayner wrote:
>    Using dir-locals is a great tip, I'll jot that down too.
>
>      Does such a function exist?
>
>    I wasn't sure, but I found package-lint-batch-and-exit which is
>    intended for the command line, but it has a helper function
>    package-lint-batch-and-exit-1 that looks like it does this.

I saw that and interpreted it a bit differently, but it does look like
the closest fit to be a basis for an interactive feature. Should be
simple to spoon-feed it a list of elisp files from a directory root ...

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by LaurenceWarne** [comment]
If it's helpful, `package-lint-main-file` is respected by the linting done by https://github.com/alphapapa/makem.sh.

**Comment by Boruch-Baum** [comment]
On 2021-08-31 19:11, Chris Rayner wrote:
> I wasn't sure, but ...

Done!

https://github.com/purcell/package-lint/pull/218

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Pull request merged**
