### PR TITLE
Add recipe for mini-modeline

### PR DESCRIPTION
**Pull request by kiennq**
### Brief summary of what the package does

Merge mode line and minibuffer into one.

### Direct link to the package repository

https://github.com/kiennq/emacs-mini-modeline

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Noticing some similarity to the independently developed package, [feebleline](https://github.com/tautologyclub/feebleline/).  @kiennq, have you seen that package?

**Comment by kiennq** [comment]
I've first heard of that package when I try to pr my package on [reddit](https://www.reddit.com/r/emacs/comments/cfovww/minimodeline_display_mode_line_in_minibuffer/).
AFAIK, there're some similar packages to mine:
- [feebleline](https://github.com/tautologyclub/feebleline/)
- [awesome-tray](https://github.com/manateelazycat/awesome-tray)
- [minibuffer-line](https://elpa.gnu.org/packages/minibuffer-line.html)

The main differences with those packages are:
- You can bring the modeline as it to minibuffer. The other only offer a slim down version of modeline or only some predefined components only. I'm not sure how much you can customize it.
- I've gone to a great length of trying to merge the echo area and modeline in minibuffer.
  - Intercept `message` to display message on placeholder in minibuffer. `awesome-tray` did the same though.
  - Intercept `current-message` and merge them to minibuffer
  - Disable `echo-keystrokes` when needed
  - Other small optimization to make sure you don't have to sacrifice perf more than when you turn on mode line.
  - etc ....

I'm not listing those differences in my README since I'm not aware of those packages when I first created mine though.

**Comment by riscy** [comment]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
mini-modeline.el:114: All variables and subroutines might as well have a documentation string
Warning (emacs): 
mini-modeline.el:227: All variables and subroutines might as well have a documentation string
Warning (emacs): 
mini-modeline.el:230: All variables and subroutines might as well have a documentation string
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
1 issue found:

35:36: warning: This file is not in the `cl-lib' ELPA compatibility package: require `cl-lib' instead.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
```
mini-modeline.el:233:Warning (check-declare): said `anzu--cons-mode-line' was
    defined in anzu.el: file not found
mini-modeline.el:234:Warning (check-declare): said `anzu--reset-mode-line' was
    defined in anzu.el: file not found
```

Miscellaneous and minor:
- mini-modeline.el#L282: Parentheses should be gathered together on one line
- mini-modeline.el#L309: Parentheses should be gathered together on one line

**Comment by kiennq** [comment]
Thanks, fixed with latest push.

**Comment by purcell** [comment]
Thanks! Notes:

- Prefer to `let`-bind `inhibit-read-only` [here](https://github.com/kiennq/emacs-mini-modeline/blob/b1ce74d7297cbb913f19c96a1c8ef8870f79012d/mini-modeline.el#L117-L120)
- Don't autoload the enable/disable functions: they are an implementation detail of the global minor mode.
- Prefer `dolist` or `mapc` to `--each`: you really don't need to depend on `dash` for this basic functionality.
- You don't actually need `symbol-name` [here](https://github.com/kiennq/emacs-mini-modeline/blob/b1ce74d7297cbb913f19c96a1c8ef8870f79012d/mini-modeline.el#L222)

None of these are a blocker to merging, though, so I'll go ahead and do that now, and you can fix the above points in your own time. Welcome to MELPA!

**Pull request merged**
