### PR TITLE
Add package pyconf

### PR DESCRIPTION
**Pull request by andcarnivorous**
### Brief summary of what the package does

This package allows to create and run python execution configurations similar to the ones from dap-mode.
Only byte-compile complaint is a docstring too long.

### Direct link to the package repository

https://github.com/andcarnivorous/pyconf

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for your patience!  Quick first pass --

`pyconf.el` with byte-compile using Emacs 28.1:
```
pyconf.el:71:8: Warning: docstring wider than 80 characters
```

`pyconf.el` with package-lint 20220607.738:
```
1 issue found:
6:23: warning: Use a non-snapshot version number for dependency on "pyvenv" if possible.
```
I [see](https://stable.melpa.org/#/?q=pyvenv) there is for example a v1.21 which you could use to pacify this warning.

I also notice your `;;; Commentary` -- while great -- uses tabs instead of spaces to align some of the code; probably you are using some number other than 8 as your default tab width, but for other users (and in browsers, such as when viewing the MELPA index) things look quite a bit skewed right:
image

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to ping for another pass.

**Comment by andcarnivorous** [comment]
Hey sorry, was gonna update this soon after but got days off and traveled a bit so I kinda forgot about it :P I updated the documentation to correct the pyvenv version to 1.21 (latest one and also the one I am using) and tried to correct the indentation (I think it's something that happens with the comment-region, it's quite odd but hopefully it looks fine now.)
Regarding the docstring,  I mentioned in PR that it is failing, however the args alone of that function take up a lot of the characters, I hope this is not a big issue, also because I plan on refactoring the function into smaller ones eventually that will need shorter docs.

**Comment by riscy** [comment]
> I mentioned in PR that it is failing, however the args alone of that function take up a lot of the characters, I hope this is not a big issue, also because I plan on refactoring the function into smaller ones eventually that will need shorter docs.

This is an easy fix -- just rewrite the one-liner docstring like this:
```elisp
  "Execute COMMAND-S pointing to PATH-TO-FILE.
Set the `default-directory' to EXEC-DIR if provided and pass the
PARAMS given.  Load with `pyvenv' the VENV virtualenv if provided
and set the ENV-VARS if provided."
```
And that should put the checklist behind us.

**Comment by andcarnivorous** [comment]
@riscy Done! Had either no idea or forgotten you could do that with docstrings, sorry lol

**Comment by riscy** [comment]
Great thanks -- taking a closer look now.

As I look at this, my first question is whether something similar hasn't already been written (that you could also potentially contribute to).  pyconf is relatively short at 90 loc -- not necessarily a bad thing -- but also less than a month old, and may deserve some more time to develop its niche.  Check out some of these similar-sounding packages https://melpa.org/#%2F%3Fq=python+env and let me know what you think.  Have you had a chance to try any of these out, especially the more popular ones, and compare to your approach?

A couple minor suggestions on the code itself.  In `pyconf-run-python-proc` you check the truthiness of the variable `venv` on line 79, but before that you have set it to `""`.  In elisp, unlike in Python, `""` is truthy, so that form will never execute in the way you intended.  While I'm here, if you're mixing `if` and `progn` (without an "else" form) then you should just use `when` as on line 80.

Less importantly, this file contains a mixture of tabs and spaces used for indentation which can be difficult to navigate and/or may display strangely for people who have customized tab width.  Typically everyone sticks with spaces in the elisp world these days `(setq-default indent-tabs-mode nil)`.  Also, the embellishment `;;;;;...` below your `;;; Commentary` is unnecessary, and it will show up in the MELPA index as part of your package's description.

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out. :)

**Comment by andcarnivorous** [comment]
Hi thanks for the feedback, especially on the silly mistakes in the elisp code.

> As I look at this, my first question is whether something similar hasn't already been written (that you could also potentially contribute to). pyconf is relatively short at 90 loc -- not necessarily a bad thing -- but also less than a month old, and may deserve some more time to develop its niche. Check out some of these similar-sounding packages https://melpa.org/#%2F%3Fq=python+env and let me know what you think. Have you had a chance to try any of these out, especially the more popular ones, and compare to your approach?
I use daily several of the mainstream python related modes (pyvenv,  pyenv, lsp-mode, dap-mode, python-mode, etc...) and the only mode I found that has a similar utility is dap-mode. However, it requires to have debugpy installed, and executes your code with a lot of overhead and with dap-ui (if you have that enabled by default), so there is no easy/intuitive way to make a config to just execute your python module I believe. With this mode you don't need to have debugpy install and not even lsp-mode, it's just a mode that builds your `python` command and sets the virtual env you want to use. 

> A couple minor suggestions on the code itself. In `pyconf-run-python-proc` you check the truthiness of the variable `venv` on line 79, but before that you have set it to `""`. In elisp, unlike in Python, `""` is truthy, so that form will never execute in the way you intended. While I'm here, if you're mixing `if` and `progn` (without an "else" form) then you should just use `when` as on line 80.

I believe I have addressed these mistakes in the last commits on main.
 
> Less importantly, this file contains a mixture of tabs and spaces used for indentation which can be difficult to navigate and/or may display strangely for people who have customized tab width. Typically everyone sticks with spaces in the elisp world these days `(setq-default indent-tabs-mode nil)`. Also, the embellishment `;;;;;...` below your `;;; Commentary` is unnecessary, and it will show up in the MELPA index as part of your package's description.

I have used untabify and it should be just spaces now. Did not know about the `(setq-default indent-tabs-mode nil)`, thanks!

**Comment by riscy** [comment]
Apologies on the time since reviewing - hope this wasn't too much of an inconvenience.

Everything looks good on this end, so I'll go ahead and merge now.

**Pull request merged**
