### PR TITLE
Add go-capf

### PR DESCRIPTION
**Pull request by phikal**
### Brief summary of what the package does

A gocode based completion backend from `completion-at-point`.

### Direct link to the package repository

https://git.sr.ht/~zge/go-capf

### Your association with the package

I'm the maintainer and creator.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback

    ~~I've used version 0.7 from melpa-stable.~~
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
These checks are semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd>:
```
Warning (emacs): 
go-capf.el:54: Name emacs should appear capitalized as Emacs
Warning (emacs): 
go-capf.el:100: First sentence should end with punctuation
Warning (emacs): 
go-capf.el:100: Argument `str' should appear (as STR) in the doc string
```

<kbd>M-x package-lint</kbd> (using version 20190606.2210):
```
1 issue found:

105:1: error: "go-completion-at-point-function" doesn't start with package's prefix "go-capf".
```

**Comment by phikal** [comment]
All except the last issue were added by a few extra commits since I opened this pull request, and I've fixed them now.

The last one

    105:1: error: "go-completion-at-point-function" doesn't start with package's prefix "go-capf".

is still a bit "hard" to fix, since go-capf is just short for go-completion-at-point...

**Comment by purcell** [comment]
> ```
> error: "go-completion-at-point-function" doesn't start with package's prefix "go-capf".
> ```
> 
> 
> is still a bit "hard" to fix, since go-capf is just short for go-completion-at-point.

True. I'd probably just name the function `go-capf`, though. (You could `defalias` it to the longer name, and `package-lint` probably wouldn't notice, at least until I start detecting that in `package-lint`...)

**Comment by phikal** [comment]
I renamed the function, but didn't do the defalias. After all, before it's published there's no need to ensure backwards compatibility, and another name is just another name.

**Comment by purcell** [comment]
Avoid the `executable-find` [here](https://git.sr.ht/~zge/go-capf/tree/master/go-capf.el#L37) -- there's no need to lock the executable to the specific version on the PATH at the time this file is loaded, because the PATH might change later. Setting this to simply "go" would work as expected, so just do that. You can detect the absence of the executable later if necessary.

But apart from that, this looks good, so I'll go ahead and merge. Thanks for your patience.

**Pull request merged**
