### PR TITLE
Add lambdapi-mode

### PR DESCRIPTION
**Pull request by gabrielhdt**
### Brief summary of what the package does

This package provides a major mode for editing Lambdapi source code.

### Direct link to the package repository

https://github.com/Deducteam/lambdapi

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Cool!  Here's a quick (automated) run through the checklist -- hope this helps.

### lambdapi-abbrev.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
```
1 issue found:
28:70: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
```


### lambdapi-capf.el ###

byte-compile-file (using Emacs 26.3):
```
lambdapi-capf.el:31:55:Warning: reference to free variable `company-backends'
lambdapi-capf.el:31:55:Warning: assignment to free variable `company-backends'
```
You can silence these with an empty forward-declaration, i.e. `(defvar company-backends)`.

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!


### lambdapi-input.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
```
1 issue found:
266:1: warning: Closing parens should not be wrapped onto new lines.
```


### lambdapi-mode.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!

### lambdapi-site-file.el ###

**Maybe you want to `:exclude` this file from the recipe, based on its commentary?**

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
lambdapi-site-file.el:0: The first line should be of the form: ";;; package --- Summary"
Warning (emacs): 
lambdapi-site-file.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
lambdapi-site-file.el:7: You should have a section marked ";;; Code:"
Warning (emacs): 
lambdapi-site-file.el:16: The footer should be: (provide 'lambdapi-site-file)\n;;; lambdapi-site-file.el ends here
```

package-lint-current-buffer (using version 20200408.203):
- No issues!


### lambdapi-smie.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!


### lambdapi-vars.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!


### Loadability ###

Running #'load on each file:
```
Loading lambdapi-abbrev.el
Loading lambdapi-capf.el
Loading lambdapi-input.el
Loading lambdapi-mode.el
Loading lambdapi-site-file.el
Loading lambdapi-smie.el
Loading lambdapi-vars.el
Done.
```

### License ###

- GitHub API found `Other`
  - It looks hard to map the existing license to one of the GPL compatible licenses https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses -- perhaps this code could be licensed under one of those?
- Please add license boilerplate or an [SPDX license identifier](https://spdx.org/using-spdx-license-identifier) to lambdapi-abbrev.el
- Please add license boilerplate or an [SPDX license identifier](https://spdx.org/using-spdx-license-identifier) to lambdapi-capf.el
- Please add license boilerplate or an [SPDX license identifier](https://spdx.org/using-spdx-license-identifier) to lambdapi-input.el
- Please add license boilerplate or an [SPDX license identifier](https://spdx.org/using-spdx-license-identifier) to lambdapi-mode.el
- Please add license boilerplate or an [SPDX license identifier](https://spdx.org/using-spdx-license-identifier) to lambdapi-site-file.el
- Please add license boilerplate or an [SPDX license identifier](https://spdx.org/using-spdx-license-identifier) to lambdapi-smie.el
- Please add license boilerplate or an [SPDX license identifier](https://spdx.org/using-spdx-license-identifier) to lambdapi-vars.el

**Comment by riscy** [comment]
And please ping when ready for another look.  :)

**Comment by gabrielhdt** [comment]
> And please ping when ready for another look. :)

It is ready for another look, thanks for notifying!

**Comment by riscy** [comment]
Sounds good!

It looks like I was mistaken about the license -- it is definitely on the GPL compatible list.  However, would you still add some license boilerplate to _each_ file, or even simply this line:
```
;; SPDX-License-Identifier: CeCILL Free Software License Agreement v2.1
```
to the top of each of your elisp files above any `;; Commentary`?  I recommend an SPDX-License-Identifier as a one-liner because it's standardized and machine-detectable (although I see in one elisp file you have "License: CeCILL-B").

These still pop up during a byte compile with a "clean" Emacs session:
```
lambdapi-capf.el:32:55:Warning: reference to free variable `company-backends'
lambdapi-capf.el:32:55:Warning: assignment to free variable `company-backends'
```
I notice you have some `require`'s embedded in the function to avoid the warning, but the compiler won't actually run those during byte compilation.  You can remove those embedded forms and, to avoid those warnings, you can use:
```elisp
(defvar-local company-backends)
```
somewhere at the top of the file.

Small stuff:
- lambdapi-input.el#L267: Consider `unless ...` instead of `when (not ...)`
- compnay -> company (in lambdapi-input.el)

**Comment by gabrielhdt** [comment]
Thanks, I have integrated your suggestions, they are waiting to be merged in upstream lambdapi (see https://github.com/Deducteam/lambdapi/pull/364). I'll let you know when it's done.

**Comment by gabrielhdt** [comment]
It has been merged, @riscy, you may proceed to a final (?) check.

**Comment by riscy** [comment]
I'll make one more PR against that repo since I made a mistake above (sorry about that). Then we should be good to go.

**Comment by riscy** [comment]
Great.  Thanks for contributing this to MELPA. :)

**Comment by tarsius** [comment]
@riscy you said:

> you still add some license boilerplate to _each_ file, or even simply this line:
> ```
> ;; SPDX-License-Identifier: CeCILL Free Software License Agreement v2.1
> ```

Yes, one should specify the SPDX-License-Identifier in each file, but the value must be a ... well a SPDX-License-Identifier. "CeCILL Free Software License Agreement v2.1" is the full name of a license, the corresponding identifier is `CECILL-2.1`. See the table header at https://spdx.org/licenses/.

```
;; SPDX-License-Identifier: CECILL-2.1
```

@gabrielhdt please update all the libraries to use the correct value. Thanks.

**Comment by riscy** [comment]
Woops, sorry both about that. :)  I think I must have copied from the wrong column.

**Pull request merged**
