### PR TITLE
added scrum

### PR DESCRIPTION
**Pull request by ianxm**
### Brief summary of what the package does

Generates a scrum board and reports from an org buffer.

### Direct link to the package repository

https://github.com/ianxm/emacs-scrum

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

Not needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
This looks pretty cool.  It should probably be called `org-scrumm` rather than `scrumm` or `emacs-scrumm`,  which fits the naming convention to communicate that it's based on Org,.

**Comment by ianxm** [comment]
I assume you're talking about the package name and not the repository name. I'm fine with changing it to `org-scrum`. Did you mean to use the double 'm'? I will check with the orgmode list if there is any objection to my using that name.

**Comment by alphapapa** [comment]
> I assume you're talking about the package name and not the repository name.

Right, the issue is helping users find it in MELPA.

> Did you mean to use the double 'm'?

No, I must have been reading about SCUMM recently.  :)

> I will check with the orgmode list if there is any objection to my using that name.

I replied to your post there approving the request.  ;)  Seriously, though, there is no process by which to approve package names with `org-` prefixes.  There are many of them on MELPA, and new ones are added frequently.  The only way it could be a problem would be, e.g. if there were already a feature by that name in `org` or `org-contrib`.

**Comment by ianxm** [comment]
Thanks for the "approval." I suppose the `org-` prefix doesn't imply it is part of org or endorsed by org, but I thought some might see it that way so I at least wanted to let the people behind org have a chance to disavow it.

I've changed the name in the emacs-scrum package and updated this PR. Let me know if you'd like me to squash the commits.

**Comment by ianxm** [comment]
So, does thumbs up mean you acknowledge the name change, or does it mean you want me to squash the commits?

**Comment by riscy** [comment]
> So, does thumbs up mean you acknowledge the name change, or does it mean you want me to squash the commits?

No need.

**Comment by riscy** [comment]
- It feels like the `:group` of `defgroup org-scrum` should be `org` as opposed to `org-scrum` itself.

Some notes on the style -- I feel like the code could be better flattened and factored out for better maintainability:
- The lambda spanning around 256--268 almost feels like it could just be its own function; it is also underindented, which makes the region a little difficult to parse.
- Similarly with the really big lambda beginning around 133 -- this one _really_ feels like it should be a function -- it even contains a lambda within the lambda.
- Similarly with the lambda around 365--383.  And around here, why not continue to use the `let` block to define the variables instead of using `setq`?  Something like: ```elisp
            (let* ((hdg (nth 4 (org-heading-components)))
                   (bracket (string-match "\\[" hdg))               ; index of bracket character
                   (id (or (org-entry-get (point) "TASKID") "\\_\\_\\_"))
                   (owner (or (org-entry-get (point) "OWNER") "\\_\\_\\_"))
                   (est (or (org-entry-get (point) "ESTIMATED") "\\_\\_\\_")))
              (when bracket (setq hdg (substring hdg 0 (1- bracket))))
              (setq str (concat str (format "...
```

And some other very minor things:
- org-scrum.el#L111: It's safer to sharp-quote function names; use `#'`
- org-scrum.el#L112: It's safer to sharp-quote function names; use `#'`
- org-scrum.el#L157: It's safer to sharp-quote function names; use `#'`
- org-scrum.el#L158: It's safer to sharp-quote function names; use `#'`
- org-scrum.el#L249: It's safer to sharp-quote function names; use `#'`
- org-scrum.el#L266: It's safer to sharp-quote function names; use `#'`
- org-scrum.el#L130: It's safer to sharp-quote function names; use `#'`
- org-scrum.el#L6: Prefer `https` over `http` (if possible)
- org-scrum.el#L23: Prefer `https` over `http` (if possible)
- In the README, "here is are example" -> "here is an example"

**Comment by ianxm** [comment]
thanks for the detailed review. All are good suggestions. I've pushed the changes.

**Comment by riscy** [comment]
No trouble.  This looks good to go -- the following are non-blocking but I'll leave them for your consideration:

- org-scrum.el#L187: Single-line comments should begin with `;;`
- org-scrum.el#L190: Single-line comments should begin with `;;`

**Comment by ianxm** [comment]
changes made. thanks!

**Pull request merged**
