### PR TITLE
Add "adaptive-theme" Emacs package

### PR DESCRIPTION
**Pull request by alvarocsm91**
### Brief summary of what the package does

Adaptive Theme package has been created to protect your eyesight while working near windows or outside buildings. Its functions change your theme from light to dark and backwards, depending on the hour.

This package provides three functions, explained from less to more resource usage. The "adaptive-theme" function allows to load different Emacs themes automatically based on the hour set up by the user or by default sunset and sunrise hours.
The "adaptive-theme-location" function allows to load different Emacs themes automatically based on the city set up by the user or by default sunset and sunrise city hours.
The "adaptive-theme-autolocation" function allows to load different themes automatically based on the nearest city detected.

### Direct link to the package repository

https://github.com/alvarocsm91/adaptive-theme

### Your association with the package

I'm the maintainer, contributor and enthusiastic user.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
This is an iteration of #7059.

**Comment by riscy** [comment]
Quick run over the checklist --

### adaptative-theme.el ###

byte-compile (using Emacs 27.1):
```
adaptative-theme.el:588:1:Warning: the function `org-web-tools--get-url' is
    not known to be defined.
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200816.24):
```
3 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
10:12: warning: "A/1" is not a valid version. MELPA will handle this, but other archives will not.
```


### Loadability ###

Verifying ability to #'load each file:
```
Loading adaptative-theme.el
Done.
```

### Package ###

- GitHub API found `GNU Lesser General Public License v3.0`
- adaptative-theme.el (GPL) -- Adaptative Emacs theme to protect your eyesight

(Note above your repo is using the LGPL, but your file appears to have the boilerplate of the general GPL which are different licenses; instead of general GPL boilerplate you could always use an [SPDX-License-Identifier](https://spdx.org/using-spdx-license-identifier) for the LGPL)

**Comment by riscy** [comment]
I should add, you probably need to add a `Package-Requires` on a later version of org than comes with Emacs 27.1 to catch the missing function in the byte-compiler.

**Comment by riscy** [comment]
Feel free to ping when you're ready for another look.

**Comment by alvarocsm91** [comment]
Emacs word deleted ins summary.
A/1 version changed by 1.0.0.
change keywords by founded with finder-list-keywords.

**Comment by alvarocsm91** [comment]
I don't understand this comment:
"I should add, you probably need to add a Package-Requires on a later version of org than comes with Emacs 27.1 to catch the missing function in the byte-compiler."
I'm using GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.17.3) of 2020-05-22

**Comment by riscy** [comment]
Thanks --

> Emacs word deleted ins summary.

Currently it reads "Adapt`at`ive Emacs theme to protect your eyesight" but if you want to follow the letter of the lint, prefer "**Adaptive** theme to protect your eyesight".

> I don't understand this comment:

My mistake.  It turns out you are missing `org-web-tools` in your Package-Requires (which currently only contains `;; Package-requires: ((emacs "25.1"))`).

I've had a taker to look more closely at the package and I feel like there are quite a number of issues that could still be addressed:

- Inlining a bunch of defvars into the defun of `adaptative-theme-location` is unorthodox -- really they should appear at the top level unless there's a compelling reason for them to be here (there's not).  These defvars also don't begin with your package's prefix (adaptive-theme-); the linters aren't able to pick up on this but they will if you move the defvars to the top level
- These defvars appear to be here so that you can `setq` them immediately after, but if you need locally scoped variables then you should read about `let` and `let*` forms
- Minor, but it would probably also be a good idea to `(require 'org-web-tools)` at the top-level, since this appears to be a hard requirement
- This block won't do anything -- it will simply define an anonymous function that gets thrown away:
```elisp
  (if (/= atl--is-internet-up 0)
      ;; If internet is not connected
      (lambda ()
        (adaptative-theme(light-theme dark-theme))
        (progn (message "No network detected") nil)
        (return)))
```

I hope that gives you something to start with -- there are communities out there (reddit is a good one) that you can ask for to get people to look at your package and provide elisp feedback.
but is also malformed (`adaptive-theme(light-theme dark-theme)`).

**Comment by riscy** [comment]
I just noticed (I think) that this should be "adaptive" theme instead of "adaptative" theme -- or is that intentional?

**Comment by alvarocsm91** [comment]
Just modify lambda malformed function!

**Comment by riscy** [comment]
Thanks for getting back.  For your feedback, I think you've changed the malformed part to `(adaptive-theme (dark-theme light-theme))` (i.e. added a space), but the block still won't do anything.  I think most of my other comments still stand.

**Comment by alvarocsm91** [comment]
Hello!

- I have already removed all the emacs references in the adative-theme.el file.

- I refer to the package "org-web-tools" in the header.

- I don't refer to local variables with respect to the package because I make them with respect to the function that contains them.

- Many of the defined variables do not have to be initialized in the function as it gets them automatically.

- I don't use let because of the previous comment, you don't have to define the initial value of the variables.

- require 'org-web-tools) is used when necessary, because it is not necessary for the whole package, this means that you do not have to install it if you are not going to use it.

**Comment by riscy** [comment]
Hello, the "Emacs" in the package summary looks fixed.  Thanks for that.

It may be that you're referring to org-web-tools in the header on a develop branch -- at least on the default branch I just see `(require 'org-web-tools)`.   There is no Package-Requires on it.  I think this covers your first and last bullets.  However, now I'm also noticing calls to `gruvbox-light-soft` and `gruvbox-dark-hard` -- is gruvbox a prerequisite for this package?

> I make them with respect to the function that contains them.

Emacs Lisp might be different from what you're used to (I am thinking maybe C due to the Doxygen style docstrings):
```
(defvar test-3--variable 0)

(defun test-3 ()
  (defvar test-3--variable)
  (setq test-3--variable 10))

(test-3)

test-3--variable  ; this is now 10!
```
They "leak" and they could clash with variables from another hypothetical package called `atl`.  I think the above issue covers three of your bullets, correct me if I'm wrong.

The malformed lambda I mentioned above seems malformed in part because you appear to be using a C-like function invocation: `(adaptive-theme (light-theme dark-theme))` but I think you should test that code out, because the block is just creating an anonymous function and doing nothing with it.

I'm not digging too deeply because I think there are still some fundamental issues we need to shake out, but I'd recommend reformatting code that looks like this:
```elisp
  (if (< at--init-hour-int am-hour)

      ;; true if init hour <  dawn hour is night

      (setq at--is-day nil)

    ;; Evaluate minutes if is the same hour

    (if (= at--init-hour-int am-hour)

        ;; evaluate minutes

        (if (< at--init-min-int am-min)

            ;; true if init min <  dawn min is night

            (setq at--is-day nil)

          ;; Evaluate seconds if is the same minute

          (if (= at--init-sec-int am-sec)
```
it seems to have excessive vertical space (although we can call that subject), but this is a perfect use case for the `cond` special form.

**Comment by alvarocsm91** [comment]
Last changes!

- Include (require 'org-web-tools) in file header.

- Change function prefix with package prefix.

- Include al variable initialization and its description.

- Next function detect if you are connected, if you are connected, you can use org-web-tools functions, else, execute apadtive-theme function that dont require internet connection. Yes, it works correctly.
"
  (if (/= adaptive-theme--is-internet-up 0)

      ;; If internet is not connected

      (lambda ()
        (adaptive-theme (light-theme dark-theme))
        (progn (message "No network detected") nil)
        (return)))
"
I'm sorry but i don't understand why is malformed i just saw many lambda functions in recomended codes and i can't detect the error. 

- I don't understand either what soy say about vertical spaces, i think is correct in all file.

Thanks for all.

**Comment by riscy** [comment]
Your `Package-Requires` should look like this:

```
;; Package-requires: ((emacs "25.1") (org-web-tools "1.1.1"))
```

Remember to run `package-lint` and check the byte-compile output, they're indispensable! :)

**Comment by alvarocsm91** [comment]
Package requires updated with org-web-tools 1.1.1

package-lint report not issues found and no problems with byte compile or byte recompile file functions.

**Comment by riscy** [comment]
I think you still haven't addressed many of the comments [here](https://github.com/melpa/melpa/pull/7102#issuecomment-687899154) -- please take another  look.

> I'm sorry but i don't understand why is malformed i just saw many lambda functions in recomended codes and i can't detect the error.

I would encourage you to reach out to the greater community on this one (feel free to link to this PR).  Here's a hint -- you can extract that lambda into a named function:
```elisp
(defun internet-isnt-up ()
  (adaptive-theme (light-theme dark-theme))
  (progn (message "No network detected") nil)
  (return))
```
and read the byte-compiler's output.

**Comment by alvarocsm91** [comment]
Hello,

I re-read the comment you say:

- I inlining a "brunch" of variables to help me an other people to understand the code, I try with let but give many warnings to me when i try to write the variable description, because of that i'm using defvars.

- Those variables all ready are defined with the prefix variable.

- I don't define those variables in top level to don't us space that i don't use, and don't use let because i cant setup the variable definition.

- I don't put (require 'org-web-tools) at the top to don't downoad this package with this module. Is important to know that you can use this function adaptative-theme with all emacs versions.

- The internet function is all ready explained. It works and is well formed.

- I know that i can create a simply function to use one time one function but i think is waste many time, for this situations we have lambda functions.

- My byte-compyile function don't give nothing to me, no warnings, no linterns no problems and it works without problems. What are you reading with your byte compile? which version are you using?

I really think that i waste many time with those "pretty code" comments, please make a list with the chages, make pull request if you want and if are important i will read and include but i cant continue with that. I think that is interesant package to many people.

**Comment by riscy** [comment]
I apologize in that case -- I don't personally think this code is ready, but we can tag another MELPA maintainer in if you like.

**Comment by alvarocsm91** [comment]
If you want to tag another MELPA mantainer no problem.

Please make me a list with all issues.

If you detect any warning include the report in your comment.

**Comment by alvarocsm91** [comment]
@riscy are you there?

**Comment by riscy** [comment]
Hi,

I'm still around if you have any specific questions, but I don't think this code is ready to be included in MELPA.  I also think it isn't worth pulling in another maintainer, because they'll tell you similar.

There are a lot of PR's open as you can see, so I can't burn too much time on your submission.  You've addressed some of my comments - thanks for that - but I'll repeat from above:

- Inlining a bunch of defvars into the defun of adaptative-theme-location is unorthodox -- really they should appear at the top level unless there's a compelling reason for them to be here (there's not).  If you want to disregard
- The `(if (/= adaptive-theme--is-internet-up 0)` block won't do anything -- it will simply define an anonymous function that gets thrown away.
- Re: calls to gruvbox-light-soft and gruvbox-dark-hard -- is gruvbox a prerequisite for this package?
- Your code byte-compiles with warnings from a clean start: `adaptive-theme.el:646:1:Warning: the function `org-web-tools--get-url' is not known to be defined.`  You can read about `declare-function` to solve this, or -- since this is in your `Package-Requires` list -- just add the `(require 'org-web-tools)`
- I will concede that the vertical space recommendation is a "pretty code" comment :)

**Comment by tarsius** [comment]
There have been no new commits or a reply since the above, so I am closing this now.

**Pull request closed without merging**
