### PR TITLE
Update ox-rst recipe

### PR DESCRIPTION
**Pull request by msnoigrs**
### Brief summary of what the package does

reSturcturedText Back-End for Org-Mode Export Engine.

### Direct link to the package repository

https://github.com/msnoigrs/ox-rst

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. You've got a spurious file in this pull request, though. Please can you fix it?

**Comment by msnoigrs** [comment]
I'm sorry for my mistake previous pull request. fixed it. Please look this again.

**Comment by purcell** [comment]
No worries: merged now, thanks.

**Comment by msnoigrs** [comment]
Thanks.

**Pull request merged**
