### PR TITLE
Add recipe for casual-lib

### PR DESCRIPTION
**Pull request by kickingvegas**
### Brief summary of what the package does

Casual Lib is a package of common routines used by the Casual porcelains.

### Direct link to the package repository

https://github.com/kickingvegas/casual-lib

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  You certainly have a clearer view of the `casual-` space than I do, but how many different casual packages do you suppose this library will be used by?  This may be a good time to invoke the [rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)).

Also, for functions like this --
```
(defun casual-lib-buffer-writeable-p ()
  "Predicate to test if buffer is writeable."
  (not buffer-read-only))
```
it seems like it's not such a burden to inline into the relevant code (and actually as a dev I would much prefer that over).  If you speculate you may need to generalize this pattern in the future, I'd just wait until that specific future arrives.

**Comment by kickingvegas** [comment]
@riscy - wrt to in-lining predicates; the problem with that approach is that I must define a lambda to get it to work with a Transient macro, so instead would prefer to writing a dedicated function instead of multiple instances of lambda. Is this coding practice a blocker for acceptance into MELPA?

As far as the number of Casual packages, I have five currently defined that I plan to use this library to consolidate code:
- Calc
- Info
- Dired
- Avy
- I-Search

I have more packages that I plan to deploy:
- ibuffer
- Bookmarks
- Re-Builder
- Edebug

**Comment by kickingvegas** [comment]
@riscy Furthermore I do plan on submitting to MELPA next week an umbrella package called `casual-suite` that will offer users a single source to pick up all Casual porcelains. The work on package renaming and getting `casual-lib` in place is to support distributing `casual-suite` in a maintainable fashion.

**Comment by riscy** [comment]
>  Is this coding practice a blocker for acceptance into MELPA?

No, not at all, and I agree with you now that I understand.  I just wanted to make sure - but merging this now.

**Pull request merged**
