### PR TITLE
Add recipe for elmame.

### PR DESCRIPTION
**Pull request by Iacob**
### Brief summary of what the package does

This package containing a mame front-end for emacs.

### Direct link to the package repository

https://github.com/Iacob/elmame

### Your association with the package

I'm the original author.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [] My elisp byte-compiles cleanly
- [] `M-x checkdoc` is happy with my docstrings
- [] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
I get the following byte compiler warnings on Emacs 30:

<details><summary>Log @2023-04-24 12:40:47 -0400</summary>
search filter: "#latest #linked-errors byte-comp warn"
<table>
<thead><th>Package</th><th>Status</th><th>Info</th><th>Time</th></thead>
<tbody>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame-config.el:19:11 Warning: ‘make-variable-buffer-local’ not called at toplevel</td><td>7533.874683</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame-config.el:19:12 Warning: ‘make-variable-buffer-local’ not called at toplevel</td><td>7533.874687</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame-config.el:19:13 Warning: ‘make-variable-buffer-local’ not called at toplevel</td><td>7533.874690</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame-config.el:19:14 Warning: ‘make-variable-buffer-local’ not called at toplevel</td><td>7533.874693</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame-config.el:19:15 Warning: ‘make-variable-buffer-local’ not called at toplevel</td><td>7533.874696</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame-config.el:19:16 Warning: ‘make-variable-buffer-local’ not called at toplevel</td><td>7533.874700</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame-config.el:19:17 Warning: ‘make-variable-buffer-local’ not called at toplevel</td><td>7533.874704</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame-config.el:17:91 Warning: the function ‘elmame-mame-read-user-config’ is not known to be defined.</td><td>7533.884726</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame-config.el:31:54 Warning: the function ‘widget-value-set’ is not known to be defined.</td><td>7533.884729</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame-pkg.el:2:2 Warning: the function ‘define-package’ is not known to be defined.</td><td>7534.214752</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame.el:14:30 Warning: ‘insert-file’ is for interactive use only; use ‘insert-file-contents’ instead.</td><td>7534.214765</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame.el:11:62 Warning: assignment to free variable ‘elmame-mame-context’</td><td>7534.214773</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame.el:54:127 Warning: reference to free variable ‘elmame-mame-context’</td><td>7534.214779</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame.el:6:158 Warning: value from call to ‘mapcar’ is unused; use `mapc' or `dolist' instead</td><td>7534.214783</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame.el:6:198 Warning: ‘beginning-of-buffer’ is for interactive use only; use ‘(goto-char (point-min))’ instead.</td><td>7534.214786</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame.el:4:210 Warning: the function ‘elmame-mame-config-panel’ is not known to be defined.</td><td>7534.214792</td></tr>
<tr><td>elmame</td><td>byte-compilation</td><td>elmame.el:23:70 Warning: the function ‘elmame-mame-load-machine-defs’ is not known to be defined.</td><td>7534.214795</td></tr></tbody>
</table>
</details>


I took a quick look at the code.
I would suggest turning on flymake-mode and fixing all the warnings/errors it raises.
package-lint is also a useful package for linting your program.

**Comment by riscy** [comment]
CI is failing due to:

```
... error "Illegal multi-line package description in %s"
```
Likely this is because of the extra (leading) newline in your -pkg.el (you should also solve the extra newline at the start of elmame.el, too)

@progfolio has good advice; here is a quick first pass from my end:

`elmame-config.el` with byte-compile using Emacs 28.1:
```
elmame-config.el:15:39: Warning: `make-variable-buffer-local' not called at
    toplevel
elmame-config.el:65:48: Warning: `make-variable-buffer-local' not called at
    toplevel
elmame-config.el:17:37: Warning: `make-variable-buffer-local' not called at
    toplevel
elmame-config.el:54:48: Warning: `make-variable-buffer-local' not called at
    toplevel
elmame-config.el:55:48: Warning: `make-variable-buffer-local' not called at
    toplevel
elmame-config.el:76:48: Warning: `make-variable-buffer-local' not called at
    toplevel
elmame-config.el:77:48: Warning: `make-variable-buffer-local' not called at
    toplevel
In end of data:
elmame-config.el:91:17: Warning: the function `elmame-mame-read-user-config'
    is not known to be defined.
elmame-config.el:76:31: Warning: the function `widget-value-set' is not known
    to be defined.
```

`elmame-config.el` with checkdoc 0.6.2:
```
elmame-config.el:0: The first line should be of the form: ";;; package --- Summary"
elmame-config.el:0: You should have a section marked ";;; Commentary:"
elmame-config.el:2: You should have a section marked ";;; Code:"
elmame-config.el:101: The footer should be: (provide 'elmame-config)\n;;; elmame-config.el ends here
elmame-config.el:5: All interactive functions should have documentation
elmame-config.el:42: White space found at end of line
```

`elmame-config.el` with package-lint 20230315.1052:
```
18 issues found:
11:0: error: "widget-text-exec" doesn't start with package's prefix "elmame".
11:5: error: You should depend on (emacs "24.3") if you need `defvar-local'.
12:0: error: "text-exec" doesn't start with package's prefix "elmame".
12:5: error: You should depend on (emacs "24.3") if you need `defvar-local'.
13:0: error: "widget-text-working-dir" doesn't start with package's prefix "elmame".
13:5: error: You should depend on (emacs "24.3") if you need `defvar-local'.
14:0: error: "text-working-dir" doesn't start with package's prefix "elmame".
14:5: error: You should depend on (emacs "24.3") if you need `defvar-local'.
15:0: error: "widget-text-rom-dir" doesn't start with package's prefix "elmame".
15:5: error: You should depend on (emacs "24.3") if you need `defvar-local'.
16:0: error: "text-rom-dir" doesn't start with package's prefix "elmame".
16:5: error: You should depend on (emacs "24.3") if you need `defvar-local'.
17:0: error: "widget-extra-args" doesn't start with package's prefix "elmame".
17:5: error: You should depend on (emacs "24.3") if you need `defvar-local'.
25:16: error: You should depend on (emacs "27.1") if you need `json-serialize'.
29:23: error: You should depend on (emacs "27.1") if you need `json-serialize'.
33:19: error: You should depend on (emacs "27.1") if you need `json-serialize'.
37:16: error: You should depend on (emacs "27.1") if you need `json-serialize'.
```

`elmame-mame-machine-info-loader.el` with checkdoc 0.6.2:
```
elmame-mame-machine-info-loader.el:0: The first line should be of the form: ";;; package --- Summary"
elmame-mame-machine-info-loader.el:0: You should have a section marked ";;; Commentary:"
elmame-mame-machine-info-loader.el:1: You should have a section marked ";;; Code:"
elmame-mame-machine-info-loader.el:39425: The footer should be: (provide 'elmame-mame-machine-info-loader)\n;;; elmame-mame-machine-info-loader.el ends here
elmame-mame-machine-info-loader.el:1: All variables and subroutines might as well have a documentation string
```

`elmame-mame-machine-info-loader.el` with package-lint 20230315.1052:
```
1 issue found:
39425:0: warning: Closing parens should not be wrapped onto new lines.
```

`elmame.el` with byte-compile using Emacs 28.1:
```
elmame.el:28:16: Warning: `insert-file' is for interactive use only; use
    `insert-file-contents' instead.
In elmame-mame-save-context:
elmame.el:62:43: Warning: assignment to free variable `elmame-mame-context'
In elmame-mame:
elmame.el:128:49: Warning: reference to free variable `elmame-mame-context'
elmame.el:156:115: Warning: `mapcar' called for effect; use `mapc' or `dolist'
    instead
elmame.el:192:26: Warning: `beginning-of-buffer' is for interactive use only;
    use `(goto-char (point-min))' instead.
In end of data:
elmame.el:210:4: Warning: the function `elmame-mame-config-panel' is not known
    to be defined.
elmame.el:70:23: Warning: the function `elmame-mame-load-machine-defs' is not
    known to be defined.
```

`elmame.el` with checkdoc 0.6.2:
```
elmame.el:0: The first line should be of the form: ";;; package --- Summary"
elmame.el:210: The footer should be: (provide 'elmame)\n;;; elmame.el ends here
elmame.el:11: Name emacs should appear capitalized as Emacs
elmame.el:23: First sentence should end with punctuation
elmame.el:23: First line should be capitalized
elmame.el:26: All variables and subroutines might as well have a documentation string
elmame.el:38: All variables and subroutines might as well have a documentation string
elmame.el:41: All variables and subroutines might as well have a documentation string
elmame.el:44: Argument `name' should appear (as NAME) in the doc string
elmame.el:57: Argument `name' should appear (as NAME) in the doc string
elmame.el:89: All variables and subroutines might as well have a documentation string
elmame.el:103: All interactive functions should have documentation
elmame.el:204: All interactive functions should have documentation
elmame.el:208: All interactive functions should have documentation
```

`elmame.el` with package-lint 20230315.1052:
```
11 issues found:
82:40: error: You should depend on (emacs "25.1") or the seq package if you need `seq-find'.
83:20: error: You should depend on (emacs "25.1") or the seq package if you need `seq-filter'.
98:8: error: You should depend on (emacs "24.4") if you need `string-join'.
123:25: error: You should depend on (emacs "25.1") or the seq package if you need `seq-max'.
127:22: error: You should depend on (emacs "25.1") if you need `alist-get'.
128:17: error: You should depend on (emacs "25.1") if you need `alist-get'.
167:6: warning: Closing parens should not be wrapped onto new lines.
181:7: warning: Closing parens should not be wrapped onto new lines.
182:5: warning: Closing parens should not be wrapped onto new lines.
194:2: warning: Closing parens should not be wrapped onto new lines.
195:7: warning: Closing parens should not be wrapped onto new lines.
```

Package and license:
- Package-Requires mismatch between elmame.el and elmame-pkg.el!
- elmame-pkg.el -- consider excluding this file; MELPA creates one
- GNU Lesser General Public License v3.0 (via API)
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to elmame-config.el
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to elmame-mame-machine-info-loader.el
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to elmame.el

**Comment by Iacob** [comment]
Hello @riscy ,

I made huge updates on the source files and they contains no error and warning now. Could you please restart the build progress?

Thank you very much.

**Comment by riscy** [comment]
Checklist looks good now.  Taking a deeper look --

- Have you considered just calling this project `mame`?  The `el` is redundant (this is an Emacs package, after all).  Alternatively, consider that you've prefixed everything in elmame.el with `elmame-mame` -- this prefix isn't necessary and in most cases you should probably just be using `elmame` as your prefix.  E.g., `elmame-mame-make-shell-command` could just be `elmame-make-shell-command`
- You seem to have fragments of a major mode defined (e.g. you do `(run-hooks 'elmame-mame-mode-hook)`); why not go ahead and define the mode using e.g. `(define-derived-mode elmame-mode fundamental-mode "Mame"` with an idiomatically defined keymap (check other major modes for the norms on how to do this); I think this would help the structure immensely
- Minor, but I'm wondering where you got the data for elmame-mame-machine-info-loader.el?  Maybe you could cite a source (unless this is a novel list of your own creating); that way future devs can come in and help you keep the source data in sync with your list.
- And as a minor style thing, it's typical to close up nested lists with `)))` instead of `) ) )` (the extra spaces are unusual vs. the community style)

**Comment by Iacob** [comment]
Hello @riscy 

Have you considered just calling this project mame? The el is redundant (this is an Emacs package, after all). 
============
That's OK, I will modify the project name and the function prefix. There's a ``-mame'' in the prefix because there's also a ``elmame-mess'' in planning. I will give it another name when the ``mess'' interface finished.

why not go ahead and define the mode using e.g. (define-derived-mode elmame-mode fundamental-mode "Mame" with an idiomatically defined keymap (check other major modes for the norms on how to do this); I think this would help the structure immensely
============
I've never written a major mode before but I will try to write one for this project.

Minor, but I'm wondering where you got the data for elmame-mame-machine-info-loader.el? Maybe you could cite a source (unless this is a novel list of your own creating); that way future devs can come in and help you keep the source data in sync with your list.
============
The machine info loader is generated by the machine info extractor (https://github.com/Iacob/elmame/blob/master/tools/machines_extractor.el), the input source is the output of command ``mame -listxml''

And as a minor style thing, it's typical to close up nested lists with ))) instead of ) ) ) (the extra spaces are unusual vs. the community style)
============
I will update the code and remove these spaces.


I'll come back after changing the code.

Thank you very much.

**Pull request closed without merging**
