### PR TITLE
Add lsp-ruby

### PR DESCRIPTION
**Pull request by gpittarelli**
### Brief summary of what the package does

Implements some Ruby IDE features via [lsp-mode](https://github.com/emacs-lsp/lsp-mode) and [this solargraph gem](https://github.com/castwide/solargraph)

### Direct link to the package repository

https://github.com/emacs-lsp/lsp-ruby

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

N/A

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

I know little about Ruby, but a little about Emacs, so I have this suggestion:
```el
(defun lsp-ruby--render-string (str)
  "Render STR with `ruby-mode' syntax highlighting."
  (ignore-errors
    (with-temp-buffer
      (ruby-mode)
      (insert str)
      (font-lock-ensure)
      (buffer-string))))
```
Instead of using a new temporary buffer and activating `ruby-mode` each time this function is called, you could use a permanent, hidden buffer created when the function is first called, and only activate `ruby-mode` once.  This would likely perform much better, and it would avoid activating whatever hooks the user may have configured for `ruby-mode` every time the function is called.  For example, I do this in https://github.com/alphapapa/helm-org-rifle/blob/master/helm-org-rifle.el#L1530 to avoid activating `org-mode` every time a string is fontified.

**Comment by yyoncho** [comment]
@alphapapa to avoid the hooks you may use  `(delay-mode-hooks (ruby-mode))` .

**Comment by alphapapa** [comment]
@yynozk Thanks, that's good to know, but in this case, I think running `ruby-mode` for every string should still be avoided.  Even if user hooks are delayed, it's still not necessary to do everything the mode does.

**Comment by yyoncho** [comment]
@alphapapa 
```emacs-lisp
(benchmark
 1000
 (with-temp-buffer
   (delay-mode-hooks (ruby-mode))))
```
=> Elapsed time: 0.000112s

**Comment by purcell** [comment]
Good notes above, thanks. I'll merge this now, but yes, @gpittarelli, you should use `delay-mode-hooks` in this code, as above.

**Pull request merged**
