### PR TITLE
Add recipe for osm

### PR DESCRIPTION
**Pull request by minad**
### Brief summary of what the package does

OpenStreetMap viewer

Screenshot

### Direct link to the package repository

https://github.com/minad/osm

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Wow!  This looks really interesting -- I'm looking forward to trying it out.  Here's a quick first pass:

`ol-osm.el` with package-lint 20220213.1457:
```
2 issues found:
37:0: error: "ol-osm-open" doesn't start with package's prefix "osm".
50:0: error: "ol-osm-store" doesn't start with package's prefix "osm".
```
These arise because I'm setting `package-lint-main-file` based on the name of the package -- prefer all files to have the same prefix as the package.

`osm.el` with byte-compile using Emacs 27.1:
```
osm.el:460:47:Warning: assignment to free variable
    `bookmark-make-record-function'
In end of data:
osm.el:763:1:Warning: the function `file-name-concat' is not known to be
    defined.
```
Regarding the above, you may be implicitly depending on a later version of Emacs than 27.1.  As for `bookmark...function`,  I think just a bare `(defvar bookmakr...function)` at the top of your file will pacify the compiler without requiring an import.

`osm.el` with [melpazoid](https://github.com/riscy/melpazoid):
- osm.el#L541: `concat` may be unneeded; `insert` can take multiple arguments

**Comment by minad** [comment]
Thanks! I fixed the issues.

**Comment by minad** [comment]
Could this be merged soon please? osm.el got some publicity recently on https://news.ycombinator.com/item?id=30682841. I'd like to distribute via ELPA such that I don't have to tag new releases all the time to get changes out to the users via GNU ELPA. This is particularly helpful in the early phase of the project while things are still moving fast and breaking from time to time.

**Comment by riscy** [comment]
Yep, that sounds fine, and congratulations on the publicity!  I took a quick look and everything looks good to go.

Worth sharing since I was running scans, but these aren't blockers:
- osm.el#L550: It's safer to sharp-quote function names; use `#'`
- osm-mode: https://github.com/emacsmirror/osm-mode.git (via emacsmirror)

**Pull request merged**
