### PR TITLE
Add gitlab-snip-helm package

### PR DESCRIPTION
**Pull request by Sasanidas**
### Brief summary of what the package does

This package provide a simple way to create snippets an upload it to gitlab.com

### Direct link to the package repository

https://gitlab.com/sasanidas/gitlab-snip

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
I modified your recipe (the GitLab fetcher requires a `:repo` instead of a `:url` property).

### gitlab-snip.el ###

byte-compile-file (using Emacs 26.3):
```
gitlab-snip.el:101:100:Warning: assignment to free variable
    `gitlab--request-result'
gitlab-snip.el:99:141:Warning: reference to free variable
    `gitlab--request-result'
gitlab-snip.el:103:26:Warning: assignment to free variable
    `helm-source-user-snippets'
In end of data:
gitlab-snip.el:110:1:Warning: the following functions are not known to be
    defined: json-encode, json-read
```
Looks like you need a couple forward-declarations with defvar, a `(require 'json)`, and the variable `helm-source-user-snippets` should probably also be forward-declared and prefixed with your package name (although I haven't taken a close look into `gitlab-snip-helm-snippets` yet).

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
```
1 issue found:
67:0: error: "gitlab--snippet-actions" doesn't start with package's prefix "gitlab-snip".
```

Last I'll mention is the name of the package and the summary line could be improved.  This relies on `helm` (so we should probably mention that somewhere since many users prefer ido or ivy or whichever).  Maybe call the package `gitlab-snip-helm` and leave room for a `gitlab-snip-ivy`?  Or prefer `completing-read` over helm, if possible, and support everyone's completers?  The summary line `Gitlab snippets api conexion` feels unspecific to me.  I like what you wrote at the top of this PR: `Upload snippets to gitlab.com using helm`.

**Comment by Sasanidas** [comment]
> I modified your recipe (the GitLab fetcher requires a `:repo` instead of a `:url` property).
> ### gitlab-snip.el
> 
> byte-compile-file (using Emacs 26.3):
> 
> ```
> gitlab-snip.el:101:100:Warning: assignment to free variable
>     `gitlab--request-result'
> gitlab-snip.el:99:141:Warning: reference to free variable
>     `gitlab--request-result'
> gitlab-snip.el:103:26:Warning: assignment to free variable
>     `helm-source-user-snippets'
> In end of data:
> gitlab-snip.el:110:1:Warning: the following functions are not known to be
>     defined: json-encode, json-read
> ```
> 
> Looks like you need a couple forward-declarations with defvar, a `(require 'json)`, and the variable `helm-source-user-snippets` should probably also be forward-declared and prefixed with your package name (although I haven't taken a close look into `gitlab-snip-helm-snippets` yet).
> 
> checkdoc (using version 0.6.1):
> 
>     * No issues!
> 
> 
> package-lint-current-buffer (using version 20200408.203):
> 
> ```
> 1 issue found:
> 67:0: error: "gitlab--snippet-actions" doesn't start with package's prefix "gitlab-snip".
> ```
> 
> Last I'll mention is the name of the package and the summary line could be improved. This relies on `helm` (so we should probably mention that somewhere since many users prefer ido or ivy or whichever). Maybe call the package `gitlab-snip-helm` and leave room for a `gitlab-snip-ivy`? Or prefer `completing-read` over helm, if possible, and support everyone's completers? The summary line `Gitlab snippets api conexion` feels unspecific to me. I like what you wrote at the top of this PR: `Upload snippets to gitlab.com using helm`.

Hello, thank you for you review.
I change the name of the package as suggested, it makes more sense, thanks for that.
Sorry about the checkdoc, compile and lint errors, I was adding new functionalities and didn't check it correctly.

About the backend, for now I'm only planing to implementing in helm, because is the thing I use, but there is an easy function to use for extract the functionality to other potential completion frameworks like ivy.

For now, it compiles good and the linter is correct, i'm open to suggestion.

Thank you.

**Comment by riscy** [comment]
You'll also need to rename the filename of your recipe to `gitlab-helm-snip`.  Otherwise all the checks look happy.

**Comment by Sasanidas** [comment]
> You'll also need to rename the filename of your recipe to `gitlab-helm-snip`. Otherwise all the checks look happy.

Ok, the repository url and file changed. :+1:

**Comment by riscy** [comment]
Taking another look now -- `gitlab-snip-helm-user-token` might benefit from being made customizable for users who want to use that interface:
```elisp
(defcustom gitlab-snip-helm-user-token ""
  "GitLab API token."
  :type 'string)
```
similarly with `gitlab-snip-helm-visibility`, and `gitlab-snip-helm-server`.  I like to do this even for users who don't use the customize interface, because it shouts "you can change this" at them in the online help.

I'd recommend running indent region, e.g. <kbd>M-: (indent-region (point-min) (point-max))</kbd> or equivalent.

The function `gitlab-snip-helm--actions` feels like it needs to be turned into two functions.  That way you won't need to pass a string to determine which branch to go down.  You could create two functions, `gitlab-snip-helm--action-insert` and `gitlab-snip-helm--action-get-snippets` or something (although I'm sure you can think of better names than those).

Some docstrings could be cleaned up as follows:
```elisp
(defun gitlab-snip-helm-save ()
  "Create a snippet from the region.
Send it to the GitLab server at `gitlab-snip-helm-server'."
..
```

```elisp
(defun gitlab-snip-helm-insert ()
  "Insert the selected snippet in the current buffer."
...
```
Hopefully this is helpful!

**Comment by Sasanidas** [comment]
> Taking another look now -- `gitlab-snip-helm-user-token` might benefit from being made customizable for users who want to use that interface:
> 
> ```emacs-lisp
> (defcustom gitlab-snip-helm-user-token ""
>   "GitLab API token."
>   :type 'string)
> ```
> 
> similarly with `gitlab-snip-helm-visibility`, and `gitlab-snip-helm-server`. I like to do this even for users who don't use the customize interface, because it shouts "you can change this" at them in the online help.
> 
> I'd recommend running indent region, e.g. M-: (indent-region (point-min) (point-max)) or equivalent.
> 
> The function `gitlab-snip-helm--actions` feels like it needs to be turned into two functions. That way you won't need to pass a string to determine which branch to go down. You could create two functions, `gitlab-snip-helm--action-insert` and `gitlab-snip-helm--action-get-snippets` or something (although I'm sure you can think of better names than those).
> 
> Some docstrings could be cleaned up as follows:
> 
> ```emacs-lisp
> (defun gitlab-snip-helm-save ()
>   "Create a snippet from the region.
> Send it to the GitLab server at `gitlab-snip-helm-server'."
> ..
> ```
> 
> ```emacs-lisp
> (defun gitlab-snip-helm-insert ()
>   "Insert the selected snippet in the current buffer."
> ...
> ```
> 
> Hopefully this is helpful!


Hello!
As suggested, these are the changes recently made:

1 - Change all the defvar with defcustom, and a group was created.

2 - The function `gitlab-snip-helm--actions` was changed for 2 function.

3 - Some of the function and variables commentaries were changed.

It compiles cleanly, open for more suggestions.

Thank you!

**Comment by riscy** [comment]
Great -- I had a last dig around for related packages, and wanted to bring one up.

Have you had a chance to look at https://github.com/nlamirault/emacs-gitlab by @nlamirault?  It is quite popular and -- although it hasn't seen a lot of recent development -- it almost looks like a good home for the feature you're providing here, if you'd be willing to integrate it into that package's workflows.

Take a look and see what you think (it's possible that what you're proposing may already be implemented, although I wasn't able to see snippet support based on a cursory glance).  If you're open to the option, we can wait with this PR to see if @nlamirault responds either way.

**Comment by Sasanidas** [comment]
> Great -- I had a last dig around for related packages, and wanted to bring one up.
> 
> Have you had a chance to look at https://github.com/nlamirault/emacs-gitlab by @nlamirault? It is quite popular and -- although it hasn't seen a lot of recent development -- it almost looks like a good home for the feature you're providing here, if you'd be willing to integrate it into that package's workflows.
> 
> Take a look and see what you think (it's possible that what you're proposing may already be implemented, although I wasn't able to see snippet support based on a cursory glance). If you're open to the option, we can wait with this PR to see if @nlamirault responds either way.

Mmm, it seems a very interesting package, but I think it's way more big than the small functionality I want to provide, that  package is more of a gitlab API with tons of features, this is more of a small package for a fast copy/paste code and the function of upload it to a gitlab instance.
For these reasons for me at least, the aiming is different, nonetheless I would be pleased to hear what @nlamirault could say, and if it is the case, to integrate this functionality in his package.
Thank you!

**Comment by riscy** [comment]
Ping me when the week is up if we haven't heard back -- and thanks for accommodating.

**Comment by riscy** [comment]
Ok, I think it's safe to say that package is pretty dormant.

I would recommend you keep an eye on it just in case it does become active (or perhaps it will need a maintainer some day), but this is good to merge now.

**Pull request merged**
