### PR TITLE
Add `generators` recipe

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
### Brief summary of what the package does

Functions to generate data structures.

### Direct link to the package repository

https://github.com/emilyseville7cfg-better-emacs/generators/blob/main/generators.el

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Review by progfolio — CHANGES_REQUESTED** [review]
You need to add the recipe under the recipes directory.
You have added it to the main directory of the MELPA respository.

**Comment by riscy** [comment]
Thanks again for this - I see this PR, but I try to limit myself to one PR per author on each pass.  It's fine to keep this PR open, but you can help me out by [limiting the number of recipe pull requests you have open at once](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#waiting-for-reviews-and-taking-feedback-into-account).

**Comment by EmilySeville7cfg** [comment]
@riscy, can you review this PR?

**Comment by riscy** [comment]
I'll be on it and your other PRs soon - to keep myself from burning out, I limit myself to one PR per author per week.  As soon as https://github.com/melpa/melpa/pull/8323 is wrapped up, I'll move onto your next PR.

If you have a preferred order for me to review your PRs, you can help me out by limiting yourself to one at a time.

**Comment by riscy** [comment]
I see you closed #8323 -- thanks for the heads up!  I'm taking a look at this new package now.

At the outset, I feel like this package may need more time to mature and expand before it's indexed in MELPA.  Correct me if I'm wrong about anything while I explain:

First, I'm having trouble imagining where someone would benefit from using the function `generators-list`, rather than just writing e.g. `(cl-loop for i upfrom 0 upto (1- length) collect (funcall selector i))` themselves.  The latter is familiar to anyone familiar with `cl-loop` and does not require a third-party dependency.

The function `generators-sequence` is interesting and - like you wrote - accommodates very long sequences without realizing them explicitly in memory.  But I took a look at the `generator` package (which I'm not too familiar with, so bear with me) and feel like making generators using `iter-defun` (and `iter-lambda`) is more flexible and already built into Emacs -- for example here's a `generators-sequence` using `iter-yield`:
```elisp
(setq counter (funcall (iter-lambda () (dotimes (i 10) (iter-yield (1+ i))))))
```

In the meantime, quick linting pass -

`generators.el` with byte-compile using Emacs 28.1:
```
generators.el:27:13: Warning: reference to free variable `generators-sequence'
generators.el:27:42: Warning: reference to free variable `&optional'
generators.el:27:52: Warning: reference to free variable `length'
generators.el:32:41: Warning: reference to free variable `selector'
generators.el:36:18: Warning: assignment to free variable `length'
In generators-list:
generators.el:58:12: Warning: reference to free variable `for'
generators.el:58:16: Warning: reference to free variable `i'
generators.el:58:18: Warning: reference to free variable `upfrom'
generators.el:58:27: Warning: reference to free variable `upto'
generators.el:59:12: Warning: reference to free variable `collect'
In end of data:
generators.el:58:4: Warning: the function `cl-loop' is not known to be
    defined.
generators.el:42:6: Warning: the function `iter-yield' is not known to be
    defined.
generators.el:27:33: Warning: the function `selector' is not known to be
    defined.
generators.el:27:2: Warning: the function `iter-defun' is not known to be
    defined.
```
These all look to arise because the file needs these dependencies declared:
```elisp
(require 'generator)
(require 'cl-lib)
```
and that seems to clear all of the above.

A few other tips:

- The `;; URL` block of your front-matter should typically appear above the copyright and not inside the `;;; Comentary`, i.e. next to your `Package-Requires` and `Version` and so on
- Your `Commentary` should usually be self-encapsulating and not point users to external sources (e.g. "For details view README file." which might be problematic because MELPA does not distribute the READMEs)

**Comment by EmilySeville7cfg** [comment]
> First, I'm having trouble imagining where someone would benefit from using the function generators-list, rather than just writing e.g. (cl-loop for i upfrom 0 upto (1- length) collect (funcall selector i)) themselves. The latter is familiar to anyone familiar with cl-loop and does not require a third-party dependency.

There is no good completion for cl-loop (`(CLAUSE...)` is not the best one as it's required to read docs to understand what CLAUSE can be), this is a problem. I wanna completion to suggest me what parameters to put and where. From that perspective having my function is better as it's small and user exactly know what parameters are expected. :)

**Comment by riscy** [comment]
> I wanna completion to suggest me what parameters to put and where.

I see now, and this is actually a compelling argument for packages like these, e.g. dash.  [dash](https://melpa.org/#/dash) is in fact one package you want to take a good look at as an example of a (very) mature/expanded set of library functions encapsulating various ways to handle lists.

You should also take a good look at these packages:
- https://melpa.org/#/iterator
- https://melpa.org/#/for
- and especially https://melpa.org/#/iter2

which on a brief glance seem to be providing some or all of what is implemented here.  And -- for context -- we generally discourage overlapping functionality between packages, and try to get maintainers to work together if a particular feature/implementation has drawbacks in one package.

**Comment by riscy** [comment]
By the way, I ran your updated code through the linters and everything looks cleared up now.

**Comment by EmilySeville7cfg** [comment]
Dash looks awesome, I'll give it a try. :) Thanks!

**Pull request closed without merging**
