### PR TITLE
sudoku recipe import

### PR DESCRIPTION
**Pull request by zevlg**
### Brief summary of what the package does

Play sudoku in GNU Emacs.   Includes such features as:

* Custom puzzle editor
* Save/Load puzzles
* Puzzles downloader from websudoku.com and menneske.no
* Puzzles solver

and much more

### Direct link to the package repository

https://github.com/zevlg/sudoku.el

### Your association with the package

I'm the author and maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by tarsius** [comment]
There's already another `sudoku.el`: https://sourceforge.net/projects/sudoku-elisp/. Have you looked at that?

**Comment by zevlg** [comment]
Yeah, I've seen that implementation. Even more, I was inspired by it to write this one

Jr2075's implementation was missing crucial features, and there wes several stuckpoints in code to extend it, so I decided to totally rewrite it

**Comment by purcell** [comment]
Cool, but what should we do to avoid confusion? Even if you believe your sudoku.el is better, we would generally consider that name to have been claimed by the previous version. Perhaps a variation on the name?

**Comment by zevlg** [comment]
@jkr what do you think about naming?  Should we keep plain `sudoku.el` name, but interfering with your initial name, or choose another one?

**Comment by zevlg** [comment]
Will wait couple days for @jkr response, then rename to `sudoku+' on silence

**Comment by jkr** [comment]
Haven't really thought about it in a decade -- consider it abandoned and do what you think best. If that's renaming, do so with my blessing.

**Comment by zevlg** [comment]
Thanks, great!  Let's then keep plain `sudoku.el` for convenience

**Comment by purcell** [comment]
Super, thanks.

**Pull request merged**
