### PR TITLE
Add Casual Dired

### PR DESCRIPTION
**Pull request by kickingvegas**
### Brief summary of what the package does

An opinionated Transient-based porcelain for Emacs Dired.

### Direct link to the package repository

https://github.com/kickingvegas/casual-dired

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this - excellent.  I only have a couple very minor comments that aren't blockers by any means:

In e.g. `casual-dired-about-dired` you have back/front quotes around the URLs, e.g. ``` URL `https://github.com/kickingvegas/casual-dired/discussions' ```but those are typically for creating hyperlinks in the Emacs "online" help.  The norm for URLs in Emacs is to surround with `<angle brackets>` which operates well with e.g. `find-file-at-point`.  

I also have `casual-dired-sort-by.el#L231: It's safer to sharp-quote function names; use #'` which on its own is the most minor of things, but I'll mention it as an fyi.

**Comment by riscy** [comment]
Also you're aware of the namespace overlap with [casual](https://melpa.org/#/casual) since casual is your own package.  But I'll note it here for completeness.

**Comment by kickingvegas** [comment]
@riscy Thanks for the comments! I will make a patch update to reflect them.

**Comment by kickingvegas** [comment]
@riscy Trying to reconcile your guidance of putting angle brackets with what is documented the GNU manual, where they provide this example.

    The GNU project website has more information (see URL
    `https://www.gnu.org/').

<https://www.gnu.org/software/emacs/manual/html_node/elisp/Documentation-Tips.html>

Using the example above lets me use mouse 1 to click on the URL as a link and open the browser.

**Comment by riscy** [comment]
I stand corrected, and thank you very much for that!

**Pull request merged**
