### PR TITLE
Add swift3-mode recipe

### PR DESCRIPTION
**Pull request by taku0**
### Brief summary of what the package does

Major-mode for Apple's Swift programming language.

This is a fork of chrisbarrett/swift-mode with a new indentation engine, supporting Swift 3.

### Direct link to the package repository

https://github.com/taku0/swift3-mode

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

None

### Did you read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)?

Yes.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

The metadata is not correct here: you have a `-pkg.el` file, which means that any metadata in `swift3-mode.el` will be ignored. You've got a `Package-Requires` header in there which specifies a dependency on Emacs 24.4, and that dependency will therefore be masked. I suggest you delete the `-pkg.el` file (MELPA will generate one) and just put all the metadata directly in the `swift3-mode.el` file.

In the meantime, all the identifiers are in the form `swift-mode*`, but they should be `swift3-mode*`, otherwise it will be impossible to have both this package and `swift-mode` installed simultaneously without them clashing.

In any case, perhaps it would make more sense to submit your indentation engine changes to the upstream `swift-mode`? Is there a reason why that would not be possible?

**Comment by taku0** [comment]
Removed `-pkg.el` and renamed symbol prefixes.

> Is there a reason why that would not be possible?

I made several PR to the chrisbarrett/swift-mode but they rejected the PRs due to increased complexity.

https://github.com/chrisbarrett/swift-mode/pull/74
https://github.com/chrisbarrett/swift-mode/pull/126

chrisbarrett/swift-mode doesn't seem to be active now. Both the code and the Issues/PRs are left for a long time with critical bugs (https://github.com/chrisbarrett/swift-mode/issues/125#issuecomment-244169790).

**Comment by purcell** [comment]
Thanks. I'll merge this now, but you also need to rename the `defgroup` from `swift` to `swift3`, plus the references to that name from `defcustom` forms, e.g. [this one](https://github.com/taku0/swift3-mode/blob/604ffeb94028e9207aaa91de7ebd28d711f6dc79/swift3-mode-indent.el#L38).

Another small tip is that [this line](https://github.com/taku0/swift3-mode/blob/604ffeb94028e9207aaa91de7ebd28d711f6dc79/swift3-mode.el#L138) is redundant, because `define-derived-mode` generates it for you. :-)

**Comment by purcell** [comment]
I'm sorry to hear that the changes couldn't be integrated into `swift-mode`. Given that there are a bunch of open issues there, if I were @chrisbarrett I'd be inclined to simply make you a maintainer so that you can help fix things centrally without needing to fork. That'd be much better for everyone, I would think. What do all you high-volume `swift-mode` contributors think? (cc @ap4y, @bbatsov, @uk-ar)

**Comment by bbatsov** [comment]
I'm fine with the idea. I definitely think it's a mistake to start another major mode.

**Comment by chrisbarrett** [comment]
I've opened chrisbarrett/swift-mode/issues/133 for transferring swift-mode an organisation.

**Comment by purcell** [comment]
Super, thanks Chris! @taku0's work looks really good, so I hope you can all sort something out. Ping me later if - as I hope - this `swift3-mode` package can be deleted! :-)

**Comment by taku0** [comment]
Thanks all.
Migration will take a little time. swift3-mode lacks some features and automated tests swift-mode has.

**Pull request merged**
