### PR TITLE
Add recipe for oauth2-auto

### PR DESCRIPTION
**Pull request by MartinNowak**
-------

### Brief summary of what the package does

Authenticate yourself to an OAuth2 provider from inside Emacs.

### Direct link to the package repository

[telotortium/emacs-oauth2-auto: Automatically stored and configured OAuth2 for Emacs](https://github.com/telotortium/emacs-oauth2-auto)

### Your association with the package

Recipe author/package user

### Relevant communications with the upstream package maintainer

- [Add to Melpa · Issue #3 · telotortium/emacs-oauth2-auto](https://github.com/telotortium/emacs-oauth2-auto/issues/3)
- [fix byte-compile warning by MartinNowak · Pull Request #18 · telotortium/emacs-oauth2-auto](https://github.com/telotortium/emacs-oauth2-auto/pull/18)

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly (telotortium/emacs-oauth2-auto#18 fixes docstring warning)
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

- oauth2-auto.el#L479: It's safer to sharp-quote function names; use `#'`
- oauth2-auto.el#L3: Have you done the paperwork to assign this copyright?
- oauth2-auto.el#L11: This may be a copy-paste error?

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by MartinNowak** [comment]
Thanks @riscy.

> * oauth2-auto.el#L479: It's safer to sharp-quote function names; use `#'`

:+1: https://github.com/telotortium/emacs-oauth2-auto/pull/20
> * oauth2-auto.el#L3: Have you done the paperwork to assign this copyright?

https://github.com/telotortium/emacs-oauth2-auto/pull/19
> * oauth2-auto.el#L11: This may be a copy-paste error?

Yes, same thx. https://github.com/telotortium/emacs-oauth2-auto/pull/19
I'll try to hunt the original authors to get those changes merged.

**Comment by boogsbunny** [comment]
What's the status here?

**Comment by riscy** [comment]
Apologies for having let this one slip off my radar since September.

Regarding my sharp-quote nag above, I see a PR here that's unmerged https://github.com/telotortium/emacs-oauth2-auto/pull/20 and I left a comment there just now.

Byte-compiling with the latest Emacs release currently gives a minor warning.  This is super minor, something that has probably come up since this PR was opened, (and also something I need to fix in some of my packages!), but since it's being passed on to users' screens as a warning, I think it's good to get these fixed before we merge into MELPA:

`oauth2-auto.el` with byte-compile using Emacs 29.1:
```
oauth2-auto.el:212:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
```

**Comment by boogsbunny** [comment]
bump @MartinNowak

**Comment by boogsbunny** [comment]
I saw your comment regarding the sharp-quote. That should be fine since it isn't merged anyway and still is just a regular quote, right?

Is [this open PR ](https://github.com/telotortium/emacs-oauth2-auto/pull/18)the only blocker now?

**Comment by riscy** [comment]
Yes, it's unfortunate that that's an actual byte-compile warning - but once that PR is merged, we'll have a clean byte-compile and I say this is ready to go.

**Comment by boogsbunny** [comment]
That makes sense. By the way, the PR has been merged now, so this should be good to go!

**Comment by riscy** [comment]
Thank you!

**Comment by riscy** [comment]
And, welcome to MELPA. :)

**Pull request merged**
