### PR TITLE
Add recipe for igist

### PR DESCRIPTION
**Pull request by KarimAziev**
### Brief summary of what the package does

This package provides a transient interface for editing, creating, updating and deleting GitHub gists and comments.

There is an existing [gist](https://melpa.org/#/gist) package, but it is not working with recent Emacs versions. Collaboration is hardly possible because it hasn't been touched in five years and has stale open issues and pull requests.

### Direct link to the package repository

<https://github.com/KarimAziev/igist>

### Your association with the package

Author/Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
> existing [gist](https://melpa.org/#/gist) [...] is not working with recent Emacs versions. Collaboration is hardly possible because it hasn't been touched in five years and has stale open issues and pull requests.

This is significant and maybe we want to consider an alternate route in this case.  Check this Wiki page out: https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks ; it's a much better outcome for Emacers if a broken package like gist gets fixed, rather than them having to figure out whether "igist" or "gist" will work for them.

Does one of those issues describe what is broken when trying to use this package in a modern Emacs?  I'll also ping @defunkt for good measure.

(Note your work on this package (igist) lends you credit as a future maintainer of gist, if we determine that the old gist should get a new maintainer.)

**Comment by KarimAziev** [comment]
@riscy I did some research, and here what's I have found:

  - `gist` is broken because of the library that provides the core API mapping - [gh.el](https://github.com/sigma/gh.el). All dependent libraries have  [similar](https://github.com/dgtized/github-clone.el/issues/30) open issues.

  - Detect the exact problem with `gh.el` is problematic - it looks like the issue  with either native compilation or with `eieio` changelog since  Emacs 25 (e.g., `eieio-compat` was moved to obsolete in Emacs 29 master).

I agree that one package is better, and I could fix and maintain the gist by removing `gh.el` or merging with `igist`. But fixing `gh.el` looks like not worth it because:

  - it looks like also not to be maintained
  - `eieoe` have extensive changelog since Emacs 25
  - `igist` has features that are not implemented in `gh.el`

**Comment by riscy** [comment]
Thank you very much for doing that investigation.  I'm noting that gh.el appears to be broken.  How do you feel about maintaining gist by removing the broken gh.el dependency and merging in your additional igist features?

I will also ping @sigma for thoughts here, as the apparent current maintainer of gist.

**Comment by KarimAziev** [comment]
@riscy Yes, I am working on it. But I'm afraid that the merge request may go unanswered. Did you get a response from  @defunct or @sigma?

**Comment by sigma** [comment]
hey. Thanks for the ping :)

I'd happily merge igist into gist if that helps (and hand over maintainership if you're interested!)
As you noted the various packages in that chain are seldom maintained: I essentially fix them for myself whenever I move to a new Emacs version (and I'm happy with 28 right now :))
As for eieio, it has been an unmitigated disaster for years, so cutting it sounds great to me !

**Comment by KarimAziev** [comment]
@sigma  Thank you for the response!
Yes, I am a heavy user of the gists service, and I have some ideas about new features (e.g., explore public gists), so I have enough motivation to maintain it. But the first merge request (it takes some time) will just migrate from eioioe-based API, I guess.

**Comment by riscy** [comment]
I think it's fine to keep this PR open to continue discussion, but my understanding is it sounds like @KarimAziev can take over maintenance of the existing gist package.  I think this is a good outcome -- thanks all. :)

**Comment by KarimAziev** [comment]
@sigma Please take a look at this [pull request](https://github.com/sigma/gh.el/pull/112).

**Comment by KarimAziev** [comment]
@sigma @riscy   Merge request for gist is also [ready](https://github.com/defunkt/gist.el/pull/124).

**Comment by riscy** [comment]
Shall we close this PR for now, then?

**Comment by KarimAziev** [comment]
> Shall we close this PR for now, then?

I would but maybe is it better to close it after merging MR to gists? Because it is still open.

**Comment by riscy** [comment]
In the meantime I'll just mark this awaiting-upstream, but ping me when it's time to look here again.

**Comment by KarimAziev** [comment]
Hi @sigma and @riscy,

I hope you're doing well. I am writing to request the merge of my package `igist` into the MELPA repository.

`igist` is a feature-rich package that provides a transient interface for editing, creating, updating, and deleting GitHub gists and comments. It offers advanced features such as more advanced render engines, exploring public gists, adding/editing comments, and utilizing auth sources for authentication.

I have followed all the necessary procedures and guidelines for MELPA package submission, including passing package-lint checks and successful byte-compilation. Additionally, I would like to bring to your attention that I was also responsible for fixing the `gist` package by enabling lexical binding in the `gh.el` library.

While the fixed version of `gist` now incorporates lexical binding, `igist` provides additional enhancements and features that are not present in the fixed version. These enhancements offer improved functionality, advanced rendering, and an enhanced user experience for managing GitHub gists.

Given these points, I kindly request that you review and consider merging `igist` into the MELPA repository, taking into account its adherence to MELPA guidelines, positive user feedback, and the need for an actively maintained package with advanced features in this domain.

Thank you for your attention and consideration. I look forward to your response and the possibility of contributing `igist` to the MELPA community.

**Comment by riscy** [comment]
Just to refresh my context, weren't we aiming at you taking over gist and incorporating your feature enhancements ("improved functionality, advanced rendering, and an enhanced user experience for managing GitHub gists"):

> I'd happily merge igist into gist if that helps (and hand over maintainership if you're interested!)

Have you changed your mind about going in this direction?

**Comment by KarimAziev** [comment]
> Just to refresh my context, weren't we aiming at you taking over gist and incorporating your feature enhancements ("improved functionality, advanced rendering, and an enhanced user experience for managing GitHub gists"):
> 
> > I'd happily merge igist into gist if that helps (and hand over maintainership if you're interested!)
> 
> Have you changed your mind about going in this direction?

I want to mention that I did make a minor pull request to `gist` previously, but it was ignored by the author. Adapting the existing `igist` package to incorporate its enhancements into `gist` would indeed be a significant task, and there is a possibility that it might be ignored as well. However, I still believe that merging `igist` into `gist` and taking over maintainership would be a good approach to address the issues with the current `gist` package and provide users with an improved solution. Nevertheless, it seems like I have done what I could in that regard.

Additionally, I want to emphasize a few more points regarding my request to merge `igist` directly into MELPA. Firstly, the previous pull request I made to `gist` was overlooked, indicating potential difficulties in incorporating the enhancements from `igist` into `gist`. Given this, merging `igist` directly into MELPA would be a more practical approach to address the issues and ensure the enhancements are made available to users without delays or possible neglect.

Secondly, it is important to consider that popular Emacs configuration starters, such as Spacemacs, have already removed the unmaintained `gist` package, while Doom Emacs has marked it as stale and deprecated. These actions underscore the need for an actively maintained and feature-rich package for managing GitHub gists. Given this context, I believe it is crucial for MELPA to consider whether to continue with the unmaintained `gist` package or integrate `igist` to provide users with a reliable and enhanced solution.

Thank you for your consideration and attention to this matter.

**Comment by riscy** [comment]
> However, I still believe that merging igist into gist and taking over maintainership would be a good approach to address the issues with the current gist package and provide users with an improved solution

Okay - @sigma did mention above a willingness to hand over maintainership, but people get busy.  Here's what I think: the fact that the existing gist is not working with recent Emacs versions suggests that we may ultimately just want to deindex the existing gist package and replace it with yours.  (I think having a "gist" and an "igist" is confusing for users; how will they know which one they should use?  The answer should be the one that works, and we should try to prioritize the users here.)

In the interest of moving this along, let's merge your igist under the current name.  If it turns out in the future it makes sense for you to take over the canonical "gist" package name (effectively accepting @sigma's offer above), we can do that, and I think that will put users in a better place.

**Pull request merged**
