### PR TITLE
Recipe for mu4easy

### PR DESCRIPTION
**Pull request by danielfleischer**
### Brief summary of what the package does

Opinionated collection of packages and a customizable configuration for using mu4e with multiple email accounts with ease. 

### Direct link to the package repository

https://github.com/danielfleischer/mu4easy

### Your association with the package

Creator and maintainer of the package. 

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, I like the idea for this.  Altogether I think this behavior should be gated behind a minor mode that a user deliberately activates, because this makes significant changes to the Emacs runtime state as well as potentially reaching out to MELPA/QUELPA at load time, which could lead to hard-to-debug configs.

With a global minor mode, all of the hooks and advice and variable changes (using setq) could take effect when a user toggles the mode on (and with appropriate bookkeeping, they could be removed when the user toggles the mode off).

In the meantime, here's the output of a couple quick checks on this:

`mu4easy.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- mu4easy.el#L8: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
```

`#'load`-check on each file:
```
Loading mu4easy.el
  mu4easy.el:Error: Emacs 28.1:
  (void-variable mu4e-view-actions)
```

Stderr output while compiling/loading:
```
Contacting host: melpa.org:80
Error (use-package): Failed to install quelpa-use-package: melpa.org/80 Temporary failure in name resolution
Error (use-package): Cannot load quelpa-use-package
Error (use-package): Cannot load mu4e-icalendar
Error (use-package): Failed to parse package mu4e-goodies-tags: use-package: Unrecognized keyword: :quelpa
Error (use-package): Failed to install mu4e-column-faces: melpa.org/80 Temporary failure in name resolution
Error (use-package): Cannot load mu4e-column-faces
Error (use-package): Failed to parse package mu4e-alert: use-package: Unrecognized keyword: :quelpa
Error (use-package): Failed to parse package helm-mu: use-package: Unrecognized keyword: :quelpa
Error (use-package): Failed to install org-msg: melpa.org/80 Temporary failure in name resolution
Error (use-package): Cannot load org-msg
```

**Comment by danielfleischer** [comment]
Thanks for the review. I'll rework it into a global minor mode. 

Need to make sure mu+mu4e are installed which is a external package and an Emacs library. 

Also, what's the current convention of installing Emacs dependencies from github? I see from the errors quelpa wasn't installed so all the dependencies weren't installed.

**Comment by danielfleischer** [comment]
Hi, I refactored the library into a global minor mode; carefully restoring the variables upon disabling the mode, removing hooks and advices. Removed `use-package` and `quelpa` completely, only depending on other melpa packages. Passing `checkdoc` and `package-lint`.

However I have an issue with melpazoid: my entire package assumes the user is using the maildir-utils (mu) [1.8+ package](https://github.com/djcb/mu/tree/master), together with its mu4e elisp library. So modifications to the  melpazoid dockerfile are needed. However [mu 1.8](https://packages.ubuntu.com/kinetic/maildir-utils) is not available for Ubuntu 20.04. Alternatively, one can git clone and build mu; it needs [meson >= 0.60](https://packages.ubuntu.com/jammy/meson) which is also not available for Ubuntu 20.04. Bumping the base image to 22.10 is not compatible with [kelleyk emacs28](https://launchpad.net/~kelleyk/+archive/ubuntu/emacs). I'm not an Ubuntu user so I'm not sure how to get the melpazoid test working.

**Comment by riscy** [comment]
> I have an issue with melpazoid: my entire package assumes the user is using the maildir-utils (mu) [1.8+ package](https://github.com/djcb/mu/tree/master), together with its mu4e elisp library. So modifications to the melpazoid dockerfile are needed. However [mu 1.8](https://packages.ubuntu.com/kinetic/maildir-utils) is not available for Ubuntu 20.04. Alternatively, one can git clone and build mu; it needs [meson >= 0.60](https://packages.ubuntu.com/jammy/meson) which is also not available for Ubuntu 20.04. Bumping the base image to 22.10 is not compatible with [kelleyk emacs28](https://launchpad.net/~kelleyk/+archive/ubuntu/emacs). I'm not an Ubuntu user so I'm not sure how to get the melpazoid test working.

I see - I think there are also a handful of other situations where melpazoid won't cut it (without significant changes to the Dockerfile); for example, from memory, vterm *also* requires more than simply installing an elisp package.  mu4e has been on my radar but I (obviously) haven't done anything about it yet.

"Passing" melpazoid itself isn't a strict requirement though, and despite the name, melpazoid is really just my own personal set of scripts, and it's (mostly) just running the other checkers.  Sometimes I have to do things manually, like here.  That said, everything looks good -- and I appreciate the work you did turning this into a minor mode.

A couple other small things (non-blocking)
- Your author line `;; Author: Daniel Fleischer;;  <danflscr@gmail.com>` has extra semicolons before your email
- You may want to introduce customizable variables to handle different systems, e.g. your minor mode runs: `(setq mu4e-mu-binary "/usr/local/bin/mu")` but what if `mu` lives somewhere else?  Users have no way of changing the "/usr/local/bin/mu" literal; in fact, it would probably be safer to use `executable-find` (and hope users have their PATH setup properly) than to use this literal
- `being adviced`  -> `advised` is what we typically say in elisp
- `agrument when advicing` -> `aRGument when adviSing`

**Pull request merged**
