### PR TITLE
add recipe for lsp-python-ms

### PR DESCRIPTION
**Pull request by andrew-christianson**
### Brief summary of what the package does

This package implements an lsp-mode client for Microsoft's python
languager server.

### Direct link to the package repository

https://github.com/andrew-christianson/lsp-python-ms

### Your association with the package

I am a maintainer of the package.  Code initially authored by @cpbotha

### Relevant communications with the upstream package maintainer

**none-needed**
### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by andrew-christianson** [comment]
Thanks for the comments, I'll make the suggested changes.

**Comment by MatthewZMD** [comment]
Any updates?

**Comment by muffinmad** [comment]
There are https://github.com/xhcoding/ms-python already on melpa which provides same feature. Maybe it would be better to improve `ms-python` package if it missing some features of this package?

**Comment by purcell** [comment]
> There are https://github.com/xhcoding/ms-python already on melpa which provides same feature. Maybe it would be better to improve `ms-python` package if it missing some features of this package?

Yes, agree. How about it, @xhcoding and @andrew-christianson? What would be the best way to get a single great package which works for (at least) both of you?

**Comment by cpbotha** [comment]
Thank you very much @muffinmad and @purcell for the time you invest in this too.

This was discussed with @xhcoding and @andrew-christianson in this issue: https://github.com/andrew-christianson/lsp-python-ms/issues/9

In short, both works started in parallel, unbeknownst to each other, based on my blog post. @xhcoding was quick on the melpa trigger :) but @andrew-christianson 's version ended up getting substantially more development effort.

We all, including @xhcoding , thought it would be best to fold his work into @andrew-christianson 's version, which is the only one working with the new Emacs LSP support.

What would be the best way to do this?

**Comment by purcell** [comment]
> What would be the best way to get this version to be the canonical one on Melpa?

Firstly I'd merge this (done!). Then I'd be happy to merge a further PR removing @xhcoding's package.

I'd also note that this new package would benefit from a little bit of polishing: in particular, turn the option vars into `defcustom`s where possible, with a containing `defgroup`. :-)

**Pull request merged**
