### PR TITLE
Adds recipe for white-theme

### PR DESCRIPTION
**Pull request by anler**
Just another theme ^^

https://github.com/anler/white-theme.el

### CODE REVIEW

**Comment by syohex** [comment]
There are no `*.el` file. Did you push `.el` file ?

**Comment by anler** [comment]
@syohex totally forgot about it, sorry! is pushed now

**Comment by purcell** [comment]
Thanks. The identifiers named `basic-colors-*` should all be called `white-theme-*` instead, to avoid name clashes. Looks good otherwise.

**Comment by anler** [comment]
@purcell done!

**Comment by purcell** [comment]
Thanks!

**Comment by anler** [comment]
\0/ thank you guys!

**Pull request merged**
