### PR TITLE
typo in realgud-old-debuggers

### PR DESCRIPTION
**Pull request by rocky**
tepanx -> trepanx

### CODE REVIEW

**Comment by purcell** [comment]
Applied manually in 260b4d5a85c380dda0f7bb0370e3ffa8cc3c0275. Thanks.

**Comment by purcell** [comment]
(For the record, the way to submit this would have been to create a fresh branch off our `master`, fix the typo there, and then just send a pull request for that branch.)

**Comment by rocky** [comment]
Yeah, I realize that now. I'm sorry for all of the undue hassle.

**Comment by purcell** [comment]
Not a problem. :-)

**Pull request closed without merging**
