### PR TITLE
Add helm-perspeen recipe

### PR DESCRIPTION
**Pull request by jimo1001**
### Brief summary of what the package does

Simple helm interface for perspeen.

### Direct link to the package repository

https://github.com/jimo1001/helm-perspeen

### Your association with the package

maintainer.

### Relevant communications with the upstream package maintainer

**None needed**.

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Is this line necessary ? 
- https://github.com/jimo1001/helm-perspeen/blob/2c25eb5132bc452a78a6373947d98e8706236ee4/helm-perspeen.el#L107

You declare `helm-projectile` as package dependency, so this `require` never fails. This s-expression is evaluated at `package-initialize` and `helm-projectile` and its dependencies are loaded at that time. This makes emacs initialization slow and is bad for package lazy loading.

**Comment by jimo1001** [comment]
Surely, this line is unnecessary.
The integration with `helm-projectile` is an optional feature, so I removed from `Package-Requires`.
https://github.com/jimo1001/helm-perspeen/commit/90826312f85658d4bfb71b83e4d5c3ed0187da5a

**Comment by syohex** [comment]
`with-eval-after-load` was introduced at Emacs 24.4. Please declare minimum Emacs version in `Package-Requires` header. Or use `eval-after-load`(+ `quote`) instead of it.

**Comment by jimo1001** [comment]
replaced the using function from `with-eval-after-load` to `eval-after-load`.
https://github.com/jimo1001/helm-perspeen/commit/1d10a83b44cfe71eb3fe372cec10c640fe8b3deb

**Comment by syohex** [comment]
Merged

**Pull request merged**
