### PR TITLE
Add recipe for units-mode

### PR DESCRIPTION
**Pull request by Atreyagaurav**
### Brief summary of what the package does

This mode uses [gnu units](https://www.gnu.org/software/units/units.html) to facilitate unit related conversions/calculations inside emacs.

### Direct link to the package repository

https://github.com/Atreyagaurav/units-mode

### Your association with the package

The Author and the Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by Atreyagaurav** [comment]
I've run melpazoid run in my repo, which has passed. 

Link: https://github.com/Atreyagaurav/units-mode/runs/8170865777?check_suite_focus=true

And I'm aware of unit conversion offered by `calc`, we can use calc in embedded mode, but I felt the need to have an easier way to use unit conversions, and while talking to the maintainer of the `gnu units` I learned there aren't any other emacs interface they've heard about hence I made this.

My plan is to use this package to not only interactively convert units in emacs but also provide functions for unit conversion for other modules, for example my [litex-mode](https://github.com/Atreyagaurav/litex-mode) currently only deals with numerical values, so I've been thinking about adding units support https://github.com/Atreyagaurav/litex-mode/issues/23 and have tried many different approach and this one is by far the easiest.

**Comment by riscy** [comment]
Thanks -- and I'm glad to hear melpazoid might've been useful in preparing this. :)

Your rationale above is helpful too.  Happy to hit merge on this.

**Comment by progfolio** [comment]
Surprised this got through so quickly.
Compiling in a clean environment raises the following warning:

* units-mode.el:25:75 Warning: the function ‘string-join’ is not known to be defined. 121336.742405

This can be solved by adding:

```emacs-lisp
(eval-when-compile (require 'subr-x))
```

* The units-mode minor mode definition is empty. 
* Since you are using `shell-command-to-string` with a user option, I would advise  quoting those args via `shell-quote-argument`. Better yet would be to follow the advice in the `shell-command` docstring:

```emacs-lisp
In Elisp, you will often be better served by calling `call-process' or
`start-process' directly, since they offer more control and do not
impose the use of a shell (with its need to quote arguments)."
```

Cool idea for a general library though.
I can see it being useful in other packages.

**Comment by Atreyagaurav** [comment]
@progfolio  Hi, can you tell me what "The units-mode minor mode definition is empty." means? 
I think I can fix the others, but not this one. I used `define-minor-mode` macro and it should have done everything.

**Comment by progfolio** [comment]
> @progfolio Hi, can you tell me what "The units-mode minor mode definition is empty." means? I think I can fix the others, but not this one. I used `define-minor-mode` macro and it should have done everything.

It's not a technical error, it's just not doing anything. Providing some commands/functions does not require that a minor mode be defined.

**Comment by Atreyagaurav** [comment]
oh, so I can just do `(provide 'units-mode`) and it'll be fine? I wanted it to be minor mode so I can use the hooks.

**Comment by riscy** [comment]
@progfolio has definitely caught some issues I missed -- I sort of had my foot on the gas.

Incidentally I think not detecting the missing subr-x is a bug with melpazoid (melpazoid's byte-compile runtime knows about subr-x because subr-x is a transitive dependency of package.el).

**Comment by Atreyagaurav** [comment]
https://github.com/Atreyagaurav/units-mode/commit/8611f09fa1d0ca898eef262ad45d8585a64344b3

I've fixed the subr-x and the shell-quote on this commit. I'd run into `subr-x` problem before in my CI tests and I solved it by adding `-l subr-x` instead of doing require, sorry about that.

And I think I'll still use `shell-command-to-string`, as `call-process` seems to write to buffer and would probably have to do something to get the string.

**Comment by progfolio** [comment]
> oh, so I can just do `(provide 'units-mode`) and it'll be fine?
Yes.

> I wanted it to be minor mode so I can use the hooks.

I'm not sure how this would be beneficial based off of what your package has in it so far.
Can you give an example of how you would use those hooks?

**Comment by progfolio** [comment]
> call-process seems to write to buffer and would probably have to do something to get the string.

```emacs-lisp
(with-temp-buffer
  ;; The DESTINATION arg is `t', meaning insert output in this buffer.
  (call-process "ls" nil t nil "--fart")
  (buffer-string))
```

I'll leave it as an exercise to the reader on how non-zero exits from the process should be handled.

**Pull request merged**
