### PR TITLE
Add recipe for earthfile-mode 

### PR DESCRIPTION
**Pull request by wingyplus**
### Brief summary of what the package does

A major mode for editing Earthly file.

### Direct link to the package repository

https://github.com/earthly/earthly-emacs.

### Your association with the package

I'm maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Code looks great, and thanks for your close adherence to the checklist.

I only notice there is no mention of the license in the source file itself.  I'd suggest adding an [SPDX-License-Identifier](https://spdx.dev/ids/) to earthly-mode.el -- in this case you could add `;; SPDX-License-Identifier: MPL-2.0`

I also suggest renaming this package to `earthfile-mode` for higher specificity and to help discoverability (you could still mention "Earthly" in your summary line, which would make it pop up in "earthly" searches).  On my first look, Earthly seems to be the tool itself, and Earthfiles seem to be what this mode is actually for editing.

**Comment by wingyplus** [comment]
> I only notice there is no mention of the license in the source file itself. I'd suggest adding an [SPDX-License-Identifier](https://spdx.dev/ids/) to earthly-mode.el -- in this case you could add `;; SPDX-License-Identifier: MPL-2.0`

I've a PR open in https://github.com/earthly/earthly-mode/pull/7. Please comment if it's incorrect. :)

> I also suggest renaming this package to `earthfile-mode` for higher specificity and to help discoverability (you could still mention "Earthly" in your summary line, which would make it pop up in "earthly" searches). On my first look, Earthly seems to be the tool itself, and Earthfiles seem to be what this mode is actually for editing.

I named `earthly-mode` for 2 reasons:

* To align with another editor plugin. For example https://github.com/earthly/earthly.vim. 
* Earthly team has a plan to add more tools which are currently under gathering an idea and discussion.

**Comment by riscy** [comment]
License identifier looks great, thanks for accommodating.

I don't think calling it `earthly-mode` is a blocker, but if you plan to add more tools unrelated to the file-editing major mode, it might make sense to make them a separate package.

Here's my rationale, but let me know what you think: separate packages would help users keep their dependencies leaner if they wanted one and not the other(s).  It's also sort of what you see in with [docker](https://melpa.org/#/?q=docker), where there are packages like dockerfile-mode (which depends on `s`), and the very useful docker-tramp (which has _no_ dependencies), and so forth.  It also means you would have more "namespaces" to play with.

**Comment by wingyplus** [comment]
> License identifier looks great, thanks for accommodating.
> 
> I don't think calling it `earthly-mode` is a blocker, but if you plan to add more tools unrelated to the file-editing major mode, it might make sense to make them a separate package.
> 
> Here's my rationale, but let me know what you think: separate packages would help users keep their dependencies leaner if they wanted one and not the other(s). It's also sort of what you see in with [docker](https://melpa.org/#/?q=docker), where there are packages like dockerfile-mode (which depends on `s`), and the very useful docker-tramp (which has _no_ dependencies), and so forth. It also means you would have more "namespaces" to play with.

Thank you for helping to review the package. I think it's a good idea to separate the package between tools and major-mode. But I want to keep all official packages in the same repo, is it possible to do? If yes, I might create a sub-directory to separate between earthfile-mode and the tool packages that will be coming in the future.

**Comment by riscy** [comment]
> I want to keep all official packages in the same repo, is it possible to do?

Yep, you can definitely do that with custom recipes.  [Here](https://github.com/melpa/melpa/pull/7700/files)'s an example of a recently merged PR that does something like that.

**Comment by wingyplus** [comment]
@riscy I have change the major mode that you suggest in https://github.com/earthly/earthly-mode/pull/8. Hopefully, you can help review. After merged, I'll change the package in this PR to `earthfile-mode` instead.

**Comment by wingyplus** [comment]
Hi @riscy, I edit the PR base on your suggestion. The package was renamed to `earthfile-mode` and include only `earthfile-mode.el` in the recipe. The repository got rename to be more generic and I update the PR description to the correct repository URL. Please kindly review again. 🙇

**Comment by riscy** [comment]
Thank you!  This looks good to go.  And welcome to MELPA. :)

**Pull request merged**
