### PR TITLE
Add markdown-soma 

### PR DESCRIPTION
**Pull request by jasonm23**
### Brief summary of what the package does

Provides live markdown preview as a minor mode (+ using the browser)

### Direct link to the package repository

https://github.com/jasonm23/markdown-soma

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed all of these by doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`markdown-soma.el` with checkdoc 0.6.2:
```
markdown-soma.el:59: All variables and subroutines might as well have a documentation string
markdown-soma.el:65: All variables and subroutines might as well have a documentation string
markdown-soma.el:71: All variables and subroutines might as well have a documentation string
markdown-soma.el:78: All variables and subroutines might as well have a documentation string
markdown-soma.el:121: All variables and subroutines might as well have a documentation string
```

Package and license:
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by jasonm23** [comment]
thank you I'll get it updated

**Comment by riscy** [comment]
Thanks, just let me know here when you do and I'll take another look.

**Comment by jasonm23** [comment]
Will do.  Thank you.

**Comment by jasonm23** [comment]
Ok it should all be ready now.

**Comment by riscy** [comment]
Thanks!  Another quick pass with the compiler --

`markdown-soma.el` with byte-compile using Emacs 28.1:
```
markdown-soma.el:240:10: Warning: reference to free variable
    `markdown-soma-highlightjs-theme-list'
```
I think this is easily fixed with a couple of style changes -- one is to declare your variables near the top of the file rather than at the bottom, before any functions.  But for this particular variable I notice you've got a `defvar` line followed by `setq` line at the top level.  These should be combined into a single defvar with a docstring, e.g. `(defvar markdown-soma-highlightjs-theme-list '(...) "Docstring.")`

In fact there are a couple top-level `setq`s that should be replaced by `defvars`:
- markdown-soma.el#L96: Top-level `setq` should be replaced by `defvar`
- markdown-soma.el#L244: Top-level `setq` should be replaced by `defvar`

I also notice you state dependencies on `s` and `f` but as far as I'm able to tell you don't make use of either of these in the code.

**Comment by riscy** [comment]
Apologies, I just realized you are using dash's `--map`, but you should know that it is just a `mapcar` wrapper, so you could potentially drop that dependency entirely.

**Comment by jasonm23** [comment]
Awesome, thanks!

I was a bit confused why I was still getting that free variable warning.  I
was using defvar only without the setq.  I split them out to silence the
free variable warning.  Which on my end worked sigh.

I'll make the change and hoist to the top.

As far as s and dash dependency you're mistaken.

Not the only uses but for example:

https://github.com/jasonm23/markdown-soma/blob/master/markdown-soma.el#L119

https://github.com/jasonm23/markdown-soma/blob/master/markdown-soma.el#L221

Thanks Chris

**Comment by jasonm23** [comment]
Pushed the fix for defvars

**Comment by riscy** [comment]
Thanks for accommodating - I think the form used for `defvar markdown-soma-highlightjs-theme-list` is currently malformed.  The docstring should be the last argument.

On this pass I also noticed -- perhaps in rare cases -- in `markdown-soma--shell-command`, filenames with special characters or quotation marks could cause issues (e.g. a file called `$css.css` fed into `" --custom-css \"%s\"`); you're better off removing the quotation marks and using `shell-quote-argument` instead (e.g. `" --custom-css %s" (shell-quote-argument ...)`)

Minor:
- Markdown soma execuatble  -> executable (I'd also suggest word-wrapping this text closer to 80 chars)
- Also, `markdown-soma--needs-executable-message` looks like it should be a `defconst` (at the top of the file) rather than a function; and also instead of raising this as a `message` it may make sense to pop up a *help* buffer (see the function `help-buffer`, `help-insert-string` I believe)
- "See the list of themes other than "vs" at the end of this file." -> not at the end of the file anymore, but it may be better to just write ```"see the variable `xyz'" ```
- In `markdown-soma-restart`, I feel like if `markdown-soma-mode` isn't active, some kind of message should be given to the user to that effect
- `(error "Warning markdown-soma-custom-css is %s is not a css file" css-file)` looks like it should be a `user-error` instead of an `error` (and the message has one extra "is")
- `markdown-soma--render-buffer-hooks` mentions `markdown-soma-render-buffer` but I don't see the latter defined

**Comment by jasonm23** [comment]
Thanks for the feedback. I'll make some changes

**Comment by jasonm23** [comment]
https://github.com/jasonm23/markdown-soma/blob/master/markdown-soma.el#L406

Please search for names you think are missing.

**Comment by jasonm23** [comment]
Implemented most of the recommendations.  I'm in full agreement on using Help instead of message for the wall of text re: missing `soma` executable.

I need to lookup how that works though, because `(help-insert-string "string")` just inserted directly into my current buffer, when I evaluated the form.

**Comment by jasonm23** [comment]
```
    (progn
      (switch-to-buffer-other-window (help-buffer))
      (help-insert-string markdown-soma--needs-executable-message))
```
Seems to do the trick.

**Comment by jasonm23** [comment]
Ok, all changes in.  Any further suggestions?

**Comment by jasonm23** [comment]
BTW Got the result I needed by joining the highlight-theme-list to a single line.

**Comment by riscy** [comment]
Thanks!

> Please search for names you think are missing.

That was my fault, `hi-lock-face-symbol-at-point` (which I'm often using to help me read code) was catching the `.` at the end of this docstring: `"hooks which trigger markdown-soma-render-buffer.")`.  A bit unrelated, but I'd suggest rewriting that docstring as: ```"hooks which trigger `markdown-soma-render-buffer'.")``` to create a help hyperlink to the right place.

A couple small checkdoc nags popped up in the latest --

`markdown-soma.el` with checkdoc 0.6.2:
```
markdown-soma.el:119: First line should be capitalized
markdown-soma.el:178: Messages should start with a capital letter
markdown-soma.el:178: Error messages should *not* end with a period
```

But I think these shouldn't be blockers either (but worth fixing; I think these are valid and for the time being something we look for all MELPA-indexed packages to try to adhere to).

Thanks again -- merging. :)

**Comment by jasonm23** [comment]
```sh
markdown-soma.el:119: First line should be capitalized
markdown-soma.el:178: Messages should start with a capital letter
markdown-soma.el:178: Error messages should *not* end with a period
```

Thank you, I'll get those organized.

**Comment by jasonm23** [comment]
0bc5fcaeca919f0ce639eb7e6565a70de5189712

**Pull request merged**
