### PR TITLE
Add recipe for outline-yaml

### PR DESCRIPTION
**Pull request by jamescherti**
### Brief summary of what the package does

The `outline-yaml.el` Emacs package provides a minor mode for Emacs that enables **code folding and outlining for YAML files**. It leverages the built-in `outline-minor-mode` to provide a structured view of YAML files, allowing users to fold and unfold YAML files.

This package helps when editing long and complex YAML files, which makes code folding becomes an invaluable tool because it is allowing the collapse and expansion of sections of the file and enhancing readability and navigation.

### Direct link to the package repository

https://github.com/jamescherti/outline-yaml.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I noticed you've got other PR(s) already open #9103.  To split my review time evenly between authors, I try to do one PR at a time per author, but I promise I'll get to this when we resolve earlier PRs.

**Comment by jamescherti** [comment]
Thank you for letting me know. I appreciate your approach to managing reviews and understand the need to prioritize. I'll look forward to your feedback once the earlier PRs are resolved.

**Comment by mattiasb** [comment]
The link in the original post directs you to the `outline-indent.el` package instead of `outline-yaml.el` which confused me at first. :)

**Comment by mattiasb** [comment]
Also: It might be worth mentioning how this relates to the `outline-indent` package you posted at the same time. From the description it *sounds* like the `outline-indent` would cover all that `outline-yaml` does. I assume that's incorrect though? :)

**Comment by jamescherti** [comment]
Hello @mattiasb,

The `outline-indent` package focuses on general indentation for outlines, while `outline-yaml` is specifically designed for the YAML format. `outline-indent` can be used to outline YAML files, but `outline-yaml` is better for YAML files.

**Comment by mattiasb** [comment]
Gotcha! I assume YAML block scalars is an example of something that does (or could) work better in `outline-yaml.el` for example?

**Comment by jamescherti** [comment]
That's right, @mattiasb . Block scalar is a good example that works better in `outline-yaml` than `outline-indent`. The first comments after "---" are also hidden by `outline-yaml`. I am also planning to add additional functions to ease editing long and complicated YAML files.

**Comment by jamescherti** [comment]
I am closing this pull request for now.

(Please focus on adding `outline-indent.el` https://github.com/melpa/melpa/pull/9105 , which offers generic support for various indent-based text files such as YAML and Python.)

**Pull request closed without merging**
