### PR TITLE
Add recipe for icomplete-vertical

### PR DESCRIPTION
**Pull request by oantolin**
### Brief summary of what the package does

This package defines a global minor mode to display icomplete candidates vertically.

### Direct link to the package repository

https://github.com/oantolin/icomplete-vertical

### Your association with the package

I am the creator and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, this looks good to me -- the only thing I'd add is we generally ask for a LICENSE file that GitHub can detect (e.g. no markup) if possible (see: https://github.com/licensee/licensee )

And as a small suggestion, you might be able to shorten your summary line down from `Global minor mode to display icomplete candidates vertically` to `Display icomplete candidates vertically` (since I think a properly implemented package would use a global minor mode for this behavior anyway).

Also I'm curious, what's `(declare (indent 1))`?  The Emacs help for `defun-declarations-alist` doesn't provide a description.

**Comment by oantolin** [comment]
Thanks for taking a look at the package and for your suggestions! I've added the text of the GPL 3 as a file called LICENSE and I shortened the package description at the top of `icomplete-vertical.el` as you suggested.

What `(declare (indent n))` (where `n` is some positive integer) does is tell Emacs that the first `n` arguments of the macro are special and must be indented further than the remaining ones. It is used for macros that end in an implicit `progn`, to specifiy where the implicit `progn` starts.

This is documented in `(info "(Elisp) Indenting Macros")`.

**Comment by riscy** [comment]
Ah right it's a macro.  Thank you for enlightening me.

Also, this looks good to go.  Thanks, and welcome to MELPA! :)

**Comment by oantolin** [comment]
Amazing, thanks!

**Pull request merged**
