### PR TITLE
Add recipe for dimmer

### PR DESCRIPTION
**Pull request by gonewest818**
### Brief summary of what the package does

This module provides a subtle visual indication which window is
currently active by dimming the faces on the others.  It does this
nondestructively, and computes the dimmed faces dynamically such
that your overall color scheme is shown in a muted form without
requiring you to define the "dim" versions of every face.

The percentage of dimming is user configurable.  In addition, for
users of "light" themes there is a dimmer-invert flag that adjusts
the faces brighter (toward white, rather than toward black).

Unlike other modules with similar goals, this implementation
does *not* change the color of the background in any way. It only
adjusts foregrounds.

### Direct link to the package repository

https://github.com/gonewest818/dimmer.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by manuel-uberti** [comment]
This looks great!

**Comment by gonewest818** [comment]
Thank you! Hope you give it a try!

**Comment by manuel-uberti** [comment]
I did, actually. It only seems to dim other windows when point is in the minibuffer. Can anyone else confirm?

**Comment by gonewest818** [comment]
Can you open an issue for that? ==> https://github.com/gonewest818/dimmer.el

**Comment by manuel-uberti** [comment]
Done > https://github.com/gonewest818/dimmer.el/issues/3

**Comment by gonewest818** [comment]
Thank you.

**Comment by purcell** [comment]
Thanks! Quick feedback:
- Don't [shim built-in functions](https://github.com/gonewest818/dimmer.el/blob/master/dimmer.el#L82-L108) using their original names. The [elisp conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html) mention this. Aren't those functions available in Emacs 25+ anyway? If not, consider bumping the dependency instead of shimming.
- You should add a `defgroup` to define the `dimmer` group and place it in the global custom group hierarchy.
- `dimmer-invert` should be unnecessary: you can infer it by looking at the `default` face and seeing whether the background is brighter than the foreground.

**Comment by gonewest818** [comment]
Roger that. Thanks for the feedback.

**Comment by gonewest818** [comment]
Ok, done. All feedback has been addressed.

**Comment by purcell** [comment]
Awesome, thanks.

BTW, while I'm not personally a `dash`, fan, it provides an `-if-let`/`-if-let*`. The whole history of the built-in counterparts is a bit silly.

**Pull request merged**
