### PR TITLE
Add ellama

### PR DESCRIPTION
**Pull request by s-kostyaev**
### Brief summary of what the package does

Ellama is an [ollama](https://github.com/jmorganca/ollama) client for
Emacs. It provides a set of commands for interacting with the Ollama
API, allowing users to ask questions, define words, translate text,
and more. Ellama natively supports streaming output. With this package you can interact with local ai assistant, that works on your device.

### Direct link to the package repository

https://github.com/s-kostyaev/ellama

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

* No byte-compile errors 🎉 

`ellama.el` with checkdoc (0.6.2)

```
No issues found.
```

`ellama.el` with package-lint (20230905.629)

```
No issues found.
```

Package and license:

- GPLv3

**Comment by riscy** [comment]
Hi @s-kostyaev --

It looks like you have `Package-Requires: ((emacs "27.1"))` but at least in Emacs 28, the signature for `libxml-parse-html-region` is:
```elisp
(libxml-parse-html-region START END &optional BASE-URL)
```
whereas in Emacs 29, the signature is
```elisp
(libxml-parse-html-region &optional START END BASE-URL)
```
so I think unless you depend on Emacs 29, you should supply point-min and point-max as arguments.

Also the default recipe
```elisp
(ellama :repo "s-kostyaev/ellama" :fetcher github)
```
is equivalent to what you have here, and preferred -- it lets your repo grow without adjusting the recipe on MELPA's side.

**Comment by s-kostyaev** [comment]
Hi.
Thanks for review. Fixed @riscy

**Comment by riscy** [comment]
Looks good.  This isn't necessarily a blocker, but it might be useful to expand your summary and/or commentary to mention more about this.  E.g. mention LLM, which is a great discoverability keyword in this case.  In your Commentary, mention the entrypoints, maybe unpack what Ollama is, etc.

I also notice you have:
```elisp
(make-local-variable 'ellama-context)
(make-local-variable 'ellama--unprocessed-data)
(make-local-variable 'ellama--request)
(make-local-variable 'ellama--extract)
(make-local-variable 'ellama--prefix-regexp)
(make-local-variable 'ellama--suffix-regexp)
(make-local-variable 'ellama--extraction-state)
(make-local-variable 'ellama-line)
```
but you can skip all this if you use `defvar-local`, e.g. `(defvar-local ellama--line nil)`.

**Comment by s-kostyaev** [comment]
@riscy thank you for helpful feedback!

**Pull request merged**
