### PR TITLE
Add receipe for prometheus-mode

### PR DESCRIPTION
**Pull request by peterhoeg**
### Brief summary of what the package does

Major modes for working with Prometheus.

### Direct link to the package repository

https://gitlab.com/peterhoeg/prometheus-mode

### Your association with the package

Author/maintainer.

### Relevant communications with the upstream package maintainer

NA

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`prometheus-data-mode.el` with package-lint 20230315.1052:
```
1 issue found:
12:0: error: Package-Requires outside the main file have no effect.
```

`prometheus-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- The `;;; Commentary` for this file is much wider than 80 characters
```

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to prometheus-data-mode.el
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to prometheus-mode.el

You should be aware that GPL version 2 is incompatible with MELPA; see https://github.com/johannes-mueller/company-wordfreq.el/issues/6 for example.

**Comment by peterhoeg** [comment]
Thanks for the review Chris.

I must have used an older version of package-lint, because I’m not getting any errors from it. I was also not aware of melpazoid, so I’ll address those too.

**Comment by peterhoeg** [comment]
> 12:0: error: Package-Requires outside the main file have no effect.

So this may be slightly off-topic, and if you need me to take this conversation elsewhere, that’s no problem of course - but is there a way to get `package-lint' to not look at a file in isolation, but instead check the entire “project”?

Basically, package-lint doesn’t complain in `prometheus-data-mode.el', because it doesn’t know that it isn’t the main file. And without `Package-Requires', it will start complaining bitterly about `setq-local'.

All the issues have been addressed.

**Comment by peterhoeg** [comment]
And I just found `package-lint-main-file'. I apologize for the noise.

**Comment by riscy** [comment]
Not a problem - and thank you for the PR on melpazoid. :)

This looks good to go, although I will note that your front-matter is a little unusual in terms of formatting.  Something like this:
```elisp
...
;; Created: May 09, 2023
;; Modified: May 09, 2023
;; Keywords: languages
;; Homepage: https://hoeg.com
;;
;; This file is not part of GNU Emacs.

;;; License:

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:
;;
;;  Major mode for viewing data/metrics from prometheus exporters.
;;
;;  Currently, the following features are supported:
;;  1. Syntax highlighting
;;  2. imenu
;;
;;; Code:

...
```
would usually be written like this:
```elisp
...
;; Created: May 09, 2023
;; Modified: May 09, 2023
;; Keywords: languages
;; Homepage: https://hoeg.com
;; SPDX-License-Identifier: GPL-3.0-or-later

;; This file is not part of GNU Emacs.

;;; Commentary:

;;  Major mode for viewing data/metrics from prometheus exporters.

;;  Currently, the following features are supported:
;;  1. Syntax highlighting
;;  2. imenu

;;; Code:

...
```

**Comment by riscy** [comment]
And while I'm noticing it, your `Homepage:` metadata should probably point to a homepage for the package itself - users visiting the [index for a package](https://melpa.org/#/package-lint) would expect clicking the "Homepage" link to take them to something specifically relevant to the package.

**Pull request merged**
