### PR TITLE
Add lisp-local recipe

### PR DESCRIPTION
**Pull request by lassik**
### Brief summary of what the package does

Allows different Lisp indentation in each buffer via a `lisp-indent-function` wrapper that temporarily replaces global indentation-related symbol properties with local values.

### Direct link to the package repository

https://github.com/lispunion/emacs-lisp-local

### Your association with the package

Wrote it

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by lassik** [comment]
The package could also be `lisp-local`. In that case, the user-settable variable would be `lisp-local-indent` instead of the slightly confusing `lisp-buffer-local-indent`.

**Comment by lassik** [comment]
The package name could also be `lisp-local`. In that case, the user-settable variable would be `lisp-local-indent` instead of the slightly confusing `lisp-buffer-local-indent`.

**Comment by purcell** [comment]
> The package name could also be `lisp-local`. In that case, the user-settable variable would be `lisp-local-indent` instead of the slightly confusing `lisp-buffer-local-indent`.

Yeah, that would probably be good, or perhaps `lisp-local-indent`.

**Comment by lassik** [comment]
I thought `local` would be good instead of `local-indent`, since other buffer-local Lisp behavior can perhaps be added to the package later. Then people don't have to install new hooks for another package if they want the new behavior.

My goal is to keep this package minimalist so it only provides some variables for the settings, and is unopinionated about where those settings come from. Other packages could supply them.

**Comment by lassik** [comment]
OK, changed package name from `lisp-buffer-local` to `lisp-local`. Checked that it works using `make recipes/lisp-local` followed by `make sandbox INSTALL=lisp-local`.

I took the opportunity to move the package from my personal GitHub account to [lispunion/emacs-lisp-local](https://github.com/lispunion/emacs-lisp-local) while at it. I have an ongoing project to collect a bunch of cross-Lisp-compatibility stuff under that organization.

**Comment by riscy** [comment]
Nice.

**Pull request merged**
