### PR TITLE
Add recipe for pr-review

### PR DESCRIPTION
**Pull request by blahgeek**
### Brief summary of what the package does

This package allows users to review github pull requests in emacs.

### Direct link to the package repository

https://github.com/blahgeek/emacs-pr-review

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by wandersoncferreira** [comment]
:O we worked on the same problem independently ? https://github.com/melpa/melpa/pull/7775

**Comment by blahgeek** [comment]
> :O we worked on the same problem independently ? #7775

Ah... and it seems that we started the projects at roughly the same time, with many similar designs. What a nice surprise :D

**Comment by riscy** [comment]
That's an interesting turn of events. :)  I don't think this is a blocker in either case if the authors want to pursue independent directions.  Here's a quick run over the checklist (I notice you've left checkdoc un-checked, but it's easier for maintainers/more fair for everyone if you solve everything you can, at least until MELPA revises the checklist.)

### pr-review-action.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
pr-review-action.el:37: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-action.el:107: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-action.el:180: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-action.el:295: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-action.el:299: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-action.el:372: Argument `reviewer-logins' should appear (as REVIEWER-LOGINS) in the doc string
Warning (emacs): 
pr-review-action.el:69: `y-or-n-p' argument should end with "? "
```

package-lint (using version 20211107.1614):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- pr-review-action.el#L52: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L53: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L85: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L86: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L148: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L168: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L198: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L214: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L228: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L242: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L255: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L268: It's safer to sharp-quote function names; use `#'`
- pr-review-action.el#L289: It's safer to sharp-quote function names; use `#'`

### pr-review-api.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
pr-review-api.el:51: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:64: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:75: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:100: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:109: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:123: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:142: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:147: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:152: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:157: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:162: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:167: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:172: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:178: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:187: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:193: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-api.el:224: All variables and subroutines might as well have a documentation string
```

package-lint (using version 20211107.1614):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- pr-review-api.el#L41: `load-file-name` is nil if using `eval-buffer`; consider `(or load-file-name buffer-file-name)`

### pr-review-common.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20211107.1614):
- No issues!


### pr-review-input.el ###

byte-compile (using Emacs 27.1):
```
pr-review-input.el:123:1:Warning: the function `replace-string-in-region' is
    not known to be defined.
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
pr-review-input.el:90: First line is not a complete sentence
Warning (emacs): 
pr-review-input.el:90: Argument `allow-empty' should appear (as ALLOW-EMPTY) in the doc string
```

package-lint (using version 20211107.1614):
- No issues!


### pr-review-render.el ###

byte-compile (using Emacs 27.1):
```
pr-review-render.el:63:4:Warning: mapconcat called with 2 arguments, but
    requires 3
In end of data:
pr-review-render.el:618:1:Warning: the following functions are not known to be
    defined: string-replace, length>
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
pr-review-render.el:47: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:59: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:63: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:70: Argument `dom' should appear (as DOM) in the doc string
Warning (emacs): 
pr-review-render.el:98: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:127: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:168: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:172: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:211: Lisp symbol `magit-section' should appear in quotes
Warning (emacs): 
pr-review-render.el:222: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:226: First line is not a complete sentence
Warning (emacs): 
pr-review-render.el:242: First line is not a complete sentence
Warning (emacs): 
pr-review-render.el:242: Argument `pending-review-thread' should appear (as PENDING-REVIEW-THREAD) in the doc string
Warning (emacs): 
pr-review-render.el:301: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:366: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:396: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:409: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:432: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:458: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:500: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:510: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:524: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review-render.el:605: All variables and subroutines might as well have a documentation string
```

package-lint (using version 20211107.1614):
```
2 issues found:
208:10: warning: Closing parens should not be wrapped onto new lines.
428:8: warning: Closing parens should not be wrapped onto new lines.
```

Other [lints](https://github.com/riscy/melpazoid):
- pr-review-render.el#L177: It's safer to sharp-quote function names; use `#'`
- pr-review-render.el#L391: It's safer to sharp-quote function names; use `#'`
- pr-review-render.el#L588: It's safer to sharp-quote function names; use `#'`
- pr-review-render.el#L589: It's safer to sharp-quote function names; use `#'`
- pr-review-render.el#L453: It's safer to sharp-quote function names; use `#'`
- pr-review-render.el#L465: `concat` may be unneeded; `insert` can take multiple arguments
- pr-review-render.el#L475: `concat` may be unneeded; `insert` can take multiple arguments
- pr-review-render.el#L486: `concat` may be unneeded; `insert` can take multiple arguments

### pr-review.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
pr-review.el:26: Name emacs should appear capitalized as Emacs
Warning (emacs): 
pr-review.el:37: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review.el:82: All interactive functions should have documentation
Warning (emacs): 
pr-review.el:88: All interactive functions should have documentation
Warning (emacs): 
pr-review.el:94: All interactive functions should have documentation
Warning (emacs): 
pr-review.el:99: All interactive functions should have documentation
Warning (emacs): 
pr-review.el:104: All variables and subroutines might as well have a documentation string
Warning (emacs): 
pr-review.el:140: First line is not a complete sentence
Warning (emacs): 
pr-review.el:223: Argument `new-window' should appear (as NEW-WINDOW) in the doc string
Warning (emacs): 
pr-review.el:233: Argument `query' should appear (as QUERY) in the doc string
```

package-lint (using version 20211107.1614):
```
1 issue found:
53:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

Other [lints](https://github.com/riscy/melpazoid):
- pr-review.el#L137: It's safer to sharp-quote function names; use `#'`
- pr-review.el#L191: It's safer to sharp-quote function names; use `#'`
- pr-review.el#L228: It's safer to sharp-quote function names; use `#'`

**Comment by blahgeek** [comment]
@riscy Thank you so much for your patient review. All errors should be fixed now, PTAL.

> I notice you've left checkdoc un-checked, but it's easier for maintainers/more fair for everyone if you solve everything you can, at least until MELPA revises the checklist

OK I see. However, personally I still think it's unnecessary to document all the internal functions. Maybe it's possible to revise the checklist in the future?

> 53:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.

I'm not sure how should I fix this. I want to provide keybindings for evil users, so I use `(with-eval-after-load 'evil ...)` for this purpose. Do you have any suggestions?

Thanks!

**Comment by riscy** [comment]
> personally I still think it's unnecessary to document all the internal functions.  Maybe it's possible to revise the checklist in the future?

I tend to agree, and I'm probably being stricter than we need to be with checkdoc.  To be honest, I already (secretly) omit a few checkdocs (sentence-end-double-space, checkdoc-proper-noun-list, checkdoc-verb-check-experimental-flag) since they tend to be false positives.  One of these days I'll jot my thoughts down in an issue or something.

> I want to provide keybindings for evil users

Practically speaking I think the pattern you're using is probably okay, but the [manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Hooks-for-Loading.html) suggests:

> If you need to examine and set the variables defined in another library (those meant for outside use), you can do it immediately—there is no need to wait until the library is loaded. If you need to call functions defined by that library, you should load the library, preferably with `require` 

In the spirit of that I could suggest `(when (and (require 'evil nil t) (fboundp 'evil-define-key*)) ...)` or just telling users outright "If you want evil-mode bindings enabled, call `pr-review-evil-setup` or add `(with-eval-after-load 'evil (pr-review-evil-setup))` to your config"

While I'm here, here are a couple of the lingering linter nags below --

checkdoc (using version 0.6.2):
```
Warning (emacs): 
pr-review-action.el:76: `y-or-n-p' argument should end with "? "
Warning (emacs): 
pr-review-action.el:225: `y-or-n-p' argument should end with "? "
Warning (emacs): 
pr-review-action.el:242: `y-or-n-p' argument should end with "? "
Warning (emacs): 
pr-review-action.el:245: `y-or-n-p' argument should end with "? "
Warning (emacs): 
pr-review-action.el:249: Error messages should *not* end with a period
```

byte-compile (using Emacs 27.1):
```
pr-review-render.el:735:1:Warning: the function `length>' is not known to be
    defined.
```

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by riscy** [comment]
> But this package may be loaded before evil, so the first option cannot work reliably, right?

The form `(require 'evil nil t)` will load evil in proactively if it's available, but I suppose there are cases where someone has evil on their load-path but doesn't necessarily want it brought in.

The problem with `eval-after-load` and the reason why I think `package-lint` flags it, is that you're leaving a chunk of code in the wings that the user doesn't explicitly know about.  It might never be run (I don't know what the performance impact of hundreds of packages doing this would be--probably negligible?) or it might end up being run in unexpected circumstances (for example if someone ran `unload-feature` on pr-review before they bring in evil), causing a surprise error.  That's all a little contrived, but I think having all packages following that guideline is better for the package ecosystem altogether.

I think it's not productive for me to *insist* in this case, but I'll hold off on merging until you get a chance to weigh that feedback, since it's hard to undo on a package that's in wider use.  Should be a quick merge when I hear back.

While I'm here, here's a couple more minor lints (non-blocking, just fyi):
- pr-review-render.el#L784: It's safer to sharp-quote function names; use `#'`
- pr-review-render.el#L785: It's safer to sharp-quote function names; use `#'`
- pr-review-render.el#L543: It's safer to sharp-quote function names; use `#'`
- pr-review-render.el#L515: `concat` may be unneeded; `insert` can take multiple arguments
- pr-review-render.el#L563: `concat` may be unneeded; `insert` can take multiple arguments
- pr-review-render.el#L580: `concat` may be unneeded; `insert` can take multiple arguments
- pr-review-render.el#L590: `concat` may be unneeded; `insert` can take multiple arguments
- pr-review-render.el#L601: `concat` may be unneeded; `insert` can take multiple arguments

**Comment by blahgeek** [comment]
> The problem with `eval-after-load` and the reason why I think `package-lint` flags it, is that you're leaving a chunk of code in the wings that the user doesn't explicitly know about.  It might never be run (I don't know what the performance impact of hundreds of packages doing this would be--probably negligible?) or it might end up being run in unexpected circumstances (for example if someone ran `unload-feature` on pr-review before they bring in evil), causing a surprise error.  That's all a little contrived, but I think having all packages following that guideline is better for the package ecosystem altogether.
> 
> I think it's not productive for me to *insist* in this case, but I'll hold off on merging until you get a chance to weigh that feedback, since it's hard to undo on a package that's in wider use.  Should be a quick merge when I hear back.

I see, thanks for your reply. I've modified this part to get rid of `eval-after-load` now. Now it will be called when `pr-review-mode` is used the first time. PTAL.

> While I'm here, here's a couple more minor lints (non-blocking, just fyi):

Fixed.

**Comment by riscy** [comment]
Thanks!  I'll merge this now.

**Pull request merged**
