### PR TITLE
Added zetz-mode

### PR DESCRIPTION
**Pull request by damon-kwok**
### Brief summary of what the package does

An Emacs mode for the [ZetZ](https://github.com/zetzit/zz) programming language.

### Direct link to the package repository

https://github.com/damon-kwok/zetz-mode

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Code looks good.  A couple quick notes:

- Some people may dislike rainbow-delimiters (I'm actually a happy user), so making them a dependency, and auto-activating them, shouldn't be the responsibility of a major mode.  It should be up to the user to turn on this option on their own.  In general, you should try to avoid toggling on minor modes when you don't need to, although I admit there are some grey areas around this
- Same for hl-todo, whitespace-mode, yafolding mode (there are several folding packages -- your users may not all use yafolding!).  I also notice you require 'fill-column-indicator but don't activate it.  In general, try to make your dependency list as small as possible
- zetz-mode.el#L462: It's safer to sharp-quote function names; use `#'`
- zetz-mode.el#L518: It's safer to sharp-quote function names; use `#'`
- zetz-mode.el#L383: You can use `not` or `null` (and it's unusual to use CAPITALIZED variable names)

**Comment by damon-kwok** [comment]
@riscy Thanks for your feedback, Fixed.

**Comment by riscy** [comment]
Thanks for accommodating and trimming down the dependencies.  I've got

byte-compile (using Emacs 26.3):
```
zetz-mode.el:489:1:Warning: the following functions are not known to be
    defined: yafolding-get-element-region, yafolding-go-parent-element,
    yafolding-hide-region
```
which is due to the function `zetz-folding-hide-element` -- this function isn't bound to anything or documented, so looks like it might be easy to remove?

Lastly, I just noticed this: `(defalias 'zetz-parent-mode (if (fboundp 'prog-mode) 'prog-mode 'fundamental-mode))` -- almost surely `prog-mode` is included with Emacs 25.  Is there a reason you do this?

Hope this helps.

**Comment by damon-kwok** [comment]
@riscy Thanks, Updated.

**Comment by riscy** [comment]
Looks good!  It looks like I missed this the last time around, but as a last thing, could you add license boilerplate or an [SPDX-License-Identifier](https://spdx.org/using-spdx-license-identifier) to zetz-mode.el?

**Comment by damon-kwok** [comment]
@riscy I updated four PR's, and Added SPDX License Identifiers.

**Comment by riscy** [comment]
Great, thanks!  And welcome to MELPA.  :)

**Pull request merged**
