### PR TITLE
Add tfsmacs to MELPA.

### PR DESCRIPTION
**Pull request by sebasmonia**
### Brief summary of what the package does

tfsmacs is a package to work with Team Foundation Server from Emacs. This package deals only with the source control aspect, not PBIs, sprints, builds, or any other thing contained in TFS.

### Direct link to the package repository

https://github.com/sebasmonia/tfsmacs

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, and sorry for the slow response.

This looks great overall, but the `tfs-` prefix for the symbols should match the package and feature name, ie. `tfsmacs-`. It looks like you originally called this `tfs`, in which case the prefix would have matched.

You might also like to provide a prefix keymap that users could bind to `C-c t`, in order to easily get all the suggested global keybindings.

**Comment by sebasmonia** [comment]
Thanks for the feedback!
I'll update the names and documentation and re-submit. It will probably take a few days as I'm away from home :)

**Comment by sebasmonia** [comment]
For the key map I'm reading about define-prefix-command, will add this too.

**Comment by sebasmonia** [comment]
Added a prefix keymap and renamed (hopefully) ALL references to the old name.

Appreciate the code review, this is new territory for me :)

**Comment by DamienCassou** [comment]
Some more feedback:
- could you please squash the commits into just one?
- please add `-*- lexical-binding: t; -*-` at the end of the first line
- the file header is very unusual. You might consider using M-x auto-insert to get something standard
- you might want to use `(executable-find "tf.cmd")` as default value for tfsmacs-cmd if that works
- the `defcustom`s following a `defgroup` don't have to specify the `:group` because the group is inferred
- there is a lint warning on the first `define-key` line. I don't understand why though. @purcell?
- instead of concatenating strings for the buffer name, Emacs lisp code usually uses `format`
- `string-empty-p` will tell you if a string is empty, no need to compare it to ""
- I don't understand why you add spaces at the end of the results of -get-collection-parameter and -get-login-parameter
- similarly, I don't get why these functions return the empty string. You could just return nil (the default if you use `when`/`unless` instead of `if`) and filter out the nils at the end
- you could use derived-mode-p instead of testing the value of major-mode
- instead of extracting the first caracter of a string with substring to compare it with string-equal, you could use `string-prefix-p`
- in -write-file-to-temp-directory, the code concatenates a list of strings that have been created by exploding a big string (by `process-lines` in -process-command-sync). This seems both costly and useless.
- I don't have time to read the rest of the file

I think this PR could be merged as soon as the commits are squashed.

**Comment by sebasmonia** [comment]
After fighting a lot with git (thanks heavens for Magit!) I managed to merge the commits into a single one.

I will transfer the feedback into an issue in the tfsmacst repo, thank you!

**Comment by sebasmonia** [comment]
Thanks @DamienCassou for the amazing feedback. I made most of the changes except two which I moved to new, separate issues. More details in [the tfsmacs issue](https://github.com/sebasmonia/tfsmacs/issues/1).

**Comment by tarsius** [comment]
@DamienCassou You should use `Rebase and merge` instead of `Create a merge commit`. Also in cases like this where the commit message contains a lot information about things that went wrong on the first attempt (and which was preserved due to a `git commit --squash` without the message being sanitized), it would be better if you stripped that useless information when you "merge" into `master`.

> After fighting a lot with git (thanks heavens for Magit!) I managed to merge the commits into a single one.

I am guessing that you did `r i` and then `f` on all but the first commit. Instead of `f` you should have `s` on all commits and then removed the obsolete information when presented with the concatenations of the old commit messages.

**Comment by sebasmonia** [comment]
Hi Jonas,

I did a mix of command line and Magit commands since until very recently I was more of an hg guy.
So it sort of worked but not sure of the details.

All I can confirm is that I edited the last commit message after the squash.

Will keep the advice in mind for next time!
________________________________

**Comment by tarsius** [comment]
I don't think one can set a default, just which methods are allowed and which are not. But I believe the last used method is sticky per user and repository.

**Comment by purcell** [comment]
Yeah, I typically squash and merge commits in PRs, because it's sometimes kinder for contributors, and the setting is indeed sticky. It's never bad to teach people about rebasing and squashing, though. :-)

**Pull request merged**
