### PR TITLE
Added recipe for go-imports.

### PR DESCRIPTION
**Pull request by yasushi-saito**
https://github.com/yasushi-saito/go-imports

### Brief summary of what the package does

go-imports inserts a package import statement, given the package name.

### Direct link to the package repository
https://github.com/yasushi-saito/go-imports

### Your association with the package
Maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick feedback:
- This code is not building shell commands safely. For example, what if `root` contains a space, quotes or worse [here](https://github.com/yasushi-saito/go-imports/blob/aae96b81b429c9ca16c926a03508b01f41c754e0/go-imports.el#L127)? Both `root` and `perl-script` should be escaped with `shell-quote-argument`, not simply with `'`.
- Consider providing `;;;###autoload` comments for the main interactive functions so that the user doesn't need to `require` the library.

**Comment by yasushi-saito** [comment]
Thanks. I changed the call-process part so that it invoke perl directly, w/o find&grep and such. This should avoid the problem you mentioned. Also added autoload magic lines.

**Comment by purcell** [comment]
Great! Looks good.
- Don't use `ido-completing-read` directly: just use `completing-read`. Then the behaviour will be overridden automatically by the user's preferred completion mechanism (helm, ivy, ido etc.)
- Rather than putting the perl script in a string and then writing it to a temporary file, just add it to the repository, then you can include it in the package recipe (with `:files (:defaults "go-imports.pl")`. To find its location in the code, you can capture the results of `load-file-name` in a `defconst`.

**Comment by yasushi-saito** [comment]
Thanks for the review. I applied all your comments.

**Comment by purcell** [comment]
Thanks. Added in 4118ebf0, since this PR had become a little cluttered. :-)

**Pull request closed without merging**
