### PR TITLE
Add recipe for astro-ts-mode

### PR DESCRIPTION
**Pull request by Sorixelle**
### Brief summary of what the package does

Provides a major mode for editing [Astro](https://astro.build/) templates.

### Direct link to the package repository

https://github.com/Sorixelle/astro-ts-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I see that you're doing some localized "patching" of treesitter at the bottom of the source file.  From my perspective your rationale is good, but I hope you do follow up and report this (and your fix).  Emacs 29 is not yet released, after all.

Some quick feedback --

- The function `astro-mode--advice-for-treesit-buffer-root-node` uses the form `(if <pred> t <body>)` but I'd recommend just using `(unless <pred> <body>)` *or* rewriting the predicate as its negation, `(and (eq major-mode 'astro-mode) (not (eq lang 'astro)))`
- I'm not totally familiar with the conventions/expectations treesitter is introducing -- so please bear with me with this question -- but some major modes that have both a "traditional" and a "treesitter" version are following the convention of naming the treesitter version with a ts, e.g. [c-ts-mode](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/c-ts-mode.el) vs. regular old c-mode.  Is there a good reason to not name this `astro-ts-mode`?

Some minor checkpoints, worth fixing within reason:
`astro-mode.el` with checkdoc 0.6.2:
```
astro-mode.el:138: Symbols t and nil should not appear in single quotes
astro-mode.el:146: First line is not a complete sentence
```

**Comment by Sorixelle** [comment]
Thanks for the feedback! I definitely intend to report these issues upstream - just not very familiar with the Emacs mailing lists, so I need to look into how to actually report them :sweat_smile: 

A few clarifications:
> The function `astro-mode--advice-for-treesit-buffer-root-node` uses the form `(if <pred> t <body>)` but I'd recommend just using `(unless <pred> <body>)` or rewriting the predicate as its negation, `(and (eq major-mode 'astro-mode) (not (eq lang 'astro)))`

I don't think I can use `unless` here, since I need to return `t` if the predicate fails, and not `nil` - otherwise the advice won't continue execution of the actual function. I can negate the predicate, but all that would do is require me to swap `THEN` and `ELSE`, and I'm not sure what benefit there is to doing that.

> I'm not totally familiar with the conventions/expectations treesitter is introducing -- so please bear with me with this question -- but some major modes that have both a "traditional" and a "treesitter" version are following the convention of naming the treesitter version with a ts, e.g. [c-ts-mode](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/c-ts-mode.el) vs. regular old c-mode. Is there a good reason to not name this `astro-ts-mode`?

No reason in particular - I figured since there isn't an existing non-treesitter-based mode for this language yet, there wasn't really a need for the `ts` specifier. I don't see anything in the Info manual saying to do it one way or the other either. I'll see if I can get some clarification on the convention.

**Comment by riscy** [comment]
> I don't think I can use unless here, since I need to return t

I should have read the docstring on that function - thanks for clarifying my mistake.

>  I'll see if I can get some clarification on the convention.

I wondered if an author like you might have more insight (I'm an Emacs 28 Luddite over here, at least until the next version is released).  Let me know if you're easily able to get this clarification, but if not let's merge this.

**Comment by Sorixelle** [comment]
I'm told that adding `-ts-` to the mode name [is preferable](https://lists.gnu.org/archive/html/help-gnu-emacs/2023-06/msg00223.html), so I'm going to refactor the package to align with it.

**Comment by Sorixelle** [comment]
Package refactored. Let me know if there's any other changes to make.

**Comment by riscy** [comment]
Thank you for checking on that `-ts-` convention for me!  That's actually a huge help.

Welcome to MELPA. :)

**Pull request merged**
