### PR TITLE
Add company-org-block

### PR DESCRIPTION
**Pull request by xenodium**
### Brief summary of what the package does

A company completion backend for org blocks.

### Direct link to the package repository

https://github.com/xenodium/company-org-block

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this submission.  Here's a very quick first pass over the checklist:

### company-org-block.el ###

byte-compile (using Emacs 27.1):
```
company-org-block.el:82:4:Warning: `seq-contains' is an obsolete function (as
    of 27.1); use `seq-contains-p' instead.
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
1 issue found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
```
Prefer `Version` (MELPA adds `Package-Version`).

### Package ###

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by xenodium** [comment]
> Thanks for this submission. Here's a very quick first pass over the checklist

Thanks for taking a look Chris.

> company-org-block.el:82:4:Warning: `seq-contains' is an obsolete function (as
    of 27.1); use `seq-contains-p' instead.

Ok to keep warning since it was obsoleted in 27.1?

> Prefer Version (MELPA adds Package-Version).

Added Version.

> Add a LICENSE file that GitHub can detect (e.g. no markup) if possible

Added LICENSE.

**Comment by riscy** [comment]
> Ok to keep warning since it was obsoleted in 27.1?

Ah, definitely.  This wouldn't be a blocker but an alternative might be to use `member` instead since you don't specify a TESTFN, and then your users wouldn't see any byte-compile noise.  I realize you might want to keep consistent with the use of seq-filter above that, though.

That said, this looks like a cool package and I'm happy to merge.  Welcome to MELPA. :)

**Comment by xenodium** [comment]
> That said, this looks like a cool package and I'm happy to merge. Welcome to MELPA. :)

Thank you Chris!

**Pull request merged**
