### PR TITLE
Added recipe for with-shell-interpreter

### PR DESCRIPTION
**Pull request by p3r7**
### Brief summary of what the package does

Provides helper function `with-shell-interpreter` to ease dealing with the few vars acting as implicit parameters for shell functions.

They can be set as explicit keyword argument instead of having to let-bind vars.

Lib dependency for packages in [p3r7/prf-shell](https://github.com/p3r7/prf-shell).

There is also an [accompanying blog post](https://www.eigenbahn.com/2020/01/19/painless-emacs-shell-commands) that walks through the implementation.

### Direct link to the package repository

https://github.com/p3r7/with-shell-interpreter

### Your association with the package

Maintainer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
  **NB:** Except for macro `with-shell-interpreter` wich takes &rest args but maps them to keyword args, like use-package does.
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi!  Thanks for this.  I actually read the blog post today. :)  Here's a quick pass:

### with-shell-interpreter.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
- Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems)
- Lexical binding has been enabled
```
with-shell-interpreter.el:94:1:Warning: Unused lexical variable
`w32-quote-process-args'
with-shell-interpreter.el:94:1:Warning: Unused lexical variable
`explicit-shell-file-name'
```
These aren't blockers, and these won't show up without lexical binding enabled, but you can future-proof against them in case you decide to enable lexical binding (requiring Emacs 24) by adding the following underneath your `(require 'cl-lib)`:
```elisp
(require 'shell)  ; <-- for explicit-shell-file-name
(defvar w32-quote-process-args)
```

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs):
with-shell-interpreter.el:52: Argument `args' should appear (as ARGS) in the doc string
Warning (emacs):
with-shell-interpreter.el:153: Argument `plist' should appear (as PLIST) in the doc string
```
I think these should be easy to silence -- I would only insist on the first one (since it is a "public" function), for which you could write "For full documentation on ARGS, please see the README file that came with..." in the docstring, for example.

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191220.419):
```
94:0: error: "eval-with-shell-interpreter" doesn't start with package's prefix "with-shell-interpreter".
```
These ones are sticky, but it's safer to take a hard line with them for everyone's benefit -- would it be possible to rename this function to `with-shell-interpreter-eval`?

**Comment by p3r7** [comment]
Wow, thanks for the in-detail review.

**lexical binding**

Enabled.

As for `w32-quote-process-args`, the var is defined on Windows build of Emacs. So I conditionally defvar'ed it for the other platforms.

```el
(unless (boundp 'w32-quote-process-args)
  (defvar w32-quote-process-args))
```

**checkdock**

Fixed referrence to vars.


**package prefix**

Fine by me, I renamed `eval-with-shell-interpreter` into `with-shell-interpreter-eval`.

It's still clear enough what it does.

**Comment by riscy** [comment]
Apologies this has taken so long to get back to.  I'm taking a second pass to look at the code/semantics (and I'm reminded of our discussion on a shx issue! :)

I've been recently advised to be more strict regarding licenses on packages, so I have the following nags that I neglected to mention in the first round:

- Please add an [automatically detectable](https://github.com/licensee/licensee) LICENSE file to your repository (e.g. no markup)
- with-shell-interpreter.el has no (formal) license boilerplate before the `;;; Commentary` section (there is some boilerplate that references `lusty-explorer.el`, but I'm not sure which license it is)
- (Please use a [GPL-compatible](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses) license)

Some of the documentation, such as your commentary and elsewhere, suggests, e.g.:
```elisp
For full documentation on ARGS, please see the README file that came with
this file.  Usage:
```
but by default, MELPA doesn't ship the README, and usually it can be better if the functions are self-documenting in the Emacs style (i.e. comprehensive).  For what it's worth, your documentation does look comprehensive already, but the README pointer feels out of place.  Maybe add the README pointer to the end, with a web link, rather than at the beginning of the documentation?

Those are the main issues I can see right now, so once that's all resolved I think this should look good to merge.

Ultra minor:
- with-shell-interpreter.el#L166: Consider `when ...` instead of `unless (not ...)`
- providint -> providing
- usefull -> useful
- porperty -> property

**Comment by p3r7** [comment]
Now worry for time taken and thanks again for the feedback.

I fixed all the listed issues:
- [x] added GPL-compatible license (Expat aka MIT) [e1a55b6d39993d380806f5d486ce40df64d3bfe0](https://github.com/p3r7/with-shell-interpreter/commit/e1a55b6d39993d380806f5d486ce40df64d3bfe0) & [852b4d171ec64d1e4804f4bcdc7eece8f34421b9](https://github.com/p3r7/with-shell-interpreter/commit/852b4d171ec64d1e4804f4bcdc7eece8f34421b9)
- [x] added direct link to README [2eae11dbe18d65f0564da3e3b5e9f216f32a014e](https://github.com/p3r7/with-shell-interpreter/commit/2eae11dbe18d65f0564da3e3b5e9f216f32a014e)
- [x] biref commentary [8b218f125b7cfa6318748d22bc89e59ed2a76c94](https://github.com/p3r7/with-shell-interpreter/commit/8b218f125b7cfa6318748d22bc89e59ed2a76c94)
- [x] `when` instead of `unless (null ...)` [abcdc2d0e9a5fba1b71d967353419c5b443f0882](https://github.com/p3r7/with-shell-interpreter/commit/abcdc2d0e9a5fba1b71d967353419c5b443f0882)
- [x] fixed spelling (providint, usefull...) [85a95dace699ab2ee6a01a6a392af8da89556906](https://github.com/p3r7/with-shell-interpreter/commit/85a95dace699ab2ee6a01a6a392af8da89556906)

**Comment by riscy** [comment]
One small checkdoc popped up
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs):
with-shell-interpreter.el:74: Some lines are over 80 columns wide
```

and a quick flyspell yields:
- useinstead -> use instead
- implict -> implicit
- Usefull -> Useful

I think these are small enough to not block on, and I'll trust you'll get that checkdoc nag. :)

And, welcome to MELPA!

**Pull request merged**
