### PR TITLE
rename ob-sly to ob-lisp

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by milkypostman** [comment]
please add `:old-names` to the new recipe. 

example: https://github.com/melpa/melpa/blob/master/recipes/cider

**Comment by stardiviner** [comment]
@milkypostman I updated my recipe. Thanks for reviewing.

**Comment by stardiviner** [comment]
@milkypostman hi, can you merge this update now? I need to install it recently. sorry for disturbing you.

**Comment by tarsius** [comment]
There already is an `ob-lisp.el` which is part or Org-mode itself. Upon closer inspection it turned out that it actually is the *same* `ob-lisp.el`, @stardiviner just made one small change.

In my opinion @stardiviner should get his/her changes merged into Org-mode and his/her fork should be removed from Melpa. Also, @stardiviner, you should restore the list of authors in the library header - you are not the author you just added an option. (The years are wrong too.)

```diff
diff --git a/lisp/ob-lisp.el b/lisp/ob-lisp.el
index 04df7fb..7ba17c7 100644
--- a/lisp/ob-lisp.el
+++ b/lisp/ob-lisp.el
@@ -1,12 +1,14 @@
-;;; ob-lisp.el --- org-babel functions for common lisp evaluation
+;;; ob-lisp.el --- org-babel functions for common lisp evaluation with SLY or SLIME.
 
-;; Copyright (C) 2009-2016 Free Software Foundation, Inc.
+;; Copyright (C) 2016-2020 Free Software Foundation, Inc.
 
-;; Authors: Joel Boehland
-;;      Eric Schulte
-;;      David T. O'Toole <dto@gnu.org>
-;; Keywords: literate programming, reproducible research
-;; Homepage: http://orgmode.org
+;; Authors: stardiviner <numbchild@gmail.com>
+;; Maintainer: stardiviner <numbchild@gmail.com>
+;; Keywords: org babel lisp sly slime
+;; URL: https://github.com/stardiviner/ob-lisp
+;; Created: 1th March 2016
+;; Version: 0.0.1
+;; Package-Requires: ((org "8"))
 
 ;; This file is part of GNU Emacs.
 
@@ -25,17 +27,27 @@
 
 ;;; Commentary:
 
-;;; support for evaluating common lisp code, relies on slime for all eval
+;;; Support for evaluating Common Lisp code, relies on SLY or SLIME for all eval.
 
 ;;; Requirements:
 
-;; Requires SLIME (Superior Lisp Interaction Mode for Emacs.)
-;; See http://common-lisp.net/project/slime/
+;; Requires SLY (Sylvester the Cat's Common Lisp IDE) and SLIME
+;; See:
+;; - https://github.com/capitaomorte/sly
+;; - http://common-lisp.net/project/slime/
 
 ;;; Code:
 (require 'ob)
 
-(declare-function slime-eval "ext:slime" (sexp &optional package))
+(defcustom org-babel-lisp-eval-fn "sly-eval"
+  "The function to be called to evaluate code on the Lisp side."
+  :group 'org-babel
+  :version "24.1"
+  :options '("sly-eval" "slime-eval")
+  :type 'stringp)
+
+
+;; (declare-function sly-eval "ext:sly" (sexp &optional package))
 
 (defvar org-babel-tangle-lang-exts)
 (add-to-list 'org-babel-tangle-lang-exts '("lisp" . "lisp"))
@@ -71,25 +83,29 @@ (defun org-babel-expand-body:lisp (body params)
        (format "(pprint %s)" body)
       body)))
 
+;;;###autoload
 (defun org-babel-execute:lisp (body params)
-  "Execute a block of Common Lisp code with Babel."
-  (require 'slime)
+  "Execute a block `BODY' with `PARAMS' of Common Lisp code with Babel."
+  (pcase org-babel-lisp-eval-fn
+    ("slime-eval" (require 'slime))
+    ("sly-eval" (require 'sly)))
   (org-babel-reassemble-table
    (let ((result
          (funcall (if (member "output" (cdr (assoc :result-params params)))
                       #'car #'cadr)
                   (with-temp-buffer
                     (insert (org-babel-expand-body:lisp body params))
-                    (slime-eval `(swank:eval-and-grab-output
-                                  ,(let ((dir (if (assoc :dir params)
-                                                  (cdr (assoc :dir params))
-                                                default-directory)))
-                                     (format
-                                      (if dir (format org-babel-lisp-dir-fmt dir)
-                                        "(progn %s\n)")
-                                      (buffer-substring-no-properties
-                                       (point-min) (point-max)))))
-                                (cdr (assoc :package params)))))))
+                    (funcall org-babel-lisp-eval-fn
+                             `(swank:eval-and-grab-output
+                               ,(let ((dir (if (assoc :dir params)
+                                               (cdr (assoc :dir params))
+                                             default-directory)))
+                                  (format
+                                   (if dir (format org-babel-lisp-dir-fmt dir)
+                                     "(progn %s\n)")
+                                   (buffer-substring-no-properties
+                                    (point-min) (point-max)))))
+                             (cdr (assoc :package params)))))))
      (org-babel-result-cond (cdr (assoc :result-params params))
        result
        (condition-case nil
```

**Comment by stardiviner** [comment]
@tarsius Hi, I'd like to send push request to Org-mode. But I can't find Org-mode repo on GitHub.

**Comment by tarsius** [comment]
You have to send your patch to the mailing list, see http://orgmode.org/community.html.

**Comment by purcell** [comment]
Thanks @tarsius - recipe removed in ea64446. @stardiviner: definitely follow up on the org-mode mailing list, but if you eventually decide instead to rename this back to `ob-sly`, just let me know, and we can re-add it.

**Comment by stardiviner** [comment]
@purcell Sorry for distributing you, Seems Org-mode ML have not updated for a few days. I can't wait. I need to use my own modify. So I rename it back to `ob-sly`.
Here is the ML thread: http://thread.gmane.org/gmane.emacs.orgmode/105928
My recipe is still on branch `ob-sly`.
Should I create a PR again?

**Comment by stardiviner** [comment]
I created an PR at here: https://github.com/melpa/melpa/pull/3763

**Comment by tarsius** [comment]
The patch has been applied: http://thread.gmane.org/gmane.emacs.orgmode/105928.

**Comment by purcell** [comment]
@tarsius Great, so that means we drop `ob-sly`/`ob-lisp` from MELPA, right?

**Comment by tarsius** [comment]
Or rather not add it again.

**Comment by purcell** [comment]
Oh right, yes - it's currently not here. :-)

**Comment by stardiviner** [comment]
Awesome, I will delete my PR. Thanks guys.

**Pull request merged**
