### PR TITLE
Add recipe isearch-project.

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Incremental search through the whole project.

### Direct link to the package repository

https://github.com/jcs090218/isearch-project

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
This looks cool.  Good screencast in the readme.

Looking at the code, I see functions like:

* ` isearch-project-is-contain-list-string`
* ` isearch-project-remove-nth-element`
* `isearch-project-filter-directory-files-recursively`

Which seem to reimplement existing functionality.  I recommend looking at existing libraries like `cl-lib`, `dash`, and `f`.  There is also, e.g. `directory-files-recursively` which has a `REGEXP` argument.

**Comment by purcell** [comment]
>     * ``
> 
> 
> Which seem to reimplement existing functionality. I recommend looking at existing libraries like `cl-lib`, `dash`, and `f`. There is also, e.g. `directory-files-recursively` which has a `REGEXP` argument.

Agree.

Other notes:
- Whenever I see a list like `isearch-project-ignore-paths`, I know that an opportunity to re-use built-in functionality has been missed. You should never need to repeat exclusions for `.git`, `.hg` etc in multiple packages! `grep-find-ignored-directories` is a standard variable for this purpose, for example. Or maybe use `project.el` or `projectile` to help you know what files the user considers "searchable" in the current context. Don't forget there are other considerations like ignoring binary files etc.
- Regarding things like `isearch-project-forward-symbol-at-point`, there's already `compilation-next-error`, and behaviour like this is built into grep-mode etc. Why not use built-in or packaged search functionality internally and simply hide the `*grep*` buffer? This would let you dramatically simplify the code, and would potentially allow it to work with `rg`, `ag` etc. too.
- There's a typo [here](https://github.com/jcs090218/isearch-project/blob/8ba55c00fb96e6f262261f1560254decbf8cbb7b/isearch-project.el#L56), but in any case you shouldn't use `\` to extend initial docstring lines across two lines.

**Comment by purcell** [comment]
(I should add that I really like the idea of letting the user seamlessly switch from searching within a single file to jumping across an entire project. I'd like to see this as seamless and reliable as possible, hence the critical feedback above.)

**Comment by jcs090218** [comment]
> * Whenever I see a list like `isearch-project-ignore-paths`, I know that an opportunity to re-use built-in functionality has been missed. You should never need to repeat exclusions for `.git`, `.hg` etc in multiple packages! `grep-find-ignored-directories` is a standard variable for this purpose, for example. Or maybe use `project.el` or `projectile` to help you know what files the user considers "searchable" in the current context. Don't forget there are other considerations like ignoring binary files etc.

Fixed! I used grep-find-ignored-directories instead of self defined variable `isearch-project-ignore-paths`.

> * Regarding things like `isearch-project-forward-symbol-at-point`, there's already `compilation-next-error`, and behaviour like this is built into grep-mode etc. Why not use built-in or packaged search functionality internally and simply hide the `*grep*` buffer? This would let you dramatically simplify the code, and would potentially allow it to work with `rg`, `ag` etc. too.

I just have it as an option because `isearch` have one and I used it a lot. The reason I don't use `grep` because I never used it, I would definitely like to give it a try. :D

> * There's a typo [here](https://github.com/jcs090218/isearch-project/blob/8ba55c00fb96e6f262261f1560254decbf8cbb7b/isearch-project.el#L56), but in any case you shouldn't use `\` to extend initial docstring lines across two lines.

Fixed!

**Comment by purcell** [comment]
Merged now, thanks

**Pull request merged**
