### PR TITLE
add recipe for sentex

### PR DESCRIPTION
**Pull request by mooseyboots**
### Brief summary of what the package does

Provides complex sentence-ending rules based on OmegaT and Okapi Framework regular expressions.

### Direct link to the package repository

https://codeberg.org/martianh/sentex

### Your association with the package

author

### Relevant communications with the upstream package maintainer

NA

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by mooseyboots** [comment]
ah, my repo includes .eld files, which melpa doesn't accept by default. i have adapted the default files directive to include them, but if avoiding .eld is considered best practice, i can also do that.

**Comment by tarsius** [comment]
> it looks like that's why the CI build failed too?

The error message is `Invalid files spec entry quote`. That means that you must remove the quote that appears here: `:files '(...)`.

You also should not duplicate the default spec, instead you should reference it: `:files (:defaults "*.eld")`. That is documented at https://github.com/melpa/melpa#recipe-format.

**Comment by mooseyboots** [comment]
amended

**Comment by riscy** [comment]
Thanks -- the rules lists are impressive.

**Pull request merged**
