### PR TITLE
Add recipe for tabnine

### PR DESCRIPTION
**Pull request by shuxiao9058**
### Brief summary of what the package does

AI complete package with [tabnine](https://www.tabnine.com/).

### Direct link to the package repository

https://github.com/shuxiao9058/tabnine

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by tarsius** [comment]
Please use a separate pull-request for each package. Doing that makes review easier. Thanks!

**Comment by shuxiao9058** [comment]
> Please use a separate pull-request for each package. Doing that makes review easier. Thanks!

done now, this pr for tabnine recipe

**Comment by riscy** [comment]
Thank you very much both!  Here's a quick review of tabnine vs. the checklist --

`tabnine.el` with byte-compile using Emacs 28.1:
```
tabnine.el:119:1: Warning: custom-declare-variable `tabnine-idle-delay'
    docstring wider than 80 characters
In tabnine--buffer-changed:
tabnine.el:246:8: Warning: docstring wider than 80 characters
In tabnine--send-request:
tabnine.el:286:11: Warning: docstring wider than 80 characters
tabnine.el:286:34: Warning: Unused lexical argument `request'
In tabnine--completion-capf-p:
tabnine.el:620:32: Warning: Unused lexical variable `kind'
tabnine.el:621:33: Warning: Unused lexical variable `completion_kind'
In tabnine--response-display-with-capf-p:
tabnine.el:634:8: Warning: `mapcar' called for effect; use `mapc' or `dolist'
    instead
In tabnine--process-filter:
tabnine.el:661:41: Warning: Unused lexical argument `process'
In tabnine-install-binary:
tabnine.el:724:10: Warning: Unused lexical variable `ex'
In tabnine--overlay-displaying-result:
tabnine.el:780:11: Warning: Unused lexical variable `ov-completion-index'
In tabnine--set-overlay-text:
tabnine.el:840:61: Warning: Unused lexical variable `tail'
In tabnine--show-completion:
tabnine.el:941:47: Warning: Unused lexical variable `kind'
tabnine.el:942:23: Warning: Unused lexical variable `detail'
tabnine.el:949:44: Warning: Unused lexical variable `ov'
In tabnine-complete:
tabnine.el:993:56: Warning: Unused lexical variable `cached-result'
tabnine.el:1033:1: Warning: defcustom for `tabnine-completion-triggers' fails
    to specify type
tabnine.el:1033:1: Warning: defcustom for `tabnine-completion-triggers' fails
    to specify type
In tabnine-completion-at-point:
tabnine.el:1249:25: Warning: Unused lexical argument `status'
In tabnine--prefetch-advice:
tabnine.el:1263:50: Warning: Unused lexical argument `orig-func'
tabnine.el:1263:50: Warning: Unused lexical argument `args'
In end of data:
tabnine.el:886:14: Warning: the function `vterm-insert' is not known to be
    defined.
tabnine.el:885:14: Warning: the function `vterm-delete-region' is not known to
    be defined.
```

`tabnine.el` with checkdoc 0.6.2:
```
tabnine.el:1076: Argument `args' should appear (as ARGS) in the doc string
tabnine.el:1089: Argument `&reset' should appear (as &RESET) in the doc string
tabnine.el:1264: All variables and subroutines might as well have a documentation string
```
A variable named "&reset" looks very unusual to me -- should this be `&rest`?

`tabnine.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- tabnine.el#L256: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
- tabnine.el#L1267: Loading a package should rarely add advice
- tabnine.el#L564: Consider using %F instead of %Y-%m-%d in time strings
- tabnine.el#L564: Consider using %T instead of %H:%M:%S in time strings
```


On a very quick scan I also notice `shell-command` being called without using `shell-quote-argument` on the args.  For example `(shell-command (format "tar -xf %s" (expand-file-name bundle-path)))` is a little unsafe, because it is possible for a filename to have shell control characters in it like `'` or `>` or `|`.

**Comment by shuxiao9058** [comment]
> Thank you very much both! Here's a quick review of tabnine vs. the checklist --
> 
> `tabnine.el` with byte-compile using Emacs 28.1:
> 
> ```
> tabnine.el:119:1: Warning: custom-declare-variable `tabnine-idle-delay'
>     docstring wider than 80 characters
> In tabnine--buffer-changed:
> tabnine.el:246:8: Warning: docstring wider than 80 characters
> In tabnine--send-request:
> tabnine.el:286:11: Warning: docstring wider than 80 characters
> tabnine.el:286:34: Warning: Unused lexical argument `request'
> In tabnine--completion-capf-p:
> tabnine.el:620:32: Warning: Unused lexical variable `kind'
> tabnine.el:621:33: Warning: Unused lexical variable `completion_kind'
> In tabnine--response-display-with-capf-p:
> tabnine.el:634:8: Warning: `mapcar' called for effect; use `mapc' or `dolist'
>     instead
> In tabnine--process-filter:
> tabnine.el:661:41: Warning: Unused lexical argument `process'
> In tabnine-install-binary:
> tabnine.el:724:10: Warning: Unused lexical variable `ex'
> In tabnine--overlay-displaying-result:
> tabnine.el:780:11: Warning: Unused lexical variable `ov-completion-index'
> In tabnine--set-overlay-text:
> tabnine.el:840:61: Warning: Unused lexical variable `tail'
> In tabnine--show-completion:
> tabnine.el:941:47: Warning: Unused lexical variable `kind'
> tabnine.el:942:23: Warning: Unused lexical variable `detail'
> tabnine.el:949:44: Warning: Unused lexical variable `ov'
> In tabnine-complete:
> tabnine.el:993:56: Warning: Unused lexical variable `cached-result'
> tabnine.el:1033:1: Warning: defcustom for `tabnine-completion-triggers' fails
>     to specify type
> tabnine.el:1033:1: Warning: defcustom for `tabnine-completion-triggers' fails
>     to specify type
> In tabnine-completion-at-point:
> tabnine.el:1249:25: Warning: Unused lexical argument `status'
> In tabnine--prefetch-advice:
> tabnine.el:1263:50: Warning: Unused lexical argument `orig-func'
> tabnine.el:1263:50: Warning: Unused lexical argument `args'
> In end of data:
> tabnine.el:886:14: Warning: the function `vterm-insert' is not known to be
>     defined.
> tabnine.el:885:14: Warning: the function `vterm-delete-region' is not known to
>     be defined.
> ```
> 
> `tabnine.el` with checkdoc 0.6.2:
> 
> ```
> tabnine.el:1076: Argument `args' should appear (as ARGS) in the doc string
> tabnine.el:1089: Argument `&reset' should appear (as &RESET) in the doc string
> tabnine.el:1264: All variables and subroutines might as well have a documentation string
> ```
> 
> A variable named "&reset" looks very unusual to me -- should this be `&rest`?
> 
> `tabnine.el` with [melpazoid](https://github.com/riscy/melpazoid):
> 
> ```
> - tabnine.el#L256: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
> - tabnine.el#L1267: Loading a package should rarely add advice
> - tabnine.el#L564: Consider using %F instead of %Y-%m-%d in time strings
> - tabnine.el#L564: Consider using %T instead of %H:%M:%S in time strings
> ```
> 
> On a very quick scan I also notice `shell-command` being called without using `shell-quote-argument` on the args. For example `(shell-command (format "tar -xf %s" (expand-file-name bundle-path)))` is a little unsafe, because it is possible for a filename to have shell control characters in it like `'` or `>` or `|`.

fixed now.

**Comment by riscy** [comment]
Thanks! Here's the latest --
`tabnine.el` with byte-compile using Emacs 28.1:
```
tabnine.el:884:14: Warning: the function `vterm-insert' is not known to be
    defined.
tabnine.el:883:14: Warning: the function `vterm-delete-region' is not known to
    be defined.
```

`tabnine.el` with checkdoc 0.6.2:
```
tabnine.el:1084: Argument `&reset' should appear (as &RESET) in the doc string
```
Please see above re: the name of this variable.

`tabnine.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- tabnine.el#L258: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
- tabnine.el#L1264: Loading a package should rarely add advice
```
This nag on 1264 is from my own scripts, but appears to be a new issue -- simply loading a package shouldn't cause a global side-effect like this.   Most of these should happen as a result of the user explicitly calling a function or toggling a mode off or on -- I'd add this advice when tabnine is enabled (and remove it when the mode is disabled0.

**Comment by shuxiao9058** [comment]
> 

done, please have a review now.

**Comment by riscy** [comment]
Thanks!  This look good to go, I'll hit merge.

Not a blocker, but I just noticed In this:
```elisp
;;; tabnine.el --- An unofficial TabNine package ;; -*- lexical-binding: t -*-
```
There's no need for the `;;` (this should be removed in case it inadvertently becomes part of your package summary)

**Pull request merged**
