### PR TITLE
Add flymake-golangci recipe

### PR DESCRIPTION
**Pull request by shackra**
### Brief summary of what the package does

A flymake backend that uses golangci lint for linting go-mode source files

### Direct link to the package repository

https://gitlab.com/shackra/flymake-golangci

### Your association with the package

author and maintainer

### Relevant communications with the upstream package maintainer

Not relevant.

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
> but the recipe contains the URL plist, so, what could be going on?

For the `gitlab` fetcher you should only set `:repo`. You should *not* also set `:url`.

**Comment by shackra** [comment]
I have build the package with `make recipes/flymake-golangci` successfully

**Comment by riscy** [comment]
A quick pass over the checklist:

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190905.1847):
```
No issues found.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems) (and depend on at least (emacs "24"))
(The following assumes lexical binding is enabled)
```
flymake-golangci.el:60:1:Warning: defcustom for `flymake-golangci-executable'
    fails to specify type
flymake-golangci.el:60:1:Warning: defcustom for `flymake-golangci-executable'
    fails to specify containing group
flymake-golangci.el:60:1:Warning: defcustom for `flymake-golangci-executable'
    fails to specify type
flymake-golangci.el:60:1:Warning: defcustom for `flymake-golangci-executable'
    fails to specify containing group
flymake-golangci.el:64:1:Warning: defcustom for `flymake-golangci-deadline'
    fails to specify type
flymake-golangci.el:64:1:Warning: defcustom for `flymake-golangci-deadline'
    fails to specify containing group
flymake-golangci.el:64:1:Warning: defcustom for `flymake-golangci-deadline'
    fails to specify type
flymake-golangci.el:64:1:Warning: defcustom for `flymake-golangci-deadline'
    fails to specify containing group
flymake-golangci.el:67:1:Warning: defcustom for `flymake-golangci-tests' fails
    to specify containing group
flymake-golangci.el:67:1:Warning: defcustom for `flymake-golangci-tests' fails
    to specify containing group
flymake-golangci.el:72:1:Warning: defcustom for `flymake-golangci-fast' fails
    to specify containing group
flymake-golangci.el:72:1:Warning: defcustom for `flymake-golangci-fast' fails
    to specify containing group
flymake-golangci.el:77:1:Warning: defcustom for `flymake-golangci-disable-all'
    fails to specify containing group
flymake-golangci.el:77:1:Warning: defcustom for `flymake-golangci-disable-all'
    fails to specify containing group
flymake-golangci.el:82:1:Warning: defcustom for `flymake-golangci-enable-all'
    fails to specify containing group
flymake-golangci.el:82:1:Warning: defcustom for `flymake-golangci-enable-all'
    fails to specify containing group
flymake-golangci.el:87:1:Warning: defcustom for
    `flymake-golangci-enable-linters' fails to specify containing group
flymake-golangci.el:87:1:Warning: defcustom for
    `flymake-golangci-enable-linters' fails to specify containing group
flymake-golangci.el:91:1:Warning: defcustom for
    `flymake-golangci-disable-linters' fails to specify containing group
flymake-golangci.el:91:1:Warning: defcustom for
    `flymake-golangci-disable-linters' fails to specify containing group
```

Added miscellaneous hints (automated):
- flymake-golangci.el#L7: Use `Version` instead of `Package-Version` (MELPA automatically adds `Package-Version`)
- flymake-golangci.el#L21: Prefer `https` over `http` (if possible)

**Comment by shackra** [comment]
I made some changes, please let me know.

**Comment by riscy** [comment]
Looks good.  Thanks!

**Pull request merged**
