### PR TITLE
Add recipe for es6-snippets

### PR DESCRIPTION
**Pull request by CodyReichert**
### Brief summary of what the package does

`es6-snippets` provides [a set of yasnippets](https://github.com/CodyReichert/es6-snippets#snippets) for writing JavaScript in ES6 syntax.

### Direct link to the package repository

https://github.com/CodyReichert/es6-snippets

### Your association with the package

Owner/maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by DamienCassou** [comment]
Could you please contribute your snippets to https://github.com/AndreaCrotti/yasnippet-snippets instead of creating another package?

MELPA provides a curated set of Emacs Lisp packages, not an exhaustive list of every single Emacs Lisp file ever created. As such, MELPA maintainers tend to only accept packages not duplicating existing packages.

**Comment by CodyReichert** [comment]
Sure. What's the case with all of the other snippet packages in MELPA, out of curiosity?

**Comment by DamienCassou** [comment]
> What's the case with all of the other snippet packages in MELPA, out of curiosity?

let's ask the others: @purcell @milkypostman @tarsius @syohex

**Comment by DamienCassou** [comment]
I'm closing this ticket as there hasn't been any feedback on it. I hope others will reopen if they disagree.

**Pull request closed without merging**
