### PR TITLE
Add counsel-org-clock

### PR DESCRIPTION
**Pull request by akirak**
### Brief summary of what the package does

Counsel (Ivy) commands for org-clock

### Direct link to the package repository

https://github.com/akirak/counsel-org-clock

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by DamienCassou** [comment]
Please lint your code as specified by CONTRIBUTING.md. Your code has at least 9 issues. More feedback:

- you might want to extract the large `cl-destructuring-bind` block from `counsel-org-clock-context` into a new function. This should be easier to read.
- instead of passing `:test` to `cl-remove-duplicate`, you can pass `:key`, this will make your code much simpler

    ```emacs
    (cl-remove-duplicates [...] :key #'cdr)
    ```
- what about extracting the definition of the "clock out (if current)" action to its own function?

**Comment by akirak** [comment]
Thank you for your feedback. 

> Your code has at least 9 issues. 

I checked my package with package-lint and flycheck-package, but I encountered only the following error: "Cannot open load file: No such file or directory, ivy"

Do you know how to fix this error? There seems to be something wrong with my configuration of the checker...

I will fix up the rest soon.

**Comment by akirak** [comment]
Now I think I have fixed the issues. My package presents no issue at least in my environment.

**Comment by DamienCassou** [comment]
Akira Komamura <notifications@github.com> writes:
> I checked my package with package-lint and flycheck-package, but I
> encountered only the following error: "Cannot open load file: No such
> file or directory, ivy".  Do you know how to fix this error? There
> seems to be something wrong with my configuration of the checker...

this is highly dependent on your personal configuration and hard to get
it right (at least for me). To make sure my packages are ok, I use
Travis or Gitlab CI to run the linters for me.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by akirak** [comment]
I've edited the comment so that it contains a link to the thread.

**Comment by purcell** [comment]
Thanks - this looks good. Merging now.

Regarding the comment `This is deprecated in 0.2. Use `counsel-org-clock--with-marker'.` - you can use `define-obsolete-function-alias` for this instead. :-)

**Pull request merged**
