### PR TITLE
Add recipe for quelpa-leaf

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Emacs quelpa handler for leaf

*P.S This is basically the port of [quelpa-use-package](https://github.com/quelpa/quelpa-use-package)*

### Direct link to the package repository

https://github.com/quelpa/quelpa-leaf

### Your association with the package

The maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by jcs090218** [comment]
@riscy I know I have multiple PRs opened at once. Now I have only #7292 and this (2). Is this okay to you? Or you want me to close this down? 😕 

Let me know what you think! Thanks!

**Comment by riscy** [comment]
Don't worry, it's okay to occasionally have multiple PR's open. :)

**Comment by riscy** [comment]
Just one package-lint on this one:

package-lint (using version 20210111.341):
```
1 issue found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
```
I think this isn't a false positive, since Quelpa is also capitalized in Quelpa documentation.

The other issue I see is this happening at the top-level:
```
;;;###autoload
(quelpa-leaf-init)
```
but really a line like that should go in the `;;; Commentary`, since packages should try to avoid making modifications simply when they're loaded (with a few exceptions like auto-mode-alist).

Maybe we can also ask @canao3 to take a quick peek to see if this is idiomatic.

**Comment by jcs090218** [comment]
> I think this isn't a false positive, since Quelpa is also capitalized in Quelpa documentation.

I have kept it lowercase intentionally because [quelpa-use-package]() has lowercase. Just to keep thing consistent. Of course this isn't a huge blocker for me to change it.

> but really a line like that should go in the ;;; Commentary, since packages should try to avoid making modifications simply when they're loaded (with a few exceptions like auto-mode-alist).

Ah.. I think this was my mistake. Fixed in https://github.com/quelpa/quelpa-leaf/commit/a88e8de6f6c8d1806ebe98b2ef4330794a00c5c4.

---

Thanks for the review!

**Comment by riscy** [comment]
> Just to keep things consistent. Of course this isn't a huge blocker for me to change it.

Probably that other package should upcase it as well. :)  I trust you'll fix that though, so that's not a blocker.  But I'll let this sit open a little while in case we hear anything from @canao3.  It should be an easy merge soon.

**Comment by jcs090218** [comment]
> in case we hear anything from @canao3

I think you are meant @conao3? A friendly ping here. :)

**Comment by conao3** [comment]
Thanks for mentioning me!
I basically want to consolidate leaf plugins into `leaf-keywords` instead of cluttering up packages like `leaf-*` for leaf keywords.
If @jcs090218 is willing, please consider contributing to [leaf-keywords](https://github.com/conao3/leaf-keywords.el).

**Comment by jcs090218** [comment]
I may just keep it as it is. :)

**Comment by conao3** [comment]
OK, I don't like create `leaf-*` package to add new keyword, but I can't actively stop it; there is no blocker that will refuse to add it to MELPA if it clears @riscy's review.

**Comment by riscy** [comment]
Thanks both.  I suppose there's nothing stopping @conao3 from implementing such behavior in `leaf-keywords` (maybe it's easy to do so?), but I think this disagreement isn't a blocker.

> Ah.. I think this was my mistake. Fixed in quelpa/quelpa-leaf@a88e8de.

Probably I wasn't clear - you should tell people to call `(quelpa-leaf-init)` in your commentary.  You should not do this when the package is simply imported.

This remains -- package-lint (using version 20210111.341):
```
1 issue found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
```

And one note:
- quelpa-leaf.el#L63: No `format` required; `warn` takes an f-string

**Comment by jcs090218** [comment]
> Probably I wasn't clear - you should tell people to call (quelpa-leaf-init) in your commentary. You should not do this when the package is simply imported.

I don't know why I have it in the first place. Fixed!

> quelpa-leaf.el#L63: No format required; warn takes an f-string

Good catch. Thanks!

**Pull request merged**
