### PR TITLE
add cell-mode recipe

### PR DESCRIPTION
**Pull request by dto**
### Brief summary of what the package does

Cell-mode implements a customizable object-oriented spreadsheet user interface in an Emacs buffer.

### Direct link to the package repository

https://gitlab.com/dto/cell-mode

### Your association with the package

I am the author and maintainer. 

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

Notes: In some spots Flycheck fails to detect docstrings after CL-DEFMETHOD. I use dynamic binding in the inner rendering loop, but I am planning to eliminate this.

### CODE REVIEW

**Comment by riscy** [comment]
Thanks.  I was about to suggest you compare this to `cell-mode`, and then I realized _this_ is that package, and it isn't indexed yet. :)  Quick first pass --

### cell-mode.el ###

byte-compile (using Emacs 27.1):
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
cell-mode.el:148:30:Warning: Package cl is deprecated
In cell-insert:
cell-mode.el:1392:28:Warning: reference to free variable `row'
cell-mode.el:1392:32:Warning: reference to free variable `col'
In cell-insert-blank:
cell-mode.el:1404:26:Warning: reference to free variable `row'
cell-mode.el:1404:30:Warning: reference to free variable `col'
In cell-insert-spacer:
cell-mode.el:1418:24:Warning: reference to free variable `row'
cell-mode.el:1418:28:Warning: reference to free variable `col'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
cell-mode.el:254: All variables and subroutines might as well have a documentation string
Warning (emacs): 
cell-mode.el:326: All variables and subroutines might as well have a documentation string
Warning (emacs): 
cell-mode.el:354: All variables and subroutines might as well have a documentation string
Warning (emacs): 
cell-mode.el:363: All variables and subroutines might as well have a documentation string
Warning (emacs): 
cell-mode.el:672: All variables and subroutines might as well have a documentation string
Warning (emacs): 
cell-mode.el:1253: White space found at end of line
```

package-lint (using version 20200906.512):
```
1 issue found:
148:29: warning: Replace deprecated `cl' with `cl-lib'.  The `cl-libify' package can help with this.
```

Other [lints](https://github.com/riscy/melpazoid):
- cell-mode.el#L662: It's safer to sharp-quote function names; use `#'`
- cell-mode.el#L663: It's safer to sharp-quote function names; use `#'`
- cell-mode.el#L676: Optionally use `unless ...` instead of `when (not ...)`
- cell-mode.el#L678: Optionally use `unless ...` instead of `when (not ...)`
- cell-mode.el#L680: Optionally use `unless ...` instead of `when (not ...)`
- cell-mode.el#L682: Optionally use `unless ...` instead of `when (not ...)`
- cell-mode.el#L726: Optionally use `unless ...` instead of `when (not ...)`
- cell-mode.el#L853: Optionally use `unless ...` instead of `when (not ...)`
- cell-mode.el#L1226: Optionally use `unless ...` instead of `when (not ...)`
- cell-mode.el#L1719: Optionally use `unless ...` instead of `when (null ...)`
- cell-mode.el#L35: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by riscy** [comment]
I'll mark this awaiting upstream, but feel free to ping when ready for another look.

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by dto** [comment]
> 

Greetings @riscy , my sincere apologies for not answering these messages sooner, I did not see the notifications. I'm planning to revise cell-mode to make the changes you suggest. Thanks for your feedback and assistance!

**Comment by riscy** [comment]
No trouble!  I'll re-mark this awaiting upstream for now but feel free to reach out.

**Pull request closed without merging**
