### PR TITLE
Add recipe for symbol-overlay-mc

### PR DESCRIPTION
**Pull request by mavit**
-------

### Brief summary of what the package does

Provides integration between the `symbol-overlay` and `multiple-cursors` packages.

### Direct link to the package repository

https://github.com/xenodium/symbol-overlay-mc/

### Your association with the package

I am a contributor.

### Relevant communications with the upstream package maintainer

[The author has suggested I submit the package to MELPA](https://www.reddit.com/r/emacs/comments/1h321x2/comment/lzpk5lv/).

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
This PR is changing the MELPA recipe to a "test" branch - we prefer to point to the default branch, but maybe this change wasn't deliberate?

**Comment by mavit** [comment]
> but maybe this change wasn't deliberate?

Indeed not.  I somehow seem to have committed entirely the wrong thing. Apologies.  Now fixed.

**Comment by riscy** [comment]
Thanks!

Quick feedback on the metadata: I think the `;;; Commentary` could be expanded on - I had to jump from reddit to the blog post to get an idea of what this package does.  Similarly with your summary line, "Symbol overlay extensions" (I see one "extension" and my brain wants to file this under multiple cursor extensions, not symbol overlay extensions).

Re: package-lint -

⸺ `symbol-overlay-mc.el` with package-lint 20241127.1826:
```
1 issue found:
57:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

This is sometimes a contentious one but I think reasonably applies here and is worth unpacking.  This sort of thing is usually left to users to sort out, i.e. in their configs, because in theory they may not want this shortcut (and how will a novice know how to remove it?), they may want to use that keybinding for something else, or *another* package might want to use that same keybinding, and then which package gets to win the autoload battle?  If you want to provide users with a convenience for this, you could define an autoloaded function that runs this form.

**Comment by mavit** [comment]
> This is sometimes a contentious one but I think reasonably applies here and is worth unpacking. This sort of thing is usually left to users to sort out, i.e. in their configs, because in theory they may not want this shortcut (and how will a novice know how to remove it?), they may want to use that keybinding for something else, or _another_ package might want to use that same keybinding, and then which package gets to win the autoload battle?

I appreciate this is a concern in general, but collisions seem pretty unlikely in this particular case.  It seems like a bridge we could cross if we ever came to it.

I hate that we make users stop, read the documentation, and think about this sort of thing every time they try out a new package.  For me, one of the big benefits of transient menus is that they avoid the need to set up (and then forget) lots of keybindings; they can just quietly be there when you want them.

Nevertheless, I will submit a pull request to remove this feature.

**Comment by riscy** [comment]
> but collisions seem pretty unlikely in this particular case

You're right, they usually are pretty unlikely.  But it's admittedly far easier (for lazy me :) to encourage a "rule" than a grey area.

Thanks again for this - merging!

**Pull request merged**
