### PR TITLE
add: dired-view-data

### PR DESCRIPTION
**Pull request by ShuguangSun**
### Brief summary of what the package does

View data from dired via ESS.

### Direct link to the package repository

https://github.com/ShuguangSun/dired-view-data

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thank you for this.  Quick first pass --

### dired-view-data.el ###

byte-compile (using Emacs 27.1):
```
dired-view-data.el:188:17:Warning: reference to free variable
    `dired-guess-shell-alist-user'
dired-view-data.el:188:17:Warning: assignment to free variable
    `dired-guess-shell-alist-user'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
dired-view-data.el:71: Symbols t and nil should not appear in single quotes
Warning (emacs): 
dired-view-data.el:128: Argument `dt' should appear (as DT) in the doc string
Warning (emacs): 
dired-view-data.el:135: Argument `file-name' should appear (as FILE-NAME) in the doc string
```

**Comment by ShuguangSun** [comment]
Thanks for the check. Updated and fixed.

**Comment by riscy** [comment]
Hello, I had a quick look and the fixes don't appear to be in place yet.  Possibly they haven't been merged into your default branch.

**Comment by ShuguangSun** [comment]
Now updated.

Sorry for my mistake.

**Comment by riscy** [comment]
Thanks a lot, that puts the checklist behind us.

Just a couple bits of more in-depth feedback.  The package name dired-view-data.el doesn't right away make me think of ESS -- maybe `dired-view-ess-data` or similar may be a more discoverable name, or even `dired-view-data-r` to make it clear that you're favoring R instead of something else.  The other thing I notice is that you've got 90% of a minor mode here with the function `dired-view-data-initialization`.  I suggest defining a minor mode with its own keymap (rather than sneaking a keybinding into `dired-mode-map` when the user calls this function), which will additionally let users easily turn the behavior back off again.

**Comment by ShuguangSun** [comment]
Thanks.

1. For the package name, I'm thinking in the future it would be expanded to employ python (e.g., pandas) as another backend. So I leave the name alone.
2. It is a good idea to define a minor mode. I'll implent it.

**Comment by riscy** [comment]
> For the package name, I'm thinking in the future it would be expanded to employ python (e.g., pandas) as another backend. So I leave the name alone.

Ok, I think that's completely reasonable.  In the meantime it may be worth adjusting your summary line to include the R restriction so nobody is surprised by the reliance on R.  E.g. "View data in dired using ESS and R".  You can adjust it in the future when you support more backends.

> It is a good idea to define a minor mode. I'll implent it.

Thanks!  Feel free to ping here when that's ready for a look.

**Comment by ShuguangSun** [comment]
The minor mode added.

**Comment by riscy** [comment]
Thanks -- I think this is good to merge, but after another close look here are a handful of issues you may want to look into:

- Filenames can contain `'` which means patterns like ```"`%1$s` <- readRDS('%2$s')\n"``` can fail or inadvertently execute code.  One approach for dealing with this might be to lean on `shell-quote-argument` or to simply refuse to "view" files that contain dangerous characters
- Unless I'm missing something, I suspect the function `dired-view-data-mode-on` isn't necessary -- users can just call `dired-view-data-mode` in most cases
- `dired-view-data-mode-hook` is defined as a variable but not referenced anywhere. I'd recommend you just drop it unless there's an existing use-case that needs hooks
- `dired-view-data-mode` gives no feedback to the user when it doesn't apply (e.g. when we're not using dired-mode)

**Pull request merged**
