### PR TITLE
Add recipe for python-blue

### PR DESCRIPTION
**Pull request by grantjenks**
### Brief summary of what the package does

Use the Python [Blue](https://pypi.org/project/blue/) package to reformat Python buffers.

### Direct link to the package repository

https://github.com/grantjenks/emacs-python-blue

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by grantjenks** [comment]
I'm not sure if the code requires "cl-lib". I noticed this is common in other packages but python-blue seems to work fine without it.

**Comment by grantjenks** [comment]
Also, when I navigate my fork of the "melpa" repository, Emacs pops up lots of messages like:
```
The local variables list in /Users/grantjenks/repos/melpa/recipes/
contains values that may not be safe (*).

Do you want to apply it?  You can type
y  -- to apply the local variables list.
n  -- to ignore the local variables list.
!  -- to apply the local variables list, and permanently mark these
      values (*) as safe (in the future, they will be set automatically.)
```
And I'm not sure if that's the fault of my python-blue package or some wizardry in the melpa repo that my config is not playing nice with. Please advise.

**Comment by dakra** [comment]
Since `blue` is basically `black` wouldn't it be easier to just use any of the existing black formatters and set the back-format-command to `blue` ?

I personally use https://github.com/raxod502/apheleia
But there is also https://github.com/wbolster/emacs-python-black and https://github.com/pythonic-emacs/blacken

And if you implement a formatter I would probably use https://github.com/purcell/emacs-reformatter which makes creating new formatters really easy.

**Comment by riscy** [comment]
> Since blue is basically black wouldn't it be easier to just use any of the existing black formatters and set the back-format-command to blue ?

This is good feedback, and it's worth considering alongside the fact that the blue project would prefer it if black just added more configuration options.  @grantjenks I notice you're one of the authors of blue, but have you considered whether that would fulfill your use-case?

On the other hand, I think the blue project is accumulating lots of little differences.  I would *bet* on blue getting more and more different from black over time with a different ecosystem of formatting options, so I don't think MELPA should be against merging this, especially since it's being contributed by the same author as the blue python package.

**Comment by grantjenks** [comment]
> @dakra I personally use https://github.com/raxod502/apheleia
> ...
> And if you implement a formatter I would probably use https://github.com/purcell/emacs-reformatter which makes creating new formatters really easy.

Both of those look promising. I'm investigating them as options.

> @riscy have you considered whether that would fulfill your use-case?

Integrating Blue with Black is one of the long term goals. Unfortunately, Black is famously the "uncompromising Python code formatter" so compromise will take some time.

**Comment by riscy** [comment]
Do you want to hold off on merging (and potentially growing your userbase) while you investigate the aforementioned options?  I don't think there are any blockers here.

**Comment by grantjenks** [comment]
Sure, let's revisit once I can investigate the other options.

**Pull request closed without merging**
