### PR TITLE
Add prog-fill recipe

### PR DESCRIPTION
**Pull request by ahungry**
### Brief summary of what the package does

Breaks long line calls (chained methods or huge arg lists) into multi-line somewhat intelligently.

### Direct link to the package repository

https://github.com/ahungry/prog-fill

### Your association with the package

Owner

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, this looks good! Just one note: you must not [auto-enable](https://github.com/ahungry/prog-fill/blob/7e20b9636ec2247e54318dbac570062fb65c34c3/prog-fill.el#L140-L143) this package upon installation. That has to be the user's choice: like all the built-in Emacs packages, it should be possible for a user to have this installed but not activated.

**Comment by ahungry** [comment]
Sure, Ill update with a fix to the autoload snippet

**Comment by ahungry** [comment]
@purcell updated to remove the autoload key binding

**Comment by mattiasb** [comment]
This looks great!

One thing I (as a potential future user) would want is for the settings variables to use `defcustom` and `defgroup`. I find it much easier to customize a mode inside `M-x customize` than having to reach for my `init.el`. :)

**Comment by purcell** [comment]
Great - merged, thanks!

**Comment by ahungry** [comment]
@mattiasb thanks!  Updated to use defcustom over defvar

**Comment by mattiasb** [comment]
Yay! :)

**Pull request merged**
