### PR TITLE
Add recipe for cats

### PR DESCRIPTION
**Pull request by Fuco1**
### Brief summary of what the package does

This package implements various abstractions from Category Theory like functors, applicatives, monads, traversibles, foldables and so on. It is in a way an "extension" of libraries like seq or dash to arbitrary structures like trees or custom data types.

### Direct link to the package repository

https://github.com/Fuco1/emacs-cats

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- I see that there are some checkdoc issues that you probably left in deliberately.  Take a look at https://github.com/melpa/melpa/issues/8450, but I think at least one of those checkdocs points to an issue with the quoting of the docstring in `cats-fold-map`, which you can see syntax-highlighted here:
image

**Comment by riscy** [comment]
Just to followup, I'd suggest fixing as many of these checkdocs as is feasible -- the `Argument x should appear (as X) in the doc string` can be especially useful because these will create syntax highlighted help buffers.

**Comment by Fuco1** [comment]
@riscy I cleaned up the issues with the checkdoc, although I still think it's rather high noise to signal ratio documenting all the methods.

**Comment by minad** [comment]
FWIW I also think that checkdoc should be relaxed to not require method documentations. The point of generic functions is that we avoid some repetition. :)

**Comment by riscy** [comment]
I think the issue with the `cats-fold-map` docstring is still persisting -- the example needs its quotation marks escaped (see screenshot in https://github.com/melpa/melpa/pull/8458#issuecomment-1484187313).

Thank you for accommodating checkdoc.  As with anything we saw lots of contrasting opinions on the topic, but I do think it's within reason not to overcomment those defmethods.

**Comment by Fuco1** [comment]
Oh I couldn't figure out what the issue was from the error message, now I see it :D  Fixed and pushed.

**Comment by riscy** [comment]
Thanks!  All set here.  One last note I have is this:

- cats-data-maybe.el#L53: It's safer to sharp-quote function names; use `#'`

which could future-proof against name changes, if any.

**Pull request merged**
