### PR TITLE
Add flycheck-popup-tip recipe

### PR DESCRIPTION
**Pull request by Simplify**
### Brief summary of what the package does

Display Flycheck error messages using popup.el 

### Direct link to the package repository

https://github.com/flycheck/flycheck-popup-tip

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. You've got just a single minor mode, which intercepts `post-command-hook`. This means that every command in every buffer - whether or not that buffer uses flycheck - is going to have all its commands inspected. This is very inefficient, and I'd be surprised if it's the only way to make this work. Instead, you should be able to make a non-global minor mode which keeps state in buffer-local variables, and modifies `post-command-hook` buffer-locally rather than globally. (You can still easily make a global minor mode to enable it globally, by adding/removing your minor mode to `flycheck-mode-hook` when the global minor mode is enabled/disabled.)

**Comment by Simplify** [comment]
Hi @purcell, sorry for delay. I just changed code to implement non-global minor mode, makes more sense. Original minor-mode code came from `flycheck-pos-tip` that also implemented global minor-mode.

**Comment by purcell** [comment]
Okay, great, but also note my comment about only modifying hooks locally: you should pass the `LOCAL` flag when calling `add-hook` and `remove-hook`.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by Simplify** [comment]
@purcell , @tarsius , sorry about delay. Code is changed now to pass `local` flag when adding or removing hooks.

**Pull request merged**
