### PR TITLE
Add org-gamedb recipe

### PR DESCRIPTION
**Pull request by repelliuss**
### Brief summary of what the package does

A game API client for org-mode. It makes queries for certain resources like games, companies, characters, etc., extracts user defined properties, summary, image and inserts them in an org buffer. It uses [Giant Bomb's](https://www.giantbomb.com/) API.

### Direct link to the package repository

https://github.com/repelliuss/org-gamedb

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Just at a quick first pass, there's one small byte-compile warning:

byte-compile (using Emacs 27.1):
```
org-gamedb.el:286:1:Warning: Unused lexical variable `singular-root'
```

I think this is resolved by simplifying`org-gamedb--complement-resource` which leads to a simpler macroexpansion:
```elisp
(defun org-gamedb--complement-resource (resource)
  "Take a plural RESOURCE and return its singular endpoint."
  (pcase resource
    ((pred (string-match "people")) "person")
    ((and
      (pred (string-match "\\(.+\\)ies\\'"))
      (app (match-string 1) singular-root))
     (concat singular-root "y"))
    (plural (substring plural 0 (- (length plural) 1)))))
```

**Comment by repelliuss** [comment]
Sorry about that. I was compiling it fine on 28.0.5 fine but reproduced it on 27.2. Fixed it.

**Comment by riscy** [comment]
No problem. :)  This looks like a cool package.

My last comment is I wonder whether the summary in your top line could be improved tweaked.  "A game API client ..." doesn't feel too discoverable from a search perspective.  Maybe:
```
;;; org-gamedb.el --- Track video games in org-mode with giantbomb.com's API -mode -*- lexical-binding: t; -*-
```
and then if people search for giantbomb or game catalog in the MELPA index they'll arrive at your package.

I think this is not a blocker though, so I'll merge this.

**Comment by repelliuss** [comment]
It sure can be improved and I'll listen your advice.

I appreciate your time on this.

**Pull request merged**
