### PR TITLE
Add recipe for selcand.

### PR DESCRIPTION
**Pull request by erjoalgo**
### Brief summary of what the package does

A vimium-like emacs lisp utility for ergonomically selecting a lisp object by navigating a tree of hint characters.

### Direct link to the package repository

https://github.com/erjoalgo/selcand

### Your association with the package

Author, maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`selcand.el` with byte-compile using Emacs 28.1:
```
selcand.el:95:45: Warning: the function `string-join' is not known to be
    defined.
```
(I believe this needs a `(require 'subr-x)`)

`selcand.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- selcand.el#L117: It's safer to sharp-quote function names; use `#'`
```

I also notice your front-matter has a lot of empty entries (`Description:`, `Last-Updated:`, etc.).  A lot of these aren't necessary (package-lint will tell you) so you may as well omit them rather than have them blank.

**Comment by erjoalgo** [comment]
Sorry about that, it should be fixed:

https://github.com/erjoalgo/selcand/commit/247ffe0acda30c71896a173953119d127903ffbf
https://github.com/erjoalgo/selcand/commit/90332b7225e575943d2b7815becd1656d659155f
https://github.com/erjoalgo/selcand/commit/710eda3b2f0071e7d2c11f3db865c375e9d7989e

**Comment by riscy** [comment]
Thanks again for those fixes.

One more thing I notice now is that your License boilerplate has been placed inside your `;;; Commentary` - you should put your license boilerplate above your commentary so that it isn't a part of it.

That said -- and I may be missing something -- but how is a user intended to use this?  Neither of the two functions are defined as interactive, for instance, and the commentary lacks any entrypoint instructions.

**Comment by erjoalgo** [comment]
Thanks, updated commentary and added usage example:

```
;;; Commentary:
;; Like vimium, selcand-select enumerates a potentially large list
;; of candidates using very short hints that the user may type to
;; make a selection.
;; It is intended to be used from emacs lisp code to prompt the user
;; to select from a list of choices.
;; Sample usage: (switch-to-buffer (selcand-select (buffer-list)))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
```

**Comment by riscy** [comment]
Thank you *very* much for that example, that clarifies greatly.

(I wonder if another good example might be `(load-theme (selcand-select (custom-available-themes)))`, because `(switch-to-buffer (selcand-select (buffer-list)))` jarringly includes buffers that are usually hidden... just my subjective take.)

I would also recommend against the `;;;;;;;;;` embellishments in your front-matter, because you don't know how they will be parsed by downstream tools.  For example running `(lm-commentary)` on your buffer yields the string:
```elisp
;;; Commentary:
;; Like vimium, selcand-select enumerates a potentially large list
;; of candidates using very short hints that the user may type to
;; make a selection.
;; It is intended to be used from emacs lisp code to prompt the user
;; to select from a list of choices.
;; Sample usage: (switch-to-buffer (selcand-select (buffer-list)))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
```
which I think is approximately what will appear in the MELPA index, and here the horizontal `;` looks out of place.

No blockers though - merging!

**Comment by erjoalgo** [comment]
Incorporated your feedback. Thanks for merging.

**Pull request merged**
