### PR TITLE
Add recipe for modablist

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Modifiable tabulated-list extension.

### Direct link to the package repository

https://github.com/jcs-elpa/modablist

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
This looks interesting.  A few notes:

1.  The name is not very descriptive or readable.  How about `tabulated-list-editor` or something like that?
2.  The readme says:
> By the current implementation this package alone doesn't do much. You would probably need to extend this package and treat this as a library or framework.

That suggests to me that it's not ready for publishing on MELPA yet.  It sounds like it either needs to be extended and polished into such a library, or that it at least would need to be actually used by a package in MELPA.  MELPA already has library packages that are basically not used by anything and seem like abandonware, and I think it should try to avoid that.

**Comment by jcs090218** [comment]
> The name is not very descriptive or readable. How about tabulated-list-editor or something like that?

Hmm... I think the name is too long. I prefer shorter name! Thanks!

> That suggests to me that it's not ready for publishing on MELPA yet. It sounds like it either needs to be extended and polished into such a library, or that it at least would need to be actually used by a package in MELPA. 

May be or may not. I mean by just editing `tabulated-list` table does not do much (subjectively). But that's the goal of this package. I treat this package a module/layer for other further extend package; hence it's a library. I might call this package a framework because it has more restriction.

From my point of view, this package has the potential for better user experience. Maybe like editing `spreadsheet`, `watch list` or `memory stack trace`, etc. I know some package already has this kind of feature but it often gives user terrible experience; and again, subjectively, no offense.

Just to clarify, this is a mature library/framework for other package to extend on top of it, but it doesn't do much on it's own.

> MELPA already has library packages that are basically not used by anything and seem like abandonware, and I think it should try to avoid that.

I totally understand.

**Comment by riscy** [comment]
I haven't looked too closely yet but agree with @alphapapa's sentiment.  Maybe something has changed that caused you to reopen the PR?

If this doesn't do too much on its own, and it's only a couple months old, maybe we should wait on this.  The screencap looks awesome and it's a neat tech demo, but maybe you want to wait until you have an application built on top of this.

**Comment by riscy** [comment]
(I just realized you may have closed the PR to keep the number of them down; if so, thanks for that.)

**Comment by jcs090218** [comment]
Okay, I can close this now! I do have plan build the tool on top of this! Thanks! ;)

> (I just realized you may have closed the PR to keep the number of them down; if so, thanks for that.)

All good! From my point of view, I don't think by having PRs opened will pressure other people. But that doesn't apply to everyone. I can just close it and open it later on. I just like to have PRs open so I don't forget about it. Anyway, thanks for the review!

**Pull request closed without merging**
