### PR TITLE
recipes/apparmor-mode: update location to upstream apparmor project

### PR DESCRIPTION
**Pull request by alexmurray**
The old location of github.com/alexmurray/apparmor-mode is now frozen and future development will occur directly in the upstream apparmor project repo on gitlab.

### CODE REVIEW

**Comment by tarsius** [comment]
We generally recommend that the opposite be done -- that the elisp is move *out of* the repository for the bigger project for which it provides an interface. See #5361, where we track progress in that direction and justify that preference.

Please consider reverting this migration.

Links for our convenience:
- https://gitlab.com/apparmor/apparmor
- https://github.com/alexmurray/apparmor-mode
- If this move was discussed somewhere, please link to it.

**Comment by alexmurray** [comment]
Thanks for the review @tarsius - essentially the main reason to move it into the upstream apparmor project is for consistency with the apparmor.vim script (which also lives there) and to try and make maintenance of the mode easier to support the latest upstream features etc.

**Comment by tarsius** [comment]
It's of course your call. All I can say is that I see it as a step backward and that (of course without knowing the details in this particular case) I doubt that bundling will make it easier to support the latest upstream features in any significant way.

**Comment by riscy** [comment]
I definitely appreciate the ease of working inside one repository, but I should point out that users using e.g. straight.el or the builtin `package-vc-install`/`package-vc-upgrade` will have to pull and store the entire repository as well.  I'll echo @tarsius's sentiment though: it's your call and this repository doesn't appear overly massive.

Let us know what you decide.  Also, in the meantime, I can point out a couple small lints --

`apparmor-mode.el` with byte-compile using Emacs 29.4:
```
apparmor-mode.el:345:2: Error: Wrong type argument: proper-list-p, (beg . end)
```
This is because of the `cl-loop` embedded in this function; this error won't occur if you `(require 'cl-lib)` explicitly, since it may not always have been brought in when users are compiling.

**Comment by riscy** [comment]
Friendly ping :)

**Comment by alexmurray** [comment]
Based on your suggestions, I've instead created a new separate repo just for apparmor-mode under the main gitlab.com/apparmor project (https://gitlab.com/apparmor/apparmor-mode) which is essentially the same as the previous one under my personal github account - hopefully this is acceptable.

**Comment by tarsius** [comment]
> I've instead created a new separate repo just for apparmor-mode under the main gitlab.com/apparmor project

Perfect!

Don't forget to require `cl-lib`, and you should also update the link in the old repository on github.

**Comment by alexmurray** [comment]
Thanks @tarsius - old github README.md updated in https://github.com/alexmurray/apparmor-mode/commit/0e1b250228bdabc2cc6b8767cd5015fe3cc692e0 and explicit `cl-lib` require added in https://gitlab.com/apparmor/apparmor-mode/-/merge_requests/3 (along with a few other cleanups too).

**Comment by tarsius** [comment]
Cheers!

**Pull request merged**
