### PR TITLE
Corrected advice in getting-started.html

### LINKED ISSUE #8461: Proposed advice for package-compute-transaction does not fix the problem
In section *Dependency order is reversed* at

https://github.com/melpa/melpa/blob/6205f77bbb6c3a44146110f2a0e293cdf4280228/html/partials/getting-started.html#L137

A piece of advice is shown, which is supposed to fix a problem with `package-compute-transaction` in Emacs 24.

With multiple dependencies, this advice does not work correctly. With the following advice, the dependency order comes out exactly as in later versions of package.el:

```elisp
  (defadvice package-compute-transaction
      (around package-compute-transaction-fix activate)
    "Fix order of requirements."
    (let ((package-list (ad-get-arg 0)))
      (let (package-list)
        (ad-set-args 0 (list nil  (ad-get-arg 1)))
        ad-do-it)
      (dolist (elt (nreverse ad-return-value))
        (setq package-list (cons elt (delq elt package-list))))
      (setq ad-return-value package-list))))
```

BTW,  that is not the only problem with old Emacsen. In pursuing the goal to have a single `package-user-dir` with byte code in version sub-directories for all the versions of Emacs that I still encounter during Administration (23.4, 24.3, 24.5, 25.2, 26.3, 27.1)  I found quite some issues that can be fully back-ported with defadvice and a couple of compatibility definitions . See [package-compat](https://almost-un.org/selpa/#/package-compat).

### PR DESCRIPTION
**Pull request by wolfmanx**
Fixes #8461

### CODE REVIEW

**Comment by riscy** [comment]
For what it's worth, these changes look correct to me. :)

**Comment by wolfmanx** [comment]
If you actually want to check, this might be helpful:

``` elisp
(defun package-compat-check-deps ()
  "Check dependency computation of `package-compute-transaction'."
  (let ((package--initialized t)
        (archive-contents
         '((abc-mode . [(20220713 1359) nil "" single])
           (cask-package-toolset . [(20170921 2256)
                                    ((emacs) (cl-lib) (s) (dash) (f)
                                     (commander) (ansi) (shut-up))
                                    "" tar])
           (s . [(20220902 1511) nil "" single])
           (dash . [(20230304 2223) ((emacs)) "" tar])
           (f . [(20230116 1032) ((emacs) (s) (dash)) "" tar])
           (commander . [(20140120 1852) ((s) (dash) (cl-lib) (f)) "" single])
           (ansi . [(20230306 1823) ((emacs) (cl-lib)) "" single])
           (shut-up . [(20210403 1249) ((cl-lib) (emacs)) "" single])
           (cl-lib . [(0 7 1) nil "" tar])))
        (arc "melpa")
        package-archive-contents)
    (dolist (pkg archive-contents) (package--add-to-archive-contents pkg arc))
    (let ((package-alist (list (assq 'abc-mode package-archive-contents)))
          (package--builtins (delq nil (list (assq 'emacs package--builtins))))
          (package--builtin-versions
           (and (boundp 'package--builtin-versions)
                (list (assq 'emacs package--builtin-versions))))
          deps)
      (setq deps
            (package-compute-transaction
             () (list (list 'cask-package-toolset))))
      (if (fboundp 'package-desc-name)
          (setq deps (mapcar #'package-desc-name deps)))
      deps)))

;; no advice 24.5, 25.2, 26.3, 27.1
;; '(cl-lib shut-up ansi dash s f commander cask-package-toolset)

;; no advice 23.4, 24.3
;; '(shut-up ansi commander f dash s cl-lib cask-package-toolset)

;; advised 23.4, 24.3
;; '(cl-lib shut-up ansi dash s f commander cask-package-toolset)
```

**Comment by tarsius** [comment]
> If you actually want to check, this might be helpful:

Thanks! I don't really want to install Cask, but I think it is safe to assume that you ran this test after writing it, so that is good enough for me. :grin:

**Comment by tarsius** [comment]
The reason I didn't merge this as soon as I saw it, is actually meta.

@riscy I assume you "merge" using `Squash and merge` but ...

Hm, when I began that process two days ago, it behaved differently than I remember it behaving and how it behaves now. That probably was a quickly reverted change in behavior on Github's part. What I saw after pressing that button but before confirming, strongly suggested that the commit would be attributed to me, and Wolfgang's contribution would only be acknowledged using a Git pseudo header (Co-authored or something like that).

That didn't seem right. Luckily they seem to have quickly realized that too. Or are you familiar with this kind of outcome? Personally I detest all "merge" methods provided by Github and never use it in my own repositories, so I don't have much experience with them.

**Comment by tarsius** [comment]
> Personally I detest all "merge" methods provided by Github

When it is actually possible to fast-forward, then I would like to use the missing `merge by doing a fast-forward` button. :roll_eyes:

The advantage of their "merge" methods is that they can sign it using their "any user who successfully logged in to Github" key (https://github.com/web-flow.gpg).

The disadvantage is that no tool except for Github itself can tell that the pull-request is merged. The associated `refs/pull/N/head` is not modified when you "merge" using Github, so any tool that limits itself to Git and ignores the Github API, won't know whether the pull-request is merged or not. :scream: 

I can't help but be cynical about that. If they at least allowed fast-forwards, then the story would be different. Better yet, they could show whether the tip of the pr ref has a valid signature, in which case `rebase and merge`, so that I could stay a way from that if it only had disadvantages.

Ps: I've very recently started to try harder to sign my locally created commits to this repository. A few unsigned commits will likely continue to slip through, but fewer than before.

**Comment by riscy** [comment]
> @riscy I assume you "merge" using Squash and merge but ...

That's exactly what I use.  I almost always edit out the "co-authored by" part that GitHub helpfully fills in.  It's almost always noise.

**Pull request merged**
