### PR TITLE
Add flycheck-aspell and flymake-aspell packages.

### PR DESCRIPTION
**Pull request by tychoish**
### Brief summary of what the package does

Provides integration between apell and flycheck/flymake
respectively. Specified as seperate packages.

### Direct link to the package repository

https://github.com/your/awesome_package

### Your association with the package

I am just a happy user, and have coordinated this with the package
maintainer [here](https://github.com/leotaku/flycheck-aspell/issues/7).

### Relevant communications with the upstream package maintainer

None needed. 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks a lot for taking these all on -- it's appreciated.

Typically README's are automatically excluded when distributing the packages, so unless there's a good reason for them to be included we should drop those from the recipe.

In both recipes we have:
```
8:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```
but this is one of the minor package-lint warnings.  It could potentially be resolved by adding e.g. `wp` to the list of keywords (as in `(wp . "word processing")`), but not a blocker.  After we sort out the READMEs this is an easy merge.

**Comment by tychoish** [comment]
I've pushed the fixes to remove the README. As I'm not the maintainer of the package, getting a change in to change the keyworkds may take slightly longer, but I'll see what I can do.

**Comment by tychoish** [comment]
The keyword fix was merged into master.

**Comment by tychoish** [comment]
Is there anything more I need to do on this?

**Comment by riscy** [comment]
All good.  Thanks!

**Pull request merged**
