### PR TITLE
Move base16-emacs to new location

### PR DESCRIPTION
**Pull request by belak**
**What the package does:** base16-theme is a collection of themes which are generated from sets of 16 colors.

**Package repository:** https://github.com/belak/base16-emacs

**Package association:** I am the new maintainer.

I recently took over the base16-emacs project. I'm moving the theme files into a separate directory, so I figured now would be a good time to make sure the repo location is updated as well.

I have tested `make recipes/base16-theme` and `package-install-file` to ensure this package still works as designed.

### CODE REVIEW

**Comment by belak** [comment]
Ah, I see, it errors... what would the best way be to resolve this? Should it just be broken for a little bit?

**Comment by belak** [comment]
I put the only copy of the theme files in the root and I'll move them after this gets merged.

**Comment by belak** [comment]
I've updated the PR description with all relevant information as specified in CONTRIBUTING.md.

**Comment by purcell** [comment]
Thanks! Do you plan to submit a subsequent PR removing the `"*.el"` pattern?

**Comment by purcell** [comment]
(Or perhaps you're going to keep the `base16-theme-pkg.el` file in the root... in which case you should use `:defaults` instead of `"*.el"` please.)

**Comment by belak** [comment]
The idea was that `base16-theme.el` would stay in the root (because that defines the important part) and all the schemes would go in build so you can see the important stuff. There's nothing in build right now because I didn't want to break the package while the migration was happening.

What does `:defaults` actually do? I think, because of the separate build dir, that wouldn't work though

**Comment by belak** [comment]
So, would it be `(base16-theme :repo "belak/base16-emacs" :fetcher github :files (:defaults "build/*.el"))`?

**Comment by purcell** [comment]
> The idea was that base16-theme.el would stay in the root (because that defines the important part) and all the schemes would go in build so you can see the important stuff. There's nothing in build right now because I didn't want to break the package while the migration was happening.

:+1:


> What does :defaults actually do? I think, because of the separate build dir, that wouldn't work.

It expands to `*.el`, plus some other stuff, and excludes test files.


> So, would it be (base16-theme :repo "belak/base16-emacs" :fetcher github :files (:defaults "build/*.el"))?

Yeah, exactly!

**Pull request merged**
