### PR TITLE
Add recipe for `magit-gitlab`

### PR DESCRIPTION
**Pull request by arvidj**
### Brief summary of what the package does

A magit extension for working with GitLab merge requests.

### Direct link to the package repository

https://gitlab.com/arvidnl/magit-gitlab

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings

yes, within reason, but I have not documented all internal variables and functions.

- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`magit-gitlab.el` with package-lint 20240507.1722:
```
37 issues found:
33:0: error: "mg-favorite-users" doesn't start with package's prefix "magit-gitlab".
(etc)
```
In my opinion you should use `read-symbol-shorthands` sparingly (and only with Emacs>28).  This is not such a long package name for which users or developers will frequently manually be typing `magit-gitlab-` in full.

- magit-gitlab.el#L305: It's safer to sharp-quote function names; use `#'`
- magit-gitlab.el#L308: It's safer to sharp-quote function names; use `#'`
- magit-gitlab.el#L465: It's safer to sharp-quote function names; use `#'`
- magit-gitlab.el#L101: Use `(temporary-file-directory)` instead of /tmp in code

Package and license:
- Unreachable package URL in magit-gitlab.el front matter: https://gitlab.com/arvidnl/magit-gitlab.el
- magit-gitlab.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by arvidj** [comment]
Thanks for your swift and careful review.

> Thanks for this. Quick first pass --
> 
> `magit-gitlab.el` with package-lint 20240507.1722:
> 
> ```
> 37 issues found:
> 33:0: error: "mg-favorite-users" doesn't start with package's prefix "magit-gitlab".
> (etc)
> ```
> 
> In my opinion you should use `read-symbol-shorthands` sparingly (and only with Emacs>28). This is not such a long package name for which users or developers will frequently manually be typing `magit-gitlab-` in full.

Okay, done.

>     * magit-gitlab.el#L305: It's safer to sharp-quote function names; use `#'`
> 
>     * magit-gitlab.el#L308: It's safer to sharp-quote function names; use `#'`
> 
>     * magit-gitlab.el#L465: It's safer to sharp-quote function names; use `#'`

Added sharp quotes.

>     * magit-gitlab.el#L101: Use `(temporary-file-directory)` instead of /tmp in code
> 

Removed this variable since it was unused.

> Package and license:
> 
>     * Unreachable package URL in magit-gitlab.el front matter: https://gitlab.com/arvidnl/magit-gitlab.el
> 
>     * magit-gitlab.el needs _formal_ license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

Fixed URL and added license boilerplate and SPDX-License-Identifier.

**Comment by riscy** [comment]
Thank you, looks solid. And, welcome to MELPA :)

**Comment by arvidj** [comment]
> Thank you, looks solid. And, welcome to MELPA :)

Thanks!

**Pull request merged**
