### PR TITLE
Add esonify recipe

### PR DESCRIPTION
**Pull request by oflatt**
### Brief summary of what the package does
An emacs extension that sonifies your code. Skilled users will begin to be able to recognize some code based solely upon the music it generates. Hear sine waves at different frequencies for lowercase letters, square waves for uppercase letters, and triangle waves for keybindings.

### Direct link to the package repository

https://github.com/oflatt/esonify

### Your association with the package

creator/maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
Well...that sounds interesting...it's just begging for a demonstration video, though.  :)

**Comment by oflatt** [comment]
Here is a demonstration video.
Audio quality is a bit poor because the recording buffers didn't seem to deal with all the new sounds very well.
<https://www.youtube.com/watch?v=fwBh6FKxzcQ>

**Comment by oflatt** [comment]
esonify now has more documentation and customizable variables.

**Comment by purcell** [comment]
Thanks! Some notes:

- In the recipe, `"*.el"` should be `:defaults`.
- `alphabethash.el` should be named `esonify-alphabethash.el`, if it's even needed -- it looks like the data is already in `esonify.el`
- There's no `defgroup` for the `esonify` customisation group: you should add one, to place it appropriately in the custom hierarchy.
- [This line](https://github.com/oflatt/esonify/blob/7cfea844f61090888c662b4c6fa1adc0713ab637/esonify.el#L42) seems hokey and unnecessary: you can just `(require 'esonify-sound-wav)` if you need it, however...
- `esonify-sound-wav` appears to be a "rebadged" `sound-wav.el`, which looks like an upstream library. It should be relied on directly, and published separately if necessary.
- [Here](https://github.com/oflatt/esonify/blob/master/esonify.el#L110-L119) there's no need to convert the symbol to a string -- just compare symbols, e.g. (eq last-command-event 'up)`. `pcase` is a neat way of writing these expressions, btw.

Hope that helps - shout out if you have questions.

**Comment by oflatt** [comment]
Thank you for all of the advice.

About sound-wav.el- the reason I rebadged sound-wav.el is that, for my purposes, I would like it to use Play() instead of PlaySync() for playing through .net on windows. However, I am not sure this is best for sound-wav.el in general. I have tried to contact the maintainer of sound-wav and submitted an issue.

What's the best thing to do in this situation, in your opinion?

**Comment by oflatt** [comment]
A bit confused about require in elisp- I'm getting
File error: Cannot open load file, No such file or directory, esonify-sound-wav
When trying to replace the line with (require 'esonify-sound-wav)

**Comment by purcell** [comment]
> About sound-wav.el- the reason I rebadged sound-wav.el is that, for my purposes, I would like it to use Play() instead of PlaySync() for playing through .net on windows. However, I am not sure this is best for sound-wav.el in general. I have tried to contact the maintainer of sound-wav and submitted an issue.
> 
> What's the best thing to do in this situation, in your opinion? You said, "published separately if necessary." What does this entail? Another pull request to melpa?

Ah, I see https://github.com/syohex/emacs-sound-wav/issues/6 -- perhaps now that you've got your own patched version, you can submit a pull request to @syohex, and then simply depend on the `sound-wav` package.

If for some reason that's really not possible, then you could include `esonify-sound-wav.el` in the recipe, but you'd need to change all the `sound-wav-*` symbols to be `esonify-sound-wav-`. The first solution would be greatly preferable for everyone, I think.


> A bit confused about require in elisp- I'm getting
> File error: Cannot open load file, No such file or directory, esonify-sound-wav
> When trying to replace the line with (require 'esonify-sound-wav

If you're trying this locally, then yes, this will happen: you'd need to `M-: (push default-directory load-path)` to put the current directory on `load-path`, as would be the case when installed as a package. But also note that you won't be able to `require` the file unless its `provide` form provides a feature with a matching name, which isn't yet the case, as above.

**Comment by oflatt** [comment]
For now, I did the esonify-sound-wav.el solution.
I also submitted the pull request on emacs-sound-wav.

**Comment by purcell** [comment]
> For now, I did the esonify-sound-wav.el solution.

Makes sense. MELPA doesn't pull together package dependencies from all the files, only from the main file (esonify.el), so you'll also need to include the `deferred` and `cl-lib` dependencies for `esonify-sound-wav.el` in the `Package-Requires` line of `esonify.el`. Then I think we'll be good to go. :-)

**Comment by oflatt** [comment]
Done.

**Comment by oflatt** [comment]
Are we waiting on something to merge, or are we good to go?

**Comment by purcell** [comment]
> Are we waiting on something to merge, or are we good to go?

There's still no `defgroup` as mentioned above, and the `defcustom` vars are (by definition) public, and so should use the `esonify-` prefix, not `esonify--`. Other than that, all looks good.

**Comment by oflatt** [comment]
Sorry I missed that one, esonify now has a defgroup.
Thanks for the help.

**Comment by purcell** [comment]
Sweet, merged now - thanks!

**Comment by alphapapa** [comment]
@oflatt You might find this helpful when testing: https://github.com/alphapapa/emacs-package-dev-handbook#byte-compile-and-load-directory

**Pull request merged**
