### PR TITLE
Add recipe for Casual Avy

### PR DESCRIPTION
**Pull request by kickingvegas**
### Brief summary of what the package does

Casual Avy is a Transient menu for [Avy](https://github.com/abo-abo/avy).

### Direct link to the package repository

https://github.com/kickingvegas/casual-avy

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

> will require the following Elisp to be evaluated before running package-lint

Yes but that sort of defeats the purpose. :)    It may feel inconvenient, but a simple and fair way to prevent namespace collisions across MELPA (and hopefully elsewhere) is to ask that the package, variable names, and function names all use the same prefix.  In very rare cases I would make exceptions to this rule (e.g. backward compatibility with a package predating this rule) -- and `package-lint` has some of these exceptions built into it.

**Comment by kickingvegas** [comment]
@riscy Understood. Will remove the shorthand.

**Comment by tarsius** [comment]
You might want to look into using the `shorthands` package (part of Emacs).

**Comment by kickingvegas** [comment]
@riscy Have updated Casual Avy with requested change for release v1.0.3. Please re-review for MELPA distribution.

https://github.com/kickingvegas/casual-avy/releases/tag/1.0.3

Thanks!

**Comment by riscy** [comment]
Thank you for that reminder, @tarsius - I've added a note about `shorthands` to my canned advice when this one comes up.

@kickingvegas This looks great now, and thank you for accommodating.

**Comment by kickingvegas** [comment]
@tarsius Does your comment suggest that there is a way to use shorthands in a MELPA package? Or was that directed at @riscy as an fyi?

**Comment by riscy** [comment]
Shorthands in elisp: https://www.gnu.org/software/emacs/manual/html_node/elisp/Shorthands.html

**Comment by kickingvegas** [comment]
@riscy to clarify, I used (or at least thought I did) the guidance for shorthands as shown in the link. I found that this practice does not pass `package-lint-current-buffer` by default. Further investigation found this ticket https://github.com/purcell/package-lint/issues/238 which provided a work-around configuration.

Regardless, my take-away is that shorthands are not allowed in MELPA packages. I'm asking though if that is really true or is there a way to use shorthands that would not require configuration of `package-lint`?

**Pull request merged**
