### PR TITLE
Added new package recipe for  `Counsel-fd`

### PR DESCRIPTION
**Pull request by CsBigDataHub**
### Brief summary of what the package does

counsel interface for [fd](https://github.com/sharkdp/fd).

### Direct link to the package repository

https://github.com/CsBigDataHub/counsel-fd

### Your association with the package

I am a maintainer

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- a quick pass through the checklist:

### counsel-fd.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
```
counsel-fd.el:32:1:Error: Cannot open load file: No such file or directory, counsel
```
I believe the `Package-Requires` line needs `counsel` added as well to resolve this.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191220.419):
```
1 issue found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
```

<details><summary>Misc...</summary>

### Maintainer/license

- PR by CsBigDataHub: https://github.com/CsBigDataHub/counsel-fd
- License found (through API): 'GNU General Public License v3.0' (good)
- LICENSE excerpt: 'GNU GENERAL PUBLIC LICENSE...'
- License appears to be written into individual files

### Possibly related
- https://melpa.org/#/counsel
- https://melpa.org/#/counsel-bbdb
- https://melpa.org/#/counsel-codesearch
- https://melpa.org/#/counsel-css
- https://melpa.org/#/counsel-dash

### Summary

- (counsel-fd :repo "CsBigDataHub/counsel-fd" :fetcher github)
- Package-Requires: emacs "24.4"
- _elisp/counsel-fd.el (gpl): counsel interface for fd
</details>

**Comment by CsBigDataHub** [comment]
@riscy , Just curious - what would the typical duration after creating a pull request the package would be available in Melpa?

**Comment by riscy** [comment]
That's super hard to answer.  It depends. :)  Maybe I can help a bit by describing what can slow things down when I'm reviewing.

If the checklist isn't met, then I'll ask the submitter to double-check and/or clarify why they need any exception(s), and that could mean they have to wait until the next weekend before I look again.  Various checklist items may raise false positives, but if you can work around them and present an immaculate checklist, then you're also demonstrating (to me) the intention to be a good maintainer.

If there are issues with the recipe (e.g., it includes files that aren't needed, or a small change to the upstream repo could enable us to use the "default" recipe, which is preferred), or the license (maybe there's a permissive GPL-3-compatible license but it's too informal), but that stuff is part of the checklist.

If it is difficult to tell what the package does, that can slow things down.  This might not be the package maintainer's fault, but my own fault for not being familiar with how some part of Emacs or some ecosystem of Emacs works, but the easier you can make it for me, the better.

If the package bears a resemblance to other Emacs/MELPA packages, either in name or functionality, and its novelty isn't clear, that can slow things down.

I also try to understand/use the code when feasible.  If the code has a function that's 100 lines long in it, or is obfuscated beneath macros that aren't familiar to me, then I have to admit that sometimes my brain will just give up and I'll put the package away for when I have more energy.

**Comment by CsBigDataHub** [comment]
> That's super hard to answer. It depends. :) Maybe I can help a bit by describing what can slow things down when I'm reviewing.
> 
> If the checklist isn't met, then I'll ask the submitter to double-check and/or clarify why they need any exception(s), and that could mean they have to wait until the next weekend before I look again. Various checklist items may raise false positives, but if you can work around them and present an immaculate checklist, then you're also demonstrating (to me) the intention to be a good maintainer.
> 
> If there are issues with the recipe (e.g., it includes files that aren't needed, or a small change to the upstream repo could enable us to use the "default" recipe, which is preferred), or the license (maybe there's a permissive GPL-3-compatible license but it's too informal), but that stuff is part of the checklist.
> 
> If it is difficult to tell what the package does, that can slow things down. This might not be the package maintainer's fault, but my own fault for not being familiar with how some part of Emacs or some ecosystem of Emacs works, but the easier you can make it for me, the better.
> 
> If the package bears a resemblance to other Emacs/MELPA packages, either in name or functionality, and its novelty isn't clear, that can slow things down.
> 
> I also try to understand/use the code when feasible. If the code has a function that's 100 lines long in it, or is obfuscated beneath macros that aren't familiar to me, then I have to admit that sometimes my brain will just give up and I'll put the package away for when I have more energy.

Thanks for the reply and thanks for all the hard work all the maintainers put in to Melpa.

**Comment by riscy** [comment]
Thanks for saying so.  :) Feel free to ping when you're ready for another pass!

**Comment by CsBigDataHub** [comment]
> Thanks for saying so. :) Feel free to ping when you're ready for another pass!

@riscy , Sorry I did not get you. What do you mean by "another pass" ?

 Is there something wrong with the code and you want me look in to it?

**Comment by purcell** [comment]
> Is there something wrong with the code and you want me look in to it?

Yes, there was feedback in the initial response from @riscy, including that you need to declare a package dependency on `counsel`.

**Comment by purcell** [comment]
Couple of other quick notes:

* Your quoting is unsafe [here](https://github.com/CsBigDataHub/counsel-fd/blob/470ed50f36bde6418fd83bc813294ec060eb2ec8/counsel-fd.el#L47) - use `shell-quote-argument`, not just `concat` with quote characters
* Similarly, long string commands are generally a bad idea. Consider using a list for the command [here](https://github.com/CsBigDataHub/counsel-fd/blob/470ed50f36bde6418fd83bc813294ec060eb2ec8/counsel-fd.el#L34), and only joining the piees when you want to actually execute the command. The various clunky `(car (split-string counsel-fd-base-command)` are a sign of this being a good idea.
* You need to declare `counsel-fd-current-dir` formally. You're assigning it with `setq`.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by CsBigDataHub** [comment]
> Friendly ping!

@tarsius , Code has been updated. Sorry for the delay have been bit busy at work.

**Comment by riscy** [comment]
It looks like you still need to declare a `Package-Requires` on counsel -- this is a line like:
```elisp
;; Package-Requires: ((counsel "0.13.0"))
```
in your front matter.

I think the rest of the comments above have been addressed!

**Comment by CsBigDataHub** [comment]
Sorry, I have missed it. Updated accordingly.

**Comment by tarsius** [comment]
Please fix that according to my comments at https://github.com/CsBigDataHub/counsel-fd/commit/9553f45ebb654d834337f80752ca0e19deeb8cd2.

**Comment by CsBigDataHub** [comment]
> Please fix that according to my comments at [CsBigDataHub/counsel-fd@9553f45](https://github.com/CsBigDataHub/counsel-fd/commit/9553f45ebb654d834337f80752ca0e19deeb8cd2).

This has been fixed

**Pull request merged**
