### PR TITLE
Add recipe for neut-mode

### PR DESCRIPTION
**Pull request by vekatze**
### Brief summary of what the package does

`neut-mode` is a major mode for the [Neut](https://vekatze.github.io/neut/) programming language.
This mode supports syntax highlighting, automatic indentation, and LSP integration.

### Direct link to the package repository

https://github.com/vekatze/neut-mode

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`neut-mode.el` with byte-compile using Emacs 29.2:
```
neut-mode.el:434:17: Warning: reference to free variable `lsp-language-id-configuration'
neut-mode.el:434:17: Warning: assignment to free variable `lsp-language-id-configuration'
In end of data:
neut-mode.el:437:22: Warning: the function `lsp-stdio-connection' is not known to be defined.
neut-mode.el:436:5: Warning: the function `make-lsp-client' is not known to be defined.
neut-mode.el:435:4: Warning: the function `lsp-register-client' is not known to be defined.
```

`neut-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- neut-mode.el#L242: Could this point/line-beginning-position comparison use `bolp`?
- neut-mode.el#L337: Could this point/line-beginning-position comparison use `bolp`?
- neut-mode.el#L76: Consider `beginning-of-line`
- neut-mode.el#L182: Consider `beginning-of-line`
- neut-mode.el#L321: Consider `beginning-of-line`
- neut-mode.el#L66: Consider `end-of-line`
```

Package and license:
- neut-mode.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by vekatze** [comment]
@riscy 

Thank you for your review. I've fixed all of the warnings and ensured that the following runs cleanly:

```
git clone https://github.com/riscy/melpazoid
cd melpazoid
MELPA_PR_URL=https://github.com/melpa/melpa/pull/8987 make
```

Could you please check this PR again?

**Comment by riscy** [comment]
Thanks for running melpazoid on this!  I'm reminded there's several updates I need to get pushed onto the main branch...

In any case, this looks good.  One comment I have is that you seem to be using back/front quotes (``` ` ``` and `'`) as generic highlighters, but they actually do something special in Emacs - they create hyperlinks in the help to other functions and variables.   So for example your docstring for `neut--genuine-closing-angle-p` creates hyperlinks to the unrelated `<` and `->` (if one has dash installed) functions:
image

Similarly with `neut--make-hash-table` - you don't need to quote CHARS in its docstring because that isn't (usually) a function.  Simply capitalizing CHARS is enough for the Emacs online help to figure out that it's a special reference to a variable like so:
image

**Comment by vekatze** [comment]
Thank you! I'll update docstrings soon.

**Pull request merged**
