### PR TITLE
Add recipe for mybuild-mode

### PR DESCRIPTION
**Pull request by easimonenko**
### Brief summary of what the package does

_mybuild-mode_ -- major mode for GNU Emacs for Mybuild files from [Embox](https://embox.github.io/) operating system.

_mybuild-mode_ supports:
- syntax highlighting;
- proper indentations.

### Direct link to the package repository

https://github.com/easimonenko/mybuild-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Quick first pass --

- mybuild-mode.el#L57: Top-level `setq` should usually be replaced by `defvar` (in this case you should likely be combining the two forms around `mybuild-highlights`)
- You do not need to `defvar mybuild-mode-hook`; such a hook is already automatically created for you when you use the `define-derived-mode` macro
- You also don't need to invoke `(use-local-map mybuild-mode-map)`; this map should automatically be used because you've given it the conventional name
- Note rather than `(set-syntax-table mybuild-mode-syntax-table)`, `define-derived-mode` takes a keyword entry, e.g.
 ```elisp
;;;###autoload
(define-derived-mode mybuild-mode c-mode "Mybuild"
  "Major mode for Mybuild files.
\\{mybuild-mode-map}"  ; this'll neatly document the keybindings
  :syntax-table mybuild-mode-syntax-table
  (setq-local comment-start ...
  ```
- You may want to add `;;;###autoload` cookies to `mybuild-mode` and your `(add-to-list ...` which is the usual convention around major modes
- Very minor, but you write `setq font-lock-defaults` whereas the preceding forms use `setq-local`; every single one of these variables is buffer-local, so for consistency it may make sense to also write `(setq-local font-lock-defaults '(mybuild-highlights))`
- Also minor, but a major mode doesn't need to document itself as `GNU Emacs major mode for ...` -- this is sort of implied.  You could just write `Major mode for ...`

**Comment by easimonenko** [comment]
@riscy Thank you for your useful comments! I will make corrections a little later.

**Comment by riscy** [comment]
In fact `define-derived-mode` will even take care of running the hooks for you, so the line `(run-hooks 'mybuild-mode-hook)` isn't necessary (and in fact might be harmful if hooks are run two times).

Other than that, this looks like an easy merge.

**Comment by easimonenko** [comment]
@riscy Thanks! Done: https://github.com/easimonenko/mybuild-mode/commit/879117b965a593b47432208e388e852223adcc88

**Comment by easimonenko** [comment]
@riscy Thanks!

**Pull request merged**
