### PR TITLE
Add recipes for islisp-mode and inferior-islisp

### PR DESCRIPTION
**Pull request by Sasanidas**
### Brief summary of what the package does

It's a major mode and inferior mode for the [ISLisp programming language](https://en.wikipedia.org/wiki/ISLISP).

It also include some "advance" and non enable by default features (such as etags integration).

### Direct link to the package repository

https://gitlab.com/sasanidas/islisp-mode

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by lassik** [comment]
@Sasanidas Thanks for the quick work!

Should we split `inferior-islisp` into its own package? (Can still be in the same git repo.)

**Comment by Sasanidas** [comment]
> Should we split `inferior-islisp` into its own package? (Can still be in the same git repo.)

I'm not sure if it make sense to have a separate package, there are some example on both directions in MELPA, in this case, I think both the major mode and the repl (giving that is a small REPL) can go together.
But If it is a requirement, I can make it work :+1:

**Comment by lassik** [comment]
> having two packages would let you adhere to the prefix rules package-lint nags about

Indeed. I'd vote for this since the package-name-to-symbol-name mapping is more consistent and predictable. ISLisp mode is also useful without inferior-islisp. The git repo can stay as it is; just need two recipe files for MELPA to specify which files go in each package.

**Comment by lassik** [comment]
Dylan and DIME (Dylan IDE) were recently split into two packages in a similar way.

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to reach out.

**Comment by Sasanidas** [comment]
I separate the main major mode from the inferior, the inferior depends on the major mode but not the other way around.

Let me know if I made some mistakes @riscy , thanks for the lint check.

**Comment by lassik** [comment]
Please convert tabs to spaces. Otherwise looks good to me.

**Comment by riscy** [comment]
No problem @Sasanidas!  Thanks for being accommodating with respect to the prefixes and splitting up the package.

For `islisp-mode` here's a quick checklist check:

### islisp-tags.el ###

byte-compile (using Emacs 27.1):
```
islisp-tags.el:92:15:Warning: reference to free variable
    `easy-islisp-library-directory'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
islisp-tags.el:57: All variables and subroutines might as well have a documentation string
Warning (emacs): 
islisp-tags.el:92: All variables and subroutines might as well have a documentation string
Warning (emacs): 
islisp-tags.el:94: Error messages should *not* end with a period
```

package-lint (using version 20210528.2348):
```
1 issue found:
11:0: error: Package-Requires outside the main file have no effect.
```

And a couple comments about the keybindings:
- Correct me if I'm wrong but islisp-mode.el looks like it's creating bindings over C-c g and C-c w, which are reserved (see Key Binding Conventions in the Emacs Lisp manual).  You can always suggest these to a user in your Commentary, but you should let them set those particular keybindings themselves
- There is a similar set of keybindings in islisp-tags.el -- these ones aren't reserved but they are defined at the top level, which can sometimes lead to overwriting user bindings.  For example imagine a user config that requires islisp-mode.el, customizes islisp-mode-map with a `(kbd "C-c C-w")` keybinding, and then sets `islisp-advance-features` to true; they'll lose their keybindings.  I recommend playing it safe, either by not having an "advanced" mode (advanced mode doesn't seem much more complicated) or by checking whether you're overwriting user bindings using `(lookup-key islisp-mode-map ...)`


### inferior-islisp.el ###

I think this has the same issue as above regarding overwriting keybindings at load time.  Setting the keybindings of an outside-package major mode at load time is also a little unusual, but since both are yours and they're tied together I wouldn't insist.

**Comment by riscy** [comment]
I'll mark this awaiting-upstream in the meantime, but feel free to reach out with any questions!

**Comment by Sasanidas** [comment]
I'm so sorry! 

Completely forgot about this issue :face_with_spiral_eyes: , I've add a function to check IF the keybinding is defined in the keymap before setting it a new value.

Some minor errors are also fixed now.

Ping @riscy to give it a go, and thanks! :)

**Comment by riscy** [comment]
Thanks!  I think the keybinding issues are behind us -- here's the latest checks:

`islisp-mode.el` with byte-compile using Emacs 27.1:
```
islisp-mode.el:267:21:Warning: reference to free variable
    `inferior-islisp-buffer'
In end of data:
islisp-mode.el:297:1:Warning: the function `inferior-islisp' is not known to
    be defined.
```

`islisp-mode.el` with checkdoc 0.6.2:
```
islisp-mode.el:61: All variables and subroutines might as well have a documentation string
```

- islisp-mode.el#L289: I'm just noticing this, but advice should usually be added using named functions rather than lambdas, since it's cumbersome to remove advice defined by anonymous functions

**Comment by Sasanidas** [comment]
OK I think I fix the documentation string and the lambda function, there was also a bug in the way that I was defining multiple keys.

Regarding the free variable warning, I think it's fine, giving that I'm requiring the package before using these variables (so they are going to be define at that time).

Thanks for taking a look @riscy :+1:

**Comment by riscy** [comment]
> Regarding the free variable warning, I think it's fine, giving that I'm requiring the package before using these variables (so they are going to be define at that time).

I see what's going on, the `require` is inlined and the two packages are loosely entwined.  Here's a couple suggestions:

-  Replace the `require` with something like `(unless (require 'inferior-islisp nil t) (user-error "Package inferior-islisp must be installed"))` to give users a clear message instead of a backtrace
- Pacify the byte-compiler by adding a `defvar` and a `declare-function` for the variable/function respectively

These are relatively minor but I think should be easy fixes -- ping me if you've got any questions. :)

**Comment by riscy** [comment]
Marked awaiting-upstream for now, but feel free to reach out.

**Comment by Sasanidas** [comment]
Sorry about the delay, I added your suggestions :+1:  (@riscy )

**Comment by riscy** [comment]
No problem!  It has been a while so I've lost a bit of context, but here's the latest:

`islisp-mode.el` with checkdoc 0.6.2:
```
islisp-mode.el:281: First sentence should end with punctuation
```

`islisp-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- islisp-mode.el#L74: It's safer to sharp-quote function names; use `#'`
- islisp-mode.el#L300: It's safer to sharp-quote function names; use `#'`
- islisp-mode.el#L74: Prefer one blank line between this top-level form and the next
- islisp-mode.el#L162: Prefer one blank line between this top-level form and the next
- islisp-mode.el#L302: Prefer one blank line between this top-level form and the next
- islisp-mode.el#L300: Loading a package should rarely add advice
```

The advice nag on line 300 is definitely worth checking out -- advice is usually for when you have no other choice (e.g. there is no hook, and you can't change the code). But in this case, you control that code, so there should be no need for advice.

**Comment by Sasanidas** [comment]
Oh I see, yeah that advice wasn't in the best place tho, I changed the mode function to add it as a last instruction.

Also put these back-quotes and remove unnecessary lines

**Comment by riscy** [comment]
Thanks - I'm normally here on weekends, which is why my previous response seemed so fast!

There is still:
`inferior-islisp.el` with checkdoc 0.6.2:
```
inferior-islisp.el:157: First sentence should end with punctuation
```
due to the docstring for islisp-mode being stubbed in with an empty string `""`.  And that puts the checklist behind us. :)

Now that I'm taking a closer look I notice your `;;; Commentary` is stubbed in with just "Quick intro" for both packages -- you should fill this in, describe some quick entrypoints (the mode it defines), maybe mention `islisp-tags` (which they may have no idea about, and needs to be loaded separately) and give users something to grasp at when they're browsing the MELPA index.

The rest of my comments from this closer look (now that the checklist is done) are minor:
- You're indenting with a mix of tabs and spaces -- opt for one since, especially these days, different browsers/editors may have different ideas about how wide a tab should be.
- Rather than calling `eww` to browse in `islisp-hyperdraft-lookup-documentation`, I'd personally just recommend browse-url.  If users want to use eww, they can `(setq browse-url-browser-function 'eww-browse-url)`
- Note that your `(add-to-list 'auto-mode-alist '("\\.lsp\\'" . islisp-mode))` clashes with a builtin auto-mode, `("\\.li?sp\\'" . lisp-mode)`.  I think this is fine (looks like most islisp files use the lsp extension) but you should be aware of this overlap and possibly mention it in your Commentary.

**Comment by lassik** [comment]
> looks like most islisp files use the lsp extension

Is there a semi-reliable way to differentiate between ISLisp and Common Lisp by looking at the file contents?

**Comment by riscy** [comment]
I'll mark this one awaiting-upstream for now, but feel free to reach out.

**Comment by Sasanidas** [comment]
> 

There are some differents, but really not that many, in fact some files can be exactly the same.

**Comment by Sasanidas** [comment]
> Note that your (add-to-list 'auto-mode-alist '("\\.lsp\\'" . islisp-mode)) clashes with a builtin auto-mode, ("\\.li?sp\\'" . lisp-mode). I think this is fine (looks like most islisp files use the lsp extension) but you should be aware of this overlap and possibly mention it in your Commentary.

That's quite unfortunate, the lsp extension that Common Lisp uses it's from a library https://www.cliki.ne/Lisp%20Server%20Pages
so it's not really part of the language.
Still, i'll add the warning to the README and in the major mode header.

**Comment by Sasanidas** [comment]
Hello @riscy , thanks for the patience, I added the requested changes :+1:

**Comment by lassik** [comment]
> Note that your (add-to-list 'auto-mode-alist '("\.lsp\'" . islisp-mode)) clashes with a builtin auto-mode, ("\.li?sp\'" . lisp-mode).

`magic-mode-alist` can be used to detect the language based on buffer contents.

**Comment by riscy** [comment]
This is a great suggestion that escaped me - thank you @lassik.  In this case I wonder if it would be tricky to define a MATCH-FUNCTION that would always work since most islisp looks like exactly like regular lisp, in this case.

Not a blocker, but your `;;; Commentary` should be word-wrapped somewhere around the typical 80 characters, because downstream systems, including the MELPA index itself, won't wrap this text (and in fact shouldn't, because sometimes those lines *need* to be long to hold error messages or long URLs).  Similarly the file islisp-hyperdraft.el still has a stub Commentary section which would probably be worth addressing down the road.

**Pull request merged**
