### PR TITLE
Add recipe for js-auto-beautify

### PR DESCRIPTION
**Pull request by Qquanwei**
### Brief summary of what the package does

auto format js code by js-beautify

### Direct link to the package repository

https://github.com/Qquanwei/auto-beautify.el

### Your association with the package

I am maintainer

### Relevant communications with the upstream package maintainer

[e.g., package.el compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Incorrect package header and footer
- Incorrect package dependency format. You must specify version
- Wrong `&optional` argument usage
- No autoload cookie

**Comment by Qquanwei** [comment]
Thanks :)
Fixed but I'm not sure all is correct

**Comment by syohex** [comment]
https://github.com/Qquanwei/auto-beautify.el/pull/1

Package header is still incorrect.

**Comment by purcell** [comment]
Thanks! Some quick feedback:
- Since this package is just for js, it should be called `js-auto-beautify` instead.
- All top-level symbols need to be prefixed with the package name, so symbols `current-line-empty-p` are not allowed. See the [elisp conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html) for more on this.
- The `" AB "` lighter string should be `" AB"`

**Comment by Qquanwei** [comment]
@purcell
ye! looks right, I fixed this PR 

refactor : auto-beautify -> js-auto-beautify
fixed : " AB " -> " AB"

**Comment by purcell** [comment]
Don't forget the `;;; auto-beautify.el ends here` footer too! :-)

**Comment by Qquanwei** [comment]
ok 
(sorry for you)

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
