### PR TITLE
Add recipe for helm-shell-history

### PR DESCRIPTION
**Pull request by anoopemacs**
### Brief summary of what the package does

Use helm to search the shell history when in shell-mode

### Direct link to the package repository

https://github.com/anoopemacs/helm-shell-history

### Your association with the package

An enthusiastic user. This package's original author is https://github.com/yuutayamada/helm-shell-history
I have merely fixed some package-lint errors to publish this to melpa.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Have you had any contact with @yuutayamada? The best outcome would be if you submit your changes to @yuutayamada's repo and they get merged there directly. Alternatively if @yuutayamada is happy for you to become the new maintainer, that would be good too.

**Comment by anoopemacs** [comment]
Thank you for reviewing @purcell

I have now gotten in touch with @yuutayamada  at https://github.com/yuutayamada/helm-shell-history/pull/1
Closing this pull request for now.

**Comment by yuutayamada** [comment]
Hello guys,

Recently my use of Emacs is kinda getting less, if @anoopemacs would want to maintain the package, 
I am totally okay with it. (and also I switched counsel.el)

**Comment by anoopemacs** [comment]
> ### Brief summary of what the package does
> Use helm to search the shell history when in shell-mode
> 
> ### Direct link to the package repository
> https://github.com/anoopemacs/helm-shell-history
> 
> ### Your association with the package
> An enthusiastic user. This package's original author is https://github.com/yuutayamada/helm-shell-history
> I have merely fixed some package-lint errors to publish this to melpa.
> 
> ### Relevant communications with the upstream package maintainer
> **None needed**
> 
> ### Checklist
> Please confirm with `x`:
> 
> * [x]  The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
> * [x]  I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
> * [x]  I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
> * [x]  My elisp byte-compiles cleanly
> * [x]  `M-x checkdoc` is happy with my docstrings
> * [x]  I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
> * [ ]  I have confirmed some of these without doing them

Edit:-
* [x] I am a maintainer of this project

**Comment by anoopemacs** [comment]
> Hello guys,
> 
> Recently my use of Emacs is kinda getting less, if @anoopemacs would want to maintain the package,
> I am totally okay with it. (and also I switched counsel.el)

Thanks a lot for the quick reply. I would love to be a maintainer of this awesome tool.
The helm world misses you @yuutayamada :)

**Comment by riscy** [comment]
That's great news, thanks very much for volunteering. :)

Some quick feedback --

package-lint (using version 20210127.158):
```
1 issue found:
8:23: warning: Use a non-snapshot version number for dependency on "helm" if possible.
```
[This version](https://stable.melpa.org/#/helm) is probably adequate.

- helm-shell-history.el#L51: It's safer to sharp-quote function names; use `#'`
- helm-shell-history.el#L62: It's safer to sharp-quote function names; use `#'`
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by anoopemacs** [comment]
Thank you for the feedback @riscy 
Have fixed the package lint issues and added a license file that github detects

**Comment by riscy** [comment]
Thank you!

**Pull request merged**
