### PR TITLE
Add kaocha-runner

### PR DESCRIPTION
**Pull request by magnars**
### Brief summary of what the package does

The package runs Clojure tests with the Kaocha library via CIDER (the Clojure IDE for Emacs).

### Direct link to the package repository

https://github.com/magnars/kaocha-runner.el

### Your association with the package

Maintainer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

Good checklist! The README and this are both very useful to improve quality. Thanks.

### CODE REVIEW

**Comment by riscy** [comment]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
1 issue found:

38:0: warning: Private functions generally should not be autoloaded.
```
Although this isn't a function, it is still a customizable variable.  In general, defcustoms shouldn't be private (as indicated by the double-hyphen) since by definition they should be visible (and customizable) to the user.  I also think the autoload cookies here and in the defgroup [aren't necessary](https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html#When-to-Autoload), but maybe you can clarify why they might need to be.

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
No issues! 🎉

Miscellaneous and minor:
- kaocha-runner.el#L21: Prefer `https` over `http` (if possible)

**Comment by magnars** [comment]
All good points. Thank you, I'll fix those at once.

The autoload for group/custom is just a piece of cargo culting on my part, having seen it in other packages. If they are not needed, I'll remove them.

**Comment by magnars** [comment]
Also, sorry for not catching the lint error. I added the autoloading without rerunning the linter. Shame on me.

**Comment by magnars** [comment]
All feedback has now been followed.

**Comment by purcell** [comment]
Looks good, even if the Clojurey-but-not-emacs-lispy "?" suffix in place of "-p" hurts my eyes a bit. ;-)  Merging now, thanks.

**Comment by magnars** [comment]
Thanks, Steve! :)

lør. 17. aug. 2019 kl. 07:23 skrev Steve Purcell <notifications@github.com>:

**Pull request merged**
