### PR TITLE
Positron forcibly adopting parrot

### PR DESCRIPTION
**Pull request by psionic-k**
There's no action on d12's parrot since I forked over a year ago, so I figured it was time to point MELPA at my fork.

My fork has a progress implementation for running parrot on git pushes and a hook function for org todo state changes.  These are enabled by default.  I considered turning them off by default, but I figure most people want to see a parrot when they install parrot and configure via customize from there.

Emacs support bumped to 27, pretty reasonable.

### Parrot

XPM modeline animations on certain actions.  Commands for word rotation that incorporate these rotations.

### Direct link to the package repository

https://github.com/positron-solutions/parrot

### Your association with the package

Maintainer.  Contributed a bit and couldn't contact the maintainer until after I had detached my fork.  Never got around to pointing MELPA over.

### Relevant communications with the upstream package maintainer

None further needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
You mentioned "couldn't contact the maintainer until after I had detached my fork" but we do have a wiki page on this https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks that should offer some clarity too.

Also I think it's prudent to mention @dp28 here, who is active recently on GitHub, and can chime in!

**Comment by riscy** [comment]
Have you reached out to the author's email?  I can do this if you want; the email address appears to be available in the current source code hosted on MELPA.

Incidentally, it is bad form for your version to erase the author's name from the `Author` metadata.  This field is in fact designed to support multiple authors, so instead of:
```elisp
;; Author: Psionik K <73710933+psionic-k@users.noreply.github.com>
;; URL: https://github.com/positron-solutions/parrot
;; Version: 2.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: games
```
your metadata block would be:
```elisp
;; Author: Psionik K <73710933+psionic-k@users.noreply.github.com>
;;         Other <some@email...address.com>
;; URL: https://github.com/positron-solutions/parrot
;; Version: 2.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: games
```
and you can verify that `(lm-authors)` gives you back a list to ensure you've formatted it correctly.

**Comment by tarsius** [comment]
I would recommend using:

```elisp
;; Author: {original author}
;;         {author of newer parts}
;; Maintainer: {author of newer parts}
```

I.e., list the original (aka *first*) author *first*, and highlight the fact that somebody else is doing the maintaining now, by adding the Maintainer header, which is intended for that purpose.

If the new parts pale in comparison to the original code, then it might be more appropriate to initially use just


```elisp
;; Author: {original author}
;; Maintainer: {author of newer parts}
``` 

and only after great things have been achieved, upgrade to listing multiple authors.

**Comment by psionic-k** [comment]
Reverted to putting me in the maintainer position.  I emailed d12 and linked.  Let's give them some time and things will naturally work themselves out.

**Comment by riscy** [comment]
Hi again @psionic-k - was I correct before in `@`'ing dp28 on GitHub?  Also, has the original author gotten back to you yet, or should we give this another week or so?

**Comment by psionic-k** [comment]
> was I correct
Known unknown :man_shrugging: 

I haven't heard anything on my end.  I went ahead and switch the maintainer email to my company generic contact email.

**Comment by riscy** [comment]
Hi again!  I realize I made a mistake above and dp28 was not the right user.  @dp12 if you see this, can you chime in?

@psionic-k another good part of https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks to read is under the "Other things to note" section, e.g. the section under opening a series of PRs.

**Comment by dp12** [comment]
Hi @riscy, thank you for bringing this to my attention. I am still interested in maintaining this package. I did see @psionic-k's PR for parrot, but I encountered an error with the package installation that I requested @psionic-k to look into before I could merge in the PR. Rather than pushing a fix, @psionic-k closed the PR (https://github.com/dp12/parrot/pull/12).

I would like to continue maintaining parrot as a plugin focused first on providing rotation functionality and secondly for showing parrot animations associated with the rotations. Functionality outside of these two goals is a bit of a moving target and not something I have the time or interest in to expand further. If others (e.g., @psionic-k) would like to fork the package and provide extended animation capabilities in a new package for MELPA, they are welcome to do so. I will try to make this clear by updating the README.

**Comment by psionic-k** [comment]
I decided to lubricate the conversation by correcting any outstanding compiler warnings so that my fork is 100% available to extract diffs for maintenance.

Before I made this PR, I double-checked rotation since I know I don't personally value that behavior and was likely to neglect it.  There are no remaining outstanding concerns from the https://github.com/dp12/parrot/pull/12.

@dp12  I wish you would have mentioned that I emailed you on the 21st so it doesn't sound like I dropped that PR and then showed up by surprise :smile_cat:

I don't recall my thinking around closing that PR, but my only memory was that I had already detached and later on when I saw my name last in the conversation, I probably assumed no further maintenance would occur and closed it.

> not something I have the time or interest in to expand further

From the original PR text:
> * animating while a process is running (magit-push integration provided)
> * integration with org todo state change provided. Changing an item to "DONE" animates by default.

There was no indication that these features were unwelcome in your fork at that time.  This is a rather unexpected shift of stance.  I feel compelled to point out that rotation is extremely niche while org todo states and magit push enjoy near universal popularity.

If these changes are not incorporated, I will continue to my request to take over maintainership.  While the MELPA maintainers will be right according to their process to close my PR, I think the users come out on bottom in that case, so I recommend @dp12 either incorporating the changes or allowing the change in maintainership to pass.

**Comment by dp12** [comment]
Thanks for the reply @psionic-k. TBH, I was quite surprised to hear about the proposed change in maintainership, but that's partly my fault for not checking that particular email account more frequently (I almost never receive emails there). I do check GitHub issues more frequently though, which is a nice place to discuss maintainership issues. 

I am still interested in incorporating your changes provided they pass installation checks and make sense in the context of the existing parrot functions. I will try to take another look if you believe you've fixed the errors. My conception of what parrot is has also been changing since I first released it, and I'm finding that I would like to avoid scope creep and communicate this more clearly to contributors. That being said, happy to take another look if you're interested in incorporating the changes into the original parrot repo.

**Comment by riscy** [comment]
I'll close this for now because I see @dp12 is active and wanting to keep maintainership status.  We can always reopen in the future if things change, though.  (And thanks @psionic-k for being willing to contribute as a maintainer.)

**Pull request closed without merging**
