### PR TITLE
Add plain-theme recipe

### PR DESCRIPTION
**Pull request by yegortimoshenko**
https://github.com/yegortimoshenko/plain-theme

### CODE REVIEW

**Comment by purcell** [comment]
Wouldn't it make more sense to just turn off `font-lock-mode`?

**Comment by yegortimoshenko** [comment]
No, see [the rationale](https://github.com/yegortimoshenko/plain-theme#rationale).

Turning off `font-lock-mode` will disable useful things that are not syntax highlighting: CIDER error underlining, `markdown-mode` italics and underlined URLs. And `org-mode` is nearly useless without `font-lock-mode` turned on.

**Comment by purcell** [comment]
Cool, thanks for the pointer. Makes sense!

**Comment by purcell** [comment]
P.S. It's a bug if a package like CIDER ever explicitly enables `font-lock-mode` -- they should never do that. /cc @bbatsov

**Comment by yegortimoshenko** [comment]
Oops, it looks like this issue was solved 3 months ago, see clojure-emacs/cider#1768. Now, that it has been fixed, I don't know other packages that conflict with `font-lock-mode` off, so I'll remove it from my rationale. I still hold the first argument, though.

**Comment by purcell** [comment]
Fair enough. :-)

**Pull request merged**
