### PR TITLE
Add recipe for mermaid-ts-mode

### PR DESCRIPTION
**Pull request by JonathanHope**
### Brief summary of what the package does

Major mode for [Mermaid](https://mermaid.js.org/) built on tree sitter.

### Direct link to the package repository

https://github.com/JonathanHope/mermaid-ts-mode

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`mermaid-ts-mode.el` with package-lint 20230905.629:
```
4 issues found:
1:0: error: Package should have a Homepage or URL header.
1:0: warning: The package summary should not end with a period.
7:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
27:0: error: "mermaid" doesn't start with package's prefix "mermaid-ts".
```

- Add *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/) to mermaid-ts-mode.el

**Comment by JonathanHope** [comment]
> Thanks for this. Quick first pass --
> 
> `mermaid-ts-mode.el` with package-lint 20230905.629:
> 
> ```
> 4 issues found:
> 1:0: error: Package should have a Homepage or URL header.
> 1:0: warning: The package summary should not end with a period.
> 7:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
> 27:0: error: "mermaid" doesn't start with package's prefix "mermaid-ts".
> ```
> 
>     * Add _formal_ license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/) to mermaid-ts-mode.el

Thanks for the feedback! I have pushed up a commit to address it.

**Comment by riscy** [comment]
Thank you for adding that boilerplate, although I think there is one oversight re: `;; This file is part of GNU Emacs.` (which is probably a copy-paste error).

**Comment by JonathanHope** [comment]
> Thank you for adding that boilerplate, although I think there is one oversight re: `;; This file is part of GNU Emacs.` (which is probably a copy-paste error).

Ah I saw that in other packages so I blindly copied it over. It has been removed. Thanks!

**Comment by riscy** [comment]
All good here.  Welcome to MELPA. :)

**Pull request merged**
