### PR TITLE
Add kwallet-auth-source package

### PR DESCRIPTION
**Pull request by vaartis**
### Brief summary of what the package does

A small package I wrote that allows to use KWallet as an auth-source.

### Direct link to the package repository

https://github.com/vaartis/auth-source-kwallet

### Your association with the package

I'm the maintainer / creator of the package.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hello, just a quick first pass.

### kwallet-auth-source.el ###

byte-compile with Emacs 27.1:
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org
- Lexical binding will be used in what follows
- No issues!

checkdoc 0.6.2:
- No issues!

package-lint 20200906.512:
```
1 issue found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
```


### Loadability ###

Verifying ability to #'load each file:
```
Loading kwallet-auth-source.el
Done.
```

### Package ###

- GitHub API found `GNU General Public License v3.0`
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to kwallet-auth-source.el

**Comment by vaartis** [comment]
Hopefully this should address the issues described.

**Comment by riscy** [comment]
I apologize for not mentioning this, but `Version:` is preferred over `Package-Version:` since MELPA will automatically create a `Package-Version` when the package goes out.

I notice the latest version gives this byte-compile with Emacs 27.1:
```
kwallet-auth-source.el:43:1:Warning: Unused lexical variable `port'
kwallet-auth-source.el:43:1:Warning: Unused lexical variable `type'
kwallet-auth-source.el:43:1:Warning: Unused lexical variable `backend'
```
Is it possible this points to a bug?  If not and the arguments have to be there, you can rename them to e.g. `_port`, `_type`, `_backend` and the byte-compiler will understand.

I'm also taking a closer look at the code now.  I notice you have a top-level `advice-add` which modifies Emacs behavior as soon as this package is loaded.  Generally we urge that simply loading a package should not have side effects that modify Emacs' behavior (or otherwise do some arbitrary amount of work) except in a narrow set of cases (e.g. adding to auto-mode-alist).  You could suggest the user adds this advice as part of your commentary, or even support a global minor mode that can be toggled off and on by users.

**Comment by vaartis** [comment]
Seems like adding lexical variables allows the compiler to check for unsused variables. 
Marked them with the underscore and changed package-version to version just now.

**Comment by riscy** [comment]
Great, thanks.

I had another look and read into the source of `auth-source.el` that comes with Emacs.  It seems like it already _mentions_ KWallet (on line 257 in Emacs 27.1), so it strikes me that there probably already is support for KWallet.  That is, the authors write `:tag "Secret Service API/KWallet/GNOME Keyring"` under the "Source definition".  Is it possible KWallet is already supported?

In any case, it looks like my comment re: `advice-add` still stands -- and since I took another look, here's a few more suggestions I jotted down.

- `kwallet-auth-source-key-separator` is this value ever likely to change?  It seems like this would be baked into kwallet, but I admit I'm not sure
- I'd suggest `kwallet-auth-source-wallet` and `kwallet-auth-source-folder`, `user`, and `host` should all probably use `shell-quote-argument` in case they contain special characters that the shell would interpret (for example spaces or `>` or ``` ` ```, etc., and using concat inside concat where these variables are used isn't necessary
- Instead of `:source "."`, why not `:source "KWallet"` ?

**Comment by vaartis** [comment]
> Is it possible KWallet is already supported?

While such support is said to exist, it never worked for me. I assume it work with DBus somehow, but for me this only ever worked for gnome keyring, not KWallet. And I couldn't find any documentation on the internet on how to make KWallet work with this secret service. Some write one has to install gnome-keyring, but this just makes emacs use gnome keyring and not KWallet.

> Instead of :source ".", why not :source "KWallet" ?

Must be some typo on my end, never noticed this.

> kwallet-auth-source-key-separator 

This is for key name separation. I, personally, use KWallet for email, so for me the separator would be '@' to separate the username and hostname as "name@mail.com". It's merely a symbol that is added to the name of the key to somehow separate username and domain name. I left it available for change in case someone does need it.

I'll fix the advice, quoting and source and respond back in the thread soon.

**Comment by vaartis** [comment]
All right, updated the repository with the fixes for the aforementioned things.

**Comment by riscy** [comment]
> While such support is said to exist, it never worked for me.

Do you think there's a bug with Emacs?  There's also secrets.el, documented [here](https://www.gnu.org/software/emacs/manual/html_node/auth/Secret-Service-API.html), describing itself as a "Client interface to gnome-keyring and kwallet."

I apologize for how long this is taking, but I'm a bit hesitant to merge since I'm seeing the KDE Wallet mentioned as supported in a few places in the Emacs docs.  I think it would be valuable to nail down where Emacs is failing at this, so that we can either file a bug report or suggest some improved documentation.

**Comment by riscy** [comment]
I'll mark this awaiting upstream in the meantime.

**Comment by riscy** [comment]
Hello, I know it has been some time.  I recently started to look into auth-source again and went ahead and looked into kwallet.  It seems from [this reddit thread](https://www.reddit.com/r/kde/comments/d8tjln/is_there_a_orgfreedesktopsecrets_implementation/) (which I found when reading [this](https://rtfm.co.ua/en/what-is-linux-keyring-gnome-keyring-secret-service-and-d-bus/#KWallet)) that KWallet's secret service implementation remains unfinished.  So I think the Emacs builtins are mistaken in listing KWallet in the .el files we talked above above.

That being the case, hopefully you're still open to visiting this one.  I figure this is good to merge, but one last question:
would you be open to renaming this package to `auth-source-kwallet`?  Then it would align with e.g. Emacs's builtin `auth-source-pass` so that all such packages exist in a similar namespace neighborhood.

**Comment by vaartis** [comment]
Sorry for not responding for a while, other things to do.. Yeah, i'll rename the package.

**Comment by riscy** [comment]
> Sorry for not responding for a while, other things to do

No worries, I'm equally guilty.  Everything checks out to me and I don't see any blockers, so this looks good to merge.

One thing I'd recommend fixing when you get a chance is that this will return invalid passwords (corresponding to the output from the shell) if kwallet-query is not installed.  For example:
```elisp
(auth-source-pick-first-password :host "riscy@host")
=> "/bin/bash: kwallet-query: command not found"
```
I think just adding a conditional to `auth-source-kwallet--kwallet-search` will do the trick, such as:
```elisp
(cl-defun auth-source-kwallet--kwallet-search (&rest spec &key _backend _type host user _port &allow-other-keys)
  "Search KWallet for the specified user and host.
SPEC, BACKEND, TYPE, HOST, USER and PORT are as required by
auth-source."
  (if (executable-find "kwallet-query")
    (let ((got-secret
           (string-trim
            (shell-command-to-string
             (concat "kwallet-query " auth-source-kwallet-wallet
                     " -f " auth-source-kwallet-folder
                     " -r "
                     (shell-quote-argument
                      (concat user auth-source-kwallet-key-separator host)))))))
      (list (list :user user :secret got-secret)))
    (warn "`auth-source-kwallet': kwallet-query is not installed")
    nil))
```
And welcome to MELPA. :)

**Pull request merged**
