### PR TITLE
Add consult-notes recipe

### PR DESCRIPTION
**Pull request by mclearc**
### Brief summary of what the package does

Uses consult to allow completing read across directories of notes

### Direct link to the package repository

https://github.com/mclear-tools/consult-notes

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

I am able to contact if there are breaking changes to consult 

### Checklist

- [X ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [ X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ X] My elisp byte-compiles cleanly
- [X ] `M-x checkdoc` is happy with my docstrings
- [ X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

Thank you!!

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass below --

`consult-notes-org-roam.el` with byte-compile using Emacs 28.1:
```
consult-notes-org-roam.el:36:1: Error: Cannot open load file: No such file or directory, s
```
Looks like a missing `Package-Requires` on `s`.

`consult-notes-org-roam.el` with package-lint 20220607.738:
```
3 issues found:
6:0: error: Package-Requires outside the main file have no effect.
43:0: error: "org-roam-node-display-template" doesn't start with package's prefix "consult-notes".
103:0: error: "org-roam-old-display-template" doesn't start with package's prefix "consult-notes".
```

`consult-notes.el` with package-lint 20220607.738:
```
3 issues found:
6:55: warning: Use a properly versioned dependency on "marginalia" if possible.
6:68: warning: Use a properly versioned dependency on "embark" if possible.
199:0: error: "org-roam-directory" doesn't start with package's prefix "consult-notes".
```
fyi, marginalia has 0.13 as its recent stable version, embark has 0.17

`consult-notes.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- consult-notes.el#L204: There is no need to quote lambdas (neither #' nor ')
- consult-notes.el#L204: It's safer to sharp-quote function names (consult-notes--make-source); use `#'`
- consult-notes.el#L229: It's safer to sharp-quote function names; use `#'`
- consult-notes.el#L229: It's safer to sharp-quote function names; use `#'`
```

**Comment by mclearc** [comment]
Thank you for the comments!

> ```
> consult-notes-org-roam.el:36:1: Error: Cannot open load file: No such file or directory, s
> ```
> 
> Looks like a missing `Package-Requires` on `s`.

Should be fixed

> `consult-notes-org-roam.el` with package-lint 20220607.738:
> 6:0: error: Package-Requires outside the main file have no effect.

Fixed

> 43:0: error: "org-roam-node-display-template" doesn't start with package's prefix "consult-notes".
> 103:0: error: "org-roam-old-display-template" doesn't start with package's prefix "consult-notes".

I'm not sure what to do here as these are functions from org-roam and are only run (along with the rest of consult-notes-org-roam) if org-roam is installed. I had hope that I was writing out the dependencies in a way that wouldn't affect someone who doesn't have org-roam installed, so any advice here would be helpful. 
 
> `consult-notes.el` with package-lint 20220607.738:
> 3 issues found:
> 6:55: warning: Use a properly versioned dependency on "marginalia" if possible.
> 6:68: warning: Use a properly versioned dependency on "embark" if possible.

Fixed -- this was a mistake on my part -- there are no explicit dependencies on marginalia or embark. 

> 199:0: error: "org-roam-directory" doesn't start with package's prefix "consult-notes".

Same deal here as the issues with consult-notes-org-roam -- any advice appreciated!

> - consult-notes.el#L204: There is no need to quote lambdas (neither #' nor ')
> - consult-notes.el#L204: It's safer to sharp-quote function names (consult-notes--make-source); use `#'`
> - consult-notes.el#L229: It's safer to sharp-quote function names; use `#'`
> - consult-notes.el#L229: It's safer to sharp-quote function names; use `#'`

Done -- thanks!

See commit https://github.com/mclear-tools/consult-notes/commit/5dee1e17be6d94d6557c1b971ac34d45ee2ba0c1 for all changes.

**Comment by riscy** [comment]
> I'm not sure what to do here as these are functions from org-roam and are only run (along with the rest of consult-notes-org-roam) if org-roam is installed. I had hope that I was writing out the dependencies in a way that wouldn't affect someone who doesn't have org-roam installed, so any advice here would be helpful.

These two affect the variables you defvar'd, not the functions.  In the case of `(defvar org-roam-node-display-template nil)`, this variable appears to exist as part of org-roam.  So if you're just declaring the variable, remove the `nil` and that makes it clear to the byte-compiler what's going on.  In the case of `org-roam-old-display-template`, this variable does not exist as part of org-roam, and so it should have a name that matches your package's namespace.

I might suggest just splitting this up into two MELPA recipes and have consult-notes-org-roam declare a `Package-Requires` on org-roam.  I wouldn't *insist*, but it would save you a tremendous amount of `declare-x` boilerplate in that file.

By the way, you should double-check your use of `defvar` across the code -- it takes three arguments, and only the third one is the docstring, but in some cases you're putting a docstring value where the initial value should go.

**Comment by mclearc** [comment]
@riscy -- thanks again for these comments. I have revised all the variable names & declarations. Everything should pass byte-compilation and package linting now (or at least it does on my tests). I've  kept this as a single recipe, largely because there are other consult org-roam packages out there (with differing features or functionality) and adding a new one seems like it would make things more confusing than necessary. You can see the full set of changes here: https://github.com/mclear-tools/consult-notes/commit/7de92a09ba9ddfe36a6bce686cfbb4b48554540b

**Comment by riscy** [comment]
Thank you!  And fair point about the existence of e.g. https://melpa.org/#/consult-org-roam .

Here's the latest on my end --

`consult-notes-org-roam.el` with byte-compile using Emacs 28.1:
```
consult-notes-org-roam.el:105:1: Warning: defvar
    `consult-notes-org-roam--old-display-template' docstring wider than 80
    characters
```

`consult-notes-org-roam.el` with checkdoc 0.6.2:
```
consult-notes-org-roam.el:106: Some lines are over 80 columns wide
```

The above two are actually the same issue (I'm still surprised the byte-compiler is checking this these days). I think you can get everything past checkdoc by rewriting the docstring as e.g.
```elisp
  "For internal use only.
This will contain the old display template settings when
`consult-notes-org-roam-mode' is loaded.  For internal use
only."
```

`consult-notes-org-roam.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- consult-notes-org-roam.el#L132: Prefer one blank line between this top-level form and the next
```
(Minor; I just added this check to my list of checks, which is why you may be seeing it appearing out of thin air)

`consult-notes.el` with byte-compile using Emacs 28.1:
```
consult-notes.el:232:79: Warning: reference to free variable
    `org-roam-directory'
```
This one may be new for when org-roam isn't installed.

**Comment by riscy** [comment]
Looks good!  Thanks.

**Pull request merged**
