### PR TITLE
Add helm-taskrunner recipe

### PR DESCRIPTION
**Pull request by sehnsucht13**
### Brief summary of what the package does
Helm-taskrunner is a frontend for the taskrunner library. It lets the user select and run tasks/targets from several build/taskrunner utilities. The pull request for the library is #6400 

### Direct link to the package repository

https://github.com/emacs-taskrunner/helm-taskrunner
### Your association with the package
Creator/Maintainer
### Relevant communications with the upstream package maintainer
None needed
### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
A quick pass over the checklist:

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190905.1847):
```
2 issues found:

1:1: error: package.el cannot parse this buffer: Invalid version syntax: `v3.0' (must start with a number)
8:60: error: "v3.0" is not a valid version string: see `version-to-list'.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
No byte-compilation issues! 😎

Added miscellaneous hints (automated):
- helm-taskrunner.el#L344: It's safer to sharp-quote function names; use `#'`

**Comment by sehnsucht13** [comment]
Thanks for the feedback. I will fix it asap

**Comment by riscy** [comment]
Ping! :)

**Comment by riscy** [comment]
Feel free to reopen this when you're ready!

**Pull request closed without merging**
