### PR TITLE
add recipe for clingo-mode

### PR DESCRIPTION
**Pull request by llaisdy**
### Brief summary of what the package does

A major mode for working with clingo Answer Set Programming files (see https://potassco.org/).

Differences from the similar pasp-mode (see below) are due partly to my use of the mode to help my learning of answer set programming (eg examples directory; ability to call clingo on a selected region of the buffer, not just the whole file), partly to my discussions with the Potassco community (eg aim for feature parity with the [vim clingo mode](https://github.com/rkaminsk/vim-syntax-clingo/blob/master/syntax/gringo.vim), which is maintained by the Potassco people themselves).

If/when the package is accepted I shall add an installation from melpa section to the README.

### Direct link to the package repository

https://github.com/llaisdy/clingo-mode

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

This package is based on [pasp-mode](https://github.com/santifa/pasp-mode) which seems to have been abandoned.  I have discussed the best way to proceed on the Potassco mailing list (archive links available on request).

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Quick first pass --

- A user might have some concern with `clingo-generate-echo` -- what if `region` contains a quotation mark or other shell control characters?  The outcomes could sometimes be destructive if these aren't handled carefully
- clingo-mode.el#L334: Top-level `define-key` can sometimes overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- clingo-mode.el#L211: It's safer to sharp-quote function names; use `#'`
- (Minor) the `progn`s under `define-compilation-mode` and `clingo-reload-mode`  appear to not be necessary
- (Minor) Anwser -> Answer
- I'm just curious about `clingo-reload-mode` -- which is it necessary to sometimes do such an aggressive reload?  Or is this a developer convenience function? (In which case maybe it shouldn't be `interactive` thus polluting user's completions, and/or maybe it should be private, e.g. `clingo--reload`)

**Comment by llaisdy** [comment]
Thanks very much for the feedback!  I'll have a think and update the PR accordingly.

**Comment by riscy** [comment]
Had a quick look; I wonder if the changes aren't reflected on the default branch yet?

**Comment by llaisdy** [comment]
I haven't made any changes yet :)

**Comment by llaisdy** [comment]
Hello @riscy!  Brief update: I think I have addressed all your concerns, apart from the first one about `clingo-generate-echo`.  I am working on that now --- you are right, a quotation mark breaks the input --- will look for something to escape the string and/or try `shell-command-on-region`.

Re clingo-reload-mode: yes, a convenience for when I am hacking on the code.  Agree about marking the function as private, and removing `interactive`.

**Comment by riscy** [comment]
Everything looks good here!  A couple more quick comments as I merge:

- You might (or might not - ymmv) see some readability benefits from using `(eval-when-compile (require' rx))` and running the `rx` macro on some of your regexps, for example `(re-search-forward "\\.\\|:-\\|:")` can be written `(re-search-forward (rx (or "." ":-" ":")))`
- I'd recommend moving the `Todo` under your `;;; Commentary` into a separate frontmatter section -- you can simply rewrite the heading as `;;; Todo:` instead of `;;; Todo` (i.e. add a colon) and verify that it's stripped out with `(lm-commentary)`.  (Also move Keybindings above this new `;;; Todo: section)`

**Comment by llaisdy** [comment]
That is brilliant, thank you!  I'll incorporate the outstanding recommendations into clingo-mode soon.

**Pull request merged**
