### PR TITLE
Add counsel-mairix

### PR DESCRIPTION
**Pull request by ane**
### Brief summary of what the package does

An ivy interface for Mairix.

### Direct link to the package repository

https://sr.ht/~ane/counsel-mairix/

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks!  Here's a quick first pass.

### counsel-mairix.el ###

byte-compile (using Emacs 27.1):
```
counsel-mairix.el:122:43:Warning: Unused lexical variable `rmailbuf'
counsel-mairix.el:122:43:Warning: Unused lexical variable `sumbuf'
counsel-mairix.el:122:43:Warning: Unused lexical variable
    `rmail-display-summary'
counsel-mairix.el:125:17:Warning: reference to free variable `rmail-buffer'
counsel-mairix.el:127:19:Warning: reference to free variable
    `rmail-summary-buffer'
counsel-mairix.el:235:1:Warning: Unused lexical variable `q'
In counsel-mairix--insert-pattern:
counsel-mairix.el:249:26:Warning: looking-back called with 1 argument, but
    requires 2-3
counsel-mairix.el:307:1:Warning: Unused lexical variable `prev'
In counsel-mairix--avy-yank-word:
counsel-mairix.el:424:13:Warning: assignment to free variable `yanked'
In end of data:
counsel-mairix.el:539:1:Warning: the following functions are not known to be
    defined: rmail-show-message, avy-process, avy-jump
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
counsel-mairix.el:279: Argument `new' should appear (as NEW) in the doc string
Warning (emacs): 
counsel-mairix.el:284: Argument `new' should appear (as NEW) in the doc string
Warning (emacs): 
counsel-mairix.el:289: Argument `new' should appear (as NEW) in the doc string
Warning (emacs): 
counsel-mairix.el:294: Argument `new' should appear (as NEW) in the doc string
Warning (emacs): 
counsel-mairix.el:389: Argument `name' should appear (as NAME) in the doc string
Warning (emacs): 
counsel-mairix.el:487: All variables and subroutines might as well have a documentation string
Warning (emacs): 
counsel-mairix.el:464: White space found at end of line
```

package-lint (using version 20200906.512):
```
3 issues found:
1:0: error: Package should have a Homepage or URL header.
381:0: error: "with-avy" doesn't start with package's prefix "counsel-mairix".
388:0: error: "define-address-avy" doesn't start with package's prefix "counsel-mairix".
```

Other possible lints:
- counsel-mairix.el#L321: It's safer to sharp-quote function names; use `#'`
- counsel-mairix.el#L24: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by ane** [comment]
Thanks. I fixed the byte compilation issues and the package-lint stuff, are the docstrings important enough to fix?

**Comment by riscy** [comment]
Yes please -- see the checklist.  Thanks!

**Comment by ane** [comment]
Ok, the docstrings are now fixed. Should be fine now.

**Comment by riscy** [comment]
Thanks very much for being understanding.  Regarding these last remaining warnings:

byte-compile (using Emacs 27.1):
```
counsel-mairix.el:553:1:Warning: the following functions are not known to be
    defined: avy-process, avy-jump
```

You can use `declare-function` to clean up byte-compile output, e.g. `(declare-function avy-process "ext:avy.el" ...)` or similar.

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by ane** [comment]
Sorry! Totally forgot about this! Now it should work cleanly, I added those `declare-function`s.

**Comment by riscy** [comment]
Great!  This won't block the merge, but you may want to wordwrap some of your long docstrings.  One example is `counsel-mairix-display-result-message`.  I mention this because the Emacs help facility doesn't know where it should do the wrapping and this could make it harder for some users to read.  In any case, thanks for this.

**Pull request merged**
