### PR TITLE
Add ascii-table recipe

### PR DESCRIPTION
**Pull request by lassik**
### Brief summary of what the package does

Interactive ASCII table

Show a character map of the ubiquitous 7-bit ASCII character set (128 characters in total).

Do `M-x ascii-table` to bring up a window with the ASCII table.  Press 'b' for binary, 'o' for octal, 'd' for decimal and 'x' for hexadecimal. Press TAB to change the way control characters are shown.

### Direct link to the package repository

https://github.com/lassik/emacs-ascii-table

### Your association with the package

Wrote it

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```
 ascii.el    17     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 ascii.el    27     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
```
Note:
`ascii` is a common word and may have a good package name like `ascii-table` or `ascii-interactive-table`.

**Comment by lassik** [comment]
Thanks. Fixed the checkdoc warnings. My copy of checkdoc did not warn about them. Maybe it's sensitive to the value of `sentence-end-double-space`.

**Comment by lassik** [comment]
Please vote on this comment:

* 👍 - change the package name to `ascii-table`
* 👎 - keep the package name `ascii`

**Comment by lassik** [comment]
The current command name is `M-x ascii`. Changing the package name to `ascii-table` would mean that the command has to be `M-x ascii-table` as well. Of course, you could still do `(defalias 'ascii 'ascii-table)` in your personal Emacs config, but it's an extra step.

* If the package name is kept as `ascii`, perhaps other ASCII-related things besides the table can also be collected in the same package.
* On the other hand, it could be more polite towards GNU to let them have all symbols that start with `ascii`.
* On the third hand, Emacs has existed for 35 years and they still haven't coined any such symbols.

**Comment by purcell** [comment]
Definitely suggest `ascii-table`. We all use completing `M-x` or keybdindings anyway, so command name length isn't really an issue, nor the longer internal identifiers. Looks good though!

**Comment by lassik** [comment]
Thanks for the review.

OK, the request to change the name to `ascii-table` is unanimous. Changed.

**Comment by purcell** [comment]
Great, merged now - thanks!

**Pull request merged**
