### PR TITLE
Add recipe for doom-parents

### PR DESCRIPTION
**Pull request by tomekw**
### Brief summary of what the package does

A set of Doom Emacs mappings for manipulating parentheses and sexps

### Direct link to the package repository

https://github.com/tomekw/doom-parents

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly **I didn't teast that as I don't know how to check this**
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Although useful, this sort of lower-level configuration is not usually something that we tend to index in MELPA.  It's also hard to express the dependency on doom since it isn't a package that gets indexed anywhere.

But please let me know if I can give more clarification around this.

**Comment by tomekw** [comment]
Thank you @riscy for looking into this. Should I close the PR then?

My idea was to give it more visibility as some people my find it useful, but maybe there is a better place to host this.

**Comment by minad** [comment]
I've heard that Doom plans to add community maintained modules. @tomekw Maybe your configuration could be added there?

**Comment by riscy** [comment]
Thanks both -- I think @minad has a great suggestion.  @tomekw I think we should close this for now, but I'll be interested to look into doom's community maintained modules.

**Pull request closed without merging**
