### PR TITLE
Add recipe for historian

### PR DESCRIPTION
**Pull request by raxod502**
### Brief summary of what the package does

Historian.el stores the results of completing-read and similar
functions persistently. This provides a way to give completion
candidates that are more frequently or more recently used a better
position in the candidates list.

### Direct link to the package repository

https://github.com/PythonNut/historian.el

### Your association with the package

I'm an enthusiastic user---I had been wanting something that would
properly generalize `smex` for quite a while.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ ] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
This is nice. I wonder if @abo-abo is aware of your work on this library?

**Comment by manuel-uberti** [comment]
Out of curiosity: does this make `smex` obsolete?

**Comment by abo-abo** [comment]
@purcell I wasn't aware, thanks for the pointer. There was some discussion for a similar feature at https://github.com/abo-abo/swiper/issues/436, but it's not finalized.

**Comment by raxod502** [comment]
@manuel-uberti Unfortunately, not quite yet. It only needs one additional feature, though: displaying the last few selected items at the top of the list when there is no query typed in. This should be a pretty easy feature to add, however. Once I have time I would like to make it a complete replacement for `smex` and also write some documentation. Neither me nor the author tend to have oodles of free time, unfortunately.

**Pull request merged**
