### PR TITLE
Added a recipe for helm-selected.el

### PR DESCRIPTION
**Pull request by takaxp**
### Brief summary of what the package does

This package is an helm extension for selected.el. selected.el provides a combined keymap with associated commands for the selected region like a popup menu when you right-click on a selected word in your document. The menu, however, will not be displayed in an emacs buffer. So this package provides a visible menu with command candidates by supporting of helm interface.

### Direct link to the package repository

https://github.com/takaxp/helm-selected

### Your association with the package

the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by takaxp** [comment]
I don't know why the Travis get so angry...
The log message says "Cask could not be bootstrapped. Try again later, or report an issue at https://github.com/cask/cask/issues".
Any thoughts what I should do next?

**Comment by purcell** [comment]
Thanks, looks good. These days you should be using `cl-lib` instead of the deprecated `cl` library. It's generally just a matter of changing the `require` line and using `cl-loop` instead of `loop` etc.

**Comment by purcell** [comment]
Also, sorry for the slow turnaround.

**Comment by takaxp** [comment]
Thank you for the practical comment! I'll change it soon.
And I don't think this merge is slow :) thanks!

**Pull request merged**
