### PR TITLE
Add recipe for bupper

### PR DESCRIPTION
**Pull request by se7entyse7en**
Signed-off-by: Lou Marvin Caraig <loumarvincaraig@gmail.com>

### Brief summary of what the package does

Provides a command for swapping the buffer of the current window with the one of another window.

### Direct link to the package repository

https://github.com/se7entyse7en/bupper

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  The execution looks good, but have you had a chance to check out [swap-buffers](https://github.com/ekazakov/swap-buffers) or possibly [buffer-move](https://github.com/lukhas/buffer-move)?

**Comment by se7entyse7en** [comment]
Hi @riscy, thanks for taking a look into this! 🙇 

Thanks for pointing out those two packages! So here are my thoughts:
- `buffer-move`: it's cool, but it doesn't cover some use cases. For example, I use emacs on a 4k monitor and I use the frame split in 5 columns and some of those are split by 2 or 3 rows. So being able to swap with a specific other window instead of just "moving" is what would be needed in this use case at least.
- `swab-buppfers`: the idea here seems to be exactly the very same as `bupper`. I didn't run it, but by solely looking at the screenshots, the thing that I don't like is that it hides the content of the window during the selection. I agree though that this could be considered as a minor UI thing and that could probably be customized by opening a PR upstream.

This is my very first experience in writing an elisp (or at least doing something meaningful that could be packaged 😂), and since I think I came up with something that could be useful to others in the community I decided that it worth trying to add it to `melpa`. But in case you think the difference/originality is not enough, I understand it and feel free to close this issue 👍

**Comment by alphapapa** [comment]
See also `ace-window`, whose readme explains: https://github.com/abo-abo/ace-window

```
Change the action midway

You can also start by calling ace-window and then decide to switch the action to delete or swap etc. 
By default the bindings are:

    x - delete window
    m - swap windows
    M - move window
    c - copy window
    j - select buffer
    n - select the previous window
    u - select buffer in the other window
```

**Comment by se7entyse7en** [comment]
I'm an `ace-window` user, but I totally missed that functionality. It still requires an extra key-press, but since there are already different valid alternatives that achieve the same (even if in different ways), I'll leave it to you whether to merge or close.

**Comment by riscy** [comment]
> I didn't run [swap-buffers], but by solely looking at the screenshots, the thing that I don't like is that it hides the content of the window during the selection. I agree though that this could be considered as a minor UI thing and that could probably be customized by opening a PR upstream.

I just tested it out myself and it doesn't hide the content during selection.  I'd encourage you to give it a try too.  (But yes arguably the screenshots could be improved for clarity.)

I do like your package's execution, but maybe this is an opportunity for you to join forces with the author of swap-buffers, and see if you can't get the behavior you desire out of it.  (Quickly looking at the swap-buffers code I can see some customization options need small maintenance, e.g. `swap-buffers-increase` isn't used anywhere).

**Comment by riscy** [comment]
This is always a hard call to make because I don't want to discourage good work.  Out of curiosity I'd love to see how this package continues to develop in the future -- so this doesn't preclude the possibility of you reopening a PR for this package in the future -- but I think for now it's a good idea to leave it as a playground.  (I have a few elisp projects that I similarly use as playgrounds, so I understand the sentiment.)

**Comment by se7entyse7en** [comment]
No worries I totally understand, I’m glad that during this first experience I found a community willing to help and providing useful suggestions.

**Pull request closed without merging**
