### PR TITLE
Add orgraphy recipe

### PR DESCRIPTION
**Pull request by matthias-margush**
### Brief summary of what the package does

Enhance any theme with visual improvements for org mode, markdown

### Direct link to the package repository

https://github.com/matthias-margush/orgraphy

### Your association with the package

I am the creator of the package

### Relevant communications with the upstream package maintainer

n/a

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Checklist looks great on a quick first pass.  I'll look in more detail soon...

In the meantime, I couldn't help but try it out and notice my `ivy-read` fonts are changed, for example when I'm switching buffers.  This is apparently because the counsel faces inherit from org-mode, which caught me by surprise, so I'm passing it along fyi (not that there's much you can do but document it for users):

image

**Comment by matthias-margush** [comment]
Interesting. From the `counsel-outline-face-style` doc, it looks like this is a feature `counsel-outline`. It's default setting uses the `counsel-outline-default` face in the outline selection buffer (so no scaling.) It offers a few other choices that will display the outline with scaled fonts in various ways. So from what I can tell, the font scaling here is intended by ivy, and would additionally need to be wanted & turned on by the user explicitly.

**Comment by purcell** [comment]
Thanks! Some notes:

- The font heights and styles are hard-coded, and cannot be customised. This makes the whole file seem like a bundle of personal preferences rather than a package that will be useful to  other people. The theme system supports multiple active themes at one time, so you could simply write an additional theme for those customisations.
- Is [this](https://github.com/matthias-margush/orgraphy/blob/6799e5265e168e518983afd2eb6fec84898c234d/orgraphy.el#L161) really what the minor mode does?
- Why are you [altering `org-mode-hook`](https://github.com/matthias-margush/orgraphy/blob/6799e5265e168e518983afd2eb6fec84898c234d/orgraphy.el#L139-L155) from a global minor mode when you could instead provide a local minor mode that the user can activate in `org-mode-hook`? This is unidiomatic. Whenever you find yourself writing `init` and `deinit` functions, you're probably writing a minor mode. Same applies when you find yourself saving previous values of faces or variables to hash tables etc.
- Same comment here re. linking to the README. At least tell the user roughly how to use the package.

**Comment by purcell** [comment]
Ping! :-)

**Comment by riscy** [comment]
Please feel free to reopen if/when this is ready.

**Pull request closed without merging**
