### PR TITLE
Add sml-basis recipe

### PR DESCRIPTION
**Pull request by lassik**
### Brief summary of what the package does

Provides commands to look up exceptions, functors, signatures, structures, types, and values in the Standard ML Basis Library.

Each command provides tab completion and opens the documentation in your web browser using `browse-url`. The standard variable `browse-url-browser-function` can be used to control which web browser is used to open what pages.

The documentation is at https://smlfamily.github.io/Basis/.

### Direct link to the package repository

https://github.com/lassik/emacs-sml-basis

### Your association with the package

Just wrote it

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by lassik** [comment]
Tested using the Docker container `silex/emacs:24.5` that it loads and produces no byte-compiler warnings.

**Comment by riscy** [comment]
Checklist looks good, although I wonder about the license/copyright state of the file sml-basis-data.el.  It says it's automatically converted from the web -- is it converted from https://smlfamily.github.io/Basis/?  That page has license terms that must be "prominently displayed within every machine-readable copy." (and I suppose this counts as a "copy").

**Comment by lassik** [comment]
Good point. `sml-basis-data.el` is an automated conversion of the index of that manual. I doubt the index will count as a reproduction of the manual, but it's good to err on the safe side. Would it be adequate if I copy that notice as a source code comment into `sml-basis-data.el`? When people use this Emacs package to visit any of the web pages with the actual documentation, they print the copyright notice at the bottom of every page.

**Comment by riscy** [comment]
Yeah -- I'm obviously not a lawyer, but as a copyright owner I'd appreciate having that notice copied into the boilerplate.

**Comment by riscy** [comment]
And, thanks! :)

**Pull request merged**
