### PR TITLE
Add indent-info recipe

### PR DESCRIPTION
**Pull request by terlar**
### Brief summary of what the package does

Show indentation information in status bar.

### Direct link to the package repository

https://github.com/terlar/indent-info.el

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by terlar** [comment]
Unfortunately I could not check the box for `M-x checkdock` as it complains about the usage of `indent-info-mode' in the documentation string, as it wants to be more specific. It wants to be prefixed with function, command, variable, option or symbol. But I am not sure what mode counts as.

**Comment by purcell** [comment]
Thanks - looks handy! Quick feedback:
- Please remove the `:files` spec from the recipe, which is unnecessary here.
- [Changing mode-line-position at the top level of the file](https://github.com/terlar/indent-info.el/blob/28045d16e192b61e1ef4af7626278d89592f9ca6/indent-info.el#L117-L121) seems inappropriate. Presumably it should happen when the mode is enabled/disabled instead.
- [redraw-frame](https://github.com/terlar/indent-info.el/blob/28045d16e192b61e1ef4af7626278d89592f9ca6/indent-info.el#L142) should probably be `force-mode-line-update` instead
- [`(if (not x) ...)`](https://github.com/terlar/indent-info.el/blob/28045d16e192b61e1ef4af7626278d89592f9ca6/indent-info.el#L170-L171) is better written `(unless x ...)`

**Comment by terlar** [comment]
Thank you for the feedback. I have fixed the things you mentioned in the feedback. Found a better way to add the indent info to `mode-line-position` and added it inside the mode toggle part, I hope it is the right way.

**Comment by purcell** [comment]
Looks great! Two more small points (though I'll merge now anyway):
- `indent-info-mode-enable` shouldn't be autoloaded: users shouldn't be calling it directly anyway, when they can just use `indent-info-mode` directly instead.
- You should remove the mode line entry when disabling the minor mode, so your `when` should be an `if`.

Welcome to MELPA!

**Comment by terlar** [comment]
Thank you, I have addressed those issues.
Glad to finally do some contribution to the community.

**Pull request merged**
