### PR TITLE
Add exwm-x

### PR DESCRIPTION
**Pull request by tumashu**
exwm-x is an extension of exwm

### CODE REVIEW

**Comment by purcell** [comment]
Thanks.

- Please amend the commit to remove the `:files` spec, which is unnecessary here.
- The `exwm-x-example.el` file should probably not be included in the package, because it will not byte-compile without `use-package`. Perhaps move it to an "examples" subdirectory?

**Comment by tumashu** [comment]
exam-x-example.el is useful, if i put it ot examples subdir,  we should deal with load-path,  
what about:
```
;; Local Variables:
;; no-byte-compile: t
;; End:

```

**Comment by tumashu** [comment]
```
Please amend the commit to remove the :files spec, which is unnecessary here.
```
This has some other problem: how to deal with .dir-local.el file and how to remove snapshot dir?

**Comment by purcell** [comment]
> what about:
> 
> ;; Local Variables:
> ;; no-byte-compile: t
> ;; End:

Yep, fine.

> This has some other problem: how to deal with .dir-local.el file and how to remove snapshot dir?

Neither of those would be included by the default pattern. Check out our README to see the defaults.

**Comment by tumashu** [comment]
Fixed, check again.

**Comment by purcell** [comment]
Super, thanks.

**Pull request merged**
