### PR TITLE
Add recipe for new package lsp-scheme

### PR DESCRIPTION
**Pull request by rgherdt**
Add support for Scheme to the lsp-mode. Currently only CHICKEN and Guile are
supported. This package relies on scheme-lsp-server available at
https://codeberg.org/rgherdt/scheme-lsp-server. I am the creator of both the
LSP server and this package.

Repository: https://codeberg.org/rgherdt/emacs-lsp-scheme

Differently than most other lsp-mode packages, lsp-scheme creates a single
instance of Scheme (Guile or CHICKEN, depending on which library is loaded) that
spawns on demand new threads providing LSP servers. This way the user can
interact with the running instance, for which a REPL is available at
*lsp-scheme*, and information is provided based on what the user defined/loaded.

### Brief summary of what the package does

[Please write a quick summary of the package.]

### Direct link to the package repository

https://github.com/your/awesome_package

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Based on the namespaces of the different files, it's possible these should either be separate recipes, or have their prefixes aligned.  In the meantime, here's a quick first pass --

`lsp-chicken.el` with byte-compile using Emacs 28.1:
```
lsp-chicken.el:64:1: Warning: argument `_update\?' not left unused
lsp-chicken.el:64:1: Warning: argument `_client' not left unused
```

`lsp-chicken.el` with package-lint 20220607.738:
```
6 issues found:
35:0: error: "lsp-chicken--install-dir" doesn't start with package's prefix "lsp-scheme".
38:0: error: "lsp-chicken--install-egg" doesn't start with package's prefix "lsp-scheme".
58:0: error: "lsp-chicken--server-installed-p" doesn't start with package's prefix "lsp-scheme".
64:0: error: "lsp-chicken--ensure-server" doesn't start with package's prefix "lsp-scheme".
85:0: error: "lsp-chicken--setup-environment" doesn't start with package's prefix "lsp-scheme".
95:0: error: "lsp-chicken" doesn't start with package's prefix "lsp-scheme".
```

`lsp-guile.el` with byte-compile using Emacs 28.1:
```
lsp-guile.el:39:1: Warning: argument `_update\?' not left unused
lsp-guile.el:39:1: Warning: argument `_client' not left unused
```

`lsp-guile.el` with package-lint 20220607.738:
```
5 issues found:
36:0: error: "lsp-guile--install-dir" doesn't start with package's prefix "lsp-scheme".
39:0: error: "lsp-guile--ensure-server" doesn't start with package's prefix "lsp-scheme".
65:0: error: "lsp-guile--server-installed-p" doesn't start with package's prefix "lsp-scheme".
71:0: error: "lsp-guile--setup-environment" doesn't start with package's prefix "lsp-scheme".
89:0: error: "lsp-guile" doesn't start with package's prefix "lsp-scheme".
```

`lsp-scheme.el` with byte-compile using Emacs 28.1:
```
lsp-scheme.el:200:11: Warning: the function `lsp-guile' is not known to be
    defined.
lsp-scheme.el:197:11: Warning: the function `lsp-chicken' is not known to be
    defined.
```

`lsp-scheme.el` with checkdoc 0.6.2:
```
lsp-scheme.el:40: First sentence should end with punctuation
```

`lsp-scheme.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- lsp-scheme.el#L229: It's safer to sharp-quote function names; use `#'`
- lsp-scheme.el#L23: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- lsp-scheme.el#L201: No `format` required; `error` takes an f-string
```

Package and license:
- Prefer equivalent recipe: `(lsp-scheme :url "https://codeberg.org/rgherdt/emacs-lsp-scheme" :fetcher git)`
- lsp-scheme-pkg.el -- consider excluding; MELPA creates one

**Comment by riscy** [comment]
Thanks for checking out melpazoid. :)  Interesting error from Docker - I will have to keep an eye out for that one.  (Admittedly the docker dependency is a big one but it really helps level the environment out.)

Another quick pass --

- I think this requires a `lsp-mode` in its `Package-Requires` line
- You have a `Package-Requires` on dash, but I don't think you're making direct use of it.  Correct me if I'm wrong
- I see two `Package-Version` lines, but also you should prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)

**Comment by rgherdt** [comment]
> Thanks for checking out melpazoid. :) Interesting error from Docker - I will have to keep an eye out for that one. (Admittedly the docker dependency is a big one but it really helps level the environment out.)
> 
FWIT, I'm using Docker 20.10.5 on Debian 11.

> Another quick pass --
> 
>     * I think this requires a `lsp-mode` in its `Package-Requires` line
> 
>     * You have a `Package-Requires` on dash, but I don't think you're making direct use of it.  Correct me if I'm wrong
> 
>     * I see two `Package-Version` lines, but also you should prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)

Thanks for pointing this out, I applied the changes. The requirements were those from lsp-mode, I replaced them by "((emacs "25.1") (f "0.20.0") (lsp-mode "8.0.0"))".

**Comment by riscy** [comment]
Thanks!  Apologies for the back and forth, on another look I'm noticing you have two `Keywords:` lines and two `Author` lines.  Also note that, conventionally, the Author/Keywords/Version/Package-Requires block goes before the Copyright statement and license boilerplate.

Minor:
- Since it's a fairly big dependency I'd recommend listing Chicken somewhere on your summary line, e.g. "Scheme support for lsp-mode via CHICKEN"
- Should `(error "Implementation not supported: %s" implementation)` perhaps be a `user-error` instead?
- spwans -> spawns (ultra minor obviously)

**Comment by rgherdt** [comment]
> Thanks! Apologies for the back and forth, on another look I'm noticing you have two `Keywords:` lines and two `Author` lines. Also note that, conventionally, the Author/Keywords/Version/Package-Requires block goes before the Copyright statement and license boilerplate.
> 
> Minor:
> 
>     * Since it's a fairly big dependency I'd recommend listing Chicken somewhere on your summary line, e.g. "Scheme support for lsp-mode via CHICKEN"
> 
>     * Should `(error "Implementation not supported: %s" implementation)` perhaps be a `user-error` instead?
> 
>     * spwans -> spawns (ultra minor obviously)

Don't worry, my bad that I still had those copy&paste mistakes in the header, thanks for the suggestions. Fixed.
I added some more notes regarding implementations (CHICKEN and Guile). My goal is to keep the LSP server/client portable, and I'm already working on adding support to Gambit. So maybe the main description (first line) could stay like it is. What do you think?

**Comment by riscy** [comment]
Looks good to go!  Thanks. :)

**Pull request merged**
