### PR TITLE
Update url for helm-fuzzy.

### PR DESCRIPTION
**Pull request by jcs090218**
I moved this repo to under an organization, update the url. :D

### CODE REVIEW

**Comment by riscy** [comment]
Just out of curiosity, why don't these packages start out in the organization? :)

**Comment by jcs090218** [comment]
Oh, it's just my workflow. If the package doesn't get merged then I might transfer the package to somewhere else. :0

**Comment by tarsius** [comment]
> If the package doesn't get merged then I might transfer the package to somewhere else.

By "doesn't get merged" do you mean "is not added to Melpa because the maintainers reject it"?

Where would you transfer it to?

> Oh, it's just my workflow.

It sounds like this workflow makes things more complicated for Melpa maintainers, who now have to figure out (and optionally manage to remember for a long time) what you are doing and why.

Could your workflow be adjusted so that it doesn't involve two pull-requests if things go well? I.e. please consider going with `elpa-host/PACKAGE` right away.

**Comment by tarsius** [comment]
On #6445 @jcs090218 said:

>  Starting from next package I will start the package from organization.

**Pull request merged**
