### PR TITLE
Add recipe for ROOT-mode

### PR DESCRIPTION
**Pull request by jaypmorgan**
### Brief summary of what the package does

ROOT-mode provides the functionality to evaluate C++ code using the ROOT REPL (https://root.cern/) in C++ buffers, and C++ org-mode source code blocks.

### Direct link to the package repository

https://github.com/jaypmorgan/root-mode

### Your association with the package

I am the maintainer of ROOT-mode.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`root-mode.el` with byte-compile using Emacs 27.1:
```
root-mode.el:138:1:Warning: Unused lexical argument `proc'
root-mode.el:159:1:Warning: Unused lexical variable `vterm-shell'
In end of data:
root-mode.el:502:1:Warning: the following functions are not known to be
    defined: vterm-send-return, vterm
```
You can rename `proc` to `_proc` and the byte-compiler should be happy with that.  You can also `(defvar vterm-shell)` to pacify the byte-compiler for the second warning.  With respect to the undefined functions, you can use `declare-function` against those.  These are annoying to have to do, but they'll clean up the byte compile for users without vterm installed.

And here are some ultra minor sharp-quote nags, which can help the byte-compiler out in the future:
- root-mode.el#L251: It's safer to sharp-quote function names; use `#'`
- root-mode.el#L283: It's safer to sharp-quote function names; use `#'`
- root-mode.el#L135: It's safer to sharp-quote function names; use `#'`


I'm curious about `(add-hook 'root-mode-hook 'root--initialise)` in `root-mode` -- why not just call `root-initialise` directly?

`root-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- root-mode.el#L250: It's safer to sharp-quote function names; use `#'`
- root-mode.el#L282: It's safer to sharp-quote function names; use `#'`
- root-mode.el#L135: It's safer to sharp-quote function names; use `#'`
```

Package and license:
- Avoid specifying `:branch` except in unusual cases

**Comment by jaypmorgan** [comment]
Thanks @riscy for taking a look at it! I thought I'd already cleaned up all of these warnings... I'll respond again when they have been corrected :-).

**Comment by jaypmorgan** [comment]
Thanks again @riscy , I've gone through these warnings

**Comment by riscy** [comment]
Excellent, thanks for accommodating. This looks like an awesome package.  Some slightly more thoughtful feedback:

- I'm worried about the name `root-mode`; are you flexible on this?  It's a hugely overloaded term in computing and especially unix-like environments.  At least on their page they also refer to ROOT-based scripts as "CERN ROOT scripts", so maybe another possible name could be `cern-root-mode.el`?
- I believe the default `version-regexp` MELPA is using `"^[rRvV]?\\(.*\\)$"` should match the versions of the releases your cutting, so perhaps it doesn't need to be included in the recipe at all?
- For your purposes, `(progn (beginning-of-line) (point))` could be written as `(point-at-bol)` which I *think* would let you write the entire `root-eval-line` function without wrapping it in `root--remembering-position`

**Comment by jaypmorgan** [comment]
> I'm worried about the name root-mode; are you flexible on this? It's a hugely overloaded term in computing and especially unix-like environments. At least on their page they also refer to ROOT-based scripts as "CERN ROOT scripts", so maybe another possible name could be cern-root-mode.el?

That has also been a concern for me, but hadn't thought of a suitable alternative. Though, cern-root seems to work okay. Since the project is in it's infancy, changing the name shouldn't have an impact. Before changing it, I'll have a think about some possible alternatives.

> I believe the default version-regexp MELPA is using "^[rRvV]?\\(.*\\)$" should match the versions of the releases you're cutting, so perhaps it doesn't need to be included in the recipe at all?
> For your purposes, (progn (beginning-of-line) (point)) could be written as (point-at-bol) which I think would let you write the entire root-eval-line function without wrapping it in root--remembering-position

Noted. I'll update these.

**Comment by riscy** [comment]
Since `main` is your default branch I've removed that from your recipe.  If you decide you need to use a non-default branch in the future (not recommended) then that's an easy fix.

Happy to merge here -- and welcome to MELPA. :)

**Pull request merged**
