### PR TITLE
Add sorcery-theme

### PR DESCRIPTION
**Pull request by vxid**
### Brief summary of what the package does

Sorcery is a dark and low-contrast Emacs theme inspired by apprentice.
The repository includes screenshots.

### Direct link to the package repository

https://github.com/vxid/emacs-theme-sorcery

### Your association with the package
I am the maintainer.

### Relevant communications with the upstream package maintainer
None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi - thanks for your close adherence to the checklist!

I believe you want to add a `provide-theme` line above your `(provide 'sorcery-theme)` line at the bottom of the file (I had a quick check of `autothemer` and it seems it doesn't do this for you, although I suspected it might).

And a couple notes about the license:
- Use a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- Please add license boilerplate or an [SPDX license identifier](https://spdx.org/using-spdx-license-identifier) to sorcery-theme.el

**Comment by vxid** [comment]
Thank you for the feedback!

I did switch the license to GPL and added the required `(provide-theme 'sorcery)` (this is what I used at first but `package-lint` complained for some reason).

Let me know if I did something wrong, this is my first PR to MELPA.

**Comment by riscy** [comment]
I notice you wrote `;; Copyright (c) 2020 Free Software Foundation, Inc.` but really the copyright is yours unless you did the paperwork to reassign your copyright.  Probably you'll want to update that (you own the copyright automatically) but that's not a blocker.

Looks like a great theme!  Thanks and welcome to MELPA. :)

**Comment by riscy** [comment]
(The copyright line is optional -- copyright is automatic -- and the license is the important part)

**Comment by vxid** [comment]
Oops, I will correct it next time I push some changes. Thanks a lot for the help!

**Pull request merged**
