### PR TITLE
Add 'modus-themes' recipe and make necessary edits

### PR DESCRIPTION
**Pull request by protesilaos**
### Brief summary of what the package does

Highly accessible themes that conform with the WCAG AAA standard for color contrast (the highest accessibility standard of its kind).

### Direct link to the package repository

https://gitlab.com/protesilaos/modus-themes

### Your association with the package

Author/maintainer

### Relevant communications with the upstream package maintainer

None needed.  I am the maintainer

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by protesilaos** [comment]
Apart from introducing the new `modus-themes` recipe, this PR makes explicit the branch of the `modus-operandi-theme` and `modus-vivendi-theme` recipes (also mine).  This is because that branch will stop receiving updates in accordance with what I outlined in issue 7245: <https://github.com/melpa/melpa/issues/7245>.

**Comment by tarsius** [comment]
The explicit `:files` should not be necessary.

**Comment by protesilaos** [comment]
> The explicit :files should not be necessary.

Okay, I will update it right away.  How about the `:branch`?  I plan to make `main` the default once this goes forward.

**Comment by tarsius** [comment]
> I plan to make `main` the default once this goes forward.

That's still necessary I believe. We should make it unnecessary to be explicit but it might be a while until I get around to it.

**Comment by protesilaos** [comment]
> That's still necessary I believe. We should make it unnecessary to be explicit but it might be a while until I get around to it.

I understand.  Thank you!

**Comment by riscy** [comment]
> That's still necessary I believe. We should make it unnecessary to be explicit but it might be a while until I get around to it.

Some people are discovering that straight.el has trouble when the default branch isn't called master, but I believe MELPA handles it fine unless I'm missing something.

**Comment by riscy** [comment]
By the way, @protesilaos, I'm always happy to see when you have new Emacs videos.

A couple quick issues I see:

How come your boiler plate contains:
```elisp
;; Copyright (C) 2019-2020 Free Software Foundation, Inc.
;; This file is part of GNU Emacs.
```
I think these aren't part of Emacs (yet?) and can you remind me if you signed the paperwork for FSF copyright assignment?  Mostly just to check if these are copy-paste mistakes which are common.

`Package-Requires outside the main file have no effect.` although these are all compatible -- fyi.

**Comment by protesilaos** [comment]
>> That's still necessary I believe. We should make it unnecessary to be explicit but it might be a while until I get around to it.
>
> Some people are discovering that straight.el has trouble when the default branch isn't called master, but I believe MELPA handles it fine unless I'm missing something.

I say we keep the branch explicit.  Though I am always willing to follow your instructions.

> By the way, @protesilaos, I'm always happy to see when you have new Emacs videos.

Thanks!  And I realise that I have not praised you in particular and the rest of the Melpa team for all your contributions (you had reviewed my two previous submissions as well).  I shall rectify that.

> I think these aren't part of Emacs (yet?) and can you remind me if you signed the paperwork for FSF copyright assignment? Mostly just to check if these are copy-paste mistakes which are common.

They are since a few months ago: https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/themes.  I can point you to the specific commit if you need, as well as mailing list threads.

> Package-Requires outside the main file have no effect. although these are all compatible -- fyi.

Just to be sure I understand this: I only need that comment header in `modus-themes.el` but not in all the others?

**Comment by tarsius** [comment]
> Just to be sure I understand this: I only need that comment header in `modus-themes.el` but not in all the others?

Yes, it is only needed in the "main library". Of course previously the repository contained multiple "main" libraries because each one of them was distributed as a separate package, but since that isn't the case anymore this additional metadata isn't used by any tools anymore.

Also note that GNU Elpa has different requirements (last I checked). For packages consisting of more than one file it requires the `NAME-pkg.el` file to exist and ignores metadata from the main library. (While Melpa ignores a preexisting `NAME-pkg.el` file and (re-)generates it from information it finds in the main file.) :stuck_out_tongue_closed_eyes:

**Comment by tarsius** [comment]
I just checked and `package-build.el` does not the branch to be set explicitly as it uses something resembling `git remote show origin | grep HEAD`. But we can set it explicitly for `straight` for now.

**Comment by protesilaos** [comment]
Thank you!

**Comment by riscy** [comment]
I just noticed these are also on ELPA, although as two separate packages instead of one.  I'll quote purcell on this one:

> we don't find it super helpful to host packages that are also in GNU ELPA, because it can lead to confusion about which of two different versions is the canonical one -- here the code would exist both in your github repo and in the Savannah git, where others could also modify it. Is it wise/helpful for us to continue to host it here too?

**Comment by protesilaos** [comment]
> I just noticed these are also on ELPA, although as two separate packages instead of one.

Yes, this will now have to change.  I started from here and will proceed with sending the new code to upstream Emacs (probably tomorrow).

GNU ELPA was configured in the previous state, back when MELPA also served two packages.  The code for GNU ELPA was pulled from my repo and the two packages were internally marked as "external": https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/externals-list#n185 (however, because the themes are now in Emacs as well, they should be edited to become `:core` packages---notwithstanding the merge into a single package).

> I'll quote purcell on this one [...]

I understand the potential problem.  What do you think is the best solution here?

**Comment by riscy** [comment]
> I understand the potential problem. What do you think is the best solution here?

I think, given you've signed the copyright forms for FSF, it's best to host the package only on ELPA to avoid any confusion.

**Comment by riscy** [comment]
(There's no rush to do this or anything though, that's just a heads up on what & why.)

**Comment by protesilaos** [comment]
> it's best to host the package only on ELPA to avoid any confusion.
>
> (There's no rush to do this or anything though, that's just a heads up on what & why.)

This is fine by me, though I would need some time to make the requisite changes.  Not least because GNU ELPA is currently two releases behind and I have no write access there.

What would be a reasonable time frame for the transition?  Three to six months, perhaps?  Do I notify you via a PR that deletes the `modus-themes` recipe?  Or will this be handled internally?

What happens to those who will get the `modus-themes` package in present time from MELPA once it is deleted?  Will `package.el` automatically switch them to the `modus-themes` on ELPA (assuming that is available by then)?

**Comment by riscy** [comment]
> What would be a reasonable time frame for the transition? Three to six months, perhaps? Do I notify you via a PR that deletes the modus-themes recipe? Or will this be handled internally?

This timespan sounds fine to me.  Ideally yes you would open a PR that removes the recipes.

> What happens to those who will get the modus-themes package in present time from MELPA once it is deleted? Will package.el automatically switch them to the modus-themes on ELPA (assuming that is available by then)?

I'm fairly certain that it will be a seamless process for users -- they'll continue to be able to download the latest modus-themes from wherever it's indexed.

**Comment by protesilaos** [comment]
Thank you, Chris!  I will open a new PR as soon as Emacs and ELPA get the latest version.

**Pull request merged**
