### PR TITLE
Add flymd recipes

### PR DESCRIPTION
**Pull request by mola-T**
https://github.com/mola-T/flymd

flymd is a on the fly markdown preview package.

### CODE REVIEW

**Comment by milkypostman** [comment]
please change files to `(:defaults "flymd.html")`

how does this compare with markdown-mode? it seems like with markdown mode all you need is an on-save hook. also there is some timer function builtin to emacs I think where you can hookup a function call to a timer.

it seems like this might be better as a minor mode?

**Comment by purcell** [comment]
> it seems like this might be better as a minor mode?

+1

**Comment by mola-T** [comment]
@milkypostman 

1. How does this compare with markdown-mode?

   I love the `markdown-mode`. But it cannot fulfill my need. The way you suggested is not the best for me. New browser windows/tabs will be created upon function calls or the browser page needs to be refresh constantly. 

In fact, it is more close to https://github.com/ancane/markdown-preview-mode. But I also have problem using this.....

2. I don't implement this as a minor mode because it is overhead and not user-friendly.
 
   For example, if user want to bring up a live preview, they do `flymd-mode` and a browser page is brought up. If the user close the browser page accidentally, they can't call `flymd-mode` again to open the browse page. It will lead to another function like `flymd-open-browser` which I don't prefer.

**Comment by purcell** [comment]
Thanks.

**Pull request merged**
