### PR TITLE
Add ‘elpa-deploy’ recipe.

### PR DESCRIPTION
**Pull request by oitofelix**
----

### Brief summary of what the package does

ELPA deployment library

This library provides `elpa-deploy`: a complement to the function
`package-upload-file` from `package-x.el`, which automatizes the
deployment of simple and multi-file packages.  This function
automatizes the upload of a library to an ELPA directory so that no
other action is needed.  Particularly useful for rapid ELPA deployment
aiding testing and releases.  The procedures automatically taken care
of consist of updating the version field of a package source using the
current time-stamp, generating its tar archive if multi-file, and
uploading the results to a specified ELPA directory, while deleting
any previous version of the same package already deployed.

### Direct link to the package repository

https://github.com/oitofelix/elpa-deploy

### Your association with the package

I’m the original author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- you've probably seen my other lint checks.  For this one the only thing I'm seeing on an automated first pass is this one:

- elpa-deploy.el#L10: Use `Version` instead of `Package-Version` (MELPA automatically adds `Package-Version`)

I need to check the documentation around this one, so it may not even be your fault. :)

**Comment by oitofelix** [comment]
Hello Chris,

Chris Rayner <notifications@github.com> writes:

>   • elpa-deploy.el#L10: Use Version instead of Package-Version (MELPA automatically adds Package-Version)

This has been fixed.

Thank you!

-- 
 88888  FFFFF Bruno Félix Rezende Ribeiro (oitofelix) [0x28D618AF]
 8   8  F     http://oitofelix.freeshell.org/
 88888  FFFF  mailto:oitofelix@gnu.org
 8   8  F     irc://chat.freenode.org/oitofelix
 88888  F     xmpp://oitofelix@riseup.net

**Comment by riscy** [comment]
Hi!  You opened this PR before some recent updates to `package-lint`, which will tell you that you need to depend on Emacs 24.4.  It's a small change, and I was considering grandfathering it in, but it's also a very easy change to make.

Another small thing I notice is that you use unicode in some of the strings you display to users (e.g. `Package definition file ‘%s’ doesn’t exist`).  For usability purposes and for those who might be stuck on simpler terminals, it may be worth converting those to ASCII, but your call.

PIng me when you have `;; Package-Requires: ((emacs "24.4") (f "0.0"))` and we should be all set!

**Comment by oitofelix** [comment]
Hi Chris,


Chris Rayner <notifications@github.com> writes:

> PIng me when you have ;; Package-Requires: ((emacs "24.4") (f "0.0"))
> and we should be all set!

Done.


> Another small thing I notice is that you use unicode in some of the
> strings you display to users (e.g. Package definition file ‘%s’
> doesn’t exist). For usability purposes and for those who might be
> stuck on simpler terminals, it may be worth converting those to ASCII,
> but your call.

I’d prefer to make that change once the first user in those
circumstances complain about it.


Thanks!

-- 
Bruno Félix Rezende Ribeiro (oitofelix) [0x28D618AF]
<http://oitofelix.freeshell.org/>

**Comment by riscy** [comment]
Great, thanks!

**Pull request merged**
