### PR TITLE
Add recipe for ivy-xcdoc

### PR DESCRIPTION
**Pull request by hex2010**
ivy-xcdoc provide functions to search Xcode documents with ivy interface.

### CODE REVIEW

**Comment by hex2010** [comment]
I wrote this package, please let me know if any issues.

**Comment by hex2010** [comment]
direct url: https://github.com/hex2010/emacs-ivy-xcdoc

don't know if it is issues error 255:
```
$ make recipes/ivy-xcdoc 
End of file during parsing
 • Building recipe ivy-xcdoc ...
emacs --no-site-file --batch -l package-build/package-build.el --eval "(let ((package-build-stable nil) (package-build-write-melpa-badge-images t) (package-build-archive-dir (expand-file-name \"./packages\" package-build--melpa-base))) (package-build-archive 'ivy-xcdoc))"
End of file during parsing
make: [recipes/ivy-xcdoc] Error 255 (ignored)
ls: ./packages/ivy-xcdoc-*: No such file or directory
 ✓ Wrote  
 Sleeping for 0 ...
sleep 0

```

**Comment by syohex** [comment]
`eww` was introduced at Emacs 24.4. However minimum emacs version of this package is 24.1. And this package with default configuration uses eww function.

**Comment by hex2010** [comment]
It's thanks to syohex that I notice eww is a new feature.
Emacs requires is updated to 24.4 .

screenshot

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
