### PR TITLE
Add recipe for company-phpactor

### PR DESCRIPTION
**Pull request by kermorgant**
### Brief summary of what the package does

company backend using [phpactor](https://github.com/phpactor/phpactor)

### Direct link to the package repository

https://github.com/emacs-php/phpactor.el

### Your association with the package

Co-author

### Relevant communications with the upstream package maintainer

 **None needed** 

### Checklist

- [ ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. This is missing a `Package-Requires` dependency on `phpactor`, which it `require`s.

**Comment by kermorgant** [comment]
Thanks for the review. Package-Requires dependency on phpactor is now added.

**Comment by purcell** [comment]
Excellent, merging now, thanks. You might like to drop the use of `cl-lib` and its dependency, since `pcase` should be available in Emacs 24.3 as a built-in, and can be used much like `cl-case`.

**Comment by purcell** [comment]
Also: welcome to MELPA! :tada:

**Pull request merged**
