### PR TITLE
adding recipe for kubernetes-helm

### PR DESCRIPTION
**Pull request by abrochard**
### Brief summary of what the package does

Provides utility functions to interact with Helm (https://helm.sh/), the kubernetes package manager.

### Direct link to the package repository

https://github.com/abrochard/kubernetes-helm

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. A couple of quick notes:

- Don't build command lines with `concat` if you can avoid it: prefer Emacs process functions which accept an array of arguments, so that you do not have issues with special characters (including spaces) in file/directory names, for example. At the very least, here you would have to use `shell-quote-argument` to make the `directory` arguments safe.
- Adding `&` to the command and using `shell-command` is hacky: that function is made for interactive use, and here it would be better to use the functionality in `compile.el`, or to call something like `start-process` directly.
- Prefer `(unless x y)` to `(if (not x) y)`: generally, prefer `when` and `unless` to `if` in cases where there is only one branch.
- Typo: "teh"
- "Emacs utility functions and bindings for" can just be "Commands for". ("Emacs" is redundant in any case, since all elisp is for Emacs. :smile:)

Hope that helps!

**Comment by abrochard** [comment]
Hi @purcell , thank you so much for the feedback! As always, it's greatly appreciated.
I'm on vacation right now, but I will tackle these as soon as I'm back. I believe that my (other PR)[https://github.com/melpa/melpa/pull/5873] suffers from the same flaws. I will update that one too.
Wishing you happy holidays!

**Comment by purcell** [comment]
Merged now, thanks for your patience, and sorry for the slow turnaround!

**Comment by abrochard** [comment]
Thank you! No worries!

**Pull request merged**
