### PR TITLE
Wsl

### PR DESCRIPTION
**Pull request by m0smith**
### Brief summary of what the package does

Integrate Windows native EMACS with Windows Subsystem for Linux

### Direct link to the package repository

https://github.com/m0smith/wsl-el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Apologies for the extremely long turnaround.  Here's a quick pass --

### wsl.el ###

byte-compile (using Emacs 27.1):
```
wsl.el:101:1:Warning: Unused lexical argument `wsl-exe'
wsl.el:120:1:Warning: Unused lexical argument `wsl-exe'
wsl.el:135:1:Warning: Unused lexical argument `wsl-exe'
wsl.el:137:35:Warning: reference to free variable `wsl-exe'
wsl.el:137:43:Warning: reference to free variable `archive-zip-extract'
wsl.el:137:43:Warning: assignment to free variable `archive-zip-extract'
wsl.el:137:64:Error: Invalid read syntax: ")"
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
wsl.el:59: First sentence should end with punctuation
Warning (emacs): 
wsl.el:68: First sentence should end with punctuation
Warning (emacs): 
wsl.el:73: First sentence should end with punctuation
Warning (emacs): 
wsl.el:87: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:92: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:102: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:106: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:115: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:121: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:124: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:133: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:136: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:140: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:153: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:160: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:171: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:185: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:193: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:204: All variables and subroutines might as well have a documentation string
```

package-lint (using version 20200906.512):
```
11 issues found:
92:3: error: You should depend on (emacs "25.1") or the seq package if you need `seq-let'.
95:5: error: You should depend on (emacs "25.1") or the seq package if you need `seq-let'.
96:7: error: You should depend on (emacs "25.1") or the seq package if you need `seq-let'.
116:3: error: You should depend on (emacs "25.1") if you need `when-let'.
118:2: warning: Closing parens should not be wrapped onto new lines.
124:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
140:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
162:1: warning: Closing parens should not be wrapped onto new lines.
179:6: warning: Closing parens should not be wrapped onto new lines.
181:2: warning: Closing parens should not be wrapped onto new lines.
201:2: warning: Closing parens should not be wrapped onto new lines.
```

Other possible lints:
- wsl.el#L102: It's safer to sharp-quote function names; use `#'`

### Loadability ###

Verifying ability to #'load each file:
```
Loading wsl.el
wsl.el:Error: Emacs 27.1 errored during load
Done.
```

**Comment by m0smith** [comment]
Thanks.  It passed when I submitted it but I got lazy.  I'll clean it up with my next commit.
I am, truly and sincerely,
your friend and well-wisher,



Matthew O. Smith
Remember:  We Need Congressional Term Limits #wnctl
* Author of "Ferocious Flirting: Making Marriage Wonderful" - https://amzn.to/2skFm2L* Blog: http://www.ferociousflirting.com
* Software Ninja - http://www.software-ninja.com* The $25.00 Investor - https://25dollarinvestor.blogspot.com/
 

    On Saturday, December 12, 2020, 11:51:35 AM MST, Chris Rayner <notifications@github.com> wrote:  
 
 


Apologies for the extremely long turnaround. Here's a quick pass --

wsl.el

byte-compile (using Emacs 27.1):
wsl.el:101:1:Warning: Unused lexical argument `wsl-exe'
wsl.el:120:1:Warning: Unused lexical argument `wsl-exe'
wsl.el:135:1:Warning: Unused lexical argument `wsl-exe'
wsl.el:137:35:Warning: reference to free variable `wsl-exe'
wsl.el:137:43:Warning: reference to free variable `archive-zip-extract'
wsl.el:137:43:Warning: assignment to free variable `archive-zip-extract'
wsl.el:137:64:Error: Invalid read syntax: ")"

checkdoc (using version 0.6.2):
Warning (emacs): 
wsl.el:59: First sentence should end with punctuation
Warning (emacs): 
wsl.el:68: First sentence should end with punctuation
Warning (emacs): 
wsl.el:73: First sentence should end with punctuation
Warning (emacs): 
wsl.el:87: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:92: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:102: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:106: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:115: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:121: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:124: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:133: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:136: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:140: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:153: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:160: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:171: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:185: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:193: All variables and subroutines might as well have a documentation string
Warning (emacs): 
wsl.el:204: All variables and subroutines might as well have a documentation string

package-lint (using version 20200906.512):
11 issues found:
92:3: error: You should depend on (emacs "25.1") or the seq package if you need `seq-let'.
95:5: error: You should depend on (emacs "25.1") or the seq package if you need `seq-let'.
96:7: error: You should depend on (emacs "25.1") or the seq package if you need `seq-let'.
116:3: error: You should depend on (emacs "25.1") if you need `when-let'.
118:2: warning: Closing parens should not be wrapped onto new lines.
124:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
140:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
162:1: warning: Closing parens should not be wrapped onto new lines.
179:6: warning: Closing parens should not be wrapped onto new lines.
181:2: warning: Closing parens should not be wrapped onto new lines.
201:2: warning: Closing parens should not be wrapped onto new lines.

Other possible lints:
   
   - wsl.el#L102: It's safer to sharp-quote function names; use #'

Loadability

Verifying ability to #'load each file:
Loading wsl.el
wsl.el:Error: Emacs 27.1 errored during load
Done.

**Comment by riscy** [comment]
Thanks, feel free to ping here when you're ready.

**Comment by riscy** [comment]
This one is approaching a year, so I'm going to close for now.  But you can always reopen or make a new PR in the future!

**Pull request closed without merging**
