### PR TITLE
Add recipe for perject

### PR DESCRIPTION
**Pull request by overideal**
### Brief summary of what the package does

An Emacs package for working with projects 

### Direct link to the package repository

https://github.com/overideal/perject

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`perject-consult.el` with byte-compile using Emacs 28.1:
```
perject-consult.el:16:1: Error: Cannot open load file: No such file or directory, consult
```

`perject-tab.el` with byte-compile using Emacs 28.1:
```
perject-tab.el:504:68: Warning: the function `cl-constantly' is not known to
    be defined.
```

`perject-transient.el` with package-lint 20221003.1636:
```
8 issues found:
17:10: error: You should depend on (emacs "28.1") or the transient package if you need `transient'.
225:1: error: You should depend on (emacs "28.1") or the transient package if you need `transient-define-prefix'.
260:1: error: You should depend on (emacs "28.1") or the transient package if you need `transient-define-prefix'.
297:1: error: You should depend on (emacs "28.1") or the transient package if you need `transient-define-prefix'.
360:1: error: You should depend on (emacs "28.1") or the transient package if you need `transient-define-prefix'.
387:1: error: You should depend on (emacs "28.1") or the transient package if you need `transient-define-prefix'.
471:3: error: You should depend on (emacs "28.1") or the transient package if you need `transient-setup'.
487:3: error: You should depend on (emacs "28.1") or the transient package if you need `transient-setup'.
```
I'd just recommend putting Emacs 28.1 in your Package-Requires here.

`perject.el` with byte-compile using Emacs 28.1:
```
perject.el:113:34: Warning: reference to free variable
    `savehist-additional-variables'
perject.el:113:34: Warning: assignment to free variable
    `savehist-additional-variables'
In perject--desktop-info:
perject.el:1971:35: Warning: reference to free variable
    `desktop-buffer-ok-count'
perject.el:1972:35: Warning: reference to free variable
    `desktop-buffer-fail-count'
In end of data:
perject.el:1677:88: Warning: the function `perject-tab-tabs' is not known to
    be defined.
perject.el:1613:75: Warning: the function `perject-tab-collection-tabs' is not
    known to be defined.
```

`perject.el` with checkdoc 0.6.2:
```
perject.el:1634: Argument `prompt' should appear (as PROMPT) in the doc string
perject.el:1752: Argument `event' should appear (as EVENT) in the doc string
perject.el:1779: Argument `value' should appear (as VALUE) in the doc string
perject.el:1783: Argument `value' should appear (as VALUE) in the doc string
```

`perject.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- perject.el#L1438: It's safer to sharp-quote function names; use `#'`
- perject.el#L1444: It's safer to sharp-quote function names; use `#'`
```

Package and license:
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to perject-consult.el
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to perject-ibuffer.el
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to perject-tab.el
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to perject-transient.el

**Comment by overideal** [comment]
Thanks for your answer. I have a couple of comments/questions:
1. I have a Author, Version, Package-Requires etc. block within the main file perject.el. Do I also need it for the other files?
2. Related to this: Do I need a package-requires block within perject-consult to fix the first byte-compilation warning? I don't wanna make consult a strict requirement of the main package, since only the optional module perject-consult depends on it.
3. Also related: How do I specify that transient (or Emacs 28.1+) is required for perject-transient?
4. About the other byte compilation errors. In my opinion they are not valid. All the "free variables" are defined within other packages and the same holds true for the two perject-tab-* functions. What should I do there?
5. Regarding checkdoc: The PROMPT argument is referenced indirectly (by reference to another function) and I don't really know what to write for the other three arguments. Do you have a suggestion?
6. Do I have to put the license into every file? It seems a bit redundant to me, since it is already in the main one.

**Comment by riscy** [comment]
1. Version, author, copyright, and license should be in every file.  But it is best to have package-requires in only one file, because we have repeatedly seen authors in the past with the mistaken belief that package-requires has an effect in files other than your main file (it doesn't).
2. You can make perject-consult a standalone package with a dependency on consult (this is what I would do) or you can adjust your code so that the byte-compiler doesn't yell at users who don't have consult installed; both are acceptable
3. Adjust the versions in the package-requires of your main file (perject.el)
4. I'll take `savehist-additional-variables` for example; to solve this, just `(require 'savehist)` at the top of your file, and the byte-compiler won't complain because it will know the variable has been declared somewhere.  But for byte-compile errors like `perject.el:1677:88: Warning: the function 'perject-tab-tabs' is not known to be defined.` you'd need to adjust your dependency tree, or use forward declarations
5. These are minor; I won't insist.  But you can fix them by writing something like "PROMPT, PREDICATE, ... are the same as for ..."
6. Yes

**Comment by overideal** [comment]
I addressed your recommendations in the latest commit. Thanks for the help!

**Comment by riscy** [comment]
Thanks!  Merging.

**Pull request merged**
