### PR TITLE
Add tsort

### PR DESCRIPTION
**Pull request by ehawkvu**
### Brief summary of what the package does

An implementation of topological sort using Kahn's algorithm.

### Direct link to the package repository

https://github.com/ehawkvu/tsort.el

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None Needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

* No byte-compile errors 🎉 

`tsort.el` with checkdoc (0.6.2)

```
No issues found.
```

`tsort.el` with package-lint (20230905.629)

```
No issues found.
```

Package and license:

- MIT

**Comment by riscy** [comment]
Thanks for this, @ehawkvu (and thank you for splitting this algo out into its own dependency) - @jcs090218 is correct that your repo is detectably licensed as MIT, but in your source file you have:
```elisp
;; License: MIT
```
but you should use *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/); these are machine detectable and unambiguous, whereas "License: MIT" is not necessarily.

**Comment by ehawkvu** [comment]
@riscy Issue should be fixed! For future reference, if I were to add an additional file (such as `tsort-contrib.el`) which contains some extra methods/functions, such as parsing text that tsort(1) would be able to take, should I make that a separate package or would it be fine to include in this package as well?

**Comment by riscy** [comment]
Looks good - thanks.

> if I were to add an additional file (such as tsort-contrib.el) 

Yes, this is totally fine and since you're using the default recipe, your package can easily grow to accommodate multiple files.  Just make sure you're following the prefix rules (every file starts with tsort-) and you're set.

Merging - and, welcome to MELPA. :)

**Pull request merged**
