### PR TITLE
Add `streak` package

### PR DESCRIPTION
**Pull request by fosskers**
### Brief summary of what the package does

This package provides `streak-mode`, a minor mode for tracking a daily streak, say for exercising, language learning, or otherwise. Displays your current record in the mode line.

### Direct link to the package repository

https://github.com/fosskers/streak

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

Here is a little feedback:

* Rather than defining symbols with constants for the number of seconds in a day, etc, i would just write those numbers into the code where needed.  The fewer symbols added by a package, the better.
* You should have a `defgroup`, and then your `defcustom` can omit the `:group`.
* You probably want to use `expand-file-name` against `~` rather than `substitute-in-file-name` with `$HOME`.  (You might also want to use XDG-dir-related functions in newer Emacs versions.)
* `streak--buffer-first-line` and `streak--tomorrow` are other examples of functions that probably doesn't need to be named functions.  I would just inline them in the places where called.
* At the bottom you do `(add-hook 'streak-mode-on-hook #'streak--show-streak-in-modeline)`, but no such hook variable is defined.  As well, merely loading a package shouldn't modify hooks.  You should probably use the minor mode's body forms to do the necessary bookkeeping when the mode is enabled or disabled.

BTW, have you considered tracking multiple streaks?  Also, it would be helpful to users if you showed a screenshot and contrasted this with Org Habits.

**Comment by fosskers** [comment]
Thank you for the feedback! Yes it occurred to me that there are several patterns here that aren't XDG or Windows compliant, so I can change those areas to be more general.

I'll take a look at the private functions you mentioned to see if I should inline them. I probably kept them all separate for my own internal bookkeeping purposes. 

I believe `streak-mode-on-hook` is automatically created by `define-minor-mode`, no?

And yes, I'd love to be able to track multiple streaks. I've been thinking of a way to do that since last night. Namely, `completing-read` could be use to `streak-reset` only the particular one you've chosen. And then the user could easily define their own streaks in their own config, with custom labels (and icons, etc).

**Comment by alphapapa** [comment]
> I believe `streak-mode-on-hook` is automatically created by `define-minor-mode`, no?

Not according to the docstring or the manual, that I can see.  Maybe you're thinking of `MODE-hook`, i.e. `streak-mode-hook`.  Anyway, adding that function to the mode's hook won't remove it from the mode line when the mode is disabled.  The idiomatic way to handle this is to put a form like `(if streak-mode (progn ENABLE-FORM ...) DISABLE-FORM ...)` in the mode definition's body.

**Comment by fosskers** [comment]
Thank you, I'll fix that.

**Comment by fosskers** [comment]
Alright! Following your suggestions I've:

- [x] Adopted `xdg` for more portable calculation of directories
- [x] Implemented proper mode deactivation
- [x] Removed certain symbols to avoid cluttering the namespace
- [x] Improved documentation

**Comment by alphapapa** [comment]
Thanks.  A couple other points:

* FYI, `file-name-concat` appears to be new in Emacs 28.  If you're targeting Emacs 27, you should probably use `expand-file-name`.  See https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Name-Expansion.html

>  Implemented proper mode deactivation Removed certain symbols to avoid cluttering the namespace

* Having activated `super-nitpick-mode`, you might consider inlining the `streak--hide-streak-in-modeline` and `streak--show-streak-in-modeline` functions; since they are so short and only called in the mode's body, that kind of code is usually inlined in it.

**Comment by fosskers** [comment]
> FYI, file-name-concat appears to be new in Emacs 28

Ah didn't notice, I can use `concat` easily enough here.

> you might consider inlining

Sure, I'll do that.

**Comment by alphapapa** [comment]
> Ah didn't notice, I can use `concat` easily enough here.

You could, and many people do, but AFAIK `expand-file-name` is the more appropriate way, i.e. `(expand-file-name "streak" (xdg-cache-home))`.

**Comment by fosskers** [comment]
All fixed!

**Comment by riscy** [comment]
Thanks for this -- looks handy -- and thanks for your close adherence to the checklist.  Here's some feedback:

- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to streak.el (this is the big one)
- `streak-set` has (in my opinion) an unfriendly interactive interface unless one happens to have epoch time memorized -- personally I'd drop the interactive part, but that's not a blocker
- Mode-line real estate is extremely valuable (think about e.g. laptop users with 80 columns of space); in light of that I'd strongly suggest shortening and/or making customizable the default renderings and only adding spaces where you need to, e.g. (`" Streak Starts Tomorrow "` -> `" s:0"`, `" 10 Hours `" -> `" streak:10h"` or something similar)

**Comment by fosskers** [comment]
Thank you for the feedback!

Okay I'll figure out that license header.

Funny, I don't even advertise `streak-set` in my README, so I probably never intended it to really be `interactive`. I'll make the change.

A customizable streak display is also a great idea, I could probably implement it as a format string as accepted by `(format ...)`, then users are free to do what they like. Thoughts?

**Comment by fosskers** [comment]
Alright, I've made all the changes.

**Comment by riscy** [comment]
Yeah, that sounds like a good idea to me.

**Comment by fosskers** [comment]
Should be good to go now, please let me know if there are any other improvements I can make.

**Comment by riscy** [comment]
Great thanks!  And, welcome to MELPA. :)

**Comment by fosskers** [comment]
It's an honour :) Thanks for including `streak`.

**Pull request merged**
