### PR TITLE
Add recipe for sequed

### PR DESCRIPTION
**Pull request by brannala**
### Brief summary of what the package does

Package presents a bioinformatics environment for viewing DNA sequence alignments with color-coded bases and quickly navigating sequence by base position. It works with alignments in fasta format which I can provide upon request for evaluating the program. It also allows sequences to be exported in a different format for phylogenetic analysis.

### Direct link to the package repository

https://github.com/brannala/sequed

### Your association with the package

Developer/Maintainer

### Checklist

Please confirm with `x`:

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [ x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x] My elisp byte-compiles cleanly
- [ x] `M-x checkdoc` is happy with my docstrings
- [ x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- quick first pass.

package-lint (using version 20210127.158):
```
2 issues found:
86:3: error: You should depend on (emacs "25.1") if you need `font-lock-ensure'.
116:3: error: You should depend on (emacs "25.1") if you need `font-lock-ensure'.
```

Other [lints](https://github.com/riscy/melpazoid):
- sequed.el#L157: It's safer to sharp-quote function names; use `#'`
- sequed.el#L204: It's safer to sharp-quote function names; use `#'`
- sequed.el#L222: Single-line comments should usually begin with `;;`
- sequed.el#L73: Double-check the documentation for `define-derived-mode` -- there's no need to set the major mode when using `define-derived-mode`, or the mode-name (I notice you're putting a docstring comment where the mode name would normally go), or to explicitly set keymaps.
- sequed.el#L63: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- sequed.el#L64: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- sequed.el#L96: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`



- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by brannala** [comment]
Thanks for flagging these issues. Your recommended changes have been made and pushed.

**Comment by riscy** [comment]
Thanks very much.   I see a top level define-key persists on line 64 and 91.  The reason we should avoid calling `define-key` at the top level is that users may customize that keymap _before_ your package is loaded, and this will silently undo their work.

Taking a closer look into the code, I think the font-locking that occurs when `sequed-mkaln` is called is a bit convoluted; It feels like it would be more straightforward and far more efficient to define another major mode with syntax coloring defined over `a c g t`, rather than slipping in a call to `(font-lock-mode -1)` and manually walking a cursor through the buffer to colorize characters.

**Comment by brannala** [comment]
Thanks. I placed the remaining top-level define-key statements into the let block. The font-lock-defaults variable is now used to define base coloring in sequed-aln-mode.

**Comment by riscy** [comment]
Thanks, this looks good.  A couple more non-blockers that I failed to notice.  I'll leave them here fyi -

```elisp
(defvar sequed-label-length)
(defvar sequed-seq-length)
(defvar sequed-noseqs)
```
First, I think these only ever apply to one buffer but it may be safer going forward to use `defvar-local` on these, in case you ever want to support multiple view buffers.  Using `defvar-local` will force you to also declare a default value of `nil`.

You also use `error` in many places, but you should be sure this is what you mean, and not `user-error`.  `error` will tend to open a backtrace, and you probably don't want to fling that at the user for errors like "Not a fasta file" or even "Attempt to move outside sequence".

You can make it easier for others to inspect your code by breaking your lines at something a little narrower (I'm thinking of `sequed-color-labels` as I write this).

As always make sure you re-run the checks after making these changes, but this looks good to go.  Thanks!

**Comment by brannala** [comment]
Thanks for all the helpful recommendations which I will implement.

**Pull request merged**
