### PR TITLE
New package recipe - meghanada

### PR DESCRIPTION
**Pull request by mopemope**
- Summary: A Better Java Development Environment for Emacs
- Link: https://github.com/mopemope/meghanada-emacs
- Association: I am the author

### CODE REVIEW

**Comment by syohex** [comment]
- Missing `cl-lib` and `yasnippet` dependencies
- Use `cl-lib` instead of `cl` in company-meghanada.el
- Load `thingatpt` in company-meghanada.el for using its functions
- Please check byte-compile warnings

**Comment by mopemope** [comment]
@syohex Thanks for the feedback. I have fixed the issues.

**Comment by syohex** [comment]
- [Here](https://github.com/mopemope/meghanada-emacs/blob/ed58774879763c873ccbcc059ee09dee4a51a035/company-meghanada.el#L201) should be `cl-case`

**Comment by mopemope** [comment]
@syohex I have fixed it . Thanks.

**Comment by syohex** [comment]
- https://github.com/mopemope/meghanada-emacs/blob/ed58774879763c873ccbcc059ee09dee4a51a035/meghanada.el#L142

Please use `make-directory` function instead of `mkdir`. Non Unix platform does not have `mkdir` command.

- I suppose `~/.emacs.d/meghanada` is preferable to `~/.meghanada`
- You need not to write package header in every files. It is enough in meghanada.el

**Comment by mopemope** [comment]
@syohex Please take another look at the commit. Thanks

**Comment by syohex** [comment]
I apologize to you for my lack of clarity. 

> I suppose ~/.emacs.d/meghanada is preferable to ~/.meghanada

 Please use `locate-user-emacs-file` function or `user-emacs-directory` instead of using `~/.emacs.d` directory.

> Please use make-directory function instead of mkdir. Non Unix platform does not have mkdir command.

Please set second argument `parent` of `make-directory`. It is same as `mkdir -p`.

**Comment by mopemope** [comment]
@syohex Thank you for your advice. PTAL the commit.
Is this OK ?

**Comment by syohex** [comment]
- mode-line string should start with space. Screenshot is here

--

a

--

- Does server program work without any configurations ?

I got null pointer exception by running server program.

```
% java -jar ~/.emacs.d/meghanada/meghanada.jar
Exception in thread "main" java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at java.util.Properties.setProperty(Properties.java:166)
	at java.lang.System.setProperty(System.java:796)
	at meghanada.Main.main(Main.java:35)
```

**Comment by mopemope** [comment]
@syohex I have fixed a modeline-string. see https://github.com/mopemope/meghanada-emacs/commit/96e5df1c5c965afa1a9d9d7c514e180433549cd9

and fixed server problem (see https://github.com/mopemope/meghanada-server/issues/2)

Please try again `M-x meghanada-install-server`.

**Comment by syohex** [comment]
I have send PR(https://github.com/mopemope/meghanada-emacs/pull/7)

**Comment by syohex** [comment]
It looks errors were gone

**Comment by mopemope** [comment]
@syohex Merged. Thanks!!!

**Comment by syohex** [comment]
Merged.

**Pull request merged**
