### PR TITLE
This package is renamed.

### PR DESCRIPTION
**Pull request by stardiviner**
Do I need other way to mark old package is renamed?

https://github.com/stardiviner/eldoc-overlay

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by stardiviner** [comment]
@milkypostman Done. Thanks.

**Comment by stardiviner** [comment]
@milkypostman I'v renamed my package and files to `eldoc-overlay` finished. Can merge this PR now. Thanks, sorry for the disturb.

**Comment by tarsius** [comment]
You also have to rename the occurrence of `eldoc-overlay-mode` *inside* the recipe.

**Comment by milkypostman** [comment]
I think it’s done.

**Comment by milkypostman** [comment]
Can’t merge cause the test is failing. Will have to look later.

**Comment by milkypostman** [comment]
Oh I see the problem. The file inside the repo needs to be renamed to match the package name. So in your repo you need to rename eldoc-overlay-mode.el to eldoc-overlay.el

Then rerun the Travis test

**Comment by stardiviner** [comment]
I have done in-file renaming: https://github.com/stardiviner/eldoc-overlay/blob/master/eldoc-overlay.el

Guess this is because of CI delay update.

**Comment by milkypostman** [comment]
Restarted the job. Sorry I didn’t realize I wasn’t logged in so I thought the mobile Travis wouldn’t let me rerun it.

**Comment by stardiviner** [comment]
@milkypostman CI passed test. I think there is no question now. can be merged.

**Pull request merged**
