### PR TITLE
add: diffpdf, transient UI for diffpdf

### PR DESCRIPTION
**Pull request by ShuguangSun**
### Brief summary of what the package does

A transient UI for diffpdf (external program to diff pdf files).

### Direct link to the package repository

https://github.com/ShuguangSun/diffpdf.el

### Your association with the package

I'm the author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

byte-compile (using Emacs 27.1):
```
diffpdf.el:127:1:Warning: the function `dired-get-marked-files' is not known
    to be defined.
```
I believe you just need to `(require 'dired)` for this.

I believe this defcustom is malformed:
```
(defcustom diffpdf-program (executable-find "diffpdf")
  "Program of diffpdf."
  :group 'diffpdf
  :type (string :tag "Path to diffpdf"))
```
and throws an error when Emacs tries to load the file.  Should that be `:type 'string :tag "Path to diffpdf"`?

**Comment by ShuguangSun** [comment]
Fixed. Thanks for the findings.

**Comment by riscy** [comment]
Thanks, that puts the checklist behind us.

On a very quick glance it appears the defcustom is still malformed, although your change does improve things so that Emacs can actually load the file.  Instead of:
```elisp
(defcustom diffpdf-program (executable-find "ls")
  "Program of diffpdf."
  :group 'diffpdf
  :type '(string :tag "Path to diffpdf"))
```
you want
```elisp
(defcustom diffpdf-program (executable-find "ls")
  "Program of diffpdf."
  :group 'diffpdf
  :type 'string
  :tag "Path to diffpdf")
```
although I would only recommend using `:tag` in `defcustoms` in rare cases -- I don't think this usage adds much.

Another issue I'm noticing is that in `diffpdf--command` you're going through each file and surrounding it with quotation marks, but I wonder if `shell-quote-argument` achieves the same thing.  This would also make you able to handle e.g. files with ``` ` ``` in them, and other special characters that will be directly interpreted by the shell.  The same goes for the ARGS argument to that function -- it should probably use `shell-quote-argument` too.

**Comment by ShuguangSun** [comment]
Thanks for the careful review. I updated it accordingly, and also fix a bug introduced come along with the new version of transient. Now it works as expected.

**Comment by riscy** [comment]
Thanks, that's looking better and this is looking close.  You probably want to use `shell-quote-argument` on `args` as well, so instead of `(string-join args " ")` I believe you could do `(mapconcat #'shell-quote-argument args " ")`.

Also, I apologize for the number of round trips, but I see one more issue: if `diffpdf` isn't found, `diffpdf-program` will be nil.  `concat` turns nils into the empty string, so `(concat diffpdf-program " " arguments " " ...` tries to execute the args directly as a shell command, which will give confusing error messages to users in the best case, so you should definitely check that `diffpdf-program` is non-nil.

**Comment by ShuguangSun** [comment]
fix it. 

thanks for your careful review. I learned a lot.

**Comment by riscy** [comment]
I think you still haven't used `shell-quote-argument` on `args` as I mentioned above, but perhaps since those come directly from transient they're "safe".  Still might be a good idea to do so for safety.

This is minor, but `(error "`diffpdf-program' is not defined or not in the PATH.")` should probably be a `user-error` intead, since the former will expose a backtrace probably unnecessarily.  That's not a blocker though -- look good to merge.

**Pull request merged**
