### PR TITLE
Add recipe for ruby-json-to-hash

### PR DESCRIPTION
**Pull request by otavioschwanck**
### Brief summary of what the package does

Convert JSON to Hash and play with the keys

### Direct link to the package repository

https://github.com/otavioschwanck/ruby-json-to-hash.el

### Your association with the package

maintainer

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Just as a heads up, I try to focus on one PR per contributor at a time, but I'll leave a (very) quick first pass here --

package-lint (using version 20211107.1614):
```
1 issue found:
9:38: warning: Use a non-snapshot version number for dependency on "smartparens" if possible.
```
It looks like the latest non-snapshot version is 1.11.0 for https://stable.melpa.org/#/smartparens

Other [lints](https://github.com/riscy/melpazoid):
- ruby-json-to-hash.el#L182: `concat` may be unneeded; `insert` can take multiple arguments
- ruby-json-to-hash.el#L197: `concat` may be unneeded; `insert` can take multiple arguments
- ruby-json-to-hash.el#L205: `concat` may be unneeded; `insert` can take multiple arguments

**Comment by otavioschwanck** [comment]
> 1.11.0

@riscy changes made!

**Comment by riscy** [comment]
Thanks!  I apologize for missing this earlier, but it looks like there's a license mismatch: the repo is MIT licensed, but the file itself has GPL boilerplate.  I also mentioned this when merging rails-routes #7754 but it looks like it hasn't been fixed there yet too -- fyi.

**Comment by otavioschwanck** [comment]
> Thanks! I apologize for missing this earlier, but it looks like there's a license mismatch: the repo is MIT licensed, but the file itself has GPL boilerplate. I also mentioned this when merging rails-routes #7754 but it looks like it hasn't been fixed there yet too -- fyi.

Sorry about that, fixed on my three projects!

**Comment by riscy** [comment]
Thanks!  Merging this.

**Pull request merged**
