### PR TITLE
Revert "Revert "Update recipe for evil""

### PR DESCRIPTION
**Pull request by milkypostman**
Reverts melpa/melpa#4517

### CODE REVIEW

**Comment by milkypostman** [comment]
@agsdot sorry for the flip flop. i realized my excitement got the better of me

is there a public announcement from main maintainers that this will be the defacto repo?

**Comment by agsdot** [comment]
Just did a comment on [melpa/melpa#4517](https://github.com/melpa/melpa/pull/4517).

**Comment by milkypostman** [comment]
@agsdot lets let @purcell sign off on this. I am sorry for the hassle but I do not normally commit package changes that much, but this sparked my interest as a user. i'm sure it's fine but out of respect I prefer if someone else takes a look too. Or even @syohex 

I think that this is a really good move for the evil / emacs community. so i am in full support and if we don't hear anything in 48 hours i'll merge anyways.

**Comment by agsdot** [comment]
@milkypostman , sounds good.

Just found this post [Project status #737](https://github.com/emacs-evil/evil/issues/737).

And also @syohex [tweet](https://twitter.com/syohex/status/821908380012818432)!

Yes, awaiting confirmation from @purcell and @syohex is a good move.

**Comment by syohex** [comment]
Looks good.

**Comment by agsdot** [comment]
Thanks @syohex . Also, @milkypostman , found this [diff](https://bitbucket.org/lyro/evil/wiki/commits/3d2bb60e9d8bf33657fdff646b99a2b412bc5650#chg-Home.wiki) on the wiki history for [lyro/evil](https://bitbucket.org/lyro/evil), made by Frank Fischer himself:

"The Evil project migrated to {{https://github.com/emacs-evil/evil|its new location at github}}."

**Comment by milkypostman** [comment]
in that case we can merge

**Pull request merged**
