### PR TITLE
Add face-explorer

### PR DESCRIPTION
**Pull request by Lindydancer**
### Brief summary of what the package does

Library and tools for faces and text properties

This library is useful for packages that convert syntax highlighted buffers to other formats.  The functions can be used to determine how a face or a face text property looks, in terms of primitive face attributes (e.g. foreground and background colors).  Two sets of functions are provided, one for existing frames and one for fictitious displays, like 8 color tty.

In addition, a number of interactive tools for inspecting faces and face properties are included.

Future versions of "e2ansi" (a package that renders syntax highlighted buffers using ANSI sequences, which can be used to make `less` display files with syntax highlighting) will need this library.

### Direct link to the package repository

https://github.com/Lindydancer/face-explorer

### Your association with the package

I'm the author of the package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Lindydancer** [comment]
Ping!

**Comment by purcell** [comment]
Super, thanks. Sorry for the delay.

**Comment by Lindydancer** [comment]
Thanks!

    -- Anders

**Comment by kaushalmodi** [comment]
@Lindydancer Can you please add the package URL to the header too? Thanks!

**Comment by Lindydancer** [comment]
Fixed, thanks!

    -- Anders

**Pull request merged**
