### PR TITLE
Add recipe for code-review

### PR DESCRIPTION
**Pull request by wandersoncferreira**
### Brief summary of what the package does

`code-review` lets you submit code reviews from Emacs.

This work is heavily inspired by @charignon works on https://github.com/charignon/github-review with a new UI to enable support for more features.

There are also an extension point to support other forges.

### Direct link to the package repository

https://github.com/wandersoncferreira/code-review

### Your association with the package

I am the maintainer of `code-review`.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks!  This is a quick first pass, and please forgive any oversights in the byte-compile -- I'm having a bit of trouble with my setup vs. the current `forge` recipe.  Note there's a lot of verbiage here but the issues seem easy to fix:

### code-review-comment.el ###

package-lint (using version 20210528.2348):
```
9 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a Homepage or URL header.
1:0: warning: The package summary should start with an uppercase letter or a digit.
1:51: warning: You should depend on (emacs "24.1") if you need lexical-binding.
90:8: error: You should depend on (emacs "25.1") if you need `if-let'.
93:15: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
142:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
181:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
248:28: error: You should depend on (emacs "24.4") if you need `string-trim'.
```

### code-review-core.el ###

package-lint (using version 20210528.2348):
```
41 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a Homepage or URL header.
1:81: warning: You should depend on (emacs "24.1") if you need lexical-binding.
16:0: error: "code-review-pullreq-infos" doesn't start with package's prefix "code-review-core".
16:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
19:0: error: "code-review-infos-deferred" doesn't start with package's prefix "code-review-core".
19:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
22:0: error: "code-review-pullreq-diff" doesn't start with package's prefix "code-review-core".
22:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
25:0: error: "code-review-diff-deferred" doesn't start with package's prefix "code-review-core".
25:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
28:0: error: "code-review-commit-diff" doesn't start with package's prefix "code-review-core".
28:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
31:0: error: "code-review-commit-comments" doesn't start with package's prefix "code-review-core".
31:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
34:0: error: "code-review-commit-comments-deferred" doesn't start with package's prefix "code-review-core".
34:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
37:0: error: "code-review-commit-diff-deferred" doesn't start with package's prefix "code-review-core".
37:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
40:0: error: "code-review-send-review" doesn't start with package's prefix "code-review-core".
40:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
43:0: error: "code-review-send-replies" doesn't start with package's prefix "code-review-core".
43:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
46:0: error: "code-review-get-labels" doesn't start with package's prefix "code-review-core".
46:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
49:0: error: "code-review-set-labels" doesn't start with package's prefix "code-review-core".
49:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
52:0: error: "code-review-get-assignees" doesn't start with package's prefix "code-review-core".
52:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
55:0: error: "code-review-set-assignee" doesn't start with package's prefix "code-review-core".
55:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
58:0: error: "code-review-get-milestones" doesn't start with package's prefix "code-review-core".
58:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
61:0: error: "code-review-set-milestone" doesn't start with package's prefix "code-review-core".
61:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
64:0: error: "code-review-set-title" doesn't start with package's prefix "code-review-core".
64:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
67:0: error: "code-review-set-description" doesn't start with package's prefix "code-review-core".
67:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
70:0: error: "code-review-merge" doesn't start with package's prefix "code-review-core".
70:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defgeneric'.
```


### code-review-db.el ###

package-lint (using version 20210528.2348):
```
16 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a Homepage or URL header.
1:58: warning: You should depend on (emacs "24.1") if you need lexical-binding.
22:0: error: "code-review-database-connector" doesn't start with package's prefix "code-review-db".
27:0: error: "code-review-database-file" doesn't start with package's prefix "code-review-db".
35:0: error: "code-review-buffer" doesn't start with package's prefix "code-review-db".
45:0: error: "code-review-path" doesn't start with package's prefix "code-review-db".
57:0: error: "code-review-comment" doesn't start with package's prefix "code-review-db".
67:0: error: "code-review-pullreq" doesn't start with package's prefix "code-review-db".
97:0: error: "code-review-database" doesn't start with package's prefix "code-review-db".
100:0: error: "code-review--db-version" doesn't start with package's prefix "code-review-db".
108:0: error: "code-review--db-connection" doesn't start with package's prefix "code-review-db".
121:0: error: "code-review--db-table-schema" doesn't start with package's prefix "code-review-db".
181:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
184:5: error: You should depend on (emacs "24.1") if you need `pcase-dolist'.
415:3: error: You should depend on (emacs "25.1") if you need `if-let'.
```


### code-review-github.el ###

package-lint (using version 20210528.2348):
```
24 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a Homepage or URL header.
1:55: warning: You should depend on (emacs "24.1") if you need lexical-binding.
55:3: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
62:23: error: You should depend on (emacs "24.4") if you need `string-join'.
65:20: error: You should depend on (emacs "24.4") if you need `string-trim'.
66:45: error: You should depend on (emacs "24.4") if you need `string-empty-p'.
75:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
89:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
100:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
114:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
125:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
206:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
216:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
235:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
266:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
279:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
293:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
306:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
316:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
329:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
339:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
349:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
359:1: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-defmethod'.
```

Other [lints](https://github.com/riscy/melpazoid):
- code-review-github.el#L66: No `format` required; `message` takes an f-string
- code-review-github.el#L372: No `format` required; `message` takes an f-string

### code-review-section.el ###

```
Warning (emacs): 
code-review-section.el:416: Argument `orig' should appear (as ORIG) in the doc string
```

package-lint (using version 20210528.2348):
```
51 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a Homepage or URL header.
1:38: warning: You should depend on (emacs "24.1") if you need lexical-binding.
44:0: error: "code-review-full-refresh?" doesn't start with package's prefix "code-review-section".
48:0: error: "code-review-grouped-comments" doesn't start with package's prefix "code-review-section".
52:0: error: "code-review-hold-written-comment-ids" doesn't start with package's prefix "code-review-section".
56:0: error: "code-review-hold-written-comment-count" doesn't start with package's prefix "code-review-section".
64:3: error: You should depend on (emacs "25.1") if you need `when-let'.
65:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
75:3: error: You should depend on (emacs "25.1") if you need `when-let'.
76:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
84:3: error: You should depend on (emacs "25.1") if you need `when-let'.
91:3: error: You should depend on (emacs "25.1") if you need `when-let'.
98:3: error: You should depend on (emacs "25.1") if you need `when-let'.
99:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
110:3: error: You should depend on (emacs "25.1") if you need `when-let'.
111:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
112:25: error: You should depend on (emacs "24.4") if you need `string-empty-p'.
130:3: error: You should depend on (emacs "25.1") if you need `when-let'.
131:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
153:3: error: You should depend on (emacs "25.1") if you need `when-let'.
154:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
162:29: error: You should depend on (emacs "24.4") if you need `string-join'.
170:3: error: You should depend on (emacs "25.1") if you need `when-let'.
171:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
177:28: error: You should depend on (emacs "24.4") if you need `string-join'.
185:3: error: You should depend on (emacs "25.1") if you need `when-let'.
186:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
187:25: error: You should depend on (emacs "24.4") if you need `string-join'.
193:39: error: You should depend on (emacs "24.4") if you need `string-empty-p'.
208:3: error: You should depend on (emacs "25.1") if you need `when-let'.
209:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
227:3: error: You should depend on (emacs "25.1") if you need `when-let'.
228:36: error: You should depend on (emacs "24.4") if you need `string-empty-p'.
235:15: error: You should depend on (emacs "24.4") if you need `string-empty-p'.
256:3: error: You should depend on (emacs "25.1") if you need `when-let'.
257:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
264:48: error: You should depend on (emacs "24.4") if you need `string-empty-p'.
295:46: error: You should depend on (emacs "25.1") if you need `alist-get'.
307:13: error: You should depend on (emacs "24.4") if you need `add-face-text-property'.
317:26: error: You should depend on (emacs "25.1") if you need `alist-get'.
344:16: error: You should depend on (emacs "25.1") if you need `alist-get'.
386:19: error: You should depend on (emacs "24.4") if you need `add-face-text-property'.
396:19: error: You should depend on (emacs "24.4") if you need `add-face-text-property'.
406:19: error: You should depend on (emacs "24.4") if you need `add-face-text-property'.
503:25: error: You should depend on (emacs "25.1") if you need `alist-get'.
524:11: error: You should depend on (emacs "25.1") if you need `when-let'.
590:5: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
591:5: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
606:13: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
626:5: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
```

Other [lints](https://github.com/riscy/melpazoid):
- code-review-section.el#L480: No `format` required; `message` takes an f-string

### code-review-utils.el ###

package-lint (using version 20210528.2348):
```
12 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a Homepage or URL header.
1:49: warning: You should depend on (emacs "24.1") if you need lexical-binding.
61:3: error: You should depend on (emacs "25.1") if you need `alist-get'.
67:3: error: You should depend on (emacs "25.1") if you need `if-let'.
67:18: error: You should depend on (emacs "25.1") if you need `alist-get'.
73:3: error: You should depend on (emacs "24.4") if you need `string-trim'.
83:28: error: You should depend on (emacs "24.4") if you need `string-trim'.
148:3: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
214:16: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
221:16: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
282:26: error: You should depend on (emacs "25.1") if you need `alist-get'.
```


### code-review.el ###

package-lint (using version 20210528.2348):
```
10 issues found:
121:0: error: "magit-code-review-commit-section-map" doesn't start with package's prefix "code-review".
127:0: error: "magit-code-review-comment-body-section-map" doesn't start with package's prefix "code-review".
133:0: error: "magit-code-review-comment-header-section-map" doesn't start with package's prefix "code-review".
139:0: error: "magit-code-review-local-comment-section-map" doesn't start with package's prefix "code-review".
146:0: error: "magit-code-review-local-comment-header-section-map" doesn't start with package's prefix "code-review".
153:0: error: "magit-code-review-feedback-section-map" doesn't start with package's prefix "code-review".
159:0: error: "magit-code-review-feedback-header-section-map" doesn't start with package's prefix "code-review".
165:0: error: "magit-code-review-labels-section-map" doesn't start with package's prefix "code-review".
171:0: error: "magit-code-review-assignee-section-map" doesn't start with package's prefix "code-review".
177:0: error: "magit-code-review-milestone-section-map" doesn't start with package's prefix "code-review".
```

**Comment by wandersoncferreira** [comment]
Thanks for the feedback @riscy . I am pretty sure used package-lint but could not get these errors :/ anyway... they are fixed at master now however the last `magit-*-map` functions cannot be fixed because `magit-section` package relies on this pattern to create dynamic keybindings when you hover over a specific section. More info here https://magit.vc/manual/magit/Section-Types-and-Values.html

**Comment by tarsius** [comment]
> `magit-*-map` functions cannot be fixed because `magit-section` package relies on this pattern to create dynamic keybindings when you hover over a specific section. More info here https://magit.vc/manual/magit/Section-Types-and-Values.html

That information is outdated; I'll fix it soon. You should define a class for "every" section type, set its `keymap` slot and pass the class name to `magit-insert-section`. For section types that don't need a keymap and/or some other slot or customized method you can omit defining a class but should still pick a name that could later be used as the name of a class (you seem to already be doing that).

For historic reasons Magit and Forge only follow this newer convention for a handful of section types. See `magit-file-section` for an example of a section type that uses the new convention. There aren't actually any methods defined for that class, but you will find a few `magit-file-section-p`. If I were to start over there probably would be more generic functions whose behavior could be customized using section-type-specific methods.

You appear to use objects whose class derives from `closql-object` as section values. I could consider making derive from both `closql-object` *and* `magit-section`, but this would probably only complicate things. To avoid conflicts, ending the name of section classes with `-section` seems like a good idea. You should also look at `magit-section-ident` and the generic function `magit-section-ident-value` and implement methods for the latter. If you don't do that, then Magit could fail to keep the section selected when refreshing the buffer. Two objects may be non-`equal` (see `magit-get-section`) but still represent the same thing. Magit doesn't need that but see `magit-section-ident-value(forge-object)`.

**Comment by tarsius** [comment]
@riscy
/cc @purcell 

```
70:0: error: "code-review-merge" doesn't start with package's prefix "code-review-core".
```

It does not start with the *library's* prefix but it does start with **package's** prefix. I think it is perfectly okay to use the latter, otherwise one would have to rename lots of symbols when splitting a library in two, for example.

IMO we should stop encouraging that people make their symbol names longer to comply with the linter here. As I see it https://github.com/wandersoncferreira/code-review/commit/ec56204cac373a81429172b45811d06a007e7371 makes the symbol names worse. The linter should be improved, but meanwhile this can be worked around by .... hm I thought there was a header keyword such as `Package-Prefix` but I cannot find any reference to that and `package-lint--get-package-prefix` wouldn't respect it anyway (yet).

From `D.1 Emacs Lisp Coding Conventions` (emphasize mine):

>   • You should choose a short word to distinguish your program from
>     other Lisp programs.  The names of all global symbols in your
>     program, that is the names of variables, constants, and functions,
>     should begin with that chosen prefix.  Separate the prefix from the
>     rest of the name with a hyphen, ‘-’.  This practice helps avoid
>     name conflicts, since all global variables in Emacs Lisp share the
>     same name space, and all functions share another name space(1).
>     ...
>     If one prefix is insufficient, your package **can** use two or three
>     alternative common prefixes, so long as they make sense.

This says nothing about a convention of using one prefix per *library*.

**Comment by wandersoncferreira** [comment]
> @riscy /cc @purcell
> 
> ```
> 70:0: error: "code-review-merge" doesn't start with package's prefix "code-review-core".
> ```
> 
> It does not start with the _library's_ prefix but it does start with **package's** prefix. I think it is perfectly okay to use the latter, otherwise one would have to rename lots of symbols when splitting a library in two, for example.

This would be so much better IMO.

**Comment by wandersoncferreira** [comment]
> > `magit-*-map` functions cannot be fixed because `magit-section` package relies on this pattern to create dynamic keybindings when you hover over a specific section. More info here https://magit.vc/manual/magit/Section-Types-and-Values.html
> 
> That information is outdated; I'll fix it soon. You should define a class for "every" section type, set its `keymap` slot and pass the class name to `magit-insert-section`. For section types that don't need a keymap and/or some other slot or customized method you can omit defining a class but should still pick a name that could later be used as the name of a class (you seem to already be doing that).
> 
> For historic reasons Magit and Forge only follow this newer convention for a handful of section types. See `magit-file-section` for an example of a section type that uses the new convention. There aren't actually any methods defined for that class, but you will find a few `magit-file-section-p`. If I were to start over there probably would be more generic functions whose behavior could be customized using section-type-specific methods.
> 
> You appear to use objects whose class derives from `closql-object` as section values. I could consider making derive from both `closql-object` _and_ `magit-section`, but this would probably only complicate things. To avoid conflicts, ending the name of section classes with `-section` seems like a good idea. You should also look at `magit-section-ident` and the generic function `magit-section-ident-value` and implement methods for the latter. If you don't do that, then Magit could fail to keep the section selected when refreshing the buffer. Two objects may be non-`equal` (see `magit-get-section`) but still represent the same thing. Magit doesn't need that but see `magit-section-ident-value(forge-object)`.

These are great advices, I am refactoring the code to adequate to this new standard. There are a few functions that I currently dispatch using `with-slots (type) ` because I want it to work only for specific sections.. so methods attached to sections classes are the way to go here.

**Comment by riscy** [comment]
Sorry, I just realized I was spewing false positives regarding the prefixes above.  Please disregard -- it's the package prefix that is important.  I had to do things a little more manually because of the aforementioned difficulty installing that one recipe, and neglected to set package-lint-main-file.

**Comment by riscy** [comment]
Here's the fixed messages.  Apologies again for the confusion I created. :)

byte-compile (using Emacs 27.1):
```
code-review-comment.el:308:46:Warning: reference to free variable
    `code-review-commit-buffer-name'
```

byte-compile (using Emacs 27.1):
```
code-review-section.el:735:1:Warning: the following functions are not known to
    be defined: code-review-comment-make-group, code-review-commit-minor-mode,
    code-review-mode
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
code-review-section.el:427: Argument `orig' should appear (as ORIG) in the doc string
```

byte-compile (using Emacs 27.1):
```
code-review-utils.el:388:1:Warning: the function `code-review-github-repo' is
    not known to be defined.
```

byte-compile (using Emacs 27.1):
```
code-review.el:216:13:Warning: assignment to free variable `reload\?'
```

package-lint (using version 20210528.2348):
```
10 issues found:
121:0: error: "magit-code-review-commit-section-map" doesn't start with package's prefix "code-review".
127:0: error: "magit-code-review-comment-body-section-map" doesn't start with package's prefix "code-review".
133:0: error: "magit-code-review-comment-header-section-map" doesn't start with package's prefix "code-review".
139:0: error: "magit-code-review-local-comment-section-map" doesn't start with package's prefix "code-review".
146:0: error: "magit-code-review-local-comment-header-section-map" doesn't start with package's prefix "code-review".
153:0: error: "magit-code-review-feedback-section-map" doesn't start with package's prefix "code-review".
159:0: error: "magit-code-review-feedback-header-section-map" doesn't start with package's prefix "code-review".
165:0: error: "magit-code-review-labels-section-map" doesn't start with package's prefix "code-review".
171:0: error: "magit-code-review-assignee-section-map" doesn't start with package's prefix "code-review".
177:0: error: "magit-code-review-milestone-section-map" doesn't start with package's prefix "code-review".
```

**Comment by riscy** [comment]
I'll be back next weekend, but I'll quickly followup that the following files might need license boilerplate:

- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to code-review-core.el
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to code-review-db.el

And it is worth being aware of this similarly named package:

- git-code-review: https://github.com/emacsmirror/git-code-review.git (via emacsmirror)

**Comment by wandersoncferreira** [comment]
> I'll be back next weekend, but I'll quickly followup that the following files might need license boilerplate:
> 
> * Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to code-review-core.el
> * Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to code-review-db.el
> 
> And it is worth being aware of this similarly named package:
> 
> * git-code-review: https://github.com/emacsmirror/git-code-review.git (via emacsmirror)

I fixed the issues pointed here and also did a small refactor based on tarsius suggestions to have individual classes for each section. Please let me know if you have more feedback. The codebase is quite large for typical Elisp projects but I believe the current version is stable enough for wide usage. (I'm very busy recently so I couldn't stress test more tbh)

With regards to naming conflict/similarity, I don't see any problem with `git-code-review` seems like many attempts to fix the same problem.

**Comment by riscy** [comment]
Here's a quick run since the latest refactor:

### code-review-comment.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### code-review-core.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### code-review-db.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### code-review-github.el ###

byte-compile (using Emacs 27.1):
```
code-review-github.el:57:19:Warning: reference to free variable
    `code-review-log-file'
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### code-review-section.el ###

byte-compile (using Emacs 27.1):
```
code-review-section.el:826:24:Warning: reference to free variable
    `code-review-comment-commit-buffer\?'
In end of data:
code-review-section.el:835:1:Warning: the following functions are not known to
    be defined: code-review-mode, code-review-commit-minor-mode
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### code-review-utils.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### code-review.el ###

byte-compile (using Emacs 27.1):
```
code-review.el:237:1:Warning: Unused lexical argument `feedback'
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
- No issues!

**Comment by wandersoncferreira** [comment]
Really appreciate the help @riscy identifying the issues. All fixed in master@HEAD.

**Comment by riscy** [comment]
Great!  I think there's just a couple more and we should be past the byte-compile:

byte-compile (using Emacs 27.1):
```
code-review-section.el:770:1:Warning: the function `code-review--build-buffer'
    is not known to be defined.
```

byte-compile (using Emacs 27.1):
```
code-review-utils.el:449:1:Warning: the function `code-review--build-buffer'
    is not known to be defined.
```

You're aware of the fairly similar PR open -- now might be a good time to pause and see if there's any collaboration opportunity there.  I don't think that's necessarily a blocker, but it might be worth differentiating the packages to help users choose (e.g., right now your `;;; Commentary` is a little sparse with just "`code-review` lets you submit code review with Emacs.")

**Comment by wandersoncferreira** [comment]
fixed @riscy . I read the code from @blahgeek and is really interesting how similar both projects are in some aspects. I would be very glad to have him as collaborator in the project, however my time schedule is very complex right now because my daughter is 1 week old and I am mostly in the computer during my dawn to not get asleep during my night shifts taking care of her hehehehe...

@blahgeek this is my email address if you want to chat a way forward to collaborate: wand@hey.com

@riscy I would suggest to merge both projects independently for now.

**Comment by blahgeek** [comment]
@wandersoncferreira First of all, congratulations on your new arrival! :heart: 

I agree that we can try to merge both projects to melpa independently for now, having a few extra users' feedback would be great for both projects.

Looking forward, I would be interested in some kind of collaboration. I haven't really had the time to try your project or read the code yet, I would take some time to do that and think about the way to collaborate. I will reach to you if I have any thought (but please expect some delay :)

**Comment by riscy** [comment]
Thanks both!  @wandersoncferreira, I wonder if a recent code change has introduced some new warnings:

byte-compile (using Emacs 27.1):
```
code-review-section.el:271:11:Warning: assignment to free variable
    `code-review-comment-cursor-pos'
In code-review-toggle-reaction-at-point:
code-review-section.el:359:30:Warning: reference to free variable
    `code-review-reaction-types'
In code-review-reactions-reaction-at-point:
code-review-section.el:377:9:Warning: assignment to free variable
    `code-review-comment-cursor-pos'
code-review-section.el:384:20:Warning: reference to free variable
    `code-review-reaction-types'
In code-review-code-comment-reaction-at-point:
code-review-section.el:452:11:Warning: assignment to free variable
    `code-review-comment-cursor-pos'
In code-review-comment-insert-reactions:
code-review-section.el:572:32:Warning: reference to free variable
    `code-review-reaction-types'
In end of data:
code-review-section.el:1141:1:Warning: the following functions are not known
    to be defined: code-review--build-buffer, emojify-completing-read
```

byte-compile (using Emacs 27.1):
```
code-review-utils.el:374:11:Warning: assignment to free variable
    `code-review-comment-cursor-pos'
In code-review-utils--set-milestone-field:
code-review-utils.el:403:11:Warning: assignment to free variable
    `code-review-comment-cursor-pos'
In code-review-utils--set-title-field:
code-review-utils.el:413:11:Warning: assignment to free variable
    `code-review-comment-cursor-pos'
In end of data:
code-review-utils.el:513:1:Warning: the function `code-review--build-buffer'
    is not known to be defined.
```

Finally on code-review-utils.el#L509 I can see that loading the package is automatically adding a (local) hook to `after-change-functions`.  I don't know if this will be doing what you intend, since the hook will only be local to whatever buffer was focused on when the package is loaded.  More importantly, adding/removing hooks should usually be done as part of activating/deactivating the mode.

**Comment by wandersoncferreira** [comment]
Thanks again @riscy . I am calling `package-lint-current-buffer` on every buffer and I can't see these warnings :/

I added the `(require 'emojify nil t)` to fix the `emojify-completing-read` warning, should it be enough?

With regards to `after-change-functions` I can leave without it for now. I am currently working in a new version of this function anyway. I removed the hook for now.

**Comment by wandersoncferreira** [comment]
@riscy , `emojify` is now a required package and the warnings are gone afaict. There is anything else that concerns you for merging the recipe?

**Comment by riscy** [comment]
Hi @wandersoncferreira, look like I overlooked checking this one today.  Here's the latest --

byte-compile (using Emacs 27.1):
```
code-review-comment.el:237:25:Warning: reference to free variable
    `code-review-commit-buffer-name'
code-review-comment.el:238:23:Warning: reference to free variable
    `code-review-buffer-name'
In end of data:
code-review-comment.el:334:1:Warning: the function `code-review--build-buffer'
    is not known to be defined.
```

byte-compile (using Emacs 27.1):
```
code-review-section.el:1144:1:Warning: the function
    `code-review--build-buffer' is not known to be defined.
```

byte-compile (using Emacs 27.1):
```
code-review-utils.el:512:1:Warning: the function `code-review--build-buffer'
    is not known to be defined.
```

**Comment by wandersoncferreira** [comment]
@riscy fixed :)

To suppress the warning of functions I should have used `declare-function`.. TIL something new =)

**Comment by riscy** [comment]
Thanks!  I wasn't very helpful, but that works.  The (probably obvious) alternative would be to change the physical layout of the package so that the forward declarations aren't necessary, but you also have the tool `M-x check-declare` to help out.  This looks good to go now -- merging!

**Pull request merged**
