### PR TITLE
Add cobalt.el recipe.

### PR DESCRIPTION
**Pull request by accidentalrebel**
### Brief summary of what the package does
Cobalt.el is an Emacs interface for Cobalt.rs, a static site generator written in Rust.

### Direct link to the package repository
https://github.com/cobalt-org/cobalt.el

### Your association with the package
Maintainer.

### Relevant communications with the upstream package maintainer
***None needed***

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- "Summary" isn't a very good [package short description](https://github.com/cobalt-org/cobalt.el/blob/1d5d558dee4c83693645a63982fb214f32d79c99/cobalt.el#L1)
- For `:group 'cobalt`, you should also have added a `(defgroup cobalt ...)` form

Looks great otherwise!

**Comment by accidentalrebel** [comment]
Uh oh. I missed that `Summary` part. Thanks will fix these in the next hour. Thanks!

**Comment by accidentalrebel** [comment]
Hello! Requested changes have been fixed. Thanks!

**Comment by purcell** [comment]
Thanks, merged. Also sent you https://github.com/cobalt-org/cobalt.el/pull/1. :-)

**Pull request merged**
