### PR TITLE
Receipe: circadian - automatic theme-switching based on daytime

### PR DESCRIPTION
**Pull request by GuidoSchmidt**
### Brief summary of what the package does

Circadian provides a way to automatically switch themes for day and night and features two themes: hemera-theme and nyx-theme.

### Direct link to the package repository

https://github.com/GuidoSchmidt/circadian.el

### Your association with the package

Creater and maintainer 🙂 

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! I would use something like this myself. Quick comments:
- Please package each theme separately, since they don't belong hidden in another package.
- `(when (not x) ..)` is better written `(unless x ...)`
- Prefer the `-p` to `?` for predicate functions: it's more idiomatic in elisp.
- The `linum`-related code doesn't really belong in this package
- The use of hooks to trigger the theme changes is weird, particularly the use of `after-change-major-mode-hook`. Instead, I'd expect to see timers.
- This would all be best wrapped up as a global minor mode can be toggled.
- Why only two themes? I could imagine using three or more. Maybe just define everything with an `alist` of `(hour . theme-name)`, and perform a lookup from top to bottom based on the current hour.
- You can avoid the kind of code in `circadian-load-theme-disable-old-theme` by setting themes with `(custom-set-variables `(custom-enabled-themes '(,name)))`, where `name` is a variable containing the theme name.

Hope that helps!

**Comment by GuidoSchmidt** [comment]
I'm still beginner at Elisp and still learning a lot, therefore much thanks for the nice and detailed feedback! 🙂 👍 I will try to implement your suggestions.

**Comment by GuidoSchmidt** [comment]
@purcell I've mostly re-implemented the package thanks to your great suggestions, timed functions work great - thanks for pointing me into that direction. Themes have been moved to their own packages.

**Comment by purcell** [comment]
Nice! Merging now. Welcome to MELPA!

**Pull request merged**
