### PR TITLE
Add bencode recipe

### PR DESCRIPTION
**Pull request by xuchunyang**
### Brief summary of what the package does

Reading and writing [Bencode](https://en.wikipedia.org/wiki/Bencode) which is the encoding used in BitTorrent files.

### Direct link to the package repository

https://github.com/xuchunyang/bencode.el

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

The maintainer

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.

I cannot find any issues for this package :tada:

Note:
Please write your repository URL in **Direct link to the package repository**.

**Comment by xuchunyang** [comment]
> Please write your repository URL in **Direct link to the package repository**.

Fixed. Thank you for the feedback.

**Comment by riscy** [comment]
There's already an Emacsmirrored package called bencode at https://github.com/emacsmirror/bencode.git so to prevent a collision it may be a good idea to rename this package.  10 years since its last update (!) but still.

Code looks good, though.

**Comment by xuchunyang** [comment]
I've renamed bencode to bencoding: the repo, the package name and the melpa recipe.

**Comment by riscy** [comment]
Great, thanks!

**Pull request merged**
