### PR TITLE
Add 'workroom' recipe

### PR DESCRIPTION
**Pull request by AkibAzmain**
### Brief summary of what the package does

Named rooms for doing work without irrelevant distracting buffers.

### Direct link to the package repository

https://codeberg.org/akib/emacs-workroom

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Without my having tried this, have you had a chance to compare to some similar-sounding packages?:

- https://melpa.org/#/bufler
- https://melpa.org/#/state
- [Some possible others](https://melpa.org/#/?q=workspace)

In the meantime some quick feedback:
`workroom.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- workroom.el#L153: It's safer to sharp-quote function names; use `#'` - if you did this you'd get a valuable byte-compile warning re: "the function `workroomp` is not known to be defined."
- workroom.el#L176: Top-level `define-key` can sometimes overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- workroom.el#L534: No `format` required; `user-error` takes an f-string
- workroom.el#L548: No `format` required; `user-error` takes an f-string
```

**Comment by AkibAzmain** [comment]
@riscy Thanks, you caught a bug: 

```
(defalias 'workroom-p 'workroomp) ; Wrong
(defalias 'workroomp #'workroom-p) ; Correct
```

Addressed all issues you have found.  But I have no idea what to do with the `define-key` issue.

**Comment by riscy** [comment]
Thank you!  Just quickly checking, do you have any comment about where your package fits compared to the packages I mentioned?

> define-key issue

It's ultimately minor,  but running `define-key` at the top level means people (mostly devs) who eval the buffer in the process of making changes can have their personalized bindings overwritten, which you can prevent by wrapping everything in the `defvar`, e.g.:

```elisp
(defvar workroom-command-map
  (let ((keymap (make-sparse-keymap)))
    ;; NOTE:  Be sure to update commentary and README when you modify this.
    ;; ...
    (define-key workroom-command-map "K" #'workroom-kill-buffer)
    keymap)
  "Keymap containing all useful commands of Workroom.")
```

**Comment by AkibAzmain** [comment]
Thanks for the suggestion, I've fixed it.

> Just quickly checking, do you have any comment about where your package fits compared to the packages I mentioned?

My package is similar to `persp-mode` and `perspective`, but the only difference is that it supports than one window configuration per workspace, which was one of the design goals.

**Comment by riscy** [comment]
> the only difference is that it supports than one window configuration per workspace, which was one of the design goals

Take what I say with a grain of salt, but I wonder if it would be easier to implement the behavior you want on top of one of these existing packages?  That way you could benefit from e.g. persp-mode's ecosystem (including integration with projectile for example), its existing userbase, and its existing features.  Sometimes this can be a better outcome, but I'll see what you think.

**Comment by riscy** [comment]
Okay, looks good to merge here.  I have a couple quick comments but no blockers:

- "Your all workrooms" -> "All your workrooms"
- In some cases I see both `user-error` and `error` catching the same kinds of errors in the same function (e.g. `workroom-kill-view`), but maybe this is a deliberate choice for some reason?

**Comment by AkibAzmain** [comment]
Thanks for merging it.

> "Your all workrooms" -> "All your workrooms"

Yeah, that's more clear.  I changed that.  Thanks again.

**Pull request merged**
