### PR TITLE
Add recipe for leader-key

### PR DESCRIPTION
**Pull request by Havner**
### Brief summary of what the package does

Simple helper to add leader key functionality (e.g. for god-mode)

The idea is to replicate a vim/evil leader key concept, but be independent of
any other mode.  This has been developed and tested together with god-mode
but should work without it or even without any modal mode.  It works together
with which-key, but the dependency is optional.

### Direct link to the package repository

https://github.com/havner/leader-key

### Your association with the package

I'm an author and maintainer.

### Relevant communications with the upstream package maintainer

I'm both author and maintainer so I guess: None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

- No byte-compile errors 🎉

`leader-key.el` with checkdoc (0.6.2)

```
leader-key.el:274: Lisp symbol `major-mode' should appear in quotes
leader-key.el:315: Lisp symbol `major-mode' should appear in quotes
```

`leader-key.el` with package-lint (20230905.629)

```
282:7: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
323:9: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
```

**Comment by Havner** [comment]
> `leader-key.el` with checkdoc (0.6.2)
> 
> ```
> leader-key.el:274: Lisp symbol `major-mode' should appear in quotes
> leader-key.el:315: Lisp symbol `major-mode' should appear in quotes
> ```
Hmm, strange, my checkdoc didn't show that. I'll verify the version.

> `leader-key.el` with package-lint (20230905.629)
> 
> ```
> 282:7: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
> 323:9: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
> ```
This I saw, but since the whole package is kinda advanced configuration and it's only a warning I intentionally decided to go with it. IMO the usage of `eval-after-load' in those functions is justified. It's also optional (it only triggers when optional parameter is used).

> Package and license:
> 
>     * Add a LICENSE file to the repository
>       See: https://github.com/licensee/licensee
Ok, I'll add.

**Comment by jcs090218** [comment]
> This I saw, but since the whole package is kinda advanced configuration and it's only a warning I intentionally decided to go with it. IMO the usage of `eval-after-load' in those functions is justified. It's also optional (it only triggers when optional parameter is used).

Yeah, I agree with this. This should be fine. 🤔 However, `@riscy` will make the final decision!

**Comment by riscy** [comment]
Thanks both.  Yes, the eval-after-loads looks fine to me (the containing functions are themselves for configurations).

Let me know when that license is in place.

**Comment by Havner** [comment]
> > `leader-key.el` with checkdoc (0.6.2)
> > ```
> > leader-key.el:274: Lisp symbol `major-mode' should appear in quotes
> > leader-key.el:315: Lisp symbol `major-mode' should appear in quotes
> > ```
> 
> Hmm, strange, my checkdoc didn't show that. I'll verify the version.
Strange indeed. I've updated emacs to 29.1, I have checkdoc 0.6.2 and it still doesn't show me those warnings. I've fixed them though.

> > Package and license:
> > ```
> > * Add a LICENSE file to the repository
> >   See: https://github.com/licensee/licensee
> > ```
> 
> Ok, I'll add.

Done

After installing emacs 29.1 it showed two new warnings for byte compilation (also quotation related). I've fixed them.

**Comment by Havner** [comment]
> Thanks both. Yes, the eval-after-loads looks fine to me (the containing functions are themselves for configurations).
> 
> Let me know when that license is in place.

License added, all quotation warnings fixed.

**Comment by riscy** [comment]
Thanks!  All set here.

**Pull request merged**
