### PR TITLE
Add codespaces recipe

### PR DESCRIPTION
**Pull request by patrickt**
### Brief summary of what the package does

This package adds helper functions and a completing-read interface to connect to running GitHub Codespaces instances via TRAMP.

### Direct link to the package repository

https://github.com/patrickt/codespaces.el

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, looks like an interesting package.  Quick first pass --

`codespaces.el` with byte-compile using Emacs 28.1:
```
codespaces.el:106:8: Warning: docstring wider than 80 characters
```
These have just started being reported with Emacs 28.  It seems incredibly minor, but by fixing this you can ensure your users are seeing a clean byte-compile.

`codespaces.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- codespaces.el#L7: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
```

**Comment by patrickt** [comment]
@riscy Thanks for the eyeballs! I’ve addressed the issues you raised, and it’s ready for another look at your convenience.

**Comment by riscy** [comment]
Looks good to go.  On this last glance I notice that the uses of `error` (e.g. for telling the user about `gh` missing) could be replaced with non-backtrace-opening `user-error`s.  I also eschew writing "Please" in prompts the user will see over and over again, but that's purely a matter of opinion. :)

**Comment by patrickt** [comment]
@riscy Oh, I didn’t know about `user-error`. Thank you!

**Pull request merged**
