### PR TITLE
Add recipe for pardef

### PR DESCRIPTION
**Pull request by FloatingLion**
### Brief summary of what the package does

A python docstring generator, like https://github.com/naiquevin/sphinx-doc.el but it's

- more functionality (placeholders, `__init__`, ..)
- more robust (backslash multiline, comment, ..)
- and more extensible.

### Direct link to the package repository

https://github.com/FloatingLion/pardef.el

### Your association with the package

I'm the maintainer of this package.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, this looks pretty cool -- and I appreciated the demo.

You mention some differences between your package and sphinx-doc, but from my shallow understanding it seems like this package simply has a few features that sphinx-doc doesn't.  Just in case, have you thought about extending the existing sphinx-doc with these features?  Or is that unreasonable given the different implementations (which is fine too)?

- I'm having trouble wrapping my head around the name pardef, but since the package revolves around sphinx-style docstrings you should ideally mention `sphinx` somewhere in the package name or summary line
- pardef.el#L675: It's safer to sharp-quote function names; use `#'`
- pardef.el#L7: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- pardef.el#L799: Use `when ...` instead of `unless (null ...)`
- pardef.el#L845: Use `when ...` instead of `unless (null ...)`
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by FloatingLion** [comment]
Thanks very much for your advices.  All them are fixed:

- A more appropriate summary
- Use sharp-quote instead of simply quote
- Replace the ;; Package-Version
- Add LICENSE file
- and two (when ...)

I am new to Emacs and isn't very skillful at it.  Thanks for your guidance again!

**Comment by riscy** [comment]
Thanks for taking a look -- one last question I'll reiterate since it may have been lost in the shuffle: have you thought about extending the existing sphinx-doc with these features? Or is that unreasonable given the different implementations (which is fine too)?

This is often something we ask authors to consider, because (a) it is often better for the users to have fewer *great* choices instead of many minimally viable packages that they end up using piecemeal, and (b) you can benefit from working with an experienced/skillful package developer.

**Comment by FloatingLion** [comment]
OK. I will try to extend present package instead of create a new one. Thank you for your time!

**Comment by riscy** [comment]
Thanks very much for accommodating.  If it turns out the key features you're looking for are somehow infeasible, we can definitely revisit.

**Pull request closed without merging**
