### PR TITLE
add helm-etags-plus recipe

### PR DESCRIPTION
**Pull request by jixiuf**
### Brief summary of what the package does
Another Etags helm.el interface, it support multiple tag files.

### Direct link to the package repository

https://github.com/jixiuf/helm-etags-plus

### Your association with the package

I am the maintainer

### CODE REVIEW

**Comment by syohex** [comment]
- You should name `helm-etags-plus.el` instead of `helm-etags+.el` if you name package `helm-etags-plus`. (Tests on travis is failed by this naming issue).
- I suppose `ctags-update.el` should be moved to other repository. (And then you need not to specify `:files` attribute in recipe.

**Comment by purcell** [comment]
Some quick feedback:
- Top-level symbols like `pos-in-same-symbol-p` are not allowed: all such symbols should have the `helm-etags-plus-` prefix.
- Similarly, symbols like `helm-c-source-etags-plus-select` should probably be of the form `helm-etags-plus-c-source-select` instead.
- `M-x checkdoc` would have some advice on tidying up some of those docstrings.

Looks good otherwise.

**Comment by jixiuf** [comment]
updated

**Comment by purcell** [comment]
Super, thanks - merged!

**Pull request merged**
