### PR TITLE
Add goggles recipe

### PR DESCRIPTION
**Pull request by minad**
### Brief summary of what the package does

Pulse on modified region similar to evil-goggles, without the evil part.

### Direct link to the package repository

https://github.com/minad/goggles

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by minad** [comment]
As an additional note for anyone interested in reviewing this package: For me goggles is mainly meant as a replacement for volatile-highlights, which is a very popular (percentile 98.74), but has quite a few downsides from my perspective.

* It is essentially unmaintained, no commit for 5 years
* It contains obsolete code (cl instead of cl-lib, old advice mechanism, untested xemacs support anyone?)
* I don't agree with the way its written, it has an overengineered extension-mechanism. The extension mechanism (or the old advice mechanism) somehow seems to require bytecode compilation at startup. Maybe I am wrong here regarding the reasons, but at least volatile-highlights appears as an entry in the startup profiler-report. This should not be.
* It does not support pulse

Since improving volatile-highlights does not seem possible to me, except rewriting it, I rather prefer making another package. Otherwise this would simply lead to unnecessary breakage for 99% of the users...

Furthermore since there is already an evil-goggles package - I always wondered where the goggles are. If someone could point me to a viable alternative I would also gladly take it!

**Comment by alphapapa** [comment]
This looks very nice.  I've wanted a better alternative to `volatile-highlights` for a while, and using `pulse` seems like a great solution.  Here's a little feedback:

1.  It would be easier to review the package if the functions were arranged with the entry point (e.g. the minor mode) first and subsequent functions in the order in which they're called.  As it is, the file begs to be read bottom-to-top.
2.  The docstring of `goggles--after-change` could be more descriptive.  "Remember..." doesn't say what the function does, which is to push an overlay to `goggles--changes`.
3.  The variable `goggles--changes` could be called, e.g. `goggles--overlays`, which would be more descriptive.
4.  The code you've written is very clean and concise.  Nevertheless, it might be preferable to write `goggles` as a function rather than a macro.  It would make the code easier to understand.
5.  If you keep it as a macro, it should probably be named something like `defgoggles` or `goggles-define`, which would be consistent with standard practice for macros that define functions.

Thanks a lot for making this.  I'm going to go try it out now.  :)

**Comment by alphapapa** [comment]
Some notes after testing:

1.  When I `yank`, it seems to highlight much more than the region of the buffer that has the yanked text.
2.  It would probably be a good idea for the faces to inherit from some `font-lock-` faces rather than hard-coded color names.
3.  It may be my imagination, or clutter from elsewhere in my Emacs config, but I wonder if 15 pulses per operation might be too many for a default, from a performance perspective.  Sometimes it seems to cause some pauses for me.

**Comment by minad** [comment]
@alphapapa Thank you for reviewing - I've been looking forward to a review.

> This looks very nice.

Thank you!

>     1. It would be easier to review the package if the functions were arranged with the entry point (e.g. the minor mode) first and subsequent functions in the order in which they're called.  As it is, the file begs to be read bottom-to-top.

I think I chose the order since I wanted to define the things first which are used later. But this is not necessary here. Maybe defining the mode earlier is better maybe not, one could also see it as the climax of the story, so it could somehow come at the end ;) I don't care deeply about this issue - so if you insist, I can change this, but I generally dislike reordering code since it destroys the diffs.

>     2. The docstring of `goggles--after-change` could be more descriptive.  "Remember..." doesn't say what the function does, which is to push an overlay to `goggles--changes`.

Agree.

>     3. The variable `goggles--changes` could be called, e.g. `goggles--overlays`, which would be more descriptive.

No. I had this name before and it is not what is meant here. The list of overlays is used as a changelog. Overlays are only the means to achieve this. The overlays change themselves under the subsequent modifications and therefore are a good fit as objects to use in this log. I should document this better. Maybe there is an alternative idea on what I could do. I cannot simply record the begin and end points of all the changes since these will not stay constant when new changes come in. The overlays in the list are also never shown in the end. I create a new overlay based on the min/max from this changelog.

Now that I think about it and I learned more things when writing Consult, I guess I should rather use a pair of markers instead of overlays for the changelog. Two markers are probably cheaper than a single overlay?

>     4. The code you've written is very clean and concise.  Nevertheless, it might be preferable to write `goggles` as a function rather than a macro.  It would make the code easier to understand.

Yes, it might. But I would like to keep the macro. I like that I can expand the macro using macroexpand and look at the resulting code. Furthermore by using a macro the code is expanded at compile time and I like this and it pleases my inner compiler guy.

>     5. If you keep it as a macro, it should probably be named something like `defgoggles` or `goggles-define`, which would be consistent with standard practice for macros that define functions.

Yes, I can do that. I think I've chosen the name for its snappiness. I don't care deeply about this. defgoggles would be fine for me in contrast to goggles-define. But for defgoggles, the package linter complains btw.

>     6. As well, the `goggles` macro's docstring should be more descriptive than it is.  It should explain how to use it and what it does.

Agree.

>     7. The `yank` goggle says `yank` twice.  Is that intended?

Yes, the first is the goggles name, after that the list of commands follow. It looks weird.

> When I yank, it seems to highlight much more than the region of the buffer that has the yanked text.

This sounds like a bug. I don't see this. For me only the yanked text is pulsing with a green background. Any idea what this could be? I am on Emacs 27.1, pretty standard everything I guess.

> It would probably be a good idea for the faces to inherit from some font-lock- faces rather than hard-coded color names.

Yes, generally agree. But I really want different background colors here. They should be suggestive as addition and deletions.
So I have to chose some colors myself. Since writing this I learned a few things regarding choosing faces, e.g. using the matching to check if the background is bright or dark and then selecting the color accordingly. I will improve the face definitions here, but I think I should inherit from something existing. Existing faces would be match, highlight, region etc.

> It may be my imagination, or clutter from elsewhere in my Emacs config, but I wonder if 15 pulses per operation might be too many for a default, from a performance perspective. Sometimes it seems to cause some pauses for me.

Ok, I can just use the default values. I think it is 10, but with a larger delay.

> It seems like the goggles-pulse variable is superfluous.

No, it is not. It sets the pulse-flag, which is a variable from pulse.el. If you set pulse-flag to nil, the region will not pulse. The nice thing here is that goggles will just behave like volatile-highlights if you set this flag!

All in all there seems to be only one deeper issue - the bug. I am not sure on how to proceed here. Can you describe the issue a bit better? When deleting I am using an :extend face, such that the whole line is highlighted. But you don't mean that I guess? I would not have expected such an issue since what I am doing with the change log is pretty simple. Instead of using overlays I could convert to markers and you try again but I don't think that changes anything. Another thing we could try is adding some log messages to see the regions of the logged operations, but there are usually many so it is not that easy to see. I will experiment with a different Emacs version and see how everything works and then come back here.

**Comment by minad** [comment]
@alphapapa I finished your points. I did some tests on Emacs 26, which didn't go well. Something is behaving weird there. If it is only a problem on Emacs 26, I can investigate if something relevant to goggles has been changed from 26->27. Are you using Emacs 26? For me on Emacs 27 everything works well and I haven't seen issues yet.

**Comment by alphapapa** [comment]
> > 1. It would be easier to review the package if the functions were arranged with the entry point (e.g. the minor mode) first and subsequent functions in the order in which they're called.  As it is, the file begs to be read bottom-to-top.
> 
> I think I chose the order since I wanted to define the things first which are used later. But this is not necessary here. Maybe defining the mode earlier is better maybe not, one could also see it as the climax of the story, so it could somehow come at the end ;) I don't care deeply about this issue - so if you insist, I can change this, but I generally dislike reordering code since it destroys the diffs.

As Knuth would say, code is not meant only for computers, but for people--ultimately, people make the machines that run the code.  From that perspective, code's primary purpose is to describe procedures to people.

Ordering the code in a file in reverse of the order in which it is executed would be much like asking someone to read a how-to guide in reverse, by starting at the final step and reading backward.  I'm sure you can see how disorienting that would be.

Instead, a guide starts by introducing the procedures and with the first step, to be followed in order.

This approach is more helpful from a pedagogical perspective.  Starting from the top, one gains a high-level understanding: what does this package do?  What command do I call to begin using it?  As one reads further, one proceeds to deeper understanding: How does this command work?  What functions does it call to do the actual work?  What other functions are called that do the low-level manipulations?

This way, one can read as far as is necessary in order to gain a certain level of understanding, and need not proceed further.  This is especially helpful when debugging unfamiliar code: I may not even need to know that a low-level function exists in order to discover and fix a bug at a higher level of abstraction.

And from a purely practical perspective, reading from bottom-to-top means going up and down, back and forth, rather than reading linearly, in order.

So by ordering your code in reverse, you increase the work of the reader trying to understand your code.  Do you see what I mean?

> 
> **Wontfix** After reading through the code again and adding some ;;;;sections, I think I would like to keep the order like this. The mode definition itself is rather insignificant.

It's your code, so you may do as you wish.  Note, though, that the minor mode definition is how the user begins using your package.  To the user, it's the most significant part of the code.  And for anyone wondering how the package works, wanting to follow the order of execution, it's the starting point.

> > 3. The variable `goggles--changes` could be called, e.g. `goggles--overlays`, which would be more descriptive.
> 
> No. I had this name before and it is not what is meant here. The list of overlays is used as a changelog. Overlays are only the means to achieve this. The overlays change themselves under the subsequent modifications and therefore are a good fit as objects to use in this log. I should document this better.

It would be good to explain that in the docstring.  It would only require a couple of sentences.

> Maybe there is an alternative idea on what I could do. I cannot simply record the begin and end points of all the changes since these will not stay constant when new changes come in. The overlays in the list are also never shown in the end. I create a new overlay based on the min/max from this changelog.
> 
> Now that I think about it and I learned more things when writing Consult, I guess I should rather use a pair of markers instead of overlays for the changelog. Two markers are probably cheaper than a single overlay?

Yes, generally, overlays shouldn't be used unless necessary, AFAIK.  Also, in case you didn't know, while markers are eventually garbage-collected, AFAIU it's better to clean them up manually.  See the Elisp manual for more details.

> > 5. If you keep it as a macro, it should probably be named something like `defgoggles` or `goggles-define`, which would be consistent with standard practice for macros that define functions.
> 
> Yes, I can do that. I think I've chosen the name for its snappiness. I don't care deeply about this. defgoggles would be fine for me in contrast to goggles-define. But for defgoggles, the package linter complains btw.

Yes, the linter expresses the preference for the standard that symbols begin with the package name, e.g. `goggles-define`.  See the Elisp manual, section D.1 Emacs Lisp Coding Conventions.

> > 7. The `yank` goggle says `yank` twice.  Is that intended?
> 
> Yes, the first is the goggles name, after that the list of commands follow. It looks weird.

That's an example of how a macro can be more confusing than a function.  Anyway, you might consider accepting quoted symbols, so e.g. it could be written:

    (goggles-define yank #'yank #'yank-pop)

Regarding the bug, yes, I was testing on Emacs 26.3.  When I yank, it seems to pulse from either the beginning or end of the yanked text to either the beginning or end of the buffer.  It might be related to the `:extend`-related face changes in Emacs 27.  I guess it's up to you whether you want to support Emacs <27, but I've recently heard about people still using Emacs 25.2, so I guess people will be using Emacs 26 for quite a while longer.

BTW, when quoting in these issues, please don't use code blocks, because it doesn't wrap text, so it requires using an embedded horizontal scrollbar to read the whole quote.

**Comment by minad** [comment]
> It would be good to explain that in the docstring. It would only require a couple of sentences.
Done.

> Yes, generally, overlays shouldn't be used unless necessary, AFAIK. Also, in case you didn't know, while markers are eventually garbage-collected, AFAIU it's better to clean them up manually. See the Elisp manual for more details.

Thank you. This is helpful. I will also modify my Consult package now that I know that. Interestingly I haven't seen bad effects due to creating many markers. I am simply generating enough garbage for the collector to take the markers early enough it seems.

> Regarding the bug, yes, I was testing on Emacs 26.3. When I yank, it seems to pulse from either the beginning or end of the yanked text to either the beginning or end of the buffer. It might be related to the :extend-related face changes in Emacs 27. I guess it's up to you whether you want to support Emacs <27, but I've recently heard about people still using Emacs 25.2, so I guess people will be using Emacs 26 for quite a while longer.

My goal is to support 26 and 27 at least. This bug should be fixed, but at first I had to confirm if it is really the Emacs version. This helps me with the digging.

**Comment by minad** [comment]
>  I will also modify my Consult package now that I know that. Interestingly I haven't seen bad effects due to creating many markers. I am simply generating enough garbage for the collector to take the markers early enough it seems.

Now that I revisited that it is actually not that obvious what the best approach regarding markers is. In the goggles case it is easy, since I can simply reset the markers while walking over the change log. But for consult-line I am generating many markers, one per line, and after selection the whole candidate list of all line strings and markers is garbage. If it is collected soon the marker problem is gone. Now I could walk again over the whole candiate list after completion finished, potentially keeping the candidate list alive for longer than necessary but unlinking all the markers from the buffer potentially earlier which is good for subsequent editing commands. I guess the case in that case it is not so clear what to do. To keep things simple, I would probably rather go with not writing code and hoping for the gc to jump in soon enough. Not doing the garbage collectors job somehow ;)

**Comment by minad** [comment]
@alphapapa Update: The Emacs 26 bug is fixed, a ridiculous one, I must admit: I did not use buffer local variables. I am astonished that this worked flawlessly on Emacs 27 for me. Are there more things here you would like to address? It would be great if you could check if it works for you now. Thank you.

**Comment by alphapapa** [comment]
It appears that you did solve that bug.

Also, I noticed that when I kill text, it pulses to the end of the line rather than only up to the point of the text that was killed.  I don't know if that's intended, or if it can easily be fixed, but it is a bit disorienting to have it pulse more than the region that was actually killed.

About markers: It probably doesn't matter.  I haven't looked closely at all of your code, but I can't imagine how you could be creating enough to cause a problem.  I think it probably requires hundreds or thousands to begin to have a noticeable impact.

**Comment by minad** [comment]
Thank you for looking into this again. Yes, pulsing to the end is due to regions being extended in emacs 26, or isn't it? In emacs 27 I extend the removed face since otherwise you would not see pulsing at all in some cases. I am not sure what the default should be but I liked it a bit better that way.

I agree with the markers. But for the consult-line swiper implementation 100k lines is not that unrealistic. But I consult-line is still fast except for the startup cost.

**Comment by alphapapa** [comment]
> If possible could you mark this as alphapapa-approved/reviewed somehow please in order for this to get merged at some point? I guess we sorted out all important things.

As you know, I'm not a MELPA staff member, so my review is unofficial.  I just do it to help out.  It's up to MELPA to decide when to merge this.  There's no mark that I can give.

**Comment by minad** [comment]
Yes, I just meant that you can state that according to your assessment this package is good to merge if you think it is. Not adding a label or sth. (It would be good if you could, this was somehow my proposal. Such that active non-official reviewers can be onboarded as maintainers. But let's not restart that discussion again.)

**Comment by alphapapa** [comment]
I haven't been asked to give a personal "stamp of approval" to package submissions, and I think it would be presumptuous of me to do so, because my opinion isn't what matters.  My feedback is intended to help the author and, to whatever extent, save the MELPA maintainers from having to write that feedback themselves.

**Comment by minad** [comment]
OK. Thank you for the review. Would you like to take a look at consult too? Right now I am more focused on that package (and marginalia which is to be submitted).

**Comment by alphapapa** [comment]
Sure, I'll take a look.  I can't promise how comprehensive my review will be or that I will actually test it, because I also have Elisp projects of my own I'm working on.  :)

**Comment by minad** [comment]
> Sure, I'll take a look. I can't promise how comprehensive my review will be or that I will actually test it, because I also have Elisp projects of my own I'm working on. :)

Sure, you have! Since you are a helm user as far as I understood, it might also be not that interesting for you.

**Comment by riscy** [comment]
Thanks both, what a great exchange.  I think there's only one issue to work out:

package-lint (using version 20200906.512):
```
1 issue found:
143:0: error: "defgoggles" doesn't start with package's prefix "goggles".
```
Since `goggles-` is implicitly your package's "namespace", I can suggest `goggles-def` or `goggles-define` instead?    (And update the goggles--list docstring.)  Otherwise this looks good to go.

Minor/pedantic:
- seperetely -> separately

**Comment by minad** [comment]
@riscy Thank you for looking at this. I had the simple name "goggles" before. But since it is a macro, @alphapapa proposed to rather use "defgoggles" or "goggles-define". Since both of you seem to prefer "goggles-define" I will change this.

**Comment by minad** [comment]
See here: https://github.com/minad/goggles/commit/d8de040e6760cfb5fa40ee748199c669033f11ec (typo fixed too)

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
