### PR TITLE
mpdmacs -- A lightweight MPD client for Emacs.

### PR DESCRIPTION
**Pull request by sp1ff**
### Brief summary of what the package does

A lightweight MPD client for Emacs.

### Direct link to the package repository

https://github.com/sp1ff/mpdmacs

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass.

### mpdmacs.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- mpdmacs.el#L120: It's safer to sharp-quote function names; use `#'`
- mpdmacs.el#L555: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- mpdmacs.el#L556: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))` (and several more)
```

**Comment by a13** [comment]
@riscy Doesn't MELPA has an action to check all these automatically yet? :)

**Comment by sp1ff** [comment]
@riscy Related to @a13 's question: how did you produce these lints? I confess, I'm confused by the second & third. How can I be overwriting user bindings when I'm creating them in my own keymap?

**Comment by riscy** [comment]
> Doesn't MELPA has an action to check all these automatically yet? :)

Not yet!  Probably we should. :)  We recently migrated the ci to GitHub actions, so it isn't a stretch.

> Related to @a13 's question: how did you produce these lints? I confess, I'm confused by the second & third. How can I be overwriting user bindings when I'm creating them in my own keymap?

I have [some scripts](https://github.com/riscy/melpazoid) that run the checklist and can plug into an action.  It's not foolproof -- occasionally there are dependencies like vterm or mu4e that are nontrivial to get set up properly.

I admit it's a little contrived, but in the case of the keymaps, what could happen is someone might have a config or even a custom-set-variable that looks like this:
```elisp
(defvar mpdmacs-keymap
  (let ((keymap (make-sparse-keymap)))
    (define-key keymap "P" #'mpdmacs-pause)
    ;; ...a handful of other custom keybindings ...
    keymap))
```
and if they `(require 'mpdmacs)` _after_ doing this because their config is a little convoluted, or if they're a developer who evals the buffer to test a change, their keybinding will get clobbered.  It's easy enough for package maintainers to wrap the entire keybinding's definition inside a defvar that won't overwrite existing values, so we may as well.  Hopefully that clarified -- I realize the lint I left is a bit terse.

**Comment by sp1ff** [comment]
Ahhhhhhhhh.... so. Yes, I see. All lints corrected.
Every time I submit a package to MELPA, I learn about a new linting tool. I'll be adding melpazoid to my toolchain. Thanks!

**Comment by sp1ff** [comment]
@riscy bump

**Comment by riscy** [comment]
Having a closer look at the code now, apologies for the turnaround time.  The code looks good, but have you thought about using a minor mode rather than the two functions called `mpdmacs-enable` and `mpdmacs-unload`?  Especially since you're doing mode-like things such as running hooks.  I may be missing it, but it also looks like`mpdmacs-keymap` isn't used anywhere (please correct me if I'm wrong).

**Comment by sp1ff** [comment]
No problem-- I'm happy to have someone reading ;) That's an interesting suggestion. I had shied away from the idea of a minor mode because this is a global thing-- I wanted one socket to the MPD server per Emacs instance, not one per buffer. But after your comment I perused the docs for `define-minor-mode` & stumbled on the idea that minor modes can be *global*.
I also looked at the code for `erc` & `elfeed`-- not minor modes, but then they provide true user interfaces, which is an explicit non-goal of this package.
In fact, I kind of like the idea of making `mpdmacs` a minor mode to explicitly disambiguate it from `mpdel` (which again provides a full-blown UI in Emacs). OK... give me a few days to try it out & I'll ping you here.

**Comment by sp1ff** [comment]
Done, @riscy . Have a look.

**Comment by riscy** [comment]
I like it. :)  Some quick feedback but this is getting close:

Excerpt from byte-compile (using Emacs 27.1):
```
mpdmacs.el:77:1:Warning: defcustom for `mpdmacs-prefix-keys' fails to specify
    type
In mpdmacs-send:
mpdmacs.el:354:9:Warning: reference to free variable `mpdmacs-mode'
```
For the first I think we just need `:type 'string` -- the second can be fixed by moving your `define-minor-mode` form to the top of the file which, when expanded, will define that variable for you.

I also notice a couple blocks like this:
```
(mpdmacs--def-player-opts-viewer repeat)
(mpdmacs--def-player-opts-viewer random)
(mpdmacs--def-player-opts-viewer single)
(mpdmacs--def-player-opts-viewer consume)
(mpdmacs--def-player-opts-viewer state)
(mpdmacs--def-player-opts-viewer crossfade)
(mpdmacs--def-player-opts-viewer replay-gain-mode)
(mpdmacs--def-player-opts-viewer volume)
```
but can't see their purpose (maybe debugging?)

Lastly, this is minor, but I notice a call to `error` in `mpdmacs--modify-volume` and I wonder whether that should be a user-error that doesn't necessarily pop up the debugger?

**Comment by riscy** [comment]
Never mind, now I see what those 'blocks' I mentioned do. :)

**Comment by sp1ff** [comment]
Hey Chris, so:

- byte-compilation errors fixed
- I agree with your suggestion RE `user-error`; I was unaware of this function! I replaced `error` with `user-error` in `mpdmacs--modify-volume`, as well as a few other places in similar situations (the command is well-formed, it's just that the MPD server is in the wrong state to handle it)

Oh-- and melpazoid runs cleanly against it now :)

**Comment by riscy** [comment]
Looks good!

**Pull request merged**
