### PR TITLE
Add org-snooze recipe

### PR DESCRIPTION
**Pull request by xueeinstein**
### Brief summary of what the package does

Inspired by Google Inbox, org-snooze helps you to snooze your code, doc, feed at a given time. 

### Direct link to the package repository

https://github.com/xueeinstein/org-snooze.el

### Your association with the package

maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by DamienCassou** [comment]
Thank you for your PR. Good job. Here is some feedback:

1. please add `-*- lexical-binding: t; -*-` at the end of the first line
2. please explain in the README what you mean by "appt reminder"
3. please use `~/.emacs.d/` as base directory for the records file
4. please clarify the docstrings of your variables and functions. For example, what do you mean by "title of org file", what does "time of late today" mean and what is this string going to change for the user.
5. please use `defcustom` instead of `defvar` for variables whose value can be changed by users
6. please run checkdoc to avoid typos in your docstrings (e.g., "propertiese")
7. `org-snooze-left-trim-special-chars` could use `string-trim-left` (same for `org-snooze-trim-*`)
8. `org-snooze-trim-state-chars` could use `string-prefix-p` which doesn't require `save-match-data`. The `dolist` form could have `s` at the end of its first argument so you wouldn't have to add `s` after the `dolist`. The `(if (string-match…` could be replaced with a `when`. The function could be renamed not to end with `-chars` because it's trimming states directly.
9. I suggest you add a `;;;###autoload` cookie before `org-snooze` function so it could be used before `org-snooze` is required.
10. You may extract functions out of `org-snooze`. This will ease code reading and automated testing.
12. Your code might face problem if the snooze file starts with some configuration lines (e.g., for export).
13. `add-to-list` already checks if the new element is already part of the list

**Comment by xueeinstein** [comment]
Hi @DamienCassou, thank you for your review! I updated my code to support new function and followed most of your reviews.  Please have a check.

**Comment by purcell** [comment]
Thanks, including for your patience! This looks useful, and great job fixing things up. Some further notes from me:
- Why not use a single `replace-match` pass [here](https://github.com/xueeinstein/org-snooze.el/blob/5fdf5025563851b695bb0e72811ea6cc48153685/org-snooze.el#L55)? You can combine the list of strings into a single regexp using `regexp-opt`.
- Please place the `lexical-binding` form on the first line, after the package description. Some Emacs versions ignored it if it was not on that line.

Neither of those is a blocker to merging, which I will do now - welcome to MELPA! :tada:

**Comment by xueeinstein** [comment]
Hi Purcell, I updated my code followed your new comments. Thank you for the merge!

**Pull request merged**
