### PR TITLE
Reopen Add select-themes recipe

### PR DESCRIPTION
**Pull request by jasonm23**

### CODE REVIEW

**Comment by jasonm23** [comment]
hmm @purcell can you make sense of this travis error?

**Comment by jasonm23** [comment]
Assume this is the problem?

```
;;; darcsum

Fetcher: darcs
Source: http://hub.darcs.net/simon/darcsum

Cloning http://hub.darcs.net/simon/darcsum to /home/travis/build/melpa/melpa/working/darcsum/
Command '(env LC_ALL=C /usr/bin/timeout -k 60 600 darcs get http://hub.darcs.net/simon/darcsum /home/travis/build/melpa/melpa/working/darcsum/)' exited with non-zero status 127: /usr/bin/timeout: failed to run command `darcs': No such file or directory


travis_time:end:0490f5db:start=1455192937527609832,finish=1455194123839712843,duration=1186312103011
[0K
[31;1mThe command "./run-travis-ci.sh" exited with 255.[0m

Done. Your build exited with 1.
```

**Comment by purcell** [comment]
Thanks. You can ignore that build error (see #3592). The more comprehensive Travis build process is still a work in progress, and currently frequently produces false negatives.

You're missing a `provide` form. Also, less importantly, `Interactively Select themes` should be `Interactively select themes`.

The `-- default --` string looks hokey to me. `completing-read` has built-in handling of defaults, and checking the selection against the "default" string is weird, as is all the backquote interpolation.

**Comment by jasonm23** [comment]
I got caught up in solving it with splice, and knew all along Default is part of completing-read. I can fix that later today hopefully.

**Comment by purcell** [comment]
You can just use the code in `load-theme`, which begins something like this:

```el
  (interactive
   (list
    (intern (completing-read "Load custom theme: "
			     (mapcar 'symbol-name
				     (custom-available-themes))))
    nil nil))
  (unless (custom-theme-name-valid-p theme)
     ... do stuff
```

**Comment by purcell** [comment]
i.e. you're basically writing a version of `load-theme` which turns off all other themes, afaict.

**Comment by jasonm23** [comment]
Yup, check out helm-themes it's what I wanted to do minus Helm.

**Comment by jasonm23** [comment]
Upstream fixed.

**Comment by jasonm23** [comment]
Hold on, still yak shaving...

**Comment by jasonm23** [comment]
Ok, all done (0.1.3)

**Comment by jasonm23** [comment]
ref jasonm23/emacs-select-themes

**Comment by purcell** [comment]
Thanks. Sent you a typo fix in https://github.com/jasonm23/emacs-select-themes/pull/1.

**Pull request merged**
