### PR TITLE
Add recipe for hover

### PR DESCRIPTION
**Pull request by ericdallo**
### Brief summary of what the package does

This package allows running the [hover](https://github.com/go-flutter-desktop/hover) binary as an interactive inferior process.

### Direct link to the package repository

https://github.com/ericdallo/hover.el

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer
None needed.

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```
 hover.el     1   1 warning         The package summary should start with an uppercase letter or a digit. (emacs-lisp-package)
 hover.el     8   4 warning         You should include standard keywords: see the variable `finder-known-keywords'. (emacs-lisp-package)
 hover.el    39   1 error           "flutter-sdk-path" doesn't start with package's prefix "hover". (emacs-lisp-package)
 hover.el   141   1 error           "build-hover-command" doesn't start with package's prefix "hover". (emacs-lisp-package)
```

**Comment by ericdallo** [comment]
Thanks @conao3, I added some tests a CI for checking these and already fixed.

**Comment by conao3** [comment]
Thanks your improvement!
I found some issues with your package.

1. Please define package customization group.
2. Please concider using when/unless instead of if which have no else form.
3. Please use proper indent in the whole Elisp file.

BTW, why are you use this hook instead of write in `hover-mode` major mode definition?
https://github.com/ericdallo/hover.el/blob/56f72a157d8e690a9628f56b659a194c534635c4/hover.el#L179

**Comment by ericdallo** [comment]
Thanks for the help @conao3, I found this way to configure some inital setup, I don't know any other way :disappointed: , could you suggest a better solution?

**Comment by conao3** [comment]
How about this? I do the same thing and I think it's easier.
```diff
1 file changed, 5 insertions(+), 10 deletions(-)
hover.el | 15 +++++----------

modified   hover.el
@@ -108,13 +108,6 @@ The function's name will be NAME prefixed with 'hover-'."
   "Hot reload hover buffer and show window again."
   (pop-to-buffer-same-window hover-buffer-name t))
 
-(defun hover--initialize ()
-  "Helper function to initialize Hover."
-  (setq comint-process-echoes nil)
-  (when hover-flutter-sdk-path
-    (let ((flutter-command-path (concat (file-name-as-directory hover-flutter-sdk-path) "bin")))
-      (setenv "PATH" (concat flutter-command-path ":" (getenv "PATH"))))))
-
 ;;; Key bindings
 
 (defconst hover-interactive-keys-alist
@@ -185,9 +178,11 @@ args."
 ;;;###autoload
 (define-derived-mode hover-mode comint-mode "Hover"
   "Major mode for `hover-run'."
-  (setq comint-prompt-read-only t))
-
-(add-hook 'hover-mode-hook #'hover--initialize)
+  (setq comint-prompt-read-only t)
+  (setq comint-process-echoes nil)
+  (when hover-flutter-sdk-path
+    (let ((flutter-command-path (concat (file-name-as-directory hover-flutter-sdk-path) "bin")))
+      (setenv "PATH" (concat flutter-command-path ":" (getenv "PATH"))))))
 
 (provide 'hover)
 ;;; hover.el ends here
```

**Comment by ericdallo** [comment]
Done @conao3 , I don't know how I didn't think of that :sweat_smile:

**Comment by ericdallo** [comment]
@conao3 Could you approve the PR please :sweat_smile:

**Comment by conao3** [comment]
Honestly, as I have no push rights, I cannot merge this PR.
Please wait for MELPA maintainer's comment.

**Comment by ericdallo** [comment]
Sorry for tag you here, but could you merge it @riscy? :sweat_smile:

**Comment by ericdallo** [comment]
@riscy Do I need to reference this PR somewhere?

**Comment by riscy** [comment]
Sorry, there's still quite a backlog.  I'll get to it! :)

**Comment by ericdallo** [comment]
Thanks for the reply!!

**Comment by riscy** [comment]
This looks solid to me.  A couple quick comments:

- hover.el#L211: It's safer to sharp-quote function names; use `#'`
- Is `(setq comint-prompt-read-only t)` really necessary?  This feels like something users might set to their own preferences, just like with comint-mode in general.

I wouldn't say either of the above are blockers, since everything else seems to check out.   Welcome to MELPA!

**Comment by ericdallo** [comment]
Thanks @riscy, I'll check these suggestions!

**Pull request merged**
