### PR TITLE
Add citar-embark recipe

### PR DESCRIPTION
**Pull request by bdarcus**
I'm the creator and maintainer of the [citar package](https://github.com/emacs-citar/citar).

This PR has two commits, which together splits the package in two.

The first is for a new, small, `citar-embark` integration package for citar, to avoid us having to use `with-eval-after-load` and such, and simplify configuration for users.

The other adjusts the citar existing recipe so it excludes `citar-embark.el`, since the code shares the same repo.

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass on the new citar-embark:

- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to citar-embark.el (I see the repo is GPL-licensed, but a user may only have the file in their possession)
- The `;;; Commentary` "Description" has probably been left that way as a stub

And since we're here it may be worth checking on some issues in citar:

- You'll have to check my work, but you may be able to drop the dep on org 9.5 if you simply add a dependency on Emacs 28.1
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to citar-capf.el
- When loading citar-capf.el:
  citar-capf.el:Error: Emacs 28.1 couldn't load:
  (void-function citar--ref-completion-table)

Note that byte-compiling passes for citar-capf.el, but loading appears to not be working.

**Comment by bdarcus** [comment]
Oops; sorry about the oversights!

Couple of followups:

On the license, do you mean I want:

```
;; License: GPL-3.0-or-later
```

... or:

```
;; SPDX-License-Identifier: GPL-3.0-or-later
```

...?

And on:

> ... you may be able to drop the dep on org 9.5 if you simply add a dependency on Emacs 28.1

Yes, and in fact, we do rely in key places on Emacs 28 features for the completion UI (namely, affixation and grouping). I just didn't want to be too aggressive, and I know people update org independently of Emacs.

**Comment by riscy** [comment]
> `;; SPDX-License-Identifier: GPL-3.0-or-later`

Exactly this.  I should actually start linking to https://spdx.dev/ids/ instead.

**Comment by bdarcus** [comment]
OK, so that means changing the existing `License` lines too? E.g. that's a new thing?

And do all files need this, or just the main package files?

If the latter, then `citar-capf.el` wouldn't be included, since it's part of the citar package?

**Comment by riscy** [comment]
I'm about to step out the door, but the existing full license boilerplate is fine and can stay the same.  Only the license line in citar-capf.el is nonstandard; if you want a one-liner I'd strongly recommend going with the SPDX style, because it is unambiguously machine detectable.

**Comment by bdarcus** [comment]
But if citar-capf is part of the citar package, shouldn't I remove the
license line altogether?

**Comment by bdarcus** [comment]
Sorry; I had I misunderstood one obvious detail; that all files do have license info; it's just some of them include the actual text.

Anyway, changes committed to the citar repo:

- added the `;; SPDX-License-Identifier: GPL-3.0-or-later` to `citar-capf.el`, `citar-embark.el`, and also while I was at it `citar.el`
- fixed compilation error in `citar-capf.el`
- fixed commentary in `citar-embark.el`

**Comment by riscy** [comment]
Thanks!  All set here. :)

**Pull request merged**
