### PR TITLE
feat: adds new package: magit-stats

### PR DESCRIPTION
**Pull request by LionyxML**
### Brief summary of what the package does
A package that generates a Repository Statistics Report (git) from inside Emacs.

You call `magit-stats` when inside a file inside a git folder and you're presented with some options:
- An HTML report rendered by shr on its own buffer
- An HTML report saved as an html file and opened with the OS default browser
- An JSON report output to it's own buffer

This package is actually a "wrapper" for a cli tool (written in NodeJS) with the same name hosted on npm registry: https://www.npmjs.com/package/magit-stats.

Here's an image of it in action: 
image

### Direct link to the package repository

https://github.com/LionyxML/magit-stats

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

This package, as said above, is a wrapper for a cli tool. It needs the executable `npx` that automatically "downloads" and runs a binary from the Npm registry. This is a very common pratice on the NodeJS world. If your machine have nodeJS (node@latest and npm@latest) you probably have npx installed, if not, it will be necessary, more info: https://www.npmjs.com/package/npx

This project is the result from an idea shared with @tarsius, that may be found here: https://github.com/magit/magit/discussions/4846. I hope he is OK with the package name :) 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by tarsius** [comment]
That looks very nice. I'll play with it soon; once I've got the node thing figured out.

> I hope he is OK with the package name :)

Yes, that's okay. And I guess using the same name for the cli tool serves as advertisement for magit, for those unfortunate souls that don't use emacs yet. :wink:

**Comment by progfolio** [comment]
Cool idea.

Some suggestions:

Considering the package requires npx, is it worth supporting Emacs 24.4? 


In your defgroup you define the package `:prefix` as:

```emacs-lisp
:prefix "magit-stats-*"
```

The value is intended to be a string, not a regular expression. 
That string is trimmed from symbols in the customize buffer/menu
when `custom-unlispify-remove-prefixes` is non-nil.
Your current value will trim one character too many.
`"magit-stats-"` should work properly.

For `magit-stats`:

It might be better to use mnemonic key bindings for the interactive options.
Better yet, let the user decide via a user option.

The advertisement in the read-char-choice prompt is excessive.
I would drop: `"[magit-stats] (A NON Official maybe future magit plugin)"`.

The type of output could be a parameter of `magit-stats`.
That would make it friendly to call programmatically and make better use of the interactive spec.
e.g.

```emacs-lisp
(defun magit-stats (output)
  "Generate GIT Repository Statistics OUTPUT."
  (interactive (read-char-choice "
a - Generate HTML report to a new buffer
b - Generate HTML report to a file and open on OS default viewer
c - Save JSON report data to a new buffer
q - Quit
" '(97 98 99 113)))
;;etc
```

An even more flexible approach would be have magit-stats dispatch to a function which does its work.
This would allow the different types of output to be called more easily, users to define the prompt keys, and the command to be easily extended.


<details><summary>For example:</summary>
```emacs-lisp
(defcustom magit-stats-backends
  '((?a magit-stats-in-buffer   "Generate HTML report in a new buffer")
    (?b magit-stats-with-viewer "Open HTML report with default viewer")
    (?c magit-stats-json-buffer "Save JSON report data in buffer"))
  "List of backends for the `magit-stats' command.
Each entry is of form: (CHAR FN DESCRIPTION)
ETC..."
  :type 'list)

;;;###autoload
(defun magit-stats-in-buffer ()
  (interactive)
  (with-current-buffer (get-buffer-create "*magit-stats-stdout*")
    (message "Loading...")
    (erase-buffer)
    (shell-command magit-stats-command-html-stdout (current-buffer))
    (shr-render-buffer (current-buffer))
    (pop-to-buffer (current-buffer))
    (kill-buffer "*magit-stats-stdout*")
    (message "Loaded!")))

;;;###autoload
(defun magit-stats-with-viewer ()
  (interactive)
  (message "Loading...")
  (shell-command  magit-stats-command-html-open)
  (message "Loaded!"))

;;;###autoload
(defun magit-stats-json-buffer ()
  (with-current-buffer (get-buffer-create "*magit-stats-stdout*")
    (message "Loading...")
    (erase-buffer)
    (shell-command magit-stats-command-html-json-stdout (current-buffer))
    (pop-to-buffer (current-buffer))))

;;;###autoload
(defun magit-stats (backend)
  "Generate GIT Repository Statistics via BACKEND."
  (interactive
   (list (car (alist-get (read-char-choice
                          (format "magit-stats backend (%s):\n%s"
                                  (substitute-command-keys "\\[keyboard-quit] to quit")
                                  (mapconcat (lambda (b) (format "%c - %s\n" (car b) (car (last b))))
                                             magit-stats-backends))
                          (mapcar #'car magit-stats-backends))
                         magit-stats-backends))))
  (if (functionp backend) (funcall backend) (user-error "Unknown backend: %s" backend)))
```
</details>

Consider adding an autoload cookie to `magit-stats` as in the example above.

Consider putting the buffers which display data into `special-mode` after populating them.
It will put them in read-only mode and bind `q` to bury the buffer.

Prefer `call-process` over `shell-command` when possible.
Otherwise, be sure to quote arguments via `shell-quote-argument`.

There is no error handling if the npx command fails.
It would be useful to throw a user-error if, for example, the command is called from a buffer which is not in a git repository.
Currently I get the following (confusing from a user perspective) buffer instead:

<details>
fatal: not a git repository (or any of the parent directories): .git node:child_process:960 throw err; ^
Error: Command failed: git log --all --pretty=format:'{%n "commit": "%H",%n "abbreviated_commit":
"%h",%n "tree": "%T",%n "abbreviated_tree": "%t",%n "parent": "%P",%n "abbreviated_parent":
"%p",%n "refs": "%D",%n "encoding": "%e",%n "sanitized_subject_line": "%f",%n "commit_notes":
"%N",%n "verification_flag": "%G?",%n "signer": "%GS",%n "signer_key": "%GK",%n "author": {%n
"name": "%aN",%n "email": "%aE",%n "date": "%aD"%n },%n "commiter": {%n "name": "%cN",%n
"email": "%cE",%n "date": "%cD"%n }%n},' fatal: not a git repository (or any of the parent directories): .
git at checkExecSyncError (node:child_process:885:11) at execSync (node:child_process:957:15) at
/home/n/.npm/_npx/bdf4407d3dcdebb3/node_modules/magit-stats/bin/magit-stats.cjs:67:3147846
at /home/n/.npm/_npx/bdf4407d3dcdebb3/node_modules/magit-stats/bin/magit-stats.cjs:67:3149346
at 918
(/home/n/.npm/_npx/bdf4407d3dcdebb3/node_modules/magit-stats/bin/magit-stats.cjs:67:3149353)
at r
(/home/n/.npm/_npx/bdf4407d3dcdebb3/node_modules/magit-stats/bin/magit-stats.cjs:67:3150514)
at /home/n/.npm/_npx/bdf4407d3dcdebb3/node_modules/magit-stats/bin/magit-stats.cjs:67:3151010
at Object.
(/home/n/.npm/_npx/bdf4407d3dcdebb3/node_modules/magit-stats/bin/magit-stats.cjs:67:3151018)
at Module._compile (node:internal/modules/cjs/loader:1246:14) { status: 128, signal: null, output: [
null, Buffer(0) [Uint8Array] [], Buffer(69) [Uint8Array] [ 102, 97, 116, 97, 108, 58, 32, 110, 111, 116, 32,
97, 32, 103, 105, 116, 32, 114, 101, 112, 111, 115, 105, 116, 111, 114, 121, 32, 40, 111, 114, 32, 97, 110,
121, 32, 111, 102, 32, 116, 104, 101, 32, 112, 97, 114, 101, 110, 116, 32, 100, 105, 114, 101, 99, 116,
111, 114, 105, 101, 115, 41, 58, 32, 46, 103, 105, 116, 10 ] ], pid: 1518922, stdout: Buffer(0) [Uint8Array]
[], stderr: Buffer(69) [Uint8Array] [ 102, 97, 116, 97, 108, 58, 32, 110, 111, 116, 32, 97, 32, 103, 105, 116,
32, 114, 101, 112, 111, 115, 105, 116, 111, 114, 121, 32, 40, 111, 114, 32, 97, 110, 121, 32, 111, 102, 32,
116, 104, 101, 32, 112, 97, 114, 101, 110, 116, 32, 100, 105, 114, 101, 99, 116, 111, 114, 105, 101, 115,
41, 58, 32, 46, 103, 105, 116, 10 ] } Node.js v19.6.0 
</details>


<details><summary>Byte compilation warnings:</summary>
search filter: "#latest #linked-errors warn"
<table>
<thead><th>Package</th><th>Status</th><th>Info</th><th>Time</th></thead>
<tbody>
<tr><td>magit-stats</td><td>byte-compilation</td><td>magit-stats.el:10:73 Warning: the function ‘shr-render-buffer’ is not known to be defined.</td><td>289.917462</td></tr></tbody>
</table>
</details>

**Comment by LionyxML** [comment]
Thanks @progfolio!

I've refactored https://github.com/LionyxML/magit-stats/blob/main/magit-stats.el following your feedback.

There was a leak to the cli package and the error message should not be something like that. I fixed it in the cli and also covered error cases on the emacs package that now uses `call-process`.

It still requires a version of emacs because `alist-get` (linter was not happy without the correct emacs version).

Also added the require for `shr` so the build runs clean.

Do I have to resubmit something to this PR?

**Comment by progfolio** [comment]
> Do I have to resubmit something to this PR?

No need. @riscy will review when they have time. I independently review packages, so I don't have any say on what makes it into MELPA. However, I can help test and get the package to a state where the process is faster.

Some more suggestions:

Currently all commands fail for me with the following ouput:

```emacs-lisp
sh: line 1: magit-stats: command not found
```

This is due to the construction of the commands passed to \`call-process\`. Calling the npx binary directly via \`call-process\` instead of starting a shell to call should work. e.g.

```emacs-lisp
(call-process "npx" nil (get-buffer-create "*test*") nil "magit-stats" "--html" "--stdout")
```

Note, too, how the arguments are passed individually instead of a single string. You could use \`split-string\` on your current user options, or change them to be lists of strings. e.g.

```emacs-lisp
(defcustom magit-stats-command-html-stdout '("--html" "--stdout")
```

I also think it's safe to assume the "npx magit-status" part of each command. That would allow you to simplify the options. Since each command offers the option to customize the options, it might be worth rolling everything in to the \`magit-stats-backends\` option. That will prevent the need to add a new defcustom every time a new command is added so that its options can also be customized. If you decide to go that route, it might also be worth making the option accept plists to make the data more declarative. e.g.

```emacs-lisp
(defcustom magit-stats-backends
  '((:key ?h :command magit-stats-in-buffer :description "HTML report in a new buffer" :options ("--html" "--stdout"))
    ;;etc
    ))
```

This would require updating the \`magit-stats\` command to use \`plist-get\` to extract the values:

```emacs-lisp
(defun magit-stats (backend)
  "Generate GIT Repository Statistics via BACKEND."
  (interactive
   (list (alist-get
          (read-char-choice
           (format "magit-stats backend (%s):\n%s"
                   (substitute-command-keys "\\[keyboard-quit] to quit")
                   (mapconcat (lambda (b) (format "%c - %s\n" (plist-get b :key) (plist-get b :description)))
                              magit-stats-backends))
           (mapcar (lambda (b) (plist-get b :key)) magit-stats-backends))
          (mapcar (lambda (b) (cons (plist-get b :key) (plist-get b :command))) magit-stats-backends))))
  (if (functionp backend) (funcall backend) (user-error "Unknown backend: %s" backend)))
```

**Comment by LionyxML** [comment]
Thanks again @progfolio !

I think for now I'll just make things simpler even if it means a little bit of hardcoding.

May you check if the new version calling "npx" directly works for you?

**Comment by progfolio** [comment]
> May you check if the new version calling "npx" directly works for you?

Now I get:

> sh: line 1: magit-stats: command not found

It may have to do with the value of default-directory when the process is called or the shell PATH (if that's how npx works). If that turns out to be a pain to figure out, you might want to revert to the shell-command functions.

**Comment by LionyxML** [comment]
Yeah, it really became a pain, lol.

I think I settled with something from both implementations here.

I reverted to shell-command, but "hardcoded" the commands, so the user cannot make any harmful things with customization. Errors will be printed to the buffer (and now are human readable from the cli).

Also the choice menu is way better your way.

Tell me if everything looks okay now @progfolio ! And thanks again for reviewing it.

**Comment by progfolio** [comment]
> Yeah, it really became a pain, lol.

I had some more time to look into it, as I was puzzled myself.
The `sh: line 1: magit-stats: command not found` error only happens when I invoke `npx magit-stats` from within the magit-stats repository. Other repositories work fine with that method.
My hunch is it's something specific to the way npm/npx work rather than something on the Emacs side of things.

I have some more suggestions, which I implemented as I was looking over the code.
I've pushed them here:

https://github.com/progfolio/magit-stats/commit/99cbfc4ef6f3eee76af9e680847c383659e5cdcc

Feel free to try those out and use any of the code you like.

Some other things I noticed once I got the binary working:

When generating the html output in a buffer, I get the following error in my \*Messages* buffer:

```
Error parsing SVG image: XML parse error: Error domain 1 code 9 on line 2 column 925 of data: Input is not proper UTF-8, indicate encoding !
Bytes: 0xC1 0xA2 0xC0 0x80
```

The CLI leaves behind git-stats.html/json files when using commands. Personally, I'd rather it didn't as the information is mostly transitory in active repostories and the files put the repo in a dirty state. The user could also just save the generated buffers on to disk if they desire to keep them around. I would suggest reconsidering the file generation (either skipping it altogether, or writing to `temporary-file-directory` instead of `default-directory`).


I tried running the CLI tool on the emacs source repository (which is large).
It looks like the JS heap gets exhausted in that case:

<details><summary>core dump</summary>

```
<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7fa27e28054d node::Abort() [/usr/bin/../lib/libnode.so.111]
 2: 0x7fa27df66b3f node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/usr/bin/../lib/libnode.so.111]
 3: 0x7fa27e63cf64 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/bin/../lib/libnode.so.111]
 4: 0x7fa27e63d358 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/bin/../lib/libnode.so.111]
 5: 0x7fa27e82fa3c  [/usr/bin/../lib/libnode.so.111]
 6: 0x7fa27e835eed  [/usr/bin/../lib/libnode.so.111]
 7: 0x7fa27e847866 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/usr/bin/../lib/libnode.so.111]
 8: 0x7fa27e849776 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/../lib/libnode.so.111]
 9: 0x7fa27e84a791 v8::internal::Heap::CollectAllGarbage(int, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/../lib/libnode.so.111]
10: 0x7fa27e7c89ed v8::internal::StackGuard::HandleInterrupts() [/usr/bin/../lib/libnode.so.111]
11: 0x7fa27ebeb695 v8::internal::Runtime_StackGuardWithGap(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/../lib/libnode.so.111]
12: 0x7fa27e5383f9  [/usr/bin/../lib/libnode.so.111]
Aborted (core dumped)
```

</summary>

A possible improvement for the UI would be for the reports to include the path of the repository. As it stands, every repository just gets the heading "Repository Statistics".

**Comment by LionyxML** [comment]
Great! 
We're heading to progress @progfolio ! :)

I'm fixing this annoying bugs, meawhile I just generated this to MELPA repo:
image
Does it make any sense?

As soon as I get a working version I'll update here.

**Comment by LionyxML** [comment]
@progfolio just updated the npx package.

`npx magit-stats --version` should be 1.0.19-dev.

If your npx refuses to use the current version, manually deletion might be needed: `rm -rf ~/.npm/_npx`.

`npx magit-stats --help` will now show a new option, the memory heap size that node is using. I defaulted it to be a lot bigger then original, but you may force it to a bigger number if inside a really huge git folder.

json is now a boolean so you won't be able to rename this file for now.

There was also a bug where double quotes in the authors name broke the parsers, this was fixed.

The only know bug for the cli now is passing "--html and --json" defaults to json, I'll make then a OR option later. Also later I'll add the name of the folder (and probably the remote URL) to the rendered HTML.

That's it, it would be nice to see if it worked for you! Also feel free to PR my repo.

**Comment by riscy** [comment]
Very cool visuals, thanks for this.

Should we be using the default recipe? `(magit-stats :repo "LionyxML/magit-stats" :fetcher github)` is equivalent at the moment.

I get this byte-compile nag --

`magit-stats.el` with byte-compile using Emacs 28.1:
```
magit-stats.el:86:36: Warning: mapconcat called with 2 arguments, but requires
    3
```

**Comment by LionyxML** [comment]
Hello there!

@progfolio : I spent some time polishing the cli tonight, mostly fixing some bugs, current version is now `1.0.20-dev`.  It now shows the repository directory name as the repo name (name can also be passed through cli now) and the remote URL.

As @riscy suggested I changed the recipe to the default.

I have no warnings compiling it locally: `Emacs version: 29.0.60`. And the pipeline also shows no warnings (but I don't now if it is configured to show warnings):
image

Is it still a problem there?

**Comment by tarsius** [comment]
> Ping?

@riscy usually reviews on Sundays.

**Comment by riscy** [comment]
Thanks for accommodating --

> I have no warnings compiling it locally: Emacs version: 29.0.60

I think this is because you're using Emacs 29, which is still an upcoming release, but I byte-compiled with 28.1; moreover your package metadata claims `Package-Requires: ((emacs "25.1"))`.

For Emacs 28 (and 25.1) you'll need to add an explicit SEPARATOR argument to that function.  (Maybe it defaults to the empty string in Emacs 29?  I don't know myself.)

**Comment by progfolio** [comment]
> For Emacs 28 (and 25.1) you'll need to add an explicit SEPARATOR argument to that function. (Maybe it defaults to the empty string in Emacs 29? I don't know myself.)

Yes. The separator was made optional in 29:

https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=d652efcd087099c71cd76c4bbf2bbf04314844b4

**Comment by LionyxML** [comment]
Living and learning! :)

Another thing required emacs 25.1 that I can't remember now (but it was pointed by the linter).

I just added the third param as a blank string. It still works and now byte-compiles gracefully, both on macOS with emacs 29 and Debian with emacs 27.1.

**Comment by riscy** [comment]
Thanks -- looks good to merge.

While I do so, I wonder if `(with-current-buffer (get-buffer-create "*magit-stats-stdout*")` makes more sense as `(with-temp-buffer`; as far as I can tell there's no reason to name it, since you also explicitly kill it afterward.

**Pull request merged**
