### PR TITLE
add recipe ob-sly.

### PR DESCRIPTION
**Pull request by stardiviner**
https://github.com/stardiviner/ob-sly

### CODE REVIEW

**Comment by purcell** [comment]
It feels like you should be declaring a package dependency on `sly` and simply `require`-ing it. `declare-function` is an unnecessary shortcut, and this package won't work without `sly` installed anyway.

**Comment by stardiviner** [comment]
@purcell I check out MELPA  README, but have not found any `:depend` or similar keywords. Where should I declare this dependency?

**Comment by stardiviner** [comment]
I updated my `ob-sly`. added `(require 'sly)` and commented out that `declare-function` line.

**Comment by purcell** [comment]
Add a metadata header like this:

```
;; Package-Requires: ((sly "2.14"))
```

:-)

**Comment by purcell** [comment]
(i.e. in your ob-sly.el file, next to the `;; Author:` header.)

**Comment by stardiviner** [comment]
Updated, check it out. Thanks for reviewing.

**Comment by purcell** [comment]
Super, thanks.

**Pull request merged**
