### PR TITLE
Add tempel-collection

### PR DESCRIPTION
**Pull request by Crandel**
### Brief summary of what the package does

This package provide a collection templates for different Emacs modes using [tempel](https://github.com/minad/tempel) template engine

### Direct link to the package repository

https://github.com/Crandel/tempel-collection

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by minad** [comment]
See also #8282. There is also a discussion on the https://github.com/minad/tempel/issues/68 if it is better to package templates separately per language or as a single collection package.

**Comment by riscy** [comment]
I commented on #8282 but in the meantime here's a quick first pass --

`tempel-collections.el` with package-lint 20221003.1636:
```
3 issues found:
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
8:23: warning: Use a non-snapshot version number for dependency on "tempel" if possible (e.g. [1.5](https://stable.melpa.org/#/tempel)?)
55:1: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
```
Perhaps the `eval-after-load` is a false positive in the context of these libraries.

Package and license:
- Prefer the default recipe or `:defaults`, if possible, e.g. `(tempel-collections :repo "Crandel/tempel-collections" :fetcher github :files (:defaults "templates"))`

**Comment by Crandel** [comment]
Hi @riscy,
thank you for quick reply.
I fixed first issue.
Second issue is controversial for me as this is a tempel version from Melpa. Should I use elpa version `0.5` instead?

**Comment by minad** [comment]
@Crandel Maybe the name tempel-collection would be better?

**Comment by Crandel** [comment]
> @Crandel Maybe the name tempel-collection would be better?

I thought about collection, but more natural for me sounds one template collection per mode, so for several modes it would be collections.

**Comment by minad** [comment]
If we don't listen to type theorists a collection of collections is still a collection. ;)

**Comment by Crandel** [comment]
> If we don't listen to type theorists a collection of collections is still a collection. ;)

Valid point. Will update the name and repo link

**Comment by riscy** [comment]
> Second issue is controversial for me as this is a tempel version from Melpa. Should I use elpa version 0.5 instead?

I think the issue with the dependency on the tempel version has been resolved - I'm not ignoring this question, I just think you've found the solution. :)

This looks good from my end -- merging!

**Pull request merged**
