### PR TITLE
Add php-align recipe

### PR DESCRIPTION
**Pull request by someonewithpc**
### Brief summary of what the package does
Rules list for aligning in PHP

### Direct link to the package repository
https://github.com/tetsujin/emacs-php-align

### Your association with the package

Just a user

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [ x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [ x ] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x ] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [ x ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
This package is closely related to `php-mode`, so I think it should be achieved by PR to `php-mode` rather than providing it as a separate package.
What do @tesujin (the pakcage author), @zonuexe (the `php-mode` maintainer) think?

**Comment by riscy** [comment]
Noting here that this is a 9-year-old package with what appears to be an inactive maintainer (although you never know -- we'll wait.)   And yet, surprisingly, is well-behaved (telling the user to add a hook instead of forcing one in when the package is loaded).

**Comment by tetsujin** [comment]
Thanks. I'm  https://github.com/tetsujin/emacs-php-align author.
emacs-php/php-mode#615 plan looks very good!

**Comment by zonuexe** [comment]
@someonewithpc @riscy 
php-align.el has been merged into `php-mode` package. (Thanks @tetsujin!)

**Comment by conao3** [comment]
My apologies to @tetsujin. I did typo your username and mentioned another person...
Thanks, @someonewithpc, @zonuexe, and @tetsujin for quick and good collaboration!

**Comment by riscy** [comment]
This is a great outcome.  @someonewithpc I'll close this out, but feel free to respond here with followups (or reopen if it was closed incorrectly).

**Pull request closed without merging**
