### PR TITLE
add cool-mode recipe

### PR DESCRIPTION
**Pull request by nverno**
### Brief summary of what the package does

A major mode for editing Cool programming language files.
https://en.wikipedia.org/wiki/Cool_(programming_language)

### Direct link to the package repository

https://github.com/nverno/cool-mode

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for your patience!  Quick first pass --

`cool-completion.el` with package-lint 20220607.738:
```
3 issues found:
7:0: error: Package-Requires outside the main file have no effect.
78:0: error: "company-cool-add-keywords" doesn't start with package's prefix "cool".
85:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

`cool-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- cool-mode.el#L220: It's safer to sharp-quote function names; use `#'`
- cool-mode.el#L225: It's safer to sharp-quote function names; use `#'`
- cool-mode.el#L343: Terminate auto-mode-alist entries with `\\'`
```

**Comment by nverno** [comment]
Thankyou, updated - except for warning about `eval-after-load`.

**Comment by riscy** [comment]
Just writing to let you know I'm not ignoring this PR, but I strive to try to give one review to each individual author on every pass I do.  I'll take a look at this one in the next batch.

**Comment by riscy** [comment]
Looks good - thanks!

**Pull request merged**
