### PR TITLE
Add Puni

### PR DESCRIPTION
**Pull request by AmaiKinono**
### Brief summary of what the package does

Puni is a package for soft deletion, which means deleting while keeping expressions balanced. It offers pre-defined soft deletion commands, and an API to easily define your own.

### Direct link to the package repository

https://github.com/AmaiKinono/puni

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback

   I left a "Global minor modes should be autoloaded" error. I actually wrapped it into a `progn` form and autoload it, then the user could enable `puni-global-mode` before `puni` is actually loaded. I learned this technique from [selectrum](https://github.com/raxod502/selectrum/blob/97693d0aea2c548197e9d1de3bdedf8e703775a4/selectrum.el#L2995).

- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings

   Let me explain this one. There are many functions doing the same thing, but in different directions, like `puni--forward-blanks` and `puni--backward-blanks`. In all the "backward" functions, I simply write the docstring as "Backward version of the forward function". This reduces the cost of maintaining 2 similar docstrings.

   In my test suite, I [hacked checkdoc a bit](https://github.com/AmaiKinono/puni/blob/master/scripts/checkdoc-hack.el), so it accepts missing arguments in the "Backward version of ..." docstrings, but all other errors are keeped, so there are really no problems.

   Besides, all interactive commands have full docstrings, no matter if they are forward or backward commands.

- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
I can tell from the readme that you've put a lot of work into this package.  It looks impressive, well-documented, and appealing.

However, as you mention in the readme, Emacs already provides these basic tools.  In fact, Emacs already has a `kill-sexp` command:

```
kill-sexp is an interactive compiled Lisp function in ‘lisp.el’.

It is bound to C-M-k.

(kill-sexp &optional ARG)

Kill the sexp (balanced expression) following point.
With ARG, kill that many sexps after point.
Negative arg -N means kill N sexps before point.
This command assumes point is not in a string or comment.
```
So why is an apparently very featureful package needed to do the same simple thing that a built-in command does?

If you've already answered this in your readme, then please take this as an indication that the rationale may be too deeply buried or verbosely exposited.  :)

**Comment by AmaiKinono** [comment]
Thanks for your advice!

> Emacs already has a `kill-sexp` command

I didn't know this before. But, as I pointed out in the README:

> A major mode can provide a `forward-sexp-function`. Ideally, it should work like the built-in `forward-sexp`, but unfortunately, many of these `forward-sexp-function`s have all sorts of problems, with the prominent one being jumping out of current sexp to search for a start/end of a sexp.

This `kill-sexp` doesn't work well for such major modes.

Try this in `web-mode` (`|` is the cursor):

```html
<|a href="example.com">click me</a>
```

Call `kill-sexp`:

```html
<|click me</a>
```

(What just happened?}

But call `puni-kill-line`:

```html
<|>click me</a>
```

(I can tell it kills the content in the opening tag).

The main work done by Puni, actually, is fixing these unproperly implemented `forward-sexp-function`s in a systematic and unified way.

> Another perspective might be that, if you are offering facilities to define new movement commands in a flexible and powerful way, perhaps your package's scope (and description) ought not be focused on "deleting" things--maybe that's selling it short.

Puni doesn't offer APIs for defining movement commands. It only focuses on soft deleting (the main API is `puni-soft-delete-by-move).

And I don't considering the selling to be short. When programming, what you are doing is editing text, but what you have in mind is manipulating the syntax structure. My personal experience (being a long time smartparens user) is, programming with:

- auto pairing (offered by `electric-pair-mode`)
- soft deletion (offered by Puni)

is an approach to getting very close to "structural editing", while still keeping the flexibility of editing plain text. Soft deletion is an important part of this approach.

> It would be good to compare it with other packages that are similar, like Lispy, Smartparens, etc.

Good idea. I can do this.

> The readme would really benefit from a good table of contents. I can recommend https://github.com/alphapapa/org-make-toc :)

I agree, as the README is intense. Your package looks awesome, unfortunately I wrote my README in markdown :rofl: I can look for some other tools.

**Comment by alphapapa** [comment]
> This kill-sexp doesn't work well for such major modes.  Try this in web-mode (| is the cursor):

I see what you mean.  

> The main work done by Puni, actually, is fixing these unproperly implemented forward-sexp-functions in a systematic and unified way.

Well, not that your package isn't useful, but have you considered submitting patches to fix the `-sexp` commands in those major modes in Emacs?   That way, everything that can use those commands could benefit, including this new package of yours.

> And I don't considering the selling to be short. When programming, what you are doing is editing text, but what you have in mind is manipulating the syntax structure. My personal experience (being a long time smartparens user) is, programming with...is an approach to getting very close to "structural editing", while still keeping the flexibility of editing plain text

Yes, that's what I mean.  The bigger picture is more than just deleting.  The fundamental problem is discerning the boundaries in structure--what commands then do based on those boundaries is a separate, and much more easily handled, matter.

(With regard to that, if you haven't been following the tree-sitter-related discussions on emacs-devel, you probably should, because that would probably solve a lot of these problems at a more fundamental level--it might also, eventually, obsolete this package of yours, to some extent, but I don't say that to dissuade you.  :)

> I agree, as the README is intense. Your package looks awesome, unfortunately I wrote my README in markdown rofl I can look for some other tools.

Well, my best advice would be to use Pandoc to convert it from Markdown to Org.  It should be pretty seamless.  :)  But short of that, IIRC the `toc-org` package (sort of a friendly competitor to `org-make-toc`) also supports Markdown.

**Comment by AmaiKinono** [comment]
> but have you considered submitting patches to fix the `-sexp` commands in those major modes in Emacs?

This is too ideal. I can't fix them for all major modes that have the problem. While if I use a unified way to fix them, Puni users who use major modes that I don't use can enjoy the result.

To clarify, by

> fixing these unproperly implemented `forward-sexp-function`s in a systematic and unified way.

I did't mean I fix them one by one. I invented a mechanism to build `puni-strict-forward/backward-sexp`, a pair of "properly behaved" sexp-navigating functions, out of a partly working `forward-sexp-function`.

Also, There may already be a lot of things that depends on those (improperly implemented) `forward-sexp-functions`. Fixing them would break these things.

I'm not saying you pointed a wrong direction. I agree what you said, but the cost is way higher than creating Puni.

> Yes, that's what I mean. The bigger picture is more than just deleting. The fundamental problem is discerning the boundaries in structure--what commands then do based on those boundaries is a separate, and much more easily handled, matter.

I see. In fact, I've already implemented an `expand-region` based on Puni: https://github.com/AmaiKinono/puni/wiki/The-Puni-version-of-expand-region. Maybe Puni is actually more powerful than I thought, but that's a topic to be explored in the future.

> if you haven't been following the tree-sitter-related discussions on emacs-devel, you probably should

Actually, I followed it a little bit :D But I feel uncertain about bringing such component into Emacs. Language server client is another example.

I do like [SMIE](https://www.gnu.org/software/emacs/manual/html_node/elisp/SMIE-Indentation.html) more. If you give it a table of syntax, it gives you back 3 things:

- Reliable indent rules.
- A good `forward-sexp-function`
- `smie-close-block`

And the best about it is, it's in pure elisp.

> IIRC the `toc-org` package (sort of a friendly competitor to `org-make-toc`) also supports Markdown.

Thanks. I'll have a look.

**Comment by AmaiKinono** [comment]
I've finished these 2 items:

- Compare with ParEdit, Lispy and smartparens.
- Add a toc.

**Comment by AmaiKinono** [comment]
> perhaps your package's scope (and description) ought not be focused on "deleting" things--maybe that's selling it short.

You are seriously right :D I just figured out how to implement slurp:

9376b2ea9283b7d86e0fb2510e8b4ce0a4a5230e

barf, splice, raise... they can be implemented using the same technique.

**Comment by riscy** [comment]
Thanks both -- this looks like a high-quality package.  Here's a quick run over the checklist --

### puni.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
puni.el:140: Argument `bound' should appear (as BOUND) in the doc string
Warning (emacs): 
puni.el:169: Argument `string' should appear (as STRING) in the doc string
Warning (emacs): 
puni.el:186: Argument `bound' should appear (as BOUND) in the doc string
Warning (emacs): 
puni.el:209: Argument `syntax' should appear (as SYNTAX) in the doc string
Warning (emacs): 
puni.el:227: Argument `bound' should appear (as BOUND) in the doc string
Warning (emacs): 
puni.el:275: Argument `bound' should appear (as BOUND) in the doc string
Warning (emacs): 
puni.el:423: Argument `bound' should appear (as BOUND) in the doc string
Warning (emacs): 
puni.el:717: Argument `probe' should appear (as PROBE) in the doc string
Warning (emacs): 
puni.el:809: Argument `skip-single-line-comments' should appear (as SKIP-SINGLE-LINE-COMMENTS) in the doc string
```
I think your rationale above ("I simply write the docstring as "Backward version of the forward function") is fine after going through them.  In the future though I'd ask that you consider accommodating checkdoc to the best extent you can.  This is my personal opinion and not that of the MELPA maintainers at large, but until we change the checklist requirement around checkdoc, it's generally more work for reviewers if we have to manually check and/or negotiate your rationale for checklist exceptions.  (And, as a group, contributors have more time than reviewers.)

package-lint (using version 20210528.2348):
```
1 issue found:
1419:2: error: Global minor modes should be autoloaded or, rarely, `:require' their defining file (i.e. ":require 'puni"), to support the customization variable of the same name.
```
This is happening because you've wrapped the declaration in a `progn`, which I think isn't necessary.  But I see people doing this sometimes and I don't understand why -- so if I'm missing something let me know.  Otherwise I think both of the top-level progns can be removed.

Other [lints](https://github.com/riscy/melpazoid):
- puni.el#L1200: This double negation could be collapsed (`not` aliases `null`)
- puni.el#L1227: This double negation could be collapsed (`not` aliases `null`)
- puni.el#L572: No `format` required; `error` takes an f-string
- puni.el#L643: No `format` required; `error` takes an f-string
- puni.el#L693: No `format` required; `error` takes an f-string
- puni.el#L719: No `format` required; `error` takes an f-string

**Comment by AmaiKinono** [comment]
> This is happening because you've wrapped the declaration in a `progn`, which I think isn't necessary. But I see people doing this sometimes and I don't understand why -- so if I'm missing something let me know.

It's for lazy load. If you autoload a minor mode wrapped in `progn`, together with the functions/variables directly used by it, you can enable that minor mode before the package is loaded. In puni's case, it will only be loaded after any of the commands is called. I learned this technique from [selectrum](https://github.com/raxod502/selectrum/blob/97693d0aea2c548197e9d1de3bdedf8e703775a4/selectrum.el#L2995).

> Other lints...

Thanks! I've fixed them.

**Comment by riscy** [comment]
> It's for lazy load [...]

Oops, apologies for missing that in your original comment.  I notice selectrum has a clarifying comment about why it does this (maybe you should too?).  It's interesting, but I wonder if it's sort of an obscure and premature optimization -- e.g. do you know how much time this saves in practice? If not, I'd suggest not doing this.  I wouldn't want to see every package doing this, all of them putting extra code in my loaddefs which I'd imagine could eventually impact Emacs startup time.

**Comment by riscy** [comment]
I think that's not worth blocking on at this point.  Thanks for this!

**Pull request merged**
