### PR TITLE
Add frame-customize

### PR DESCRIPTION
**Pull request by plandes**
### Brief summary of what the package does

Allows for customization of Emacs frames, which include height and width of new Emacs frames.  Options for new frames are those given to `make-frame`.  This is handy for those that rather resize your Emacs frames with a key binding than using your mouse.

### Direct link to the package repository

https://github.com/plandes/frame-customize

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for submitting this. You should rename this file and package to `cframe` so that everything is consistent. Additionally, you have some missing package dependencies which you should declare. Thanks!

**Comment by purcell** [comment]
Thanks. Please add an explicit version for the `dash` dependency. Package dependencies without versions are invalid syntactically in some `package.el` versions.

**Comment by plandes** [comment]
This is done--I'm not sure why it isn't kicking off the travis build though...

**Comment by purcell** [comment]
> This is done--I'm not sure why it isn't kicking off the travis build though...

There's a conflict, because you've pulled in an unrelated conflicting change. I suggest you rebase onto our latest `master`, and then force-push the branch to here.

**Comment by plandes** [comment]
@purcell Sorry about this confusion and any pain its cased :(. Yes, I made this change and then only realized it would probably cause issues later and it has.

I have resolved the change, did a fetch, merge (rebase wasn't doing anything), and push.  However, I can't push to melpa directly.  I can only push to my fork:
```bash
$ git push --force org topic-branch
remote: Permission to melpa/melpa.git denied to plandes.
fatal: unable to access 'https://github.com/melpa/melpa/': The requested URL returned error: 403
```

**Comment by purcell** [comment]
> I can't push to melpa directly. I can only push to my fork:

Yes, that's what I meant: pushing to your fork updates this PR.

I'm going to squash this commit before merging, but as a note for next time: what you needed to do was use an interactive rebase of your fork on top of our branch, and then drop/squash commits as necessary in order to tidy it up. And after rebasing like that, a force-push becomes necessary.

Anyway, we're all set here - thanks.

**Comment by plandes** [comment]
Got it.  Sorry again for the extra hassle.

Question: I a few more libraries I'm finally able to contribute.  What's the best way going forward from what I have?  Merge with melpa/melpa, add changes to the topic-branch or just remove the branch and create a new branch?

**Comment by purcell** [comment]
Just the usual: create a separate branch for each, based off our `master`, and submit separate PRs.

**Pull request merged**
