### PR TITLE
Add diary-manager recipe

### PR DESCRIPTION
**Pull request by raxod502**
### Brief summary of what the package does

`diary-manager` is a way for you to maintain a collection of daily diary entries.

### Direct link to the package repository

https://github.com/raxod502/diary-manager

### Your association with the package

I am the author of `diary-manager`.

### Relevant communications with the upstream package maintainer

N/A

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback [except for the prefix; I think `diary-manager-` is really just too long and I prefer `dm-` instead]
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings [except where the suggestions impaired readability]
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by raxod502** [comment]
Ping. Any changes needed here?

**Comment by raxod502** [comment]
* Lexical binding has been enabled.
* The prefix has been changed to `diary-manager-`.
* The unnecessary `:group` specifications have been removed. Thanks, I didn't know about that! (I went and removed them from all my packages.)
* [A comparison to `diary-lib` was added to the README](https://github.com/raxod502/diary-manager#how-is-this-different-from-diary-lib).
* I separate my sentences with one space. `sentence-end-double-space` is set to nil in a file-local variable, and [you can see that checkdoc is passing on Travis](https://travis-ci.org/raxod502/diary-manager).
* Many functions and variables were made private.

**Comment by DamienCassou** [comment]
Ok for me, I'm merging.

**Comment by raxod502** [comment]
Thanks so much!

**Pull request merged**
