### PR TITLE
Adding morrowind-emacs-theme to MELPA

### PR DESCRIPTION
**Pull request by SamuelBanya**
### Brief summary of what the package does

This adds the 'morrowind-emacs-theme' to MELPA so that other users can enjoy this great theme I created 

### Direct link to the package repository

https://github.com/samuelbanya/morrowind-emacs-theme

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer
Thanks for allowing me to contribute to MELPA with a great new theme I created.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`morrowind-emacs-theme.el` with package-lint 20220607.738:
```
8 issues found:
1:0: error: Package should have a Homepage or URL header.
1:0: warning: The word "emacs" is redundant in Emacs package names.
26:0: error: Package should have a non-empty ;;; Commentary section.
94:10: error: You should depend on (emacs "24.1") if you need `org-date'.
98:10: error: You should depend on (emacs "24.1") if you need `org-block'.
101:10: error: You should depend on (emacs "24.1") if you need `org-todo'.
250:8: warning: Closing parens should not be wrapped onto new lines.
266:3: warning: Closing parens should not be wrapped onto new lines.
```

(The dependency on emacs 24.1 is probably a false positive)

**Comment by SamuelBanya** [comment]
Just to be on the same page, what version of Emacs were you using when you received this error?

Also, do I need to revise these false positives? I ask because I created it using the 'ThemeCreator' web app:
https://mswift42.github.io/themecreator/

**Comment by riscy** [comment]
> what version of Emacs were you using when you received this error?

I run Emacs 28.1 for these, but those came from the 20220607.738 version of package-lint.

> do I need to revise these false positives?

No, they pop up often in themes.  Not to worry. :)

**Comment by SamuelBanya** [comment]
Okay, thanks for this response. Just making sure, this is my first time submitting anything to MELPA, so I've been stoked in anticipation and wanted to make sure I did anything on my end to make sure it was OK.

**Comment by riscy** [comment]
By the way, not all of them were false positives.  Here's a sanitized list:

`morrowind-emacs-theme.el` with package-lint 20220607.738:
```
8 issues found:
1:0: error: Package should have a Homepage or URL header.
1:0: warning: The word "emacs" is redundant in Emacs package names.
26:0: error: Package should have a non-empty ;;; Commentary section.
250:8: warning: Closing parens should not be wrapped onto new lines.
266:3: warning: Closing parens should not be wrapped onto new lines.
```

**Comment by SamuelBanya** [comment]
Just to be clear, do you absolutely need me to fix these in order for these to be approved to be on MELPA? @riscy 

I ask because a lot of that was not done by me, but by that Theme Creator mentioned above.

Please let me know, and I'll then open a related GitHub Issues related issue on that project to mention this.

More so, because I think the related fixes should be minimal and not too bad comparatively to the point where I could even check it out too. Just wanted to prevent the same issue from anyone else who makes themes using that tool too.

**Comment by riscy** [comment]
Yes, and we appreciate you accommodating. :)  MELPA has nothing to do with Theme Creator.

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out. :)

**Comment by SamuelBanya** [comment]
@riscy I reached out to the 'Theme Creator' maintainer, but am trying to figure out how to make his utility work with MELPA, so its a bit hard at the moment to figure out how to truly fix this to make it suitable for MELPA.

Not sure what to do.

At this point, it might be even easier just going the 'base16' route instead, not sure.

**Comment by riscy** [comment]
All that's needed in this case is to modify the source file at your repository to fix the issues [here](https://github.com/melpa/melpa/pull/8095#issuecomment-1174361353).

**Comment by riscy** [comment]
@SamuelBanya friendly ping. :)

**Comment by SamuelBanya** [comment]
I'll put it as nice as I can, I just wanted to upload it to MELPA without having to really do any work. A lot of people complain about the MELPA process, and honestly, its hard to deal with. Now I kind of understand why people just make their own packages or grab them from GitHub without putting them up on MELPA.

Its just a theme, and it doesn't do any malicious harm.

Anyway, I don't really know how to fix my package honestly, since the Emacs Theme Creator dev didn't get back to me I don't believe, and its been a while.

Would love to include this in MELPA but I have no idea what to do.

@riscy

**Comment by riscy** [comment]
No problem, I think this is fair of you to say.  If you have no idea what to do, here's are some pointers:

`1:0: error: Package should have a Homepage or URL header.`

This requires you to add a block to your header, e.g.:
```elisp
;; Author: Samuel Banya
;; URL: https://github.com/samuelbanya/morrowind-emacs-theme
;; Version: 0.1
;; Package-Requires: ((emacs "24"))
;; Created with ThemeCreator, https://github.com/mswift42/themecreator.
```

`1:0: warning: The word "emacs" is redundant in Emacs package names.`

The package is called `morrowind-emacs-theme` but this is obviously for Emacs; you can rename the package to `morrowind-theme`.

`26:0: error: Package should have a non-empty ;;; Commentary section.`

Your `Commentary` is empty - you should fill it in with a summary, both for users and so that the MELPA index has some more metadata on your package.

`253:8: warning: Closing parens should not be wrapped onto new lines.`

For this one, you can just pull the closing paren on line 253 onto the previous line.

**Comment by tarsius** [comment]
This pull-request has been open for over half a year. @SamuelBanya could you please get this over the finish line soon, or else close it? If you do the latter but still plan to get this into Melpa eventually, then you might want to add a quick message here. You can ask us to reopen this pull-request when you are ready.

**Comment by SamuelBanya** [comment]
I have made the revisions as requested, @riscy 
Can you please review my changes to see if they are approved:
https://github.com/SamuelBanya/morrowind-theme

@tarsius 
I had a lot of personal things going on like career change stuff, and honestly had to put this on the side burner, but just got the revisions done today.

Can you pease let me know if I need to re-add anything or if my latest commit changes on the repo itself are now incorporated into this melpa build?

**Comment by riscy** [comment]
> Can you please let me know if I need to re-add anything

No need for you to change anything here - I updated your recipe and I'm pulling the latest code pointed at by your recipe when I review. :)

`morrowind-theme.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- morrowind-theme.el#L25: Triple semicolons `;;;` are usually for section headings
```
I'd recommend also adding linebreaks to the commentary and arriving at:
```elisp
;;; Commentary:

;; An Emacs theme based upon the colors found in the in-game menu of the Elder
;; Scrolls III: Morrowind game by Bethesda.  Nerevar approved... though Dagoth
;; Ur was not present for a related comment upon press release
```

`morrowind-theme.el` with package-lint 20221003.1636:
```
4 issues found:
97:5: error: You should depend on (emacs "24.1") if you need `org-date'.
101:5: error: You should depend on (emacs "24.1") if you need `org-block'.
104:5: error: You should depend on (emacs "24.1") if you need `org-todo'.
270:2: warning: Closing parens should not be wrapped onto new lines.
```
This is minor because these are just color definitions, but you could quiet package-lint up by depending on Emacs 24.1 instead of Emacs 24.

The above issues are minor enough that I don't think it's worth blocking on them at this late stage -- but please try to get to them when you can!

And, welcome to MELPA. :)

**Comment by SamuelBanya** [comment]
Hey @riscy 
Question, so going forward, is any commit made to my main repo automatically merged as well?

I ask because that latest recipe above doesn't include the latest theme name revision commit I had to do as well:
https://github.com/SamuelBanya/morrowind-theme/commit/d321e4bdef83ac247ebe8c45ed4b2dc3602903df

**Comment by SamuelBanya** [comment]
@riscy 
I also added the revisions you suggested by adding the separate comment lines in the beginning.

I also changed the following line to just Emacs 24.1 as you requested:
```
;; Package-Requires: ((emacs "24.1"))
```

Would this be sufficient?

Also, how long does it take to show up on the MELPA site itself after this gets merged etc? And also, are any other further revision commits automatically included from here on out if I make changes to the theme as I go on?

I ask because there's a few minor things I have to change, like for the 'Swiper' related colors etc to make it not so blindly grey for highlights etc.

**Comment by riscy** [comment]
> Question, so going forward, is any commit made to my main repo from now onward automatically merged into the MELPA version as well?

Yes; it may take a while for the change to propagate.  You can see the latest-build information at the top-right side of https://melpa.org/

> Would this be sufficient?

Yes, that's great!

> how long does it take to show up on the MELPA site itself after this gets merged etc?

I don't have exact numbers but I expect you'll see it in a few hours at the most.

> are any other further revision commits automatically included from here on out if I make changes to the theme as I go on?

Yep - MELPA will repeatedly pull and re-host the latest code, albeit with a small bit of lag time.

**Pull request merged**
