### PR TITLE
Add recipe for js2hl

### PR DESCRIPTION
**Pull request by redguardtoo**
### Brief summary of what the package does

Highlight/rename things using `js2-mode' parser

### Direct link to the package repository

https://github.com/redguardtoo/js2hl

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Looks like the recipe filename and the recipe itself have mismatched names (evil-matchit)

**Comment by redguardtoo** [comment]
fixed

**Comment by riscy** [comment]
Code looks good.  Have you spoken to @mishoo about this?  The blog post mentions something about these changes sometimes making their way into the original js2 mode, so it might be good to get some insight from the original author.

**Comment by mishoo** [comment]
Happy if this makes it into melpa, and also that it's cleaned up from js2-refactor dependency; it didn't use much of it anyway.

**Comment by redguardtoo** [comment]
@mishoo , thanks.

**Comment by riscy** [comment]
Thanks both!

**Pull request merged**
