### PR TITLE
Added recipe for Boxes program integration.

### PR DESCRIPTION
**Pull request by Mike-Woolley**
### Brief summary of what the package does

Provides an Emacs interface to the Boxes command line program which draws, removes, and repairs ASCII art boxes.

### Direct link to the package repository

https://github.com/ascii-boxes/boxes.git

### Your association with the package

Contributor. 

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`boxes.el` with package-lint 20221003.1636:
```
3 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:44: warning: You should depend on (emacs "24.1") if you need lexical-binding.
85:1: error: You should depend on (emacs "24.3") if you need `defvar-local'.
```
These look easy to fix - prefer `Version` in this case.

`#'load`-check on each file:
```
Loading boxes.el
  boxes.el:Error: Emacs 28.1:
  (file-missing "Searching for program" "No such file or directory" "boxes")
```
This tells me that if `boxes` isn't found when users (attempt to) bring this in, an error will occur.  This could mean errors in the middle of loading a user's config, which can be inconvenient and lead to a partially setup Emacs.  What I'd recommend is to programmatically delay executing the code in `defconst boxes-types-list` until the user needs it; e.g. change it into a function.

One last comment I have is about the recipe, especially `:files ("doc/*.el")` -- this is technically fine, but I wonder if this file will always exist in a "doc" directory?  Sometimes we gently encourage creating independent repos for packages, because it can make things a little easier on the tools and/or users.  (MELPA will exctract your code and distribute only that, but users of e.g. straight.el will end up cloning your whole repo using this recipe, I believe.)

**Comment by Mike-Woolley** [comment]
Thanks for your detailed comments Chris !

> ```
> 3 issues found:
> 1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
> 1:44: warning: You should depend on (emacs "24.1") if you need lexical-binding.
> 85:1: error: You should depend on (emacs "24.3") if you need `defvar-local'.
> ```

I will fix the dependencies.

`Version:` is a bit tricker as this code is over 20 years old and never had a version number, so adding one now begs the question what it should be? 1.0 just doesn’t seem right 😊

So I deliberately didn’t add a Version header and the MELPA documentation indicates that it will use the repo version tag if not provided (I see little value in duplicating that information in the .el file).

> ```
> Loading boxes.el
>   boxes.el:Error: Emacs 28.1:
>   (file-missing "Searching for program" "No such file or directory" "boxes")
> ```
> 
> This tells me that if `boxes` isn't found when users (attempt to) bring this in, an error will occur. This could mean errors in the middle of loading a user's config, which can be inconvenient and lead to a partially setup Emacs. What I'd recommend is to programmatically delay executing the code in `defconst boxes-types-list` until the user needs it; e.g. change it into a function.

Good point, I’ll change that to evaluate it just before it’s required for the first time.

> One last comment I have is about the recipe, especially `:files ("doc/*.el")` -- this is technically fine, but I wonder if this file will always exist in a "doc" directory? Sometimes we gently encourage creating independent repos for packages, because it can make things a little easier on the tools and/or users. (MELPA will exctract your code and distribute only that, but users of e.g. straight.el will end up cloning your whole repo using this recipe, I believe.)

That might be politically difficult, plus the likelihood of the location changing is very small and if it does we can change the recipe - so I’d rather not have do that right now…

Thanks,
Mike

**Comment by Mike-Woolley** [comment]
Thinking about the Version issue some more, setting `Package-Version` to “1.0” and omitting `Version` is maybe a good compromise…

**Comment by riscy** [comment]
That works fine -

I will respond more fully later, but other well-known package authors have also just gone with `Version: 0.0` which they never update, and let MELPA determine its own package-version.  So there are a few options.

**Comment by riscy** [comment]
Thank you!  Merging this.

**Comment by Mike-Woolley** [comment]
Thanks Chris !

**Pull request merged**
