### PR TITLE
Add a recipe for ct.el

### PR DESCRIPTION
**Pull request by neeasade**
### Brief summary of what the package does

Provides utility functions for editing individual colors in color spaces. 

### Direct link to the package repository

https://github.com/neeasade/ct.el

### Your association with the package

Author, Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

Disclaimer: This is my first package, and melpa submission.

### CODE REVIEW

**Comment by neeasade** [comment]
I've just noticed that I can't seem to `(require 'ct)`, but I can if I change the feature name back to `color-tools` -- does the feature name have to match the file name? If I wish to keep the short prefix shoudl I rename the file to ct.el?

**Comment by riscy** [comment]
This looks like a valuable set of utilities, thanks for this.

To keep things consistent I believe it's preferred that your main filename, recipe, `:group`, `:prefix`, etc. are all the same.  This makes it possible for us to know which prefixes are taken simply by scanning existing package names.  In this case I think `color-tools` would be preferable.

In the meantime here's a quick first pass.

### color-tools.el ###

byte-compile (using Emacs 27.1):
```
color-tools.el:306:1:Warning: Unused lexical argument `Vmod'
color-tools.el:306:1:Warning: Unused lexical argument `Smod'
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210111.341):
```
2 issues found:
1:0: error: There is no (provide 'color-tools) form.
7:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```

Other [lints](https://github.com/riscy/melpazoid):
- color-tools.el#L70: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L72: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L78: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L79: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L82: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L128: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L132: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L138: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L142: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L144: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L150: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L163: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L164: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L170: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L182: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L367: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L27: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L28: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L29: It's safer to sharp-quote function names; use `#'`
- color-tools.el#L87: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading color-tools.el
Done.
```

### Package ###

- GitHub API found `MIT License`
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to color-tools.el
- color-tools.el (unknown license) -- Utilities for editing individual colors

**Comment by neeasade** [comment]
@riscy thanks for the feedback, and your time in a first pass! I wasn't aware of melpazoid, I'll use that and resolve the issues. re: the prefix: am I just overthinking the verbosity of `color-tools` vs `ct`? EG in [this expression](https://github.com/neeasade/tarps/blob/00bd5d8158e6043cb2492725716dd37813f958c3/tarp-mcfay-theme.el#L9-L14) I feel like it's just "gross" looking -- but I don't have anything concrete to back up that feeling. Maybe it's just that stuff like {s,dash,f,fn}.el all have such concise prefixes, and it makes me want to have a similar claim for colors.

**Comment by riscy** [comment]
> am I just overthinking the verbosity of color-tools vs ct? EG in this expression I feel like it's "gross" looking -- but I don't have anything concrete to back up that feeling. Maybe it's just that stuff like {s,dash,f,fn}.el all have such concise prefixes, and it makes me want to have a similar claim for colors.

You're right it is verbose.  :)  There are packages out there that try to hide the prefix from the programmer in various ways, but you eventually get used to it.  You _could_ use `ct` as your package's prefix/namespace, and then also have that as your package name, elisp file name, etc.  I would suggest against it, but I could be convinced this package merits it.

For what it's worth, following contemporary MELPA standards I'd probably push back against the prefixes of some of the packages you mention.

**Comment by neeasade** [comment]
> I could be convinced this package merits it.
 
I think the feeling I'm going for with color-tools is like the old quote about having "100 functions to operate on 1 data structure" rather than "10 functions to operate on 10 data structures". The core assumption is that everything comes back into the RGB space, and the set of functions is oriented around that. The reason I think of EG s.el is because color-tools.el(ct.el?) has functions for operating on individual colors and comparing at-most 2 colors, with an goal of not prescribing stuff like design decisions or a theming framework. I think maybe somehow I percieve the hubris of a short namespace to be authoritative in a space like that, even though that is not necessarily the case. (and my goal in communicating that would be to encourage contributors and correctness)
 
> For what it's worth, following contemporary MELPA standards I'd probably push back against the prefixes of some of the packages you mention.

That is a good point!

-----

also considering: `c-`, `colortools-`

Thanks for bearing with me while I think out loud here

**Comment by neeasade** [comment]
I have opted for the rebrand to `ct.el`. Updated the recipe and package to reflect that, ran package-lint (I don't have melpazoid setup locally yet)

**Comment by riscy** [comment]
Okay, thank you for accommodating.  Here's the latest quick check --

### ct.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210111.341):
```
2 issues found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
8:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```

Other [lints](https://github.com/riscy/melpazoid):
- ct.el#L160: It's safer to sharp-quote function names; use `#'`
- ct.el#L192: It's safer to sharp-quote function names; use `#'`
- ct.el#L381: It's safer to sharp-quote function names; use `#'`
- ct.el#L480: It's safer to sharp-quote function names; use `#'`

**Comment by neeasade** [comment]
Thanks -- resolved

**Comment by riscy** [comment]
Thanks, this looks good to merge.  Checkdoc "misses" on these but fyi a documentation string like:
```
  "Work with a color C in the LAB space using function TRANSFORM. Ranges for LAB are 0-100, -100 -> 100, -100 -> 100."
```
should be formatted to fit in ~80 columns, e.g., this is better:
```
  "Work with a color C in the LAB space using function TRANSFORM.
Ranges for LAB are 0-100, -100 -> 100, -100 -> 100."
```
Otherwise Emacs will do the wrapping for us and we get help windows that can look like this:
image

**Comment by neeasade** [comment]
Thanks, I'll take a look at those. 

OT: I've been a shx user for years, thanks for that package

**Comment by riscy** [comment]
> OT: I've been a shx user for years, thanks for that package

It means a lot to hear that.  Thanks. :)

**Pull request merged**
