### PR TITLE
Add recipe for magit-gptcommit

### PR DESCRIPTION
**Pull request by douo**
### Brief summary of what the package does

 A magit extension for generating commit messages with help of gpt.

### Direct link to the package repository

https://github.com/douo/magit-gptcommit

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`magit-gptcommit.el` with byte-compile using Emacs 29.1:
```
magit-gptcommit.el:429:11: Warning: `gptel--debug' is an obsolete variable (as of 0.6.5); use `gptel-log-level' instead.
magit-gptcommit.el:429:11: Warning: reference to free variable `gptel--debug'
In magit-gptcommit--stream-cleanup:
magit-gptcommit.el:474:11: Warning: `gptel--debug' is an obsolete variable (as of 0.6.5); use `gptel-log-level' instead.
magit-gptcommit.el:474:11: Warning: reference to free variable `gptel--debug'
```

`magit-gptcommit.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- magit-gptcommit.el#L81: Customizable variables shouldn't be private
- magit-gptcommit.el#L104: Customizable variables shouldn't be private
```

Package and license:
- magit-gptcommit.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by douo** [comment]
@riscy  Thank you for your review. I have addressed your comments and updated the package.  I would appreciate it if you could review the updated version and provide any additional feedback you may have.

**Comment by riscy** [comment]
Looks good.  I would highly recommend making `defconst magit-gptcommit--prompt-one-line` *not* a constant and also non-private - I'm sure people would want to have some freedom to change this prompt.  (I tried "conventional commits" for a while, which seems to be what you're prompting for, and felt they didn't add much.  For instance, what would you call a commit that adds a recipe to MELPA?  A `feat`?  A `build`?  A `chore`? :)

**Comment by douo** [comment]
Thank you for the suggestion. It makes sense, and I will make that change. Sorry for the delayed response.
As for your question about the conventional commit type for adding a new recipe to MELPA, after testing it out myself, the results are as follows: 

Screenshot 2024-03-27 at 11 12 22

Since the temperature is not 0, I believe this answer is not fixed. :)

**Pull request merged**
