### PR TITLE
Add recipe for `geiser-overlay`

### PR DESCRIPTION
**Pull request by port19x**
### Brief summary of what the package does

This package follows the long tradition of [sly-overlay](https://git.sr.ht/~fosskers/sly-overlay), [eros](https://github.com/xiongtx/eros) and [cider](https://docs.cider.mx/cider/index.html) by providing evaluation result overlays for scheme.

### Direct link to the package repository

https://github.com/port19x/geiser-overlay

### Your association with the package

I'm the author and maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, and thank you also for the heads-up re: sly.   I just see a couple small nags -

`geiser-overlay.el` with byte-compile using Emacs 29.4:
```
geiser-overlay.el:238:46: Warning: the function `geiser-eval--send/wait' is not known to be defined.
geiser-overlay.el:238:18: Warning: the function `geiser-eval--retort-result' is not known to be defined.
```
Also, I think `send-wait` instead of `send/wait` would be more in line with coding conventions; as far as my understanding goes, `/` is "permitted" by tools like package-lint because it can represent a mathematical operation, but should ideally not be reused outside that context.  Not a blocker though (especially since package-lint doesn't complain)

`geiser-overlay.el` with checkdoc 0.6.2 (fix *within reason*):
```
geiser-overlay.el:229: First sentence should end with punctuation
```

**Comment by port19x** [comment]
I have no influence on the naming of `geiser-eval--send/wait`, so we'll have to ignore that.

The two functions get loaded when geiser is started. I'm already doing a `(require 'geiser)` up top, but if you know of a way to load it earlier or to otherwise make the bytecompiler shut up, I'm open to suggestions

good catch with the checkdoc, forgot to re-lint after the bug fix :+1:

**Comment by riscy** [comment]
> but if you know of a way to load it earlier or to otherwise make the bytecompiler shut up, I'm open to suggestions

q.v. `declare-function`

**Comment by port19x** [comment]
Please take another look

**Comment by riscy** [comment]
Thank you!  Merging this now.

**Pull request merged**
