### PR TITLE
Add caser.el.

### PR DESCRIPTION
**Pull request by zck**
### Brief summary of what the package does

This package provides functionality to change text casing from camelCase to dash-case to snake_case.

### Direct link to the package repository

https://hg.sr.ht/~zck/caser.el

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

n/a.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by terlar** [comment]
Might be good to provide a comparison to:
https://github.com/akicho8/string-inflection

**Comment by zck** [comment]
The main difference is that string-inflection focuses on cycling through a series of inflections with one command; caser focuses on having a separate command for each case type desired.

There's a secondary difference in that caser better supports operating on a region -- string-inflection allows it once, but then disables the region, so calling it a second time only operates on the last word. I suspect this is a bug in string-inflection, so it's not a major difference.

**Comment by riscy** [comment]
Thanks for pointing that one out @terlar!  Good comparison.

I think the distinction is appropriate -- here's a quick first pass:

`caser.el` with package-lint 20230806.1331:
```
15 issues found:
23:0: error: Package should have a non-empty ;;; Commentary section.
27:0: error: `caser/camelcase-dwim' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
41:0: error: `caser/camelcase-region' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
66:0: error: `caser/upcase-char' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
72:0: error: `caser//move-to-beginning-of-word' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
81:0: error: `caser//move-to-end-of-word' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
88:0: error: `caser//forward-word' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
112:0: error: `caser//word-helper' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
133:0: error: `caser/camelcase-word' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
138:0: error: `caser/snakecase-dwim' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
152:0: error: `caser/snakecase-region' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
195:0: error: `caser/snakecase-word' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
200:0: error: `caser/dashcase-word' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
205:0: error: `caser/dashcase-region' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
248:0: error: `caser/dashcase-dwim' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
```

**Comment by zck** [comment]
All package-lint warnings taken care of.

**Comment by riscy** [comment]
Thanks for accommodating,  but it looks like you've renamed the functions and then added a bunch of aliases like `(defalias 'caser/snakecase-region #'caser-snakecase-region)`.  It's the community standard to use hyphens (including for commands) and this feels like it's unnecessarily stuffing the namespace with aliases.  For example now when I type `M-x caser`, my command completion is listing the functions AND your (unorthodox) aliases.

Also, I apologize for this, but I need to walk back my statement above re: the distinction being appropriate.
 
> The main difference is that string-inflection focuses on cycling through a series of inflections with one command; caser focuses on having a separate command for each case type desired.

I went and looked at the code for string-inflection and it has functions (with `interactive` forms in them, hence commands) that look like this:

```elisp
;;;###autoload
(defun string-inflection-lower-camelcase ()
  "fooBar format"
  (interactive)
  (string-inflection-insert
   (string-inflection-camelcase-function (string-inflection-get-current-word))))
```
So it strikes me that there are separate commands for each case type in that original package.  However, I do feel that `caser` has more powerful functions, e.g. `caser-camelcase-region` will camelcase ANY region.

> There's a secondary difference in that caser better supports operating on a region -- string-inflection allows it once, but then disables the region, so calling it a second time only operates on the last word. I suspect this is a bug in string-inflection, so it's not a major difference.

Maybe @akicho8 can confirm if this is just a bug.  And in that case, I think the better result for users of MELPA is that the bug is fixed, and we improve/extend the existing package instead of adding another one that appears to be doing virtually the same thing.

What are your thoughts on that?

**Comment by zck** [comment]
In terms of the two packages, it seems that string-inflection has an [explicit design choice](https://github.com/akicho8/string-inflection/issues/38) of only supporting the letters a-z.

Caser.el has made the other choice: to work with any characters, even for alphabets that do not have capital letters. There are examples in the readme for Icelandic, German, and Korean.

I'll have to think more about the naming style.

**Comment by riscy** [comment]
Okay, you've convinced me you're taking a different path than string-inflection.

Re: the namespacing, if you believe you have existing users that are using e.g. `case/camelcase-region` in their configs, the right thing to do here would be to use `define-obsolete-function-alias` and to migrate off them in a future major version bump.  This may seem a little strict, but I think there's value in enforcing some uniformity here, even though elisp lets you throw virtually anything in a function name.

**Comment by zck** [comment]
I've pushed changes to do the renames.

**Comment by riscy** [comment]
Thank you!  Merging.

**Comment by zck** [comment]
Hooray! Thanks.

**Comment by purcell** [comment]
Couple of extra random points for you, @zck:

- Worth adding `;;;###autoload` for high-level interactive commands, so they will trigger loading the package lazily. `caser-camelcase-dwim` would be an example.
- At the same time, none of the `caser--*` functions should be `interactive`, since no end-user commands should have a "private" name prefix like `caser--`

**Pull request merged**
