### PR TITLE
Add rust-auto-use.el

### PR DESCRIPTION
**Pull request by vmalloc**
### Brief summary of what the package does
This package automatically inserts `use` statements in Rust code based on the current symbol.

### Direct link to the package repository

https://github.com/vmalloc/rust-auto-use.el

### Your association with the package
I am the developer and current maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by vmalloc** [comment]
I tried to follow the guides as best as I can. This is my first contribution, so I apologize in advance if I missed something. Any feedback is greatly appreciated.

**Comment by purcell** [comment]
Thanks! Notes:
- Please use a more complete boilerplate, as `M-x auto-insert` would insert in an empty `.el` file. Then the headers will be more complete, and the licence text will be explicit.
- Make `rust-auto-use-cache-filename` a `defcustom`, in a `defgroup`.
- Don't use `concat` to build filenames: prefer `expand-file-name`
- Add a `;;;###autoload` cookie comment before the definition of the `rust-auto-use` command.
- When invoking `emacs-lisp-mode`, also use `delay-mode-hooks`, to avoid the temp buffer having `flycheck`, `company` etc. enabled in it.

Hope that helps!

**Comment by vmalloc** [comment]
@purcell thanks for the feedback! Can you clarify a bit about the last point? Do you mean embed a call to that function within the `with-temp-buffer` body?

**Comment by purcell** [comment]
>  Can you clarify a bit about the last point? Do you mean embed a call to that function within the `with-temp-buffer` body?

Instead of `(emacs-lisp-mode)` you'd use `(delay-mode-hooks (emacs-lisp-mode))`.

**Comment by vmalloc** [comment]
@purcell Thanks! Will get to it soon

**Comment by vmalloc** [comment]
@purcell I pushed the changes corresponding to your feedback. I hope I did them correctly -- if not will gladly fix any further problems.

Thanks again!

**Comment by purcell** [comment]
Great. Sent you some tweaks in https://github.com/vmalloc/rust-auto-use.el/pull/1, but this is basically looking good, so I'll merge this now. Thanks for you patience, and welcome to MELPA! :tada:

**Comment by vmalloc** [comment]
Thanks!

**Pull request merged**
