### PR TITLE
Add recipe for bibtex-actions

### PR DESCRIPTION
**Pull request by bdarcus**
### Brief summary of what the package does

Provides a completing-read-based front-end to bibtex-completion, and so an alternative to [helm-bibtex and ivy-bibtex](https://github.com/tmalsburg/helm-bibtex). 

While not required as dependencies, it's primarily designed for Selectrum and Embark.

### Direct link to the package repository

https://github.com/bdarcus/bibtex-actions

### Your association with the package

Creator and maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Note this is my first emacs/melpa package, but I setup the [elisp-check](https://github.com/leotaku/elisp-check) github action on the repo at the beginning, and have addressed warnings and errors as I've gone. There are currently no errors or warnings.

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks very much for your close adherence to the checklist.

I don't think this is a blocker, but I see your line:
```elisp
;; REVIEW: is this the correct way to ensure we use the custom separator in
;;         'bibtex-actions-read'?
(defvar crm-separator)
```
and on first glance this won't have any effect.

In any case, welcome to MELPA. :)

**Comment by bdarcus** [comment]
Thanks!

> ... on first glance this won't have any effect.

Quick clarification: you're suggesting I remove that defvar line (and, of course, the accompanying comment)?

Also, while I have you, if you all think the elisp-check GitHub action meets your standards, you might include it in the contributing doc and in the PR checklist as an option?

**Comment by riscy** [comment]
Yes -- as far as my knowledge goes, the only time you'd add a bare defvar (i.e. declare the variable without an initial value) is to hint the compiler that such a variable is going to be referenced in the code but is expected to have been set elsewhere.   But you're just using a locally scoped variable called cmr-separator, so you don't need to defvar it.

> if you all think the elisp-check GitHub action meets your standards, you might include it in the contributing doc and in the PR checklist as an option?

Is this an open PR somewhere?

**Comment by riscy** [comment]
(Or maybe you can link me to elisp-check so I know I'm landing in the right place.)

**Comment by bdarcus** [comment]
Here's the link:

https://github.com/marketplace/actions/emacs-lisp-check

**Comment by bdarcus** [comment]
Can I ask one more followup @riscy?

I noticed the way I had the description setup was such that in the list of package, only the "description" link shows up, because it's too long.

So I changed it to have a short first line, and then the rest, assuming the build scripts would pick that up.

But so far, no.

Is there something else I should do?

**Comment by riscy** [comment]
I think I see what you mean (from melpa.org):

image

This is because the first line of your file is:
```elisp
;;; bibtex-actions.el --- Description -*- lexical-binding: t; -*-
```
Which I should've checked for.  Instead of "Description" you should put an actual summary of your package. :)

**Comment by bdarcus** [comment]
Oh, duh!

Thanks, and sorry for the noise.

**Comment by bdarcus** [comment]
Another quick question @riscy - I realize I have a mistake in my latest commit message, and that melpa has already indexed it. Does that mean I shouldn't amend the commit?

It's not a big problem if that's the case.

**Comment by riscy** [comment]
Hmm, as far as I'm aware MELPA won't index your commit messages and I think MELPA is okay with you amending commits, but as a general rule it's better to make your default branch append-only so that people who are tracking the repo directly don't get into a bad state.

**Pull request merged**
