### PR TITLE
Add nord-emacs

### PR DESCRIPTION
**Pull request by arcticicestudio**
<p align="center"></p>

<p align="center"> <a href="https://github.com/arcticicestudio/nord-emacs/releases/latest"></a> <a href="https://github.com/arcticicestudio/nord/releases/tag/v0.2.0"></a>  <a href="https://www.gnu.org/software/emacs/#Releases"></a></p>

<p align="center">An arctic, north-bluish clean and elegant <a href="https://www.gnu.org/software/emacs">Emacs</a> theme.</p>

<p align="center">Designed for a fluent and clear workflow.<br>
Based on the <a href="https://github.com/arcticicestudio/nord">Nord</a> color palette.</p>

Nord Emacs is a 16 colorspace theme build to run in GUI- and terminal mode with support for many third-party syntax- and UI packages.

---

  - **Direct link to the package repository**:
    [arcticicestudio/nord-emacs](https://github.com/arcticicestudio/nord-emacs)
  - **Association with the package**:
    Owner of the project
  - **Relevant communications with the upstream package maintainer**:
    None needed

### Checklist
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- ~My elisp byte-compiles cleanly~
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! I sent you some fixes in https://github.com/arcticicestudio/nord-emacs/pull/21. You'll also need to call this package `nord-theme`, of course, rather than `nord-emacs`: please rename the recipe file and adjust the contents to match

**Comment by arcticicestudio** [comment]
Thanks for your fast reply and the PR to fix this format issues 👍 
Do I need to update the change the name in the recipe too ot only the file name? 
`(nord-emacs ...` -> `(nord-theme ...`

**Comment by purcell** [comment]
> Do I need to update the change the name in the recipe too ot only the file name?
> (nord-emacs ... -> (nord-theme ...

Yes please, both. The first element of the recipe is the package's name, which is `nord-theme` in this case.

**Comment by arcticicestudio** [comment]
Updated the file- and package name.

**Comment by purcell** [comment]
Awesome, thanks.

**Pull request merged**
