### PR TITLE
Remove matrix-client from Recipes

### PR DESCRIPTION
**Pull request by rrix**
This is broken and unmaintained. I don't have time to refactor it enough to be functional and would
rather not provide a poor user experience. I'm not sure how to decomm a recipe other than git rm'ing it, feel free to point this in the right direction.

### CODE REVIEW

**Comment by purcell** [comment]
Sure, thanks.

**Comment by alphapapa** [comment]
I was actually thinking about trying this the other day.  Oh well.  :)

**Comment by rrix** [comment]
@alphapapa I'm going to pick it up again this summer, but right now I'm worried that it's broken enough to push people away from wanting to use Matrix.

**Comment by alphapapa** [comment]
@rrix Forgive the grossly out-of-place question, but I'm sure you can give me a straight answer quickly: Is it possible to simply make your own channel on the main matrix.org server, i.e. one where you can control who can join it?  I did quite some searching on the matrix.org site and on Google, but I couldn't find a simple answer to this simple question.  I'd like to give Matrix a try, but I don't want to have to run my own server just to have my own private channel for a few friends.  Thanks.

**Comment by jgkamat** [comment]
@alphapapa yes, for questions this is a good place to start: https://riot.im/app/#/room/%23matrix:matrix.org

If you are using riot-web, click the plus button in the lower left to make a new channel, then go into channel settings (top right) and you can change permissions settings from there.

**Pull request merged**
