### PR TITLE
Add recipe for frontside-javascript

### PR DESCRIPTION
**Pull request by cowboyd**
### Brief summary of what the package does

`frontside-javascript` makes working within the JavaScript _ecosystem_ easy.

JavaScript development can be complex. Not only does in execute with in the context of the browser, node, deno (and others), With the rise of transpilers such as Babel and TypeScript, the needs for editing, testing, and building JavaScript are more difficult than ever.

While editors like VSCode come out of the box being robust tools for working with JavaScript, it takes hours, if not weeks of research for JS on Emacs to not be flat out broken.  Just getting the editor not to incorrectly spew your buffer with errors is a chore.  The reasons for this are severalfold. For starters, you are likely to encounter many different variants of JavaScript: TypeScript, TSX, JSX, and even "vanilla" JS could use any number of syntax extensions via tools like babel. There is no one-size fits all JavaScript syntax, and so editors need to be smart about sourcing project syntax from the project configuration itself.

The goal of `frontside-javascript` is simple: any JavaScript project you care to clone should just work straight away, no matter if it contains TypeScript, React, Node, ES6, Deno, or whatever; now and going forward.   By work, it means it should:

1. Be able to understand the syntax as defined by the project itself, not a global concept of JavaScript syntax.
2. Highlight errors and automatically format based on the configured style of the project itself, not a global concept of style
3. Have completions, documentations, and refactoring at the current point based on the sources of the current project.
4. find and navigate to symbolic references

Again, you should get all this no matter what mixture of JavaScripts you happen to encounter in the wild.

### Direct link to the package repository

https://github.com/thefrontside/frontmacs/tree/release/packages/javascript

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

N/A (we maintain this package)

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- quick first pass.

### frontside-javascript.el ###

byte-compile (using Emacs 27.1):
```
frontside-javascript.el:213:1:Warning: the following functions are not known
    to be defined: flycheck-add-mode, flycheck-add-next-checker,
    tide-tsfmt-options
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210127.158):
```
2 issues found:
8:88: warning: Use a non-snapshot version number for dependency on "flycheck" if possible.
8:115: warning: Use a non-snapshot version number for dependency on "js2-mode" if possible.
```

### Package ###

- Avoid specifying `:branch` except in unusual cases (we prefer to build off the default branch; you can tag releases by following the MELPA Stable guidelines)
- The LICENSE file can be removed from the recipe
- GitHub API found `MIT License`
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to frontside-javascript.el (rather than telling users "See LICENSE for details", which could be ambiguous and isn't detectable by common tools)

**Comment by cowboyd** [comment]
@riscy Hello, and thanks for reviewing!

> package-lint (using version 20210127.158):
> 
> 2 issues found:
> 8:88: warning: Use a non-snapshot version number for dependency on "flycheck" if possible.
> 8:115: warning: Use a non-snapshot version number for dependency on "js2-mode" if possible.

- `js2-mode` uses the current day for its version numbers for their releases https://github.com/mooz/js2-mode/releases
- `flycheck` has not had a major version released in almost 4 years, and unfortunately, the snapshot version is required 🤷🏻‍♂️ 

I'll make the other changes

**Comment by cowboyd** [comment]
@riscy Ok, I've updated the license to use an SPDX reference, and removed the branch name from the recipe.

let me know if there's anything else!

**Comment by purcell** [comment]
Hey Charles! Hope you're doing well.

You can and should ditch all those `(require ...)` calls inside functions and move them to the top level so that they execute unconditionally when the file is loaded or compiled. That way, you won't need all those `defvar` stub declarations because the compiler will know what you're talking about. All the libs get loaded as soon as someone calls `frontside-javascript` anyway.

(You may have been trying to defer loading libs until later: the way to do this is to put functions like, say, 'frontside-javascript--typescript-mode-hook` in a separate `frontside-javascript-typescript` file and autoload it, with the `(require 'tide)` etc. at the top level in that file instead.)

**Comment by cowboyd** [comment]
@purcell doing great, and thanks for the tip! For some reason flycheck always complains about the first require statement for some reason. For example

```
Cannot open load file: No such file or directory, js2-mode
```

It only every complains about the first `require`, and it doesn't matter which order I put them in. In any case, the tests still pass and it appears to work fine, so I dunno 🤷🏻‍♂️

**Comment by purcell** [comment]
Yeah, that's because flycheck compiles the code in a background emacs process that doesn't re-use the current environment, and by default it doesn't inherit the `load-path`, so it doesn't see the other libs you have installed. A good option is to configure (or temporarily set) `flycheck-emacs-lisp-load-path` to the symbol `'inherit`.

**Comment by purcell** [comment]
Merged now, in any case. Have a great weekend!

**Comment by tarsius** [comment]
This package includes some copies of libraries by Drew from the Emacswiki. The library names are prefixed with `vendor-`, but the symbols are not. This vendoring was done because we did [Remove all Emacswiki packages](https://github.com/melpa/melpa/pull/5008) for good reasons.

We have brought back some wiki packages before and could do the same here but this isn't the only issue: the name of the symbols defined in these libraries lack a common prefix. (And while I am guilty of that myself sometimes (and feel we should relax our rules a bit), I think these are extreme examples, which should not be allowed in Melpa.)

IMO it would be best to not use any of these libraries. Maybe you use only very little functionality provided by these libraries, in which case it would make sense to just copy-paste those parts into your own libraries. (With new symbol name prefixes and proper attribution.)

/cc @purcell

**Comment by cowboyd** [comment]
@tarsius The repo in which this package appears does indeed contain the vendored `zoom-frm` library, but the javascript package published by this recipe does not. For some history, this repo used to contain a monolithic emacs setup which I'm now in the process of extracting what useful pieces I can.

This package is strictly related to JavaScript, and it's the only one I've been focused on re-working, but I have thought about extracting the font-zooming functionality into a package since it's the only way I've encountered to emulate the zooming behavior for most native OSX and Windows apps. If that's something of interest, then I could do that and only carry forward the pieces from `zoom-frm` (with attribution) as you mentioned.

**Comment by tarsius** [comment]
That's find for now but once the transitional period is over, every repository from which Melpa builds a package should be free from vendored libraries. IMO it would have been better to do the cleanup first before adding this package to Melpa.

I don't know your plans exactly so I don't know if that means that you will have to adapt some third-party code.

**Comment by purcell** [comment]
> IMO it would have been better to do the cleanup first before adding this package to Melpa.

I think it's okay in this case because this specific recipe/package doesn't include any such vendored code, even though the the *repository* from which it comes currently *does*.

**Comment by cowboyd** [comment]
>  I don't know your plans exactly so I don't know if that means that you will have to adapt some third-party code.

@tarsius I wasn't really sure to be quite honest, and wanted to see how this process of submitting to melpa went, but now that it's done, we will definitely be removing dead code, and extracting that which makes sense. At the very least, we'll be marking clearly those pieces of the repository that are deprecated, and will take the advice about vendored script in mind going forward.

**Comment by tarsius** [comment]
When you do that, then please maked sure to remove the dependency on `company-lsp` because loading that actually breaks the lsp setup. See #7461.

**Comment by cowboyd** [comment]
> When you do that, then please maked sure to remove the dependency on `company-lsp` because loading that actually breaks the lsp setup. See #7461.

Awesome! Thanks for the heads up.

**Comment by cowboyd** [comment]
> Friendly ping 🏓

@tarsius thanks! I've released a version of the legacy package with `company-lsp` removed

**Comment by tarsius** [comment]
Thanks!

`frontmacs-language-server.el` still requires `company-lsp`, which breaks the lsp setup as mentioned above.

**Comment by cowboyd** [comment]
@tarsius I removed that on master https://github.com/thefrontside/frontmacs/blob/master/frontmacs-language-server.el which is the legacy branch.

All of the new development is happening on the `release` branch, and that file `frontmacs-languages-server.el` is now deprecated.  Also, it has been moved into the `archive` directory since it is not being published anywhere anymore. As we sift through those files, I'll be completely removing them.

**Pull request merged**
