### PR TITLE
Add recipe for el-exiftool

### PR DESCRIPTION
**Pull request by arunisaac**
### Brief summary of what the package does

el-exiftool is an elisp wrapper around ExifTool.  ExifTool supports reading and writing metadata in various formats including EXIF, XMP and IPTC.

### Direct link to the package repository

https://git.systemreboot.net/el-exiftool

### Your association with the package

Author and maintainer

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Please load `tq` for using its function
- Don't load `cl.el` at load time. You should load cl-lib.el instead of it and use cl-lib functions/macros. However it looks cl-lib functions are not used in your package.
- Unused local variable name should start with `_`. Please check byte-compiling result.

**Comment by arunisaac** [comment]
Thanks for the feedback. I've made all three changes. However, since I'm using `cl-destructuring-bind` and `cl-function`, both macros from `cl-macs`, I'm requiring `cl-macs` instead of `cl-lib` as you suggested. Is that alright?

**Comment by syohex** [comment]
- Please load `cl-lib` instead of `cl-macs`. 3rd party should load `cl-lib`.

**Comment by arunisaac** [comment]
Done. `cl-lib` loaded instead of `cl-macs`.

**Comment by syohex** [comment]
Merged

**Comment by purcell** [comment]
I'd have suggested you rename this to `exiftool`. The `el-` prefix is redundant and unhelpful. If you'd like to do that now, I'd encourage it: just rename the source file and the symbols in it, then submit a subsequent PR to rename and update the MELPA recipe.

**Comment by arunisaac** [comment]
Ok, I'll rename the library to `exiftool`.

**Comment by purcell** [comment]
Yay, thanks!

**Pull request merged**
