### PR TITLE
Add scp

### PR DESCRIPTION
**Pull request by tszg**
### Brief summary of what the package does

Use the SCP command to transfer files with the remote server

### Direct link to the package repository

https://github.com/tszg/emacs-scp

### Your association with the package

I'm the developer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! This is probably not the best package name, since `sftp` is a specific program, and this package doesn't use it, which could lead to a lot of confusion.

**Comment by tszg** [comment]
This package USES SCP. Can I change it to SCP

**Comment by tszg** [comment]
Thanks @purcell  for the feedback!
This package uses the scp program, and I have changed the package name to scp.

**Comment by purcell** [comment]
Thanks!

- It seems dangerous to [change the global value of `enable-local-variables`](https://github.com/tszg/emacs-scp/blob/f551fa9ca6549c4db85abcca815a24848a335e5e/scp.el#L37). That whole `scp-locals-init` function seems like it shouldn't need to exist.
- Don't use `org-mode` here: use `special-mode`, which will also bind `q` for you.
- Also, [this line](https://github.com/tszg/emacs-scp/blob/f551fa9ca6549c4db85abcca815a24848a335e5e/scp.el#L33) will modify the keymap every time you run `scp`. Put that line at the top level after the mode declaration instead.
- Don't use [replace-regexp-in-string](https://github.com/tszg/emacs-scp/blob/f551fa9ca6549c4db85abcca815a24848a335e5e/scp.el#L56) when the args are not regexes. Bad things can happen! Either use a different function, or escape the regexps first - there's `regexp-quote` for that.
- Variable names should be `remote-path` rather than `remote_path`.
- When you [build strings with `%s`](https://github.com/tszg/emacs-scp/blob/f551fa9ca6549c4db85abcca815a24848a335e5e/scp.el#L72) you will have a bad time - use `shell-quote-argument` to make interpolated values safe inside command strings.

**Comment by tszg** [comment]
Thanks, I will fix it as soon as possible

**Comment by tszg** [comment]
Thanks for @purcell valuable comments, I made most of the changes, please review.

**Comment by purcell** [comment]
Looks good - welcome to MELPA!

**Comment by alphapapa** [comment]
Just a thought: it would generally be better to use `rsync` than `scp`, especially when transmitting directories or multiple files.

**Comment by tszg** [comment]
Thank you @alphapapa , this is a good idea!

**Pull request merged**
