### PR TITLE
add chatu

### PR DESCRIPTION
**Pull request by kimim**
### Brief summary of what the package does

Add a keyword #+chatu: for handling image in orgmode and markdown-mode.

### Direct link to the package repository

https://github.com/kimim/chatu

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this; cool idea.  Quick first pass --

`chatu.el` with byte-compile using Emacs 29.1:
```
chatu.el:317:28: Warning: reference to free variable `markdown-mode-map'
chatu.el:325:49: Warning: reference to free variable `org-open-at-point-functions'
chatu.el:324:20: Warning: assignment to free variable `org-open-at-point-functions'
In end of data:
chatu.el:205:11: Warning: the function `org-redisplay-inline-images' is not known to be defined.
chatu.el:201:11: Warning: the function `markdown-display-inline-images' is not known to be defined.
chatu.el:200:11: Warning: the function `markdown-remove-inline-images' is not known to be defined.
```

**Comment by kimim** [comment]
I want `chatu-mode` to work with orgmode and markdown-mode, so I require them based on the buffer major mode. Are these warning acceptable?

```emacs-lisp
(cond ((and (featurep 'markdown-mode)
                (derived-mode-p 'markdown-mode))
           (require 'markdown-mode)
           (keymap-set markdown-mode-map "C-c C-c C-c" 'chatu-add)
           (advice-add 'markdown-follow-thing-at-point
                       :before-until
                       #'chatu-ctrl-c-ctrl-o))
          ((and (featurep 'org)
                (derived-mode-p 'org-mode))
           (require 'org)
           (add-hook 'org-ctrl-c-ctrl-c-hook #'chatu-ctrl-c-ctrl-c)
           (add-to-list 'org-open-at-point-functions #'chatu-ctrl-c-ctrl-o)))
```

**Comment by riscy** [comment]
Thank you for accommodating --

> Fix the warnings with `with-no-warnings`

If we know the root cause (and can address it) it's far preferable for a production-ready package to do that instead.  So for example, rather than this:
```elisp
(defun chatu-refresh-image ()
  "Refresh image for different major mode."
  (cond ((and (featurep 'markdown-mode)
              (derived-mode-p 'markdown-mode))
         (with-no-warnings
           (require 'markdown-mode)
           (markdown-remove-inline-images)
           (markdown-display-inline-images)))
        ((and (featurep 'org)
              (derived-mode-p 'org-mode))
         (with-no-warnings
           (require 'org)
           (org-redisplay-inline-images)))))
```
you can write:
```elisp
(declare-function markdown-remove-inline-images "ext:markdown-mode.el")
(declare-function markdown-display-inline-images "ext:markdown-mode.el")
(declare-function org-redisplay-inline-images "org.el")
(defun chatu-refresh-image ()
  "Refresh image depending on the current major mode."
  (cond
   ((derived-mode-p 'markdown-mode)
    (markdown-remove-inline-images)
    (markdown-display-inline-images))
   ((derived-mode-p 'org-mode)
    (org-redisplay-inline-images))))
```
This is cleaner (you only have to `declare-function` once per function) and you can validate this bookkeeping using `check-declare-file`; being able to validate it is far safer than strewing `with-no-warnings` throughout the code.

**Comment by kimim** [comment]
Thanks @riscy, I adjusted the code according to you suggestions now.

**Comment by riscy** [comment]
Thanks - one more pass from me but this is looking close.  I'm seeing

`chatu-drawio.el` with byte-compile using Emacs 29.1:
```
chatu-drawio.el:41:19: Warning: Unused lexical variable `err'
```
In this particular case the usual approach is to write `condition-case nil` instead of `condition-case err` I believe.

**Comment by kimim** [comment]
Thanks. I fixed this issue. `err` is not used in the handler.

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
