### PR TITLE
ert-results - filter and display ert test results

### PR DESCRIPTION
**Pull request by rswgnu**
### Brief summary of what the package does

ert-results extends the Emacs Regression Test library, ert.el, with two new commands:

  {f} - (ert-results-filter) - filters display of test results based on point

  {t} - (ert-results-toggle) - toggles display/hiding of all selected tests

### Direct link to the package repository

https://github.com/rswgnu/ert-results

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

 **None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
These are conveniences which would be well suited for merging upstream.

Where is the `ert-display` feature provided?
I had to comment out the check for that feature in `ert-results-filter-status-p` to get the filtering working on Emacs 30.

**Comment by rswgnu** [comment]
I renamed the package from ert-display to ert-results so if there is any remaining reference to the former, it needs correction.  — rsw-- BobOn Dec 31, 2023, at 5:40 PM, Nicholas Vollmer ***@***.***> wrote:﻿
These are conveniences which would be well suited for merging upstream.
Where is the ert-display feature provided?
I had to comment out the check for that feature in ert-results-filter-status-p to get the filtering working on Emacs 30.

**Comment by rswgnu** [comment]
I have fixed this and released version 1.0.2.  Thanks for pointing the
issue out.

-- rsw

**Comment by rswgnu** [comment]
On Sun, Dec 31, 2023 at 5:40 PM Nicholas Vollmer ***@***.***>
wrote:

> These are conveniences which would be well suited for merging upstream.
>
Yes, I have messaged the original author and hope he will do so.  Until
that time, we'll have this as a separately available package.  -- rsw

**Comment by riscy** [comment]
Thank you for this, and thank you again @progfolio .  My quick first pass --

`ert-results.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ert-results.el#L14: Have you done the paperwork to assign this copyright? (I always confirm this)
- ert-results.el#L230: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- ert-results.el#L231: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
```

- ert-results.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/).  I do see you have `Licensed under the GNU General Public License, version 3.` but being formal means machine detectability.

**Comment by rswgnu** [comment]
Ok, I will add an SPDX.  The key nindings are not used in the mode, so are available as is.And yes, my copyright assignment is on file with the FSF.-- rswOn Jan 1, 2024, at 9:48 PM, Chris Rayner ***@***.***> wrote:﻿
Thank you for this, and thank you again @progfolio .  My quick first pass --
ert-results.el with melpazoid:
- ert-results.el#L14: Have you done the paperwork to assign this copyright? (I always confirm this)
- ert-results.el#L230: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- ert-results.el#L231: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`


ert-results.el needs formal license boilerplate and/or an SPDX-License-Identifier.  I do see you have Licensed under the GNU General Public License, version 3. but being formal means machine detectability.

**Comment by rswgnu** [comment]
Did the above and conditionalized the key bindings so they can't interfere
with any prior ones from ert.el.

**Comment by rswgnu** [comment]
Any timeframe on when this will get merged?  Thanks.

**Comment by progfolio** [comment]
> Any timeframe on when this will get merged? Thanks.

The queue is usually worked through once a week.

**Comment by rswgnu** [comment]
Thanks, I’ll look forward to being able to announce it.

**Comment by riscy** [comment]
Thank you -- here is one more very minor byte-compile warning that popped up:

`ert-results.el` with byte-compile using Emacs 29.1:
```
ert-results.el:324:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
```
This warning is a real drag and only appeared in Emacs 29, but in *this* case it's actually accurate!  The issue is that the `*Help*` buffer will render this docstring as:
```
ert-results--map-tests is a Lisp closure.

(ert-results--map-tests FUNC)

In an ert results buffer, return result of applying FUNC over its tests.
For example, to get all test names: (ert-results-map-tests #’ert-test-name).
```
and you'll notice that `ert-test-name` has the wrong kind of quote on it.

I'll try to take another look at this today if you're able to sort this out, since it's such an easy fix.  But since this has been promoted to a byte-compile warning, I prefer to treat it seriously.

(My personal opinion on this counts for little, but I truly wish Emacs had originally went with *not* manipulating the apostrophes in docstrings downstream, which would completely avoid this sort of issue)

**Comment by rswgnu** [comment]
I’m just getting off a flight but will try to deal with late today.-- BobOn Jan 7, 2024, at 3:34 PM, Chris Rayner ***@***.***> wrote:﻿
Thank you -- here is one more very minor byte-compile warning that popped up:
ert-results.el with byte-compile using Emacs 29.1:
ert-results.el:324:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)

This warning is a real drag and only appeared in Emacs 29, but in this case it's actually accurate!  The issue is that the *Help* buffer will render this docstring as:
ert-results--map-tests is a Lisp closure.

(ert-results--map-tests FUNC)

In an ert results buffer, return result of applying FUNC over its tests.
For example, to get all test names: (ert-results-map-tests #’ert-test-name).

and you'll notice that ert-test-name has the wrong kind of quote on it.
I'll try to take another look at this today if you're able to sort this out, since it's such an easy fix.  But since this has been promoted to a byte-compile warning, I prefer to treat it seriously.
(My personal opinion on this counts for little, but I truly wish Emacs had originally went with not manipulating the apostrophes in docstrings downstream, which would completely avoid this sort of issue)

**Comment by rswgnu** [comment]
Pushed a fix for this doc string issue.

**Comment by riscy** [comment]
Thanks again -- and welcome to MELPA. :)

**Comment by rswgnu** [comment]
Thanks, Chris.  That took 2 weeks.  Hopefully, future single file packages
won't be so involved.

Cheers,

Robert

**Pull request merged**
