### PR TITLE
add recipe ob-php

### PR DESCRIPTION
**Pull request by stardiviner**
https://github.com/stardiviner/ob-php

### CODE REVIEW

**Comment by stardiviner** [comment]
Oops, the package `s` always want to be dead sometimes.

**Comment by purcell** [comment]
MELPA was a bit broken at the time of the travis build, so don't worry about that. :-)

The package description needs to be fixed, because it says: "Execute Redis queries within org-mode blocks."

**Comment by stardiviner** [comment]
@purcell ok, fixed, sorry for my reckless.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
