### PR TITLE
Add beef-mode recipe

### PR DESCRIPTION
**Pull request by thechampagne**
### Brief summary of what the package does

Syntax highlighting for the Beef programming language.

### Direct link to the package repository

https://github.com/thechampagne/beef-mode

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Hi @thechampagne - just writing to let you know I see this, but try to restrict myself to one PR per author per cycle.

**Comment by riscy** [comment]
Quick first pass on this one --

`beef-mode.el` with package-lint 20221003.1636:
```
1 issue found:
172:4: warning: Closing parens should not be wrapped onto new lines.
```
Easy fix here.

As with the [ring-mode PR](https://github.com/melpa/melpa/pull/8254) we should endeavor to take these language major-mode recipes as far as we can before indexing them into MELPA.  It seems quite feasible to define the comment-start/comment-end variables, for example, and this looks like a C-like programming language whose `indent-line-function` can also be defined, which will *greatly* improve the use of this major mode for users.

**Comment by riscy** [comment]
Friendly ping. :) I do see some development happening on the upstream, but let me know when you're ready for another pass.

**Comment by riscy** [comment]
Hi @thechampagne, just another friendly ping.

**Comment by riscy** [comment]
Another quick ping @thechampagne.  If we've lost touch with you for now, it may be worthwhile for us to close your other PRs.  They can always easily be opened in the future!

**Comment by thechampagne** [comment]
Hey, sorry for the late reply the reason is that I don't have any new thing to add this mode.

**Comment by riscy** [comment]
Thanks for your reply.  I don't want to sound too stern, but please refer to the last paragraph of [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org) and try to communicate what you've changed (and what feedback you've decided not to address).

Regarding this feedback from before:

> this looks like a C-like programming language whose indent-line-function can also be defined, which will greatly improve the use of this major mode for users.

It looks like you have decided not to implement this.  This is fine, but a bit disappointing if you intend to be the maintainer of a dozen major modes.  Admittedly, indent-line-functions are some of the most challenging parts of major modes to implement, but they're also arguably the most useful.  I recommend you read up on this (check out smie or other packages that can help you out with this).

**Pull request merged**
