### PR TITLE
Add recipe help-find-org-mode

### PR DESCRIPTION
**Pull request by EricCrosson**
### Brief summary of what the package does

Advises built-in help functions to find org source-bocks over tangled-code where possible

### Direct link to the package repository

https://github.com/ericcrosson/help-find-org-mode

### Your association with the package

- author
- maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by equwal** [comment]
Remove `#'` from before the functions in `help-find-org-mode`. No further complaints.

**Comment by equwal** [comment]
My mistake, I agree with you and it is the better choice for byte compiler.

**Comment by equwal** [comment]
Jumping to ORG source is duplicated here: https://github.com/melpa/melpa/pull/5849

**Comment by purcell** [comment]
Merged, thanks.

> Jumping to ORG source is duplicated here: #5849

Maybe, but the packages don't appear related, and this one has a clear narrow purpose.

**Pull request merged**
