### PR TITLE
merge request of a recipe gemini-code-completion

### PR DESCRIPTION
**Pull request by shishimaru**
### Brief summary of what the package does

This package inserts source code generated with Google Gemini by sending parts of code opened in current buffer.

### Direct link to the package repository

https://github.com/shishimaru/gemini-code-completion.el

### Your association with the package

I am a maintainer of this package.

### Relevant communications with the upstream package maintainer

On this pull request.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  This PR modifies two recipe files - could you exclude the `helm-find-project-files` recipe?

In the meantime, re: google-gemini, it appears it has a dependency (google-gemini) that is not installable -

`gemini-code-completion.el` with byte-compile using Emacs 29.4:
```
gemini-code-completion.el:30:2: Error: Cannot open load file: No such file or directory, google-gemini
```

`gemini-code-completion.el` with package-lint 20240507.1722:
```
1 issue found:
7:23: error: Package google-gemini is not installable.
```

`#'load`-check on each file:
```
Loading gemini-code-completion.el
  gemini-code-completion.el:Error: Emacs 29.4:
  (file-missing "Cannot open load file" "No such file or directory" "google-gemini")
```

**Comment by shishimaru** [comment]
> Thanks for this. This PR modifies two recipe files - could you exclude the helm-find-project-files recipe?

Oh, sorry, it is my old recipe and not needed in this package.

> In the meantime, re: [gemin-code-completion] it appears it has a dependency (google-gemini) that is not installable -

It is a dependent package distributed via JCS ELPA, not Melpa.
https://github.com/emacs-openai/google-gemini

I want to get your advice, how should I describe the dependency in the header of my code gemini-code-completion.el ?

**Comment by tarsius** [comment]
> It is a dependent package distributed via JCS ELPA, not Melpa.

It is `gemini-code-completion` which depends on `google-gemini`.

Melpa only distributes packages whose dependencies are part of Emacs or are being distributed on GNU Elpa, NonGNU Elpa or Melpa itself. So you will have to ask the maintainer of JCS ELPA, if he is willing to distribute your package there.

**Comment by tarsius** [comment]
Closing since the author will to open a new pr when he is ready (as per https://github.com/emacs-openai/google-gemini/issues/2).

**Pull request closed without merging**
