### PR TITLE
Create eta

### PR DESCRIPTION
**Pull request by zcaudate**
### Brief summary of what the package does

This is a *micro-framework* for customising key-bindings built on top of [bind-key](https://github.com/jwiegley/use-package/blob/master/bind-key.el). It provides two macros for standardising and associating intent with key-bindings: a standard version `eta/bind` and multi-dispatch version for standardisation of functionality across major modes: `eta/mode`.

### Direct link to the package repository

https://github.com/zcaudate/eta

### Your association with the package

the maintainer.

### Relevant communications with the upstream package maintainer

This is my first commit to melpa so hopefully it goes through.

### Checklist

Please confirm with `x`:

- [ x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x ] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- quickly looking over this.

- Your `;;; Commentary` line probably needs updating (currently says: "call docker build on org babel block"), ideally with some entrypoints or maybe usage examples -- your Brief Summary above would even be good, but the README looks excellent, so I think it's just a matter of putting the right text in
- The asterisks around the variable names like `eta-*lock*` are nonstandard I think, although in your defense package-lint didn't complain about these -- but generally it's encouraged to stick to letters and hyphens
- I don't see the rationale for wrapping `eta-bind-fn` with the `eta-bind` macro, but maybe I'm missing something; while I'm looking at that code, the `if` inside `eta-bind-fn` could probably just be a `when` and then you wouldn't need a `progn` nested inside
- Similar for the `eta-mode` macro simply wrapping `eta-mode-form`; and while I'm here, `eta-mode` is easily mistaken for an Emacs major or minor mode, so I would recommend renaming this function since it's neither of these
- The dependency on `s` is unnecessary and I'd suggest dropping it since you only use `s-concat`, which is just a `concat` wrapper
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible / See: https://github.com/licensee/licensee

**Comment by riscy** [comment]
Also your summary line can lose the semicolon after "bind".  :)

**Comment by zcaudate** [comment]
@riscy thanks for looking through the code. Most of the `non-conventions` such as the `*earmuffs*` and the `-fn` for macros are habits from clojure. The linter and the checker really caught me by surprise (like in a pleasant way). I wasn't prepared for that at all and I did the bare minimum to pass it. You can see [this](https://github.com/zcaudate/eta/commit/ae339e4d741fca732481effbda607c7161a0c2f0#diff-b908fca3489bae2bdc414914a5aa0f5417250a7d6649b10c11f0ccdb0b3cd9f6) was what I submitted before I read through the checklist.

I'll fixed those up shortly.

**Comment by riscy** [comment]
Thanks for the explanation!  I'm meaning to check out Clojure soon.  Feel free to ping when ready for another check.

**Comment by zcaudate** [comment]
@riscy: ping

- Added License
- Copied intro to commentary
- `mode` renamed to `modal`
- removed `s`
- changed `if` to `when`
- `eta-*<name>*` rename to eta-var-<name>

Clojure's kinda stalled right now (to be honest, the code quality for a lot of libraries are not that good and it also needs a better compiler which is not going to happen) but still worth getting into for the concurrency model alone.  Also the jvm is getting better and better so it's a good gateway drug.

**Comment by riscy** [comment]
Looks good!  And, welcome to MELPA. :)

Minor and non-blocking:
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems

**Comment by zcaudate** [comment]
yay.

I'm a bit confused by how to add `-*- lexical-binding: t; -*-`

currently there's a description on the first line (without the semicolon)

```
;;; eta.el --- Standard and multi dispatch key bind -*-
```

Do I just remove the description?

**Comment by riscy** [comment]
```
;;; eta.el --- Standard ... key bind -*- lexical-binding: t -*-
```

**Pull request merged**
