### PR TITLE
Added recipe for vital-dark-theme

### PR DESCRIPTION
**Pull request by tashrifsanil**
### Brief summary of what the package does

Vital Dark theme is a minimal Emacs color theme that highlights important elements of your code, and is meant to be easy on the eyes. It's an attempted clone of the vital dark syntax theme for emacs. This theme uses spacemacs-theme as base. There's only a dark variant and it should work 256 color terminals.

### Direct link to the package repository

https://github.com/tashrifsanil/vital-dark-theme

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]
I guess I'm all of the above

### Relevant communications with the upstream package maintainer

[e.g., package.el compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ ] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Please remove byte-compiled file from repository
- Please remove autoload file from repository.

Both files are generated by package.el at installing.

**Comment by tashrifsanil** [comment]
Sorry about that, I've removed the byte-compiled file and the autoload file

**Comment by purcell** [comment]
Thanks. Quick feedback:
- `"A dark color theme for Emacs"` -- all Emacs themes are for Emacs, so you should remove `for Emacs` from this! :-)
- It would be preferable for you to use the standard boilerplate comments in `vital-dark-theme.el`: just 2 of several advantages would be that the `-pkg.el` file would then not be necessary, and you would have included information about the licence under which you are distributing this code. (Ironically, you have all the necessary boilerplate in the `-common` file, but not this one.)
- `dyn-let`, `true-color-p` etc. should be prefixed with the package name.
- Testing for display capabilities at the time you create the theme is a completely invalid approach, since the theme will potentially be used on many future frames with different capabilities. The correct approach is to specify different conditional class variants for each of the faces, then Emacs will automatically select the variant for the current frame based upon its display capabilities.

Hope that helps!

**Comment by tashrifsanil** [comment]
Thanks for your reply purcell. I've made changes based on your first 3 points. But the your last point is where I'm kind of at a loss. I'm only beginning to understand some of the capabilities of the colour theme, and most of it was shamelessly taken from the dark variant of the [spacemacs theme](https://github.com/nashamri/spacemacs-theme). Needless to say the look of the theme came to be by fiddling around with the spacemacs theme. I'm kind of unsure about how as to go about your last point, an example code snippet or something would be very helpful

**Comment by purcell** [comment]
> I'm kind of unsure about how as to go about your last point, an example code snippet or something would be very helpful

Sure. Here's how the built-in `font-lock-keyword-face` is defined:
```el
(defface font-lock-keyword-face
  '((((class grayscale) (background light)) :foreground "LightGray" :weight bold)
    (((class grayscale) (background dark))  :foreground "DimGray" :weight bold)
    (((class color) (min-colors 88) (background light)) :foreground "Purple")
    (((class color) (min-colors 88) (background dark))  :foreground "Cyan1")
    (((class color) (min-colors 16) (background light)) :foreground "Purple")
    (((class color) (min-colors 16) (background dark))  :foreground "Cyan")
    (((class color) (min-colors 8)) :foreground "cyan" :weight bold)
    (t :weight bold))
  "Font Lock mode face used to highlight keywords."
  :group 'font-lock-faces)
```
Note that this single face definition has variants with different class specs, and Emacs then chooses the first variant which matches the specs of the current frame. It's pretty elegant, and completely standard. :-)

**Comment by tashrifsanil** [comment]
I do apologize for the late response, but I'm kind of having issues wrapping my head around what specifically I'm supposed to change. Do I modify everything after the basics section, and do I declare each of the faces with defface as shown in the snippet? I do apologize if this comes off as overly trivial

**Comment by purcell** [comment]
Yep, such that each face entry under basics would have a couple of variants defined. The true-colour variant would have the class `((class color) (min-colors 16777216))` and the other would have a class like `((class color) (min-colors 89))`.

**Comment by tarsius** [comment]
@tashrifsanil Any progress on this?

**Comment by tarsius** [comment]
This has been open for more than half a year now. Closing.
Feel free to open a new pull request when you are ready.

**Pull request closed without merging**
