### PR TITLE
Add recipe format-region

### PR DESCRIPTION
**Pull request by tanrax**
### Brief summary of what the package does

Transform region in different formats: camelCase, kebap-case or lisp-case, PascalCase or snake_case.

### Direct link to the package repository

https://github.com/tanrax/format-region.el/

### Your association with the package

I am manteiner

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
The name "format-region" is a little broad for what this package does.
It would also be useful to hear how this differs from prior art such as:

https://github.com/akicho8/string-inflection

**Comment by riscy** [comment]
Strongly agree re: the name of the package.  Here's a quick first pass of the checklist in the meantime --

`format-region.el` with byte-compile using Emacs 28.1:
```
format-region.el:14:8: Warning: docstring wider than 80 characters
In format-region-curried:
format-region.el:28:11: Warning: docstring wider than 80 characters
format-region.el:33:7: Warning: assignment to free variable
    `format-region-to-format-camel-case'
format-region.el:34:7: Warning: assignment to free variable
    `format-region-to-format-kebab-case'
format-region.el:35:7: Warning: assignment to free variable
    `format-region-to-format-pascal-case'
format-region.el:36:7: Warning: assignment to free variable
    `format-region-to-format-snake-case'
In format-region-to-camel-case:
format-region.el:50:27: Warning: reference to free variable
    `format-region-to-format-camel-case'
In format-region-to-kebab-case:
format-region.el:55:27: Warning: reference to free variable
    `format-region-to-format-kebab-case'
In format-region-to-lisp-case:
format-region.el:60:27: Warning: reference to free variable
    `format-region-to-format-kebab-case'
In format-region-to-pascal-case:
format-region.el:65:27: Warning: reference to free variable
    `format-region-to-format-pascal-case'
In format-region-to-snake-case:
format-region.el:70:27: Warning: reference to free variable
    `format-region-to-format-snake-case'
In format-region-debug:
format-region.el:76:45: Warning: reference to free variable
    `format-region-to-format-camel-case'
format-region.el:77:45: Warning: reference to free variable
    `format-region-to-format-kebab-case'
format-region.el:78:46: Warning: reference to free variable
    `format-region-to-format-pascal-case'
format-region.el:79:45: Warning: reference to free variable
    `format-region-to-format-snake-case'
```

`format-region.el` with checkdoc 0.6.2:
```
format-region.el:15: Some lines are over 80 columns wide
```
(You definitely want to look at wrapping the lines in this source file; it's way outside the norm for Emacs lisp community standards.)

`format-region.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- The `;;; Commentary` for this file is much wider than 80 characters
- format-region.el#L20: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
- format-region.el#L22: It's safer to sharp-quote function names; use `#'`
- format-region.el#L33: Top-level `setq` should usually be replaced by `defvar`
- format-region.el#L34: Top-level `setq` should usually be replaced by `defvar`
- format-region.el#L35: Top-level `setq` should usually be replaced by `defvar`
- format-region.el#L36: Top-level `setq` should usually be replaced by `defvar`
```

Package and license:
- Prefer equivalent recipe: `(format-region :repo "tanrax/format-region.el" :fetcher github)`
- Invalid SPDX license: GNU General Public License v3.0 or later (you probably want `;; SPDX-License-Identifier: GPL-3.0-or-later`; SPDX is a very specific format)

**Comment by tanrax** [comment]
@progfolio The truth is that after String inflection my package only provides the possibility of transforming phrases, with spaces, to variable names. I was unaware of the existence of the package. I see 2 possibilities: 
1. Close it (it's not a relevant functionality for the community) 
2. Rename it to "phrase to variable", or similar.
From experience, what do you recommend?

**Comment by tanrax** [comment]
@riscy I have implemented the improvements you mentioned.

**Comment by riscy** [comment]
If your package is only providing marginally more functionality than the existing package, the third option which you didn't list is for you to make PRs to that package, and benefit its existing users.  (This is often the best outcome and it is usually what we prefer by far!).  Otherwise I think renaming it to be really clear about its scope is the best course of action.

And thank you for your edits - here's what remains otherwise  --

`format-region.el` with byte-compile using Emacs 28.1:
```
format-region.el:33:11: Warning: docstring wider than 80 characters
```
It was surprising to me when these became byte-compile *warnings* but this should be wrapped.  (Checkdoc will subsequently complain `format-region.el:34: First line is not a complete sentence` but this is lower-priority and addressable if you are willing to break up the sentence.)

`format-region.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- The `;;; Commentary` for this file is much wider than 80 characters
- format-region.el#L25: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
- format-region.el#L27: It's safer to sharp-quote function names; use `#'`
```
Please wrap the Commentary - downstream tools will not know how to do so (and can't know how, because Commentary may contain e.g. blocks of code that shouldn't be wordwrapped)

**Comment by tanrax** [comment]
@riscy I've applied the changes, modified my settings so I don't have any more problems with mixing tabs and spaces (thank you) and learned a bit more how to be careful with line lengths. 
Then, for the benefit of the users, you can close my Pull Request. My functionality is too simple not to be part of another library like string-inflection. 
I'm learning a lot thanks to your reviews, thank you very much. 
Any last advice?

**Comment by riscy** [comment]
Thank you for your understanding @tanrax - your situation is like mine, where I have a few scratch packages I've written that I don't feel ready to put up on MELPA for various reasons.  I'll close this, but you're welcome to reopen or follow-up any time. :)

**Comment by tanrax** [comment]
@riscy Thanks to you. I think you do a great job of filtering and training :)

**Pull request closed without merging**
