### PR TITLE
Add `random-generators` recipe

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
### Brief summary of what the package does

Functions to generate random numbers and data structures.

### Direct link to the package repository

https://github.com/emilyseville7cfg-better-emacs/random-generators/blob/main/random-generators.el

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
I don't understand why in this PR and in #8339 CI fails but in #8337 passes.

**Comment by progfolio** [comment]
> I don't understand why in this PR and in #8339 CI fails but in #8337 passes.

from the CI output: `"Recipe '%s' contains mismatched package name"`

Probably because your package is named random-generators, but the recipe file is named "random-generators.el"

**Comment by tarsius** [comment]
I.e., you repeated this mistake: https://github.com/melpa/melpa/pull/8323#issuecomment-1355850828, and the fix is the same this time around: drop the `.el` suffix.

**Comment by EmilySeville7cfg** [comment]
@riscy, can you review this PR?

**Comment by riscy** [comment]
Apologies for the delay in getting to this PR, @EmilySeville7cfg.  I know you read my [earlier comment as to why](https://github.com/melpa/melpa/pull/8337#issuecomment-1375243740) but I'll link it for reference.

You appear to be interested in writing library code that client code would depend on.  I love this, and I envy the motivated elisp devs who build stuff like this that I depend on.  But I feel you should accrue a bit more Emacs/Elisp experience and experiment with putting these libraries to use in nontrivial ways before rushing to index these for general consumption.  I want to be as helpful as possible here, so I'll invest some time in giving you concrete advice --

First, spend some time thinking on and rethinking APIs.  E.g. for this function signature, `random-generators-number (&optional from to)` because the version with one argument `(random-generators-number 10)` gives me a number from 10 to 100 (that's odd, right?), where most people would expect a number from 0 to 10.  So I recommend removing the `&optional` or putting `to` before `from`.  A lot of situations like these will resolve themselves through experience and/or using your library.

It's also an awkward decision imo to have two functions `random-generators-list-from` and `random-generators-list-from or-empty` that do the same thing, have virtually the same documentation, but one errors when the `sequence` argument is nil.  Imo you should just let empty sequences be mapped to empty sequences, and if the client code is worried about this they should handle the exceptional case themselves.

On the topic of error checking:  you may want to look at `cl-assert` for raising errors under certain conditions.  But I also notice identical (or very similar) error checking is being repeated again and again, e.g. these exact lines appear three times --
```elisp
  (unless (or (integerp from) (null from))
    (error "The lowest range boundary '%s' is not an integer or nil" from))
  (unless (or (integerp to) (null to))
    (error "The highest range boundary '%s' is not an integer or nil" to))
...
  (if (> from to)
      (error "The lowest range boundary '%s' exceeds the highest range boundary '%s'" from to))
```
and this to me invites deduplication in a separate validation function.  (I don't always agree with aggressive deduplication, but in this case the logic is identical and you'll benefit from not cluttering up the code with this stuff again and again).

And while we're talking about bounds, code like this:
```elisp
  (setq from (cond
              ((null from) 0)
              (t from))
        to (cond
            ((null to) 100)
            (t to)))
```
is more idiomatically and clearly written in elisp as e.g. `(setq from (or from 0) to (or to 100))` but I would recommend using separate `setq`s if there is any logic involved in the form at all, e.g.
```elisp
(setq from (or from 0))
(setq to (or to 100))
```
And, in the same vein, something like `(if (null sequence) '() (random-generators--list-from-implementation sequence length)))` should just be written `(when sequence (random-generators...)))`.

And then a few much more minor points:

- The package `;;; Commentary` should be expanded on -- `This package is the part of Better Emacs project.` is too little to go on, and your commentary should usually expand upon your summary line (first line of your file); a couple of examples is usually very helpful to users and reviewers like me
- The `;; URL:` line typically goes up next to your `;; Version` and other one-liner metadata; take a look at the highest quality packages on MELPA, and copy how they do it
- Regarding style (non-blocking): it's typical to put a space between the function name and argument list, so instead of `(defun random-generators-number(&optional from to)` you'd write `(defun random-generators-number (&optional from to)`; this is the community style and you should try to adhere when feasible.  You are also mixing tabs and spaces for indentation, which can have jarring effects if someone has a nonstandard tab width; prefer spaces only

**Comment by EmilySeville7cfg** [comment]
Thanks for advices. 😁 I'll address them.

**Comment by EmilySeville7cfg** [comment]
Thanks for advices. 😁 I'll address them.

**Comment by riscy** [comment]
Sounds good -- I am happy to take another look, but there's no rush.  The code is still quite young, and it's usually much better if a package like this has existed for a while and its use-cases ironed out before indexing for wider consumption.

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out.

**Pull request closed without merging**
