### PR TITLE
Add recipe for network-watch

### PR DESCRIPTION
**Pull request by jamiguet**
### Brief summary of what the package does

Package provides global minor mode for dealing with intermittent networking.

### Direct link to the package repository

https://github.com/jamiguet/network-watch

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
This needs some work still, sorry.
- You say above you're run `package-lint`, but I don't think you have: you've got a bunch of symbols which don't begin with `network-watch-`, which they all must. So use `network-watch-up-hook` etc.
- There's no point altering `after-init-hook`: what if someone loads this library after their Emacs is already started? You've missed my point about the global minor mode: when the mode is enabled, it should start watching the network and invoking the up/down hooks as necessary, and when the mode is disabled it should stop.
- Mapping interfaces per machine is unnecessary. This library doesn't need to know about the machine name to do its job, so it shouldn't.
- Don't call `customize-save-variable` directly: you should never decide for the user that their `custom.el` should be updated.
- Don't use `defvar` to [declare local variables]: you're acually declaring a global variable there. Use `let`, in general. In this particular case there are functions like and `mapcar`, `append` you can use to even avoid needing a local variable. I recommend reading "Practical Common Lisp" (available free online) to learn lisp style.
- Lots of typos: "intermitent", "refersh reate" etc.
- Based on its docstring `network-watch-p` should be called `network-watch-active-p`.
- `network-watch` is a very unclear variable name.
- Don't place the trailing `)` on its own line: that's bad lisp style. :-)

Hope that helps!

**Comment by jamiguet** [comment]
Thanks for the feedback I'll get cracking on those changes and further
education.

Hooks appear to not be reported by package lint I tweak it further.

Thanks again

**Comment by jamiguet** [comment]
Apologies for the delay, life got on the way of hacking.

I believe all the comments have been addressed.
Thank you for your feedback I have learned quite a bit in the process.

Let me know if any other elements need improving.

**Comment by purcell** [comment]
Thanks. Sent you a bunch of fixes in https://github.com/jamiguet/network-watch/pull/1.

**Comment by purcell** [comment]
Merged now - thanks!

**Pull request merged**
