### PR TITLE
Add recipe for flycheck-plantuml

### PR DESCRIPTION
**Pull request by alexmurray**
### Brief summary of what the package does
Integrates plantuml with flycheck for automatic syntax errors highlighting for plantuml documents in Emacs

### Direct link to the package repository

https://github.com/alexmurray/flycheck-plantuml

### Your association with the package

I am the maintainer

### Relevant communications with the upstream package maintainer

I am the maintainer :smile: 

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Looks good.

BTW I suppose `with-eval-after-load` is better than `eval-after-load`. `with-eval-after-load` was introduced at Emacs 24.4 so it is no problem for this package users.

**Comment by alexmurray** [comment]
Thanks for the hint on `with-eval-after-load` - have just made the change in https://github.com/alexmurray/flycheck-plantuml/commit/e521525e9ee02ea95cbea6f674a077916ec203a2

**Comment by syohex** [comment]
Merged

**Comment by alexmurray** [comment]
Thanks.

**Pull request merged**
