### PR TITLE
Add dwim-coder-mode

### PR DESCRIPTION
**Pull request by pksadiq**
### Brief summary of what the package does

An Emacs mode to let you code/go crazy

### Direct link to the package repository

https://gitlab.com/sadiq/crazy-mode

### Your association with the package

I'm the maintainer of the package

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

There are no public `defun`s.  And so I guess it's okay for them to not have any documentation.

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I notice you're using Emacs 29 which hasn't been released, so please forgive any oversights (my pipeline only checks with the current release, Emacs 28).  Quick first pass --

I see you've used `checkdoc` but please make an effort to address at least some of its feedback.  Consider:

- crazy-common.el:52: All interactive functions should have documentation
- crazy-default.el:25: You should convert this comment to documentation
- crazy-mode.el:34: All interactive functions should have documentation
- crazy-mode.el:54: Messages should start with a capital letter (you can quote the form, e.g. 'treesitter')

`crazy-c.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- crazy-c.el#L152: This double negation can be collapsed (`not` aliases `null`)
```

`crazy-common.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- crazy-common.el#L74: It's safer to sharp-quote function names; use `#'`
- crazy-common.el#L98: It's safer to sharp-quote function names; use `#'`
- crazy-common.el#L108: It's safer to sharp-quote function names; use `#'`
- crazy-common.el#L113: It's safer to sharp-quote function names; use `#'`
- crazy-common.el#L56: It's safer to sharp-quote function names; use `#'`
```

`crazy-default.el` with byte-compile using Emacs 28.1:
```
crazy-default.el:47:43: Warning: the function `pos-bol' is not known to be
    defined.
```
Perhaps this is an Emacs 29ism?  If so disregard.

`crazy-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- crazy-mode.el#L94: It's safer to sharp-quote function names; use `#'`
- crazy-mode.el#L95: It's safer to sharp-quote function names; use `#'`
```

Package and license:
- Creative Commons Zero v1.0 Universal (via API)
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to crazy-c.el
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to crazy-common.el
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to crazy-default.el
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to crazy-mode.el
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to crazy-python.el
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to crazy-rust.el

**Comment by pksadiq** [comment]
```
crazy-default.el:47:43: Warning: the function `pos-bol' is not known to be
    defined.
```

Yes, this is an Emacs 29 API

Everything else fixed. thanks for the suggestions.

**Comment by pksadiq** [comment]
Renamed to dwim-coder-mode. I believe the CI failure is unrelated

**Comment by riscy** [comment]
The CI failure is probably due to this being forked from a non-recent version of mainline, but I'm able to confirm on my end that this will build.

I think this is a good first contribution and I'm happy to merge (welcome to MELPA :) -- although I would encourage you to enhance your `;;; Commentary` so that people browsing the MELPA package index know what languages this impacts (i.e. not all "programming modes", of course - only C, Python and Rust currently).  We ask that you take a look at checkdoc too (within reason) and simple nags like "dwim-coder-python.el:28: You should convert this comment to documentation" are totally fixable and imo a strict improvement.

**Pull request merged**
