### PR TITLE
Add company-ctags recipe

### PR DESCRIPTION
**Pull request by redguardtoo**
### Brief summary of what the package does

This library enables the completion using Company mode and Ctags for Emacs. It's simply fast because a new optimized algorithm is designed for Ctags.

### Direct link to the package repository

https://github.com/redguardtoo/company-ctags

### Your association with the package

I'm the developer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Taking a quick look at this --

Is there a major distinction between this and [https://github.com/company-mode/company-mode/blob/master/company-etags.el](company-etags)?  I can see you've contributed to company-etags and even have a blog post on using ctags with etags, so I thought I'd check.

Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems) (and depend on at least (emacs "24"))
(The following assumes lexical binding is enabled)
```
company-ctags.el:354:1:Warning: Unused lexical argument `backends'
```
(This may indicate a bug?  `backends` is supplied but not used)

Added miscellaneous hints (automated):
- company-ctags.el#L11: This statement may not currently be accurate (i.e. you're not part of Emacs)
- company-ctags.el#L6: Prefer `https` over `http` (if possible)
- company-ctags.el#L24: Prefer `https` over `http` (if possible)

**Comment by redguardtoo** [comment]
Thanks. I updated my code.

The `company-ctags` use new algorithm optimized for ctags. So it's faster than `company-etags`.

`company-etags` does not accept my pull request.

**Comment by riscy** [comment]
Apologies for the delay on this.  Can you link us to the pull request?

**Comment by redguardtoo** [comment]
@riscy , I'm not sure. You mean the original company pull request?

It's https://github.com/company-mode/company-mode/pull/904

The request was reverted in https://github.com/company-mode/company-mode/pull/909

So I create a new package company-ctags.

**Comment by riscy** [comment]
> company-etags does not accept my pull request.

This pull request. :)

**Comment by riscy** [comment]
Oh, I see that is the pull request.  How come it was reverted?  Apologies for the battery of questions, but I'm missing a lot of context here.

**Comment by redguardtoo** [comment]
It's decided it's better to apply my new algorithm to Emacs internal API`tags-completion-table`.

It's doable but also requires a lot of changes of my optimization only for ctags. It could take a long time to get my code to be released. When it's released, it might not be ctags related, more like some generic tag search API (and a bit slower).

So I think it's better to release `company-ctags` as an independent package for now, so users who use ctags can use a fastest code completion engine optimized for ctags only right now.

**Comment by riscy** [comment]
Ah, I see.  Thanks!

**Comment by riscy** [comment]
Thanks for your patience - merging.

**Pull request merged**
