### PR TITLE
Add the `jsonian` package

### PR DESCRIPTION
**Pull request by iwahbe**
### Brief summary of what the package does

`jsonian` provides another major mode to edit json files. It is different then `json-mode` because it works much faster on large files. It also includes a different set of utility functions:
- `jsonian-path` to retrieve the json path to `(point)` (this does exist in `json-mode` but the way it works does not scale to the file sizes I regularly encounter).
- `jsonian-edit-string` which makes it easy to edit large multi-line strings. 

### Direct link to the package repository

https://github.com/iwahbe/jsonian

### Your association with the package

I am the author and maintainer. 

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them
   😄

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

- jsonian.el#L744: Loading a package should rarely add advice.  In this case, I would at least defer this advice-add until the mode is enabled for the first time.  You may also want to define a function called `jsonian-unload-function` that removes this advice so that if someone calls `unload-feature` on jsonian, they won't get errors when trying to `narrow-to-defun`.
- jsonian.el#L781: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to jsonian.el; MELPA won't package the LICENSE file, and an SPDX license identifier would be unambiguous and machine-detectable

**Comment by iwahbe** [comment]
I merged in https://github.com/iwahbe/jsonian/pull/21 to address your first pass.

**Comment by riscy** [comment]
Thanks -- taking a deeper look now.

- You mention this is much faster than `json-mode` (which is also on MELPA) but can you comment on where the speed-ups come from (and maybe if they can be merged into json-mode too?)  Also, have you compared to the default builtin json-editing-mode, i.e. `javascript-mode`?
- This is also not a blocker at all, but have you had a chance to look at https://melpa.org/#/json-navigator for comparison purposes?
- `(add-to-list 'magic-fallback-mode-alist '("^[{[]$" . jsonian-mode))` seems a little bit aggressive (and, well, magic); I can see `json-mode` does this too, but it may be safer to suggest this to users in your `;;; Commentary`. But I'm open to discussing
- `(add-to-list 'auto-mode-alist '("\\.json\\'" . jsonian-mode))` will duplicate an existing builtin Emacs auto-mode-alist entry.  I think this is okay in this case, but I'd mention it in your `;;; Commentary` that users will see an immediate overriding effect when they load the package
- It seems your `;;; Commentary` could be expanded to mention the major mode itself, as well as a couple of the other interactive functions like the traversal functions (`jsonian-enclosing-item`), `jsonian-find`
- connivance -> convenience
- jsonian.el#L48: It's safer to sharp-quote function names; use `#'`

**Comment by iwahbe** [comment]
Again, thanks for the feedback. I appreciate the time and expertise. https://github.com/iwahbe/jsonian/pull/25 addresses this set of changes. I'll address your points in order:
- Speed
  - syntax highlighting:`jsonian-mode` applies faster syntax highlighting then `javascript-mode`. I didn't look that deep into `javascript-mode`, but their parsing is necessarily much more complicated then parsing the JSON acceptable subset of javascript. `json-mode` is derived from `javascript-mode`, so it incurs the same penalties that `javascript-mode` has. It has a further set of regex based syntax highlighting to highlight keys separate then values. `jsonian-mode` uses custom string parsing functions to identify keys vs values, which take optimizations not available to regex such as checking the highlight state of the preceding character. I added a speed section in my [README](https://github.com/iwahbe/jsonian/blob/41e2f32b5e68b9eee9842c612ad24288108ea62b/README.md#L179-L213) which addresses this question numerically and in greater detail.
  - Path finding: `json-mode` exposes [`json-snatcher`](https://github.com/Sterlingg/json-snatcher) which implements the same functionality as `jsonian-path`. `json-snatcher` operates by parsing the buffer, and then looking up your position to determine which node the point is in. `jsonian-path` is much faster since it parses back from the requested point to the document root, thus parsing only necessary segments. It avoids parsing interior objects by using emacs's ability to bounce between balanced matching brackets/braces.
- I hadn't seen `json-navigator`. It's a very cool way to display a JSON document, especially when the document is small. Unfortunately, it requires a prompt parse to display the hierarchy. 
- I'm happy to move that to the commentary section. I added it since I saw that `json-mode` had it and I was trying for full parity at the time. If it isn't standard it can be moved.
- I mentioned it in the `;;; Commentary` section.
- Updated
- Fixed
- I was actually trying to alias a variable instead of a function, which I suppose is why the `#'` syntax exists. I fixed that.

**Comment by riscy** [comment]
Thanks so much for the explanations, I can tell you've given it a lot of thought.  This looks good to merge -- and, welcome to MELPA.

**Pull request merged**
