### PR TITLE
New theme cycle package

### PR DESCRIPTION
**Pull request by Traivok**
#### Later, i pretend to implement a automatic theme changing by hooks.

;; Copyright (c) 2017 Free Software Foundation, Inc.

;; Autor: José Ricardo Alves Figueirôa <jraf@cin.ufpe.br>
;; Version: 1.0
;; Package-Requires: ((emacs "24.3"))
;; Keywords: faces
;; URL: https://github.com/Traivok/emacs-theme-cycle

### Direct link to the package repository

https://github.com/Traivok/theme-cycle

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

Emacs 24.3 is needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for taking the time to submit this! There's already a [cycle-themes package](https://github.com/toroidal-code/cycle-themes.el/blob/master/cycle-themes.el), so by default I'm slightly -1 on adding a new similarly-named package which tries to do the same thing. I note that you support separate lists of themes, e.g. dark and light, but this could be implemented on top of `cycle-themes`, or added to it.

Additionally, the keymap handling here is very unidiomatic: it's not even possible to bind a preferred key to a function that will cycle themes in a specific direction.

**Comment by Traivok** [comment]
Thanks for the feedbeck, this is my first project with FP.

I will do my best to make better packages in the future. :)

**Comment by purcell** [comment]
No worries -- it's great that you got something working. If you have any elisp questions, just let me know.

**Comment by Traivok** [comment]
Thank you very much.

I'm not experienced with functional programming, but i started reading "Structure and Interpretation of computer" programs recently. Emacs itself is a PF study.

Is it a good start? Can you recommend other good books?

**Comment by purcell** [comment]
Yes, SICP is a really good starting point. You might also consider Practical Common Lisp, because that covers a lot of the FP mindset, and also teaches a lot of stuff about Lisp that you can apply to Elisp.

**Comment by Traivok** [comment]
Thanks a lot.

**Pull request closed without merging**
