### PR TITLE
add madhat2r-theme recipe

### PR DESCRIPTION
**Pull request by madhat2r**
Provides an easy on the eyes dark theme for emacs

https://github.com/madhat2r/madhat2r-theme

I am the owner/maintaner 

### Checklist

- [ x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I cannot load this package by following error.

```
Load error for madhat2r-theme.el:
(void-variable dotspacemacs-use-ido)
```

- All package symbols(functions and variables) should start with package prefix, so `create-madhat2r-theme` should be `madhat2r-create-theme`
- autoload cookie of `provide-theme` is not necessary
- Please remove `pkg.el` file. Its content does not consistent with package header of `madhat2r-theme.el`
- A customize variable `madhat2r-theme-comment-bg` is never used.

**Comment by madhat2r** [comment]
Sorry I missed those. All corrected now.

**Comment by madhat2r** [comment]
Thanks @purcell  for the feedback. I have this all cleaned up now.

**Comment by purcell** [comment]
Nice work, thanks!

**Pull request merged**
