### PR TITLE
Add recipe for sse.

### PR DESCRIPTION
**Pull request by clonex10100**
### Brief summary of what the package does

Library that adds a function to listen to SSE streams.

### Direct link to the package repository

https://github.com/clonex10100/sse.el

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

N/A

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
I'd suggest you somehow add the word `server-sent event` to your summary line to help discoverability of this package -- I notice the elisp file itself never expands/links the acronym SSE, not even in the Commentary block.  I mention this because I was unfamiliar with the term. :)

And, thank you for your close adherence to the checklist.  The only feedback I have is that a line like this:
```elisp
(advice-add #'url-http-generic-filter :after #'sse--url-filter-advice)
```
shouldn't happen automatically as soon as the package is imported, and should probably be suggested in your `;;; Commentary`, or supported by toggling a mode.  This lets users deactivate the package without having to restart Emacs and can prevent difficult debugging situations from arising.

**Comment by riscy** [comment]
I'll mark this awaiting upstream, but feel free to ping for anything.

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by tarsius** [comment]
I am closing this since we haven't heard back in a year.

If you still want to add this, then please address the feedback and then ask us to reopen and do another review.

**Pull request closed without merging**
