### PR TITLE
add virtual-comment

### PR DESCRIPTION
**Pull request by thanhvg**
### Brief summary of what the package does
This package allows adding virtual comments to files in buffers. These comments
don't belong to the files so they don't. They are saved in project root or a
global file which can be viewed and searched. The file name is `.evc`.

### Direct link to the package repository

https://github.com/thanhvg/emacs-virtual-comment

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

Non needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Just taking a quick peek.  Is there any comparison to be made with [persistent-overlays](https://github.com/mneilly/Emacs-Persistent-Overlays)?  In the meantime:

- virtual-comment.el#L692: It's safer to sharp-quote function names; use `#'`
- virtual-comment.el#L693: It's safer to sharp-quote function names; use `#'`
- virtual-comment.el#L697: It's safer to sharp-quote function names; use `#'`
- virtual-comment.el#L701: It's safer to sharp-quote function names; use `#'`
- virtual-comment.el#L707: It's safer to sharp-quote function names; use `#'`
- virtual-comment.el#L708: It's safer to sharp-quote function names; use `#'`
- virtual-comment.el#L711: It's safer to sharp-quote function names; use `#'`
- virtual-comment.el#L714: It's safer to sharp-quote function names; use `#'`
- virtual-comment.el#L633: Lighter should start with a space
- virtual-comment.el#L400: Could this point/point-at-bol comparison use `bolp`?

**Comment by riscy** [comment]
And:

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by thanhvg** [comment]
Thank you for reviewing my packages. 

I added sharp quotes and fixed the lighter name. Thank you for showing me the `bolp` function. I have replaced the old predicate with it. I also added license file.

Regard to package https://github.com/mneilly/Emacs-Persistent-Overlays, I don't see it has the same features as this package. As I already mentioned in the commentary section of the package and the readme file: https://github.com/blue0513/phantom-inline-comment and  https://www.emacswiki.org/emacs/InPlaceAnnotations are similar packages and inspirations to this one.

Thanks.

**Comment by riscy** [comment]
Thank you!

**Pull request merged**
