### PR TITLE
First check-in of new salesforce-utils recipe

### PR DESCRIPTION
**Pull request by grimnebulin**
Hi--

This is a very short package of Salesforce utility functions, all related to converting a 15-character Salesforce ID into an 18-character ID-with-checksum.

The source repository is here:

https://github.com/grimnebulin/emacs-salesforce

I am the creator/maintainer.

### CODE REVIEW

**Comment by syohex** [comment]
- There is no `provide`(ex `(provide 'salesforce-utils)` ) so users cannot load it by `(require 'salesforce-utils)`.
- It uses cl-lib functions but it does not load cl-lib and does not have a package-dependency header. (Load cl-lib.el instead of cl.el and remove `eval-when-compile` because it uses not only macros but also functions)
- Load `thingatpt` package for using `word-at-point` which is not autoloaded function

**Comment by grimnebulin** [comment]
OK, I've updated my source repo per your comments.  Please have another look.

**Comment by purcell** [comment]
Thanks! Pending https://github.com/grimnebulin/emacs-salesforce/pull/1.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
