### PR TITLE
Add elsa

### PR DESCRIPTION
**Pull request by Emiller88**
### Brief summary of what the package does

Elsa is a tool that analyses your elisp code without loading or running it. It can track types and provide helpful hints when things don't match up before you even try to run the code.

### Direct link to the package repository

https://github.com/emacs-elsa/Elsa

### Your association with the package

An enthusiastic user

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by Fuco1** [comment]
This won't work properly because the `bin` directory won't be packaged.  Look at how `buttercup` does it.

**Comment by Fuco1** [comment]
This won't work properly because the `bin` directory won't be packaged.  Look at how `buttercup` does it.

**Comment by Fuco1** [comment]
This won't work properly because the `bin` directory won't be packaged.  Look at how `buttercup` does it.

**Comment by Fuco1** [comment]
This won't work properly because the `bin` directory won't be packaged.  Look at how `buttercup` does it.

**Comment by Fuco1** [comment]
This won't work properly because the `bin` directory won't be packaged.  Look at how `buttercup` does it.

**Comment by Fuco1** [comment]
This won't work properly because the `bin` directory won't be packaged.  Look at how `buttercup` does it.

**Comment by Fuco1** [comment]
This won't work properly because the `bin` directory won't be packaged.  Look at how `buttercup` does it.

**Comment by Fuco1** [comment]
This won't work properly because the `bin` directory won't be packaged.  Look at how `buttercup` does it.

**Comment by Fuco1** [comment]
This won't work properly because the `bin` directory won't be packaged.  Look at how `buttercup` does it.

**Comment by Fuco1** [comment]
This won't work properly because the `bin` directory won't be packaged.  Look at how `buttercup` does it.

**Comment by Fuco1** [comment]
This won't work properly because the `bin` directory won't be packaged.  Look at how `buttercup` does it.

**Comment by Fuco1** [comment]
Sorry for the duplicates.... github was acting crazy in the morning.

**Comment by vermiculus** [comment]
Looking at `bin/elsa`, is it really necessary to run the necessary code? It seems to only be a convenience wrapper around `elsa-run`.

**Comment by vermiculus** [comment]
Is `bin` actually necessary? `bin/elsa` seems to be a very thin wrapper around `elsa-run`.

**Comment by Fuco1** [comment]
@vermiculus There still needs to be some binary that will run the thing.  You can absolutely not run it in your "editing" instance of Emacs.

**Comment by vermiculus** [comment]
In other words, it must be a separate emacs process, yes? I'd be interested to learn how this limitation came to be, but I can leave that as an exercise to myself for a weekend :-) Your word is more than enough here.

If there was a way to kick off a subprocess from within emacs, that would accomplish the same goal, yes?

**Comment by Fuco1** [comment]
You need to have clean namespace for the symbols.  If we are analyzing something in a tainted environment it can not work properly (load paths, separation, repeatable results...).

Imagine you package.el update elsa and run analysis again from the same process but some data is saved in an old format.  A basic user will be completely lost.

**Comment by vermiculus** [comment]
Would an interactive command to start an emacs subprocess with the right arguments be an acceptable way to kick off the checks?

**Comment by Fuco1** [comment]
I save some results of the analysis on the interned symbols.  These persist for the whole session.  So it's not so much about migration than it is about consistency.  You can change the code and re-run the analysis and it can mix up old and new results in some weird ways and give wrong results.

I simply did not want to deal with this.  Running a new process is a super easy way to ensure everything is clean.

**Comment by vermiculus** [comment]
Thanks for the info :-) the first question stands, though

**Comment by Fuco1** [comment]
Yes, it would, but I don't find interactive ways to do testing very appealing.  I always run ert/buttercup from shell to be sure.  How would something like flycheck use an interactive command?  Elsa is a tool mostly ment to be used with something like that (=flycheck), not really "interactively" with yet another custom-made interface.

**Comment by vermiculus** [comment]
It may not be the most effective way to use Elsa, but it could be *a* way to use Elsa. I agree that creating a new ERT-like interface for it would be way too much work (unless the relevant code can be easily re-used), but some Emacs-based entry point would be prudent for something installable over ELPA -- even if that entry point is just `shell-command-to-string` or similar.

**Comment by purcell** [comment]
So what's the conclusion with this, @Fuco1 ? That the recipe makes sense, but only if we add the bin wrapper? Not sure how to proceed here.

**Comment by purcell** [comment]
(Closed accidentally, sorry.)

**Comment by Fuco1** [comment]
@purcell Yes to make it work with Cask which is my preferred method of how people use this we need that bin wrapper.

I don't know if I can push a fix to this branch.

**Comment by purcell** [comment]
Great, thanks folks.

**Pull request merged**
