### PR TITLE
added recipe for org-auto-tangle

### PR DESCRIPTION
**Pull request by yilkalargaw**
### Brief summary of what the package does

This package allows to tangle org files asynchronously by simply adding the option ```#+auto_tangle: t```. This is especially useful in literate emacs init and config files. You can simply use this package and the aforementioned org option to enable you to automatically tangle the file without blocking emacs (i.e. asynchronously).

### Direct link to the package repository

https://github.com/yilkalargaw/org-auto-tangle

### Your association with the package

I am a maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
I believe you need to add `async` to your `Package-Requires` line.  If I add that requirement:

### org-auto-tangle.el ###

byte-compile (using Emacs 27.1):
```
org-auto-tangle.el:100:1:Warning: the following functions are not known to be
    defined: org-auto-tangle-find-value, org-auto-tangle-async
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210111.341):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- org-auto-tangle.el#L88: `concat` may be unneeded; messages are already f-strings
- Prefer the default recipe or use `:defaults`, if possible.
  It seems to be equivalent: `(org-auto-tangle :repo "yilkalargaw/org-auto-tangle" :fetcher github)`
- GitHub API found `Other`
  - Try to use a standard format for your license file.
    See: https://github.com/licensee/licensee

**Comment by terlar** [comment]
Isn't it better to put this behind a minor mode to avoid having the hooks added unconditionally?

I had another version of this myself (unpublished) in case there is some useful functionality there (added support for tangle+byte compile):
https://github.com/terlar/emacs-config/blob/master/lisp/auto-tangle.el

**Comment by riscy** [comment]
I didn't take a close enough look to notice the add-hook, but yes that's right.

**Comment by yilkalargaw** [comment]
Thanks @riscy  & @terlar. I will put it behind a minor mode. 

But the warning are caused because the methods are defined dynamically. Declaring them in them globally solves the issue but I'm unsure that doing so is better.

**Comment by yilkalargaw** [comment]
I have moved the the it all into a minor mode as suggested by  @riscy & @terlar. I have also moved the two methods to the top level to remove the warnings. I am open to more suggestions.

**Comment by riscy** [comment]
> P.S. The license issue might just be caused by the fact that I am using an org file.

It could be that, or that you added your copyright to the license file.  Copyrights and licenses are separate entities, and it's a good idea to try to get common tooling to be able to detect what your license is without ambiguity.

Thanks very much for accommodating with the minor mode.   Some notes:

- org-auto-tangle.el#L84: Lighter should start with a space (this is also quite a large lighter, but I would guess many people hide/diminish their lighters anyway)
- Your mode should also _remove_ the hook after it's turned off
- The way the `add-hook` lines are nested makes me suspect that you're copyng the user's `after-save-hook` _into_ `org-mode-hook`
- Rather than adding an anonymous function into the user's hooks, you should add a named function so that when users inspect the list they can see where their hooks came from; adding lambdas into hooks is for when we're being lazy in our Emacs configs :)


Also checkdoc (using version 0.6.2):
```
Warning (emacs): 
org-auto-tangle.el:68: Argument `file' should appear (as FILE) in the doc string
```

**Comment by yilkalargaw** [comment]
@riscy based on your suggestions I have:

- added a space before the lighter and changed it to org-a-t
- I have moved the anonymous function inside the hook to a named function called ```org-auto-tangle-tangle-if-tag-exists```
- I have added a remove-hook statement for when the mode is turned off
- I have removed the nested hooks by moving the org-mode check to the function ```org-auto-tangle-tangle-if-tag-exists```
- I have corrected the issue with the doc string.

**Comment by yilkalargaw** [comment]
I have also corrected the license issues. It was the title header and the all rights reserved line.

**Comment by riscy** [comment]
I notice the `remove-hook` doesn't specify the local argument, but that should be specified too -- otherwise I think it's not removing the local hook.  Should be an easy merge after that!

**Comment by yilkalargaw** [comment]
I have just made the commit that  adds local argument to the remove-hook.

**Comment by riscy** [comment]
A couple more minor notes, but no blockers I see:

- purcell recently made me aware of a better way to delay the loading of org -- see https://github.com/melpa/melpa/pull/7403#issuecomment-773728860 --  I think we're far enough along that this isn't a blocker (and I vaguely remember somewhere deep in the Emacs Lisp manual where it says inlining a require is okay)
- `(re-search-forward "^#\\+auto_tangle: \\(.*\\)" nil :noerror)` will miss `#+auto_tangle:  t` (two spaces between auto and t), so perhaps the regular expression needs to be more general.  I see the regexp `"^\\([ \t]*\\)#\\+begin_src[ \t]+\\([^ \f\t\n\r\v]+\\)[ \t]*"` in `org-babel-src-block-regexp` for example; not a blocker, just fyi
- `(string= (buffer-local-value 'major-mode (current-buffer)) "org-mode")` could more concisely be `(eq major-mode 'org-mode)` -- casting to a string is not necessary in this case I believe
- org-auto-tangle.el#L88: It's safer to sharp-quote function names; use `#'`
- org-auto-tangle.el#L90: It's safer to sharp-quote function names; use `#'`

Thank you, and welcome to MELPA! :)

**Comment by yilkalargaw** [comment]
Thanks for all the help @riscy. I have integrated changes to accommodate the last three comments. I'll work on the first two.

**Pull request merged**
