### PR TITLE
Add recipe for emacs-async-await

### PR DESCRIPTION
**Pull request by chuntaro**
### Brief summary of what the package does

This is a simple implementation of Async/Await.  
Inspired by the Async/Await implementation of TypeScript.

This implementation uses generator.el included in Emacs 25.

### Direct link to the package repository

https://github.com/chuntaro/emacs-async-await

### Your association with the package

Author, maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Please don't define functions which does not start with package prefix for naming convention. `a/a--is-error` etc. And please don't use `/` separator for coding convention. 
- Is `await` global macro necessary ? Is it enough to use local macro by `macro-let` ?
- Please don't use melpa package version like `(promise "20170118.431")` and use package version for other package manager`(promise "1.0")`.

**Comment by chuntaro** [comment]
I modified it.

a/a-* -> async-await-*
(promise "20170118.431") -> (promise "1.0")

> Is await global macro necessary ? Is it enough to use local macro by macro-let ?

What I wanted to do was defmacro, which works only with the required file.
I do not know how to do it, so I commented out.

**Comment by purcell** [comment]
Thanks. More quick feedback:
- The package should probably not include `async-await-examples.el`. The best way to achieve this would be to place it in an `examples` subdirectory in your repo.
- Please remove `for Emacs` from the package description: it's redundant, because all elisp packages are for Emacs. :-)

**Comment by chuntaro** [comment]
I modified it.

- Move `async-await-examples.el` to `examples` subdirectory
- Remove `for Emacs`

**Comment by purcell** [comment]
Nice, thanks!

**Comment by chuntaro** [comment]
Thanks!

**Pull request merged**
