### PR TITLE
Add dw recipe

### PR DESCRIPTION
**Pull request by integral-dw**
### Brief summary of what the package does
Generate passphrases according to the diceware method.
Diceware is a simple method for generating passwords (_passphrases_), using dice for TRNG.
The setup is such that a passphrase of _N_ words is about as secure as a password of _2N_ random (printable) ASCII characters.
The package itself automates the process of looking up the words from a given wordlist, and combining them to a passphrase, meaning the package requires a wordlist file (sources linked in README and comments section of the source file) + 1 or more physical dice.

For more information regarding diceware, see the [homepage](http://world.std.com/~reinhold/diceware.html) (or ask me).
**Diceware** Ⓒ 1995-2020 Arnold G. Reinhold

### Direct link to the package repository
https://github.com/integral-dw/dw-passphase-generator

### Your association with the package
Creator & maintainer.

I am in no way affiliated with Arnold G. Reinhold.  I claim no ownership over the method itself.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] ~~I have confirmed some of these without doing them~~ ;)

### CODE REVIEW

**Comment by integral-dw** [comment]
Hi! I know the package still has a few warnings in the ol' README, but I am pretty happy with the package by now and willing to give it the version bump to **1.0.0** once someone else has scrutinized it.  There are still two minor features missing, but they should not affect the overall quality of the code.

**Comment by riscy** [comment]
Code looks good.

I am a complete cryptography rube, and part of a GPL license is "no warranty", but is there any published evidence that this is actually a good idea?  If you follow the instructions on the page, you'll get a password that's one in... 46,656 which would comprise a tiny fragment of a brute force password list.

Minor:
- thei -> their
- artithmetic. -> arithmetic
- bignumns -> bignums

**Comment by riscy** [comment]
Never mind, I can't count. :)

**Comment by riscy** [comment]
As one last comment, this will create passwords with "more e's" and "less x's" and (for example) "an" as a common substring, so there's probably a massive drop in entropy... maybe that's worth commenting on somewhere.  E.g. how long would a random alphanumeric password have to be to match a recommended-length diceware password?

**Comment by riscy** [comment]
Really there are no blockers on this one.  Thanks. :)

**Comment by integral-dw** [comment]
Fixed the typos, thanks!  Seems I keep overlooking some despite checkdoc.
Now, regarding your questions, I am far from an expert myself, but I will try to be accurate. 
> this will create passwords with "more e's" and "less x's" and (for example) "an" as a common substring, so there's probably a massive drop in entropy.

It is true that the per-character entropy suffers a bit due to the way characters are very unevenly distributed.  However, it is important to keep in mind that entropy is a logarithmic measure, for something to even make a dent into it, it must cut down the space of possibilities by _factors_ (of 2, 3, orders of magnitude..) for example, under ideal circumstances, the entropy of the latin alphabet would be `log2(26)` or ~4.7 bits.  The [diceware page](http://world.std.com/~reinhold/dicewarefaq.html) cites a work estimating the entropy of the English language to be roughly 1.3, [other works](https://www.princeton.edu/~wbialek/rome/refs/shannon_51.pdf) seem to estimate it between 1 and 2._something_.  

However, it's important to keep in mind that actual language makes sense, and has a couple of ubiquitous glue words (pronouns, particles, small verbs) massively influence the statistic.  So it's better to get a real world example: Taking a word list such as the [eff one](https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt), I get an entropy of 4.26 bits per character judging by relative occurrence of letters alone.  That means even if an attacker knew the exact composition of the words, (but not the words themselves), the passphrase would still be as hard to crack as a random character string of the same length drawn from a set of 19 characters with that approach.  

In other words, trying to brute-force a passphrase on a per-character level is essentially unfeasible for passphrases with more than a couple characters per word on average (this is why dw discards too short passphrases, it basically prunes a minuscule percentage of the possibility space to ensure character-based approaches are always less efficient than word-based ones).  This means that the attacker knowing the exact word list is a reasonable worst-case scenario, in which case each word is still about 12.9 bits of entropy.  This finally brings us to..

> how long would a random alphanumeric password have to be to match a recommended-length diceware password?

To quote the README:
>A password generated by picking a random sequence of printable ASCII characters has log2(95) or ≈6.6 “bits” of entropy per character. Likewise, a passphrase has 5*log2(6) or ≈12.9 bits of entropy per word, **meaning a six-word passphrase is about the same quality as a perfectly random string of 12 printable characters, a seven word passphrase is equivalent to 14.** The trade-off that arises is between having to type “fill 33rd chi drury behind chick fade” and having to remember “9W]OZ<D`zBnDpf”.

**Comment by riscy** [comment]
Wow, thanks very much for elucidating.

**Pull request merged**
