### PR TITLE
Link auto-highlight-symbol to my fork.

### PR DESCRIPTION
**Pull request by jcs090218**
I have post a comment, see https://github.com/melpa/melpa/pull/2086#issuecomment-691812380.

I don't think @gennad every concerned about this package. 😕 May I ask if I am able to maintain this package to my fork? Thanks!

**UPDATE:** @gennad has transferred the repo to me! Now the link is updated repo URL. 😄

### CODE REVIEW

**Comment by riscy** [comment]
Great, thank you for taking over!

If you're interested in doing some maintenance:

- auto-highlight-symbol.el:254:13:Warning: Package cl is deprecated
- checkdoc (of course!)

And these are ultimately very minor but sometimes shake out bugs:

- auto-highlight-symbol.el#L683: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L849: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L1434: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L1435: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L1437: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L1439: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L1126: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L1214: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L1245: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L1641: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L1134: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L1213: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L1247: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L263: It's safer to sharp-quote function names; use `#'`
- auto-highlight-symbol.el#L917: It's safer to sharp-quote function names; use `#'`

**Comment by jcs090218** [comment]
> auto-highlight-symbol.el:254:13:Warning: Package cl is deprecated

Yeah, I am trying to avoid using `cl` but it gives me error after I have changed to `cl-lib` instead of `cl`. 😕 I still don't know how to avoid it.

> And these are ultimately very minor but sometimes shake out bugs:

Will fix!

**Comment by purcell** [comment]
> Yeah, I am trying to avoid using `cl` but it gives me error after I have changed to `cl-lib` instead of `cl`. 😕 I still don't know how to avoid it.

Maybe share the error and I might have a suggestion?

**Comment by jcs090218** [comment]
I got this error.

```
Debugger entered--Lisp error: (void-function loop)
  (loop for x in face when (memq x facelist) return x)
  (if (listp face) (loop for x in face when (memq x facelist) return x) (memq face facelist))
  (let ((facelist (symbol-value faces))) (if (listp face) (loop for x in face when (memq x facelist) return x) (memq face facelist)))
  ahs-face-p(nil ahs-inhibit-face-list)
  (not (ahs-face-p (if ahs-face-check-include-overlay (append (ahs-get-overlay-face beg) (if (listp face) face (list face))) face) 'ahs-inhibit-face-list))
  (and symbol (not (ahs-dropdown-list-p)) (not (ahs-face-p (if ahs-face-check-include-overlay (append (ahs-get-overlay-face beg) (if (listp face) face (list face))) face) 'ahs-inhibit-face-list)) (not (ahs-symbol-p ahs-exclude symbol t)) (ahs-symbol-p ahs-include symbol))
  (if (and symbol (not (ahs-dropdown-list-p)) (not (ahs-face-p (if ahs-face-check-include-overlay (append (ahs-get-overlay-face beg) (if (listp face) face (list face))) face) 'ahs-inhibit-face-list)) (not (ahs-symbol-p ahs-exclude symbol t)) (ahs-symbol-p ahs-include symbol)) (progn (list symbol beg end)))
  (let* ((bounds (bounds-of-thing-at-point 'symbol)) (beg (car bounds)) (end (cdr bounds)) (face (if bounds (progn (get-text-property beg 'face)))) (symbol (if bounds (progn (buffer-substring beg end))))) (if (and symbol (not (ahs-dropdown-list-p)) (not (ahs-face-p (if ahs-face-check-include-overlay (append (ahs-get-overlay-face beg) (if ... face ...)) face) 'ahs-inhibit-face-list)) (not (ahs-symbol-p ahs-exclude symbol t)) (ahs-symbol-p ahs-include symbol)) (progn (list symbol beg end))))
  ahs-highlight-p()
  (let ((hl (ahs-highlight-p))) (if hl (progn (ahs-highlight (nth 0 hl) (nth 1 hl) (nth 2 hl)))))
  (progn (let ((hl (ahs-highlight-p))) (if hl (progn (ahs-highlight (nth 0 hl) (nth 1 hl) (nth 2 hl))))))
  (if (and auto-highlight-symbol-mode (not ahs-highlighted)) (progn (let ((hl (ahs-highlight-p))) (if hl (progn (ahs-highlight (nth 0 hl) (nth 1 hl) (nth 2 hl)))))))
  ahs-idle-function()
  apply(ahs-idle-function nil)
  timer-event-handler([t 0 0 299999 t ahs-idle-function nil idle 999999])
```

Is weird the something was working but it doesn't work after switching to `cl-lib`. 😕

**Comment by purcell** [comment]
Well `loop` is from `cl`. `(require 'cl-lib)` should work fine, as long as you use `cl-loop` instead of `loop`.

**Comment by jcs090218** [comment]
Okay, I now know the differences between `cl` and `cl-lib`. I thought `cl-lib` would be fully compatible to `cl`.

**Pull request merged**
