### PR TITLE
Add recipe for Corsair

### PR DESCRIPTION
**Pull request by rob137**
### Brief summary of what the package does

**Corsair** is an Emacs package that helps gather text to populate LLM prompts for [GPTel](https://github.com/karthink/gptel).

### Direct link to the package repository

https://github.com/rob137/Corsair

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed.**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

⸺ `corsair.el` with package-lint 20240923.1044:
```
1 issue found:
1:0: error: package.el cannot parse this buffer: Package lacks a file header
```
This should read:
```elisp
;;; corsair.el --- Text accumulation enhancements for GPTel -*- lexical binding: t; -*-
```

⸺ `corsair.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- corsair.el#L62: `concat` may be unneeded; `insert` can take multiple arguments
- corsair.el#L73: `concat` may be unneeded; `insert` can take multiple arguments
- corsair.el#L84: `concat` may be unneeded; `insert` can take multiple arguments
```

Stderr output while compiling/loading:
```
Malformed mode-line: "lexical binding: t;" in buffer "corsair.el"
Malformed mode-line: "lexical binding: t;" in buffer "corsair.el"
```
This should be `lexical-binding: t;` (hyphenated)

⸺ Package and license:
- Prefer equivalent recipe: `(corsair :repo "rob137/corsair" :fetcher github)`

**Comment by tarsius** [comment]
@riscy If I remember correctly, you agreed with my reasoning that the `:fetcher` is the "type" of the package and that it is therefore preferable if that comes. I.e., recommend this instead:

```
(corsair :fetcher github :repo "rob137/corsair")
```

**Comment by riscy** [comment]
Yes, that sounds right - I'll fix this now.

**Comment by riscy** [comment]
Thanks @rob137 - a couple more bits of feedback, non-blocking I think:

You use a combination of `error` and `message` for error feedback, e.g. `(error "No project found")` and `(message "No region selected")`, but in all cases what I think you want is `user-error` rather than a stacktrace-opening `error`.

This is also a very minor and somewhat related "tip", where you can decrease the overall indentation of your functions by dealing with the execution-ending branch of an `if` first.  E.g. instead of:
```
(defun corsair-accumulate-file-name ()
  "Append file name to the GPTel chat buffer."
  (interactive)
  (if buffer-file-name
      (let ((name (file-name-nondirectory buffer-file-name)))
        (with-current-buffer (get-buffer-create corsair-chat-buffer-name)
          (goto-char (point-max))
          (insert "\n" name "\n")
          (message "File name accumulated to GPTel chat buffer.")))
    (message "No file associated with this buffer.")))
```
You can write:
```
(defun corsair-accumulate-file-name ()
  "Append file name to the GPTel chat buffer."
  (interactive)
  (if (not buffer-file-name)
      (message "No file associated with this buffer.")
    (let ((name (file-name-nondirectory buffer-file-name)))
      (with-current-buffer (get-buffer-create corsair-chat-buffer-name)
        (goto-char (point-max))
        (insert "\n" name "\n")
        (message "File name accumulated to GPTel chat buffer.")))))
```
leading to less indentation overall, or what I would personally do:
```elisp
(defun corsair-accumulate-file-name ()
  "Append file name to the GPTel chat buffer."
  (interactive)
  (unless buffer-file-name (user-error "No file associated with this buffer."))
  (let ((name (file-name-nondirectory buffer-file-name)))
    (with-current-buffer (get-buffer-create corsair-chat-buffer-name)
      (goto-char (point-max))
      (insert "\n" name "\n")))
  (message "File name accumulated to GPTel chat buffer."))
```
I also think the prolific debug messages like `(message "File name accumulated to GPTel chat buffer.")` are not that useful to users, and I'd personally omit them, but ymmv.

Finally, your`Suggested Key bindings` which currently appear at the *bottom* of your file, would be even better placed at the *top* of your file, in your `;;; Commentary`.  It's not easy for someone to understand precisely what your package offers at a glance, but if you show the keybindings in your `;;; Commentary` I think it's much more obvious.

**Comment by tarsius** [comment]
FWIW, I might write

```elisp
(defun corsair-accumulate-file-name ()
  "Append file name to the GPTel chat buffer."
  (interactive)
  (cond
   (buffer-file-name
    (let ((name (file-name-nondirectory buffer-file-name)))
      (with-current-buffer (get-buffer-create corsair-chat-buffer-name)
        (goto-char (point-max))
        (insert "\n" name "\n")
        (message "File name accumulated to GPTel chat buffer"))))
   ((message "No file associated with this buffer"))))
```

But I have used all of these approaches and don't think there's a clear winner. (I'm not a fan of writing the complete `(unless COND BODY...)` on one line, even though I sometimes do that too.

Also note that I removed the periods at the end of the messages, as it is customarily done.

**Comment by rob137** [comment]
Many thanks all!

**Pull request merged**
