### PR TITLE
Add nerdtab package

### PR DESCRIPTION
**Pull request by casouri**
### Brief summary of what the package does

This package provides keyboard-oriented tabs for Emacs.

Kind of like [winum](https://github.com/deb0ch/emacs-winum), but for buffers.

### Direct link to the package repository

https://github.com/casouri/nerdtab

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for the submission and your patience! Quick feedback:

- If you're going to `:inherit` a default face like `'highlight`, don't override attributes, e.g. [here](https://github.com/casouri/nerdtab/blob/dba3c83b4ce6c1de84ef7ebe4ce144a009c61e68/nerdtab.el#L118) - what if a user's `highlight` face is simply underlined? :-) Just stick with `:inherit`.
- Delete your commented-out code - that's what git is for!
- Consider adding an `;;;###autoload` for `nerdtab-mode`.

Looks good otherwise.

**Comment by casouri** [comment]
Thanks :smile:

In the last few commits I have:
* removed commented-out codes
* removed modifications from three inherit faces
* added autoload comment to two minor modes
* added a convenience command

**Comment by purcell** [comment]
Great - merged, thanks! Welcome to MELPA. :tada:

**Comment by casouri** [comment]
Thanks! I’m so exited :smile:

**Pull request merged**
