### PR TITLE
Add php-scratch recipe

### PR DESCRIPTION
**Pull request by mallt**
- php-scratch is a scratch buffer to interactively evaluate php code
- repository url: https://github.com/mallt/php-scratch
- I am the author of the package

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- You're going to need to declare package dependencies for `s` and `php-mode`. -
- Since you're using `user-error`, you'll need to depend on Emacs 24.4 (I think). 
- `local-set-key` is usually a warning sign. Why not define a derived mode of php-mode so that you have a proper key map to modify?

Hope that helps!

**Comment by Fanael** [comment]
> Since you're using `user-error`, you'll need to depend on Emacs 24.4 (I think).

Emacs 24.3.

**Comment by purcell** [comment]
> Emacs 24.3.

Thanks, wasn't sure offhand!

**Comment by Fanael** [comment]
As I said before, `C-h n` is your friend in this sort of situations.

**Comment by mallt** [comment]
Thanks a lot for the feedback! 
I've added the package dependencies and moved the keybindings to a derived mode.

**Comment by purcell** [comment]
Nice! Thanks.

**Pull request merged**
