### PR TITLE
Recipe: current-word-highlight-mode

### PR DESCRIPTION
**Pull request by kijimaD**
### Brief summary of what the package does

Highlight current word minor mode.

### Direct link to the package repository

https://github.com/kijimaD/current-word-highlight-mode

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- I like the animated demos.

I may be lacking context but I'm having trouble imagining where this would be used instead of symbol highlighting (or maybe symbol highlighting just with a [stricter syntax table](https://www.gnu.org/software/emacs/manual/html_node/eintr/Syntax.html)).

I also think we should carefully consider having multiple different packages which separately handle the highlighting of different kinds of "thing"s.  One could imagine this getting out of hand with separate packages to highlight words, symbols, sentences, lists, etc.  Do you see any possibility of adding this as a feature to an existing package like `auto-highlight-symbol`?

**Comment by purcell** [comment]
Yes, there are similar packages, e.g. symbol-overlay, but I guess this does something a little different in that it is made to co-exist with those others. So I'm 50/50 on adding it to MELPA.

Some specific notes about the code:

- Toggling mode off doesn't stop the timer
- Looks like the built-in `(bounds-of-thing-at-point 'word)` could be used to simplify the code a bit
- Custom group lists itself as its own parent
- Globalized mode is declared before the local mode: should be the other way around
- Instead of a dummy declaration for `current-word-highlight-mode`, just declare things in the right order
- `:extend` built-in faces by default instead of unconditionally choosing colours that may or may not look good depending on the user's current theme. At the very least, declare variants for light and dark modes.
- Consider removing `-mode` from the package name. It is already very long, and generally you don't need `-mode` in the name unless it's a major mode.

**Comment by kijimaD** [comment]
Thank you for your thoughtful answer. I am very happy.

 I'm not a native English speaker, so please forgive me if I'm late in replying and the content is a bit unnatural.
First of all, I would like to tell you why I decided to make this package.

- **Inconvenience I felt**: It's hard to know what is a word. `this_word` is one word, `word1-word2` are two words. Also, in languages that don't have separators, such as Japanese, it is more difficult to foresee words. So, it is hard to move word.
- **First thing I tried**: I tried a package that highlights words.
- **The problem**: I am already using the symbol highlighting package, and highlighting the **whole** word further clutters the screen.
- **To solve**: I decided I needed a package that highlights **only** the word around the cursor, as opposed to a package that highlights the **whole** area words.

What I intended by not having an existing package was to highlight **only the word around the cursor**. Similar highlighting packages can highlight the entire screen word, but did not seem to highlight only around the cursor. Also, I thought it would be best not to add this similar but different feature to an existing package.

I already use `auto-highlight-symbol` to highlight the entire text with a symbol, and I felt that highlighting the word further would be too much to display and difficult to read. Other similar packages seemed to have only the whole thing, and as Purcell said, this is meant to be used alongside packages that highlight the whole thing.

Thank you for your time.

**Comment by riscy** [comment]
I'm more inclined to add this to MELPA given the above justification (I didn't have the Japanese language context, but I did notice it in the screenshots on my first time looking at this), and the rationale sounds heartfelt.  Thanks, @kijimaD, your reply was clear. :)

I think of @purcell's suggestions, these remain to be addressed:
- Toggling mode off doesn't stop the timer
- :extend built-in faces by default instead of unconditionally choosing colours that may or may not look good depending on the user's current theme. At the very least, declare variants for light and dark modes.

**Comment by kijimaD** [comment]
@riscy 
Thank you😄 I didn't explain the reason well enough when I made the pull request. I'm so glad you understand!

> I think of @purcell's suggestions, these remain to be addressed:

> Toggling mode off doesn't stop the timer
:extend built-in faces by default instead of unconditionally choosing colours that may or may not look good depending on the user's current theme. At the very least, declare variants for light and dark modes.

You're right.

Due to my lack of knowledge💧, it has taken some time to fix these two issues.
Today, I fixed the timer issue and committed it! <a href="https://github.com/kijimaD/current-word-highlight/commit/e1fbac45e185f053211e125213f0fc28d9303550">e1fbac4</a>

The rest, fixing the face issues, will take some more time... Please wait a little longer!

**Comment by kijimaD** [comment]
I've fixed the faces problem! <a href="https://github.com/kijimaD/current-word-highlight/commit/bb1891d0b1bb6b4832e0dc4e4dc1f10b61dc621a">bb1891d</a>
If this looks good, then all the fixes are done!

**Comment by riscy** [comment]
Okay, look good.  I will merge this then.  Thanks for adding this, and welcome to MELPA. :)

**Pull request merged**
