### PR TITLE
Add recipe for wal-mode

### PR DESCRIPTION
**Pull request by LucasKl**
### Brief summary of what the package does
A [major mode](https://github.com/LucasKl/wal-major-mode) for the [Waveform Analysis Language](https://github.com/ics-jku/wal). Adds syntax highlighting and comint based evaluation of WAL expressions.

### Direct link to the package repository

https://github.com/LucasKl/wal-major-mode

### Your association with the package
I am the maintainer.

### Relevant communications with the upstream package maintainer
None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Very quick first pass --

`wal.el` with byte-compile using Emacs 27.1:
```
wal.el:59:7:Warning: assignment to free variable `wal-op-arithmetic'
wal.el:60:7:Warning: assignment to free variable `wal-op-logical'
wal.el:61:7:Warning: assignment to free variable `wal-op-keywords'
wal.el:65:7:Warning: assignment to free variable `wal-op-control-flow'
wal.el:66:7:Warning: assignment to free variable `wal-op-special'
wal.el:69:39:Warning: reference to free variable `wal-op-keywords'
wal.el:69:7:Warning: assignment to free variable `wal-keywords-regexp'
wal.el:70:41:Warning: reference to free variable `wal-op-arithmetic'
wal.el:70:7:Warning: assignment to free variable `wal-arithmetic-regexp'
wal.el:71:38:Warning: reference to free variable `wal-op-logical'
wal.el:71:7:Warning: assignment to free variable `wal-logical-regexp'
wal.el:72:43:Warning: reference to free variable `wal-op-control-flow'
wal.el:72:7:Warning: assignment to free variable `wal-control-flow-regexp'
wal.el:73:38:Warning: reference to free variable `wal-op-special'
wal.el:73:7:Warning: assignment to free variable `wal-special-regexp'
wal.el:78:11:Warning: reference to free variable `wal-keywords-regexp'
wal.el:79:11:Warning: reference to free variable `wal-arithmetic-regexp'
wal.el:80:11:Warning: reference to free variable `wal-logical-regexp'
wal.el:81:11:Warning: reference to free variable `wal-control-flow-regexp'
wal.el:82:11:Warning: reference to free variable `wal-special-regexp'
wal.el:75:7:Warning: assignment to free variable `wal-highlights'
wal.el:98:7:Warning: assignment to free variable `wal-keywords'
In wal-complete-symbol:
wal.el:134:35:Warning: reference to free variable `wal-keywords'
In wal-eval-sexpr-behind:
wal.el:142:9:Warning: assignment to free variable `end'
wal.el:144:9:Warning: assignment to free variable `start'
wal.el:145:14:Warning: reference to free variable `end'
wal.el:146:82:Warning: reference to free variable `start'
wal.el:147:19:Warning: assignment to free variable `sexpr'
wal.el:147:4:Warning: reference to free variable `sexpr'
In wal-eval-sexpr-forward:
wal.el:152:9:Warning: assignment to free variable `start'
wal.el:154:9:Warning: assignment to free variable `end'
wal.el:155:14:Warning: reference to free variable `start'
wal.el:156:88:Warning: reference to free variable `end'
wal.el:157:19:Warning: assignment to free variable `sexpr'
wal.el:157:4:Warning: reference to free variable `sexpr'
In wal-eval-buffer:
wal.el:164:30:Warning: assignment to free variable `buffer-content'
wal.el:164:30:Warning: reference to free variable `buffer-content'
wal.el:166:9:Warning: assignment to free variable `sexpr'
wal.el:166:54:Warning: reference to free variable `sexpr'
wal.el:197:42:Warning: reference to free variable `comint-mode-map'
In wal-repl-initialize:
wal.el:205:9:Warning: assignment to free variable `comint-process-echoes'
wal.el:206:9:Warning: assignment to free variable `comint-use-prompt-regexp'
In run-wal:
wal.el:212:39:Warning: assignment to free variable `wal-repl-buffer'
wal.el:212:11:Warning: reference to free variable `wal-repl-buffer'
In wal-repl-mode:
wal.el:222:9:Warning: assignment to free variable `comint-prompt-regexp'
wal.el:225:9:Warning: assignment to free variable `comint-prompt-read-only'
In end of data:
wal.el:235:1:Warning: the following functions are not known to be defined:
    comint-send-string, comint-send-input, comint-mode
```

`wal.el` with package-lint 20220213.1457:
```
2 issues found:
185:3: error: You should depend on (emacs "25.1") if you need `font-lock-ensure'.
208:0: error: "run-wal" doesn't start with package's prefix "wal".
```

`wal.el` with [melpazoid](https://github.com/riscy/melpazoid):
- wal.el#L212: It's safer to sharp-quote function names; use `#'`
- wal.el#L228: Single-line comments should usually begin with `;;`
- wal.el#L231: Loading a package should rarely add hooks; can you run this function directly when the mode is activated?

**Comment by LucasKl** [comment]
Hi! Thanks for the comments.
Sorry for those warnings. I had to run Emacs without my init to reproduce them.
All comments should be fixed now.

**Comment by riscy** [comment]
Thank you!  One more quick scan --

`wal.el` with byte-compile using Emacs 27.1:
```
wal.el:202:42:Warning: reference to free variable `comint-mode-map'
In wal-repl-initialize:
wal.el:210:9:Warning: assignment to free variable `comint-process-echoes'
wal.el:211:9:Warning: assignment to free variable `comint-use-prompt-regexp'
In wal-repl-mode:
wal.el:228:9:Warning: assignment to free variable `comint-prompt-regexp'
wal.el:231:9:Warning: assignment to free variable `comint-prompt-read-only'
In end of data:
wal.el:239:1:Warning: the following functions are not known to be defined:
    comint-send-string, comint-send-input, comint-mode
```
I think these are an easy fix, simply requiring a `(require 'comint)`.

**Comment by LucasKl** [comment]
Thanks, should be done.
I'm sorry again I don't get these errors when byte-compiling. Am I missing some flag or something like that?

**Comment by riscy** [comment]
Most likely you're not seeing all of the compilation warnings because you're compiling your code in an instance of Emacs that has already loaded the code, or some past version of it at least.  Using `flycheck` helps with this, or you can restart emacs using `emacs -Q` and try compiling from there to get those.  In any case the checklist is behind us now. :)

Altogether the code looks good, but I see this is implementing a major mode for a specific language.  The convention in cases like these is to name the package (and the recipe) `wal-mode` rather than just `wal` (but don't worry, your prefix namespace would continue to be `wal-`).

**Comment by LucasKl** [comment]
Thank you very much for taking the time to help me out with this. I really appreciate it!
I renamed wal.el to wal-mode.el and updated all references to it as well as the recipe.

**Comment by riscy** [comment]
Sorry for the pain in the back, there's one more change that needs to go through --

`wal-mode.el` with checkdoc 0.6.2:
```
wal-mode.el:239: The footer should be: (provide 'wal-mode)\n;;; wal-mode.el ends here
```

**Comment by LucasKl** [comment]
I fixed the required change. Thanks for you patience.

**Comment by riscy** [comment]
Thank you!  Looks great now.

**Comment by LucasKl** [comment]
Awesome! Thank you very much!

**Pull request merged**
