### PR TITLE
Add recipe for org-anki

### PR DESCRIPTION
**Pull request by eyeinsky**
### Brief summary of what the package does

Synchronize org entries to Anki.

### Direct link to the package repository

https://github.com/eyeinsky/org-anki

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

EDIT: i've now successfully built and installed the package with no errors.

### CODE REVIEW

**Comment by alphapapa** [comment]
> I installed the package with just `eval-buffer` because nixos's emacs package folder is read-only, so `package-install-file` couldn't save the file.

You need to test installation of the package before submitting.  You should test it in a clean Emacs configuration.  The MELPA instructions explain how to do that using its Makefile.  You could also use https://github.com/alphapapa/emacs-sandbox.sh

**Comment by eyeinsky** [comment]
@alphapapa I've now successfully installed it (via `package-install-file`) with no issues!

**Comment by riscy** [comment]
Have you had a chance to compare to https://melpa.org/#/anki-editor ?

Otherwise here's a quick first pass -

package-lint 20200906.512:
```
1 issue found:
142:3: error: You should depend on (emacs "24.4") if you need `org-export-string-as'.
```

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by eyeinsky** [comment]
@riscy Thank you for reviewing this!

> Have you had a chance to compare to https://melpa.org/#/anki-editor ?

The big difference is that anki-editor requires to change the outline (heading structure) to make cards while I just use a heading as the card's frontside and content as card's backside. This is important to those who just want to ankify their notes without changing them. But otherwise they are similar yes as they both sync org content to Anki. (I mention this under the [Why](https://github.com/eyeinsky/org-anki#why) section too.)

> Otherwise here's a quick first pass -
> 
> package-lint 20200906.512:
> 
> ```
> 1 issue found:
> 142:3: error: You should depend on (emacs "24.4") if you need `org-export-string-as'.
> ```

Since I'm not using this function directly then I wonder if it's [ox-slimhtml](https://melpa.org/#/ox-slimhtml) which should depend on version 24.4? (It now depends on just version 24)

>     * Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
>       See: https://github.com/licensee/licensee

Done!

**Comment by riscy** [comment]
> Since I'm not using this function directly

I think it's here on line 142:
```elisp
(defun org-anki--string-to-html (string)
  "Convert STRING (org element heading or content) to html."
  (org-export-string-as string 'slimhtml t nil))
```

**Comment by eyeinsky** [comment]
Ah, sorry -- I'm completely blind! I've fixed it now.

**Comment by riscy** [comment]
Looks good to go. :)

**Pull request merged**
