### PR TITLE
Add recipe for evil-textobj-treesitter

### PR DESCRIPTION
**Pull request by meain**
### Brief summary of what the package does

Create [`evil`](https://github.com/emacs-evil/evil) text-objects using [`tree-sitter`](https://github.com/emacs-tree-sitter/elisp-tree-sitter) grammar.

### Direct link to the package repository

https://github.com/meain/evil-textobj-treesitter

### Your association with the package

I am the the author and maintainer of the package

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- very quick first pass:

checkdoc (using version 0.6.2):
```
Warning (emacs): 
evil-textobj-treesitter.el:140: All variables and subroutines might as well have a documentation string
```

- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to evil-textobj-treesitter.el

**Comment by meain** [comment]
Thanks @riscy , missed the docstring when I moved around some code.

I have added the docstring in https://github.com/meain/evil-textobj-treesitter/commit/3c17eb1720604fd173fdf87df88bb6ff916488b9 and SPDX-License-Identifier in https://github.com/meain/evil-textobj-treesitter/commit/6f58d86ad946101adedec7abe1d702c16c179427

**Comment by riscy** [comment]
Thanks!  As an addendum but not a blocker, I notice your supporting code (from the `queries` subdir) would also benefit from license boilerplate, or some indication that it comes from https://github.com/nvim-treesitter/nvim-treesitter-textobjects/tree/master/queries.  Also caught a couple small typos in docstrings (closeset, vaild, insdie) but this looks good to merge.

And, welcome to MELPA. :)

**Comment by meain** [comment]
I'll be sure to take care of those things. Also, thanks for the welcome :)

**Pull request merged**
