### PR TITLE
Add recipe for vc-ign

### PR DESCRIPTION
**Pull request by wolfmanx**
### Brief summary of what the package does

ignore file administration in VC

Mark multiple files in vc-dir-mode or dired-mode an create/remove properly escaped and anchored entries in/from appropriate ignore files. Edit arbitrary patterns for an ignore file based on escaped file name.

### Direct link to the package repository

https://github.com/wolfmanx/vc-ign

### Your association with the package

Maintainer, Developer

### Relevant communications with the upstream package maintainer

None needed*

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings

```diff
1 file changed, 4 insertions(+)
Cask | 4 ++++

new file   Cask
@@ -0,0 +1,4 @@
+(source gnu)
+(source melpa)
+
+(package-file "vc-ign.el")
```
```
$ cask; cask build
Loading package information... done
Package operations: 1 installs, 0 removals
  - Installing [ 1/1] emacs (24)... already present
Compiling /home/conao/dev/forks/vc-ign/vc-ign.el...

In vc-default-ign-get-ignore-file-and-pattern:
vc-ign.el:384:28:Warning: reference to free variable ‘vc-ign-ignore-param-none’
vc-ign.el:815:25:Warning: reference to free variable ‘vc-dir-menu-map’

In end of data:
vc-ign.el:872:1:Warning: the following functions are not known to be defined:                                                                      
    vc-dired-deduce-fileset, dired-map-over-marks, dired-get-filename,
    vc-ign-delete-if, vc-ign--read-lines, vc-svn-command, vc-dir-current-file,                                                                     
    dired-get-marked-files, vc-deduce-fileset, dired-make-relative,
    dired-mark-pop-up, dired-mark-prompt, vc-dir-resynch-file,
    vc-dir-move-to-goal-column, vc-bzr-root, vc-git-root, vc-hg-root, vc-mtn-root
Compiling /home/conao/dev/forks/vc-ign/vc-repair.el...

In toplevel form:
vc-repair.el:73:10:Warning: reference to free variable ‘vc-ewoc’
vc-repair.el:189:10:Warning: reference to free variable ‘vc-git-log-output-coding-system’
vc-repair.el:191:10:Warning: reference to free variable ‘vc-git-commits-coding-system’
vc-repair.el:202:46:Warning: reference to free variable ‘vc-git-program’
vc-repair.el:304:39:Warning: reference to free variable ‘vc-src-program’
vc-repair.el:355:12:Warning: reference to free variable ‘vc-src-command-safe’                                                                      
vc-repair.el:388:15:Warning: reference to free variable ‘vc-src-log-switches’                                                                      

In end of data:
vc-repair.el:446:1:Warning: the following functions are not known to be
    defined: ewoc-map, vc-dir-fileinfo->directory, vc-dir-fileinfo->marked,                                                                        
    vc-dir-fileinfo->name, (setf vc-dir-fileinfo->marked), ewoc-locate,
    ewoc-data, ewoc-next, ewoc-invalidate, vc-dir-fileinfo->state, ewoc-nth,                                                                       
    vc-dir-mark-file, vc-svn-command, vc-hg-command, vc-run-delayed,
    vc-hg-after-dir-status, vc-ign-file-name-directory,
    vc-ign-file-relative-name, vc-src--parse-state, vc-src-dir-status-files,                                                                       
    vc-src-command-raw, vc-src-command-iterator, vc-setup-buffer
```

```
 vc-ign.el    76   1 error           "string-match-p" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.el    77     warning         Argument ‘regexp’ should appear (as REGEXP) in the doc string (emacs-lisp-checkdoc)
 vc-ign.el    86     warning         All variables and subroutines might as well have a documentation string (emacs-lisp-checkdoc)
 vc-ign.el    90   7 error           Aliases should start with the package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.el    91   5 error           Aliases should start with the package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…    94   1 error           "bindings--define-key" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   118   1 error           "vc-deduce-fileset" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   120     warning         All variables and subroutines might as well have a documentation string (emacs-lisp-checkdoc)
 vc-ign.…   124   1 error           "vc-dired-deduce-fileset" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   125     warning         All variables and subroutines might as well have a documentation string (emacs-lisp-checkdoc)
 vc-ign.…   129     warning         All variables and subroutines might as well have a documentation string (emacs-lisp-checkdoc)
 vc-ign.…   129   1 error           "vc-dir-resynch-file" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   131   1 error           "vc-default-ign-ignore-completion-table" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   141   1 error           "vc-default-ign-find-ignore-file" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   179   1 error           "vc-svn-ign-ignore-completion-table" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   355   1 error           "vc-default-ign-ignore" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   356     warning         You should convert this comment to documentation (emacs-lisp-checkdoc)
 vc-ign.…   361   1 error           "vc-default-ign-get-ignore-file-and-pattern" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   384  28 warning         reference to free variable ‘vc-ign-ignore-param-none’ (emacs-lisp)
 vc-ign.…   417   1 error           "vc-default-ign-modify-ignore-specs" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   494     warning         You should convert this comment to documentation (emacs-lisp-checkdoc)
 vc-ign.…   534   1 error           "vc-default-ign-ignore-param" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   591   1 error           "vc-cvs-ign-find-ignore-file" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   594   1 error           Aliases should start with the package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   596   1 error           "vc-cvs-ign-ignore-param-glob" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   600   1 error           "vc-cvs-ign-ignore-param" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   604   1 error           "vc-cvs-ign-glob-escape" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   617   1 error           "vc-svn-ign-find-ignore-file" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   620   1 error           Aliases should start with the package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   622   1 error           "vc-svn-ign-ignore-param-glob" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   626   1 error           "vc-svn-ign-ignore-param" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   630   1 error           "vc-svn-ign-modify-ignore-specs" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   631     warning         You should convert this comment to documentation (emacs-lisp-checkdoc)
 vc-ign.…   650   1 error           "vc-src-ign-find-ignore-file" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   653   1 error           Aliases should start with the package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   655   1 error           "vc-src-ign-glob-escape" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   669   1 error           "vc-src-ign-ignore-param-glob" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   673   1 error           "vc-src-ign-ignore-param" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   687   1 error           "vc-bzr-ign-find-ignore-file" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   691   1 error           Aliases should start with the package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   693   1 error           "vc-bzr-ign-ignore-param-regexp" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   697   1 error           "vc-bzr-ign-ignore-param" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   711   1 error           "vc-git-ign-find-ignore-file" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   715   1 error           Aliases should start with the package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   717   1 error           "vc-git-ign-ignore-param" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   731   1 error           "vc-hg-ign-find-ignore-file" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   735   1 error           Aliases should start with the package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   737   1 error           "vc-hg-ign-ignore-param-regexp" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   741   1 error           "vc-hg-ign-ignore-param-glob" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   745   1 error           "vc-hg-ign-ignore-param" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   771   1 error           "vc-mtn-ign-find-ignore-file" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   774   1 error           Aliases should start with the package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   776   1 error           "vc-mtn-ign-ignore-param-regexp" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   780   1 error           "vc-mtn-ign-ignore-param" doesn't start with package's prefix "vc-ign". (emacs-lisp-package)
 vc-ign.…   815  25 warning         reference to free variable ‘vc-dir-menu-map’ (emacs-lisp)
 vc-ign.…   872   1 warning         the following functions are not known to be defined: vc-dired-deduce-fileset, dired-map-over-marks, dired-get-filename, vc-ign-delete-if, vc-ign--read-lines, vc-svn-command, vc-dir-current-file, dired-get-marked-files, vc-deduce-fileset, dired-make-relative, dired-mark-pop-up, dired-mark-prompt, vc-dir-resynch-file, vc-dir-move-to-goal-column, vc-bzr-root, vc-git-root, vc-hg-root, vc-mtn-root (emacs-lisp)
```

**Comment by wolfmanx** [comment]
@conao3 Thanks for the hint about Cask. I have split the package and removed unrelated Emacs Lisp files. All of Cask, package-lint, flymake, checkdoc pass now.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by wolfmanx** [comment]
> Friendly ping!

Sorry, I was too busy for a while. I'll work on it on the weekend.

**Comment by riscy** [comment]
I'll mark this awaiting upstream, but please ping when it's ready for another look!

**Comment by tarsius** [comment]
Soooo... it has been a year.

I am closing this now but once you are ready you can simply ask for us to reopen this.

**Pull request closed without merging**
