### PR TITLE
Add consult-git-log-grep recipe

### PR DESCRIPTION
**Pull request by ghosty141**
### Brief summary of what the package does

consult interface to git log --grep

### Direct link to the package repository

https://github.com/ghosty141/consult-git-log-grep

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.   Quick first pass --

`consult-git-log-grep.el` with byte-compile using Emacs 28.1:
```
consult-git-log-grep.el:118:49: Warning: `(truncate-string-to-width (cdr
    (assoc 'sha metadata)) 8)' is a malformed function
consult-git-log-grep.el:118:49: Warning: `(cdr (assoc 'datetime metadata))' is
    a malformed function
consult-git-log-grep.el:118:49: Warning: `(cdr (assoc 'author metadata))' is a
    malformed function
consult-git-log-grep.el:118:49: Warning: `(truncate-string-to-width (cdr
    (assoc 'sha metadata)) 8)' is a malformed function
consult-git-log-grep.el:118:49: Warning: `(cdr (assoc 'datetime metadata))' is
    a malformed function
consult-git-log-grep.el:118:49: Warning: `(cdr (assoc 'author metadata))' is a
    malformed function
consult-git-log-grep.el:126:17: Warning: reference to free variable
    `marginalia-annotator-registry'
consult-git-log-grep.el:126:17: Warning: assignment to free variable
    `marginalia-annotator-registry'
In end of data:
consult-git-log-grep.el:120:8: Warning: the function `marginalia--fields' is
    not known to be defined.
consult-git-log-grep.el:84:14: Warning: the function `string-blank-p' might
    not be defined at runtime.
```

**Comment by ghosty141** [comment]
These come frmo relying on the marginalia package if it exists. This package can be used standalone just if the dependency "consult" is satisfied. If the user has the "marginalia" package installed, certain goodies are added like showing the author name or datetime on the side. [See the code here](https://github.com/ghosty141/consult-git-log-grep/blob/4195aa52794920a4fc17d0c7a960d68102a2f178/consult-git-log-grep.el#L117)

This is the same way consult-spotify does this: [See here][https://codeberg.org/jao/espotify/src/commit/ea6d6021e5acc550560325db2f09198839ee702f/consult-spotify.el#L113) which has been accepted. The code byte-compiles cleanly if marginalia is present since the marginalia--field macro does it's magic.

Any ideas how to make it compile cleanly for users without the marginalia package? I'd be happy to handle this differently if there is a way.

**Comment by minad** [comment]
My recommendation is to avoid using Marginalia here. Marginalia is meant to extend existing commands, which you do not control. It is not meant to be used by packages. I just pointed this out to @Nyoho in #8268 (https://github.com/Nyoho/consult-hatena-bookmark/issues/4#issuecomment-1311665250). See also the note in https://github.com/minad/marginalia#adding-custom-annotators-or-classifiers.

**Comment by ghosty141** [comment]
Ah yeah I see. Thanks for the advice, I'll get to fixing it.

**Comment by ghosty141** [comment]
I've commited [0abdc860](https://github.com/ghosty141/consult-git-log-grep/commit/0abdc860e50a756e75ff63c6a6e7ef2448075de7) which uses consult--read :annotate. Bytecompiling doesn't produce any warnings now.

**Comment by riscy** [comment]
Thank you for accommodating.  This looks good on my end, but I do notice you're depending on `consult--async-command` and other "private" functions in consult.  This means you shouldn't be surprised if your package breaks when if those interfaces change or disappear, and I'd recommend looking for alternatives to these private interfaces if possible.

Not a blocker but definitely something I'd recommend getting ahead of, if you can (maybe by setting up periodic CI to make sure you're compatible with the latest consult).  Merging!

**Pull request merged**
