### PR TITLE
Add recipe for consult-org-roam

### PR DESCRIPTION
**Pull request by jgru**
### Brief summary of what the package does

`consult-org-roam` is a collection of functions to operate [org-roam](https://github.com/org-roam/org-roam) with the help of [consult](https://github.com/minad/consult) and its live preview feature.

### Direct link to the package repository

https://github.com/jgru/consult-org-roam

### Your association with the package

I am the author and the maintainer of this package.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback 
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
> This is intended, since the packages aims to override those functions. Hope, this is okay.

Thanks for this note!  I see what you're aiming for, but usually it's better if packages do their best to stay inside their own namespaces, and if users can undo the effects of loading/applying a package.  But all's not lost...

Instead I'd recommend you use `(advice-add #'org-roam-node-read :around #'consult-org-roam-node-read)` or similar, and then define the latter function.  After that, you can define a minor mode (`consult-org-roam-mode` maybe) and let users use this minor mode to toggle the advice off and on.  That way no definitions get clobbered which can lead to confusing experiences for users.

A couple other quick items --

- consult-org-roam.el#L80: There is no need to quote lambdas (neither #' nor ')
- Add a standard license header or an [SPDX-License-Identifier](https://spdx.dev/ids/) to consult-org-roam.el
- consult-org-roam-pkg.el -- consider excluding; MELPA creates one

**Comment by jgru** [comment]
Thank you very much for your review, @riscy. 
I work on these proposals and ping you, if they are ready.
Thanks again!

Best regards,
jgru

**Comment by jgru** [comment]
Hi @riscy, 

all the issues brought up were addressed. 
I want to underline that I avoided overriding the functions by introducing a minor mode as proposed by you. 
Would you mind to have a second look at the package? 

Thanks in advance for your help on this. 

Best regards,
jgru

**Comment by riscy** [comment]
Thanks a ton for accommodating. :)  This look ready to go -- and, welcome to MELPA. :)

**Pull request merged**
