### PR TITLE
Recipe: Add sbuffer

### PR DESCRIPTION
**Pull request by alphapapa**
### Brief summary of what the package does

Sbuffer is like Ibuffer, but using magit-section to group buffers in a very flexible way.

### Direct link to the package repository

https://github.com/alphapapa/sbuffer.el

### Your association with the package

Author and maintainer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### Notes

* Sbuffer is named like Ibuffer, with an "S" for "sections."  However, there is an unrelated package on MELPA named `s-buffer`, which I just discovered.  It is not depended on by any other MELPA package, and it doesn't have very many installs, so I'm not sure if the similar name is a problem.

  I'm willing to consider renaming this package, but naming things is hard...  :)  I thought about `mbuffer`, since it uses Magit sections, but there is also an `m-buffer` package, which is similar to `s-buffer` (!).  So I'm open to suggestions here.

Thanks.

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.

I cannot find any issues for this package :tada:

**Comment by alphapapa** [comment]
@conao3 Not sure whether to be glad there were no issues found, or mildly annoyed at noise from your bot posting that.  :P

**Comment by conao3** [comment]
I'm not a bot :)
Manually clone, byte-compile and read your whole code.

But I think such bots are useful for speeding up the flow of MELPA.
A typical suggestion that can be analyzed statically. I want to use the Webhook feature, but only the MELPA maintainer has permission...

**Comment by alphapapa** [comment]
Haha, okay, I guessed you had written a bot since the responses were so similar.

I'm guessing it wouldn't be too difficult to write a GitHub Actions script that would run makem.sh or whatever on new package recipes (i.e. it would checkout the new package into a temporary directory and run against its code).  Then much of these reviews could be automated and viewable by recipe submitters.

**Comment by conao3** [comment]
Yes exactly.
I have noticed in the last few weeks that the warnings I am seeing are different from the warnings the package owner is seeing sometimes.

I think they probably customize the presence or absence of warnings.
Because of these issues, it is important to build the package in a clean, standard environment and check for warnings.

**Comment by alphapapa** [comment]
Right, that's why I suggest, e.g. running `./makem.sh --sandbox lint`, which always uses the latest version of `package-lint` and `relint` and is unaffected by the user's local config.

**Comment by alphapapa** [comment]
I'm withdrawing this PR temporarily because I'm expanding the scope of the package and am looking for a better name.  If anyone's interested, it's going to have a kind of frame-based workspace-switching functionality using rules to categorize buffers into workspaces automatically (i.e. the Sbuffer groups).  Naming suggestions are welcome.

**Pull request closed without merging**
