### PR TITLE
post blog-minimal recipe

### PR DESCRIPTION
**Pull request by thiefuniverse**
### Brief summary of what the package does

Blog-minimal is a simple static site generator based on org mode. It's so simple and others can hack it quickly and then create and modify their own site.

### Direct link to the package repository

https://github.com/thiefuniverse/blog-minimal

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- `:files ("*.el" "media" "templates" "about.org")` in the recipe should instead be `:files (:defaults "media" "templates" "about.org")`
- In the "Commentary" section of the main .el file, don't just point people at the website: it's best if the code itself provides the documentation a user will need, and the Commentary section will form the long package summary on the MELPA page for this package.
- You can skip the `-pkg.el` file because MELPA will generate it for you: instead it's often easier to just include a `;; Package-Requires: ...` header in the ain .el file
- `bm.el` is a pre-existing library for bookmarks. Your `bm-vars.el` and `bm-utils.el` should be called `blog-minimal-vars.el` and `blog-minimal-utils.el` for consistency.
- Similarly, `bm/` is not a good prefix. Firstly, `/` should be `-`, and secondly `bm` is not globally unique and should instead match the package name, ie. use `blog-minimal-` throughout. See the [elisp coding conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html) for more info.
- Use `M-x checkdoc` to get advice on how to format your elisp docstrings to match the conventions.
- You're using `s-` functions, but have not declared a dependency on the `s` package.

Hope that helps!

**Comment by thiefuniverse** [comment]
Thanks for your guide, I have updated it.

**Comment by syohex** [comment]
It is not enough yet. Please check https://github.com/thiefuniverse/blog-minimal/pull/4 and its comment.

**Comment by thiefuniverse** [comment]
Thanks for your patience. :smile:

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
