### PR TITLE
Add recipe for cakecrumbs.el

### PR DESCRIPTION
**Pull request by kuanyui**
### Brief summary of what the package does
 Show parent-chain on header for HTML / Jade / Pug / LESS / SCSS / Sass / Stylus 

### Direct link to the package repository

https://github.com/kuanyui/cakecrumbs.el

### Your association with the package

Author.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
  > There're some tiny functions that needn't docstrings.
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
Skimmed through the code, noticed 2 things:
 * If you add customization variables you might as well go with `defcustom`
 * All your functions start with `cakecrumbs-`. It is convention that this is the prefix for public, user-facing functions. "Private" functions should instead be prefixed with `cakecrumbs--`.

**Comment by purcell** [comment]
Thanks! Quick feedback:

- There's no need to have [separate `light` and `dark` specs](https://github.com/kuanyui/cakecrumbs.el/blob/4b88ef88f10c9c21fa4a2ee9984947b32185c081/cakecrumbs.el#L68-L69) for faces that you're `inherit`ing - they have their own `light` and `dark` variants, so just use `:inherit`.
- You should change `kill-buffer-hook` locally, not [globally](https://github.com/kuanyui/cakecrumbs.el/blob/4b88ef88f10c9c21fa4a2ee9984947b32185c081/cakecrumbs.el#L617). Perhaps set it locally when enabling the mode?
- Add `;;;###autoload` cookies for the minor mode and `cakecrumbs-auto-setup` functions

Hope that helps!

**Comment by tarsius** [comment]
Friendly ping!

**Comment by kuanyui** [comment]
Thanks everyone, I just fixed them.

**Comment by tarsius** [comment]
Thanks!

**Pull request merged**
