### PR TITLE
Add recipe for tree-edit

### PR DESCRIPTION
**Pull request by ethan-leba**
### Brief summary of what the package does

Structural editing in Emacs for any language supported by tree-sitter.

### Direct link to the package repository

https://github.com/ethan-leba/tree-edit

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Checklist look great!  And I was actually unfamiliar with `mode-local` so this is interesting.  Some feedback:

- The summary line that just says "Description" was probably just forgotten about, but in its current state it's not too useful for supporting search in the [MELPA index](https://melpa.org)
- The package currently only appears to support Java, but I may be missing something.  I understand you probably have plans to support more languages (I see "for any language" in your main file's `;;; Commentary`) but I would recommend a more specific package name and Commentary until you're really at that point
- The hard requirements on `evil` and `avy` are fairly heavy; both are the type of packages I would avoid using as dependencies unless the package is specifically about them.  I see `evil` may be an important dependency, in which case maybe that needs to be reflected in the package-name/summary/Commentary; or maybe you want to carve off an `evil-tree-edit` package that adds these bindings.  (That would also help with namespacing, since it seems this package is currently creating a `evil-tree-state-map` keybinding outside of its `tree-edit-` namespace)
- tree-edit.el#L820: Lighter should start, but not end, with a space
- tree-edit.el#L502: Loading a package should rarely add hooks; this looks like it should be done/undone by toggling tree-edit-mode

**Comment by ethan-leba** [comment]
Thanks for the review!

> * The package currently only appears to support Java, but I may be missing something.  I understand you probably have plans to support more languages (I see "for any language" in your main file's `;;; Commentary`) but I would recommend a more specific package name and Commentary until you're really at that point

It's true that tree-edit currently only supports Java, but that was an arbitrary choice as a first language to develop against. Tree-edit was explicitly written to be language-agnostic as much as possible -- there's no Java logic anywhere within the codebase. Therefore I'd like to keep the name as is if that's alright.

> * The hard requirements on `evil` and `avy` are fairly heavy; both are the type of packages I would avoid using as dependencies unless the package is specifically about them.  I see `evil` may be an important dependency, in which case maybe that needs to be reflected in the package-name/summary/Commentary; or maybe you want to carve off an `evil-tree-edit` package that adds these bindings.  (That would also help with namespacing, since it seems this package is currently creating a `evil-tree-state-map` keybinding outside of its `tree-edit-` namespace)

That sounds reasonable to me, I'll go ahead and split off the `evil`/`avy` reliant parts into an `evil-tree-edit` package.

**Comment by ethan-leba** [comment]
I've addressed the [minor comments](https://github.com/ethan-leba/tree-edit/commit/81038344768a15a5fc54250dbaf478cc0106701d) and split off the evil/avy parts into a [separate package](https://github.com/ethan-leba/tree-edit/commit/fe0d2ff4edc016a4ed0ec3466a3f4438a64640bf), and updated the MELPA recipes accordingly. I'd like to keep the packages in the same repo for the time being until the tree-edit interface is more stable. Let me know if this looks OK!

**Comment by riscy** [comment]
Thanks for accommodating -- since the refactor I see just one byte-compile warning:

byte-compile (using Emacs 27.1):
```
tree-edit.el:747:1:Warning: the function `avy-process' is not known to be
    defined.
```
which you can resolve with `declare-function`, and then this should be an easy merge.

Not strictly blockers but fyi:
- tree-edit-java-grammar.el has "Description" as its summary line
- Similarly for tree-edit-java.el
- Similarly for tree-edit-view.el
- I suggest an explicit `Package-Requires` and `require` on `tsc` in evil-tree-edit.el, in addition to `tree-sitter` itself -- rather than relying on transitive imports to always be intact
- Similarly for `(require 's)` in evil-tree-edit.el

**Comment by ethan-leba** [comment]
No problem! Addressed the remaining comments: https://github.com/ethan-leba/tree-edit/commits/main 

Let me know if any other changes are needed!

**Comment by riscy** [comment]
Thanks for this, and welcome to MELPA!

**Pull request merged**
