### PR TITLE
Add starlit theme

### PR DESCRIPTION
**Pull request by TheJJ**
### Brief summary of what the package does

The package provides a dark color scheme.

### Direct link to the package repository

https://github.com/SFTtech/starlit-emacs

### Your association with the package

I created and will maintain it :)

### Relevant communications with the upstream package maintainer

**None needed**, I'm the maintainer.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Everything looks good here, but I think GitHub's [licensee](https://github.com/licensee/licensee) is failing to auto-detect your license.  On a quick glance I think this is because the license text contains https links instead of http links -- this is unfortunate, but I suspect you could make it so the GitHub API can auto-detect your license by adjusting those.

**Comment by TheJJ** [comment]
Thanks for the hint, I'll see how I can get the license detection fixed :)

**Comment by TheJJ** [comment]
Ok, this is really strange. I installed `licensee` 9.15.2 via `gem install licensee` in a throwaway lxd-container.

 `licensee` seems to badly misjudge the license:

```
License:        NOASSERTION
Matched files:  LICENSE, COPYING, README.md
LICENSE:
  Content hash:  7d4cdf499d39e2e1ce27b2878e22872f0f5a74dd
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       GPL-3.0
COPYING:
  Content hash:  f50b9c9d168f9852ecdae3654ff5a9d772dd3a0d
  License:       NOASSERTION
  Closest non-matching licenses:
    ISC similarity:    30.14%
    Zlib similarity:   26.52%
    MIT-0 similarity:  26.47%
README.md:
  Content hash:  bf83d816e0c820af4419993ff1cd3fba5b3f6a4e
  License:       NOASSERTION
  Closest non-matching licenses:
    WTFPL similarity:  15.84%
    ISC similarity:    5.26%
    0BSD similarity:   4.98%
```

only after i rename `COPYING` and `README.md`, it actually detects the GPL...

even an empty `COPYING` file will lead the resulting license to be NOASSERTION (an empty README.md is ignored):
```
License:        NOASSERTION
Matched files:  LICENSE, COPYING
LICENSE:
  Content hash:  7d4cdf499d39e2e1ce27b2878e22872f0f5a74dd
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       GPL-3.0
COPYING:
  Content hash:  da39a3ee5e6b4b0d3255bfef95601890afd80709
  License:       NOASSERTION
  Closest non-matching licenses:
    Zlib similarity:   0.00%
    WTFPL similarity:  0.00%
    Vim similarity:    0.00%
```

At that point my motivation of debugging and fixing this funny detector tool is rather low, but I've opened issues...
licensee/licensee#553 licensee/licensee#554

**Comment by riscy** [comment]
Thank you for looking into that -- I own [a repo](https://github.com/riscy/shx-for-emacs/) where a COPYING file is correctly detected as a GPL 3.0 license but that's the only license-like file in there.  I've also seen issues where a file called `license-check.el` or similar inside the repository trips Licensee up, even though there is a valid LICENSE file in there.

I didn't notice you had both files in there... I think in the case of the starlit repo, you could just remove one of the two files?

**Comment by TheJJ** [comment]
I tried, and then the readme gets in the way and leads to NOASSERTION again.
I'd prefer to keep both since in copying there's the author list (as I did with most of my projects), and in license it's the unmodified license text. Rather than working around bugs in licensee I think they should be fixed there :)

**Pull request merged**
