### PR TITLE
Add recipe for exercism-modern

### PR DESCRIPTION
**Pull request by elken**
### Brief summary of what the package does

A modern interface to [exercism](https://exercism.org), providing a clean UI and simple submission.

### Direct link to the package repository

https://github.com/elken/exercism-modern

### Your association with the package

It's my package

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
How does this compare to the exercism package added yesterday?:

https://github.com/melpa/melpa/pull/8206

is collaboration with the author of that package a possibility?

**Comment by riscy** [comment]
Hi @elken, any thoughts on the above question?

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to reach out.

**Comment by progfolio** [comment]
@elken 

https://github.com/elken/exercism-modern/commit/e5b492e188d63ed7e3265ebd84b60d4614149790

Seems to indicate that you no longer have interest in submitting this package to MELPA.
Is that the case?

**Pull request closed without merging**
