### PR TITLE
Add recipe for projection

### PR DESCRIPTION
**Pull request by mohkale**
### Brief summary of what the package does

Projection is a utility package for working with Projects in Emacs built on top of `project.el`. Think of it as a more modular projectile.

### Direct link to the package repository

https://github.com/mohkale/projection

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback (It's complaining about project not being a standard keyword, and about some dependencies (which are in MELPA) not being installable :confused:)
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by mohkale** [comment]
Hi @riscy 

I should have addressed most of the issues please recheck. 

## melpazoid

This is neat, but I find the interface a little kludgy. I'd really rather not depend on another repo to be able to lint my own. If you could eventually upload this to the docker artifactory so I can pull it in directly that would be great. In the meantime I'm failing to run it manually as well :/.

```bash
RECIPE='(projection :repo "mohkale/projection" :fetcher github)' LOCAL_REPO='~/.cache/emacs/straight/repos/projection/' make

...

DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

unknown flag: --progress
See 'docker build --help'.
make[1]: *** [Makefile:19: image] Error 125
```

## packagelint

For reference I'm not sure how to run packagelint in my CI/CD configuration. Just running it by itself in each buffer is giving a bunch of standard package errors which are all covered by the main `projection.el` file.

```text
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a Homepage or URL header.
1:0: warning: The package summary should not end with a period.
1:72: warning: You should depend on (emacs "24.1") if you need lexical-binding.
...
make: *** [Makefile:44: src/projection-commands.pkglint] Error 1
```

I'd really rather not repeat the preamble in each file when the main one should be the definitive version. 

## subwarnings

This is because project and compile-multi are not installable. I have no idea how to fix this, in my case I build and test with cask and it can install both of these just fine.

```
1 issue found:
7:23: warning: This makes the package uninstallable in all released Emacs versions.
```

I'd rather not fix these if possible. All the ibuffer macros generate functions prefixed with `ibuffer-` and maintaining an inconsistent mix of `ibuffer-projection` and `projection-ibuffer` is just confusing.

```
4 issues found:
181:0: error: "ibuffer-projection-current-project" doesn't start with package's prefix "projection".
221:0: error: "ibuffer-projection-set-filter-groups" doesn't start with package's prefix "projection".
231:0: error: "ibuffer-projection-unset-filter-groups" doesn't start with package's prefix "projection".
253:0: error: "ibuffer-projection-toggle-filter-groups" doesn't start with package's prefix "projection".
```

If this is referring to the use of autoload instead of require, it's to avoid a cyclic dependency. The helper to define CMake commands is in projection-types-cmake, but both target generation functions need access to it. I could rearchitect a bit to workaround it but I think an autoload is the cleaner solution here.

```
- projection-types-cmake.el#L249: It may be simpler to just `require` this dependency
- projection-types-cmake.el#L250: It may be simpler to just `require` this dependency
```

Again, not sure how to fix. I'm on project release `0.9.8` which does have this function defined. I'm guessing what you're building with is using the older project version or project added this new function without a new release.

```
projection-ibuffer.el:84:38: Warning: the function `project-name' is not known
    to be defined.
```

**Comment by riscy** [comment]
>  I'd really rather not depend on another repo to be able to lint my own.

It's not a requirement - it's just how I am running the checks, and you can use it as a reference only if you prefer to.

> Just running [package-lint] by itself in each buffer ...

You may want to check out the variable `package-lint-main-file`; see [here](https://github.com/melpa/melpa/blob/4caa9a03cad40d24484fce27fcfcf75b1d08e814/FAQ.md#how-do-i-make-package-lint-check-a-package-with-multiple-files) (a WIP FAQ that I haven't worked on in some time).

> I'd rather not fix these if possible. All the ibuffer macros generate functions prefixed with ibuffer-

I see - if this is an existing convention, we can accommodate.

Just to clear things up, here's the only thing I see as being left to do --`projection-multi-make.el` with package-lint 20230315.1052:
```
1 issue found:
45:0: error: "compile-multi-make--help-regex" doesn't start with package's prefix "projection".
```

**Comment by mohkale** [comment]
> Just to clear things up, here's the only thing I see as being left to do --projection-multi-make.el with package-lint 20230315.1052:

Ah, my bad, I missed this on my initial pass through the TODO list. It should be fixed now. Thanks Riscy :-).

**Comment by riscy** [comment]
I think you removed your `Package-Requires` line on Emacs 29, but clearly Emacs 29 is still necessary since you're referring to the function `project-name`.  You should restore that Package-Requires on Emacs so that users don't get confused (especially since Emacs 29 isn't yet released).

**Comment by mohkale** [comment]
@riscy 

Bumped minimum supported version to Emacs 29 for now :-).

**Comment by riscy** [comment]
The checklist looks good now - although I have to ask, what's the motivation for a package that "acts as a substitute for `projectile` wherever possible."  Why wouldn't a user just install projectile?  Is it because this has more features, e.g. around compilation?

**Comment by mohkale** [comment]
>  Why wouldn't a user just install projectile?

I suppose it's more of a stylistic sort of choice since projectile added native project.el support recently. Personally I was just wanting to start moving away from projectile and closer to project.el and I see having to sort of hack support for one into the other as wasteful or unnecessary. I see projection as a facility for extending project.el with project specific facilities that takes very heavy inspiration from projectile.

Eventually I might try exporting some of the features of projection into 3rd party optional packages. projection-multi.el for example is one my most used features since writing it but I see no reason it couldn't be hosted separately :thinking:.

**Comment by riscy** [comment]
I think that rationale is reasonable - merging this.

**Pull request merged**
