### PR TITLE
Add recipe for sensei

### PR DESCRIPTION
**Pull request by abailly**
### Brief summary of what the package does

This package provides a simple interface to sensei, a personal note taking and "meta-cognition" tool. See https://abailly.github.io/sensei/ for more info.

### Direct link to the package repository

https://github.com/abailly/sensei

### Your association with the package

Maintainer and author.

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Very quick first pass --

`sensei.el` with byte-compile using Emacs 27.1:
```
sensei.el:41:14:Warning: reference to free variable `request'
sensei.el:64:1:Warning: Unused lexical variable `data'
sensei.el:92:1:Warning: Unused lexical variable `data'
In end of data:
sensei.el:175:1:Warning: the following functions are not known to be defined:
    use-package, request, map, projectile-project-root
```

`sensei.el` with package-lint 20220412.1648:
```
17 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
1:0: error: Package should have a Homepage or URL header.
1:46: warning: You should depend on (emacs "24.1") if you need lexical-binding.
5:0: error: Expected (package-name "version-num"), but found package.
5:0: error: Expected (package-name "version-num"), but found request.
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
36:0: error: Package should have a non-empty ;;; Commentary section.
39:10: error: You should depend on (emacs "24.1") if you need `package'.
51:2: warning: Closing parens should not be wrapped onto new lines.
86:15: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-function'.
88:17: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-function'.
114:15: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-function'.
116:17: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-function'.
130:47: error: You should depend on (emacs "27.1") if you need `json-parse-buffer'.
141:2: warning: Closing parens should not be wrapped onto new lines.
156:2: warning: Closing parens should not be wrapped onto new lines.
170:2: warning: Closing parens should not be wrapped onto new lines.
```
From memory I think the "Expected (package-name..." lints above are not actually breaking issues, but you can easily pacify those by specifying a version number ("0.0" in a pinch).

**Comment by abailly** [comment]
Thanks a lot for taking the time to give this feedback. I will do my homework and address those issues.

**Comment by abailly** [comment]
@riscy I have fixed the package-lint warnings but I am a bit clueless to fix the ones from byte compilation: It seems the package's dependencies are not taken into account which explains why emacs cannot find those functions' definition. How can I fix that? I am an emacs package writer noob, thanks for any help you can provide.

**Comment by abailly** [comment]
I have tried to byte-compile a package from another PR (#8001) and I get the same kind of messages than when I byte-compile my package:
```
% emacs -batch -f batch-byte-compile *.el

In toplevel form:
consult-ls-git.el:46:1:Error: Cannot open load file: No such file or directory, consult
```

What should I do to address these issues? They are caused by a `(require 'xxx)` which cannot be resolved when byte compiling AFAICT

**Comment by abailly** [comment]
I think I have addressed all the issues, could you please have another look @riscy

**Comment by riscy** [comment]
Hi @abailly -- sorry for the delayed reply, I'm mostly here during weekends.

- Ultra minor, but you can use `"%FT%T%z"` instead of `"%Y-%m-%dT%TZ"` for the ISO 8601 format
- Also minor but the body of text under your `Commentary` usually starts with `;;` instead of `;;;`; fortunately this doesn't seem to be adversely affecting `(lm-commentary)` but I'm not sure how MELPA will end up formatting your commentary when your package is indexed
- I'd sharp-quote `sensei-send-note-and-close` in `sensei-record-note` just so the byte-compiler can be on guard in case the function name changes
- cloes -> close, Succesfully -> Successfully

**Comment by riscy** [comment]
Altogether the preceding are minor issues, so I'm happy to merge.  And, welcome to MELPA. :)

**Comment by abailly** [comment]
Thank you so much @riscy! I will take care of the suggested changes. One thing I am note sure of is what you mean by "sharp-quote" the function names?

**Comment by abailly** [comment]
Ah, I see, prepending `#'` to the function's name, will do.

**Pull request merged**
