### PR TITLE
Add recipe for yasnippet-capf

### PR DESCRIPTION
**Pull request by elken**
### Brief summary of what the package does

Provides a completion-at-point function for yasnippet

### Direct link to the package repository

https://github.com/elken/yasnippet-capf

### Your association with the package

I am the author/maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Checklist looks good, but there appear to be some issues with the license:

- The repo appears to be GPL 2 (not 3-or-later) -- see https://github.com/johannes-mueller/company-wordfreq.el/issues/6 for why this is an issue
- The file yasnippet-capf.el lacks license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by elken** [comment]
> Thanks for this. Checklist looks good, but there appear to be some issues with the license:
> 
>     * The repo appears to be GPL 2 (not 3-or-later) -- see [Please use a license that is compatible with Emacs' GPL-3.0-or-later johannes-mueller/company-wordfreq.el#6](https://github.com/johannes-mueller/company-wordfreq.el/issues/6) for why this is an issue

Clicked the wrong link on github's license generator, my bad.

>     * The file yasnippet-capf.el lacks license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

Will add both now :)

**Comment by elken** [comment]
Closes https://github.com/elken/yasnippet-capf/issues/11

**Comment by riscy** [comment]
Thanks for your patience. :)

**Comment by elken** [comment]
No problem at all :)

**Pull request merged**
