### PR TITLE
Added denote-explore package

### PR DESCRIPTION
**Pull request by pprevos**
### Brief summary of what the package does

Enhanced functionality to manage Denote file collections.

### Direct link to the package repository

https://github.com/pprevos/denote-explore/

### Your association with the package

Are you the maintainer and enthusiastic user

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I've modified the recipe to let me run checks on it, but please confirm it matches your intentions.  Quick first pass --

`denote-explore-dashboard.el` with byte-compile using Emacs 29.1:
```
denote-explore-dashboard.el:38:35: Warning: Unused lexical argument `list-size'
In denote-explore-dashboard-activate:
denote-explore-dashboard.el:63:18: Warning: reference to free variable `dashboard-item-generators'
denote-explore-dashboard.el:63:18: Warning: assignment to free variable `dashboard-item-generators'
denote-explore-dashboard.el:65:17: Warning: reference to free variable `dashboard-items'
denote-explore-dashboard.el:65:17: Warning: assignment to free variable `dashboard-items'
denote-explore-dashboard.el:66:17: Warning: reference to free variable `dashboard-item-shortcuts'
denote-explore-dashboard.el:66:17: Warning: assignment to free variable `dashboard-item-shortcuts'
In denote-explore-dashboard-deactivate:
denote-explore-dashboard.el:73:34: Warning: reference to free variable `dashboard-items'
denote-explore-dashboard.el:72:9: Warning: assignment to free variable `dashboard-items'
In end of data:
denote-explore-dashboard.el:57:4: Warning: the function `dashboard-insert-shortcut' is not known to be defined.
denote-explore-dashboard.el:56:29: Warning: the function `denote-explore-count-keywords' is not known to be defined.
denote-explore-dashboard.el:55:29: Warning: the function `denote-explore-count-notes' is not known to be defined.
denote-explore-dashboard.el:44:30: Warning: the function `all-the-icons-octicon' is not known to be defined.
denote-explore-dashboard.el:42:4: Warning: the function `dashboard-insert-heading' is not known to be defined.
```

`denote-explore-dashboard.el` with package-lint 20231121.1907 and `package-lint-main-file` = "denote-explore.el":
```
2 issues found:
8:0: error: Package-Requires outside the main file have no effect.
37:0: warning: Private functions generally should not be autoloaded.
```

`denote-explore-dashboard.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- denote-explore-dashboard.el#L55: `concat` may be unneeded; `insert` can take multiple arguments
- denote-explore-dashboard.el#L56: `concat` may be unneeded; `insert` can take multiple arguments
```

`denote-explore.el` with byte-compile using Emacs 29.1:
```
denote-explore.el:230:14: Warning: Unused lexical variable `file-type'
```

`denote-explore.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- denote-explore.el#L159: It's safer to sharp-quote function names; use `#'`
- denote-explore.el#L184: No `format` required; `message` takes an f-string
- denote-explore.el#L318: No `format` required; `user-error` takes an f-string
```

Also in `denote-explore--script-call` you likely want to run `shell-quote-argument` against each of the arguments, just in case someone e.g. the load-directory happens to have a shell control character in it (apostrophes are common for instance).

**Comment by pprevos** [comment]
Thanks for the detailed review.

Oops, I copied the recipe from my other package and did not change the name.

Fixed all indicated issues and committed the latest version. Apologies for introducing these issues.

**Comment by riscy** [comment]
Here's the latest (maybe not all of your changes got pushed, which happens) --

`denote-explore-dashboard.el` with byte-compile using Emacs 29.1:
```
denote-explore-dashboard.el:37:35: Warning: Unused lexical argument `list-size'
In denote-explore-dashboard-activate:
denote-explore-dashboard.el:62:17: Warning: reference to free variable `dashboard-item-generators'
denote-explore-dashboard.el:62:17: Warning: assignment to free variable `dashboard-item-generators'
denote-explore-dashboard.el:64:17: Warning: reference to free variable `dashboard-items'
denote-explore-dashboard.el:64:17: Warning: assignment to free variable `dashboard-items'
denote-explore-dashboard.el:65:17: Warning: reference to free variable `dashboard-item-shortcuts'
denote-explore-dashboard.el:65:17: Warning: assignment to free variable `dashboard-item-shortcuts'
In denote-explore-dashboard-deactivate:
denote-explore-dashboard.el:72:34: Warning: reference to free variable `dashboard-items'
denote-explore-dashboard.el:71:9: Warning: assignment to free variable `dashboard-items'
In end of data:
denote-explore-dashboard.el:56:4: Warning: the function `dashboard-insert-shortcut' is not known to be defined.
denote-explore-dashboard.el:55:21: Warning: the function `denote-explore-count-keywords' is not known to be defined.
denote-explore-dashboard.el:54:21: Warning: the function `denote-explore-count-notes' is not known to be defined.
denote-explore-dashboard.el:43:30: Warning: the function `all-the-icons-octicon' is not known to be defined.
denote-explore-dashboard.el:41:4: Warning: the function `dashboard-insert-heading' is not known to be defined.
```

`denote-explore-dashboard.el` with package-lint 20231121.1907 and `package-lint-main-file` = "denote-explore.el":
```
1 issue found:
8:0: error: Package-Requires outside the main file have no effect.
```

`denote-explore.el` with byte-compile using Emacs 29.1:
```
denote-explore.el:230:14: Warning: Unused lexical variable `file-type'
```

**Comment by pprevos** [comment]
Hi @riscy ,

I ave removed `denotex-explore-dashboard.el` as I need to figure out some dependency issues. It is only auxiliary to the package.

**Comment by riscy** [comment]
Thanks!  Here's the latest on my side --

`denote-explore.el` with byte-compile using Emacs 29.1:
```
denote-explore.el:230:14: Warning: Unused lexical variable `file-type'
In end of data:
denote-explore.el:349:16: Warning: the function `json-encode' is not known to be defined.
```
If `file-type` is somehow needed but not used (I don't think it is?) you can pacify the byte compiler by renaming it to `_file-type`. 

The use of `json-encode` needs a `(require 'json)`.

**Comment by pprevos** [comment]
Thanks for the feedback,

Interestingly I don't get this error. What am I missing? I did follow the MELPA instructions page for tracking issues.

I removed line 230. That was a debugging line that should not be in the prod version. 

Fixed another unrelated bug.

Thanks for your patience, it is a learning experience.

P:)

**Comment by riscy** [comment]
> Interestingly I don't get this error. What am I missing? I did follow the MELPA instructions page for tracking issues.

Most likely you're compiling your code in an instance of Emacs that has already loaded the code, or some past version of it at least.  Using `flycheck` helps with this, or you can restart emacs using `emacs -Q` and try compiling from there.  This is actually one of the biggest gotchas in package development (imo) and one of the reasons melpazoid came to be.

Here's the latest --

`denote-explore-dashboard.el` with byte-compile using Emacs 29.1:
```
denote-explore-dashboard.el:34:2: Error: Cannot open load file: No such file or directory, dashboard
```
I think this ties into the package-lint in the next block -- easy fix.

`denote-explore-dashboard.el` with package-lint 20240118.1725 and `package-lint-main-file` = "denote-explore.el":
```
1 issue found:
8:0: error: Package-Requires outside the main file have no effect.
```

`denote-explore.el` with byte-compile using Emacs 29.1:
```
denote-explore.el:289:18: Warning: reference to free variable `table'
```
Looks like some leftover debugging code here I think?

`#'load`-check on each file:
```
Loading denote-explore.el
  denote-explore.el:Error: Emacs 29.1:
  (void-variable table)
Loading denote-explore-dashboard.el
  denote-explore-dashboard.el:Error: Emacs 29.1:
  (file-missing "Cannot open load file" "No such file or directory" "dashboard")
```

Package and license:
- denote-explore.el must include all of the Package-Requires listed in denote-explore-dashboard.el: dashboard "2.19.1"

**Comment by pprevos** [comment]
Thanks for the feedback ad your patience.

I looked at Melpazoid, but am lost on how to use it. It tested using a clean Emacs and test user directory with this init file:

```
(package-initialize)

(add-to-list ' package-archives
               '("melpa" . "https://melpa.org/packages/"))

(package-vc-install
 '(denote-explore
   :url "https://github.com/pprevos/denote-explore/"))

(use-package denote
  :ensure t
  :custom
  (denote-directory "~/Documents/notes/"))
```

Compilation without errors.

Also used: `flycheck`, `checkdoc`, `package-lint` and . Surely it is OK now :)

**Comment by riscy** [comment]
> I looked at Melpazoid, but am lost on how to use it.

It (and its docs) could definitely be better, but it's not strictly necessary to use in any case. :)

Everything checks out on my end - thanks again!

**Pull request merged**
