### PR TITLE
Add recipe for mu4e-query-fragments

### PR DESCRIPTION
**Pull request by wavexx**
### Brief summary of what the package does

`mu4e-query-fragments` allows to define query snippets ("fragments") that
can be used in regular `mu4e` searches or bookmars. Fragments can be used to
define complex filters to apply in existing searches, or supplant bookmarks
entirely. Fragments compose properly with regular mu4e/xapian operators, and
can be arbitrarily nested.

### Direct link to the package repository

https://github.com/wavexx/mu4e-query-fragments.el

### Your association with the package

Author

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

package-lint complains that I use mu4e/qf as opposed to mu4e-query-fragments as the prefix, however I'm using mu4e/[suffix] to avoid namespace clashes with mu4e symbols, as well to keep it reasonably editable.

The same strategy is used with multiple-cursors (where mc/[ext] is used).

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick feedback:
- `mu4e` is not a well-formed package dependency: `package-lint` should have warned about this. In fact `mu4e` is not installable as a package, so you should not list it.
- Re. the `mu4e/qf` prefix, just use `mu4e-query-fragments` to match the package name. `mc/` set a bad example, and we don't accept non-standard prefixes these days, since we want to promote the elisp community standards.

**Comment by wavexx** [comment]
On Fri, Sep 08 2017, Steve Purcell wrote:
> - `mu4e` is not a well-formed package dependency: `package-lint`
> should have warned about this. In fact `mu4e` is not installable as a
> package, so you should not list it.

Ok, didn't notice, as I made the mu4e package locally for myself. Sorry
about this.

> Re. the `mu4e/qf` prefix, just use `mu4e-query-fragments` to match the
> package name. `mc/` set a bad example, and we don't accept
> non-standard prefixes these days, since we want to promote the elisp
> community standards.

Is there some "standard" shortcut for long package names that want to be
descriptive?

Prefixing everything with mu4e-query-fragments makes me want to just
change the package name to mu4e-qf, honestly.

**Comment by wavexx** [comment]
I changed the prefix to `mu4e-qf`. If that's not enough, I will rename the package itself.

**Comment by purcell** [comment]
> Prefixing everything with mu4e-query-fragments makes me want to just change the package name to mu4e-qf, honestly.

I actually think the prefix is okay as `mu4e-query-fragments`, particularly for a little package like this, but if you stick with `mu4e-qf`, then yes, it would make sense to rename the package IMO.

**Comment by wavexx** [comment]
On Sat, Sep 09 2017, Steve Purcell wrote:
>> Prefixing everything with mu4e-query-fragments makes me want to just
>> change the package name to mu4e-qf, honestly.
>
> I actually think the prefix is okay as `mu4e-query-fragments`,
> particularly for a little package like this, but if you stick with
> `mu4e-qf`, then yes, it would make sense to rename the package IMO.

Having variables names such as
mu4e-query-fragments-append-to-new-queries is not something I'd want to
do, honestly.

But I also dislike "mu4e-qf" as a package name in terms of
discoverability.

I actually have three more extensions to mu4e that I'd like to publish.
query-fragments is the smallest.

One of them would be "mu4e-jump-to-list", which internally I shortened
to mu4e-jtl-*. Similarly, I would have variables of the form
mu4e-jtl-max-age-threshold, which would become a juggernaut such as
mu4e-jump-to-list-max-age-threshold.

There's a real visual clutter with such long names.
But I'd rather sacrifice the prefix than the informative part of
variable name.

**Comment by wavexx** [comment]
On Sat, Sep 09 2017, Yuri D'Elia wrote:
> On Sat, Sep 09 2017, Steve Purcell wrote:
>>> Prefixing everything with mu4e-query-fragments makes me want to just
>>> change the package name to mu4e-qf, honestly.
>>
>> I actually think the prefix is okay as `mu4e-query-fragments`,
>> particularly for a little package like this, but if you stick with
>> `mu4e-qf`, then yes, it would make sense to rename the package IMO.

Oh well, I went in and renamed the prefix to mu4e-query-fragments.
package-lint now doesn't complain anymore, although there was some eye
watering involved.

**Comment by wavexx** [comment]
@purcell anything missing?

**Comment by purcell** [comment]
Great - merging now. Thanks for your patience. :-)

**Pull request merged**
