### PR TITLE
Update ein recipe to remove zeroein.el from package

### PR DESCRIPTION
**Pull request by millejoh**
### Brief summary of what the package does

Emacs IPython Notebook.

### Direct link to the package repository

https://github.com/millejoh/emacs-ipython-notebook

### Your association with the package

I am the current maintainer.

### Relevant communications with the upstream package maintainer

Package is already part of melpa, I am tweaking the recipe to remove a file that is unnecessary when ein is installed via melpa.

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
There are some unrelated commits. Could you use topic branch and re-send pull request ?

**Comment by millejoh** [comment]
Yes, of course, though unfortunately my knowledge of git-fu is not quite strong enough to know exactly what needs to be done. If you have some time could you point me in the direction of what I need to do?

**Comment by syohex** [comment]
I have cherry-picked your commit(https://github.com/melpa/melpa/commit/215e163755fe391ce1f049622e7b9bf9a8aea95a).

**Comment by syohex** [comment]
Reference
- https://help.github.com/articles/about-pull-requests/
- https://yangsu.github.io/pull-request-tutorial/

Please take care at next time.

**Comment by millejoh** [comment]
I will, and thank you for taking mercy on this poor soul.

**Pull request closed without merging**
