### PR TITLE
Add sqlite-mode-extras

### PR DESCRIPTION
**Pull request by xenodium**
### Brief summary of what the package does

Extend Emacs 29 sqlite-mode capabilities.

### Direct link to the package repository

https://github.com/xenodium/sqlite-mode-extras

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
Cool features. Have you considered proposing these changes upstream?

**Comment by xenodium** [comment]
Possibly in the future as I currently have limited time available.

This package was born out of [these experiments](https://xenodium.com/further-sqlite-mode-extensions) in my dots repo. Having said that, I've received enough user requests to  publish to MELPA as they found it useful. 

Given time constraints, publishing to MELPA is the best compromise I can currently offer.

**Comment by riscy** [comment]
Thanks for this.  I've got one small nag:

- sqlite-mode-extras.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

And one question around (of course) string injection.  In `sqlite-mode-extras-edit-row-field` for example I see the variable `table` is from `(sqlite-mode-extras--type-property-at-point)` - is it possible for the resulting text property to contain characters that we wouldn't want to see interpolated into a SQL query?

**Comment by xenodium** [comment]
Thanks for the feedback Chris!

> sqlite-mode-extras.el needs formal license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

oh yes, thanks. Done. https://github.com/xenodium/sqlite-mode-extras/commit/a214d2d01ab8eec748187e36ee5c2b7e10044cb0

>  is it possible for the resulting text property to contain characters that we wouldn't want to see interpolated into a SQL query?

Only if the undesired characters were explicitly put into the property. Unlikely as the property is typically populated by table data from the upstream `sqlite-mode-list-tables` function, which gets table info via `select name from sqlite_master`.

It's a good safety shout though. I can look into additional redundancy, but that will need to wait a little while. I had been postponing submission to MELPA to maybe develop things further, though have been getting feedback that things have been fairly stable for users. I'm hoping MELPA submission would also encourage contributions for enhancements, including safety/redundancy.

Ok to postpone additional work in this space?

**Comment by xenodium** [comment]
> Ok to postpone additional work in this space?

@riscy  Had a little look and added some initial assertions: https://github.com/xenodium/sqlite-mode-extras/commit/25e7e5212632dcc4702cf1f29528913be4bd23ec

**Comment by riscy** [comment]
Thank you - I agree with your assessment on the severity being pretty minimal.  Let's merge.

**Comment by xenodium** [comment]
Thanks for your help Chris!

**Pull request merged**
