### PR TITLE
Redirect stardiviner recipes to emacsmirror

### PR DESCRIPTION
**Pull request by Boruch-Baum**
+ references: #7872 #7882

### CODE REVIEW

**Comment by riscy** [comment]
Thanks @Boruch-Baum and @stardiviner!

**Comment by tarsius** [comment]
Usually when the upstream repository disappears then I move the package from the Emacsmirror to the Emacsattic. There are exceptions, most importantly if other packages still depend on it, then I add it to the Emacsorphanage and then mirror that on the Emacsmirror.

I am doing neither in this case for now because I still have hope that @stardiviner will find a more satisfying solution and want to avoid work that I would later have to discard again depending on what they do.

@stardiviner A possible host is https://repo.or.cz. It has been around for a very long time and has very few strings attached. Alternatively, as others have already pointed out, you might want to reconsider sourcehut and codeberg; but I have a feeling repo.or.cz is most suited to your needs.

**Comment by tarsius** [comment]
Well the nearest star is simply known as the *sun* but maybe they mean the nearest star to the sun, in which has that would be *Alpha Centauri*.

**Comment by tarsius** [comment]
*Proxima Centauri* actually.

**Comment by stardiviner** [comment]
@tarsius Thanks very much. I have not realized that, I thought it's some kind of weird question that related to their country.

**Comment by Boruch-Baum** [comment]
@stardiviner : I spent some time researching, and came up with the following that might match your temperament:

+ A gitlab instance:  https://framagit.org/
  + operated by a long-term stable track-record (since 2001), ideologically-FOSS, anti-corporate non-profit not based in a super-power nation-state.
     https://en.wikipedia.org/wiki/Framasoft

**Comment by stardiviner** [comment]
@Boruch-Baum Oh, sorry to forget update here. I have found a hosting website now.
https://github.com/melpa/melpa/issues/7872#issuecomment-1032451991

Thanks for your researching. I will add it to my bookmarks, might consider add as another git remote. Thanks very much.

**Pull request merged**
