### PR TITLE
propose writer-word-goals

### PR DESCRIPTION
**Pull request by ag91**
### Brief summary of what the package does

With wwg you can set how many words you want to write and it will
count that down for you, encouraging on your way there.

### Direct link to the package repository

https://github.com/ag91/writer-word-goals

### Your association with the package

I am the creator and maintainer of wwg.el.

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  There are a couple of other packages in this space [here](https://melpa.org/#/?q=word%20count) -- can you comment on how yours differs?  Also, considering that <kbd>M-x count-words</kbd> or <kbd>C-u M-=</kbd> will already message users about how many words are in the buffer, I'd suggest at least mentioning that in your docs/Commentary.  And then you can describe how your package augments that workflow (e.g. doing the word counting in the background, on a timer).

In the meantime some thoughts/suggestions:

- If you are just going to write messages every 15 seconds, have you considered putting something in `mode-line-format` or `header-line-format`?
- wwg.el#L7: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- This looks like it would be better implemented as a minor mode, since the ingredients of a minor mode are there (e.g. toggling off and on, tracking buffer-local variables) and the result would be more familiar to many users
- No `progn` is required to wrap the `else` part of an `if`
- I'd suggest breaking your lines at something a little narrower to make it easier for others to inspect your code (especially those on a laptop display).  Also be aware that the Emacs online help does not know where to break words in long docstrings, so make sure those are word wrapped too

**Comment by ag91** [comment]
Fantastic feedback @riscy ! This is just amazing: I will address all your points asap and get back with a much better version of my mode.

**Comment by ag91** [comment]
@riscy I have rewritten my commentary to give a better sense of what I am trying to achieve with the mode. In a gist it is about encouraging writers: for now I am gamifying the writing of content, but I already have a branch that I am testing for editing.

About the other points:

- modeline idea: great, I find the message in the console sufficient and powerusers can just substitute the function in the defvar if they prefer another visualization (I may do that later if I find a better way to gamify things)
- version: done and thanks for the explanation!
- license: done and thans again: I did not know about licensee
- minor-mode: I am not sure about that, one of the defvar needs to be global because keeps track of all the buffers with a goal running in it. I shall think about it some more, how about I change that later, if needed?
- progn: actually that form has to return `nil` but the `message` function returns a string
- breaking lines: done, sorry for bothering your review

**Comment by riscy** [comment]
> minor-mode: I am not sure about that, one of the defvar needs to be global because keeps track of all the buffers with a goal running in it. I shall think about it some more, how about I change that later, if needed?

Since there are already a few packages in this space, I figure we should reach for a high-quality, idiomatic solution in this case.  So while I wouldn't insist on a minor mode for this, there _should_ be a way for users to disable the timer(s) if they don't finish.  Toggling a mode off is a natural approach.  Another consideration: what should happen if the user simply closes a buffer without finishing?  I'll leave the particular details to you, but implementing a minor mode will make a lot of these questions stand out.

> progn: actually that form has to return nil but the message function returns a string

That's still fine:
```elisp
    (if (<= remaining-words 0)
        (progn
          (beep)
          (message
           "Well done! You wrote %s words, and %s extra words of what you planned!!"
           target-count
           (abs remaining-words))
          'finished)
      (message
       "%s %s words left."
       (wwg-choose-message remaining-words)
       remaining-words)
      nil)))
```

> breaking lines: done, sorry for bothering your review

No problem, that line-length complaint is a "canned" message I'm experimenting with, I'll try to soften the language a bit.  But remember to run checkdoc again after you make such adjustments!

**Comment by ag91** [comment]
@riscy you convinced me! Let's do it right. Is the following what you expected? https://github.com/ag91/writer-word-goals/commit/37c9321354618e8d09cc3bc78750c2a0ac7d7b27

**Comment by riscy** [comment]
Yes, just like that. :)  However, the mode should follow the prefix rules and end with `-mode`, so I would call it `wwg-mode`.  It should also be the only way to toggle the mode on -- so I notice for example the interactive function `wwg-set-goal-current-buffer` and `wwg-set-1k-goal-current-buffer` are still user-accessible and they don't toggle the mode on when called.

Instead I'd recommend deleting those two functions and defining the mode like this:

```
(define-minor-mode wwg-mode
  "Toggle writer goal mode for writing some number of words."
  :group 'wwg
  (if (not wwg-mode)
      (cancel-timer (car (alist-get (current-buffer) wwg-active-timer-alist)))
    (let* ((current (count-words (point-min) (point-max)))
           (target (read-number "How many words do you want to write? " 1000)))
      (wwg-monitor-word-count-for-buffer (+ current target) (current-buffer)))))
```

Here's the latest scan of the checklist, although I think the package-lint is addressed by the above change:

checkdoc (using version 0.6.2):
```
Warning (emacs): 
wwg.el:63: Second line should not have indentation
Warning (emacs): 
wwg.el:69: Second line should not have indentation
Warning (emacs): 
wwg.el:69: Some lines are over 80 columns wide
```

package-lint (using version 20210127.158):
```
1 issue found:
141:0: error: "word-writer-goal" doesn't start with package's prefix "wwg".
```

**Comment by ag91** [comment]
very cool, I like your version better! Fixes applied.

**Comment by riscy** [comment]
I notice the variable `wwg-number-of-words` is no longer used anywhere, but I don't count that as a blocker.  Welcome to MELPA! :)

**Comment by ag91** [comment]
Amazing! Thanks Chris!
(I will clean that up in my next commit then)

**Pull request merged**
