### PR TITLE
Add recipe: grip-mode.

### PR DESCRIPTION
**Pull request by seagle0128**
### Brief summary of what the package does

Instant Github-flavored Markdown preview using [grip] https://github.com/joeyespo/grip) (Github README Instant Preview).

### Direct link to the package repository

https://github.com/seagle0128/grip-mode

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

N/A

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by seagle0128** [comment]
Updated the checklist. Please merge. Thanks！

**Comment by markhepburn** [comment]
@seagle0128  I just came here wondering when it would be merged too, but probably also worth considering https://github.com/melpa/melpa/issues/4154

(Love your package btw!)

**Comment by riscy** [comment]
Thanks for the close adherence to the checklist.  One comment I have is that looking for the executable once [here](https://github.com/seagle0128/grip-mode/blob/8792144d856aff7dd5c3eed7698987db3f073a51/grip-mode.el#L53) means that, if the user installs grip, they'll have to restart Emacs (or painstakingly re-set the variable) before grip is detected correctly -- and the error message doesn't tell them as much.

Maybe when the check [here](https://github.com/seagle0128/grip-mode/blob/8792144d856aff7dd5c3eed7698987db3f073a51/grip-mode.el#L72-L73) fails, you could try once more to locate the binary.  Or you could try to locate the binary on every call to `grip-start-process`, which would be (undetectably) slower but more robust.

Another ultra minor thing I'm seeing is that "Github" is usually branded "GitHub".

**Comment by seagle0128** [comment]
@riscy Thanks a lot for the suggestion! I've updated the codes according to your comments.

**Comment by purcell** [comment]
> Maybe when the check [here](https://github.com/seagle0128/grip-mode/blob/8792144d856aff7dd5c3eed7698987db3f073a51/grip-mode.el#L72-L73) fails, you could try once more to locate the binary. Or you could try to locate the binary on every call to `grip-start-process`, which would be (undetectably) slower but more robust.

Yeah, it's generally best not to try to locate a specific binary path at all, because that's what `exec-path`/`$PATH` are for. If the user wants to provide a full path when customising an executable path, then they can still do that.

A couple more notes from me:
- You should provide a `:group` for your `defgroup` form, perhaps `applications`.
- The `buffer-file-name` handling [here](https://github.com/seagle0128/grip-mode/blob/15f6d5777f9124cda5940a4f70ee6905edc0d144/grip-mode.el#L111-L126) is a bit inconsistent: in one function, nothing happens if the buffer is not backed by a file, and in the other, and error will occur. The ideal would be that temp files should be used when the buffer does not have a filename: it's generally best not to assume that every buffer has a file.
- Don't use `concat` to build file names, in any case. In fact, [here](https://github.com/seagle0128/grip-mode/blob/15f6d5777f9124cda5940a4f70ee6905edc0d144/grip-mode.el#L113) you should probably just use `default-directory` instead of trying to get the buffer file's directory.

Hope that helps! This is okay to merge in the meantime, but please take a look at those points above in your own time.

**Comment by seagle0128** [comment]
Thank you very much, @purcell !

The comments are helpful. I am working on it.

**Pull request merged**
