### PR TITLE
Add recipe for morganey-mode

### PR DESCRIPTION
**Pull request by rexim**
### Brief summary of what the package does

Major mode for editing source code written in [Morganey](https://github.com/morganey-lang/Morganey) programming language

### Direct link to the package repository

https://github.com/morganey-lang/morganey-mode

### Your association with the package

Author, maintainer

### Relevant communications with the upstream package maintainer

None needed 

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
`C-\\` is bound to `toggle-input-method` by default. Some non-english people like Japanse, Chinese etc, may use this command for writing comment or string etc. So I suppose other key should be bound instead of `C-\\`.

**Comment by rexim** [comment]
@syohex thanks for reporting that UX problem! :)

**Comment by rexim** [comment]
@syohex I addressed the problem in https://github.com/morganey-lang/morganey-mode/issues/12 Thanks!

**Comment by syohex** [comment]
Merged

**Comment by rexim** [comment]
@syohex thanks!

**Pull request merged**
