### PR TITLE
add org-generate recipe

### PR DESCRIPTION
**Pull request by conao3**
### Brief summary of what the package does

Generate template files/folders from one org document.

### Direct link to the package repository

https://github.com/conao3/org-generate.el

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Just a quick first pass --

- org-generate.el#L144: No `format` required; messages are already f-strings
- org-generate.el#L172: Consider `unless ...` instead of `when (not ...)`

**Comment by conao3** [comment]
Fixed, thanks.

**Comment by riscy** [comment]
This is really interesting, sort of like a yasnippet for generating an entire directory tree.  I notice you have only one `sample.org`, but I wonder if it would be a valuable service to have this come with a `generators/` subdirectory with a bunch of standardized generators that you could open up to the community for contributions (elisp project generators, latex document generators, etc.)

Minor:
- Gerenate -> Generate
- it have childlen -> it has children
-

**Comment by conao3** [comment]
Thanks! And generate a lot of yasnippet snippets from one org document is one of the major purposes for this package.

**Pull request merged**
