### PR TITLE
Added shen-elisp recipe.

### PR DESCRIPTION
**Pull request by deech**
http://github.com/deech/shen-elisp

An implementation of the Shen programming language in Elisp.

I am the package author.

### CODE REVIEW

**Comment by purcell** [comment]
Hi! Change of heart? Not ready?

**Comment by deech** [comment]
It wasn't. It is now. Very much appreciate the bump!

**Comment by purcell** [comment]
Thanks - looks very cool!

Quick questions/comments:

- Do you intend to bundle `install.el`?
- Technically `:defaults` is preferred to `"*.el"` in recipes, since it also includes other files you might add later, e.g. info manuals
- We normally wouldn't bundle `.org` files into packages because they're not at all discoverable after installation. And `shen-elisp.org` looks like the tangled source for the `.el` files, so that really isn't needed afaict.
- At least for public commands, you should follow the [elisp coding conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html) rather than CL/Clojure style, so `shen-repl` rather than `shen/repl`.
- Snippets like `(require 'shen "shen.el")` are just workarounds for broken installations, and might subvert loading of byte-compiled files. Just use `(require 'shen)`

**Comment by deech** [comment]
Thanks for your feedback!
- No the install.el isn't doing anything.
- I'll remove the org files
- In fact the KLambda/*.kl should probably be removed as well.
- Ah, I didn't know about the naming conventions. Unfortunately I doubled down on the 'shen/' prefix early on for all the written and generated Elisp so I'd rather not change that now.
- I'll remove the filenames from the `require` forms.
Thanks for your feedback!

**Comment by purcell** [comment]
Great thanks - this misses the `-pkg.el` file though. Would you mind adding that into the `:files` list please? `"shen*.el"` might do the trick.

**Comment by deech** [comment]
Sorry for all the errors. This is now fixed and intermediate commits have been squashed. Thanks again!

**Comment by purcell** [comment]
Awesome, thanks.

**Pull request merged**
