### PR TITLE
Added `dired-file-preview` recipe

### PR DESCRIPTION
**Pull request by SpringHan**
### Brief summary of what the package does

`dired-file-preview` is a package that allows users to use `dired` with preview support.

### Direct link to the package repository

https://github.com/SpringHan/dired-file-preview

### Your association with the package

I'm maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by Boruch-Baum** [comment]
Package `diredc` does this (full disclosure: I'm that package's author). That package operates similarly to `midnight commander`'s preview, using the same default keybinding <kbd>C-x q</kbd>. Additionally, `diredc` allows one to exclude "garbage" (eg. binariy) or otherwise unwanted files from being automatically previewed, by mime-type or by regex. I've half-finished support for `hexl-mode` preview of certain files, hopefully to be added soon.

**Comment by SpringHan** [comment]
OK, that's fine. I'll close this PR.

**Comment by Boruch-Baum** [comment]
On 2021-07-24 21:56, Jim Huang wrote:
>    OK, that's fine. I'll close this PR.

Not so fast! Just because duplication exists, doesn't mean your package
doesn't have value for general MELPA distribution. For example: your
package may do something better than mine (or some other package); your
package may be more desirable for people who don't want the other
features in my package and who may consider my package 'bloated'. There
could be other reasons also.

I didn't post my comment to say that you package shouldn't be
MELPA-ized, just to add a data-point in consideration, especially since
package `diredc` includes many features that aren't obvious from the
package name.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by SpringHan** [comment]
It doesn't matter. I wrote this package because I don't know there have been a package achieved the preview function.  
Now, since there's a better & powerful package can do it, I think there's no need to add my package into MELPA. Haha.

**Pull request closed without merging**
