### PR TITLE
Add msgpack recipe

### PR DESCRIPTION
**Pull request by xuchunyang**
### Brief summary of what the package does

An Emacs Lisp library for reading and writing [MessagePack](https://msgpack.org/) object

### Direct link to the package repository

https://github.com/xuchunyang/msgpack.el

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

I'm the maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

1. Please use proper indent in the whole Elisp file.

**Comment by xuchunyang** [comment]
> 1. Please use proper indent in the whole Elisp file.

This has been fixed with you PR. I copied that code from json.el and forgot to reindent it.

**Comment by riscy** [comment]
Looks good to me.  Thanks for this!

Minor:
    asscess -> access

**Comment by xuchunyang** [comment]
Thanks. I've fixed the typo.

**Pull request merged**
