### PR TITLE
Add recipe for competitive-programming-snippets

### PR DESCRIPTION
**Pull request by sei40kr**
### Brief summary of what the package does

Competitive Programming snippets for [Yasnippet](https://github.com/joaotavora/yasnippet).

### Direct link to the package repository

https://github.com/sei40kr/competitive-programming-snippets

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. [This](https://github.com/sei40kr/competitive-programming-snippets/blob/6146108c3babdae5a57831354098e4d7cb1a9372/competitive-programming-snippets.el#L51) will cause double-initialisation if people use your autoloaded setup function, so I think you should remove that line. Looks good otherwise.

**Comment by sei40kr** [comment]
@purcell 
I removed ```;;;###autoload``` pragma from initialization.

**Comment by purcell** [comment]
> I removed `;;;###autoload` pragma from initialization.

You didn't, as far as I can see - it's still there. But that's fine. I think [this](https://github.com/sei40kr/competitive-programming-snippets/blob/6146108c3babdae5a57831354098e4d7cb1a9372/competitive-programming-snippets.el#L51) is the line you should delete. Better to have an explicit setup function than to have loading the library cause side effects.

**Comment by mem-YSeong** [comment]
@purcell 
Sorry I had failed to push.
I updated to remove the initialization on load. Please review.
Thanks for your advice.

**Comment by sei40kr** [comment]
@purcell 
Sorry I failed to push the update.
I re-updated the package to remove the initialization on load. Please review.
Thanks for your advice!

https://github.com/sei40kr/competitive-programming-snippets/commit/29e9c0a2e2332caded31190b97f388ffa3a9218b

**Pull request merged**
