### PR TITLE
Recipes: add shroud

### PR DESCRIPTION
**Pull request by o-nly**
Quality: usable; Shroud.el is a user interface for the Shroud password manager

### Brief summary of what the package does

Shroud is a simple password manager using gnupg to encrypt plain
scheme expressions.  This package provides functions for working
with shroud.

### Direct link to the package repository

https://github.com/o-nly/emacs-shroud

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

Not security oriented.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

- You need to add the missing package dependency declaration for `f`.
- Add empty lines between the top-level declarations please.
- Don't use `apply` [when you don't have to](https://github.com/o-nly/emacs-shroud/blob/master/shroud.el#L157).
- Put [all `require` forms](https://github.com/o-nly/emacs-shroud/blob/a43f10032a8fa8403b72026a6f9c9cc192b07142/shroud.el#L197) at the top of the code.
- Why are you defining global functions in a weird way [here](https://github.com/o-nly/emacs-shroud/blob/a43f10032a8fa8403b72026a6f9c9cc192b07142/shroud.el#L207-L212)? Use `cl-letf` or similar to declare local functions.
- There are no docs in the code itself about how to use it: you should put the node about `M-x shroud-bui` in there, but also perhaps consider aliasing that command as `shroud`, since users won't care that it was implemented with `bui`.

Hope that helps!

**Comment by o-nly** [comment]
> Thanks!
> 
> * You need to add the missing package dependency declaration for `f`.

Done.

> * Add empty lines between the top-level declarations please.

Done.

> * Don't use `apply` [when you don't have to](https://github.com/o-nly/emacs-shroud/blob/master/shroud.el#L157).

Thanks, fixed.

> * Put [all `require` forms](https://github.com/o-nly/emacs-shroud/blob/a43f10032a8fa8403b72026a6f9c9cc192b07142/shroud.el#L197) at the top of the code.

Done.

> * Why are you defining global functions in a weird way [here](https://github.com/o-nly/emacs-shroud/blob/a43f10032a8fa8403b72026a6f9c9cc192b07142/shroud.el#L207-L212)? Use `cl-letf` or similar to declare local functions.

Thanks, fixed.

> * There are no docs in the code itself about how to use it: you should put the node about `M-x shroud-bui` in there, but also perhaps consider aliasing that command as `shroud`, since users won't care that it was implemented with `bui`.
> 
> Hope that helps!

Thanks, pushed changes to project repo! :)

**Comment by purcell** [comment]
Super! Sorry for the slow response: this PR is merged now. Welcome to MELPA! :tada:

**Comment by o-nly** [comment]
thanks! woohoo!

**Pull request merged**
