### PR TITLE
Add recipe for flycheck-raku

### PR DESCRIPTION
**Pull request by CIAvash**
### Brief summary of what the package does

Checks Raku programming language syntax using flycheck

### Direct link to the package repository

https://github.com/Raku/flycheck-raku

### Your association with the package

A contributor

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### Additional Notes

Since the name of Perl 6 programming language was changed to Raku, I think `flycheck-perl6` on melpa should be deleted, because it works on `perl6-mode` which no longer exists on melpa(it was replaced with `raku-mode`).

This package is a community fork of a fork of the original [flycheck-perl6](https://github.com/hinrik/flycheck-perl6) by @hinrik.

### CODE REVIEW

**Comment by riscy** [comment]
> Since the name of Perl 6 programming language was changed to Raku, I think flycheck-perl6 on melpa should be deleted, because it works on perl6-mode which no longer exists on melpa(it was replaced with raku-mode).

I think this is reasonable but perhaps @hinrik could weigh in.  Also whether there's any interest in co-maintaining from either party.

> This package is a community fork of a fork of the original flycheck-perl6 by @hinrik.

Per CONTRIBUTING.org, we usually try not to merge forks.  To be clear, I am not so worried that this is a fork of @hinrik's repository, because that repository is out of date and currently incompatible with the current naming.  I am more worried that this is a fork of @widefox's repository.  In order to know how this will affect users, it would be good to know things like: will @widefox's repository continue being developed separately?  Would @widefox want to archive or rename that repository if this were indexed in MELPA?

With all that said, I personally think it makes sense to merge this PR (since its parent org is Raku itself) and remove the old perl6 recipe, but hopefully we can hear back from some of the authors mentioned above.

One last comment I can make on the code is that the dependency on `projectile` could be perceived as a bit heavy, since modern Emacs comes with `project-roots` function builtin and it may not be a user's preference to use projectile.

**Comment by hinrik** [comment]
> > Since the name of Perl 6 programming language was changed to Raku, I think flycheck-perl6 on melpa should be deleted, because it works on perl6-mode which no longer exists on melpa(it was replaced with raku-mode).
> 
> I think this is reasonable but perhaps @hinrik could weigh in. Also whether there's any interest in co-maintaining from either party.

Sounds good to me. I'm not very involved in this project anymore. :+1:

**Comment by CIAvash** [comment]
@riscy I did saw `project-roots`, but I wasn't sure how to use it. I took a look at `project.el` and replaced `projectile` with `project`.

@widefox's package hasn't been published on melpa or anywhere else but GitHub. Is that a problem?

**Comment by widefox** [comment]
OK by me. Getting it into Melpa seems useful to others. I've no plans currently to develop my fork, just say what you'd like it renamed to.

**Comment by riscy** [comment]
Thanks both for getting back so quickly.  @widefox it would probably be clearest if you added a link in the README to the current repository and then archived yours, if that works for you.  Much appreciated. :)

I can merge this and unindex flycheck-perl6.

**Comment by widefox** [comment]
Done as requested.

**Comment by riscy** [comment]
Thank you @widefox  :)

**Pull request merged**
