### PR TITLE
Add recipe for ocaml-eglot

### PR DESCRIPTION
**Pull request by xvw**
### Brief summary of what the package does

Provides an interface to interact with `ocaml-lsp-server` via Eglot. `OCaml-eglot` is an alternative to `merlin` for editing OCaml code (based on LSP).

### Direct link to the package repository

https://github.com/tarides/ocaml-eglot

### Your association with the package

Maintainer (and creator)

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Code looks good - just a couple notes re: licensing below.

- ocaml-eglot-req.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- ocaml-eglot-util.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- ocaml-eglot.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by xvw** [comment]
Thanks a lot, I fix that soon as possible!

**Comment by xvw** [comment]
Done and merged on `main`:
- https://github.com/tarides/ocaml-eglot/blob/main/ocaml-eglot.el#L17
- https://github.com/tarides/ocaml-eglot/blob/main/ocaml-eglot-req.el#L8
- https://github.com/tarides/ocaml-eglot/blob/main/ocaml-eglot-util.el#L8

**Comment by riscy** [comment]
Thank you!

**Pull request merged**
