### PR TITLE
Add recipe for zhcosin/chinese-number

### PR DESCRIPTION
**Pull request by zhcosin**
### Brief summary of what the package does

Converting number format between Arabic and Chinese.

### Direct link to the package repository

https://github.com/zhcosin/chinese-number

### Your association with the package

I am the author and maintainer, and some other has contribute for this package.

### Relevant communications with the upstream package maintainer

None

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR(https://github.com/zhcosin/chinese-number/pull/2)

**Comment by zhcosin** [comment]
I have merged it already.

**Comment by syohex** [comment]
- no autoload cookies
- Public interfaces should use `-` separator, not `--`. And private functions/variables uses `--` separator instead of `-` separator

**Comment by zhcosin** [comment]
Now I had add the autoload commentary at the public interface function, and adjust the separator in function name, thanks for your reminder.

**Comment by syohex** [comment]
I have sent PR(https://github.com/zhcosin/chinese-number/pull/5) about autoload.
Is README updated about interface name ?

**Comment by zhcosin** [comment]
Thanks for your carefulness, and I was very sorry for my carelessness, I have commit a modify fix this problem.

**Comment by syohex** [comment]
Looks good.

**Comment by purcell** [comment]
Thanks. I sent you a fix in https://github.com/zhcosin/chinese-number/pull/6.

You shouldn't really use the `cnum-` prefix here. It's okay if you want to use it internally, because I realise that some of the identifiers are very long, but your public functions at least should all have the `chinese-number-` name prefix.

**Comment by zhcosin** [comment]
Thanks, I will review problems like this after the Chinese National Day.

**Comment by zhcosin** [comment]
Now I fixed the prefix problem by modify almost all function name, use the `chinese-number--` as the prefix for all variables and functions, so some function name was very long.

**Comment by purcell** [comment]
Super, thanks!

**Pull request merged**
