### PR TITLE
Add fill-function-arguments

### PR DESCRIPTION
**Pull request by davidshepherd7**
### Brief summary of what the package does
 Add/remove line breaks between function arguments and similar constructs 

### Direct link to the package repository

https://github.com/davidshepherd7/fill-function-arguments

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Looks handy.

- You're missing a `defgroup` to define your customisation group and place it appropriately in the global hierarchy.
- You can help users by adding an `;;;###autoload` cookie comment for the `-dwim` command.

**Comment by davidshepherd7** [comment]
Ah, thanks for reminding me! For some reason I always seem to forget exactly those two things :disappointed:

**Comment by davidshepherd7** [comment]
Hi, just checking did you forget about this? I've made the two suggested changes. :+1:

**Comment by purcell** [comment]
> Hi, just checking did you forget about this? I've made the two suggested changes.

Nope, I only have time to check in on MELPA approximately weekly right now. Merging... :-)

**Comment by davidshepherd7** [comment]
Oh sorry for bothering you then, I completely understand :slightly_smiling_face: 

Thanks for the code review.

**Pull request merged**
