### PR TITLE
Add the ‘hasky-stack’ package

### PR DESCRIPTION
**Pull request by mrkkrp**
### Brief summary of what the package does

Interface to the Stack Haskell development tool.

### Direct link to the package repository

https://github.com/hasky-mode/hasky-stack

### Your association with the package

Author and maintainer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mrkkrp** [comment]
Remaining issues from `package-lint`:

> 8:52: warning: Use a non-snapshot version number for dependency on "magit-popup" if possible.

I think `magit-popup` is versioned in this "snapshot" fashion and it's not possible to specify a non-snapshot version, although I may be wrong.

/cc @tarsius

**Comment by tarsius** [comment]
> I think magit-popup is versioned in this "snapshot" fashion and it's not possible to specify a non-snapshot version, although I may be wrong.

When I create a release I set the version to something like `2.*` and in the very next version commit I set the "version" to something like `2017....`. So you should use non-snapshot version numbers.

**Comment by mrkkrp** [comment]
OK, done.

**Comment by purcell** [comment]
Nice!

**Pull request merged**
