### PR TITLE
Add ergoemacs-status package

### PR DESCRIPTION
**Pull request by mattfidler**
Add ergoemacs-status package.

See https://github.com/ergoemacs/ergoemacs-status

### CODE REVIEW

**Comment by mattfidler** [comment]
Just so you know:
- I am the maintainer. 
- The ergoemacs-status package maintainer.
- ergoemacs-status is an adaptive mode-line

**Comment by purcell** [comment]
Thanks. Sent a fix in https://github.com/ergoemacs/ergoemacs-status/pull/2.

Please remove the unnecessary `:files` spec from the recipe, ideally by amending the recipe commit and force-pushing it back here.

Looks good otherwise.

**Comment by mattfidler** [comment]
It was changed

**Comment by purcell** [comment]
> It was changed

Thanks. I see the PR I submitted has been merged, but I don't see the requested change to the recipe.

**Comment by mattfidler** [comment]
Ok.  I'm unsure why it removed the files twice, but it should be OK.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
