### PR TITLE
Add recipe for helm-treemacs-icons

### PR DESCRIPTION
**Pull request by yyoncho**
### Brief summary of what the package does

Integration between treemacs icons and helm(++).

### Direct link to the package repository

https://github.com/yyoncho/helm-treemacs-icons

### Your association with the package

author

### Relevant communications with the upstream package maintainer

none needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
Note: I have used it - it has one false negative for the name of the package containing "emacs"
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick pass --

### helm-treemacs-icons.el ###

byte-compile-file (using Emacs 26.3):
```
helm-treemacs-icons.el:35:1:Warning: defcustom for
    `helm-treemacs-icons-mode->icon' fails to specify type
helm-treemacs-icons.el:35:1:Warning: defcustom for
    `helm-treemacs-icons-mode->icon' fails to specify containing group
helm-treemacs-icons.el:35:1:Warning: defcustom for
    `helm-treemacs-icons-mode->icon' fails to specify type
helm-treemacs-icons.el:35:1:Warning: defcustom for
    `helm-treemacs-icons-mode->icon' fails to specify containing group
```
You can clean up the byte-compiler with, e.g.:
```elisp
(defcustom helm-treemacs-icons-mode->icon
  '((dired-mode . dir-open)
    (emacs-lisp-mode . "el")
    (spacemacs-buffer-mode . "el"))
  "Lookup Emacs mode -> `treemacs' icon key."
  :type '(alist :key-type symbol :value-type sexp)
  :group 'treemacs
)
```
but you may also want to `defgroup

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-treemacs-icons.el:39: Name emacs should appear capitalized as Emacs
Warning (emacs): 
helm-treemacs-icons.el:116: First sentence should end with punctuation
```

package-lint-current-buffer (using version 20200419.406):
```
2 issues found:
1:0: warning: The word "emacs" is redundant in Emacs package names.
92:28: warning: Closing parens should not be wrapped onto new lines.
```
First is a false positive (treemacs), but second can be addressed.

**Comment by riscy** [comment]
I also notice you don't package-requires on `helm` -- should you?

**Comment by yyoncho** [comment]
> I also notice you don't package-requires on `helm` -- should you?

No, we shouldn't - if we require helm it may instantiate its sources before we have set the advice and also, there is no point to require it since the code works without loading helm.

I have pushed a new change, so it is ready to be re-reviewed.

**Comment by yyoncho** [comment]
I will rename the package to helm-icons and provide integration with all-the-icons - thus cancelling this request.

**Pull request closed without merging**
