### PR TITLE
Add fastdef recipe

### PR DESCRIPTION
**Pull request by redguardtoo**
fastdef insert terminology from google top search results.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Some quick thoughts:
- Please depend on `ivy`, not `swiper`: see https://melpa.org/#/ivy
- The `:files` spec shouldn't be necessary here. Either delete the `-pkg.el` file, or include them both in the package, by removing the `:files` spec.
- `fastdef` isn't a very obvious name. Why not something like `google-define` or `search-define`?

**Comment by redguardtoo** [comment]
thanks for head up. I update fastdef and recipe.
I'd rather keep the original name because I have plan to make fastdef have more ways to get the definition of a term.

**Comment by purcell** [comment]
Okay. But now you need to delete the `-pkg.el` file: it's not needed by MELPA, but when present it overrides the metadata in the `fastdef.el` file, which means your package dependencies will disappear.

**Comment by redguardtoo** [comment]
I deleted the *-pkg.el

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
