### PR TITLE
Add recipe for djinni-mode

### PR DESCRIPTION
**Pull request by danielmartin**
### Brief summary of what the package does

Major mode for editing Djinni files. Djinni is an IDL for generating interfaces in C++, Objective C and Java. 

### Direct link to the package repository

https://github.com/danielmartin/djinni-mode

### Your association with the package

I'm the creator and maintainer of this package.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by danielmartin** [comment]
Thanks for the review, @riscy! I've addressed your comments in https://github.com/danielmartin/djinni-mode/commit/f1716ba7dd81285f28c49ea555ff4885ef9f10c4

**Comment by purcell** [comment]
Thanks, mostly looks great. Just a few little comments:
- You should provide a `defgroup` to define the `djinni` custom group you reference in your `defcustom`s
- You're making changes to the global values of `compile-command` and `compilation-error-regexp-alist` etc. every time a buffer is opened. I don't think that's your intention. Instead: a) make your own compilation command, and bind that to `C-c C-c` instead of `compile`, which will leave `compile` usable for other purposes; b) just modify `compilation-error-regexp-alist-alist` globally, and; c) add `djinni` to `compilation-error-regexp-alist` buffer-locally in your compilation buffer. There's a useful `define-compilation-mode` macro.

**Comment by danielmartin** [comment]
Thanks for the review, @purcell ! I've addressed your comments in https://github.com/danielmartin/djinni-mode/commit/d5ba87e8beb4449647d46cb4e2d9cf5d681275a4

**Comment by purcell** [comment]
Looks great, and I'll merge now. Note that you can (and probably should) just modify `compilation-error-regexp-alist-alist` at the top-level, because it's really just a bag of shorthand names for sets of patterns.

**Pull request merged**
