### PR TITLE
Added outline-toc recipe.

### PR DESCRIPTION
**Pull request by abingham**
### Brief summary of what the package does

Adds a table of contents sidebar for outline-mode compatible buffers.

### Direct link to the package repository

https://github.com/abingham/outline-toc.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- Don't ever hard-code a font family or size. Just make `outline-toc-font-face` an empty definition, then users can customise or theme it as desired.
- "for Emacs" in docstrings is redundant.
- Don't define your own `outline-toc-current-section` face colours: instead, `:inherit highlight`.
- You've got `defcustoms` with `--` in their name, but the `--` denotes private vars/functions, so this is contradictory. If they're really for end-user tweaking, use `-` instead of `--`.
- Re. `;; TODO: How do we specify "for all outline-mode" docs? Outline-mode is minor, I think...` -- there's `outline-mode-hook`, and.. the `outline-mode` variable.
- Minor mode lighters should have a leading space, so `"OToc"` => `" OToc"`

Hope that helps!

**Comment by abingham** [comment]
Thanks for the feedback. I've worked them into the latest version. The code is still a bit of a mess, but I plan to clean it up as I work with the package a bit more.

**Comment by alphapapa** [comment]
@abingham You might be able to build a lot of your code on top of `navi-mode`.  I think it already handles some things like that.  Although it's not structured as a library, it might still be a useful building block.

**Comment by abingham** [comment]
@alphapapa Actually it looks like `imenu-list` might do almost everything I
need already. With the exception of synchronizing with navigation in the
master document, it provides all of the features I want in outline-toc. But
when I find some time to work on outline-toc some more, I'll definitely
look at navi-mode again.

**Pull request merged**
