### PR TITLE
New recipe: magrant

### PR DESCRIPTION
**Pull request by p3r7**
### Brief summary of what the package does

magrant provides an interface similar to magit for [Vagrant](https://www.vagrantup.com/).

It uses the same underlying library ([transient](https://github.com/magit/transient)) for turning a command line program into an Emacs interface.

Other packages are built around the same principle like [kubel](https://github.com/abrochard/kubel) and [docker](https://github.com/Silex/docker.el).

### Direct link to the package repository

https://github.com/p3r7/magrant

### Your association with the package

Maintainer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by p3r7** [comment]
Please note that the code is heavily inspired by the structure of package [docker](https://github.com/Silex/docker.el).

It's the first time that I truly make a package split into several files.
I'm not 100% sure about certain conventions.

**Package header**

I put the proper full package header in the main entry point, [magrant.el](https://github.com/p3r7/magrant/blob/master/magrant.el) and not in the other sub-files. `package-lint-current-buffer` complains a bit when analyzing the children files due to this.

**File name and function prefix**

I respected the convention of having all the symbols in a file be prefixed with the file name.

The only exception is [magrant-core.el](https://github.com/p3r7/magrant/blob/master/magrant-core.el).

Package docker [does the same thing](https://github.com/Silex/docker.el/blob/master/docker-core.el).
I guess that it had those "core" declarations in the [main file](https://github.com/Silex/docker.el/blob/master/docker.el) but that caused circular dependency issues. Hence the need to extract them to a sub-file.

There would be no issue in renaming the symbols in this file with the `magrant-core` if you deem it necessary.

**Comment by purcell** [comment]
> package-lint-current-buffer complains a bit when analyzing the children files due to this.

You can set `package-lint-main-file` in `.dir-locals.el` to handle this. :-)

**Comment by p3r7** [comment]
Thanks for the tip!

`package-lint` is now happy.

**Comment by riscy** [comment]
Looks like a good multi-file package!  I just have a few minor things:

- Summary line "Emacs interface to Vagrant commands on boxes" doesn't need to contain Emacs
- magrant-utils.el#L48: Consider `unless ...` instead of `when (null ...)`
- confort -> comfort
- The empty `;;; Commentary` blocks in some files could be filled in with their summary line (I don't see why not)

**Comment by p3r7** [comment]
Thanks.

All the last comments where addressed in https://github.com/p3r7/magrant/commit/83a6856d787f9a6519cd8fbc6c829d4000539d9f and https://github.com/p3r7/magrant/commit/7578ba68502a6ebe71fd547ed4c9e851ffbd6682.

**Pull request merged**
