### PR TITLE
Add onlyonce.el recipe

### PR DESCRIPTION
**Pull request by Kyure-A**
### Brief summary of what the package does

Executing a function that you want to **only once** the first time

### Direct link to the package repository

https://github.com/Kyure-A/onlyonce.el

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

 **None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
Is this necessary?:

https://github.com/Kyure-A/onlyonce.el/blob/0484b57ca5207bf155423828a0fb84d02d859f0b/onlyonce.el#L52-L53

**Comment by Kyure-A** [comment]
When I wrote this package previously, I think the description you pointed out was necessary. However, when I think about it, it is unnecessary if it is loaded properly in init.el first. I will fix it.

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`onlyonce.el` with byte-compile using Emacs 29.1:
```
onlyonce.el:32:2: Error: Cannot open load file: No such file or directory, s
```
I believe `s` needs to be added to the Package-Requires.

`onlyonce.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- The `;;; Commentary` for this file is much wider than 80 characters
- onlyonce.el#L40: Customizable variables shouldn't be private
- onlyonce.el#L104: `unless` body does not need to be wrapped in `progn`
```

**Comment by Kyure-A** [comment]
I think I have corrected the points you have raised. I don't think it is much of a problem that the docstring of a function exceeds 80 characters, should I fix it?

**Comment by riscy** [comment]
Yes, some of these docstrings are even more than 150 characters long.   The Emacs online help facility will not word wrap for users whose windows are not this wide.  The only time you would want to go longer than the typical 80 characters is if you had a piece of code or a URL that needed to be more than 80 characters long, but these are exceptional cases.

Also note that the latest has unescaped single quotes, which as of Emacs 29 have been promoted to byte-compile warnings.   These should be cleaned up too -- here's the latest:

`onlyonce.el` with byte-compile using Emacs 29.1:
```
onlyonce.el:40:2: Warning: custom-declare-variable `onlyonce-executable-list' docstring wider than 80 characters
onlyonce.el:46:2: Warning: custom-declare-variable `onlyonce-executed-p' docstring wider than 80 characters
onlyonce.el:46:2: Warning: custom-declare-variable `onlyonce-executed-p' docstring has wrong usage of unescaped single quotes (use \= or different quoting)
In onlyonce--normalize-command-from-string:
onlyonce.el:52:2: Warning: docstring wider than 80 characters
onlyonce.el:52:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
In onlyonce--normalize-command-from-list:
onlyonce.el:61:2: Warning: docstring wider than 80 characters
onlyonce.el:61:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
In onlyonce--normalize-command-from-symbol:
onlyonce.el:78:2: Warning: docstring wider than 80 characters
onlyonce.el:78:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
In onlyonce--normalize-command:
onlyonce.el:83:2: Warning: docstring wider than 80 characters
onlyonce.el:83:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
In onlyonce-add:
onlyonce.el:94:2: Warning: docstring wider than 80 characters
```

**Comment by alphapapa** [comment]
I hate to be grinchy, but this appears to be the kind of package that will nearly never be used and couldn't be recommended to other users.  It isn't idiomatic Elisp at all.  The problem it solves should generally be solved by other means (e.g. using appropriate constructs, which are idempotent).  Using this package would generally indicate that the user doesn't understand how to do what it does more correctly within Emacs, which leaves this package as a kind of ugly hack.  Not that I have the authority, but were it up to me, I would NAK this for inclusion in MELPA.

@Kyure-A I don't mean to denigrate your contribution.  Rather, there are much better and simpler ways to solve the problem you're trying to solve with this library, and it wouldn't be good to encourage other users to solve it like this library does.  So this library shouldn't be added to MELPA as a nearly permanent example that others may stumble upon.

If you'd like to learn more about Emacs and Elisp and better ways to solve this problem, ask around on, e.g. r/emacs on Reddit, and experienced users can help teach you.

**Comment by Kyure-A** [comment]
I've received similar criticism before, but when I think about it again, it's really true. It wasn't a very good package. I'm no longer feeling like I can maintain this ugly package, so I'm going to close this pull request. Thanks to all the maintainers!

**Pull request closed without merging**
