### PR TITLE
Add evil-org-improved

### PR DESCRIPTION
**Pull request by Somelauw**
### Brief summary of what the package does

Integrate evil-mode and org-mode by defining key bindings and motions.

### Direct link to the package repository

https://github.com/Somelauw/evil-org-improved

### Your association with the package

I'm the maintainer. It was originally forked from https://github.com/edwtjo/evil-org-mode by @edwtjo, but by now it has diverted significantly from the original.

### Relevant communications with the upstream package maintainer

The discussion about forking started here https://github.com/edwtjo/evil-org-mode/issues/39

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ ] I've used package-lint to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
There are some warnings if that matters, but most of them were from before I forked it. I'll try to get rid of them.
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
You can't use the same identifiers in a forked package, sorry, so you'll need to change all your `evil-org-*` to `evil-org-improved-*`. Every package must have a unique namespace.

Forks, in general, are something we try hard to avoid, because they're a confusing outcome for the community.

The *best* solution here would be if @edwtjo is happy to nominate your fork as the new official maintained version of `evil-org`, which seems like a good idea to me. You'd then rename your fork back to `evil-org.el`, and we would update our existing `evil-org` recipe to point at your fork. How about it, @edwtjo ?

**Comment by Somelauw** [comment]
@purcell hmm, I'm not not yet sure about the namespace title, because "evil-org-improved-" is a bit long.

**Comment by edwtjo** [comment]
Sure thing, what do you guys need from me, an updated README.md in my repo?

**Comment by edkolev** [comment]
@Somelauw do you think the dependency on evil-leader can be removed or at least made optional?

**Comment by Somelauw** [comment]
@edkolev It should already be an optional dependency. Let me know if you are unable to use it without evil-leader. I'll remove it from "Package-Requires" in the comment later.

**Comment by Somelauw** [comment]
I have renamed evil-org-improved to evil-org. If I understand correctly, I should make a new pull request that updates the evil-org recipe.

**Comment by purcell** [comment]
> I have renamed evil-org-improved to evil-org. If I understand correctly, I should make a new pull request that updates the evil-org recipe.

Yes please, or push different commits to this pull request branch.

You might consider recreating your repo as a fork of @edwtjo's original `evil-org-mode`, to make its history a little more clear.

Once we've updated the recipe then yes, @edwtjo, it'd be nice if you added a note to your repo.

**Comment by Somelauw** [comment]
On the suggestion of @purcell, I have recreated the repo as https://github.com/Somelauw/evil-org-mode.
This has been done in a new pull request https://github.com/melpa/melpa/pull/4740 (already merged).

@edwtjo Can you add a note that links to https://github.com/Somelauw/evil-org-mode?

**Comment by edwtjo** [comment]
Updated README in the old repo, thanks!

**Comment by edkolev** [comment]
Sorry for polluting this thread.

@Somelauw issues aren't enabled in your forked repo. I wanted to open an issue to share some recommendations, like:
- I think having `use-package` install instructions is a good improvement, something like:
```
(use-package evil-org
  :ensure t
  :after org
  :config
  (add-hook 'org-mode-hook 'evil-org-mode))
```
- the README should list all keybindings, no need to click link "Full overview of bindings and configuration" to keythemes.org
- not all keybindings are clear to me, e.g. I need to check the source for `evil-org-delete-char` to see what it does -- users should be able to most if not all information from the README

Thanks for this package

**Comment by Somelauw** [comment]
@edkolev Thanks. I have enabled issues.

> - I think having use-package install instructions is a good improvement, something like:

They look good to me. I'll add them.

I'll have to think about how to address your other points, because I want to documentation to be complete, but not overwhelming. In org-mode it's easy to fold information, but on Github everything appears on a single page.

**Pull request closed without merging**
