### PR TITLE
Add a recipe for alda-mode

### PR DESCRIPTION
**Pull request by jgkamat**
I created `alda-mode` a major mode for emacs which helps with editing [alda source code files](https://github.com/alda-lang/alda). Here is the information requested in your readme.

- [Link to source repository](https://github.com/jgkamat/alda-mode)
- Association: Creator

This is still a WIP, but the basic functionality is complete (ive tested out everything according to the readme). This is my first time doing anything serious with elisp, so let me know if there are any issues. Thanks!

### CODE REVIEW

**Comment by syohex** [comment]
- `setq-local` was introduced at Emacs 24.3, however you can use `setq` for `comment-start`, `comment-end`, `indent-line-function`, because they are already declared as buffer local variable.(or use `set` + `make-local-variable`)
- Missing **autoload cookie** for `alda-mode` and `auto-mode-alist` setting

**Comment by jgkamat** [comment]
Hi, thanks for your review! I've made the requested changes [in this commit](https://github.com/jgkamat/alda-mode/commit/7b599b15f8061e71af22d01edcef534c8dda0150).

**Comment by purcell** [comment]
Thanks, looks good. Sent you a couple more small fixes, then we're good to go. :-)

**Comment by jgkamat** [comment]
just merged

Its pretty cool that this is a code review too, thanks for helping out! :smile:

**Comment by purcell** [comment]
Happy to help.

**Comment by jgkamat** [comment]
Any chance this can be merged if its good now?

**Comment by purcell** [comment]
Sure, sorry for the delay - done!

**Pull request merged**
