### PR TITLE
Add Easy Buffer

### PR DESCRIPTION
**Pull request by onixie**
Easy Buffer provides key bindings for accessing various buffers easily.

### Brief summary of what the package does

Easy Buffer provides key bindings for opening frequently used buffers and easy way to close buffers.

### Direct link to the package repository

https://github.com/onixie/easy-fwb

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

A little feedback:

1.  Loading the package shouldn't bind keys in `Buffer-menu-mode-map`.  That is for users to do in their config.
3.  Instead of `(eval-when-compile (require 'cl))`, use `(require 'cl-lib)`.
3.  Compared to easy-window and easy-frame, I think this isn't generally suitable for publishing as a package.  It's essentially these 4 commands and some key bindings:
```el
(defun easy-buffer-switch-to-scratch ()
  "Switch to *scratch* buffer."
  (interactive)
  (switch-to-buffer "*scratch*"))

(defun easy-buffer-switch-to-messages ()
  "Switch to *Messages* buffer."
  (interactive)
  (switch-to-buffer "*Messages*"))

(defun easy-buffer-switch-to-.emacs ()
  "Open .emacs file buffer."
  (interactive)
  (find-file "~/.emacs"))

(defun easy-buffer-switch-to-calendar ()
  "Switch to *Calendar* buffer."
  (interactive)
  (if (or (not (fboundp 'calendar-exit))
	  (null (calendar-exit)))
      (calendar)))
```

**Comment by onixie** [comment]
Thanks for your kind review. I'll cancel this PR.

**Comment by alphapapa** [comment]
@onixie Note that I am not a MELPA maintainer, just an occasional contributor who tries to give back by reviewing some packages ahead of their "official" reviews.  So my opinion is not a decision by MELPA.  :)  However, given their feedback on similar packages in the past, I think they would say the same here.

**Comment by casouri** [comment]
You can put it on Emacs Wiki. They would welcome your contribute.

**Comment by onixie** [comment]
Thanks for your advices, guys.

**Pull request closed without merging**
