### PR TITLE
Add recipe for exercism

### PR DESCRIPTION
**Pull request by anonimitoraf**
### Brief summary of what the package does

Integration for https://exercism.org. It streamlines doing exercises (within Emacs of course!).

### Direct link to the package repository

https://github.com/anonimitoraf/exercism.el

### Your association with the package

Author/maintainer

### Relevant communications with the upstream package maintainer

None needed as I am the maintainer

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Checklist looks great.  A couple other small issues:

- In `exercism-open-exercise`, no `progn` is required for the "else" part of an `if` block
- It might make sense to wrap `exercism-directory` with an `(expand-file-name ...)` which I believe might be better-behaved with Windows systems, but I haven't got a machine to test that on
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to exercism.el

**Comment by anonimitoraf** [comment]
Thanks so much for the quick reply and the helpful feedback! I've addressed them in my latest commits.

Thanks!

**Comment by riscy** [comment]
Thanks!  This looks about ready to go, but I just now noticed the use of `shell-command-to-string` -- for these it's a good idea to run the arguments through `shell-quote-argument` just in case someone inadvertently puts shell control characters in their API token or exercism slug, for example.

**Comment by anonimitoraf** [comment]
Cool thanks for raising that! Should be fixed now 😄

**Comment by riscy** [comment]
I'd recommend "Unofficial https://exercism.org integration" as a summary line instead of `Emacs (unofficial) integration for https://exercism.org`; the latter is a bit redundant in specifying Emacs.  Not a blocker, though.

**Comment by anonimitoraf** [comment]
Ah yes! Thanks for the suggestion and for mergin!

**Pull request merged**
