### PR TITLE
Add rbs-mode recipe

### PR DESCRIPTION
**Pull request by ybiquitous**
### Brief summary of what the package does

`rbs-mode` is a major mode for RBS (a type signature language for Ruby).

### Direct link to the package repository

https://github.com/ybiquitous/rbs-mode

### Your association with the package

I am the:

- package author
- package maintainer
- MELPA recipe author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, I'm excited about rbs.  The checklist look great, but one thing I notice is that you have defined `comment-start` and `comment-end` but comments don't seem to be catching any syntax highlighting:

image

Also, I can see users will have to manually indent their rbs files when they use this major mode.  I realize how involved the indentation code for such a syntax is, so I don't think this is a blocker -- but definitely something I hope is at the top of the todo list.

**Comment by ybiquitous** [comment]
@riscy Thank you for the feedback!

> one thing I notice is that you have defined `comment-start` and `comment-end` but comments don't seem to be catching any syntax highlighting:

I've [enabled `comment-use-syntax`](https://github.com/ybiquitous/rbs-mode/pull/4), so could you please check it again? In my environment, it seems to work well:

image

> I realize how involved the indentation code for such a syntax is, so I don't think this is a blocker -- but definitely something I hope is at the top of the todo list.

Yes, I agree. I've created the [issue to support smart indenting](https://github.com/ybiquitous/rbs-mode/issues/3), but it is a hard task... 😅

**Comment by riscy** [comment]
Thanks, comments work great for me now.  A bit short on time this weekend but I had another thought about the indentation and thought it would be useful not to fall back on Emacs's default indent function (which definitely doesn't follow anything close to a ruby convention), but to instead add something like this, which is a little better behaved in this context:
```
(defcustom rbs-indent-offset 2
  "Size of one indentation step."
  :type 'integer
  :safe 'intergerp)
  
(defun rbs-indent-line ()
  (insert (make-string rbs-indent-offset ? )))
```

**Comment by ybiquitous** [comment]
@riscy Thank you so much for your kindness!

I have implemented a simple indentation based on your idea.
https://github.com/ybiquitous/rbs-mode/releases/tag/v0.3.0

Though the implementation is still naive, I think it's a bit better than before. 😅

**Comment by riscy** [comment]
Great, thanks!  I seem to remember Matsumoto saying something along the lines of: if he couldn't get the `begin`/`end` syntax to indent properly in Emacs (a nontrivial feat) he may have given up on that particular syntax.  So the fact that he was able to do so sort of shaped Ruby as a language.  I can't find a link now, so I may be misremembering.  In any case, this looks good to merge.

**Comment by ybiquitous** [comment]
@riscy Thank you for the review and merge! 🙌🏼 

Maybe I’ve never heard of it before, but the indentation is surely difficult... 😓

**Pull request merged**
