### PR TITLE
Add recipe for russian-techwriter

### PR DESCRIPTION
**Pull request by dunmaksim**
### Brief summary of what the package does

Input method for russian techwriters

### Direct link to the package repository

https://github.com/dunmaksim/emacs-russian-techwriter-input-method

### Your association with the package

I am maintainer.

### Relevant communications with the upstream package maintainer

None

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

- russian-techwriter.el#L4: Have you done the paperwork to assign this copyright?
- russian-techwriter.el#L10: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- Your `;;; Commentary` looks to simply be the GPL license boilerplate; you want to put this license boilerplate *above* the Commentary and write distinct commentary that describes the package -- e.g. an expansion of "Input method for russians technical writers". 
- Is there a relationship (or overlap) between this package and the Emacs-builtin functions in cyril-util.el or cyrillic.el?  You may already be aware of these libraries, but I thought I'd double-check

**Comment by dunmaksim** [comment]
Hello!

Thank you for review!

Me updated package `russian-techwriter`. Please, review this one more time.

My package do not have relationship with `cyril-util.el` and `cyrillic.el`, and used for typing special chars in russian keyboard layout without using `(inser-char)` function:

| Character | Default EMACS input type / `russian-computer` | `russian-typewriter` |
|-----------|-----------------------------------------------|----------------------|
| «         | **[C-x 8 <]**                                 | **[/ < <]**          |
| »         | **[C-x 8 >]**                                 | **[/ > >]**          |
| §         | **[C-x 8 RET "SECTION SIGN" RET]**            | **[/ p a]**          |
| €         | **[C-x 8 RET "EURO SIGN" RET]**               | **[/ e u]**          |

**Comment by riscy** [comment]
Thanks for checking on cyril-util/cyrillic.el.

The Commentary is improved, but you removed the license boilerplate from the file -- you should put the license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) somewhere above your `;;; Commentary` section.

This is a small point, but I also recommend changing your summary line from `Input method for russians technical writers` to `Input methods for Russian technical writers`

**Comment by dunmaksim** [comment]
English is not my native language, excuse my typing errors and thanks for fixing.

* [X] Added license boilerplate and SPDX-License-Identifier into `russian-techwriter.el`.
* [X] Fixed typing error in package summary.
* [X] Added info about package creation date.

**Comment by riscy** [comment]
Looks great -- thanks for accommodating.

**Pull request merged**
