### PR TITLE
Add mldoc recipe

### PR DESCRIPTION
**Pull request by zonuexe**
### Brief summary of what the package does

MLDoc is an extension of ElDoc with a function definition helper and a multiple configuration mechanism.

### Direct link to the package repository

https://github.com/emacs-php/mldoc

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Your minor mode declaration `(define-minor-mode mldoc-mode ...` should handle toggling the mode both off and on, but at the moment only appears to handle turning the mode on.  (See [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Minor-Modes.html)).  The automatic turning on of eldoc presents an interesting issue -- should eldoc be turned (back) off when your minor mode is toggled off?  Should it remain on?  I'll leave that part up to you.

In your docstrings, the ``` `backtick/apostrophe' ```-style quoting is typically just used to wrap symbols (and in that way creates hyperlinks in the online help).  So for example this:
```elisp
  "Return propertized string by `ARGS' list, `CURRENT-ARG', `ARG-SEPARATOR' and `ARG-SPEC'."
```
Should probably be written:
```elisp
  "Return propertized string by ARGS list, CURRENT-ARG, ARG-SEPARATOR and ARG-SPEC."
```
and
```elisp
  "Return list for function `propertize' by `PROPERTIZER' alist."
```
Should be written:
```elisp
  "Return list for function `propertize' by PROPERTIZER alist."
```
(Emacs will automatically detect that these capitalized forms are part of your function signature and highlight them in the online help as well).

Hope that helps!

**Comment by zonuexe** [comment]
@riscy Thank you, I fixed.

**Comment by riscy** [comment]
Thanks - I've had some time to look a little more deeply at this.  Just as a general code thing, I notice I'm having trouble evaluating your buffer due to the definition of the minor mode.  It looks like if you don't pass _any_ keyword arguments (e.g. `:group` or `:lighter`) then the arguments "init-value, lighter, and keymap" must be provided.  So I'd recommend supplying `:group` and potentially a customizable `:lighter` to your minor mode to make sure that block is evaluable.

Hopefully that's helpful...

Further, I'm reading your documentation and I am having trouble understanding the workflow for this.  Maybe you can clarify -- is it up to a developer to write additional code in order to support mldoc-style documentation?  Your README has an example, but I am having trouble seeing things end-to-end.

**Comment by tarsius** [comment]
Closing due to inactivity.
Let us know when you are ready so that we can reopen and finish the review.

**Pull request closed without merging**
