### PR TITLE
Add `symbol-navigation-hydra` recipe

### PR DESCRIPTION
**Pull request by bgwines**
### Brief summary of what the package does

This is a hydra inspired by the Spacemacs AHS Transient State. It's a tool for navigating around and acting upon instances of a symbol (e.g. a function name or a keyword) within a specified range, which can be adjusted. It has some functionality that the Spacemacs hydra does not.

There's a gif demoing the functionality in the repo README.

### Direct link to the package repository

https://github.com/bgwines/symbol-navigation-hydra

### Your association with the package

I'm the author (and am pretty new to Emacs and writing Elisp :)).

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

### symbol-navigation-hydra.el ###

byte-compile (using Emacs 26.3):
```
symbol-navigation-hydra.el:447:1:Warning: the following functions are not
    known to be defined: symbol-navigation-hydra-is-active,
    symbol-navigation-hydra-darken-plugin-face,
    symbol-navigation-hydra-plugin-color,
    symbol-navigation-hydra-get-active-xy,
    symbol-navigation-hydra-plugin-component, iedit-mode,
    iedit-restrict-region, helm-do-ag, projectile-project-root
```
It is better if the elisp byte-compiles cleanly, so -- on first glance -- at least some of those functions should simply be defined at the top level, rather than inlined inside another defun.

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200616.2257):
- No issues!

Suggestions/experimental static checks:
- symbol-navigation-hydra.el#L153: It's safer to sharp-quote function names; use `#'`
- symbol-navigation-hydra.el#L24: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by bgwines** [comment]
Thank you so much for the feedback! I've addressed it in https://github.com/bgwines/symbol-navigation-hydra/commit/854b3d8eaf70b1b531c73e906f529e75949d928f?w=1.

My apologies; I got distracted and also fixed some line breaks to bring things under 80 characters. Should've done that in a separate commit to make it easier for you to see the changes. I'd be happy to split that up if you'd like.

**Comment by riscy** [comment]
> Thank you so much for the feedback! I've addressed it in bgwines/symbol-navigation-hydra@854b3d8?w=1. Really sorry about the unclean compilation, don't know what happened there since I checked the checkbox...

Don't worry, it happens.  :) flycheck-mode is handy for checking these in real-time, if you're not using it on your elisp files.

Another thing I will check -- I notice `ahs-plugin-bod-face` (and I'm not familiar with ahs-plugin) and it seems like maybe it should be `body`?  Similarly with `ahs-plugin-defalt-face` which should probably be `default`.  Everything else looks good, so I think it's a quick merge after we hear back from you about that.

I appreciate the .gif.  I'm guilty of this in some of my own repos too, but it may be a good idea to move the ~4MB gif onto an image hosting service or even just another branch.  4MB isn't a big deal but it's large enough for me to mention it.  Note that MELPA will not send downstream users the gif, but people who are installing with a package installer like straight.el will still have to download the gif.

**Comment by bgwines** [comment]
thanks for the feedback!

regarding `ahs-plugin-bod-face` and `ahs-plugin-defalt-face`, these are actually variables exposed by the package I am wrapping:

https://github.com/mhayashi1120/auto-highlight-symbol-mode/blob/master/auto-highlight-symbol.el#L419

and

https://github.com/mhayashi1120/auto-highlight-symbol-mode/blob/master/auto-highlight-symbol.el#L407

(huh, expected Github to preview that code for you here), so I don't think I can rename them, but please let me know if there is another way for me to address this :)

> but people who are installing with a package installer like straight.el will still have to download the gif

oh, shoot; that makes total sense. I'll investigate this and make the change accordingly. Thanks for bringing it up!

**Comment by bgwines** [comment]
on a separate note, I am currently working on adding a few more heads to the hydra for some multiple cursors stuff; should be ready in a day or two. I don't want to burden you with extra code review, but if you would like to provide feedback / if I should be soliciting review for code changes at a time so close to submitting the recipe here, I'd be happy to at-mention you in the commit for that. Thanks so much either way!

**Comment by riscy** [comment]
> I'd be happy to at-mention you in the commit for that. Thanks so much either way!

Yep, that would be fine. :)  I'm eating my hat about the ahs face names.

And welcome to MELPA!

**Comment by bgwines** [comment]
thank you ☺️

**Pull request merged**
