### PR TITLE
recipes/plain-org-wiki: Add plain-org-wiki

### PR DESCRIPTION
**Pull request by abo-abo**
### Brief summary of what the package does

Quickly browse or create Org files.

### Direct link to the package repository

https://github.com/abo-abo/plain-org-wiki

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Before a closer look, please check the following:

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
No issues found.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems)
(The following assumes lexical binding is enabled)
```
plain-org-wiki.el:63:1:Warning: Unused lexical variable `ffip-project-root'

In end of data:
plain-org-wiki.el:115:1:Warning: the function `ffip-project-search' is not
    known to be defined.
```

Added miscellaneous hints (automated):
- plain-org-wiki.el#L23: Prefer `https` over `http` (if possible)

**Comment by abo-abo** [comment]
@riscy Thanks, fixed.

**Comment by riscy** [comment]
Thanks!

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
1 issue found:
1:79: warning: You should depend on (emacs "24") if you need lexical-binding.
```
Sorry about this, my message up there should mention the Emacs 24 dependency required.

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
plain-org-wiki.el:117:1:Warning: the function `ffip-project-search' is not
    known to be defined.
```
One way to address this one is to depend on `(find-file-in-project "5.7.7")` for example.  So altogether your `Package-Requires` would read like:
```elisp
;; Package-Requires: ((emacs "24") (find-file-in-project "5.7.7"))
```

Another thing I notice is that `(require 'helm)` is buried in `plain-org-wiki-helm`, but you could also soft-require it using `(require helm nil t) (declare-function helm "ext:helm.el")`

**Comment by riscy** [comment]
Hi!  I saw [your commit](https://github.com/abo-abo/plain-org-wiki/commit/e246b65dfecb94758cb97493f368ea52047c5f8a#diff-109a883063be58ae8183b9d358084664R8) -- feel free to ping when you're ready for another pass.  At this very moment it looks like you still need a `require` on `find-file-in-project`.

**Comment by abo-abo** [comment]
Requiring `find-file-in-project` is not essential to the functionality of the package, in my opinion.

**Comment by riscy** [comment]
That's fair, but your elisp should byte-compile cleanly:
```
In end of data:
plain-org-wiki.el:118:1:Warning: the function `ffip-project-search' is not
    known to be defined.
```
and your function `plain-org-wiki-files-recursive` calls `ffip-project-search`.

**Comment by abo-abo** [comment]
OK, it should now byte compile cleanly.

**Comment by purcell** [comment]
This is missing a package dependency declaration [for `ivy`](https://github.com/abo-abo/plain-org-wiki/blob/5b3ea15507f0e42c4210495480fe566b398460b9/plain-org-wiki.el#L33).

> Another thing I notice is that `(require 'helm)` is buried in `plain-org-wiki-helm`, but you could also soft-require it using `(require helm nil t) (declare-function helm "ext:helm.el")`

@riscy Eeagerly loading `helm` (which might be installed, but not used) wouldn't be ideal.  So the solution here  would be the `declare-function` you suggest, and to remove the `(require 'helm)` and `(require 'helm-multi-match)` completely.

(Really, to package this properly you'd have a separate little `plain-org-wiki-helm` package with a proper dependency on `plain-org-wiki` and `helm`. These byte compilation workarounds are generally a sign that the code is doing things the wrong way. For this little case I wouldn't insist.)

**Comment by abo-abo** [comment]
@purcell Thanks, added the dependency on ivy.

**Comment by riscy** [comment]
Hi @abo-abo, I see the push -- I think this issue still isn't addressed:

> the solution here would be the declare-function ..., and to remove the (require 'helm) and (require 'helm-multi-match) completely.

**Comment by riscy** [comment]
Currently on the master branch I see:

```elisp

;;;###autoload
(defun plain-org-wiki-helm ()
  "Select an org-file to jump to."
  (interactive)
  (require 'helm)
  (require 'helm-multi-match)
  (helm :sources
        '(((name . "Projects")
           (candidates . plain-org-wiki-files)
           (action . plain-org-wiki-find-file))
          ((name . "Create org-wiki")
           (dummy)
           (action . plain-org-wiki-find-file)))))
```
@purcell's suggestion is to use `declare-function`, so at the top of your file you would have:
```elisp
(require 'ivy)
(declare-function helm "ext:helm.el" t)
```
Another small thing I'm noticing with the latest `package-lint` -- you want to depend on Emacs 24.3 rather than Emacs 24.1 for `cl-mapcan`.

After these I think everything's sorted and this is good to merge.

**Comment by abo-abo** [comment]
@riscy Thanks.

**Comment by riscy** [comment]
Great, thanks!

**Comment by abo-abo** [comment]
Thanks.

**Pull request merged**
