### PR TITLE
Add recipe for agenix

### PR DESCRIPTION
**Pull request by t4ccer**
### Brief summary of what the package does

agenix.el enables transparent editing for agenix secrets.

### Direct link to the package repository

https://github.com/t4ccer/agenix.el

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

I'm the maintainer so can answer everything here.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`agenix.el` with byte-compile using Emacs 28.1:
```
agenix.el:43:1: Warning: custom-declare-variable `agenix-pre-mode' docstring
    wider than 80 characters
```
(These have actually become byte-compile *warnings* recently, and therefore very much worth fixing.)

`agenix.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- agenix.el#L90: It's safer to sharp-quote function names; use `#'`
- agenix.el#L102: It's safer to sharp-quote function names; use `#'`
- agenix.el#L136: It's safer to sharp-quote function names; use `#'`
- agenix.el#L170: It's safer to sharp-quote function names; use `#'`
- agenix.el#L111: No `format` required; `warn` takes an f-string
```

Package and license:
- Prefer equivalent recipe: `(agenix :repo "t4ccer/agenix.el" :fetcher github)`

**Comment by t4ccer** [comment]
Thanks for the review! I've addressed the warnings in https://github.com/t4ccer/agenix.el/commit/60e0376bb9137e607aabea331a812b9c89f1007c and I'll try integrate melpazoid into my CI pipeline in the future

**Comment by riscy** [comment]
Thank you for accommodating.  I had one more close look and I've got a couple more suggestions, but this is a quick merge after:

- `agenix-mode-if-with-secrtes-nix` -- this looks like a typo, and since it is autoloaded and interactive you *probably* want this to be correct
- `(run-hooks 'agenix-pre-mode-hook)` this variable is undocumented (and I think nonstandard?) so I would recommend documenting it, and maybe explaining to the user (or me) why it is needed in addition to the `agenix-mode-hook` that will get created by `define-derived-mode`
- Also be aware of `user-error` (as opposed to the usual`error` function); sometimes we don't want to open an elisp backtrace when it was due to faulty user input, e.g. in `agenix-decrypt-buffer`
- And since I'm in spellcheck mode, `transaprent` -> `transparent`, `evalutation` -> `evaluation`

**Comment by t4ccer** [comment]
Thanks, I've fixed these typos, and documented `agenix-pre-mode-hook`. wrt. error, I'm not sure what's the best way here, `error` is used only if `age` encryption/decryption fails which shouldn't happen unless there's a bug in my or their code, so it should be fine

**Comment by riscy** [comment]
Thank you - looks good here.

One other small thing I'd review is that your status messages, e.g. stuff like:
```
"Not decrypting. File %s does not exist and will be created when you will save this buffer."
```
...doesn't unnecessarily exceed 80 characters by too much, which is of course arbitrary but widely expected.  (It's a nice quality of life thing when my messages aren't word-wrapping at the bottom of my frame.)  This particular message is going to have a filename interpolated in it, but could still be shortened a bit:
```
"Not decrypting. File %s does not exist yet."
```
since I think the fact that the file will be created on save should be obvious to most Emacs users.

Non-blocking though.  And welcome to MELPA. :)

**Pull request merged**
