### PR TITLE
add ciel.el recipe

### PR DESCRIPTION
**Pull request by cs14095**
Hi, please add ciel.

A command that is clone of "ci" in vim.
https://github.com/cs14095/ciel.el

Thank you.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- `C-c i` and `C-c o` are [reserved for end users](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html), so you must not use them in your minor mode. But that's easy to solve: you don't need a global minor mode anyway - just tell users to bind those two keys globally.
- The `%name` convention is unusual, and I would advise against it
- I think `(unless (null %region)` is equivalent to `(when %region`
- `""` isn't a great docstring ;-)
- You seem to have reinvented prefix maps: why not just create individual commands for each subcommands, and bind them into a prefix map?

Hope that helps!
-

**Comment by cs14095** [comment]
Thank you for response.
So I should

 - remove `(define-minor-mode ` and `(defvar ciel-mode-map `
 - add `(global-set-key "\C-ci" 'ciel-ci)`

then is this ok?

**Comment by purcell** [comment]
Yes, that's enough to merge this recipe.

But I'd also suggest you investigate creating individual commands for `c i w` etc, because they might be useful individually. You can use a function or macro to eliminate duplicated code, and then put all the commands in a prefix keymap. :-)

**Comment by cs14095** [comment]
Hi, I changed you pointed out.
Please look over https://github.com/cs14095/ciel.el/blob/master/ciel.el.

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
