### PR TITLE
Add new recipe: flycheck-drstring

### PR DESCRIPTION
**Pull request by danielmartin**
Lint Swift documentation using DrString

### Brief summary of what the package does

This packages integrates DrString (https://github.com/dduan/DrString) in Flycheck. DrString is a linter for Swift documentation. It warns the programmer about things like missing documentation for function arguments, incorrect casing, etc. By specifying a configuration file per project, users can adapt the expected style to the conventions of individual projects.

This package also integrates a Flycheck error explainer that gives an overview of what's incorrect and what's the suggested way to fix it.

### Direct link to the package repository

https://github.com/danielmartin/flycheck-drstring

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
### flycheck-drstring.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
```
flycheck-drstring.el:155:1:Warning: the function `swift-mode' is not known to
be defined.
```

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191220.419):
- No issues! 💯

<details><summary>Other notes...</summary>
These notes are for reference and not part of the checks.

### Maintainer/license
- PR by danielmartin: https://github.com/danielmartin/flycheck-drstring
- License found (through API): 'GNU General Public License v3.0' (good)
- LICENSE excerpt: 'GNU GENERAL PUBLIC LICENSE...'
- License appears to be written into individual files

### Summary
- (flycheck-drstring :fetcher github :repo "danielmartin/flycheck-drstring") 
- Package-Requires: emacs "25.1", flycheck "0.25"
- _elisp/flycheck-drstring.el (gpl): Doc linting for Swift using DrString
</details>

**Comment by danielmartin** [comment]
Thanks! Byte-compilation warning should be fixed by https://github.com/danielmartin/flycheck-drstring/commit/444eb3661ea61ac26665e788f5055a3ac9f512dd

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.

1. Please add Cask file is good to easy resolve dependency, build, packaging etc.
2. Please indent the whole file because of some of places indent are broken.
3. Please add `Keyword:` header.
4. Please fix the order in the file header.
  package "one-line description -> copyright declaration -> package meta info -> license -> commentary -> code order" is common.
5. Please consider to use `when-let` instead of `if-let` and `progn` combination.
6. Please declare `swift-mode` is defined in `swift-mode` package.
  Or your package require swift-mode? `drstring` flycheck checker is only enabled when `swift-mode`.
  If this case, you could list `swift-mode` as dependencies and just `require` `swift-mode` is the most easy way.

**Comment by riscy** [comment]
Looks good!  Thanks, @conao3, for taking a look and for making the PR!

**Comment by conao3** [comment]
Your welcome!

**Pull request merged**
