### PR TITLE
Add recipe for tempo-abbrev

### PR DESCRIPTION
**Pull request by xFA25E**
### Brief summary of what the package does

It provides functions that help binding tempo templates (or any function) on abbrev hooks. Since abbrevs support inheritance, these hooks will support inheritance by mode too.

### Direct link to the package repository

https://github.com/xFA25E/tempo-abbrev

### Your association with the package

I'm the maintainer

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by minad** [comment]
Out of interest, did you try my [Tempel](https://github.com/minad/tempel) package? It also provides an integration with the abbrev mechanism. Tempel doesn't use Tempo since it turned out that I could not reuse most of it due to the interactive nature of Tempel. But the Tempo-compatible reimplementation is very small thanks to `pcase`.

**Comment by xFA25E** [comment]
> Out of interest, did you try my [Tempel](https://github.com/minad/tempel) package?

@minad no, I did not. I want to reuse as much tempo as possible. Really, this package should have been called `abbrev-hook`, because it provides a sophisticated mechanism of binding hooks on abbrevs + a wrapper that creates names for tempo. But, I initially created it with tempo in mind.

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --


`tempo-abbrev.el` with package-lint 20221003.1636:
```
9 issues found:
222:0: error: "ta-call" doesn't start with package's prefix "tempo-abbrev".
235:0: error: "ta-define" doesn't start with package's prefix "tempo-abbrev".
246:0: error: "ta-define-hook" doesn't start with package's prefix "tempo-abbrev".
266:0: error: "ta-mode-abbrev-table" doesn't start with package's prefix "tempo-abbrev".
273:0: error: "ta-abbrev-table" doesn't start with package's prefix "tempo-abbrev".
277:0: error: "ta-update-table-regexp" doesn't start with package's prefix "tempo-abbrev".
285:0: error: "ta-abbrev-table-names" doesn't start with package's prefix "tempo-abbrev".
295:0: error: "ta-set-table-parent" doesn't start with package's prefix "tempo-abbrev".
302:0: error: "ta-templates" doesn't start with package's prefix "tempo-abbrev".
```

**Comment by xFA25E** [comment]
Thanks for your work, too. :)

Unfortunately, `package-lint` [doesn't support](https://github.com/purcell/package-lint/issues/238) `read-symbol-shorthands`, yet. 

What should I do? I would really prefer to use latest stable emacs (28) features, such as _shorthands_.

**Comment by minad** [comment]
@xFA25E Shorthands seem hardly worth it for a package of 300 lines. You could easily make your package compatible with many Emacs versions given that both Abbrev and Tempo are old Emacs features.

**Comment by riscy** [comment]
I'm in agreement with @minad here.

**Comment by xFA25E** [comment]
Thanks for your kind suggestions.

However, I believe that developers can (and should) use latest stable emacs features to simplify development process and maintenance cost. If you disagree with this principle, then you can close this PR.

**Comment by minad** [comment]
I agree - where it makes sense. Note that I maintain the Compat package which allows you to use the newest APIs even on old Emacs versions.

In this case however, Shorthands arguably increase the maintainance burden since the existing tooling does not yet support it. Also the Shorthand feature is half-baked and may see further updates in future Emacs versions.

**Pull request closed without merging**
