### PR TITLE
Add recipe ivy-rich.

### PR DESCRIPTION
**Pull request by Yevgnen**
### Brief summary of what the package does

Provides more friendly interfaces for `ivy`.

### Direct link to the package repository

https://github.com/Yevgnen/ivy-rich

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

[e.g., package.el compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- missing `projectile` dependency
- `subr-x` requires Emacs 24.4 or higher version
- Please write package description(Short description at first line after `---` )

**Comment by Yevgnen** [comment]
@syohex Thanks for your quick reply and advices! I've updated the source. Please check it.

**Comment by syohex** [comment]
It looks package has bug.

https://github.com/Yevgnen/ivy-rich/issues/1

**Comment by Yevgnen** [comment]
@syohex Thanks for reporting it!  I'll looking into it soon.

**Comment by alphapapa** [comment]
Just curious, how exactly does your package improve on `ivy-switch-buffer`?  It would be good to show what the difference is.

Also, in the screenshot, why is there a list of file paths under the buffer list?

**Comment by Yevgnen** [comment]
@alphapapa Currently not much really.  I just make it more like `helm` as I was a `helm` user. The list of full path is the original `ivy` feature, which is called `virtual buffers`. It could be also formatted though. You can see some discussion [here](https://github.com/abo-abo/swiper/issues/256)

Personally, for some `ivy` extensions, the default display of candidates is really unfriendly. For example, here's the `org-ref` using `ivy`

screen shot 2016-11-29 at 11 24 19 pm

I can't see the even basic alignment. 

Compared to `helm` with the default settings

screen shot 2016-11-29 at 11 28 12 pm

I've also wrote a `ivy-org-ref-rich` for it too. Even now it's just like a toy.

In my opinion, this(at least a more slightly friendly interface) should be done by the origin author of the package. But there are so many package, I don't want to advice them one by one and most of them seem not much interested in it. I rather to wrote it myself, and share them to anyone who is interested in it.

**Comment by purcell** [comment]
Thanks, sorry for the slow response. Busy end of year here.

- `--` in a symbol prefix denotes private symbols, so don't use `ivy--`
- `ivy-switch-buffer-rich` would be better called `ivy-rich-switch-buffer`, since it's in a package called `ivy-rich`
- There's package metadata in both `.el` files, but we'll only read the data in `ivy-rich`. Why not just make this one file, called `ivy-rich-switch-buffer`? Then at least it would make (a little more) sense that it depends on `projectile`.
- In any case, don't assume that the user has activated or wants to use `projectile`. Check whether `projectile-mode` is true.

**Comment by Yevgnen** [comment]
Thanks for your relay and suggestions. I've updated the package into melpa convention. Please check when you have time.

**Comment by syohex** [comment]
Looks good.

**Comment by syohex** [comment]
Merged

**Pull request merged**
