### PR TITLE
Add `moonshot' recipe.

### PR DESCRIPTION
**Pull request by ageldama**
### Brief summary of what the package does

  * Detect or Manually configure the build directory of the project
  * Run arbitrary commands in `compilation-mode`
    * Commands can be configured per project
    * Each command string will expand special tags for your project root directory, absolute filename of the buffer, etc
  * Run project' executable file in `compilation-mode` or Debug it with realgud/gud
    * Automatically searched in project root directory and project build directory,
    * Suggest most relevant executable from the current buffer. (by Levenshtein distance)

### Direct link to the package repository

https://github.com/ageldama/moonshot

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi, thanks for this.  Here's a quick first pass:

### moonshot.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
Loading /workspace/.emacs.d/elpa/realgud-20191123.1341/realgud/common/custom...
```
moonshot.el:171:9:Warning: reference to free variable
`moonshot-file-list->distance-alist'
moonshot.el:175:21:Warning: reference to free variable `file-names'
moonshot.el:171:59:Warning: reference to free variable `&key'
moonshot.el:171:64:Warning: reference to free variable `dist-fun'
moonshot.el:174:10:Warning: reference to free variable `file-list->dist-alist'
moonshot.el:177:28:Warning: reference to free variable `fn'
```

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191220.419):
- No issues! 💯

<details><summary>Misc...</summary>

### Maintainer/license

- PR by ageldama: https://github.com/ageldama/moonshot
- License found (through API): 'GNU General Public License v3.0' (good)
- LICENSE excerpt: 'GNU GENERAL PUBLIC LICENSE...'

### Summary

- (moonshot :fetcher github :repo "ageldama/moonshot") 
- Package-Requires: realgud "1.5.1", cl-lib "0.5", emacs "25.1", projectile "2.0.0", f "0.18", s "1.11.0", counsel "0.11.0", seq "2.20", levenshtein "1.0"
- _elisp/moonshot.el (unknown license): Run executable file, debug and build commands on project
</details>

**Comment by ageldama** [comment]
Hi, @riscy , thank you for the review!

I've updated the https://github.com/ageldama/moonshot/commit/00bd54136335fb6954e144f8481eaef6b002ac3d , please review later.


I couldn't reproduce the warnings above, I think those are related with `cl-lib`'s `defun*`.
Anyway, I've replaced the `defun*` with `defun` and `defcustom`.

I'm using: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-30

And here's my `*compilation-log*` of `byte-compile-file`:
Screenshot from 2020-01-27 20-09-31



ANYWAY, I think it won't happen no more since I've changed the `defun*`. :-)


Thank you in advance!

**Comment by riscy** [comment]
Minor, but this one:
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
Loading /workspace/.emacs.d/elpa/realgud-20191123.1341/realgud/common/custom...
```
moonshot.el:182:20:Warning: reference to free variable `file-list->dist-alist'
```
can be fixed by using the macros from `cl-lib` instead of `cl`:
```elisp
(defun moonshot-file-list->distance-alist (fn file-names)
  "Calculate string difference distances from `FN' of given `FILE-NAMES'.
By using `moonshot-file-name-distance-function'.
Evaluates as nil when `FN' or `FILE-NAMES' is nil."
  (cl-block file-list->dist-alist
    (unless (and fn file-names)
      (cl-return-from file-list->dist-alist nil))
    (let ((fn* (f-filename fn)))
      (mapcar (lambda (i)
                (cons (funcall moonshot-file-name-distance-function
                               fn* (f-filename i))
                      i))
              file-names))))
```
(`block` and `return-from-file-list` are part of deprecated `cl`).

Another thing that just caught my attentionis that you use `ivy-read`, but why not `completing-read`?  That will give your users the flexibility to choose not to use ivy in case they prefer another completion manager.

Why is `moonshot-project-build-dir` a customizable user option?  It seems like `defvar-local` might be more appropriate for declaring variable, but I may be missing something.

Lastly, I feel like your `;; Commentary` needs some more information about what this package does.  Maybe something like: "This package locates a project build directory for the current buffer, and makes it easier to run common debug and execution commands from that directory."

Hope that helps. :)

**Comment by ageldama** [comment]
@riscy Thank you so much

Updates:
* The Commentary-section
* Replace `block` with `cl-block`

Thank you for your code reviewing, I didn't expect that I could get such helping during registering MELPA, thak you again.

Yes, those points are great and I made issues for that: https://github.com/ageldama/moonshot/issues
Once it registered at MELPA, I need to prepare next release including your opinions.

Thanks and hope it gets merged soon!

**Comment by ageldama** [comment]
@riscy UPDATED!

* with `defvar-local`
* and `completing-read`

DONE!

Thank you so much! and please merge this!

**Comment by riscy** [comment]
About the license - it's better if we can include license boilerplate at the top of the file before the `;;; Commentary` section, in case a user only receives the file.  MELPA by default will not distribute your LICENSE.  (You can see an example of the GPL 3 boilerplate for elisp files in, e.g., the org file that comes with Emacs.)

You can make it so people can set the moonshot-project-build-dir with a magic comment:
```
(defvar-local moonshot-project-build-dir nil
  "Project build directory. Can be a string or a form.")
(put 'moonshot-project-build-dir 'safe-local-variable #'stringp)
```
But I would strongly advise ONLY doing this for `stringp` types, since you `eval` this variable when it's not a string.

I also notice that you're quoting argument names on docstrings like this:
```elisp
  "Calculate string difference distances from `FN' of given `FILE-NAMES'.
```
But it's sufficient to just capitalize them.  The ``` `/' ``` style of quoting is actually to create hyperlinks within Emacs' help facility.  The capitalization is sufficient for Emacs to know to fontify those as arguments within the help facility.

I also have some edit suggestions for your Commentary section (and the parts of your Commentary that are repeated as docstrings within the code):

```
;;; Commentary:

;; This package locates a project build directory for the current
;; buffer, and makes it easier to run common debug and execution
;; commands from that directory.
;;
;; << Determining the Project Build Directory >>
;;
;; 1) If file local variable `moonshot-project-build-dir' is set:
;;   a) if it starts with "/", use it as-is
;;   b) if it does not start with "/":
;;      - Append it to project root directory or the directory of current buffer.
;;      - If the directory of current buffer is not available, it's nil.
;;   c) if it is a sexp, run `eval' on it and return the value
;;   d) Implemented in `moonshot-project-build-dir-by-value' function.
;; 2) Otherwise, check projectile
;; 3) Otherwise, use the directory of current buffer

;; << Launching an Executable >>
;;
;;  This is accomplished using `moonshot-run-executable':
;;  1) It will search executable files under `moonshot-project-build-dir'.
;;  2) It will suggest executable files based on the buffer filename.

;; << Launching a Debugger with Executable >>
;;
;;  This is accomplished using `moonshot-run-debugger':
;;  - Similar to `moonshot-run-executable', choose an executable to debug.
;;  - The supported debuggers are listed in `moonshot-debuggers'.

;; << Running a Shell Command in Compilation-Mode >>
;;
;;  This is accomplished using `moonshot-run-runner':
;;  - Global shell command presets are `moonshot-runners-preset'.
;;  - Per project commands can be added to `moonshot-runners', by specifying variable in `.dir-locals.el' etc.
;;
;;  <<< Command String Expansion >>>
;;    - The following format specifiers are will expanded in command string:
;;      %a  absolute pathname            ( /usr/local/bin/netscape.bin )
;;      %f  file name without directory  ( netscape.bin )
;;      %n  file name without extension  ( netscape )
;;      %e  extension of file name       ( bin )
;;      %d  directory                    ( /usr/local/bin/ )
;;      %p  project root directory       ( /home/who/blah/ ), using Projectile
;;      %b  project build directory      ( /home/who/blah/build/ ), using `moonshot-project-build-dir'"
```

**Comment by ageldama** [comment]
Hey @riscy , Revised it according by your recommendations: https://github.com/ageldama/moonshot/commit/83a9933cd4af234ae15fdc3a39e660d646b0c246

I've learned so much from your recommendations and during this PR, thank you again. :-)

**Comment by riscy** [comment]
Alright, looks good to go.  And, welcome to MELPA! :)

**Comment by ageldama** [comment]
Wow!

**Pull request merged**
