### PR TITLE
Add recipe for Casual

### PR DESCRIPTION
**Pull request by kickingvegas**
### Brief summary of what the package does

An opinionated [Transient](https://github.com/magit/transient)-based porcelain to support the casual usage of Emacs [Calc](https://www.gnu.org/software/emacs/manual/html_mono/calc.html).

### Direct link to the package repository

https://github.com/kickingvegas/Casual

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this - this looks excellent.  Quick first pass --

`casual.el` with byte-compile using Emacs 29.2:
```
casual.el:178:15: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el:199:18: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el:202:19: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el:212:27: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el:296:7: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el:387:27: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el:609:27: Warning: (lambda nil \...) quoted with ' rather than with #'
```
I think these aren't due to you not being careful, but just due to the macro expecting function names.  But I also think the fix is worth doing, which is to avoid anonymous functions inside these transient definitions, and introduce named private functions.  Admittedly there are a lot, but you will also avoid noise at the console along these lines:

Stderr output while compiling/loading:
```
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
casual.el: Warning: (lambda nil \...) quoted with ' rather than with #'
```

Package and license:
- Avoid specifying `:branch` except in unusual cases (MELPA will automatically pick up the main branch if it's your default branch)

**Comment by kickingvegas** [comment]
Addressed all comments raised by @riscy:

- Code change to use named private functions to avoid Transient macro warnings.
- Updated Casual MELPA recipe to *not* specify branch.

Please review update for publication of Casual on MELPA.

**Comment by kickingvegas** [comment]
Updated Casual to v1.1.0. https://github.com/kickingvegas/Casual/pull/45

**Comment by kickingvegas** [comment]
Updated Casual to v1.2.0. https://github.com/kickingvegas/Casual/pull/57

Now with support for plotting.

**Comment by riscy** [comment]
Thank you @kickingvegas - looking good here.  Some quick feedback on the latest code, but otherwise this looks good to merge --

`casual-binary.el` with checkdoc 0.6.2 (fix *within reason*):
```
casual-binary.el:31: You should have a section marked ";;; Code:"
```

And some (optional) sharp-quoting you could do, to get the byte-compiler on your side:

- casual-graphics.el#L98: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L123: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L124: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L147: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L148: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L154: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L161: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L173: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L190: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L197: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L208: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L215: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L222: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L229: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L236: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L244: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L251: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L258: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L265: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L272: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L279: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L286: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L293: It's safer to sharp-quote function names; use `#'`
- casual-graphics.el#L300: It's safer to sharp-quote function names; use `#'`

**Comment by kickingvegas** [comment]
Updated Casual to v1.2.1. https://github.com/kickingvegas/Casual/pull/67

Note: Moved all Elisp files to `lisp/` directory. 

Please review again for MELPA release.

**Comment by riscy** [comment]
Thanks again for this!

**Pull request merged**
