### PR TITLE
Add org-treescope recipe

### PR DESCRIPTION
**Pull request by mtekman**
### Brief summary of what the package does

Provides a calendar-based UI for performing sparse matches on an org-mode file.

### Direct link to the package repository

https://github.com/mtekman/org-treescope.el

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
  (two small lexical scope warnings that I am not sure how to avert)
- [X] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
It would probably be a good idea if this package provided a UI wrapper around `org-ql-sparse-tree` rather than writing all this functionality from scratch.  `org-ql` already provides a simple query syntax for dates and priorities, e.g.
```el
(org-ql-sparse-tree
  '(and (ts :from "2020-01-01" :to today)
        (priority "A"))
```
A calendar-based picker for the timestamp predicate's arguments would be almost all that's needed, and `org-ql`'s searching should be faster and more flexible.

**Comment by mtekman** [comment]
Hey thanks!

I thought about the excellent org-ql, but I have more experience with the native org-match-sparse, and didn't want to be saddled with more dependencies than necessary because I thought it might be slower (though I am pleased by your most recent post that gccemacs has provided a fantastic speedup). Also I had no idea it did sparse matching, I thought it was more of an agenda thing.

> You claim the package byte-compiles cleanly, but it does not.

I mentioned that I get two lexical scope warnings. I'm not really sure how to get around those without rewriting my macros and breaking other things.

Much to play and contend with, thanks for the review!

**Comment by alphapapa** [comment]
`org-ql` is a library for searching Org files quickly and efficiently.  The libraries `org-ql-view` and `org-ql-search` provide an Agenda-like UI on top of that.  The `org-ql-sparse-tree` command uses `org-ql` as a search backend to provide functionality like the built-in Org sparse trees (it copies the tree-related code).  `org-ql`'s searching is generally much faster than the built-in Org searching, because it's optimized and uses caching.

> I mentioned that I get two lexical scope warnings. I'm not really sure how to get around those without rewriting my macros and breaking other things.

That means that you're doing something wrong, or at least unidiomatically.  Please ask for help with those specific issues so we can advise you on how to fix them.

**Comment by mtekman** [comment]
> org-ql's searching is generally much faster than the built-in Org searching, because it's optimized and uses caching.

well you piqued my interest there, currently my matching has some slowdowns that I want to eliminate.

Hmm. I guess a small rewrite is in order. Shall I close this PR and re-open when it is up to scratch? Or is adding [WIP] tag enough?

**Comment by alphapapa** [comment]
If you intend to rewrite it, you should close the PR and make a new one when it's ready, because the MELPA reviewers don't need to review code that is going to be replaced.

**Comment by mtekman** [comment]
okay, till next time -- and thanks!

**Comment by alphapapa** [comment]
Let me know if you have any questions about using org-ql.

**Comment by mtekman** [comment]
I made a rewrite, split out several functions into standalone(-ish) libraries, and incorporate `org-ql-sparse` (with massive speedups).

**Comment by riscy** [comment]
Looks great, and nice animated gif demo. :)  I note this:

- org-treescope-query.el#L103: No `format` required; messages are already f-strings

but it's not a blocker by any means.  Thanks!

**Pull request merged**
