### PR TITLE
Add recipe for helm-twitch

### PR DESCRIPTION
**Pull request by BenediktBroich**
### Brief summary of what the package does

I just want to integrate helm-twitch into spacemacs. Merge this first [twitch-api](https://github.com/melpa/melpa/pull/7889) This part is already merged [streamlink](https://github.com/melpa/melpa/pull/7670)

### Direct link to the package repository

https://github.com/BenediktBroich/helm-twitch

### Your association with the package

I am the maintainer. 

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by BenediktBroich** [comment]
The requested changes were merged.

**Comment by riscy** [comment]
Hi @BenediktBroich, I see this but I'll take a closer look next week, just to distribute my time more evenly between authors.  But one question --

> The requested changes were merged.

This is the second time I've seen you make this comment - how come you wrote it when no changes have been requested?

**Comment by BenediktBroich** [comment]
@riscy cool tanks. Syohex did crate a PR on my repo right after i created the PR here. So i thought this was the review and just wanted to notify him about the merge here.

**Comment by riscy** [comment]
Ah, I see now what you meant.  I think syohex is currently just an untethered and independent force for good in the Emacs community (despite a history of contributing to MELPA!).  But I had a look on my side and everything checks out.  (Package-lint warns about the snapshot dependencies, but I don't think either of those dependent packages have stable releases, so we're good to go.)  Thanks again!

**Comment by tarsius** [comment]
[BenediktBroich](https://github.com/BenediktBroich) please use the correct case of your username in recipes. Thanks!

**Pull request merged**
