### PR TITLE
Create renpy-mode

### PR DESCRIPTION
**Pull request by billywade**
### Brief summary of what the package does

Major mode for editing Ren'Py script files. 

### Direct link to the package repository

https://github.com/billywade/renpy-mode

### Your association with the package

I'm the current maintainer, but I don't use it frequently enough or know Elisp well enough to be able to maintain it effectively

### Relevant communications with the upstream package maintainer

none needed

### Checklist

Please confirm with `x`:

- [ x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [ x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
In general, we don't want to add unmaintained packages to MELPA.  MELPA's intended to be a curated library containing packages that meet a certain standard of quality.  You say in the readme:

> This mode is currently unmaintained. I'm keeping it because the original upstream developer doesn't use either Emacs or Ren'Py anymore. If you use this and know ELisp better than I do (a very low bar), let me know and this major mode is yours.

I think this effectively disqualifies the package from being suitable for MELPA.  Besides that, it appears that it hasn't been significantly updated for almost 10 years, and it has many minor issues that would need cleaning up before being published here.

It's great that you are doing what you can to keep it alive and visible, and if it finds a qualified maintainer (or if you decide to be one), it would probably be a good candidate for MELPA.  In the meantime, you might choose to publicize it in other ways so that interested users can find it and install it on their own (and you might publish instructions to do so with tools like quelpa, el-get, straight.el, etc).

Note that I'm not a MELPA maintainer, just a contributor who tries to help reduce the PR backlog by doing initial reviews.  This is not an official decision by MELPA.

Thanks.

**Comment by tarsius** [comment]
The package name has to match the name of the library -- in this case `renpy`.

**Comment by billywade** [comment]
@alphapapa You're absolutely right, but where should I publish this to get that kind of visibility? If I start using Ren'Py more or get more free time to learn Elisp, I just might, but that's pretty unlikely given real life and all.
@tarsius Fixed, thanks for the head's up.

**Comment by tarsius** [comment]
You also have to rename the recipe file.

**Comment by billywade** [comment]
also, @alphapapa, if you would open up issues for errors you see I can try to fix them anyways. I might learn something.

**Comment by alphapapa** [comment]
> You're absolutely right, but where should I publish this to get that kind of visibility?

This is the Internet.  But I don't think the audience for the package is very large to begin with.  Just post it on Reddit and stuff, and people who want it can find it with Google.

> If I start using Ren'Py more or get more free time to learn Elisp, I just might, but that's pretty unlikely given real life and all.

I feel a bit confused.  You've said two or three times that you are not maintaining the package and are not likely to start doing so.  So it's not really your package.  But you want MELPA to publish it so users more dedicated than yourself will find it and take over?

> if you would open up issues for errors you see I can try to fix them anyways. I might learn something.

I am busy with projects of my own.  There are many resources about developing Emacs packages available for you to study.

**Comment by billywade** [comment]
> You've said two or three times that you are not maintaining the package and are not likely to start doing so. So it's not really your package. But you want MELPA to publish it so users more dedicated than yourself will find it and take over?

You pretty much hit the nail on the head. It is a niche audience, but even if I don't use the package enough or have the skill to keep it chugging, I figure there's someone who would have use for it who doesn't know it exists for lack of visibility. 

>I am busy with projects of my own. There are many resources about developing Emacs packages available for you to study

I get you, I just thought I'd ask. As for learning Emacs and Elisp more, that's something for me to do when I'm not a student, because between real life, classes, work, and trying to teach myself computer science, I'm usually kept pretty busy.

**Comment by alphapapa** [comment]
> You pretty much hit the nail on the head. It is a niche audience, but even if I don't use the package enough or have the skill to keep it chugging, I figure there's someone who would have use for it who doesn't know it exists for lack of visibility.

That's fine, but MELPA is not a place to essentially dump code in the hope that it will find a new home.  There are many Emacs packages on GitHub and other places that are not in MELPA.

**Comment by billywade** [comment]
Alrighty, I'll find a place to put it.

**Comment by purcell** [comment]
Thanks for the discussion above. At this point, now that you've adopted the package as an interim maintainer, we could potentially merge this. However, the file's header is malformed, so it's not yet a valid package file. You'd need to make `package-lint` happy with it. :-)

**Comment by billywade** [comment]
Thanks @purcell, I just went through and made some changes. ```package-lint``` seems happy with it, but let me know if I missed something in my edits.

**Comment by purcell** [comment]
Looks good now, yay! Merged. :-)

**Comment by billywade** [comment]
Thank you so much!

**Pull request merged**
