### PR TITLE
Remove dir-locals from lsp-mode

### PR DESCRIPTION
**Pull request by ericdallo**

### CODE REVIEW

**Comment by purcell** [comment]
That file is excluded automatically by the ":defaults" spec. How did you conclude that this change was necessary?

BTW "clients/*.el" rather than "clients" means "copy clients/*.el to the root of the resulting package." I know it was like that before, but is that the desired behaviour?

**Comment by ericdallo** [comment]
Oh sorry, I didn't know default was already excluding that, I checked the [cider](https://github.com/melpa/melpa/blob/master/recipes/cider#L3) and I thought it was missing from lsp-mode too, but cider is not using default 😅 

> BTW "clients/.el" rather than "clients" means "copy clients/.el to the root of the resulting package." I know it was like that before, but is that the desired behaviour?

yes, we copy all the clients to the root indeed :)

**Comment by purcell** [comment]
Sweet, if you find that file in an installed dir, it would be a bug on our side, so please let us know! :-)

**Comment by ericdallo** [comment]
Sure, I'm used to having lsp-mode local, that's why I didn't realize that melpa already removes it, sorry for that 😅 
Thank you @purcell!

**Pull request closed without merging**
