### PR TITLE
add go-gen-test recipe

### PR DESCRIPTION
**Pull request by s-kostyaev**
### Brief summary of what the package does

Generating go tests from emacs.

### Direct link to the package repository

https://github.com/s-kostyaev/go-gen-test

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by s-kostyaev** [comment]
How to prevent `(:exclude .dir-locals.el test.el tests.el *-test.el *-tests.el)` ?

**Comment by purcell** [comment]
Thanks!

- The `:files` spec is unnecessary here, so please remove it.
- Use `(interactive "r")` to more easily get the region extents in `go-gen-test-dwim`
- The way to decide whether the user wants to use the region is with `use-region-p`, not `region-active-p`.
- Don't [build commands with `format` and string concatenation](https://github.com/s-kostyaev/go-gen-test/blob/c1e7e5ce99f7bf66cc8bfef818b4437f5e7406cb/go-gen-test.el#L122-L124) unless you're also using `shell-quote-argument` -- if `buffer-file-name` contains spaces or quotes here, you're in trouble.

Looks good otherwise. :-)

**Comment by s-kostyaev** [comment]
> The :files spec is unnecessary here, so please remove it.
Then this project can't build because of filename is `go-gen-test.el` which one matched by `*-test.el`
Other things I will fix soon. Thanks for review.

**Comment by purcell** [comment]
> Then this project can't build because of filename is go-gen-test.el

Doh, right. Sorry! Merging now.

**Pull request merged**
