### PR TITLE
Add ivy-filthy-rich

### PR DESCRIPTION
**Pull request by casouri**
### Brief summary of what the package does

Similar to ivy-rich, this package adds more information to ivy. 
However, ivy-filthy-rich can be customized.

### Direct link to the package repository

https://github.com/casouri/ivy-filthy-rich

### Your association with the package

Maintainer & author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### Note

- ~~package-lint complains about prefix because I use `ifrich` instead of `ivy-filthy-rich`~~ ~~I'm fixing that.~~ It's fixed.
- checkdoc complains about the "80 columns" on two or three docstrings, they are not ridiculously long.

### CODE REVIEW

**Comment by casouri** [comment]
But I see many other people using short prefixes, and of rich isn’t very easy to duplicate. Do I have to use full prefix?

**Comment by alphapapa** [comment]
This is MELPA's policy. I'm just informing you to save them the trouble of
typing it themselves. Some older packages don't follow the rule because it
wasn't enforced then.

**Comment by casouri** [comment]
I definitely will use a shorter package name next time.

**Comment by alphapapa** [comment]
Just saw this, maybe you can collaborate: https://github.com/Yevgnen/ivy-rich/tree/customize https://www.reddit.com/r/emacs/comments/8whyuk/request_for_testing_new_version_of_ivyrich/

**Comment by casouri** [comment]
I think ivy-rich's new branch is pretty complete functionality wise, so I'll just close this.

**Pull request closed without merging**
