### PR TITLE
Add sort-words.el recipe

### PR DESCRIPTION
**Pull request by dotemacs**
As per subject, sort-words.el added

https://github.com/dotemacs/sort-words.el

### CODE REVIEW

**Comment by syohex** [comment]
- `(provide 'sort-words)` is missing
- `list-to-string` should be named `sort-words-list-to-string` or remove it and use its content directly.

And I suppose you should not check by `(use-region-p)` for function usage(See `sort-lines` implementation)

**Comment by dotemacs** [comment]
Good points @syohex, thanks!

**Comment by dotemacs** [comment]
Hey @syohex 

the omission that shouldn't have been there, have now been fixed:

- prefix for function name: **list-to-string** correctly named **sort-words-list-to-string**
- **provided** added

https://github.com/dotemacs/sort-words.el/pull/3

**Comment by dotemacs** [comment]
And I've removed the (use-region-p) check

**Comment by purcell** [comment]
Thanks, looks good. Maybe run `M-x checkdoc`, which will help you tidy up the docstrings so they conform to the conventions. :-)

**Pull request merged**
