### PR TITLE
mu4e-views

### PR DESCRIPTION
**Pull request by lordpretzel**
### Brief summary of what the package does

Add xwidget-webkit as a new method for viewing emails in `mu4e`. Keybindings are available in the xwidgets window to make the integration smoother.

### Direct link to the package repository

https://github.com/lordpretzel/mu4e-views

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### Notes

This packages requires the `xwidget-reuse` package for which I also submitted a pull request to melpa. It won't work until `xwidgets-reuse` is available in melpa.

### CODE REVIEW

**Comment by lordpretzel** [comment]
This fails until #7071 is merged.

**Comment by riscy** [comment]
Oh, right, mu4e is a tricky one.  I'll stub that line out and cherry pick some byte-compiler warnings and you can let me know what you think?

```
In mu4e-views-cursor-msg-view-window-down:
mu4e-views.el:453:20:Warning: xwidget-webkit-scroll-up called with 1 argument,
    but accepts only 0

In mu4e-views-cursor-msg-view-window-up:
mu4e-views.el:464:20:Warning: xwidget-webkit-scroll-down called with 1
    argument, but accepts only 0

mu4e-views.el:703:1:Warning: the following functions are not known to be
    defined:  ...
    thing-at-point-bounds-of-url-at-point, thing-at-point-url-at-point,
...
```
I think for the last one you just need to `(require 'thingatpt)`, and the other two seem to point to an issue with arg lists.

package-lint (using version 20200816.24):
```
1 issue found:
661:2: warning: Closing parens should not be wrapped onto new lines.
```
Easy!

**Comment by lordpretzel** [comment]
Hi,

thanks! I've fixed all of these. Turns out that the scroll functions started to take an optional argument with Emacs 27 so I am now checking for the emacs version to use the right calling conventions.

**Comment by lordpretzel** [comment]
@tarsius I think all remaining requests have been addressed or am I missing something?

**Comment by riscy** [comment]
Removed the 'awaiting upstream' on this one.

**Comment by riscy** [comment]
Thanks, taking a closer look now.  A couple comments:

- On lines 205,411,477,553 you don't need a `progn` for the else part of an `if` -- and you never need a `progn` for a single expression
- The _only_ system that can wordwrap your docstrings 100% correctly is you (automatic word-wrappers can never know if a line actually _needs_ to be long), so you should endeavour to wordwrap your docstrings in the file.  Using <kbd>M-q</kbd> is a default keybinding to do this.  Here's how one of your docstrings is currently rendering in the help:
image

- There are no MELPA rules on line length, but 250 characters seems too long to me and is hard for me to read (and hence understand what's going on).  Not a blocker, but strive for something reasonable (I personally recommend staying within double-digits) so that this:
```elisp
(insert (wrap-row "attachments" (mapconcat (lambda (att) (concat "<div class=\"mu4e-mu4e-views-attachment\">" (lax-plist-get att :name) " (" (mu4e-display-size (lax-plist-get att :size)) ")</div>"))  attachments "") "mu4e-attachments"))))
```
becomes more like this:
```

- If you named `mu4e-views-deactivate` `mu4e-views-unload-function` instead, then it will be called automatically when <kbd>M-x unload-feature</kbd> is used by the user (check out the help for that command)

After these are cleared up I think this is good to go.

And here's a quick ispell:
- choosen -> chosen
- attachements -> attachments
- layour -> layer
- viewin -> viewing

**Comment by lordpretzel** [comment]
thanks for your patience and hard work on melpa! I've pushed a commit fixing these. There were a few other problems and typos in the documentation that I've fixed too. I reduced the line length for most of the code. The only long lines are now the CSS definition.

**Comment by riscy** [comment]
Thanks for saying so. :)  This looks good to go.

**Pull request merged**
