### PR TITLE
Add emacs-trr in recipes

### PR DESCRIPTION
**Pull request by iory**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. The `TRR:` prefix should be `trr-`, as per the [elisp conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html) - should be a straightforward search/replace for @kawabata. :-)

Looks good otherwise.

**Comment by iory** [comment]
@purcell 
replaced TRR: -> trr-

**Comment by purcell** [comment]
Super, thanks!

**Comment by iory** [comment]
Thanks, too!

**Pull request merged**
