### PR TITLE
Add recipe for imbot

### PR DESCRIPTION
**Pull request by QiangF**
### Brief summary of what the package does

an input method management bot

### Direct link to the package repository

https://github.com/QiangF/imbot

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Please have another look at the checklist.

### imbot.el ###

byte-compile (using Emacs 26.3):
```
imbot.el:169:1:Warning: Unused lexical argument `args'
imbot.el:172:1:Warning: Unused lexical argument `args'
In end of data:
imbot.el:305:1:Warning: the following functions are not known to be defined:
    company--active-p, company-complete-selection
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
imbot.el:33: First sentence should end with punctuation
Warning (emacs): 
imbot.el:33: First line should be capitalized
Warning (emacs): 
imbot.el:38: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:47: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:50: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:53: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:59: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:65: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:85: First sentence should end with punctuation
Warning (emacs): 
imbot.el:85: First line should be capitalized
Warning (emacs): 
imbot.el:108: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:125: You should convert this comment to documentation
Warning (emacs): 
imbot.el:132: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:170: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:173: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:178: First sentence should end with punctuation
Warning (emacs): 
imbot.el:178: First line should be capitalized
Warning (emacs): 
imbot.el:191: First sentence should end with punctuation
Warning (emacs): 
imbot.el:191: First line should be capitalized
Warning (emacs): 
imbot.el:191: Lisp symbol `prog-mode' should appear in quotes
Warning (emacs): 
imbot.el:197: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:206: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:233: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:239: First sentence should end with punctuation
Warning (emacs): 
imbot.el:239: First line should be capitalized
Warning (emacs): 
imbot.el:249: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:255: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:260: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:147: White space found at end of line
```

package-lint (using version 20200419.406):
```
4 issues found:
1:0: warning: The package summary is too long. It should be at most 60 characters.
1:0: warning: The package summary should start with an uppercase letter or a digit.
129:0: error: "hydra-curr-map" doesn't start with package's prefix "imbot".
282:0: error: Global minor modes should be autoloaded or, rarely, `:require' their defining file (i.e. ":require 'imbot"), to support the customization variable of the same name.
```

**Comment by QiangF** [comment]
I think I have fixed the warning.

**Comment by QiangF** [comment]
Maybe "Warning: Unused lexical argument `args'" is an error.

**Comment by riscy** [comment]
Here's the latest from the checklist.  Regarding `args` in the byte-compile warnings, you can rename these variables to `_args` to hint to the compiler that they're deliberately unused.  Please also address the other feedback when you have time.

### imbot.el ###

byte-compile (using Emacs 26.3):
```
imbot.el:85:1:Warning: Unused lexical argument `args'
imbot.el:89:1:Warning: Unused lexical argument `args'
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
imbot.el:31: First sentence should end with punctuation
Warning (emacs): 
imbot.el:36: First sentence should end with punctuation
Warning (emacs): 
imbot.el:39: First sentence should end with punctuation
Warning (emacs): 
imbot.el:42: First sentence should end with punctuation
Warning (emacs): 
imbot.el:52: First sentence should end with punctuation
Warning (emacs): 
imbot.el:58: First sentence should end with punctuation
Warning (emacs): 
imbot.el:64: First sentence should end with punctuation
Warning (emacs): 
imbot.el:72: First sentence should end with punctuation
Warning (emacs): 
imbot.el:75: First sentence should end with punctuation
Warning (emacs): 
imbot.el:75: Lisp symbol `emulation-mode-map-alists' should appear in quotes
Warning (emacs): 
imbot.el:86: First sentence should end with punctuation
Warning (emacs): 
imbot.el:86: Argument `args' should appear (as ARGS) in the doc string
Warning (emacs): 
imbot.el:90: First sentence should end with punctuation
Warning (emacs): 
imbot.el:90: Argument `args' should appear (as ARGS) in the doc string
Warning (emacs): 
imbot.el:96: First sentence should end with punctuation
Warning (emacs): 
imbot.el:99: First sentence should end with punctuation
Warning (emacs): 
imbot.el:115: First sentence should end with punctuation
Warning (emacs): 
imbot.el:118: First sentence should end with punctuation
Warning (emacs): 
imbot.el:130: First sentence should end with punctuation
Warning (emacs): 
imbot.el:130: Lisp symbol `prog-mode' should appear in quotes
Warning (emacs): 
imbot.el:136: First sentence should end with punctuation
Warning (emacs): 
imbot.el:145: First sentence should end with punctuation
Warning (emacs): 
imbot.el:159: First sentence should end with punctuation
Warning (emacs): 
imbot.el:162: First sentence should end with punctuation
Warning (emacs): 
imbot.el:165: First sentence should end with punctuation
Warning (emacs): 
imbot.el:169: First sentence should end with punctuation
Warning (emacs): 
imbot.el:172: First sentence should end with punctuation
Warning (emacs): 
imbot.el:179: First sentence should end with punctuation
Warning (emacs): 
imbot.el:182: First sentence should end with punctuation
Warning (emacs): 
imbot.el:187: All variables and subroutines might as well have a documentation string
Warning (emacs): 
imbot.el:191: First sentence should end with punctuation
Warning (emacs): 
imbot.el:198: First sentence should end with punctuation
Warning (emacs): 
imbot.el:216: First sentence should end with punctuation
Warning (emacs): 
imbot.el:216: Argument `add-or-remove' should appear (as ADD-OR-REMOVE) in the doc string
Warning (emacs): 
imbot.el:21: White space found at end of line
```

package-lint (using version 20200419.406):
```
3 issues found:
158:0: error: "evil-normal-state-minor-mode" doesn't start with package's prefix "imbot".
161:0: error: "god-local-mode" doesn't start with package's prefix "imbot".
164:0: error: "hydra-curr-map" doesn't start with package's prefix "imbot".
```

**Comment by QiangF** [comment]
All should be fixed excpet the package-lint warning, these variables are defined in external packages. (My checkdoc has an error and can't run, but I have checked each warning)

**Comment by riscy** [comment]
Another quick surface-level scan --

checkdoc (using version 0.6.1):
```
Warning (emacs): 
imbot.el:75: Lisp symbol `emulation-mode-map-alists' should appear in quotes
Warning (emacs): 
imbot.el:140: First sentence should end with punctuation
Warning (emacs): 
imbot.el:207: Argument `add-or-remove' should appear (as ADD-OR-REMOVE) in the doc string
```

package-lint (using version 20200419.406):
```
3 issues found:
153:0: error: "evil-normal-state-minor-mode" doesn't start with package's prefix "imbot".
156:0: error: "god-local-mode" doesn't start with package's prefix "imbot".
159:0: error: "hydra-curr-map" doesn't start with package's prefix "imbot".
```
The reason package-lint is complaining about these is not just that you're defvaring them, but you're also specifying values (even though it's just `nil`) and docstrings for these variables.  Simply `(defvar evil-normal-state-minor-mode)` (for example) will fix it.

A couple more minor things while I'm looking:
- imbot.el#L196: It's safer to sharp-quote function names; use `#'`
- On line 222, the "else" part of an `if` doesn't require a `progn`
- You're currently reliant on a transitive import to give you `seq-find` but you might want to be ultra safe and `(require 'seq)` as well

**Comment by QiangF** [comment]
All fixed! Thank you!

**Comment by QiangF** [comment]
Compared to sis, imbot is much shorter and less complicated, it combined many hook into one. But I haven't used sis since I made imbot.

**Comment by riscy** [comment]
For this line:
```elisp
#'(imbot--english-p imbot--prefix-override-p)
```
..you should probably just be using a regular quote:
```elisp
'(imbot--english-p imbot--prefix-override-p)
```
but for example if you want to use the sharp-quote to denote functions, you'd use:
```elisp
(list #'imbot--english-p #'imbot--prefix-override-p)
```

It seems the byte-compiler is okay with this (at least in Emacs 26.3) so I won't block, but I'd recommend fixing that.  And, welcome to MELPA!

**Pull request merged**
