### PR TITLE
add zimwiki-mode

### PR DESCRIPTION
**Pull request by WillForan**
### Brief summary of what the package does
edit zim wiki text files in emacs with some of the convinces afford by zimwiki 

### Direct link to the package repository

https://github.com/WillForan/zimwiki-mode

### Your association with the package
I'm the package maintainer

### Relevant communications with the upstream package maintainer
**None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi!  Just a quick pass over the checklist:

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190905.1847):
```
7 issues found:

274:63: warning: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
280:68: warning: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
283:55: warning: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
284:70: warning: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
285:70: warning: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
289:54: warning: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
290:61: warning: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
zimwiki-mode.el:338:1:Warning: the following functions are not known to be
    defined: helm-do-ag, helm-projectile, dokuwiki-mode
```

**Comment by WillForan** [comment]
Thanks for the quick feedback @riscy! I updated upstream keybindings. I don't know how to address the compile warnings. I added `(require ...)` for the functions in packages also within `Package-Requires`. `make sandbox` seems to work fine.

**Comment by riscy** [comment]
It looks like adding the `require`s fixed the issue.

I'm looking at the definition of your major mode -- I notice you enable flyspell-mode, but it should be up to the user whether or not they do so.  I also notice that enabling your mode turns on dikuwiki-mode.  It feels like your mode should extend dikuwiki-mode (i.e. you should derive from dikuwiki-mode instead of text-mode).  Also, define-derive-mode will automatically do the work required to `(use-local-map zimwiki-mode-map)`, so you can drop that line.

I think you should also learn about the variable auto-mode-alist if you haven't seen it before.  Is there a standard extension that zim-wiki files use?  Basically a function like this should not need to exist (and removing functions like these could help you remove the dependency on, e.g., helm-projectile..)
```elisp
(defun zimwiki-helm-projectile ()
  "Go to a file using ‘helm-projectile’ (requires notebook in VCS)."
  (interactive)
  (helm-projectile)
  (zimwiki-mode))
```

A couple other minor things I'm noticing with the source buffer open:
- Your package's short description calls it "Zim *Deskopt* Wiki edit mode"
- Commentary lines should start with two semicolons (e.g. near "ffap code from", or "find a page")
- All closing parentheses should be gathered together on one line in elisp
- It feels like "zim" and "wiki" are two words, so why not call this package "zim-wiki-mode"?
- We try to avoid sending test functions to users -- the code in your tests at the bottom of the mode can go in a separate file (e.g. zim-wiki-test.el) that will be ignored by MELPA's default recipe

**Comment by WillForan** [comment]
Thanks for the careful (and kind!) feedback!
 - [x] "Desktop" typo fixed
 - [x] `;;` for comments
 - [x] `...)))` ending parens all in one place
 - [x] `zim-wiki-mode` is indeed the more appropriate name
 - [x] test code moved to `zim-wiki-mode-test.el`
 - [x] flyspell removed
 - [ ] I was totally unaware of `auto-mode-alist`, but zim uses the a `.txt` extension. Matching that would probably be too broad?
 - [ ] `helm-projectile` and `helm-ag` are used to mimic similar options in the desktop application: search notebook by page title, and by content. but there's bonus fuzzy search using helm
- [ ] I pushed `link-hinter` extension functions for dokuwiki-mode style links. Hopefully no new issues arise because of that. (package-lint made sure I named them with `zim-wiki-` prefix.)

**Comment by riscy** [comment]
Apologies for letting so much time pass.  I'm taking another look now --

The `define-derived-mode zim-wiki-mode` looks great, although the docstring could be updated to fix the typo: "Major mode for `editing` zim wiki."

You may want to sharp-quote the functions you call with your keybindings, e.g.
```elisp
(define-key map (kbd "C-c C-z")   #'zim-wiki-hydra/body)
```
This'll guarantee you get compiler errors in case the function doesn't exist (all your functions exist, don't worry).

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
4 issues found:

47:1: warning: Closing parens should not be wrapped onto new lines.
52:2: warning: Closing parens should not be wrapped onto new lines.
57:2: warning: Closing parens should not be wrapped onto new lines.
135:0: warning: Closing parens should not be wrapped onto new lines.
```

**Comment by WillForan** [comment]
Thanks! fixed warnings, typo, and added sharp quoting!

**Comment by riscy** [comment]
Great!  Sorry for the long waits.  This looks good to go, but I will comment that you don't need to (and probably shouldn't?) check your `zim-wiki-mode.elc` file into git since it should be created by the developers who check out your repo, and whatever version of Emacs they have installed.  Doesn't affect MELPA users of course.

And, welcome to MELPA!

**Comment by WillForan** [comment]
yikes! didn't mean to include that. Thanks for all the help!

**Pull request merged**
