### PR TITLE
Add recipe for sxiv.el

### PR DESCRIPTION
**Pull request by contrapunctus-1**
### Brief summary of what the package does

Runs sxiv, the Simple X Image Viewer

### Direct link to the package repository

https://gitlab.com/contrapunctus/sxiv.el

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```diff
new file   Cask
@@ -0,0 +1,4 @@
+(source gnu)
+(source melpa)
+
+(package-file "sxiv.el")
```

```
$ cask; cask build
Loading package information... done
Package operations: 2 installs, 0 removals
  - Installing [ 1/2] emacs (25.1)... already present
  - Installing [ 2/2] dash (2.16.0)... done
Compiling /home/conao/dev/forks/sxiv.el/sxiv.el...

In sxiv-dired-marked-files-p:
sxiv.el:53:32:Warning: reference to free variable ‘dired-re-mark’

In sxiv-dired-mark-files:
sxiv.el:71:28:Warning: reference to free variable ‘dired-re-dot’

In end of data:
sxiv.el:160:1:Warning: the following functions are not known to be defined:
    dired-insert-subdir, dired-mark-if, dired-get-filename,
    dired-file-name-at-point, dired-get-marked-files
```

**Comment by contrapunctus-1** [comment]
@conao3 thanks! Didn't realize I'd have to depend on Dired too. I've added and pushed a `(require 'dired)`, should I be adding it to the Package-Requires too?

**Comment by conao3** [comment]
I think it isn't needed. Other dired-related packages registered in MELPA don't seem to list `dired` as a dependency either. This is fulfilled by the requirements of Emacs version.

**Comment by purcell** [comment]
Thanks! Quick notes:

- Don't use `eq` to check `major-mode`, e.g. [here](https://gitlab.com/contrapunctus/sxiv.el/-/blob/dae46e6f5890f3d97d45eaadf0194b7ff01f6baf/sxiv.el#L51) - prefer `derived-mode-p`. That whole function could just be:
```el
(defun sxiv-dired-marked-files-p ()
  "Return t if there are marked files in the current Dired buffer.
With no marked files, or if not in a Dired buffer, return nil."
  (and (derived-mode-p 'dired-mode)
       (save-excursion
         (goto-char (point-min))
         (re-search-forward dired-re-mark nil t))))
```
- Looks good otherwise (putting aside my strong dislike of `dash`'s anaphoric macros)

In any case, this can be merged and you can consider the above in your own time. :-)

**Pull request merged**
