### PR TITLE
add recipe goldendict

### PR DESCRIPTION
**Pull request by stardiviner**
### Brief summary of what the package does

A simple wrapper of "goldendict" command as dictionary.

### Direct link to the package repository

https://github.com/stardiviner/goldendict.el

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi there,

This looks neat.  However, please be careful with calling shells with user input: https://github.com/stardiviner/goldendict.el/blob/master/goldendict.el#L42

You should at least escape it with `shell-quote-argument`, but you don't actually need to run it as a shell command at all.  Instead you can call the process directly.  Here's a macro that I use:
```el
(defmacro call-process-with-args (process &rest args)
  "Return results of running PROCESS with ARGS."
  (declare (indent defun))
  `(with-temp-buffer
     (unless (= 0 (call-process ,process nil t nil
                                ,@args))
       (user-error ,(concat process " failed")))
     (buffer-substring-no-properties (point-min) (point-max))))
```
Used like:
```el
(defun get-day-of-week (string)
  "Parse STRING with the GNU `date' command and return day-of-week as string."
  (call-process-with-args
    "date" "-d" string "+%a"))
```

**Comment by stardiviner** [comment]
I don't know how to use your code in my case. Because it does not show result in buffer. It popup a GUI popup window. So use shell command is fine I think.

**Comment by alphapapa** [comment]
> it does not show result in buffer. It popup a GUI popup window.

Ah, my mistake.  

> Thanks for your suggestion, I updated my code by applying shell-quote-argument on word.

Did you forget to push?  I don't see that change in your repo.  :)

However, you should probably still use `call-process`.  The docstring for `shell-command` says:
```
In Elisp, you will often be better served by calling ‘call-process’ or
‘start-process’ directly, since it offers more control and does not impose
the use of a shell (with its need to quote arguments).
```
Maybe I'm making too big a deal out of it, but as far as I know, it's generally safer and better to avoid using shell commands whenever possible.

**Comment by stardiviner** [comment]
@alphapapa Aha, Thanks, I see. I have not check out the docstring of `call-process`. I take your point. Will update code soon. Might network delay or push failed. I will check my code. Thanks.

**Comment by stardiviner** [comment]
Now, updated. Check it out. Thanks for reviewing.

**Comment by alphapapa** [comment]
Cool, although now you don't need to use `shell-quote-argument` on `word`.  :)

**Comment by stardiviner** [comment]
Done.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
