### PR TITLE
Add difftastic - an Emacs wrapper for difftastic

### PR DESCRIPTION
**Pull request by pkryger**
### Brief summary of what the package does

The `difftastic` is designed to integrate [`difftastic`](https://github.com/wilfred/difftastic) into your Emacs workflow, enhancing your code review and comparison experience. This package automatically displays `difftastic`'s output within Emacs using faces from your user theme, ensuring consistency with your overall coding environment.

### Direct link to the package repository

https://github.com/pkryger/difftastic.el

### Your association with the package

I am author and maintainer of this ps package

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thank you for this.  Why not call this package `difftastic`?  I think an exact match on the name would improve its discoverability.

Beyond that, a couple minor issues -- easy fixes:

`difft.el` with package-lint 20230806.1331:
```
1 issue found:
8:38: warning: Use a non-snapshot version number for dependency on "magit" if possible.
```

`difft.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- difft.el#L195: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)` in your personal config
```
(Optional but encouraged)

**Comment by tarsius** [comment]
> Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)` in your personal config

@riscy, IMO it be better to recommend to `consider ((emacs-lisp-mode (indent-tabs-mode . nil)) in dir-locals.el`. A mixture of different indentation styles is usually due to different people using different "personal" global values. Changing the personal value of one contributor, even if it is the maintainer, won't address that. Enforcing the project's style does. (Though it still requires an explicit `M-x untabify` for each elisp file, of course. It might make sense to point that out too.)

**Comment by riscy** [comment]
@tarsius Great points, and I probably should have thought more about that lint before inflicting it on people.  Also, I was unaware of `M-x untabify`!

**Comment by pkryger** [comment]
@riscy, @tarsius, thank you very much for your time spent reviewing this package.

I was wondering about the name and `difftastic` was a one that came to my mind. I didn't want to snatch the name from  @Wilfred, but the discoverability argument convinced me. Renamed it.

When it comes to `indent-tabs-mode` I'm from the camp of: set globally to nil. And this is how I have it my personal set up, so I have not double checked that copy/pasted code preserved spaces. Apologies for that. I think the `dir-locals.el` solution would be the best, but I went and `M-x untabify`'ied everything.

> `difft.el` with package-lint 20230806.1331:
> 
> ```
> 1 issue found:
> 8:38: warning: Use a non-snapshot version number for dependency on "magit" if possible.
> ```

In the code I used [`magit-thing-at-point`](https://github.com/magit/magit/blob/86b8491ce87a67551e1fb4261a41f2160ded590a/lisp/magit-section.el#L464) and that was added on 25 Mar 2022 [95b4325](https://github.com/magit/magit/tree/95b432530a6b131e63bec7411ee768f1dee9f629). Since the last `magit` release I was able to find was [3.3.0](https://stable.melpa.org/#/magit) I decided to go with snapshot (optimistically assumed 1 day after the commit). If you have a better approach to that, I'm happy to update.

**Comment by riscy** [comment]
Okay, that sounds within reason to me.  Thanks for accommodating. :)

Merging now -- and welcome to MELPA!

**Comment by riscy** [comment]
I'm noticing this just a little late, but your summary line says:

`Emacs wrapper for difftastic`

And in the MELPA index the "Emacs" part isn't necessary.  I'd just shorten to "Wrapper for difftastic" and that gives you extra room in case you want to add a bit more detail in the future.

**Comment by pkryger** [comment]
> [...] I'd just shorten to "Wrapper for difftastic" and that gives you extra room in case you want to add a bit more detail in the future.

Updated as suggested.

> Merging now -- and welcome to MELPA!

Thank you for merging! I'm glad to join 🙂.

**Comment by Wilfred** [comment]
Thanks for building this! No objection to you using the name :)

**Pull request merged**
