### PR TITLE
Create everlasting-scratch

### PR DESCRIPTION
**Pull request by beacoder**
The scratch buffer that lasts forever.

### Brief summary of what the package does
This package provides a global minor mode `everlasting-scratch-mode' that causes the scratch to respawn after it's killed and with its content restored, the scratch could survive manual kill and emacs restart (with help of desktop.el)

### Direct link to the package repository

https://github.com/beacoder/everlasting-scratch

### Your association with the package

author

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, looks like an interesting modification on top of the scratch buffer workflow.  Just a couple of quick questions to help my understanding of the implementation --

- I may be missing something but I'm confused by the logic in `everlasting-scratch-kill` -- isn't it simpler to just have this function return `nil` to prevent the scratch buffer from being killed in the first place, rather than messing around with the hook and then calling `(everlasting-scratch-respawn)`?
- Rather than `(advice-add #'everlasting-scratch-kill :before #'everlasting-scratch-save)`, why not just make `everlasting-scratch-save` check the value of the `everlasting-scratch-mode` variable to check whether the mode is enabled or not?

**Comment by beacoder** [comment]
Hi,
for the first question, we want to handle the normal kill and exit emacs the same way, so choose to save data before killing it or exiting emacs.
for second question, almost same reason, when emacs is up, of course you can prevent the buffer from being killed, but what I want is that the buffer data can survive the emacs restart as well, so we need to save data and then restore it.
then we're bound to do the save and restore thing, then why not do it for both scenarios: kill buffer when emacs is running, and exit emacs.
best regards.

**Comment by riscy** [comment]
I can see your first point - run the same code path every time.  I'm not sure I understand your response to the second point, though.  If I'm being a little more clear, why not just add `(when everlasting-scratch-mode (everlasting-scratch-save))` to the top of the definition of `everlasting-scratch-kill`?  In which case your mode won't have to add advice `(advice-add #'everlasting-scratch-kill :before #'everlasting-scratch-save)` and remove advice `(advice-remove #'everlasting-scratch-kill #'everlasting-scratch-save)` when the mode is toggled off/on respectively.

Ultimately I think that's pretty minor, though - happy to hit merge on this.

**Comment by beacoder** [comment]
thanks, I could try to improve it.

**Pull request merged**
