### PR TITLE
Add recipe for processing-3-mode

### PR DESCRIPTION
**Pull request by motform**
### Brief summary of what the package does

`processing-3-mode` is a minimalist mode for the third version of the Processing programming language. The `processing-mode` packade is more sophisticated/opinionated, but not updated for p3. This package has simpler ambitions, which it fulfils by leveraging the Processing command line tools.

### Direct link to the package repository

https://github.com/motform/processing-3-mode

### Your association with the package

I am the maintainer and creator.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
Please fix this issue:

>  Recipe ’processing-3-mode’ contains mismatched package name ’arduino-cli-mode’

**Comment by motform** [comment]
> Please fix this issue:
> 
> > Recipe ’processing-3-mode’ contains mismatched package name ’arduino-cli-mode’

That's what you get for copy-pasting while making New Years dinner. 😅 It's fixed now!

**Comment by riscy** [comment]
Re: the existing process-mode --

> is more sophisticated/opinionated, but not updated for p3

is this update something that you see can be fixed?  If it's feasible, that would be far better for users.  Maybe the ways in which it is opinionated can be turned into user options as well.  I don't see a lot of recent GitHub activity from @ptrv but I will leave this mention.

In the meantime, processing-3-mode.el#L170: Terminate auto-mode-alist entries with `\\'`

**Comment by riscy** [comment]
Hello, I just thought I'd ping and check if there's a followup.  Maybe my suggestion isn't possible, and we also haven't heard back from @ptrv so this is probably fine.  It looks like the auto-mode-alist entry still needs to be fixed.

**Comment by motform** [comment]
> Hello, I just thought I'd ping and check if there's a followup. Maybe my suggestion isn't possible, and we also haven't heard back from @ptrv so this is probably fine. It looks like the auto-mode-alist entry still needs to be fixed.

Hi, I have been busy with other things, but yes, in essence I agree with the your previous post that it would be much nicer if there was one Processing mode. Having version-defined modes is not very useful, esp. considering the fact that they are about to release P4, whose breaking changes are completely ignored by any type of editor mode.

I looked over @ptrv's mode and we more or less do the same things, sans how we handle the calls to the compiler (CLI front end vs path to the compiler). I think it would be optimal to patch/fork his mode with support for the latter method and maybe call it "Processing mode". I have sent him an email, will keep this thread updated.

**Pull request closed without merging**
