### PR TITLE
Add recipe for orderless

### PR DESCRIPTION
**Pull request by oantolin**
### Brief summary of what the package does

Completion style that matches multiple regexps in any order

### Direct link to the package repository

https://github.com/oantolin/orderless

### Your association with the package

I am the author and maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

byte-compile-file (using Emacs 26.3):
```
orderless.el:184:1:Warning: the function `orderless--highlight-matches' is not
    known to be defined.
```

The form that contains the defun seems a little bit unusual too (but I may not be familiar with what's going on there) so the issue might be lurking in there.

**Comment by oantolin** [comment]
I just wanted to avoid another global variable, when it is a constant used only in that one function. But if the byte-compiler complains about not finding the function definition inside the `let`, I guess I could flatten the structure. (I think the real fix is making the byte-compiler slightly smarter, but I'm definitely not going to try doing that... :D.)

I'll comment back here when I've made the change.

**Comment by oantolin** [comment]
Done, @riscy . Sorry about that. I guess I only byte-compiled it when that function was already defined, so I never noticed the byte-compiler's blindness to let forms.

**Comment by riscy** [comment]
No worries!  This looks great.  Thanks. :)

**Pull request merged**
