### PR TITLE
add proced-narrow

### PR DESCRIPTION
**Pull request by travisjeffery**
### Brief summary of what the package does

This package provdes live filtering of processes in proced buffers.  In general, after calling
proced-narrow you type a filter string into the minibuffer to filter the list of processes.  After
each change proced-narrow automatically reflects the change in the buffer. 

### Direct link to the package repository

https://github.com/travisjeffery/proced-narrow

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd>:
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
No issues! 🎊

<kbd>M-x byte-compile-file</kbd>:
```
proced-narrow.el:92:1:Warning: Unused lexical variable
    `proced-narrow-filter-function'
proced-narrow.el:118:1:Warning: Variable `proced-narrow-buffer' declared after
    its first use
proced-narrow.el:124:1:Warning: Variable `proced-narrow-filter-function'
    declared after its first use
```

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
No issues! 🎉

-------
- [#L130](https://github.com/travisjeffery/proced-narrow/blob/master/proced-narrow.el#L130): It is beneficial to sharp-quote hooks; use `#'`
- [#L133](https://github.com/travisjeffery/proced-narrow/blob/master/proced-narrow.el#L133): It is beneficial to sharp-quote hooks; use `#'`

**Comment by travisjeffery** [comment]
Thanks, I've addressed all the issues.

**Comment by purcell** [comment]
Thanks!

- The `:files` spec in the recipe is unnecessary, so you can remove it.
- Don't put a `Package-Version` [header](https://github.com/travisjeffery/proced-narrow/blob/e93fd5a46afc0c1dc6924290dad6c64570b60bb8/proced-narrow.el#L8) in the file. You don't need it because MELPA will add one. `Version` is enough to keep `package-lint` happy.
- With [this autoload](https://github.com/travisjeffery/proced-narrow/blob/e93fd5a46afc0c1dc6924290dad6c64570b60bb8/proced-narrow.el#L133), anything that uses the minibuffer before this file is loaded will explode. Removing the `;;;###autoload` cookie should fix this.
- You might consider preferring `seq` (or `cl-lib`) to `dash`, since it's built into newer Emacsen, and still available as a separate package for older Emacsen.

Hope that helps!

**Comment by travisjeffery** [comment]
@purcell @riscy thanks I've push fixed for all your comments. Removed the :files spec, removed the Package-version header, removed that autoload, and switched to seq.

**Comment by riscy** [comment]
It looks like the latest `seq` is 2.20 [from Elpa](https://elpa.gnu.org/packages/seq.html) which package-lint complains about too.

Other than that, everything appears to have been addressed -- feel free to ping when ready.

**Comment by travisjeffery** [comment]
Ah, I use emacs 27 and looked at its version of seq.  just pushed an update to use 2.20.

If you mean me to ping instead of @purcell I'm ready anytime.

**Comment by travisjeffery** [comment]
Thanks, @riscy.

**Comment by travisjeffery** [comment]
@riscy @purcell :ping_pong:

**Comment by riscy** [comment]
Doing some user testing on this -- sorry for the long turnaround.

I think you need to `(require 'delsel)` for `minibuffer-keyboard-quit` (`delsel` isn't always necessarily loaded).  It would probably be worthwhile to sharp-quote the functions on [these](https://github.com/travisjeffery/proced-narrow/blob/master/proced-narrow.el#L63-L65) lines -- flycheck would've told you about the issue with `minibuffer-keyboard-quit`.

This helpful hint:

> To bring it back to the original view, you can call `revert buffer' (usually bound to g).

...feels like it belongs in something users will typically access, like the docstring for the mode or the `proced-narrow` function.

Some minor stuff I'm noticing as I look at the source that might be helpful:
- `provdes` -> `provides`
- `minibufferto` -> `minibuffer to`
- `origininal` -> `original`
- `tthem` -> `them`

**Comment by travisjeffery** [comment]
@riscy sorry about those. I've pushed fixes for all of them. Thanks.

**Comment by riscy** [comment]
Great thanks.  I would still recommend sharp-quoting the functions [here](https://github.com/travisjeffery/proced-narrow/blob/df5cce50b3d1219b23d28e23cbf68e0c7807a15c/proced-narrow.el#L64-L66) (it's a good habit to get into).

For this documentation line [here](https://github.com/travisjeffery/proced-narrow/blob/df5cce50b3d1219b23d28e23cbf68e0c7807a15c/proced-narrow.el#L77), I'm realizing you could write the last sentence as: 
```elisp
"To bring it back to the original view, use \\[revert buffer]."
```
This way Emacs will automatically determine the keybinding (i.e. whether it's <kbd>g</kbd> or who-knows-what) when the help is displayed.

Those are more tips for your consideration than blockers, though, and this looks good.  Welcome to MELPA. :)

**Pull request merged**
