### PR TITLE
Add recipe for spdx

### PR DESCRIPTION
**Pull request by condy0919**
### Brief summary of what the package does

Insert SPDX license header.

### Direct link to the package repository

https://github.com/condy0919/spdx.el

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
I wondered when someone would write this!  Thanks.

One quick nag from the byte-compiler:

byte-compile (using Emacs 27.1):
```
spdx.el:606:1:Warning: the function `tempo-template-spdx' is not known to be
    defined.
```
Can this be silenced by forward-declaring the function with `declare-function`?

**Comment by condy0919** [comment]
> Can this be silenced by forward-declaring the function with declare-function?

Thanks for suggestion, the warning is silenced.

**Comment by riscy** [comment]
Great, taking a closer look now.  The docs say the output resembles this:

```
;Copyright (C) 2020  spdx.el Authors
;SPDX-License-Identifier: AGPL-1.0-only
```
Is this accurate?  I ask because single-line comments need to start with `;; ` (two semicolons and a space) or Emacs will get confused about how to indent them.

I also notice that GitHub is unable to auto-identify the license of your repository.  I'm not sure why this might be since you appear to be using a normally formatted LICENSE file -- maybe it's trying to read your "spdx" file as a license?  That's unfortunate but maybe it can't be helped.

And lastly, since you'll be maintaining this, I thought I'd check if you have any plans for how you'll keep the SPDX license list up to date.  Maybe you have a tool to do this, or you could mention in your README that you invite contributions from the community to help keep the list updated.

**Comment by condy0919** [comment]
> Is this accurate? I ask because single-line comments need to start with ;; (two semicolons and a space) or Emacs will get confused about how to indent them.

Fixed, now there will be `;; ` (two semicolons follows a space).

``` emacs-lisp
;; Copyright (C) 2020  spdx.el Authors
;; SPDX-License-Identifier: AGPL-1.0-only
```

> I also notice that GitHub is unable to auto-identify the license of your repository. I'm not sure why this might be since you appear to be using a normally formatted LICENSE file -- maybe it's trying to read your "spdx" file as a license? That's unfortunate but maybe it can't be helped.

The LICENSE file is auto generated when the repository created. Clicking the
`View license` in the repository page will redirect to the file. It does
identify the license file.

> And lastly, since you'll be maintaining this, I thought I'd check if you have any plans for how you'll keep the SPDX license list up to date. Maybe you have a tool to do this, or you could mention in your README that you invite contributions from the community to help keep the list updated.

Notes about contribution is added in the README, needs the help of community!
Maybe the CI should check the latest license version per week?

**Comment by riscy** [comment]
I'm surprised that the auto-generated license isn't detectable by GitHub's use of licensee.  Would you indulge me and try copying the (very slightly different) LICENSE file from your [emacs.d](https://github.com/condy0919/.emacs.d), which seems recognizable, into this repository?

**Comment by condy0919** [comment]
image

Thanks, now it shows properly

**Comment by riscy** [comment]
Thanks, with that out of the way I tried this on a few files and it works really well.

It seems like it's doing two things -- adding boilerplate for a Copyright and a License, and I guess technically those are two very different things.  I suggest you have two functions, one for the license and one for the copyright (and one for _both_ if you like).  You could also change your summary line to "Insert SPDX license and copyright headers".

Incidentally I noticed there is already a copyright.el that comes packaged with Emacs and you could mention in your README/Commentary, but ironically it inserts `; comments like this` instead of `;; comments like this` in Elisp files, so your solution is better.

One last way I see to go whole hog with this solution is to first check if the file already has SPDX identifiers and/or copyright lines first to limit conflicting bits of boilerplate.  If there already is such a line, you could prompt the user whether or not to update/replace them.

**Comment by riscy** [comment]
It appears that this was sorted out -- merging.  Thanks, and welcome to MELPA. :)

**Comment by condy0919** [comment]
Thanks

**Pull request merged**
