### PR TITLE
Add recipe for sly-overlay

### PR DESCRIPTION
**Pull request by fosskers**
### Brief summary of what the package does

`sly-overlay` adds evaluation overlays for Common Lisp in the spirit of CIDER and EROS.

### Direct link to the package repository

https://git.sr.ht/~fosskers/sly-overlay

### Your association with the package

Maintainer.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`sly-overlay.el` with byte-compile using Emacs 29.1:
```
sly-overlay.el:27:2: Error: Cannot open load file: No such file or directory, sly
```
I think the `Package-Requires` needs a dependency on sly is all.

**Comment by fosskers** [comment]
Done, thanks. `flycheck` on my end is telling me:

> Package sly is not installable.

Not sure what that's about.

**Comment by riscy** [comment]
Thanks!  Merging this.

**Comment by fosskers** [comment]
Quick follow-up: I'm able to install `sly-overlay` from MELPA fine, but I can't seem to get it to show up in the website's search results. Any ideas?

**Comment by riscy** [comment]
Apologies for responding to this years later - it fell off.  I can assure you it's appearing there now, so I think it may have just been a data refresh delay (probably on the order of days not years ;)

**Comment by fosskers** [comment]
Weird, thanks.

**Pull request merged**
