### PR TITLE
add session-async to melpa

### PR DESCRIPTION
**Pull request by FelipeLema**
### Brief summary of what the package does

Package for doing asynchronous processing in Emacs, just like [`async.el`](https://github.com/jwiegley/emacs-async)

Unlike `async.el`, the API for this package provides a separate Emacs session that can stay alive across async calls.

### Direct link to the package repository

https://codeberg.org/FelipeLema/session-async.el

### Your association with the package

Maintainer and owner 

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

People in https://github.com/astahlman/ob-async/issues/1 are probably interested in this package.

### CODE REVIEW

**Comment by alphapapa** [comment]
This is a super cool idea.

**Comment by riscy** [comment]
Yeah, I like this. It's generalizing what flycheck uses to check elisp files in a clean runtime.  Here's a quick run over the checklist (nothing major, and nothing that's hard to fix):

### session-async.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
session-async.el:175: Argument `conn' should appear (as CONN) in the doc string
Warning (emacs): 
session-async.el:302: Argument `conn' should appear (as CONN) in the doc string
```

package-lint (using version 20210528.2348):
```
2 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
11:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```

Other [lints](https://github.com/riscy/melpazoid):
- session-async.el#L77: It's safer to sharp-quote function names; use `#'`
- session-async.el#L132: It's safer to sharp-quote function names; use `#'`
- session-async.el#L278: It's safer to sharp-quote function names; use `#'`
- session-async.el#L263: This double negation can be collapsed (`not` aliases `null`)

**Comment by FelipeLema** [comment]
hey @riscy , I think I've addressed all of your comments now

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
