### PR TITLE
Add cmd-to-echo recipe

### PR DESCRIPTION
**Pull request by mallt**
### Brief summary of what the package does

Show the output of long-running commands (f.ex. javascript bundlers) in the echo area.
### Direct link to the package repository

https://github.com/mallt/cmd-to-echo
### Your association with the package

I am the maintainer
### Relevant communications with the upstream package maintainer

/
### Checklist
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- `compgen` works only on bash. zsh implements it too but it is a shell function so it does not work with `shell-command-to-string`. I suppose `bash -c 'compgen -c'` is better than it. For example `(process-lines "bash" "-c" "compgen -c")`

**Comment by mallt** [comment]
Thank you @syohex! I've replaced the shell-command-to-string with process-lines.

**Comment by purcell** [comment]
This looks really handy, but tying this code to `bash` by calling out to the shell is a bad idea, sorry. Just read a string, and consider using `shell-command-history` or `compile-history`.

**Comment by mallt** [comment]
Hi @purcell, maybe I could also ignore any errors for the completion command:
`(completing-read "Command: "
                 (ignore-errors
                     (process-lines "bash" "-c" "compgen -c")))`

This way people using bash will still get the command completions.

Thanks!

**Comment by purcell** [comment]
It's still not a great idea IMO. No comparable package does anything like this merely for the sake of convenient completions.

In fact, I dug a bit deeper, and there's a standard `read-shell-command` function in `simple.el` -- you should just use that! :-)  Then if you want to add some magic completion for that function, you can `fset` it to a custom version something more to your liking, without changing this package directly.

**Comment by mallt** [comment]
Thanks a lot for the help @purcell, that is indeed exactly what I was looking for! I'm sorry to have missed that function... I've updated the repo.

**Comment by purcell** [comment]
Yay, great - merged! I'll have to add this to my own config.

It occurred to me that it might be quite nice to make a further command which could be run in a `*Shell command*` or `*Compilation*` buffer, such that it would hide the buffer and then start piping output through to the echo area...

**Comment by mallt** [comment]
Thanks!

That would be nice indeed, I quickly looked at it but I think this might require tweaking the internals of `shell-command` or `compile` as I don't immediately see an option to specify a custom filter for these functions.

**Pull request merged**
