### PR TITLE
This pull request adds a new recipe for `greader`, a library for hand…

### PR DESCRIPTION
**Pull request by michelangelo-rodriguez**
…ling TTS (text-to-speech) tasks within an Emacs buffer.

**Features of `greader`**:
- Read an Emacs buffer using TTS.
- Convert a buffer to an audiobook.
- Translate a buffer "on-the-fly" while reading using the `google-translate` package (already available on MELPA).
- Additional functionalities to enhance the TTS experience in Emacs.

Thank you for considering this addition.

### Brief summary of what the package does

[Please write a quick summary of the package.]

### Direct link to the package repository

https://github.com/your/awesome_package

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [] My elisp byte-compiles cleanly
- [] I've used `M-x checkdoc` to check the package's documentation strings
- [] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
upstream URL: https://gitlab.com/michelangelo-rodriguez/greader

**Comment by riscy** [comment]
Thanks for this.  Note I've also updated your recipe to work with the gitlab package builder.  In the meantime, here's a quick first pass.  Please let me know if any of the formatting in the text below could be improved for readability, since it includes a lot of markup.

`greader-audiobook.el` with package-lint 20240507.1722 and `package-lint-main-file` = "greader.el":
```
1 issue found:
10:0: error: Package-Requires outside the main file have no effect.
```
This "outside the main file" issue is very minor; not a big worry.

`greader-audiobook.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- greader-audiobook.el#L271: It's safer to sharp-quote function names; use `#'`
- greader-audiobook.el#L301: It's safer to sharp-quote function names; use `#'`
```

`greader-dict.el` with package-lint 20240507.1722 and `package-lint-main-file` = "greader.el":
```
4 issues found:
9:0: error: Package-Requires outside the main file have no effect.
15:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
291:0: error: "string-hash-ignore-case" doesn't start with package's prefix "greader".
292:3: error: You should depend on (emacs "26.1") if you need `sxhash-equal'.
```
You can of course disregard the emacs 26.1 issue, because you are using compat.

`greader-dict.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- greader-dict.el#L128: Have you done the paperwork to assign this copyright?
- greader-dict.el#L773: you should use `shell-quote-argument` on greader-dict-filename
- greader-dict.el#L506: `concat` may be unneeded; `insert` can take multiple arguments
```

`greader-espeak.el` with package-lint 20240507.1722 and `package-lint-main-file` = "greader.el":
```
1 issue found:
12:2: warning: Closing parens should not be wrapped onto new lines.
```

`greader-espeak.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- greader-espeak.el#L2: Have you done the paperwork to assign this copyright?
```

`greader-mac.el` with package-lint 20240507.1722 and `package-lint-main-file` = "greader.el":
```
1 issue found:
10:2: warning: Closing parens should not be wrapped onto new lines.
```

`greader-mac.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- greader-mac.el#L65: It's safer to sharp-quote function names; use `#'`
- greader-mac.el#L2: Have you done the paperwork to assign this copyright?
```

`greader-speechd.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- greader-speechd.el#L3: Have you done the paperwork to assign this copyright?
```

`greader-translate.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- greader-translate.el#L97: Lighter should start with a space
```

`greader.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- greader.el#L3: Have you done the paperwork to assign this copyright?
- greader.el#L1554: Avoid `with-no-warnings` if the root cause can be addressed
- greader.el#L1228: `read-string` prompts should often end with a space
- greader.el#L1231: `read-string` prompts should often end with a space
- greader.el#L1246: `concat` may be unneeded; `insert` can take multiple arguments
```

`#'load`-check on each file:
```
Loading greader.el
  greader.el:Error: Emacs 29.3:
  (void-function greader-espeak)
```

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee
- greader-espeak.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- greader-mac.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by michelangelo-rodriguez** [comment]
Chris Rayner ***@***.***> writes:

> Thanks for this. Note I've also updated your recipe to work with the gitlab package builder. In
> the meantime, here's a quick first pass. Please let me know if any of the formatting in the
> text below could be improved for readability, since it includes a lot
> of markup.
Thanks, I fixed all the issues signaled by `package-lint' installed from
melpa.
Does exists something like "melpazoid" only for lisp analysis?
Thanks and best regards.

**Comment by riscy** [comment]
> Does exists something like "melpazoid" only for lisp analysis?

package-lint is the closest in terms of just checking your elisp, and to be honest I have been thinking I should try to rewrite some of the best melpazoid checks and see if I can get them merged into package-lint.  You can run melpazoid.el standalone (without all the installation checks) but it's not well-documented yet. :)

Here's the remaining minor stuff:

- greader-audiobook.el#L277: It's safer to sharp-quote function names; use `#'`
- greader-audiobook.el#L307: It's safer to sharp-quote function names; use `#'`
- greader-dict.el#L504: `concat` may be unneeded; `insert` can take multiple arguments
- greader-mac.el#L64: It's safer to sharp-quote function names; use `#'`
- greader.el#L1245: `concat` may be unneeded; `insert` can take multiple arguments

And medium stuff:

- greader-translate.el#L97: Lighter should start with a space
- greader.el#L1227: `read-string` prompts should often end with a space
- greader.el#L1230: `read-string` prompts should often end with a space

And one major item, I believe, if I try to load greader.el directly -
```
Loading greader.el
  greader.el:Error: Emacs 29.3:
  (void-function greader-espeak)
```

And the license checks:
- Try to use a standard license file format for your repo
    See: https://github.com/licensee/licensee
    e.g. https://www.gnu.org/licenses/gpl-3.0.txt
- greader-espeak.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- greader-mac.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by michelangelo-rodriguez** [comment]
Chris Rayner ***@***.***> writes:

>  Does exists something like "melpazoid" only for lisp analysis?
>
> package-lint is the closest in terms of just checking your elisp, and to be honest I have been
> thinking I should try to rewrite some of the best melpazoid checks and see if I can get them
> merged into package-lint. You can run melpazoid.el standalone (without all the installation
> checks) but it's not well-documented yet. :)
>
> Here's the remaining minor stuff:
>
> * greader-audiobook.el#L277: It's safer to sharp-quote function names; use #'
> * greader-audiobook.el#L307: It's safer to sharp-quote function names; use #'
> * greader-dict.el#L504: concat may be unneeded; insert can take multiple arguments
> * greader-mac.el#L64: It's safer to sharp-quote function names; use #'
> * greader.el#L1245: concat may be unneeded; insert can take multiple arguments
>
> And medium stuff:
>
> * greader-translate.el#L97: Lighter should start with a space
> * greader.el#L1227: read-string prompts should often end with a space
> * greader.el#L1230: read-string prompts should often end with a space
>
> And one major item, I believe, if I try to load greader.el directly -
>
> Loading greader.el
>   greader.el:Error: Emacs 29.3:
>   (void-function greader-espeak)
I fixed All stuff except loading greader.el: I cannot reproduce the
error, but `greader-espeak' is an autoloaded function: could you tell me
how you get this error?
Thanks again.
Michelangelo Rodriguez

**Comment by riscy** [comment]
> `greader-espeak' is an autoloaded function: could you tell me how you get this error?

I test the case where a user is loading your package directly from their load-path.  In general I think packages shouldn't rely on autoloading to get around issues with physical design/dependency hierarchy, because this is an optional convenience feature for users.

**Comment by michelangelo-rodriguez** [comment]
> `greader-espeak' is an autoloaded function: could you tell me how you get this error?
> 
> I test the case where a user is loading your package directly from their load-path. In general I think packages shouldn't rely on autoloading to get around issues with physical design/dependency hierarchy, because this is an optional convenience feature for users.
> 
Ok, it should work.
Michelangelo

**Comment by riscy** [comment]
Thank you for accommodating -- this is much improved.  Here's the only salient issue I see:

- greader-translate.el#L97: Lighter should start, but not end, with a space

**Comment by michelangelo-rodriguez** [comment]
> 
> 
> Thank you for accommodating -- this is much improved. Here's the only salient issue I see:
> 
> greader-translate.el#L97: Lighter should start, but not end, with a space
Ok, fixed.
Thanks
Michelangelo

**Comment by riscy** [comment]
Thanks again!

**Pull request merged**
