### PR TITLE
Create evangelion-theme

### PR DESCRIPTION
**Pull request by crmsnbleyd**
### Brief summary of what the package does

It's a dark theme

### Direct link to the package repository

https://github.com/crmsnbleyd/evangelion-theme

### Your association with the package

Maintainer

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

Screenshot_20240901_193752

### CODE REVIEW

**Comment by riscy** [comment]
Thank you!

**Comment by tarsius** [comment]
You should not `(provide 'evangelion)`. `(provide-theme 'evangelion)` takes care of providing `evangelion-theme` (it appends the `-theme`), which is the correct feature to provide, since it has to match the name of the library `evangelion-theme.el`.

**Comment by riscy** [comment]
This is a good point @tarsius and also something I can keep a check on going forward.

**Comment by tarsius** [comment]
Another reminder: @crmsnbleyd Please drop the `(provide 'evangelion)`.

**Comment by crmsnbleyd** [comment]
heu @tarsius really sorry for the delay, I haven't been checking my github notifications :/ updating ASAP

**Pull request merged**
