### PR TITLE
Add zen-mode recipe

### PR DESCRIPTION
**Pull request by kristate**
### Brief summary of what the package does

`zen-mode` provides syntax highlighting for the [Zen Programming Language](http://zen-lang.org).

### Direct link to the package repository

https://github.com/zenlang/zen-mode

### Your association with the package

I am the maintainer of the `zen-mode` package.

### Relevant communications with the upstream package maintainer

N/A

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

Thank-you.

### CODE REVIEW

**Comment by riscy** [comment]
### zen-mode.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
zen-mode.el:156: All variables and subroutines might as well have a documentation string
Warning (emacs): 
zen-mode.el:157: All variables and subroutines might as well have a documentation string
Warning (emacs): 
zen-mode.el:158: All variables and subroutines might as well have a documentation string
Warning (emacs): 
zen-mode.el:161: All variables and subroutines might as well have a documentation string
Warning (emacs): 
zen-mode.el:171: All interactive functions should have documentation
Warning (emacs): 
zen-mode.el:228: You should convert this comment to documentation
Warning (emacs): 
zen-mode.el:262: All variables and subroutines might as well have a documentation string
Warning (emacs): 
zen-mode.el:274: All variables and subroutines might as well have a documentation string
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
11 issues found:

22:0: error: Package should have a non-empty ;;; Commentary section.
116:0: error: Customization groups should not end in "-mode" unless that name would conflict with their parent group.
146:5: warning: Closing parens should not be wrapped onto new lines.
265:4: error: You should depend on (emacs "24.1") if you need `syntax-propertize-rules'.
303:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
304:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
305:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
309:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
310:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
311:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
312:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
zen-mode.el:113:1:Warning: unescaped character literals `?)', `?]' detected!
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other static checks:
- zen-mode.el#L149: No need to sharp-quote lambdas (but also no harm)
- zen-mode.el#L295: No need to sharp-quote lambdas (but also no harm)
- zen-mode.el#L20: Prefer `https` over `http` (if possible)

**Comment by kristate** [comment]
> M-x checkdoc (using version 0.6.1):


> M-x package-lint-current-buffer (using version 20191124.132):


> M-x byte-compile-file (using Emacs 26.3):

Fixed.

> Other static checks:

Fixed.

**Comment by kristate** [comment]
> M-x checkdoc (using version 0.6.1):

```
Checkdoc: Done.
```

> M-x package-lint-current-buffer (using version 20191124.132):

`No issues found.`

> M-x byte-compile-file (using Emacs 26.3):

Fixed.

> Other static checks:

Fixed.

---

Thank-you.

**Comment by riscy** [comment]
It seems there are a few different Zenlangs, but this one is by far the most active.  Thanks for this -- looks great.

**Pull request merged**
