### PR TITLE
Add recipe for ibrowse

### PR DESCRIPTION
**Pull request by nicolas-graves**
### Brief summary of what the package does

ibrowse stands for interactive browse, its goal is to be able to control your browser through common actions, be it on browser tabs, history or bookmarks using Emacs. 

It relies on the `completing-read` built-in interface, and thus benefits greatly from integration with `consult`, `marginalia` and `vertico`. 

### Direct link to the package repository

https://git.sr.ht/~ngraves/ibrowse.el

### Your association with the package

Author and maintainer

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`ibrowse-bookmark.el` with package-lint 20221003.1636:
```
17 issues found:
1:0: error: Error parsing main package file "ibrowse.el": (error Package lacks a file header)
1:70: warning: You should depend on (emacs "24.1") if you need lexical-binding.
8:0: error: Package-Requires outside the main file have no effect.
34:10: error: You should depend on (emacs "26.1") if you need `radix-tree'.
83:19: error: You should depend on (emacs "24.4") if you need `string-suffix-p'.
86:17: error: You should depend on (emacs "26.1") if you need `radix-tree-subtree'.
88:13: error: You should depend on (emacs "26.1") if you need `radix-tree-subtree'.
89:13: error: You should depend on (emacs "24.4") if you need `string-remove-suffix'.
95:24: error: You should depend on (emacs "26.1") if you need `radix-tree-subtree'.
96:24: error: You should depend on (emacs "26.1") if you need `radix-tree-subtree'.
97:24: error: You should depend on (emacs "26.1") if you need `radix-tree-subtree'.
124:3: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
126:9: error: You should depend on (emacs "25.1") or the seq package if you need `seq-mapcat'.
139:3: error: You should depend on (emacs "25.1") or the seq package if you need `seq-mapcat'.
144:18: error: You should depend on (emacs "25.1") if you need `alist-get'.
150:6: error: You should depend on (emacs "25.1") or the seq package if you need `seq-reduce'.
150:34: error: You should depend on (emacs "26.1") if you need `radix-tree-insert'.
```

`ibrowse-core.el` with package-lint 20221003.1636:
```
10 issues found:
1:0: error: Error parsing main package file "ibrowse.el": (error Package lacks a file header)
1:65: warning: You should depend on (emacs "24.1") if you need lexical-binding.
10:0: error: Package-Requires outside the main file have no effect.
32:10: error: You should depend on (emacs "25.1") or the seq package if you need `seq'.
69:5: error: You should depend on (emacs "25.1") or the seq package if you need `seq-sort'.
71:6: error: You should depend on (emacs "25.1") or the seq package if you need `seq-filter'.
85:3: error: You should depend on (emacs "24.1") if you need `pcase'.
86:11: error: You should depend on (emacs "24.3") if you need `user-error'.
88:8: error: You should depend on (emacs "24.3") if you need `user-error'.
119:5: error: You should depend on (emacs "24.1") if you need `pcase'.
```

`ibrowse-embark.el` with byte-compile using Emacs 28.1:
```
ibrowse-embark.el:32:1: Error: Cannot open load file: No such file or directory, marginalia
```
I think this is due to a missing `Package-Requires` in the main file.

`ibrowse-embark.el` with package-lint 20221003.1636:
```
3 issues found:
1:0: error: Error parsing main package file "ibrowse.el": (error Package lacks a file header)
1:67: warning: You should depend on (emacs "24.1") if you need lexical-binding.
7:0: error: Package-Requires outside the main file have no effect.
```

`ibrowse-history.el` with package-lint 20221003.1636:
```
5 issues found:
1:0: error: Error parsing main package file "ibrowse.el": (error Package lacks a file header)
1:68: warning: You should depend on (emacs "24.1") if you need lexical-binding.
8:0: error: Package-Requires outside the main file have no effect.
34:12: error: You should depend on (emacs "24.4") if you need `subr-x'.
106:12: error: You should depend on (emacs "25.1") if you need `pcase-lambda'.
```

`ibrowse-history.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ibrowse-history.el#L90: Consider using %F instead of %Y-%m-%d in time strings
```

`ibrowse-tab.el` with package-lint 20221003.1636:
```
6 issues found:
1:0: error: Error parsing main package file "ibrowse.el": (error Package lacks a file header)
1:60: warning: You should depend on (emacs "24.1") if you need lexical-binding.
7:0: error: Package-Requires outside the main file have no effect.
36:3: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
45:11: error: You should depend on (emacs "25.1") or the seq package if you need `seq-map'.
46:20: error: You should depend on (emacs "27.1") if you need `json-parse-buffer'.
```

`ibrowse.el` with package-lint 20221003.1636:
```
1 issue found:
1:0: error: package.el cannot parse this buffer: Package lacks a file header
```

`#'load`-check on each file:
```
Loading ibrowse-bookmark.el
Loading ibrowse-core.el
Loading ibrowse-embark.el
  ibrowse-embark.el:Error: Emacs 28.1:
  (file-missing "Cannot open load file" "No such file or directory" "marginalia")
Loading ibrowse-history.el
Loading ibrowse-tab.el
Loading ibrowse.el
```

**Comment by nicolas-graves** [comment]
Hi ! 
Thanks for the review and sorry for all errors, I had forgotten warnings on the header, the rest should be fixed in the current repo. 

I still do have doubts on how to manage the error of marginalia, since I can byte-compile the file, and that embark is given the same treatment as marginalia without any errors. 

Do you have any clue on what I should do about the marginalia error ? Or should I just update the pull request instead? 

Thanks again!

**Comment by nicolas-graves** [comment]
Thanks @minad for your help. 

@riscy, I've added a commit removing marginalia dependency by following minad's recommendations, all errors from the first pass are now corrected, ready for a review ;)

**Comment by riscy** [comment]
Thanks both!  @minad I've added a check on my end to try to ensure nobody has a dependency on marginalia.

@nicolas-graves There's one byte-compile nag arising:

`ibrowse-embark.el` with byte-compile using Emacs 28.1:
```
ibrowse-embark.el:31:1: Error: Cannot open load file: No such file or directory, embark
```
which I believe just points to a missing dependency.

**Comment by minad** [comment]
> Thanks both! @minad I've added a check on my end to try to ensure nobody has a dependency on marginalia.

Thanks, @riscy! That's a good idea.

**Comment by nicolas-graves** [comment]
@riscy Indeed, it's now fixed ;)

**Comment by minad** [comment]
@nicolas-graves You could also avoid the Embark dependency. See for example Prot's tmr package as an example: https://github.com/protesilaos/tmr/blob/c71f0e2f3ad81e2b3c99aa0874777fdb82704a8b/tmr.el#L474-L519

**Comment by riscy** [comment]
Thanks for all the changes.  Here's the latest --

`ibrowse-bookmark.el` with package-lint 20221003.1636:
```
1 issue found:
8:0: error: Package-Requires outside the main file have no effect.
```
You should be aware of this in each file (I won't repeat this error for each file though).

`ibrowse-embark.el` with byte-compile using Emacs 28.1:
```
ibrowse-embark.el:58:27: Warning: the function
    `ibrowse-bookmark-insert-markdown-link' is not known to be defined.
ibrowse-embark.el:57:27: Warning: the function
    `ibrowse-bookmark-insert-org-link' is not known to be defined.
ibrowse-embark.el:56:27: Warning: the function `ibrowse-bookmark-copy-url' is
    not known to be defined.
ibrowse-embark.el:55:27: Warning: the function `ibrowse-bookmark-delete' is
    not known to be defined.
ibrowse-embark.el:54:27: Warning: the function `ibrowse-bookmark-browse-url'
    is not known to be defined.
ibrowse-embark.el:48:27: Warning: the function
    `ibrowse-history-insert-markdown-link' is not known to be defined.
ibrowse-embark.el:47:27: Warning: the function
    `ibrowse-history-insert-org-link' is not known to be defined.
ibrowse-embark.el:46:27: Warning: the function `ibrowse-history-copy-url' is
    not known to be defined.
ibrowse-embark.el:45:27: Warning: the function `ibrowse-history-delete' is not
    known to be defined.
ibrowse-embark.el:44:27: Warning: the function `ibrowse-history-browse-url' is
    not known to be defined.
ibrowse-embark.el:38:27: Warning: the function
    `ibrowse-tab-insert-markdown-link' is not known to be defined.
ibrowse-embark.el:37:27: Warning: the function `ibrowse-tab-insert-org-link'
    is not known to be defined.
ibrowse-embark.el:36:27: Warning: the function `ibrowse-tab-copy-url' is not
    known to be defined.
ibrowse-embark.el:35:27: Warning: the function `ibrowse-tab-close' is not
    known to be defined.
ibrowse-embark.el:34:27: Warning: the function `ibrowse-tab-select' is not
    known to be defined.
```

`ibrowse-embark.el` with package-lint 20221003.1636:
```
5 issues found:
7:0: error: Package-Requires outside the main file have no effect.
32:0: error: "embark-browser-tab-actions" doesn't start with package's prefix "ibrowse".
42:0: error: "embark-browser-history-actions" doesn't start with package's prefix "ibrowse".
52:0: error: "embark-browser-bookmark-actions" doesn't start with package's prefix "ibrowse".
66:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```
The `with-eval-after-load` is on point, in this case.  If the user wants this behavior, it looks to me like you should be implementing a global minor mode that can be toggled off and on.  And then users can -- in their confugirations -- write `(with-eval-after-load 'embark (ibrowse-embark-mode))`

**Comment by minad** [comment]
@riscy

> The with-eval-after-load is on point, in this case. If the user wants this behavior, it looks to me like you should be implementing a global minor mode that can be toggled off and on. And then users can -- in their confugirations -- write (with-eval-after-load 'embark (ibrowse-embark-mode))

No, the warning is not on point. I wouldn't have made the recommendation in https://github.com/melpa/melpa/pull/8350#issuecomment-1396948933 if `with-eval-after-load` wasn't justified here. In this case ibrowse registers a bunch of keymaps in Embark, which does not have any negative or unexpected effects. Such registration of functionality across packages is common and is better than creating a separate integration package which in this case would have to depend on both Embark and Ibrowse. Introducing a minor mode is complete overkill, for code that essentially adds three elements to a list. Note that minor modes are exposed as interactive functionality via M-x and as such clutters the UI presented to the user.

I already mentioned the TMR package in https://github.com/melpa/melpa/pull/8350#issuecomment-1396948933, which does a similar registration with Embark.

As a related example, my Consult package has certain auto-registration of functionality depending on the current completion UI (https://github.com/minad/consult/blob/4a7167c331d3c0c0d60b1d2d54c840f33e446683/consult.el#L4935-L4940). It would be much much harder for the user if these integrations would have to be turned on manually or even worse would have to be installed as separate packages.

Generally I think the `with-eval-after-load' warning of package-lint is too aggressive and shouldn't apply to scenarios where only a small bit of inter-package registration is performed. However of course one shouldn't use code like the following. This should stay discouraged:

~~~ elisp
(with-eval-after-load 'foo
   (defun ibrowse-foo ()
      (interactive)
      ...))
~~~

**Comment by nicolas-graves** [comment]
I've fixed undefined function and package-requires errors, and renamed properly variables in ibrowse-embark. 
The warning for `with-eval-after-load` is still present, but I don't have sufficient expertise to decide on this debate.

**Comment by riscy** [comment]
Thanks both.  I often make mistakes when reviewing, so I appreciate you pointing out where I'm making wrong turns, @minad.  But let me try to explain where I think this case can go wrong:

> In this case ibrowse registers a bunch of keymaps in Embark, which does not have any negative or unexpected effects. 

Here's the form in question:

```elisp
(with-eval-after-load 'embark
  (when (fboundp 'ibrowse-tab--get-candidates)
    (add-to-list
     'embark-keymap-alist
     '(browser-tab . ibrowse-embark-tab-actions)))
  ...
```
If a user's config contains `(require 'embark) (require 'ibrowse-embark) (require 'ibrowse-embark-tab)` in that order, then we will not add the `ibrowse-embark-tab-actions` bindings.  But if a user's config contains `(require 'embark) (require 'ibrowse-embark-tab) (require 'ibrowse-embark)` in *that* order, we *will* add the keybindings.  I think when situations like this arise again and again, it can turn users' configs into a house of cards.

But I'm not extremely familiar with embark, and maybe this the convention.

Let me know what you (both) think.  Otherwise the code looks good @nicolas-graves. :)

**Comment by minad** [comment]
@riscy I am not sure what the `fboundp` check is doing in the `with-eval-after-load` block here. 

But nothing can go wrong due to Embark in this case. The Embark package provides minibuffer actions triggered by `embark-act`. As soon as ibrowse is loaded, e.g., by starting a completion session from the ibrowse package itself (ibrowse is loaded at that point), the registration with Embark will be performed by the `with-eval-afte-load` block if Embark is already loaded. If Embark is not available at that point, it will be loaded as soon as the users presses the `embark-act` key from inside the completion session, which will then finally trigger the registration of the keymap. 

The loading order does not matter. In every case the registered actions will be available when acting with `embark-act`. The convention used here may be specific to Embark, but it is fine.

As I said in https://github.com/melpa/melpa/pull/8350#issuecomment-1399330846 I wouldn't have made the recommendation otherwise.

**Comment by nicolas-graves** [comment]
@riscy Thanks for pointing that out, I've refactored it without thinking about this possibility. 

I wanted users to have the possibility to use any subset of {`ibrowse-tab.el`, `ibrowse-history.el`, `ibrowse-bookmark.el`}. 

I'm going to simplify the three with direct `with-eval-after-load`.

**Comment by minad** [comment]
@nicolas-graves It seems that the problem is that your package is too fine grained? If you fix that `with-eval-after-load 'embark` should be fine. Did I understand that correctly?

**Comment by nicolas-graves** [comment]
@minad I think I can just delete ibrowse-embark and put the three parts in the three files aforementionned.

**Comment by nicolas-graves** [comment]
Done, WDYT @riscy  ?

**Comment by minad** [comment]
@nicolas-graves I saw that you used categories like `browser-tab` etc. My recommendation would be to use categories belonging to the namespace `ibrowse-`, e.g., `ibrowse-tab`. This is also the convention which I follow in Consult (`consult-location` category). The Marginalia package is an exception since it adds unnamespaced categories to existing Emacs commands.

**Comment by nicolas-graves** [comment]
@riscy I'm also done with this refactor and renames, ready for a review, hopefully the last ;)

**Comment by riscy** [comment]
Thanks - I think that solution looks good.   A few extra warnings popped up, but this should be a quick merge afterwards:

`ibrowse-bookmark.el` with byte-compile using Emacs 28.1:
```
ibrowse-bookmark.el:181:8: Warning: docstring wider than 80 characters
```

`ibrowse-history.el` with byte-compile using Emacs 28.1:
```
ibrowse-history.el:123:8: Warning: docstring wider than 80 characters
In end of data:
ibrowse-history.el:135:4: Warning: the function `ibrowse-core-act-by-name' is
    not known to be defined.
```


`ibrowse-tab.el` with byte-compile using Emacs 28.1:
```
ibrowse-tab.el:57:8: Warning: docstring wider than 80 characters
```

**Comment by nicolas-graves** [comment]
@riscy These errors are now fixed, sorry for the back and forth :)

**Comment by riscy** [comment]
Looks good, thanks!  Welcome to MELPA. :)

**Pull request merged**
