### PR TITLE
Add aio-request package

### PR DESCRIPTION
**Pull request by truls**
### Brief summary of what the package does

This package adds a wrapper around the request.el package allowing it to be used with the emacs-aio package which provides async/awail style handling of asynchronous events for Emacs lisp. 

### Direct link to the package repository

https://github.com/truls/aio-request

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
A quick pass over the checklist:

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191027.20):
```
1 issue found:

1:0: warning: The package summary should start with an uppercase letter or a digit.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

Added miscellaneous hints (automated):
- aio-request.el#L10: Use `Version` instead of `Package-Version` (MELPA automatically adds `Package-Version`)

**Comment by truls** [comment]
Thanks for the feedback. The issues are fixed.

**Comment by riscy** [comment]
This looks like a very good idea -- since it is just a single function, have you thought about opening a pull request to the `request` package?

**Comment by riscy** [comment]
Ping!

I feel like it's okay if you _haven't_, but the benefit is that your functionality starts being maintained along with the core requests package.

**Comment by tarsius** [comment]
Closing due to inactivity.
Let us know when you are ready so that we can reopen and finish the review.

**Pull request closed without merging**
