### PR TITLE
Remove :files in evil-goggles recipe

### PR DESCRIPTION
**Pull request by edkolev**
### Brief summary of what the package does

Adds global minor mode evil-goggles-mode, which, when on, briefly shows a colored overlay to indicate what text will be affected. For example, 2 dd will briefly show an overlay on the 2 lines which will be deleted before deleting them.

### Direct link to the package repository

https://github.com/edkolev/evil-goggles

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by edkolev** [comment]
I'll be splitting the single .el file into two files. This PR removes `:files` so melpa can pick up all `*.el` files.

Thanks

**Comment by purcell** [comment]
Sure, that's a good idea anyway, but I'd suggest that it's not idiomatic to split a short (300-line) elisp package into multiple files.

**Comment by edkolev** [comment]
I see.. I was planning to add a `...-faces.el` file where only `defface`s would be added. I'll reconsider and probably leave everything in the same file for now.

Thanks

**Comment by purcell** [comment]
> I see.. I was planning to add a ...-faces.el file where only deffaces would be added. I'll reconsider and probably leave everything in the same file for now.

:+1:

Related tip, then: when defining new faces, try not to choose your own colours. Instead, use `:inherit` in the face definition to create your new faces as aliases for built-in faces. This way, themes will automatically look good, but users can still override the faces if desired.

**Pull request merged**
