### PR TITLE
Add recipe for password-menu.

### PR DESCRIPTION
**Pull request by rnadler**
### Brief summary of what the package does

password-menu is a UI wrapper for the built-in Emacs `auth-source' library.

### Direct link to the package repository

https://github.com/rnadler/password-menu

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a The MIT License (MIT).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Looks good, and thank you for your close adherence to the checklist!  I'm surprised a 'porcelain' for auth-source didn't exist yet (I searched around).

**Comment by riscy** [comment]
Actually, before I hit merge, I recommend expanding your summary line to make mention of auth-source to make this more discoverable.  Currently you have:
```elisp
;;; password-menu.el --- Password Menu  -*- lexical-binding: t; -*-
```
but I'd recommend something like
```
;;; password-menu.el --- Password menu for auth-source secrets  -*- lexical-binding: t; -*-
```
...or something similar, just so when people search "auth-source" they find this.

**Comment by rnadler** [comment]
Thanks for the suggestion! Done.

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
