### PR TITLE
Add rust-playground recipe

### PR DESCRIPTION
**Pull request by grafov**
### Brief summary of what the package does

GNU/Emacs mode that setup local playground for code snippets in Rust
language similar to play.rust-lang.org.

### Direct link to the package repository

https://github.com/grafov/rust-playground

### Your association with the package

I am author of the package.

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Could you put `Version:` header ?

**Comment by grafov** [comment]
I thought this header should be added by MELPA build scripts. My another plugin `go-playground` (already passed to MELPA) has not this header too. Sure I will add the header to both packages.

**Comment by syohex** [comment]
BTW `package-lint` says.

```
1:1: error: package.el cannot parse this buffer: Package lacks a "Version" or "Package-Version" header
1:1: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
```

**Comment by grafov** [comment]
Yes it reported this ...but I ignored the warning because of my previous package has same notice but  was passed to MELPA successfully :)

**Comment by grafov** [comment]
@syohex I just added `Version` to the package header.

**Comment by syohex** [comment]
Thanks

**Comment by purcell** [comment]
Some belated feedback:
- You should probably add a `defgroup rust-playground` in which to place your custom items -- that group can, of course, live inside the `rust-mode` group.
- You're making command lines by concatenating file and directory paths which might contain spaces or other special characters. Use `shell-quote-argument` to avoid this.

**Comment by grafov** [comment]
Thank for your feedback.

I already done the subgroup in previous commits (see line 50) as:

```elisp
 (defgroup rust-playground nil
  "Options specific to Rust Playground."
  :group 'rust-mode)
```

Shell arg for compiler call string fixed just now.

**Comment by purcell** [comment]
Awesome.

**Pull request merged**
