### PR TITLE
Add recipe for buckwalter-arabic.el

### PR DESCRIPTION
**Pull request by joehakimrahme**
### Brief summary of what the package does

Translates latin characters to arabic characters using the Buckwalter transliteration table.

### Direct link to the package repository

https://github.com/joehakimrahme/buckwalter-arabic

### Your association with the package

I'm the author and maintainer of the package

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x ] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x] My elisp byte-compiles cleanly
- [ x] `M-x checkdoc` is happy with my docstrings
- [ x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by joehakimrahme** [comment]
oops, sorry for closing this by mistake :(

**Comment by purcell** [comment]
Thanks! Quick feedback:

- All symbols must be prefixed with the package name prefix - why didn't `package-lint` point that out for you? (You might then prefer to call the package `buckwalter`, with a uniform `buckwalter-` prefix for its top-level symbols.)
- Please follow lisp naming conventions, e.g. `workOnStringP` -> `work-on-string-p`, no `$` etc.
- I think you should consider also providing a pair of `quail` input methods.

**Comment by joehakimrahme** [comment]
Thanks for the feedback, first time writing a package it's very helpful.

I renamed the package and changed symbol names to fit package-lint, and renamed a few offending variables (Is there a doc detailing the common lisp conventions?).

I didn't know about `quail`; it looks interesting and I might provide methods later on, thanks.

**Comment by purcell** [comment]
> Thanks for the feedback, first time writing a package it's very helpful.
> 
> I renamed the package and changed symbol names to fit package-lint, and renamed a few offending variables

Looks great - merging now. Sorry for the slow turnaround: December has been mad.


> (Is there a doc detailing the common lisp conventions?).

The Elisp coding conventions info is probably a good place to start: https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html


> I didn't know about quail; it looks interesting and I might provide methods later on, thanks.

👍

**Comment by joehakimrahme** [comment]
Thanks for merging.

So just to be clear, any commit I push to my repo now, will be made available on melpa, or is there something in particular I should be doing to push latest versions?

**Comment by purcell** [comment]
> So just to be clear, any commit I push to my repo now, will be made available on melpa

Yep, generally with a few hours delay.

**Comment by yassinphilip** [comment]
> any commit I push to my repo now, will be made available

Yes, that is correct, @joehakimrahme ; And any [version-tagged](https://git-scm.com/book/en/v2/Git-Basics-Tagging) commit will be available on MELPA stable.

**Comment by tarsius** [comment]
@joehakimrahme Unfortunately we can no longer distribute packages that are not released under a license that is not compatible with the license used by Emacs itself (GPL v3), not even if it is an older GPL version.

Please consider updating to v3 or to "either version 3, or (at your option) any later version". Please also make sure that the permission statement matches the expected format, i.e.:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with Magit.  If not, see http://www.gnu.org/licenses.
```

Thanks!

**Comment by joehakimrahme** [comment]
@tarsius okay I'll update the license soon.

Was this discussed somewhere in public? Can I check the rationale behind it?

**Comment by tarsius** [comment]
Yes, but the last few times I tried to find the best summary by @purcell I could not find it anymore. Maybe he can.

In short, elisp packages can (except in some rare cases where it would be possible to run the elisp as common lisp with minor modifications) be considered to derive from Emacs, and we agree with or are not motivated to challenge that interpretation.

**Comment by purcell** [comment]
@tarsius You might have been referring to [this discussion](https://github.com/purcell/package-lint/issues/83)?

**Pull request merged**
