### PR TITLE
Add xref-rst package

### PR DESCRIPTION
**Pull request by ideasman42**
### Brief summary of what the package does

This package supports looking up references in reStructuredText multi-file projects (`ref`, `term`, `doc` & file references).

This is useful for quickly navigating between sections in large, cross referenced manuals for example

### Direct link to the package repository

https://gitlab.com/ideasman42/emacs-xref-rst

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
IIUC the `xref` system in Emacs is extensible.  Have you considered writing this functionality on top of it?

**Comment by ideasman42** [comment]
> IIUC the `xref` system in Emacs is extensible. Have you considered writing this functionality on top of it?

No, I wasn't aware this could be made a back-end to xref, if this is the case, I'd need to look into support this since I don't know anything about xref internals beyond whats needed for this package.

**Comment by ideasman42** [comment]
Update, converted this package to use `xref`.

**Comment by ideasman42** [comment]
Added support for glossary look-ups (`term`)

**Comment by riscy** [comment]
Quick first pass --

### xref-rst.el ###

byte-compile (using Emacs 27.1):
```
xref-rst.el:93:1:Warning: Unused lexical variable `end'
xref-rst.el:93:1:Warning: Unused lexical variable `beg'
In xref-rst--range-of-block-at-current-indent:
xref-rst.el:116:9:Warning: assignment to free variable `beg'
xref-rst.el:116:13:Warning: assignment to free variable `end'
xref-rst.el:116:13:Warning: reference to free variable `beg'
xref-rst.el:116:13:Warning: reference to free variable `end'
xref-rst.el:367:1:Warning: Unused lexical variable `current-filepath'
xref-rst.el:429:1:Warning: Unused lexical variable `current-dir'
xref-rst.el:429:1:Warning: Unused lexical variable `current-filepath'
xref-rst.el:505:1:Warning: Unused lexical variable `current-dir'
xref-rst.el:505:1:Warning: Unused lexical variable `current-filepath'
In end of data:
xref-rst.el:685:1:Warning: the function `thing-at-point-looking-at' is not
    known to be defined.
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- xref-rst.el#L660: It's safer to sharp-quote function names; use `#'`

**Comment by ideasman42** [comment]
Apologies for the warnings, I further developed this after running `byte-compile`, all issues should now be resolved, including the sharp-quote.

**Comment by riscy** [comment]
No problem. :)  Emacs is maybe pathalogically difficult to get a clean byte-compile for on the first shot due to the compiler sharing state with the author's editing environment.  I think there are a couple more warnings on the latest:

byte-compile (using Emacs 27.1):
```
xref-rst.el:368:1:Warning: Unused lexical variable `current-filepath'
xref-rst.el:430:1:Warning: Unused lexical variable `current-dir'
xref-rst.el:430:1:Warning: Unused lexical variable `current-filepath'
xref-rst.el:506:1:Warning: Unused lexical variable `current-dir'
xref-rst.el:506:1:Warning: Unused lexical variable `current-filepath'
```

**Comment by ideasman42** [comment]
Strange, I'm not getting these warnings with emacs from master 28.0.50.

Even so, corrected the unused variables.

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
