### PR TITLE
Add dream-theme

### PR DESCRIPTION
**Pull request by djcb**
### Brief summary of what the package does

`dream-theme` is  a maximalist dark color theme inspired by Nordic/Zenburn etc.

### Direct link to the package repository

https://github.com/djcb/dream-theme

### Your association with the package

Author & maintainer

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thank you for this -- here's a quick first pass over the checklist:

### dream-theme.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
dream-theme.el:14: Name emacs should appear capitalized as Emacs
```
This is actually pointing to a mixup in the `;;; Commentary` section which is inadvertently including your package boilerplate and license.  You can verify this by running <kbd>M-: (lm-commentary)</kbd> in the buffer.  You just need to move the Commentary below the license boilerplate and above your `;;; Code` section.  While I'm here I also notice this line: `;; Keyworeds: faces. theme` contains a typo and should be comma-separated.

package-lint (using version 20210320.438):
```
1 issue found:
1:0: error: There is no (provide 'dream-theme) form.
```
This is a modest false-positive from package-lint, since provide-theme already does this; however, I recommend solving this by adding `(provide 'dream-theme)` at the bottom of the file so that you can have a 100% green package-lint.

In addition:
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by djcb** [comment]
Thanks for the quick review! I've made the requested changes.

**Comment by riscy** [comment]
Thanks.   package-lint appears to be throwing a false positive on the `deftheme` name.  I'll include it here so that I can link this PR in the issue that I'll raise with package-lint momentarily, but you don't need to act on this:

package-lint (using version 20210320.438):
```
1 issue found:
32:0: error: "dream" doesn't start with package's prefix "dream-theme".
```

I think this looks good to go.  And, welcome to MELPA. :)

**Comment by riscy** [comment]
Oh, I forgot to check that you made the `Keywords` fix before merging.  Please change this:
```
;; Keyworeds: faces.  theme
```
to this:
```
;; Keywords: faces, theme
```
when you get a chance.

**Comment by djcb** [comment]
Oh, that's silly, thanks for noticing -- fixed.

**Pull request merged**
