### PR TITLE
Add recipe for anything-tramp

### PR DESCRIPTION
**Pull request by masasam**
### Brief summary of what the package does

Tramp with anything interface

### Direct link to the package repository

https://github.com/masasam/emacs-anything-tramp

### Your association with the package

I'm the author of the package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
> Direct link to the package repository
>
> https://github.com/your/awesome_package

Please write your repository URL.

**Comment by masasam** [comment]
I fix it.
I am sorry for miss

**Comment by syohex** [comment]
And this package and `helm-tramp` should check whether `~/.ssh/config` exists(and show message if it does not exists). There is error if it does not exists in current implementation.

**Comment by masasam** [comment]
I fix it.
Added processing when there is no. ssh/config for both helm-tramp ans anything-tramp package.

**Comment by syohex** [comment]
Merged

**Pull request merged**
