### PR TITLE
Update catppuccin-theme

### PR DESCRIPTION
**Pull request by NamesCode**
Had to specify multiple packages

### Brief summary of what the package does

Emacs Theme

### Direct link to the package repository

https://github.com/catppuccin/emacs

### Your association with the package

a maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
**About package-lint
When I run on other confirmed files it gives the same errors so I think there's an issue on my side. If someone could take a look at this just to check then that would be appreciated.
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.   Quick first pass --

`catppuccin-frappe-theme.el` with byte-compile using Emacs 28.1:
```
catppuccin-frappe-theme.el:9:1: Error: Cannot open load file: No such file or directory, autothemer
```
I'm not sure what changes have taken place since the initial merge, but this repo needs a "main" file with the same name as the recipe, e.g. a catppuccin-theme.el file.  And that file would have a `Package-Requires:` line that would specify a dependency on `autothemer`.

`catppuccin-frappe-theme.el` with checkdoc 0.6.2:
```
catppuccin-frappe-theme.el:0: The first line should be of the form: ";;; package --- Summary"
catppuccin-frappe-theme.el:0: You should have a section marked ";;; Commentary:"
```

`catppuccin-frappe-theme.el` with package-lint 20221003.1636:
```
9 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a ;;; Commentary section.
1:0: error: Package should have a Homepage or URL header.
1:0: error: package.el cannot parse this buffer: Package lacks a file header
7:12: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-lib'.
170:3: error: You should depend on (emacs "24.1") if you need `org-block'.
174:3: error: You should depend on (emacs "24.1") if you need `org-todo'.
180:3: error: You should depend on (emacs "24.1") if you need `org-date'.
509:1: warning: Closing parens should not be wrapped onto new lines.
```

`catppuccin-latte-theme.el` with byte-compile using Emacs 28.1:
```
catppuccin-latte-theme.el:8:1: Error: Cannot open load file: No such file or directory, autothemer
```

`catppuccin-latte-theme.el` with checkdoc 0.6.2:
```
catppuccin-latte-theme.el:0: The first line should be of the form: ";;; package --- Summary"
catppuccin-latte-theme.el:0: You should have a section marked ";;; Commentary:"
```

`catppuccin-latte-theme.el` with package-lint 20221003.1636:
```
9 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a ;;; Commentary section.
1:0: error: Package should have a Homepage or URL header.
1:0: error: package.el cannot parse this buffer: Package lacks a file header
6:12: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-lib'.
169:3: error: You should depend on (emacs "24.1") if you need `org-block'.
173:3: error: You should depend on (emacs "24.1") if you need `org-todo'.
179:3: error: You should depend on (emacs "24.1") if you need `org-date'.
505:2: warning: Closing parens should not be wrapped onto new lines.
```

`catppuccin-mocha-theme.el` with byte-compile using Emacs 28.1:
```
catppuccin-mocha-theme.el:7:1: Error: Cannot open load file: No such file or directory, autothemer
```

`catppuccin-mocha-theme.el` with checkdoc 0.6.2:
```
catppuccin-mocha-theme.el:0: The first line should be of the form: ";;; package --- Summary"
catppuccin-mocha-theme.el:0: You should have a section marked ";;; Commentary:"
```

`catppuccin-mocha-theme.el` with package-lint 20221003.1636:
```
9 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a ;;; Commentary section.
1:0: error: Package should have a Homepage or URL header.
1:0: error: package.el cannot parse this buffer: Package lacks a file header
5:12: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-lib'.
168:3: error: You should depend on (emacs "24.1") if you need `org-block'.
172:3: error: You should depend on (emacs "24.1") if you need `org-todo'.
178:3: error: You should depend on (emacs "24.1") if you need `org-date'.
507:1: warning: Closing parens should not be wrapped onto new lines.
```

`#'load`-check on each file:
```
Loading catppuccin-frappe-theme.el
  catppuccin-frappe-theme.el:Error: Emacs 28.1:
  (file-missing "Cannot open load file" "No such file or directory" "autothemer")
Loading catppuccin-latte-theme.el
  catppuccin-latte-theme.el:Error: Emacs 28.1:
  (file-missing "Cannot open load file" "No such file or directory" "autothemer")
Loading catppuccin-mocha-theme.el
  catppuccin-mocha-theme.el:Error: Emacs 28.1:
  (file-missing "Cannot open load file" "No such file or directory" "autothemer")
```

Package and license:
- No .el file matches the name 'catppuccin-theme'
- Prefer the default recipe or `:defaults`, if possible.
- Can't check package-requires if there is no 'main' file
- MIT License (via API)
- unknown license -- catppuccin-frappe-theme.el: (no header)
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to catppuccin-frappe-theme.el
- unknown license -- catppuccin-latte-theme.el: (no header)
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to catppuccin-latte-theme.el
- unknown license -- catppuccin-mocha-theme.el: (no header)
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to catppuccin-mocha-theme.el

**Comment by NamesCode** [comment]
Thanks for running it through, I will fix this as soon as possible

**Comment by NamesCode** [comment]
I have updated the files. Could you take a look over them to see if I've done this correctly or if I've missed something

**Comment by riscy** [comment]
There is a [WIP faq](https://github.com/melpa/melpa/blob/4caa9a03cad40d24484fce27fcfcf75b1d08e814/FAQ.md) around themes that should help, but this package needs a "main" file.  You could follow the convention in the README, or perhaps rename this package to "catppuccin" to make package-lint happy.

It's also a good idea to prefer the default recipe or `:defaults`, if possible, but we can address this issue after the naming.

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out!

**Comment by tarsius** [comment]
There is a newline character in one of the filenames. Please also fix other formatting issues--intend it as you would indent lisp code.

Please also rename the package to `catppuccin-themes.el`, and make sure it contains the appropriate package metadata and that it is included in the Melpa package.

Every package should provide a library whose name matches that of the
package.  This allows tools, such as those used by Melpa, to extract
metadata.

At the same time every library named "...-theme.el" must itself
implement a theme because `load-theme` unfortunately assumes that
every file on `custom-theme-load-path` with such a name actually
provides a theme.  If it encounters files that to not provide a theme
but are never-the-less named "...-theme.el", then it falsely offers
those as themes, and trying to activate them will result in errors.

Furthermore, since this package provides multiple themes, it makes
sense to give it a name that suggests so.

Unfortunately package.el does not (yet?) support informing the user
about package renames or even automatically updating to the new name,
so some users will not notice this rename for a while.  Add a note
at the beginning of the readme, in the hope that will help at least
some users.

Re https://github.com/melpa/melpa/issues/8219.

**Comment by NamesCode** [comment]
There have been some changes in the main repo so I've redone the checklist. I think this should be Melpa compliant. I've also changed the recipe.

### Checklist



- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

**Comment by NamesCode** [comment]
Unnecessary now

**Pull request closed without merging**
