### PR TITLE
Add taskrunner recipe

### PR DESCRIPTION
**Pull request by sehnsucht13**
### Brief summary of what the package does
Taskrunner is a library which is used to retrieve targets/tasks from taskrunners/build systems used in development. It provides support for asynchronously/synchronously retrieving these from the currently visited project and providing them to the calling function(intended to be a frontend such as helm/ivy/ido. Package recipes will be submitted for those soon). It provides support for taskrunners/build systems such as Gulp, Grunt, Make, CMake, Cabal and so on. It aims to be highly modular so it can be used by other package creators to retrieve useful info from these build/taskrunner systems.

Edit: Just as a heads up to whoever reviews this, this package currently uses `emacs-async` to implement its async functionality. This is somewhat temporary. It will be left to support emacs 25 but for emacs 26 and above, I plan on using the provided threads, running the functions to collect the tasks and then polling them for when the result is finished.
Edit 2: The thread idea has been scrapped :(. The UI still freezes when running functions which run processes which take a long time.

### Direct link to the package repository
https://github.com/emacs-taskrunner/emacs-taskrunner

### Your association with the package
I am the creator/maintainer
### Relevant communications with the upstream package maintainer
None needed.
### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

Thanks a lot in advance to anybody who is reviewing this as well as those who help maintain MELPA!

### CODE REVIEW

**Comment by riscy** [comment]
A couple byte-compile nags as I'm passing through quickly:

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
taskrunner-leiningen.el:48:1:Warning: the function `map' is not known to be
    defined.

ivy-taskrunner.el:307:1:Warning: the following functions are not known to be
    defined: counsel-projectile-switch-project, map
```
Mostly resolved by preferring `cl-map` (and adding a require on `cl-lib`).

**Comment by sehnsucht13** [comment]
Thank you. I don't know how i did not catch that. Apologies! I will fix them immediately

**Comment by sehnsucht13** [comment]
Changes have been made to both `helm-taskrunner` and `ivy-taskrunner` in order to silence the warnings. The offending code will never be reached unless `helm/ivy-projectile` packages are installed but the bytecompiler complains about them anyways. Those have been silenced by checking if the symbol is bound.

Apologies for not detecting these, I did not think about testing this without the `helm/ivy-projectile` packages installed.

**Comment by alphapapa** [comment]
> Edit: Just as a heads up to whoever reviews this, this package currently uses `emacs-async` to implement its async functionality. This is somewhat temporary. It will be left to support emacs 25 but for emacs 26 and above, I plan on using the provided threads, running the functions to collect the tasks and then polling them for when the result is finished.

I'm not an expert on Emacs new thread support, but FYI, they're not generally useful at this time.  This is mainly because only one Elisp thread can run at a time, so it's like cooperative multitasking.  In contrast, `emacs-async` actually runs a separate process, so it actually runs simultaneously with the parent process's Elisp.  I'd recommend waiting until the implementation becomes more mature and useful.  On the other hand, maybe you can show us the way.  :)

**Comment by sehnsucht13** [comment]
Yea, I unfortunately just found that out today while trying to implement threading. Time was wasted but a lesson was learned. Either way, thanks a lot for the heads up! That idea is scrapped for now since the UI thread still blocks but I will keep an eye on it.

**Comment by alphapapa** [comment]
Ah, too bad, I was hoping to save you that trouble.  :)

**Comment by sehnsucht13** [comment]
No worries at all. I still appreciate the heads up!

**Comment by riscy** [comment]
Taking another pass at this -- apologies for the turnaround time.  There may have been some changes to the code since I last attempted to compile:

In taskrunner-web.el:
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
taskrunner-web.el:139:1:Warning: the following functions are not known to be
    defined: taskrunner--make-task-buff-name, taskrunner--narrow-to-line
```

In taskrunner-ruby.el:
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
taskrunner-ruby.el:38:1:Warning: the following functions are not known to be
    defined: taskrunner--narrow-to-line, taskrunner--make-task-buff-name
```

In taskrunner-mix.el:
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
taskrunner-mix.el:64:1:Warning: the function `taskrunner--make-task-buff-name'
    is not known to be defined.
```

In taskrunner-leinengen.el:
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
taskrunner-leiningen.el:51:1:Warning: the function
    `taskrunner--make-task-buff-name' is not known to be defined.
```

In taskrunner-java.el:
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
taskrunner-java.el:155:1:Warning: the function
    `taskrunner--make-task-buff-name' is not known to be defined.
```

In taskrunner-general.el:
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
taskrunner-general.el:301:26:Warning: reference to free variable
    `taskrunner-dobi-bin-path2'

In end of data:
taskrunner-general.el:309:1:Warning: the following functions are not known to
    be defined: taskrunner--narrow-to-line, taskrunner--make-task-buff-name
```

In taskrunner-clang.el:
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
taskrunner-clang.el:159:1:Warning: the following functions are not known to be
    defined: taskrunner--narrow-to-line, taskrunner-add-to-build-cache,
    taskrunner--make-task-buff-name
```

I think a lot of the above could be sorted out by adding the right `require`'s.

In taskrunner.el:
Added miscellaneous hints (automated):
- taskrunner.el#L779: It's safer to sharp-quote function names; use `#'`
- taskrunner.el#L855: Consider `unless ...` instead of `when (not ...)`
- taskrunner.el#L78: Prefer `https` over `http` (if possible)

**Comment by sehnsucht13** [comment]
aah yes there definetely have been quite a few changes. I apologize, it was a bit of time since I submitted and I completely forgot about this while merging devel and master branches together. I will take a look at it and fix it ASAP. Sorry again about this.

**Comment by sehnsucht13** [comment]
Hello again! Apologies for taking so long but the recommended fixes have been implemented. The bytecompile is clean and without any errors.

**Comment by riscy** [comment]
Great.  This looks like an excellent package.  Thanks!  And, welcome to MELPA!

**Pull request merged**
