### PR TITLE
Add info file to ledger-mode recipe

### PR DESCRIPTION
**Pull request by JalapenoGremlin**
### Brief summary of what the package does

This is just a modification to an existing recipe for ledger-mode. This change only adds the "doc/*.texi" files to the recipe so that the ledger-mode.info file can be generated, as well.

### Direct link to the package repository

https://github.com/ledger/ledger-mode

### Your association with the package

I'm just a user, who likes documentation with the code.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
I think the solution here is to simply remove `:files` altogether, which will result in all those files being includes. Would you mind testing that and amending the recipe accordingly please?

**Comment by JalapenoGremlin** [comment]
Yep. That does exactly the correct thing.  So.... (my github fu may be off).

**Comment by purcell** [comment]
Super, thanks!

**Comment by jaccarmac** [comment]
@JalapenoGremlin This recipe change is causing problems for those trying to install `ledger-mode`, as the mode depends on loading a `ledger-test.el` which is excluded by the default recipe setting from MELPA. I'm in the middle of provisioning a new dev machine so can't add to the PR myself just yet, but this patch should be pretty close:

```
modified   recipes/ledger-mode
@@ -1 +1,7 @@
-(ledger-mode :fetcher github :repo "ledger/ledger-mode" :old-names (ldg-mode))
+(ledger-mode :fetcher github
+             :repo "ledger/ledger-mode"
+             :files ("*.el" "*.el.in" "dir" "*.info" "*.texi" "*.texinfo"
+                     "doc/dir" "doc/*.info" "doc/*.texi" "doc/*.texinfo"
+                     (:exclude ".dir-locals.el" "test.el" "tests.el"
+                               "*-tests.el"))
+             :old-names (ldg-mode))
```

Thanks!

**Comment by purcell** [comment]
Thanks, good catch. Just `:files (:defaults "ledger-test.el")` is sufficient here, and I've applied that in 1549048b.

**Comment by JalapenoGremlin** [comment]
Wow. Sorry about that, @jaccarmac. I didn't have a problem loading the package locally. Good catch. 
I'll review the CONTRIB more closely next time so that I don't break things in the future -- Perhaps I missed something that could have caught this before submitting the pull request.

**Comment by jaccarmac** [comment]
Sweet, didn't realize that was a feature @purcell. Thanks for the trick!

No worries @JalapenoGremlin, I've dealt with weird packaging issues before when my environment wasn't perfectly clean. I'm just happy you left a paper trail to follow so I could hunt down the issue easily :smile:!

**Pull request merged**
