### PR TITLE
Create herald-the-mode-line

### PR DESCRIPTION
**Pull request by marcowahl**
### Brief summary of what the package does

Herald the mode-line as message.

### Direct link to the package repository

https://github.com/marcowahl/herald-the-mode-line

### Your association with the package

maintainer - contributor - enthusiastic user

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick notes:
- `s/occurances/occurrences/`
- There's no need to escape `%`, because you can just say `(message "%s" (format-mode-line (or mode-line-format hide-mode-line)))`.

In fact, that then becomes the code for almost the entire library, in which case I really don't think this is worth adding as a package. :-)

**Comment by marcowahl** [comment]
Thanks.  TIL "occurrence".

I think I'll apply your suggestion.  Thanks.

And agreed.  This little thing might not be worthy enough to be a package.

You shall decide, please.

**Comment by purcell** [comment]
Yep, let's not add this. Thanks for taking the time to submit it though!

**Comment by marcowahl** [comment]
Ok.

Thanks for the effort you invested in herald-the-mode-line.

**Pull request closed without merging**
