### PR TITLE
add consult-gh-forge recipe

### PR DESCRIPTION
**Pull request by armindarvish**
-------

### Brief summary of what the package does

Adds magit/forge integration for consult-gh (see #9118)

### Direct link to the package repository

https://github.com/armindarvish/consult-gh

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

`consult-gh-forge.el` with byte-compile using Emacs 29.4:
```
consult-gh-forge.el:274:95: Warning: Unused lexical argument `forge'
consult-gh-forge.el:299:86: Warning: Unused lexical argument `forge'
```

`consult-gh-forge.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- consult-gh-forge.el#L343: Lighter should start with a space
```

Stderr output while compiling/loading:
```
consult-gh-forge.el: Warning: reference to free variable `consult-gh-forge-mode'
```

**Comment by armindarvish** [comment]
@riscy Thanks for the comments.

> consult-gh-forge.el:274:95: Warning: Unused lexical argument `forge'
consult-gh-forge.el:299:86: Warning: Unused lexical argument `forge'

I added a `(ignore forge)` to those functions, but I am not sure if there is a better way to handle this. From what I understand, a `cl-defmethod` should have the same arguments as the cl-`defgeneric` form, and therefore, I kept the same form even though I don't really need the `forge` input variable in this case. Admittedly, I don't fully understand how the geenric fuinctions work, so I wonder if @tarsius has some comments/suggestions that can improve the code here.

> - consult-gh-forge.el#L343: Lighter should start with a space
fixed it.

> consult-gh-forge.el: Warning: reference to free variable `consult-gh-forge-mode'
I moved the `define-minor-mode` up, so I think this should be fixed now.

**Comment by tarsius** [comment]
Name the argument `_forge` instead of `forge`. That communicates to both the human reader and the compiler, that the argument is unused.

**Comment by armindarvish** [comment]
@tarsius Thanks for the help. I fixed that now!

**Comment by riscy** [comment]
Thank you!

**Pull request merged**
