### PR TITLE
Add recipe for build-helper

### PR DESCRIPTION
**Pull request by afonso360**
### Brief summary of what the package does

```build-helper``` allows control over multiple build systems with one single interface.

Users can simply execute commands on a compile buffer and have their command history
recorded per project. Users can also link build-helper with other build systems and execute
elisp functions provided by other projects.

### Direct link to the package repository

https://github.com/afonso360/build-helper/

### Your association with the package

I'm the creator and maintainer.

### Relevant communications with the upstream package maintainer

**None**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Should `build-helper-setup` be autoload function ?

**Comment by afonso360** [comment]
Yes, it probably should be.

Fixed in the latest commit

**Comment by syohex** [comment]
Looks good.

**Comment by purcell** [comment]
Thanks. Quick feedback:
- `:group 'build-helper` means your `defgroup` is its own parent, which I don't think is what you want. ;-)
- Use `:group` in your `defcustom` forms
- `build-helper--functions` should be what users customize, IMO: they can then modify it using the custom interface, or via directory-local variables (which trivially give you per-major-mode configs). `build-helper-add-function` doesn't really add anything other than the requirement that users write elisp to customize the package, and your hand-rolled approach isn't idiomatic.

**Comment by afonso360** [comment]
Based on your feedback:

Variables are now in their appropriate groups and the package is now grouped under programming tools.

Moved `build-helper--functions` and `build-helper--comint` to be public and gave them an appropriate customize interface.

I haven't removed `build-helper-add-function` because I still think its useful, but I agree that it shouldn't be the only way to add functions (this also applies to `comint` settings).

@purcell @syohex Thank you for taking the time to review my package.

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
