### PR TITLE
Add ivy-youtube recipe

### PR DESCRIPTION
**Pull request by squiter**
### Brief summary of what the package does

This package is a `ivy` version of `helm-youtube`. It uses `ivy` to list youtube videos and launch the browser to watch selected video.

### Direct link to the package repository

https://github.com/squiter/ivy-youtube

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Looks good

**Comment by tarsius** [comment]
@syohex Weren't you given commit access and the permission to merge if it "Looks good"? Just asking because I am currently going through the list of open pull requests, adding `awaiting upstream` and otherwise pinging Steven.

@purcell If done so by "asking for a review" from you (using the Reviewers pull-down on the right). Is it sufficiently clear what I mean when I do that? Maybe we could also add a `lgtm` tag -- kinda the opposite of `awaiting upstream`.

**Comment by purcell** [comment]
>  If done so by "asking for a review" from you

Works for me, but probably a "lgtm" tag would be less specific to me, and therefore better in the long run.

Regarding the package itself, here's my feedback:
- Don't depend on `swiper` -- depend on `ivy`, instead.

Looks good otherwise!

**Comment by squiter** [comment]
@purcell you are right! I fixed this dependency problem, thanks.

**Comment by syohex** [comment]
Merged

**Pull request merged**
