### PR TITLE
Add hal-mode

### PR DESCRIPTION
**Pull request by strahlex**
Emacs mode for [Machinekit](http://machinekit.io) [HAL files](http://www.machinekit.io/docs/hal/basic_hal/)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, but that isn't close to being a standard-formatted emacs package yet. Want to follow up upstream with a corresponding PR to fix it up?

**Comment by strahlex** [comment]
Yes would be great.

**Comment by purcell** [comment]
Okay, I'll leave this pull request open for now - let me know when the changes have been made.

**Comment by strahlex** [comment]
Updated the package

**Comment by purcell** [comment]
Pending https://github.com/strahlex/hal-mode/pull/1.

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
