### PR TITLE
Add scramble recipe

### PR DESCRIPTION
**Pull request by deadblackclover**
### Brief summary of what the package does

Generate random states for Rubik's cubes puzzles. The generated sequence helps mess up Rubik's cube for later reassembly.

### Direct link to the package repository

https://github.com/deadblackclover/scramble-el

### Your association with the package

Creator and maintaner

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Since this is a relatively niche feature of a rubik's cube, have you thought of PR'ing this feature to the existing [rubik package](https://melpa.org/#/rubik)?  That package has gone some years without an update, but it might benefit from incorporating an interesting feature like this.

In terms of code feedback, I just have the following --

- scramble.el#L76: Don't set global bindings; tell users how in your `;;; Commentary`.

**Comment by deadblackclover** [comment]
@riscy Thanks for the info! I have looked into this package, but unfortunately my package has a slightly different purpose.

Speedcubers often use sequences like this to confuse the cube before assembling it. This package is just for that, to quickly generate a sequence, disassemble the cube and reassemble it at speed.

I have also made corrections based on your comment.

**Comment by riscy** [comment]
> Speedcubers often use sequences like this to confuse the cube before assembling it. This package is just for that, to quickly generate a sequence, disassemble the cube and reassemble it at speed.

I understand, but my thought is that Rubik's cubes are sort of already niche subject matter.  Standing just on its own, scramble.el feels like a fairly simple random string generator and probably one of those niche functions that might not be fully ready to be a package on MELPA.  Although maybe a useful helper if you want to track your Rubik's moves.

I also read a bit on scrambles [here](https://ruwix.com/puzzle-scramble-generators/rubiks-cube-scrambler/) (I know nothing about this stuff) and I'm reading: "It is critical that all states that could be generated have an equal likelihood of being generated", and that scramblers "work by picking a random state out of all of the possible states that take at least 4 moves to solve ... and generating a [sequence of moves](https://ruwix.com/the-rubiks-cube/algorithm/) that achieves that state."  I think scramble.el does not fulfill the equal likelihood criterion.

**Comment by deadblackclover** [comment]
> I understand, but my thought is that Rubik's cubes are sort of already niche subject matter. Standing just on its own, scramble.el feels like a fairly simple random string generator and probably one of those niche functions that might not be fully ready to be a package on MELPA. Although maybe a useful helper if you want to track your Rubik's moves.

Okay, I understand. Maybe I will add my work to another package or continue to develop my own.

**Pull request closed without merging**
