### PR TITLE
Add emojify-logos recipe

### PR DESCRIPTION
**Pull request by mxgoldstein**
### Brief summary of what the package does

This package adds logo icons for various programming languages and tools to emojify.el

### Direct link to the package repository

https://github.com/mxgoldstein/emojify-logos

### Your association with the package

The maintainer

### Relevant communications with the upstream package maintainer

**None needed**
### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Much of the code here is about downloading the logos, but you should really just include them in the package and avoid all that hassle. We'll rebuild fresh packages when the logos change.

**Comment by mxgoldstein** [comment]
Should I just copy the files directly from the package every time it's run?

**Comment by purcell** [comment]
Yes: `:files (:defaults "logo")` will cause the package to contain the same directory structure as your repository, so you can just use `load-file-name` to find the `logo` directory in both cases.

**Comment by mxgoldstein** [comment]
Adapted it.

**Comment by purcell** [comment]
Thanks, merged now - sorry for the slow response: work has been busy!

**Pull request merged**
