### PR TITLE
Add pd-remote

### PR DESCRIPTION
**Pull request by agraef**
pd-remote utility for Emacs->Pd communication

### Brief summary of what the package does

Talks to the pd-remote.pd abstraction in order to send messages from Emacs to Pd, e.g., to compile stuff in Pd, enable/disable DSP mode in Pd, etc.

### Direct link to the package repository

https://github.com/agraef/pd-remote

### Your association with the package

Author and Maintainer, cf. https://agraef.github.io/

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by agraef** [comment]
Yes, package-lint will complain about some issues in pd-remote.el. But I'd argue that all but one of those complaints aren't relevant, because they're about stylistic and coding conventions, and as a seasoned elisp programmer I beg to differ.

The only real issue I see in package-lint's output is about the `C-g` in the `"\C-c\C-g"` keybinding. I agree that this is a poor choice and will change it in a future release.

So can this be merged then, please? I'd very much like to have this in MELPA so that my students have an easier way to install pd-remote on their laptops.

**Comment by agraef** [comment]
Maybe some remarks about the purpose of this package and why I'd like to have it added to MELPA are in order.

This isn't a mode, it's a little "remote control" utility for Pd, Miller Puckette's realtime multimedia and computer music environment. The current version is a simplified and unified version of what I've been distributing with various Pd externals for a long time now.

The package provides a way to send messages from Emacs to Pd. Specifically, it hooks into Emacs' Faust and Lua modes so that the user can edit Faust and Lua programs running as objects in Pd, and then tell these objects to recompile or reload themselves once the user is done editing the source code. Moreover, it allows pretty much any message to be sent from Emacs to Pd. Another useful example is `pd dsp` to quickly turn dsp processing in Pd on and off without having to switch from Emacs to Pd.

I'd say that it's innovative enough to warrant a spot in MELPA. There's nothing quite like it, for *any* editor.

I use this utility quite a lot in courses I teach at the university. As a die-hard Emacs fan for many many years, I'm fine with installing it manually myself. But I'd really like to see it in MELPA to make installation easier for my students, who often struggle with Emacs even without me telling them that they need to "put some bit of elisp into their .emacs.d and make sure that Emacs finds it." ;-)

**Comment by agraef** [comment]
Ok, I slashed all the package-lint complaints now in git, except for the faust-mode-map, that I won't change because I think that the name is correct (as I argued above).

So is this acceptable now? Any feedback appreciated.

**Comment by agraef** [comment]
I think that this should meet all your guidelines now, what else can I do to help with the review?

I realize that this is no run-of-the-mill Emacs package and that people around here might not be very familiar with computer music software which is what this is about. I'm also worried about the lack of feedback, because I see that there's a considerable backlog of open PRs over here, so whatever I can do to speed up the process I'm happy to do.

Sorry if this comes over as a bit impatient, that's because I am. :) (I have a presentation next week where I'd also like to show this particular package, and in any case I'd be happy if it was available to my students asap.)

**Comment by riscy** [comment]
Hi @agraef, I typically only review MELPA submissions on weekends.  Thanks for your patience. :)  Here's a quick first pass of the checklist --

`pd-remote.el` with byte-compile using Emacs 28.1:
```
pd-remote.el:109:1: Error: Cannot open load file: No such file or directory, lua-mode
```
An extra note here is that you should put your `require` lines at the top of the file.

`pd-remote.el` with package-lint 20221003.1636:
```
3 issues found:
8:22: warning: Use a properly versioned dependency on "faust-mode" if possible.
8:33: warning: Use a properly versioned dependency on "lua-mode" if possible.
98:0: error: "faust-mode-map" doesn't start with package's prefix "pd-remote".
```
You can get the stable version numbers from here: https://stable.melpa.org/#/lua-mode https://stable.melpa.org/#/faust-mode.

I want to provide some guidance here, assuming I'm understanding correctly: it looks like you're trying to extend faust-mode by using lines like this:
```elisp
;; NOTE: If you don't have this, or you don't need it, just comment the following two lines.
(setq auto-mode-alist (cons '("\\.dsp$" . faust-mode) auto-mode-alist))
(autoload 'faust-mode "faust-mode" "FAUST editing mode." t)
```
and 
```elisp
;; Juan's Faust mode doesn't have a local keymap, add one.
(defvar faust-mode-map nil)
...
```
It appears you're trying to define a mode that is derived from faust-mode (and lua-mode as well); you should consider just using `define-derived-mode` for this with its own keymap and the auto-mode-alist entry set accordingly.  I think that comment "just comment the following two lines" is outdated; faust-mode is an explicit dependency of your package per the Package-Requires line.

`pd-remote.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- pd-remote.el#L87: There is no need to quote lambdas (neither #' nor ')
- pd-remote.el#L89: There is no need to quote lambdas (neither #' nor ')
- pd-remote.el#L91: There is no need to quote lambdas (neither #' nor ')
- pd-remote.el#L103: There is no need to quote lambdas (neither #' nor ')
- pd-remote.el#L106: There is no need to quote lambdas (neither #' nor ')
- pd-remote.el#L118: There is no need to quote lambdas (neither #' nor ')
- pd-remote.el#L78: Prefer `add-to-list` to add to auto-mode-alist
- pd-remote.el#L111: Prefer `add-to-list` to add to auto-mode-alist
- pd-remote.el#L106: Loading a package should rarely add hooks
- pd-remote.el#L79: It may be simpler to just `require` this dependency
- pd-remote.el#L113: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- pd-remote.el#L114: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- pd-remote.el#L115: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- pd-remote.el#L118: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
```

`#'load`-check on each file:
```
Loading pd-remote.el
  pd-remote.el:Error: Emacs 28.1:
  (file-missing "Cannot open load file" "No such file or directory" "lua-mode")
```

Package and license:
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to pd-remote.el

**Comment by agraef** [comment]
@riscy Of course, I understand that you don't want to look at these all the time. ;-) Thanks for getting back to me and for the thorough review! I'll be away on a business trip starting tomorrow, but I hope that I can look into the issues you raised before next weekend.

**Comment by agraef** [comment]
> I think that comment "just comment the following two lines" is outdated

Yep, that comment is outdated and needs to be removed.

> It appears you're trying to define a mode that is derived from faust-mode

Not really. Rather I'm just adding some commands to both faust-mode and lua-mode in order to talk to corresponding Faust and Lua objects in Pd. lua-mode already has a keymap where I can bind these commands, but faust-mode hasn't, and thus I need to add one.

I don't really see pd-remote.el as a derived mode, not even as a minor mode, just some utility commands to be added to the two existing modes.

**Comment by agraef** [comment]
Also note that these pd-remote commands aren't useful for ordinary users of faust-mode and lua-mode. They will be used only by Pd users who need that functionality while editing Faust and Lua scripts in Emacs.

I don't think that derived modes are the right thing for this. Maybe I could turn pd-remote.el into a minor mode, but that seems overkill to me as well.

**Comment by agraef** [comment]
Hmm, looking at what the elisp reference manual has to say about minor modes, maybe that would be the proper solution after all. That way the special commands could be added to the minor mode keymap and not clobber any existing keymaps. Also, pd-remote wouldn't really have to depend on faust-mode and lua-mode any more.

I'd just need to figure out which major mode the buffer is actually in, since the "Compile" command needs to be different depending on whether the user is editing a Faust or a Lua script.

I think that I'll give that a go as soon as I find the time.

**Comment by agraef** [comment]
Ok, I reworked this now so that it uses a minor mode to extend the Faust and Lua keymaps instead of clobbering them. I still need to keep faust-mode and lua-mode as dependencies, though, so that I can add file extensions and hooks to enable the minor mode. This is about as clean as I can make it without compromising functionality.

> Add formal license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to pd-remote.el

I'm not sure what you mean. "MIT" (in the License line) *is* a proper SPDX-License-Identifier.

> #'load-check on each file

Sorry, but I don't understand this either. I don't have `load-check` in my Emacs, and for me, the package loads fine with `load`. So what am I supposed to do here?

**Comment by agraef** [comment]
About that `load` issue: This is likely caused by faust-mode (and lua-mode) not being installed or not being found on the (MELPA) load path. Since both packages are being loaded using `require` in the pd-remote package, they need to be present and on the load-path when loading them.

I had a similar issue with flycheck, which I cured by setting `flycheck-emacs-lisp-load-path` to `'inherit`.

**Comment by riscy** [comment]
Thank you for accommodating.  Please let me know if I missed any specific questions/points you have in what follows --

> I'm not sure what you mean. "MIT" (in the License line) is a proper SPDX-License-Identifier.

I see that now, so my explanation should have been better.  But unless you prefix it with "SPDX-License-Identifier:" rather than "License:" it isn't machine-detectable in the same way; the benefit of an explicit SPDX license line is that I can hit an API with the specific identifier to ensure we've got an appropriate license.  (`License: MIT` is unambiguous, but I sometimes see `License: GPL` which could be *anything*, so it's better to use the explicit SPDX identifiers in general.)

Here's the latest --

`pd-remote.el` with package-lint 20221003.1636:
```
1 issue found:
8:57: warning: Use a non-snapshot version number for dependency on "lua-mode" if possible.
```
See stable.melpa.org/#/lua-mode

`pd-remote.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- pd-remote.el#L123: Loading a package should rarely add hooks -- these should go in a user's config
- pd-remote.el#L124: Loading a package should rarely add hooks -- ditto
- pd-remote.el#L117: Terminate auto-mode-alist entries with `\\'`
- pd-remote.el#L120: Terminate auto-mode-alist entries with `\\'`
```

**Comment by agraef** [comment]
Ok, so your suggestion is to replace `;; License: MIT` with `;; SPDX-License-Identifier: MIT` in line 10, is that right? That's easy enough, will do.

> See stable.melpa.org/#/lua-mode

Well, I actually went to https://stable.melpa.org/#/lua-mode, as you advised, and "20210802" *is* the version it gives me there:

image

Do you see something else??

**Comment by agraef** [comment]
I think that 20210802 is the stable version number, in any case it's the latest tag in https://github.com/immerrr/lua-mode.

The other issues I've fixed now, except this one:

> Loading a package should rarely add hooks -- these should go in a user's config

While I see the rationale behind this policy, I'm unhappy with it in this case, since I'd really like to have the keybindings from the minor mode work out of the boy in faust-mode and lua-mode. This is the primary purpose of the pd-remote package after all.

@riscy How much of a strict requirement is this? If I have to remove the hooks from the package in order to get it accepted, then I'll do it. But then I'll have to instruct the user to do this him/herself, and explain what this does. But I'd like to keep things as simple as possible for the end user.

**Comment by agraef** [comment]
Oh well, I guess that users should be able to copy and paste 3 lines from the README to their .emacs, so I've removed the add-hook commands from the package now.

So all outstanding issues should be fixed now, I guess?

**Comment by riscy** [comment]
> Well, I actually went to https://stable.melpa.org/#/lua-mode, as you advised, and "20210802" is the version it gives me there

Apologies, I didn't realize their stable versioning pattern was triggering package-lint.

> But I'd like to keep things as simple as possible for the end user.

I was in your shoes with the first package I submitted to MELPA, so I understand.  And some packages have decided to make adding advice and hooks at load time the convention.  But imo you should not in this case.  Maybe the user only wants one of the hooks; maybe the user only wants the hook in certain situations; it's possible another package might come along that interferes, and then it becomes very difficult for a user to debug their config.  A lot of the rationale for this is similar to why [you don't want to do similar things in extremely large python projects](https://instagram-engineering.com/python-at-scale-strict-modules-c0bb9245c834) for example.

**Comment by agraef** [comment]
Thanks!

**Pull request merged**
