### PR TITLE
Add codcut-emacs recipe

### PR DESCRIPTION
**Pull request by dgopsq**
### Brief summary of what the package does

Using this package it will be possible to share a selected code to Codcut, a new mobile app (social network for developers) that will launch soon both on Android and iOS.

### Direct link to the package repository

https://github.com/codcut/codcut-emacs

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by mattiasb** [comment]
>     * [x]  The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).

There's no license file or header in the repository though!

**Comment by dgopsq** [comment]
I'm sorry, I thought it was an implicit thing, just added a `LICENSE` file.

**Comment by riscy** [comment]
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
3 issues found:

1:1: warning: Including "Emacs" in the package summary is usually redundant.
1:1: error: There is no (provide 'codcut-emacs) form.
6:1: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems)
(The following assumes lexical binding is enabled)
```
codcut-emacs.el:67:1:Warning: Unused lexical variable `headers'
codcut-emacs.el:67:1:Warning: Unused lexical variable `status'
```

Added miscellaneous hints (automated):
- codcut-emacs.el#L8: Use `Version` instead of `Package-Version` (MELPA automatically adds `Package-Version`)
- codcut-emacs.el#L105: No `format` required; messages are already f-strings

**Comment by riscy** [comment]
Re: the above, you should remove the `-emacs` from your package name - the `.el` suffices to mark this package as "for Emacs".

**Comment by dgopsq** [comment]
Thank you for the review, all the issues should be fixed!

**Comment by riscy** [comment]
One thing I wanted to ask about was this:

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems) (and depend on at least (emacs "24"))
(The following assumes lexical binding is enabled)
```
codcut.el:67:1:Warning: Unused lexical variable `headers'
codcut.el:67:1:Warning: Unused lexical variable `status'
```

What's the effect of running `setq` on `headers` and `status`?  I may be missing something since the `url` library has some weird dynamic binding conventions around `url-request-data`, `url-request-method`, and `url-request-extra-headers`, but `headers` and `status` don't appear to be among these?

**Comment by dgopsq** [comment]
You are right, it is useless actually. I removed `headers` and `status` and added a check to `url-http-response-status` directly, but now I rightly get a `Reference to free variable 'url-http-response-status'`. Can you tell me what's the best way to deal with this warning?

(I "learned" lisp just to make this plugin, and I've writed it quite a time ago, so I apologize for these kind of errors, and please tell me if you see something else that looks weird!)

**Comment by dgopsq** [comment]
That warning should be fixed too in the latest commit.

**Comment by riscy** [comment]
Great, thanks.  This looks good to go.  And, welcome to MELPA! :)

**Pull request merged**
