### PR TITLE
Add recipe for lexic

### PR DESCRIPTION
**Pull request by tecosaur**
### Brief summary of what the package does

This provides a major mode to view the output of dictionary tools,       
and utilities that perform searches and nicely format the results.       
                                                                         
Currently tied to sdcv, but this is intended to be changed in the future.

### Direct link to the package

https://github.com/tecosaur/lexic

### Your association with the package

Maintainer

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Is there any comparison to be made with [define-it](https://github.com/jcs-elpa/define-it) and similar lookup packages?  In the meantime, quick first pass --

### lexic.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
lexic.el:114: First line is not a complete sentence
Warning (emacs): 
lexic.el:143: Documentation strings should not start or end with whitespace
Warning (emacs): 
lexic.el:131: Symbols t and nil should not appear in single quotes
Warning (emacs): 
lexic.el:567: Some lines are over 80 columns wide
Warning (emacs): 
lexic.el:660: Argument `expected-word' should appear (as EXPECTED-WORD) in the doc string
Warning (emacs): 
lexic.el:735: First line is not a complete sentence
Warning (emacs): 
lexic.el:746: Some lines are over 80 columns wide
Warning (emacs): 
lexic.el:1380: Argument `pronunciation' should appear (as PRONUNCIATION) in the doc string
Warning (emacs): 
lexic.el:1726: Some lines are over 80 columns wide
```

package-lint (using version 20200906.512):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- lexic.el#L517: It's safer to sharp-quote function names; use `#'`
- lexic.el#L651: It's safer to sharp-quote function names; use `#'`
- lexic.el#L222: Optionally use `unless ...` instead of `when (null ...)`
- lexic.el#L513: Optionally use `unless ...` instead of `when (null ...)`

**Comment by riscy** [comment]
I will mark this awaiting upstream, but feel free to ping when ready for another look.

**Comment by tecosaur** [comment]
I'll probably get back to this sometime this week :slightly_smiling_face: will ping when I've done so. Thanks.

**Comment by tecosaur** [comment]
Hi @riscy, I've just pushed an update which should resolve all the issues you've raised.

**Comment by riscy** [comment]
Thanks!  Here's the latest --

### lexic.el ###

byte-compile (using Emacs 27.1):
```
lexic.el:662:1:Warning: argument `_expected-word' not left unused
```
I think simply removing the underscore in this variable name will fix this.

checkdoc (using version 0.6.2):
```
Warning (emacs): 
lexic.el:143: Documentation strings should not start or end with whitespace
Warning (emacs): 
lexic.el:570: Some lines are over 80 columns wide
```
The first checkdoc isn't so bad when I look at it, but also easy to fix.  The second can be fixed by rephrasing to e.g. `Test RESULT for failure and format accordingly`.

Looking a little more closely at the code itself:
- ```Turning on Text mode runs the normal hook `lexic-mode-hook'."``` -- should this be lexic mode, not Text mode?  Maybe I'm not understanding that mechanism
- This pattern when activating the major mode `(setq-local text-mode-hook (remove #'spell-fu-mode (remove #'flyspell-mode text-mode-hook)))` is a bit sneaky and won't work for user configs where these modes get activated some other way (via an anonymous function in the hook for example).  I would say to just warn users against it in your documentation, and suggest to them a lexic-mode hook they can run that can guard against this
- candicates -> candidates, seperators -> separators, definately -> definitely , prodessing -> processing

**Comment by tecosaur** [comment]
Hey @riscy, thanks for the revision.

Once again, I think I've taken care of everything mentioned :stuck_out_tongue:.

Regarding the `(setq-local text-mode-hook ...)`, I've added this to the mode docstring:
```
This mode locally removes any `spell-fu-mode' or `flyspell-mode' entries in
`text-mode-hook', but won't catch any other spell-checking initialisation.
Consider resolving any edge cases with an addition to `lexic-mode-hook'.
```

**Comment by riscy** [comment]
The latest gives --

byte-compile (using Emacs 27.1):
```
lexic.el:753:1:Warning: Unused lexical argument `expected-word'
lexic.el:1777:1:Warning: Unused lexical argument `expected-word'
lexic.el:1856:1:Warning: Unused lexical argument `expected-word'
lexic.el:1881:1:Warning: Unused lexical argument `expected-word'
```
so there are some areas where this argument is unused, and some where it's used.  If you only change the unused ones to `_expected-word` then this should be cleaned up.  It's minor but it'll get you to a clean byte compile.

I think fixing these will also fix the checkdoc nags around these variables not being documented.

Thanks, and sorry for the back and forth.  This is an easy merge once those are fixed. :)

**Comment by tecosaur** [comment]
@riscy I've addressed that. I think it should be good now.

**Comment by riscy** [comment]
Thanks, looks good to go!  Welcome to MELPA. :)

**Comment by tecosaur** [comment]
Brilliant! Just four more of my PRs to go now :smile:.

**Pull request merged**
