### PR TITLE
Add recipe for media-thumbnail

### PR DESCRIPTION
**Pull request by jojojames**
### Brief summary of what the package does

Package provides a way to create an image/thumbnail from a media file (picture/video). It also has a minor-mode to display these pictures in Dired.

### Direct link to the package repository

https://github.com/jojojames/media-thumbnail

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`media-thumbnail.el` with byte-compile using Emacs 28.1:
```
media-thumbnail.el:221:63: Warning: Unused lexical variable `file'
In media-thumbnail--redisplay:
media-thumbnail.el:237:63: Warning: Unused lexical variable `command'
In media-thumbnail-dired-mode:
media-thumbnail.el:356:6: Warning: Unused lexical variable `delay'
In end of data:
media-thumbnail.el:354:8: Warning: the function `dired-hide-details-mode' is
    not known to be defined.
media-thumbnail.el:306:30: Warning: the function `dired-get-filename' is not
    known to be defined.
media-thumbnail.el:303:16: Warning: the function `dired-move-to-filename' is
    not known to be defined.
media-thumbnail.el:252:12: Warning: the function `dired-do-redisplay' is not
    known to be defined.
```
I've seen the "unused lexical variable" popping up when using `pcase-let*`; it's sometimes tricky to solve, so let me know if I can help diagnose with macroexpand.  The last few seem to be due to a missing `(require 'dired)`.

`media-thumbnail.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- media-thumbnail.el#L323: It's safer to sharp-quote function names; use `#'`
- media-thumbnail.el#L356: It's safer to sharp-quote function names; use `#'`
```

**Comment by jojojames** [comment]
Woops, thanks for checking, hope I've fixed it all.

**Comment by riscy** [comment]
`media-thumbnail.el` with package-lint 20220607.738:
```
1 issue found:
33:10: warning: This file is not in the `cl-lib' ELPA compatibility package: require `cl-lib' instead.
```
I think this is fixed with `(require 'cl-lib)` and nothing more.

**Comment by jojojames** [comment]
Fixed.

**Comment by riscy** [comment]
Looks good.  I had one last look and I notice you're using the `:default` keyword to catch the default condition in `media-thumbnail-for-file`'s `cond`.  This is definitely not a blocker, but it's idiomatic/standard to just use `t` instead, to the point where when I'm looking at a `cond`, my eye is scanning for the `(t xyz)` at the end.  Your use of `:default` is more literate but "surprised" me in a way that made me have to read the code twice, especially with that `:defaullt` being packed in among other keywords like `:command`, etc.

**Comment by jojojames** [comment]
Noted, I always found (t ) to be confusing instead... I'll think it through.

**Pull request merged**
