### PR TITLE
Add fsbot-data-browser recipe

### PR DESCRIPTION
**Pull request by Benaiah**
Simple package to view the entry database of the resident bot at #emacs on Freenode.

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR(https://github.com/Benaiah/fsbot-data-browser/pull/1) about autoload cookie.

**Comment by Benaiah** [comment]
I’ve merged it and made a new release (for melpa-stable).

**Comment by syohex** [comment]
Merged

**Comment by purcell** [comment]
@Benaiah You're only using `-map` from `dash` -- why not just use the built-in `mapc` or `mapcar` instead, and drop the dependency?

**Comment by Benaiah** [comment]
@purcell good point, I think it just got left in from when I first wrote the function. I intentionally avoided request.el for the same reason, so I'll replace that.

**Pull request merged**
