### PR TITLE
Add recipe for plumber

### PR DESCRIPTION
**Pull request by 8dcc**
### Brief summary of what the package does

In short, it allows the user to call a different function depending on the format of the supplied text. For example, plumbing a URL might call the `browse-url` function, plumbing the text `printf(3)` might call the `man` function, and plumbing a path might open it in `dired`. The text formats can be configured by the user.

This package was inspired by [Plan9's plumber](https://9p.io/wiki/plan9/using_plumbing/index.html).

### Direct link to the package repository

https://github.com/8dcc/plumber.el

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

⸺ `plumber.el` with package-lint 20240923.1044:
```
3 issues found:
1:76: warning: You should depend on (emacs "24.1") if you need lexical-binding.
194:22: error: You should depend on (emacs "28.1") or the compat package if you need `format-prompt'.
207:16: error: You should depend on (emacs "25.1") or the seq package if you need `seq-find'.
```

**Comment by 8dcc** [comment]
Added dependencies for `emacs 25.1` and `compat 28.1.2.2` in https://github.com/8dcc/plumber.el/commit/b046aa7738c125cf2c20d1ff3201201cc714d4bd.

**Comment by riscy** [comment]
Thanks, the checklist looks great.

This seems like a good idea, reminiscent of the built-in `find-file-at-point` - have you used that command?  At the very least I think you should describe this as a `ffap` alternative to help its discoverability.  I think at least half of this behavior is captured by `ffap` (finding files, going to URLs, and composing mail) and the implementations there will probably inform more standard ways of going about things.

Some more specific feedback -
- For the "mail address" regexp, I think instead of `compose` you may want to call `browse-url-mail` (or just `browse-url`) because this hooks into what the user has configured as their preferred mail application
- For the "elisp expression" regexp, I think this will only work for zero-argument elisp expressions like `(this)` - not for elisp expressions `(like this)` which I suspect will be confusing for users.  But I would recommend being extra cautious with putting any kind of arbitrary elisp evaluation behind a do-what-I-mean keyboard shortcut, and maybe even dropping support for this

**Comment by 8dcc** [comment]
> This seems like a good idea, reminiscent of the built-in `find-file-at-point` - have you used that command? At the very least I think you should describe this as a `ffap` alternative to help its discoverability. I think at least half of this behavior is captured by `ffap` (finding files, going to URLs, and composing mail) and the implementations there will probably inform more standard ways of going about things.

I have used `find-file-at-point`, but only for jumping between source-code files. I was not aware that it could be used for URLs, for example. I added a note to the README in https://github.com/8dcc/plumber.el/commit/e54632cbc9c362f24ef0ecfebc923aa35f6ca384.

> For the "mail address" regexp, I think instead of `compose` you may want to call `browse-url-mail` (or just `browse-url`) because this hooks into what the user has configured as their preferred mail application

I think this is a good change. Added in https://github.com/8dcc/plumber.el/commit/7655ed6d6d69249488abf57a3b39fc762792be6f.

> For the "elisp expression" regexp, I think this will only work for zero-argument elisp expressions like `(this)` - not for elisp expressions `(like this)` which I suspect will be confusing for users.

I just tested it (on the [latest commit](https://github.com/8dcc/plumber.el/commit/e54632cbc9c362f24ef0ecfebc923aa35f6ca384)), and it worked fine. Quoting the [Emacs Manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Char-Classes.html):

>‘[:print:]’  
> This matches any printing character—**either spaces** or graphic characters matched by ‘[:graph:]’.

So it should support any whitespace character.

> But I would recommend being extra cautious with putting any kind of arbitrary elisp evaluation behind a do-what-I-mean keyboard shortcut, and maybe even dropping support for this

I did not consider this. I personally find it useful, but I could remove it from the default list, and add it in my personal config (and add a note to the README).

---

Apart from all this, I updated some stuff in the repository since I made the PR, but nothing big, mostly internal code. As a side note, if you have any suggestions for regexps that could be added to the default rule list, feel free to comment them here or on the repository.

**Comment by riscy** [comment]
> So it should support any whitespace character.

Have you tested this?  If I place my cursor on the opening parenthesis of `(message "Hello world")`, `plumber-plum` suggests I "Plum" `(message`.

> if you have any suggestions for regexps that could be added to the default rule list

An easy place to go looking is look at URI schemes like `ftp://`, `file://`, `irc://`, etc.

**Comment by 8dcc** [comment]
> If I place my cursor on the opening parenthesis of `(message "Hello world")`, `plumber-plumb` suggests I "Plumb" `(message`.

The regexp is not used when filling the [default value](https://github.com/8dcc/plumber.el/blob/e54632cbc9c362f24ef0ecfebc923aa35f6ca384/plumber.el#L194) of the prompt. The regexp is used to match if the actual user input; either what was typed on the `read-string` prompt, or the contents of the region, if active.

The default (or initial, depending on `plumber-fill-text-prompt`) value of the prompt is filled with [`plumber--thing-at-point`](https://github.com/8dcc/plumber.el/blob/e54632cbc9c362f24ef0ecfebc923aa35f6ca384/plumber.el#L165-L176). This function returns the *blank-delimited* word at point. Although I admit it could be improved, this is intentional because I couldn't really select something this "general" using the normal `thing-at-point` function.

> An easy place to go looking is look at URI schemes like `ftp://`, `file://`, `irc://`, etc.

I didn't think of this. Thanks.

**Comment by riscy** [comment]
I see - thank you for clarifying!

I'll hit merge now.  And welcome to MELPA. :)

**Pull request merged**
