### PR TITLE
Add recipe for helm-tramp

### PR DESCRIPTION
**Pull request by masasam**
### Brief summary of what the package does

Tramp with helm interface using ~/.ssh/config

### Direct link to the package repository

https://github.com/masasam/emacs-helm-tramp

### Your association with the package

I'm the author of the package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Emacs does not permit `add-to-list` against lexical variables. I got following errors at byte-compiling. Please remove `-*- lexical-binding: t; -*-` or rewrite it with `cl-pushnew`, `push` etc.

```
helm-tramp.el:55:63:Error: ‘add-to-list’ can’t use lexical var ‘hosts’; use
    ‘push’ or ‘cl-pushnew’
helm-tramp.el:57:5:Error: ‘add-to-list’ can’t use lexical var ‘hosts’; use
    ‘push’ or ‘cl-pushnew’
```

**Comment by masasam** [comment]
I modified it.
remove -*- lexical-binding: t; -*-
and
 I Add defvar so that tramp-default-method does not become undefined

**Comment by masasam** [comment]
sorry.
I canceled the previous one and rewrote it with push using -*- lexical-binding: t; -*-

**Comment by syohex** [comment]
Please don't redefine `tramp-default-method`, it is defined tramp.el.  Why don't you load `tramp.el` ?

**Comment by masasam** [comment]
Indeed I fixed it.

**Comment by syohex** [comment]
Merged. However please add docstring to `helm-tramp` command for users.

**Comment by masasam** [comment]
Thank you for the review

**Pull request merged**
