### PR TITLE
Add recipe for packages `loopy` and `loopy-dash`.

### PR DESCRIPTION
**Pull request by okamsn**
After working on the package longer, this a second attempt at adding this package. The first attempt was https://github.com/melpa/melpa/pull/7253, a few months ago.

### Brief summary of what the package does

- Loopy is a looping macro with more flexibility than `cl-loop`. It provides features like:
  - better destructuring 
    - arrays as well as lists
    -  fields such as passed to `setf`
    - destructuring for accumulation clauses, such that `(collect (i j) some-value)` destructures `some-value` and adds those values to the two lists `i` and `j` 
    - destructuring for variable declarations, such as in the `with`clause.
    - Ability to perform destructuring with `seq` and `pcase` as well as the built-in method.
  - a Lispy-er syntax, with clauses like `if`, `cond`, `when`, and `unless`
  - flexible order in loop clauses
  - Extensibility in adding new loop clauses and adding new names for clauses
  - Customizability in setting the default behavior for destructuring and assignment
  - Experimentally using arbitrary code inside the macro, and embedding some of the clauses inside that code. This feature still needs more testing.

- `loopy-dash` is a separate package that allows for destructuring using the Dash package.  Since every other library Loopy uses is built-in, I made this a separate package.

Loopy is mainly influenced by `cl-loop`, but, as requested in the previous PR to include this package, we have been trying to add features from Iterate. The syntax and clause names are specific to `loopy` (but have built-in aliases), but we are working to add keyword arguments to clauses to make it more comparable to the optional arguments found in Iterate.

### Direct link to the package repository

https://github.com/okamsn/loopy

Documentation: https://github.com/okamsn/loopy/blob/master/doc/loopy-doc.org

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
  - Byte compilation of `loopy-pcase.el` complains that a variable `_` is being used in a `lambda` function, even though it is not. I have not figured out why yet.
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
You mention this byte-compile (using Emacs 27.1):
```
loopy-pcase.el:82:1:Warning: variable `_' not left unused
```
I think this is because `cl-function` is mapping that argument into a new function based on the lambda, so it is technically used.  You can just change the function signature to `(lambda ((var val &rest rest)) ...` to quiet the byte-compiler.

A quick pass over the other checks:

checkdoc (using version 0.6.2):
```
Warning (emacs): 
loopy.el:797: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
loopy.el:799: Lisp symbol `top-level' should appear in quotes
Warning (emacs): 
loopy-iter.el:320: Argument `tree' should appear (as TREE) in the doc string
Warning (emacs): 
loopy-commands.el:1525: First line is not a complete sentence
Warning (emacs): 
loopy-commands.el:1525: Some lines are over 80 columns wide
```
Ultimately these are pretty easy and I think the second is even a false positive (I usually just write `top level` to avoid it).

**Comment by okamsn** [comment]
Thank you, I have fixed those issues.

What other things should be changed?

**Comment by riscy** [comment]
All set, thanks.  And, welcome to MELPA. :)

**Comment by okamsn** [comment]
> All set, thanks. And, welcome to MELPA. :)

Thanks!

**Pull request merged**
