### PR TITLE
Add consult-gh recipe

### PR DESCRIPTION
**Pull request by armindarvish**
-------

### Brief summary of what the package does

Interactive minibuffer interface to GitHub command-line client ("gh").
Uses consult to allow completing read across GitHub resources (repositories, issues,...)

### Direct link to the package repository

https://github.com/armindarvish/consult-gh

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I think `Package-Requires` dependencies on `f` and `embark` are missing from the main file, leading to some of the byte-compile issues below --

`consult-gh-embark.el` with byte-compile using Emacs 29.4:
```
consult-gh-embark.el:21:2: Error: Cannot open load file: No such file or directory, embark
```

`consult-gh-embark.el` with package-lint 20240507.1722 and `package-lint-main-file` = "consult-gh.el":
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

`consult-gh-embark.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- consult-gh-embark.el#L3: Have you done the paperwork to assign this copyright?
```
This might be worth double-checking especially since consult-gh.el has your copyright, but the supporting source files (like this one) have an FSF copyright.

`consult-gh-forge.el` with byte-compile using Emacs 29.4:
```
consult-gh-forge.el:80:34: Warning: Unknown slot `owner'
consult-gh-forge.el:82:33: Warning: Unknown slot `githost'
In consult-gh-forge--magit-setup-buffer-internal:
consult-gh-forge.el:161:13: Warning: assignment to free variable `magit-previous-section'
consult-gh-forge.el:164:13: Warning: assignment to free variable `magit-buffer-gitdir'
consult-gh-forge.el:165:13: Warning: assignment to free variable `magit-buffer-topdir'
In consult-gh-forge--topic-setup-buffer:
consult-gh-forge.el:200:28: Warning: Unknown slot `owner'
consult-gh-forge.el:204:11: Warning: Unused lexical variable `magit-generate-buffer-name-function'
consult-gh-forge.el:205:44: Warning: Unknown slot `worktree'
In consult-gh-forge--issue-view:
consult-gh-forge.el:243:131: Warning: `consult-gh--issue-view-action' called with 0 arguments, but requires 1
In consult-gh-forge--pr-view:
consult-gh-forge.el:280:131: Warning: `consult-gh--pr-view-action' called with 0 arguments, but requires 1
consult-gh-forge.el:280:184: Warning: reference to free variable `issue'
In end of data:
consult-gh-forge.el:242:37: Warning: the function `forge-get-topic' is not known to be defined.
consult-gh-forge.el:207:146: Warning: the function `forge-topic-mode' is not known to be defined.
consult-gh-forge.el:207:124: Warning: the function `forge-pullreq-mode' is not known to be defined.
consult-gh-forge.el:207:82: Warning: the function `forge-issue-p' is not known to be defined.
consult-gh-forge.el:173:8: Warning: the function `magit-refresh-buffer' is not known to be defined.
consult-gh-forge.el:170:6: Warning: the function `magit-display-buffer' is not known to be defined.
consult-gh-forge.el:164:34: Warning: the function `magit-gitdir' is not known to be defined.
consult-gh-forge.el:163:27: Warning: the function `magit-setup-buffer-internal' is not known to be defined.
consult-gh-forge.el:163:8: Warning: the function `magit-xref-setup' is not known to be defined.
consult-gh-forge.el:159:21: Warning: the function `magit-generate-new-buffer' is not known to be defined.
consult-gh-forge.el:156:32: Warning: the function `magit-current-section' is not known to be defined.
consult-gh-forge.el:155:20: Warning: the function `magit-get-mode-buffer' is not known to be defined.
consult-gh-forge.el:154:27: Warning: the function `magit-buffer-value' is not known to be defined.
consult-gh-forge.el:132:33: Warning: the function `magit-toplevel' is not known to be defined.
consult-gh-forge.el:133:26: Warning: the function `consult-gh--make-tempdir' is not known to be defined.
consult-gh-forge.el:126:6: Warning: the function `forge--pull-topic' is not known to be defined.
consult-gh-forge.el:104:57: Warning: the function `forge--split-forge-url' is not known to be defined.
consult-gh-forge.el:73:4: Warning: the function `closql-delete' is not known to be defined.
consult-gh-forge.el:66:10: Warning: the function `forge--pull' is not known to be defined.
consult-gh-forge.el:61:8: Warning: the function `forge-get-repository' is not known to be defined.
```

`consult-gh-forge.el` with package-lint 20240507.1722 and `package-lint-main-file` = "consult-gh.el":
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

`consult-gh-forge.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- consult-gh-forge.el#L3: Have you done the paperwork to assign this copyright?
- consult-gh-forge.el#L110: No `format` required; `message` takes an f-string
```

`consult-gh-transient.el` with package-lint 20240507.1722 and `package-lint-main-file` = "consult-gh.el":
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

`consult-gh-transient.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- consult-gh-transient.el#L3: Have you done the paperwork to assign this copyright?
```

`consult-gh.el` with byte-compile using Emacs 29.4:
```
consult-gh.el:658:14: Warning: `replace-regexp' is for interactive use only; use `re-search-forward' and `replace-match' instead.
In consult-gh--file-lookup:
consult-gh.el:1057:28: Warning: Unused lexical argument `args'
In consult-gh--file-state:
consult-gh.el:1082:22: Warning: Unused lexical variable `prefix'
consult-gh.el:1083:22: Warning: Unused lexical variable `suffix'
In consult-gh--files-view:
consult-gh.el:1141:32: Warning: Unused lexical argument `repo'
consult-gh.el:1166:11: Warning: Unused lexical variable `prefix'
consult-gh.el:1167:11: Warning: Unused lexical variable `suffix'
In consult-gh--repo-format:
consult-gh.el:1268:11: Warning: Unused lexical variable `w'
consult-gh.el:1269:11: Warning: Unused lexical variable `s'
consult-gh.el:1282:12: Warning: `mapcar' called for effect; use `mapc' or `dolist' instead
In consult-gh--repo-lookup:
consult-gh.el:1294:28: Warning: Unused lexical argument `args'
In consult-gh--repo-state:
consult-gh.el:1320:25: Warning: `mapcar' called for effect; use `mapc' or `dolist' instead
In consult-gh--repo-view:
consult-gh.el:1393:17: Warning: Unused lexical variable `org-display-remote-inline-images'
In consult-gh--repo-clone:
consult-gh.el:1432:58: Warning: Unused lexical argument `args'
In consult-gh--issue-list-format:
consult-gh.el:1744:12: Warning: `mapcar' called for effect; use `mapc' or `dolist' instead
In consult-gh--search-issues-format:
consult-gh.el:1795:12: Warning: `mapcar' called for effect; use `mapc' or `dolist' instead
In consult-gh--issue-lookup:
consult-gh.el:1813:28: Warning: Unused lexical argument `args'
In consult-gh--issue-state:
consult-gh.el:1840:25: Warning: `mapcar' called for effect; use `mapc' or `dolist' instead
In consult-gh--issue-view:
consult-gh.el:1922:17: Warning: Unused lexical variable `org-display-remote-inline-images'
In consult-gh--pr-list-format:
consult-gh.el:1981:12: Warning: `mapcar' called for effect; use `mapc' or `dolist' instead
In consult-gh--search-prs-format:
consult-gh.el:2025:12: Warning: `mapcar' called for effect; use `mapc' or `dolist' instead
In consult-gh--pr-lookup:
consult-gh.el:2036:28: Warning: Unused lexical argument `args'
In consult-gh--pr-state:
consult-gh.el:2064:29: Warning: `mapcar' called for effect; use `mapc' or `dolist' instead
In consult-gh--pr-view:
consult-gh.el:2149:17: Warning: Unused lexical variable `org-display-remote-inline-images'
In consult-gh--search-code-format:
consult-gh.el:2200:12: Warning: `mapcar' called for effect; use `mapc' or `dolist' instead
In consult-gh--code-lookup:
consult-gh.el:2211:28: Warning: Unused lexical argument `args'
In consult-gh--code-state:
consult-gh.el:2232:26: Warning: Unused lexical variable `query'
consult-gh.el:2236:26: Warning: Unused lexical variable `prefix'
consult-gh.el:2237:26: Warning: Unused lexical variable `suffix'
In consult-gh--code-view-action:
consult-gh.el:2296:11: Warning: Unused lexical variable `query'
In consult-gh--repo-list-transform:
consult-gh.el:2303:47: Warning: Unused lexical argument `builder'
consult-gh.el:2310:9: Warning: Unused lexical variable `input'
In consult-gh--search-repos-transform:
consult-gh.el:2439:50: Warning: Unused lexical argument `builder'
consult-gh.el:2446:9: Warning: Unused lexical variable `input'
In consult-gh--issue-list-transform:
consult-gh.el:2634:48: Warning: Unused lexical argument `builder'
consult-gh.el:2641:9: Warning: Unused lexical variable `input'
In consult-gh--search-issues-transform:
consult-gh.el:2759:51: Warning: Unused lexical argument `builder'
consult-gh.el:2766:9: Warning: Unused lexical variable `input'
In consult-gh--pr-list-transform:
consult-gh.el:2872:45: Warning: Unused lexical argument `builder'
consult-gh.el:2879:9: Warning: Unused lexical variable `input'
In consult-gh--search-prs-transform:
consult-gh.el:2996:48: Warning: Unused lexical argument `builder'
consult-gh.el:3003:9: Warning: Unused lexical variable `input'
In consult-gh--search-code-transform:
consult-gh.el:3108:49: Warning: Unused lexical argument `builder'
consult-gh.el:3115:9: Warning: Unused lexical variable `input'
In consult-gh:
consult-gh.el:3272:10: Warning: reference to free variable `consult-omni-default-interactive-command'
In end of data:
consult-gh.el:1644:47: Warning: the function `f-directory-p' is not known to be defined.
consult-gh.el:1390:17: Warning: the function `markdown-display-inline-images' is not known to be defined.
consult-gh.el:1389:17: Warning: the function `markdown-mode' is not known to be defined.
consult-gh.el:733:8: Warning: the function `org-fold-show-all' is not known to be defined.
consult-gh.el:732:8: Warning: the function `org-table-map-tables' is not known to be defined.
```

`consult-gh.el` with checkdoc 0.6.2 (fix *within reason*):
```
consult-gh.el:874: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:880: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:934: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:1157: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:1362: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:1474: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:1887: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:2112: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:2528: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:2655: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:2732: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:2847: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:2893: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:2968: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:3083: Lisp symbol `consult-gh' should appear in quotes
consult-gh.el:3228: Lisp symbol `consult-gh' should appear in quotes
```

`consult-gh.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- consult-gh.el#L769: It's safer to sharp-quote function names; use `#'`
- consult-gh.el#L1445: No `format` required; `message` takes an f-string
- consult-gh.el#L1489: No `format` required; `message` takes an f-string
- consult-gh.el#L1567: No `format` required; `message` takes an f-string
- consult-gh.el#L1625: No `format` required; `message` takes an f-string
```

`#'load`-check on each file:
```
Loading consult-gh.el
Loading consult-gh-transient.el
Loading consult-gh-forge.el
Loading consult-gh-embark.el
  consult-gh-embark.el:Error: Emacs 29.4:
  (file-missing "Cannot open load file" "No such file or directory" "embark")
```

Stderr output while compiling/loading:
```
magit/forge is not loaded. Make sure both magit and forge are installed and loaded before loading consult-gh-forge.
```

Package and license:
- Prefer equivalent recipe: `(consult-gh :repo "armindarvish/consult-gh" :fetcher github)`
- consult-gh.el must include all of the Package-Requires listed in consult-gh-embark.el, including: consult-gh "1.0"
- consult-gh.el must include all of the Package-Requires listed in consult-gh-forge.el, including: consult-gh "1.0", forge "0.3.3"
- consult-gh.el must include all of the Package-Requires listed in consult-gh-transient.el, including: consult-gh "1.0"
- GNU General Public License v3.0 (via repo API)
- consult-gh-embark.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- consult-gh-forge.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- consult-gh-transient.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- consult-gh.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

Package name:
- `consult-gh` conflicts with: https://github.com/emacsmirror/consult-gh (via emacsmirror)

**Comment by riscy** [comment]
Woops - please disregard that note about "conflicts with" at the bottom of my previous message.  That was only meant for me to double-check against, not for you to worry about.

**Comment by armindarvish** [comment]
@riscy Thank you for the feedback. I am working on resolving some issues, but the first thing I would like to do is to change the recipe and limit it to consult-gh.el. I think the right approach would be to make consult-gh-embark.el, consult-gh-forge.el, and consult-gh-transient.el their own package. Ideally, I would want to keep all the files in the same repository on GitHub but make separate recipes for each as a separate MELPA package. 

So what would be the recommendation. Should I change the recipe to something like this:

```
(consult-gh
 :fetcher github
 :repo "armindarvish/consult-gh"
 :files ("consult-gh.el" "dir" "*.info" "*.texi" "*.texinfo"
  "doc/dir" "doc/*.info" "doc/*.texi" "doc/*.texinfo"
  "docs/dir" "docs/*.info" "docs/*.texi" "docs/*.texinfo"
  (:exclude
   "screenshots/*.*" ".dir-locals.el" "lisp/.dir-locals.el"
   "test.el" "tests.el" "*-test.el" "*-tests.el"
   "lisp/test.el" "lisp/tests.el" "lisp/*-test.el" "lisp/*-tests.el")))
```

Or are there some other recommended approach?

**Comment by tarsius** [comment]
> Should I change the recipe to something like this:

No. Use `:files ("consult-gh.el")`.

**Comment by tarsius** [comment]
`:files ("consult-gh.el")` means "that one file and nothing else".

So `:files ("consult-gh.el" (:exclude "screenshots/*.*"))` is a meaningless complication.

Even if you used something like `:files (:defaults (:exclude "consult-gh-*.el"))`, you would *not* have to add `(:exclude "screenshots/*.*")`, because `:defaults` does *not* include `"screenshots/*.*"`.

**Comment by armindarvish** [comment]
Thanks @tarsius!
Ok, for some reason, I thought adding that exclude form would exclude that path from the git tree (which could then make the git cloning much faster). I just fixed this according to your recommendation. 

I just tested the recipe in vanilla emacs with package-build and it seems to work fine, although I do see some weird warning saying:
```
;; Please check the following package descriptor.
;; If the correct package description or dependencies are missing,
;; then the source .el file is likely malformed, and should be fixed.
(consult-gh
 . [(20240807 2133)
    ((emacs (29 1)) (consult (1 0)) (markdown-mode (2 6)))
    "Consulting GitHub Client" tar
    ((:commit . "245105f0131edd53494dd6cd17731d2e68fe8316")
     (:keywords "convenience" "matching" "tools" "vc")
     (:url . "https://github.com/armindarvish/consult-gh"))])
```

 Can you @rsicy and @tarsius take a look and advise if there is any changes needed. 
 
 Thanks!

**Comment by riscy** [comment]
Thank you both!  @armindarvish, the recipe looks great now.

These three remaining issues are because your Package-Requires should only be in your main file (consult-gh.el in this case) and they should include everything.  In our case, consult needs to be declared as a dependency inside consult-gh.el:

`consult-gh-transient.el` with package-lint 20240507.1722 and `package-lint-main-file` = "consult-gh.el":
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

`consult-gh.el` with byte-compile using Emacs 29.4:
```
consult-gh.el:43:2: Error: Cannot open load file: No such file or directory, consult
```

Package and license:
- consult-gh.el must include all of the Package-Requires listed in consult-gh-transient.el, including: consult-gh "1.1"



`consult-gh.el` with checkdoc 0.6.2 (fix *within reason*):
```
consult-gh.el:504: First sentence should end with punctuation
```
(Minor)

`consult-gh.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- consult-gh.el#L1027: Top-level `setq` should usually be replaced by `defvar` or `defconst`
```

**Comment by armindarvish** [comment]
@riscy Thanks for checking again.

> In our case, consult needs to be declared as a dependency inside consult-gh.el
How do I exactly do that? I already have `consult` under 'Package-Requires' in consult-gh.el. Is that not enough?

> Minor)
  consult-gh.el with [melpazoid](https://github.com/riscy/melpazoid)
  
I don't know if this is a very valid issue. The variable is declared with defvar earlier in the same file and later set with setq after the setter function is defined. Is there a better way of doing that?

Everything else should be fixed now!

**Comment by riscy** [comment]
I'm looking at your latest code and not seeing the issue re: consult firing anymore, so I think you're solid there.  It's possible I was somehow checking an older version of your code - if so, I apologize for the confusion!

Here's the latest I'm seeing - 

`consult-gh-transient.el` with byte-compile using Emacs 29.4:
```
consult-gh-transient.el:35:2: Error: Wrong type argument: stringp, nil
```

`consult-gh.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- consult-gh.el#L1027: Top-level `setq` should usually be replaced by `defvar` or `defconst`
```

`#'load`-check on each file:
```
Loading consult-gh.el
  consult-gh.el:Error: Emacs 29.4:
  (wrong-type-argument stringp nil)
Loading consult-gh-transient.el
  consult-gh-transient.el:Error: Emacs 29.4:
  (wrong-type-argument stringp nil)
```

Stderr output while compiling/loading:
```
"gh" is not found on this system

"gh" is not found on this system
```

I think the load-check and the stderrs are arising because of the aforementioned `setq`, which calls `(consult-gh--auth-current-active-account)` at load time; you should avoid doing things like logging into services when loading a package (e.g. what happens if the user is trying to start Emacs without an internet connection?)

**Comment by tarsius** [comment]
https://github.com/magit/forge/discussions/584#discussioncomment-10316823 should also be addressed before this is added to Melpa.

**Comment by armindarvish** [comment]
> [magit/forge#584 (comment)](https://github.com/magit/forge/discussions/584#discussioncomment-10316823) should also be addressed before this is added to Melpa.

@tarsius I don't think this is necessary, since we don't have forge integration in this recipe. I am planing to make the forge integration its own package (a.k.a. MELPA recipe) and when I do that, I have to address your comment.

**Comment by armindarvish** [comment]
@riscy, 

> consult-gh-transient.el with byte-compile using Emacs 29.4:
> consult-gh-transient.el:35:2: Error: Wrong type argument: stringp, nil



There is some circular logic here. I removed the `Package-Requires:` from consult-gh-transient per previous comments, but now it is throwing an error because it does not recognize `consult-gh` itself. So now I added back `Package-Requires: ((consult-gh 1.1))`! 


> consult-gh.el with [melpazoid](https://github.com/riscy/melpazoid): 
> - consult-gh.el#L1027: Top-level `setq` should usually be replaced by `defvar` or `defconst`

As I said before, the issue about `setq` v.s. `defvar` does not seem that relevant to me. I am first using `defvar` to define the variable and later in the code use `setq` to set it. I can change it if needed, but I don't see what's wrong with the current approach.

All other issues you are seeing is because the command line program `gh` is not available when you run your melpazoid tests. Even if you add `gh` (for example in a docker environment), you still need to log in with your GitHub account before `gh` works. The `consult-gh` Emacs package is checking if the command line program is available and working properly, and when not, throws an error, so the user knows to install and log in.

**Comment by tarsius** [comment]
> > [magit/forge#584 (comment)](https://github.com/magit/forge/discussions/584#discussioncomment-10316823) should also be addressed before this is added to Melpa.
> 
> @tarsius I don't think this is necessary, since we don't have forge integration in this recipe. I am planing to make the forge integration its own package (a.k.a. MELPA recipe) and when I do that, I have to address your comment.

Agreed.

**Comment by riscy** [comment]
Thanks for the latest -

>  So now I added back Package-Requires: ((consult-gh 1.1))!

I think the code has changed since you wrote this comment, as I don't see the Package-Requires on consult-gh in any of your files.  Don't hesitate to let us know here when you make such changes, because the extra context can definitely help me!

> As I said before, the issue about setq v.s. defvar does not seem that relevant to me

There are [ways that setq is different](https://www.gnu.org/software/emacs/manual/html_node/eintr/defvar.html) and I find the "only set the variable if it doesn't already have a value" useful as a developer, because I (e.g.) re-evaluate an entire buffer without clobbering existing customizations.  This isn't a big deal except that this `setq` is linked to the other issues, i.e. :   

> All other issues you are seeing is because the command line program gh is not available when you run your melpazoid tests.

The aforementioned top-level `setq` runs:
```elisp
(setq consult-gh--auth-current-account (consult-gh--auth-current-active-account))
```
And because this is at the top level, this gets run as soon as someone loads your code, e.g. when they start up a new Emacs session.  I can tell from your comment that you are aware that this means [gh auth status](https://cli.github.com/manual/gh_auth_status) gets called, which means "the authentication state of each known account is tested and any issues are included in the output."

But my key point is that this happens *when people are starting their Emacs session* and if it fails, it can interrupt further loading of their configuration file, which can needlessly put them in a difficult state to even fix the issue.

People should be able to load your code without having gh installed or an internet connection.

**Comment by armindarvish** [comment]
@riscy 

> I think the code has changed since you wrote this comment, as I don't see the Package-Requires on consult-gh in any of your files. Don't hesitate to let us know here when you make such changes, because the extra context can definitely help me!
> 

This should be solved now. Please check again.

> But my key point is that this happens _when people are starting their Emacs session_ and if it fails, it can interrupt further loading of their configuration file, which can needlessly put them in a difficult state to even fix the issue.
> 
> People should be able to load your code without having gh installed or an internet connection.

I understand the concern, and there was some elisp issue in
`consult-gh--auth-current-active-account` that I have now fixed to avoid causing the issue you were encountering before. 
To your general point about no internet connection, etc. the code checks if the program `gh` is available and also if there is no error in the output. So in all cases, whether gh is not available, or there is no internet connection, or the gh program is not logged in, ... everything should still load correctly. Or that was at least the intention, but there was some elisp error (wrong type variable) that I have now fixed.

Please let me know if the latest version works or there are still some outstanding issues.

**Comment by armindarvish** [comment]
Sorry I closed by mistake and reopened!

**Comment by riscy** [comment]
Thanks - I understand your intent!  The issue with loading the code failing when the subprocess call to "gh" fails appears to be fixed now.

The remaining issue that I see is that consult-gh-transient.el states a `Package-Requires` on `consult-gh`, but that file is *part* of `consult-gh`, so your package has a dependency on itself.  package-lint will indirectly tell you about this if you check `consult-gh-transient.el` with `package-lint-main-file` = "consult-gh.el":
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```
It indeed has no effect, but it should be fixed for correctness.

I will merge this now - thank you for accommodating the long turnaround time... And, welcome to MELPA! :)

**Pull request merged**
