### PR TITLE
Add tabak-theme recipe

### PR DESCRIPTION
**Pull request by timrichardt**
### Brief summary of what the package does

 A zenburn inspired theme with dark and light variants.

### Direct link to the package repository

https://github.com/timrichardt/tabak-theme

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback. (No issues found.)
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- Quick first pass over the checklist:

checkdoc (using version 0.6.2):
```
Warning (emacs): 
tabak-theme.el:55: First line is not a complete sentence
Warning (emacs): 
tabak-theme.el:67: First line is not a complete sentence
Warning (emacs): 
tabak-theme.el:1075: First line is not a complete sentence
```
I think these are easy to fix -- Emacs prefers a Python style docstring that looks like this:
```
  "Return a face specification.
SPEC has to be a property list with face properties. Foreground
...
```
which I believe makes it easier to create one-line apropos summaries.

Your license made me smile, but to be thorough we strive for licenses that are on the GPL-compatible list.  Regarding your current license:

- GitHub API found `Other`
  - Try to use a standard format for your license file.
    See: https://github.com/licensee/licensee
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to tabak-theme.el

**Comment by timrichardt** [comment]
O sorry, I did not apply the checkdoc suggestions.

First sentences are now exposed. `M-x checkdoc`

```
Buffer comments and tags:  Ok
Documentation style:       Ok
Message/Query text style:  Ok
Unwanted Spaces:           Ok
```

I moved to GPLv3. However, it is a shame, GitHub neglects Beeware as a license. Beerware even has such an SPDX identifier https://spdx.org/licenses/Beerware.html . :smiley:

I hope everything is fine now.

Thank you very much for your work!

**Comment by riscy** [comment]
> GitHub neglects Beerware as a license. Beerware even has such an SPDX identifier

Actually that's minor (and I realize now I wasn't very clear) -- the big issue is that Beerware isn't on the GPL-compatible list https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

Everything looks improved now, but there's a new (either that or I missed it) package-lint nag:

package-lint (using version 20210425.3):
```
1 issue found:
7:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```
and in this case I'd recommend just adding "faces" to that list to align.

**Comment by riscy** [comment]
I notice you made that Keywords change -- thanks for that.  That puts the checklist behind us.

As for the theme itself, I think you're defining the two versions in a somewhat idiosyncratic way.  The way you've defined the themes right now, I believe they won't show up in the <kbd>M-x load-theme</kbd> list which is the standard entrypoint to loading a new theme.  For an example of a package that does this well while respecting MELPA's namespace conventions, I think https://github.com/waymondo/apropospriate-theme provides a good example.

As an aside, it's actually come up recently that we might want to have a FAQ for how to create (multi-theme) color theme packages, so hopefully this'll be a clearer process in the future.

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to message if you have any questions.

**Pull request closed without merging**
