### PR TITLE
Add qt-pro-mode

### PR DESCRIPTION
**Pull request by EricCrosson**
### Brief summary of what the package does

Provides a major-mode for editing Qt build-system files.

### Direct link to the package repository

https://github.com/ericcrosson/qt-pro-mode

### Your association with the package

Maintainer, contributor, user

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by EricCrosson** [comment]
It seems like the ci build failed on the fetch of upstream `cask` resources

**Comment by purcell** [comment]
Thanks. I re-ran the build and it looks fine.

As for the specifics, the code looks good, just one little oddity: `(eval-after-load 'qt-pro-mode #'qt-pro-mode-associate-files)` is nonsensical, since that form will only execute when `qt-pro-mode` is loaded. In other words, just promote the code inside `qt-pro-mode-associate-files` to the top level and you'll get the same effect.

Bonus tip: `define-derived-mode` will automatically set the syntax table correctly based on its name, so you can omit `:syntax-table qt-pro-mode-syntax-table`. That macro will also define a major mode map for you, so instead of declaring it explicitly yourself, you can simply put code at the top level which adds entries to the keymap, as long as you place that code after the `define-derived-mode` form.

**Comment by purcell** [comment]
And re. `fic-mode`, you shouldn't decide for the user to enable this. It's orthogonal to this package, so you should leave it out: you can put it in your personal config easily enough: `(add-hook 'qt-pro-mode-hook 'fic-mode)`.

**Comment by EricCrosson** [comment]
Thanks for the tips! I appreciate the code review. 

[This commit](https://github.com/EricCrosson/qt-pro-mode/commit/804ff95e0b060708c160347e58296320565769ed) implements your feedback.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
