### PR TITLE
Add luarocks recipe

### PR DESCRIPTION
**Pull request by marsam**
### Brief summary of what the package does

Includes helpers for [LuaRocks](https://luarocks.org/)

### Direct link to the package repository

https://github.com/emacs-pe/luarocks.el

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR(https://github.com/emacs-pe/luarocks.el/pull/1). Please check it.

**Comment by purcell** [comment]
Quick feedback from me:
- "for Emacs" is redundant in `"LuaRocks tools for Emacs."` and should be removed. Same with ` in this Emacs`. later.
- Why use `(parse-colon-path (getenv "PATH"))` instead of `exec-path`? They should always be in sync anyway, otherwise all sorts of things can go wrong.

**Comment by marsam** [comment]
> "for Emacs" is redundant in "LuaRocks tools for Emacs." and should be removed. Same with in this Emacs. later.

Thanks for the suggestion, I've removed it.

> Why use (parse-colon-path (getenv "PATH")) instead of exec-path? They should always be in sync anyway, otherwise all sorts of things can go wrong.

I think `exec-path` is initialized from `PATH` on startup, so further modifications on `PATH`, can make them out of sync. e.g https://github.com/jorgenschaefer/elpy/issues/1086#issuecomment-282291034

**Comment by purcell** [comment]
> I think exec-path is initialized from PATH on startup, so further modifications on PATH, can make them out of sync. e.g jorgenschaefer/elpy#1086 (comment)

True, but then that's a bug elsewhere, including in the case you referenced. Emacs code generally relies on `exec-path` being correct at all times. You shouldn't have to add code to work around that IMO. Anyhow, I'll leave that choice to you.

**Pull request merged**
