### PR TITLE
Add recipe for ghub+

### PR DESCRIPTION
**Pull request by vermiculus**
### Brief summary of what the package does

Uses [apiwrap](https://github.com/vermiculus/apiwrap.el) to provide functions that wrap GitHub's API endpoints with [ghub](https://github.com/tarsius/ghub) calls.

### Direct link to the package repository

https://github.com/vermiculus/ghub-plus

### Your association with the package

Creator/maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by vermiculus** [comment]
It's allowing for some exciting things for Magithub 😄
screen shot 2017-05-07 at 1 26 17 am

**Comment by purcell** [comment]
Merged, thanks. There's a typo in the package description line you should probably fix though.

**Comment by vermiculus** [comment]
`a thick GitHub API client built *on* ghub`? Or is there another one?

**Comment by purcell** [comment]
That's the one. Sorry for being cryptic.

**Comment by vermiculus** [comment]
No worries, thanks for catching it!

**Pull request merged**
