### PR TITLE
Add recipe for sequential-yank

### PR DESCRIPTION
**Pull request by knu**
### Brief summary of what the package does

Minor mode for Emacs to copy and paste strings sequentially

### Direct link to the package repository

https://github.com/knu/sequential-yank.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

`sequential-yank.el` with byte-compile using Emacs 29.1:

```
In toplevel form:
sequential-yank.el:142:17: Warning: reference to free variable `mc/cursor-specific-vars'
sequential-yank.el:142:17: Warning: assignment to free variable `mc/cursor-specific-vars'
sequential-yank.el:143:17: Warning: reference to free variable `mc--default-cmds-to-run-once'
sequential-yank.el:143:17: Warning: assignment to free variable `mc--default-cmds-to-run-once'
sequential-yank.el:144:17: Warning: reference to free variable `mc--default-cmds-to-run-for-all'
sequential-yank.el:144:17: Warning: assignment to free variable `mc--default-cmds-to-run-for-all'

In end of data:
sequential-yank.el:94:42: Warning: the function `mc/all-fake-cursors' is not known to be defined.
```

`sequential-yank.el` with checkdoc (0.6.2)

```
No issues found
```

`sequential-yank.el` with package-lint (20230905.629)

```
55:0: error: `sequential-yank:push' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
59:0: error: `sequential-yank:replace' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
63:0: error: `sequential-yank:pop' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
79:0: error: `sequential-yank:ad:kill-new' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
88:0: error: `sequential-yank:auto-quit-maybe' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
141:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

Package and license:

- BSD-2

**Comment by riscy** [comment]
Re: the referencing of free variables, you can fix with `(require 'multiple-cursors)`; alternatively you may have to do bookkeeping using e.g. `(defvar mc/cursor-specific-vars)` and `declare-function`.

**Comment by knu** [comment]
@riscy Thanks, I've added declarations.

**Comment by riscy** [comment]
Thank you @knu.  Here's the latest --

`sequential-yank.el` with package-lint 20231110.1025:
```
6 issues found:
55:0: error: `sequential-yank:push' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
59:0: error: `sequential-yank:replace' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
63:0: error: `sequential-yank:pop' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
79:0: error: `sequential-yank:ad:kill-new' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
90:0: error: `sequential-yank:auto-quit-maybe' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
147:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```
I'm usually pretty strict about the non-standard separators, just to keep things as close as possible to the community conventions.  (Yes, some existing packages on MELPA don't follow all the rules, but these packages typically predate our contemporary list of checks.)

Re: `with-eval-after-load`
- I looked at some of the [relevant source for mc--default-cmds-to-run-once](https://github.com/magnars/multiple-cursors.el/blob/234806c832994cadedb42596fe235e91bbd59e8c/multiple-cursors-core.el#L398) and I think what you've done makes sense.  (I'll mention @magnars here so that he can consider making these public variables instead of private variables)

**Comment by knu** [comment]
@riscy OK, I've renamed the private functions with colons in their names.

**Comment by riscy** [comment]
Thanks, looks good.  One more thing I'll add as I hit merge is that your front-matter has a atypical order.  This won't bother any of the tools but, as a for-instance, the typical ordering would resemble something like this:
```elisp
;;; sequential-yank.el --- Minor mode to copy and paste strings sequentially

;; Author: Akinori MUSHA <knu@iDaemons.org>
;; URL: https://github.com/knu/sequential-yank.el
;; Created: 29 Oct 2023
;; Version: 0.1.1
;; Package-Requires: ((emacs "24.4"))
;; Keywords: killing, convenience

;; Copyright (c) 2023 Akinori MUSHA
;;
;; All rights reserved.
;;
;; Redistribution and use in source and binary forms, with or without
;; modification, are permitted provided that the following conditions
;; are met:
;; 1. Redistributions of source code must retain the above copyright
;;    notice, this list of conditions and the following disclaimer.
;; 2. Redistributions in binary form must reproduce the above copyright
;;    notice, this list of conditions and the following disclaimer in the
;;    documentation and/or other materials provided with the distribution.
;;
;; THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
;; ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;; IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;; ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
;; FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
;; DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
;; OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
;; HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
;; LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
;; OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
;; SUCH DAMAGE.

;;; Commentary:

;; This package provides a global minor mode to copy and paste strings
;; sequentially.

;; In `sequential-yank-mode', every killed/copied string is stored in
;; a global queue so they can later be yanked sequentially with the
;; `sequential-yank' command.

;; Support for multiple-cursors is built in.
```

**Pull request merged**
