### PR TITLE
Added recipe for popper.el.

### PR DESCRIPTION
**Pull request by karthink**
### Brief summary of what the package does

`popper.el` provides a minor-mode to designate buffers as "popups" and summon
and dismiss them with a key. Useful for many things, including toggling display
of REPLS, documentation, compilation or shell output, etc.

### Direct link to the package repository

https://github.com/karthink/popper

### Your association with the package

I'm the author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by karthink** [comment]
Updated dependencies as per [pull request](https://github.com/karthink/popper/pull/1) on `popper.el`.

**Comment by riscy** [comment]
Quick first-pass:

### popper.el ###

byte-compile (using Emacs 27.1):
```
popper.el:224:20:Warning: reference to free variable `popper-mode'
In popper-open-latest:
popper.el:243:20:Warning: reference to free variable `popper-mode'
```
You can fix these by declaring the mode before referencing the variable.

checkdoc (using version 0.6.2):
```
Warning (emacs): 
popper.el:175: First line is not a complete sentence
```

package-lint (using version 20210127.158):
```
2 issues found:
59:10: warning: This file is not in the `cl-lib' ELPA compatibility package: require `cl-lib' instead.
60:10: warning: This file is not in the `cl-lib' ELPA compatibility package: require `cl-lib' instead.
```

Other [lints](https://github.com/riscy/melpazoid):
- popper.el#L367: It's safer to sharp-quote function names; use `#'`
- popper.el#L374: It's safer to sharp-quote function names; use `#'`
- popper.el#L24: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- popper.el#L230: Optionally use `unless ...` instead of `when (not ...)`
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by karthink** [comment]
Thank you. I addressed all of these in [a1f0f33](https://github.com/karthink/popper/commit/a1f0f3356698f3e2fa25ddd0a7cc5c39e58acfd9). 

- package-lint and checkdoc report no messages.
- Byte compile is clean.
- Using sharp-quote on function names
- https on links
- Added a LICENSE file (GPL 3)

**Comment by riscy** [comment]
Thanks, the checklist is behind us.

I suspect this is in a novel space, but just in case there's an opportunity to collaborate or a redundancy, have you had a chance to compare to e.g. https://github.com/emacsorphanage/popwin/tree/1184368d3610bd0d0ca4a3db4068048c562c2b50 and any of the various other "pop" packages on MELPA? (I realize "popup" is used to describe all sorts of things in Emacs)

Some other minor nags as I scan through:
- `(progn (display-buffer buf))` -> no progn
- The variables `popper-reference-names` and `popper-reference-modes` look like they will always contain the exact same values as each other, but I may have missed something
- The docstring for `popper-popup-p` seems a bit misleading since it never actually makes use of the variable `popper-reference-buffers`

**Comment by karthink** [comment]
Thanks for the feedback. Some notes:

> I suspect this is in a novel space, but just in case there's an opportunity to collaborate or a redundancy, have you had a chance to compare to e.g. https://github.com/emacsorphanage/popwin/tree/1184368d3610bd0d0ca4a3db4068048c562c2b50 and any of the various other "pop" packages on MELPA? (I realize "popup" is used to describe all sorts of things in Emacs)

- I actually renamed the package from `popup-buffers` to `popper` before submission since `popup` is used for some kind of child frame display library in MELPA. Most other `popup` packages on MELPA are built on this feature, which is unconnected to popper-mode. The current name is intended to invoke `pop` in the sense of `pop-to-buffer`.

- popwin is indeed similar to my package, there is some redundancy there at the moment. But there are a couple of differences:

  - popwin provides an alternative interface to `display-buffer` and  `display-buffer-alist`, sort of like shackle.el. In the spirit of orthogonality, popper-mode only handles _when_ and in what order popups are displayed, leaving the _how_ to the user's display-buffer configuration. So it can work with shackle or popwin. (The code for popper-mode is much simpler and smaller as a result.)

  - My plan for its future involves integration with project.el/projectile or any user-defined predicate, so that only popups relevant to the current context are shown when cycling through them. (I'm working on this in a branch.) The idea is for `popper-toggle-popup` to behave in a DWIM fashion, giving the user the popup they expect.

> Some other minor nags as I scan through:
> - `(progn (display-buffer buf))` -> no progn

Fixed.

> - The variables `popper-reference-names` and `popper-reference-modes` look like they will always contain the exact same values as each other, but I may have missed something
> - The docstring for `popper-popup-p` seems a bit misleading since it never actually makes use of the variable `popper-reference-buffers`

`popper-reference-buffers` is the user-facing custom list that contains both buffer names (regexps) and buffer major-modes to identify popups. `popper-reference-names` and `popper-reference-modes` are created by separating `popper-reference-buffers` into these two categories. This is for convenience, so the user can specify a single list. So `popper-popup-p` is using both.

`popper-reference-buffers` is intended to be expanded to include user-defined predicates for identifying buffers.

If you would like to get an overview of the intended use and experience of this package, I [made a demo](https://www.youtube.com/watch?v=-1i9P54M4_8). (It includes a 'motivation' section, the timestamps might be helpful to navigate.)

**Comment by karthink** [comment]
Thanks for the feedback. Some notes:

> I suspect this is in a novel space, but just in case there's an opportunity to collaborate or a redundancy, have you had a chance to compare to e.g. https://github.com/emacsorphanage/popwin/tree/1184368d3610bd0d0ca4a3db4068048c562c2b50 and any of the various other "pop" packages on MELPA? (I realize "popup" is used to describe all sorts of things in Emacs)

I actually renamed the package from `popup-buffers` to `popper` before submission since `popup` is used for some kind of child frame display library in MELPA. Most other `popup` packages on MELPA are built on this feature, which is unconnected to popper-mode. The current name is intended to invoke `pop` in the sense of `pop-to-buffer`.

`popwin` is indeed similar to my package, there is some redundancy there at the moment. But there are a couple of differences:

  - popwin provides an alternative interface to `display-buffer` and  `display-buffer-alist`, sort of like shackle.el. In the spirit of orthogonality, popper-mode only handles when and in what order popups are displayed, leaving the how to the user's display-buffer configuration. So it can work with shackle or popwin. (The code for popper-mode is much simpler and smaller as a result.)

  - My plan for its future involves integration with project.el/projectile or any user-defined predicate, so that only popups relevant to the current context are shown when cycling through them. (I'm working on this in a branch.) The idea is for `popper-toggle-popup` to behave in a DWIM fashion, giving the user the popup they expect.

> Some other minor nags as I scan through:
> - `(progn (display-buffer buf))` -> no progn

Fixed.

> - The variables `popper-reference-names` and `popper-reference-modes` look like they will always contain the exact same values as each other, but I may have missed something
> - The docstring for `popper-popup-p` seems a bit misleading since it never actually makes use of the variable `popper-reference-buffers`

`popper-reference-buffers` is the user-facing custom list that contains both buffer names (regexps) and buffer major-modes to identify popups. `popper-reference-names` and `popper-reference-modes` are created by separating `popper-reference-buffers` into these two categories. This is for convenience, so the user can specify a single list. So `popper-popup-p` is using both.

`popper-reference-buffers` is intended to be expanded to include user-defined predicates for identifying buffers.

If you would like to get an overview of the intended use and experience of this package, I [made a demo](https://www.youtube.com/watch?v=-1i9P54M4_8). (It includes a 'motivation' section, the timestamps might be helpful to navigate.)

**Comment by riscy** [comment]
Thanks for the link to the excellent video and the explanation above.  This looks good to me -- welcome to MELPA!

**Comment by karthink** [comment]
Thank you.

> My plan for its future involves integration with project.el/projectile or any user-defined predicate, so that only popups relevant to the current context are shown when cycling through them. (I'm working on this in a branch.) The idea is for `popper-toggle-popup` to behave in a DWIM fashion, giving the user the popup they expect.

I just updated the repo with this feature. In the course of maintaining this package, is there anything I need to do besides run the above checks (checkdoc/package-lint/byte-compile etc) before committing to Master?

**Comment by riscy** [comment]
Nice -- nope, there's nothing you need to do beyond that.  If you wish to release a stable snapshot every once in a while, you can add tags.  See https://github.com/melpa/melpa/#melpa-stable

**Pull request merged**
