### PR TITLE
Add recipe for ddate

### PR DESCRIPTION
**Pull request by pymander**
### Brief summary of what the package does

Provides an easy interface for the ddate (Discordian date) command.

### Direct link to the package repository

https://git.sr.ht/~earneson/emacs-ddate

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- quick first pass:

`ddate.el` with byte-compile using Emacs 28.1:
```
ddate.el:101:1: Error: Symbol's value as variable is void: ddate-day-colors
```
Emacs attempts to expand/evaluate macros before it gets to anything else.  As a result I believe this is the result of a [wrong time](https://www.gnu.org/software/emacs/manual/html_node/elisp/Problems-with-Macros.html#Problems-with-Macros) issue in the code.

**Comment by pymander** [comment]
@riscy Ahhh, dang. Okay, I have taken out the `rx` macro and am just constructing regular expressions the old fashioned way. Can you please take another look?

**Comment by riscy** [comment]
Thanks, this looks good now.

As a minor suggestion, I might consider using `user-error` instead of `error` here, to avoid opening backtraces on users when the elisp code won't reasonably be at fault for the error.  But that's not a blocker -- merging.

**Comment by riscy** [comment]
As I hit merge, I also notice you should probably be using `shell-quote-argument` on the arguments that are being passed into `shell-command-to-string`.  These look safe enough right now, but I strongly recommend looking into that, just in case.

**Pull request merged**
