### PR TITLE
Add issue-link

### PR DESCRIPTION
**Pull request by sshaw**
### Brief summary of what the package does

Get the link to JIRA/Tracker/GitHub etc... bugs, features & issues. Turn their IDs into buttons.

### Direct link to the package repository

https://github.com/sshaw/issue-link

### Your association with the package

Developer/Maintainer

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by dakra** [comment]
Looks very similar to `bug-reference-mode` which is built-in to Emacs. Maybe you should describe the differences if your package does something else/better?

**Comment by sshaw** [comment]
> Looks very similar to bug-reference-mode which is built-in to Emacs. 

I hadn't heard of this, but seems like I can leverage it and drop a dependency. 

> Maybe you should describe the differences...

Yes, will do. Adding a link to the buffer is %33 of what it does.

**Comment by purcell** [comment]
Yep, I'm also not clear what this provides over and above `bug-reference-mode`, and we strongly prefer to not host multiple very similar packages where possible, to avoid confusion - it's better to have authors collaborate on established packages unless they're a disaster. :-)

**Comment by DamienCassou** [comment]
I'm closing this for now. Feel free to reopen when ready.

**Pull request closed without merging**
