### PR TITLE
Add recipe for dup-transform: utility for graphics programmers

### PR DESCRIPTION
**Pull request by garyo**
### Brief summary of what the package does

Simple Emacs package for graphics programmers, to duplicate and transform rgb/xy lines.

Graphics programmers often need to write near-duplicate code to process rgb or rgba pixels, or xy/xyz coordinates.
This package aims to make that a little more friction-free by auto-detecting common patterns and duplicating the lines with the proper transformations.

### Direct link to the package repository

https://github.com/garyo/dup-transform.el

### Your association with the package

I'm the author and intend to maintain it.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

`dup-transform.el` with package-lint 20240919.1647:
```
14 issues found:
10:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
43:0: error: "dup-tranform" doesn't start with package's prefix "dup-transform".
69:10: error: You should depend on (emacs "29.1") or the compat package if you need `keymap-global-set'.
85:23: error: You should depend on (emacs "28.1") or the compat package if you need `string-search'.
86:23: error: You should depend on (emacs "28.1") or the compat package if you need `string-search'.
87:23: error: You should depend on (emacs "28.1") or the compat package if you need `string-search'.
98:9: warning: Closing parens should not be wrapped onto new lines.
117:8: warning: Closing parens should not be wrapped onto new lines.
121:4: warning: Closing parens should not be wrapped onto new lines.
146:9: warning: Closing parens should not be wrapped onto new lines.
158:2: warning: Closing parens should not be wrapped onto new lines.
167:6: warning: Closing parens should not be wrapped onto new lines.
168:4: warning: Closing parens should not be wrapped onto new lines.
188:4: warning: Closing parens should not be wrapped onto new lines.
```

`dup-transform.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- The `;;; Commentary` for this file is much wider than 80 characters
```
(A lot of downstream consumers of the commentary will expect ~80 characters, whereas yours goes out to 113 characters.)

**Comment by garyo** [comment]
Thanks for the notes, @riscy . All of these should be fixed as of https://github.com/garyo/dup-transform.el/commit/6cbfb9

**Comment by riscy** [comment]
Thanks, checklist looks great.

I think this is a really cool idea - looking for *some* element on a line of code that looks like it could be iterated over, and then create an "unrolled loop" over those iterations.  This doesn't just apply to graphics programming, I think, but other situations where a `for` loop isn't the right choice (e.g. your struct or object-oriented based examples where you have struct.x, struct.y, and struct.z).  I feel like it's an idea that could perhaps be generalized, with inevitable UI considerations like: what if we see *two* elements that look iterable, how does the user specify which one to iterate over?

Anyway, this look good to merge to me, but I (very) quickly tried to find some graphics programming code* that felt like it might fit the patterns you use, but it seems to not work in the cases I found.  So I feel like there will be some effort required from the programmer to write code that matches your expected patterns, and that should ideally be made a bit more explicit in the Commentary, even with examples.

*That code (to be fair, I only looked around very quickly):
- https://github.com/miloyip/svpng/blob/master/example.c - C code, probably doesn't match expected patterns
- https://github.com/misund/hex-to-rgba/blob/master/src/index.js - js, intuitively seems to match expected patterns but fails
- https://github.com/colorjs/color-rgba/blob/master/index.js - js, seems to match expected patterns but only reproduces one

**Comment by riscy** [comment]
And, welcome to MELPA :)

**Comment by garyo** [comment]
Thanks!! I'll look into those cases & see what I can do to make it more useful.

**Pull request merged**
