### PR TITLE
Add recipe for work-timer

### PR DESCRIPTION
**Pull request by krisbalintona**
### Brief summary of what the package does

`Work-timer` is a flexible package for displaying a timer in the mode line. The timer counts up, and when it reaches its set duration, a sound is played. This package stands out by automatically determining the timer duration based on simple, user-defined functions (with functions for popular use cases built-in). Notably, these functions can take into account the history of completed timers, such as their durations and total running time. This makes for a means to create timers in a DWIM fashion whose durations reliably conform to your expectations (while allowing for the freedom to deviate when things don't go according to play).

As such, this `work-timer` is particularly useful for users who want to manage their work and break periods effectively, such as students aiming to be more productive. For example, the package makes it easy to work for a target of 25 minutes by creating a "work" timer, then, when taking a break, creating a "break" timer for 25% of the work time. Moreover, if the user works for only 15 minutes or even 50 minutes, the break timer can still be 25% of the time worked (or not, if the user configures the appropriate function to do so).

### Direct link to the package repository

https://github.com/krisbalintona/work-timer

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I suspect not, but any relationship to the Emacswiki `work-timer`? https://github.com/emacsmirror/emacswiki.org/blob/master/work-timer.el  - I may need to review my notes on what to do in the case where we have such a naming collision.

Some minor stuff re: sharp-quoting, fyi mostly -
- work-timer.el#L216: It's safer to sharp-quote function names; use `#'`
- work-timer.el#L816: It's safer to sharp-quote function names; use `#'`
- work-timer.el#L817: It's safer to sharp-quote function names; use `#'`
- work-timer.el#L818: It's safer to sharp-quote function names; use `#'`
- work-timer.el#L820: It's safer to sharp-quote function names; use `#'`
- work-timer.el#L821: It's safer to sharp-quote function names; use `#'`
- work-timer.el#L822: It's safer to sharp-quote function names; use `#'`

**Comment by krisbalintona** [comment]
> Thanks for this. I suspect not, but any relationship to the Emacswiki `work-timer`? https://github.com/emacsmirror/emacswiki.org/blob/master/work-timer.el - I may need to review my notes on what to do in the case where we have such a naming collision.

Oh, I didn't know there was another "work-timer." I hadn't checked the Emacswiki. Let me know what I should do about the name; I'm not married to it and can think of something else. I only figured the keywords "work" and "timer" would make the package more discoverable to those looking for what the package has to offer.

> Some minor stuff re: sharp-quoting, fyi mostly -
> 
>     * work-timer.el#L216: It's safer to sharp-quote function names; use `#'`
> 
>     * work-timer.el#L816: It's safer to sharp-quote function names; use `#'`
> 
>     * work-timer.el#L817: It's safer to sharp-quote function names; use `#'`
> 
>     * work-timer.el#L818: It's safer to sharp-quote function names; use `#'`
> 
>     * work-timer.el#L820: It's safer to sharp-quote function names; use `#'`
> 
>     * work-timer.el#L821: It's safer to sharp-quote function names; use `#'`
> 
>     * work-timer.el#L822: It's safer to sharp-quote function names; use `#'`

Good to know! I never did know why function names should be sharp-quoted since everything seems to work fine without it. I just looked it up and now I know — those lines are now fixed.

Please let me know if there are any other changes in order. This is my first time trying to add a package onto MELPA :)

**Comment by riscy** [comment]
> I'm not married to it and can think of something else.

Changing it might be the least confusing thing to do because, at least at one point in time, the Emacs wiki was treated as a "source" of Emacs packages.  And, btw, thank you for accommodating. :)

> sharp-quoted

Yes, sharp-quoting is totally optional but, if you sharp-quote everything you can, the byte-compiler can check at compile time if those functions exist.  I surfaced those with [melpazoid](https://github.com/riscy/melpazoid) which is my own little tangle of scripts for checking MELPA submissions.  The sharp-quote detection is just a couple dozen regexps - nothing sophisticated.

**Comment by krisbalintona** [comment]
Thanks for sharing your `melpazoid`. I might use that in the future. Before I go ahead and rename the package and all its functions, variables, and docstrings, I'd like to try and settle on a name we can both be happy with. What do you think about the following names:
- adaptive-timer
- focus-timer
- productivity-timer

As you can see, I'm partial to having "timer" in the title because I think it'd make discoverability much better. I think "productivity-timer" is the most discoverable and indicative of its functionality, so that's currently my favorite. I also don't believe the name has been used for an existing package (I've checked emacswiki, Reddit, and the popular package archives).

**Comment by riscy** [comment]
Of the three, only `focus-timer` has a (findable) package in a similar namespace:

- `focus` is similar: https://melpa.org/#/focus

All three are fine.  I also agree with having `timer` in there, and yes discoverability is important.

I don't know if it's any help, but the aforementioned melpazoid contains a [function](https://github.com/riscy/melpazoid/blob/master/melpazoid/melpazoid.py#L593) that does some name lookups from common sources.

**Comment by alphapapa** [comment]
@krisbalintona Have you seen https://github.com/alphapapa/hammy.el ?

**Comment by riscy** [comment]
I am remiss to forget hammy, and we should definitely compare - thank you @alphapapa!

**Comment by krisbalintona** [comment]
> @krisbalintona Have you seen https://github.com/alphapapa/hammy.el ?

@alphapapa You have a package for everything! I've checked out your package and here are a few comments. (Note: I actually knew about your package when I started writing the bespoke code that eventually turned out to be work-timer. However, that was a long while ago, before hammy had most of its features — hence why I wrote my own code.)

**Similarities**
- Has mode-line support (albeit of a different format).
- Supports overrun/overdue timer states.
- Freedom to set duration of timers however users like.
- Pauses for timers.
- Org-agenda integration.
- Timer sound.

**Differences**
- Work-timer does not support multiple timers running concurrently (and it isn't obvious to me how I would neatly implement that feature into the current codebase).
    - Consequently, hammy has UIs for selecting then acting on timers.
- Defining hammy timers is declarative. Work-timer chooses to have users set the value for work and break timer variables. (This is partially because work-timer only has one timer running.)
- **Work-timer has `work-timer-history`, which is basically a running log of all the parameters (duration, elapsed time, pauses, timer type) for every timer run.** (This is important to my use-case and I emphasize so in the README: I wanted the duration of my next timer to be determined by the parameters of previous timers I've run.)
- Hammy can only adjust the duration of timers (currently), whereas work-timer currently can change timer duration and elapsed time (and changing more parameters can be implemented easily).
- Hammy timers have properties, e.g, :before, :advance, :face, whereas work-timer doesn't (though theoretically much of that can be mirrored by user-defined functions, or somewhat easily implemented by work-timer itself).

That's roughly my comparison between hammy and work-timer (name potentially TBD!) based on a brief trial of hammy and a quick perusal of its code.

I'm not sure what should be done. On one hand, hammy and work-timer have many core similarities. In fact, as far as I can tell, hammy is more easily configurable to certain edge cases users might have (because of the `hammy-define` macro). (Also, hammy's code is probably more robust.) On the other hand, I feel like work-timer does currently fit a niche because how `work-timer-history` lets users, e.g., add or subtract from the duration of a timer if they took too long or too little a break previously. For instance, I think it'd be a non-trivial task for me to get hammy to a check all the boxes I've made work-timer to check for me.

There is the point that one package could be written to make the other obsolete. However, I'm not sure how difficult it would be to add features to hammy such that I'd have no need for work-timer. (And I do think hammy would be a better package to extend since its code seems to be a stronger base than mine.)

**Comment by alphapapa** [comment]
Hi @krisbalintona,

Thanks, that is a very thorough comparison!  A few thoughts:

> Defining hammy timers is declarative. Work-timer chooses to have users set the value for work and break timer variables. 

I agree that it can be convenient to set various parameters by using special variables.  This can be implemented easily in Hammy timers, for example, here's one I use in my personal config:
```el
(defcustom ap/hammy-flywheel-rest-duration "10 minutes"
  "Duration of Hammy flywheel rest intervals."
  :type 'string
  :group 'hammy)

(hammy-define (propertize "🎡" 'face '(:foreground "orange"))
  :documentation "Get your momentum going! (with MPC)"
  :intervals (list
              (interval :name "Rest"
                        :face 'font-lock-type-face
                        :duration (lambda (&rest _ignore)
                                    ap/hammy-flywheel-rest-duration)
                        :before (do (announce "Rest time!")
                                    (notify "Rest time!")
                                  (when ap/hammy-mpc-enabled
                                    (mpc-pause)))
                        :advance (remind "10 minutes"
                                         (do (announce "Rest time is over!")
                                             (notify "Rest time is over!")
                                           (run (concat "aplay " (expand-file-name "~/Misc/Sounds/Mario/smw_princess_help.wav"))))))
              (interval :name "Work"
                        :face 'font-lock-builtin-face
                        :duration (climb "5 minutes" "45 minutes"
                                         :descend t :step "5 minutes")
                        :before (do (announce "Work time!")
                                    (notify "Work time!")
                                  (when ap/hammy-mpc-enabled
                                    (ap/hammy-mpc-before (/ current-duration 60))))
                        :advance (remind "10 minutes"
                                         (do (announce "Work time is over!")
                                             (notify "Work time is over!")
                                           (run (concat "aplay " (expand-file-name "~/Misc/Sounds/Mario/smw_coin.wav")))))))
  :after (do (announce "Flywheel session complete!")
             (notify "Flywheel session complete!"))
  :complete-p (do (and (> cycles 1)
                       interval
                       (equal "Work" interval-name)
                       (equal (duration "5 minutes") current-duration))))
```
I usually use `embark` to set it, e.g. `C-h v ap/hammy-flywheel-rest-duration C-. =`, but one could also write commands to do so.

> Work-timer has work-timer-history, which is basically a running log of all the parameters (duration, elapsed time, pauses, timer type) for every timer run. (This is important to my use-case and I emphasize so in the README: I wanted the duration of my next timer to be determined by the parameters of previous timers I've run.)

Hammy does keep a log buffer, e.g. `M-x hammy-view-log RET`.  Also, each hammy timer keeps a history list of the intervals that have elapsed in the current session.  It would be relatively easy to enhance that functionality for various purposes (e.g. output to a log file).  I'd be glad to receive your ideas or contributions on that.

> Hammy can only adjust the duration of timers (currently), whereas work-timer currently can change timer duration and elapsed time (and changing more parameters can be implemented easily).

I'm not sure I understand this part exactly.  From Hammy's perspective, the elapsed time is just a calculation of the relevant intervals' start and stop times.  If you needed to adjust these times to make corrections for logging purposes, it wouldn't be difficult to write some commands to allow such adjustment interactively; I'm open to such ideas.

> On the other hand, I feel like work-timer does currently fit a niche because how work-timer-history lets users, e.g., add or subtract from the duration of a timer if they took too long or too little a break previously.

I think that could be implemented without too much difficulty, maybe without even changing Hammy itself.  For an example, see the code of Hammy's "1/3-rd time" timer, which calculates interval lengths based on the cumulative lengths of previous intervals.

> or instance, I think it'd be a non-trivial task for me to get hammy to a check all the boxes I've made work-timer to check for me, and I'm not sure if I could achieve even that. (Not to detract from hammy: perhaps my use is too idiosyncratic.)

You may be right.  OTOH my intention is that Hammy should provide the tools so that such user-specific workflows can be easily defined without having to write a whole library from scratch.  So I'd be glad to collaborate with you on implementing such things in Hammy, as your own code within a `hammy-define` form, and/or as enhancements to Hammy to make such things easier to do.

Anyway, your code works for you, which is always the most important thing.  But if you're interested in contributing to Hammy or collaborating to try to meet your needs with it, I'll be glad to.

**Comment by krisbalintona** [comment]
> > Defining hammy timers is declarative. Work-timer chooses to have users set the value for work and break timer variables.
>
> I agree that it can be convenient to set various parameters by using special variables. This can be implemented easily in Hammy timers, ...

I was just noting the difference. Seeing how you've implemented hammy, I do think your approach is more flexible, so implementation-wise I don't see a drawback to your approach.

> > Work-timer has work-timer-history, which is basically a running log of all the parameters (duration, elapsed time, pauses, timer type) for every timer run. (This is important to my use-case and I emphasize so in the README: I wanted the duration of my next timer to be determined by the parameters of previous timers I've run.)
>
> Hammy does keep a log buffer, e.g. `M-x hammy-view-log RET`. Also, each hammy timer keeps a history list of the intervals that have elapsed in the current session. It would be relatively easy to enhance that functionality for various purposes (e.g. output to a log file). I'd be glad to receive your ideas or contributions on that.

Ah, you're right. So hammy collects and reports on those relevant details, so it should be easy to store them for later reference by users in their timers, correct? If so, I think that'd go a long way to hammy supporting how I currently use work-timer.

> > Hammy can only adjust the duration of timers (currently), whereas work-timer currently can change timer duration and elapsed time (and changing more parameters can be implemented easily).
>
> I'm not sure I understand this part exactly. From Hammy's perspective, the elapsed time is just a calculation of the relevant intervals' start and stop times. If you needed to adjust these times to make corrections for logging purposes, it wouldn't be difficult to write some commands to allow such adjustment interactively; I'm open to such ideas.

I mentioned this because I sometimes (i) forget to pause a timer and want to shorten the elapsed time or (ii) forget to start a timer and wish to increase the elapsed time. But yes, even though I haven't looked through hammy.el thoroughly, it shouldn't be too hard to implement such a feature since you'd just be modifying the start time.

> > On the other hand, I feel like work-timer does currently fit a niche because how work-timer-history lets users, e.g., add or subtract from the duration of a timer if they took too long or too little a break previously.
>
> I think that could be implemented without too much difficulty, maybe without even changing Hammy itself. For an example, see the code of Hammy's "1/3-rd time" timer, which calculates interval lengths based on the cumulative lengths of previous intervals.

Hmmm, I see. I didn't notice the first go-around since the 1/3-rd time example code on the README has less than the actual 1/3rd-time code. So, if I'm understanding things correctly, there is an etc slot in the hammy struct that could store and reference unused/overdue time of previous timer(s). That's smart.

> Anyway, your code works for you, which is always the most important thing. But if you're interested in contributing to Hammy or collaborating to try to meet your needs with it, I'll be glad to.

I'm not a fan of bifurcating efforts and reinventing the wheel (especially when someone else's "wheel" is written better than mine lol), so if it's feasible to expand hammy to meet how I've been using work-timer (which is probably the case, but I'd need to try migrating to hammy to be sure), then I'd opt for that path instead. Accordingly, I would probably help work development on hammy, using work-timer until I can replace it with hammy. @alphapapa Thank you for taking the time to discus this with me!

I mention this because if that's the case, then work-timer probably shouldn't be added to MELPA, right, @riscy? Since hammy would ideally eclipse its functionality.

**Comment by riscy** [comment]
> I mention this because if that's the case, then work-timer probably shouldn't be added to MELPA, right, @riscy? Since hammy would ideally eclipse its functionality.

Yes.  Not just for hammy/work-timer but for all packages, this has been a mainstay of MELPA code review: "is there another package (on MELPA, ELPA, non-GNU ELPA?) that does close to the same thing?"

When that's the case, the best possible outcome is that any missing features and improvements get added to the package that's already in an archive.  Then the whole community benefits.  But making this decision isn't always easy, for reasons you can imagine.

I say you could try to implement atop and/or contribute into hammy to restore your workflow.  If it doesn't work out, we can always revisit this with more knowledge than we had before.

**Comment by krisbalintona** [comment]
Sounds good to me, looks like we're on the same page. I'll be experimenting with hammy.el and will try contributing in the case that I'd like some of the functionality I sought in work-timer to be officially added to the package. In any case, thank you for your time --- I'll close this PR for now, and will consider reopening if the above doesn't pan out.

**Pull request closed without merging**
