### PR TITLE
Add recipe for conda.el

### PR DESCRIPTION
**Pull request by necaris**
An environment manager for users of the Anaconda open data science toolchain and the `conda` tool for managing environments. Conda is primarily aimed at Python code, but also supports R and other general-purpose packages.

Available on GitHub at: https://github.com/necaris/conda.el -- I am the maintainer.

### CODE REVIEW

**Comment by syohex** [comment]
- `advice-add` and `advice-remove` were introduced at Emacs 24.4 but minimum Emacs version of this package is 24.0.

**Comment by purcell** [comment]
Agree re. `advice-add` etc.

Further feedback from me:

- Please omit `:files` here, since the default is fine.
- `in Emacs` is redundant.
- `conda-preactivate-hook` etc. should be `defcustom`s

(Obviously all sorts of hilarious things can go wrong when trying to temporarily set or apply/remove changes to `exec-path`, but it's hard to avoid that with packages like this that interface with very un-emacsy tools like `rbenv`, `virtualenv` etc.)

**Comment by necaris** [comment]
Thank you @syohex and @purcell for the review! Addressed your comments in https://github.com/necaris/conda.el/commit/83aae1718c626c6dfb4878a29f341a19b076c92c and https://github.com/melpa/melpa/pull/4246/commits/1ecc2acb9292a6d8ff17b78f201f227b51dbc43c :-)

**Comment by syohex** [comment]
Could you squash commits ?

**Comment by necaris** [comment]
@syohex done!

**Comment by syohex** [comment]
Thanks merged

**Pull request merged**
