### PR TITLE
Add recipe for makefile-executor

### PR DESCRIPTION
**Pull request by thiderman**
### Brief summary of what the package does

Various extensions to makefile-mode! Currently aimed at working with Makefile targets from a project perspective. If there are multiple makefiles, a `completing-read` between them is shown! When a Makefile is selected, another selection with all the possible targets is shown.

### Direct link to the package repository

https://github.com/thiderman/makefile-executor.el

### Your association with the package

Maintainer!

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, this looks handy! Quick feedback:
- Don't interpolate file paths into commands without using `shell-quote-argument`
- Rather than modify `makefile-mode-map`, you should generally provide a little minor mode, and then tell users to add it to `makefile-mode-hook`.
- Just adding `+` is a slightly lazy way to name this package, particularly when it's such a small and narrow add-on package. :-)

**Comment by thiderman** [comment]
Great feedback! I'll address the points and make adjustments accordingly! Thanks! :)

**Comment by thiderman** [comment]
I have addressed all the points of feedback and renamed the package! 💃 

I wasn't super sure of where to put the `shell-quote-argument`, mostly because all of the filenames involved are temporary files generated by emacs itself. Regardless, best practices are a good thing and I'd rather follow them than not!

**Comment by purcell** [comment]
Thanks.

**Pull request merged**
