### PR TITLE
Add textx-mode

### PR DESCRIPTION
**Pull request by novakboskov**
### Brief summary of what the package does

Basic support for editing [TextX](https://github.com/igordejanovic/textX) files.

### Direct link to the package repository

https://github.com/novakboskov/textx-mode

### Your association with the package

I am maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
This package requires Emacs 25.1 or higher versions. However it looks Emacs 24.3 can work. Which features requires Emacs 25.1 ?

**Comment by novakboskov** [comment]
@syohex It doesn't require any "special power" or Emacs 25.1. The sole reason I declared that version is that I've tested it only against that version because it is one which I'm currently using. Should I change that to 24.3?

**Comment by syohex** [comment]
> Should I change that to 24.3?

Yes if you possible. Because many people still use older version Emacs(Some Linux distribution like ubuntu does not provide Emacs 25.1 yet).

**Comment by novakboskov** [comment]
@syohex OK, changed.

**Comment by purcell** [comment]
Thanks. Quick feedback:
- You should include a `defgroup` form to declare the `textx` group
- `define-derived-mode` will generate the mode map and hook vars, so you don't need to declare those yourself
- `font-lock-defaults` is always buffer-local, so `setq` is sufficient, rather than `setq-local`

**Comment by novakboskov** [comment]
@purcell Thank you. :)
I did it that way in the latest commit.

**Comment by syohex** [comment]
Thanks. Merged.

**Pull request merged**
