### PR TITLE
flutter-l10n-flycheck: new recipe

### PR DESCRIPTION
**Pull request by amake**
### Brief summary of what the package does

An optional Flycheck checker companion package for flutter.el.

### Direct link to the package repository

https://github.com/amake/flutter.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
flutter-l10n.el:163: First line is not a complete sentence
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
1 issue found:

102:1: error: "forward-dart-string" doesn't start with package's prefix "flutter-l10n".
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
No issues! 🎉

Misc. automated checks:
- flutter-l10n.el#L23: Prefer `https` over `http` (if possible)

**Comment by riscy** [comment]
Wooops, sorry about that.  Wrong elisp file. :(

In the _correct_ file I only see a minor packag-elint issue:
```
1 issue found:

1:1: warning: The package summary should start with an uppercase letter or a digit.
```

**Comment by amake** [comment]
That's OK, the other file is a dependency so we might as well talk about it.

> flutter-l10n.el:163: First line is not a complete sentence

What is the best practice here? I couldn't find a good way to phrase it without going over 80 chars (to be honest, I didn't try that hard), so I wrapped it. I can squash the warning by escaping the line break, but then there's a super long line when inspecting docs with e.g. `describe-function`.

> 102:1: error: "forward-dart-string" doesn't start with package's prefix "flutter-l10n".

This is to support `bounds-of-thing-at-point` from `thingatpt`:

```
;; The function bounds-of-thing-at-point finds the beginning and end
;; positions by moving first forward to the end of the "thing", and then
;; backwards to the beginning.  By default, it uses the corresponding
;; forward-"thing" operator (eg. forward-word, forward-line).
```

The other option is to use symbol properties, but those seemed a bit magical so I went with the function.

> 1:1: warning: The package summary should start with an uppercase letter or a digit.

I've now fixed this.

**Comment by riscy** [comment]
> What is the best practice here?

Just looking at your latest code, I think it would be straightforward to write:
```elisp
  "Return a hash table of existing IDs found in `flutter-l10n-file'.
Values are t."
```
One rationale is that `apropos` shows a listing that _only_ contains the first line of every docstring, so it's best if that line is somehow complete.

Thanks re: `thingatpt`, I wasn't aware of that!  I'll take a deeper look at the code soon.

**Comment by amake** [comment]
Thanks for the suggestion. I've pushed fixes for all outstanding issues.

> Thanks re: thingatpt, I wasn't aware of that! I'll take a deeper look at the code soon.

I just bit the bullet and went with the symbol property solution.

**Comment by riscy** [comment]
Great thanks!  Sorry about the long turnaround. :)

**Pull request merged**
