### PR TITLE
Add recipe for khalel

### PR DESCRIPTION
**Pull request by hperrey**
### Brief summary of what the package does

Import, edit and create calendar events using command-line tool khal

### Direct link to the package repository

https://gitlab.com/hperrey/khalel

### Your association with the package

author/maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- just a very quick pass over the checklist:

### khalel.el ###

byte-compile (using Emacs 27.1):
```
khalel.el:194:1:Warning: Unused lexical variable `org-icalendar-use-scheduled'
khalel.el:194:1:Warning: Unused lexical variable `org-icalendar-store-UID'
In khalel-add-capture-template:
khalel.el:268:17:Warning: reference to free variable `org-capture-templates'
khalel.el:268:17:Warning: assignment to free variable `org-capture-templates'
khalel.el:301:1:Warning: Unused lexical variable `win'
khalel.el:322:1:Warning: Unused lexical variable `desc'
In khalel--capture-finalize-calendar-export:
khalel.el:326:26:Warning: reference to free variable `org-capture-plist'
khalel.el:358:1:Warning: Unused lexical argument `event'
```
(I'm not sure where some of those org- variables come from, but you may need to `Package-Require` a later version of org-mode).

And while I've got you:
- khalel.el#L188: No `format` required; `message` takes an f-string

**Comment by hperrey** [comment]
Thank you very much for the review and helpful feedback!
This is my first package (and submission to melpa) and I really appreciate your time and help :)

I fixed the causes of those warnings now by cleaning up and/or requiring the specific org-packages where the necessary variables are defined. All changes are in the repo -- BTW, I bumped the version number and realized that was maybe a bit hasty. Just wanted the latest tag to be as clean as possible and hope that doesn't interfere with the submission process..

**Comment by riscy** [comment]
> BTW, I bumped the version number and realized that was maybe a bit hasty. Just wanted the latest tag to be as clean as possible and hope that doesn't interfere with the submission process..

Nope, you're fine. :)  By default MELPA will automatically generate a `Package-Version` for your file based on the last commit to the repo -- your `Version` header is for you and your users (and should correspond with the names of your tags/releases if you choose to do so).

These are non-blocking, but a few more small items:
- "throuh khal" -> "through khal" in your summary line
- `defgroup khalel nil` sets its parent group as `Calendar` but this should be `calendar` (downcased)
- `defcustom khalel-default-calendar "privat"` -- is `privat` the normal default, or should this be `private`?
- `defcustom khalel-default-alarm "10"` is this in minutes (the docstring could say); the `:type` might also be changed to an `'integer`, I think, if that's a restriction
- "duplicate entires" -> "duplicate entries"

**Comment by hperrey** [comment]
Thank you so much for the review and merge! :)

**Pull request merged**
