### PR TITLE
Add lsp-ui

### PR DESCRIPTION
**Pull request by sebastiencs**
### Brief summary of what the package does

Package that contains all the higher level UI modules of `lsp-mode`

### Direct link to the package repository

https://github.com/emacs-lsp/lsp-ui

### Your association with the package

Maintainer

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Yeah, this isn't going to work because the [lsp-mode](https://melpa.org/#/lsp-mode) package already has `lsp-flycheck`. `lsp-ui` shouldn't contain files or symbols whose names don't start with `lsp-ui`. (`lsp-mode` is allowed to use `lsp-*`.) My suggestion would be to rename files as necessary, or get them merged to `lsp-mode` upstream.

P.S. Re. the face definitions in `lsp-xref`, you should either `:inherit` from built-in faces (preferred) or specify both `dark` and `light` variants.

**Comment by sebastiencs** [comment]
@purcell Thanks for the review !
I have made the necessary changes

**Comment by purcell** [comment]
Great, thanks. To avoid clashes, I think you'll have to rename the `'lsp` flycheck checker to `'lsp-ui`. Looks good otherwise.

**Comment by MaskRay** [comment]
lsp-flycheck is now lsp-ui-flycheck. Really thanks to sebastiencs for pushing forward all of these!

lsp-ui-doc.el with cquery --enable-comments is so amazing

**Comment by sebastiencs** [comment]
@purcell done :)

**Comment by MaskRay** [comment]
Will we have lsp-ui in Melpa by the end of 2017 🎆🎉

**Comment by purcell** [comment]
> Will we have lsp-ui in Melpa by the end of 2017 🎆🎉

Not in New Zealand. ;-)

**Comment by purcell** [comment]
... But maybe where _you_ are. Happy New Year!

**Pull request merged**
