### PR TITLE
Add recipe for ruff-flymake

### PR DESCRIPTION
**Pull request by cjfuller**
### Brief summary of what the package does

This is a flymake backend for the python linter [ruff](https://github.com/charliermarsh/ruff). While ruff itself technically supports emacs via the language server protocol, a dedicated flymake backend allows you to run a primary language server in eglot that provides more than just lint suggestions while still seeing feedback from ruff. Ruff itself is an extremely fast linter that combines rules from a number of python linters into one tool.

### Direct link to the package repository

https://github.com/cjfuller/ruff-flymake

### Your association with the package

I am the author / maintainer.

### Relevant communications with the upstream package maintainer

**None needed.**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  ruff is an exciting tool in the Python universe. :)  Quick first pass --

`ruff-flymake.el` with byte-compile using Emacs 28.1:
```
ruff-flymake.el:76:34: Error: Wrong type argument: proper-list-p, (beg . end)
```

Package and license:
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to ruff-flymake.el

**Comment by cjfuller** [comment]
Thanks!

I've pushed an update that fixes the wrong type argument issue and adds an SPDX license ID to the lisp file itself.

While I'd run `M-x byte-compile` before, I think I didn't have flymake set up correctly to see the feedback it produces (hence missing the error you indicated), and now after fixing that, I am getting bunch of warning-level diagnostics about using free variables in the cl-loop macro (on "while", "for", etc.), which seems to me like the linter is just not understanding the cl-loop macro. Is this ok to ignore? As far as I can tell my only other option is not to use this macro, which seems silly.

**Comment by riscy** [comment]
Yeah - most likely you're not seeing all of the compilation warnings because you're compiling your code in an instance of Emacs that has already loaded the code, or some past version of it at least.

In the case of these byte-compile warnings:

`ruff-flymake.el` with byte-compile using Emacs 28.1:
```
ruff-flymake.el:75:27: Warning: reference to free variable `while'
ruff-flymake.el:78:27: Warning: reference to free variable `for'
ruff-flymake.el:78:31: Warning: reference to free variable `msg'
ruff-flymake.el:78:35: Warning: reference to free variable `='
ruff-flymake.el:81:75: Warning: reference to free variable `line'
ruff-flymake.el:81:80: Warning: reference to free variable `col'
ruff-flymake.el:82:79: Warning: reference to free variable `region'
ruff-flymake.el:82:27: Warning: reference to free variable `collect'
ruff-flymake.el:83:27: Warning: reference to free variable `into'
ruff-flymake.el:83:32: Warning: reference to free variable `diags'
ruff-flymake.el:84:27: Warning: reference to free variable `finally'
```

it looks like you're missing a `(require 'cl-lib)` in order to use the `cl-loop` macro.

**Comment by cjfuller** [comment]
Ah ok, thank you, that makes sense. I added an `(eval-when-compile (require 'cl-lib))`, and it looks like those warnings are gone.

**Comment by riscy** [comment]
This just occurred to me, but the large majority of flymake packages are named `flymake-xyz`, as opposed to `xyz-flymake` like you have here.  It might help to prevent redundant packages from being written if you used the former naming convention.  Let me know what you think about that before we merge?

You'll have to:
- Update the recipe filename
- Change the name of the file, and the prefixes of its functions/variables
- Update the recipe itself (both the name of the packages and possibly the repo name)
but I think it will be worth it.

**Comment by cjfuller** [comment]
Sure, I can do that! (I always thought the convention was a bit silly because how often are you going to the package list to look for all the things flymake can do vs. how often are you going to the package repo to look for all the packages related to a given language or tool? But as you point out the benefits of following the convention probably outweigh any other concern here.)

**Comment by cjfuller** [comment]
Never mind, while doing the rename, it appears that since the time I originally wrote this package, someone has created and gotten merged into MELPA `flymake-ruff`, so no need for this!

(Apologies for wasting your time on a duplicate, and thanks anyway for helping me learn more about emacs packaging!)

**Pull request closed without merging**
