### PR TITLE
Add marginalia

### PR DESCRIPTION
**Pull request by minad**
### Brief summary of what the package does

Marginalia mode adds annotations to minibuffer-completions and enhances existing commands by adding a completion category if a command does not provide a completion category by itself. The category is inferred by some heuristics, e.g., by looking at the prompt. This package is meant to be used in conjuction with [Consult](https://github.com/minad/consult) (see PR #7255) and [Embark](https://github.com/oantolin/embark). The package has been extracted from these two packages in order to avoid overlap and to separate concerns. Formerly Consult supported `consult-annotate-mode` which has been superseded by this package.

This package is comparable to packages like [ivy-rich](https://github.com/Yevgnen/ivy-rich), but without the Ivy dependency.
Like Consult and Embark, Marginalia mode is completion system agnostic. It works with [icomplete-vertical](https://github.com/oantolin/icomplete-vertical) and [selectrum](https://github.com/raxod502/selectrum). In principle it could also work with other completion frameworks, but 
for Helm and Ivy other Helm/Ivy-specific annotator libraries already exist.

### Direct link to the package repository

https://github.com/minad/marginalia

### Your association with the package

Co-maintainer/co-author together with @oantolin 

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick notes:

* Don't override `:weight` when inheriting other face definitions. Just leave them untouched and trust the "upstream" theme - they can be customised as desired by the user in a way that fits their taste.
* You might like to just use `regexp-quote` [here](https://github.com/minad/marginalia/blob/main/marginalia.el#L164)
* [Here](https://github.com/minad/marginalia/blob/main/marginalia.el#L180) you should just require `package`. It will almost inevitably have been loaded at startup time anyway.

These are not blockers, so I will go ahead and merge now, first removing the unnecessary `:branch main` spec from the recipe -- we use the default branch for the repo, which is `main`.

**Comment by oantolin** [comment]
Thank you Steve!

A couple of questions about the feed back:

- The reason we don't `require` package is that we actually don't require it, that is, if you have it loaded and use its commands you get some functionality, but if you are one of those people that avoid loading it, we don't force you to (and of course, you don't get the associated functionality from our package). Is that OK?

- I don't understand the `regexp-quote` suggestion at all, I'm afraid. It points to variable that holds an alist with regexps in it. The regexps match some words as words, i.e., between word boundaries. How would `regexp-quote` help here?

**Comment by minad** [comment]
> Here you should just require package. It will almost inevitably have been loaded at startup time anyway.

I am using package.el myself, so I would also be okay with requiring package the beginning. But as far as I understood from straight.el, package.el is an optional component.

> Don't override :weight when inheriting other face definitions. Just leave them untouched and trust the "upstream" theme - they can be customised as desired by the user in a way that fits their taste.

This can be fixed!

**Comment by purcell** [comment]
> * The reason we don't `require` package is that we actually don't require it, that is, if you have it loaded and use its commands you get some functionality, but if you are one of those people that avoid loading it, we don't force you to (and of course, you don't get the associated functionality from our package). Is that OK?

I mean, it's okay, but just feels clunky. I think any user of a recent Emacs would have to jump through some hoops to avoid loading `package.el` (even if using `straight`), and this way you have to declare a whole bunch of vars and functions. But sure, take your pick! :-)

> * I don't understand the `regexp-quote` suggestion at all, I'm afraid. It points to variable that holds an alist with regexps in it. The regexps match some words as words, i.e., the regexps contain `\<` and `\>` which match word boundaries. How would `regexp-quote` help here?

I misread this as escaped `<` and `>` sorry. You're right. But you can use `regexp-opt` with a single-element list potentially. Just thinking about risk of typos in the `\\<` matches...

**Comment by purcell** [comment]
Actually I'd probably just `rx` those patterns.

**Comment by minad** [comment]
> I mean, it's okay, but just feels clunky.

It is a bit clunky. But right now we took the road to avoid loading some non-strictly necessary components. In general we try to keep dependencies low for those packages. As you have observed, marginalia and consult have no dependency (while it is nice if the packages are used together), and it could happen as well that embark won't depend on marginalia. @oantolin knows more.

> Actually I'd probably just rx those patterns, and I say that as a reformed Perl hacker who loves regexps.

I am a *non-reformed* Perl hacker if only regarding regexps. I would love to see pcre2el and pcre2el-mode reloaded. Since this code is by @oantolin, he should respond. But from what I see, there does not seem to be a need to change anything here.

**Comment by purcell** [comment]
> But from what I see, there does not seem to be a need to change anything here.

Yeah, it's totally fine, ultimately. I'm just spouting options.

**Comment by aspiers** [comment]
The removal of `:branch "main"` has actually broken installation via [raxod502/straight.el](https://github.com/raxod502/straight.el), although perhaps that is arguably a bug in straight.el - looking into that now.  I have also reported it in https://github.com/minad/marginalia/issues/24.

**Comment by aspiers** [comment]
Submitted as https://github.com/raxod502/straight.el/issues/647

**Pull request merged**
