### PR TITLE
Add sly-company

### PR DESCRIPTION
**Pull request by joaotavora**
Tested this with 

```
make clean
make sandbox
M-x package-list-packages
C-s sly-company
i
x
```

All the dependencies pulled in correctly. `M-x sly` starts a REPL and `M-x sly-company-mode` gets you running.

### CODE REVIEW

**Comment by nlamirault** [comment]
I can't find sly-company from Melpa stable. Any idea ?

**Comment by purcell** [comment]
sly-company.el was only added to the repository after the most recent version tag there, so there's no tagged version of it for melpa stable to use.

**Comment by nlamirault** [comment]
Thanks !

**Comment by capitaomorte** [comment]
@purcell does this mean that if I retag sly-company it'll be included in melpa stable?

**Comment by purcell** [comment]
Yes it does. If you need/want the versions to be separate from those of `slime-company`, you'd need separate repos.

**Comment by capitaomorte** [comment]
Alright. It is a different repo, differently named, even though github registers it as a fork , which it is. I've tagged sly-company 0.8 and pushed.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
