### PR TITLE
Update move-text

### PR DESCRIPTION
**Pull request by jasonm23**
Don't pull from the emacswiki - new repo added

### CODE REVIEW

**Comment by purcell** [comment]
Yay, thanks.

**Comment by Wilfred** [comment]
Argh, I patched the version on the wiki just after this changed. :)

**Comment by jasonm23** [comment]
You're the reason why this had to happen.  Your fix broke some people and there was no oversight.

**Comment by jasonm23** [comment]
We will need to nail down which versions broke

**Comment by jasonm23** [comment]
Would you open an issue on the repo itself, and we will get it fixed up :+1:

**Comment by jasonm23** [comment]
(In the meantime we can make the old version stable and the latest on wiki, edge.)

**Comment by Wilfred** [comment]
Sorry about that. I've opened https://github.com/emacsfodder/move-text/issues/2 so we can fix this properly.

**Pull request merged**
