### PR TITLE
Add wallpaper package

### PR DESCRIPTION
**Pull request by farlado**
### Brief summary of what the package does

Wallpaper management within Emacs, including:

- Choosing a static wallpaper or set of wallpapers
- Cycling randomly through wallpapers in a directory
- Setting specific wallpapers for given workspaces (e.g. in EXWM or i3wm)

Currently depends on feh, but I am open to expanding it to try to work with other wallpaper-setting programs.

### Direct link to the package repository

https://github.com/farlado/emacs-wallpaper

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly (on Emacs 27)
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Just a very quick first pass:

byte-compile-file (using Emacs 26.3):
```
wallpaper.el:232:4:Warning: directory-files-recursively called with 5
    arguments, but accepts only 2-3
```

**Comment by farlado** [comment]
> Just a very quick first pass:
> 
> byte-compile-file (using Emacs 26.3):
> 
> ```
> wallpaper.el:232:4:Warning: directory-files-recursively called with 5
>     arguments, but accepts only 2-3
> ```

Whoa, none of the linters have introduced warnings about differences between Emacs 26 and 27. Pushing the fix ASAP.

**Comment by alphapapa** [comment]
@farlado You can use this with GitHub Actions to lint on multiple Emacs versions: https://github.com/alphapapa/makem.sh

**Comment by farlado** [comment]
@alphapapa Thanks, it passes now. A single warning is displayed when the test is run, but this is expected behavior for my package when feh isn't found upon loading.

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

1. Please use `Version` instead of `Package-Version`.

---

1. Please check external command is exist or use Elisp instead of invoking external command.
```diff
modified   wallpaper.el
@@ -279,9 +279,11 @@ Returns nil if variable `wallpaper-per-workspace-mode' is nil."
   "Get the current i3 workspace."
   (if (= (shell-command "pgrep i3") 0)
       (string-to-number
-       (shell-command-to-string
-        (concat "i3-msg -t get_workspaces | "
-                "jq -r '.[] | select(.focused==true).name'")))
+       (if (not (executable-find "jq"))
+           (error "External command `jq' is missing")
+         (shell-command-to-string
+          (concat "i3-msg -t get_workspaces | "
+                  "jq -r '.[] | select(.focused==true).name'"))))
     (display-warning 'wallpaper "Cannot get current i3 workspace!")))
 
 (defun wallpaper-per-workspace-vdesk-get ()
```

**Comment by riscy** [comment]
Ultra minor, but having an empty line between your `^L` and `;;; Code:` header cause <kbd>M-x finder-commentary</kbd> to display the `^L` at the bottom:
image
You can fix this by removing the empty line between the `^L` and the `;;; Code:`.

Beyond that this is very neatly written. Welcome to MELPA!

**Pull request merged**
