### PR TITLE
Add railscasts-reloaded-theme

### PR DESCRIPTION
**Pull request by thegeorgeous**
### Brief summary of what the package does
The package is a port of Ryan Bates's famous [Railscasts theme](https://github.com/ryanb/dotfiles/blob/master/vim/colors/railscasts.vim)
[Please write an introduction of the package.]

### Direct link to the package repository

https://github.com/thegeorgeous/railscasts-reloaded-theme

### Your association with the package

[Are you the maintainer? have you contributed? do you just like the package a lot?]
I am the author and maintainer
### Relevant communications with the upstream package maintainer

[e.g., package.el compatibility changes that you have submitted. Write **None needed** if there is no problem.]
**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
What is different from https://github.com/mikenichols/railscasts-theme ?

**Comment by thegeorgeous** [comment]
@syohex, more colors, more supported modes and I plan to add more modes later on as well as support for customisations à la [zenburn](http://github.com/bbatsov/zenburn-emacs). Except for the basic syntax highlighting, most of the face-color mappings are a rewrite. The original theme IMHO provides a very primitive support

**Comment by syohex** [comment]
Is adding new package rather than improving(sending PR) [railscast-theme](https://github.com/mikenichols/railscasts-theme) code ?

**Comment by thegeorgeous** [comment]
@syohex, I did think of that, but this code has hardly anything in common with the [railscasts-theme](https://github.com/mikenichols/railscasts-theme) other than the colors used. This is more like a rewrite of the entire code.

**Comment by purcell** [comment]
Thanks, merged. You should remove the text "Emacs port" in the places it appears, since it's redundant in the context of an Emacs package, and adds no information. :-)

**Comment by thegeorgeous** [comment]
Thanks! will make the changes! 😃

**Pull request merged**
