### PR TITLE
Add navigel

### PR DESCRIPTION
**Pull request by DamienCassou**
### Brief summary of what the package does

Facilitate the creation of tabulated-list based UIs

### Direct link to the package repository

https://gitlab.petton.fr/DamienCassou/navigel/

### Your association with the package
I'm the author

### Relevant communications with the upstream package maintainer

none required

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by Silex** [comment]
Can you describe the differences with https://github.com/politza/tablist a little bit?

**Comment by DamienCassou** [comment]
> Can you describe the differences with https://github.com/politza/tablist a little bit?

@Silex: Thank you for the suggestion. I just [improved the README](https://gitlab.petton.fr/DamienCassou/navigel/commit/b25d96d1268e72cce7750fab22afbdabe0bb8fc8) a bit to clarify the difference. I copy/paste it here:

> This package depends on [[https://github.com/politza/tablist][tablist]] to get support for marking, deletion and more.  On top of the tablist package, navigel provides an easy way to specify the content of your tabulated lists: through entities specified with method overrides.  This makes it a breath to have tablist-based navigation within domain objects.

**Comment by Silex** [comment]
:+1: 

I already use `tablist` in docker.el, I might consider navigel :wink:

**Comment by DamienCassou** [comment]
Philippe Vaucher <notifications@github.com> writes:
> I already use `tablist` in docker.el, I might consider navigel :wink:

please don't hesitate to give feedback (being missing doc, missing
features, broken stuff…). It's in early stage of development even though
it is inspired by former packages I've created.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by tarsius** [comment]
Wouldn't it be better if `tablist` and `navigel` were merged into `tabulated-list` itself?

**Comment by DamienCassou** [comment]
Jonas Bernoulli <notifications@github.com> writes:
> Wouldn't it be better if `tablist` and `navigel` were merged into
> `tabulated-list` itself?

regarding tablist, I think it could be a good idea. I'm not sure for
navigel though because it heavily relies on CL methods for the public
API which is not really how Emacs code is usually structured. I think it
would be a bit alien for Emacs core.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by purcell** [comment]
Very nice, thanks - merged.

**Comment by tarsius** [comment]
@DamienCassou 

The recipe actually references the github repository not the repository from your gitea instance that you mentioned above. Is the former intended as a mirror of the later? The later is ahead of the former.

Melpa gets 19 of your packages from github while it gets `json-process-client` from https://gitea.petton.fr. What's up with that?

**Comment by DamienCassou** [comment]
Jonas Bernoulli <notifications@github.com> writes:
> The recipe actually references the github repository not the
> repository from your gitea instance that you mentioned above. Is the
> former intended as a mirror of the later?


The github repository is supposed to mirror the one on gitea. The goal
of referencing github from melpa instead of gitea is to reduce the
likelihood that the repository is down when melpa is building. Moreover,
when Nicolas Petton switched from GitLab to Gitea recently, I lost the
automatic synchronization of my repositories. I have to pay more
attention when I commit on gitea to also propagate the changes to Github.


> The later is ahead of the former.


This is fixed now.


> Melpa gets 19 of your packages from github while it gets
> `json-process-client` from https://gitea.petton.fr. What's up with
> that?


I should have pushed json-process-client to github, just like the
others. Sorry about that.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by tarsius** [comment]
Well, do you think it is more likely that petton.fr goes down than it is for you to forget to push to the mirror? :stuck_out_tongue_winking_eye:

But you don't actually have to remember to do so yourself anyway. Use this instead:

```
git remote set-url --push origin https://gitea.petton.fr/DamienCassou/navigel.git
git remote set-url --add --push origin git@github.com:DamienCassou/navigel.git
```

The first command is required even though this just duplicates the value of the fetch url.

**Comment by DamienCassou** [comment]
Jonas Bernoulli <notifications@github.com> writes:
> Well, do you think it is more likely that petton.fr goes down than it
> is for you to forget to push to the mirror?
> :stuck_out_tongue_winking_eye:


You have a point :-).


> But you don't actually have to remember to do so yourself anyway. Use
> this instead: […]


This is actually a very nice tip, thank you so much. I'm not sure it
will solve all my problems (e.g., when I merge a PR in gitea, master
will change there but not in github) but it will certainly help me quite
a bit. It's too bad I can't specify this in my ~/.emacs.d/.gitmodules
file.

Best,


-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Pull request merged**
