### PR TITLE
recipe for mu4e-goodies

### PR DESCRIPTION
**Pull request by panjie**
### Brief summary of what the package does

mu4e (mu for emacs)is a full-feature email client runs inside emacs. Here are some useful extensions/hacks of mu4e.

- Signature switch by rules
- Highlight the VIP's mails
- Check automatically if you forget to add your attachments
- Interaction with Lync/SkypeFB (in office)
- Much convenient way to manipulate tags
- Many useful hacks

### Direct link to the package repository

https://github.com/panjie/mu4e-goodies

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Are you sure you got everything on the checklist? :)

**Comment by panjie** [comment]
> Are you sure you got everything on the checklist? :)

Although some `checkdoc` issues remain, I thought I got everything on the checklist. But I am a newbie for this, If I ignored anything pls tell me. Thank you for the review.

**Comment by tarsius** [comment]
> If I ignored anything pls tell me.

You did ignore something and you can learn what it is by simply reading the list "again".

**Comment by panjie** [comment]
Please excuse my carelessness. I had checked and unchecked the last one.

**Comment by riscy** [comment]
From CONTRIBUTING.md:

> MELPA only looks at the main .el file (or -pkg.el file, if provided, though we discourage that). If you have different optional parts of a large package, each of which has different dependencies, then these should really be published as separate packages.

In your case, it looks like all of your dependencies are the same in all files (`Package-Requires: ((emacs "25.1"))`), but really only one file needs to have `Package-Requires` in it.

Ok, onto the checklist.  It seems you need to double-check the checklist.  With package-lint I see messages like these:
```
27:0: error: "mu4e-msgv-action-view-in-browser" doesn't start with package's prefix "mu4e-goodies-actions".
```
Note that as long as your functions/variables are prefixed with `mu4e-goodies`, that's fine, but this one (and others) aren't prefixed correctly.  I tried to remove those false positives where I could below:

### mu4e-goodies-actions.el
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
mu4e-goodies-actions.el:28: Argument `msg' should appear (as MSG) in the doc string
Warning (emacs): 
mu4e-goodies-actions.el:47: Argument `msg' should appear (as MSG) in the doc string
Warning (emacs): 
mu4e-goodies-actions.el:82: Lisp symbol `org-todo' should appear in quotes
Warning (emacs): 
mu4e-goodies-actions.el:91: First line is not a complete sentence
Warning (emacs): 
mu4e-goodies-actions.el:91: Argument `todop' should appear (as TODOP) in the doc string
Warning (emacs): 
mu4e-goodies-actions.el:123: Argument `istodo' should appear (as ISTODO) in the doc string
Warning (emacs): 
mu4e-goodies-actions.el:146: Argument `msg' should appear (as MSG) in the doc string
Warning (emacs): 
mu4e-goodies-actions.el:181: Argument `msg' should appear (as MSG) in the doc string
Warning (emacs): 
mu4e-goodies-actions.el:186: Argument `msg' should appear (as MSG) in the doc string
Warning (emacs): 
mu4e-goodies-actions.el:191: Argument `msg' should appear (as MSG) in the doc string
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
15 issues found:

16:0: error: Package should have a non-empty ;;; Commentary section.
27:0: error: "mu4e-msgv-action-view-in-browser" doesn't start with package's prefix "mu4e-goodies-actions".
46:0: error: "mu4e-msgv-action-sender-related-mails" doesn't start with package's prefix "mu4e-goodies-actions".
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
mu4e-goodies-actions.el:27:1:Warning: Unused lexical argument `msg'
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

### mu4e-goodies-hacks.el
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
mu4e-goodies-hacks.el:46: Argument `towin' should appear (as TOWIN) in the doc string
Warning (emacs): 
mu4e-goodies-hacks.el:46: Lisp symbol `mu4e-view' should appear in quotes
Warning (emacs): 
mu4e-goodies-hacks.el:79: Argument `orig-fun' should appear (as ORIG-FUN) in the doc string
Warning (emacs): 
mu4e-goodies-hacks.el:93: Argument `notsave' should appear (as NOTSAVE) in the doc string
Warning (emacs): 
mu4e-goodies-hacks.el:93: Lisp symbol `mu4e-bookmarks' should appear in quotes
Warning (emacs): 
mu4e-goodies-hacks.el:144: Keycode M-d embedded in doc string.  Use \\<keymap> & \\[function] instead
Warning (emacs): 
mu4e-goodies-hacks.el:143: Argument `orig-func' should appear (as ORIG-FUNC) in the doc string
Warning (emacs): 
mu4e-goodies-hacks.el:159: First line is not a complete sentence
Warning (emacs): 
mu4e-goodies-hacks.el:179: All interactive functions should have documentation
Warning (emacs): 
mu4e-goodies-hacks.el:204: First line is not a complete sentence
Warning (emacs): 
mu4e-goodies-hacks.el:204: Argument `msg' should appear (as MSG) in the doc string
Warning (emacs): 
mu4e-goodies-hacks.el:205: Lisp symbol `mu4e-shr2text' should appear in quotes
Warning (emacs): 
mu4e-goodies-hacks.el:227: First sentence should end with punctuation
Warning (emacs): 
mu4e-goodies-hacks.el:227: Argument `word' should appear (as WORD) in the doc string
Warning (emacs): 
mu4e-goodies-hacks.el:247: Argument `expr' should appear (as EXPR) in the doc string
Warning (emacs): 
mu4e-goodies-hacks.el:37: White space found at end of line
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
10 issues found:

78:0: error: "mml-attach-file--go-to-eob" doesn't start with package's prefix "mu4e-goodies-hacks".
158:0: error: "mu4e~fontify-signature" doesn't start with package's prefix "mu4e-goodies-hacks".
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
mu4e-goodies-hacks.el:203:1:Warning: Unused lexical argument `msg'
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other (from @riscy):
- mu4e-goodies-hacks.el#L71: This define-key could overwrite a user's keybindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- mu4e-goodies-hacks.el#L72: This define-key could overwrite a user's keybindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- mu4e-goodies-hacks.el#L109: This define-key could overwrite a user's keybindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- mu4e-goodies-hacks.el#L191: This define-key could overwrite a user's keybindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- mu4e-goodies-hacks.el#L192: This define-key could overwrite a user's keybindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- mu4e-goodies-hacks.el#L193: This define-key could overwrite a user's keybindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- mu4e-goodies-hacks.el#L76: Prefer `https` over `http` (if possible)

### mu4e-goodies-header-color.el
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
mu4e-goodies-header-color.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
mu4e-goodies-header-color.el:32: Argument `msg' should appear (as MSG) in the doc string
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
4 issues found:

1:0: error: Package should have a ;;; Commentary section.
1:0: warning: The package summary should start with an uppercase letter or a digit.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
mu4e-goodies-header-color.el:31:1:Warning: Unused lexical argument `width'
mu4e-goodies-header-color.el:31:1:Warning: Unused lexical argument `msg'
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

### mu4e-goodies-keyword-alert.el
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
mu4e-goodies-keyword-alert.el:62: First line is not a complete sentence
Warning (emacs): 
mu4e-goodies-keyword-alert.el:62: Argument `keyword' should appear (as KEYWORD) in the doc string
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

### mu4e-goodies-lync.el
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
mu4e-goodies-lync.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
mu4e-goodies-lync.el:22: Argument `emails' should appear (as EMAILS) in the doc string
Warning (emacs): 
mu4e-goodies-lync.el:49: White space found at end of line
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
2 issues found:

1:0: error: Package should have a ;;; Commentary section.
76:0: error: "mu4e-msgv-action-lync-with-all" doesn't start with package's prefix "mu4e-goodies-lync".
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other:
- mu4e-goodies-lync.el#L71: This define-key could overwrite a user's keybindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- mu4e-goodies-lync.el#L72: This define-key could overwrite a user's keybindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`

### mu4e-goodies-signature-switch.el
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
mu4e-goodies-signature-switch.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
mu4e-goodies-signature-switch.el:23: Some lines are over 80 columns wide
Warning (emacs): 
mu4e-goodies-signature-switch.el:37: First line is not a complete sentence
Warning (emacs): 
mu4e-goodies-signature-switch.el:37: Argument `signame' should appear (as SIGNAME) in the doc string
Warning (emacs): 
mu4e-goodies-signature-switch.el:73: First line is not a complete sentence
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
5 issues found:

1:0: error: Package should have a ;;; Commentary section.
22:0: error: "mu4e-goodies-signatures" doesn't start with package's prefix "mu4e-goodies-signature-switch".
36:0: error: "mu4e-goodies-switch-signature" doesn't start with package's prefix "mu4e-goodies-signature-switch".
72:0: error: "mu4e-goodies-switch-signature-by-rule" doesn't start with package's prefix "mu4e-goodies-signature-switch".
87:73: warning: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other:
- mu4e-goodies-signature-switch.el#L86: It is beneficial to sharp-quote hooks; use `#'`
- mu4e-goodies-signature-switch.el#L87: This define-key could overwrite a user's keybindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`


### mu4e-goodies-tags.el
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
mu4e-goodies-tags.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
mu4e-goodies-tags.el:77: Argument `msg' should appear (as MSG) in the doc string
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
4 issues found:

1:0: error: Package should have a ;;; Commentary section.
47:0: error: "mu4e-goodies~quick-tag" doesn't start with package's prefix "mu4e-goodies-tags".
50:0: error: "mu4e-goodies-add-del-quick-tag" doesn't start with package's prefix "mu4e-goodies-tags".
76:0: error: "mu4e-goodies-headers-add-tags-to-subject" doesn't start with package's prefix "mu4e-goodies-tags".
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
mu4e-goodies-tags.el:76:1:Warning: Unused lexical argument `width'
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other:
- mu4e-goodies-tags.el#L127: It's safer to sharp-quote function names; use `#'`
- mu4e-goodies-tags.el#L35: This define-key could overwrite a user's keybindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- mu4e-goodies-tags.el#L36: This define-key could overwrite a user's keybindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`


### mu4e-goodies-utils.el
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
mu4e-goodies-utils.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
mu4e-goodies-utils.el:25: First line is not a complete sentence
Warning (emacs): 
mu4e-goodies-utils.el:25: Argument `addr' should appear (as ADDR) in the doc string
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
2 issues found:

1:0: error: Package should have a ;;; Commentary section.
24:0: error: "mu4e-goodies~get-real-addr" doesn't start with package's prefix "mu4e-goodies-utils".
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉


### mu4e-goodies.el
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
No issues found.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

**Comment by tarsius** [comment]
Friendly ping!

**Pull request closed without merging**
