### PR TITLE
Add recipe for haki-theme

### PR DESCRIPTION
**Pull request by idlip**
A dark theme for emacs

### Brief summary of what the package does

haki is an pleasant, dark theme for emacs.
Inspired by modus-vivendi, I have tailored it for some modern ui like.

### Direct link to the package repository

https://github.com/idlip/haki

### Your association with the package

I'm the author of the package/theme

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [] My elisp byte-compiles cleanly
- [] I've used `M-x checkdoc` to check the package's documentation strings
- [] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

Actually there is an error.
I have added a function here [haki-modal-mode-line](https://github.com/idlip/haki/blob/26588e05a4668d98cae1e99e9f36db2e6dae38c5/haki-theme.el#L207) which changes mode-line border according to meow/evil state.

But i get these [errors](http://dpaste.com/CAM2XQGHP) with flycheck, Im not sure what will be the easy way to fix this.
Ik i can use `(declare-function meow-insert-state-p "ext:meow")
` but im not sure if its the best way to use it for all 12 functions..

I'm still a novice in emacs-lisp (that is why i have only did theme)
Please let me know what is the better way for this.

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.   You seem to be combining a theme with a mode line implementation, and those should probably be two separate packages.  Here's a quick first pass of the checklist --

`haki-theme.el` with byte-compile using Emacs 28.1:
```
haki-theme.el:224:10: Warning: the function `evil-replace-state-p' is not
    known to be defined.
haki-theme.el:223:10: Warning: the function `evil-emacs-state-p' is not known
    to be defined.
haki-theme.el:222:10: Warning: the function `evil-operator-state-p' is not
    known to be defined.
haki-theme.el:221:10: Warning: the function `evil-motion-state-p' is not known
    to be defined.
haki-theme.el:220:10: Warning: the function `evil-normal-state-p' is not known
    to be defined.
haki-theme.el:219:10: Warning: the function `evil-insert-state-p' is not known
    to be defined.
haki-theme.el:218:10: Warning: the function `evil-visual-state-p' is not known
    to be defined.
haki-theme.el:215:10: Warning: the function `meow-keypad-mode-p' is not known
    to be defined.
haki-theme.el:214:10: Warning: the function `meow-motion-mode-p' is not known
    to be defined.
haki-theme.el:213:10: Warning: the function `meow-normal-mode-p' is not known
    to be defined.
haki-theme.el:212:10: Warning: the function `meow-insert-mode-p' is not known
    to be defined.
haki-theme.el:211:10: Warning: the function `meow-beacon-mode-p' is not known
    to be defined.
```
These dependencies need to be in your `Package-Requires`^

`haki-theme.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- haki-theme.el#L83: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
```

Package and license:
- Avoid specifying `:branch` except in unusual cases; MELPA prefers the default branch
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to haki-theme.el

**Comment by idlip** [comment]
Hey @riscy , thank you for taking a look.

> `haki-theme.el` with byte-compile using Emacs 28.1:

I just added an function optionally to change mode-line border color according to evil/meow states (modal editing)
The package (theme) does not run this, it is just defined. If user has installed the packages, they can add it to a hook.

So I have made it as optional function.
So i wanted to know, how can i require or make `meow` and `evil` as optional dependency only if user has it installed?

> Avoid specifying `:branch` except in unusual cases; MELPA prefers the default branch
I will remove that and force push.

> Add formal license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to haki-theme.el

Sorry, I dont get what you mean.
The license I have is genuine gpl3 officially, right?
Shouldn't i use that?

> - haki-theme.el#L83: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`

About this, I have tried to remove as much indents and used spaces instead, but some may have been left off. Should i manually remove those indents?

**Comment by riscy** [comment]
> So i wanted to know, how can i require or make meow and evil as optional dependency only if user has it installed?

To achieve a clean byte-compile with significant optional dependencies like this, check out `declare-function` -- you'll have to do bookkeeping to make sure that you've got a `declare-function` for each of the optional functions you're making use of. (I am assuming you will instruct users to put a hook in their config to run `haki-modal-mode-line` -- otherwise I don't think this will have any effect as-is).


> Sorry, I dont get what you mean. The license I have is genuine gpl3 officially, right? Shouldn't i use that?

Apologies, my automation failed to pick up the license.  This is because you're using nonstandard phrasing: "Haki theme is free package: you can redistribute it...".  Use the Standard License Header described at the bottom of https://spdx.org/licenses/GPL-3.0-or-later.html and your file's license will more easily be machine-detectable.  Or use an [SPDX-License-Identifier](https://spdx.dev/ids/).

**Comment by idlip** [comment]
Thanks a lot for corrections, I have made the changes. And the package build with no error on my end.
Hopefully it can be merged!

**Comment by riscy** [comment]
Thanks for this.  I think we can merge, but I think the summary line: "Elegant, dark theme" and your README heading "A pleasant, modern theme" don't tell users too much about this theme.

I think a huge keyword for you is "high-contrast", so even adjusting your summary line (and README) to say "An elegant, high-contrast, dark theme" would massively improve discoverability.  (Truly elegance is in the eye of the beholder, but I digress.)

And welcome to MELPA. :)

**Comment by idlip** [comment]
Oh yes, will fix it.
My brain was thinking of some eye candy word that time.

Thank you for taking care of my package!

**Comment by tarsius** [comment]
Please add a package summary (on the first line).

You can base it on the package description, i.e., "An elegant, high-contrast dark-theme in modern sense."

"A ... dark-theme" is a bit weird though. There is no such thing as a "dark-theme". There are dark themes and there are light themes, but they are still all just *themes*. (This is different from *minor-modes* and *major-modes*, which are very different things; despite all the similarities, that lead to the term "mode" being used in both cases.)

**Comment by tarsius** [comment]
Ah... @riscy already pointed out that a summary is needed.

**Comment by idlip** [comment]
Ah, i had removed it thinking it would cross more than 80 column.

Added the summary back. 

Thanks again for pointing it out!

**Comment by riscy** [comment]
Looks good on my end - thank you @idlip!

**Pull request merged**
