### PR TITLE
elysium

### PR DESCRIPTION
**Pull request by lanceberge**
### Brief summary of what the package does

Automatically apply LLM-generated code suggestions to your code buffer using `gptel` as the backend. The code changes can then be merged in using `smerge-mode`.

### Direct link to the package repository

https://github.com/lanceberge/elysium

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None Needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this. Do you know how this differs from https://github.com/emacsmirror/copilot and any other similar packages?  There are a growing number of packages in this space, and I want to make sure there isn't any overlap, when contributors could be joining forces. :)

Very minor nag - gptel-copilot.el#L186: No `format` required; `message` takes an f-string

**Comment by lanceberge** [comment]
Hey, thanks for the feedback! I just pushed the fix for 186.

It looks like that copilot package uses exclusively GitHub Copilot as an LLM. It looks like that package doesn't enable code suggestions that the user prompts.

`gptel-copilot` uses `gptel` as a backend, which can work with OpenAI, Anthropic, and many more LLM backends. It also allows the user to prompt the changes they want, and to apply them in the form of a git-merge, which means we can more easily save and discard hunks of changes.

**Comment by meain** [comment]
@lanceberge Just curios. How does it differ from how https://github.com/karthink/gptel/blob/master/gptel-rewrite.el works?

**Comment by riscy** [comment]
Thank you @meain for chiming in with that.  I think it's worth tagging @karthink here.  There's a proliferation of codegen packages right now - it's difficult for me to keep up with, and inevitably there is going to be some overlap.

If there *is* overlap in this case, maybe it's possible for these two authors to exchange ideas.

**Comment by karthink** [comment]
> EDIT: Just realized gptel-rewrite was just added yesterday 😆

@meain This feature has existed in gptel since the beginning, I just changed the UI a bit and moved the feature into a separate file last week.

>  There's a proliferation of codegen packages right now - it's difficult for me to keep up with, and inevitably there is going to be some overlap.

@riscy The features provided by the packages all overlap to varying extents, but the user interfaces are all different.  This is expected since people are experimenting with different UIs, and getting LLM completions is simple, it just involves making http requests.  I also think this experimentation should be encouraged, because no one knows yet what the best ways to integrate LLMs with Emacs are.  What works best for "the mainstream" (VSCode-style UIs) doesn't necessarily work best for us.

As for gptel, it's essentially two things in one:

1.  A minimal but flexible UI (`gptel` and `gptel-menu`) that can handle a variety of ad-hoc tasks, but is not particularly suited for specialized ones like context-aware code generation, like Elysium is.
2.  An API (`gptel-request`) to abstract away the http requests/response parsing and other plumbing so folks can build custom workflows on top.

Right now this API is used by a small handful of packages.  If it gets many more consumers, I can separate out `gptel-request` into its own minimal package that can serve as a backend for different UIs like Elysium and [Evedel](https://github.com/daedsidog/evedel).  That way they don't have to pollute the session with gptel's (unused) UI code.  `gptel` will depend on it too, of course.

I don't have a strong opinion on what should and shouldn't be on MELPA, I trust your judgment there. However, here is an incomplete map of this space, this might help you orient yourself.

llm-clients-2024

**Comment by lanceberge** [comment]
@karthink Thank you for this! `gptel` is excellent. I'm happy to contribute any of the functionality of `elysium` to `gptel` if people think that that's the best way to contribute this functionality to Emacs. Splitting `gptel-request` out to a separate package sounds like a great idea! I'm planning on experimenting with `gptel-rewrite` next

**Comment by riscy** [comment]
Thanks everyone for the thoughtful comments - I'll merge this!

**Pull request merged**
