### PR TITLE
Added recipe for tpl-dumper

### PR DESCRIPTION
**Pull request by natelastname**
### Brief summary of what the package does

Create files from yas-snippet templates

### Direct link to the package repository

https://github.com/natelastname/tpl-dumper

### Your association with the package

Sole author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`tpl-dumper.el` with byte-compile using Emacs 29.3:
```
tpl-dumper.el:41:11: Warning: `(dummy-prompt (prompt choices &optional display-fn) (declare (ignore prompt)) (or (find name choices :key display-fn :test #'string=) (throw 'notfound nil)))' is a malformed function
tpl-dumper.el:39:39: Warning: Unused lexical argument `name'
tpl-dumper.el:46:12: Warning: Unused lexical variable `yas-prompt-functions'
In end of data:
tpl-dumper.el:48:10: Warning: the function `yas-insert-snippet' is not known to be defined.
tpl-dumper.el:41:4: Warning: the function `flet' is not known to be defined.
```

`tpl-dumper.el` with package-lint 20240330.1458:
```
2 issues found:
6:38: warning: Use a properly versioned dependency on "yasnippet" if possible.
9:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```
Re: yasnippet, check https://stable.melpa.org/#/yasnippet for a version number.

**Comment by natelastname** [comment]
> Thanks for this. Quick first pass --
> 
> `tpl-dumper.el` with byte-compile using Emacs 29.3:
> 
> ```
> tpl-dumper.el:41:11: Warning: `(dummy-prompt (prompt choices &optional display-fn) (declare (ignore prompt)) (or (find name choices :key display-fn :test #'string=) (throw 'notfound nil)))' is a malformed function
> tpl-dumper.el:39:39: Warning: Unused lexical argument `name'
> tpl-dumper.el:46:12: Warning: Unused lexical variable `yas-prompt-functions'
> In end of data:
> tpl-dumper.el:48:10: Warning: the function `yas-insert-snippet' is not known to be defined.
> tpl-dumper.el:41:4: Warning: the function `flet' is not known to be defined.
> ```
> 
> `tpl-dumper.el` with package-lint 20240330.1458:
> 
> ```
> 2 issues found:
> 6:38: warning: Use a properly versioned dependency on "yasnippet" if possible.
> 9:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
> ```
> 
> Re: yasnippet, check https://stable.melpa.org/#/yasnippet for a version number.

Thank for the feedback, I made changes that should address these issues. Please let me know if you need anything else.

**Comment by natelastname** [comment]
Actually, hold on, I just realized I forgot to address the byte compile errors.

**Comment by riscy** [comment]
No problem - I can provide them here for reference --

`tpl-dumper.el` with byte-compile using Emacs 29.3:
```
tpl-dumper.el:41:14: Warning: Package cl is deprecated
tpl-dumper.el:41:14: Warning: `(dummy-prompt (prompt choices &optional display-fn) (declare (ignore prompt)) (or (find name choices :key display-fn :test #'string=) (throw 'notfound nil)))' is a malformed function
tpl-dumper.el:39:39: Warning: Unused lexical argument `name'
tpl-dumper.el:46:12: Warning: Unused lexical variable `yas-prompt-functions'
In end of data:
tpl-dumper.el:114:28: Warning: the function `f-dirname' is not known to be defined.
tpl-dumper.el:105:8: Warning: the function `f-exists-p' is not known to be defined.
tpl-dumper.el:98:6: Warning: the function `f-write-text' is not known to be defined.
tpl-dumper.el:95:13: Warning: the function `yas-minor-mode' is not known to be defined.
tpl-dumper.el:70:18: Warning: the function `f-join' is not known to be defined.
tpl-dumper.el:48:10: Warning: the function `yas-insert-snippet' is not known to be defined.
```
Some of these clear up if you `(require 'cl-lib)` (and not `(require 'cl)`)

`tpl-dumper.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- tpl-dumper.el#L209: Use `(temporary-file-directory)` instead of /tmp in code
- tpl-dumper.el#L106: No `format` required; `message` takes an f-string
- tpl-dumper.el#L110: No `format` required; `message` takes an f-string
```
The `tmp` nag above looks like it may be due to some test code that might disappear when you're finished?

**Comment by natelastname** [comment]
Ok, I am pretty sure this passes the checks now. Thanks for the feedback and please let me know if you have any questions.

**Comment by natelastname** [comment]
Also forgot to mention that I made a fairly substitute update the package

**Comment by natelastname** [comment]
Actually I'm observing bugs when I use "cl-flet" instead of "flet". Currently working on a solution that doesn't introduce errors (because using flet instead of cl-flet produces package-lint warnings.)

**Comment by riscy** [comment]
Thanks for the update!  Let me know when it's ready to go, or if there's possibly something I can help with.

**Comment by natelastname** [comment]
Any tips for how to replace flet with cl-letf would be helpful. I can't figure out how to get rid of this function.

The main value-add of this package in the first place is that it handles the contrived work-around required to do something that should be an easy task (i.e., inserting a yasnippet template non-interactively). This contrived work-around involves using an obsolete function, which is why resolving this warning is hard.

**Comment by tarsius** [comment]
> Any tips for how to replace flet with cl-letf would be helpful.

Use a `lambda` instead. There's no need to name the function here, since it gets called by virtue of being a member of a hook.


```elisp
(defun tpl-dumper-insert-yas-by-name (name)
  "Insert Yas-snippet NAME at point."
  (catch 'notfound
    (let ((yas-prompt-functions
           (list (lambda (_prompt choices &optional display-fn)
                   (or (find name choices :key display-fn :test #'string=)
                       (throw 'notfound nil))))))
      (yas-insert-snippet t))))
```

And you can prefix a symbol name with `_` to keep the byte-compiler from complaining about it being unused.

The use of `throw`+`catch` seems questionable. Wouldn't it be better to show a `user-error`, instead of silently aborting?

Using `cl-letf` would look like this:

```elisp
(cl-flet (((symbol-function 'dummy-prompt)
           (lambda ...))) ...)
```

**Comment by natelastname** [comment]
Thank you @tarsius , this is super helpful. Can verify that your implementation works.

I wouldn't doubt that the use of throw+catch is misguided here, I'll take another hard look at it.

**Comment by natelastname** [comment]
I implemented / pushed changes that should clear `package-lint` and `byte-compile` warnings.

Thank and please let me know if you need any additional info

**Comment by riscy** [comment]
Thank you!  Can you confirm you pushed the latest to your default branch?  I see the same issues as before --

`tpl-dumper.el` with byte-compile using Emacs 29.3:
```
tpl-dumper.el:42:12: Warning: Package cl is deprecated
tpl-dumper.el:42:12: Warning: Unused lexical variable `yas-prompt-functions'
In end of data:
tpl-dumper.el:108:28: Warning: the function `f-dirname' is not known to be defined.
tpl-dumper.el:99:8: Warning: the function `f-exists-p' is not known to be defined.
tpl-dumper.el:92:6: Warning: the function `f-write-text' is not known to be defined.
tpl-dumper.el:89:13: Warning: the function `yas-minor-mode' is not known to be defined.
tpl-dumper.el:64:18: Warning: the function `f-join' is not known to be defined.
tpl-dumper.el:46:8: Warning: the function `yas-insert-snippet' is not known to be defined.
```

`tpl-dumper.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- tpl-dumper.el#L206: Use `(temporary-file-directory)` instead of /tmp in code
- tpl-dumper.el#L100: No `format` required; `message` takes an f-string
- tpl-dumper.el#L104: No `format` required; `message` takes an f-string
```

**Comment by natelastname** [comment]
I see what went wrong here, I started using melpazoid so this shouldn't arise again. 

I'm now seeing
```
tpl-dumper.el:42:12: Warning: Unused lexical variable `yas-prompt-functions'
In end of data:
tpl-dumper.el:108:28: Warning: the function `f-dirname' is not known to be defined.
tpl-dumper.el:99:8: Warning: the function `f-exists-p' is not known to be defined.
tpl-dumper.el:92:6: Warning: the function `f-write-text' is not known to be defined.
tpl-dumper.el:89:13: Warning: the function `yas-minor-mode' is not known to be defined.
tpl-dumper.el:64:18: Warning: the function `f-join' is not known to be defined.
tpl-dumper.el:46:8: Warning: the function `yas-insert-snippet' is not known to be defined.

```
All of these warnings are caused by functions that are imported in the package header:
```
;; Package-Requires: ((emacs "28.1") (cl-lib "0.7.1") (yasnippet "0.14.0") (f "0.20.0"))
```

Any tips for how to resolve these warnings?

**Comment by tarsius** [comment]
> All of these warnings are caused by functions that are imported in the package header:

The package header is only used by the package manager (and related tooling), but doesn't actually cause any libraries to be loaded. For that you need `(require 'f)` and others.

**Comment by natelastname** [comment]
> > All of these warnings are caused by functions that are imported in the package header:
> 
> The package header is only used by the package manager (and related tooling), but doesn't actually cause any libraries to be loaded. For that you need `(require 'f)` and others.

Ok, makes sense

Just pushed some changes and the melpazoid action is clean. Thank you for the help so far and please let me know if there's anything else

**Comment by riscy** [comment]
Thank you - the checklist is behind us now.  I'm taking a deeper look now and trying to understand the purpose of this package.  I think what you're doing is cool, but the summaries of it that people will see might not coax them into using it.

First, the name `tpl-dumper` feels to me like it could benefit from being unpacked into `template-dumper`.  You also write "...from yas-snippet templates" in your summary line, but these are usually written "yasnippet", correct?  I think you want to make sure you get that right because that's an important searchable keyword for your package.

Next, I think this Package needs a better Commentary.  "Create files with yasnippet templates" seems like it could cause confusion, because isn't that exactly what yasnippet is for?  Maybe you "Create a project directory tree comprised of template files"?  And if that's the case, maybe this is more of a `project-templater` than a `template-dumper`.  Your README potentially has a better summary: "enables [creating?] a directory of files that are each initialized from a named Yasnippet template."

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by natelastname** [comment]
I agree, and I'm planning to make these changes as soon as I get a chance, sorry for the delayed response.

**Comment by natelastname** [comment]
Just got around to this,
- Fixed spelling of yasnippet in summary line
- Changed the name of the package from `tpl-dumper` to `template-dumper`
- Updated melpa recipe

**Comment by riscy** [comment]
Thank you - any thoughts on the `;;; Commentary`?  Quoting from earlier,

> "Create files with yasnippet templates" seems like it could cause confusion, because isn't that exactly what yasnippet is for? Maybe you "Create a project directory tree comprised of template files"? ...  Your README potentially has a better summary: "enables [creating?] a directory of files that are each initialized from a named Yasnippet template."

**Comment by natelastname** [comment]
> Thank you - any thoughts on the `;;; Commentary`?  Quoting from earlier,
> 
> > "Create files with yasnippet templates" seems like it could cause confusion, because isn't that exactly what yasnippet is for? Maybe you "Create a project directory tree comprised of template files"? ...  Your README potentially has a better summary: "enables [creating?] a directory of files that are each initialized from a named Yasnippet template."
> 
> 

You would think that "creating files from yasnippet snippets" is what yasnippet already does, but it's not. Yasnippet is more about inserting templates into existing files. 

Creating new files from snippets non-interactively is surprisingly hard to do in yasnippet. It requires understanding the internal data structures of yasnippet and some rather advanced elisp techniques (as we saw before.) 

This single pain point is why I originally created this package. I added the project template directory tree thing much later.

**Comment by riscy** [comment]
> You would think that "creating files from yasnippet snippets" is what yasnippet already does, but it's not. Yasnippet is more about inserting templates into existing files.

I understand what you're saying (and I think you probably understand what I'm saying) - it's not an easy distinction to express in a few words.  I still worry "Create files from yasnippet templates" may cause people to gloss over your package, but I don't see any blockers.

**Comment by natelastname** [comment]
> > You would think that "creating files from yasnippet snippets" is what yasnippet already does, but it's not. Yasnippet is more about inserting templates into existing files.
> 
> I understand what you're saying (and I think you probably understand what I'm saying) - it's not an easy distinction to express in a few words. I still worry "Create files from yasnippet templates" may cause people to gloss over your package, but I don't see any blockers.

Yes, I do see what you're saying and I think your concern is valid.

Thanks for working with  me to get this merged!

**Pull request merged**
