### PR TITLE
Update Jade's recipe to include texinfo documentation

### PR DESCRIPTION
**Pull request by NicolasPetton**
### Brief summary of what the package does

A JavaScript development environment for Emacs.

### Direct link to the package repository

https://github.com/NicolasPetton/jade

### Your association with the package

I'm the author of the package.

### Relevant communications with the upstream package maintainer

The recipe is already in MELPA, this updates it so include Jade's documentation.

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ ] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
I'd suggest you just put your texi files directly in the "doc" subdir and we'll include them automatically. It's better if authors use consistent repo structures than to have lots of tweaked recipes.

**Comment by NicolasPetton** [comment]
@purcell I use Sphinx to build the documentation (and export to texinfo), which is why the folder structure is a bit different.

**Comment by NicolasPetton** [comment]
@purcell I moved the Sphinx documentation so that Jade's texinfo files are in the doc directory. Thanks for your suggestion.

**Comment by purcell** [comment]
Nice - thanks for this!

**Pull request closed without merging**
