### PR TITLE
Add helix-theme recipe

### PR DESCRIPTION
**Pull request by ibakepunk**
### Brief summary of what the package does

This is a color theme inspired by default colors in Helix editor.

### Direct link to the package repository

https://github.com/ibakepunk/helix-theme

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`helix-theme.el` with package-lint 20240507.1722:
```
3 issues found:
1:0: error: package.el cannot parse this buffer: Search failed: ";;; helix-theme.el ends here"
1:106: warning: You should depend on (emacs "24.1") if you need lexical-binding.
7:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```

If you solve the first package-lint issue you will see the following:
`helix-theme.el` with package-lint 20240507.1722:
```
5 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
1:0: warning: The package summary is too long. It should be at most 60 characters.
1:0: warning: The package summary should not end with a period.
1:106: warning: You should depend on (emacs "24.1") if you need lexical-binding.
7:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```

**Comment by ibakepunk** [comment]
Oops, sorry about that, somehow I missed it, I'll fix it and get back to you.

**Comment by ibakepunk** [comment]
@riscy thanks for your feedback. I updated my repo to remove the errors.

**Comment by riscy** [comment]
Thank you.  Just minor stuff now -

- As above, Including "Emacs" in the package summary is usually redundant.  (I notice Package-Lint isn't reporting this in the latest code, but that is still relevant)
- If you wanted to keep the `Keywords` listing, you'd only have to add a "faces" keyword (per `finder-known-keywords`)
- Unless you're using some kind of literal code generator and can't avoid it, I'd just nix the single-line comment that says ";; End:" - the last line of the file tells everything (";;; helix-theme.el ends here").

**Comment by ibakepunk** [comment]
@riscy I believe it's OK to remove the Emacs 24.1 requirement and let the `package-lint` report ` warning: You should depend on (emacs "24.1") if you need lexical-binding.`, right?

**Comment by riscy** [comment]
If your code depends on lexical binding, you should continue to depend on Emacs 24.1 - if you know your code doesn't depend on lexical binding, you could just remove `-*- lexical-binding: t; -*-` from your summary line.

(On the topic of your summary line, I notice it still says "Emacs color theme" but ought to just say "Color theme...")

**Comment by ibakepunk** [comment]
Thanks, I don't think I **need** lexical binding. So I updated my package according to your comments.

**Comment by riscy** [comment]
Thank you!  Merging this.

**Pull request merged**
