### PR TITLE
Add quiz.el

### PR DESCRIPTION
**Pull request by davep**
### Brief summary of what the package does

A simple trivia quiz game that uses [The Open Trivia Database](https://opentdb.com/) as the back end.

### Direct link to the package repository

https://github.com/davep/quiz.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, this is fun. You should use `define-derived-mode` rather than rolling your own major mode function: that way you can extend `special-mode` (which gives you the `q` behaviour for free) and skip the boiler plate in your hand-rolled version.

**Comment by davep** [comment]
Thanks. I'll take a look at that. I've got a few packages that might
benefit from that.

**Comment by davep** [comment]
Now done.

Amusingly I've actually used this approach in much older code of mine, and seem to have forgotten about it. (including `quickurl` and `5x5` which are part of Emacs itself!)

**Comment by purcell** [comment]
:-)  Merged now, thanks!

**Pull request merged**
