### PR TITLE
Added sign recipes

### PR DESCRIPTION
**Pull request by mola-T**
[https://github.com/mola-T/sign](https://github.com/mola-T/sign)

I am the author.

The package is to provide hook like features.
It can achieve something like hook with arguments and and delayed hook call.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. The name is quite confusing, I'd say: "sign" is not a natural abbreviation of "signal", so I think the package should be called "signal". Also, please provide some information in the `Commentary` section rather than simply referring people to the github page -- the `Commentary` text appears on the MELPA package package, and also in the `M-x list-packages` menu when a user presses `?`. Few people will discover this package if it isn't clearly described. :-)

**Comment by mola-T** [comment]
Thanks for you advice, I added `commentary`.

For the package name, I can say that I use signal originally. However, `signal` itself is `Emacs` built-in function. During developing the package, I find that there will be `font-lock` conflict. Moreover, I am afraid people will be confused with the `Emacs` built-in `signal` which is related to `error`

**Comment by mola-T** [comment]
Any response?

**Comment by purcell** [comment]
How about "signals", then? That would be clearer. Then you'd have `defsignal`, `signals-connect`, `signals-disconnect` etc. Also, `emitB` would be `signals-emitb`.

**Comment by mola-T** [comment]
I think "signal" is better than "signals" XD
I will make a new pull request. You can close this one.

**Comment by purcell** [comment]
But signal

**Pull request closed without merging**
