### PR TITLE
add recipe for ninrod/evil-replace-with-char

### PR DESCRIPTION
**Pull request by ninrod**
### Brief summary of what the package does

This package provides an evil operator, =zx= to replace all chars of a text object with a char.

### Direct link to the package repository

https://github.com/ninrod/evil-replace-with-char

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by tarsius** [comment]
The build error is due to an unrelated change, which is fixed now. Please rebase your commit so that the tests can be run for your change. If you use Magit you can do so using <kbd>f u</kbd> to fetch, <kbd>r u</kbd> to rebase, and <kbd>P - f p</kbd> to force push.

**Comment by ninrod** [comment]
@tarsius, thanks! I've implemented the rebase.

**Comment by tarsius** [comment]
Turns out the issue still isn't fixed... I'll keep you posted.

**Comment by ninrod** [comment]
hum... seems that the error persists. here's the output of `make recipes/replace-with-char`:

```sh
melpa $ make recipes/replace-with-char
 • Building recipe replace-with-char ...
/usr/bin/timeout -k 60 600 emacs --no-site-file --batch -L package-build -l package-build --eval "(let ((package-build-stable nil) (package-bu
ild-write-melpa-badge-images t) (package-build-archive-dir (expand-file-name \"./packages\" package-build--melpa-base))) (package-build-archiv
e 'replace-with-char))"                                                                                                                      
Cannot open load file: É um diretório, /home/ninrod/code/emacs/melpa/package-build
make: [Makefile:92: recipes/replace-with-char] Error 255 (ignored)
ls: não foi possível acessar './packages/replace-with-char-*': Arquivo ou diretório não encontrado
 ✓ Wrote  
 Sleeping for 0 ...
sleep 0

melpa $ 
```sh

**Comment by ninrod** [comment]
Hi @tarsius, the tests seem to be running now. Is there anything else I can do?

**Comment by tarsius** [comment]
I only occasionally review submitted recipes and their packages. I am not currently in the mood to do it now.

**Comment by purcell** [comment]
Thanks for this. Quick feedback:
- The custom group is [apparently its own child](https://github.com/ninrod/replace-with-char/blob/dbe4516fc23a93b501e02d51d893d3747e489ba9/replace-with-char.el#L46) :-/
- Call this package `evil-replace-with-char`, please. There's no indication otherwise that this is for Evil users.
- The customisation isn't going to work, because if someone sets the key after this package has been loaded, it will never take effect. Customisable keymaps are the only reliable and consistently-unsurprising way to allow users to customise keys. Instead, just tell users to `(define-key evil-normal-state-map "zx" 'evil-operator-replace-with-char)`.
- I expect that `evil-define-operator` supports autoloading, so you might want to add an `;;;###autoload` marker comment for the definition.

**Comment by ninrod** [comment]
Hey thanks for the tips @purcell! You're absolutelly right. I'll implement those.

**Comment by ninrod** [comment]
@purcell, I've implemented all your recommendations. ❤️

**Comment by purcell** [comment]
Great - thanks for your patience! Merged now.

**Pull request merged**
