### PR TITLE
Add hacker-typer recipe

### PR DESCRIPTION
**Pull request by therockmandolinist**
### Brief summary of what the package does

For amusement, implements a customizable version of http://hackertyper.com in emacs.

### Direct link to the package repository

https://github.com/therockmandolinist/emacs-hacker-typer

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### Note

This is my first package and I consider myself fairly new to emacs-lisp, I understand (and bear with me) if it's riddled with errors or terrible ways of doing things.

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR with small fix. https://github.com/therockmandolinist/emacs-hacker-typer/pull/1

**Comment by therockmandolinist** [comment]
Merged, thanks!

I'm not sure if this is the right place to ask, but I have one question/hesitation about my package. One of the functions sets `inhibit-redisplay` to `t` while it opens a file and removes comments from it. Is it possible that this isn't the recommended way to do this and I should call an async process to do this externally instead? In case there's user input during the process leading to unexpected issues, or something like that.

**Comment by syohex** [comment]
[note] `file-name-case-insensitive-p` is very newer API. It is implemented only in development Emacs, in other word stable Emacs users cannot use it.

**Comment by therockmandolinist** [comment]
Thanks for the heads up. I took that directly from the code for set-auto-mode. I've updated it to just include the try for case-sensitive and fallback to case-insensitive without using `file-name-case-insensitive-p`.

**Comment by purcell** [comment]
Thanks. `hacker-typer for emacs` isn't a great package description: can you find something better please? "for emacs" is redundant, and the description doesn't tell a potential user what the package actually does.

**Comment by therockmandolinist** [comment]
@purcell that's a fair point. how specific/technical does it have to be? how about something like: "Pretend to write code like a pro"

**Comment by purcell** [comment]
I like it!

**Comment by therockmandolinist** [comment]
@purcell thanks for the feedback, I've committed the changes. 

Also, a question for future reference: if a later version of the package requires async, for example - would I just add the appropriate info to the `;; Package Requires` line?

**Comment by purcell** [comment]
> Also, a question for future reference: if a later version of the package requires async, for example - would I just add the appropriate info to the ;; Package Requires line?

Yes, exactly. Merging now - thanks!

**Pull request merged**
