### PR TITLE
Add stripes

### PR DESCRIPTION
**Pull request by stepnem**
### Brief summary of what the package does

Highlight every other `stripes-unit' (3 by default) lines with an
alternative background color or font. Useful for buffers that display
lists of any kind, as a guide for your eyes to follow these lines.

### Direct link to the package repository

https://gitlab.com/stepnem/stripes-el

### Your association with the package

I am the maintainer and coauthor.

### Relevant communications with the upstream package maintainer

Originally I found the old version at https://www.emacswiki.org/emacs/stripes.el

Based on communication and agreement with Michael Schierl, the
original author, I have taken over the maintenance. He has also given
me permission to release it into the public domain.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback

[with the exception of "1:0: warning: The package summary should start with an uppercase letter or a digit.", cf. purcell/package-lint#162]

- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Looks very nice.  Quick first pass.

### stripes.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200226.2001):
```
1 issue found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
```
I see the issue you've raised, but please capitalize the line.

### License ###

- Please add a LICENSE or COPYING file to the repository
- stripes.el has no detectable license text ("public domain" is probably too informal -- what about [CC0](https://www.gnu.org/licenses/license-list.en.html#CC0) or the Unlicense?)

- Use a GPL-compatible license.
  See: https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

**Comment by alphapapa** [comment]
Cool, I was just thinking about a feature like this a little while ago and wondered if anyone had made something like this.

Curious, though: I see that it removes and creates overlays for the whole buffer every time a change is made to its contents.  How is performance?

**Comment by stepnem** [comment]
> Curious, though: I see that it removes and creates overlays for the whole buffer every time a change is made to its contents.  How is performance?

I know, right? :-D

I have been wondering the same, and even did some experiments with both
jit-lock and using pre-redisplay-functions instead (similar to what
region updating code does), but neither seemed better (or maybe I just
don't know how to do it right), quite the opposite, I was getting
noticeable redisplay lags (kind of what one sees with font-locking
updates in largeish buffers), whereas with the current seemingly
outrageous solution I haven't noticed any issues (even e.g. in rapidly
changing helm completion buffers, which I thought could be a problem).

I'm certainly interested in any feedback or alternative suggestions,
though.

**Comment by riscy** [comment]
>  For works of software it is not recommended, as CC0 has a term expressly stating it does not grant you any patent licenses

Apologies, CC0 was a bad suggestion. :)

**Comment by stepnem** [comment]
> package-lint-current-buffer (using version 20200226.2001):
> ```
> 1 issue found:
> 1:0: warning: The package summary should start with an uppercase letter or a digit.
> ```
> I see the issue you've raised, but please capitalize the line.

I'm sorry (sincerely, I do appreciate you people's work and dedication
here), but as it currently stands I much prefer not having my packages
in MELPA to submitting to such unreasonable requirements. I have
expressed my opinion on the matter in the issue mentioned at some
length, and haven't seen any rational arguments to the contrary.

> ### License ###
>
> - Please add a LICENSE or COPYING file to the repository
> - stripes.el has no detectable license text ("public domain" is probably too informal -- what about [CC0](https://www.gnu.org/licenses/license-list.en.html#CC0) or the Unlicense?)
>
> - Use a GPL-compatible license.
>   See: https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

I dislike licenses or any kind of legalese, and as far as I know public
domain is GPL compatible, or that's what I learned last time I was
researching the FSF's stance on the matter, anyway.

**Comment by alphapapa** [comment]
> package-lint-current-buffer (using version 20200226.2001): ``` 1 issue found: 1:0: warning: The package summary should start with an uppercase letter or a digit. ``` I see the issue you've raised, but please capitalize the line.
> I'm sorry (sincerely, I do appreciate you people's work and dedication here), but as it currently stands I much prefer not having my packages in MELPA to submitting to such unreasonable requirements. 

I guess you should close this PR then.

> I have expressed my opinion on the matter in the issue mentioned at some length, and haven't seen any rational arguments to the contrary.

The simplest reason is that it looks better in the list of packages when their descriptions are capitalized rather than having them randomly capitalized or not.  You may not care about that argument, but it's not irrational.  MELPA is trying to improve the quality of the repository and the user experience as a whole, and details matter.

> ### License ### - Please add a LICENSE or COPYING file to the repository - stripes.el has no detectable license text ("public domain" is probably too informal -- what about [CC0](https://www.gnu.org/licenses/license-list.en.html#CC0) or the Unlicense?) - Use a GPL-compatible license. See: https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses
> I dislike licenses or any kind of legalese, and as far as I know public domain is GPL compatible, or that's what I learned last time I was researching the FSF's stance on the matter, anyway.

You're asking MELPA to distribute this software.  MELPA asks that it have certain licenses.  If you're not willing to meet that request, again, you should close the PR.

**Comment by riscy** [comment]
Regarding the license, I'll quote the GPL-compatible licenses page:

> If you want to release your work to the public domain, we encourage you to use formal tools to do so.

And the [section of CONTRIBUTING on GPL-compatible licenses](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#what-to-know-before-opening-a-pull-request):

> The repository should contain a LICENSE or COPYING file, formatted so that it can be detected by common tooling.

Incidentally, I'll mention here that the package name `stripes` is in direct conflict with an Emacsmirror package (repo git@github.com:emacsmirror/stripes.git), so it would be a good idea to rename this package if you decide to go forward with it.

**Comment by stepnem** [comment]
> Regarding the license, I'll quote the GPL-compatible licenses page:
>
>> If you want to release your work to the public domain, we encourage you to use formal tools to do so.
>
> And the [section of CONTRIBUTING on GPL-compatible licenses](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#what-to-know-before-opening-a-pull-request):
>
>> The repository should contain a LICENSE or COPYING file, formatted so that it can be detected by common tooling.

I wanted to avoid all this. Still do. That said, I do lack sufficient
legal expertise, so if it really is so important to you, I am willing to
include something like UNLICENSE in the repository.

(I'll also note that there are already a few dozen other public domain
packages in MELPA, including two mine, reviewed and approved by you and
Steve just a few months ago without any license-related comment.)

> Incidentally, I'll mention here that the package name `stripes` is in
> direct conflict with an Emacsmirror package (repo
> git@github.com:emacsmirror/stripes.git), so it would be a good idea to
> rename this package if you decide to go forward with it.

Yes, that's just the old version import from EmacsWiki, to be superseded
by this version, not a separate package.

**Comment by riscy** [comment]
> I'll also note that there are already a few dozen other public domain packages in MELPA, including two mine, reviewed and approved by you and Steve just a few months ago without any license-related comment.)

Thanks, I've recently asked to be a bit more strict with licenses.

**Comment by stepnem** [comment]
> Thanks, I've recently asked to be a bit more strict with licenses.

OK. For any particular reason?

Somewhat interestingly, despite the text about CC0 you quoted upthread,
now reading the Wikipedia article on the Unlicense I notice that both
the FSF as well as others allegedly actually recommend CC0 over
Unlicense for software:

https://en.wikipedia.org/wiki/Unlicense

https://en.wikipedia.org/wiki/Creative_Commons_license#Zero_/_public_domain

So, I'll let you interested parties take the pick I guess.

I think with CC0 I could get away with just a link in the library
headers instead of a separate file...?

**Comment by riscy** [comment]
I also said:

> Apologies, CC0 was a bad suggestion. :)

**Comment by stepnem** [comment]
> I also said:
>
>> Apologies, CC0 was a bad suggestion. :)

Precisely. I think you misread my last reply.

**Comment by riscy** [comment]
Yeah, sorry. :)  I need to take a break.

**Comment by riscy** [comment]
@tarsius -- I wanted to double-check with you that the existence of "stripes" on Emacsmirror isn't an issue for merging this package?

Also, I could use some help in addressing @stepnem's concerns about licensing --

> OK. For any particular reason?

and possibly some guidance on this one.

**Comment by tarsius** [comment]
> I wanted to double-check with you that the existence of "stripes" on Emacsmirror isn't an issue for merging this package?

It's not a problem in this case because this isn't another package by the same name but a newer version of the same package, and the original author has agreed to the takeover.

(@riscy but please keep asking if in doubt.)

(@stepnem if that conversation happened somewhere in public, then it would be great if you could link to it. Otherwise if Michael Schierl has a github account, then it would be great if you could summon him to give a brief statement.)

> Also, I could use some help in addressing @stepnem's concerns about licensing --

A public-domain dedication is perfectly fine. I just ask that it is done in a way that can be parsed by `elx.el`, which is the case here.

https://www.gnu.org/licenses/license-list.en.html#PublicDomain

**Comment by stepnem** [comment]
> (@stepnem if that conversation happened somewhere in public, then it
> would be great if you could link to it. Otherwise if Michael Schierl
> has a github account, then it would be great if you could summon him
> to give a brief statement.)

We communicated by e-mail, but Michael does apparently also have a
GitHub account, let's see: @schierlm

Thanks.

**Comment by schierlm** [comment]
What kind of statement are you expecting from me? Sorry I did not read the whole conversation.

About `stripes.el` or its former name `color-alternation-mode.el`: Yes I wrote this originally, and posted it as color-alternation-mode.el to gnu.emacs.sources usenet group on Oct 24, 2003 (more than 16 years ago). The original version alternated the color for each line, and the feature to apply it to larger blocks came later.

At that time, Google still archived almost whole Usenet (they even bought DejaNews), so I myself do not have the thread archived anywhere and cannot find it any longer. I am unaware and do not care how many forks of it made it into some wikis or other repositories.

I am also no longer using Emacs, so I don't care about what happens to the package and/or who maintains it (if it is still useful for him).

I also agree to have my original code put into the Public Domain (or relicense it under MIT license if anyone prefers that), but cannot talk about anyone who may have edited it later without adding his name to the copyright statement.

**Comment by tarsius** [comment]
> What kind of statement are you expecting from me?

You covered it. :grinning: (Basically "yes I am okay with this".)

**Pull request merged**
