### PR TITLE
Add Daml mode from https://github.com/bartfailt/daml-mode

### PR DESCRIPTION
**Pull request by arobertn**
### Brief summary of what the package does

The package provides a mode for editing files written in the [Daml smart contract language](https://docs.daml.com). It includes support for LSP mode (a language server comes with the Daml developer install).

### Direct link to the package repository

https://github.com/bartfailt/daml-mode

### Your association with the package

I'm a user of the package.

### Relevant communications with the upstream package maintainer

[Discussion taking place on Daml forum thread here.](https://discuss.daml.com/t/daml-syntax-highlighting-on-emacs/3174/11)

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

`daml-mode.el` with byte-compile using Emacs 29.1:

```
No issue found.
```

`daml-lsp.el` with byte-compile using Emacs 29.1:

```
In toplevel form:
daml-lsp.el:70:36: Warning: attempt to let-bind constant `:uri'
daml-lsp.el:70:41: Warning: attempt to let-bind constant `:note'

In lsp-daml--virtualResource-note:
daml-lsp.el:71:40: Warning: reference to free variable `uri'
daml-lsp.el:71:44: Warning: reference to free variable `note'
daml-lsp.el:74:38: Warning: attempt to let-bind constant `:uri'
daml-lsp.el:74:43: Warning: attempt to let-bind constant `:contents'

In lsp-daml--virtualResource-change:
daml-lsp.el:75:40: Warning: reference to free variable `uri'
daml-lsp.el:75:44: Warning: reference to free variable `contents'
```

`daml-mode.el` with checkdoc (0.6.2)

```
daml-mode.el:26: First line is not a complete sentence
daml-mode.el:36: First line is not a complete sentence
daml-mode.el:36: There should be two spaces after a period
```


`daml-lsp.el` with checkdoc (0.6.2)

```
daml-lsp.el:30: All variables and subroutines might as well have a documentation string
daml-lsp.el:43: All variables and subroutines might as well have a documentation string
daml-lsp.el:70: All variables and subroutines might as well have a documentation string
daml-lsp.el:74: All variables and subroutines might as well have a documentation string
daml-lsp.el:78: All variables and subroutines might as well have a documentation string
```

`daml-mode.el` with package-lint (20230905.629)

```
1:0: error: Error parsing main package file "lisp/daml-mode.el": (file-missing Opening input file No such file or directory d:/_workspace/_lang/elisp/daml-mode/lisp/lisp/daml-mode.el)
6:0: error: Package-Requires outside the main file have no effect.
19:10: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-lib'.
33:2: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-remove-duplicates'.
45:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
```

`daml-lsp.el` with package-lint (20230905.629)

```
1:0: error: Error parsing main package file "lisp/daml-mode.el": (file-missing Opening input file No such file or directory d:/_workspace/_lang/elisp/daml-mode/lisp/lisp/daml-mode.el)
12:10: error: You should depend on (emacs "24.1") if you need `shr'.
29:0: error: "lsp-daml--virtualResource-kill-hook" doesn't start with package's prefix "daml".
42:0: error: "lsp-daml--script-result-buffer-name" doesn't start with package's prefix "daml".
69:0: error: "lsp-daml--virtualResource-note" doesn't start with package's prefix "daml".
73:0: error: "lsp-daml--virtualResource-change" doesn't start with package's prefix "daml".
77:0: error: "lsp-daml--display-virtualResource" doesn't start with package's prefix "daml".
81:17: error: You should depend on (emacs "24.1") if you need `libxml-parse-html-region'.
86:11: error: You should depend on (emacs "24.1") if you need `shr-insert-document'.
```

Package and license:

- GPLv3

**Comment by riscy** [comment]
Thanks both.  I will quickly add a couple notes re: the license -

- lisp/daml-lsp.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- lisp/daml-mode.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by arobertn** [comment]
Thanks @jcs090218 and @riscy. I'll submit a PR upstream to fix these and let you know when that is ready. (When I ran the same version of package-lint I did not get those warnings btw, so it seems I have some learning to do on how to run it.)

**Comment by riscy** [comment]
> (When I ran the same version of package-lint I did not get those warnings btw, so it seems I have some learning to do on how to run it.)

By the way, this is likely because `package-lint-main-file` hasn't been set when you're running it, so there are fewer things that package-lint checks for.  I'm adding a note in my output scroll to help disambiguate this, so your comment helps.

Let me know when this is ready for another look. :)

**Comment by bartfailt** [comment]
Hello @riscy , @arobertn . I believe I fixed all the warnings. I don't have any emacs packaging experience, so let me know if I missed something.

**Comment by purcell** [comment]
Hi Adrian! I'd note that `daml-lsp` and `daml-mode` should really be two separate packages, with the former depending on the latter. ie. someone should be able to use `daml-mode` without needing the full `lsp-mode` package to be installed, e.g. if they are prefer to use `eglot` instead. This can be achieved by having two recipes here, each with `:include ("the-corresponding-file.el")` and adding the appropriate `Package-Requires` header in `daml-lsp.el`.

**Comment by bartfailt** [comment]
@arobertn I just fixed that let-binding warning in my last commit: https://github.com/bartfailt/daml-mode/commit/649fa8158285f7343339f8ccf0d7ce2b9b5b5917

**Comment by bartfailt** [comment]
@purcell So the best practice is that a single repository can produce multiple melpa packages. In other words the recipes breaking it up into multiple packages? I was thinking about eglot, but I didn't want to create two separate package with one file each.

**Comment by purcell** [comment]
> So the best practice is that a single repository can produce multiple melpa packages. In other words the recipes breaking it up into multiple packages?

It depends. It's somewhat easier from a MELPA perspective if each repo has a single package (which might itself contain multiple files). This way you don't tend to have to tweak the include/exclude patterns in MELPA as your package evolves. But in the case of a small repo like this where you've got one or two small sub-packages, it's fine to keep them together and divide them up using the recipes. At this early stage, in your position, I'd probably just make a new `daml-lsp` repo and move that file over there, with a copy of the other boilerplate. Repos are free, and then it's a bit neater if you want to put badges in the README etc. Up to you!

**Comment by riscy** [comment]
The checklist looks great here - I've just held off since last week because I agree that this should be two separate packages.  Assuming the determination of how to do this hasn't been made yet, but (to echo purcell) it's up to you. :)

(Two packages with a single file each aren't a problem *at all*.)

**Comment by arobertn** [comment]
For comparison's sake, I created a draft PR (https://github.com/bartfailt/daml-mode/pull/3) to support package splitting. I did not create the corresponding PR here though (with two recipes and `:include ("daml-{mode,lsp}.el")`).

**Comment by bartfailt** [comment]
@arobertn I moved daml-lsp into its own repo here https://github.com/bartfailt/daml-lsp and added the removal commit to your PR. Can you update this PR here to only include daml-mode and create a similar for daml-lsp. If your PR is ready in the daml-mode repo, please mark is as ready for review and I will merge it.

**Comment by bartfailt** [comment]
fyi I merged @arobertn 's PR (https://github.com/bartfailt/daml-mode/pull/3)

**Comment by purcell** [comment]
Great, merged now. :-)

**Comment by purcell** [comment]
I added `daml-lsp` too since it was in good shape.

**Comment by arobertn** [comment]
Thanks both. (Sorry @bartfailt you were quicker than me here.) I tested install from melpa (`M-x package-install daml-lsp`) and it worked perfectly. :-)

**Pull request merged**
