### PR TITLE
eredis now maintained at github

### PR DESCRIPTION
**Pull request by lujun9972**

### CODE REVIEW

**Comment by purcell** [comment]
Is this change of maintainer documented somewhere?

**Comment by purcell** [comment]
Why don't we just ping @justinhj here and see what he thinks? :-)

**Comment by lujun9972** [comment]
Good idea!

**Comment by justinhj** [comment]
Hi there, yeah I've been meaning to update Melpa to point at the github repo but I don't know how to do it. Assuming that was your question :)

**Comment by purcell** [comment]
Mainly just wanted to confirm that you're fine with the MELPA eredis
drawing from the specific Github repo mentioned in this PR.

**Comment by justinhj** [comment]
I moved the original to github.com/justinhj/eredis I'd prefer to use that

**Comment by purcell** [comment]
Cool, done. Maybe you'd be open to pull requests from @lujun9972 and others if they've made improvements they believe are necessary or worthwhile?

**Comment by justinhj** [comment]
Absolutely. Also I found out recently that this doesn't work with Windows Redis servers because of the new line differences. I would like to fix that soon too.

**Comment by lujun9972** [comment]
sorry, I don't know there is justinhj/eredis repository

so, should I modify the `eredis` file and push it again or waiting @justinhj to do the push?

**Comment by purcell** [comment]
@lujun9972 No, I've updated the recipe to use Justin's repo, so if you send him a pull request and he merges it, your changes would automatically appear in MELPA.

**Comment by lujun9972** [comment]
That's cool. Thank you :smiley:

**Pull request closed without merging**
