### PR TITLE
Add recipe for aiken-mode

### PR DESCRIPTION
**Pull request by ch1bo**
### Brief summary of what the package does

An emacs major mode providing syntax highlighting, indentation and formatting
commands for the [Aiken](https://aiken-lang.org/) smart contract language.

### Direct link to the package repository

https://github.com/ch1bo/aiken-mode

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`aiken-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- aiken-mode.el#L79: There is no need to quote lambdas (neither #' nor ')
```

Also your `auto-mode-alist` entry matching `"\\.ak"` should match `\\.ak\\'"` instead

**Comment by ch1bo** [comment]
Added melpazoid as a CI on my repository and fixed the linting errors: https://github.com/ch1bo/aiken-mode/actions/runs/6222213255

**Comment by ch1bo** [comment]
@riscy I addressed your points and the package now also moved to [aiken-lang/aiken-mode](https://github.com/aiken-lang/aiken-mode)

**Comment by riscy** [comment]
Thank you!

**Pull request merged**
