### PR TITLE
Add neuron-mode recipe

### PR DESCRIPTION
**Pull request by felko**
### Brief summary of what the package does

Major mode for editing notes using the [neuron](https://neuron.zettel.page/) zettelkasten manager.

### Direct link to the package repository

https://github.com/felko/neuron-mode

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Checklist looks good on a very quick first pass.  I only see --

byte-compile-file (using Emacs 26.3):
```
neuron-mode.el:148:1:Warning: Unused lexical argument `show-tags'
```

which looks like it should be used in the function body, based on the docstring.

**Comment by felko** [comment]
Thanks, that should be fixed now.

**Comment by riscy** [comment]
The latest --

byte-compile-file (using Emacs 26.3):
```
neuron-mode.el:408:1:Warning: the function `neuron-query-tag' is not known to
    be defined.
```
(called in a couple places)

**Comment by felko** [comment]
Fixed 👍 

`byte-compile-file` seems to raise warnings when a function is not in the environment, but actually doesn't care about whether it's in the current file or not. I evaluate the buffer during the development of the package (and `neuron-query-tag` existed at one point) so the warning didn't trigger. Took me a while to understand.

**Comment by riscy** [comment]
Yeah, this is one of the biggest gotchas when developing Emacs packages.  `flycheck` for emacs lisp mode can give you great feedback that can prevent these sorts of things.

In any case this looks good to me.  I also took a peek at your webpage and like what you've done with the place re: neuron. :)  And, welcome to MELPA!

**Comment by felko** [comment]
Thank you, I am not the author of neuron itself, nor the author of [neuron.zettel.page](https://neuron.zettel.page) though

**Pull request merged**
