### PR TITLE
Add recipe for easky

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Control Eask CLI in Emacs

### Direct link to the package repository

https://github.com/emacs-eask/easky

### Your association with the package

The author

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
With `eask lint checkdoc`

`easky.el` with checkdoc (0.6.2)

```
easky.el:858: Name emacs should appear capitalized as Emacs
```

The "Emacs" here should be lower case to differentiate the command `eask emacs`.

`easky.el` with package-lint (20230905.629)

```
1:0: warning: Including "Emacs" in the package summary is usually redundant.
```

Hope this isn't a blocker. 😕

**Comment by riscy** [comment]
Thanks for this.  Checkdoc is within reason.

Re: those package-lint warnings, consider a user on Emacs 27.1 will see corresponding byte-compile warnings along these lines --

`easky-package.el` with byte-compile using Emacs 28.1:
```
easky-package.el:164:47: Warning: the function `package-upgrade-all' is not
    known to be defined.
easky-package.el:156:47: Warning: the function `package-upgrade' is not known
    to be defined.
easky-package.el:140:47: Warning: the function `package-recompile-all' is not
    known to be defined.
easky-package.el:132:47: Warning: the function `package-recompile' is not
    known to be defined.
```

which you can pacify for them using `declare-function`.

> Hope [Including "Emacs" in the package summary] this isn't a blocker. 😕

But it *is* redundant. :)  This is an Emacs package that will be used in Emacs.  I would just write the summary as "Control the Eask command-line interface".

I also notice you're calling `shell-command-to-string` with an unsanitized string (I infer it would be the name of an elisp function, but note that elisp functions can technically contain shell control characters, although obviously MELPA discourages it).  This is minor but I'll mention it just in case.

**Comment by jcs090218** [comment]
I've fixed the checkdoc warnings and changed the package summary to "Control the Eask command-line interface".

> I also notice you're calling shell-command-to-string with an unsanitized string (I infer it would be the name of an elisp function, but note that elisp functions can technically contain shell control characters, although obviously MELPA discourages it). This is minor but I'll mention it just in case.

I have tried to wrap it with the function `shell-quote-argument`, but it doesn't work on Windows. 🤔 

The output:

```
'"eask --help"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by riscy** [comment]
> but it doesn't work on Windows.

Are you implying it does work in unix-like environments?  I can't see the code that generated the error you're showing, but at a guess you ran `shell-quote-argument` over the entire command, instead of the individual arguments.

**Comment by jcs090218** [comment]
> Are you implying it does work in unix-like environments? I can't see the code that generated the error you're showing, but at a guess you ran `shell-quote-argument` over the entire command, instead of the individual arguments.

I obviously forgot how to use this function... I've applied the fix! Sorry for the confusion! 😓

**Comment by riscy** [comment]
Thanks - I can merge this now, but I'd ask you to improve your `;;; Commentary`.  I remember suggesting this to you in the past (so I apologize for sounding like a broken record) but your Commentary shouldn't be an automated copy-paste of your summary line -- otherwise, why would we have both?  Your commentary is a chance to include entrypoints, context, and examples.  One *obvious* thing that is missing for "easky"  is context -- you should at the very least include a link to Eask, on which this is meant to be built.

One other thing I want to caution you on is that I am seeing lots of optional dependencies being into this eask ecosystem you've created; in easky I see yet another example, where you're defvaring variables from `github-elpa` without ever declaring a dependency on it.  In general doing this sort of thing is valid practice, but (in my humble opinion) you're taking on considerable risk by hanging *invisible* dependencies on many packages (and Emacs versions) in such a way that the byte-compiler will have difficulty detecting them when something goes wrong.

**Pull request merged**
