### PR TITLE
Add faustine

### PR DESCRIPTION
**Pull request by yassinphilip**
### Brief summary of what the package does

Faustine allows the editing of [Faust](http://faust.grame.fr/about/) code : Syntax highlight, indentation, completion (ac) rules and helper functions. It also has a notion of project : The Faust files are inter-linked, and can be build together. It introduces a major mode and two minor modes, the latter two both local to the former one ; More info about Faustine and Faust in the README.md file.

### Direct link to the package repository

https://bitbucket.org/yassinphilip/faustine

### Your association with the package

I'm the author, maintainer and, well, also a happy user of Faustine.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

I can't offer any feedback on the package's stated purpose, but here is a little feedback on the package itself:

* The package headers at the top aren't in the standard format, e.g. the `Version` header has `;;;`, and the author, keywords, etc. headers are separated from the other package headers.
* I see `defvar`s for `auto-complete` vars like `(defvar ac-sources)`.  Instead you should `(require 'auto-complete)`.
* You should also declare package dependencies on `auto-complete` and any other packages you require.
* It would be good to include a few sentences in the commentary that explain at least how to activate the modes, because the readme won't necessarily be available with the source file after installation.
* Might be good to `(require 'easymenu)`; I don't know if it's loaded by default.
* In `faustine-source-code` you call `/bin/bash`, so I guess you should note that this is a Unix/Cygwin-only package.
* I guess you might want to use `shell-quote-argument` when you use `shell-command-to-string` or `start-process-shell-command`.  On the other hand, for `shell-command-to-string`, you could use `call-process` instead.
* `(string= "" ...` can be `(string-empty-p`, using `subr-x`, but I guess it's a matter of style.

Overall it looks like you did a great job, looks like a solid Emacs package.  Thanks.

**Comment by yassinphilip** [comment]
Hi Alphapapa, thanks for the feedback!!

> The package headers at the top aren't in the standard format, e.g. the Version header has ;;;, and the author, keywords, etc. headers are separated from the other package headers.

How comments are really to be organized/laid out is still unclear to me, I conformed to what the linter and flycheck were saying, isn't this enough? I also watched at other packages, would [this package's way of doing things](https://github.com/mkcms/himp/blob/master/himp.el) be OK? I'm having a hard time figuring out what I did differently..? Can't I just prefix every line with `;;;` and move on? There should be a template somewhere, I'm sorry, I'm sure there is, where is it? :)

> I see defvars for auto-complete vars like (defvar ac-sources). Instead you should (require 'auto-complete). You should also declare package dependencies on auto-complete and any other packages you require.

Ah! About that ; Is there any "auto-install the required packages" in the packaging system? From what I could gather, there is. That would basically mean that any `required` package will be installed, can you confirm that?

But you are definitely right, those `defvar`s are hacky, redundant and dirty.

I wanted to make things optional ; You use auto-complete, fine, now you have sensible AC rules for this language. You don't, fine, no AC (ideally I can `message` you once about that) ; Is this behavior even possible?

> It would be good to include a few sentences in the commentary that explain at least how to activate the modes, because the readme won't necessarily be available with the source file after installation.

Well, the idea is that the package handles it and adds itself to the `auto-mode-alist`, but then again some people (not me) prefer to handle those adds themselves ; What would be the best practice? Should I drop the `auto-mode-alist` auto-adding altogether?

> Might be good to (require 'easymenu); I don't know if it's loaded by default.

I think it is ; OK, I'm going to investigate (like read your answers above, specially about this "auto-install required mackages" and get the final word about that. See, ideally there would be a message that says "This package works better with (but can work fine without) this package, do you want to install it"? It would be really nice to settle this interrogation for me.

> In faustine-source-code you call /bin/bash, so I guess you should note that this is a Unix/Cygwin-only package.

Ah, yes. This is a PB too ; What is the best practice regarding shell command interpreters that would allow maximum portability? I'm only asking, I know I can test it myself, but if you know, please tell me :p Thank you for pointing this out anyway, hey, are you even paid to scrutinize my crappy code?

> I guess you might want to use shell-quote-argument when you use shell-command-to-string or start-process-shell-command. On the other hand, for shell-command-to-string, you could use call-process instead.

Oh, I guess this is the answer to my right above questions about shell commands portability ; Will do.

> (string= "" ... can be (string-empty-p, using subr-x, but I guess it's a matter of style.

Of course it could. This went under my radar, It's supposed to be handled by the "universal" `faustine-log-to-buffer` sentinel. Again, thanks.

> Overall it looks like you did a great job, looks like a solid Emacs package. Thanks.

Wow, thanks to *you* ; This final comment made my day, much like Melpa made my life so much easier in general :)

yPhil (https://yassinphilip.bitbucket.io)

PS - I'm going to address all the above and update the master branch, should I do anything more to make things easier for you guys? Oh, and is it okay if I update my recipe to include the README.md? Should I even do that? I mean, every package should ship with its documentation, right?

**Comment by alphapapa** [comment]
> How "header" comments (?) are really to be organized/laid out is still unclear to me, I conformed to what the linter and flycheck were saying, isn't this enough? I also looked at other random packages, would this package's way of doing things be OK? I'm having a hard time figuring out what I did differently..? Can't I just prefix every line with ;;; and move on? There should be a template somewhere, I'm sorry, I'm sure there is, where is it? :)

Allow me to point you to a new project of mine.  :)  Go here and click on the link "Package headers and structure": https://alphapapa.github.io/emacs-package-dev-handbook/#org26c5a7a

> > I see defvars for auto-complete vars like (defvar ac-sources). Instead you should (require 'auto-complete). You should also declare package dependencies on auto-complete and any other packages you require.

> Ah! About that ; Is there any "auto-install the required packages" feature (and if there is, what is handling it, Emacs, the package feature, or Melpa itself)? From what I can gather, there is. That would basically means that any required package will be installed, can you confirm that?

When you declare your dependencies in the `Package-Requires:` line, they will be installed automatically when your package is installed. 

> I wanted to make things optional ; You use auto-complete, fine, now you have sensible AC rules for this language. You don't, fine, no AC (ideally I can message you once about that) ; Is this behavior even possible? I'm really looking forward to sorting this out.

You can use `with-eval-after-load` to support optional packages.  You can see how I did it here: https://github.com/alphapapa/org-recent-headings/blob/master/org-recent-headings.el#L435  Be advised that it can sometimes cause weird issues with the byte-compiler or user configs if you don't fully understand how it all works under the hood; I don't, and so I've lost a few hairs trying to make it work there.  I think it's finally correct, but I thought that several times before, too, before I made a small change to my personal config and started getting errors on init.

> > It would be good to include a few sentences in the commentary that explain at least how to activate the modes, because the readme won't necessarily be available with the source file after installation.

> Well, the idea is that the package handles it and adds itself to the auto-mode-alist, but then again some people (not me) prefer to handle those adds themselves ; What would be the best practice? Should I drop the auto-mode-alist auto-adding altogether (and leave in the cold users like me who like things to... Hum, work out of the box? Dwim ;)) ?

I don't know about this, but I'm guessing that it's okay to go ahead and add to the auto-mode-alist.  Steve or Syohei should know the answer.

> >Might be good to (require 'easymenu); I don't know if it's loaded by default.

> I think it is ; OK, I'm going to investigate (like read your answers above, specially about this "auto-install required mackages" and get the final word about that. See, ideally there would be a message that says "This package works better with (but can work fine without) this package, do you want to install it"?

Probably best to just mention the optional packages in the documentation.  If your package is nearly unusable without them, you could use `message` to suggest installing them to the user, but then you have to figure out when to show the message...

> It would be really nice to settle this interrogation for me. My ideal is my package working fine without any alteration of the init file, thus allowing a clean de-install, by the way. Is this handled too by package? I mean, the de-install, like removing "customize" entries too?

This is a matter for package.el.  In Emacs 25 it tracks which packages are installed as dependencies.

> > In faustine-source-code you call /bin/bash, so I guess you should note that this is a Unix/Cygwin-only package.

> Ah, yes. This is a PB too ; What is the best practice regarding shell command interpreters that would allow maximum portability? I'm only asking, I know I can test it myself, but if you know, please tell me :p

Sorry, I don't know the answer to this.

> Thank you for pointing this out anyway, hey, are you even paid to scrutinize my crappy code and suffer through my airport English?

Your code actually seems very well done!  It's far better than most packages that I've reviewed.

> > I guess you might want to use shell-quote-argument when you use shell-command-to-string or start-process-shell-command. On the other hand, for shell-command-to-string, you could use call-process instead.

> Oh, I guess this is the answer to my right above questions about shell commands portability ; Will do.

I think that's not a matter of portability as much as security.  Arguments to the shell should always be quoted, in general, but I confess I haven't messed with shell-command-to-string much in Emacs.  I've just used call-process and call-process-region, for which quoting isn't necessary.

> > Overall it looks like you did a great job, looks like a solid Emacs package. Thanks.

> Wow, thanks to you ; This final comment made my day, much like Melpa made my life so much easier in general :)

Well, you did a very comprehensive job before submitting the package, far more than most authors do.  And MELPA has helped me a lot too, so I try to help out Steve and Syohei by giving some cursory reviews before they do theirs.  They are much more experienced and knowledgeable than I am, however; I always learn a lot when they give me feedback.

> PS - I'm going to address all the above and update the master branch, should I do anything more to make things easier for you guys?

That's fine.

> Oh, and is it okay if I update Faustine's recipe to include the README.md?) Should I even do that, I mean, every package should/must ship with its documentation, right?

You'd have to ask Steve or Syohei on this.  I think it's generally frowned upon, as the user would have to dig into the ELPA directory to find it.  Some Emacs packages have an entire man page's worth of text in the commentary (which I think is a bit overkill, but better than nothing).

Another data point is Helm, which ships some separate documentation in a `helm-help.el` file, which defines variables containing Org-mode text that is displayed when the user calls the help commands.

**Comment by yassinphilip** [comment]
Hi!

Another fine answer, thanks a lot for your guidance @alphapapa :)
I think I'm finally finished. I addressed all of the concerns raised above, plus I consolidate some functions :

- [x]  Headers OK
- [x]  No externals (see below)
- [x]  Abstracted/portable shell commands
- [ ]  Not sure about `shell-quote-argument` usage (see below)
- [x]  No more string= ""

I gave up on completion, plain and simple ; I will *not* force the installation of a completion backend system on the user, no discussion about that ; I find it somehow disappointing to not be able to simply say "If the user have AC installed, then please silently add this list of keywords to it" and "Oh, company? Well then do this, but please shut up" without unleashing a hell of "free variables" and "function is not know to be defined" warnings. I'm talking _two full (holy) days_ here, just trying to add my keywords to _potentially installed_ libraries lists. Let's not even talk about it, I'm really fed up with this "require" rigid nonsense.

So, yeah. From now on it will only be bug fixing and corners smoothing ; Now how does this work, will my package be reviewed again? I mean, do I have a chance to see it in MELPA before the end of summer? This year? 

I will study sub shell string quoting, and maybe (probably, if the tests are successful) include it in master _in the future_, but can this detail not stall the package inclusion, please?

What else can I do to make things happen?

**Comment by alphapapa** [comment]
> I gave up on completion, plain and simple ; I will not force the installation of a completion backend system on the user, no discussion about that ; I find it a little more than mildly disappointing to not be able to simply say "If the user have AC installed, then please silently add this list of keywords to it" and "Oh, company? Well then do this, but please shut up" without unleashing a hell of "free variables" and "function is not know to be defined" warnings.  I'm talking two full (holy) days here, just trying to add my keywords to potentially installed libraries lists. Let's not even talk about it, I'm really fed up with this "require" rigid nonsense.

Those are merely byte-compiler warnings, and they can be silenced easily.  See the `declare-function` function.  They need not stop you from using `with-eval-after-load` to support `ac` and `company-mode`.  e.g. see how I used it here: https://github.com/alphapapa/org-recent-headings/blob/master/org-recent-headings.el#L377

> Now how does this work, will my package be reviewed again? I mean, do I have a chance to see it in MELPA before the end of summer? This year?

I am not a MELPA staff member, just an enthusiastic user who tries to help out now and then.  If you look at the merged PRs, you can see that sometimes they take a few days, sometimes a few weeks.  Everyone here contributes in their spare time, so it depends on how busy they are in real life.  Your package is also much larger than the average new submission.  Please be patient.

> I will study sub shell string quoting, and maybe (probably, if the tests are successful) include it in master in the future, but can this detail not stall the package inclusion, please?

Again, this is not up to me.  Steve or Syohei should probably be consulted about whether this is necessary.

**Comment by yassinphilip** [comment]
>> I gave up on completion, plain and simple ; I will not force the installation of a completion backend system on the user, no discussion about that ; I find it a little more than mildly disappointing to not be able to simply say "If the user have AC installed, then please silently add this list of keywords to it" and "Oh, company? Well then do this, but please shut up" without unleashing a hell of "free variables" and "function is not know to be defined" warnings. I'm talking two full (holy) days here, just trying to add my keywords to potentially installed libraries lists. Let's not even talk about it, I'm really fed up with this "require" rigid nonsense.

> Those are merely byte-compiler warnings, and they can be silenced easily. See the declare-function function. They need not stop you from using with-eval-after-load to support ac and company-mode. e.g. see how I used it here: https://github.com/alphapapa/org-recent-headings/blob/master/org-recent-headings.el#L377

Mm... Not sure I want to go back in there... It's sunny outside, and both AC and Company are weird, I can't seem to achieve what I want without at best warnings, at worse plain breaking everything :(

>> Now how does this work, will my package be reviewed again? I mean, do I have a chance to see it in MELPA before the end of summer? This year?

> I am not a MELPA staff member, just an enthusiastic user who tries to help out now and then. If you look at the merged PRs, you can see that sometimes they take a few days, sometimes a few weeks. Everyone here contributes in their spare time, so it depends on how busy they are in real life. Your package is also much larger than the average new submission. Please be patient.

Ah... Okay, then. The more thanks for *your* patience, BTW :)

**Comment by alphapapa** [comment]
> Mm... Not sure I want to go back in there... It's sunny outside, and both AC and Company are weird, I can't seem to achieve what I want without at best warnings, at worse plain breaking everything :(

That's ok, I don't blame you.  You can always add a note in the readme with example code and users can configure it themselves.

> Ah... Okay, then. The more thanks for your patience, BTW :)

Just trying to give back, because I have received much.  :)

**Comment by yassinphilip** [comment]
>> Mm... Not sure I want to go back in there... It's sunny outside, and both AC and Company are weird, I can't seem to achieve what I want without at best warnings, at worse plain breaking everything :(

> That's ok, I don't blame you. You can always add a note in the readme with example code and users can configure it themselves.

Hey, if you feel like it, you're welcome to commit on the repo! Seriously, that would be cool :)

>> Ah... Okay, then. The more thanks for your patience, BTW :)

> Just trying to give back, because I have received much. :)

Still, thank you very much ; I guess I should do that too (review MELPA PRs) I will, probably. It's basic nature cycle ;)

**Comment by alphapapa** [comment]
> Hey, if you feel like it, you're welcome to commit on the repo! Seriously, that would be cool :)

Thanks for the invitation, but since I can't use the package myself (I don't do anything like audio synthesis), I'll have to pass.  :)

> Still, thank you very much ; I guess I should do that too (review MELPA PRs) I will, probably. It's basic nature cycle ;)

Great!  BTW, if you're interested in helping other package developers, you're welcome to contribute to https://alphapapa.github.io/emacs-package-dev-handbook/ anytime you see something that should be added.

**Comment by yassinphilip** [comment]
I see packages come and go (yeah, I come everyday, this is sad) but mine has been stalled for a month now. Is there something wrong with it? How would I know if for some reason, you guys decide not to include it?

**Comment by alphapapa** [comment]
@purcell He has been waiting a while...  :)

**Comment by Silex** [comment]
@yassinphilip: probably just an oversight, it'd be included soon IMHO. Friendly ping to @milkypostman as well.

**Comment by purcell** [comment]
Yep, sorry, having trouble keeping on top of everything in recent months due to work commitments. Nothing personal about this package, it just slipped through the cracks - thanks for your patience!

Quick feedback, then:
- I believe SMIE was ony added in one of the 24.x versions of Emacs, so you should declare a package dependency on that.
- Please use `:files (:defaults EXTRA-STUFF)` instead of `:files (EXTRA-STUFF "faustine.el")`.
- The `defgroup keyboard-shortcuts` should be prefixed with `faustine-`. `package-lint` should have told you about that.
- Don't make custom vars for all the keybindings: just put them in `faust-mode-map`, and users can customise it as they see fit.
- [These lines](https://bitbucket.org/yassinphilip/faustine/src/0088d9b2dbdf2ad9f911ecc554a577616e46cf6f/faustine.el?at=master&fileviewer=file-view-default#faustine.el-476:477) are redundant: `define-derived-mode` does this for you. Same for [this](https://bitbucket.org/yassinphilip/faustine/src/0088d9b2dbdf2ad9f911ecc554a577616e46cf6f/faustine.el?at=master&fileviewer=file-view-default#faustine.el-473). Also, you shouldn't have to call `font-lock-ensure` (or equivalent) explicitly.
- Consider `cl-case` or `pcase` [here](https://bitbucket.org/yassinphilip/faustine/src/0088d9b2dbdf2ad9f911ecc554a577616e46cf6f/faustine.el?at=master&fileviewer=file-view-default#faustine.el-643:646)
- Providing `faustine-configure` is redundant and not idiomatic.
- Always use `shell-quote-argument` when [building command lines](https://bitbucket.org/yassinphilip/faustine/src/0088d9b2dbdf2ad9f911ecc554a577616e46cf6f/faustine.el?at=master&fileviewer=file-view-default#faustine.el-729), to protect against file names which contain quotes or spaces. Same [here](https://bitbucket.org/yassinphilip/faustine/src/0088d9b2dbdf2ad9f911ecc554a577616e46cf6f/faustine.el?at=master&fileviewer=file-view-default#faustine.el-761) and in other places.
- Never try to [deduce file names from buffer names](https://bitbucket.org/yassinphilip/faustine/src/0088d9b2dbdf2ad9f911ecc554a577616e46cf6f/faustine.el?at=master&fileviewer=file-view-default#faustine.el-762): standard features like `uniquify` can break your assumptions. Instead, use `buffer-file-name`.
- It may not be safe to rely on propertising items with xpm images, because they will not render in text frames. Better to (at least) use standard faces, e.g. `success`, `error`.
- I think the `.dsp` file extension is not particularly unique to `faustine`, so I'm not sure you should [autoload the `auto-mode-alist` entry](https://bitbucket.org/yassinphilip/faustine/src/0088d9b2dbdf2ad9f911ecc554a577616e46cf6f/faustine.el?at=master&fileviewer=file-view-default#faustine.el-887).

Hope that helps!

**Comment by Silex** [comment]
@purcell for president! what an amazing feedback :+1:

**Comment by yassinphilip** [comment]
@purcell Wow, @Silex is right, thanks!

I tried to address all the points in your message ; From the top:

> I believe SMIE was ony added in one of the 24.x versions of Emacs, so you should declare a package dependency on that.

OK, I added a
```
;; Package-Requires: ((emacs "24.3"))
```
entry in the headers.

> Please use :files (:defaults EXTRA-STUFF) instead of :files (EXTRA-STUFF "faustine.el").

Ah, OK. Kind of counter-intuitive but OK ; I updated the recipe, it seems to build and install OK ; I pushed it to master, was that the right thing to do?

> The defgroup keyboard-shortcuts should be prefixed with faustine-. package-lint should have told you about that.

Actually, no, lint doesn't care, probably because being a sub-group it is protected behind some kind of namespace ; semantically, it actually makes sense. Anyway, it's gone, you are right on this next point:

> Don't make custom vars for all the keybindings: just put them in faust-mode-map, and users can customise it as they see fit.

Done. Removed the mode-map `#autoload` too, it was there because of the defcustoms, so, yes.

> These lines are redundant: define-derived-mode does this for you. Same for this. Also, you shouldn't have to call font-lock-ensure (or equivalent) explicitly.

Ah, OK. Done ; done ; done.

> Consider cl-case or pcase here

My I ask why? I mean, `cond` does the job natively, why would I use something else?

> Providing faustine-configure is redundant and not idiomatic.

Yes. Sorry.

> Always use shell-quote-argument when building command lines, to protect against file names which contain quotes or spaces. Same here and in other places.

Wow, I didn't know about that ; thanks a lot for making Faustine safer.

> Never try to deduce file names from buffer names: standard features like uniquify can break your assumptions. Instead, use buffer-file-name.

That, too :p

> It may not be safe to rely on propertising items with xpm images, because they will not render in text frames. Better to (at least) use standard faces, e.g. success, error.

This is the only one I didn't adress directly ; you're talking about [this](https://bitbucket.org/yassinphilip/faustine/src/master/faustine.el?at=master&fileviewer=file-view-default#faustine.el-275:293), right? Note that I had to put those "props" mode vars as `risky-local-variable t` maybe for that reason. I'd love to display a string (or nothing) instead of the the XPM in console-mode, only I don't know how to do that at all...

> I think the .dsp file extension is not particularly unique to faustine, so I'm not sure you should autoload the auto-mode-alist entry.

And again, you are right. I've been riding that fence since the beginning, thanks for making the decision.

**Comment by purcell** [comment]
> May I ask why? I mean, cond does a (seemingly..? Is there a potential PB? Do tell) job natively, why would I load a lib to do it?

`pcase` is built-in, and `cl-lib` is built into Emacs 24.3+ (or available via ELPA): both allow you to avoid repeating the `eq type` expression. It's not a big deal, just a tip. :-)

> It may not be safe to rely on propertising items with xpm images, because they will not render in text frames. Better to (at least) use standard faces, e.g. success, error.
> 
> This is the only one I didn't adress directly ; you're talking about this, right? Note that I had to put those "props" mode vars as risky-local-variable t maybe for that reason. I'd love to display a string (or nothing) instead of the the XPM in console-mode, only I'm not really sure how to do that properly...

No, I was talking about the `propertize` calls, like [this](https://bitbucket.org/yassinphilip/faustine/src/0088d9b2dbdf2ad9f911ecc554a577616e46cf6f/faustine.el?at=master&fileviewer=file-view-default#faustine.el-332:337). Just thinking about how that will display on non-graphic terminals.

In any case, this is merged now - thanks for your patience!

**Comment by purcell** [comment]
And, as I try to remember to say: welcome to MELPA!

**Comment by tarsius** [comment]
@yassinphilip What happened to this repository (and your Bitbucket account for that matter)?

Is this package available from somewhere else now or should we delete it?

**Comment by purcell** [comment]
Package deleted.

**Comment by yassinphilip** [comment]
Aw, sorry, I renamed my bitbucket account (s/yassinphilip/yphil/g) and thought I had everything planned out, but forgot about Faustine on MELPA, my (very) bad.

The repo is here: https://bitbucket.org/yphil/faustine

**Comment by yassinphilip** [comment]
Guys, I'm really sorry about all this hassle ; I made a [new pull request](https://github.com/melpa/melpa/issues/5211) ; Please excuse this inexcusable error, this won't happen again.

Sorry _again_.

**Comment by tarsius** [comment]
It's not that bad at all ;-)
But there are many packages and many open pull requests, so we need to resolve things quickly. But once the maintainer does what is required of him we can add such packages back and we understand that other people sometimes are just too busy or forget about something.

**Pull request merged**
