### PR TITLE
Switch to new fork for origami?

### PR DESCRIPTION
**Pull request by jcs090218**
Base on the thread here #6716; I would like to take over [origami](https://github.com/gregsexton/origami.el) (if @gregsexton agreed?).

I have started a fork here [jcs-elpa/origami.el](https://github.com/jcs-elpa/origami.el). I consider this as a much updated version due to that I have been fixing bug and clean up the code for few weeks. And it has new features and supports more programming languages by default.

### CODE REVIEW

**Comment by gregsexton** [comment]
Please merge this. @jcs090218 looks to have put in a lot of time and effort here. Spot checking some of the diffs, they look reasonable. I suspect he or she will make for a great maintainer.

**Comment by jcs090218** [comment]
@gregsexton Thank you! Glad you have time to response! 😄 

I don't know who is responsible to this type of PR here. So I guess I will ping the current maintainers. Sorry if I ping to the wrong person! @purcell @tarsius @riscy

**Comment by minad** [comment]
@gregsexton Would it make sense if you instead add @jcs090218 to your repository as a collaborator? I think many would prefer that instead of changing the location in the melpa repository. This way it would also be more clear that you endorse @jcs090218 as a maintainer.

**Comment by jcs090218** [comment]
@minad Hmm... I like to have all my repo in a place, so probably not. Unless @gregsexton willing to transfer the repo to me, I would rather choose to update the recipe's url for less hassle. 😅 But thanks for the suggestion! 👍

**Comment by minad** [comment]
@jcs090218 I understand your sentiment. As far as I see it, this is the original maintainers decision to make. For everyone else beside you, not changing the url is less hassle since then it is obvious from looking at the repository if it is the official one. Usually I always find it difficult if suddenly a forked repository is the official one, therefore I try to avoid that. Transferring is certainly an option too. Note, that I am just an outsider here, do whatever you prefer and discuss with the melpa maintainers.

**Comment by jcs090218** [comment]
@minad I see your point here! I think it would be great if @gregsexton transfer the repo to me so then we can keep all PRs and issues! But I am fine with both solutions!

@gregsexton What do you think?

Thanks for both participating!

**Comment by tarsius** [comment]
If you want to do it perfectly, then it is a little complicated:

1. @gregsexton says that he is going to transfer the repository to @jcs090218.
2. @jcs090218 contacts github support to remove the link relationship from his fork. Last I checked users could not do that themselves and transferring is not possible without either doing this or deleting the fork.
3. Github does that and informs @jcs090218.
4. @jcs090218 informs @gregsexton.
5. @gregsexton transfers to @jcs090218.
6. @jcs090218 transfers each issue/pr individually and in numeric order from this detached fork to the upstream repository, which is now located under his account.

Alternatively @jcs090218 deletes his fork and then @gregsexton transfers the upstream repository.

In any case, @jcs090218 should ***not delete*** the fork ***until*** @gregsexton has agreed to transfer.

**Comment by minad** [comment]
@tarsius There is a simple alternative, which I would prefer and which avoids any hassle. This is simply adding @jcs090218 to the original origami repository by @gregsexton. This would work for everyone. While I understand that it is nice for @jcs090218 to have everything at one place, ultimately this does not seem very realistic to me. Usually you contribute to many repositories all over github and even distributed over different repository hosting services.

**Comment by tarsius** [comment]
I am not actually saying the repository has to be transferred, by the way. IMO the available options are, in order of preference:

1. Transfer original repository to new organization account. Original author and maintainer both keep full access. Issues from temporary fork are merged into this repository.
2. Same but either original author drops out and/or issues are not merged.
3. Leave original repository where it is. New maintainer is given access. Issues from temporary fork are merged into this repository.
4. Same but issues are not merged.
5. Use new forked repository. Do **not** delete original repository, not now **or later**.
6. Use new forked repository. And now or eventually destroy history by deleting original repository.

**Comment by tarsius** [comment]
> @tarsius There is a simple alternative, which I would prefer and which avoids any hassle. This is simply adding @jcs090218 to the original origami repository by @gregsexton. This would work for everyone. While I understand that it is nice for @jcs090218 to have everything at one place, ultimately this does not seem very realistic to me. Usually you contribute to many repositories all over github and even distributed over different repository hosting services.

I agree that @jcs090218 should quickly give up on this idea.

But letting him avoid doing that is not why I proposed the above. (1) (and (5)) avoid deleting **either** set of existing issues. Keeping the issues from the fork is not very important IMO, but if you want to do a **perfect** transfer, then you would have to do that. **Realistically** I would suggest going with (2) or (4).

**Comment by jcs090218** [comment]
> If you want to do it perfectly, then it is a little complicated:

> 1. @gregsexton says that he is going to transfer the repository to @jcs090218.
> 2. @jcs090218 contacts github support to remove the link relationship from his fork. Last I checked users could not do that themselves and transferring is not possible without either doing this or deleting the fork.
> 3. Github does that and informs @jcs090218.
> 4. @jcs090218 informs @gregsexton.
> 5. @gregsexton transfers to @jcs090218.
> 6. @jcs090218 transfers each issue/pr individually and in numeric order from this detached fork to the upstream >repository, which is now located under his account.

I think the steps 2-3 can be avoided? My fork is under [jcs-elpa](https://github.com/jcs-elpa) and not my account [jcs090218](https://github.com/jcs090218). And steps 6 would be fine to me; there aren't much issues and PRs in the new fork. I can transfer it one by one.

> 1. Transfer original repository to new organization account. Original author and maintainer both keep full access. Issues from temporary fork are merged into this repository.

Yeah, this is what I was hoping. 😅

**Comment by minad** [comment]
@jcs090218 I read through the old thread #6716. Since the original maintainer has stated that he would like to keep his packages as is without adding new features, which is an acceptable stand point, I wonder if it wouldn't make more sense to do a fork under a new name instead. Melpa can continue to distribute the original package. At some point the decision could be made to delete origami from the package index if your new package has superseded it completely, but that step is optional. Has that possibility been considered?

**Comment by jcs090218** [comment]
> I wonder if it wouldn't make more sense to do a fork under a new name instead.

@minad Although this could be an option, I would probably say "no". Because changing the package name is much laborious than consider to two other options (to new location/transfer repo). And I disagreed with situation like a bunch of package with different distribution, `origami-1`, `origami-2`, and go on forever. The funny thing is, that was my backup plan if @gregsexton disagreed and not letting me change to the new fork. Yet once @gregsexton agreed I will not like to choose this plan B here. 😅 

> Since the original maintainer has stated that he would like to keep his packages as is without adding new features, which is an acceptable stand point,

I don't think @gregsexton said that he does not only want the new feature. I think he said he want to keep things small and stable. And I have mentioned this inside the email before he showed up in this thread. So I assumed @gregsexton is satisfy the changes I am making here and I guess that it is why he agreed. I told him that the core is the same and doesn't change much, and so the current version from my fork should fully compatible to the version from the original repository.

**Comment by riscy** [comment]
For the record I don't think any of the MELPA maintainers are unhappy with @gregsexton's maintainership.  #6716 mentions a namespace violation which should indeed be fixed, and the various other small nags in open PRs should be merged, but overall I think it is fine for a maintainer to have this attitude:

> I haven't stopped working on origami or httprepl. Both provide a core functionality that works well and I consider them stable.

I would strongly prefer option 1 that @tarsius mentions and agree with the ranking.  By "new organization account" I believe @tarsius means an organization called e.g. origami.el and owned by @gregsexton -- not jcs-elpa.  If this prevents @jcs090218 from being willing to maintain origami in the long term, he could seek out other maintainers to take over from there, and I imagine he'd be successful given origami's popularity.

**Comment by jcs090218** [comment]
> By "new organization account" I believe @tarsius means an organization called e.g. origami.el and owned by @gregsexton -- not jcs-elpa.

Okay, I think I misunderstood the meaning of "new organization account". From my current point of view, I would either do the following. 1. Transfer it to me so it's under `jcs-elpa`. 2. Update the recipe URL to `jcs-elpa`. 😅 I know it's unrealistic to have everything in one place. I am not saying I am not willing to do it, it's just I have too many organizations now and if I have a chance to denied a new account or new organization I would do that. Here I have a chance, so I will insist and try to grab this chance. Sorry for being a bit stubborn here. 😅 

Unless there is one or more people wanting to maintain this package together, then maybe? I mean this make a lot more sense to create an organization? If no one else is going to maintain this package, then I don't see the reason to create an organization. 😖 

> If this prevents @jcs090218 from being willing to maintain origami in the long term, we could seek out other maintainers to take over from there, and I imagine we'd be successful given origami's popularity.

But I see your point here.

**Comment by minad** [comment]
> I would strongly prefer option 1 that @tarsius mentions and agree with the ranking. By "new organization account" I believe @tarsius means an organization called e.g. origami.el and owned by @gregsexton -- not jcs-elpa. If this prevents @jcs090218 from being willing to maintain origami in the long term, we could seek out other maintainers to take over from there, and I imagine we'd be successful given origami's popularity.

I agree with this. I am not a melpa maintainer and don't even have any skin in the game here - I am not using origami, while I shortly considered a while ago, I did not, due to the unclear maintenance status. But it still somehow rubs me off the wrong way how @jcs090218 wants to proceed here.

1. @jcs090218 acts as if they already own this package in some sense.
2. @jcs090218 prefers jcs-elpa over contributing to the repository by @gregsexton, despite this being more of an accepted procedure and despite the preferences of the melpa maintainers.
3. @jcs090218 prefers jcs-elpa over a "neutral" organisation or over the established emacsorphanage, despite this being more of an accepted procedure and despite the preferences of the melpa maintainers.
4. If there is genuine interest in improving and contributing origami, it does not matter where the package is maintained.
5. Obviously 4. holds only in the case where the maintainer of the original repository allows access. However if for whatever reason
 the maintainer of the original repository does not do that (e.g. does not see the need to improve the package, has different opinions regarding maintenance or development plans, ...), then there is always the possibility of creating a completely distinct fork.

Overall I feel Melpa should not be the judge in such cases. But if for whatever reason Melpa wants to judge, I would also find it preferable to have a package maintained either as part of the established Emacs orphanage or as part of a hypothetical origami organisation or even do nothing.

**Comment by jcs090218** [comment]
Oh, god. This get so complicated. What I would say is I respect what @gregsexton decision, and @gregsexton accepted this PR. The order I am respecting is @gregsexton > `myself` > `melpa maintainers` > `others`. Since I consider this package as an adoption, I would like to manage the package the way I want. 😕 I think as long both myself and @gregsexton agreed, we should be fine.

**Comment by gregsexton** [comment]
This is a fork. I'm not looking for a maintainer or even a contributor.

I acknowledge that I'm not actively working on the package. As I've said before, the package is generally solid. I'll address major issues - I use this functionality daily. This is all a deliberate choice, I'm just prioritising other things right now.

I don't wish to transfer ownership. I would like to be able to take the code in any future direction I like, if, when, and how I want. I also don't want to add a maintainer. I don't want to spend time syncing with someone, sharing a vision, reviewing code etc.

@jcs090218 seems to care about Origami and wants to move it forward. That's cool, it's what sharing source is all about. I'm not trying to add friction.

The discussion here, which I do think melpa should be a judge in is: what is the best thing to distribute for users? I don't know @jcs090218 and have no idea what they want to do with the package. I looked at a few commits and they seem reasonable - I don't see any evidence of harm. 

I currently see two options to move forward. Let @jcs090218's fork be the source of truth for the package 'Origami' as distributed by melpa, or @jcs090218 should distribute under a new name.

I don't mind which direction you decide to go. They have different tradeoffs which you're best placed to prioritise. I'll abide by any decision the community makes that doesn't violate my stated desire to control my own fork. Is this reasonable?

I don't feel I have any right to expect anything from MELPA, and just want to thank you for the value you add to Emacs.

**Comment by jcs090218** [comment]
@gregsexton Thanks for your response!

I think @gregsexton say it all. Just to clarify, I would choose to update the recipe to new location, which is under `jcs-elpa`. I don't want to distribute it under a new name and I already stated my reasons above a few posts (scroll up). :wink:

**Comment by minad** [comment]
@jcs090218 As far as I see it, the name "origami" is taken in Melpa by @gregsexton's package, which is still his package and which should stay to be his package. Why is it not an option for you to chose a new name? Furthermore there is certainly a precendent for this exact situation, maybe not in the context of Melpa, but in the greater FOSS context, e.g., think of XEmacs vs Emacs.

**Comment by jcs090218** [comment]
@minad Instead of you questioning me. I am more curious about, why not? Is there a particular reason that you don't want me to take over origami? 😕 

> As far as I see it, the name "origami" is taken in Melpa by @gregsexton's package, which is still his package and which should stay to be his package.

I know origami is @gregsexton's package but he agreed with this PR. Am I missing something here? 😕 

> think of XEmacs vs Emacs.

I don't know XEmacs so I don't have a particular opinion on that. 😖

**Comment by minad** [comment]
> @minad Instead of you questioning me. I am more curious about, why not? Is there a particular reason that you don't want me to take over origami?

I would very much like to see you maintaining a fork of origami. But I think it would be better to continue the work under a different name, introducing a clear cut, clearly stating the reasons for the fork and describing the differences. I've looked at your repository yesterday and it seems you have put quite some good work into your fork which is appreciated. As I said, I am not using origami, but maybe I will do given a well-maintained fork exists.

**Comment by jcs090218** [comment]
> But I think it would be better to continue the work under a different name, introducing a clear cut, clearly stating the reasons for the fork and describing the differences.

I think there is a miscommunication here. I don't want to make a clear cut. I consider this fork as a continuous development/maintain fork. If I would want to make a clear cut I will do that in a different package. But instead of remaking the wheel, I have chose to pick up origami. Here are the reasons why,

1. There are multiple folding packages, I don't want to add another one.
2. Although I am not very satisfy with the code base, origami is the one I like

I can make my own folding package myself without origami. But this against reason (1).

> but maybe I will do given a well-maintained fork exists.

Thank you! I consider myself a better maintainer since @gregsexton isn't going to contribute more on open source projects. I mean my intention to open the issue #6716 is to make @gregsexton an active maintainer. I never thought @gregsexton will refuse. And I never thought I would have to pick up origami myself. 😅 I was even hoping someone else can take over it, so I can just use it. :smiling_imp: Unfortunately, this never happens. 😓

**Comment by tarsius** [comment]
@gregsexton I sympathize with your annoyance in #6716 and would like to apologize for contributing to that there and here again. I can also understand where the other side is coming from but I think in this case we have all been ignoring your opinion and interests too much and for too long.

This is why I brought up this topic among the Melpa maintainers two weeks ago, but I was too busy to follow up and did not get around to publicly communicating what we discussed before it was too late and things already took of here again.

I'll try to summarize now:

The Melpa maintainers do not wish nor have the authority to decide what constitutes a good maintainer. If the current maintainer wishes to keep their role (especially if they are the original author), then it is not up to us to overrule that decision. We sometimes bless a takeover if a maintainer has been missing in action for a long time but this is not the case here.

In an earlier attempt to summarize the discussion so far, at https://github.com/melpa/melpa/issues/6716#issuecomment-613122354, I stated that I would most likely support a fork. I am unsure whether I meant a fork under the original name or using a new name but now I can report that we Melpa maintainers would only support a takeover if @gregsexton wholeheartedly welcomed that.

While @gregsexton first statement in this thread taken by itself does not make it clear that he does not do that, earlier statements and especially this last one make it very clear:

> This is a fork. I'm not looking for a maintainer or even a contributor.

> I don't wish to transfer ownership. I would like to be able to take the code in any future direction I like, if, when, and how I want. I also don't want to add a maintainer. I don't want to spend time syncing with someone, sharing a vision, reviewing code etc.

You then go on to saying:

> I currently see two options to move forward. Let @jcs090218's fork be the source of truth for the package 'Origami' as distributed by melpa, or @jcs090218 should distribute under a new name.

> I don't mind which direction you decide to go. They have different tradeoffs which you're best placed to prioritise. I'll abide by any decision the community makes that doesn't violate my stated desire to control my own fork. Is this reasonable?

> I don't feel I have any right to expect anything from MELPA, and just want to thank you for the value you add to Emacs.

I appreciate that you leave the decision what Melpa should do to the *Melpa maintainers*. I hope I made it clear above that in making that decision we take the wishes of the *package maintainer* very serious. By distributing a fork we would effectively endorse that as the official version and, again, we don't think we should make that call when a package is still being maintained.

So our decision is to not support a takeover.

**Comment by minad** [comment]
@jcs090218

> I think there is a miscommunication here. I don't want to make a clear cut. I consider this fork as a continuous development/maintain fork. If I would want to make a clear cut I will do that in a different package. But instead of remaking the wheel, I have chose to pick up origami. Here are the reasons why,

I will stop communicating at this point. I stated my opinion and tried to be neutral here. The point is, there won't be a continuous development. There is already a cut. Despite you considering your fork as the true and worthy successor of the original "origami" it is not, since the original maintainer did not actually hand over his project to you. And this won't change if one redirects the link in Melpa to your fork. This is just bending the facts as I see it.

There is no problem in creating another fork under a different name or in creating a new package. It happens all the time and it is okay. In other language ecosystems which are less curated, e.g., Haskell, this happens much more regularly I suspect. For example there are some libraries which are considered very solid and which are widely used, e.g., the Haskell parser combinator library Parsec. Unfortunately it is also showing its age. I would not recommend anyone to use it for new projects, but it also does not make sense to throw it over board or turn it upside down. It will stay as is, only minor fixes will be applied in the future. It is okay like that. However for newer projects, the library has been superseded by other modernized libraries.
Within the context of Melpa it seems to me that at some point origami could be superseded by your new package and at that point, Melpa could decide to remove the original origami from the index leaving only your package.

**Comment by minad** [comment]
@tarsius Sorry, I did not see you already responded. Ignore my last comment.

**Comment by tarsius** [comment]
@jcs090218 to potentially have your fork added to Melpa you would have to rename it. (Using a new name, not something like "origami-2".) We have not yet decided whether we would add such a fork to Melpa in this case. It depends on how different it is from the original. If it only brought the package more in line with contemporary MELPA/Emacs lisp guidelines, then that probably not be enough. I haven't taken more than a cursory glance at the changes yet.

**Comment by jcs090218** [comment]
> Despite you considering your fork as the true and worthy successor of the original "origami" it is not, since the original maintainer did not actually hand over his project to you.

@minad Okay, I think I get your point. I don't really care much about the project authority thing (even with original author agreed?). I am here to keep origami alive. And if @gregsexton think my fork isn't right, he can change it back whenever if he wants to. 😕 But I am fine to change name if you really care about that instead of someone try to keep a project alive. May be I should not ever done that. 😓 

> to potentially have your fork added to Melpa you would have to rename it. (Using a new name, not something like "origami-2".) We have not yet decided whether we would add such a fork to Melpa in this case. It depends on how different it is from the original. If it only brought the package more in line with contemporary MELPA/Emacs lisp guidelines, then that probably not be enough. I haven't taken more than a cursory glance at the changes yet.

@tarsius This is not a design of a new package at all. I even said that I would like to keep fully compatible to @gregsexton's fork. So if @gregsexton want to use my fork from melpa it would not be any too much hassle. 😓 I can say 99% of core code doesn't change due to the compatibility. I have only added something else I consider bug fix, some features, etc. And these changes do not change the core. I wouldn't expect you to say, "Okay, let's add this", because this wasn't my intention.

---

I can rename this my fork to something else, but this package would have 80%-90% of code the same as origami. 😓 If this is not going to happens. I think I can just start a brand project without forking other people's repository. I don't even know why am I reading `origami`'s code...

If it's above conditions is fine, I can rename the package to something else.

**Comment by jpablobr** [comment]
While I can see why "origami-2" isn't a great name, mostly when the idea isn't (or doesn't seem to be) to enhance origami (at least feature-wise - kind of like what https://github.com/remyferre/comment-dwim-2 does), for these type of (fork) situations being able to keep the original name somewhere (if desired) adds a lot to the description of the project. Maybe "jcs-origami"?

**Comment by minad** [comment]
@jcs090218 @jpablobr I also thought about "jcs-origami". But maybe it also makes sense to use something distinct and take the chance to do breaking changes at this point. From my experience, projects accumulate some cruft over the years such that a general overhaul is sometimes appropriate.

**Comment by jcs090218** [comment]
I don't think I am proposing this anymore. This is just waste of time and not worth doing it.

So I am closing this PR. Thanks for everyone's participation!

**Comment by gregsexton** [comment]
Well, I didn't see things playing out like this! @jcs090218, you put in a bunch of work already. The policy has been made clear that you should release under a different name. Why not do that? I'm sure a healthy chunk of users would be happy to switch for the benefit of promised development. Seems a shame to abandon your efforts.

Thanks all for an interesting conversation. @tarsius, I really appreciate your empathy.

**Comment by jcs090218** [comment]
Yeah, I don't want thing turn out this way. I feel a bit hurt that I was just trying to make origami better and hopefully it benefits to origami's users. I am not proposing it anymore because I don't think people wanted me to take over origami; that's fine. If that's what people want, I respect to the community. Plus, I'm already happy having my own fork of origami! I don't see adding another package (new name) would help the community. 

In addition, there are something that ties to origami. For instance, I am using `lsp-origami`. Does that mean I need to create another package for my new package? As I said, I am already happy using my own fork of origami. It is laborious to do and there are a bunch of functions and variables I need to rename to the new name. 

There are just a bunch of reasons that do not make sense to me. Like the others, our subjective opinions conflict with each other. And I am trying to make everyone happy and see if I can benefit the Emacs community. I am not letting other people just to make me happy if my fork doesn't actually help the others. Thanks for people being kind to me, but I don't see people think this is helpful. And this is why I choose to close this issue.

And thanks again!

**Comment by minad** [comment]
I would proceed as follows:

1. Introduce a new name, rename all the functions. Ensure consistency.
2. Keep adding improvements such that at some point the package becomes a candidate for inclusion here (Maybe you already added enough for it to be viable, @tarsius seems to be undecided)
3. If there are packages bound to origami, suggest to the authors of those packages to create another version tied to your fork. Probably they will switch over if your fork has significant improvements over the original.

While I stated subjective opinions in this thread, I also tried to make it clear that the approach of forking under a new name or transferring ownership are more accepted approaches in the community (or in the open source community in general) for package takeover. I don't think this is purely subjective, rather normative. Just changing the link in the Melpa repository does not seem to be a standard approach and it is also not good for many reasons as is clear from this thread, but some of those reasons may be subjective.

**Comment by jcs090218** [comment]
@minad I fully understand your point here. I was saying, if me taking over origami doesn't benefits the community. I am not making a new package because I satisfy with my own fork. Plus it's a lot of work! I would like to stick to origami because it already serves me well! 

The conflict is, making a new package -> I waste my time reading code for origami because I don't need to. I also waste my time to keep my fork compatible to current fork. I waste my time and effort borrowing (forking) the code from origami if I was intend to make a brand new package and I know I don't need to. Do you see the conflict? 😕 

Hence, this is why I close this PR. I choose to do nothing. And keep everything as it! I am still happy with my own fork. ;)

**Comment by minad** [comment]
Ok that is fine!

**Comment by jcs090218** [comment]
Thanks for your understanding! 😄

**Comment by wyuenho** [comment]
What a great way to destroy people's motivation to contribute meaningful work to an important package. This is such a minor issue and somehow you could bikeshed it to death. Great job guys, you all must work well with colleagues at your companies. No wonder people are getting burnt out from doing open source.

**Comment by riscy** [comment]
@wyuenho You may have a point here, but this has been closed for almost a year.  And I was sort of disappointed to get a message like this that appears to be shaming me in my inbox.

If you want to follow this up and talk about ways we can reduce friction for contributors in the future, let's raise it in a new issue.

**Comment by minad** [comment]
> And I was sort of disappointed to get a message like this that appears to be shaming me in my inbox.
> 
> If you want to follow this up and talk about ways we can reduce friction
> for contributors in the future, let's raise it in a new issue.

I think @wyuenho's tone here is inappropriate and unjustified. Package
takeover in an authoritative package repository is not a minor issue. I
am glad that you @riscy opened a new issue to discuss a procedure for
package takeover.

I disagree with the approach taken here to take over origami without
clear consent by the original maintainer. I would not want my packages
being taken over for some reason as long as there are no clear rules for
the process. Furthermore as a user of MELPA packages I am putting trust
in the original maintainer and in MELPA to handle takeover processes
sensitively.

As I see it, a package takeover is justified if the original maintainer
cannot be reached for a long time and if there are open issues which
need urgent fixing. I would also consider takeover or dropping the
package from the repository to be justified when there are problematic
security issues and the original maintainer refuses or ignores patches
which fix the issues.

However if the original maintainer considers a package feature complete
or done, I am not sure if a takeover is justified. This is the case here
with origami. As has been pointed out, it is better to continue
maintenance of the package as a fork under a new name.

**Comment by wyuenho** [comment]
@riscy You are not even remotely close to being an offender here, there's no need to feel any shame.

> If you want to follow this up and talk about ways we can reduce friction for contributors in the future, let's raise it in a new issue.

I don't know about the future, the Emacs community has lots of long standing economical, procedural and personality issues that have long been talked about, but in this case the first step is to ignore @minad.

@minad Are you the package author? Are you a Melpa maintainer? Why are you offering the strongest opinion and most complicated solution to a problem that neither @gregsexton nor @jcs090218 have? As a mere package user, your opinion should count just as much as any other's, I see no reason why you should be let to add so much friction to this PR.

> I disagree with the approach taken here to take over origami without
clear consent by the original maintainer. 

Greg has already said twice he's fine with Jen-Chieh to take over the Melpa package URL, which is what this PR is about. If the concern is confusion, Greg can put a few sentences in the README to tell people the Melpa package is actually Jen-Chieh's fork. Problem solved. Is this perfect? Probably not, but it's the path to the least resistance. Since Greg is neither looking for a maintainer or major contributions, and he's not actively working on the package, and Jen-Chieh isn't looking to massively alter the direction of Origami, this seems to be the best way forward.

@jcs090218 I don't know if you are looking for a co-maintainer, you kind of hinted at it, I offer myself if you are.
@gregsexton I know there's already gregsexton/origami.el#99 , but are you okay with making it clear in the README to point people to Jen-Chieh's fork?

Are there anyone from Melpa against this? I know this is @tarsius 's preference 5), but I think we should honor the authors' wishes.

**Comment by tarsius** [comment]
I have locked this for now. We maintainers will talk about it and maybe reopen and make another statement.

**Comment by tarsius** [comment]
I have (once more) read the whole discussion and my main takeaway is that despite the very contradictory standpoints (and maybe except for the brief "you are rude" "no you are rude" intermezzo) everyone was being constructive and tried hard to respect opposing views. Tensions flared up a bit occasionally, but everyone realized we are in this together and we only have a chance to get to a satisfactory result if we collaborate. Despite all these good intentions we did not reach a satisfactory solution. No one got what they wanted and it is understandable that this left everyone a bit frustrated and it is perfectly okay that some expressed their frustration.

But IMO it is much more important that no bridges were burned.

This leaves open the door to maybe revisit the situation again at a later time. Maybe some standpoints have softened or we can find a compromise that had not occurred to us so far. That is just one reason why it is more important that we stopped the conversation on good terms even without a satisfactory result, than to force some solution but salt the earth.

If there is still interest in resuming the conversation, then I would recommend delaying it until the Melpa maintainers have clarified their position on package handovers. We have an open issue about that (#7739) but I feel we should probably first discuss this in private. This is going to take some time.

I would like to ensure everyone that we do not tolerate bullying behavior here and that you are welcome to contact us privately if you feel we failed to step in when things got out of hand.

Finally I want to address @wyuenho directly.

> This is such a minor issue

We the Melpa maintainers feel it is not a minor issue at all for us to bless a fork or to effectively define what constitutes good maintainership. We occasionally are forced to do so but we do so reluctantly and we always prefer for the involved parties to come to a mutually satisfying result, with our guidance if there is need for that, but still without us making the decision.

I have said as much before (https://github.com/melpa/melpa/pull/7215#issuecomment-740630342) but you just ignore that and call it a "minor issue" anyway. We don't think it is a minor issue how we use our influence and we strongly reject all attempts at bullying us into using our influence to get the results desired by an individual or group.

Everything else that you said (beside calling it a "minor issue")...

> What a great way to destroy people's motivation to contribute meaningful work to an important package. [...] somehow you could bikeshed it to death. Great job guys, you all must work well with colleagues in real life. No wonder people are getting burnt out from doing open source.

... is a personal attack. This crosses the line and we consider this bullying. This is not accepted and if you do it again you will be banned. Being the target of such attacks is one of the reasons why people turn away from open source, or any community really, and we want to make it very clear that we do not tolerate it.

> As a mere package user, your opinion should count just as much as any other's, I see no reason why you should be let to add so much friction to this PR.

And yet you think that you doing exactly that somehow is justified. @minad on the other hand has done nothing wrong. He always stayed civil and he constructively argued for what he considers the best path forward. This also goes for other participants in this conversation.

**Pull request closed without merging**
