### PR TITLE
Add php-cs-fixer recipe

### PR DESCRIPTION
**Pull request by pivaldi**
### Brief summary of what the package does

[php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) wrapper for the Emacs editor.

### Direct link to the package repository

https://github.com/OVYA/php-cs-fixer

### Your association with the package

I'am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [ x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x ] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x] My elisp byte-compiles cleanly
- [ x] `M-x checkdoc` is happy with my docstrings
- [ x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by rubenrua** [comment]
+1

**Comment by purcell** [comment]
Thanks. Quick feedback:
- Remove the URL and "for Emacs" from the initial description line of the package.
- Don't use `cl` -- use `cl-lib` instead, and declare a package dependency on `cl-lib` 0.5.
- The `defgroup` for the `php-cs-fixer` custom group is missing, and should be added.
- `php-cs-fixer--delete-whole-line` can probably be implemented using simply `(let (kill-ring) (kill-whole-line))`
- `php-cs-fixer-build-rules-options` docstring say "private method", so use the double-hyphen prefix, ie. `php-cs-fixer--build-rules-options`.
- [This top-level-code](https://github.com/OVYA/php-cs-fixer/blob/ed351cad77e954974130b6ed2bfc1a00a7bda6ea/php-cs-fixer.el#L219-L220) should be deleted: better to detect a missing executable at runtime, not load-time.

Hope that helps.

**Comment by FanchTheSystem** [comment]
+1

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
