### PR TITLE
recipes/simple-paren added

### PR DESCRIPTION
**Pull request by andreas-roehler**
;; Commands inserting paired delimiters.  These are are easy to extend
;; by just providing the delimiting characters as shown below with
;; math white square brackets

;; (defun simple-paren-mathematical-white-square-bracket (arg)
;;   "Insert MATHEMATICAL LEFT/RIGHT WHITE SQUARE BRACKETs

;; With \\[universal-argument] insert braces literatim."
;;   (interactive "*P")
;;   (simple-paren--intern ?⟦  ?⟧ arg)
;;   )

;; Examples, curor as pipe-symbol:

;; (defun foo1 |	==> (defun foo1 ()

;; |interactive		==> (interactive)

;; int|eractive		==> int(eractive)

;; With C-u keep padding
;; | foo		==> ( foo )

;; Suggested keys
;; (global-set-key [(super ?\()] 'simple-paren-parentize)
;; (global-set-key [(super ?{)] 'simple-paren-brace)
;; (global-set-key [(super ?\[)] 'simple-paren-bracket)
;; (global-set-key [(super ?')] 'simple-paren-singlequote)
;; (global-set-key [(super ?\")] 'simple-paren-doublequote)
;; (global-set-key [(super ?<)] 'simple-paren-lesser-then)
;; (global-set-key [(super ?>)] 'simple-paren-greater-then)

### Direct link to the package repository

https://github.com/your/awesome_package

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Please fill in the PR template above.

**Comment by andreas-roehler** [comment]
All answered with yes.

**Comment by andreas-roehler** [comment]
Being the only author. URL: https://github.com/andreas-roehler/simple-paren

Thanks for your care!

**Comment by purcell** [comment]
Thanks. Sent you https://github.com/andreas-roehler/simple-paren/pull/1 as an example of using a macro to reduce duplication.

There are currently [lots of packages](https://melpa.org/#/?q=pair) which deal with pairs and autowrapping, so I'd rather not add another if I can help it. Does this package provide anything those others don't?

**Comment by andreas-roehler** [comment]
AFAIU and features are related, these modes use electric-inserts.
Thats deliberately avoided - the command should never go into your way.
Also implementation is dead simple, thus trivial to extend.

**Comment by purcell** [comment]
Cool. I've removed the redundant :files spec from the recipe and merged it.

**Comment by andreas-roehler** [comment]
Great, thanks!

**Pull request merged**
