### PR TITLE
Add buffer-ring recipe

### PR DESCRIPTION
**Pull request by countvajhula**
### Brief summary of what the package does

[This is a companion PR to #7469 .]

[This package (written in 2009)](https://www.emacswiki.org/emacs/BufferRing) allows you to organize buffers in rings, and organize such rings in rings as well. It derives from the older MTorus package, but provides just the basics without any frills. There are other great packages that derive from MTorus, like [this recent one](https://github.com/chimay/torus) which looks great and seems to be very mature. Due to its minimalism, the present package is probably a good option especially for developers, if you need a buffer ring data structure to power some other functionality. I plan to use it in an upcoming package, [rigpa](https://github.com/countvajhula/rigpa).

### Direct link to the package repository

https://github.com/countvajhula/buffer-ring

### Your association with the package

I am volunteering to maintain this package, but I'm not the original author. See the [companion PR](https://github.com/melpa/melpa/pull/7469) for more details.

I've made a number of modifications to this package, including:

- supporting buffers being part of more than one ring
- bugfixes in deletion and search
- updating code to account for the additions and deprecations in dynamic-ring
- using lexical binding
- adding lots of tests!

### Relevant communications with the upstream package maintainer

See companion PR.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi @countvajhula - I haven't looked at this yet under the assumption that it's tied to the ongoing discussions in #7469.  Let me know if that's not the case, but in the meantime I will mark this one awaiting upstream.

**Comment by countvajhula** [comment]
Yup that's right @riscy . Would be better to wait to look at it until that's all worked out, and thank you.

**Comment by countvajhula** [comment]
This one is ready to go as well 👌

**Comment by countvajhula** [comment]
@riscy no rush at all, but bumping just in case it's off your radar since it still has the "awaiting upstream" tag.

Btw, unrelated specifically to this PR, I've been wondering about the MELPA twitter feed. I've noticed that it seems to tweet whenever a package is updated, but my other package [symex.el](https://github.com/countvajhula/symex.el) which is on MELPA never appears there, even though it does have tagged releases on github that also bump the Version header in the main elisp file. Is there something special I need to do for these packages to count as being "updated"?

**Comment by riscy** [comment]
Thanks for the bump, I do often filter out the 'awaiting-upstream' PRs and that's what happened here.  Here's a quick pass over the machine-detectable stuff:

### buffer-ring.el ###

byte-compile (using Emacs 27.1):
```
buffer-ring.el:271:1:Warning: Unused lexical argument `args'
```
Easy fix here I think -- just rename the variable to `_args` and the byte-compiler will know what's going on.

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210511.2055):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- buffer-ring.el#L170: It's safer to sharp-quote function names; use `#'`
- buffer-ring.el#L233: It's safer to sharp-quote function names; use `#'`
- buffer-ring.el#L45--58: Don't set global bindings; tell users how in your `;;; Commentary`.

The global bindings at the top of the file could potentially be placed in a minor mode keymap or just your Commentary, which gives users a chance to customize them (and not have this package overwrite their existing keybindings).

**Comment by countvajhula** [comment]
@riscy melpazoid looks really useful!

Thanks for pointing out those issues, those should be fixed now.

I set up a CI pipeline for these repos and added melpazoid to it. One weird thing is that the lint checker I configured manually from MELPA instructions some time ago [seems to be failing](https://github.com/countvajhula/buffer-ring/runs/2649015259?check_suite_focus=true#step:7:13
) for this package, but [melpazoid succeeds](https://github.com/countvajhula/buffer-ring/runs/2648991071?check_suite_focus=true). These are the errors I'm seeing there:
```
buffer-ring.el:9:38: error: Package dynaring is not installable.
buffer-ring.el:9:57: error: Package s is not installable.
buffer-ring.el:9:70: error: Package ht is not installable.
```

I'm assuming these messages are not really valid for some reason, since they don't show up when I run the checker locally...

I also occasionally (nondeterministically) see [this error](https://github.com/countvajhula/buffer-ring/runs/2648712613?check_suite_focus=true):
```
Missing dependency: "https://elpa.gnu.org/packages/let-alist-1.0.6.el: Bad Request", "Setting `package-selected-packages' temporarily since \"emacs -q\" would overwrite customizations
```
Not sure why this happens but once again, melpazoid doesn't run into any of these (and they don't show up locally) so maybe it's nothing to worry about? 🤷

**Comment by riscy** [comment]
> the lint checker I configured manually from MELPA instructions some time ago seems to be failing

Off the top of my head I can't recall where we have such a lint checker described, but the reason those are showing up is because it isn't adding MELPA to its `package-archives` variable.  melpazoid does this, and I bet you're doing it locally too which is why it succeeds for you.  That occasional/nondeterministic error is a puzzle to me though. :)

I notice one package-lint nag which may be relatively recent:
```
123:5: error: You should depend on (emacs "25.1") or the seq package if you need `seq-map'.
```
but otherwise this should be a quick merge.

**Comment by countvajhula** [comment]
I'm running the same command locally as on the GA job, and [this log](https://github.com/countvajhula/buffer-ring/runs/2650057951?check_suite_focus=true#step:7:12) seems to confirm that melpa is added to the `package-archives` variable. I admit I don't really have much of an idea how to go about debugging this, but I looked at the package-lint source for some inspiration and noticed [this dependency](https://github.com/purcell/package-lint/blob/f910d9912997230e3a34429265ee95b7c0dbec8e/package-lint.el#L10) looked familiar -- that `(let-alist "1.0.6")` dependency is the same one that it intermittently fails to find on GA, and it does fail at the package-lint install step:
```
 Missing dependency: "https://elpa.gnu.org/packages/let-alist-1.0.6.el: Bad Request", "Setting `package-selected-packages' temporarily since \"emacs -q\" would overwrite customizations
Contacting host: elpa.gnu.org:443
"
Package operations: 20 installs, 0 removals
  - Installing [ 1/20] ht (2.0)... downloading
  - Installing [ 1/20] ht (2.0)... done
  - Installing [ 2/20] dynaring (0.2.0)... downloading
  - Installing [ 2/20] dynaring (0.2.0)... done
  - Installing [ 3/20] flycheck (latest)... downloading
  - Installing [ 3/20] flycheck (latest)... done
  - Installing [ 4/20] package-lint (latest)... downloading
make: *** [Makefile:34: install] Error 255
Error: Process completed with exit code 2.
```
So, maybe it's just that ELPA intermittently becomes inaccessible?

But re: the `package is not installable` errors, would be nice to understand that but it's probably moot since melpazoid already runs package-lint so I could just remove that step from my workflow 🙈 .

I've addressed the lint error you found re: the `seq` dependency.

**Comment by countvajhula** [comment]
I googled `INIT_PACKAGE_EL` to see where I might have found that, and came across [this](https://github.com/purcell/package-lint/blob/f910d9912997230e3a34429265ee95b7c0dbec8e/run-tests.sh#L11-L12). I noticed it refreshed the package archive after running `package-initialize`, which my script wasn't doing. Adding this in caused the "package not installable" errors to go away! Not sure why it was working in `dynaring` and `symex` (problem was never encountered in either of these repos) but not `buffer-ring` (problem was _always_ encountered here), where they were all running basically identical scripts. But, at least it seems to be fixed now. I was just concerned that the error might be symptomatic of a genuine underlying problem, but I'll probably transition my workflow to just rely on melpazoid for this, once the dust settles and I don't notice any other disparities in the build results.

**Comment by riscy** [comment]
I'm glad that's sorted.  :)  I've run into similar rusty corners in the past.

**Comment by countvajhula** [comment]
🎉  Thanks!

**Pull request merged**
