### PR TITLE
Move package-build.el to a seperate repository and merge it as a subtree

### PR DESCRIPTION
**Pull request by tarsius**
In #3569 and #3570 we talked about moving `package-build.el` to a separate repository, without going into the details of how it can then be made available to the other build tools again.

I think it is best if we simply add the `package-build` repository as a subtree of the `melpa` repository. That way we don't have to worry about potential issues when fetching the latest version and we also explicitly track which revision was used at any given time.

I have created the filtered history as described at https://github.com/melpa/melpa/pull/3569#issuecomment-181034310 and pushed the result to https://github.com/tarsius/package-build.

If you decide to use this, then you should fork my `package-build` repository to `melpa/package-build`. Once you have done that I will delete my repository, making the latter the "root of the network".

Everyone who works on `package-build.el` and Melpa should then clone the `package-build` repository and then add that clone as a remote inside the Melpa repository:

```sh
cd /path/to/melpa/..
git clone git@github.com:melpa/package-build.git
cd melpa
git remote add package-build ../package-build
git fetch package-build
```

After making changes in the `package-build` repository, they can be imported into the Melpa repository using `make pull-package-build`.

### CODE REVIEW

**Comment by purcell** [comment]
Done. Thanks so much for putting this PR together. Let's see what breaks!

**Comment by purcell** [comment]
I guess we'll leave issues for package-build here for now, and only gradually move over to maintaining package-build separately at its new home.

**Comment by purcell** [comment]
Build's failing with an apparent load-path issue and I'm not sure why...

**Comment by tarsius** [comment]
I'll look into it.

**Comment by tarsius** [comment]
I forgot to adjust the path in the `package-build` recipe. Fixed in #4123. But that doesn't seem related.

The error must be in https://github.com/melpa/melpa/blob/8511dbe322a17e8fdf2bb433def776756ce0e9ed/run-travis-ci.sh#L13. But your abb42a067451fbf0720ce2dd571b2c787c30b528 should address that. I haven't gotten any further than that yet.

**Comment by tarsius** [comment]
Uh, wait... that fix is broken... having high hopes for https://travis-ci.org/melpa/melpa/builds/151783986.

**Comment by tarsius** [comment]
Okay, now on to the bigger issue: you should not have squashed. `git subtree` needs the merge commits that it creates.

I have rerolled the changes since you squashed my commits. I have cherry-picked the various recipe commits and since history had to be rewritten anyway I have integrated the various path adjustment fixup commits into "Move package-build.el to a separate repository".

The result is in `tarsius/master`. I think you should hard reset `master` to `tarsius/master` as soon as possible and then force push. If any contributors are having issue due to the reset, then I can help with that. But I don't think we really have a choice here.

**Comment by tarsius** [comment]
Pending https://travis-ci.org/tarsius/melpa/builds/151791773

**Comment by purcell** [comment]
> I think you should hard reset master to tarsius/master as soon as possible and then force push.

Done. That makes sense. Thanks for figuring this out. The squash was the default when merging via Github, since we typically squash recipe PRs... sigh.

**Comment by tarsius** [comment]
You are welcome!

**Comment by purcell** [comment]
If it's okay with @milkypostman I'd quite like to add you as a MELPA committer, not that I'd expect you to be actively working on this project, but because I have a lot of faith in your judgement and attention to detail.

**Comment by tarsius** [comment]
I would very much appreciate that, thanks.

**Comment by milkypostman** [comment]
Sounds fine with me.

**Comment by milkypostman** [comment]
is there any issue with just separating these packages eventually? I feel like we could just check the recipes out into their own directory and just have the scripts update the root and the packages?

both submodules and subtrees seem to be annoying, 

```
git clone package-build
cd package-build
git clone recipes
```

i'm fine with this for now too because I do appreciate your work on this, I just assumed the scripts would go with package build.

i'm also OK if we have a `toolchain` repo that only contains everything besides the recipes.

so 

```
git clone toolchain
cd toolchain
git clone package-build
git clone recipes
```

thoughts? also I don't really care about bloated history that much but filtering is fine too.

**Comment by milkypostman** [comment]
oh, and we could just rename *this* repo to `recipes` and then move all the recipes to the root of the repo. but just ideas.

**Comment by purcell** [comment]
Cool. I've added @tarsius to the MELPA org, and as a collaborator on the 2 repos. Yay!

Regarding what should live where, I'd ultimately like to get `package-build.el` out of the MELPA repo entirely, such that the MELPA repo would bootstrap itself at build time by installing the MELPA package of `package-build`, or directly grabbing it from git. We'll need to move recipe format docs to the package-build repo ultimately. Recipes themselves could live in a separate repo. And some of `package-build.el` is specific to MELPA, e.g. the default directory paths, but also the `shields.io` badge image stuff, so we should move that to a separate `melpa.el` or similar in this repo IMO. I'm not in a super hurry to do any of that.

**Comment by tarsius** [comment]
> Cool. I've added @tarsius to the MELPA org, and as a collaborator on the 2 repos. Yay!

Weeeeeee!

> not that I'd expect you to be actively working on this project

I've started labeling issues, because I think it helps a lot to see what areas need work and how much. (Then, depending on your mood, you can concentrate on the areas that need the most work *or* one where you actually have a change to "get done" in a usable time frame, for example.)

* I would like to add a `build` label distinct from the existing `website`. The former would be used for things like #4113 and the latter for #3818.

* I have alread added a `version` label for all the discussions about version schemes. This subject keeps coming up, usually without proper review of past discussions. Labeling might help here. And I *still* intend to work on that eventually myself. Not having to hunt down the relevant discussions yet once more when I have another look, might help motivate me to do so.

**Comment by tarsius** [comment]
@purcell, @milkypostman I have made my Melpa membership public. You should probably do the same, which you can do at https://github.com/orgs/melpa/people.

**Pull request merged**
