### PR TITLE
Add recipe for light-dashboard

### PR DESCRIPTION
**Pull request by ichernyshovvv**
### Brief summary of what the package does

Simple dashboard that might be used as a desktop or startup screen.

### Direct link to the package repository

https://github.com/ichernyshovvv/light-dashboard

### Your association with the package

Author

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.

Off the bat I recommend that `light-dashboard-open` be written in such a way that its return value is the "light dashboard" buffer.  This would let users config their `initial-buffer-choice` (as defined in the builtin startup.el) to point to the `#'light-dashboard-open` function (or even better, just `#'light-dashboard`).

Also while I'm here, at light-dashboard.el#L87: `concat` may be unneeded; `insert` can take multiple arguments

**Comment by ichernyshovvv** [comment]
Thanks, [added](https://github.com/ichernyshovvv/light-dashboard/commit/439140fcbfb4fc8b60e97b5e4cabc0988bee600c) `light-dashboard` function that could be used as a value for `initial-buffer-choice`, removed unnecessary concat

**Comment by ichernyshovvv** [comment]
Please don't merge it yet. I'm in the process of applying some major changes. Thanks for the review.

**Comment by ichernyshovvv** [comment]
Hi.

We've made a lot of improvements to the package. The code is much cleaner and now it's compatible with at least Emacs 27. Also, we've changed the name and from now it resides [here](https://github.com/ichernyshovvv/enlight).

**Comment by riscy** [comment]
Thank you!  Everything checks out here - merging.

**Pull request merged**
