### PR TITLE
Added recipe for zetteldesk

### PR DESCRIPTION
**Pull request by Vidianos-Giannitsis**
### Brief summary of what the package does

Zetteldesk.el exposes a workflow where you select buffers and org-roam nodes from a completion menu and filter generic functions such as switch-to-buffer and org-roam-node-find to show only the things you selected. Then it allows you to insert their contents in a seperate buffer and make an outline of the topic in question. Its an org-roam implementation of something mentioned in "How to Take Smart Notes".

### Direct link to the package repository

https://github.com/Vidianos-Giannitsis/zetteldesk.el

### Your association with the package

I am the author and maintainer of the package

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`zetteldesk.el` with byte-compile using Emacs 27.1:
```
zetteldesk.el:113:1:Warning: global/dynamic var `zetteldesk' lacks a prefix
```

`zetteldesk.el` with package-lint 20220412.1648:
```
4 issues found:
63:0: error: "org-roam-node-poi-or-moc-p" doesn't start with package's prefix "zetteldesk".
68:0: error: "org-roam-backlink-query" doesn't start with package's prefix "zetteldesk".
81:0: error: "org-roam-backlink-query*" doesn't start with package's prefix "zetteldesk".
95:0: error: "org-roam-node-sort-by-backlinks" doesn't start with package's prefix "zetteldesk".
```

Other notes:
- zetteldesk.el#L209: You can just use `if buffer`
- zetteldesk.el#L245: Same
- zetteldesk.el#L285: Same
- zetteldesk.el#L374: Loading a package should rarely add hooks (and I actually don't think any `'zetteldesk-mode-on-hook`  hook will exist anyway; the minor mode should create a hook called `zettel-desk-mode-hook` instead)

Package and license:
- Prefer the default recipe or `:defaults`, if possible.

**Comment by Vidianos-Giannitsis** [comment]
Hello,

So I explicitly left the byte-compile and package-lint errors in because I wanted to ask you about them as this is my first time contributing to such a project and didn't know how else I could contact someone.

On the byte-compile error, what is exactly the issue on having a variable named zetteldesk. I don't mind changing it, but out of curiosity and for future reference I would be interested to know what the issue is.

For the package-lint errors, these 4 functions don't have the prefix zetteldesk as they are functions that build on top of org-roam (some of them were even in my config for other purposes as well) and not specific to zetteldesk.el, but some of the package's functionality then needs them. Is it generally a bad practice to name these functions as such and if so why? 

On the 3 notes about using `if buffer`, you are right, I genuinely don't know why I didn't think of it, its simpler. For the hook one, I thought the define-minor-mode macro creates these hooks anyways, and the fact that they worked ensured me that's the case. But I checked the hook and it does not have a doc string so I suppose that's what you mean. Should I make a defcustom for it so it has documentation or did I misunderstand your statement? And for the on-hook, I preferred that as the command creates a new buffer, so there is no point in creating that when the mode turns off. If there is a problem with that I can hook it in the zetteldesk-mode-hook.

For the recipe, I tried to follow the example on the MELPA README, for multiple packages in the same repository as that is my case. Is something I put unnecessary? Because I think with defaults, it would consider zetteldesk.el and the other optional packages I have for it as the same package, which is not really the desired behaviour.

Finally I wanted to ask, something not related to this pull request but the package in general. I tried these checks on the keybindings extension of the package so I can commit that as well, when done with the main package and due to it using hydras, some docstrings of the larger functions are over 80 characters. But since those are automatically generated by the hydra's definition how can I change them (if you know)? Or is it not an issue in that case?

Thanks a lot for your time looking at the package and I am sorry for asking so many questions. I am just really new to this (its my first ever contribution to a project, let alone one as large as MELPA) so I just have a lot of questions. Hope its not too much of a burden to answer them. Will get back to you once I look at your other comments as well and will fix them when I have time. 

Kind Regards, 
Vidianos

P.S. I sent this via email on Monday, but I just noticed it was never sent due to checking out of curiosity why there has been no reply yet. I have had a hectic schedule after the Easter break (which in my country ended Monday) and haven't had any time to check before now. At least this email issue allowed me to address the Other Notes section better, which I was planning to check when I found the time. So sorry for the delayed answer

**Comment by riscy** [comment]
Hi!  If I miss any questions please forgive me and just ask them again, I won't mind.

> what is exactly the issue on having a variable named zetteldesk

I don't know the official reason, but suppose a package like `s` defined a global variable called `s`, and just imagine the problems that would create.  It's true `zetteldesk` is a unique sounding word, but it's still global and it lacks a namespace (where the byte-compiler is detecting "namespaces" by looking for hyphens).

While I'm here, I haven't traced fully through the code, but using `(default-value 'zetteldesk)` to fetch the string "default" is misusing the `defcustom` system, which is intended for user customizations, not for production elisp code; probably you want to `defconst` that default value or revisit the implementation.

> Is it generally a bad practice to name these functions as such and if so why?

Yes -- this is not your package's namespace.  It may feel inconvenient, but a simple and fair way to prevent namespace collisions across MELPA (and hopefully elsewhere) is to ask that the package, variable names, and function names all use the same prefix.  In very rare cases I would make exceptions to this rule (e.g. backward compatibility with a package predating this rule) -- and `package-lint` has some of these exceptions built into it.

> Should I make a defcustom for it so it has documentation or did I misunderstand your statement?

As far as I can see, no code is reading `zetteldesk-mode-on-hook` so whatever hooks you add to that are never going to be executed.  When you define a minor mode with `define-minor-mode`, a variable called `zetteldesk-mode-hook` is defined and this is the one that is read when the mode turns on.  **BUT** if you want to do something when the mode turns on, you should use the BODY parameter of `define-minor-mode`.

> for multiple packages in the same repository as that is my case

If you have multiple packages in one repo, all good.  Disregard my comment. :)

No worries about the delays in replying; I'm similarly only here on weekends.

**Comment by Vidianos-Giannitsis** [comment]
Ok, thanks for the clarifications, I fixed them in [this](https://github.com/Vidianos-Giannitsis/zetteldesk.el/commit/f744f35ab96263a94e6fc9181e399c6607cf7537) commit. However, I would suggest looking at the master branch ideally because I made some other fixes as well (although I am pretty sure I did all the above in the one linked and master just has these fixes in the other extensions and updating the documentation).

I believe everything is fixed now, but if there is something missing please inform me. Will be opening a pull request for the package's extensions for upload when this is done. 

But since I am here, I want to ask you one more thing for my package's default keybindings. So I have an extension for implementing these as I don't like people who force you into them (you can view it [here](https://github.com/Vidianos-Giannitsis/zetteldesk.el/blob/v1.0.0/zetteldesk-kb.el) if you have the time). Thing is I want to add keybindings for the other extensions I have, without making one of the two rely on the other. The first thing that came to mind is using the `with-eval-after-load` macro, but I saw that its not supposed to be used in packages. For now I just left the code for adding those in the Wiki as I couldn't find a "correct" way of doing this and it would feel weird I think to have multiple keybindings packages. However, I wanted to ask, is there any way to do something like this (evaluate the code only if the other extension is loaded) that is meant to be used in a package?

Thanks again for all the help!

**Comment by riscy** [comment]
> is there any way to do something like this (evaluate the code only if the other extension is loaded) that is meant to be used in a package?

This is a hard question to give a general answer to.  You could check out functions like `featurep`, or folks sometimes use forms like `(when (require 'optional-package nil t) ...)`.  But what you're doing right now -- leaving the code in the wiki or even the `;;; Commentary` when appropriate -- is a great way to do things.  Emacs users don't need to have their hands held too much, and their Emacs will be easier to debug if these sorts of fine-tuned configuration options are inside their config instead of lurking invisibly inside `add-hook` and `eval-after-load` forms which could end up being evaluated in any order.

This looks ready to go, though!  Happy to merge -- and welcome to MELPA. :)

**Comment by Vidianos-Giannitsis** [comment]
Yeah, I can definitely see what you mean. In the start I made the keybindings extension as from my experience its good for the author to provide a ready experience for keybindings as it helps you learn the package more and from there on it made sense to add to those keybindings the commands of the other extensions.

But yeah, its not so necessary for the package to add these on its own. Most Emacs people can figure this out on their own.

Anyways, thanks for answering all my questions and helping me contribute to this project. I am happy to be a part of this!

**Comment by Vidianos-Giannitsis** [comment]
Hello,

So I explicitly left the byte-compile and package-lint errors in because I
wanted to ask you about them as this is my first time contributing to such
a project and didn't know how else I could contact someone.

On the byte-compile error, what is exactly the issue on having a variable
named zetteldesk. I don't mind changing it, but out of curiosity and for
future reference I would be interested to know what the issue is.

For the package-lint errors, these 4 functions don't have the prefix
zetteldesk as they are functions that build on top of org-roam (some of
them were even in my config for other purposes as well) and not specific to
zetteldesk.el, but some of the package's functionality then needs them. Is
it generally a bad practice to name these functions as such and if so why?

I will look on the others more closely when I have the time (hopefully
tomorrow) but from a brief glance, on the hook one, aren't the hooks
zetteldesk-mode-hook, zetteldesk-mode-on-hook and zetteldesk-mode-off-hook
created from the define-minor-mode macro? That's what I thought. But if I
need to explicitly define them, there's no problem, I just thought they'd
already been created.

One last thing I wanted to ask, is I tried these checks on the keybindings
extension of the package so I can commit that as well, when done with the
main package and due to it using hydras, some docstrings of the larger
functions are over 80 characters. But since those are automatically
generated by the hydra's definition how can I change them (if you know)? Or
is it not an issue in that case?

Thanks a lot for your time looking at the package and I am sorry for asking
so many questions. I am just really new to this (its my first ever
contribution to a project, let alone MELPA) so I just have a lot of them.
Hope its not too much of a burden to answer them. Will get back to you once
I look at your other comments as well and will fix them when I have time.

Kind Regards,
Vidianos

**Comment by riscy** [comment]
Please excuse me if I missed answering any questions.  You also may want to raise these as repo issues for the community to answer because I might be unlikely to see your followup questions here.

> On the byte-compile error, what is exactly the issue on having a variable
> named zetteldesk. I don't mind changing it, but out of curiosity and for
> future reference I would be interested to know what the issue is.

I think I answered this question above, but I'll paste: I don't know the official reason, but suppose a package like s defined a global variable called s, and just imagine the problems that would create. It's true zetteldesk is a unique sounding word, but it's still global and it lacks a namespace (where the byte-compiler is detecting "namespaces" by looking for hyphens).

> For the package-lint errors, these 4 functions don't have the prefix zetteldesk ... Is it generally a bad practice to name these functions as such and if so why?

I'm assuming you're referring to the 4 functions in the first pass, but they aren't present in the current version of your package.  Yes, it's discouraged.  It may feel inconvenient, but a simple and fair way to prevent namespace collisions across MELPA (and hopefully elsewhere) is to ask that the package, variable names, and function names all use the same prefix.  In very rare cases I would make exceptions to this rule (e.g. backward compatibility with a package predating this rule) -- and `package-lint` has some of these exceptions built into it.

> But since those are automatically generated by the hydra's definition how can I change them (if you know)?

I'm not familiar with that package; you may want to raise that issue with the hydra package maintainer if it's generating code that's causing undue warnings.

**Pull request merged**
