### PR TITLE
Add recipe for symbol-overlay.el

### PR DESCRIPTION
**Pull request by wolray**
### Brief summary of what the package does

Highlighting symbols with keymap-enabled overlays

### Direct link to the package repository

https://github.com/wolray/symbol-overlay/

### Your association with the package

Creator and maintainer

### Relevant communications with the upstream package maintainer

None

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
`package-lint` says:

```
24 issues found:

226:1: error: "so-query-replace-s" doesn't start with package's prefix "symbol-overlay".
218:1: error: "so-query-replace" doesn't start with package's prefix "symbol-overlay".
205:1: error: "so-jump-s" doesn't start with package's prefix "symbol-overlay".
194:1: error: "so-jump-call" doesn't start with package's prefix "symbol-overlay".
177:1: error: "so-jump-to-def" doesn't start with package's prefix "symbol-overlay".
171:1: error: "so-jump-prev" doesn't start with package's prefix "symbol-overlay".
165:1: error: "so-jump-next" doesn't start with package's prefix "symbol-overlay".
158:1: error: "so-remove-s" doesn't start with package's prefix "symbol-overlay".
152:1: error: "so-remove-all" doesn't start with package's prefix "symbol-overlay".
142:1: error: "so-put" doesn't start with package's prefix "symbol-overlay".
128:1: error: "so-count-s" doesn't start with package's prefix "symbol-overlay".
101:1: error: "so-put-s" doesn't start with package's prefix "symbol-overlay".
94:1: error: "so-get-s" doesn't start with package's prefix "symbol-overlay".
92:1: error: "make-variable-buffer-local" doesn't start with package's prefix "symbol-overlay".
89:1: error: "so-def-function" doesn't start with package's prefix "symbol-overlay".
79:1: error: "so-colors" doesn't start with package's prefix "symbol-overlay".
77:1: error: "make-variable-buffer-local" doesn't start with package's prefix "symbol-overlay".
76:1: error: "so-keywords-alist" doesn't start with package's prefix "symbol-overlay".
64:1: error: "so-overlay-map" doesn't start with package's prefix "symbol-overlay".
62:1: error: "cl" doesn't start with package's prefix "symbol-overlay".
61:1: error: "thingatpt" doesn't start with package's prefix "symbol-overlay".
99:7: error: You should depend on (emacs "24.3") if you need `user-error'.
1:1: error: package.el cannot parse this buffer: Package lacks a "Version" or "Package-Version" header
1:1: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
```

**Comment by wolray** [comment]
Except those prefix and version errors, all errors found by `package-lint` are fixed in the latest commit.

**Comment by alphapapa** [comment]
I don't understand; every one of those errors is a prefix or version error.

Please fix the prefix errors.  That check was added for a reason.  :)

**Comment by purcell** [comment]
Yep, latest commit still shows a bunch of `so-*` symbol names. Did you forget to push your fix for that?

**Comment by wolray** [comment]
Yes, I understand the importance of adding a prefix to all newly defined symbols in the package. I just thought that a "so-" as the abbreviation of "symbol-overlay-" is OK, too.

However, I will fix that ASAP. Thanks for your reminder. :)

**Comment by purcell** [comment]
Great, thanks. If you think about it, 2-character prefixes only allow maybe 36x36 unique combinations (including digits). Better to use longer ones, then, and the package name is good practice. :-)

**Comment by wolray** [comment]
The prefix and version errors have been fixed.

I have re-checked the package using `package-lint`, `checkdoc` and `byte-compile-file`. No more errors were found.

**Comment by purcell** [comment]
Awesome, thanks!

**Pull request merged**
