### PR TITLE
Added muze-mode recipe.

### PR DESCRIPTION
**Pull request by ACov96**
### Brief summary of what the package does

This package provides syntax highlighting and basic indentation support for the Muze programming language.

### Direct link to the package repository

https://github.com/ACov96/muze-mode

### Your association with the package

I am the author and current maintainer of the package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings

```
 muze-mo…   225   4 error           You should depend on (emacs "25.1") if you need `font-lock-ensure'. (emacs-lisp-package)
```

**Comment by riscy** [comment]
I'll mark this awaiting upstream, because that's a legitimate package-lint fix.

I'd also suggest:

- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Minor, but it might be worth adding the muze link to your repo's README too.
- Should you be doing anything like the following? (I don't know what the standard extension is)
```elisp
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.mz\\'" . muze-mode))
```
- Also minor, but the notes in your commentary:
```
;; This is a major mode to go alongside the Muze language project.  None
;; of use are Elisp gurus, so forgive any weirdness you might see.  We don't
;; know why it's like this either...
```
... are going to appear on MELPA (such as [this one for bazel-mode](https://melpa.org/#/bazel-mode)), and that informal note about not being a guru is probably unnecessary. :)  I'd suggest a list of features (e.g. the code you've written for indentation, etc.), a description of what Muze is since it's an unusual language, that sort of thing.

**Comment by purcell** [comment]
Other notes:
- You'll want to at least `;;;###autoload` the major mode definition
- [Here](https://github.com/ACov96/muze-mode/blob/ce3514d2ad12aa7d8ed4b9b61a28505a4ccc789e/muze-mode.el#L185-L190) you'll generally end up unnecessarily calling `muze-first-word` many more times than necessary, so you should streamline that.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by tarsius** [comment]
Closing. Please ask us to reopen once you are ready.

**Pull request closed without merging**
