### PR TITLE
add recipe for heaven-and-hell

### PR DESCRIPTION
**Pull request by valignatev**
### Brief summary of what the package does

When it's lightly outside, light theme easier on the eyes, and dark theme is better when it's night.
This package allows to quickly switch between dark and light themes. At a single keypress. 

### Direct link to the package repository

https://github.com/valignatev/heaven-and-hell

### Your association with the package

I am a creator and maintainer of this package

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! This looks useful. Sorry for the slow response - here's some quick feedback:

- You should remove `:files` from the recipe. The default is fine, and you shouldn't include README.md inside the Emacs package. Any relevant documentation should go in the `;;; Commentary:` section of the main elisp file.
- `#'wombat` should be `'wombat`. It's not a function.
- `eval` shouldn't be necessary at all.
- "emacs" shouldn't appear in the name of variables or functions you define. It's all emacs code! :-)
- You can use `custom-set-variables` to set and apply the enabled themes more robustly, rather than trying to call `load-theme` with `t` at the right time. Here's some [similar code I've been using for years](https://github.com/purcell/emacs.d/blob/master/lisp/init-themes.el) to do the same thing. Similarly with your reset function, you can just use `custome-set-variables` to set `custom-enabled-themes` to `nil`.
- Emacs supports having multiple themes enabled simultaneously, and your code does not allow for that. Maybe just add/remove the light/dark themes from `custom-enabled-themes` as needed.

**Comment by valignatev** [comment]
Hi @purcell, thanks a LOT! I've learned a big ton about emacs theme system thanks to you. I've tried to improve the quality of `heaven-and-hell` according to your feedback, hope it's good enough now.

P.S. If only npm had that quality bar :smile:

**Comment by purcell** [comment]
Great!

> P.S. If only npm had that quality bar

I don't know if I'd scale to the size of the Javascript community! :-)

**Comment by purcell** [comment]
Anyhow, merged - welcome to MELPA! :tada:

**Pull request merged**
