### PR TITLE
Add recipe for robot-log

### PR DESCRIPTION
**Pull request by Apteryks**
### Brief summary of what the package does

Major mode for viewing RobotFramework debug log files.

### Direct link to the package repository

https://git.sr.ht/~apteryx/emacs-robot-log

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them
      ^ I don't know what that means.

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.

The final checklist item is a "joke" to see whether people just checked all the boxes without carefully reading. You "passed" by not checking that one. :)

Here's a quick first pass --

`robot-log.el` with package-lint 20220607.738:
```
4 issues found:
367:5: error: You should depend on (emacs "28.1") if you need `named-let'.
437:15: error: You should depend on (emacs "28.1") if you need `named-let'.
476:12: error: You should depend on (emacs "28.1") if you need `named-let'.
478:21: error: You should depend on (emacs "28.1") if you need `named-let'.
```

`robot-log.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- robot-log.el#L8: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- robot-log.el#L519: Terminate auto-mode-alist entries with `\\'`
```

**Comment by Apteryks** [comment]
Hi!

> Thanks for this.
> 
> The final checklist item is a "joke" to see whether people just checked all the boxes without carefully reading. You "passed" by not checking that one. :)

Haha!  I'm glad I passed the test.

> Here's a quick first pass --
> 
> `robot-log.el` with package-lint 20220607.738:
> 
> ```
> 4 issues found:
> 367:5: error: You should depend on (emacs "28.1") if you need `named-let'.
> 437:15: error: You should depend on (emacs "28.1") if you need `named-let'.
> 476:12: error: You should depend on (emacs "28.1") if you need `named-let'.
> 478:21: error: You should depend on (emacs "28.1") if you need `named-let'.
> ```

Ah, I had used `emacs-package-lint` in Guix at version 0.16, which is the latest *released* version, but not the latest commit, as MELPA seems to be shipping.

> `robot-log.el` with [melpazoid](https://github.com/riscy/melpazoid):
> 
> ```
> - robot-log.el#L8: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
> - robot-log.el#L519: Terminate auto-mode-alist entries with `\\'`
> ```

I believe I've fixed these in the latest commit in the upstream repo: https://git.sr.ht/~apteryx/emacs-robot-log.

Thanks for taking a look!

**Comment by riscy** [comment]
Thanks, that puts the easy checks behind us.  Looking a little more closely I have a couple more bits of feedback:

Calling `(robot-log-configure-keymap robot-log-mode-map)` every time the mode is activated seems like it risks overwriting user customizations.  Probably what you want to do is to just defvar the keymap once and for all before you define the mode,
```elisp
(defvar robot-log-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "n") ...
```

Rather than `(and arg (= 0 arg) (user-error "Arg cannot be 0"))` you can just write `(if (zerop arg) ...` or `(if (eq arg 0) ...`

I believe the line `(provide 'robot-log)` is appearing twice, probably a copy/paste error.

Whenever I see a pattern like:
```elisp
                      (if (not pos)
                          (progn
                            (robot-log-next-error (if (< arg 0) -1 1))
                            (next (if (not (robot-log-handled-p))
                                      (point)
                                    nil)))
                        pos)
```
I immediately think about flipping the conditional, `(if pos ...)` which would let you drop the `progn`.

Except for the keymap issue I would say these are all relatively minor.  Should be a quick merge after.

**Comment by Apteryks** [comment]
Hello, and thank you for the more deep review of the code! I believe I've addressed these in the last commit 26da475, which I also tagged 0.1.4.  Thanks!

**Comment by riscy** [comment]
Looks good - thanks!

**Comment by Apteryks** [comment]
Thanks for the review and merge, @riscy !

**Pull request merged**
