### PR TITLE
add consult-gh-embark

### PR DESCRIPTION
**Pull request by armindarvish**
-------

### Brief summary of what the package does

Adds embark actions for consult-gh (recently merged in #9118)

### Direct link to the package repository

https://github.com/armindarvish/consult-gh

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Checklist looks great, but I see this package does:

```elisp
(add-to-list 'embark-default-action-overrides '(consult-gh-repos . consult-gh-embark-default-action))
(add-to-list 'embark-default-action-overrides '(consult-gh-issues . consult-gh-embark-default-action))
(add-to-list 'embark-default-action-overrides '(consult-gh-prs . consult-gh-embark-default-action))
(add-to-list 'embark-default-action-overrides '(consult-gh-files . consult-gh-embark-default-action))
(add-to-list 'embark-default-action-overrides '(consult-gh-codes . consult-gh-embark-default-action))
```
at the top-level, at load-time.  We usually want to put these kinds of environment modifications behind a setup action, e.g. enabling a mode, to prevent surprises to users.  Less importantly, you should also consider what will happen if someone unloads your package, e.g. `(unload-feature 'consult-gh-embark)` - will `consult-gh-repos` still work?

**Comment by armindarvish** [comment]
@riscy Thanks for the comments. Here is my response:

> I see this package does:
(add-to-list 'embark-default-action-overrides '(consult-gh-repos . consult-gh-embark-default-action))
(add-to-list 'embark-default-action-overrides '(consult-gh-issues . consult-gh-embark-default-action))
(add-to-list 'embark-default-action-overrides '(consult-gh-prs . consult-gh-embark-default-action))
(add-to-list 'embark-default-action-overrides '(consult-gh-files . consult-gh-embark-default-action))
(add-to-list 'embark-default-action-overrides '(consult-gh-codes . consult-gh-embark-default-action))
>
> at the top-level, at load-time. We usually want to put these kinds of environment modifications behind a setup action, e.g. enabling a mode, to prevent surprises to users.

I understand the concern, but in this case, we are changing the default embark actions for minibuffer completion candidates of **only consult-gh**, which is defined by the categories such as `consult-gh-repos` (car of the cons in the code above). I don't see what would be the surprise, if the `consult-gh-embark` package changes embark actions for consult-gh since that's what it is supposed to do, and there are no changes to anything outside consult-gh specific categories!
To me introducing a minor-mode does not make a lot of sense because all this package is doing is adding embark actions specifically for consult-gh candidates and as far as I know, embark itself does not define a minor-mode for each category either.

> Less importantly, you should also consider what will happen if someone unloads your package, e.g. (unload-feature 'consult-gh-embark) - will consult-gh-repos still work?

Yes, the core consult-gh functions do not depend on the embark actions. If somebody unloads `consult-gh-embark`, the consult-gh commands work as expected. Calling `embark-act` when the cursor is specifically on a consult-gh candidate in the minibuffer would cause an error, but that is expected because if you unload the `consult-gh-embark` feature, then calling embark on consult-gh candidates (and not other things) would not work anymore!

Please let me know if that makes sense, or if you think there are still changes needed.

**Comment by riscy** [comment]
> I don't see what would be the surprise, if the consult-gh-embark package changes embark actions for consult-gh since that's what it is supposed to do

I had the same view when I first submitted a package to MELPA.  But packages that don't immediately change the environment can be reliably used as dependencies (even just for ad hoc scripts), and lead to easier-to-debug configs because users can see explicitly what's changing and when, especially in cases when they have two packages with overlapping functionalities.

If I'm missing something, or you just insist, then we can go down that route - but I want to make sure contributors understand.

> If somebody unloads consult-gh-embark ... Calling embark-act when the cursor is specifically on a consult-gh candidate in the minibuffer would cause an error, but that is expected because if you unload the consult-gh-embark feature, then calling embark on consult-gh candidates (and not other things) would not work anymore!

I assume the error is different than the error the user would normally encounter (due to `consult-gh-embark-default-action` no longer existing) and I also assume the user would then have to restart Emacs (or carefully step through `embark-default-action-overrides` and remove everything you've automatically added from that list) to get things back to "pristine".

---------

OK, I realize this seems like only a minor inconvenience (if any) for users, but when I'm reviewing packages for these things I try to be consistent and use broad rules that have a net benefit for the entire ecosystem, regardless of "inconvenience" level.  And Emacs has idiomatic ways of dealing with these things.  A mode is one way.  Or, or example, if you write a function called `consult-gh-embark-unload-function` then you can do some cleanup to the `embark...overrides` list when the `unload-feature` command is called by the user.

**Comment by riscy** [comment]
> I agree that it would be ideal if we find a good way to go back to embark acting like before loading this package

I think this can be handled.  Emacs will automatically look for a function called `consult-gh-embark-unload-function` when the `unload-feature` command is called by the user.  So if you define such a function, you can "go back".   I think this is a good compromise - what do you think?

**Comment by armindarvish** [comment]
>  So if you define such a function, you can "go back". I think this is a good compromise - what do you think?

Sounds good! Let me try doing that and test it and see how that goes. I'll update here once I have something.

**Comment by armindarvish** [comment]
@riscy I added a `consult-gh-embark-unload-function` per your suggestion. Can you take a look now and let me know if there are any other suggestions/comments?

**Comment by armindarvish** [comment]
@riscy Actually after further testing, I decided to define a minor mode after all. It's cleaner that way and easier to maintain in the future as well. Take a look and let me know what you think.

**Comment by riscy** [comment]
I think this makes a lot of sense!  I'd go one step further and not automatically turn the mode on when the package is loaded (you have `(consult-gh-embark-mode +1)` at the top level) - it would give users a clear view of what's going on.

One more note is that, by convention, the lighter on consult-gh-embark.el#L284 should start with a space.

This is very close to ready to merge, so let me know when you're ready and I'll try to get back here quickly.

**Comment by armindarvish** [comment]
@riscy I fixed the issues you mentioned. This should be good to go now!

**Comment by riscy** [comment]
Thank you!

**Pull request merged**
