### PR TITLE
Add recipe dired-hist

### PR DESCRIPTION
**Pull request by Anoncheg1**
### Brief summary of what the package does

Add two commands: "back" and "forward".

Traverse Dired buffer history (or just path) according to history.

As buttons in every modern file managers: Thunar, Microsoft Explorer, Nautilus, Konqueror.

### Direct link to the package repository

https://github.com/Anoncheg1/dired-hist

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`dired-hist.el` with byte-compile using Emacs 29.1:
```
dired-hist.el:153:12: Warning: reference to free variable `for'
dired-hist.el:153:16: Warning: reference to free variable `b'
dired-hist.el:153:18: Warning: reference to free variable `in'
dired-hist.el:154:12: Warning: reference to free variable `do'
In end of data:
dired-hist.el:282:25: Warning: the function `copy' is not known to be defined.
dired-hist.el:153:4: Warning: the function `cl-loop' might not be defined at runtime.
```
(You need to `require 'cl-lib`)

`dired-hist.el` with checkdoc 0.6.2 (fix *within reason*):
```
dired-hist.el:149: Argument `where' should appear (as WHERE) in the doc string
```

`dired-hist.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- The `;;; Commentary` for this file is much wider than 80 characters
```

**Comment by Anoncheg1** [comment]
Fixed.

**Comment by riscy** [comment]
Thanks again - checklist looks good.

I like this idea.  To be thorough, though, I wanted to check: have you heard of dired+ https://www.emacswiki.org/emacs/DiredPlus ?  It is (or was once) a popular package, and I believe it contains a configuration option that prevents Emacs from opening new dired buffers, and supports this sort of forward/back behavior already.

**Comment by Anoncheg1** [comment]
I looked at https://www.emacswiki.org/emacs/dired%2b.el and https://github.com/emacsmirror/dired-plus/blob/master/dired+.el
There is no back and forward commands for history. And I don't like when everything in one file.

I found history support only in this packages, they have own history implementation
- diredc - diredc-history-mode - Midnight Commander features (plus) for dired
- dirvish - extensions/dirvish-history.el - A modern file manager based on dired mode
I was unable to extract history from them, but I will track their implementation for inspiration.

**Comment by riscy** [comment]
Gotcha, and thanks for looking into those. :)

**Pull request merged**
