### PR TITLE
Add currency-convert recipe

### PR DESCRIPTION
**Pull request by lassik**
### Brief summary of what the package does

Convert amounts of money from one currency to another in Emacs.

Exchange rates are downloaded from exchangeratesapi.io. They ought to be accurate enough for everyday purposes. It goes without saying that you should not rely on this package for investment or business decisions.

### Direct link to the package repository

https://github.com/lassik/emacs-currency-convert

### Your association with the package

Just wrote it

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by lassik** [comment]
Testing:

* Do `M-x currency-convert`. It says `Please do M-x currency-convert-update-rates` in the echo area.
* Do `M-x currency-convert-update-rates`. It downloads a JSON file from the API, saves it in your `.emacs.d` directory and loads it into Emacs.
* Do `M-x currency-convert` again. It asks in the minibuffer for an `Amount` and then separately for a `Currency`. The amount is just a float (`12.34`); for currency, try tab completion to list all choices.
* All conversions from the given amount in the given currency to other currencies are shown in a `*Currency*` buffer.
* Running `M-x currency-convert` again overwrites the `*Currency*` buffer with the new amount.

**Comment by riscy** [comment]
It's probably not an issue, and correct me if I'm wrong, but is the `cl-lib` required here?

```elisp
;; Package-Requires: ((emacs "24.4") (cl-lib "0.5"))
```
since cl-lib should come packaged with Emacs 24.4? (Although I have to admit I'm not sure which version.)

In any case, I can't count that as a blocker. :)

**Comment by lassik** [comment]
> is the `cl-lib` required here?

I have no idea :)

**Comment by lassik** [comment]
Neither `M-x byte-compile-file` in a vanilla Emacs nor `M-x package-lint-current-buffer` raise any issues when omitting the `cl-lib` so I'll do that.

**Comment by riscy** [comment]
Yeah, `cl-lib` started to come with Emacs in 24.3 it looks like.

**Comment by lassik** [comment]
We should add a warning to package-lint when `cl-lib` is redundant.

**Pull request merged**
