### PR TITLE
Add insert-random recipe

### PR DESCRIPTION
**Pull request by lassik**
### Brief summary of what the package does

Insert random characters from various character sets.

Provides the following commands:

* `insert-random-lowercase`
* `insert-random-uppercase`
* `insert-random-alphabetic`
* `insert-random-alphanumeric`
* `insert-random-digits`
* `insert-random-hex-uppercase`
* `insert-random-hex-lowercase`

As well as a general-purpose `insert-random` command.

Use a prefix argument to say how many random characters to insert.

### Direct link to the package repository

https://github.com/lassik/emacs-insert-random

### Your association with the package

Just wrote it

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Code looks great to me!  I'm having trouble thinking of the common use-case though - could you help clarify?  (May also be good to add to your Commentary)

**Comment by lassik** [comment]
Thanks. The main use cases are to generate:

* test input when writing code
* examples of hashes, numbers, etc. when writing documentation and specifications

**Comment by lassik** [comment]
`C-u 10 insert-random-alphanumeric` can generate a random 10-character password, etc.

**Comment by riscy** [comment]
Great examples -- I wonder if those would be worth adding to the Commentary, but not a blocker obviously.

**Comment by lassik** [comment]
Thanks for merging this. Commentary now updated accordingly.

**Pull request merged**
