### PR TITLE
Add recipe for nova color theme.

### PR DESCRIPTION
**Pull request by muirmanders**
### Brief summary of what the package does

[Nova](https://trevordmiller.com/projects/nova) color theme.

### Direct link to the package repository

https://github.com/muirmanders/emacs-nova-theme

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by muirmanders** [comment]
Thanks. I cleaned up the deps by removing them and bumping emacs version, and I added a simple readme w/ screenshot.

**Comment by muirrn** [comment]
Hi - Are my changes sufficient or did you want something else?

**Comment by purcell** [comment]
Looks good, merging now - welcome to MELPA! :tada:

I would note that you may have some issues with the theme in text terminals, based on my experience using the `color` functions in my `tomorrow` themes -- specifically, if you load the themes in a text frame, colours will be interpolated in the very limited colour space of that frame, and then will display poorly later in any GUI frames that are created. In my case, I inlined the interpolated colour values, but YMMV. :-)

**Comment by muirrn** [comment]
Thanks! Good tip regarding colors. I wasn't planning to care about making it look good in terminals for now, but I hadn't considered that interaction between text/GUI frames.

**Comment by purcell** [comment]
Cool. Here's what's working for me: https://github.com/purcell/color-theme-sanityinc-tomorrow/commit/e7ae36c5f90310e06457c663cec7db4f5a79582c

**Pull request merged**
