### PR TITLE
added rubik mode recipe

### PR DESCRIPTION
**Pull request by Kurvivor19**
### Brief summary of what the package does

Rubik's cube puzzle in emacs

### Direct link to the package repository

https://github.com/Kurvivor19/rubik-mode

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks - great idea! Please run `package-lint` as requested: it will have some feedback for you that I would just have to give manually.

**Comment by Kurvivor19** [comment]
Refactoring according to `package-lint` done.

**Comment by purcell** [comment]
Thanks! You missed some package-lint feedback:
```
2 issues found:

9:1: error: Expected (package-name "version-num"), but found calc.
9:1: error: Expected (package-name "version-num"), but found cl-lib.
```

That's because versionless package dependencies aren't understood by all versions of `package.el`.

Additionally, `rubik-cube-undo` gets used as a function on line 679, but it isn't defined anywhere.

**Comment by Kurvivor19** [comment]
These issues have been adressed now

**Comment by purcell** [comment]
Great, merged! Welcome to MELPA. 🎉

**Comment by tarsius** [comment]
What license is this released under? Sounds like `BEER-WARE` might be to you liking. If so, then please add this to the library header:

```
;;; License: BEER-WARE
```

**Comment by purcell** [comment]
Ah yes, missed that -- you'd indicated that the license is GPLv3-compatible, but it's not. Please can you choose such a licence? It's mandatory for inclusion in MELPA.

**Comment by purcell** [comment]
Alright, I googled it and see that it's loosely compatible, so yay - but please add a header to indicate this more formally, as suggested by Jonas above, otherwise audit tools are likely to flag the package as non-compliant at some point. Thanks! :-)

**Comment by Kurvivor19** [comment]
Acknowledged and done. Yes, that is beerware - and i have checked it is compliant before deciding on it. Truth is, more complicated GPL stuff made my brain hurt, so i opted for simpler approach

**Comment by purcell** [comment]
Beer is good.

**Pull request merged**
