### PR TITLE
Add ispc-mode

### PR DESCRIPTION
**Pull request by Munksgaard**
### Brief summary of what the package does

ispc-mode is a major mode for editing [ispc](https://ispc.github.io) programs.

### Direct link to the package repository

https://github.com/Munksgaard/ispc-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks.  Looks like some very minor checkdoc nags that look easy to fix below --

### ispc-mode.el ###

byte-compile with Emacs 27.1:
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
- No issues!

checkdoc 0.6.2:
```
Warning (emacs): 
ispc-mode.el:49: First sentence should end with punctuation
Warning (emacs): 
ispc-mode.el:55: First sentence should end with punctuation
Warning (emacs): 
ispc-mode.el:59: First sentence should end with punctuation
Warning (emacs): 
ispc-mode.el:66: First sentence should end with punctuation
Warning (emacs): 
ispc-mode.el:73: First sentence should end with punctuation
```

package-lint 20200906.512:
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- ispc-mode.el#L26: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

Minor:
- fucntions -> functions

**Comment by Munksgaard** [comment]
Thank you for the detailed comments @riscy! I believe I have addressed all of them in the ispc-mode repository now.

**Comment by riscy** [comment]
Thanks!

**Comment by riscy** [comment]
And welcome to MELPA. :)

**Pull request merged**
