### PR TITLE
Add recipe for transwin.

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Make window/frame transparent.

### Direct link to the package repository

https://github.com/jcs-elpa/transwin

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Looks good.  Have you had a chance to compare to [seethru](https://melpa.org/#/seethru)?  One note:

- transwin.el#L81: No `format` required; messages are already f-strings

**Comment by jcs090218** [comment]
> Looks good. Have you had a chance to compare to seethru? One note:

Cool, I didn't notice this package. Weird that I have search through the melpa page, but it doesn't show up. 😕 Anyway, I feel like `seethru` have something I need like `seethru` and `seethru-relative` yet other functions may not be useful for me or this package. 

> transwin.el#L81: No format required; messages are already f-strings

Fixed! 😄

**Comment by tarsius** [comment]
> Merge https://github.com/melpa/melpa into transwin

Don't do that. Instead rebase your feature branch onto the upstream master branch.

**Comment by jcs090218** [comment]
May I ask why? 😕 I don't see the difference.

Anyway, I don't know how to rebase the branch from what I am currently doing, so may I open another PR instead? Thanks! 😄

**Comment by tarsius** [comment]
There is one official sequence of commits that have made it into Melpa. All the pull-requests are things that may or may not make it into Melpa. The merge commit messages should therefore say "this thing has been accepted into the official version". Your commit says "the official version has been accepted into some random unofficial version".

> Anyway, I don't know how to rebase the branch from what I am currently doing, so may I open another PR instead? Thanks!

Please no new pr. Just use `git rebase master` instead of `git merge master`. Doing that should even remove the earlier merge commit.

**Comment by jcs090218** [comment]
Okay, does this works? 😕 

I tried `git rebase master` but it gives me the error `invalid upstream master`. So then I `git rebase origin`, I think it rebase it to my fork's master branch. Is this what you want? 😕 

Anyway, CI failed. 😓

**Comment by tarsius** [comment]
> Okay, does this works? [...] So then I `git rebase origin`,

No. Use `git rebase origin/master` instead.

> Anyway, CI failed.

That sort of CI failure sometimes happens. I don't know why. Don't worry about it.

**Comment by jcs090218** [comment]
I ran command `git rebase origin/master`, yet I get `Current branch transwin is up to date`. 😕 

> That sort of CI failure sometimes happens. I don't know why. Don't worry about it.

Got you! 👍

**Comment by tarsius** [comment]
Well I do that sort of thing using one or two key presses in Magit, and while I had to look at how `git` does it to implement that...

Anyway if you first `git reset --hard HEAD~` to remove the merge commit, then `git rebase origin/master` should start doing the right thing afterwards.

**Comment by riscy** [comment]
This looks fine now.  I'll squash squash these through the UI so that these merge-commits, while certainly unnecessary, won't make it into our commit history.

**Pull request merged**
