### PR TITLE
Add apib-mode recipe

### PR DESCRIPTION
**Pull request by w-vi**
### Brief summary of what the package does

Major mode for editing API Blueprint files [https://apiblueprint.org/](https://apiblueprint.org/)

### Direct link to the package repository

https://github.com/w-vi/apib-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Please check code and use the package with plain Emacs at least once.

- I cannot load your library. What is `defconst-mode-local` ?
- `nil` is not a function. This package uses `nil` as function at much parts.
- Too many byte-compile warnings.

**Comment by w-vi** [comment]
Fixed
- `defconst-mode-local` comes from cedet so I have removed it
- cleaned up the `nil` is not a function
- No byte-compile warnings when run with clean emacs anymore.

Thanks a lot for the feedback and review it is my first package so I am learning how to do it properly.

**Comment by purcell** [comment]
Quick feedback:
- You can & should remove `in GNU Emacs` from the package description
- Don't use `concat` to build command strings unless you're also using `shell-quote-argument` to make filenames safe: they might contain spaces or quotes
- Adding new global compilation patterns every time you open a file in this mode isn't a good idea. What you probably want instead is to a specific function that end users can call, e.g. `apib-run-drafter`, rather than trying to modify the built-in compilation machinery.
- Define your font lock keywords globally as a `defconst`, then add them by name (e.g. `apib-mode-font-lock-keywords`) in the mode function.
- Don't use `(executable-find "drafter")` at load time, because `exec-path` may or may not get modified before or after loading `apib-mode`: instead, just use the plain string `"drafter"` as the default.

**Comment by w-vi** [comment]
I have updated the package significantly, includes now some sanity test using `ert`. Have tried it using the package in clean emacs as well.

**Comment by w-vi** [comment]
Is there anything I can do to push it?

**Comment by purcell** [comment]
Thanks, looking better! Just a couple more small things, then we should be ready to merge:
- You'll need a `defgroup` to define the `apib-mode` custom group, and place it in one of the standard customisation groups.
- [This sort of thing](https://github.com/w-vi/apib-mode/blob/5386f3ad2c454eccab22d2e9849b762b153e49ee/apib-mode.el#L155-L160) isn't safe when filenames contain spaces, quotes or other characters with special meanings to the shell. Use `shell-quote-argument` to escape command arguments.

**Comment by w-vi** [comment]
Thanks a lot for the feedback I have learnt so much. Will fix those.

**Comment by w-vi** [comment]
Updated so there is a proper group now.
Regarding the `shell-quote-argument` I've setup a [test where there is a space in filename](https://github.com/w-vi/apib-mode/blob/master/apib-mode-test.el#L62) to check where the quoting needs to take place and the bit you have pointed out it seems that I should not do it as then I'm getting error that the file was not found. Looking at `call-process` documentation I am not sure how it works but not quoting works.

**Comment by syohex** [comment]
Please don't put unrelated files(`install-deps.el`, `load-deps`) which matches against default file patterns at top directory and please check package content again if you add files. 

```
% make recipes/apib-mode
% tar tf packages/apib-mode-20161202.117.tar
apib-mode-20161202.117/
apib-mode-20161202.117/apib-mode-pkg.el
apib-mode-20161202.117/apib-mode.el
apib-mode-20161202.117/install-deps.el
apib-mode-20161202.117/load-deps.el
```

**Comment by w-vi** [comment]
Sorry I forgot to update melpa recipe and after your comment decided to move the files to subdirectory as a cleaner solution. I hope that now everything is OK.

**Comment by syohex** [comment]
Looks good

**Comment by purcell** [comment]
Thanks, sorry for the slow response. Busy end of year here.

**Comment by w-vi** [comment]
I thank you for teaching me.

**Pull request merged**
