### PR TITLE
Add `electric-cursor`

### PR DESCRIPTION
**Pull request by duckwork**
### Brief summary of what the package does

This package contains a global minor mode, `electric-cursor-mode`, which automatically sets the cursor-type depending on what mode the user is in.  `electric-cursor-mode` is more flexible than the currently available package, [bar-cursor](https://melpa.org/#/bar-cursor).

### Direct link to the package repository

https://github.com/duckwork/electric-cursor

### Your association with the package

I am the author of the package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by mattiasb** [comment]
This won't work in terminals FWIW. You'll have to send special terminal control characters there instead.

Something like this:
```lisp
;; For box
(send-string-to-terminal "\e[1 q")
;; For bar
(send-string-to-terminal "\e[5 q")
```

**Comment by duckwork** [comment]
Great idea! Implemented in [this commit](https://github.com/duckwork/electric-cursor/commit/a25614973e7e5c027603cf84908b79fdac031e8f) -- I also added some code to revert to the previous cursor after the mode is disabled.

**Comment by mattiasb** [comment]
> Great idea! Implemented in [this commit](https://github.com/duckwork/electric-cursor/commit/a25614973e7e5c027603cf84908b79fdac031e8f) -- I also added some code to revert to the previous cursor after the mode is disabled.

Yeah it's pretty neat that it's possible. It's a little bit rough though since it changes the terminal itself so keeping tabs of it is pretty hard. Say that you do a `C-z` for example (to suspend Emacs for doing some short commands) you'll have the cursor as defined within Emacs. Same if you kill or exit Emacs without resetting them. So it's a tradeoff. :)

Anyhow, I won't derail this more now. :)

**Comment by duckwork** [comment]
Hmm, I might want to set it behind an option then, just in case the user doesn't want to apply the settings in a terminal.

**Comment by duckwork** [comment]
FYI -- I added the option.  😎

**Comment by riscy** [comment]
>  electric-cursor-mode is more flexible than the currently available package, bar-cursor.

Thanks for the comparison -- this is actually really helpful.  I wonder if this flexibility (which I'm not familiar enough with either package to comment on) couldn't be contributed to bar-cursor?  If not I think that's fine, this check is mostly to be thorough.

I'm noticing these package-lints:

package-lint (using version 20210425.3):
```
2 issues found:
9:23: error: You can only depend on Emacs version 24 or greater: package.el for Emacs 23 does not support the "emacs" pseudopackage.
103:30: error: You should depend on (emacs "24.1") if you need `pcase'.
```
and I'll also note the way you specify your License within your boilerplate is a bit informal and may be harder for tooling to detect.  For a one-liner I recommend an [SPDX-License-Identifier](https://spdx.dev/ids/).

**Comment by duckwork** [comment]
Should be fixed -- I *think* I did the `SPDX-License-Identifier` correctly.  Also I forgot about package-lint, sorry about that!  I'll remember for the next one.

As far as contributing to `bar-cursor`, I think this is different enough to warrant another package.  `bar-cursor` only works with `overwrite-mode`, and has no mechanism to extend it; in contrast, `electric-cursor` is extensible by design, and only happens to share functionality with `bar-cursor` by default because that's what I personally use it for.  I can reach out to the author of `bar-cursor`, but the repo was last updated 5 months ago to update the copyright term.  I'm not sure how interested they'd be in basically re-writing their package.

Thanks so much for the review!  I'm pretty new to this kind of contributing, so I appreciate the thoroughness.

**Comment by riscy** [comment]
Looks good here -- thanks, and welcome to MELPA. :)

**Pull request merged**
