### PR TITLE
Add cycle-at-point

### PR DESCRIPTION
**Pull request by ideasman42**
### Brief summary of what the package does

Cycle common operators and keywords with a single key-stroke.

Context sensitive cycling of words such as (`true` / `false`) (`==` / `!=`), (`<` / `>`), (`is` / `is not`) ... and others depending on the major mode.

- Presets are included for C/C++/Python/ELisp (or users can set their own literals to cycle).
- Integer bases are also supported (cycle hex/decimal/octal/binary).
- Values to cycle can be generated on the fly.

### Direct link to the package repository

https://gitlab.com/ideasman42/emacs-cycle-at-point

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Cool idea -- quick first pass below:

`cycle-at-point-preset-c++-mode.el` with checkdoc 0.6.2:
```
cycle-at-point-preset-c++-mode.el:13: All variables and subroutines might as well have a documentation string
```

`cycle-at-point-preset-c++-mode.el` with package-lint 20211122.1152:
```
1 issue found:
4:0: error: Package-Requires outside the main file have no effect.
```

`cycle-at-point-preset-c-mode.el` with byte-compile using Emacs 27.1:
```
cycle-at-point-preset-c-mode.el:26:1:Warning: the function
    `cycle-at-point-find-integer-bases-at-point' is not known to be defined.
```

`cycle-at-point-preset-c-mode.el` with checkdoc 0.6.2:
```
cycle-at-point-preset-c-mode.el:12: All variables and subroutines might as well have a documentation string
```

`cycle-at-point-preset-c-mode.el` with package-lint 20211122.1152:
```
1 issue found:
4:0: error: Package-Requires outside the main file have no effect.
```

`cycle-at-point-preset-cmake-mode.el` with byte-compile using Emacs 27.1:
```
cycle-at-point-preset-cmake-mode.el:23:1:Warning: the function
    `cycle-at-point-find-alphabet-symbol' is not known to be defined.
```

`cycle-at-point-preset-cmake-mode.el` with checkdoc 0.6.2:
```
cycle-at-point-preset-cmake-mode.el:12: You should convert this comment to documentation
```

`cycle-at-point-preset-cmake-mode.el` with package-lint 20211122.1152:
```
1 issue found:
4:0: error: Package-Requires outside the main file have no effect.
```

`cycle-at-point-preset-emacs-lisp-mode.el` with byte-compile using Emacs 27.1:
```
cycle-at-point-preset-emacs-lisp-mode.el:25:1:Warning: the function
    `cycle-at-point-find-alphabet-symbol' is not known to be defined.
```

`cycle-at-point-preset-emacs-lisp-mode.el` with checkdoc 0.6.2:
```
cycle-at-point-preset-emacs-lisp-mode.el:12: All variables and subroutines might as well have a documentation string
```

`cycle-at-point-preset-emacs-lisp-mode.el` with package-lint 20211122.1152:
```
1 issue found:
4:0: error: Package-Requires outside the main file have no effect.
```

`cycle-at-point-preset-lang-en.el` with checkdoc 0.6.2:
```
cycle-at-point-preset-lang-en.el:12: All variables and subroutines might as well have a documentation string
```

`cycle-at-point-preset-lang-en.el` with package-lint 20211122.1152:
```
1 issue found:
4:0: error: Package-Requires outside the main file have no effect.
```

`cycle-at-point-preset-python-mode.el` with byte-compile using Emacs 27.1:
```
cycle-at-point-preset-python-mode.el:29:1:Warning: the following functions are
    not known to be defined: cycle-at-point-find-integer-bases-at-point,
    cycle-at-point-find-alphabet-symbol
```

`cycle-at-point-preset-python-mode.el` with checkdoc 0.6.2:
```
cycle-at-point-preset-python-mode.el:12: All variables and subroutines might as well have a documentation string
```

`cycle-at-point-preset-python-mode.el` with package-lint 20211122.1152:
```
1 issue found:
4:0: error: Package-Requires outside the main file have no effect.
```

`cycle-at-point.el` with byte-compile using Emacs 27.1:
```
cycle-at-point.el:487:1:Warning: the function `string-replace' is not known to
    be defined.
```

`cycle-at-point.el` with checkdoc 0.6.2:
```
cycle-at-point.el:80: Keycode A-Z embedded in doc string.  Use \\<keymap> & \\[function] instead
```

`cycle-at-point.el` with [melpazoid](https://github.com/riscy/melpazoid):
- cycle-at-point.el#L96: There is no need to quote lambdas (neither #' nor ')
- cycle-at-point.el#L382: There is no need to quote lambdas (neither #' nor ')
- cycle-at-point.el#L384: There is no need to quote lambdas (neither #' nor ')
- cycle-at-point.el#L387: There is no need to quote lambdas (neither #' nor ')

Package and license:
- LICENSE excerpt: `GNU GENERAL PUBLIC LICENSE...`
- Add a standard license header or an [SPDX-License-Identifier](https://spdx.dev/ids/) to cycle-at-point-preset-c++-mode.el
- Add a standard license header or an [SPDX-License-Identifier](https://spdx.dev/ids/) to cycle-at-point-preset-c-mode.el
- Add a standard license header or an [SPDX-License-Identifier](https://spdx.dev/ids/) to cycle-at-point-preset-cmake-mode.el
- Add a standard license header or an [SPDX-License-Identifier](https://spdx.dev/ids/) to cycle-at-point-preset-emacs-lisp-mode.el
- Add a standard license header or an [SPDX-License-Identifier](https://spdx.dev/ids/) to cycle-at-point-preset-lang-en.el
- Add a standard license header or an [SPDX-License-Identifier](https://spdx.dev/ids/) to cycle-at-point-preset-python-mode.el

**Comment by ideasman42** [comment]
@riscy thanks, and gosh, I need to look more into error checking.

Tested with emacs 27 and 29 (master) and still wasn't able to redo all of these warnings, although I think most are handled.

re: `string-replace` not being known, this is part of `subr` but `(require 'subr)` gives me a warning.

```
cycle-at-point.el:43:2: Error: Loading file /opt/emacs/share/emacs/29.0.50/lisp/subr.elc failed to provide feature ‘subr’
```

There is another warning that I get but would rather ignore:

```
1:0: warning: The word "emacs" is redundant in Emacs package names.
```

Since the preset name is created based on the major mode.

**Comment by ideasman42** [comment]
- Found that string-replace isn't available in emacs-27 (using replace-regexp-in-string instead).
- Removed `printf` (debugging left in by accident).
- Use GPL 3.0-or-later everywhere.

**Comment by riscy** [comment]
Look great!  Thank you for this.

**Pull request merged**
