### PR TITLE
Add recipe for org-index.

### PR DESCRIPTION
**Pull request by marcIhm**
### Brief summary of what the package does

A personal adaptive index for org.

### Direct link to the package repository

https://github.com/marcIhm/org-index

### Your association with the package

I am the author.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by tarsius** [comment]
> org-index.el is also in the contrib-directory of org

In such cases it is better to not also add it as a separate package, else two packages - this one and `org-plus-contrib`.

**Comment by tarsius** [comment]
In the past @bzg has said that he prefers if Org extensions are maintained separately instead of being added to `contrib/`, but I don't know how that plan is coming along.

**Comment by bzg** [comment]
Yes, I still have this plan. We will release Org 9.1.8 soon, then 9.2, then remove the `contrib/` directory from Org's repository. The idea is to have `org-contrib.git` living on https://code.orgmode.org.

**Comment by marcIhm** [comment]
Hi, I see the Point; if asked to decide between org-contrib and melpa, I opt for melpa, because it is easier to install from there. So just removed from org-contrib :-( I will add it again, if found useful, once org-contrib has moved.

**Comment by marcIhm** [comment]
Currently org-index is no longer in the head of org (which is okay for bzg and me). However, the latest tag of org (9.1.8) still contains org-index.el. So the situation is somewhat mixed ... 
How to proceed then ? Can this pull-request be accepted or should it wait for the next tag of org (probably 9.2), which will no longer contain org-index ?

**Comment by bzg** [comment]
FWIW, I hope to release Org 9.2 in a month or so.

**Comment by marcIhm** [comment]
Thats not Long :-) Would be fine with waiting until then.

**Comment by marcIhm** [comment]
Yes, made it three subdirs (each with .nosearch). Looks cleaner now :-)

**Comment by tarsius** [comment]
Thanks!

**Comment by purcell** [comment]
Merged now, and I know this is pre-existing code, but I'm just going to say that I think [this function](https://github.com/marcIhm/org-index/blob/master/org-index.el#L2887-L3207) is pretty extreme and could probably be split up. The function says it's written a particular way for performance, but much of its code is for setting up keybindings that could instead be defined in a little minor mode. :-)

**Comment by marcIhm** [comment]
Thanx, for your suggestion !
I am still learning lisp and this sounds like a good improvement.

Am 08.04.2018 um 10:50 schrieb Steve Purcell:

**Pull request merged**
