### PR TITLE
Add recipe for bbww

### PR DESCRIPTION
**Pull request by natelastname**
### Brief summary of what the package does

bbww (Better BackWard Word) provides alternatives to some basic text editing functions such as:

forward-word
backward-word
forward-kill-word
backward-killword 
 
### Direct link to the package repository

https://github.com/natelastname/better-backward-word.git

### Your association with the package

I am currently the sole author and user of this package 

### Relevant communications with the upstream package maintainer

None

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`bbww.el` with byte-compile using Emacs 28.1:
```
bbww.el:51:4: Warning: Unused lexical variable `temp'
In bbww-get-backward-region:
bbww.el:62:8: Warning: docstring wider than 80 characters
In bbww-skip-chars-bidi:
bbww.el:81:36: Warning: Unused lexical argument `chars'
In bbww-forward-word:
bbww.el:116:4: Warning: Unused lexical argument `arg'
In bbww-backward-kill-word:
bbww.el:126:4: Warning: Unused lexical argument `arg'
bbww.el:168:1: Warning: defcustom for `bbww-mode' fails to specify containing
    group
bbww.el:168:1: Warning: defcustom for `bbww-mode' fails to specify containing
    group
```

`bbww.el` with checkdoc 0.6.2:
```
bbww.el:72: All variables and subroutines might as well have a documentation string
bbww.el:77: All variables and subroutines might as well have a documentation string
bbww.el:82: All variables and subroutines might as well have a documentation string
bbww.el:87: Argument `arg' should appear (as ARG) in the doc string
bbww.el:92: Argument `arg' should appear (as ARG) in the doc string
bbww.el:92: Lisp symbol `mwim-end' should appear in quotes
bbww.el:99: Argument `arg' should appear (as ARG) in the doc string
bbww.el:116: All interactive functions should have documentation
bbww.el:125: Argument `arg' should appear (as ARG) in the doc string
bbww.el:131: All interactive functions should have documentation
bbww.el:136: All interactive functions should have documentation
bbww.el:160: First sentence should end with punctuation
bbww.el:169: First sentence should end with punctuation
```

`bbww.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bbww.el#L162: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
```

**Comment by natelastname** [comment]
Thank you for the feedback. I fixed the linting issues (unused variables, checkdoc problems, failing to specify a group)

> `bbww.el` with [melpazoid](https://github.com/riscy/melpazoid):
> 
> ```
> - bbww.el#L162: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
> ```

I do not understand this issue. define-key should not overwrite any bindings because it's assigning to a keymap defined by the package?

I deliberately chose not to use sparse keymaps because I couldn't get them to work with `emulation-mode-map-alists` without causing problems. (Breaking `emulation-mode-map-alists`  is very bad)

**Comment by riscy** [comment]
See https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips-for-Defining.html under "When defining and initializing a variable that holds a complicated value...", which writes it better than I could:

> reloading the file once the variable is initialized will not alter it; that is important if the user has run hooks to alter part of the contents (such as, to rebind keys)

My example used `make-sparse-keymap` but you can just as well substitute in `make-keymap`.

**Comment by natelastname** [comment]
> See https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips-for-Defining.html under "When defining and initializing a variable that holds a complicated value...", which writes it better than I could:
> 
> > reloading the file once the variable is initialized will not alter it; that is important if the user has run hooks to alter part of the contents (such as, to rebind keys)
> 
> My example used `make-sparse-keymap` but you can just as well substitute in `make-keymap`.

Thank you for explaining this.

I just implemented this change.

**Comment by riscy** [comment]
Thanks for this.  A couple minor checkdocs --

`bbww.el` with checkdoc 0.6.2:
```
bbww.el:92: Lisp symbol `mwim-end' should appear in quotes
bbww.el:176: First sentence should end with punctuation
```

I think these are both valid (the latter suggesting rewriting the docstring to `"Minor mode for better backward word (bbww)."`

You also have some self-notes embedded in the code (e.g. `Crash course on key bindings`) which aren't harmful but you might want to integrate the most relevant details into your docstrings.

Non-blocking, though.  And welcome to MELPA. :)

**Pull request merged**
