### PR TITLE
Add hmac recipe

### PR DESCRIPTION
**Pull request by grimnebulin**
### Brief summary of what the package does

Implements a Hash-based Message Authentication Code around Emacs's built-in secure-hash function.

### Direct link to the package repository

https://github.com/grimnebulin/emacs-hmac

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by DamienCassou** [comment]
Some feedback:

- Please run linters specified in CONTRIBUTING.md. They would have told you about:
  - you miss a `;;; Code:` section in the header
  - the first line of `hmac` docstring is more than 80 characters long
  - your `if-let` is broken, it needs an additional pair of parenthesis around the variable bindings (more precisely, you use a deprecated syntax)
- the package documentation could say a little more about why the wrapper is useful and what it does precisely. Please consider contributing to emacs core.

**Comment by grimnebulin** [comment]
I did run the linters.  I don't personally like the `;;; Code:` section because it's perfectly obvious where the code is.  The first line of the `hmac` docstring is 79 characters long, including the newline, and the linter erroneously includes the docstring indentation in its character count.  But since you insist, I've made those changes.

The `if-let` is certainly not broken; it works fine.  I can't find any indication that the syntax is deprecated.  It is explicitly allowed as a special case in my local Emacs, built a few months ago, and also in the current Emacs master.  It is also not deprecated in both the earliest and latest tagged versions of Emacs 25 (as specified in my `Package-Requires` line).  Searching for the terms "emacs if-let deprecated" turns up nothing relevant.

**Comment by DamienCassou** [comment]
Sean McAfee <notifications@github.com> writes:
> […] But since you insist, I've made those changes.


I'm very sorry you felt I insisted. In my mind, I just gave you my
personal opinion. I don't think you should change your code in any way
you don't like: after all, you are going to maintain it, not
me. Moreover, I don't even have the admin rights on Melpa to merge your
PR, so I don't decide on anything.


> The `if-let` is certainly not broken; it works fine.  I can't find any
> indication that the syntax is deprecated.  […]

More information in this discussion:
https://lists.gnu.org/archive/html/emacs-devel/2018-03/msg00321.html


-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by purcell** [comment]
Thanks @grimnebulin - looks good, merging now. Sorry for the long delay in getting to this.

**Pull request merged**
