### PR TITLE
Add recipe for LiTeX mode

### PR DESCRIPTION
**Pull request by Atreyagaurav**
### Brief summary of what the package does

A minor mode to convert valid elisp/lisp expressions to latex. So that they can be evaluated as they are in emacs, and later converted to valid LaTeX expressions for reports and presentations.

### Direct link to the package repository

https://github.com/Atreyagaurav/litex-mode

### Your association with the package

I'm the author of the package (will be a maintainer too).

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by Atreyagaurav** [comment]
Melpazoid tests: Passed with few warnings.
Here's the build:
https://github.com/Atreyagaurav/litex-mode/runs/5127496777?check_suite_focus=true

If there are more recent commits on main after I wrote this, you can probably check it from there for the build result. Hopefully trying to reduce the time you have to spend on this :)

I did try to fix that warnings in next version, I have fixed as much as possible, but the test fails due to lint error in a function I had refactored as a part of next version (which is in dev branch). The main branch still is same.
https://github.com/Atreyagaurav/litex-mode/runs/5127779702?check_suite_focus=true

Which I think can be considered false positive, I have made an issue on package-lint:
 https://github.com/purcell/package-lint/issues/222

**Comment by Atreyagaurav** [comment]
package-lint false positive is fixed on the upstream, and I've pushed and made a new release for latest version with Fixes and more functionality. Both main branch and the release tag compiles and installs fine without problem on `STABLE=t EMACS_COMMAND=emacs make sandbox INSTALL=litex-mode` and `EMACS_COMMAND=emacs make sandbox INSTALL=litex-mode` locally.

**Comment by riscy** [comment]
I think this is right -- you're not using the `/` as a separator.

I may be overlooking something but I think the way keybindings have been set up is a little unorthodox (requiring users to refer to `litex-key-map`, and also modifying `litex-mode-map` at eval/load time after the minor mode declares it).  I'd suggest:

```elisp
(defvar litex-mode-map
  (let ((keymap (make-sparse-keymap)))
    (define-key keymap (kbd "F") 'litex-format-region)
    (define-key keymap (kbd "f") 'litex-format-region-last)
    (define-key keymap (kbd "E") 'litex-eval-and-replace)
    (define-key keymap (kbd "e") 'litex-eval-and-insert)
    (define-key keymap (kbd "s") 'litex-sexp-to-latex-exp)
    (define-key keymap (kbd "S") 'litex-sexp-solve-all-steps)
    (define-key keymap (kbd "r") 'litex-sexp-replace-variables)
    (define-key keymap (kbd "+") 'litex-increment-number)
    (define-key keymap (kbd "l") 'litex-exp-to-latex)
    (define-key keymap (kbd "m") 'litex-exp-in-latex-math)
    (define-key keymap (kbd "A") 'litex-solve-all-steps-equation)
    (define-key keymap (kbd "a") 'litex-solve-all-steps-eqnarray)
    (define-key keymap (kbd "×") 'litex-insert-or-replace-x)
    keymap))

(define-minor-mode litex-mode
  "Minor mode for Calculations on lisp, and formatting on LaTeX."
  :lighter " LiTeX")
```
The minor mode will use that keymap by name per convention, and users can define the keymap before loading the mode (if they so wish) without any risk of having their bindings overwritten.

**Comment by Atreyagaurav** [comment]
Oh, it's like this: 
`litex-mode-map` is quite literal, if I make `F` do something in that mode map, then instead of inserting `F` when I press `F` it'll call that function mapped to it, which makes it impossible to type thing when I'm using this minor mode. As some keys will be mapped in minor mode, while some won't be.

Obvious way to not have that problem is to use prefix key in the mapping itself, like assigning it to 'C-c F' or sth, but I don't want to replace or mess with user's settings. The reason I made it save in a variable is so that they can decide on the prefix key themselves. Or just not use the prefix key and this defined variable map, they can still use functions, or map only the functions they need using local-set key. My readme shows I'm used C-e as my prefix keys coz I use `End` for going to the end of the line, but I don't want to make that assumption for all the users. 

The reason I only binded `(kbd "×") ` directly is because it's a unicode character (that's not x) that's equivalent to `\times` in latex, and people are not likely to type it out for any other reason than this. But I'll remove that too, since it's not really necessary.

**Comment by Atreyagaurav** [comment]
I removed that direct map, so there won't be any default keymap in litex mode, user can choose to use this map with some prefix keys or, map their own keys with some functions. Hopefully that's ok. 
Latest commit has the fixes, on master.

**Comment by riscy** [comment]
>  I just wanted to leave it there just in case some users want to use it from there instead of having to copy the whole thing in their config.

I can see your rationale, but in that case I'd suggest making this clearer.  For example, as a casual viewer I get confused by this unused variable called `litex-key-map` so I'd suggest renaming it `litex-mode-map-example` instead.  To make it extra clear you haven't forgotten to define keybindings, you could simply add a `(defvar litex-mode-map (make-sparse-keymap))`.  And then in your `;;; Commentary` or even the docstring for `litex-mode` you could suggest something like, "by default the minor mode does not bind any keys but you can activate an example keymap with `(setq litex-mode-map litex-mode-map-example)` or modify this variable yourself".  And then finally, as a bonus, you can remind the user which bindings are active by revising the minor-mode docstring to:
```
(define-minor-mode litex-mode
  "Minor mode for Calculations on lisp, and formatting on LaTeX.
\n\\{litex-mode-map}
See: `litex-mode-map' for more details."
  :lighter " LiTeX")
```

That was long-winded and this isn't a blocker!  I'm happy to hit merge -- and welcome to MELPA. :)

**Comment by Atreyagaurav** [comment]
Yeah I'll do that, I should make that clear in the documentation I was too used to just making things for myself so fell sort of explaining I guess.

Thank you. And glad to be a contributor finally.

**Pull request merged**
