### PR TITLE
add: poe-filter-mode recipe

### PR DESCRIPTION
**Pull request by queertypes**
### Brief summary of what the package does

This package provides syntax highlighting support for [Path of Exile](https://www.pathofexile.com/) item filter files, such as those produced by [Neversink](https://github.com/NeverSinkDev/NeverSink-Filter).

### Direct link to the package repository

https://gitlab.com/queertypes/poe-filter-mode

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

#### Build Recipe Output

```
$ make recipes/poe-filter-mode
 • Building package poe-filter-mode ...
Package: poe-filter-mode
Fetcher: gitlab
Source:  https://gitlab.com/queertypes/poe-filter-mode.git

Cloning https://gitlab.com/queertypes/poe-filter-mode.git to /home/allele/dev/emacs/melpa/working/poe-filter-mode/
Copying files (->) and directories (=>)
  from /home/allele/dev/emacs/melpa/working/poe-filter-mode/
  to /tmp/poe-filter-modeMXucZ9/poe-filter-mode-20191225.1012
    poe-filter-mode-pkg.el -> poe-filter-mode-pkg.el
    poe-filter-mode.el -> poe-filter-mode.el
Built poe-filter-mode in 4.341s, finished at Wed Dec 25 05:31:36 2019
 ✓ Success:
4.0K -rw-rw-r-- 1 allele allele 149 Dec 25 05:31 packages/poe-filter-mode-20191225.1012.entry
 12K -rw-rw-r-- 1 allele allele 10K Dec 25 05:31 packages/poe-filter-mode-20191225.1012.tar
4.0K -rw-rw-r-- 1 allele allele 969 Dec 25 05:31 packages/poe-filter-mode-badge.svg
   0 -rw-rw-r-- 1 allele allele   0 Dec 25 05:31 packages/poe-filter-mode-readme.txt
```

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!

### poe-filter-mode.el

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No issues! 💯

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
4 issues found:

1:0: warning: The package summary should not end with a period.
26:0: error: Package should have a non-empty ;;; Commentary section.
108:10: warning: Closing parens should not be wrapped onto new lines.
125:2: warning: Closing parens should not be wrapped onto new lines.

```

Other static checks:
- poe-filter-mode.el#L118: It is unusual to derive from fundamental-mode
  - (This looks like it should be deriving from `prog-mode`?)
- poe-filter-mode.el#L24: Prefer `https` over `http` (if possible)
- Including poe-filter-mode-pkg.el is discouraged -- MELPA will create a `-pkg.el` file
- Also, I notice your repo only has one branch (and it is the `develop` branch).  There's nothing wrong with this, although if you plan to add a `master` branch in the future and make that the default branch, MELPA would prefer to point to `master` whenever possible.

**Comment by queertypes** [comment]
hi! Thanks for the feedback and double-checks.

I've addressed the linter and static check feedback in this commit: https://gitlab.com/queertypes/poe-filter-mode/commit/ee81801f2b72b3ea0792b42cc1ea10e1a4c34380

I've addressed the `-pkg.el` feedback in this commit: https://gitlab.com/queertypes/poe-filter-mode/commit/f7b3ce0e17ddda0eb181ea3518487c241a1fb495

Thanks for the note re: branches. I won't add a `master` branch in the future. If ever there's a need for a more stable branch than `develop`, I'll name it `stable`. Thanks!

**Comment by riscy** [comment]
Have you seen this package? https://melpa.org/#/poe-lootfilter-mode  Are these trying to do the same thing?

**Comment by queertypes** [comment]
I hadn't seen that. Very cool! Seems to provide slightly more functionality, as well. :)

I'm confirming - they do basically the same thing (provide syntax highlighting). The key difference currently is that:

- jdodds's poe-lootfilter-mode provides some imenu regexp support
- mine also highlights some new syntax added over the past 9 months

What would you like to do in this case? I'm fine with not having my package added to melpa if y'all feel that subtly different variations aren't needed.

**Comment by riscy** [comment]
Thanks for confirming.  Usually the best outcome is when you can contribute a patch to the existing project, and then everyone wins.  It looks like the author has been active recently, so that might be easy.

**Comment by queertypes** [comment]
Thanks for your help and review on this! I'll go ahead and close this out and defer to the existing implementation.

**Pull request closed without merging**
