### PR TITLE
add outrespace

### PR DESCRIPTION
**Pull request by articuluxe**
### Brief summary of what the package does

Outrespace is a collection of utilities to manage c++ namespaces.

### Direct link to the package repository

https://github.com/articuluxe/outrespace

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi, I gotta say, I love the intro in the readme!  Very entertaining and clever.

Few things I've noticed:

* You need to declare your dependencies in the package requirements, like `ivy`.
* Not a problem, but after declaring your `defgroup`, you can leave out the `:group 'outrespace` from all the subsequent `def`s.
* Also not a problem, but `(let ((lst '()))) can be simply `(let (lst))`, as the empty list is the same as `nil`.  (You can also call it `list` since elisp is a lisp-2, but it's up to you.)
* Might want to remove this old code: https://github.com/articuluxe/outrespace/blob/master/outrespace.el#L156  :)
* Looking at outrespace--namespace-regexp, let me take a moment to evangelize the `rx` macro.  Many people aren't aware of it, and it makes writing and maintaining complex regexps much easier.  Up to you, of course.  :)
* I see you call a function to define keys in your map when you activate the mode.  Instead, you can define the map with `defvar` at the top of the file.

I can't offer any feedback related to the C++-related code, but overall this looks very well made, very consistent with Emacs conventions.  Great job.

**Comment by articuluxe** [comment]
Hello,

Your feedback was very helpful. I have pushed fixes for the various issues you raised below. 

Thank you very much for taking the time to review the code!

**Comment by purcell** [comment]
Thanks! A little more feedback from me:
- `"C-c n"` is specified in two separate places in the file, but it's also reserved for end-users, so you must not bind it. See the [keybinding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) for more on this. Best to just tell the user in your docs how to bind their own preferred prefix key to your prefix map.
- Instead of `(make-variable-buffer-local (defvar ...`, use `defvar-local`. That's new as of Emacs 24.3. (So not *very* new...)
- Don't add `:bold t` to `:inherit highlight`. The purpose of inheriting is to get a well-themed appearance by default, and the user's theme might completely avoid bold.

Hope that helps.

**Comment by articuluxe** [comment]
Great, thanks for the advice. 

I've pushed changes to address these comments. 

Thanks again

**Comment by purcell** [comment]
Thanks, looks good. One further point is that you really shouldn't depend on and use `ivy` directly from this package: just use `completing-read`, and then the user's preferred completion system (`ido`, `ivy`, `helm`) will override it as necessary.

**Comment by articuluxe** [comment]
Thanks for the advice.  I spent some time trying to undo this dependency, but ran into a problem.

Basically it seems as if emacs’s completing-read cannot handle multiple identical keys.  Please correct me if I’m wrong in this.

In c++, it is possible to define a namespace in multiple places, which means when jumping to a namespace, there may be multiple entries whose name is identical, differing only in their buffer location.
If there is no provision to handle identical keys, then jumping to a namespace by name is random.

Ivy, however, allows me to store each specific namespace in the cdr of each element of an alist, where the car is the namespace name.  This allows non-ambiguous navigation.

I hope I’ve explained this adequately.

**Comment by alphapapa** [comment]
Ivy and Helm do make it easier by supporting both a "display" and a "real" value.  To do this with plain completing-read, you need to map the display value to the real value yourself.  It seems that you're right about it not accepting multiple identical keys, so I guess you'll have to make the keys unique by appending something to the identifiers.

**Comment by articuluxe** [comment]
OK, I've made the ivy dependency non-mandatory. If ivy is installed, the current and preferable behavior is available. Otherwise the code falls back to standard completing-read, appending unique suffixes onto the namespace identifiers. 

Thank you.

**Comment by purcell** [comment]
Great, merging now...

**Comment by purcell** [comment]
Great, merging now... welcome to MELPA!

**Comment by articuluxe** [comment]
Thank you!

**Pull request merged**
