### PR TITLE
Add recipe for ibrowse-core.

### PR DESCRIPTION
**Pull request by nicolas-graves**
### Brief summary of what the package does

This package is part of ibrowse.el : 

ibrowse stands for interactive browse, its goal is to be able to control your browser through common actions, be it on browser tabs, history or bookmarks using Emacs.

It relies on the completing-read built-in interface, and thus benefits greatly from integration with consult, marginalia and vertico.

Currently this package is only the part which allows to identify which browser is currently being used, and contains some code used by other subpackages. 

### Direct link to the package repository

https://git.sr.ht/~ngraves/ibrowse.el

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

Since the first inclusion in MELPA, I have reworked on the proper independence of functionality, which makes the package able to be split in different components, hence the recipe update.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by nicolas-graves** [comment]
Next I'll add the package `ibrowse-sql` then `ibrowse-tab`, `ibrowse-bookmark` and `ibrowse-history`, I'm doing this in order, like in contributing.org. Finally I'll update `ibrowse` once all of these are done. I'm also closing https://github.com/melpa/melpa/pull/8647

**Comment by minad** [comment]
Hi,

it seems a bit excessive to split this package up so much, since this complicates package distribution and installation by the user. Are there scenarios where users want only a subset of the components? In my packages where I am facing similar issues with core vs auxillary functionality I went with an [extensions/](https://github.com/minad/vertico/tree/main/extensions) directory. This worked well for me so far.

**Comment by nicolas-graves** [comment]
Does it really complicate user experience this much ? 
There might be users that would need only a subset of the components (the example I have in mind is if a person wants a replacement for one of the packages listed in https://github.com/nicolas-graves/ibrowse.el/blob/master/README.org). I don't have a strong opinion on that but my logic was that since some functionality is truly modular, once the burden of the package distribution paid, it would not be more complicated for the user.

**Comment by nicolas-graves** [comment]
maybe also the difference here is that I don't have a "core functionality" and then extensions. Each of the three subpackages is its own functionality. The package itself is more a collection of these three subpackages (which share common code).

**Comment by minad** [comment]
From my experience, the added maintenance effort of splitting packages over eagerly is already costly, including the MELPA review. As soon as you have registered all these small packages, it is hard to move back. The boundaries of your design are then settled. This may not matter so much if your design is stable. You still have some additional maintenance burden when you create releases.  You either bump all the package versions separately or in lock-step, but that could be an indication that they should rather be packaged together. 

I often find it helpful to look at the consequences. If your action is going to produce more work and is difficult to take back, it makes sense to be very sure about the benefits. Another example are public vs private APIs. I am quite conservative regarding making APIs public since this makes it hard to take the API back if it is suboptimal. On the other hand, this makes packages less useful and less stable as libraries. So depending on perspective the judgement differs.

Of course splitting packages makes a lot of sense if some functionality stands on its own and is useful and reusable on its on. Iirc for example Magit had some sub package like Transient (or its precedessor) included. But then it became clear that such a gui library would be useful on its own. I am not sure if this is the case in your design. From my intuition your package looks similar to other packages which face similar scenarios, e.g., EMMS, ERC or my Vertico or Corfu come with sub-components which can be used optionally. These packages are still modular but only distributed as one to reduce the maintenance burden.

As you say, the difference may be that your ibrowse is rather a collection of separate packages. In this case separate distribution is justified if the components are exchangeable, e.g., if you can replace one ibrowse-history component with yet another yahistory package. But then, your components are still coupled via the ibrowse-core component and one may get an inferior user experience when replacing a component in that way?

In the end it is a matter of preference and opinion. I hope my thoughts can be helpful nevertheless.

**Comment by nicolas-graves** [comment]
This is of course helpful, thanks. 

What's true is that the subpackages are not necessarily stabilized. I think I'll keep ibrowse-core as it is, but maybe ibrowse-sql would rather be merged into -history.el and -bookmark-firefox.el. And ibrowse-tab.el will probably be entirely rewritten once the webdriver bidi protocol is available on stable versions of chromium and firefox. 

The most sensible thing might be to wait until I feel the package stabilizes and re-evaluate the situation based on our discussion. I'm going to close this pull request for now, and will maybe reactivate the discussion in a few months, if I still feel splitting the packages makes sense.

**Pull request closed without merging**
