### PR TITLE
Add company-posframe recipe

### PR DESCRIPTION
**Pull request by tumashu**
This is the first step to rename company-childframe to company-posframe,

After I finish company-childframe, I think its child-frame code is useful for other package,
for example: pyim, ivy, flycheck ...

So I extract child-frame related code and create a new package: posframe

Now I think company-posframe is a better name :-) for company-childframe

### CODE REVIEW

**Comment by DamienCassou** [comment]
Please follow the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md).

**Comment by DamienCassou** [comment]
I'm closing this for now. Feel free to reopen when ready.

**Comment by tumashu** [comment]
more detail?

**Comment by tumashu** [comment]
This just rename the exist package, company-childframe, do you mean regard it is a really *new* package?

**Comment by DamienCassou** [comment]
Sorry about that, I don't know why I wrote that in the first place. I was probably in a hurry. You may want to use `:old-names` in the recipe.

**Comment by tumashu** [comment]
```
 You may want to use :old-names in the recipe.
```
I will add :old-names when I remove company-childframe, 

at the moment, I need company-childframe and company-posframe 
both exist and company-childframe require company-posframe

When most company-childframe's user switch to company-posframe.
I will remove company-childrame and add :old-names to company-posframe

**Comment by purcell** [comment]
Makes sense - now merged.

**Pull request merged**
