### PR TITLE
add go recipe files path

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by purcell** [comment]
I think this should actually just be `"back-ends"` rather than `"back-ends/*.el"`: the `back-ends` directory should be included as-is in the package, not flattened.

**Comment by stardiviner** [comment]
@purcell right. So I should use `:files ("back-ends" "stone.wav")` ?

**Comment by purcell** [comment]
Not quite: I'm suggesting `:files (:defaults "back-ends" "stone.wav")`

**Comment by stardiviner** [comment]
@purcell I updated my PR. Please check it out. Thanks

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
