### PR TITLE
Add recipe for axe

### PR DESCRIPTION
**Pull request by cniles**
### Brief summary of what the package does

axe provides interfaces for working with AWS resources from Emacs.  E.g., invoke Lambda functions with a buffer's contents or tail Cloudwatch Log events

### Direct link to the package repository

https://github.com/cniles/axe

### Your association with the package

I am both the author and maintainer of this package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  I believe you need to add hmac (version 0.0 since I'm not seeing a stable release) to your `Package-Requires`.  I stubbed that in and here's some quick feedback:

### axe-api.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
axe-api.el:286: Argument `host' should appear (as HOST) in the doc string
```

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- axe-api.el#L58: It's safer to sharp-quote function names; use `#'`
- axe-api.el#L138: It's safer to sharp-quote function names; use `#'`
- axe-api.el#L143: It's safer to sharp-quote function names; use `#'`
- axe-api.el#L154: It's safer to sharp-quote function names; use `#'`
- axe-api.el#L187: It's safer to sharp-quote function names; use `#'`
- axe-api.el#L82: It's safer to sharp-quote function names; use `#'`
- axe-api.el#L100: It's safer to sharp-quote function names; use `#'`
- axe-api.el#L120: It's safer to sharp-quote function names; use `#'`
- axe-api.el#L22: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- axe-api.el#L59: You can use `not` or `null`

### axe-buffer-mode.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
axe-buffer-mode.el:71: Argument `delay' should appear (as DELAY) in the doc string
Warning (emacs): 
axe-buffer-mode.el:88: Argument `next-token-fn' should appear (as NEXT-TOKEN-FN) in the doc string
```

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- axe-buffer-mode.el#L22: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### axe-lambda.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
axe-lambda.el:79: Argument `data' should appear (as DATA) in the doc string
```

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- axe-lambda.el#L22: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### axe-logs.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
axe-logs.el:56: Argument `success' should appear (as SUCCESS) in the doc string
Warning (emacs): 
axe-logs.el:74: First sentence should end with punctuation
Warning (emacs): 
axe-logs.el:74: Argument `success' should appear (as SUCCESS) in the doc string
Warning (emacs): 
axe-logs.el:138: Some lines are over 80 columns wide
```

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- axe-logs.el#L22: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### axe-s3.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
axe-s3.el:47: Argument `fetch-owner' should appear (as FETCH-OWNER) in the doc string
Warning (emacs): 
axe-s3.el:69: Argument `success' should appear (as SUCCESS) in the doc string
Warning (emacs): 
axe-s3.el:97: Argument `success' should appear (as SUCCESS) in the doc string
Warning (emacs): 
axe-s3.el:112: Argument `success' should appear (as SUCCESS) in the doc string
```

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- axe-s3.el#L185: No `format` required; messages are already f-strings
- axe-s3.el#L193: No `format` required; messages are already f-strings
- axe-s3.el#L22: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- axe-s3.el#L76: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### axe-util.el ###

byte-compile (using Emacs 27.1):
```
axe-util.el:103:1:Warning: the function `libxml-parse-xml-region' is not known
    to be defined.
```
Most of the time I think libxml2 support will be available, but [not always](https://www.gnu.org/software/emacs/manual/html_node/elisp/Parsing-HTML_002fXML.html).  Not a blocker, but you may want to document this and/or use `libxml-available-p` to give a user-warning.

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- axe-util.el#L59: It's safer to sharp-quote function names; use `#'`
- axe-util.el#L21: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### axe.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- axe.el#L24: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by riscy** [comment]
One more note --

- Prefer the default recipe if possible.
  It seems to be equivalent: `(axe :repo "cniles/axe" :fetcher github)`

**Comment by cniles** [comment]
I've applied all feedback except the issue regarding libxml.  For the sake of expediency, could you elaborate on how to properly warn the user in the event `libxml-available-p` fails. (even if it's just a reference to some elisp that does what you're mentioning).  Either case, I'll figure it out and put something in.

Thank you for taking the time to review my package!

**Comment by cniles** [comment]
@riscy I believe all feedback has been applied, including warning if libxml2 is unavailable.  See `axe-util.el#L36`.

**Comment by riscy** [comment]
Looks great.  Thanks!

**Pull request merged**
