### PR TITLE
Add prefab Package

### PR DESCRIPTION
**Pull request by LaurenceWarne**
### Brief summary of what the package does

Prefab is a tool aiming to provide integration for project generation tools like [cookiecutter](https://github.com/cookiecutter/cookiecutter).  A video demo can be found in the README.

### Direct link to the package repository

https://github.com/LaurenceWarne/prefab.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Apologies for the delay on reviewing this one, I got a little bit backlogged.  The code looks great, and thank you so much for your adherence to the checklist.

I'm wondering about the package name and summary line - I think `prefab` makes sense in a general way, but on first glance this appears to be geared toward the use of cookiecutter which (I think?) is restricted to Python projects.  To help discoverability/disambiguation, maybe the package name should mention `cookiecutter` and/or Python projects?

**Comment by LaurenceWarne** [comment]
> Apologies for the delay on reviewing this one, I got a little bit backlogged. The code looks great, and thank you so much for your adherence to the checklist.

No problem at all, and thanks :slightly_smiling_face: 

> I'm wondering about the package name and summary line - I think prefab makes sense in a general way, but on first glance this appears to be geared toward the use of cookiecutter which (I think?) is restricted to Python projects. To help discoverability/disambiguation, maybe the package name should mention cookiecutter and/or Python projects?

`cookiecutter ` is not restricted to generating Python projects (as an example here's an `eldev` template I put together: https://github.com/LaurenceWarne/cookiecutter-eldev) though it does need a Python installation.  I did originally use the project name `cookiecutter`, but I thought something more general like `prefab` would be appropriate when/if more tools are integrated - though granted currently only cookiecutter integration is implemented.  What do you think?

**Comment by riscy** [comment]
Okay, yep!  I didn't realize cookiecutter as that general, and that sounds fine to me if there's possible expansion into other tools in the future.  Still I'd suggest including 'cookiecutter" in your summary line to aid in discoverability, e.g. "Integrated project generation with cookiecutter", but that's not a blocker.


A couple other minor things:
- "retuned" -> "returned"
- I wonder if there is some benefit to having `prefab--cookiecutter-conf` check whether that file actually exists (`file-exists-p`), and not actually halting but leaving a message or a y/n prompt for the user

**Comment by LaurenceWarne** [comment]
> "retuned" -> "returned"

I don't know how you managed to spot that, thanks :smile: 

> I wonder if there is some benefit to having prefab--cookiecutter-conf check whether that file actually exists (file-exists-p), and not actually halting but leaving a message or a y/n prompt for the user

The file existence is optional, `None` as an arg just indicates there's no config and the next step would just be to use the template defaults only.  Hopefully the last commit makes this clearer in the [doc](https://github.com/LaurenceWarne/prefab.el#customisation), along with some of the other changes you mentioned.  Thanks again!

**Pull request merged**
