### PR TITLE
Add recipe for chezmoi.el

### PR DESCRIPTION
**Pull request by tuh8888**
### Brief summary of what the package does

Provides functions to help interact with [chezmoi](https://www.chezmoi.io/), a dotfile management package, from emacs. Provides equivalents to find-file and save-buffer which maintain source and target state appropriately. Also integrates with Dired.

### Direct link to the package repository

https://github.com/tuh8888/chezmoi.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.    Some quick feedback:

- The `Commentary` looks like it was overlooked
- Avoid using `|` as a variable/function name separator.  The community style is hyphens only (so-called kebab-case).  Normally package-lint picks these up, but I think it has an exception for `|` not for use as a separator, but to allow functions to use reference `|` as a logic symbol.
- I believe `(shell-command (concat "chezmoi add " file))` is going to have trouble with files that contain special characters, like apostrophes and ampersands and other characters that could interact with the shell.  You should use `(shell-quote-argument file)` here.

**Comment by tuh8888** [comment]
Thanks for your feedback. I believe I've made the suggested changes. Anything else you can think of?

**Comment by riscy** [comment]
Thanks for accommodating. :)  One more thing I'll add is that your `;;; Commentary` should be wrapped (by you) because the things that display this assume it's preformatted -- e.g. see the MELPA index page for [magit](https://melpa.org/#/magit).  `M-q` should do the trick.

I trust that one's an easy one to fix, so no blockers -- and welcome to MELPA. :)

**Comment by tuh8888** [comment]
Cool, didn't know about `M-q`. Fixed and thanks for merging me!

**Pull request merged**
