### PR TITLE
Add ghub and glab recipes

### PR DESCRIPTION
**Pull request by tarsius**

### CODE REVIEW

**Comment by vyp** [comment]
Just in case you forgot or something, tarsius/glab doesn't exist yet! :wink:

**Comment by syohex** [comment]
`tarsius/glab` is missed. https://github.com/tarsius/glab returns 404 status code. And `ghub` can be used only Emacs 25 or higher version because it uses `pcase-lambda`. But it does not specify minimum Emacs version.

**Comment by tarsius** [comment]
Now they do (`glab` had the same issue).

**Comment by purcell** [comment]
Yay, thanks.

**Pull request merged**
