### PR TITLE
Add efar

### PR DESCRIPTION
**Pull request by suntsov**
### Brief summary of what the package does

This package provides FAR-like file manager for Emacs.

### Direct link to the package repository

https://github.com/suntsov/efar

### Your association with the package

I'm author and maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick (automated) first pass --

### efar.el ###

byte-compile (using Emacs 27.1):
```
efar.el:2948:1:Warning: the following functions are not known to be defined:
    w32-shell-execute, comint-send-input
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
efar.el:45: White space found at end of line
```

package-lint (using version 20210127.158):
```
22 issues found:
376:31: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
378:31: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
380:31: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
382:31: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
386:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
388:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
390:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
393:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
395:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
397:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
399:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
402:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
404:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
406:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
408:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
410:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
416:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
418:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
420:34: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
431:33: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
433:33: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
435:35: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
```

Other [lints](https://github.com/riscy/melpazoid):
- efar.el#L1808: It's safer to sharp-quote function names; use `#'`
- efar.el#L1861: It's safer to sharp-quote function names; use `#'`
- efar.el#L1466: It's safer to sharp-quote function names; use `#'`
- efar.el#L2945: It's safer to sharp-quote function names; use `#'`
- efar.el#L2188: It's safer to sharp-quote function names; use `#'`
- efar.el#L2189: It's safer to sharp-quote function names; use `#'`
- efar.el#L2190: It's safer to sharp-quote function names; use `#'`
- efar.el#L23: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- efar.el#L3: Have you done the paperwork or is this copy-pasted?
- efar.el#L843: Could this point/point-min comparison use `bobp`?
- efar.el#L1769: This double negation can be collapsed (`not` aliases `null`)
- efar.el#L1263: Use `when ...` instead of `unless (null ...)`
- efar.el#L1169: Prefer `(eq major-mode 'xyz)`
- efar.el#L2188: Loading a package should rarely add hooks -- consider implementing a mode
- efar.el#L2189: Loading a package should rarely add hooks
- efar.el#L2190: Loading a package should rarely add hooks

**Comment by riscy** [comment]
I'll mark this one awaiting upstream, but please feel free to message if you've got any questions.

**Comment by suntsov** [comment]
Hello Chris,

Thank you for the checking and pointing to the errors!

Recently I merged branch for the version 1.0 into the master. Byte-compile and checkdoc problems are solved there.

The issues with reserved key sequences I wouldn't fix. I have three arguments against this:
1. I used lot's of original FAR shortcuts and would like to keep them.
2. All key bindings which I set are local key bindings and therefore actual for eFar buffer only.
3. There is a possibility to customize any eFar key binding if user wants to.

Most of "other lint" issues I fixed. 
Honestly I don't understand what does "efar.el#L3: Have you done the paperwork or is this copy-pasted?" mean.
I also ignored remarks about hooks for now. I plan to implement a mode in one of the next version, though I have no clue how it could help to avoid warnings about hooks (I'm newbie in Emacs Lisp, sorry).

And I have a question regarding 'awaiting-upstream' label. What does it mean? Do I need to do anything else or just wait?

Kind regards,
Vladimir Suntsov

**Comment by suntsov** [comment]
I have got one more question: what is the utility you used to get "other lints" please?

**Comment by riscy** [comment]
> What does [awaiting upstream] mean?

That means we're waiting for a fix/change to happen upstream (your repo) before looking again.

> Have you done the paperwork or is this copy-pasted?

I should improve that nag. :)  Some folks copy-paste "Copyright Free Software Foundation" into their file's boilerplate, but unless you've signed your copyright to the FSF then the copyright is yours.

> what is the utility you used to get "other lints" please?

There's a link ('lints'): https://github.com/riscy/melpazoid -- sometimes they raise more false positives than they need to, so I usually hand-check them before pasting them along.

It will probably be the weekend before I take an actual close look at the code and I can sympathize with your rationale, but the reserved keybindings and auto-hooks major issues.  When in doubt you can suggest users configure the package in such a way in their config, but this shouldn't happen simply because they loaded the file.

**Comment by suntsov** [comment]
Alright, I reread Emacs Lisp documentation about hooks and now I think I understand more about mode hooks. But most likely I won't have time to change that in the near future.

As for keybindings I'd still keep them as they are now unless it prevents publishing the package to the MELPA. Will wait for your closer look at package. 
Thank you for your work!

**Comment by riscy** [comment]
> I'd still keep them as they are now unless it prevents publishing the package to the MELPA

Yes, I'd push back against indexing any package that doesn't meet these criteria; both the reserved keybindings and auto-hooks are major issues.  But I'm happy to discuss alternatives/options (e.g. answer any questions about writing a mode, etc.)  Ultimately there's no hurry to index everything in MELPA.

Also in the meantime I'll bump this question: is the copyright yours, or FSF's?

**Comment by suntsov** [comment]
Alright, I'll think of a way to overcome keybinding issues. Maybe I can provide a separate optional .el file with keybinding customizations.
For the major mode implementation I might need help. Most likely I will come later back to you with questions :) Thanks!

> Also in the meantime I'll bump this question: is the copyright yours, or FSF's?

What does your question exactly mean? 
Honestly I do know almost nothing about copyright stuff. This is a first project I'm going to share with people outside my development team at work. I just added license as Github proposed. Would appreciate any explanation from your side how that usually works.

**Comment by riscy** [comment]
> What does your question exactly mean?

At the top of your file you wrote "Copyright (C) 2021 Free Software Foundation, Inc.", but I would have expected to have seen "Copyright (C) 2021 <your name here>".

**Comment by suntsov** [comment]
Hello Chris,

I have implemented major mode and changed the way of keybinding definition.
Besides one issue Melpazoid is happy now with the code :) 
Not sure how critical this issue is (Prefer `define-derived-mode`). Not much, I hope.

The changes are in the master branch. I would appreciate if you could take a look again.

**Comment by riscy** [comment]
Thank you for accommodating, that puts the checklist behind us.

> Not sure how critical this issue is (Prefer define-derived-mode). Not much, I hope.

This is the modern way to define a mode because it handles all of the expected mode boilerplate for you.  For example, a mode should ideally have a hook that users can customize, and `define-derived-mode` will create one automatically.  Don't worry, it's not too far from what you've got -- I'd suggest something like:
```elisp
(define-derived-mode efar-mode fundamental-mode "eFar"
    :group 'efar
    (if (not ...
```
Then you don't have to explicitly kill local variables, you don't have to specify use-local-map, you don't have to explicitly set major-mode and mode-name, you don't have to explicitly create and run hooks for your major mode, etc.  Although I don't know what the purpose of this is, which seems unnecessary in the mode definition `(setq mode-line-format (list " " mode-line-modes))`.

I also notice the way you're defining the keymap `efar-mode-map` can clobber some user customizations because every time the mode is activated the keymap is redefined.  Instead you can `(defvar efar-mode-map (let ((keymap (make-sparse-keymap))) [insert the code for efar-mode-set-keys here but modify keymap instead] keymap) "Keymap for eFar buffer.")  That way the keymap is defined once, when the package is loaded, and if users modify it before or after loading the package their customizations won't disappear.

**Comment by suntsov** [comment]
Thanks for pointing this out. I changed the way of mode and keymap definition. I also removed (setq mode-line-format ...).
The changes are contained  in the last merge to master branch.

**Comment by riscy** [comment]
I got a chance to experiment with this -- this is a fun package.

This is improving but I think there are still a couple of issues to work out before we merge, but I do like where this is headed.

I feel like the solution for your keymap definitions is unnecessarily complex (involving "registering" a bunch of mappings on lines 333-490 by declaring every single keymap as its own custom variable using some metaprogramming in a cl-loop, and then later applying them into a proper keymap on line 3578).  I'd just localize all of this code inside `efar-mode-map` and let users modify the `efar-mode-map` variable -- if they choose to -- rather than introducing all of this machinery.

You call `ido-completing-read` in several places, but if you just use plain old `completing-read` (if possible) then users of different completion managers will be able to benefit from those managers' hooks.

I just noticed this, but the community elisp style differs a bit from what you're using: there should be a space between your function name and its argument list, e.g. `(defun efar-search-int-start-search(args)` should be `(defun efar-search-int-start-search (args)`; similarly the elisp convention for indicating predicates is `x-predicate-p` instead of `x-predicate?`

Your `;;; Commentary` contains at least one very long line and should be word-wrapped to something reasonable so it displays well in the MELPA index (the MELPA index cannot possibly know where to do wordwrapping because long lines may contain necessarily long code)

The symbols you chose for borders seem to not be universally interpretable, e.g. here's what this looks like when I run Emacs in terminal mode:
image

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now -- feel free to reach out.

**Comment by suntsov** [comment]
Hello Chris,

Sorry for the long absence. Coronavirus has pity on no man - and I'm no different than anybody else...

Now I've fixed all coding style issues, commentary and ido-completing-read.
The changes are committed to the master.

Honestly, I don't know how do what you propose for keymap definitions. How users will customize keybindings via efar-mode-map? And also please take into account that all this machinery is not only intended to support keys customization, but for some other things, like displaying hints and buffer with key binding descriptions, as well.

I also don't know what to do with border symbols.  I don't see adequate replacement... Do you have any ideas?
Characters I choose are UTF8 one, so from my understanding they should displayed correctly if UTF8 is supported by Emacs. BTW, i don't have such a problem when running in terminal mode.

**Comment by riscy** [comment]
I apologize for letting this slip - I need a better workflow for removing the awaiting label.

> i don't have such a problem when running in terminal mode.

This is probably just my setup then, not to worry. :)

> Honestly, I don't know how do what you propose for keymap definitions. How users will customize keybindings via efar-mode-map? And also please take into account that all this machinery is not only intended to support keys customization, but for some other things, like displaying hints and buffer with key binding descriptions, as well.

On another look I see you're being fairly exhaustive with everything you bind, so maybe customization isn't something you had in mind.  I think it's fine as is, although running `(setq efar-keys '())` at the top level seems like it shouldn't be unnecessary - but not a blocker.

**Comment by suntsov** [comment]
No worries. Thanks a lot for merging!
I've got one question - what is a process of updating the package in melpa? What are my steps to publish a new version?

**Pull request merged**
