### PR TITLE
Add consult-dash

### PR DESCRIPTION
**Pull request by orki**
### Brief summary of what the package does

Consult interface to dash-docs. Requires /bin/sh.

### Direct link to the package repository

https://codeberg.org/ravi/consult-dash.git

### Your association with the package

I am the sole author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [  ] I have confirmed some of these without doing them

Note that both the byte-compiler and package-lint produce warnings due to the presence of `with-eval-after-load`. Those are the only issues of which I am aware, but I have no idea how to fix them. Those additional features provided by the two `with-eval-after-load` blocks are not worth moving to their own packages.

### CODE REVIEW

**Comment by riscy** [comment]
Currently it looks like the byte-compiler will throw an error (completely fail, not just warn) if embark and/or marginalia aren't installed, so users wouldn't be able to fully install this.  You *could* "fix" this by hiding the form from the byte compiler by quoting it (e.g. `(with-eval-after-load "x" (eval '(progn ...))`).

But simply loading a package should cause few side effects like these (unless there's some strong existing convention e.g. with `auto-mode-alist`).  Most things like this should happen as a result of the user explicitly calling a function or toggling a mode off or on, like `(consult-dash-setup-embark)`.  I feel this is especially true in this case, because your automatic modifications are reaching into the internals of these packages by relying on private functions like `consult-dash--open-url` and `marginalia--fields`).

This note on avoiding side effects also applies to the `advice-add`; let the users do these sorts of things themselves, so that they can undo them or remove them from their configuration in cases when they don't need them.

**Comment by orki** [comment]
Since `embark-define-keymap` is a macro from `embark`, there is no way for the byte compiler to work without having already loaded `embark`. Is the right solution a combination of hiding the functionality behind the suggested `consult-dash-setup-embark` *and* the use of `eval`? Perhaps @oantolin has a suggestion here.

Another difficulty with both `consult` and `marginalia` is that the line between public APIs and private APIs is a bit more nuanced. As far as I can tell, `consult-XXX` (note single dash) are public functions intended to be used by the end user, but library functions that are intended to be used by other packages are denoted `consult--XXX` (note double dash), the same as purely internal functions. `marginalia--fields` is a similar example from `marginalia`. @minad, the author of both consult and marginalia,  will likely correct me if my understanding is incorrect.

**Comment by minad** [comment]
> Another difficulty with both consult and marginalia is that the line between public APIs and private APIs is a bit more nuanced. As far as I can tell, consult-XXX (note single dash) are public functions intended to be used by the end user, but library functions that are intended to be used by other packages are denoted consult--XXX (note double dash), the same as purely internal functions. marginalia--fields is a similar example from marginalia. @minad, the author of both consult and marginalia, will likely correct me if my understanding is incorrect.

For Marginalia the situation is not nuanced at all. *All Marginalia APIs are private.* There is no point in using Marginalia in packages, since you can write your own annotation functions directly without Marginalia. The only *marginal* advantage of Marginalia is that you profit from the formatting functions, but this is really negligible. For example the packages Citar, Dtache and Org-Roam implement their own annotation functions without Marginalia. This is the recommended approach. See the `:annotate` argument of `consult--read`. See also the note https://github.com/minad/marginalia#adding-custom-annotators-or-classifiers.

For Consult the situation is indeed nuanced. The APIs are still private since I want to encourage developers to just use plain `completing-read` and I want to reserve the ability to still make careful changes to the APIs. There are significant relevant benefits to use `consult--read` in special scenarios.

1. Asynchronous completion commands, e.g., `consult-ripgrep` or in this case `consult-dash`. 
2. Multi source commands or sources, see `consult--multi`
3. Commands which take advantage of preview and narrow support of `consult--read`, e.g., `consult-buffer`.

**Comment by minad** [comment]
> Since embark-define-keymap is a macro from embark, there is no way for the byte compiler to work without having already loaded embark. Is the right solution a combination of hiding the functionality behind the suggested consult-dash-setup-embark and the use of eval? Perhaps @oantolin has a suggestion here.

Don't use `embark-define-keymap`. Define your keymap with `defvar`, `make-sparse-keymap` etc. This will solve the issue you are facing.

**Comment by oantolin** [comment]
As usual, I fully agree with @minad: one shouldn't use embark-define-key map, that's primarily meant for embark itself and may be useful for users in their configuration but should not be used by package authors as it creates a spurious dependency on embark.

**Comment by minad** [comment]
@orki It is okay to use `with-eval-after-load` for Embark integration. The package lint warning in this case can be ignored.

**Comment by orki** [comment]
That is indeed much preferable, thanks. Readded automatic embark integration.

**Comment by orki** [comment]
@riscy Do you have any further concerns?

**Comment by riscy** [comment]
Apologies, I had a busy weekend and a busy week ahead - I'll look again soon. :)

**Comment by riscy** [comment]
Thanks for your patience.  Here's the latest --

`consult-dash.el` with byte-compile using Emacs 28.1:
```
consult-dash.el:221:58: Warning: reference to free variable
    `embark-general-map'
consult-dash.el:222:17: Warning: reference to free variable
    `embark-keymap-alist'
consult-dash.el:222:17: Warning: assignment to free variable
    `embark-keymap-alist'
consult-dash.el:224:41: Warning: reference to free variable
    `embark-default-action-overrides'
consult-dash.el:224:21: Warning: assignment to free variable
    `embark-default-action-overrides'
```
You can pacify the byte-compiler by using `defvar` on the free variables (e.g. `(defvar embark-general-map)`).  


`consult-dash.el` with checkdoc 0.6.2:
```
consult-dash.el:41: First sentence should end with punctuation
```

`consult-dash.el` with package-lint 20220607.738:
```
1 issue found:
226:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

I think @minad's advice is valid (so this won't be a blocker), but I'll continue to be stubborn and recommend against using `with-eval-after-load` (e.g. what should users do if they like consult-dash but don't like the effect it has on their use of embark?)

**Comment by orki** [comment]
@riscy Made the required byte compiler changes for the missing variables. I need to figure out a better way to test byte compiler errors without needing to run `emacs -q` first.
While it is conceivable that someone might object to adding support for `embark` automatically, without this support, `embark` is entirely useless for `consult-dash` as `embark` has no idea what to do with `consult-dash` results. This change does not impact any other use of `embark`.

**Comment by minad** [comment]
@riscy Using `with-eval-after-load` is the right approach here. Embark requires registration of target keymaps. It is perfectly fine from the side of Embark to do it like this and as @orki wrote it will not affect any other use of Embark. I suspect that all users who use both consult-dash and Embark want the packages to collaborate.

There are the following alternatives, which I think are worse:

1. Define a global minor mode which performs the registration, which just adds unnecessary complexity. I think modes should be reserved for things which are supposed to be toggled interactively.
2. Let the user to register the keymap manually. This will lead to more effort for most of the users. In contrast, far fewer users may profit, the ones who don't want the registration.

In general I am also against `with-eval-after-load` but there are very few scenarios, where it seems justified, e.g., registration of functionality in other packages and tiny bits of gluing code which lets packages interact. If a much larger amount of integration code is needed, a separate integration package is the way to go, e.g. `embark-consult` However in this case we are talking about three lines of registration code.

@orki You should write this in a more concise style. This should do:

~~~ elisp

(defvar consult-dash-embark-keymap
  (let ((map (make-sparse-keymap)))
    (define-key map "y" #'consult-dash-yank-candidate-url)
    map)
  "Actions for consult dash results.")

(with-eval-after-load 'embark
  (setq consult-dash-embark-keymap (make-composed-keymap consult-dash-embark-keymap embark-general-map))
  (add-to-list 'embark-keymap-alist '(consult-dash-result . consult-dash-embark-keymap))
  (setf (alist-get 'consult-dash-result embark-default-action-overrides) #'consult-dash--open-url))
~~~

**Comment by orki** [comment]
@riscy Made the changes as @minad suggested: moving the key definition into the keymap creation, and inline definition of the code previously inside the embark-enable function.

Years of programming on tiny microprocessors makes me sensitive to unnecessary code and threading issues, and hence not defining anything in the keymap until necessary. However, I reworked it as suggested. The defvars are still necessary to avoid compiler warnings if embark is not loaded at compile time.

**Comment by riscy** [comment]
Thanks for the discussion above, all.  In this small case I won't insist on the `with-eval-after-load` issue, but I'm not intending to set a precedent here.  I prefer to err on the side of "[strict](https://instagram-engineering.com/python-at-scale-strict-modules-c0bb9245c834)".  That's enough on this package-lint though, we can move past it.

I also mentioned the automatic `advice-add` above -- to be more helpful I tried to familiarize myself with dash-docs and I think this advice is unnecessary.  It seems like [the intention in dash-docs](https://github.com/dash-docs-el/dash-docs/blob/master/dash-docs.el#L182=) is to let users define `dash-docs-docsets` as they see fit, so why introduce *another* variable (`consult-dash-docsets`) that does the same, but requires a potentially fragile wrapper?

Since I'm looking past the checklist I can also see the `;;; Commentary` could use some work.  You could mention the keybinding that gets is being quietly added, talk about the motivation for the package, etc.  Also the `;; To do` header can be written `;;; To do:` so that your developer todo-list isn't showing up in the package's description in the MELPA index (you can run `(lm-commentary)` to double-check).

**Comment by orki** [comment]
I'd love to get rid of the extra `consult-dash-docsets` variable; however, it is possible that one may want to have both `helm-dash` and `consult-dash` available. Due to the history of `dash-docs`, the variable `dash-docs-docsets` is intended to be used with `helm-dash`. For example, the `dash-docs` authors decided themselves that [an extra variable is necessary for counsel-dash](https://github.com/dash-docs-el/counsel-dash/blob/master/counsel-dash.el#L57).

I did not know about the sectioning of the commentary section. Added. There is no keybinding that is quietly added; an *entirely new keymap* has been created which does not impact any existing keymaps. These keybindings cannot be pressed by accident; in particular, these keybindings are explicitly shown prior to use in the embark buffer (sole buffer from which they can be used).

**Comment by minad** [comment]
@orki I agree with @riscy that the usage of an advice for the docsets does not seem appropriate. Maybe you could work with dash-docs upstream to find a better solution if this is really necessary. Maybe dash-docs could introduce some hook? But I also think that you could just get rid of the additional variable and advice without any obvious downsides.

**Comment by riscy** [comment]
Apologies for the delay.  I think we can move on from the `consult-dash-docsets` variable and merge this one in.  Thanks again for this -- and thanks everyone for the valuable discussion. :)

And @orki -- welcome to MELPA!

**Pull request merged**
