### PR TITLE
Add ivy-hydra, modify ivy

### PR DESCRIPTION
**Pull request by abo-abo**
Fixes https://github.com/abo-abo/swiper/issues/464

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. The first element of the recipe form for `ivy-hyrda` should be `ivy-hydra`, but it's currently `ivy` -- that's the reason for the build failure. Please could you update that?

**Comment by purcell** [comment]
<kbd>C-c C-c</kbd> lets you test these recipes locally, btw, which we recommend.

**Comment by abo-abo** [comment]
> C-c C-c

Thanks, a very nice feature. I've force-pushed on the PR, should be correct now.

**Comment by purcell** [comment]
Super, thank you.

**Pull request merged**
