### PR TITLE
fix(4clojure.el): update to maintained working fork of 4clojure.el

### PR DESCRIPTION
**Pull request by Macavirus**
### Brief summary of what the package does

Open and evaluate 4clojure questions.

### Direct link to the package repository

https://github.com/abend/4clojure.el

### Your association with the package

User. 

### Relevant communications with the upstream package maintainer

Current package maintainer @losingkeys has not updated his package in a long time and no longer works with current emacs versions. @abend has a maintained fork that works as expected.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Have we tried to get in touch with @losingkeys about passing over maintainership?  And is @abend okay with helping bring the package up to the latest MELPA checks?  Here's a quick pass through the checklist:

### 4clojure.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
4clojure.el:44: First sentence should end with punctuation
Warning (emacs): 
4clojure.el:44: Argument `problem-number' should appear (as PROBLEM-NUMBER) in the doc string
Warning (emacs): 
4clojure.el:59: First sentence should end with punctuation
Warning (emacs): 
4clojure.el:59: Argument `problem-number' should appear (as PROBLEM-NUMBER) in the doc string
Warning (emacs): 
4clojure.el:66: First line is not a complete sentence
Warning (emacs): 
4clojure.el:66: Argument `problem-number' should appear (as PROBLEM-NUMBER) in the doc string
Warning (emacs): 
4clojure.el:75: First sentence should end with punctuation
Warning (emacs): 
4clojure.el:75: Argument `problem-number' should appear (as PROBLEM-NUMBER) in the doc string
Warning (emacs): 
4clojure.el:80: First line is not a complete sentence
Warning (emacs): 
4clojure.el:80: Argument `problem-number' should appear (as PROBLEM-NUMBER) in the doc string
Warning (emacs): 
4clojure.el:89: First line is not a complete sentence
Warning (emacs): 
4clojure.el:89: Argument `problem-number' should appear (as PROBLEM-NUMBER) in the doc string
Warning (emacs): 
4clojure.el:107: First line is not a complete sentence
Warning (emacs): 
4clojure.el:107: Argument `problem-number' should appear (as PROBLEM-NUMBER) in the doc string
Warning (emacs): 
4clojure.el:107: Name emacs should appear capitalized as Emacs
Warning (emacs): 
4clojure.el:121: Second line should not have indentation
Warning (emacs): 
4clojure.el:121: First line is not a complete sentence
Warning (emacs): 
4clojure.el:121: Argument `problem-number' should appear (as PROBLEM-NUMBER) in the doc string
Warning (emacs): 
4clojure.el:138: First line is not a complete sentence
Warning (emacs): 
4clojure.el:150: First sentence should end with punctuation
Warning (emacs): 
4clojure.el:150: Argument `problem-number' should appear (as PROBLEM-NUMBER) in the doc string
Warning (emacs): 
4clojure.el:170: First sentence should end with punctuation
Warning (emacs): 
4clojure.el:170: Argument `problem-number' should appear (as PROBLEM-NUMBER) in the doc string
Warning (emacs): 
4clojure.el:176: All interactive functions should have documentation
Warning (emacs): 
4clojure.el:191: First line is not a complete sentence
Warning (emacs): 
4clojure.el:200: First line is not a complete sentence
Warning (emacs): 
4clojure.el:210: First sentence should end with punctuation
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
12 issues found:

1:0: error: Package should have a Homepage or URL header.
8:23: error: Package json is not installable.
43:0: error: `4clojure/get-question-cached' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
58:0: error: `4clojure/questions-for-problem' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
65:0: error: `4clojure/first-question-for-problem' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
74:0: error: `4clojure/description-of-problem' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
79:0: error: `4clojure/restrictions-for-problem' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
88:0: error: `4clojure/start-new-problem' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
106:0: error: `4clojure/format-problem-for-buffer' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
120:0: error: `4clojure/get-answer-from-current-buffer' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
137:0: error: `4clojure/problem-number-of-current-buffer' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
149:0: error: `4clojure/check-answer' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems)
(the following is with lexical binding enabled)
```
4clojure.el:98:88:Warning: `beginning-of-buffer' is for interactive use only;
    use `(goto-char (point-min))' instead.

In 4clojure/check-answer:
4clojure.el:166:3:Warning: assignment to free variable `result'
4clojure.el:166:3:Warning: reference to free variable `result'

In end of data:
4clojure.el:244:1:Warning: the following functions are not known to be
    defined: function*, first
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other static checks:
- 4clojure.el#L60: It's safer to sharp-quote function names; use `#'`
- 4clojure.el#L115: It's safer to sharp-quote function names; use `#'`
- 4clojure.el#L102: It's safer to sharp-quote function names; use `#'`
- 4clojure.el#L96: Single-line comments should begin with `;;`
- 4clojure.el#L3: This copyright notice may need updating.
- 4clojure.el#L21: Prefer `https` over `http` (if possible)
- 4clojure.el#L49: Prefer `https` over `http` (if possible)
- 4clojure.el#L96: Prefer `https` over `http` (if possible)
- 4clojure.el#L152: Prefer `https` over `http` (if possible)
- 4clojure.el#L179: Prefer `https` over `http` (if possible)
- 4clojure.el#L183: Prefer `https` over `http` (if possible)

**Comment by Macavirus** [comment]
I have already raised an issue with @losingkeys about the specific fix he needs to merge that is fixed in @abend fork, but he has not been responsive so far. I have not mentioned to him transferring melpa ownership. Meanwhile @abend fork has no way to raise issues. Perhaps neither is the appropriate repo owner. 

Thanks for the checks. I think this can be on hold for now until either of them take notice, or I fix this myself and resubmit.

**Comment by riscy** [comment]
Great.  Thank you for doing this, btw -- it's great to see useful packages getting lasting maintainership.

**Comment by abend** [comment]
Hi all,

I'm happy to take over maintainership.  I just enabled issues in my fork.  I can work on the MELPA requirements brought up by @riscy as well.

**Comment by Macavirus** [comment]
Great @abend! Thanks for the fix

**Comment by tarsius** [comment]
It would be best if the old upstream repository was transferred to the new "owner". Not sure if that works between user accounts, but transferring to the [Emacs orphanage](https://github.com/emacsorphanage) might be transferable and that only requires that I temporarily make @losingkeys a member and that he then performed the transfer.

@losingkeys would you be interested in doing that? Has anyone tried contacting him by email yet?

**Comment by losingkeys** [comment]
Hello! Sorry for the radio silence on this. Happy to transfer ownership. Do I just move the GitHub project?

Appreciate the contributions!

**Comment by tarsius** [comment]
Yep. I just invited you so you can do that now.

**Comment by losingkeys** [comment]
Done. Let me know if it didn't work :)

**Comment by tarsius** [comment]
Great thanks!

Do you want to keep write access to this repository or should I remove you again?

**Comment by tarsius** [comment]
I've invited @abend to the moved repository.

**Comment by losingkeys** [comment]
No thanks. If I have contributions I'll open PRs :).

**Pull request closed without merging**
