### PR TITLE
Add Harpoon

### PR DESCRIPTION
**Pull request by otavioschwanck**
### Brief summary of what the package does

Harpoon plugin for emacs, based on ThePrimeagen for vim.

This plugin offers quick bookmarks separated by project and branch. You can quick navigate between your working files and forget about that files opened that you will not use anymore.

Harpoon persists between emacs sessions.

### Direct link to the package repository

https://github.com/otavioschwanck/harpoon.el

### Your association with the package

Maintainer

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Have you had a chance to compare to other bookmakring packages such as https://melpa.org/#/bookmark-in-project for example? (I'm not personally too familiar with the bookmarking ecosystem in Emacs).

Besides that, a couple fairly minor suggestions:

- The customization type for `harpoon-separate-by-branch` looks like it should be boolean instead of string, if I'm not mistaken
- "Bookmarks with steroids" would probably be more conventionally written "Bookmarks on steroids" 
- harpoon.el#L50: Customizable variables shouldn't be private
- harpoon.el#L54: Customizable variables shouldn't be private
- harpoon.el#L203: Top-level `define-key` can sometimes overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`

**Comment by the-moriarty** [comment]
> Thanks for this! Have you had a chance to compare to other bookmakring packages such as https://melpa.org/#/bookmark-in-project for example? (I'm not personally too familiar with the bookmarking ecosystem in Emacs).
> 
> Besides that, a couple fairly minor suggestions:
> 
> * The customization type for `harpoon-separate-by-branch` looks like it should be boolean instead of string, if I'm not mistaken
> * "Bookmarks with steroids" would probably be more conventionally written "Bookmarks on steroids"
> * harpoon.el#L50: Customizable variables shouldn't be private
> * harpoon.el#L54: Customizable variables shouldn't be private
> * harpoon.el#L203: Top-level `define-key` can sometimes overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`

Fixed all the points except the define-key (for some raeson dindt work:)
```
(defvar harpoon-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "<return>") #'harpoon-find-file)))
```

About the harpoon VS others:  It only applies in branch instead per project and has a interface to re-order, delete, and go-to.

**Comment by otavioschwanck** [comment]
> Thanks for this! Have you had a chance to compare to other bookmakring packages such as https://melpa.org/#/bookmark-in-project for example? (I'm not personally too familiar with the bookmarking ecosystem in Emacs).
> 
> Besides that, a couple fairly minor suggestions:
> 
> * The customization type for `harpoon-separate-by-branch` looks like it should be boolean instead of string, if I'm not mistaken
> * "Bookmarks with steroids" would probably be more conventionally written "Bookmarks on steroids"
> * harpoon.el#L50: Customizable variables shouldn't be private
> * harpoon.el#L54: Customizable variables shouldn't be private
> * harpoon.el#L203: Top-level `define-key` can sometimes overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`

Fixed all the points except the define-key (for some raeson dindt work:)
```
(defvar harpoon-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "<return>") #'harpoon-find-file)))
```

About the harpoon VS others:  It only applies in branch instead per project and has a interface to re-order, delete, and go-to.

**Comment by riscy** [comment]
> Fixed all the points except the define-key (for some raeson dindt work:)

It may be because `defvar` by design won't overwrite an existing variable, which is why it's better to use than a top-level define-key.  Let me know if that helps!

**Comment by the-moriarty** [comment]
> (defvar harpoon-mode-map
>   (let ((map (make-sparse-keymap)))
>     (define-key map (kbd "<return>") #'harpoon-find-file)))

Fixed!

**Comment by otavioschwanck** [comment]
> > Fixed all the points except the define-key (for some raeson dindt work:)
> 
> It may be because `defvar` by design won't overwrite an existing variable, which is why it's better to use than a top-level define-key. Let me know if that helps!

Fixed!

**Comment by riscy** [comment]
Thanks!  Ready to merge, but I have a couple minor things I didn't notice the first time around -- not blockers but I recommend fixing these in order of importance from first to last:

- `harpoon--create-directory` uses `shell-command` to call mkdir and create a directory, but Emacs has a builtin `make-directory` function that you should be using instead
- The commentary should probably wrap at around 79 characters by convention if possible
- Even though it makes me sound like an unfun ogre, I would avoid frowny faces `=(` and other embellishments like exclamation marks in package messages, e.g. `File not found. =(` and `File added to harpoon!`
- Similar to your package summary, no need to write "for Emacs" in the doc for `defgroup harpoon` -- "Organize bookmarks by project and branch" would be the best high-level summary from my perspective
- Hhe -> The
- dont exists -> doesn't exist

**Comment by the-moriarty** [comment]
Thanks for the tips, fixed!

**Pull request merged**
