### PR TITLE
Add recipe for non-edit-mode

### PR DESCRIPTION
**Pull request by aragaer**
### Brief summary of what the package does

Minor mode that disables most editing commands (but not all) to protect the file from accidental editing.

### Direct link to the package repository

https://gitlab.com/aragaer/non-edit-mode

### Your association with the package

Created this package for myself.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
It would be useful to know how this differs from the built-in "special-mode".

**Comment by aragaer** [comment]
It is a minor mode that can be used with any other major mode. It was inspired by vim/evil command mode.

**Comment by progfolio** [comment]
Got ya. Then a comparison to view-mode would be more appropriate.

**Comment by aragaer** [comment]
It allows some "high-level" editing like copy/paste, moving around org subtrees, setting properties and tags -- again, similar to command mode in vim.

**Comment by riscy** [comment]
Thanks for this.  I think this is a cool idea, but details like those above would be good to add to your `;;; Commentary`.  (I might've also asked "how's this different from `read-only-mode`?" if not for the conversation.)

I'd recommend extending the default list `non-edit-disabled-functions` too -- for example why not `newline-and-indent`?  Why not `delete-char`?  Have you considered default support for popular packages like evil, e.g. `evil-delete-char`?

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by aragaer** [comment]
I might be expanding the `;;; Commentary` to point out that it is "based on" evil's command mode. Basically it is a command mode but without any of the evil bindings.

Since command mode in evil does allow `delete-char`, that one is not disabled. I am not sure `newline-and-indent` is available as a simple keystroke, but `indent-for-tab-command` is again, similar to `=` in evil command mode.

**Comment by riscy** [comment]
I see now - I like the analogy to vi command mode that you've written, that made things click for me.

**Pull request merged**
