### PR TITLE
create hsluv recipe

### PR DESCRIPTION
**Pull request by woozong**
### Brief summary of what the package does

This package provides an Elisp implementation of the HSLUV colorspace conversions as created by Alexei Boronine (@boronine), and documented on http://www.hsluv.org/
HSLuv is a human-friendly alternative to HSL.
CIELUV is a color space designed for perceptual uniformity based on human experiments. When accessed by polar coordinates, it becomes functionally similar to HSL with a single problem: its chroma component doesn't fit into a specific range.
HSLuv extends CIELUV with a new saturation component that allows you to span all the available chroma as a neat percentage.

### Direct link to the package repository

https://github.com/hsluv/hsluv-emacs

### Your association with the package

Maintainer of the Emacs implementation of HSLuv
Contributor to the hsluv org on github. 

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, looks good, but you'll need to declare a package dependency on the version of `seq` that's in GNU ELPA. :-)

**Comment by woozong** [comment]
@purcell I assume
`  ;; Package-Requires: ((seq "2.20"))`
would be sufficient? (my first package here ;-))

**Comment by woozong** [comment]
package dependency added to [hsluv.el](https://github.com/hsluv/hsluv-emacs/blob/master/hsluv.el)

**Comment by purcell** [comment]
Great, thanks - merged! Welcome to MELPA. :tada:

**Comment by woozong** [comment]
Oh woohoo :-)

**Pull request merged**
