### PR TITLE
add consult

### PR DESCRIPTION
**Pull request by minad**
### Brief summary of what the package does

This package provides various commands based on completing-read: consult-buffer (buffer/recent file switching), consult-line (swiper-like search), consult-mark (select from the mark ring), ... It is meant to be used together with icomplete/selectrum as a substitute for ivy/counsel.

### Direct link to the package repository

https://github.com/minad/consult

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
A few notes, as requested:

1.  `defcustom` forms need not specify the group when listed after a `defgroup` in the same file.
2.  I see `consult-fontify-limit`.  I haven't read all the code, but I'm guessing that means that you fontify whole buffers in some commands.  Instead, you could probably font-lock just the regions that are to be displayed in the commands using `font-lock-ensure` with a start and end point.
3.  Macro `consult--gc-increase` could be named something like `consult-with-increased-gc`, which would be more idiomatic.
4.  The macro `consult--preview` could use a more descriptive docstring, and maybe name.  I can't easily understand its purpose.
5.  Some other docstrings are also not very descriptive, like `consult--preview-line`'s.
6.  Is it necessary to use `letrec` here?  https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L290  If not, it would probably be better not to.  As it is, I don't understand why it's necessary.
7.  It's a matter of style, but loops like this tend to be more readable using `cl-loop`, IMO, especially with its built-in destructuring: https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L363
8.  Back to item 2, I see this: https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L497  That's probably an example of where you should font-lock just the regions to be displayed.  (That's what Helm generally does, AFAIK, and it works well.)
9.  This is a matter of style, and opinions vary, but this one-symbol-per-line formatting makes code very difficult to read, IMO: https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L642  I think sometimes we adhere too rigidly to line-length targets, which obfuscates the natural "shape" of the code, which makes it harder to recognize patterns.
10.  This function should probably be called `consult-toggle-mode` or something like that, because the name `consult-minor-mode` implies that there is a minor mode by that name: https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L740
11.  This looks useful: https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L751  I have a similar command in my config.  The docstring should mention that it disables active themes first.
12.  Again, docstrings like this do not explain what the function's purpose is or how it works: https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L845

Hope that helps.

**Comment by minad** [comment]
> I see consult-fontify-limit. I haven't read all the code, but I'm guessing that means that you fontify whole buffers in some commands. Instead, you could probably font-lock just the regions that are to be displayed in the commands using font-lock-ensure with a start and end point.

When

**Comment by minad** [comment]
Thank you for looking.

I agree, some docs/names can be improved and will be. But for example consult--preview is actually an internal internal function, it is a helper for an internal function, that does not mean it shouldn't have better docs though ;).

Some answers:

> 2. I see consult-fontify-limit. I haven't read all the code, but I'm guessing that means that you fontify whole buffers in some commands. Instead, you could probably font-lock just the regions that are to be displayed in the commands using font-lock-ensure with a start and end point.

Unfortunately there is no other way. consult-line takes the whole buffer, chops it in pieces and presents it in the minibuffer. consult-line is the swiper implementation. For this to work I must fontify the whole buffer. Some of the other commands could be optimized regarding to this, but I think it is ok like this. Afaik Ivy/Swiper has some limit too.

> 6. Is it necessary to use letrec here? https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L290 If not, it would probably be better not to. As it is, I don't understand why it's necessary.

This is precisely the letrec usage from https://www.gnu.org/software/emacs/manual/html_node/elisp/Local-Variables.html

> 7. It's a matter of style, but loops like this tend to be more readable using cl-loop, IMO, especially with its built-in destructuring: https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L363

Maybe. I have a different style than you. I prefer functional style, smaller composable functions etc. I am a Haskeller. But that does not always work in elisp I guess. Still, I don't like to have a DSL for loops. But no need to discuss things like this ;)

> 8. Back to item 2, I see this: https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L497 That's probably an example of where you should font-lock just the regions to be displayed. (That's what Helm generally does, AFAIK, and it works well.)

This is precisely the case where it won't work.

> 9. This is a matter of style, and opinions vary, but this one-symbol-per-line formatting makes code very difficult to read, IMO: https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L642 I think sometimes we adhere too rigidly to line-length targets, which obfuscates the natural "shape" of the code, which makes it harder to recognize patterns.

Indeed. Does not look nice. I should reformat this. But please let's not talk too much style.

> 10. This function should probably be called consult-toggle-mode or something like that, because the name consult-minor-mode implies that there is a minor mode by that name: https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L740

Yes, I actually got already confused by this myself :laughing: But the general naming scheme of consult is `consult-thing` :)
Maybe I kick this function out in the end. It is not really useful tbh.

> 11. This looks useful: https://github.com/minad/consult/blob/814e1e27629fdba97e3fe7eb9d8274b14c857a6c/consult.el#L751 I have a similar command in my config. The docstring should mention that it disables active themes first.

It does more than you think maybe. It immediately shows the theme via the preview function when scrolling through the candidates. Pretty nice.

**Comment by alphapapa** [comment]
> But for example consult--preview is actually an internal internal function, it is a helper for an internal function, that does not mean it shouldn't have better docs though ;).

Yes, I always advocate for every function to be properly documented, whether internal or not.  It's always frustrating to be trying to understand a package or fix a bug and trace execution to a function that has no docstring and is not easy to understand.  Without a docstring, I have to spend time deciphering a function that might end up being unrelated to the problem, while a well-written docstring could have saved me the time.  Being Emacs, where every line of code is available and intended to be viewable, it's a courtesy to others to take a few moments to write a docstring.

> Unfortunately there is no other way. consult-line takes the whole buffer, chops it in pieces and presents it in the minibuffer. consult-line is the swiper implementation. For this to work I must fontify the whole buffer. Some of the other commands could be optimized regarding to this, but I think it is ok like this. Afaik Ivy/Swiper has some limit too.

What if you only presented candidates that match the input?  Then wouldn't you only need to fontify certain lines?

> Maybe. I have a different style than you. I prefer functional style, smaller composable functions etc. I am a Haskeller. But that does not always work in elisp I guess. Still, I don't like to have a DSL for loops. But no need to discuss things like this ;)

As you probably know, one of the benefits of Lisps is being able to write small DSLs to express ideas more clearly and concisely.  Lisp is compatible with any style, including functional, compositional, imperative, iterative, etc.

In Elisp, specifically, functional and compositional programming incurs a performance penalty due to function call overhead.  `cl-loop` has the benefit of generating very efficient code from concise expressions.  In performance-sensitive code, using `cl-loop` is generally going to perform much better than a purely functional style.

> Indeed. Does not look nice. I should reformat this. But please let's not talk too much style.

You did ask for my feedback.  In MELPA reviews, we commonly give style-related feedback, because it relates to the readability of the code, which affects how easy it is to review the code, understand it, and modify it--and one of the reasons people use Emacs is that all of the code is available to read, learn from, and modify.  That's why we, and the Elisp manual, recommend following certain coding conventions.  Writing code that's consistent with certain patterns benefits the whole, even if it sometimes goes against personal preferences.

> It does more than you think maybe. It immediately shows the theme via the preview function when scrolling through the candidates. Pretty nice.

Cool, that's like Helm's "persistent actions" feature, which allows the user to execute an action on a candidate while "persisting" the Helm session (rather than exiting it and acting on the chosen candidate).

**Comment by minad** [comment]
>  What if you only presented candidates that match the input? Then wouldn't you only need to fontify certain lines?

That's right. But consult-lines always starts presenting everything from the get go.

> As you probably know...

I am aware of the things you write regarding cl-loop :) I appreciate your pov and I use cl-loop or dolist etc in performance sensitive parts of the code, for example the consult-line-candidates function which is responsible for the startup cost of consult-line.

> Cool, that's like Helm's "persistent actions" feature, which allows the user to execute an action on a candidate while "persisting" the Helm session (rather than exiting it and acting on the chosen candidate).

Is it? I think it is more like the ivy preview feature? If you consider using icomplete/selectrum + consult + marginalia, then one should also add embark to the set of packages, since this is providing actions. It provides a function embark-act-noexit, which sounds more like the helm persistent actions to me.

**Comment by alphapapa** [comment]
> > What if you only presented candidates that match the input? Then wouldn't you only need to fontify certain lines?
> 
> That's right. But consult-lines always starts presenting everything from the get go.

What's the value of that?  The user can already see all of the lines, because he's already looking at the whole buffer when he calls the command, right?  So if you wait for input to get candidates, and only fontify matching candidates, you could avoid the performance problem, and you could fontify candidates in buffers of any size.  Why not do this?

> > Cool, that's like Helm's "persistent actions" feature, which allows the user to execute an action on a candidate while "persisting" the Helm session (rather than exiting it and acting on the chosen candidate).
> 
> Is it? I think it is more like the ivy preview feature? ... It provides a function embark-act-noexit, which sounds more like the helm persistent actions to me.

What's the difference in the end result?  When displaying themes, Helm's persistent action previews them without exiting the Helm session.

> If you consider using icomplete/selectrum + consult + marginalia, then one should also add embark to the set of packages, since this is providing actions.

On one hand, having 5 modular packages that each do a specific job sounds nice and clean.  On the other hand, it begins to feel like a combinatoric explosion, like I'd have to learn what each of those things do, and which one I should choose, and then configure each one...  But Helm does all of those things, and it does them well.  Thierry has put years of work into making Helm fast and flexible.  So I don't see much reason to switch away from Helm.  It's kind of like the difference between using Vim, piping its buffers to several different shell commands, and using Emacs's built-in commands that do the same thing with a keystroke.  But WFYB.

**Comment by minad** [comment]
> What's the value of that? The user can already see all of the lines, because he's already looking at the whole buffer when he calls the command, right? So if you wait for input to get candidates, and only fontify matching candidates, you could avoid the performance problem, and you could fontify candidates in buffers of any size. Why not do this?

Sure I could do that. But this is not how it is designed and I like to keep it that way. It is a matter of design/taste. You have to try it and then you can see if you like it how it works or not. Furthermore there is no real performance problem. The fontify limit is just a safe guard and Emacs also has safe guards for long lines, large files etc. It works very well for small and medium files up to lets say 20000 loc for quick navigation. You should also consider that doing this per-candidate/per-region fontification adds complexity and potential bugs. If I can avoid it, I do. Since the design already forces me to do it that way, there is not much to argue I think. The design comes before the optimization - only if it turns out that the design is fundamentally not viable. But it is.

> What's the difference in the end result? When selecting themes, Helm's persistent action previews them without exiting the Helm session.

Maybe none. But I am not a Helm user. There is an architectural difference however, but this might not be relevant to the user of such a feature.

> On one hand, having 5 modular packages that each do a specific job sounds nice and clean. On the other hand, it begins to feel like a combinatoric explosion, like I'd have to learn what each of those things do, and which one I should choose, and then configure each one... 

When you would have asked me a while ago I would have agreed. And let's say - for a beginner user this does sound complicated. However if you look into the internals of those packages - they are not depending on each other. They are designed in a way such that they only rely on the Emacs APIs. One package does one thing well and independent of the rest. This automatically forces a natural separation of what each package does. And you potentially have options to switching out components, e.g., selectrum<->icomplete-vertical. You can chose precisely what you want. You can configure everything of this in Helm too I guess, but it is different to building up from bottom than building down from the top. Therefore I think configuration will not be more complicated than the Helm configuration. If I look at my init.el, selectrum/icomplete need nearly no configuration, they simply do the thing they are supposed to do, marginalia just adds annotations and needs no configuration except if you want to annotate some of your own (broken) commands, which do not report the correct category. It should work out of the box for new commands which adhere to the rules. Now consult is a bit of a different kind. Since it offers utilities and I prefer not force any keybindings upon the user, you have to configure the keybindings. But that's okay for me.

> But Helm does all of those things, and it does them well. Thierry has put years of work into making Helm fast and flexible. So I don't see much reason to switch away from Helm. 

Yes, I respect the work put into Helm and appreciate all the great ideas which originate from there and also from Ivy. However when I tried Helm the first time it didn't feel right to me for various reasons. Now the approach of using smaller components and adding functionality step by step, understanding it step by step fits me better. This is highly subjective.

**Comment by minad** [comment]
@alphapapa Maybe I should add one thing to my answer regarding the consult-line candidates. As I said, currently all completion candidates are generated up-front, all lines are shown. As of now there is also a technical reason for this - dynamically generating candidate lists is a bit of a pain point of the completing-read api. We are currently trying to sort this, but it is complicated. After having done that, it would be possible to implement what you suggested, filtering the lines after the first characters and then presenting only those.

**Comment by purcell** [comment]
Thanks for this, looking forward to trying to replace `ivy`/`counsel` with this and `selectrum` etc.

Same point about avoiding `:weight` etc. when specifying faces as `:inherit`, but otherwise looks good, so merging. :tada:

**Comment by minad** [comment]
Thank you for merging. If you have any feedback, please let us know! Expect some rough edges around, the packages are still young!

**Comment by minad** [comment]
@purcell Also note the Embark package by @oantolin which will bring actions to the mix. As far as I understood it will be proposed soon for inclusion on Melpa. Currently some refactoring is in progress which aligns the package with marginalia.

**Comment by purcell** [comment]
> If you have any feedback, please let us know! Expect some rough edges around, the packages are still young!

Looks good so far. What I'm really missing from my `ivy` habits is a replacement for `counsel-ag` so I can `rg` symbols and then optionally jump into an occur buffer. Is that something likely to fit with `consult`? If so, I'd be happy to look at providing code.

**Comment by minad** [comment]
> Looks good so far. What I'm really missing from my ivy habits is a replacement for counsel-ag so I can rg symbols and then optionally jump into an occur buffer. Is that something likely to fit with consult? If so, I'd be happy to look at providing code.

Yes, it is on the wish list (https://github.com/minad/consult/issues/6) and also just now https://github.com/minad/consult/issues/46. However there is some roadblock with regards to the completing-read API support of Selectrum. I hope this will be addressed soon.

**Pull request merged**
