### PR TITLE
WIP: Add missing files after use-package refactor

### PR DESCRIPTION
**Pull request by nickmccurdy**
This is a work in progress. The current recipe for `use-package` is broken (except in MELPA Stable) because some of the package code has been extracted to other files that are not included yet. Installing the package with the new recipe no longer produces https://github.com/jwiegley/use-package/issues/533 but does display the following errors on load:

```
Warning (use-package): Unrecognized keyword: :ensure
Warning (use-package): Unrecognized keyword: :delight
Warning (use-package): Unrecognized keyword: :diminish
```

### Brief summary of what the package does

A use-package declaration for simplifying your .emacs

### Direct link to the package repository

https://github.com/jwiegley/use-package

### Your association with the package

Contributor

### Relevant communications with the upstream package maintainer

@jwiegley
https://github.com/jwiegley/use-package/issues/533#issuecomment-348852211

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by marsam** [comment]
I think the patch could be written as:

```diff
diff --git a/recipes/use-package b/recipes/use-package
index 761adf92..55bc0fa8 100644
--- a/recipes/use-package
+++ b/recipes/use-package
@@ -1,4 +1,4 @@
 (use-package
     :fetcher github
     :repo "jwiegley/use-package"
-    :files ("use-package.el"))
+    :files (:defaults (:exclude "bind-key.el")))
```

**Comment by purcell** [comment]
> I think the patch could be written as:

Yes, that would be better. I'm a bit sad that @jwiegley has decided to arbitrarily abbreviate the filenames to `up-*`: they still define `use-package-` symbols, and I always ask people to match up the filenames within a package to avoid unexpected clashes with other packages later.

**Comment by nickmccurdy** [comment]
@marsam Good idea, just committed this. I think the unrecognized keyword issue still stands though, so probably not ready to merge yet (unless we want to deploy this to at least get `use-package` partially working until we figure that out).

**Comment by jwiegley** [comment]
@purcell I was unaware that this was a frowned upon naming procedure. It's what Eshell does, and Org-mode does, and a few other packages besides, to avoid unnecessarily long filenames within a package. The loaded symbols are still all within the same namespace.

**Comment by jwiegley** [comment]
@nickmccurdy How are you loading use-package that it triggers these errors? The file `use-package.el` requires `up-diminish.el`, `up-delight.el`, and `up-ensure.el`, which each add handling for their respective keywords to `use-package-keywords`.

**Comment by manuel-uberti** [comment]
@jwiegley since I have this error too, this is how I load `use-package` in my `init.el`:
```
;; Bootstrap `use-package', `diminish' and `dash'
(unless (and (package-installed-p 'use-package)
             (package-installed-p 'diminish)
             (package-installed-p 'dash))
  (package-refresh-contents)
  (package-install 'use-package)
  (package-install 'diminish)
  (package-install 'dash))
```

**Comment by nickmccurdy** [comment]
@jwiegley Good point, I forgot about org-mode's naming convention. I've been loading it with this (simplified version of my [.emacs](https://github.com/nickmccurdy/dotfiles/blob/master/home/.emacs)).

```emacs
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "http://orgmode.org/elpa/")
                         ("gnu" . "https://elpa.gnu.org/packages/")))
(package-initialize)
(package-refresh-contents)
(package-install 'use-package)
```

**Comment by purcell** [comment]
> I was unaware that this was a frowned upon naming procedure.

I wouldn't say frowned-upon, but when the filenames don't have a common prefix, there's the possibility of future name clashes just like with symbols. I'd happily have accepted an "up" package without wondering about (or, likely, even being aware of) whether its "up-core.el" file might get confused with the same-named file in `use-package`, so it just seems prudent to choose the names with care. Once abbreviated file names are in Emacs itself, then that's an automatic win, obviously. :-)

**Comment by iced** [comment]
why it is not merged yet?

**Comment by purcell** [comment]
> why it is not merged yet?

@iced Because we are volunteers and not available 24 hours a day to service requests.

**Comment by iced** [comment]
no offense was intended ;) all involved - ty for fix.

**Comment by jwiegley** [comment]
@purcell That makes sense, how about once we get the current version working, we'll coordinate the name change after so it doesn't disrupt anyone this time?

**Comment by bostonaholic** [comment]
Good news: The changes have propagated to melpa.

Bad news: New errors caused by other packages referencing functions that were pulled into the new `up-core.el`.

```

**Comment by scmanjarrez** [comment]
@bostonaholic Any available workaround to fix the "use-package-core" void variable?

**Comment by jwiegley** [comment]
This is something for me to fix. Working on it.

**Comment by jwiegley** [comment]
This is now fixed in 9145e7c.

**Comment by jwiegley** [comment]
Or it should be, can someone please test and confirm?

**Comment by natecraig** [comment]
@jwiegley 9145e7c fixed the use-package-core void variable. Thank you!

**Comment by marsam** [comment]
btw, the recipe must be update to also exclude `bind-chord.el` which belongs to [bind-chord](https://github.com/waymondo/use-package-chords/blob/master/bind-chord.el) package.

**Comment by scmanjarrez** [comment]
@jwiegley 9145e7c fixed the void variable issue. Thanks!

**Comment by jwiegley** [comment]
Note that bind-chord and system-packages are both completely optional dependencies. I've changed the project so that it can even successfully byte-compile without them present.

So, these definitely shouldn't be auto-installed by MELPA simply by installing use-package. They are opt-in features for users that have separately installed key-chord, and who then declare `(use-package use-package-chords)`.

**Comment by jwiegley** [comment]
Also, there is now a Makefile in `use-package`, which can be use as `make` to compile, `make test` to run the tests, and `make install` to build and install. I copied the template for these Makefiles from Magit, so many thanks to @tarsius.

**Comment by jwiegley** [comment]
@scmanjarrez A user is reporting in https://github.com/jwiegley/use-package/issues/540 this same `use-package-core` error. Is MELPA not yet updated?

**Comment by scmanjarrez** [comment]
@jwiegley No, MELPA hasn't been updated yet. I updated it manually.

**Comment by bostonaholic** [comment]
Melpa is still showing `(commit 3f7e98)`

**Comment by bostonaholic** [comment]
Melpa is now using `(commit 05015c)` of use-package. I have confirmed that the fix works! Thanks @jwiegley.

**Comment by jwiegley** [comment]
Yay, disasters averted. Expect this to quiet down again now. All issues in the tracker but one have been resolved, and I have no further feature work planned. Next steps are documentation, and integration into Emacs.

**Comment by cjauvin** [comment]
I must be doing something wrong but.. I have updated to MELPA 20171204.1321 (05015c), and I'm now having a bunch of:
```
Error (use-package): Failed to parse package whole-line-or-region: Symbol’s function definition is void: gensym
Error (use-package): Failed to parse package sublime-themes: Symbol’s function definition is void: gensym
Error (use-package): Failed to parse package spacemacs-theme: Symbol’s function definition is void: gensym
Error (use-package): Failed to parse package spaceline: Symbol’s function definition is void: gensym
Error (use-package): Failed to parse package exec-path-from-shell: Symbol’s function definition is void: gensym
Error (use-package): Failed to parse package project-explorer: Symbol’s function definition is void: gensym
Error (use-package): Failed to parse package web-mode: Symbol’s function definition is void: gensym
Error (use-package): Failed to parse package projectile: Symbol’s function definition is void: gensym
Error (use-package): Failed to parse package helm-projectile: Symbol’s function definition is void: gensym
```
Any idea what might cause this?

**Comment by nayefc** [comment]
Same .. ^

**Comment by cjauvin** [comment]
I have a question: since this update is currently killing my whole Emacs environment, I'd like to revert to a previous version. However I've always been using MELPA, so I don't know which version is safe to revert to (no history seems to be provided https://melpa.org/#/use-package). Moreover, the latest release, https://github.com/jwiegley/use-package/releases/tag/2.3, seems too ancient, at more than a year ago. So I'd like to get a safe commit hash version, and bonus points if I get a clear set of steps explaining how to perform the required manual downgrade steps.. Thanks!

**Comment by ZzAntares** [comment]
You don't need to downgrade HEAD is working fine the problem, as I understand, has to be with the MELPA build which now they say it works but I'm having the same problem as yours.

The way I solved is `cd` into the `~/.emacs.d/elpa/use-package-20171204.1321/`, then erase everything there `rm -rf ./*` (careful with that) and clone `git clone <use-package repo> .` (don't forget that last dot), finally restart Emacs.

Today I learned why the Emacs pros tend to manage their packages with git, so in cases like this, you just checkout a prior working commit.

**Comment by jwiegley** [comment]
I didn't realize that `gensym` was only introduced in Emacs 26. This issue has been resolved by defining `use-package-gensym`.

**Comment by terlar** [comment]
For me it solved the `gensym` issue by `(require 'cl)` before `use-package`. But I guess that is the old deprecated stuff / cl-version before the prefixes.

**Comment by cjauvin** [comment]
@terlar I'm making progress:

```Error (use-package): Cannot load spacemacs-theme
Symbol's function definition is void: diminish
```

**Comment by s-kostyaev** [comment]
> I didn't realize that gensym was only introduced in Emacs 26
@jwiegley `package-lint` can help you

**Comment by terlar** [comment]
@cjauvin that is fine. `diminish` has become an optional dependency, so if you are using that you have to explicitly add that package now, like mentioned in the breaking changes of https://github.com/jwiegley/use-package/blob/master/NEWS.md#breaking-changes

**Comment by nickmccurdy** [comment]
MELPA is now up to date with 066d37 (latest commit as of this comment).

**Comment by nickmccurdy** [comment]
@jwiegley After the update I still had `Unrecognized keyword` errors until added `((eval-when-compile (require 'use-package))` below my original installation code (`(package-install 'use-package)`), even though I'm not manually byte compiling. Is this a regression or was I loading `use-package` improperly?

**Comment by manuel-uberti** [comment]
FWIW, I delete `use-package` and just reinstalled from MELPA. Upon restarting Emacs (with the snippet in my `init.el` I posted above), `use-package` was correctly installed with no errors and no warnings.

**Comment by nickmccurdy** [comment]
@manuel-uberti Try adding `(eval-when-compile (require 'use-package))` after `(package-install 'use-package)` like in my previous comment. It fixed it for me, but I don't know why.

**Comment by KrullBorg** [comment]
adding (eval-when-compile...) works for also for me, thanks

**Comment by purcell** [comment]
> That makes sense, how about once we get the current version working, we'll coordinate the name change after so it doesn't disrupt anyone this time?

Sounds good. The new formulation of this recipe (with `:excludes`) should make things fairly future-proof, though.

**Comment by purcell** [comment]
> > I didn't realize that gensym was only introduced in Emacs 26
> 
> @jwiegley package-lint can help you

True, but `package-lint` is also not currently great for multi-file packages.

**Comment by purcell** [comment]
BTW, all, sorry it took a while for the package to get re-built after merging this recipe. It was late night here in New Zealand and it didn't occur to me to force an immediate rebuild.

**Comment by manuel-uberti** [comment]
@nickmccurdy thanks for the tip. This what I have now after deleting `use-package`, adding `(eval-when-compile (require 'use-package))` and restarting Emacs:
```
Error (use-package): shell/:catch: Variable binding depth exceeds max-specpdl-size
```

**Comment by nickmccurdy** [comment]
@purcell In retrospect, I think I should actually exclude more including `bind-chord` and the packages we're moving into the `use-package` repository. I'll probably send a PR for that soon.

Also if a `use-package` contributor can confirm which files should be in the main package or in separate packages that would be awesome. I'm mostly confused about if the optional `use-package` plugins (for example `use-package-chords`) should be separate packages, or only their dependencies (for example `bind-chord`).

**Comment by nickmccurdy** [comment]
@manuel-uberti Looks like you have this issue: https://github.com/jwiegley/use-package/issues/550

**Comment by jwiegley** [comment]
@manuel-uberti I've made changes to address the `max-specpdl-size` problem; can you please try the latest again and let me know if it works?

**Comment by manuel-uberti** [comment]
@jwiegley reinstalled it from MELPA, I confirm the mentioned error is gone now. Thank you.

**Pull request merged**
