### PR TITLE
Add gn-mode recipe

### PR DESCRIPTION
**Pull request by lashtear**
### Brief summary of what the package does

A major-mode for editing GN (ninja generator) config files in Emacs. Files of this type (e.g. BUILD.gn or *.gni) are common in Chromium-derived projects like Chrome and (Anaheim) Edge.

### Direct link to the package repository

https://github.com/lashtear/gn-mode

### Your association with the package

Author / maintainer / recipe writer

### Relevant communications with the upstream package maintainer

None needed yet!

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).

    The package is licensed with BSD 3-clause

- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

    ಠ_ಠ

### CODE REVIEW

**Comment by riscy** [comment]
Also one `package-lint` warning: ```1:73: warning: You should depend on (emacs "24") if you need lexical-binding.```

**Comment by lashtear** [comment]
Great review, thanks!

I hadn't considered `evil-mode`-- I'll try to do so in the future as it really does change motion commands.  I've implemented your fix.

The end-of-buffer related text loss is particularly bad, but apparently never came up because everything is "usually" under-indented.  `(point-max)` shrinking beneath the prior end violates several invariants there, so I've replaced `e` with a (hopefully more readable) `cl-symbol-macrolet` called `work-end` that always evaluates that `min` with `(point-max)`.  Alternatively, we could use a marker, but I think this is lower overhead.

I don't need lexical-binding, but it was strongly advised by the MELPA submission process.  I should have run package-lint again afterward-- added the `(emacs "24")` dependency.

Please take a look at the 0.4 release now; these should all be fixed.  Again, thanks for looking!

**Comment by riscy** [comment]
I'm not a MELPA maintainer -- just a fellow contributor -- but it's working great for me now.

**Comment by riscy** [comment]
Checking back, I may have been wrong about the `forward-char` thing -- it seems like evil doesn't move the cursor backward except after some interactivity.  Sorry for the confusion. :)

**Comment by lashtear** [comment]
Even so, `forward-line` is a bit more clear about what is intended, I think, so leaving that as-is unless there is other trouble with it.  Again, thanks for looking!

**Comment by purcell** [comment]
Looks great now, thanks. Merging now!

**Pull request merged**
