### PR TITLE
Add recipe for js-pkg-mode

### PR DESCRIPTION
**Pull request by ovistoica**
### Brief summary of what the package does

A comprehensive minor mode for working with JavaScript/TypeScript projects that supports multiple package managers (npm, yarn, pnpm, bun, deno). Provides convenient keybindings for common package management tasks like installing dependencies, running scripts, and managing project files.

Post on reddit about package: 
https://www.reddit.com/r/emacs/comments/1h5w9qg/jspkgmode_a_minor_mode_for_working_with/

### Direct link to the package repository

https://github.com/ovistoica/js-pkg-mode

### Your association with the package

I am the maintainer of this package.

### Relevant communications with the upstream package maintainer

None needed - this is a new package that I maintain.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

Note: Please verify the checklist items are actually true for your package before submitting.

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

⸺ `js-pkg-mode.el` with package-lint 20241127.1826:
```
1 issue found:
127:41: error: You should depend on (emacs "28.1") if you need `lock-file'.
```
I believe this is a false positive but we can strive for a clean package-lint anyway. What I'd recommend doing with this is to just rename the variable to `lock-file_` (it only appears local to that function); this avoids the naming collision with the built-in (although the builtin is a function, not a variable) and pacifies package-lint.

⸺ `js-pkg-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- js-pkg-mode.el#L189: No `format` required; `message` takes an f-string
```

I'll also point out https://github.com/jakoblind/js-import which I think is different but still inside this "javascript project" space; fyi, mostly.

**Comment by ovistoica** [comment]
Thank you for the review. I changed `lock-file` -> `lock-file_` to appease package-lint. 

That is an excellent suggestion regarding js-import. I didn't know about it. I will add it as extra functionality in the future. 

For now, I will put a link in the readme for people to be aware of it

**Comment by ovistoica** [comment]
```
- js-pkg-mode.el#L189: No `format` required; `message` takes an f-string
```
- Fixed

**Comment by ovistoica** [comment]
Updated README to point to `js-import` for import functionality (for now)

**Comment by riscy** [comment]
> I will add it as extra functionality in the future.

If you do so it would be awesome if you could work with @jakoblind, if it turns out it's better for users to have only one package in this space to refer to.  But obviously not a blocker.

Merging, and welcome to MELPA. :)

**Pull request merged**
