### PR TITLE
Add recipe for license-templates.

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Create LICENSE using GitHub API.

### Direct link to the package repository

https://github.com/jcs-elpa/license-templates

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Are you using this to create the license file for the repo at https://github.com/jcs-elpa/license-templates.git ?   The reason I ask is that, for this repo, the GitHub API is finding `Other`, which suggests its license has a nonstandard format.

**Comment by jcs090218** [comment]
Nope, I copy the license file from my other project. I don't know why GitHub couldn't find the file though. 😕

**Comment by tarsius** [comment]
> I don't know why GitHub couldn't find the file though.

It appears to "find" the file. (The "View license" link works as expected.) It just fails miserably to detect that it contains a copy of the GPLv3.


I recommend you use this package to reinsert its license. You will then notice some difference and also (and that might be more important) that you did not replace the placeholders with the appropriate values. Then check if that fixes things. Also you might want to improve the package so that it encourages users to replace the placeholders. You might also want to add a second command that also reads the file to be used as the license file instead of having the user open the file first and then insert into the current buffer.

**Comment by tarsius** [comment]
Actually prefer `LICENSE` and only offer to use another file if that already exists.

Also see https://github.com/licensee/licensee#documentation.

**Comment by jcs090218** [comment]
I believe this is a GitHub bug. Once I have removed `license-template.el` then the license can be recognized as GPLv3 as the screenshot shown below.

Image 1

I think GitHub is confused by my other file that has prefix with word `license`? 😕

**Comment by tarsius** [comment]
You should file a bug report and while you are waiting for that to get fixed you should probably add a note about this to the readme or else potential users are likely to ignore it.

**Comment by jcs090218** [comment]
> You should file a bug report

I had file a bug report, they are using [licensee](https://github.com/licensee/licensee) for their license parsing. I will report this issue directly to `licensee` repo.

> while you are waiting for that to get fixed you should probably add a note about this to the readme or else potential users are likely to ignore it

I already have a badge represent `GPL v3` in my readme file. Would this be enough? 😕

**Comment by tarsius** [comment]
No. I was thinking something along the lines: You might have noticed that `GPL-3.0 License` is not being displayed on the right just below `Readme` where it should be displayed. You might therefore think that this package fails miserably at its very job because the LICENSE file that it puts into the repository is what is supposed to cause the notice to appear. The fact that this does not appear to happen even for the repository of this package itself is concerning but don't worry; it is actually Github/licensee that is triping over the name of this package. Unless your package's name also begins with `license-` it in all likelihood won't be affected. See [link to issue about that].

**Comment by jcs090218** [comment]
> No. I was thinking something along the lines: ...

Added! Thanks for the advice! 👍

**Comment by riscy** [comment]
Looks good -- thanks for this and for debugging that issue with licensee.  One minor typo in the prompt (Creat should be Create) but looks good to merge.

**Pull request merged**
