### PR TITLE
Xhair

### PR DESCRIPTION
**Pull request by Boruch-Baum**
### Brief summary of what the package does

* Highlights the current line and column

This package simultaneously applies `vline-mode` and `hl-line-mode`, with tweaks, to present POINT in highlighted cross-hairs, reporting the value of POINT as a message in the echo area. This will remain in effect until toggled manually (function `xhair-mode` by default), or until the next keypress (function `xhair` by default), or for a set interval (function `xhair-flash` by default).

Note: checkdoc complains about the package keywords I've selected, but they come from Emacs 27 list.

### Direct link to the package repository

https://github.com/Boruch-Baum/emacs-xhair

### Your association with the package

Author. This is a work derived from Drew Adams' package `crosshairs.el`, with his consent and co-ordination.

### Relevant communications with the upstream package maintainer

There is a private email correspondence between me and Drew that I suppose I could share if you insist, but I would want to ask him first.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Very quick pass --

### xhair.el ###

byte-compile (using Emacs 27.1):
```
xhair.el:86:1:Error: Cannot open load file: No such file or directory, vline
```
I think vline is not available in MELPA?

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
3 issues found:
1:0: error: Package should have a Homepage or URL header.
7:38: error: Package vline is not installable.
83:35: warning: Use variable `user-emacs-directory' or function `locate-user-emacs-file' instead of a literal path to the Emacs user directory or files.
```

Other [lints](https://github.com/riscy/melpazoid):
- xhair.el#L12: Use empty lines instead of `;;` on a line by itself within your Commentary
- I think the subheadings in your `;;; Commentary` may cut the parser off early.  Try `M-: (lm-commentary)` to check

### Package ###

- GitHub API found `GNU General Public License v3.0`
- A [SPDX-License-Identifier](https://spdx.dev/ids/) is a little more machine-detectable

**Comment by Boruch-Baum** [comment]
I would like to be "commit-stingy" and get all the MELPA compliance
changes squashed into a single commit, so I have a few questions about
some of your feedback items before I make the push:


On 2021-07-04 17:11, Chris Rayner wrote:
> I think vline is not available in MELPA?

1] I have the vline package installed as a MELPA package, but I didn't
   see it on MELPA either, so I performed a check on github, and found
   that it was added to MELPA as PR#478, 2013-01-24. The directory and
   file timestamps that I have locally for the vline package is
   2017-07-16, but the directory name is vline-20120108.445.

   The package definition file `vline-pkg.el` points to a URL at
   emacswiki, so it may have been removed from MELPA as part of the
   'great purge' (issue #2342).

   My cursory web search finds no comparable package in emacs core or
   MELPA.

   I've sent an email to what I hope is a current address for the author
   of the vline package, asking him about hosting the package on a
   secure website (and I've cc'ed the email to what I hope is a current
   address for you).

> 83:35: warning: Use variable `user-emacs-directory' or function `locate-user-ema
> cs-file' instead of a literal path to the Emacs user directory or files.

2] Duh. Line 82 was a comment I wrote to myself warning me to delete
   that line before uploading. It was there for testing in \emacs -Q
   conditions.

>    Other [1]lints:
>      * xhair.el#L12: Use empty lines instead of ;; on a line by itself
>        within your Commentary

3] I've asked a question about this in my parallel response to #7622
   (cursor-flash).

>      * I think the subheadings in your ;;; Commentary may cut the parser
>        off early. Try M-: (lm-commentary) to check

4] You are correct, and that's a problem for me, but for a reason
   outside MELPA. Since 2020-10, I've been sitting on a TODO item for
   emacs-core that expects a triple semi-colon for subheadings. See
   here[1] for a point in the long emacs-devel thread that includes the
   working elisp code as an attachment.

   The attachment there is a single function that produces a (humble me)
   extremely very cool org-mode summary of all commentary *and* symbol
   docstrings *and* etc. Do try it on any of my elisp package files, or
   any of yours. It may make your day. I'm that proud of it. And you can
   see how little elisp was needed.

   What put that item on the back-burner was the usual emacs-devel
   'gimme more, gimme more'. They rightfully complained that org-mode
   takes too long to load, and wanted me to use instead an outline
   minor-mode that at the time was still in development and hadn't yet
   been released.

>      * A [2]SPDX-License-Identifier is a little more machine-detectable

5] I've asked a question about this in my parallel response to #7622
   (cursor-flash).


[1] https://lists.gnu.org/archive/html/emacs-devel/2020-10/msg01260.html


--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
>  I've cc'ed the email to what I hope is a current address for you.

I received it, thank you for taking that on!

> Do try it on any of my elisp package files, or any of yours.

Wow, that's amazing!  I tried it out on one of my packages that's broken up into sections with triple-semicolons and it generated a very nice tree.  I've been keeping my eyes open for something that would generate summary overviews of packages, for obvious reasons... :)

Let's keep an eye on that vline-mode issue for a little while and see if it gets any traction.

**Comment by Boruch-Baum** [comment]
On 2021-07-05 13:15, Chris Rayner wrote:
>      I've cc'ed the email to what I hope is a current address for you.
>
>    I received it, thank you for taking that on!

Quite welcome.

>      Do try it on any of my elisp package files, or any of yours.
>
>    Wow, that's amazing! I tried it out on one of my packages that's broken
>    up into sections with triple-semicolons and it generated a very nice
>    tree. I've been keeping my eyes open for something that would generate
>    summary overviews of packages, for obvious reasons... :)

That got me thinking:

1] Do you think I should publish it as a stand-alone package?

   I'm not certain when I'll return to continue developing it for
   emacs-core to meet the additional wish lists that they insisted on,
   and if history is any guide, there will be more additional feature
   requirements and integration requirements before they decide finally
   whether (or not!) to accept the submission. Publishing it stand-alone
   gets it to an audience *now*, and makes it available to a wider
   audience (ie. people using older versions of emacs).

2] Submit it to MELPA?

   See #1

3] My only reluctance to publishing the content is that I really really
   dislike the name `org-el-file'. Any suggestions? el-contents? pkg-layout?

4] This all is off-topic, so if you want you can respond to the above
   off-list to my email.

>    Let's keep an eye on that vline-mode issue for a little while and see
>    if it gets any traction.

It's been over two weeks and I haven't heard back. The author seems to
have a github account ***@***.***) most recently used on May 26, but I'm
not sure whether it's good etiquette to contact him there. What's the
next step?

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
> What's the next step?

I had a look around and I think there's an easy solution!  It look like we can add a MELPA recipe that points to https://github.com/emacsorphanage/vline.   It appears to be totally MELPA compatible (minus a couple of lints that I think we can let slide in this case) so I added it in 515c6cd2efaa2c330122aabd7b23f29d5e4ec27d.  I'll re-check this PR after MELPA finishes its next build cycle.

Regarding `org-el-file`, I like the idea of adding it somewhere (I'd be curious what core thinks the outstanding issues are).  Names like `pkg2org` or `pkg-summary/overview/layout` sound good to me (I'd lean toward `pkg` since a lot of el files lack deliberate layouts). :)

**Comment by riscy** [comment]
Sorry it took me the week to come back to this.  Here's the latest now that vline has been added to MELPA:

### xhair.el ###

byte-compile (using Emacs 27.1):
```
xhair.el:315:1:Warning: the following functions are not known to be defined:
    yascroll-bar-mode, yascroll:show-scroll-bar
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
2 issues found:
1:0: error: Package should have a Homepage or URL header.
83:35: warning: Use variable `user-emacs-directory' or function `locate-user-emacs-file' instead of a literal path to the Emacs user directory or files.
```

**Comment by Boruch-Baum** [comment]
On 2021-07-31 09:53, Chris Rayner wrote:
> Sorry it took me the week to come back to this.

No problem. We all do this in our *spare* time.

I've pushed a "MELPA compliance" commit that fixes the issues.

In related news, I received an email from the author of the dependency
"vline". He wasn't able to respond earlier but is willing to host the
"vline" package on his github repository. I updated him about the
emacs-orphanage work-around, and suggested he issue a PR to modify it to
point to his repository, or that he post a comment here, or that he
contact you for guidance.

Thanks much.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by buzztaiki** [comment]
@riscy 

Hi,

I'm an original author of vline.el.
I'd like to maintain vline.el in my github repository.

Should I do the following?
1. Create a vline.el repository.
2. Create a PR to update the [recipe](https://github.com/melpa/melpa/blob/master/recipes/vline).
3. Notify to https://github.com/emacsorphanage/vline that I have created the repository.

Please let me know if there is a better way.

**Comment by riscy** [comment]
Hi @buzztaiki -- I'm referring back to [this](https://github.com/melpa/melpa/pull/6555#issuecomment-576011875) comment to guess the best approach, which I think is to have the existing emacsorphanage repository transferred over to you.  But I'll ping @tarsius here just in case.

Then step 2 would be to update the recipe (the redirect should work in the meantime).

**Comment by tarsius** [comment]
I can do that but they could also just fork https://github.com/emacsorphanage/vline. There is no additional metadata that could be lost by forking instead of transferring. Once the recipe is updated I would delete emacsorphanage/vline, and so their repository would no longer appear as a fork.

If you want to transfer then tell me, but also note that you then have to accept within 24 hours or so, or the transfer is automatically cancelled.

**Comment by riscy** [comment]
Meanwhile, this PR looks ready to go.  Thanks, @Boruch-Baum!

**Comment by Boruch-Baum** [comment]
On 2021-08-01 21:22, Chris Rayner wrote:
>    Meanwhile, this PR looks ready to go. Thanks, ***@***.***!

Quite welcome. Enjoy.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by buzztaiki** [comment]
I'll just fork the https://github.com/emacsorphanage/vline and then update the recipe.
Thanks to @riscy @tarsius for letting me know!

**Pull request merged**
