### PR TITLE
Add add-hooks

### PR DESCRIPTION
**Pull request by nickmccurdy**
### Brief summary of what the package does

Function for setting multiple hooks

### Direct link to the package repository

https://github.com/nickmccurdy/add-hooks

### Your association with the package

Author and maintainer

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. There's no reason for that to be a macro, though, and it just makes the code more brittle: if it were a simple function, you'd be able to pass in a quoted list, the result of a function call, or a variable containing a list of hooks to add.

Also, please include docs in the `Commentary` section rather than referring people to the README, which won't be included in the package. Better yet, include some examples in the docstring for `add-hooks`.

**Comment by nickmccurdy** [comment]
Thank you for your feedback, I converted it to a function taking a quoted list and updated its docstring to include the rest of the readme contents.

**Comment by purcell** [comment]
Yay, much better! To be consistently prefixed, and match up with the package name, you should rename `add-hook*` to `add-hooks*`. (Also, the current example for `add-hook*` uses `add-hooks` instead of `add-hook*`.)

**Comment by nickmccurdy** [comment]
Thanks. I intentionally named `add-hook*` that way since it's a modification of `add-hook`, and I didn't want to imply that it's a modification of `add-hooks` (since `add-hooks` uses `add-hook*` internally). Do you think `add-hooks-pair` would be a more appropriate name for `add-hook*`? You're totally right about the example typo, I just fixed that.

**Comment by purcell** [comment]
> Do you think add-hooks-pair would be a more appropriate name for add-hook*?

Yes, that would be good.

**Comment by nickmccurdy** [comment]
I renamed `add-hook*` to `add-hooks-pair`.

**Comment by purcell** [comment]
Awesome - merged!

**Pull request merged**
