### PR TITLE
Add playonline

### PR DESCRIPTION
**Pull request by twlz0ne**
### Brief summary of what the package does

Play code with online playgrounds.

Can be applied to a buffer or region or code block (require markdown / org-mode)

### Direct link to the package repository

https://github.com/twlz0ne/playonline.el

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```shell
$ cask; cask build
Loading package information... done
Package operations: 5 installs, 0 removals
  - Installing [ 1/5] request (latest)... done
  - Installing [ 2/5] json (latest)... already present
  - Installing [ 3/5] dash (latest)... done
  - Installing [ 4/5] with-proxy (latest)... done
  - Installing [ 5/5] markdown-mode (latest)... done
Compiling /home/conao/dev/forks/playonline.el/cask-bootstrap.el...
Compiling /home/conao/dev/forks/playonline.el/playonline-test-helper.el...

In toplevel form:
playonline-test-helper.el:30:18:Warning: reference to free variable
    ‘with-proxy-senders’

In end of data:
playonline-test-helper.el:40:1:Warning: the function ‘with-proxy’ is not known
    to be defined.
Compiling /home/conao/dev/forks/playonline.el/playonline.el...
```

**Comment by twlz0ne** [comment]
@conao3 Don't use `cask build`, use `make`.

**Comment by riscy** [comment]
Here's a quick first pass:

### playonline.el ###

byte-compile-file (using Emacs 26.3):
```
playonline.el:535:16:Warning: reference to free variable
    `playonline--output-response-result'
```
This one looks like a typo -- as if the function isn't being called?

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200313.2338):
```
1 issue found:
8:38: error: Package json is not installable.
```
Correct me if I'm wrong but json seems to come with Emacs and I suspect it came with Emacs 24.4?

Experimental static checks/suggestions:
- playonline.el#L674: It's safer to sharp-quote function names; use `#'`

**Comment by twlz0ne** [comment]
@riscy Thanks for your review.

I have fixed these just now: https://github.com/twlz0ne/playonline.el/commit/08c702c2f0f19896712cf3c95e681f4a8d658fd9

**Comment by riscy** [comment]
I still see a `Package-Requires` on json -- is it somehow necessary?  I believe it comes with Emacs, and package-lint is flagging it as uninstallable.

**Comment by twlz0ne** [comment]
It's now deleted: https://github.com/twlz0ne/playonline.el/commit/7f20037688d92e6af67384d99abf7f9671326cd1

**Comment by riscy** [comment]
A couple quick notes on packaging -- in an [earlier PR](https://github.com/melpa/melpa/pull/6723#issuecomment-599512028) it was recommended you remove cask-bootstrap.el -- are you open to that recommendation here?

You're also quite close to being able to just use the default recipe (preferable because it means zero maintenance PR's if you decide to rename files and so forth) if you rename your test helper to e.g. `separedit-helper-test.el` or move the tests into another directory.

**Comment by twlz0ne** [comment]
Folder structure reorganized: https://github.com/twlz0ne/playonline.el/commit/463a94fc01112817d1e6e0209ea85385efcb1329

```sh
⋊> [~/.e/s/playonline] tree -I "*~|*#" .
.
├── Cask
├── LICENSE
├── Makefile
├── README.md
├── playonline.el
├── run-test.example.sh
└── test
    ├── playonline-test-helper.el
    ├── playonline-test.el
    ├── test-bootstrap.el
    └── test-checkinstall.el

```

**Comment by riscy** [comment]
This looks substantial - thanks.  I've updated the recipe to use the default recipe per your current folder structure, since I believe that's your intent.  Of course using the default recipe is preferable, but if I was wrong in that assumption, open another PR -- those ones are easy to review and merge.

Minor:
- shabang -> shebang I believe (couple places)
- responsed -> responded
- websit -> website
- statment -> statement
- definded -> defined

**Pull request merged**
