### PR TITLE
Add recipe for ttt

### PR DESCRIPTION
**Pull request by KrokodileGlue**
### Brief summary of what the package does

A simple tic-tac-toe package. Currently it only supports two-player games, but future versions will include a single-player mode.

### Direct link to the package repository

https://github.com/KrokodileGlue/tic-tac-toe

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
Did you actually run package-lint and address it's feedback?

**Comment by KrokodileGlue** [comment]
Sorry about that. I wrote an Emacs package about a year ago and thought I remembered everything. That issue has been fixed.

**Comment by alphapapa** [comment]
Cool!  But I think before this is published on MELPA it needs networked multiplayer support.

**Comment by KrokodileGlue** [comment]
Sure. I actually have most of that done already so I'll finish it up today.

**Comment by alphapapa** [comment]
D= Honestly I was just joking about the multiplayer thing...

**Comment by KrokodileGlue** [comment]
I was not joking.

**Comment by KrokodileGlue** [comment]
Ok, there we go! Basic networked multiplayer support. A little wonky still and there's still no bot to play against, but I'll add/fix that stuff some other time

**Comment by purcell** [comment]
Nice, thanks!

- As `package-lint` should have told you, you should declare a package dependency on either `cl-lib` or Emacs 24.3 since you're using `cl-lib`.
- You should add an `;;;###autoload` cookie comment for the `ttt` command.

**Comment by DamienCassou** [comment]
I'm closing for now. Feel free to open a new PR when you are ready by following instructions at https://github.com/magit/magit/wiki/Dedicated-pull-request-branches.

**Pull request closed without merging**
