### PR TITLE
Add recipe for eglot-tempel

### PR DESCRIPTION
**Pull request by fejfighter**
### Brief summary of what the package does

This package provides templated completion of function arguments when loaded with eglot mode and tempel, a simple templating library

### Direct link to the package repository

https://github.com/fejfighter/eglot-tempel

### Your association with the package

Author/Maintainer

### Relevant communications with the upstream package maintainer

pending merging of https://github.com/fejfighter/eglot-tempel/pull/4 as an external contributor will need to agree to license

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`eglot-tempel.el` with byte-compile using Emacs 28.1:
```
eglot-tempel.el:58:1: Warning: defcustom for `eglot-tempel-mode' fails to
    specify containing group
eglot-tempel.el:58:1: Warning: defcustom for `eglot-tempel-mode' fails to
    specify containing group
```

`eglot-tempel.el` with checkdoc 0.6.2:
```
eglot-tempel.el:25: First sentence should end with punctuation
eglot-tempel.el:59: First sentence should end with punctuation
```
Easy fixes!

`eglot-tempel.el` with package-lint 20230315.1052:
```
3 issues found:
46:0: error: "tempel-expand-yas-snippet" doesn't start with package's prefix "eglot-tempel".
62:9: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-add'.
64:7: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
```
I think the prefix issue is an expected yas-snippet pattern but please confirm for me.

`eglot-tempel.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- eglot-tempel.el#L38: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
```

Package and license:
- Add a LICENSE file to the repository
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to eglot-tempel.el

**Comment by mattiasb** [comment]
The URL is misspelled btw. :) Should be: https://github.com/fejfighter/eglot-tempel

**Comment by fejfighter** [comment]
@riscy Sorry, I had hoped that the branch with those fixes bundled with the licence inclusion would have seen approval by now. I have split out the fixes (except the licence change) and merged those.

@mattiasb you'd think I'd know how to type my own user name - fixed

Thanks for the first pass, I will ping here when I get that License stuff sorted, I'd prefer that all parties accept it

**Comment by fejfighter** [comment]
@riscy @mattiasb The License PR just got merged, Should be in a state for a second pass

**Comment by riscy** [comment]
Thank you!  Here's the latest --

`eglot-tempel.el` with byte-compile using Emacs 28.1:
```
eglot-tempel.el:75:10: Warning: reference to free variable `eglot'
```
This is super minor, but I think this `eglot` should be quoted as `'eglot` in the definition of the minor mode.

`eglot-tempel.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- eglot-tempel.el#L53: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
```
Also minor, but bear in mind people will have different tab widths which can really garble mixed indentation styles.

**Comment by riscy** [comment]
I'll mark this awaiting-usptream for now, but feel free to reach out when ready.

(One more thing I noticed -- very minor -- is that in `eglot-tempel--convert`, the regular expression appears to be unnecessarily escaping the `$` character.  Emacs should syntax-highlight these to let you know, but then again those backslashes might be there for dev clarity.)

**Comment by fejfighter** [comment]
I have addressed the last concerns and added melpazoid to the repo to catch future issues:
https://github.com/fejfighter/eglot-tempel/actions/runs/5376868269/jobs/9754602546

setting `indent-tabs-mode` to nil seems to not have any affect for my emacs for some reason. it has been set for some time and yet I always have tabs creep in.

And thanks for the regexp update, I must  have been over cautious when writing it. but happy to see it simplified, even a little.

**Comment by riscy** [comment]
Thank you!  Merging.

(I'm curious about the `indent-tabs-mode` thing; I'll make a mental note to see if there's another variable that might control this.)

**Pull request merged**
