### PR TITLE
Adding rms-quote package recipe

### PR DESCRIPTION
**Pull request by m0n73**
### Brief summary of what the package does
This package selects and messages out a random crazy thing RMS
has said in the past. The user can add to the quotes list directly from
emacs.

### Direct link to the package repository

https://github.com/m0n73/rms-quote

### Your association with the package

I am the maintainer and so far sole contributor. 

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
Lets not do this.

This list (which I have only skimmed) contains some questionable statements.
However kicking someone who is already down is also uncalled for.

Quoting from https://medium.com/@thomas.bushnell/a-reflection-on-the-departure-of-rms-18e6a835fd84 (which you might want to read):

> I feel very sad for him. He’s a tragic figure. He is one of the most brilliant people I’ve met, who I have always thought desperately craved friendship and camaraderie, and seems to have less and less of it all the time. This is all his doing; nobody does it to him. But it’s still very sad. As far as I can tell, he believes his entire life’s work is a failure.

**Comment by heapsmash** [comment]
Oh man, this is amazing. 
@tarsius the funniest time to kick some one is when they are down.

**Comment by m0n73** [comment]
The intent was to make light of something absurd, namely RMS having to resign because of poor reporting and hysterical outrage. Certain things he says and does are ridiculous, but him having to resign is a huge issue.

**Comment by milkypostman** [comment]
I don’t want to delve too far into this.

Despite context, the words are inappropriate and perpetuating them further provides no benefit to the world.

**Comment by tarsius** [comment]
> I would like to avoid having this discussion on our issue tracker.

To that effect I have closed this conversation. I have chosen "too heated" because the other available options made no sense.

**Pull request closed without merging**
