### PR TITLE
Add a recipe for omni-theme

### PR DESCRIPTION
**Pull request by zoedsoupe**
### Brief summary of what the package does

This theme is a dark, heavyly inspired by [Dracula](https://github.com/dracula).

Screenshot for Omni

### Direct link to the package repository

https://github.com/getomni/omni

### Your association with the package

I'm the maintainer/author

### Relevant communications with the upstream package maintainer

*None Needed*

### Checklist

Please confirm with `x`:

- [ ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

About LICENSE: Although is licensed by MIT LICENSE, which I dont't agree with the name because is ambigous, I can't change it. Even that the theme is mine, is under an organization with a project structure that had chosen this license.

Also, this is really useless for this PR, but: I admit that I lol for the last checkbox ahah, awesome job!

### CODE REVIEW

**Comment by riscy** [comment]
If the license is confirmed to be legally GPL compatible then it's on that (linked) list, and the MIT license is there.  It will probably be less confusing for your users if you (re)license the code as MIT, or put the color theme in its own repository that is fully GPL compatible.  Anecdotally, if I were working at an enterprise considering using your software, I would avoid repositories with mixed licenses if I could.

Note `all-the-icons` is a heavy dependency for a theme to come with.  I think it's very likely someone would want to use your theme without that installed.  (Not _strictly_ a blocker, but for your consideration.)

All that said, here's a quick mostly-automated pass:

### omni-theme.el ###

byte-compile (using Emacs 27.1):
- omni-theme.el#L864: Don't set `no-byte-compile: t`.
  Byte-compiling is enabled in what follows
```
omni-theme.el:146:9:Warning: reference to free variable `flycheck-mode'
omni-theme.el:147:25:Warning: reference to free variable
    `flycheck-last-status-change'
omni-theme.el:148:35:Warning: reference to free variable
    `flycheck-current-errors'
omni-theme.el:199:1:Warning: Unused lexical variable
    `diff-current-refined-background'
omni-theme.el:199:1:Warning: Unused lexical variable `diff-current-background'
omni-theme.el:199:1:Warning: Unused lexical variable `diff-removed-background'
omni-theme.el:199:1:Warning: Unused lexical variable `diff-added-background'
omni-theme.el:199:1:Warning: Unused lexical variable `pink-light'
omni-theme.el:199:1:Warning: Unused lexical variable `yellow-light'
omni-theme.el:825:12:Warning: `focus-in-hook' is an obsolete variable (as of
    27.1); after-focus-change-function
In end of data:
omni-theme.el:868:1:Warning: the following functions are not known to be
    defined: flycheck-count-errors, flycheck-list-errors, magit-git-success,
    magit-git-string, magit-get-current-branch
```
I quickly looked at just that first warning, and it looks like this theme will fail to run if flycheck isn't installed.  Maybe you can use `bound-and-true-p`, but there might be some deeper issues to look into.

checkdoc (using version 0.6.2):
```
Warning (emacs): 
omni-theme.el:867: The footer should be: (provide 'omni-theme)\n;;; omni-theme.el ends here
```
This is actually a bit of a false positive since `provide-theme` will handle providing the feature, but you can silence this by adding that redundant line to the end.  Also (and package lint mentions this too) there's a mismatch between your filename and package name and summary line.  All three of these should be `omni-theme`, but your summary line mentions omni.el, the last line says `;;; omni.el ends here`.

package-lint (using version 20210227.314):
```
10 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
1:0: error: There is no (provide 'omni) form.
1:43: warning: You should depend on (emacs "24.1") if you need lexical-binding.
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
147:18: error: You should depend on (emacs "24.1") if you need `pcase'.
149:48: error: You should depend on (emacs "25.1") or the let-alist package if you need `let-alist'.
512:5: error: You should depend on (emacs "24.1") if you need `org-date'.
542:5: error: You should depend on (emacs "24.1") if you need `org-block'.
791:3: warning: Closing parens should not be wrapped onto new lines.
854:18: warning: Closing parens should not be wrapped onto new lines.
```
Some of the version warnings might be false positives (in my opinion it's fine to define a color for `org-date` in a color theme that's compatible with earlier versions of Emacs than 24.1) but others are definitely not.

Other [lints](https://github.com/riscy/melpazoid):
- omni-theme.el#L23: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- omni-theme.el#L824: Loading a package should rarely add hooks -- you should define a minor-mode mode for this behavior
- omni-theme.el#L825: Loading a package should rarely add hooks
- omni-theme.el#L826: Loading a package should rarely add advice
- omni-theme.el#L827: Loading a package should rarely add advice

**Comment by riscy** [comment]
Just marking this awaiting upstream for now, but feel free to ping.

**Comment by Mdsp9070** [comment]
I'm very busy at now, but I really want to publish this package! On this or next week I'll solve these issues! Thanks for answering!

**Comment by Mdsp9070** [comment]
Ok, so I made all changes, removed `all-the-icons` dependency and focused only on theme. Also changed `license` to be `GPL` compatible.

Package installs sucessfully with `package-install-file` and `package-lint` do not returns any errors.

**Comment by riscy** [comment]
Thank you for those updates!  Here's some more feedback regarding the linters (you can run package-lint to check these):

package-lint (using version 20210425.3):
```
20 issues found:
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
34:0: error: "omni--cached-for" doesn't start with package's prefix "omni-theme".
48:0: error: "omni" doesn't start with package's prefix "omni-theme".
51:0: error: "omni" doesn't start with package's prefix "omni-theme".
56:0: error: "omni-use-paddings-in-mode-line" doesn't start with package's prefix "omni-theme".
66:0: error: "omni-ro-face" doesn't start with package's prefix "omni-theme".
70:0: error: "omni-modified-face" doesn't start with package's prefix "omni-theme".
74:0: error: "omni-not-modified-face" doesn't start with package's prefix "omni-theme".
78:0: error: "omni-buffer-position-face" doesn't start with package's prefix "omni-theme".
82:0: error: "omni-vc-face" doesn't start with package's prefix "omni-theme".
86:0: error: "omni-ok-face" doesn't start with package's prefix "omni-theme".
90:0: error: "omni-warning-face" doesn't start with package's prefix "omni-theme".
94:0: error: "omni-error-face" doesn't start with package's prefix "omni-theme".
98:0: error: "omni-buffer-coding" doesn't start with package's prefix "omni-theme".
101:0: error: "omni--true-color-p" doesn't start with package's prefix "omni-theme".
705:0: error: "omni-face-when-active" doesn't start with package's prefix "omni-theme".
711:0: error: "omni-selected-window" doesn't start with package's prefix "omni-theme".
714:0: error: "omni--set-selected-window" doesn't start with package's prefix "omni-theme".
721:0: error: "omni--active-window-p" doesn't start with package's prefix "omni-theme".
726:0: error: "omni-mode" doesn't start with package's prefix "omni-theme".
```
I think these pop up because the package has recently been renamed to `omni-theme`.

And while I'm here, I'm looking again at the code and I think the definition of `omni-mode` has a few issues I think I see:
- I think you want a `:global t` minor mode rather than a local minor mode, which you've currently got
- the `BODY` underneath `define-minor-mode` should contain a conditional to check whether the mode is being toggled on or off, and proceed accordingly (right now your mode only turns itself on)
- If I trace through all of the advice the minor mode enables, it seems to be just to keep the value of `omni-selected-window` updated to influence the function `omni-face-when-active` -- but this function isn't used anywhere as far as I can tell

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but ask here if you've got any questions.

**Comment by tarsius** [comment]
I am closing this pull-request because it is over a year old now. That doesn't mean that we won't add this to Melpa, just that you have to ask us to reopen it once you are ready.

**Pull request closed without merging**
