### PR TITLE
Adds receipe for ytdious youtube/invidious client

### PR DESCRIPTION
**Pull request by spiderbit**
### Brief summary of what the package does
A fork of the ytel client, but different enough to justify a different project, it is rewritten to use tabulated-list and uses multiple buffers for different searches, while ytel uses only 1 buffer for all searches, so you can't refresh 5 searches in the back you overwrite your searches.
Besides that it has added some features like showing a thumbnail in a split window and other stuff.

### Direct link to the package repository

https://github.com/spiderbit/ytdious

### Your association with the package

Maintainer and developer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
A quick first pass gives me --

byte-compile (using Emacs 27.1):
```
ytdious.el:384:1:Warning: the following functions are not known to be defined:
    s-contains-p, s-join, s-starts-with-p
```
so you may need a package-requires on `s`; however, that dependency can often be avoided (which can be useful for small packages) by using builtins.   Also at ytdious.el#L251: It's safer to sharp-quote function names; use `#'`.

**Comment by spiderbit** [comment]
@riscy the 2 issues you pointed out should be solved with my 2 last commits.

**Comment by spiderbit** [comment]
Is this now sitting here 5 Months for no reason, or does it get into melpa, I think the "vetting" process here is kind of strange, because you only check if at time X the source fullfills all your criteria and high standards, but then whatever I push upstream get's automatically updated over Melpa. So over time the source can become to some shitty quality you never would accept according to that criteria but it stays in melpa forever.

But whatever rocks your boat, I think there is nothing blocking the merge here, now can we got it going because it's pretty important I think people install 95-99% of their packages of emacs over melpa, it's good for melpa to have that package included and of course good for me to have more users/ more potential bugfixes or some dl numbers to boost my ego :D

**Comment by riscy** [comment]
Hi, we're aware of the issues you describe.  There has been some talk of posting some high-level quality status of existing packages in MELPA.  My own code sometimes veers outside the guidelines, but I try to fix it when I notice, and I expect the vast majority of package authors have the same attitude.

> now can we got it going

That quick first pass is very easy for me to do, but I'll take another look now for any oversights it may have missed.

And please be patient. :)  You may not realize it, but the attitude of your comment is off-putting.  I mostly do this on weekends, and it's more fun for me if it stays civil.

I will only list the current blockers: You have boilerplate in your file that describes GPL version 2 or later, but also (elsewhere) a license line that says `License: GNU General Public License >= 3`.  You should also pick a reasonable width at which to wrap your `;;; Commentary`, which on some lines extends to 170 characters; tools like `finder-commentary` won't know where to break the lines and your package's eventual Description in the MELPA index will render improperly.

**Comment by spiderbit** [comment]
I am sorry I think I made my comment with a funny undertone to not make it to aggressive, it's just a bit frustrating because I assumed that is just a quick formal process, because it just is a fork of a project that is already in melpa, so I didn't expect it to be so complicated.

Also I got a bit panicked seeing so much pull requests that sit there since months, the process seems a bit cumbersome. Even the merge process seems pretty complicated by itself and I have here already a feature locally implemented I hold back from pushing and well to mature it a bit...

A quick "noticed" will look at it if I have time or something would have calmed my nerve, not meant as critique just as feedback / suggestion. And sorry but beeing a bit more agressive first (if you don't overdue it) can get sometimes clarify things faster... and I am german so we are a bit more direct that comes of as unfriendly... sorry...

Find it strange that there is problems with the license stuff because I did not change it, pretty sure and again it's a fork of a project in melpa... but will look into it.

**Comment by spiderbit** [comment]
Fixed the 2 issues you mentioned.

**Comment by riscy** [comment]
> it just is a fork of a project that is already in melpa

I think I was distracted responding to your first comment that I missed this important note.

We try to push back against forks if there's any possibility of simply writing an extension, or -- best of all -- cooperating with the original authors to get these essential features integrated.  Would you consider talking to the original authors about integrating your changes instead?

**Comment by spiderbit** [comment]
@riscy I did do that, but he was not willing to accept some patches and then my fork did go a much different route.

It's also not mergable anymore because I replaced his custom made ui code with tabulated-list code which has certain advantages but also some disadvantages.

He also is not very active and suggested to me to make a fork:
https://github.com/gRastello/ytel/issues/14

Because I am way more active on this I would have to become the new upstream, and he seems not to be willing to even accept even small changes that made sense:
https://github.com/gRastello/ytel/issues/12

and in reference to him comparing his project to elfeed I would argue that mine is more like gnus. He seems to be more a artsi person I am a functional person. I have more elisp experience than him (not my first project) even his json wrapper is meh because it wrapps around curl instead of some request lib or whatever got introduced with Emacs 27.

He seems to also see his project more as a base where people use to build their own stuff based on it with very minimal features, I try to make a ready feature complete client.

Here locally I can view channel videos as example sure he could probably merge that specific code back, but I have 27 commits over him sure there is a "comments" plugin that also includes a preview picture, but that is harder to setup and there is another fork that also was not included but also goes in a different direction:
https://github.com/pablobc-mx/ytel/tree/dev

I can't implement tabulated-view as extension, I also have code here with emms integration which to be fair is not included in the project yet it's more a alternatve to open a video directly in mpv I can add it with names to the emms playlist.

I would be the new upstream because I am way more active and I don't think he wants to remove his fork and give me the name, and I am no even sad about it, it's like saying there should be only 1 email client in emacs, the tabulated-list thing is just a to big change, and even if I would ignore that writing for all the changes I want a extension would add a huge overhead and big problems in distributing them...

But I repeat myself the fork/merge was discussed and I did what he suggested and I agree that this is the only sane option, maybe if one of our forks get's more traction one of our clients could be removed at some point, but I don't think this day is today, except you want to kick out his branch:

> Given that it behaves differently from the current release (as you pointed out), that I've been ignoring you quite a lot (stuff happened) and that my willingness to work on ytel is quite low at the moment I suggest you go for a fork. As for the name problem see if you can come up with something, then renaming variables and workspaces should not be a big deal as the codebase is not big and Emacs is, after all, a good text editor.

**Comment by riscy** [comment]
Alright, sounds good to me - thanks!

**Pull request merged**
