### PR TITLE
add recipe for ob-diagrams

### PR DESCRIPTION
**Pull request by ggreif**

### CODE REVIEW

**Comment by ggreif** [comment]
I am not the author, just a happy user who thinks this is useful.

**Comment by ggreif** [comment]
Feel free to squash on merge (GitHub now enabled this), but if you prefer I can do it myself too.

**Comment by purcell** [comment]
Nice, thanks! Yes, the squash-on-merge feature is a valuable addition for me. Would you mind removing the blank line from the recipe, and adding the customary `;;; ob-diagrams.el ends here` to the end of the `.el` file please?

**Comment by ggreif** [comment]
Sure. I opened https://github.com/bergey/org-babel-diagrams/pull/4 to this end.

**Comment by ggreif** [comment]
@purcell `ob-diagrams.el` should be conformant now!

**Comment by purcell** [comment]
Nice, thanks!

**Comment by ggreif** [comment]
@https://github.com/acowley this might be interesting to your `.org` toolchain too.

**Pull request merged**
