### PR TITLE
Add Cap'n Proto mode.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
### Brief summary of what the package does

Major mode for editing Capn' Proto Files.
Cap'n Proto is an insanely fast data interchange format and capability-based RPC system.

### Direct link to the package repository

https://github.com/capnproto/capnproto

### Your association with the package

An enthusiastic user?

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks very much for this submission.  The code loads fine, but would you be willing to open a PR to fix some of the checklist?  Here's the gist:

### capnp-mode.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
capnp-mode.el:75: The footer should be: (provide 'capnp-mode)\n;;; capnp-mode.el ends here
Warning (emacs): 
capnp-mode.el:25: Argument `arg' should appear (as ARG) in the doc string
```

package-lint (using version 20210528.2348):
```
3 issues found:
1:0: error: Package should have a Homepage or URL header.
1:0: warning: The package summary should start with an uppercase letter or a digit.
31:8: warning: Closing parens should not be wrapped onto new lines.
```
(Note I added the `provide` form to the buffer before running package-lint so that it could parse the code.)

**Comment by riscy** [comment]
Thanks very much for taking that on. :)  When your PR gets looked at/merged, feel free to ping here again.  In the meantime I'll mark this awaiting upstream.

**Comment by tmcgilchrist** [comment]
@riscy PR merged and ready to go.

**Comment by riscy** [comment]
Looks good!  Thanks for that.

**Pull request merged**
