### PR TITLE
Add media-progress, media-progress-dired and media-progress-dirvish

### PR DESCRIPTION
**Pull request by jumper047**
### Brief summary of what the package does
Packages displays progress of the video file in dired/dirvish buffer. Useful when you have directory with lots of videos and you forgot where you stopped last time.

### Direct link to the package repository
https://github.com/jumper047/media-progress

### Your association with the package
Author and maintainer

### Relevant communications with the upstream package maintainer
None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for these.  Quick first pass (note the big issue I see between these two packages is that they are *both* distributing copies of the same file, media-progress.el; you may need to rethink how you plan to distribute these).

`media-progress-dired.el` with checkdoc 0.6.2:
```
media-progress-dired.el:107: First line should be capitalized
media-progress-dired.el:111: First line should be capitalized
media-progress-dired.el:138: All variables and subroutines might as well have a documentation string
media-progress-dired.el:144: All variables and subroutines might as well have a documentation string
```

`media-progress-dired.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- media-progress-dired.el#L2: Have you done the paperwork to assign this copyright?
- media-progress-dired.el#L130: Could this point/line-end-position comparison use `eolp`?
- media-progress-dired.el#L83: `concat` may be unneeded; `insert` can take multiple arguments
```

`media-progress.el` with byte-compile using Emacs 28.1:
```
media-progress.el:120:20: Warning: the function `string-split' is not known to
    be defined.
```
I think this is coming from a version of Emacs later than 28.1.

`media-progress.el` with package-lint 20230315.1052:
```
19 issues found:
8:0: error: Package-Requires outside the main file have no effect.
36:0: error: "media-progress" doesn't start with package's prefix "media-progress-dired".
41:0: error: "media-progress-mpv-cfg-dir" doesn't start with package's prefix "media-progress-dired".
46:0: error: "media-progress-prefer-with-path" doesn't start with package's prefix "media-progress-dired".
58:0: error: "media-progress-extensions" doesn't start with package's prefix "media-progress-dired".
65:0: error: "media-progress-completed-threshold" doesn't start with package's prefix "media-progress-dired".
71:0: error: "media-progress-mpv-watch-later-dir-name" doesn't start with package's prefix "media-progress-dired".
74:0: error: "media-progress-format" doesn't start with package's prefix "media-progress-dired".
77:0: error: "media-progress-completed-message" doesn't start with package's prefix "media-progress-dired".
80:0: error: "media-progress-fallback-format" doesn't start with package's prefix "media-progress-dired".
84:0: error: "media-progress-watched-time-format" doesn't start with package's prefix "media-progress-dired".
87:0: error: "media-progress-mediainfo-command" doesn't start with package's prefix "media-progress-dired".
90:0: error: "media-progress-mediainfo-args" doesn't start with package's prefix "media-progress-dired".
93:0: error: "media-progress--media-p" doesn't start with package's prefix "media-progress-dired".
101:0: error: "media-progress--get-watch-later-file" doesn't start with package's prefix "media-progress-dired".
118:0: error: "media-progress--parse-wl-line" doesn't start with package's prefix "media-progress-dired".
125:0: error: "media-progress--extract-pos" doesn't start with package's prefix "media-progress-dired".
134:0: error: "media-progress--get-duration" doesn't start with package's prefix "media-progress-dired".
144:0: error: "media-progress-info-string" doesn't start with package's prefix "media-progress-dired".
```

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

------------

`media-progress.el` with byte-compile using Emacs 28.1:
```
media-progress.el:120:20: Warning: the function `string-split' is not known to
    be defined.
```

`media-progress.el` with package-lint 20230315.1052:
```
19 issues found:
8:0: error: Package-Requires outside the main file have no effect.
36:0: error: "media-progress" doesn't start with package's prefix "media-progress-dirvish".
41:0: error: "media-progress-mpv-cfg-dir" doesn't start with package's prefix "media-progress-dirvish".
46:0: error: "media-progress-prefer-with-path" doesn't start with package's prefix "media-progress-dirvish".
58:0: error: "media-progress-extensions" doesn't start with package's prefix "media-progress-dirvish".
65:0: error: "media-progress-completed-threshold" doesn't start with package's prefix "media-progress-dirvish".
71:0: error: "media-progress-mpv-watch-later-dir-name" doesn't start with package's prefix "media-progress-dirvish".
74:0: error: "media-progress-format" doesn't start with package's prefix "media-progress-dirvish".
77:0: error: "media-progress-completed-message" doesn't start with package's prefix "media-progress-dirvish".
80:0: error: "media-progress-fallback-format" doesn't start with package's prefix "media-progress-dirvish".
84:0: error: "media-progress-watched-time-format" doesn't start with package's prefix "media-progress-dirvish".
87:0: error: "media-progress-mediainfo-command" doesn't start with package's prefix "media-progress-dirvish".
90:0: error: "media-progress-mediainfo-args" doesn't start with package's prefix "media-progress-dirvish".
93:0: error: "media-progress--media-p" doesn't start with package's prefix "media-progress-dirvish".
101:0: error: "media-progress--get-watch-later-file" doesn't start with package's prefix "media-progress-dirvish".
118:0: error: "media-progress--parse-wl-line" doesn't start with package's prefix "media-progress-dirvish".
125:0: error: "media-progress--extract-pos" doesn't start with package's prefix "media-progress-dirvish".
134:0: error: "media-progress--get-duration" doesn't start with package's prefix "media-progress-dirvish".
144:0: error: "media-progress-info-string" doesn't start with package's prefix "media-progress-dirvish".
```

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

**Comment by jumper047** [comment]
@riscy sorry for delay - now, I hope, I addressed all issues you found

**Comment by riscy** [comment]
No problem, you're right on time (I'm usually here on weekends :)

Here's the latest across these 3 recipes --

`media-progress.el` with byte-compile using Emacs 28.1:
```
media-progress.el:156:36: Warning: `(media-p (media-progress--media-p
    media-file))' is a malformed function
media-progress.el:163:30: Warning: reference to free variable `wl-file'
In end of data:
media-progress.el:160:20: Warning: the function `wl-file' is not known to be
    defined.
media-progress.el:159:8: Warning: the function `when-let*' is not known to be
    defined.
media-progress.el:151:11: Warning: the function `string-join' is not known to
    be defined.
```
I think this file needs a `(require 'subr-x)` to resolve the above.

`media-progress-dired.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- media-progress-dired.el#L4: Have you done the paperwork to assign this copyright? (I always double-check why packages have this line, in case of copy-paste mistakes)
- media-progress-dired.el#L85: `concat` may be unneeded; `insert` can take multiple arguments
```

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

**Comment by jumper047** [comment]
Hope I not missed your weekend appearance:) 
Regarding copyrights - I borrowed dired-related code from https://github.com/amno1/dired-git-log/blob/main/dired-git-log.el, so I leaved existing copyrights as is and added mine on top. Is it correct?
Other issues should be resolved

**Comment by riscy** [comment]
Yes, looks good here.  I'm running a bit late but it's a long weekend where I live. :)

**Comment by jumper047** [comment]
Awesome!
And thank you for your work!

**Pull request merged**
