### PR TITLE
Add recipe for grammarbot

### PR DESCRIPTION
**Pull request by zevlg**
### Brief summary of what the package does

`grammarbot.el` is GNU Emacs interface to wonderful GrammarBot service.

### Direct link to the package repository

https://github.com/zevlg/grammarbot.el

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick pass over the checklist:

### grammarbot.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
```
grammarbot.el:293:41:Warning: `(rep-idx (grammarbot--issue-choose
match-point))' is a malformed function
grammarbot.el:300:44:Warning: reference to free variable `rep-idx'
In end of data:
grammarbot.el:394:1:Warning: the function `when-let' is not known to be
defined.
```


<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191220.419):
```
5 issues found:
177:5: error: You should depend on (emacs "25.1") or the seq package if you need `seq-doseq'.
232:9: error: You should depend on (emacs "25.1") or the seq package if you need `seq-doseq'.
299:3: error: You should depend on (emacs "25.1") if you need `when-let'.
305:21: error: You should depend on (emacs "25.1") if you need `json--plist-to-alist'.
366:15: error: You should depend on (emacs "25.1") or the seq package if you need `seq-doseq'.
```

Other static checks/suggestions:
- grammarbot.el#L321: It's safer to sharp-quote function names; use `#'`
- grammarbot.el#L332: It's safer to sharp-quote function names; use `#'`
- grammarbot.el#L228: It's safer to sharp-quote function names; use `#'`
- grammarbot.el#L24: Prefer `https` over `http` (if possible)
- grammarbot.el#L88: Prefer `https` over `http` (if possible)
- grammarbot.el#L156: Prefer `https` over `http` (if possible)

License:
- GitHub API found `GNU General Public License v3.0`
- gpl license text appears in individual files (good)

**Comment by zevlg** [comment]
Thanks, I've fixed all these issues

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

1. Please consider adding Cask file is good to easy resolve dependency, build, packaging etc.
2. The dependency of `cl-lib` is unneeded because your package depends on Emacs-25.

**Comment by riscy** [comment]
Finally digging deeper on this.  This looks close, but here's one more bit of feedback:

One thing I notice is that, when I don't have a grammarbot-api-key, I see: "GrammarBot v4.3.1 detected no issues".  I can see from [here](https://api.grammarbot.io/v2/check?text=testing&api-key=123) that there will probably not be a clue about missing the api key, but maybe you can check on your end if it's nil and warn the user?

**Comment by zevlg** [comment]
> Finally digging deeper on this. This looks close, but here's one more bit of feedback:
> 
> One thing I notice is that, when I don't have a grammarbot-api-key, I see: "GrammarBot v4.3.1 detected no issues". I can see from [here](https://api.grammarbot.io/v2/check?text=testing&api-key=123) that there will probably not be a clue about missing the api key, but maybe you can check on your end if it's nil and warn the user?

Not having api key is totally ok, as described in docstring to `grammarbot-api-key`.  After reaching 100 requests limit without API key, there will be error reported mentioning that limit is reached.  Grammarbot probably need to check for this error. I'll test this one

Try [this request](https://api.grammarbot.io/v2/check?text=testig) with typo error in "testing".  As you can see this typo error is reported

**Comment by riscy** [comment]
I see what was happening for me - I was testing a document that had a `/` in it.  I think this package needs a solution for that and other characters like & (`url-hexify-string`?) -- and maybe some awareness of the maximum length of a URL?  Otherwise you might look into POSTing the data using e.g. Emacs requests.

Also when I test by making the region this line of text:

"melpazoid is a bundle of scripts"

I get an error with the following traceback:
```
Debugger entered--Lisp error: (wrong-number-of-arguments #<subr max> 0)
  max()
  apply(max nil)
  (let ((max-rlen (apply (function max) (mapcar (function (lambda (rep) (length ...))) replacements))) (rep-idx 48)) (seq-do (function (lambda (rep) (if (= rep-idx (+ 57 1)) (progn (setq rep-idx 97))) (insert "(" (propertize (char-to-string rep-idx) (quote face) (quote bold)) ")") (insert " " (plist-get rep :value) " ") (insert (make-string (- max-rlen (length ...)) 32)) (if (>= (current-column) fill-column) (progn (insert "\n"))) (setq rep-idx (1+ rep-idx)))) replacements))
  (save-current-buffer (set-buffer (get-buffer-create grammarbot-choices-buffer)) (erase-buffer) (insert (plist-get match :message) "\n") (if (= 1 (length replacements)) (progn (insert (format "Rule: %S\n" (plist-get match :rule))))) (insert "\n") (let ((max-rlen (apply (function max) (mapcar (function (lambda ... ...)) replacements))) (rep-idx 48)) (seq-do (function (lambda (rep) (if (= rep-idx (+ 57 1)) (progn (setq rep-idx 97))) (insert "(" (propertize (char-to-string rep-idx) (quote face) (quote bold)) ")") (insert " " (plist-get rep :value) " ") (insert (make-string (- max-rlen ...) 32)) (if (>= (current-column) fill-column) (progn (insert "\n"))) (setq rep-idx (1+ rep-idx)))) replacements)) (goto-char (point-min)) (current-buffer))
  (let* ((match (cdr match-point)) (replacements (plist-get match :replacements))) (save-current-buffer (set-buffer (get-buffer-create grammarbot-choices-buffer)) (erase-buffer) (insert (plist-get match :message) "\n") (if (= 1 (length replacements)) (progn (insert (format "Rule: %S\n" (plist-get match :rule))))) (insert "\n") (let ((max-rlen (apply (function max) (mapcar (function ...) replacements))) (rep-idx 48)) (seq-do (function (lambda (rep) (if (= rep-idx ...) (progn ...)) (insert "(" (propertize ... ... ...) ")") (insert " " (plist-get rep :value) " ") (insert (make-string ... 32)) (if (>= ... fill-column) (progn ...)) (setq rep-idx (1+ rep-idx)))) replacements)) (goto-char (point-min)) (current-buffer)))
  grammarbot--choices-buffer((#<marker (moves after insertion) at 7603 in grammarbot.el> :message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo"))))
  (display-buffer (grammarbot--choices-buffer match-point) grammarbot-choices-display-buffer-action)
  (let* ((nreps (length (plist-get (cdr match-point) :replacements))) (read-prompt (concat (format "0%s to replace, " (cond ((< nreps 2) "") ((< nreps 11) (format "-%d" ...)) (t (concat "-" ...)))) "SPC to leave unchanged, " "C-g to cancel")) (got-valid-keys nil) (ret-rep-idx nil)) (display-buffer (grammarbot--choices-buffer match-point) grammarbot-choices-display-buffer-action) (while (not got-valid-keys) (let ((key (read-key read-prompt))) (cond ((if (and (>= key 48) (<= key 57) (< ... nreps)) (progn (setq ret-rep-idx ...) (setq got-valid-keys t)))) ((= key 7) (keyboard-quit)) ((= key 32) (setq got-valid-keys t))))) ret-rep-idx)
  (if match-point (let* ((nreps (length (plist-get (cdr match-point) :replacements))) (read-prompt (concat (format "0%s to replace, " (cond (... "") (... ...) (t ...))) "SPC to leave unchanged, " "C-g to cancel")) (got-valid-keys nil) (ret-rep-idx nil)) (display-buffer (grammarbot--choices-buffer match-point) grammarbot-choices-display-buffer-action) (while (not got-valid-keys) (let ((key (read-key read-prompt))) (cond ((if (and ... ... ...) (progn ... ...))) ((= key 7) (keyboard-quit)) ((= key 32) (setq got-valid-keys t))))) ret-rep-idx) (if (get-buffer grammarbot-choices-buffer) (progn (kill-buffer grammarbot-choices-buffer))))
  grammarbot--issue-choose((#<marker (moves after insertion) at 7603 in grammarbot.el> :message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo"))))
  (and t (grammarbot--issue-choose match-point))
  (let* ((rep-idx (and t (grammarbot--issue-choose match-point)))) (if rep-idx (progn (grammarbot--issue-replace match-point rep-idx) t) nil))
  grammarbot--issue-interactively((#<marker (moves after insertion) at 7603 in grammarbot.el> :message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo"))))
  (if (grammarbot--issue-interactively match-pnt) (grammarbot--stat-inc stats :replaced) (grammarbot--stat-inc stats :ignored))
  (cond ((or arg (grammarbot--issue-accept-p match-pnt)) (grammarbot--issue-replace match-pnt 0) (grammarbot--stat-inc stats :replaced)) ((grammarbot--issue-ignore-p match-pnt) (grammarbot--stat-inc stats :ignored)) (t (if (grammarbot--issue-interactively match-pnt) (grammarbot--stat-inc stats :replaced) (grammarbot--stat-inc stats :ignored))))
  (closure ((stats :ignored 0 :replaced 0) (match-points (#<marker (moves after insertion) at 7603 in grammarbot.el> :message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo")))) (result :software (:name "GrammarBot" :version "4.3.1" :apiVersion 1 :premium :json-false :premiumHint "You might be missing errors only the Premium version can find. Upgrade to see what you're missing." :status "") :warnings (:incompleteResults :json-false) :language (:name "English (US)" :code "en-US" :detectedLanguage (:name "English (US)" :code "en-US")) :matches [(:message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo")))]) (arg) (end . 7636) (start . 7603) t) (match-pnt) (cond ((or arg (grammarbot--issue-accept-p match-pnt)) (grammarbot--issue-replace match-pnt 0) (grammarbot--stat-inc stats :replaced)) ((grammarbot--issue-ignore-p match-pnt) (grammarbot--stat-inc stats :ignored)) (t (if (grammarbot--issue-interactively match-pnt) (grammarbot--stat-inc stats :replaced) (grammarbot--stat-inc stats :ignored)))))((#<marker (moves after insertion) at 7603 in grammarbot.el> :message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo"))))
  mapc((closure ((stats :ignored 0 :replaced 0) (match-points (#<marker (moves after insertion) at 7603 in grammarbot.el> :message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo")))) (result :software (:name "GrammarBot" :version "4.3.1" :apiVersion 1 :premium :json-false :premiumHint "You might be missing errors only the Premium version can find. Upgrade to see what you're missing." :status "") :warnings (:incompleteResults :json-false) :language (:name "English (US)" :code "en-US" :detectedLanguage (:name "English (US)" :code "en-US")) :matches [(:message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo")))]) (arg) (end . 7636) (start . 7603) t) (match-pnt) (cond ((or arg (grammarbot--issue-accept-p match-pnt)) (grammarbot--issue-replace match-pnt 0) (grammarbot--stat-inc stats :replaced)) ((grammarbot--issue-ignore-p match-pnt) (grammarbot--stat-inc stats :ignored)) (t (if (grammarbot--issue-interactively match-pnt) (grammarbot--stat-inc stats :replaced) (grammarbot--stat-inc stats :ignored))))) ((#<marker (moves after insertion) at 7603 in grammarbot.el> :message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo")))))
  seq-do((closure ((stats :ignored 0 :replaced 0) (match-points (#<marker (moves after insertion) at 7603 in grammarbot.el> :message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo")))) (result :software (:name "GrammarBot" :version "4.3.1" :apiVersion 1 :premium :json-false :premiumHint "You might be missing errors only the Premium version can find. Upgrade to see what you're missing." :status "") :warnings (:incompleteResults :json-false) :language (:name "English (US)" :code "en-US" :detectedLanguage (:name "English (US)" :code "en-US")) :matches [(:message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo")))]) (arg) (end . 7636) (start . 7603) t) (match-pnt) (cond ((or arg (grammarbot--issue-accept-p match-pnt)) (grammarbot--issue-replace match-pnt 0) (grammarbot--stat-inc stats :replaced)) ((grammarbot--issue-ignore-p match-pnt) (grammarbot--stat-inc stats :ignored)) (t (if (grammarbot--issue-interactively match-pnt) (grammarbot--stat-inc stats :replaced) (grammarbot--stat-inc stats :ignored))))) ((#<marker (moves after insertion) at 7603 in grammarbot.el> :message "Possible spelling mistake found" :shortMessage "Spelling mistake" :replacements [] :offset 0 :length 9 :context (:text "melpazoid is a bundle of scripts " :offset 0 :length 9) :sentence "melpazoid is a bundle of scripts" :type (:typeName "Other") :rule (:id "MORFOLOGIK_RULE_EN_US" :description "Possible spelling mistake" :issueType "misspelling" :category (:id "TYPOS" :name "Possible Typo")))))
  (save-excursion (seq-do (function (lambda (match-pnt) (cond ((or arg (grammarbot--issue-accept-p match-pnt)) (grammarbot--issue-replace match-pnt 0) (grammarbot--stat-inc stats :replaced)) ((grammarbot--issue-ignore-p match-pnt) (grammarbot--stat-inc stats :ignored)) (t (if (grammarbot--issue-interactively match-pnt) (grammarbot--stat-inc stats :replaced) (grammarbot--stat-inc stats :ignored)))))) match-points))
  (unwind-protect (save-excursion (seq-do (function (lambda (match-pnt) (cond ((or arg ...) (grammarbot--issue-replace match-pnt 0) (grammarbot--stat-inc stats :replaced)) ((grammarbot--issue-ignore-p match-pnt) (grammarbot--stat-inc stats :ignored)) (t (if ... ... ...))))) match-points)) (grammarbot--issue-highlight nil) (grammarbot--issue-choose nil) (if grammarbot-show-stats (progn (message "GrammarBot issues: %d, ignored: %d, replaced: %d" (length match-points) (plist-get stats :ignored) (plist-get stats :replaced)))))
  (if match-points (unwind-protect (save-excursion (seq-do (function (lambda (match-pnt) (cond (... ... ...) (... ...) (t ...)))) match-points)) (grammarbot--issue-highlight nil) (grammarbot--issue-choose nil) (if grammarbot-show-stats (progn (message "GrammarBot issues: %d, ignored: %d, replaced: %d" (length match-points) (plist-get stats :ignored) (plist-get stats :replaced))))) (if grammarbot-show-stats (progn (message "GrammarBot v%s detected no issues" (plist-get (plist-get result :software) :version)))))
  (let* ((result (grammarbot--api-check (buffer-substring-no-properties start end) grammarbot-api-key grammarbot-language)) (match-points (mapcar (function (lambda (match) (cons (copy-marker ... t) match))) (plist-get result :matches))) (stats (list :ignored 0 :replaced 0))) (if match-points (unwind-protect (save-excursion (seq-do (function (lambda (match-pnt) (cond ... ... ...))) match-points)) (grammarbot--issue-highlight nil) (grammarbot--issue-choose nil) (if grammarbot-show-stats (progn (message "GrammarBot issues: %d, ignored: %d, replaced: %d" (length match-points) (plist-get stats :ignored) (plist-get stats :replaced))))) (if grammarbot-show-stats (progn (message "GrammarBot v%s detected no issues" (plist-get (plist-get result :software) :version))))))
  grammarbot(7603 7636 nil)
  funcall-interactively(grammarbot 7603 7636 nil)
```

**Comment by zevlg** [comment]
> Otherwise you might look into POSTing the data using e.g. Emacs requests.

Yeah, thanks, using `request` package with POST instead of GET is the best approach, will do so

**Comment by riscy** [comment]
Thanks!  Ping when ready. :)

**Comment by tarsius** [comment]
Friendly ping!

**Comment by zevlg** [comment]
> Friendly ping!

Yes yes, I remember this, just so busy these days :(

**Comment by tarsius** [comment]
Okay okay, just checking. :wink:

**Comment by zevlg** [comment]
I've decided not to put it into MELPA, sorry for disturbance

**Pull request closed without merging**
