### PR TITLE
Add python-mls

### PR DESCRIPTION
**Pull request by jdtsmith**
**Brief summary of what the package does**

Multi-line commands for (i)Python in the inferior python shell.  Create/yank/kill/recall/save history.  

**Direct link to the package repository**

https://github.com/jdtsmith/python-mls

**Your association with the package**

I am the author and maintainer.

**Relevant communications with the upstream package maintainer**

None needed

**Checklist**

- [X]   The package is released under a GPL-Compatible Free Software License
- [X]   I've read CONTRIBUTING.org
- [X]   I've used the latest version of package-lint to check for packaging issues, and addressed its feedback
- [X]   My elisp byte-compiles cleanly
- [X]   M-x checkdoc is happy with my docstrings
- [X]   I've built and installed the package using the instructions in CONTRIBUTING.org
- [ ]   I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, looks interesting and the checklist looks good.

One issue I see is that as soon as this is loaded, it is adding globally active hooks on `inferior-python-mode-hook` and `python-mode-hook` and possibly even advising `comint-output-filter`.   But simply loading a package should cause few side effects.  Most of these should happen as a result of the user explicitly calling a function or toggling a mode off or on.  In particular adding hooks and advice should probably be done as part of a [minor mode](https://www.gnu.org/software/emacs/manual/html_node/elisp/Minor-Modes.html) and the effects localized as much as possible.

And some minor stuff:
- python-mls.el#L9: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- python-mls.el#L377: Single-line comments should usually begin with `;;`

**Comment by jdtsmith** [comment]
Thanks for the feedback.  I've altered it so that `python-mls-setup` serves as the front-end which adds/removes the hooks to both inferior-python-mode and python-mode hooks.  This keeps the minor-mode focused on hooking into/overriding the default python-mode behavior it needs to.  If you `M-x python-mls-mode` in a buffer to turn it off, it removes the hook, disabling for future sessions and mentioning this.

Also fixed the minor stuff.

**Comment by riscy** [comment]
Thanks for accommodating!  One minor thing I notice with the latest is that whenever this package is loaded, it creates what appears to be debug output as it defines the keybindings (even if it's loaded from a compiled state):
```
Narrowing Command: python-nav-backward-block
Narrowing Command: python-nav-forward-block
Narrowing Command: python-nav-backward-up-list
```

I think once that's fixed this is an easy merge.  And while I'm here, a couple minor suggestions on sharp-quoting:

- python-mls.el#L461: It's safer to sharp-quote function names; use `#'`
- python-mls.el#L465: It's safer to sharp-quote function names; use `#'`
- python-mls.el#L466: It's safer to sharp-quote function names; use `#'`
- python-mls.el#L460: It's safer to sharp-quote function names; use `#'`

**Comment by jdtsmith** [comment]
Just pushed these changes, thanks for mentioning. I've also made some improvements to the README PR was submitted.

**Comment by riscy** [comment]
Great thanks!  Merging.

**Pull request merged**
