### PR TITLE
Add elisp-autofmt

### PR DESCRIPTION
**Pull request by ideasman42**
### Brief summary of what the package does

Emacs lisp auto-formatter which can be enabled as a minor mode, reformatting the buffer on save.

- The whole file is formatted (it's parsed and rewritten).
- Excessive overhead is avoided by using `replace-buffer-contents`, so minor re-formatting isn't a heavy operation.
- Definitions are extracted from emacs + packages to guide formatting decisions.
- Definitions can optionally be extracted from relative paths too (for multi-file packages).
- In practice I've found this fast enough that even on large elisp files it's typically between 200ms..400ms.
- Tested with all emacs-lisp files and every melpa package to format the files without changing the resulting byte-code output.
- Already used for most of the packages I maintain on melpa.

### Direct link to the package repository

https://codeberg.org/ideasman42/emacs-elisp-autofmt

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
I am hesitant to merge this, not because the package doesn't meet the checklist standards, but because this is an idiosyncratic indentation style that has (in my opinion) rightly [criticized as nonstandard](https://github.com/melpa/melpa/pull/7999#issuecomment-1110760994); it also doesn't match the [style guide](https://github.com/bbatsov/emacs-lisp-style-guide) or any style that is used in core elisp, and contradicts the builtin `lisp-indent-line`.  For these reasons, I would discourage people from using this style widely (I think I have even commented on it in the past for your own repos, but have not blocked on it).

For those reasons, my position is that MELPA should not merge this.  (For what it's worth, I also maintain my own auto-formatter that I haven't indexed on MELPA either.)

**Comment by ideasman42** [comment]
This seems reasonable, in that case - I'd like to support something as close as possible to emacs preferred style.

Added initial support to a temporary feature-branch:
This is the result:

- https://gist.github.com/ideasman42/c78b36cea5352298c95c12360c2b16f2
- https://gist.github.com/ideasman42/0dcf1663e71115a6c8e0bce7d5b71a82
- https://gist.github.com/ideasman42/45cda2983709cd182bbbf134237408c2

How about enable "emacs" formatting by default, and iron out any outstanding issues in the auto formatting, then consider the package for inclusion?

**Comment by riscy** [comment]
I think that's a great change, and thank you very much for considering that. Linting this recipe raises a couple issues:

- No .el file matches the name 'elisp-autofmt'
- Prefer the default recipe or `:defaults`, if possible.
- Can't check package-requires if there is no 'main' file

Once that file is included, I also see:
- elisp-autofmt.el#L259: It's safer to sharp-quote function names; use `#'`
- elisp-autofmt.el#L638: It's safer to sharp-quote function names; use `#'`
- elisp-autofmt.el#L560: Could this point/point-max comparison use `eobp`?
- elisp-autofmt.el#L559: Could this point/point-min comparison use `bobp`?
- elisp-autofmt.el#L761: This double negation can be collapsed (`not` aliases `null`)

The dependency on Python seems a little bit heavy, but I admit it's common for Python to be installed on user systems.  But the use of `match` in the Python code requires Python 3.10+, and if you were able to remove that you might be able to support (much) earlier versions of Python as well.  Not a blocker though.

**Comment by ideasman42** [comment]
- Removed use of `match` (for Python 3.8 compat).
- Resolved melpazoid warnings.
- Rewrote formatting to be calculated in Python entirely (not relying on emacs indentation).
- elisp-autofmt now uses `native` style by default & for it's self.

----

re:

> * No .el file matches the name 'elisp-autofmt'
> 
> * Prefer the default recipe or `:defaults`, if possible.
> 
> * Can't check package-requires if there is no 'main' file

Not sure what to make of these, there is an `elisp-autofmt.el` file, not sure what you mean by using `:defaults`. Not sure why there would be a main file.

**Comment by riscy** [comment]
The recipe was not including the elisp file, but I've updated it - confirm that's what you want and this should be good to go.

**Comment by ideasman42** [comment]
Thanks, I'm not familier with this area, that should be fine.

**Comment by riscy** [comment]
Thanks - ready to merge.

My last thought is whether the `;;; Commentary` could be expanded to include at least a mention of the minor mode -- and even better would be a description of the methodology used to to autoformat buffers.  I'm especially curious because, as I mentioned I have my own personal elisp formatter with its own [conventions](https://github.com/riscy/elfmt#features).

**Comment by ideasman42** [comment]
Thanks! I was curious to check on the formatting utility you  were working on, I've seen a similar utility on the wiki which  re-formats S-expressions, however from being used to clang-format / black ... I'm quite fond of whole file re-formatting, where no matter what the input, as long as it's syntactically correct - you'll get the same output.

I tried to avoid too many hard coded checks on emacs-isums, although it's difficult to avoid at times.
Nevertheless,  using function type, min/max args, and doc-string + indent properties, it's possible to do practically everything emacs own indentation is doing.

**Pull request merged**
