### PR TITLE
Add recipe for elisa

### PR DESCRIPTION
**Pull request by s-kostyaev**
### Brief summary of what the package does

ELISA (Emacs Lisp Information System Assistant) is a project
designed to help Emacs users quickly find answers to their
questions related to Emacs and Emacs Lisp. Utilizing the powerful
Ellama package, ELISA provides accurate and relevant responses to
user queries, enhancing productivity and efficiency in the Emacs
environment. By integrating links to the Emacs info manual after
answering a question, ELISA ensures that users have easy access to
additional information on the topic, making it an essential tool
for both beginners and advanced Emacs users.

ELISA creates index from info manuals. When you send message to
`elisa-chat` it search to semantically similar info nodes in index,
get first `elisa-limit` nodes, add it to context and send your message
to llm. LLM generates answer to your message based on provided
context. You can read not only answer generated by llm, but also info
manuals by provided links.

### Direct link to the package repository

https://github.com/s-kostyaev/elisa

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`elisa.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- elisa.el#L3: Have you done the paperwork to assign this copyright?
```
I always confirm this one because it's a frequent copy-paste error.  (Also, if you *have* done the paperwork, you can also consider ELPA as a package index, but of course MELPA is happy to host high-quality packages.)

One thing I'd like to point out is that if I merely try to load this package, it's making a network call (I have network turned off when I'm running this load test) --
```
Loading elisa.el
  elisa.el:Error: Emacs 29.1:
  (error "github.com/443 Temporary failure in name resolution")
```
This isn't something a package should do at load time, because if the user doesn't have internet access, they might not be able to start Emacs normally.

**Comment by s-kostyaev** [comment]
> - elisa.el#L3: Have you done the paperwork to assign this copyright?

Yes.

> This isn't something a package should do at load time, because if the user doesn't have internet access, they might not be able to start Emacs normally.

This will be called once. After download dependencies it will not do it second time. But maybe I should do something else. I just want better user experience out of the box.

**Comment by SqrtMinusOne** [comment]
> After download dependencies it will not do it second time

I'd make a command for that, e.g. `M-x elisa-install`. [all-the-icons](https://github.com/domtronn/all-the-icons.el?tab=readme-ov-file#installation), [telega,el](https://github.com/zevlg/telega.el) do it this way, for instance.

And maybe throw something like
```lisp
(user-warning "Please run `elisa-install' to use this")
```
in functions that depend on that download.

**Comment by riscy** [comment]
For what it's worth, "better user experience out of the box" is a laudable goal, but I think going with @SqrtMinusOne 's suggestion is the best approach.  Thank you both. :)

**Comment by s-kostyaev** [comment]
@SqrtMinusOne @riscy 

Done. Thank you for review and for advice how to fix it.

**Comment by riscy** [comment]
My quick tests are showing this works exactly as intended - thanks again both.

**Pull request merged**
