### PR TITLE
Add recipe for mermaid-docker-mode

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
### Brief summary of what the package does

This library attempts to create Mermaid graphs via mermaid-ink aka mermaid as an API via a custom locally-built Docker image with restricted network access, so that you are sure nothing gets out and your system is kept isolated from random Node.js deps/files noise all around the filesystem.

### Direct link to the package repository

https://github.com/KeyWeeUsr/mermaid-docker-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

`mermaid-docker-mode.el` with byte-compile using Emacs 29.1:

```
In mermaid-docker-build-docker-image:
mermaid-docker-mode.el:181:10: Warning: Unused lexical variable `failed'

In mermaid-docker-initial-container-run:
mermaid-docker-mode.el:200:10: Warning: Unused lexical variable `failed'

In mermaid-docker-http-request:
mermaid-docker-mode.el:245:46: Warning: reference to free variable `dest'
mermaid-docker-mode.el:245:51: Warning: reference to free variable `body'

In mermaid-docker-test-graph-rendering:
mermaid-docker-mode.el:251:10: Warning: Unused lexical variable `name'

In mermaid-docker-create-image-for-offline-mode:
mermaid-docker-mode.el:280:10: Warning: Unused lexical variable `name'

In mermaid-docker-start-offline-mode:
mermaid-docker-mode.el:307:10: Warning: Unused lexical variable `name'

In mermaid-docker-test-graph-rendering-via-external-editor:
mermaid-docker-mode.el:396:10: Warning: Unused lexical variable `out-buff'

In mermaid-docker-render-external:
mermaid-docker-mode.el:432:10: Warning: Unused lexical variable `out-buff'

In mermaid-docker-render-internal:
mermaid-docker-mode.el:458:7: Warning: `mermaid-docker-get-url' called with 2 arguments, but accepts only 1

In mermaid-docker-compile-file:
mermaid-docker-mode.el:470:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
```

`mermaid-docker-mode.el` with checkdoc (0.6.2)

```
mermaid-docker-mode.el:499: The footer should be: (provide 'mermaid-docker-mode)\n;;; mermaid-docker-mode.el ends here
mermaid-docker-mode.el:492: First sentence should end with punctuation
```

`mermaid-docker-mode.el` with package-lint (20230905.629)

```
No issues found.
```

**Comment by riscy** [comment]
Thanks for this.  I noticed you've got other PR(s) #8749 already open.  To split my review time evenly between authors, I try to do one PR at a time per author, but I promise I'll get to this when we resolve earlier PRs.

**Comment by KeyWeeUsr** [comment]
@jcs090218 Thanks, fixed!

**Comment by riscy** [comment]
Thanks @KeyWeeUsr.  Checking this one out now, here's the latest --

`mermaid-docker-mode.el` with byte-compile using Emacs 29.1:
```
mermaid-docker-mode.el:444:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
```
This was reported above -- These byte-compile warnings were added in Emacs 29, but you can fix them by using back/front quotes, e.g. (``` `thing in quotes' ```).

`mermaid-docker-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- mermaid-docker-mode.el#L373: Use `(temporary-file-directory)` instead of /tmp in code
- mermaid-docker-mode.el#L407: Use `(temporary-file-directory)` instead of /tmp in code
- mermaid-docker-mode.el#L341: You should be careful to run shell-quote-argument on these arguments  - if any of the variables accidentally contain shell control characters, there could be big consequences
- mermaid-docker-mode.el#L103: You can use `not` or `null` instead of `(eq input nil)`
- mermaid-docker-mode.el#L107: You can use `not` or `null`
- mermaid-docker-mode.el#L231: You can use `not` or `null`
- mermaid-docker-mode.el#L397: You can use `not` or `null`
- mermaid-docker-mode.el#L239: No `format` required; `error` takes an f-string
- mermaid-docker-mode.el#L236: No `format` required; `message` takes an f-string
```

**Comment by KeyWeeUsr** [comment]
@riscy Thanks, hopefully fixed now! :+1:

**Comment by riscy** [comment]
Thank you -- I'm just realizing this now, but as in #8823, avoid specifying `:commit` in your branch except in unusual cases.  I will refocus on that PR so that we can get that fixed in the MELPA index.

**Comment by riscy** [comment]
> You should be careful to run shell-quote-argument on these arguments

This is for this function:

```python

(defun mermaid-docker-get-ip ()
  "Get current IP of a running mermaid-docker container."
  (let ((cmd
         (format "docker inspect %s | jq -r %s"
                 mermaid-docker-image-name
                 (format ".[].NetworkSettings.Networks.%s.IPAddress"
                         mermaid-docker-net))))
    (replace-regexp-in-string "\n" "" (shell-command-to-string cmd))))
```
and the (admittedly minor) issue is that `mermaid-docker-image-name` is customizable and not strictly validated, so a user could inadvertently put shell control characters in here without understanding the consequences.  Better to write `(shell-quote-argument mermaid-docker-image-name)` in the above function.

I also notice that this package seems to have debugging (`message` calls) leftover in some cases, e.g. `mermaid-docker--create-temp-work-folder` is running `(message "Create temp work folder")`; users will look at their `*Messages*` and not know where this came from -- and messaging some of these events aren't really going to help them anyway.  (Who's creating a temp work folder?  How can I find out?  Did I need to know about this?)

One last note re: conditionals is that you can probably reduce your use of `progn` in some cases.  For example in `mermaid-docker-install`, the body of a `when` doesn't need a `progn`, but you're using `(when (not` so I might even suggest `(unless ...` (again, with no progn).

**Comment by KeyWeeUsr** [comment]
@riscy Thanks, `(shell-quote-argument ...)` added. Re the debugging calls, they are meant for the user as progress instead of just debugging. Building a Docker image, especially with a bad internet connection, is horribly slow. :disappointed: I added a prefix though, so a user can know where it's coming from and even suppress it for the future. Still, I'd like to have it enabled by default because the first run is the slowest and the most critical. `(progn ...)` removed too, unless `(if ...)`-ed.

**Comment by riscy** [comment]
> I added a prefix though

I figure that solves it - thank you.  Possibly for future reference, if you want to do asynchronous compilation and keep a log, you might want to check out the `#'compile` function (with COMINT enabled).

**Pull request merged**
