### PR TITLE
recipes/helm-fish-completion: Add helm-fish-completion

### PR DESCRIPTION
**Pull request by Ambrevar**
### Brief summary of what the package does

Helm interface for fish-completion.

### Direct link to the package repository

https://github.com/emacs-helm/helm-fish-completion

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

 **None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Should your `package-requires` include `fish-completion`?  It also looks like you need `(require 'esh-mode)`

**Comment by Ambrevar** [comment]
Fixed, thanks!

**Comment by riscy** [comment]
Great, and thanks for your patience.  There's a small package-lint nag:

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
1 issue found:

1:0: warning: The package summary should start with an uppercase letter or a digit.
```
and my usual https nag :) 
- helm-fish-completion.el#L27: Prefer `https` over `http` (if possible)

Beyond that, I see an autoload cookie on `helm-fish-completion-make-eshell-source`, but maybe it's not necessary?  See [when to autoload](https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html).

Beyond that, the code is looking good -- ping me for another check.

**Comment by Ambrevar** [comment]
Thanks for the review, I've fixed the 2 issues.

Regarding the autoload: The idea is that the user only needs to add

(setq helm-esh-pcomplete-build-source-fn #'helm-fish-completion-make-eshell-source)

to their Emacs configuration to enable Helm Fish completion.
Alternatively, I could remove the autoload and let the user call
`(require 'helm-fish-completion)` themselves.  Thoughts?

**Comment by riscy** [comment]
Looks good!  Thanks for this.

**Pull request merged**
