### PR TITLE
Add arxiv-mode

### PR DESCRIPTION
**Pull request by Simon-Lin**
### Brief summary of what the package does

arxiv-mode is an Emacs major mode for viewing updates on arXiv.org.

### Direct link to the package repository

https://github.com/fizban007/arxiv-mode

### Your association with the package

coauthor/maintainer

### Relevant communications with the upstream package maintainer

This little project has been around for some time now. 
However we recently decided to polish and publish it on MELPA so more people can benefit from it :)
This is also my first time publishing package on MELPA. Please let me know if there's anything I missed!

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
`arxiv-mode.el` with byte-compile using Emacs 27.1:
```
arxiv-mode.el:192:15:Warning: assignment to free variable `url'
arxiv-mode.el:192:4:Warning: reference to free variable `url'
arxiv-mode.el:307:1:Warning: Lexical argument shadows the dynamic variable
    arxiv-buffer
In arxiv-populate-page:
arxiv-mode.el:315:23:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
arxiv-mode.el:332:1:Warning: Lexical argument shadows the dynamic variable
    arxiv-buffer
arxiv-mode.el:372:1:Warning: Unused lexical argument `x'
arxiv-mode.el:372:1:Warning: Unused lexical argument `x'
arxiv-mode.el:439:1:Warning: Unused lexical variable `bibfile'
In arxiv-export-bibtex:
arxiv-mode.el:510:15:Warning: assignment to free variable `bibtex-info'
arxiv-mode.el:507:18:Warning: assignment to free variable `bibfile'
arxiv-mode.el:507:8:Warning: reference to free variable `bibfile'
arxiv-mode.el:512:19:Warning: reference to free variable `bibtex-info'
In end of data:
arxiv-mode.el:810:1:Warning: the following functions are not known to be
    defined: bibtex-set-dialect, bibtex-generate-autokey
```

`arxiv-mode.el` with checkdoc 0.6.2:
```
arxiv-mode.el:181: Argument `ev' should appear (as EV) in the doc string
arxiv-mode.el:308: Lisp symbol `arxiv-entry-list' should appear in quotes
arxiv-mode.el:334: Lisp symbol `arxiv-current-entry' should appear in quotes
arxiv-mode.el:499: Lisp symbol `arxiv-default-bibliography' should appear in quotes
arxiv-mode.el:678: Lisp symbol `arxiv-query-data-list' should appear in quotes
```

`arxiv-mode.el` with package-lint 20211122.1152:
```
35 issues found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
1:69: warning: You should depend on (emacs "24.1") if you need lexical-binding.
9:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
10:23: warning: Use a properly versioned dependency on "hydra" if possible.
109:2: warning: Closing parens should not be wrapped onto new lines.
208:9: error: You should depend on (emacs "25.1") if you need `directory-name-p'.
227:7: error: You should depend on (emacs "24.3") if you need `setq-local'.
228:7: error: You should depend on (emacs "24.4") if you need `prettify-symbols-mode'.
258:5: error: You should depend on (emacs "24.3") if you need `quit-restore-window'.
269:18: error: You should depend on (emacs "24.1") if you need `window-total-width'.
283:32: error: You should depend on (emacs "25.1") or the seq package if you need `seq-subseq'.
287:45: error: You should depend on (emacs "25.1") if you need `alist-get'.
288:33: error: You should depend on (emacs "25.1") if you need `alist-get'.
298:15: error: You should depend on (emacs "25.1") if you need `alist-get'.
301:15: error: You should depend on (emacs "25.1") if you need `alist-get'.
347:20: error: You should depend on (emacs "25.1") if you need `alist-get'.
348:6: error: You should depend on (emacs "25.1") if you need `alist-get'.
349:6: error: You should depend on (emacs "25.1") if you need `alist-get'.
354:20: error: You should depend on (emacs "25.1") if you need `alist-get'.
355:6: error: You should depend on (emacs "25.1") if you need `alist-get'.
356:6: error: You should depend on (emacs "25.1") if you need `alist-get'.
361:27: error: You should depend on (emacs "25.1") if you need `alist-get'.
362:6: error: You should depend on (emacs "25.1") if you need `alist-get'.
458:8: error: `authors' was removed in Emacs version 25.1.
465:19: error: You should depend on (emacs "24.4") if you need `string-join'.
476:7: error: You should depend on (emacs "24.1") if you need `bibtex-set-dialect'.
526:5: error: You should depend on (emacs "24.1") if you need `pop-to-buffer-same-window'.
531:5: error: You should depend on (emacs "24.1") if you need `bibtex-set-dialect'.
532:6: warning: Closing parens should not be wrapped onto new lines.
566:19: error: You should depend on (emacs "27.1") if you need `decoded-time-hour'.
566:56: error: You should depend on (emacs "27.1") if you need `decoded-time-minute'.
566:90: error: You should depend on (emacs "27.1") if you need `decoded-time-second'.
761:2: warning: Closing parens should not be wrapped onto new lines.
784:2: warning: Closing parens should not be wrapped onto new lines.
805:2: warning: Closing parens should not be wrapped onto new lines.
```

`arxiv-query.el` with byte-compile using Emacs 27.1:
```
arxiv-query.el:49:1:Warning: Unused lexical variable `parsed-query'
arxiv-query.el:107:1:Warning: Unused lexical variable `exception'
In arxiv-parse-api:
arxiv-query.el:139:31:Warning: `mapcar' called for effect; use `mapc' or
    `dolist' instead
```

`arxiv-query.el` with checkdoc 0.6.2:
```
arxiv-query.el:104: First line should be capitalized
```

`arxiv-query.el` with package-lint 20211122.1152:
```
5 issues found:
1:50: warning: You should depend on (emacs "24.1") if you need lexical-binding.
116:69: error: `authors' was removed in Emacs version 25.1.
146:10: error: `authors' was removed in Emacs version 25.1.
158:3: warning: Closing parens should not be wrapped onto new lines.
170:5: error: You should depend on (emacs "24.3") if you need `user-error'.
```

`arxiv-vars.el` with checkdoc 0.6.2:
```
arxiv-vars.el:264: First line should be capitalized
```
A false positive, but so easy to fix too.

`arxiv-vars.el` with package-lint 20211122.1152:
```
1 issue found:
1:72: warning: You should depend on (emacs "24.1") if you need lexical-binding.
```

**Comment by Simon-Lin** [comment]
Thanks for the response! I've fixed the issues mentioned above.

**Comment by riscy** [comment]
Thanks very much for fixing those.  We can let this last one through, but it's an easy one to fix:

`arxiv-mode.el` with package-lint 20211122.1152:
```
1 issue found:
10:38: warning: Use a properly versioned dependency on "hydra" if possible.
```
It seems the latest stable version is available as [0.15.0](https://stable.melpa.org/#/hydra).

**Comment by riscy** [comment]
Also, welcome to MELPA! :)

**Pull request merged**
