### PR TITLE
Added sniem recipe

### PR DESCRIPTION
**Pull request by SpringHan**
### Brief summary of what the package does

Sniem means Simple United Editing Method. It's a new editing method for emacs. All the motions and most of the operations are related to `last-point`, and there are some great functions like `sniem-object-catch`, `sniem-middle-keyboard-or-fn`, `sniem-mark-jump`, etc.

### Direct link to the package repository

https://github.com/SpringHan/sniem

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by SpringHan** [comment]
A new PR from [7424](https://github.com/melpa/melpa/pull/7424)

**Comment by SpringHan** [comment]
And this is the only warning.
> ## sniem.el
> ```
> sniem.el:390:17:Warning: reference to free variable
>     `awesome-tray-module-alist'
> sniem.el:390:17:Warning: assignment to free variable
>     `awesome-tray-module-alist'.
> ```
> 
> In my project, I provide the support for the package named `awesome-tray`, so if I want to save the support, I can't delete these codes. And I've also added the check with `featurep`.

**Comment by SpringHan** [comment]
@riscy

**Comment by riscy** [comment]
Thanks very much, taking another look at the checklist items.

While I'm here I also need to stress that your package shouldn't advise or add hooks automatically as soon as it's loaded.  For instance, sniem-object-catch.el adds a hook to deactivate-mark-hook, sniem-operation.el also adds a hook to deactivate-mark-hook and adds advice to `keyboard-quit`, sniem.el adds advice to wdired-mode, etc.  This sort of stuff should only be enabled/disabled along with the mode whenever possible.

### sniem-operation.el ###

checkdoc (using version 0.6.2):
```
Warning (emacs): 
sniem-operation.el:442: Argument `add' should appear (as ADD) in the doc string
Warning (emacs): 
sniem-operation.el:504: Argument `string1' should appear (as STRING1) in the doc string
Warning (emacs): 
sniem-operation.el:182: `y-or-n-p' argument should end with "? "
Warning (emacs): 
sniem-operation.el:707: White space found at end of line
```

### sniem.el ###

byte-compile (using Emacs 27.1):
```
sniem.el:451:17:Warning: reference to free variable
    `awesome-tray-module-alist'
sniem.el:451:17:Warning: assignment to free variable
    `awesome-tray-module-alist'
```
You mentioned these above - in this case you can just `(defvar awesome-tray-module-alist)` at the top of the file in question.  But I will mention here that a function that's meant to just print state information should ideally not be meddling with `awesome-tray-module-alist` as a side effect.

**Comment by riscy** [comment]
Just noticed this as well, the pcase pattern `59` appears twice for qwerty in sniem-digit-argument-read-char.

**Comment by SpringHan** [comment]
Thanks, I've solved the problems you said.

**Comment by riscy** [comment]
Thanks very much, looks like an interesting package.  It looks like there's one other side effect when loading your package -- `awesome-tray-module-alist` gets modified even if the user hasn't initialized sniem yet.  I think this is minor enough to not block us, but hopefully you get a chance to clean that up.

The rest of these are for your information:
- The pcase pattern for qwerty contains 39 twice
- sniem.el#L167: Optionally use `unless ...` instead of `when (null ...)`
- sniem.el#L449: There is no need to quote lambdas (neither #' nor ')
- sniem-operation.el#L654: Use `search-*`'s NOERROR argument
- sniem-operation.el#L686: Use `search-*`'s NOERROR argument
- sniem-operation.el#L711: Use `search-*`'s NOERROR argument
- sniem-operation.el#L714: Use `search-*`'s NOERROR argument
- sniem-object-catch.el#L325: Optionally use `unless ...` instead of `when (not ...)`

**Comment by SpringHan** [comment]
Thanks so much for your contribution!  
The last problems have been solved.

**Pull request merged**
