### PR TITLE
Add elegant-agenda-mode

### PR DESCRIPTION
**Pull request by justinbarclay**
### Brief summary of what the package does

elegant-org-agenda is a theme, of sorts, for org-agenda that overrides some fonts and typefaces to create an elegant looking agenda.

### Direct link to the package repository

https://github.com/justinbarclay/elegant-agenda-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### Additional
For what it's worth I've also set-up [melpazoid](https://github.com/justinbarclay/elegant-agenda-mode/runs/1416134117) to verify linting rules are maintained.

### CODE REVIEW

**Comment by alphapapa** [comment]
This looks interesting.  Curious, have you tried it with `org-super-agenda` and `org-ql` views?

**Comment by justinbarclay** [comment]
I haven't but I think it looks good in `org-super-agenda`. I think the only thing I'd want to futz with more are the positioning of tags, but I think that's a bit more challenging with variable-width fonts.
image

**Comment by justinbarclay** [comment]
I stand corrected, straight just had an old version of my package installed.

image

**Comment by riscy** [comment]
Looks good to me.  I wonder if this is the beginning of org-agendas being "themed"?

And apologies for the long turnaround time. :)

**Comment by justinbarclay** [comment]
Best Christmas present this year. Thanks for looking at this!

**Pull request merged**
