### PR TITLE
add rime recipe

### PR DESCRIPTION
**Pull request by DogLooksGood**
### Brief summary of what the package does

RIME input method in Emacs.

### Direct link to the package repository

https://github.com/DogLooksGood/emacs-rime

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by DogLooksGood** [comment]
Have tried to build and installed following the insturctions. 
But only el file is installed.

**Comment by mihaiolteanu** [comment]
> But only el file is installed.

Yes, I'm not sure your "lib.c" and "Makefile" files need to be in the recipe.
I can only guess, but those two files seem to be part of a library that the user needs to install separately and are not part of this package.

**Comment by DogLooksGood** [comment]
@mihaiolteanu 
These two files are used to build the dynamic module which is necessary for this package.

**Comment by DogLooksGood** [comment]
The CI failed due to `File already exists: /tmp/rime6412HWe/rime-20200317.1828/rime.el`

**Comment by riscy** [comment]
The `:defaults` part of the recipe already gets `rime.el`.  I'll modify.

**Comment by DogLooksGood** [comment]
I see, thanks

**Comment by purcell** [comment]
Looks good, @DogLooksGood :-)

Merging now, thanks.

**Pull request merged**
