### PR TITLE
Add recipe for sway-lang-mode

### PR DESCRIPTION
**Pull request by fgimenez**
### Brief summary of what the package does

A sway specific major mode.

### Direct link to the package repository

https://github.com/hhamud/sway-mode

### Your association with the package

A contributor.

### Relevant communications with the upstream package maintainer

I proposed to the package creator to submit the package in this issue https://github.com/hhamud/sway-mode/issues/2. Also, changes in preparation for the package submission were proposed and merged here https://github.com/hhamud/sway-mode/pull/3

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

/cc @hhamud

### CODE REVIEW

**Comment by hhamud** [comment]
Nice!.

**Comment by riscy** [comment]
Thanks for this.  I think there is a namespace conflict with https://melpa.org/#/sway .  One way to avoid this would be to rename this to `sway-lang-mode`.

`sway-mode.el` with byte-compile using Emacs 28.1:
```
sway-mode.el:94:17: Warning: reference to free variable
    `lsp-language-id-configuration'
sway-mode.el:94:17: Warning: assignment to free variable
    `lsp-language-id-configuration'
In end of data:
sway-mode.el:102:53: Warning: the function `lsp-package-path' is not known to
    be defined.
sway-mode.el:101:38: Warning: the function `lsp-stdio-connection' is not known
    to be defined.
sway-mode.el:99:5: Warning: the function `make-lsp-client' is not known to be
    defined.
sway-mode.el:98:4: Warning: the function `lsp-register-client' is not known to
    be defined.
sway-mode.el:96:4: Warning: the function `lsp-dependency' is not known to be
    defined.
sway-mode.el:86:32: Warning: the function `rust-mode' is not known to be
    defined.
```
You do have a `Package-Requires` on `lsp`, but you probably need to `(require ..)` it; the dependency on rust-mode appears to need to be captured in the Package-Requires line.

`sway-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- sway-mode.el#L64: Top-level `setq` should usually be replaced by `defvar`
```

Package and license:
- Apache License 2.0 (via API)
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to sway-mode.el ; the reason for this is because these methods are machine-detectable which makes it easier to automatically check your package license

**Comment by fgimenez** [comment]
Thanks @riscy we have pushed changes to the package repo and melpazoid is passing, also updated the recipe to `sway-lang-mode` as suggested, please take another look.

**Comment by riscy** [comment]
Thanks!  Here's the latest --

`sway-lang-mode.el` with byte-compile using Emacs 28.1:
```
sway-lang-mode.el:104:53: Warning: the function `lsp-package-path' might not
    be defined at runtime.
sway-lang-mode.el:103:38: Warning: the function `lsp-stdio-connection' might
    not be defined at runtime.
sway-lang-mode.el:101:5: Warning: the function `make-lsp-client' might not be
    defined at runtime.
sway-lang-mode.el:100:4: Warning: the function `lsp-register-client' might not
    be defined at runtime.
sway-lang-mode.el:98:4: Warning: the function `lsp-dependency' might not be
    defined at runtime.
sway-lang-mode.el:88:37: Warning: the function `rust-mode' might not be
    defined at runtime.
```
It looks like these are pointing to missing `(require 'lsp)` and `(require 'rust-mode)` lines

**Comment by fgimenez** [comment]
> It looks like these are pointing to missing (require 'lsp) and (require 'rust-mode) lines

ok, should be fixed now, pls take another look

**Comment by hhamud** [comment]
@riscy Is it possible for you to take another look at this?

**Comment by riscy** [comment]
Looks good!  Merging.

**Pull request merged**
