### PR TITLE
Add recipes for org-zettelkasten and zettelkasten

### PR DESCRIPTION
**Pull request by ymherklotz**
### Brief summary of what the package does

This package provides a very simple and minimal implementation of the Zettelkasten method, either using org-mode as a base (`org-zettelkasten`), or an implementation from scratch without any large dependencies (`zettelkasten`).

### Direct link to the package repository

https://github.com/ymherklotz/emacs-zettelkasten

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- some quick feedback:

### zettelkasten.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
zettelkasten.el:97: Argument `link-text' should appear (as LINK-TEXT) in the doc string
```

package-lint (using version 20210528.2348):
```
1 issue found:
318:98: error: You should depend on (emacs "25.1") if you need `string>'.
```

Other [lints](https://github.com/riscy/melpazoid):
- zettelkasten.el#L235: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L259: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L261: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L280: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L286: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L299: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L312: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L323: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L333: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L341: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L362: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L371: There is no need to quote lambdas (neither #' nor ')
- zettelkasten.el#L212: `concat` may be unneeded; `insert` can take multiple arguments
- zettelkasten.el#L224: `concat` may be unneeded; `insert` can take multiple arguments
- zettelkasten.el#L329: `concat` may be unneeded; `insert` can take multiple arguments
- zettelkasten.el#L360: `concat` may be unneeded; `insert` can take multiple arguments

### org-zettelkasten.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- I would avoid quoting `org-mode` in the summary line just in case it interferes with tokenization and search
- org-zettelkasten.el#L101: There is no need to quote lambdas (neither #' nor ')
- org-zettelkasten.el#L140: Simply loading this package shouldn't automatically enable the mode; let the user enable the mode explicitly
- The default directory of `org-zettelkasten-directory` seems too presumptuous (what if someone doesn't want their private notes automatically uploaded to Dropbox?  moreover `zk` is so short as to be cryptic); I'd go with something safer like `(concat (file-name-directory user-init-file) "/org-zettelkasten)"

**Comment by ymherklotz** [comment]
Thanks so much for the quick feedback!

I don't know how I missed those `package-lint` and `checkdoc` warnings, sorry about that.  These are fixed in the main repository though.

I have also removed `#'` from the lambdas and removed `concat` from `insert`.

> I would avoid quoting org-mode in the summary line just in case it interferes with tokenization and search

Yes that makes more sense, I have removed the quoting from the summary line.

> Simply loading this package shouldn't automatically enable the mode; let the user enable the mode explicitly

And that's true, I'll add that in the instructions instead.

> The default directory of org-zettelkasten-directory seems too presumptuous

Yes, sorry about that, even I don't use dropbox and just use that as my default documents directory.  I should have checked that before, as it's definitely just a personal configuration.

**Comment by ymherklotz** [comment]
One note though, it seems like `melpazoid` errors out if I use `(concat (file-name-directory user-init-file) "/org-zettelkasten")` as the `defcustom` for `org-zettelkasten-directory`.

From the errors, it seems like `user-init-file` is `nil` and therfore make `file-name-directory` fail.  For now, to appease `melpazoid` in my github actions, I have set the default directory to be `(expand-file-name "~/zettelkasten")` which works.

**Comment by riscy** [comment]
Huh!  I should fix that.  Thanks for mentioning it.  I suspect it's because user-init-file is nil when running Emacs in batch mode.

**Comment by riscy** [comment]
This looks good to go.  Welcome to MELPA. :)

**Pull request merged**
