### PR TITLE
Add recipe for ai-mode

### PR DESCRIPTION
**Pull request by Lispython**
### Brief summary of what the package does

This package provides a minor mode for interacting with AI.
The main idea of the extension is to provide the user various possibilities for interacting with AI.
The package allows the use of various backends as AI and allows the addition of other custom integrations.

### Direct link to the package repository

https://github.com/ai-mode/ai-mode

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
I believe there are several packages (on MELPA alone) doing similar things; have you had a chance to compare to any of them, and/or to possibly submit your ideas to them?  In the meantime, here's a quick first pass --

`ai-chat.el` with package-lint 20230315.1052:
```
1 issue found:
7:0: error: Package-Requires outside the main file have no effect.
```

`ai-chat.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ai-chat.el#L11: This may be a copy-paste error?
- ai-chat.el#L47: Customizable variables shouldn't be private
- ai-chat.el#L58: Customizable variables shouldn't be private
- ai-chat.el#L63: Customizable variables shouldn't be private
- ai-chat.el#L68: Customizable variables shouldn't be private
- ai-chat.el#L79: Customizable variables shouldn't be private
- ai-chat.el#L87: Customizable variables shouldn't be private
- ai-chat.el#L214: No `format` required; `message` takes an f-string
- ai-chat.el#L222: No `format` required; `message` takes an f-string
- ai-chat.el#L410: No `format` required; `message` takes an f-string
```

`ai-completions.el` with byte-compile using Emacs 28.1:
```
ai-completions.el:51:1: Warning: defcustom for
    `ai-completions--current-backend' fails to specify type
ai-completions.el:51:1: Warning: defcustom for
    `ai-completions--current-backend' fails to specify type
In ai-completions--coordinator:
ai-completions.el:131:8: Warning: docstring wider than 80 characters
In ai-completions--get-text-to-complete:
ai-completions.el:193:8: Warning: Unused lexical variable `min-point'
In ai-completions--select-prev-or-abort:
ai-completions.el:307:11: Warning: Unused lexical variable `result'
In ai-completions-change-backend:
ai-completions.el:438:34: Warning: reference to free variable
    `ai--change-backend-prompt'
```

`ai-completions.el` with checkdoc 0.6.2:
```
ai-completions.el:550: First sentence should end with punctuation
```

`ai-completions.el` with package-lint 20230315.1052:
```
2 issues found:
7:0: error: Package-Requires outside the main file have no effect.
549:0: error: "print-buffer-lang" doesn't start with package's prefix "ai".
```

`ai-completions.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ai-completions.el#L328: It's safer to sharp-quote function names; use `#'`
- ai-completions.el#L329: It's safer to sharp-quote function names; use `#'`
- ai-completions.el#L330: It's safer to sharp-quote function names; use `#'`
- ai-completions.el#L331: It's safer to sharp-quote function names; use `#'`
- ai-completions.el#L11: This may be a copy-paste error?
- ai-completions.el#L39: Customizable variables shouldn't be private
- ai-completions.el#L45: Customizable variables shouldn't be private
- ai-completions.el#L51: Customizable variables shouldn't be private
- ai-completions.el#L56: Customizable variables shouldn't be private
- ai-completions.el#L64: Customizable variables shouldn't be private
- ai-completions.el#L77: Customizable variables shouldn't be private
- ai-completions.el#L324: Lighter should start with a space **this lighter is also absurdly long**
- ai-completions.el#L139: No `format` required; `message` takes an f-string
- ai-completions.el#L158: No `format` required; `message` takes an f-string
- ai-completions.el#L165: No `format` required; `message` takes an f-string
- ai-completions.el#L319: No `format` required; `message` takes an f-string
- ai-completions.el#L440: No `format` required; `message` takes an f-string
- ai-completions.el#L552: No `format` required; `message` takes an f-string
```

`ai-mode.el` with byte-compile using Emacs 28.1:
```
ai-mode.el:92:1: Warning: defcustom for `ai-async-query-backend' fails to
    specify type
ai-mode.el:92:1: Warning: defcustom for `ai-async-query-backend' fails to
    specify type
ai-mode.el:105:1: Warning: defcustom for `ai-sync-query-backend' fails to
    specify type
ai-mode.el:105:1: Warning: defcustom for `ai-sync-query-backend' fails to
    specify type
In ai--async-query-by-type:
ai-mode.el:252:8: Warning: docstring wider than 80 characters
In ai-perform-async-backend-query:
ai-mode.el:309:50: Warning: Unused lexical variable `extra-params'
In end of data:
ai-mode.el:228:5: Warning: the function `ai--with-current-buffer-callback' is
    not known to be defined.
```

`ai-mode.el` with package-lint 20230315.1052:
```
2 issues found:
7:37: warning: Use a properly versioned dependency on "cl-lib" if possible.
7:44: warning: An explicit dependency on cl-lib <= 1.0 is not needed on Emacs >= 24.3.
```

`ai-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ai-mode.el#L174: It's safer to sharp-quote function names; use `#'`
- ai-mode.el#L175: It's safer to sharp-quote function names; use `#'`
- ai-mode.el#L176: It's safer to sharp-quote function names; use `#'`
- ai-mode.el#L177: It's safer to sharp-quote function names; use `#'`
- ai-mode.el#L11: This may be a copy-paste error?
- ai-mode.el#L76: Customizable variables shouldn't be private
- ai-mode.el#L81: Customizable variables shouldn't be private
- ai-mode.el#L87: Customizable variables shouldn't be private
- ai-mode.el#L119: Customizable variables shouldn't be private
- ai-mode.el#L124: Customizable variables shouldn't be private
- ai-mode.el#L290: No `format` required; `message` takes an f-string
- ai-mode.el#L298: No `format` required; `message` takes an f-string
```

`ai-openai-chat.el` with byte-compile using Emacs 28.1:
```
ai-openai-chat.el:49:11: Warning: docstring wider than 80 characters
ai-openai-chat.el:49:51: Warning: Unused lexical variable `fail-callback'
In ai-openai-chat--sync-request:
ai-openai-chat.el:78:11: Warning: docstring wider than 80 characters
In ai-openai-chat--async-send-query:
ai-openai-chat.el:115:11: Warning: docstring wider than 80 characters
In ai-openai-chat--async-send-context:
ai-openai-chat.el:130:11: Warning: docstring wider than 80 characters
In ai-openai-chat--sync-send-query:
ai-openai-chat.el:146:11: Warning: docstring wider than 80 characters
```

`ai-openai-chat.el` with package-lint 20230315.1052:
```
1 issue found:
7:0: error: Package-Requires outside the main file have no effect.
```

`ai-openai-chat.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ai-openai-chat.el#L11: This may be a copy-paste error?
- ai-openai-chat.el#L39: Customizable variables shouldn't be private
- ai-openai-chat.el#L90: No `format` required; `message` takes an f-string
```

`ai-openai-completions.el` with byte-compile using Emacs 28.1:
```
ai-openai-completions.el:50:11: Warning: docstring wider than 80 characters
ai-openai-completions.el:50:55: Warning: Unused lexical variable
    `fail-callback'
ai-openai-completions.el:64:50: Warning: Unused lexical variable `n'
In ai-openai-completions--sync-request:
ai-openai-completions.el:77:11: Warning: docstring wider than 80 characters
ai-openai-completions.el:88:50: Warning: Unused lexical variable `n'
In ai-openai-completions--async-send-query:
ai-openai-completions.el:107:11: Warning: docstring wider than 80 characters
In ai-openai-completions--sync-send-query:
ai-openai-completions.el:124:11: Warning: docstring wider than 80 characters
ai-openai-completions.el:124:76: Warning: Unused lexical variable `message'
In ai-openai-completions--completion-backend:
ai-openai-completions.el:141:11: Warning: docstring wider than 80 characters
```

`ai-openai-completions.el` with package-lint 20230315.1052:
```
1 issue found:
7:0: error: Package-Requires outside the main file have no effect.
```

`ai-openai-completions.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ai-openai-completions.el#L11: This may be a copy-paste error?
- ai-openai-completions.el#L37: Customizable variables shouldn't be private
```

`ai-openai.el` with package-lint 20230315.1052:
```
1 issue found:
7:0: error: Package-Requires outside the main file have no effect.
```

`ai-openai.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ai-openai.el#L11: This may be a copy-paste error?
- ai-openai.el#L43: Customizable variables shouldn't be private
- ai-openai.el#L48: Customizable variables shouldn't be private
- ai-openai.el#L53: Customizable variables shouldn't be private
- ai-openai.el#L58: Customizable variables shouldn't be private
```

`ai-utils.el` with byte-compile using Emacs 28.1:
```
ai-utils.el:316:66: Warning: Unused lexical variable `response'
```

`ai-utils.el` with package-lint 20230315.1052:
```
1 issue found:
7:0: error: Package-Requires outside the main file have no effect.
```

`ai-utils.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ai-utils.el#L185: It's safer to sharp-quote function names; use `#'`
- ai-utils.el#L186: It's safer to sharp-quote function names; use `#'`
- ai-utils.el#L11: This may be a copy-paste error?
- ai-utils.el#L36: Customizable variables shouldn't be private
- ai-utils.el#L52: Customizable variables shouldn't be private
```

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to reach out.

**Comment by riscy** [comment]
Friendly ping again. :)

**Comment by riscy** [comment]
Hi @Lispython -- you have several other PRs open but I haven't heard a response to this one yet.  If you want to close this one until it's ready, we can move ahead with the others.

**Comment by riscy** [comment]
Hi @Lispypython -- please let me know if you are intending to fix the above issues.  Otherwise, I'll close this PR next week.

**Comment by riscy** [comment]
(This will at least let me move onto your other PRs.)

**Comment by Lispython** [comment]
I'm sorry, I currently have no time to fix the remarks. As soon as I have some availability, I will open a new PR. My other PRs related to this and I will close them too.

**Pull request closed without merging**
