### PR TITLE
add dante

### PR DESCRIPTION
**Pull request by jyp**
### Brief summary of what the package does

Emacs mode for Interactive Haskell

[[http://stable.melpa.org/packages/dante-badge.svg]]

Dante is a fork of Intero mode. It steals many good ideas from Intero,
it aims for light weightedness. Dante has no dependency on "Stack" nor
on any custom Haskell code. Dante's Emacs code is about half as long
as that of Intero. Flychecking is optional (yet recommended).

### Direct link to the package repository

https://github.com/jyp/dante

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Please do not global functions/variables/macros which don't start with package prefix. In this case, `cps-bind` and `cps-let` for name conflict.
- This package requires haskell-mode however it does not load haskell-mode.

**Comment by jyp** [comment]
I have fixed those two problems in dante/master. Thanks for pointing them out!

**Comment by purcell** [comment]
Thanks - this is really interesting!

Quick feedback from me:
- The `:files` spec is not necessary here, and should be omitted from the recipe. The README covers this a little.
- You've got a package description in the header, but it should be in the `Commentary:` section of the header so it can be parsed out by the various tools (including ours) which expect standard elisp boilerplate formatting.
- The keybindings you're using are reserved for major modes, as per the [elisp manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html). Are they "borrowed" from `intero`?
- `(flycheck-select-checker 'haskell-ghc)` should probably be replaced with code that simply triggers `flycheck` to re-select the default checker itself, in case that would not be `haskell-ghc` given the user's config.

**Comment by jyp** [comment]
Thanks for all the good points. Regarding the keybindings: I've changed them to fit the convention (as far as I understand).

Yet, to answer your question: indeed, Intero steals keybindings of the form C-c C-<letter>. There is a long tradition of doing so in interactive "layers" over the (major) Haskell mode. Perhaps the Haskell major mode should officialize the tradition (maybe it does already).

**Comment by purcell** [comment]
> Yet, to answer your question: indeed, Intero steals keybindings of the form C-c C-letter. There is a long tradition of doing so in interactive "layers" over the (major) Haskell mode. Perhaps the Haskell major mode should officialize the tradition (maybe it does already).

Yeah, I think haskell mode and its extensions have been a bit of a "Wild West" for some time! :-)  I'm keen to try `dante` out myself, as a mostly-satisfied `intero` user. I'd love to know (or be able to read about) the differences between the two: presumably `intero` is able to do a bunch of stuff which `dante` can't.

**Comment by jyp** [comment]
@purcell : Intero is "stack only", which is a no-go for me. Dante will work with any GHCi.
Additionally, Dante:
* supports xref-find-definitions / xref-find-references
* has a different approach to Haskell evaluation
* does not support eldoc nor hoogle

**Comment by purcell** [comment]
Cool - thanks for the notes. You should put those in the README too. :-)

**Pull request merged**
