### PR TITLE
Add recipe for graphql-ts-mode

### PR DESCRIPTION
**Pull request by jorams**
### Brief summary of what the package does

A major mode for GraphQL documents based on the built in support for tree-sitter.

### Direct link to the package repository

https://git.sr.ht/~joram/graphql-ts-mode

### Your association with the package

I'm the creator and maintainer of this package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`graphql-ts-mode.el` with byte-compile using Emacs 28.1:
```
graphql-ts-mode.el:220:21: Warning: the function `cl-loop' is not known to be
    defined.
graphql-ts-mode.el:197:4: Warning: the function `cl-flet' is not known to be
    defined.
graphql-ts-mode.el:183:5: Warning: the function `when-let*' is not known to be
    defined.
```
For these I think you should include `(require 'cl-lib)` and `(require 'subr-x)` (rather than rely on them potentially being transitively imported)

`graphql-ts-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- graphql-ts-mode.el#L198: It's safer to sharp-quote function names; use `#'`
- graphql-ts-mode.el#L4: Triple semicolons `;;;` are usually for section headings
```
The second one here (L4) implies your front-matter should look more like this:
```elisp
;;; graphql-ts-mode.el --- Tree-sitter support for GraphQL  -*- lexical-binding: t; -*-

;; Copyright (C) 2023 Joram Schrijver <i@joram.io>

;; Author: Joram Schrijver <i@joram.io>
;; Maintainer: Joram Schrijver <i@joram.io>
;; Created: September 2023
;; Version: 0.1.0
;; License: GPL-3.0-or-later
;; Package-Requires: ((emacs "29.1"))
;; Keywords: languages graphql tree-sitter
;; URL: https://sr.ht/~joram/graphql-ts-mode/
```

**Comment by jorams** [comment]
Thanks! I've fixed all of these except for `(require 'subr-x)`. In Emacs 29.1 `when-let*` is in `subr.el`, so I don't think it needs `subr-x` anymore?

**Comment by tarsius** [comment]
On 29.1 no; but there will be users sticking to older releases for years to come.

You could wrap the require form to only load `subr-x` when an older release is used. On the other hand, something else is bound to load `subr-x` anyway -- after all you are currently counting on that :grin: -- so you could also skip the conditional, without worrying too much that you might be responsible for it to be loaded needlessly. On the other other hand, a conditional would also document why it might be necessary to load the library.

**Comment by jorams** [comment]
I can add the require, but I still don't really understand why. This package explicitly requires Emacs 29.1 and is built on the tree-sitter support introduced in Emacs 29.1.

Is the goal for the package to be compilable in older versions despite not otherwise working? In this case the macro exists in a different location, but how would that work for macros that don't yet exist at all?

**Comment by tarsius** [comment]
It's kinda obvious 29.1 is needed, but I still missed it.
No, then we are good to go of course.

**Pull request merged**
