### PR TITLE
add recipe for master of ceremonies

### PR DESCRIPTION
**Pull request by psionic-k**
### Brief summary of what the package does

Used for authoring and conducting presentations.  I use this as a companion to dslide.  It employs Emacs display to feature selected content and to highlight it for making videos that step through expressions.

A short video of the `moc-focus` command.  https://www.reddit.com/r/freemacs/comments/1h5r8uv/master_of_ceremonies_has_been_overhauled/

### Direct link to the package repository

https://github.com/positron-solutions/moc

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

Note, checkdoc is falsely flagging HIGHLIGHTS, which is a noun in my usages.

### CODE REVIEW

**Comment by psionic-k** [comment]
```
   ! doc/moc.texi -> moc.texi
Debugger entered--Lisp error: (void-function file-name-with-extension)
```
:thinking:   I pushed a doc rebuild.  Unsure of the nature of the error.  Going to let this cook.  Philip might have illuminating feedback on the Non-GNU ELPA submission.

I'm adding some features to trim and hide text in the meantime.

**Comment by tarsius** [comment]
>     Debugger entered--Lisp error: (void-function file-name-with-extension)

db853a11396aa7d96757becef2090413f96c905b should take care of that.

**Comment by psionic-k** [comment]
I have done the basic updates to consider this ready for general exposure.

Updates from here on out are just feature adds and tweaks as I get to them / finish cooking.

**Comment by riscy** [comment]
Thanks for this (& subsequent updates).  Quick first pass -

⸺ `moc.el` with byte-compile using Emacs 29.4:
```
moc.el:635:2: Error: Need command, got `:info'
```

⸺ `moc.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- moc.el#L1200: Could this `point`/`point-max` comparison use `eobp`?
- moc.el#L1192: Consider `beginning-of-line`
- moc.el#L1201: Consider `beginning-of-line`
- moc.el#L1360: Consider `beginning-of-line`
- moc.el#L1211: Consider `end-of-line`
- moc.el#L687: Consider using %T instead of %H:%M:%S in time strings
```

⸺ `moc.el` with checkdoc 0.6.2 (fix *within reason*):
```
moc.el:710: Argument `offset' should appear (as OFFSET) in the doc string
moc.el:1090: All interactive functions should have documentation
moc.el:1105: All interactive functions should have documentation
moc.el:1145: Argument `buffer' should appear (as BUFFER) in the doc string
moc.el:1174: All variables and subroutines might as well have a documentation string
moc.el:1183: Argument `buffer' should appear (as BUFFER) in the doc string
moc.el:1244: Argument `buffer' should appear (as BUFFER) in the doc string
moc.el:1255: Open parenthesis in column 0 should be escaped
moc.el:1282: All variables and subroutines might as well have a documentation string
moc.el:1316: All variables and subroutines might as well have a documentation string
```

`#'load`-check on each file:
```
Loading moc.el
  moc.el:Error: Emacs 29.4:
  (error "Eager macro-expansion failure: (error \"Need command, got `:info'\")")
```

⸺ Package and license (note: multiple licenses)
- pkg/moc.el: MIT License
- pkg/doc/moc.texi: GPL*
- Repository: GNU General Public License v3.0

**Comment by psionic-k** [comment]
- [x] License header consistency
- [x] Check eobp and line-beginning / line-end suggestions.  Rejected because I could not obtain the same behavior with these ostensibly equivalent forms.  Reversion in history in 6a098da
- [x] Load check, newer Transient version requirement made explicit
- [x] Checkdocs
- [x] Time format replacement 

I could not find a corresponding issue in my local changes or the last master for:
> moc.el:1255: Open parenthesis in column 0 should be escaped

New version has preliminary support for visual modes.  The more I just let Emacs do the work, the more the implementation grew small and consistent across a wide variety of inputs.

**Comment by riscy** [comment]
> I could not find a corresponding issue in my local changes or the last master for [unescaped open parenthesis]

Fair, and checkdoc is within reason.  I was never able to understand the reason for this checkdoc (and maybe it has been deprecated).  But I will note that I typically don't use a bleeding edge version of Emacs for these checks - I strive to do it with the latest official release.

>  Rejected because I could not obtain the same behavior with these ostensibly equivalent forms.

Interesting.  I'll try to hunt down your changes with the hash you gave me - I'd obviously be interested to know which ones (all?) were not equivalent.

I think there have been some other code changes in the interim.  Here's the latest salient issues -

⸺ `moc.el` with byte-compile using Emacs 29.4:
```
moc.el:1032:23: Warning: the function `visual-wrap-prefix-mode' is not known to be defined.
```

⸺ `moc.el` with package-lint 20241127.1826:
```
1 issue found:
289:0: error: Global minor modes should be autoloaded or, rarely, `:require' their defining file (i.e. ":require 'moc"), to support the customization variable of the same name.
```

**Comment by riscy** [comment]
I can see in one case the replacement you used was backwards - `(goto-char (line-beginning-position))` should not be replaced with `(end-of-line)` but rather `(beginning-of-line)`:

https://github.com/positron-solutions/moc/commit/6a098da71c3ce83b8819692cd27b71b678768f60#diff-bf9f5b62971131fddb3ab3f0f8ba4acce20828e4f15061e883c23832e3e25000L1276-L1277

**Comment by psionic-k** [comment]
Lol.  Well, I hope I'm getting better at pushing master without enough sleep.

- Missing autoload confirmed & corrected
- behavior of equivalent forms confirmed & corrected
- visual wrap prefix mode, is now always confirmed `fboundp` before attempting to use.  The expressions were changed to just try either mode if either was requested (they do the same thing).  The newer one is preferred.  Since the playback will likely be suboptimal without at least one, I added a warning.

**Comment by riscy** [comment]
Looks great here :)

If you haven't, ensure GitHub release v0.6.2 is up-to-date with your current code and `Package-Version` - I'll merge this now.

**Comment by psionic-k** [comment]
Thanks.

I bumped the pre-release notes and master version to 0.6.3.  This way I can tag and freeze releases at sensible points while maintaining a completely fresh changelog history in master.  Makes sense to me.  Hope it's a good strategy.

**Pull request merged**
