### PR TITLE
Add recipe for comp-ide

### PR DESCRIPTION
**Pull request by SidharthArya**
### Brief summary of what the package does
A basic implementation of a competitive ide on emacs

### Direct link to the package repository

https://github.com/SidharthArya/comp-ide.el

### Your association with the package

I am a maintainer

### Relevant communications with the upstream package maintainer

None Needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Very quick first pass of the checklist:

### comp-ide-recipes.el ###

byte-compile (using Emacs 27.1):
```
comp-ide-recipes.el:36:7:Warning: assignment to free variable
    `comp-ide-comp-ide-compile-recipes'
comp-ide-recipes.el:43:7:Warning: assignment to free variable
    `comp-ide-comp-ide-execute-recipes'
comp-ide-recipes.el:54:7:Warning: assignment to free variable
    `comp-ide-geterrors'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
comp-ide-recipes.el:0: The first line should be of the form: ";;; package --- Summary"
```

package-lint (using version 20210528.2348):
```
4 issues found:
9:0: error: Package-Requires outside the main file have no effect.
42:37: warning: Closing parens should not be wrapped onto new lines.
53:37: warning: Closing parens should not be wrapped onto new lines.
57:22: warning: Closing parens should not be wrapped onto new lines.
```

**Comment by SidharthArya** [comment]
HI,
Fixed with https://github.com/SidharthArya/comp-ide.el/commit/a87e19cdbbe698e6dfe127615618908da660befc

**Comment by riscy** [comment]
Thanks for taking a look!  Based on the summary line I didn't know what "competitive IDE" meant.  If there's not enough room, I'd recommend changing "A very basic implementation of a competitive ide" to "A simple competitive programming IDE".

Re-running the byte-compile improves the above, but currently gives me the following:

byte-compile (using Emacs 27.1):
```
comp-ide-recipes.el:35:1:Warning: defcustom for
    `comp-ide-comp-ide-compile-recipes' fails to specify containing group
comp-ide-recipes.el:35:1:Warning: defcustom for
    `comp-ide-comp-ide-compile-recipes' fails to specify containing group
comp-ide-recipes.el:39:1:Warning: defcustom for
    `comp-ide-comp-ide-execute-recipes' fails to specify containing group
comp-ide-recipes.el:39:1:Warning: defcustom for
    `comp-ide-comp-ide-execute-recipes' fails to specify containing group
```
You could solve these by inlining this file into your main file, or else you'll have to `(require 'comp-ide)` in the recipes file and reference the :group.

I also notice you're specifying `:type 'list` in your defcustoms in comp-ide.el, but probably the customization type should be _set_ instead of _list_ (it is an unfortunate naming scheme).

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to ping me.

**Comment by SidharthArya** [comment]
Hi @riscy,
I have ujpdated the source code. Can you please check again ??

**Comment by riscy** [comment]
Thanks @SidharthArya, that puts those checks behind us!  I took some time to take a closer look at this package and I can see the value in something like this, but this needs a little more in terms of desk checking the code and/or careful active maintenance.  Some quick notes on some outstanding issues I can see as I scroll through --

- The package seems to claim the buffer names `*Input*` and `*Output*` for its own and opens and closes these whenever it likes, but I think you'd want to use something unique to the package for these
- Similarly killing buffers named `*eshell*` out of nowhere could be disruptive for users; you would want to read up on `eshell-buffer-name` for this case
- By splitting comp-ide.el and comp-ide-recipes.el into separate files, without having either one of them import the other, I believe the user has to explicitly require both of them in their configuration
- The calls to makunbound seem strange to me, for example `(makunbound 'ide-code-window)` (is that even the correct variable name?) -- followed by calls to `defvar` which should rarely if ever appear inside function definitions -- are you just trying to set these variables to nil?
- Conventionally I believe the mode name should end with `-mode`
- Minor but the lighter "ID" doesn't seem to have much to do with the name of the package
- Both `comp-ide-open` and `comp-ide-close` are running hooks (actually `comp-ide-close` is running `comp-ide-hooks` which doesn't exist) but probably you'd only want to run such things when things are being setup?

**Comment by SidharthArya** [comment]
Hi @riscy,
Thank you for the feedback. I appreciate it very much.
I will make these changes, Thanks.

**Pull request closed without merging**
