### PR TITLE
Add objed

### PR DESCRIPTION
**Pull request by clemera**
### Brief summary of what the package does

Navigate and edit text objects with Emacs 

### Direct link to the package repository

https://github.com/clemera/objed

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback. 
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Lots to look at here, but it all looks pretty sane to me. I've fixed up the recipe a bit and will merge now. Welcome to MELPA! :tada:

**Comment by clemera** [comment]
Great, thanks! One question, for updating the code of the package. Will melpa rebuild the package when I pushed new commits to my master branch or only if I update the version number? Sorry if this is obvious, this is all new to me.

**Comment by purcell** [comment]
Re. your deleted question about MELPA rebuilds, they happen automatically. Add version number tags to your repo if you want stable versions published to MELPA Stable. :-)

**Comment by clemera** [comment]
Thanks, I figured that out after checking the current build :)

**Pull request merged**
