### PR TITLE
Add new file directories for treemacs.

### PR DESCRIPTION
**Pull request by Alexander-Miller**
### Brief summary of what the package does

This is just an update to the existing treemacs packages to prepare for some file structure refactoring. I like to separate my code into different files, and by now I've near 20 of them, with yet more to come. Time to (eventually) clean up a little. I want to put my elisp and python code into separate directories instead of stuffing everything into root. It's supposed to look [like this](https://github.com/Alexander-Miller/treemacs/tree/files/src).
Of course the package should still be built while the change isn't made yet, so all the old files and exclusions are kept in the recipes for now. I'll open a second PR to remove them once the refactoring is made.

### Direct link to the package repository

https://github.com/Alexander-Miller/treemacs

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
I'd personally just put the python in a subdir, and leave the `.el` source at the top level. That'd save a bit of recipe clunkiness too. Is that an option?

**Comment by Alexander-Miller** [comment]
Not really. Stashing the python away won't really reduce clutter and my expectations for more scripts have been heavily dialed back - turns out synchronously querying file system contents or parsing thousands of git status entries in elisp is faster than using an asynchronous python or shell script.
So it's really all about putting away all those .el files.

**Comment by purcell** [comment]
> So it's really all about putting away all those .el files.

I guess I really just don't get it: the whole point of that repo is to hold `.el` files, and there's not much else there. So I don't see the benefit of hiding them away in a subdir. :-)

But anyway, I'll go ahead and merge.

**Comment by Alexander-Miller** [comment]
> But anyway, I'll go ahead and merge.

Thanks.

>  So I don't see the benefit of hiding them away in a subdir. :-)

There are a few advantages for me. 

 * A completely flat file structure isn't the best use-case for treemacs, which I always use to work on the repo. A few extra dirs make for much better navigation with treemacs' goto parent/neighbour button functions.
 * My own working copy is quite a bit more cluttered than what you see on github. I have directories for testing git parsing, icon display and performance, and 3 or more various scripts that I play with.
 * Professionally I do java, so I guess this is just what I'm used to.

**Comment by purcell** [comment]
:+1:

**Pull request merged**
