### PR TITLE
Add recipe for declutter

### PR DESCRIPTION
**Pull request by sanel**
### Brief summary of what the package does

declutter is a small Emacs addon that will help you with reading online content. It will remove all distractions and present you with readable html, straight inside your Emacs.

### Direct link to the package repository

https://github.com/sanel/declutter

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- please take a look at the checklist:

checkdoc (using version 0.6.2):
```
Warning (emacs): 
declutter.el:159: Argument `url' should appear (as URL) in the doc string
```

package-lint (using version 20210528.2348):
```
8 issues found:
9:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
42:10: error: You should depend on (emacs "24.1") if you need `shr'.
43:10: error: You should depend on (emacs "24.4") if you need `eww'.
50:0: error: "outline-api" doesn't start with package's prefix "declutter".
108:9: error: You should depend on (emacs "24.4") if you need `shr-render-region'.
139:9: error: You should depend on (emacs "25.1") if you need `eww-readable'.
154:5: error: You should depend on (emacs "24.4") if you need `eww-mode'.
156:5: error: You should depend on (emacs "24.4") if you need `eww'.
```

And a couple other nags:
- declutter.el#L155: It's safer to sharp-quote function names; use `#'`
- declutter.el#L142: It's safer to sharp-quote function names; use `#'`
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by sanel** [comment]
Thank you @riscy! I've fixed all mentioned warnings and errors.

**Comment by riscy** [comment]
Looks solid.  Thanks for this.

**Comment by sanel** [comment]
Thank you!

**Pull request merged**
