### PR TITLE
Add gotest-ts package

### PR DESCRIPTION
**Pull request by chmouel**
Add package gotest-ts https://github.com/chmouel/gotest-ts.el/

### Brief summary of what the package does

let you run gotests subtest with treesitter 

### Direct link to the package repository

https://github.com/chmouel/gotest-ts.el/

### Your association with the package

maintainer

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [] I've built and installed the package using the instructions in [CONTRIBUTING.org](ht[[[[tps://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
]]]]

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

⸺ `gotest-ts.el` with byte-compile using Emacs 29.4:
```
gotest-ts.el:41:2: Warning: custom-declare-variable `gotest-ts-get-subtest-key' docstring has wrong usage of unescaped single quotes (use \= or different quoting)
```

⸺ `gotest-ts.el` with package-lint 20241127.1826:
```
1 issue found:
6:38: warning: Use a non-snapshot version number for dependency on "gotest" if possible.
```
(see: https://stable.melpa.org/#/gotest)

Lastly I notice your file gotest-ts.el has GPL boilerplate, but your repository is Apache 2.0-licensed.

**Comment by chmouel** [comment]
Thank you so much for that thorough review @riscy I have fixed the warnings and error you mentioned.

**Comment by riscy** [comment]
Thanks!  I will merge but note that your `;;; Commentary` doesn't need to include the word `commentary` at the top (probably an oversight :)

```
;;; Commentary:

;; commentary
;; This mode provides Emacs functionality for running tests using GoTest
;; and Treesitter.
```
(third line)

**Comment by chmouel** [comment]
Very nice thank you, I'll fix the extraneous commentary

**Pull request merged**
