### PR TITLE
Add snap-indent recipe

### PR DESCRIPTION
**Pull request by jeffvalk**
### Brief summary of what the package does

Snap-indent provides simple automatic indentation (and optional formatting) when yanking/pasting text.

### Direct link to the package repository

https://github.com/jeffvalk/snap-indent

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
- I have seen something similar to this, although I can't remember exactly.  Have you had a chance to look at/compare to [auto-indent-mode](https://github.com/mattfidler/auto-indent-mode.el)?

**Comment by jeffvalk** [comment]
Yes, `snap-indent` came about because `auto-indent-mode` has interoperability bugs with common packages (company, swiper, and others) that have remained unaddressed for years (see [here](https://github.com/mattfidler/auto-indent-mode.el/issues/65), [here](https://github.com/mattfidler/auto-indent-mode.el/issues/66), and [here](https://github.com/mattfidler/auto-indent-mode.el/issues/70)). 

My original preference was to fix those and submit a PR to auto-indent-mode, but when I looked at that package's source, I was a bit shocked to find that it is 2655 lines of code. For the use case, I expected something minimal and compact. I think simple and hygienic is the better approach, so this package seemed sensible. 

This rationale is mentioned in `snap-indent`'s readme section titled [Replacement for auto-indent-mode](https://github.com/jeffvalk/snap-indent/blob/2bf8634e2ee795c06dae09881ae1bdc39ed4112a/README.md#replacement-for-auto-indent-mode).

**Comment by riscy** [comment]
Oh, and Makefiles.

**Comment by jeffvalk** [comment]
Good thoughts. Thanks. Done.

**Pull request merged**
