### PR TITLE
Add org babel functions for CFEngine 3

### PR DESCRIPTION
**Pull request by nickanderson**
I am the author of the package.
The code can be found here: https://github.com/nickanderson/ob-cfengine3

### CODE REVIEW

**Comment by nickanderson** [comment]
Made fixups for package-lint, executed recipie with result:

```
;; Please check the following package descriptor.
;; If the correct package description or dependencies are missing,
;; then the source .el file is likely malformed, and should be fixed.
(ob-cfengine3 .
              [(20170906 831)
               nil "Org Babel functions for CFEngine 3" single
               ((:authors
                 ("Nick Anderson" . "nick@cmdln.org"))
                (:maintainer "Nick Anderson" . "nick@cmdln.org")
                (:url . "https://github.com/nickanderson/ob-cfengine3"))])
```

**Comment by purcell** [comment]
Thanks! Few little issues here:
- No licence info. Please use the standard boilerplate, as inserted by `M-x auto-insert`. (Try that in an empty file.)
- You're concatenating filenames into commands without using `shell-quote-argument`, so you're going to have a bad time with paths that contain spaces or quotes.
- Generally you shouldn't use the full path of an executable by default: instead, rely on Emacs having its PATH set properly. So try `cf-agent` instead of `/var/cfengine/bin/cf-agent`.
- `(delete-file tempfile)` should probably be in an `unwind-protect` form, to ensure it always gets called.
- The autoloaded `eval-after-load` block is not idiomatic. Instead, require `ob` at the top, then simply modify the variables directly. See [this](https://github.com/corpix/ob-blockdiag.el/blob/master/ob-blockdiag.el) and [this](https://github.com/stig/ob-applescript.el/blob/master/ob-applescript.el) for examples.

Hope that helps!

**Comment by nickanderson** [comment]
Hey, thanks for the code review!

I will look into these. It may be a while before I can address them.

This was my first package and some of the first elisp i have cobbled together.

**Comment by nickanderson** [comment]
@purcell I tried to address all of your points.

**Comment by nickanderson** [comment]
Thanks!

**Pull request merged**
