### PR TITLE
Add jump-tree recipe.

### PR DESCRIPTION
**Pull request by yangwen0228**
### Brief summary of what the package does

This package is inspired by and a combination of undo-tree and jumplist, and copy a lot of codes from them. With this package, we can jump back and forth in a tree way like undo-tree.

### Direct link to the package repository

https://github.com/yangwen0228/jump-tree

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. This is neat! Merging now - welcome to MELPA!

**Comment by yangwen0228** [comment]
@purcell Many thanks! Actually, I'm a big fan of you! The very first starter-kit I used is yours, that helps me a lot to switch from Vim to Emacs(that time, you use Evil, and I love Evil, too). After you stop using Evil, I stoped using Evil, too(get annoyed about the different Evil states and keybindings conflict). I learned a lot from your configurations.

**Comment by purcell** [comment]
I'm glad my config was helpful to you! :-)

**Comment by alphapapa** [comment]
@yangwen0228 I'm curious, I see that the copyright in the file is 2009-2017.  Did you really make this in 2009 and only publish it just now?  :)

**Comment by yangwen0228** [comment]
Sorry. Publish it just now. This file is modified based on the undo-tree.el, so maybe some contents are just not correct and I pay little attention to that stuffs.😊

**Comment by alphapapa** [comment]
Cool!  :)

**Comment by yangwen0228** [comment]
Add some more features: 
1. support commands not in the record list, but the movement is exceeding the threshold, like 200 points;
2. when switch to another buffer.
We can always move back and forth conveniently.

**Pull request merged**
