### PR TITLE
Add meson-mode

### PR DESCRIPTION
**Pull request by wentasah**
### Brief summary of what the package does

This package simplifies editing of Meson build system scripts. It does syntax highlighting and indentation.

### Direct link to the package repository

https://github.com/wentasah/meson-mode

### Your association with the package

I'm the author and maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- This package cannot be byte-compiled. (Please check https://github.com/wentasah/meson-mode/pull/3)

**Comment by wentasah** [comment]
Your fix is merged. Thanks.

**Comment by syohex** [comment]
There are some smie warnings. Is it no problem ?

```
Warning (smie): Conflict: eol =/> elif
Warning (smie): Total: 1 warnings
```

**Comment by wentasah** [comment]
On Wed, Mar 29 2017, Syohei YOSHIDA wrote:
> There are some smie warnings. Is it no problem ?
>
> ```
> Warning (smie): Conflict: eol =/> elif
> Warning (smie): Total: 1 warnings
> ```

It could cause problems with indentation in certain cases, but I have
not figured out how to solve it properly. Anyway, I've committed a
(temporary) fix.

Thanks.
-Michal

**Comment by purcell** [comment]
Thanks! Mostly looks great - nice work! Just a couple of points I noticed:
- I feel like when there are two multiline strings in a buffer, `(rx "'''" (zero-or-more anything) "'''")` might match from the beginning of one to the end of the second?
- F6-F8 are reserved for users, so you must not bind them. See the [keybinding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) for more on which keys you can bind on the user's behalf.

**Comment by wentasah** [comment]
> - I feel like when there are two multiline strings in a buffer, `(rx
> "'''" (zero-or-more anything) "'''")` might match from the beginning
> of one to the end of the second?

Yes. Good catch.

> - F6-F8 are reserved for users, so you must not bind them. See the
> keybinding conventions for more on which keys you can bind on the
> user's behalf.

Both problems are now fixed. Thanks.

**Comment by purcell** [comment]
Great, thanks!

**Pull request merged**
