### PR TITLE
Add recipe for py-vterm-interaction

### PR DESCRIPTION
**Pull request by vale981**
### Brief summary of what the package does

This is a port (clone) of https://github.com/shg/julia-vterm.el to python
with some slight modifications and tweaks.

### Direct link to the package repository

https://github.com/vale981/py-vterm-interaction.el

### Your association with the package

I'm the maintainer. Most of the code must be credited to the Shigeaki Nishina (@shg).

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Hi @vale981 , do you still intend for this PR to be a draft?  When it's ready, please mark it as "Ready for review".  I apologize for not noticing sooner, since I filter out draft PRs.  In the meantime, here's a quick first pass of what you've got, in case it's helpful -

`python-vterm.el` with package-lint 20240507.1722:
```
3 issues found:
325:37: error: You should depend on (emacs "27.1") if you need `json-parse-buffer'.
631:2: error: Aliases should start with the package's prefix "python-vterm".
634:2: error: Aliases should start with the package's prefix "python-vterm".
```

`python-vterm.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- python-vterm.el#L605: It's safer to sharp-quote function names; use `#'`
- python-vterm.el#L631: It's safer to sharp-quote function names; use `#'`
```

**Comment by vale981** [comment]
hi :). I'll have to check with the original author, although my "fork" has deviated significantly. I think it's ok for now to publish it, if it wasn't that session management is plain broken. Once I fix that, I'll mark this ready for review.

**Comment by shg** [comment]
Hi, I am the author of julia-vterm.el.

As @vale981 knows, I have been developing [python-vterm.el](https://github.com/shg/python-vterm.el), as well as [ob-python-vterm.el](https://github.com/shg/ob-python-vterm.el), aiming to provide similar usability and Babel support in Python as with the combination of [julia-vterm.el](https://github.com/shg/julia-vterm.el) and [ob-julia-vterm.el](https://github.com/shg/ob-julia-vterm.el).

As julia-vterm.el and ob-julia-vterm.el are already published on MELPA, I was planning to register my version of python-vterm.el also on MELPA at some point. However, as I understand it, different packages with the same name cannot coexist on MELPA.

I'd like to request that this package use a different name to avoid possible confusion, if published as an independent package on MELPA. I understand that you can't be forced to do this. This is just a request from the author of julia-vterm.el.

**Comment by vale981** [comment]
Hey, I'm totally fine with renaming it (or not publishing it at all). As of now, our aims are a little different, and I'm mostly scratching my own itch with the package.

**Comment by vale981** [comment]
Ok, I fixed the session management and renamed the package :).

**Comment by riscy** [comment]
Thanks for the update!  Here's the latest -

`py-vterm-interaction.el` with byte-compile using Emacs 29.4:
```
py-vterm-interaction.el:403:15: Warning: Variable `py-vterm-interaction-paste-with-return' declared after its first use
py-vterm-interaction.el:406:15: Warning: Variable `py-vterm-interaction-paste-with-clear' declared after its first use
In py-vterm-interaction-send-region-or-current-line:
py-vterm-interaction.el:495:2: Warning: docstring wider than 80 characters
In py-vterm-interaction-send-run-buffer-file:
py-vterm-interaction.el:595:2: Warning: docstring wider than 80 characters
py-vterm-interaction.el: Error: Invalid read syntax: "#", 625, 43
```
Note the last one re: invalid read syntax is because you've got sharp-quoting inverted - should be `#'` rather than `'#` - and this happens a couple places in the file.

`py-vterm-interaction.el` with package-lint 20240913.1546:
```
1 issue found:
654:2: error: Aliases should start with the package's prefix "py-vterm-interaction".
```
What's the purpose for these conditional aliases?  I would just suggest to the users to put this alias in their configs, if they want to use it - problem solved.

**Comment by vale981** [comment]
Oh my goodness :P something must have gone wrtong here :P. W/r/t the aliases: that's from julia-vterm. I'll remove that :)

**Comment by vale981** [comment]
all should be fixed now. i ran byte-compile w/o any issues

**Comment by riscy** [comment]
No problem - it's pleasant to write elisp within Emacs, but it does often result in stuff that hasn't been byte-compiled from scratch (probably something like 25% of the time - it's very high).

**Comment by riscy** [comment]
Welcome to MELPA, btw. :)

**Pull request merged**
