### PR TITLE
Add embark recipe

### PR DESCRIPTION
**Pull request by oantolin**
### Brief summary of what the package does

Embark provides a sort of right-click or contextual menu for Emacs, making it easy to run relevant actions on the current target, which can be a minibuffer completion candidate or the thing at point. The actions offered depend on the type of target, for example, if you are currently in `find-file`, Embark will offer you actions such as `copy-file`, `delete-file`, `make-directory`, etc. The determination of what the target is and which actions to offer is highly configurable.

This is similar to the notion of actions in the well-known Helm and Ivy packages (though those are limited to acting on minibuffer completion candidates).

### Direct link to the package repository

https://github.com/oantolin/embark

### Your association with the package

I am the author and maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, look neat.  A couple bits of feedback:

- Instead of `(autoload 'package-delete "package")` etc., you should probably just `(require 'package)` if possible
- I notice you're using `embark-action<%s>` to define parenthesized functions, but the community style is to use hyphens as delimiters.  I think the reason package-lint admits these is to support the names of comparison function names.  This looks like an established package so I don't know how much that would break, so I think we shouldn't insist

And a quick ispell -
- choosen -> chosen
- particulary -> particularly

**Comment by oantolin** [comment]
> Thanks, look neat.

Thank you!
> A couple bits of feedback:
> * Instead of `(autoload 'package-delete "package")` etc., you should probably just `(require 'package)` if possible

I wouldn't mind requiring those packages. The autoloads are there so that people can use Embark without being forced to load those packages. They do all come with Emacs, so I think I mostly used the `autoload` route because I feared upsetting the people that go to some effort to avoid loading `package.el`. (I don't think anybody would mind me requiring, say, `dired`, but some people seem to have it in for `package.el`.) How important would you say it is to change this?

> * I notice you're using `embark-action<%s>` to define parenthesized functions, but the community style is to use hyphens as delimiters.  I think the reason package-lint admits these is to support the names of comparison function names.  This looks like an established package so I don't know how much that would break, so I think we shouldn't insist

Well, I consider the format of those autogenerated command names to be an implementation detail, so I have no problem at all in changing them. I made them `embark-action--%s` now oantolin/embark@9b4dab834a2be2b73eec41ebc1671a61b9a151cd. People aren't meant to even need to know what these names are! 
 
> And a quick ispell -
> 
> * choosen -> chosen
> * particulary -> particularly

Oops, thank you! oantolin/embark@339d87fa03f17ff13be18ef7d6dc3526cf5e1b1a

**Comment by minad** [comment]
@riscy @oantolin We did the same in the recent MELPA addition marginalia, I think it is better not to require package.el.

**Comment by riscy** [comment]
Okay, I think that's fine -- the [coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html) also say "consider putting require statements inside the relevant functions rather than at the top-level".   My gut tells me this is preferable because I believe the autoload statement has a global effect -- people who use your package [may become accustomed](https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html) to being able to `(package-delete "xyz")` without an explicit load, but this is minor.  I don't consider this a blocker.

> I made them embark-action--%s now

Thanks for accommodating! :)

**Comment by oantolin** [comment]
The coding conventions also say, right after that, "Or use autoload statements to load the extra library when needed. This way people who don’t use those aspects of your file do not need to load the extra library." But I think `require` inside the functions (1) looks prettier, and (2) avoids the global effect you mention. I think I'll do that instead, thanks!

**Comment by oantolin** [comment]
Mmh. The autoload version satisfies the byte-compiler, while the version with `require` inside the functions does not. I think I'm leaving it with autoloads for now.

**Comment by oantolin** [comment]
Thank you very much for the review and for merging, @riscy!

**Comment by riscy** [comment]
Yeah, that's fine too.  You can pacify the byte-compiler by forward-declaring (`declare-function`, `defvar`) if you're inclined.

**Pull request merged**
