### PR TITLE
Add OpenFOAM recipe.

### PR DESCRIPTION
**Pull request by ralph-schleicher**
### Brief summary of what the package does

Major modes for editing OpenFOAM data files and C++ code.

### Direct link to the package repository

https://github.com/ralph-schleicher/emacs-openfoam

### Your association with the package

I'm the package author and maintainer.

### Relevant communications with the upstream package maintainer

N/A

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.   There's a quick first pass below but I also notice this is introducing an alias `∇-mode` outside of its namespace which we usually push back against.  I'd suggest that line is a good candidate for inclusion in the `;;; Commentary`.

### openfoam.el ###

byte-compile (using Emacs 27.1):
```
openfoam.el:256:22:Warning: `make-variable-buffer-local' not called at
    toplevel
In end of data:
openfoam.el:875:1:Warning: the function `openfoam-c++-minor-mode' is not known
    to be defined.
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
openfoam.el:123: Argument `method' should appear (as METHOD) in the doc string
Warning (emacs): 
openfoam.el:570: Disambiguate system-name by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
openfoam.el:700: First line is not a complete sentence
Warning (emacs): 
openfoam.el:710: Argument `here' should appear (as HERE) in the doc string
```

package-lint (using version 20210326.241):
```
3 issues found:
133:4: warning: Closing parens should not be wrapped onto new lines.
202:2: warning: Closing parens should not be wrapped onto new lines.
537:0: error: Aliases should start with the package's prefix "openfoam".
```

Other [lints](https://github.com/riscy/melpazoid):
- openfoam.el#L537: It's safer to sharp-quote function names; use `#'`
- openfoam.el#L218: This double negation can be collapsed (`not` aliases `null`)
- openfoam.el#L738: This double negation can be collapsed (`not` aliases `null`)
- openfoam.el#L749: This double negation can be collapsed (`not` aliases `null`)
- openfoam.el#L807: This double negation can be collapsed (`not` aliases `null`)

### Package ###

- Prefer the default recipe or use `:defaults`, if possible.
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- openfoam-pkg.el -- consider removing this file; MELPA will create one based on the contents of openfoam.el if you add a `Package-Requires` like to your frontmatter

**Comment by ralph-schleicher** [comment]
The most controversal point is probably the ∇-mode alias. So let's elaborate on that first.

Con:
* It violates the package prefix rule.

Pro:
* The Emacs coding standards permit deviation from the package prefix convention under certain conditions. For example, it is acceptable to provide ‘foo-game’ and ‘play-foo’ as entry points for the user if Emacs would use ‘play-’ as the command prefix for all games.
* It is the Emacs convention to enter a major mode with a user command ending with ‘-mode’.
* The nabla operator is the logo of OpenFOAM so it is natural to associate ∇ with OpenFOAM. This is especially true for the OpenFOAM community. Thus, Emacs should honor this and provide both names as entry points for the user.
* There is no other free software that is either called nabla or uses the nabla operrator as it's logo. We harm no one here.
* It's damm cool.

Thus, there are good reasons to accept the ∇-mode command. Look at it as a micro-package on top of the OpenFOAM package.

Now to the rest.

* The byte-compile warnings are due to the fact that Polymode support is an optional feature loaded at run time. These warnings can be ignored.
* The checkdoc warnings are not relevant and can be ignored.
* The package-lint messages are all non-issues.

I really would appreciate it if you don't insist on fixing all these non-issues.

**Comment by riscy** [comment]
It'll probably be until next weekend when I have a chance to look again, but hopefully those semi-canned responses give some rationale --

It may feel inconvenient, but a simple and fair way to prevent namespace collisions across MELPA (and hopefully elsewhere) is to ask that the package, variable names, and function names all use the same prefix.  In very rare cases I would make exceptions to this rule (e.g. backward compatibility with a package predating this rule) -- and `package-lint` has some of these exceptions built into it.

(In this case, what happens if someone wants to do the same for [nabla lang](http://nabla-lang.org/)?)

I know I seem pedantic, but I have good reasons for asking authors to cleanly solve all the warnings and errors indicated in the checklist:
- they're a crude but effective quality control check
- you won't get used to disregarding them out of hand, which could cause you to miss real issues in the future
- in the case of byte-compile warnings and errors, you spare users being distracted by them during installation
- my being strict about them means I spend less bandwidth trying to negotiate grey areas in a fair and consistent way

**Comment by ralph-schleicher** [comment]
I've fixed all the byte-compile warnings and the reasonable checkdoc warnings.
Also removed openfoam-pkg.el.

**Comment by riscy** [comment]
Thank you very much -- here's the latest salient issues:

byte-compile (using Emacs 27.1):
```
openfoam.el:268:22:Warning: `make-variable-buffer-local' not called at
    toplevel
```

As well as:
- openfoam.el#L552: It's safer to sharp-quote function names; use `#'` (minor)
- openfoam.el#L7: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by ralph-schleicher** [comment]
These issues should be fixed now. The byte-compile warning was a nasty beast; it is not displayed in batch mode and there is no way to fix it except for disabling the warning via a file local variable.

Happy Easter.

**Comment by riscy** [comment]
Thanks for getting that all out of the way.  I'm taking a closer look at the code now.

I think what you've done to resolve the byte-compile warning (disabling it) is reasonable in this situation.

I notice that you have a package-requires on polymode (i.e. a strict dependency).  Maybe you don't intend for that dependency to be strict, in which case you should remove it from your package-requires (and you can stop reading this paragraph).  But if you do intend for it to be strict, you could just explicitly require it and a lot of the code spent managing polymode as a soft dependency would disappear, and the call to `define-polymode` in `openfoam-poly-setup` could happen at the top level which would fix the aforementioned byte-compile warning.

**Comment by ralph-schleicher** [comment]
The strict dependency on Polymode is justified if the package is installed via MELPA, since Polymode is also available in MELPA.  However, if a user installs the package manually, then she should not be forced to install Polymode as well. Beside that I see MELPA only as an intermediate step to find a greater user base. Once the package is mature I will contribute it to Emacs anyway. But then I do not want to backport it so that it can be used without Polymode. Additionally, Polymode itself still has some rough corners and I'm not sure which multiple major mode solution will be the final one. So, MMM support should be a run-time option and not a compile-time option. At least for the moment.

**Comment by riscy** [comment]
>  However, if a user installs the package manually, then she should not be forced to install Polymode as well.

This feels like it would be nice to offer to MELPA users as well -- generally we push for smaller dependency lists.

**Comment by ralph-schleicher** [comment]
Done.

**Comment by purcell** [comment]
Nice package!

> The most controversal point is probably the ∇-mode alias

Agreed: there's no need for that alias, in the end. I can understand the aesthetic appeal, but users can trivially alias it their local config. All the actual definitions are consistently `openfoam-*`.

Looks good apart from that. `openfoam-shell` is quite a wild ride!

**Comment by ralph-schleicher** [comment]
I've removed the ∇-mode alias.
The package should be clean now.

**Comment by purcell** [comment]
Danke Ralph, herzlich willkommen bei MELPA. :tada:

**Pull request merged**
