### PR TITLE
Add recipe for semaphore

### PR DESCRIPTION
**Pull request by bendlas**
### Brief summary of what the package does

A semaphore based on two monotonic counters and a condition variable.

The condition variable enables it to interact with threads, while the two counters enable it to support a lifetime-count of acquisitions.

### Direct link to the package repository

https://github.com/webnf/semaphore.el

### Your association with the package

I'm the creator and maintainer

### Relevant communications with the upstream package maintainer

I expect the API to be totally stable, grow-only. It has been used in a real-world project.

Thanks to the checklist and package-lint, I last-minute renamed `make-semaphore` to `semaphore-create`. Will be happy about further feedback before I tag the first version, since this package assumes a pretty important provision in elisp land.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by bendlas** [comment]
cc https://github.com/chuntaro/emacs-promise/issues/7

**Comment by purcell** [comment]
Thanks! I suspect this should be a pair of recipes, right? One recipe would specify `:files ("semaphore.el")` and the other recipe would include only `semaphore-promise.el`: `semaphore-promise.el` would then declare package dependencies on `sempahore` and `promise`. Alternatively (and perhaps less ideally) you'd need to declare a package dependency on `promise` in `semaphore.el`, and then leave this as one recipe.

Code itself looks good, but please remove the redundant "semaphore: " string at the beginning of the package description [here](https://github.com/webnf/semaphore.el/blob/d3816842c5ec7ae4634425ccec1f87cd687f53c4/semaphore.el#L1) to keep things tidy.

**Comment by bendlas** [comment]
> I suspect this should be a pair of recipes, right?

The intention was for `promise` to be a kind of optional dependency, as proposed [here](https://github.com/cask/cask/issues/334), but I can also make two recipes. Those can be hosted in the same repo, right?

**Comment by purcell** [comment]
> The intention was for `promise` to be a kind of optional dependency, as proposed [here](https://github.com/cask/cask/issues/334), but I can also make two recipes.

Yes, I think that's ideal. Much better to avoid optional dependencies!

> Those can be hosted in the same repo, right?

Yes, and you can use `:files` in the recipe to specify which file goes in each recipe.

**Comment by purcell** [comment]
Ping! :-)

**Comment by bendlas** [comment]
Is it alright like [this](https://github.com/webnf/semaphore.el/blob/3912621594d3efb4ea4447e14927576db2a534ca/semaphore-promise.el#L10)?

**Comment by riscy** [comment]
That looks right to me.  Let me bump this up the queue --

[/elisp/semaphore-promise.el]
-------------------------------------------------------------------------------
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd>:
```
Warning (emacs): 
semaphore-promise.el:40: Second line should not have indentation
Warning (emacs): 
semaphore-promise.el:40: First line is not a complete sentence
Warning (emacs): 
semaphore-promise.el:40: Argument `semaphore' should appear (as SEMAPHORE) in the doc string
```

<kbd>M-x package-lint</kbd> (using version 20190606.2210):
```
1 issue found:

1:1: warning: The package summary should start with an uppercase letter or a digit.
```

<kbd>M-x byte-compile-file</kbd>:
```
semaphore-promise.el:55:7:Warning: `semaphore' is an obsolete variable (as of
    25.1); use 'semaphore instead
semaphore-promise.el:59:30:Warning: `semaphore' is an obsolete variable (as of
    25.1); use 'semaphore instead
semaphore-promise.el:62:29:Warning: `semaphore' is an obsolete variable (as of
    25.1); use 'semaphore instead
```
(These are interesting.  I am able to "fix" these by changing the variable's name, but I haven't dug any deeper than that.)

<kbd>M-x check-declare-file</kbd> (not on the MELPA checklist):
No issues! 🎉

Minor:
- 9: Prefer `https` over `http` (if possible)

-------------------------------------------------------------------------------
[/elisp/semaphore.el]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd>:
```
Warning (emacs): 
semaphore.el:53: First line is not a complete sentence
```

<kbd>M-x package-lint</kbd> (using version 20190606.2210):
No issues! 🎊

<kbd>M-x byte-compile-file</kbd>:
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (not on the MELPA checklist):
No issues! 🎉

Minor:
- 9: Prefer `https` over `http` (if possible)

**Comment by purcell** [comment]
Thanks, merged now - sorry about the slow turnaround.

**Pull request merged**
