### PR TITLE
Add recipe for semantic-thrift

### PR DESCRIPTION
**Pull request by jerryxgh**
Change-Id: I5411cb378195cbe2abd2ae628ddae5a0ff250058

### Brief summary of what the package does

With thrift-mode, semantic-thrift support semantic level jumping of thrift. It use semantic(emacs 28 builtin) to generate thrift parser, and provide semantic jumping ability.

### Direct link to the package repository

https://github.com/jerryxgh/semantic-thrift

### Your association with the package

maintainer, I'm the creator and maintainer of this package

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, this looks like a big contribution.  (Perhaps the `;;; Commentary` could be expanded with a little more context -- you could see semantic's own `;;; Commentary` and aim for a uniform level of detail.)  Quick first pass --

`semantic-thrift-wy.el` with checkdoc 0.6.2:
```
semantic-thrift-wy.el:588: Argument `include-literal' should appear (as INCLUDE-LITERAL) in the doc string
```

`semantic-thrift-wy.el` with package-lint 20230605.1550:
```
3 issues found:
7:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
539:2: warning: Closing parens should not be wrapped onto new lines.
587:0: error: "extract-include-id" doesn't start with package's prefix "semantic-thrift".
```

`semantic-thrift-wy.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- semantic-thrift-wy.el#L43: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
```

Package and license:
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to semantic-thrift.el
- There are two authors listed across the two source files, "bytedance" and "Guanghui Xu"; I'm just confirming that this discrepancy is deliberate, because only one of the files has license boilerplate

**Comment by jerryxgh** [comment]
Thank you very much for your comment, it seems that some improvement should be done. This is my plan:

**Comment by riscy** [comment]
Gotcha.  Good plan -- let me know when ready for another pass. :)

> 539:2: warning: Closing parens should not be wrapped onto new lines.

I wouldn't consider this a blocker if the code is auto-generated, so don't worry about that one.  But be on the lookout for things like out-of-namespace prefixes, and byte-compile warnings/errors.

**Comment by jerryxgh** [comment]
Hi riscy, the plan above has been accomplished, and there are no out-of-namespace prefixes, and byte-compile warnings/errors of `semantic-thrift-wy.el` now.

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
