### PR TITLE
Add cursor-in-brackets recipe

### PR DESCRIPTION
**Pull request by yascentur**
Please add a new recipe of cursor-in-brackets.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. You can use `define-globalized-minor-mode` instead of `define-global-minor-mode` to avoid the lambda there.

**Comment by yascentur** [comment]
Thanks for merging and reviewing.
According to describe-function in Emacs 24.5, define-global-minor-mode is an alias for \`define-globalized-minor-mode' in \`easy-mmode.el'.
It seems that the lambda cannot be avoided by using define-globalized-minor-mode instead of define-global-minor-mode.

**Comment by purcell** [comment]
Oh, really? Okay. In any case, as of Emacs 24,
```el
(lambda ()
    (cursor-in-brackets-mode t))
```
is equivalent to `'cursor-in-brackets-mode`, so you only need the former if you want to support Emacs < 24.

**Comment by yascentur** [comment]
OK. It is fixed.

**Pull request merged**
