### PR TITLE
Add validate-html.

### PR DESCRIPTION
**Pull request by arthurgleckler**
### Brief summary of what the package does

This file installs the command validate-html, which sends the
current buffer to the World Wide Web Consortium's HTML Validator
service and displays the results in a dedicated buffer in Compilation mode.  Use
standard Compilation commands like next-error to move through the
errors in the source buffer.

### Direct link to the package repository

https://github.com/arthurgleckler/validate-html

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by lassik** [comment]
This package depends on `seq`. Does `seq` need to be included in the `Package-Requires:` header?

**Comment by arthurgleckler** [comment]
No, because I depend on a late enough version of Emacs.  The package-lint package offered both as choices.

**Comment by lassik** [comment]
I tested this package on Emacs 27.1 and can confirm it works.

**Comment by lassik** [comment]
Tested using `docker run -it silex/emacs:25.1` that it works and byte-compiles without warnings on the minimum Emacs version listed in `Package-Requires`.

**Comment by riscy** [comment]
Thanks, this is excellent.

The only ask would be to use a LICENSE file that GitHub can detect.

Minor:
- Display the resuls -> results (+ "in a dedicated buffer...")

**Comment by arthurgleckler** [comment]
> Thanks, this is excellent.

Thank you.

> The only ask would be to use a LICENSE file that GitHub can detect.

Good point.  Added.

> * Display the resuls -> results (+ "in a dedicated buffer...")

I added the word "dedicated" in the comments and in the **Brief summary of what the package does** above.

**Pull request merged**
