### PR TITLE
Recipe: Add dogears

### PR DESCRIPTION
**Pull request by alphapapa**
### Brief summary of what the package does

This library automatically and smartly remembers where you’ve been, in and across buffers, and helps you quickly return to any of those places. It uses the Emacs bookmarks system internally (but without modifying the bookmarks-alist) to save and restore places with mode-specific functionality.

As usual, it’s configurable to suit each user, with regard to how often places are remembered, which ones, and for how long.

It uses standard Emacs completion, so it works with Helm, Ivy, Selectrum, Vertico, etc. For Helm users, a helm-dogears-source is also provided in helm-dogears.el that can be used with any Helm command.

### Direct link to the package repository

https://github.com/alphapapa/dogears.el

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

I'll allow it.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them (I've yet to be fooled by this...but maybe someday...)

Thanks as always for your work on MELPA.

### CODE REVIEW

**Comment by alphapapa** [comment]
Before this gets merged, I'm considering renaming it to `dog-ears`, because of the visual ambiguity (is it `dog ears` or `do gears`?).  Feedback would be appreciated.  :)

**Comment by mattiasb** [comment]
How does this compare to [history-mode](https://github.com/tcw165/history) and [backward-forward-mode](https://github.com/Lenbok/emacs-backward-forward)?

**Comment by alphapapa** [comment]
@mattiasb I hadn't seen `backward-forward-mode`.  `history-mode` I saw in [gumshoe](https://github.com/Overdr0ne/gumshoe)'s readme recently.  

And as you can see from the list in its readme there are numerous "back/forward/where-was-i" tools that have been made for Emacs over the years.  In the Dogears readme, I've described how it works, its various commands, and its internal implementation, as well as shown screenshots of one of its primary features.  You can see that some of its features appear to be unique, like using the `bookmark` library to return to places whose buffers have been killed, having a sortable list of places visible in a separate buffer or a side window, and having a flexible, customizable system for determining what places are saved and when.

I don't plan to write a comprehensive, set-union/set-difference comparison of every such tool out there.  [I've done that sort of thing before](https://github.com/alphapapa/makem.sh#comparisons), and it takes a lot of time.  If you'd like to do that, I'll be glad to add it to the documentation.  Otherwise, I'd suggest picking one of the tools that strikes your fancy, and trying it out.  If you find something that works for you, enjoy it.

**Comment by riscy** [comment]
Thanks!

> I'm considering renaming it to dog-ears, because of the visual ambiguity

Personally I'd be fine with either; for what it's worth, the dictionary spells it [with a hyphen](https://www.merriam-webster.com/dictionary/dog-eared) if you're on the fence.

I do notice helm-dogears.el is included in the recipe which might not be deliberate?  Otherwise this is an easy merge.

**Comment by alphapapa** [comment]
Thanks for the feedback.  At this point, I think I'll leave the name as-is.

Whether to include the Helm file is a good question.  I already configured it to avoid byte-compile warnings for users who don't have Helm installed.  It's far too trivial to publish as a separate package, and I don't foresee that changing.  So it doesn't seem unreasonable to let the file be in the package, so users can just `require` it if they want to.  Alternatively, it could be omitted from the package, and then users who want it later would need to manually download the file and install it somewhere.

Given how small and trivial the file is, and as long as it doesn't cause any warnings, I'd lean toward leaving it included.  But I'll follow your guidance here.

**Comment by riscy** [comment]
Yep, that makes sense to me.  The only issue I see is namespace related, in that the package is also reserving `helm-dogears`.  E.g. there's the small risk someone could inadvertently/unscrupulously add a `helm-dogears` package without it being noticed in time.  I'd suggest renaming it to `dogears-helm` if we include it here, or creating a separate recipe (either in this PR or another which I'll keep an eye out for).

**Comment by alphapapa** [comment]
Okay, I guess I'll just bite the bullet and make a recipe for it.  I kind of hate to "spam" the packages list, but better than having a conflict someday, and it's more convenient for users than having to install the file manually.  I'll add it to this PR and repush...

**Comment by alphapapa** [comment]
@riscy I think that should do it.  Thanks for your help as always.

**Comment by riscy** [comment]
Sounds good -- and thanks for accommodating. :)

**Pull request merged**
