### PR TITLE
Add recipe for rom-party.el

### PR DESCRIPTION
**Pull request by LaurenceWarne**
### Brief summary of what the package does

A rewrite of https://jklm.fun/ 's bomb party in Emacs (there is a video demo in the README).

(Bomb party is a word game where you are given a two or three letter prompt, and you have to find a word which contains the given prompt as a substring). 

### Direct link to the package repository

https://github.com/LaurenceWarne/rom-party.el

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
Cool idea. I could see CRDT being used to implement a multiplayer mode down the line.

> ;; Note by default on first invocation, `rom-party' will download a
> ;; remote index file asynchronously and so may not start straight away.

Could you tell me more about the index file?
Is it necessary to compile/download it, or could things be reworked so that information is streamed in as needed?

**Comment by riscy** [comment]
Good feedback from @progfolio - from a metadata standpoint I also recommend adding the word "game" somewhere in your summary line (first line of the file).  As it is, I see a package-called "rom party" with a summary of "bomb party" and I didn't know what either of these were, of it that were a typo.  Maybe the summary line could be:

```
Rendition of the "Bomb Party" game
```
or *something* like that.

**Comment by LaurenceWarne** [comment]
Thank you both for the comments!

> Could you tell me more about the index file?
Is it necessary to compile/download it, or could things be reworked so that information is streamed in as needed?

In order to check that a user input is correct for a given prompt, I only need to check it's contained in the set of allowed words,  but I find it's useful to have a map of all prompts to all their valid words ahead of time for difficulty checking.  It's a bit rudimentary, but currently prompts can be filtered using the `rom-party-prompt-filter` which would take the prompt itself and list of allowed words.

For sure this indexing has been the main pain point of developing the package.  Initially instead of downloading an index, I would create it on first invocation of `rom-party`, but I found this took ~ 20s (not counting downloading the word sources as well), so I thought it might be faster to have users download an index ahead of time.  Compressing the index brings it down to ~10MB which hopefully shouldn't take too long to download.  Though if a user changes any of the default word sources, we don't download, and index manually.  Suggestions are more than welcome.   Perhaps the compressed index could be bundled with the package itself?

> Good feedback from @progfolio - from a metadata standpoint I also recommend adding the word "game" somewhere in your summary line (first line of the file). As it is, I see a package-called "rom party" with a summary of "bomb party" and I didn't know what either of these were, of it that were a typo. Maybe the summary line could be:

Thanks, should be done now.

**Comment by riscy** [comment]
Thanks @LaurenceWarne - I can tell you've given the index-file-download some thought. :)

I ran a quick flyspell to check some of the text that might go out to users.  Some (non-blocking) typos in the elisp file, fyi:
- containg -> containing
- `Times up` -> `Time's up`
- `frequences` -> `frequencies`

**Comment by LaurenceWarne** [comment]
> I ran a quick flyspell to check some of the text that might go out to users. Some (non-blocking) typos in the elisp file, fyi:
>
>   containg -> containing
>    Times up -> Time's up
>    frequences -> frequencies

Oh nice thanks!

> Thanks @LaurenceWarne - I can tell you've given the index-file-download some thought. :)

I wondered if you had any comment about the idea of including the index as part of the package itself using `:files`, or is that something you would generally discourage?

**Comment by progfolio** [comment]
> > I ran a quick flyspell to check some of the text that might go out to users. Some (non-blocking) typos in the elisp file, fyi:
> > containg -> containing
> > Times up -> Time's up
> > frequences -> frequencies
> 
> Oh nice thanks!
> 
> > Thanks @LaurenceWarne - I can tell you've given the index-file-download some thought. :)
> 
> I wondered if you had any comment about the idea of including the index as part of the package itself using `:files`, or is that something you would generally discourage?

I distribute word files in the wordel repository (which is available through MELPA):

https://github.com/progfolio/wordel/blob/main/words/wordle

So long as the size of the file isn't huge, I don't think it would be a problem.

**Comment by LaurenceWarne** [comment]
Cool, in that case I might put a PR together to add the compressed index to the recipe.

**Pull request merged**
