### PR TITLE
Add: halloweenie-themes recipe

### PR DESCRIPTION
**Pull request by gcentauri**
### Brief summary of what the package does

Halloween oriented color themes

### Direct link to the package repository

https://cicadas.surf/cgit/halloweenie-themes.git

### Your association with the package

Maintainer and contributor.

### Relevant communications with the upstream package maintainer

none needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

* No byte-compile errors 🎉 

`halloweenie-themes.el` with checkdoc (0.6.2)

```
No issues found
```

`halloweenie-theme.el` with checkdoc (0.6.2)

```
halloweenie-theme.el:0: The first line should be of the form: ";;; package --- Summary"
halloweenie-theme.el:0: You should have a section marked ";;; Commentary:"
halloweenie-theme.el:20: You should have a section marked ";;; Code:"
halloweenie-theme.el:72: The footer should be: (provide 'halloweenie-theme)\n;;; halloweenie-theme.el ends here
```

`pumpkin-spice-theme.el` with checkdoc (0.6.2)

```
pumpkin-spice-theme.el:0: The first line should be of the form: ";;; package --- Summary"
pumpkin-spice-theme.el:0: You should have a section marked ";;; Commentary:"
pumpkin-spice-theme.el:20: You should have a section marked ";;; Code:"
pumpkin-spice-theme.el:63: The footer should be: (provide 'pumpkin-spice-theme)\n;;; pumpkin-spice-theme.el ends here
```

`halloweenie-themes.el` with package-lint (20230905.629)

```
No issues found.
```

`halloweenie-theme.el` with package-lint (20230905.629)

```
1 issue found:

1:0: error: There is no `provide' form.
```

`pumpkin-spice-theme.el` with package-lint (20230905.629)

```
2 issues found:

1:0: error: There is no `provide' form.
62:0: warning: Closing parens should not be wrapped onto new lines.
```

Package and license:

* Add a LICENSE file to the repository
See: https://github.com/licensee/licensee

**Comment by gcentauri** [comment]
@jcs090218 - thanks for catching these! i wasn't sure how a multi-file package was meant to work but i think i've addressed the issues here

**Comment by jcs090218** [comment]
Normally, all `.el` files should live under the same namespace. Take a look at my package [eask](https://github.com/emacs-eask/eask); it contains tree files, and they all lived under `eask-` namespace. But I don't know if that is required or not. 🤔 

Anyway, you don't need to specify package metadata in every file. Only the package main file is needed.

**Comment by gcentauri** [comment]
Yeah I realized that later looking at `modus-themes`. I'll take another pass at pulling out the extra metadata in the other files.

Is it a problem to have two themes without using a namespace to group them?

I could just publish the two themes separately as well.

**Comment by gcentauri** [comment]
Package metadata has been removed from the individual theme files.

**Comment by jcs090218** [comment]
Let's wait for `@riscy` to review this! ;)

**Comment by riscy** [comment]
> Is it a problem to have two themes without using a namespace to group them?  I could just publish the two themes separately as well.

Yes, even for themes it's best to make sure that namespaces are in line.  (I think it would be quite easy for someone to propose e.g. a `pumpkin-spice-theme` package, and it would be nontrivial to uncover that the `halloweenie-themes` package is using that namespace.)

I think `package-lint` is not detecting this discrepancy because it doesn't recognize the `autothemer-deftheme` macro.

The WIP FAQ https://github.com/melpa/melpa/blob/4caa9a03cad40d24484fce27fcfcf75b1d08e814/FAQ.md (which I need to do something with) contains a guide on writing a package with multiple themes, but the naming can get awkward; publishing two separate themes makes good sense in this case.

**Comment by macrologist** [comment]
What about https://github.com/owainlewis/emacs-color-themes ? This is a counter example to the one-namespace rule. So it may be bad practice, but precedent shows that it is not disqualifyingly bad.

**Comment by riscy** [comment]
Thank you for accommodating!  These look good to go. :)

**Pull request merged**
