### PR TITLE
Return helm-words back

### PR DESCRIPTION
**Pull request by sergeyklay**
### Brief summary of what the package does

Customizable Helm extension for easy looking up words in various online/offline dictionaries and thesauri.

Refs:
- https://github.com/pronobis/helm-words/pull/2
- https://github.com/melpa/melpa/commit/cc53e7c

### Direct link to the package repository

https://github.com/pronobis/helm-words

### Your association with the package

I'm an enthusiastic user

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
From what I can tell, the package author ignored the issue for over 3 years, and then finally merged a patch without comment.

Is the author actually *maintaining* the package?  If the author is not really actively maintaining it, then it probably should not be in MELPA, especially since it depends on a package like Helm and various online services which are likely to break at any random moment.  Not every Emacs package needs to be in MELPA.

**Comment by sergeyklay** [comment]
Ok. Not a problem at all. Thank you for the feedback

**Comment by alphapapa** [comment]
@sergeyklay Please note that I'm not a MELPA staff member, so my opinion is not a decision, just my two cents.  :)

**Comment by sergeyklay** [comment]
@alphapapa In general, your arguments seemed convincing to me. So MELPA membership was not decisive for me.

**Pull request closed without merging**
