### PR TITLE
Add eldoc-box

### PR DESCRIPTION
**Pull request by casouri**
### Brief summary of what the package does

Make eldoc display document messages in childframe

### Direct link to the package repository

https://github.com/casouri/eldoc-box

### Your association with the package

Maintainer (wrote the package but copied code from lsp-ui, hence maintainer)

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings (except a minor one)
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by casouri** [comment]
Done, does it look ok?

**Comment by alphapapa** [comment]
That looks very cool!  I'd suggest taking the screenshot again with the child frame's background a bit lighter, though, because I had to look very closely to see where the child frame was.

One other thing, it would be helpful if you could clarify the differences between the two functions:

> eldoc-box-hover-mode
> Show documentation upon hover. Note that you need to enable ElDoc mode for this to work.

> eldoc-box-hover-at-point-mode
> This minor mode shows doc at point. Don’t try to enable both minor mode: you can only enable one in the same time.

They both have `hover` in their names, but only one's docstring says `hover`, so I'm not sure which does what.

Also, regarding:

> Don’t try to enable both minor mode: you can only enable one in the same time.

Why not add a check in the modes to disable the opposite mode, so the user can't do it wrong?

**Comment by casouri** [comment]
Thank you for taking your time.

I've changed the screenshot, updated the explanation of the two minor modes, and added safety code in minor mode definitions.

Does the screenshot look ok? It seems distinctive in my eyes but I'm not sure if it's the same for others.

**Comment by alphapapa** [comment]
Yes, the doc frame is easier to distinguish in the screenshot now.

**Comment by purcell** [comment]
Thanks for this, and for your patience. Couple of things stand out to me:

- The code is surprisingly complex, and I'm surprised you can't use something like `posframe` here. Is there a reason that's not possible?
- Lots of typos, e.g.: "childframw", "cildframe"

**Comment by casouri** [comment]
> The code is surprisingly complex

Can't deny it. The main reason is to fix edge cases here and there and try to play nice with eldoc, which is mainly designed for displaying stuff in the echo area. If you look at the [initial version](https://github.com/casouri/eldoc-box/tree/bfda87893d1835fce022b21c40b9fca934ee56f5), you can see it is indeed pretty simple. All the superfluous code boils down to 1) keep eldoc from hiding the childframe when it shouldn't, 2) hide the childframe when it should be hidden.

> I'm surprised you can't use something like posframe here. Is there a reason that's not possible?

Not really. It is just because lsp-ui doesn't use posframe. At first, I just want a `lsp-ui-doc` for eglot because eglot doesn't have one (and won't include one). So I went to `lsp-ui`, copied some code from it and modified the code to work with eldoc (because eglot only have an API through eldoc). It was initially named `eglot-doc`.

Then the author of eglot said it can be used with eldoc in general, instead of eglot. It's a good idea so I changed the name to `eldoc-box` and removed eglot dependency.

The code I copied from `lsp-ui` never had any problem so I didn't bother to replace it with posframe.

> Lots of typos, e.g.: "childframw", "cildframe"

Sorry for that, "childframe" is marked wrong itself in flyspell so I didn't pay much attention to it. They should be fixed in the latest update.

Hope I answered your questions.

**Comment by purcell** [comment]
Makes sense, merged now: thanks for your patience, and sorry for the slow turnaround!

**Pull request merged**
