### PR TITLE
Add recipe for package: pkg-overview

### PR DESCRIPTION
**Pull request by Boruch-Baum**
### Brief summary of what the package does

This package parses an elisp file's comments, definitions,
docstrings, and other documentation into a hierarchical `org-mode`
buffer. It is intended to facilitate familiarization with a file's
contents and organization / structure. The viewer can quickly swoop
in and out and across the file structure using standard `org-mode`
commands and keybindings.

### Direct link to the package repository

https://github.com/Boruch-Baum/emacs-pkg-overview

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

N/A. However, sort-of related: The lisp file include a link to the beginning of a relevant thread on the `emacs-devel` mailing list (2020-10-15), and a summary of the current state of that conversation.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
> Delete pointback
> Merge branch 'melpa:master' into master
> Merge branch 'melpa:master' into master
> Create cursor-flash
> Delete cursor-flash
> Merge branch 'melpa:master' into master
> Create pkg-overview

That's quite noisy and unfortunately all your recipe pull-requests look like this.

When you create a pull-request to add a recipe for a new package, then please do it like this:

1. Checkout out the `master` branch
2. Pull
3. Create and checkout a new feature branch [the name of the package could serve as the branch name]
4. Add a single commit which adds the recipe [`Add recipe for "<name>"` would be a good commit message]

If it turns out that something was wrong with the recipe, then amend the correction to the original commit and the force-push. If you want/need to sync your feature branch with `master`, then do so by rebasing, not by merging `master` into your feature branch.

Thanks!

**Comment by Boruch-Baum** [comment]
> That's quite noisy and unfortunately all your recipe pull-requests look like this.

I've noticed, and it bothers me, too.

> When you create a pull-request to add a recipe for a new package, then please do it like this:
> ...

Most of the issue seems to be how (or that) I'm "re-using" the same github repository for subsequent PR's. That accounts for all the merges, which are when I'm updating using the github interface to "fetch upstream" into the master branch of my github copy from melpa/melpa. Is there an alternative to having to perform the github process of totally deleting my fork of the repository and then re-creating another one?

I don't grok your suggestion about re-basing as an alternative to merging, because the github interface doesn't seem to offer that. Also, the merges that are reflected in the commit message that you see are not into any of my feature branches, they're into my copy of the melpa master branch, as performed by the github interface using the button labeled "fetch upstream"

**Comment by alphapapa** [comment]
> I don't grok your suggestion about re-basing as an alternative to merging, because the github interface doesn't seem to offer that.

You should probably use Magit for that.  It's like 2 keypresses.

**Comment by alphapapa** [comment]
Also, I've already written some code to do this sort of thing.  See https://github.com/alphapapa/unpackaged.el#convert-elisp-to-org-format

**Comment by Boruch-Baum** [comment]
On 2021-07-29 17:11, alphapapa wrote:
>      I don't grok your suggestion about re-basing as an alternative to
>      merging, because the github interface doesn't seem to offer that.
>
>    You should probably use Magit for that. It's like 2 keypresses.

OK then. I was trying to avoid having any local git instance of melpa
repository, since it's large, and the single action of adding a recipe
is so simple using the github browser interface (add a file, paste), but
the accumulating objections to the side-effects have swayed me. So the
following is my TODO after this PR is processed?

1) Delete github repository of my melpa fork

2) For next recipe, use whatever combination of magit/forge/hub works, probably
   performing just a shallow clone of only the master branch,


--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
On 2021-07-29 17:12, alphapapa wrote:
>    Also, I've already written some code to do this sort of thing. See
>    [1]https://github.com/alphapapa/unpackaged.el#convert-elisp-to-org-form
>    at

I just took a look at your code and here are what I see as the differences:

1) Mine presents comment lines. Thus, mine will present any/all blocks
   of documentation that may appear within the elisp file outside of
   docstrings. This will most commonly include the commentary and other
   documentation usually placed at the beginning of an elisp file before
   any of the code.

2) Mine presents output in the sequence that exists in the elisp file.
   IIUC, your code forces a rigid presentation of first command
   docstrings and then function docstrings. This speaks to my design
   goal of familiarizing a reader with the layout / structure /
   organization of the elisp file, as its author intended.

3) Mine presents output for *all* types of definitions, but if I'm reading
   your code correctly, yours only presents documentation for commands
   and functions, not for defcustoms, etc.

4) Mine recognizes and operates on lines beginning with three
   semi-colons, treating them as org-mode headings to improve
   understanding of the file's structure / layout.

5) Mine is simpler, shorter, and depends only on org-mode.

In the "wild", authors and project choose or evolve over time to
organize their elisp in many different ways that you might not expect,
and that layout can help a reader understand and navigate the code-base.
For example, if you have a copy of the emacs-w3m package, try my
pkg-overview on file w3m.el (~12k lines).

--
hkp://keys.gnupg.net CA45 09B5 5351 7C11 A9D1 7286 0036 9E45 1595 8BC0

**Comment by alphapapa** [comment]
> So the following is my TODO after this PR is processed? 1) Delete github repository of my melpa fork

No, just use Magit to push to your fork.

**Comment by Boruch-Baum** [comment]
Also, if what I said about your code is correct, try applying both to
the dired-aux.el file, part of emacs core.

Related emacs bug report thread:
  https://debbugs.gnu.org/cgi/bugreport.cgi?bug=47957

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
On 2021-07-29 21:23, alphapapa wrote:
>      So the following is my TODO after this PR is processed? 1) Delete
>      github repository of my melpa fork
>
>    No, just use Magit to push to your fork.

A few questions, then:

1) How can I use magit without a local copy of the repo?

2) How will that remove all prior, existing 'noise' commits that Jonas
   listed?

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by alphapapa** [comment]
> 1) How can I use magit without a local copy of the repo?

You can't.  That's not how git works.  A local checkout of the repo isn't that big; unless your computer is something like 25 years old, the disk space shouldn't be an issue.

**Comment by tarsius** [comment]
I don't consider Github a sufficient interface for doing version control. I strongly recommend you get a local copy of the repository to work on using Magit and other tools. There is nothing wrong with this approach unless your only local persistent storage is a floppy disc.

If you insist on using Github, then the only work flow that doesn't result in a huge mess is to delete and reclone the repository for every pull-request, which of course means you can only have one pull-request at a time. I would consider such a workflow very silly and its bad for the environment. You need to reclone because Github doesn't even support pulling -- only one of the many reason why Github is completely unsuitable for doing version control.

**Comment by Boruch-Baum** [comment]
On 2021-07-30 01:36, Jonas Bernoulli wrote:
>    I don't consider Github a sufficient interface for doing version
>    ...

Ya. I already conceded the point a few emails earlier in the thread.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
I'd welcome feedback about how to implement a suggestion of Stefan Kangas over on `emacs-devel` how to better represent autoload functions. What I'm thinking might work visually would be to convert
```
;;;###autoload
(defun pkg-overview (file)
```
to something like:
```
*** defun-autoload  pkg-overview (file)
```
or:
```
*** def-autoload  pkg-overview (file)
```

**Comment by tarsius** [comment]
As a tag maybe?

```
*** defun pkg-overview (file)                                   :autoload:
```

**Comment by Boruch-Baum** [comment]
On 2021-08-01 11:28, Jonas Bernoulli wrote:
>    As a tag maybe?
> *** defun pkg-overview (file)                                   :autoload:

That looks very nice. Great idea, and there's already provision in org
mode to re-align all tags in a buffer...

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
I've pushed six commits that add functionality. On my side, the result
byte compiles cleanly and passes package-lint. The only complaint from
check-doc is:

*** pkg-overview.el: checkdoc-package-keywords V 0.6.2
pkg-overview.el:10: Unrecognized keywords: docs help lisp maint outlines
tools

But all those keywords do exist in my emacs version (27.1) of variable
finder-known-keywords.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
Thanks for this, everything checks out on my end. :)  I'll squash and merge wrt the discussion above.

**Comment by Boruch-Baum** [comment]
On 2021-08-07 13:36, Chris Rayner wrote:
>    Thanks for this, everything checks out on my end. :) I'll squash and
>    merge wrt the discussion above.

Thank you. And I'll do my part in the future to avoid any similar drama.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Pull request merged**
