### PR TITLE
Add lab recipe

### PR DESCRIPTION
**Pull request by isamert**
### Brief summary of what the package does

A package that provides a simple integration with GitLab (managed or self-hosted).

### Direct link to the package repository

https://github.com/isamert/lab.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
I get the following error when installing:

```emacs-lisp
⛔ Warning (emacs): Error loading "lab" autoloads: (void-function defmemoize)
```

Which is due to autoloading this form:

```emacs-lisp
;;;###autoload
(defmemoize lab-get-all-owned-projects ()
  "Get all projects owned by you."
  (lab--request
   "projects"
   :owned 'true
   :%collect-all? t))
```

`defmemoize` itself is not autoloaded.

**Comment by riscy** [comment]
Thanks for this.  Quick first pass from my end --

I think you are aware of `gitlab` (https://melpa.org/#/gitlab) hence naming this `lab`, but can you comment on the differences and/or need for a separate gitlab interface?

`lab.el` with checkdoc 0.6.2:
```
lab.el:190: All variables and subroutines might as well have a documentation string
lab.el:220: All variables and subroutines might as well have a documentation string
lab.el:309: All variables and subroutines might as well have a documentation string
lab.el:314: All variables and subroutines might as well have a documentation string
lab.el:562: All variables and subroutines might as well have a documentation string
lab.el:936: All variables and subroutines might as well have a documentation string
lab.el:991: All variables and subroutines might as well have a documentation string
lab.el:1013: All variables and subroutines might as well have a documentation string
lab.el:1032: All variables and subroutines might as well have a documentation string
lab.el:1035: All variables and subroutines might as well have a documentation string
lab.el:1043: All variables and subroutines might as well have a documentation string
lab.el:1052: All variables and subroutines might as well have a documentation string
lab.el:1061: All variables and subroutines might as well have a documentation string
lab.el:1066: All variables and subroutines might as well have a documentation string
lab.el:1071: All variables and subroutines might as well have a documentation string
lab.el:1077: All variables and subroutines might as well have a documentation string
lab.el:1083: All variables and subroutines might as well have a documentation string
lab.el:1100: All variables and subroutines might as well have a documentation string
lab.el:1104: All variables and subroutines might as well have a documentation string
```
FYI; undocumented private functions are within reason imo.

`lab.el` with package-lint 20230315.1052:
```
1 issue found:
780:67: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
```

`#'load`-check on each file:
```
Loading lab.el
  lab.el:Error: Emacs 28.1:
  (void-variable embark-keymap-alist)
```

**Comment by isamert** [comment]
> I think you are aware of gitlab (https://melpa.org/#/gitlab) hence naming this lab, but can you comment on the differences and/or need for a separate gitlab interface?

I am aware but haven't used it. The main difference is the package `gitlab` is only an elisp wrapper for GitLab API. It provides some user-level functionality by gitlab-avy and gitlab-helm files but they are only limited to listing projects and issues. lab.el offers more comprehensive user level functionality, which I outlined in the [README](https://github.com/isamert/lab.el#functionality-summary). It also provides a helper function to interact with GitLab's API but it's only one function, instead of exposing every endpoint as a separate function as gitlab package does. I also have a comparison with `forge` at the end of the README. I can also add this comparison (with a little bit more detail) later.

> FYI; undocumented private functions are within reason imo.

Yeah, these errors are generated by private functions only.

> lab.el with package-lint 20230315.1052:
> > 1 issue found:
> > 780:67: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)

Whoops, I overlooked this one I guess. Fixed it.

> #'load-check on each file:
> Loading lab.el
>   lab.el:Error: Emacs 28.1:
>   (void-variable embark-keymap-alist)

Not quite sure about this one, I have this line that's probably causing the issue:

```
(defvar embark-keymap-alist)
```

which is just there to satisfy compiler. lab.el has optional embark support. I also used similar lines on other projects and haven't gotten this error. Maybe I'm missing something?

> I get the following error when installing:
> > ⛔ Warning (emacs): Error loading "lab" autoloads: (void-function defmemoize)

Thanks for reporting! I removed the autoload cookie for this function, I guess it does not need one really.

**Comment by riscy** [comment]
> Not quite sure about this one, I have this line that's probably causing the issue:

You have a top-level form `(lab--define-actions-for project ...` --  I think this is because Emacs attempts to expand/evaluate macros before it gets to anything else.  As a result I believe this is the result of a [wrong time](https://www.gnu.org/software/emacs/manual/html_node/elisp/Problems-with-Macros.html#Problems-with-Macros) bug in the code.

**Comment by isamert** [comment]
> >Not quite sure about this one, I have this line that's probably causing the issue:
>
> You have a top-level form `(lab--define-actions-for project ...` -- I think this is because Emacs attempts to expand/evaluate macros before it gets to anything else. As a result I believe this is the result of a [wrong time](https://www.gnu.org/software/emacs/manual/html_node/elisp/Problems-with-Macros.html#Problems-with-Macros) bug in the code.

Hi @riscy! Thanks for the pointers. I don't think it's a case of _wrong time_. Because the evaluation during the macro expansion do not reference `embark-keymap-alist`, only the expanded code references it. But while going through the code for the mentioned macro I realized there is another bug related to embark support and fixed it.

I tried running `melpazoid` on the package but didn't get this warning, searched for `load-check` and haven't find anything related to it. Where can I find the `load-check` function/macro so that I can also test it in my local. Maybe it's some false positive?

**Comment by riscy** [comment]
You're correct that this isn't a wrong-time issue with the macro itself - rather that the macro is being called at load time.

> I tried running melpazoid on the package but didn't get this warning, searched for load-check and haven't find anything related to it. Where can I find the load-check function/macro so that I can also test it in my local? Maybe it's some false positive?

Sure - that code is [here](https://github.com/riscy/melpazoid/blob/cad60971ae00fcd8d5d6e8f32cfb79d0ebdccb40/melpazoid/melpazoid.el#L410C4-L416); it's just running "load" on the file.

If I let the error spool out a bit:
```elisp
(void-variable embark-keymap-alist)
  (member '(lab-project . lab--embark-keymap-for-project) embark-keymap-alist)
  (if (member '(lab-project . lab--embark-keymap-for-project) embark-keymap-alist) embark-keymap-alist (setq embark-keymap-alist (cons '(lab-project . lab--embark-keymap-for-project) embark-keymap-alist)))
  eval-buffer(#<buffer  *load*-402835> nil "/workspace/pkg/lab.el" nil t)  ; Reading at buffer position 20390
  load-with-code-conversion("/workspace/pkg/lab.el" "/workspace/pkg/lab.el" nil t)
  load("/workspace/pkg/lab.el" nil t t)
```
The variable `embark-keymap-alist` doesn't exist at the time the `lab--define-actions-for` macro is being executed.  (The defvar you have does give a hint to the *compiler*, but doesn't actually make the variable non-void.)  I wonder - are you checking the code on an instance of Emacs that already has `embark` loaded in?

**Comment by isamert** [comment]
> The variable embark-keymap-alist doesn't exist at the time the lab--define-actions-for macro is being executed. (The defvar you have does give a hint to the compiler, but doesn't actually make the variable **non-void**.)

Oh, now I realized the problem. Thanks for detailed explanation!

> I realized there is another bug related to embark support and fixed it.

[This should fix the issue](https://github.com/isamert/lab.el/commit/3e33e532aea48ffadde4e4e48efd26523d362a0d). I wasn't thinking in terms of variable being void, I was thinking if it was defined or not but the problem is, as you said, it was being void at the time of evaluation. I simply moved the call to `embark-keymap-alist` under `(with-eval-after-load 'embark ...)`. Sorry for being a burden and thanks again for your detailed response!

**Comment by riscy** [comment]
Looks good to merge.  Thanks for your patience. :)

**Pull request merged**
