### PR TITLE
Add oauth2-request recipe

### PR DESCRIPTION
**Pull request by conao3**
### Brief summary of what the package does

OAuth2 request package interface.

### Direct link to the package repository

https://github.com/conao3/oauth2-request.el

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thank you, checklist look great.  I had a quick search around and I wonder if this functionality could be implemented through or supported by https://github.com/ccrusius/auth-source-xoauth2 -- but let me know if I'm way off base.

**Comment by conao3** [comment]
Wow, I cannot know the package but I notice this in the commentary section.
```
;; Adds XOAuth2 authentication capabilities to auth-source.
```
Presumably, this is to add xoauth2 support to auth-source. (literally)
I'm adding oauth2 token refresh before request package request, which has a different purpose.


Also, I am concerned about the wording.
```
;; Some code is basically the same as code in the external
;; `request.el' and `oauth2.el' packages.
```
I prefer to re-develop the wheel, but I know that it is better to use what our predecessors have made, especially when it comes to security.

**Comment by riscy** [comment]
I see now.  Thanks.  Minor, but I wonder if `(error "Don't specify Authorization slot")` could be rephrased to `(error "Don't specify an Authorization header")`; perhaps it should also be softened to a `user-error`, but I'll leave that up to you.

**Comment by conao3** [comment]
OK, thanks!

**Pull request merged**
