### PR TITLE
Recipe for sunburn-theme

### PR DESCRIPTION
**Pull request by mvarela**
## Brief summary of what the package does

A low-contrast theme derived from Zenburn

## Direct link to the package repository

https://github.com/mvarela/Sunburn-Theme/

## Your association with the package

Maintainer

## Relevant communications with the upstream package maintainer

None needed.

## Checklist

Please confirm with x:

 

- [x] The package is released under a GPL-Compatible Free Software License.
- [x]   I've read CONTRIBUTING.md
- [x]    I've used the latest version of package-lint to check for packaging issues, and addressed its feedback
- [x]   My elisp byte-compiles cleanly
- [x]    M-x checkdoc is happy with my docstrings
- [x]    I've built and installed the package using the instructions in CONTRIBUTING.md

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Looks good - I sent you some little fixes in https://github.com/mvarela/Sunburn-Theme/pull/2. You might also like to add a definition for the new `line-number` and `line-number-current-line` faces that are replacing `linum` in the latest Emacs version.

**Comment by mvarela** [comment]
Thanks Steve! I've merged your fixes, added the new faces to the theme, and tested them on the pre-release.

**Comment by purcell** [comment]
Great, added - welcome to MELPA!

**Comment by purcell** [comment]
P.S. the theme looks really nice.

**Comment by mvarela** [comment]
Thanks!

**Pull request merged**
