### PR TITLE
Add recipe for roc-mode

### PR DESCRIPTION
**Pull request by AjaiKN**
### Brief summary of what the package does

A major mode for the Roc programming language.

### Direct link to the package repository

https://gitlab.com/tad-lispy/roc-mode

### Your association with the package

I'm one of the maintainers (along with tad-lispy).

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

Note that there's another open pull request (#8953) that adds a different package called `roc-ts-mode`. See [my comment there](https://github.com/melpa/melpa/pull/8953#issuecomment-2282905381) for why I opened a new one.

This major mode does use treesit as well,  so I'm not sure whether it would be better to rename this package to `roc-ts-mode`.

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

> This major mode does use treesit as well, so I'm not sure whether it would be better to rename this package to roc-ts-mode.

Good catch - based on discussions I've seen on emacs-devel, this is the standard when it's a `ts`-only mode.

`roc-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- roc-mode.el#L377: Could this `point`/`point-min` comparison use `bobp`?
```

`roc-repl.el` with package-lint 20240507.1722 and `package-lint-main-file` = "roc-mode.el":
```
1 issue found:
86:0: error: Aliases should start with the package's prefix "roc".
```
I think this particular one is minor in the scheme of things and *very* commonly violated (albeit typically among the Emacs builtins), but I'd lean toward staying in the namespace.

Extremely minor, but these files have stub descriptions and Commentary:
- roc-cli.el: Description
- roc-repl.el: Description
- roc-start.el: Description

**Comment by AjaiKN** [comment]
> > This major mode does use treesit as well, so I'm not sure whether it would be better to rename this package to r`oc-ts-mode`.

> Good catch - based on discussions I've seen on emacs-devel, this is the standard when it's a `ts`-only mode.

Do you have any suggestions about how to go about that renaming? Would it be best to rename the package and all the functions to use the `roc-ts-` prefix? I'm a little conflicted about whether it makes sense to rename functions/files like `roc-repl` and `roc-build`, since they're not really treesit-related.

I've addressed the other issues you mentioned:

- Changed `point-min` comparison to `bobp`: https://gitlab.com/tad-lispy/roc-mode/-/commit/d77b20263705b6910ae31170ae4e01fa441a6d9f
- Removed `run-roc` alias: https://gitlab.com/tad-lispy/roc-mode/-/commit/08e36a6465881e7b6e373e19780cad7931691a6d
- Replaced stub descriptions and commentary: https://gitlab.com/tad-lispy/roc-mode/-/commit/1d7e44472f6f2ae0cecb76d024f0a42ff45eb068

Thanks for the help!

**Comment by meedstrom** [comment]
> Would it be best to rename the package and all the functions to use the roc-ts- prefix?

I'm not a Melpa maintainer, but as I understand it yes, that would fit standard practice.  If one day you extend the package to also work without tree-sitter, then you can always rename the package back, as well as rename back those things you mentioned, `roc-repl` and `roc-build`, keeping only the tree-sitter stuff in a subpackage "roc-ts-mode.el".  But if you never intend to do that because tree-sitter is just better, then why bother? :)

I suppose it is also a possibility for the package to be called "roc.el" and which ships only a `roc-ts-mode` major mode and no `roc-mode`.  That'd kinda cramp someone else's style if they wanted to make a roc mode though, they'd be forced to call it roc2-mode.

**Comment by AjaiKN** [comment]
The renaming is done! @riscy

And thanks for the advice @meedstrom!

**Comment by riscy** [comment]
Thank you, and thank you @meedstrom for the naming suggestion - strongly agree here.

@AjaiKN, welcome to MELPA! :)

**Pull request merged**
