### PR TITLE
Add recipe for sq

### PR DESCRIPTION
**Pull request by dorleosterode**
### Brief summary of what the package does

Provides convenient functions and key bindings to inspect OpenPGP
data using sq, Sequoia PGP's command line frontend.  Currently,
this is primarily useful for OpenPGP developers.

### Direct link to the package repository

https://gitlab.com/sequoia-pgp/sqel

### Your association with the package

I'm part of the sequoia ecosystem.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
  - The author is aware of problems with the docstrings.
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I see your note re: checkdoc, but it's something we ask all authors to take a look at equally -- hence I'm including them below.  If you have any questions about how to massage certain stubborn docstrings to fit, let me know.

`sq.el` with byte-compile using Emacs 28.1:
```
sq.el:59:4: Warning: Unused lexical argument `b'
sq.el:59:4: Warning: Unused lexical argument `e'
```

`sq.el` with checkdoc 0.6.2:
```
sq.el:43: First line is not a complete sentence
sq.el:43: Argument `arguments' should appear (as ARGUMENTS) in the doc string
sq.el:56: First line is not a complete sentence
sq.el:56: Argument `arguments' should appear (as ARGUMENTS) in the doc string
sq.el:63: First line is not a complete sentence
sq.el:63: Argument `b' should appear (as B) in the doc string
sq.el:75: First line is not a complete sentence
sq.el:75: Argument `b' should appear (as B) in the doc string
sq.el:88: First line is not a complete sentence
sq.el:88: Argument `b' should appear (as B) in the doc string
sq.el:101: First line is not a complete sentence
sq.el:101: Argument `b' should appear (as B) in the doc string
sq.el:109: First line is not a complete sentence
sq.el:113: Keycode C-c embedded in doc string.  Use \\<mapvar> & \\[command] instead
sq.el:109: Argument `prefix' should appear (as PREFIX) in the doc string
```

`sq.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- sq.el#L49: It's safer to sharp-quote function names; use `#'`
- sq.el#L116: Don't set global bindings; tell users how in your `;;; Commentary`.
```
Re: line 116, I think you end up creating a lot of checkdoc noise by supplying default keybindings that have a prefix that is reserved to appear only in user configs.  I would ask you to avoid doing this -- not because it's "bad", but because if *every* package started doing this without some back-pressure, then these checks would become useless as a reviewing aid.

Package and license:
- COPYING excerpt: `Sequoia PGP sqel is free software; you can redistribute it and/or modify...`
- sq.el (GPL*) -- Bindings for Sequoia PGP's cli

Re: the license, by customizing the license you risk making it difficult for programs to automatically detect the license, e.g. [gitlab thinks the license is "other"](https://gitlab.com/sequoia-pgp/sqel/-/blob/main/COPYING) -- for that reason I would recommend using a "standard" version of the license.

**Comment by teythoon** [comment]
Thanks for the feedback.  I'll address that.  However, regarding this:

> Re: line 116, I think you end up creating a lot of checkdoc noise by supplying default keybindings that have a prefix that is reserved to appear only in user configs. I would ask you to avoid doing this -- not because it's "bad", but because if every package started doing this without some back-pressure, then these checks would become useless as a reviewing aid.

I'm a bit at a loss what to do.  Note that I don't set the keybindings, instead I supply a function that if invoked by the user in their config sets global key bindings.  I fear that asking the user to set key bindings for each individual function will be both very verbose, and users will miss out on future extensions to this package.

If there is a better way to achieve this, please do point that out!

**Comment by riscy** [comment]
I actually think I was being too picky there.  Happy to merge this, but do note this (very minor) lint:

sq.el:151: Argument `prefix' should appear (as PREFIX) in the doc string

which you can fix by just capitalizing the word PREFIX in the docstring.

**Comment by teythoon** [comment]
Cool, thanks!

> sq.el:151: Argument `prefix' should appear (as PREFIX) in the doc string

Odd, I don't know how I missed that!  Will fix it in the next release.

**Pull request merged**
