### PR TITLE
Add recipe for projection dape

### PR DESCRIPTION
**Pull request by mohkale**
### Brief summary of what the package does

Allows you to select debug targets based on the current project type and forward them to dape.

### Direct link to the package repository

https://github.com/mohkale/projection

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

N/A.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I noticed you've got other PR(s) already open #8961.  To split my review time evenly between authors, I try to do one PR at a time per author, but I promise I'll get to this when we resolve earlier PRs.

**Comment by riscy** [comment]
Thanks for this - checklist look great, but I just noticed incomplete commentary:

```elisp
;;; Commentary:

;; TODO: commentary.
```

**Comment by mohkale** [comment]
Ah, my bad, sorry. Added now.

**Comment by riscy** [comment]
Thanks - looks good.

**Pull request merged**
