### PR TITLE
Add recipe for el-patch

### PR DESCRIPTION
**Pull request by raxod502**
### Brief summary of what the package does

`el-patch` is a package for future-proofing Emacs Lisp customizations.
It provides a mechanism for overriding a function in such a way that
you can check later whether or not the original definition has
changed, thus reducing the probability that your customizations will
break without warning.

### Direct link to the package repository

https://github.com/raxod502/el-patch

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Please don't remove pull request template.

Code review
- `(quote el-patch-add)`, `(quote ...)` pattern in pcase is supported since Emacs 25. This package requires Emacs 24.4 or higher version but Emacs 24.4 and 24.5 does not work.

**Comment by raxod502** [comment]
Ah yes, my apologies about the PR template. You might want to remove this advice from `CONTRIBUTING.md`,

> After verifying the entry works properly please open a pull request on
> GitHub. Consider the [hub](https://github.com/github/hub)
> command-line utility by [defunkt](http://chriswanstrath.com/) which
> helps simplify this process.

as `hub` does not respect PR templates.

I will bump the required Emacs version upstream.

**Comment by syohex** [comment]
Could you add License ? Add License file into repository or add comment in file.

**Comment by raxod502** [comment]
How did I forget that? Silly me.

**Comment by syohex** [comment]
Merged.

**Comment by alphapapa** [comment]
Unfortunately this package lacks any useful description in the commentary, requiring potential users to open a browser to the GitHub page and scroll down to the third page of content to find out what it does.

**Comment by raxod502** [comment]
Fair point. I will add a description. Thanks for the feedback.

**Comment by alphapapa** [comment]
Thanks!  Looks like an amazing package, by the way!

**Comment by purcell** [comment]
> Unfortunately this package lacks any useful description in the commentary, requiring potential users to open a browser to the GitHub page and scroll down to the third page of content to find out what it does.

Agreed - definitely needs a worth `Commentary:` section in `el-patch.el`. :-)

**Comment by raxod502** [comment]
Done. Sorry it took so long, I have been submerged in other work and also distracted by the fact that I'm trying to refactor the `el-patch` kernel to allow for `el-patch-defvar`, `el-patch-defcustom`, and more (not just `el-patch-defun` and friends).

**Comment by purcell** [comment]
Nice. :-)

**Pull request merged**
