### PR TITLE
Add emacs-helper recipes

### PR DESCRIPTION
**Pull request by tumashu**
### Brief summary of what the package does

This package is tumashu's emacs-config, somebody of my emacs community want
to it become a package, and I will update it frequently.

### Direct link to the package repository

https://github.com/tumashu/emacs-helper

### Your association with the package

I am maintainer and use it every day.

### Relevant communications with the upstream package maintainer

None

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I think this is very personal configurations. I suppose it is better to prepare install script like [prelude](https://github.com/bbatsov/prelude/) or use [spacemacs](https://github.com/syl20bnr/spacemacs/) like setup(Add init.el and `git clone` it as `~/.emacs`) rather than MELPA package.

**Comment by tumashu** [comment]
This package will be used in different way: I want to it grow as a simple emacs "book" for beginner instead of a "config",  it will be the sourse of documents: http://tumashu.github.io/emacs-helper/

**Comment by tumashu** [comment]
Although there are few "documents" at moment.

**Comment by purcell** [comment]
Yes, this is really personal configuration, and not a coherent package with a specific purpose which will be useful to many people. So, sorry, but we've declined packages like this previously, and I'm going to decline this one too.

**Pull request closed without merging**
