### PR TITLE
Add recipe for crazy-theme

### PR DESCRIPTION
**Pull request by eval-exec**
### Brief summary of what the package does

The Crazy theme give you crazy experience, it will generate random color on every you load this theme, use this Emacs theme if you are crazy.

### Direct link to the package repository

https://github.com/eval-exec/crazy-theme.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
Cool idea.
Some suggestions:

There is a duplicate Commentary  section in the header of the file which should be removed.

There is a lot of repetition in the face specs. Consider doing setting the faces programmatically, rather than manually copying the spec for each face.
I see the pattern `(apply 'format "#02X#02X#02X ...)` enough where it may make sense to abstract that into a function.

**Comment by riscy** [comment]
Quick first pass from my side too --

The summary line "Minimalistic light color theme" seems incorrect? :)

`crazy-theme.el` with byte-compile using Emacs 28.1:
- Temporarily ignoring `no-byte-compile` flag
```
crazy-theme.el:75:1: Warning: defcustom for `crazy-foreground-func' fails to
    specify containing group
crazy-theme.el:75:1: Warning: defcustom for `crazy-foreground-func' fails to
    specify containing group
crazy-theme.el:79:1: Warning: defcustom for `crazy-background-func' fails to
    specify containing group
crazy-theme.el:79:1: Warning: defcustom for `crazy-background-func' fails to
    specify containing group
```

`crazy-theme.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- crazy-theme.el#L54: It's safer to sharp-quote function names; use `#'`
- crazy-theme.el#L59: It's safer to sharp-quote function names; use `#'`
- crazy-theme.el#L63: It's safer to sharp-quote function names; use `#'`
- crazy-theme.el#L73: It's safer to sharp-quote function names; use `#'`
```

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

**Comment by eval-exec** [comment]
> Cool idea. Some suggestions:
> 
> There is a duplicate Commentary section in the header of the file which should be removed.
> 
> There is a lot of repetition in the face specs. Consider setting the faces programmatically, rather than manually copying the spec for each face. I see the pattern `(apply 'format "#02X#02X#02X ...)` enough where it may make sense to abstract that into a function.

Thank you, I think I can group these faces into seperate "grouped faces", and apply some crazy function to the "grouped faces".

**Comment by riscy** [comment]
No worries - let me know when ready for another look.

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to reach out.

**Comment by progfolio** [comment]
@eval-exec  Still interested in submitting this package?

**Comment by riscy** [comment]
Friendly ping :)

**Comment by riscy** [comment]
I'll close this for now, but don't hesitate to reopen when this is ready for another look.

**Pull request closed without merging**
