### PR TITLE
Add evil-lispops

### PR DESCRIPTION
**Pull request by precompute**
### Brief summary of what the package does

Functions that make lisp editing easier for Evil users.

Functions are used in normal mode.

### Direct link to the package repository

https://github.com/precompute/evil-lispops

### Your association with the package

Maintainer / Contributor

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`evil-lispops.el` with byte-compile using Emacs 29.2:
```
evil-lispops.el:74:2: Warning: defvar `evil-lispops-setup-done?' docstring wider than 80 characters
evil-lispops.el:77:2: Warning: defvar `evil-lispops-open-inside' docstring wider than 80 characters
In evil-lispops--get-range:
evil-lispops.el:117:2: Warning: docstring wider than 80 characters
In evil-lispops-open-parent-end:
evil-lispops.el:202:9: Warning: reference to free variable `evil-lispops-goto-parent-end'
In evil-lispops-goto-child-beg:
evil-lispops.el:216:12: Warning: Unused lexical variable `postloop?'
In evil-lispops-goto-left-sibling-beg:
evil-lispops.el:378:12: Warning: `looking-back' called with 1 argument, but requires 2 or 3
evil-lispops.el:434:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode'
In evil-lispops-mode:
evil-lispops.el:434:2: Warning: docstring wider than 80 characters
```

`evil-lispops.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- evil-lispops.el#L428: It's safer to sharp-quote function names; use `#'`
- evil-lispops.el#L425: `unless` body does not need to be wrapped in `progn`
```

Stderr output while compiling/loading:
```
evil-lispops.el: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode'
```

**Comment by precompute** [comment]
All issues fixed, except for the following, because the complete sentences are over 80 chars:

`evil-lispops.el` with checkdoc 0.6.2 (fix *within reason*):
```
evil-lispops.el:75: First line is not a complete sentence
evil-lispops.el:79: First line is not a complete sentence
evil-lispops.el:120: First line is not a complete sentence
evil-lispops.el:435: First line is not a complete sentence
```

I didn't test with Melpazoid when I made the pull request, but I did use checkdoc, byte-compile and package-lint and they didn't show me any errors.  Byte compile *should* have, I was using a function as a variable.  Maybe it's my config, I don't know.

**Comment by progfolio** [comment]
Some notes:

```diff
@@ -71,10 +71,15 @@
 (require 'evil)
 
 ;;;; Variables
+
+;; A more idiomatic name would be evil-lispops-setup-p
 (defvar evil-lispops-setup-done? nil
   "Whether `evil-lispops-setup’ has been invoked successfully in the
 current instance.")
 
+;; If this is meant to be customized by the user, it should be a defcustom.
+;; This will also allow you to specify the accepted types, rather than encoding
+;; them in the docstring.
 (defvar evil-lispops-open-inside t
   "Whether evil-lispops-open-* commands open inside the bracket (t) or
 before the bracket (nil).")
@@ -112,37 +117,31 @@ evil-lispops-bindings
   "Bindings set when `evil-lispops-mode’ is enabled.")
 
 ;;;; Helper Functions
+;; This macro could be replaced by `cl-decf' at no cost.
+;; Evil already depends on cl-lib.
 (defmacro evil-lispops--dec-var (var)
   "Decrement and set `VAR’."
   `(setq ,var (- ,var 1)))
 
-(defun evil-lispops--get-range (&optional count inclusive?)
+;;`inclusivep' would be a more idiomatic parameter name.
+;; Parameters are not generally quoted in docstrings; just capitalized.
+(defun evil-lispops--get-range (&optional count inclusivep)
   "Use `evil-select-paren’ to get the value of points at the ends of a
-paren pair. Accepts `COUNT’.  `INCLUSIVE?’ determines whether range is
+paren pair. Accepts COUNT.  INCLUSIVEP determines whether range is
 inside the paren block or outside."
-  (let ((count (or count 1)))
-    ;; evil-select-paren does not work when bracket is at [:space:]+(eobp)
-    ;; (if (and (or (eobp)
-    ;;              (= (point-max) (+ (point) 1))
-    ;;              (= (point-max) (+ (point) 2)))
-    ;;          (looking-at ")"))
-    ;;     (save-excursion
-    ;;       (goto-char (- (point) 1))
-    ;;       (evil-select-paren ?\( ?\) (point) 0 nil count inclusive?))
-    ;;   (evil-select-paren ?\( ?\) (point) 0 nil count inclusive?))
-    (evil-select-paren ?\( ?\) (point) 0 nil count inclusive?)))
+  (evil-select-paren ?\( ?\) (point) 0 nil (or count 1) inclusivep))
 
 ;;;; Operators:
 
-(defun evil-lispops-goto-beg (&optional count inclusive?)
-  "Go to beginning of paren pair.  `COUNT’ to enable jumping to nth parent.
-`INCLUSIVE’ for cursor placement style."
+;; The `progn' is unnecessary for the body of these functions.
+;; Since the `count' variable is only used once, there's no need to let-bind it.
+(defun evil-lispops-goto-beg (&optional count inclusivep)
+  "Go to beginning of paren pair.  COUNT to enable jumping to nth parent.
+INCLUSIVEP for cursor placement style."
   (interactive)
-  (progn
-    (if (looking-at ")")
-        (goto-char (- (point) 1)))
-    (let ((count (or count 1)))
-      (goto-char (car (evil-lispops--get-range count inclusive?))))))
+  (if (looking-at ")")
+      (goto-char (- (point) 1))
+    (goto-char (car (evil-lispops--get-range (or count 1) inclusive?)))))
 
 (defun evil-lispops-goto-end (&optional count inclusive?)
   "Go to end of paren pair.  `COUNT’ to enable jumping to nth parent.
@@ -382,8 +381,8 @@ evil-lispops-goto-left-sibling-beg
         (progn
           (goto-char (- (point) 1))
           (if goto-end?
-            (evil-lispops-goto-left-adjacent-child-end count)
-          (evil-lispops-goto-left-adjacent-child-beg count)))))))
+              (evil-lispops-goto-left-adjacent-child-end count)
+            (evil-lispops-goto-left-adjacent-child-beg count)))))))
 
 (defun evil-lispops-goto-left-sibling-end (&optional count)
   "Go to end of left sibling paren pair.  Accepts `COUNT’."
@@ -424,6 +423,9 @@ evil-lispops--bind-keys
 (defun evil-lispops-setup ()
   "Setup bindings for `evil-lispops’."
   (interactive)
+  ;; What if `evil-lispops-bindings' have been changed, and the mode is re-enabled?
+  ;; It's probably better to unconditionally set the keys.
+  ;; The performance cost is negligible.
   (unless evil-lispops-setup-done?
     (evil-lispops--bind-keys)
     (setq evil-lispops-setup-done? t)))
@@ -432,9 +434,7 @@ evil-lispops-mode-map
   "Keymap used by `evil-lispops-mode’.")
 
 (define-minor-mode evil-lispops-mode
-  "Edit Lisp evilly.  Adds commands to evil’s normal mode that help you
-jump to / open at the beginning / end of the current / parent / adjacent
-paren block."
+  "Edit Lisp evilly.  Adds commands to edit and navigate sexps."
   :lighter nil
   (evil-lispops-setup))
```

**Comment by progfolio** [comment]
> @progfolio Thank you for the review and the suggestions! I have incorporated all of them, except the one about not using progn. That breaks a few functions, so I've let it stay in. This is my first "serious" package to MELPA and your review is very helpful.

You're welcome.
The `progn` is implicit in many cases where it's used here.
I've changed a few functions to illustrate below.

Many of these functions offer symmetrical operations.
e.g. goto-beg/end, left/right.
So they should be defined in terms of one another.
For example, your definitions which offer a parameter to reverse direction can be used to define
their opposite operations by partially applying that parameter.
See the definition of `backward-sexp` (note how it passes a negative argument to `forward-sexp`) for a built-in example.

```diff
@@ -78,35 +78,34 @@ evil-lispops-open-inside
   :group 'evil-lispops)
 
 (defvar evil-lispops-bindings
-  (list
-   '(">." "evil-lispops-goto-end")
-   '("<." "evil-lispops-goto-beg")
-   '(">i" "evil-lispops-open-end")
-   '("<i" "evil-lispops-open-beg")
-   '(">j" "evil-lispops-open-child-end")
-   '("<j" "evil-lispops-open-child-beg")
-   '(">J" "evil-lispops-goto-child-end")
-   '("<J" "evil-lispops-goto-child-beg")
-   '(">k" "evil-lispops-open-parent-end")
-   '("<k" "evil-lispops-open-parent-beg")
-   '(">K" "evil-lispops-goto-parent-end")
-   '("<K" "evil-lispops-goto-parent-beg")
-   '(">h" "evil-lispops-open-left-adjacent-child-end")
-   '("<h" "evil-lispops-open-left-adjacent-child-beg")
-   '(">H" "evil-lispops-goto-left-adjacent-child-end")
-   '("<H" "evil-lispops-goto-left-adjacent-child-beg")
-   '(">l" "evil-lispops-open-right-adjacent-child-end")
-   '("<l" "evil-lispops-open-right-adjacent-child-beg")
-   '(">L" "evil-lispops-goto-right-adjacent-child-end")
-   '("<L" "evil-lispops-goto-right-adjacent-child-beg")
-   '(">n" "evil-lispops-open-right-sibling-end")
-   '("<n" "evil-lispops-open-right-sibling-beg")
-   '(">N" "evil-lispops-goto-right-sibling-end")
-   '("<N" "evil-lispops-goto-right-sibling-beg")
-   '(">p" "evil-lispops-open-left-sibling-end")
-   '("<p" "evil-lispops-open-left-sibling-beg")
-   '(">P" "evil-lispops-goto-left-sibling-end")
-   '("<P" "evil-lispops-goto-left-sibling-beg"))
+  '(">."  'evil-lispops-goto-end
+    "<."  'evil-lispops-goto-beg
+    ">i"  'evil-lispops-open-end
+    "<i"  'evil-lispops-open-beg
+    ">j"  'evil-lispops-open-child-end
+    "<j"  'evil-lispops-open-child-beg
+    ">J"  'evil-lispops-goto-child-end
+    "<J"  'evil-lispops-goto-child-beg
+    ">k"  'evil-lispops-open-parent-end
+    "<k"  'evil-lispops-open-parent-beg
+    ">K"  'evil-lispops-goto-parent-end
+    "<K"  'evil-lispops-goto-parent-beg
+    ">h"  'evil-lispops-open-left-adjacent-child-end
+    "<h"  'evil-lispops-open-left-adjacent-child-beg
+    ">H"  'evil-lispops-goto-left-adjacent-child-end
+    "<H"  'evil-lispops-goto-left-adjacent-child-beg
+    ">l"  'evil-lispops-open-right-adjacent-child-end
+    "<l"  'evil-lispops-open-right-adjacent-child-beg
+    ">L"  'evil-lispops-goto-right-adjacent-child-end
+    "<L"  'evil-lispops-goto-right-adjacent-child-beg
+    ">n"  'evil-lispops-open-right-sibling-end
+    "<n"  'evil-lispops-open-right-sibling-beg
+    ">N"  'evil-lispops-goto-right-sibling-end
+    "<N"  'evil-lispops-goto-right-sibling-beg
+    ">p"  'evil-lispops-open-left-sibling-end
+    "<p"  'evil-lispops-open-left-sibling-beg
+    ">P"  'evil-lispops-goto-left-sibling-end
+    "<P"  'evil-lispops-goto-left-sibling-beg)
   "Bindings set when `evil-lispops-mode’ is enabled.")
 
 ;;;; Helper Functions
@@ -121,46 +120,37 @@ evil-lispops-goto-beg
   "Go to beginning of paren pair.  COUNT to enable jumping to nth parent.
 INCLUSIVEP for cursor placement style."
   (interactive)
-  (progn
-    (if (looking-at ")")
-        (goto-char (- (point) 1)))
-    (let ((count (or count 1)))
-      (goto-char (car (evil-lispops--get-range count inclusivep))))))
+  (when (looking-at ")") (goto-char (- (point) 1)))
+  (goto-char (car (evil-lispops--get-range (or count 1) inclusivep))))
 
 (defun evil-lispops-goto-end (&optional count inclusivep)
   "Go to end of paren pair.  COUNT to enable jumping to nth parent.
 INCLUSIVEP for cursor placement style."
   (interactive)
-  (progn
-    (if (looking-at ")")
-        (goto-char (- (point) 1)))
-    (let ((count (or count 1)))
-      (goto-char (cadr (evil-lispops--get-range count inclusivep))))))
+  (when (looking-at ")") (goto-char (- (point) 1)))
+  (goto-char (cadr (evil-lispops--get-range (or count 1) inclusivep))))
 
 (defun evil-lispops-open-beg ()
   "Open at beginning of paren pair."
   (interactive)
-  (progn
-    (if evil-lispops-open-inside
-        (evil-lispops-goto-beg)
-      (evil-lispops-goto-beg nil t))
-    (evil-insert 0)))
+  (if evil-lispops-open-inside
+      (evil-lispops-goto-beg)
+    (evil-lispops-goto-beg nil t))
+  (evil-insert 0))
 
 (defun evil-lispops-open-end ()
   "Open at end of paren pair."
   (interactive)
-  (progn
-    (if evil-lispops-open-inside
-        (evil-lispops-goto-end)
-      (evil-lispops-goto-end nil t))
-    (evil-insert 0)))
+  (if evil-lispops-open-inside
+      (evil-lispops-goto-end)
+    (evil-lispops-goto-end nil t))
+  (evil-insert 0))
 
 (defun evil-lispops-goto-parent-beg (&optional count inclusivep)
   "Go to beginning of parent paren pair.  Accepts COUNT.
 INCLUSIVEP for cursor placement style."
   (interactive "P")
-  (if (looking-at "(")
-      (goto-char (+ (point) 1)))
+  (when (looking-at "(") (goto-char (+ (point) 1)))
   (evil-lispops-goto-beg (1+ (or count 1)) inclusivep))
 
 (defun evil-lispops-goto-parent-end (&optional count inclusivep)
@@ -186,156 +176,137 @@ evil-lispops-open-parent-end
     (if evil-lispops-open-inside
         (evil-lispops-goto-parent-end count)
       (evil-lispops-goto-parent-end count t))
-    (unless (eq (point) point)
-      (evil-lispops-open-end))))
+    (unless (eq (point) point) (evil-lispops-open-end))))
 
-(defun evil-lispops-goto-child-beg (&optional count goto-end? relative?)
-  "Go to beginning of child paren pair.  Accepts COUNT.
-GOTO-END? for the reverse operation.  RELATIVE’ for relative child."
+(defun evil-lispops-goto-child-beg (&optional n reversep relativep)
+  "Go to beginning of Nth child paren pair.
+REVERSEP for the reverse operation.  RELATIVEP for relative child."
   (interactive "P")
-  (let ((count (or count 1))
-        (point (point)))
-    (unless relative? (evil-lispops-goto-beg))
-    (let ((parentrange (evil-lispops--get-range)))
-      (while (> count 0)
-        (progn
-          (while (and (not (looking-at "("))
-                      (> (cadr parentrange) (point)))
-            (evil-forward-WORD-begin))
-          (evil-lispops-goto-beg nil t)
-          (if (not (= count 1))
-              (progn
-                (evil-lispops-goto-end)
-                (goto-char (+ (point) 1))))
-          (cl-decf count)))
-      (if (looking-at "(")
-          (progn (goto-char (+ (point) 1))
-                 (when goto-end? (evil-lispops-goto-end)))
-        (goto-char point)))))
+  (let ((n (or n 1))
+        (point (point))
+        (parentrange (evil-lispops--get-range)))
+    (unless relativep (evil-lispops-goto-beg))
+    (while (> n 0)
+      (while (and (not (looking-at "("))
+                  (> (cadr parentrange) (point)))
+        (evil-forward-WORD-begin))
+      (evil-lispops-goto-beg nil t)
+      (if (= n 1)
+          (cl-decf n)
+        (evil-lispops-goto-end)
+        (goto-char (+ (point) 1))))
+    (if (not (looking-at "("))
+        (goto-char point)
+      (goto-char (+ (point) 1))
+      (when reversep (evil-lispops-goto-end)))))
 
-(defun evil-lispops-goto-child-end (&optional count)
-  "Go to end of child paren pair.  Accepts COUNT."
+(defun evil-lispops-goto-child-end (&optional n)
+  "Go to end of Nth child paren pair."
   (interactive "P")
-  (evil-lispops-goto-child-beg (or count 1) t))
+  (evil-lispops-goto-child-beg (or n 1) t))
 
-(defun evil-lispops-open-child-beg (&optional count)
-  "Open at beginning of child paren pair.  Accepts COUNT."
+(defun evil-lispops-open-child-beg (&optional n)
+  "Open at beginning of Nth child paren pair."
   (interactive "P")
   (let ((point (point)))
-    (progn
-      (evil-lispops-goto-child-beg (or count 1))
-      (unless (eq (point) point)
-        (evil-lispops-open-beg)))))
+    (evil-lispops-goto-child-beg (or n 1))
+    (unless (eq (point) point) (evil-lispops-open-beg))))
 
-(defun evil-lispops-open-child-end (&optional count)
-  "Open at end of child paren pair.  Accepts COUNT."
+(defun evil-lispops-open-child-end (&optional n)
+  "Open at end of Nth child paren pair."
   (interactive "P")
   (let ((point (point)))
-    (progn
-      (evil-lispops-goto-child-end (or count 1))
-      (unless (eq (point) point)
-        (evil-lispops-open-end)))))
+    (evil-lispops-goto-child-end (or n 1))
+    (unless (eq (point) point) (evil-lispops-open-end))))
 
-(defun evil-lispops-goto-right-adjacent-child-beg (&optional count)
-  "Go to beginning of right adjacent child paren pair.  Accepts COUNT."
+(defun evil-lispops-goto-right-adjacent-child-beg (&optional n)
+  "Go to beginning of Nth right adjacent child paren pair."
   (interactive "P")
-  (evil-lispops-goto-child-beg (or count 1) nil t))
+  (evil-lispops-goto-child-beg (or n 1) nil t))
 
-(defun evil-lispops-goto-right-adjacent-child-end (&optional count)
-  "Go to end of right adjacent child paren pair.  Accepts COUNT."
+(defun evil-lispops-goto-right-adjacent-child-end (&optional n)
+  "Go to end of Nth right adjacent child paren pair."
   (interactive "P")
-  (evil-lispops-goto-child-beg (or count 1) t t))
+  (evil-lispops-goto-child-beg (or n 1) t t))
 
-(defun evil-lispops-open-right-adjacent-child-beg (&optional count)
-  "Open at beginning of right adjacent child paren pair.  Accepts COUNT."
+(defun evil-lispops-open-right-adjacent-child-beg (&optional n)
+  "Open at beginning of Nth right adjacent child paren pair."
   (interactive "P")
   (let ((point (point)))
-    (progn
-      (evil-lispops-goto-child-beg (or count 1) nil t)
-      (unless (eq (point) point)
-        (evil-lispops-open-beg)))))
+    (evil-lispops-goto-child-beg (or n 1) nil t)
+    (unless (eq (point) point) (evil-lispops-open-beg))))
 
-(defun evil-lispops-open-right-adjacent-child-end (&optional count)
-  "Open at end of right adjacent child paren pair.  Accepts COUNT."
+(defun evil-lispops-open-right-adjacent-child-end (&optional n)
+  "Open at end of Nth right adjacent child paren pair.."
   (interactive "P")
   (let ((point (point)))
-    (progn
-      (evil-lispops-goto-child-beg (or count 1) t t)
-      (unless (eq (point) point)
-        (evil-lispops-open-end)))))
+    (evil-lispops-goto-child-beg (or n 1) t t)
+    (unless (eq (point) point) (evil-lispops-open-end))))
 
-(defun evil-lispops-goto-left-adjacent-child-beg (&optional count)
-  "Go to beginning of left adjacent child paren pair.  Accepts COUNT."
+(defun evil-lispops-goto-left-adjacent-child-beg (&optional n)
+  "Go to beginning of Nth left adjacent child paren pair."
   (interactive "P")
-  (let ((count (or count 1))
+  (let ((n (or n 1))
         (point (point))
         (parentrange (evil-lispops--get-range)))
-    (while (> count 0)
-      (progn
-        (while (and (not (looking-at ")"))
-                    (> (point) (car parentrange)))
-          (evil-backward-WORD-end))
-        (evil-lispops-goto-beg nil t)
-        (cl-decf count)
-        (if (looking-at "(")
-            (evil-lispops-goto-beg)
-          (if (> (point) (car parentrange))
-              (goto-char point)))))))
-
-(defun evil-lispops-goto-left-adjacent-child-end (&optional count)
-  "Go to end of left adjacent child paren pair.  Accepts COUNT."
+    (while (> n 0)
+      (while (and (not (looking-at ")")) (> (point) (car parentrange)))
+        (evil-backward-WORD-end))
+      (evil-lispops-goto-beg nil t)
+      (cl-decf n)
+      (if (looking-at "(")
+          (evil-lispops-goto-beg)
+        (if (> (point) (car parentrange))
+            (goto-char point))))))
+
+(defun evil-lispops-goto-left-adjacent-child-end (&optional n)
+  "Go to end of Nth left adjacent child paren pair."
   (interactive "P")
-  (progn
-    (evil-lispops-goto-left-adjacent-child-beg (or count 1))
-    (evil-lispops-goto-end)))
+  (evil-lispops-goto-left-adjacent-child-beg (or n 1))
+  (evil-lispops-goto-end))
 
-(defun evil-lispops-open-left-adjacent-child-beg (&optional count)
-  "Open at beginning of left adjacent child paren pair.  Accepts COUNT."
+(defun evil-lispops-open-left-adjacent-child-beg (&optional n)
+  "Open at beginning of Nth left adjacent child paren pair."
   (interactive "P")
-  (progn
-    (evil-lispops-goto-left-adjacent-child-end (or count 1))
-    (evil-lispops-open-beg)))
+  (evil-lispops-goto-left-adjacent-child-end (or n 1))
+  (evil-lispops-open-beg))
 
-(defun evil-lispops-open-left-adjacent-child-end (&optional count)
-  "Open at end of left adjacent child paren pair.  Accepts COUNT."
+(defun evil-lispops-open-left-adjacent-child-end (&optional n)
+  "Open at end of Nth left adjacent child paren pair."
   (interactive "P")
-  (progn
-    (evil-lispops-goto-left-adjacent-child-beg (or count 1))
-    (evil-lispops-open-end)))
+  (evil-lispops-goto-left-adjacent-child-beg (or n 1))
+  (evil-lispops-open-end))
 
-(defun evil-lispops-goto-right-sibling-beg (&optional count goto-end?)
-  "Go to beginning of right sibling paren pair.  Accepts COUNT.
-GOTO-END? for the reverse operation."
+(defun evil-lispops-goto-right-sibling-beg (&optional n reversep)
+  "Go to beginning of Nth right sibling paren pair.
+When REVERSEP is non-nil, reverse direction."
   (interactive "P")
-  (let ((count (or count 1))
+  (let ((count (or n 1))
         (point (point)))
-    (progn
-      (evil-lispops-goto-end)
-      (goto-char (+ (point) 1))
-      (if (looking-at ")")
-          (goto-char point)
-        (if goto-end?
-            (evil-lispops-goto-right-adjacent-child-end count)
-          (evil-lispops-goto-right-adjacent-child-beg count))))))
+    (evil-lispops-goto-end)
+    (goto-char (1+ (point)))
+    (if (looking-at ")")
+        (goto-char point)
+      (funcall (if reversep #'evil-lispops-goto-right-adjacent-child-end
+                 #'evil-lispops-goto-right-adjacent-child-beg)
+               count))))
 
-(defun evil-lispops-goto-right-sibling-end (&optional count)
-  "Go to end of right sibling paren pair.  Accepts COUNT."
+(defun evil-lispops-goto-right-sibling-end (&optional n)
+  "Go to end of Nth right sibling paren pair."
   (interactive "P")
-  (evil-lispops-goto-right-sibling-beg (or count 1) t))
+  (evil-lispops-goto-right-sibling-beg (or n 1) t))
 
-(defun evil-lispops-open-right-sibling-beg (&optional count)
-  "Open at end of right sibling paren pair.  Accepts COUNT."
+(defun evil-lispops-open-right-sibling-beg (&optional n)
+  "Open at end of Nth right sibling paren pair."
   (interactive "P")
-  (progn
-    (evil-lispops-goto-right-sibling-beg (or count 1))
-    (evil-lispops-open-beg)))
+  (evil-lispops-goto-right-sibling-beg (or n 1))
+  (evil-lispops-open-beg))
 
-(defun evil-lispops-open-right-sibling-end (&optional count)
-  "Go to end of right sibling paren pair.  Accepts COUNT."
+(defun evil-lispops-open-right-sibling-end (&optional n)
+  "Go to end of Nth right sibling paren pair."
   (interactive "P")
-  (progn
-    (evil-lispops-goto-right-sibling-beg (or count 1) t)
-    (evil-lispops-open-end)))
+    (evil-lispops-goto-right-sibling-beg (or n 1) t)
+    (evil-lispops-open-end))
 
 (defun evil-lispops-goto-left-sibling-beg (&optional count goto-end?)
   "Go to beginning of left sibling paren pair.  Accepts COUNT.
@@ -350,8 +321,8 @@ evil-lispops-goto-left-sibling-beg
         (progn
           (goto-char (- (point) 1))
           (if goto-end?
-            (evil-lispops-goto-left-adjacent-child-end count)
-          (evil-lispops-goto-left-adjacent-child-beg count)))))))
+              (evil-lispops-goto-left-adjacent-child-end count)
+            (evil-lispops-goto-left-adjacent-child-beg count)))))))
 
 (defun evil-lispops-goto-left-sibling-end (&optional count)
   "Go to end of left sibling paren pair.  Accepts COUNT."
@@ -373,30 +344,27 @@ evil-lispops-open-left-sibling-end
     (evil-lispops-open-end)))
 
 ;;;; Mode
-(defun evil-lispops--define-key (binding function)
-  "Define a key with `evil-define-minor-mode-key’.
-Needs FUNCTION that will be bound to BINDING."
-  (evil-define-key
-    'normal evil-lispops-mode-map binding (intern (car function))))
+(defvar evil-lispops-mode-map (make-sparse-keymap)
+  "Keymap used by `evil-lispops-mode’.")
 
 (defun evil-lispops--bind-keys ()
   "Bind keys for `evil-lispops-mode’."
   (evil-define-key 'normal evil-lispops-mode-map (kbd ">>") 'evil-shift-right)
   (evil-define-key 'normal evil-lispops-mode-map (kbd "<<") 'evil-shift-left)
-  (dolist (p evil-lispops-bindings)
-    (evil-lispops--define-key (car p) (cdr p))))
+  (eval `(evil-define-key 'normal evil-lispops-mode-map
+           ,@(mapcar (lambda (it) (if (stringp it) (list 'kbd it) it))
+                     evil-lispops-bindings))
+        t))
 
 (defun evil-lispops-setup ()
   "Setup bindings for `evil-lispops’."
   (interactive)
   (evil-lispops--bind-keys))
 
-(defvar evil-lispops-mode-map (make-sparse-keymap)
-  "Keymap used by `evil-lispops-mode’.")
-
+;;;###autoload
 (define-minor-mode evil-lispops-mode
   "Edit Lisp evilly.  Adds commands to edit and navigate sexps."
-  :lighter nil
+  :lighter " evil-lispops"
   :group 'evil-lispops
   (evil-lispops-setup))

**Comment by precompute** [comment]
Thank you!  I've added a lighter string, removed all the `progn`s, renamed vars and nuked the internal var for binding instead of using a function to feed contents of said var to `evil-define-key`.  The file's been reduced by 85 lines so far!

**Comment by riscy** [comment]
@progfolio , you're a star - thank you for that.

@precompute There are a couple more things I want to check on --

`evil-lispops.el` with checkdoc 0.6.2 (fix *within reason*):
```
evil-lispops.el:75: First line is not a complete sentence
evil-lispops.el:82: First line is not a complete sentence
evil-lispops.el:89: First line is not a complete sentence
evil-lispops.el:116: First line is not a complete sentence
```
These are an "issue" because M-x apropos only reveals the first sentence in each docstrings.  All you have to do is turn a docstring like this:
```
(defcustom evil-lispops-open-inside t
  "If non-nil, evil-lispops-open-* commands open inside the bracket.  If nil,
they open outside the bracket."
  :type 'boolean
  :group 'evil-lispops)
```
into one like this:
```elisp
(defcustom evil-lispops-open-inside t
  "If non-nil, evil-lispops-open-* commands open inside the bracket.
If nil, they open outside the bracket."
  :type 'boolean
  :group 'evil-lispops)
```

- `evil-lispops--bind-keys` is "private" due to the double-dash, but it's also interactive and so readily available for users to M-x with or bind to keys.  Since it's only ever called by `evil-lispops-setup` (which is arguably just a pass-through) you can remove the `interactive` from the bind-keys function.
- Your `define-minor-mode evil-lispops-mode` doesn't call `evil-lispops-setup` which I would have expected - shouldn't the minor mode also be running the setup?

**Comment by precompute** [comment]
Thanks the review.  I've changed the docstrings accordingly.  

I want users to be able to use their own keybinds, so that function isn't called when the mode is activated.  I instead recommend users use `:config` in `use-package` to run that function.

I could also just call that function in evil-lispops.el itself but I'm not sure if that would be accepted.

**Comment by precompute** [comment]
I've removed the `evil-lispops-setup` function entirely.  Now, `evil-lispops--bind-keys` (only populates the keymap) is called when the file is loaded.  Clean bill from melpazoid.

**Comment by riscy** [comment]
Okay, that's reasonable, and I appreciate that evil keybindings are difficult to give the conventional treatment in packages.

**Comment by precompute** [comment]
Thanks a lot!

**Pull request merged**
