### PR TITLE
Add Sculpture-themes

### PR DESCRIPTION
**Pull request by t-e-r-m**
### Brief summary of what the package does

A Vivid theme for Emacs, inspired by the colors attributed to Greco-Roman Sculptures.

Monospace fonts are boring – use variable pitch when it doesn’t break indentation / flow.

Two versions - Light and Dark.

### Direct link to the package repository

https://github.com/t-e-r-m/sculpture-themes

### Your association with the package

I am the Author / Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback

I get the following error:
```
1 issue found:

10:37: error: Package autothemer is not installable.

```
I am not sure how to mitigate this.  Other themes that use autothemer show the same error.
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

I have defined a few custom faces.  
- Should they be prefixed with the name of my theme?
- Should they be removed, because using them requires extra configuration?

### CODE REVIEW

**Comment by riscy** [comment]
> I am not sure how to mitigate this. Other themes that use autothemer show the same error.

This may be down to your `package-archives` variable not including MELPA -- I don't see that issue on my end, so you're clear. :)  Re-running package-lint after that fix may give you:

### sculpture-light-theme.el ###

package-lint (using version 20210511.2055):
```
25 issues found:
1:0: error: There is no `provide' form.
10:0: error: Package-Requires outside the main file have no effect.
47:0: error: "sculpture-light-theme" doesn't start with package's prefix "sculpture-theme".
51:0: error: "head-outline-1" doesn't start with package's prefix "sculpture-theme".
52:0: error: "head-outline-2" doesn't start with package's prefix "sculpture-theme".
53:0: error: "head-outline-3" doesn't start with package's prefix "sculpture-theme".
54:0: error: "head-outline-4" doesn't start with package's prefix "sculpture-theme".
55:0: error: "head-outline-5" doesn't start with package's prefix "sculpture-theme".
56:0: error: "head-outline-6" doesn't start with package's prefix "sculpture-theme".
57:0: error: "head-outline-7" doesn't start with package's prefix "sculpture-theme".
58:0: error: "head-outline-8" doesn't start with package's prefix "sculpture-theme".
59:0: error: "modeline-percent" doesn't start with package's prefix "sculpture-theme".
60:0: error: "modeline-line" doesn't start with package's prefix "sculpture-theme".
61:0: error: "modeline-mode" doesn't start with package's prefix "sculpture-theme".
62:0: error: "modeline-workspace" doesn't start with package's prefix "sculpture-theme".
63:0: error: "variable-pitch-italic" doesn't start with package's prefix "sculpture-theme".
64:0: error: "elfeed-title-1" doesn't start with package's prefix "sculpture-theme".
65:0: error: "elfeed-title-2" doesn't start with package's prefix "sculpture-theme".
66:0: error: "elfeed-title-3" doesn't start with package's prefix "sculpture-theme".
67:0: error: "elfeed-title-4" doesn't start with package's prefix "sculpture-theme".
68:0: error: "elfeed-title-5" doesn't start with package's prefix "sculpture-theme".
69:0: error: "elfeed-title-6" doesn't start with package's prefix "sculpture-theme".
70:0: error: "elfeed-title-7" doesn't start with package's prefix "sculpture-theme".
71:0: error: "elfeed-title-8" doesn't start with package's prefix "sculpture-theme".
72:0: error: "elfeed-star-face" doesn't start with package's prefix "sculpture-theme".
```
The `provide` is a false positive, and you'll be able to align with prefix rules by renaming sculpture-light-theme to sculpture-theme-light.  For the others, I think it's unnecessary for you to be calling `defface` ahead of time, which should clear up the bulk of those.

Other [lints](https://github.com/riscy/melpazoid):
- sculpture-light-theme.el#L30: Use empty lines instead of `;;` on a line by itself within your Commentary

### sculpture-theme.el ###
- sculpture-theme.el#L30: Use empty lines instead of `;;` on a line by itself within your Commentary

**Comment by t-e-r-m** [comment]
Thank you for the review.  I've made the requested changes, but the light version of the theme isn't showing up in `load-theme` for me, but only in `enable-theme`.  It will probably take me a while to debug this and make the package ready for Melpa.

**Comment by t-e-r-m** [comment]
I think I have mitigated the issue, it had something to do with how the themes were named (or at least that's my best guess right now).  I initially thought it was an issue with autothemer, and removed the dependency.  It wasn't, and was reproducible on Vanilla emacs until I renamed the themes as folllows:

`sculpture-theme` -> `sculpture-dark-theme`
`sculpture-theme-light` -> `sculpture-light-theme`

Both show up in `load-theme` now.

### Checklist



- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

**Comment by riscy** [comment]
Hi @t-e-r-m I reran the build and you can see it's getting caught up on there not being a 'main' file.

I will ping @purcell on this one since I haven't personally written a theme before and in case I've missed anything.  But generally you'd want to lay things out something like what you see below (three files, all of them sharing the same prefix, and the "theme" files ending in -theme.el).

```
;;; exa-themes-dark-theme.el --- Example theme: dark variant

;;; Commentary:
;; An example theme -- dark variant.

;;; Code:

;; Local variables:
;; package-lint-main-file: "exa-themes.el"
;; end:

(require 'exa-themes)

(deftheme exa-themes-dark "Example theme: dark variant.")
(custom-theme-set-faces
 'exa-themes-dark
 `(default ((t (:background "midnight blue" :foreground ,exa-main-color)))))

(provide-theme 'exa-themes-dark)
(provide 'exa-themes-dark-theme)
;;; exa-themes-dark-theme.el ends here





;;; exa-themes-light-theme.el --- Example theme: light variant

;;; Commentary:
;; An example theme -- light variant.

;;; Code:

;; Local variables:
;; package-lint-main-file: "exa-themes.el"
;; end:

(require 'exa-themes)

(deftheme exa-themes-light "Example theme: light variant.")
(custom-theme-set-faces
 'exa-themes-light
 `(default ((t (:background "snow1" :foreground ,exa-main-color)))))

(provide-theme 'exa-themes-light)
(provide 'exa-themes-light-theme)
;;; exa-themes-light-theme.el ends here




;;; exa-themes.el --- An 'exa'mple theme pack containing two themes

;; URL: https://github.com/melpa/
;; Version: 0

;;; Commentary:
;; An example theme.

;;; Code:

(defgroup exa-themes nil "An 'exa'mple theme pack." :prefix "exa-themes-" :group 'faces)
(defcustom exa-themes-main-color "#FF0000" "The shared foreground color." :type 'string)

;;;###autoload
(add-to-list
 ;; Register this theme when it's loaded or when the buffer is evaluated:
 'custom-theme-load-path
 (if load-file-name (file-name-directory load-file-name) default-directory))

(provide 'exa-themes)
;;; exa-themes.el ends here
```

**Comment by t-e-r-m** [comment]
I've made the requested changes.  I used melpazoid this time, and apart from the `provide` false positive, there seem to be no errors.

I've also changed the name of the package from *sculpture-theme* to *sculpture-themes*.

**Comment by riscy** [comment]
Just one last nag on this one, but not a blocker since we've already had a few iterations:

byte-compile (using Emacs 27.1):
```
sculpture-themes-light-theme.el:75:1:Warning: Unused lexical variable `bw00'
```
I'd just remove this, and then your users can benefit from the peace of mind of a silent byte-compile.  In any case, thanks a lot for this -- interesting theme!  And welcome to MELPA. :)

**Comment by t-e-r-m** [comment]
I've removed the variable.

And thanks a lot for approving my theme!  Glad to have it on MELPA!

**Pull request merged**
