### PR TITLE
Add recipe for satysfi-ts-mode

### PR DESCRIPTION
**Pull request by Kyure-A**
### Brief summary of what the package does

A tree-sitter based major-mode for [SATySFi](https://github.com/gfngfn/satysfi)

### Direct link to the package repository

https://github.com/Kyure-A/satysfi-ts-mode

### Your association with the package

author

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`satysfi-ts-mode.el` with byte-compile using Emacs 29.1:
```
satysfi-ts-mode.el:45:2: Warning: custom-declare-variable `satysfi-ts-mode-indent-offset' docstring has wrong usage of unescaped single quotes (use \= or different quoting)
satysfi-ts-mode.el:119:2: Warning: defvar `satysfi-ts-mode--font-lock-settings' docstring has wrong usage of unescaped single quotes (use \= or different quoting)
satysfi-ts-mode.el:196:2: Warning: defvar `satysfi-ts-mode--syntax-table' docstring has wrong usage of unescaped single quotes (use \= or different quoting)
satysfi-ts-mode.el:204:2: Warning: defvar `satysfi-ts-mode--indent-rules' docstring has wrong usage of unescaped single quotes (use \= or different quoting)
satysfi-ts-mode.el:258:2: Warning: defvar `satysfi-ts-mode-map' docstring has wrong usage of unescaped single quotes (use \= or different quoting)
In satysfi-ts-mode--indent:
satysfi-ts-mode.el:262:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
satysfi-ts-mode.el:265:13: Warning: Unused lexical variable `i'
satysfi-ts-mode.el:265:13: Warning: Unused lexical variable `i'
```
I sympathize for the mess re: `\=` but it's better to have a clean byte compile.

`satysfi-ts-mode.el` with checkdoc 0.6.2 (fix *within reason*):
```
satysfi-ts-mode.el:271: First sentence should end with punctuation
```

`satysfi-ts-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- satysfi-ts-mode.el#L268: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
```

**Comment by Kyure-A** [comment]
I have fixed the part pointed out by https://github.com/Kyure-A/satysfi-ts-mode/commit/e366ad2b51ef7c958d4d5702d7cc185fb92917ab 
 (I haven't tested melpazoid because it's too much trouble to run it on my own, but I fixed it according to melpazoid's comment so it shouldn't be a problem).

**Comment by riscy** [comment]
>  I never knew that byte-compile would warn me if I did not use `\=!`

Yes, I am actually pretty upset about the decision going in that direction.  I will spare you my rant. :)

But, in this case, I think a clarification is worth making.  Something like this:
```elisp
(defcustom satysfi-ts-mode-indent-offset 4
  "Indent offset for \='satysfi-ts-mode\='."
  :version "29.1"
  :type 'integer
  :safe 'integerp
  :group 'satysfi)
```
should be written like this:
```elisp
(defcustom satysfi-ts-mode-indent-offset 4
  "Indent offset for `satysfi-ts-mode'."
  :version "29.1"
  :type 'integer
  :safe 'integerp
  :group 'satysfi)
```
The backward/forward quoting ``` `like this' ``` will not cause compiler warnings.  And it will also create a hyperlink in the Emacs online help, linking your functions' documentation to each other for users.

If you wanted to single-quote something 'like this', that's the case when you have to carve up your docstrings with extra markup, e.g. ``` \='like this\=' ``` or get a byte-compile warning.

One last thing I'm noticing (that I didn't catch last time) is:

- satysfi-ts-mode.el#L305: Terminate auto-mode-alist entries with `\\'`
- satysfi-ts-mode.el#L306: Terminate auto-mode-alist entries with `\\'`

`\\'` is preferred to `$` because `$` is merely the end of a line (filenames can technically contain linebreaks) but `\\'` is the end of the string.

**Comment by Kyure-A** [comment]
I have corrected the points you pointed out at https://github.com/Kyure-A/satysfi-ts-mode/commit/682b44c80a395a9f8d5b9b64a7d19ece96b5c7df. The correct way to write Emacs Lisp I didn't know, so the review was very helpful. Thanks.

**Comment by riscy** [comment]
Here's the last issue:

- satysfi-ts-mode.el#L279: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`

See the bottom of https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips-for-Defining.html as a reference.

**Comment by Kyure-A** [comment]
I fixed it! Thanks.

**Comment by riscy** [comment]
Thank you!

**Comment by riscy** [comment]
And welcome to MELPA. :)

**Pull request merged**
