### PR TITLE
Add recipe for gulp-task-runner

### PR DESCRIPTION
**Pull request by NicolasPetton**
This package provides a straightforward integration of [Gulp](http://gulpjs.com/) in Emacs. 

Evaluate `M-x gulp` to get the list of gulp tasks of a project and run a task.

- [x] I'm the author of the package
- [x] The package is on github: https://github.com/NicolasPetton/gulp-task-runner
- [x] The package builds (`C-c C-c` in the recipe buffer)
- [x] The package installs properly via `package-install-file`

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Why not just call this "gulp"? It's odd to have the package be `gulp-task-runner`, and then use the `gulp` prefix internally.

**Comment by purcell** [comment]
Also:
- Add an `;;;###autoload`
- `shell-command-to-string` will save a line or two
- Rather than simply calling `compile`, consider using `compilation-start` and naming the buffer `*gulp*` or similar, to avoid clobbering the user's existing `*compilation*` buffer.

**Comment by syohex** [comment]
> shell-command-to-string will save a line or two

I suppose `process-lines` saves lines more.

**Comment by NicolasPetton** [comment]
Steve Purcell <notifications@github.com> writes:

> Thanks. Why not just call this "gulp"? It's odd to have the package be
> `gulp-task-runner`, and then use the `gulp` prefix internally.

gulp.el is an obsolete package in emacs.

**Comment by NicolasPetton** [comment]
:+1: Thanks guys for the feedback.  I pushed some improvements.

**Comment by NicolasPetton** [comment]
@purcell Is it better now?

**Comment by syohex** [comment]
Merged

**Pull request merged**
