### PR TITLE
Add restore-frame-position

### PR DESCRIPTION
**Pull request by aaronjensen**
### Brief summary of what the package does

Remember and restore initial frame position when restarting Emacs.

### Direct link to the package repository

https://github.com/aaronjensen/restore-frame-position

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer
None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
I think the built-in `desktop-save-mode` does this, no?

**Comment by aaronjensen** [comment]
@purcell I didn't know about this mode, thanks! That said, `desktop-save-mode` appears to do too much, at least for my setup. Even when disabling all of the buffer saving, it still breaks my mode line (spaceline) and perspectives when I try to use it.

I can add a note to the readme saying why one may want to use `restore-frame-position` instead of `desktop-save-mode` if you think that would be useful.

**Comment by kaushalmodi** [comment]
I use `desktop-save-mode` to restore my frame. I would suggest filing an emacs bug report explaining the issue you are seeing and how you can start from emacs -Q install only the packages related to this issue and list the steps to recreate the issue.

**Comment by aaronjensen** [comment]
@kaushalmodi what settings do you use? I'll see if I can track down what my issue is. Given that this package is probably redundant, I'll go ahead and close it out.

**Comment by kaushalmodi** [comment]
I just have `desktop-restore-frames` at its default non-nil value. Another important thing for my emacsclient workflow is to load `desktop` after a second after my `init.el` finishes loading. Then I do `(desktop-save-mode 1)` , followed by `(desktop-read)`. My full desktop setup is [here][1].

[1]: https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-desktop.el

**Comment by aaronjensen** [comment]
@kaushalmodi Thank you for sharing your setup. Seeing your setup and the various workarounds/comments in it, it makes me feel like I'll probably just continue using my package which does one thing and does it well. I'd rather not take the time to try and pare down what `desktop-save-mode` does and work around its issues with my existing setup.

I'll keep my package available on github. It'd be nice to have it in MELPA, but I understand if it wouldn't be acceptable. /cc @purcell

**Comment by aaronjensen** [comment]
I was able to get this working for myself with:

```elisp
  (setq desktop-globals-to-save '()
        desktop-files-not-to-save ".*"
        desktop-buffers-not-to-save ".*"
        desktop-save t)
  (when (window-system)
    (desktop-save-mode)
    (desktop-read))
```

Thanks for the pointers @kaushalmodi and @purcell

**Comment by purcell** [comment]
Nice!

**Comment by edkolev** [comment]
Do you guys happen to know if `desktop-save-mode` can skip saving/restoring the color theme?

If it's not possible, I think this package might be useful.

**Comment by kaushalmodi** [comment]
`desktop-save-mode` does not save the theme for me.

**Comment by edkolev** [comment]
For me, using the configuration by aaronjensen pasted above, it saves stuff such as:
```
...
(foreground-color . "#655370")
(background-color . "#fbf8ef")
(background-mode . light)
(cursor-color . "#100a14")
...
```
in the .emacs.desktop file.

Seems like this is produced by `(frameset-save ...)` from frameset.el though, not by desktop.el.

**Pull request closed without merging**
