### PR TITLE
Add recipe for kkp

### PR DESCRIPTION
**Pull request by benjaminor**
### Brief summary of what the package does

kkp adds support for the [Kitty Keyboard Protocol (KKP)](https://sw.kovidgoyal.net/kitty/keyboard-protocol) to Emacs.

### Direct link to the package repository

https://github.com/benjaminor/kkp

### Your association with the package

Owner/Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`kkp.el` with byte-compile using Emacs 28.1:
```
kkp.el:457:6: Warning: define-key called with 4 arguments, but accepts only 3
```

`kkp.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- kkp.el#L202: It's safer to sharp-quote function names; use `#'`
```
Very minor, but e.g. `(apply #'concat args)`

Package and license:
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to kkp.el

**Comment by benjaminor** [comment]
Thanks for the review! I addressed your remarks in the latest commits.

**Comment by progfolio** [comment]
Could this be converted to a global minor mode?
It looks like the functionality would fit the bill and it would make it easier for users to enable/disable the functionality.

**Comment by riscy** [comment]
@progfolio is absolutely right -- functions like `kkp-enable`, `kkp-disable`, and their `-in-terminal` variants point very much to a global minor mode that can be toggled off and on using the typical Emacs idioms.

**Comment by benjaminor** [comment]
Alright, I added a global minor mode `global-kkp-mode`, but kept the `-in-terminal` commands (alas no buffer-local minor mode). This terminal feature does not map well onto a buffer-local mode, as one buffer could be open in multiple terminals where one terminal supports kkp but another one does not.

I don't think it's possible to have a terminal-local mode, at least I did not find any documentation on it.

**Comment by riscy** [comment]
I see your argument.  In light of that I think you should feel free to go with consistency between the two modes of enabling if you want -- I'll merge now and leave that to you.

Also, welcome to MELPA. :)

**Pull request merged**
