### PR TITLE
Add recipe for ox-rss.

### PR DESCRIPTION
**Pull request by BenedictHW**
Summary: RSS 2.0 Back-End for Org Export Engine
Link: https://gitlab.com/nsavage/ox-rss
Association: User
Communication: Maintainer notified at
https://gitlab.com/nsavage/ox-rss/-/issues/1

-------

### Brief summary of what the package does

This library implements an RSS 2.0 back-end for Org exporter, based on the
`html' back-end. It requires Emacs 24.1 at least. It provides two commands for
export, depending on the desired output: org-rss-export-as-rss' (temporary
buffer) and org-rss-export-to-rss' (as a ".xml" file).

### Direct link to the package repository

https://gitlab.com/nsavage/ox-rss

### Your association with the package

I am not the maintainer but an enthusiastic user! It used to be part of
org-contrib but was moved to it's own separate repository.

https://git.sr.ht/~bzg/org-contrib/log/release_0.4

I have notified the maintainer of this request for MELPA addition.

https://gitlab.com/nsavage/ox-rss/-/issues/1

I've NOT modified the package in any way for MELPA.

### Relevant communications with the upstream package maintainer

None needed to the best of my knowledge.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

``` shell
ben@BHW-THINKPAD:~/melpa$ make recipes/ox-rss
 • Building package ox-rss ...
Package: ox-rss
Fetcher: gitlab
Source:  https://gitlab.com/nsavage/ox-rss.git

Cloning https://gitlab.com/nsavage/ox-rss.git to /home/ben/melpa/working/ox-rss/
Checking out 80b5001c3d1c10b578d799bd8ff49e9267a2d5ff
Built ox-rss in 1.208s, finished at 2023-01-05T04:43:30+0000
 ✓ Success:
 16K -rw-r--r-- 1 ben ben 15K Jan  4 23:43 packages/ox-rss-20210605.1055.el
4.0K -rw-r--r-- 1 ben ben 345 Jan  4 23:43 packages/ox-rss-20210605.1055.entry
```

### CODE REVIEW

**Comment by BenedictHW** [comment]
And thanks for taking the time to maintain MELPA :). Have a blessed 2023.

**Comment by riscy** [comment]
Thank you for this.  I see this package is also currently on the emacsmirror: https://github.com/emacsmirror/ox-rss and it would be a good fit to be indexed in MELPA.  In the meantime, here's a quick first pass --

`ox-rss.el` with byte-compile using Emacs 28.1:
```
ox-rss.el:257:27: Warning: `org-bracket-link-regexp' is an obsolete variable
    (as of 9.3); use `org-link-bracket-re' instead.
```

`ox-rss.el` with checkdoc 0.6.2:
```
ox-rss.el:290: Argument `headline' should appear (as HEADLINE) in the doc string
ox-rss.el:323: Argument `info' should appear (as INFO) in the doc string
ox-rss.el:382: Argument `contents' should appear (as CONTENTS) in the doc string
ox-rss.el:391: Argument `contents' should appear (as CONTENTS) in the doc string
```

`ox-rss.el` with package-lint 20221003.1636:
```
44 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
77:10: error: You should depend on (emacs "24.4") if you need `ox-html'.
82:0: error: "org-export-rss" doesn't start with package's prefix "ox-rss".
117:1: error: You should depend on (emacs "24.4") if you need `org-export-define-derived-backend'.
126:3: error: You should depend on (emacs "24.1") if you need `org-open-file'.
171:5: error: You should depend on (emacs "24.4") if you need `org-icalendar-create-uid'.
173:3: error: You should depend on (emacs "24.4") if you need `org-export-to-buffer'.
199:5: error: You should depend on (emacs "24.4") if you need `org-icalendar-create-uid'.
201:18: error: You should depend on (emacs "24.4") if you need `org-export-output-file-name'.
203:5: error: You should depend on (emacs "24.4") if you need `org-export-to-file'.
217:6: error: You should depend on (emacs "24.4") if you need `org-icalendar-create-uid'.
221:7: error: You should depend on (emacs "24.4") if you need `org-icalendar-create-uid'.
224:3: error: You should depend on (emacs "24.1") if you need `org-publish-org-to'.
233:10: error: You should depend on (emacs "24.4") if you need `org-export-get-relative-level'.
234:7: error: You should depend on (emacs "24.4") if you need `org-export-data-with-backend'.
235:13: error: You should depend on (emacs "24.3") if you need `org-element-property'.
236:21: error: You should depend on (emacs "24.4") if you need `org-export-data'.
239:18: error: You should depend on (emacs "24.4") if you need `org-export-data'.
241:18: error: You should depend on (emacs "24.4") if you need `org-export-get-headline-number'.
244:16: error: You should depend on (emacs "24.3") if you need `org-element-property'.
245:15: error: You should depend on (emacs "26.1") if you need `org-export-get-reference'.
247:8: error: You should depend on (emacs "24.3") if you need `org-element-property'.
248:17: error: You should depend on (emacs "24.3") if you need `org-element-property'.
250:27: error: You should depend on (emacs "24.4") if you need `string-empty-p'.
253:9: error: You should depend on (emacs "24.1") if you need `org-time-string-to-time'.
255:12: error: You should depend on (emacs "24.3") if you need `org-element-property'.
260:6: error: You should depend on (emacs "24.3") if you need `org-element-property'.
271:13: error: You should depend on (emacs "24.3") if you need `org-element-property'.
272:6: error: You should depend on (emacs "24.3") if you need `org-element-property'.
294:8: error: You should depend on (emacs "24.3") if you need `org-element-property'.
296:14: error: You should depend on (emacs "24.3") if you need `org-element-property'.
325:10: error: You should depend on (emacs "24.4") if you need `org-export-data'.
326:10: error: You should depend on (emacs "24.4") if you need `org-export-data'.
329:14: error: You should depend on (emacs "24.4") if you need `org-export-data'.
331:16: error: You should depend on (emacs "24.4") if you need `org-export-data'.
337:10: error: You should depend on (emacs "24.3") if you need `url-encode-url'.
378:3: error: You should depend on (emacs "24.4") if you need `org-html-encode-plain-text'.
379:4: error: You should depend on (emacs "24.4") if you need `org-timestamp-translate'.
384:18: error: You should depend on (emacs "24.4") if you need `org-html-encode-plain-text'.
385:11: error: You should depend on (emacs "24.4") if you need `org-export-activate-smart-quotes'.
405:22: error: You should depend on (emacs "24.3") if you need `org-element-at-point'.
406:15: error: You should depend on (emacs "24.3") if you need `org-element-property'.
408:13: error: You should depend on (emacs "24.1") if you need `org-entry-get'.
410:7: error: You should depend on (emacs "24.1") if you need `org-set-property'.
```
I think the nag on line 82 is a false positive (I can never keep the org-ecosystem's prefix conventions straight in my head :)

`ox-rss.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ox-rss.el#L3: Have you done the paperwork to assign this copyright?
- ox-rss.el#L251: Consider using %T instead of %H:%M:%S in time strings
- ox-rss.el#L330: Consider using %T instead of %H:%M:%S in time strings
```
I assume the answer to the line 3 lint is "yes" since this used to be a part of org-contrib.  All of the other lints from melpazoid are optional.

Package and license:
- Add a LICENSE file to the repository

**Comment by BenedictHW** [comment]
Good evening!

Yeah, I emailed some trivial patches to Nick Savage (current maintainer) who mentioned he does not use ox-rss anymore but was willing to apply the patches or to make me the maintainer. I made a fork with the suggested changes made as suggested by the linters. The new fork lives at:

https://github.com/BenedictHW/ox-rss

Hopefully Nick can confirm this. Either way, please let me know if there is anything else I can do to help.

Cheers,

**Comment by riscy** [comment]
This all looks above board, but I'll mention @NickSavage here so that he gets a notification, since it would be best if we could get a quick confirmation.

As far as the MELPA checklist goes, everything looks good -- and when we merge this, your package will replace the [version that's kept on emacsmirror](https://github.com/emacsmirror/ox-rss).

**Comment by NickSavage** [comment]
Hi all, I can confirm that I've spoken with Benedict about this, and that his repo should be the source of truth for this. I'm going to update the README on my version to point there.

Thanks for all your efforts on this!

**Comment by riscy** [comment]
Thanks very much all - merging.

**Pull request merged**
