### PR TITLE
[add] receipe for multitran, initial import

### PR DESCRIPTION
**Pull request by zevlg**
### Brief summary of what the package does

Nifty Emacs interface to http://multitran.com

Supports multiple languages, including Esperanto, Latin and Luxembourgish.

### Direct link to the package repository

https://github.com/zevlg/multitran.el

### Your association with the package

I'm author

### Relevant communications with the upstream package maintainer

None

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

Also checked for byte compilation

### CODE REVIEW

**Comment by syohex** [comment]
- I suppose it is better to define major-mode `define-derived-mode` rather than `defun`
- https://github.com/zevlg/multitran.el/blob/e0954896d3b9a56a787eb740039a2fec1d9ee77a/multitran.el#L600 . `current-word` returns `nil`, then the package searches `nil` word. Is it intended behavior ?

**Comment by syohex** [comment]
BTW please use `x` instead of `*` for check-box. This is GFM specification.

**Comment by zevlg** [comment]
thanks, I've committed suggestions you made - https://github.com/zevlg/multitran.el/commit/bc174d031e9649793bc8759a928605d85fb69ff3

**Comment by purcell** [comment]
Thanks. Sent you https://github.com/zevlg/multitran.el/pull/2.

However, you should also fix the face definitions: instead of defining new colour specs, you should inherit existing faces (e.g. `:inherit comment`, `:inherit link` etc.) so that the faces look good with all existing themes.

**Comment by zevlg** [comment]
@purcell nice suggestion about faces definition, `shadow' and `link' quite suits

**Comment by zevlg** [comment]
Pushed faces related changes - https://github.com/zevlg/multitran.el/commit/0a18683644b63aaf9a55a433c23ff4c83bceb915

**Comment by purcell** [comment]
Nice, thanks.

**Pull request merged**
