### PR TITLE
Adding the package visual-replace.

### PR DESCRIPTION
**Pull request by szermatt**
### Brief summary of what the package does

Visual Replace provides a nicer interface for query-replace and replace-string on Emacs than the built-in one.

The main improvements are:

* The prompt of Visual Replace includes both the text to be replaced and the replacement. This makes it easier to craft possibly complex regular expression search and replace.

* You can modify the scope and type of the search-and-replace command.

* You can see what is going to be modified as you edit the command arguments.

Visual Replace is really just an interface for the existing query and replace mechanisms built into Emacs, that is, the actual replacements are always done by the standard Emacs commands.

### Direct link to the package repository

https://github.com/szermatt/visual-replace/

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

- GPL 2.0 is not compatible with the license used by Emacs.  See [here](https://github.com/johannes-mueller/company-wordfreq.el/issues/6) for more details.
- visual-replace.el:1400: First line is not a complete sentence (minor but actually you've quoted the entire variable plus the period, which will create an invalid hyperlink in the online help)
- Reminder: ensure GitHub release 0.2 is up-to-date with your current code and `Package-Version`

**Comment by szermatt** [comment]
Thanks for the reply ! 

> Thanks for this. Quick first pass -
> 
>     * GPL 2.0 is not compatible with the license used by Emacs.  See [here](https://github.com/johannes-mueller/company-wordfreq.el/issues/6) for more details.

Switched to GPL 3 or later. It was meant to be "2 or later", so redistributing even older versions of the code under GPL 3, if needed, shouldn't be a problem either.

> 
>     * visual-replace.el:1400: First line is not a complete sentence (minor but actually you've quoted the entire variable plus the period, which will create an invalid hyperlink in the online help)

Fixed. 

> 
>     * Reminder: ensure GitHub release 0.2 is up-to-date with your current code and `Package-Version`

Release 0.2 is in the past, the code that's currently in the github repository is meant to be the next version in development, it has additional fixes and features already. Is it the wrong way of handling versioning with mepla?

In that situation, should I re-release 0.2 ? Delete release 0.2? Make a new release (0.3)? 

I'm happy to do whatever is needed with the release I just don't understand.

**Comment by riscy** [comment]
I'm still trying to figure out the best messaging I can give, but the thread where this originates is here:

https://github.com/melpa/melpa/pull/9074#issuecomment-2381583577

Basically the issue is that we've fixed some things (like the license in this particular case) but release 0.2 still exists.  When we merge this, MELPA stable will reach out and grab the 0.2 release of your code, not the latest version.

I'd just make a new release.  I might even call it 1.0.0 because a license change is a non-forward-compatible change in theory (but probably not in practice) but you can go with whatever version scheme is best for the project.

**Comment by szermatt** [comment]
I think I understand now. Thank you!

I created release 1.0 for MELPA stable. Now was a good time for that, in any cases.

**Comment by riscy** [comment]
Thanks a ton for accommodating. :)

**Comment by szermatt** [comment]
Thank you!

**Pull request merged**
