### PR TITLE
Add lavenderless-theme

### PR DESCRIPTION
**Pull request by lthms**
### Brief summary of what the package does

`lavenderless-theme` is inspired by [`lavender-theme`](https://github.com/emacsfodder/emacs-lavender-theme) and is based on the [`colorless-themes` macro](https://git.sr.ht/~lthms/colorless-themes.el), which has been added to melpa for quite some time now (#6075).

### Direct link to the package repository

All my “colorless themes” are located in the `colorless-themes` repository: https://git.sr.ht/~lthms/colorless-themes.el

### Your association with the package

I am the author and maintainer of both `lavenderless-theme` and `colorless-themes`.

### Relevant communications with the upstream package maintainer

The logic of this recipe is exactly the same as `nordless-theme` (see #6339 if interested).

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
### lavenderless-theme.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
- Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems)
- Lexical binding has been enabled
- No issues! 💯

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191220.419):
```
23:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```

Other static checks/suggestions:
- lavenderless-theme.el#L16: Prefer `https` over `http` (if possible)

**Comment by lthms** [comment]
Hi @riscy and thanks for this review. Just to be sure, regarding the warning of `package-lint-current-buffer`: this is a warning I basically have all the time, and I guess I could change `theme` by `faces` (but AFAIK `nordless-theme` also has `theme` as keyword and it was not a problem.

Also, I have modified the license text to redirect to gnu.org using `https://`.

Again, thanks!

**Comment by riscy** [comment]
Great, thanks!  I'll merge this now.

**Comment by lthms** [comment]
Thanks!

**Pull request merged**
