### PR TITLE
add code-compass recipe

### PR DESCRIPTION
**Pull request by ag91**
### Brief summary of what the package does

This supports developers using a Git repository to analyze (visually) the health and complexity of their work via the repository history. 

### Direct link to the package repository

https://github.com/ag91/code-compass
### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`code-compass.el` with byte-compile using Emacs 28.1:
```
code-compass.el:496:40: Warning: Unused lexical variable
    `browse-url-generic-program'
In code-compass-show-code-churn-sync:
code-compass.el:754:45: Warning: Unused lexical variable `it'
In code-compass--show-coupled-files:
code-compass.el:933:48: Warning: Unused lexical variable `it'
code-compass.el:947:69: Warning: Unused lexical variable `it'
In code-compass--insert-authors-colors-in-file:
code-compass.el:1040:68: Warning: Unused lexical argument `repository'
In code-compass--get-analysis-as-string-from-csv:
code-compass.el:1224:66: Warning: Unused lexical argument `repository'
In code-compass-show-fragmentation-sync:
code-compass.el:1264:70: Warning: Unused lexical variable `it'
In code-compass-word-analysis-region-graph:
code-compass.el:1383:20: Warning: Unused lexical variable `it'
In code-compass--get-matching-coupled-files:
code-compass.el:1484:41: Warning: Unused lexical variable `it'
code-compass.el:1479:85: Warning: Unused lexical variable `it'
In code-compass--open-slack-from-email:
code-compass.el:1543:31: Warning: reference to free variable
    `slack-current-team'
In code-compass-slack-main-contributor:
code-compass.el:1559:29: Warning: reference to free variable
    `slack-current-team'
In code-compass-show-raw-csv:
code-compass.el:1762:49: Warning: Unused lexical variable `it'
In end of data:
code-compass.el:1552:10: Warning: the function `slack-team-users' is not known
    to be defined.
code-compass.el:1545:7: Warning: the function
    `slack-create-user-profile-buffer' is not known to be defined.
code-compass.el:1544:6: Warning: the function `slack-buffer-display-im' is not
    known to be defined.
```

`code-compass.el` with checkdoc 0.6.2:
```
code-compass.el:889: First sentence should end with punctuation
code-compass.el:482: Messages should start with a capital letter
code-compass.el:784: Messages should start with a capital letter
code-compass.el:984: Messages should start with a capital letter
code-compass.el:1036: Messages should start with a capital letter
code-compass.el:1122: Messages should start with a capital letter
code-compass.el:1174: Messages should start with a capital letter
```

`code-compass.el` with package-lint 20221003.1636:
```
48 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
7:103: error: Package url is not installable. (I think this and vc come with emacs??)
7:103: warning: Use a properly versioned dependency on "url" if possible.
7:107: error: Package vc is not installable.
7:107: warning: Use a properly versioned dependency on "vc" if possible.
312:0: error: Aliases should start with the package's prefix "code-compass".
337:0: error: Aliases should start with the package's prefix "code-compass".
384:11: error: You should depend on (emacs "28.1") if you need `length>'.
409:0: error: Aliases should start with the package's prefix "code-compass".
562:0: error: Aliases should start with the package's prefix "code-compass".
573:0: error: Aliases should start with the package's prefix "code-compass".
582:0: error: Aliases should start with the package's prefix "code-compass".
657:0: error: Aliases should start with the package's prefix "code-compass".
668:0: error: Aliases should start with the package's prefix "code-compass".
711:0: error: Aliases should start with the package's prefix "code-compass".
736:0: error: Aliases should start with the package's prefix "code-compass".
758:0: error: Aliases should start with the package's prefix "code-compass".
766:0: error: Aliases should start with the package's prefix "code-compass".
812:0: error: Aliases should start with the package's prefix "code-compass".
820:0: error: Aliases should start with the package's prefix "code-compass".
918:0: error: Aliases should start with the package's prefix "code-compass".
931:0: error: Aliases should start with the package's prefix "code-compass".
966:0: error: Aliases should start with the package's prefix "code-compass".
1007:0: error: Aliases should start with the package's prefix "code-compass".
1017:0: error: Aliases should start with the package's prefix "code-compass".
1080:58: error: You should depend on (emacs "28.1") if you need `length>'.
1091:0: error: Aliases should start with the package's prefix "code-compass".
1104:0: error: Aliases should start with the package's prefix "code-compass".
1146:0: error: Aliases should start with the package's prefix "code-compass".
1156:0: error: Aliases should start with the package's prefix "code-compass".
1205:0: error: Aliases should start with the package's prefix "code-compass".
1215:0: error: Aliases should start with the package's prefix "code-compass".
1281:0: error: Aliases should start with the package's prefix "code-compass".
1287:0: error: Aliases should start with the package's prefix "code-compass".
1348:0: error: Aliases should start with the package's prefix "code-compass".
1356:0: error: Aliases should start with the package's prefix "code-compass".
1366:0: error: Aliases should start with the package's prefix "code-compass".
1374:0: error: Aliases should start with the package's prefix "code-compass".
1385:0: error: Aliases should start with the package's prefix "code-compass".
1469:0: error: Aliases should start with the package's prefix "code-compass".
1523:0: error: Aliases should start with the package's prefix "code-compass".
1562:0: error: Aliases should start with the package's prefix "code-compass".
1656:0: error: Aliases should start with the package's prefix "code-compass".
1667:0: error: Aliases should start with the package's prefix "code-compass".
1687:0: error: Aliases should start with the package's prefix "code-compass".
1693:0: error: Aliases should start with the package's prefix "code-compass".
1748:0: error: Aliases should start with the package's prefix "code-compass".
1771:0: error: Aliases should start with the package's prefix "code-compass".
```

`code-compass.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- code-compass.el#L330: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L597: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1044: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1277: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1334: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1453: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L312: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L337: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L409: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L562: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L573: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L582: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L657: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L668: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L711: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L736: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L758: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L766: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L812: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L820: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L918: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L931: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L966: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1007: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1017: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1091: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1104: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1146: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1156: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1205: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1215: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1281: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1287: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1348: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1356: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1366: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1374: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1385: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1469: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1523: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1562: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1656: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1667: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1687: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1693: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1748: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1771: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1453: Loading a package should rarely add hooks; leave this to the users to do in their configs, or add a setup function or minor mode
- code-compass.el#L1695: Loading a package should rarely add hooks
- code-compass.el#L328: Consider using %F instead of %Y-%m-%d in time strings
- code-compass.el#L908: No `format` required; `error` takes an f-string
- code-compass.el#L1468: No `format` required; `message` takes an f-string
- code-compass.el#L1494: `concat` may be unneeded; `insert` can take multiple arguments
- code-compass.el#L1769: `concat` may be unneeded; `insert` can take multiple arguments
```

**Comment by ag91** [comment]
`Aliases should start with the package's prefix "code-compass`

I left these for backwards compatibility as I am not sure if users have switched to the new namespace: do I need to remove those aliases or can I hide that warning somehow?

I didn't know about melpazoid, thanks!

**Comment by riscy** [comment]
Hi :)

> can I hide that warning somehow?

You can use `define-obsolete-function-alias` instead of `defalias` and that should make package-lint happy, as well as inform your users that it's time to move on.

**Comment by ag91** [comment]
just a ping: am I expected to do something for this to go forward?

**Comment by riscy** [comment]
Hello - when you've had a chance to fix/address the issues above, mention them here and I'll know it's time (see CONTRIBUTING.org for the finer points).  Here's the latest, which I believe overlaps with some of the above:

`code-compass.el` with byte-compile using Emacs 28.1:
```
code-compass.el:515:40: Warning: Unused lexical variable
    `browse-url-generic-program'
In code-compass-show-code-churn-sync:
code-compass.el:790:45: Warning: Unused lexical variable `it'
In code-compass--get-coupling-alist-sync:
code-compass.el:887:57: Warning: Unused lexical variable `it'
In code-compass--generate-list-authors-colors:
code-compass.el:1098:35: Warning: Use -zip-pair instead of -zip to get a list
    of pairs
In code-compass-show-fragmentation-sync:
code-compass.el:1314:70: Warning: Unused lexical variable `it'
In code-compass-word-analysis-region-graph:
code-compass.el:1433:20: Warning: Unused lexical variable `it'
In code-compass--get-matching-coupled-files:
code-compass.el:1539:41: Warning: Unused lexical variable `it'
code-compass.el:1534:85: Warning: Unused lexical variable `it'
In code-compass--open-slack-from-email:
code-compass.el:1598:31: Warning: reference to free variable
    `slack-current-team'
In code-compass-slack-main-contributor:
code-compass.el:1614:29: Warning: reference to free variable
    `slack-current-team'
In code-compass-show-raw-csv:
code-compass.el:1831:49: Warning: Unused lexical variable `it'
In end of data:
code-compass.el:1748:65: Warning: the function `file-name-parent-directory' is
    not known to be defined.
code-compass.el:1607:10: Warning: the function `slack-team-users' is not known
    to be defined.
code-compass.el:1600:7: Warning: the function
    `slack-create-user-profile-buffer' is not known to be defined.
code-compass.el:1599:6: Warning: the function `slack-buffer-display-im' is not
    known to be defined.
```

`code-compass.el` with checkdoc 0.6.2:
```
code-compass.el:501: Messages should start with a capital letter
code-compass.el:820: Messages should start with a capital letter
code-compass.el:1027: Messages should start with a capital letter
code-compass.el:1079: Messages should start with a capital letter
code-compass.el:1165: Messages should start with a capital letter
code-compass.el:1217: Messages should start with a capital letter
```

`code-compass.el` with package-lint 20230315.1052:
```
1 issue found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
```
(Debatable, but the current summary looks like a tag line instead of a summary.)

`code-compass.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- code-compass.el#L343: It's safer to sharp-quote function names; use `#'`
- code-compass.el#L1523: No `format` required; `message` takes an f-string
```

Stderr output while compiling/loading:
```
code-compass.el: Warning: Use -zip-pair instead of -zip to get a list of pairs
```

**Comment by ag91** [comment]
hi, thanks for checking again. I addressed the ones I could act upon just now.
Checkdock's ones seem noise, probably the regexp used is conflicting with my code.
 Same for `Warning: Unused lexical variable `it'`, my code is using those.
Slack features are protected by an if-else (eg, `slack-team-users`).
Again the tool expects the let variable `browse-url-generic-program` to be used in the body, but I set to change Emacs behavior: no action there either.

So I don't think I have anything else to do at this point, unless I am missing something.

**Comment by riscy** [comment]
Here's the latest with a few more details --
`code-compass.el` with byte-compile using Emacs 28.1:
```
code-compass.el:515:40: Warning: Unused lexical variable
    `browse-url-generic-program'
In code-compass-show-code-churn-sync:
code-compass.el:790:45: Warning: Unused lexical variable `it'
In code-compass--get-coupling-alist-sync:
code-compass.el:887:57: Warning: Unused lexical variable `it'
In code-compass-show-fragmentation-sync:
code-compass.el:1318:70: Warning: Unused lexical variable `it'
In code-compass-word-analysis-region-graph:
code-compass.el:1437:20: Warning: Unused lexical variable `it'
In code-compass--get-matching-coupled-files:
code-compass.el:1545:41: Warning: Unused lexical variable `it'
code-compass.el:1540:85: Warning: Unused lexical variable `it'
In code-compass--open-slack-from-email:
code-compass.el:1604:31: Warning: reference to free variable
    `slack-current-team'
In code-compass-slack-main-contributor:
code-compass.el:1620:29: Warning: reference to free variable
    `slack-current-team'
In code-compass-show-raw-csv:
code-compass.el:1854:49: Warning: Unused lexical variable `it'
In end of data:
code-compass.el:1613:10: Warning: the function `slack-team-users' is not known
    to be defined.
code-compass.el:1606:7: Warning: the function
    `slack-create-user-profile-buffer' is not known to be defined.
code-compass.el:1605:6: Warning: the function `slack-buffer-display-im' is not
    known to be defined.
```
You can solve the "unused lexical variable" and missing slack- functions with the following bookkeeping block at the top of your code:
```elisp
(defvar browse-url-generic-program)
(defvar slack-current-team)
(declare-function slack-team-users "ext:slack.el")
(declare-function slack-create-user-profile-buffer "ext:slack.el")
(declare-function slack-buffer-display-im "ext:slack.el")
```
I'm not an experienced user of dash *at all* but I think your warnings around unused lexical `it`s are due to abusing `-->` as a `progn`, for example:
```elisp
   (--> repository
        (code-compass-produce-git-report it nil date)
        (code-compass--run-code-maat analysis it)
        (find-file (concat "./" analysis ".csv")))
```
isn't actually threading the value into the eventual `find-file`,  so it should just be:
```elisp
   (--> repository
        (code-compass-produce-git-report it nil date)
        (code-compass--run-code-maat analysis it))
   (find-file (concat "./" analysis ".csv"))
```

Or this form
```elisp
   (--> repository
        (code-compass-produce-git-report it nil)
        code-compass--produce-code-maat-coupling-report
        (code-compass--get-analysis-as-string-from-csv "coupling")
        (code-compass--add-filename-to-analysis-columns repository it)
        (--map (s-split "," it) (cdr it))))
```
is ignoring the return value of `code-compass--produce-code-maat-coupling-report` in the middle of the chain (we really just care about its side effect, which is to run a shell command that produces coupling.csv?)
```elisp
   (--> repository
        (code-compass-produce-git-report it nil)
        code-compass--produce-code-maat-coupling-report)
   (--> (code-compass--get-analysis-as-string-from-csv "coupling")
        (code-compass--add-filename-to-analysis-columns repository it)
        (--map (s-split "," it) (cdr it)))))
```

Like I said, I'm not well-versed in dash, but this seems to be what's going on and the above two changes are cleaning up the byte-compile.  I think it's also clearer what's going on this way, too.

You're right that the checkdoc regex is just looking for function names that end in `error`; you could rename if you wanted a clean checkdoc, but not a blocker.

Package-lint has some new ones too -- `code-compass.el` with package-lint 20230315.1052:
```
2 issues found:
1:0: warning: The package summary is too long. It should be at most 60 characters.
1:0: warning: The package summary should start with an uppercase letter or a digit.
```

**Comment by ag91** [comment]
thanks for explaining those to me: I totally didn't know about declaring variables to satisfy the byte compiler! That is useful.
I handled all the errors I could see following your suggestions: cool!

**Comment by riscy** [comment]
Right on.  Thank you for accommodating -- merging!

**Pull request merged**
