### PR TITLE
Add receipe for guid.

### PR DESCRIPTION
**Pull request by sthilaid**
### Brief summary of what the package does

A simple guid generator.

### Direct link to the package repository

https://github.com/sthilaid/guid

### Your association with the package

Author / maintainer

### Relevant communications with the upstream package maintainer

This is a follow up from the pull request: https://github.com/melpa/melpa/pull/8773

I don't know how to fix most of the package lint warnings such as adding depencies on certain version of emacs
There are some docstrings warning/errors that I couldn't care to fix either. Hopefully these are not showstoppers...

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

- No byte-compile error 🎉

`guid.el` with checkdoc (0.6.2)

```
guid.el:0: The first line should be of the form: ";;; package --- Summary"
guid.el:0: You should have a section marked ";;; Commentary:"
guid.el:2: You should have a section marked ";;; Code:"
guid.el:33: The footer should be: (provide 'guid)\n;;; guid.el ends here
guid.el:3: All variables and subroutines might as well have a documentation string
guid.el:19: First sentence should end with punctuation
guid.el:19: First line should be capitalized
guid.el:19: Argument `upcase?' should appear (as UPCASE?) in the doc string
guid.el:27: First sentence should end with punctuation
guid.el:27: First line should be capitalized
guid.el:27: Argument `upcase?' should appear (as UPCASE?) in the doc string
guid.el:20: Messages should start with a capital letter
guid.el:28: Messages should start with a capital letter
```

`guid.el` with package-lint (20230905.629)

```
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a ;;; Commentary section.
1:0: error: Package should have a Homepage or URL header.
1:0: error: package.el cannot parse this buffer: Wrong type argument: package-desc, nil
12:25: error: You should depend on (emacs "25.1") or the seq package if you need `seq-reduce'.
13:37: error: You should depend on (emacs "25.1") or the seq package if you need `seq-map'.
```

Package and license:

- None

**Comment by riscy** [comment]
Thanks for this.  I noticed you've got other PR(s) already open (#8796 #8797 #8798 #8799).  To split my review time evenly between authors, I try to do one PR at a time per author, but I promise I'll get to this when we resolve earlier PRs.

**Comment by alphapapa** [comment]
I'm afraid that this isn't a package in its current form at all.  As well, Emacs/Org already has this function built-in:
```
org-id-uuid is a native-compiled Lisp function in ‘org-id.el’.

(org-id-uuid)

Return string with random (version 4) UUID.
```
There is little-to-no value to having a tiny library like this added to MELPA, especially given the namespacing issues. 

@sthilaid If you feel like Emacs/Org is missing something like this, it would be much better to try to upstream improvements into them so that everyone can benefit without having to install yet-another-package.  MELPA tries to avoid the NPM-style problems.

**Comment by riscy** [comment]
Hi @sthilaid - per [this comment](https://github.com/melpa/melpa/pull/8796#issuecomment-1868583863) I'll close this and the PRs with issues you made around the same time.  But do remember that you can always re-open these (preferably one at a time) if you'd like to discuss further, and I'll be happy to help.

**Pull request closed without merging**
