### PR TITLE
add recipe for zeno-theme 

### PR DESCRIPTION
**Pull request by jbharat**
### Brief summary of what the package does

It's a new theme, dark and based on variations of blue colour.

### Direct link to the package repository

https://github.com/jbharat/zeno-theme

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, and sorry for the delay. Quick notes:

- Don't use camel or snake case in elisp, like `slantType` or `atlantis_green`, `fullBlack`. Use `kebab-case` instead. And certainly don't use a mix!
- Don't set font families directly, e.g. [here](https://github.com/jbharat/zeno-theme/blob/master/zeno-theme.el#L213). It doesn't work at all well across platforms. Instead, `:inherit` the built-in `'variable-pitch` face if that's the effect you want.

Looks good otherwise. :-)

**Comment by jbharat** [comment]
Thanks. You are right. I will make the  changes as per your comments.

**Comment by purcell** [comment]
Cool, just ping me here when done, and I'll take another look.

**Comment by jbharat** [comment]
I have changed all variables to kebab case and removed font family

**Comment by purcell** [comment]
Much nicer! :-)

Merging now.

**Pull request merged**
