### PR TITLE
frame-local recipe

### PR DESCRIPTION
**Pull request by sebastiencs**
### Brief summary of what the package does

Access variables local to a frame

### Direct link to the package repository

https://github.com/sebastiencs/frame-local

### Your association with the package

Author

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by xuchunyang** [comment]
@tarsius The build fails due to `package-build` now uses `cl-defmethod` thus requires Emacs 25 and Travis is using Emacs 24.5.

**Comment by DamienCassou** [comment]
This [has been fixed](https://github.com/melpa/package-build/issues/17). Can someone please run the test suite again on Travis?

**Comment by DamienCassou** [comment]
You have some comments written like this:

```emacs
(defun frame-local-set (name value &optional frame)
  "Set the symbol NAME's value to VALUE in the current frame.
If FRAME is non-nil, set the symbol in this frame.
```
I often see similar comments written like this instead:

```emacs
(defun frame-local-set (name value &optional frame)
  "Set the symbol NAME's value to VALUE in FRAME.
If FRAME is nil, set the symbol in current frame.
```

> Similar to `frame-local-set' but NAME doesn't need to be quoted.

should that be "*must not* be quoted" instead?

I find that code a bit weird:

```emacs
(setq frame-local--obarrays (delq frame frame-local--obarrays)
         frame-local--obarrays (delq obarray frame-local--obarrays)))
```

what about merging the 2 assignment into one like this (untested): `(setq frame-local--obarrays (delq obarray (delq frame frame-local--obarrays))))`

**Comment by tarsius** [comment]
> This has been fixed. Can someone please run the test suite again on Travis?

We had to wait a few hours for the Melpa `package-build` package to become available. Turns out there's another issue and we have to wait another few hours. But I locally tested with the Emacs version used by Melpa, so changes are good this fix is enough.

**Comment by sebastiencs** [comment]
@DamienCassou Thanks for the review. It's fixed now

**Comment by purcell** [comment]
Thanks - merged. Sorry for the very slow turnaround on this.

**Comment by basil-conto** [comment]
@sebastiencs Out of curiosity, what is the intended use-case for `frame-local` vs using [frame parameters](https://www.gnu.org/software/emacs/manual/html_node/elisp/Frame-Parameters.html), as suggested here: https://emacs.stackexchange.com/a/40852/15748 ?

**Comment by sebastiencs** [comment]
@basil-conto I was using frame parameters for [sidebar.el](https://github.com/sebastiencs/sidebar.el) but I've found out that when listing +2000 files, I was losing ~1 second to access the frame parameters.
I could probably solve the slowdown another way, but I have prefered to write `frame-local`, which creates an obarray for each frame, I think it is cleaner than using frame parameters, and definitely faster.
Also it doesn't pollute the frame parameters with potentially lots of variables.

If one don't care about theses criterias, I guess that frame parameters are good enough

**Comment by basil-conto** [comment]
@sebastiencs OK, thanks for the explanation. :)

**Pull request merged**
