### PR TITLE
Add recipe for hyperkitty package.

### PR DESCRIPTION
**Pull request by maxking**
### Brief summary of what the package does

Hyperkitty is an emacs based interface to read email archives hosted 
via [Hyperkitty archiver](https://hyperkitty.readthedocs.io/).

### Direct link to the package repository

https://github.com/maxking/hyperkitty.el

### Your association with the package

I am the author and maintainer of the package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by maxking** [comment]
I am trying to figure out if there is a way to declare a min version of Emacs somewhere to get the CI to pass, which is using  24.5.1.

**Comment by riscy** [comment]
> I am still trying to figure out why the CI is failing, it seems to be having issues with git commit object.

Don't worry about Travis, I think it needs some tlc.

**Comment by riscy** [comment]
Here's a quick pass:

### hyperkitty.el ###

byte-compile (using Emacs 27.1):
```
hyperkitty.el:323:7:Warning: assignment to free variable `email-highlights'
```
Also looks like it doesn't share your package's prefix.

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- hyperkitty.el#L78: It's safer to sharp-quote function names; use `#'`
- hyperkitty.el#L125: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- hyperkitty.el#L318: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- hyperkitty.el#L319: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- hyperkitty.el#L320: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- hyperkitty.el#L356: `read-string` prompts should often end with a space
- hyperkitty.el#L189: No `format` required; messages are already f-strings
- hyperkitty.el#L6: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading hyperkitty.el
Done.
```

### Package ###

- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to hyperkitty.el

**Comment by maxking** [comment]
@riscy thanks a lot for the review. I have made the changes you suggested in https://github.com/maxking/hyperkitty.el/pull/6 and https://github.com/maxking/hyperkitty.el/pull/7.

**Comment by riscy** [comment]
No problem -- looks good.  And, welcome to MELPA! :)

**Pull request merged**
