### PR TITLE
Add recipe for nael

### PR DESCRIPTION
**Pull request by mekeor**
### Brief summary of what the package does

Nael provides a humble major-mode for the Lean programming-language and theorem-prover.  It is a radical fork fo lean4-mode that aims to use Emacs' built-in facilities like Eglot, ElDoc and Project.

### Direct link to the package repository

https://codeberg.org/mekeor/nael

### Your association with the package

I am the author and maintainer.

Also note that I do have an active, valid, intact copyright-assignment to the FSF.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

What are your thoughts on https://github.com/melpa/melpa/pull/8106 ?  This PR has sat unresolved for some time, and it makes sense to me that - if you have resolved many of the issues with lean4-mode, that we call this lean4-mode.  ("nael.el" is strange and probably hampers discoverability; moreover it should probably be called `nael-mode` instead of just `nael`).

Minor license stuff -
- Invalid SPDX id `Apache-2.0, GPL-3.0-or-later`; check https://spdx.dev/ids/ - this is minor but SPDX actually defines boolean operators, and I believe in this case you should use OR (but correct me if I'm wrong)

**Comment by t-c-acc** [comment]
@mekeor, thank you so much, you possibly are the actual best :P

Alternative name suggestion: "leaner-mode" or "leaner4-mode"

**Comment by tani** [comment]
@mekeor Thank you for developing the charming project! I would like to ask you to reopen the issue to add nael-mode?

**Comment by dschrempf** [comment]
> Closing because Nael will be discontinued in favor of lean4-mode on which I'm beginning to work on, now that I got write-access to it.

Can you comment on this @mekeor? It seems that `nael-mode` is actively developed, while `lean4-mode` is not.

**Comment by mekeor** [comment]
I failed to contribute to Lean4-Mode because it's (almost) unmaintained. I went back to work on Nael instead. But it still lacks documentation and some features, to say the least.

**Pull request closed without merging**
