### PR TITLE
Add evil-goggles

### PR DESCRIPTION
**Pull request by edkolev**
### Brief summary of what the package does

Adds global minor mode `evil-goggles-mode`, which, when on, briefly shows a colored overlay to indicate what text will be affected. For example, `2 dd` will briefly show an overlay on the 2 lines which will be deleted before deleting them.

### Direct link to the package repository

https://github.com/edkolev/evil-goggles

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by edkolev** [comment]
This package depends on emacs 25 because of `funcall-interactively`. But I couldn't find a way to emulate this function for older emacsen.

I would appreciate if anyone can give me a hint how `funcall-interactively` can be emulated for emacs <25. Thanks.

**Comment by purcell** [comment]
Will `call-interactively` do the trick?

**Comment by edkolev** [comment]
I don't think so, `call-interactively` doesn't allow specifying the arguments. I guess the package will just have to depend on emacs 25.

**Comment by edkolev** [comment]
I had forgotten to autoload the minor mode, this is fixed now https://github.com/edkolev/evil-goggles/commit/ae066ce954410cb16d57dee4dba2892d943f468f

Please let me know if I can improve the PR in any way.

**Comment by purcell** [comment]
Thanks

**Comment by edkolev** [comment]
Great, thank you!

**Pull request merged**
