### PR TITLE
add pact-mode recipe

### PR DESCRIPTION
**Pull request by emilypi**
### Brief summary of what the package does

A major mode for editing Pact, a smart contract language, in Emacs. See http://kadena.io/pact.

### Direct link to the package repository

https://github.com/kadena-io/pact-mode

### Your association with the package

Maintainer, contributor, colleague of author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, and sorry for the slow turnaround. Quick notes:

- This package will bundle `pact-flycheck.el`, but that should be a separate package because it has opinionated and heavier-weight dependencies. So this recipe should have `:files ("pact-mode.el")`, there should be a separate `pact-flycheck` recipe with `:files ("pact-flycheck.el")`, and `pact-flycheck.el` should declare package dependencies on `flycheck` and `pact-mode`. Also note that `flycheck-pact` would be a better name, since it better reflects current conventions.
- [This version check](https://github.com/kadena-io/pact-mode/blob/5b334255212abf29890f01055f5abd5c28348efc/pact-mode.el#L89-L90) should be at the top level, or (better) simply removed. You should instead declare a package dependency on Emacs 24.3 - `package-lint` should have mentioned this when you ran it.
- You can drop the `progn` [here](https://github.com/kadena-io/pact-mode/blob/5b334255212abf29890f01055f5abd5c28348efc/pact-mode.el#L188)
- [Version variables](https://github.com/kadena-io/pact-mode/blob/5b334255212abf29890f01055f5abd5c28348efc/pact-mode.el#L37) are generally a bad idea. This one is already out of step with the file header. Just use the file header (and note that MELPA will insert a package version for you there).

Hope that helps!

**Comment by emilypi** [comment]
@purcell Thanks for the feedback Steve! No worries on the turnaround - I'll sort out your suggestions and come back today 😄

**Comment by emilypi** [comment]
@purcell All of your comments have been addressed. I've submitted the `flycheck-pact` recipe in a [separate PR](https://github.com/melpa/melpa/pull/5711).

**Comment by purcell** [comment]
Awesome, merged now. Welcome to MELPA. :tada:

**Comment by emilypi** [comment]
Thanks @purcell! Very stoked :)

**Pull request merged**
