### PR TITLE
Newspeak mode

### PR DESCRIPTION
**Pull request by danielsz**
Major mode for the newspeak language.
https://newspeaklanguage.org/

### Brief summary of what the package does

Provide facilities to edit Newspeak source code. 

### Direct link to the package repository

https://github.com/danielsz/newspeak-mode

### Your association with the package

Author and maintainer of package. 

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [ x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by danielsz** [comment]
Thank you for the pach. It's merged. Is there anything else?

**Comment by riscy** [comment]
Thanks for this and for catching everything on the checklist.  Suggestions:

- newspeak-mode.el#L130: Customizable variables shouldn't be private
- "1984" was an inspiration for the title of the language but I don't know whether it's appropriate to set as the "name" of the mode (I honestly can't see this affecting anything, but I thought I'd bring it up; some people prefer the whimsical stuff to be optional)
- Add a LICENSE file that GitHub can detect (e.g. no markup)
- Currently the license boilerplate in your elisp file is part of your `;;; Commentary` -- put it above the `;;; Commentary`
- Variable names in Emacs shouldn't be capitalized in code (e.g. COUNT); the capitalization _is_ used in documentation though

**Comment by danielsz** [comment]
Excellent suggestions. I've made the appropriate changes and merged everything. Thank you, Chris!

**Comment by riscy** [comment]
No problem. :)  I notice one more byte-compile in the latest, but after this should be a quick merge:

byte-compile (using Emacs 27.1):
```
newspeak-mode.el:310:62:Warning: reference to free variable `basic-indent'
```

**Comment by danielsz** [comment]
Fixed. Good catch. Sorry about that. Thank you, Chris.

**Comment by riscy** [comment]
Looks good!  Thanks. :)

**Comment by danielsz** [comment]
Thank you! 

I'm very grateful for your precious work.

**Pull request merged**
