### PR TITLE
Remove company-childframe

### PR DESCRIPTION
**Pull request by tumashu**
company-childframe has been renamed to company-posframe, removed.

### CODE REVIEW

**Comment by milkypostman** [comment]
Shouldn’t we rename the recipe then?

**Comment by tumashu** [comment]
company-posframe has been added many month ago

**Comment by tumashu** [comment]
https://github.com/melpa/melpa/blob/68c1203ae710e5f7af3f0e5e2877aba6deaf1ac8/recipes/company-posframe

**Comment by purcell** [comment]
Thanks

**Pull request merged**
