### PR TITLE
Add recipe for chatgpt-shell

### PR DESCRIPTION
**Pull request by tejasbubane**
### Brief summary of what the package does

A minimal ChapGPT Emacs shell.

### Direct link to the package repository

https://github.com/xenodium/chatgpt-shell

### Your association with the package

A contributor

### Relevant communications with the upstream package maintainer

https://github.com/xenodium/chatgpt-shell/pull/4

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Have you had a chance to check out the other [ChatGPT packages](https://melpa.org/#/?q=gpt) that have been added to MELPA?  It's worth describing how this package differs, since there have been a few of these lately.

Also note that your `Package-Requires` has to be all on one line, per package-lint:
```
8:0: error: Couldn't parse "Package-Requires" header: End of file during parsing: /workspace/pkg/melpazoid.el
```

Following that, here's a quick first pass --

`chatgpt-shell.el` with byte-compile using Emacs 28.1:
```
chatgpt-shell.el:49:1: Warning: defcustom for `chatgpt-shell-language-mapping'
    fails to specify type
In chatgpt-shell-interrupt:
chatgpt-shell.el:374:35: Warning: reference to free variable
    `chatgpt-shell--prompt-internal'
In chatgpt-shell--eval-input:
chatgpt-shell.el:405:42: Warning: reference to free variable
    `chatgpt-shell--prompt-internal'
In chatgpt-shell--write-reply:
chatgpt-shell.el:535:33: Warning: reference to free variable
    `chatgpt-shell--prompt-internal'
In chatgpt-shell--find-string-in-buffer:
chatgpt-shell.el:581:8: Warning: docstring wider than 80 characters
In chatgpt-shell--download-image:
chatgpt-shell.el:589:8: Warning: docstring wider than 80 characters
In chatgpt-shell--extract-commands-and-responses:
chatgpt-shell.el:637:27: Warning: reference to free variable
    `chatgpt-shell--prompt-internal'
In end of data:
chatgpt-shell.el:651:24: Warning: the function `js-json-mode' is not known to
    be defined.
```

`chatgpt-shell.el` with package-lint 20230315.1052:
```
4 issues found:
153:0: error: Aliases should start with the package's prefix "chatgpt-shell".
211:0: error: "dall-e-shell" doesn't start with package's prefix "chatgpt-shell".
228:0: error: "inferior-chatgpt-mode" doesn't start with package's prefix "chatgpt-shell".
387:12: error: You should depend on (emacs "28.1") if you need `json-available-p'.
```

`chatgpt-shell.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- chatgpt-shell.el#L384: It's safer to sharp-quote function names; use `#'`
- chatgpt-shell.el#L190: It's safer to sharp-quote function names; use `#'`
- chatgpt-shell.el#L191: It's safer to sharp-quote function names; use `#'`
```

**Comment by riscy** [comment]
It does seem to break `package-lint` and my own check script (melpazoid) -- presumably these need to get caught up to the package assembly code.

**Comment by xenodium** [comment]
Hi folks. Wasn't aware of this PR. I'm happy to address any issues highlighted here. I happen to have open #8479 (I'm the package author/owner btw).

**Comment by xenodium** [comment]
I'm sorry, I totally missed the mention in https://github.com/xenodium/chatgpt-shell/pull/4

Either way, I'm happy to address any pending issues. As far as I can tell, most issues are already addressed in the latest snapshot when I opened #8479

**Comment by tejasbubane** [comment]
Hi @xenodium, no worries I'll close this PR in favor of yours https://github.com/melpa/melpa/pull/8479

**Pull request closed without merging**
