### PR TITLE
Add livedown

### PR DESCRIPTION
**Pull request by shime**
### Brief summary of what the package does

Live offline Markdown previews.
### Direct link to the package repository

https://github.com/shime/emacs-livedown
### Your association with the package

I'm an author.
### Relevant communications with the upstream package maintainer

**None**
### Checklist
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR(https://github.com/shime/emacs-livedown/pull/7)

And
- Use `-` separator instead of `:` separator for [Emacs Lisp Coding Convention](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html#Coding-Conventions)
- No autoload cookie

**Comment by shime** [comment]
Merged your PR, changed the separator and added autoload cookies.

**Comment by purcell** [comment]
Thanks! A little more feedback from me:
- "for Emacs" in the package description is redundant and should be removed
- Similarly, don't use strings like `emacs-livedown`
- The parent group of the `livedown` custom group cannot be itself - instead, place it in one of the standard custom groups (`files`?)
- `livedown-autostart` is bogus, because the file may be loaded before that variable is set. Instead, you should define a global minor mode, which will automatically give you a place to start/stop the server
- These shell commands with `&` 
- When building command strings with `%s`, you need to use the `shell-quote-argument` unless you want bad things to happen when certain characters are found in file paths

Hope that helps!

**Comment by tarsius** [comment]
@shime Are you planing to make the suggested changes? We cannot merge this before you do, or explain why (some of that) is unnecessary/undesirable.

@purcell What's that supposed to mean?

> These shell commands with `&`

**Comment by purcell** [comment]
Hah, sorry. Those `livedown stop` shell commands seem to use `&` to suppress errors, but they could also lead to race conditions.

**Comment by tarsius** [comment]
It has been half a year and I am closing this now. Feel free to reopen when you have the time to finish this.

**Pull request closed without merging**
