### PR TITLE
Add pest-mode

### PR DESCRIPTION
**Pull request by ksqsf**
### Brief summary of what the package does

This package provides advanced support for Pest (a parser generator) grammar files.

### Direct link to the package repository

https://github.com/ksqsf/pest-mode

### Your association with the package

**Maintainer**

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```
 pest-mod…    52   1 error           Customization groups should not end in "-mode" unless that name would conflict with their parent group. (emacs-lisp-package)
```

1. Please consider adding your major-mode to interpreter-mode-alist like auto-mode-alist.
2. Please add `Keyword:` header
3. Please remove unneeded let
4. Please consider spliting flymake integration feature from core major-mode package.

**Comment by ksqsf** [comment]
Thanks to @conao3, these points have been addressed. 

I've updated the recipe and added `flymake-pest` and `flycheck-pest`.

**Comment by riscy** [comment]
Hello!  Sorry for the delay on this, but per CONTRIBUTING can you close this PR and open one PR for each recipe?

You will probably want them in the order in which they are required, so for example the first PR you open should be for pest-mode.  Then you'll need to add pest-mode to the `Package-Requires` in flymake-pest.el and flycheck-pest.el so that they can build and be tested.

On a quick glance, you're also missing a `Package-Requires` on flycheck for flycheck-pest.el, and here's one small checkdoc nag for your consideration:

checkdoc (using version 0.6.1):
```
Warning (emacs): 
flymake-pest.el:155: Lisp symbol `pest-input-mode' should appear in quotes
```

**Comment by ksqsf** [comment]
@riscy Sure. All done!

**Comment by riscy** [comment]
Nope, this is a fine PR now. :)  Stay tuned.

**Comment by riscy** [comment]
This looks good to me.  Some non-blocking suggestions:

Minor:
- pest-mode.el#L227: Consider `unless ...` instead of `when (null ...)`
- furthur -> further
- non-nill -> non-nil

**Comment by ksqsf** [comment]
Thanks!

**Pull request merged**
