### PR TITLE
Add ob-nim package

### PR DESCRIPTION
**Pull request by Lompik**
Org-mode source code interaction for the [nim](http://nim-lang.org) language

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- You should declare a dependency on `(cl-lib "0.5")`
- `:version "24.3"` in the defcustom is wrong
- There are 3 commits in the PR - would you be able to rebase the branch and force-push it to eliminate the unnecessary commits please?

**Comment by Lompik** [comment]
Thanks !

**Comment by tarsius** [comment]
@purcell Again, shall I just merge such things myself? (The raised issues have been addressed.)

**Comment by purcell** [comment]
Thanks, and yep @tarsius, feel free to merge in cases like this.

**Pull request merged**
