### PR TITLE
Added recipe for async-job-queue

### PR DESCRIPTION
**Pull request by owinebar**
Brief summary of what the package does

Direct link to the package repository

### Brief summary of what the package does

Manages a queue of async jobs by dispatching to a fixed number of slots.

### Direct link to the package repository

https://github.com/owinebar/emacs-async-job-queue

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by owinebar** [comment]
Hi, I'm resubmitting with a clean branch.  All previous feedback has been addressed AFAIK.

**Comment by riscy** [comment]
Thanks for this and for accommodating.  The latest I can see is a missing dependency on [queue](https://elpa.gnu.org/packages/queue.html) in your Package-Requires

**Comment by owinebar** [comment]
On Mon, Apr 24, 2023 at 3:06 PM Chris Rayner ***@***.***>
wrote:

> Thanks for this and for accommodating. The latest I can see is a missing
> dependency on queue <https://elpa.gnu.org/packages/queue.html> in your
> Package-Requires
>
You're right - I had a homebrew queue in there, then converted to the
existing package but forgot to add the dependency.

WIll make that change.

Lynn

**Comment by owinebar** [comment]
On Mon, Apr 24, 2023 at 6:35 PM Lynn Winebarger ***@***.***> wrote:
>
> On Mon, Apr 24, 2023 at 3:06 PM Chris Rayner ***@***.***> wrote:
>>
>> Thanks for this and for accommodating. The latest I can see is a missing dependency on queue in your Package-Requires
>
> You're right - I had a homebrew queue in there, then converted to the existing package but forgot to add the dependency.
>
> WIll make that change.

Ok, fixed the dependency and some bugs from making jobs able to
complete when the job finished rather than only at polling time.

Lynn

**Comment by riscy** [comment]
Thank you!  Here's the latest I see --

`async-job-queue.el` with byte-compile using Emacs 28.1:
```
async-job-queue.el:616:62: Warning: the function
    `async-job-queue-process-queue' is not known to be defined.
```

I had a look and I can't find this function defined anywhere, so I think the byte-compiler is onto something.

**Comment by owinebar** [comment]
I removed all the shorthands notation I was trying out after I noticed
package-install-from-buffer was removing the local variable block.  That
typo was the last one I removed.

I'm not sure why I hadn't caught it.  I'm actively using this package in
developing my "unboxed" package file-level install manager.  Cataloging all
the files in 2400 installed packages takes a minute or two, even with 32
async jobs processing 50 packages at a time.  But no more than a minute or
two.

**Comment by riscy** [comment]
Thanks!  Everything looks good to go.

**Pull request merged**
