### PR TITLE
Add recipes/terraform-doc

### PR DESCRIPTION
**Pull request by TxGVNN**
### Brief summary of what the package does

Look up the Terraform documentation on the homepage

### Direct link to the package repository

https://github.com/TxGVNN/terraform-doc

### Your association with the package

Maintainer

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by DamienCassou** [comment]
The fact that you have checked "I have confirmed some of these without doing them" is kind of a bad sign.

**Comment by TxGVNN** [comment]
> The fact that you have checked "I have confirmed some of these without doing them" is kind of a bad sign.

Oh, my mistake. I created 3 PR before, so this is like a habit. 
I almost tested it by myself then just tick without reading.

I will learn from experience. Thank you

**Comment by riscy** [comment]
- [This](https://github.com/TxGVNN/terraform-doc/blob/f353ae26a0c453b9204ca9b94ac6a2fafd862616/terraform-doc.el#L105) seems unusual, but maybe I'm missing something.  How come we need the `with-current-buffer` wrapper?
- If possible, you should prefer to write a loop like the following instead of using [`perform-replace`](https://github.com/TxGVNN/terraform-doc/blob/f353ae26a0c453b9204ca9b94ac6a2fafd862616/terraform-doc.el#L114) -- note that `perform-replace` echoes messages too, which isn't what you want:
  ```elisp
  (while (re-search-forward "foo[ \t]+bar" nil t)
    (replace-match "foobar" nil nil))
  ```
- [This](https://github.com/TxGVNN/terraform-doc/blob/f353ae26a0c453b9204ca9b94ac6a2fafd862616/terraform-doc.el#L106-L118) chunk and [this](https://github.com/TxGVNN/terraform-doc/blob/f353ae26a0c453b9204ca9b94ac6a2fafd862616/terraform-doc.el#L135-L146) chunk feel like they have quite a lot of repeated code.  Also, both feel like they should be pulled into their own function(s).  It will make the code easier to read, and since these contain a lot of (fragile) parsing logic, you want them to be easier to edit and update in isolation from other functions.
- None of the checkers complain about it due to transitive dependencies, but I would personally be leery about relying on e.g. `shr-render-region` being available without adding an explicit require on `shr`.

**Comment by TxGVNN** [comment]
Hi @riscy,

Thanks for your great comment,
I have updated the 4 points which you mentioned. Could you have a look?

**Comment by purcell** [comment]
Looks good now, merging - thanks!

**Pull request merged**
