### PR TITLE
Add package mu4e-marker-icons

### PR DESCRIPTION
**Pull request by stardiviner**
### Brief summary of what the package does

Display mu4e header markers with icons.

### Direct link to the package repository

https://github.com/stardiviner/mu4e-marker-icons

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thank you, looks good by the checklist (and good application of a global minor mode).  Some quick checks --

- mu4e-marker-icons.el#L12: Have you done the paperwork or is this copy-pasted?
- mu4e-marker-icons.el#L8: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)

**Comment by stardiviner** [comment]
> Thank you, looks good by the checklist (and good application of a global minor mode). Some quick checks --
> 
>     * mu4e-marker-icons.el#L12: Have you done the paperwork or is this copy-pasted?

Maybe I misunderstand your means. Does this means have I assigned FSF papers? If yes, Then Yes. I assigned FSF papers.
Is there some website can check this list?

> 
>     * mu4e-marker-icons.el#L8: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)

Modified.

**Comment by riscy** [comment]
> Does this means have I assigned FSF papers? If yes, Then Yes. I assigned FSF papers.

Yes, sometimes people have just copy pasted this line from another package and aren't aware they have to fill out specific paperwork to assign their copyright over to FSF.  Doing that paperwork is a requirement for adding a package to ELPA, for example, but not for MELPA.  Hopefully that clears it up? :)

>  Is there some website can check this list?

If you're referring to the list I pasted above, it is from some scripts I run here https://github.com/riscy/melpazoid

**Comment by stardiviner** [comment]
> > Does this means have I assigned FSF papers? If yes, Then Yes. I assigned FSF papers.
> 
> Yes, sometimes people have just copy pasted this line from another package and aren't aware they have to fill out specific paperwork to assign their copyright over to FSF. Doing that paperwork is a requirement for adding a package to ELPA, for example, but not for MELPA. Hopefully that clears it up? :)

Clear.

> 
> > Is there some website can check this list?
> 
> If you're referring to the list I pasted above, it is from some scripts I run here https://github.com/riscy/melpazoid

No, I mean is there a list of person list who has assigned FSF papers.

**Comment by riscy** [comment]
> No, I mean is there a list of person list who has assigned FSF papers.

I had a look and I see FSF maintains a [directory](https://directory.fsf.org/wiki/Main_Page) of free software, but I'm not sure.

**Comment by stardiviner** [comment]
I see, not this website. I used to ask assign@fsf.org, not explict answer too. I give up.

**Comment by riscy** [comment]
I trust that you have, don't worry. :)

**Comment by riscy** [comment]
This looks good to go.  My last comment is minor and not a blocker: your docstrings enquote variable names using ``` ` ``` and `'`, e.g. ```"Store mu4e header markers value from `L'." ```.  But those quotes are usually for creating hyperlinks in the help system -- it's sufficient to just upcase the L.

**Comment by stardiviner** [comment]
I see, thanks. Will update soon.

**Pull request merged**
