### PR TITLE
Add recipe for turbo-log

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Automating the process of writing meaningful log messages.

### Direct link to the package repository

https://github.com/jcs-elpa/turbo-log

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

### turbo-log.el ###

byte-compile (using Emacs 27.1):
```
turbo-log.el:141:1:Warning: Unused lexical argument `end'
turbo-log.el:141:1:Warning: Unused lexical argument `beg'
```

**Comment by riscy** [comment]
Hello, I haven't heard back but I looped back and it looks like there was an update fixing the above, so that puts the checklist behind us.

This looks like a package in the same vein as the docstring package and I think I have some similar concerns (at risk of sounding like a broken record).  In particular without being an expert in a given language, it's hard to know whether these are idiomatic methods of logging, so we need to do some extra legwork to make sure that these are all correct.  I've got one foot out the door but now you know where I'm coming from -- I'll hopefully revisit this this evening.

**Comment by riscy** [comment]
From a usability standpoint the code operates pretty well.

I'd argue the summary line is misleading -- this looks like it's more for debug statements that are using the simplest method available to output a string, rather than exemplary ways of writing meaningful log messages.

"Branding" every log message with a conspicuous `╘[TL]` prefix seems unnecessary; imo a tool like this should try as much as it can to get out of your way even (especially) under its default configuration.

But most importantly I don't think this package reaches the maturity threshold, and we shouldn't be in a hurry to index anything and everything in MELPA.  To give some concrete examples, I'm just checking on languages I have some basic familiarity with -- at a glance, the c++ version calls `count` instead of `cout` and has no endline, and I suppose to be thorough it should check whether `iostream` has been brought into the file.  The python (3) version inserts an extra space, because the multi-arg version of `print` already puts spaces between its arguments.  The rust version should probably use Debug formatting (`"{?:}"`) which will happily increase the chances of byte-compilation succeeding.  The ruby version won't work unless the argument can be implicitly converted into a string (e.g. integers, floats, nils...), so you either need to do the cast explicitly or use string interpolation.

**Comment by riscy** [comment]
What I propose we do is close this PR for a few months and give it some time to mature.  You can reach out to proficient developers in the different languages and have them give you candid feedback, and then feel free to reopen this PR (or link to it in the followup) for another look.

**Comment by jcs090218** [comment]
Thanks for the explanation! Sorry for the late reply! I was kind of busy recently. I will close this PR and open it later I feel the tool is much mature! Thank you very much for the review! :)

**Pull request closed without merging**
