### PR TITLE
Add recipe for async-status

### PR DESCRIPTION
**Pull request by seokbeomKim**
### Brief summary of what the package does

To support a progress indicator for Emacs processes running with `async` package

### Direct link to the package repository

https://github.com/seokbeomKim/async-status

### Your association with the package

Author/maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
```emacs-lisp
;;; async-status.el --- A package for indicator support
```

You'll want to enable lexical binding for the package.

```emacs-lisp
;;; async-status.el --- A package for indicator support  -*- lexical-binding: t; -*-
```

It seems like the overall design could be simplified by making use of `make-temp-file` instead of generating your own UUID.
It could be used to store a per-process file on the struct and would simplify the bookkeeping.

```emacs-lisp
(defvar async-status--private-directory
  (expand-file-name "async-status" user-emacs-directory)
  "Default directory path for async-status package.
```

With that in mind, I would think `temporary-file-directory` would be a better spot for these files.

```emacs-lisp
`MSG_ID': Message id returned by `async-status--req-msg-id'.

`FS_WATCHER_ID': File watcher descriptor. This must be set by
calling `async-status--add-msg-to-bar'.

`FILE_PATH': The target file to watch file events. Emacs process
```

It would be more idiomatic to use hyphens in these slot names. e.g.

```emacs-lisp
msg-id
fs-watcher-id
file-path
```

It's questionable to ignore errors of this type:

```emacs-lisp
  (ignore-errors (delete-directory async-status--private-directory t))
  (ignore-errors (mkdir async-status--private-directory)))
```

It would be better to use `condition-case` to properly handle errors.

**Comment by seokbeomKim** [comment]
I appreciate your code review!

#### Lexical binding
* Okay, I fixed it.

#### Using temp file instead of UUID
* Thanks for your advice. I agree with that using UUID was unnecessary code, so I removed those parts using UUID away.

#### Code convention (regarding the name of private functions and slots)
* Okay. I changed the name of them. 

#### Ignore-errors
* I was trying to make the code behave like `rm -rf`. But I saw that this was the wrong approach. The related code has been removed by avoiding UUID.

Again, thank you for the detailed advice.

**Comment by riscy** [comment]
Awesome, @progfolio and thanks again. :)

A couple more comments from my end --

`async-status.el` with package-lint 20230806.1331:
```
1 issue found:
12:55: warning: Use a properly versioned dependency on "posframe" if possible.
```
You can pacify this little nag by specifying e.g. [1.4.2](https://stable.melpa.org/#/posframe) for this posframe version.  If you get used to seeing warnings like this from package-lint, you might miss a *real* issue in the future

Package and license:
- Avoid specifying `:branch` except in unusual cases -- in this case, MELPA will always use your repo's default branch.  This keeps you free to change the name of your default branch, so we recommend you exclude it when you can.

**Comment by seokbeomKim** [comment]
Thanks for the feedback.
I have changed the code and recipe as you pointed out.

**Comment by riscy** [comment]
One more thing to mention - you should be aware of the [async](https://melpa.org/#/async) package.  There is a chance (albeit small) that you may run into namespace collisions.

Not a blocker, though. Merging!

**Pull request merged**
