### PR TITLE
add: blackboard-theme recipe

### PR DESCRIPTION
**Pull request by don9z**
### Brief summary of what the package does

Add blackboard-theme (TextMate's)

### Direct link to the package repository

https://github.com/don9z/melpa

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR about package meta comments.

https://github.com/don9z/blackboard-theme/pull/4

**Comment by purcell** [comment]
Thanks, looks good. Please remove "for Emacs" from the package description. It's redundant, since every Emacs package and theme is "for Emacs" -- `package-lint` would have warned you about that. :-)

**Comment by don9z** [comment]
done 

https://github.com/don9z/blackboard-theme/commit/d8b984f2541bb86eb4363a2b4c94631e49843d4a

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
