### PR TITLE
Update ox-nikola recipe

### PR DESCRIPTION
**Pull request by msnoigrs**
### Brief summary of what the package does

export Nikola blog posts in reStructuredText syntax from Org-Mode

### Direct link to the package repository

https://github.com/msnoigrs/ox-nikola

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by tarsius** [comment]
Based on the information on your profile

> Masanao Igarashi
> msnoigrs

I assume that you simply changed your nickname from `masanao` to `msnoigrs`. Is that correct?

**Comment by msnoigrs** [comment]
Yes. It's correct.

**Comment by tarsius** [comment]
This was confusing. I did not notice that you had modified the `ox-rst` recipe instead of the one of `ox-nikola` and was then wondering why the rebase resulted in no new commit.

Also when you modify a recipe, then you should communicate upfront why that change is being made. The information that you did provide is mostly relevant when adding a *new* package.

**Comment by msnoigrs** [comment]
All right. I'll be more careful. Thanks.

**Pull request merged**
