### PR TITLE
Add maxima recipe

### PR DESCRIPTION
**Pull request by Sasanidas**
### Brief summary of what the package does
This is a major-mode,minor-mode and inferior-mode for the [maxima](http://maxima.sourceforge.net/) the computer algebra system, it is a fork from the original one that ship with the product, but with major improvements in code quality,completion and latex integration.

This is still a work in progress, it's right now way more usable than the original file, but still doesn't fit the MELPA criteria,
There still code to improve and fix some warnings ,I'm doing my best to address the package issues.
Thank you.

### Direct link to the package repository

https://gitlab.com/sasanidas/maxima

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks!  Quick first pass -- hope this helps (I do see you wrote you're currently addressing the issues):

### maxima-font-lock.el ###

byte-compile (using Emacs 27.1):
```
maxima-font-lock.el:98:42:Error: Symbol's value as variable is void: maxima-vars-1
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200901.2204):
```
6 issues found:
12:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
1422:0: error: "inferior-maxima-font-lock-keywords-1" doesn't start with package's prefix "maxima".
1426:0: error: "inferior-maxima-font-lock-keywords-2" doesn't start with package's prefix "maxima".
1430:0: error: "inferior-maxima-font-lock-keywords-3" doesn't start with package's prefix "maxima".
1434:0: error: "inferior-maxima-font-lock-keywords" doesn't start with package's prefix "maxima".
1437:0: error: "inferior-maxima-font-setup" doesn't start with package's prefix "maxima".
``

Other possible lints:
- maxima-font-lock.el#L1402: It's safer to sharp-quote function names; use `#'`

### maxima-noweb.el ###

byte-compile (using Emacs 27.1):
```
maxima-noweb.el:147:1:Warning: Unused lexical variable `pt'
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200901.2204):
```
1 issue found:
15:0: error: Package-Requires outside the main file have no effect.
```


### maxima.el ###

byte-compile (using Emacs 27.1):
```
maxima.el:363:37:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
In maxima-strip-string-end:
maxima.el:380:37:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
In maxima-remove-whitespace-from-ends:
maxima.el:415:15:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
maxima.el:433:1:Warning: Unused lexical variable `end'
In maxima-remove-whitespace-from-beg:
maxima.el:438:15:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
maxima.el:452:1:Warning: Unused lexical variable `beg'
In maxima-remove-whitespace-from-end:
maxima.el:457:15:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
maxima.el:1227:1:Warning: Unused lexical variable `bol-pt'
maxima.el:1564:1:Warning: Unused lexical variable `place'
In maxima-get-help:
maxima.el:1575:33:Warning: assignment to free variable `name'
maxima.el:1575:6:Warning: reference to free variable `name'
maxima.el:1596:1:Warning: Unused lexical variable `lmark'
In maxima-apropos:
maxima.el:1633:19:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
maxima.el:1737:1:Warning: Unused lexical variable `lmark'
In maxima-help-variation:
maxima.el:1753:26:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
maxima.el:1765:8:Warning: `mapcar' called for effect; use `mapc' or `dolist'
    instead
maxima.el:1896:18:Warning: `mouse-choose-completion' is an obsolete function
    (as of 23.2); use `choose-completion' instead.
maxima.el:1964:1:Warning: Unused lexical argument `arg'
maxima.el:1964:1:Warning: Unused lexical argument `arg'
maxima.el:1989:23:Warning: reference to free variable `company-backends'
maxima.el:1989:23:Warning: assignment to free variable `company-backends'
maxima.el:2025:1:Warning: Unused lexical variable `keep-going'
In maxima-check-parens:
maxima.el:2093:9:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
maxima.el:2156:1:Warning: Unused lexical variable `i'
maxima.el:2447:1:Warning: Unused lexical variable `pos'
maxima.el:2447:1:Warning: Unused lexical variable `pmark'
maxima.el:2447:1:Warning: Unused lexical argument `string'
In inferior-maxima-remove-double-input-prompt:
maxima.el:2450:30:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
maxima.el:2461:1:Warning: Unused lexical argument `string'
maxima.el:2494:1:Warning: Unused lexical argument `proc'
In maxima-start:
maxima.el:2506:14:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
maxima.el:2523:21:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
In maxima-get-command:
maxima.el:2586:37:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
In maxima-last-output:
maxima.el:2659:4:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
maxima.el:3093:1:Warning: Unused lexical variable `outputbeg'
In end of data:
maxima.el:3399:1:Warning: the following functions are not known to be defined:
    maxima-noweb-re-search-forward, maxima-noweb-re-search-backward,
    maxima-noweb-next-char-word-part-p, maxima-noweb-forward-word,
    maxima-noweb-backward-word, maxima-noweb-goto-beginning-of-form,
    maxima-noweb-goto-end-of-form,
    maxima-noweb-perhaps-smart-calculate-indent, Info-menu,
    Info-follow-nearest-node, Info-goto-node, maxima-help-insert-line, s-trim,
    company-begin-backend, company-in-string-or-comment, company-grab-symbol,
    org-latex-preview
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200901.2204):
```
28 issues found:
270:0: error: "inferior-maxima-after-output-wait" doesn't start with package's prefix "maxima".
283:0: error: "inferior-maxima-process" doesn't start with package's prefix "maxima".
286:0: error: "inferior-maxima-input-end" doesn't start with package's prefix "maxima".
289:0: error: "inferior-maxima-output-end" doesn't start with package's prefix "maxima".
291:0: error: "inferior-maxima-waiting-for-output" doesn't start with package's prefix "maxima".
293:0: error: "inferior-maxima-exit-hook" doesn't start with package's prefix "maxima".
295:0: error: "inferior-maxima-prompt" doesn't start with package's prefix "maxima".
1847:0: error: "comint-dynamic-list-completions" doesn't start with package's prefix "maxima".
1967:0: error: "company-maxima-libraries" doesn't start with package's prefix "maxima".
1979:0: error: "company-maxima-symbols" doesn't start with package's prefix "maxima".
2418:0: error: "inferior-maxima-running" doesn't start with package's prefix "maxima".
2424:0: error: "inferior-maxima-get-old-input" doesn't start with package's prefix "maxima".
2439:0: error: "inferior-maxima-comint-send-input" doesn't start with package's prefix "maxima".
2447:0: error: "inferior-maxima-remove-double-input-prompt" doesn't start with package's prefix "maxima".
2461:0: error: "inferior-maxima-replace-tabs-by-spaces" doesn't start with package's prefix "maxima".
2472:0: error: "inferior-maxima-wait-for-output" doesn't start with package's prefix "maxima".
2480:0: error: "inferior-maxima-output-filter" doesn't start with package's prefix "maxima".
2494:0: error: "inferior-maxima-sentinel" doesn't start with package's prefix "maxima".
2858:0: error: "inferior-maxima-previous-inputs" doesn't start with package's prefix "maxima".
2871:0: error: "inferior-maxima-input-complete" doesn't start with package's prefix "maxima".
2892:0: error: "inferior-maxima-complete" doesn't start with package's prefix "maxima".
2909:0: error: "inferior-maxima-check-and-send-line" doesn't start with package's prefix "maxima".
2931:0: error: "inferior-maxima-send-line" doesn't start with package's prefix "maxima".
2936:0: error: "inferior-maxima-bol" doesn't start with package's prefix "maxima".
2945:0: error: "inferior-maxima-bol-position" doesn't start with package's prefix "maxima".
2954:0: error: "inferior-maxima-mode" doesn't start with package's prefix "maxima".
3300:5: error: You should depend on (emacs "27.1") if you need `org-latex-preview'.
3322:2: error: Aliases should start with the package's prefix "maxima".
```

Other possible lints:
- maxima.el#L2315: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2412: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2526: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2528: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2530: It's safer to sharp-quote function names; use `#'`
- maxima.el#L3392: It's safer to sharp-quote function names; use `#'`
- maxima.el#L3395: It's safer to sharp-quote function names; use `#'`
- maxima.el#L3322: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2399: Prefer `define-derived-mode`
- maxima.el#L3008: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L3010: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L3012: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L3014: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L3016: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L3017: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L3018: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L3019: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L1399: Consider `unless ...` instead of `when (not ...)`
- maxima.el#L3159: Consider `unless ...` instead of `when (not ...)`

### Loadability ###

Verifying ability to #'load each file:
```
Loading maxima-font-lock.el
Loading maxima-noweb.el
Loading maxima.el
Done.
```

### Package ###

- Prefer the default recipe if possible.
  It seems to be equivalent: `(maxima :repo "sasanidas/maxima" :fetcher gitlab)`
- LICENSE excerpt: `GNU GENERAL PUBLIC LICENSE...`
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.org/using-spdx-license-identifier) to maxima-noweb.el
- maxima-font-lock.el (GPL) -- syntax highlighting for maxima.el
- maxima-noweb.el (unknown license) -- Maxima minor mode for noweb-mode interaction
- maxima.el (GPL) -- Major modes for writing Maxima code

**Comment by Sasanidas** [comment]
Sorry for the delay @riscy , I'm working on it.
I will change the recipe, there is new files and the noweb file is not going to be included.

Aside from that, I will ping when I think the package is ready for another check.

Well, the name is similar to imaxima, but the aim is quite different, and well imaxima it's quite outdated.

Thanks for the feedback!

**Comment by Sasanidas** [comment]
@riscy 
Seems like it's more or less ready, I have some question with the `inferior-maxima` error.
Seems like other packages like octave have the inferior mode inside too, so I don't know if I should decouple it.

Most of the errors are in maxima-font-lock.el, which is a file that need some work.

Again, thanks for the feedback!

**Comment by riscy** [comment]
No worries about any delay!  You're referring to errors like this, right?
```
2717:0: error: "inferior-maxima-mode" doesn't start with package's prefix "maxima".
```
It's true that some older packages use `inferior-xyz` as a prefix, but you'll find old packages on MELPA that break all sorts of contemporary guidelines.  The reason MELPA (and package-lint) cares so much about prefixes is that this is the only way for us to "namespace".  If someone were to come along and add a package called `inferior-maxima-mode`, users could potentially end up with confusing bugs.  It seems like the easy solution in this case would be to rename those functions/variables to e.g. `maxima-inferior-mode`, although I do appreciate that `inferior-` is an idiomatic prefix in elisp.

Here's the latest (perhaps `company-maxima` wants to be in a separate recipe).

### company-maxima.el ###

byte-compile (using Emacs 27.1):
```
company-maxima.el:39:1:Error: Cannot open load file: No such file or directory, company
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
```
3 issues found:
11:0: error: Package-Requires outside the main file have no effect.
43:0: error: "company-maxima-libraries" doesn't start with package's prefix "maxima".
57:0: error: "company-maxima-symbols" doesn't start with package's prefix "maxima".
```


### maxima-font-lock.el ###

byte-compile (using Emacs 27.1):
```
maxima-font-lock.el:98:42:Error: Symbol's value as variable is void: maxima-vars-1
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
```
6 issues found:
12:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
1422:0: error: "inferior-maxima-font-lock-keywords-1" doesn't start with package's prefix "maxima".
1426:0: error: "inferior-maxima-font-lock-keywords-2" doesn't start with package's prefix "maxima".
1430:0: error: "inferior-maxima-font-lock-keywords-3" doesn't start with package's prefix "maxima".
1434:0: error: "inferior-maxima-font-lock-keywords" doesn't start with package's prefix "maxima".
1437:0: error: "inferior-maxima-font-setup" doesn't start with package's prefix "maxima".
```

Other possible lints:
- maxima-font-lock.el#L1402: Why does this need to be done in a hook?  Why not in the definition of the major mode itself?

### maxima-poly.el ###

byte-compile (using Emacs 27.1):
```
maxima-poly.el:32:1:Error: Cannot open load file: No such file or directory, polymode
```
Probably a missing `Package-Requires`

checkdoc (using version 0.6.2):
```
Warning (emacs): 
maxima-poly.el:10: White space found at end of line
```

package-lint (using version 20200906.512):
```
1 issue found:
11:0: error: Package-Requires outside the main file have no effect.
```

Other possible lints:
- maxima-poly.el#L74: Does this file exist?  Should you just `require` it?

### maxima.el ###

byte-compile (using Emacs 27.1):
```
maxima.el:2218:1:Warning: Unused lexical argument `string'
maxima.el:2230:1:Warning: Unused lexical argument `string'
maxima.el:2263:1:Warning: Unused lexical argument `proc'
In maxima-start:
maxima.el:2275:14:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
In end of data:
maxima.el:3160:1:Warning: the following functions are not known to be defined:
    Info-menu, Info-follow-nearest-node, Info-goto-node,
    maxima-help-insert-line, s-trim
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
```
23 issues found:
264:0: error: "inferior-maxima-after-output-wait" doesn't start with package's prefix "maxima".
277:0: error: "inferior-maxima-process" doesn't start with package's prefix "maxima".
280:0: error: "inferior-maxima-input-end" doesn't start with package's prefix "maxima".
283:0: error: "inferior-maxima-output-end" doesn't start with package's prefix "maxima".
285:0: error: "inferior-maxima-waiting-for-output" doesn't start with package's prefix "maxima".
287:0: error: "inferior-maxima-exit-hook" doesn't start with package's prefix "maxima".
289:0: error: "inferior-maxima-prompt" doesn't start with package's prefix "maxima".
2189:0: error: "inferior-maxima-running" doesn't start with package's prefix "maxima".
2195:0: error: "inferior-maxima-get-old-input" doesn't start with package's prefix "maxima".
2210:0: error: "inferior-maxima-comint-send-input" doesn't start with package's prefix "maxima".
2218:0: error: "inferior-maxima-remove-double-input-prompt" doesn't start with package's prefix "maxima".
2230:0: error: "inferior-maxima-replace-tabs-by-spaces" doesn't start with package's prefix "maxima".
2241:0: error: "inferior-maxima-wait-for-output" doesn't start with package's prefix "maxima".
2249:0: error: "inferior-maxima-output-filter" doesn't start with package's prefix "maxima".
2263:0: error: "inferior-maxima-sentinel" doesn't start with package's prefix "maxima".
2620:0: error: "inferior-maxima-previous-inputs" doesn't start with package's prefix "maxima".
2634:0: error: "inferior-maxima-input-complete" doesn't start with package's prefix "maxima".
2655:0: error: "inferior-maxima-complete" doesn't start with package's prefix "maxima".
2672:0: error: "inferior-maxima-check-and-send-line" doesn't start with package's prefix "maxima".
2694:0: error: "inferior-maxima-send-line" doesn't start with package's prefix "maxima".
2699:0: error: "inferior-maxima-bol" doesn't start with package's prefix "maxima".
2708:0: error: "inferior-maxima-bol-position" doesn't start with package's prefix "maxima".
2717:0: error: "inferior-maxima-mode" doesn't start with package's prefix "maxima".
```

Other possible lints:
- maxima.el#L2086: Why not `(setq-local ...` instead of `(make-local-variable ...) (setq ...)`?
- maxima.el#L2086: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2183: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2294: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2296: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2298: It's safer to sharp-quote function names; use `#'`
- maxima.el#L3153: It's safer to sharp-quote function names; use `#'`
- maxima.el#L3156: Why is this done in a hook?
- maxima.el#L2170: Prefer `define-derived-mode` over `(defun maxima-mode` (not a blocker)
- maxima.el#L665: Could this point/point-min comparison use `bobp`?
- maxima.el#L2771: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L2773: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L2775: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L2777: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L2779: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L2780: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L2781: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L2782: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- maxima.el#L1284: No `format` required; messages are already f-strings
- maxima.el#L1474: No `format` required; messages are already f-strings

**Comment by Sasanidas** [comment]
Hello @riscy , I changed the maxima recipe, now it only include the essential files (maxima.el and maxima-font-lock.el), as suggested, I'm going to submit another 2 packages related to Maxima, company-maxima, and poly-maxima (related to poly-mode).

I re-write the maxima-font-lock.el so now it's way easy to read, and split the keywords in files and package lint seems now more happy :+1: 

Regards.

**Comment by riscy** [comment]
Nice, thanks for that.  Here's another quick scan of those two files with the new recipe:

### maxima-font-lock.el ###

byte-compile (using Emacs 27.1):
```
maxima-font-lock.el:86:42:Error: Symbol's value as variable is void: maxima-font-lock-functions
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
```
1 issue found:
15:0: error: Package-Requires outside the main file have no effect.
```

Other possible lints:
- maxima-font-lock.el#L153: It's safer to sharp-quote function names; use `#'`

### maxima.el ###

byte-compile (using Emacs 27.1):
```
maxima.el:1407:8:Warning: `beginning-of-buffer' is for interactive use only;
    use `(goto-char (point-min))' instead.
In maxima-mode:
maxima.el:2130:4:Warning: misplaced interactive spec: `(interactive)'
```

Other possible lints:
- maxima.el#L2132: Since you're using `define-derived-mode`, you don't have to `kill-all-local-variables`, nor set the major mode, or the mode-name, or call `use-local-map`, or explicitly run the hooks.
- maxima.el#L635: Could this point/point-min comparison use `bobp`?
- maxima.el#L2733: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`

**Comment by Sasanidas** [comment]
Ok, I think I addressed these issues, thanks for the fast response :+1:

**Comment by riscy** [comment]
No problem, you caught me on MELPA.  Looking a bit closer, the last couple things to fix (non-blocking by the looks of it):

- `(test-simple "1.3.0")` shouldn't be in your `Package-Requires`.  I'd fix that as soon as you can, but I don't think that's a blocker.
- I think adding this hook at the bottom of the file shouldn't be necessary `(add-hook 'maxima-minor-mode-hook 'maxima-minor-mode-highlighting)` -- you can add the hook when turning the minor mode on.

I also have this laundry list of extremely minor lints that I've been sparing you from, but I'll leave it here for reference :)

- maxima.el#L1384: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2140: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2250: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2252: It's safer to sharp-quote function names; use `#'`
- maxima.el#L2254: It's safer to sharp-quote function names; use `#'`
- maxima.el#L3117: It's safer to sharp-quote function names; use `#'`
- maxima.el#L3120: It's safer to sharp-quote function names; use `#'`
- maxima.el#L303: Single-line comments should usually begin with `;;`
- maxima.el#L817: Single-line comments should usually begin with `;;`
- maxima.el#L1161: Single-line comments should usually begin with `;;`
- maxima.el#L1162: Single-line comments should usually begin with `;;`
- maxima.el#L1163: Single-line comments should usually begin with `;;`
- maxima.el#L1164: Single-line comments should usually begin with `;;`
- maxima.el#L1178: Single-line comments should usually begin with `;;`
- maxima.el#L1179: Single-line comments should usually begin with `;;`
- maxima.el#L1188: Single-line comments should usually begin with `;;`
- maxima.el#L1189: Single-line comments should usually begin with `;;`
- maxima.el#L1195: Single-line comments should usually begin with `;;`
- maxima.el#L1976: Single-line comments should usually begin with `;;`
- maxima.el#L1977: Single-line comments should usually begin with `;;`
- maxima.el#L1985: Single-line comments should usually begin with `;;`
- maxima.el#L1988: Single-line comments should usually begin with `;;`
- maxima.el#L2001: Single-line comments should usually begin with `;;`
- maxima.el#L2280: Single-line comments should usually begin with `;;`
- maxima.el#L2349: Single-line comments should usually begin with `;;`
- maxima.el#L2350: Single-line comments should usually begin with `;;`
- maxima.el#L2565: Single-line comments should usually begin with `;;`
- maxima.el#L2732: Single-line comments should usually begin with `;;`
- maxima.el#L2733: Single-line comments should usually begin with `;;`
- maxima.el#L2881: Single-line comments should usually begin with `;;`
- maxima.el#L2914: Single-line comments should usually begin with `;;`

**Pull request merged**
