### PR TITLE
Adding recipe for schrute-mode

### PR DESCRIPTION
**Pull request by shackra**
### Brief summary of what the package does

Dwight K. Schrute-mode or `schrute-mode` for short, is a minor global mode that will help you to remember that there is a better way to do something. By better I mean using commands like `avy-goto-line` instead of making several invocations of `next-line` in a row with either `C-<down>` or `C-n` keybindings. If your memory is like mine, you'll often forget those features are available, if you commit the mistake of taking the long route, `schrute-mode` will be there to save the day... just don't forget to configure it!.

### Direct link to the package repository

https://bitbucket.org/shackra/dwight-k.-schrute/

### Your association with the package

Creator and maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- no autoload cookie
- no `provide`
- Emoji in lighter does not show anything if platform does not have emoji font

**Comment by shackra** [comment]
Fixed! sorry about that.

**Comment by purcell** [comment]
Thanks. Quick feedback:
- Declaring a dependency on `((emacs "22.2"))` is actually counterproductive, because `package.el` for Emacs 23 does not know about the `emacs` pseudopackage, so this clause actually makes the package uninstallable on Emacs < 24. :-)
- In any case, you're using `defvar-local`, which requires Emacs 24.3 -- `flycheck-package` will tell you about that, so please consider using it, because it saves me time reviewing!
- `(string-match-p " \\*Minibuf-[0-1]+\\*" (buffer-name))` is bogus: use `minibufferp`
- You have code to turn the mode on, but not to turn it off. You should add the latter, in order to be able to restore `post-command-hook`.
- `" Bear"` as a lighter isn't a good default, and will confuse people who expect to see `Schrute` or similar.
- `defcustom` supports compound types, so you can (and should) use something more specific than `'list` for the `:type` of `schrute-shortcut-commands`.

**Comment by shackra** [comment]
Hello again!

I've fixed the mess noted by @purcell but regarding the last bullet point, is something I would like to do so I can assure the user is not doing something weird or wrong when setting `schrute-shortcut-commands`... but can we bypass that for now? I feel that specific topic is a little out of reach for me right now.

I swear I had the flycheck-package installed and all, no idea why the checker isn't added when opening the main file of my project :-/

**Comment by shackra** [comment]
B-b-but I have flycheck enabled! I don't get it, no error was reported to me while working on schrute-mode https://bitbucket.org/shackra/dwight-k.-schrute/src/99857394886e516d5ebd63fedff200bceaef1d4d/.dir-locals.el?at=master&fileviewer=file-view-default

I'm going to fix the other stuff, thanks! 

El 23 de octubre de 2016 14:29:18 GMT-06:00, Steve Purcell <notifications@github.com> escribió:
>Thanks. Quick feedback:
>- Declaring a dependency on `((emacs "22.2"))` is actually
>counterproductive, because `package.el` for Emacs 23 does not know
>about the `emacs` pseudopackage, so this clause actually makes the
>package uninstallable on Emacs < 24. :-)
>- In any case, you're using `defvar-local`, which requires Emacs 24.3
>-- `flycheck-package` will tell you about that, so please consider
>using it, because it saves me time reviewing!
>- `(string-match-p " \\*Minibuf-[0-1]+\\*" (buffer-name))` is bogus:
>use `minibufferp`
>- You have code to turn the mode on, but not to turn it off. You should
>add the latter, in order to be able to restore `post-command-hook`.
>- `" Bear"` as a lighter isn't a good default, and will confuse people
>who expect to see `Schrute` or similar.
>- `defcustom` supports compound types, so you can (and should) use
>something more specific than `'list` for the `:type` of
>`schrute-shortcut-commands`.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/melpa/melpa/pull/4345#issuecomment-255612234

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alphapapa** [comment]
This package sounds neat, and I like the humor.  But I have this nagging feeling that there's already a package that does something like this, or almost like it...

**Comment by shackra** [comment]
Like bind-chord, annoying-arrows? Well, whenever I'm about to do something, I think, "Would an idiot
do that?" And if they would, I do not do that thing. So, no Jim, I did not reinvent the wheel (Dwight
Schrute, probably)

In all seriousness, my goal with this package was to remove some luggage from the users mind, with
bind-chord you still have to make new bindings, which means you still need to remember they are there
for you for easy reach of that shinny new functionality you got for Emacs. Some users may like this
path, and it is fine, right?.

Other users, like me, would like to ease a little this frenzy of binding stuff (and try to remember
those binds), and I swear that often I forget that I had X thing bound to whatever key and instead
use some old command X was suppose to replace. Dwight is there to assist the user *only* when needed
(assuming the user did the required configuration), "only when needed" is translated to "when the
user 'falls asleep' pressing some key" or "when the user hits quickly too many times the same
keys". People may find my UX decisions with this package questionable, but then there are other
options for them to use, right? :D

I just thought something like Dwight Schrute was lacking in MELPA.

El miércoles 26 de octubre del 2016 a las 0538 horas, alphapapa escribió:

> This package sounds neat, and I like the humor. But I have this nagging feeling that there's already a package that does something like this, or almost like it...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by alphapapa** [comment]
@shackra I didn't mean it as a criticism, I think this is a great idea!  I just feel like there's something I've seen before that does something like this.  I wasn't able to find it by googling, but now I'm thinking maybe it's something built-in to Emacs, something that says something like, "The command do-something is also bound to C-x whatever" when you run the command with `M-x` instead of the bound key.  I haven't been able to put my finger on it, but I know I've seen Emacs say that to me before...

**Comment by shackra** [comment]
I didn't get it that way! 

If you find that command, please put it here, I want to know too

El 26 de octubre de 2016 14:46:03 GMT-06:00, alphapapa <notifications@github.com> escribió:
>@shackra I didn't mean it as a criticism, I think this is a great idea!
>I just feel like there's something I've seen before that does something
>like this.  I wasn't able to find it by googling, but now I'm thinking
>maybe it's something built-in to Emacs, something that says something
>like, "The command do-something is also bound to C-x whatever" when you
>run the command with `M-x` instead of the bound key.  I haven't been
>able to put my finger on it, but I know I've seen Emacs say that to me
>before...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/melpa/melpa/pull/4345#issuecomment-256471774

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by purcell** [comment]
Merging now, thanks!

**Comment by shackra** [comment]
Thank you!! 

El 29 de octubre de 2016 17:32:41 GMT-06:00, Steve Purcell <notifications@github.com> escribió:
>Merging now, thanks!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/melpa/melpa/pull/4345#issuecomment-257122229

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alphapapa** [comment]
@shackra Aha!  The thing I was thinking of is the variable `suggest-key-bindings`, which is built-in to Emacs.  I think that it doesn't do anything for me since I use `helm-M-x` (which displays bindings in the list with each command).

**Comment by shackra** [comment]
Cool, thanks for the info!

El domingo 30 de octubre del 2016 a las 2207 horas, alphapapa escribió:

> @shackra Aha! The thing I was thinking of is the variable suggest-key-bindings, which is built-in to Emacs. I think that it doesn't do anything for me since I use helm-M-x (which displays bindings in the list
> with each command).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Pull request merged**
