### PR TITLE
Add ‘info-rename-buffer’ recipe.

### PR DESCRIPTION
**Pull request by oitofelix**
----

### Brief summary of what the package does

Rename Info buffers to match manuals

`info-rename-buffer-mode` is a global minor-mode that automatically
renames Info buffers to match their visiting manual.

That’s a useful feature when consulting several Info manuals
simultaneously, because it frees the user from the burden of renaming
Info buffers to descriptive names manually before visiting another
manual, thus avoiding accidentally overriding the currently visited
node in case the user tries to open a new Info buffer.

### Direct link to the package repository

https://github.com/oitofelix/info-rename-buffer

### Your association with the package

I’m the original author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
This looks cool, and very simple.  Have you considered trying to contribute it upstream to Emacs itself?

**Comment by oitofelix** [comment]
alphapapa <notifications@github.com> writes:

> This looks cool, and very simple. Have you considered trying to
> contribute it upstream to Emacs itself?

Glad you liked it!  I did submit it for review on
‘emacs-devel@gnu.org’[1], but no one replied yet.


Footnotes: 
[1]  https://lists.gnu.org/archive/html/emacs-devel/2019-08/msg00339.html

-- 
 88888  FFFFF Bruno Félix Rezende Ribeiro (oitofelix) [0x28D618AF]
 8   8  F     http://oitofelix.freeshell.org/
 88888  FFFF  mailto:oitofelix@gnu.org
 8   8  F     irc://chat.freenode.org/oitofelix
 88888  F     xmpp://oitofelix@riseup.net

**Comment by alphapapa** [comment]
Ah, that's too bad, it happens sometimes.  :(  It would probably be okay to post a followup since it hasn't been noticed.

**Comment by riscy** [comment]
This is cool.  The only very minor issue I'm seeing is that MELPA will automatically add your `Package-Version`, so instead specifying just `Version:` is preferred.  I don't know if this is documented anywhere, so probably not your fault:

```elisp
;; Author: Bruno Félix Rezende Ribeiro <oitofelix@gnu.org>
;; Keywords: help
;; Package: info-rename-buffer
;; Homepage: https://github.com/oitofelix/info-rename-buffer
;; Version: 0
;; Package-Requires: ((emacs "24.3"))
```

**Comment by oitofelix** [comment]
Hi Chris,

Thanks for reviewing the code.

The issue you reported has been fixed.


Chris Rayner <notifications@github.com> writes:

> This is cool. The only very minor issue I'm seeing is that MELPA will
> automatically add your Package-Version, so instead specifying just
> Version: is preferred.


-- 
 88888  FFFFF Bruno Félix Rezende Ribeiro (oitofelix) [0x28D618AF]
 8   8  F     http://oitofelix.freeshell.org/
 88888  FFFF  mailto:oitofelix@gnu.org
 8   8  F     irc://chat.freenode.org/oitofelix
 88888  F     xmpp://oitofelix@riseup.net

**Comment by riscy** [comment]
Great thanks!

**Pull request merged**
