### PR TITLE
Add recipe for saveplace-pdf-view

### PR DESCRIPTION
**Pull request by nicolaisingh**
### Brief summary of what the package does

Extend `save-place-mode` to allow automatically persisting between Emacs sessions the current page/position of the PDF file being visited with `pdf-view-mode`.

### Direct link to the package repository

https://github.com/nicolaisingh/saveplace-pdf-view

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass.

### saveplace-pdf-view.el ###

byte-compile (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
saveplace-pdf-view.el:94:1:Warning: the following functions are not known to
    be defined: pdf-view-bookmark-jump, pdf-view-bookmark-make-record
```

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200419.406):
- No issues!


### Loadability ###

Verifying ability to #'load each file:
```
Loading saveplace-pdf-view.el
Done.
```

### Package ###

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible

**Comment by nicolaisingh** [comment]
Thanks for the review!

I've addressed the comments:
> byte-compile (using Emacs 26.3):
> 
> - Per CONTRIBUTING.org, consider using lexical binding.
>   See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
> - Lexical binding will be used in what follows

Lexical binding is now set.

> - Add a LICENSE file that GitHub can detect (e.g. no markup) if possible

GPL3 license file added.

**Comment by manuel-uberti** [comment]
Not a review, just a comment from a happy user: this package works as advertised. :)

Thank you @nicolaisingh.

**Comment by nicolaisingh** [comment]
> Not a review, just a comment from a happy user: this package works as advertised. :)
> 
> Thank you @nicolaisingh.

Wow I didn't expect this.  Thank you @manuel-uberti for the kind words! :heart_eyes_cat:

**Comment by manuel-uberti** [comment]
I was using a local store solution (grabbed from Doom Emacs, IIRC), but I prefer your way of leveraging something already built-in. :)

**Comment by riscy** [comment]
Awesome, thanks for accommodating.  Here's the latest.

### saveplace-pdf-view.el ###

byte-compile (using Emacs 26.3):
```
saveplace-pdf-view.el:94:1:Warning: the following functions are not known to
    be defined: pdf-view-bookmark-jump, pdf-view-bookmark-make-record
```
For these I think you need a Package-Requires on pdf-tools, and a `(require 'pdf-tools)` in your elisp.

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200616.2257):
```
1 issue found:
1:0: warning: The package summary should not end with a period.
```

**Comment by nicolaisingh** [comment]
> For these I think you need a Package-Requires on pdf-tools, and a (require 'pdf-tools) in your elisp.

Updated.

> package-lint (using version 20200616.2257):
> 
> 1 issue found:
> 1:0: warning: The package summary should not end with a period.

Woops I forgot to re-run `package-lint` after fixing the previous warnings.

**Comment by riscy** [comment]
Great.  Welcome to MELPA! :)

**Pull request merged**
