### PR TITLE
Add recipe for eros

### PR DESCRIPTION
**Pull request by xiongtx**
### Brief summary of what the package does

Evaluation result overlays for Emacs Lisp.

### Direct link to the package repository

https://github.com/xiongtx/eros

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Looks good.

**Comment by xiongtx** [comment]
Thanks; when can it be merged?

**Comment by purcell** [comment]
Wait - is this any different to https://github.com/Fuco1/litable ? If not, I will probably suggest we remove `eros`. /cc @Fuco1

**Comment by syohex** [comment]
Ah, sorry I couldn't remember that.

**Comment by xiongtx** [comment]
`litable` evaluates things on the fly; `eros` does not. `litable` also requires you to declare functions as pure; `eros` does not.

**Comment by purcell** [comment]
:+1:

You might also like `lively.el`, if you haven't seen that before.

**Comment by xiongtx** [comment]
Neat, though that package seems to be abandoned. Might be a good choice for making dashboards, if you're into that sort of thing.

**Comment by purcell** [comment]
Yeah, `lively.el§ definitely not actively maintained, but it doesn't really need to be. An outstanding hacker friend of mine wrote it years ago. :-)

**Pull request merged**
