### PR TITLE
Add heroku recipe

### PR DESCRIPTION
**Pull request by licht1stein**
### Brief summary of what the package does

Interface to manage Heroku apps from within Emacs that is organized using transient (like Magit). Allows viewing and tailing logs, editing environment variables, restarting and destroying apps, running commands within heroku servers in both normal and detached mode etc.

### Direct link to the package repository

https://github.com/licht1stein/heroku.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`heroku.el` with byte-compile using Emacs 28.1:
```
heroku.el:578:39: Warning: Unused lexical argument `args'
In heroku-run-bash:
heroku.el:583:39: Warning: Unused lexical argument `args'
In heroku-config-edit-save:
heroku.el:601:28: Warning: reference to free variable `heroku--env-old-value'
heroku.el:606:70: Warning: reference to free variable `heroku--env-key'
In heroku-env-edit-mode:
heroku.el:613:39: Warning: `make-variable-buffer-local' not called at toplevel
heroku.el:612:17: Warning: `make-variable-buffer-local' not called at toplevel
In heroku-config-edit:
heroku.el:628:11: Warning: assignment to free variable `heroku--env-key'
heroku.el:629:11: Warning: assignment to free variable `heroku--env-old-value'
In end of data:
heroku.el:501:39: Warning: the function `comint-mode' is not known to be
    defined.
```

`heroku.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- heroku.el#L224: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
- heroku.el#L214: You can use `not` or `null`
- heroku.el#L332: No `format` required; `message` takes an f-string
- heroku.el#L531: No `format` required; `message` takes an f-string
- heroku.el#L542: No `format` required; `message` takes an f-string
- heroku.el#L624: No `format` required; `message` takes an f-string
```

Package and license:
- GNU General Public License v3.0 (via API)
- unknown license -- heroku.el: Like Magit but for Heroku CLI
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to heroku.el

Package name:
- `heroku` already exists: https://github.com/emacsattic/heroku - I think this one is worth knowing about although it may be outdated by this point.    @tarsius forgive my poor memory, but is there anything we need to do here vs. the attic when a new package comes along claiming the same name?

**Comment by licht1stein** [comment]
I'll fix the linting error,
But that package is one commit eleven years ago. How can I get the name?

**Comment by tarsius** [comment]
> But that package is one commit eleven years ago. How can I get the name?

@licht1stein 

Yes.
But since we Melpa maintainers effectively bless a new implementation to supersede an older implementation, we do have to take a look. We cannot just add the new implementation to Melpa, if we are aware that there is an older implementation, just because that happens to be missing from Melpa.

> forgive my poor memory, but is there anything we need to do here vs. the attic when a new package comes along claiming the same name?

@riscy

I think we are still in the process of figuring out *how much* we have to do in such a situation. I think we should:

- Look at both implementation. If the new implementation is featureful and well written, while the old implementation is a dirty hack that probably only ever worked for its author, then the situation is clear. But it seldom is *that* simple.
- In some cases we should try to get the two authors/maintainers taking to each other, but in some cases doing that might needlessly add friction.
- We should ask the author of the new implementation to study the old implementation. Are there any features that should be ported? We might even encourage the author to add a note to their readme. I.e., since they are taking over the package name, I think we can expect at least the same amount of investigating the old implementation from them, that we are willing to put in ourselves. Doing that also signals to us, that they are prepared to deal with conflicts that might arise from the takeover.
 
In this case, the old implementation seems to boil down to an elaborate `(shell ...)`, while the new provides a convenient interface to construct commands. (Though as the author of Transient, I am of course biased. :grinning:)

But I have never used Heroku myself. The old implementation seems to be doing something with SQL, while the string "sql" does not appear in the new implementation. I don't know if it makes sense for a `heroku` package to do SQL stuff and it would take me some time to figure that out. So the answer to this question (and similar questions in other cases), is exactly what I would like the author of the new implementation to look into and then tell us about.

**Comment by licht1stein** [comment]
Wow, that's a very elaborate answer, thank you! I'll check the old package and get back to you :)

**Comment by tarsius** [comment]
> Are there any features that should be ported?

I should point out that that is a *question*. Just because the old implementation has a feature, that does not necessarily mean that it has to be added to the new.

The first package I ever wrote was `auto-compile`. (I think. More or less.) In the early days it tried to provide all the features of all the other packages in that space provided (expect for one or two truly crazy ones). Once I removed all those unnecessary features, the package got a lot more useful.

For `hl-todo`, another early package, things played out differently. It started out explicitly stating that "these are the features I need, I don't plan to add the features that I don't need, here are some alternative implementations that have more features". Over time I did have to add some of those unnecessary features because my package became the most popular in this area (because the basics were more solid, I like to think), despite lacking features many users expected from such a package. Eventually I had to give up on pointing those users to (IMO inferior) alternatives, and just implement them in my package as well.

So... when we ask someone to implement features they might not need, because they are replacing an implementation that had those features, we should keep in mind that these features might turn out to be a liability *or* we are doing them a favor because eventually they will have to be implemented them anyway, because users expect them.

It's hard to know ahead of time -- but it seems like a good idea to encourage the author to think about it, without strong-arming them into doing something that seems unnecessary to them. That seems to be working here:

> Wow, that's a very elaborate answer, thank you! I'll check the old package and get back to you :)

**Comment by licht1stein** [comment]
I have looked into the old heroku.el package, and implemented both commands it had: `heroku-run` and `heroku-sql`. Moreover, the implementation in the old heroku.el would not work today, because you cannot pass the password to `psql` directly. However, I have implemented a secure workaround by temporarily setting an environment variable with the password. It came out to be a nice addition to heroku.el, even though I don't use Heroku's postgres myself.

I have also fixed all the linting errors and added melpazoid to Github Actions for heroku.el (and other packages of mine). Thank you for all the help @riscy @tarsius

**Comment by riscy** [comment]
Thank you @tarsius -- I agree entirely with that, and I've kept a link to your comment so I can remind myself going forward.

@licht1stein -- thanks also for your kind accommodation and taking the time to mull over the existing heroku.el.  I think this is good to merge in light of that.

**Pull request merged**
