### PR TITLE
Update imgur recipe

### PR DESCRIPTION
**Pull request by marsam**
### Brief summary of what the package does

Hi:
I want to promote my imgur.el instead of the currenlty available one. Mostly because the current imgur.el uses a [deprecated api since march 2016](https://blog.imgur.com/2016/01/11/imgur-api-version-3/), and I think is no longer maintained.

Feel free to close, if you consider it unnecesary.

### Direct link to the package repository

https://github.com/emacs-pe/imgur.el

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by dotemacs** [comment]
Your package name @marsam, is the same as the package you're replacing.

What are the rules about this, package name "shadowing"?

**Comment by tarsius** [comment]
Well, I would say the rule is "It all depends on the contents of 'Relevant communications with the upstream package maintainer'", which in this case unfortunately was left out :wink:

**Comment by marsam** [comment]
Hi, I only realized that there was already a imgur.el package after I cloned the melpa repository, sorry I've incorrectly hurried and made this pull request. I'm going to contact with the current package maintainer.

**Comment by ecraven** [comment]
I'd love to see this in melpa, just tried it, and it works well ;)

**Pull request closed without merging**
