### PR TITLE
Add package hush

### PR DESCRIPTION
**Pull request by tirimia**
### Brief summary of what the package does

The package enables retrieving secrets/values (caching optional and included) from pluggable sources

### Direct link to the package repository

https://github.com/tirimia/hush

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I may need a better explanation of what this does - I see from the Commentary it outsources the storing of secrets? but as a user I'd have trouble making sense of that.  Otherwise, quick first pass --

`hush.el` with byte-compile using Emacs 28.1:
```
hush.el:82:60: Warning: `(cached (gethash key hush--default-cache))' is a
    malformed function
hush.el:82:60: Warning: `(cached (gethash key hush--default-cache))' is a
    malformed function
hush.el:97:30: Warning: reference to free variable `cached'
hush.el:96:41: Warning: reference to free variable `value-timestamp'
In hush-get:
hush.el:102:35: Warning: `(engine (or engine hush-default-engine))' is a
    malformed function
hush.el:110:54: Warning: reference to free variable `hush-engine'
hush.el:110:32: Warning: reference to free variable `callback'
In end of data:
hush.el:108:14: Warning: the function `callback' is not known to be defined.
hush.el:107:14: Warning: the function `hush-engine' is not known to be
    defined.
hush.el:96:26: Warning: the function `value-fresh' is not known to be defined.
hush.el:95:26: Warning: the function `value-timestamp' is not known to be
    defined.
hush.el:94:16: Warning: the function `if-let*' is not known to be defined.
```

I think this needs an explicit `(eval-when-compile (require 'subr-x))`

**Comment by tirimia** [comment]
Thank you so much for looking over it so quickly!
I have not, for the life of me, been able to get those warnings myself 😅, but I added the suggested code to the top of the file and also included CI via elisp-check in the repository to prevent regressions.

Have also updated the README and the Commentary of the package in the hopes of making the purpose of this library more clear, hope it helps 😸

**Comment by tirimia** [comment]
Update: also added Melpazoid to the CI, will keep in mind to use it for future projects

**Comment by riscy** [comment]
Thank you!  (And I appreciate hearing that melpazoid might be somewhat useful :)

Given your new Commentary, the builtin that immediately leaps to line is `auth-source` - I make use of, for example, `auth-source-pass` and there is for example [auth-source-1password](https://melpa.org/#/auth-source-1password).  Have you had a chance to make a comparison?

**Comment by riscy** [comment]
If `auth-source` is unwieldy (I don't disagree) another approach might be to complement or expand on its functionality.    But altogether I think an `auth-source` alternative would be fine, and I'd agree that a quick comparison should be done first.  (I'm not singling you out -- this is actually a pretty common request and I think it's good for users to see too e.g. in your Commentary.)

I think the degree to which auth-source is integrated various Emacs packages shouldn't be underestimated. It's automatically invoked when using tramp, for instance.

**Comment by tirimia** [comment]
Added a comparison both to the README and Commentary. I know you work hard to keep MELPA a source of quality packages, so the reviews have to be rigorous and objective, so thank you ❤️

**Comment by riscy** [comment]
Up to you but I may make it clear that this is an `auth-source` alternative even in your Summary line, e.g. `Pluggable secret manager (auth-source alternative)` (which is still under the 60 character limit for summaries).  This would probably help discoverability a great deal.

Not a blocker though - merging!

**Pull request merged**
