### PR TITLE
Add Siri shortcuts recipe

### PR DESCRIPTION
**Pull request by DaniruKun**
### Brief summary of what the package does

This package wraps the `shortcuts` command line tool, as well as the [Shortcuts URL scheme API.](https://support.apple.com/en-gb/guide/shortcuts-mac/apd621a1ad7a/5.0/mac/12.0)

It enables interactions with Siri Shortcuts on macOS Monterey and later.

### Direct link to the package repository

https://github.com/DaniruKun/siri-shortcuts.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

***None needed***

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by DaniruKun** [comment]
Melpazoid passes for latest commit: https://github.com/DaniruKun/shortcuts-el/runs/4476215344?check_suite_focus=true

**Comment by riscy** [comment]
Awesome, thanks!  This package looks great and the execution is good, but I'm personally wondering whether the name `shortcuts` might be a little too all-encompassing.  A name like `siri` or `siri-shortcuts` or `macos-shortcuts` would possibly improve discoverability, and make it clear that these shortcuts are only for macOS, and not for other operating systems.

**Comment by DaniruKun** [comment]
@riscy the main reasoning behind `shortcuts` was that in all of Apple official docs, only the word "Shortcuts" is used (e.g. `shortcuts` CLI, Shortcuts app in the App Store etc.).

But you have a good point about discoverability from outside, will `siri-shortcuts` be good enough?

**Comment by riscy** [comment]
I think `siri-shortcuts` would be great!

**Comment by DaniruKun** [comment]
@riscy updated the package to `siri-shortcuts`, as well as in the recipe and ran Melpazoid and checks again.

**Comment by riscy** [comment]
Thank you for accommodating!  Merging.

**Pull request merged**
