### PR TITLE
Added recipe for ob-solidity.

### PR DESCRIPTION
**Pull request by hrkrshnn**
### Brief summary of what the package does

Org babel integration for solidity language.

### Direct link to the package repository

https://github.com/hrkrshnn/ob-solidity

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings. There are two issues, that I don't think require fixes, as I'm using the org-babel template.
  
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
`ob-solidity.el` with checkdoc 0.6.2:
```
ob-solidity.el:63: Argument `processed-params' should appear (as PROCESSED-PARAMS) in the doc string
ob-solidity.el:85: Argument `body' should appear (as BODY) in the doc string
```

Thanks for this!  Quick first pass --

> There are two issues, that I don't think require fixes

I understand where you're coming from, but those are easy fixes and they're the same standards we look for in other packages.  Also consider that it takes more of my bandwidth to validate the exception rather than you fixing it.

`ob-solidity.el` with package-lint 20211122.1152:
```
4 issues found:
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
62:0: error: "org-babel-expand-body:solidity" doesn't start with package's prefix "ob-solidity".
62:0: error: `org-babel-expand-body:solidity' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
67:0: error: "org-babel-eval-solidity" doesn't start with package's prefix "ob-solidity".
```
From memory I think these are org-babel conventions so not necessarily blockers, but the first one's worth taking a look at.

`ob-solidity.el` with [melpazoid](https://github.com/riscy/melpazoid):
- ob-solidity.el#L97: You can use `not` or `null`

**Comment by riscy** [comment]
These are minor but in the interest of being consistent across reviews I'll hold off on merging this.  Feel free to ping when ready for another look!

**Comment by hrkrshnn** [comment]
@riscy Thanks for pinging me, sorry about not responding in time.

I've fixed the above recommendations in https://github.com/hrkrshnn/ob-solidity/pull/2.

> From memory I think these are org-babel conventions so not necessarily blockers, but the first one's worth taking a look at.

Yes, the last three are from org-babel conventions, so left them like that. Fixed the first one. Could you please review again, thanks.

**Comment by riscy** [comment]
Looks good here, thanks!  Merging.  And welcome to MELPA. :)

**Pull request merged**
