### PR TITLE
Cursor flash

### PR DESCRIPTION
**Pull request by Boruch-Baum**
### Brief summary of what the package does

* Highlights the cursor on buffer/window-switch

* Flashes a square of positions around POINT for a customizable interval.

This package temporarily highlights the area immediately surrounding POINT when navigating amongst buffers and windows. It is intended to assist in visually identifying the current POINT and the current window when many windows are on the same frame or when windows are very large (related (stackexchange question)[https://unix.stackexchange.com/questions/83167/emacs-finding-the-cursor-in-multiple-windows]).

NOTE: checkdoc complains about the package keywords I've chosen, but they come directly from the Emacs 27 info list

### Direct link to the package repository

https://github.com/Boruch-Baum/emacs-cursor-flash

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

N/A

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by manuel-uberti** [comment]
I'll let the MELPA team review this, but maybe you could consider highlighting the differences with [nav-flash](https://github.com/rolandwalker/nav-flash) and [beacon](https://github.com/Malabarba/beacon).

**Comment by Boruch-Baum** [comment]
On 2021-06-24 23:27, Manuel Uberti wrote:
>    I'll let the MELPA team review this, but maybe you could consider
>    highlighting the differences with [1]nav-flash and [2]beacon.

Thanks. I'll take a look at those. I didn't know either existed, and if
what I wrote is an unnecessary duplicate I'm happy to close the PR.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
On 2021-06-24 23:27, Manuel Uberti wrote:
>    I'll let the MELPA team review this, but maybe you could consider
>    highlighting the differences with [1]nav-flash and [2]beacon.

OK, that was quicker than I expected...

Based upon their documentation and graphics, the two packages seem
themselves very similar, almost identical, to each other in that they
both highlight a buffer *line* near the cursor position.

My submission is much more subtle and specific in that it highlights
only the positions surrounding POINT. To wit, if in the following ascii
diagram POINT is at 0, the positions marked X would be flashed:

       XXX
       X0X
       XXX

The distinction is particularly relevant in wide windows: My package
would identify an exact horizontal and vertical location, while the
description of the other packages indicate they only indicate a vertical
position.

I did not install and evaluate either of those packages, but I can say
that I went to the extra effort of guaranteeing a uniform presentation
for all positions of POINT, including special code for the cases of POINT
on the final line of a buffer, and on a line longer than those above and
below it.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by manuel-uberti** [comment]
Thank you for the detailed explanation.  :+1: 

It's up to the MELPA team now.

**Comment by riscy** [comment]
Thanks, looks like a handy package.  My main feedback:

byte-compile (using Emacs 27.1):
```
cursor-flash.el:272:1:Warning: the following functions are not known to be
    defined: yascroll-bar-mode, yascroll:show-scroll-bar, vline-mode
```
For when users don't have these packages, I'd suggest handling these using `declare-function`.  (You can still use `check-declare-file` to check them on your end.)

And some very minor stuff:
- `License: GPL3+` is fine as far as license boilerplate goes, but an [SPDX-License-Identifier](https://spdx.dev/ids/) can be a little less ambiguous for automatic detection.
- cursor-flash.el#L15: Use empty lines instead of `;;` on a line by itself within your Commentary
- cursor-flash.el#L189: Optionally use `unless ...` instead of `when (not ...)`

**Comment by Boruch-Baum** [comment]
On 2021-07-04 13:37, Chris Rayner wrote:
>    Thanks, looks like a handy package. My main feedback:

Hope you enjoy it! I would like to be "commit-stingy" and get all the
MELPA compliance changes squashed into a single commit, so I have a few
questions about some of your feedback items before I make the push:

>    byte-compile (using Emacs 27.1):
> cursor-flash.el:272:1:Warning: the following functions are not known to be
>     defined: yascroll-bar-mode, yascroll:show-scroll-bar, vline-mode
>
>    For when users don't have these packages, I'd suggest handling these
>    using declare-function. (You can still use check-declare-file to check
>    them on your end.)

1] Although it's only a compiler warning, I don't have any problem with
   using declare-function and have made that change. Do I *need* to use
   `check-declare-file'? The modes are being checked by their associated
   variable value, using `bound-and-true-p'.

>    And some very minor stuff:
>      * License: GPL3+ is fine as far as license boilerplate goes, but an
>        [1]SPDX-License-Identifier can be a little less ambiguous for
>        automatic detection.

2] MELPA uses the keyword form "License", while the footnote reference
   uses the keyword form "SPDX-License-Identifier", so how should the
   text read?

     SPDX-License-Identifier: GPL-3.0-or-later

     License: GPL-3.0-or-later

>      * cursor-flash.el#L15: Use empty lines instead of ;; on a line by
>        itself within your Commentary

3] Does that apply for (otherwise) empty only within the commentary
   section, or throughout the file. For example, I use that form within
   other documentation sections at the top of the file, and also as part
   of the headings delineating different sections of code.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
> Do I *need* to use `check-declare-file'? The modes are being checked by their associated variable value, using `bound-and-true-p'.

That confusion is my fault.  I just meant that if you wanted to check correctness (on your own or as part of a CI step), the `check-declare-file` is one way to do that on your end.  It's nothing you'd need to add to your code or anything.

> MELPA uses the keyword form "License"

This might be down to my own ignorance -- I didn't think we explicitly looked for that keyword.  If it's easy for you to do, can you point me to where that's being used/parsed by MELPA?

> how should the text read?

As for what to use: I would write `SPDX-License-Identifier: GPL-3.0-or-later`.  This is a minor issue (you can use either) but I personally prefer SPDX-License-Identifiers because they are formalized and support unambiguous lookup, whereas `License: BSD` for example could be anything.

> Does that apply for (otherwise) empty only within the commentary?

Yeah, only within the Commentary.  For example here's the conventional blank line in action in bytecomp.el:
```elisp
;;; Commentary:

;; The Emacs Lisp byte compiler.  This crunches lisp source into a sort
;; of p-code (`lapcode') which takes up less space and can be interpreted
;; faster.  [`LAP' == `Lisp Assembly Program'.]
;; The user entry points are byte-compile-file and byte-recompile-directory.
```
I suspect mentioning this isn't benefiting anyone so I may give that one up.  Putting a `;;` on that blank line causes `finder-commentary` to add an extra blank line, and many packages in the MELPA index have an extra newline in their commentary in the index as a result.  We could probably just clean it up downstream.

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by Boruch-Baum** [comment]
On 2021-07-17 10:56, Chris Rayner wrote:
>    Friendly ping. :)

And I have no idea why I put off pushing the commit. It was ready weeks
ago. Maybe I had lingering confusion about when to delete empty comment
lines. As it is, I had deleted *all* of them everywhere, but honestly I
don't like the style and deleting empty comment lines within a long
comment block (such as the commentary section) affects readability,
leading me to think that the separated paragraphs are separate comments
instead a continuum.

Commit finally pushed a few minutes ago.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
> I don't like the style and deleting empty comment lines within a long comment block

This is probably something I should stop mentioning in reviews, actually.  For what it's worth I think the issue is solved altogether by formatting like this:

```elisp
;;; Commentary:

;;; Long paragraph 1
;;; Long paragraph 1
;;
;;; Long paragraph 2
;;; Long paragraph 2

;;; TODOs:

;; ...

;;; Code:
```

In any case, thanks and apologies for the turnaround time.

**Pull request merged**
