### PR TITLE
Add Recipe for Noir-ts-mode

### PR DESCRIPTION
**Pull request by hhamud**
### Brief summary of what the package does

An emacs package that uses tree-sitter to help highlight noir syntax.

### Direct link to the package repository

https://github.com/hhamud/noir-ts-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by hhamud** [comment]
@riscy I know that you only check PRs during the weekend so can you do a quick check of mine before the next week?

**Comment by purcell** [comment]
Some quick fly-by observations:

- Missing `Package-Requires` dependency on Emacs 29
- Missing `defgroup` to declare the `'noir` group — and then the `:group` in the `defcustoms` would be redundant.
- `:version` in the `defcustom` is bogus: that's not the version of the Emacs standard library to which this library was added :-)
- Don't override `treesit-font-lock-level` — that's a user-level preference!

**Comment by hhamud** [comment]
1. Thanks for pointing it out I have added this in.
2. Would the example below be satisfactory?
4. Good point!. It has been removed. 

```elisp
(defgroup noir-ts nil
  "Major mode for editing Noir code."
  :prefix "noir-ts-"
  :group 'languages)

(defcustom noir-ts-mode-indent-offset 4
  "Number of spaces for each indentation step in `noir-ts-mode'."
  :type 'integer
  :safe 'integerp
  :group 'noir-ts)
```

**Comment by riscy** [comment]
Thanks for this, and yes that looks good.  Here's the latest on my end --

`noir-ts-mode.el` with package-lint 20230806.1331:
```
9 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a Homepage or URL header.
1:0: warning: The package summary should start with an uppercase letter or a digit.
26:0: error: Package should have a non-empty ;;; Commentary section.
31:10: error: You should depend on (emacs "29.1") if you need `treesit'.
90:3: error: You should depend on (emacs "29.1") if you need `treesit-font-lock-rules'.
194:9: error: You should depend on (emacs "29.1") if you need `treesit-ready-p'.
195:5: error: You should depend on (emacs "29.1") if you need `treesit-parser-create'.
222:5: error: You should depend on (emacs "29.1") if you need `treesit-major-mode-setup'.
```
(Fix your version dependency from emacs 29.0.90 and you should be golden on the dependency nags)

**Comment by hhamud** [comment]
> Thanks for this, and yes that looks good. Here's the latest on my end --
> 
> `noir-ts-mode.el` with package-lint 20230806.1331:
> 
> ```
> 9 issues found:
> 1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
> 1:0: error: Package should have a Homepage or URL header.
> 1:0: warning: The package summary should start with an uppercase letter or a digit.
> 26:0: error: Package should have a non-empty ;;; Commentary section.
> 31:10: error: You should depend on (emacs "29.1") if you need `treesit'.
> 90:3: error: You should depend on (emacs "29.1") if you need `treesit-font-lock-rules'.
> 194:9: error: You should depend on (emacs "29.1") if you need `treesit-ready-p'.
> 195:5: error: You should depend on (emacs "29.1") if you need `treesit-parser-create'.
> 222:5: error: You should depend on (emacs "29.1") if you need `treesit-major-mode-setup'.
> ```
> 
> (Fix your version dependency from emacs 29.0.90 and you should be golden on the dependency nags)

That should be all done now.

**Comment by riscy** [comment]
Ultimately this is minor but this has persisted --

`noir-ts-mode.el` with package-lint 20230806.1331:
```
1 issue found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
```
There are times when lower-case makes sense, but I believe even [the official site](https://tree-sitter.github.io/tree-sitter/) capitalizes that name.

Not a blocker, so I'll hit merge now.  And thanks again for this. :)

**Pull request merged**
