### PR TITLE
Add atcoder-tools recipe

### PR DESCRIPTION
**Pull request by sei40kr**
### Brief summary of what the package does

Compile and test a solution for an AtCoder contest problem from Emacs.

### Direct link to the package repository

https://github.com/sei40kr/emacs-atcoder-tools

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
A quick pass over the checklist:

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
atcoder-tools.el:0: The first line should be of the form: ";;; package --- Summary"
Warning (emacs): 
atcoder-tools.el:43: All variables and subroutines might as well have a documentation string
Warning (emacs): 
atcoder-tools.el:53: All variables and subroutines might as well have a documentation string
Warning (emacs): 
atcoder-tools.el:58: All variables and subroutines might as well have a documentation string
Warning (emacs): 
atcoder-tools.el:66: All interactive functions should have documentation
Warning (emacs): 
atcoder-tools.el:81: All interactive functions should have documentation
Warning (emacs): 
atcoder-tools.el:71: Error messages should *not* end with a period
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191027.20):
```
1 issue found:

1:0: warning: The package summary should start with an uppercase letter or a digit.
```

**Comment by sei40kr** [comment]
Sorry I've fixed the upstream, please review again.

**Comment by riscy** [comment]
Apologies for the long turnaround time, I've not had a working computer.  Running another quick pass:

### atcoder-tools.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
atcoder-tools.el:78: Argument `working-directory' should appear (as WORKING-DIRECTORY) in the doc string
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
No issues found.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
atcoder-tools.el:148:1:Warning: the following functions are not known to be
    defined: s-replace-all, f-dirname, s-join, f-join
```
(A `(require 'f)` is needed in addition to adding these to your `Package-Requires`)

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other static checks:
- atcoder-tools.el#L82: No need to sharp-quote (or quote) lambdas, but also no harm

**Comment by sei40kr** [comment]
@riscy 
Thank you for your review.

I updated the source code.
My apologize for bothering you repeatedly.

**Comment by riscy** [comment]
No problem!  This really looks like a useful package (with Rust support, great).

Everything appears to check out now.  Welcome to MELPA!

**Pull request merged**
