### PR TITLE
Stan mode packages

### PR DESCRIPTION
**Pull request by kaz-yos**
### Brief summary of what the package does
example

These are a family of emacs packages to provide programming support for Stan, a probabilistic programming language for Bayesian statistical inference.

- UPDATE stan-mode for indentation and syntax highlighting
- UPDATE stan-snippets for function argument completion
- NEW company-stan for auto-completion via company
- NEW eldoc-stan live help for function arguments
- NEW flycheck-stan on-the-fly syntax checking with stanc (stan compiler)
- NEW ac-stan for auto-completion via auto-complete

Note that they are kept in a single repo because they must be kept in sync with the common stan language definition file.

### Direct link to the package repository

https://github.com/stan-dev/stan-mode/

### Your association with the package

Current Maintainer

### Relevant communications with the upstream package maintainer

Not applicable

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback: No issues on [Travis-CI](https://travis-ci.org/stan-dev/stan-mode/jobs/587722072#L1977)
- [x] My elisp byte-compiles cleanly: No byte-compilation issues on [Travis-CI](https://travis-ci.org/stan-dev/stan-mode/jobs/587722072#L1482)
- [x] `M-x checkdoc` is happy with my docstrings: No issue on [Travis-CI](https://travis-ci.org/stan-dev/stan-mode/jobs/587722072#L2109). Run via elisp-lint
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi @kaz-yos -- thank you for this!  Can you please reopen six PR's for the six changed/added recipes?

**Comment by kaz-yos** [comment]
The packages have to be in the same repo, but I can split the PR. Thank for your time and effort!

**Comment by riscy** [comment]
That should be fine.  Thanks for doing that!  It helps distribute review bandwidth in a "fair" way.

**Comment by kaz-yos** [comment]
This PR has been split into individual packages. I'm closing this.

**Pull request closed without merging**
