### PR TITLE
Added rewriting-pcase recipe

### PR DESCRIPTION
**Pull request by owinebar**
### Brief summary of what the package does

Use pcase to rewrite the source of an elisp file with the text of a replacement value, without disturbing surrounding comments.

### Direct link to the package repository

https://github.com/owinebar/emacs-rewriting-pcase

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by mattiasb** [comment]
The URL gives a 404. You probably meant: https://github.com/owinebar/emacs-rewriting-pcase :)

**Comment by owinebar** [comment]
On Wed, Apr 19, 2023 at 6:20 AM Mattias Bengtsson ***@***.***>
wrote:

> The URL gives a 404. You probably meant:
> https://github.com/owinebar/emacs-rewriting-pcase :)
>
I'm not sure which URL you're talking about.  My eyes are probably skipping
the mistake.  The one in the recipe seems to be correct since "make
recipes/emacs-rewriting-pcase" works (for me at least).

Thanks,
Lynn

**Comment by owinebar** [comment]
> The URL gives a 404. You probably meant: https://github.com/owinebar/emacs-rewriting-pcase :)

Thanks!  Fixed.

Lynn

**Comment by riscy** [comment]
This is esoteric but interesting. I think adding the words "dev tool".  I might have also added "tools" (as in programming tools, per `finder-known-keywords`) to the list of `Keywords:`, but that's not a blocker.

**Comment by owinebar** [comment]
On Mon, Apr 24, 2023 at 3:15 PM Chris Rayner ***@***.***>
wrote:

> This is esoteric but interesting. I think adding the words "dev tool". I
> might have also added "tools" (as in programming tools, per
> finder-known-keywords) to the list of Keywords:, but that's not a blocker
>
I'm not sure where you mean to add the words "dev tool", but I'll
definitely add "tools" to the keywords.

It is esoteric, especially in its current state.  Eventually I'd like to
make it properly recursive, so it could be used for tasks like rewriting
obsolete constructs into modern ones (e.g. converting cl to cl-lib).  But
it's already useful for one particular code-rewriting job.

Thanks,
Lynn

**Comment by riscy** [comment]
Apologies, that strange phrasing fell out of over-editing (and I can partially blame the red-eye flight I just took).  Here's what I intended to write -- and this is what's appearing on GH right now too:

> I might have also added "tools" (as in programming tools, per finder-known-keywords) to the list of Keywords:, but that's not a blocker.

**Pull request merged**
