### PR TITLE
Add recipe for julia-ts-mode

### PR DESCRIPTION
**Pull request by ronisbr**
### Brief summary of what the package does

This package contains the Emacs major mode for the Julia programming language using tree-sitter for font-lock, indentation, imenu, and navigation. It is derived from [julia-mode](https://github.com/JuliaEditorSupport/julia-emacs).

This new implementation solves some problems that the old regex-based implementation cannot handle. The discussion related to using tree-sitter in Julia community can be found here:

https://github.com/JuliaEditorSupport/julia-emacs/issues/174

### Direct link to the package repository

https://github.com/ronisbr/julia-ts-mode

### Your association with the package

I am the author of the package.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Happy to see a ts-mode deriving reusing the parts of an existing major mode!

My pipeline is only able to run in Emacs 28, but I think these issues that the compiler teased our are valid:

`julia-ts-mode.el` with byte-compile using Emacs 28.1:
```
julia-ts-mode.el:109:1: Warning: defface for `julia-ts-mode-macro-face' fails
    to specify containing group
julia-ts-mode.el:113:1: Warning: defface for
    `julia-ts-mode-quoted-symbol-face' fails to specify containing group
julia-ts-mode.el:117:1: Warning: defface for
    `julia-ts-mode-interpolation-expression-face' fails to specify containing
    group
julia-ts-mode.el:121:1: Warning: defface for
    `julia-ts-mode-string-interpolation-face' fails to specify containing
    group
```
where these can be solved by adding a `defgroup` form near the top of the `;;; Code` for example:
```elisp
(defgroup julia-ts-mode nil
  "..."
  :prefix "julia-ts-"
  :group 'julia-mode ; not sure if this exists as a possible parent group?
  )
```

I also notice the file and repo are MIT licensed, but the license on the repository appears to be nonstandard, so that it isn't machine detectable by GitHub as an MIT-licensed repo.  For cases like these, Try to use a standard license file format (see: https://github.com/licensee/licensee).

**Comment by ronisbr** [comment]
Hi @riscy !

Thank you for your very fast review!

Sorry about those warnings, my Emacs compilation did not show any warning at all. I think I fixed all the problems you mentioned! Please, let me know if it is good to be merged.

Thanks!

**Comment by riscy** [comment]
> Sorry about those warnings, my Emacs compilation did not show any warning at all.

It's no problem at all, it's extremely common (and I do it too) because the Emacs byte-compiler uses whatever state the current Emacs runtime has, which can inadvertently suppress a lot of warnings (e.g. about things not being defined).

This looks good to go - welcome to MELPA. :)

**Comment by ronisbr** [comment]
Thanks @riscy !

**Pull request merged**
