### PR TITLE
pebble-mode

### PR DESCRIPTION
**Pull request by ArneBab**
### Brief summary of what the package does

Support for editing pebble templates https://pebbletemplates.io/

### Direct link to the package repository

https://github.com/ArneBab/pebble-mode

### Your association with the package

Creator

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Checklist looks great, but I have a couple of other lints I run on top:

`pebble-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- pebble-mode.el#L401: It's safer to sharp-quote function names; use `#'`
- pebble-mode.el#L393: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- pebble-mode.el#L394: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- pebble-mode.el#L395: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- pebble-mode.el#L396: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
```

Also, if you don't want your personal developer TODO list to be part of the `;;; Commentary` (and thus featured in the MELPA index) you can change `;; TODO` to `;;; TODO:` and verify using `M-: (lm-commentary)`

**Comment by ArneBab** [comment]
Thank you!  I fixed the sharp-quote and the commenting, but I’m unsure about the keymap, because I do not want to start empty, but build on the keymap of html-mode.

Can you give me a hint how to do that without the global key-setting?

**Comment by riscy** [comment]
You've got the sharp quote as `'#` instead of `#'`, but otherwise that looks good.

Re: the keybinding, the docs should give you some good pointers: https://www.gnu.org/software/emacs/manual/html_node/elisp/Inheritance-and-Keymaps.html

**Comment by ArneBab** [comment]
'# fixed — thank you for checking!

**Comment by riscy** [comment]
Sharp-quote looks good -- let me know how the inherited keybindings are going, too!

**Comment by ArneBab** [comment]
Thank you for coming back to me. pebble-mode now uses definition inside a defvar following the example in https://stackoverflow.com/questions/19308390/how-to-define-keymap-for-minor-mode-correctly (thank you for the pointer!)

⇒ https://github.com/ArneBab/pebble-mode/commit/5ebaf01fcf1ef8886934e4e0626a6fbec5c80c55

**Comment by riscy** [comment]
Thanks, the keybindings look great now and all the automatic lints are clear.  I think this is close to an easy merge, but I'm noticing another few issues as I take a deeper dive:

- The top-level form `(when pebble-enable-indent-on-save (add-hook 'pebble-mode-hook ...` looks incorrect to me - this will only be evaluated once (when the package loads) so the variable `pebble-enable-indent-on-save` will have no effect when toggled after loading.  Possibly this warrants its own minor mode, but that's probably overkill in this case; instead you could add a local after-save-hook when the mode is activated; that hook would call a function that checks the value of `pebble-enable-indent-on-save`.  `pebble-enable-indent-on-save`, by the way, appears like it should be a buffer-local variable, i.e. defined using `defvar-local` instead of `defvar`.
- `pebble-close-tag` calls out to `error`, but this looks like a `user-error` to me; `user-error`s do users the favor of not opening a backtrace on them when something goes wrong

**Comment by ArneBab** [comment]
Thank you! I moved the when into the mode-hook, so it now gets checked at mode activation (to avoid having too many save-hooks).

close tag now uses user-error.

**Comment by riscy** [comment]
Apparently by suggesting you use `user-error` I was also not realizing you'd need to depend on Emacs 24.3.  (I'd recommend you add the dependency on that Emacs version just to silence package-lint).

My thought re: adding an after-save hook would be code along these lines.  I think I was needlessly verbose above --
```elisp
;;;###autoload
(define-derived-mode pebble-mode html-mode  "Pebble"
  "Major mode for editing pebble files."
  :group 'pebble
  ;; ... 
  (set (make-local-variable 'indent-line-function) 'pebble-indent-line)
  ;; every pebble-mode buffer has an after-save hook
  (add-hook 'after-save-hook #'pebble-indent-buffer-hook nil t))

;; note the defvar-local; now users can change this variable on a per-buffer basis
(defvar-local pebble-enable-indent-on-save nil)

(defun pebble-indent-buffer-hook ()
  "Used as an `after-save-hook' if `pebble-indent-on-save' is non-nil."
  (when pebble-enable-indent-on-save (pebble-indent-buffer))
```

**Comment by ArneBab** [comment]
For the requirements: I should have set emacs-lisp-package as my flycheck-checker … thank you!

To the save hook: I understood this, but I’ve already gotten problems with too many save-hooks, so I don’t want to add one unconditionally. I now added a note in the commentary about this. Activation on a per-buffer basis could come in handy, so I now added part of your description to the custom description.

**Comment by riscy** [comment]
I see, and I understand.  Adding a hook to a mode whose definition you control seems unnecessary though -- what about?:

```elisp
(define-derived-mode pebble-mode html-mode  "Pebble"
  "Major mode for editing pebble files."
  :group 'pebble
  ;; ...
  (when pebble-enable-indent-on-save
    (add-hook 'after-save-hook #'pebble-indent-buffer nil 'make-it-local)))
```

**Comment by riscy** [comment]
There are a few checkdoc nags that I'll just mention:

`pebble-mode.el` with checkdoc 0.6.2:
```
pebble-mode.el:82: Open parenthesis in column 0 should be escaped
pebble-mode.el:87: Documentation strings should not start or end with whitespace
pebble-mode.el:78: First line is not a complete sentence
```

**Comment by ArneBab** [comment]
Thank you! I let checkdoc autofix those.

**Pull request merged**
