### PR TITLE
Add recipe for dirvish

### PR DESCRIPTION
**Pull request by alexluigit**
### Brief summary of what the package does

Dirvish is a minimalistic file manager based on dired-mode. 

### Direct link to the package repository

https://github.com/alexluigit/dirvish

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Just a very quick first pass --

`dirvish-advices.el` with checkdoc 0.6.2:
```
dirvish-advices.el:44: Argument `fn' should appear (as FN) in the doc string
dirvish-advices.el:82: Argument `fn' should appear (as FN) in the doc string
dirvish-advices.el:88: Argument `fn' should appear (as FN) in the doc string
dirvish-advices.el:95: Argument `win' should appear (as WIN) in the doc string
```

`dirvish-advices.el` with package-lint 20211122.1152:
```
2 issues found:
117:5: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
125:5: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

`dirvish-advices.el` with [melpazoid](https://github.com/riscy/melpazoid):
- dirvish-advices.el#L38: It's safer to sharp-quote function names; use `#'`

`dirvish-body.el` with checkdoc 0.6.2:
```
dirvish-body.el:44: All variables and subroutines might as well have a documentation string
dirvish-body.el:56: All variables and subroutines might as well have a documentation string
dirvish-body.el:61: All variables and subroutines might as well have a documentation string
dirvish-body.el:67: All variables and subroutines might as well have a documentation string
dirvish-body.el:40: White space found at end of line
```

`dirvish-body.el` with package-lint 20211122.1152:
```
1 issue found:
45:3: error: You should depend on (emacs "26.1") if you need `when-let*'.
```

`dirvish-body.el` with [melpazoid](https://github.com/riscy/melpazoid):
- dirvish-body.el#L73: It's safer to sharp-quote function names; use `#'`
- dirvish-body.el#L74: It's safer to sharp-quote function names; use `#'`

`dirvish-footer.el` with [melpazoid](https://github.com/riscy/melpazoid):
- dirvish-footer.el#L24: It may be simpler to just `require` this dependency; this doesn't affect just your package, but any other package that might make use of `format-spec`

`dirvish-header.el` with checkdoc 0.6.2:
```
dirvish-header.el:36: All variables and subroutines might as well have a documentation string
dirvish-header.el:55: First line is not a complete sentence
dirvish-header.el:56: Disambiguate dirvish-header-width by preceding w/ function,command,variable,option or symbol.
dirvish-header.el:70: You should convert this comment to documentation
```

`dirvish-header.el` with [melpazoid](https://github.com/riscy/melpazoid):
- dirvish-header.el#L65: `concat` may be unneeded; `insert` can take multiple arguments

`dirvish-helpers.el` with checkdoc 0.6.2:
```
dirvish-helpers.el:30: First line is not a complete sentence
dirvish-helpers.el:39: Argument `args' should appear (as ARGS) in the doc string
dirvish-helpers.el:52: All variables and subroutines might as well have a documentation string
dirvish-helpers.el:61: All variables and subroutines might as well have a documentation string
dirvish-helpers.el:72: Argument `win' should appear (as WIN) in the doc string
dirvish-helpers.el:76: All variables and subroutines might as well have a documentation string
dirvish-helpers.el:90: First line is not a complete sentence
dirvish-helpers.el:90: Argument `alist' should appear (as ALIST) in the doc string
dirvish-helpers.el:101: Argument `fileset' should appear (as FILESET) in the doc string
dirvish-helpers.el:145: First sentence should end with punctuation
dirvish-helpers.el:163: All variables and subroutines might as well have a documentation string
dirvish-helpers.el:178: All variables and subroutines might as well have a documentation string
dirvish-helpers.el:150: Error messages should *not* end with a period
```

`dirvish-helpers.el` with package-lint 20211122.1152:
```
5 issues found:
97:22: error: You should depend on (emacs "26.1") if you need `split-window-no-error'.
162:0: error: `dirvish-get--i/o-status' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
163:3: error: You should depend on (emacs "26.1") if you need `when-let*'.
177:0: error: `dirvish-set--i/o-status' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
178:3: error: You should depend on (emacs "26.1") if you need `when-let*'.
```

`dirvish-helpers.el` with [melpazoid](https://github.com/riscy/melpazoid):
- dirvish-helpers.el#L152: It's safer to sharp-quote function names; use `#'`
- dirvish-helpers.el#L81: It's safer to sharp-quote function names; use `#'`

`dirvish-minibuffer-preview.el` with checkdoc 0.6.2:
```
dirvish-minibuffer-preview.el:42: First sentence should end with punctuation
dirvish-minibuffer-preview.el:42: First line should be capitalized
dirvish-minibuffer-preview.el:54: First sentence should end with punctuation
dirvish-minibuffer-preview.el:54: First line should be capitalized
dirvish-minibuffer-preview.el:86: First sentence should end with punctuation
dirvish-minibuffer-preview.el:86: First line should be capitalized
dirvish-minibuffer-preview.el:96: Argument `fn' should appear (as FN) in the doc string
```

`dirvish-minibuffer-preview.el` with package-lint 20211122.1152:
```
4 issues found:
7:0: error: Package-Requires outside the main file have no effect.
55:3: error: You should depend on (emacs "26.1") if you need `when-let*'.
100:3: error: You should depend on (emacs "26.1") if you need `when-let*'.
109:52: error: You should depend on (emacs "27.1") if you need `minibuffer-history-value'.
```

`dirvish-parents.el` with checkdoc 0.6.2:
```
dirvish-parents.el:72: All variables and subroutines might as well have a documentation string
```

`dirvish-preview.el` with checkdoc 0.6.2:
```
dirvish-preview.el:68: Argument `entry' should appear (as ENTRY) in the doc string
dirvish-preview.el:122: All variables and subroutines might as well have a documentation string
dirvish-preview.el:135: First sentence should end with punctuation
dirvish-preview.el:135: First line should be capitalized
dirvish-preview.el:135: Argument `proc' should appear (as PROC) in the doc string
dirvish-preview.el:146: Argument `preview-window' should appear (as PREVIEW-WINDOW) in the doc string
```

`dirvish-preview.el` with package-lint 20211122.1152:
```
4 issues found:
39:42: error: You should depend on (emacs "27.1") if you need `mailcap-file-name-to-mime-type'.
62:23: error: You should depend on (emacs "26.1") if you need `file-attribute-size'.
97:24: error: You should depend on (emacs "27.1") if you need `mailcap-file-name-to-mime-type'.
158:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

`dirvish-preview.el` with [melpazoid](https://github.com/riscy/melpazoid):
- dirvish-preview.el#L91: It's safer to sharp-quote function names; use `#'`
- dirvish-preview.el#L116: It's safer to sharp-quote function names; use `#'`

`dirvish-vars.el` with checkdoc 0.6.2:
```
dirvish-vars.el:61: First sentence should end with punctuation
dirvish-vars.el:61: First line should be capitalized
dirvish-vars.el:94: Documentation strings should not start or end with whitespace
dirvish-vars.el:94: First sentence should end with punctuation
dirvish-vars.el:98: First line is not a complete sentence
dirvish-vars.el:103: First line is not a complete sentence
dirvish-vars.el:140: First line is not a complete sentence
dirvish-vars.el:222: Lisp symbol `dirvish-window' should appear in quotes
dirvish-vars.el:274: First line is not a complete sentence
```

`dirvish-vars.el` with package-lint 20211122.1152:
```
2 issues found:
29:0: error: "recentf-list" doesn't start with package's prefix "dirvish".
217:0: error: `dirvish-i/o-queue' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
```
(I'm not sure if the recentf-list defvar is even necessary, but correct me if I'm wrong)

`dirvish.el` with checkdoc 0.6.2:
```
dirvish.el:199: Messages should start with a capital letter
```

`dirvish.el` with package-lint 20211122.1152:
```
4 issues found:
1:0: warning: The package summary should not end with a period.
1:0: warning: The package summary should start with an uppercase letter or a digit.
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
202:3: error: You should depend on (emacs "26.1") if you need `when-let*'.
```

`dirvish.el` with [melpazoid](https://github.com/riscy/melpazoid):
- dirvish.el#L305: It's safer to sharp-quote function names; use `#'`
- dirvish.el#L306: It's safer to sharp-quote function names; use `#'`
- dirvish.el#L133: It's safer to sharp-quote function names; use `#'`
- dirvish.el#L5: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)

**Comment by alexluigit** [comment]
Hi @riscy , thanks for your review!
I have fixed them all, here is the log from melpazoid: 

https://github.com/alexluigit/dirvish/runs/4497213419?check_suite_focus=true#step:5:1

**Comment by riscy** [comment]
Thanks, that was quick!  Looks like a neat package.  Some (non-blocking) suggestions which I'll leave here, but this looks good to merge:

- In `dirvish-init` you use `posframe-workable-p` to check whether dirvish can run; if not, it says "requires GUI" -- but if at some point `posframe-workable-p` works in the text UI, will this message/check still be accurate?  If not it might be a good idea to reproduce the check in your own code, just so nothing shifts beneath your feet
- The `defvar` on `recentf-list` in dirvish-header.el seems unnecessary on a _very_ quick first glance (maybe it deserves a comment if I'm mistaken)
- In a function with a name like `dirvish-get--parent` it's typical to put the double-dashes after the package name (e.g. `dirvish--get-parent` instead) to signify a private/internal function or variable.  In the same vein the function `dirvish-internal-paste` seems like it could be renamed to `dirvish--paste` to get the point across idiomatically.  But I may not be keying into the pattern you're using here
- Should the `error` on dirvish.el:140 be a `user-error`?
- I notice you're using an SPDX license identifier in dirvish.el, but GPL boilerplate in the other files -- possibly you could align all the files with an SPDX license identifier (easier to machine-identify, and easier for you to relicense if you should decide to in the future); definitely minor though

All that said, welcome to MELPA. :)

**Comment by alexluigit** [comment]
> * In `dirvish-init` you use `posframe-workable-p` to check whether dirvish can run; if not, it says "requires GUI" -- but if at some point `posframe-workable-p` works in the text UI, will this message/check still be accurate?  If not it might be a good idea to reproduce the check in your own code, just so nothing shifts beneath your feet

Would this error message be more reasonable?
`Dirvish.el: posframe unable to initialize under current Emacs instance`

> * The `defvar` on `recentf-list` in dirvish-header.el seems unnecessary on a _very_ quick first glance (maybe it deserves a comment if I'm mistaken)

Fixed.


> * In a function with a name like `dirvish-get--parent` it's typical to put the double-dashes after the package name (e.g. `dirvish--get-parent` instead) to signify a private/internal function or variable.  In the same vein the function `dirvish-internal-paste` seems like it could be renamed to `dirvish--paste` to get the point across idiomatically.  But I may not be keying into the pattern you're using here

Thank you very much for this. I always get confused by how this convention works. Fixed.

> * Should the `error` on dirvish.el:140 be a `user-error`?

Fixed.


> * I notice you're using an SPDX license identifier in dirvish.el, but GPL boilerplate in the other files -- possibly you could align all the files with an SPDX license identifier (easier to machine-identify, and easier for you to relicense if you should decide to in the future); definitely minor though

I didn't know it can be done with any files, thanks for pointing out. 

Thanks for merging and your thoughtful suggestions!

**Comment by riscy** [comment]
> Would this error message be more reasonable?

Yes, I think that accurately puts the blame on the posframe check.  Makes good sense to me.

> Thanks for merging and your thoughtful suggestions!

No problem -- thanks to you too for submitting this.

**Pull request merged**
