### PR TITLE
New pack/fuz

### PR DESCRIPTION
**Pull request by cireu**
### Brief summary of what the package does

- `fuz.el` :: fuzzy scoring and matching utils dynamic modules
- `helm-fuz.el` :: Use `fuz` with `helm`
- `ivy-fuz.el` :: Use `fuz` with `ivy`

### Direct link to the package repository

https://github.com/cireu/fuz.el

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by Silex** [comment]
What's the difference with https://github.com/lewang/flx (supported by ivy)?

**Comment by cireu** [comment]
@Silex 

I take a simple look at flx

1. fuz.el is a simple elisp binding of Rust crate [fuzzy-matcher](https://github.com/lotabout/fuzzy-matcher), it use an O(m*n) time complexity algorithm, in my exprience it's more precise than flx's one.

For example, I type `spcl` to search all callable, and sort them with `helm-flx` and `helm-fuz`.

This is `helm-flx`

图片

And this is `helm-fuz` 

图片

In fact, `fuz.el` scoring algorithm is similar with this PR https://github.com/abo-abo/swiper/pull/1518

2. flx.el build lots of cons while building heatmap for scoring(It use cons to pass multiple value), these conses need time to be GCed. fuz.el extract string from Elisp VM, and the heatmap building and scoring was done by rust, so `fuz.el` needs less GC time while querying on a long long string(Quantified benchmark needed)

3. flx.el provide a memoization function, fuz.el don't include it in the core part, but you can find a `fuz-memo-function` in `fuz-extra.el`

> does it also favor the start of words?

Of course, fuzzy scoring algorithm should put more weights on "prefix of boundary"(matching start of string, matching the substring followed with a separator)

**Comment by cireu** [comment]
Close since I meet some issue with bootstraping dynamic module.

**Comment by Silex** [comment]
@cireu: neat, thanks for the explanations!

So, the difference between yours and https://github.com/abo-abo/swiper/pull/1518 is that yours is faster because rust?

**Comment by cireu** [comment]
On Tue, 06 Aug 2019 15:02:29 +0800,
Philippe Vaucher wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (7bit)>]
> @cireu: neat, thanks for the explanations!
> 
> So, the difference between yours and abo-abo/swiper#1518 is that yours is faster because rust?
> 
> ―
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

I believe so, but need some bench.

**Comment by cireu** [comment]
Update README and I think it's suitable for melpa now.

**Comment by riscy** [comment]
Hi @cireu, can you split this up into three PR's?  Typically it's one PR per new package.  Thanks. :)

**Comment by cireu** [comment]
@riscy  I add another pull request for helm-fuz. https://github.com/melpa/melpa/pull/6360

And I don't want to publish ivy-fuz because it's not stable enough now.

**Comment by riscy** [comment]
Thanks so much for that -- it's much appreciated.

**Comment by riscy** [comment]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
fuz.el:29: Name emacs should appear capitalized as Emacs
Warning (emacs): 
fuz.el:71: Symbols t and nil should not appear in single quotes
Warning (emacs): 
fuz.el:81: Symbols t and nil should not appear in single quotes
Warning (emacs): 
fuz.el:116: Error messages should *not* end with a period
```

```
Warning (emacs): 
fuz-extra.el:36: Argument `face' should appear (as FACE) in the doc string
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
1 issue found:
47:31: error: Aliases should start with the package's prefix "fuz".
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
```
fuz.el:52:Warning (check-declare): said `fuz-core-calc-score-clangd' was
    defined in fuz-core.el: file not found
fuz.el:53:Warning (check-declare): said `fuz-core-calc-score-skim' was defined
    in fuz-core.el: file not found
fuz.el:54:Warning (check-declare): said `fuz-core-find-indices-clangd' was
    defined in fuz-core.el: file not found
fuz.el:55:Warning (check-declare): said `fuz-core-find-indices-skim' was
    defined in fuz-core.el: file not found
```

Sharp-quote suggestions:
- fuz.el#L59: Alias targets should be sharp-quoted; use `#'`
- fuz.el#L60: Alias targets should be sharp-quoted; use `#'`
- fuz.el#L61: Alias targets should be sharp-quoted; use `#'`
- fuz.el#L62: Alias targets should be sharp-quoted; use `#'`

**Comment by cireu** [comment]
> Sharp-quote suggestions:

Fixed in https://github.com/cireu/fuz.el/commit/db75e054ca046ef9bd6f80aede5836541597035e

**Comment by purcell** [comment]
Looks good, thanks - merged!

**Comment by tarsius** [comment]
What is `fuz-core`? It is being soft-required in `fuz.el` but there is no such library. You use a few functions from `fuz-core` and have instructed the byte-compiler to not warn about that. Why isn't `fuz-core` publicly available and what happens if a user tries to use functionality that depends on it?

**Comment by cireu** [comment]
> What is `fuz-core`? It is being soft-required in `fuz.el` but there is no such library. You use a few functions from `fuz-core` and have instructed the byte-compiler to not warn about that. Why isn't `fuz-core` publicly available and what happens if a user tries to use functionality that depends on it?

It was defined in dynamic modules, documentations and arglist were generated by Rust,

Please check all `#[defun]` block in https://github.com/cireu/fuz.el/blob/master/src/dynmod.rs

**Comment by tarsius** [comment]
A thanks for the information!

**Pull request merged**
