### PR TITLE
Add enlightened theme

### PR DESCRIPTION
**Pull request by slondr**
### Brief summary of what the package does

An enlightened Emacs theme

### Direct link to the package repository

https://hg.sr.ht/~slondr/enlightened

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi, here's a quick first pass --

package-lint-current-buffer (using version 20200419.406):
```
5 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
1:0: warning: The package summary should start with an uppercase letter or a digit.
1:0: error: There is no (provide 'enlightened-theme) form.
20:0: warning: Closing parens should not be wrapped onto new lines.
117:0: warning: Closing parens should not be wrapped onto new lines.
```
You can add `(provide 'enlightened-theme)` under the `provide-theme` form.  "An Emacs 24 theme..." as a summary line could be improved -- why not just "A theme based on enlightened"?  

A couple requests we have regarding the licensing:
- Please add a LICENSE or COPYING file to the repository
- Please add license boilerplate or an [SPDX-License-Identifier](https://spdx.org/using-spdx-license-identifier) to enlightened-theme.el
- Use a GPL-compatible license.
  See: https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

**Comment by slondr** [comment]
Hi, I believe I've addressed your concerns

1. Updated the package description to simply "A theme based on enlightened" (with uppercase first letter)
1. Added `(provide 'enlightened-theme)`
1. Fixed the style issues
1. Added COPYING to the repository
1. Added an SPDX license identifier to the source code

Please let me know if there's anything else I should do 
Thank you

**Comment by riscy** [comment]
Great, the license stuff looks sorted -- thank you.

I did another run over the checklist and here's the latest:

### enlightened-theme.el ###

byte-compile-file (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
enlightened-theme.el:0: You should have a section marked ";;; Commentary:"
```

check-declare-file (optional):
- No issues!

package-lint-current-buffer (using version 20200419.406):
```
3 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a ;;; Commentary section.
1:0: error: Package should have a Homepage or URL header.
```

**Comment by tarsius** [comment]
Friendly ping! :ping_pong:

**Comment by slondr** [comment]
@riscy I believe I fixed those

**Comment by riscy** [comment]
Here's the latest --

checkdoc (using version 0.6.2):
```
Warning (emacs): 
enlightened-theme.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210127.158):
```
2 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a ;;; Commentary section.
```

**Comment by slondr** [comment]
I do have a commentary section

**Comment by tarsius** [comment]
The `:` at the end of `Commentary` is missing. The line has to be:

```
;;; Commentary:
```

**Comment by slondr** [comment]
Ah, sorry about that — I’ve fixed it now. 
Package-lint now reports nothing except the the warning about versioning on non-MELPA archives, which, this being MELPA, I’m assuming I can safely ignore?

**Pull request merged**
