### PR TITLE
add counsel-css recipe

### PR DESCRIPTION
**Pull request by waymondo**
### Brief summary of what the package does

counsel-css is an ivy-mode backend for css selectors (works for SCSS and LESS too). It also has a hook to integrate its parser into Imenu.

### Direct link to the package repository

https://github.com/hlissner/emacs-counsel-css

### Your association with the package

enthusiastic user

### Relevant communications with the upstream package maintainer

none needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by manuel-uberti** [comment]
Any updates on this one? :)

**Comment by purcell** [comment]
Looks good, and I've merged this now, but hey, @hlissner, you should please add a minimum Emacs version dependency to the `Package-Requires` header. I see you're relying on `subr-x`: `package-lint` can help you see which version you might need to specify. It's best not to rely on transitive dependencies that `counsel` etc. might have.

**Comment by hlissner** [comment]
@purcell And done! 

However, package-lint didn't complain about `subr-x` missing from my Package-Requires header, nor could I figure out what version to use. With `(subr-x "0")` it complains:

```
error     Package subr-x is not installable. (emacs-lisp-package)
warning   Use a properly versioned dependency on "subr-x" if possible. (emacs-lisp-package)
```

In a brief search, I couldn't find another package that depends on subr-x to reference. Any advice?

**Comment by purcell** [comment]
Yeah, `package-lint` will detect the use of many _functions_ from `subr-x`, and suggest a corresponding minimum Emacs version. You're correct that `subr-x` itself shouldn't be declared as a package dependency.

**Pull request merged**
