### PR TITLE
Add recipe for org-linenote

### PR DESCRIPTION
**Pull request by seokbeomKim**
### Brief summary of what the package does

A note-taking package motivated by [vscode 'Line Note' extension](https://marketplace.visualstudio.com/items?itemName=tkrkt.linenote).

### Direct link to the package repository

https://github.com/seokbeomKim/org-linenote

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
This looks interesting.  Have you compared it with other Emacs/Org-based annotation libraries on MELPA?

**Comment by seokbeomKim** [comment]
I tried other note packages like org-roam, denote, and org-remark. I think they are pretty good for personal use (or project management), but not for the code-based source code project.

The main difference is the purpose of sharing with others by keeping notes based on the directory tree of a project. So, for users who want to analyze the code and share the notes with others (including vscode users), this package could be useful.

**Comment by alphapapa** [comment]
Of those examples, org-remark seems like the only one aimed at annotation, and it looks featureful.  It would be helpful to potential users if you compared them.

Besides that one, here are some others that seem relevant:

- https://github.com/bastibe/annotate.el: Mentions "code reviews"
- https://github.com/org-noter/org-noter: Doesn't mention source code, but seems likely to work with it too

I know that it can be tedious, but a few notes comparing similar tools can help save users time in deciding which one meets their needs.

**Comment by seokbeomKim** [comment]
Thanks for the feedback. 
You are correct that it seems to not be easy to understand the difference from other note-taking packages.
I rewrote the README.org but I am not sure this is enough for others, but I hope the overall description could be useful to understand the package's specification.

**Comment by alphapapa** [comment]
Thanks, that seems like a big improvement.

**Comment by riscy** [comment]
Thank you both, this is a great outcome.  Here's a quick first pass of the checks --

`org-linenote.el` with byte-compile using Emacs 29.2:
```
org-linenote.el:108:8: Warning: the function `string-remove-prefix' is not known to be defined.
```
This needs a `(require 'subr-x)`

`org-linenote.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- org-linenote.el#L255: It's safer to sharp-quote function names; use `#'`
- org-linenote.el#L133: It's safer to sharp-quote function names; use `#'`
- org-linenote.el#L76: Consider `beginning-of-line`
- org-linenote.el#L164: This double negation can be collapsed (`not` aliases `null`)
- org-linenote.el#L246: Loading a package should rarely add hooks (Can we instead encapsulate this in a minor mode or activation function?
- org-linenote.el#L247: Loading a package should rarely add hooks
```

Package and license:
- Avoid specifying `:branch` except in unusual cases (if `main` is your default branch, you don't need this in your recipe)

**Comment by seokbeomKim** [comment]
@riscy, Thanks for the feedback. 

I checked warnings from melpazoid and byte-compiling and modified the code. 
According to the feedback, I added the minor mode into the code.

**Comment by riscy** [comment]
Thank you - the summary line is triggering a few minor package-lint nags:

```
3 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
1:0: warning: The package summary is too long. It should be at most 60 characters.
1:0: warning: The package summary should not end with a period.
```

I think writing `A note package inspired by VS Code's Linenote` brings this right into line with those standards, and then this is an easy merge.

**Comment by seokbeomKim** [comment]
Sorry for making you cumbersome. I have updated the summary.

**Comment by riscy** [comment]
Looks great!  And thank you likewise for your patience with the process.

**Pull request merged**
