### PR TITLE
Add recipe for txl

### PR DESCRIPTION
**Pull request by tmalsburg**
### Brief summary of what the package does

Interface to DeepL http api for machine translation.

### Direct link to the package repository

https://github.com/tmalsburg/txl.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### Notes
Package-lint reported that `request` and `guess-language` are not installable but I verified that they are installable.

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

`txl.el` with byte-compile using Emacs 29.4:
```
txl.el:99:2: Warning: custom-declare-variable `txl-deepl-split-sentences' docstring wider than 80 characters
txl.el:99:12: Warning: defcustom for `txl-deepl-split-sentences' has syntactically odd type `'(choice (const :tag No splitting nil) (const :tag Split on interpunction and on newlines t) (const :tag Split on interpunction only, ignoring newlines  'nonewlines))'
txl.el:114:12: Warning: defcustom for `txl-deepl-formality' has syntactically odd type `'(choice (const :tag Default 'default) (const :tag More formal language 'more) (const :tag Less formal language 'less))'
In end of data:
txl.el:192:14: Warning: the function `org-forward-paragraph' is not known to be defined.
txl.el:191:16: Warning: the function `org-end-of-item-list' is not known to be defined.
txl.el:178:14: Warning: the function `org-backward-paragraph' is not known to be defined.
txl.el:177:16: Warning: the function `org-beginning-of-item-list' is not known to be defined.
txl.el:176:16: Warning: the function `org-in-item-p' is not known to be defined.
```
Probably a `(require 'org)` is needed.

`txl.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- txl.el#L158: It's safer to sharp-quote function names; use `#'`
- txl.el#L206: It's safer to sharp-quote function names; use `#'`
- txl.el#L252: It's safer to sharp-quote function names; use `#'`
```

Package and license:
- Avoid specifying `:branch` except in unusual cases (if `master` is your default branch, we'll pick that up)
- Add a LICENSE file to the repository - see: https://github.com/licensee/licensee

**Comment by tmalsburg** [comment]
Thank you, and sorry for overlooking the byte compile warnings (looked at the wrong buffer for output).  I think I fixed all issues above, plus some more picked up by byte-compiling in Emacs 31.0.50 (quoting functions with `#'`).

**Comment by riscy** [comment]
I'm not seeing any byte-compilation issues here, but your header should include the package summary *and* the lexical-binding note, e.g.
```elisp
;;; txl.el --- Provides machine translation via DeepL's REST API -*- lexical-binding: t -*-
```
but beyond that this looks good to go.

**Comment by tmalsburg** [comment]
Ah, wasn't aware that description and lexical-binding need to be on the same line.  Fixed it. Thank you!

**Comment by riscy** [comment]
Thanks!  Looks good to go.

**Pull request merged**
