### PR TITLE
Revert "Add tabulated-list-ext package"

### PR DESCRIPTION
**Pull request by purcell**
Reverts melpa/melpa#3652, as suggested by author.

### CODE REVIEW

**Comment by Silex** [comment]
Hey! that was a bit too quick, I didn't update `docker.el` with the new dependency yet!

**Comment by Silex** [comment]
I'm tring to hack my way into refactoring docker.el with the new dependency, but it's not trivial. Given the build already started, it means I have ~4 hours to succeed before the next build.

docker.el will be broken in the meantime but that's ok, shit happens :wink:

**Comment by Silex** [comment]
@purcell: ok, I managed to repair it just before the new build started :relieved:

**Comment by purcell** [comment]
LOL, sorry... was trying to be efficient in the little window I have each day for MELPA work!

**Comment by Silex** [comment]
No worries, it gave me the motivation to work on my package :+1:

**Pull request merged**
