### PR TITLE
add nndiscourse

### PR DESCRIPTION
**Pull request by dickmao**
### Brief summary of what the package does

A Gnus backend for Discourse

### Direct link to the package repository

https://github.com/dickmao/nndiscourse

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

1. Please use proper indent in the whole Elisp file.
  Proper indent helps us understand Lisp code quickly.
2. Please use `prin1-to-string` instead of an empty `format`.
3. Please concider using `awhen` instead of `aif` which have no `else` form.
4. Please remove top-level sexp.
All packages should not have side-effects just require package for user-experience. see https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html#Coding-Conventions
> Simply loading a package should not change Emacs's editing behavior. Include a command or commands to enable and disable the feature, or to invoke it. 

I suggest all packages should have `*-setup` and `*-teardown` function if some setup is needed.
(There are many top-level sexp, I cannot arrange `*-setup` and `*-teardown` function...)

**Comment by riscy** [comment]
Quick first pass on this, but I agree with @conao3  -- *most* of the time, when you're adding hooks (or fsetting), you want to be doing these changes with the togglability of a minor mode.

The recipe looks complicated, maybe moreso than it needs to be?  Maybe it would be simplest if it only included the elisp files, and then did a `bundle-install` using the GitHub URL to your gem, rather than having the gem packaged with the elisp files.  Is that a possibility?

Other than that:

### nndiscourse.el ###

byte-compile-file (using Emacs 26.3):
```
nndiscourse.el:50:1:Error: Cannot open load file: No such file or directory, json-rpc
```
Missing a `Package-Requires` in this case.

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200226.2001):
- No issues!

...except!:
```
;; Evade package-lint!
(fset 'gnus-user-format-function-S
      (symbol-function 'nndiscourse--format-time-elapsed))
```
Should this be override advice?  Should it be added to a global minor mode, to let the users toggle the behavior on and off in case they run into issues?

Experimental static checks/suggestions:
- nndiscourse.el#L371: It's safer to sharp-quote function names; use `#'`
- nndiscourse.el#L985: It's safer to sharp-quote function names; use `#'`
- nndiscourse.el#L1081: It's safer to sharp-quote function names; use `#'`
- nndiscourse.el#L1082: It's safer to sharp-quote function names; use `#'`

**Comment by dickmao** [comment]
> The recipe looks complicated, maybe moreso than it needs to be?

I'd like to beg off a two-stage install.  I'm a beginner rubyist and bundler confuses me generally.  I also don't think the recipe is complicated, and as I mentioned in `nnreddit`, the ruby code makes no sense without the elisp.  That is, the ruby code should not comprise an independent gem.

> nndiscourse.el:50:1:Error: Cannot open load file: No such file or directory, json-rpc

Fixed, thank you. https://github.com/dickmao/nndiscourse/commit/2721fdff07d793e0b8019fc1e5d34264a2ef7fad

> (fset 'gnus-user-format-function-S
>       (symbol-function 'nndiscourse--format-time-elapsed))
> Should it be added to a global minor mode?

No?  There is so much that is "wrong" (by modern standards) about Gnus that this small liberty seems *de minimus*.  There are precedents for this namespace pollution in `gnus-diary.el` and `gnus-registry.el`.

**Comment by dickmao** [comment]
> ;; Evade package-lint!
> (fset 'gnus-user-format-function-S

Hum I now remember trying to work around this for nnreddit.  I forget the details but something about Gnus made this very hard -- like the `gnus-parameters` (Gnus's contortionist mechanism for decoupling backend namespaces) didn't allow hygienically setting function bindings, only value bindings (and Gnus line formatting needs to get at a function binding).

**Comment by riscy** [comment]
Okay, this looks good then.  Thanks!

**Pull request merged**
