### PR TITLE
Add recipie for haskell-ts-mode

### PR DESCRIPTION
**Pull request by ScamChamp**
### Brief summary of what the package does
A haskell major mode that uses treesitter, provided stuff like indentation, syntax colouring, imenu, etc...

### Direct link to the package repository

https://codeberg.org/pranshu/haskell-ts-mode/src/branch/main

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

`haskell-ts-mode.el` with byte-compile using Emacs 29.4:
```
haskell-ts-mode.el:317:47: Warning: Unused lexical argument `override'
haskell-ts-mode.el:317:56: Warning: Unused lexical argument `start'
haskell-ts-mode.el:317:62: Warning: Unused lexical argument `end'
In haskell-ts-fontify-type:
haskell-ts-mode.el:325:48: Warning: Unused lexical argument `override'
haskell-ts-mode.el:325:57: Warning: Unused lexical argument `start'
haskell-ts-mode.el:325:63: Warning: Unused lexical argument `end'
In haskell-ts-imenu-name-function:
haskell-ts-mode.el:334:11: Warning: macro `haskell-ts-imenu-name-function' defined too late
haskell-ts-mode.el:377:17: Warning: reference to free variable `eglot-server-programs'
haskell-ts-mode.el:377:17: Warning: assignment to free variable `eglot-server-programs'
In end of data:
haskell-ts-mode.el:365:15: Warning: the function `comint-check-proc' might not be defined at runtime.
haskell-ts-mode.el:361:4: Warning: the function `comint-send-string' might not be defined at runtime.
haskell-ts-mode.el:360:4: Warning: the function `comint-send-region' might not be defined at runtime.
haskell-ts-mode.el:323:36: Warning: the function `treesit-node-children' might not be defined at runtime.
haskell-ts-mode.el:315:4: Warning: the function `treesit-major-mode-setup' might not be defined at runtime.
haskell-ts-mode.el:282:12: Warning: the function `treesit-ready-p' might not be defined at runtime.
haskell-ts-mode.el:61:6: Warning: the function `treesit-font-lock-rules' might not be defined at runtime.
```

`haskell-ts-mode.el` with checkdoc 0.6.2 (fix *within reason*):
```
haskell-ts-mode.el:61: All variables and subroutines might as well have a documentation string
haskell-ts-mode.el:279: First sentence should end with punctuation
haskell-ts-mode.el:279: First line should be capitalized
haskell-ts-mode.el:318: All variables and subroutines might as well have a documentation string
haskell-ts-mode.el:326: All variables and subroutines might as well have a documentation string
haskell-ts-mode.el:335: All variables and subroutines might as well have a documentation string
haskell-ts-mode.el:342: All variables and subroutines might as well have a documentation string
haskell-ts-mode.el:346: All variables and subroutines might as well have a documentation string
haskell-ts-mode.el:349: All variables and subroutines might as well have a documentation string
haskell-ts-mode.el:352: All variables and subroutines might as well have a documentation string
haskell-ts-mode.el:355: All variables and subroutines might as well have a documentation string
haskell-ts-mode.el:358: First line should be capitalized
haskell-ts-mode.el:358: Argument `start' should appear (as START) in the doc string
haskell-ts-mode.el:364: All interactive functions should have documentation
haskell-ts-mode.el:371: All variables and subroutines might as well have a documentation string
haskell-ts-mode.el:286: White space found at end of line
```

`haskell-ts-mode.el` with package-lint 20240507.1722:
```
71 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:70: warning: You should depend on (emacs "24.1") if you need lexical-binding.
8:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
29:47: error: You should depend on (emacs "29.1") if you need `treesit'.
61:5: error: You should depend on (emacs "29.1") if you need `treesit-font-lock-rules'.
81:1: warning: Closing parens should not be wrapped onto new lines.
129:18: error: You should depend on (emacs "29.1") if you need `treesit-node-prev-sibling'.
130:30: error: You should depend on (emacs "29.1") if you need `treesit-node-type'.
131:14: error: You should depend on (emacs "29.1") if you need `treesit-node-prev-sibling'.
160:17: error: You should depend on (emacs "29.1") if you need `treesit-node-prev-sibling'.
161:29: error: You should depend on (emacs "29.1") if you need `treesit-node-type'.
162:14: error: You should depend on (emacs "29.1") if you need `treesit-node-prev-sibling'.
169:8: error: You should depend on (emacs "29.1") if you need `treesit-node-start'.
169:28: error: You should depend on (emacs "29.1") if you need `treesit-node-child'.
179:17: error: You should depend on (emacs "29.1") if you need `treesit-node-prev-sibling'.
180:30: error: You should depend on (emacs "29.1") if you need `treesit-node-type'.
181:14: error: You should depend on (emacs "29.1") if you need `treesit-node-prev-sibling'.
184:13: error: You should depend on (emacs "29.1") if you need `treesit-node-start'.
184:33: error: You should depend on (emacs "29.1") if you need `treesit-node-prev-sibling'.
192:22: error: You should depend on (emacs "29.1") if you need `treesit-node-type'.
198:14: error: You should depend on (emacs "29.1") if you need `treesit-node-prev-sibling'.
199:33: error: You should depend on (emacs "29.1") if you need `treesit-node-type'.
205:22: error: You should depend on (emacs "29.1") if you need `treesit-node-type'.
211:14: error: You should depend on (emacs "29.1") if you need `treesit-node-prev-sibling'.
212:33: error: You should depend on (emacs "29.1") if you need `treesit-node-type'.
224:22: error: You should depend on (emacs "29.1") if you need `treesit-node-start'.
224:42: error: You should depend on (emacs "29.1") if you need `treesit-node-prev-sibling'.
230:4: warning: Closing parens should not be wrapped onto new lines.
282:11: error: You should depend on (emacs "29.1") if you need `treesit-ready-p'.
284:3: error: You should depend on (emacs "29.1") if you need `treesit-parser-create'.
285:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
288:8: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
289:8: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
291:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
292:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
293:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
295:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
298:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
299:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
300:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
302:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
309:6: error: You should depend on (emacs "29.1") if you need `treesit-node-text'.
309:25: error: You should depend on (emacs "29.1") if you need `treesit-node-child'.
311:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
312:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
313:3: error: You should depend on (emacs "24.3") or the compat package if you need `setq-local'.
315:3: error: You should depend on (emacs "29.1") if you need `treesit-major-mode-setup'.
318:27: error: You should depend on (emacs "29.1") if you need `treesit-node-type'.
320:8: error: You should depend on (emacs "29.1") if you need `treesit-node-start'.
321:8: error: You should depend on (emacs "29.1") if you need `treesit-node-end'.
323:35: error: You should depend on (emacs "29.1") if you need `treesit-node-children'.
326:21: error: You should depend on (emacs "29.1") if you need `treesit-node-child'.
327:18: error: You should depend on (emacs "29.1") if you need `treesit-node-type'.
330:8: error: You should depend on (emacs "29.1") if you need `treesit-node-start'.
331:8: error: You should depend on (emacs "29.1") if you need `treesit-node-end'.
336:17: error: You should depend on (emacs "29.1") if you need `treesit-node-text'.
342:32: error: You should depend on (emacs "29.1") if you need `treesit-node-type'.
343:12: error: You should depend on (emacs "29.1") if you need `treesit-node-type'.
343:31: error: You should depend on (emacs "29.1") if you need `treesit-node-parent'.
351:0: error: "haskell_ts-imenu-data-type-p" doesn't start with package's prefix "haskell-ts".
355:3: error: You should depend on (emacs "29.1") if you need `treesit-node-text'.
355:22: error: You should depend on (emacs "29.1") if you need `treesit-node-child'.
357:0: error: "haskell-compile-region-and-go" doesn't start with package's prefix "haskell-ts".
363:0: error: "run-haskell" doesn't start with package's prefix "haskell-ts".
368:3: error: You should depend on (emacs "24.1") if you need `pop-to-buffer-same-window'.
370:0: error: "haskellsession" doesn't start with package's prefix "haskell-ts".
373:77: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
374:59: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
376:1: error: You should depend on (emacs "24.4") if you need `with-eval-after-load'.
376:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
380:7: error: You should depend on (emacs "29.1") if you need `treesit-ready-p'.
```

`haskell-ts-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- haskell-ts-mode.el#L196: This double negation can be collapsed (`not` aliases `null`)
- haskell-ts-mode.el#L209: This double negation can be collapsed (`not` aliases `null`)
- haskell-ts-mode.el#L373: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- haskell-ts-mode.el#L374: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
```

**Comment by ScamChamp** [comment]
@riscy , I fixed all of byte compile errors apart from 2 dumb ones to do with free eglot variables, which is made sure to by loaded before running. Also fixed most checkdoc ones, but some simple functions have really descriptive names, so I skipped on adding docstring.

**Comment by riscy** [comment]
Thanks - I don't see the eglot variable compile errors currently, for what it's worth.

> but some simple functions have really descriptive names, so I skipped on adding docstring.

This is fine - all within reason. :)

> I don't think the double negation can be collapsed,

This is minor, but (for example) `(while (and (not (null n)) (not (eq pos 0)))` can become `(and n (not (eq pos 0)))`.

Here's the latest -

`haskell-ts-mode.el` with byte-compile using Emacs 29.4:
```
haskell-ts-mode.el:43:11: Warning: defgroup for `haskell-ts-mode' fails to specify containing group
haskell-ts-mode.el:52:12: Warning: defcustom for `haskell-ts-use-indent' fails to specify type
haskell-ts-mode.el:56:12: Warning: defcustom for `haskell-ts-font-lock-level' fails to specify type
```

`haskell-ts-mode.el` with package-lint 20240507.1722:
```
2 issues found:
43:0: error: Customization groups should not end in "-mode" unless that name would conflict with their parent group.
43:0: error: Customization groups should specify a parent via `:group'.
```

**Comment by ScamChamp** [comment]
The package has been added to elpa

**Pull request closed without merging**
