### PR TITLE
Add grugru recipe.

### PR DESCRIPTION
**Pull request by ROCKTAKEY**
### Brief summary of what the package does

Rotate text at point.

### Direct link to the package repository

https://github.com/ROCKTAKEY/grugru

### Your association with the package

I'm author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

```
1 issue found:

330:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```
The `with-eval-after-load` section is so that `describe-function` can find functions defined by macro of this package.

### CODE REVIEW

**Comment by conao3** [comment]
Hi, @ROCKTAKEY!
Such a great and unique package!

One point, I recommend wrap the block with function or just `(require 'find-func)` at the toplevel to suit Elisp convention.
```emacs-lisp
(defun find-func-integration ()
  (require 'find-func)
  (defun grugru--function-advice (original symbol type library)
    "Advice for `find-function-search-for-symbol' from grugru."
    (let ((name (symbol-name symbol)))
      (or (funcall original symbol type library)
          (and (null type)
               (with-current-buffer (find-file-noselect library)
                 (when (re-search-forward
                        (format "\\|\\(^\\s-*(grugru-define-function\\s-*%s\\)"
                                (regexp-quote name))
                        nil t)
                   (cons (current-buffer) (match-beginning 0))))))))
  (advice-add 'find-function-search-for-symbol :around 'grugru--function-advice))
```

**Comment by terlar** [comment]
Is it worth to do comparison to:
- https://github.com/dp12/parrot
- https://github.com/nschum/rotate-text.el (not maintained for 11 years, but still)

**Comment by ROCKTAKEY** [comment]
@conao3 Thanks! This section is strongly inspired by [hydra](https://github.com/abo-abo/hydra/blob/8a9124f80b6919ad5288172b3e9f46c5332763ca/hydra.el#L323). As you say, I think these section should be wrapped or expanded, too. But some might think `(require 'find-func)` is annoying because this package does not actually require find-func, while wrapping function seem to be annoying for some one because this function is for just `describe-function`, not needed for work. So I wondering how it should be.

@terlar Thanks for telling me these packages. 
These two packages cannot define major-mode local rotation (parot even doesn't have buffer-local one). In addition, grugru can completely define what is picked at point, while rotate-text only can redefine definitions of word and symbol. And, grugru has a function that defines what texts are rotated, so user don't have to touch variable directly. Also, even though grugru can rotate multiple sets of texts by 1 command, grugru can define a new function which rotate specific sets of text.

**Comment by riscy** [comment]
Neat.  Quick first pass -- I'd double check the unused variable, and, on a very quick first glance, check whether there should be some minor mode toggling the advice on `find-function-search-for-symbol`?

### grugru-default.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200616.2257):
- No issues!


### grugru.el ###

byte-compile (using Emacs 26.3):
```
grugru.el:253:1:Warning: Unused lexical variable `now'
```

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200616.2257):
```
1 issue found:
502:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

Suggestions/experimental static checks:
- grugru.el#L180: It's safer to sharp-quote function names; use `#'`
- grugru.el#L514: It's safer to sharp-quote function names; use `#'`

### Loadability ###

Verifying ability to #'load each file:
```
Loading grugru-default.el
Loading grugru.el
Done.
```

**Comment by ROCKTAKEY** [comment]
@riscy Thanks! I decided to use minor-mode, and all errors were fixed.

**Comment by riscy** [comment]
Very cool.  Thanks!

**Comment by ROCKTAKEY** [comment]
Thanks!

**Pull request merged**
