### PR TITLE
Add docker-cli package

### PR DESCRIPTION
**Pull request by bosko**
### Brief summary of what the package does

Enables running commands in Docker container within Emacs buffer.

### Direct link to the package repository

https://github.com/bosko/docker-cli

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by Silex** [comment]
@bosko: are you ok if I get inspiration from this for https://github.com/Silex/docker.el/issues/7 ? I never took the time to find out what needed to be done for a proper `comint` shell, so I just used `async-shell-command` but how you do it looks easy.

**Comment by bosko** [comment]
@Silex of course not. As a matter of act I will be glad if you do so ;)

**Comment by bosko** [comment]
@riscy Thank you very much for this excellent review. Frankly speaking this is one of the best code reviews I've seen recently. I will try to fix all issues as soon as possible.

**Comment by mattiasb** [comment]
@bosko Just a small drive-by comment: Your README asks the user to install `inf-ruby` instead of `docker-cli` from melpa. :)

**Comment by bosko** [comment]
@riscy I think I've fixed all issues from your review.

I was not able to reproduce package-lint warning so I guessed problem was in lowercase 'running' so I've made it uppercase in the first line of the source file.

I removed mentioning of Rails console and keywords setting because both of them are not ready yet and I want to leave them for the next version.

**Comment by riscy** [comment]
Aw thanks for saying so.  One last thing I'm noticing is that you probably want to set the `require-match` argument on `completing-read` to t, for both the commands and the containers (which must exist).

**Comment by bosko** [comment]
@riscy `completing-read` is set to `t` and in addition I've added check if command or container are empty strings.

**Comment by riscy** [comment]
Looks great now.  Welcome to MELPA, and thank you!

**Pull request merged**
