### PR TITLE
Add redacted

### PR DESCRIPTION
**Pull request by bkaestner**
### Brief summary of what the package does

`redacted-mode` is an Emacs minor mode to hide your current text by changing your buffer's display table.

### Direct link to the package repository

https://github.com/bkaestner/redacted.el

### Your association with the package

I am the author and the maintainer.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org) ([melpazoid result](https://github.com/bkaestner/redacted.el/runs/4636019481?check_suite_focus=true))
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, this is neat!

I don't think this is a blocker but the name "secret-mode" makes me think of things like credentials and auth tokens.  Emacs for example comes packaged with secrets.el which is all about collections of credentials.  Something like `redact-mode` might be more precise.

But, you seem to already have an established userbase under the name secret-mode, so I don't consider the above a blocker.  Let me know what you think though, and I'm happy to merge.

(Along those same lines, your summary line "hide text in buffer" is a bit vague; I can think of other ways to hide text, including folding or background colors and so forth; maybe "Obscure text in buffer" would be clearer.)

**Comment by bkaestner** [comment]
> I don't think this is a blocker but the name "secret-mode" makes me think of things like credentials and auth tokens. Emacs for example comes packaged with secrets.el which is all about collections of credentials. Something like `redact-mode` might be more precise.

That's a good point, and you're not the [first one that suggested a new name](https://old.reddit.com/r/emacs/comments/pyg33z/secretmodeel_display_your_text_as_unicode_block/heupvvj/). To be honest, I completely forgot about renaming it to `redacted-mode`, even though I was rather excited by u/flyin1501 idea.

> (Along those same lines, your summary line "hide text in buffer" is a bit vague; I can think of other ways to hide text, including folding or background colors and so forth; maybe "Obscure text in buffer" would be clearer.)

Your feedback on the summary is also point on, and brings me to a potential other name. However, I'm fairly new to writing Emacs packages, so I'm not entirely sure which name would fit best.

Which one would you see more fitting? `redacted-mode`, `text-obscure-mode` or `obscure-mode`? I wouldn't want to pick a name that might have a (more promising?) other package waiting for it. English is not my first language, so I'm very much looking forward to hear your thoughts!

**Comment by riscy** [comment]
Hmm, it's completely up to you of course -- all of those names are more accurate I think.  You also have the option of simply calling the package `redacted` or `text-obscure` (and then of course `redacted-mode` and `text-obscure-mode` are within your namespace).  `redacted-mode` sounds good to me personally, and maybe it's a positive sign that someone else suggested it independently.

**Comment by bkaestner** [comment]
Just a quick update: I've renamed the upstream to `redacted.el` and the package to `redacted`. However, I'm still pondering whether to call the package `redacted` or `redact`, since commands like `redacted-region` might sound strange compared to `redact-region`.

I'll think about that till Wednesday and then update the PR. Thanks for your patience!

**Comment by riscy** [comment]
I also sometimes choose package names that result in nice M-x verbs -- take your time!

**Comment by bkaestner** [comment]
Happy holidays! 🎄

I finally had some time to think about it.  I've settled for `redacted`, even if the commands will look like `(redacted-region region-start region-end)` or `redacted-redact-region` (which I actually prefer).

Thanks again for your patience and your feedback!

**Comment by riscy** [comment]
Great!  Hitting merge now.  And, welcome to MELPA. :)

**Pull request merged**
