### PR TITLE
Recipe for clean-kill-ring

### PR DESCRIPTION
**Pull request by NicholasBHubbard**
### Brief summary of what the package does

Add custom filter predicates to keep the kill-ring clean

### Direct link to the package repository

https://github.com/NicholasBHubbard/clean-kill-ring.el

### Your association with the package

I am the author

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`clean-kill-ring.el` with byte-compile using Emacs 28.1:
```
clean-kill-ring.el:87:1: Warning: defcustom for `clean-kill-ring-mode' fails
    to specify containing group
clean-kill-ring.el:87:1: Warning: defcustom for `clean-kill-ring-mode' fails
    to specify containing group
In clean-kill-ring-mode:
clean-kill-ring.el:98:31: Warning: (lambda (&rest _args) \.\.\.) quoted with '
    rather than with #'
```

`clean-kill-ring.el` with checkdoc 0.6.2:
```
clean-kill-ring.el:33: First line is not a complete sentence
clean-kill-ring.el:45: First line is not a complete sentence
clean-kill-ring.el:64: First line is not a complete sentence
clean-kill-ring.el:85: First sentence should end with punctuation
clean-kill-ring.el:90: White space found at end of line
```

`clean-kill-ring.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- clean-kill-ring.el#L98: Quoting this lambda may prevent it from being compiled
- clean-kill-ring.el#L101: Quoting this lambda may prevent it from being compiled
- clean-kill-ring.el#L98: It's safer to sharp-quote function names; use `#'`
- clean-kill-ring.el#L101: It's safer to sharp-quote function names; use `#'`
```

Stderr output while compiling/loading:
```
clean-kill-ring.el: Warning: (lambda (&rest _args) \.\.\.) quoted with ' rather than with #'
clean-kill-ring.el: Warning: (lambda (&rest _args) \.\.\.) quoted with ' rather than with #'
```

Package and license:
- MIT License (via API)
- unknown license -- clean-kill-ring.el: Keep the kill ring clean
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to clean-kill-ring.el

**Comment by NicholasBHubbard** [comment]
Thanks for the feedback. I made a commit that should fix these issues.

**Comment by riscy** [comment]
Thanks -- looks handy!

**Comment by riscy** [comment]
And, welcome to MELPA. :)

**Pull request merged**
