### PR TITLE
Add radio recipe

### PR DESCRIPTION
**Pull request by olav35**
### Brief summary of what the package does

Radio is a radio player for Emacs. It plays internet radio channels by interfacing with vlc in the background.

### Direct link to the package repository

https://github.com/olav35/radio

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Looks good, and thanks for adhering to the checklist.  Here's a quick first pass.

### radio.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200616.2257):
- No issues!

Suggestions/experimental static checks:
- radio.el#L44: It's safer to sharp-quote function names; use `#'`
- radio.el#L48: Consider `unless ...` instead of `when (not ...)`
- radio.el#L21: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- radio.el#L30: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- radio.el#L31: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- radio.el#L32: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- radio.el#L33: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- radio.el#L34: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- radio.el#L35: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- radio.el#L36: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- radio.el#L37: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- radio.el#L48: You can use `not` or `null`

### Loadability ###

Verifying ability to #'load each file:
```
Loading radio.el
Done.
```

### Similarly named ###

- emms-player-mpv-jp-radios: https://melpa.org/#/emms-player-mpv-jp-radios
- org-radiobutton: https://melpa.org/#/org-radiobutton
- radio: https://github.com/emacsattic/radio
- Error: a package called 'radio' exists

The big issue is that the Emacsattic already has a `radio` package in it.  Are you feeling flexible about the package name?

**Comment by olav35** [comment]
I updated the package according to the suggestions. Renaming the package is not a problem. Provided I can think of a new name that is. As evident by the current one naming things is not my talent. If anyone has a name suggestion feel free to share it. Otherwise I will go with something boring like eradio or oradio.

**Comment by olav35** [comment]
I renamed the package to eradio.

**Comment by riscy** [comment]
Thanks for accommodating!  I've updated your recipe to reflect the name change, but also you'll have to rename your elisp file to "eradio.el" and update any summary lines, the footer (package-lint should warn you when you do), etc.

**Comment by olav35** [comment]
Done.

**Comment by riscy** [comment]
Could you also rename your recipe file to eradio?

**Comment by riscy** [comment]
Thanks for accommodating!  I'm able to take a closer look now.  I think this is just about ready to go, but I'd recommend you make `eradio-channels` a `defcustom` instead of a `defvar` to make it a little easier to customize.

I'd also strongly recommend you mention VLC somewhere on your summary line and/or in your `;;; Commentary` -- this will make it more discoverable and people will know what the package does.

Lastly, on your `start-process` line, you'll probably want to use `shell-quote-argument` (and you may need to `(require 'subr)` for that) on the URL (which should possibly be lower-cased to match typical elisp style, but I wouldn't block on that).  E.g.:

```elisp
(defun eradio-play-low-level (url)
  "Play radio channel URL in a new process."
  (let ((url (shell-quote-argument url)))
    (setq eradio-process (start-process "eradio-process" nil "vlc" "--no-video" "-I" "rc" url))))
```
This is good practice in general, but is especially the case with URLs which frequently have ampersands in them that could interfere with the shell, e.g. a URL like <kbd>https://music.fm:1234?channel=x&playlist=emacs.pls</kbd> (as a maybe contrived example)

**Comment by olav35** [comment]
I made most of the changes you suggested. Unfortunately escaping the url with `shell-quote-argument` did not work at all. I tested it and it refused to play any urls. I don't think start-process uses a shell so that might be why `shell-quote-argument` is redundant.

**Comment by riscy** [comment]
You're completely right about `shell-quote-argument`.  Sorry about the noise (my advice would have made sense if you were running `shell-command` instead of `start-process`).

**Comment by olav35** [comment]
Great! Thank you for merging it.

**Pull request merged**
