### PR TITLE
Reconstruct jk-org2md-hexo to org2md : )

### PR DESCRIPTION
**Pull request by loveminimal**
### Brief summary of what the package does

A package render `.org` to `.md` which could be rendered by HEXO. 

### Direct link to the package repository

https://github.com/loveminimal/org2md

### Your association with the package

I'm Jack LIU, the maintainer : )

### Relevant communications with the upstream package maintainer

`org2md` based on `ox-gfm`, and more powerful.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
1.  What is HEXO?
2.  How does this differ from org-export's built-in Markdown export, and from Pandoc's Org->Markdown conversion, and why would a user use this package instead of those?
3.  If there are any things that this package does better than those, could those improvements be made in those other packages instead of creating yet another Org->Markdown exporter?

**Comment by loveminimal** [comment]
> 1. What is HEXO?
> 2. How does this differ from org-export's built-in Markdown export, and from Pandoc's Org->Markdown conversion, and why would a user use this package instead of those?
> 3. If there are any things that this package does better than those, could those improvements be made in those other packages instead of creating yet another Org->Markdown exporter?

I will think about it. Hah :）
- HEXO is a static blog generator. and org-export's built-in Markdown export always cannot be rendered by many Markdown Engines. 
- `ox-gfm`  is okay, but it also cannot be directly rendered by HEXO which need a speical Front-mattar
- Acturally, this package offers two simple functions and solve the problem of images show.

And you opinion is okay. Thanks : )

**Comment by alphapapa** [comment]
1.  If the package is specific to HEXO, it ought to have HEXO in its name, e.g. `ox-md-hexo` or something like that.
2.  If possible, you should probably implement it with `org-export-define-derived-backend`.
3.  What is this code trying to do?

```el
	  (let ((file-title (concat "---\ntitle: "
				  (car filename-list) " "
				  (car (cdr filename-list)) " "
				  (car (cdr (cdr filename-list))) " "
				  (car (cdr (cdr (cdr filename-list)))) " "
				  (car (cdr (cdr (cdr (cdr filename-list))))) " "
				  (car (cdr (cdr (cdr (cdr (cdr filename-list)))))) " "
				  (car (cdr (cdr (cdr (cdr (cdr (cdr filename-list))))))) " "
				  (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr filename-list)))))))) "\n")))
```

**Comment by loveminimal** [comment]
> 1. If the package is specific to HEXO, it ought to have HEXO in its name, e.g. `ox-md-hexo` or something like that.
> 2. If possible, you should probably implement it with `org-export-define-derived-backend`.
> 3. What is this code trying to do?
> 
> ```emacs-lisp
> 	  (let ((file-title (concat "---\ntitle: "
> 				  (car filename-list) " "
> 				  (car (cdr filename-list)) " "
> 				  (car (cdr (cdr filename-list))) " "
> 				  (car (cdr (cdr (cdr filename-list)))) " "
> 				  (car (cdr (cdr (cdr (cdr filename-list))))) " "
> 				  (car (cdr (cdr (cdr (cdr (cdr filename-list)))))) " "
> 				  (car (cdr (cdr (cdr (cdr (cdr (cdr filename-list))))))) " "
> 				  (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr filename-list)))))))) "\n")))
> ```

First, thanks for you help :+1: 

To me, it is main for HEXO. In fact, it is suitable for all other Markdown engines :100:  ：）

Second, this package, I think, is need being enhanced later. If I make sure it is exactly very stable, maybe I can pull a request to `org-export-define-derived-backend`.

Finally, the block above is used to add a format strings to the generated markdown file, like this:

```
---
title: how to be yourself
---
````
Thus, hexo can render it : )

**Comment by purcell** [comment]
Thanks! Some notes:

- Since this package is hexo-specific, I feel like the package name should be org2hexo or similar.
- Don't use the buffer name when [what you want is the filename](https://github.com/loveminimal/org2md/blob/08fd3d10838e14e76610aafd7c352a8d8b4a04b0/org2md.el#L43): use `buffer-file-name`.
- Don't use `string-split` to manipulate filename extensions. There are built-in functions like `file-name-sans-extension`.
- Don't use `write-region` and `append-to-file` when you could instead simply use `with-temp-b uffer`, copy the current buffer's content into that temp buffer, do any necessary manipulation, then finally write it to the destination file.
- `switch-window-then-maximize` is a strange thing for this command to do, as is `kill-buffer`.
- [This code is bogus](https://github.com/loveminimal/org2md/blob/08fd3d10838e14e76610aafd7c352a8d8b4a04b0/org2md.el#L49-L56). What you probably want to use is `(mapconcat 'identity " " filename-list)`, or simply replace `"-"` with `" "` in the filename.
- Don't introduce variables with `nil` values unnecessarily, e.g. [here](https://github.com/loveminimal/org2md/blob/08fd3d10838e14e76610aafd7c352a8d8b4a04b0/org2md.el#L60-L61). You can write all of that code with only `let`, and no `setq`! :-)

Hope that helps!

**Comment by loveminimal** [comment]
> Thanks! Some notes:
> 
> * Since this package is hexo-specific, I feel like the package name should be org2hexo or similar.
> * Don't use the buffer name when [what you want is the filename](https://github.com/loveminimal/org2md/blob/08fd3d10838e14e76610aafd7c352a8d8b4a04b0/org2md.el#L43): use `buffer-file-name`.
> * Don't use `string-split` to manipulate filename extensions. There are built-in functions like `file-name-sans-extension`.
> * Don't use `write-region` and `append-to-file` when you could instead simply use `with-temp-b uffer`, copy the current buffer's content into that temp buffer, do any necessary manipulation, then finally write it to the destination file.
> * `switch-window-then-maximize` is a strange thing for this command to do, as is `kill-buffer`.
> * [This code is bogus](https://github.com/loveminimal/org2md/blob/08fd3d10838e14e76610aafd7c352a8d8b4a04b0/org2md.el#L49-L56). What you probably want to use is `(mapconcat 'identity " " filename-list)`, or simply replace `"-"` with `" "` in the filename.
> * Don't introduce variables with `nil` values unnecessarily, e.g. [here](https://github.com/loveminimal/org2md/blob/08fd3d10838e14e76610aafd7c352a8d8b4a04b0/org2md.el#L60-L61). You can write all of that code with only `let`, and no `setq`! :-)
> 
> Hope that helps!

Okay, thanks, Sir. I will check and fix it. :)

**Comment by riscy** [comment]
Hey @loveminimal, have you given any thought to renaming the package?  Or this comment:
> switch-window-then-maximize is a strange thing for this command to do, as is kill-buffer.

At the very least I'm noticing `switch-window-then-maximize` is part of the `switch-window` package that you will possibly need to add a dependency on.  Also, a quick pass through the checklist.  package-lint is giving me:
```
1:54: warning: You should depend on (emacs "24") if you need lexical-binding.
6:1: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```
Byte-compiling is giving me:
```
In end of data:
org2md.el:80:1:Warning: the following functions are not known to be defined:
    org-gfm-export-as-markdown, switch-window-then-maximize
```

**Comment by loveminimal** [comment]
> Hey @loveminimal, have you given any thought to renaming the package? Or this comment:
> 
> > switch-window-then-maximize is a strange thing for this command to do, as is kill-buffer.
> 
> At the very least I'm noticing `switch-window-then-maximize` is part of the `switch-window` package that you will possibly need to add a dependency on. Also, a quick pass through the checklist. package-lint is giving me:
> 
> ```
> 1:54: warning: You should depend on (emacs "24") if you need lexical-binding.
> 6:1: warning: You should include standard keywords: see the variable `finder-known-keywords'.
> ```
> 
> Byte-compiling is giving me:
> 
> ```
> In end of data:
> org2md.el:80:1:Warning: the following functions are not known to be defined:
>     org-gfm-export-as-markdown, switch-window-then-maximize
> ```

Hey, riscy. I'm sorry for that. I had to adjust my job last days, and I will deal with those errors as soon as possible.  Hah . Thanks.

**Pull request closed without merging**
