### PR TITLE
Add projectile-git-autofetch

### PR DESCRIPTION
**Pull request by lunaryorn**
### Brief summary of what the package does

Automatically fetch git repositories known to projectile.

### Direct link to the package repository

https://github.com/andrmuel/projectile-git-autofetch

### Your association with the package

Just an enthusiastic user

### Relevant communications with the upstream package maintainer

I already did a [cleanup](https://github.com/andrmuel/projectile-git-autofetch/pull/1), and the maintainer @andrmuel [agreed with me submitting this package](https://github.com/andrmuel/projectile-git-autofetch/issues/2#issuecomment-259238382).

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR about autoload cookie. https://github.com/andrmuel/projectile-git-autofetch/pull/3

**Comment by lunaryorn** [comment]
@syohex Thanks!

**Comment by andrmuel** [comment]
Thank you! Just merged that pull request.

**Comment by syohex** [comment]
Merged

**Comment by lunaryorn** [comment]
@syohex @andrmuel Thanks a lot, folks! 👍

**Pull request merged**
