### PR TITLE
Add recipe for firebase-rules-mode

### PR DESCRIPTION
**Pull request by dherbst**
### Brief summary of what the package does

firebase-rules-mode.el provides syntax highlighting for Firebase rules files.

### Direct link to the package repository

https://github.com/dherbst/firebase-rules-mode

### Your association with the package

Package maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  

One very minor issue is that your `;;; Commentary` should be wrapped at around 80 characters to improve how it gets presented downstream, e.g. in the MELPA index.

But this is also a good opportunity to expand that Commentary to mention whether you plan to do anything about automatic indentation.  This [language](https://firebase.google.com/docs/rules/rules-language) has nesting and function definitions, and (eventually) warrants significantly more than just syntax highlighting.  Letting users know whether this is on the roadmap could be helpful.

**Comment by dherbst** [comment]
Thanks @riscy, I reformatted the `Commentary` for 80 characters, and added a note about automatic indention.  Please let me know if this is in line with what you expect.

**Comment by riscy** [comment]
That look great - thank you!

**Comment by riscy** [comment]
And, welcome to MELPA. :)

**Pull request merged**
