### PR TITLE
Add recipe for tesouro.el

### PR DESCRIPTION
**Pull request by rberaldo**
### Brief summary of what the package does

Implements a thesaurus for Brazilian Portuguese by querying https://dicio.com.br/ for synonyms of the word under point.

### Direct link to the package repository

https://github.com/rberaldo/tesouro.el/

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  The checklist look great.

My only (purely technical) concern here is that, for the moment, MELPA is an English-language index of packages, and this package's summary line is in Portuguese.  When people use the (admittedly simple) search, they expect to use English keywords.  And if we were to make the search more sophisticated (synonyms, hyponyms, etc.) this task is much simplified with there being only one language to handle.  But let me know your thoughts on that.

**Comment by rberaldo** [comment]
Thanks, @riscy! It did not dawn on me that the summary line is what MELPA indexes for searching packages (this is my first time contributing). I agree with your rationale; as a user, I myself would search for such a package using English. I've just pushed a commit that translates the summary line into English.

**Comment by riscy** [comment]
Thank you for accommodating!  Very minor but the summary line went too long:

`tesouro.el` with package-lint 20220913.1226:
```
1 issue found:
1:0: warning: The package summary is too long. It should be at most 60 characters.
```

I think this is fixed by rephrasing, e.g. as `Brazilian Portuguese synonym search using dicio.com.br`.

**Comment by riscy** [comment]
Thank you!  Just a (non-blocking) comment on `;;; Commentary:` style, typically triple semicolons are for headers, and the paragraphs only start with two semicolons, e.g. you want:

```elisp
;;; Commentary:

;; Queries dicio.com.br for synonyms of a word using @ThiagoNelsi’s
;; dicio-api (https://github.com/ThiagoNelsi/dicio-api)

;; Heavily based on @AnselmC’s le-thesaurus.el
;; (https://github.com/AnselmC/le-thesaurus.el/)
```

**Pull request merged**
