### PR TITLE
dslide

### PR DESCRIPTION
**Pull request by psionic-k**
### Brief summary of what the package does

Domain Specific sLIDEs, a more configurable, extensible re-write of org-tree-slide, taking an approach appropriate for integrating with other all of the other buffers of Emacs.   It integrates org babel blocks into the same forward-backward interface.  Try it by calling `dslides-deck-start` on test/demo.org for a preview.

It's in heavy development, but the releases I cut should run the demo well.

### Direct link to the package repository

https://github.com/positron-solutions/dslide

### Your association with the package

Author.  I forked from org-tree-slide but ended up completely re-writing about 95% using the org element API and EIEIO.

### Relevant communications with the upstream package maintainer

**None Needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`dslide.el` with byte-compile using Emacs 29.3:
```
dslide.el:2464:12: Warning: value returned from (1+ (org-element-property :begin element)) is unused
dslide.el:2464:12: Warning: value returned from (1+ (#[514 \211;\203\300\301#\207\302A@"\207 [get-text-property 0 plist-get] 6 (/usr/share/emacs/29.3/lisp/org/org-element.elc . 14297)] :begin element)) is unused
In end of data:
dslide.el:1531:10: Warning: the function `hide-mode-line-mode' is not known to be defined.
```
Note you are using the `when-let` macro which depends on subr.el.

`dslide.el` with checkdoc 0.6.2 (fix *within reason*):
```
dslide.el:2688: The footer should be: (provide 'dslide)\n;;; dslide.el ends here
dslide.el:484: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:497: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:528: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:540: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:557: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:574: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:612: All variables and subroutines might as well have a documentation string
dslide.el:615: All variables and subroutines might as well have a documentation string
dslide.el:619: All variables and subroutines might as well have a documentation string
dslide.el:621: All variables and subroutines might as well have a documentation string
dslide.el:623: All variables and subroutines might as well have a documentation string
dslide.el:626: All variables and subroutines might as well have a documentation string
dslide.el:644: First line is not a complete sentence
dslide.el:687: First line is not a complete sentence
dslide.el:693: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:706: All variables and subroutines might as well have a documentation string
dslide.el:709: All variables and subroutines might as well have a documentation string
dslide.el:724: All variables and subroutines might as well have a documentation string
dslide.el:775: All variables and subroutines might as well have a documentation string
dslide.el:833: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:855: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:910: First line is not a complete sentence
dslide.el:915: All variables and subroutines might as well have a documentation string
dslide.el:923: All variables and subroutines might as well have a documentation string
dslide.el:935: You should convert this comment to documentation
dslide.el:949: All variables and subroutines might as well have a documentation string
dslide.el:962: All variables and subroutines might as well have a documentation string
dslide.el:995: Argument `parent' should appear (as PARENT) in the doc string
dslide.el:1130: All variables and subroutines might as well have a documentation string
dslide.el:1135: All variables and subroutines might as well have a documentation string
dslide.el:1140: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:1174: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:1181: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:1196: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:1209: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:1222: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:1232: All variables and subroutines might as well have a documentation string
dslide.el:1260: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:1298: All variables and subroutines might as well have a documentation string
dslide.el:1300: You should convert this comment to documentation
dslide.el:1304: All variables and subroutines might as well have a documentation string
dslide.el:1307: All variables and subroutines might as well have a documentation string
dslide.el:1316: All variables and subroutines might as well have a documentation string
dslide.el:1322: All variables and subroutines might as well have a documentation string
dslide.el:1327: You should convert this comment to documentation
dslide.el:1346: All variables and subroutines might as well have a documentation string
dslide.el:1383: All variables and subroutines might as well have a documentation string
dslide.el:1393: Argument `method-names' should appear (as METHOD-NAMES) in the doc string
dslide.el:1405: All variables and subroutines might as well have a documentation string
dslide.el:1445: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:1456: All variables and subroutines might as well have a documentation string
dslide.el:1463: All variables and subroutines might as well have a documentation string
dslide.el:1470: All variables and subroutines might as well have a documentation string
dslide.el:1474: You should convert this comment to documentation
dslide.el:1481: All variables and subroutines might as well have a documentation string
dslide.el:1510: All variables and subroutines might as well have a documentation string
dslide.el:1520: All variables and subroutines might as well have a documentation string
dslide.el:1543: All variables and subroutines might as well have a documentation string
dslide.el:1571: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:1590: Argument `obj' should appear (as OBJ) in the doc string
dslide.el:1618: You should convert this comment to documentation
dslide.el:1636: You should convert this comment to documentation
dslide.el:1654: All variables and subroutines might as well have a documentation string
dslide.el:1660: All variables and subroutines might as well have a documentation string
dslide.el:1680: All variables and subroutines might as well have a documentation string
dslide.el:1703: All variables and subroutines might as well have a documentation string
dslide.el:1723: All variables and subroutines might as well have a documentation string
dslide.el:1742: All variables and subroutines might as well have a documentation string
dslide.el:1833: Argument `fun' should appear (as FUN) in the doc string
dslide.el:1846: Argument `fun' should appear (as FUN) in the doc string
dslide.el:1860: Argument `type' should appear (as TYPE) in the doc string
dslide.el:1868: Argument `heading' should appear (as HEADING) in the doc string
dslide.el:1879: Argument `heading' should appear (as HEADING) in the doc string
dslide.el:1896: Argument `heading' should appear (as HEADING) in the doc string
dslide.el:1904: Argument `heading' should appear (as HEADING) in the doc string
dslide.el:1956: All variables and subroutines might as well have a documentation string
dslide.el:1976: Argument `heading' should appear (as HEADING) in the doc string
dslide.el:1986: Argument `element' should appear (as ELEMENT) in the doc string
dslide.el:2002: First sentence should end with punctuation
dslide.el:2018: Argument `point' should appear (as POINT) in the doc string
dslide.el:2128: All variables and subroutines might as well have a documentation string
dslide.el:2131: All variables and subroutines might as well have a documentation string
dslide.el:2137: All variables and subroutines might as well have a documentation string
dslide.el:2216: All variables and subroutines might as well have a documentation string
dslide.el:2311: All variables and subroutines might as well have a documentation string
dslide.el:2321: All variables and subroutines might as well have a documentation string
dslide.el:2346: Argument `key' should appear (as KEY) in the doc string
dslide.el:2386: All variables and subroutines might as well have a documentation string
dslide.el:2396: All variables and subroutines might as well have a documentation string
dslide.el:2399: You should convert this comment to documentation
dslide.el:2431: Argument `signal' should appear (as SIGNAL) in the doc string
dslide.el:2455: All variables and subroutines might as well have a documentation string
dslide.el:2506: All variables and subroutines might as well have a documentation string
dslide.el:706: Error messages should *not* end with a period
```

`dslide.el` with package-lint 20240507.1722:
```
1 issue found:
1:0: error: package.el cannot parse this buffer: Search failed: ";;; dslide.el ends here"
```
See the corresponding issue re: the footer from checkdoc above.

`dslide.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- dslide.el#L1946: Could this `point`/`point-max` comparison use `eobp`?
- dslide.el#L1929: Could this `point`/`point-min` comparison use `bobp`?
- dslide.el#L966: Use `when ...` instead of `unless (null ...)`
- dslide.el#L2097: Consider using %F instead of %Y-%m-%d in time strings
```

**Comment by psionic-k** [comment]
Lol, well I hadn't pushed my checkdoc cleanups.  Sorry for that.

There is still a large number of missing docstring warnings, but it's the EIEIO methods for which I have documentation on the generic method.

**Comment by psionic-k** [comment]
> ```
> dslide.el:2464:12: Warning: value returned from (1+ (org-element-property :begin element)) is unused
> dslide.el:2464:12: Warning: value returned from (1+ (#[514 \211;\203��\300\301��#\207\302A@�"\207 [get-text-property 0 plist-get] 6 (/usr/share/emacs/29.3/lisp/org/org-element.elc . 14297)] :begin element)) is unused
>```

On inspection, the values are in use, though I did remove one `+1` call in https://github.com/positron-solutions/dslide/commit/c131653996cbe9732a1f2471bfd749f0cac84434

>```
> In end of data:
> dslide.el:1531:10: Warning: the function `hide-mode-line-mode' is not known to be defined.
> ```

I have soft-required `hide-mode-line-mode` in https://github.com/positron-solutions/dslide/commit/d33205f26080b145327ce4197e0bb6a948e6a3f2

> Note you are using the `when-let` macro which depends on subr.el.

Since subr doesn't provide a feature, I don't know how I would express a requirement.  Please advise.

> ```
> - dslide.el#L1946: Could this `point`/`point-max` comparison use `eobp`?
> - dslide.el#L1929: Could this `point`/`point-min` comparison use `bobp`?
>```

Adopted in 7028c07acee0d1c0bfcbd86830e33d75b550dd20

>```
> - dslide.el#L966: Use `when ...` instead of `unless (null ...)`
>```

The surrounding expressions must compare one `nil` and one `t` value.  I think it's easier to read with consistent use of `unless` here.

>```
> - dslide.el#L2097: Consider using %F instead of %Y-%m-%d in time strings
> ```

Just on the basis that I have to look up `%F` and this isn't a package using such formats frequently, I will pass on this change.

**Comment by psionic-k** [comment]
Thanks for the thorough checking by the way :+1:

I'm getting too accustomed to just expecting it.

**Comment by progfolio** [comment]
> Since subr doesn't provide a feature, I don't know how I would express a requirement. Please advise.

I think you're good here without any modifications.

```
emacs -q --batch --eval '(print (fboundp `when-let))' 
;; Should print t on Emacs 29
```

> The surrounding expressions must compare one nil and one t value. I think it's easier to read with consistent use of unless here.

For what it's worth, I read the code prior to seeing these notes and was going to suggest `when` over the `unless (null...` as well. Double negation is generally harder to parse.

A couple design notes:

- It would be nice if there were a way to resume a presentation and/or start from an arbitrary point.
  My first intuition was that dslide-deck-start would start from wherever point was in the Org file. It might be nice to arrange for that by default and something like passing a prefix arg to start from the beginning or a particular slide.

- The part of your demo which depends on your other package should gracefully error.
  You have the power of elisp at your hands there, it would be a testament to the flexibility of the program if you could detect when the user doesn't have the package installed and end the presentation there or offer instructions on how to install it.


Very cool project overall.
I know org-tree-slide seemed like it needed a facelift last I checked and most other presentation packages rely on external JS libraries.
Your package looks much more polished in comparison.

**Comment by psionic-k** [comment]
Among other things, I enabled the default option for `dslide-start-from` to `point`.  (currently limited to root headings)

The babel action will now highlight a failed block in the base buffer and will also ask the user if they want to visit it.

There is a new command `dslide-deck-develop` that starts the presentation with the base buffer visible.  The babel action highlights executed blocks.  The success / fail faces are configurable.

I'm considering adding support to retry / skip / abort the babel blocks.  Haven't decided how I want to fit this to the 3-button interface (overloading `dslide-deck-start` with its "secondary action" that is planned).  What I'm considering is how to save a presenter who will be obviously sweating if their normally succeeding block suddenly fails at a critical moment :cold_sweat:.

Just released 0.4.0, getting rid of the worst of the trickiness in the action code.  A lot of the action coordination was no better than a tech demo in terms of maturity.

The animation is much prettier due to a subtle math fix :cat2: 

Before telling everyone I've achieved a 1.0 release, I have 95% decided to combine the "slide action" and "child action" into several distinct slide classes instead.  The resulting configuration markup will feel a lot better for users because they will just set a slide class and perhaps add some extra actions, but will rarely need to set two properties in two places to accomplish one change.  This will incidentally remove the `unless` code mentioned earlier.

**Comment by psionic-k** [comment]
I just completed a 0.5.0 release that I think makes the last major configuration API change.  You can see the demo.org for evidence of improved configuration API.  Code-wise, the new combined slide-child actions are much more local and easier to reason about.  The questionable logic code was incidentally removed.  A lot of redundant expressions have been condensed.

The stuff I'm working on moving forward feature-wise:
* inline animation and composed child action
* alternative action overloading to enable a video playing or other temporary interface (also my idea for babel block failure recovery)
* built-in hiding of drawers and keywords

**Comment by riscy** [comment]
Thanks both - and @psionic-k this really is a cool package, and well-documented. :)

I apologize for my `when-let` mistake above, I didn't carefully read the byte-compiler messages and thought it resembled the errors that occur when a macro definition hasn't been brought in.  (I also didn't realize that subr.el doesn't `provide` anything!)

Here's the latest I'm seeing (I'll omit the checkdoc which is largely the same):

`dslide.el` with byte-compile using Emacs 29.3:
```
dslide.el:2328:36: Warning: value returned from (1+ start) is unused
dslide.el:2328:36: Warning: value returned from (1+ start) is unused
In dslide-display-develop:
dslide.el:2638:14: Warning: value returned from (get-buffer-window slide-buffer) is unused
In end of data:
dslide.el:1440:12: Warning: the function `hide-mode-line-mode' is not known to be defined.
```

The third warning re: `(get-buffer-window slide-buffer)` is legitimate - the `unless` form is closed too early by the looks of things:
```elisp
    (unless (get-buffer-window slide-buffer))
     (display-buffer slide-buffer 'display-buffer-same-window))
```

> On inspection, the values are in use [re: the `1+ start` nags]

You are right - I looked at the macroexpand of `(setf (overlay-start overlay) (1+ start))` and it gives:
```elisp
    (let* ((v overlay))
      (progn
        (move-overlay v (1+ start) (overlay-end v))
        (1+ start)))
```
so the byte-compiler is complaining about the return value of the macro being unused.  All MELPA packages are encouraged to get to a clean byte-compile, so what I suggest here is using `move-overlay` directly in this case.

**Comment by psionic-k** [comment]
Malformed `unless`
https://github.com/positron-solutions/dslide/commit/145b06df68b3d584c491e76a300aead662c8271e

Macro expansion
https://github.com/positron-solutions/dslide/commit/baedd89de4b38fa25645e0761f94c9ee7c9a2d7d

Thanks, didn't even know about `move-overlay`.

I really need to overhaul my workflows.  I've been meaning to see about using Elpaca's (hi progfolio) various package testing macros to overcome several problems that became more of an issue, especially with a lot of EIEIO and dead methods hanging around.

**Comment by progfolio** [comment]
> I really need to overhaul my workflows. I've been meaning to see about using Elpaca's (hi progfolio) various package testing macros to overcome several problems that became more of an issue, especially with a lot of EIEIO and dead methods hanging around.

I typically have a keybinding set up to launch a fresh Emacs instance and test in that. `elpaca-test` is also good if you want to entirely bypass your own config and/or automate tests. When going that route I recommend using `:ref local` in the test declaration, which will avoid hitting the network for downloading recipe menus/Elpaca.

**Comment by psionic-k** [comment]
AFAIK no blockers here.

**Comment by riscy** [comment]
Thank you @psionic-k - I think my only last suggestion (not a blocker) would be to replace your `(defun init-emacs-lisp-mode-setup () (message "Nyan!"))` stub in wiz-shortdoc.el with something that tells the user more than "Nyan" :)

**Comment by riscy** [comment]
(Apologies for any noise I sent out - I just delete a previous reply which was about another package.)

Regarding the last warning --

`dslide.el` with byte-compile using Emacs 29.3:
```
dslide.el:1445:12: Warning: the function `hide-mode-line-mode' is not known to be defined.
```



The byte-compiler recognizes this and will not warn about the function not being defined if you write it this way:
```elisp
(when (fboundp 'hide-mode-line-mode)
          (hide-mode-line-mode 1))
```

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by psionic-k** [comment]
Sorry for slow reply.  I began fixing some things and needed to stabilize.

https://github.com/positron-solutions/dslide/releases/tag/v0.5.2

**Comment by psionic-k** [comment]
I managed to introduce another compile warning that only showed up after restart.  Also incorporating some changes from feedback from GNU's mailing list.

**Comment by psionic-k** [comment]
Okay, looks clean on my end.  I have also applied some feedback from emacs-devel.

**Comment by riscy** [comment]
Thanks - here's the latest I'm seeing --

`dslide.el` with byte-compile using Emacs 29.3:
```
dslide.el:1591:19: Warning: Unused lexical argument `w'
dslide.el:1591:40: Warning: reference to free variable `wb'
```
Should that `w` be `wb?

**Comment by psionic-k** [comment]
Ouch yeah, I somehow slipped a command in between building it to make a video and committing.  Fixed.

**Comment by riscy** [comment]
Thank you!  Merging this.

**Comment by psionic-k** [comment]
Hey thanks for running the show!

**Pull request merged**
