### PR TITLE
Add elisp-repo-kit

### PR DESCRIPTION
**Pull request by psionic-k**
Signed-off-by: Psionik K <73710933+psionic-k@users.noreply.github.com>

### Brief summary of what the package does

Emacs repo kit clones a repo and replaces strings, providing a very quick way from within Emacs to set up a repository that has lints and tests set up for Github Actions

### Direct link to the package repository

https://github.com/positron-solutions/elisp-repo-kit/

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for your patience!  Quick first pass --

`elisp-repo-kit.el` with byte-compile using Emacs 28.1:
```
elisp-repo-kit.el:40:1: Error: Cannot open load file: No such file or directory, dash
```
Most likely this needs a `Package-Requires` on dash, but since you only appear to be using that package in one place, you may be able to avoid the dependency.

`elisp-repo-kit.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- elisp-repo-kit.el#L121: It's safer to sharp-quote function names; use `#'`
- elisp-repo-kit.el#L102: `concat` may be unneeded; `insert` can take multiple arguments
```

**Comment by riscy** [comment]
Thanks!  I'll take a closer look at the melpazoid issue when time permits.

I like the idea for this package, but I feel like I'm running into issues when trying it out.  For example if I run `elisp-repo-kit-new`, I get prompted:
```
Directory ‘<my emacs dir>/Emacs.app/Contents/MacOS/package_name/author/package_name/author/’ does not exist; create? (y or n)
```
which seems incorrect.

This seems to rely on GitHub, but not every package needs to be on GitHub; I think this constraint should be reflected in the package name, or the summary line, or at least the commentary

I also notice `elisp-repo-kit-great-job` doesn't seem to be used anywhere, but correct me if I'm wrong.


I'd recommend also taking a look at (and possibly integrating) some related packages:
- https://melpa.org/#/spdx -- inserting SPDX license identifiers in package files
- https://melpa.org/#/license-templates -- similar, uses the GitHub API
- https://melpa.org/#/lice -- similar
- https://melpa.org/#/epkg -- could you use this to check whether the package has a unique name?

**Comment by psionic-k** [comment]
I'll aim for having this polished **in about two weeks** and actually using it as the foundation of my other packages.

> This seems to rely on GitHub, but not every package needs to be on GitHub; I think this constraint should be reflected in the package name, or the summary line, or at least the commentary

I'll update this.  Because of the Actions support provided, it's 100% tied to Github.

> I also notice elisp-repo-kit-great-job doesn't seem to be used anywhere, but correct me if I'm wrong.

I want to change this to a commented minimal example.

There's an inherent tradeoff design of the package / repo.  The more behavior I add, the more the output is not a minimal repo without adding more stuff to strip out stuff I added.  If I use too many templates or external files, it's more indirection / maintenance.

> I'd recommend also taking a look at (and possibly integrating) some related packages:

Will do.  I had been avoiding dependencies, but I don't think it's an issue if I go in the direction of commented examples and using comments to strip out things that aren't relevant after cloning.

Part of my goal is to set up with elisp IDE behavior ready to go.  To me this means test discovery and runners for lints & tests. Some of the linters seemed focused on batch workflows instead of interactive calls.  I've been looking and packages like elmake and others.  I think the cask requirement of elmake feels out of place if dependencies for sandbox testing are provided via Nix anyway.  I'm sorting these issues out among available options.

**Comment by psionic-k** [comment]
I think I will just hit the melpa json endpoint to check package names.

I think I can integrate spdx usefully.  Going to keep a GPL3+ default so that the DCO + GPL3 accounting still provides a decent path for future code into FSF code bases.

**Comment by alphapapa** [comment]
> Part of my goal is to set up with elisp IDE behavior ready to go. To me this means test discovery and runners for lints & tests. Some of the linters seemed focused on batch workflows instead of interactive calls. I've been looking and packages like elmake and others.

FWIW, I just added an Elisp library to `makem` containing a Transient menu to make running it from within Emacs very easy: https://github.com/alphapapa/makem.sh#transient-menu-makemel

**Comment by riscy** [comment]
> I'll aim for having this polished in about two weeks and actually using it as the foundation of my other packages.

Thanks!  In that case, is it safe to say I can wait for you to ping me for another look when you're ready?

**Comment by psionic-k** [comment]
I finished up a round of work on the upstream:

- and added a few commands such as project aware feature reloading for package and tests
- simplified the elisp used in CI
- better support for renaming consistency from potential forks

However, I also changed my prefix to `erk` without changing the features over to `erk` and files to `erk.el` etc.  Package lint complains.  I'm not wedded to any idea, but as far as being clear for discovery and concise for usage, I'm fine with the scheme I've arrived at.

**Comment by riscy** [comment]
>  Package lint complains.

I think the rename is fine, but we should make sure the package name aligns too - it's really the only easy way to fend off naming collisions.  That said, here's the latest --

`elisp-repo-kit.el` with byte-compile using Emacs 28.1:
```
elisp-repo-kit.el:268:11: Warning: the function `string-join' might not be
    defined at runtime.
elisp-repo-kit.el:134:27: Warning: the function `string-remove-suffix' might
    not be defined at runtime.
```
For these you probably want `(eval-when-compile (require 'subr-x))`

`elisp-repo-kit.el` with package-lint 20221003.1636:
```
28 issues found:
8:95: error: Package ert is not installable.
57:0: error: "erk-github-package-name" doesn't start with package's prefix "elisp-repo-kit".
64:0: error: "erk-package-prefix" doesn't start with package's prefix "elisp-repo-kit".
69:0: error: "erk-github-userorg" doesn't start with package's prefix "elisp-repo-kit".
76:0: error: "erk--gpl3-notice" doesn't start with package's prefix "elisp-repo-kit".
90:0: error: "erk--rename-maps" doesn't start with package's prefix "elisp-repo-kit".
96:0: error: "erk--files-with-strings" doesn't start with package's prefix "elisp-repo-kit".
102:0: error: "erk--project-root" doesn't start with package's prefix "elisp-repo-kit".
107:18: error: You should depend on (emacs "27.1") if you need `with-suppressed-warnings'.
110:20: error: You should depend on (emacs "28.1") if you need `project-root'.
113:0: error: "erk--reload" doesn't start with package's prefix "elisp-repo-kit".
127:0: error: "erk--dir-features" doesn't start with package's prefix "elisp-repo-kit".
137:0: error: "erk--package-features" doesn't start with package's prefix "elisp-repo-kit".
143:0: error: "erk--test-features" doesn't start with package's prefix "elisp-repo-kit".
150:0: error: "erk-reload-project-package" doesn't start with package's prefix "elisp-repo-kit".
166:0: error: "erk-reload-project-tests" doesn't start with package's prefix "elisp-repo-kit".
182:0: error: "erk-ert-rerun-this-no-reload" doesn't start with package's prefix "elisp-repo-kit".
195:0: error: "erk-ert-rerun-this" doesn't start with package's prefix "elisp-repo-kit".
207:0: error: "erk-ert-project-results-buffer" doesn't start with package's prefix "elisp-repo-kit".
210:0: error: "erk-ert-project-selector" doesn't start with package's prefix "elisp-repo-kit".
229:0: error: "erk-ert-project" doesn't start with package's prefix "elisp-repo-kit".
236:0: error: "erk--rename-package" doesn't start with package's prefix "elisp-repo-kit".
253:0: error: "erk--replace-strings" doesn't start with package's prefix "elisp-repo-kit".
306:0: error: "erk-clone" doesn't start with package's prefix "elisp-repo-kit".
337:0: error: "erk-rename-relicense" doesn't start with package's prefix "elisp-repo-kit".
366:0: error: "erk-new" doesn't start with package's prefix "elisp-repo-kit".
392:29: error: You should depend on (emacs "28.1") if you need `string-chop-newline'.
398:29: error: You should depend on (emacs "28.1") if you need `string-chop-newline'.
```
I think `ert` is builtin and tied to Emacs versions, so can be removed from the package-requires.

`elisp-repo-kit.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- elisp-repo-kit.el#L109: It's safer to sharp-quote function names; use `#'`
- elisp-repo-kit.el#L110: It's safer to sharp-quote function names; use `#'`
```

**Comment by psionic-k** [comment]
Believe I got all nits cleaned up.  Commits to satisfy package-lint etc at the end of the log in master.

Mainly was working to improve the structure based on experience adding CI to a few more repos.  Been using the package reload and project test commands a lot.

**Comment by riscy** [comment]
Looks great now.  I think this is close to ready to merge but I have some feedback about `shell-command` --

i.e. if possible, I recommend using `call-process` (you can avoid having to run `cd %s` by using `git clone`'s optional [directory] argument).  I make this recommendation because if someone inadvertently puts shell control characters or spaces in e.g. erk-github-userorg then *arbitrary* things can happen.  Alternatively, check out `shell-quote-argument` to quote the arguments and prevent this.

Ultra minor:
- Github is branded as "GitHub", I figure we may as well use the capitalization the entity itself uses
- avaialble -> availabe, reaload -> reload (based on a quick flyspell)

**Comment by psionic-k** [comment]
I made the recommended updates and then added some more to clean up some behaviors.

In interactive testing, the package can create a new package, which after loading is then capable of reloading itself.  After clone & rename, all changes are properly reflected in staged / unstaged changes.

**Comment by riscy** [comment]
Looks good.  Thanks, and welcome to MELPA. :)

**Pull request merged**
