### PR TITLE
Add recipe for Uniline

### PR DESCRIPTION
**Pull request by tbanel**
### Brief summary of what the package does

The UNICODE standard contains characters to draw lines and boxes. The package makes it easy to leverage those characters.

See https://github.com/tbanel/uniline/blob/main/README.org for examples of drawings done by Uniline.

### Direct link to the package repository

https://github.com/tbanel/uniline

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings.
**Beware**: there remain a few non-fixable issues, due to a convention of Hydra about docstrings starting with an empty line.
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Have you had a chance to compare to https://melpa.org/#/unicode-enbox ?  There is also https://melpa.org/#/boxes but it looks like that one's focused on ASCII boxes.  I don't have experience with any of these packages, including yours, but maybe there's a way to merge efforts.  Let me know!

In the meantime, quick first pass -

`uniline.el` with checkdoc 0.6.2 (fix *within reason*):
```
uniline.el:1786: Documentation strings should not start or end with whitespace
uniline.el:1786: First sentence should end with punctuation
uniline.el:1836: Documentation strings should not start or end with whitespace
uniline.el:1836: First sentence should end with punctuation
```

`uniline.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- uniline.el#L1904: There is no need to quote lambdas (neither #' nor ')
- uniline.el#L881: Avoid `with-no-warnings` if the root cause can be addressed
- uniline.el#L895: Avoid `with-no-warnings` if the root cause can be addressed
```
In fact, I think the `with-no-warnings` are unnecessary?  Note that form is to suppress *byte-compile* warnings, not runtime warnings.

**Comment by tbanel** [comment]
Hi Chris riscy!

### unicode-enbox

Yes. I looked at all packages on MELPA and Gnu ELPA that have some relationship with mine (searching keywords like _"unicode", "drawing", "sketch", "diagram"_ and so on). I mentioned lots of them in the `README.org`. For some reason, I did not mentioned `unicode-enbox`. I'll do it. Thanks for reminding me.

Building `uniline` on `unicode-enbox`? Well… This will save the code for `uniline-draw-inner-rectangle` (20 lines of Lisp). And then I will have to deal with lines crossing each other, like for example:
```
     ╭─────────╮
     │         │
     │    ┏━━━━┿━━┓
     ╰────╂────╯  ┃
          ┗━━━━━━━┛
```
And of course, `uniline-draw-inner-rectangle` would have to insert the result of `unicode-enbox` (which is a string) into the current buffer.

`uniline` is essentially interactive on an infinite buffer. `unicode-enbox` is essentially a sub-routine aimed at creating a string. It seems to me those two packages do not overlap, except both manipulate the same UNICODΕ block named _"box drawing"_.

### boxes

About `boxes`, yes! I mentioned it in my `README.org`. And yes, it does ASCII art (not UNICODE). It draws nice looking boxes with unicorns, flowers, parchments. Clearly `boxes` & `uniline` cover different purposes.

### Docstrings & checkdoc

I know about the _"fix within reason"_ warnings of `checkdoc`. Those are documentation strings for `hydra`. And `hydra` requires a first empty line to enable substitutions.

See for instance:
https://github.com/abo-abo/hydra/blob/master/hydra.el, line 1276:

`"When DOCSTRING starts with a newline, special Ruby-style substitution will be performed by hydra--format."`

So I cannot _"fix [those warnings] within reason"_.

### Melpazoid

I recently discovered `melpazoid`, and installed it as a _"GitHub Action"_ on my repo. Quite well done! It warned about the `#'lambda` issue. I will fix that.

About the `with-no-warnings` warning, I did it on purpose. I build a constant circular list (an elegant way to simplify algorithms using it) which triggers the warning.

I used `with-no-warnings` to avoid user installing the package seeing a nasty warning. But you may be right: the warning is not displayed in any trace log. I will remove `with-no-warnings` and see what happens.

### until next time

Thanks riscy, for your time and comments!
Have fun
Thierry

**Comment by riscy** [comment]
Thanks!  That's fair, and I think this is an easy merge.

Before doing so, I just wanted to double-check the recipe with you.  This would also work, which would allow your recipe to grow to include other .el files -
```elisp
(uniline :fetcher github :repo "tbanel/uniline" :files (:defaults (:exclude "bench*.el")))
```
Or, you could use the default recipe and move the bench.el files into another directory.

There's a preference for the default recipe when possible, but I'll leave this up to you.

**Comment by tbanel** [comment]
OK, let's go for the default recipe. I guess it implies removing the `:files` tag, leaving just:
```elisp
(uniline :fetcher github :repo "tbanel/uniline")
```

Should I submit a new pull-request?

I moved `bench*.el` files out of the way, in a new `tests/` sub-directory of the git-repo. They are still part of the project, acting as non-regression tests. But they are not intended to be distributed in the MELPA package.

I saved the sophisticated recipe you suggested for later on, when `uniline` will turn into a million lines project (2000 lines today) 🙂.

Thanks riscy!
Have fun

**Comment by riscy** [comment]
> Should I submit a new pull-request?

No need - we can just update here.

**Comment by riscy** [comment]
Let me know when you're ready for another look!

**Comment by tbanel** [comment]
ready!

**Pull request merged**
