### PR TITLE
Add recipe for dtache

### PR DESCRIPTION
**Pull request by niklaseklund**
### Brief summary of what the package does

The dtache package allows users to run shell commands detached from Emacs. These commands are launched in sessions, using the program dtach. The package enables a seamless integration where commands are run using decoupled dtach processes, which dtache makes sure behind the scenes, that Emacs can attach to.

### Direct link to the package repository

https://gitlab.com/niklaseklund/dtache

### Your association with the package

I am the package maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, this is a cool package.  A couple quick suggestions on a quick first pass --

`dtache-eshell.el` with [melpazoid](https://github.com/riscy/melpazoid):
- dtache-eshell.el#L127: Lighter should start with a space

`dtache.el` with [melpazoid](https://github.com/riscy/melpazoid):
- dtache.el#L694: It's safer to sharp-quote function names; use `#'`
- dtache.el#L701: It's safer to sharp-quote function names; use `#'`
- dtache.el#L984: Could this point/point-min comparison use `bobp`?
- dtache.el#L1202: Lighter should start with a space

**Comment by niklaseklund** [comment]
Thanks feedback @riscy :). I have uploaded a new commit addressing the issues from melpazoid. You can find the commit here: https://gitlab.com/niklaseklund/dtache/-/commit/aca73c1e6038cb73afc43d8237b11dda657231ac

**Comment by niklaseklund** [comment]
So the package just got merged into ELPA. Just wanted to let you know in case it causes any issue? I was thinking that it could be available in both archives.

**Comment by riscy** [comment]
That won't cause any issues except perhaps some minor confusion from users; we usually discourage it unless there's a compelling reason, like you want to use MELPA to support a more rapid release cycle.

**Comment by niklaseklund** [comment]
My motivation for having it in both is as you say more rapid feedback from users due to possibility to use MELPA releases.  So I would still like to have it available in both then :)

**Comment by riscy** [comment]
Sounds good!  Here's the latest (I think some things have changed) --

`dtache.el` with checkdoc 0.6.2:
```
dtache.el:290: Disambiguate compilation-minor-mode by preceding w/ function,command,variable,option or symbol.
dtache.el:1204: Disambiguate dtache-shell-mode by preceding w/ function,command,variable,option or symbol.
```
I find these are hard to rephrase to satisfy checkdoc -- feel free to ignore these.

And at dtache.el#L629 I see you're now setting a global key binding.  It's better to just tell users how to do this in your `;;; Commentary` so they can make it an unsurprising part of their config.  Alternatively -- and what I might recommend instead -- is you can create a global minor mode with its own keymap that will be in effect when the mode's enabled.

**Comment by niklaseklund** [comment]
@riscy yeah I have no idea how to rephrase those either so I'll skip them for now :)

Its a valid point. A global minor mode could be something, I will give that some thought. I have uploaded a patch where I instead remove the global binding and at the same time makes sure that the other dtache modes that do exist properly binds the key instead. I don't know if a global minor mode is favorable over this solution but I think the new solution at least removes the problem of a global binding.

 Its addressed in this patch https://gitlab.com/niklaseklund/dtache/-/commit/cdeb7dcf3ba3780c470e9649fcd77afb885195bd

**Comment by riscy** [comment]
I like your solution!   This looks good to merge.  And, welcome to MELPA. :)

**Pull request merged**
