### PR TITLE
Recipe for regswap package.

### PR DESCRIPTION
**Pull request by skitov**
### Brief summary of what the package does

`regswap.el` swaps two regions of text within a buffer.

### Direct link to the package repository

https://github.com/skitov/regswap

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass; these are minor and should be easy fixes -

- The `;;; Commentary` for this file is much wider than 80 characters
- You are writing functions signatures in a C-style, e.g. `defun regswap-rgn()` but the elisp community style is `defun regswap-rgn ()` (with a space before the arglist)
- Regarding the instructions `These keybindings can be set by placing (regswap-setup-default-keybindings)`, my recommendation would be to tell users explicitly to place e.g. `(global-set-key (kbd "C-x w w") 'regswap-mark-region)`  (and so forth) in their init - that way they can see clearly how to customize the keybindings if they don't want to use the defaults.

Minor sharpquote stuff -
- regswap.el#L150: It's safer to sharp-quote function names; use `#'`
- regswap.el#L108: It's safer to sharp-quote function names; use `#'`
- regswap.el#L83: It's safer to sharp-quote function names; use `#'`

**Comment by riscy** [comment]
Also, this repository lacks a LICENSE file and should have one added - See: https://github.com/licensee/licensee

**Comment by skitov** [comment]
> Thanks for this. Quick first pass; these are minor and should be easy fixes -
> 
> * The `;;; Commentary` for this file is much wider than 80 characters
> * You are writing functions signatures in a C-style, e.g. `defun regswap-rgn()` but the elisp community style is `defun regswap-rgn ()` (with a space before the arglist)
> * Regarding the instructions `These keybindings can be set by placing (regswap-setup-default-keybindings)`, my recommendation would be to tell users explicitly to place e.g. `(global-set-key (kbd "C-x w w") 'regswap-mark-region)`  (and so forth) in their init - that way they can see clearly how to customize the keybindings if they don't want to use the defaults.
> 
> Minor sharpquote stuff -
> 
> * regswap.el#L150: It's safer to sharp-quote function names; use `#'`
> * regswap.el#L108: It's safer to sharp-quote function names; use `#'`
> * regswap.el#L83: It's safer to sharp-quote function names; use `#'`

Thanks for feedback, I've made requested changes.

**Comment by riscy** [comment]
Thank you for accommodating.  Merging this now -- and welcome to MELPA. :)

**Pull request merged**
