### PR TITLE
Add mame recipe.

### PR DESCRIPTION
**Pull request by Iacob**
### Brief summary of what the package does

mame.el is a MAME front-end

### Direct link to the package repository

https://github.com/Iacob/elmame

### Your association with the package

I'm the original author.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks again.  As a note for myself, this follows from https://github.com/melpa/melpa/pull/8508

`mame-config.el` with package-lint 20230315.1052:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```
(Minor, fyi)

`mame-config.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- mame-config.el#L52: This line (and possibly others) indents with mixed tabs/spaces; see `indent-tabs-mode`
```

`mame-machine-info-loader.el` with checkdoc 0.6.2:
```
mame-machine-info-loader.el:29: All variables and subroutines might as well have a documentation string
```
You are *so* close to a 100% checkdoc, I'd recommend just getting this one done.  But not a blocker. :)

`mame-machine-info-loader.el` with package-lint 20230315.1052:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```

`mame.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- mame.el#L45: This line (and possibly others) indents with mixed tabs/spaces; see `indent-tabs-mode`
```

There are no blockers here, however.  Merging!

**Comment by tarsius** [comment]
In `documents/archive/elmame-config.el`, you still require `elmame`.

**Comment by Iacob** [comment]
Hello @tarsius,

That file is an archived source file, no reference are pointed to it. Now all unnecessary files and tools are removed from the project source tree. They will be placed in another project.

**Comment by tarsius** [comment]
Thanks for removing these files!

For the Emacsmirror, I extract all provided and required features, by parsing all libraries (i.e., files that end with `*.el` and contain `(provide ...)`). I do this to detect broken dependencies. Sometimes there are false positives as in this case. If you want to hide certain directories from the tools used by the Emacsmirror, but also from some other tools that deal with libraries, you can add a file named `.nosearch` to the subdirectory.

**Comment by Iacob** [comment]
Hello @tarsius,

Thank you for the reminder, I will follow that naming rule.

**Pull request merged**
