### PR TITLE
Add recipe for filenotify-recursive

### PR DESCRIPTION
**Pull request by jethrokuan**
### Brief summary of what the package does

This package is like the in-built `filenotify`, but watches directories recursively. Whenever directories are created or destroyed, watchers are spawned and stopped appropriately.

This package was created to be used within `org-roam`: the database can then be kept up-to-date, tracking changes to the filesystem not directly caused by Emacs.

### Direct link to the package repository

https://github.com/jethrokuan/filenotify-recursive

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
This seems like it would be generally useful.  Could it be upstreamed into Emacs?

**Comment by jethrokuan** [comment]
> This seems like it would be generally useful. Could it be upstreamed into Emacs?

Sure, I can look into how that it is done, but I'd also like this to also be available to users pre-Emacs 28 and available soonish.

**Comment by riscy** [comment]
Thanks for this -- quick first pass:

package-lint (using version 20210528.2348):
```
19 issues found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
7:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
38:0: error: "fnr-descriptors" doesn't start with package's prefix "filenotify-recursive".
44:0: error: "fnr--uuid" doesn't start with package's prefix "filenotify-recursive".
66:0: error: "fnr--subdirectories-recursively" doesn't start with package's prefix "filenotify-recursive".
105:26: error: You should depend on (emacs "27.1") if you need `ignore-error'.
131:0: error: "fnr--add-watchers" doesn't start with package's prefix "filenotify-recursive".
138:0: error: "fnr--rm-watchers" doesn't start with package's prefix "filenotify-recursive".
142:0: error: "fnr--update-descs" doesn't start with package's prefix "filenotify-recursive".
148:0: error: "fnr-add-watch" doesn't start with package's prefix "filenotify-recursive".
194:0: error: "fnr-rm-watch" doesn't start with package's prefix "filenotify-recursive".
202:0: error: "fnr--wrap-callback" doesn't start with package's prefix "filenotify-recursive".
209:0: error: "fnr--update-directory-watchers" doesn't start with package's prefix "filenotify-recursive".
220:0: error: "fnr--update-created-directory" doesn't start with package's prefix "filenotify-recursive".
229:0: error: "fnr--update-stopped-directory" doesn't start with package's prefix "filenotify-recursive".
238:0: error: "fnr--update-renamed-directory" doesn't start with package's prefix "filenotify-recursive".
243:0: error: "fnr--directory-watched-p" doesn't start with package's prefix "filenotify-recursive".
248:0: error: "fnr--directory-actionable-p" doesn't start with package's prefix "filenotify-recursive".
257:0: error: "fnr-clear-all" doesn't start with package's prefix "filenotify-recursive".
```

- filenotify-recursive.el#L100: You can use `not` or `null`
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to ping.

**Comment by riscy** [comment]
After a quick search I noticed there was some activity to get this upstreamed into Emacs, and it's been over a year since our last exchange here.  I'll close this PR for now, but if you want it reopened don't hesitate to let me know, and I'll reopen it immediately.

**Comment by jinnovation** [comment]
For posterity, here is at least one relevant emacs-devel thread on this topic: https://lists.gnu.org/archive/html/emacs-devel/2021-08/msg00876.html

**Pull request closed without merging**
