### PR TITLE
adding buffer-manage recipe

### PR DESCRIPTION
**Pull request by plandes**
### Brief summary of what the package does

Provides support to multiple managed buffers (i.e. inferior shells, SQL sessions, etc.).

### Direct link to the package repository

https://github.com/plandes/buffer-manage

### Your association with the package

Original author and maintainer.

### Relevant communications with the upstream package maintainer

None.

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
[NOTE] Please use topic branch instead of master branch for pull request. There is unrelated commit.

**Comment by plandes** [comment]
Sorry about that.  What is the "topic branch"?

**Comment by plandes** [comment]
Oh, you mean I should create a new branch on my fork, add the commit to that branch and create a pull request based on that fork correct?

**Comment by purcell** [comment]
Yep.

**Comment by plandes** [comment]
From syohex's comments I presume you guys will take it from here.  However, if you want me to resubmit using the separate topic branch I'm more than happy to do that.

**Comment by syohex** [comment]
See #4489

**Pull request closed without merging**
