### PR TITLE
Update recipe for ibrowse

### PR DESCRIPTION
**Pull request by nicolas-graves**
### Brief summary of what the package does

ibrowse stands for interactive browse, its goal is to be able to control your browser through common actions, be it on browser tabs, history or bookmarks using Emacs.

It relies on the completing-read built-in interface, and thus benefits greatly from integration with consult, marginalia and vertico.

### Direct link to the package repository

https://git.sr.ht/~ngraves/ibrowse.el

### Your association with the package

Author and maintainer. 

### Relevant communications with the upstream package maintainer

Since the first inclusion in MELPA, I have reworked on the proper independence of functionality, which makes the package able to be split in different components, hence the recipe update. 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by tarsius** [comment]
A single recipe file can only contain a single recipe form (the one for the package matching the name of the file), so you need to create three new files.

**Comment by riscy** [comment]
I've also recently updated CONTRIBUTING.el, moments ago --

https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#what-to-know-before-opening-a-pull-request

please consider the latest text under the "one recipe per pull request" section.

**Comment by nicolas-graves** [comment]
Thanks, I must have misread. I'll do that.

**Comment by nicolas-graves** [comment]
I also have a question. Here I basically have one file that is common to all packages (ibrowse-core.el), one file that is common to ibrowse-history.el and ibrowse-bookmarks.el (namely ibrowse-sql.el). My choice in this recipe was to include them as :files in all 3 subpackages, but wouldn't this lead to some code repetition (e.g. ibrowse-core.el being present multiple times) ? Or should I instead use :requires and define subpackages (but which do not provide interesting functionality alone) ibrowse-core and ibrowse-sql ?

**Comment by riscy** [comment]
You shouldn't include ibrowse-sql.el in all three packages.  (In fact you won't be able to because you'll unavoidably have namespace violations).  You'd also create an issue where users who ran the form `(require 'ibrowse-sql)` wouldn't know which copy of the file was being loaded, wouldn't be able to tell if it was the correct version for the functionality they were using, etc.

If the functionality is trivial library code that your packages share, that you can't see anyone else ever using as a dependency, then it's not a big deal to copy the functions themselves into the other packages, with correct namespacing.

Another alternative would be to just combine all of your files into one larger "ibrowse-plus" package.

**Pull request closed without merging**
