### PR TITLE
Added recipe for calc-prog

### PR DESCRIPTION
**Pull request by Jesse-Millwood**
### Brief summary of what the package does

This package adds some units to the calc program that cover common IEC binary units like Byte, KiB, MiB, GiB. It also adds a couple calc stack based utility functions for bit shifting.

### Direct link to the package repository

https://github.com/Jesse-Millwood/calc-prog

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I think there is a cycle during macroexpansion, which is preventing some of the checklist checks from being able to be run --

`calc-prog.el` with byte-compile using Emacs 28.1:
```
calc-prog.el:59:1: Error: Recursive load: "/workspace/pkg/calc-prog.el", "/workspace/pkg/calc-prog.el", "/workspace/pkg/calc-prog.el", "/workspace/pkg/calc-prog.el", "/workspace/pkg/calc-prog.el", "/workspace/pkg/melpazoid.el"
```

`calc-prog.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- calc-prog.el#L49: Top-level `setq` should be replaced by `defvar`
- calc-prog.el#L57: Top-level `setq` should be replaced by `defvar`
```

`#'load`-check on each file:
```
Loading calc-prog.el
  calc-prog.el:Error: Emacs 28.1 couldn't load:
  (error "Recursive load" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/melpazoid.el")
```

Stderr output while compiling/loading:
```
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "calc-prog.el") => (macroexpand-all (defmath prog-shift-left-by …)) => (macroexpand (defmath …)) => (load "calc-prog.el")
Eager macro-expansion failure: (error "Recursive load" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/melpazoid.el")
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "calc-prog.el") => (macroexpand-all (defmath prog-shift-left-by …)) => (macroexpand (defmath …)) => (load "calc-prog.el")
Eager macro-expansion failure: (error "Recursive load" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/melpazoid.el")
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "calc-prog.el") => (macroexpand-all (defmath prog-shift-left-by …)) => (macroexpand (defmath …)) => (load "calc-prog.el")
Eager macro-expansion failure: (error "Recursive load" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/melpazoid.el")
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "calc-prog.el") => (macroexpand-all (defmath prog-shift-left-by …)) => (macroexpand (defmath …)) => (load "calc-prog.el")
Eager macro-expansion failure: (error "Recursive load" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/melpazoid.el")
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "calc-prog.el") => (macroexpand-all (defmath prog-shift-left-by …)) => (macroexpand (defmath …)) => (load "calc-prog.el")
Eager macro-expansion failure: (error "Recursive load" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/melpazoid.el")
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "calc-prog.el") => (macroexpand-all (defmath prog-shift-left-by …)) => (macroexpand (defmath …)) => (load "calc-prog.el")
Eager macro-expansion failure: (error "Recursive load" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/melpazoid.el")
Eager macro-expansion failure: (error "Recursive load" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/melpazoid.el")
Eager macro-expansion failure: (error "Recursive load" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/calc-prog.el" "/workspace/pkg/melpazoid.el")
```

**Comment by Jesse-Millwood** [comment]
Hey @riscy would you happen to know where to look for how a package is loaded from something like melpa? 

I have tried to manually byte compile and use `load-file` and I don't get any recursive load issues and I've tried `eval-buffer` and still don't get the recursive load issues. However, when I run `C-c C-c` in my melpa package, I get the recursive load issue. I'd just like to locally create this manually to investigate deeper.

**Comment by riscy** [comment]
It looks like the recursive load is due to a naming collision -- the macroexpansion runs `(require 'calc-prog`) (which is an Emacs builtin!) but it is also the name of your package, hence the loop.  Likely this package needs to be renamed.

With regard to the two top-level `setq`s you should think about how this might interact with another package that wants to define `math-additional-units`.  I think it is probably more appropriate to use `add-to-list` here.  Running `(setq math-units-table nil)` on its own at load time seems like it could lead to bad interactions with other packages, however.

**Comment by Jesse-Millwood** [comment]
> which is an Emacs builtin!

Oh wow, that's embarrassing. Thanks for catching that! This was driving me mad!

> Likely this package needs to be renamed.

Agreed, I'll rename it. 

> With regard to the two top-level setqs you should think about how this might interact with another package that wants to define math-additional-units. I think it is probably more appropriate to use add-to-list here. Running (setq math-units-table nil) on its own at load time seems like it could lead to bad interactions with other packages, however.

I agree it isn't ideal. But in the `C-h v` for `math-additional-units` it says: 

```
Additional units table for user-defined units.
Must be formatted like ‘math-standard-units’.
If you change this, be sure to set ‘math-units-table’ to nil to ensure
that the combined units table will be rebuilt.
```

I don't see many examples on line regarding changing this that don't use setq directly on the `math-additional-units` and the `math-units-table`. I wonder if I should do as you say and add to the list and maybe conditionally set `math-units-table` to `nil`?

**Comment by riscy** [comment]
> Thanks for catching that! This was driving me mad!

No problem. :) That's the first time I ran into that issue too.

> I don't see many examples on line regarding changing this that don't use setq directly on the math-additional-units and the math-units-table. I wonder if I should do as you say and add to the list and maybe conditionally set math-units-table to nil?

Just imagine there were another package that did the same thing as yours, and imagine a user had both packages installed.  Then put yourself in the shoes of a user trying to debug that situation.  I haven't looked too deeply into it but I think `add-to-list` is definitely the right way to go about this.

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out. :)

**Comment by Jesse-Millwood** [comment]
> I'll mark this awaiting upstream for now, but feel free to reach out. :)

Thanks! Sorry for the delay, a few life things got in the way and I hadn't touched my personal computer in a while. I just made some updates and append to the list of units now.

**Comment by riscy** [comment]
Here's the latest (very quick, superficial pass) --

`calc-prog-utils.el` with byte-compile using Emacs 28.1:
```
calc-prog-utils.el:48:7: Warning: assignment to free variable
    `prog-math-additional-units'
calc-prog-utils.el:56:37: Warning: reference to free variable
    `math-additional-units'
calc-prog-utils.el:56:59: Warning: reference to free variable
    `prog-math-additional-units'
calc-prog-utils.el:56:59: Warning: assignment to free variable
    `math-additional-units'
In calc-prog-shift-left-by:
calc-prog-utils.el:59:1: Warning: docstring wider than 80 characters
In calcFunc-prog-shift-left-by:
calc-prog-utils.el:61:4: Warning: docstring wider than 80 characters
In calc-prog-shift-right-by:
calc-prog-utils.el:65:1: Warning: docstring wider than 80 characters
In calcFunc-prog-shift-right-by:
calc-prog-utils.el:67:4: Warning: docstring wider than 80 characters
In calc-prog-mask:
calc-prog-utils.el:71:1: Warning: docstring wider than 80 characters
In calcFunc-prog-mask:
calc-prog-utils.el:73:4: Warning: docstring wider than 80 characters
```


`#'load`-check on each file:
```
Loading calc-prog-utils.el
  calc-prog-utils.el:Error: Emacs 28.1:
  (void-variable math-additional-units)
```

Re: math-additional-units, you should `require` whatever file it's defined in and use `add-to-list` instead of `setq`.

Also note the code has a stray `(message "hello")` line in it, which I assume was for debugging. :)

Also, your `;;; Code:` line seems to start before some of your `;;; Commentary` is complete, but correct me if I'm wrong -- the coment lines immediately under the `;;; Code` look useful as commentary.

**Comment by Jesse-Millwood** [comment]
I fixed the docstrings and used `defvar` to define my list of units and then `mapc` to use `add-to-list` to add to the additional units variable. I used `checkdoc` again and byte compiled it to make sure there were no errors on that front. 
I used `C-c C-c` in the recipe to try it out and it seems to behave as expected.

**Comment by riscy** [comment]
Thank you for accommodating, and also thanks for your patience.

Now that the checklist is behind us, I'm taking a closer look at the code.  And by the way: This looks handy and the additional units seem like something that stock Emacs should include!  If you're feeling ambitious you may want to see if you can get some of this merged into Emacs itself.

- Just to be safe, you should also `(require 'calc)` for `defmath`, rather than relying on it being transitively imported by `calc-units`
- This is a little nitpicky, but when I look at `math-standard-units`, the exponentiations in the "short descriptions" of the units omit spaces and extraneous parentheses; e.g. `"3.0856775854*10^16 m"` for a parsec.  I think it would look more seamless if you followed the same style and wrote `"1024^5 * Byte"` instead of `"(1024 ^ 5) * Byte"` (or even just used B instead of Byte, since B is as far as I'm aware the standard abbreviation)
- This is also nitpicky, but prefixing each unit's "long description" with `IEC` is probably extraneous; there's no other context in which the word "kibibyte" would appear

Lastly, I was wrong about this and I apologize if it wasted any time:

> Running (setq math-units-table nil) on its own at load time seems like it could lead to bad interactions with other packages, however.

which was due to my own lack of understanding about the `math-additional-units` conventions.  I think you can make this clear in the code by documenting it, e.g. something like:
```elisp
(mapc (lambda (unit) (add-to-list 'math-additional-units unit))
      '((PiB "(1024 ^ 5) * Byte" "IEC Pebibyte")
        (TiB "(1024 ^ 4) * Byte" "IEC Tebibyte")
        (GiB "(1024 ^ 3) * Byte" "IEC Gibibbyte")
        (MiB "(1024 ^ 2) * Byte" "IEC Mebibyte")
        (KiB "1024 * Byte" "IEC Kibibyte 1024 bytes")
        (Byte "8 * bit" "A byte is the usual grouping of bits to be used in computational storage")
        (bit nil "The most basic computational storage unit")))
;; after changing `math-additional-units', `math-units-table' must be
;; set to nil to ensure that the combined units table will be rebuilt:
(setq math-units-table nil)
```

**Comment by Jesse-Millwood** [comment]
> Thank you for accommodating, and also thanks for your patience.
> 
> Now that the checklist is behind us, I'm taking a closer look at the code. And by the way: This looks handy and the additional units seem like something that stock Emacs should include! If you're feeling ambitious you may want to see if you can get some of this merged into Emacs itself.

Thanks for taking the time to make sure the packages in melpa are quality! I appreciate the second set of eyes. Yeah I might try and submit it upstream, I already have signed the fsf papers. But I have another package that I want to submit after this and the units will help. 

> 
>     * Just to be safe, you should also `(require 'calc)` for `defmath`, rather than relying on it being transitively imported by `calc-units`
> 

Good call, I'll add that.

>     * This is a little nitpicky, but when I look at `math-standard-units`, the exponentiations in the "short descriptions" of the units omit spaces and extraneous parentheses; e.g. `"3.0856775854*10^16 m"` for a parsec.  I think it would look more seamless if you followed the same style and wrote `"1024^5 * Byte"` instead of `"(1024 ^ 5) * Byte"` (or even just used B instead of Byte, since B is as far as I'm aware the standard abbreviation)
> 

Oh yeah I like that. I'll make that change.

>     * This is also nitpicky, but prefixing each unit's "long description" with `IEC` is probably extraneous; there's no other context in which the word "kibibyte" would appear
> 
I like that, I'll make the change.
> 
> Lastly, I was wrong about this and I apologize if it wasted any time:
> 
> > Running (setq math-units-table nil) on its own at load time seems like it could lead to bad interactions with other packages, however.
> 
> which was due to my own lack of understanding about the `math-additional-units` conventions. I think you can make this clear in the code by documenting it, e.g. something like:
> 
> ```emacs-lisp
> (mapc (lambda (unit) (add-to-list 'math-additional-units unit))
>       '((PiB "(1024 ^ 5) * Byte" "IEC Pebibyte")
>         (TiB "(1024 ^ 4) * Byte" "IEC Tebibyte")
>         (GiB "(1024 ^ 3) * Byte" "IEC Gibibbyte")
>         (MiB "(1024 ^ 2) * Byte" "IEC Mebibyte")
>         (KiB "1024 * Byte" "IEC Kibibyte 1024 bytes")
>         (Byte "8 * bit" "A byte is the usual grouping of bits to be used in computational storage")
>         (bit nil "The most basic computational storage unit")))
> ;; after changing `math-additional-units', `math-units-table' must be
> ;; set to nil to ensure that the combined units table will be rebuilt:
> (setq math-units-table nil)
> ```

Great, that whole interaction with the `math-units-table` was confusing to me. I'll add that.

I made those changes and pushed.

**Comment by riscy** [comment]
Thanks!  Merging now.  And, welcome to MELPA. :)

**Pull request merged**
