### PR TITLE
Added recipe for company-ipa.

### PR DESCRIPTION
**Pull request by mguzmann**
### Brief summary of what the package does

This package adds a backend for to company for inserting IPA symbols based on phonological descriptions.

### Direct link to the package repository

https://gitlab.com/mguzmann89/company-ipa/

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x ] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x ] My elisp byte-compiles cleanly
- [x ] `M-x checkdoc` is happy with my docstrings
- [x ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
### company-ipa.el ###

byte-compile with Emacs 27.1:
```
company-ipa.el:200:7:Warning: assignment to free variable
    `company-ipa--latex-prefix-regexp'
company-ipa.el:204:7:Warning: assignment to free variable
    `company-ipa--unicode-prefix-regexp'
In company-ipa-symbols-unicode:
company-ipa.el:261:34:Warning: reference to free variable
    `company-ipa--unicode-prefix-regexp'
```
It looks like you're using `setq` to declare variables -- use `defvar`.  I also notice `company-ipa--latex-prefix-regexp` isn't used anywhere.

checkdoc 0.6.2:
- No issues!

package-lint 20200906.512:
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- company-ipa.el#L3: Have you done the paperwork or is this copy-pasted?  If you haven't done the paperwork, the copyright is your own.
- company-ipa.el#L24: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by riscy** [comment]
That's just a quick first pass -- let me know if you have any questions.

**Comment by mguzmann** [comment]
Thank you for checking! I have fixed the two issues you mention (I think).

**Comment by riscy** [comment]
This looks cool.  Some more feedback now that I've had a chance to look in depth:

- Using "¬" as a leader seems tricky - I definitely don't have that key on my (US/NA) keyboard.  Maybe a sequence of leader characters that appear on more (most?) keyboards, like <kbd>~pp</kbd> would make it more accessible
- I notice `company-ipa-symbols-unicode` mentions "mathematical" symbols
- This is minor, but instead of instructing users `To change the prefix, execute: (setq company-ipa-symbol-prefix "·") before loading this file` you could provide a setter function that also regenerates the `company-ipa--unicode-prefix-regexp` variable (I assume that's why you wrote "before loading this file")

**Comment by riscy** [comment]
I'll mark this awaiting upstream, but feel free to ping.

**Comment by riscy** [comment]
Friendly ping - I think this one is pretty close to ready, there are just the minor nags above.

**Comment by mguzmann** [comment]
Thank you for the patience. The first two are easy, I am wondering about the third one since I'm not so experienced with elisp and packages. Would something like

```
(defun company-ipa-set-trigger-prefix (prefix)
  "Change the trigger prefix for company ipa."
  (progn
    (setq company-ipa-symbol-prefix prefix)
    (setq company-ipa--unicode-prefix-regexp
	  (concat (regexp-quote company-ipa-symbol-prefix)
		  "[^ \t\n]*"))
    (setq company-ipa--symbols
	  (company-ipa--make-candidates company-ipa-symbol-list-basic))))
```

Be ok?

**Comment by riscy** [comment]
Yes, exactly - although the progn isn't necessary under the defun so you can drop that.  That'll make it easier for users to try things out without having to restart Emacs.

**Comment by mguzmann** [comment]
Got it, thanks. I pushed the changes.

**Comment by riscy** [comment]
Thanks, looks good to merge to me.  Very minor and not a blocker but on second look I notice you're downcasing "ipa" everywhere, except in in the summary line where you write "Ipa".  Since it's an acronym I think it's preferred to just write IPA everywhere. 

I'll also add you never expand the acronym anywhere, so nobody reading your Commentary/summary line alone will know what this does.  I know of at least one other thing IPA could refer to. :)

**Pull request merged**
