### PR TITLE
Add nyxt.el recipe

### PR DESCRIPTION
**Pull request by migalmoreno**
### Brief summary of what the package does

This package offers a minimal API to interact with the Nyxt browser from Emacs.

### Direct link to the package repository

https://github.com/migalmoreno/nyxt.el

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
I notice you're polling via `sleep-for` in `nyxt--sly-eval` and `nyxt-run`. Is there a cleaner way to do this?
e.g. Make them asynchronous and take a callback.

At the very least, you may want to switch to `sit-for` which will still allow the Emacs display to update. You can also give the user an indication that they're in a polling by setting `mode-line-process` while polling. The poll interval should be made customizable as well.

**Comment by riscy** [comment]
I will add my much less thoughtful first pass here --

`nyxt.el` with byte-compile using Emacs 29.1:
```
nyxt.el:125:62: Warning: reference to free variable `exwm--frame'
nyxt.el:129:45: Warning: reference to free variable `exwm-workspace--current'
In end of data:
nyxt.el:128:31: Warning: the function `exwm-workspace--position' is not known to be defined.
nyxt.el:128:8: Warning: the function `exwm-workspace-switch' is not known to be defined.
```
I think these are just unavoidable if the user doesn't have exwm installed.  And I think it makes sense for the user to be seeing these warnings during byte-compile when that's the case.

`nyxt.el` with package-lint 20231121.1907:
```
2 issues found:
9:37: warning: Use a properly versioned dependency on "sly" if possible.
116:5: error: You should depend on (emacs "26.1") or the compat package if you need `when-let*'.
```
See https://stable.melpa.org/#/sly for a version.

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to reach out.

**Comment by riscy** [comment]
Friendly ping. :)

**Pull request closed without merging**
