### PR TITLE
Add doom-modeline recipe

### PR DESCRIPTION
**Pull request by seagle0128**
### Brief summary of what the package does

The modeline package extracted from [DOOM Emacs](https://github.com/hlissner/doom-emacs/tree/master/modules/ui/doom-modeline).

### Direct link to the package repository

https://github.com/seagle0128/doom-modeline

### Your association with the package

maintaner

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by seagle0128** [comment]
Any update for this PR? Can you please accept it?

**Comment by DamienCassou** [comment]
Sorry for the delay.

1. the `deface`s following a `defgroup` don't have to specify the `:group` because the group is inferred
3. Please run linters specified in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md). They would have told you about:
    1. including Emacs in the package description (first line of the file is redundant)
    2. you should use standard keywords
    3. you shouldn't globally change values of other packages' variables because users might have specified something different. If you only want to declare the variables to please the compiler, remove the second argument to `defvar`. If you want to change the value of these variables while doom-modeline executes, let-bind them. If you really want to force new defaults on these variables, do that from a minor mode.
    4. there should be 2 spaces after periods in docstrings
    5. function docstrings should reference every argument (not the case of `doom-modeline--buffer-file-name-relative`)
    6. all variables and functions must have a docstring
5. the `defgroup` makes `doom-modeline` a subgroup of `doom` which may not exist. I suggest referencing a standard group instead
6. please add dash to the list of Package-Requires (even if it's already a requirement of another dependency)

**Comment by seagle0128** [comment]
Thanks for your update!

I've fixed all issues according to your feedback. Please check the latest commit.

Only one question.
> there should be 2 spaces after periods in docstrings

If I add 2 spaces after periods, I got another warning:
`Second line should not have indentation (emacs-lisp-checkdoc)`.

So I have to a one empty in the second line. Is it Okay?

**Comment by alphapapa** [comment]
I think the two-spaces rule doesn't apply across line breaks.

**Comment by seagle0128** [comment]
@alphapapa @DamienCassou  Thanks! I updated the comments again. Please review and approve.

**Comment by purcell** [comment]
Looking ready to merge now, which I'll go ahead and do, but I'd like to point out that you shouldn't ever `:inherit` other faces and *also* override their attributes, e.g. by making them bold, underlined or inverse-video. That could easily look awful, just as if you had invented your own colours. The best approach here is to simply `:inherit` the faces, and leave the user to customise the rest.

**Comment by seagle0128** [comment]
Thanks for your comments, @purcell !
I will improve in the future release.

**Pull request merged**
