### PR TITLE
Add recipe for org-assistant.

### PR DESCRIPTION
**Pull request by tyler-dodge**
### Brief summary of what the package does

org-assistant provides support for accessing chat APIs such as ChatGPT in the context of an org notebook

### Direct link to the package repository

https://github.com/tyler-dodge/org-assistant

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`org-assistant.el` with byte-compile using Emacs 28.1:
```
org-assistant.el:56:1: Warning: Package cl is deprecated
In org-assistant-execute:
org-assistant.el:181:66: Warning: Unused lexical variable `url-request-method'
org-assistant.el:181:66: Warning: Unused lexical variable
    `url-request-extra-headers'
org-assistant.el:165:52: Warning: Unused lexical variable `url-request-data'
In end of data:
org-assistant.el:347:13: Warning: the function `org-babel-execute:?' is not
    known to be defined.
org-assistant.el:177:7: Warning: the function `deferred:url-retrieve' is not
    known to be defined.
org-assistant.el:142:8: Warning: the function `auth-source-search' is not
    known to be defined.
```
I think the `cl is deprecated` warning is out of your control and due to `uuid`.  In the case of the unused lexical variables (which are indeed used downstream) you can use e.g. `(defvar url-request-method)` at the top level to pacify the byte-compiler.  `auth-source-search` is not autoloaded so you should `(require 'auth-source)`.  The undefined `deferred` functions are worth looking into, I believe.

`org-assistant.el` with package-lint 20230315.1052:
```
1 issue found:
342:25: error: You should depend on (emacs "28.1") if you need `string-fill'.
```

**Comment by tyler-dodge** [comment]
Thanks for taking a look.

I made an update to the repo so those issues should be fixed: https://github.com/tyler-dodge/org-assistant/commit/b4314184820b359f8e14bc9d6199f8385c17f732

Also, I added a [package-lint](https://github.com/tyler-dodge/org-assistant/blob/main/nix/package-lint.nix) 
nix target so that should avoid this class of issues from other packages I submit in the future since it'll ensure a clean build that uses package.el.

**Comment by riscy** [comment]
Is this very similar to this [org-ai](https://melpa.org/#/org-ai) that was merged last month? (https://github.com/melpa/melpa/pull/8457)  I had a quick look at org-ai's commentary which mentions being able to be used `Inside org-mode / #+begin_ai..#+end_ai blocks`.  If that's the case, there may be a benefit in adding any features you perceive as missing to the former package.

**Comment by tyler-dodge** [comment]
It looks like org-ai uses some non-standard begin_ai end_ai blocks instead of org babel's common patterns.

It's similar, but it looks like it has a different underlying philosophy on how they want to integrate with org, and I think that is enough of a difference to warrant a separate package.

**Comment by riscy** [comment]
Okay, that sounds reasonable.  I'd recommend you M-q (`fill-paragraph`) the paragraphs in your `;;; Commentary` since MELPA won't autoformat this for you when displaying the package in the web index.  Wrapping at a consistent 80 columns is standard and doesn't look that bad.

You might be able to improve some of the nesting in `org-assistant--org-blocks`, e.g. the form `(progn (let* ((match-start ...` doesn't need a `progn` because the `let` is enough to wrap the individual forms.  I think the same can be said of the deeply nested `progn` in `org-assistant-org-babel-async-response` (on line 225).

These are non-blocking, however.  Thanks again - merging.

**Pull request merged**
