### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by riscy** [comment]
I'm not well-versed in setting up dependabot like this, but should this be in `.github/workflows` instead of just `.github`?

In my experience dependabot is already raising alerts and making PRs in my own repositories without any additional setup (for better or worse; e.g. it will PR version changes that are incompatible with other dependencies).

Maybe you could let us know what this would add?

**Comment by riscy** [comment]
I was a bit fast to reply to this one.  I probably have to read more from your links, to be honest. :)

**Comment by riscy** [comment]
Apologies for taking so long to look at this one.  I want ahead and read some of the documentation:

> When you enable Dependabot version updates for GitHub Actions, Dependabot will help ensure that references to actions in a repository's workflow.yml file are kept up to date.

Correct me if I'm wrong; my understanding is this enables a check for code that doesn't exist yet on MELPA.  This isn't necessarily a bad thing to do.  But I personally try to veer away from speculative additions to a code base, and I don't foresee a need for this now or in the near-to-medium future.

**Comment by naveensrinivasan** [comment]
> Apologies for taking so long to look at this one. I want ahead and read some of the documentation:
> 
> > When you enable Dependabot version updates for GitHub Actions, Dependabot will help ensure that references to actions in a repository's workflow.yml file are kept up to date.
> 
> Correct me if I'm wrong; my understanding is this enables a check for code that doesn't exist yet on MELPA. This isn't necessarily a bad thing to do. But I personally try to veer away from speculative additions to a code base, and I don't foresee a need for this now or in the near-to-medium future.

OK. I will close it.

**Pull request closed without merging**
