### PR TITLE
Add ivy-omni-org

### PR DESCRIPTION
**Pull request by akirak**
### Brief summary of what the package does

Unified Ivy interface to access Org buffers, Org files, and Org bookmarks

### Direct link to the package repository

https://github.com/akirak/ivy-omni-org

### Your association with the package

I am the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Cool, I'm interested in using this.  I left a similar comment in your other PR:
- Since you use `if-let`, it may be worth adding: `(require 'subr-x)`

**Comment by akirak** [comment]
Thanks, but I didn't find `if-let` in the source code of this package. Maybe I deleted that at some moment.

**Comment by riscy** [comment]
Woops, sorry about that -- I meant to copy/paste the line `(require 'seq)` for `seq-difference`

**Comment by akirak** [comment]
Thank you, I've fixed that.

**Comment by purcell** [comment]
Looks good, thanks - merging.

In general it's worth considering using the `seq-` functions when possible. I've noticed that the `seq` equivalents of some `cl-` functions like `cl-remove-duplicates` are *much* more efficient, which can make a difference in completion code.

**Pull request merged**
