### PR TITLE
Add package hack-mode, a major mode for hacklang

### PR DESCRIPTION
**Pull request by jra3**
### Brief summary of what the package does

A new major mode for [hacklang](https://hacklang.org/)

### Direct link to the package repository

https://github.com/hhvm/hack-mode

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Couple of issues here:

- You've got the dependencies a bit muddled up here, because a major mode should not be depending on something opinionated like `lsp-hack`. Let your users install that separately, don't force it on them. Major modes are primarily for indentation and font lock.
- You're trampling the `auto-mode-alist` entry for `.php` whenever this is installed, but that's bad practice unless your package is unambiguously the community-wide default for that extension. Instead, suggest that users add that entry themselves, or simply do it when this feature is loaded.
- Don't [modify your own major mode hook](https://github.com/hhvm/hack-mode/blob/a41009780b7eb940585602a0b0005abb1dd32fb8/hack-mode.el#L639)
- [These old-fashioned lines](https://github.com/hhvm/hack-mode/blob/a41009780b7eb940585602a0b0005abb1dd32fb8/hack-mode.el#L627-L632) should be generated for you by `define-major-mode`, so you should be able to delete them.

Hope that helps!

**Comment by purcell** [comment]
Also, sorry about the slow turnaround.

**Comment by jra3** [comment]
I appreciate the feedback. It was really valuable and pointed out a bunch of problems.

I've made the suggested changes in the source repo

**Comment by purcell** [comment]
Looks great, thanks - merged!

**Pull request merged**
