### PR TITLE
Add recipe for `project-butler`

### PR DESCRIPTION
**Pull request by sthesing**
### Brief summary of what the package does

This package is a little add-on to Emacs' built-in `project.el`. It opens buffers and windows for you and arranges them according to your specifications. It does so by offering an "Open buffers" command into the list of `project-switch-commands`  presented to the user when selecting a project.

### Direct link to the package repository

https://codeberg.org/jabbo/project-butler

### Your association with the package

Author, maintainer, enthusiastic user.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.

Have you checked out e.g. [burly](https://melpa.org/#/burly)?  I am not an expert in burly or your package, but it strikes me that maybe all you want is a hook on certain project.el commands that invokes functions from burly?  In that way you could avoid having to write all of the window management stuff yourself (including I think the interesting DSL you came up with to implement `project-butler--place-buffers`).

**Comment by sthesing** [comment]
Hi, thanks for taking the time and the feedback!
Yeah, I'm aware of burly and I have just a few days ago become aware of [Activities](https://elpa.gnu.org/packages/activities.html) (by the same author) as well.
You're right that they do very similar things and if all I wanted was invoking them via project switching, I'd probably have an easier time doing that.
The main differences (if I understand it correctly) are that both burly and activities

1. approach it by "saving" the current state of windows and buffers and restoring it later
2. store that state in a format that is not designed to be read an edited by humans. burly for example leverages Emacs' bookmarks functionality to store an URL string that begins with something like `emacs+burly+windows:?%28%28%28min-height%20` and goes on for some 30 lines.  Activities is more readable because it stores the state in automatically generated elisp code.

The approach of my package is to define the desired state. For people like me who like to declaratively configure their setup in text and reproduce it on different machines, this is preferable. For others who want to continue from where they left off, burly and/or activities is preferable.
So I guess these packages serve (slightly) different use cases.

**Comment by riscy** [comment]
This sounds reasonable, but if that is your distinguishing feature you should definitely add it to your `;;; Commentary` and/or your README so that users know how this package is different from other packages.  Currently you only write "Add-on for project.el to automatically open and arrange project related buffers and windows," so nobody will know about the key feature of configuring their setup in text.

**Comment by sthesing** [comment]
Thanks so much for your feedback. Thinking about it made me understand my own package better.
If have changed both the commentary and project description in the README and have also added a subheading to the "Alternatives" section, there. That should give users a good idea what the package is about and provide users who are looking for something else helpful directions.

Again, thanks for taking the time! This is so helpful.

**Comment by riscy** [comment]
Thank you - I like the new commentary. I'll go ahead and merge this.  And, welcome to MELPA. :)

**Comment by sthesing** [comment]
Thanks!

**Pull request merged**
