### PR TITLE
add recipe flycheck-inline

### PR DESCRIPTION
**Pull request by stardiviner**
### Brief summary of what the package does

Display flycheck error message with inline style.

### Direct link to the package repository

https://github.com/stardiviner/flycheck-inline

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by stardiviner** [comment]
What does this CI error means?
```
  Scenario: read recipes
    Given read recipes
      Recipe 'flycheck-inline' contains mismatched package name 'flycheck-pos-tip'
2 scenarios (1 failed, 1 passed)
3 steps (1 failed, 0 skipped, 2 passed)
```

**Comment by purcell** [comment]
> What does this CI error means?

Can you guess? ;-) Look at the content of your pull request -- there's an error with it. You've checked the box above which says "I've built and installed the package using the instructions in CONTRIBUTING.md", but that can't be true in this case.

**Comment by stardiviner** [comment]
Damn, I forget to write the correct package name. I've updated recipe.

**Comment by stardiviner** [comment]
@purcell I updated my recipe, and updated my package by adding a minor mode for easily toggle this minor mode.

**Comment by purcell** [comment]
Thanks. Feedback on the code now:

- Please provide a very brief `Commentary` section describing how to use the code.
- `with-eval-after-load 'flycheck` is inappropriate: just `(require 'flycheck)` at the top level
- The minor mode is not a great solution, because when you disable it, it might not restore `flycheck-display-errors-function` to its previous value. Instead, just give the user instructions to `(setq flycheck-display-errors-function 'flycheck-inline)`, and add an `;;;###autoload` cookie comment for the `flycheck-inline` function.

**Comment by stardiviner** [comment]
@purcell updated. Check out them.
Ask one question, why this minor mode toggle (disable) will not restore `flycheck-display-errors-function` to default value? even I set code like this?
```elisp
(define-minor-mode flycheck-inline-mode
  "This is a minor mode to display flycheck error message in inline way."
  :global t
  (if flycheck-inline-mode
      (setq flycheck-display-errors-function 'flycheck-inline)
    (setq flycheck-display-errors-function 'flycheck-display-error-messages)
    ))
```
If so, is there a correct solution?

**Comment by purcell** [comment]
> Ask one question, why this minor mode toggle (disable) will not restore flycheck-display-errors-function to default value? even I set code like this?

Because `flycheck-display-errors-function` might not have been `flycheck-display-error-messages` when the mode was enabled.

What you're talking about here is a simple setting, not a toggled mode, so just remove the mode.

**Comment by stardiviner** [comment]
What about enable this hook in major mode hook? Like:
```elisp
(add-hook 'clojure-mode-hook #'flycheck-inline-mode)
```
This will override flycheck default have been `flycheck-display-error-messages` value.

**Comment by purcell** [comment]
> This will override flycheck default have been flycheck-display-error-messages value.

Only if someone hadn't previously set it to something different!

What you should probably do is just provide an autoloaded `flycheck-inline-enable` function which simply says `(setq-local flycheck-display-errors-function 'flycheck-inline)`.

**Comment by purcell** [comment]
(I say `setq-local`, because if you want to add it to a major mode hook, presumably your intention is to change the local flycheck behaviour, not the global flycheck behaviour.)

**Comment by stardiviner** [comment]
Ok, I will code, use `setq-local`, and update usage commentary.
I'm still uploading code.

**Comment by stardiviner** [comment]
@purcell Hi, I updated my source code.

**Comment by purcell** [comment]
> Hi, I updated my source code.

But the global minor mode is still there, and using `setq-local` in it is incorrect. As I suggested above, I think the mode should be removed and replaced with a simple "enable" command.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by stardiviner** [comment]
@tarsius @purcell , Hi sorry for late response, I'm busy on life mess recently. I updated my code, check it out.

**Comment by purcell** [comment]
Thanks. Sent you a couple of fixes in https://github.com/stardiviner/flycheck-inline/pull/1.

**Comment by stardiviner** [comment]
@purcell merged. Thanks.

**Comment by purcell** [comment]
Great!

**Pull request merged**
