### PR TITLE
Add select-themes recipe

### PR DESCRIPTION
**Pull request by jasonm23**
Simple interactive theme selector that disables other custom themes before loading the selected theme or "-- Default --"

### CODE REVIEW

**Comment by syohex** [comment]
You need not to specify `:files` attribute. It is enough to use default pattern. Default pattern is as below. Please see `:files` section of [here](https://github.com/melpa/melpa#recipe-format) in more detail.

```
("*.el" "*.el.in" "dir"
 "*.info" "*.texi" "*.texinfo"
 "doc/dir" "doc/*.info" "doc/*.texi" "doc/*.texinfo"
 (:exclude ".dir-locals.el" "test.el" "tests.el" "*-test.el" "*-tests.el"))
```

**Comment by jasonm23** [comment]
Sure, but it's not a problem to include it.  See `use-package`

**Comment by syohex** [comment]
However you need to update MELPA recipe if you add some files in that repository in the future. (While you need not to update MELPA recipe if files you add are matched against default pattern.)

**Comment by jasonm23** [comment]
That's ok, I know how it works.  Please note, this package won't have additional files.

In the unlikely occasion that it does, I will update or remove the `:files` keyword as appropriate.

Thanks for raising the flag anyway, someone else may not know how it works.

**Comment by purcell** [comment]
Yep, when the default is adequate, we would prefer that it is not overridden. I'll make that clearer in the README.

**Comment by jasonm23** [comment]
I'm only reluctant to fix it now because I'm away from a machine for 24-48+ hours, phone only.

I can probably ssh onto something and do it if it's a requiremebtZ

**Comment by jasonm23** [comment]
Done via the magic of tiny fonts and unix shells :)

**Comment by jasonm23** [comment]
Travis errors don't seem to be related to **select-themes**

**Comment by jasonm23** [comment]
closing and reopening to force travis to rerun

**Pull request closed without merging**
