### PR TITLE
added company-solidity

### PR DESCRIPTION
**Pull request by ssmolkin1**
### Brief summary of what the package does

This is a simple company-mode back-end which provides autocompletion for the Solidity programming language.

### Direct link to the package repository

https://github.com/ssmolkin1/company-solidity

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [ x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x ] My elisp byte-compiles cleanly
- [ x ] `M-x checkdoc` is happy with my docstrings
- [ x ] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

- You're missing package dependency declarations for `company` and `cl-lib`.
- You might like to add an `;;;###autoload` cookie comment for the `company-solidity` function.

**Comment by ssmolkin1** [comment]
Thanks! I've updated the package to fix both issues.

**Comment by purcell** [comment]
Great - merged, thanks! Welcome to MELPA. :tada:

**Comment by ssmolkin1** [comment]
Thanks!

**Pull request merged**
