### PR TITLE
Add recipe for quoted-scratch

### PR DESCRIPTION
**Pull request by narendraj9**
### Brief summary of what the package does

This package lets you add new quotes to a collection of Quotes. Displays random quote from the collection in the scratch buffer. It also allows you to have a quote from htttp://quote.rest/qod.json in your scratch buffer on startup. I have also included some Auroville qualities with the quote text in Chinese and English.

### Direct link to the package repository

https://github.com/narendraj9/quoted-scratch

### Your association with the package

I am the creator and maintainer.

### Relevant communications with the upstream package maintainer

None needed

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Load url.el for using its features
- Please use `-` separator instead of `/` for coding convention

**Comment by narendraj9** [comment]
@syohex Fixed the above two issues. :) Thanks.

**Comment by syohex** [comment]
- There is an issue on older Emacs(https://github.com/narendraj9/quoted-scratch/pull/1)

**Comment by narendraj9** [comment]
@syohex Merged your pull request. Thanks! :)

**Comment by narendraj9** [comment]
@syohex Is there anything else I should change?

**Comment by purcell** [comment]
Quick feedback:
- Use `:defaults` in the recipe, please, rather than `"*.el*`
- Don't use the `qs-` prefix: use `quoted-scratch-`
- When setting faces, don't specify only one colour: either provide `dark` _and_ `light`-background versions of the face, or (better) `:inherit` from a standard face so that the default appearance matches the user's theme.
- Most of the code in this package is a reinvention of code in `fortune.el`, particularly the `fortune` function. Please just use the code there instead.

The particular combination of quote and Auroville quality makes this feel like a _very_ personal set of configuration, so I'm not sure I can see this being widely appealing, and my current feeling is that you should probably keep it in your own Emacs config rather than trying to package it here.

**Comment by narendraj9** [comment]
@purcell The Auroville quality can be hidden with a custom parameter that is provided. I think you have a valid point. This might not be useful for a wide set of people.

**Comment by purcell** [comment]
I was thinking about this: the generalisation would be to create a kind of `scratch-format` package, which would provide a `scratch-format` variable a little like the existing `mode-line-format`. Users could customise that variable as desired (including with `:eval` forms), and the package would ensure that the variable was re-applied to the scratch buffer when changed.

A recently-added package which is a little similar is [scratch-message](https://github.com/thisirs/scratch-message/blob/master/scratch-message.el), by @thisirs. That package is quite similar to this one, including a predefined selection of quotes.

Rather than everyone reinventing the wheel, perhaps it'd be worth you and @thisirs building upon `scratch-message` so that it works for both of you, possibly using the format variable idea above? I'd be really keen to see what you might come up with.

In any case, there are so many overlapping scratch-related packages (see also [fortune-cookie](https://github.com/andschwa/fortune-cookie), for example) that I'm not keen to add this one too, sorry.

**Comment by narendraj9** [comment]
@purcell The generalisation idea is really cool. Thanks! :+1:

**Pull request closed without merging**
