### PR TITLE
Added recipe for alpha-sudo

### PR DESCRIPTION
**Pull request by alpha-catharsis**
### Brief summary of what the package does

sudo-utils provides some useful interactive and non-interactive functions for working with sudo shell program.

### Direct link to the package repository

https://github.com/alpha-catharsis/sudo-utils

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, checklist looks good and the code and documentation are solid.  The only thing I'd suggest is to not put your username in the package's name, since it adds a spurious search keyword (maybe sudo-util?)

Minor:
- withouth -> without
- environmente -> environment
- suggetions -> suggestions

**Comment by alpha-catharsis** [comment]
> Thanks, checklist looks good and the code and documentation are solid. The only thing I'd suggest is to not put your username in the package's name, since it adds a spurious search keyword (maybe sudo-util?)

Thank you very much for the review and for the feedback. I will fix the typos and change the package name as suggested (together with the repository name, functions name prefix and associated documentation, so to make everything coherent). Then I will update the pull request.

**Comment by alpha-catharsis** [comment]
I managed to change the package name and associated items. I made a quick check and everything seems fine.

**Comment by alpha-catharsis** [comment]
OK, I managed to amend the commit message

**Comment by riscy** [comment]
Thanks so much for being accommodating. And, welcome to MELPA! :)

**Pull request merged**
