### PR TITLE
recipes: add el-fetch

### PR DESCRIPTION
**Pull request by xgqt**
### Brief summary of what the package does

Neofetch-inspired, system information gathering program (CPU, memory, Emacs properties).

### Direct link to the package repository

https://gitlab.com/xgqt/emacs-el-fetch (path: `src/el-fetch`)

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
For those of us who don't know what "neofetch" is, you should probably describe what this does without too much prior knowledge.

**Comment by xgqt** [comment]
> For those of us who don't know what "neofetch" is, you should probably describe what this does without too much prior knowledge.

Do you think "Neofetch-inspired, system information gathering program in Emacs Lisp." is sufficient?

**Comment by tarsius** [comment]
> Neofetch-inspired, system information gathering program in Emacs Lisp.

That certainly helped correcting my misconception that this was a download manager. You can drop the "in Emacs Lisp" because that's a given for an Emacs package. You could use the gained room to mention things like cpu, memory, disc usage.

**Comment by xgqt** [comment]
https://gitlab.com/xgqt/emacs-el-fetch/-/commit/3853e1649414a6d0c353aeb153be9224ae6cb1c5

@tarsius up

**Comment by riscy** [comment]
Thanks for accommodating @xgqt -- this package looks useful.  Just running some quick checks here:

`el-fetch.el` with package-lint 20220213.1457:
```
2 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
1:0: warning: The package summary is too long. It should be at most 60 characters.
```
I think it would be clear if you simplified the summary line to the same docstring that `#'el-fetch` has -- you don't have to go into too much detail.  I agree having `neofetch` in the summary line would help discoverability.

`el-fetch.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- el-fetch.el#L191: There is no need to quote lambdas (neither #' nor ')
```

Package and license:
- Add a GPL-compatible LICENSE file to the repository

Minor stuff:
- It's more typical for the Copyright/Author/Homepage/Version/Package-Requires block to appear closer to the top of the file's frontmatter, but you've got it halfway down the page underneath your Copyright statement.  I don't think this is a blocker -- it's just a little unusual -- but your layout is a little unconventional versus what my eyes are used to seeing.  Take a look at some of the Emacs builtin elisp files (e.g. bytecomp.el) to see a more typical layout
- The backslashes on the parens in `el-fetch-font-lock-keywords` won't do anything; double-check that regexp (maybe you can just remove the backslashes)
- gigibytes -> gigabytes
- In `el-fetch--info-emacs-frame` I might just use `format` instead of `concat`

**Comment by xgqt** [comment]
> Thanks for accommodating @xgqt -- this package looks useful. Just running some quick checks here:
> 
> `el-fetch.el` with package-lint 20220213.1457:
> 
> ```
> 2 issues found:
> 1:0: warning: Including "Emacs" in the package summary is usually redundant.
> 1:0: warning: The package summary is too long. It should be at most 60 characters.
> ```
> 
> I think it would be clear if you simplified the summary line to the same docstring that `#'el-fetch` has -- you don't have to go into too much detail. I agree having `neofetch` in the summary line would help discoverability.
> 
> `el-fetch.el` with [melpazoid](https://github.com/riscy/melpazoid):
> 
> ```
> - el-fetch.el#L191: There is no need to quote lambdas (neither #' nor ')
> ```
> 
> Package and license:
> 
>     * Add a GPL-compatible LICENSE file to the repository
> 
> 
> Minor stuff:
> 
>     * It's more typical for the Copyright/Author/Homepage/Version/Package-Requires block to appear closer to the top of the file's frontmatter, but you've got it halfway down the page underneath your Copyright statement.  I don't think this is a blocker -- it's just a little unusual -- but your layout is a little unconventional versus what my eyes are used to seeing.  Take a look at some of the Emacs builtin elisp files (e.g. bytecomp.el) to see a more typical layout
> 
>     * The backslashes on the parens in `el-fetch-font-lock-keywords` won't do anything; double-check that regexp (maybe you can just remove the backslashes)
> 
>     * gigibytes -> gigabytes
> 
>     * In `el-fetch--info-emacs-frame` I might just use `format` instead of `concat`



> 1:0: warning: Including "Emacs" in the package summary is usually redundant.

It complains about "Emacs" in "... (CPU, memory, Emacs properties)". I dont know what I should replace Emacs to here...


> Add a GPL-compatible LICENSE file to the repository

Already there:
https://gitlab.com/xgqt/emacs-el-fetch/-/blob/master/LICENSE.txt


> The backslashes on the parens in el-fetch-font-lock-keywords won't do anything; double-check that regexp (maybe you can just remove the backslashes)

It works for me like it should - text inside `()` has `font-lock-comment-face`


> gigibytes -> gigabytes

I was taught that `1024^3`B is GiB - gibibyte and `1000^3`B a GB - gigabyte

**Comment by xgqt** [comment]
Can we agree on `Neofetch-like, information gathering program (CPU, RAM, etc)`?
It is exactly 60 chars.

**Comment by xgqt** [comment]
Honestly the best way would be if @tarsius (who, I assume, takes care of merging PRs) would recommend a description, cause we can go on like this indefinite amount of time. :D

Also, update: https://gitlab.com/xgqt/emacs-el-fetch/-/commit/65107390ea0dc197fca3e82d08361aa4e1e3b9cf

**Comment by xgqt** [comment]
> I think it would be clear if you simplified the summary line to the same docstring that #'el-fetch has -- you don't have to go into too much detail. I agree having neofetch in the summary line would help discoverability.

Oh, I forgot about this!

Up: https://gitlab.com/xgqt/emacs-el-fetch/-/commit/2f76f47ab8b8330f04be4c045f3496dd0a59f251

**Comment by riscy** [comment]
> I dont know what I should replace Emacs to here...

In that case the Emacs was probably a mild false-positive, but sometimes some modest rephrasing can get you at something that none of the linters complain about -- which it looks like you did.

> [LICENSE.txt] already there

This is on me -- my checks weren't looking for a file called LICENSE.txt.  Fixed on my end now.

> I was taught that 1024^3B is GiB - gibibyte and 1000^3B a GB - gigabyte

You're right about these terms; new to me. :)

This all looks good to go now.  Thanks for this, and welcome to MELPA. :)

**Comment by xgqt** [comment]
> > I dont know what I should replace Emacs to here...
> 
> In that case the Emacs was probably a mild false-positive, but sometimes some modest rephrasing can get you at something that none of the linters complain about -- which it looks like you did.
> 
> > [LICENSE.txt] already there
> 
> This is on me -- my checks weren't looking for a file called LICENSE.txt. Fixed on my end now.
> 
> > I was taught that 1024^3B is GiB - gibibyte and 1000^3B a GB - gigabyte
> 
> You're right about these terms; new to me. :)
> 
> This all looks good to go now. Thanks for this, and welcome to MELPA. :)

Thank you too.
Late response since I did not get a e-mail notification...

**Pull request merged**
