### PR TITLE
Add Gopher recipe.

### PR DESCRIPTION
**Pull request by msnyder-info**
### Brief summary of what the package does

Gopher.el is a browser for Gopher sites. Gopher is a linked set of largely textual sites or "gopher holes". It predates the web and is experiencing re-growth as its qualities compare favorably against the bloat and advertising of the modern web.

### Direct link to the package repository

https://github.com/msnyder-info/gopher.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

N/A
### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [*] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

*save for one warning

### CODE REVIEW

**Comment by purcell** [comment]
Great comments, @riscy, thanks. I'll hold off on taking a closer look until we hear back from @msnyder-info, but I already see some issues like a missing package dependency on `cl-lib`, which `package-lint` should really have caught...

**Comment by purcell** [comment]
Ping!

**Comment by msnyder-info** [comment]
Sorry for the radio silence on this. I'm going to be going traveling for the next week and will hopefully have the bandwidth to tackle the issues seen here by then. Thanks @purcell and @riscy! Is it okay if this PR sticks around until then?

**Comment by purcell** [comment]
> Is it okay if this PR sticks around until then?

Yup!

**Comment by kensanata** [comment]
Looks like @Chobbes's changes fixed almost all of the issues?

**Comment by purcell** [comment]
> Looks like @Chobbes's changes fixed almost all of the issues?

Yes, but just needs to declare package dependencies. I submitted a fix for this in https://github.com/msnyder-info/gopher.el/pull/23 -- once merged, this PR can also be merged.

**Comment by riscy** [comment]
Looking ready to go.  Welcome to MELPA. :)

**Pull request merged**
