### PR TITLE
add recipe for flexoki-themes

### PR DESCRIPTION
**Pull request by crmsnbleyd**
### Brief summary of what the package does

This package includes a dark and light theme variant of the [Flexoki](https://stephango.com/flexoki) colour scheme.

### Direct link to the package repository

[https://github.com/crmsnbleyd/flexoki-emacs-theme](https://github.com/crmsnbleyd/flexoki-emacs-theme)

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

* No byte-compile error 🎉 

`flexoki-themes.el` with checkdoc (0.6.2)

```
No issues found
```

`flexoki-dark-theme.el` with checkdoc (0.6.2)

```
flexoki-dark-theme.el:22: First sentence should end with punctuation
```

`flexoki-light-theme.el` with checkdoc (0.6.2)

```
flexoki-light-theme.el:22: First sentence should end with punctuation
```

`flexoki-themes.el` with package-lint (20230905.629)

```
No issues found.
```

`flexoki-dark-theme.el` with package-lint (20230905.629)

```
2 issues found:

9:0: error: Package-Requires outside the main file have no effect.
22:0: error: "flexoki-dark" doesn't start with package's prefix "flexoki-themes".
```

`flexoki-light-theme.el` with package-lint (20230905.629)

```
2 issues found:

9:0: error: Package-Requires outside the main file have no effect.
22:0: error: "flexoki-light" doesn't start with package's prefix "flexoki-themes".
```

Package and license:

- GPLv3

**Comment by crmsnbleyd** [comment]
@jcs090218 thank you for your help, I've addressed the issues mentioned in your comment :)

**Comment by riscy** [comment]
Thanks @crmsnbleyd - I am not sure if this is a result of changes made after @jcs090218 's suggestions, but here's a quick pass:

`flexoki-themes-dark-theme.el` with byte-compile using Emacs 28.1:
```
flexoki-themes-dark-theme.el:22:2: Warning: the function
    `flexoki-themes-create' is not known to be defined.
```
Due to a missing `(require ...`

`flexoki-themes-dark-theme.el` with package-lint 20230905.629 and `package-lint-main-file` = "flexoki-themes.el":
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

`flexoki-themes-light-theme.el` with byte-compile using Emacs 28.1:
```
flexoki-themes-light-theme.el:22:2: Warning: the function
    `flexoki-themes-create' is not known to be defined.
```

`flexoki-themes-light-theme.el` with package-lint 20230905.629 and `package-lint-main-file` = "flexoki-themes.el":
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

Package and license:
- Avoid specifying `:branch` except in unusual case; MELPA will read your default branch (whether it is named "trunk" or something else) so we prefer that it isn't hardcoded

**Comment by crmsnbleyd** [comment]
thanks @riscy , I had mistakenly removed `(require 'flexoki-themes)` from the two files assuming package-requires referred to that -- quite silly of me. Sorry! Package-lint is now happy, and so is the byte-compiler

**Comment by riscy** [comment]
Thank you @crmsnbleyd - looks good.  Welcome to MELPA. :)

**Pull request merged**
