### PR TITLE
add vulpea recipe

### PR DESCRIPTION
**Pull request by d12frosted**
### Brief summary of what the package does

A bunch of helpers for dealing with `org-roam` files. The most
important assumption of this library (and the reason it can't be part
of upstream) is that each note is required to have a file-level `ID`
in `PROPERTIES` drawer (which is available only in latest versions of
Org).

It also provides  an API for working with description  lists in notes.
The first description list in file is called `meta` and hence the name
of `vulpea-meta` module.

I am not sure if anyone is interested in this library. I would love to
have it as part of MELPA to ease the distribution. I am using this
library in my personal projects (which are not *yet* open sourced). So
if you think it that it's too *personal*, feel free to reject this
recipe. On the other hand, your feedback is always valuable 😸 

Thanks in advance for your time!

### Direct link to the package repository

https://github.com/d12frosted/vulpea

### Your association with the package

I am a maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them (haha, a good one!)

<details>
  <summary>make recipe/vulpea</summary>
  <pre>

λ make recipes/vulpea
 • Building package vulpea ...
Package: vulpea
Fetcher: github
Source:  https://github.com/d12frosted/vulpea.git

Updating /Users/d12frosted/Developer/melpa/working/vulpea/
Copying files (->) and directories (=>)
  from /Users/d12frosted/Developer/melpa/working/vulpea/
  to /var/folders/8f/4rf99dhs1p9g6k4bcy8n9w6c0000gn/T/vulpea7y6lGY/vulpea-20210112.1723
    vulpea-db.el -> vulpea-db.el
    vulpea-meta.el -> vulpea-meta.el
    vulpea-utils.el -> vulpea-utils.el
    vulpea.el -> vulpea.el
Created vulpea-20210112.1723.tar containing:
  vulpea-20210112.1723/
  vulpea-20210112.1723/vulpea-db.el
  vulpea-20210112.1723/vulpea-meta.el
  vulpea-20210112.1723/vulpea-pkg.el
  vulpea-20210112.1723/vulpea-utils.el
  vulpea-20210112.1723/vulpea.el
Built vulpea in 6.588s, finished at Tue Jan 12 20:19:34 2021
 ✓ Success:
4.0K -rw-r--r-- 1 d12frosted staff  367 Jan 12 20:19 packages/vulpea-20210112.1723.entry
 24K -rw-r--r-- 1 d12frosted staff  22K Jan 12 20:19 packages/vulpea-20210112.1723.tar
4.0K -rw-r--r-- 1 d12frosted staff 1.2K Jan 12 20:19 packages/vulpea-badge.svg
4.0K -rw-r--r-- 1 d12frosted staff   18 Jan 12 20:19 packages/vulpea-readme.txt

  </pre>
</details>

### CODE REVIEW

**Comment by riscy** [comment]
> I am not sure if anyone is interested in this library.

If you're not sure, would you consider posting an RFC on reddit or freenode or similar?

Quick first pass in the meantime.

### vulpea-db.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210111.341):
```
1 issue found:
8:0: error: Package-Requires outside the main file have no effect.
```

Other [lints](https://github.com/riscy/melpazoid):
- vulpea-db.el#L7: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)

### vulpea-meta.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210111.341):
```
1 issue found:
8:0: error: Package-Requires outside the main file have no effect.
```

Other [lints](https://github.com/riscy/melpazoid):
- vulpea-meta.el#L7: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)

### vulpea-utils.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210111.341):
```
1 issue found:
8:0: error: Package-Requires outside the main file have no effect.
```

Other [lints](https://github.com/riscy/melpazoid):
- vulpea-utils.el#L7: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)

### vulpea.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210111.341):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- vulpea.el#L7: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)

### Loadability ###

Verifying ability to #'load each file:
```
Loading vulpea-db.el
Loading vulpea-meta.el
Loading vulpea-utils.el
Loading vulpea.el
Done.
```

### Package ###

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to vulpea-db.el
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to vulpea-meta.el
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to vulpea-utils.el
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to vulpea.el

**Comment by d12frosted** [comment]
@riscy hey, thank you for your feedback. Didn't know about `Version` vs `Package-Version`. And good point regarding License file! Will update.

I have few questions regarding `Package-Requires`. How do you run `package-lint`? Are you using https://github.com/riscy/melpazoid? I did `M-x package-lint-current-buffer` on `vulpea-db.el` and did not get this error:

```
1 issue found:
8:0: error: Package-Requires outside the main file have no effect.
```

On the other hand, if I remove `Package-Requires` I get the followig warnings and errors:

```
4 issues found:

1:44: warning: You should depend on (emacs "24.1") if you need lexical-binding.
36:10: error: You should depend on (emacs "25.1") or the seq package if you need `seq-map'.
43:5: error: You should depend on (emacs "25.1") or the seq package if you need `seq-map'.
62:3: error: You should depend on (emacs "26.1") if you need `when-let*'.
```

So I am confused. Is having `Package-Requires` in each file an issue?

**Comment by riscy** [comment]
Yeah, that's running melpazoid. :) There is a variable you can set in package-lint to specify which is the main file (`package-lint-main-file`).  The danger it's pointing out is that people may end up putting different requirements in each file.  Each file will individually pass package-lint but the package as a whole will only use what's in the main file.  The main file is usually the one whose name matches your recipe name.

But as long as all of the package-requires are the same, it's probably more of a warning.

**Comment by d12frosted** [comment]
Thanks for explanations. I agree that there is a danger of having different `Package-Requires`. Initially I put it there after running linters 😸 And to make `flycheck` working (e.g. not to show me an error when I `require` one of the dependenices).

Will check `package-lint-main-file` option. 💯

**Comment by riscy** [comment]
Thank you, that puts the checklist behind us.  Taking a closer look --

- The package is for org-roam but that isn't reflected in its name, or in its summary line or in its Commentary ("Vulpea is a fox")
- Minor, but along those lines your frontmatter in vulpea.el could be cleaned up (two URL: lines for example, one empty)
- Loading a package shouldn't automatically add advice like `(advice-add 'org-roam-capture--new-file :around #'vulpea--capture-new-file)`; if something goes wrong users will have trouble diagnosing the issue and don't have an ergonomic way to undo this change.  I suggest you put this in your `;;; Commentary` or create a global minor mode that can be toggled off and on
- Everyone has their style but there are benefits to keeping packages inside a single file.  Package-Lint becomes easier to manage, although I'd still encourage you read about package-lint main file; flycheck works without devs having to configure their load path, these sorts of things.  Definitely not a blocker, but something to consider when a package is < ~1000 lines
- Use `;;;###autoload` cookies [sparingly](https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html).   Does `vulpea-meta-clean` need to be autoloaded, for example?

**Comment by riscy** [comment]
I will also add that `org-roam-capture--new-file` has declared itself as a "private" function that technically isn't meant to be used from outside.  Sometimes there's no way around this, but you may wish to contact the author about making that part of the public interface.

**Comment by d12frosted** [comment]
@riscy thank you very much for your feedback. And for your time 💯 

1. Good point. I thought that README is enough, but I should definitely improve summary and commentary.
2. Will clean those up 🤦 
3. Regarding advice. This is something I added recently to overcome an 'async' nature of capturing. I am planning to send a PR to `org-roam` as I think it could be useful for other users to have out of box, meanwhile I will mention it in README and Commentary with instructions how to disable it and what effect it has on users (e.g. after `vulpea-create` database with notes will not be updated automatically).
4. I can definitely understand what you mean. Thankfully, there is `flycheck-eldev` that helps me with multiple files. I will document that it helps with development (aside from running tests and linter). I've split the package into several files because `vulpea-meta` is quite special. Maybe it should be a separate package 🤔 . You give me some topics to think about.
5. I will check all my autoloads. Since it's a library for writing other applications, maybe I can remove most of them. On the other hand, I wanted to help users not to load `org` accidentaly. E.g. `(require 'vulpea)` will load too much elisp. So the usual approach here is not to use autoloads in libraries? I will also check how `dash`, `s` and other libraries do.

So I will cover all these points over the following days and will let you know once done. Meanwhile, could you please let me know if 4-5 make sense to you?

**Comment by d12frosted** [comment]
@riscy docs are improved, autoloads are removed (checked how other libraries approach this - no autoloads). Let me know what you think :)

**Comment by riscy** [comment]
Thanks for having a look.  :)

The summary line "Vulpea is a fox" will probably keep users from understanding what this does and even if it's related to org-roam.  A better summary line would be "A collection of note-taking functions" or something similar.  For example think about users who are searching using MELPA's web search, e.g. https://melpa.org/#/?q=org-roam

> I will mention it in README and Commentary with instructions how to disable it and what effect it has on users (e.g. after vulpea-create database with notes will not be updated automatically).

It isn't just a matter of whether it's documented.  We're pushing back against this sort of thing for all packages.  Behavioral modifications to Emacs at import-time should be disabled by default, and instructions for how to enable them can go in the README/Commentary or be supported by a mode toggle.

**Comment by d12frosted** [comment]
@riscy 

Alright, makes sense regarding the search. Fixed that in https://github.com/d12frosted/vulpea/commit/490d3defcd891bf2be35214a80e571f6cc44c541

Regarding advising, I am not sure that it's a good idea to provide minor mode for utitliary library nor to ask users to do advising by themselves. Unfortunately, this advising is crutial for `vulpea-create` to be not only efficient, but to return some meaningful result users can use afterwards. 

1. Minor mode or some function that does advising sounds appealing, as once advising is not needed, users are not broken by changing implementation details. That function will noop. Besides, minor mode for utility function sounds strange to me.
2. Asking users to do advising by themselves also doesn't sound right to me, because it is implementation detail that will change with time (I am wating for `org-roam` v2 to land, so I can propose some changes in capturing flow). Once advising is not needed, users might suffer from advising private function by themselves.

Also, disabling advise by default means that any package using `vulpea` (for example, [vino][1]) will have to delegate this requirement further to users. And since `vulpea` is mostly a library for writing other applications, it would feel wierd to users of packages using this library, as usage of `vulpea` is implementation detail 🤔 

In any case, I am not arguing with you. I am just trying to get to the right decision from different standpoints. On one hand, I know that advising is considered harmful, on the other hand I think leaking abstractions are much worse in my sense. Right now the only solution satisfying abstraction is a function that will advise and will noop in a month or so (or throw a warning 🤷 , so I can remove it). WDYT?

P. S. thank you for spending so much time on reviewing this package. I've done multiple improvements thanks to you 🙇 

  [1]: https://github.com/d12frosted/vino

**Comment by riscy** [comment]
> Also, disabling advise by default means that any package using vulpea (for example, vino) will have to delegate this requirement further to users. And since vulpea is mostly a library for writing other applications, it would feel wierd to users of packages using this library, as usage of vulpea is implementation detail 🤔

A solution here is that dependent packages like vino could check whether vulpea-mode is active and warn the user, at least until org-roam offers a builtin history of recently captured files.

I'm looking at the code now and see that the modification is small, modifying only one variable, but imagine (for example) if the user simply had `(require 'vulpea)` in their config and the signature of `org-roam-capture--new-file` changed.  Then imagine the user had hundreds of packages loaded, and each one made implicit modifications like this -- it could end up making things hard on users.

**Comment by d12frosted** [comment]
> modifying only one variable
> their config and the signature of org-roam-capture--new-file changed

It modifies only the variable defined and owned by `vulpea`. The idea is to simply remember result of `org-roam-capture--new-file` execution. Signature is not changed, original function is called uncoditionally with all passed arguments. In order to guard myself and others from this advising, I use the following:

1. Advising function [mimics signature][1] of original function. No `&rest args` is used in advising function, so whenever signature of original function changes, `vulpea` breaks. 
2. `vulpea` has [a test][2] relying on proper usage of `org-roam-capture--new-file`.
3. Tests are run not only on `vulpea` code base change, but also on a [daily basis via cron][3].

This advising is also transitively tested in `vino`, because `vulpea-create` is [used][4] [quite][5] [a][6] [lot][7] [in][8] [there][9]. So the tests (daily as well) will fail if contract breaks 😸 

That being said, I will check how to proceed here. Maybe I will be able to sneak with my change to `org-roam` before V2. 😸 In the worst case scenario, I will simply provide a function/mode as you advice.

So will keep you posted! Thanks again for looking into this case ❤️ 

  [1]: https://github.com/d12frosted/vulpea/blob/master/vulpea.el#L133
  [2]: https://github.com/d12frosted/vulpea/blob/master/test/vulpea-test.el#L77
  [3]: https://github.com/d12frosted/vulpea/blob/master/.github/workflows/main.yml#L12
  [4]: https://github.com/d12frosted/vino/blob/master/vino.el#L244
  [5]: https://github.com/d12frosted/vino/blob/master/vino.el#L443
  [6]: https://github.com/d12frosted/vino/blob/master/vino.el#L820
  [7]: https://github.com/d12frosted/vino/blob/master/vino.el#L831
  [8]: https://github.com/d12frosted/vino/blob/master/vino.el#L907
  [9]: https://github.com/d12frosted/vino/blob/master/vino.el#L975

**Comment by riscy** [comment]
I'll mark this awaiting upstream, but feel free to ping for anything.

**Comment by d12frosted** [comment]
Hey @riscy 

I extracted that advice into separate function, so now there are no advices upon loading `vulpea` 😸 Please checkout https://github.com/d12frosted/vulpea/commit/2d145e74ad3de770ee5a35b5cb5afd9d7f1afa99 commit.

**Comment by riscy** [comment]
Excellent, thanks for accommodating. :)

**Pull request merged**
