### PR TITLE
add spinner

### PR DESCRIPTION
**Pull request by brotzeit**
### Brief summary of what the package does

Emacs mode-line spinner for operations in progress 

### Direct link to the package repository

https://github.com/brotzeit/spinner

### Your association with the package

This package is orphaned. It's a dependency of one of my packages. I want to make improvements and want it to be on melpa.

### Relevant communications with the upstream package maintainer

I think @Malabarba doesn't mind if I take maintainership of the package.

### Checklist

- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] My elisp byte-compiles cleanly
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
It's great to see a potentially orphaned package gaining a maintainer.  Thanks a lot for this.

It may be a good idea to raise an [issue](https://github.com/Malabarba/spinner.el/issues) at the original repo, and link it here so we can track @Malabarba 's thoughts.

Also, if you are going to take over maintainership, this is a good opportunity to get the package ready for MELPA:

A quick pass over the checklist:

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190905.1847):
```
4 issues found:

1:1: error: Package should have a Homepage or URL header.
1:1: warning: The package summary is too long. It should be at most 60 characters.
1:95: warning: You should depend on (emacs "24") if you need lexical-binding.
100:14: warning: Replace deprecated `cl' with `cl-lib'.  The `cl-libify' package can help with this.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
No byte-compilation issues! 😎

Added miscellaneous hints (automated):
- spinner.el#L3: I always double-check that maintainers are aware of this line -- something for you to consider/confirm.
- spinner.el#L20: Prefer `https` over `http` (if possible)

**Comment by Malabarba** [comment]
Hey there, :wave: 

I'll admit I completely missed a few spinner PRs a year or two ago. I've rearranged my gmail filters now, so if there's anything you'd like to add to the package I promise I'll be more attentive now.

In any case, adding a package to Melpa with the same name as a package in GNU Elpa but different sources is sure to cause dependency issues for a lot of people as soon as the two packages start diverging in code. 

If you'd like to fork the repo to add features you're free to do so, but please rename the package so  it won't cause people problem. However, if that's the case, I invite to add these features as PRs on the original repo, so they'll be available to every Emacs user (via Gelpa), not just those who've configured Melpa.

**Comment by brotzeit** [comment]
It looked like you don't have the time to maintain the package. The main reason is that I want the package on melpa. My tests are failing because of spinner and this seems to be related to elpa https://travis-ci.com/brotzeit/rustic/jobs/240165667 and some users also seem to have problems installing the package https://github.com/brotzeit/rustic/issues/65. Any idea ?

I would actually be happy if I don't have to maintain another package ;)

**Comment by Malabarba** [comment]
> It looked like you don't have the time to maintain the package. 
For most of my packages, I don't. But spinner is very low maintenance. :-)

> The main reason is that I want the package on melpa. My tests are failing because of spinner and this seems to be related to elpa https://travis-ci.com/brotzeit/rustic/jobs/240165667 and some users also seem to have problems installing the package brotzeit/rustic#65. Any idea ?

This line tells me cask can't find the package, 
`  - Installing [ 4/12] spinner (1.7.3)... not available`
That probably means the configuration you're using in the CI is overriding emacs default `package-archives` variable.

The default value of that variable is `(("gnu" . "https://elpa.gnu.org/packages/"))`. The correct behaviour is to add entries to it, so it would look something like this:
```
(("m-stable" . "http://stable.melpa.org/packages/")
 ("melpa" . "http://melpa.org/packages/")
 ("gnu" . "https://elpa.gnu.org/packages/"))
```

I suspect your CI setup is doing something like this `(setq package-archives '(("melpa" . "http://melpa.org/packages/")
)))`. 

It's very possible the same happens to your users. Some of them might be inadvertently overriding the variable instead of appending to it.

However, this is just speculation based on personal experience, I didn't look deeply into your CI setup.

**Comment by brotzeit** [comment]
> That probably means the configuration you're using in the CI is overriding emacs default package-archives variable.

It worked before and therefore I assumed that `cask` handles this correctly.

Would it be ok for you to put spinner on melpa ? Most new users are used to melpa and I don't see any downside ?

**Comment by alphapapa** [comment]
> It worked before and therefore I assumed that cask handles this correctly.

Cask uses the archive sources configured in the `Cask` file.  Check the Cask documentation for info.

**Comment by Malabarba** [comment]
@brotzeit 

> Would it be ok for you to put spinner on melpa ? Most new users are used to melpa and I don't see any downside ?

The downside is that the way that Melpa handles version numbers can break dependency management for other packages. Don't get me wrong, this is not a criticism to Melpa and I don't disagree with the way it's done. I love Melpa and have several other packages on it, I just prefer not to put there a package that's already available on Gnu Elpa. 

Still, like I said, you're free to fork spinner and host it on Melpa if it's more convenient to you, I just ask that you change the package name to avoid dependency issues for other people.

**Comment by brotzeit** [comment]
@Malabarba I will try to find another solution. Thanks for the reply.

**Comment by riscy** [comment]
Thanks all!

**Pull request closed without merging**
