### PR TITLE
Add recipe for abgaben.el

### PR DESCRIPTION
**Pull request by akoehn**
### Brief summary of what the package does

abgaben.el helps with correcting and grading assignments you receive by mail.
It automates saving attachments, linking them in org-mode files and composing replies
once you are done annotating the files (probably using pdf-tools).

### Direct link to the package repository

https://gitlab.com/akoehn/abgaben

### Your association with the package

I'm the author of this package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
The package link is giving me a 404. I can't find the repository on your profile either. Did you delete it or make it private?

**Comment by akoehn** [comment]
whoops, wrote github instead of gitlab...  Fixed.

**Comment by Alexander-Miller** [comment]
* `(defcustom abgaben-root-folder "/home/arne/lehre/2017-gwv/abgaben/` - that should be set to some sane default, like $HOME/abgaben. Same for abgaben-org-file
 * Too much German in the code base. Not just the customization vars, but also text being inserted, like line 261.
 * Looks like you're using mu4e code. If so you should add it as a dependency and require it.
 * The workflow looks fairly nontrivial. A nicely formatted readme with pictures and examples is much more publikumswirksam than just the comment header.

**Comment by akoehn** [comment]
Thanks for the reply, I'll look into those parts.  I forgot that my personal defaults are still in there.

mu4e is not a package; how should I add a dependency?

I'm working on a readme with gifs etc.

**Comment by Alexander-Miller** [comment]
I'm asking about mu4e because I see you use functions `mu4e~view-get-attach`. and `mu4e-view-save-attachment-single`. Where are they defined?

**Comment by akoehn** [comment]
They are part of mu4e, but mu4e is not installable via package.el.  I can add a `(require 'mu4e)` (and have done so), but can't add mu4e to the dependency list of my package.

Other packages extending mu4e also don't depend on mu4e.

**Comment by Alexander-Miller** [comment]
Ah, I didn't know that mu4e is not on melpa. In that case all you need to do is `require` it.

**Comment by akoehn** [comment]
I have updated the code base:

 - generic defaults for defvars
 - removed German strings
 - `(require 'mu4e)`

I'll add a README later, as time permits.

**Comment by akoehn** [comment]
There is now a README with videos explaining the workflow.

**Comment by purcell** [comment]
Thanks! Quick feedback:
- `emacs` isn't a great parent group for the `defgroup`. Maybe `applications` or `comm`?
- Typo: `worklfow`
- `completing-read` prompt strings should end with a space
- I think the correct English translation of Abgabe would be "submission". While I support the name of the package overall, I would advise using "submission" in symbol names, apart from the prefix -- e.g. `abgaben-save-abgabe` would be `abgaben-save-submission`, `abgaben--construct-abgabenbody` would be `abgaben--construct-submission-body` etc.

Hope that helps!

**Comment by purcell** [comment]
Also, please move those lonely `)` where they belong, with their friends on the lines above. :-)

**Comment by akoehn** [comment]
@purcell, thanks for your remarks! I've updated the package accordingly.

**Comment by purcell** [comment]
Awesome - merged now! Welcome to MELPA. :-)

**Pull request merged**
