### PR TITLE
Add recipe for counsel-toki

### PR DESCRIPTION
**Pull request by emiflake**
### Brief summary of what the package does

This package exposes a counsel search through the toki pona dictionary.

### Direct link to the package repository

https://github.com/emiflake/counsel-toki

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  This looks good to go, but a couple comments:

- `We check here because not all users may have org-mode available` -- I think this will never be true especially with a dependency on emacs 25.1 as you declare.  Users will *always* have org-mode available, so this code will always run
- counsel-toki.el#L49: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`

**Comment by emiflake** [comment]
Thanks for the review. I will fix this tomorrow!

**Comment by riscy** [comment]
> The formatting after removing tab indentation is a little peculiar but I'll likely fix that later this week.

I should mention this is just a consideration for you.  No big deal.  The reason I have been bringing it up recently is that some authors may be unaware they're mixing tabs and spaces.   Meanwhile languages like Go that actually enforce tabs are ushering us into a world where people actually `setq tab-width` to something obscene like 4.

**Comment by riscy** [comment]
I'm taking a deeper look at the code and I just noticed:

```elisp
(defvar counsel-toki--data
  nil
  "The parsed word data as found on `https://linku.la/jasima/data.json'.")

(request "https://linku.la/jasima/data.json"
  :parser 'json-read
  :success (cl-function
             (lambda (&key data &allow-other-keys)
               (setq counsel-toki--data data))))
```

We should rewrite this - whenever someone starts up Emacs, they will be reaching out across their network to download 1M, every single time.  If they aren't connected to the internet, this will throw an error and stop them from starting Emacs entirely.  And I think it's polite to let the user know when you're going to run out and fetch some data with a `y-or-n` prompt or similar.

I think it's still fine to call out for the json, but you can add a getter function that checks whether is nil, and then asks the user if they want to run the download.

**Comment by emiflake** [comment]
> I think it's still fine to call out for the json, but you can add a getter function that checks whether is nil, and then asks the user if they want to run the download.

Good point! I've made it prompt the user for permission, it should now work a little more transparently :)

**Comment by riscy** [comment]
Thank you!  Merging this -- and welcome to MELPA. :)

**Pull request merged**
