### PR TITLE
Add adaptative-theme package

### PR DESCRIPTION
**Pull request by alvarocsm91**
### Brief summary of what the package does

Add adaptative-theme package with different functions to reload themes dark and light depending on the hour or location

### Direct link to the package repository

https://github.com/alvarocsm91/adaptative-theme

### Your association with the package

An enthusiastic emacs user, author and mantainer 

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by jcs090218** [comment]
I think the package link support to point to here? 

https://github.com/alvarocsm91/adaptative-theme

**Comment by tarsius** [comment]
You must drop `:url` (it causes an error) and you most likely should also drop `:branch` and `:commit`. Please look at the documentation for why. If you actually want to use `:commit` for some reason, then we would like you to explain why that is so.

**Comment by tarsius** [comment]
I am afraid we won't be able to add this to Melpa any time soon. You also ignored *many* conventions regarding the library header (there should be one :grin:), closing parens (not on separate lines), symbol names (library prefix) etc.

**Comment by riscy** [comment]
Here's a quick pass -- it's true there is some work to do here, so I'll mark as awaiting-upstream, but feel free to ping if you have questions later on (or reach out to the community on reddit or stackexchange etc.)

### adaptative-theme.el ###

byte-compile (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
adaptative-theme.el:211:108:Warning: assignment to free variable
    `am-hour-init'
adaptative-theme.el:211:148:Warning: assignment to free variable `am-min-init'
adaptative-theme.el:211:186:Warning: assignment to free variable `am-sec-init'
adaptative-theme.el:214:128:Warning: assignment to free variable
    `pm-hour-init'
adaptative-theme.el:214:167:Warning: assignment to free variable `pm-min-init'
adaptative-theme.el:214:205:Warning: assignment to free variable `pm-sec-init'
adaptative-theme.el:55:34:Warning: assignment to free variable `init-time'
adaptative-theme.el:58:33:Warning: reference to free variable `init-time'
adaptative-theme.el:56:41:Warning: assignment to free variable `init-hour-str'
adaptative-theme.el:62:23:Warning: reference to free variable `init-hour-str'
adaptative-theme.el:71:10:Warning: assignment to free variable `init-hour-int'
adaptative-theme.el:59:40:Warning: assignment to free variable `init-min-str'
adaptative-theme.el:59:40:Warning: reference to free variable `init-min-str'
adaptative-theme.el:77:16:Warning: assignment to free variable `init-min-int'
adaptative-theme.el:62:40:Warning: assignment to free variable `init-sec-str'
adaptative-theme.el:62:40:Warning: reference to free variable `init-sec-str'
adaptative-theme.el:81:18:Warning: assignment to free variable `init-sec-int'
adaptative-theme.el:121:7:Warning: assignment to free variable `is-day'
adaptative-theme.el:213:11:Warning: assignment to free variable `is-morning'
adaptative-theme.el:190:13:Warning: assignment to free variable `is-night'
adaptative-theme.el:192:38:Warning: reference to free variable `init-hour-int'
adaptative-theme.el:193:38:Warning: reference to free variable `init-min-int'
adaptative-theme.el:194:35:Warning: reference to free variable `init-sec-int'
adaptative-theme.el:194:35:Warning: reference to free variable `is-day'
adaptative-theme.el:126:28:Warning: reference to free variable `is-morning'
adaptative-theme.el:172:24:Warning: assignment to free variable `pm-hour-str'
adaptative-theme.el:172:40:Warning: assignment to free variable `pm-min-str'
adaptative-theme.el:172:40:Warning: reference to free variable `pm-hour-str'
adaptative-theme.el:172:40:Warning: reference to free variable `pm-min-str'
adaptative-theme.el:211:33:Warning: assignment to free variable `pm-str'
adaptative-theme.el:187:24:Warning: assignment to free variable `am-hour-str'
adaptative-theme.el:187:40:Warning: assignment to free variable `am-min-str'
adaptative-theme.el:187:40:Warning: reference to free variable `am-hour-str'
adaptative-theme.el:187:40:Warning: reference to free variable `am-min-str'
adaptative-theme.el:195:15:Warning: assignment to free variable `am-str'
adaptative-theme.el:214:143:Warning: reference to free variable `is-night'
adaptative-theme.el:195:48:Warning: assignment to free variable `am-str-int'
adaptative-theme.el:195:48:Warning: reference to free variable `am-str-int'
adaptative-theme.el:214:21:Warning: reference to free variable `pm-str'
adaptative-theme.el:214:108:Warning: reference to free variable `am-hour-init'
adaptative-theme.el:214:108:Warning: reference to free variable `pm-hour-init'
adaptative-theme.el:214:148:Warning: reference to free variable `am-min-init'
adaptative-theme.el:214:148:Warning: reference to free variable `pm-min-init'
adaptative-theme.el:214:186:Warning: reference to free variable `am-sec-init'
adaptative-theme.el:214:186:Warning: reference to free variable `pm-sec-init'
adaptative-theme.el:214:186:Warning: assignment to free variable `pm-timer'
adaptative-theme.el:214:186:Warning: reference to free variable `am-str'
adaptative-theme.el:214:186:Warning: assignment to free variable `am-timer'
In adaptative-theme-location:
adaptative-theme.el:242:13:Warning: assignment to free variable
    `internet-external-host'
adaptative-theme.el:243:75:Warning: reference to free variable
    `internet-external-host'
adaptative-theme.el:245:11:Warning: assignment to free variable
    `is-internet-up'
adaptative-theme.el:245:11:Warning: reference to free variable
    `is-internet-up'
adaptative-theme.el:248:10:Warning: adaptative-theme called with 1 argument,
    but requires 2-8
adaptative-theme.el:248:38:Warning: reference to free variable `light-theme'
adaptative-theme.el:258:7:Warning: assignment to free variable `url'
adaptative-theme.el:268:28:Warning: reference to free variable `url'
adaptative-theme.el:269:43:Warning: assignment to free variable `web_to_scrap'
adaptative-theme.el:269:20:Warning: reference to free variable `web_to_scrap'
adaptative-theme.el:283:35:Warning: assignment to free variable `webDataHtml'
adaptative-theme.el:283:21:Warning: assignment to free variable
    `webRegexModel'
adaptative-theme.el:299:16:Warning: reference to free variable `webRegexModel'
adaptative-theme.el:287:18:Warning: reference to free variable `webDataHtml'
adaptative-theme.el:287:30:Warning: assignment to free variable
    `daylight-regex'
adaptative-theme.el:287:48:Warning: reference to free variable
    `daylight-regex'
adaptative-theme.el:293:44:Warning: assignment to free variable `subWebStr'
adaptative-theme.el:299:29:Warning: assignment to free variable
    `timeGroupRegex'
adaptative-theme.el:313:33:Warning: reference to free variable
    `timeGroupRegex'
adaptative-theme.el:302:25:Warning: reference to free variable `subWebStr'
adaptative-theme.el:302:35:Warning: assignment to free variable `timeStr'
adaptative-theme.el:302:46:Warning: reference to free variable `timeStr'
adaptative-theme.el:308:48:Warning: assignment to free variable `amTime'
adaptative-theme.el:323:48:Warning: assignment to free variable `pmTime'
adaptative-theme.el:314:27:Warning: reference to free variable `amTime'
adaptative-theme.el:314:37:Warning: assignment to free variable `amSeparator'
adaptative-theme.el:314:55:Warning: reference to free variable `amSeparator'
adaptative-theme.el:310:35:Warning: assignment to free variable `amHourStr'
adaptative-theme.el:320:18:Warning: reference to free variable `amHourStr'
adaptative-theme.el:328:42:Warning: assignment to free variable `amHourInt'
adaptative-theme.el:315:34:Warning: assignment to free variable `amMinStr'
adaptative-theme.el:325:17:Warning: reference to free variable `amMinStr'
adaptative-theme.el:328:62:Warning: assignment to free variable `amMinInt'
adaptative-theme.el:324:27:Warning: reference to free variable `pmTime'
adaptative-theme.el:324:37:Warning: assignment to free variable `pmSeparator'
adaptative-theme.el:324:55:Warning: reference to free variable `pmSeparator'
adaptative-theme.el:320:35:Warning: assignment to free variable `pmHourStr'
adaptative-theme.el:320:35:Warning: reference to free variable `pmHourStr'
adaptative-theme.el:328:52:Warning: assignment to free variable `pmHourInt'
adaptative-theme.el:325:34:Warning: assignment to free variable `pmMinStr'
adaptative-theme.el:325:34:Warning: reference to free variable `pmMinStr'
adaptative-theme.el:328:71:Warning: assignment to free variable `pmMinInt'
adaptative-theme.el:328:19:Warning: reference to free variable `amHourInt'
adaptative-theme.el:328:19:Warning: reference to free variable `pmHourInt'
adaptative-theme.el:328:19:Warning: reference to free variable `amMinInt'
adaptative-theme.el:328:19:Warning: reference to free variable `pmMinInt'
In adaptative-theme-autolocation:
adaptative-theme.el:349:13:Warning: assignment to free variable
    `internet-external-host'
adaptative-theme.el:350:75:Warning: reference to free variable
    `internet-external-host'
adaptative-theme.el:352:11:Warning: assignment to free variable
    `is-internet-up'
adaptative-theme.el:352:11:Warning: reference to free variable
    `is-internet-up'
adaptative-theme.el:355:10:Warning: adaptative-theme called with 1 argument,
    but requires 2-8
adaptative-theme.el:365:9:Warning: assignment to free variable `url-location'
adaptative-theme.el:368:45:Warning: reference to free variable `url-location'
adaptative-theme.el:378:41:Warning: assignment to free variable `webDataHtml'
adaptative-theme.el:381:20:Warning: reference to free variable `webDataHtml'
adaptative-theme.el:381:32:Warning: assignment to free variable
    `location-regex'
adaptative-theme.el:381:50:Warning: reference to free variable
    `location-regex'
adaptative-theme.el:385:37:Warning: assignment to free variable `subLocStr'
adaptative-theme.el:402:27:Warning: reference to free variable `subLocStr'
adaptative-theme.el:408:33:Warning: assignment to free variable `init-regex'
adaptative-theme.el:408:50:Warning: assignment to free variable `end-regex'
adaptative-theme.el:408:20:Warning: reference to free variable `init-regex'
adaptative-theme.el:408:20:Warning: reference to free variable `end-regex'
adaptative-theme.el:411:51:Warning: assignment to free variable `myCountryLoc'
adaptative-theme.el:411:64:Warning: assignment to free variable `myCityLoc'
adaptative-theme.el:411:2:Warning: reference to free variable `myCountryLoc'
adaptative-theme.el:411:2:Warning: reference to free variable `myCityLoc'
In end of data:
adaptative-theme.el:413:1:Warning: the following functions are not known to be
    defined: dark-theme, return, org-web-tools--get-url
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
adaptative-theme.el:0: The first line should be of the form: ";;; package --- Summary"
Warning (emacs): 
adaptative-theme.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
adaptative-theme.el:2: You should have a section marked ";;; Code:"
Warning (emacs): 
adaptative-theme.el:412: The footer should be: (provide 'adaptative-theme)\n;;; adaptative-theme.el ends here
Warning (emacs): 
adaptative-theme.el:4: Documentation strings should not start or end with whitespace
Warning (emacs): 
adaptative-theme.el:4: Argument `light-theme' should appear (as LIGHT-THEME) in the doc string
Warning (emacs): 
adaptative-theme.el:6: Name emacs should appear capitalized as Emacs
Warning (emacs): 
adaptative-theme.el:223: Documentation strings should not start or end with whitespace
Warning (emacs): 
adaptative-theme.el:223: Some lines are over 80 columns wide
Warning (emacs): 
adaptative-theme.el:223: Argument `ligth-theme' should appear (as LIGTH-THEME) in the doc string
Warning (emacs): 
adaptative-theme.el:225: Name emacs should appear capitalized as Emacs
Warning (emacs): 
adaptative-theme.el:332: Second line should not have indentation
Warning (emacs): 
adaptative-theme.el:332: Documentation strings should not start or end with whitespace
Warning (emacs): 
adaptative-theme.el:332: Some lines are over 80 columns wide
Warning (emacs): 
adaptative-theme.el:332: Argument `light-theme' should appear (as LIGHT-THEME) in the doc string
Warning (emacs): 
adaptative-theme.el:334: Name emacs should appear capitalized as Emacs
```

package-lint (using version 20200419.406):
```
27 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a ;;; Commentary section.
1:0: error: Package should have a Homepage or URL header.
1:0: error: package.el cannot parse this buffer: Package lacks a file header
86:18: warning: Closing parens should not be wrapped onto new lines.
87:10: warning: Closing parens should not be wrapped onto new lines.
88:6: warning: Closing parens should not be wrapped onto new lines.
111:10: warning: Closing parens should not be wrapped onto new lines.
112:6: warning: Closing parens should not be wrapped onto new lines.
113:4: warning: Closing parens should not be wrapped onto new lines.
142:14: warning: Closing parens should not be wrapped onto new lines.
146:8: warning: Closing parens should not be wrapped onto new lines.
153:12: warning: Closing parens should not be wrapped onto new lines.
156:6: warning: Closing parens should not be wrapped onto new lines.
157:4: warning: Closing parens should not be wrapped onto new lines.
163:4: warning: Closing parens should not be wrapped onto new lines.
169:4: warning: Closing parens should not be wrapped onto new lines.
178:4: warning: Closing parens should not be wrapped onto new lines.
184:4: warning: Closing parens should not be wrapped onto new lines.
196:4: warning: Closing parens should not be wrapped onto new lines.
203:6: warning: Closing parens should not be wrapped onto new lines.
206:4: warning: Closing parens should not be wrapped onto new lines.
207:2: warning: Closing parens should not be wrapped onto new lines.
219:4: warning: Closing parens should not be wrapped onto new lines.
251:4: warning: Closing parens should not be wrapped onto new lines.
358:4: warning: Closing parens should not be wrapped onto new lines.
412:0: warning: Closing parens should not be wrapped onto new lines.
```


### Loadability ###

Verifying ability to #'load each file:
```
Loading adaptative-theme.el
Done.
```

### Package ###

- GitHub API found `GNU Lesser General Public License v3.0`
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.org/using-spdx-license-identifier) to adaptative-theme.el
- pkg/adaptative-theme.el (unknown license) -- (no header)


When you're ready, I would recommend a recipe of:
```elisp
(adaptative-theme :fetcher github :repo "alvarocsm91/adaptative-theme")
```
to begin with.

**Comment by alvarocsm91** [comment]
I change the repository files and reopen other pull request

**Comment by tarsius** [comment]
Next time please just update the existing pull-request instead.

**Pull request closed without merging**
