### PR TITLE
Add recipe for ox-hugo

### PR DESCRIPTION
**Pull request by kaushalmodi**
### Brief summary of what the package does

This library implements a Markdown back-end compatible with the
Hugo static site generator (https://gohugo.io/) for Org exporter.
This includes the generation of the Hugo post front-matter in TOML
or YAML.

### Direct link to the package repository

https://github.com/kaushalmodi/ox-hugo

### Your association with the package

Author

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!
- The `:files` spec is unnecessary here, I think.
- `ox-blackfriday` looks like it should be a separate package, maybe? Generally all files in a package would have a common name prefix.

**Comment by kaushalmodi** [comment]
The `ox-blackfriday` is current kept as a "silent" exporter. So it's bindings will not show up the Org Exporter dialog, and unnecessarily clutter the interface. If there's demand for standalone `ox-blackfriday` in future, I can package is that way. But right now, it's almost exclusively used by Hugo. 

I'll remove the `:files` spec. I was just being cautious that the `.dir-locals.el` does not get included.

**Comment by kaushalmodi** [comment]
> ox-blackfriday looks like it should be a separate package, maybe? Generally all files in a package would have a common name prefix.

At present, `ox-blackfriday` is kept as an internal separate library, and so it has its own namespace. Is that a big concern. If I package it separately, I would need to expose it's bindings in the Org Exporter menu, which will introduce clutter, as no one would use them.

**Comment by kaushalmodi** [comment]
> The :files spec is unnecessary here, I think.

I have force pushed an update to this PR.. removing the `:files`.. they were not needed as you said.

Is the other point you raised a blocker to this PR?

**Comment by purcell** [comment]
Should be fine, but definitely consider extracting `ox-blackfriday` as a separate package at some point. :-)

**Comment by kaushalmodi** [comment]
> consider extracting ox-blackfriday as a separate package at some point. :-)

I'll definitely do that when there's need. The package is almost ready to be published if anyone ever needed standalone `ox-blackfriday`.. I'd just need to uncomment [these lines][1]. 

And thanks for merging this recipe.. my first major package :D

[1]: https://github.com/kaushalmodi/ox-hugo/blob/69a6001b00b6fe35404c4220e1e476724719215f/ox-blackfriday.el#L51-L60

**Pull request merged**
