### PR TITLE
Add recipe for dir-config

### PR DESCRIPTION
**Pull request by jamescherti**
### Brief summary of what the package does

The `dir-config` Emacs package automatically loads and evaluates Elisp code from a `.dir-config.el` file found in the buffer's current directory or its closest parent directory. This enables Emacs to adjust settings or execute functions specific to the directory structure of each buffer.

For instance, you can use the `dir-config` package to:
- **Configure project-specific settings**: Automatically set up environment variables, keybindings, or modes unique to each project.
- **Apply directory-specific customizations**: Set specific behaviors or preferences for files in different directories, such as enabling or disabling certain minor modes based on security considerations. For example, you might disable linters that execute code in directories where you handle untrusted code.
- **Manage multiple environments**: Switch between different coding environments or workflows by loading environment-specific configurations.

Features:
- Automatic Configuration Discovery: Searches for and loads `.dir-config.el` file from the directory of the current buffer or its parent directories.
- Selective Directory Loading: Restricts the loading of configuration files to directories listed in the variable `dir-config-allowed-directories`, ensuring control over where configuration files are sourced from.
- The `global-dir-config-mode` mode: Automatically loads the `.dir-config.el` file whenever a file or directory is opened, leveraging the `find-file-hook` to ensure that the dir configurations are applied.
- The `.dir-config.el` file name can be changed by modifying the `dir-config-file-names` defcustom.

### Direct link to the package repository

https://github.com/jamescherti/dir-config.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by mattiasb** [comment]
This question is bound to come up so I might as well ask: How does this compare to .dir-locals.el files?

**Comment by jamescherti** [comment]
Hello @mattiasb ,

Here are the differences between `.dir-locals.el` (built-in) and `.dir-config.el` (this package):

- `.dir-locals.el` (built-in): 
  - Primarily used for setting per-directory local variables and customizing buffer-specific behavior.

- `.dir-config.el` (The `dir-config` package):
  - Provides more extensive capabilities by loading and evaluating Emacs Lisp code for tasks such as environment configuration, keybindings, and other complex setup processes.
  - Better suited for more complex, project-specific setups where additional customization and dynamic behavior are required.

If the user’s needs primarily involve configuring Emacs variables, the built-in `.dir-locals.el` is sufficient. For more advanced, project-specific configurations that include code execution and comprehensive environment management, `.dir-config.el` files offer more flexibility and control.

**Comment by riscy** [comment]
Thanks for this.  I think the rationale here is sound, and this is a good innovation.

I'd recommend seeing if you can work "dir-locals" into your summary line, however, because I think it's a valuable search keyword for this package, but this isn't a blocker.  Example: "dir-config.el: Flexible dir-locals alternative".

**Comment by jamescherti** [comment]
Hello @riscy,
Thank you for your suggestion and the quick merge! I updated the summary line to include: "Flexible dir-locals alternative".

**Pull request merged**
