### PR TITLE
add recipe org-seek

### PR DESCRIPTION
**Pull request by stardiviner**
### Brief summary of what the package does

Search Org-mode files in a directory with search engines.

### Direct link to the package repository

https://github.com/stardiviner/org-searching.el

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by stardiviner** [comment]
MELPA requirements fixed https://github.com/stardiviner/org-searching.el/pull/1

**Comment by syohex** [comment]
- https://github.com/stardiviner/org-searching.el/blob/master/org-searching.el#L2 makes no sense. Buffer local variable should be defined at first line or `Local Variables` section
- I suppose `Search Engine` stands for `Web search engine` rather than grep like tools in general.
- `org-search` prefix is used by org-mode. I suppose this package name confuse with them

**Comment by stardiviner** [comment]
- I removed second line
- renamed `org-searching` to `org-seek`
- renamed `search engine` to `search tool`

**Comment by syohex** [comment]
Could you change PR title too ?

**Comment by stardiviner** [comment]
@syohex renamed PR title, but don't know how to change branch name. Should I rename the branch name?

**Comment by purcell** [comment]
No need to rename the branch.

Re. the code:
- Why not default `org-seek-org-root-path` to `org-directory`?
- You might like to mention "ag" in the package description line. You can remove it later if you eventually support other search tools.

Merging now, in any case.

**Pull request merged**
