### PR TITLE
Add simple-bookmarks recipe

### PR DESCRIPTION
**Pull request by jtkDvlp**
A smart enhancement for emacs providing a simple but convenient interface to your recently and often used bookmarks / functioncalls.

https://github.com/jtkDvlp/simple-bookmarks/

I am the author and maintainer of the package.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- Don't use `sb/` as a prefix. There are only 26x26 two-character prefixes available, which is fewer than there are packages on MELPA alone. Just use `simple-bookmarks-`, as per the [elisp conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html). (Same applies to `sbf/`, `sbi/` etc -- just use the same prefix throughout.)
- `Emacs bookmark / functioncall manager` can just be `Bookmark / functioncall manager`, since all emacs packages are for Emacs. Same goes for `for emacs` in the commentary. :-)
- Use `defcustom` to declare the `simple-bookmarks` custom group, and to place it logically within the standard customisation hierarchy

Hope that helps!

**Comment by jtkDvlp** [comment]
Thanks for feedback.

> Don't use sb/ as a prefix. There are only 26x26 two-character prefixes available, which is fewer than there are packages on MELPA alone. Just use simple-bookmarks-, as per the elisp conventions. (Same applies to sbf/, sbi/ etc -- just use the same prefix throughout.)

Got it

> Emacs bookmark / functioncall manager can just be Bookmark / functioncall manager, since all emacs packages are for Emacs. Same goes for for emacs in the commentary. :-)

Also got it XD

> Use defcustom to declare the simple-bookmarks custom group, and to place it logically within the standard customisation hierarchy

Don´t got it. I already used the `defcustom` but only for one customizable var all the other vars should not be customized. Isn´t it right this way?

**Comment by purcell** [comment]
> Don´t got it. I already used the defcustom but only for one customizable var all the other vars should not be customized. Isn´t it right this way?

Sorry, my mistake: I meant to write `defgroup`, not `defcustom`!

**Comment by jtkDvlp** [comment]
Ok, thanks. Now there is a group in v1.6.

**Comment by purcell** [comment]
Great - merged! :-)

**Pull request merged**
