### PR TITLE
Add modelica mode

### PR DESCRIPTION
**Pull request by rudi**
### Brief summary of what the package does

Major mode for the Modelica language

### Direct link to the package repository

https://github.com/modelica-tools/modelica-mode

### Your association with the package

Co-maintainer

### Relevant communications with the upstream package maintainer

Submitted a series of pull requests that hopefully bring it up to current Emacs conventions

Added github ci support that should keep us honest ;)

Was added as maintainer after release of 2.0.0

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by rudi** [comment]
Upstream maintainer is @dietmarw

**Comment by riscy** [comment]
Thanks for this.  Great documentation in the Commentary :)  Here's a quick first pass --

`modelica-mode.el` with checkdoc 0.6.2:
```
modelica-mode.el:1159: First line is not a complete sentence
```
These are always annoying, but they help with the output of `M-x apropos`; I'd recommend rephrasing to something like
```elisp
  "Overlay value when point is in an overlay with property PROP.
If point is not in such an overlay, return nil."
```

`modelica-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- modelica-mode.el#L363: It's safer to sharp-quote function names; use `#'`
- modelica-mode.el#L931: Could this point/point-max comparison use `eobp`?
- modelica-mode.el#L941: Could this point/point-min comparison use `bobp`?
- modelica-mode.el#L958: Could this point/point-min comparison use `bobp`?
- modelica-mode.el#L434: `concat` may be unneeded; `insert` can take multiple arguments
- modelica-mode.el#L889: `concat` may be unneeded; `insert` can take multiple arguments
```

**Comment by rudi** [comment]
> Thanks for this. Great documentation in the Commentary :) Here's a quick first pass --

Thanks for the review!  Your comments are now fixed upstream.

**Comment by riscy** [comment]
Thank you!

**Pull request merged**
