### PR TITLE
html-stable/updates.rss.erb: update melpa stable links

### PR DESCRIPTION
**Pull request by xgqt**
Closes: https://github.com/melpa/melpa/issues/8275
Signed-off-by: Maciej Barć <xgqt@gentoo.org>

### CODE REVIEW

**Comment by xgqt** [comment]
Basically a copy of `html/updates.rss.erb` but this time with proper name and base URL.

**Comment by riscy** [comment]
@milkypostman I think this one is beyond my reckoning. :)

**Comment by milkypostman** [comment]
Can't we do something that just detects the correct URL to use?

I guess I don't know much about `erb` anymore.

**Comment by milkypostman** [comment]
@xgqt I went ahead and made the change in #8329. Would you mind taking a look and reviewing?

**Comment by xgqt** [comment]
that's a lot better

**Comment by riscy** [comment]
@xgqt Thank you for this PR - do you think the problem has been resolved in the other one, and we can close this?

**Comment by xgqt** [comment]
> @xgqt Thank you for this PR - do you think the problem has been resolved in the other one, and we can close this?

Yes, this is resolved. Thanks.

**Pull request closed without merging**
