### PR TITLE
Add recipe for consult-ls-git

### PR DESCRIPTION
**Pull request by rcj**
### Brief summary of what the package does

consult extension for git

### Direct link to the package repository

https://github.com/rcj/consult-ls-git/

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by minad** [comment]
Hi, why not call your package `consult-git`? There is a small overlap with `consult-git-grep` but I don't plan to add more git functionality to Consult itself.

**Comment by rcj** [comment]
Similar reason, I don't intend to add additional git functionality besides listing files/stashes/etc. I thought consult-git could imply a much broader feature set.

**Comment by minad** [comment]
Makes sense then. Maybe someone will create a broader `consult-git` package at some point which will then subsume the functionality. I didn't add more git functionality to Consult since vc and magit seem sufficient. I assume you need consult-ls-git to replace some counsel commands in your workflow?

**Comment by rcj** [comment]
I actually never used counsel. I had similar custom functions before as I work on a large repo with 100k+ files and I often want to open a specific one where I know parts of the name but not necessarily the exact location. I had bad experience with projectile in the past wrt. performance on such large projects. Maybe project.el would work better, haven't tried it yet.

**Comment by riscy** [comment]
Thanks for this!

Thanks for your close adherence to the checklist.  Have you tested how this package works with unusual directories (e.g. directories whose names contain shell control characters or spaces or such things)?  I worry that `consult-ls-git--project-root` -- since no call to `shell-quote-argument` is made on it -- could cause issues when being passed in unescaped to `shell-command-to-string`.

**Comment by rcj** [comment]
No I didn't, but it would be a problem indeed, thanks. I added `shell-quote-argument` for the project root arguments.

**Comment by minad** [comment]
@yadex205 I stumbled over your package incidentally when I added a link to your consult-ag package to the Consult README (https://github.com/minad/consult/commit/ed44a20c23b7ee1b78a8cd0f56b005c880fc4c29).

**Comment by yadex205** [comment]
@rcj @minad Thanks for mention. Yes I recently (maybe at the same time) created `consult-git-ls`, but it just satisfy my purpose and is not enough to be published to MELPA.

> It seems `consult-ls-git` currently doesn't support listing only a subtree of a repository compared to `consult-git-ls`.

Sorry it's an unexpected behaviors..... (Of course I want to search entire of a repo) It seems `consult-ls-git` is more stable and satisfy many people's purpose (including me).

So it would be better `consult-ls-git` will be published as is. Also if it's better, I can rename `consult-git-ls` or archive the repo.

**Comment by minad** [comment]
On 4/26/22 07:01, Kanon Kakuno wrote:
> So it would be better `consult-ls-git` will be published as is. Also if it's better, I can rename `consult-git-ls` or archive the repo.

Maybe just create a link to consult-ls-git, mentioning that this package
is more developed and available on MELPA?

**Comment by yadex205** [comment]
@minad Thank you, I'll keep my repo and add link to `consult-ls-git` with some comments. 

@riscy @rcj Please proceed if there's no problem.

**Comment by riscy** [comment]
Huge thanks to everyone above for helping us arrive at this point.  I'm super thankful to see your input on consult-related packages @minad.  This looks good to merge.

@rcj there is a very minor checkdoc and a couple other notes that I'll leave fyi:
- consult-ls-git.el:159: Argument `command' should appear (as COMMAND) in the doc string
- `(error "Not a git repository")` should probably be a `user-error` rather than an `error`

**Comment by rcj** [comment]
Thanks a lot to everyone!

**Pull request merged**
