### PR TITLE
Add recipe for completing-read-cider

### PR DESCRIPTION
**Pull request by enzuru**
### Brief summary of what the package does

This package lets you search through Clojure symbols defined in CIDER using Emacs' built-in competing-read function.

### Direct link to the package repository

https://github.com/enzuru/completing-read-cider

### Your association with the package

I am the original author and current maintainer.

### Relevant communications with the upstream package maintainer

**None needed*

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by minad** [comment]
Hi, why not add this and the related functionality in #8849 and #8851 directly to the respective upstream packages?

**Comment by enzuru** [comment]
@minad let me reach out to the projects and ask them. Will tag you once I have an answer.

**Comment by riscy** [comment]
Thanks for this one too.  My feeling is similar to as I wrote in https://github.com/melpa/melpa/pull/8849, as well as what the CIDER folks wrote to you, i.e. that landing this in documentation could be the best way.

Alternatively, an existing package in MELPA that you might consider joining forces with may be https://melpa.org/#/ac-cider -- although I'm not familiar with this project, and it hasn't seen an update in a while.

**Comment by enzuru** [comment]
@riscy will go ahead and either submit this to documentation or write a blog post -- thank you

**Comment by riscy** [comment]
Thank you for your understanding. :)

**Pull request closed without merging**
