### PR TITLE
add tangonov-theme

### PR DESCRIPTION
**Pull request by trev-dev**
### Brief summary of what the package does

It's a dark theme for Emacs :)

### Direct link to the package repository

https://github.com/trev-dev/tangonov-theme

### Your association with the package

I am the creator/matintainor

### Relevant communications with the upstream package maintainer

**None Needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by progfolio** [comment]
At a glance it looks like your package defines functions without your package prefix.
e.g. color-blend should be tangonov-color-blend or tangonov--color-blend.

**Comment by trev-dev** [comment]
Yeah, I though that might come up. For the sake of being terse, could I use a more ambiguous prefix such as `tn-blend` or `tn/darken`?

**Comment by progfolio** [comment]
Elisp convention is to use hyphens to delimit parts of symbols.
I would advise against using an abbreviated faux namespace.
Using `tangonov-` as your prefix makes it clear to users that a symbol belongs to your package.
It looks like you only have a handful of symbols with this package, too.

**Comment by riscy** [comment]
It looks like the namespacing issue was resolved.  A couple more on my end:

- Avoid specifying `:branch` except in unusual cases (MELPA prefers to use the default branch whenever possible)
- Prefer equivalent recipe: `(tangonov-theme :repo "trev-dev/tangonov-theme" :fetcher github :branch "dist")` or better yet `(tangonov-theme :repo "trev-dev/tangonov-theme" :fetcher github)`
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

**Comment by trev-dev** [comment]
Thanks for your help! I have implemented your feedback. Let me know if there is anything else that needs doing.

**Comment by riscy** [comment]
Looks good. Thanks!

**Pull request merged**
