### PR TITLE
Add jsdoc recipe

### PR DESCRIPTION
**Pull request by isamert**
### Brief summary of what the package does

A simple package to generate [JSDoc-style](https://jsdoc.app/about-getting-started.html) comments. It tries to infer as much as it can while generating the comment for the user.

### Direct link to the package repository

https://github.com/isamert/jsdoc.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`jsdoc.el` with checkdoc 0.6.2:
```
jsdoc.el:69: All variables and subroutines might as well have a documentation string
jsdoc.el:87: All variables and subroutines might as well have a documentation string
jsdoc.el:95: All variables and subroutines might as well have a documentation string
jsdoc.el:104: All variables and subroutines might as well have a documentation string
jsdoc.el:112: All variables and subroutines might as well have a documentation string
jsdoc.el:116: All variables and subroutines might as well have a documentation string
jsdoc.el:120: All variables and subroutines might as well have a documentation string
jsdoc.el:157: All variables and subroutines might as well have a documentation string
jsdoc.el:190: All variables and subroutines might as well have a documentation string
jsdoc.el:233: All variables and subroutines might as well have a documentation string
jsdoc.el:236: All variables and subroutines might as well have a documentation string
jsdoc.el:239: All variables and subroutines might as well have a documentation string
jsdoc.el:242: All variables and subroutines might as well have a documentation string
```

`jsdoc.el` with package-lint 20221003.1636:
```
1 issue found:
9:23: warning: This makes the package uninstallable in all released Emacs versions.
```

**Comment by isamert** [comment]
Thanks for the report @riscy! If possible, I would like to keep _internal_ functions and variables undocumented. Because they tend to change and documentation starts to lag behind which causes confusion for the reader. 

About the package-lint error: Yes, this package only supports Emacs 29+ and I have no intention to support older versions (as it requires built-in tree-sitter). If it's not suitable for MELPA in this condition, we can close the PR and I can re-submit when Emacs 29 gets released.

**Comment by riscy** [comment]
> If possible, I would like to keep internal functions and variables undocumented. Because they tend to change and documentation starts to lag behind which causes confusion for the reader.

I agree with this in general, i.e. that extraneous comments adds a maintenance burden.  But this has been asked of all contributors as part of the checklist for a while now, and there are a lot of authors who had to roll up their sleeves (or roll their eyes) and document private functions to adhere to the checklist.

Nevertheless, I'll try to raise a MELPA issue about this today (feel free to do so yourself if I forget) -- since I'd rather we change policy as a result of a discussion over an issue, rather than an arbitrary exception being made in a recipe PR.

Everything else looks good. Stay tuned...

**Comment by riscy** [comment]
q.v. #8450

**Comment by riscy** [comment]
I'll merge this now, considering the above issue.

**Pull request merged**
