### PR TITLE
Llm

### PR DESCRIPTION
**Pull request by ahyatt**
These recipes are for the llm package, which is used as a library for those wanting to use llms, allowing the client (and, ultimately, the user), to switch LLMs to their preferred one.

### Brief summary of what the package does

The llm package provides `cl-defgeneric` abstract functions for clients who want to use LLMs.  The other packages, `llm-openai`, and `llm-vertex` provide two implementation of integration with two different LLM services.  Client packages can use the llm package to integrate with, and provide their users with the capability of changing the LLM used.

### Direct link to the package repository

https://github.com/ahyatt/llm

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Have you had a chance to compare this to any of the existing LLM packages out there?  (There have recently been a glut of them, albeit many of them focused on OpenAI or ChatGPT).  Let me know if you're not able to search any up for comparison.

I have made a recent change to [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#what-to-know-before-opening-a-pull-request) and I'm asking authors for one recipe per pull request, *especially* if one package is a dependency of the others.  Would you be willing to narrow this PR down to one for us to start with?

One general piece of advice I can give you across all recipe files is that MELPA wants to avoid pulling from custom branches (e.g. something like `:branch "melpa"`) whenever possible.  We'd much prefer your default branch with the recipe customized as needed.

**Comment by ahyatt** [comment]
Thanks for the reply.  Let me explain a few things.  First, this isn't similar to other packages that integrate with openai, this is a library for all those other packages, plus more to come, so they can use this instead, and the users can select the LLM backend to use.  That's the plan, at any rate.

Because of that, the core package, `llm`, is just the interface.  Clients would need to use one other supplemental package, `llm-openai`, or `llm-vertex` to do anything.  The idea is the package they are using would require `llm`, but to use it, the client has to have the right plugin.  So in this case, it isn't like other packages where you have a main package an auxiliary packages.  The `llm` package is not usable by end-users without the other package.  I can still make the change to just start with `llm`, but since it doesn't make sense without the other packages, I'd send you a pull request with the others right after that.  Let me know what you think.

And about the special branch, I agree.  I'm trying to get this included in GNU ELPA as well.  If I do, maybe we don't need it to be part of MELPA, and we can just abandon this pull request.  However, they want me to add warnings for non-free llm backends (which is all of them right now).  I've done so in the main branch, but in the MELPA branch, I'd prefer not do that (the change in behavior I haven't checked in yet, but I'll do that soon).  This is why there are different branches. 

Let me try to get clarity on whether they will ever accept this in or not to GNU ELPA.  The conversation has been dragging on, and if I just knew they wouldn't, I could just make the main branch the same as the MELPA one.

**Comment by riscy** [comment]
>  I'm trying to get this included in GNU ELPA as well. If I do, maybe we don't need it to be part of MELPA, and we can just abandon this pull.

Let us know when this decision is made and we can move ahead.

**Comment by ahyatt** [comment]
Thanks for checking back.  We've decided to include it in GNU ELPA, so I think this won't be needed.  I'll close this pull request.  If for some reason it makes sense to add this to MELPA, I'll re-open.  Thanks!

**Pull request closed without merging**
