### PR TITLE
provide function name not keybinding in contributing.org

### PR DESCRIPTION
**Pull request by mooseyboots**
`C-c C-c` in the recipe buffer doesn't do anything for me, better to name the function to run rather than a fragile keybinding.

### CODE REVIEW

**Comment by tarsius** [comment]
It would be better to determine why the key binding is fragile and to then fix that.

**Comment by tarsius** [comment]
> i understand sharing the name of the function rather than a binding to be a general recommendation in all of emacs-land, as keybindings can change with different set-ups.

Looking at https://www.gnu.org/software/emacs/manual/html_node/emacs/Moving-Point.html, for example, the convention seems to be to mention both; with a focus on the key binding, but mentioning the command for the benefit of those who use different key bindings.

So, if you don't want to put more effort into this, transposing these two pieces of information in you pull-request, would be the way to go.

> the docs don't mention the mode the recipe file should be used in. so i'm not sure how the binding is supposed to be established.

If I remember correctly, the minor mode `package-recipe-mode` is supposed to be automatically turned on, which makes the key binding available. It is unlikely that any starter-kit or such would change that binding. But it does not appear to be working. What is needed is that someone(tm) has to figure out why it is not working. I believe it is supposed to be turned on by `.dir-locals.el`. Maybe not.

Once it has been fixed, there is no need to merge this pull-request. I could of course figure out what is wrong myself, but there are many things that I know that have to be improved in Melpa, and this just never made it to the top of the list. But since you are interested in this issue, maybe you could do it?

**Comment by tarsius** [comment]
I am working on it now.

My guess as to why it doesn't currently work for you is that you answered "no" when asked whether you wanted to enable the relevant "potentially unsafe" file-local setting `(eval ....)`. I am guessing you are not the only one doing that, so we have to put in more of an effort to enable the mode, without users having to explicitly opt-in.

**Comment by mooseyboots** [comment]
from my pov, which is that of an amateur goose of a programmer and so a long way away from your pov, even if the issue gets fixed its good for people to know what commands they're running. then they can look them up, learn stuff, and so on.

re the issue, i have no `.dir-locals.el` in `.emacs.d/elpa/recipes/`. 

i can't be sure but i also have a feeling that i may have had to create that directory when i first manually built a package for submission to MELPA. is it possible for it not to be there by default?

...

i also don't have `package-recipe-mode` though i do have `package-build-mode`. 

`package-build` MELPA package is installed, and `package-recipe{-mode}.el` files are in its dir.

[i'm not sure if this info is helpful or just a way of making a fool of myself on the internet.]

**Comment by tarsius** [comment]
You can see my work so far at https://github.com/melpa/package-build/compare/package-recipe-mode?expand=1. I was interrupted by recent regressions in Emacs.

> re the issue, i have no `.dir-locals.el` in `.emacs.d/elpa/recipes/`. 

I was talking about: `/where/you/cloned/melpa/recipes/.dir-locals.el`. `~/.emacs.d/elpa/` is where `package.el` installs packages. You should clone the melpa repository to some other location.

The `C-c C-c` binding that this is about is only available if you visit, e.g., `/where/you/cloned/melpa/recipes/magit`.

**Comment by mooseyboots** [comment]
> [i'm not sure if this info is helpful or just a way of making a fool of myself on the internet.]

the penny drops! it was the latter.

sorry for wasting your time.

for me `package-build-recipes-dir` points to the other, wrong location... and it is not customized. `package-build--melpa-base` points to `.emacs.d/elpa`, as that's where `package-build` is installed. Based on this bit of the docs:

> Create a file under the directory specified by package-build-recipes-dir (default: recipes/ directory where package-build was loaded).

from that info it wasn't clear that i was storing recipes and building in the wrong place. but no one else seems to have my issue, so perhaps i'm the only one with the wrong location/set-up.

**Comment by riscy** [comment]
This also affects me, I believe because I have:
```elisp
(setq enable-local-eval nil enable-local-variables :safe)
```
in my config.  I think this'd be worth merging into the docs.

**Comment by tarsius** [comment]
> I think this'd be worth merging into the docs.

Well, I am not against mentioning the command name, but still think the key binding should come first, before the command.

Also I think https://github.com/melpa/package-build/compare/package-recipe-mode makes it unnecessary. I haven't merged that yet because I am busy with other things and also because while working on it I realized that we would make the other commands readily available, which recipe contributors are asked to run. But that is even more work, for which I don't have the time right now.

**Comment by riscy** [comment]
Agreed on both counts!  This PR seems to list the binding first, but I might take it one step further and change:
```org
or with ~C-c C-c~ (~package-build-current-recipe~) in the recipe
```
to include the M-x prefix, e.g.
```org
or with ~C-c C-c~ (~M-x package-build-current-recipe~) in the recipe
```

**Pull request merged**
