### PR TITLE
add recipe for docker-robe

### PR DESCRIPTION
**Pull request by aki2o**
### Brief summary of what the package does

A plugin lets robe.el work under docker container.

### Direct link to the package repository

https://github.com/aki2o/emacs-docker-robe

### Your association with the package

I'm a maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ ] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Please use `-` separator instead of `:`(also use `--` instead of `::` for private symbols) for emacs lisp convention
- There is no autoload cookie
- Missing cl-lib dependency in dependency header
- Please put docstring to entry point functions at least

**Comment by Silex** [comment]
Just wanted to mention https://github.com/emacs-pe/docker-tramp.el allows to run shells inside containers, might simplify the implementation.

**Comment by aki2o** [comment]
fixed.
But, not changed separator because I'd like to use not `-` as separator when the package name includes `-`.

I know it's recommended.
But, I think it can't force that to third party plugin like this pull request.
At present, other many plugins exists which uses not `-` separator char.

**Comment by Silex** [comment]
https://yourlogicalfallacyis.com/bandwagon :wink:

**Comment by purcell** [comment]
Where there is a clear community standard, choosing your own preference anyway means you're not interested in the community being able to work smoothly with your code. And that's fine, but if that's the case, why share that code with the community via MELPA? ;-)

**Comment by tarsius** [comment]
As @purcell said, you are of course free to break with the conventions if you don't like them. But it is okay if we don't include the package here because you have done so.

**Pull request closed without merging**
