### PR TITLE
Added new theme (minimal-mistakes-theme)

### PR DESCRIPTION
**Pull request by The-Repo-Club**
### Brief summary of what the package does

[Please write a quick summary of the package.]

### Direct link to the package repository

https://github.com/Minimal-Mistakes/emacs

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

maintainer

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for your patience.  Quick first pass --

`minimal-mistakes-theme.el` with checkdoc 0.6.2:
```
minimal-mistakes-theme.el:72: Documentation strings should not start or end with whitespace
```

`minimal-mistakes-theme.el` with package-lint 20220607.738:
```
8 issues found:
857:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
858:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
859:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
860:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
861:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
862:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
863:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
864:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
```

Package and license:
- GitHub API found `MIT License`
- minimal-mistakes-theme.el (unknown license) -- Minimal-Mistakes Theme
  - Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to minimal-mistakes-theme.el

**Comment by The-Repo-Club** [comment]
may need to look into dracula theme as the code base is the same just different colors also even the licence is the same... and since they are on the repo I thought this could be too :)

**Comment by riscy** [comment]
It's true, sometimes packages that are already indexed on MELPA have issues with them (or accrue issues with time).  If you think these issues also exist in dracula-theme, you could help them out by fixing them there, too.  Here's the latest --

`minimal-mistakes-theme.el` with checkdoc 0.6.2:
```
minimal-mistakes-theme.el:73: Documentation strings should not start or end with whitespace
```

`minimal-mistakes-theme.el` with package-lint 20220607.738:
```
8 issues found:
858:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
859:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
860:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
861:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
862:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
863:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
864:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
865:35: error: You should depend on (emacs "25.1") if you need `alist-get'.
```

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out. :)

**Comment by tarsius** [comment]
This pull-request has been open for over half a year. @The-Repo-Club could you please get this over the finish line soon, or else close it? If you do the latter but still plan to get this into Melpa eventually, then you might want to add a quick message here. You can ask us to reopen this pull-request when you are ready.

**Pull request closed without merging**
