### PR TITLE
Add biblio

### PR DESCRIPTION
**Pull request by cpitclaudel**
Browse and import bibliographic references from a variety of sources

This is a meta-package; I expect most people will use this one, but those who don't want all bibliographic sources don't need to install it, and can install just the relevant packages. 

Source: https://github.com/cpitclaudel/biblio.el
I'm the maintainer :)

### CODE REVIEW

**Comment by purcell** [comment]
See #3696

**Comment by cpitclaudel** [comment]
Ok, PR updated to reduce this to two packages :)

**Comment by cpitclaudel** [comment]
I'd love a quick check to make sure that I got that :excludes thing right, but hopefully I did :)

**Comment by purcell** [comment]
Yay, thanks!

**Pull request merged**
