### PR TITLE
recipes/pamparam: Add pamparam

### PR DESCRIPTION
**Pull request by abo-abo**
### Brief summary of what the package does

Simple and fast flashcards

### Direct link to the package repository

https://github.com/abo-abo/pamparam

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, this looks great! Some feedback:

- The recipe will include `elpa.el`. I'd suggest you keep distributed and non-distributed elisp files in separate dirs in your repo.
- You `require` hydra, but there's no declared dependency on it.
- The `pam-` prefix should be `pamparam-` throughout. `package-lint` should have told you about this... is it broken?

**Comment by abo-abo** [comment]
> The recipe will include elpa.el. I'd suggest you keep distributed and non-distributed elisp files in separate dirs in your repo.

I tried once to move it elsewhere. It was too tricky w.r.t. paths.

> You require hydra, but there's no declared dependency on it.

`lispy` depends on `hydra`.

> The pam- prefix should be pamparam- throughout. package-lint should have told you about this... is it broken?

`package-lint` didn't complain. But I'd really prefer to keep the `pam-` prefix. It's unique enough, and is more convenient for programming and discoverability.

**Comment by purcell** [comment]
> I tried once to move it elsewhere. It was too tricky w.r.t. paths.

Okay, then you'll need something like `:files (:defaults (:exclude "elpa.el"))` in the recipe.

> lispy depends on hydra.

It might not always depend on `hydra` - it's good style to depend explicitly on all the packages you use directly, not rely on transitive dependencies.

> But I'd really prefer to keep the pam- prefix. It's unique enough, and is more convenient for programming and discoverability.

Please don't. `pam` already means something else in Linux land, and bytes are cheap. `pamparam` is still a short prefix by elisp standards.

**Comment by abo-abo** [comment]
> pam already means something else in Linux land

It's nothing too relevant to user land. In the unlikely event of `pam.el` ever coming up, I can make a rename to `pamparam-`.

**Comment by alphapapa** [comment]
> It's nothing too relevant to user land. In the unlikely event of pam.el ever coming up, I can make a rename to pamparam-.

But then users would have to fix their configs.  :(

**Comment by tarsius** [comment]
@purcell Do you still insist on the prefix being changed?
@abo-abo Do you still insist on the prefix kept as is?

It's not up to me to make a decision, but if neither of you changes his mind, then I will close this issue. :wink:

**Comment by abo-abo** [comment]
@tarsius Renaming the prefix isn't a blocker for me, although keeping the same one would be more convenient.  I've switched jobs a few months ago, and the current job strain prevents me from putting a lot of time into my personal projects. I already maintain many packages, I probably shouldn't add one more for now. If my job situation improves, I'll rename the prefix and request another merge. You can keep the PR open or close it, as you prefer.

Pamparam is a good package, I use it every day and wanted to share it. I just don't want to make any maintenance promises right now.

**Comment by purcell** [comment]
Cool, I sent a PR in https://github.com/abo-abo/pamparam/pull/6.

**Pull request merged**
