### PR TITLE
Add himalaya

### PR DESCRIPTION
**Pull request by dantecatalfamo**
### Brief summary of what the package does

An Emacs front-end for the [himalaya](https://github.com/soywod/himalaya) email client

### Direct link to the package repository

https://github.com/dantecatalfamo/himalaya-emacs

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Very quick first pass --

`himalaya.el` with package-lint 20220213.1457:
```
1 issue found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
```
Prefer "Version" in this case -- MELPA will add Package-Version automatically.

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- Ultra minor: Ddefault -> Default, displaus -> displays

**Comment by riscy** [comment]
Marked awaiting-upstream for now, but feel free to reach out.

**Comment by tarsius** [comment]
@dantecatalfamo Friendly ping!

**Comment by dantecatalfamo** [comment]
Hey! I've been super busy recently, thanks for reminding me! :slightly_smiling_face:

**Comment by dantecatalfamo** [comment]
Should be good to go now

**Comment by riscy** [comment]
Thanks!  Looks good to go.

Just small small feedback re: the use of `error` -- given a form like
  ```elisp
   (with-current-buffer-window "*himalaya error*" nil nil (insert output))
     (error "Himalaya exited with a non-zero status"))
  ```
You may want to prefer `user-error`s if you don't want to display both the `output` as well as potentially exposing the entire backtrace to the user.

**Pull request merged**
