### PR TITLE
New recipe: org-calibre-notes

### PR DESCRIPTION
**Pull request by bpanthi977**
### Brief summary of what the package does

This package extract highlights and notes taken in Calibre ebook reader and saves them to a org file.

### Direct link to the package repository

https://github.com/bpanthi977/org-calibre-notes

### Your association with the package

I am the maintainer and creator of this package.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
Notes from a quick pass:

- Why does this package require counsel/ivy instead of using the built in completing read functions?

- Checkdoc reports the following:

```emacs-lisp
org-calibre-notes.el         35   1 warning  e-f-b-c  docstring has wrong usage of unescaped single quotes (use \= or different quoting)
```

In some of your commands you would be better suited by utilizing `user-error`. e.g.
`org-calibre-notes-save` could be re-written as:

```emacs-lisp
(defun org-calibre-notes-save ()
  "Save calibre notes (exported as json to clipboard) into a org file."
  (interactive)
  (when-let ((parsed (or (ignore-errors (json-parse-string (current-kill 0)))
                         (user-error "Invalid JSON")))
             (source (org-calibre-notes-select-ebook-file))
             (savefile (org-calibre-notes-select-save-file source)))
    (with-current-buffer (find-file-noselect savefile)
      (org-calibre-notes-parse-and-insert parsed-json source))))
```

**Comment by bpanthi977** [comment]
Thank you for your review. I have made the following changes: 

- replaced counsel with `read-file-name` function.
- used `user-error` instead of ignoring errors.


`M-x checkdoc` didn't report any warnings for me (I have Emacs 28.1). And from the message you got, it seems checkdoc threw warning for use of single quote in the example code. I think this should be fine.

**Comment by progfolio** [comment]
> it seems checkdoc threw warning for use of single quote in the example code. I think this should be fine.

You'll want to escape those single quotes so readers of your documentation can copy your examples and run them. Unescaped they will be rendered as curly quotes in the \*Help* buffer.

**Comment by bpanthi977** [comment]
I have update the docstring.

**Comment by progfolio** [comment]
> I have updated the docstring.

You'll want: `(mapcar #\\='first (assort list))` in the same docstring.

**Comment by bpanthi977** [comment]
Oh yes, right. Missed it.
Updated now.

**Comment by riscy** [comment]
Thank you both (and thank you so much @progfolio -- great points).

Have you had a chance to compare to https://melpa.org/#/calibredb ?  I notice it does some small things with org(-ref) and wanted to double-check.

I notice this line: `;;; License: MIT` which is a bit informal; I would recommend adding an [SPDX-License-Identifier](https://spdx.dev/ids/) instead to org-calibre-notes.el which is both standard and easily machine detectable.  I won't block on this, however.

**Comment by riscy** [comment]
Thank you @bpanthi977 - have you had a chance to consider the SPDX license identifier?  It's a small change, but it's far more rigorous than `;;; License: MIT`

**Comment by bpanthi977** [comment]
@riscy I took your suggestion and update to SPDX license identifier.

**Comment by riscy** [comment]
Thank again both - merging.

**Pull request merged**
