### PR TITLE
Add recipe/colorless-themes

### PR DESCRIPTION
**Pull request by lthms**
### Brief summary of what the package does

colorless-themes generalize, [nordless-theme](https://github.com/lthms/nordless-theme.el), a minimalist theme inspired by [nofrils](https://github.com/robertmeta/nofrils), an extremely minimalist colorscheme for vim, and [nord](https://github.com/arcticicestudio/nord), a north-bluish color palette.  More precisely, it provides a macro called `colorless-themes-make` to easily derive new “mostly colorless” themes.

### Direct link to the package repository

https://git.sr.ht/~lthms/colorless-themes.el

### Your association with the package

I am the author and maintainer of the package.

### Relevant communications with the upstream package maintainer

This PR is the first of a serie; I first add colorless-themes, which provide a generic macro to generate theme. Then, I will propose one PR per theme that I have generated using this macro.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
1.  Are these themes "colorless" or merely desaturated?  IOW I feel like the name could be more descriptive.
2.  While sr.ht is cool, there are no screenshots available in the `colorless-themes` repo, while `nordless-theme` has them.  This seems like a significant regression for users.

**Comment by lthms** [comment]
Thanks for your feedback.

Mostly they are colorless (as in “no syntax highlighting, with the notable exception of diffs and comments).

As for the screenshots, I have to admit you are right, but I am reluctant to add them to the repo again. I was planning to create a small presentation webpage, and add a link to this page to the repo instead. If you prefer to wait for this to be done before merging, I totally get that :).

**Comment by alphapapa** [comment]
> If you prefer to wait for this to be done before merging, I totally get that :).

@lthms I'm not a MELPA staff member, just offering my two cents.

**Comment by lthms** [comment]
Just a head-up. I am planning to publish a small project webpage to describe the currently available themes next week. I still like the name and wouldn’t change it unless it is very blocking, though.

**Comment by purcell** [comment]
Sorry for the delay. It occurs to me that the other way to handle all of this is to keep publishing `nordless-theme` but have it depend on a `colorless-themes` utility package. Have you considered that option? It'd kinda nice for people to just browse to and install the specific theme they want. I'm thinking about doing something similar with my own theme bundles.

**Comment by lthms** [comment]
To be completely honest with you, it was my first idea… but I couldn’t find any comprehensive and straightforward guide to do just that. It’s on me.

I would more than willing to do it, though.

**Comment by purcell** [comment]
You'd start by publishing `colorless-themes` as a package on MELPA containing the core macros/functions necessary to define those sorts of themes. Once published, you'd transition the `nordless-theme` package to `require` that package and use its functions, together with adding a `Package-Requires` dependency header entry to declare the package dependency.

**Comment by lthms** [comment]
That is way simpler that what I imagined! I had a look at `package.el` files and related.

I will try to do just that, starting by publishing colorless-themes as a package, and then create a repo for each theme currently located in `colorless-themes` repo.

Can I use this PR, or do you rather want me to create a new one?

**Comment by purcell** [comment]
> Can I use this PR, or do you rather want me to create a new one?

Just use this one. Ping when ready please!

**Comment by lthms** [comment]
Hi!

It took me quite some times, but I have finally taken the time to tackle your feedback. Sorry it took me so long. ):

That being said, *I think* everything is good now!

**Comment by riscy** [comment]
Hi @lthms!  @purcell can correct me if I'm wrong, but I think the intention was that we first get `colorless-themes` into MELPA, and then from there you can make followup PR's to get the dependent themes merged.  Typically it should be one PR per package.

That said, I recommend re-running through the checklist on `colorless-themes.el`:

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
6 issues found:

21:24: error: Package colorless-themes is not installable.  (No need to self-require)
23:1: warning: You should include standard keywords: see the variable `finder-known-keywords'.
37:1: error: "colorless/make" doesn't start with package's prefix "colorless-themes".
37:1: error: `colorless/make' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
244:1: error: "colorless/load" doesn't start with package's prefix "colorless-themes".
244:1: error: `colorless/load' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
Per CONTRIBUTING.org, consider using lexical binding
(The following assumes lexical binding is enabled)
```
colorless-themes.el:37:1:Error: Lisp nesting exceeds `max-lisp-eval-depth'
```

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
No issues! 🎉

Minor:
- colorless-themes.el#L16: Prefer `https` over `http` (if possible)

**Comment by lthms** [comment]
Thanks for the feedback @riscy, and sorry for the not having re-running through the checklist myself. I will do as you said: one PR for colorless-themes and one PR per theme then.

Hopefully I shall do it right this time :p.

**Comment by riscy** [comment]
A typical combination of keywords is: `faces, themes` where `faces` refers to ("fonts and colors for text").  Often when I wonder about this, I go and look at the keywords a related package has used.

> I couldn’t reproduce ._.

It doesn't happen to me with your latest commit, so I think once the keywords are set we're good to merge.  Thanks for sticking with it -- looking forward to pulling down the child themes when we add them.

**Comment by lthms** [comment]
I think [we are good now](https://git.sr.ht/~lthms/colorless-themes.el/commit/ed8e577748d05c2d7e17770c9ffdded7f6d5b863).

Let me know if I need to do anything else. Thanks for your help and reviews

**Comment by riscy** [comment]
Thank you!

**Comment by lthms** [comment]
Thanks :heart: will be back soon with an update of `nordless`, and several other PRs for my other themes.

**Pull request merged**
