### PR TITLE
New recipe: afterglow

### PR DESCRIPTION
**Pull request by ernstvanderlinden**
### Brief summary of what the package does

Temporary highlighting for regions, lines, or custom-defined regions after specific function calls. This visual feedback tool is perfect for tracking code evaluations, cursor movements, or any changes within your buffer

### Direct link to the package repository
https://github.com/ernstvanderlinden/emacs-afterglow

### Your association with the package
Maintainer

### Relevant communications with the upstream package maintainer

After conversation with Nicholas Vollmer and Chris Rayner, we discarded the original package pull request.
This is a new package which originally was called `evil-hl`. The package has been renamed to `afterglow` and refactored to not only support evil users.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by ernstvanderlinden** [comment]
Oops, forgot to push the release tag to github

**Comment by riscy** [comment]
Thanks!  Technically pushing release tags is not required unless you want to push a stable release.   So it's especially not required during the review phase.  That said, quick first pass --

`afterglow.el` with byte-compile using Emacs 29.1:
```
afterglow.el:241:4: Warning: the function `hash-table-keys' is not known to be defined.
```

`afterglow.el` with checkdoc 0.6.2 (fix *within reason*):
```
afterglow.el:313: All variables and subroutines might as well have a documentation string
afterglow.el:404: All variables and subroutines might as well have a documentation string
```

`afterglow.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- afterglow.el#L268: `fmakunbound` should rarely occur in packages; I don't understand why you need to do this - could you help me understand? What function are you `fmakunbound`ing?
- afterglow.el#L288: `fmakunbound` should rarely occur in packages
- afterglow.el#L304: `fmakunbound` should rarely occur in packages
```

**Comment by ernstvanderlinden** [comment]
Thanks Chris, all changes have been pushed to GitHub. Please see fixes below.

Have a great day,
Ernest


On 2 Mar 2024, at 21:15, Chris Rayner ***@***.***> wrote:



Thanks! Technically pushing release tags is not required unless you want to push a stable release. So it's especially not required during the review phase. That said, quick first pass --

afterglow.el with byte-compile using Emacs 29.1:

afterglow.el:241:4: Warning: the function `hash-table-keys' is not known to be defined.


> Ernest:

  Added `(require 'subr-x)` as it defines `hash-table-keys`

  afterglow.el with byte-compile using Emacs 30.0:
  Compiling /Users/eml/repo/eml/emacs-pkg/afterglow/afterglow.el...done
  Wrote /Users/eml/repo/eml/emacs-pkg/afterglow/afterglow.elc

afterglow.el with checkdoc 0.6.2 (fix within reason):

afterglow.el:313: All variables and subroutines might as well have a documentation string
afterglow.el:404: All variables and subroutines might as well have a documentation string

> Ernest:

  Added 2 new doc strings. One false positive in defun doc string `afterglow-remove-triggers`.

afterglow.el with melpazoid<https://github.com/riscy/melpazoid>:

- afterglow.el#L268: `fmakunbound` should rarely occur in packages; I don't understand why you need to do this - could you help me understand? What function are you `fmakunbound`ing?
- afterglow.el#L288: `fmakunbound` should rarely occur in packages
- afterglow.el#L304: `fmakunbound` should rarely occur in packages


> Ernest:

  Afterglow is designed to create package functions that advise non-package functions, and it tracks these to ensure they can be removed or `fmakunbound` when necessary. This action is triggered under specific conditions, for example:
  - When the Afterglow minor mode is disabled;
  - If a user decides to remove an Afterglow 'trigger' function.

**Comment by riscy** [comment]
> Afterglow is designed to create package functions that advise non-package functions, and it tracks these to ensure they can be removed or `fmakunbound` when necessary

Alright, I understand what's going on here.  I think this is extremely flexible but maybe too flexible for the average use case, but who can speculate? :)

**Comment by riscy** [comment]
And, welcome to MELPA. :)

**Comment by ernstvanderlinden** [comment]
Thanks a bunch Chris! Really happy to join the MELPA club :-)))

Have a great day,
Ernest

On 10 Mar 2024, at 19:24, Chris Rayner ***@***.***> wrote:

﻿

And, welcome to MELPA. :)

**Pull request merged**
