### PR TITLE
Recipe: Add helm-bufler, separate from bufler

### PR DESCRIPTION
**Pull request by alphapapa**
This moves Bufler's Helm-related code into a separate `helm-bufler` package.

When this PR is merged, I'll merge the branch https://github.com/alphapapa/bufler.el/tree/wip/helm-bufler-package into `master` to complete the transition.

Thanks.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
On a quick glance I notice `helm-bufler` lacks a `Package-Requires` which should probably include bufler (since it requires bufler-workspace).

**Comment by alphapapa** [comment]
@riscy `helm-bufler.el` in the linked branch has the header.  I don't want to merge it to `master` until the recipe is merged, because the other changes in `helm-bufler.el` will cause errors for users without Helm installed.

**Comment by riscy** [comment]
Hopefully not catching you off guard merging at this strange hour -- we had a fire alarm go off in the building so here I am. :)

**Comment by alphapapa** [comment]
Unlucky for you, lucky for me.  :)  Thanks, Chris.  I'll merge that branch now.

**Pull request merged**
