### PR TITLE
Add mess recipe.

### PR DESCRIPTION
**Pull request by Iacob**
### Brief summary of what the package does

Front-end for MAME in MESS mode.

### Direct link to the package repository

https://github.com/Iacob/mess.el

### Your association with the package

I'm the owner of the package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`mess-base.el` with checkdoc 0.6.2:
```
mess-base.el:67: Argument `user-config' should appear (as USER-CONFIG) in the doc string
```

`mess-base.el` with package-lint 20230605.1550:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```

`mess-config.el` with byte-compile using Emacs 28.1:
```
mess-config.el:154:20: Warning: the function `mess-machine-info-loader-load'
    is not known to be defined.
mess-config.el:89:16: Warning: the function `mess-base-reload-user-config' is
    not known to be defined.
mess-config.el:83:6: Warning: the function `mess-base-save-user-config' is not
    known to be defined.
```

`mess-config.el` with package-lint 20230605.1550:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```

`mess-config.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- mess-config.el#L165: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
```

`mess-machine-info-loader.el` with package-lint 20230605.1550:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```

**Comment by Iacob** [comment]
@riscy issues fixed

**Comment by riscy** [comment]
Thanks!  I recognize the list in mess-machine-info-loader.el from https://github.com/melpa/melpa/pull/8526 ; considering this is 4.7MB of data, and that it's not unlikely someone would have both your `mame` and `mess` packages installed, I wonder if it would make sense to have `mess` depend on `mame` so that users don't have two packages with the same giant lists in them.  What do you say?

Another thing I notice when looking at the code is that you are placing the `provide` lines at the top of the files, e.g. `(provide 'mame-machine-info-loader)` -- it's convention for these to go at the bottom of the file.  I also notice this happening with the `mame` package, e.g.

- mame-machine-info-loader.el:39677: The footer should be: (provide 'mame-machine-info-loader)\n;;; mame-machine-info-loader.el ends here

**Comment by Iacob** [comment]
@riscy mame is added to the dependency list

**Comment by riscy** [comment]
Thanks!  Regarding the footers of your packages, they should look like:

```elisp
(provide 'x)
;; x.el ends here
```

So for example in mess-config.el, you have the `provide` as the first code line in the file, but it should be the last code line in the file.  Same with mess-base.el, and mess.el.

**Comment by Iacob** [comment]
@riscy Thank you for the reminder. All files are updated.

**Comment by riscy** [comment]
Looks good - thanks!

**Pull request merged**
