### PR TITLE
Add recipe: binder

### PR DESCRIPTION
**Pull request by rnkn**
### Brief summary of what the package does

Binder is an Emacs global minor mode facilitating multi-file writing projects, taking influence from popular writing app Scrivener. Using a project file `.binder.el` in a project's top-level directory it tracks a linear-list of files and properties including their order, inclusion state in the final project, notes, and tags.

### Direct link to the package repository

https://github.com/rnkn/binder

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by rnkn** [comment]
p.s. Please note that package-lint will report that seq is not installable on Emacs versions >= 25, but is required for Emacs 24.x.

**Comment by riscy** [comment]
Thanks, this looks interesting.  Here's a quick first pass --

### binder-tutorial.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200901.2204):
- No issues!


### binder.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
binder.el:260: Disambiguate binder-mode by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
binder.el:673: Disambiguate binder-mode by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
binder.el:682: Disambiguate binder-mode by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
binder.el:1232: Disambiguate binder-mode by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
binder.el:1551: Disambiguate binder-concat-mode by preceding w/ function,command,variable,option or symbol.
```

package-lint (using version 20200901.2204):
- No issues!

Other possible lints:
- binder.el#L694: It's safer to sharp-quote function names; use `#'`
- binder.el#L695: It's safer to sharp-quote function names; use `#'`
- binder.el#L1286: It's safer to sharp-quote function names; use `#'`
- binder.el#L697: It's safer to sharp-quote function names; use `#'`
- binder.el#L910: It's safer to sharp-quote function names; use `#'`
- binder.el#L966: It's safer to sharp-quote function names; use `#'`
- binder.el#L1526: It's safer to sharp-quote function names; use `#'`
- binder.el#L942: Could this point/point-max comparison use `eobp`?
- binder.el#L1462: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- binder.el#L1463: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- binder.el#L1464: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- binder.el#L1465: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- binder.el#L1466: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- binder.el#L847: Consider `unless ...` instead of `when (not ...)`
- binder.el#L201: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading binder-tutorial.el
Loading binder.el
Done.
```

**Comment by rnkn** [comment]
Awesome, thanks I've made most of the changes mentioned. Those I've decided against are:

> checkdoc (using version 0.6.2):
> 
> ```
> Warning (emacs): 
> binder.el:260: Disambiguate binder-mode by preceding w/ function,command,variable,option or symbol.
> Warning (emacs): 
> binder.el:673: Disambiguate binder-mode by preceding w/ function,command,variable,option or symbol.
> Warning (emacs): 
> binder.el:682: Disambiguate binder-mode by preceding w/ function,command,variable,option or symbol.
> Warning (emacs): 
> binder.el:1232: Disambiguate binder-mode by preceding w/ function,command,variable,option or symbol.
> Warning (emacs): 
> binder.el:1551: Disambiguate binder-concat-mode by preceding w/ function,command,variable,option or symbol.
> ```

Any `*-mode` is not ambiguous, or if it is I'd think that a bug in the program. I think checkdoc should not raise `*-mode` symbol names as ambiguous.

> * binder.el#L847: Consider `unless ...` instead of `when (not ...)`

Just in the context of this function, where this forms part of a series of when statements, I find `(when (not ...) ...)` to be more consistent/idiomatic.

Thanks for the checks!

**Comment by rnkn** [comment]
p.s. I'm not sure why the Travis checks are failing; the Github Actions checks are all okay: https://github.com/rnkn/binder/actions/runs/253258941

**Comment by riscy** [comment]
The Travis build has some issues tracking commits right now -- nothing to worry about on your end.

**Comment by riscy** [comment]
> Any *-mode is not ambiguous, or if it is I'd think that a bug in the program. I think checkdoc should not raise *-mode symbol names as ambiguous.

I agree, checkdoc is pedantic.  In this case I think it's upset because `define-minor-mode` creates a variable _and_ a function  called `binder-mode`, but many checkdocs are nonissues.

In any case, everything looks good!  Thanks for this.

**Pull request merged**
