### PR TITLE
Add winds

### PR DESCRIPTION
**Pull request by Javyre**
### Brief summary of what the package does

Window configuration switcher grouped by workspaces

winds.el is very similar to [eyebrowse](https://github.com/wasamasa/eyebrowse/) and other window config
switchers, but allows for having mutiple "workspaces" grouping sets
of window config slots.

### Direct link to the package repository

https://github.com/Javyre/winds.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Just rolling through with a really quick first pass --

### winds.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
winds.el:138: First line is not a complete sentence
Warning (emacs): 
winds.el:138: Some lines are over 80 columns wide
Warning (emacs): 
winds.el:161: All variables and subroutines might as well have a documentation string
Warning (emacs): 
winds.el:163: All variables and subroutines might as well have a documentation string
Warning (emacs): 
winds.el:168: All variables and subroutines might as well have a documentation string
Warning (emacs): 
winds.el:176: All variables and subroutines might as well have a documentation string
Warning (emacs): 
winds.el:184: All variables and subroutines might as well have a documentation string
```

package-lint-current-buffer (using version 20200408.203):
- No issues!

Small stuff:
- winds.el#L27: Prefer `https` over `http` (if possible)
- "crrent" -> "current"
- "mutiple" -> "multiple"
- "Defalut" -> "Default"

**Comment by Javyre** [comment]
Thanks, should be all fixed now

**Comment by riscy** [comment]
I appreciate the example in your README.  As a last comment, I see:

byte-compile-file (using Emacs 26.3):
```
winds.el:269:13:Warning: reference to free variable `desktop-globals-to-save'
winds.el:273:19:Warning: assignment to free variable `desktop-globals-to-save'
```

but it is because you inline your require (which is good style, so it's fine).  However you can quiet the compiler by adding a simple `(defvar desktop-globals-to-save)` at the top of the file.

That is small enough and easy enough to fix that I don't think it's worth blocking on. :)

Welcome to MELPA!

**Comment by Javyre** [comment]
Great! Thanks, the warning is suppressed now.

**Pull request merged**
