### PR TITLE
Add monokai-pro-theme recipe

### PR DESCRIPTION
**Pull request by belak**
### Brief summary of what the package does

A simple theme based on the monokai pro themes from VSCode and Monokai.

### Direct link to the package repository

https://github.com/belak/emacs-monokai-pro-theme

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

Note that I've built the package successfully, but installing it gives the error "Package does not untar cleanly into monokai-pro-theme-20190425.1245/". I've untarred it manually and it seems to work fine, so I'm not sure what the issue is. It's also based on another theme package of mine which I know works.

### CODE REVIEW

**Comment by milkypostman** [comment]
please add a screenshot

**Comment by belak** [comment]
Screen Shot 2019-04-25 at 1 55 27 PM

**Comment by milkypostman** [comment]
I meant to please add it to your github so visitors can see the screenshot
in the readme. Since Melos won’t pull this file there is very little
overhead for users.

**Comment by belak** [comment]
Ah, got it. Done.

**Comment by belak** [comment]
Nifty. That shortens up a few lines. I'll also look at doing that for my other themes. Nice to know I don't need the -pkg file as well.

**Comment by purcell** [comment]
Cool, merged now. :-)

**Pull request merged**
