### PR TITLE
added recipe for pastery.

### PR DESCRIPTION
**Pull request by diasbruno**
### Brief summary of what the package does

paste snippets to pastery.

### Direct link to the package repository

https://github.com/diasbruno/pastery.el

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by xuchunyang** [comment]
Autoload cookies are missing for interactive commands.

**Comment by syohex** [comment]
And I have sent PR about packaging. https://github.com/diasbruno/pastery.el/pull/11 . Please check it.

**Comment by diasbruno** [comment]
Thanks, @xuchunyang @syohex.

**Comment by diasbruno** [comment]
@xuchunyang @syohex fixed all package details.

**Comment by syohex** [comment]
There is no autoload cookies yet. https://github.com/diasbruno/pastery.el/pull/13 Please see this PR.

**Comment by diasbruno** [comment]
Thank you, @syohex. New version released.

**Comment by syohex** [comment]
@diasbruno Merged. I have sent PR about command interface, please check it(https://github.com/diasbruno/pastery.el/pull/21)

**Pull request merged**
