### PR TITLE
Create ox-epub

### PR DESCRIPTION
**Pull request by ofosos**
Add a recipe for ox-epub.

### Summary

This package is an additional exporter for org-mode that generates .epub files.

org-epub extends the org export infrastructure to create custom .epub files. This includes a customized html export backend that generated epub 2 compatible output, features to include cover art, as well as generating a comprehensive table of contents and finally building the .epub files

https://github.com/ofosos/ox-epub

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Please don't use earmuff variable like common lisp for Emacs Lisp coding convention. Use `org-epub-current-file` instead of `*org-epub-current-file*`. And declare it as global variable.
- And there are some byte-compile warnings, please check.

**Comment by ofosos** [comment]
Ok, both are fixed.

**Comment by syohex** [comment]
There are still issue on Emacs 25.1. I have sent PR(https://github.com/ofosos/org-epub/pull/1), please check it.

**Comment by ofosos** [comment]
Checked, looks good. Thanks for spotting this.

**Comment by marsam** [comment]
@ofosos cool package! Can you consider rename it to `ox-epub`, I think is common practice use `ox-` prefix for org exporters.

**Comment by ofosos** [comment]
@marsam that is actually a good idea. I will do this approx. 8 PM UTC.

**Comment by purcell** [comment]
> @marsam that is actually a good idea. I will do this approx. 8 PM UTC.

Bump! :-)

**Comment by ofosos** [comment]
@purcell Narf, just got home from work at 11PM, I think I want to hear some radio and hack on this code a little :)

**Comment by ofosos** [comment]
I renamed the package but left the functions in the `org-' namespace. I think this is consistent with the rest of the `ox-*' packages. What do you think? If you're satisfied I'll bump stable to another patchlevel,

**Comment by ofosos** [comment]
@marsam @purcell Any comments on this?

**Comment by marsam** [comment]
@ofosos sorry for the delay. LGTM.

**Comment by syohex** [comment]
Merged

**Pull request merged**
