### PR TITLE
Add mxf-view

### PR DESCRIPTION
**Pull request by t-suwa**
### Brief summary of what the package does

Easy to use MXF file viewer. Display physical structures of MXF in neat.

### Direct link to the package repository

https://github.com/t-suwa/mxf-view

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by DamienCassou** [comment]
Some feedback:

1. can you please squash the commits into just 1?
2. please add `-*- lexical-binding: t; -*-` at the end of the first line
3. you might want to add an autoload cookie for the major mode

**Comment by t-suwa** [comment]
Thank you for your kind feedback and sorry for inconvenience.
I found some lexical binding related issues and fixed them.

**Comment by purcell** [comment]
Thanks. Further feedback from me:

- You don't need to set the [keymap for the major mode](https://github.com/t-suwa/mxf-view/blob/fbf479a486fc8930aafcf36a3190b347f5077290/mxf-view.el#L140) - `define-derived-mode` does this for you.
- The file extension regexp [here](https://github.com/t-suwa/mxf-view/blob/fbf479a486fc8930aafcf36a3190b347f5077290/mxf-view.el#L1663) should end with `\\'`, to match end-of-input. (Currently it would match `.mxfslfkjdf`, for example.)
- You should use `cl-lib` instead of the now-deprecated `cl`. In most cases, you'd just need to `(require 'cl-lib)` and then prefix any `cl` functions or macros with `cl-`, e.g. `first` => `cl-first`.

None of those are barriers to merging this package, though, so I'll go ahead and do that now. Welcome to MELPA! :tada:

**Comment by t-suwa** [comment]
I'm very impressed  your feedback and effort.   Thanks guys.

**Pull request merged**
