### PR TITLE
Add chinese-pyim-greatdict recipe

### PR DESCRIPTION
**Pull request by tumashu**

### CODE REVIEW

**Comment by tumashu** [comment]
chinese-pyim is a chinese pinyin input method,  chinese-pyim-greatdict is a pinyin dict of this im.

**Comment by purcell** [comment]
Great, thanks. Please could you change the `"*.el"` to `:defaults` in the `:files` spec?

**Comment by tumashu** [comment]
Fixed.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
