### PR TITLE
Added malyon

### PR DESCRIPTION
**Pull request by speedenator**
### Brief summary of what the package does

This package provides a basic interpreter for version 3, 5, 8 z code
story files as generated by Inform (C) Graham Nelson and Infocom.

### Direct link to the package repository

https://github.com/speedenator/malyon.git

### Your association with the package

I'm just a fan, wanting to create a MELPA-based repository from the original EmacsWiki (https://www.emacswiki.org/emacs/MalyonMode) for better package portability

### Relevant communications with the upstream package maintainer

Have sent request to author / maintainer Peter Ilberg, but he hasn't responded yet. From comments, he states he is unable to maintain this anymore.

### Checklist

- [X ] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X ] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
There are too many byte-compile warnings. Please check and fix them as possible.

This package defines many aliases for compatiblity(?) however almost them are not necessary to define alias. For example `cadr`, `mapc`, `mapcan`, `remove`. You can use them directly.

**Comment by speedenator** [comment]
Updated; byte-compiles on 25 w/ no warnings, and ran through tests so builds and runs fine as far as I can tell. Left in 5 aliases for what I think are long-deprecated functions - the local code now handles things.

**Comment by syohex** [comment]
`caddr` and `cdddr` are cl-lib functions. 

https://github.com/speedenator/malyon/pull/1

**Comment by speedenator** [comment]
ah true. my old-school habits still getting the better of me. :)

**Comment by speedenator** [comment]
Inc - any remaining issues for PR?

**Comment by syohex** [comment]
https://github.com/speedenator/malyon/pull/3

Package header is broken. Sorry I'm very busy in this week.

**Comment by purcell** [comment]
Thanks, sorry for the slow response. Busy end of year here.

**Comment by speedenator** [comment]
No problem. Thanks for helping!

**Pull request merged**
