### PR TITLE
Add parinfer-rust recipe.

### PR DESCRIPTION
**Pull request by justinbarclay**
### Brief summary of what the package does

Parinfer is a system for managing your indentation and parens in lisp and scheme like languages based on specific modes. Shaun Lebron has a put together a great site [site](https://shaunlebron.github.io/parinfer/) explaining and demoing how this works system.

`parinfer-rust-mode.el` is a minor mode that acts as an interface to the parinfer-rust library. [parinfer-rust](https://github.com/eraserhd/parinfer-rust) is, in my opinion, the most complete implementation of the Parinfer system -- next to the JS reference implementation. By this I mean it actively supports the 3 major modes for Parinfer: paren, indent, and smart without hiding them behind experimental flags or warnings.  The major downside of using parinfer-rust is that it is a dynamic modules and, as such, requires Emacs' be compiled with the `--with-modules` flag to run.

There is an alternative implementation of [parinfer](https://github.com/DogLooksGood/parinfer-mode) for Emacs, but unfortunately it has hidden some parts of the implementation for Parinfer behind a feature branch and hasn't seen much progress in releasing that feature in over a year.
### Direct link to the package repository

https://github.com/justinbarclay/parinfer-rust-mode

### Your association with the package

I am the primary maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Interesting!  Just to start off with, you should rename `parinfer-rust-mode.el` to `parinfer-rust.el` -- then it becomes your "main" file, and MELPA will know where to look for the dependencies.  I'm skipping package-lint below for now until that's fixed:

### parinfer-rust-changes.el ###

byte-compile (using Emacs 26.3):
```
parinfer-rust-changes.el:57:36:Error: Symbol's value as variable is void: parinfer-rust-library
```

checkdoc (using version 0.6.1):
- No issues!

Suggestions/experimental static checks:
- parinfer-rust-changes.el#L158: Consider `unless ...` instead of `when (not ...)`
- parinfer-rust-changes.el#L17: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### parinfer-rust-helper.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

Suggestions/experimental static checks:
- parinfer-rust-helper.el#L197: Consider `unless ...` instead of `when (not ...)`
- parinfer-rust-helper.el#L199: Consider `unless ...` instead of `when (not ...)`
- parinfer-rust-helper.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### parinfer-rust-mode.el ###

byte-compile (using Emacs 26.3):
```
parinfer-rust-mode.el:131:1:Error: Cannot open load file: No such file or directory, ~/.emacs.d/parinfer-rust/parinfer-rust-linux.so
```

checkdoc (using version 0.6.1):
- No issues!

Suggestions/experimental static checks:
- parinfer-rust-mode.el#L352: It's safer to sharp-quote function names; use `#'`
- parinfer-rust-mode.el#L353: It's safer to sharp-quote function names; use `#'`
- parinfer-rust-mode.el#L361: It's safer to sharp-quote function names; use `#'`
- parinfer-rust-mode.el#L362: It's safer to sharp-quote function names; use `#'`
- parinfer-rust-mode.el#L349: It's safer to sharp-quote function names; use `#'`
- parinfer-rust-mode.el#L351: It's safer to sharp-quote function names; use `#'`
- parinfer-rust-mode.el#L303: No `format` required; messages are already f-strings
- parinfer-rust-mode.el#L259: Consider `unless ...` instead of `when (not ...)`
- parinfer-rust-mode.el#L22: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading parinfer-rust-changes.el
parinfer-rust-changes.el:Error: Emacs 26.3 errored during load
Loading parinfer-rust-helper.el
Loading parinfer-rust-mode.el
Could not find the parinfer-rust library, would you like to automatically download it from github?(yes or no) parinfer-rust-mode.el:Error: Emacs 26.3 errored during load
Done.
```
I think it's best to wait until the user activates parinfer-rust-mode to ask them if they want to download the library.

### Package ###

- No .el file matches the name 'parinfer-rust'

**Comment by justinbarclay** [comment]
Hmm I think, I'd prefer to rename the recipe to parinfer-rust-mode if possible then. I didn't think through the ramification of naming a MELPA package as something different then the files themselves.

I've fixed up all the code suggestions. 

I would really prefer to not defer the download prompt. In my mind akin to package-require specifying the dependencies of the file/package. But, because their is no package management system in Emacs for dynamic libraries, I had to build a system that makes sure the library exists before the interface can load. 

So if _it's_ absolutely necessary for me to defer the prompt in the minor mode initialization I'll further explore the work required to get this working. I did take an initial stab at it and byte compiler errors started getting thrown around and a lot of my [tests failed](https://app.circleci.com/pipelines/github/justinbarclay/parinfer-rust-mode/192/workflows/66261128-32d3-4edf-a0a3-8335ac1eb300/jobs/365/steps).


I do admit a current flaw to my setup is that errors like `parinfer-rust-changes.el:Error: Emacs 26.3 errored during load` due to an assumption I make that `parinfer-rust-mode.el` is always loaded first (thus validating the dynamic library exists and the other files can then be required).

**Comment by justinbarclay** [comment]
Alternatively, would it be appropriate instead of prompting, just to download the library if it's not detected in the load path and have an alert like [emacsql-sqlite](https://melpa.org/#/emacsql-sqlite) does?

**Comment by riscy** [comment]
I hear where you're coming from.  Maybe there is some way to improve the user experience though, since this feels like it will be a bit rough for some users who try to install the package by compiling it, instead of loading it first:

- We download the MELPA package and attempt to byte-compile the files (possibly in lexicographic order)
- The first file we try to compile, parinfer-rust-changes.el, throws an error because we didn't get a chance to download the library yet -- we just see a "no such file" error
- parinfer-rust-helper.el compiles successfully
- We try to compile parinfer-rust-mode.el, which throws an error since `parinfer-rust--check-for-library` is not called during compilation, only during loading (is this a good use for `eval-when-compile`?)

**Comment by justinbarclay** [comment]
You’re right, compiling this package for the first time definitely has its pitfalls.

I could turn off the prompt/download behaviour during byte compilation and instead throw an error should the library not exist. Redirecting them to the readme to find out how to install the library?

> parinfer-rust.so not found. For steps on how to download or install parinfer-rust please see https://github.com/justinbarclay/parinfer-rust-mode

**Comment by riscy** [comment]
> I could turn off the prompt/download behaviour during byte compilation and instead throw an error

I think I was being too verbose. To me the usability issue is that there _is_ no prompt/download behavior during byte compilation -- just an error about being unable to load the module.  Redirecting them to the README when this happens would definitely be an improvement.

After looking a little more deeply what I'd recommend is to use `(require 'parinfer-rust parinfer-rust-library t)` (the `t` signifying "noerror").  This means you'll get byte-compile warnings, but everything will compile without errors.

You can even mute those warnings by adding lines like:
```elisp

(declare-function parinfer-rust-make-option "ext:parinfer-rust" t t)
(declare-function parinfer-rust-make-changes "ext:parinfer-rust" t t)
(declare-function parinfer-rust-new-options "ext:parinfer-rust" t t)
(declare-function parinfer-rust-make-request "ext:parinfer-rust" t t)
(declare-function parinfer-rust-execute "ext:parinfer-rust" t t)
(declare-function parinfer-rust-get-in-answer "ext:parinfer-rust" t t)
(declare-function parinfer-rust-debug "ext:parinfer-rust" t t)
(declare-function parinfer-rust-print-error "ext:parinfer-rust" t t)
(declare-function parinfer-rust-version "ext:parinfer-rust" t t)
```
at the top of the file.  That way you'll end up with a silent (happy) byte-compile, and a failure-to-load error that only gets triggered when the user actually tries to load the package.

**Comment by justinbarclay** [comment]
That clears it up alot! Thank you for pointing me in the right direction :)

On master, I've set "noerror" and declared all those functions. As well I'm exploring your first suggestion, installing the module during byte compilation in a separate branch/warning about the missing module. I can leave another comment in this PR when that works is finished if it is required to add this recipe to melpa :)

**Comment by justinbarclay** [comment]
I've added the warning/prompt during byte compilation as well. I admit, that's a much better experience for users. Thanks for the suggestion.

**Comment by riscy** [comment]
> I've added the warning/prompt during byte compilation as well.

I won't block on this, but I think it's better to let everything byte-compile cleanly, and only warn the user when they try to _load_ the library.  Otherwise users will have to remember to go back and re-attempt the byte-compile after installing the module (which they may never end up doing).  It's not a big deal, and this has given me a chance to think about how packages with external dependencies like this should work.

Also I'll note (but again won't block on) this:
```
parinfer-rust-changes.el:205:1:Warning: the function `string-join' is not
    known to be defined.
```
which can be fixed with a `(require 'subr-x)`, and as a small suggestion, parinfer-rust-mode.el#L370: Consider `unless ...` instead of `when (not ...)`

**Comment by justinbarclay** [comment]
That is great to hear! 🥳 

Thanks for all your help, I really appreciate it. I have also fixed the other issues you've talked about, though I could not find the when not.

I really appreciate you pushing me to defer the prompt until `parinfer-rust-mode` is called, I think I've found a way that satisfies the way I like to structure code and still making it a better experience for the user.  

I've left in the prompt at  compile time for now and I will probably revisit that later, when I've had more time to test/consider that experience.

**Pull request merged**
