### PR TITLE
Add recipe streamlink

### PR DESCRIPTION
**Pull request by BenediktBroich**
### Brief summary of what the package does

Some useful function to control livestreamer.
 
### Direct link to the package repository

https://github.com/BenediktBroich/streamlink

### Your association with the package

I am the maintainer. I just want to integrate helm-twitch into spacemacs. So basically i am just manipulating https://github.com/atheriel/helm-twitch a little bit. Livestreamer is one part of this. 

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
How long do you plan to maintain this package?  Twitch tends to churn APIs, and Streamlink tends to go stale.  It might be better for this to live outside of MELPA.

**Comment by BenediktBroich** [comment]
I can not really predict how long i will update this. Right now i am just trying to get it working again. You may be right. The erc-twich melpa package for twitch icons in irc it is also broken. The twitch api endpoint does not exist anymore.

**Comment by riscy** [comment]
Thanks for this submission -- and that's a fair comment above from @alphapapa.  If you wanted to be _really_ safe you could build some kind of breaking-changes-check into your CI, have that check run periodically, and display an icon on your README indicating the status.  I think these days GitHub actions makes that pretty straightforward, but it _is_ extra work.

> Right now i am just trying to get it working again.

Just to double check this, is this package currently broken?  I am not a regular user of either of the services in question...

In the meantime, here's a quick run over the checklist:

### streamlink.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
streamlink.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
streamlink.el:43: First line is not a complete sentence
Warning (emacs): 
streamlink.el:81: First line is not a complete sentence
Warning (emacs): 
streamlink.el:90: First line is not a complete sentence
Warning (emacs): 
streamlink.el:105: First line is not a complete sentence
Warning (emacs): 
streamlink.el:120: Argument `size' should appear (as SIZE) in the doc string
Warning (emacs): 
streamlink.el:151: First line is not a complete sentence
Warning (emacs): 
streamlink.el:177: First line is not a complete sentence
Warning (emacs): 
streamlink.el:204: Argument `size' should appear (as SIZE) in the doc string
```

package-lint (using version 20210528.2348):
```
8 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a ;;; Commentary section.
1:0: error: Package should have a Homepage or URL header.
1:0: warning: The package summary should not end with a period.
63:1: error: You should depend on (emacs "24.3") if you need `defvar-local'.
66:1: error: You should depend on (emacs "24.3") if you need `defvar-local'.
69:1: error: You should depend on (emacs "24.3") if you need `defvar-local'.
243:11: warning: Closing parens should not be wrapped onto new lines.
```

Other [lints](https://github.com/riscy/melpazoid):
- streamlink.el#L180: This double negation can be collapsed (`not` aliases `null`)
- streamlink.el#L189: This double negation can be collapsed (`not` aliases `null`)

**Comment by BenediktBroich** [comment]
@riscy This package should work. I will have a look at the warning.

**Comment by BenediktBroich** [comment]
All warnings are fixed and a CI is integrated. I think it is ready for melpa.

**Comment by riscy** [comment]
Thanks - I think this look good to merge.

Non-blocker: The use of `prog1` to define the keymap struck me as a little unusual but I may be missing something.  I'm curious to know if there's a reason why you didn't write it without the prog1 e.g. as:
```elisp
(defvar streamlink-mode-map
  (let ((map (make-sparse-keymap)))
    (suppress-keymap map)
    (define-key map "q" 'streamlink-kill-buffer)
    ;; ...
    map)
  "Keymap for `streamlink-mode'.")
```

Another non-blocker: I'd recommend documenting the version of `streamlink` that this works with, since it seems like it has some fragile dependence on the process output.  For example `(re-search-forward "Available streams:\s")` will emit a show-stopping error if streamlink decides to reword its output.

**Pull request merged**
