### PR TITLE
Add glue recipe

### PR DESCRIPTION
**Pull request by hajovonta**
### Brief summary of what the package does

Allows interop between Common Lisp and Emacs.
Provides functions to run Common Lisp code on the SLIME-connected CL backend from Emacs Lisp. It is now possible to outsource long-running processes from Emacs and get feedback (think about progressbars, status updates etc)

### Direct link to the package repository

https://git.sr.ht/~hajovonta/glue/

### Your association with the package

Package author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
Your macros could probably all be functions.
 Instead of expanding based off of the `slime-connected-p` or `sly-connected-p` predicates, you could have a variable, which is set once and used throughout. e.g.

```emacs-lisp
(defvar bubbles--cl-environment
  (cond
   ((slime-connected-p) 'slime)
   ((sly-connected-p) 'sly)
   (t ;;Gracefully handle case where use is not connected.
      ;;Offer to connect?
    ))
  "CL Implementation used for evaluation.")

;;example usage

(defun bubbles-send-sync (cl-text)
  "Run CL form synchronously and return result.
Input valid CL form as string as CL-TEXT."
  (if-let ((fn (intern (format "%s-eval" bubbles--cl-environment)))
           ((functionp fn)))
      (funcall fn `(cl:eval (cl:read-from-string ,cl-text)))
    (message "Not connected.")))
```

You'll also want to add a Package-Requires section to your package header.

**Comment by hajovonta** [comment]
Hi @progfolio ,
thanks for your observation. I'll create a change with these.
Regarding the package-requires section, I'm not sure how to handle that it needs *either* SLIME or SLY?

**Comment by hajovonta** [comment]
Also there is a problem with the package name as I wasn't aware that there is already a M-x bubbles. Bummer

**Comment by hajovonta** [comment]
It seems SLY has a slightly differently behaving code walker which requires a different approach in injecting the CL code. I need one or two days, already have an idea how to handle it.

**Comment by hajovonta** [comment]
There is now a ticket in SLY to get better understanding of the problem: https://github.com/joaotavora/sly/issues/539

**Comment by hajovonta** [comment]
I removed SLY-related code from the package until it resolves.
Also changed the macros to functions.
Added Package-Header with 24.1 dependency.

Please review again.

**Comment by hajovonta** [comment]
I re-added SLY-related code, and the package was heavily refactored.
The interaction-mode (SLIME and SLY) is now customizable via the bubbles-interaction variable.
Functions that are intended to be called externally now check for selected interaction package to be installed and connected.

Also added a solution to each function that injects the (eval-in-emacs) function to CL side to be able to call it there interaction-agnostic.
Please review.

**Comment by riscy** [comment]
Thanks both (and @progfolio thank you so much for also looking at these, you have my heartfelt appreciation).  @hajovonta here's the latest from the linters, now that things are settled (except for the name, where bubbles.el is an Emacs builtin already):

`bubbles.el` with byte-compile using Emacs 28.1:
```
bubbles.el:38:1: Warning: defcustom for `bubbles-interaction' fails to specify
    containing group
bubbles.el:38:1: Warning: defcustom for `bubbles-interaction' fails to specify
    containing group
In end of data:
bubbles.el:82:4: Warning: the function `sly-eval-async' is not known to be
    defined.
bubbles.el:77:4: Warning: the function `slime-eval-async' is not known to be
    defined.
bubbles.el:72:23: Warning: the function `bubbles-precheck' is not known to be
    defined.
bubbles.el:66:4: Warning: the function `sly-eval' is not known to be defined.
bubbles.el:62:4: Warning: the function `slime-eval' is not known to be
    defined.
bubbles.el:53:54: Warning: the function `sly-connected-p' is not known to be
    defined.
bubbles.el:45:56: Warning: the function `slime-connected-p' is not known to be
    defined.
```
The slime/sly warnings are due to a missing dependency in your Package-Requires.

`bubbles.el` with checkdoc 0.6.2:
```
bubbles.el:39: First sentence should end with punctuation
bubbles.el:62: All variables and subroutines might as well have a documentation string
bubbles.el:66: All variables and subroutines might as well have a documentation string
bubbles.el:77: All variables and subroutines might as well have a documentation string
bubbles.el:82: All variables and subroutines might as well have a documentation string
bubbles.el:102: All variables and subroutines might as well have a documentation string
bubbles.el:113: All variables and subroutines might as well have a documentation string
bubbles.el:134: All variables and subroutines might as well have a documentation string
bubbles.el:144: All variables and subroutines might as well have a documentation string
```

`bubbles.el` with package-lint 20221003.1636:
```
1 issue found:
122:4: warning: Closing parens should not be wrapped onto new lines.
```

Package and license:
- Add a GPL-compatible LICENSE file to the repository

**Comment by hajovonta** [comment]
Hi @riscy , thanks for the review. I corrected most of the issues, and now neither checkdoc neither package-lint shows problems.
The issue with SLIME/SLY remains, however. I don't want to include these as dependency, because it's up to the user which of these is installed/used, and I think very few users will have both.

Can I somehow indicate in Package-Requires that at least one of them is needed?

Alternatively, I can hide the warnings by transforming the call into funcalls but I think it's a bit overkill for this purpose.

**Comment by hajovonta** [comment]
I'm in search for a new package name.

**Comment by riscy** [comment]
> Can I somehow indicate in Package-Requires that at least one of them is needed?

Unfortunately there's no "or" functionality.  `slime` is an order of magnitude more popular, so you may want to specialize, or build two packages that share a common core.  Alternatively you could depend on neither and throw runtime errors when both can't be found, but you should check out `declare-function` to do some bookkeeping on the optional functions.

> I'm in search for a new package name.

All good.  Standing by. :)

**Comment by hajovonta** [comment]
I considered the options, and I think the current one is the closest to what I would expect if I were an user of this package. If I make two packages, the user will need to decide which is to be used, which is basically an offloading of the problem to the users.
Currently, one can write code based on my package and not care about which integration-mode is installed - at the cost of a few byte-compilation warnings (and the missing functions won't be called at runtime anyway, because of the precheck)
Meanwhile I see many compilation warnings for packages already existing in MELPA, so not sure if this rigorousness is just for new packages or are those being corrected as well? Maybe I'm missing something.

**Comment by hajovonta** [comment]
I added a bunch of declare-function for the SLIME/SLY-related functions. If this is acceptable, I plan to rename the package to "glue" - there is no such package afaik :-)

**Comment by riscy** [comment]
That looks good to me.


These aren't really a blocker because the MELPA checklist doesn't care about `check-declare`, but your declare-function forms trip up `M-x check-declare-file`, e.g.:
```
bubbles.el:48:Warning (check-declare): said ‘slime-eval’ was defined in slime:
    Malformed declaration
bubbles.el:49:Warning (check-declare): said ‘slime-eval-async’ was defined in
    slime: Malformed declaration
bubbles.el:51:Warning (check-declare): said ‘sly-eval’ was defined in sly:
    Malformed declaration
bubbles.el:52:Warning (check-declare): said ‘sly-eval-async’ was defined in
    sly: Malformed declaration
bubbles.el:47:Warning (check-declare): said ‘slime-connected-p’ was defined in
    slime.el: file not found
bubbles.el:50:Warning (check-declare): said ‘sly-connected-p’ was defined in
    sly.el: file not found
```
Which can be fixed by (for example) changing
```elisp
(declare-function slime-eval "slime" sexp)
```
to
```elisp
(declare-function slime-eval "ext:slime.el" (sexp &optional package))
```
where the "ext:" prefix means to only check slime.el for `slime-eval` if the file is found.

**Comment by hajovonta** [comment]
Thank you.
I made the change, now check-declare-file doesn't complain. Changed the sly functions as well.
I guess I will need a new pull-request commit for the package name change (still haven't decided)

**Comment by hajovonta** [comment]
If you think all is OK please merge.

**Comment by riscy** [comment]
Thanks, it all checks out - I'd recommend changing your summary line from "Common Lisp interop" to "Common Lisp interop using sly or slime", *especially* since there is no explicit dependency on either; this might help keep people from being surprised by what the package actually needs to function.

I'd also recommend hitting M-q on your `;;; Commentary` paragraphs, just to let Emacs do the text justification for you.

Minor, but I look at `glue--precheck` and I can see that you're using `progn` unnnecessarily for the "else" part of your `if`s.  Consider:
```elisp
(defun glue--precheck ()
  "Checking whether the selected interaction package is installed/connected."
  (cond
   ((eq 'slime glue-interaction)
    (if (locate-library "slime")
        (if (slime-connected-p) 'slime (progn (message "Not connected.") nil))
      (message "SLIME is not installed.")
      nil))
   ((eq 'sly glue-interaction)
    (if (locate-library "sly")
        (if (sly-connected-p) 'sly (progn (message "Not connected.") nil))
      (message "SLY is not connected.")
      nil))))
```
Ultimately I think these are minor, though - merging.  And, welcome to MELPA. :)

**Comment by hajovonta** [comment]
Thanks! I changed the comments and the code according to your suggestions. I'll also add a readme with more examples soon.

**Pull request merged**
