### PR TITLE
Add recipe for bpftrace-mode

### PR DESCRIPTION
**Pull request by jgkamat**
### Brief summary of what the package does

bpftrace-mode is a tiny major mode for bpftrace files. bpftrace is a scripting language that aims to be a high-level interface to eBPF, and is found here:

https://github.com/iovisor/bpftrace

### Direct link to the package repository

https://gitlab.com/jgkamat/bpftrace-mode

### Your association with the package

Creator/maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
I gave this a quick try using the examples at the bpftrace repo and this works great for me.  Nice work.

Some very minor, miscellaneous comments/suggestions:
- 9: If possible, prefer `https://` to `http://`
- 23: If possible, prefer `https://` to `http://`
- 54: If possible, prefer `https://` to `http://`
- 39: Prefer `unless ...` to `when (not ...))`

**Comment by riscy** [comment]
Actually, I just noticed you could define the keymap using, e.g.
```elisp
(defvar bpftrace-mode-map (make-space-keymap)
  "Keymap for `bpftrace-mode' buffers.")
```
And there seems to be some issues with turning font-locking on and off when activating/deactivating the mode -- I'll keep looking into it to be a little more helpful.

**Comment by jgkamat** [comment]
Chris Rayner writes:

> Actually, I just noticed you could define the keymap using, e.g.
> ```elisp
> (defvar bpftrace-mode-map (make-space-keymap)
>   "Keymap for `bpftrace-mode' buffers.")
> ```

Good idea, fixed

> And there seems to be some issues with turning font-locking on and off when 
> activating/deactivating the mode -- I'll keep looking into it to be a little 
> more helpful.

I can't seem to reproduce when toggling between bpftrace-mode and 
fundamental-mode. Do you have some specific commands and/or files that are 
causing the issue for you? I am doing some weird and/or questionable things to 
steal c-mode's font lock settings and apply my own on-top of them, so that 
might be the issue. Since bpftrace syntax is almost exactly c (down to 
allowing includes), I would like to find a way to share the font-lock 
settings.

**Comment by riscy** [comment]
Sorry about the turnaround on that -- I tried reproducing on your latest code and it looks like I was mistaken.  This looks good to go!

**Pull request merged**
