### PR TITLE
Add nix-modeline recipe

### PR DESCRIPTION
**Pull request by unjordy**
### Brief summary of what the package does

`nix-modeline` is a global minor mode that shows how many [Nix](https://nixos.org/) package manager builds (or evaluations) are running in the background, updated live using the [entr](http://eradman.com/entrproject/) utility. This comes especially in handy if you combine Nix with an asynchronous project build tool like [lorri](https://github.com/target/lorri) or [nix-direnv](https://github.com/nix-community/nix-direnv), as is common for Nix core maintainers and heavy users, since without `nix-modeline` there is no obvious way to tell when a background build has completed. To my knowledge, this package does not replicate any functionality in an existing Emacs package.

### Direct link to the package repository

https://github.com/ocelot-project/nix-modeline

### Your association with the package

I created this package.

### Relevant communications with the upstream package maintainer

I deprived him of sleep until he agreed to finish this package and submit it to MELPA.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, this is interesting. I'm a nix-direnv user on MacOS and I couldn't get `nix-modeline-mode` to display anything but `?`, though the process is apparently running: it's hard to see what's happening because there isn't a dedicated buffer for the process, so I suspect you should just run it in a separate buffer (being careful to propagate any local process environment, e.g. using the `inheritenv` package) for debuggability. It's also questionable whether it's necessary to effectively embed a shell script, since the "watch a file and notify on a particular schedule" could just be accomplished in elisp using a timer: it would mean polling the sqlite db but the difference in raw efficiency would be minuscule.

**Comment by purcell** [comment]
(Probably one issue is not having `entr` installed globally. I suspect that should be avoided by using a `nix shell` command to automatically make `entr` available if the `.el` file isn't installed declaratively, which will always be the case when installed from MELPA.)

**Comment by unjordy** [comment]
Hey @purcell! Thank you for giving `nix-modeline` a try!

> it's hard to see what's happening because there isn't a dedicated buffer for the process, so I suspect you should just run it in a separate buffer (being careful to propagate any local process environment, e.g. using the inheritenv package) for debuggability.

I admittedly skimped on error handling for `nix-modeline`'s 1.0.0 release; I got a tad obsessed with writing an industrial-strength elisp logger that uses an Org mode output format (MELPA package for this hopefully soon) and pushed off error handling until I finished that package. The backend process for `nix-modeline` definitely deserves a dedicated buffer, probably with a size cap since `entr` gets a little bit spammy.

> (Probably one issue is not having `entr` installed globally. I suspect that should be avoided by using a `nix shell` command to automatically make `entr` available if the `.el` file isn't installed declaratively, which will always be the case when installed from MELPA.)

For this, I decided to go with [a pattern `nixpkgs` uses on occasion](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs-modes/cedille/default.nix) and rewrite `nix-modeline.el`'s global `entr` into a store-specific path on declarative install. My reasoning is that it makes the package potentially easier to compose with other Nix packages, and it gives the least surprising result on various types of Nix systems (full-declarative NixOS/`nix-darwin`, partially declarative, or fully imperative with everything pulled in via `nix-env`).

I do like the idea of pulling `nix-modeline`'s dependencies in automatically, but unfortunately `nix-shell` has some implementation issues that could prevent its use here: primarily, `nix-shell` instantiations get deleted from your store on `nix-collect-garbage` by default, which would cause a rebuild the user probably wouldn't expect (with corresponding high CPU usage, network reliance, and UI delay as a result of running `nix-modeline-mode`). It's possible to create a gcroot that would prevent that from happening (which is what [lorri and nix-direnv do](https://github.com/target/lorri#garbage-collection-roots)), but that would likely create a bit of complexity and quite a few edge cases. Nix flakes and `nix develop` would do well here since they cache evaluations, but flakes are an experimental feature at this point and very few Nix installs support them.

However, all of this might just be academic because --

> It's also questionable whether it's necessary to effectively embed a shell script, since the "watch a file and notify on a particular schedule" could just be accomplished in elisp using a timer: it would mean polling the sqlite db but the difference in raw efficiency would be minuscule.

I want to thank you for pointing this out, because it made me crack open the elisp manual and find out there's a [built-in `filenotify` library](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Notifications.html) that seems to implement all of `entr`'s functionality, and combined with `list-system-processes` and `process-attributes`, I think I can make a pure elisp version of `nix-modeline` with no runtime dependencies. There might be a couple caveats around portability and performance I'd have to work around, but I think the good far outweighs the bad. I'm starting work on that rewrite tonight for a 1.1.0 release of `nix-modeline`.

If you end up using `nix-modeline` and find it frustrating (or unexpectedly useful!), please drop by [ocelot-project/nix-modeline](https://github.com/ocelot-project/nix-modeline) and let me know!

**Comment by riscy** [comment]
Thanks @unjordly for the thorough explanation.  I was also unaware of filenotify.el -- given @purcell's feedback this looks like the best option.   All of the checklist look great given the current version of the code, but feel free to ping here when you've got an updated version to look at.

**Comment by unjordy** [comment]
@purcell @riscy I just finished up version 1.1.0, which replaces `entr` with a `filenotify` watcher implementation. On Linux, this entirely eliminates all of the package's non-Lisp runtime dependencies. macOS uses the `pgrep` included in the operating system to gather process information, since `process-attributes` on that platform is crippled.

I did some performance profiling with small `lorri` projects on NixOS with Spacemacs/gccEmacs and a couple Macs running Doom/gccEmacs, and efficiency seems really good. I did notice a little micro-stuttering on NixOS when `nix-modeline` updated during Nix builds, but I think that might be due to an unrelated issue. Since I can fine-tune when Emacs listens to `filenotify` events, I was also able to eliminate a couple of race conditions that existed in the `entr` implementation.

Let me know what you think!

**Comment by riscy** [comment]
I'm not a nix user (yet -- @purcell released a [video](https://www.youtube.com/watch?v=TbIHRHy7_JM) a while back that is on my 'reading' list) but to the best of my ability to understand, the rationale above looks good to me.

I have one small lint to report (nix-modeline.el#L147: No `format` required; `message` takes an f-string) but this looks good to merge to me.

**Pull request merged**
