### PR TITLE
Add `range-pattern` recipe

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
### Brief summary of what the package does

Range pattern for pcase.

### Direct link to the package repository

https://github.com/emilyseville7cfg-better-emacs/range-pattern/blob/main/range-pattern.el

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
I don't understand why in this PR and in #8338 CI fails but in #8337 passes.

**Comment by EmilySeville7cfg** [comment]
Should I add `Version` and other fields for all package files or not? For instance I [have](https://github.com/emilyseville7cfg-better-emacs/range-pattern/blob/main/tests.el) unit tests written here and am not sure whether I should copy "header" (big top level commentary) from `range-pattern.el`.

**Comment by alphapapa** [comment]
This `pcase` extension would be of very limited value being hosted as a package on MELPA.  It would be much more useful if it were part of Emacs itself.  I'd recommend proposing it in a patch on emacs-devel.

**Comment by EmilySeville7cfg** [comment]
@riscy, can you review this PR?

**Comment by riscy** [comment]
Hi @EmilySeville7cfg - apologies for not mentioning it here, but as you know my attention was over on #8338; do you want to close that PR while you iterate, and have me focus on this one?

(Due to limited personal bandwidth I try to limit myself to reviewing one PR per author per cycle.)

What do you think of @alphapapa's comment?  I tend to agree with the suggestion; and similar to my comment in #8338, you may want to build some general elisp experience before tackling library/language-feature code.

**Comment by EmilySeville7cfg** [comment]
@riscy, then I guess I propose it to Emacs itself. Maybe they incorporate it. But not now definitely, now I am working on another my project in Bash. 😁

**Pull request closed without merging**
