### PR TITLE
add markdown-changelog recipe

### PR DESCRIPTION
**Pull request by plandes**
### Brief summary of what the package does

Create and maintain [Keep a Changelog](http://keepachangelog.com/) changelogs,
which adheres to [Semantic Versioning](http://semver.org/).

### Direct link to the package repository

https://github.com/plandes/markdown-changelog

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
The description and documentation read more like an imperative command than an Emacs package that helps you do what it says.  :)

**Comment by plandes** [comment]
@alphapapa My terse and (lacking?) description matches your run-on. :). OK, are you asking me fill it out a little?  I'm more than happy to accommodate--just let me know what you want.

**Comment by riscy** [comment]
The code looks solid to me.  Some of your `;;; Commentary` text could might complement the current README (especially with regard to the entrypoints, `markdown-changelog-new` and
`markdown-changelog-add-release`) but not a blocker.

I'll just nag you for this one extremely minor `package-lint`, but it's an easy merge after that.

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
1 issue found:

1:0: warning: The package summary should not end with a period.

```

Other static checks:
- markdown-changelog.el#L32: Prefer `https` over `http` (if possible)
- markdown-changelog.el#L88: Prefer `https` over `http` (if possible)
- markdown-changelog.el#L89: Prefer `https` over `http` (if possible)

**Comment by plandes** [comment]
Re package lint: I was using 0.7 (commit 4c90df4919f7b96921a939b3bd88bedfd08d041e) and it didn't complain.  I've upgraded to the latest, replicated the issue and fixed it (thanks).

I have also added additional documentation as requested.  Thanks for pushing me to do that--I tend towards lethargy at times :)

**Comment by plandes** [comment]
Thanks @alphapapa and @riscy for making this easy.

**Pull request merged**
