### PR TITLE
replace ac-php

### PR DESCRIPTION
**Pull request by xcwen**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. A few little issues here:
- `(ac-php-core 1)` should be `(ac-php-core "1")` -- the quotes are mandatory
- The first line of `company-php.el` needs to be `;;; company-php.el --- company backend for php`, not the copyright line, and a similar change is needed in `ac-php-core.el`. Check the formatting using `M-: (package-buffer-info)`
- Please declare a package dependency on `(cl-lib "0.5")` where you're using `cl-lib`
- Instead of `(when (featurep 'company) (require 'company))`, you can just use `(require 'company)` now

Also, can you rebase this branch on our current `master`? The current version of this pull request has conflicts.

**Comment by xcwen** [comment]
thanks . i updated.

**Comment by xcwen** [comment]
please recheck my packages. thanks ^)^

**Comment by dunn** [comment]
There are still merge conflicts.

**Pull request closed without merging**
