### PR TITLE
Add recipe for pinyin-isearch

### PR DESCRIPTION
**Pull request by Anoncheg1**
### Brief summary of what the package does

Preview pull requests: https://github.com/melpa/melpa/pull/8859

Provide replacement for isearch-forward, isearch-backward.
Allow to search with pinyin in pinyin and a Chinese text and ignore diacritical tone marks for speed.

Difference with pinyin-search.el: we search in pinyin text and ignore tones.

> but I'm not too familiar with quail or setting input methods. Maybe you can point me to a reference for this, so I can learn more about this loading-in of quail/sisheng?

About (load "quail/sisheng"): I was unable to determinate reason of args-out-of-range error and just suppress it. I need only constants from this files. Emacs don't support partial loading, so there is not other way to do it cheaper.

All tests succeed: https://github.com/Anoncheg1/pinyin-isearch/actions/runs/

### Direct link to the package repository

https://github.com/Anoncheg1/pinyin-isearch

### Your association with the package

I am the maintainer.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used `M-x package-lint-current-buffer` to check package stylistic errors.

### CODE REVIEW

**Comment by Anoncheg1** [comment]
requre more work.

**Comment by riscy** [comment]
Thank you!  (Note it's not too bad to leave a PR open, especially while you're actively working on feedback on the package).  Here's the latest --

`pinyin-isearch.el` with byte-compile using Emacs 29.1:
```
pinyin-isearch.el:122:17: Warning: reference to free variable `sisheng-regexp'
In pinyin-isearch--get-position-first-syllable:
pinyin-isearch.el:147:41: Warning: reference to free variable `pinyin-isearch-syllable-table'
In pinyin-isearch-regexp-function:
pinyin-isearch.el:235:57: Warning: Unused lexical argument `lax'
In pinyin-isearch--sisheng-to-normal:
pinyin-isearch.el:275:19: Warning: reference to free variable `sisheng-regexp'
pinyin-isearch.el:279:42: Warning: reference to free variable `sisheng-vowel-table'
pinyin-isearch.el:280:11: Warning: assignment to free variable `input-vowel'
pinyin-isearch.el:295:13: Warning: reference to free variable `sisheng-syllable-table'
```

`pinyin-isearch.el` with package-lint 20231121.1907 and `package-lint-main-file` = "pinyin-isearch-pkg.el":
```
5 issues found:
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
155:8: warning: Closing parens should not be wrapped onto new lines.
250:9: warning: Closing parens should not be wrapped onto new lines.
310:0: warning: Closing parens should not be wrapped onto new lines.
317:11: warning: Closing parens should not be wrapped onto new lines.
```

`pinyin-isearch.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- The `;;; Commentary` for this file is much wider than 80 characters
- pinyin-isearch.el#L204: It's safer to sharp-quote function names; use `#'`
```

Package and license:
- pinyin-isearch-pkg.el -- consider excluding; MELPA can create one from pinyin-isearch.el

**Comment by Anoncheg1** [comment]
I fixed everything.

**Comment by Anoncheg1** [comment]
I prepare major update, that is why I close pull request for several days.

**Comment by Anoncheg1** [comment]
Major update have been made: search in hieroglyphs added.

**Comment by riscy** [comment]
Thank you for the update.  The latest is below -- it appears that pinyin-isearch-loaders.el is throwing a "wrong type argument" during byte compilation.  Is there some dependency that's needed?

`pinyin-isearch-hieroglyphs.el` with byte-compile using Emacs 29.1:
```
pinyin-isearch-hieroglyphs.el:55:2: Error: Wrong type argument: stringp, nil
```

`pinyin-isearch-hieroglyphs.el` with package-lint 20231121.1907 and `package-lint-main-file` = "pinyin-isearch.el":
```
13 issues found:
9:0: error: Package-Requires outside the main file have no effect.
87:14: warning: Closing parens should not be wrapped onto new lines.
88:12: warning: Closing parens should not be wrapped onto new lines.
89:10: warning: Closing parens should not be wrapped onto new lines.
132:27: error: You should depend on (emacs "28.1") or the compat package if you need `string-replace'.
135:6: warning: Closing parens should not be wrapped onto new lines.
191:12: warning: Closing parens should not be wrapped onto new lines.
193:10: warning: Closing parens should not be wrapped onto new lines.
230:25: warning: Closing parens should not be wrapped onto new lines.
260:24: warning: Closing parens should not be wrapped onto new lines.
267:0: warning: Closing parens should not be wrapped onto new lines.
282:23: warning: Closing parens should not be wrapped onto new lines.
296:0: warning: Closing parens should not be wrapped onto new lines.
```

`pinyin-isearch-hieroglyphs.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- pinyin-isearch-hieroglyphs.el#L206: It's safer to sharp-quote function names; use `#'`
- pinyin-isearch-hieroglyphs.el#L284: It's safer to sharp-quote function names; use `#'`
- pinyin-isearch-hieroglyphs.el#L221: It's safer to sharp-quote function names; use `#'`
- pinyin-isearch-hieroglyphs.el#L291: It's safer to sharp-quote function names; use `#'`
```

`pinyin-isearch-loaders.el` with package-lint 20231121.1907 and `package-lint-main-file` = "pinyin-isearch.el":
```
3 issues found:
9:0: error: Package-Requires outside the main file have no effect.
42:0: warning: Closing parens should not be wrapped onto new lines.
76:2: warning: Closing parens should not be wrapped onto new lines.
```

`pinyin-isearch-loaders.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- pinyin-isearch-loaders.el#L106: Loading a package should rarely add advice
```

`pinyin-isearch-pinyin.el` with byte-compile using Emacs 29.1:
```
pinyin-isearch-pinyin.el:51:2: Error: Wrong type argument: stringp, nil
```

`pinyin-isearch-pinyin.el` with package-lint 20231121.1907 and `package-lint-main-file` = "pinyin-isearch.el":
```
6 issues found:
9:0: error: Package-Requires outside the main file have no effect.
56:0: error: "sisheng-regexp" doesn't start with package's prefix "pinyin-isearch".
58:0: error: "sisheng-vowel-table" doesn't start with package's prefix "pinyin-isearch".
60:0: error: "sisheng-syllable-table" doesn't start with package's prefix "pinyin-isearch".
139:8: warning: Closing parens should not be wrapped onto new lines.
210:17: warning: Closing parens should not be wrapped onto new lines.
```

`pinyin-isearch.el` with byte-compile using Emacs 29.1:
```
pinyin-isearch.el:61:2: Error: Wrong type argument: stringp, nil
```

`pinyin-isearch.el` with package-lint 20231121.1907 and `package-lint-main-file` = "pinyin-isearch.el":
```
3 issues found:
1:0: warning: The package summary should not end with a period.
1:0: warning: The package summary should start with an uppercase letter or a digit.
152:2: warning: Closing parens should not be wrapped onto new lines.
```

`pinyin-isearch.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- pinyin-isearch.el#L193: It's safer to sharp-quote function names; use `#'`
- pinyin-isearch.el#L169: You can use `not` or `null`
- pinyin-isearch.el#L193: Merely loading a package should rarely add hooks
```

**Comment by Anoncheg1** [comment]
Everything fixed I hope.

**Comment by riscy** [comment]
Here's the latest --

`pinyin-isearch-chars.el` with byte-compile using Emacs 29.1:
```
pinyin-isearch-chars.el:136:15: Warning: reference to free variable `pinyin-isearch-strict'
In pinyin-isearch-chars--recursion:
pinyin-isearch-chars.el:175:38: Warning: reference to free variable `pinyin-isearch-strict'
In pinyin-isearch-chars--add-fallback:
pinyin-isearch-chars.el:239:17: Warning: reference to free variable `pinyin-isearch-strict'
In pinyin-isearch-chars-regexp-function:
pinyin-isearch-chars.el:327:56: Warning: reference to free variable `pinyin-isearch-strict'
In pinyin-isearch-chars-strict-regexp-function:
pinyin-isearch-chars.el:355:17: Warning: reference to free variable `pinyin-isearch-strict'
pinyin-isearch-chars.el:357:11: Warning: assignment to free variable `pinyin-isearch-strict'
```

`pinyin-isearch-chars.el` with package-lint 20240118.1725 and `package-lint-main-file` = "pinyin-isearch.el":
```
2 issues found:
9:0: error: Package-Requires outside the main file have no effect.
139:27: error: You should depend on (emacs "28.1") or the compat package if you need `string-replace'.
```

`pinyin-isearch-chars.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- pinyin-isearch-chars.el#L207: It's safer to sharp-quote function names; use `#'`
- pinyin-isearch-chars.el#L277: It's safer to sharp-quote function names; use `#'`
```

`pinyin-isearch-loaders.el` with package-lint 20240118.1725 and `package-lint-main-file` = "pinyin-isearch.el":
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

`pinyin-isearch-loaders.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- pinyin-isearch-loaders.el#L128: Loading a package should not add advice
```
See my comment below, but it strikes me that this package is doing a lot of (extra?) work at load-time, and we're advising (and then unadvising) packages at load-time to do this work, which is unusual and seems hacky.

`pinyin-isearch-pinyin.el` with byte-compile using Emacs 29.1:
```
pinyin-isearch-pinyin.el:277:16: Warning: reference to free variable `pinyin-isearch-strict'
In pinyin-isearch-pinyin-regexp-function:
pinyin-isearch-pinyin.el:294:54: Warning: reference to free variable `pinyin-isearch-strict'
```

`pinyin-isearch-pinyin.el` with package-lint 20240118.1725 and `package-lint-main-file` = "pinyin-isearch.el":
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

`pinyin-isearch.el` with byte-compile using Emacs 29.1:
```
pinyin-isearch.el: Warning: the function `isearch-toggle-strict' is not known to be defined.
pinyin-isearch.el: Warning: the function `isearch-toggle-characters' is not known to be defined.
pinyin-isearch.el: Warning: the function `isearch-toggle-pinyin' is not known to be defined.
```

`pinyin-isearch.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- pinyin-isearch.el#L172: You can use `not` or `null`
- pinyin-isearch.el#L221: This double negation can be collapsed (`not` aliases `null`)
- pinyin-isearch.el#L228: This double negation can be collapsed (`not` aliases `null`)
- pinyin-isearch.el#L193: Loading a package should rarely add hooks
```
Re: the adding of hooks, it's looking like perhaps a lot of the functionality supported by this package should be wrapped up in a togglable mode?

Stderr output while compiling/loading (again, is there perhaps a mode that should be toggled on before this work starts being done?)
```
Loading /nix/store/7z29qxfwv9y1zxv35m7qgkqkprj28wsg-emacs-29-1/share/emacs/29.1/lisp/leim/quail/PY.el.gz...
uncompressing PY.el.gz...
uncompressing PY.el.gz...done
Loading /nix/store/7z29qxfwv9y1zxv35m7qgkqkprj28wsg-emacs-29-1/share/emacs/29.1/lisp/leim/quail/Punct.el.gz...
uncompressing Punct.el.gz...
uncompressing Punct.el.gz...done
Loading /nix/store/7z29qxfwv9y1zxv35m7qgkqkprj28wsg-emacs-29-1/share/emacs/29.1/lisp/leim/quail/sisheng.el.gz...
uncompressing sisheng.el.gz...
uncompressing sisheng.el.gz...done
```

**Comment by Anoncheg1** [comment]
I separated loading dependencies to functions.

How to fix this?
`  9:0: error: Package-Requires outside the main file have no effect.
`
I don't know reason for this warning.
```
  pinyin-isearch.el:221:10: Warning: the function ‘isearch-toggle-strict’ is not
    known to be defined.
  pinyin-isearch.el:219:10: Warning: the function ‘isearch-toggle-characters’ is
    not known to be defined.
  pinyin-isearch.el:217:10: Warning: the function ‘isearch-toggle-pinyin’ is not
    known to be defined.
```

**Comment by riscy** [comment]
> How to fix this?

You can simply not list `Package-Requires` outside of the main file.  Also note that pinyin-isearch-loaders.el depends on emacs "27.2" but pinyin-isearch.el depends on emacs "28.1".

> I don't know reason for this warnings

You are using `isearch-define-mode-toggle` in `pinyin-isearch-activate-submodes` but after some experimenting I think this macro is meant to be used at the top level.

While I'm here, all of your `declare-function`s at the top of pinyin-isearch.el appear to be unnecessary e.g. because you correctly have `(require 'pinyin-isearch-pinyin)` (so you don't need to declare the functions in that module)

**Comment by Anoncheg1** [comment]
>> You can simply not list Package-Requires outside of the main file.
Without Package-Requires When I use M-x package-lint-current-buffer I have another error:
pinyin-isearch-chars.el:322:1: error: You should depend on (emacs "24.3") if you need `defvar-local'.
Please ignore Package-Requires in outside of the main file.
I use https://github.com/purcell/package-lint
Look at my https://github.com/Anoncheg1/pinyin-isearch/blob/main/run-tests.el

Everything else is fixed.

**Comment by riscy** [comment]
> Please, ignore Package-Requires outside of the main file.

It's "safe" for us to ignore these as requested, but only up to a point.  Your main file claims you require Emacs 28.1, but pinyin-isearch-loders.el claims you only require Emacs 27.2.  This isn't as big an issue as if you had it the other way around, but should still be fixed.

> When I use M-x package-lint-current-buffer I have another error

You aren't seeing the same errors because you haven't defined `package-lint-main-file`.  There is a WIP FAQ that addresses this -- https://github.com/melpa/melpa/blob/4caa9a03cad40d24484fce27fcfcf75b1d08e814/FAQ.md#how-do-i-make-package-lint-check-a-package-with-multiple-files -- but for now as long as you align the Emacs versions this looks good to go.

**Comment by Anoncheg1** [comment]
I fixed everything, thank you.

**Comment by riscy** [comment]
Thank you for your patience with all that - I'll merge this now.

**Pull request merged**
