### PR TITLE
Add recipe for iota

### PR DESCRIPTION
**Pull request by Mango0x45**
### Brief summary of what the package does

Iota is a package that allows you to perform simple- and easy enumerations.

### Direct link to the package repository

https://git.sr.ht/~mango/iota.el

### Your association with the package

I am the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass, and mostly this looks like minor/easy-to-fix stuff --

`iota.el` with byte-compile using Emacs 28.1:
```
iota.el:33:1: Warning: defgroup for `iota' fails to specify containing group
```

`iota.el` with package-lint 20230806.1331:
```
1 issue found:
33:0: error: Customization groups should specify a parent via `:group'.
```

**Comment by Mango0x45** [comment]
I’ve pushed a fix to my repo, should be good now

**Comment by riscy** [comment]
Checklist looks great now - thank you for that.

Have you had a chance to compare to these existing packages?
- https://melpa.org/#/shift-number
- https://melpa.org/#/evil-numbers (this depends on `evil` and so isn't as general as yours, but worth a look)

**Comment by Mango0x45** [comment]
Sorry for the delay, I was on vacation. I have taken a look at those two packages. The main difference is that those seem to be purely dedicated to simple increments and decrements of a number at point, something that is easy enough to do without a function. My main reason for making this package is that I very often find myself having to create sequences of ascending numbers. It's very often that I copy+paste a line many times and then need to go back and increment a number for each line or something. This package solves that problem.

**Comment by riscy** [comment]
No problem - I do MELPA PRs in a big batch so I'm never blocked (but it sometimes means I lose context).  I think your rationale is good.

I will merge this because you seem to have extended functionality, but also: have you tried out the Emacs builtin functionality where you write a list, e.g.
```md
- item 1
- item 2
- item 3
- item 4
```
and then call `M-x org-cycle-list-bullet`?  Or non-interactively, call `(org-cycle-list-bullet 2)` or `(org-cycle-list-bullet 3)` to go directly to a numeric list?  It appears you don't need to be in org-mode to do this.

Just something to be aware of, and maybe something worth mentioning to users in your `;;; Commentary`.

**Pull request merged**
