### PR TITLE
Create sticky-scroll-mode

### PR DESCRIPTION
**Pull request by jclasley**
### Brief summary of what the package does

Language agnostic sticky scrolling -- [see VSCode documentation](https://learn.microsoft.com/en-us/visualstudio/ide/editor-sticky-scroll?view=vs-2022)

### Direct link to the package repository

https://github.com/jclasley/sticky-scroll-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`sticky-scroll-mode.el` with byte-compile using Emacs 29.4:
```
sticky-scroll-mode.el:74:65: Warning: reference to free variable `sticky-scroll--buffer-alist'
sticky-scroll-mode.el:75:16: Warning: reference to free variable `sticky-scroll-quit'
```

`sticky-scroll-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- sticky-scroll-mode.el#L50: Customizable variables shouldn't be private
```

Package and license:
- sticky-scroll-mode.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by jclasley** [comment]
Thanks for the feedback!
Resolved comments and ran melpazoid against the `master` branch

**Comment by riscy** [comment]
Thank you!  Checklist looks great.  This looks like it was challenging (and fun) to implement in Emacs - kudos.

In terms of whether this package is yet in a finished state, I feel like one element missing here is the horizontal line that vsCode introduces to indicate folded code.  But this is minor.

More importantly, I'm also test driving this locally and notice at least one edge case where the "context" line disappears (and then reappears after some further vertical cursor movement).  I seem to be able to reproduce it consistently when stepping my cursor upward inside a function that has a blank line inside it.  Let me know if I can provide a little gif of this behavior or something.

Do you think these issues (especially the second one) are worth addressing before indexing this on MELPA?

**Comment by jclasley** [comment]
That is a known bug, and probably something I should address prior to integration. I’ll keep tinkering to preserve the context on blank lines! I’ll reach back out once I’ve got it. 

Thank you!

**Comment by riscy** [comment]
Yes, but as I reread my likely hastily written comment, I think the "finished state" qualifier should have gone next to the disappearing context-line issue.  I don't think the horizontal line is a make-or-break thing, but I did find it easy to get lost without it.  I apologize for the confusion - last weekend was a busy one.

Let me know when you're ready for another pass!

**Comment by riscy** [comment]
Thank you - I think that particular issue is fixed but I suspect (?) there may be some specific features of your own set up that is letting this work smoothly on your end.

For example, I'm not able to get the "sticky" effect at all while testing this on a vanilla Emacs instance, which does these big jumps as you scroll around.  I wonder whether you have certain assumptions about `scroll-conservatively` and/or `scroll-margin` - once I set `(setq scroll-conservatively 101 scroll-margin 0)` for instance this works better.

But even then, I only see the effect when scrolling up - not when scrolling down.

You may also want to see how your mode behaves in window-mode with `line-spacing` set to a nonzero value (in my own setup, I have it at 3, and I think that's causing some issues too; maybe you just want to set that variable to 0 when someone enables the mode, but be sure to restore it for them when they turn the mode off).

This is minor, but I think there are still debug messages echoing in the minibuffer as I move around.

**Comment by jclasley** [comment]
You're absolutely right! Thank you for taking the time to thoroughly test and give feedback. I'm fixing those issues and will have an updated branch for you soon. This is my first package, and I appreciate the feedback and patience.

**Comment by riscy** [comment]
Friendly ping :)

**Comment by jclasley** [comment]
I'm having trouble replicating the issue with `scroll-conservatively` and `scroll-margin`. Are you able to send me a file snippet and the settings in order to replicate it?

As far as `line-spacing` goes, I have a fix where I just set the `sticky-window`'s line spacing to `0`, but am holding out on it in order to get both that fix and the `scroll-conservatively` in the same one! Thanks for the nude.

**Comment by jclasley** [comment]
I think that the big jumps are behaving as expected -- sticky scroll only shows the higher context (indents `<n` where `n` is the point's current indentation) that are off-screen, so if your whole context is on screen it won't show anything. I tested it with `scroll-conservatively 0` and if the indentation is sufficiently large to be off screen it will show the sticky window. 

The latest branch has debugs removed! Thanks for the feedback :)

**Pull request merged**
