### PR TITLE
Add org-drawio for handling drawio image in orgmode

### PR DESCRIPTION
**Pull request by kimim**
### Brief summary of what the package does

Add a keyword #+drawio for handling drawio image in orgmode.

### Direct link to the package repository

https://github.com/kimim/org-drawio

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`org-drawio.el` with byte-compile using Emacs 29.1:
```
org-drawio.el:72:2: Error: Cannot open load file: No such file or directory, s
```
Looks like a missing `Package-requires` on `s` for this one - easy fix.

`org-drawio.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- org-drawio.el#L203: You should use `shell-quote-argument` on some of the arguments passed through here, for instance `dio-output-dir` is not quoted, but it's valid for a directory to contain shell control characters in its name.
- org-drawio.el#L232: Similar note here re `shell-quote-argument`
- org-drawio.el#L207: `concat` may be unneeded; `insert` can take multiple arguments
```

**Comment by kimim** [comment]
Thanks @riscy , I fixed the issue from both byte-compile and melpazoid.

**Comment by riscy** [comment]
I think there have been some more changes too; here's the latest on my end --

`org-drawio.el` with byte-compile using Emacs 29.1:
```
org-drawio.el:226:64: Warning: `next-line' is for interactive use only; use `forward-line' instead.
In end of data:
org-drawio.el:255:8: Warning: the function `w32-shell-execute' is not known to be defined.
org-drawio.el:172:23: Warning: the function `org-element-property' is not known to be defined.
```

Also in `org-drawio-open` your use of `(format " \"%s\"" path)` to try to quote the shell argument won't cut it - and in any case instead of writing your own "quoter" you should use `shell-quote-argument` on this argument.

**Comment by kimim** [comment]
Thanks @riscy, I fixed these issues now.

**Comment by riscy** [comment]
Thank you.  One last comment is you may want to change the line `;;; Change log` to read `;;; Change log:` and make it an actual section heading.  Functions like `(lm-commentary)` will then exclude this from your commentary -- the text description that shows up in the MELPA index.

**Pull request merged**
