### PR TITLE
Add recipe for typewriter-roll-mode

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
### Brief summary of what the package does

This minor mode attempts to remove distraction of seeing the previous lines of text while dumping an uninterrupted stream of thoughts, hence preventing focus jumping to revisions whether to handle typos, spacing or complete rewording and losing such a thought in the process.

### Direct link to the package repository

https://github.com/KeyWeeUsr/typewriter-roll-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

`typewriter-roll-mode.el` with checkdoc (0.6.2)

```
typewriter-roll-mode.el:79: First line is not a complete sentence
```

`typewriter-roll-mode.el` with package-lint (20230905.629)

```
1 issue found:

1:83: warning: You should depend on (emacs "24.1") if you need lexical-binding.
```

I'm seeing something like:

```elisp
(if (not (eq pos (current-column)))
    (typewriter-roll-scroll-up))
```

can simply be 

```elisp
(unless (eq pos (current-column))
  (typewriter-roll-scroll-up))
```

**Comment by riscy** [comment]
Thanks @jcs090218.

And thanks, @KeyWeeUsr.  This implementation actually works really well.  A couple bits of feedback --

- The summary line says "Minor mode to force writing on first line only" but the first thing that leaps to my mind is that this is a writing tool and that should probably appear somehow as part of your summary.  The fact that it's a minor mode is an implementation detail, I guess.  Maybe "Writing aid for distraction-free writing" would get me to a place of understanding more quickly.
- I also notice you're using `(inline)` for which the online help says "You don't need this" :) but what are you attempting to achieve with this?  You may want to see `defsubst` but I don't think you really need this either.
- `typewriter-roll-check` does not look like it should be interactive

**Comment by KeyWeeUsr** [comment]
@jcs090218 Thank you, fixed!
@riscy Thanks for the comments. About `(inline)` the attempt was to split to funcs yet keep it there, kind of an "alias" for simple functionality or grouping some logic away of larger funcs. Same in the other PRs. :)

**Comment by riscy** [comment]
> About (inline) the attempt was to split to funcs yet keep it there, kind of an "alias" for simple functionality or grouping some logic away of larger funcs.

Hmm, Is the intent just to tag these as helper or private functions?  If so, the accepted way to do this is to use double hyphenation.  E.g., instead of `typewriter-roll-mode-deactivate` name the function `typewriter-roll-mode--deactivate`.  This signals unambiguously to other Elisp devs that this function does not stand alone and is used by another function.  It also signals to other Elisp devs that, if they are going to depend on your package, they should not depend on this function, because it's a private implementation detail.  I'm sure this is what you want to be using instead of `(inline)`.

Re: this checkdoc --
```
typewriter-roll-mode.el:75: First line is not a complete sentence
```
Not a blocker, but what I'd do is just rephrase the sentence to fit on one line.  I don't need the docstring for a minor mode to tell me that it's a minor mode, for instance:
```elisp
(define-minor-mode typewriter-roll-mode
  "Justify and scroll text to keep a single line in focus."
  :lighter " typewriter-roll"
  (if typewriter-roll-mode
      (typewriter-roll-mode-activate)
    (typewriter-roll-mode-deactivate)))
```

**Comment by KeyWeeUsr** [comment]
@riscy Thanks, I guess it's better now.

**Comment by riscy** [comment]
Thank you! Merging this - and welcome to MELPA. :)

**Pull request merged**
