### PR TITLE
Add recipe for project-shells

### PR DESCRIPTION
**Pull request by hying-caritas**
### Brief summary of what the package does

Manage the shell buffers of each project.

### Direct link to the package repository

https://github.com/hying-caritas/project-shells.git

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR please check it https://github.com/hying-caritas/project-shells/pull/1

**Comment by syohex** [comment]
And there is no autoload cookie.

**Comment by hying-caritas** [comment]
Thanks for pointing out this.  I just added autoload cookies.

**Comment by purcell** [comment]
Thanks. Quick feedback:
- `project-shells-default-shell-name` should probably default to `shell-file-name`, not simply `"sh"`. (Also, `"/bin/sh"` is hard-coded later in the file.)
- The code looks like it will fail by default if projectile is not installed and loaded.
- Is it possible that you should be using `shell-quote-argument` instead of writing your own `project-shells--escape-sh`?
- Instead of the complex `project-shells-setup` code and custom variables holding various keybindings, a simpler and more idiomatic solution would be to create a small minor mode with the appropriate keymap, then enable that minor mode in the necessary buffers.

**Comment by hying-caritas** [comment]
Thanks for comments and pointing out the issues.

- project-shells-default-shell-name is just the name of the shell buffer, not the shell inferior program to run, in fact (shell) is called for shell buffers, so explicit-shell-file-name, (getenv "ESHELL"), or shell-file-name will be used.  Later "/bin/sh" is hard-coded to run in ansi-term, but I then run "exec" explicit-shell-name project-shells-term-args.  I do this because I want to use different command line arguments for shell buffer and terminal buffer.

- Thanks to point this out.  Will check symbol binding and default to empty project name and home directory when the project related function definition is nil.

- Will change the code to use shell-quote-argument

- Will create a small minor mode.

**Comment by purcell** [comment]
> project-shells-default-shell-name is just the name of the shell buffer, not the shell inferior program to run

Oh, okay - sorry!

**Comment by hying-caritas** [comment]
I have changed the code to address your comments.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
