### PR TITLE
Add undo-fu

### PR DESCRIPTION
**Pull request by ideasman42**
### Brief summary of what the package does

Helpers to expose undo/redo functionality on top of Emacs own undo commands
*(without modifying the internal undo data which tends to be buggy, [example](https://www.reddit.com/r/emacs/comments/85t95p/undo_tree_unrecognized_entry_in_undo_list/))*.

- Undo marks the initial step when activated.
- Redo will not redo past this initial undo action.
- Redo will not undo if the last action in the undo stack is not an undo.

These constraints can be disabled temporarily by pressing Ctrl-G.

### Direct link to the package repository

https://gitlab.com/ideasman42/emacs-undo-fu

### Your association with the package

Author/Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by manuel-uberti** [comment]
Neat idea. At a first (quick) try it works as expected, so thanks for this package.

One minor note: are the newlines [here](https://gitlab.com/ideasman42/emacs-undo-gofer/blob/master/undo-gofer.el#L98) and [here](https://gitlab.com/ideasman42/emacs-undo-gofer/blob/master/undo-gofer.el#L160) really necessary?

**Comment by manuel-uberti** [comment]
Oh, another note: you have two `(provide 'undo-gofer)` at the end.

**Comment by ideasman42** [comment]
Thanks for checking this out. Corrected double provide, the parens on own line is the code-style I prefer, where every block is indented by 2, and multi-line blocks never proceed single line blocks, While it's a little odd, It makes it easy to know how deep blocks are nested and works well with auto-formatting.

**Comment by riscy** [comment]
Just quickly passing through --
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
undo-tastic.el:82:1:Warning: Unused lexical argument `list-to-find'
undo-tastic.el:109:1:Warning: Unused lexical variable `steps'
```
Usually these are easy to fix (prefix with `_`) but especially in the case of `steps` it seems like that variable wasn't meant to be ignored?

**Comment by ideasman42** [comment]
@riscy thanks, both should have been used. corrected.

**Comment by ideasman42** [comment]
Anything I can do to help get this included?

I posted an [RFC to reddit](https://www.reddit.com/r/emacs/comments/eab4ry) and got some positive responses.

**Comment by Silex** [comment]
@ideasman42: @riscy has computer problems, but there's nothing that seem to prevent your package from being included. Just be a bit patient :wink:

**Comment by riscy** [comment]
Very much appreciate seeing the RFC on Emacs, btw (I would encourage everyone to do this).  Thanks for your patience -- this looks good to go!

**Comment by Silex** [comment]
Just wanted everyone to be aware of this interesting undo-tree update that explains the bug: http://www.dr-qubit.org/Lost_undo-tree_history.html

**Pull request merged**
