### PR TITLE
Add recipe scala-repl

### PR DESCRIPTION
**Pull request by sheepduke**
### Brief summary of what the package does

This package provides functions to perform REPL-driven development for Scala programming language.

Currently it supports the following features:

1. Automatically detect project root, trigger a REPL session and attach to it.
2. Evaluate source code in the REPL session that the current buffer is attached to.
3. Customize commands to run for SBT/Mill projects or non-project files.
4. Run ad-hoc REPL sessions with custom commands and manually attach to/detach from it.
5. Support multiple REPL sessions for different projects/ad-hoc files.

Note that the evaluation functionality is restricted by corresponding Scala REPL.

Also note that this package *might* work on Emacs < 29.1, but it is not guaranteed. You are welcome to open an issue on the GitHub page and let know if it does.

This package does not define any minor mode. You are free to bind its functions in scala-mode or scala-ts-mode however you like.

### Direct link to the package repository

https://github.com/sheepduke/scala-repl.el

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`scala-repl.el` with byte-compile using Emacs 29.2:
```
scala-repl.el:97:6: Warning: `comint-run' is for interactive use only; use `make-comint' instead.
In scala-repl--get-buffer-name:
scala-repl.el:212:3: Warning: reference to free variable `scala-repl-buffer-name'
In scala-repl--ensure-project-root:
scala-repl.el:227:3: Warning: reference to free variable `scala-repl-project-type-root'
In end of data:
scala-repl.el:191:8: Warning: the function `comint-send-string' is not known to be defined.
scala-repl.el:128:8: Warning: the function `comint-clear-buffer' is not known to be defined.
scala-repl.el:90:27: Warning: the function `cl-position' might not be defined at runtime.
```

`scala-repl.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- scala-repl.el#L183: It's safer to sharp-quote function names; use `#'`
- scala-repl.el#L82: It's safer to sharp-quote function names; use `#'`
```

Package and license:
- scala-repl-pkg.el -- consider excluding; MELPA can create one from scala-repl.el
- GNU General Public License v3.0 (via API)

**Comment by sheepduke** [comment]
Hi @riscy,

Thank you for help reviewing this. I have fixed the compilation and melpazoid warnings.

Could you please help check it again?

**Comment by riscy** [comment]
Thanks!  Here's the latest I'm seeing --

`scala-repl.el` with byte-compile using Emacs 29.3:
```
scala-repl.el:200:8: Warning: the function `comint-send-string' is not known to be defined.
scala-repl.el:136:8: Warning: the function `comint-clear-buffer' is not known to be defined.
scala-repl.el:96:27: Warning: the function `cl-position' might not be defined at runtime.
```
I think we need a `(require 'comint)` and  `(require 'cl-lib)` for these.

Package and license:
- scala-repl-pkg.el -- consider excluding; MELPA can create one from scala-repl.el.  I mentioned this already but if you are happy maintaining the information in both places, I surely don't mind.

**Comment by riscy** [comment]
Thank you!  This is not a blocker but I thought I'd mention it since your checkdoc is otherwise immaculate --

`scala-repl.el` with checkdoc 0.6.2 (fix *within reason*):
```
scala-repl.el:184: Argument `no-switch-p' should appear (as NO-SWITCH-P) in the doc string
```

Hitting merge now.  And, welcome to MELPA. :)

**Pull request merged**
