### PR TITLE
Add recipe for helm-tree-sitter

### PR DESCRIPTION
**Pull request by Giedriusj1**
### Brief summary of what the package does

Helm interface to tree-sitter. Works very similar to helm-semantic, but tree-sitter is used for getting the AST. Currently understands C, C++, Rust and Python languages, but I'm planning on expanding this in the future.

### Direct link to the package repository

https://github.com/Giedriusj1/helm-tree-sitter

### Your association with the package

Creator, maintainer and a user

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  As a small fyi, it looks like tree-sitter unfortunately makes network connections when it's loaded (for the first time?), so I had to enable Emacs to make network connections in order to compile your package.

After that I caught one byte-compile warning:

`helm-tree-sitter-core.el` with checkdoc 0.6.2:
```
helm-tree-sitter-core.el:38: Lisp symbol `major-mode' should appear in quotes
```

And you should be aware that Package-Requires outside the main file have no effect.

One last comment is that MELPA prefers to track the default branch whenever possible (generally we discourage the use of `:branch` unless it's necessary); if you want to cut releases, you can use versions tags which will be hosted on https://stable.melpa.org.  But not everyone likes to use MELPA stable, so there's some flexibility here.

**Comment by Giedriusj1** [comment]
Thanks for looking at this!

You are correct, the first time you load tree-sitter it has to fetch the appropriate binaries. This is because the actual syntax parsing is done within a loadable module. I agree that it's not the most elegant solution, but I guess there is no other way to deal with loadable modules, since you need a new set for each architecture.

Regarding the redundant requires - I've put them in to make byte compiler happy when compiling the package. I do understand that normally the main file would be loaded first, thus loading all of the required dependencies, but I guess while byte compiling the package it's not clear to the compiler that the main file would be loaded firsts :thinking:  Anyways - I've removed those additional requires if you are happy with that.

I've also addressed the other issues raised :)

**Comment by riscy** [comment]
Great, I'm able to run the checks cleanly -- I think a few more issues have revealed themselves that I didn't catch in the first round:

`helm-tree-sitter-c.el` with byte-compile using Emacs 27.1:
```
helm-tree-sitter-c.el:197:1:Warning: the following functions are not known to
    be defined: helm-tree-sitter-core-elem-p,
    helm-tree-sitter-utils-node-children-to-alist,
    helm-tree-sitter-core-elem-node, helm-tree-sitter-utils-get-node-text,
    helm-tree-sitter-utils-append-space-if-not-empty,
    helm-tree-sitter-utils-strip-newlines, tsc-node-p, tsc-get-parent,
    helm-tree-sitter-utils-prepend-depth-if-needed
```

`helm-tree-sitter-core.el` with byte-compile using Emacs 27.1:
```
helm-tree-sitter-core.el:39:73:Warning: reference to free variable
    `helm-tree-sitter-producer-mode-maps'
In end of data:
helm-tree-sitter-core.el:85:1:Warning: the following functions are not known
    to be defined: tsc-node-type, tsc-node-text, tsc-node-start-position,
    tsc-count-named-children, tsc-get-nth-named-child
```

`helm-tree-sitter-cpp.el` with byte-compile using Emacs 27.1:
```
helm-tree-sitter-cpp.el:125:1:Warning: the following functions are not known
    to be defined: helm-tree-sitter-utils-node-children-to-alist,
    helm-tree-sitter-utils-get-node-text-or-nil,
    helm-tree-sitter-utils-get-node-text,
    helm-tree-sitter-utils-prepend-depth-if-needed
```

I'm a bit behind on MELPA PR's so I haven't looked too closely at those, but feel free to ping if any questions.

**Comment by Giedriusj1** [comment]
Okay, all of the byte compile issues should be fixed now!

**Comment by riscy** [comment]
Thanks!  Everything checks out here and this looks useful.  I just noticed `:candidate-number-limit 9999` which seems a little arbitrary to me (why isn't this at least a `defconst`?) but that's not a blocker.  Merging -- and welcome to MELPA. :)

**Comment by Giedriusj1** [comment]
Awesome. Thanks! :)

**Pull request merged**
