### PR TITLE
Add le-gpt

### PR DESCRIPTION
**Pull request by AnselmC**
### Brief summary of what the package does

It's a fork of [gpt.el](https://github.com/stuhlmueller/gpt.el) that adds more advanced gpt integration.
I had started contributing to the original package, but the last comment on my latest PR was made about a month ago.
Since I want to actively add new features, this turn-around time led me to create a proper fork.

This fork already adds many new features, including project awareness, completion at point, and transforming selections.

### Direct link to the package repository

https://github.com/AnselmC/le-gpt.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed** (I think?)

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!

> It's a fork of [gpt.el](https://github.com/stuhlmueller/gpt.el) that adds more advanced gpt integration.

Per CONTRIBUTING.org, we consider forks in only exceptional circumstances.  However, it was wisely suggested to me that the LLM space is highly dynamic right now and I don't want to stymie creativity.  And maybe you are calling this a "fork" but intending to go in a completely different direction.

Alternatively, perhaps @stuhlmueller can comment here on whether it would be possible to give you maintainer rights in the original repository.  I haven't looked at any of the PRs you've proposed, but in that case we wouldn't need a fork and gpt.el development velocity might be able to proceed at a pace that at least one of its contributors would like to see.

In the meantime -

⸺ `le-gpt-chat.el` with byte-compile using Emacs 29.4:
```
le-gpt-chat.el:214:13: Warning: reference to free variable `le-gpt-chat-mode-map'
In end of data:
le-gpt-chat.el:69:8: Warning: the function `le-gpt-chat-mode' is not known to be defined.
```

⸺ `le-gpt-project.el` with byte-compile using Emacs 29.4:
```
le-gpt-project.el:112:6: Warning: the function `projectile-project-files' is not known to be defined.
```

⸺ `le-gpt-chat.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- le-gpt-chat.el#L98: It's safer to sharp-quote function names; use `#'`
- le-gpt-chat.el#L89: It's safer to sharp-quote function names; use `#'`
- le-gpt-chat.el#L129: You may want to consider `(derived-mode-p 'xyz)`
- le-gpt-chat.el#L166: You may want to consider `(derived-mode-p 'xyz)`
- le-gpt-chat.el#L214: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- le-gpt-chat.el#L215: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- le-gpt-chat.el#L216: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- le-gpt-chat.el#L217: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
```

⸺ Package and license:
- le-gpt-chat.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- le-gpt-completion.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- le-gpt-core.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- le-gpt-project.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- le-gpt-transform.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by riscy** [comment]
> Sorry that I missed the part on not accepting forks, feel free to close this PR.

That's why I said 'maybe you are calling this a "fork" but intending to go in a completely different direction'; I think largely when we talk about forks in MELPA we're talking about someone who is maintaining a forked version of an original package but still setting out to do the same thing.

If you're going a completely different direction, you shouldn't brand yourself as a gpt.el fork (even though this is how it may have started) but as a completely new package that acknowledges gpt.el for a lot of its underlying code.

> markdown-mode

You have the `require` on markdown-mode, but you also need to add markdown-mode to your `Package-Requires` in your main file (le-gpt.el), otherwise it won't be installed by melpazoid and more importantly won't be detected as a dependency during package installation.

That being said, if it's not truly a dependency of your package, you may want to make it optional and use e.g. `(when (featurep 'markdown-mode) ...` and/or `declare-function` bookkeeping to pacify the byte-compiler.

**Comment by AnselmC** [comment]
Ok, thanks for the pointers! I added `markdown-mode` to `Package-Requires`, and `melpazoid` is now passing.
I've also removed the "fork"-lingo from the package description on GitHub, though I kept it in the readme and `Commentary` sections - I want to make sure the attribution is clear.

Hope this works for you!

**Comment by riscy** [comment]
Thank you and sorry about the verbosity - I guess I was also trying to relay my own opinion about why MELPA would be touchy with forks and why that might not apply here.  I'm not trying to redefine the word fork, even though that's how it reads. :)

I'll merge this now.  Best of luck on the LLM adventure, and welcome to MELPA. :)

**Pull request merged**
