### PR TITLE
Add tab-bar-buffers

### PR DESCRIPTION
**Pull request by ajrosen**
### Brief summary of what the package does

This package piggy-backs on `tab-bar-mode' to implement a simple buffer manager.  Instead of managing tabs it manages buffers.

### Direct link to the package repository

https://github.com/ajrosen/tab-bar-buffers

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for your patience!  Quick first pass --

`tab-bar-buffers.el` with package-lint 20220607.738:
```
21 issues found:
105:0: error: "tab-bar-buffer-name-format" doesn't start with package's prefix "tab-bar-buffers".
118:0: error: "tab-bar-buffer-current-buffer-number" doesn't start with package's prefix "tab-bar-buffers".
125:0: error: "interesting-buffer-p" doesn't start with package's prefix "tab-bar-buffers".
138:0: error: "interesting-buffers" doesn't start with package's prefix "tab-bar-buffers".
148:0: error: "interesting-buffers--sort" doesn't start with package's prefix "tab-bar-buffers".
153:0: error: "buffer-name-lessp" doesn't start with package's prefix "tab-bar-buffers".
160:0: error: "switch-to-buffer-by-number" doesn't start with package's prefix "tab-bar-buffers".
178:0: error: "tab-bar-buffer-new-buffer" doesn't start with package's prefix "tab-bar-buffers".
185:0: error: "tab-bar-buffer-select-buffer" doesn't start with package's prefix "tab-bar-buffers".
197:0: error: "tab-bar-buffer-next" doesn't start with package's prefix "tab-bar-buffers".
207:0: error: "tab-bar-buffer-prev" doesn't start with package's prefix "tab-bar-buffers".
216:0: error: "tab-bar-buffer-recent" doesn't start with package's prefix "tab-bar-buffers".
223:0: error: "tab-bar-buffer-last" doesn't start with package's prefix "tab-bar-buffers".
230:0: error: "tab-bar-buffer-close-buffer" doesn't start with package's prefix "tab-bar-buffers".
239:0: error: Aliases should start with the package's prefix "tab-bar-buffers".
240:0: error: Aliases should start with the package's prefix "tab-bar-buffers".
241:0: error: Aliases should start with the package's prefix "tab-bar-buffers".
242:0: error: Aliases should start with the package's prefix "tab-bar-buffers".
243:0: error: Aliases should start with the package's prefix "tab-bar-buffers".
244:0: error: Aliases should start with the package's prefix "tab-bar-buffers".
245:0: error: Aliases should start with the package's prefix "tab-bar-buffers".
```
The defaliases should almost certainly be avoided, since they're automatically shadowing existing builtin aliases.

Regarding the repo itself, add a LICENSE file that GitHub can detect (e.g. no markup) if possible -- See: https://github.com/licensee/licensee

**Comment by ajrosen** [comment]
I've added a LICENSE file.

I'm using `defalias` for all of the `tab-bar` functions that `tab-bar--define-keys` creates bindings for.  

The alternative was to create new, nearly identical versions of `tab-bar-select-tab-modifiers`, `tab-bar--define-keys`, and `tab-bar--undefine-keys`.

**Comment by riscy** [comment]
I see what you're saying, but this sort of runtime modification should happen as a result of the user explicitly calling a function or toggling a mode off or on, e.g. as a [minor mode](https://www.gnu.org/software/emacs/manual/html_node/elisp/Minor-Modes.html).  In this case you could wrap these functions in `:around` advice as part of enabling `tab-bar-buffers-mode`, and then remove that advice when the mode is turned off again.

**Comment by ajrosen** [comment]
With a little help from ``fset`` I'm properly restoring the ``tab-bar-mode`` key bindings when disabling ``tab-bar-buffers-mode``.  And the key bindings are redefined only when the mode is enabled.

Thanks!

**Comment by riscy** [comment]
I think aliasing functions to capture keybindings is still the wrong way to go about this.  The implementation at the time of this writing is (still) creating aliases outside of its namespace, and I think this is exacerbated by using `fset` which introduces even more objects outside of this package's namespace (e.g. imagine if someone submitted a package called tbb).   Have you considered using `:around` advice?

There are a couple of other cases where you're outside of your namespace (your package is called tab-bar-buffers.el but there are functions like `interesting-buffer-p`, `tab-bar-buffer-name-format`, etc.)  Package-lint should give you the full listing:

`tab-bar-buffers.el` with package-lint 20220607.738:
```
21 issues found:
111:0: error: "tab-bar-buffer-name-format" doesn't start with package's prefix "tab-bar-buffers".
124:0: error: "tab-bar-buffer-current-buffer-number" doesn't start with package's prefix "tab-bar-buffers".
131:0: error: "interesting-buffer-p" doesn't start with package's prefix "tab-bar-buffers".
144:0: error: "interesting-buffers" doesn't start with package's prefix "tab-bar-buffers".
154:0: error: "interesting-buffers--sort" doesn't start with package's prefix "tab-bar-buffers".
159:0: error: "buffer-name-lessp" doesn't start with package's prefix "tab-bar-buffers".
166:0: error: "switch-to-buffer-by-number" doesn't start with package's prefix "tab-bar-buffers".
184:0: error: "tab-bar-buffer-new-buffer" doesn't start with package's prefix "tab-bar-buffers".
191:0: error: "tab-bar-buffer-select-buffer" doesn't start with package's prefix "tab-bar-buffers".
203:0: error: "tab-bar-buffer-next" doesn't start with package's prefix "tab-bar-buffers".
213:0: error: "tab-bar-buffer-prev" doesn't start with package's prefix "tab-bar-buffers".
222:0: error: "tab-bar-buffer-recent" doesn't start with package's prefix "tab-bar-buffers".
229:0: error: "tab-bar-buffer-last" doesn't start with package's prefix "tab-bar-buffers".
236:0: error: "tab-bar-buffer-close-buffer" doesn't start with package's prefix "tab-bar-buffers".
258:2: error: Aliases should start with the package's prefix "tab-bar-buffers".
259:2: error: Aliases should start with the package's prefix "tab-bar-buffers".
260:2: error: Aliases should start with the package's prefix "tab-bar-buffers".
261:2: error: Aliases should start with the package's prefix "tab-bar-buffers".
262:2: error: Aliases should start with the package's prefix "tab-bar-buffers".
263:2: error: Aliases should start with the package's prefix "tab-bar-buffers".
264:2: error: Aliases should start with the package's prefix "tab-bar-buffers".
```

**Comment by ajrosen** [comment]
Light dawns on Marblehead!  I hadn't realized :around could skip the advised function entirely.  And I cleaned up all the prefixes...

**Comment by riscy** [comment]
Thanks, that puts the checklist behind us.

I found this package a little bit hard to understand at first, so I tried to write up my own description of it -- let me know if this is accurate (and maybe you could revise your Commentary to help unfamiliar people like me).  This package (1) provides basic functions for switching buffers.  Then it assumes the user has keybindings set up for switching tabs, but it (2) co-opts those existing keybindings to call these functions via a minor mode.  Users can toggle the co-opted keybindings on and off to switch buffers or switch tabs.

This look good to merge, though -- and welcome to MELPA. :)

**Pull request merged**
