### PR TITLE
New: hack-time-mode

### PR DESCRIPTION
**Pull request by marcowahl**
### Brief summary of what the package does

Fork time (to some extend) 

### Direct link to the package repository

https://gitlab.com/marcowahl/hack-time-mode

### Your association with the package

maintainer+contributor+enthusiastic user

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [ x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly

Warnings

- [x ] `M-x checkdoc` is happy with my docstrings
- [ x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Some functions are undefined, please check function names by byte-compiling or using all features of this package
- You should load `org.el` for using `org-read-data`. It is not an autoload function.

**Comment by marcowahl** [comment]
Thanks for your suggestions!

- AFAICT hack-time-mode now also byte-compiles cleanly. 
- And I put a (require 'org) immediately in front of the call to org-read-data.

**Comment by purcell** [comment]
I'll go ahead and merge this, but some feedback:

- For `org-read-data`, don't `(require 'org)`: instead, use `declare-function` at the top level.
- Consider making `target-date` a parameter to `hack-time-mode-set-current-time`: you can then change the `interactive` form to `(interactive (list (org-read-date)))` and everything will work the same as currently, but more flexibly.
- Note that your `prologue ends here` is currently part of the `Commentary` section, and will be included in the extracted documentation for the package which is displayed on the MELPA page and via the Emacs package list buffer when pressing `?`.
- Don't indent the subsequent lines in the minor mode docstring

**Comment by marcowahl** [comment]
Thanks for your feedback!  I think I fixed these issues.

Best regards and thanks for including the package into melpa.

**Pull request merged**
