### PR TITLE
add recipe for tester package

### PR DESCRIPTION
**Pull request by tonini**
Hi

I would like to add a recipe for my `tester.el` package.

Cheers

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Is there any overlap here with [test-case-mode](https://github.com/ieure/test-case-mode), which has been around for many years?

I looked through the code and the README, and it still wasn't really clear what this does. The examples show how to do some sort of configuration, but afaict they don't show how to actually run tests. The configuration looks a little weird to me -- for example, the ruby example will do exactly the same thing in every ruby buffer. It feels like there should just be an `alist` variable somewhere which maps `ruby-mode` to the corresponding sessions.

Also, hash tables are an odd choice for the `tester--storage` data: more idiomatic would be an `alist`, `plist`, or a `cl-lib` `defstruct`.

**Comment by tonini** [comment]
Hi, 

Excuse the late responds, the summer and the lake hold me a bit back from the desk. :smile: 

 > Is there any overlap here with test-case-mode, which has been around for many years?

I think not, with `tester` I just add two functions which act as interface to call the initialized test functions the user registered with `(tester-init-test-run FUNCTION TEST-FILE-REGEX)`. 

The idea behind is that you can register any kind of function which should be run in a specific mode and test file when `tester-run-test-file` is called. Just make it possible to always just need to call one function to run the test in the current context.

For the implementation specific feedback, I fully appreciate your feedback and would work on that and refine the codebase.

**Comment by purcell** [comment]
Okay. Right now it's not possible IMO to look at the `.el` file on its own and know how to use it, so you should include a more complete `Commentary:` section, perhaps just copying across some of the info and examples from the README.

**Comment by milkypostman** [comment]
hey @tonini any word on this?

**Comment by tarsius** [comment]
@tonini here's a friendly ping for you.

**Comment by tarsius** [comment]
Please reopen if you decide to work on this again.

**Pull request closed without merging**
