### PR TITLE
add recipe sclang for SuperCollider.

### PR DESCRIPTION
**Pull request by stardiviner**
### Brief summary of what the package does

sclang for Emacs from SuperCollider.

### Direct link to the package repository

https://github.com/supercollider/supercollider

### Your association with the package

Like this package.

### Relevant communications with the upstream package maintainer
None

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by stardiviner** [comment]
I think the section `:files ()` might have problem. But I don't know how to write it, so I post it here at first, if someone knows how to write it, please let me know.

**Comment by syohex** [comment]
Please read https://github.com/melpa/melpa#recipe-format .

BTW `cmake . && make` must be run before installing this package. How is this issue resolved this problem ?

**Comment by stardiviner** [comment]
@syohex I updated my commit, is it correct?
Maybe I can add into recipe REAMDE to let user know how to do the `cmake && make` step?

**Comment by syohex** [comment]
> I updated my commit, is it correct?

It looks no update.

**Comment by stardiviner** [comment]
Sorry I have not force updated branch. Now it's updated.

**Comment by syohex** [comment]
- What is `sc` ? Did you mean `editors/scel/sc/` ?
- `sclang-vars.el.in` is not installed. It is necessary to generate `scalang-vars.el` by `cmake`

**Comment by stardiviner** [comment]
- Yes, `sc` is `editors/scel/sc/`. Do we need it?
- I checked out the file `sclang-vars.el` content, it did need `cmake`. Bad news.

What is your suggestion?

**Comment by syohex** [comment]
> Yes, sc is editors/scel/sc/. Do we need it?

https://github.com/stardiviner/melpa/blob/7a863f6a6f74234fb06128ff3a7ef7147623d018/recipes/sclang#L4

You wrote `"sc"`. This means "sc" at top directory.  There is no such directory. Did you check whether recipe is correct by `make recipes/your_recipe_name` and generated tar file contains all necessary files ? If not, please don't check checkbox in PR template.

**Comment by stardiviner** [comment]
Closed because can't fix `sclang-vars.el.in` problem.

**Pull request closed without merging**
