### PR TITLE
Add magit-lfs

### PR DESCRIPTION
**Pull request by Ailrun**
### Brief summary of what the package does

Integrate git-lfs with magit

### Direct link to the package repository

https://github.com/ailrun/magit-lfs

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- Please just use the default file list (ie. remove `:files` completely). We wouldn't normally include files like `CHANGES` in the built packages.
- Don't depend on a snapshot version of `magit`: use the latest MELPA Stable version instead.
- The custom group description for `magit-lfs` is empty.

**Comment by Ailrun** [comment]
@purcell 

I fix it. Thank you for feedback.

Anyway, I can't access melpa-stable version of `magit` via emacs and [melpa-stable](https://stable.melpa.org/) page with my firefox.
So I just use latest release version of `magit` in [magit release page](https://github.com/magit/magit/releases).

Is there any way to solve these problems?

**Comment by purcell** [comment]
It looks like the disk is full on the MELPA Stable server, sorry. I’ll look into that and get things working again.

**Comment by purcell** [comment]
Hey @milkypostman, don't suppose you can see what's filled up the MELPA Stable server. It has 11GB in "working", just like the main MELPA server, and nothing else is obviously huge, so I'm unsure how it has filled 20GB, or how to fix this. Can you bump up the disk size maybe?

**Comment by tarsius** [comment]
* You are using but not requiring `dash`. (Okay so `magit` does that for you, but since it is a third-party package you should still make this explicit. I for one like to be able to immediately tell if a library uses thing s like `dash` and `cl-lib`.)
* It seems unnecessary to put some stuff into a separate `magit-lfs-core.el`.

**Comment by Ailrun** [comment]
@tarsius I update it.

**Comment by tarsius** [comment]
There's an extra dash in the copyright line: `;; Copyright (C) 2017- Junyoung Clare Jang`, probably a typo. You should remove that or tools that try to extract the year(s) will choke on it.

**Comment by Ailrun** [comment]
@tarsius I fix it too. Thanks.

**Pull request merged**
