### PR TITLE
Create key-assist

### PR DESCRIPTION
**Pull request by Boruch-Baum**
### Brief summary of what the package does

Minibuffer keybinding cheatsheet and launcher

### Direct link to the package repository

https://github.com/Boruch-Baum/emacs-key-assist

### Your association with the package

I'm the owner, author, maintainer, etc...

### Relevant communications with the upstream package maintainer

N/A

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
It would be helpful to have a screenshot of the output.  Also, the readme should probably mention `which-key` and how this package compares.

**Comment by Boruch-Baum** [comment]
> It would be helpful to have a screenshot of the output

Hmm. I don't think so, because the way the output displays will depend largely upon any user's particular emacs mini-buffer setup (eg. vanilla completing-read, helm, ido, icicles, ivy, ...). This package doesn't "roll-its-own" display format.

> Also, the readme should probably mention `which-key` and how this package compares.

I've never used `which-key`, but the description on its github readme is that it is a:
1) minor mode that
2) "displays the key bindings following your currently entered incomplete command (a prefix) in a popup" and
3) it seems to have rolled its own complex display method with
4) many specific customization features

The package I'm submitting:
1) isn't a minor mode that needs to be toggled on when you want it and off when it gets annoying
2) outputs keybindings based on *any* regexp of your choice (default is based upon major mode)
3) uses whatever display behavior you've already told emacs you prefer (no 'roll-your-own')
4) simple and straightforward with no need for defcustoms
5) programmer-friendly
5.1) Under the hood, it supports the possibility for elisp programmers and package developers to "go to town" with a very flexible input data structure to create custom command launchers and keybinding cheatsheets.

Ultimately: I don't want the burden of every-so-often needing to update a comparison list every time some other package is added or introduces a significant change; I don't want to be accused of making unfair or incomplete comparisons; I don't want the burden of having to learn the details of every other package that I'm not using.

**Comment by riscy** [comment]
This PR is adding a file to the root of MELPA, but you want the file to be added to the `recipes` subdir.

Not a blocker but I also thought a screenshot would be useful to see (even with a caveat like "this screenshot used ivy" or the default completing-read function).  The comparison is useful to see -- maybe another way to phrase it would be that "key-assist" is an engine around which packages similar to which-key could be developed.

In the meantime, quick first pass (only minor issues pop up -- thanks for your close adherence to the checklist):

- key-assist.el#L165: It's safer to sharp-quote function names; use `#'`
- key-assist.el#L351: It's safer to sharp-quote function names; use `#'`
- key-assist.el#L11: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- key-assist.el#L302: Optionally use `unless ...` instead of `when (not ...)`
- key-assist.el#L337: Optionally use `unless ...` instead of `when (not ...)`
- key-assist.el#L351: Optionally use `unless ...` instead of `when (not ...)`

**Comment by alphapapa** [comment]
> Hmm. I don't think so, because the way the output displays will depend largely upon any user's particular emacs mini-buffer setup (eg. vanilla completing-read, helm, ido, icicles, ivy, ...). This package doesn't "roll-its-own" display format.

That needn't stop you from showing a screenshot (or even a "text screenshot", i.e. copy/paste buffer contents) of what it shows in a default Emacs configuration.  Without a visual example, it will be difficult for users to imagine what this does and why they would want to use it.

> Ultimately: I don't want the burden of every-so-often needing to update a comparison list every time some other package is added or introduces a significant change; I don't want to be accused of making unfair or incomplete comparisons; I don't want the burden of having to learn the details of every other package that I'm not using.

The comparison needn't be comprehensive or guaranteed to be current.  The purpose is to help users understand what makes your package unique relative to other packages that, on the surface, seem very similar.

Now that MELPA has thousands of packages, one of the chief obstacles to new packages gaining traction is the problem of discovery.  If a user reads about your package, but he can't discern what it does, and it sounds like a package he already has does essentially the same thing, he will be unlikely to try it.  It would be a shame for your package to miss out on potential users that way.

**Comment by Boruch-Baum** [comment]
Thanks, Chris. Most suggestions adopted.

On 2020-11-08 13:05, Chris Rayner wrote:
>    This PR is adding a file to the root of MELPA, but you want the file to
>    be added to the recipes subdir.

Oops. Fixed. I didn't want to locally clone the melpa repository, so I
was using the web interface and got confused.

>      * key-assist.el#L302: Optionally use unless ... instead of when (not

Oh, how I hate the 'unless' idiom...

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
@riscy , @alphapapa : OK, Since both of you insist, I give in. I included a sample output in the README.

**Comment by alphapapa** [comment]
> @riscy , @alphapapa : OK, Since both of you insist, I give in. I included a sample output in the README.

Ah, that helps so much!  Now I understand what it does.  IIUC, it's like a simpler, more focused version of `C-h m`, that shows *just* the major mode bindings, without all the extraneous things like the list of minor modes, prefix key maps, global key bindings, etc.  I've always felt like `C-h m` made it too difficult to get a simple list of major mode bindings, and it looks like `key-assist` solves that (as well as allowing its facilities to be used in a programmable way).

Is my understanding correct?  If so, I'd suggest emphasizing (from the users' perspective) that it acts like a better `C-h m`, and putting that example near the top of the readme.  I think that will "sell" it very quickly to potential users.  :)

**Comment by Boruch-Baum** [comment]
On 2020-11-09 15:24, alphapapa wrote:
>    IIUC, it's like a simpler, more focused version of C-h m, that
>    shows just the major mode bindings, without all the extraneous
>    things like the list of minor modes, prefix key maps, global key
>    bindings, etc.

That's correct, but only when the user enters nothing at the command's
prompt. However, at that prompt the user can enter any regex or
sub-string, and thus get any subset of emacs commands that are bound at
that instant. For example, you could be in an *Occur* buffer but want a
presentation of frame commands, so at the command prompt you would type
'frame' (without the quotes). Try it. Play with it. Spread the news.
Enjoy.

>    Is my understanding correct? If so, I'd suggest emphasizing (from the
>    users' perspective) that it acts like a better C-h m, and putting that
>    example near the top of the readme. I think that will "sell" it very
>    quickly to potential users. :)

After my elaboration above, would you recommend "selling" it any
differently? What I mean is, how would you modify your paragraph above?

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by alphapapa** [comment]
> After my elaboration above, would you recommend "selling" it any differently? What I mean is, how would you modify your paragraph above?

I would recommend to explicitly compare it to `C-h m` and show how much easier the output is to use.  Looking at the first paragraph in the readme, under "For Emacs users:", it's not that it's not descriptive, but it's a lot to ask a potential user to understand and visualize from scratch.  Comparing it to `C-h m` explicitly would give a user something concrete to liken it to, and showing them the output would make it easy to see how much better it is.  I think that would be like an "instant sale", because it's so obvious how much easier it is to use in comparison.

**Comment by alphapapa** [comment]
BTW, I saw at the bottom of the source file the link to the bug report about upstreaming it.  Do you still plan to push for that?  If it were upstreamed, it might be confusing to have it in MELPA and built-in, or to have to subsequently delete the package from MELPA.

**Comment by Boruch-Baum** [comment]
On 2020-11-10 00:50, alphapapa wrote:
>    BTW, I saw at the bottom of the source file the link to the bug report
>    about upstreaming it. Do you still plan to push for that?

Yes.

>    If it were upstreamed, it might be confusing to have it in MELPA
>    and built-in

A lot of hypotheticals there, and a long time-line, and useless for
emacs users of prior versions. Debian (ahem, me) is still stuck at emacs
version 26, and if the package does get integrated, that wouldn't happen
to at least version 28. Meanwhile, there exist users with older versions
still.

Pushing to MELPA gets it to users (of more versions) quickly, gets me
more feedback to improve the package, and maybe encourages the emacs
developers to use it.

>    or to have to subsequently delete the package from MELPA.

Is that difficult?

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by alphapapa** [comment]
All fair points.  I don't guess deleting a package from MELPA is difficult, but I'd imagine it could be confusing to some users.

**Comment by riscy** [comment]
Yeah, deleting is easy.  I think especially if the package ends up on GNU ELPA, it's usually not a terrible experience for users.  Altogether this looks good to go.

**Pull request merged**
