### PR TITLE
use-package extensions now reside in use-package distribution

### PR DESCRIPTION
**Pull request by waymondo**
### Direct link to the package repository

https://github.com/jwiegley/use-package

### Your association with the package

Maintainer & contributor

### Relevant communications with the upstream package maintainer

These extensions have now been included in the `use-package` distribution.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by nickmccurdy** [comment]
Sorry for the noise, ignore those three pull requests, they're basically the same. 😄 Thanks.

**Comment by kaushalmodi** [comment]
@nickmccurdy No worries. But the recipe of `use-package` itself still needs to be fixed. See this deeply nested comment in a commit: https://github.com/jwiegley/use-package/commit/042e7292e4c4b29be81f875c270bfaec40f75434#commitcomment-26045246

**Comment by nickmccurdy** [comment]
I've been working on fixing the use-package recipe, hopefully I'll have it in by tomorrow.

**Comment by kaushalmodi** [comment]
@nickmccurdy 

> hopefully I'll have it in by tomorrow

I thought of giving a try at this PR; hope that was fine.

**Pull request merged**
