### PR TITLE
Add tab-bar-display recipe.

### PR DESCRIPTION
**Pull request by ROCKTAKEY**
### Brief summary of what the package does

Display strings on tab-bar in Emacs

### Direct link to the package repository

https://github.com/ROCKTAKEY/tab-bar-display

### Your association with the package

Author/maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
* Have you tested the code in the commit you've submitted?  I think it won't work due to misspelled variable names.
* Rather than publishing this as a MELPA package, it might be good to propose a patch to Emacs itself.  It would be trivial to add a couple of variables for a `tab-bar-prefix` and `tab-bar-suffix`.

**Comment by ROCKTAKEY** [comment]
>Have you tested the code in the commit you've submitted? I think it won't work due to misspelled variable names.

I'm very sorry. I've tested old one mistakenly.

>Rather than publishing this as a MELPA package, it might be good to propose a patch to Emacs itself. It would be trivial to add a couple of variables for a tab-bar-prefix and tab-bar-suffix.

Hmm, you seem to be right. I'd like to listen from others about that.

btw, I'm planning to add feature like clickable text, and text over/below tab-bar. (probably, it is still trivial to add them as a patch to Emacs itself)

**Comment by alphapapa** [comment]
I recently had a patch to `tab-line` merged into Emacs.  Juri Linkov, the author of the `tab-bar` and `tab-line` packages, was very helpful in the process.  I'm sure he would give due consideration to these ideas as well.  I encourage you to post them to emacs-devel.

**Comment by ROCKTAKEY** [comment]
Thanks. 
I'm willing to post that, but I've never posted to emacs-devel. Is there any thorough instruction?
As far as I searched, my postal address seems to be necessary. Is it true? I'd not like to send my personal information at all.

Sorry for many question less relevant to melpa.

**Comment by conao3** [comment]
> As far as I searched, my postal address seems to be necessary. Is it true?

No, but it is needed only FSF sign process.
Thanks @alphapapa, I'll make some instructions for him for emacs-devel.

**Comment by riscy** [comment]
Just marking this awaiting upstream while we await an outcome.  Thanks all.

**Comment by link0ff** [comment]
Such plans to add prefix/suffix strings to the tab bar were already discussed several times on emacs-devel:
https://lists.gnu.org/archive/html/emacs-devel/2019-10/msg00685.html
https://lists.gnu.org/archive/html/emacs-devel/2020-11/msg01167.html
So these two options will be added upstream to tab-bar.el soon.

Still this package could be published if it will provide more features and customization.  For example, it could provide an easy to customize option to enable the clock aligned to the right, or even moving some elements of the mode-line to the tab-bar, such as when `display-time` is enabled, its clock could be displayed on the tab bar instead of the mode-line of each buffer, etc.

**Comment by riscy** [comment]
Probably I need to take another look at this -- sorry for the delay.  :)  I'll remove the awaiting tag and take a look soon.

**Comment by riscy** [comment]
Hi @ROCKTAKEY, I realize it's been quite some time but have you made a decision about whether you want to try to submit a patch to Emacs, or whether the options @link0ff mentions will cover this use case?  I humbly agree that there's room for an "extended widgets" package too, if you wanted to take things in that direction.

**Comment by ROCKTAKEY** [comment]
@riscy, thank for your mention, and sorry for my late reply.
I've not use tab-bar.el extended on upstream, so I close this PR once. I will re-open this PR if I judge that this package can be room for "extended widgets".

**Pull request closed without merging**
