### PR TITLE
Add recipe for godoctor

### PR DESCRIPTION
**Pull request by microamp**
### Brief summary of what the package does

Emacs frontend for [godoctor](http://gorefactor.org/), a refactoring tool for the Go programming language.

### Direct link to the package repository

https://github.com/microamp/godoctor.el

### Your association with the package

I'm the maintainer of the package.

### Relevant communications with the upstream package maintainer

None

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- I suppose not dry-run commands should do save-buffer before calling godoctor and do revert-buffer after it. How about ?

**Comment by microamp** [comment]
How about simply making it complain when the current buffer is not saved? This behaviour is consistent with `go-rename` AFAIK. 

Something like
```emacs-lisp
(when (buffer-modified-p)
  (error "Please save the current buffer before invoking godoctor"))
```
?

**Comment by syohex** [comment]
No problem.

**Comment by microamp** [comment]
The change discussed above has been merged into `master`, https://github.com/microamp/godoctor.el/pull/3

Please have a look when you can. Thanks!

**Comment by syohex** [comment]
Buffer is not updated after file changed by godoctor. All users don't enable `auto-revert-mode`. I thinks you need to add `revert-buffer`.

**Comment by microamp** [comment]
Thanks for spotting it. Should've handled that. Here's the latest change. https://github.com/microamp/godoctor.el/pull/4

**Comment by syohex** [comment]
Looks good.

**Comment by purcell** [comment]
Thanks. Quick feedback:
- The parent group for your `defgroup` should not be `go` if that is not guaranteed to be defined, which it isn't in this case. Use `languages`.
- "Emacs" in the package description is redundant. All frontends implemented as Emacs packages are Emacs frontends!

**Comment by microamp** [comment]
Thanks for your comments. The changes suggested above are now in `master`. https://github.com/microamp/godoctor.el/pull/5

> All frontends implemented as Emacs packages are Emacs frontends!

And you're indeed right! :)

**Comment by purcell** [comment]
Super, thanks.

**Pull request merged**
