### PR TITLE
Add recipe for meow-tree-sitter

### PR DESCRIPTION
**Pull request by skissue**
### Brief summary of what the package does

Integrates the `treesit` library in Emacs 29+ with [Meow](https://github.com/meow-edit/meow)’s motions.

### Direct link to the package repository

https://github.com/skissue/meow-tree-sitter

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

N/A

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Checklist looks good, but I'm having trouble understanding some of the files or their history.  E.g.

queries/javascript.scm contains a comment that says:
```lisp
; See runtime/queries/ecma/README.md for more info.

; inherits: _javascript,ecma
```
Is this from e.g. [helix](https://github.com/helix-editor/helix/tree/master)?

**Comment by skissue** [comment]
> Is this from e.g. [helix](https://github.com/helix-editor/helix/tree/master)?

Yes, I took all the queries near-verbatim from the helix project, and then just flattened the directory structure since I didn't need any of the other files. I can do some manual cleanup if necessary.

**Comment by riscy** [comment]
You may as well - attribution is also a good idea, if I didn't miss it.

**Comment by skissue** [comment]
I went ahead and looked through all the queries and cleaned them up as I saw fit. I have attribution in the README, but I added it to the package file's commentary as well. Let me know if there are any other changes you'd like me to make.

**Comment by riscy** [comment]
Thank you!  Merging now - and welcome to MELPA. :)

**Pull request merged**
