### PR TITLE
Add recipe for selectrum

### PR DESCRIPTION
**Pull request by raxod502**
### Brief summary of what the package does

Selectrum is a better solution for incremental narrowing in Emacs, replacing Helm, Ivy, and IDO. Its design philosophy is based on choosing the right abstractions and prioritizing consistency and predictability over special-cased improvements for particular cases. As such, Selectrum follows existing Emacs conventions where they exist and are reasonable, and it declines to implement features which have marginal benefit compared to the additional complexity of a new interface.                                    

### Direct link to the package repository

https://github.com/raxod502/selectrum

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

Note: `package-lint` reports erroneous warnings about autoloading, as explained [in a comment](https://github.com/raxod502/selectrum/blob/210e85697c60befaa03891d282fe593e64fe62b8/selectrum.el#L964-L968).

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```emacs-lisp
 selectru…    15     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…    18     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   100     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   101     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   101     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   103     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   115     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   130     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   131     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   132     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   133     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   135     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   141     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   161     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   162     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   178     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   180     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   227     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   227     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   242     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   261     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   680     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   697     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   704     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   706     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   744     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   814     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   828   1 warning         Private functions generally should not be autoloaded. (emacs-lisp-package)
 selectr…   922   1 warning         Private functions generally should not be autoloaded. (emacs-lisp-package)
 selectr…   929     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   944   1 warning         Private functions generally should not be autoloaded. (emacs-lisp-package)
 selectr…   952     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   956     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 selectr…   960     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 select…   979   3 error           Global minor modes should be autoloaded or, rarely, `:require' their defining file (i.e. ":require 'selectrum"), to support the customization variable of the same name. (emacs-lisp-package)
 select…  1002  12 warning         `with-eval-after-load' is for use in configurations, and should rarely be used in packages. (emacs-lisp-package)
 select…  1029   8 warning         `with-eval-after-load' is for use in configurations, and should rarely be used in packages. (emacs-lisp-package)
```

**Comment by raxod502** [comment]
Thanks for your feedback.

* I've now explicitly disabled `sentence-end-double-space` in a file-local variable.
* The warnings about autoloading and `with-eval-after-load` are erroneous, as I mentioned above.

**Comment by purcell** [comment]
Thanks, this looks interesting! A few notes:

- I agree that the `with-eval-after-load` [block](https://github.com/raxod502/selectrum/blob/e8748a4e78867b79e608392875a389a62b0753af/selectrum.el#L1002-L1006) is misplaced. You're trying to add/remove advice in synch with whether the minor mode is enabled, but `dired` could be loaded at any later time, so you'd just get a big queue of deferred code that would executed at that point. Here I would just `advice-add` at the top level, and check for `selectrum-mode` in the advice function to decide whether to do anything special: that would be more idiomatic, and no-op advice is cheap enough that you can just leave it enabled. You can safely add advice for functions that have not yet been defined. Same goes for all the other advice, and the `selectrum--when-compile` seems unnecessary there. The minor mode definition will look so much tidier then.
- Otherwise looks really good, keen to take it for a spin.

**Comment by raxod502** [comment]
Thank you @purcell for the feedback and sorry for the delay in response. I got rid of the `with-eval-after-load` and `selectrum--when-compile` forms in the minor mode definition. Instead of adding the advice globally, I decided to simply remove a sharp quote so that I don't get a byte-compile warning. That way, the advice is cleaned up neatly and we get the best of both worlds.

**Comment by riscy** [comment]
Great, thanks!

**Pull request merged**
