### PR TITLE
Added calc-at-point

### PR DESCRIPTION
**Pull request by walseb**
### Brief summary of what the package does
This package allows you to perform calculations on buffer contents

### Direct link to the package repository

https://github.com/walseb/calc-at-point

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```diff
new file   Cask
@@ -0,0 +1,4 @@
+(source gnu)
+(source melpa)
+
+(package-file "calc-at-point.el")
```

```
$ cask; cask build
Loading package information... done
Package operations: 2 installs, 0 removals
  - Installing [ 1/2] dash (2.12.0)... done
  - Installing [ 2/2] emacs (26)... already present
Compiling /home/conao/dev/forks/calc-at-point/calc-at-point.el...

In toplevel form:
calc-at-point.el:30:1:Error: Cannot open load file: No such file or directory, dash-functional
```

```
 calc-at-…    65     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 calc-at…    96     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 calc-at…   120     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
```

missing `dash-functional` dependency?

**Comment by walseb** [comment]
Thanks it should work now. What did you use to generate the last warnings? `M-x checkdoc` doesn't report any warnings.

**Comment by purcell** [comment]
This looks great. I guess my only point of feedback here is that you probably shouldn't try to provide the authoritative definition of `'number` for `think-at-point`. It certainly wouldn't pick up numbers in certain locales. How about `calc-number`, to make it a bit more specific to the purpose?

**Comment by walseb** [comment]
Good point. The thing is that the normal `thing-at-point` function already has a definition of `'number`, but the function `bounds-of-thing-at-point` doesn't. So I just copied the regex from the already defined `'number` function and put it into `bounds-of-thing-at-point`. But I will think of a more modular solution or maybe just rename the package. And this is unrelated but do you know of a function that works like `string-to-number` but returns numbers with higher precision? Currently it seems to round to `float` which messes up numbers with many decimal places

**Comment by purcell** [comment]
> And this is unrelated but do you know of a function that works like `string-to-number` but returns numbers with higher precision? Currently it seems to round to `float` which messes up numbers with many decimal places

Not sure, sorry, but I'd probably look somewhere like the `calc` source code for clues.

**Comment by walseb** [comment]
I'm now no longer modifying `thing-at-point` and instead allow the user to pass in functions that returns the boundary of the thing at point when run. I still depend on `thing-at-point` because the default implementation of this function uses it to get the boundaries

**Comment by riscy** [comment]
Cool idea!  Looks good to go.  Non-blocking, but I find sharp-quoting can help me detect problems earlier by causing the compiler to warn, e.g. --

- calc-at-point.el#L67: It's safer to sharp-quote function names; use `#'`
- calc-at-point.el#L222: It's safer to sharp-quote function names; use `#'`
- calc-at-point.el#L214: It's safer to sharp-quote function names; use `#'`

**Comment by walseb** [comment]
Thanks! It should be fixed now, although I didn't sharp quote any operators partially because it made it look more complex and because it would be very strange for them to be missing

**Pull request merged**
