### PR TITLE
add lazygit recipe

### PR DESCRIPTION
**Pull request by tslight**
### Brief summary of what the package does

`lazygit` provides commands to batch run git operations on all of you GitLab or GitHub repositories.

For instance, one can clone all of your GitHub and GitLab repos in one fail swoop or pull from them or check the status of them.

### Direct link to the package repository

https://gitlab.com/tspub/lisp/lazygit

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks -- is there any relationship to [this lazygit](https://github.com/jesseduffield/lazygit)?  If not, that project looks popular and you may want to avoid its namespace.

Quick first pass of the checklist to follow.  I notice the summary line of the main file is "Git Forge Clients" which doesn't communicate much to me, and its `;;; Commentary` feels like some of your README can probably be fed into there to describe what's going on. 

### lazygit.el ###

byte-compile (using Emacs 27.1):
```
lazygit.el:313:1:Warning: the function `button-mode' is not known to be
    defined.
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
lazygit.el:11: Name emacs should appear capitalized as Emacs
```

package-lint (using version 20200906.512):
- No issues!


### lazygithub.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
lazygithub.el:29: Name emacs should appear capitalized as Emacs
```

package-lint (using version 20200906.512):
```
1 issue found:
29:0: error: Package-Requires outside the main file have no effect.
```


### lazygitlab.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
lazygitlab.el:32: Name emacs should appear capitalized as Emacs
```

package-lint (using version 20200906.512):
```
1 issue found:
32:0: error: Package-Requires outside the main file have no effect.
```

### Loadability ###

Verifying ability to #'load each file:
```
Loading lazygit.el
Loading lazygithub.el
Loading lazygitlab.el
Done.
```

### Package ###

- LICENSE excerpt: `Copyright (c) 2018, Toby Slight...`
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to lazygit.el
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to lazygithub.el
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to lazygitlab.el

**Comment by conao3** [comment]
Are there any comparison with @tarsius's [forge](https://github.com/magit/forge) which is official [magit](https://github.com/magit/magit) plugin?

**Comment by riscy** [comment]
>  I notice the summary line of the main file is "Git Forge Clients" which doesn't communicate much to me

I actually wasn't familiar with the term "git forge" so this one's on me. :)

**Comment by riscy** [comment]
Feel free to ping when ready for another look!

**Comment by riscy** [comment]
I seem to be running into a 404 when trying to access this repository.  I'll close this PR now since we also haven't heard anything in a while, but feel free to reopen if I'm missing something.

**Pull request closed without merging**
