### PR TITLE
Add ydl4e recipe

### PR DESCRIPTION
**Pull request by tuedachu**
### Brief summary of what the package does

`ytdl` is a simple Emacs interface for youtube-dl to make its usage easier and more intuitive.

### Direct link to the package repository

https://gitlab.com/tuedachu/ytdl

### Your association with the package

I am the creator and maintainer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by mihaiolteanu** [comment]
I think you should have reopened the previous PR, https://github.com/melpa/melpa/pull/6507?!

**Comment by tuedachu** [comment]
Sorry about that...

**Comment by riscy** [comment]
True, but this is fine now.  Very quickly I can point out this nag:

byte-compile-file (using Emacs 26.3):
```
ydl4e.el:476:1:Warning: the function `async-start' is not known to be defined.
```

**Comment by tuedachu** [comment]
Thanks for the feedback.

I have added async as requirement. It should work now.

How can I easily get the dependencies of my package? Thanks.

**Comment by riscy** [comment]
> How can I easily get the dependencies of my package? Thanks.

If you enable flycheck in your elisp buffers, it should let you know when a `require` is missing, and then you can check whether each `require` is built in to Emacs or not.  If you want to be really thorough, the [scripts I use are available](https://github.com/riscy/melpazoid) and will generate errors when required packages aren't available.  (There are also lots of other build tools like makem.sh or cask for Emacs)

**Comment by riscy** [comment]
Ok, taking a deeper look now --

- The apostrophes in `(format "cd '%s' && youtube-dl " destination-folder)` are probably meant to capture e.g. spaces in the directory's name.  But you should use the `shell-quote-argument` function to handle this in a general way (for example in the case where the directory is "Dan's Music").  You should also look into using that function for things like filenames and anything else that will gum up the works if it contains characters that the shell will eat.
- Your window handling in `ydl4e-run-youtube-dl-eshell` seems fragile to me -- in some (many) window arrangements, it will be inappropriate to `(split-window-right)` and in my experience it can be very finnicky to get `(windmove-right)`/`(windmove-left)`-type operations to work in general (for example imagine if users had their windows in a staggered arrangement where moving "left" doesn't necessarily undo moving "right").  I would recommend using a combination of `pop-to-buffer` and `save-window-excursion` to create and do things in a side window.
- While I'm at it, why eshell? :)  Why not use something like the built-in `(compile "<command>")` which will handle all of the window manipulations for you.
- A couple elisp conventions you may or may not be aware of -- it might be useful is to use two dashes to indicate private functions (e.g. `ydl4e--eval-field`) that are not meant to be part of your public interface.  A predicate like `ydl4e-destination-folder-exist?` is typically written `ydl4e-destination-folder-exist-p` in lisp.

**Comment by riscy** [comment]
Another note I'll make is that you might want to name your package in a less abbreviated way.  `ydl4e` is difficult to remember and doesn't have `youtube` in it anywhere, but it will help discoverability (especially of the <kbd>M-x</kbd> variety) if the package were named, e.g., `youtube-dl`.  The "4e" part is especially redundant since I'm assuming it stands for "for Emacs".

**Comment by tuedachu** [comment]
> > How can I easily get the dependencies of my package? Thanks.
> 
> If you enable flycheck in your elisp buffers, it should let you know when a `require` is missing, and then you can check whether each `require` is built in to Emacs or not. If you want to be really thorough, the [scripts I use are available](https://github.com/riscy/melpazoid) and will generate errors when required packages aren't available. (There are also lots of other build tools like makem.sh or cask for Emacs)

Thanks! I have just tested it and it's great!

**Comment by tuedachu** [comment]
Thanks for your very detailed feedback. I will address your comments and let you know when I am done.

**Comment by tuedachu** [comment]
Thanks for the feedback. Please find my comments inline.

> * The apostrophes in `(format "cd '%s' && youtube-dl " destination-folder)` are probably meant to capture e.g. spaces in the directory's name.  But you should use the `shell-quote-argument` function to handle this in a general way (for example in the case where the directory is "Dan's Music").  You should also look into using that function for things like filenames and anything else that will gum up the works if it contains characters that the shell will eat.

Done.

> * Your window handling in `ydl4e-run-youtube-dl-eshell` seems fragile to me -- in some (many) window arrangements, it will be inappropriate to `(split-window-right)` and in my experience it can be very finnicky to get `(windmove-right)`/`(windmove-left)`-type operations to work in general (for example imagine if users had their windows in a staggered arrangement where moving "left" doesn't necessarily undo moving "right").  I would recommend using a combination of `pop-to-buffer` and `save-window-excursion` to create and do things in a side window.

I decided to use the built-in behavior of `eshell`. I therefore removed the `(windowmove-left)` and `(windowmove-right)`. The default eshell behavior is good enough, I believe.

> * While I'm at it, why eshell? :)  Why not use something like the built-in `(compile "<command>")` which will handle all of the window manipulations for you.

I have tried to use `(compile <command>)` but emacs was complaining because of some parentheses (e.g. `.%(ext).s`).

> * A couple elisp conventions you may or may not be aware of -- it might be useful is to use two dashes to indicate private functions (e.g. `ydl4e--eval-field`) that are not meant to be part of your public interface.  A predicate like `ydl4e-destination-folder-exist?` is typically written `ydl4e-destination-folder-exist-p` in lisp.

Thanks. I reviewed the code and tried to follows those conventions when applicaple.

Further feedback is of course very welcome! Thanks.

**Comment by tuedachu** [comment]
> Another note I'll make is that you might want to name your package in a less abbreviated way. `ydl4e` is difficult to remember and doesn't have `youtube` in it anywhere, but it will help discoverability (especially of the M-x variety) if the package were named, e.g., `youtube-dl`. The "4e" part is especially redundant since I'm assuming it stands for "for Emacs".

There is already an Emacs package named `youtube-dl` (not on Melpa but on Emacsmirror).

I decided to rename the package `ytdl`. Not ideal, I agree, but I guess it is better than `ydl4e`. I am open to suggestions! :)

**Comment by riscy** [comment]
Looks good -- I see no blockers.

One last nit in passing:

> "Filename already exist in the destination folder (eventually with a different extension)!"

I find this warning message a little hard to understand (and maybe too long too).  What about something like "Destination filename already exists!" or similar?

In any case, welcome to MELPA!

**Pull request merged**
