### PR TITLE
Add google-theme recipe

### PR DESCRIPTION
**Pull request by Gulkbag**
### Brief summary of what the package does
A Elegant theme based on google colors

### Direct link to the package repository

https://github.com/Gulkbag/Emacs-Google-Theme
### Your association with the package

The developer

### Checklist 
Please confirm with `x`: 
 * [x]  The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
* [x]  I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org) 
* [x]  I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
* [x]  My elisp byte-compiles cleanly 
* [x]  `M-x checkdoc` is happy with my docstrings 
* [x]  I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
* [x]  I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, please ping us here with a comment when you've completed the checklist.

**Comment by Gulkbag** [comment]
@purcell  Completed

**Comment by riscy** [comment]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
google-theme.el:0: The first line should be of the form: ";;; package --- Summary"
Warning (emacs): 
google-theme.el:140: White space found at end of line
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
3 issues found:

1:1: error: Package should have a Homepage or URL header.
1:1: error: There is no (provide 'Google-theme) form.
28:0: error: Package should have a non-empty ;;; Commentary section.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
Per CONTRIBUTING.org, consider using lexical binding
(The following assumes lexical binding is enabled)
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
No issues! 🎉

Minor:
- google-theme.el#L24: Prefer `https` over `http` (if possible)
-----

Probably several are fixed by removing the blank leading lines and downcasing the first character of [this line](https://github.com/Gulkbag/Emacs-Google-Theme/blob/master/google-theme.el#L4).

**Comment by Gulkbag** [comment]
@riscy Fixed, i think.

**Comment by riscy** [comment]
That looks better, but please re-run checkdoc and the most recent package-lint on your latest.

**Comment by purcell** [comment]
> That looks better, but please re-run checkdoc and the most recent package-lint on your latest.

Yup, and also downcase the symbol `'Google` to `'google`. `deftheme` has an additional `DOC` arg which you can (and should) use to add a human description of the theme.

**Comment by purcell** [comment]
> That looks better, but please re-run checkdoc and the most recent package-lint on your latest.

Ping! :-)

**Comment by riscy** [comment]
Hi @Gulkbag, feel free to reopen this PR when it's ready for another look.

**Pull request closed without merging**
