### PR TITLE
Add sharper, a transient-based dotnet CLI wrapper

### PR DESCRIPTION
**Pull request by sebasmonia**
### Brief summary of what the package does

Sharper is a `dotnet` CLI wrapper, built using Transient.

### Direct link to the package repository

https://github.com/sebasmonia/sharper

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks!  Quick first pass.

### sharper.el ###

byte-compile (using Emacs 27.1):
```
sharper.el:145:18:Warning: reference to free variable
    `url-http-end-of-headers'
In end of data:
sharper.el:1296:1:Warning: the function `c-defun-name-and-limits' is not known
    to be defined.
```
(require 'url-http) and (require 'cc-mode) should do the trick.

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- sharper.el#L943: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- sharper.el#L944: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- sharper.el#L1049: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- sharper.el#L1050: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- sharper.el#L1142: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- sharper.el#L1143: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- sharper.el#L1245: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- sharper.el#L55: Customizable variables shouldn't usually be private

### Loadability ###

Verifying ability to #'load each file:
```
Loading sharper.el
Done.
```

### Package ###

- GitHub API found `MIT License`
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to sharper.el (slightly more formal/detectable than just "License: MIT")

**Comment by sebasmonia** [comment]
> (require 'url-http) and (require 'cc-mode) should do the trick.

Added the first require. For cc-mode, this is optional and there's a fallback with thing-at-point, so I guarded the call with `fboundp` instead. Let me know what you think.

Updated the customizable variable to make it public, it was a mistake.

Finally, the `define-key` calls are all assigning to the keymaps of the modes that were just defined. If you still think it should be corrected I can make the relevant changes.

Thank you for your feedback!

**Comment by riscy** [comment]
I think the remaining byte-compile warning -

```
sharper.el:146:18:Warning: reference to free variable
    `url-http-end-of-headers'
```
is not your fault, but url-http's -- it only does `(defvar url-http-end-of-headers)` without an implied value.  You could silence it by adding your own benign `(defvar url-http-end-of-headers)` after `(require 'url-http)` although I won't block on that.

> Finally, the define-key calls are all assigning to the keymaps of the modes that were just defined. If you still think it should be corrected I can make the relevant changes.

Yes, because someone (or some other mode) may define a customized keymap for your mode, which would get clobbered when they bring in your mode.  If you `(defvar sharper--solution-management-mode-map` before you call `define-derived-mode`, you won't overwrite the user's keybindings, and that `define-derived-mode` will automatically use the keymap because its name matches.

Looks like an easy merge after that.

**Comment by sebasmonia** [comment]
Added a `defvar` for each derived mode.

Thank you~

**Comment by riscy** [comment]
Hello, just a friendly ping.  I notice this could still have a `(defvar 'url-http-end-of-headers)` at the top (which I mentioned was optional), and some of the top-level define-keys are still prone to overwriting user keybindings.  For the latter, a good pattern is:

```elisp
(defvar sharper--solution-management-mode-map
  (let ((km (make-sparse-keymap)))
    (define-key km (kbd "RET") 'sharper-transient-solution)
    (define-key km (kbd "g") 'sharper--solution-management-refresh)
    km)
  "Keymap for `sharper--solution-management-mode'.")
```

**Comment by sebasmonia** [comment]
You know, when I made the changes before I wasn't quite sure it made a difference. Now that I saw your second suggestion and after applying it I understand why the previous version didn't make sense :man_facepalming: 

Thanks for your patience.

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
