### PR TITLE
Add recipe for mlso-theme

### PR DESCRIPTION
**Pull request by Mulling**
### Brief summary of what the package does

A dark, medium contrast theme with warm colors

### Direct link to the package repository

https://github.com/Mulling/mlso-theme

### Your association with the package

I am the author and maintainer of the package

### Relevant communications with the upstream package maintainer

None Needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```
 mlso-them…     7   5 warning         You should include standard keywords: see the variable `finder-known-keywords'. (emacs-lisp-package)
```

**Comment by Mulling** [comment]
Thanks, Fixed.

**Comment by conao3** [comment]
Thanks! and please follow comment convention. Please read [Emacs-lisp-style-guide; Comment](https://github.com/bbatsov/emacs-lisp-style-guide#comments).

And why are you stop byte-compile? https://github.com/Mulling/mlso-theme/blob/6ee0c1717b7445a26496bf39f830523e5e891657/mlso-theme.el#L241

**Comment by Mulling** [comment]
> Thanks! and please follow comment convention. Please read [Emacs-lisp-style-guide; Comment](https://github.com/bbatsov/emacs-lisp-style-guide#comments).
Fixed, i think...

> And why are you stop byte-compile? https://github.com/Mulling/mlso-theme/blob/6ee0c1717b7445a26496bf39f830523e5e891657/mlso-theme.el#L241
No real reason. Just saw it somewhere and thought it was necessary.

**Comment by conao3** [comment]
Probably not necessary.
Try byte-compiling (remove the local variable) to see how it works. MELPA `make sandbox` help test your package works well.

**Comment by riscy** [comment]
Yeah, it's not necessary to not byte-compile.  Byte-compiling is useful -- even for a theme -- since its warnings/errors can reveal existing problems. 

You may also want to consider:
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems

Some LICENSE boilerplate is something we're looking out for more carefully now.  You may want to add e.g. `SPDX-License-Identifier: WTFPL` somewhere in your `Version/URL/Author/Package-Requires` block (somewhere above your `;;; Commentary:` at least.

After that, this looks good to go.

**Comment by Mulling** [comment]
Thank you, I've added the license boilerplate. And i already have lexical binding enabled.

**Comment by riscy** [comment]
It's just my opinion, but it would be better if you wrote `SPDX-License-Identifier: WTFPL` in full -- the extra formality will [resolve any ambiguity](https://spdx.org/ids-why) and make it detectable.

It's strongly recommended, but not a blocker.

**Comment by riscy** [comment]
Oh, and welcome to MELPA. :)

**Pull request merged**
