### PR TITLE
Add recipe for soar-mode.

### PR DESCRIPTION
**Pull request by adeschamps**
### Brief summary of what the package does

This package provides a major mode for the Soar language.

### Direct link to the package repository

https://github.com/adeschamps/soar-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by adeschamps** [comment]
Thanks for the feedback. Soar is a fairly obscure language with a very small community. There are still some edge cases in my syntax highlighting and indentation, but it works well for the majority of Soar code I've worked on.

I addressed the warnings, extracted the indentation into a customizable setting, and included the license in the file. It also derives from `prog-mode` now.

**Comment by purcell** [comment]
Thanks, and sorry for the slow response. Quick notes:

- Delete [this](https://github.com/adeschamps/soar-mode/blob/f02d59ec5a3807a5815cf35aabe93a8e5b97c492/soar-mode.el#L46) -- `define-derived-mode` generates this code.
- Same for [this](https://github.com/adeschamps/soar-mode/blob/f02d59ec5a3807a5815cf35aabe93a8e5b97c492/soar-mode.el#L54-L58) -- I believe that `C-j` is bound by default to `newline-and-indent`.
- [This code](https://github.com/adeschamps/soar-mode/blob/f02d59ec5a3807a5815cf35aabe93a8e5b97c492/soar-mode.el#L110) is trying to declare a new global variable every time it runs. I think you just want to `let`-bind the cur-indent variable here instead.
- You should `;;;###autoload` the major mode too.
- `font-lock-keywords` is always buffer-local, so you can just use `setq` [here](https://github.com/adeschamps/soar-mode/blob/f02d59ec5a3807a5815cf35aabe93a8e5b97c492/soar-mode.el#L128).

Hope that helps!

**Comment by adeschamps** [comment]
Thanks for the feedback, and sorry for the delay. I've made the changes you suggested.

**Comment by purcell** [comment]
Super, thanks - merged now! Welcome to MELPA. :tada:

**Pull request merged**
