### PR TITLE
Add recipe for freeze-it

### PR DESCRIPTION
**Pull request by rnkn**
### Brief summary of what the package does

Minor mode to make your previous writing in current read-only after a short delay (to kill your inner editor).

### Direct link to the package repository

https://github.com/rnkn/freeze-it

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by SpecialBomb** [comment]
So, how exactly is this package used? I read the README and I still don't understand what it does.

**Comment by rnkn** [comment]
The README is clear. I'm not sure how much more I can add. After a delay, the text from a position back a word, line, visual-line or paragraph from point to point-min is made read-only, preventing a writer from going back and changing it. This may not make much sense to a coder but is useful for writers (for whom the package is intended).

**Comment by alphapapa** [comment]
Haha, this is a clever idea.  Only in Emacs!  Maybe there should be a command to explicitly "unfreeze" text, for those who aren't quite as...pure?  :)

**Comment by SpecialBomb** [comment]
Ah, I see now. I just didn't understand what "your inner-editor" meant.

Also, it was more of a personal question, not criticizing your description
at all. I just didn't get it haha.

**Comment by rnkn** [comment]
> Haha, this is a clever idea. Only in Emacs! Maybe there should be a command to explicitly "unfreeze" text, for those who aren't quite as...pure? :)

@alphapapa thanks. Thing is I know if I include an unfreeze command then I'd be tempted to use it, and removing the cognitive temptation is the intended purpose of the minor mode. But it's not totally brutalist; it's easy enough to just kill the buffer and visit the file again, or just `C-x r SPC 1 RET C-x k RET C-x r j 1 y`

**Comment by alphapapa** [comment]
> just `C-x r SPC 1 RET C-x k RET C-x r j 1 y`

LOL, again, only in Emacs.  :)

BTW, I recently relearned about `C-x SPC`'s improved rectangle select.  I think you can do something like: `C-x SPC [move cursor] C-k [move cursor] C-y` now, and by doing it that way, the lower-right corner of the rectangle is properly extended to match earlier lines when necessary.

**Comment by rnkn** [comment]
I've made the README a bit clearer.

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```
 freeze-i…    32     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 freeze-i…    37     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 freeze-i…    40     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
```

**Comment by rnkn** [comment]
@conao3 you have the wrong setting for `sentence-end-double-space`

**Comment by conao3** [comment]
See [Emacs-lisp-style-guilde#comments](https://github.com/bbatsov/emacs-lisp-style-guide#comments)
> Comments longer than a word begin with a capital letter and use punctuation. Separate sentences with two spaces.

There are two spaces after the period throughout Emacs.
@riscy seems tired of advising these people (https://github.com/riscy/melpazoid/blob/9d7cbc456d4bb38602e9d64728ab6495d2f8faf6/melpazoid/melpazoid.el#L79), but I'll keep suggesting.
More packages that don't follow the rules are bad for the Emacs community.

**Comment by rnkn** [comment]
@conao3 that link is just some other person's preferences, and given this is my package, it will follow my preferences. I understand that Emacs, as a long lived program, will have some boomers still stuck in their two-space ways, which is fine, but the very existence of a user option `sentence-end-double-space` is evidence enough that this is indeed optional.

**Comment by conao3** [comment]
Not a preference, but a [requirement for MELPA](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#making-your-package-ready-for-inclusion) registration.

If you insist on that idea, close this PR.
[A related comment](https://github.com/melpa/melpa/pull/6740#issuecomment-596239547) is exist but this comment for LICENSE.

But I don't think it's necessary because I know you're smart.

**Comment by rnkn** [comment]
@conao3 peruse the `package-lint.el` and `package-build.el` files to see how package requirements are met. You will no doubt lead a happier life by learning to accept that other people in any community will have different preferences to your own.

**Comment by alphapapa** [comment]
@rnkn

> I understand that Emacs, as a long lived program, will have some boomers still stuck in their two-space ways, which is fine, but the very existence of a user option `sentence-end-double-space` is evidence enough that this is indeed optional.

Now, now, two-spaces is objectively superior, especially in Emacs (remember `M-a` and `M-e`, which are not useful with one-space).  And I'm no baby boomer.  ;)  But I agree with you in that you should be able to use your own preference for this in your own packages.

@conao3

> If you insist on that idea, close this PR.
> 
> But I don't think it's necessary because I know you're smart.

Not cool, man.

**Comment by SpecialBomb** [comment]
I say let the package pass for now by following the linting and the community can decide on the silly spaces stuff. What matters right now is putting a package in and making sure it works properly.

Play nice, boys and girls.

**Comment by rnkn** [comment]
> (remember `M-a` and `M-e`, which are not useful with one-space).

These change behaviour based on `sentence-end-double-space`. I've since added a file local variable to this and all my packages to alleviate any problem one might have when navigating the documentation strings in source by sentence.

**Comment by alphapapa** [comment]
> These change behaviour based on `sentence-end-double-space`.

Ah, good point.  But IMO they aren't very useful without two spaces, because then they don't navigate by sentence, just like `C-s .`.  Ah well, this age-old debate will probably outlive the Emacs/vi one.  :)

**Comment by riscy** [comment]
This looks good to me - I also have to say thanks everyone for contributing above, I smiled.

Minor:
- tempation -> temptation

**Comment by rnkn** [comment]
Thanks!

**Pull request merged**
