### PR TITLE
Add org-wikish

### PR DESCRIPTION
**Pull request by Benaiah**
### Brief summary of what the package does

Simple Org wiki system.

### Direct link to the package repository

https://github.com/benaiah/org-wikish

### Your association with the package

I wrote `org-wikish` over the last couple weeks.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- `org-wikish-wiki-directory` should be custom variable(defined by `defcustom`) and its autoload cookie is not necessary
- `org-wikish-link-word-at-point-and-enter` is used but it is not defined.

**Comment by Benaiah** [comment]
@syohex just pushed fixes for those.

**Comment by syohex** [comment]
Sorry, I should have explained in more detail.

- Please define group by `defgroup` for `defcustom` variables and specify its type attribyte(`:type`)
- I suppose `org-wikish-wiki-directory` should have better default value. Current default value `/your/directory/here/` causes error in most case(because there is no such directory). For example, `~/.emacs.d/org-wikish-wiki`(Use `user-emacs-directory` instead of `~/.emacs.d`) etc.

**Comment by purcell** [comment]
> Use user-emacs-directory instead of ~/.emacs.d

See also the useful function `locate-user-emacs-file`.

**Comment by tarsius** [comment]
Upstream still hasn't responded to my pull request implementing our suggestions, so I am closing this now.

**Pull request closed without merging**
