### PR TITLE
Add recipe for modaled

### PR DESCRIPTION
**Pull request by DCsunset**
### Brief summary of what the package does

Modaled provides fully customizable modal editing for Emacs. Unlike other popular modal editing packages, Modaled doesn't provide any keybindings and nor does it come with any minor modes by default. Instead, it provides useful functions based on which users can create minor modes and keybindings by themselves. This greatly facilitates customization of modal editing.

### Direct link to the package repository

https://github.com/DCsunset/modaled

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Have you had a chance to compare to e.g. modalka or ryo-modal (check e.g. https://melpa.org/#/?q=modal).  In the meantime, here's a quick first pass --

`modaled.el` with package-lint 20230315.1052:
```
2 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
124:6: error: Global minor modes should be autoloaded or, rarely, `:require' their defining file (i.e. ":require 'modaled"), to support the customization variable of the same name.
```

**Comment by DCsunset** [comment]
Thanks for your feedback. Compared to modalka and ryo-modal, modaled supports creating multiple minor modes and comes with no default mode, which makes it possible to implement different states in modal editing and different keybindings for different situations.

I've fixed first warning. However, I don't quite understand the second error. In my code, the global minor mode is defined in a macro, while the macro itself has the autoload comment. Since the macro is autoloaded, shouldn't the mode defined inside already autoloaded as well?

**Comment by DCsunset** [comment]
I've fixed the second error by adding the `:require 'modaled`. Not sure if that is redundant but it suppresses the error emitted by package-lint.

**Comment by riscy** [comment]
I think the code looks good to merge, but a couple metadata/style comments:

- The file is using pure tabs for indentation which is unconventional - I'd strongly recommend `(setq indent-tabs-mode nil)` and using only spaces for identation in Emacs lisp code
- The package summary at the top says "Fully customizable modal editing" but I think what you wrote in your `;;; Commentary` is clearer, e.g. "build your own modal editing minor mode" or similar

I think neither is worth blocking on - merging.  And, welcome to MELPA. :)

**Comment by DCsunset** [comment]
Thanks for merging it and your suggestions. I'll fix them in my repo.

**Pull request merged**
