### PR TITLE
add recipe company-lua

### PR DESCRIPTION
**Pull request by stardiviner**
https://github.com/ptrv/company-lua

### CODE REVIEW

**Comment by marsam** [comment]
I think you also need to include the .lua files

```diff
 (company-lua
  :fetcher github
- :repo "ptrv/company-lua")
+ :repo "ptrv/company-lua"
+ :files ("company-lua.el"
+         ("lua" "lua/*")))
```

**Comment by purcell** [comment]
Or rather, just `:files (:defaults "lua")`, please.

**Comment by stardiviner** [comment]
Updated.

**Comment by ptrv** [comment]
Any news here?

**Comment by milkypostman** [comment]
CI had issues. retrying.

**Comment by stardiviner** [comment]
@milkypostman CI seems passed.

**Pull request merged**
