### PR TITLE
Add a recipe for the feline modeline

### PR DESCRIPTION
**Pull request by chee**
### Brief summary of what the package does

It's a light fast modeline replacement.

It looks like this:

screenshot of modeline

### Direct link to the package repository

https://opensource.chee.party/chee/feline-mode

### Your association with the package
I am the creator _and_ a highly enthusiastic user

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses) - gpl3 baby
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org) - ye
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback - i have, some of the error messages are very hard to understand and act on
- [x] My elisp byte-compiles cleanly - ye
- [x] `M-x checkdoc` is happy with my docstrings - OKOKOKOKOK
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org) - yes, this was a very pleasant and well designed process

### CODE REVIEW

**Comment by progfolio** [comment]
A few notes:

<details><summary>Log @2023-03-01 01:05:19 -0500</summary>
search filter: "byte-comp warning"
<table>
<thead><th>Package</th><th>Status</th><th>Info</th></thead>
<tbody>
<tr><td>feline-mode</td><td>byte-compilation</td><td>feline.el:189:34: Warning: the function ‘project-root’ is not known to be defined.</td></tr></tbody>
</table>
</details>

Consider enabling lexical binding. e.g.

```emacs-lisp
;;; feline.el --- A modeline with very little  -*- lexical-binding: t; -*-
```

feline-evil mentions faces (e.g. feline-evil-operator-face, feline-evil-replace-face) which are not defined. Another way to implement this would be:

```emacs-lisp
(defun feline-evil nil
  "Get a feline representation of the evil mode."
  (when-let ((state (bound-and-true-p evil-state)))
	 (propertize (symbol-name state) 'face (intern (format "feline-evil-%s-face" state)))))
```

That will obviate the need for the `feline--fbound-and-p` macro.

**Comment by chee** [comment]
> feline-evil mentions faces (e.g. feline-evil-operator-face, feline-evil-replace-face) which are not defined. 
lol! oops, I'll add those now. Thanks! Learning my lesson about adding `evil` as an afterthought.
>   (when-let ((state (bound-and-true-p evil-state)))
> 	 (propertize (symbol-name state) 'face (intern (format "feline-evil-%s-face" state)))))
> ```
> 
> That will obviate the need for the `feline--fbound-and-p` macro.
Oh! This is really cool and helpful! Thanks, I'll do that!

**Comment by chee** [comment]
> ```emacs-lisp
> (propertize (symbol-name state) 'face (intern (format "feline-evil-%s-face" state))))
> ```

Will this be a problem if evil adds new states that I haven't defined a face for?

**Comment by riscy** [comment]
> Will this be a problem if evil adds new states that I haven't defined a face for?

This seems like it would be easy to test for (and probably worth testing for in general) but I don't foresee evil being too unstable in that regard.

The code is looking good at this stage -- thanks @progfolio -- and from a checklist perspective all that's missing is a license indicator in feline.el: Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to feline.el

**Comment by chee** [comment]
> The code is looking good at this stage -- thanks @progfolio -- and from a checklist perspective all that's missing is a license indicator in feline.el: Add _formal_ license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to feline.el

ooh! thanks, I've added it now. `;; SPDX-License-Identifier: GPL-3.0-or-later`

**Comment by riscy** [comment]
Thanks - merging!

**Pull request merged**
