### PR TITLE
evil-python-movement: port Neovim's movement in Python to Emacs/Evil

### PR DESCRIPTION
**Pull request by FelipeLema**
### Brief summary of what the package does

Port of Python movement in Neovim to Evil+Emacs.

Inspired by https://stackoverflow.com/a/28284564

### Direct link to the package repository

https://bitbucket.org/FelipeLema/evil-python-movement.el/src/master/

### Your association with the package

Creator and maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
A couple of thoughts:

 * There's a thread over at /r/emacs about your package (and emojis in code in general). The general sentiment seems to be that you've committed a crime against nature.
 * I agree, those emojis make the code both unreadable and unwriteable.
 * It also goes against the convention of your package name being the prefix for your functions.
 * You're missing a Package-Requires header.
 * Shouldn't some of those functions or motions be autoloaded?

**Comment by FelipeLema** [comment]
Just submitted changes to address your remarks. I didn't _think_ those motions needed autoload, but I don't mind them having them either.

**Comment by edkolev** [comment]
@FelipeLema you'll need something like this for autoload to work with evil: https://github.com/edkolev/evil-lion/blob/master/evil-lion.el#L75

**Comment by FelipeLema** [comment]
Done, thanks @edkolev

**Comment by purcell** [comment]
Thanks for your patience - some quick notes:

- I think the URL in the recipe should be https://bitbucket.org/FelipeLema/evil-python-movement.el, ie. not include the "/src/master" suffix
- Your symbol prefixes are still not consistently `evil-python-movement-`
- The lines inside the `Commentary` section should begin with `;;`, not `;;;`.

**Comment by FelipeLema** [comment]
Updated according to comments 👍

**Comment by FelipeLema** [comment]
Just updated. Couldn't grep for `\bevil-python-[^m]`

**Comment by DamienCassou** [comment]
- Please run linters specified in CONTRIBUTING.md. They would have told you about:
  - you miss Homepage or URL header
  - either include standard keywords, or remove the `Keywords:` header

**Comment by FelipeLema** [comment]
Updated per @DamienCassou's comments. Indeed I missed `package-lint`'s comments (I had installed with `flycheck-package`, but not activated it).

Sorry about missing that.

**Comment by DamienCassou** [comment]
1. `top-level-def-regex` and `def-regex` are mostly the same. You might want to extract the common part and use the rx' `regex` construct to embed it into the other two.
2. instead of using the heavyweight `s-match` only as a boolean, you might want to use `string-match-p`.
3. I'm not sure why you can't use `search-forward-regexp` and `search-backward-regexp` instead of implementing your own (e.g., with `forward-to-top-level-def`).
4. In `common-python-movement`, I find it a bit weird that the code constructs a list only to get the last element. You could try to reimplement that with `cl-loop`
5. I suggest you write a few words around your `;; [[` and `;; [m` comment lines in the code. I first thought those comment lines were some special markup for a minor mode or for evil. What about `;; Definition for the [[ keybinding`

**Pull request merged**
