### PR TITLE
Add recipe for `ovpn-mode'

### PR DESCRIPTION
**Pull request by anticomputer**
### Brief summary of what the package does

An openvpn configuration and connection management mode.

### Direct link to the package repository

https://github.com/anticomputer/ovpn-mode

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

N/A

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Some notes:
- When you ran it, `package-lint` should have told you that you need a package dependency for `cl-lib`.
- [This line](https://github.com/anticomputer/ovpn-mode/blob/d39886d619e479acff3b3343ff3a678b582cd0e8/ovpn-mode.el#L169) is redundant, since `define-derived-mode` expands to code which calls `use-local-map` for you.
- Prefer to `let`-bind `inhibit-read-only` in cases like [this](https://github.com/anticomputer/ovpn-mode/blob/d39886d619e479acff3b3343ff3a678b582cd0e8/ovpn-mode.el#L539-L552).
- Nice to see you're carefully using `shell-quote-argument` where appropriate. [This](https://github.com/anticomputer/ovpn-mode/blob/d39886d619e479acff3b3343ff3a678b582cd0e8/ovpn-mode.el#L939) and [this](https://github.com/anticomputer/ovpn-mode/blob/d39886d619e479acff3b3343ff3a678b582cd0e8/ovpn-mode.el#L992) might well not be safe, though.
- You might consider failing fast with code like `(unless cond (error "Could not start openvpn ..."))` to make the [long hanging `if` + `progn` code](https://github.com/anticomputer/ovpn-mode/blob/d39886d619e479acff3b3343ff3a678b582cd0e8/ovpn-mode.el#L724-L796) more comprehensible. The `message` calls there (and elsewhere) should probably be errors in any case.
- [Here](https://github.com/anticomputer/ovpn-mode/blob/d39886d619e479acff3b3343ff3a678b582cd0e8/ovpn-mode.el#L1070-L1073) you're modifying the global `kill-buffer-hook`, then checking every time a buffer is killed to see if it is the open vpn buffer. Instead, in openvpn mode, just modify the local version of `kill-buffer-hook` : see `add-hook`'s "local" argument.

Hope that helps!

**Comment by anticomputer** [comment]
Thanks for the feedback Steve, I'll implement the suggested improvements as well as address the missing package require. Regarding the privileged shell call out safety, I did consider the potential for "shoot in foot" user behavior on that privileged shell interface there as noted in the documentation. I think I will explicitly remove interactive use of that functionality and limit it to the hardcoded xterm and chrome spawners to limit the potential for pilot error. Cheers!

**Comment by anticomputer** [comment]
https://github.com/anticomputer/ovpn-mode/commit/ffd46f97a6b6e6b72f3f795f09807ae3b08a2d18 addresses your feedback. I agree that removing the copious if/progn constructs makes for much more readable code.

**Comment by purcell** [comment]
Awesome, merged now. Welcome to MELPA! :tada:

**Pull request merged**
