### PR TITLE
Add recipe for quarto-mode

### PR DESCRIPTION
**Pull request by cscheid**
### Brief summary of what the package does

This package provides a mode for editing Quarto documents: https://quarto.org

### Direct link to the package repository

https://github.com/quarto-dev/quarto-emacs/

### Your association with the package

I'm the developer and maintainer.

### Relevant communications with the upstream package maintainer

N/A

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

There _are_ two warnings on byte-compilation, but I believe them to be spurious. Specifically:

```
quarto-mode.el:59:20:Warning: ‘make-variable-buffer-local’ not called at
    toplevel
quarto-mode.el:63:20:Warning: ‘make-variable-buffer-local’ not called at
    toplevel
```

These come up because I'm calling a macro that eventually uses make-variable-buffer-local from inside a conditional. I don't know a way around this. I'm trying hard to to avoid requiring ESS, a large optional dependency that won't be necessary for some of our users. At the same time, if the user _has_ ESS installed, we want to support it.

### CODE REVIEW

**Comment by riscy** [comment]
There's one way you could pacify the compiler, which is by writing `(eval '(define-polymode ...`.  I don't think that makes the code any better (really it makes it a bit worse) but there are definitely benefits to having a clean byte-compile (your users don't see any noise when they install your package, and you don't get used to seeing "warnings" which could eventually end up pointing to real issues).  I lean toward asking authors to get the byte-compile warnings fully sorted out, since it's a slippery slope otherwise.

I think you may also be byte-compiling in an instance of Emacs that has already loaded in the package, since this also shows up when compiling from scratch:
```
quarto-mode.el:147:9:Warning: reference to free variable
    `poly-quarto-mode-map'
```
which is because `easy-menu-define` is being parsed earlier than the mode declaration (and its map), although I'm not so familiar with the polymode toolkit to easily debug this.

**Comment by cscheid** [comment]
I certainly was byte-compiling on an instance that had the package loaded. I didn't realize that byte-compiling is stateful. Apologies if I missed this in the instructions, this is the first package I'm trying to get on MELPA.

When you say "compiling from scratch", is there (eg) a command-line invocation to make this work? I was definitely just `M-x byte-compile-file`, which will not possibly work if you need the "stateless" output.

**Comment by cscheid** [comment]
I'm now using Cask, and the current version on `quarto-dev/quarto-emacs.git` builds without warnings for me locally.

**Comment by riscy** [comment]
I may have missed all of these last weekend (my apologies if that's the case), or things may have changed substantially since the last review -- here's what I'm currently seeing:

`quarto-mode.el` with checkdoc 0.6.2:
```
quarto-mode.el:138: All variables and subroutines might as well have a documentation string
quarto-mode.el:148: All variables and subroutines might as well have a documentation string
quarto-mode.el:165: All variables and subroutines might as well have a documentation string
quarto-mode.el:174: All variables and subroutines might as well have a documentation string
quarto-mode.el:245: Argument `begin-region' should appear (as BEGIN-REGION) in the doc string
quarto-mode.el:293: First line should be capitalized
quarto-mode.el:309: All variables and subroutines might as well have a documentation string
quarto-mode.el:314: First sentence should end with punctuation
quarto-mode.el:314: First line should be capitalized
quarto-mode.el:318: First sentence should end with punctuation
quarto-mode.el:318: First line should be capitalized
quarto-mode.el:264: Messages should start with a capital letter
quarto-mode.el:245: White space found at end of line
```

`quarto-mode.el` with package-lint 20220213.1457:
```
3 issues found:
213:8: error: You should depend on (emacs "25.1") if you need `make-process'.
222:6: error: You should depend on (emacs "25.1") if you need `make-process'.
302:2: warning: Closing parens should not be wrapped onto new lines.
```

`quarto-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
- quarto-mode.el#L304: It's safer to sharp-quote function names; use `#'`
- quarto-mode.el#L150: This double negation can be collapsed (`not` aliases `null`)
- quarto-mode.el#L261: No `format` required; `error` takes an f-string

In addition to these you should avoid adding advice and hooks when the mode is simply brought in; instead, you can do these things inside the minor mode.

**Comment by cscheid** [comment]
Thank you for the continued help and review. I assumed that `cask build` was running these checks, but clearly I'm wrong. I'll fix them asap.

**Comment by cscheid** [comment]
I've set up melpazoid CI (_thank you_, btw, CI support makes things a lot easier), and I fixed most issues.

However, I'm not sure what to do about hooks and advice. Specifically, I don't know what you mean by "you can do these things inside the minor mode". My advice function is checking for the case where `quarto-mode` is disabled and passing through the call in case. I looked around online for documentation on this and couldn't find much help. Could you point me in the right direction? Thanks again.

**Comment by riscy** [comment]
Apologies for being so brief at the end of that comment!  With regard to the *hook*, as I take another look I think that one's actually fine -- the package is adding a hook to its own mode.

With regard to the advice, I tend to comment on these because it's better if advice can be deferred for as long as possible, and it's best if a package can change as little of Emacs's behavior as possible when it's initially imported.  In this case, simply importing the package causes `fill-paragraph` to be wrapped in advice that (1) the user probably isn't aware of, (2) may create slowdowns that the user needn't pay for (yet), and (3) may cause bugs/interactions that are very difficult for novice users to track down.  I'm not saying 2 or 3 is the case with your code which actually look safe on first glance.  But the more packages that do this, the riskier it becomes.

I'm not yet familiar with how polymode defines modes, but I think the best case scenario would be if you could add this advice when one of the modes is activated.  This might not be realistic though.  Let me know if that's the case, and/or if the rationale above makes sense.  Otherwise I think we can just move ahead with the merge.

**Comment by cscheid** [comment]
Ok, I'm going to assume the hook needs no change.

With respect to the advice setting: would you feel comfortable if that same hook checked and installed the advice on being executed for the first time? It would solve the problem that people installing the package don't want the advice when the mode is not active, but it wouldn't solve the problem that the advice would still technically run after every buffer in quarto-mode has been shut down.

**Comment by riscy** [comment]
That sounds fine to me - and thank you very much for being understanding and accommodating.  You also may want to check out the `unload-feature` function that will give users a way of undoing some of this.  Here's an [example](https://github.com/riscy/shx-for-emacs/blob/master/shx.el#L1148-L1171).

**Comment by cscheid** [comment]
Got it. I expect to have these revisions done next week. Thanks again for your help.

**Comment by cscheid** [comment]
I've added a `quarto-mode-unload-function` and moved the advice addition to inside the hook behind a global check. [Melpazoid seems ok](https://github.com/quarto-dev/quarto-emacs/runs/5414600158) with [the changes](https://github.com/quarto-dev/quarto-emacs/commit/4d36898cf25a65c073f2ac966c06c865a1dd6890).

**Comment by riscy** [comment]
The latest shows a small byte-compile warning:
```
quarto-mode.el:327:11:Warning: assignment to free variable
    `quarto-mode-adviced-installed'
```
which I think is because of a typo (adviced instead of advice).  Should be easy to tackle that quickly, so I'll hit merge.

And, welcome to MELPA. :)

**Comment by cscheid** [comment]
I fixed the typo 🤦 . Thank you!!

**Pull request merged**
