### PR TITLE
Add helm-jira

### PR DESCRIPTION
**Pull request by DeX3**
### Brief summary of what the package does

Helm-bindings for interacting with JIRA issues and BitBucket/Stash Pull requests.

### Direct link to the package repository

https://github.com/DeX3/helm-jira

### Your association with the package

I'm the creator and maintainer of this package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

A little feedback:

In the defcustoms, you don't need `:initialize 'custom-initialize-set` or `:group 'helm-jira`.

**Comment by noctuid** [comment]
> If a defcustom does not specify any :group, the last group defined with defgroup in the same file will be used. This way, most defcustom do not need an explicit :group.

I didn't know this before today. Seems like this would be a good thing to check for in package-lint.

**Comment by alphapapa** [comment]
> Seems like this would be a good thing to check for in package-lint.

Occasionally it's necessary to specify it, but most of the time not.  Perhaps they would welcome a patch over there.  :)

**Comment by DeX3** [comment]
Nice, thanks for the feedback, I updated the package.

**Comment by purcell** [comment]
Thanks, particularly for your patience. This looks good, so merging now. You should consider adding `;;;###autoload` cookies for the various interactive commands that might be user-initiated entry points for the package.

**Comment by purcell** [comment]
And: welcome to MELPA! :tada:

**Pull request merged**
