### PR TITLE
Add recipe for run-command-recipes

### PR DESCRIPTION
**Pull request by semenInRussia**
### Brief summary of what the package does

This is collection of recipes to [run-command](https://github.com/bard/emacs-run-command).

### Direct link to the package repository

https://github.com/semenInRussia/emacs-run-command-recipes

### Your association with the package

I am the creator and maintainer of this package.

### Relevant communications with the upstream package maintainer
**None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Quick first pass below.  Also note I see a Package-Requires mismatch between run-command-recipes-haskell.el and run-command-recipes.el (the main file should specify the `Package-Requires` across all files).

`run-command-recipes-elisp.el` with package-lint 20211122.1152:
```
18 issues found:
7:0: error: Package-Requires outside the main file have no effect.
37:0: error: "rcr/elisp-modes" doesn't start with package's prefix "run-command-recipes".
37:0: error: `rcr/elisp-modes' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
43:0: error: "rcr/elisp-cask-project-p-function" doesn't start with package's prefix "run-command-recipes".
43:0: error: `rcr/elisp-cask-project-p-function' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
49:0: error: "rcr/elisp-cask-filename" doesn't start with package's prefix "run-command-recipes".
49:0: error: `rcr/elisp-cask-filename' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
55:0: error: "rcr/elisp-cask-project-p" doesn't start with package's prefix "run-command-recipes".
55:0: error: `rcr/elisp-cask-project-p' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
65:0: error: "rcr/elisp-file-was-compiled-p" doesn't start with package's prefix "run-command-recipes".
65:0: error: `rcr/elisp-file-was-compiled-p' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
71:0: error: "rcr/elisp-compile-current-file" doesn't start with package's prefix "run-command-recipes".
71:0: error: `rcr/elisp-compile-current-file' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
76:0: error: "rcr/elisp-recompile-current-file" doesn't start with package's prefix "run-command-recipes".
76:0: error: `rcr/elisp-recompile-current-file' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
81:0: error: "rcr/elisp-recompile-current-directory" doesn't start with package's prefix "run-command-recipes".
81:0: error: `rcr/elisp-recompile-current-directory' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
86:0: error: "run-command-recipe-elisp" doesn't start with package's prefix "run-command-recipes".
```

`run-command-recipes-elisp.el` with [melpazoid](https://github.com/riscy/melpazoid):
- run-command-recipes-elisp.el#L3: Have you done the paperwork to assign this copyright?

`run-command-recipes-files.el` with byte-compile using Emacs 27.1:
```
run-command-recipes-files.el:38:1:Warning: the function
    `projectile-acquire-root' is not known to be defined.
```

`run-command-recipes-files.el` with package-lint 20211122.1152:
```
3 issues found:
7:0: error: Package-Requires outside the main file have no effect.
29:0: error: "rcr/project-root" doesn't start with package's prefix "run-command-recipes".
29:0: error: `rcr/project-root' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
```

`run-command-recipes-files.el` with [melpazoid](https://github.com/riscy/melpazoid):
- run-command-recipes-files.el#L3: Have you done the paperwork to assign this copyright?

`run-command-recipes-hashtables.el` with package-lint 20211122.1152:
```
3 issues found:
8:0: error: Package-Requires outside the main file have no effect.
29:0: error: "rcr/hashtable-put" doesn't start with package's prefix "run-command-recipes".
29:0: error: `rcr/hashtable-put' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
```

`run-command-recipes-hashtables.el` with [melpazoid](https://github.com/riscy/melpazoid):
- run-command-recipes-hashtables.el#L3: Have you done the paperwork to assign this copyright?

`run-command-recipes-haskell.el` with byte-compile using Emacs 27.1:
```
run-command-recipes-haskell.el:38:1:Error: Cannot open load file: No such file or directory, haskell-mode
```

`run-command-recipes-haskell.el` with package-lint 20211122.1152:
```
9 issues found:
7:0: error: Package-Requires outside the main file have no effect.
41:0: error: "rcr/haskell-complie-function" doesn't start with package's prefix "run-command-recipes".
41:0: error: `rcr/haskell-complie-function' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
47:0: error: "rcr/haskell-modes" doesn't start with package's prefix "run-command-recipes".
47:0: error: `rcr/haskell-modes' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
53:0: error: "rcr/haskell-mode-p" doesn't start with package's prefix "run-command-recipes".
53:0: error: `rcr/haskell-mode-p' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
60:0: error: "run-command-recipe-haskell" doesn't start with package's prefix "run-command-recipes".
71:4: warning: Closing parens should not be wrapped onto new lines.
```

`run-command-recipes-haskell.el` with [melpazoid](https://github.com/riscy/melpazoid):
- run-command-recipes-haskell.el#L3: Have you done the paperwork to assign this copyright?

`run-command-recipes-latex.el` with package-lint 20211122.1152:
```
6 issues found:
7:0: error: Package-Requires outside the main file have no effect.
38:0: error: "rcr/pdflatex-command" doesn't start with package's prefix "run-command-recipes".
38:0: error: `rcr/pdflatex-command' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
48:0: error: "rcr/tex-modes" doesn't start with package's prefix "run-command-recipes".
48:0: error: `rcr/tex-modes' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
54:0: error: "run-command-recipe-latex" doesn't start with package's prefix "run-command-recipes".
```

`run-command-recipes-latex.el` with [melpazoid](https://github.com/riscy/melpazoid):
- run-command-recipes-latex.el#L3: Have you done the paperwork to assign this copyright?

`run-command-recipes-pandoc.el` with package-lint 20211122.1152:
```
16 issues found:
7:0: error: Package-Requires outside the main file have no effect.
43:0: error: "rcr/pandoc-output-formats" doesn't start with package's prefix "run-command-recipes".
43:0: error: `rcr/pandoc-output-formats' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
98:0: error: "rcr/html-modes" doesn't start with package's prefix "run-command-recipes".
98:0: error: `rcr/html-modes' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
104:0: error: "rcr/pandoc-formats-and-extensions" doesn't start with package's prefix "run-command-recipes".
104:0: error: `rcr/pandoc-formats-and-extensions' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
122:0: error: "rcr/add-modes-with-format-to-table" doesn't start with package's prefix "run-command-recipes".
122:0: error: `rcr/add-modes-with-format-to-table' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
131:0: error: "rcr/pandoc-major-modes-input-formats" doesn't start with package's prefix "run-command-recipes".
131:0: error: `rcr/pandoc-major-modes-input-formats' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
151:0: error: "rcr/pandoc-change-format-of-file" doesn't start with package's prefix "run-command-recipes".
151:0: error: `rcr/pandoc-change-format-of-file' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
158:0: error: "rcr/pandoc-format-for-major-mode" doesn't start with package's prefix "run-command-recipes".
158:0: error: `rcr/pandoc-format-for-major-mode' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
164:0: error: "run-command-recipe-pandoc" doesn't start with package's prefix "run-command-recipes".
```

`run-command-recipes-pandoc.el` with [melpazoid](https://github.com/riscy/melpazoid):
- run-command-recipes-pandoc.el#L3: Have you done the paperwork to assign this copyright?

`run-command-recipes.el` with package-lint 20211122.1152:
```
3 issues found:
52:0: error: "rcr" doesn't start with package's prefix "run-command-recipes".
63:0: error: "rcr/supported-recipes" doesn't start with package's prefix "run-command-recipes".
63:0: error: `rcr/supported-recipes' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
```

`run-command-recipes.el` with [melpazoid](https://github.com/riscy/melpazoid):
- run-command-recipes.el#L3: Have you done the paperwork to assign this copyright?

**Comment by semenInRussia** [comment]
All fixed!

p.s.
Thank you for `melpazoid`, I think melpa's contributors must add "`melpazoid` is happy with my beautiful code"  to Pull Request's todo list

**Comment by riscy** [comment]
Thanks for saying so!  It would probably be a good idea for us to throw _something_ like this into CI checks.  I guess one thing that holds it back is in about 5% of cases some important checks will fail even though nothing's "wrong" due to idiosyncrasies in the Emacs ecosystem, so we'd have to build out some kind of a way to make exceptions.

That said, here's another quick pass --

`run-command-recipes-elisp.el` with package-lint 20211122.1152:
```
1 issue found:
128:0: error: "run-command-recipe-elisp" doesn't start with package's prefix "run-command-recipes".
```

`run-command-recipes-elisp.el` with [melpazoid](https://github.com/riscy/melpazoid):
- run-command-recipes-elisp.el#L122: It's safer to sharp-quote function names; use `#'`

`run-command-recipes-haskell.el` with package-lint 20211122.1152:
```
1 issue found:
60:0: error: "run-command-recipe-haskell" doesn't start with package's prefix "run-command-recipes".
```

`run-command-recipes-latex.el` with package-lint 20211122.1152:
```
1 issue found:
53:0: error: "run-command-recipe-latex" doesn't start with package's prefix "run-command-recipes".
```

`run-command-recipes-pandoc.el` with package-lint 20211122.1152:
```
1 issue found:
165:0: error: "run-command-recipe-pandoc" doesn't start with package's prefix "run-command-recipes".
```

`load`-check on each file:
```
Loading run-command-recipes-haskell.el
  run-command-recipes-haskell.el:Error: Emacs 27.1 couldn't load:
  (user-error "Run-command-recipes-haskell.el: Install `haskell-mode', faster!")
```
I think this is fine in this case, but in larger cases we'd probably suggest splitting something like this out into its own package with an explicit dependency.  Not a blocker, just an fyi... but on a quick glance you should note the function name here is `run-command-recipes-haskell-complie-function` which misspells "compile".

Package and license:
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible

**Comment by semenInRussia** [comment]
All fixed, (again).

Thank You (again)!

Sorry for use names as `run-command-recipe-latex`, I am use standard declared in `run-command`, I am think this is good.

Sorry for "compile", My english isn't good, I am rename this to "run"

**Comment by riscy** [comment]
Looks good to merge.  Thanks for this -- and welcome to MELPA. :)

A couple more minor notes:
- I'd encourage removing the dependency on `s` -- both of `s-concat`, `s-upcase` have builtin equivalents (`concat`, `upcase`)
- run-command-recipes-elisp.el#L122: There is no need to quote lambdas (neither #' nor ') -- this line could in fact be changed from `#'(lambda () (call-interactively 'ert))` to `(lambda () (call-interactively #'ert))`
- I was looking around at similar packages in the space and https://github.com/p3r7/friendly-shell looks like it may be interesting to you.

**Comment by semenInRussia** [comment]
Thank you, this package really interesting for me!

**Pull request merged**
