### PR TITLE
add company-erlang recipe

### PR DESCRIPTION
**Pull request by s-kostyaev**
### Brief summary of what the package does

`company-erlang` is company backend for erlang based on `ivy-erlang-complete`.

### Direct link to the package repository

https://github.com/s-kostyaev/company-erlang

### Your association with the package

I am the author.

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Could you remove pkg file from repository ? It is enough to use package header of `company-erlang.el`.

**Comment by s-kostyaev** [comment]
@syohex done.

**Comment by syohex** [comment]
Merged

**Comment by s-kostyaev** [comment]
Thanks

**Comment by purcell** [comment]
I'd suggest you apply version tags to both this and `ivy-erlang-complete`, so that you can depend on a non-snapshot version of the latter from this package, and so that both get included in MELPA Stable.

**Comment by s-kostyaev** [comment]
I think it's good idea. Where can I read how to do this?

**Comment by purcell** [comment]
Just add git tags, e.g. "0.1" or "v1.2", then use those numbers (rather than snapshot version numbers) when specifying dependencies in `Package-Requires:` headers. Packages for which there are version tags are automatically included in MELPA Stable, without any further steps being necessary on your part.

**Comment by s-kostyaev** [comment]
@purcell thanks for clarifying. Done.

**Pull request merged**
