### PR TITLE
Add recipe for minad/vertico.

### PR DESCRIPTION
**Pull request by milkypostman**
### Brief summary of what the package does

Very simple vertical completion package. From the author that brought you *marginalia* and *consult*.

Tagging @minad here because I was surprised to find that this package wasn't already in MELPA.

### Direct link to the package repository

https://github.com/minad/vertico

### Your association with the package

enthusiastic user

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by minad** [comment]
I intentionally didn't submit it here for now since the package is on GNU ELPA. Some of my packages are on both MELPA and GNU ELPA, some only on ELPA, some only on MELPA. I have yet to figure out the best way to distribute packages.

I like that MELPA distributes nightly builds in case users want to get access to the bleeding edge version. Furthermore MELPA offers download statistics and help a bit regarding visibility of packages. On the other hand there exists also elpa-devel, which also distributes nightly builds. elpa-devel sees far less usage than MELPA though and it does not hurt to have multiple distribution channels. Overall I am undecided about this.

(If Vertico gets added here, I would probably also add my [Corfu](https://github.com/minad/corfu) package here, just to be a bit more consistent.)

**Comment by milkypostman** [comment]
I’m happy to use elpa-devel. Is there a link somewhere? 

I think saying that if a package is in elpa-devel then it doesn’t really need to be in MELPA. I didn’t know about that though.

**Comment by minad** [comment]
> I think saying that if a package is in elpa-devel then it doesn’t really need to be in MELPA.

Well, every ELPA package is available on ELPA-devel. So this is a bit of a general question - does it make sense to kick out every ELPA package from MELPA? There is one crucial difference - MELPA promotes to use the nightly packages, simply by the fact that MELPA has the two archives MELPA/MELPA-stable in contrast to having MELPA and a MELPA-devel/unstable.

> I’m happy to use elpa-devel. Is there a link somewhere?

There is a badge in the vertico README right at the top: https://github.com/minad/vertico

**Comment by milkypostman** [comment]
`https://elpa.gnu.org/devel/archive-contents` is the path to the `archive-contents` for devel.

It's weird that it's not better advertised. And yes, I agree with what you say about MELPA/stable and ELPA/devel. The contrast is there due to necessity.

I am now a bit more motivated to get MELPA with similar versioning working. At least as a goal because I see that **I** personally would use elpa-devel and MELPA together.

I do think that once a package moves to ELPA we probably don't need to keep it in MELPA unless it starts to go unmaintained.

**Pull request closed without merging**
