### PR TITLE
Recipe: Add bufler

### PR DESCRIPTION
**Pull request by alphapapa**
### Brief summary of what the package does

Bufler is like a butler for your buffers, presenting them to you in an organized way based on your instructions. The instructions are written as grouping rules in a simple language, allowing you to customize the way buffers are grouped. The default rules are designed to be generally useful, so you don’t have to write your own.

It also provides a workspace mode which allows frames to focus on buffers in certain groups. Since the groups are created automatically, the workspaces are created dynamically, rather than requiring you to put buffers in workspaces manually.

### Direct link to the package repository

https://github.com/alphapapa/bufler.el

### Your association with the package

Author and maintainer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please check your recipe. Do you really want to bundle `helm-bufler` to this package?
```
$ make recipes/bufler
 • Building package bufler ...
Package: bufler
Fetcher: github
Source:  https://github.com/alphapapa/bufler.el.git

Cloning https://github.com/alphapapa/bufler.el.git to /home/conao/dev/forks/melpa/working/bufler/
Copying files (->) and directories (=>)
  from /home/conao/dev/forks/melpa/working/bufler/
  to /tmp/buflerBzubX0/bufler-20200301.1257
    bufler-group-tree.el -> bufler-group-tree.el
    bufler-workspace.el -> bufler-workspace.el
    bufler.el -> bufler.el
    helm-bufler.el -> helm-bufler.el
    bufler.info -> bufler.info
Built bufler in 15.670s, finished at Mon Mar  2 17:25:07 2020
 ✓ Success:
4.0K -rw-r--r-- 1 conao conao 413  3月  2 17:24 packages/bufler-20200301.1257.entry
 80K -rw-r--r-- 1 conao conao 80K  3月  2 17:24 packages/bufler-20200301.1257.tar
4.0K -rw-r--r-- 1 conao conao 969  3月  2 17:25 packages/bufler-badge.svg
4.0K -rw-r--r-- 1 conao conao 575  3月  2 17:24 packages/bufler-readme.txt
```

**Comment by alphapapa** [comment]
> 1. Please check your recipe. Do you really want to bundle `helm-bufler` to this package?

Yes, as you can see in `helm-bufler.el`, I have taken great care to ensure that it works properly with or without `helm` installed, with no warnings or errors in either case.  Users who have and load Helm will find the variable and function defined; those who do not will not.

**Comment by conao3** [comment]
OK, then I suggest moving `defun` out of `when` to silence byte-compiler.

## before
```shell
$ cask; cask build
Loading package information... done
Package operations: 5 installs, 0 removals
  - Installing [ 1/5] magit-section (0.1)... already present
  - Installing [ 2/5] f (0.17)... already present
  - Installing [ 3/5] dash-functional (2.17)... already present
  - Installing [ 4/5] dash (2.17)... already present
  - Installing [ 5/5] emacs (26.3)... already present
Compiling /home/conao/dev/forks/bufler.el/bufler-group-tree.el...
Compiling /home/conao/dev/forks/bufler.el/bufler-workspace.el...
Compiling /home/conao/dev/forks/bufler.el/bufler.el...
Compiling /home/conao/dev/forks/bufler.el/helm-bufler.el...

In end of data:
helm-bufler.el:88:1:Warning: the function ‘helm-bufler-switch-buffer’ is not
    known to be defined.
```
## after
```shell
$ cask; cask build
Loading package information... done
Package operations: 5 installs, 0 removals
  - Installing [ 1/5] magit-section (0.1)... already present
  - Installing [ 2/5] f (0.17)... already present
  - Installing [ 3/5] dash-functional (2.17)... already present
  - Installing [ 4/5] dash (2.17)... already present
  - Installing [ 5/5] emacs (26.3)... already present
Compiling /home/conao/dev/forks/bufler.el/bufler-group-tree.el...
Compiling /home/conao/dev/forks/bufler.el/bufler-workspace.el...
Compiling /home/conao/dev/forks/bufler.el/bufler.el...
Compiling /home/conao/dev/forks/bufler.el/helm-bufler.el...
```
## diff
```diff
new file   Cask
@@ -0,0 +1,4 @@
+(source gnu)
+(source melpa)
+
+(package-file "bufler.el")

modified   helm-bufler.el
@@ -42,26 +42,26 @@
   (defvar helm-type-buffer-actions)
   (declare-function helm-make-source "helm-source" t t)
 
+  (defun helm-bufler-switch-buffer (buffer)
+    "Switch to BUFFER.
+With two universal prefixes, also set the frame's workspace.
+This mimics `bufler-workspace-switch-buffer'."
+    (when (equal '(16) current-prefix-arg)
+      (bufler-workspace-frame-set
+       ;; FIXME: Ideally we wouldn't call `bufler-buffers' again
+       ;; here, but `bufler-buffer-alist-at' returns a slightly
+       ;; different structure, and `bufler-group-tree-leaf-path'
+       ;; doesn't accept it.  Maybe the issue is related to using
+       ;; `map-nested-elt' in `bufler-buffer-alist-at'.  Maybe
+       ;; that difference has been the source of some other
+       ;; confusion too...
+       (butlast (bufler-group-tree-leaf-path (bufler-buffers) buffer))))
+    (switch-to-buffer buffer))
+
   (when (require 'helm nil 'noerror)
 
     (require 'helm-types)
 
-    (defun helm-bufler-switch-buffer (buffer)
-      "Switch to BUFFER.
-With two universal prefixes, also set the frame's workspace.
-This mimics `bufler-workspace-switch-buffer'."
-      (when (equal '(16) current-prefix-arg)
-        (bufler-workspace-frame-set
-         ;; FIXME: Ideally we wouldn't call `bufler-buffers' again
-         ;; here, but `bufler-buffer-alist-at' returns a slightly
-         ;; different structure, and `bufler-group-tree-leaf-path'
-         ;; doesn't accept it.  Maybe the issue is related to using
-         ;; `map-nested-elt' in `bufler-buffer-alist-at'.  Maybe
-         ;; that difference has been the source of some other
-         ;; confusion too...
-         (butlast (bufler-group-tree-leaf-path (bufler-buffers) buffer))))
-      (switch-to-buffer buffer))
-
     (defvar helm-bufler-source
       (helm-make-source "Bufler's workspace buffers" 'helm-source-sync
         :header-name (lambda (_name)
```

Also, I recommend creating a separate package called `helm-bufler` to take care of `ivy` users.

**Comment by alphapapa** [comment]
> ```shell
> helm-bufler.el:88:1:Warning: the function ‘helm-bufler-switch-buffer’ is not
>     known to be defined.
> ```

The warning is fixed.  Thanks for pointing it out.

> Also, I recommend creating a separate package called helm-bufler to take care of ivy users.

I'm not planning to make a separate package for one function and one variable when it's already handled cleanly now.

I don't know what you mean about Ivy.  Bufler already works with Ivy, as documented in the readme.

**Comment by riscy** [comment]
A minor nag from the ghost of Emacs 26.3:
```
bufler-workspace-tabs.el:110:17:Warning: assignment to free variable
    `tab-bar-separator'
```
I think that one's just a simple defvar.

I notice that each of the files (except bufler-workspace-tabs.el) has a `Package-Requires` and they're different from bufler.el's.  Of course, as long as the bufler.el `Package-Requires` is maintained as a superset of all the others it's fine, but it's something I mention because there have been mistakes in the past.

This is a quick merge after the tab-bar-separator nag, so ping me!

**Comment by alphapapa** [comment]
@riscy Oops, I keep making changes after linting and then forget to relint.  The warning is fixed, thanks.

The `Package-Requires` headers in the other files were incidental, and I removed them for clarity.

Thanks.

**Pull request merged**
