### PR TITLE
add clhs - common lisp hyperspec interface

### PR DESCRIPTION
**Pull request by sam-s**
### Brief summary of what the package does

Access the Common Lisp HyperSpec (CLHS)

### Direct link to the package repository

https://gitlab.com/sam-s/clhs

### Your association with the package

author/maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by lassik** [comment]
SLIME comes with a [`hyperspec.el`](https://github.com/slime/slime/blob/master/lib/hyperspec.el) that's self-contained and doesn't depend on the rest of SLIME.

Could we merge your package into it? If people want to browse CLHS without installing SLIME, we could convince the SLIME folks to extract the file into its own Emacs package.

**Comment by sam-s** [comment]
SLIME's `hyperspec.el` is the old version and only supports 8.3 file names.
My version supports both the original long file names and the new 8.3 ones (as well as any future compliant version).

The correct approach is to remove `hyperspec` from SLIME and [Sly](https://github.com/joaotavora/sly/blob/master/lib/hyperspec.el) and make both of them depend on `clhs`.

**Comment by lassik** [comment]
Could also email the list at https://mailman.common-lisp.net/pipermail/slime-devel/

(Wow, just realized that you wrote large parts of CLISP! I'm not worthy :-)

**Comment by riscy** [comment]
This looks good to me, and thanks for your close adherence to the checklist.

Usually we recommend adding a LICENSE file to the repository -- ideally one that is standard and detectable by common tooling.  I also notice you mention the GPL in your boilerplate but there remains some small ambiguity (which version of the GPL?) that you could clear up with a standardized license identifier like `;; SPDX-License-Identifier: GPL-3.0-or-later` from https://spdx.dev/ids/.

**Comment by lassik** [comment]
Comments from the SLIME maintainers in [this thread](https://github.com/slime/slime/issues/615):

> In any case, that new clhs package has the drawback (IMHO) that it requires downloading and parsing the hyperspec symbol table for each Emacs session. I don't think we want to bother with it at this point. Thanks for letting us know, though.

**Comment by lassik** [comment]
Currently both [SLIME](https://github.com/slime/slime) and [SLY](https://github.com/joaotavora/sly) ship a copy of `hyperspec.el`. Each would like to keep its copy so that their packages are easier to run from directly from git. For MELPA, the result is that there are now duplicate copies of `hyperspec.el`, and `clhs.el` would be a third file with the same purpose.

SLIME's maintainer suggests one solution is to keep a copy of `hyperspec.el` in their git repo but tweak the file glob in the MELPA recipe so that file is not installed by the `slime` MELPA package. This seems reasonable to me.

**Comment by riscy** [comment]
Thanks a ton for that information, @lassik -- hugely appreciated.  As a relative outsider I think I can summarize this as:

clhs supports both the original long file names and the new 8.3 ones (as well as any future compliant version), and also downloads and parses the hyperspec symbol table for each Emacs session, which some users of hyperspec.el will see as a drawback.

> For MELPA, the result is that there are now duplicate copies of hyperspec.el, and clhs.el would be a third file with the same purpose.
> SLIME's maintainer suggests one solution is to keep a copy of hyperspec.el in their git repo but tweak the file glob in the MELPA recipe so that file is not installed by the slime MELPA package

I figure adding this is not a bad idea, and clhs is already in the Emacsmirror (but I'll hold off merging until the licensing is clarified above).  Regarding the duplication of hyperspec.el, I think there are two options if the maintainers want to improve the status quo:

- extract hyperspec.el into its own package, and then both SLY and SLIME could depend on it (and tweak the file glob in their recipes, as you suggested)
- modify hyperspec.el in each case to use the package's namespace, leaving each package free to make independent behavioral changes

**Comment by lassik** [comment]
> * extract hyperspec.el into its own package, and then both SLY and SLIME could depend on it (and tweak the file glob in their recipes, as you suggested)

Yes, IMHO that's the best idea.

> * modify hyperspec.el in each case to use the package's namespace, leaving each package free to make independent behavioral changes

That would work, but the SLIME and SLY maintainers seems quite conservative so it's unlikely they'd prefer major changes to the interface.

Could we work to establish a common home for the hyperspec package, and integrate @sam-s 's improvements into it? Since SLIME is opposed to the requirement to download and parse the hyperspec, could we make that optional and bundle a default symbol table with the package?

From a user's point of view, all three packages (SLIME hyperspec, SLY hyperspec, and the new clhs) do exactly the same thing.

**Comment by purcell** [comment]
Agree `hyperspec.el` should be its own package, and we can merge this in the meantime. Welcome to MELPA, @sam-s! :tada:wew

**Pull request merged**
