### PR TITLE
Add empv recipe

### PR DESCRIPTION
**Pull request by isamert**
### Brief summary of what the package does

Emacs media player, media library manager, radio player, YouTube
frontend. It let's you play any type of media with a focus on
completing-read based interface. Uses mpv as it's backend.

### Direct link to the package repository

https://github.com/isamert/empv.el

### Your association with the package

I am the maintainer of this package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### Extra notes

There are some byte-compile warnings but that's due to `embark` and
`consult` packages being optional dependencies of this package, the
package works fine without these dependencies and integrates with them
if they are installed. Let me know if this is a problem for you and if
there are any workarounds that I can apply. I am aware of the
`declare-function` macro but most of the warnings stem from `embark`'s
`embark-define-keymap` and `declare-function` can not fix them.

Also there are some info-level issues that checkdoc reports, I hope
these are fine.

### CODE REVIEW

**Comment by riscy** [comment]
Re: `declare-function`/`defvar`, I think it is better for maintainers to apply these wherever they can -- it ensures all of the issues are at least accounted for and understood.  Macros can be problematic like you said, but let's see how far we can get.

Re: the checkdoc, it's best if you can fix as many of those as feasible -- we ask the same of all contributors.  If it's possible to fix, I'd rather we fix it than ignore the checkdoc output.  There's good justification for even its info-level warnings.

Here's a quick first pass:

`empv.el` with byte-compile using Emacs 28.1:
```
empv.el:1502:8: Warning: `"y"' is a malformed function
empv.el:1502:8: Warning: `"e"' is a malformed function
empv.el:1502:8: Warning: `"n"' is a malformed function
empv.el:1502:8: Warning: `"p"' is a malformed function
empv.el:1502:8: Warning: `"c"' is a malformed function
empv.el:1502:8: Warning: `"e"' is a malformed function
empv.el:1502:8: Warning: `"n"' is a malformed function
empv.el:1502:8: Warning: `"p"' is a malformed function
empv.el:1502:8: Warning: `"p"' is a malformed function
empv.el:1502:8: Warning: `"y"' is a malformed function
empv.el:1502:8: Warning: `"m"' is a malformed function
empv.el:1502:8: Warning: `"r"' is a malformed function
empv.el:1502:8: Warning: `"R"' is a malformed function
empv.el:1510:59: Warning: reference to free variable
    `empv-embark-youtube-item-actions'
empv.el:1505:10: Warning: reference to free variable `empv-youtube-copy-link'
empv.el:1506:10: Warning: reference to free variable `empv-enqueue'
empv.el:1507:10: Warning: reference to free variable `empv-enqueue-next'
empv.el:1508:10: Warning: reference to free variable `empv-play'
empv.el:1509:10: Warning: reference to free variable
    `empv-youtube-show-comments'
empv.el:1510:17: Warning: reference to free variable `embark-keymap-alist'
empv.el:1528:17: Warning: assignment to free variable `embark-keymap-alist'
empv.el:1511:39: Warning: reference to free variable
    `embark-transformer-alist'
empv.el:1529:40: Warning: assignment to free variable
    `embark-transformer-alist'
empv.el:1518:57: Warning: reference to free variable
    `empv-embark-radio-item-actions'
empv.el:1521:25: Warning: reference to free variable
    `empv-embark-playlist-item-actions'
empv.el:1523:10: Warning: reference to free variable `empv-playlist-play'
empv.el:1524:10: Warning: reference to free variable `empv-playlist-copy-path'
empv.el:1525:10: Warning: reference to free variable `empv-playlist-move'
empv.el:1526:10: Warning: reference to free variable `empv-playlist-remove'
empv.el:1527:10: Warning: reference to free variable
    `empv-playlist-remove-others'
empv.el:1533:15: Warning: reference to free variable `embark-file-map'
empv.el:1537:15: Warning: reference to free variable `embark-url-map'
In end of data:
empv.el:1558:6: Warning: the function `consult--async-sink' is not known to be
    defined.
empv.el:1559:6: Warning: the function `consult--async-refresh-immediate' is
    not known to be defined.
empv.el:1561:6: Warning: the function `consult--async-throttle' is not known
    to be defined.
empv.el:1562:6: Warning: the function `consult--async-split' is not known to
    be defined.
empv.el:1551:42: Warning: the function `consult--async-split-initial' is not
    known to be defined.
empv.el:1550:19: Warning: the function `consult--lookup-member' is not known
    to be defined.
empv.el:1545:4: Warning: the function `consult--read' is not known to be
    defined.
empv.el:1503:4: Warning: the function `embark-define-keymap' is not known to
    be defined.
```

`empv.el` with checkdoc 0.6.2:
```
empv.el:48: First sentence should end with punctuation
empv.el:62: First line is not a complete sentence
empv.el:69: First line is not a complete sentence
empv.el:90: Symbols t and nil should not appear in single quotes
empv.el:169: First line is not a complete sentence
empv.el:177: First line is not a complete sentence
empv.el:255: First line is not a complete sentence
empv.el:263: First line is not a complete sentence
empv.el:263: Some lines are over 80 columns wide
empv.el:290: First line is not a complete sentence
empv.el:364: All variables and subroutines might as well have a documentation string
empv.el:401: All variables and subroutines might as well have a documentation string
empv.el:487: All variables and subroutines might as well have a documentation string
empv.el:509: All variables and subroutines might as well have a documentation string
empv.el:526: All variables and subroutines might as well have a documentation string
empv.el:535: All variables and subroutines might as well have a documentation string
empv.el:606: First line is not a complete sentence
empv.el:648: First line is not a complete sentence
empv.el:648: Argument `prompt' should appear (as PROMPT) in the doc string
empv.el:683: First line is not a complete sentence
empv.el:773: First sentence should end with punctuation
empv.el:782: First sentence should end with punctuation
empv.el:791: First sentence should end with punctuation
empv.el:797: First sentence should end with punctuation
empv.el:906: First line is not a complete sentence
empv.el:906: Argument `uri' should appear (as URI) in the doc string
empv.el:955: First sentence should end with punctuation
empv.el:962: First sentence should end with punctuation
empv.el:998: All variables and subroutines might as well have a documentation string
empv.el:1030: All variables and subroutines might as well have a documentation string
empv.el:1070: All variables and subroutines might as well have a documentation string
empv.el:1195: First line is not a complete sentence
empv.el:1203: First line is not a complete sentence
empv.el:1203: Argument `video-id' should appear (as VIDEO-ID) in the doc string
empv.el:1316: All variables and subroutines might as well have a documentation string
empv.el:1320: All variables and subroutines might as well have a documentation string
empv.el:1383: All variables and subroutines might as well have a documentation string
empv.el:1390: All variables and subroutines might as well have a documentation string
empv.el:1393: All interactive functions should have documentation
empv.el:1397: All interactive functions should have documentation
empv.el:1401: All interactive functions should have documentation
empv.el:1405: All interactive functions should have documentation
empv.el:1409: All interactive functions should have documentation
empv.el:1413: All interactive functions should have documentation
empv.el:1438: First line is not a complete sentence
empv.el:1456: All variables and subroutines might as well have a documentation string
empv.el:1461: All variables and subroutines might as well have a documentation string
empv.el:1464: All variables and subroutines might as well have a documentation string
empv.el:1467: All variables and subroutines might as well have a documentation string
empv.el:1478: All variables and subroutines might as well have a documentation string
empv.el:1482: All variables and subroutines might as well have a documentation string
empv.el:1489: Argument `type' should appear (as TYPE) in the doc string
empv.el:1493: Argument `type' should appear (as TYPE) in the doc string
empv.el:1497: Argument `type' should appear (as TYPE) in the doc string
empv.el:1503: All variables and subroutines might as well have a documentation string
empv.el:1544: Argument `prompt' should appear (as PROMPT) in the doc string
empv.el:1557: All variables and subroutines might as well have a documentation string
empv.el:1582: All variables and subroutines might as well have a documentation string
```

`empv.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- empv.el#L334: It's safer to sharp-quote function names; use `#'`
- empv.el#L343: It's safer to sharp-quote function names; use `#'`
- empv.el#L347: It's safer to sharp-quote function names; use `#'`
- empv.el#L981: It's safer to sharp-quote function names; use `#'`
- empv.el#L51: Use `(temporary-file-directory)` instead of /tmp in code
- empv.el#L342: Consider using %F instead of %Y-%m-%d in time strings
- empv.el#L884: Consider using %F instead of %Y-%m-%d in time strings
- empv.el#L342: Consider using %T instead of %H:%M:%S in time strings
- empv.el#L342: Consider using %R instead of %H:%M in time strings
- empv.el#L884: Consider using %R instead of %H:%M in time strings
```

**Comment by progfolio** [comment]
IMO it's best to provide separate recipes for optional dependencies, even if the source code is all managed in the same repository. Two separate features, empv-embark and empv-consult, could be maintained in their own files and declare empv as a dependency.

**Comment by progfolio** [comment]
I notice is you sleep for a hard-coded 1.5 seconds in `empv-start`. 
A (slightly) more robust approach would be to repeatedly send commands until you get a response.
I do that in a personal package I wrote for mpv/Emacs integration:

https://github.com/progfolio/emp/blob/9269b21faa9bf77d2a7b9593889d1b31d7854951/emp.el#L125-L127

With that approach you don't have to wait as long and an error can be reliably signaled when it times out.

**Comment by riscy** [comment]
Good, attentive advice from @progfolio.  It's been a bit since we've heard back, so I'll mark this awaiting-upstream for now.  Feel free to reach out, @isamert.

**Comment by isamert** [comment]
I'm in the middle of moving into another country, so I can't really progress here. I'll let you know when it's ready. Also, thanks for the tips and the report!

**Comment by isamert** [comment]
I made a few changes:
- Cleared all melpazoid and byte-compile warnings.
- Only checkdoc warnings are undocumented functions now, no other style issues.
- Moved `embark` support to it's own file, `empv-embark.el`.
- Left `consut` support as-is, because it requires more work to move it into another file but no byte-compile warnings are present. Used `declare-function` to get around that.

I have one question though: Should I add another recipe for `empv-embark` or let the recipe stay as is so that when user installs `empv`, `empv-embark` will be fetched too, and user can simply do `(require 'empv-embark)` if they want to activate it. What are your opinions on this? @riscy @progfolio

**Comment by progfolio** [comment]
You'll want to add embark as a dependency of empv-embark.el. Otherwise package managers (at least Elpaca and straight.el) will throw byte-compilation errors when attempting to install the package. e.g.



<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (straight-use-package
   '(empv :protocol https :depth 1 :package "empv" :host github :repo "isamert/empv.el"))
  (with-current-buffer straight-byte-compilation-buffer
    (message "%S"
             (buffer-substring-no-properties
              (point-min)
              (point-max)))))
```
</details>

- Test run at: `2023-01-22 12:56:15`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) ce7bb7a 2023-01-08`
- emacs-version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-01-08`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 3fa415c 2023-01-20
Cloning empv.el...
Cloning empv.el...done
Building empv...
Building empv...done

"
$ /usr/bin/emacs -Q -L /tmp/straight.el-test-5h8dYv/straight/build/straight/ --batch --eval \\
 \"(let ((default-directory \\\"/tmp/straight.el-test-5h8dYv/straight/build/\\\"))
  (normal-top-level-add-subdirs-to-load-path)
  (byte-recompile-directory \\\"/tmp/straight.el-test-5h8dYv/straight/build/straight/\\\" 0 'force))\"
Checking /tmp/straight.el-test-5h8dYv/straight/build/straight/...
Compiling /tmp/straight.el-test-5h8dYv/straight/build/straight/straight-autoloads.el...
Compiling /tmp/straight.el-test-5h8dYv/straight/build/straight/straight-ert-print-hack.el...
Compiling /tmp/straight.el-test-5h8dYv/straight/build/straight/straight-x.el...
Compiling /tmp/straight.el-test-5h8dYv/straight/build/straight/straight.el...
Done (Total of 3 files compiled, 1 skipped)

$ /usr/bin/emacs -Q -L /tmp/straight.el-test-5h8dYv/straight/build/empv/ --batch --eval \\
 \"(let ((default-directory \\\"/tmp/straight.el-test-5h8dYv/straight/build/\\\"))
  (normal-top-level-add-subdirs-to-load-path)
  (byte-recompile-directory \\\"/tmp/straight.el-test-5h8dYv/straight/build/empv/\\\" 0 'force))\"
Checking /tmp/straight.el-test-5h8dYv/straight/build/empv/...
Compiling /tmp/straight.el-test-5h8dYv/straight/build/empv/empv-autoloads.el...
Compiling /tmp/straight.el-test-5h8dYv/straight/build/empv/empv-embark.el...

In toplevel form:
empv-embark.el:34:2: Error: Cannot open load file: No such file or directory, embark
Compiling /tmp/straight.el-test-5h8dYv/straight/build/empv/empv.el...
Done (Total of 1 file compiled, 1 failed, 1 skipped)
"
Packages:
"straight"                n/a                  develop 3fa415c 2023-01-20
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 10f16723 2023-01-21
"gnu-elpa-mirror"         n/a                  master eb11995 2022-12-15
"nongnu-elpa"             n/a                  main 0e54bf5f6d 2023-01-07
"el-get"                  melpa                master 837fcbb8 2023-01-04
"emacsmirror-mirror"      n/a                  master a2d65d0 2023-01-11
"empv"                    n/a                  main c127a6c 2023-01-22


```
</details>

> Left consult support as-is, because it requires more work to move it into another file but no byte-compile warnings are present. Used declare-function to get around that.

I would remedy this similarly to the embark integration. Whatever code relies directly on consult should be written to instead use the built-in completing-read API. A separate feature can enhance as necessary. I took a brief look at the consult integration and it looks like you are relying on many internal (denoted by the `--` in the symbol name) details of consult:

    (declare-function consult--read "consult")
    (declare-function consult--lookup-member "consult")
    (declare-function consult--async-split-initial "consult")
    (declare-function consult--async-sink "consult")
    (declare-function consult--async-refresh-immediate "consult")
    (declare-function consult--async-throttle "consult")
    (declare-function consult--async-split "consult")
    
That's a code smell that the integration should be refactored.
Breaking it out and making consult a direct dependency of the feature will likely make that easier. 


> Should I add another recipe for empv-embark or let the recipe stay as is so that when user installs empv, empv-embark will be fetched too, and user can simply do (require 'empv-embark) if they want to activate it. 

IMO optional integrations with external packages belong in their own recipes.
To use your example, the user can only `(require 'empv-embark)` if they already have embark installed. Even then, the package manager byte-compilation issue I mentioned above will prevent the package from being byte-compiled correctly.

I'm not sure what MELPA's policy is, but personally I like to avoid foisting a bundle of packages on users who only want one.

**Comment by isamert** [comment]
> You'll want to add embark as a dependency of empv-embark.el.

Yes, I somehow forgot that, will fix it!

> To use your example, the user can only (require 'empv-embark) if they already have embark installed. Even then, the package manager byte-compilation issue I mentioned above will prevent the package from being byte-compiled correctly.

This makes sense. Although I don't mind an extra file on my system, it is not a good behavior if user is required to install a dependency on their own.

>  I took a brief look at the consult integration and it looks like you are relying on many internal (denoted by the -- in the symbol name) details of consult:

Yes, that is on purpose. I am aware that these functions belong to the internal API of the `consult` package but rewriting this integration without making use of these internal functions means that I will need to re-implement `consult--read` and all the other supplementary functionality in my package which I do not want. This integration brings a very simple quality of life improvement over what `empv` already provides if `consult` is not installed and I don't really want to get into the hassle of implementing an async completing-read (which seems to be quite problematic due to the nature of Emacs) for such a small feature. I can add a note to the README about this functionality being fragile due to the usage of internal functions.

Thanks for the review!

**Comment by minad** [comment]
@isamert Embark integration should ideally not provided by its own package but by a `with-eval-after-load` block, which just registers the keymap. I just had a similar discussion with @riscy in #8350. You can take a look there for reference. Another simple example for Embark integration is Prot's TMR package. See 

* https://github.com/protesilaos/tmr/blob/c71f0e2f3ad81e2b3c99aa0874777fdb82704a8b/tmr.el#L474-L483

* https://github.com/protesilaos/tmr/blob/c71f0e2f3ad81e2b3c99aa0874777fdb82704a8b/tmr.el#L512-L519

**Comment by isamert** [comment]
Moved embark integration back to empv.el, based on @minad's suggestion. Can you guys take a look at it again?

I will fix other mentioned problems (like hard-coded `sleep` and `consult` integration) in a more disciplined manner but I think these are out of scope for this issue. I can iterate on newer versions.

**Comment by riscy** [comment]
Looks good here -- thanks for your efforts around this package.  Since this has been a while I'll merge, but please do try to get to all of the checkdocs mentioned (just because this is something we ask of all authors).

And, welcome to MELPA! :)

**Comment by isamert** [comment]
Well, great! Thanks everyone for helping out! Hopefully I will also bring my other packages too.

**Pull request merged**
