### PR TITLE
Add claude-shell recipe

### PR DESCRIPTION
**Pull request by arminfriedl**
### Brief summary of what the package does

Anthropic's [Claude](https://claude.ai/) integration in Emacs based on [shell-maker](https://github.com/xenodium/chatgpt-shell/). Essentially a REPL to interact with Claude 3 models via it's REST API in a comint buffer.

### Direct link to the package repository

https://github.com/arminfriedl/claude-shell

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by arminfriedl** [comment]
In case you wonder about the split off of `claude-shell-fontifier.el` - this is because most of these functions are slightly adapted copy-pasta from `chatgpt-shell`. They are meant to be integrated into `shell-maker`, which this package is based on (see e.g. TODO in [1]). However, until this is done I have to duplicate them and to make it easier to remove later I organized them in their own helper file.

[1] https://github.com/xenodium/chatgpt-shell/blob/bf2d12ed2ed60c498d95215fa1cf81c2b23191a7/chatgpt-shell.el#L920

**Comment by riscy** [comment]
Thank you for this, and thanks for the explanation up there.  Here's a quick first pass --

`claude-shell-fontifier.el` with byte-compile using Emacs 29.2:
```
claude-shell-fontifier.el:282:19: Warning: the function `shell-maker-buffer' is not known to be defined.
claude-shell-fontifier.el:254:10: Warning: the function `map-elt' is not known to be defined.
claude-shell-fontifier.el:28:10: Warning: the function `shell-maker-narrow-to-prompt' is not known to be defined.
```

`claude-shell-fontifier.el` with checkdoc 0.6.2 (fix *within reason*):
```
claude-shell-fontifier.el:0: The first line should be of the form: ";;; package --- Summary"
claude-shell-fontifier.el:0: You should have a section marked ";;; Commentary:"
claude-shell-fontifier.el:1: You should have a section marked ";;; Code:"
```

`claude-shell.el` with byte-compile using Emacs 29.2:
```
claude-shell.el:187:18: Warning: reference to free variable `url-http-end-of-headers'
In claude-shell:
claude-shell.el:326:15: Warning: reference to free variable `claude-shell-mode-map'
```

Package and license:
- MIT License (via API)
- claude-shell-fontifier.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- "Start an FastGPT shell." -> "a FastGPT shell"

**Comment by arminfriedl** [comment]
Thank you!

I think all the remarks should be addressed now. If you could re-check would be great.

**Comment by riscy** [comment]
Thank you! Looks good.

Last minute typos after a quick flyspell -
- `Antrophic` -> `Anthropic`
- `dedictated` -> `dedicated
- `succint` -> `succinct` (this one might be especially worth fixing, since it appears in a prompt)

**Comment by arminfriedl** [comment]
Thank you for these last minute suggestions!

Fixed the typos now and indeed the typo in the prompt was especially bad :grimacing: I'm glad you spotted that!

**Pull request merged**
