### PR TITLE
org-tree-slide-pauses recipe

### PR DESCRIPTION
**Pull request by cnngimenez**
### Brief summary of what the package does

Provide `\pause` Beamer-like commands to org-tree-slide. When the presentation starts, it shadows the text between pauses and show it one by one with the typical C-> (M-x `org-tree-slide-move-next-tree`) for easy explanation. 
Org-mode list are also supported automatically!

### Direct link to the package repository

https://github.com/cnngimenez/org-tree-slide-pauses

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks - quick first pass.

byte-compile (using Emacs 27.1):
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
org-tree-slide-pauses.el:357:1:Warning: the following functions are not known
    to be defined: some, search, subseq, map
```
I think these are just some missing `require`s, but be aware you want to `(require 'cl-lib)` and use `cl-search`, `cl-sum`, etc. since `search`, `sum` are deprecated.

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- org-tree-slide-pauses.el#L346: No `format` required; messages are already f-strings
- org-tree-slide-pauses.el#L306: Optionally use `unless ...` instead of `when (not ...)`
- org-tree-slide-pauses.el#L23: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by cnngimenez** [comment]
Thanks!
I have just updated the code with all the warnings and lints fixed (commit: cnngimenez/org-tree-slide-pauses@d23733b6ad77fa764c369b8b82628a8eb7567237)

❓  Question: **What tool or function did you use for the "Other possible lints" section?**
I cannot find it! I tried [elisp-lint](https://github.com/gonewest818/elisp-lint/) package and `elint-file` but they don't report that. It is really useful!

**Comment by riscy** [comment]
I'll take a look soon!  The other possible lints are from [some scripts I run](https://github.com/riscy/melpazoid).  I get that question frequently so I'll start making it explicit. :)

**Comment by riscy** [comment]
Thanks!  Just one remains -- this should be a `cl-map` instead of `map`.
byte-compile (using Emacs 27.1):
```
org-tree-slide-pauses.el:359:1:Warning: the function `map' is not known to be
    defined.
```
I would also revise the summary line in a couple small ways -- typically there should be no punctuation at the end (although I'll note `package-lint` isn't able to detect exclamation marks).  You'll also want to be on the lookout to check whether the backslash interferes with any utilities (not that I've seen so far).  Altogether I'd suggest "Bring the \pause command from Beamer to org-tree-slide".

Minor docstring typos:
- Maunal -> Manua
- visibles -> visiblel
- hidding -> hiding

**Comment by cnngimenez** [comment]
Thanks again!

I learn two things: 
1. the cl package is deprecated (thus `map` is deprecated too).
2. melpazoid.el should be executed in terminal (with `emacs -Q --batch`)  and not with `M-x`. That way, all warnings appears.

This new commit fixes the typos (😳    sorry!), the summary and the cl-map (requires cl-extra and 24.5): cnngimenez/org-tree-slide-pauses@f02af7102e9ecef7c3dac0d376d85bbb8c4de4cc 

If you find any other problems, I'll be glad to fix them 👍🏽

**Comment by riscy** [comment]
> melpazoid.el should be executed in terminal (with emacs -Q --batch) and not with M-x. That way, all warnings appears.

Yeah, I should do something about that.  I think flycheck has it figured out, where it runs the emacs linter in a separate (clean) Emacs process so that all the warnings appear.  If you haven't tried out flycheck with Emacs lisp code, check it out!

On that note, welcome to MELPA. :)

**Pull request merged**
