### PR TITLE
Added recipe for treeview

### PR DESCRIPTION
**Pull request by tilmanrassy**
### Brief summary of what the package does

Abstract framework for tree navigation.  Based on this framework, specific libraries for particular hierarchical data can be implemented, for example, file systems. It's a prerequisite for dir-treeview, another package I created a pull request for.

### Direct link to the package repository

https://github.com/tilmanrassy/emacs-treeview

### Your association with the package

Maintainer, contributor (and an enthusiastic user :-) )

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
All good on the checklist, thanks!

Code looks good, but what's the purpose of the sequence of `intern`s at the top of the file?  I am thinking they ultimately have no effect.

- Around lines 40,817,894, you don't need a `progn` around the body of a `while`
- treeview.el#L301: It's safer to sharp-quote function names; use `#'`
- treeview.el#L22: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by tilmanrassy** [comment]
@riscy Thank you for the quick feedback!

I fixed the issues you mentioned. I also removed the `inern`s. They were indeed superfluous (I misunderstood of the `intern` function).

**Comment by alphapapa** [comment]
@tilmanrassy Have you considered using structs, generic functions, or EIEIO instead of the many buffer-local variables pointing to instance functions?

**Comment by tilmanrassy** [comment]
@alphapapa I used buffer local variables pointing to functions because it's simple and implementable in basic Emacs Lisp without any extra packages. But I see your point. Buffer local variables are a peculiarity of Emacs Lisp, not present in pure Lisp, and strongly related to buffers. Using them to create an interface, which is a rather general concept, might be a bit odd. Despite this, a believe my approach is not that bad. And the technique is used a lot in Emacs, I think.

But you're right, it might be worth to think about a better solution.

**Comment by riscy** [comment]
@alphapapa has good feedback -- it's worth exploring alternative representations because it can dramatically shrink code/improve maintainability.  That said, I tend toward Emacs Lisp primitives too (is this some form of [primitive obsession](http://wiki.c2.com/?PrimitiveObsession) we suffer from, maybe?).

Now that I'm looking more closely, for some of the defvars you can prefer `defvar-local` instead of e.g.:
```
(defvar treeview-suggest-point-pos-in-control-function 'treeview-get-overlay-center ...
(make-variable-buffer-local 'treeview-suggest-point-pos-in-control-function)
```
And for `treeview-return-nil` you could use the function `#'ignore`, but maybe there is a reason you want it named that way.

I don't think any of these are blockers, though.  Welcome to MELPA!

**Comment by tilmanrassy** [comment]
Thank you very much! :-)

**Pull request merged**
