### PR TITLE
add v2ex-mode

### PR DESCRIPTION
**Pull request by aborn**
v2ex-mode for visiting v2ex.com.

### CODE REVIEW

**Comment by xuchunyang** [comment]
Repo link: https://github.com/aborn/v2ex-mode

**Comment by xuchunyang** [comment]
Sent your a small fix. Pending https://github.com/aborn/v2ex-mode/pull/5

**Comment by aborn** [comment]
Thanks @xuchunyang ! Merged!

**Comment by purcell** [comment]
Thanks. Quick feedback:
- Please use `v2ex--` for private functions instead of `v2ex/`, as per the [elisp conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html).
- You can remove `in emacs` from the package description: it's redundant.
- Consider using `special-mode` as the parent mode. It will give you the `q` functionality for free, and it is a good convention to follow.

**Comment by purcell** [comment]
Also, you should use `defcustom` to declare the `v2ex` custom group and specify its position in the standard customisation hierarchy.

**Comment by aborn** [comment]
v2ex-mode.el code updated! Thanks @purcell advice.

**Comment by purcell** [comment]
Thanks. I think you can/should remove the `v2ex-quit` command and binding now too.

**Comment by aborn** [comment]
Yeah, I have removed the v2ex-quit command in latest code. Thanks again!

**Pull request merged**
