### PR TITLE
Add insert-char-preview package

### PR DESCRIPTION
**Pull request by matsievskiysv**
### Brief summary of what the package does

Insert Unicode character via `insert-char-preview` similar to `insert-char`, but with character preview.
In combination with packages like [counsel](https://github.com/abo-abo/swiper) it allows quick searching through possible characters. 

For example, search for `left bracket`:

screenshot

**Packages with similar functionality**:

  - [list-unicode-display](https://github.com/purcell/list-unicode-display)
  Lists Unicode characters based on the regexp in new buffer.
  Not as fast as inserting via minibuffer (like in this package).

<s>**[ht](https://github.com/Wilfred/ht.el) dependency**:</s>

<s>The same functionality may be achieved using builtin hash tables but `ht` implementation is significantly faster.</s>

### Direct link to the package repository

https://gitlab.com/matsievskiysv/insert-char-preview

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

*None needed*

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by manuel-uberti** [comment]
Out of curiosity, can you show some benchmark showing the differences between `ht` and the built-in `hash-table`?

**Comment by matsievskiysv** [comment]
> Out of curiosity, can you show some benchmark showing the differences between ht and the built-in hash-table?

Looks like I was wrong about performance:
```elisp
(package-initialize)
(require 'ht)

(defmacro measure-time (&rest body)
  "Measure the time it takes to evaluate BODY."
  `(let ((time (current-time)))
     ,@body
     (float-time (time-since time))))

(setq gc-cons-threshold 200000000)

(defun mean (arg)
  (/ (apply '+ arg) (safe-length arg)))

(defun rms (arg)
  (sqrt (/ (apply #'+ (mapcar (lambda (x) (* x x)) arg))
           (safe-length arg))))

(defvar itnum 20 "Number of iterations")

;; ht
(let ((acc))
  (dotimes (n itnum)
    (setq acc
	  (cons (measure-time
		 (let ((h (ht-create)))
		   (maphash (lambda (k v)
			      (ht-set h (format "%x-%s-%s"
						v (string v) k)
				      v))
			    (ucs-names))))
		acc)))
  (message "Mean %6f; RMS %6f // ht"
           (mean acc) (rms acc)))

(garbage-collect)

;; hash-table w preallocation
(let ((acc))
  (dotimes (n itnum)
    (setq acc
	  (cons (measure-time
                 (let ((h (make-hash-table :size (hash-table-size (ucs-names)) :test 'equal)))
                   (maphash (lambda (k v)
                              (puthash (format "%x-%s-%s"
                                               v (string v) k)
                                       v h))
                            (ucs-names))
                   h))
		acc)))
  (message "Mean %6f; RMS %6f // hash-table w preallocation"
           (mean acc) (rms acc)))

(garbage-collect)

;; hash-table w/o preallocation
(let ((acc))
  (dotimes (n itnum)
    (setq acc
	  (cons (measure-time
                 (let ((h (make-hash-table :test 'equal)))
                   (maphash (lambda (k v)
                              (puthash (format "%x-%s-%s"
                                               v (string v) k)
                                       v h))
                            (ucs-names))
                   h))
		acc)))
  (message "Mean %6f; RMS %6f // hash-table w/o preallocation"
           (mean acc) (rms acc)))

(garbage-collect)
```

Output:
```
Mean 0.050735; RMS 0.058521 // ht
Mean 0.035097; RMS 0.035098 // hash-table w preallocation
Mean 0.039142; RMS 0.040294 // hash-table w/o preallocation
```

**Comment by matsievskiysv** [comment]
Switched to `hash-table`

**Comment by manuel-uberti** [comment]
Thank you. Sorry if my request came out as rude, but I saw from your code you were using code from `ht` that is mostly wrapping built-in functionalities, so I couldn't see the performance improvement.

**Comment by matsievskiysv** [comment]
> Regarding the new code: I don't know if you will get an improvement out of this, but you could let-bind `(ucs-names)` instead of calling it twice. Probably something minor to avoid repetition, I don't know.

Yep, added this

**Comment by manuel-uberti** [comment]
Great! Another thing you may want to look into is [`lazy-completion-table`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Completion.html). Maybe worth it for a performance boost.

**Comment by matsievskiysv** [comment]
> Great! Another thing you may want to look into is [`lazy-completion-table`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Completion.html). Maybe worth it for a performance boost.

These look like a low level functions that may be used by a completion system. I think that counsel and other completion backends use these internally.

**Comment by alphapapa** [comment]
FYI, for benchmarking, I recommend using the `bench-multi-lexical` macro, which ensures that the code is tested with lexical binding and after byte-compiling: https://github.com/alphapapa/emacs-package-dev-handbook#bench-multi-lexical

**Comment by matsievskiysv** [comment]
> https://github.com/alphapapa/emacs-package-dev-handbook

Did not know about this, thanks!

**Comment by a13** [comment]
Doesn't `counsel-unicode-char` have the same functionality?

**Comment by matsievskiysv** [comment]
> Doesn't `counsel-unicode-char` have the same functionality?

Oh, cool! Didn't know about this function. Don't need this one then.

**Comment by manuel-uberti** [comment]
I thought this one was based on `completing-read` and thus a more general approach for non-counsel users.

**Comment by matsievskiysv** [comment]
> I thought this one was based on `completing-read` and thus a more general approach for non-counsel users.

I use counsel so I'm happy with `counsel-unicode-char`. If you think that this package might be useful to somebody, I'll reopen this PR.

**Comment by manuel-uberti** [comment]
I guess whoever doesn't use `counsel-unicode-char` or `helm-ucs` could find your package useful. :)

**Comment by riscy** [comment]
I think since this exists in a couple of popular completion frameworks (although not all of them -- so I think MELPA could be persuaded if there are strong feelings), and the author @matsievskiysv is happy with the counsel version, it may be a good idea to hold off.  My possibly unwarranted worry is that the package won't be regularly used, even by its author...?

But like @manuel-uberti points out, other completion libraries (ido, icicles, others) could probably benefit from this.

**Comment by manuel-uberti** [comment]
Totally up to MELPA and @matsievskiysv at this point. I thought this package could be useful the users of built-in completion libraries such as `icomplete-mode` or packages like `selectrum`.

**Comment by matsievskiysv** [comment]
I think, it's up to you, guys.

> My possibly unwarranted worry is that the package won't be regularly used, even by its author...?

I think, I will use it. I like this package's formatting a bit better then of `counsel-unicode-char`.

**Comment by riscy** [comment]
Okay, I think that's fine in this case.  The one last thing to do is add a `LICENSE` file to the repository (GitLab for example is recognizing the repo as having "no license").

**Comment by matsievskiysv** [comment]
Done

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
