### PR TITLE
Add freeradius-mode for editing FreeRadius configuration files and un…

### PR DESCRIPTION
**Pull request by VersBinarii**
…lang policy files

### Brief summary of what the package does

Helper mode for FreeRadius server config files and unlang policies.

### Direct link to the package repository

https://github.com/VersBinarii/freeradius-mode

### Your association with the package

I am maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [ ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by VersBinarii** [comment]
Hello and thanks for the feedback. 
Yes, you are correctly identified the config files to check :)
I believe i addressed everything you listed above. I plan to add couple of more features to the package as i pick up more elisp skills ;)

I would like to improve the regex matching and find a way to enable the mode automaticaly for the config files. The problem with this is that the files have no extension to run a regex on.
So i though about 2 approaches:
1. match on the directory, since by convention all config files must reside in raddb directory, and enable the mode for all files within it.
2. force user to activate the mode manually for the file initially and store the name of the file and trigger the mode the next time the file is opened.

Would you be able to advice if either of those approaches is "idiomatic" for emacs?

**Comment by riscy** [comment]
Matching on the directory is probably your best bet here - I would maybe follow `nginx-mode` which does this as `("/nginx/.+\\.conf\\'" . nginx-mode)`.

**Comment by VersBinarii** [comment]
Great. I'll check it out then.

**Comment by purcell** [comment]
Ping! :-)

**Comment by VersBinarii** [comment]
Yes, yes :) 
Thank you for all the feedback. I was just busy with some other stuff last few weeks.
I hope to sort it all out next week.

**Comment by VersBinarii** [comment]
Hello @purcell,
 I believe i addressed most of the items from your feedback. Not sure about my indentation settings, i will need to investigate it a bit more. I will also try to improve the regexes a bit more over next few days.

**Comment by purcell** [comment]
Cool, thanks!

**Pull request merged**
