### PR TITLE
Add jiggle to MELPA recipes

### PR DESCRIPTION
**Pull request by emres**
This package provides the jiggle mode, so that when switching to a buffer the cursor is jiggled, drawing the attention of user where it is. We discern motion more easily than color or shape, so jiggling the cursor on a large frame lets it be seen instantly without searching.

https://github.com/emres/jiggle

I am the maintainer.
### Checklist
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- `Version` header is incorrect format. It should be like `1.0`, `1.2.3` etc
- URL header does not refers to your repository, is it no problem ?
- There are too many byte-compile warnings, please check.

**Comment by emres** [comment]
Hello @syohex, 

I've addressed your concerns in emres/jiggle@8c70afcb0f68fcd4fe08ef7fea6ce9c1f110f5f6. 

Can you check again please?

**Comment by purcell** [comment]
Thanks! This looks useful.

Given `jiggle-setup-hook` and `jiggle-load-hook` together with `jiggle-disabled`, the configuration of this looks a little convoluted and unidiomatic. The fact that you're `eval`-ing modified advice when toggling the mode is a big indicator that there is almost certainly a better approach. Can you instead inspect `this-command` or `last-command` in order to decide whether or not to jiggle after a cursor move? I'd expect the implementation to look more like a simple `after-command-hook` function with a list of "don't jiggle" commands.

**Comment by tarsius** [comment]
@emres How are things progressing?

**Comment by emres** [comment]
Hello @tarsius, unfortunately I had to put things on hold for a while, basically because I didn't have time to address the concerns raised by @purcell. "Didn't have time" mostly meaning: this is a very old code-base and I'm not the original author and my Emacs Lisp knowledge is not at the level to quickly implement the changes requested (help, contributions, etc. in the form of pull request to https://github.com/emres/jiggle is of course welcome :-).

**Comment by tarsius** [comment]
Okay then, let's leave this open until you or someone else finds the time to look into this.

**Comment by tarsius** [comment]
I'm closing this now anyway. But please feel free to reopen this when you have the time to finish the required work. Thanks!

**Pull request closed without merging**
