### PR TITLE
Package third-time

### PR DESCRIPTION
**Pull request by swflint**
### Brief summary of what the package does

This package implements Third Time style time management for Emacs.

### Direct link to the package repository

https://git.sr.ht/~swflint/third-time

### Your association with the package

Maintainer.

I know I have a number of packages under review.  Please take your time.

### Relevant communications with the upstream package maintainer

N/A

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this - you have a few other open PRs open so I'll focus on those first (not a big deal, but please see [CONTRIBUTING.org's](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#waiting-for-reviews-and-taking-feedback-into-account) re: you can help them by limiting the number of pull requests you have open at once").

**Comment by riscy** [comment]
Thanks again for your patience.  A couple quick notes --

`third-time.el` with package-lint 20230905.629:
```
1 issue found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
```
Maybe use the blog post's title "Third Time: a better way to work" or "Third Time: a work/break time tracker"

Also your recipe could just be `(third-time :repo "swflint/third-time" :fetcher sourcehut)` which is equivalent, unless I'm missing something.

Otherwise this implementation looks solid to me.

**Comment by swflint** [comment]
> Thanks again for your patience. A couple quick notes --
> 
> `third-time.el` with package-lint 20230905.629:
> 
> ```
> 1 issue found:
> 1:0: warning: Including "Emacs" in the package summary is usually redundant.
> ```
> 
> Maybe use the blog post's title "Third Time: a better way to work" or "Third Time: a work/break time tracker"

That's a good idea.  Thanks.

> Also your recipe could just be `(third-time :repo "swflint/third-time" :fetcher sourcehut)` which is equivalent, unless I'm missing something.

It would be, wouldn't it?  Since I submitted a bunch off of one repo, I think I just included the `:files` out of habit.

> Otherwise this implementation looks solid to me.

I've gone ahead and updated the two issues.  Thanks!

**Comment by riscy** [comment]
All set - thanks!

**Comment by terlar** [comment]
Would be nice to have a comparison to https://github.com/SqrtMinusOne/pomm.el
I just tried to find this as I remember it being merged and then stumbled upon this other MELPA package.

**Pull request merged**
