### PR TITLE
added taskpaper-mode

### PR DESCRIPTION
**Pull request by avelino**
ref: https://github.com/saf-dmitry/taskpaper-mode/issues/1

### Brief summary of what the package does
Emacs major mode for editing TaskPaper format

### Direct link to the package repository

https://github.com/saf-dmitry/taskpaper-mode

### Your association with the package

I'm user
authors is @saf-dmitry

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by saf-dmitry** [comment]
> Brief summary of what the package does
>
> Emacs major mode for editing papertask format

Please correct the summary:

Emacs major mode for editing TaskPaper format

**Comment by tarsius** [comment]
... and remove "Emacs". That's redundant for an Emacs package. (It makes sense to use that in the README, but not in the library header.)

**Comment by purcell** [comment]
> ... and remove "Emacs"

`package-lint` explicitly provides this feedback, if you run it as requested.

**Comment by tarsius** [comment]
The summary has been changed.

**Pull request merged**
