### PR TITLE
Add recipe for occurx-mode

### PR DESCRIPTION
**Pull request by k32**
### Brief summary of what the package does

An Emacs plugin for filtering large log files.

Improvements over the built-in `occur`:
- Patterns are specified using rx notation in a regular buffer rather than  the minibuffer.
- Patterns can be easily saved and restored.
- It is possible to specify multiple patterns, and `occurx` will highlight them with different colors.
- Searches are not limited to a single line; it is possible to use a custom delimiter.
- It is possible to match multiple regular expressions for each entry and to negate regular expressions.

### Direct link to the package repository

https://github.com/k32/occurx-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by k32** [comment]
Byte compilation reports a few warnings about free variable assignment, but they are local variables defined when one of the minor modes is enabled. I am not sure if it makes sense to create them via `defvar-local`, since it'll add them to all buffers (?) even when they are not relevant.

There are a few warnings about unused lexical variables as well, but they will be used in the future versions, so I'd like to keep them as reminders to myself. If that's not acceptable, then I will comment them out.

**Comment by riscy** [comment]
Thanks for this, those features look solid.  Quick first pass --

`occurx-mode.el` with byte-compile using Emacs 28.1:
```
occurx-mode.el:221:24: Warning: Unused lexical variable `offset'
In occurx-run:
occurx-mode.el:300:18: Warning: reference to free variable
    `occurx-dependent-buffers'
```
The first one (line 221) happens because the variable `offset` is set in a couple of places, but I don't believe it's ever used in the code other than by being set (I ran a macroexpand just to be sure, because pcase often flummoxes me).  The second one (line 300) happens because `defvar-local` is declared *after* the `occurx-run` function.  Moving this `defvar-local` to the top of the file fixes that.

`occurx-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- occurx-mode.el#L105: Lighter should start with a space
- occurx-mode.el#L319: Top-level `setq` should usually be replaced by `defvar`
- occurx-mode.el#L414: Top-level `setq` should usually be replaced by `defvar`
- occurx-mode.el#L321: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- occurx-mode.el#L415: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
```
I think the last two hints there should solve the use of `setq`.

**Comment by k32** [comment]
Thanks for the quick review. I got a clean melpazoid run here: https://github.com/k32/occurx-mode/pull/2

Here's what changed:
- This compile warning wasn't spurious indeed. I thought that `setq` counts as "usage" of a lexical variable, but the check was smarter. It was a leftover from old version of code that worked differently. Now it's removed.
- I changed license from AGPL to GPL v3. The source code was under GPL already, and remote execution clause doesn't make sense in this context, so I fixed that to avoid confusion.
- Other minor fixes, such as adding spaces to lighters, reordering definitions to avoid free variable warnings, etc.

**Comment by riscy** [comment]
Right on, thank you!  And welcome to MELPA.

**Pull request merged**
