### PR TITLE
Add recipe for emacs-everywhere

### PR DESCRIPTION
**Pull request by tecosaur**
### Brief summary of what the package does

A re-implementation of the ideas in [zachcurry/emacs-anywhere](https://github.com/zachcurry/emacs-anywhere).

System-wide popup Emacs windows for quick edits.

### Direct link to the package repository

https://github.com/tecosaur/emacs-everywhere

### Your association with the package

Author.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This look very cool.  Quick first pass below --

byte-compile (using Emacs 27.1):
```
emacs-everywhere.el:270:28:Warning: reference to free variable
    `emacs-everywhere--dir'
In end of data:
emacs-everywhere.el:404:1:Warning: the following functions are not known to be
    defined: org-in-src-block-p, org-ctrl-c-ctrl-c, evil-insert-state,
    spell-fu-buffer, markdown-mode, org-export-to-buffer
```
For the first I think you just need to make sure the defvar comes first.  Many of the "not known to be defined" warnings are due to sharp-quoting these functions.  So you could either remove the sharp-quotes and the compiler won't try to match them up with existing functions, or you could use `declare-function` and arrive at a clean byte-compile.

A very minor checkdoc (using version 0.6.2):
```
Warning (emacs): 
emacs-everywhere.el:290: Argument `force' should appear (as FORCE) in the doc string
```

And although I currently see no issue with it currently, I suggest you use `shell-quote-argument` when you call `shell-command`, for example on line 323.  No shell I know of will trip over an argument like "app-name", but if (somehow) one of the scripts ended up being called "app|name" (I know, contrived) then the command will fail.  I only mention this because whenever I see `shell-command` I always look for matching `shell-quote-argument` usage.

**Comment by tecosaur** [comment]
How come you come up with niggles that melpazoid doesn't? :stuck_out_tongue: https://github.com/tecosaur/emacs-everywhere/runs/1852082109.

Anyway, I think I've resolved everything you've raised - with the sole exception of using `shell-quote-argument`. Given that the value passed is internal (i.e. cannot be user-set), simple, and with obvious usage, the "chance" that one of the shell scripts names contains anything other than `[A-z0-9-_]` is about zero IMO.

**Comment by riscy** [comment]
I think they are there under the `Run` fold, but (for now) melpazoid doesn't fail unless it sees red errors.

shell-command stuff sounds good.

Since this is still fresh in my mind, I had another quick look and I have a small concern about the `emacs-everywhere-init-hooks` defcustom and the way you progressively fill that variable in as the package is loaded.  By declaring it as customizable, you're telling users they can specify it (i.e. via the customize- interface), but as soon as they load your package, whatever they specified gets added to.  Maybe I should put it as a question: do you really want user customizing this, or believing that they can remove the builtin hooks?  If not, you could just make it a defconst and putting all of the hooks in at once (but you might have to do so after your functions are declared so the compiler knows what's happening).

Beyond that I don't see any blockers.

**Comment by tecosaur** [comment]
> `emacs-everywhere-init-hooks` ... do you really want user customizing this, or believing that they can remove the builtin hooks?

Oh, this is *exactly* how I indeed `emacs-everywhere-init-hooks` to work. Everything hooked onto it are "optional extras", what's hooked on by default are just a guess of what most users will like.

**Comment by riscy** [comment]
The problem then is if they remove the optional extras in their configuration, and then they load the package, those optional extras will be added back in, won't they?

**Comment by tecosaur** [comment]
? They just need to be removed after load then. I don't see the issue.

**Comment by tecosaur** [comment]
Scratch that, I see the potential issue. I've moved the default hooks into the `defcustom` with my latest commit.

**Comment by tecosaur** [comment]
Hi @riscy, if you could take another peek that would be great 🙂

**Comment by riscy** [comment]
package-lint (using version 20210214.2252):
```
2 issues found:
1:0: warning: The word "emacs" is redundant in Emacs package names.
12:52: warning: An explicit dependency on cl-lib <= 1.0 is not needed on Emacs >= 24.3.
```
The first is fine as discussed; the second isn't a blocker but fyi.  

And, thanks for this. :)

**Pull request merged**
