### PR TITLE
Add realgud-xdebug recipe

### PR DESCRIPTION
**Pull request by Sasanidas**
### Brief summary of what the package does

Add a [realgud](https://github.com/realgud/realgud) front-end for the PHP debugger [xdebug](https://xdebug.org/).

### Direct link to the package repository

https://github.com/realgud/realgud-xdebug

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  There may be some false positives in the following due to the use of `provide-this` (mostly to do with the file footers), but I have not been careful to exclude them below.  In the past I've been told that some of the realgud packages are not being actively modified and we've grandfathered in some of the issues as a result -- let me know if that's the case here.

I also know the author(s) have signed copyrights to the FSF, so we see quite a few realgud packages over on ELPA.  This one isn't there, but that repository might be the preferred place to index this package (ideally packages don't get hosted on both).

### core.el ###

byte-compile (using Emacs 27.1):
```
core.el:50:1:Warning: Unused lexical argument `opt-debugger'
core.el:53:1:Warning: Unused lexical argument `orig-args'
In xdebug-parse-cmd-args:
core.el:55:9:Warning: reference to free variable `realgud:xdebug-command-name'
In xdebug-suggest-invocation:
core.el:64:31:Warning: reference to free variable
    `realgud:xdebug-command-name'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
core.el:82: The footer should be: (provide 'core)\n;;; core.el ends here
Warning (emacs): 
core.el:51: First sentence should end with punctuation
Warning (emacs): 
core.el:51: First line should be capitalized
Warning (emacs): 
core.el:51: Argument `opt-debugger' should appear (as OPT-DEBUGGER) in the doc string
Warning (emacs): 
core.el:54: First sentence should end with punctuation
Warning (emacs): 
core.el:54: Argument `orig-args' should appear (as ORIG-ARGS) in the doc string
```

package-lint (using version 20210111.341):
```
8 issues found:
1:0: error: There is no `provide' form.
37:0: error: "realgud--xdebug-minibuffer-history" doesn't start with package's prefix "realgud-xdebug".
40:0: error: "realgud--xdebug-remote-minibuffer-history" doesn't start with package's prefix "realgud-xdebug".
50:0: error: "xdebug-query-cmdline" doesn't start with package's prefix "realgud-xdebug".
53:0: error: "xdebug-parse-cmd-args" doesn't start with package's prefix "realgud-xdebug".
59:0: error: "xdebug-suggest-invocation" doesn't start with package's prefix "realgud-xdebug".
66:0: error: "xdebug-reset" doesn't start with package's prefix "realgud-xdebug".
77:0: error: "realgud--xdebug-customize" doesn't start with package's prefix "realgud-xdebug".
```
(I think the `realgud--xdebug-` prefix should be `realgud-xdebug--` in these cases, although I also notice there is a `realgud:xdebug-` prefix as well.)

### init.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
init.el:179: The footer should be: (provide 'init)\n;;; init.el ends here
Warning (emacs): 
init.el:130: White space found at end of line
```

package-lint (using version 20210111.341):
```
6 issues found:
1:0: error: There is no `provide' form.
33:0: error: "realgud:xdebug-pat-hash" doesn't start with package's prefix "realgud-xdebug".
33:0: error: `realgud:xdebug-pat-hash' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
83:7: warning: Closing parens should not be wrapped onto new lines.
151:0: error: "realgud:xdebug-command-hash" doesn't start with package's prefix "realgud-xdebug".
151:0: error: `realgud:xdebug-command-hash' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
```

### realgud-xdebug.el ###

byte-compile (using Emacs 27.1):
```
realgud-xdebug.el:41:1:Error: Cannot open load file: No such file or directory, /workspace/pkg/xdebug/xdebug
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210111.341):
- No issues!

### track-mode.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
track-mode.el:65: The footer should be: (provide 'track-mode)\n;;; track-mode.el ends here
```

package-lint (using version 20210111.341):
```
5 issues found:
1:0: error: There is no `provide' form.
39:0: error: "realgud:xdebug-track-mode-hook" doesn't start with package's prefix "realgud-xdebug".
39:0: error: `realgud:xdebug-track-mode-hook' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
48:0: error: "realgud:xdebug-track-mode" doesn't start with package's prefix "realgud-xdebug".
48:0: error: `realgud:xdebug-track-mode' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
```

### xdebug.el ###

byte-compile (using Emacs 27.1):
```
xdebug.el:74:1:Warning: Unused lexical argument `no-reset'
xdebug.el:74:1:Warning: Unused lexical argument `opt-cmd-line'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
xdebug.el:102: The footer should be: (provide 'xdebug)\n;;; xdebug.el ends here
```

package-lint (using version 20210111.341):
```
8 issues found:
1:0: error: There is no `provide' form.
42:0: error: "realgud:xdebug-command-name" doesn't start with package's prefix "realgud-xdebug".
42:0: error: `realgud:xdebug-command-name' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
60:0: error: "realgud:xdebug-break-line" doesn't start with package's prefix "realgud-xdebug".
60:0: error: `realgud:xdebug-break-line' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
74:0: error: "realgud:xdebug" doesn't start with package's prefix "realgud-xdebug".
74:0: error: `realgud:xdebug' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
100:0: error: Aliases should start with the package's prefix "realgud-xdebug".
```

### Loadability ###

Verifying ability to #'load each file:
```
Loading core.el
Loading init.el
Loading realgud-xdebug.el
realgud-xdebug.el:Error: Emacs 27.1 errored during load
Loading track-mode.el
Loading xdebug.el
Done.
```
```
Loading /workspace/.emacs.d/elpa/realgud-20201221.1435/realgud/common/custom...
Loading /workspace/.emacs.d/elpa/realgud-20201221.1435/realgud/lang/java...
Eager macro-expansion failure: (file-missing "Cannot open load file" "No such file or directory" "/workspace/pkg/xdebug/xdebug")
Eager macro-expansion failure: (file-missing "Cannot open load file" "No such file or directory" "/workspace/pkg/xdebug/xdebug")
```
For the above load failures, it looks like some kind of assumption is being made about the default-directory when the package is loaded.

**Comment by Sasanidas** [comment]
> I also know the author(s) have signed copyrights to the FSF, so we see quite a few realgud packages over on ELPA. This one isn't there, but ELPA might be the preferred place to index this package (ideally packages don't get hosted on both).

Yes, I think most of the packages are in ELPA, but this one uses a dependency (the xdebug cli) that is not yet free software, so I don't think it is appropriate to put it there.

Thanks for checking the errors!, I will figure out how to solve most of them and ping again.

Regards

**Comment by riscy** [comment]
Thanks so much for being accommodating.  Feel free to ping me whenever. :)

**Comment by Sasanidas** [comment]
So, I lost the changes that I was doing locally... I'm not that motivated with this project and I want to contribute a couple of packages, so I'm going to close this for now.
I will make a new merge request in the future

**Pull request closed without merging**
