### PR TITLE
Added a package file for poet-client

### PR DESCRIPTION
**Pull request by wailo**
### Brief summary of what the package does

Emacs client for po.et. A decentralized protocol for content ownership, discovery and monetization in media.

### Direct link to the package repository

https://github.com/wailo/emacs-poet

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
Please tidy up your code to make it easier to review.  e.g. there are a lot of blank lines in strange places, code that isn't indented properly, etc.  You may find `aggressive-indent-mode` helpful.

**Comment by wailo** [comment]
Thanks for the tip. I have reformatted the whole code and removed blank lines

**Comment by alphapapa** [comment]
It's not generally correct to use `defvar` inside a function.  Is there something about the widget library that requires that?

**Comment by wailo** [comment]
Without defvar, I was getting (assignment to free variable) warnings. which indicateas that the variables are shared in the global space, while my intention is to keep the vars in a local scope.
According to the answer in this link: https://emacs.stackexchange.com/questions/24169/how-to-fix-warning-assignment-to-free-local-variable-in-lambda-function, using defvar solves the warning. and the doc in this link https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Variables.html states that defvar will bind the variable to local scope if declared without init value. This is why I used defvar. 

Looking at the code again, I decided to get rid of all defvars and replace them with a temporaries in a [let] statement. Changes have been pushed.

**Comment by purcell** [comment]
Looks good - thanks for your patience, merging now. Welcome to MELPA! :tada:

**Comment by wailo** [comment]
Thank you!

**Pull request merged**
