### PR TITLE
Hyperbole recipe update - Add hyrolo.py; remove TAGS; install images to man/im

### PR DESCRIPTION
**Pull request by rswgnu**
Basic update to the existing recipe.  I am the author.

### CODE REVIEW

**Comment by rswgnu** [comment]
Thanks much.

**Comment by tarsius** [comment]
I did not notice that this also removes the recipe for `ert-results`. I assume this was a mistake and have restored it.

**Comment by rswgnu** [comment]
It looked to me like the PR added that recipe which had looked strange but if it is there now, we are all good.  Thanks.

**Comment by tarsius** [comment]
You could avoid such mistakes by rebasing your feature branch on top of `master` (or better yet `origin/master`) instead of merging that into your feature branch. Merging the "mainline" **into** a feature branch is an anti-pattern. That is at least the case when the changes in the feature branch are completely unrelated to the changes on `master`. That is the case here; your recipe is unrelated to the recipes for unrelated packages.

Additionally you might in some cases want to squash your changes into a single commit before pushing (in particular when later commits merely fix/refine changes made in earlier commits).

**Comment by rswgnu** [comment]
Good thoughts.  Will work on doing so.  Thanks.

**Pull request merged**
