### PR TITLE
Add splunk-mode recipe

### PR DESCRIPTION
**Pull request by jakewilliami**
### Brief summary of what the package does

Adds a major mode for editing Splunk Search Processing Language (SPL) query source code.

### Direct link to the package repository

https://github.com/jakewilliami/splunk-mode

### Your association with the package

I am the author, maintainer, and likely sole user of this package

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses) (under MIT license, but happy to change if there's a preferred GPL-compatible free software license)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I realize it has a non-obvious name, but have you had a chance to check out https://melpa.org/#/paimon and compare to your own major-mode?

In the meantime, thanks for your close adherence to the checklist.  Here's a couple very minor sharp-quote hints:

- splunk-mode.el#L380: It's safer to sharp-quote function names; use `#'`
- splunk-mode.el#L276: It's safer to sharp-quote function names; use `#'`

**Comment by riscy** [comment]
Friendly ping on this one - have you had a chance to check out paimon?

**Comment by jakewilliami** [comment]
Hi @riscy, apologies for the delay in getting back to you!  I did see [Paimon](https://github.com/r0man/paimon.el/) when I was initially looking for a Splunk mode, before writing it myself.  It seems to me that Paimon is a comprehensive tool to interact with a Splunk server.  The library I wrote is a small one that simply offers syntax highlighting.

**Comment by riscy** [comment]
Thank you for letting me foist that verification onto you - it goes without saying you have more splunk context than I do.

Merging this now.  And welcome to MELPA. :)

**Pull request merged**
