### PR TITLE
Add recipe for ob-async

### PR DESCRIPTION
**Pull request by astahlman**
### Brief summary of what the package does

ob-async enables asynchronous execution of org-babel src blocks.

### Direct link to the package repository

https://github.com/astahlman/ob-async

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [ X ] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ X ] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ X ] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I suppose it is better to moving test files into some directory and use default value of `files` attribute in recipe(= not specifying `files` attribute). How about ?

**Comment by tarsius** [comment]
It appears the test files were already moved into a subdirectory before @syohex suggested that this should be done. @astahlman please update this pr, dropping the `:files` property. (Do so by amending the commit and force-pushing to the branch this pr is based on.)

**Comment by astahlman** [comment]
Thanks for the review, @tarsius. I've removed the `:files` property

**Comment by syohex** [comment]
Merged

**Pull request merged**
