### PR TITLE
Add posframe

### PR DESCRIPTION
**Pull request by tumashu**
### Brief summary of what the package does

Pop a  child-frame at point

### Direct link to the package repository

https://github.com/tumashu/posframe

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [-] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by tumashu** [comment]
@purcell  Is it merge the PR quicker, for two packages of mine are waiting it into melpa :-)

**Comment by purcell** [comment]
Looks good, but I don't really understand the comment about compatibility. If this requires Emacs 26, then why not make that a package dependency?

**Comment by tumashu** [comment]
use pyim as example,  pyim can work well with emacs24, if we let posframe require emacs26, pyim will not installable in emacs24,  is we do not let pyim hard depend posframe, i had let user manual install posframe

**Comment by purcell** [comment]
Following that logic, everyone would list optional dependencies as mandatory (for convenient installation), and every depended-upon package would do its compatibility checks at runtime. That would be terrible for the package ecosystem.

The answer here is surely to make `posframe` depend on the Emacs version it needs, and to *not* add a package dependency on `posframe` to `pyim`. You can still add code in `pyim` which allows it to support `posframe` if available/configured.

**Comment by tumashu** [comment]
Maybe you are right, fixed.

**Comment by purcell** [comment]
Super, thank you! Merged.

**Comment by purcell** [comment]
I appreciate your support! :tada:

**Pull request merged**
