### PR TITLE
add forex

### PR DESCRIPTION
**Pull request by md-arif-shaikh**
### Brief summary of what the package does

Minimal implementation of forex rate, currency conversion using google finance

### Direct link to the package repository

https://github.com/md-arif-shaikh/forex

### Your association with the package

Author. Maintainer.

### Relevant communications with the upstream package maintainer

None

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this - I notice you left two checklist items off, but as far as I can tell your byte-compile and package-lint are in great shape.

I have to seriously wonder, how reliable are the html classes in `forex--google-class-alist`?  Is the use of these documented anywhere?  (Is there an API?)  Otherwise I think this is potentially a very brittle package that will break as soon as that page's HTML gets rebuilt.

Small stuff I noticed on a quick glance:
- Minima -> Minimal
- Your Commentary could benefit from mentioning the main interactive entrypoints

**Comment by md-arif-shaikh** [comment]
@riscy thanks for the comments. I agree with the point of using standard API but as far as I understand there is no such API from google. In fact, I read such an API was there but has been continued since 2012 and also is not supposed to be used for public apps.

Also, I have now added more to the commentary section as suggested.

**Comment by riscy** [comment]
I think we should lean toward not merging this for a couple reasons:

- No such Google API exists, and therefore this package *needs* to rely on scraping elements whose names could easily change -- it is probably too brittle.  You'd also need to consider handling the possible situation in which Google starts showing captchas instead of forex results
- There is already a package for currency conversion -- https://melpa.org/#/currency-convert -- that makes use of a public API that is unlikely to break without (much) warning

I'll close this PR if the above sounds fair to you, but let me know what you think.

**Comment by md-arif-shaikh** [comment]
Sounds reasonable. The other package you mentioned, unfortunately, needs a subscription which I was trying to avoid.

**Pull request closed without merging**
