### PR TITLE
Add recipe for ppcompile.

### PR DESCRIPTION
**Pull request by whatacold**
### Ping-pong compile projects on remote machines

This package tries to ease the workflow that consists of coding locally,
compiling remotely, and fixing errors with `next-error' and `previous-error' locally.
It depends on built-in packages: auth-source,
project , files-x and compile.
And it also depends on external programs: rsync, ssh, and expect.

### Direct link to the package repository

https://github.com/whatacold/ppcompile

### Your association with the package

I'm the author and the maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for your patience!  We have this warning:

`ppcompile.el` with byte-compile using Emacs 28.1:
```
ppcompile.el:132:1: Warning: defvar `ppcompile--current-buffer' docstring
    wider than 80 characters
```
I'm investigating why this has become a warning worth reporting by the *byte-compiler* in Emacs 28, but I anticipate this would be easy to fix on your end (and then users won't see it during install).  Otherwise this should be a quick merge.

**Comment by whatacold** [comment]
Thanks, Chris.

Just fixed the docstring, I didn't notice this as I was still on 27 :(

**Comment by riscy** [comment]
No problem. :)  This is a pretty interesting package -- happy to merge.  A couple absolutely minor lints while I do:

- ppcompile.el#L191: There is no need to quote lambdas (neither #' nor ')
- ppcompile.el#L219: There is no need to quote lambdas (neither #' nor ')
- ppcompile.el#L225: There is no need to quote lambdas (neither #' nor ')

**Comment by riscy** [comment]
I may have hit merge a little quickly (which tells me it's time to take a break) but I'm noticing as I look around that there's no use of `shell-quote-argument` anywhere.  What if, for example, the user's ssh password contains special characters that could interfere with the shell?  E.g. if my password were `riscy|business` then `(setq process-environment (cons (format "PPCOMPILE_PASSWORD=%s" ...` seems like users may run into issues?

**Comment by whatacold** [comment]
Thanks!

As for the issues you mentioned, I will take a look and try to fix them, thanks!

**Pull request merged**
