### PR TITLE
New package: helm-fuz

### PR DESCRIPTION
**Pull request by cireu**
### Brief summary of what the package does

Helm's usage of fuz.

### Direct link to the package repository

https://github.com/cireu/fuz.el

### Your association with the package

author

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
helm-fuz.el:103: Some lines are over 80 columns wide
Warning (emacs): 
helm-fuz.el:168: First line is not a complete sentence
Warning (emacs): 
helm-fuz.el:187: First line is not a complete sentence
Warning (emacs): 
helm-fuz.el:187: Keycode M-x embedded in doc string.  Use \\<keymap> & \\[function] instead
Warning (emacs): 
helm-fuz.el:187: Argument `cands' should appear (as CANDS) in the doc string
Warning (emacs): 
helm-fuz.el:216: Some lines are over 80 columns wide
Warning (emacs): 
helm-fuz.el:216: Argument `pattern' should appear (as PATTERN) in the doc string
Warning (emacs): 
helm-fuz.el:230: Argument `orig-fun' should appear (as ORIG-FUN) in the doc string
Warning (emacs): 
helm-fuz.el:253: Argument `orig-fun' should appear (as ORIG-FUN) in the doc string
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
1 issue found:

8:39: error: Package fuz is not installable.
```
(Contingent on https://github.com/melpa/melpa/pull/6346)

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
No issues! 🎉

Miscellaneous and minor:
- helm-fuz.el#L160: Use `unless ...` instead of `when (not ...)`

**Comment by cireu** [comment]
Personally I can't understand `unless` form quickly, so I prefer `(when (not ...) ...)`

**Comment by cireu** [comment]
80 chars and spell issues: most fixed in https://github.com/cireu/fuz.el/commit/549d803375e72630c2367c13475de893185feb0f

> helm-fuz.el:187: Keycode M-x embedded in doc string.  Use \\<keymap> & \\[function] instead

Maybe just false positive because I write `helm-M-x` in docstring.

> Argument `orig-fun' should appear (as ORIG-FUN) in the doc string

They're just advices, is it necessary to write arguments in the first line of docstring for them? 

@riscy

**Comment by riscy** [comment]
> Maybe just false positive because I write helm-M-x in docstring.

Ah, thanks for checking and sorry for the oversight.

> They're just advices, is it necessary to write arguments in the first line of docstring for them?

It's helpful to the maintainers if the checklist is clean, even if it requires a bit of extra finetuning.  In this case you could write a docstring like `  "Around-advice where ORIG-FUN is `helm-ff-filter-candidate-one-by-one'."` or similar.

**Comment by cireu** [comment]
https://github.com/cireu/fuz.el/commit/261b88178211989add3cd4308ad7b89c4a2243ff

Done in this commit

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
