### PR TITLE
Add streamline recipe

### PR DESCRIPTION
**Pull request by matthias-margush**
### Brief summary of what the package does

Minimalist's Mode Line

### Direct link to the package repository

https://github.com/matthias-margush/streamline

### Your association with the package

I am the creator of the package

### Relevant communications with the upstream package maintainer

n/a

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! This is neat, and the code mostly looks good. Couple of notes:

- The keybinding stuff is unnecessarily idiosyncratic and could be made much simpler: you have a global minor mode, so just give that mode a keymap and put the toggle keybinding in it. That's the standard way for users to customise bindings, and changes they make will always be reflected immediately, unlike in the current code. (`C-s-g` uses "Super", right? If so, that's not a great default binding, when not all keyboards can produce Super.)
- The name `streamline--hide` is a bit confusing. Why not `streamline--show-original` for clarity?
- The `eval`s in [these forms](https://github.com/matthias-margush/streamline/blob/master/streamline.el#L47-L49) seem undesirable to me. What am I missing?
- Rather than direct people from the source code [to an online README](https://github.com/matthias-margush/streamline/blob/master/streamline.el#L32-L33), prefer to place a little documentation in the `Commentary`. Among other things, this text is used to document your package on its MELPA page and when people hit `?` in the `M-x list-packages` page.

Hope that helps!

**Comment by jcs090218** [comment]
@matthias-margush Hi, may I know the differences between this package and [feebleline](https://github.com/tautologyclub/feebleline)? :D Because both these two packages look similar to me.

**Comment by matthias-margush** [comment]
Thanks for the PR feedback. I'll be able to take a look next weekend. 

As far as the difference between feebleline and this:
- streamline goes out of its way to display nothing (modeline nor minibuffer), feebleline goes out of its way to display stuff in the minibuffer.
- the author of feebleline admits to using an ugly theme, and I would never do such a thing (:aghast:)

That said, feebleline looks great and  I might use feebleline myself and leave this for the true luddites.

**Comment by purcell** [comment]
Ping! :-)

**Comment by terlar** [comment]
There is also this one, that hides the modeline:
https://github.com/hlissner/emacs-hide-mode-line

Together with the built-in window devider I think it looks the same?
```
(setq window-divider-default-places t
      window-divider-default-bottom-width 1)
(window-divider-mode 1)
```

**Comment by riscy** [comment]
Please feel free to reopen if/when this is ready.  Thanks!

**Pull request closed without merging**
