### PR TITLE
Add recipe for ob-bitfield

### PR DESCRIPTION
**Pull request by gsingh93**
### Brief summary of what the package does

Adds `org-babel` support for generating bitfield diagrams from source blocks using https://github.com/Arth-ur/bitfield.

### Direct link to the package repository

https://github.com/gsingh93/ob-bitfield

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Checklist looks good, with a couple checkdoc nags:

`ob-bitfield.el` with checkdoc 0.6.2:
```
ob-bitfield.el:45: Argument `body' should appear (as BODY) in the doc string
ob-bitfield.el:85: Messages should start with a capital letter
```

One thing I notice is that this calls `(org-babel-eval (concat "python3 -m bit_field " args) "")` without any use of `shell-quote-argument`, which could potentially wreak havoc if someone (accidentally) adds shell control characters to any of the arguments (in-file which might contain an apostrophe or space, lanes, vspace, hspace, fontfamily, etc.)

I think this error: `(error "You need to specify a :file parameter")` should be calling `user-error` instead; probably the same with `(error "bitfield does not support sessions")` although I'm not familiar with babel sessions.

**Comment by gsingh93** [comment]
> ob-bitfield.el:45: Argument `body' should appear (as BODY) in the doc string

I had actually checked the docstrings for various `ob-*.el` packages out there and made this docstring consistent with those. That being said, I don't mind fixing this.

> ob-bitfield.el:85: Messages should start with a capital letter

Since the package is named "bitfield" and not "Bitfield", I think it makes sense to ignore this warning.  What do you think?

> One thing I notice is that this calls `(org-babel-eval (concat "python3 -m bit_field " args) "")` without any use of `shell-quote-argument`

Good catch, will fix this.

> I think this error: (error "You need to specify a :file parameter") should be calling user-error instead

You're right, will fix.

**Comment by gsingh93** [comment]
@riscy I've made the changes I mentioned above. I didn't quote `in-file`, as that argument doesn't come from the user, and while `out-file` does come from the user, it's only passed to `call-process` or `with-temp-buffer` (through the `svg-file` argument), and those elisp functions seem to handle it correctly what any additional quoting (at least with my limited testing of adding a single quote, double quote, and space in the filename).

**Comment by riscy** [comment]
Thank you!  All looks good here.

**Pull request merged**
