### PR TITLE
Diredc

### PR DESCRIPTION
**Pull request by Boruch-Baum**
### Brief summary of what the package does

This package extends emacs' dired-mode with features found in almost all file managers, and also some unique features:

    Resilient dedicated dual-pane frame.
        similar look to midnight commander.
        intelligent recovery of manually altered frame configuration
        exit diredc/dired cleanly and totally
    Navigable directory history
        backward, forward, or to a direct history entry
    File quick-preview mode
        inspired by, and similar to, midnight commander's "C-x q"
    Current file's supplemental information in minibuffer (optional)
        eg. output from getfattr, getfacl, stat, exif.
    Multiple panel views
        inspired by, and similar to, midnight commander's "M-t"
            superior configurability
            directly choose a specific panel view, or toggle to next
    Trash management
        per xfreedesktop standard
        restore trashed files to their original locations
        empty the trash, along with its administrative overhead
        view trash summary information
    Navigate "up" n parent directories ("^" or C-u ^")
    Quick shell window
        choose your default shell / terminal emulation mode
        choose your default shell program
        easily opt for pre-configured alternatives
        useful pre-defined shell variables
            $d1, $d2 dired-directory in this/other pane
            $f1, $f2 current dired file in this/other pane
            $t1, $t2 tagged elements in this other pane
                as a shell array variable, if supported by the shell
    Bookmark support
    Edit dired buffers (really wdired-mode, not diredc)
    Set both panels to same directory (use "=" or "C-u =")
        inspired by `midnight commander's "M-i"

Bonus customization features

    Customize colors for chmod bits (font-lock)
    toggle display of "hidden" or "undesirable" files (dired-omit mode)
    auto-refresh buffers (auto-revert-mode)
    highlight current line (hl-line-mode)
    don`t wrap long lines (toggle-truncate-lines)

### Direct link to the package repository

https://github.com/Boruch-Baum/emacs-diredc

### Your association with the package

Owner/maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly (some known unimportant warnings)
- [x] `M-x checkdoc` is happy with my docstrings (a few bugs and exceptions)
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Couple of very quick notes after a couple of minutes skimming the code, not a full review:

- Don't [set global bindings for the user](https://github.com/Boruch-Baum/emacs-diredc/blob/97d7f16e9af8b3eee141ddda5cec5f96e45ba562/diredc.el#L339-L342). Just tell them how to do it in your `Commentary:` section.
- Regarding colorising file modes, there's already the `diredfl` package for this, with decent theme support, so I'd suggest dropping that functionality here and perhaps suggesting that other package.
- Define `diredc-mode` with `define-derived-mode` or `define-minor-mode`. Among other things, this should let you get rid of `use-local-map` invocations.

**Comment by purcell** [comment]
Bonus:
- Yeah, looks like `diredc-mode` should be a global minor mode, and then diredc--hook-function should instead probably be a global minor mode. That gives you two handy keymaps to put your extra functionality in.

**Comment by Boruch-Baum** [comment]
@purcell : I've registered your feedback as issues at the repository, for me to get back to.

**Comment by riscy** [comment]
My own quick pass.


### diredc.el ###

byte-compile (using Emacs 27.1):
```
diredc.el:388:7:Warning: assignment to free variable `diredc-mode-map'
diredc.el:406:7:Warning: assignment to free variable `diredc-browse-mode-map'
In diredc--advice--wdired-exit:
diredc.el:829:20:Warning: reference to free variable `diredc-mode-map'
diredc.el:859:1:Warning: Unused lexical argument `oldfun'
In diredc--hook-function:
diredc.el:941:21:Warning: reference to free variable `diredc-mode-map'
In diredc-browse--hook-function:
diredc.el:1014:28:Warning: reference to free variable `diredc-browse-mode-map'
diredc.el:1093:1:Warning: Unused lexical argument `program'
In diredc-trash-assistant:
diredc.el:1385:34:Warning: reference to free variable `diredc-mode-map'
diredc.el:1473:1:Warning: Unused lexical variable `auto-revert-verbose'
diredc.el:1825:1:Warning: Unused lexical variable `x'
diredc.el:1825:1:Warning: Unused lexical variable `x'
In diredc-bonus-configuration:
diredc.el:2055:14:Warning: `directory-free-space-args' is an obsolete variable
    (as of 27.1); ignored, as Emacs uses `file-system-info' instead
In diredc-update-keymap:
diredc.el:2073:9:Warning: assignment to free variable `diredc-mode-map'
In diredc-do-not-quit-window:
diredc.el:2106:54:Warning: reference to free variable `diredc-mode-map'
diredc.el:2108:1:Warning: Unused lexical variable `x'
In diredc-mode:
diredc.el:2190:26:Warning: reference to free variable `diredc-mode-map'
In end of data:
diredc.el:2302:1:Warning: the following functions are not known to be defined:
    system-trash-info, popup-menu*
```
Some quick tips: declare variables with `defvar` before (or instead) of `setq`ing them; if you need a variable somewhere as a placeholder but need to leave it unused, you can prefix it with `_` to satisfy the byte-compiler (`_x`), but these may point to bugs.

checkdoc (using version 0.6.2):
```
Warning (emacs): 
diredc.el:979: Disambiguate view-mode by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
diredc.el:1024: Argument `str' should appear (as STR) in the doc string
Warning (emacs): 
diredc.el:1324: Disambiguate view-mode by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
diredc.el:1341: Keycode C-x embedded in doc string.  Use \\<keymap> & \\[function] instead
Warning (emacs): 
diredc.el:1343: Disambiguate view-mode by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
diredc.el:1883: Keycode M-i embedded in doc string.  Use \\<keymap> & \\[function] instead
```
Probably a false positive regarding  `Keycode C-x`/`M-i` (although you may want to be specific about which function, not which keybinding).

package-lint (using version 20200906.512):
```
6 issues found:
367:66: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
368:59: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
369:60: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
370:60: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
371:54: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
521:0: error: "dired-allow-duplicate-buffers" doesn't start with package's prefix "diredc".
```

Other possible lints:
- diredc.el#L783: It's safer to sharp-quote function names; use `#'` (and in other places)
- diredc.el#L10: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- diredc.el#L875: Single-line comments should usually begin with `;;` (and in other places)
- diredc.el#L745: Optionally use `unless ...` instead of `when (not ...)` (and in other places)
- diredc.el#L434: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by Boruch-Baum** [comment]
Thanks, Chris. I ran my tests on emacs 26 and emacs 28 snapshot.Much of
what you found are really false positives when you examine them, but
some I did change. Some notes follow. Thanks.

On 2020-11-08 22:17, Chris Rayner wrote:
>    My own quick pass.
>
>    byte-compile (using Emacs 27.1):
> ...
> diredc.el:1825:1:Warning: Unused lexical variable `x'

This is an example of the frustration of using these generally useful
tools: the several instances of this warning were due to usage of
function dotimes which requires a variable assignment for the iterator
even if it isn't used (false positive). I decided, fine, I would try to
avoid the warning anyway, so I replaced the function with (loop repeat n
do ...), which isn't flagged .... in emacs 26. However, in emacs 28
snapshot each usage is flagged twice. Ultimately, I used your suggestion
of prefixing the variable with an underscore.

>    checkdoc (using version 0.6.2):
> Warning (emacs):
> diredc.el:979: Disambiguate view-mode by preceding w/ function,command,variable,
> option or symbol.

This never reads clearly when referring to modes...

> diredc.el:1341: Keycode C-x embedded in doc string.  Use \\<keymap> & \\[functio
> n] instead

This (and similar) isn't referring to an emacs keybinding at all

>    package-lint (using version 20200906.512):
> 6 issues found:
> 367:66: error: This key sequence is reserved (see Key Binding Conventions in the
>  Emacs Lisp manual)

Not relevant for this buffer.

> 521:0: error: "dired-allow-duplicate-buffers" doesn't start with package's prefi
> x "diredc".

It's intentionally meant as a dired defcustom, and is the subject of
ongoing threads on the emacs-devel and emacs-bugs. That whole code
section is a prime candidate for inclusion in emacs 28, but go figure,
I've gotten mixed signals about whether the entire package will be
included or just portions of it or just snippets or nothing at all.

>      * diredc.el#L745: Optionally use unless ... instead of when (not ...)
>        (and in other places)

Oh, how I hate the 'unless' idiom (rant suppressed).

Thanks again. The new commits have been uploaded.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
Just touching base since I see the two issues are still open --

> Ultimately, I used your suggestion of prefixing the variable with an underscore.

I think that's your best bet, and it's also clear to humans.  You can also use that on, e.g. `diredc.el:1076:1:Warning: Unused lexical argument 'program'`, and the other one (`oldfun`).

I know you've deemed some of these unimportant, but if you get used to seeing warnings you might overlook real problems when they pop up.  All of them look like they could be gracefully handled/silenced, and some actually are important, e.g.,
```
diredc.el:388:7:Warning: assignment to free variable `diredc-mode-map'
```
happens because of the top-level `(setq diredc-mode-map (diredc--create-keymap))` where you should be using `defvar`.  `setq` will clobber existing definitions (like user customizations).  Luckily it looks like solving this warning will cause a few of the others to disappear.

> > 367:66: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)

> Not relevant for this buffer.

I may be missing something, but I think it's still relevant -- just because it's unlikely scenario doesn't mean a user can't expect the convention to hold?

**Comment by Boruch-Baum** [comment]
> Just touching base since I see the two issues are still open --
They're very low priority, so will probably stay open without additional action input. The `mode` issue had been the original implementation and caused more grief than the macro was worth, so was abandoned, and the global keybinding is conditional and is the whole point of loading the package; an affected user should just unload the feature or not load it in the first place.

> diredc.el:388:7:Warning: assignment to free variable `diredc-mode-map'
> ```
> happens because of the top-level `(setq diredc-mode-map (diredc--create-keymap))` where you should be using `defvar`. `setq` will clobber existing definitions (like user customizations). Luckily it looks like solving this warning will cause a few of the others to disappear.

OK. How do you want to be credited on the commit? Also, it makes makes my workflow a little more consistent if you can post future 'stuff' directly to the repository, as either an issue or a pull request. 

> > > 367:66: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
> > Not relevant for this buffer.
> I may be missing something, but I think it's still relevant -- just because it's unlikely scenario doesn't mean a user can't expect the convention to hold?

What exactly are you saying is relevant? In other words, what result that you get from `C-h b C-c i` do you think relevant for a `dired` buffer? I get commands related to `iedit-mode`, which I don't see *ever* relevant for `dired` buffers, which are read-only and require a special and separate (existing) handling mode for editing.

**Comment by Boruch-Baum** [comment]
@riscy : ping (I want to be certain you received my [post](https://github.com/melpa/melpa/pull/7213#issuecomment-732064331) 13hours ago; I didn't explicitly address you there)

**Comment by riscy** [comment]
Yes I saw this, but I mostly look at recipes on the weekends.

**Comment by riscy** [comment]
> The mode issue had been the original implementation and caused more grief than the macro was worth, so was abandoned

I understand.  I think this isn't a blocker, but the code should byte-compile cleanly, i.e. without warnings.

> and the global keybinding is conditional and is the whole point of loading the package; an affected user should just unload the feature or not load it in the first place.

Feedback we often give is that simply loading a package should not have side effects that modify Emacs's behavior.  There are a couple of rare exceptions to this (e.g., auto-mode-alist).  But you should not set keybindings, conditionally (e.g. if they have not been set already) or unconditionally (e.g. `(global-set-key [remap dired-other-frame] 'diredc)`).

> How do you want to be credited on the commit? Also, it makes makes my workflow a little more consistent if you can post future 'stuff' directly to the repository, as either an issue or a pull request.

Please don't worry about crediting me.  Though I can't speak for other MELPA maintainers, generally it's easier for me to leave comments on the MELPA PR since MELPA houses recipes from various scm repository managers.  I apologize if that's a burden for you.

> What exactly are you saying is relevant? In other words, what result that you get from C-h b C-c i do you think relevant for a dired buffer? I get commands related to iedit-mode, which I don't see ever relevant for dired buffers, which are read-only and require a special and separate (existing) handling mode for editing.

The lint points you [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html): "Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the **only** sequences reserved for users, so do not block them."

> That whole code
> section is a prime candidate for inclusion in emacs 28, but go figure,
> I've gotten mixed signals about whether the entire package will be
> included or just portions of it or just snippets or nothing at all.

Until we know for sure, I think it is better to not speculate and to follow the prefix rules.  You can add special handling (e.g. `define-obsolete-variable-alias`) if things change.

**Comment by Boruch-Baum** [comment]
> Please don't worry about crediting me. Though I can't speak for other MELPA maintainers, generally it's easier for me to leave comments on the MELPA PR since MELPA houses recipes from various scm repository managers. I apologize if that's a burden for you.

OK. Done and pushed, with the added benefit that the code byte-compiles almost perfectly now.

> > What exactly are you saying is relevant? In other words, what result that you get from C-h b C-c i do you think relevant for a dired buffer? I get commands related to iedit-mode, which I don't see ever relevant for dired buffers, which are read-only and require a special and separate (existing) handling mode for editing.
> 
> The lint points you [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html): "Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the **only** sequences reserved for users, so do not block them."

OK. Done. I'm not terribly happy with my solution alternative, `C-c ?`, but it satisfies the guidelines. I came to use `C-c i` through a cascade of my own mistakes, beginning with forgetting that `iedit` wasn't a part of emacs-core, and continuing by forgetting that the mode's default was `C-;` and that I was the one to locally change it because that keybinding is unavailable to emacs-nox users.

**Comment by Boruch-Baum** [comment]
I see that the bookmark commands are bound by default to the `C-c b` prefix, so have changed those, and have updated the documentation.

**Comment by riscy** [comment]
Here's the latest byte-compile (using Emacs 27.1):
```
diredc.el:406:7:Warning: assignment to free variable `diredc-browse-mode-map'
diredc.el:859:1:Warning: Unused lexical argument `oldfun'
In diredc-browse--hook-function:
diredc.el:1014:28:Warning: reference to free variable `diredc-browse-mode-map'
diredc.el:1076:1:Warning: Unused lexical argument `program'
diredc.el:1456:1:Warning: Unused lexical variable `auto-revert-verbose'
In diredc-bonus-configuration:
diredc.el:2038:14:Warning: `directory-free-space-args' is an obsolete variable
    (as of 27.1); ignored, as Emacs uses `file-system-info' instead
In end of data:
diredc.el:2285:1:Warning: the following functions are not known to be defined:
    system-trash-info, popup-menu*
```
I believe my comments in https://github.com/melpa/melpa/pull/7213#issuecomment-731867620 point the way toward cleaning most of these up.  The obsolete warning is okay.  Even though `((fboundp 'system-trash-empty) (system-trash-info))` is usually safe, you might want to do the bounded check on `system-trash-info` instead of `system-trash-empty`, and you can clean up the byte-compile using `declare-function` to silence the warning about `system-trash-info` not being defined, e.g.  something like `(declare-function system-trash-info "ext:system-trash.el" ...)`.

**Comment by Boruch-Baum** [comment]
On 2020-12-12 10:26, Chris Rayner wrote:
>  I believe my comments in [1]#7213 (comment) point the way toward
>  cleaning most of these up.

Thanks for the patience on this. I had been byte-compiling on v26, as
debian doesn't yet have v27, and in that environment these warnings
aren't showing for me. I do have a local copy of a v28 snapshot from a
month or two ago and am now byte-compiling against that also.

>  The obsolete warning is okay.

I'm noting it anyway to figure out how to make the relevant
customization for future versions.

>  Even though ((fboundp 'system-trash-empty) (system-trash-info)) is
>  usually safe, you might want to do the bounded check on
>  system-trash-info instead of system-trash-empty,

Done.

>  and you can clean up the byte-compile using declare-function to
>  silence the warning about system-trash-info not being defined

The fboundp check was sufficient to clean it up. Also, there is no
particular external file-name defined for the function's location, but
your advice was useful for popup-menu*.

Hopefully this can finally pass muster...

FULL DISCLOSURE: byte-compiling under emacs-snapshot (v28) produces
several new warnings for the setq-local usages at lines 1082-1087.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
> Thanks for the patience on this. I had been byte-compiling on v26

It's no problem. :)  I think it may not be a matter of which version you're using, but whether you're doing a clean byte-compile.  Many package authors compile their packages in an Emacs instance that has already evaluated their code (or its dependencies).  For what it's worth, flycheck-mode is robust against this.

The latest byte-compile with Emacs 27.1:
```
diredc.el:860:1:Warning: Unused lexical argument `oldfun'
diredc.el:1077:1:Warning: Unused lexical argument `program'
diredc.el:1457:1:Warning: Unused lexical variable `auto-revert-verbose'
In diredc-bonus-configuration:
diredc.el:2039:14:Warning: `directory-free-space-args' is an obsolete variable
    (as of 27.1); ignored, as Emacs uses `file-system-info' instead
```
For the unused oldfun and program, you can just rename these to `_oldfun` and `_program` for the compiler to know what's going on.  The unused autorevert variable can be fixed with e.g. `(require 'autorevert)` or `(eval-when-compile (require 'autorevert))` I believe.

**Comment by Boruch-Baum** [comment]
All done. Checked on emacs 26 and snapshot-28

On 2020-12-17 09:27, Chris Rayner wrote:
> diredc.el:1457:1:Warning: Unused lexical variable `auto-revert-verbose'
> ...
>    The unused autorevert variable can be fixed with e.g. (require
>    'autorevert) or (eval-when-compile (require 'autorevert)) I
>    believe.

That was a pleasant surprise. I thought the compiler snagged the unused
lexical variable because in my function it truly wasn't being used - I
needed to define it (as NIL) in order to unset its config feature when
auto-revert mode was invoked.

Are we all done?

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
There is just this package-lint 20200906.512:
```
1 issue found:
523:0: error: "dired-allow-duplicate-buffers" doesn't start with package's prefix "diredc".
```
I know you said it's possible this will become a part of core Emacs's dired, but 

> Until we know for sure, I think it is better to not speculate and to follow the prefix rules. You can add special handling (e.g. define-obsolete-variable-alias) if things change.

So while I realize this may feel pedantic, every package has to follow this rule and we should wait for https://github.com/Boruch-Baum/emacs-diredc/issues/3.

**Comment by riscy** [comment]
Sorry, I fogged up while writing that -- we should wait for https://github.com/Boruch-Baum/emacs-diredc/issues/3 and, as a separate issue, this package should _also_ follow the prefix rules.

**Comment by Boruch-Baum** [comment]
All done.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
Took a quick look at the latest -- I still see `(global-set-key [remap dired-other-frame] 'diredc)` at the top-level.  You can tell users how to do that in your `Commentary`.

**Comment by Boruch-Baum** [comment]
On 2020-12-18 10:35, Chris Rayner wrote:
>    Took a quick look at the latest -- I still see (global-set-key [remap
>    dired-other-frame] 'diredc) at the top-level. You can tell users how to
>    do that in your Commentary.

That was intentional, but I did it just now and pushed the change.

The reason I didn't do so prior was because while technically the remap
does use the function global-set-key, it's functionally a different
operation, more like an advice-around. If you think about, would you
have objected had a MELPA candidate advised-around some emacs global
function? I imagine that's done often by many packages, so I didn't
consider it on par with your prior guidance.

Anyway, the only purpose of the remap was to avoid confusion for users
who in the past used function dired-other-frame, which I have doubts is
a large user-set. I made a short note in the documentation.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by riscy** [comment]
> If you think about, would you have objected had a MELPA candidate advised-around some emacs global function?

Yes! :)  Generally we urge that simply loading a package should not have side effects that modify Emacs' behavior (or otherwise do some arbitrary amount of work) except in a narrow set of cases (e.g. adding to auto-mode-alist).  The usual advice in this case is to define a minor mode that users can toggle on (and then off again without restarting Emacs).

**Comment by riscy** [comment]
Okay, I think we're set.  Thanks for this, and for your patience with all the feedback.

**Comment by Boruch-Baum** [comment]
On 2020-12-20 10:09, Chris Rayner wrote:
>    Merged [1]#7213 into master.

Celebrations spontaneously ensue! Din of merriment resound throughout
the countryside! Two long weekends decreed for commemoration! (uh?)

Thanks.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Pull request merged**
