### PR TITLE
Added recipe for gabesoft-solarized theme

### PR DESCRIPTION
**Pull request by gabesoft**
### Brief summary of what the package does

Gabesoft-Solarized is my own version of the solarized theme using only the basic solarized colors.

### Direct link to the package repository

https://github.com/gabesoft/gabesoft-solarized

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]
All of the above

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ ] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
You need to put `gabesoft-solarized-theme.el` file or put `*-pkg.el` file. Please check by `make recipes/gabesoft-solarized `.

**Comment by gabesoft** [comment]
Addded *-pkg file

**Comment by purcell** [comment]
Thanks. Quick feedback:
- Please remove `for emacs` from the package description strings. All Emacs packages are for Emacs, so this is redundant, and best avoided.
- `gs-` is not a legal prefix. Use `gabesoft-solarized-` throughout instead, to match the package name.
- Using `gs-gui-color-p` and checking the capabilities of the display in which the theme is initially loaded is incorrect use of the face capabilities, and has various failure modes: you can actually define a single theme which will adapt itself to all possible displays. See my comments in #4413 for more on that.

**Comment by tarsius** [comment]
@gabesoft Any progress on this?

**Comment by gabesoft** [comment]
I think I'll wait on this for now.

**Pull request closed without merging**
