### PR TITLE
Recipe for poly-wdl

### PR DESCRIPTION
**Pull request by jmonlong**
### Brief summary of what the package does

This is a polymode to edit [Workflow Description Language](https://software.broadinstitute.org/wdl/) files. It uses [wdl-mode](https://github.com/zhanxw/wdl-mode) for the WDL parts and [sh-mode](https://www.emacswiki.org/emacs/ShMode) for the command chunks.

### Direct link to the package repository

[https://github.com/jmonlong/poly-wdl](https://github.com/jmonlong/poly-wdl)

### Your association with the package

I'm the maintainer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by jmonlong** [comment]
Sorry about that, I really thought the package-lint command passed. Maybe I had an older version.

I updated my [poly-wdl repo](https://github.com/jmonlong/poly-wdl) to fix the errors ([commit](https://github.com/jmonlong/poly-wdl/commit/fe2ee0c441795c35a8c127fa1f7006a5f251f564)).

For the warning, I could only find a snapshot version for the dependency wdl-mode. 

Should I commit something to my MELPA fork to launch the automated checks?

**Comment by riscy** [comment]
The checks aren't automated, just me running a script inside a sandbox. :)  It'd be a bit of work to fully automate them, because there are often idiosyncrasies in how packages are put together.  So, no need to commit anything else to MELPA at the moment.

**Comment by riscy** [comment]
...and, this looks great.  Welcome to MELPA! :)

**Comment by jmonlong** [comment]
Awesome, thanks!

**Pull request merged**
