### PR TITLE
Add elpa-clone recipe

### PR DESCRIPTION
**Pull request by dochang**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. What's the plan for this?

I'm wary of distributing this in its current form because our server will get hammered if people use it. Would you mind introducing a non-zero default sleep interval between successive fetches, so that there is some sort of basic rate limiting?

(Note also that a package repository usually contains `somepackage-readme.txt` files for each package too. There may also be GPG signatures.)

**Comment by xuchunyang** [comment]
BTW, there is an [ELPA mirror](https://mirrors.tuna.tsinghua.edu.cn/help/elpa/) provided by Tsinghua University TUNA Association, so if you want clone, for example, melpa, then use `rsync://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/`. rsync can save resources heavily.

**Comment by purcell** [comment]
Yes, we could also possibly set up an rsync service.

**Comment by dochang** [comment]
@purcell What about 5 seconds as minimal download interval? Is it enough?

**Comment by dochang** [comment]
Currently it lacks some features (signature, readme, etc).  I will add them in the future.

I wrote this package because there is no standard method for mirroring ELPA archive.  Most archives don't support sync services like rsync and there is only HTTP which supported by all ELPA archives.

**Comment by dochang** [comment]
@purcell A variable named `elpa-clone-download-interval` has been added.  Default value is 5 seconds.

**Comment by purcell** [comment]
Super, thanks! Separately I've opened #4020, because I think we should provide rsync access at some point.

**Pull request merged**
