### PR TITLE
Add helm-atoms package

### PR DESCRIPTION
**Pull request by dantecatalfamo**
### Brief summary of what the package does

This package adds a way to perform an interactive reverse variable lookup using helm. It allows you to find the name of an elisp variable by only knowing the value of its contents.

### Direct link to the package repository

https://github.com/dantecatalfamo/helm-atoms

### Your association with the package

I'm the maintainer!

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by dantecatalfamo** [comment]
Note: package-lint complains about `helm-source-atoms` not containing my package prefix, but according to the helm documentation, helm sources should begin with `helm-source-` for consistency.

https://github.com/emacs-helm/helm/wiki/Developing
> For consistency, prefix your source names with helm-source- (e.g. helm-source-info-emacs).

**Comment by riscy** [comment]
Thanks -- you reminded me to add `helm-source` to a list of forbidden package names.  Here's a quick first pass.

### helm-atoms.el ###

byte-compile (using Emacs 27.1):
```
helm-atoms.el:67:1:Warning: the function `helpful-variable' is not known to be
    defined.
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
```
1 issue found:
48:0: error: "helm-source-atoms" doesn't start with package's prefix "helm-atoms".
```
(This can pass.)

Other possible lints:
- helm-atoms.el#L59: You might use `when ...` instead of `unless (null ...)`

### Loadability ###

Verifying ability to #'load each file:
```
Loading helm-atoms.el
Done.
```

### Package ###

- GitHub API found `GNU General Public License v3.0`
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to helm-atoms.el
- helm-atoms.el (unknown license) -- Reverse variable lookup using Helm

**Comment by dantecatalfamo** [comment]
Thank you very much!

I've updated the package header to include license information. I've also replaced `(unless (null ...)` with `(when ...)`, as recommended.

Regarding the error warning that `helpful-variable` isn't defined, what would be the best way to deal with that? This is the code in question.

```elisp
(defun helm-atoms ()
  "Reverse variable lookup using helm."
  (interactive)
  (let ((symbol (helm :sources '(helm-source-atoms))))
    (when symbol
      (if (require 'helpful nil 'noerror)
          (helpful-variable symbol)
        (describe-variable symbol)))))
```

`helpful-variable` is a richer version of `describe-variable` provided by another package. In this case I'm trying to check if it's installed, then calling it if available. Is there a better way to do this so that it doesn't raise byte-compile warnings?

**Comment by riscy** [comment]
Ah, I see -- `(declare-function helpful-variable "ext:helpful.el" t t)` for example should do the trick.

**Comment by dantecatalfamo** [comment]
Added the line `(declare-function helpful-variable "ext:helpful.el" t t) ; Prevent byte-compiler warnings` to the top of the file, should be good to go! :+1:

**Comment by riscy** [comment]
Interesting package, thanks.

**Pull request merged**
