### PR TITLE
add recipe ignore-mouse

### PR DESCRIPTION
**Pull request by dradetsky**
### Brief summary of what the package does

Ignores mouse input events at the input-decode-map level.

### Direct link to the package repository

https://github.com/dradetsky/ignore-mouse

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

I'm worried if I tell melpa's maintainers I talk to myself, they'll be less inclined to accept my PR.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [ ] I've used `M-x checkdoc` to check the package's documentation strings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this (and re: talking to yourself, of course it's good to have an internal feedback loop).  Here's a quick first pass of the checklist -

⸺ `ignore-mouse.el` with checkdoc 0.6.2 (fix *within reason*):
```
ignore-mouse.el:36: All variables and subroutines might as well have a documentation string
ignore-mouse.el:41: All variables and subroutines might as well have a documentation string
ignore-mouse.el:50: All variables and subroutines might as well have a documentation string
ignore-mouse.el:55: All variables and subroutines might as well have a documentation string
```

⸺ `ignore-mouse.el` with package-lint 20240923.1044:
```
8 issues found:
29:0: error: `ignore-mouse/base-events' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
31:0: error: `ignore-mouse/wheel-events' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
33:0: error: `ignore-mouse/touch-events' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
35:0: error: `ignore-mouse/gen-numbered' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
40:0: error: `ignore-mouse/anglefy' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
43:0: error: `ignore-mouse/default-event-ids' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
49:0: error: `ignore-mouse/apply-to' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
54:0: error: `ignore-mouse/unapply-to' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
```

⸺ `ignore-mouse.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- The main file's `;;; Commentary` should not be a stub
```

⸺ Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

**Comment by dradetsky** [comment]
I don't think you should rely on licensee. I put this in my source
```
;; SPDX-License-Identifier: WTFPL
```

and licensee returns 90% confidence of it being MIT license (which isn't a bad prior, but also not what you're supposed to do). I can add the WTFPL text to LICENSE and it makes no difference to licensee, which continues to report 90% odds of MIT. Also, I can change it to

```
;; SPDX-License-Identifier: GPL-3.0-only
```

and licensee still thinks it's 90% likely to be MIT. 

In re the lint errors: are you only going to add my recipe if I fix them? I bitterly hate `--`, and I wish someone would explain why it's supposed to be a good idea. Moreover, all the violations (except in re commentary) are part of the implementation, not the interface.

**Comment by dradetsky** [comment]
actually, I went ahead and put https://www.gnu.org/licenses/gpl-3.0.txt in `LICENSE` and it still says MIT. I even went ahead and committed it to a new branch just in case that was relevant. It wasn't. You should probably stop using licensee.

**Comment by dradetsky** [comment]
Since @jamescherti submitted his version #9229 of this same package idea, and his version seems more likely to be rapidly accepted, I'm going to close my PR in favor of his. Instead, I've pulled my concern regarding licensee into #9230.

Fun fact: licensee says inhibit-mouse.el is MIT-licensed.

**Comment by riscy** [comment]
Thank you for being active in taking this step!

> I don't think you should rely on licensee.

FYI (and I should make this clearer in my output) licensee is what GitHub uses to determine licenses on its repo.  Those determinations are served by the GitHub API.  It's not any of our tooling that relies on licensee.

**Pull request closed without merging**
