### PR TITLE
Add insecure-lock

### PR DESCRIPTION
**Pull request by BlueFlo0d**
### Brief summary of what the package does

`insecure-lock` is an extensible screen lock framework.

### Direct link to the package repository

https://github.com/BlueFlo0d/insecure-lock

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Here's a quick first pass --

`insecure-lock.el` with byte-compile using Emacs 28.1:
```
insecure-lock.el:74:24: Warning: (lambda nil \.\.\.) quoted with ' rather than
    with #'
In end of data:
insecure-lock.el:201:11: Warning: the function `posframe-delete' is not known
    to be defined.
insecure-lock.el:192:19: Warning: the function `posframe-show' is not known to
    be defined.
insecure-lock.el:167:17: Warning: the function `redacted-mode' is not known to
    be defined.
insecure-lock.el:144:16: Warning: the function `display-buffer-full-frame' is
    not known to be defined.
insecure-lock.el:48:6: Warning: the function `keymap-substitute' is not known
    to be defined.
```

`insecure-lock.el` with checkdoc 0.6.2:
```
insecure-lock.el:71: All variables and subroutines might as well have a documentation string
insecure-lock.el:77: All variables and subroutines might as well have a documentation string
```

`insecure-lock.el` with package-lint 20221003.1636:
```
14 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
1:55: warning: You should depend on (emacs "24.1") if you need lexical-binding.
95:0: error: Global minor modes should be autoloaded or, rarely, `:require' their defining file (i.e. ":require 'insecure-lock"), to support the customization variable of the same name.
113:23: error: You should depend on (emacs "27.1") if you need `ignore-error'.
121:11: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-incf'.
141:11: error: You should depend on (emacs "24.3") if you need `setq-local'.
148:1: error: You should depend on (emacs "24.3") if you need `defvar-local'.
149:1: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
160:22: error: You should depend on (emacs "24.3") if you need `setq-local'.
169:18: error: You should depend on (emacs "24.3") if you need `setq-local'.
174:10: error: You should depend on (emacs "24.1") if you need `shr'.
175:1: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
188:55: error: You should depend on (emacs "25.1") if you need `shr-string-pixel-width'.
189:55: error: You should depend on (emacs "25.1") if you need `shr-string-pixel-width'.
```

`insecure-lock.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- insecure-lock.el#L75: Quoting this lambda may prevent it from being compiled
- insecure-lock.el#L92: It's safer to sharp-quote function names; use `#'`
- insecure-lock.el#L3: Have you done the paperwork to assign this copyright?
- insecure-lock.el#L11: This may be a copy-paste error?
```

`#'load`-check on each file:
```
Loading insecure-lock.el
  insecure-lock.el:Error: Emacs 28.1:
  (void-function keymap-substitute)
```

**Comment by BlueFlo0d** [comment]
Thanks for the quick reply! I've managed to fix some of the warnings.

Some remaining questions:
- I uses `keymap-substitute`, which doesn't exist before Emacs 29.1. The older Emacsen has `substitute-key-definition`, which is deprecated in Emacs 29.1. What's the right way to use either of the functions?
- Some modules depend on optional external dependencies (`posframe` and `redacted`). I'm using `eval-after-load` but it gives warnings. Is there a better way?
  - This seems to cause the `not known to be defined` warnings because byte-code compiler doesn't understand `eval-after-load`?

**Comment by riscy** [comment]
I'm assuming your first question is answered.

Optional external dependencies are not always easy to handle, but I'll take this one as an example:
```elisp
insecure-lock.el:238:8: Warning: the function `posframe-delete' is not known to be defined.
```
This happens inside this function:
```elisp
(with-eval-after-load 'posframe
  [...]
  (defun insecure-lock-posframe ()
    "`insecure-lock' module that display a posframe."
    (if insecure-lock-mode
        (progn
          (get-buffer-create " *Insecure Lock Screensaver*")
          (add-hook 'insecure-lock-update-functions insecure-lock-posframe-update-function)
          (funcall insecure-lock-posframe-update-function))
      (posframe-delete " *Insecure Lock Screensaver*")))
```

- I would just drop the `with-eval-after-load 'posframe` wrapper and define this function regardless as to whether posframe is installed.  If you're worried about the `(require 'shr)` you could inline it into a function, but you'd probably take on some warnings if you did this
- Read about `featurep` and `functionp` - the byte-compiler is smart about `functionp` and won't bother you about function calls that you wrap in a functionp, e.g. I'd recommend rewriting this as:
  ```elisp
  (defun insecure-lock-posframe ()
  "`insecure-lock' module that display a posframe."
  (unless (require 'posframe nil t) (user-error "Posframe not available"))
  (when (functionp 'posframe-delete)  ; this "when" hints the byte-compiler
    (if (not insecure-lock-mode)
        (posframe-delete " *Insecure Lock Screensaver*")
      (get-buffer-create " *Insecure Lock Screensaver*")
      (add-hook 'insecure-lock-update-functions insecure-lock-posframe-update-function)
      (funcall insecure-lock-posframe-update-function))))
  ```
-

**Comment by BlueFlo0d** [comment]
Hi riscy,

Thanks you for the suggestion! I've made those changes locally, but haven't commit yet.

Try loading the package on demand rather than `eval-after-load` is definitely a good idea. Thank you for letting me learn something new!

I have some doubt on whether it's worth it to use the `(when ...)` trick to silence the warning. IMO it clutters the code a bit, more `functionp` clauses need to be added if in the future more APIs are used, and the benefit is unclear. What do you think?

**Comment by riscy** [comment]
> I have some doubt on whether it's worth it to use the (when ...) trick to silence the warning. IMO it clutters the code a bit, more functionp clauses need to be added if in the future more APIs are used, and the benefit is unclear. What do you think?

Here are a couple of alternatives.  1, check out `declare-function` which you can use to tell the byte-compiler not to warn about those functions.  However this won't solve your issue of having to add/declare more APIs if you want them to be optional.  2, consider hiving the "optional" functionality into a separate package that would serve as an add-on to your package, but with the extra dependencies in place.

You mentioned that you think the benefit is unclear, but in my experience it can save users some grief if the packages they are installing are only raising warnings (and errors, obviously) when something is detectably wrong.  Imagine a user has 100 packages installed and half of them are raising "harmless" warnings on install because some maintainers want to be the exception to the rule -- we can do better than this.

**Comment by BlueFlo0d** [comment]
I've fixed all byte-compile and package-lint warnings on my Emacs 29. Any more TODOs before this package could be added?

**Comment by riscy** [comment]
Definitely improved, and thanks for accommodating.  Here are the latest --

`insecure-lock.el` with checkdoc 0.6.2:
```
insecure-lock.el:74: All variables and subroutines might as well have a documentation string
insecure-lock.el:80: All variables and subroutines might as well have a documentation string
insecure-lock.el:198: Messages should start with a capital letter
insecure-lock.el:230: Messages should start with a capital letter
```

`insecure-lock.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- insecure-lock.el#L78: There is no need to quote lambdas (neither #' nor ')
- insecure-lock.el#L3: Have you done the paperwork to assign this copyright?
- insecure-lock.el#L12: This may be a copy-paste error?
```

Based on the last two notes above, I think you may have copy-pasted some boilerplate from an existing file.

**Comment by BlueFlo0d** [comment]
> `insecure-lock.el` with checkdoc 0.6.2:
> 
> ```
> insecure-lock.el:74: All variables and subroutines might as well have a documentation string
> insecure-lock.el:80: All variables and subroutines might as well have a documentation string
>```
I think these functions are pretty trivial and their use are obvious from their names. Is it acceptable to not have docstring for them?
>```
> insecure-lock.el:198: Messages should start with a capital letter
> insecure-lock.el:230: Messages should start with a capital letter
> ```
Fixed.
> 
> `insecure-lock.el` with [melpazoid](https://github.com/riscy/melpazoid):
> 
> ```
> - insecure-lock.el#L78: There is no need to quote lambdas (neither #' nor ')
> ```
Fixed.
> ```
> - insecure-lock.el#L3: Have you done the paperwork to assign this copyright?
> - insecure-lock.el#L12: This may be a copy-paste error?
> ```
> 
> Based on the last two notes above, I think you may have copy-pasted some boilerplate from an existing file.
I have done copy right assignment with FSF before and I may intend to submit the package to GNU Elpa at some point. In this case, are these lines appropriate?

**Comment by riscy** [comment]
> Is it acceptable to not have docstring for them?

I agree in principle and have stopped insisting, but you're close enough to a clean checkdoc that I can't see why you wouldn't (and this way you don't get used to seeing checkdoc issues and ignoring them; some are useful).

> are these lines appropriate?

"This file is part of GNU Emacs." is not true.  "I have done copy right assignment with FSF before" is ambiguous to me; have you done it for this software in particular?

**Comment by BlueFlo0d** [comment]
I've updated the copyright notice to remove those clauses.

**Comment by riscy** [comment]
Thanks, that puts the checklist behind us.  Taking a closer look now --

- The use of `sudo` is very surprising; unless I'm missing something, you can't expect every user to even have sudo access and have this block work (you're effectively asking for root access to run the "true" command just to check the user's password).  Something like `su $(whoami) -c true` seems a little safer and more robust
- The community style generally entails spaces between function definitions, putting your `(require 'x)`'s at the top of the file, and probably also collecting your `defvar`s in one place instead of scattered between function definitions; since you're aiming for wider distribution with this package, you should follow that style whenever you can
- There's a mix of `error` and `user-error` in this package, but on first glance the `error`s look like they should be `user-error`s that don't open up backtraces (see the documentation on `user-error`)
- Minor stuff: compatability -> compatibility, autheticating -> authenticating,

**Comment by BlueFlo0d** [comment]
> * The use of `sudo` is very surprising; unless I'm missing something, you can't expect every user to even have sudo access and have this block work (you're effectively asking for root access to run the "true" command just to check the user's password).  Something like `su $(whoami) -c true` seems a little safer and more robust

I was struggling to make `su` accept input (it doesn't read from stdin) but I've now figured it out using built-in pty support for async process. I've switched to `su`.

> * The community style generally entails spaces between function definitions, putting your `(require 'x)`'s at the top of the file, and probably also collecting your `defvar`s in one place instead of scattered between function definitions; since you're aiming for wider distribution with this package, you should follow that style whenever you can

I'm grouping relevant `defun` and `defvar` together, which I think is more modular and readable. Variables in this packages are usually used pretty locally, restrained to a few functions (which immediately follows the `defvar`).

> * There's a mix of `error` and `user-error` in this package, but on first glance the `error`s look like they should be `user-error`s that don't open up backtraces (see the documentation on `user-error`)

The `error`s are indeed exceptional guards that should never be reached during normal operations. (`insecure-lock-lock-keys` `insecure-lock-unlock-keys` etc are not user facing command, they're supposed to be called in pairs by user facing commands).

> * Minor stuff: compatability -> compatibility, autheticating -> authenticating,

Fixed.

**Comment by riscy** [comment]
Thanks for accommodating, especially wrt the use of sudo!

> I'm grouping relevant defun and defvar together, which I think is more modular and readable.

I don't think this is worth blocking on, but you're contravening existing conventions and this helpful [Emacs lisp style guide](https://github.com/bbatsov/emacs-lisp-style-guide).  The inconsistency is probably not helping readability.  But the private defvars next to the functions that use them isn't as much of a concern.

In any case, merging - and welcome to MELPA. :)

**Pull request merged**
