### PR TITLE
Add recipe for message-view-patch

### PR DESCRIPTION
**Pull request by seanfarley**
-------

### Brief summary of what the package does

Colorizes (colourises) emails that contain patches (e.g. mailing list based workflows) for `mu4e` and `gnus`.

### Direct link to the package repository

https://github.com/seanfarley/message-view-patch

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, this looks neat.    And thanks for your close adherence to the checklist and for being diligent about crediting earlier code authors. :)

Two very minor notes from me, but after the first is addressed I think this should be a quick merge:

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- message-view-patch.el#L250: You can use `not` or `null`

**Comment by seanfarley** [comment]
Ah, good points and thanks for the feed back :-D I'll address those now.

**Comment by seanfarley** [comment]
Do I need to trigger a rebuild or something like that for my new commits?

**Comment by riscy** [comment]
Nope, just leaving a comment in the PR is good enough. :)  Thanks for this.

**Comment by seanfarley** [comment]
Thanks!

**Pull request merged**
