### PR TITLE
Drop `:commit` from `decor` and `typewriter-roll-mode` recipe

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
### Brief summary of what the package does

This library attempts to simplify removal of all frame (window) decorations via two simple functions and possibly some constants later for customization.

### Direct link to the package repository

https://github.com/KeyWeeUsr/decor

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by tarsius** [comment]
We usually don't pin packages to specific commits. Why is that being done here? I didn't spot anything concerning this in #8749.

**Comment by KeyWeeUsr** [comment]
@tarsius what should be used instead? I didn't find any `:tag` [here](https://github.com/melpa/melpa#recipe-format) :thinking: Or better said, is there a way to use a tag instead?

**Comment by tarsius** [comment]
Neither `:tag` nor `:commit` should be set. Melpa will then automatically publish the last commit from the default branch, and Melpa Stable will then automatically publish the highest tagged release. Users who want to use the latest commit can use Melpa and users who want to use only released version can use Melpa Stable.

**Comment by riscy** [comment]
I went ahead and changed this recipe to what it should be (and made sure I don't overlook these again on my end).  @KeyWeeUsr let us know when you're feeling ready for this change and we can merge.

**Comment by KeyWeeUsr** [comment]
@tarsius Thanks, I've adjusted the repo and added tags.
@riscy Feel free to merge. Other `:commit`-removing patches here:
* https://github.com/melpa/melpa/pull/8832
* https://github.com/melpa/melpa/pull/8750/commits/660be0559303ebd5846858a336df6d82ce09dd5b
* https://github.com/melpa/melpa/pull/8816/commits/13e87bf4e6f8f187e8f77c7ed58a68875b48656f

**Comment by tarsius** [comment]
Usually we prefer one pull-request per package, but in this case it would be convenient to have a single pull-request, which fixes this for all your packages. Thanks!

**Comment by KeyWeeUsr** [comment]
@tarsius Should be in the correct state now :+1:

**Comment by riscy** [comment]
Thanks both - I've also ensured on my end that I'm much more likely to notice this in the future.

**Pull request merged**
