### PR TITLE
Adding recipe for copilot-chat package

### PR DESCRIPTION
**Pull request by chep**
### Brief summary of what the package does

This package allows you to chat with github copilot.

### Direct link to the package repository

https://github.com/chep/copilot-chat.el

### Your association with the package
Author/maintainer

### Relevant communications with the upstream package maintainer
**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Do you know how this differs from https://github.com/emacsmirror/copilot and any other similar packages?

Otherwise, here's a quick first pass --

`copilot-chat-copilot.el` with byte-compile using Emacs 29.4:
```
copilot-chat-copilot.el:333:2: Warning: docstring wider than 80 characters
copilot-chat-copilot.el:333:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
copilot-chat-copilot.el:350:25: Warning: Unused lexical variable `err'
In copilot-chat--curl-analyze-response:
copilot-chat-copilot.el:360:45: Warning: Unused lexical argument `proc'
In copilot-chat--curl-ask-cb:
copilot-chat-copilot.el:430:12: Warning: Unused lexical variable `proc'
copilot-chat-copilot.el:429:4: Warning: Empty let* body
```

`copilot-chat-copilot.el` with checkdoc 0.6.2 (fix *within reason*):
```
copilot-chat-copilot.el:0: The first line should be of the form: ";;; package --- Summary"
copilot-chat-copilot.el:267: All variables and subroutines might as well have a documentation string
copilot-chat-copilot.el:305: Argument `prompt' should appear (as PROMPT) in the doc string
copilot-chat-copilot.el:314: All variables and subroutines might as well have a documentation string
copilot-chat-copilot.el:320: All variables and subroutines might as well have a documentation string
copilot-chat-copilot.el:323: All variables and subroutines might as well have a documentation string
copilot-chat-copilot.el:328: All variables and subroutines might as well have a documentation string
copilot-chat-copilot.el:331: All variables and subroutines might as well have a documentation string
copilot-chat-copilot.el:334: Some lines are over 80 columns wide
copilot-chat-copilot.el:334: Argument `segment' should appear (as SEGMENT) in the doc string
copilot-chat-copilot.el:361: You should convert this comment to documentation
copilot-chat-copilot.el:422: All variables and subroutines might as well have a documentation string
copilot-chat-copilot.el:164: Messages should start with a capital letter
copilot-chat-copilot.el:186: Messages should start with a capital letter
```

`copilot-chat-copilot.el` with package-lint 20240507.1722 and `package-lint-main-file` = "copilot-chat.el":
```
18 issues found:
47:0: warning: Closing parens should not be wrapped onto new lines.
103:3: warning: Closing parens should not be wrapped onto new lines.
165:39: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
166:34: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
167:41: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
187:50: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
240:46: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
276:27: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
289:57: error: You should depend on (emacs "27.1") if you need `json-parse-string'.
290:53: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
291:65: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
292:48: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
351:13: error: You should depend on (emacs "27.1") if you need `json-parse-string'.
414:27: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
415:53: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
416:36: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
430:17: error: You should depend on (emacs "25.1") if you need `make-process'.
443:51: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
```

`copilot-chat-copilot.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- copilot-chat-copilot.el#L2: `lexical-binding` must be on the end of the first line
```

`copilot-chat-markdown.el` with byte-compile using Emacs 29.4:
```
copilot-chat-markdown.el:37:19: Warning: assignment to free variable `copilot-chat--first-word-answer'
copilot-chat-markdown.el:39:17: Warning: reference to free variable `copilot-chat--first-word-answer'
In copilot-chat-markdown-init:
copilot-chat-markdown.el:51:9: Warning: assignment to free variable `copilot-chat-prompt'
```

`copilot-chat-markdown.el` with checkdoc 0.6.2 (fix *within reason*):
```
copilot-chat-markdown.el:0: The first line should be of the form: ";;; package --- Summary"
copilot-chat-markdown.el:34: All variables and subroutines might as well have a documentation string
copilot-chat-markdown.el:46: All variables and subroutines might as well have a documentation string
copilot-chat-markdown.el:51: All variables and subroutines might as well have a documentation string
```

`copilot-chat-markdown.el` with package-lint 20240507.1722 and `package-lint-main-file` = "copilot-chat.el":
```
2 issues found:
46:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
47:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
```

`copilot-chat-markdown.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- copilot-chat-markdown.el#L38: Consider using %T instead of %H:%M:%S in time strings
- copilot-chat-markdown.el#L41: Consider using %T instead of %H:%M:%S in time strings
```

`copilot-chat-org.el` with byte-compile using Emacs 29.4:
```
copilot-chat-org.el:38:19: Warning: assignment to free variable `copilot-chat--first-word-answer'
copilot-chat-org.el:40:17: Warning: reference to free variable `copilot-chat--first-word-answer'
In copilot-chat-org-init:
copilot-chat-org.el:52:9: Warning: assignment to free variable `copilot-chat-prompt'
```

`copilot-chat-org.el` with checkdoc 0.6.2 (fix *within reason*):
```
copilot-chat-org.el:0: The first line should be of the form: ";;; package --- Summary"
copilot-chat-org.el:35: All variables and subroutines might as well have a documentation string
copilot-chat-org.el:47: All variables and subroutines might as well have a documentation string
copilot-chat-org.el:52: All variables and subroutines might as well have a documentation string
```

`copilot-chat-org.el` with package-lint 20240507.1722 and `package-lint-main-file` = "copilot-chat.el":
```
2 issues found:
47:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
48:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
```

`copilot-chat-org.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- copilot-chat-org.el#L39: Consider using %T instead of %H:%M:%S in time strings
- copilot-chat-org.el#L42: Consider using %T instead of %H:%M:%S in time strings
```

`copilot-chat-shell-maker.el` with byte-compile using Emacs 29.4:
```
copilot-chat-shell-maker.el:33:2: Error: Cannot open load file: No such file or directory, shell-maker
```

`copilot-chat-shell-maker.el` with checkdoc 0.6.2 (fix *within reason*):
```
copilot-chat-shell-maker.el:0: The first line should be of the form: ";;; package --- Summary"
copilot-chat-shell-maker.el:111: The footer should be: (provide 'copilot-chat-shell-maker)\n;;; copilot-chat-shell-maker.el ends here
copilot-chat-shell-maker.el:44: All variables and subroutines might as well have a documentation string
copilot-chat-shell-maker.el:61: All interactive functions should have documentation
copilot-chat-shell-maker.el:67: All variables and subroutines might as well have a documentation string
copilot-chat-shell-maker.el:74: All variables and subroutines might as well have a documentation string
copilot-chat-shell-maker.el:83: All variables and subroutines might as well have a documentation string
copilot-chat-shell-maker.el:96: All variables and subroutines might as well have a documentation string
copilot-chat-shell-maker.el:102: All variables and subroutines might as well have a documentation string
```

`copilot-chat-shell-maker.el` with package-lint 20240507.1722 and `package-lint-main-file` = "copilot-chat.el":
```
5 issues found:
84:34: error: You should depend on (emacs "25.1") or the cl-lib package if you need `cl-struct-slot-value'.
96:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
97:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
98:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
99:3: error: You should depend on (emacs "24.4") or the nadvice package if you need `advice-remove'.
```

`copilot-chat-shell-maker.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- copilot-chat-shell-maker.el#L74: It's safer to sharp-quote function names; use `#'`
- copilot-chat-shell-maker.el#L46: `concat` may be unneeded; `insert` can take multiple arguments
```

`copilot-chat.el` with byte-compile using Emacs 29.4:
```
copilot-chat.el:106:22: Warning: function `copilot-chat-mode' defined multiple times in this file
In copilot-chat--format-data:
copilot-chat.el:119:42: Warning: Unused lexical argument `type'
In copilot-chat-prompt-mode:
copilot-chat.el:133:22: Warning: function `copilot-chat-prompt-mode' defined multiple times in this file
```

`copilot-chat.el` with checkdoc 0.6.2 (fix *within reason*):
```
copilot-chat.el:0: The first line should be of the form: ";;; package --- Summary"
copilot-chat.el:85: First line should be capitalized
copilot-chat.el:87: First sentence should end with punctuation
copilot-chat.el:91: Open parenthesis in column 0 should be escaped
copilot-chat.el:111: Argument `data' should appear (as DATA) in the doc string
copilot-chat.el:120: Argument `content' should appear (as CONTENT) in the doc string
copilot-chat.el:142: All variables and subroutines might as well have a documentation string
copilot-chat.el:173: All variables and subroutines might as well have a documentation string
copilot-chat.el:270: First sentence should end with punctuation
copilot-chat.el:284: All interactive functions should have documentation
copilot-chat.el:288: All interactive functions should have documentation
copilot-chat.el:337: All interactive functions should have documentation
copilot-chat.el:346: All interactive functions should have documentation
copilot-chat.el:364: All interactive functions should have documentation
copilot-chat.el:379: All interactive functions should have documentation
copilot-chat.el:394: All variables and subroutines might as well have a documentation string
```

`copilot-chat.el` with package-lint 20240507.1722 and `package-lint-main-file` = "copilot-chat.el":
```
9 issues found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
10:23: warning: Use a properly versioned dependency on "request" if possible.
10:33: warning: Use a properly versioned dependency on "markdown-mode" if possible.
10:49: warning: Use a properly versioned dependency on "org" if possible.
11:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
57:47: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
66:53: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
67:70: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
76:67: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
```

`copilot-chat.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- copilot-chat.el#L102: Unnecessary if you use `define-derived-mode`
- copilot-chat.el#L130: Unnecessary if you use `define-derived-mode`
- copilot-chat.el#L177: `concat` may be unneeded; `insert` can take multiple arguments
```

**Comment by chep** [comment]
Hi,

This package does not provides completion as the others packages. It is used to chat with github copilot and to send it code blocks for debug/document/explanation/…

Wow lot of work to do. I'm going to push corrections.

**Comment by riscy** [comment]
> Wow lot of work to do. I'm going to push corrections.

Let us know when you're ready!

**Comment by riscy** [comment]
But before you go to too much trouble, can you unpack this -

>  It is used to chat with github copilot and to send it code blocks for debug/document/explanation/…

Do the other packages not also provide this functionality?  We try to get authors to contribute to improving existing packages when this is the case.

**Comment by chep** [comment]
> But before you go to too much trouble, can you unpack this -
> 
> > It is used to chat with github copilot and to send it code blocks for debug/document/explanation/…
> 
> Do the other packages not also provide this functionality? We try to get authors to contribute to improving existing packages when this is the case.

No, other packages only provide completion. This feature requires a specific UI.

**Comment by riscy** [comment]
Just in case my thumbs-up wasn't visible to you, that sounds good to me.  Thanks!

**Comment by chep** [comment]
I pushed new commit and checkdoc byte compilation and package lint seem ok.

The only problem is keybindings. I can't use `C-c` but actually a lot of melpa package use it. Markdown-mode for example.

**Comment by riscy** [comment]
I've just checked markdown-mode against package-lint I didn't see any keybindings flagged (let me know if I missed something).  Note that not *everything* that starts with `C-c` is reserved for the user - you can see the manual for more.

Here's the latest -

⸺ `copilot-chat-curl.el` with checkdoc 0.6.2 (fix *within reason*):
```
copilot-chat-curl.el:72: First line is not a complete sentence
copilot-chat-curl.el:79: First line is not a complete sentence
```

`copilot-chat-markdown.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- copilot-chat-markdown.el#L1: `lexical-binding` must be on the end of the first line
- copilot-chat-markdown.el#L42: Consider using %T instead of %H:%M:%S in time strings
- copilot-chat-markdown.el#L45: Consider using %T instead of %H:%M:%S in time strings
```

`copilot-chat-org.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- copilot-chat-org.el#L41: Consider using %T instead of %H:%M:%S in time strings
- copilot-chat-org.el#L44: Consider using %T instead of %H:%M:%S in time strings
```

⸺ `copilot-chat-shell-maker.el` with byte-compile using Emacs 29.4:
```
copilot-chat-shell-maker.el:31:2: Error: Cannot open load file: No such file or directory, shell-maker
```

`copilot-chat-shell-maker.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- copilot-chat-shell-maker.el#L137: It's safer to sharp-quote function names; use `#'`
- copilot-chat-shell-maker.el#L82: Could this `point`/`point-max` comparison use `eobp`?
- copilot-chat-shell-maker.el#L112: Consider using %T instead of %H:%M:%S in time strings
- copilot-chat-shell-maker.el#L49: `concat` may be unneeded; `insert` can take multiple arguments
```

⸺ `copilot-chat.el` with checkdoc 0.6.2 (fix *within reason*):
```
copilot-chat.el:255: Lisp symbol `copilot-chat--buffer' should appear in quotes
```

⸺ `copilot-chat.el` with package-lint 20240923.1044 and `package-lint-main-file` = "copilot-chat.el":
```
9 issues found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
10:23: warning: Use a properly versioned dependency on "request" if possible.
10:33: warning: Use a properly versioned dependency on "markdown-mode" if possible.
10:49: warning: Use a properly versioned dependency on "org" if possible.
11:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
56:47: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
65:53: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
66:70: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
75:67: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
```

`copilot-chat.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- copilot-chat.el#L175: `concat` may be unneeded; `insert` can take multiple arguments
```

**Comment by chep** [comment]
Hello,

> I've just checked markdown-mode against package-lint I didn't see any keybindings flagged (let me know if I missed something). Note that not _everything_ that starts with `C-c` is reserved for the user - you can see the manual for more.

mardown-mode.el:
```
(defvar markdown-mode-map
  (let ((map (make-keymap)))
    ;; Markup insertion & removal
    (define-key map (kbd "C-c C-s") markdown-mode-style-map)
    (define-key map (kbd "C-c C-l") 'markdown-insert-link)
    (define-key map (kbd "C-c C-k") 'markdown-kill-thing-at-point)
    ;; Promotion, demotion, and cycling
    (define-key map (kbd "C-c C--") 'markdown-promote)
    (define-key map (kbd "C-c C-=") 'markdown-demote)
    (define-key map (kbd "C-c C-]") 'markdown-complete)
    ;; Following and doing things
    (define-key map (kbd "C-c C-o") 'markdown-follow-thing-at-point)
    (define-key map (kbd "C-c C-d") 'markdown-do)
    (define-key map (kbd "C-c '") 'markdown-edit-code-block)
    ;; Indentation
    (define-key map (kbd "RET") 'markdown-enter-key)
    (define-key map (kbd "DEL") 'markdown-outdent-or-delete)
    (define-key map (kbd "C-c >") 'markdown-indent-region)
    (define-key map (kbd "C-c <") 'markdown-outdent-region)
    ;; Visibility cycling
    (define-key map (kbd "TAB") 'markdown-cycle)
    ;; S-iso-lefttab and S-tab should both be mapped to `backtab' by
    ;; (local-)function-key-map.
    ;;(define-key map (kbd "<S-iso-lefttab>") 'markdown-shifttab)
    ;;(define-key map (kbd "<S-tab>")  'markdown-shifttab)
    (define-key map (kbd "<backtab>") 'markdown-shifttab)
    ;; Heading and list navigation
    (define-key map (kbd "C-c C-n") 'markdown-outline-next)
    (define-key map (kbd "C-c C-p") 'markdown-outline-previous)
    (define-key map (kbd "C-c C-f") 'markdown-outline-next-same-level)
    (define-key map (kbd "C-c C-b") 'markdown-outline-previous-same-level)
    (define-key map (kbd "C-c C-u") 'markdown-outline-up)
    ;; Buffer-wide commands
    (define-key map (kbd "C-c C-c") markdown-mode-command-map)
    ;; Subtree, list, and table editing
    (define-key map (kbd "C-c <up>") 'markdown-move-up)
    (define-key map (kbd "C-c <down>") 'markdown-move-down)
    (define-key map (kbd "C-c <left>") 'markdown-promote)
    (define-key map (kbd "C-c <right>") 'markdown-demote)
    (define-key map (kbd "C-c S-<up>") 'markdown-table-delete-row)
    (define-key map (kbd "C-c S-<down>") 'markdown-table-insert-row)
    (define-key map (kbd "C-c S-<left>") 'markdown-table-delete-column)
    (define-key map (kbd "C-c S-<right>") 'markdown-table-insert-column)
    (define-key map (kbd "C-c C-M-h") 'markdown-mark-subtree)
    (define-key map (kbd "C-x n s") 'markdown-narrow-to-subtree)
    (define-key map (kbd "M-RET") 'markdown-insert-list-item)
    (define-key map (kbd "C-c C-j") 'markdown-insert-list-item)
    ;; Lines
    (define-key map [remap move-beginning-of-line] 'markdown-beginning-of-line)
    (define-key map [remap move-end-of-line] 'markdown-end-of-line)
    ;; Paragraphs (Markdown context aware)
    (define-key map [remap backward-paragraph] 'markdown-backward-paragraph)
    (define-key map [remap forward-paragraph] 'markdown-forward-paragraph)
    (define-key map [remap mark-paragraph] 'markdown-mark-paragraph)
    ;; Blocks (one or more paragraphs)
    (define-key map (kbd "C-M-{") 'markdown-backward-block)
    (define-key map (kbd "C-M-}") 'markdown-forward-block)
    (define-key map (kbd "C-c M-h") 'markdown-mark-block)
    (define-key map (kbd "C-x n b") 'markdown-narrow-to-block)
    ;; Pages (top-level sections)
    (define-key map [remap backward-page] 'markdown-backward-page)
    (define-key map [remap forward-page] 'markdown-forward-page)
    (define-key map [remap mark-page] 'markdown-mark-page)
    (define-key map [remap narrow-to-page] 'markdown-narrow-to-page)
    ;; Link Movement
    (define-key map (kbd "M-n") 'markdown-next-link)
    (define-key map (kbd "M-p") 'markdown-previous-link)
    ;; Toggling functionality
    (define-key map (kbd "C-c C-x C-e") 'markdown-toggle-math)
    (define-key map (kbd "C-c C-x C-f") 'markdown-toggle-fontify-code-blocks-natively)
    (define-key map (kbd "C-c C-x C-i") 'markdown-toggle-inline-images)
    (define-key map (kbd "C-c C-x C-l") 'markdown-toggle-url-hiding)
    (define-key map (kbd "C-c C-x C-m") 'markdown-toggle-markup-hiding)
    ;; Alternative keys (in case of problems with the arrow keys)
    (define-key map (kbd "C-c C-x u") 'markdown-move-up)
    (define-key map (kbd "C-c C-x d") 'markdown-move-down)
    (define-key map (kbd "C-c C-x l") 'markdown-promote)
    (define-key map (kbd "C-c C-x r") 'markdown-demote)
    ;; Deprecated keys that may be removed in a future version
    (define-key map (kbd "C-c C-a L") 'markdown-insert-link) ;; C-c C-l
    (define-key map (kbd "C-c C-a l") 'markdown-insert-link) ;; C-c C-l
    (define-key map (kbd "C-c C-a r") 'markdown-insert-link) ;; C-c C-l
    (define-key map (kbd "C-c C-a u") 'markdown-insert-uri) ;; C-c C-l
    (define-key map (kbd "C-c C-a f") 'markdown-insert-footnote)
    (define-key map (kbd "C-c C-a w") 'markdown-insert-wiki-link)
    (define-key map (kbd "C-c C-t 1") 'markdown-insert-header-atx-1)
    (define-key map (kbd "C-c C-t 2") 'markdown-insert-header-atx-2)
    (define-key map (kbd "C-c C-t 3") 'markdown-insert-header-atx-3)
    (define-key map (kbd "C-c C-t 4") 'markdown-insert-header-atx-4)
    (define-key map (kbd "C-c C-t 5") 'markdown-insert-header-atx-5)
    (define-key map (kbd "C-c C-t 6") 'markdown-insert-header-atx-6)
    (define-key map (kbd "C-c C-t !") 'markdown-insert-header-setext-1)
    (define-key map (kbd "C-c C-t @") 'markdown-insert-header-setext-2)
    (define-key map (kbd "C-c C-t h") 'markdown-insert-header-dwim)
    (define-key map (kbd "C-c C-t H") 'markdown-insert-header-setext-dwim)
    (define-key map (kbd "C-c C-t s") 'markdown-insert-header-setext-2)
    (define-key map (kbd "C-c C-t t") 'markdown-insert-header-setext-1)
    (define-key map (kbd "C-c C-i") 'markdown-insert-image)
    (define-key map (kbd "C-c C-x m") 'markdown-insert-list-item) ;; C-c C-j
    (define-key map (kbd "C-c C-x C-x") 'markdown-toggle-gfm-checkbox) ;; C-c C-d
    (define-key map (kbd "C-c -") 'markdown-insert-hr)
    map)
  "Keymap for Markdown major mode.")
```

Anyway I'm gonna change the binding ;-) and fix other issues.

**Comment by chep** [comment]
I pushed new commits that should resolve the issues.

**Comment by riscy** [comment]
Thank you!  Here's the latest -

⸺ `copilot-chat-shell-maker.el` with byte-compile using Emacs 29.4:
```
copilot-chat-shell-maker.el:66:6: Warning: the function `copilot-chat-reset' is not known to be defined.
```

⸺ `copilot-chat.el` with checkdoc 0.6.2 (fix *within reason*):
```
copilot-chat.el:253: First sentence should end with punctuation
```

⸺ `copilot-chat.el` with package-lint 20240923.1044 and `package-lint-main-file` = "copilot-chat.el":
```
4 issues found:
8:23: warning: Use a properly versioned dependency on "request" if possible.
8:33: warning: Use a properly versioned dependency on "markdown-mode" if possible.
8:49: warning: Use a properly versioned dependency on "org" if possible.
8:70: warning: Use a properly versioned dependency on "chatgpt-shell" if possible.
```
For example version 0.3.2 of [request](https://stable.melpa.org/#/request).

⸺ `copilot-chat.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- copilot-chat.el#L173: `concat` may be unneeded; `insert` can take multiple arguments
```

⸺ Package and license:
- Specify `:fetcher` before `:repo` in your recipe (fixed just now)
- Reminder: ensure GitHub release v1.1.0 aligned with your current source code

**Comment by chep** [comment]
> Thank you! Here's the latest -
> 
> ⸺ `copilot-chat-shell-maker.el` with byte-compile using Emacs 29.4:
> 
> ```
> copilot-chat-shell-maker.el:66:6: Warning: the function `copilot-chat-reset' is not known to be defined.
> ```
> 
> ⸺ `copilot-chat.el` with checkdoc 0.6.2 (fix _within reason_):
> 
> ```
> copilot-chat.el:253: First sentence should end with punctuation
> ```
> 
> ⸺ `copilot-chat.el` with package-lint 20240923.1044 and `package-lint-main-file` = "copilot-chat.el":
> 
> ```
> 4 issues found:
> 8:23: warning: Use a properly versioned dependency on "request" if possible.
> 8:33: warning: Use a properly versioned dependency on "markdown-mode" if possible.
> 8:49: warning: Use a properly versioned dependency on "org" if possible.
> 8:70: warning: Use a properly versioned dependency on "chatgpt-shell" if possible.
> ```
> 
> For example version 0.3.2 of [request](https://stable.melpa.org/#/request).
> 
> ⸺ `copilot-chat.el` with [melpazoid](https://github.com/riscy/melpazoid):
> 
> ```
> - copilot-chat.el#L173: `concat` may be unneeded; `insert` can take multiple arguments
> ```
> 
> ⸺ Package and license:
> 
>     * Specify `:fetcher` before `:repo` in your recipe (fixed just now)
> 
>     * Reminder: ensure GitHub release v1.1.0 aligned with your current source code

This should be fixed. I removed the org dependency as it is, I think, built-in.
I changed the version to 1.2.0 and will create the release as soon as there is no more problems here.

**Comment by riscy** [comment]
Yes, looks good here!  Thank you for accommodating.

Welcome to MELPA! :)

**Comment by chep** [comment]
Thank you.

**Pull request merged**
