### PR TITLE
Add helm-rdefs recipe

### PR DESCRIPTION
**Pull request by saidie**
### Brief summary of what the package does

This package provides helm interface for [rdefs](https://github.com/knsmr/rdefs).

### Direct link to the package repository

https://github.com/saidie/emacs-helm-rdefs

### Your association with the package

maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
It looks there is bug when file path contains space.
- https://github.com/saidie/emacs-helm-rdefs/pull/1

**Comment by saidie** [comment]
Thank you for your pull request! It is merged and released https://github.com/saidie/emacs-helm-rdefs/releases/tag/v1.0.1

**Comment by syohex** [comment]
Looks good.

**Comment by syohex** [comment]
Merged

**Comment by saidie** [comment]
Thank you !

**Pull request merged**
