### PR TITLE
add flymake-kondor recipe

### PR DESCRIPTION
**Pull request by turbo-cafe**
### Brief summary of what the package does

package integrates clojure linter clj-kondo into flymake

### Direct link to the package repository

https://github.com/turbo-cafe/flymake-kondor

### Your association with the package

i'm mantainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Apologies for the long turnaround time on this one -- the code looks good, although I have one small nag related to this:

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
1 issue found:

1:0: warning: The package summary should start with an uppercase letter or a digit.
```

In fact, maybe `emacs linter with clj-kondo` may be better expressed as `Linter using clj-kondo`.  I also wonder if the name `flycheck-kondor` is a little too idiosyncratic -- why not `flycheck-clj-kondo`?

**Comment by tarsius** [comment]
Closing due to inactivity.
Let us know when you are ready so that we can reopen and finish the review.

**Comment by turbo-cafe** [comment]
hi, I updated source s.t. package-lint has no more complaints. is it possible to reopen current PR?

**Comment by riscy** [comment]
The one last thing to see about is adding a LICENSE file to the repository -- preferably one GitHub can detect (See: https://github.com/licensee/licensee).  You wouldn't have seen this in CONTRIBUTING.org or the README when you opened your PR, but it's something we're looking for now.

It'll be a quick merge after that.

**Comment by turbo-cafe** [comment]
added LICENSE.txt

**Pull request merged**
