### PR TITLE
Add recipe for yaml-pro

### PR DESCRIPTION
**Pull request by zkry**
### Brief summary of what the package does

yaml-pro builds on the work I did in https://github.com/zkry/yaml.el/ to add features when editing YAML. With the power of a parser, activities like folding, moving/deleting subtrees become more accurate. It also opens the possibility to add features such as editing a value in a detached buffer.

### Direct link to the package repository

https://github.com/zkry/yaml-pro

### Your association with the package

author and maintainer

### Relevant communications with the upstream package maintainer

n/a

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Quick first pass --

`yaml-pro-edit.el` with package-lint 20220607.738:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```

`yaml-pro.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- yaml-pro.el#L260: Prefer one blank line between this top-level form and the next
```

Package and license:
- Prefer equivalent recipe: `(yaml-pro :repo "zkry/yaml-pro" :fetcher github)`

**Comment by zkry** [comment]
Thanks for the help!

**Comment by riscy** [comment]
Thanks for this, ready to merge.  This is just spitballing, but I wonder if a mode like this would consider syntax highlighting or some kind of dissuasion for some of the most egregious yaml gotchas, e.g.
```yaml
key1: ”value1”
norway-country-code: No
letter-y: Y
```
(nonascii quotation marks, No = `false`, Y *sometimes* = `true` depending on the parser, etc.)

**Comment by zkry** [comment]
That's a good idea actually. I noticed some stuff in yaml mode regarding tricky-to-handle syntax highlight cases ([example](https://github.com/yoshiki/yaml-mode/issues/72)). I'll add these to the roadmap.

**Pull request merged**
