### PR TITLE
Add recipe for ob-base64

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
### Brief summary of what the package does

Mark your source code block containing base64-encoded data as `base64` with `:type` marking its extension and have it displayed in Emacs or externally.

### Direct link to the package repository

https://github.com/KeyWeeUsr/ob-base64

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

Style is copied from [`ob-template.el`](https://git.sr.ht/~bzg/worg/blob/master/org-contrib/babel/ob-template.el) and I'm not sure which of the functions could be possibly called via `apply` or likes with string building e.g. `(apply 'org-babel-<user's lang>-initiate-session)`:

`ob-base64.el` with package-lint 20231121.1907:
```
5 issues found:
81:0: error: "org-babel-expand-body:base64" doesn't start with package's prefix "ob-base64".
81:0: error: `org-babel-expand-body:base64' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
171:0: error: "org-babel-base64-var-to-base64" doesn't start with package's prefix "ob-base64".
175:0: error: "org-babel-base64-table-or-string" doesn't start with package's prefix "ob-base64".
179:0: error: "org-babel-base64-initiate-session" doesn't start with package's prefix "ob-base64".
```

but I wrapped it to `defalias` instead, so maybe that helps.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks @KeyWeeUsr - I see at the time of writing you have two other PRs open.   Per the [contributing doc](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#waiting-for-reviews-and-taking-feedback-into-account) I try to look at one per author per review pass -- and you can help with the backlog by not opening too many additional PRs simultaneously.

**Comment by riscy** [comment]
Thanks for your patience.  Here's the latest --

`ob-base64.el` with byte-compile using Emacs 29.1:
```
ob-base64.el:307:29: Warning: `point-at-eol' is an obsolete function (as of 29.1); use `line-end-position' or `pos-eol' instead.
```
I think for compatibility with Emacs 26 you'd prefer `line-end-position` here; worth future-proofing against this.

`ob-base64.el` with package-lint 20231121.1907:
```
5 issues found:
90:0: error: Aliases should start with the package's prefix "ob-base64".
90:0: error: `org-babel-expand-body:base64' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
91:0: error: Aliases should start with the package's prefix "ob-base64".
92:0: error: Aliases should start with the package's prefix "ob-base64".
93:0: error: Aliases should start with the package's prefix "ob-base64".
```
These are fine and in line with org-babel's prefix conventions, but is there an advantage to using aliases instead of just defining the functions with those names?  (I realize some linters may fuss because of prefixes, but they're already fussing because of the alias prefixes.)

Beyond the future-proofing above, the code looks good.  A couple more quick things I notice:
- `ob-base64--render-external-cleanup` isn't called from anywhere at a quick glance; is this called by some convention I'm unaware of?
- Some of your comments look useful to users (e.g. the block above `ob-base64-expand-body-base64`'s definition) and should probably be converted into docstrings in the future.
- `ob-base64-initiate-session` looks like a noop (which I think is okay) but it's docstring is therefore misleading -- better no docstring than a wrong one, imo, and maybe worth checking for other stuff like this.

**Comment by KeyWeeUsr** [comment]
@riscy Thanks :+1:

> [...] is there an advantage to using aliases instead of just defining the functions with those names [...]?

Just that if that specific linter or perhaps an alternative to it in the future decides to check the func names strongly and be quiet or softer about aliases this would pass normally. Working with the premise of any user being able to `(defalias 'my-dummy-alias #'package-func)` in the init file or wherever while the package still trying to "be nice" towards the linter. For example if I didn't like `auto-revert-mode` I might alias it as `refresh-mode`.

For `ob-base64--render-external-cleanup` it's me being blind, it should have been in the `(cond ...)` part. :sweat_smile: 

And `ob-base64-expand-body-base64` comment is copy-paste from [the template](https://git.sr.ht/~bzg/worg/blob/master/org-contrib/babel/ob-template.el) as well as the expanding function, however I moved it to the docstring.

**Comment by KeyWeeUsr** [comment]
Ah, alright :sweat_smile: I've dropped the aliases and kept the org-babel naming.

**Comment by riscy** [comment]
Thank you @KeyWeeUsr!  Altogether I think this is ready to merge.  A couple last nitpicks I notice:

```elisp
(defcustom ob-base64-default-external
  nil
  "Open images in external viewer or insert to Org buffer."
  :group 'ob-base64
  :type 'boolean)
```
I think the docstring is a little unclear here - I'd prepend "When non-nil", e.g. `When non-nil, open images using an external viewer.`

But if you're not sensitive about mixing types, you could possibly combine this customizable with `ob-base64-external-viewer-bin`, e.g.:
```elisp
(defcustom ob-base64-external-viewer-bin
  nil
  "When non-nil (e.g. /usr/bin/xviewer), use the image viewer at the supplied path."
  :group 'ob-base64
  :type 'string)
```

**Comment by tarsius** [comment]
`org-babel-expand-body:base64` requires `inf-base64`. Where can that library be obtained? Or is this a mistake?

**Comment by KeyWeeUsr** [comment]
@tarsius I don't use such a library nor is it present on my system, however there is for example package `inf-ruby` which is described as "Run a Ruby process in a buffer", so perhaps something on your system expects such a package (`inf-<lang>`) by reading any `org-babel-expand-body:<lang>` function?

**Comment by tarsius** [comment]
Your code is (optionally) requiring the `inf-base64`, see https://github.com/KeyWeeUsr/ob-base64/blob/d6a728f3c87981f590579af6cb543447fd56a081/ob-base64.el#L104. If I understand you correctly, you are saying that you are not actually aware of the existence of a `inf-base64` library. I therefore think you should not require that library.

**Comment by KeyWeeUsr** [comment]
That's very strange. It appears I included it there in the initial version and completely forgot about it. :disappointed:  Removed, thanks!

**Comment by tarsius** [comment]
You're welcome!

**Pull request merged**
