### PR TITLE
add new adafruit-wisdom package

### PR DESCRIPTION
**Pull request by gonewest818**
### Brief summary of what the package does

In the spirit of dad-joke, pulls a quote at random from adafruit.com. This is a curated list of mostly engineering, math and science-related quotes from well known figures in those fields.

### Direct link to the package repository

https://github.com/gonewest818/adafruit-wisdom.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

none needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gonewest818** [comment]
The Travis build error doesn't look related to this package:

- ["Failed to download melpa archive"](https://travis-ci.org/melpa/melpa/builds/299755174#L643)
- ["Package s- is unavailable"](https://travis-ci.org/melpa/melpa/builds/299755174#L654)
- ["Cask could not be bootstrapped. Try again later..."](https://travis-ci.org/melpa/melpa/builds/299755174#L655)

**Comment by purcell** [comment]
Thanks. I'll merge this, but here are a couple of tips:

- `(message "%s" quote)` can just be `(message quote)`.
- `(zerop (length quote))` should be `(null quote)`.

**Comment by purcell** [comment]
Also, welcome to MELPA!

**Comment by gonewest818** [comment]
Thanks!

I’ll make those changes too.

**Pull request merged**
