### PR TITLE
Add point-pos recipe

### PR DESCRIPTION
**Pull request by alezost**
### Brief summary of what the package does

Saves and restores point positions.  I always thought that it can't be
useful for anyone but me, but it looks like it can:

  https://github.com/alezost/point-pos.el/issues/1

So I wonder would it make sense to add it to MELPA?

### Direct link to the package repository

https://github.com/alezost/point-pos.el

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
I know you've looked at bookmarks to some extent, but have you looked at all the packages? Really feels like this must exist already!

Re. the code itself, you'd want to add a bunch of autoload cookies, and I also feel like you're probably reinventing a lot of code that's already in [ring.el](https://www.gnu.org/software/emacs/manual/html_node/elisp/Rings.html) for you to use.

**Comment by alezost** [comment]
> I know you've looked at bookmarks to some extent, but have you looked
> at all the packages?

No, actually I didn't search for similar packages at all :smile:
I don't insist on adding this package to MELPA, feel free to reject it!

> Really feels like this must exist already!

The alternatives surely can exist.  Perhaps @cmpitg knows: somehow he
found my package and decided to use it for some reason.

> Re. the code itself, you'd want to add a bunch of autoload cookies,

No, I think there should be only one autoload - for `point-pos-save`.
The other commands can't be used until a first position will be saved so
autoloading them seems useless to me.

> and I also feel like you're probably reinventing a lot of code that's
> already in ring.el for you to use.

Hm, I'm not sure it will suit the needs of `point-pos`, but I didn't
know about `ring.el`, thanks for pointing!

**Comment by purcell** [comment]
> I think there should be only one autoload - for point-pos-save.

Ah, yup, and I didn't notice that autoload when I reviewed.

Well, I'll go ahead and merge this for now, and you can follow up with any further changes that make sense to you - thanks! :-)

**Comment by kaushalmodi** [comment]
@alezost Seems like the [history][1] package is pretty close. Would you like to compare with that?

@cmpitg https://github.com/alezost/point-pos.el/issues/2

[1]: https://github.com/boyw165/history

**Comment by alezost** [comment]
Thanks for merging!
@kaushalmodi I replied in the issue you opened, thanks!

**Comment by cmpitg** [comment]
@alezost @kaushalmodi Thanks for keeping me in the loop :-). Since this issue is about getting `point-pos` into MELPA, I'll reply in alezost/point-pos.el#2.

**Pull request merged**
