### PR TITLE
Add prettier-js recipe

### PR DESCRIPTION
**Pull request by rcoedo**
### Brief summary of what the package does

Formats your JavaScript code using 'prettier' on file save.

### Direct link to the package repository

https://github.com/prettier/prettier-emacs/blob/master/prettier-js.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

** None needed **

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by rcoedo** [comment]
We decided to promote the prettier-js.el package to its own repository. There was an open PR already (https://github.com/melpa/melpa/pull/4765) but I'm making this one pointing to the new location.

**Comment by jbr** [comment]
Came here to add this recipe, happy to see it's here already.  Minor note: The direct link in the PR should be to https://github.com/prettier/prettier-emacs/blob/master/prettier-js.el or https://github.com/prettier/prettier-emacs/ not https://github.com/prettier/prettier-emacs/prettier-js.el, which doesn't work.

**Comment by rcoedo** [comment]
You're right @jbr, thanks for the feedback! 😄

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
