### PR TITLE
Add apparmor-mode recipe

### PR DESCRIPTION
**Pull request by alexmurray**
### Brief summary of what the package does

Major mode for editing apparmor security profiles, including syntax highlighting, with optional support for flycheck.

### Direct link to the package repository

https://github.com/alexmurray/apparmor-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks - quick first pass.

### apparmor-mode.el ###

byte-compile (using Emacs 27.1):
```
apparmor-mode.el:303:1:Warning: `"apparmor_parser"' is a malformed function
apparmor-mode.el:303:1:Warning: `(error line-start "AppArmor parser error for
    " (file-name) " in " (file-name) " at line " line ": " (message)
    line-end)' is a malformed function
apparmor-mode.el:304:28:Warning: reference to free variable `apparmor'
apparmor-mode.el:314:12:Warning: reference to free variable `apparmor-mode'
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- apparmor-mode.el#L228: There is no need to quote lambdas (neither #' nor ')
- apparmor-mode.el#L278: Could this point/point-min comparison use `bobp`?
- apparmor-mode.el#L24: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading apparmor-mode.el
Done.
```

### Package ###

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by alexmurray** [comment]
Thanks for the detailed review, this should be resolved with alexmurray/apparmor-mode@e3888ca and alexmurray/apparmor-mode@3ff9df5

**Comment by riscy** [comment]
No problem, apologies for the lengthening turnaround time.  The code looks good and the mode works well for me.

I'm just looking at your auto-mode-alist.  First I wonder if it would make sense to use auto-mode-alist's APPEND argument to make matching on the directory a last resort, just in case someone has a README.md or similar file hiding in that directory.

Also, I experimented with [this](https://github.com/nibags/apparmor-profiles/tree/master/apparmor.d) repository as an example and realized that someone working on that repository wouldn't have apparmor-mode enabled automatically, since it's missing the `/etc` prefix.  They could just add a magic comment, but if apparmor.d is a strong convention in the apparmor world, maybe it would make sense to just look for the apparmor.d directory, e.g., `(add-to-list 'auto-mode-alist '("\\/apparmor\\.d/" . apparmor-mode) t)`

I don't consider those blockers, but I think the first suggestion (use APPEND) is a probably a good idea.  Thanks!

**Comment by alexmurray** [comment]
Thanks @riscy - I tried your suggestion but using APPEND as t seemed to never have the mode get applied - so I think the best option is to use the more specific form for just /etc/apparmor.d as I already had since this should only contain apparmor profile and no other files anyway.

**Pull request merged**
