### PR TITLE
Add recipe for test-sha.

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Test ground for secure hash algorithms.

### Direct link to the package repository

https://github.com/jcs-elpa/test-sha

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thank you for this.  The output looks neat, but I'm stumped as to the typical use-case for such a package?

**Comment by jcs090218** [comment]
Yeah, this package probably aren't that useful. Only time I uses this when I am doing with `sha` work. Maybe by checking the encrypted data from frontend to backend, and then to database, etc.

**Comment by riscy** [comment]
It's absolutely fine if it's a niche package, but based on what you write above it seems like a crystal clear use-case hasn't really emerged yet (correct me if I'm wrong).  You have great output, but we should try to adhere to:

> MELPA provides a curated set of Emacs Lisp packages, not an exhaustive list of every single Emacs Lisp file ever created.

So if this is more of a demo or an exercise for your own sake, it might be best to hold off on adding it to MELPA.  If you're ever not sure, a good way to take the temperature of the community is to post an RFC (request-for-comments) somewhere.

**Comment by jcs090218** [comment]
Got you! I think I will close it since my reason isn't meet the requirement! 👍

**Comment by riscy** [comment]
Thanks for being understanding.  :)

**Pull request closed without merging**
