### PR TITLE
Update recipe for yeetube

### PR DESCRIPTION
**Pull request by thanosapollo**
### Brief summary of what the package does

Front-end for youtube

### Direct link to the package repository

https://git.thanosapollo.com/yeetube

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needex

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by tarsius** [comment]
Please mention the move at the old location, https://git.sr.ht/~thanosapollo/yeetube.el, so we can easily confirm the validity of this.

**Comment by thanosapollo** [comment]
I've changed the URL in the package description a while ago & mention the new source in the readme installation section, plus all the commits are signed by me, the sourcehut repo description is also marked with (mirror). 

What else should I do?

**Comment by thanosapollo** [comment]
I deleted the sourcehut repo & would like to remove this package recipe from melpa, thank you.

**Comment by tarsius** [comment]
> I've changed the URL in the package description a while ago & mention the new source in the readme installation section, plus all the commits are signed by me, the sourcehut repo description is also marked with (mirror).
> 
> What else should I do?

I did not notice that the commits are signed or that the sourcehut repository was marked as mirror(*), and apologize for that.

(*) I don't know what that would look like and didn't spot an redirection url. I actually looked for signs like this.

I did of course notice that the user name was the same, but that alone isn't proof that this isn't a hostile takeover; however unlikely, such a match could also mean that someone is playing the long game.

When I did not find a link to the new repository in the readme, I looked at the copy of the repository that I already had on disk, not realizing that it was several days out of date. I noticed that the url header still referred to sr.ht, and based on that I decided to ask you for help.

> I deleted the sourcehut repo & would like to remove this package recipe from melpa, thank you.

I can only assume that you want your package removed from Melpa because we "make unreasonable requests and therefore it is not worth the effort to have a package distributed there". Please realize that we have to deal with a lot of requests and are bound to make a mistake here and there.

I am not merging the removal just yet, in the hope you will reconsider. Removing your package will only hurt its popularity, that's pretty much the only effect.

**Comment by thanosapollo** [comment]
The description of the repo included `(mirror)`, I've referenced the git.thanosapollo.com repo in the installation instructions etc. Plus I'm the one that submitted the original recipe and thats the same domain name for the email contact since day 1. 

But the main reason is that I don't like using github nor do I see any point of using it (I'm not a developer). 

I'm doing this just for fun and anything that makes it less fun is not something that I want to deal with or invest my time. 

I don't mind if the package is on melpa or not since I don't gain anything from it being popular or not either. It's just a niche emacs package that I made to learn emacs lisp.

Apologies if I gave you the wrong impression or offended you in my decision, I'm a fan of your work with emacs. 

Thank you for trying to be accommodating and understanding of the situation.

**Comment by tarsius** [comment]
Seems I not only did a subpar job at verifying your identity, but also jumped to conclusions. :zany_face:

I have since verified that the new commit were signed with the same key as the old commits I had already fetched from the old repository.

I'll merge the migration commit in a bit.

**Comment by thanosapollo** [comment]
No worries, I handled this badly too. Have a nice day & thank you for your work.

**Comment by tarsius** [comment]
> No worries, I handled this badly too. Have a nice day & thank you for your work.

Misunderstanding and conflicts happen. What matters is that we found a way out of that.

> I'll merge the migration commit in a bit.

Merged. (Due to technical issues this pr has to be closed as "unmerged".)

**Pull request closed without merging**
