### PR TITLE
Add `keepass-mode` package

### PR DESCRIPTION
**Pull request by ifosch**
### Brief summary of what the package does

`keepass-mode` allows the user to open, read, and query a KeePass DB file.

### Direct link to the package repository

https://github.com/ifosch/keepass-mode

### Your association with the package

I'm the maintainer to the package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.

Including keepass-mode-pkg.el is discouraged -- MELPA will create a `-pkg.el` file, so this may be worth excluding from your recipe.  More below:

### keepass-mode-autoloads.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
- No issues! 💯

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

(Skipping package-lint on this file)

Other static checks/suggestions:
- keepass-mode-autoloads.el#L22: Prefer `https` over `http` (if possible)

### keepass-mode.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
- No issues! 💯

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191220.419):
- No issues! 💯

Other static checks/suggestions:
- keepass-mode.el#L49: It's safer to sharp-quote function names; use `#'`
- keepass-mode.el#L57: No `format` required; messages are already f-strings
- keepass-mode.el#L59: No `format` required; messages are already f-strings
- keepass-mode.el#L22: Prefer `https` over `http` (if possible)
- The function `keepass-mode-command` looks like it should be using `shell-quote-argument` for all of the arguments; otherwise if one of the arguments has special characters (|, &, etc.) then the command will fail

<details><summary>Misc...</summary>

### Maintainer/license

- PR by ifosch: https://github.com/ifosch/keepass-mode
- License appears to be written into individual files
- Including keepass-mode-pkg.el is discouraged -- MELPA will create a `-pkg.el` file

### Summary

- (keepass-mode :fetcher github :repo "ifosch/keepass-mode" :branch "melpa")
- Package-Requires: emacs "27"
- _elisp/keepass-mode-autoloads.el (gpl): Manually generated autoloads
- _elisp/keepass-mode-pkg.el (gpl): Mode for KeePass DB
- _elisp/keepass-mode.el (gpl): Mode to open Keepass DB
</details>

**Comment by ifosch** [comment]
@riscy I've implemented all your suggestions and fixed the checks in the `melpa` branch. Let me know if there's anything else. Thank you!

**Comment by riscy** [comment]
Thanks, looks much better.

I've been advised to make sure packages are adding GitHub compatible LICENSE/COPYING files to the repository when possible.  You could use the same LICENSE.md file MELPA uses, for example, and then the GitHub API would pick up that you're GPL3.

I'm not so familiar with what's going on in keepass-mode-autoloads.el -- if we want to autoload keepass-mode, couldn't we just add an autoload cookie to keepass-mode.el and have one fewer file?  In reading the documentation, it seems like the "keepass.mode" argument in this:
```elisp
(autoload 'keepass-mode "keepass.mode" nil t)
```
should be "keepass-mode" (since that's the name of the corresponding file).

I may be missing something, since this is new to me, but maybe you can help clarify?

**Comment by ifosch** [comment]
Now the upstream contains a LICENSE.md file with the GPL 3.0 text, and I've implemented the autoload cookie, removing the `keepass-mode-autoloads.el` file.

**Comment by tarsius** [comment]
> Now the upstream contains a LICENSE.md file with the GPL 3.0 text

It would be better to use a `LICENSE` file which contains a copy of the license that has *not* been markdownified. Tools such as those by Github and the Emacsmirror can detect the latter but not (yet?) the former.

**Comment by ifosch** [comment]
> It would be better to use a `LICENSE` file which contains a copy of the license that has _not_ been markdownified. Tools such as those by Github and the Emacsmirror can detect the latter but not (yet?) the former.

Fine, LICENSE.md removed, and replaced with a LICENSE with plain GPL text.

**Comment by riscy** [comment]
Thanks for your patience with that, @ifosch -- I was not fully aware of the problems with a markdownified license before this.

**Comment by ifosch** [comment]
> Thanks for your patience with that, @ifosch -- I was not fully aware of the problems with a markdownified license before this.

No problem :smile:

**Comment by riscy** [comment]
Regarding your major mode definition:
```elisp
;;;###autoload
(define-derived-mode keepass-mode tabulated-list-mode "KeePass mode"
  "KeePass mode."
  (setq keepass-mode-db buffer-file-truename)
  (setq keepass-mode-password (keepass-mode-ask-password))
  (setq keepass-mode-group-path "")
  (kill-buffer)
  (switch-to-buffer (format "*KeePass %s*" keepass-mode-db))
  (use-local-map keepass-mode-map)
  (make-local-variable 'keepass-mode-db)
  (make-local-variable 'keepass-mode-password)
  (make-local-variable 'keepass-mode-group-path)
  (keepass-mode-open))

;; ...
(add-to-list 'auto-mode-alist '("\\.kdbx\\'" . keepass-mode))
(add-to-list 'auto-mode-alist '("\\.kdb\\'" . keepass-mode))
```
It feels like this is using a major mode as a "backdoor" to the *KeePass XYZ* buffer -- i.e., the major mode kills the buffer it was started in.  I can understand the usage pattern you're going for, though (and I like it).

I feel like killing the buffer and switching to a new one is what is forcing you to manually `(use-local-map keepass-mode-map)`, whereas that would be automatic if the buffer didn't change.  I also wonder if deriving from `tabulated-list-mode` is having an effect, since the buffer we end up in (*KeePass XYZ*") is not the buffer we started with?

I'll stop there and see what you think about that -- maybe there is a way to write a <kbd>M-x keepass</kbd> command that retains a lot of the workflow you're going for.

**Comment by ifosch** [comment]
@riscy Thanks for your points. I just reduced the major mode removing these lines. This was a very early development stage, where in some point I found I needed this, but I just removed, and it works perfectly without the buffer switch and, as you felt, the mode map manual set.

I discard the implementation of such `M-x keepass` command for now, since I think it's better to work with this attached to using a specific file, but I was considering to have some way of creating files in some future, maybe using such a function.

**Comment by riscy** [comment]
Okay, right on.  Then the next (and I think last!) thing I'll point out is that these variables
```elisp
(defvar keepass-mode-db "")
(defvar keepass-mode-password "")
(defvar keepass-mode-group-path "")
```
feel like they want to be using `defvar-local`, instead, especially the password. (Currently the password is asked for every time we open the buffer; then we set the *global* value of keepass-mode-password to that password -- which persists everywhere -- and then we make it local).  So instead we could have:
```elisp
(defvar-local keepass-mode-db "")
(defvar-local keepass-mode-password "")
(defvar-local keepass-mode-group-path "")

;; ..

;;;###autoload
(define-derived-mode keepass-mode tabulated-list-mode "KeePass"
  "KeePass mode for interacting with the KeePass DB.
\\{keepass-mode-map}"
  (setq-local keepass-mode-db buffer-file-truename)
  (setq-local keepass-mode-password (keepass-mode-ask-password))
  (setq-local keepass-mode-group-path "")
  (keepass-mode-open))
```
Ping me when ready and we can get this merged.

**Comment by ifosch** [comment]
@riscy I see your point in this change also. I've changed to use `defvar-local` and `setq-local`. Thanks!

**Comment by riscy** [comment]
Great thanks!  And, welcome to MELPA!

**Comment by ifosch** [comment]
> Great thanks! And, welcome to MELPA!

Thank you very much!

**Pull request merged**
