### PR TITLE
Add a recipe for blackjack-el

### PR DESCRIPTION
**Pull request by gdonald**
### Brief summary of what the package does

This package allows you to play the game of Blackjack in Emacs.

### Direct link to the package repository

https://github.com/gdonald/blackjack-el

### Your association with the package

I am the original author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
Always fun to see more games for Emacs.
A few suggestions:

- You'll want to autoload the entry point to the game so users can lazy-load the library. e.g.

```emacs-lisp
;;;###autoload
(defun blackjack ;etc
```

- The lexical binding declaration needs to be on the first line of the file for it to work.

- Most of the functions in the program should not be "public". Use the two dash convention to indicate they are internal. e.g.

```emacs-lisp
(defun blackjack--next-id ;;etc
```

- It's idiomatic to give predicates a `-p` or `p` suffix. e.g.

```emacs-lisp
(defun blackjack-hit-p
```

However, I would suggest rethinking game move validation.
Instead of splitting it into separate functions for each type of move,
you could have a single `blackjack-valid-move-p` predicate which takes the game state object
and a move as arguments. e.g.

```emacs-lisp
(defun blackjack-valid-move-p (move game) 
```

As far the UI goes, I would reconsider reading from the minibuffer in a loop.
You could, instead, define a major mode which binds keys in the game's buffer to commands.
That would allow the user to easily customize the key bindings and visually would keep the focus "in the buffer". 
You can also use the header-line to display hints for keybindings.
[wordel](https://www.github.com/progfolio/wordel) is an example of such an interface.

**Comment by riscy** [comment]
I think this is great advice from @progfolio.  I've got surface-level comments to add on this quick first pass --

`blackjack.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- blackjack.el#L11: Triple semicolons `;;;` are usually for section headings
- blackjack.el#L1: `lexical-binding` must be on the end of the first line
- blackjack.el#L860: You can use `not` or `null`
```

Package and license:
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to blackjack.el
- GNU General Public License v2.0 (via API) is incompatible with MELPA currently; see the discussion in https://github.com/johannes-mueller/company-wordfreq.el/issues/6 for example
- Minor, but your `URL` is `https://https://github.com/gdonald/blackjack-el` (an extra https)

**Comment by gdonald** [comment]
> - blackjack.el#L860: You can use `not` or `null`

Thank you for all the feedback and comments, I appreciate it.

I do not understand this bit of feedback, I am already using `not` on line 860:

https://github.com/gdonald/blackjack-el/blob/main/blackjack.el#L860

`(if (not (eq content nil))`

Can you please clarify?  Thanks.

**Comment by progfolio** [comment]
> (if (not (eq content nil))

Not nil = anything except nil. e.g.

```emacs-lisp
(if content ;etc
```

**Comment by gdonald** [comment]
I have completed the work with addressing all of your suggested fixes and updates.  Please let me know if there is anything else.  Thanks.

**Comment by riscy** [comment]
I think this is good to merge, but please consider some of these suggestions on the code itself:

- `progn` isn't necessary in the "else" part of an `if` form, e.g. the second `progn` here:
```elisp
      (if (blackjack--player-hand-done-p player-hand)
          (progn ...)
        (progn
```
- The code contains a combination of tabs and spaces; many people will customize the width at which tabs appear in their Emacs, in which case your code will appear jagged; prefer spaces (q.v. `indent-tabs-mode`)
- You should use `setq` when it makes sense, instead of liberally using `setf` everywhere to set variable values; `setf` has much heavier semantic "weight" and you'll cause people to really scratch their head if you use it where a `setq` would do
- You only need to use `let*` (with an asterisk) if you need to use values declared earlier on in the `let` block (it's also a useful visual annotation for other programmers *when* that's the case).  E.g. `(let* ((cards (slot-value player-hand 'cards)))` can just use a `let`; or, `(let* ((player-hand nil) (dealer-hand nil))` could also be written with a normal `let` (it could also be written `(let (player-hand dealer-hand) ...` if you just need nil values)

**Comment by gdonald** [comment]
> I think this is good to merge, but please consider some of these
> suggestions on the code itself:

I have completed all of your suggested improvements.

Thank you for teaching me lisp :)

**Pull request merged**
