### PR TITLE
Add recipe for coercion

### PR DESCRIPTION
**Pull request by liuyinz**
### Brief summary of what the package does

Inspired by coercion in abolish.vim, switch naming convention style quickly.
Extending features by define split and join functions.

### Direct link to the package repository

https://github.com/liuyinz/coercion.el

### Your association with the package

maintainer/author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by mattiasb** [comment]
How does this compare to the `string-inflection` package?

**Comment by liuyinz** [comment]
I extract every transformation as stand-alone commands rather than pair-style in `string-reflection` which must binds
for_bar => FOO_BAR together.

**Comment by riscy** [comment]
Thanks for this.  Code looks good, although maybe we can buff up the `;;; Commentary`?  I had to go through google to stumble my way into the repository for abolish.vim.  Then I scrolled halfway down the README to find the section on coercion:

> https://github.com/tpope/vim-abolish#coercion

Maybe we can do the MELPA index one better and write up a self-contained `;;; Commentary` describing what this package can do.  Even better, include the distinction between this package and string-inflection that you just mentioned above in that Commentary.

Here's some quick notes in the meantime:

- The repo has an MIT license but the source file has GPL boilerplate
- coercion.el#L108: It's safer to sharp-quote function names; use `#'`

**Comment by liuyinz** [comment]
@riscy fix these problem yet.

**Comment by riscy** [comment]
Thank you, looks great.  Merging!

**Pull request merged**
