### PR TITLE
Add dot-env recipe

### PR DESCRIPTION
**Pull request by amodelbello**
### Brief summary of what the package does

[.env](https://github.com/motdotla/dotenv) functionality for emacs

### Direct link to the package repository

https://github.com/amodelbello/dotenv.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

After building the recipe and running `package-install-file`, the package wasn't available in my emacs environment until I manually evaluated the .elc file. I'd never used that command before and I'm not sure if this is normal behavior or if I did something wrong in building/installing 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by amodelbello** [comment]
@manuel-uberti - Thanks, no I hadn't seen that package yet. Looks useful but geared more towards project-scoped environment variables.

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`dotenv.el` with package-lint 20230605.1550:
```
1 issue found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
```
(You've just got "summary")

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

Package name:
- `dotenv-mode` already exists: https://melpa.org/#/dotenv-mode -- unfortunately this is a direct namespace conflict, and we should work to find a non-conflicting name for your package

**Comment by amodelbello** [comment]
Hi @riscy I've made the suggested changes:

1. Added a summary
2. Added a license
3. Changed name from `dotenv` to `dot-env`

**Comment by riscy** [comment]
I can see the value in this, but this also strikes me as the quickest possible implementation.  For example none of these lines are handled correctly due to the simplicity of the parser:
```env
test_string = this is my \"test string\"
padding="    "
question = "What's new?"
invalid: 10
```
I think where you want to start with a curated MELPA package for this functionality this is to write a robust **reader** of .env files (does none exist?  This would be a significant contribution in that case), and then use that as a backend for a package like this.

Consider for example that Emacs has a robust backend for json files:
```elisp
(alist-get 'padding (json-read-from-string "{\"padding\": \"   \"}"))
```

**Comment by amodelbello** [comment]
@riscy It is indeed the quickest possible implementation. I'm unable to find an existing dotenv parser and am willing to create one that implements the full spec. Would the best approach be to submit two separate packages, one for front end and one for the parser, or should I just add the parser to the current package?

**Comment by riscy** [comment]
I'd recommend going for separate packages, and the full spec backend would be a great contribution.   You may also find that the front-end ends up being almost trivial (resembling my json example up there), especially if the backend supports good interfaces.

**Comment by riscy** [comment]
Let me know how this is going -- does it make sense to close this PR during this revamp?

**Comment by amodelbello** [comment]
It's going. I haven't been able to devote as much time to it as I would have liked but I do intend to have something within maybe a couple of months.

After digging into the dotenv repo I realized that the functionality I was attempting here is actually part of the api, so I think a single repo will be better than the two we discussed. 

We can use this PR here for that, or if you don't want this PR just hanging around for a while, you can close this one and I'll just create a new one when it's ready.

**Comment by riscy** [comment]
Re: the single repo, that's just fine.

I don't think we'll gain a lot by leaving this open - we can open a new PR when it's time (and you can refer back to this one if you want, when you do).

I'll close for now, but if you want to check anything with me I'll respond here.

**Pull request closed without merging**
