### PR TITLE
How to remove the dev repo

### PR DESCRIPTION
**Pull request by ShalokShalom**
Here, I add a short description how to remove the 'bleeding edge' repository.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, but I think it's already _fairly_ clear from the docs, and we don't use the term `development repo` to describe the default MELPA archive anyway, so I think this change would lead to additional confusion.

**Comment by ShalokShalom** [comment]
There is absolutely nothing in the README, while the homepage describes it. 
Plus, that one speaks about "bleeding-edge" packages, that in confuses. 
And third, you indeed mention 

>  If you leave the original MELPA server in your package-archives then by default you will get the development versions of packages and not the stable ones, because the development versions are higher.

**Comment by ShalokShalom** [comment]
Ah, you commited a new version of the README. That one looks fine. 😄

**Comment by purcell** [comment]
> Ah, you commited a new version of the README. That one looks fine.

Yep, forgot to mention that in a comment here - thanks for the prod.

**Comment by ShalokShalom** [comment]
prod.? :)

**Comment by milkypostman** [comment]
a poke. like, "thanks for reminding me"

**Comment by ShalokShalom** [comment]
Ah, I see. :)

**Pull request closed without merging**
