### PR TITLE
Add recipe for emacs-webdriver

### PR DESCRIPTION
**Pull request by maurooaranda**
### Brief summary of what the package does

This package is a local end implementation of the WebDriver API, written entirely on Emacs Lisp.
See [https://www.w3.org/TR/webdriver2/](https://www.w3.org/TR/webdriver2/)

It allows to write code in Emacs Lisp for controlling a browser that implements the remote end of the specification.

### Direct link to the package repository

https://gitlab.com/mauroaranda/emacs-webdriver

### Your association with the package

I'm the author and maintainer.

### Relevant communications with the upstream package maintainer

** None needed **

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

- No byte-compile error 🎉 

`webdriver.el` with checkdoc (0.6.2)

```
No issues found
```

`webdriver.el` with package-lint (20230905.629)

```
No issues found.
```

Everything LGTM! :)

**Comment by maurooaranda** [comment]
> I'm helping MELPA maintainers a little bit here.
> 
>     * No byte-compile error 🎉
> 
> 
> `webdriver.el` with checkdoc (0.6.2)
> 
> ```
> No issues found
> ```
> 
> `webdriver.el` with package-lint (20230905.629)
> 
> ```
> No issues found.
> ```
> 
> Everything LGTM! :)

Thanks for taking the time to go through these checks.

**Comment by jcs090218** [comment]
> Thanks for taking the time to go through these checks.

👍 I'm only doing the basic tests. `@riscy` will review this and might give you more feedback, etc. :)

**Comment by jcs090218** [comment]
Oh, BTW. You might want to add a LICENSE file in your repository. See: https://github.com/licensee/licensee

**Comment by riscy** [comment]
Thanks - looks like a solid implementation.  Merging!

**Comment by maurooaranda** [comment]
Thanks!

**Pull request merged**
