### PR TITLE
Add recipe for window-tool-bar

### PR DESCRIPTION
**Pull request by chaosemer**
### Brief summary of what the package does

Add tool bars to windows. Keep tool bars clean and useful for experienced Emacs users. 

### Direct link to the package repository

https://github.com/chaosemer/window-tool-bar

### Your association with the package

Author, maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this - looks useful, although a fairly radical idea to actually use the Emacs tool bars. :)  Quick first pass --

`window-tool-bar.el` with byte-compile using Emacs 29.1:
```
window-tool-bar.el:332:21: Warning: reference to free variable `tool-bar-map'
```
This looks like a missing `(require 'tool-bar)` is all that's wrong here.

**Comment by chaosemer** [comment]
Thanks, fixed on HEAD.

Sorry for missing this, it wasn't an issue locally for me. `tool-bar` must get conditionally preloaded based on compilation flags, which is why I missed that.

> a fairly radical idea to actually use the Emacs tool bars. :) 

Yeah, I know. :)

**Comment by chaosemer** [comment]
**Please hold off on merging this PR.** I have left this open to get any additional feedback you may provide.

When I mentioned this in passing in a [bug report to the core Emacs developers](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=68334), they were interested in taking this package into core. I could see that resulting in the name changing and i do not know how MELPA handles package renames.

My ideal world would be for this package to be in core Emacs and also have a more frequent update schedule via MELPA / Gnu ELPA. If you have advice on how to do so, please share.

**Comment by riscy** [comment]
I'll mark this awaiting-upstream until we know what to do.  In the meantime, here's the only bytecomp issue --

`window-tool-bar.el` with byte-compile using Emacs 29.1:
```
window-tool-bar.el:389:8: Warning: reference to free variable `window-tool-bar--allow-images'
```

**Comment by riscy** [comment]
Friendly ping :)

**Comment by chaosemer** [comment]
Sorry for the delay.

window-tool-bar is on GNU Elpa, so I don't think it needs to also be on MELPA.. Closing this.

**Pull request closed without merging**
