### PR TITLE
Add fortune-mode recipe

### PR DESCRIPTION
**Pull request by lassik**
### Brief summary of what the package does

This major mode helps you edit collections of fortune cookies. The file format is the one used by the Unix `fortune` program. A line with a single '%' separates each pair of adjacent fortunes.

### Direct link to the package repository

https://github.com/lassik/emacs-fortune-mode

### Your association with the package

Just wrote it

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by lassik** [comment]
Tested that it works in the minimum supported Emacs version using the Docker container `silex/emacs:24`.

**Comment by riscy** [comment]
Thanks for this!

> Should I change the dependency

I think this is fine, and package-lint also has some checks to make sure that 24.1 will work given the functions you're using.  

I notice there is an existing `fortune-mode` package at https://github.com/emacsmirror/fortune-mode which I believe is hosted here: https://www.emacswiki.org/emacs/fortune-mode.el.  It looks like it has the same aim, so maybe there is an opportunity to join forces and/or take over maintainership of the existing package?

**Comment by lassik** [comment]
> Thanks for this!

Thank you for the fast turnaround on the review.

> package-lint also has some checks to make sure that 24.1 will work given the functions you're using.

Fair enough. package-lint is happy with the code.

> I notice there is an existing `fortune-mode` package at https://github.com/emacsmirror/fortune-mode which I believe is hosted here: https://www.emacswiki.org/emacs/fortune-mode.el.

Sorry, I wasn't aware that this code existed.

Indeed, the .el file in that emacsmirror package is character-for-character identical to the code on the EmacsWiki page. MELPA has no prior PRs dealing with a `fortune-mode`; I wonder how the code got into emacsmirror. Does it mirror EmacsWiki in addition to MELPA?

> It looks like it has the same aim, so maybe there is an opportunity to join forces and/or take over maintainership of the existing package?

Recent versions of Emacs bundle a `fortune.el` file. (by Holger Schauer, copyright 1999, 2001-2021). It deals with running the `fortune` external program, and can also append fortune cookies to collection files, but does not have a major mode for editing collection files.

The `fortune-mode.el` from EmacsWiki is also 20 years old code, but from a different author, and seems to combine functionality of `fortune.el` and my package.

I'll do a review of `fortune.el` and the two `fortune-mode.el`, and merge everything not in `fortune.el` into my `fortune-mode.el` in such a way that it relies on the functionality in `fortune.el`. Ideally all of this stuff could be merged into `fortune.el` and bundled with Emacs, but I'm under the impression that the submission process is somewhat difficult.

**Comment by lassik** [comment]
Merged the code from EmacsWiki. [Details in this commit message.](https://github.com/lassik/emacs-fortune-mode/commit/8f00dfd30800bf41390cc8200a0dad837c76689e)

**Comment by riscy** [comment]
Thanks so much for that!  I think this is fine to merge, but I'll ping @tarsius for suggestions on what we might want to do about the package name in this case.  I think it is better if your package didn't have the same name as the Emacs wiki one -- but if we can think of your package as a spiritual continuation of the Emacs wiki one (maybe by involving the original author here? although I'm having trouble finding up-to-date contact info) then I believe it would be fine to keep the name.

**Comment by tarsius** [comment]
> I'll do a review of `fortune.el` and the two `fortune-mode.el`, and merge everything not in `fortune.el` into my `fortune-mode.el` in such a way that it relies on the functionality in `fortune.el`.

Exemplary :+1: :grin: 

> Ideally all of this stuff could be merged into `fortune.el` and bundled with Emacs, but I'm under the impression that the submission process is somewhat difficult.

You need to sign the copyright papers and send the changes by mail. I recommend you do the legal stuff now, so that things are ready once you have another contribution, that needs to be merged into Emacs -- urgently :grinning:. The patch submission is doable too.

So yeah, I think it would be best if your code were merged into `fortune.el` but if you don't want to do that or not yet, then that's fine by me too.

**Comment by riscy** [comment]
@lassik thoughts on this?  I think we can go ahead and bring this into MELPA in the meantime, but I agree with @tarsius above on the potential best case scenario.

**Comment by riscy** [comment]
Friendly ping. :)

**Pull request closed without merging**
