### PR TITLE
Add recipe for eyebrowse-restore

### PR DESCRIPTION
**Pull request by FrostyX**
MELPA package requested here https://github.com/FrostyX/eyebrowse-restore/issues/4

### Brief summary of what the package does

This package periodically saves all Eyebrowse window configurations for all Emacs frames. Apart from that, a window configuration is saved when closing a frame or manually using `M-x eyebrowse-restore-save-all`. After an Emacs crash, a user can run `M-x eyebrowse-restore` to restore the Eyebrowse window configurations from a backup of their choice.

### Direct link to the package repository

See https://github.com/FrostyX/eyebrowse-restore/

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by FrostyX** [comment]
My apologies, this is my first MELPA package, and I am not sure about these two things.

> I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback

I did use the `M-x package-lint-current-buffer` command and it returned only one warning

    1 issue found:
    9:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.

I checked the variable and the list of standard keywords is very limited, bordering on useless for this package. Should I keep the current keywords or update them to only the standard keywords?

> My elisp byte-compiles cleanly

It compiles without any errors, the `*Compile-Log*` shows only some warnings.  I've seen similar errors for many other packages, so I am not sure whether they must be fixed or not.

**Comment by FrostyX** [comment]
I think the CI failed for reasons unrelated to this PR.

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/e/emacs/emacs-bin-common_26.3+1-1ubuntu2_amd64.deb  503  Service Unavailable [IP: 52.154.174.208 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by LaurenceWarne** [comment]
> I checked the variable and the list of standard keywords is very limited, bordering on useless for this package. Should I keep the current keywords or update them to only the standard keywords?

Perhaps `convenience` would be appropriate?  `eyebrowse` itself uses it as well: https://depp.brause.cc/eyebrowse/eyebrowse.el.

**Comment by riscy** [comment]
Re: the build, I think some infra not directly related to MELPA was just down.  I reran and it looks good now.

Re: finder-known-keywords, you can use a mix of "standard" keywords and your own keywords.  It's true that finder-known-keywords are very broad -- as long as you have at least one standard keyword situating this package.

In the meantime, here's a quick first pass --

`eyebrowse-restore.el` with byte-compile using Emacs 28.1:
```
eyebrowse-restore.el:39:1: Warning: defcustom for `eyebrowse-restore-dir'
    fails to specify containing group
eyebrowse-restore.el:39:1: Warning: defcustom for `eyebrowse-restore-dir'
    fails to specify containing group
eyebrowse-restore.el:44:1: Warning: defcustom for
    `eyebrowse-restore-save-interval' fails to specify containing group
eyebrowse-restore.el:44:1: Warning: defcustom for
    `eyebrowse-restore-save-interval' fails to specify containing group
eyebrowse-restore.el:48:1: Warning: defcustom for
    `eyebrowse-restore-keep-old-backups' fails to specify containing group
eyebrowse-restore.el:48:1: Warning: defcustom for
    `eyebrowse-restore-keep-old-backups' fails to specify containing group
eyebrowse-restore.el:52:1: Warning: defcustom for
    `eyebrowse-restore-if-only-one' fails to specify containing group
eyebrowse-restore.el:52:1: Warning: defcustom for
    `eyebrowse-restore-if-only-one' fails to specify containing group
eyebrowse-restore.el:66:1: Warning: defcustom for `eyebrowse-restore-mode'
    fails to specify containing group
eyebrowse-restore.el:66:1: Warning: defcustom for `eyebrowse-restore-mode'
    fails to specify containing group
```
You need an `eyebrowse-restore` group defined using something like:
```elisp
(defgroup eyebrowse-restore nil
  "some comment"
  :prefix "eyebrowse-restore-"
  :group '<some parent, maybe eyebrowse's group?>)
```

`eyebrowse-restore.el` with package-lint 20221003.1636:
```
1 issue found:
9:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```
(As above)

`eyebrowse-restore.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- eyebrowse-restore.el#L156: There is no need to quote lambdas (neither #' nor ')
```

Package and license:
- Add a matching LICENSE file to the repository

**Comment by FrostyX** [comment]
Thank you very much @LaurenceWarne and @riscy for the review.
I made all the requested changes. The compile log doesn't  show any errors now.

**Comment by riscy** [comment]
Thanks for the changes.  Re: the license you added, it appears to be GPL 2.0 and you should prefer GPL 3.0+ for [reasons explained here](https://github.com/johannes-mueller/company-wordfreq.el/issues/6). 

Less importantly (but still fixable) is a checkdoc nag:

`eyebrowse-restore.el` with checkdoc 0.6.2:
```
eyebrowse-restore.el:40: First sentence should end with punctuation
```

**Comment by FrostyX** [comment]
Good catch @riscy, thank you. I fixed both.

**Comment by riscy** [comment]
Looks good!

On one last look, I might suggest dropping the dependency on `s` -- `s` is an awesome package, but you're only making use of `s-replace` which is a very thin wrapper around `(replace-regexp-in-string (regexp-quote old) new s t t)`.  (Believe it or not, my current Emacs config doesn't require `s`.)

That's non-blocking, though.  Welcome to MELPA. :)

**Pull request merged**
