### PR TITLE
Add recipe for eask-mode

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

major mode for editing Eask files

### Direct link to the package repository

https://github.com/emacs-eask/eask-mode

### Your association with the package

The author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.

Technically there is a namespace conflict between this package `eask-mode`, and your earlier package `eask`.  This is because the convention is that every `x-mode` package implicitly claims the `x` namespace (e.g. `js-mode` implicitly claims `js-` and `js--` as valid prefixes).

I'd recommend we do one of the following (in order of preference, but with flexibility):

- Rename your earlier package to `eask-lib` and fix all of the prefixes - it is, as my understanding goes, library code for a node.js application you developed
- Leave this package named as it is, and just accept this namespace violation.  I don't mind making an exception in this case because you own both packages, but this is not something I want to make a habit of doing

Let me know which you decide -

**Comment by jcs090218** [comment]
> Technically there is a namespace conflict between this package eask-mode, and your earlier package eask. This is because the convention is that every x-mode package implicitly claims the x namespace (e.g. js-mode implicitly claims js- and js-- as valid prefixes).

This is new knowledge to me. Didn't know this will cause a namespace conflict. 😓 

> * Leave this package named as it is, and just accept this namespace violation. I don't mind making an exception in this case because you own both packages, but this is not something I want to make a habit of doing

Let's go for this method for now. I could rename `eask` to `eask-lib` at any time if I changed my mind. 🤔

**Comment by riscy** [comment]
Gotcha, we can go with that.

Apologies for the delay since I'm not sure how this snuck through, but I'm seeing this minor package-lint --

`eask-mode.el` with package-lint 20230905.629:
```
1 issue found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
```

**Comment by jcs090218** [comment]
Fixed! :)

**Comment by riscy** [comment]
Thanks - merging!

**Pull request merged**
