### PR TITLE
Adding helm-taskswitch

### PR DESCRIPTION
**Pull request by bdc34**
### Brief summary of what the package does

Provides an X window and buffer switching with helm.

### Direct link to the package repository

https://github.com/bdc34/helm-taskswitch

### Your association with the package

I am the maintainer. This is my first MELPA package. 

### Relevant communications with the upstream package maintainer

Maintainer would like package on MELPA.

### Checklist

Please confirm with `x`:

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [ x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x] My elisp byte-compiles cleanly
- [ x] `M-x checkdoc` is happy with my docstrings (except warning about first line summary but I have lexical-binding there. )
- [ x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by bdc34** [comment]
Thanks for your help. I've made these changes here: [Commit](https://github.com/bdc34/helm-taskswitch/commit/25e8bf2fcdce2afc3c5197399f5192246ff244f1)

**Comment by purcell** [comment]
>     * I think the magic `lexical-binding` comment would also work on the second line

Nope, that should always go on the first line, odd though that is -- there was at least one Emacs version which didn't correctly apply it if it was not on the first line.

**Comment by bdc34** [comment]
Thanks, I've moved the lexical-binding to the first line. [Commit](https://github.com/bdc34/helm-taskswitch/commit/e74ae4a8e4e037d8b719e287da6f08fcae156b9f)

**Comment by purcell** [comment]
I took a closer look and sent you a fix in https://github.com/bdc34/helm-taskswitch/pull/1, but I _think_ I can go ahead and merge now anyway. Welcome to MELPA! :tada:

P.S. You should `:inherit` built-in faces where possible instead of choosing your own colours. This allows your package to look reasonable in various themes.

**Pull request merged**
