### PR TITLE
new package: consult-notmuch

### PR DESCRIPTION
**Pull request by jaor**
### Brief summary of what the package does

Perform notmuch queries using consult autocompletion.

### Direct link to the package repository

https://codeberg.org/jao/consult-notmuch

### Your association with the package

Author and maintainer

### Checklist

Please confirm with `x`:

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x ] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x] My elisp byte-compiles cleanly
- [x ] `M-x checkdoc` is happy with my docstrings
- [ x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, taking a very quick look -

- In your recipe you specify `:branch "main"` but if this is your default branch MELPA will handle it.  And we prefer that you don't specify it, because it gives you the freedom in the future to change the branch's name without another PR
- I double-checked the `notmuch` code and `:group 'Notmuch` should be written `:group 'notmuch`
- `consult--read` is by convention a private function and not part of the public interface of consult, so it seems the author did not expect you to use it in this way.  I wouldn't say this is strictly a blocker, but it's a shaky linchpin to rely on.  I'd recommend asking the consult author to make this a public-facing function.
- Also not a blocker, and this is obviously a false positive -- package-lint (using version 20210127.158):
```
1 issue found:
89:12: error: `authors' was removed in Emacs version 25.1.
```
but I think there's a lot of value in having a fully green package-lint.  For example if _actual_ issues arise, you won't have gotten used to seeing errors.  Since this is just a locally scoped variable, maybe it's worth renaming to `authors_` (I'm borrowing a Python convention here) or `creators` or similar.

**Comment by jaor** [comment]
On Sat, Feb 13 2021, Chris Rayner wrote:

> Thanks for this, taking a very quick look -
>
>   • In your recipe you specify :branch "main" but if this is your
>   default branch MELPA will handle it. And we prefer that you don't
>   specify it, because it gives you the freedom in the future to change
>   the branch's name without another PR

fixed (but you might perhaps want to clarify that in the melpa readme,
where it seems to indicate that if it's not 'main' one should do add
:branch--perhaps i didn't read carefully enough, though).

>   • I double-checked the notmuch code and :group 'Notmuch should be
>   written :group 'notmuch

oops, sorry about that. fixed.

>   • consult--read is by convention a private function and not part of
>   the public interface of consult, so it seems the author did not
>   expect you to use it in this way. I wouldn't say this is strictly a
>   blocker, but it's a shaky linchpin to rely on. I'd recommend asking
>   the consult author to make this a public-facing function.

i know it's not conventional, but consult--read is the sanctioned way of
writing these interfaces in consult.  the author and i have discussed
extensively this an other issues.  i'll forward him your comments, but i
wouldn't hold my breadth :) (there are other similar functions that are
part of that API using the same convention, i even wrote a blog post on
how to use
them--https://jao.io/blog/2021-01-21-consulting-spotify-in-a-better-way.html)

>   • Also not a blocker, and this is obviously a false positive --
>   package-lint (using version 20210127.158):
>
> 1 issue found:
> 89:12: error: `authors' was removed in Emacs version 25.1.
>
> but I think there's a lot of value in having a fully green
> package-lint. For example if actual issues arise, you won't have
> gotten used to seeing errors. Since this is just a locally scoped
> variable, maybe it's worth renaming to authors_ (I'm borrowing a
> Python convention here) or creators or similar.

i just renamed it to something else.

thanks a lot for your careful review.  let me know if there's anything
else.

**Comment by riscy** [comment]
Looks great to me, thanks!

**Comment by jaor** [comment]
many thanks!

**Pull request merged**
