### PR TITLE
Added recipe ivy-todo

### PR DESCRIPTION
**Pull request by Kungsgeten**
### Brief summary of what the package does

`ivy-todo` lets you manage org-mode TODO lists using [ivy](https://github.com/abo-abo/swiper). The primary use case is to manage TODO lists of the project you're currently working on (ivy-todo will guess using [projectile](https://github.com/bbatsov/projectile) or vc.el).

A somewhat similar package is [org-projectile](https://github.com/IvanMalison/org-projectile) but `ivy-todo` isn't bound to projectile and you do not necessary need to manage project TODOs with it. The workflow is also different compared to `org-projectile`.

### Direct link to the package repository

https://github.com/Kungsgeten/ivy-todo

### Your association with the package

I'm the author and maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

Sorry, I haven't used the last one. I've submitted packages to Melpa before though, so I hope it'll work.

### CODE REVIEW

**Comment by Kungsgeten** [comment]
Hi! Sorry for disturbing, but it's been a while and I haven't heard anything regarding this pull request. Perhaps I'm spoiled because my previous pull requests has been handled quickly :) @purcell @syohex

**Comment by syohex** [comment]
- Emacs has `vc.el` since very old versions and `(require 'vc nil t)` never fails. But `vc-root-dir` was introduced at Emacs 25. This package requires Emacs 24.3 or higher versions but 24.3 and 24.4 and 24.5 does not have `vc-root-dir` and then exception is thrown on such Emacs.

**Comment by Kungsgeten** [comment]
Good catch! I guess this commit should fix it: https://github.com/Kungsgeten/ivy-todo/commit/01b8e99e764ba50f75d8e07a5c8267bca5dbcdca

**Comment by purcell** [comment]
This is still going to explode for users with neither a recent Emacs or projectile. 

The right way to handle this IMO is to provide a `defcustom` that defines the function for finding the project root, then fail at runtime if it is unset. By all means set the default value for that defcustom to either projectile-project-root or vc-root if you find they are defined at the time your library is loaded.

**Comment by Kungsgeten** [comment]
@purcell It might be a good idea to provide a `defcustom` like you suggest, in order to optimize `ivy-todo--guess-headline-name` a bit. That function is usually run once per file though, and isn't particullary slow. It will not explode Emacs: If neither `projectile`, `find-file-in-project` or `vc` cond clause triggers it will return `nil` and the user just enters the TODO list name manually (see lines 85--86). `ivy-todo` doesn't have to be used in projects, it can manage general TODO lists.

**Comment by purcell** [comment]
I'll go ahead and merge, but I'd definitely suggest moving to configuration rather than run-time tests.

Thanks!

**Pull request merged**
