### PR TITLE
Add context-transient (formerly repo-transient)

### PR DESCRIPTION
**Pull request by licht1stein**
### context-transient
Easily create repo-specific transient menus for Emacs.

### Direct link to the package repository

https://github.com/licht1stein/context-transient.el

### Your association with the package

Maintainer

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
This is an interesting idea, but I feel like it could be generalized.
Why not a command which runs a hook until success to determine which transient to display?
This would allow for contextual transients of all manner.

**Comment by licht1stein** [comment]
Sounds cool, but I would need a hint on how it should work. Can you suggest and I'll play with it?

**Comment by progfolio** [comment]
> Can you suggest and I'll play with it?

Sure.

```emacs-lisp
(require 'transient)
(defgroup contextual-transient nil "Contextual transient menus."
  :group 'convenience)

(defcustom contextual-transient-hook nil
  "Hook run with `contextual-transient'.
Each element must be a function which returns nil (to be skipped),
or a symbol naming a `contextual-transient' menu.
Functions are run in order until the first non-nil result is returned."
  :type 'hook)

(defun contextual-transient ()
  "Run `contextual-transient-hook' until success."
  (interactive)
  (if-let ((transient (run-hook-with-args-until-success 'contextual-transient-hook)))
      (funcall transient)
    (user-error "No transient found for current context")))

;;@FIX: Don't eval NAME arg twice.
;;@FIX: Push named functions to hook.
;;@MAYBE: Namespace defined menus.
;;@MAYBE: Don't require keyword arg for menu definition.
(cl-defmacro contextual-transient-define (name &key doc context menu)
  "Define a transient MENU with NAME with DOC and DEFINITION to run in CONTEXT."
  (declare (indent 1))
  `(progn (transient-define-prefix ,name () ,doc ,menu)
          (add-hook 'contextual-transient-hook (lambda () (when ,(macroexp-progn (list context)) ',name)))))
```

Then, we can define a contextual transient which will only work in the \*scratch\* buffer like so:

```emacs-lisp
(contextual-transient-define itch
  :doc "Itch a *scratch*"
  :context (equal (buffer-name) "*scratch*")
  :menu
  [["Test" ("i" "Itch *scratch*" (lambda () (interactive) (message "Itched")))]])
```

Does that help?

**Comment by licht1stein** [comment]
@progfolio wow thanks! Let me read the code and play with it and I'll get back here with either questions or improved package.

**Comment by licht1stein** [comment]
@progfolio this is amazing. I have redone the repo, please take a look. And I guess I need to fix the todos that you left, but I don't know how yet :)

**Comment by progfolio** [comment]
> @progfolio this is amazing. I have redone the repo, please take a look. And I guess I need to fix the todos that you left, but I don't know how yet :)

Cool. My suggestion would be to work on it a bit until it's in solid shape and then submit it to MELPA.

**Comment by licht1stein** [comment]
@progfolio thank you! I'll tag you once I tested it a bit, thank you again!

**Comment by licht1stein** [comment]
@progfolio I have also added `:repo` and `:buffer` keys as samples of often used contexts

**Comment by riscy** [comment]
@progfolio Thank you, as always, for your insightful comments.  Hugely appreciated.

@licht1stein If your code is ready for it, here's a quick pass with the linters --

`context-transient.el` with byte-compile using Emacs 29.3:
```
context-transient.el:121:15: Warning: Stray `declare' form: (declare (indent 1))
In context-transient-require-defclj:
context-transient.el:139:2: Warning: docstring wider than 80 characters
In end of data:
context-transient.el:99:33: Warning: the function `project-name' is not known to be defined.
```

`context-transient.el` with checkdoc 0.6.2 (fix *within reason*):
```
context-transient.el:94: Argument `project' should appear (as PROJECT) in the doc string
context-transient.el:140: First sentence should end with punctuation
```

`context-transient.el` with package-lint 20240330.1458:
```
1 issue found:
141:0: error: "defclj" doesn't start with package's prefix "context-transient".
```

**Comment by licht1stein** [comment]
@riscy thank you so much! I think I fixed all of the comments, except the last one on `defclj`. This is not defined within the library, a user has to explicityly run `(context-transient-require-defclj)` in their code to define and use defclj, so it shouldn't be an issue, but I will totally trust your judgement on this.

**Comment by licht1stein** [comment]
Fixed all of the comments + added melpazoid to CI

**Comment by riscy** [comment]
@progfolio while I've got your attention here (I hope), I tried to email you at protonmail to no avail.  Can you reach out and let me know if there's a better way to get in touch with you?

@licht1stein Solid, and thank you for accommodating everything.  I'll merge this now.

**Comment by progfolio** [comment]
> @progfolio while I've got your attention here (I hope), I tried to email you at protonmail to no avail.  Can you reach out and let me know if there's a better way to get in touch with you?

Sorry about that!
nv@parenthetic.dev should work.

**Comment by licht1stein** [comment]
Great, thanks!

**Pull request merged**
