### PR TITLE
adding recipe for mermaid-mode

### PR DESCRIPTION
**Pull request by abrochard**
### Brief summary of what the package does

Major mode for working on mermaid graph files.

### Direct link to the package repository

https://github.com/abrochard/mermaid-mode

### Your association with the package

maintainer?

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Some notes:
- Use `defconst` to introduce `mermaid-highlights`, [not `setq`](https://github.com/abrochard/mermaid-mode/blob/b9782e75ab9ab1d6a70bd944213c396f7740bf79/mermaid-mode.el#L60).
- Consider converting the two `defvar`s into `defcustom`s, with a containing `defgroup`.
- There's no guarantee that `(buffer-file-name)` returns non-nil, so [this code](https://github.com/abrochard/mermaid-mode/blob/b9782e75ab9ab1d6a70bd944213c396f7740bf79/mermaid-mode.el#L97) will be unreliable. Where possible, don't expect that every buffer in your major mode is associated with a file.
- [This line](https://github.com/abrochard/mermaid-mode/blob/b9782e75ab9ab1d6a70bd944213c396f7740bf79/mermaid-mode.el#L123) is generated for you by `define-derived-mode`, so you should delete it.
- `mermaid-highlights` should be called `mermaid-font-lock-keywords`, which is much more conventional.
- Don't call "open" [here](https://github.com/abrochard/mermaid-mode/blob/b9782e75ab9ab1d6a70bd944213c396f7740bf79/mermaid-mode.el#L105) - instead, use `browse-url-default-browser`. ("open" is only available on MacOS.) Same applies to `mermaid-open-doc`.

Hope that helps.

**Comment by purcell** [comment]
Super slow (sorry) but merged now. Thanks!

**Comment by abrochard** [comment]
No problem! Thank you very much! Onto the next one.

**Comment by purcell** [comment]
> Onto the next one.

Give me some time to keep up... ;-)

**Pull request merged**
