### PR TITLE
Add flymake-joker recipe

### PR DESCRIPTION
**Pull request by beetleman**
### Brief summary of what the package does

This package adds Clojure(Script) syntax checker (via Joker) to flycheck.

### Direct link to the package repository

https://github.com/beetleman/flymake-joker

### Your association with the package

I'm maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Great thanks!  This looks about ready to go.  Some quick things I see:

- flymake-joker.el#L90: It is beneficial to sharp-quote hooks; use `#'`
- flymake-joker.el#L91: It is beneficial to sharp-quote hooks; use `#'`
- flymake-joker.el#L96: It is beneficial to sharp-quote hooks; use `#'`
- flymake-joker.el#L88: Consider `unless ...` instead of `when (not ...)`

**Comment by beetleman** [comment]
I will apply your suggestions today.

**Comment by riscy** [comment]
Have you had a chance to look at http://melpa.org/#/flycheck-joker ?  I feel like there are significant similarities, even up to your summary line.

Minor, but I just noticed:
- `raported` -> `reported`
- `keybord` -> `keyboard`
- `cheker` (in a few places) -> `checker`

**Comment by beetleman** [comment]
Apparently I forget to mention that i use flycheck-joker as base (I was in hurry and my plugin and flycheck-joker use the same tool but different emacs backend), but flymake is build in emacs so i decide to write integration with it.

**Comment by riscy** [comment]
Okay, that makes sense!  I think you will want to change your summary line, though: `Add Clojure syntax checker (via Joker) to flycheck` -- since you're not using flycheck.  Your commentary also mentions ";; This package adds Clojure syntax checker (via Joker) to flycheck."

**Comment by beetleman** [comment]
Tank you for all help and patience @riscy. I fixed all mistakes mentioned by you and also I added information that is based on `candid82/flycheck-joker`.

**Comment by riscy** [comment]
One last thing I notice which isn't a blocker is in a docstring: "keyboard accepted by flymake" -> "keyword accepted by flymake".  Beyond that this looks good to go.  And, welcome to MELPA!

**Pull request merged**
