### PR TITLE
Added svg-tag-mode recipe

### PR DESCRIPTION
**Pull request by rougier**
### Brief summary of what the package does

Replace arbitrary keywords with SVG tags

### Direct link to the package repository

https://github.com/rougier/svg-tag-mode

### Your association with the package

Author / maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by Compro-Prasad** [comment]
2020-11-14-095739_1366x768_scrot
How make it work properly?

**Comment by rougier** [comment]
You might need to adjust the y offset depending on the font used. What is your font  family ? Can you try with Roboto Mono?

**Comment by Compro-Prasad** [comment]
2020-11-16-091544_1366x768_scrot

Which offset you are talking about?

**Comment by rougier** [comment]
This vertical offset yes. Can you open an issue on the repository?

**Comment by riscy** [comment]
Looks very cool.  Quick first pass.

### svg-tag-mode.el ###

byte-compile (using Emacs 27.1):
```
svg-tag-mode.el:126:1:Warning: Unused lexical variable `box'
```
You can remove this, or if you want to keep it you can rename the variable to `_box` and the compiler will know what's going on.

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- svg-tag-mode.el#L196: It's safer to sharp-quote function names; use `#'`
- svg-tag-mode.el#L199: It's safer to sharp-quote function names; use `#'`
- svg-tag-mode.el#L208: It's safer to sharp-quote function names; use `#'`
- svg-tag-mode.el#L25: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading svg-tag-mode.el
svg-tag-mode.el:Error: Emacs 27.1 errored during load
Done.
```
Looks like this errored because I tried to load this library in an `emacs -nw` instance in which the :height of the default face is 1, yielding an invalid face with a height of 1 - 20 = -19 for `svg-tag-default-face`.  This could keep people from starting Emacs in the terminal, so probably you want to make the package robust to this.

### Package ###

- Prefer the default recipe or use `:defaults`, if possible: you can ideally move the example files into an `examples` directory, or you can use `(:defaults (:exclude ...))`.  This will give you room to grow in the future without needing another PR.

**Comment by rougier** [comment]
Thanks for the review, I'm making fixes:

- [x] Unused lexical variable `box'
- [x] svg-tag-mode.el#L196: It's safer to sharp-quote function names; use #'
- [x] svg-tag-mode.el#L199: It's safer to sharp-quote function names; use #'
- [x] svg-tag-mode.el#L208: It's safer to sharp-quote function names; use #'
- [x] svg-tag-mode.el#L25: Prefer https over http if possible (why?)
- [ ] svg-tag-mode.el:Error: Emacs 27.1 errored during load
- [ ] default recipe

**Comment by rougier** [comment]
I think I've fixed everything. By the way what is your linter that warns about sharpquote?

**Comment by riscy** [comment]
That's a check that's part of [these](https://github.com/riscy/melpazoid) scripts.

**Comment by riscy** [comment]
This looks great -- one last nag from the byte-compiler:

byte-compile (using Emacs 27.1):
```
svg-tag-mode.el:225:1:Warning: the function `font-lock-extra-managed-props' is
    not known to be defined.
```

I think the sharp-quote here is to blame -- `font-lock-extra-managed-props` is not a function so shouldn't have a `#'` in front of it.

Looks like a quick merge after that.

**Comment by rougier** [comment]
Thanks, fixed.

**Comment by riscy** [comment]
Thanks!  Welcome to MELPA. :)

**Pull request merged**
