### PR TITLE
Add recipe for org-transclusion-http

### PR DESCRIPTION
**Pull request by josephmturner**
### Brief summary of what the package does

Transclude content over HTTP in Org mode with [org-transclusion](https://nobiot.github.io/org-transclusion/)!

### Direct link to the package repository

https://git.sr.ht/~ushin/org-transclusion-http

### Your association with the package

Author, maintainer.

### Relevant communications with the upstream package maintainer

***None needed***

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`org-transclusion-http.el` with byte-compile using Emacs 29.3:
```
org-transclusion-http.el:69:4: Error: url is not a struct name
```

**Comment by josephmturner** [comment]
Thanks, @riscy!  Fixed on `master`.

@alphapapa, do you know why `makem` didn't catch this?

**Comment by alphapapa** [comment]
> @alphapapa, do you know why `makem` didn't catch this?

As best I can tell, it's because `makem.sh` loads the `package` library, which loads `url`.

So as long as one is developing a library to be installed with `package`, I guess it should be no problem for actual users.  If a library were compiled without having loaded `package`, and used a library loaded by `package`, but not explicitly loaded by the library in question, then I suppose one might get a warning or compilation failure, like the one here.

I suppose it would be possible to modify `makem.sh` to compile libraries without having loaded `package`, but since it uses `package` to install the dependency packages and add their directories to the `load-path`, that would seem to require reimplementation of some what `package-initialize` does.

Maybe we could run Emacs with `package-initialize` just to output the `load-path`, and then re-run Emacs with that `load-path`, without calling `package-initialize`.  I don't know if it would be worth it, but maybe it would be more correct that way.  I'm curious about how Melpazoid solves this.

**Comment by josephmturner** [comment]
Thanks @alphapapa for the explanation and the fix!

**Comment by riscy** [comment]
> I'm curious about how Melpazoid solves this.

I'm not 100% happy with the solution but melpazoid painstakingly avoids importing anything (including `package`) before running the byte-compile check.  I'm sure for the vast majority of cases we can assume of users will have `package` brought in.

Thanks @josephmturner for this - merging now.

**Comment by josephmturner** [comment]
Thank you @riscy!!

**Pull request merged**
