### PR TITLE
Recipe for shellhist

### PR DESCRIPTION
**Pull request by NicholasBHubbard**
### Brief summary of what the package does

Provide a configurable command input history for `M-x shell`.

### Direct link to the package repository

https://github.com/NicholasBHubbard/shellhist

### Your association with the package

I am the author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`shellhist.el` with byte-compile using Emacs 28.1:
```
shellhist.el:58:44: Warning: reference to free variable `comint-eol-on-send'
shellhist.el:59:48: Warning: reference to free variable
    `comint-use-prompt-regexp'
shellhist.el:63:52: Warning: reference to free variable `comint-get-old-input'
In end of data:
shellhist.el:38:35: Warning: the function `string-blank-p' is not known to be
    defined.
```
It looks like this needs a `require` on `'comint`.    `string-blank-p` also needs a require on `'subr-x`.

**Comment by NicholasBHubbard** [comment]
I updated `shellhist.el` to require comint and subr-x.

However, I was not able to reproduce the byte-compile warnings you pointed out.

When I byte compile `shellhist.el` with `byte-compile-file` it compiles the file fine without any warnings, and my `*Compile-Log*` buffer simply contains the following:
```
Compiling file /home/_73/p/shellhist/shellhist.el at Thu Apr 20 15:01:06 2023
```

**Comment by riscy** [comment]
Thanks - all of the byte-compile warnings were solved by adding those dependencies.

Most likely you're not seeing all of the compilation warnings because you're compiling your code in an instance of Emacs that has already loaded the code, or some past version of it at least.  Using `flycheck` helps with this, or you can restart emacs using `emacs -Q` and try compiling from there.

With the checklist out of the way, I am curious how this --

> functionality for saving the input history in M-x shell

compares to `#'comint-write-input-ring` and `#'comint-read-input-ring` which appear to be for exactly the same purpose?  (Correct me if I'm wrong.)  If there *is* a distinction to be made, that would be worth expanding your `;;; Commentary` with.

**Comment by NicholasBHubbard** [comment]
I updated the `;;; commentary` as it was vague and incomplete.

`#'comint-write-input-ring` and `#'comint-read-input-ring` are used for loading/storing the `comint-input-ring` from/to a file.

While shellhist does save the shell history to a file so it can persist across sessions, it also does more. Everytime the user enters a input command into `M-x shell`, that input is run through the filters in `shellhist-filters`, which is a list of strings and functions. Strings in this list are interpreted as regexs, such that if the shell input matches one of the regexs then it is not added to the history. The function filters in `shellhist-filters` are all applied to the input command, and if any of them return non-nil then the input is not added to the history. These filters are useful for keeping garbage out of the history like plain "cd" and "ls" commands, blank entries, etc. Shellhist also prevents duplicates from entering the history (by deleting the old duplicate(s) and keeping the new one).

It is important to note that the shellhist history is global (not buffer-local) which means that all `M-x shell` buffers share the history. Comints `comint-input-ring` is buffer-local which is the reason I created shellhist in the first place, as I wanted all my shells to share an input history.

Finally, an interactive command `shellhist-history-search` is provided that lets the user search through the history with `completing-read`, and insert the selection into the `M-x shell` input buffer.

**Comment by riscy** [comment]
Let me make some suggestions below, because you'll potentially be able to share vocabulary and config options with comint -- or you may discover that comint already implements some of these features out of the box.

> Everytime the user enters an input command into M-x shell, that input is run through the filters in shellhist-filters, which is a list of strings and functions.

Have you thought about (re-)using `comint-input-filter`?  I'm sure the rationale for its existence is similar to yours.  And I think a user who has already set up `comint-input-filter` would appreciate not having two unattached systems for filtering input in place.

> Shellhist also prevents duplicates from entering the history

There is a variable `comint-input-ignoredups` that many users will have already configured.  The semantics are slightly different and this is a buffer-local variable, but -- again -- consider that users may struggle having two systems in place for ignoring duplicates.

> an interactive command shellhist-history-search is provided

Check out `#'comint-history-isearch-backward-regexp` and `#'comint-dynamic-list-input-ring` if you haven't.  If you implemented `shellhist--history` as a ring, you could possibly reuse that entire facility with e.g. `(let ((comint-history-ring shellhist--history)) (comint-history-isearch-backward-regexp))` or similar.

> the shellhist history is global (not buffer-local)

I think this is your big differentiator and it should be the headline.  Your summary line is "Keep track of shell history" but maybe "Share shell history across buffers" would give me a better hint about the real feature add here.

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to ping.

**Comment by NicholasBHubbard** [comment]
Closed. I'm working on a larger project that will implement this functionality.

**Pull request closed without merging**
