### PR TITLE
add all recipe

### PR DESCRIPTION
**Pull request by conao3**
### Brief summary of what the package does

Edit all lines matching a given regexp.

### Direct link to the package repository

https://github.com/conao3/all.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

all.el is originally wrote by Per Abrahamsen.
It is registered with elpa, but has had no activity since 2012.
Now that I have taken over the maintenance of the [all-ext](https://melpa.org/#/all-ext) recently registered in MELPA, I would like to register its dependency, all, to MELPA.
I emailed the author, but he hasn't replied yet.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
1.  How does this compare with `M-x occur`'s editing functionality?
2.  You are proposing to fork a package to MELPA which already exists in ELPA, while leaving the old version in ELPA, with the same name in both places?

**Comment by conao3** [comment]
1. While `occur` only looks for the regular expression you enter and displays it in a new buffer, `all` can edit the buffer and propagate the changes back to the buffer in real-time.
2. It is common for ELPA to have older versions and MELPA to provide HEAD under development.
It would be confusing if the maintainer of the ELPA package and I made different changes under different philosophies. I have sent the author an e-mail asking for his intention, but I have not received a reply.

**Comment by alphapapa** [comment]
> 1. While `occur` only looks for the regular expression you enter and displays it in a new buffer, `all` can edit the buffer and propagate the changes back to the buffer in real-time.

`occur` can also edit occurrences and propagate the changes back to the source buffer.

> 2. It is common for ELPA to have older versions and MELPA to provide HEAD under development.
>    It would be confusing if the maintainer of the ELPA package and I made different changes under different philosophies. I have sent the author an e-mail asking for his intention, but I have not received a reply.

It's one thing for a MELPA-only package with many unresolved bugs and pull requests and an AFK maintainer to be built from a new fork, or transferred to a new maintainer with the author's permission (e.g. Syohex's packages).

It's another for an ELPA package to be hijacked and masked by a fork on MELPA because...why, exactly?  

> It would be confusing if the maintainer of the ELPA package and I made different changes under different philosophies

So you want to hijack his package to your own fork, using the same name, imposing your different philosophies on it, and confusing users in the process?  And, likely, surreptitiously causing your fork to be installed over the ELPA version for users who have both MELPA and ELPA configured.  That seems completely inappropriate.

What's stopping you from contributing to it on ELPA?

**Comment by conao3** [comment]
No. I said that I sent an email Per Abrahamsen to prevent users from getting confused by editing each under different intentions.

It doesn't matter where the repository is.
If you think it should be managed by `emacsorphanage`, I would issue that.

**Comment by alphapapa** [comment]
You sent him an email, but you've filed this PR to put your own fork on MELPA under the same name, which would effectively hijack it to your own fork for MELPA users, without waiting for a reply from him.

I ask again: What's stopping you from contributing to it on ELPA?

**Comment by conao3** [comment]
All the necessary information is already shown.
1. I became a maintainer of `all-ext`.
2. MLEPA does not have `all-ext` dependency `all`
3. `all` exists in ELPA but has not been updated since 2012.
4. I sent an email to Per Abrahamsen, who wrote `all`, but I haven't heard back yet.

Abandoned since 2012, `all` did not conform to current MELPA conventions.
By submitting this PR I wanted to receive a code review from MELPA.

> I ask again: What's stopping you from contributing to it on ELPA?

I have not stopped contributing to ELPA.
I just don't want to contribute to ELPA. It's very far from my flow and there are big hurdles to contribute.

**Comment by alphapapa** [comment]
> I sent an email to Per Abrahamsen, who wrote all, but I haven't heard back yet.

So maybe give it a few weeks before trying to take over his package?

> Abandoned since 2012, all did not conform to current MELPA conventions.

I guess many ELPA packages don't.

> By submitting this PR I wanted to receive a code review from MELPA.

No, you said when opening the PR:

> I would like to register its dependency, all, to MELPA.

You didn't post this PR asking for a code review.

> I just don't want to contribute to ELPA. It's very far from my flow and there are big hurdles to contribute.

Your workflow preferences do not justify hijacking a package to MELPA under the same name, masking the ELPA version, and causing users to unknowingly install your version over the ELPA one.

This is wholly inappropriate.

**Comment by tarsius** [comment]
I agree with @alphapapa it would be a rather hostile move to do this.

@conao3 You have two options: contribute to `all` upstream wants you to, or don't. If you choose the latter and that means that you can no longer maintain `all-ext`, then that is fine too, just let me know.

/cc @purcell

**Pull request closed without merging**
