### PR TITLE
Add c-eval recipe

### PR DESCRIPTION
**Pull request by lassik**
### Brief summary of what the package does

By analogy with the Lisp Interaction mode that comes with Emacs, this package provides commands to instantly compile and run C code.

Use `c-eval-scratch` to get a buffer in which to write code. You can also evaluate code from other buffers.

The following commands execute a C program from the current buffer:

* `c-eval-buffer`
* `c-eval-region`

The following commands evaluate C code from the minibuffer:

* `c-eval-expression`
* `c-eval-sizeof`

### Direct link to the package repository

https://github.com/lassik/emacs-c-eval

### Your association with the package

Just wrote it

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by lassik** [comment]
Tested using the Docker container `silex/emacs:24.5` that there are no byte-compiler warnings.

**Comment by riscy** [comment]
Thanks,  everything checks out for me.  One thing that strikes me is there's potentially an opportunity to lean on the builtin `compile` function, which would save you having to create your own sentinel and potentially present users with something more familiar (I found `display-buffer-in-side-window` a little unusual).  E.g.

```elisp

(defun c-eval--raw-string (string)
  "Internal function to evaluate the unadorned C program in STRING."
  (let* ((tmpdir
          (file-name-as-directory
           (or (and c-eval-temp-directory
                    (expand-file-name c-eval-temp-directory))
               (let ((tmp (getenv "TMPDIR")))
                 (and (not (null tmp))
                      (not (equal "" tmp))
                      tmp))
               default-directory))))
    (with-temp-buffer
      (insert string)
      (write-region (point-min) (point-max) (concat tmpdir "c-eval.c")))
    (let ((default-directory tmpdir))
      (compile "cc -o c-eval c-eval.c && ./c-eval"))))
```
(You'll also notice I used a `let` to temporarily switch the `default-directory` to prevent any lasting effects.)

Another benefit is you get some syntax highlighting for "free" when there are warnings/info from the compiler.

Very minor, and you may have just been aiming to be explicit with these, but there's also an opportunity to flatten:
- c-eval.el#L92: This double negation can be collapsed (`not` aliases `null`)
- c-eval.el#L137: This double negation can be collapsed (`not` aliases `null`)

**Comment by lassik** [comment]
Thanks, a thorough review as usual! Using `*Compilation*` is an interesting idea but has two problems:

* Recompiling with the `g` key (or `M-x recompile`) erases the old build log from the buffer, whereas c-eval should accumulate a transcript of the output where new output is appended to the old. In other words, like a Unix shell or Lisp REPL session in "question and answer" style. Any erasing of the log should be done manually by the user.

* It's useful evaluate one-off snippets while running a long compilation process in the background. Is there good support multiple ongoing compilations? (The log erasing issue may still remain.)

`(not (null ...))` is a Lisp idiom for coercing any value into a boolean. Your linter is correct in that it's unnecessary here. I simplified the first case, but the second is really esoteric without it. In Emacs Lisp (and Common Lisp), `nil` is both a symbol and a list; `(and (symbolp x) (not (null x)))` checks for a non-list symbol. Simplifying it to `(and (symbolp x) x)` looks kind of confusing. What to do?

**Comment by lassik** [comment]
I agree that the side window looks a bit weird, especially with all the noise about `process finished`. Maybe it should be displayed in the "other window" (a full-height pane) instead of the "side window" (which for me, actually goes to the bottom of the frame, not the side).

**Comment by purcell** [comment]
> I agree that the side window looks a bit weird, especially with all the noise about `process finished`. Maybe it should be displayed in the "other window" (a full-height pane) instead of the "side window" (which for me, actually goes to the bottom of the frame, not the side).

Generally, trying to figure out where people will want their windows is an impossible. The best advice I have for this is to just use `display-buffer` and then people can use the standard mechanisms like `display-buffer-alist` configuration to customise how buffers pop up in various circumstances.

**Comment by lassik** [comment]
Good advice. I changed the code to use `display-buffer` as you suggest.

**Comment by riscy** [comment]
Yeah, that's a good point.  One last thing is I wonder whether it'd make sense to make the list `"cc" "-o" "c-eval" "c-eval.c"` into a defvar/defcustom so that people could target specific compilers if they wished.  That's not a blocker, though.  Thanks for this, I can really see myself using it.

**Comment by lassik** [comment]
> I wonder whether it'd make sense to make the list `"cc" "-o" "c-eval" "c-eval.c"` into a defvar/defcustom so that people could target specific compilers if they wished.

Yes, users should definitely be able to change the compiler and flags. Many expert C/C++ programmers will likely want to test the same code with multiple compilers in parallel; it's not clear how to make this easy. Perhaps compilers should be named: `gcc`, `clang`, etc. with the possibility of having multiple versions of the same compiler. Please open an issue if/when you need this and we can talk more.

> Thanks for this, I can really see myself using it.

Glad to hear that! Pull requests / feature requests are welcome.

**Pull request merged**
