### PR TITLE
add tmux-mode recipe

### PR DESCRIPTION
**Pull request by nverno**
### Brief summary of what the package does

Major mode for tmux files.

### Direct link to the package repository

https://github.com/nverno/tmux-mode

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

- No byte-compile error 🎉 

`tmux-mode.el` with checkdoc (0.6.2)

```
No issues found.
```

`tmux-mode.el` with package-lint (20230905.629)

```
No issues found.
```

Package and license:

- MIT

**Comment by riscy** [comment]
Thanks for this.  I'm noticing that you have the following boilerplate line:
```
;; This is free and unencumbered software released into the public domain.
```
Also, at least one of your other recent packages has this line but my eyes haven't been catching it.  It strikes me an oversight that your software is both public domain *and* GPL-licensed.  GPL licenses are actually fairly restrictive and rigorous (i.e. as far as I know incompatible with merely "public domain" software).  Your repo itself is also licensed as GPL only, which could create confusion.  I'd recommend you just go with the GPL license, and drop the boilerplate lines about public domain.

I also notice your `auto-mode-alist` entry `(add-to-list 'auto-mode-alist (cons "\\.tmux.*" 'tmux-mode))` can match all sorts of filenames, e.g. `.tmux12345.notes.txt` (for instance).  I'm not a tmux pro, but is the typical tmux config file just called `.tmux.conf`?

**Comment by nverno** [comment]
Thankyou, those were oversights.  I removed that public domain line and fixed the `auto-mode-alist`.
I'll fix the license on the other repos as well.

**Comment by riscy** [comment]
Looks good, thank!

**Pull request merged**
