### PR TITLE
Add ring-mode recipe

### PR DESCRIPTION
**Pull request by thechampagne**
### Brief summary of what the package does

Syntax highlighting for the Ring programming language.

### Direct link to the package repository

https://github.com/thechampagne/ring-mode

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`ring-mode.el` with checkdoc 0.6.2:
```
ring-mode.el:709: Name emacs should appear capitalized as Emacs
ring-mode.el:693: Name emacs should appear capitalized as Emacs
```
(These are really very minor and one is definitely a false positive, but fyi)

`ring-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ring-mode.el#L864: It's safer to sharp-quote function names; use `#'`
```
Also minor.

It looks like you have copied the *entire* GPL license into the front-matter of this package which is unnecessary, but there is a standard license header that you can use [see the SPDX entry](https://spdx.org/licenses/GPL-3.0-or-later.html).  Alternatively you can use a one-liner, e.g. `;; SPDX-License-Identifier: GPL-3.0-or-later`.

I think you've also used function definitions to store values that should probably be constants (q.v. `defconst`) and I'm certain there's a more legible way to handle case insensitivity in `ring-keywords()`; I'd suggest doing a bit more reading, but if you get stuck I can help you find a solution.

**Comment by thechampagne** [comment]
`checkdoc` is much happier now.

`melpazoid` is not mentioned in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

About the license and the code I prefer it like that. I don't think it does matter does it ?

**Comment by riscy** [comment]
melpazoid is just my own personal collection of scripts for checking code.  So it's not an official requirement of MELPA, but I started providing the link to preempt the inevitable "where are you getting these messages from?"

> About the license and the code I prefer it like that. I don't think it does matter does it ?

Read [how to use the GPL](https://www.gnu.org/licenses/gpl-howto.html) especially the section titled "The license notices".  There is a standard form for the license statement -- and it's highly irregular to paste hundreds of lines of legal text the way you are.

I believe my last line of comments wasn't addressed, but feel free to reach out with questions.

**Comment by milkypostman** [comment]
It's really important for the long term maintainability, and viability, of MELPA that we adhere to prescribed licensing practices for GPL.

**Comment by thechampagne** [comment]
👍

**Comment by riscy** [comment]
Just to reiterate:

> I believe my last line of comments wasn't addressed, but feel free to reach out with questions.

Look into, for example, `font-lock-keywords-case-fold-search` (e.g. maybe you want to `(setq-local font-lock-keywords-case-fold-search t)` when activating your major mode).  This makes the font-lock matching case insensitive, which will keep you from having to do this:

```elisp
    "[c\\|C][h\\|H][a\\|A][n\\|N][g\\|G][e\\|E][r\\|R][i\\|I][n\\|N][g\\|G][k\\|K][e\\|E][y\\|Y][w\\|W][o\\|O][r\\|R][d\\|D]\\|"                    ;; changeringkeyword
```
and note rather than have the `\\|` built into the strings to accommodate `(mapconcat 'identity ring-keywords "")` you could just use the `regexp-opt` function.

I also notice you have comment lines like `;;"Ring programming language font lock keywords."` inside a `defconst`, but the last argument of the defconst is where the docstring goes.

**Comment by thechampagne** [comment]
It's not working.
```elisp
;;;###autoload
(define-derived-mode ring-mode prog-mode "Ring"
  "A major mode for the Ring programming language."
  :syntax-table ring-mode-syntax-table
  (setq-local font-lock-keywords-case-fold-search t)
  (setq-local font-lock-defaults '(ring-font-lock-keywords)))
```

**Comment by riscy** [comment]
My apologies, the docs for that variable state:
```elisp
This is set via the function ‘font-lock-set-defaults’, based on
the CASE-FOLD argument of ‘font-lock-defaults’.
```
So here is a minimal working example:
```elisp
(defconst ring-font-lock-keywords
  (list
   '("\\<true\\>"  . font-lock-constant-face)
   '("\\<false\\>" . font-lock-constant-face)))

;;;###autoload
(define-derived-mode ring-mode prog-mode "Ring"
  "A major mode for the Ring programming language."
  (setq-local font-lock-defaults
              (list 'ring-font-lock-keywords nil 'case-fold)))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.ring\\'" . ring-mode))
```

**Comment by thechampagne** [comment]
It worked for everything. I only want it to work on constants and keywords.

**Comment by riscy** [comment]
You could read the highest-scored answer here: https://emacs.stackexchange.com/questions/8109/how-can-i-build-a-regexp-insensitive-to-case

But that's just one example, and there are other much more maintainable/programmatic ways to do what you're doing.  Since you've opened quite a few recipes about major modes -- which are much appreciated, especially for these niche languages -- I strongly recommend you try to read up more on these patterns.

At least this package lacks borderline essentials like defining `indent-line-function` and setting `comment-start`/`comment-end`.  In the past I've merged major modes that have skipped defining `indent-line-function` (it can be tricky) but I try to recommend to authors that they focus on tackling `indent-line-function` next.

**Comment by riscy** [comment]
Friendly ping :)

I realize this sounds a bit picky, but I don't think what's described above should be too tricky.  I can help with implementation details if you get stuck.  I think adding major modes to the Emacs package world is valuable if we can start with a good base, and theknowledge you gain in this PR would be able to be applied to the 8 other major modes you have open PRs for.

**Comment by thechampagne** [comment]
Unfortunately I haven't found a solution, any help would be appreciated.

**Comment by riscy** [comment]
For instance I'd suggest:
```elisp
(defun ring--font-lock-constants (limit)
  "Match case-insensitive ring constants up to LIMIT."
  (let ((case-fold-search t))
    (re-search-forward
     (rx word-boundary (or "true" "false") word-boundary)
     limit 'no-error)))

(defun ring--font-lock-keywords (limit)
  "Match case-insensitive ring keywords up to LIMIT."
  (let ((case-fold-search t))
    (re-search-forward
     (rx
      word-boundary
      (or
       "again" "and" "but" "bye" "call" "case" "catch" "changeringkeyword"
       "changeringoperator" "class" "def" "do" "done" "else" "elseif" "end"
       "exit" "for" "from" "func" "get" "give" "if" "import" "in" "load"
       "loadsyntax" "loop" "new" "next" "not" "off" "ok" "on" "or" "other"
       "package" "private" "put" "return" "see" "step" "switch" "to" "try"
       "while" "endfunc" "endclass" "endpackage" "endif" "endfor" "endwhile"
       "endswitch" "endtry" "function" "endfunction" "break" "continue")
      word-boundary)
     limit 'no-error)))

(defconst ring-font-lock-keywords
  (list
   `("\\(#.*\\)" . font-lock-comment-face)
   `(ring--font-lock-constants . font-lock-constant-face)
   `(ring--font-lock-keywords  . font-lock-keyword-face)
```
which would let you do away with both:
```elisp
(defconst ring-keywords
  '("[a\\|A][g\\|G][a\\|A][i\\|I][n\\|N]\\|"                                                                                                        ;; again
    "[a\\|A][n\\|N][d\\|D]\\|"                                                                                                                      ;; and
    "[b\\|B][u\\|U][t\\|T]\\|"                                                                                                                      ;; but
    "[b\\|B][y\\|Y][e\\|E]\\|"                                                                                                                      ;; bye
    "[c\\|C][a\\|A][l\\|L][l\\|L]\\|"                                                                                                               ;; call
    "[c\\|C][a\\|A][s\\|S][e\\|E]\\|"                                                                                                               ;; case
    ...
```
and this pattern in `ring-font-lock-keywords`
```
`("\\<\\([T\\|t][R\\|r][U\\|u][E\\|e]\\|[F\\|f][A\\|a][L\\|l][S\\|s][E\\|e]\\)\\>" . font-lock-constant-face)
```
and I would at least define your major mode as:
```elisp
;;;###autoload
(define-derived-mode ring-mode prog-mode "Ring"
  "A major mode for the Ring programming language."
  :syntax-table ring-mode-syntax-table
  (setq-local comment-start "# " comment-start-skip "#+\\s-*")
  (setq-local font-lock-defaults '(ring-font-lock-keywords)))
```
since by adding that very simple `comment-start` line you're enabling users to use `comment-dwim` to add comments to their code, and it costs you virtually no investment effort as a maintainer.

On a quick glance, `indent-line-function` looks nontrivial for this programming language but I'd recommend looking at other languages with similar rules.

**Comment by thechampagne** [comment]
👍

**Comment by riscy** [comment]
I had another look and it looks like you followed up.  Thanks for accommodating -- and welcome to MELPA. :)

**Pull request merged**
