### PR TITLE
Add Easy Frame

### PR DESCRIPTION
**Pull request by onixie**
Easy Frame provides key bindings to manipulate frames easily.

### Brief summary of what the package does

Easy Frame binds arrow keys [+ modifier keys] for various frame placement commands in an X window environment.

### Direct link to the package repository

https://github.com/onixie/easy-fwb

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

A little feedback:

1.  Loading the package shouldn't do `(add-hook 'window-setup-hook 'easy-frame-mode)`.  That is for users to do in their config.
2.  More documentation is needed.  As it is now, users will likely not understand what the package does, and won't bother to find out.

**Comment by purcell** [comment]
Thanks @onixie - this still needs a little more documentation please. I have no idea what this package is for, but I'm sure it's useful. :-)

**Comment by DamienCassou** [comment]
What is the status of this PR?

**Comment by tarsius** [comment]
I am closing this because @onixie has not responded to your suggestions and because I think that these libraries are of limited use to anybody beside their author. In particular I think that the key bindings are too much tailored to the authors preference. Some of the libraries define some commands which could be of use to other users though, provided some documentation is added. I am not against adding this in principal, but that will need some work and so far we got silence instead.

**Pull request closed without merging**
