### PR TITLE
Add recipe for translate-mode

### PR DESCRIPTION
**Pull request by rayw000**
### Brief summary of what the package does

A paragraph-oriented Emacs minor mode for doing article translation jobs. 

### Direct link to the package repository

https://github.com/rayw000/translate-mode

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Very quick first pass --

`translate-mode.el` with byte-compile using Emacs 27.1:
```
translate-mode.el:264:11:Warning: reference to free variable `translate-mode'
In end of data:
translate-mode.el:295:1:Warning: the function `format-prompt' is not known to
    be defined.
```

`translate-mode.el` with checkdoc 0.6.2:
```
translate-mode.el:171: Argument `arg' should appear (as ARG) in the doc string
translate-mode.el:263: Disambiguate master-mode by preceding w/ function,command,variable,option or symbol.
```
I think the one on 263 is ignorable in this case.

`translate-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
- translate-mode.el#L268: It's safer to sharp-quote function names; use `#'`
- translate-mode.el#L7: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- translate-mode.el#L287: Lighter should start with a space
- translate-mode.el#L268: Loading a package should rarely add hooks; this is probably not so bad since you're adding hooks to your own mode, but probably you could just call the function directly

Similarly named:
- translate: https://github.com/emacsattic/translate.git (via emacsmirror)

**Comment by rayw000** [comment]
> translate-mode.el with [melpazoid](https://github.com/riscy/melpazoid):

This awesome workflow helps me a lot. Thank you @riscy !
Now I have fixed all issues `melpazoid` complains. Could you please review it again?

**Comment by riscy** [comment]
Looks like a solid use of master.el.  Thanks again!  I just have some high-level feedback, but I don't think any of it is quite worth blocking on.  So I'm happy to merge this, but please take what follows into consideration --

I had a bit of trouble guessing how this works before I saw the screen recording, I think because I didn't know exactly what a "translation job" was, since that term (translation) is a fairly overloaded computing term.  I'd suggest adding phrasing along the lines of "side-by-side document translation workflow" to your summary line and/or `;;; Commentary`

When you use the term "referring" throughout the code, I think you should use the word "reference" (e.g. instead of "buffer for translation referring" you can say "reference buffer", and instead of "artcle referring buffer" you can say "reference buffer").  By similar reasoning the minor mode might be better called "translate-reference-mode".  And, maybe the word "original" should also be replaced with "reference" throughout the code (to keep the vocabulary of function/variable names small), e.g. `translate-get-reference-paragraph-text-at-point`.

Lastly -- I'm guilty myself of doing this -- but it might be worth hosting your screen recording *outside* of the repo -- otherwise everyone who clones the repository (MELPA, but also people using straight.el) will have to clone the 4.4M gif alongside the source code.

**Comment by rayw000** [comment]
Quite valuable and sweet feedback! As a non-native speaker, I learnt a lot from it. Thank you @riscy 😃

**Pull request merged**
