### PR TITLE
Add evil-lion package

### PR DESCRIPTION
**Pull request by edkolev**
### Brief summary of what the package does

Defines a minor mode (evil-lion-mode) which adds two evil-mode operators `gl` and `gL` for left and right align. Port of [vim-lion](https://github.com/tommcdo/vim-lion)

### Direct link to the package repository

https://github.com/edkolev/evil-lion

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by edkolev** [comment]
There's one byte-compile error, which I'm not sure how to best fix - this new package uses `(align-region)` from emacs' `align.el`. But the `align-region` function has no autoload cookie.

The approach I took is, right before calling:
```
      (when (not (fboundp 'align-region))
        (require 'align))
      (align-region .........)
```

But maybe this is a better appraoch:
```
(autoload 'align-region "align.el")
```

However, the second approach prints an annoying message on first use `uncompressing align.el.gz...done`. That's why I went with the first approach.

**Comment by syohex** [comment]
- Dependency header is insufficient(https://github.com/edkolev/evil-lion/pull/1)
- Why don't you load `align.el` at top level ?

**Comment by edkolev** [comment]
> Why don't you load align.el at top level ?

If possible, I would like to load `align.el` the first time the `gl`/`gL` evil operator is pressed, instead of when `(evil-lion-mode)` is called.

I'll try to split evil-lion.el into two files (evil-lion-core.el and evil-lion.el), maybe this way I'll be able to achieve the desired behaviour.

**Comment by edkolev** [comment]
The byte compile warning is now silenced with `(declare-function align-region "align")` in https://github.com/edkolev/evil-lion/commit/af12db645c50c3e677ed6287265989d745143e59

**Comment by purcell** [comment]
> The byte compile warning is now silenced with (declare-function align-region "align") in edkolev/evil-lion@af12db6

Then now you don't need to `(require 'align-region)` at all. You can drop the `fboundp` conditional wrapper around `declare-function` too.

**Comment by edkolev** [comment]
@purcell thanks - the `fboundp` is now removed https://github.com/edkolev/evil-lion/commit/039c82f5183a01b6e008b1028b48f1ec33f74eff

However, I can't get align.el to be loaded without this:
```
      (when (not (fboundp 'align-region))
        (require 'align))
```

The `align-region` function isn't autoloaded (no autoload cookie in align.el) - maybe this is the reason `declare-function` isn't sufficient to load align.el?

**Comment by purcell** [comment]
Sorry, you're right. But you can use `(autoload 'align-region "align")` instead of `declare-function`. I think it's a little nicer than loading a feature explicitly from inside a function.

In the meantime, I'll go ahead and merge this.

(P.S. `unless` is nicer than `(when (not ...) ...)`)

**Comment by edkolev** [comment]
Thanks!

Also thanks for `unless` :) https://github.com/edkolev/evil-lion/commit/875ca7bde23d6102356675af0e6c27775eb21d17

**Pull request merged**
