### PR TITLE
Add recipe for fish-completion

### PR DESCRIPTION
**Pull request by Ambrevar**
### Brief summary of what the package does

Add fish-based completion to Emacs and allow Eshell to fall back on it.

### Direct link to the package repository

https://github.com/Ambrevar/emacs-fish-completion

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

I am not sure about what the best practice is when it comes to functions setting external global variables, in this case `eshell-default-completion-function`.
Have a look at `fish-completion-eshell-toggle`: I suspect there is a much more idiomatic / cleaner way to do this.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick notes:
- Don't use `%s` to interpolate strings directly into command strings: they might contain quotes etc. Use `shell-quote-argument` to escape them for you first.
- When you've got functions for `fish-completion-eshell-toggle-globally` and `fish-completion-eshell-toggle`, what you really want is a local and a global minor mode. :-)
- No need to mention `Emacs` in the description line of the package: all elisp is for Emacs, so this is redundant.

Hope that helps!

**Comment by Ambrevar** [comment]
1. Fixed, thanks for the catch.
2. I wasn't sure whether declaring a minor mode wasn't too overkill for a single variable but it turns out it makes everything simpler.  Thanks!
3. By "Emacs" I actually meant `pcomplete`.  Fixed.

**Comment by purcell** [comment]
Great! Minor modes often simplify things a lot.

Merged now - welcome to MELPA!

**Comment by Ambrevar** [comment]
Thanks!

**Pull request merged**
