### PR TITLE
Add recipe for exwm-float

### PR DESCRIPTION
**Pull request by mtekman**
### Brief summary of what the package does

This package provides a minor mode for manipulating floating frames in EXWM, particularly Picture-in-Picture frames though in theory it can target any floating frame. When enabled, the frame can be moved around by the keyboard, and user-customizable hotkeys can be used to place the frame in static locations.

[Live demo here](https://gitlab.com/mtekman/exwm-floatmode.el/uploads/5a7249fce6c8123459d214282b1ededf/out3.mp4)

### Direct link to the package repository

https://gitlab.com/mtekman/exwm-float.el

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass -- some issues appear to be due to wordwrapping the top line:

### exwm-floatmode.el ###

byte-compile (using Emacs 27.1):
- exwm-floatmode.el#L2: Move `lexical-binding: t` to the first line
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210111.341):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- exwm-floatmode.el#L394: You can use `not` or `null`

### Loadability ###

Verifying ability to #'load each file:
```
Loading exwm-floatmode.el
Done.
```
```
<a> is undefined
<a> is undefined
<a> is undefined
<a> is undefined
<a> is undefined
<a> is undefined
```
^ The fact that this is being output at load-time could point to an issue

### Package ###

- LICENSE excerpt: `GNU GENERAL PUBLIC LICENSE...`
- exwm-floatmode.el (GPL) -- Convenient modes and bindings for

**Comment by mtekman** [comment]
Thanks @riscy !

I added the following 6 commits:

* Review related fixes:
   * licensing fix
   * simplified conditional clause
   * fixed load issue and key binding ceremony
        * This was what was causing the `<a> is not defined` issue

* Not review related:
    * removed dash dependency
    * ignore for clean byte compile
    * autoloads changed

**Comment by riscy** [comment]
Great, thanks.  It looks like your recipe may need to exclude the `test-keymaps.el` file, which will be packaged up and sent to users by default.  Or you can rename it `keymaps-test.el` and it'll automatically be excluded.

Another quick pass of the main file:

### exwm-floatmode.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
exwm-floatmode.el:0: The first line should be of the form: ";;; package --- Summary"
Warning (emacs): 
exwm-floatmode.el:590: The footer should be: (provide 'exwm-floatmode)\n;;; exwm-floatmode.el ends here
```

package-lint (using version 20210127.158):
```
1 issue found:
1:0: error: package.el cannot parse this buffer: Package lacks a file header
```

**Comment by mtekman** [comment]
Thanks -- I just rebased without that file

I was confused by the checkdoc error, because in your first comment I thought you suggested that I add "(GPL)" to the name of the package, so I did and assumed that the upstream checkdoc would validate it. This is not the case then?

**Comment by riscy** [comment]
> I was confused by the checkdoc error, because in your first comment I thought you suggested that I add "(GPL)" to the name of the package, so I did and assumed that the upstream checkdoc would validate it. This is not the case then?

Ah!  Sorry about that, this was a lazy paste on my part that wasn't meant to point out any issue in particular -- that puts the checklist behind us.

Taking a closer look I have the following feedback:

- `(existing-binding (describe-key-briefly (kbd key)))` leaves echoes in the message area when the package is loaded, but you could check `(key-binding (kbd key))` instead
- Some of your documentation strings are unwrapped (the one for `exwm-floatmode-position-configs` extends as far as column 475); these should probably be wrapped at something standard like 80 characters or thereabouts so that (for example) the <kbd>M-x help</kbd> output isn't linebreaking in the middle of words
- Your `;;; Commentary` includes a TODO section, so your TODO will be indexed along with the description of your package in the MELPA index; perhaps users don't need to see this, but I believe you could replace the line `;; TODO:` with `;;; TODO:` to fix this.
- Minor, but back-front quoting functions/variables in your docstrings with two delimiters (e.g. ``` ``exwm-floatmode-position-configs'' ```) is typically done with just one delimiter on each side ( ``` `exwm-floatmode-position-configs' ```)
- Minor I think, but it's a bit unusual to name this package "floatmode" since <kbd>mode</kbd> has a very special meaning in the Emacs-sphere; if you're not locked in on that name, maybe `exwm-float` would be a better package name and prefix?

**Comment by mtekman** [comment]
Thanks! So I've fixed the `existing-binding` echo issue as you suggested in these two commits:

 * [simplified key detection](https://gitlab.com/mtekman/exwm-floatmode.el/-/commit/f46c1c22fb4d4f556bb7c96d62da5e7758a30e48)
 * [fix to existing key-binding](https://gitlab.com/mtekman/exwm-floatmode.el/-/commit/94e88101cf283887c30c13ea9178faafd640a823)

and I fixed the line-wrapping, double quotes, and split out the TODO into a separate file:

* [split out TODO to file](https://gitlab.com/mtekman/exwm-floatmode.el/-/commit/0afa0b787d80bc70fe3482ac79ead76ac1579969)
* [line wrap comment strings and remove double quotes](https://gitlab.com/mtekman/exwm-floatmode.el/-/commit/42acf177cea6d6b9dcfac8e706325aab08a16f38)

As for the package name, I'm definitely open to ideas (after having renamed it twice before as the project evolved), but `exwm-floating` [already exists](https://github.com/ch11ng/exwm) and so naming it `exwm-float` might be a bit too close to that and give the wrong impression that this package overrides or extends the current floating frame module.

This package only augments the existing floating frame capabilities, and does so primarily through a minor mode, so for that reason I feel that `exwm-floatmode` is reasonably apt at describing at -- but I don't want to blow conventions, so if you can think of a name encapsulates these two qualities (extra features, and minor-mode) I'm all ears!

Possible names I can think of:

* exwm-float-mode ? (added a hyphen)
* exwm-float-funcs ? (but this gives the impression of extra functions not bound to a mode)
*

**Comment by riscy** [comment]
Thank you!  I like `exwm-float-mode` but that suggests that users would be able to type <kbd>exwm-float-mode</kbd> to activate the toggle.  Maybe the minor mode could be similarly renamed to `exwm-float-mode` and that would make everything less surprising.

Also while I'm here, I notice there is an extra close paren around line 399 in the current code, and `checkdoc` gives its usual pedantic nag about `exwm-floatmode--inner-mode-exit`'s lack of docstring. :)

This should be an easy merge soon.

**Comment by mtekman** [comment]
Nice -- okay I went with exwm-float, because it does indeed make sense that the main mode should end in `-mode`

Fixed the dangling parenthesis (not sure how that snuck in there!)

Cheers

**Comment by riscy** [comment]
All set -- thanks for this.

**Comment by mtekman** [comment]
woo! thanks @riscy

**Pull request merged**
