### PR TITLE
Add dash-alfred recipe

### PR DESCRIPTION
**Pull request by xuchunyang**
### Brief summary of what the package does

Search Dash docs on-the-fly

### Direct link to the package repository

https://github.com/xuchunyang/dash-alfred.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by kidd** [comment]
is there any major difference with helm-dash?

**Comment by xuchunyang** [comment]
helm-dash is an independent application. dash-alfred is a search interface to Dash.app, dash-alfred works with Dash.app. The official (suggested by Dash.app) Emacs plugin is [dash-at-point](https://github.com/stanaka/dash-at-point), which can't search on-the-fly.

**Comment by riscy** [comment]
Just because `helm-dash` is an independent application doesn't mean we're not inadvertently duplicating functionality.  Similarly, there is [counsel-dash](https://github.com/dash-docs-el/counsel-dash), which looks to cover some of the feature you've developed here.  Can you comment a bit more on the novelty of your package so we know what to look for?

In the meantime, here's a pass over the code:

- [This](https://github.com/xuchunyang/dash-alfred.el/blob/e7f0f8dc98b1ecc7ca36652daa7b0b34ede1b8d2/dash-alfred.el#L35-L38) looks like something that would be worth making customizable or documenting in your commentary or README.
- [This](https://github.com/xuchunyang/dash-alfred.el/blob/e7f0f8dc98b1ecc7ca36652daa7b0b34ede1b8d2/dash-alfred.el#L56-L63) and [this](https://github.com/xuchunyang/dash-alfred.el/blob/e7f0f8dc98b1ecc7ca36652daa7b0b34ede1b8d2/dash-alfred.el#L107-L114) are so similar that I would strongly recommend factoring them out into a single function -- it'll make bugfixes easier in the future and shorten your code.
- The error message for ivy is `dashAlfredWorkflow fails` but the error message for helm is `dashAlfredWorkflow failed` -- probably both should be "failed"

**Comment by riscy** [comment]
Looking again, I'm seeing that this is an interface to Alfred rather than just dash, which makes sense.  Sorry for my misunderstanding.

**Comment by xuchunyang** [comment]
> Just because `helm-dash` is an independent application doesn't mean we're not inadvertently duplicating functionality. Similarly, there is [counsel-dash](https://github.com/dash-docs-el/counsel-dash), which looks to cover some of the feature you've developed here

That's right. `helm-dash` and `counsel-dash` are third-part client for browsing Dash docsets and probably have the same (and more) functionality. But when I try `helm-dash` last year it didn't work for me (I was unable to download the docsets). Dash.app is the official client for Dash docsets. My package, dash-alfred, isn't another third-part client of Dash docsets, it's just an interface for the Dash.app, thus its implement is mush simpler than `helm-dash` and `counsel-dash`.



> In the meantime, here's a pass over the code:

I have addressed these three points.

**Comment by xuchunyang** [comment]
I also updated the gif on README.md. I hope it makes the purpose of the package clearer.

**Comment by riscy** [comment]
Thanks for that.  This looks good to me!

**Pull request merged**
