### PR TITLE
Add recipe for find-dupes-dired

### PR DESCRIPTION
**Pull request by ShuguangSun**
### Brief summary of what the package does

Find dupes using external command (fdupes/jdupes) and handle them in dired-mode.

### Direct link to the package repository

https://github.com/ShuguangSun/find-dupes-dired

### Your association with the package

I'm the author and the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --
### find-dupes-dired.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
find-dupes-dired.el:59: Some lines are over 80 columns wide
Warning (emacs): 
find-dupes-dired.el:111: Argument `proc' should appear (as PROC) in the doc string
Warning (emacs): 
find-dupes-dired.el:167: Argument `proc' should appear (as PROC) in the doc string
Warning (emacs): 
find-dupes-dired.el:285: Some lines are over 80 columns wide
Warning (emacs): 
find-dupes-dired.el:398: Some lines are over 80 columns wide
```

package-lint (using version 20200906.512):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- find-dupes-dired.el#L214: It's safer to sharp-quote function names; use `#'`
- find-dupes-dired.el#L96: It's safer to sharp-quote function names; use `#'`

**Comment by ShuguangSun** [comment]
Thanks. I updated it accordingly.

**Comment by riscy** [comment]
Here's the latest, just a quick pass again --

### find-dupes-dired.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
find-dupes-dired.el:59: Some lines are over 80 columns wide
Warning (emacs): 
find-dupes-dired.el:112: Argument `proc' should appear (as PROC) in the doc string
Warning (emacs): 
find-dupes-dired.el:168: Argument `proc' should appear (as PROC) in the doc string
```

package-lint (using version 20210111.341):
- No issues!

**Comment by ShuguangSun** [comment]
The three warnings come from some variables referencing to `find-dired`, e.g., `find-ls-option` and `find-dired-filter`. I'd like to keep the similar documents as those in find-dired.

**Comment by riscy** [comment]
I suppose that's not a blocker in this case.  But if you want to maintain an explicit relationship to the find-dired functions, I'd suggest adding help-hyperlinks to them rather than insisting on copy-pasted versions of their docstrings.  You already do this for `find-dupes-dired-ls-option` ("For more information...") but this:

```
(defun find-dupes-dired-filter (proc string)
  "Filter for \\[find-dupes-dired] processes."
```
could easily be
```
(defun find-dupes-dired-filter (proc string)
  "Filter for \\[find-dupes-dired] processes.
This is analogous to `find-dired-filter'."
```
And that might free you up to clean up the docstrings so that if an issue ever does arise, you're not used to seeing checkdoc warnings.

**Pull request merged**
