### PR TITLE
Add recipe for simple-modeline

### PR DESCRIPTION
**Pull request by gexplorer**
### Brief summary of what the package does

A simple mode-line configuration for Emacs.

### Direct link to the package repository

https://github.com/gexplorer/simple-modeline

### Your association with the package

Author

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Looks nice!  Here's a quick run through the checklist --

### simple-modeline-core.el ###

byte-compile-file (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
simple-modeline-core.el:65: First sentence should end with punctuation
Warning (emacs): 
simple-modeline-core.el:65: Argument `name' should appear (as NAME) in the doc string
```

package-lint-current-buffer (using version 20200408.203):
```
1 issue found:
84:4: warning: Closing parens should not be wrapped onto new lines.
```


### simple-modeline-segments.el ###

byte-compile-file (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
simple-modeline-segments.el:185:1:Warning: the function `string-trim' is not
    known to be defined.
```
This you can fix with `(require 'subr-x)`.

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
```
6 issues found:
55:35: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
82:40: error: You should depend on (emacs "26.1") if you need `region-bounds'.
128:19: error: You should depend on (emacs "24.1") if you need `pcase'.
133:15: error: You should depend on (emacs "24.1") if you need `pcase'.
155:19: error: You should depend on (emacs "24.4") if you need `string-trim'.
171:16: error: You should depend on (emacs "24.4") if you need `string-trim'.
```
In this case you should add a `Package-Requiers` line to simple-modeline.el with a late-enough Emacs version.

Suggestions/experimental static checks:
- simple-modeline-segments.el#L78: It's safer to sharp-quote function names; use `#'`
- simple-modeline-segments.el#L103: It's safer to sharp-quote function names; use `#'`

### simple-modeline.el ###

byte-compile-file (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200408.203):
- No issues!


### Loadability ###

Running #'load on each file:
```
Loading simple-modeline-core.el
Loading simple-modeline-segments.el
Loading simple-modeline.el
Done.
```

### License ###

- Use a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by gexplorer** [comment]
Ok I just pushed all the changes you requested @riscy , thanks for the feedback!

**Comment by riscy** [comment]
No problem!  There's still the one issue re: adding a tooling-detectable LICENSE (or COPYING) file, but after that this is a quick merge.

**Comment by gexplorer** [comment]
Done, I just added the license.

**Comment by riscy** [comment]
Great!

**Pull request merged**
