### PR TITLE
Propose to use updated: inkpot-theme

### PR DESCRIPTION
**Pull request by ideasman42**
### Brief summary of what the package does

Update to a theme

### Direct link to the package repository

https://github.com/ideasman42/emacs-inkpot-theme

### Your association with the package

Offering to take over as maintainer to (unmaintained package). since author isnt responding.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

----

Contacted the author and submitted PR's - but this hasn't been updated since 2012.

Heres a comparison showing (the emacs theme as it is, the original theme in gvim, and my updated theme in emacs).
http://members.iinet.net.au/~ideasman42/pics/inkpot_theme_compare.png

Summary:

- Match original theme colors for: Cursor, selection, parenthesis, highlighted-line, (keyword, constant, error & function) terms, secondary selection and isearch.
- Add colors for ivy.
- Add document comment color.
- Correct mode-line variable names.

### CODE REVIEW

**Comment by syohex** [comment]
- I have sent PR about package meta comment https://github.com/ideasman42/emacs24-inkpot/pull/1
- Please write theme description. It is docstring of `deftheme` macro. Users cannot see anything without it by `M-x describe-theme`

**Comment by ideasman42** [comment]
Added description to `deftheme`, From checking other themes these descriptions tend to be short.
https://github.com/ideasman42/emacs24-inkpot/commit/f971e12d89f76fbb2c6ec615474c55d78d09d518

Also, possibly now would be a good time to rename the repository to `emacs-inkpot-theme` ? (the version number is now out-dated).
So I've pushed this repository to: https://github.com/ideasman42/emacs-inkpot-theme

**Comment by syohex** [comment]
- `URL:` header is not updated
- And please put license description
- Please squash commits

**Comment by ideasman42** [comment]
Updated URL, Added license... squishing commits now.

**Comment by purcell** [comment]
I'd suggest changing `"Inkpot theme, dark color scheme with bright easily identifiable colors."` to `"Dark color scheme with bright easily identifiable colors."`, because repeating the theme name is redundant.

Looks good otherwise - merging now.

**Comment by ideasman42** [comment]
@purcell thanks for the suggestion, applied.

**Pull request merged**
