### PR TITLE
Add modern-sh

### PR DESCRIPTION
**Pull request by damon-kwok**
### Brief summary of what the package does

An Emacs minor mode for editing shell script.

modern-sh-screenshot

### Direct link to the package repository

https://github.com/damon-kwok/modern-sh

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by a13** [comment]
I get the feeling that it's partly a poor man's projectile, isn't it?

**Comment by Silex** [comment]
@a13: this seems to be a better `sh-mode`, what gives you the impression that it's related to project management?

**Comment by a13** [comment]
@Silex functions like `modern-sh-project-*` look like they are

**Comment by riscy** [comment]
> More importantly, it is not what I want.

I won't block on your choice of how to handle "sh" projects (although please do consider my comments).  But I don't like seeing good feedback responded to like this.  What you want is secondary to good support for and compatibility with the ecosystem.

**Comment by damon-kwok** [comment]
Sorry, I am from a non-native English speaking country and my English is not clear enough.
I see that project.el still requires user-defined root, and It always returns nil in a non-Git directory. Neither of them is what I want.

**Comment by terlar** [comment]
What is user-defined root? I see it has something like this, where you could define custom project detection:
https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/project.el#L160

On the other hand I do know that it has changed quite a bit in the recent Emacs version, so I guess the benefit of a native dependency might not hold true (if you would have to specify the version from GNU ELPA). I was bringing it up due to your concern of projectile being too large.

I wasn’t sure if it would work for your use case, just a consideration.

**Comment by damon-kwok** [comment]
https://github.com/emacs-mirror/emacs/blob/bc5da2c3fb882a2df9d358e5b82869ab48a04d9a/lisp/progmodes/project.el#L1220
Thanks, Because I see that it contains the operation of project directory switching, which may cause unnecessary complexity. I used projectile for a while before, but because I didn't want to introduce it for an interface, I gave up.I only need one function: get the root directory location.

**Comment by damon-kwok** [comment]
@terlar I know very little about project.el, are you interested in submitting a PR?

**Comment by damon-kwok** [comment]
@riscy Updated project root trait:
```elisp
(defun modern-sh-project-root-p (path)
  "Return t if directory `PATH' is the root of the Modern shell project."
  (let* ((files '( ".projectile" ".git" ".svn" ".hg" ".bzr"  ;
                   "Dockerfile" ".editorconfig" ".gitignore" ;
                   "Makefile" "CMakeLists.txt" "make.bat"))
          (foundp nil))
    (while (and (> (length files) 0)
             (not foundp))
      (let* ((filename (car files))
              (filepath (concat (file-name-as-directory path) filename)))
        (setq files (cdr files))
        (setq foundp (file-exists-p filepath)))) ;
    foundp))
```

**Comment by riscy** [comment]
Sounds good.  Like I said, I won't block on this, but files like Makefile, .gitignore, and Dockerfile often end up in project subdirectories that aren't necessarily the root directory -- something to be aware of.

Thanks for this!

**Comment by damon-kwok** [comment]
This is indeed a problem, and I will find a way to solve it.

**Pull request merged**
