### PR TITLE
Add receipe for my repo pins

### PR DESCRIPTION
**Pull request by NinjaTrappeur**
### Brief summary of what the package does

The general idea of this package is to help with keeping a set of git repositories in a single unified tree.

IE. organizing the git repositories in a structure like that

```
~/code-root
├── codeberg.org
│   └── Freeyourgadget
│       └── Gadgetbridge
└── github.com
    ├── BaseAdresseNationale
    │   └── fantoir
    ├── mpv-player
    │   └── mpv
    └── NinjaTrappeur
        ├── cinny
        └── h.el
```

The package provides a unified entry point to jump to a local repository clone, and query remote forges then clone a repository found there.

Some screencaps shamelessly stolen from the project's readme illustrating what I mean with the (confusing?) previous paragraph :)

### Direct link to the package repository

https://github.com/NinjaTrappeur/h.el

### Your association with the package

I am the maintainer.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by minad** [comment]
Did you consider using a longer package name prefix? h is not meaningful and should not be used.

**Comment by NinjaTrappeur** [comment]
This package is an emacs port of a software called h: https://github.com/zimbatm/h

Would `hel` be good enough? 

If not, I'll try to think about something better without reflecting the original name.

**Comment by minad** [comment]
hel is slightly better, but also not that meaningful? Something like projnav or projectnav may be even better. The h project you linked above has a reason to use a short name, since it is as a shell command. This reason does not exist in Emacs. But even for a shell command using such short names isn't good engineering. I would use longer meaningful names (three characters or more). The user can use define shell aliases if they want an abbreviation for commonly used commands.

**Comment by NinjaTrappeur** [comment]
Alright. I'll try to find something more descriptive, hopefully involving a terrible pun.

**Comment by alphapapa** [comment]
Well, if `project-ninja` is too long, how about...well, `pun`?  It could stand for "Project Unifying Ninja"...

**Comment by riscy** [comment]
I agree that the `h` is a little on the short side, and I think we authors should be careful about taking those namespaces unless there's extremely good justification (e.g. [a major mode for a popular programming language](https://melpa.org/#/d-mode)).

While you're thinking about the rename, I have some very minor lints I can pass along while I'm rolling through:

- h.el#L626: This double negation can be collapsed (`not` aliases `null`)
- h.el#L640: This double negation can be collapsed (`not` aliases `null`)
- h.el#L614: No `format` required; `error` takes an f-string
- h.el#L622: No `format` required; `error` takes an f-string
- h.el#L678: No `format` required; `error` takes an f-string
- h.el#L767: No `format` required; `error` takes an f-string
- h.el#L779: No `format` required; `error` takes an f-string
- h.el#L669: No `format` required; `message` takes an f-string
- h.el#L680: No `format` required; `message` takes an f-string
- h.el#L690: No `format` required; `message` takes an f-string
- h.el#L691: No `format` required; `message` takes an f-string
- h.el#L694: No `format` required; `message` takes an f-string

**Comment by NinjaTrappeur** [comment]
> Well, if project-ninja is too long, how about...well, pun? It could stand for "Project Unifying Ninja"...

Haha. I like it! It's a bit too egomaniac for me to be comfortable with it, though. Thanks :smile: 

------------------------------------------------------------------------------

I renamed the project to "my repo pins"[^1] in https://github.com/NinjaTrappeur/my-repo-pins/commit/c058603766c3e62c2af9dc2c184dc732268f97ae.

I fixed the issues listed by @riscy in https://github.com/NinjaTrappeur/my-repo-pins/commit/001016ebf557bc9a13aea3b8e1196fd4e5b57af6. Your linting rules were **really** useful for a newcomer like me. I did not manage to set up your linter in my CI for now though[^2].

-------------------------------------------------------------------------------------

PTAL

[^1]: :open_umbrella: 
[^2]: as it is, I can only install Melpa packages in my test job. I'll probably rework it in the future to include your linter :)

**Comment by alphapapa** [comment]
> I did not manage to set up your linter in my CI for now though

FYI, https://github.com/alphapapa/makem.sh lets you easily test packages in a sandboxed Emacs config, locally or on CI.

**Comment by riscy** [comment]
Now that things are settled I took a closer look --

I noticed this comment:
```
            ;; Buckle up, dirty hack ahead:
            ;;
            ;; As I am writing this, there's no way to tell the emacs
            ;; byte compiler a particular dependency is optional.
```
What you can do in this case is `(require 'evil-core nil t)` and then use `declare-function` to hint the byte-compiler that the function is expected to exist when you call it, e.g. `(declare-function evil-local-set-key "ext:evil-core.el" nil t)` should do the trick.

In a couple cases you're throwing `error`s but you might want to check whether `user-error` is a better choice (i.e. do you want to not potentially open a stack trace for the user when this happens?)

In your front matter only the headings should start with `;;;` e.g. `;;; Commentary:` and the body text should start with two `;;`.  Right now it works okay, but by starting with `;;;` you risk `(lm-commentary)` misinterpreting any line that contains `;;; <word>:` as a section heading, which would truncate your `;;; Commentary`.

A minor code-style comment I have is that most if not all of your `progn`s are unnecessary -- `defun`/`lambda` bodies never need to start with `progn` and the body under a `let` doesn't need to be wrapped in a `progn`.  The `if` in `my-repo-pins--fetch-github-parse-response` could just be rewritten as a `when` (which doesn't need a `progn` and will return nil when the condition isn't met anyway).  And noting that `'()` is equivalent to `nil` the same can be said of `my-repo-pins--get-code-root-projects`.

Also minor, `my-repo-pins--completing-read-or-custom` mentions `complete-read` but should this be `completing-read`?

**Comment by NinjaTrappeur** [comment]
Wow, this was a goldmine. Massive kudos for the spot on advices!

I addressed all your comments in the above commits (incl. the completing read typo, I forgot to mention your review URL in the commit message for this one).

PTAL

**Comment by riscy** [comment]
Looks good to go.  A last couple of nits I'm noticing at the last minute, nothing blocking --

- avoid camelCase in elisp code -- it's the community style
- A `progn` isn't necessary around the "else" part of an `if`; this could save you some nesting in a couple places
- You should aim to format example output (e.g. as in the docstring for `my-repo-pins--fetch-gitea-parse-response` and `my-repo-pins--fetch-github-parse-response`) the way elisp should normally appear, i.e. no trailing parentheses on lines by themselves
- taylor -> tailor, dertermine -> determine

And welcome to MELPA. :)

**Comment by NinjaTrappeur** [comment]
ACK. I fixed the last two points.

> And welcome to MELPA. :)

Thanks :smile: 

-------------------------------------------------

I wanted to state that I'm very impressed by this review process. I did not expect to learn so much from a repository inclusion PR! 

There's of course some level of automation involved, but, looking at some review comments in this PR, I can see that there's still a fair share of careful manual review involved. 

Meaning a fair share of effort and time spent in that review process. 

It transforms this vetting phase into a knowledge transfer/learning experience for newcomers. From the receiving side perspective, it definitely made me feel welcome in this Emacs greater community. That's a nice feeling to experience.

Thank you a lot for that.

**Pull request merged**
