### PR TITLE
Add recipe for Socyl

### PR DESCRIPTION
**Pull request by nlamirault**
### Brief summary of what the package does

The emacs frontend for several search tools (ag, pt, sift, ripgrep, ...) 
### Direct link to the package repository

https://github.com/nlamirault/socyl
### Your association with the package

I'm the maintener.
### Relevant communications with the upstream package maintainer

NONE
### Checklist
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

Signed-off-by: Nicolas Lamirault nicolas.lamirault@gmail.com

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR(https://github.com/nlamirault/socyl/pull/2) about cl-lib

**Comment by nlamirault** [comment]
Merged.

**Comment by purcell** [comment]
Thanks - looks nice. Quick feedback:

- Why autoload `socyl--pt-regexp` etc? I don't see how that provides any benefit, given how you've organised the files: you're loading all of them unconditionally from `socyl.el` anyway.
- The package description `Socyl, the emacs frontend for several search tools` shouldn't mention Emacs, or repeat the package name. Just use `Front-end for several search tools`
- No usage information is provided in the `Commentary` section of `socyl.el`, so it's not obvious how to use the package.

Hope that helps!

**Comment by tarsius** [comment]
@nlamirault It appears there's little to be done for you to get this accepted into Melpa. Do you plan to do that anytime soon?

**Comment by nlamirault** [comment]
asap. I will try that next week.

**Comment by tarsius** [comment]
Okay, thanks!

**Comment by nlamirault** [comment]
Done.

**Comment by tarsius** [comment]
Thanks! And merged.

**Pull request merged**
