### PR TITLE
Add recipe for company-plsense

### PR DESCRIPTION
**Pull request by CeleritasCelery**
### Brief summary of what the package does

company backend for Perl5 via [plsense](https://github.com/aki2o/emacs-plsense)

### Direct link to the package repository

https://github.com/CeleritasCelery/company-plsense

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

none needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Today I learned about `tq` - very neat. Quick feedback:

- You're missing a dependency declaration for `cl-lib`. `package-lint` should have pointed that out...
- [Here](https://github.com/CeleritasCelery/company-plsense/blob/c388cb4d88e11886c022f0449c5fa8fa378e18ba/company-plsense.el#L52) you're saying that the customisation group is its own parent.
- You can drop the `:group` keys from the `defcustom` items, since they will default to the last-defined group above.
- Is [this](https://github.com/CeleritasCelery/company-plsense/blob/c388cb4d88e11886c022f0449c5fa8fa378e18ba/company-plsense.el#L218) safe for filenames containing spaces or quote characters? I feel like you'd want to use `shell-quote-argument` or similar here.

**Comment by CeleritasCelery** [comment]
I was under the impression that `cl-lib` was built-in and that's why I didn't include it. Also `package-lint` was clean. Either way I will address your feedback and post a new comment. Thanks!

**Comment by CeleritasCelery** [comment]
Alright @purcell I fixed all the issues you brought up except the one below

> Is this safe for filenames containing spaces or quote characters?

I am glad you pointed it out, because it forced me to double check. When we create a process with `plsense --interactive` it starts a it's own REPL that doesn't have a problem with spaces, quotes, `$`'s, etc in file names. So the answer is yes.

**Comment by purcell** [comment]
> I was under the impression that cl-lib was built-in and that's why I didn't include it. Also package-lint was clean.

Turned out that's a bug in `package-lint` - thanks for discovering it!

**Comment by purcell** [comment]
Super, thanks - merged!

**Comment by purcell** [comment]
And... welcome to MELPA. :-)

**Pull request merged**
