### PR TITLE
Add recipe for shades-of-purple-theme

### PR DESCRIPTION
**Pull request by arturovm**
### Brief summary of what the package does

This package is a port of [Shades of Purple for VSCode](https://github.com/ahmadawais/shades-of-purple-vscode) by @ahmadawais

### Direct link to the package repository

https://github.com/arturovm/shades-of-purple-emacs

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This is minor since I believe `provide-theme` already runs `provide` behind the scenes, but --

package-lint (using version 20210111.341):
```
1 issue found:
1:0: error: There is no (provide 'shades-of-purple-theme) form.
```
you can pacify package-lint by adding that line, and it's no harm.

If "main" is your default branch in GitHub, there's no need to specify it in your recipe and we prefer that you don't.  This gives you the freedom in the future to rename your default branch without followup PRs.

**Comment by arturovm** [comment]
@riscy Hi, Chris, thanks for taking a look at this! Do you mean adding a `provide` form _instead_ of the `provide-theme` form? Or in addition to? Sorry for the newbie question, I'm still new to Elisp.

And sure, I'll remove the branch keyword (:

Thanks again.

**Comment by riscy** [comment]
In addition to.  :)  Not a newbie question -- I think you'll have to be careful that the `provide` line goes at the very end of the file too, or checkdoc will nag.

**Comment by arturovm** [comment]
@riscy Alright! Done. The linters aren't complaining now 👌🏽

**Comment by riscy** [comment]
Thanks!  And, welcome to MELPA. :)

**Comment by arturovm** [comment]
@riscy Thanks! :D

**Pull request merged**
