### PR TITLE
Add recipe for mpdel-embark

### PR DESCRIPTION
**Pull request by DamienCassou**
### Brief summary of what the package does

Summary: Integrate Emacs package mpdel with embark

### Direct link to the package repository

https://github.com/mpdel/mpdel-embark

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`mpdel-embark.el` with byte-compile using Emacs 28.1:
```
mpdel-embark.el:29:1: Error: Cannot open load file: No such file or directory, libmpdel
```
It looks like a package-requires is needed on libmpdel, mpdel, and embark.

When these are available checkdoc whines a little bit:
`mpdel-embark.el` with checkdoc 0.6.2:
```
mpdel-embark.el:42: Disambiguate mpdel-core-map by preceding w/ function,command,variable,option or symbol.
mpdel-embark.el:135: Disambiguate mpdel-core-map by preceding w/ function,command,variable,option or symbol.
```
but these rephrasings can admittedly be surprisingly difficult.

**Comment by DamienCassou** [comment]
> It looks like a package-requires is needed on libmpdel, mpdel, and embark.

Fixed. Sorry for not paying attention enough. I'm sure I tried to install mpdel-embark inside a sandbox Emacs as recommended by the CONTRIBUTING file. What I think happened is that all dependencies were already downloaded and Emacs just loaded them fine. It would be cool if the sandbox could work in a clean `.emacs.d/` directory.

> When these are available checkdoc whines a little bit:

Fixed as well. My CI runs checkdoc in batch mode automatically and it didn't catch these errors. It seems running checkdoc interactively triggers more errors...

Thank you for the attention you gave to my PR. I appreciate your effort.

**Comment by DamienCassou** [comment]
@riscy is it ok if I merge the PR now?

**Comment by riscy** [comment]
No problem -- 

>  It would be cool if the sandbox could work in a clean .emacs.d/ directory.

That's a good idea - my "hack" right now is the melpazoid scripts, which install everything from scratch, but they can occasionally be error-prone.

But yes you can merge - or I'll just go ahead and do that right now. :)

**Pull request merged**
