### PR TITLE
Add recipe for kotlin-ts-mode

### PR DESCRIPTION
**Pull request by bricka**
### Brief summary of what the package does

Major mode for Kotlin based on tree-sitter

### Direct link to the package repository

https://gitlab.com/bricka/emacs-kotlin-ts-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

***None needed***

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this. 

I am only familiar with treesitter at the highest level, so maybe you an help clarify for me.  Are we to anticipate a glut of new `ts` major modes with the introduction of treesit to Emacs 29?  In general I feel like it would be better for users if the existing major modes incorporated treesit functionality as an optional feature.  e.g. I'm just going by lines of code which obviously isn't everything, but the existing kotlin major mode is twice as large; wouldn't it be great if these two major modes shared a development path?

The nits --

`kotlin-ts-mode.el` with package-lint 20221003.1636:
```
2 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
6:23: warning: This makes the package uninstallable in all released Emacs versions.
```
It's true that MELPA *will* handle the `Version:` nit, but I think it's better to make package-lint happy and add such a header (Prefer `Version` over `Package-Version`).

This major mode probably also needs an `auto-mode-alist` entry similar to [the existing kotlin mode's](https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/blob/55eed95033a59d7448a4b2bc11879e62c05e361b/kotlin-mode.el#L492-L493).

**Comment by bricka** [comment]
Thanks for calling out the nitpicks!

To your main question: unfortunately, probably yes. The choice with the built-in modes was also to develop new major modes supporting `tree-sitter` instead of updating existing ones...see for example https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/c-ts-mode.el. There's a bit of explanation here: https://git.savannah.gnu.org/cgit/emacs.git/tree/admin/notes/tree-sitter/starter-guide under "Tree-sitter major modes".

**Comment by jcs090218** [comment]
Maybe this package can be submit to the upstream too? Due to there are many `xxx-ts-mode` submissions by seeing the emacs-devel, 

* `ruby-ts-mode` - https://lists.gnu.org/archive/html/emacs-devel/2022-12/threads.html
* `toml-ts-mode` - https://lists.gnu.org/archive/html/emacs-devel/2022-12/msg00353.html

Just an advice. 👀

**Comment by wkirschbaum** [comment]
> I am only familiar with treesitter at the highest level, so maybe you an help clarify for me. Are we to anticipate a glut of new `ts` major modes with the introduction of treesit to Emacs 29? In general I feel like it would be better for users if the existing major modes incorporated treesit functionality as an optional feature. e.g. I'm just going by lines of code which obviously isn't everything, but the existing kotlin major mode is twice as large; wouldn't it be great if these two major modes shared a development path?

There has been quite a bit discussion around this in emacs devel, but for now -ts-mode's will live separately because the implementation is significantly different and also adding tree-sitter dependency might cause unwanted behaviour for derived modes. Point is there will be ts-modes in parallel with non-ts modes for emacs 29. 

I am busy prepping for submission of elixir-ts-mode and heex-ts-mode which will be submitted to emacs master, but only for emacs 30, which is a long enough time to have an interim MELPA version for people to use in the mean time if it makes sense.

**Comment by riscy** [comment]
Thanks all for helping my understanding.  These will be a little harder to review because my current pipeline is Emacs 28-based -- apologies in advance for any oversights.

Here's an updated pass of the package in this PR:

`kotlin-ts-mode.el` with byte-compile using Emacs 28.1:
```
kotlin-ts-mode.el:387:8: Warning: docstring wider than 80 characters
kotlin-ts-mode.el:380:4: Warning: the function `string-join' is not known to
    be defined.
```

`kotlin-ts-mode.el` with package-lint 20221003.1636:
```
11 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
6:23: warning: This makes the package uninstallable in all released Emacs versions.
156:5: warning: Closing parens should not be wrapped onto new lines.
198:5: warning: Closing parens should not be wrapped onto new lines.
339:9: warning: Closing parens should not be wrapped onto new lines.
343:4: warning: Closing parens should not be wrapped onto new lines.
344:4: warning: Closing parens should not be wrapped onto new lines.
362:6: warning: Closing parens should not be wrapped onto new lines.
363:4: warning: Closing parens should not be wrapped onto new lines.
385:2: warning: Closing parens should not be wrapped onto new lines.
405:2: warning: Closing parens should not be wrapped onto new lines.
```

**Comment by riscy** [comment]
Also please disregard my comment above re: auto-mode-alist; I am actually not yet aware what the norm is for these packages re: auto-mode-alist, especially when a non-treesit mode is anticipated to be available in the same install.

**Comment by wkirschbaum** [comment]
Just for reference want to link the explanation why ts-modes from Eli to rms: https://mail.gnu.org/archive/html/emacs-devel/2023-01/msg00007.html. 

@bricka I created an issue to address some byte compile issues without tree-sitter: https://gitlab.com/bricka/emacs-kotlin-ts-mode/-/issues/1

**Comment by bricka** [comment]
Sorry for the radio silence of the past few days. Happy New Year!

I have done another update of the package, and `package-lint` is not returning any errors for me. I also don't see any `byte-compile` warnings at all, but I never saw the warning about `string-join` at all. Is there anything that I need to do to see more potential warnings?

**Comment by wkirschbaum** [comment]
> I have done another update of the package, and `package-lint` is not returning any errors for me. I also don't see any `byte-compile` warnings at all, but I never saw the warning about `string-join` at all. Is there anything that I need to do to see more potential warnings?

Please run byte-compile on a emacs build --without-tree-sitter, because there are many warnings, so the issue i created on your repository. You can also have a look at -ts-modes already submitted to emacs core. 

you probably also need to add `(eval-when-compile (require 'subr-x))` to the top of the file before using `string-join`.

**Comment by riscy** [comment]
Thank you very much for looking, @wkirschbaum - this is a difficult package for me to automatically test because Emacs 29 isn't part of my testing pipeline.

**Comment by riscy** [comment]
@bricka Friendly ping over here. :)

**Comment by bricka** [comment]
I completely forgot to answer on this ticket: sorry! As far as I know, I have now addressed all of the byte compilation issues.

I get this from `package-lint`, but it's expected:
```
1 issue found:

7:23: warning: This makes the package uninstallable in all released Emacs versions.
```

And no issues when byte compiling. With Tree Sitter:
```
alex@danu ‹ emacs-29 › : ~/src/emacs
[0] % ./src/emacs -batch -f batch-byte-compile ~/src/emacs-kotlin-ts-mode/kotlin-ts-mode.el 

alex@danu ‹ emacs-29 › : ~/src/emacs
[0] % 
```

And w/o Tree Sitter:
```
alex@danu ‹ emacs-29 › : ~/src/emacs-wo-treesit
[0] % ./src/emacs -batch -f batch-byte-compile ~/src/emacs-kotlin-ts-mode/kotlin-ts-mode.el     

alex@danu ‹ emacs-29 › : ~/src/emacs-wo-treesit
[0] % 
```

Let me know what you all think.

**Comment by riscy** [comment]
Do we have a link to the issue @wkirschbaum raised on the repository, and do we know whether it's resolved?  Unfortunately (not to sound like a broken record) these Emacs 29 packages are currently hard for me to verify, so getting some input from other community members is extremely valuable.

**Comment by wkirschbaum** [comment]
@riscy the issues I picked up were resolved.

**Comment by riscy** [comment]
Looks good - and thanks all!

**Pull request merged**
