### PR TITLE
Circuitpython mode

### PR DESCRIPTION
**Pull request by nelsonov**
### Brief summary of what the package does

Minor mode to improve workflow when programming microcontrollers in Adafruit's [Circuitpython.](https://circuitpython.org/)

### Direct link to the package repository

https://github.com/nelnet-team/circuitpython-mode

### Your association with the package

I am the author

### Relevant communications with the upstream package maintainer

None Needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass.

### circuitpython-mode.el ###

byte-compile (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
circuitpython-mode.el:101:11:Warning: reference to free variable
    `circuitpython-copy-path'
```

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200419.406):
```
3 issues found:
5:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
145:69: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
146:74: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
```

Suggestions/experimental static checks:
- circuitpython-mode.el#L154: It's safer to sharp-quote function names; use `#'`

### Loadability ###

Verifying ability to #'load each file:
```
Loading circuitpython-mode.el
Done.
```

### Package ###


- GitHub API found `MIT License`
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.org/using-spdx-license-identifier) to circuitpython-mode.el
- Package-Requires: n/a
- pkg/circuitpython-mode.el (unknown license) -- Minor mode for CircuitPython

**Comment by nelsonov** [comment]
I do not know why Tavis is failing.  I don't see any useful output from Tavis.  I get this running `M-x version` and `M-x byte-compile-file` locally:
```
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-22, modified by Debian
Compiling /home/lnelson/src/elisp/circuitpython-mode/circuitpython-mode.el...done
Wrote /home/lnelson/src/elisp/circuitpython-mode/circuitpython-mode.elc
```
`M-x package-lint-current-buffer` shows no issues.

The `make` commands run clean:

```
18:00:16 penguin lnelson:~/src/elisp/melpa> make recipes/circuitpython-mode
 • Building package circuitpython-mode ...
Package: circuitpython-mode
Fetcher: github
Source:  https://github.com/nelnet-team/circuitpython-mode.git

Updating /home/lnelson/src/elisp/melpa/working/circuitpython-mode/
Built circuitpython-mode in 28.762s, finished at Sun Jul 26 18:12:24 2020
 ✓ Success:
4.0K -rw-r--r-- 1 lnelson lnelson 4.0K Jul 16 20:26 packages/circuitpython-mode-20200717.325.el
4.0K -rw-r--r-- 1 lnelson lnelson  339 Jul 16 20:26 packages/circuitpython-mode-20200717.325.entry
8.0K -rw-r--r-- 1 lnelson lnelson 6.0K Jul 26 18:12 packages/circuitpython-mode-20200727.52.el
4.0K -rw-r--r-- 1 lnelson lnelson  344 Jul 26 18:12 packages/circuitpython-mode-20200727.52.entry
4.0K -rw-r--r-- 1 lnelson lnelson 1.2K Jul 26 18:12 packages/circuitpython-mode-badge.svg
4.0K -rw-r--r-- 1 lnelson lnelson 2.8K Jul 26 18:12 packages/circuitpython-mode-readme.txt

18:12:43 penguin lnelson:~/src/elisp/melpa> STABLE=t make recipes/circuitpython-mode
 • Building package circuitpython-mode ...
Package: circuitpython-mode
Fetcher: github
Source:  https://github.com/nelnet-team/circuitpython-mode.git

Updating /home/lnelson/src/elisp/melpa/working/circuitpython-mode/
Built circuitpython-mode in 29.256s, finished at Sun Jul 26 18:13:15 2020
 ✓ Success:
8.0K -rw-r--r-- 1 lnelson lnelson 5.8K Jul 19 14:33 packages-stable/circuitpython-mode-0.5.el
4.0K -rw-r--r-- 1 lnelson lnelson  330 Jul 19 14:33 packages-stable/circuitpython-mode-0.5.entry
8.0K -rw-r--r-- 1 lnelson lnelson 5.9K Jul 26 18:13 packages-stable/circuitpython-mode-0.6.3.el
4.0K -rw-r--r-- 1 lnelson lnelson  338 Jul 26 18:13 packages-stable/circuitpython-mode-0.6.3.entry
4.0K -rw-r--r-- 1 lnelson lnelson 1.2K Jul 26 18:13 packages-stable/circuitpython-mode-badge.svg
4.0K -rw-r--r-- 1 lnelson lnelson 2.8K Jul 26 18:13 packages-stable/circuitpython-mode-readme.txt

```
I'm at a loss about what is wrong.

**Comment by nelsonov** [comment]
All I've done since the previous commit was change a keymap.  I still don't understand why the previous build failed and this one succeeded.

**Comment by riscy** [comment]
Sorry about that - the Travis build is a little flaky right now and you can disregard its failures (usually).  Here's the latest.

byte-compile (using Emacs 26.3):
```
circuitpython-mode.el:104:11:Warning: reference to free variable
    `circuitpython-copy-path'
```
Instead of using .dir-locals.el or file-local variables to define the variable, can we check whether it is non-nil?  Then you can simply `(defvar circuitpython-copy-path)` at the top of this file and quiet the compiler.

Minor:
- potentional -> potential
- newcommand/NEWCOMMAND -> new-command/NEW-COMMAND

**Comment by nelsonov** [comment]
I am not sure how to get rid of the compiler warning.  The file/dir-local variable is part of the intended functionality.  If `circuitpython-copy-path` is not defined externally, then do nothing with `compile-command`.  The variable is not a flag.  It's the value that should be used, if it exists, to compose the path that is used in defining a new `compile-command`. If I use `defvar`, then it overwrites the file/dir-local variable.

**Comment by nelsonov** [comment]
There's always the nuclear option of using a `(with-no-warnings ....)` block, but I'm not you would even find that acceptable. So, the offending section would look something like:
```
    (with-no-warnings (set 'compile-command
         (concat
	  "cp "
	  (file-name-nondirectory (buffer-file-name (current-buffer)))
	  " "
	  circuitpython-copy-path))))
```

**Comment by riscy** [comment]
>  If circuitpython-copy-path is not defined externally, then do nothing with compile-command. The variable is not a flag. It's the value that should be used, if it exists, to compose the path that is used in defining a new compile-command.

I believe the pattern you have in mind won't work -- this expression, which is at the top-level:
```
(if (boundp 'circuitpython-copy-path)
    (add-hook 'after-save-hook #'circuitpython-compile-copy)
  nil)
```
will only run _once_, i.e. when the user loads `circuitpython-mode` (under normal conditions).

I'll also add that it is okay (and actually common) to have a variable act as both a flag and a value in elisp; for example see the variable `display-line-numbers`.

>  If I use defvar, then it overwrites the file/dir-local variable.

`defvar` never overwrites anything.  If declares the variable (as nil or whatever) if it doesn't exist, otherwise it leaves that variable alone.  There is also a function called `defvar-local`, which automatically makes the variable buffer-local.

Hopefully that helps -- let me know!

**Comment by tarsius** [comment]
I am closing because there were no new commits or a reply in a few months.

**Pull request closed without merging**
