### PR TITLE
omtose-phellack recipe fix

### PR DESCRIPTION
**Pull request by franksn**
recipe fix.

### CODE REVIEW

**Comment by purcell** [comment]
This will *only* include the elisp in the `variants` subdir. Is that right? I doubt it.

**Comment by franksn** [comment]
it is correct.:)

**Comment by purcell** [comment]
I applied that too hastily, and then had to revert it. Essentially, you must have a file matching the name of the package/recipe so that the metadata can be located. In your case, since you don't want to bundle `omtose-phellack-theme.el` into the package, you might like to place an `omtose-phellack-theme-pkg.el` in the `variants` subdir: it would contain a `define-package` form.

**Comment by franksn** [comment]
done, thanks a lot.

**Comment by purcell** [comment]
Thanks - I’ve reapplied the changes in this PR, so they’ll take effect the next time the package builds.

**Pull request merged**
