### PR TITLE
Add recipe for general.el

### PR DESCRIPTION
**Pull request by noctuid**
[This package](https://github.com/noctuid/general.el) provides a single function to make key definition more convenient for both evil and non-evil users. It is written by myself, and I have tested it in the sandbox.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Feels like `general--delay` should be a macro. That `eval` is extremely fishy. :-)

**Comment by noctuid** [comment]
`general--delay` comes straight from evil. I think I originally tried changing it to a macro but got stuck somewhere. Thanks for merging.

**Comment by purcell** [comment]
Eurgh, okay then! :-)

**Comment by noctuid** [comment]
It is pretty ugly; I'll fix it. Thanks for the suggestion.

**Pull request merged**
