### PR TITLE
Add recipe for elisp-demos

### PR DESCRIPTION
**Pull request by xuchunyang**
### Brief summary of what the package does

Code demos for Emacs Lisp APIs

### Direct link to the package repository

https://github.com/xuchunyang/elisp-demos

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

I am the maintainer

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

**None need**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
This is a neat idea. It would be good to organize the functions by package. It may confuse users who browse the Org file to see, e.g. Dash functions mixed with built-ins.

**Comment by xuchunyang** [comment]
All Dash functions are prefixed by a `-` except `!cons` and `!cdr`. This exception caused my confusion too.

**Comment by xuchunyang** [comment]
Good idea. But I want to keep it simple for now. The Org file is already sorted alphabetically, as a result, it is also grouped by packages more or less.

**Comment by purcell** [comment]
Thanks for this, and for your patience - merged now.

**Pull request merged**
