### PR TITLE
Add new package for gerrit.el

### PR DESCRIPTION
**Pull request by thisch**
### Brief summary of what the package does

This package is currently mainly an emacs interface for the git-review CLI tool. It allows you to upload (gerrit-upload) and download (gerrit-download) gerrit changes. In the latter case it is possible to specify reviewer(s), topic name, WIP flag and custom (git-review) parameters.

### Direct link to the package repository

https://github.com/thisch/gerrit.el

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

 **None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
### gerrit-rest.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
gerrit-rest.el:55: All variables and subroutines might as well have a documentation string
Warning (emacs): 
gerrit-rest.el:90: All variables and subroutines might as well have a documentation string
Warning (emacs): 
gerrit-rest.el:93: All interactive functions should have documentation
Warning (emacs): 
gerrit-rest.el:131: All interactive functions should have documentation
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
No issues found.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other static checks:
- gerrit-rest.el#L139: It's safer to sharp-quote function names; use `#'`


### gerrit.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
gerrit.el:150: All variables and subroutines might as well have a documentation string
Warning (emacs): 
gerrit.el:165: All variables and subroutines might as well have a documentation string
Warning (emacs): 
gerrit.el:303: All variables and subroutines might as well have a documentation string
Warning (emacs): 
gerrit.el:332: Lisp symbol `top-level' should appear in quotes
Warning (emacs): 
gerrit.el:335: All interactive functions should have documentation
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
1 issue found:

328:0: error: "magit-open-reviews-issue-section-map" doesn't start with package's prefix "gerrit".
```
(This looks deliberate, which I'll take into account on next pass)

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other static checks:
- gerrit.el#L75: Alias targets should be sharp-quoted; use `#'`
- gerrit.el#L284: Alias targets should be sharp-quoted; use `#'`
- gerrit.el#L96: Prefer `https` over `http` (if possible)

**Comment by thisch** [comment]
I've just fixed all the issues except 

```
328:0: error: "magit-open-reviews-issue-section-map" doesn't start with package's prefix "gerrit".
```
which can't be fixed, because the `magit-` prefix is required by `magit-insert-section`.

**Comment by riscy** [comment]
Thanks!  I'm looking at `magit-open-reviews-issue-section-map` and have read the `magit-insert-section` docstring and that usage looks fine to me.  Not a blocker, but perhaps some of this clarifying commentary (especially the "see `magit-insert-section`" part) looks like it could be added to the variable's docstring too.

On the latest master:

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
gerrit.el:208:10:Warning: reference to free variable `history'

In gerrit-upload-set-topic:
gerrit.el:230:4:Warning: reference to free variable `history'

In gerrit-upload-set-args:
gerrit.el:237:4:Warning: reference to free variable `history'
```
But really `history` is in reference to the variable `gerrit-last-reviewers` in this case --
```elisp

(defun gerrit-upload-remove-reviewer ()
  "Interactively ask for to-be-removed reviewer name."
  (interactive)
  (setq gerrit-last-reviewers
        (delete (gerrit-upload-completing-set
                 "Reviewer: "
                 gerrit-last-reviewers)
                gerrit-last-reviewers)))
```

**Comment by thisch** [comment]
You unfortunately noticed the issue with the free var before I noticed that the travis-ci job of `gerrit.el` failed. ;)  Should be fixed now. I've also extended the docstring of the `magit-open-reviews-issue-section-map`

**Comment by riscy** [comment]
Thanks for that - digging a little deeper now, I am noticing https://github.com/terranpro/magit-gerrit and https://github.com/chmouel/gerrit-download.el -- these are older packages, but have you had a chance to compare to these?

**Comment by thisch** [comment]
> but have you had a chance to compare to these?

Sure, I had. See the last section in the Readme file.

**Comment by riscy** [comment]
I was mistakenly (transitively) importing `subr-x` and `json` before byte-compiling these files.  Here's an updated readout:

### gerrit-rest.el

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
gerrit-rest.el:40:8:Warning: `(username (nth 0 pass-entry))' is a malformed
function
gerrit-rest.el:46:18:Warning: reference to free variable `username'
gerrit-rest.el:46:18:Warning: reference to free variable `password'
gerrit-rest.el:106:1:Warning: Unused lexical variable `json-array-type'
gerrit-rest.el:126:1:Warning: Unused lexical variable `json-array-type'

In end of data:
gerrit-rest.el:144:1:Warning: the following functions are not known to be
defined: if-let, password, json-read-from-string, json-encode-list
```
(These are the ones I missed -- you just need to `(require 'json) (require 'subr-x)` at the top of this file.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
No issues found.
```



### gerrit.el

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
2 issues found:

1:0: warning: Including "Emacs" in the package summary is usually redundant.
336:0: error: "magit-open-reviews-issue-section-map" doesn't start with package's prefix "gerrit".
```
The first warning here is new -- the second one we discussed above.

Other static checks:
- gerrit.el#L96: Prefer `https` over `http` (if possible)
- Package-Requires mismatch in _elisp/gerrit-rest.el!

That last "other static check" is important - you have different `Package-Requires` in both of your files, but `gerrit.el` needs to have the complete listing for the `gerrit` package.

**Comment by thisch** [comment]
Thx for helping me fixing the issues with gerrit.el. Let me know if there is an easy way to perform the checks that you run (manually?) in my `.travis-ci.yml` file. 

> That last "other static check" is important - you have different Package-Requires in both of your files, but gerrit.el needs to have the complete listing for the gerrit package.

Does that mean that I have to sync the Package-Requires among all my *.el files?

**Comment by riscy** [comment]
> Does that mean that I have to sync the Package-Requires among all my *.el files?

No, my understanding is just your "main" file which is named after your package (in this case `gerrit.el`) needs to have the `Package-Requires`, and the helper file doesn't need it.  I need to go through MELPA's docs again to see if we write this anywhere, since I don't think this is documented (so definitely not your fault!).

> Let me know if there is an easy way to perform the checks that you run (manually?) in my .travis-ci.yml file.

There might be soon!  I've been working on a ball of python/docker/elisp that installs the package from scratch and automatically (at least without a lot of manual intervention!) runs the common checks and some extra checks in a sandbox.  There are still problems I'm ironing out (as you can see from this PR).

Some of my extra checks might make more sense as a PR to package-lint, but they are almost all brittle regexp checks that don't pay attention to the syntax tree so need to be confirmed manually, e.g.:
```elisp
  (melpazoid-misc "(add-to-list 'auto-mode-alist.*\\$"
                    "Terminate auto-mode-alist entries with \\\\'")
  (melpazoid-misc "This file is part of GNU Emacs."
                    "This statement may not currently be accurate")
  (melpazoid-misc "lighter \"[^ \"]"
                    "Minor mode lighters should start with a space")
```
probably more than you wanted to know. :)

Anyway, this is looking good to merge now.  Thanks a lot!

**Pull request merged**
