### PR TITLE
Add recipe `helm-esa`

### PR DESCRIPTION
**Pull request by masutaka**
### Brief summary of what the package does

`helm-esa.el` is a helm interface for [esa](https://esa.io/) which is a document share service.

### Direct link to the package repository

https://github.com/masutaka/emacs-helm-esa

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly

    ```
    $ emacs -Q -batch --eval '(package-initialize)' -f batch-byte-compile helm-esa.el
    $ echo $?
    0
    ```

- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Looks great, but why does this require `curl`? The default URL facilities in emacs should be able to handle this case, right? Or one of the wrapper libraries like `request`. Relying on `curl` makes this library less portable between operating systems.

**Comment by masutaka** [comment]
Thanks for your review.

I ported it from the following packages:

* https://github.com/masutaka/emacs-helm-hatena-bookmark
* https://github.com/masutaka/emacs-helm-qiita

Then I did not think deeply about using curl.

I will avoid using curl. Should I fix this time?

**Comment by masutaka** [comment]
I've removed `curl` from the requirements using [request.el](https://github.com/tkf/emacs-request).

Could you review, please?
https://github.com/masutaka/emacs-helm-esa

**Comment by riscy** [comment]
Looks great!

**Pull request merged**
