### PR TITLE
Add chinese-pyim-wbdict recipe

### PR DESCRIPTION
**Pull request by tumashu**
### Brief summary of what the package does

Some wubi dicts for chinese-pyim

### Direct link to the package repository

https://github.com/tumashu/chinese-pyim-wbdict

### Your association with the package

I'm  the maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [+] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [+] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by tumashu** [comment]
Wubi is a kind chinese input method which is based the sharp of chinese char.

**Comment by syohex** [comment]
- Why does not it require `chinese-pyim` package as package dependency ? Your package does not work without it at all.
- Why does this package allow byte-compiling ? (`no-byte-compile: t`)

**Comment by tumashu** [comment]
Fixed, thanks!
```
Why does this package allow byte-compiling ? (no-byte-compile: t)
```

**Comment by tumashu** [comment]
This package is just a data package, it can be installed without chinese-pyim. if chinese-pyim has not been installed, this package do nothing but message "you should install chinese-pyim".
```
Why does not it require chinese-pyim package as package dependency ? Your package does not work without it at all.
```

**Comment by purcell** [comment]
> This package is just a data package, it can be installed without chinese-pyim. if chinese-pyim has not been installed, this package do nothing but message "you should install chinese-pyim".

Yes, that's exactly why it should depend on `chinese-pyim`. It's not useful without it.

**Comment by tumashu** [comment]
Fixed

```
Yes, that's exactly why it should depend on chinese-pyim. It's not useful without it.
```

**Comment by purcell** [comment]
Super, thanks.

**Pull request merged**
