### PR TITLE
Add recipe for flow-mode

### PR DESCRIPTION
**Pull request by an-sh**
### Brief summary of what the package does

Major mode for flowtype.org derived from web-mode. Very minimal, but better than nothing.

### Direct link to the package repository

https://github.com/an-sh/flow-mode

### Your association with the package

Maintainer + enthusiastic user. Some code is borrowed from the original [flow-for-emacs](https://github.com/flowtype/flow-for-emacs) snippet, hence the original licence is left intact.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- I have sent PR(https://github.com/an-sh/flow-mode/pull/1), please check it.
- You should use `process-file`(`call-process`) instead of `shell-command`(`shell-command-to-string`) because if `flow-binary` contains spaces, then command is failed.

**Comment by an-sh** [comment]
Thanks for pointing that out, i've rewritten flow iterations using `call-process`.

**Comment by syohex** [comment]
https://github.com/an-sh/flow-mode/blob/9538632fbbed2dea0ab7addfa463db8be6fd3d4a/flow-mode.el#L176-L177

I suppose you should use named function instead of lambda function. Lambda function can not be removed from hook and can be added to hook multiple times.

**Comment by an-sh** [comment]
fixed

**Comment by syohex** [comment]
Merged

**Pull request merged**
