### PR TITLE
Add recipe for screenshot

### PR DESCRIPTION
**Pull request by tecosaur**
### Brief summary of what the package does

 Convenience package for creating images of the current region or buffer.
Requires `imagemagick` for some visual post-processing, and `xclip` for copying images to the clipboard.

### Direct link to the package

https://github.com/tecosaur/screenshot/

### Your association with the package

Maintainer

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Fun! I'd suggest calling this `xscreenshot` since it's not going to work for Windows or MacOS users.

**Comment by tecosaur** [comment]
I've been thinking a bit about this. It would be nice to make this cross-platform, but it seems that isn't realistic given the current reliance on `x-export-frames` (which seems to only work on Linux?). However, despite that function name, this isn't exclusive to X11 (for example, this also works on Wayland with pgtk) --- so I'm not sure that your proposed name change is actually any more fitting (sorry).

**Comment by riscy** [comment]
Ultimately the name change is up to you, but I'd agree with @purcell that a change would be good given that cross-platforming isn't realistic.  Also there is already an older package in the "screenshot" namespace [here](https://github.com/emacsmirror/screenshot.git).  Quick first pass below.

### screenshot.el ###

byte-compile (using Emacs 27.1):
```
screenshot.el:78:11:Warning: assignment to free variable
    `screenshot--tmp-file'
In screenshot-text-upload:
screenshot.el:87:19:Warning: reference to free variable
    `screenshot-text-upload-function'
In screenshot--set-screenshot-region:
screenshot.el:131:9:Warning: assignment to free variable
    `screenshot--first-line-number'
screenshot.el:132:9:Warning: assignment to free variable
    `screenshot--total-lines'
In screenshot--setup-buffer:
screenshot.el:140:34:Warning: reference to free variable `hl-line-mode'
In screenshot--format-text-only-buffer:
screenshot.el:157:32:Warning: reference to free variable
    `screenshot-font-family'
screenshot.el:158:38:Warning: reference to free variable
    `screenshot-font-size'
In screenshot--narrowed-clone-buffer:
screenshot.el:172:30:Warning: reference to free variable
    `screenshot-font-family'
screenshot.el:173:36:Warning: reference to free variable
    `screenshot-font-size'
In screenshot--process:
screenshot.el:184:13:Warning: reference to free variable
    `screenshot-text-only-p'
screenshot.el:191:40:Warning: reference to free variable
    `screenshot-border-width'
screenshot.el:192:28:Warning: reference to free variable
    `screenshot-min-width'
screenshot.el:193:24:Warning: reference to free variable
    `screenshot-max-width'
screenshot.el:194:29:Warning: reference to free variable
    `screenshot--total-lines'
screenshot.el:195:33:Warning: reference to free variable
    `screenshot-truncate-lines-p'
screenshot.el:199:40:Warning: reference to free variable
    `screenshot-line-numbers-p'
screenshot.el:202:25:Warning: reference to free variable
    `screenshot-relative-line-numbers-p'
screenshot.el:203:31:Warning: reference to free variable
    `screenshot--first-line-number'
screenshot.el:206:23:Warning: reference to free variable
    `screenshot--tmp-file'
In screenshot--post-process:
screenshot.el:224:16:Warning: reference to free variable `screenshot-radius'
screenshot.el:225:16:Warning: reference to free variable
    `screenshot-shadow-radius'
screenshot.el:239:21:Warning: reference to free variable
    `screenshot-shadow-color'
screenshot.el:240:21:Warning: reference to free variable
    `screenshot-shadow-intensity'
screenshot.el:242:21:Warning: reference to free variable
    `screenshot-shadow-offset-horizontal'
screenshot.el:243:21:Warning: reference to free variable
    `screenshot-shadow-offset-vertical'
screenshot.el:260:1:Warning: Unused lexical argument `args'
In screenshot-save:
screenshot.el:263:3:Warning: reference to free variable `screenshot--tmp-file'
screenshot.el:271:1:Warning: Unused lexical argument `args'
In screenshot-save-as:
screenshot.el:274:3:Warning: reference to free variable `screenshot--tmp-file'
screenshot.el:279:1:Warning: Unused lexical argument `args'
In screenshot-copy:
screenshot.el:284:22:Warning: reference to free variable
    `screenshot--tmp-file'
screenshot.el:297:1:Warning: Unused lexical argument `args'
In screenshot-upload:
screenshot.el:305:102:Warning: reference to free variable
    `screenshot--tmp-file'
In end of data:
screenshot.el:443:1:Warning: the following functions are not known to be
    defined: counsel-fonts, ivy-read
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
screenshot.el:251: Some lines are over 80 columns wide
Warning (emacs): 
screenshot.el:251: Argument `name' should appear (as NAME) in the doc string
Warning (emacs): 
screenshot.el:339: All variables and subroutines might as well have a documentation string
```

package-lint (using version 20200906.512):
- No issues!

### Loadability ###

Verifying ability to #'load each file:
```
Loading screenshot.el
screenshot.el:Error: Emacs 27.1 errored during load
Done.
```
This attempted to load the package in a non-gui Emacs instance -- here's the backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument font unspecified)
  font-get(unspecified :family)
  (symbol-name (font-get (face-attribute 'default :font) :family))
  (closure (t) nil (symbol-name (font-get (face-attribute 'default :font) :family)))()
  funcall((closure (t) nil (symbol-name (font-get (face-attribute 'default :font) :family))))
  eval((funcall #'(closure (t) nil (symbol-name (font-get (face-attribute 'default :font) :family)))))
  custom-initialize-reset(screenshot-font-family (funcall #'(closure (t) nil (symbol-name (font-get (face-attribute 'default :font) :family)))))
  custom-declare-variable(screenshot-font-family (funcall #'(closure (t) nil (symbol-name (font-get (face-attribute 'default :font) :family)))) "Font family to use" :type string :group screenshot)
  eval-buffer(#<buffer  *load*> nil "/workspace/pkg/screenshot.el" nil t)  ; Reading at buffer position 14438                                                                                                                                                     
  load-with-code-conversion("/workspace/pkg/screenshot.el" "/workspace/pkg/screenshot.el" nil nil)
  load("screenshot")
  load-library("screenshot")
  funcall-interactively(load-library "screenshot")
  call-interactively(load-library record nil)
  command-execute(load-library record)
  execute-extended-command(nil "load-library" nil)
  funcall-interactively(execute-extended-command nil "load-library" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by tecosaur** [comment]
Huh. Maybe I'm byte compiling wrong? I called `M-x byte-compile-file` and got no errors. Not sure quite what to do since all the free variables it's complaining about are defined with macros.

I'll fix the documentation errors that popped up with check-doc, but I suspect I'll still have lines over 80 chars.

Adding a quick check for the type of emacs instance (noninteractive, non-gui) seems like it should be fairly straightforward. Thanks for pointing that out.

**Comment by riscy** [comment]
No problem.  Probably you are byte-compiling in an Emacs instance that has already loaded the library.  Flycheck can help with this since it does a cleanroom byte compile, but there are tools like makem.sh and melpazoid that might help.

**Comment by tecosaur** [comment]
We'll have to wait and see, but it looks like Windows support [may come](https://github.com/tecosaur/screenshot/issues/3).

**Comment by riscy** [comment]
That's great if it's on the roadmap.:)  Feel free to ping when ready for another look.

**Comment by tecosaur** [comment]
I've had another look at this, and with how the free variables that it's complaining about in macros being defined in the very same macros I'm at a bit of a loss with how to resolve this.

Example:
```elisp
(screenshot--define-infix
 "-l" "line-numbers-p" "Show line numbers"
 'boolean t
 (not screenshot-line-numbers-p))
```
expands to:
```elisp
(defcustom screenshot-line-numbers-p t
  "Show line numbers"
  :type 'boolean
  :group 'screenshot)
(transient-define-infix screenshot--set-line-numbers-p ()
  "Set `screenshot--theme' from a popup buffer."
  :class 'transient-lisp-variable
  :variable 'screenshot-line-numbers-p
  :key "-l"
  :description "Show line numbers"
  :argument "--line-numbers-p"
  :reader (lambda (&rest _) (not screenshot-line-numbers-p)))
 ```
 
 If anyone has any ideas on this, that would be much appreciated.

**Comment by riscy** [comment]
Sorry it has taken me so long to reply.  As far as I can tell, the byte-compiler isn't unhappy with anything within the `screenshot--define-infix` macro so I wasn't able to quickly understand your description of the issue above.  But I believe the compiler warnings around macros can sometimes misreport line numbers.

I think what might be helpful is if you clean up as many of the byte-compile warnings as you feasibly can (e.g., ``` screenshot.el:75:11:Warning: assignment to free variable `screenshot--tmp-file' ``` just needs a `defvar`) and then that will make it easier to focus in on the tricky one.

**Comment by riscy** [comment]
I'll mark this one awaiting upstream til we hear back.

**Comment by tecosaur** [comment]
Mmm, I've been rather busy over the past few weeks and that's unlikely to change any time soon.
You can consider all my PRs on the backburner, but not forgotten abuot.

**Comment by tarsius** [comment]
I am closing this pull-request because it is over a year old now. That doesn't mean that we won't add this to Melpa, just that you have to ask us to reopen it once you are ready.

**Comment by tecosaur** [comment]
> You can consider all my PRs on the backburner, but not forgotten about.

Just for the record, as of some time in the last year or two, I no longer plan to proceed with this or #7326.

**Comment by tarsius** [comment]
Thanks for letting us know!

**Pull request closed without merging**
