### PR TITLE
Add rufo

### PR DESCRIPTION
**Pull request by aleandros**
### Brief summary of what the package does

Automatically (or manually) formats ruby and enhanced-ruby buffers with [rufo](https://github.com/asterite/rufo)

### Direct link to the package repository

https://github.com/aleandros/emacs-rufo

### Your association with the package

Creator + maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. #4829 provides a similar package, which has more idiomatic code (partly because it was mostly copied from elsewhere).

This package is smaller (great!) but also quite unidiomatic, and it needs a fair bit work before it could be included here:
- Typo on the very first line
- `add-hook` shouldn't be called unconditionally: provide a minor mode that users can enable themselves, by adding it to their `ruby-mode-hook` if desired.
- Don't use `?` as a function suffix: `-p` is idiomatic in elisp.
- Don't execute `which` to find `rufo`: there's a function called `executable-find` which does this.
- Don't modify the *global* version of `before-save-hook` and then check that it's a `ruby-mode` file: instead, modify the local version of that hook so that you don't have to check! See the `LOCAL` argument to `add-hook`.
- Don't modify other modes' keymaps: put them in the keymap for your own minor mode. Also, `C-c f` is [reserved for end-user customisation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html).

**Comment by purcell** [comment]
In the end I merged the Rufo package submitted in #4829, which is also (now) called `rufo.el` -- I suggest you give that package a try and see how it works for you. I'm sure the author would be happy to have help.

**Comment by aleandros** [comment]
Thanks a lot for the feedback! Not everyone is as thorough or takes the time to explain these things.

**Comment by purcell** [comment]
No worries. I figure that the more people know about the kind of things I mentioned, the better off the community will be, and the less I'll be the one giving tips. :-)

**Comment by aleandros** [comment]
We need "Effective Elisp" to be a thing.

**Pull request closed without merging**
