### PR TITLE
Rename flow-mode into flow-minor-mode.

### PR DESCRIPTION
**Pull request by an-sh**
### Brief summary of what the package does

A package rename, based on users feedback/patches https://github.com/an-sh/flow-minor-mode/issues/2 . Also deletes the old one to free the name, not sure how to do it correctly.

### CODE REVIEW

**Comment by syohex** [comment]
Could you  add `:old-names` attribute and squash commits ?

**Comment by purcell** [comment]
It's not clear to me that you'd need to rename the whole package, but it's fine if that's your preference. But if so, then `flow-minor-mode.el` should now `provide` the new feature name, not `flow-mode`, and you'll need to fix the header and footer comments there which currently still mentions `flow-mode.el`.

**Comment by an-sh** [comment]
I've renamed everything to flow-minor-mode, also can i keep `flow-` prefix for package symbols or should i rename them too?

**Comment by purcell** [comment]
> I've renamed everything to flow-minor-mode, also can i keep flow- prefix for package symbols or should i rename them too?

If you're renaming to "free up" the `flow-mode` name for someone else to use, you should really leave the `flow-` prefix for them, and use `flow-minor-` or `flow-minor-mode-` here.

**Comment by an-sh** [comment]
Sorry for the delay, prefix should be fixed by now.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
