### PR TITLE
Add elisp-docstring-mode

### PR DESCRIPTION
**Pull request by Fuco1**
#### elisp-docstring-mode

A simple major-mode for editing content of Emacs Lisp docstrings.  Very useful in combination with [string-edit](https://github.com/magnars/string-edit.el).

#### Features

Provides font-lock.  In combination with string-edit, there is support for automatic escaping and unascaping of quotes.

### Direct link to the package repository

https://github.com/Fuco1/elisp-docstring-mode

### Your association with the package

Author/Maintainer

### CODE REVIEW

**Comment by syohex** [comment]
- There is no autoload cookie(https://github.com/Fuco1/elisp-docstring-mode/pull/1)

**Comment by Fuco1** [comment]
@syohex Thanks, merged!

**Comment by purcell** [comment]
Cool, thanks. PS, `font-lock-defaults` is always buffer-local, so you can simply `setq` it.

**Comment by tarsius** [comment]
But except for being noise, making it explicitly buffer local, isn't really an issue. So I am merging now. You should still change that though.

**Comment by purcell** [comment]
Sorry, I think I thought I had clicked to merge already.

**Comment by Fuco1** [comment]
@purcell huh? But it is merged, not sure what you mean.

Thanks for the tip though, I'll change it when I get back home :)

**Comment by purcell** [comment]
> uh? But it is merged, not sure what you mean.

@tarsius had commented above that he was merging this. I was saying that I thought I had already done that. :-)

In any case, we all got the right outcome!

**Pull request merged**
