### PR TITLE
Expropriate package-build from melpa

### PR DESCRIPTION
**Pull request by dickmao**
In the twin interests of reduced upkeep and separation of concerns, one might consider getting the package-build subtree out of the melpa repo.

Cask, for all its warts, manages the package-build library, and github action caches ensure the CI doesn't reinstall package-build any more than necessary.

### CODE REVIEW

**Comment by milkypostman** [comment]
I think the point of Cask is only for the case of CI. For people that checkout MELPA to add recipes, the subtree is valuable. But that is just my understanding. @tarsius can confirm.

**Comment by tarsius** [comment]
It was @purcell's idea to use a subtree. I originally wanted to "manually" use `package.el` to install `package-build.el`, but I agree that using a subtree is better because it is very robust. We very much want this to be robust; at least on the server. Too much could go wrong otherwise and it could be difficult to investigate random breakage causes by `package-install` somehow going wrong.

(*Locally* I have added `config.mk` with content `LOAD_PATH = ~/.emacs.d/lib/package-build`, which is preferable *for development*.)

We shouldn't replace the subtree with something involving Cask.

This commit makes other changes and maybe those are good but I have only glimpsed at them for now because this commit does too many related but still distinct things at once. It should be split up for into multiple commits. For example, it updates the used Ubuntu version and we might want to do that even if we end up not doing any of the other things proposed here. It would help to have a commit that only updates Ubuntu and its commit message should explain what we gain by doing (just) that.

**Comment by dickmao** [comment]
> It should be split up into multiple commits

I can see we'll never meet eye-to-eye on the [bureaucracy vs. progress](https://github.com/auto-complete/auto-complete/pull/510) tradeoff.  To ensure a commit is logically decoupled from others is a sisyphean, negative-sum task, to which no software developer with any respect for his own time would accede.  Melpa certainly moves faster, with less pointless ideological handwringing, than GNU Elpa but sadly not fast enough for me.

I suppose a similar gatekeeping response awaits #7464 .  I shall wait for its explicit manifestation, and similarly close it.

**Comment by tarsius** [comment]
> I can see we'll never meet eye-to-eye

That's fine.

> no software developer with any respect for his own time

Just don't.

A major reason why you should make it easy for other people to review your changes is that as a result they have to spend less time on doing so. By outright refusing to do so, you demonstrate that you value your time much more than the time of your fellow developers. This is disrespectful and the fact that you intentionally throw in explicit insults like the bureaucracy accusation just solidifies that perception.

> I suppose a similar gatekeeping response awaits #7464 .

That's right. It is quite possible that that contains some useful stuff but figuring out whether that is the case is a time investment which may or may not pan out. This is a risk we are taking time and time again, but when a contributor refuses to lessen our workload/risk even when asked, then the reasonable thing to do is to reject the contribution.

**Comment by dickmao** [comment]
> when a contributor refuses to lessen our workload/risk

Allow me to state an obvious solution to this troublemaker.  You could add him as a maintainer.  While I quite obviously do not meet your technical standards (and the judgment is mutual), you'd be hard pressed to find someone with more free time as I.

**Comment by purcell** [comment]
> I suppose a similar gatekeeping response awaits #7464 .

I appreciate your enthusiasm and I'd like to share some thoughts.

It's not gatekeeping if we don't _unconditionally_ take potentially-helpful contributions in whatever form they were offered. Being correct and clever are insufficient to get the best results in this industry: working skillfully with others and understanding their context is necessary, in order to get consensus and buy-in. Whatever infrastructure is set up around MELPA, the maintainers need to be able to understand, operate, maintain and extend it. Yes, there are aspects of MELPA that need significant work, and contributions can help with this, but there is a total cost of ownership to consider.

Adding maintainers to compensate is not automatically a solution, and it's not a question of their available free time or technical prowess. MELPA is a team effort, not just a github repo with committers. Our maintainers work well together, prioritising the long term health of the project, and are specifically people who support the community aspects of MELPA and its established welcoming and helpful culture.

I am sympathetic if you think we're moving too slowly. However, smooth and slow is often better than fast and bumpy. I think the approach has been borne out over the 8-9 years that MELPA has grown into what it is.

**Comment by alphapapa** [comment]
> However, smooth and slow is often better than fast and bumpy. I think the approach has been borne out over the 8-9 years that MELPA has grown into what it is.

Yes, as they say in some other fields: Slow is smooth; smooth is fast.

As well, everyone does this in spare time, largely because it's enjoyable to collaborate on a project that gives back to the community.  What's the point of being antagonistic toward one another and making it no-longer enjoyable?  The people are even more valuable than the code they produce and the service they provide.

**Pull request closed without merging**
