### PR TITLE
Add recipe for symbols-outline

### PR DESCRIPTION
**Pull request by liushihao456**
### Brief summary of what the package does

Display symbols (functions, variables, etc) in a side window.

### Direct link to the package repository

https://github.com/liushihao456/symbols-outline.el

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`symbols-outline-ctags.el` with byte-compile using Emacs 28.1:
```
symbols-outline-ctags.el:164:22: Warning: Unused lexical argument `proc'
```

`symbols-outline-ctags.el` with checkdoc 0.6.2:
```
symbols-outline-ctags.el:51: Documentation strings should not start or end with whitespace
symbols-outline-ctags.el:51: First sentence should end with punctuation
symbols-outline-ctags.el:145: All variables and subroutines might as well have a documentation string
```

`symbols-outline-ctags.el` with package-lint 20230806.1331:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```

`symbols-outline-ctags.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- symbols-outline-ctags.el#L61: Could this point/point-max comparison use `eobp`?
```

`symbols-outline-follow-mode.el` with package-lint 20230806.1331:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```

`symbols-outline-lsp.el` with byte-compile using Emacs 28.1:
```
symbols-outline-lsp.el:38:1: Error: Cannot open load file: No such file or directory, lsp-mode
```
I think a `Package-Requires` is missing here.

`symbols-outline-lsp.el` with checkdoc 0.6.2:
```
symbols-outline-lsp.el:41: All variables and subroutines might as well have a documentation string
symbols-outline-lsp.el:71: All variables and subroutines might as well have a documentation string
symbols-outline-lsp.el:92: All variables and subroutines might as well have a documentation string
symbols-outline-lsp.el:99: All variables and subroutines might as well have a documentation string
```
Note that checkdocs are "within reason".

`symbols-outline-lsp.el` with package-lint 20230806.1331:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```

`symbols-outline-nerd-icon.el` with checkdoc 0.6.2:
```
symbols-outline-nerd-icon.el:114: Documentation strings should not start or end with whitespace
```

`symbols-outline-nerd-icon.el` with package-lint 20230806.1331:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```

`symbols-outline-node.el` with checkdoc 0.6.2:
```
symbols-outline-node.el:124: Argument `ln' should appear (as LN) in the doc string
symbols-outline-node.el:137: First line is not a complete sentence
symbols-outline-node.el:166: All variables and subroutines might as well have a documentation string
```

`symbols-outline-node.el` with package-lint 20230806.1331:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```

`symbols-outline-svg-icon.el` with checkdoc 0.6.2:
```
symbols-outline-svg-icon.el:49: All variables and subroutines might as well have a documentation string
symbols-outline-svg-icon.el:58: All variables and subroutines might as well have a documentation string
symbols-outline-svg-icon.el:67: All variables and subroutines might as well have a documentation string
symbols-outline-svg-icon.el:71: All variables and subroutines might as well have a documentation string
symbols-outline-svg-icon.el:84: All variables and subroutines might as well have a documentation string
symbols-outline-svg-icon.el:88: All variables and subroutines might as well have a documentation string
symbols-outline-svg-icon.el:125: All variables and subroutines might as well have a documentation string
symbols-outline-svg-icon.el:131: All variables and subroutines might as well have a documentation string
symbols-outline-svg-icon.el:223: Documentation strings should not start or end with whitespace
```

`symbols-outline-svg-icon.el` with package-lint 20230806.1331:
```
1 issue found:
6:0: error: Package-Requires outside the main file have no effect.
```

`symbols-outline-svg-icon.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- symbols-outline-svg-icon.el#L98: It's safer to sharp-quote function names; use `#'`
- symbols-outline-svg-icon.el#L158: It's safer to sharp-quote function names; use `#'`
```

`symbols-outline.el` with byte-compile using Emacs 28.1:
```
symbols-outline.el:534:36: Warning: the function `symbols-outline-ctags-fetch'
    is not known to be defined.
```

`symbols-outline.el` with checkdoc 0.6.2:
```
symbols-outline.el:76: First line is not a complete sentence
symbols-outline.el:112: All variables and subroutines might as well have a documentation string
symbols-outline.el:121: All variables and subroutines might as well have a documentation string
symbols-outline.el:202: All variables and subroutines might as well have a documentation string
symbols-outline.el:209: All variables and subroutines might as well have a documentation string
symbols-outline.el:212: All variables and subroutines might as well have a documentation string
symbols-outline.el:408: Argument `node' should appear (as NODE) in the doc string
symbols-outline.el:455: All variables and subroutines might as well have a documentation string
symbols-outline.el:492: All variables and subroutines might as well have a documentation string
symbols-outline.el:504: All variables and subroutines might as well have a documentation string
```

`symbols-outline.el` with package-lint 20230806.1331:
```
1 issue found:
1:0: warning: The package summary is too long. It should be at most 60 characters.
```

`symbols-outline.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- symbols-outline.el#L354: Could this point/point-max comparison use `eobp`?
- symbols-outline.el#L221: Consider `beginning-of-line`
- symbols-outline.el#L244: Consider `beginning-of-line`
- symbols-outline.el#L265: Consider `beginning-of-line`
- symbols-outline.el#L285: Consider `beginning-of-line`
- symbols-outline.el#L304: Consider `beginning-of-line`
- symbols-outline.el#L351: Consider `beginning-of-line`
- symbols-outline.el#L488: Consider `beginning-of-line`
- symbols-outline.el#L343: Consider `end-of-line`
```

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

**Comment by liushihao456** [comment]
Thanks for the feedback. I have fixed these issues. Could you try again?

BTW, when I run package-lint, I can't get the error "Package-Requires outside the main file have no effect." The command I used was `package-lint-current-buffer`. Maybe there's some other command that lints the entire package directory?

**Comment by riscy** [comment]
Looks great - thank you for accommodating everything.

(I am setting a variable called `package-lint-main-file` (q.v.) which specifies the main file and enables checks like that.)

Before I hit merge, your `;;; Commentary` looks like a stub, i.e.
```
;;; Commentary:
;;
;; --------------------------------------

;;; Usage:
;;
;; --------------------------------------
```
and to improve the state of the MELPA index we should probably fill that in with something, if you intended to.

**Comment by liushihao456** [comment]
Thanks for your suggestions! I have filled in the commentary sections. Please check it out. :)

**Comment by riscy** [comment]
Cool stuff.  Merging, and welcome to MELPA. :)

**Pull request merged**
