### PR TITLE
Add recipe for EKG package.

### PR DESCRIPTION
**Pull request by ahyatt**
### Brief summary of what the package does

This is a note-taking app, where the notes are tagged, some notes can have other useful metadata, and it's all stored in a sqlite database, via the `triples` package.

### Direct link to the package repository

https://github.com/ahyatt/ekg

### Your association with the package

I am the sole author.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Very quick first pass --

`ekg.el` with byte-compile using Emacs 28.1:
```
ekg.el:863:37: Warning: reference to free variable `hl-line-face'
In end of data:
ekg.el:944:37: Warning: the function `iso8601-valid-p' is not known to be
    defined.
ekg.el:704:9: Warning: the function `emacsql' is not known to be defined.
ekg.el:700:18: Warning: the function `sqlite-execute' is not known to be
    defined.
```
The compiler can be pacified about a free variable with e.g. `(defvar hl-line-face)` -- if appropriate.  The missing iso function requires a `(require 'iso8601)`, and so forth.

`ekg.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ekg.el#L3: Have you done the paperwork to assign this copyright?
- ekg.el#L286: Lighter should start with a space
- ekg.el#L309: Lighter should start with a space
```
I ask about line 3 because many authors do this by mistake; the copyright is yours unless you've signed it over.  Those lighters should also probably not *contain* spaces, since spaces are used to delimit lighters in the modeline, typically.

- GNU General Public License v2.0 (via API) -- prefer 3.0 for reasons explained [here](https://github.com/johannes-mueller/company-wordfreq.el/issues/6).

**Comment by ahyatt** [comment]
Done.  Sorry, I had run byte compilation but forgot to run it on a emacs started with `-Q`.  But, I haven't fixed the `emacssql` and `sqlite`, in which we use only one (so I requiring them is not a good idea).  I realize it's weird, but it's something already discussed with emacs maintainers (see https://lists.gnu.org/archive/html/emacs-devel/2022-11/msg00140.html).

I upgraded to GPL 3.  I changed the copyright to be to myself.  Although I have FSF copyright assignment papers submitted, I don't intend to require it of my contributors, so I think it's best to have my own copyright.  Let me know if I'm not understanding how it works, which is probable.

**Comment by riscy** [comment]
> Although I have FSF copyright assignment papers submitted, I don't intend to require it of my contributors

I'm not a lawyer or a software license expert by any stretch, but I often see multiple copyright lines in Elisp files covering various authors' contributions.

> I haven't fixed the emacssql and sqlite, in which we use only one (so requiring them is not a good idea)

This makes sense, and I read that response - in this case you should pacify the byte-compiler with a `declare-function` form for each of these.  This way your users won't see the byte-compiler warning them even though nothing is actually wrong.  E.g.
```elisp
(declare-function emacsql "ext:emacsql.el")
```
or similar.

There are still these small nags in `ekg.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ekg.el#L290: Lighter should start with a space
- ekg.el#L313: Lighter should start with a space
```

**Comment by ahyatt** [comment]
Thank you for the suggestions, I've committed fixes for these issues.

**Comment by riscy** [comment]
Thanks for accommodating - here's the latest:

`ekg.el` with byte-compile using Emacs 28.1:
```
ekg.el:716:18: Warning: the function `sqlite-execute' is not known to be
    defined.
```
should be similarly pacified with a `declare-function`.

**Comment by ahyatt** [comment]
This should be fixed, thanks.

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
