### PR TITLE
Added recipe for guess-language.el

### PR DESCRIPTION
**Pull request by tmalsburg**
### Brief summary of what the package does

Emacs minor mode that detects the language of what you're typing. Automatically switches spell checker and typo-mode. Supports multiple languages per document.  Uses a robust algorithm that works with many languages and requires only 30--40 characters of text.  Currently supported languages are: Czech, Dansk, Dutch, English, Finnish, French, German, Italian, Norwegian, Polish, Portuguese, Russian, Slovak, Slovenian, Swedish.

### Direct link to the package repository

https://github.com/tmalsburg/guess-language.el

### Your association with the package

I'm the (sole) author and maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- You should not change value of other packages globally([here](https://github.com/tmalsburg/guess-language.el/blob/6014777758e2150707e788cccbc8922a0353c7dd/guess-language.el#L124-L125)). You should use `let` or make them as buffer local variable.
- You should use buffer local argument of `add-hook` and `remove-hook` instead of `make-variable-buffer-local` at [here](https://github.com/tmalsburg/guess-language.el/blob/6014777758e2150707e788cccbc8922a0353c7dd/guess-language.el#L127)

And I have sent PR about packaging. https://github.com/tmalsburg/guess-language.el/pull/1

**Comment by tmalsburg** [comment]
Thank you very much, @syohex. I addressed your points and improved some other things as well.

**Comment by purcell** [comment]
Looks good, thanks. Go ahead and add a `;;;###autoload` for the `define-minor-mode` form too -- it'll make things more convenient for users!

**Comment by tmalsburg** [comment]
Thank you very much, Steve.  Will add the autoload.

**Pull request merged**
