### PR TITLE
Add pack recipe

### PR DESCRIPTION
**Pull request by 10sr**
### Brief summary of what the package does

Pack and unpack archive files

### Direct link to the package repository

https://github.com/10sr/pack-el

### Your association with the package

The maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by Silex** [comment]
What's the difference with dired `Z` key (`dired-do-compress`)?

**Comment by 10sr** [comment]
`dired-do-compress` creates *compressed* files, where `pack-dired-dwim` creates *archive* files.
For example, when you mark two files named `a.txt` and `b.txt` in dired buffer and call these functions:

- `dired-do-compress` will create two files named `a.txt.gz` and `b.txt.gz`
- `pack-dired-dwin` will create one file like `a.txt.tgz` (this name is a default: this command will prompt you to input name for the archive file before creating it)

**Comment by purcell** [comment]
Thanks! Nice work, and I'll go ahead and merge it now.

(PS. typo: elemetn)

**Comment by 10sr** [comment]
Thanks!

**Pull request merged**
