### PR TITLE
yasnippet-lean: Snippets for the Lean theorem prover

### PR DESCRIPTION
**Pull request by cipher1024**
### Brief summary of what the package does

Snippets for the Lean theorem prover

### Direct link to the package repository

https://github.com/leanprover-community/yasnippet-lean

### Your association with the package

Simon is the maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Very minor:
- 13: If possible, prefer `https://` to `http://`
- 32: If possible, prefer `https://` to `http://`

But this looks very tidy and good to merge!

**Comment by cipher1024** [comment]
Thanks for the note! I just made the fix. Is it worth updating the recipe?

**Comment by riscy** [comment]
Nah, you need to update the recipe here on MELPA - it rarely needs to be updated.  You might want to keep a develop branch where you push changes like these (and other) and merge them when you're ready to bump your the `Version: x` in your package docstring.

**Comment by purcell** [comment]
> Nah, you [don't] need to update the recipe here on MELPA - it rarely needs to be updated. You might want to keep a develop branch where you push changes like these (and others) and merge them when you're ready to bump your `Version: x` in your package docstring.

I'd advise against this, tbh: just work on `master` and tag with version numbers as needed. This fits with how MELPA and MELPA Stable (respectively) are meant to work.

**Pull request merged**
