### PR TITLE
add elfeed-autotag recipe

### PR DESCRIPTION
**Pull request by paulelms**
### Brief summary of what the package does

Elfeed-autotag overlays configuration in elfeed-org style on elfeed-protocol feeds

### Direct link to the package repository

https://github.com/paulelms/elfeed-autotag

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- here's a very quick first pass of the checklist.  Package-lint is right to complain about the name prefixes here:

### elfeed-autotag.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
20 issues found:
46:0: error: "pvv-elfeed-autotag-tree-id" doesn't start with package's prefix "elfeed-autotag".
51:0: error: "pvv-elfeed-autotag-ignore-tag" doesn't start with package's prefix "elfeed-autotag".
56:0: error: "pvv-elfeed-autotag-files" doesn't start with package's prefix "elfeed-autotag".
61:0: error: "pvv-elfeed-autotag-protocol-used" doesn't start with package's prefix "elfeed-autotag".
69:0: error: "pvv-elfeed-autotag-check-configuration-file" doesn't start with package's prefix "elfeed-autotag".
75:0: error: "pvv-elfeed-autotag-is-headline-contained-in-elfeed-tree" doesn't start with package's prefix "elfeed-autotag".
85:0: error: "pvv-elfeed-autotag-import-trees" doesn't start with package's prefix "elfeed-autotag".
99:0: error: "pvv-elfeed-autotag-convert-tree-to-headlines" doesn't start with package's prefix "elfeed-autotag".
129:0: error: "pvv-elfeed-autotag-filter-relevant" doesn't start with package's prefix "elfeed-autotag".
139:0: error: "pvv-elfeed-autotag-cleanup-headlines" doesn't start with package's prefix "elfeed-autotag".
144:0: error: "pvv-elfeed-autotag-import-headlines-from-files" doesn't start with package's prefix "elfeed-autotag".
157:0: error: "pvv-elfeed-autotag-convert-headline-to-tagger-params" doesn't start with package's prefix "elfeed-autotag".
167:0: error: "pvv-elfeed-autotag-export-entry-title-hook" doesn't start with package's prefix "elfeed-autotag".
174:0: error: "pvv-elfeed-autotag-export-feed-url-hook" doesn't start with package's prefix "elfeed-autotag".
181:0: error: "pvv-elfeed-autotag-export-headline-hook" doesn't start with package's prefix "elfeed-autotag".
194:0: error: "pvv-elfeed-autotag-export-titles" doesn't start with package's prefix "elfeed-autotag".
206:0: error: "pvv-elfeed-autotag-filter-entry-title-taggers" doesn't start with package's prefix "elfeed-autotag".
213:0: error: "pvv-elfeed-autotag-filter-feed-url-taggers" doesn't start with package's prefix "elfeed-autotag".
220:0: error: "pvv-elfeed-autotag-filter-subscriptions" doesn't start with package's prefix "elfeed-autotag".
234:0: error: "pvv-elfeed-autotag-process" doesn't start with package's prefix "elfeed-autotag".
```

**Comment by paulelms** [comment]
> Package-lint is right to complain about the name prefixes here

Thanks for the review! I've seen this, but I'm afraid the elfeed-autotag prefix might cause conflicts. If it matters, I will rename the package tomorrow.

**Comment by paulelms** [comment]
Renamed everything according to convention.

**Comment by riscy** [comment]
Thanks for accommodating that, I realize it can feel constraining.  I think `elfeed-autotag---import-trees` should only have a double-dash in it (there's one byte-compile nag to that effect) but besides that this looks good and should be a quick merge after that.

**Comment by paulelms** [comment]
Sorry for that, fixed @riscy

**Comment by riscy** [comment]
Looks good to me, and should be useful.  Thanks!

Non-blocking but I notice the `error` on line 75 might just be a `user-error` (the former can open backtraces which may not be what you want).

**Pull request merged**
