### PR TITLE
Add geben-helm-projectile package

### PR DESCRIPTION
**Pull request by ahungry**
I am the author.

This provides functions for integration between geben mode and helm-projectile, in particular, allowing project specific files to be opened using the helm-projectile interface, instead of manually traversing file paths from the default geben-open-file command.

Project page is at:
https://github.com/ahungry/geben-helm-projectile

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Pending https://github.com/ahungry/geben-helm-projectile/pull/1.

**Comment by purcell** [comment]
Also, please remove the `:files` spec from the recipe, since it is redundant.

**Comment by ahungry** [comment]
@purcell changes are all set now (next up, updating geben)

**Comment by purcell** [comment]
Super, thanks.

**Pull request merged**
