### PR TITLE
Add recipe for org-timeblock

### PR DESCRIPTION
**Pull request by ichernyshovvv**
### Brief summary of what the package does

Interactive SVG calendar for orgmode tasks

### Direct link to the package repository

https://github.com/ichernyshovvv/org-timeblock

### Your association with the package

Author and maintainer.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback.

The only problem I have with package-lint is that it does not support read-symbol-shorthands and therefore I get a lot of errors of the type `"function/variable" doesn't start with package's prefix`
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

> The only problem I have with package-lint is that it does not support read-symbol-shorthands

It may feel inconvenient, but a simple and fair way to prevent namespace collisions across MELPA (and hopefully elsewhere) is to ask that the package, variable names, and function names all use the same prefix (regardless of `read-symbol-shorthands`).  In very rare cases I would make exceptions to this rule (e.g. backward compatibility with a package predating this rule) -- and `package-lint` has some of these exceptions built into it.

Also, avoid specifying `:branch` except in unusual cases; MELPA prefers to read from your *default* branch, whatever its name.

**Comment by ichernyshovvv** [comment]
> It may feel inconvenient, but a simple and fair way to prevent namespace collisions across MELPA (and hopefully elsewhere) is to ask that the package, variable names, and function names all use the same prefix

What type of collisions are you talking about? The only problem with shorthands I see is that I could accidentally use a symbol from other package with the same prefix as the shortened prefix of my package. Are there any other drawbacks of using shorthands?

> Also, avoid specifying :branch except in unusual cases; MELPA prefers to read from your default branch, whatever its name

Thanks, fixed that.

**Comment by riscy** [comment]
That's exactly the kind of collision.  You might use a symbol from another package with the same prefix, another package might use the same shorthand as you, or another package may call itself `ot`.

**Comment by riscy** [comment]
Friendly ping. :)  You should also check out the conversation in https://github.com/melpa/melpa/pull/8744 re: dealing with these shorthands -- some people with more knowledge than I possess have chimed in.

**Comment by ichernyshovvv** [comment]
Sorry for the delay, have been busy.

> You might use a symbol from another package with the same prefix

Yes, but I don't use a package with that prefix :). 

> another package might use the same shorthand as you

I see no problem here. There's no collision also, because shortened prefix will be properly converted according to what's declared in file-local variables section. Shorthands only work at the file level.

> or another package may call itself ot.

That's not a problem unless I want to use that package inside org-timeblock.el file. Shorthands take effect only inside the file they've been declared in (via file-local variables mechanism), as I already mentioned.

**Comment by ichernyshovvv** [comment]
Anyway, if I want to merge the package into Org core (which still supports Emacs 27, shorthands are available since 28), I have to get rid of shorthands.

**Comment by ichernyshovvv** [comment]
Hi. I removed shorthands, and now all the issues seems to be fixed.

**Comment by riscy** [comment]
Thanks for accommodating - consistent and easy prefixes really make things way easier for everyone.  Merging this, and welcome to MELPA. :)

**Pull request merged**
