### PR TITLE
Add authinfo-color-mode

### PR DESCRIPTION
**Pull request by tecosaur**
### Brief summary of what the package does

Just makes authinfo files that little bit more colorful.
### Direct link to the package repository

https://github.com/tecosaur/authinfo-color-mode
### Your association with the package

Author & maintainer
### Relevant communications with the upstream package maintainer

na
### Checklist

Please confirm with `x`:
- [x]  The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x]  I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x]  I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x]  My elisp byte-compiles cleanly
- [x]  `M-x checkdoc` is happy with my docstrings
- [x]  I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ]  I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tecosaur** [comment]
First submission to melpa (I was going to PR to Doom, Henrik told me to melpa, I said "surely it's to small", he said nah, here we are). By the way, I have two other packages which may be of interest:
 - https://github.com/tecosaur/org-pandoc-import
 - https://github.com/tecosaur/lexic

Let me know if you'd like to see those too.

**Comment by purcell** [comment]
Thanks! I took a very quick look... Why is this not simply a new mode derived from `authinfo-mode`, but with some additional font-locking? It seems like with the approach you've chosen, you're having to reinvent the password hiding stuff from the builtin version. There must be a better way.

I guess my other observation is that your suggestion of overriding the built-in mode by using advice is not good practice: `auto-mode-alist` entries are for handling this.

> Let me know if you'd like to see those too.

That's not for us to decide! If you feel they're generally useful to others, and in a state ready to share, then feel free.

**Comment by tecosaur** [comment]
Hi Steve! Thanks for getting back to me so quickly.

> Why is this not simply a new mode derived from `authinfo-mode`?

-   `authinfo-mode` hardcodes the face used for the passwords.
-   I wanted to use a different face, the functions are fairly short, so I just copied them over and modified them
-   If you know of a better way, please let me know :)

> overriding the built-in mode by using advice is not good practice: auto-mode-alist entries are for handling this.

-   I originally just used an auto-mode entry
-   The advice is so that &ldquo;authinfo&rdquo; babel code blocks get highlighting from, and org-edit-special uses `authinfo-color-mode` instead of `authinfo-mode`
-   Once again, if you know of a better way, please let me know

Lastly, @syohex spotted some minor omissions in the file which have been fixed via a PR (thanks!).

**Comment by riscy** [comment]
Here's a quick pass on the checklist.

### authinfo-color-mode.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
authinfo-color-mode.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
authinfo-color-mode.el:31: You should have a section marked ";;; Code:"
Warning (emacs): 
authinfo-color-mode.el:50: Argument `start' should appear (as START) in the doc string
Warning (emacs): 
authinfo-color-mode.el:64: Argument `overlay' should appear (as OVERLAY) in the doc string
```

package-lint (using version 20200906.512):
```
4 issues found:
1:0: error: Package should have a ;;; Commentary section.
1:0: warning: The package summary is too long. It should be at most 60 characters.
10:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
69:0: error: "authinfo-hide-passwords" doesn't start with package's prefix "authinfo-color".
```
Maybe the last of these is a special case?

Other possible lints:
- authinfo-color-mode.el#L5: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- authinfo-color-mode.el#L27: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading authinfo-color-mode.el
Done.
```

### Package ###

- Avoid specifying `:branch` except in unusual cases in your recipe

**Comment by riscy** [comment]
Friendly ping. :)  Maybe you are waiting for a reply on your end before addressing the checklist items, in which case I can take another look.

**Comment by tecosaur** [comment]
Thanks for the ping :slightly_smiling_face: this got a bit forgotten about with some other things I was working on (e.g. https://github.com/tecosaur/ox-ansi).

I'm also considering putting this as a patch to emacs-devel and seeing if there's any interest.

**Comment by riscy** [comment]
Right on.  I'll leave the "awaiting-upstream" label on this for now, but of course feel free to follow up when ready.

**Comment by tecosaur** [comment]
Patch made, linking here in case it gets merged and I forget to follow up here: https://lists.gnu.org/archive/html/emacs-devel/2020-12/msg01531.html

**Comment by tecosaur** [comment]
It's been merged :)

**Comment by riscy** [comment]
Excellent, congrats. :)

**Pull request closed without merging**
