### PR TITLE
Add reciepe to include drone ci launcher

### PR DESCRIPTION
**Pull request by olymk2**
### Brief summary of what the package does

Runs drone exec with in current project, drone is a ci service like jenkins it uses docker and lets you run locally with the same environment
### Direct link to the package repository

https://github.com/olymk2/emacs-drone
### Your association with the package

I have created this package, its my first go at coding in lisp
### Relevant communications with the upstream package maintainer

**None needed**
### Checklist
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by olymk2** [comment]
Any comments welcome, I don't mind admitting i am new to emacs and lisp in particular :)

**Comment by syohex** [comment]
- Package description is nonsense
- No package dependency header
 - However I think it is enough to use `locate-dominating-file` instead of `projectile` function
- No `provide`
- No autoload cookie
- Use setting `let` + `default-directory` instead of `cd directory;` in shell command

**Comment by olymk2** [comment]
Thanks for the suggestions @syohex I have a question regarding locate-dominating-file

from what i can tell locate-dominating-file searches all descendants all the way back to root i am wondering if this is perhaps not desired behaviour it could run a file not related to the project, perhaps this does not really matter but i am interested in your thoughts, it would be nice to not rely on projectile.

I will address the other issues I think i have found out everything i need to make those changes.

**Comment by olymk2** [comment]
@syohex I was thinking about the project root issue some more and decided your correct so i have pushed with the amendments.

https://github.com/olymk2/emacs-drone/commit/bdcc68b93aeadb8395ec32211748ea58b1d3e392

Anything else need addressing, I am making these changes in another much larger package and integrating tests so this will be helpful when i put in my next PR.

**Comment by olymk2** [comment]
Just updated the description, your correct it was nonsense i think i misunderstood that part and changed the summary previously.

now change the description in the header [history](https://github.com/olymk2/emacs-drone/commits/master)

**Comment by purcell** [comment]
Thanks. Quick feedback from me now:
- You should either do nothing (or call `error`) when `dc-drone-root` returns `nil`, because the following code makes no sense otherwise.
- `shell-command` is easy, but it's meant for end users, and isn't a great way to run specific processes like this because they end up competing for the user's `*Shell command*` buffer. Better would be to handle `*drone*` buffer(s) yourself, use `compilation-start` etc. After all, you will probably also want to detect when the process fails so that you can report it when that happens.

So in its current form, I'm not sure there's enough here to be worth distributing, but with a little more polish that would change.

**Comment by olymk2** [comment]
@purcell great thanks for those tips i will go and research and implement those changes :)

**Comment by olymk2** [comment]
@purcell I have made these changes based on your comments, let me know if that what you intended ?

https://github.com/olymk2/emacs-drone/commit/b849f315fd8ae2f9b9ac8b7e569aa40f1e0d9adb

Also a general question, does melpa add packages from a specific commit ?
Just curious what happens if i updated my repo after something is included in melpa ?

**Comment by purcell** [comment]
That wasn't quite what I meant. I've sent you some fixes in https://github.com/olymk2/emacs-drone/pull/1.

MELPA will re-build whenever you make further commits. If you tag your repo with a version number, corresponding packages will also appear on stable.melpa.org.

**Pull request merged**
