### PR TITLE
Add recipe for casual-agenda

### PR DESCRIPTION
**Pull request by kickingvegas**
### Brief summary of what the package does

Casual Agenda is a Transient-based user interface for Org Agenda.

### Direct link to the package repository

https://github.com/kickingvegas/casual-agenda

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I'm seeing something unexpected when checking `load` on each file:
```
Loading casual-agenda.el
  casual-agenda.el:Error: Emacs 29.4:
  (invalid-slot-name "#<transient-prefix transient-prefix-157ade83abb6>" :refresh-suffixes)
Loading casual-agenda-version.el
Loading casual-agenda-utils.el
Loading casual-agenda-settings.el
```
Is this possibly due to recent changes in transient?

**Comment by kickingvegas** [comment]
@riscy Thanks for reviewing. You will need to update your local version of Transient, which in a later release added support for `:refresh-suffixes`. This should be picked up by installing the casual-agenda [dependency](https://github.com/kickingvegas/casual-agenda/blob/13683a1f12f6623aec5aff0389c8de4388cabef5/lisp/casual-agenda.el#L9) [casual-lib](https://github.com/kickingvegas/casual-lib/blob/db18e23ca60c9b0ba21644d54bb343a1099c6dbb/lisp/casual-lib.el#L9) which picks up Transient >= 0.6.0. that has it.

**Comment by meedstrom** [comment]
Well, it's *supposed* to pick up the new transient.el, but theory may not be practice :-)  When I use Elpaca, it's actually among the ignored dependencies for some reason.  So I have to do this to get the new version:

    (setq elpaca-ignored-dependencies
          (delq 'transient elpaca-ignored-dependencies))

**Comment by riscy** [comment]
For what it's worth, I am seeing an issue similar to @meedstrom's, where my sandbox ran `(package-install (cadr (assq 'casual-lib package-archive-contents)))` and it didn't lead to transient being updated, even though I can see it in the casual-lib dependencies.

But also more generally -

> You will need to update your local version of Transient [...] This should be picked up by installing the casual-agenda

I think this should be done on your side without relying on implicit transitive dependencies.

**Comment by kickingvegas** [comment]
@riscy so will flattening transitive dependencies in `casual-agenda.el` so that a newer version of `transient` and its dependencies are specified the guidance here? I'm ok with doing this, but @meedstrom seems to suggest even doing that will not enforce an update of `transient`. 

My local setup has the latest version of `magit` installed which picks up `transient` and its dependencies, masking this issue for Casual packages reliant on recent `transient` features.

**Comment by meedstrom** [comment]
I mentioned this issue in the Elpaca repo. The maintainer told me something I had apparently forgotten, but Elpaca will indeed warn the user if a newer version of Transient is required. So you need not worry about that.

**Comment by kickingvegas** [comment]
Another concern: can updating `transient` without updating `magit` break an older version of `magit`?

**Comment by meedstrom** [comment]
Yes, that depends on how well magit handles that :) But that's magit's problem, not yours, I think.

In general, that possibility is why Elpaca forces the user to make a choice. But it seems to have been status quo until now with other package managers (at least with Straight and package.el) to just install the newest version of everything.  So it is actually the way of doing things with which I'd expect the fewest issues.  We don't have an ecosystem yet where people routinely pin old versions of many packages, because that causes more breakage than it prevents (cf. why Melpa Stable is unpopular).

**Comment by kickingvegas** [comment]
@meedstrom thanks for the input. Will move forward with flattening transitive dependencies.

**Comment by riscy** [comment]
> will flattening transitive dependencies in casual-agenda.el so that a newer version of transient and its dependencies are specified the guidance here? I'm ok with doing this, but @meedstrom seems to suggest even doing that will not enforce an update of transient.

Short answer is no, it won't.  I mentioned it because in general I think it's a good idea for independent packages to list their dependencies explicitly (even though I'm fully aware you own the entire dependency tree here, and it is technically all correctly done).

Re: transient itself, I haven't traced this start to finish, but I'll try to explain my understanding of what could be happening.  package-install (and maybe other package managers inherit/share this behavior) doesn't rigorously check version numbers.  If package A depends on package B 2.0, but package B 1.0 is already installed, package B won't necessarily get updated when installing package A.

This seems to frequently cause issues when package B comes with Emacs.  For example, this behavior was causing me some grief [a few years ago](https://github.com/riscy/melpazoid/commit/07648c6c16fc59b5cceb87f28f057442afeef282) where a new package would strongly depend on a recent version of `org`, but org would not be automatically updated from the Emacs built-in version when I ran a package-install on it.  These builtin versions can actually be quite old, so them not getting auto-updated causes issues.  With transient's recent big update, and the fact that it's included with Emacs, there may be similar issues.

**Comment by riscy** [comment]
(I should add my knowledge here might be out of date and @meedstrom might have a clearer picture of what's going on.)

**Comment by kickingvegas** [comment]
@riscy okay then I suppose the guidance is:

1. Do not make code changes as the dependencies are specified correctly even though the package manager implementation will not as of this date honor the specification. 

2. Document as part of the install instructions the need to update `transient`.

**Comment by meedstrom** [comment]
I don't know much either. :) I haven't used package.el since 2015... But that's quite concerning as a packager:

> If package A depends on package B 2.0, but package B 1.0 is already installed, package B won't necessarily get updated when installing package A.

So I wonder how informative package.el's warning message is, or even if it has any warning message?  Maybe when we make a package that depends on a fresh Transient it'd make sense to run `display-warning` if the installed version is too low.

Hijacking the thread a bit now, but trying to figure out how to get the currently installed version of Transient.  Furthest I got so far was this, but it requires the `epl` library:

```elisp
(defun my-pkg-version (lib)
  (require 'epl)
  (string-join (mapcar #'number-to-string
                       (epl-package-version (epl-package-from-file
                                             (find-library-name lib))))
               "."))
```

**Comment by kickingvegas** [comment]
@riscy Created new release Casual Agenda v1.0.2 with updated documentation. 

https://github.com/kickingvegas/casual-agenda?tab=readme-ov-file#a-note-on-package-dependencies

**Comment by kickingvegas** [comment]
I'd further add, if the specification is legal and the implementation does not support it, then there is a problem with the implementation.

**Comment by meedstrom** [comment]
Or a problem with what's considered a legal spec :)  They have to match up, certainly.  

I'm not one to denigrate what other devs are thinking, but it seems some code (e.g. package.el) is written under the hope that a versioning infrastructure resembling other languages will turn up later.  In the meantime, things are fragile for users not running the latest Emacs and everyone's master branch.

There could be some logic to it I'm not getting though.  It's true that it's not so often that a problem shows up (though without telemetry, who can really know).  Just us packagers who have to check the versions of builtins and do `display-warning` so the user knows to upgrade.

**Comment by meedstrom** [comment]
Adding magit wouldn't upgrade transient, would it?

**Comment by kickingvegas** [comment]
@meedstrom if `package-install-upgrade-built-in` is `t`, then targeting a version of `magit` that uses a more recent version of `transient` should update both. At least that is my understanding. The concern is that those two packages are tightly bound, and I want to avoid the situation of updating only `transient` and breaking an older version (typically the build-in) of `magit.

**Comment by kickingvegas** [comment]
Actually got clarification, `magit` is *not* built-in so concern of requiring a update of it is relaxed. Keeping the dependency only on updating `transient`.

**Comment by kickingvegas** [comment]
Updated INSTALL instructions to reflect understanding of `package-install-upgrade-built-in` to support updating built-in packages. Please review **Casual Agenda [v1.0.3](https://github.com/kickingvegas/casual-agenda/releases/tag/1.0.3)** for publishing on MELPA.

**Comment by kickingvegas** [comment]
For reference, link to documentation on package-upgrade behavior on built-in packages. 

https://www.gnu.org/software/emacs/manual/html_node/emacs/Package-Installation.html

**Comment by riscy** [comment]
> Looking at “Customize Group: Package”, it seems that there is a variable package-install-upgrade-built-in that was introduced in 29.1. By default it is set to nil

Thank you hugely for this - I was unaware of this variable!  Digging around in this also revealed a bug with load-path management in my melpazoid scripts, so I apologize for any time this one wasted.  Merging this now.

**Comment by kickingvegas** [comment]
@riscy Thanks much! TBH, I suspect that knowledge of this variable is not widespread amongst Emacs users who been using it before 29.1. FWIW I wrote a blog post reflecting on this. http://yummymelon.com/devnull/updating-built-in-emacs-packages.html

**Comment by meedstrom** [comment]
> Hijacking the thread a bit now, but trying to figure out how to get the currently installed version of Transient. Furthest I got so far was this, but it requires the `epl` library:

Update:  I found a way you can query a builtin package version: it's recorded in a variable `package--builtin-versions`. Funnily, Transient in particular is missing from that list until Emacs 30, but you can copy-paste this hack:

https://github.com/progfolio/elpaca/blob/213a72646e024af007c610ea7574dc82e992637f/elpaca.el#L197-L205

... and... add an entry for 29.4.

**Pull request merged**
