### PR TITLE
Updated logpad.el

### PR DESCRIPTION
**Pull request by dertuxmalwieder**
I got rid of Bitbucket. No code changes since the initial commit.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
Could you do something to prove that you are the same person as **tux_** on bitbucket?

* https://bitbucket.org/tux_/logpad.el says that the repository now lives at https://code.rosaelefanten.org/logpad.el.

* https://code.rosaelefanten.org/logpad.el tells the user to "Grab it on MELPA!" ...

* ... however it also says "This page was generated in about 0.003s by **Fossil** 2.8 [f8d7f76bfd] **2019-02-20** 15:01:32" ...

* ... so this would have given an attacker a large time frame to take over this package.

Can you modify the first page (or else the second) to say that this request is legit?

**Comment by dertuxmalwieder** [comment]
The first one is generated automatically. The second one is the Fossil build date... it will be changed when my server has Fossil 2.9.

You could compare the code...?

**Comment by dertuxmalwieder** [comment]
https://bitbucket.org/tux_/itsreallyme/

Here you go

**Comment by tarsius** [comment]
Thanks!

**Pull request merged**
