### PR TITLE
Add company-statistics

### PR DESCRIPTION
**Pull request by raxod502**
### Brief summary of what the package does

> Company-statistics is a global minor mode built on top of the in-buffer completion system company-mode. The idea is to keep a log of a certain number of completions you choose, along with some context information, and use that to rank candidates the next time you have to choose — hopefully showing you likelier candidates at the top of the list.

### Direct link to the package repository

https://github.com/company-mode/company-statistics

### Your association with the package

I am a very enthusiastic user. `company-statistics` is already on GNU ELPA, it would make it easier for everyone if it were on MELPA as well.

### Relevant communications with the upstream package maintainer

**None needed** (see https://github.com/company-mode/company-statistics/issues/9)

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ ] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### FYI

I haven't so far been able to figure out the MELPA build process, and `package-lint` doesn't work for me, but I can't imagine there would be any problems with `company-statistics` since it's already on GNU ELPA. (But what do I know—if this is a problem let me know.)

### CODE REVIEW

**Comment by syohex** [comment]
There are following byte-compile warnings.

```
company-statistics.el:116:1:Warning: Unused lexical argument ‘option’
company-statistics.el:165:1:Warning: Unused lexical argument ‘cand’
company-statistics.el:215:1:Warning: Unused lexical argument ‘manual’
company-statistics.el:225:1:Warning: Unused lexical argument ‘cand’
```

If those variables are surely unused, please prepend `_` to them like `_option` for suppressing byte-compile warnings.

**Comment by ksjogo** [comment]
What is the advantage of also having it in melpa?

**Comment by raxod502** [comment]
From https://github.com/company-mode/company-statistics/issues/9:

> AFAIK this is the only package I use that I need GNU ELPA for. I ran into trouble when I tried to switch over my entire Emacs configuration to load packages with [quelpa](https://github.com/quelpa/quelpa) (actually [quelpa-use-package](https://github.com/quelpa/quelpa-use-package)). Everything worked seamlessly, since quelpa draws recipes from MELPA, except for `company-statistics`, where I had to write my own recipe.
>
> Not exactly hard, but why not make it more convenient for everyone? :)

**Comment by purcell** [comment]
Thanks, sorry for the slow response. Busy end of year here.

**Pull request merged**
