### PR TITLE
New package ox-leanpub

### PR DESCRIPTION
**Pull request by zzamboni**
### Brief summary of what the package does

Org-mode export backends to produce books in the correct structure and format for publication with [Leanpub](https://leanpub.com/).

### Direct link to the package repository

https://gitlab.com/zzamboni/ox-leanpub

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
I'm aware the `org-` community have defined `ox` as an accepted abbreviation of `org-export`, but your function/variable names don't begin with `org-export` -- I'd encourage just naming your files and recipe `org-leanpub`.

A quick pass in the meantime (all of the package-lint noise is of course related to the above):

### ox-leanpub-book.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200419.406):
```
11 issues found:
9:0: error: Package-Requires outside the main file have no effect.
90:0: error: "org-leanpub-book-manuscript-dir" doesn't start with package's prefix "ox-leanpub".
94:0: error: "org-leanpub-book-resources-dir" doesn't start with package's prefix "ox-leanpub".
99:0: error: "org-leanpub-book-images-dir" doesn't start with package's prefix "ox-leanpub".
107:0: error: "org-leanpub-matter-tags" doesn't start with package's prefix "ox-leanpub".
110:0: error: "org-leanpub-book-setup-menu-markdown" doesn't start with package's prefix "ox-leanpub".
125:0: error: "org-leanpub-book-setup-menu-markua" doesn't start with package's prefix "ox-leanpub".
142:0: error: "org-leanpub-book--outfile" doesn't start with package's prefix "ox-leanpub".
148:0: error: "org-leanpub-book--add-to-bookfiles" doesn't start with package's prefix "ox-leanpub".
167:0: error: "org-leanpub-book--process-chapter" doesn't start with package's prefix "ox-leanpub".
226:0: error: "org-leanpub-book-export" doesn't start with package's prefix "ox-leanpub".
```

Suggestions/experimental static checks:
- ox-leanpub-book.el#L222: No `format` required; messages are already f-strings
- ox-leanpub-book.el#L292: No `format` required; messages are already f-strings
- ox-leanpub-book.el#L15: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### ox-leanpub-markdown.el ###

byte-compile-file (using Emacs 26.3):
```
ox-leanpub-markdown.el:431:1:Warning: the function `org-make-tag-string' is
    not known to be defined.
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
ox-leanpub-markdown.el:167: Lisp symbol `org-md-headline' should appear in quotes
```

package-lint-current-buffer (using version 20200419.406):
```
22 issues found:
10:0: error: Package-Requires outside the main file have no effect.
81:0: error: "org-leanpub-markdown--attribute-line" doesn't start with package's prefix "ox-leanpub".
122:0: error: "org-leanpub-markdown--chomp-end" doesn't start with package's prefix "ox-leanpub".
128:0: error: "org-leanpub-markdown-table" doesn't start with package's prefix "ox-leanpub".
144:0: error: "org-leanpub-markdown-table-row" doesn't start with package's prefix "ox-leanpub".
149:0: error: "org-leanpub-markdown-table-cell" doesn't start with package's prefix "ox-leanpub".
154:0: error: "org-leanpub-markdown-latex-fragment" doesn't start with package's prefix "ox-leanpub".
164:0: error: "org-leanpub-markdown-headline-without-anchor" doesn't start with package's prefix "ox-leanpub".
205:0: error: "org-leanpub-markdown-headline" doesn't start with package's prefix "ox-leanpub".
212:0: error: "org-leanpub-markdown-inner-template" doesn't start with package's prefix "ox-leanpub".
235:0: error: "org-leanpub-markdown-footnote-reference" doesn't start with package's prefix "ox-leanpub".
247:0: error: "org-leanpub-markdown-ignore" doesn't start with package's prefix "ox-leanpub".
252:0: error: "org-leanpub-markdown-plain-text" doesn't start with package's prefix "ox-leanpub".
263:0: error: "org-leanpub-markdown-src-block" doesn't start with package's prefix "ox-leanpub".
280:0: error: "org-leanpub-markdown-example-block" doesn't start with package's prefix "ox-leanpub".
289:0: error: "org-leanpub-markdown-fixed-width-block" doesn't start with package's prefix "ox-leanpub".
303:0: error: "org-leanpub-markdown-special-block" doesn't start with package's prefix "ox-leanpub".
328:0: error: "org-leanpub-markdown-link" doesn't start with package's prefix "ox-leanpub".
358:0: error: "org-leanpub-markdown-line-break" doesn't start with package's prefix "ox-leanpub".
366:0: error: "org-leanpub-markdown-export-as-markdown" doesn't start with package's prefix "ox-leanpub".
393:0: error: "org-leanpub-markdown-export-to-markdown" doesn't start with package's prefix "ox-leanpub".
418:0: error: "org-leanpub-markdown-publish-to-leanpub" doesn't start with package's prefix "ox-leanpub".
```

Suggestions/experimental static checks:
- ox-leanpub-markdown.el#L102: It's safer to sharp-quote function names; use `#'`
- ox-leanpub-markdown.el#L16: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- ox-leanpub-markdown.el#L27: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### ox-leanpub-markua.el ###

byte-compile-file (using Emacs 26.3):
```
ox-leanpub-markua.el:485:1:Warning: the function `org-make-tag-string' is not
    known to be defined.
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
ox-leanpub-markua.el:171: Lisp symbol `org-md-headline' should appear in quotes
```

package-lint-current-buffer (using version 20200419.406):
```
23 issues found:
9:0: error: Package-Requires outside the main file have no effect.
83:0: error: "org-leanpub-markua--attribute-line" doesn't start with package's prefix "ox-leanpub".
124:0: error: "org-leanpub-markua--chomp-end" doesn't start with package's prefix "ox-leanpub".
132:0: error: "org-leanpub-markua-table" doesn't start with package's prefix "ox-leanpub".
158:0: error: "org-leanpub-markua-latex-fragment" doesn't start with package's prefix "ox-leanpub".
168:0: error: "org-leanpub-markua-headline-without-anchor" doesn't start with package's prefix "ox-leanpub".
209:0: error: "org-leanpub-markua-headline" doesn't start with package's prefix "ox-leanpub".
224:0: error: "org-leanpub-markua-item" doesn't start with package's prefix "ox-leanpub".
246:0: error: "org-leanpub-markua-inner-template" doesn't start with package's prefix "ox-leanpub".
269:0: error: "org-leanpub-markua-footnote-reference" doesn't start with package's prefix "ox-leanpub".
281:0: error: "org-leanpub-markua-ignore" doesn't start with package's prefix "ox-leanpub".
286:0: error: "org-leanpub-plain-text" doesn't start with package's prefix "ox-leanpub".
293:0: error: "org-leanpub-markua-paragraph" doesn't start with package's prefix "ox-leanpub".
302:0: error: "org-markua-get-header-arg" doesn't start with package's prefix "ox-leanpub".
312:0: error: "org-leanpub-markua-src-block" doesn't start with package's prefix "ox-leanpub".
334:0: error: "org-leanpub-markua-example-block" doesn't start with package's prefix "ox-leanpub".
343:0: error: "org-leanpub-markua-fixed-width-block" doesn't start with package's prefix "ox-leanpub".
357:0: error: "org-leanpub-markua-special-block" doesn't start with package's prefix "ox-leanpub".
382:0: error: "org-leanpub-markua-link" doesn't start with package's prefix "ox-leanpub".
412:0: error: "org-leanpub-markua-line-break" doesn't start with package's prefix "ox-leanpub".
420:0: error: "org-leanpub-markua-export-as-markua" doesn't start with package's prefix "ox-leanpub".
447:0: error: "org-leanpub-markua-export-to-markua" doesn't start with package's prefix "ox-leanpub".
472:0: error: "org-markua-publish-to-leanpub" doesn't start with package's prefix "ox-leanpub".
```

Suggestions/experimental static checks:
- ox-leanpub-markua.el#L104: It's safer to sharp-quote function names; use `#'`
- ox-leanpub-markua.el#L15: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### ox-leanpub.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200419.406):
```
1 issue found:
9:23: warning: Use a non-snapshot version number for dependency on "ox-gfm" if possible.
```

Suggestions/experimental static checks:
- ox-leanpub.el#L15: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by riscy** [comment]
I haven't checked, but some of the byte-compile warnings (such as for `org-make-tag-string`) may be due to not having a recent version of org in your Package-Requires -- the latest stable version of Emacs might not come with what you need.

**Comment by zzamboni** [comment]
@riscy thanks for your feedback! I have addressed most of the points and have some further questions:

- ox-leanpub-book.el:
  - [x] ox-leanpub-book.el#L222: No format required; messages are already f-strings
  - [x] ox-leanpub-book.el#L292: No format required; messages are already f-strings
  - [x] ox-leanpub-book.el#L15: Prefer https over http if possible (why?)
- ox-leanpub-markdown.el
  - [x] ox-leanpub-markdown.el:167: Lisp symbol `org-md-headline' should appear in quotes
  - [x] 10:0: error: Package-Requires outside the main file have no effect.
  - [x] ox-leanpub-markdown.el#L102: It's safer to sharp-quote function names; use #'
  - [x] ox-leanpub-markdown.el#L16: Prefer https over http if possible (why?)
  - [x] ox-leanpub-markdown.el#L27: Prefer https over http if possible (why?)
- ox-leanpub-markua.el
  - [x] ox-leanpub-markua.el:171: Lisp symbol `org-md-headline' should appear in quotes
  - [x] 9:0: error: Package-Requires outside the main file have no effect.
  - [x] ox-leanpub-markua.el#L104: It's safer to sharp-quote function names; use #'
  - [x] ox-leanpub-markua.el#L15: Prefer https over http if possible (why?)
- ox-leanpub.el
  - [x] ox-leanpub.el#L15: Prefer https over http if possible (why?)
  - 9:23: warning: Use a non-snapshot version number for dependency on "ox-gfm" if possible.
    - No such version exists - I can only find the snapshot version in `list-packages`.

**Comment by zzamboni** [comment]
@riscy about the naming - I based my names on some of the other `ox-*` packages that already exist, including those included with org-mode. In every `ox-<something>` package, the functions start with `org-<something>`. For example:

- [ox-hugo](https://github.com/kaushalmodi/ox-hugo/blob/master/ox-hugo.el) - functions start with `org-hugo`
- [ox-html](https://code.orgmode.org/bzg/org-mode/src/master/lisp/ox-html.el) - functions start with `org-html`
- [ox-reveal](https://github.com/hexmode/ox-reveal/blob/master/ox-reveal.el) - functions start with `org-reveal`.

My main concern with renaming the package to `org-leanpub` would be to lose discoverability and to diverge from org-mode convention for exporter packages. Having said that, I could be convinced :)

Would keeping the current names be a dealbreaker, given the existence of other packages that follow similar conventions?

Thanks for your feedback.

**Comment by zzamboni** [comment]
Addressed additional warnings
    
- Removed uses of `org-make-tag-string` (which was introduced post-org9.1).
- Added explicit `org` dependency.
- Re-added `Package-Requires` lines in individual package files, to remove package-lint-current-buffer warnings.

**Comment by zzamboni** [comment]
@riscy thanks for the call on `org-make-tag-string`! I am indeed using `org` from git on a day-to-day basis, so I had not realized this function was not available in the latest released version. As it is a simple function and it's only used once in every file, I inlined it and added an explicit dependency on `org`.

**Comment by riscy** [comment]
> I can only find the snapshot version in list-packages

There appears to be a version 1.0 [here](https://stable.melpa.org/#/ox-gfm) but sometimes those can be hard to find -- assuming 1.0 is sufficient for your needs.

> about the naming - I based my names on some of the other ox-* packages that already exist, including those included with org-mode. In every ox-<something> package, the functions start with org-<something>.

You're correct here and my assumption was wrong -- thanks for letting me know.  What I should do on my end is assume that `ox` is a synonym for `org` in package names and be careful of special cases (there is an esoteric `ox` programming language for example, and many other bits of software named "ox" out there because it's such a convenient little prefix but I digress). 

If discoverability by the word "ox" is what you're concerned about, you could rename your functions to use the same name as your package name.  This is (currently) the only way to safely namespace in Emacs, and will prevent someone from inadvertently adding an `org-leanpub` package, which could be very disruptive for users.  Especially these should be fixed since they start with neither prefix:

```
302:0: error: "org-markua-get-header-arg" doesn't start with package's prefix "ox-leanpub".
472:0: error: "org-markua-publish-to-leanpub" doesn't start with package's prefix "ox-leanpub".
```

**Comment by zzamboni** [comment]
Thanks for the feedback - here are my latest updates:

> There appears to be a version 1.0 here but sometimes those can be hard to find -- assuming 1.0 is sufficient for your needs.

I have fixed the version number in the dependency to ox-gfm.

> Especially these should be fixed since they start with neither prefix:
> 302:0: error: "org-markua-get-header-arg" doesn't start with package's prefix "ox-leanpub".
> 472:0: error: "org-markua-publish-to-leanpub" doesn't start with package's prefix "ox-leanpub".

I have fixed these. In particular, I removed the "publish" functions since they were a no-longer-used leftover from early integration with the org-publish mechanism.

About the naming, in the meantime I asked in the org mailing list, and was pointed to some discussion which has happened already for other packages, e.g. see https://github.com/purcell/package-lint/issues/89. Specifically, both the "org-" and "ox-" prefixes have some hardcoded special meanings, as described in that issue and also in https://gitlab.com/oer/org-re-reveal/-/blob/master/ox-re-reveal.el.

Given the existing convention and packages, I would insist in keeping the current names, if it's OK with you.

**Comment by riscy** [comment]
Great, thanks for your patience with me on this one. :)

**Pull request merged**
