### PR TITLE
Add recipe for org-side-tree

### PR DESCRIPTION
**Pull request by localauthor**
### Brief summary of what the package does

Creates a side-window with an outline view of a current Org mode buffer, for easy navigation and manipulation.

### Direct link to the package repository

https://github.com/localauthor/org-side-tree

### Your association with the package

Author/maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

- No byte-compile error! 🎉

`org-side-tree.el` with checkdoc (0.6.2)

```
org-side-tree.el:85: There should be two spaces after a period
org-side-tree.el:98: There should be two spaces after a period
org-side-tree.el:95: There should be two spaces after a period
org-side-tree.el:109: There should be two spaces after a period
org-side-tree.el:108: There should be two spaces after a period
org-side-tree.el:548: There should be two spaces after a period
org-side-tree.el:547: There should be two spaces after a period
org-side-tree.el:499: There should be two spaces after a period
```

`org-side-tree.el` with package-lint (20230905.629)

```
No issues found.
```

**Comment by localauthor** [comment]
> `org-side-tree.el` with checkdoc (0.6.2)
> 
> ```
> org-side-tree.el:85: There should be two spaces after a period
> org-side-tree.el:98: There should be two spaces after a period
> org-side-tree.el:95: There should be two spaces after a period
> org-side-tree.el:109: There should be two spaces after a period
> org-side-tree.el:108: There should be two spaces after a period
> org-side-tree.el:548: There should be two spaces after a period
> org-side-tree.el:547: There should be two spaces after a period
> org-side-tree.el:499: There should be two spaces after a period
> ```

This doesn’t show on my checkdoc, maybe bc of my local settings. Is this convention being insisted on?

Thanks! 🙏

**Comment by jcs090218** [comment]
> This doesn’t show on my checkdoc, maybe bc of my local settings. Is this convention being insisted on?

Yeah, I don't think the convention is applied in MELPA standard. 🤔 Don't worry about it now. `@riscy` should give more details about this. ;)

**Comment by localauthor** [comment]
I’m refactoring the package to work with outline-mode, not just org, which I think will lead to a name change (probably “outline-side-tree”). So I’m going  to close this and resubmit later. Sorry for the noise!

**Comment by riscy** [comment]
Thanks both.  Yes, those checkdoc nags are because of local settings on @jcs090218 's side.  (Also note that these days I've relaxed and consider checkdoc warnings as "within reason" per https://github.com/melpa/melpa/issues/8450 -- so these tend not to be a big deal)

Here's the latest --
`org-side-tree.el` with byte-compile using Emacs 28.1:
```
org-side-tree.el:504:8: Warning: the function `org-fold-show-subtree' is not
    known to be defined.
```
This is because you depend only on Emacs 27.2, but in that version of Emacs (and Emacs 28.1) `org-fold-show-subtree` was not defined.  You can check if Emacs 29.1 is packaging this function, or you can just add a `Package-Requires` dependency on a later version of org that has this function available.

**Comment by localauthor** [comment]
Good catch, thanks. Changed to `org-show-subtree` in latest commit.

**Comment by riscy** [comment]
Thanks!  Merging.

**Pull request merged**
