### PR TITLE
Add le-thesaurus

### PR DESCRIPTION
**Pull request by yitang**
### Brief summary of what the package does

 Query thesaurus.com for synonyms of a given word.

### Direct link to the package repository

https://github.com/AnselmC/le-thesaurus.el

### Your association with the package

I'm helping the author uploading package to Melpa

### Relevant communications with the upstream package maintainer

None

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!

I see there's already a package called `thesaurus` out there that we probably don't want to collide with:

- thesaurus: https://github.com/emacsattic/thesaurus.git (via emacsmirror)

In the meantime, here's a quick first pass --

`thesaurus.el` with byte-compile using Emacs 27.1:
```
thesaurus.el:79:1:Warning: the function `ask-thesaurus-for-synonyms' is not
    known to be defined.
```

`thesaurus.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- thesaurus.el#L46: There is no need to quote lambdas (neither #' nor ')
- thesaurus.el#L26: `lexical-binding` must be on the end of the first line
```

Package and license:
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by yitang** [comment]
renamed the package to le-thesaurus

**Comment by riscy** [comment]
Thanks for the rename!  A couple more quick comments, but this looks good to go:

- Both `progn`s under `le-thesaurus--ask-thesaurus-for-synonyms` look unnecessary; removing them could decrease the level of nesting
- le-thesaurus.el#L62: There is no need to quote lambdas (neither #' nor ')

**Comment by AnselmC** [comment]
Hey @riscy thanks for the review, I incorporated your comments :)

**Comment by yitang** [comment]
as in https://github.com/AnselmC/le-thesaurus.el/issues/19 

somehow the homepage link in the https://melpa.org/#/le-thesaurus is missing an .el in the end. I wonder how can we fix it?

**Comment by riscy** [comment]
Easy fix - it comes from [the URL line](https://github.com/AnselmC/le-thesaurus.el/blob/master/le-thesaurus.el#L4=).

**Comment by yitang** [comment]
thanks it's fixed @riscy

**Pull request merged**
