### PR TITLE
Create recipe for youdotcom

### PR DESCRIPTION
**Pull request by SamuelVanie**
Add recipe for my youdotcom ai search package

### Brief summary of what the package does

Permit to do quick web search using the You.com search api. People no longer need to sort by themselves web search results.

### Direct link to the package repository

https://github.com/SamuelVanie/youdotcom.el

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]
I am the maintainer of the project

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]
**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I notice your code spans way longer than the lowest-common-denominator of 80 characters (I see one line that is 363 characters across) so for friendliness to other devs/maintainability you should rein that in.  Otherwise, a quick first pass --

`youdotcom.el` with package-lint 20231121.1907:
```
10 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
7:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
21:10: error: You should depend on (emacs "24.1") if you need `url'.
22:10: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-lib'.
79:40: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
82:29: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
83:19: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
84:16: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
85:14: error: You should depend on (emacs "25.1") or the compat package if you need `alist-get'.
109:3: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
```

`youdotcom.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- youdotcom.el#L86: It's safer to sharp-quote function names; use `#'`
- youdotcom.el#L17: `lexical-binding` must be on the end of the first line
- youdotcom.el#L3: Have you done the paperwork to assign this copyright?
```

Package and license:
- youdotcom.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by SamuelVanie** [comment]
Good morning !
Thanks for your feedback. All issues should be fixed now.

**Comment by riscy** [comment]
Thank you - much improved!  Here's the latest --

`youdotcom.el` with byte-compile using Emacs 29.1:
```
youdotcom.el:73:14: Warning: Unused lexical argument `status'
```

`youdotcom.el` with checkdoc 0.6.2 (fix *within reason*):
```
youdotcom.el:50: White space found at end of line
```

`youdotcom.el` with package-lint 20231121.1907:
```
1 issue found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
```

**Comment by SamuelVanie** [comment]
Thanks for your review. I've just fixed those ones. Waiting for your next observations. Have a good new year !

**Comment by riscy** [comment]
Looks like that cleans up the checklist.  Taking a look at the code now --

- ⚠️ Of course I'm just noticing this, but are you supplying your own API key in the `youdotcom-api-key` const?  You almost surely don't want to do that. :)  You should regenerate a new API key for yourself after fixing this, if this is the case
- Your `;; SPDX-License-Identifier: GPL-3.0-or-later` is boilerplate that should appear at the top of the file (e.g. with your Author, Version, etc.) not underneath the `;;; Code:` section
- Why would `youdotcom-base-api-endpoint` be customizable?  (Should it not be a `defconst`?)
- The defcustom `youdotcom-number-of-results` is typed as a string, but feels like it should be an `integer` (or even better, use `natnum`).  I also notice this defcustom has `:group 'Youdotcom)` but your group should be lowercased
- The comment `;; user facing functionality prefixed youdotcom-, developer oriented API prefixed youdotcom-` doesn't appear to be needed (everything has the same prefix, doesn't it?)
- In terms of useability, why does `youdotcom-enter` contain `(message "Youdotcom session not started. Call `youdotcom-start` first.")`?  Why couldn't this function just call `youdotcom-start` itself, instead of telling the user to run an interactive command?
- `youdotcom-send-message` contains a huge lambda form that is used as a callback for `youdotcom-send-request` -- just as a matter of style, why not extract this lambda into its own named function?

**Comment by SamuelVanie** [comment]
Thanks for your observations. They made me learn more about elisp. Thanks for the API key, I introduced it by mistakes in my last late commit. Taking into account your observation, it should be better now.

**Comment by riscy** [comment]
Here are a couple popping out of the linters:

`youdotcom.el` with package-lint 20231121.1907:
```
1 issue found:
128:47: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
```

`youdotcom.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- youdotcom.el#L128: Don't set global bindings; tell users how in your `;;; Commentary`.
```

**Comment by SamuelVanie** [comment]
Sorry I fixed that and wasn't added to my commit. It should be okay now

**Comment by riscy** [comment]
Thank you - looks good to merge.

and, welcome to MELPA. :)

**Comment by SamuelVanie** [comment]
Thanks for your help

**Pull request merged**
