### PR TITLE
Add tblui recipe

### PR DESCRIPTION
**Pull request by Yuki-Inoue**
### Brief summary of what the package does

Define tabulated-list ui easily, taking use of magit(-popup) package and tablist package.

Actually, this is currently included in https://github.com/Yuki-Inoue/aws.el , and I'm trying move it out.

### Direct link to the package repository

https://github.com/Yuki-Inoue/tblui.el

### Your association with the package

I'm author

### Relevant communications with the upstream package maintainer

None

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR https://github.com/Yuki-Inoue/tblui.el/pull/2

- There is no autoload cookie
- Please write document for using this package
- There are some byte-compile warnings, please check.

**Comment by Yuki-Inoue** [comment]
- [X] PR Yuki-Inoue/tblui.el#2 : merged

---

- [ ] Document for Package : WIP
- [ ] compile warning : WIP

---

- [ ] autoload cookie

@syohex The main feature this package provides is a macro.  I'm not so much familiar with autoload cookies, but I think it's now possible to define an autoload cookie for functions defined in a macro.  Am I correct or missing some point...?

**Comment by syohex** [comment]
> @syohex The main feature this package provides is a macro. I'm not so much familiar with autoload cookies, but I think it's now possible to define an autoload cookie for functions defined in a macro. Am I mistaken or missing some point...?

You need to put autoload cookie to `defmacro` as below.

https://github.com/emacs-mirror/emacs/blob/0e963201d03d9229bb8ac4323291d2b0119526ed/lisp/calc/calc.el#L3871-L3885

**Comment by Yuki-Inoue** [comment]
@syohex Thanks for the review, all has been reflected.

@purcell Could you accept this PR?

**Comment by syohex** [comment]
Please add docstring to `tblui-define`.

**Comment by Yuki-Inoue** [comment]
@syohex done. thanks for FB.

@purcell I believe It's all ready now.

**Comment by syohex** [comment]
Merged

**Comment by Yuki-Inoue** [comment]
Oh, you are actually the maintainer, didn't knew..

Anyway, thanks for merging!

**Comment by purcell** [comment]
> Oh, you are actually the maintainer, didn't knew..

The team is growing, and I'm grateful for @syohex's help! :-)

**Pull request merged**
