### PR TITLE
Add evil-multiedit recipe

### PR DESCRIPTION
**Pull request by hlissner**
Description: A multiple cursor implementation that integrates `iedit-mode` into `evil-mode`, bringing Sublime Text's (or Atom's) multiple cursor feature to Emacs.

A little hackish, and is 24.5+ only (because I use the new advising library), but I'll iron out some of those kinks over the next week or two. As I'm relatively new to elisp, any advice would be appreciated!

+ [Repository](https://github.com/hlissner/evil-multiedit)
+ I am the author

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, looks good, but you should add `(emacs "24.5")` to the `Package-Requires` list if that version of Emacs is currently required. (I *think* 24.4 also has `nadvice.el` though...)

**Comment by hlissner** [comment]
You're right! In that case do you think a `(emacs "24.4")` dependency is still necessary?

**Comment by purcell** [comment]
Yes, you should add that dependency. :-)

**Comment by hlissner** [comment]
Done!

**Comment by purcell** [comment]
Cool, thanks

**Pull request merged**
