### PR TITLE
Add recipe for org-ai

### PR DESCRIPTION
**Pull request by rksm**
### Brief summary of what the package does

Minor mode for Emacs org-mode that provides access to OpenAI API's.
Inside an org-mode buffer you can use ChatGPT to generate text or DALL-E to generate images.

### Direct link to the package repository

https://github.com/rksm/org-ai

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  You may want to compare this to https://melpa.org/#/gpt and https://melpa.org/#/gptai and #8427; are these existing packages performing similar functions? (I expect a glut of ChatGPT packages coming to Emacs and I want to make sure we're curating/striving for the best.)

A quick first pass in the meantime:

`org-ai.el` with checkdoc 0.6.2:
```
org-ai.el:77: First line is not a complete sentence
```

`org-ai.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- org-ai.el#L354: It's safer to sharp-quote function names; use `#'`
- org-ai.el#L751: It's safer to sharp-quote function names; use `#'`
- org-ai.el#L445: It's safer to sharp-quote function names; use `#'`
- org-ai.el#L394: Could this point/line-end-position comparison use `eolp`?
- org-ai.el#L397: Could this point/point-max comparison use `eobp`?
- org-ai.el#L422: Consider `end-of-line`
- org-ai.el#L621: You can use `not` or `null`
- org-ai.el#L384: This double negation can be collapsed (`not` aliases `null`)
```

`#'load`-check on each file:
```
Loading org-ai.el
  org-ai.el:Error: Emacs 28.1:
  (cl-assertion-failed (equal (let ((test-string "
testing
  [ME]: foo bar baz zorrk
foo
[AI]: hello hello[ME]: ")) (org-ai--collect-chat-messages test-string)) '[(:role user :content "testing
foo bar baz zorrk
foo") (:role assistant :content "hello hello")]))
```

**Comment by rksm** [comment]
Hello, thank you for the feedback. This should be addressed now.

**Comment by rksm** [comment]
Any feedback or progress on this? As for other packages, I'm not aware that any of them provide an org-mode integration or do image generation.

**Comment by riscy** [comment]
Thanks - merging this one.

**Pull request merged**
