### PR TITLE
Add monokai alt theme

### PR DESCRIPTION
**Pull request by dawidof**
### Brief summary of what the package does

Theme with a dark background. Based on sublime monokai theme.

### Direct link to the package repository

https://github.com/dawidof/emacs-monokai-theme

### Your association with the package

creator/maintainer

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Dark monokai theme is already registered in MELPA(https://github.com/sjrmanning/darkokai) and it looks `darkokai` has more faces support rather than this package. What is difference between this package and it ?

**Comment by dawidof** [comment]
@syohex it has different colors 
Darkokai
darkokai
Monokai 2
monokai-2

Yes, `darkokai` has more faces support, but I've just started to develop this theme

**Comment by purcell** [comment]
The naming's a bit odd here: `monokai-2` suggests that this is a successor to `monokai`, but the latter is still maintained, and this is just an alternative version. Why not `monokai-alt-theme` or `monokai-dawidof-theme` instead?

**Comment by dawidof** [comment]
@purcell changed the name to `monokai-alt-theme`

**Comment by purcell** [comment]
Great, thanks. Can you also rename and update the recipe to match please?

**Comment by dawidof** [comment]
@purcell updated :)

**Comment by Silex** [comment]
Ah ha! I might finally be able to get rid of my old unmaintained custom [monokai](https://github.com/Silex/emacs-config/blob/master/config/000_visual.el#L29) crap :+1: 

I'll test your theme and report problems.

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
