### PR TITLE
Add replace-with-inflections, inflection aware `query-replace'

### PR DESCRIPTION
**Pull request by knu**
### Brief summary of what the package does

This package provides `query-replace-names-with-inflections`.

### Direct link to the package repository

https://github.com/knu/replace-names.el

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback

    The main (and only interactive) function does not match (start with) the package name, but I think it's a good package name.

- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings

    Internal functions do not (yet) have docstrings, though.

- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by kaushalmodi** [comment]
What are *inflections*? Can you add a README with examples and may be a screenshot?

**Comment by knu** [comment]
OK, I will.  It uses existing packages named `inflections` and `string-inflection`, so I thought users who'd be search packages related to the idea of inflection should know that already.  It is an implementation of naming conventions adopted in the Ruby on Rails framework and probably well known in the web developers.

**Comment by purcell** [comment]
Thanks! This looks useful. I feel like the package should be renamed to `replace-with-inflections`. `replace-names` is very generic, whereas `replace-with-inflections` has a clear purpose.

**Comment by knu** [comment]
Thanks for the suggestion.  I don't have any plan for the moment to add a function that is unrelated to inflections, so having the word "inflections" in the name would be reasonable.

**Comment by knu** [comment]
Renamed, added README and documentation and updated this PR.

**Comment by purcell** [comment]
Great, thanks!

**Comment by purcell** [comment]
P.S. https://github.com/eschulte/jump.el/pull/13 is now merged, so you can remove the monkey-patch. I'd also suggest renaming the `query-replace-names-with-inflections` command to `query-replace-with-inflections`, or simply `replace-with-inflections`. And `cl` appears not to be necessary.

**Comment by knu** [comment]
Thanks!

**Comment by knu** [comment]
@purcell Thanks, the first two have been addressed.  Regarding `'cl`, it was for using `letf`.  Should I use `cl-letf` via `'cl-lib` instead?

**Comment by purcell** [comment]
Yeah, that'd be great: just require `cl-lib` and add `(cl-lib "0.5")` to the `Package-Requires` header.

**Pull request merged**
