### PR TITLE
New package: tmsu

### PR DESCRIPTION
**Pull request by vifon**
### Brief summary of what the package does

An integration between GNU Emacs and [TMSU](https://tmsu.org/) file tagging system.

### Direct link to the package repository

https://github.com/vifon/tmsu.el

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Very quick first pass --

`ol-tmsu.el` with package-lint 20221003.1636:
```
4 issues found:
9:0: error: Package-Requires outside the main file have no effect.
37:0: error: "org-tmsu-link-regex" doesn't start with package's prefix "tmsu".
46:0: error: "org-tmsu-open-link" doesn't start with package's prefix "tmsu".
57:0: error: "org-tmsu-store-link" doesn't start with package's prefix "tmsu".
```
The prefix errors look like they warrant splitting an `org-tmsu` package out of this one -- a simple and fair way to prevent namespace collisions across MELPA (and hopefully elsewhere) is to ask that the package, variable names, and function names all use the same prefix.  In very rare cases I would make exceptions to this rule (e.g. backward compatibility with a package predating this rule) -- and `package-lint` has some of these exceptions built into it.

`tmsu-dired.el` with package-lint 20221003.1636:
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```
These are minor, but you should be aware if you change the `Package-Requires` in one file and not the other.

**Comment by vifon** [comment]
Thanks for the advice. May I ask you how exactly do you run `package-lint` on the scope of the whole package and not just per buffer? I'm using `package-lint-current-buffer`.

**Comment by vifon** [comment]
I just realized you explicitly mentioned calling the secondary package `org-tmsu`. I believe `ol-tmsu` is consistent with the `org-mode` conventions for packages providing new link types, but `org-tmsu` is consistent with the general namespace conventions. On the other hand I don't see any other packages named according to this `org-mode` convention apart from `ol-notmuch`. Should I go with `org-tmsu` instead after all?

**Comment by riscy** [comment]
I have trouble keeping some of org's conventions fresh in my head, but package-lint accommodates `org-tmsu-` prefixed files in a package called `ol-tmsu`, so I'd say this is up to you.  (Or you might ask the org community for guidance -- they might have strong opinions.)

It looks like there is a dependency between these two packages, e.g. ol-tmsu has `(require 'tmsu-dired)`.  You could set up a `Package-Requires` line in that package and that should resolve things.  Here's a quick pass of both packages at the moment:

`ol-tmsu.el` with byte-compile using Emacs 28.1:
```
ol-tmsu.el:34:1: Error: Cannot open load file: No such file or directory, tmsu-dired
```

`#'load`-check on each file:
```
Loading ol-tmsu.el
  ol-tmsu.el:Error: Emacs 28.1:
  (file-missing "Cannot open load file" "No such file or directory" "tmsu-dired")
```

----------
`tmsu-dired.el` with byte-compile using Emacs 28.1:
```
tmsu-dired.el:50:17: Warning: the function `dired-current-directory' might not
    be defined at runtime.
tmsu-dired.el:47:25: Warning: the function `dired-get-file-for-visit' might
    not be defined at runtime.
```
These look like they may need dired brought in directly.

`tmsu-dired.el` with package-lint 20221003.1636:
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

**Comment by vifon** [comment]
If package-lint is okay with `ol-tmsu`, let's roll with this one.

These errors should be fixed now.

Can you tell me how you invoke package-lint? No matter how I do this, I don't get the results you get. I'd rather make sure everything is fine on my side than have you do this work for me.

**Comment by riscy** [comment]
> Can you tell me how you invoke package-lint? No matter how I do this, I don't get the results you get.

I run my checks through the scripts [here](https://github.com/riscy/melpazoid) (i.e. [here](https://github.com/riscy/melpazoid/blob/master/melpazoid/melpazoid.el#L106)).

Everything looks good to go here.  Thank you!

**Comment by vifon** [comment]
Great, thank you! And thank you for the linting hint, I've managed to run the lint locally by setting `package-lint-main-file` like the function from your link, does.

**Pull request merged**
