### PR TITLE
Add recipe for sql-ts-mode

### PR DESCRIPTION
**Pull request by danilshvalov**
### Brief summary of what the package does

SQL major mode using tree-sitter

### Direct link to the package repository

https://github.com/nverno/sql-ts-mode

### Your association with the package

Enthusiastic user

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Hi @danilshvalov - @nverno is a regular face here, and maybe the author wishes to open this PR when the time is appropriate? (If I'm reading the thread linked correctly)

**Comment by danilshvalov** [comment]
> Hi @danilshvalov - @nverno is a regular face here, and maybe the author wishes to open this PR when the time is appropriate? (If I'm reading the thread linked correctly)

No problem. At the time of creating my PR, the last change was 3 months ago, so I decided that the package was ready for use (according to my feeling, it is).

**Comment by nverno** [comment]
Hey, thanks doing this.

I don't think the package is ready for Melpa yet, though. I'll try to
get it finished and post back here/reopen the pull request.

@danilshvalov maybe close this for now and reopen when it's ready?

**Comment by riscy** [comment]
I will close this for now per @nverno's preferences, but thank you @danilshvalov for being proactive about a high-quality package.

**Pull request closed without merging**
