### PR TITLE
Add recipe for casual

### PR DESCRIPTION
**Pull request by kickingvegas**
### Brief summary of what the package does

Casual is a collection of opinionated Transient-based keyboard-driven user interfaces for various built-in Emacs modes.

The package `casual` itself consolidates a number of packages published on MELPA which will be obsoleted in the near future.

Details of this consolidation is found at the following link:

https://github.com/kickingvegas/casual-suite/discussions/50

### Direct link to the package repository

https://github.com/kickingvegas/casual

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

My only concern is any stateful behavior in MELPA as the package `casual` was originally published (PR #8951) and then later renamed to `casual-calc` (PR #9064).

A subsequent PR #9213 removed the `:old-names` key from the `casual-calc` recipe.

Please let me know if there are any issues and thanks!

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
> which will be obsoleted in the near future.

Do you have a timeline for this?  I think having multiple overlapping recipes in MELPA is okay for a day or a week or so, but if we're looking at a month, maybe we can make things line up neatly to limit user exposure.

No major issues with the code, but I have a couple minor things I can point out from the linters -

- casual-editkit-utils.el#L888: `concat` may be unneeded; `insert` can take multiple arguments
- casual-editkit-utils.el#L889: `concat` may be unneeded; `insert` can take multiple arguments

⸺ `casual-re-builder.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- The `;;; Commentary` for this file is much wider than 80 characters
```

**Comment by kickingvegas** [comment]
@riscy I'm shooting to obsolete the superseded recipes from `casual` about a week or so after this PR is approved. Here's a dependency graph illustrating what I'm thinking.

casual-migration-dependencies-2024-10-19

Will make amendments from your lint warnings.

**Comment by kickingvegas** [comment]
Latest Casual update with amendments for lint warnings.

https://github.com/kickingvegas/casual/releases/tag/2.0.4

**Comment by kickingvegas** [comment]
@tarsius, @riscy thanks much!

**Pull request merged**
