### PR TITLE
add ivy-dired-hisotry

### PR DESCRIPTION
**Pull request by jixiuf**
### Brief summary of what the package does
port https://github.com/jixiuf/helm-dired-history to ivy
[Please write a quick summary of the package.]
remember dired directory you have visited and list them when you open dired buffer.
### Direct link to the package repository
https://github.com/jixiuf/ivy-dired-history

### Your association with the package
maintainer

 

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x] My elisp byte-compiles cleanly
- [ x] `M-x checkdoc` is happy with my docstrings
- [ x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Please run `package-lint` as requested. Also, I don't think you should be enabling `savehist-mode` for the user -- instead, just recommend that users enable it.

**Comment by jixiuf** [comment]
code about savehisto-mode  is removed 

package-lint-current-buffer result:
```
4 issues found: (4 defadvice)

122:1: error: "dired-mark-read-file-name" doesn't start with package's prefix "ivy-dired-history".
128:1: error: "dired-read-dir-and-switches" doesn't start with package's prefix "ivy-dired-history".
137:1: error: "dired-do-compress-to" doesn't start with package's prefix "ivy-dired-history".
172:1: error: "ivy-read-file-name-internal" doesn't start with package's prefix "ivy-dired-history".
```

**Comment by purcell** [comment]
Thanks - those warnings about the `defadvice` are spurious, and I'll fix that in `package-lint`. Re. the first line, you should add a space between `---` and the following text, and also delete the trailing ` .`.

**Comment by jixiuf** [comment]
fixed

**Comment by purcell** [comment]
Super, thanks!

**Pull request merged**
