### PR TITLE
Add surround package

### PR DESCRIPTION
**Pull request by mkleehammer**
### Brief summary of what the package does

Adds vim-surround like functionality for working with pairs of characters like parens, braces, and different quotes.

- Surround text or current symbol with pairs
- Mark / select text within pairs
- Kill text within pairs
- Delete pairs, leaving the text within
- Change pairs, like changing () to {} without disturbing the contents.

It doesn't bind any keys, but does provide a recommended keymap to bind, giving access to all functions with a single key.  The individual functions for these operations also available for binding if preferred.

### Direct link to the package repository

https://github.com/mkleehammer/surround

### Your association with the package

I am the author, maintainer, and enthusiastic user? ;)

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

- No byte-compile error 🎉 

`surround.el` with checkdoc (0.6.2)

```
No issues found.
```

`surround.el` with package-lint (20230905.629)

```
No issues found.
```

Package and license:

- MIT

**Comment by riscy** [comment]
Thank you @mkleehammer.  The code itself looks good, but I've got a couple comments/questions -

First, the `;;; Commentary` for this file is much wider than 80 characters (you look to be wrapping at about 100); the lowest common denominator line-width is 80 characters, which tends to make everyone happy.  And a lot of the tooling downstream from your commentary doesn't know how to "re-wrap" the lines to fit.

Next, have you had a chance to look at packages like [paredit](https://melpa.org/#/?q=paredit) and [lispy](https://melpa.org/#/?q=lispy)?  I'm actually not deeply familiar with either of these, but if you haven't checked them out you may find that what you've implemented exists in a similar form.  (But if not, let me know.)

**Comment by mkleehammer** [comment]
Thanks.  You have a good eye - I use 95 for my personal fill column because that's what used to
print on a laserjet printer in the 90's ;) I've wrapped everything to 80.  (I'll need to do
that to the other packages too.)

I have looked at paredit and lispy and they have very different aims.  Those are idea for sexp
based languages and are for operating on expressions as a whole.  This package emulatees the
populate vim plugin vim-surround by Tim Pope and is more focused on operating on just the pairs
themselves.  I use it many times a day for changing braces to square brackets, selecting text
within quotes, changing double quotes to single when pasting a string into a SQL query, etc.

**Comment by terlar** [comment]
I think there might be room for a smaller package like this, I was using https://github.com/Fuco1/smartparens just for this functionality until recently when I discovered I could achieve the same operations with https://github.com/AmaiKinono/puni which I am using anyways.

**Comment by riscy** [comment]
Thank you both!  The pointer to puni is another great one.

I think because I'm an evil user (and evil-surround exists) I assumed something like this *must* exist for non-evil users somewhere, but I think not.  This looks good to go -- and, welcome to MELPA. :)

**Comment by mkleehammer** [comment]
Thanks!  We appreciate the effort - MELPA has been an amazing addition to the ecosystem.

**Pull request merged**
