### PR TITLE
Add recipe for imgbb.

### PR DESCRIPTION
**Pull request by ecraven**
### Brief summary of what the package does

A simple image uploader for imgbb.com.

M-x imgbb-upload

### Direct link to the package repository

https://github.com/ecraven/imgbb.el

### Your association with the package

I am the author.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

This looks neat.  It seems a shame to limit it to a single site, though.  Have you thought about generalizing it a bit and adding support for other image hosts?

**Comment by ecraven** [comment]
> This looks neat.  It seems a shame to limit it to a single site,
> though.  Have you thought about generalizing it a bit and adding
> support for other image hosts?

This is the only one I found after a few minutes of searching that
allows non-registered uploads. If you can point me towards others where
that works, I can try how easy it would be to add others ;)

Greetings, Peter

**Comment by alphapapa** [comment]
Imgur allows it.

**Comment by ecraven** [comment]
> Imgur allows it.

How? As far as I found out, the actual API is only for registered users.
You can upload via the webinterface, but it is explicitly forbidden to
use that for an automated uploader.

**Comment by alphapapa** [comment]
I see.

**Comment by purcell** [comment]
Hey @ecraven, did you mean to close this? It's taken me a while to get to this, but I'm still happy to add it. I'd have a few little suggestions along the way:

- I think you'd need to depend on (and `require`) the `cl-lib` package for `cl-function`.
- An `;;;###autoload` for the `imgbb-upload` function would be handy for users.

Feel free to reopen if you like.

**Comment by ecraven** [comment]
Fixed those two things.
Not sure how it got closed, I'd still like this merged ;)

**Comment by purcell** [comment]
Great, thanks - merged!

**Pull request merged**
