### PR TITLE
Add recipe for sideline

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Show information on the side

### Direct link to the package repository

https://github.com/emacs-sideline/sideline

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by jcs090218** [comment]
Provide some code for testing purposes, please `eval` the following code:

```elisp
(defun my-sideline-backend (command)
  (cl-case command
    (`candidates
     (list (format "Current line is %s" (line-number-at-pos))
           (format "Current column is %s" (current-column))
           (format "Current point is %s" (point))
           (format "Current buffer is %s" (buffer-name))))))

(setq sideline-backends-right '(my-sideline-backend))
;; Or left
;;(setq sideline-backends-left '(my-sideline-backend))
```

then `M-x sideline-mode`

ezgif-5-f5675f1fee

**Comment by riscy** [comment]
Thanks for this, and for the demo - this is pretty neat.  Some very minor issues:

`sideline.el` with package-lint 20220607.738:
```
1 issue found:
10:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```

`sideline.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- sideline.el#L219: It's safer to sharp-quote function names; use `#'`
```

I'm not entirely sure, but I wonder if some flicker could be alleviated by removing `(sideline--delete-ovs)` from `sideline--post-command`, since `sideline-render` will remove the overlays anyway.  I'd suggest anything you put inside `post-command-hook` to be as fast as possible (so the more you can delay until `sideline-render` such as calculating bounds and such, the better).

**Comment by jcs090218** [comment]
> 10:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.

Is this false positive? I do have `Keywords:` header on top. 😕 

> - sideline.el#L219: It's safer to sharp-quote function names; use `#'`

Done.

> I'm not entirely sure, but I wonder if some flicker could be alleviated by removing (sideline--delete-ovs) from sideline--post-command, since sideline-render will remove the overlays anyway. I'd suggest anything you put inside post-command-hook to be as fast as possible (so the more you can delay until sideline-render such as calculating bounds and such, the better).

I think flickers were caused the bound check, I have improved it by checking the `(point)` now. We do need to delete overlays in `post-command-hook` or else overlays will hang there for a short time since `sideline` are using `sideline--delay-timer` to delay rendering.

**Comment by jcs090218** [comment]
This package uses many functions from Emacs 29 or above. So I am closing this and open with another PR after Emacs 29 is released! Sorry for the noise!

**Comment by jcs090218** [comment]
Please ignore my previous error. I was wrong about the versioning! 😅

**Comment by riscy** [comment]
Thanks for accommodating --

> Is this false positive? I do have Keywords: header on top. 😕

It's advising you to look at that variable (`finder-known-keywords`) and to include at least one "standard" keyword from that list, if you're going to have keyword metadata.  But if your keyword is just going to be "sideline", I'd just drop that line entirely since it isn't adding anything.

Also wrt metadata, your summary line "Show informations on the side" should be written "Show information on the side".

And your `;;; Commentary` should typically not just repeat your summary line but provide additional context.  Mention for example that it follows your cursor around, what its entrypoints are like how to enable it, whether/how it can be customized, etc.

Some ultra minor stuff:
- sideline.el#L343: Consider `end-of-line`
- previouse -> previous (a few instances)

**Comment by jcs090218** [comment]
Everything should be fixed by now! Thanks for the review!

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
