### PR TITLE
Add scroll-on-drag

### PR DESCRIPTION
**Pull request by ideasman42**
### Brief summary of what the package does

Interactive scrolling, which allows both very fast & slow scrolling based on mouse motion w/ non-linear scaling.
Also has the ability to cancel the scroll action on Escape.

### Direct link to the package repository

https://gitlab.com/ideasman42/emacs-scroll-on-drag

### Your association with the package

Author/maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd>:
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
No issues! 🎊

<kbd>M-x byte-compile-file</kbd>:
Per CONTRIBUTING.org, consider using lexical binding
(The following assumes lexical binding is enabled)
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
No issues! 🎉

-------
- [#L154](https://github.com/ideasman42/emacs-modal-scroll/blob/master/modal-scroll.el#L154): Don't quote lambas; this prevents them from being compiled
- [#L155](https://github.com/ideasman42/emacs-modal-scroll/blob/master/modal-scroll.el#L155): It's beneficial to sharp-quote functions; use `'#`
- [#L44](https://github.com/ideasman42/emacs-modal-scroll/blob/master/modal-scroll.el#L44): Closing parentheses are usually gathered together on one line
- [#L45](https://github.com/ideasman42/emacs-modal-scroll/blob/master/modal-scroll.el#L45): Closing parentheses are usually gathered together on one line
- [#L85](https://github.com/ideasman42/emacs-modal-scroll/blob/master/modal-scroll.el#L85): Closing parentheses are usually gathered together on one line
- ...
- [#L22](https://github.com/ideasman42/emacs-modal-scroll/blob/master/modal-scroll.el#L22): Prefer `https` over `http` (if possible)

**Comment by ideasman42** [comment]
@riscy thanks for review, all issues should be handled now.

**Comment by muffinmad** [comment]
Maybe readme must be little edited:
> there was no quick way to scroll at varied speeds

See the `mouse-wheel-scroll-amount` variable. It allows to map the modifier key to the amount to scroll.

**Comment by ideasman42** [comment]
> Maybe readme must be little edited:
> 
> > there was no quick way to scroll at varied speeds
> 
> See the `mouse-wheel-scroll-amount` variable. It allows to map the modifier key to the amount to scroll.

Replaced text with "highly varied", since you can scroll 1s, 10s or 1000s of lines with this package.

**Comment by ideasman42** [comment]
- Renamed to `scroll-by-drag` since this is more descriptive.
- Moved to gitlab.

**Comment by purcell** [comment]
Thanks! Some notes:

- Prefer `(zerop x)` to `(eq 0 x)`, e.g. [here](https://gitlab.com/ideasman42/emacs-scroll-on-drag/blob/6cf8c0d81eee8a48d734f6e728bae0f6eaf70586/scroll-on-drag.el#L81)
- Don't place `(` ([or `'`!)](https://gitlab.com/ideasman42/emacs-scroll-on-drag/blob/6cf8c0d81eee8a48d734f6e728bae0f6eaf70586/scroll-on-drag.el#L39) on their own lines. This isn't community style.
- [`x-pointer-shape`](https://gitlab.com/ideasman42/emacs-scroll-on-drag/blob/6cf8c0d81eee8a48d734f6e728bae0f6eaf70586/scroll-on-drag.el#L388) isn't a standard Emacs var on all GUI platforms. On MacOS, for example, it's not defined.
- `scroll-on-drag` only adds `(interactive)` to `(scroll-on-drag-internal)`. Why not just make `scroll-on-drag-internal` interactive, and rename it to `scroll-on-drag`?

These aren't blockers to merging, though, so you can investigate them offline in due course.

**Comment by ideasman42** [comment]
Thanks for the review, addressed all issues (x-pointer-shape checks it's bound-p first).

**Pull request merged**
