### PR TITLE
Add recipe for evil-smart-input-source

### PR DESCRIPTION
**Pull request by laishulu**
### Brief summary of what the package does

Switch input source for Emacs/evil smartly.

### Direct link to the package repository

https://github.com/laishulu/evil-smart-input-source

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Skimming the README, is this related to changing the language input for the keyboard automatically?  If so, that's a very cool idea, but I was a bit confused at first by "Automatically switch input method for evil." (I was thinking of normal vs. insert mode).  Could that be clarified?

In the meantime, all of the packaging looks good, but here's a quick run over the checklist:

### evil-smart-input-source.el ###

byte-compile-file (using Emacs 26.3):
```
evil-smart-input-source.el:138:5:Warning: `(quote mac-input-source)' is a
    malformed function
evil-smart-input-source.el:138:5:Warning: `(function (lambda nil (string-trim
    (shell-command-to-string evil-smart-input-source--macism))))' is a
    malformed function
In end of data:
evil-smart-input-source.el:231:1:Warning: the following functions are not
    known to be defined: evil-normal-state-p, evil-visual-state-p,
    evil-motion-state-p, evil-operator-state-p, ,, mac-select-input-source,
    string-trim
```
Some of these seem to indicate some syntactical errors (actually line 35 is `(define-namespace evil-smart-input-source-`) -- others seem to point to needing to `(require 'evil)`, which you would then also need to add to your `Package-Requires`.

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200313.2338):
```
24 issues found:
1:0: error: package.el cannot parse this buffer: Package lacks a file header
5:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
37:0: error: "ENGLISH" doesn't start with package's prefix "evil-smart-input-source".
38:0: error: "OTHER" doesn't start with package's prefix "evil-smart-input-source".
40:0: error: "-english-pattern" doesn't start with package's prefix "evil-smart-input-source".
43:0: error: "-other-pattern" doesn't start with package's prefix "evil-smart-input-source".
46:0: error: "-blank-pattern" doesn't start with package's prefix "evil-smart-input-source".
49:0: error: "-english-input-source" doesn't start with package's prefix "evil-smart-input-source".
52:0: error: "-other-input-source" doesn't start with package's prefix "evil-smart-input-source".
55:0: error: "-macism" doesn't start with package's prefix "evil-smart-input-source".
58:0: error: "-do-get-input-source" doesn't start with package's prefix "evil-smart-input-source".
64:0: error: "-do-set-input-source" doesn't start with package's prefix "evil-smart-input-source".
70:0: error: "-string-match-p" doesn't start with package's prefix "evil-smart-input-source".
76:0: error: "-back-detect-chars" doesn't start with package's prefix "evil-smart-input-source".
91:0: error: "-fore-detect-chars" doesn't start with package's prefix "evil-smart-input-source".
102:0: error: "-guess-context" doesn't start with package's prefix "evil-smart-input-source".
128:0: error: "-prober" doesn't start with package's prefix "evil-smart-input-source".
140:0: error: "-mk-input-source-funcs" doesn't start with package's prefix "evil-smart-input-source".
153:0: error: "-get-input-source" doesn't start with package's prefix "evil-smart-input-source".
157:0: error: "-set-input-source" doesn't start with package's prefix "evil-smart-input-source".
169:0: error: "adaptive-input-source" doesn't start with package's prefix "evil-smart-input-source".
175:0: error: "set-input-source-english" doesn't start with package's prefix "evil-smart-input-source".
179:0: error: "set-input-source-other" doesn't start with package's prefix "evil-smart-input-source".
184:0: error: "mode" doesn't start with package's prefix "evil-smart-input-source".
```
Looks mostly like prefixing issues -- double-check these, but feel free to ping to ask for help on sorting them out too.

Experimental static checks/suggestions:
- evil-smart-input-source.el#L143: There is no need to quote lambdas (neither #' nor ')
- evil-smart-input-source.el#L146: There is no need to quote lambdas (neither #' nor ')
- evil-smart-input-source.el#L149: There is no need to quote lambdas (neither #' nor ')
- evil-smart-input-source.el#L207: It's safer to sharp-quote function names; use `#'`
- evil-smart-input-source.el#L209: It's safer to sharp-quote function names; use `#'`
- evil-smart-input-source.el#L211: It's safer to sharp-quote function names; use `#'`
- evil-smart-input-source.el#L213: It's safer to sharp-quote function names; use `#'`
- evil-smart-input-source.el#L215: It's safer to sharp-quote function names; use `#'`
- evil-smart-input-source.el#L217: It's safer to sharp-quote function names; use `#'`
- evil-smart-input-source.el#L22: Prefer `https` over `http` (if possible)

**Comment by laishulu** [comment]
@riscy 
1. Clarification: Switch input source for smartly according to context language and evil mode.
2. About the prefix issue: it's becuase I use a package called `names` to manage the namespace
```
(define-namespace evil-smart-input-source-
```

**Comment by laishulu** [comment]
I am using `cask exec elsa` to check again.
Please don't put your time on this one until I report that everything is ready.

**Comment by laishulu** [comment]
@riscy Everything I can do is finished, please check.

**Comment by laishulu** [comment]
I will make the package more general, not limited to evil.
So I will close this PR.

**Pull request closed without merging**
