### PR TITLE
wttrin: changing repository to update owner/maintainer

### PR DESCRIPTION
**Pull request by cjennings**
### Brief summary of what the package does

This package displays the weather for a given location using the https://wttr.in service. 

### Direct link to the package repository

https://github.com/cjennings/emacs-wttrin

### Your association with the package

TLDR: I'm requesting to take ownership / maintenance of this abandoned broken package.

The emacs-wttrin package has been broken for many years now. Several others have submitted pull requests to maintain the package in working order. However, the authors have been unresponsive. The last commit was almost 8 years ago in 2017. 

This PR is my request to take ownership and maintenance using the following repo:  https://github.com/cjennings/emacs-wttrin. The master branch is working, contains several submitted PRs for various bug fixes, and I've added a few minor improvements.

If you believe I should rename the project and submit a new package under a different name instead, please let me know. If there are other obstacles, I'm grateful for any direction and guidance.

### Relevant communications with the upstream package maintainer

I emailed the original author for permission to take ownership of maintaining this package, but didn't receive a reply. I believe this package is now abandoned in a broken state.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, and for offering your maintainership.  Just to make sure we're being comprehensive, have you personally tried reaching out to the author?  We have a wiki page on this process:
https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks

**Comment by cjennings** [comment]
Thanks @riscy

I didn't see that page, but it looks like I've mostly been following its guidance anyway. 

Here's the section that applies:
> The author is unresponsive.
> "Unresponsive" is a bit subjective, but from our perspective an adequate attempt to contact the author is a couple emails, one to two weeks apart, and no reply for a month. Yes it's a long time, but again we want to respect the original author's time and their original contribution to the package.

Here's what I've done:
I found the author's email listed in the source code header and sent an email requesting  owner/maintainer-ship on February 12th, but didn't receive a reply. Then things got busy and I didn't send another request until April 3rd. The owner still hasn't responded, but April 3rd was about 4 days ago. If you like, I'm happy to wait another 10 days. 

In any case, if the author does eventually resurface and wants ownership, I'm fine with transferring my repo to them, or submitting PRs to their repo, or whatever they prefer. The owner/maintainer role isn't as important as getting a working version of this cool little package back on Melpa. 

Thanks for the response, and let me know how you want to proceed.

**Comment by riscy** [comment]
That sounds fine, and let's do one more thing and tag @bcbcarl directly on GitHub to improve our chances.

If this sits for another week with no reply, I'm fine to merge this and have you take over maintainership.  And, thank you again for offering that to the community.

**Comment by riscy** [comment]
Alright, thank you for this.  I'll hit merge and I can also pass along a quick run over the checks:

`wttrin.el` with byte-compile using Emacs 29.3:
```
wttrin.el:63:2: Warning: custom-declare-variable `wttrin-unit-system' docstring wider than 80 characters
In wttrin-query:
wttrin.el:109:15: Warning: assignment to free variable `buffer-face-mode-face'
wttrin.el:117:10: Warning: `goto-line' is for interactive use only; use `forward-line' instead.
wttrin.el:118:15: Warning: assignment to free variable `date-time-stamp'
wttrin.el:121:10: Warning: `goto-line' is for interactive use only; use `forward-line' instead.
wttrin.el:122:15: Warning: assignment to free variable `location-info'
wttrin.el:125:10: Warning: `goto-line' is for interactive use only; use `forward-line' instead.
wttrin.el:127:22: Warning: reference to free variable `location-info'
wttrin.el:127:41: Warning: reference to free variable `date-time-stamp'
```
For the `buffer-face-mode-face` one you need to `(require 'face-remap)`; `date-time-stamp` and `location-info` should be scoped inside a `let` block by the looks of things, rather than `setq`ing a globally available variable outside of wttrin's namespace.

Package and license:
- wttrin.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Pull request merged**
