### PR TITLE
Remove all Emacswiki packages

### PR DESCRIPTION
**Pull request by tarsius**
### Update 2018-01-24 - The Finale

Removal of Emacswiki packages has long been requested and planned, yet we've all hung on because the convenience of useful code that's insecurely managed and distributed has consistently exceeded the motivation to mitigate the risks: prominent Emacswiki authors have not taken action, while library and starter kit authors and end users (myself included) have cheerfully continued to depend on Emacswiki-sourced packages.

MELPA stopped building/updating all these packages a while ago, with the intention of removing them once we had a plan to minimise disruption. In the meantime, we continued to serve up our last-built versions. We'd have preferred to publicly sunset our continued hosting of them, but having accidentally deleted those historic (probably-outdated) packages yesterday, we now won't be restoring them. We apologise for the disruption that the sudden removal has caused (and will continue to cause), but this would likely have been the case even if we'd announced a sunset date weeks in advance, and we hope that you'll understand our decision.

In hindsight, MELPA should probably never have distributed Emacswiki-sourced packages. When MELPA was starting off, incorporating those packages helped MELPA's growth, to both the community's benefit and its cost. Thanks to everyone who pushed us to resolve this!

Now that we all know better, let's get on with fixing things and making the package ecosystem better and safer. If Emacswiki authors move their code to a MELPA-supported SCM, we can re-add those packages to MELPA. Some authors won't be willing to do that, so the community will have to decide how much it values that code, and how to get it distributed.

Whatever steps are necessary along the way, we - the MELPA maintainers - will be happy to advise.

-@purcell

---

### Update 2018-01-24

All packages were accidentally deleted, including non-Emacswiki packages. Those are in the process of being restored, but for the Emacswiki packages that is not currently possible. That probably means that we make this final soon, but still waiting for Steve to weight in. The discussion about this begins [further down](https://github.com/melpa/melpa/pull/5008#issuecomment-360098939).

---
----

### Update 2017-09-16

**Status** Packages from the Emacswiki are still available from Melpa, but they are no longer being updates, because https://github.com/melpa/package-build/pull/9 has been merged into Melpa.

**TODO** Here is a list of ongoing efforts to get packages of the Emacswiki:

- ~~#5034 Getting Drew to commit to (a) Git repository/-ies~~ **Unlikely, we've tried for a decade.**
- [ ] #5020 Moving rubikitch's packages to github **No response so far. Sent an email.**
- [x] #2342 Deprecate all emacswiki packages. **Mostly replaced by this issue, except:**
- [ ] https://github.com/melpa/melpa/issues/2342#issuecomment-291944022 asks github-using maintainers who have packages on the Emacsmirror to migrate. That issue has gotten unwieldy, so I will probably replace it with one or more new issues and start pinging.

---

### Original issue text

Since everyone here (#2342) agrees that the Emacswiki packages *should* be removed because they pose a huge security risk, let's just *do* it. We pretty much decided to do this years ago and we tried to get maintainers to move their packages. Waiting a few more years won't make any difference except that it leaves the community at risk.

### CODE REVIEW

**Comment by purcell** [comment]
I'm strongly in favour of this, and it certainly makes sense to just bite the bullet and do it. However, it *will* dramatically impact the day-to-day experience of many people who rely on certain very popular packages that are not available elsewhere. So I think we need to publicise this ahead of time and give a timeline. It would also be really helpful if @kensanata would be willing to end-of-life the hosting of code on Emacswiki on a compatible timeline - is that something you'd consider, Alex?

**Comment by purcell** [comment]
Additionally, this will presumably cause a bunch of other packages to become uninstallable, as a result of depending on packages in this list.

**Comment by purcell** [comment]
> It would also be really helpful if @kensanata would be willing to end-of-life the hosting of code on Emacswiki on a compatible timeline - is that something you'd consider, Alex?

A half-way step to this would be to block the "raw" view of files on the emacswiki, so that files could be viewed in an html wrapper, but not easily downloaded in their original form.

**Comment by jgkamat** [comment]
While this is a positive step for security, it's really annoying to suddenly find that your dotfiles no longer properly work on a new computer (arguably when you need them to work the most, since you're busy setting other stuff up). 

Would it be possible to freeze and copy the emacswiki packages to github or similar git hosting, instead of deleting them entirely? I guess that would raise the issue of who would maintain the packages then...

**Comment by tarsius** [comment]
> this will presumably cause a bunch of other packages to become uninstallable, as a result of depending on packages in this list.

We have already frozen those: https://github.com/melpa/melpa/issues/2342#issuecomment-291922427 ff. Maybe there are new ones, I'll check.

> it will dramatically impact the day-to-day experience of many people who rely on certain very popular packages that are not available elsewhere.

Could you give me a list of the download counts? We could freeze the most popular ones like we have done for the ones being depended on by non-wiki packages.

**Comment by technomancy** [comment]
> While this is a positive step for security, it's really annoying to suddenly find that your dotfiles no longer properly work on a new computer

If your dotfiles depend on software downloaded from a wiki, they're *already broken*. Better to be broken in a way that is obvious than one that is hidden.

If this doesn't get merged what's to stop someone from just deleting them from the emacswiki directly instead?

**Comment by purcell** [comment]
> Could you give me a list of the download counts? We could freeze the most popular ones like we have done for the ones being depended on by non-wiki packages.

Is this sufficient? - https://melpa.org/download_counts.json

**Comment by tarsius** [comment]
> Is this sufficient?

Yes. I forgot that exists - it was late :wink:

**Comment by tarsius** [comment]
I think we should immediately stop updating any packages from the wiki, which can be easily done by editing `package-build-checkout`. That way existing malware, if any, won't disappear, but at least no new ("let's do it before the hole gets fixed") attacks would be possible.

**Comment by tarsius** [comment]
I have updated the statistics at https://emacsmirror.net/stats/emacswiki.html.

**Comment by dgutov** [comment]
> yaoddmuse |   | company

This line is not very accurate at least: yaoddmuse is a soft dependency, company works just fine without it.

**Comment by tarsius** [comment]
> This line is not very accurate at least: yaoddmuse is a soft dependency, company works just fine without it.

I am aware of that. From https://github.com/melpa/melpa/issues/2342#issuecomment-291906557:

> It does not include any indirect dependers and it is based on automatically extracted dependency information, not the Package-Requires header.

Despite these limitations I still think this information is useful.

**Comment by tarsius** [comment]
I have updated the table. Soft dependencies are now marked as such.

**Comment by aplaice** [comment]
Looking at the dependencies as seen by MELPA (using https://melpa.org/recipes.json and https://melpa.org/archive.json), gives a similar picture (this obviously does not include soft dependencies):

dependee | depender
---|---
filesets+ | helm-filesets
font-lock+ | all-the-icons
goto-chg | evil
header2 | org-readme
help-fns+ | nu-mode
hexrgb | paper-theme
highlight | cider-eval-sexp-fu
highlight | eval-sexp-fu
highlight | evil-search-highlight-persist
highlight | floobits
highlight | nrepl-eval-sexp-fu
highlight | php-boris-minor-mode
highlight | sonic-pi
lib-requires | org-readme
thingatpt+ | el-spice
yaoddmuse | org-readme

The greatest (and by far the most important) discrepancy is that `evil` (!) depends on `goto-chg`. 

The only other differences are that `org-readme` depends on several other wiki packages, though I'm not sure whether they're really hard dependencies and, according to MELPA, `jabber` does not have a hard depency on `hexrgb` (indeed, installing `jabber` does not install `hexrgb`).

This obviously does not list all indirect dependencies (which would include everything that depends on `evil`.

**Comment by syl20bnr** [comment]
Opened an issue on the evil repo for the goto-chg problem.

**Comment by wasamasa** [comment]
`goto-chg` is particularly embarassing as I've found the code depending on it to be broken in the presence of the only other dependency, `undo-tree`.  [This fork](https://github.com/martinp26/goto-chg) works with one or two modifications so it would need to be added to our organization to make it a replacement package.

**Comment by tarsius** [comment]
> The greatest (and by far the most important) discrepancy is that `evil` (!) depends on `goto-chg`.

That's because the `evil` repository contains a copy of `goto-chg.el`. In such cases my tools don't look for another package that also provides it.

> @purcell Would you accept if I forked that package under the emacs-evil organization, modified it so that it works correctly with Evil and replaced the existing MELPA package with it?

I would very much welcome that. Actually I think that I have proposed that to the previous maintainer (or maybe I just intended to do it, or only talked about it here).

**Comment by purcell** [comment]
> @purcell Would you accept if I forked that package under the emacs-evil organization, modified it so that it works correctly with Evil and replaced the existing MELPA package with it?

Yes, definitely.

**Comment by wasamasa** [comment]
OK, done.

@tarsius Don't forget removing `goto-chg` from this PR to resolve the conflict.

**Comment by kensanata** [comment]
I think the hosting of code on Emacs Wiki is a small but positive feature. Distributing this code using a package manager might be something that requires an extra effort you are not willing to spend (and neither am I) but removing this feature would result in a net negative for me and that is why I don't think that is a good idea.

**Comment by tarsius** [comment]
Since this is trending on r/emacs...

> I think we should immediately stop updating any packages from the wiki

I have implemented that in https://github.com/melpa/package-build/pull/9. I think it is a good solution in the short run.

**Comment by tekktonic** [comment]
@kensantana the issue isn't that it's hard to maintain but that there is no verifiability and it's therefore a security risk.  I can go onto emacswiki and modify a common package to recursively delete $HOME or worse and anyone unlucky enough to pull that package before it's fixed is screwed

**Comment by tarsius** [comment]
@tekktonic: He (@kensanata) already acknowledged this risk and went on making a distinction between making package with originates from the wiki available through a package manager (i.e. allowing to "pull" it (without being aware of the original source)) and the benefits of making code available on a wiki.

I think we should let that side-issue rest for the time being and concentrate on getting the Melpa issue resolved first.

**Comment by kensanata** [comment]
Yeah, the "more work involved" I implied is something like keeping a hash of verified releases, and doing the actual verifying. It's something that a release manager would do. Whether the code author does it (which is what you would like to enforce—and which you implicitly trust all of them to do) or whether an independent release manager does it (which nobody is volunteering to do), or indeed relying on the end user to do it (basically this is what the wiki does) are simply different ways of solving the issue.
As Jonas said, we all agreed that simply copying from the wiki and packaging the latest version doesn't do it. An additional organizational step is needed. Actual work by real people, sadly. :)

**Comment by purcell** [comment]
Alright, melpa/melpa#4802 is merged (which removes support for most of the non-`git` fetchers), and that means `wiki` is next in the firing line, ie. this PR.

@tarsius has submitted https://github.com/melpa/package-build/pull/9, which will effectively prevent emacswiki packages from updating in future on MELPA. Merging it and using it for MELPA means that if we ever had to do a full rebuild from MELPA, the wiki packages would be dropped. 

I think that's acceptable, and we can establish a timeline for removing them anyway and finally merging this PR. I might suggest three months? Perhaps it would be good to somehow highlight wiki packages more prominently on the web site and (ideally) in Emacs so that people will know to avoid/migrate them... ideas?

I've spent a bit of time figuring out if MELPA's overall build machinery will break when https://github.com/melpa/package-build/pull/9 is incorporated, and I think we're safe, so I'll go ahead and apply those changes here. In any case, I modified our build script directly so that wiki packages will no longer be built (see b6b281c7).

**Comment by purcell** [comment]
I've started the ball rolling by taking the only part of `dired+` I use (extra font locking) and extracting it into a [new package](https://github.com/purcell/diredfl) hosted on github.

**Comment by tarsius** [comment]
Thanks @purcell! I have summarized the current status in my initial post above.

**Comment by Fuco1** [comment]
This will destroy my config, but I am fully in favour.  I think what @purcell did with the font lock is a great idea.  I depend on some code from `diredp` so maybe I will just copy/extract the logic into `dired-hacks` or a separate package and swap the dependency to that.

Do we want to start tracking these "soft forks" of some of the wiki functionality so we can have a list for people who would want to migrate/fix their setups?

**Comment by etu** [comment]
Couldn't deps (like font-lock+) just be placed in a repository under /melpa until someone comes along and want to maintain it?

At least it could be used for keeping track of changes and bug reports. It doesn't matter if changes take alot of time to get through if you ask me.

**Comment by Fuco1** [comment]
@etu that would probably work, but it would require some review of the code to make sure there is no dangerous content in there---we can not assume that the packages are not already compromised if we do this mainly from the security point of view.

So if people start chopping the packages into smaller pieces there will be some sort of implicit review in that and at least some basic safety will be ensured.  So it's mostly about the available resources I guess.

**Comment by etu** [comment]
So if I would create a github-organization for a emacs-wiki-packages-rescue project, and then copy all the code as initial commits without going through the code at all. And then ask people and myself to go through things to later submit to melpa after it's tested through and checked.

How would people feel about such project?

**Comment by tarsius** [comment]
> How would people feel about such project?

I still think it would be better to write some tool for Drew that would allow him to upload to the wiki as before but which would at the same time push to a per-package repository.

**Comment by etu** [comment]
@tarsius Oh... I had missed that that was an issue... What about something that scrapes emacs-wiki and makes pull requests in corresponding repositories automatically so we can have revisions and checks of what happens?

**Comment by tarsius** [comment]
> What about something that scrapes emacs-wiki

The Emacsmirror already contains 678 such repositories. I update them every few weeks.

> and makes pull requests in corresponding repositories automatically so we can have revisions and checks of what happens?

Do you want to perform these reviews for the next decade? I have been waiting for a decade for Drew to start using git. While maintaining tools specifically to deal with his packages (and five others or so). And I am done with it.

**Comment by tumashu** [comment]
What about write a helper package,  user can use this package to fetch Drew's packags?  not every person need his packages :-)

**Comment by tarsius** [comment]
@milkypostman [said](https://github.com/melpa/melpa/issues/2342#issuecomment-360023727)

> i have inadvertently deleted all emacswiki packages. so we may as well delete the recipes???

I just rebased this change two days ago and was going to ask for a timeline for its merge but then decided to wait a little until @purcell is less busy.

While I would have preferred to announce the removal of the Emacswiki packages before doing it (as was the plan), this doesn't change anything. We are all in violent agreement that they should be removed. So now that they are removed and restoring wouldn't be easy, I think that we should just leave it at that and merge this pull request.

Then we - preferably Steve, because he always seems to find the right words - should write an announcement.

**Comment by tarsius** [comment]
These are the non-wiki packages that still depend on wiki packages:

```
| Dependee (9)  | Author       | Depender                      | Type | Fetcher | Author                    |
|---------------+--------------+-------------------------------+------+---------+---------------------------|
| dropdown-list |              | thesaurus                     | soft | github  | Dino Chiesa, Alex Henning |
| etags-select  | Scott Frazer | evil-collection               | soft | github  | James Nguyen              |
| filesets+     | Drew Adams   | helm-filesets                 | soft | github  | Graham Clark              |
| font-lock+    | Drew Adams   | all-the-icons                 | hard | github  | Dominic Charlesworth      |
| font-lock+    | Drew Adams   | jemdoc-mode                   | soft | github  | Dimitar Dimitrov          |
| hexrgb        | Drew Adams   | bibliothek                    | hard | github  | Göktuğ Kayaalp            |
| hexrgb        | Drew Adams   | jabber                        | hard | git     |                           |
| hexrgb        | Drew Adams   | on-screen                     | soft | github  | Michael Heerdegen         |
| hexrgb        | Drew Adams   | paper-theme                   | hard | github  | Göktuğ Kayaalp            |
| highlight     | Drew Adams   | cider-eval-sexp-fu            | hard | github  | Sylvain Benner            |
| highlight     | Drew Adams   | eval-sexp-fu                  | hard | github  | Takeshi Banse             |
| highlight     | Drew Adams   | evil-extra-operator           | hard | github  | Dewdrops                  |
| highlight     | Drew Adams   | evil-search-highlight-persist | hard | github  | Juanjo Alvarez            |
| highlight     | Drew Adams   | floobits                      | hard | github  | Geoff Greer               |
| highlight     | Drew Adams   | nrepl-eval-sexp-fu            | hard | github  | Takeshi Banse             |
| highlight     | Drew Adams   | php-boris-minor-mode          | hard | github  | steckerhalter             |
| highlight     | Drew Adams   | sonic-pi                      | hard | github  | Joseph Wilk               |
| highlight     | Drew Adams   | spiral                        | hard | github  | Daniel Barreto            |
| strings       | Drew Adams   | ergoemacs-mode                | soft | github  | David Capello             |
| thingatpt+    | Drew Adams   | el-spice                      | hard | github  | Vedang Manerikar          |
| thingatpt+    | Drew Adams   | exato                         | hard | github  | Filipe Silva              |
| yaoddmuse     |              | company                       | soft | github  | Nikolaj Schumacher        |
| yaoddmuse     |              | org-readme                    | soft | github  | Matthew L. Fidler         |
```

* Important thing to notice is that this list is very short.

* I have posted such lists before and asked the maintainers to do something about it. I will @mention them again in a bit.

* I will check which of these packages *really* have such a dependency and then remove only those. Those with a *soft* dependency obviously don't, but even a "hard" dependency might not actually be required - it might e.g. only be required by a library that isn't even part of the Melpa package.

* Of course the intention is to add these packages back, but as past experience has shown the removal can serve to motivate the maintainers to address the issue.

**Comment by quicknir** [comment]
@tarsius Many of the packages in question (especially, several of interest to the spacemacs community) depend on highlight. What should happen with packages that really use that functionality? Is there functionality in emacs that makes the highlight package basically redundant (it's been around for a while)? Or should someone put highlight on github and then in melpa? Just curious what resolution here would be good.

**Comment by purcell** [comment]
> I just rebased this change two days ago and was going to ask for a timeline for its merge but then decided to wait a little until @purcell is less busy.

You might be waiting a while, then. :-/

> While I would have preferred to announce the removal of the Emacswiki packages before doing it (as was the plan), this doesn't change anything. We are all in violent agreement that they should be removed. So now that they are removed and restoring wouldn't be easy, I think that we should just leave it at that and merge this pull request.
> 

I absolutely support merging this, probably once we're reasonably sure that we can also remove `highlight` without breaking Spacemacs and thus resolve the conflict reported on this branch. 

> Then we - preferably Steve, because he always seems to find the right words - should write an announcement.

I'll add a note to the top of this issue, since that seems the logical place.

**Comment by purcell** [comment]
Summary note added.

**Comment by tarsius** [comment]
We also need to remove non-wiki packages that depend on one of the removed wiki packages, see respective commit.

I am waiting for https://github.com/syl20bnr/spacemacs/issues/10244#issuecomment-360433871 and 
https://github.com/syl20bnr/spacemacs/issues/10244#issuecomment-360445133 to be addressed before merging this. We can then add the removed non-wiki packages back once they have dropped the wiki dependency.

- [ ] all-the-icons @domtronn
- [ ] cider-eval-sexp-fu @clojure-emacs @bbatsov
- [ ] el-spice @vedang
- [ ] eval-sexp-fu @hchbaw
- [ ] evil-search-highlight-persist @naclander
- [ ] exato @ninrod
- [ ] floobits @Floobits
- [ ] helm-filesets @gcla
- [ ] nrepl-eval-sexp-fu @samaaron
- [ ] paper-theme @cadadr
- [ ] php-boris-minor-mode @steckerhalter
- [ ] sonic-pi @repl-electric
- [ ] spiral @unrepl

To the maintainers of these packages: Please drop the dependency on any package from the Emacswiki. These packages are no longer available from Melpa and won't be added back for security reasons. Or at least make those dependencies optional. Make sure you also edit the `Package-Requires` header keyword. Finally add a pull-request to have your package added back. You don't have to fill out the default pull-request template, instead only link to the repository and back here.

Thanks!

Read the summary at the top for more information. Sorry for the inconvenience.

There is one special case, which might be easier to fix than the others. I *think* `helm-filesets` does not actually *need* `filesets+`, but it defines a dependency on that anyway.

**Comment by cadadr** [comment]
> While I would have preferred to announce the removal of the Emacswiki packages before doing it (as was the plan), this doesn't change anything. We are all in violent agreement that they should be removed. So now that they are removed and restoring wouldn't be easy, I think that we should just leave it at that and merge this pull request.

Hi, I have patched `paper-theme` and removed the offending dependency.  I guess a better way to do this would be to leave a couple days of window for the mentioned maintainers to update their packages and report under this issue that they did so, and remove the packages if they don't.  That way less breakage would be caused to users of these packages.

**Comment by purcell** [comment]
> remove the packages if they don't. That way less breakage would be caused to users of these packages.

I think you're talking about those packages with broken dependencies now, and there's no plan to remove those -- they will definitely be given time to be fixed.

**Comment by steckerhalter** [comment]
I wonder, why don't we just use `highlight.el` from emacsmirror (https://github.com/emacsmirror/highlight)? That's what I do to provide it without emacswiki. Then we wouldn't have to dig all the bones up ;)

**Comment by purcell** [comment]
> I wonder, why don't we just use highlight.el from emacsmirror (https://github.com/emacsmirror/highlight)? That's what I do to provide it without emacswiki. Then we wouldn't have to dig all the bones up ;)

The emacsmirror version of that is automatically scraped from the wiki too, so it has the same security issues as the old Emacswiki-derived package. (We won't be accepting back into MELPA any packages which are *automatically* propagated into an SCM from Emacswiki.)

**Comment by steckerhalter** [comment]
@purcell ok, how about me making a fork and we'll use that?

**Comment by purcell** [comment]
That would be okay, I think, if you're up for maintaining it over time as necessary, or reviewing and incorporating upstream changes.

**Comment by steckerhalter** [comment]
@purcell ok, it's here: https://github.com/steckerhalter/highlight.el

@tarsius could you pull highlight.el from the new repo and readd the recipes that depend on highlight.el?

**Comment by tarsius** [comment]
> I think you're talking about those packages with broken dependencies now, and there's no plan to remove those -- they will definitely be given time to be fixed.

Okay, but those packages are uninstallable now that the dependencies are no longer available.

**Comment by tarsius** [comment]
I have merged this.

*  Get highlight from @steckerhalter's proxy repository.
* Remove all [other] Emacswiki packages.

The recipes of the non-wiki packages that depended on wiki packages have not been removed yet.

**Comment by purcell** [comment]
@tarsius Thanks, that's perfect for now, I think.

**Comment by bbatsov** [comment]
>  cider-eval-sexp-fu @clojure-emacs @bbatsov

This depends on two `EmacsWiki` packages - `highlight` and `eval-sexp-fu`. As I never really used them, I'm not really interested in forking and maintaining them.  @syl20bnr submitted this extension, so maybe he'd be willing to help out.

**Comment by mattiasb** [comment]
[all-the-icons](https://github.com/domtronn/all-the-icons.el) removed its dependency on font-lock+ [yesterday](https://github.com/domtronn/all-the-icons.el/commit/52d1f2d36468146c93aaf11399f581401a233306) fwiw.

**Comment by vedang** [comment]
I have updated `el-spice` to remove the dependency on `thingatpt+`. @tarsius : I can see the `el-spice` recipe in the melpa recipies folder, so I'm not sure there's anything else to do at the moment. Please let me know if I've missed anything.

**Comment by tarsius** [comment]
@mattiasb @vedang Thanks!

@vedang Nothing else should be required.

**Comment by ninrod** [comment]
Gentleman I've just fixed the dependencies of [exato](https://melpa.org/#/exato) so it only depends on evil now. All should be fine.

**Comment by tarsius** [comment]
@steckerhalter has announced in #6436 that he has stopped to update his mirror of `highlight`, which was used by Melpa. Guess that means I have to do it now.

This is how I am doing it (I have also added this as a comment in the recipe and as the commit message):

For security reasons Melpa does not distribute any packages that
are maintained on the Emacswiki.  For this package we are forced to
make an exception because it is required by several non-emacswiki
packages, which in turn are required by Spacemacs.

The Emacsmirror imports this package like it mirrors any other
package that is maintained on the Emacswiki, by extracting the
history of the respective library and putting the result in the
`master' branch of the respective repository on the Emacsmirror;
in this case https://github.com/emacsmirror/highlight.

Melpa then mirrors the `melpa` branch of that repository.  Unlike
the `master` branch, the `melpa` branch isn't semi-automatically
updated.  Instead some user has to open a pull-request asking me to
*merge master into melpa*.  I'll then review the changes and merge.
I expect this will only happen if there are breaking changes.

**Pull request merged**
