### PR TITLE
Add org-view-mode recipe

### PR DESCRIPTION
**Pull request by amno1**
### Brief summary of what the package does

[Please write a quick summary of the package.]

Implements a markup-free, read-only viewing mode for buffers in org-mode.

### Direct link to the package repository

https://github.com/amno1/org-view-mode

### Your association with the package

I am currently the enthusiastic author, maintainer and user :).

### Relevant communications with the upstream package maintainer

Either on GitHub issues or via email as included in the package header.

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

**None needed**

(I am not really sure what you mean here, so please have understanding if I am wrong here.)

### Checklist

- [X ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [ X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ X] My elisp byte-compiles cleanly
- [ X] `M-x checkdoc` is happy with my docstrings
- [ X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, looks interesting.

I suggest reducing the use of `autoload` cookies in the defcustoms unless it's strictly necessary.  Consider [this guideline](https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html.

One risk I see is the handling of the keybindings -- `org-view-mode-map` is rightly defined at the top level with e, E, q and Q and users are able to customize that as they see fit.  But if they invoke `org-view-edit-on` they're given a new set of keybindings that are hardcoded and they can't customize (that's not so bad even though it's inflexible).  *But* when they invoke `org-view-edit-off`, presumably they're supposed to be back where they started, but the hardcoded keybindings in that function appear like they will overwrite any earlier customizations.

To solve the above, have you considered implementing a second minor mode to capture the "edit" state?  The mode could refuse to turn itself on if `org-view-mode` isn't enabled, and it would have its own set of keybindings that could be customized in the normal way.

Beyond those, I've got a few trivial lints to report, but nothing blocking:

- org-view-mode.el#L200: It's safer to sharp-quote function names; use `#'`
- org-view-mode.el#L318: Consider `beginning-of-line`
- org-view-mode.el#L442: Consider `beginning-of-line`
- org-view-mode.el#L228: Consider `end-of-line`
- org-view-mode.el#L376: Consider `end-of-line`
- org-view-mode.el#L507: Consider `end-of-line`

**Comment by amno1** [comment]
> Thanks, looks interesting.
> 
> I suggest reducing the use of `autoload` cookies in the defcustoms unless it's strictly necessary. Consider [this guideline](https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html.

Indeed, I was going a bit against the flow there. Changed now.
 
> One risk I see is the handling of the keybindings -- `org-view-mode-map` is rightly defined at the top level with e, E, q and Q and users are able to customize that as they see fit. But if they invoke `org-view-edit-on` they're given a new set of keybindings that are hardcoded, and they can't customize (that's not so bad even though it's inflexible). _But_ when they invoke `org-view-edit-off`, presumably they're supposed to be back where they started, but the hardcoded keybindings in that function appear like they will overwrite any earlier customizations.

Of course, that was actually my blunder. And I am the first one to customize bindings for almost everything :-). I had other things in my head. It should be fixed now. Hopefully 'overriding-local-map' does what I think it does :). Works for me, so let's hear if other people scream. In that case, I have a different workaround.

> To solve the above, have you considered implementing a second minor mode to capture the "edit" state? The mode could refuse to turn itself on if `org-view-mode` isn't enabled, and it would have its own set of keybindings that could be customized in the normal way.

Indeed, I did. That was my first thought, of course. After implementing it, I realized it complicates more than what it solves, so I removed the edit minor mode. But the main reason is that I don't want it to be available "solo". I really want people to enter the quick-edit via the viewing mode and to use it only for very small edits. I think two mode maps are enough here. If overriding-mode-map does not do the job correctly, I'll implement another mechanism to switch maps. 

> Beyond those, I've got a few trivial lints to report, but nothing blocking:
> 
>     * org-view-mode.el#L200: It's safer to sharp-quote function names; use `#'`

Of course; I have just missed that one. Fixed.

>     * org-view-mode.el#L318: Consider `beginning-of-line`
> 
>     * org-view-mode.el#L442: Consider `beginning-of-line`
> 
>     * org-view-mode.el#L228: Consider `end-of-line`
> 
>     * org-view-mode.el#L376: Consider `end-of-line`
> 
>     * org-view-mode.el#L507: Consider `end-of-line`

Is there any advantage more than cosmetics?

Some of those begging-of-/end-of-* functions are marked for interactive use only, so I prefer not to remember which ones, and always use goto-char. Both APIs are implemented in C and seem to cost equally since both spend most of the time in Fline_begining_position.

Thanks for the help!

Best regards
/a

**Comment by riscy** [comment]
> Is there any advantage more than cosmetics?

Probably not -- maybe just, in my experience, code formats a little more nicely when there is less nesting, but that's hardly an advantage worth changing much of the code for.

This looks good to go!  Welcome to MELPA. :)

**Comment by amno1** [comment]
Thank you very much for very kind review and input. It was very welcomed, I forgot to write it in the earlier comment.

**Pull request merged**
