### PR TITLE
added rum-mode

### PR DESCRIPTION
**Pull request by avelino**
rum language is a free software environment for statistical computing
writing in golang

### Brief summary of what the package does

 Emacs major mode for editing Rum 

### Direct link to the package repository

https://github.com/rumlang/rum-mode

### Your association with the package

@rumlang authors 

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, and sorry for the slow response. Quick feedback:

- `cl` is deprecated, but unused here, so you can/should remove the `require`. If you need something like `cl` in future, use `cl-lib`.
- You can use `regexp-opt` to tidy up the long regexp with all the backslashes.
- Don't use `$` to terminate the filename regexp: it should be `\\'`, which matches the end of input.

Hope that helps!

**Comment by avelino** [comment]
@purcell thanks feedback (Improvements is always valid), review pls 😄

**Comment by purcell** [comment]
Thanks. The last point of feedback is still outstanding, and you should also add an `;;;###autoload` for your `define-derived-mode` form. (Also, as noted, `cl`/`cl-lib` isn't actually _needed_ here, so you can just drop the import/dependency.)

**Comment by tarsius** [comment]
Friendly ping!

**Comment by avelino** [comment]
Sorry delay
`Don't use $ to terminate the filename regexp: it should be \\', which matches the end of input.`
I couldn't do it, can you help me?

**Comment by tarsius** [comment]
This doesn't work?

```diff
diff --git a/rum-mode.el b/rum-mode.el
index 095739a..a3a241f 100644
--- a/rum-mode.el
+++ b/rum-mode.el
@@ -72,7 +72,7 @@ (define-derived-mode rum-mode lisp-mode "rum"
   (set (make-local-variable 'font-lock-defaults) '(rum-font-lock-keywords)))
 
 ;;;###autoload
-(add-to-list 'auto-mode-alist '("\\.rum$" . rum-mode))
+(add-to-list 'auto-mode-alist '("\\.rum\\'" . rum-mode))
 
 (provide 'rum-mode)
 ;;; rum-mode.el ends here
```

**Comment by avelino** [comment]
Sorry 😄 , send to master

**Comment by tarsius** [comment]
> you should also add an `;;;###autoload` for your `define-derived-mode` form. (Also, as noted, `cl`/`cl-lib` isn't actually _needed_ here, so you can just drop the import/dependency.)

Please do those two things too.

**Comment by avelino** [comment]
update guys

**Comment by purcell** [comment]
Looks good - merged, thanks. Feel free to add an `;;;###autoload` cookie comment for the `auto-mode-alist` entry.

**Pull request merged**
