### PR TITLE
add welkomscherm.el recipe

### PR DESCRIPTION
**Pull request by jjba23**
### Brief summary of what the package does

Simple, customizable and elegant dashboard package for Emacs. Compatible with GUI and TUI Emacs (> 25). welkomscherm means welcome screen in the Dutch language.

**NOTE** am i doing things right, also with requiring page-break-lines?

### Direct link to the package repository

https://github.com/jjba23/welkomscherm.el

### Your association with the package

I am the creator and maintainer.

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

⸺ `welkomscherm.el` with byte-compile using Emacs 29.4:
```
welkomscherm.el:47:9: Warning: reference to free variable `welkomscherm-centered'
```

⸺ `welkomscherm.el` with package-lint 20240923.1044:
```
1 issue found:
117:5: warning: Closing parens should not be wrapped onto new lines.
```

**Comment by jjba23** [comment]
hey @riscy ! thanks for checking, it should be fixed now in latest version (branch name: trunk)

**Comment by riscy** [comment]
Thank you!  I think a missing keyword you might have re: discoverability is "splash" screen.  Before we go ahead and merge, have you had a chance to compare this to existing packages?

- https://melpa.org/#/dashboard
- https://melpa.org/#/enlight

Obviously the implementations might differ a bit, but it's probably worth knowing about these and/or comparing them (even noting points of contrast in your Commentary, for example)

**Comment by jjba23** [comment]
hi @riscy thanks for the tips, I just published a new version of welkomscherm with better commentary and a new showcase screenshot, and some correct keywords. As for the packages you mention, i refer to them too, and just really don't need all the features they provide.

**Comment by riscy** [comment]
> and just really don't need all the features they provide.

Thank you!  I do see you write ```;; For more advanced dashboards, refer to `dashboard' or `enlight'. ``` and I realize I probably am sounding like a stickler, but can you write this as a justification for why `welkomscherm` should be in MELPA?  For example - are the extra features unavoidable, and you don't want them present in your dashboard(s) because you argue they're a visual distraction to users?  Does `welkomscherm` provide simpler configuration to users?

I.e. argue that your package is somehow providing something that users don't already have.  It's usually a far better outcome for users if we can limit unnecessary redundancy in the package index (and MELPA was never meant to host *everything* ever written - I have lots of personal elisp that's not indexed anywhere.)

**Comment by jjba23** [comment]
Hi @riscy , I understand your reasoning but think this is a bit too much on the nitpicky side. I am starting to feel like take it or leave it to be honest and hadn't expected this kind of conversation in MELPA, where free software should be celebrated.

**Comment by riscy** [comment]
> I am starting to feel like take it or leave it to be honest and hadn't expected this kind of conversation in MELPA, where free software should be celebrated.

You probably saw in CONTRIBUTING.org the following:

> MELPA provides a curated set of Emacs Lisp packages, not an exhaustive list of every single Emacs Lisp file ever created. By default, MELPA maintainers will reject packages that duplicate functionality provided by existing packages. Please try to improve existing packages instead of creating new ones when possible.

I apologize that this seems unexpected to you, but we can revisit this next week and see if you've changed your mind.

**Pull request closed without merging**
