### PR TITLE
Add recipe for typo-suggest

### PR DESCRIPTION
**Pull request by kadircancetin**
### Brief summary of what the package does

Datamuse wrapper for helm and company mode. You can check is your word correct or you can find the words typing.

### Direct link to the package repository

https://github.com/kadircancetin/typo-suggest

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

 **None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass.

### typo-suggest.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200616.2257):
```
3 issues found:
7:38: warning: Use a properly versioned dependency on "cl-lib" if possible.
7:51: error: Package json is not installable.
7:51: warning: Use a properly versioned dependency on "json" if possible.
```
json comes with Emacs by the time 24.2 was around, I believe.  If you bump your emacs requirement to version 24.3, you can remove the cl-lib dependency as well!

Suggestions/experimental static checks:
- typo-suggest.el#L74: It's safer to sharp-quote function names; use `#'`
- typo-suggest.el#L74: It's safer to sharp-quote function names; use `#'`
- typo-suggest.el#L22: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading typo-suggest.el
Done.
```

**Comment by kadircancetin** [comment]
@riscy , sorry about the linting problems. I solved the all related issues.

**Comment by riscy** [comment]
No worries. 👍 

Looking a little closer, I have a handful of issues, but none of them appear to be blocking.

- The comment `;; code goes here` underneath `;;; Code:` is probably not needed
- Check your summary line for typos ;) Don't make typo`s` with the help of helm and comp`a`ny
- Also you don't need another `;;` between the summary line and the lexical binding; you can remove it
- _Also_ this package basically looks like a wrapper around datamuse's `sug` api.  It feels like mentioning that fact either in your summary line or in the `;;; Commentary` would be a good idea.  Perhaps also documenting or linking to datamuse's API limits, since there's a strong reliance on a third-party api here.
- Elisp convention is to use hyphens instead of underscores between words in variables, so you should think about changing `fetch_str` to `fetch-str` to match the community style.
- "Number of second" -> "Number of second`s`" (same for the line with "suggestion")
- "Optional argument IGNORED ignored arguments": you can in fact rename this variable to `_ignored` and then you don't have to document it -- just a hint.

**Comment by riscy** [comment]
Since that ended up being a few more things than I expected, I'll leave this open for now -- but this is very close to ready.

**Comment by kadircancetin** [comment]
Thank you @riscy . I think I fixed all of them. I am very new at writing elisp and want to write with all the conventions. If there is any kind of suggestions which it does not need to be related to packaging I want to fix it.

**Comment by riscy** [comment]
Looks good.  Welcome to MELPA!

**Pull request merged**
