### PR TITLE
Add verona-mode

### PR DESCRIPTION
**Pull request by damon-kwok**
### Brief summary of what the package does

An Emacs major mode  for the [Verona](https://github.com/microsoft/verona/) programming language.

### Direct link to the package repository

https://github.com/damon-kwok/verona-mode

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass.

### verona-mode.el ###

byte-compile (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
verona-mode.el:496:1:Warning: the function `string-trim' is not known to be
    defined.
```

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200616.2257):
- No issues!

Suggestions/experimental static checks:
- verona-mode.el#L433: It's safer to sharp-quote function names; use `#'`
- verona-mode.el#L486: It's safer to sharp-quote function names; use `#'`
- verona-mode.el#L419: Single-line comments should (usually) begin with `;;`
- verona-mode.el#L365: You can use `not` or `null`

**Comment by damon-kwok** [comment]
@riscy Thanks for your feedback, Fixed.

**Comment by damon-kwok** [comment]
I also updated your feedback on `zetz-mode` for this.

**Comment by riscy** [comment]
Looks good, thanks!

**Pull request merged**
