### PR TITLE
Add wfnames package

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
### Brief summary of what the package does

Edit filenames like with Wdired

### Direct link to the package repository

https://github.com/thierryvolpiatto/wfnames

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- looks handy!  A couple of small bits of feedback, but should be a quick merge:

- Very minor, but I notice the summary should be "edit fil[e]names" instead of "edit filnames"
- Your README contains some key information that I think would be valuable to see in your `;;; Commentary` too, since MELPA only indexes your commentary.  E.g. everything under "features" but also "This package has no user interface".

`wfnames.el` with package-lint 20221003.1636:
```
1 issue found:
8:52: warning: An explicit dependency on cl-lib <= 1.0 is not needed on Emacs >= 24.3.
```
and correspondingly the line you've got that reads `Compatibility: 24.1+` should be updated (or removed).

**Comment by thierryvolpiatto** [comment]
Chris Rayner ***@***.***> writes:

> Thanks for this -- looks handy! A couple of small bits of feedback, but should be a quick merge:
>
>   • Very minor, but I notice the summary should be "edit fil[e]names" instead of "edit filnames"
>   • Your README contains some key information that I think would be valuable to see in your ;;; Commentary too, since MELPA only indexes your commentary. E.g. everything under "features"
>     but also "This package has no user interface".
>
> wfnames.el with package-lint 20221003.1636:
>
> 1 issue found:
> 8:52: warning: An explicit dependency on cl-lib <= 1.0 is not needed on Emacs >= 24.3.
>
> and correspondingly the line you've got that reads Compatibility: 24.1+ should be updated (or removed).

Should be fixed now, thanks!

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Chris Rayner ***@***.***> writes:

> Thanks for this -- looks handy! A couple of small bits of feedback, but should be a quick merge:
>
>   • Very minor, but I notice the summary should be "edit fil[e]names" instead of "edit filnames"
>   • Your README contains some key information that I think would be
>   valuable to see in your ;;; Commentary too, since MELPA only indexes
>   your commentary. E.g. everything under "features"

I will do this once merged because I will commit changes to Helm at the
same time and the current infos in the actual README will not be anymore
relevant.  So I will make changes later both to README and ;;;
Commentary:.

Thanks.


>   
>     but also "This package has no user interface".
>
> wfnames.el with package-lint 20221003.1636:
>
> 1 issue found:
> 8:52: warning: An explicit dependency on cl-lib <= 1.0 is not needed on Emacs >= 24.3.
>
> and correspondingly the line you've got that reads Compatibility: 24.1+ should be updated (or removed).
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I have now merged needed changes in Helm and updated both README and Commentary accordingly.

**Comment by thierryvolpiatto** [comment]
Ping, any news on this?

**Comment by riscy** [comment]
Apologies for the wait -- I am usually only here on weekend daytimes (pacific timezone).  I am about to take a break for a while, but I wanted to keep you in the loop.

**Comment by thierryvolpiatto** [comment]
Chris Rayner ***@***.***> writes:

> Apologies for the wait -- I am usually only here on weekend daytimes
> (pacific timezone). I am about to take a break for a while, but I
> wanted to keep you in the loop.

No problems, now ready to merge I think.
Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by riscy** [comment]
Yes, looks good here.  Thanks again. :)

**Comment by thierryvolpiatto** [comment]
Chris Rayner ***@***.***> writes:

> Yes, looks good here. Thanks again. :)

Great, thanks!

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Pull request merged**
