### PR TITLE
Added recipe fixed-page-mode.

### PR DESCRIPTION
**Pull request by wojnicki**
### Brief summary of what the package does

A page-based text editing/note taking/concept thinking Emacs minor mode.  Presents buffer's content as pages of predefined number of lines (50 by default).  It is an analog of pages in a notebook.

### Direct link to the package repository

https://gitlab.com/igorwojnicki/fixed-page-mode

### Your association with the package

Maintainer and author.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
Some notes/suggestions:

I get the following byte warnings on Emacs 30:

```
fixed-page-mode.el           48  34 note     e-f-c    First sentence should end with punctuation
fixed-page-mode.el          138   1 warning  e-f-b-c  docstring has wrong usage of unescaped single quotes (use \=' or different quoting such as `...')
```

If the minor mode is designed to work sans org-mode, it's not a good idea to unconditionally require org when activating the mode. Users could add this code via a hook if they desire it.
A better check in general would be:

```emacs-lisp
(when (derived-mode-p 'org-mode) ;etc
```

instead of:

```emacs-lisp
	(when (require 'org nil 'noerror)
	  (setq org-element-use-cache nil)) ;; WORKAROUND with org mode cache, otherwise org mode reports warnings
```


The `fixed-page-next` and `fixed-page-prev` commands could be implemented in terms of a `fixed-page--move` function which accepts an interger argument, similar to the interface for `forwrad-line`. That would allow either command to have its semantics reversed by passing a negative argument. e.g.

```emacs-lisp
(defun fixed-page-move (&optional n)
  "Move N pages. Negative N moves backward."
  (interactive "p")
  (widen)
  (forward-line (* n fixed-page-length))
  (fixed-page-narrow))

;;`fixed-page-next' can be a defalias for `fixed-page-move'.

(defun fixed-page-prev (&optional n)
  "Move N pages backward. Negative N moves forward."
  (interactive "p")
  (fixed-page-move (* -1 n)))
```

If you plan on adding more commands which follow the pattern of:

```emacs-lisp
(widen)
(operate-on-whole-buffer)
(fixed-page-narrow)
```

it might be useful to develop a macro similar to `save-restriction':

```emacs-lisp
(defmacro fixed-page-with-wide-buffer (body)
  "Execute BODY with buffer widened, then `fixed-page-narrow'."
  `(progn
     (widen)
     ,@body
     (fixed-page-narrow)))
```

**Comment by riscy** [comment]
Thank you @progfolio - this is good advice, especially around using `derived-mode-p`.

I think these:
```
docstring has wrong usage of unescaped single quotes
```
are coming from a yet-unreleased Emacs version (version 30) and I'd be interested to know if they decide to "release" this change.


This:
```elisp
(if (bound-and-true-p fixed-page-mode)
```
is probably too much for `bound-and-true-p` -- you can just check the variable `fixed-page-mode` directly for truthiness, it will have been implicitly declared above due to your use of `define-minor-mode`.

I also have this small nag re: the front-matter -

- fixed-page-mode.el#L27: Triple semicolons `;;;` are usually for section headings

**Comment by wojnicki** [comment]
Thanks for all the suggestions. Kind of rookie mistakes I guess. ;)
I think I've addressed all of them.

**Comment by progfolio** [comment]
@riscy 

> are coming from a yet-unreleased Emacs version (version 30) and I'd be interested to know if they decide to "release" this change.

The motivation behind that warning is that code in the docstring will render with curly-quotes otherwise.
That will lead to syntax errors when that code is copy+pasted.
I think that change is likely to land, and is good advice, but we can always wait and see, too.

**Comment by riscy** [comment]
>  That will lead to syntax errors when that code is copy+pasted.

Ah I see, so it wouldn't affect contractions but rather the use of single quotes in something like `(set 'x "y")`.

@wojnicki - fyi:

- fixed-page-mode.el#L132: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`

but otherwise this looks good to merge - thanks!

**Comment by wojnicki** [comment]
> * fixed-page-mode.el#L132: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
@riscy , thanks. Already corrected in my repo.

**Pull request merged**
