### PR TITLE
Add recipe for starhugger

### PR DESCRIPTION
**Pull request by daanturo**
### Brief summary of what the package does

Hugging Face/AI-powered text & code completion client.

### Direct link to the package repository

https://gitlab.com/daanturo/starhugger.el

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`starhugger-grep-context.el` with checkdoc 0.6.2:
```
starhugger-grep-context.el:20: All variables and subroutines might as well have a documentation string
starhugger-grep-context.el:23: All variables and subroutines might as well have a documentation string
starhugger-grep-context.el:126: All variables and subroutines might as well have a documentation string
starhugger-grep-context.el:140: All variables and subroutines might as well have a documentation string
starhugger-grep-context.el:154: All variables and subroutines might as well have a documentation string
starhugger-grep-context.el:171: Name lisp should appear capitalized as Lisp
starhugger-grep-context.el:177: Error messages should *not* end with a period
```
Try to address these within reason -

`starhugger-grep-context.el` with package-lint 20230605.1550:
```
2 issues found:
9:10: warning: This file is not in the `cl-lib' ELPA compatibility package: require `cl-lib' instead.
229:0: warning: Private functions generally should not be autoloaded.
```

`starhugger.el` with byte-compile using Emacs 28.1:
```
starhugger.el:304:1: Warning: custom-declare-variable
    `starhugger-retry-temperature-range' docstring wider than 80 characters
```

`starhugger.el` with checkdoc 0.6.2:
```
starhugger.el:77: All variables and subroutines might as well have a documentation string
starhugger.el:101: All variables and subroutines might as well have a documentation string
starhugger.el:119: All variables and subroutines might as well have a documentation string
starhugger.el:140: Some lines are over 80 columns wide
starhugger.el:173: Argument `prompt' should appear (as PROMPT) in the doc string
starhugger.el:216: All variables and subroutines might as well have a documentation string
starhugger.el:221: All variables and subroutines might as well have a documentation string
starhugger.el:305: Some lines are over 80 columns wide
starhugger.el:323: All variables and subroutines might as well have a documentation string
starhugger.el:335: All variables and subroutines might as well have a documentation string
starhugger.el:442: All variables and subroutines might as well have a documentation string
starhugger.el:465: All variables and subroutines might as well have a documentation string
starhugger.el:486: All variables and subroutines might as well have a documentation string
starhugger.el:547: All variables and subroutines might as well have a documentation string
starhugger.el:577: All variables and subroutines might as well have a documentation string
starhugger.el:584: All variables and subroutines might as well have a documentation string
starhugger.el:590: All variables and subroutines might as well have a documentation string
starhugger.el:652: All variables and subroutines might as well have a documentation string
starhugger.el:673: All variables and subroutines might as well have a documentation string
starhugger.el:682: All variables and subroutines might as well have a documentation string
starhugger.el:756: All variables and subroutines might as well have a documentation string
starhugger.el:825: All variables and subroutines might as well have a documentation string
starhugger.el:917: All variables and subroutines might as well have a documentation string
starhugger.el:967: All interactive functions should have documentation
starhugger.el:990: All variables and subroutines might as well have a documentation string
starhugger.el:1005: All variables and subroutines might as well have a documentation string
```
Try to address these within reason (I'll take another look on the next pass)

`starhugger.el` with package-lint 20230605.1550:
```
3 issues found:
27:10: warning: This file is not in the `cl-lib' ELPA compatibility package: require `cl-lib' instead.
988:0: warning: Private functions generally should not be autoloaded.
1003:0: warning: Private functions generally should not be autoloaded.
```

`starhugger.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- starhugger.el#L458: It's safer to sharp-quote function names; use `#'`
- starhugger.el#L460: It's safer to sharp-quote function names; use `#'`
- starhugger.el#L247: Can the `format` and `concat` be combined?
```

Package and license:
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to starhugger-grep-context.el

**Comment by daanturo** [comment]
Thank you for your feedback.

> starhugger-grep-context.el:171: Name lisp should appear capitalized as Lisp
> starhugger-grep-context.el:177: Error messages should *not* end with a period
> 9:10: warning: This file is not in the `cl-lib' ELPA compatibility package: require `cl-lib' instead.
> 27:10: warning: This file is not in the `cl-lib' ELPA compatibility package: require `cl-lib' instead.
> starhugger.el:967: All interactive functions should have documentation
> - starhugger.el#L458: It's safer to sharp-quote function names; use `#'`
> - starhugger.el#L460: It's safer to sharp-quote function names; use `#'`
> - starhugger.el#L247: Can the `format` and `concat` be combined?
> Add formal license boilerplate or an SPDX-License-Identifier to starhugger-grep-context.el

Solved ✨

> All variables and subroutines might as well have a documentation string

They are internal definitions, I don't think it's necessary to document them.

> Private functions generally should not be autoloaded.

About `starhugger-auto--after-change-h` and `starhugger-auto--post-command-h`: because they are used by `starhugger-auto-mode` - which is dumped into the autoload file (so that it can be enabled without loading the entire starhugger.el) - I need to autoload them.

> starhugger.el:304:1: Warning: custom-declare-variable
>     `starhugger-retry-temperature-range' docstring wider than 80 characters
> starhugger.el:140: Some lines are over 80 columns wide
> starhugger.el:305: Some lines are over 80 columns wide

They are literal URLs, breaking them into separate lines would hamper readability when looking at the code IMO.

**Comment by riscy** [comment]
> I need to autoload them.

Ah, I see the trick you're using.  If my understanding is correct, I would (gently) discourage doing this because it strikes me as premature optimization and probably not very effective (I don't know what your metric is here).  If anyone enables starhugger-auto-mode, *any* subsequent action they perform is going to load all of starhugger.el in anyway, due to the post-command-hook.

> They are literal URLs

Yes, only worry about the checkdocs within reason.  But the long curl command in `starhugger-retry-temperature-range` actually triggers a byte-compile warning that users will see during install and you should strive to fix it.  The command in that function looks feasible to add another escaped linebreak to, or there's a local variable you can set that will let the byte-compiler admit longer docstrings.

**Comment by daanturo** [comment]
> > I need to autoload them.
> 
> Ah, I see the trick you're using. If my understanding is correct, I would (gently) discourage doing this because it strikes me as premature optimization and probably not very effective (I don't know what your metric is here). If anyone enables starhugger-auto-mode, _any_ subsequent action they perform is going to load all of starhugger.el in anyway, due to the post-command-hook.
> 
> > They are literal URLs
> 
> Yes, only worry about the checkdocs within reason. But the long curl command in `starhugger-retry-temperature-range` actually triggers a byte-compile warning that users will see during install and you should strive to fix it. The command in that function looks feasible to add another escaped linebreak to, or there's a local variable you can set that will let the byte-compiler admit longer docstrings.

**Comment by daanturo** [comment]
> Ah, I see the trick you're using. If my understanding is correct, I would (gently) discourage doing this because it strikes me as premature optimization and probably not very effective (I don't know what your metric is here). If anyone enables starhugger-auto-mode, _any_ subsequent action they perform is going to load all of starhugger.el in anyway, due to the post-command-hook.

Yes I have just abandoned that loading trick.
 
> Yes, only worry about the checkdocs within reason. But the long curl command in `starhugger-retry-temperature-range` actually triggers a byte-compile warning that users will see during install and you should strive to fix it. The command in that function looks feasible to add another escaped linebreak to, or there's a local variable you can set that will let the byte-compiler admit longer docstrings.

Also added broke curl's long command. But I still leave other URLs because after splitting, they are no longer recognized by `embark`.

**Comment by riscy** [comment]
> Yes I have just abandoned that loading trick.

I approve. :) Does this mean we can solve this package-lint?

-  241:0: warning: Private functions generally should not be autoloaded.

> But I still leave other URLs 

Yes, these are fine - I was primarily concerned with the one that was raising a *byte-compile* warning (but it's fixed now).

**Comment by daanturo** [comment]
> * 241:0: warning: Private functions generally should not be autoloaded.

`starhugger-grep-context--prefix-comments` is an internal function, also being experimental, whose usage is made via customizable `starhugger-enable-dumb-grep-context`, I need to autoload it to inform its source location.

**Comment by riscy** [comment]
It looks like this is a workaround for the circular import between starhugger.el and starhugger-grep-context.el.  I think relying on the autoload facilities in this workaround is a bad idea -- autoloading shouldn't be a requirement for being able to correctly use the functions in a given emacs lisp file (even in the face of a circular import).

Really I'd recommend reorganizing the code so that the circular import isn't an issue.  Alternatively, better than relying on the existence of an autoload, would be to rewrite the `starhugger--async-prompt`'s form to include a `require`:
```elisp
    (if starhugger-enable-dumb-grep-context
        (require 'starhugger-grep-context)
        (starhugger-grep-context--prefix-comments wrapped-callback)
```
and remove the autoload on the private function.  This will give you effectively the same behavior, but someone who simply drops your files in their load-path (for example) won't run into mysterious errors due to missing autoloads.

**Comment by daanturo** [comment]
> Really I'd recommend reorganizing the code so that the circular import isn't an issue. Alternatively, better than relying on the existence of an autoload, would be to rewrite the `starhugger--async-prompt`'s form to include a `require`:
> 
> ```emacs-lisp
>     (if starhugger-enable-dumb-grep-context
>         (require 'starhugger-grep-context)
>         (starhugger-grep-context--prefix-comments wrapped-callback)
> ```
> 
> and remove the autoload on the private function. This will give you effectively the same behavior, but someone who simply drops your files in their load-path (for example) won't run into mysterious errors due to missing autoloads.

Thanks for the suggestion, I've done that.

**Comment by riscy** [comment]
Thanks again -- and welcome to MELPA. :)

**Pull request merged**
