### PR TITLE
recipes/helm-sly: Add helm-sly

### PR DESCRIPTION
**Pull request by Ambrevar**
### Brief summary of what the package does

Like Helm-SLIME for SLY: Helms for apropos, Lisp connections, xrefs.

### Direct link to the package repository

https://github.com/emacs-helm/helm-sly

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

The code is mostly inherited from Helm-SLIME, hence some dated functions and lacking docstrings.  I've committed some significant work to dust the code.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Any update on this?

**Comment by riscy** [comment]
A quick pass over the checklist:

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
helm-sly.el:92: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:107: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:110: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:113: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:116: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:119: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:122: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:125: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:152: Argument `candidate' should appear (as CANDIDATE) in the doc string
Warning (emacs): 
helm-sly.el:158: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:161: First line is not a complete sentence
Warning (emacs): 
helm-sly.el:189: Argument `candidate' should appear (as CANDIDATE) in the doc string
Warning (emacs): 
helm-sly.el:230: You should convert this comment to documentation
Warning (emacs): 
helm-sly.el:260: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:297: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:302: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:305: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:334: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:339: Argument `name' should appear (as NAME) in the doc string
Warning (emacs): 
helm-sly.el:352: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:401: Argument `xref-alist' should appear (as XREF-ALIST) in the doc string
Warning (emacs): 
helm-sly.el:410: Argument `location' should appear (as LOCATION) in the doc string
Warning (emacs): 
helm-sly.el:421: First line is not a complete sentence
Warning (emacs): 
helm-sly.el:435: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:441: All variables and subroutines might as well have a documentation string
Warning (emacs): 
helm-sly.el:447: Argument `xrefs' should appear (as XREFS) in the doc string
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191027.20):
```
1 issue found:

417:14: error: You should depend on (emacs "25.1") if you need `alist-get'.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

Added miscellaneous hints (automated):
- helm-sly.el#L461: Advice functions should be sharp-quoted; use `#'`

**Comment by Ambrevar** [comment]
Thanks, should mostly be fixed now.

**Comment by riscy** [comment]
Looks good -- there's still one more checkdoc nag:
```
helm-sly.el:467: Argument `xrefs' should appear (as XREFS) in the doc string
```

I like that `helm-sly-connection-actions` is customizable.  A minor thing is you might want to be explicit about the group `helm-sly` using:
```
(defgroup helm-sly nil
  "Helm sources and some utilities for SLY."
  :prefix "helm-sly-"
  :group 'helm
  :link '(url-link :tag "GitHub" "https://github.com/emacs-helm/helm-sly"))
```
This way when someone does <kbd>M-x customize-group helm</kbd> they'll see helm-sly and its variables under the list too.

Neither of those look like blockers to me, but I trust you'll fix the checkdoc one when you get a chance.  Thanks!

**Comment by Ambrevar** [comment]
Done, and thanks for merging!

**Pull request merged**
