### PR TITLE
Remove canary from pull request template; update doc

### PR DESCRIPTION
**Pull request by riscy**
1. I like the idea for the pull request canary ("I have confirmed these without doing them") which I believe was @purcell's add.  But in my experience it doesn't provide a strong signal, and also sometimes trips up people who aren't English-fluent.
2. The information in the pull request template is repeated in CONTRIBUTING.md.  That document is already quite long, and I thought it might be a good idea to deduplicate.

### CODE REVIEW

**Comment by tarsius** [comment]
1. Sure, kill the bird.
2. Those are trivial things to do *while* opening a pr, so I agree it doesn't have to be in the "things to think about before opening a pr" document.

**Review by tarsius — APPROVED** [review]
1. Sure, kill the bird.
2. Those are trivial things to do *while* opening a pr, so I agree it doesn't have to be in the "things to think about before opening a pr" document.

**Comment by tarsius** [comment]
By the way, I've been thinking that we should use the beta [issue forms feature](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) for a while. But unfortunately that [isn't supported](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#about-yaml-syntax-for-issue-forms) for pull-requests. Who knows, maybe one day.

But we could already create different "markdown" pull-request templates for recipe additions, migrations and modifications.

Also, since many seem unable to *replace* the space in `[ ]` with an X, maybe just go with `[]`?

**Comment by riscy** [comment]
> But we could already create different "markdown" pull-request templates for recipe additions, migrations and modifications.

Yeah, it's funny that GitHub only seems to support adding a template for one "kind" of PR.  But I'm with you on this -- I think it makes sense to look at how much this could help.

> maybe just go with `[]`?

This sounds reasonable (fewer keystrokes for everyone).  I'll push that one here and merge, and we'll see if there's any feedback.

**Comment by riscy** [comment]
> GitHub only seems to support adding a template for one "kind" of PR

Perhaps [I spoke too soon](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository).

**Pull request merged**
