### PR TITLE
Add recipe for ursa-ts-mode

### PR DESCRIPTION
**Pull request by rrthomas**
### Brief summary of what the package does

Editing mode for the Ursa programming language.

### Direct link to the package repository

https://github.com/ursalang/ursa-ts-mode

### Your association with the package

I’m the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Code appears good, but a couple issues --

`ursa-ts-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ursa-ts-mode.el#L3: Have you done the paperwork to assign this copyright?
```
Perhaps this is here because you adapted this from json-ts-mode but a lot of users leave this line in without checking.

Your license boilerplate is also not machine-detectable because it says "This pacakge is free software:" instead of "This *package* is free software:"

Your `Commentary` says where the code came from, but not anything about the package.  What's ursa?

**Comment by rrthomas** [comment]
Thanks very much for the review!

> - ursa-ts-mode.el#L3: Have you done the paperwork to assign this copyright?

I have a copyright assignment on file for Emacs. I guess that is strictly not useful until/unless this mode gets in to Emacs proper.

> Perhaps this is here because you adapted this from json-ts-mode but a lot of users leave this line in without checking.

Indeed, the code is basically copied, and the changes are relatively minor, but I've added my own copyright too.

> Your license boilerplate is also not machine-detectable because it says "This pacakge is free software:" instead of "This _package_ is free software:"

Oosp, thanks.

> Your `Commentary` says where the code came from, but not anything about the package. What's ursa?

I've addressed that now: Ursa's a new programming language I'm developing. It's at a fairly toy stage, but I'm trying to develop editor support and other affordances early in the process. See https://github.com/ursalang

**Comment by riscy** [comment]
Looks good, and thanks for clarifying re: Ursa (I googled and there are a few mentions of this term in different computing contexts, so I think this is good disambiguation).

I seem to have overlooked one more thing, which is that the repository itself needs a LICENSE file or equivalent (see: https://github.com/licensee/licensee) but this should be a quick merge after that.

**Comment by rrthomas** [comment]
I've added `LICENSE`.

**Comment by rrthomas** [comment]
Not sure if this fell through the cracks? I think I've done everything required now, but do let me know if there's anything else!

**Comment by riscy** [comment]
Hi @rrthomas -- sorry for the wait, I am usually only here on my weekends (and mostly Sundays lately.)  I do everything in a big batch and so my replies are often not real-time.

In any case, looks good to go.  Merging!

**Comment by rrthomas** [comment]
Thanks @riscy, I figured it might be that, but equally I wondered if perhaps my last quick update got lost!

**Pull request merged**
