### PR TITLE
add etop-mode

### PR DESCRIPTION
**Pull request by akacase**
### Brief summary of what the package does

etop allows users to view top and act upon pids via an emacs buffer.

### Direct link to the package repository

https://github.com/akacase/etop

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by DamienCassou** [comment]
Some feedback:

- you might want to explain the difference with the builtin `M-x proced`.
- please run linters on your code (flycheck + flycheck-package). This would have told you about a few errors:
   - missing `Package-requires` line with emacs 24 (because of lexical bindings)
   - first line of docstring for `etop-mode-generate-top-command-function` and `etop-mode-fill-buffer` are not a sentence
    - no docstring for `etop-mode-member-at-least-one`
    - the footer should not have a blank line after the `provide` line
- you might want to add docstrings to your variables
- use `--` after package name prefix for private functions and variables (e.g., `etop-mode--overlay-list`)
- instead of `if COND nil BODY` you can use `when` or `unless`
- I don't understand the `if etop-mode-map` before adding keys to it. It's value should be nil because this is how it is defined the line above. I suggest the more standard following code:

    ```emacs
    (defvar etop-mode-map
      (let ((map (make-sparse-keymap)))
        (define-key map "n" #'etop-mode-next-line)
        ...)))
    ```

**Comment by akacase** [comment]
Thanks for the feedback! I was unaware of M-x proced, so I wrote this. I'm not one for duplication, so I'll close this.

**Comment by DamienCassou** [comment]
- please make first line of docstring for `etop-mode-column-header-regexp` a complete sentence instead of just adding a `.` at the end :-)
- the docstring of `etop-refresh-rate` does not specify the unit (milliseconds, seconds, minutes?)
- please use `define-derived-mode` with parent `special` instead of the home-made function `etop-mode`.

**Comment by akacase** [comment]
I can fix all these issues, I just don't think the package should really exist at this point, since it's duplicating the behavior of M-x proced. I appreciate all the feedback.

**Comment by DamienCassou** [comment]
- in `etop-mode-fill-buffer`, you can pass the result of `get-buffer-create` as first argument of `with-current-buffer` to merge the first two lines
- please let-bind `inhibit-read-only` instead of temporarily setting it with `setq`.

**Comment by purcell** [comment]
> I can fix all these issues, I just don't think the package should really exist at this point, since it's duplicating the behavior of M-x proced. I appreciate all the feedback.

Cool, thanks @akacase!

**Pull request closed without merging**
