### PR TITLE
Add recipe for awk-snippets

### PR DESCRIPTION
**Pull request by uberkael**
### Brief summary of what the package does

Awk Emacs yasnippet snippets

### Direct link to the package repository

https://github.com/uberkael/awk-yasnippets

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`awk-yasnippets.el` with checkdoc 0.6.2:
```
awk-yasnippets.el:44: All variables and subroutines might as well have a documentation string
```

`awk-yasnippets.el` with package-lint 20230315.1052:
```
4 issues found:
9:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
39:0: error: "awk-snippets-root" doesn't start with package's prefix "awk-yasnippets".
43:0: error: "awk-snippets-initialize" doesn't start with package's prefix "awk-yasnippets".
50:1: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
```
I think the `eval-after-load` is okay in the yasnippets world.  You should figure out what this package should be called -- `awk-yasnippets` or `awk-snippets` -- and get all of these names aligned.  That will also solve some of the nags below.

Package and license:
- Prefer the default recipe or `:defaults`, if possible.  (Can you use `:defaults` instead of `*.el`?  It's the better choice.)
- No .el file matches the name 'awk-snippets'
- Can't check package-requires if there is no 'main' file

**Comment by uberkael** [comment]
Thanks, I will check it.

**Comment by uberkael** [comment]
I did update the repositories if you can take a look.
Thanks.

**Comment by riscy** [comment]
Thank you for accommodating.  Here's the latest --

`awk-yasnippets.el` with checkdoc 0.6.2:
```
awk-yasnippets.el:43: All variables and subroutines might as well have a documentation string
```
Minor and fyi.

`awk-yasnippets.el` with package-lint 20230315.1052:
```
2 issues found:
9:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
49:1: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
```
The `finder-known-keywords` issue still persists.  It's minor, but as long as package-lint is warning about it I think we should address it (and it is very easy to address).  Check out the documentation surrounding the mentioned variable and add one of the controlled keywords it lists, and this should be good to go.

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to reach out.

**Comment by uberkael** [comment]
I have updated the code to fix the warnings, let me know if there is something missing.

Thanks.

**Comment by riscy** [comment]
Thanks, looks good now.  This produces an interesting shorthand for writing awk.

Merging -- and, welcome to MELPA. :)

**Pull request merged**
