### PR TITLE
Add cubicle-mode for the model checker Cubicle

### PR DESCRIPTION
**Pull request by mebsout**
### Brief summary of what the package does

This package provides a major mode for editing files for the [model checker Cubicle](https://github.com/cubicle-model-checker/cubicle).

### Direct link to the package repository

https://github.com/cubicle-model-checker/cubicle/blob/master/emacs/cubicle-mode.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks.
- You'll need to be specific about the license. You should include the standard GPL 3 header in the elisp file, as inserted by `M-x auto-insert` if you try that in an empty `.el` file.
- `"\\.cub$"` in the file regexp should be `"\\.cub\\'"`, to match end-of-string rather than end-of-line.
- It's not appropriate to override `compile-command` in a major mode. Users can set this in a file-local or directory-local variable if they wish. And, of course, `(buffer-file-name)` will sometimes be nil, and can change through the course of the buffer's lifetime, so you can't correctly set it in a major mode anyway.
- The box around the commentary text should be removed: it will confuse the core Emacs functions that are used to extract that text for the purposes of providing a package description (and also for the MELPA package page).

**Comment by tarsius** [comment]
@mebsout Friendly ping!

**Comment by mebsout** [comment]
Sorry for the delay, the previous comments have been addressed in https://github.com/cubicle-model-checker/cubicle/commit/8dbb250

Cheers

**Comment by tarsius** [comment]
It doesn't seem appropriate to place an Emacs package below a folder intended for documentation.  You might even want to consider placing it in a completely separate repository. That doesn't really matter as far as Melpa is concerned but it helps adding the package to the [Emacsmirror](https://emacsmirror.net).

**Comment by tarsius** [comment]
Thanks!

**Pull request merged**
