### PR TITLE
Add kdeconnect recipe

### PR DESCRIPTION
**Pull request by carldotac**
### Brief summary of what the package does

This package provides helper functions to use [KDE Connect](https://community.kde.org/KDEConnect) functionality, like sending files to Android devices or making your phone ring, from within Emacs.

This is my first Emacs package. While I have tested its build and looked over past pull requests for common errors, I'm still pretty green with Emacs Lisp. So if I should change anything just let me know!

### Direct link to the package repository

https://github.com/carldotac/kdeconnect.el

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
https://github.com/carldotac/kdeconnect.el/blob/a3ffa9f3033cbc4feb63b0a547cf983fac060db8/kdeconnect.el#L88-L89

Does this error message depends on locale ? If it depends, it should use exit code instead of message content.

**Comment by syohex** [comment]
https://github.com/albertvaka/kdeconnect-kde

It looks error messages depend on locale. For example, Japanese environment users may get `デバイスは見つかりませんでした` instead of `No devices found`.

**Comment by carldotac** [comment]
Thank you for that! Unfortunately, returning no devices isn't an error from kdeconnect-cli's perspective, so I can't use stderr.

To make kdeconnect.el locale-agnostic, I've added a variable where the user can place their desired devices instead of parsing shell output. This also makes switching between devices much quicker.

**Comment by syohex** [comment]
Thanks for updating code. BTW Environment variable can be replaced temporary as below.

```lisp
(let ((process-environment (cons "LANG=C" process-environment)))
  (shell-command-to-string "kdeconnect-cli -a --id-only"))
```

**Comment by purcell** [comment]
Thanks - will merge in a moment, but just a couple of notes:

Firstly, `kdeconnect-active-device` should probably be quoted using `shell-quote-argument` before inserting it into command strings, just to be safe.

Secondly,
```el
(defun kdeconnect-select-active-device ()
  "Choose the active device from all available ones."
  (interactive)
  (setq kdeconnect-active-device
        (completing-read
         "Select a device: "
         (split-string kdeconnect-devices "," t)
nil t "")))
```
would be a little nicer/more idiomatic written like this IMO:
```el
(defun kdeconnect-select-active-device (name)
  "Set the active device."
  (interactive
   (list (completing-read
          "Select a device: "
          (split-string kdeconnect-devices "," t)
          nil t ""))))
  (setq kdeconnect-active-device name)
```
then you can also use it as a regular function.

**Pull request merged**
