### PR TITLE
Add org-babel-eval-in-repl recipe

### PR DESCRIPTION
**Pull request by diadochos**
### Brief summary of what the package does

Send and eval org-mode babel code blocks in various REPLs.

### Direct link to the package repository

https://github.com/diadochos/org-babel-eval-in-repl

### Your association with the package

I'm the creator and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- Depend on the stable version of `eval-in-repl`, see https://stable.melpa.org/#/eval-in-repl
- Don't depend on `org-plus-contrib`. The versions of `org` in recent Emacs versions will work fine with this package. Just omit the org dependency.
- You can delete the `-pkg.el` file: all the necessary metadata is in the `.el` file, and it's not necessary to duplicate it.

**Comment by diadochos** [comment]
Awesome, thank you. I've fixed them up. Would you please check again?

**Comment by purcell** [comment]
Great, thanks - looks good.

**Comment by diadochos** [comment]
@purcell Thanks a lot!

**Pull request merged**
