### PR TITLE
Added new package EMACROS

### PR DESCRIPTION
**Pull request by CsBigDataHub**
### Brief summary of what the package does

Emacros: A Package for Organizing and Handling Keyboard Macros in GNU Emacs

### Direct link to the package repository

https://github.com/CsBigDataHub/emacros

### Your association with the package

I am a maintainer

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback

fixed everything but these two issues

```error
2 issues found:

1:68: warning: You should depend on (emacs "24") if you need lexical-binding.
83:0: error: "find-file-hook" doesn't start with package's prefix "emacros".

```

- [x] My elisp byte-compiles cleanly
    
   yes but with one warning 

```warning
emacros.el:852:1:Warning: Lexical argument shadows the dynamic variable
    custom-file
```
- [x] `M-x checkdoc` is happy with my docstrings

- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi, thanks for this.  A quick automated pass and then some comments after that:

byte-compile-file (using Emacs 26.3):
```
emacros.el:852:1:Warning: Lexical argument shadows the dynamic variable
    custom-file
```
I would recommending fixing such warnings, at the very least so you and your users can experience a silent byte-compile.  Sometimes warnings indicate semantic errors and it's good to be strict about them early on in a project, when you can.

checkdoc (using version 0.6.1):
```
Warning (emacs): 
emacros.el:62: First line is not a complete sentence
Warning (emacs): 
emacros.el:105: First line is not a complete sentence
Warning (emacs): 
emacros.el:110: First line is not a complete sentence
Warning (emacs): 
emacros.el:110: Lisp symbol `exit-minibuffer' should appear in quotes
Warning (emacs): 
emacros.el:151: Some lines are over 80 columns wide
Warning (emacs): 
emacros.el:151: Lisp symbol `minibuffer-complete-and-exit' should appear in quotes
Warning (emacs): 
emacros.el:163: First line is not a complete sentence
Warning (emacs): 
emacros.el:163: Argument `letgo' should appear (as LETGO) in the doc string
Warning (emacs): 
emacros.el:647: Keycode C-g embedded in doc string.  Use \\<keymap> & \\[function] instead
Warning (emacs): 
emacros.el:703: First line is not a complete sentence
Warning (emacs): 
emacros.el:801: Argument `arg' should appear (as ARG) in the doc string
Warning (emacs): 
emacros.el:836: Name emacs should appear capitalized as Emacs
Warning (emacs): 
emacros.el:853: Some lines are over 80 columns wide
Warning (emacs): 
emacros.el:853: Argument `macro-file' should appear (as MACRO-FILE) in the doc string
Warning (emacs): 
emacros.el:890: Some lines are over 80 columns wide
Warning (emacs): 
emacros.el:890: Argument `kbd-macro' should appear (as KBD-MACRO) in the doc string
Warning (emacs): 
emacros.el:903: Argument `symbol' should appear (as SYMBOL) in the doc string
Warning (emacs): 
emacros.el:918: Argument `symbol' should appear (as SYMBOL) in the doc string
```

package-lint-current-buffer (using version 20200419.406):
```
2 issues found:
1:68: warning: You should depend on (emacs "24") if you need lexical-binding.
83:0: error: "find-file-hook" doesn't start with package's prefix "emacros".
```
The first can be disregarded since you don't rely on 24 -- the line `(defvar find-file-hook nil)` can just be written `(defvar find-file-hook)` if you want to tell the byte-compiler the variable exists.  Or just `(require 'files)`.

Suggestions/experimental static checks:
- emacros.el#L937: There is no need to quote lambdas (neither #' nor ')
- emacros.el#L3: Have you done the paperwork or is this copy-pasted? :)
- emacros.el#L37: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`

### Packaging ###

- Use a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- Please add a LICENSE or COPYING file to the repository


### Other comments

With those out of the way, it looks like what you are aiming for here is a minor mode.  Simply loading a file should not modify Emacs's behavior, for the most part, but a line like this:
```elisp
(or (memq 'emacros-load-macros find-file-hook)
    (setq find-file-hook (cons 'emacros-load-macros find-file-hook)))
```
clearly spells out minor-model to me.

Without looking too deeply into it, the many `let` forms of this nature look suspicious to me:
```elisp
(let ((find-file-hook nil)
      (emacs-lisp-mode-hook nil)
      (after-save-hook nil)
      (kill-buffer-hook nil))
```
This is a pretty wild move.  And in some cases it might be necessary to perform certain operations, but the fact that it appears multiple times throughout the source code (rather than quarantined inside a carefully commented function), and even inside a `while` loop in one case, suggests to me that the code may need some deeper reworking before being ready for prime-time.  But I haven't looked too deeply.

A couple of elisp tips I have for you: if your `if` has no `else`, you can use a `when` instead -- and when you do that, you don't have to wrap consecutive statements in a `progn`.  If you find yourself going multiple levels deep with `if` and `let` and `if` and `let` it may be time to thing about writing a function to increase understandability.

Let me know if you have any questions!

**Comment by CsBigDataHub** [comment]
@riscy ,

Thanks. This might take a while for me to look in to. Original author of this package created it for Emacs 22. I merely stumbled upon it and though it was great. I have made few modifications to support emacs 26.1 and started using it. 

As I am pretty new to emacs lisp, I would need to find a little free time to comprehend the code and try to make changes.

**Comment by riscy** [comment]
I see!  Let's for sure keep this open then.  I'm curious to spend some time in the README to figure out more about this.  Emacs 22 is over a decade ago (!) but still feels relatively recent to me. :P

**Comment by CsBigDataHub** [comment]
@riscy Link for the original code is in the [acknowledgment](https://github.com/CsBigDataHub/emacros#acknowledgment) section of README.

**Comment by CsBigDataHub** [comment]
@riscy  I was just trying to test this with emacs 27 and emacs just crashed at startup. I wanted to recompile the packages in emacs27 so I deleted `elpa` directory `.emacs.d` and this package is failing to compile.

**Comment by tarsius** [comment]
What's the situation here?

**Comment by riscy** [comment]
On a very quick glance I think some of the original issues are still there -- @CsBigDataHub can you confirm?  It may make sense to close this PR until some of the kinks can be worked out.

**Comment by CsBigDataHub** [comment]
Sure , will do that. Will reopen again when it is ready.

**Pull request closed without merging**
