### PR TITLE
Added rdxmk recipie

### PR DESCRIPTION
**Pull request by jsalzbergedu**
### Brief summary of what the package does

rdxmk is a small set of tools for [redox](https://github.com/redox-os/redox) development. It provides convince functions for building redox, a mode for dealing with buffers in the redox directory, and prevents Emacs from messing up redox' build system.

### Direct link to the package repository

https://github.com/jsalzbergedu/rdxmk

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

I am the upstream package maintainer.

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick feedback:
- You can just delete the `-pkg.el` file: all the necessary metadata for MELPA is in `rdxmk.el`, so there's no need to duplicate it.
- I'm almost certain you can replace `rdxmk-recurse-for-file` with `locate-dominating-file`. (Many people seem to independently reinvent the latter in their packages!) Plus, this way you can avoid that nasty `substring ... 0 -8` everywhere.
- When building shell commands with `concat`, you should be using `shell-quote-argument` to avoid horrible things happening when paths contain spaces, quotes or other special characters.
- [This munging of global hooks](https://github.com/jsalzbergedu/rdxmk/blob/a67c79ec0eebdc619212b5961df9301667eb5b53/rdxmk.el#L141-L142) is bad practice: you should handle this by writing a global minor mode that the user can *choose* to enable. See `define-globalized-minor-mode`.
- `"rdxmk's customization group"` should instead be `"Tools for redox development"`

Hope that helps!

**Comment by jsalzbergedu** [comment]
Thank you very much! I'll fix those things as soon as I can. Should I leave this PR open until I have, or close it and reopen it when those are fixed?

**Comment by purcell** [comment]
Feel free to leave the PR.

**Comment by jsalzbergedu** [comment]
I believe I have addressed those issues with [this commit!](https://github.com/jsalzbergedu/rdxmk/commit/93a57bd51f0f48b2425aeb5cb79121cad831371e) Thank you for helping me get rid of those brittle hacks, and if there is anything you think I should change, I would be grateful for you to let me know

**Comment by purcell** [comment]
Thanks - I sent you a few little fixes in https://github.com/jsalzbergedu/rdxmk/pull/4. Please also run `M-x checkdoc`, which will help you format your docstrings according to the conventions.

**Comment by jsalzbergedu** [comment]
Thank you again! `M-x checkdoc` had me fix one of my docstrings, I hope that I got them all in order... Thank you very much for going out of your way to get this package up to standards.

**Comment by purcell** [comment]
Thanks! Sorry for the delay in merging this.

**Pull request merged**
