### PR TITLE
Add doct recipe

### PR DESCRIPTION
**Pull request by progfolio**
### Brief summary of what the package does
doct (declarative Org capture templates) defines an alternative, declarative syntax for Org capture templates

### Direct link to the package repository
https://github.com/progfolio/doct

### Your association with the package
Maintainer

### Relevant communications with the upstream package maintainer
None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
I've been following your progress in your Reddit posts.  Glad to see it progressing.

Quick feedback, the same I give to all Org-related packages: the name should have `org` in it.  `doct` doesn't suggest anything Org related; I would guess it referred to something related to Microsoft Word templates.  So I'd suggest naming the package `org-dct`.

BTW, have you made any progress regarding integrating it into Org proper?

**Comment by progfolio** [comment]
I'm open to renaming the package if necessary.

I haven't started any discussion on the Org dev list just yet. Ideally I'd like to get some more feedback from users of the package to see if I've missed the mark on anything first.

As always, appreciate the feedback.

**Comment by riscy** [comment]
The checklist looks good -- thank you for sticking closely to it!  A couple small checks I can quickly add before taking a deeper look:

- doct.el#L244: It's safer to sharp-quote function names; use `#'`
- doct.el#L247: It's safer to sharp-quote function names; use `#'`
- betewen -> between
- occurence -> occurrence
- Replace %doct(KEYOWRD)  -> KEYWORD
- poperty -> property
- creat -> create

@alphapapa has good advice about adding org to the name (my first guess was something to help with documenting source code or similar), although there are of course a few packages on MELPA that are org-related and lack org somewhere in their name.

**Comment by progfolio** [comment]
Thank you for taking the time to look the code over.
Took care of the typos and the sharp quotes. Changes on latest master.

Let me sleep on the name change and I'll get back to you about it tomorrow.
Thanks again.

**Comment by alphapapa** [comment]
It would be more consistent with the naming convention to have an `org-` prefix.  That prefix makes discovering Org-related packages very easy.  Consider `package-list-packages`, and that a name like `doct-org` will be sorted far from all the `org-` packages.

**Comment by progfolio** [comment]
I think my main gripe with renaming it is having to read/maintain code with an even longer faux namespace prefix. Leaning toward keeping it as "doct", but I'll sleep on it and try to think of some more names tomorrow.

**Comment by alphapapa** [comment]
You don't have to tell me.  At least `org-dct` isn't nearly as long as names like `org-super-agenda` and `org-recent-headings`.  ;)  You get used to it after a while.  And there's always https://github.com/Malabarba/Nameless if it bothers you that much.

**Comment by progfolio** [comment]
@alphapapa Yeah, it's a shame namespaces haven't found their way into Elisp yet. Nameless does look like it could help a bit. Thanks for pointing that out.

@riscy I think I'd like to keep the name "doct" if that's OK. If it's a blocker, I'll rename. Thanks again.

**Comment by riscy** [comment]
Okay -- it isn't a MELPA requirement (yet?).  Sorry @alphapapa (I think it's good to continue to encourage this convention even if it's not always successful).  In any case, since the package summary is `DOCT: Declarative Org capture templates` it will remain searchable under the keyword "org", which is a good minimum.

Not a blocker, but for your consideration:
- doct.el#L25: Prefer `https` over `http` (if possible)

...and, welcome to MELPA. :)

**Comment by progfolio** [comment]
Thanks!

**Pull request merged**
