### PR TITLE
Add recipe for flymake-collection

### PR DESCRIPTION
**Pull request by mohkale**
Hi, this is a prepratory PR for an impending rename to my package `flymake-rest` to `flymake-collection`. It isn't ready to be merged yet, I just wanted to open this PR to ask what the recommended process for such a transition would be? I was hoping to keep both recipes up for a brief period, archiving the repo for the old one (after committing a message that tells users to migrate).

### CODE REVIEW

**Comment by tarsius** [comment]
It would recommend deleting the new, uninitialized repository and then renaming the old repository to the new name. That way old issues are preserved. If someone visits the old url, then Github redirects them to the new. Also add `:old-names (flymake-rest)` to the recipe.

**Comment by mohkale** [comment]
@tarsius 

Thanks for the advice. Atm I'm adding a CI/CD pipeline and test-suite to my package, but I intend to delete the new flymake-collection repo and rename the existing one to flymake-collection as you've suggested. I just want to confirm whether this would break any existing installs? I've already done a major version bump and I've marked any user facing functions with obsolete aliases pointing to the old names. Is there anything else that needs to be done for a smooth transition?

**Comment by mohkale** [comment]
Update: I've performed the rename now and updated this recipe as well. Please let me know if anything else needs to be done :-).

**Comment by riscy** [comment]
Looks like the above has been cleared up, but the repository in its current state will not currently build on MELPA -- I re-ran the build so you can check the logs.  The issue is that the softlinks in the repository are causing issues and need to be removed for the build to run correctly.

**Comment by tarsius** [comment]
Adding symlinks in the top-level directory to libraries in a sub-directory is really weird. No other package does that. Please consider not doing that. Just delete the symlinks and update the recipe to look for `src/*.el`.

**Comment by tarsius** [comment]
Ah, @risky already pointed that out too. :grinning: 

I can add to that the symlinks also cause the Emacsmirror tools to fail.

**Comment by mohkale** [comment]
Apologies. I added them just because the change broke some users installs. The plan was to remove them as soon as the recipe was updated, but I didn't realise that would break melpa or emacsmirror. I've reverted the commit in a separate branch which the recipe now points to (and so that users can still install it). Once this recipe is updated I'll remove it from the master branch as well.

**Comment by alternateved** [comment]
Sorry @mohkale for the trouble and thank you for helping out with this then.

**Comment by mohkale** [comment]
Ping.

**Comment by riscy** [comment]
Hi @mohkale -- we see this, but please be patient.  I'm usually active here on weekends.

**Comment by mohkale** [comment]
@riscy apologies I didn't mean to pressure you. Thanks for all the great work :-).

**Comment by riscy** [comment]
No worries, I should have put a smiley or rephrased to better convey my tone. :)  I just wanted to let you know I wasn't leaving you hanging.

I notice the recipe is selecting a `release` branch now instead of the default one -- technically this is fine but MELPA recipes are more future-proof if they can just point to the default branch, which you could then rename.

No blockers to merging, but I'll wait to hear back about the above (the branch) before I hit merge.

**Comment by mohkale** [comment]
@riscy

> technically this is fine but MELPA recipes are more future-proof if they can just point to the default branch

Makes sense, I've renamed the default branch to release now :-).

**Comment by mohkale** [comment]
@riscy I can't seem to install flymake-collection through straight. It's failing with a malformed recipe message but isn't much more descriptive. Do you know what could be causing this?

**Comment by riscy** [comment]
I'm not sure (not a straight.el user) but I wonder how straight handles `old-names` in recipes.  You could check another recipe that uses that attribute, like `highlight-numbers` or similar, and see if that's causing the issue?

**Comment by mohkale** [comment]
> You could check another recipe that uses that attribute, like highlight-numbers or similar, and see if that's causing the issue?

That recipe works fine, I'll follow up on straight itself. Probably a good opertunity to work on a more descriptive error message for this situation. Thanks :-).

**Pull request merged**
