### PR TITLE
add narumi recipe.

### PR DESCRIPTION
**Pull request by nryotaro**
### Brief summary of what the package does
narumi-mode is a major mode that shows a dashboard.
It shows random sampled image in a directry, bookmarks, and recent files.
You can change the wallpaper to the image on the dashboard.
Since it is a dashboard,
you can go to the entries of bookmarks and recent files by clicking them.

### Direct link to the package repository

https://github.com/nryotaro/narumi

### Your association with the package

I am the author of the package.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
From the CI check:

> Single file narumi-mode.el does not match package name narumi

The package should be named `narumi-mode`.

**Comment by tarsius** [comment]
@purcell @riscy What's the convention here? If a package consists of a major-mode for a something like a programming language or some kind of text, then I think it makes sense to name it `<foo>-mode`. IMO in such cases the symbol-prefix rule ought to be relaxed, i.e. `<foo>-` is perfectly find, insisting on `<foo>-mode` would be to much.

Here the situation is a bit different. @nryotaro sorry for not taking a closer look before commenting on the package name. This is *not* a programming/text major-mode but an "application". IMO such packages should not be named `<foo>-mode`, and the feature should also be just `<foo>`, the file `<foo>.el` and the prefix `<foo>-`. (But lets wait for comments from others before making any changes.)

**Comment by nryotaro** [comment]
@tarsius Thank you for your feedback. I will wait for their comments.

**Comment by riscy** [comment]
@nryotaro I think `narumi` is a perfect name for this package.

More verbosely -- I've never formalized these so I had to check my assumptions, but I agree with what @tarsius wrote above.  In general, I think there should be a little bit of creative wiggle room around using `-mode` to help clarify what a package actually is.  In this case, I agree with not adding `-mode` to the end of this package name, but I wouldn't personally block on that basis either.

> IMO in such cases the symbol-prefix rule ought to be relaxed, i.e. <foo>- is perfectly find, insisting on <foo>-mode would be to much.

I just confirmed package-lint already makes exceptions for this, and I also have some rudimentary checks on my end to check if `<foo>-mode` exists when indexing a `<foo>` on MELPA.

@nryotaro, I had a quick check and see only a couple minor issues in the code; non-blocking.

- You should ideally run a `M-q` (fill-paragraph) on your `;;; Commentary` block; neither the MELPA index nor Emacs will prettify that block of text for you
- narumi-mode.el#L116: Single-line comments should usually begin with `;;`
- narumi-mode.el#L244: Single-line comments should usually begin with `;;`
- Back/front quotes are typically to create hyperlinks in the builtin Help and aren't required around variable names in docstrings, e.g. ``` `WALLPAPER-PATH' ```
- directry -> directory

Let me know when you're happy with the package name and I'll take another look!

**Comment by nryotaro** [comment]
@riscy @tarsius 
Thank you for your feedback.
I renamed narumi-mode to narumi, and fixed the issues.

**Comment by riscy** [comment]
Thanks @nryotaro.  One more thing (not a blocker) is that `random` is misspelled in the summary line, but maybe more importantly it might be worth mentioning `sway` somewhere in there to help discoverability.  For example, "Display a randomly sampled image e.g. using sway"

**Comment by nryotaro** [comment]
@riscy Thank you. I fixed the issue.

**Pull request merged**
