### PR TITLE
add recipe for npm.el

### PR DESCRIPTION
**Pull request by shaneikennedy**
### Brief summary of what the package does

This is an npm client for emacs

### Direct link to the package repository

https://github.com/shaneikennedy/npm.el

### Your association with the package

I am the maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```diff
new file   Cask
@@ -0,0 +1,4 @@
+(source gnu)
+(source melpa)
+
+(package-file "npm.el")
```
```shell
$ cask; cask build
Loading package information... done
Package operations: 1 installs, 0 removals
  - Installing [ 1/1] emacs (25.1)... already present
Compiling /home/conao/dev/forks/npm.el/npm.el...

In toplevel form:
npm.el:29:1:Error: Cannot open load file: No such file or directory, transient                                                                           
```

It seems `Package-Requires` lacks `transient` specification?

**Comment by shaneikennedy** [comment]
Thanks, @conao3 ! Just updated the recipe repo.

**Comment by riscy** [comment]
Hi, thanks for this -- a quick first pass.

### npm.el ###

byte-compile-file (using Emacs 26.3):
```
npm.el:56:1:Warning: Unused lexical argument `args'
npm.el:72:1:Warning: Unused lexical argument `args'
npm.el:142:1:Warning: Unused lexical argument `args'
In end of data:
npm.el:191:1:Warning: the function `string-join' is not known to be defined.
```
You can silence the unused arguments by renaming the variable to `_args`, assuming you're not using them.  `string-join` requires a `(require 'subr-x)`.

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200313.2338):
```
2 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
24:0: error: Package should have a non-empty ;;; Commentary section.
```
I think both of these are legitimate -- your summary could just be "Run your npm workflows".

Experimental static checks/suggestions:
- npm.el#L65: It's safer to sharp-quote function names; use `#'`
- npm.el#L81: It's safer to sharp-quote function names; use `#'`
- npm.el#L107: It's safer to sharp-quote function names; use `#'`
- npm.el#L151: It's safer to sharp-quote function names; use `#'`

### Loadability ###

Running #'load on each file (empty output is good):
```
Done.
```

### Similarly named packages ###

- npm-mode https://melpa.org/#/npm-mode

Is there any distinction to be made here?  Based on summary alone, it seems to cover a similar usage space.

**Comment by shaneikennedy** [comment]
Thanks for the review, I will try to get to this this week 👍 

They are in a similar usage space but this aims to be a client to the cli tool, rather than a mode that offers functionality based on the current buffer. I looked at npm-mode when I started this in case I could just contribute there, but the experience I wanted was too far off from what that package aims for.

Let me know if that's a sufficient reason for a new package in the npm-space, cheers

**Comment by riscy** [comment]
Looks great!

> the experience I wanted was too far off from what that package aims for.

That's a completely fine reason.   As a service to the community and/or your users, it might be worth adding a section to your README describing how your package differs, what rusty corners you're aiming to avoid with your package, etc.

Minor:
- prefic -> prefix

And, welcome to MELPA! :)

**Comment by shaneikennedy** [comment]
Thanks, @riscy ! :)

**Pull request merged**
