### PR TITLE
Add recipe for cloak-mode

### PR DESCRIPTION
**Pull request by erickgnavar**
### Brief summary of what the package does

Hide sensitive data using font properties

### Direct link to the package repository

https://github.com/erickgnavar/cloak-mode

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- checklist looks great, but have you had a chance to compare to any of the following packages:

- https://melpa.org/#/hidepw
- https://melpa.org/#/letterbox-mode
- https://melpa.org/#/password-mode

**Comment by erickgnavar** [comment]
> Thanks for this -- checklist looks great, but have you had a chance to compare to any of the following packages:
> 
> * https://melpa.org/#/hidepw
> * https://melpa.org/#/letterbox-mode
> * https://melpa.org/#/password-mode

I used to use `hidepw` but it has some problems with another packages because is relies on font-locking, also its regex patterns are global and `cloak-mode` allows to have a different pattern per major mode.

This package suits better for my workflow, that's was the motivation to make it

**Comment by riscy** [comment]
I see the distinction - that seems like it would be worth adding to your `;;; Commentary` so that people can better understand what this package is about.

On that note the usage instructions specify `(add-hook 'envrc-mode-hook 'cloak-mode)` but I feel like this is a great use case for `define-globalized-minor-mode`, with a corresponding TURN-ON function that checks whether a pattern exists for that particular mode.  This would prevent users from having to add a hook for every mode that they register in `cloak-mode-patterns`.

**Comment by erickgnavar** [comment]
I made the changes, thanks for the suggestion about `define-globalized-minor-mode`, I didn't know about that feature.

**Comment by riscy** [comment]
Thank you!  We have just one byte-compile issue:

`cloak-mode.el` with byte-compile using Emacs 28.1:
```
cloak-mode.el:29:14: Warning: reference to free variable `cloak-mode'
In global-cloak-mode-enable-in-buffers:
cloak-mode.el:29:14: Warning: reference to free variable `cloak-mode'
```

which is due to the globalized minor mode needing to be defined underneath `define-minor-mode cloak-mode`.  Should be a quick merge after.

**Comment by riscy** [comment]
Looks good - thanks!

**Pull request merged**
