### PR TITLE
add recipe for smog

### PR DESCRIPTION
**Pull request by zzkt**
### Brief summary of what the package does

Analyse the writing style, word use and readability of prose.

### Direct link to the package repository

https://github.com/zzkt/smog

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
A quick walk over the checklist:

### smog.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
```
smog.el:195:1:Warning: the function `org-update-radio-target-regexp' is not
known to be defined.
```
Does this need a specific version of org-mode to be installed?

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191220.419):
- No issues! 💯

License:
- Please add a [GitHub-compatible](https://github.com/licensee/licensee) LICENSE or COPYING file to your repository
- gpl license text appears in individual files (good)

**Comment by zzkt** [comment]
Looks like `org-update-radio-target-regexp` has been around for a while (at least defined in `ol.el` in 9.3 and core in 8.1) so I've included a dependency on `(org-mode "8.1")` and also an explicit check.

**Comment by riscy** [comment]
You'd want `(org "8.1")` in this case.

Your license appears to be undetectable by the GitHub tooling -- if you convert it into a plaintext boilerplate, I think you'll have more success?  E.g. something like [this](https://github.com/riscy/license-tests).

**Comment by zzkt** [comment]
thanks for noticing (Github uses `en_US` so I'd misspelled [LICENSE](https://www.grammarly.com/blog/licence-license/) 🤖 should be fine now)

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

1. Please add Cask file is good to easy resolve dependency, build, packaging etc.
2. Please add .gitignore file is good to ignore git stage *.elc files and .cask folder.
3. Please fix indent (one place, first column is space before tab)
4. Please use `shell-quote-argument` to create safe shell command instead of just `concat`.
5. Please consider removing `if` statement because `eq` already returns a boolean value.
6. Please consider checking executable via `executable-find` before invoking an external command.

**Comment by zzkt** [comment]
Thanks @conao3 I've merged your changes

**Comment by riscy** [comment]
Great, thanks both!

**Pull request merged**
