### PR TITLE
Add github-elpa recipe

### PR DESCRIPTION
**Pull request by 10sr**
### Brief summary of what the package does

Build personal package.el-compatible package repositories that can be easily published with GitHub Pages.

### Direct link to the package repository

https://github.com/10sr/github-elpa

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

None.

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Looks good.

**Comment by purcell** [comment]
Please depend on a non-zero version of package-build, e.g. “1.0”.

**Comment by 10sr** [comment]
@purcell Done :raised_hands:

**Comment by purcell** [comment]
Yay, thanks

**Comment by 10sr** [comment]
Thanks!

**Pull request merged**
