### PR TITLE
add recipe inline-docs

### PR DESCRIPTION
**Pull request by stardiviner**
### Brief summary of what the package does

Show inline docs in Emacs.

### Direct link to the package repository

https://github.com/stardiviner/inline-docs.el

### Your association with the package

maintainer.

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
This package requires Emacs 25.1 or higher versions. What feature does request 25.1 or higher version ? It looks there is no such feature.

**Comment by stardiviner** [comment]
@syohex I see, I copy metadata from package `eldoc-overlay-mode`, forgot to modify it. I will update it right now.

**Comment by syohex** [comment]
There is cl-lib issue(https://github.com/stardiviner/inline-docs.el/pull/3)

**Comment by stardiviner** [comment]
@syohex merged. Thanks

**Comment by purcell** [comment]
- " in Emacs" in the package description is redundant and should be removed.
- Even with the screenshot, I've no idea what this package does or why I might like to use it. Please add a `Commentary` which describes how to use the package. What does `(inline-docs "STRING")` do? Should a user call it directly?
- I'd suggest `'above` and `'below` rather than `'up` and `'down`

**Comment by stardiviner** [comment]
@purcell I updated my code from all of your suggestions.

**Comment by purcell** [comment]
Did you push your changes? I don't see them.

**Comment by purcell** [comment]
Did you push your changes? I don't see them.

**Comment by stardiviner** [comment]
@purcell sorry for my fault, I have not merged from `develop` branch. Now it is pushed. Sorry for your waiting.

**Comment by purcell** [comment]
Great, thanks!

**Pull request merged**
