### PR TITLE
Add recipe for text-categories

### PR DESCRIPTION
**Pull request by Dspil**
### Brief summary of what the package does

This package lets the user define a text category in which every character that is inserted in the buffer belongs to. That category can be changed and the next additive changes to the buffer will belong to the new category. At last, the user can delete all characters belonging to a certain text category. This can be useful when debugging code where one has to insert debugging snippets and delete them after all the bugs are found.

### Direct link to the package repository

https://github.com/Dspil/text-categories

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
This is an interesting idea, however:

> When debugging code, it is not unusual to insert print statements and other temporary code in the program to locate the bugs. After locating all of them, it is impossible to undo or revert just the code used for debugging because it will revert the bug corrections too.

Are you aware of Emacs's ability to undo in a region?  e.g. you could mark some debug code in the region and then `C-/` to undo only the changes made in that region, i.e. removing the debug code.

As well, when it comes to removing temporary code, using Magit makes it trivial to review changes to code and discard hunks that aren't needed anymore.   It only takes a few keystrokes.

Looking at the implementation, I was expecting that a text property would be applied to text in a buffer, and then operations could be done on the buffer by those properties.  Instead, I see something about an extra buffer and then deleting individual characters--I can't follow what's going on.  And the Lisp code is very difficult to read due to its C-style hanging parens, etc.

So while this idea is interesting, I think the problem you describe in the readme is already solved in Emacs in a few other, more powerful ways.

BTW, I'd generally recommend that you review some Elisp resources, like the Elisp intro (`eintr` Info manual), emacs-lisp-style-guide, emacs-package-dev-handbook, etc, so that you can write code in a more idiomatic and effective way.

**Comment by Dspil** [comment]
Thank you for your response. I wasn't talking about a consecutive chunk of debug code but about a few lines in different sections entirly which doesn't lend itself for region undo. However, I will revise the code given your helpful suggestions.

**Comment by alphapapa** [comment]
>  I wasn't talking about a consecutive chunk of debug code but about a few lines in different sections entirly which doesn't lend itself for region undo.

Are you sure?

> As for the separate buffer, I used that so I can save it if the user saves the file he is working on, in order to be able to retrieve the typing categories of the characters on opening a file.

How are you storing the categories exactly?

**Comment by Dspil** [comment]
For example your text might be structured like this:

Debug
Useful
Debug
Fixed
Debug
Fixed
Debug
Useful

And I only need the debug words to vanish after I have altered the fixed words. Useful means I want it to stay too. I can't fit all the debug words in a region without including a fixed one too

The categories of the characters in a buffer are stored in a separate buffer as digits. For example digit 1 in position 10 means the 10th character ha category 1. I can save this buffer to reload it if the user opens the file he is working on again. I read what text properties are and they seem useful. Would it be better if I stored the category in them and just create the whole helper file on save?

**Comment by alphapapa** [comment]
Thanks, now I understand better what you're doing.  If you want to save a separate file like that, I can see the value in this approach; it's simple.  Text properties could also be persisted if you, e.g. used `prin1` on `buffer-string`; I suppose the value in doing that would be to allow more descriptive categories rather than 0-9.

**Comment by Dspil** [comment]
Having more descriptive categories sounds nice. I chose just a digit to be able to switch or delete categories fast. An easy improvement would be to accept any character as a category name but I couldn't think of many use cases that need more than 10 categories. Since I started using it I am losing track after 3-4.

**Comment by riscy** [comment]
Just passing through with a quick check -- you will definitely want to run package-lint if you haven't:


package-lint (using version 20210528.2348):
```
28 issues found:
1:0: error: Package should have a Homepage or URL header.
1:0: warning: The package summary is too long. It should be at most 60 characters.
1:139: warning: You should depend on (emacs "24.1") if you need lexical-binding.
32:0: error: "typing-category-buffer-prefix" doesn't start with package's prefix "typing-categories".
33:0: error: "typing-category" doesn't start with package's prefix "typing-categories".
34:0: error: "typing-category-num" doesn't start with package's prefix "typing-categories".
35:0: error: "typing-category-deleting" doesn't start with package's prefix "typing-categories".
36:0: error: "typing-category-default" doesn't start with package's prefix "typing-categories".
45:0: error: "typing-category-buffer" doesn't start with package's prefix "typing-categories".
49:0: error: "inverse-typing-category-buffer" doesn't start with package's prefix "typing-categories".
64:0: error: "typing-category-after-find-file" doesn't start with package's prefix "typing-categories".
70:3: warning: Closing parens should not be wrapped onto new lines.
77:0: error: "typing-category-after-save-file" doesn't start with package's prefix "typing-categories".
87:0: error: "typing-category-after-kill-buffer" doesn't start with package's prefix "typing-categories".
94:0: error: "enable-typing-category" doesn't start with package's prefix "typing-categories".
96:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
98:5: error: You should depend on (emacs "24.3") if you need `setq-local'.
108:0: error: "disable-typing-category" doesn't start with package's prefix "typing-categories".
110:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
125:0: error: "typing-category" doesn't start with package's prefix "typing-categories".
130:0: error: "change-typing-category" doesn't start with package's prefix "typing-categories".
134:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
136:0: error: "delete-typing-category" doesn't start with package's prefix "typing-categories".
141:5: error: You should depend on (emacs "24.3") if you need `setq-local'.
153:5: error: You should depend on (emacs "24.3") if you need `setq-local'.
156:0: error: "current-typing-category" doesn't start with package's prefix "typing-categories".
161:0: error: "reset-typing-category" doesn't start with package's prefix "typing-categories".
164:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
```

Also some very quick things I notice:
- `setq-default` is not usually used in conjunction with `defvar`; probably you want to be using `defvar-local` and dropping the `setq-default`s
- Variable names shouldn't be capitalized in elisp (but should be in the documentation), e.g. `CATEGORY`
- typing-categories.el#L169: Loading a package should rarely add hooks -- you should gate these behind a togglable mode
- typing-categories.el#L145: Could this point/point-max comparison use `eobp`?

**Comment by Dspil** [comment]
Thank you for the feedback, I believe all these issues have been resolved.

**Comment by riscy** [comment]
Taking a closer look now -- I really like the idea for this.

> I read what text properties are and they seem useful. Would it be better if I stored the category in them and just create the whole helper file on save?

In terms of execution I like the idea of using buffer variables to store the categories, rather than relying on a separate file/the contents of another buffer.  I wonder if using text properties would clash with syntax highlighting, but overlays might work well (see `make-overlay`, `delete-overlay`, etc.).  As you write, having them in a separate file is useful for reloading them from disk, but you could potentially arrive at a very simple implementation if you just lean on overlays:

```
(defvar-local category-overlays nil)

(defun category-apply ()
   "Apply category to current line - adds warning color in this case"
  (interactive)
  (let ((overlay (make-overlay (point-at-bol) (point-at-eol))))
    (overlay-put overlay 'face 'warning)
    (push overlay category-overlays)))

(defun category-delete ()
  "Delete all the affected lines."
  (interactive)
  (mapcar
   (lambda (overlay)
     (delete-region
      (overlay-start overlay)
      ;; delete the newline -- up to the end of the buffer:
      (min (point-max) (1+ (overlay-end overlay))))
     (delete-overlay overlay))
   category-overlays)
  (setq-local category-overlays nil))
```

**Comment by alphapapa** [comment]
@riscy Just FYI, text properties won't interfere with font-lock.  In that respect they're no different than overlays.

Overlays are a nice idea, though, especially in that, e.g. a subtle face could be applied to distinguish one category's text from another.

**Comment by riscy** [comment]
My mistake, I confused myself!  I was trying to propertize the text with faces when I was sketching the above snippet, and syntax highlighting (like comments) was overruling it.

**Comment by Dspil** [comment]
I'll try that too then! I guess I will have to create a helper file on save each time if I want to be able to reload the categories in the future. I hope it is not laggy on save that way.

**Comment by Dspil** [comment]
And I was thinking of adding a function to highlight categories differently temporarily for inspection. Overlays might be what is needed for this.

**Comment by Dspil** [comment]
I updated the code fully to use text-properties only, no help buffers. It should be faster too when editing and just a little bit slower on saving or loading typing categories

**Comment by Dspil** [comment]
Hello, is there anything needed to make this melpa ready?

**Comment by riscy** [comment]
I'm mostly active here on weekends, hence the delay.  Here's some quick feedback on the latest code:

byte-compile (using Emacs 27.1):
```
typing-categories.el:248:1:Warning: the function `mapcar*' is not known to be
    defined.
```
But `mapcar*` is actually deprecated -- you should `(require 'cl-lib)` and use `cl-mapcar` instead.

And a couple miscellaneous suggestions:
- typing-categories.el#L63: Could this point/point-min comparison use `bobp`?
- typing-categories.el#L114: `concat` may be unneeded; `insert` can take multiple arguments

Lastly I have some small reservation about the package name/summary line. "Typing" is an overloaded term and could refer to [type systems](https://en.wikipedia.org/wiki/Strong_and_weak_typing) (that's where my mind goes, anyway).  To me it feels like "text categories" would be a better name, and better aligns with Emacs's notion of "text properties" .   The fact that you type them with a keyboard is incidental.  For the summary I'd suggest something like "Assign text categories for bulk operations" or something along those lines.

**Comment by Dspil** [comment]
Thank you for the feedback, I have addressed all the mentioned issues in the latest commits.

**Comment by riscy** [comment]
Looks good!  Thanks again, and welcome to MELPA. :)

**Comment by Dspil** [comment]
Thank you very much!

**Pull request merged**
