### PR TITLE
Add recipe for searcher.

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Searcher in pure elisp

### Direct link to the package repository

https://github.com/jcs-elpa/searcher

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi, what does this do? :)

**Comment by jcs090218** [comment]
Oh, yeah. I didn't know why I don't bother to put down description in the readme file. Anyway, this package is similar to silver searcher (ag) and grep, etc. But written in pure elisp.

**Comment by riscy** [comment]
Ok, gotcha!  I'm definitely a fan of native solutions in terms of managing complexity.  Any comment on the performance of this in large projects, e.g. compared to grep?

I notice you're just using `string-match-p` against your `search-ignore-files` regexp list, so I think this will inadvertently ignore files that you don't want to ignore.  For example:
```elisp
(searcher--is-contain-list-string-regexp searcher-ignore-files "list.obj.txt")
```
should probably be nil, but returns 4 due to the match at the beginning of the string.  I'd imagine there is probably a similar issue with `searcher-ignore-dirs`.  A good strategy for developing a tool like this might be to add some test cases or a test directory structure to make sure there's no regressions against these edge cases.

Another small couple small notes on style:
- searcher.el#L76: There is no need to quote lambdas (neither #' nor ')
- On line 146, the progn is not necessary but no harm either.  Maybe your intention is to somehow group those `setq` forms, but in that case you might like that you can write e.g. `(setq x1 10  x2 20  x3 30)`

**Comment by jcs090218** [comment]
> should probably be nil, but returns 4 due to the match at the beginning of the string. I'd imagine there is probably a similar issue with searcher-ignore-dirs. A good strategy for developing a tool like this might be to add some test cases or a test directory structure to make sure there's no regressions against these edge cases.

Yep, true. I have made several of tools like this but I didn't come up with the solution to the edge cases. My solution maybe acceptable, since `searcher-ignore-files` and `searcher-ignore-dirs` uses regular expression hence should be easy and flexible to target the file/directory you want to ignore. And of course, if you have a better solution please let me know! 😄 

> Another small couple small notes on style:
> 
> * searcher.el#L76: There is no need to quote lambdas (neither #' nor ')
> * On line 146, the progn is not necessary but no harm either.  Maybe your intention is to somehow group those `setq` forms, but in that case you might like that you can write e.g. `(setq x1 10  x2 20  x3 30)`

All fixed! :)

**Comment by riscy** [comment]
It might be a good idea to reach out to the community to help with those edge cases -- there is certainly a better solution.

**Comment by jcs090218** [comment]
Hmmm... not sure what I am suppose to do here? 😕 Is there any community that you recommend and want me to reach out? Appreciated! 😄

**Comment by riscy** [comment]
I don't want to sound overly critical, because you do good work.  But it seems like a fairly obvious bug, and your goal as a prolific package author (with almost 50 packages on MELPA already) should be to index stuff in MELPA when it's production-ready and the edge cases are covered.

I also feel like it will be fairly easy to fix (either with some elbow grease or by reaching out to a community like the Emacs community on reddit, emacs.stackexchange.com, or even just hunting through the manual and documentation until you find a fix).  If you really get stuck, I can start looking into it, but I can't promise I'll be expedient.

**Comment by jcs090218** [comment]
> I don't want to sound overly critical, because you do good work. But it seems like a fairly obvious bug, and your goal as a prolific package author (with almost 50 packages on MELPA already) should be to index stuff in MELPA when it's production-ready and the edge cases are covered.

No worries! I agree with your point. Just point it out and I will fix it.

> I also feel like it will be fairly easy to fix (either with some elbow grease or by reaching out to a community like the Emacs community on reddit, emacs.stackexchange.com, or even just hunting through the manual and documentation until you find a fix). If you really get stuck, I can start looking into it, but I can't promise I'll be expedient.

I don't know what to ask. As a programmer, having file name like this `list.obj.txt` isn't acceptable and in most cases are being faulty edited. Hence, I have setup the regex default to `false` on these cases. 😕 If the user really want to search on something like this, the could just edit the regex list. And I think that's what most search tool works? Like adding more constrain on the command if the result didn't appear in the way they want.

**Comment by riscy** [comment]
> list.obj.txt isn't acceptable and in most cases are being faulty edited

I disagree, and I would personally insist on this being fixed before indexing this into MELPA.

**Comment by riscy** [comment]
I'll mark this as awaiting upstream, since I believe we shouldn't try to evade this issue.

**Comment by jcs090218** [comment]
I don't know if this will help? But I found some links and threads that maybe give us more hints about this topic.

By not discussing the edge case, `ag` seems to be parsing `.gitignore` file to exclude the path. And `grep` uses regex by passing it as an argument. I don't think I am going to parse `.gitignore` because I don't like the solution itself. On the other hand, I am not using any external program hence I don't need to hold a parameter string like how other package does to bridge the interface between elisp and the external program. 

By discussing the edge case, I would imagine changing all items in `searcher-ignore-files` variable with `$` at the end, so it won't ignore case like `list.obj.txt`. But I am opposing it because if the user found the problem then they can edit the **against variables** as they would. But if it is the opposite, then the user could cause inefficient experience (long search time or even crashes) which I don't want that by default. And, I have the feeling that `list.obj.txt` is not the default case I want to search? 😕 

* [How can I exclude directories from grep -R?](https://stackoverflow.com/questions/6565471/how-can-i-exclude-directories-from-grep-r)

Maybe we can identify the file to see if it is the text or binary file to determine weather we search for the file or not? This looks promising, but the performance of the IO can cause issue. 😓 

* [Emacs function for determining whether a file is text or binary?](https://www.reddit.com/r/emacs/comments/1opx6z/emacs_function_for_determining_whether_a_file_is/)

---

Anyway, I will keep searching the better solution and just to let you know I am not trying to evade the issue here.

**Comment by riscy** [comment]
> And I couldn't imagine people would name another .vscode or .git directory with different purpose. 😕 Would people do that? 😅

Won't these directories _all_ be ignored?

```
(searcher--is-contain-list-string-regexp searcher-ignore-dirs "./stats-tutorial/binomial-examples")
(searcher--is-contain-list-string-regexp searcher-ignore-dirs "./design-patterns/builder")
(searcher--is-contain-list-string-regexp searcher-ignore-dirs "./todo-list/chores")
```

**Comment by jcs090218** [comment]
> Won't these directories all be ignored?

Oh, yes. This is my mistake!

Fixed with this commit https://github.com/jcs-elpa/searcher/commit/fa72c0175857bb550bb8ca10ab54c1aae1f007eb.

**Comment by riscy** [comment]
Say I:
```
$ mkdir -p searcher-test/hello-world
$ echo 'hello_' >> searcher-test/hello-world/hi.txt
```

And then I run:
```elisp
(searcher-search-in-path "." "hello_")
```
should I be seeing `nil` here?  It seems like the code currently isn't doing a recursive search.

> This is my mistake!

Okay, now what about these?

```elisp
(searcher--is-contain-list-string-regexp searcher-ignore-dirs "./stories/nightmares/ghosts")
(searcher--is-contain-list-string-regexp searcher-ignore-dirs "./inventory/cabin/cooking-supplies")
```

**Comment by jcs090218** [comment]
> should I be seeing nil here? It seems like the code currently isn't doing a recursive search.

I got the following result.

```
((:file c:/Users/JenChieh/Downloads/workspace/searcher-test/hello-world/hi.txt :string hello_ :position 0 :line-number 1 :column 0))
```

Are you asking this suppose to be nil? Or it doesn't work in your case? It does search recursively on my side. 😕 

> Okay, now what about these?
> 
> ```
> (searcher--is-contain-list-string-regexp searcher-ignore-dirs "./stories/nightmares/ghosts")
> (searcher--is-contain-list-string-regexp searcher-ignore-dirs "./inventory/cabin/cooking-supplies")
> ```

Yes, these paths can be search now! Actually, I don't know what are you asking here. 😕

**Comment by riscy** [comment]
I see what happened - the directory I was testing on contained the word "git".  You're adding `grep-find-ignored-directories` to your `ignore-lst`, but `grep-find-ignored-directories` is NOT a list of regular expressions.  Try this for example:
```elisp
(progn 
  (make-directory "searcher-git-test")
  (make-directory "searcher-git-test/hello-world")
  (with-temp-buffer
    (insert "hello_")
    (write-file "searcher-git-test/hello-world/hi.txt"))
  (searcher-search-in-path "." "hello_"))
```

> Yes, these paths can be search now! Actually, I don't know what are you asking here.

The first one has `res/` in it, which is a pattern you ignore in `searcher-ignore-dirs`.  The second one has "bin/" in it, which you ignore in `searcher-ignore-dirs`.  My understanding is that the expressions I pasted should evaluate to nil, but if you check them, they are non-nil

**Comment by jcs090218** [comment]
> The first one has res/ in it, which is a pattern you ignore in searcher-ignore-dirs. The second one has "bin/" in it, which you ignore in searcher-ignore-dirs. My understanding is that the expressions I pasted should evaluate to nil, but if you check them, they are non-nil

Okay, I see your point here. My first design was trying to eliminate the regex, but I figured this may be too fragile and not explicit to user. I have fixed it by default with `/` in front so it is now explicit! See commit https://github.com/jcs-elpa/searcher/commit/14c81d1c0cd50fec6e2a89c6e09c93f87bb37356.

> I see what happened - the directory I was testing on contained the word "git". You're adding grep-find-ignored-directories to your ignore-lst, but grep-find-ignored-directories is NOT a list of regular expressions. Try this for example:

I was trying to reuse code from `grep` and `projectile` and may be this tool doesn't fit because I am using regex. I extracted the two variables and append it to `searcher-ignore-files`. See commit https://github.com/jcs-elpa/searcher/commit/017329d13495ad7d01b6114f9ada6c6f85cbe248.

---

Let me know what you think about the two changes?! Thanks! 😄

**Comment by riscy** [comment]
Okay, I think that's about all.  I apologize this took so long, but I think there was a bit more work that needed to be done before this was production-ready, and I hope you'll agree that's fair.

As for your summary/Commentary, you _might_ want to include the word "grep" or somehow mention that this searches _file contents_.  I wasn't able to guess what this package is meant to do based on "Searcher in pure elisp" and I suspect I'm not alone.

Thanks!

**Comment by jcs090218** [comment]
> Okay, I think that's about all. I apologize this took so long, but I think there was a bit more work that needed to be done before this was production-ready, and I hope you'll agree that's fair.

That's totally fair! Sorry that I am not an expert on this kind of tool! Plus I am a big fan on making tools to native solution in Emacs Lisp. Yet the issue is that many people doesn't care about this, and they likely to use the solution that already work! e.g. ag, grep, etc. I feel like I need more help but not quite sure how many people are interested in this. 

But that's not a big deal! As long I am still using Emacs; I will be fixing and updating this tool until it is mature and able to compete to other tool.

> As for your summary/Commentary, you might want to include the word "grep" or somehow mention that this searches file contents. I wasn't able to guess what this package is meant to do based on "Searcher in pure elisp" and I suspect I'm not alone.

Got you!

**Pull request merged**
