### PR TITLE
New recipe for OpenAI API package

### PR DESCRIPTION
**Pull request by antonhibl**
### Brief summary of what the package does

 Allows interacting with various GPT-3 Language Models directly within Emacs. You can send a prompt interactively, from selections, or from an entire buffer's text and it logs all inputs and outputs concurrently in an *openai* buffer. It also adds a function which allows querying the current list of available GPT-3 models from OpenAI.

### Direct link to the package repository

https://github.com/antonhibl/gptai

### Your association with the package

I am the creator and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by antonhibl** [comment]
I am so damn confused why this is failing wtf

**Comment by antonhibl** [comment]
this is fucking ridiculous

**Comment by antonhibl** [comment]
that was the dumbest thing to fail for holy f***

**Comment by antonhibl** [comment]
how long is the merge process for packages for MELPA, I still see PRs from awhile back waiting for merges so just wondering how fast this sort of thing is. @purcell

**Comment by progfolio** [comment]
> how long is the merge process for packages for MELPA, I still see PRs from awhile back waiting for merges so just wondering how fast this sort of thing is. @purcell

Packages have to be reviewed before they can be accepted.
How long that takes mainly depends on:

- The number of packages ahead of yours in the queue.
- The availability of the reviewer(s).
- The number of issues which turn up in the review. This is the part you can make sure goes fast by adhering closely to the checklist in the templates.

Taking a look at merged PRs will give you an idea of how long each took:

https://github.com/melpa/melpa/pulls?q=is%3Apr+is%3Aclosed

**Comment by antonhibl** [comment]
@progfolio thanks for the information!

**Comment by riscy** [comment]
Thanks both, and thanks @antonhibl for this.  Quick first pass --

`openai.el` with byte-compile using Emacs 28.1:
```
openai.el:66:22: Warning: reference to free variable `url-http-end-of-headers'
In openai-send-image-query:
openai.el:150:22: Warning: reference to free variable
    `url-http-end-of-headers'
openai.el:166:45: Warning: assignment to free variable `indn'
openai.el:171:25: Warning: assignment to free variable `image'
openai.el:170:17: Warning: assignment to free variable `index'
openai.el:172:24: Warning: reference to free variable `image'
openai.el:173:114: Warning: reference to free variable `index'
```

`openai.el` with checkdoc 0.6.2:
```
openai.el:111: Argument `buffer-name' should appear (as BUFFER-NAME) in the doc string
openai.el:129: Argument `prompt' should appear (as PROMPT) in the doc string
```

`openai.el` with package-lint 20221003.1636:
```
3 issues found:
1:52: warning: You should depend on (emacs "24.1") if you need lexical-binding.
7:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
39:10: error: You should depend on (emacs "24.1") if you need `url'.
```

`openai.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- openai.el#L3: Have you done the paperwork to assign this copyright?
```
If you have not, the copyright is your copyright, not FSF's.

`#'load`-check on each file:
```
Loading openai.el
  openai.el:Error: Emacs 28.1:
  (search-failed "^.*object.*$")
```
Simply loading this file should not cause a function like `(openai-list-models)` to run.

Package and license:
- Prefer equivalent recipe: `(openai :repo "antonhibl/openai" :fetcher github)`
- GNU General Public License v2.0 (via API) -- please [use v3.0 or later](https://github.com/johannes-mueller/company-wordfreq.el/issues/6).

**Comment by jcs090218** [comment]
It seems like we have naming collision, 😓 

* https://github.com/emacs-openai/openai
* https://github.com/emacs-openai/codegpt

Since your package does a lot more than sending request, would you consider rename this package to something else? And rely the on `openai` like what `codegpt` package does? LMKWYT?

**Comment by antonhibl** [comment]
@jcs090218 just updated the namespace to gptai, this should avoid collisions.

**Comment by antonhibl** [comment]
@riscy just updated and should have addressed all of these, let me know how it looks when you get a chance. The only thing I haven't run locally is melpazoid but I did update the license too.

**Comment by jcs090218** [comment]
> @jcs090218 just updated the namespace to gptai, this should avoid collisions.

Thank you! And thank you for all your awesome works! :)

**Comment by antonhibl** [comment]
@jcs090218 no problem, I also wanted to clarify I didnt include `(require 'openai)` because the openai package is only listen in JCS ELPA not MELPA, since this is a MELPA package I want to keep the sources delineated.

**Comment by jcs090218** [comment]
No problem! Thanks for letting me know! I plan to add Openai to MELPA, but I have another PR ([#8335](https://github.com/melpa/melpa/pull/8335)) open. It won't be soon, but hopefully, it will eventually make it.

**Comment by antonhibl** [comment]
@jcs090218 sounds good, if you ping me when that happens I can add it as a dependency because I can see a lot of crossover applications between these packages. Thanks for the assistance!

**Comment by riscy** [comment]
Thanks @antonhibl for quickly accommodating.  This looks good to merge.

- The use of `defvar`s inside functions (e.g. `(defvar gptai-image nil)`) should be replaced by `let` blocks
- I think some of your docstrings have a typo: "Sends selection code" should probably be "Send selected code" or, alternatively, I'd be inclined to use Emacs-specific language, e.g. "Send the region ..."
- Your summary line "Integrate with the OpenAI API" doesn't tell the right story, I feel.  "Interact with the OpenAI API using pre-written prompts" seems to be the theme?
- In your Commentary, "stright" -> "straight", and given "See the accompanying Readme.org for configuration details" you should be aware that MELPA will not distribute your README.  Give users a URL if the config details are too large to place in the `;;; Commentary`
- Remove leading comments like `;; optimizes code from selection text`; the docstring for the function that follows is sufficient.
- Is there any real benefit to catching the connection errors and then rethrowing them (e.g. `(condition-case gptai-err ... (error (error "..."))`?  I'd be inclined to just let Emacs throw the errors, rather than repackaging them.  It's possible some caller could handle them in a generic way... it will also lead to dozens of lines of your code being de-indented by one level :)

**Comment by antonhibl** [comment]
@riscy just pushed some changes to address these so they should be good, thanks for the review. Only 2 things I will note:

- I left the summary line as is as this package is intended to serve as a way to integrate emacs with openAI, the functions with custom query strings are placeholders as codegpt is not merged into MELPA yet but I want this functionality available. If this summary becomes a conflicting point we can change it but right now to me it seems fitting as is. 

- The other point would be about how I am handling the errors, I am throwing errors using the condition-case for err so I can catch the errors in sending a query and HTTP issues that might arise and catch the errors caught in the API itself in two separate statements. I am not sure if this is actually necessary the way I have implemented but I had trouble finding another way to handle the second case without the condition-case for err.

**Comment by riscy** [comment]
A couple very minor issues that you might want to address:

`gptai.el` with checkdoc 0.6.2:
```
gptai.el:154: First sentence should end with punctuation
gptai.el:35: White space found at end of line
```

But I'll merge this now.  And, welcome to MELPA. :)

**Pull request merged**
