### PR TITLE
Changed peg repo to emacs-straight/peg

### PR DESCRIPTION
**Pull request by damon-kwok**
### Brief summary of what the package does

This package implements Parsing Expression Grammars for Emacs Lisp. old repo `ellerh/peg.el` has not been updated for five years, and the new warehouse uses synchronized robots.

### Direct link to the package repository

https://github.com/emacs-straight/peg

### Your association with the package

An enthusiastic user

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
Q: Relevant communications with the upstream package maintainer
A: None needed

Yeah... you are being very optimistic here. :wink: 

----

This is very confusing.

How controls https://github.com/emacs-straight? All the people who have access but at least the owner(s) should make their involvement public so that they appear on https://github.com/emacs-straight/people. Visitors might then be able to deduce tentative answers at least to some of the these questions.

Does this have something to do with the straight.el package manager?

* If so, then this is probably something that is similar to my https://github.com/emacsmirror and it should only be used as a last resort. /cc @raxod502

* If not, then this organization should be renamed to avoid any confusion.

----

Concerning this particular package.

From this line in `externals-list` in the GNU Elpa repository

```
 ("peg"			:external) ;Was in "https://github.com/ellerh/peg.el"
```

we can conclude that this package should be removed from Melpa, because going forward the most recent version will be the one that is already distributed on GNU Elpa.

Please make that change instead.

**Comment by damon-kwok** [comment]
You are right, I have encountered this problem recently, I want to install ELPA's peg1.0 but the old version of Melpa will always be installed first.

**Comment by tarsius** [comment]
> the old version of Melpa will always be installed first.

Unfortunately the old version also won't go away from local installations so even after we remove it each users will have to notice themselve. It's a defect of package.el.

**Comment by raxod502** [comment]
> If so, then this is probably something that is similar to my https://github.com/emacsmirror and it should only be used as a last resort.

You are correct. In fact, my mirror has [a mirror of part of your mirror](https://github.com/emacs-straight/emacsmirror-mirror) :P 

> This is very confusing.

Sorry, I didn't realize organizations had profiles you could fill out. I've changed it so that it looks like this, which will hopefully be sufficiently elucidating:

image

**Comment by tarsius** [comment]
Thanks!  :grinning:

**Pull request closed without merging**
