### PR TITLE
add ox-report

### PR DESCRIPTION
**Pull request by DarkBuffalo**
### Brief summary of what the package does

Export your org file to minutes report PDF file

### Direct link to the package repository

https://github.com/DarkBuffalo/ox-report

### Your association with the package
i am the Author and maintener

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Looks interesting.  You should run package-lint (again) on this file.  For example the line at the top of your file should resemble:

```elisp
;;; ox-report.el --- Export your org file to minutes report PDF file -*- lexical-binding: t -*-
```

And the first block should resemble:

```elisp

;; Author: Matthias David <matthias@gnu.re>
;; URL: https://github.com/DarkBuffalo/ox-report
;; Version: 0.1
;; Package-Requires: ((emacs "24.4"))
;; Keywords: org, outlines, report, exporter, meeting, minutes
```
(Note the added `Package-Requires` and "outlines" keyword)

After that I believe these are straightforward:
```
693:4: warning: Closing parens should not be wrapped onto new lines.
705:0: error: "report-template" doesn't start with package's prefix "ox-report".

801:0: error: "report-export-as-latex" doesn't start with package's prefix "ox-report".
837:0: error: "report-export-to-latex" doesn't start with package's prefix "ox-report".
874:0: error: "report-export-to-pdf" doesn't start with package's prefix "ox-report".
910:0: error: "report-export-to-pdf-and-open" doesn't start with package's prefix "ox-report".
```

**Comment by DarkBuffalo** [comment]
sorry I start in lisp. I solved my mistakes

**Comment by DarkBuffalo** [comment]
> Looks interesting. You should run package-lint (again) on this file. For example the line at the top of your file should resemble:
> 
> ```emacs-lisp
> ;;; ox-report.el --- Export your org file to minutes report PDF file -*- lexical-binding: t -*-
> ```
> 
> And the first block should resemble:
> 
> ```emacs-lisp
> ;; Author: Matthias David <matthias@gnu.re>
> ;; URL: https://github.com/DarkBuffalo/ox-report
> ;; Version: 0.1
> ;; Package-Requires: ((emacs "24.4"))
> ;; Keywords: org, outlines, report, exporter, meeting, minutes
> ```
> 
> (Note the added `Package-Requires` and "outlines" keyword)
> 
> After that I believe these are straightforward:
> 
> ```
> 693:4: warning: Closing parens should not be wrapped onto new lines.
> 705:0: error: "report-template" doesn't start with package's prefix "ox-report".
> 
> 801:0: error: "report-export-as-latex" doesn't start with package's prefix "ox-report".
> 837:0: error: "report-export-to-latex" doesn't start with package's prefix "ox-report".
> 874:0: error: "report-export-to-pdf" doesn't start with package's prefix "ox-report".
> 910:0: error: "report-export-to-pdf-and-open" doesn't start with package's prefix "ox-report".
> ```
sorry I start in lisp. I solved my mistakes

**Comment by riscy** [comment]
No worries.  It looks like since your latest code update we've got --

byte-compile (using Emacs 27.1):
```
ox-report.el:703:1:Warning: Unused lexical variable `cc'
ox-report.el:703:1:Warning: Unused lexical variable `fromname'
ox-report.el:703:1:Warning: Unused lexical variable `subject'
ox-report.el:703:1:Warning: Unused lexical variable `from'
ox-report.el:703:1:Warning: Unused lexical variable `toc'
ox-report.el:799:1:Warning: Unused lexical variable
    `ox-report-special-contents'
ox-report.el:835:1:Warning: Unused lexical variable
    `ox-report-special-contents'
ox-report.el:872:1:Warning: Unused lexical variable
    `ox-report-special-contents'
```
but I'm assuming the code is a little bit in a state of flux still, so I can check back whenever you ping me.

The other issue that's easy to address is to add a LICENSE/COPYING file that GitHub can detect (e.g. no markup) to your repository.

**Comment by DarkBuffalo** [comment]
> No worries. It looks like since your latest code update we've got --
> 
> byte-compile (using Emacs 27.1):
> 
> ```
> ox-report.el:703:1:Warning: Unused lexical variable `cc'
> ox-report.el:703:1:Warning: Unused lexical variable `fromname'
> ox-report.el:703:1:Warning: Unused lexical variable `subject'
> ox-report.el:703:1:Warning: Unused lexical variable `from'
> ox-report.el:703:1:Warning: Unused lexical variable `toc'
> ox-report.el:799:1:Warning: Unused lexical variable
>     `ox-report-special-contents'
> ox-report.el:835:1:Warning: Unused lexical variable
>     `ox-report-special-contents'
> ox-report.el:872:1:Warning: Unused lexical variable
>     `ox-report-special-contents'
> ```
> 
> but I'm assuming the code is a little bit in a state of flux still, so I can check back whenever you ping me.
> 
> The other issue that's easy to address is to add a LICENSE/COPYING file that GitHub can detect (e.g. no markup) to your repository.

Thank you for the feedback
sorry, i think it's good.
I have indeed removed the old variables and created the license

**Comment by DarkBuffalo** [comment]
Hello @riscy 
the job is done.
I also change 
- the typo.
- the language works automatically with the choice in the orgmode file header for English and French.
`#+language: en` or `#+language: fr`

**Comment by riscy** [comment]
Thanks!

**Comment by DarkBuffalo** [comment]
thanks for all

**Pull request merged**
