### PR TITLE
Add recipe for chronometrist-goals.el

### PR DESCRIPTION
**Pull request by contrapunctus-1**
### Brief summary of what the package does

Adds time target functionality to [Chronometrist](https://github.com/contrapunctus-1/chronometrist)

### Direct link to the package repository

https://github.com/contrapunctus-1/chronometrist-goals

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
  - ~~There are errors about the package prefix. I'm not sure if it really is a big deal, since the prefix I do use is also from one of my packages. Given that, is it really important? I can rename the definitions, if it is.~~ EDIT - all definitions now use the package prefix.
- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
  - An error for `chronometrist-run-at-time`, for not mentioning the arguments. Since it is a wrapper around `run-at-time` and the descriptions for the possible values it can take are quite long...is it really necessary that I mention them? I could also hack around it by adding "For TIME, REPEAT, FUNCTION and ARGS, see `run-at-time`" :slightly_smiling_face: 
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
> There are errors about the package prefix. I'm not sure if it really is a big deal, since the prefix I do use is also from one of my packages. Given that, is it really important? I can rename the definitions, if it is.

For some background -- the org-mode-sphere has created its own conventions for prefixes that MELPA ends up having to accept.  Helm also has its own conventions for prefixes.

But the trouble with making this exception is that (1) it sets a precedent, (2) it's altogether easier when we can be consistent, and (3) this particular exception is hard for me to phrase as some kind of rule that scales well.  "packages can violate the package prefix rule if the author of an original prefix is okay with it" doesn't scale and is hard to enforce.  That's just my take, though -- I might see what @purcell thinks.

I'll also add there are benefits to bending to package-lint's draconian rules, among them is that when it does whine about something new and legitimate, you won't accidentally ignore it.

In the meantime, a small checkdoc --

checkdoc (using version 0.6.1):
```
Warning (emacs): 
chronometrist-goals.el:48: Argument `time' should appear (as TIME) in the doc string
```

**Comment by riscy** [comment]
Disregard my checkdoc nag, I see your note. :)

**Comment by contrapunctus-1** [comment]
@riscy alrighty, it's done 😀

**Comment by riscy** [comment]
Thanks for accommodating, and apologies for my long turnaround time.  Here's the latest.

### chronometrist-goal.el ###

byte-compile (using Emacs 26.3):
```
chronometrist-goal.el:52:16:Warning: reference to free variable
    `chronometrist--timers-list'
chronometrist-goal.el:53:14:Warning: assignment to free variable
    `chronometrist--timers-list'
In chronometrist-goal-stop-alert-timers:
chronometrist-goal.el:199:8:Warning: reference to free variable
    `chronometrist--timers-list'
chronometrist-goal.el:201:14:Warning: assignment to free variable
    `chronometrist--timers-list'
In end of data:
chronometrist-goal.el:218:1:Warning: the following functions are not known to
    be defined: chronometrist-run-at-time,
    chronometrist-seconds->alert-string, chronometrist-get-goal
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
chronometrist-goal.el:49: Argument `time' should appear (as TIME) in the doc string
```

package-lint (using version 20200616.2257):
- No issues!


### Loadability ###

Verifying ability to #'load each file:
```
Loading chronometrist-goal.el
Done.
```

**Comment by contrapunctus-1** [comment]
Re: compiler warnings, I feel a little confused - I test with `cask build`, and that installs all dependencies first, including Chronometrist, and in this case gave no warnings. How are you compiling it? Declaring these definitions is no issue, but I'm surprised to be running into this at all. 🤔

Should I continue to ignore the checkdoc warning as you suggested, or use that hack I mention, or something else?

**Comment by riscy** [comment]
> How are you compiling it?

It is a little involved but I'm compiling using the scripts [here](https://github.com/riscy/melpazoid).  I'm not very familiar with cask, so I'm not very helpful there. :)

Re: checkdoc, that's all fine.  Looks good!

**Pull request merged**
