### PR TITLE
Add a recipe for Elbank

### PR DESCRIPTION
**Pull request by NicolasPetton**
### Brief summary of what the package does

Elbank is a personal finances reporting tool for Emacs.  It uses
[Weboob](https://weboob.org) for scraping data from bank websites.n

### Direct link to the package repository

https://github.com/NicolasPetton/Elbank

### Your association with the package

I am the maintainer of the package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! This is a cool package. [Here](https://github.com/NicolasPetton/elbank/blob/2f2917bb2f789dd6cd36c5620fd240dfbb52c4c3/elbank.el#L50-L60) you should define the backwards-compatibility function with a prefix, according to the [elisp conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html).

**Comment by NicolasPetton** [comment]
Thanks @purcell for the review, I've added a prefix: https://github.com/NicolasPetton/elbank/commit/ae3aecb1065f5d94185495842a1c4c8e126f702f

**Comment by NicolasPetton** [comment]
@purcell Please do not merge it yet, I'm thinking about adding it to ELPA.

**Comment by tarsius** [comment]
@NicolasPetton How's that progressing?

**Comment by purcell** [comment]
> Please do not merge it yet, I'm thinking about adding it to ELPA.

@NicolasPetton Just FYI, I'm happy to merge this now and remove it later if you decide to distribute via ELPA.

**Comment by NicolasPetton** [comment]
@purcell You can merge it.

Elbank uses Weboob, which can connect to PayPal using non-free JavaScript from paypal.com, so until that issue is resolved, Elbank will not be be distributed through ELPA.

**Comment by purcell** [comment]
Great, done.

**Pull request merged**
