### PR TITLE
Add html-element-edit recipe

### PR DESCRIPTION
**Pull request by jtkDvlp**
### Brief summary of what the package does

It provides a few helper-functions for attribute- and element-handling based on the functions given by web-mode. Further more it provides functions for slurping, barfing, dissolving, raising ... elements inspired by ParEdit and Paxedit. Last but not least this package includes a minor mode to provide a keymap with default bindings using commands of web-mode and this package.

### Direct link to the package repository

https://github.com/jtkDvlp/html-element-edit

### Your association with the package

I am the maintainer and contributor of this package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Please check file names. `provide` name must equal to file name.
- `html-element-edit-attribute` -> `html-element-edit-attributes` ?
- `html-element-edit-element` -> `html-element-edit-elements` ?

I got following errors at loading.

```
html-element-edit.el:28:1:Error: Cannot open load file: No such file or directory, html-element-edit-attributes
html-element-edit.el:29:1:Error: Cannot open load file: No such file or directory, html-element-edit-elements
```

**Comment by jtkDvlp** [comment]
Fixed! Thanks syohex.

I'm sorry for this foolish errors. For me it worked because I had evaluated the buffers and not loaded the files :-$

**Comment by alphapapa** [comment]
Since this package is specifically and only for web-mode, it might be good to rename it so people who install web-mode would be more likely to find it, e.g. web-mode-edit-element

**Comment by jtkDvlp** [comment]
Good idea. Thanks. Renaming done!

**Comment by syohex** [comment]
https://github.com/jtkDvlp/web-mode-edit-element/pull/1
https://github.com/jtkDvlp/web-mode-edit-element/pull/2

I have sent two PRs. Could you check them ?

**Comment by jtkDvlp** [comment]
Both merged. Thanks!

**Comment by purcell** [comment]
Have you seen tagedit? How does this compare?

**Comment by jtkDvlp** [comment]
No, I haven´t. I looked for a package that supportes web-mode.

I took a look at it and it seems it´s working with html-mode not with web-mode. So thats the difference between the packages. It supports html-mode, my packages supports web-mode.

There is a lot of functionality at html-mode and tagedit that´s also given by web-mode. :-(

**Comment by purcell** [comment]
Okay.

You should add an `;;;###autoload` cookie comment for the `(define-minor-mode web-mode-edit-element-minor-mode ...)` form.

**Comment by jtkDvlp** [comment]
Thanks.

Done.

**Pull request merged**
