### PR TITLE
hrefactor recipe added.

### PR DESCRIPTION
**Pull request by tonyday567**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, looks interesting. Quick feedback:

- `fromMaybe` needs to be renamed to `hrefactor-from-maybe` or similar
- The indentation is ironically very inconsistent in this file: perhaps `C-x h TAB` ;-)
- `M-x checkdoc` would be a good idea

You might also be interested in https://github.com/flycheck/flycheck/issues/530, which is about providing support for "quick fixes" on top of flycheck.

**Comment by tonyday567** [comment]
Thanks Steven,
My elisp is very rusty - great feedback thanks. Will clean up.

**Comment by milkypostman** [comment]
ping when ready

**Comment by tonyday567** [comment]
Closing this, as intero is now providing this functionality

**Comment by purcell** [comment]
Yay, that's a good outcome. Thanks!

**Pull request closed without merging**
