### PR TITLE
Add subsonic mode

### PR DESCRIPTION
**Pull request by lxea**
### Brief summary of what the package does

The package provides a client for the subsonic music streaming server API

### Direct link to the package repository

https://git.sr.ht/~amk/subsonic.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer
**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Some quick feedback:

- Could this be reproducing functionality in https://github.com/kljohann/mpv.el?  Perhaps there's an opportunity for collaboration
- Minor, but you could wrap the "mpv" in `defcustom subsonic-mpv "mpv"` in an `executable-find` so as to be explicit for the user
- I wonder, should `subsonic-auth` really be throwing errors when the package is loaded?  Doing this sort of thing at load-time makes it harder to use your package as a dependency, for example.  You could wait until `subsonic-build-url` is called to throw the error as an alternative
- subsonic.el#L354: It's safer to sharp-quote function names; use `#'`
- subsonic.el#L398: It's safer to sharp-quote function names; use `#'`

**Comment by lxea** [comment]
> Thanks for this. Some quick feedback:
> 
>     * Could this be reproducing functionality in https://github.com/kljohann/mpv.el?  Perhaps there's an opportunity for collaboration
> 
It has some functionality its reproducing, the only reason im not super inclined to try use it as mpv.el seems much more video focused + org than background music. ill try give it a bit of a look, but i think there will end up being a bit more specific for music mpv operations in this that mpv.el may not want
>     * Minor, but you could wrap the "mpv" in `defcustom subsonic-mpv "mpv"` in an `executable-find` so as to be explicit for the user
> 
:+1:  
>     * I wonder, should `subsonic-auth` really be throwing errors when the package is loaded?  Doing this sort of thing at load-time makes it harder to use your package as a dependency, for example.  You could wait until `subsonic-build-url` is called to throw the error as an alternative
> 
that makes sesne i'll try update it for that
>     * subsonic.el#L354: It's safer to sharp-quote function names; use `#'`
> 
>     * subsonic.el#L398: It's safer to sharp-quote function names; use `#'`
Oh cool ill update that

**Comment by riscy** [comment]
> ill try give it a bit of a look, but i think there will end up being a bit more specific for music mpv operations in this that mpv.el may not want

Thank you for taking a look and considering. :)

I think there is one byte-compile nag:

byte-compile (using Emacs 27.1):
```
subsonic.el:164:40:Warning: reference to free variable
    `url-http-end-of-headers'
```
This is unfortunately because the builtin `url-*.el` declares the variable but doesn't give it a value, so it is still "free".  You can fix this by following their pattern and adding a line `(defvar url-http-end-of-headers)`.

That's everything, though, so this should be a quick merge after that.

**Comment by lxea** [comment]
> (defvar url-http-end-of-headers)

Ahh I wasn't sure what to do about this -- fixed, thanks!

**Comment by riscy** [comment]
All set.  Thanks for this, and welcome to MELPA. :)

A couple real quick nags since I took another look:
- I notice you return the value t in a few of your functions (example: subsonic-toggle-playing) -- is this something I'm missing about the transient interface, or are these maybe just unnecessary?
- PASSSWORD -> PASSWORD
- hte -> the
- respone -> response

**Comment by lxea** [comment]
> All set. Thanks for this, and welcome to MELPA. :)
> 
> A couple real quick nags since I took another look:
> 
>     * I notice you return the value t in a few of your functions (example: subsonic-toggle-playing) -- is this something I'm missing about the transient interface, or are these maybe just unnecessary?
> 
>     * PASSSWORD -> PASSWORD
> 
>     * hte -> the
> 
>     * respone -> response

Thanks for merging! I'll do a bit of cleaning. My spelling is truly something to behold ;_;

**Pull request merged**
