### PR TITLE
Add nnhackernews recipe

### PR DESCRIPTION
**Pull request by dickmao**
### Brief summary of what the package does

A Gnus backend for Hacker News

### Direct link to the package repository

https://github.com/dickmao/nnhackernews

### Checklist

Please confirm with `x`:

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x ] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x ] I've used a [fork of package-lint](https://github.com/purcell/package-lint/pull/130)
- [x ] My elisp byte-compiles cleanly
- [x ] `M-x checkdoc` is happy with my docstrings
- [x ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Just checking <kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
3 issues found:

9:37: warning: Use a non-snapshot version number for dependency on "request" if possible.
9:58: warning: Use a non-snapshot version number for dependency on "dash" if possible.
9:76: warning: Use a non-snapshot version number for dependency on "anaphora" if possible.
```

And while I'm here, some sharp-quote hints for your consideration:
- nnhackernews.el#L1312: It's safer to sharp-quote function names; use `#'`
- nnhackernews.el#L146: It's safer to sharp-quote function names; use `#'`
- nnhackernews.el#L149: It's safer to sharp-quote function names; use `#'`
- nnhackernews.el#L150: It's safer to sharp-quote function names; use `#'`
- nnhackernews.el#L151: It's safer to sharp-quote function names; use `#'`
- nnhackernews.el#L152: It's safer to sharp-quote function names; use `#'`
- nnhackernews.el#L1409: It is beneficial to sharp-quote hooks; use `#'`
- nnhackernews.el#L1410: It is beneficial to sharp-quote hooks; use `#'`

**Comment by dickmao** [comment]
Functions now sharp-quoted.  I do not use semantic versions on Package-Requires because package.el effectively ignores them.

**Comment by riscy** [comment]
I see, thanks for the clarification.  It seems like the discussion [there](https://github.com/purcell/package-lint/pull/130) isn't resolved.

In the interest of being consistent in how I review all packages (accommodating various exceptions actually takes significant time), I'm going to have to be pedantic and ask you to prefer mainline package-lint.

**Comment by dickmao** [comment]
You got it.

**Comment by riscy** [comment]
Thanks!  This looks good to go.  I've edited your recipe since it's equivalent to the default (this will potentially give you the flexibility to "expand" the repository without needing to open another PR).

**Pull request merged**
