### PR TITLE
Add walkman recipe

### PR DESCRIPTION
**Pull request by abrochard**
### Brief summary of what the package does

Write HTTP requests in Org mode and replay them at will using cURL

### Direct link to the package repository

https://github.com/abrochard/walkman

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
This looks really cool!  The way you use Transient is also really nice.  Some thoughts:

* You might find this useful when it comes to writing tests and such: 
https://github.com/alphapapa/makem.sh
* Some of your curl-related code is similar to code I have in https://github.com/alphapapa/plz.el.  Please feel free to chime in there if you're interested in the project.
* You might find `pcase-let*` or `-let` helpful for destructuring, e.g. at https://github.com/abrochard/walkman/blob/f9d605e8c9fa3c9ff443ce39be4556f56c0e5e3a/walkman.el#L97 you could do:
```el
(defun walkman--to-args (args &optional insecure)
  "Parse into curl args.
ARGS is the arg list.
INSECURE is optional flag to make insecure request."
  (-let (((&alist :verb :host :headers :body) args))
    (append (list "--silent" "-i" "-X" verb host) headers
            (if insecure (list "-k") '())
            (if body (list "-d" body) '()))))
```

**Comment by abrochard** [comment]
> This looks really cool! The way you use Transient is also really nice. Some thoughts:
> 
>     * You might find this useful when it comes to writing tests and such:
>       https://github.com/alphapapa/makem.sh
> 
>     * Some of your curl-related code is similar to code I have in https://github.com/alphapapa/plz.el.  Please feel free to chime in there if you're interested in the project.
> 
>     * You might find `pcase-let*` or `-let` helpful for destructuring, e.g. at https://github.com/abrochard/walkman/blob/f9d605e8c9fa3c9ff443ce39be4556f56c0e5e3a/walkman.el#L97 you could do:
> 
> 
> ```emacs-lisp
> (defun walkman--to-args (args &optional insecure)
>   "Parse into curl args.
> ARGS is the arg list.
> INSECURE is optional flag to make insecure request."
>   (-let (((&alist :verb :host :headers :body) args))
>     (append (list "--silent" "-i" "-X" verb host) headers
>             (if insecure (list "-k") '())
>             (if body (list "-d" body) '()))))
> ```

Thank you very much!
I will check out makem.sh and plz.el.

I actually have some related questions:
- I have an uncommitted unit test file, what is the common practice with it? Add it in a folder? Add it as `walkman_test.el`? Exclude it from the recipe?
- regarding destructuring, I'm actually debating using `cl-defstruct` to structure the request data a bit more. any disadvantages to doing that?

**Comment by alphapapa** [comment]
> I actually have some related questions:
> 
> * I have an uncommitted unit test file, what is the common practice with it? Add it in a folder? Add it as `walkman_test.el`? Exclude it from the recipe?

I'm not sure what you're asking.  If you're asking relating to `makem.sh`, it uses, by default, files that git knows about.  If you want to include a file not in git, see the usage instructions about `-f`.  If you're asking about the recipe, test files are not included in packages.

> * regarding destructuring, I'm actually debating using `cl-defstruct` to structure the request data a bit more. any disadvantages to doing that?

No, it's generally a good idea to do so.  You can also use `pcase-let*` to destructure and bind them as well; here's an example I have handy: https://github.com/alphapapa/org-ql/blob/wip/view-section/org-ql-view-section.el#L194

**Comment by abrochard** [comment]
> I'm not sure what you're asking. If you're asking relating to `makem.sh`, it uses, by default, files that git knows about. If you want to include a file not in git, see the usage instructions about `-f`. If you're asking about the recipe, test files are not included in packages.

Sorry I was unclear. I am asking if there is a convention in emacs lisp on:
- how to name your test file? should it be `walkman_test.el` for example
- where to put the test file in relation to the main file? is it a neighbor? subdirectory?
- does the recipe automatically exclude test files and how so?


> No, it's generally a good idea to do so. You can also use `pcase-let*` to destructure and bind them as well; here's an example I have handy: https://github.com/alphapapa/org-ql/blob/wip/view-section/org-ql-view-section.el#L194

Sweet. I'll check it out

**Comment by alphapapa** [comment]
There is no official rule that I'm aware of.  A common pattern seems to be to put Elisp test files in a `test/` subdirectory and suffix each filename with `-test`, like `package-name-test.el`.  That's what I generally recommend.

The default recipe excludes such files.  You can find more information in the MELPA docs.

**Comment by abrochard** [comment]
> There is no official rule that I'm aware of. A common pattern seems to be to put Elisp test files in a `test/` subdirectory and suffix each filename with `-test`, like `package-name-test.el`. That's what I generally recommend.
> 
> The default recipe excludes such files. You can find more information in the MELPA docs.

Great! I'll do that. Thanks!

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

1. Please consider adding Cask file is good to easy resolve dependency, build, packaging etc.
2. Please consider adding .gitignore file is good to ignore git stage *.elc files and .cask folder.
3. Please use `nreverse` instead of `reverse` in `push/nreverse` idiom
4. Please consider `walkman-mode` as minor-mode instead of just function?
  If you define `walkman-mode` as minor-mode, user can toggle this package and suit function name.
  Or, don't prepare minor-mode and bind some funcitons by user-hand is also good I think.
5. As I'm japanese, `walkman` comes only Sony's music-player :) see [Wikipedia](https://en.wikipedia.org/wiki/Walkman)
  I cannot imagine this package feature from this package name. Why are you name this package as `Walkman`?

**Comment by abrochard** [comment]
Thank you very much for your feedback.

>     1. Please consider adding Cask file is good to easy resolve dependency, build, packaging etc.
👍 
>     2. Please consider adding .gitignore file is good to ignore git stage *.elc files and .cask folder.
👍  
>     3. Please use `nreverse` instead of `reverse` in `push/nreverse` idiom
👍 
>     4. Please consider `walkman-mode` as minor-mode instead of just function?
>        If you define `walkman-mode` as minor-mode, user can toggle this package and suit function name.
>        Or, don't prepare minor-mode and bind some funcitons by user-hand is also good I think.
Left some questions about this on the PR 
>     5. As I'm japanese, `walkman` comes only Sony's music-player :) see [Wikipedia](https://en.wikipedia.org/wiki/Walkman)
>        I cannot imagine this package feature from this package name. Why are you name this package as `Walkman`?

In my culture, the word `walkman` evolved to refer to all audio cassette players. Also the point of the package is to be an old school alternative to [Postman](https://www.postman.com/) which uses curl. For that reason, I wanted a word that sounded a bit like postman but that also sounded old school and had a notion of recordings/entries.

**Comment by conao3** [comment]
> In my culture, the word walkman evolved to refer to all audio cassette players. Also the point of the package is to be an old school alternative to Postman which uses curl. For that reason, I wanted a word that sounded a bit like postman but that also sounded old school and had a notion of recordings/entries.

Good, I understand, thanks!

**Comment by riscy** [comment]
Thanks for your patience -- this looks great.

**Comment by abrochard** [comment]
Thank you so much! No worries at all!

**Pull request merged**
