### PR TITLE
Add standard-dirs

### PR DESCRIPTION
**Pull request by lafrenierejm**
### Brief summary of what the package does

Provide platform-specific paths for configuration, cache, and other data

### Direct link to the package repository

https://github.com/lafrenierejm/directories-elisp

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

NA

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This looks good to me -- at first I thought there were quite a lot of autoload cookies, but they seem correctly applied based on the package's use case.  One request is to add a LICENSE file that GitHub can detect (e.g. no markup) if possible (See: https://github.com/licensee/licensee).  

And a minor typo while I'm here being pedantic:
- platform-specfic -> platform-specific

**Comment by lafrenierejm** [comment]
> One request is to add a LICENSE file that GitHub can detect (e.g. no markup) if possible (See: https://github.com/licensee/licensee).

Done in [eac64290f524b1c5c972653a28c41d4c5ed5e626](https://github.com/lafrenierejm/directories-elisp/commit/5f7e077f0d3acb818dc2c251f1170a84a78ab399).

> And a minor typo while I'm here being pedantic:
>
> * platform-specfic -> platform-specific

Thanks for catching that.  Fixed in [eac64290f524b1c5c972653a28c41d4c5ed5e626](https://github.com/lafrenierejm/directories-elisp/commit/eac64290f524b1c5c972653a28c41d4c5ed5e626).

**Comment by purcell** [comment]
Nice! I feel like the "directories" package name is a little too broad, and is likely to lead to confusion, since "directories" has a lot of connotations. Might I suggest "platform-directories", "shared-directories", "standard-directories" or "common-directories"? I know they're a bit longer, but I think that's a good thing in this case. (You could always contract "-directories" to "-dirs" or "-paths", of course.)

**Comment by lafrenierejm** [comment]
The package and its name was inspired by the libraries in https://github.com/dirs-dev. I'd be glad to rename this package (my preference woul be "standard-dirs"), though, if the  existence of those libraries doesn't feel like it justifies the current name. Any input would be appreciated.

**Comment by riscy** [comment]
Just chiming in here, but I like standard-dirs (or dirs-standard if you want some symmetry with the stuff in dirs-dev.

**Comment by lafrenierejm** [comment]
The package has been renamed to `standard-dirs`.

**Comment by riscy** [comment]
This might be a good time to rename the repository too, so there's a match -- as well as the recipe here.

**Comment by lafrenierejm** [comment]
> This might be a good time to rename the repository too, so there's a match -- as well as the recipe here.

Oops.  Thanks for pointing that out.  It should be done now.

**Comment by riscy** [comment]
Welcome to MELPA. :)

**Comment by lafrenierejm** [comment]
Thanks, @riscy.

**Pull request merged**
