### PR TITLE
Add ivy-phpunit recipe.

### PR DESCRIPTION
**Pull request by 12pt**
### Brief summary of what the package does

Provides an ivy interface to `phpunit.el`. Provides several convenience methods such as showing potential test classes, test functions in the current buffer, and quick-jumping between test classes in the current directory.

### Direct link to the package repository

https://github.com/12pt/ivy-phpunit

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks for this! Quick feedback:

- Don't test filenames with [regexps ending in `$`](https://github.com/12pt/ivy-phpunit/blob/57668e2e6bdb668dfcf106252bb206cc88cb96d2/ivy-phpunit.el#L49) - use `\\'` instead, which matches end-of-string rather than end-of-line.
- Don't [`concat` filenames into shell command strings](https://github.com/12pt/ivy-phpunit/blob/57668e2e6bdb668dfcf106252bb206cc88cb96d2/ivy-phpunit.el#L70) without first escaping them using `shell-quote-argument` -- you have to assume they might contain spaces, quotes, semicolons etc. to be safe.

Looks good otherwise. :-)

**Comment by 12pt** [comment]
Hello, thanks for the feedback; I've updated 12pt/ivy-phpunit with the required changes, let me know if anything else is necessary. :)

**Comment by purcell** [comment]
Thanks - merged now! Appreciate your patience.

**Comment by 12pt** [comment]
Thanks!

**Pull request merged**
