### PR TITLE
Add gitpatch recipe

### PR DESCRIPTION
**Pull request by tumashu**
### Brief summary of what the package does

```
;; Gitpatch is git-format patch toolkit, which let user easy handle
;; git-format patch without exit emacs.

;; 1. Send patch with `gitpatch-mail'

;;    `gitpatch-mail' can quick send a git-format patch file from magit,
;;    dired or ibuffer buffer.
```

### Direct link to the package repository

https://github.com/tumashu/gitpatch

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by tumashu** [comment]
gnus-select-account is another package, which let user select an account before write a email.

**Comment by purcell** [comment]
Thanks. In future you should put recipes in a separate pull request so they can be reviewed independently.

Regarding gitpatch, that mostly looks good, but "C-c i" is reserved for end-user customisation, so you should choose a different keybinding.

Regarding gnus-select-account, `defgroup` is missing.

**Comment by tumashu** [comment]
```
Thanks. In future you should put recipes in a separate pull request so they can be reviewed independently.
```
Sorry, maybe next time I should use a seperate branch to pull request.

```
Regarding gitpatch, that mostly looks good, but "C-c i" is reserved for end-user customisation, so you should choose a different keybinding.

Regarding gnus-select-account, defgroup is missing.
```
1. "C-c i"  -> "C-x i"
2. gnus-select-account added

**Comment by purcell** [comment]
`C-x i` is a built-in binding (`insert-file`), so I wouldn't recommend using that either.

**Comment by tumashu** [comment]
```
C-x i is a built-in binding (insert-file), so I wouldn't recommend using that either.
```
I will find another key,

by the way: In my opinion,  if I write a mail to send patch file,  insert patch file is just  insert file :-),

**Comment by tumashu** [comment]
I just leave it to user:-) and set nil by default

**Comment by purcell** [comment]
Makes sense. Merged, thanks.

**Pull request merged**
