### PR TITLE
Add recipe for nextflow-mode

### PR DESCRIPTION
**Pull request by edmundmiller**
### Brief summary of what the package does

Adds syntax highlighting for [Nextflow](https://www.nextflow.io/)

### Direct link to the package repository

https://github.com/Emiller88/nextflow-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Very quick first pass --

`nextflow-mode.el` with byte-compile using Emacs 28.1:
```
nextflow-mode.el:25:1: Error: Cannot open load file: No such file or directory, groovy-mode
```
I think this is just a missing Package-Requires on groovy-mode?

`nextflow-mode.el` with checkdoc 0.6.2:
```
nextflow-mode.el:32: First sentence should end with punctuation
nextflow-mode.el:146: All variables and subroutines might as well have a documentation string
nextflow-mode.el:196: All variables and subroutines might as well have a documentation string
nextflow-mode.el:201: All variables and subroutines might as well have a documentation string
```

`nextflow-mode.el` with package-lint 20220607.738:
```
1 issue found:
31:0: error: Customization groups should not end in "-mode" unless that name would conflict with their parent group.
```

`nextflow-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- nextflow-mode.el#L209: It's safer to sharp-quote function names; use `#'`
- nextflow-mode.el#L210: It's safer to sharp-quote function names; use `#'`
- nextflow-mode.el#L213: It's safer to sharp-quote function names; use `#'`
- nextflow-mode.el#L214: It's safer to sharp-quote function names; use `#'`
```

`#'load`-check on each file:
```
Loading nextflow-mode.el
  nextflow-mode.el:Error: Emacs 28.1:
  (file-missing "Cannot open load file" "No such file or directory" "groovy-mode")
```

Package and license:
- GNU General Public License v3.0 -- repo license
- unknown license -- nextflow-mode.el: Major mode for editing Nextflow files
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to nextflow-mode.el

**Comment by riscy** [comment]
I'll mark this one awaiting-upstream for now, but feel free to reach out.

**Comment by tarsius** [comment]
Friendly ping. :ping_pong:

**Comment by riscy** [comment]
It's been over a year so I'll close for now.  Feel free to reopen when ready!

**Pull request closed without merging**
