### PR TITLE
admb-mode and tmb-mode

### PR DESCRIPTION
**Pull request by arnima-github**
### Brief summary of what the package does

`admb-mode` and `tmb-mode` are major modes for developing statistical models with the free software platforms AD Model Builder (http://admb-project.org) and Template Model Builder (http://tmb-project.org).

### Direct link to the package repository

https://github.com/admb-project/admb/tree/master/contrib/emacs
https://github.com/kaskr/adcomp/tree/master/emacs

### Your association with the package

Creator and maintainer of both.

### Relevant communications with the upstream package maintainer.

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick feedback, first for `admb`:

- The [version variable](https://github.com/admb-project/admb/blob/7219ff4e1f348383c603b342125c5f8e480b0cea/contrib/emacs/admb.el#L9) breaks the file header so it can't be parsed. Better to not include it anyway, usually: MELPA will insert a version, which for MELPA Stable will be the last version tag on the repo.
- It's not appropriate to [change `PATH` for the user](https://github.com/admb-project/admb/blob/7219ff4e1f348383c603b342125c5f8e480b0cea/contrib/emacs/admb.el#L101-L102) as a side effect of them loading the library
- The `\n` literals in the multi-line docstrings are unusual and undesirable: just put in an extra literal line break.
- The keybindings are all over the place, ranging from function keys, M-up/M-down etc., M-return. You should follow the [emacs lisp conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html) in assigning these. Hard-coding tab to `indent-relative` shouldn't normally be done either: instead, set `indent-line-function` for your mode.
- Don't cram [multiple statement forms](https://github.com/admb-project/admb/blob/7219ff4e1f348383c603b342125c5f8e480b0cea/contrib/emacs/admb.el#L409) onto one line.
- When matching patterns against filenames, use `\\'` to match the end of the string, so that `.barrel` doesn't match `\\.bar` etc.
- Leave empty lines [between functions](https://github.com/admb-project/admb/blob/7219ff4e1f348383c603b342125c5f8e480b0cea/contrib/emacs/admb.el#L491) - really, the code is very unidiomatically formatted, and therefore harder to follow and review than it should be.
- Don't [define `prog-mode`](https://github.com/admb-project/admb/blob/7219ff4e1f348383c603b342125c5f8e480b0cea/contrib/emacs/admb.el#L701) if it's missing - instead, name `(emacs "24")` as a package dependency.
- Don't [assume that the buffer name is a file name](https://github.com/admb-project/admb/blob/7219ff4e1f348383c603b342125c5f8e480b0cea/contrib/emacs/admb.el#L462) - it might not be. See `(buffer-file-name)`. Also, don't ever `concat` filenames into commands without escaping them with `shell-quote-argument` -- they might contain spaces or quotes.

Re. `tmb`, I mostly have much of the same feedback.

Hope that helps!

**Comment by DamienCassou** [comment]
Any news?

**Comment by arnima-github** [comment]
Thank you Steve, for a thorough and well-thought review. I'll make revisions and get back to you.

**Comment by DamienCassou** [comment]
Should we close this for now?

**Comment by purcell** [comment]
Yes, closing for now due to lack of response. Feel free to re-open later.

**Pull request closed without merging**
