### PR TITLE
Add recipe for package `org-recollect`

### PR DESCRIPTION
**Pull request by ykgoon**
### Brief summary of what the package does

Recollect and revisit forgotten org notes.

### Direct link to the package repository

https://github.com/ykgoon/org-recollect

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
### org-recollect.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
No issues found.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
org-recollect.el:8:1:Error: Cannot open load file: No such file or directory, dash
```
(This one needs to be added to your `Package-Requires` line too)

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other static checks:
- org-recollect.el#L2: Use `Version` instead of `Package-Version` (MELPA automatically adds `Package-Version`)

**Comment by riscy** [comment]
Also, please use a [GPL-compatible](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses) license.

**Comment by alphapapa** [comment]
1.  Your readme mentions inspiration by the package https://github.com/mwfogleman/org-randomnote, but it doesn't explain your package's purpose over org-randomnote.  From what I can tell, it allows the user to specify a regexp to match potential candidates.  Have you suggested that this functionality be implemented in `org-randomnote` instead of making a new, slightly different package?
2.  I see that, 10 days ago, you posted this issue on the org-randomnote repo asking to implement a feature to show a random note in the current buffer: https://github.com/mwfogleman/org-randomnote/issues/10  That's not long to wait for a response, especially at this time of year.  Why don't you ping the issue again, and be sure to tag @mwfogleman so he will notice.
3.  I'd recommend using `org-ql` for this.  It will be much faster and simpler.  I already opened an issue on the org-randomnote repo talking about faster implementations: https://github.com/mwfogleman/org-randomnote/issues/4 .  Here's one that uses `org-ql`.  It's simple, fast, flexible, and evenly weighted:

```el
(cl-defun org-goto-random-heading (&key (buffers (list (current-buffer)))
                                        regexp)
  (let* ((entries (org-ql-select buffers
                    `(regexp ,regexp)
                    :action '(cons (current-buffer) (point))))
         (entry (seq-random-elt entries)))
    (pop-to-buffer (car entry))
    (goto-char (cdr entry))))
```
Use it like:
```el
(org-goto-random-heading :buffers "~/org/main.org" :regexp "Emacs")
```

**Comment by tarsius** [comment]
The repository doesn't exist anymore.

**Pull request closed without merging**
