### PR TITLE
Add erc-matterircd

### PR DESCRIPTION
**Pull request by alexmurray**
### Brief summary of what the package does

Provides integration between `erc` and `matterircd` to automatically login to the remote mattermost server on connection to matterircd, and correctly reformats markdown-based formatting used by mattermost for display in erc buffers.

### Direct link to the package repository

https://github.com/alexmurray/erc-matterircd

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
### erc-matterircd.el ###

I need to update my tooling to use Emacs 27.1 today, but in the meantime -

Suggestions/experimental static checks:
- erc-matterircd.el#L172: There is no need to quote lambdas (neither #' nor ')
- erc-matterircd.el#L181: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L182: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L183: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L184: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L187: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L193: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L192: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L194: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L195: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L196: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L197: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L198: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L199: It's safer to sharp-quote function names; use `#'`
- erc-matterircd.el#L24: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Package ###

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by riscy** [comment]
Checklist looks good with Emacs 27.1 -- thanks!

**Comment by alexmurray** [comment]
@riscy Thanks for the review - what tool does this static analysis? I would like to add it to my own setup so I can check for this sort of thing in the future - I already have package-lint configured and am always keen to add more static analysis checks.

**Comment by riscy** [comment]
No problem. :)  This is from https://github.com/riscy/melpazoid

Also, ping me when the LICENSE file is set, and this is an easy merge.

**Comment by alexmurray** [comment]
Thanks - LICENSE added in https://github.com/alexmurray/erc-matterircd/commit/6108204f9a71aa0dd9c6d57bd7f64a5199118e1e

**Pull request merged**
