### PR TITLE
Add recipe edebug-inline-result

### PR DESCRIPTION
**Pull request by stardiviner**
### Brief summary of what the package does

Show edebug result with inline popup.

### Direct link to the package repository

https://github.com/stardiviner/edebug-inline-result

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

### edebug-inline-result.el ###

byte-compile (using Emacs 27.1):
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
edebug-inline-result.el:69:56:Warning: reference to free variable
    `edebug-previous-result'
In edebug-inline-result-enable:
edebug-inline-result.el:112:43:Warning: Use of gv-ref probably requires
    lexical-binding
edebug-inline-result.el:113:9:Warning: assignment to free variable
    `edebug-print-level'
edebug-inline-result.el:114:9:Warning: assignment to free variable
    `edebug-print-length'
In edebug-inline-result-disable:
edebug-inline-result.el:126:45:Warning: assignment to free variable
    `edebug-print-level'
edebug-inline-result.el:127:45:Warning: assignment to free variable
    `edebug-print-length'
In end of data:
edebug-inline-result.el:152:1:Warning: the following functions are not known
    to be defined: posframe-show, popup-tip, quick-peek-show, inline-docs,
    pos-tip-show, posframe-hide, quick-peek-hide, (setf quote),
    posframe-delete
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210111.341):
```
1 issue found:
23:0: error: Package should have a non-empty ;;; Commentary section.
```

Other [lints](https://github.com/riscy/melpazoid):
- edebug-inline-result.el#L21: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading edebug-inline-result.el
Done.
```
```
edebug-inline-result.el: Use of gv-ref probably requires lexical-binding
```

**Comment by stardiviner** [comment]
Lexical-binding issues is solved.

Commentary issue is solved.

https prefer is updated (my yasnippet is already update in previous MELPA packages. this package is created early, so have not updated)

> In end of data:
> edebug-inline-result.el:152:1:Warning: the following functions are not known
>     to be defined: posframe-show, popup-tip, quick-peek-show, inline-docs,
>     pos-tip-show, posframe-hide, quick-peek-hide, (setf quote),
>     posframe-delete

How to solve this problem? I think don't need to explicitly require library before really use them.
Maybe use `declare` or `autoload`?

**Comment by riscy** [comment]
> How to solve this problem?

```
edebug-inline-result.el:76:56:Warning: reference to free variable
    `edebug-previous-result'
```
I believe this is happening because the `pcase` on line 72 is a macro that the byte-compiler is trying to expand, including to resolve the value of edebug-previous-result, but that variable isn't declared until after the macro is expanded.  Possibly this points to a bug where the value there isn't what you think it is.  I believe this is a "wrong time" problem (see https://www.gnu.org/software/emacs/manual/html_node/elisp/Problems-with-Macros.html#Problems-with-Macros).

With regard to these:
```
edebug-inline-result.el:159:1:Warning: the following functions are not known
    to be defined: posframe-show, popup-tip, quick-peek-show, inline-docs,
    pos-tip-show, posframe-hide, quick-peek-hide, (setf quote),
    posframe-delete
```
If you don't want to depend on posframe then you can forward-declare the functions using `declare-function`, but the undefined `(setf quote)` function is surely a macro expansion gone bad, so it might disappear once you diagnose the first issue above.

**Comment by stardiviner** [comment]
After reading the "Wrong time" second of problems of Macro. I tried many `, ' @` etc special characters on pcase sexp. Still can't figure out how to correct it. Hard to understand the macro stuff.... I though I'm not using `defmacro` then is safe without macro. Have not thought meet macro even in `pcase`......
Can you help me by check out my latest code? Thanks in advance.
https://github.com/stardiviner/edebug-inline-result/blob/master/edebug-inline-result.el#L67

**Comment by riscy** [comment]
I have also struggled with the pcase macro. :)  I'll try to take a look at some point, but it'll probably be next weekend at the earliest.

**Comment by stardiviner** [comment]
It's fine. I will ask somewhere too. Thanks @riscy

**Comment by riscy** [comment]
Looks like I sent you off on the wrong track. :)

- I think the main thing is you're missing a `(require 'edebug)`
- The macros that were misfiring were `add-function` / `remove-function` -- you are quoting `'focus-out-hook` for example, but the macro requires that you don't quote it.  This'll solve the `(setf quote)` warning.  Probably this behavior wasn't working, so you should double-check that everything works as you intend after this change

After that we arrive at approximately this byte-compile:
```
edebug-inline-result.el:163:1:Warning: the following functions are not known
    to be defined: posframe-show, popup-tip, quick-peek-show, inline-docs,
    pos-tip-show, posframe-hide, quick-peek-hide, posframe-delete
```
which are expected.  You can tell the compile about these using `declare-function`, e.g. `(declare-function inline-docs "ext:inline-docs.el" t t)` or similar.

I notice also you're using this pattern `(require 'quick-peek nil t)` where the `t` signifies NOERROR -- I'd recommend letting the error fire or at least adding a descriptive warning message, because a failing `require` is much clearer to a user than a failing backtrace leading to an unfamiliar function like `inline-docs`.

**Comment by stardiviner** [comment]
Ok, I fixed all byte compiler warnings and errors now.
Thanks very much, @riscy

**Comment by riscy** [comment]
Hi, that's looking good.  You shouldn't quote the declare-function lines -- e.g. you want `(declare-function posframe-show "ext:posframe.el" t t)`.  You also want to make sure you get posframe-hide, quick-peek-hide, and posframe-delete.

**Comment by stardiviner** [comment]
@riscy Aha, sorry for this mistake. Fixed now. Thanks, still pushing. Should be available soon.

**Comment by riscy** [comment]
Sounds good!  Feel free to ping when ready.

**Comment by stardiviner** [comment]
Pushed already. Gentle ping ... 😄

**Comment by riscy** [comment]
Here's the latest --

byte-compile (using Emacs 27.1):
```
edebug-inline-result.el:163:1:Warning: the following functions are not known
    to be defined: posframe-hide, quick-peek-hide, posframe-delete
```
You'll also need to do the same for posframe-hide, quick-peek-hide, and posframe-delete by the looks of it.

**Comment by stardiviner** [comment]
@riscy Seems my Emacs loaded them already, so no byte compilation warnings. I updated now. Check out the latest. Thanks 😄

**Comment by riscy** [comment]
Thanks for the grief. :)

**Pull request merged**
