### PR TITLE
Add ivy-fuz

### PR DESCRIPTION
**Pull request by Silex**
### Brief summary of what the package does

Fast and precise fuzzy scoring/matching utils for Emacs, powered by rust, for ivy.

### Direct link to the package repository

https://github.com/Silex/ivy-fuz.el

### Your association with the package

Maintainer.

@cireu I know you didn't want to make this because you feel ivy-fuz is not stable enough, but I find it silly having to copy-paste `ivy-fuz.el` in my installation and hoping it doesn't change often so I made this PR :-)

You of course have the latest word on this, if you feel it might create too much maintenance for you I'll just continue with my copy-paste solution.

### Relevant communications with the upstream package maintainer

**none needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by cireu** [comment]
IMO, you can fork my repo then submit ivy-fuz to melpa. 

I'm not addicted to ivy now , thus I can't help so much solve the issue of `ivy-fuz`.  If you create a recipe point to `rustify-emacs/fuz` directly, I'm afraid that I will be in a dilemma.

**Comment by Silex** [comment]
Alright :+1:

**Comment by riscy** [comment]
Feel free to ping when this is ready to go (also, please restore the original PR template).

**Comment by Silex** [comment]
@riscy: this is ready to go.... you need something else?

**Comment by riscy** [comment]
Yeah, it would be helpful if you could restore the original PR template and fill in the questions.

**Comment by Silex** [comment]
Oh, I thought the checklist was what you did, not that you actually have to do it :laughing: 

Alright, will do.

**Comment by Silex** [comment]
This is what package-lint tells:

```
1 issue found:

1:0: error: package.el cannot parse this buffer: Search failed: ";;; ivy-fuz.el ends here"
```

No clue how to fix that.

**Comment by Silex** [comment]
Okay, I did almost everything: I built successfully with `make` but didn't install.

Btw, `C-c C-c` does not build the recipe on my machine. What do I need to do?

**Comment by riscy** [comment]
Great thanks!

I'll leave the <kbd>C-c C-c</kbd> issue on the back burner for now, but if it's persistent it may be worth raising an issue.

To prevent confusion, would it be worth having @cireu remove the old file?  Simultaneously, you could remove the fuz files from your repository that you aren't maintaining, which would enable you to use the default recipe (preferable).

One quick checklist item:
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
ivy-fuz.el:113: Argument `pattern' should appear (as PATTERN) in the doc string
```

**Comment by Silex** [comment]
> I'll leave the C-c C-c issue on the back burner for now, but if it's persistent it may be worth raising an issue.

I mean, I never managed to get it working. When I open a recipe, it's in fundamental mode, and I don't see any `melpa-mode` or similar I could activate.

> To prevent confusion, would it be worth having @cireu remove the old file? Simultaneously, you could remove the fuz files from your repository that you aren't maintaining, which would enable you to use the default recipe (preferable).

I'm not sure. I planned on making PR's to @cireu's repo from time to time. I guess it depends on him, if he still wants to somewhat support ivy in the future or if he never wants to hear about it. In the later case I think I'd delete my fork and start a new repo because it does not make sense to have it as a fork if their files are completely different.


> One quick checklist item:
> M-x checkdoc (using version 0.6.1):

Right, but this was never a blocker before tho. There are hundreds of packages on MELPA where checkdoc yells all over the place :wink:

**Comment by riscy** [comment]
> In the later case I think I'd delete my fork and start a new repo because it does not make sense to have it as a fork if their files are completely different.

Ok, let's wait for @cireu to chime in.

> There are hundreds of packages on MELPA where checkdoc yells all over the place

I see where you're coming from -- but if they opened their PR's today, we'd ask them to adhere to the current checklist.

**Comment by Silex** [comment]
> > There are hundreds of packages on MELPA where checkdoc yells all over the place
> 
> I see where you're coming from -- but if they opened their PR's today, we'd ask them to adhere to the current checklist.

Alright :wink: I fixed it.

**Comment by cireu** [comment]
> > In the later case I think I'd delete my fork and start a new repo because it does not make sense to have it as a fork if their files are completely different.
> 
> Ok, let's wait for @cireu to chime in.
> 
> > There are hundreds of packages on MELPA where checkdoc yells all over the place
> 
> I see where you're coming from -- but if they opened their PR's today, we'd ask them to adhere to the current checklist.

I will clean `ivy-fuz.el` in `rustify-emacs/fuz` and add a link to @Silex's repo in README. ;)

**Comment by Silex** [comment]
> I will clean `ivy-fuz.el` in `rustify-emacs/fuz` and add a link to @Silex's repo in README. ;)

Alright, I'll make a PR coming from a different repository, probably named `Silex/ivy-fuz.el`.

**Comment by cireu** [comment]
@Silex  @riscy  Done.

**Comment by Silex** [comment]
@cireu: Thanks, but you need to correct the repository... made you a PR at https://github.com/rustify-emacs/fuz.el/pull/6

**Comment by Silex** [comment]
@riscy: I still need to add a README and things like that to my new repo but otherwise it'd be ready to go.

**Comment by Silex** [comment]
@riscy: are you waiting on something? everything is good to go IMHO.

**Comment by riscy** [comment]
Sorry, my personal laptop is bricked at the moment.

**Comment by Silex** [comment]
Oh ok, no worries.

**Comment by riscy** [comment]
Thanks very much for your patience!  This looks good to go. :)

**Pull request merged**
