### PR TITLE
Add recipe burn

### PR DESCRIPTION
**Pull request by tanrax**
### Brief summary of what the package does

Clears the entire buffer with an expanding fire animation

### Direct link to the package repository

https://github.com/tanrax/burn.el

### Your association with the package

Maintainer

### Checklist

Please confirm with `x`:

- [ x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [ x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x] My elisp byte-compiles cleanly
- [ x] `M-x checkdoc` is happy with my docstrings
- [ x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
Please fix this error:

```
Recipe ’burn’ contains mismatched package name ’smex’
```

**Comment by tanrax** [comment]
Sorry. Updated!

**Comment by riscy** [comment]
Quick first pass --

### burn.el ###

byte-compile (using Emacs 27.1):
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
burn.el:14:7:Warning: assignment to free variable `burn--emoji'
burn.el:15:7:Warning: assignment to free variable `burn--interval'
In burn--is-empty:
burn.el:20:78:Warning: reference to free variable `burn--emoji'
In burn--replace-backward-at-point:
burn.el:24:47:Warning: reference to free variable `burn--emoji'
In burn--replace-forward-at-point:
burn.el:29:46:Warning: reference to free variable `burn--emoji'
In burn-code:
burn.el:37:14:Warning: reference to free variable `burn--interval'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
burn.el:18: All variables and subroutines might as well have a documentation string
```

package-lint (using version 20200906.512):
```
2 issues found:
1:0: error: There is no (provide 'burn) form.
40:4: warning: Closing parens should not be wrapped onto new lines.
```

**Comment by tanrax** [comment]
Sorry again, I didn't know I could use flycheck to improve my code. I have already corrected everything. (with you I'm learning )

**Comment by tanrax** [comment]
I made the changes yesterday, do you need anything from me? Thanks for everything

**Comment by riscy** [comment]
Yeah, flycheck is a great tool that takes some of the grief out of getting a clean byte-compile.   And now everything in the checklist passes, thanks for that. :)

As I look more closely at this, it looks like a cool demo, but it's simple enough that it feels to me more like a snippet or gist than something that would normally be indexed in MELPA.  Granted, there _are_ a few animated demos in MELPA like snow and flames-of-freedom, but these are both fairly substantial animation demos that you could draw inspiration from.

**Comment by tanrax** [comment]
> Yeah, flycheck is a great tool that takes some of the grief out of getting a clean byte-compile. And now everything in the checklist passes, thanks for that. :)
> 
> As I look more closely at this, it looks like a cool demo, but it's simple enough that it feels to me more like a snippet or gist than something that would normally be indexed in MELPA. Granted, there _are_ a few animated demos in MELPA like snow and flames-of-freedom, but these are both fairly substantial animation demos that you could draw inspiration from.

I understand.

It's actually more of a way of emptying a buffer in a funny way. I found it useful to clean up and start again with a smile 😀. At least that's the feeling it gives me.

**Comment by riscy** [comment]
Thanks for understanding.  I'll close this for now, but I could see this extending to something like a collection of animated ways of erasing buffers, for instance a minor mode that advises `erase-buffer` and chooses a random animation from the collection.

**Pull request closed without merging**
