### PR TITLE
Add ynab recipe

### PR DESCRIPTION
**Pull request by janders223**
### Brief summary of what the package does

Provides a major mode for interacting with ynab

### Direct link to the package repository

https://github.com/janders223/ynab.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Regarding the package name, I'm assuming this means "you need a budget", but I had to google that.  To help discoverability in the MELPA index, it may be worth unpacking that initialism so that people who (for example) search for the word "budget" will find this.

Quick pass over the checklist in the meantime --

### ynab.el ###

byte-compile-file (using Emacs 26.3):
```
ynab.el:60:1:Warning: Unused lexical variable `calc-date-format'
```

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200419.406):
```
2 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
10:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```

Suggestions/experimental static checks:
- ynab.el#L5: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by janders223** [comment]
Thanks for your help Chris. I believe I have addressed the mentioned
issues.

**Comment by riscy** [comment]
Summary looks great now, thanks.  Since the last update:

package-lint-current-buffer (using version 20200419.406):
```
1 issue found:
49:0: error: "last-used" doesn't start with package's prefix "ynab".
```

And:
- ynab.el#L142: It's safer to sharp-quote function names; use `#'`
- ynab.el#L90: No `format` required; messages are already f-strings

**Comment by janders223** [comment]
Updated, thanks @riscy.

**Pull request merged**
