### PR TITLE
Add recipe for jack

### PR DESCRIPTION
**Pull request by tonyaldon**
### Brief summary of what the package does

jack is a HTML renderer library for Emacs Lisp.

### Direct link to the package repository

https://github.com/tonyaldon/jack

### Your association with the package

I'm the author of this package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`jack.el` with byte-compile using Emacs 28.1:
```
jack.el:91:27: Warning: `((keywordp tag-kw))' is a malformed function
jack.el:108:34: Warning: reference to free variable `tag-s'
In jack-tag:
jack.el:116:35: Warning: `(c (assoc :class pairs))' is a malformed function
jack.el:116:35: Warning: `(c (assoc :class pairs))' is a malformed function
jack.el:158:65: Warning: reference to free variable `c'
In jack-html:
jack.el:197:8: Warning: docstring wider than 80 characters
In end of data:
jack.el:168:27: Warning: the function `string-empty-p' is not known to be
    defined.
jack.el:167:22: Warning: the function `string-join' is not known to be
    defined.
jack.el:102:14: Warning: the function `tag-s' is not known to be defined.
jack.el:101:4: Warning: the function `if-let*' is not known to be defined.
```

`jack.el` with checkdoc 0.6.2:
```
jack.el:69: Symbols t and nil should not appear in single quotes
jack.el:137: Documentation strings should not start or end with whitespace
jack.el:175: All variables and subroutines might as well have a documentation string
jack.el:181: All variables and subroutines might as well have a documentation string
jack.el:191: All variables and subroutines might as well have a documentation string
jack.el:198: Some lines are over 80 columns wide
jack.el:218: Symbols t and nil should not appear in single quotes
```
I notice you didn't tick the box for checkdoc, but we currently ask all authors to take a look at its feedback and address what's feasible to address.

`jack.el` with package-lint 20221003.1636:
```
1 issue found:
110:34: error: You should depend on (emacs "28.1") if you need `string-replace'.
```

**Comment by progfolio** [comment]
In addition to the above:

```
jack.el:68:2: Warning: defvar `jack-html-raise-error-p' docstring has wrong usage of unescaped single quotes (use \= or different quoting)                              
jack.el:116:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)                                                             
jack.el:197:2: Warning: docstring wider than 80 characters                                                                                                             
jack.el:197:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)                                                             
```

You may also want to consider `require`-ing the main library in your test file.
Either that or adding a no-byte-compile var to the file. e.g.:

```emacs-lisp
;; Local Variables:
;; no-byte-compile: t
;; End:
```

**Comment by tonyaldon** [comment]
Thanks for reviewing `jack`.

I made the changes corresponding to package-lint and checkdoc.  I only
left one large line in a docstring.

I also required `jack` in the test file.

Regarding the Byte compilation I don't have all the warnings you
have.  I'm running Emacs 28.1:

    (emacs-version) ; "GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2022-05-31"

And running `byte-compile-file` on `jack` gives me only this warning:

    In jack-html:
    jack.el:204:8: Warning: docstring wider than 80 characters

**Comment by progfolio** [comment]
>  I only left one large line in a docstring.

I would recommend re-formatting or rewording that docstring to avoid the warning.
It looks like your examples include HTML output. You could add some newlines to that and mention that it is formatted for clarity.

> Regarding the Byte compilation I don't have all the warnings you
have. I'm running Emacs 28.1.

Yes. This is a newer warning that was added, however it should be fixed. The rational is that unescaped single quotes in docstrings will render as curly quotes in the \*Help* buffer. Escaping them (the syntax is `\\='`)  will cause them to be rendered as straight quotes so people reading your documentation can copy your examples and actually run them.

**Comment by tonyaldon** [comment]
I've just updated the docstrings.

**Comment by riscy** [comment]
Thanks very much both --

> Regarding the Byte compilation I don't have all the warnings you have.

It looks like you're compiling on an Emacs runtime with `subr-x` already brought in.  Adding a `(require 'subr-x)` should fix that.

Some minor stuff while I'm looking a little more closely:
- It's unusual note to capitalize the section headers (`;;; Code:` and `;;; Commentary:`); I'm not 100% sure every parser will be fine with these breaks in convention, so I'd recommend capitalizing them
- `jack-escape` looks specific to the internals of your code (i.e. it doesn't escape "everything") so I'd recommend renaming to `jack--escape` so nobody gets the idea in their head that they can depend on it
- caracters -> characters

**Comment by progfolio** [comment]
> Adding a (require 'subr-x) should fix that.

Usually you'll want `(eval-when-compile (require 'subr-x))`

**Comment by tonyaldon** [comment]
I've just updated `jack` based on your suggestions.

**Comment by riscy** [comment]
Thanks, this looks good to merge.  If you haven't already, I'd recommend you check out [htmlize](https://melpa.org/#/htmlize), which is more about converting the visual content of a buffer to HTML, but there are some implementation overlaps you might draw inspiration from, e.g. maybe `htmlize-string-to-html`.

**Pull request merged**
