### PR TITLE
Add recursion-indicator recipe

### PR DESCRIPTION
**Pull request by minad**
### Brief summary of what the package does

Show recursion-indicator in the mode-line.

### Direct link to the package repository

https://github.com/minad/recursion-indicator

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by minad** [comment]
Additional notes for reviewers: This is a really simple package which only marries two different builtin indicators, to show the recursion level (minibuffer-depth-indicate-mode and the brackets around the mode for recursive editing). I like it more to have these two indicators unified since both minibuffer and recursive-edit are recursion levels. Maybe there is also potential for more indicators, like for example indicating a debugger recursion level by showing a small :beetle:. But for now the status of the package is the one I've used for a while as part of my init.el and extracted from the init.el as a separate package.

**Comment by riscy** [comment]
Hello, just letting you know I see this but will check it more closely on my next cycle since I just looked at one of your PRs.  I can quickly mention you may want to revise

> "Recursive edit, type C-M-c to get out"

Since I think it's possible someone could modify the global map and bind this chord to something else.  `M-x exit-recursive-edit` could work.  Maybe check the function `where-is`?  I'll return to this.

**Comment by minad** [comment]
> "Recursive edit, type C-M-c to get out"

I think I copied this from how the mode-line-format-modes where this is used as tooltip. I think it is "messed-up" there too. I have to recheck. But I agree that this should be improved.

Two other things you might find during your review and which I thought about improving:

1. Better face definitions
2. Maybe add support for customizable characters in order to configure for ascii only?

How do you feel about these points? Point 2 is not too important for me from these two.

**Comment by riscy** [comment]
> Better face definitions. The problem I had with this is that ideally I would like to inherit only the color from some of the default faces. I don't want to inherit more properties in order to not mess up of some of the other face definitions applied to the mode line.

I'd suggest just inheriting the faces without modification (or using them directly).  This makes it easy for themes to support the face, and it makes it easy for users to fix problems you might not anticipate with the colors.

I might be missing something, so do you have some examples of other face attributes affecting the mode line?  (I can imagine modifications to the height of the face could matter, but that's probably rare.)  I guess one attribute you _would_ want to have an effect is `:inverse-video`.

**Comment by minad** [comment]
I think some faces are applied to the whole modeline, so if I inherit from some font-lock face this could mess up some other face properties. I will make few tests if I find something satisfactory. Otherwise I can define my own colors, but I would like to avoid that if possible.

Do you have more things you would like to have addressed. This is a pretty simple thing over all.

**Comment by minad** [comment]
@riscy I managed to fix the face issue I had by inheriting from both font-lock and mode-line faces. See here https://github.com/minad/recursion-indicator/commit/37fd949f1430caad50d12dd5e9f1b77fc47fa31e

**Comment by minad** [comment]
@riscy From my side this is ready. Do you agree?

**Comment by riscy** [comment]
I'll take a look soon!

**Comment by riscy** [comment]
Great -- thanks for this.

**Pull request merged**
