### PR TITLE
Make Python 3 the default Python in CI (#7482)

### PR DESCRIPTION
**Pull request by lassik**
If I understood issue #7482 correctly, MELPA CI needs to be upgraded from Python 2 to Python 3. This PR does that.

### CODE REVIEW

**Comment by lassik** [comment]
Wait.

[From this SO thread](https://stackoverflow.com/questions/43062608/how-to-update-alternatives-to-python-3-without-breaking-apt):

> Per Debian policy, `python` refers to Python 2 and `python3` refers to Python 3. Don't try to change this system-wide or you are in for the sort of trouble you already discovered.

Also from [the Cask install script](https://github.com/cask/cask/blob/a05bdf9451db4717c169c9804f0c5259ca2d3a71/go) MELPA CI is using:

```
!!!                    DEPRECATION NOTICE
!!!
!!!
!!!    The cask `go` script will be removed on 2021/06/01.
!!!
!!!    This is due to security concerns about the way python is
!!!    invoked from curl, and to remove the python dependency from cask.
!!!
!!!    The way to install cask without depending on the `go` script
!!!    is very simple.  Just clone Cask and pass the PATH.
!!!
!!!        git clone https://github.com/cask/cask ~/.cask
!!!        PATH=$HOME/.cask/bin:$PATH
!!!
!!!        # If you want to make it permanent
!!!        echo 'PATH=$HOME/.cask/bin:$PATH' >> .bashrc
```

**Comment by lassik** [comment]
OK! Now it installs Cask in the official way (git clone) and edits the shebang line to ensure it says `python3` no matter what the upstream shebang says. This should work now and in the future.

**Comment by riscy** [comment]
I was thinking about just upgrading ubuntu to tackle the Python version issue (thus having only one version of Python to worry about, and no perl script required):

https://github.com/melpa/melpa/compare/python36-for-cask

I still need to add the `git clone`-style install of cask on that branch, however.

**Comment by lassik** [comment]
`docker run -it ubuntu:20.04` and `apt-get update && apt-get install python` shows that the default Python package is 2.x. Does GitHub's Ubuntu have a different configuration?

**Comment by riscy** [comment]
I believe so but it's been a couple weeks since I've touched that branch.  Checking...

**Comment by riscy** [comment]
Yes, Python 3.8.5.

**Comment by lassik** [comment]
PR #7488 is better, so closing this one.

**Pull request closed without merging**
