### PR TITLE
add recipe: org-roam-v1

### PR DESCRIPTION
**Pull request by jethrokuan**
### Brief summary of what the package does

This is just the current version of Org-roam, which will soon be superceded by a large breaking (conceptual) change. To facilitate people staying on the current version, I created a new repo that's pinned to that version.

The current upgrade plan is:

1. Merge v2 branch into master for `org-roam`. The implication is that those who run upgrade to a new version by pulling from MELPA will have their configs break.
2. Point people who don't wish to make the migration yet to just use `org-roam-v1` from MELPA.

I'm doing it this way around because I want v2 to be the original repository, so it inherits all the issues etc. that it had in GitHub.

If someone has another suggestion I'm all ears.

### Direct link to the package repository

https://github.com/org-roam/org-roam-v1

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by jethrokuan** [comment]
ahhh hmm even the file needs to be named org-roam-v1... hmm

**Comment by jethrokuan** [comment]
I renamed the file itself to org-roam-v1, but the functions etc. remain prefixed as `org-roam-`. While there are some function namespace clashes, I think it's reasonable expect users to only be using either v1 or the latest version. What do you think?

**Comment by riscy** [comment]
I don't know the scale of the breaking changes and I don't have a lot of wisdom here, so we may need to get the advice of MELPA maintainers with more experience.  But I would recommend against creating new packages in MELPA as a way to preserve old versions.  If every package started doing things like this, the index could get messy -- but I do sympathize with the fact that the facilities for rolling back are nonexistent.

Beyond how this would affect users, the [current org-roam](https://melpa.org/#/org-roam) also has several packages that depend on it by name.  So if anything should change its name, I would think it should be the rewritten version.

You may already be aware but Emacs does have ways of [marking functions/variables obsolete](https://www.gnu.org/software/emacs/manual/html_node/elisp/Obsolete-Functions.html).  Is it possible you could mark off the bits of public interface that are going to change with obsolete markers?

**Comment by tarsius** [comment]
I would rather avoid doing this.

After I released Magit 2 there was some isolated but loud whining, so I made an elpa archive with just Magit 1.4. I named it just `magit`, so users had to pin to that elpa archive. I don't know whether anyone ever used that. All that's need is to upload an appropriate `archive-contents` file next to the tarball and some instructions for users.

I recommend you create such an archive.

**Comment by jethrokuan** [comment]
> All that's need is to upload an appropriate archive-contents file next to the tarball and some instructions for users.

What do you mean by this? Could you point me to the location of the tarball?

> Beyond how this would affect users, the current org-roam also has several packages that depend on it by name. So if anything should change its name, I would think it should be the rewritten version.

I've been communicating with the authors of these packages, 2/3 are now v2 compatible and we had wanted to make the merge at the same time so everyone who runs `package-update` will receive compatible packages. I'm taking over the migration of the last incompatible package, but it will take some time. v2 has been in the works for over half a year and there are a fair number of users on it, and it feels a lot more stable than the current Org-roam, so I felt it was a good time to merge things in.

> You may already be aware but Emacs does have ways of marking functions/variables obsolete. Is it possible you could mark off the bits of public interface that are going to change with obsolete markers?

For context, Org-roam v2 is almost a complete rewrite of Org-roam: the entire public interface has changed, and it operates on a different conceptual level as Org-roam, making the two highly incompatible. Org-roam has a large amount of technical debt that I as the sole maintainer cannot keep up with, and Org-roam v2 is much smaller and manageable.

Since v2 is a complete rewrite I had also considered giving it a different name and publishing it on MELPA, but a similar problem remains: as I no longer intend to push updates to Org-roam, now the Org-roam on MELPA is for archival purposes.

**Comment by tarsius** [comment]
> I've been communicating with the authors of these packages, 2/3 are now v2 compatible and we had wanted to make the merge at the same time so everyone who runs `package-update` will receive compatible packages.

So really we would want to continue to distribute "v1" versions of these dependent packages as well. I am against doing that on Melpa.

> I've been communicating with the authors of these packages, 2/3 are now v2 compatible and we had wanted to make the merge at the same time so everyone who runs `package-update` will receive compatible packages.

What I was trying to say is that right before you make that switch you should use a script to download `<package>.tar` or `<package>.el` as well as `<package>-readme.txt` from Melpa for `org-roam` and the packages that depend on it. Also download `archive-contents` and remove the entries for all other packages from that. Then upload these files to a webserver into a new directory called `packages` or maybe `org-roam-v1-elpa`, and add documentation on how a user would add that archive to their `package-archives`.

**Comment by jethrokuan** [comment]
After giving it some thought, I think I'll just have users who want to stay on v1 install it by checking it out from the git repository, and provide some instructions on how to do so. I think it makes little sense to continue to distribute v1 given it is now basically EOL. Does MELPA stable keep old tagged releases? If so that's another option.

**Comment by purcell** [comment]
> Does MELPA stable keep old tagged releases? If so that's another option.

No, we don't, sorry.

**Pull request closed without merging**
