### PR TITLE
Add recipe for smilefjes.el

### PR DESCRIPTION
**Pull request by themkat**
### Brief summary of what the package does
Package for checking Mattilsynet (the Norwegian Food Administration) reports on various restaurants in Norway. Each restaurant get a smiley-face score (smile, meh and sad smileys) that is hung up on the doors of all restaurants. It is also provided in a REST API which this package uses. smilefjes is a very Norwegian way of saying smiley.

While this package is very local to Norway, and more of a fun one, I still try to add it to Melpa. Melpa now has many fun packages in addition to more serious ones (e.g, Fireplace.el), and checking restaurant scores (even if it is for only Norway) can be very useful in addition to fun. I myself use it when I'm going to a new take away place or restaurant :) Feel free to ignore if you think it is too weird or specific to Norway.

### Direct link to the package repository

https://github.com/themkat/smilefjes.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer
**None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

I have run package-lint, and it only mentions that the description is too long. While this can be fixed, I think it adds useful information in this case.

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, seems fun. :) Very quick first pass --

`smilefjes.el` with package-lint 20221003.1636:
```
1 issue found:
1:0: warning: The package summary is too long. It should be at most 60 characters.
```

**Comment by themkat** [comment]
> Thanks for this, seems fun. :) Very quick first pass --
> 
> `smilefjes.el` with package-lint 20221003.1636:
> 
> ```
> 1 issue found:
> 1:0: warning: The package summary is too long. It should be at most 60 characters.
> ```

I tried to address this in the last sentence of my PR description: "_I have run package-lint, and it only mentions that the description is too long. While this can be fixed, I think it adds useful information in this case._". We could always remove the "(food administration in Norway)" part of the description, but it adds useful information that might help English speaking people in Norway with understanding the purpose of the package 🙂 Unless you really want me to shorten it, I say we keep it a bit long.

**Comment by progfolio** [comment]
> Unless you really want me to shorten it, I say we keep it a bit long.

Is the mention of mattilsynet necessary in the description? Seems more like a detail for the commentary section.

How about something like?:

"Norwegian Food Safety Authority restaurant rating checker"
or
"View Norwegian Food Safety Authority restaurant ratings"

**Comment by themkat** [comment]
> > Unless you really want me to shorten it, I say we keep it a bit long.
> 
> 
> 
> Is the mention of mattilsynet necessary in the description? Seems more like a detail for the commentary section.
> 
> 
> 
> How about something like?:
> 
> 
> 
> "Norwegian Food Safety Authority restaurant rating checker"
> 
> or
> 
> "View Norwegian Food Safety Authority restaurant ratings"
> 
> 

You got it backwards... Mattilsynet is the important part, as that is the name 99 % of the people in Norway relate these smiley-faces to (they are at the door of every restaurant after all). I would have to guess a lot what "Food Safety Authorithy" even is, because I'm not used to calling it that.

Will remove the paranthesis mentioned above tomorrow. Still think it works better with it though...

**Comment by progfolio** [comment]
Marie Katrine Ekeberg ***@***.***> writes:

> You got it backwards... Mattilsynet is the important part, as 
> that is the name 99 % of the people
> in Norway relate these smiley-faces to (they are at the door of 
> every restaurant after all). I would
> have to guess a lot what "Food Safety Authorithy" even is, 
> because I'm not used to calling it that.

OK. I'm not from Norway, so I'm not familiar with either. If 
that's the important part and the "Food Safety Authority" part is 
not commonly known, 
something like "View Mattilsynet restaurant ratings" or "View 
Mattilsynet ratings for Norwegian restaurants" should suffice.

**Comment by themkat** [comment]
> Marie Katrine Ekeberg ***@***.***> writes:
> You got it backwards... Mattilsynet is the important part, as that is the name 99 % of the people in Norway relate these smiley-faces to (they are at the door of every restaurant after all). I would have to guess a lot what "Food Safety Authorithy" even is, because I'm not used to calling it that.
> OK. I'm not from Norway, so I'm not familiar with either. If that's the important part and the "Food Safety Authority" part is not commonly known, something like "View Mattilsynet restaurant ratings" or "View Mattilsynet ratings for Norwegian restaurants" should suffice.

Deleted my comment before your reply due to having to think it through a bit more. Also, sorry if I was a bit harsh in my reply... 😢  (I blame being late in bed on my phone + a beer for this 😆 )


Your second suggestion actually grew on me! Discussed with some other Norwegians as well, and they said it makes sense to use the English name and have Mattilsynet in the longer Commentary. I live too much in my own head sometimes 🙁 Thanks for the suggestions! 🙂

**Comment by riscy** [comment]
Thanks both, and thanks for accommodating @themkat.  Your reasoning was fair, but I'm stubborn about even the little rules because I try to be consistent with everyone, and every exception I make has the potential to set a precedent that's harder to walk back.

**Pull request merged**
