### PR TITLE
Add flower recipe

### PR DESCRIPTION
**Pull request by profitware**
### Brief summary of what the package does

Flower provides simple interface to list tasks (issues) from Jira, TFS, Gitlab and Github. It uses clomacs under the hood for integration with Flower Clojure library.

### Direct link to the package repository

https://github.com/PositiveTechnologies/flower

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!

- `applications` would probably be a better parent customisation group [than org](https://github.com/PositiveTechnologies/flower/blob/5f67ce7ac174c93695307322e8e7454dd6b06807/flower.el#L49).
- Just because `flower-mode` has been loaded doesn't mean that it should be enabled in every single `org-mode` buffer, so [this line](https://github.com/PositiveTechnologies/flower/blob/5f67ce7ac174c93695307322e8e7454dd6b06807/flower.el#L217) should likely be removed.

Looks good otherwise - nice work!

**Comment by profitware** [comment]
Hi @purcell, 

Thank you for your review! I've fixed those issues and would be happy if I managed to do this correctly.

The overall package functionality may be checked manually using the following code:

```elisp
(require 'flower)

;; Each element of `flower-tracker-queries` vector has the following format:
;; * Tracker URL or nil if only query changed
;; * Use tracker without auth if nil or with default auth otherwise - see Flower auth
;; * Tracker query or nil for default query if applicable
(setq flower-tracker-queries [("https://github.com/PositiveTechnologies/flower" nil nil)
                              ("https://github.com/melpa/melpa" nil nil)])

(add-hook 'org-mode 'flower-mode)

(global-set-key (kbd "C-c f f") 'flower-list-tasks)
(global-set-key (kbd "C-c f t") 'flower-show-task-info)
```

with `C-c f f` to list all tasks from the first task tracker in list, `M-n` to switch between trackers, `M-.` to show contents of the pointed task and `RET` to open task in browser.

I'm going to add this description to README when I release flower 0.4.0.

Thank you.

**Comment by purcell** [comment]
Great, merged - thanks! Welcome to MELPA. :tada:

**Comment by tarsius** [comment]
@profitware do you know what happened to the @PositiveTechnologies organization? It's gone, not just the repository for this package.

**Comment by profitware** [comment]
@tarsius let me please give you a bit of context. Disclaimer: I'm talking not on behalf of my current employer (IBM) or my former employer (Positive Technologies), but rather on behalf of myself. Positive Technologies was put under U.S. sanctions (https://home.treasury.gov/news/press-releases/jy0127) in 2021, so @PositiveTechnologies account was blocked. Flower project was fully implemented by me as a side project (like Nginx was implemented by Igor Sysoev while he was working in Rambler), so I still have full access to the source code (https://github.com/profitware/flower). Also I still have private access to https://github.com/PositiveTechnologies/flower, so I can transfer ownership to another organization if needed. If there is some preferable way to mitigate risk associated with your question - please tell me and I'll try to do this.

**Comment by tarsius** [comment]
We can import from your fork instead. Could you please open a pr to do that?

**Comment by profitware** [comment]
@tarsius I decided to fork the old code into new home - https://github.com/FlowerAutomation - changes reflected in PR #7991 

Thank you!

**Pull request merged**
