### PR TITLE
company-php as  a separate package

### PR DESCRIPTION
**Pull request by xcwen**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Presumably you will now change `ac-php.el` so that it declares a package dependency on `ac-php-core`?

**Comment by xcwen** [comment]
thanks . i merge @purcell   commit .  for remove "for gnu emacs"

----
you will now change ac-php.el so that it declares a package dependency on ac-php-core?

yes .

**Comment by xcwen** [comment]
;; Package-Requires: ((emacs "24") (dash "1") (php-mode "1") (auto-complete "1.4.0") (yasnippet "0.8.0") (xcscope "1") (s "1") (f "0.17.0") (popup "0.5.0") )
=>:
;; Package-Requires: ((ac-php-core "1") (auto-complete "1.4.0") (yasnippet "0.8.0")  )

**Comment by purcell** [comment]
Great! Thanks. :-)

**Pull request merged**
