### PR TITLE
Add recipe plumb

### PR DESCRIPTION
**Pull request by satotake**
### Brief summary of what the package does

plumb.el is a simple utility tool for Emacs.

It has taken an inspiration from Plan9's plumber.

It resembles a feature of 
[ffap](https://www.gnu.org/software/emacs/manual/html_node/emacs/FFAP.html) or
[hyperbole](https://www.gnu.org/software/hyperbole/) within current Emacs packages. 

### Direct link to the package repository

https://git.sr.ht/~satotake/plumb.el

### Your association with the package

Author/Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
This package seems to lack a descriptive description informing potential users of what the package does.

As well, comments in the readme like these suggest that it is not ready to be published on MELPA:

> NOTE: This package is alpha state and specifications are highly unstable for now.

> I'm a Dooms Emacs user, thus has not tested yet, but you will be able to use this on the other distros.

> NOTE: Be careful about security when you use someones' local rulesets. This can be danger.

**Comment by satotake** [comment]
> This package seems to lack a descriptive description informing potential users of what the package does.

```
This package provides 2 type of functions for `pred' and for `action'.
`pred' is used for guessing "thing" at the location point (such as filepath, url and so on).
`action' is called based on the result of `pred'.
Combined with these functions and defining as a `rule', you can interact with string text
around the point. It is similar to `ffap' but you can do more things freely.

For example, with pre-defined ruleset `plumb-default-ruleset:path', you can

- from url, open brower (same as `ffap')
- from filepath around the point, find-file it (same as `ffap')
- from filepath with line/col number, find-file it and jump to the position (like vscode)
- from commit hash in git repo, display commit patch
- from issue number in github repo source, open the issue page (like previous `gh' cli)

`plumb-use' handles rulesets and it is recommended that these are set as keybinding:

(global-set-key [...]
   #'(lambda nil (interactive) (plumb-use plumb-default-ruleset:path)))

```

Does it looks more descriptive? Any suggestions are welcome.



> As well, comments in the readme like these suggest that it is not ready to be published on MELPA:

So you mean this package needs more stability and more tests, right?

At these point, it will take some time.

Could I recreate PR in the near future after battle tests.


Thanks for your advice @alphapapa

P.S. I added some commits becaue I am wondering why CI failed but plesase do not care.
(I am going to close this PR if it is ok.)

**Comment by alphapapa** [comment]
That's a better description, but for someone who has no idea what it does, it still isn't easy to understand.

As well, it sounds like a reimplementation of `thing-at-point`, which is built-in to Emacs.  Are you familiar with that?  If you are, and you wrote Plumb anyway, it would be good to compare and contrast them so users will know what makes your package better.  If you aren't, maybe you could extend `thing-at-point` instead of reinventing the wheel.

> So you mean this package needs more stability and more tests, right?

I can't say what it needs, because I haven't used it, and it's your code.  I'm just pointing out what you said, which doesn't sound like a package ready for widespread use.

> (I am going to close this PR if it is ok.)

It's your PR, so it's up to you.  Please note that I am not a MELPA maintainer so these are merely my opinions.

**Comment by satotake** [comment]
> As well, it sounds like a reimplementation of thing-at-point, which is built-in to Emacs. Are you familiar with that? If you are, and you wrote Plumb anyway, it would be good to compare and contrast them so users will know what makes your package better. If you aren't, maybe you could extend thing-at-point instead of reinventing the wheel.

In fact, this package uses `thing-at-point` internally. So it is not reinventing but extending.
At this point, it is similar to features of `find-file-at-point(ffap)` , which also depends on `thingatpt`.
`ffap` seems to be more friendly than `thingatpt` because

- it adds `filepath` (url and etc) as "thing"
- it ties `filepath` to `find-file` (action)

We could do more if we can relates various "thing"s and actions conviniently.
That is why  I was motivated to create this package.

> It's your PR, so it's up to you. Please note that I am not a MELPA maintainer so these are merely my opinions.

Anyway, thank you. I will reopen this. When it comes to publish, please try it and tell me your feedback again! @alphapapa

**Pull request closed without merging**
