### PR TITLE
add baidu-translate

### PR DESCRIPTION
**Pull request by liShiZhensPi**
### Brief summary of what the package does

Translate the text you marked or the whole buffer using baidu-tranlsate api.

### Direct link to the package repository

https://github.com/liShiZhensPi/baidu-translate

### Your association with the package

I am the maintainer and contributor.

### Relevant communications with the upstream package maintainer

The package need the unicode-escape,i send email to him,but not get answer now.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
baidu-translate.el:47: First sentence should end with punctuation
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
No issues found.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems)
(The following assumes lexical binding is enabled)
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
No issues! 🎉

Automated sharp-quote suggestions for your consideration:

Miscellaneous and minor:
- baidu-translate.el#L7: Use `Version` instead of `Package-Version` (MELPA automatically adds `Package-Version`)
- baidu-translate.el#L38: Prefer `https` over `http` (if possible)

**Comment by liShiZhensPi** [comment]
checkdoc warning has been cleaned ,thank you!

**Comment by purcell** [comment]
Thanks, sent you a quick fix in https://github.com/liShiZhensPi/baidu-translate/pull/1, but I'll go ahead and merge this now in any case. Welcome to MELPA! :tada:

**Comment by liShiZhensPi** [comment]
Thank you, I feel very honored.

**Pull request merged**
