### PR TITLE
Add recipe for easy-hugo

### PR DESCRIPTION
**Pull request by masasam**
### Brief summary of what the package does

Emacs package for writing blogs made with hugo

### Direct link to the package repository

https://github.com/masasam/emacs-easy-hugo

### Your association with the package

I'm the author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- I suppose you should use `delete-directory` function instead of `rm -rf` for portability(like Windows etc)

**Comment by masasam** [comment]
Thank you for review.
I fixed it.

**Comment by purcell** [comment]
Thanks. Some feedback:

- The parent group of the `easy-hugo` custom group is currently defined as itself. Change it to a pre-existing group, e.g. `'tools`.
- `(when (null COND) BODY)` is much more clearly written as `(unless COND BODY)`
- Use `shell-quote-argument` when building file paths: if `easy-hugo-root` contains a space or quote, your current code will fail badly.
- Don't build file paths with `concat`. Use `expand-file-name` instead.

**Comment by masasam** [comment]
Thank you for review.
I fixed it.

**Comment by masasam** [comment]
- Don't build file paths with concat. Use expand-file-name instead.
I am sorry, I re-corrected this, so please review again

**Comment by purcell** [comment]
Thanks. I sent you a fix in https://github.com/masasam/emacs-easy-hugo/pull/1, mainly for missing `:group` declarations in your `defcustom` forms.

**Pull request merged**
