### PR TITLE
Add zoxide recipe

### PR DESCRIPTION
**Pull request by Vonfry**
### Brief summary of what the package does

Find files with [zoxide](https://github.com/ajeetdsouza/zoxide)

### Direct link to the package repository

https://gitlab.com/Vonfry/zoxide.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- I notice you didn't click the checkdoc or package-lint checkboxes, so you may have seen these:

### zoxide.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
zoxide.el:50: First line is not a complete sentence
Warning (emacs): 
zoxide.el:61: First line is not a complete sentence
Warning (emacs): 
zoxide.el:61: Argument `args' should appear (as ARGS) in the doc string
Warning (emacs): 
zoxide.el:73: Argument `path' should appear (as PATH) in the doc string
Warning (emacs): 
zoxide.el:81: Argument `path' should appear (as PATH) in the doc string
Warning (emacs): 
zoxide.el:89: Argument `query' should appear (as QUERY) in the doc string
Warning (emacs): 
zoxide.el:115: Argument `query' should appear (as QUERY) in the doc string
Warning (emacs): 
zoxide.el:139: First line should be capitalized
Warning (emacs): 
zoxide.el:146: First line should be capitalized
```
These are relatively minor but in the scheme of things should be very easy to fix.

package-lint (using version 20210528.2348):
```
3 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
1:0: warning: The package summary should start with an uppercase letter or a digit.
110:7: error: You should depend on (emacs "25.1") if you need `funcall-interactively'.
```

**Comment by Vonfry** [comment]
These are fixed now.

Currently, `package-lint-current-buffer` prints `No issues found` and
`checkdoc-current-buffer` is empty.

A log can be found [here](https://gitlab.com/Vonfry/zoxide.el/-/jobs/1379638540#L1284).

**Comment by riscy** [comment]
Thanks, that puts the checklist behind us.  Most everything else looks good, but I notice that the `args` sent to `zoxide-run` aren't escaped for characters that could interact with the shell (e.g. with `shell-quote-argument`).  It's rare, but users could run into troubles using this package against directories containing apostrophes, dollar signs, backticks, etc.  I also notice a very minor typo (zoxdie -> zoxide).

**Comment by Vonfry** [comment]
Thank for your advice. The typo problem has been fixed.

The escape with args is not necessary, because of call-process and
start-process are different from shell-command that the args are passed
to program directly through system call. Therefore, the escaped chars
will break the actions.

For example, run touch /tmp/\$a in shell, and
(with-temp-buffer (call-process "ls" nil t nil "-l" "/tmp/$a") (buffer-string))
will return what we expect.

**Comment by riscy** [comment]
> The escape with args is not necessary

You're absolutely right, apologies for the oversight.  This looks good to go.  And, welcome to MELPA. :)

**Pull request merged**
