### PR TITLE
add recipe for atomic-chrome

### PR DESCRIPTION
**Pull request by alpha22jp**
### Brief summary of what the package does

This is an Emacs version of [Atomic Chrome](https://atom.io/packages/atomic-chrome) which is an extension for Google Chrome browser that allows you to edit text areas of the browser in Emacs. It's similar to [Edit with Emacs](https://www.emacswiki.org/emacs/Edit_with_Emacs), but has some advantages as below with the help of websocket.

* The input on Emacs is reflected to the browser instantly and continuously.
* You can use both the browser and Emacs at the same time. They are updated to the same content bi-directionally.

### Direct link to the package repository

https://github.com/alpha22jp/atomic-chrome.git

### Your association with the package

I'm a maintainer of this package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- README says this package requires Emacs 24.4 or higher versions but there is no minimum Emacs version in Package-Requires
- You should name better package name, for example `chrome-edit` etc. I suppose **emacs** in package name makes no sense
- Is it necessary to call hook in minor-mode manually(I suppose hook functions are called two times) ? `define-minor-mode` macro is expanded with `run-hooks` code.

**Comment by purcell** [comment]
Agreed, this should almost certainly be called `atomic-chrome`.

Further feedback from me:
- You need a `defgroup` to define the parent group for all the `defcustom` items.
- Don't add advice to `save-buffers-kill-emacs` -- there's `kill-emacs-hook` for that

**Comment by alpha22jp** [comment]
Thanks for reviewing. I modified some points as below.

* Added emacs version dependency to Package-Requires.
* Renamed package name to "atomic-chrome".
* Removed unnecessary call of `run-hooks`.
* Added `defgroup` and set parent group to "applications".

> Don't add advice to `save-buffers-kill-emacs` -- there's `kill-emacs-hook` for that

I first tried to use `kill-emacs-hook`, but it didn't help me being prompted to kill the websocket server process. So I borrowed this idea from [edit-server](https://github.com/stsquad/emacs_chrome/blob/master/servers/edit-server.el) package. Could you tell me what is the proper way to do it?

**Comment by purcell** [comment]
Thanks!

> first tried to use kill-emacs-hook, but it didn't help me being prompted to kill the websocket server process. So I borrowed this idea from edit-server package. Could you tell me what is the proper way to do it?

Hmm. I'm surprised that didn't work. Not sure then, sorry!

**Pull request merged**
