### PR TITLE
Add 'mood-line' package

### PR DESCRIPTION
**Pull request by jessiehildebrandt**
### Brief summary of what the package does

mood-line is a minimal mode-line configuration that aims to replicate some of the features of the
doom-modeline package, but with zero dependencies and a minimal performance footprint.

### Direct link to the package repository

https://gitlab.com/jessieh/mood-line

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by jessiehildebrandt** [comment]
> This is an unofficial first pass review from a fellow contributor:
> 
>     * Package-lint:
>       ```
>       117:0: warning: Private functions generally should not be autoloaded.
>       127:0: warning: Private functions generally should not be autoloaded.
>       158:0: warning: Private functions generally should not be autoloaded.
>       ```
> 
>     * Byte-compiling:
>       ```
>       In mood-line-is-active:
>       mood-line.el:109:25:Warning: reference to free variable
>           ‘mood-line--current-window’
>       
>       In mood-line-segment-multiple-cursors:
>       mood-line.el:207:9:Warning: reference to free variable ‘multiple-cursors-mode’
>       
>       In end of data:
>       mood-line.el:302:1:Warning: the function ‘mc/num-cursors’ is not known to be
>           defined.
>       ```
> 
>     * I think `require`s are needed on:
>       
>       * flycheck
>       * multiple-cursors (for variable `multiple-cursors-mode`)
>       * anzu (for function `(anzu--update-mode-line)`)

Thank you for the feedback; I've applied corrections to address the linter's complaints about the autoloaded functions.

The package should not actually use the variables of the flycheck, mc, or anzu packages
if the respective package is not loaded, but I'm not entirely sure how to refactor the package to eliminate those warnings from the byte-compiler if that is necessary.

**Comment by tarsius** [comment]
> not entirely sure how to refactor the package to eliminate those warnings

You can use

```diff
-(foo)
+(and (fboundp 'foo) (foo))
```

**Comment by jessiehildebrandt** [comment]
> ```lisp
> (declare-function foo "foo")
> ```

Thank you, that seems to have quieted the byte-compiler. I've also applied this change to my other package and it helped there, as well.

**Comment by purcell** [comment]
Thanks! Notes:
- [`comment` might be a better face to inherit from here](https://gitlab.com/jessieh/mood-line/blob/02c6c457f0939a36af98247ebb40f36ed0cb2982/mood-line.el#L71)
- Why not call [this](https://gitlab.com/jessieh/mood-line/blob/02c6c457f0939a36af98247ebb40f36ed0cb2982/mood-line.el#L80) `mood-line-status-success` for consistency?
- A screenshot would be nice.
- I'd suggest converting `mood-line-activate` into a global `mood-line-mode` so that there's a way to toggle the behaviour off.
- That function (or mode) is the only thing that should be autoloaded.

Hope that helps!

**Comment by purcell** [comment]
I'll go ahead and merge this in the meantime, and you can address the above feedback at your leisure. Welcome to MELPA! :tada:

**Pull request merged**
