### PR TITLE
Add recipe for helm-system-packages

### PR DESCRIPTION
**Pull request by Ambrevar**
### Brief summary of what the package does

A Helm UI for your system package manager.  Awesome! :)

### Direct link to the package repository

https://github.com/emacs-helm/helm-system-packages

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [-] `M-x checkdoc` is happy with my docstrings
- [-] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

Since recently I can't seem to be able to install any of the recipes:

```
(wrong-type-argument arrayp nil)
  aref(nil 0)
  (package-version-join (aref pkg-info 0))
  (let* ((name (car archive-entry)) (pkg-info (cdr archive-entry)) (version (package-version-join (aref pkg-info 0))) (flavour (aref pkg-info 3))) (expand-file-name (format "%s-%s.%s" name version (if (eq flavour (quote single)) "el" "tar")) package-build-archive-dir))
  package-build--archive-file-name(nil)
  package-build--find-package-file("helm-system-packages")
  (package-install-file (package-build--find-package-file name))
  (progn (package-install-file (package-build--find-package-file name)))
  (if (yes-or-no-p "Install new package? ") (progn (package-install-file (package-build--find-package-file name))))
  (let ((name (file-name-nondirectory (buffer-file-name)))) (package-build-archive name) (package-build-dump-archive-contents) (let ((output-buffer-name "*package-build-result*")) (let* ((old-dir default-directory) (buf (save-current-buffer (set-buffer (get-buffer-create output-buffer-name)) (prog1 (current-buffer) (kill-all-local-variables) (setq default-directory old-dir) (setq buffer-read-only nil) (setq buffer-file-name nil) (setq buffer-undo-list t) (let ... ... ...)))) (standard-output buf)) (prog1 (progn (princ ";; Please check the following package descriptor.\n") (princ ";; If the correct package description or dependencies are missing,\n") (princ ";; then the source .el file is likely malformed, and should be fixed.\n") (pp (assoc (intern name) (package-build-archive-alist)))) (internal-temp-output-buffer-show buf))) (save-current-buffer (set-buffer output-buffer-name) (emacs-lisp-mode) (view-mode))) (if (yes-or-no-p "Install new package? ") (progn (package-install-file (package-build--find-package-file name)))))
  package-build-current-recipe()
  funcall-interactively(package-build-current-recipe)
  call-interactively(package-build-current-recipe nil nil)
  command-execute(package-build-current-recipe)
```

Not sure what's happening.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Looks useful. Quick notes:
- [Typo: excplitly](https://github.com/emacs-helm/helm-system-packages/blob/1915f3f81aeebd460a729c87ed317218e3bf9063/helm-system-packages.el#L40)
- Don't [define new faces using](https://github.com/emacs-helm/helm-system-packages/blob/1915f3f81aeebd460a729c87ed317218e3bf9063/helm-system-packages.el#L39) only foreground or background colour. They are guaranteed to look bad for many users. Instead, either `:inherit` a built-in face (preferred), or provide both `dark` and `light` variants.
- Re. [this code](https://github.com/emacs-helm/helm-system-packages/blob/1915f3f81aeebd460a729c87ed317218e3bf9063/helm-system-packages.el#L188-L190), I think `(filter 'executable-find '("emerge" "dpkg" "pacman"))` would do the trick much more cleanly.

**Comment by Ambrevar** [comment]
* Typo: fixed.
* Faces: fixed.
* filter: I guess you meant `seq-filter`?  Anyways, fixed :)

**Comment by purcell** [comment]
> filter: I guess you meant seq-filter? Anyways, fixed :)

Ah, no, sorry. I think I probably meant `cl-filter`. `seq-filter` is fine (great, even), but you'd need to declare a package depedency on the version of `seq` currently in ELPA, because it's not included in Emacs 24.4.

**Comment by Ambrevar** [comment]
Done, let me know if this is not the proper way to do it.

**Comment by purcell** [comment]
LGTM, thanks.

**Comment by Ambrevar** [comment]
Thank you very much!

**Pull request merged**
