### PR TITLE
Add keg recipe

### PR DESCRIPTION
**Pull request by conao3**
### Brief summary of what the package does

Modern Elisp package development system.
Keg is Elisp only project, alternative `cask`.

### Direct link to the package repository

https://github.com/conao3/keg.el

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
This package is my solution on #6918

**Comment by akirak** [comment]
@conao3 I know you are good at writing Emacs Lisp, and this project would be yet another example for it. However, there are already many solutions like this, including emake, makel, makem, etc. What are the advantages of your solution over [makem.sh](https://github.com/alphapapa/makem.sh) and [eldev](https://github.com/doublep/eldev), for example?

**Comment by conao3** [comment]
I like `cask`. However, because it has Python code, it is unlikely that it will be included in GNU.
I realized that I (we, Elisp community) don't want a lint tool, I want a `cask` that's **easier to use**, **faster**, and doesn't have an **outdated code**.
There are some features that have not been implemented yet, but the main features of `cask` have already been implemented.

I'm developing this package as a just successor to `cask`, so it doesn't conflict with `makem` or `eldev`.
It's not as simple as `makem`, and I can't write a complex `Eldev` file like `eldev`.
However, I think it's a project that users from `cask` can migrate to without stress and it's easy for Elisp developers to see what it doing.

**Comment by riscy** [comment]
Neat. :)  Real quick pass before a deeper look.

- keg.el#L150: It's safer to sharp-quote function names; use `#'`
- keg.el#L646: You can use `not` or `null`

**Comment by conao3** [comment]
Thanks, @riscy. I fixed.

**Comment by akirak** [comment]
@conao3 
Thanks, it looks good. Indeed, it is simpler if it is written purely in Emacs Lisp. I didn't know of commander.el, which looks useful.

Your project still contains Cask and Makefile, and apparently you are using them in GitHub Actions. If it's a replacement for Cask, could you show me a working example without Cask?

**Comment by conao3** [comment]
Keg works like this with GitHub Actions, using [setup-keg](https://github.com/marketplace/actions/setup-keg).
https://github.com/conao3/keg.el/actions/runs/121064969

I use Makefile just as a shorthand, but of course, it is possible to directly run without it if the user remembers the `keg` commands.

**Comment by conao3** [comment]
Thanks!

**Pull request merged**
