### PR TITLE
Add recipe for consult-recoll

### PR DESCRIPTION
**Pull request by jaor**
-------

### Brief summary of what the package does

Perform recoll queries using consult.

### Direct link to the package repository

https://codeberg.org/jao/consult-recoll

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

*None needed*

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- looks good to me, but I notice it relies on functions that are not part of the public interface of `consult` (`consult--read`, `consult--async-command`, etc.)  Maybe @minad would be open to making these part of the public API so that this dependency is more visible?

The minor stuff:
- consult-recoll.el#L104: This double negation can be collapsed (`not` aliases `null`)
- custumization -> customization
-

**Comment by jaor** [comment]
On Sun, Mar 21 2021, Chris Rayner wrote:

> Thanks for this -- looks good to me, but I notice it relies on
> functions that are not part of the public interface of consult
> (consult--read, consult--async-command, etc.) Maybe @minad would be
> open to making these part of the public API so that this dependency is
> more visible?

we've discussed that a bit in the context of consult-spotify: the short
answer is that, for now, those are considered by @minad as the consult
API for developers of consult extensions.

> The minor stuff:
>
>   • consult-recoll.el#L104: This double negation can be collapsed (not aliases null)

indeed. i'm now using #'identity instead.

>   • custumization -> customization

oops, fixed.

**Comment by minad** [comment]
@riscy

> Maybe @minad would be open to making these part of the public API so that this dependency is more visible?

No, I am not yet willing to do that. I have discussed this a few time and in the long term it is likely that I will make parts of the API public. I have not planned this yet, but recently Consult has stabilized if you look at the history/changelog. 

There are multiple reasons for the current approach:

* I can move around things a bit more freely during the early phase of the package. The only downside is that I have to notify the authors of the supplementary packages, or they monitor Consult closely themselves, as @jaor is doing. Obviously this is not a long term solution, but for now it works like this.
* I want to nudge the development of new packages a bit in a certain direction and see how the ecosystem develops. The whole point of the Selectrum/Consult/Embark/Marginalia/Orderless set of packages is that the components are loosely coupled and that packages mostly rely on standard APIs. If new packages rely on `completing-read`, there is no reason to depend on Consult and we end up with more flexibility overall. I have seen package prototypes where where Consult or Marginalia was used simply for the fact that they provide a slightly more convenient API compared to `completing-read`, despite not using any of the unique `consult--read` features (Luckily I could convince them to not depend on Consult, but use `completing-read` instead). Similarly I have seen usage of the`ivy-read` and `helm` APIs, despite not using any of the advanced features.

You may have seen that Selectrum recently deprecated its public API `selectrum-read` in favor of `completing-read`, such that Selectrum does not provide a main public entry point anymore. There is still `selectrum--read` internally, but there is simply no reason to use this function from an external package. So ideally we should never see `selectrum-xyz` (or `icomplete-xyz`) packages, which consume package specific APIs.

However there is also need for more advanced features (async, preview, etc) as provided by Consult and its `consult--read` API. The packages by @jaor use the async functionality and in this case the usage of the API is justified. In the end it would be better if such packages could rely on a stable and public API.

It may be a good idea if you as MELPA maintainers also look if the usage of `consult--read`, `ivy-read`, `helm` etc is really necessary in new package or if `completing-read` is sufficient. When people make new proposals for `consult-xyz` commands or new Consult-related packages, I usually look if a corresponding ivy/helm package already exists and if this package is really necessarily an ivy/helm package. Often it is possible to create a version which does not rely on ivy/helm and just consumes the standard API. See for example https://github.com/d12frosted/flyspell-correct which provides a basic package based on `completing-read` or the recent efforts to port https://github.com/tmalsburg/helm-bibtex to `completing-read`, see https://github.com/bdarcus/bibtex-actions.

Does this sound reasonable?

**Comment by riscy** [comment]
> It may be a good idea if you as MELPA maintainers also look if the usage of consult--read, ivy-read, helm etc is really necessary in new package or if completing-read is sufficient.

Thanks for that detailed reply.  This is something I used to be better about looking out for (ido included!), so I also appreciate the reminder.  I was actually ignorant of the fact that `consult` sits in this subcategory of packages, but I've made a mental note now.

**Pull request merged**
