### PR TITLE
Add org-tagged package

### PR DESCRIPTION
**Pull request by gizmomogwai**
### Brief summary of what the package does

Org tagged allows to create dynamic blocks showing a table of tasks based on tags.

### Direct link to the package repository

https://github.com/gizmomogwai/org-tagged

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback. I STILL HAVE SOME ISSUES ON THE org-tagged.el FILE, BUT I THINK THOSE ARE KIND OF FALSE POSITIVES
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -- including some of what you listed as false positives:

`org-tagged.el` with byte-compile using Emacs 28.1:
```
org-tagged.el:85:8: Warning: docstring wider than 80 characters
In org-tagged--show-configure-buffer:
org-tagged.el:96:41: Warning: Unused lexical variable `columns-widget'
org-tagged.el:98:39: Warning: Unused lexical variable `match-widget'
org-tagged.el:100:55: Warning: Unused lexical variable
    `truncation-string-widget'
org-tagged.el:160:33: Warning: reference to free variable `preview'
org-tagged.el:143:23: Warning: assignment to free variable `preview'
In end of data:
org-tagged.el:87:4: Warning: the function `widget-value-set' is not known to
    be defined.
```
The "unused lexical variable" issues seem to stem from these variables being set, but never being applied; maybe you can help me in figuring out where these are intended to be used so that we can fix those warnings?

`org-tagged.el` with package-lint 20220913.1226:
```
1 issue found:
102:7: warning: Closing parens should not be wrapped onto new lines.
```
You're using nonstandard formatting in this very small case which, while not strictly wrong, is not in the community style; so not a false positive. :)

`org-tagged.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- org-tagged.el#L9: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
```

Package and license:
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to org-tagged.el

**Comment by gizmomogwai** [comment]
Thanks for having a look!
I did not know about `melpazoid` ... nice, although i had to apply the patch from issue https://github.com/riscy/melpazoid/issues/17 to get it running locally.

I fixed most of the warnings now, but still do not understand:
```
8:23: error: Package s is not installable.
8:36: error: Package dash is not installable.
8:67: error: Package org is not installable.
```
Could you help me out with that?

**Comment by riscy** [comment]
> Could you help me out with that [package-lint warning]?

I've got some idea what that is -- I suspect a bug in melpazoid when running it locally, where `package-initialize` hasn't been run at the correct point.  Something for me to take a look at.

Nothing for you to worry about, though -- this is the only one remaining:
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to org-tagged.el

**Comment by gizmomogwai** [comment]
Thanks for the clarification.
I added not `;; SPDX-License-Identifier: MIT` after homepage ... hope that helps.

**Comment by gizmomogwai** [comment]
Hi @riscy , I hope now everything is in place :)

**Comment by riscy** [comment]
Apologies for the delay! I'm mostly only here on weekends.  Looks good here.

**Comment by gizmomogwai** [comment]
> Apologies for the delay! I'm mostly only here on weekends. Looks good here.

Thanks a lot. I did not want to harass you but just thought it might be worth a reminder :)
Good, that you have clear boundaries in place ... 
Thanks for merging!

**Pull request merged**
