### PR TITLE
recipes: add websearch

### PR DESCRIPTION
**Pull request by xgqt**
Signed-off-by: Maciej Barć <xgqt@gentoo.org>

### Brief summary of what the package does

Query search engines from Emacs.

### Direct link to the package repository

https://gitlab.com/xgqt/emacs-websearch

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

https://gitlab.com/xgqt/emacs-websearch/-/issues/

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Review by riscy — COMMENTED** [review]
Thanks for this.  Quick first pass --

Have you had a chance to look at and compare to https://melpa.org/#/engine-mode ?  MELPA is primarily aiming to index novel/innovative packages that don't exist in another established form.

On the whole the code itself looks good,  but I think there is excessive vertical space (e.g. run `M-: (lm-commentary)` on search.engine.el).

Also -- and I admit this can be a matter of opinion -- this could all just go in one file.  There are effectively less than 200 nonempty lines of code across the whole package, so I suspect some horizontal/vertical compaction would help maintainability and make it easier to read/review the code.

**Comment by xgqt** [comment]
@riscy I think engine-mode and search-engine can co-exist and do not share so much as one may think, for example engine-mode does not pre-configure any engines.

**Comment by riscy** [comment]
This looks good to merge to me, but I have some higher-level comments to make (let me know what you think) before merging:

- I think the term "search engine" has grown recently to encompass more than just Google, Bing, etc.  For example you'd call a piece of software like "Lucene" a search engine too.  I wonder if renaming this package to "web-search" or even just "websearch" would get the point across more clearly (oh, it's for searching the _web_).  As bonuses, you would then have the function "websearch" in your namespace, which is a verb, and much more natural to M-x than "search-engine", and avoid awkward naming like `"*Search Engine Engines*"`
- This is minor, and nobody will see this unless they look at the code, but when you have a comment like `WORDS-STRING is the search term."` I figure it's time to rename the variable WORD-STRING to SEARCH-TERM -- the less unique vocabulary you have in your code for referring to the same concept, the better

**Comment by xgqt** [comment]
> This looks good to merge to me, but I have some higher-level comments to make (let me know what you think) before merging:
> 
>     * I think the term "search engine" has grown recently to encompass more than just Google, Bing, etc.  For example you'd call a piece of software like "Lucene" a search engine too.  I wonder if renaming this package to "web-search" or even just "websearch" would get the point across more clearly (oh, it's for searching the _web_).  As bonuses, you would then have the function "websearch" in your namespace, which is a verb, and much more natural to M-x than "search-engine", and avoid awkward naming like `"*Search Engine Engines*"`
> 
>     * This is minor, and nobody will see this unless they look at the code, but when you have a comment like `WORDS-STRING is the search term."` I figure it's time to rename the variable WORD-STRING to SEARCH-TERM -- the less unique vocabulary you have in your code for referring to the same concept, the better

Those are very good suggestions, I will do that.

**Comment by xgqt** [comment]
renamed + fixes

**Comment by riscy** [comment]
Thanks for accommodating. :)  Merging this.

**Pull request merged**
