### PR TITLE
Add recipe for smmry

### PR DESCRIPTION
**Pull request by microamp**
### Brief summary of what the package does

A simple client that talks to [SMMRY](http://smmry.com/) [API](http://smmry.com/api)

### Direct link to the package repository

https://github.com/microamp/smmry.el

### Your association with the package

I'm the maintainer of the package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- https://github.com/microamp/smmry.el/blob/1db45082eea34efbab7120e3b03ca060068f3504/smmry.el#L125 code is always evaluated and this command always failed
- `string-trim` is defined at subr-x.el but this packaged does not load it. And subr-x is introduced at Emacs 24.4 but this packages does not require minimum Emacs version
- There are some byte-compile warnings about using free variables

**Comment by microamp** [comment]
* Oops. It must have been a last minute `magit-discard` action I did. Things got out of order. Thanks for spotting.
* I removed the `subr-x` dependency after verifying that it wasn't actually needed. The package still requires `json` though which was introduced in Emacs 23.1. So I added `Package-Requires: ((emacs "23.1"))`.
* Byte-compile warnings should not be there anymore.

Thanks for reviewing again. Much appreciated.

**Comment by microamp** [comment]
Here is the PR addressing the issues reported above: https://github.com/microamp/smmry.el/pull/2

**Comment by purcell** [comment]
Declaring a dependency on `((emacs "23.1"))` is actually counterproductive, because `package.el` for Emacs 23.x does not know about the `emacs` pseudopackage, so this clause actually makes the package uninstallable on Emacs < 24. :-)

**Comment by microamp** [comment]
I see. Thanks for the info. TIL. :)

It's been removed from `Package-Requires`.

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
