### PR TITLE
Add aangit.

### PR DESCRIPTION
**Pull request by stephenwithav**
Aangit is a Magit-like interface for quckly scaffolding new Angular apps.

https://github.com/stephenwithav/aangit

I'm the creater/maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

`aangit.el` with byte-compile using Emacs 29.1:

```
In end of data:
aangit.el:21:45: Warning: the function `dired-read-dir-and-switches' is not known to be defined.
```

`aangit.el` with checkdoc (0.6.2)

```
aangit.el:11: Name emacs should appear capitalized as Emacs
aangit.el:8: Name emacs should appear capitalized as Emacs
```

`aangit.el` with package-lint (20230905.629)

```
2 issues found:

6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
21:25: error: You should depend on (emacs "29.1") if you need `string-split'.
```

Package and license:

- MIT


You would probably want to move `;;; Commentary:` under package metada. 🤔

**Comment by stephenwithav** [comment]
Thank you for the comments.

I added the dependencies on 29.1 and dired, as well as capitalizing Emacs.  tools seems like the only appropriate standard keyword, so I kept angular and added it.

I am open to further suggestions.

**Comment by riscy** [comment]
Thanks both!  Unfortunately Emacs should *not* be capitalized in your `Package-Requires` line.  A couple other notes:

- Prefer equivalent recipe: `(aangit :repo "stephenwithav/aangit" :fetcher github)`
- aangit.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by stephenwithav** [comment]
Thank you for the feedback, @riscy.

I have a few other packages in mind once I learn this new MELPA recipe flow. :)

**Comment by riscy** [comment]
Thanks, looks good.  And, welcome to MELPA. :)

**Comment by stephenwithav** [comment]
Life goal unlocked.  Thanks!

**Pull request merged**
