### PR TITLE
Add recipe for elfeed-curate

### PR DESCRIPTION
**Pull request by rnadler**
### Brief summary of what the package does

elfeed-curate is an add-on to the Elfeed package for curating RSS feeds

### Direct link to the package repository

https://github.com/rnadler/elfeed-curate

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`elfeed-curate.el` with byte-compile using Emacs 28.1:
```
elfeed-curate.el:88:1: Warning: custom-declare-variable
    `elfeed-curate-org-options' docstring wider than 80 characters
elfeed-curate.el:98:1: Warning: custom-declare-variable
    `elfeed-curate-show-group-count' docstring wider than 80 characters
elfeed-curate.el:126:1: Warning: custom-declare-variable
    `elfeed-curate-hugo-section' docstring wider than 80 characters
In elfeed-curate-concat-other-groups:
elfeed-curate.el:231:8: Warning: docstring wider than 80 characters
In elfeed-curate-toggle-star:
elfeed-curate.el:444:8: Warning: docstring wider than 80 characters
In end of data:
elfeed-curate.el:366:6: Warning: the function `hide-mode-line-mode' is not
    known to be defined.
```

`elfeed-curate.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- elfeed-curate.el#L340: It's safer to sharp-quote function names; use `#'`
- elfeed-curate.el#L404: It's safer to sharp-quote function names; use `#'`
- elfeed-curate.el#L206: Consider using %F instead of %Y-%m-%d in time strings
```

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

**Comment by rnadler** [comment]
Changes have been pushed.
Let me know if there's anything else that needs to be addressed.
Thanks!

**Comment by riscy** [comment]
This looks good to me.  A couple more quick comments --

In `elfeed-curate--open-in-external-app`:
- One minor suggestion I have is that instead of using backticks for the acknowledgment URL in  use the `<` and `>` which seems to be more common across elisp files (back/front quotes are usually for quoting symbols in such a way that creates hyperlinks in the help), e.g. write `Simplified version of <http://xahlee.info/emacs/emacs/emacs_dired_open_file_in_ext_apps.html>"`
- This function uses variable names (e.g. `xoutBuf`) that should follow the community standards, e.g. `x-out-buf` (where I guess the `x` here is short for `xah`).  I think this is the overall largest issue right now, because I dislike setting a precedent by merging packages that have this discrepancy
- The name of the temporary buffer (`xah open in external app`) should probably also be renamed to match your package, rather than the source material you used

In `elfeed-curate-reconcile-annotations`:
- Note that `"Annotation tags reconciled for %d entries: %d added, %d removed, %d total annoations"` is already over 80 characters long (without interpolation!) and I think there will still be some users out there working with 80-char frames.  I always strive for compatibility with the widest audience, so shortening this (perhaps by removing that last word, even) could help a few users

**Comment by rnadler** [comment]
Thanks for the feedback. All of the suggestions have been addressed.

**Comment by riscy** [comment]
Thanks - merging this!

**Comment by riscy** [comment]
And, welcome to MELPA. :)

**Comment by rnadler** [comment]
@riscy Thanks!
QQ: How long does it take before the package will become available?

**Comment by riscy** [comment]
Looks like it's up now: https://melpa.org/#/elfeed-curate

**Pull request merged**
