### PR TITLE
Add counsel-jq recipe

### PR DESCRIPTION
**Pull request by munen**
### Brief summary of what the package does

With `counsel-jq`, you can quickly test queries and traverse a complex JSON structure whilst having live feedback.

### Direct link to the package repository

https://github.com/200ok-ch/counsel-jq

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
Nifty "fallout" from Organice, I suspect.  :)

**Comment by munen** [comment]
@alphapapa Partially^^ I've been meaning to write this package for a longer time, actually. We've been fans of jq for a longer time now[1] and integrating it with counsel just makes sense to turbo-charge it. Finally, I got around to doing it(;

1. https://200ok.ch/posts/jq-my-new-favorite-tool-to-work-with-json-on-the-command-line.html

**Comment by alphapapa** [comment]
Cool.  That might even be a feature that would draw in new Emacs users!

**Comment by munen** [comment]
I thought so, too.

With a little bit of documentation in the README on how to setup ivy with counsel-jq in the README this could be easily used from an otherwise vanilla Emacs without needing to know too many intrinsics of Emacs itself.

Happy to hear this hunch confirmed by someone else(;

**Comment by riscy** [comment]
Very cool.  This looks ready to merge, but here are a couple quick comments:

This line:
```
      ;; This expression uses the most recent other buffer (see
```
feels like it could [also] be part of the docstring, to tell users (and not only people looking at the source) about the behavior.

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
1 issue found:

1:0: warning: The package summary should not end with a period.
```

Should `counsel-jq` be autoloaded, as the main entrypoint to the package?

**Comment by munen** [comment]
Hi @riscy

Thank you for your feedback! I made the proposed changes where applicable. Here's feedback to your comment:

> This line:
> 
>       `;; This expression uses the most recent other buffer (see`
> 
> feels like it could [also] be part of the docstring, to tell users (and not only people looking at the source) about the behavior.

You're right, this behavior should be visible to the users and not just people reading the code. Since it's the main behavior (and  That's why I had this sentence in the top level README:

> Whenever you're happy, hit =RET= and the results will be displayed to you in the buffer =*jq-json*=.

Adding it to the docstring of the interactive function `counsel-jq` is a good idea! Hence, I did that.

> M-x package-lint-current-buffer (using version 20191124.132):
> 
> 1 issue found:
> 
> 1:0: warning: The package summary should not end with a period.

Thanks! I was the most recent version of package-lint when I created the PR which was `package-lint-20191103.1154`. Thanks for continuing to push the capabilities of that package! :pray: I just updated and made sure that `package-lint-current-buffer` has no issues.

> Should counsel-jq be autoloaded, as the main entrypoint to the package?

Very good point! Done(;

Thanks for your time and feedback, it's much appreciated! :pray: 

I hope `counsel-jq` is good to merge, now. If you have further input, I'll happily iterate on it, of course^^

**Comment by riscy** [comment]
> Thanks for continuing to push the capabilities of that package!

package-lint is all purcell's hard work. :)

I just realized you might consider adding a `(require 'swiper)` (just in case), although `ivy-read` is autoloaded so the compiler finds it without issue.  Not a blocker.

Thanks a lot for this.  And, welcome to MELPA!

**Comment by munen** [comment]
@riscy Thank you very much for pulling it in, that makes my day! :pray: 

> I just realized you might consider adding a (require 'swiper) (just in case), although ivy-read is autoloaded so the compiler finds it without issue. Not a blocker.

I did include it, so it'll be in the next build. 
NB: For that to lint correctly, I had to change the `Package-Requires` dependency to `ivy` which makes sense, because swiper has a dependency on ivy.

**Pull request merged**
