### PR TITLE
Adding ja-network to elpa repository

### PR DESCRIPTION
**Pull request by jamiguet**
### Provides hooks for handling intermittent network connectivity

Defines network-up-hook and network-down-hook which get invoked when no specified interfaces are add up on the host. It also provides a have-network-p which returns nil if none of the listed interfaces are up. 

The package uses customised variables to enable the same configuration to run on several machines.

### Direct link to the package repository

https://github.com/jamiguet/ja-network

### Your association with the package

I am the creator and maintainer.

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- You're defining a number of symbols (e.g. network-up-hook) without the proper prefix for your package. `package-lint` should have warned you about this.
- Use `let` for [this code](eac5567e2a47be1272ed73b19c43025a457fa416) - defining variables inside a block isn't a thing in elisp. :-)
- You've got hooks, and you've got a way of enabling functionality... what you've got is a global minor mode, so turn it into one, e.g. `network-monitor-mode`. If you believe this is useful to other people, why publish with the `ja-` prefix?
- [Typos](https://github.com/jamiguet/ja-network/blob/bc027a993020e1b3771950d3a784686d21737447/ja-network.el#L48)
- Your `Commentary` section is malformatted: too many `;;;`.
- Use something like `cl-find` [here](https://github.com/jamiguet/ja-network/blob/bc027a993020e1b3771950d3a784686d21737447/ja-network.el#L69-L75)
- `network-interface-list` isn't a function in my Emacs... where is that coming from?

Hope that helps!x

**Comment by jamiguet** [comment]
Thanks a lot for your feedback its my first contribution so it is very welcome.
I reply here to the simple comments.
I will re-factor the code to turn it into a global-minor-mode. So please bear with me as it may take a little bit of time to do so.

*  package-lint-20171006.1846 reports No issues except the snap-shot version for org.
* Using let already in the first fix
* I read about them, I agree its much cleaner. I will re-factor to user a global minor, please bear with me
* Typos, searched and destroyed ;)
* Commentary fixed, also a better suited commentary text.
* Using cl-find as advised
* network-interface-list is a built-in function in `C source code'. As per what apropos says on Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.7) of 2017-02-10 on lcy01-09, modified by Debian


Thanks for the feedback once again I'll get cracking to fix it.

**Comment by purcell** [comment]
> network-interface-list is a built-in function in `C source code'.

Ah yes, found it now - sorry for the noise! :-)

**Comment by jamiguet** [comment]
As part of packaging the functionality as a global-minor-mode it will change name to network-mode.
Closing pull request.

**Comment by purcell** [comment]
`network-mode` is a bit vague. Can I suggest `network-watch` instead? `-mode` suffixes are generally only advisable in package names when a major mode is provided.

**Comment by jamiguet** [comment]
Will adjust accordingly.
Thanks for the quick feedback.

**Pull request closed without merging**
