### PR TITLE
Add org-ivy-search

### PR DESCRIPTION
**Pull request by beacoder**
### Brief summary of what the package does

Poor man's full-text search engine over org files powered by ivy.

### Direct link to the package repository

https://github.com/beacoder/org-ivy-search

### Your association with the package

author

### Relevant communications with the upstream package maintainer

N/A

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I had a quick look at the implementation and this looks good.

I'm not much of an org power user, but have you checked out https://melpa.org/#/org-ql and https://melpa.org/#/org-seek in case there's some overlap?  I also think you should include the keyword "ivy" (either in your package name or in the summary which appears as the first line of your elisp file); some users might be using a different completion manager and won't know that this is incompatible with their workflow until installing.

In the meantime, quick first pass --

`org-searcher.el` with byte-compile using Emacs 28.1:
```
org-searcher.el:125:17: Warning: assignment to free variable `files'
org-searcher.el:135:34: Warning: reference to free variable `files'
org-searcher.el:182:19: Warning: assignment to free variable `rtnall'
org-searcher.el:180:39: Warning: assignment to free variable `index'
org-searcher.el:174:67: Warning: assignment to free variable `file'
org-searcher.el:178:33: Warning: assignment to free variable `ee'
org-searcher.el:138:16: Warning: reference to free variable `file'
org-searcher.el:170:34: Warning: assignment to free variable `beg'
org-searcher.el:173:73: Warning: assignment to free variable `beg1'
org-searcher.el:179:38: Warning: assignment to free variable `end'
org-searcher.el:174:92: Warning: reference to free variable `beg'
org-searcher.el:173:42: Warning: reference to free variable `beg1'
org-searcher.el:176:41: Warning: assignment to free variable `txt'
org-searcher.el:176:41: Warning: reference to free variable `index'
org-searcher.el:178:29: Warning: reference to free variable `txt'
org-searcher.el:181:33: Warning: reference to free variable `ee'
org-searcher.el:181:33: Warning: reference to free variable `end'
org-searcher.el:182:41: Warning: assignment to free variable `rtn'
org-searcher.el:183:11: Warning: reference to free variable `rtnall'
org-searcher.el:183:11: Warning: reference to free variable `rtn'
```

**Comment by beacoder** [comment]
Hi,

I've have a look over https://melpa.org/#/org-ql, there's some similarities between these two, however org-ql is more like a full bloated and complicated one, while mine is like simple and solely purpose is to do on the fly full text search.

and btw, I've update the package from org-search to org-ivy-search.
thanks.

**Comment by riscy** [comment]
> org-ql is more like a full bloated and complicated one

There is (I think?) a helm-specific package here https://melpa.org/#/helm-org-ql that is less complicated, only using org-ql as a well-established dependency.  Personally I think it's a good idea to do what you can to complement the existing ecosystem (and to list them in your README as a favor to users), but if you're heading in a different direction then that's okay.

On that topic - if your goal is a very simple/lightweight package, I'd recommend (but not insist on) stripping superfluous dependencies like beacon.  You could instead call `run-hooks` and let users add `beacon-blink` to the list of hooks when visiting agendas if they want visual indicators, or you could check out the builtin `pulse-momentary-highlight-region`.

One more thing I notice is you have a license clash.  The repo is MIT licensed, but org-ivy-search.el has GPL boilerplate.

**Comment by beacoder** [comment]
I think I'm inclined to keep beacon in there, as for helm-org-ql, still it looked complicated to me though.

for the license part, I will remove the GPL license indication.

**Comment by riscy** [comment]
Sounds good to me - and thank you for your patience and for looking into org-ql.  I'll wait for you to confirm that the licenses on the repo vs. the source file align as above.

**Comment by beacoder** [comment]
thanks, I just changed license to GPLv3 for both repo and source code.

**Comment by riscy** [comment]
Thanks!  Merging.  There's a very minor checkdoc, just fyi:

`org-ivy-search.el` with checkdoc 0.6.2:
```
org-ivy-search.el:36: White space found at end of line
```

**Comment by beacoder** [comment]
thanks.

**Pull request merged**
