### PR TITLE
Add recipe for cape

### PR DESCRIPTION
**Pull request by minad**
### Brief summary of what the package does

The cape package provides a bunch of Completion At Point Extensions. It is basically a gap filler since a lot of backend development happened in the form of Company backends. Unfortunately these Company backends do not work with my Corfu completion UI.

### Direct link to the package repository

https://github.com/minad/cape

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks!  Looks handy.

Repeating previous advice I've seen here in the past, it may be simpler to just `(require 'ispell)` instead of putting `ispell-lookup-words` in an autoload.  It might be very rare, but someone might end up inadvertently depending on the presence of this autoload in their config, leading to breakage if they ever remove your package.  Hyrum's law, I guess.

As an alternative, I remember reading in the Emacs lisp manual that it's perfectly fine to put a `require` inside a function definition to avoid expensive dependencies, although you'd have to combine that with a `declare-function` in this case to pacify the byte-compiler.

Other than that issue, this is a quick merge.

**Comment by minad** [comment]
> Repeating previous advice I've seen here in the past, it may be simpler
> to just |(require 'ispell)| instead of putting |ispell-lookup-words| in
> an autoload. It might be very rare, but someone might end up
> inadvertently depending on the presence of this autoload in their
> config, leading to breakage if they ever remove your package. Hyrum's
> law, I guess.

Yes, as a general guideline, requiring at the toplevel is better.
However this impedes lazy loadings, therefore I went with the autoload.

There are not that many alternatives - each with their own own downsides:

1. Top-level require (downside: lazy loading)
2. Top-level autoload (downside: rare problem if a user depends on the
autoload, as you pointed out.)
3. Require inside the functions (downside: you need the additional
declare-function, require happens during the control flow instead of
implicitly.)

> As an alternative, I remember reading in the Emacs lisp manual that it's
> perfectly fine to put a |require| inside a function definition to avoid
> expensive dependencies, although you'd have to combine that with a
> |declare-function| in this case to pacify the byte-compiler.

You are probably right that require inside the function is the best
option. In all my other packages I used the top-level autoload style,
since I consider the downside of the toplevel autoload minor. Therefore
I am also not too fond of changing this now, since this would mean that
I should change all my other packages too. ;)

> Other than that issue, this is a quick merge.

Thanks!

**Comment by minad** [comment]
Okay, I went with the manual require for both ispell and dabbrev now: https://github.com/minad/cape/commit/ae136b6ba4db0dbc612897751eacfa4df7f8b725. It is a bit ugly and not very robust unfortunately. I can adjust this in the future if problems occur. The cleanest long term solution would be to split the library into multiple files cape-ispell.el and cape-dabbrev.el. Then I can use toplevel requires and lazy loading is still intact. I will probably do this at some point later. For now the current version should be good enough. My goal here is to roll out the additional capfs to users of my Corfu package, which is an alternative to Company. Unfortunately it is lacking those backends, since they are missing upstream.

**Comment by riscy** [comment]
Yeah, these are tricky to sort out.  Thanks a ton for the thoughtful responses -- as well as for being willing to adjust.

**Pull request merged**
