### PR TITLE
Add create-link recipe

### PR DESCRIPTION
**Pull request by kijimaD**
### Brief summary of what the package does

A package to generate easily format links on browser(eww, w3m).

If you at Google page, `M-x create-link` save below:
- `<a href="https://www.google.com/">Google</a>`(html)
- `[Google](https://www.google.com/)`(markdown)
- `[https://www.google.com/ Google]`(wiki)

It would be very useful to be able to get these named links easily!

### Direct link to the package repository

https://github.com/kijimaD/create-link

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Looks like this needs a `Package-Requires` on request.  In addition, here's a quick first pass:

### create-link.el ###

byte-compile (using Emacs 27.1):
```
create-link.el:171:37:Warning: reference to free variable `eww-data'
create-link.el:176:24:Warning: reference to free variable `w3m-current-url'
In end of data:
create-link.el:193:1:Warning: the following functions are not known to be
    defined: eww-current-url, w3m-current-title
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210511.2055):
```
1 issue found:
143:19: warning: Closing parens should not be wrapped onto new lines.
```

**Comment by kijimaD** [comment]
@riscy
Thank you. I fixed and confirmed it!

>Looks like this needs a Package-Requires on request.

Added! ✔

byte-compile → ✔
check-doc → ✔
package-lint → ✔

**Comment by riscy** [comment]
Sorry, I forgot that w3m wasn't bundled with Emacs as well -- I think we also needs a `Package-Requires` on w3m, and then everything checks out cleanly.  

As an aside, this looks like a useful package.

**Comment by kijimaD** [comment]
I see👍
I added w3m to `Package-Requires`.
https://github.com/kijimaD/create-link/pull/23/files

**Comment by riscy** [comment]
This looks good to merge.  One last comment I have is that the `request` dependency seems quite heavy for something that just creates links, and you could potentially work around this using builtins.  This might not be the best solution but here's an example:
```
(let* ((buf (url-retrieve-synchronously url))
       (contents
        (with-current-buffer buf (buffer-substring (point-min) (point-max)))))
  (kill-buffer buf)
  contents)
```

**Comment by riscy** [comment]
Ha, and I guess w3m (which I suggested you add..!) is a heavy dependency too.  I won't block this any longer, but folks (like me) who try to keep their Emacs instance very lightweight might shy away from this because of the dependency weight.

**Comment by kijimaD** [comment]
Riscy, thank you for your review!👍 I'll check it!

**Pull request merged**
