### PR TITLE
add recipe for seqel

### PR DESCRIPTION
**Pull request by RNAer**
### Brief summary of what the package does

This package edits and visualize biological sequences including DNA, RNA, and proteins. It supports Fasta and Genbank file formats.

### Direct link to the package repository

https://github.com/RNAer/seqel

### Your association with the package

Developer/Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by lassik** [comment]
Cool to do bioinformatics in Emacs!

MELPA packages typically have a common prefix for all variables and functions. For example, in a `seqel` package, all variable and function names should start with `seqel-`. In the current package, some start with `nuc-`, some start with `pro-`, etc.

**Comment by lassik** [comment]
To make the current code conform to the usual naming pattern, the following renames should be made:

* `bioseq-*` -> `seqel-bioseq-*`
* `fasta-*` -> `seqel-fasta-*`
* `nuc-*` -> `seqel-nuc-*`
* `pro-*` -> `seqel-pro-*`
* ...

Would these be to verbose?

**Comment by RNAer** [comment]
Thanks for your prompt comments and feedback, @lassik ! It is indeed a bit verbose to add `seqel` prefix to all the functions/variables :sweat_smile:. Is this required? I assume the file names need conform too (e.g. nuc-mode.el -> seqel-nuc-mode.el)? Maybe I skimmed too fast and missed - is there any reference to this? I'd like to understand better its conventions and motivations.

**Comment by lassik** [comment]
Yes, the `nuc-mode.el` -> `seqel-nuc-mode.el` naming is the convention as well.

You could also split into multiple packages: a `bioseq` package, a `fasta` package, etc. One package can have a dependency on another package.

The names ´nuc` and `pro` are quite short; since Emacs has so many packages, there is probably some other code using those prefixes already.

**Comment by thblt** [comment]
Had a quick look:

`bioseq-interactive-region-or-line` is a macro, but it has an interactive clause that populates two arguments, although it takes none. Also it doesn't do what its docstring says. You probably want to remove the (interactive), move its contents to the body, make this a function, and fix the docstring. 

`end-of-col-err` lacks a prefix and possibly a defvar/defconst declaration, and has an extra undefined condition name, `my-own-errors`, which should be removed.

**Comment by thblt** [comment]
Also

> is there any reference to this? 

See [`(info "(elisp) Coding conventions")`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html#Coding-Conventions)

**Comment by RNAer** [comment]
Thanks a lot for the helpful feedback, @thblt and @lassik . I will add the prefix to names.

> Had a quick look:
> 
> `bioseq-interactive-region-or-line` is a macro, but it has an interactive clause that populates two arguments, although it takes none. Also it doesn't do what its docstring says. You probably want to remove the (interactive), move its contents to the body, make this a function, and fix the docstring.

This code isn't pretty, but I don't know how to make it better. I used macro here to get it to expand in a dozens of places (eg https://github.com/rnaer/seqel/blob/master/nuc-mode.el#L238) to avoid code redundancy. Do you have any suggestion how to do it better? 

> 
> `end-of-col-err` lacks a prefix and possibly a defvar/defconst declaration, and has an extra undefined condition name, `my-own-errors`, which should be removed.

I'll remove this piece of code. These lines are obsolete.

**Comment by lassik** [comment]
I agree with @thblt on `bioseq-interactive-region-or-line`. Something like this might be more idiomatic (untested code):

```Emacs Lisp
(defun bioseq-region-or-line ()
  "Return (BEG END) positions of region (if active) or current line."
  (if (use-region-p)
      (list (region-beginning) (region-end))
    (list (line-beginning-position) (line-end-position))))

(defun bioseq-unpaint (beg end)
  "Uncolor the sequences from BEG to END or the current line."
  (interactive (bioseq-region-or-line))
  (with-silent-modifications
    (remove-text-properties beg end '(font-lock-face nil))))
```

**Comment by RNAer** [comment]
fixed. any other comments? glad to learn new things in the process. I appreciate all the helps and suggestions.

**Comment by riscy** [comment]
Thanks all for the improvements discussed above.  I have a few comments about the packaging:

- The requirements in a -pkg.el file are typically placed inside the `define-package` form, but instead of getting into that I would suggest removing seqel-pkg.el and putting all of your metadata including dependencies in your main file (which in this case is seqel.el, since it matches the package name)
- You have different Package-Requires in different files (e.g. seqel-fasta-mode.el depends on Emacs 25.1, seqel.el depends on Emacs 24.3); only the Package-Requires in the main file will take effect, so adding Package-Requires (especially ones that differ) in non-main files is discouraged.  You may want to look at the variable `package-lint-main-file` before running package-lint, since you're distributing a multi-file package
- You're using "License: BSD-3" to indicate your license, but this is a little informal; prefer a [SPDX-License-Identifier](https://spdx.dev/ids/) and be sure to add a LICENSE file to your repository that GitHub correctly detects
- The default recipe is equivalent to what you have now, so you could simplify your recipe to `(seqel :repo "rnaer/seqel" :fetcher github)` which will automatically exclude test files, etc. if you expand in that direction
- There are few instances where packages should be automatically adding hooks when they're simply loaded.  For example instead of `(add-hook 'seqel-pro-mode-hook (lambda () (setq-local seqel-isearch-p t)))`, why not directly run that code when the mode is enabled?
- Without being totally familiar with what this package sets out to do, it's unusual for minor modes to be mutually exclusive of each other (re: the comment in the code "It should be not enabled with 'nuc-mode' at the same time.")  -- rather than defining minor modes, why not define two major modes?

**Comment by RNAer** [comment]
Thanks for the suggestions, @riscy 

> Thanks all for the improvements discussed above. I have a few comments about the packaging:
> 
> * The requirements in a -pkg.el file are typically placed inside the `define-package` form, but instead of getting into that I would suggest removing seqel-pkg.el and putting all of your metadata including dependencies in your main file (which in this case is seqel.el, since it matches the package name)

this package does not have external dependencies, thus no requirements in `define-package`. I can move the content in -pkg.el to seqel.el. May I ask what's the motivation?
 
> * You have different Package-Requires in different files (e.g. seqel-fasta-mode.el depends on Emacs 25.1, seqel.el depends on Emacs 24.3); only the Package-Requires in the main file will take effect, so adding Package-Requires (especially ones that differ) in non-main files is discouraged.  You may want to look at the variable `package-lint-main-file` before running package-lint, since you're distributing a multi-file package

I didn't have Package-Requires for each file previously, it was added because `package-lint-current-buffer` complained it. I am not sure how to lint multi-file package - is it suppose to run a run-tests.sh file like this https://github.com/purcell/package-lint/blob/master/run-tests.sh ?


> * You're using "License: BSD-3" to indicate your license, but this is a little informal; prefer a [SPDX-License-Identifier](https://spdx.dev/ids/) and be sure to add a LICENSE file to your repository that GitHub correctly detects

will do.

> * The default recipe is equivalent to what you have now, so you could simplify your recipe to `(seqel :repo "rnaer/seqel" :fetcher github)` which will automatically exclude test files, etc. if you expand in that direction

will do.

> * There are few instances where packages should be automatically adding hooks when they're simply loaded.  For example instead of `(add-hook 'seqel-pro-mode-hook (lambda () (setq-local seqel-isearch-p t)))`, why not directly run that code when the mode is enabled?

will do.

> * Without being totally familiar with what this package sets out to do, it's unusual for minor modes to be mutually exclusive of each other (re: the comment in the code "It should be not enabled with 'nuc-mode' at the same time.")  -- rather than defining minor modes, why not define two major modes?

Here, the major modes are for different file formats and minor modes for different types of data in the file. Usually we don't have different data (eg different type of sequences) in the same file. Technically, the package doesn't complain if users want to enable both minor modes. The docstring is just for conceptual purpose.

**Comment by riscy** [comment]
> this package does not have external dependencies, thus no requirements in define-package. I can move the content in -pkg.el to seqel.el. May I ask what's the motivation? And is there any location requirement (start or end of the seqel.el) for define-package form?

You actually don't need to put the `define-package` form in seqel.el -- all of the metadata goes into the boilerplate at the top (the first line of seqel.el contains your package description and name, your `;;; Version` contains your version, etc).  `package-lint` will help to make sure everything is in the correct format, but I see you already have those sections laid out, so you probably only need to delete the seqel-pkg.el file.

> I am not sure how to lint multi-file package - is it suppose to run a run-tests.sh

No, you'd just need to set the package-lint-main-file variable when evaluating your files using package-lint.

> Here, the major modes are for different file formats and minor modes for different types of data in the file. Usually we don't have different data (eg different type of sequences) in the same file.

Okay that sounds fine to me. :)

**Comment by riscy** [comment]
Forgot to answer this:

> May I ask what's the motivation?

MELPA will create a -pkg.el file automatically from the metadata in the main file and it means less duplication of the same information in your source.

**Comment by riscy** [comment]
Feel free to message when ready -- I'll mark this awaiting-upstream in the meantime.

**Comment by tarsius** [comment]
I am closing this pull-request because it is over a year old now. That doesn't mean that we won't add this to Melpa, just that you have to ask us to reopen it once you are ready.

**Pull request closed without merging**
