### PR TITLE
Add 'rivet-mode' recipe

### PR DESCRIPTION
**Pull request by thornjad**
### Brief summary of what the package does

Rivet mode is a minor mode for editing [Apache Rivet](https://github.com/apache/tcl-rivet) files, which blend HTML and TCL. It switches between Web and TCL major modes when appropriate.

### Direct link to the package repository

https://gitlab.com/thornjad/rivet-mode

### Your association with the package

Creator, maintainer and daily user

### Relevant communications with the upstream package maintainer

**None**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
  - ISC
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
rivet-mode.el:146: Error messages should *not* end with a period
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
No issues found.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

Other:
- rivet-mode.el#L95: It is beneficial to sharp-quote hooks; use `#'`
- rivet-mode.el#L157: It is beneficial to sharp-quote hooks; use `#'`

**Comment by thornjad** [comment]
Must have forgotten to run `checkdoc` again after adding that error message! Thank s for taking a look! I've made changes to fix these things up.

**Comment by thornjad** [comment]
I'm not sure if I should remove the `awaiting-upstream` label myself, but `checkdoc` is happy with the latest version of this package, and it uses sharp quotes.

**Comment by riscy** [comment]
Apologies for the long wait, it looks like I missed removing the label.  Thanks for pinging again. :)

**Pull request merged**
