### PR TITLE
Add recipe for gnus-summary-repo

### PR DESCRIPTION
**Pull request by TxGVNN**
### Brief summary of what the package does

A tool will help to import and export files between IMAP and local by using GNUS. It will like a storage service.

### Direct link to the package repository

https://github.com/TxGVNN/gnus-summary-repo

### Your association with the package

Maintainer

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
This is an interesting package, but I feel like it needs more documentation, considering how unusual it is.  I also recommend implementing some tests before encouraging users to trust it with their data.  That should probably include tests that users can run on their IMAP servers before starting to use the package to ensure their servers work properly with this functionality.

**Comment by TxGVNN** [comment]
Hi @alphapapa, Sorry for reply late and thanks for your suggestion. The package needs to be improved, and I just began with elisp. So it will take a lot of time :).

The first I should have a good document and describe how it works, what needs to be improved. I will do it now.

**Comment by TxGVNN** [comment]
Thank you for great review, 

>     * Since you're already `require`-ing `gnus-sum`, you don't need [this "declare-function" form](https://github.com/TxGVNN/gnus-summary-repo/blob/ef0e676dd7a402039fd517c8cf12f2117dfd8bb2/gnus-summary-repo.el#L24)
> 
I updated
>     * Consider re-using a built-in ignore list like `grep-find-ignored-files` or `grep-find-ignored-directories` instead of [defining yet another one](https://github.com/TxGVNN/gnus-summary-repo/blob/ef0e676dd7a402039fd517c8cf12f2117dfd8bb2/gnus-summary-repo.el#L40).
The purpose of `gnus-summary-repo-import-ignore` is to help people ignore the files they don't want to import  like the password, configuration file,... sensitive data. So I think should not use `grep-find-ignored-files` instead
> 
>     * Use `interactive` to handle [this code](https://github.com/TxGVNN/gnus-summary-repo/blob/ef0e676dd7a402039fd517c8cf12f2117dfd8bb2/gnus-summary-repo.el#L55-L60), e.g. you could just write `(interactive (list (or gnus-summary-repo-dir-local (read-directory-name "Select a directory to import: "))))`
I updated
> 
>     * Shouldn't [this test](https://github.com/TxGVNN/gnus-summary-repo/blob/ef0e676dd7a402039fd517c8cf12f2117dfd8bb2/gnus-summary-repo.el#L61) be `file-directory-p`?
I removed
> 
>     * Similar feedback for [this function](https://github.com/TxGVNN/gnus-summary-repo/blob/ef0e676dd7a402039fd517c8cf12f2117dfd8bb2/gnus-summary-repo.el#L71) and others -- use `interactive` where possible.
I don't know how to handle this [L129 ](https://github.com/TxGVNN/gnus-summary-repo/blob/cbd7b0d182fd37c32cccdbd684d1c8fce68eb538/gnus-summary-repo.el#L129) (read-string subject depends on filename ) and [L84](https://github.com/TxGVNN/gnus-summary-repo/blob/cbd7b0d182fd37c32cccdbd684d1c8fce68eb538/gnus-summary-repo.el#L84) (support number prefix to export many files)
> 
>     * Typos in [these var names](https://github.com/TxGVNN/gnus-summary-repo/blob/ef0e676dd7a402039fd517c8cf12f2117dfd8bb2/gnus-summary-repo.el#L225): modifation -> modification
I fixed

**Comment by TxGVNN** [comment]
>     * Shouldn't [this test](https://github.com/TxGVNN/gnus-summary-repo/blob/ef0e676dd7a402039fd517c8cf12f2117dfd8bb2/gnus-summary-repo.el#L61) be `file-directory-p`?
I mistook and updated https://github.com/TxGVNN/gnus-summary-repo/commit/849acf1050154afc6e501410bbe52e6c5d019ec8. Because of
- with importing action, I want to check it is exist directory
- with export action, I want to check it is NOT a regular file.
What do you think?

**Comment by purcell** [comment]
Thanks. I sent you a couple of fixes in https://github.com/TxGVNN/gnus-summary-repo/pull/2, but I'll go ahead and merge this now. :-)

**Comment by TxGVNN** [comment]
The good news today, thanks

**Pull request merged**
