### PR TITLE
Add recipe for wiz

### PR DESCRIPTION
**Pull request by zonuexe**
### Brief summary of what the package does

Provides macros to help configure `.emacs`.  It's like `use-package`, but more compact.

### Direct link to the package repository

https://github.com/zonuexe/emacs-wiz

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`wiz-env.el` with package-lint 20240118.1725 and `package-lint-main-file` = "wiz.el":
```
1 issue found:
10:0: error: Package-Requires outside the main file have no effect.
```

`wiz-env.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- The `;;; Commentary` for this file is much wider than 80 characters
```

`wiz-key.el` with package-lint 20240118.1725 and `package-lint-main-file` = "wiz.el":
```
1 issue found:
10:0: error: Package-Requires outside the main file have no effect.
```

`wiz-kwd.el` with byte-compile using Emacs 29.1:
```
wiz-kwd.el:89:69: Warning: reference to free variable `v'
```

`wiz-kwd.el` with package-lint 20240118.1725 and `package-lint-main-file` = "wiz.el":
```
1 issue found:
10:0: error: Package-Requires outside the main file have no effect.
```

`wiz-pkgs.el` with package-lint 20240118.1725 and `package-lint-main-file` = "wiz.el":
```
1 issue found:
10:0: error: Package-Requires outside the main file have no effect.
```

`wiz-shortdoc.el` with package-lint 20240118.1725 and `package-lint-main-file` = "wiz.el":
```
1 issue found:
54:0: error: "init-emacs-lisp-mode-setup" doesn't start with package's prefix "wiz".
```

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to reach out.

**Comment by zonuexe** [comment]
I'm sorry, I fixed it.

**Comment by riscy** [comment]
I am extremely sorry about the delay in getting back on this.  Here's the latest --

`wiz-shortdoc.el` with package-lint 20240507.1722 and `package-lint-main-file` = "wiz.el":
```
1 issue found:
54:0: error: "init-emacs-lisp-mode-setup" doesn't start with package's prefix "wiz".
```

I'm unable to tell (admittedly at a glance) why this function is being defined - it seems to be nullifying it, but the function doesn't exist in my Emacs instance.  Can you help me understand?

**Comment by zonuexe** [comment]
@riscy 
[shortdoc](https://www.gnu.org/software/emacs/manual/html_node/elisp/Documentation-Groups.html) is a built-in sample code documentation system added in Emacs 28. Here we use it to compare Lisp code with its execution results.

If you run `M-x shortdoc wiz`, you will see the following:

スクリーンショット 2024-05-29 6 29 29

To learn about the purpose of this feature, please read the Mastering Emacs article: [Emacs's Builtin Elisp Cheat Sheet](https://www.masteringemacs.org/article/emacs-builtin-elisp-cheat-sheet)

Since `wiz` is a macro for use in `init.el`, we need an example that defines a function to add to the hook. We could do something clever to avoid package-lint warnings, but that's not appropriate for user documentation.

Since these codes are simply expanded by `macroexpand`, the function `init-emacs-lisp-mode-setup` is never defined. This function is written in `init.el`, so it is prefixed with `init-`. I'm sorry if this is misleading, because it is not a built-in function for the Emacs initialization process.

**Comment by riscy** [comment]
Sorry once again about missing you last week!  I understand now - and learned about shortdoc.

Re: the package-lint warning; not a blocker, but why not just write e.g.
```elisp
    :eval (macroexpand
           '(wiz elisp-mode
              :hook-names (emacs-lisp-mode-hook lisp-interaction-mode-hook)
              :setup-hook (defun wiz-custom-setup-hook () (message "Your own hook here."))))))
```
and now package-lint is happy (no false positives for you to get used to, so you can e.g. actually gate CI on it), and I bet I wouldn't have been as confused if I saw `Your own hook here` instead of `Nyan!`.

Also not a blocker, but I think your use of shortdoc is a little idiosyncratic and because every example is a macroexpansion, but of course running `macroexpand` isn't the normal way a user would use `wiz`.  Compare to the shortdoc for `string`:
```
(make-string length init)
  Return a newly created string of length LENGTH, with INIT in each element.
  (make-string 5 ?x)
    ⇒ "xxxxx"
```
where `(make-string 5 ?x)` is much closer to exemplar code that someone would write in practice.  I understand the macroexpansion is necessary to force shortdoc into documenting how wiz works, but why not [also?] write a more straightforward explanation in your `;;; Commentary`?

With all that said, I'll hit merge on this.  And thank again!

**Pull request merged**
