### PR TITLE
Add recipe for ron-mode

### PR DESCRIPTION
**Pull request by enderger**
# Rusty Object Notation (RON) EMACS Major Mode
### What is RON
Rusty Object Notation (RON) is a relatively obscure format for storing data in the Rust Programming Language. It is predominantly used by the Amethyst Game Engine (https://amethyst.rs/) as an alternative to JSON.

### Source
https://chiselapp.com/user/Hutzdog/repository/ron-mode/home
(git mirror, used for compatibility) https://codeberg.org/Hutzdog/ron-mode

### Your association with the package
I am the author of the package, which takes inspiration from nabero's RON Mode package.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). (BSD 2-Clause)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them (Nice tripwire, BTW)

### CODE REVIEW

**Comment by enderger** [comment]
Note that since I usually use Fossil SCM for my newer projects, the repo in the package is actually an automated mirror which syncs with the trunk (Fossil's master) branch hosted on codeburg.org. Also, it appears as though the 1st build failed. I have pushed a correction to my fork (I have the package working fine via manual loading, but it appears as though I messed up the package recipe.)

**Comment by enderger** [comment]
Hey, so it's been about a week and I was wondering if there was anything I am doing wrong for the submission process.

**Comment by milkypostman** [comment]
A week turnaround time is pretty typical nowadays.  Thanks for the ping. I’ll try to have a look if no one find This soon. 
GitHub <notifications@github.com> wrote:
“Hey, so it's been about a week and I was wondering if there was anything I am doing wrong for the submission process.”

**Comment by riscy** [comment]
Don't worry about the build failure -- there are some small issues with the CI, currently.

> Hey, so it's been about a week and I was wondering if there was anything I am doing wrong for the submission process.

I'm usually looking on weekends.  Thanks for your patience!  Here's where we're at re: the checklist.

byte-compile (using Emacs 26.3):
```
ron-mode.el:49:56:Warning: reference to free variable `ron-mode-indent-offset'
```
`defvar` for this variable should fix this.

Beyond that, just some standard stuff re: making licenses as explicit as we can (as mentioned in CONTRIBUTING):

- Add a LICENSE or COPYING file to the repository

I also notice you have a line in ron.el about using the BSD 2-Clause License, but if you're feeling like it, you can improve on that line by making it tooling-detectable and standardized with e.g. an [SPDX-License-Identifier](https://spdx.org/using-spdx-license-identifier).

(I thought it was interesting that the ron repo is using `rust` syntax highlighting in their README.md)

Altogether the code looks good.  A couple small comments regarding style, docstrings are typically on a line by themselves, i.e.
```elisp
(defun ron-indent-line () "Handles line indentation."
  (interactive)
```
would be
```elisp
(defun ron-indent-line ()
  "Handles line indentation."
  (interactive)
```
and you have `(provide 'ron-mode)` twice at the bottom of the file.

**Comment by enderger** [comment]
Ok, thank you both for getting back to me on this. I've fixed the issues listed and pushed the new version to Fossil and the Git mirror. It should be ready for re-review.

As for the issue with Travis, it's probably that it's using Emacs 24.

**Comment by enderger** [comment]
Ok, I've fixed the byte compile warning (I had a few small issues with undoing and it must have been reverted)
Sorry I couldn't get to this sooner, we had a flea problem yesterday and couldn't be in the house for a good while.

**Comment by riscy** [comment]
Yikes!  Anyway, this looks good.  The one last nag I notice is that you should probably try to wrap your `;;; Commentary` (80 characters is traditional) a little more tightly, since it might display awkwardly in e.g. <kbd>M-x finder-commentary</kbd>.  Not a blocker.

And, welcome to MELPA!

**Comment by enderger** [comment]
Thanks! I'll push an update with a more terse commentary.

**Comment by riscy** [comment]
Terse isn't necessary at all for Commentary (in fact it's better when there's more information, since it shows up on your [index page](https://melpa.org/#/ron-mode)), but linewrapping is generally a good idea

**Pull request merged**
