### PR TITLE
Add company-box recipe

### PR DESCRIPTION
**Pull request by sebastiencs**
### Brief summary of what the package does

A front-end for `company-mode`

### Direct link to the package repository

https://github.com/sebastiencs/company-box

### Your association with the package

Author

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Please run `package-lint` and build the package locally as requested above.

Couple of other points about the code:
- Don't define faces with just `:foreground` or `:background` - try to inherit default (even arbitrary) faces wherever possible, so that existing themes will work smoothly with your code, otherwise define both `dark` and `light` versions of the face.
- "A company front end" doesn't tell potential users why they might use this, so why would the install the package? What's interesting about it? It's worth including just a few words to explain this, since you're publishing it for wider use.
- I think your `~` variables are supposed to be package-private. Use `--` instead, in order to follow existing conventions.
- Your minor mode definition contains only code for turning the mode on. The body of the mode definition should check for the `company-next-mode` variable and handle both turning it on and turning it off.

**Comment by sebastiencs** [comment]
Thanks for the review.

I have rename the package following [this discussion](https://github.com/company-mode/company-mode/issues/756)

> Please run package-lint and build the package locally as requested above.

Done

> Don't define faces with just :foreground or :background - try to inherit default (even arbitrary) faces wherever possible, so that existing themes will work smoothly with your code, otherwise define both dark and light versions of the face.

Done

> "A company front end" doesn't tell potential users why they might use this, so why would the install the package? What's interesting about it? It's worth including just a few words to explain this, since you're publishing it for wider use.

Done

> I think your ~ variables are supposed to be package-private. Use -- instead, in order to follow existing conventions.

I don't like this convention because when a user execute `describe-function` or `describe-variable` and type `company-box-` he will get completions for private and public var/func, which is a bit confusing from a user POV, IMHO.
With `~`, the user will only see the public items.
Is it possible to keep the `~` ?

> Your minor mode definition contains only code for turning the mode on. The body of the mode definition should check for the company-next-mode variable and handle both turning it on and turning it off.

It already contains code to turn off the mode: [here](https://github.com/sebastiencs/company-box/blob/da9a34ed4b60e621f983758aa1a4e17cf84fc584/company-box.el#L609)

**Comment by dgutov** [comment]
> I don't like this convention

Let's not try to invent different conventions in every package. If the behavior of `describe-function` is not to your liking, please report that to Emacs developers.

> It already contains code to turn off the mode: here

What happens if someone calls `(company-box-mode -1)` twice?

**Comment by sebastiencs** [comment]
> If the behavior of describe-function is not to your liking, please report that to Emacs developers.

This has nothing to do with `describe-function`, but about the completions items a user get when writing a variable/function of the package:
For example, if a user wants to change a variable, he will type:
`(setq company-box-[]`
With `--`, the user will also see private variables in the completion list

> What happens if someone calls (company-box-mode -1) twice?

Nothing, is it suppose to do something ?

**Comment by dgutov** [comment]
> but about the completions items a user get when writing a variable/function of the package

That completion table is selected inside `describe-function`. `help--symbol-completion-table`, to be exact.

> Nothing, is it suppose to do something?

OK, here's a smaller question: does `(company-box-mode -1)` properly disable the mode? It should.

**Comment by sebastiencs** [comment]
> That completion table is selected inside describe-function. help--symbol-completion-table, to be exact.

That's good to know

> > It already contains code to turn off the mode: here

>  does (company-box-mode -1) properly disable the mode? 

Smaller answer: yes

**Comment by dgutov** [comment]
> Smaller answer: yes

Indeed, that works fine.

I think you could split `company-box~set-mode` in two functions, though. For readability.

**Comment by purcell** [comment]
> It already contains code to turn off the mode: here

Great!

> With ~, the user will only see the public items.
> Is it possible to keep the ~ ?

No, sorry. These days we insist that authors follow the elisp community standards, since the point of publishing a package is to share it with the community. The standards may not be perfect, but they play a big part in everyone being able to contribute to each others code, so conformity here beats personal preferences.

**Comment by sebastiencs** [comment]
> No, sorry. 


@purcell Alright, it's done

**Comment by pkulev** [comment]
Also you can squash commits, because the package renaming within one PR is not necessary for melpa commit history.

**Comment by sebastiencs** [comment]
Done

**Comment by purcell** [comment]
Merged now - thanks for your patience. :-)

**Comment by tarsius** [comment]
@sebastiencs Are you going to package [icons-in-terminal](https://github.com/sebastiencs/icons-in-terminal) for Melpa too?

**Comment by sebastiencs** [comment]
@tarsius As discussed [here](https://github.com/sebastiencs/icons-in-terminal/issues/8#issuecomment-320904174), I'm not sure. But since there aren't many changes on the repo, it might be a good idea

**Pull request merged**
