### PR TITLE
add darcula theme

### PR DESCRIPTION
**Pull request by fommil**
https://github.com/fommil/darcula-theme-emacs

### CODE REVIEW

**Comment by tarsius** [comment]
@fommil These repositories no longer exist:

- https://gitlab.com/fommil/emacs-darcula-theme
- https://gitlab.com/fommil/emacs-intellij-theme
- https://gitlab.com/fommil/emacs-prettify-greek

Do these packages have new homes?

**Comment by fommil** [comment]
oh sorry @tarsius I migrated everything back to github.com/fommil. Everything should have the same project name. gitlab just wasn't working out for me.

**Comment by fommil** [comment]
I think I changed the naming conventions at some point, probably gitlab was setting up forwarding. This is where they live now. No changes in years:

- https://github.com/fommil/darcula-theme.el
- https://github.com/fommil/intellij-theme.el
- https://github.com/fommil/prettify-greek.el

**Comment by tarsius** [comment]
Thanks!
Updated.

**Pull request merged**
