### PR TITLE
Add recipe for blame-this

### PR DESCRIPTION
**Pull request by pierre-lecocq**
### Brief summary of what the package does

Display a git blame summary of the current line.

### Direct link to the package repository

https://github.com/pierre-lecocq/blame-this

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

 **None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Isn't this pretty much the same as [git-messenger](https://github.com/syohex/emacs-git-messenger/blob/83815915eb8c1cb47443ff34bca3fecf7d2edf3a/git-messenger.el)?

**Comment by alphapapa** [comment]
Magit also covers this functionality quite thoroughly.

**Comment by pierre-lecocq** [comment]
@purcell , @alphapapa thanks for pointing me these alternative solutions !
I don't use magit myself, and did not know about git-messenger.

I wanted to make a _very lightweight_ package for this feature as it is an important part of our workflow.
Nevertheless, if you do think it is too redundant, feel free to reject this pull request.

On a side note, thank you very much for your hard work maintaining such a valuable tool for the community!

Pierre.

**Comment by purcell** [comment]
Yep, I think that since this is well covered elsewhere, I'd prefer to decline the package, but thanks for taking the time to submit it!

**Pull request closed without merging**
