### PR TITLE
Recipe: Add hyperdrive

### PR DESCRIPTION
**Pull request by alphapapa**
### Brief summary of what the package does

[Hyperdrive](https://docs.holepunch.to/building-blocks/hyperdrive) is a secure, real-time distributed file system designed for easy peer-to-peer file sharing. hyperdrive.el is an independent project built by [USHIN](https://ushin.org/) which provides an Emacs interface for managing hyperdrives.

### Direct link to the package repository

https://git.sr.ht/~ushin/hyperdrive.el

### Your association with the package

Co-author.

### Relevant communications with the upstream package maintainer

We've agreed that we're ready to submit this to MELPA.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings (As usual, not really, but we did our best.)
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Code looks great.  One thing I notice is that the files have GNU GPL license boilerplate, but the repo's license is GNU Affero, so these should be synced up.  There is also:

`hyperdrive-org.el` with package-lint 20221003.1636:
```
1 issue found:
128:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```
but I'm aware that org has its own conventions around these.

**Comment by alphapapa** [comment]
@riscy Thanks for noticing the license issue.  @josephmturner's going to sync that up, and then it should be good to merge.

Regarding the use of `with-eval-after-load`, in this case it's the standard way to define a new Org link type after Org is loaded, to avoid forcing Org to be loaded prematurely.  But thanks for pointing it out.  :)

**Comment by josephmturner** [comment]
@riscy Thank you for catching the licensing boilerplate mistake! Fixed now.

**Comment by riscy** [comment]
Thanks both!  Merging.

**Pull request merged**
