### PR TITLE
Add amixer recipe

### PR DESCRIPTION
**Pull request by remvee**
### Brief summary of what the package does

Basic commands to control audio volume via amixer.

### Direct link to the package repository

https://github.com/remvee/amixer-el

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
You may want to make the customization group explicit with, e.g.

```elisp
(defgroup amixer nil "Functions to call out to amixer."
  :prefix "amixer-" :group 'convenience)
```

but this isn't a blocker.  Thanks for your close adherence to the checklist -- and, welcome to MELPA!

**Comment by remvee** [comment]
Thanks for the tip!

**Comment by tarsius** [comment]
Another, older, `amixer.el` also exists: http://www.sugarshark.com/elisp/mylisp/amixer.el. I'll just leave this here (and update the Emacsmirror to mirror your implementation), but would encourage you to look at the other implementation, possibly contact its author, and ideally come up with an implementation that is "better" than both current implementations, whatever that means in this case. But I do not want to be involved in the process (done that too often already, for other packages I personally am not really interested in).

**Comment by tarsius** [comment]
@riscy @purcell maybe the review process should involve checking whether another package by the same name already exists on the Emacsmirror (*including* the Emacsattic)?

**Comment by remvee** [comment]
Maybe I should also put that in my hey-lets-whip-something-up-process, it's almost identical.

**Comment by riscy** [comment]
That's my mistake!  It's outlined well already in CONTRIBUTING, but I haven't formalized it well enough as a part of my own process.

**Comment by remvee** [comment]
Please let me know if I can do anything, rename for instance.

**Comment by riscy** [comment]
Thanks hugely for the offer, @remvee.  Now that I actually take the time to google, I see one more amixer, which is part of emacspeak -- https://github.com/tvraman/emacspeak/blob/master/lisp/amixer.el

In light of that, perhaps it would be a good idea to rename -- I'd still encourage you to reach out to the amixer author @tarsius listed in case there's possibility for collaboration.

**Comment by remvee** [comment]
@tarsius let's start by dropping this recipe from melpa.  This package is the result of me trying to tidy up some of my emac.d setup, thinking somebody might also want to use it.  It only yielded 10 downloads so far at this moment (according to https://melpa.org/#/amixer) so not many people will be effected by this, if at all.  I'm not sure what the policy on pulling packages is on melpa but can you revert the merge?

Meanwhile I'll try an come up with another name and submit another PR when that's done.

**Comment by tarsius** [comment]
Considering that this only got added a few days ago, I think we can just remove it again. Please open a pull-request for that.

**Pull request merged**
