### PR TITLE
Add banner-comment

### PR DESCRIPTION
**Pull request by WJCFerguson**
### Brief summary of what the package does

Trivial Emacs package to format a comment as a banner.  Will reformat an existing banner.

### Direct link to the package repository

https://github.com/WJCFerguson/banner-comment

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, this looks handy!

- There's some `package-lint` feedback you've missed here.
- I suggest you use the standard more verbose header boilerplate which makes the licence explicit.
- Where you've hard-coded 80 as the default width, I suggest you use the value of the `fill-column` variable, which users who prefer longer or shorter lines will already have set according to their preferences.

**Comment by WJCFerguson** [comment]
Good feedback thanks, I'll address those items.  The 80 column thing occurred to me after submitting.

**Comment by WJCFerguson** [comment]
Right, should have resolved those now...

**Comment by WJCFerguson** [comment]
Oh - I just read your suggestion properly for fill-column - instead I made it another variable.  `fill-column` sounds more sensible...  I'll change it to that.

**Comment by purcell** [comment]
Great, merged now. Welcome to MELPA! :tada:

**Pull request merged**
