### PR TITLE
Add origami-predef.el

### PR DESCRIPTION
**Pull request by alvarogonzalezsotillo**
### Brief summary of what the package does

This emacs package extends the origami package to apply some initial foldings when opening a file, based on tags in the file contents.
I tried to contact the author of the origami package (see https://github.com/gregsexton/origami.el/issues/95), in order to integrate ths functionality in his package, but I got no response.

### Direct link to the package repository

https://github.com/alvarogonzalezsotillo/origami-predef

### Your association with the package
I am the author and the maintainer.

### Relevant communications with the upstream package maintainer
**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Couple very quick checklist nags:

checkdoc (using version 0.6.1):
```
Warning (emacs): 
origami-predef.el:48: All interactive functions should have documentation
```

package-lint-current-buffer (using version 20200419.406):
```
1 issue found:
51:26: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-find-if'.
```

**Comment by terlar** [comment]
No specific intention, but this might be of interest: https://github.com/melpa/melpa/issues/6716

**Comment by alvarogonzalezsotillo** [comment]
I made some changes to the package and push them to the package repository. I didn't realize that the package was not "pinned" to the existing version when I made this PR.

I have addressed the issues of dependencies and documentation, and I have made a specific branch in my repository to publish in MELPA.

**Comment by riscy** [comment]
> I have addressed the issues of dependencies and documentation, and I have made a specific branch in my repository to publish in MELPA.

The regular MELPA workflow is to just use the `master` branch, unless in special cases.  Since this package is just arriving, I think it's safe for us to just put all of your MELPA work on master -- what do you think?

If you want to differentiate from "stable" MELPA releases, you can automatically publish releases to MELPA stable by tagging releases.

By the way, I appreciate you including a Quick Start in your commentary -- useful!

**Comment by alvarogonzalezsotillo** [comment]
I use master branch now, and I added a tag for the `1.0` version.

**Comment by riscy** [comment]
Taking a closer look now.

A little more information about what the package does in the Commentary (such as you have in your README) could be useful.

I realize the indicators `*origami-this*` and `*origami-next*` are customizable, but I have a couple thoughts on these.  First, they are a bit long and maybe hard to type -- but that's not a big deal.  The other is the implicit tie-in with origami by having that word in there, but this sort of functionality could one day also exist for fold-detecting packages like hideshow, yafold, etc.  You could reduce typing and pay homage to Emacs lisp's autoload with something like `autofold` and `autofold:`, but I'll leave that for your consideration.

Some minor additional stuff:
- origami-predef.el#L99: Avoid adding '--private' functions to user's hooks
- "will the invoked" -> "will be invoked" (two places)

**Comment by alvarogonzalezsotillo** [comment]
> The other is the implicit tie-in with origami by having that word in there

My original idea was to contribute to origami (https://github.com/gregsexton/origami.el/issues/95), but that package doesn't seem to be actively maintained.

> "will the invoked" -> "will be invoked" (two places)

Solved.

> origami-predef.el#L99: Avoid adding '--private' functions to user's hooks

I removed the intermediate function and `origami-predef-apply`is called directly from `find-file-hook`

>  You could reduce typing and pay homage to Emacs lisp's autoload with something like autofold and autofold:

I agree that `*origami-this*` is, at least, questionable. Do you prefer `autofold`, `###autofold` or `*autofold*`?  I think `autofold` is nicer but can lead to conflicts with variables in usual programing languages, so i use `*autofold*` now, but I would like to know your opinion about this.

> A little more information about what the package does in the Commentary (such as you have in your README) could be useful.

I have expanded the Commentary with the contents of the readme file.

**Comment by tarsius** [comment]
> My original idea was to contribute to origami, but that package doesn't seem to be actively maintained.

Have you tried contacting him by email? He might be willing to make you a co-maintainer or something.

**Comment by alvarogonzalezsotillo** [comment]
> Have you tried contacting him by email? He might be willing to make you a co-maintainer or something.

I'm afraid I have not the skills needed to maintain origami, I don't feel confident about that.

**Comment by tarsius** [comment]
Right. Looked at #6716 again (somehow overlooked the mention above) and agree that implementing the new functionality as a new package is your best option when it comes to this base package.

@riscy Please have another look.

**Comment by riscy** [comment]
Yep, this looks good to me now.  Thanks!

**Pull request merged**
