### PR TITLE
Add recipe for counsel-world-clock

### PR DESCRIPTION
**Pull request by kchenphy**
### Brief summary of what the package does

Displaying world clock using Ivy.

### Direct link to the package repository

https://github.com/kchenphy/counsel-world-clock

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

NA
### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by tarsius** [comment]
The build error is due to an unrelated change, which is fixed now. Please rebase your commit so that the tests can be run for your change. If you use Magit you can do so using <kbd>f u</kbd> to fetch, <kbd>r u</kbd> to rebase, and <kbd>P - f p</kbd> to force push.

**Comment by kchenphy** [comment]
rebased

**Comment by purcell** [comment]
Thanks, this is neat! Note that the hard-coded list of zones will not necessarily be available on every system, and they will also change over time and get out of sync with your code. I'm not aware of a standard way to get these from Emacs, but it's something to think about: we should arguably have a `tzdata` package or similar to avoid these issues.

I'll go ahead and merge this, but you should add an `;;;###autoload` comment just before the `counsel-world-clock` function.

Welcome to MELPA!

**Comment by kchenphy** [comment]
Thanks @purcell ! I agree with you that an `tzdata` library is in need.

**Pull request merged**
