### PR TITLE
recipes: add kconfig-mode

### PR DESCRIPTION
**Pull request by elmarco**
### Brief summary of what the package does

A kernel config mode (kconfig)

### Direct link to the package repository

https://github.com/delaanthonio/kconfig-mode

### Your association with the package

User

### Relevant communications with the upstream package maintainer

https://github.com/delaanthonio/kconfig-mode/issues/2

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, this definitely looks valuable.  Here's some feedback I hope is helpful:

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems)
(The following assumes lexical binding is enabled)
```
kconfig-mode.el:121:1:Warning: Unused lexical variable `i'
```
This looks like a false positive though -- more on this below re: the `result` variable.

[This](https://github.com/delaanthonio/kconfig-mode/blob/fce71f2650a18eb974a5a26027d6986d90970ff5/kconfig-mode.el#L123) expression doesn't seem like it will have any effect.

The result variable [here](https://github.com/delaanthonio/kconfig-mode/blob/fce71f2650a18eb974a5a26027d6986d90970ff5/kconfig-mode.el#L126) seems unnecessary except to ensure that a value is returned by the function, but in that case why not write the function as:
```elisp
(defun kconfig-outline-level ()
  "Kconfig function to compute nesting level."
  (let ((prefix (match-string 0))
        (result 0))
    (dotimes (i (length prefix))
      (setq result (+ result
                      (if (equal (elt prefix i) ?\s)
                          1 tab-width))))
    result))
```
This also has the effect of fixing the compiler's false-positive on the `i` variable mentioned above, when lexical binding is enabled.

Sharp-quote suggestions:
- kconfig-mode.el#L150: It is beneficial to sharp-quote hooks; use `#'`

Miscellaneous and minor:
- kconfig-mode.el#L26: Prefer `https` over `http` (if possible)
- kconfig-mode.el#L5: This copyright notice may need updating to the current year.

**Comment by purcell** [comment]
Thanks - the `auto-mode-alist` entry looks wrong here, though. Check using `M-: (string-match-p "pattern" "/example/full/path")` that the pattern matches the files you want to be opened in this mode. Or explain here which files you'd like to match and we can help you out with the regexp.

**Comment by delaanthonio** [comment]
Upstream has been updated with the requested changes.

**Comment by riscy** [comment]
> Thanks - the auto-mode-alist entry looks wrong here, though. Check using M-: (string-match-p "pattern" "/example/full/path") that the pattern matches the files you want to be opened in this mode. Or explain here which files you'd like to match and we can help you out with the regexp.

Just to chime in on this:

```elisp
(add-to-list 'auto-mode-alist '("\\Kconfig\\\'" . kconfig-mode))
```
Looks like there is an extra `\` near the end of the string (probably we just want `\\Kconfig\\'`) but ultimately it evaluates to the same string (the extra `\` just escapes the `'`).  This should match `Kconfig` files, so I believe it works correctly.

**Comment by delaanthonio** [comment]
@riscy I updated the line to be `(add-to-list 'auto-mode-alist '("\\Kconfig\\'" . kconfig-mode))` as you requested

**Comment by riscy** [comment]
Great, thanks for this!  Welcome, both of you, to MELPA.

**Pull request merged**
