### PR TITLE
feat: add EXATO (Evil-mode XML Attributes Text Object)

### PR DESCRIPTION
**Pull request by ninrod**
### Brief summary of what the package does

Adds a text object for manipulating XML Attributes.

### Direct link to the package repository

https://github.com/ninrod/exato

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

** None Needed. **

### Checklist

Please confirm with `x`:

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [ x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x ] My elisp byte-compiles cleanly
- [ x] `M-x checkdoc` is happy with my docstrings
- [ x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. This looks okay and I'll go ahead and merge it now, but I *strongly* encourage you to remove the intrusive section markers, e.g. `header {{{`. You've got a duplicate `;;; exato.el ---` line there (such that the `lexical-binding` declaration will not take effect in some Emacs versions, and the code just looks messy as a result of all the `{{{` and `}}}`, particularly those that repeat the function names.

**Comment by ninrod** [comment]
thanks @purcell, it's a thing I brought from my vim days. I'll handle this easily.

**Comment by ninrod** [comment]
@purcell, fixed in https://github.com/ninrod/exato/commit/2eb415af77641743931c535c41ce1761f089ebc9. Thanks for the tip!

**Comment by purcell** [comment]
Nice! :-)

**Pull request merged**
