### PR TITLE
Add helm-posframe recipe

### PR DESCRIPTION
**Pull request by tumashu**
### Brief summary of what the package does

Use posframe to show helm menu.

### Direct link to the package repository

https://github.com/tumashu/helm-posframe

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

 **None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
Could you please explain this?

> Note: this file is auto converted from helm-posframe.el by el2org, please do not edit it by hand!!!

I looked at the linked el2org package, and it seems to essentially reinvent Org Babel (and/or Outshine, Outorg, outline-minor-mode, etc).

Besides that, how are users supposed to modify the code and submit pull requests?  You haven't even put the Org file in the repo.  So if a user sent a PR, you'd have to extract the changes, make them in your private Org file, then re-convert it with el2org, and commit that to the repo?

This all seems very confusing.  If you really want to maintain your Elisp files as Org files and publish them as `.el`  files, I recommend looking at Kaushal Modi's https://github.com/kaushalmodi/eless project.

**Comment by tumashu** [comment]
The document is in the comment of el file, not a external org file.  el2org is a tool which can convert orgfy comment to README.md

**Comment by alphapapa** [comment]
I'm sorry, I'm not sure I understand:

> The document is in the comment of el file, not a external org file.

So what's the difference between using el2org and using a package like Outorg?

> please do not edit it by hand!!!

Why does it say this?

**Comment by tumashu** [comment]
I mean, If you want to edit the document, you should edit the el file's commentary, and use el2org to generate README.md from commentary, instead of direct edit README.md, for the change will be override when run el2org

**Comment by alphapapa** [comment]
Oh, I thought that comment was about the `.el` file, not the readme.  So el2org creates the readme file from the elisp commentary?

**Comment by tumashu** [comment]
you are right

**Comment by purcell** [comment]
Thanks, merged - sorry for the delay.

**Comment by alphapapa** [comment]
@tumashu By the way, a screenshot would really help users understand what this does (animated GIF would be even better).

**Pull request merged**
