### PR TITLE
Add recipe `emacs-tg-themes`

### PR DESCRIPTION
**Pull request by tgadfly**
### Brief summary of what the package does

Pack of atmospheric themes.

### Direct link to the package repository

https://github.com/tgadfly/emacs-tg-themes

### Your association with the package

I am the author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Couple of initial issues here:
- The recipe and package name should be `tg-themes`, not `emacs-tg-themes`
- That name should match either a `.el` file or `-pkg.el` file in the repo, so that MELPA can access metadata for the package. I suggest adding a `tg-themes-pkg.el` file containing a `define-package` form.

**Comment by tgadfly** [comment]
Thanks for help. Did fixes for both issues.

**Comment by riscy** [comment]
Quick pass from me.

### tg-exosphere-dark-theme.el ###

byte-compile (using Emacs 26.3):
- tg-exosphere-dark-theme.el#L255: Don't set `no-byte-compile: t`.
  Byte-compiling is enabled in what follows
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
- No issues!

checkdoc (using version 0.6.1):
- No issues!


Suggestions/experimental static checks:
- tg-exosphere-dark-theme.el#L23: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### tg-thermosphere-dark-theme.el ###

byte-compile (using Emacs 26.3):
- tg-thermosphere-dark-theme.el#L255: Don't set `no-byte-compile: t`.
  Byte-compiling is enabled in what follows
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
- No issues!

checkdoc (using version 0.6.1):
- No issues!

Suggestions/experimental static checks:
- tg-thermosphere-dark-theme.el#L23: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### tg-troposphere-dark-theme.el ###

byte-compile (using Emacs 26.3):
- tg-troposphere-dark-theme.el#L255: Don't set `no-byte-compile: t`.
  Byte-compiling is enabled in what follows
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
- No issues!

checkdoc (using version 0.6.1):
- No issues!

Suggestions/experimental static checks:
- tg-troposphere-dark-theme.el#L23: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading tg-exosphere-dark-theme.el
Loading tg-thermosphere-dark-theme.el
Loading tg-troposphere-dark-theme.el
Done.
```

### Package ###

- GitHub API found `MIT License`
- Package-Requires: n/a
  - Package-Requires mismatch between tg-exosphere-dark-theme.el and tg-themes-pkg.el!
  - Package-Requires mismatch between tg-thermosphere-dark-theme.el and tg-themes-pkg.el!
  - Package-Requires mismatch between tg-troposphere-dark-theme.el and tg-themes-pkg.el!

The main issue with the packaging is that, since you chose to use a `-pkg.el` file, you'll need to specify your package-requires in there.

**Comment by tarsius** [comment]
Friendly ping! :ping_pong:

**Comment by tarsius** [comment]
No reply or new commits for ~9 months, so I am closing.

**Pull request closed without merging**
