### PR TITLE
org-trello recipe update: Exclude org-trello-tools* namespaces from recipe

### PR DESCRIPTION
**Pull request by ardumont**
Hello,
There is a problem in the actual recipe which installs unintentionally a developer 'namespace'.
[This was revealed in the following issue](https://github.com/org-trello/org-trello/issues/312).

I'm the maintainer of the package.

melpa tests are ok.

```sh
# tony at corellia in ~/repo/perso/melpa on git:master x [15:48:02]
$ make recipes/org-trello
 • Building recipe org-trello ...
/usr/bin/timeout -k 60 600 emacs --no-site-file --batch -l package-build.el --eval "(let ((package-build-stable nil) (package-build-write-melpa-badge-images t) (package-build-archive-dir (expand-file-name \"./packages\" package-build--this-dir))) (package-build-archive 'org-trello))"

;;; org-trello

Fetcher: github
Source: org-trello/org-trello

Updating /home/tony/repo/perso/melpa/working/org-trello/
/home/tony/repo/perso/melpa/working/org-trello/org-trello.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-utils.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-utils.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-setup.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-setup.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-query.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-query.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-proxy.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-proxy.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-pkg.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-pkg.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-log.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-log.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-input.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-input.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-hash.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-hash.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-entity.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-entity.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-deferred.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-deferred.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-date.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-date.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-data.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-data.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-controller.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-controller.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-cbx.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-cbx.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-buffer.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-buffer.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-backend.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-backend.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-api.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-api.el
/home/tony/repo/perso/melpa/working/org-trello/org-trello-action.el -> /tmp/org-trello16003sqK/org-trello-20160207.842/org-trello-action.el
Wrote /home/tony/repo/perso/melpa/packages/org-trello-readme.txt
File: /home/tony/repo/perso/melpa/packages/org-trello-20160207.842.entry
Built in 0.219s, finished at Mon Feb  8 15:48:12 2016
 ✓ Wrote 4.0K -rw-r--r-- 1 tony tony  218 Feb  8 15:48 ./packages/org-trello-20160207.842.entry
260K -rw-r--r-- 1 tony tony 260K Feb  8 15:48 ./packages/org-trello-20160207.842.tar
4.0K -rw-r--r-- 1 tony tony  752 Feb  8 15:48 ./packages/org-trello-badge.svg
4.0K -rw-r--r-- 1 tony tony 2.3K Feb  8 15:48 ./packages/org-trello-readme.txt
 Sleeping for 0 ...
sleep 0
```

Thanks

### CODE REVIEW

**Comment by purcell** [comment]
There's also other elisp which should get excluded, e.g. `test-install-file.el`. Please could you just put all the distributable elisp in a single directory, and we'll include all of that?

**Comment by ardumont** [comment]
Hello,

> There's also other elisp which should get excluded, e.g. test-install-file.el. 

`test-install-file.el` won't be installed (in the sample i provided, it's not included).
Only `org-trello*.el` files will be.
The exceptions being `org-trello-tools.el` (and its test namespace counterpart) are not to be included for it's not production namespaces.

> Please could you just put all the distributable elisp in a single directory, and we'll include all of that rather than worry about individual inclusions/exclusions in the recipe?

I'm not sure it's as easy as that. For packaging surely but for development, not so sure.
The last time, i splitted one file to multiple ones (because there were too much code for emacs to support it well) it had impacts i did not measure well...

What's the trouble with using the dsl provided by melpa?

Thanks for your time

**Comment by purcell** [comment]
Sorry, yes, I missed the existing `org-trello*.el` pattern.

> What's the trouble with using the dsl provided by melpa?

It means we need to change the recipe if you add more non-distributable files. But hey, if that's okay with you, it's fine with me, so I'll merge this.

**Comment by ardumont** [comment]
> It means we need to change the recipe if you add more non-distributable files. 

Ok.

> But hey, if that's okay with you, it's fine with me, so I'll merge this.

Thanks Steve.

I don't intend to do that semi-mistake again :D.
If there is yet again need, it will be in that same namespace.

`Semi` because i consciously name `org-trello-tools.el` after the other namespaces to respect convention i established previously.
And the `mistake` part was that i did not foresee the packaging trouble (i did already excluded it in the marmalade packaging through Cask... but did not see the problem in melpa).

Thanks again for your time.

Cheers,

**Comment by purcell** [comment]
Thanks for your help & patience.

**Pull request merged**
