### PR TITLE
Addition of company-axiom package

### PR DESCRIPTION
**Pull request by pdo**
### Brief summary of what the package does

A company-mode backend for axiom-environment.

### Direct link to the package repository

https://bitbucket.org/pdo/axiom-environment

### Your association with the package

Author

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Makes sense to split things out. Couple of notes:

- You'll need to add a `Package-Requires` header to `company-axiom.el` indicating dependencies on `company` and `axiom-environment`.
- The `company-active-map` modifications are unusual: by doing this you'll affect popups for all completions, not just those made using your company backend, which I'm not sure is ideal.

**Comment by pdo** [comment]
Hi Steve,

Thanks for the feedback.  I hadn't thought of your second point -- you're
right, it's not ideal, I'll look into it.

Regards,
Paul

**Comment by pdo** [comment]
Okay, I've removed the questionable code and improved the Package-Requires header, so I think we're good to go now.

Paul

**Comment by purcell** [comment]
Great, thanks!

**Pull request merged**
