### PR TITLE
Add auth-source-1password recipe

### PR DESCRIPTION
**Pull request by dlobraico**
### Brief summary of what the package does

This package provides Emacs [auth-source](https://www.gnu.org/software/emacs/manual/html_mono/auth.html#Top) integration for 1Password using [secret references](https://developer.1password.com/docs/cli/secret-references) and the op command-line tool. It’s handy for use with things like smtpmail and other Emacs packages which expect to be able to lookup login credentials. It should be a drop-in replacement for the default auth-info source.

### Direct link to the package repository

https://github.com/dlobraico/auth-source-1password

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I'm just using the builtin `auth-source-pass` for guidance on conventions, but should the `:type` in `auth-source-1password-backend` be `'password-store` instead of `'1password`?  Similarly a more suitable `:group` for `auth-source-1password` would be `auth-source`

**Comment by riscy** [comment]
Friendly ping on these (small) changes. :)

**Comment by dlobraico** [comment]
So sorry for the delay! Missed the original notification it seems. 

Thanks for these points -- should both be fixed as of https://github.com/dlobraico/auth-source-1password/commit/7bb8ad3507c58cc642b2ebbd7e57a91efab80e14.

**Comment by riscy** [comment]
No trouble - thanks again and welcome to MELPA. :)

**Pull request merged**
