### PR TITLE
Add hierarchy

### PR DESCRIPTION
**Pull request by DamienCassou**
### Brief summary of what the package does

Library to create, query, navigate and display hierarchy
  structures.

### Direct link to the package repository

http://github.com/DamienCassou/hierarchy

### Your association with the package

package maintainer

### Relevant communications with the upstream package maintainer

n/a

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, looks great!

Just one small thing: rather that specifying a `:files` spec, can I suggest you move the example `.el` file into an `examples` subdirectory in your repo?

**Comment by alphapapa** [comment]
This looks really interesting!  The readme is really good!  The only thing that could make it better is if you had some example use cases (other than the hypothetical animal kingdom one ;).

**Comment by purcell** [comment]
Merci Damien!

**Comment by DamienCassou** [comment]
Thank you both for the feedback.

> can I suggest you move the example .el file into an examples subdirectory in your repo?

done

> had some example use cases

done. Please tell me what you think.

**Comment by alphapapa** [comment]
Thanks, that helps some.  I guess I'm just a novice, but I don't understand the `parentfn` API for building the hierarchy.  It seems like an awkward way of passing the same information that a simple list of lists would have.  I'm assuming there's an academic or theoretical basis that is way over my head, but not knowing that makes it hard for me to understand how and when I would use this library.  This is just FYI, not a complaint.  :)

**Comment by DamienCassou** [comment]
@alphapapa thanks for the discussion. Could you please copy/paste this text to a new issue at http://github.com/DamienCassou/hierarchy so we can discuss it there? I think it's worth thinking and talking about it.

**Comment by DamienCassou** [comment]
Thanks for merging Steve (and thanks for saying "Merci" in French :-)).

**Pull request merged**
