### PR TITLE
Add `tldr-lint` extension recipe

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
### Brief summary of what the package does

Extension providing IDE-like features for TlDr pages.

### Direct link to the package repository

https://github.com/tldr-pages/tldr-emacs-extension

### Your association with the package

Author, maintainer

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [ ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
> Debugger entered--Lisp error: (cl-assertion-failed ((string= (symbol-name ident) name) "Recipe '%s' contains mismatched package name '%s'"))

Should I rename my `flymake-tldr-lint.el` to `tldr-lint.el`?

**Comment by tarsius** [comment]
You have to change the name of the recipe file from `tldr-lint.el` to `tldr-lint`.

**Comment by EmilySeville7cfg** [comment]
> Debugger entered--Lisp error: (cl-assertion-failed ((not (plist-get plist :url)) nil "https://github.com/tldr-pages/tldr-emacs-extension"))

I don't figure out what have I do now?

**Comment by tarsius** [comment]
The recipe file should be named `flymake-tldr-lint` and contain:

```
(flymake-tldr-lint
 :fetcher github
 :repo "tldr-pages/tldr-emacs-extension")
```

**Comment by EmilySeville7cfg** [comment]
Is it right that MELPA will automatically detect when new versions (commits marked with `vX.Y`) are available?

**Comment by milkypostman** [comment]
The version detection is true for _tags_ but for regular MELPA, version numbers are currently generated based on commit timestamps.

**Comment by riscy** [comment]
Thanks all for getting the recipe ready.  Quick first pass --

`flymake-tldr-lint.el` with byte-compile using Emacs 28.1:
```
flymake-tldr-lint.el:65:8: Warning: docstring wider than 80 characters
In tldr-remove-broken-files:
flymake-tldr-lint.el:74:8: Warning: docstring wider than 80 characters
In tldr-remove-broken-directories:
flymake-tldr-lint.el:84:8: Warning: docstring wider than 80 characters
In tldr-correct-broken-ellipsis:
flymake-tldr-lint.el:103:8: Warning: docstring wider than 80 characters
In tldr-correct-broken-numbers:
flymake-tldr-lint.el:112:8: Warning: docstring wider than 80 characters
In tldr-correct-broken-files:
flymake-tldr-lint.el:121:8: Warning: docstring wider than 80 characters
In tldr-correct-broken-directories:
flymake-tldr-lint.el:131:8: Warning: docstring wider than 80 characters
In tldr-correct-broken-ranges:
flymake-tldr-lint.el:141:8: Warning: docstring wider than 80 characters
```
Some rephrasing can fix these.  For example 
```elisp
  "Replace {{dir}}, {{dirname}}, {{dir_name}}, {{directory}}, {{directoryname}}, and {{directory_name}} placeholders with {{path/to/directory}} in the current buffer.
```
could become something like:
```elisp
  "Replace directory placeholders in current buffer.
In particular, replace {{dir}}, {{dirname}}, {{dir_name}},
{{directory}}, {{directoryname}}, and {{directory_name}}
placeholders with {{path/to/directory}} in the current buffer.
Trailing numbers are respected too."
```

`flymake-tldr-lint.el` with checkdoc 0.6.2:
```
flymake-tldr-lint.el:35: First line should be capitalized
flymake-tldr-lint.el:50: Argument `pattern' should appear (as PATTERN) in the doc string
flymake-tldr-lint.el:75: Some lines are over 80 columns wide
flymake-tldr-lint.el:85: Some lines are over 80 columns wide
flymake-tldr-lint.el:122: Some lines are over 80 columns wide
flymake-tldr-lint.el:132: Some lines are over 80 columns wide
flymake-tldr-lint.el:197: First line should be capitalized
```
Rephrasing can help with the capitalization nag here too.

`flymake-tldr-lint.el` with package-lint 20221003.1636:
```
42 issues found:
1:0: error: Package should have a Homepage or URL header.
49:0: error: "replace-regexp-entire-buffer" doesn't start with package's prefix "flymake-tldr-lint".
56:0: error: "tldr-remove-broken-ellipsis" doesn't start with package's prefix "flymake-tldr-lint".
62:2: warning: Closing parens should not be wrapped onto new lines.
63:0: warning: Closing parens should not be wrapped onto new lines.
65:0: error: "tldr-remove-broken-numbers" doesn't start with package's prefix "flymake-tldr-lint".
71:2: warning: Closing parens should not be wrapped onto new lines.
72:0: warning: Closing parens should not be wrapped onto new lines.
74:0: error: "tldr-remove-broken-files" doesn't start with package's prefix "flymake-tldr-lint".
81:2: warning: Closing parens should not be wrapped onto new lines.
82:0: warning: Closing parens should not be wrapped onto new lines.
84:0: error: "tldr-remove-broken-directories" doesn't start with package's prefix "flymake-tldr-lint".
91:2: warning: Closing parens should not be wrapped onto new lines.
92:0: warning: Closing parens should not be wrapped onto new lines.
94:0: error: "tldr-remove-broken-all" doesn't start with package's prefix "flymake-tldr-lint".
101:0: warning: Closing parens should not be wrapped onto new lines.
103:0: error: "tldr-correct-broken-ellipsis" doesn't start with package's prefix "flymake-tldr-lint".
109:2: warning: Closing parens should not be wrapped onto new lines.
110:0: warning: Closing parens should not be wrapped onto new lines.
112:0: error: "tldr-correct-broken-numbers" doesn't start with package's prefix "flymake-tldr-lint".
118:2: warning: Closing parens should not be wrapped onto new lines.
119:0: warning: Closing parens should not be wrapped onto new lines.
121:0: error: "tldr-correct-broken-files" doesn't start with package's prefix "flymake-tldr-lint".
128:2: warning: Closing parens should not be wrapped onto new lines.
129:0: warning: Closing parens should not be wrapped onto new lines.
131:0: error: "tldr-correct-broken-directories" doesn't start with package's prefix "flymake-tldr-lint".
138:2: warning: Closing parens should not be wrapped onto new lines.
139:0: warning: Closing parens should not be wrapped onto new lines.
141:0: error: "tldr-correct-broken-ranges" doesn't start with package's prefix "flymake-tldr-lint".
151:2: warning: Closing parens should not be wrapped onto new lines.
152:0: warning: Closing parens should not be wrapped onto new lines.
154:0: error: "tldr-correct-broken-long-option-argument" doesn't start with package's prefix "flymake-tldr-lint".
160:2: warning: Closing parens should not be wrapped onto new lines.
161:0: warning: Closing parens should not be wrapped onto new lines.
163:0: error: "tldr-correct-broken-all" doesn't start with package's prefix "flymake-tldr-lint".
172:0: warning: Closing parens should not be wrapped onto new lines.
174:0: error: "tldr-convert-long-option-space-separated" doesn't start with package's prefix "flymake-tldr-lint".
182:2: warning: Closing parens should not be wrapped onto new lines.
183:0: warning: Closing parens should not be wrapped onto new lines.
185:0: error: "tldr-convert-long-option-equal-sign-separated" doesn't start with package's prefix "flymake-tldr-lint".
193:2: warning: Closing parens should not be wrapped onto new lines.
194:0: warning: Closing parens should not be wrapped onto new lines.
```
Most of these look legitimate and should be pretty rote to fix.  Feel free to reach out if you need help.

`flymake-tldr-lint.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- flymake-tldr-lint.el#L250: It's safer to sharp-quote function names; use `#'`
- flymake-tldr-lint.el#L6: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
```

License clash (the repo is licensed with MIT but the source file has GPL boilerplate):
- MIT License (via API)
- GPL* -- flymake-tldr-lint.el: A TlDr Flymake backend powered by tldr-lint

**Comment by EmilySeville7cfg** [comment]
> License clash (the repo is licensed with MIT but the source file has GPL boilerplate):
>
>    MIT License (via API)
>    GPL* -- flymake-tldr-lint.el: A TlDr Flymake backend powered by tldr-lint

Do you mean that I have to change my license to GNU GPL as long as `tldr-lint` license?

**Comment by EmilySeville7cfg** [comment]
> flymake-tldr-lint.el:50: Argument `pattern' should appear (as PATTERN) in the doc string
flymake-tldr-lint.el:57: First line is not a complete sentence

But why? It [is](https://github.com/tldr-pages/tldr-emacs-extension/blob/main/flymake-tldr-lint.el#L50): `"Perform regular-expression replacement throughout buffer."`. I can't figure out what is complete sentence format then.

Is it okay to include parameters in doc string as follows?

```emacs
(defun flymake-tldr-lint--replace-regexp-entire-buffer (pattern replacement)
  "Perform regular-expression replacement throughout buffer.

pattern: pattern to search
replacement: replacement for pattern"
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward pattern nil t)
      (replace-match replacement))))
```

**Comment by EmilySeville7cfg** [comment]
Issues were [fixed](https://github.com/tldr-pages/tldr-emacs-extension/pull/26) here.

**Comment by riscy** [comment]
Thank you!  Beyond that license nag (licensee is detecting your repo as "Other" licensed instead of GPL licensed) here's the latest:

`flymake-tldr-lint.el` with byte-compile using Emacs 28.1:
```
flymake-tldr-lint.el:286:15: Warning: the function
    `flymake-diagnostic-functions' is not known to be defined.
```

This arose because of the sharp-quoting but it's a good thing, because `flymake-diagnostic-functions` is a variable that doesn't support hooks; instead it's a list that should be added to.

**Comment by EmilySeville7cfg** [comment]
If you know how to fix license I am glad to approve your PR in my extension repo. :)

**Comment by tarsius** [comment]
> If you know how to fix license

```
rm LICENSE
curl https://www.gnu.org/licenses/gpl-3.0.txt -o LICENSE
git add LICENSE
```

**Comment by EmilySeville7cfg** [comment]
> This arose because of the sharp-quoting but it's a good thing, because flymake-diagnostic-functions is a variable that doesn't support hooks; instead it's a list that should be added to.

Is it the correct fix: `(add-hook #'flymake-diagnostic-functions #'flymake-tldr-lint--backend nil t)`?

**Comment by riscy** [comment]
Ages ago I had a professor whose automatic response would've been "try it and see" and that's what I recommend here.  Your function `flymake-tldr-lint-load` is probably not working as you intend -- make sure you can confirm that.  And then if you attempt your fix above, you'll be able to confirm that won't work either.

Since `flymake-diagnostic-functions` is a list, you probably want to use `add-to-list`.

**Comment by riscy** [comment]
Apologies - I confused myself and ended up thinking that we were talking about advice instead of a hook.  The form you have now is correct - the sharp-quoting should only apply to `#'flymake-tldr-lint--backend`.  I hope that didn't waste too much of your time.

Here's the latest --

`flymake-tldr-lint.el` with byte-compile using Emacs 28.1:
```
flymake-tldr-lint.el:243:40: Warning: assignment to free variable `result'
flymake-tldr-lint.el:243:40: Warning: reference to free variable `result'
flymake-tldr-lint.el:236:29: Warning: assignment to free variable `old-result'
flymake-tldr-lint.el:241:39: Warning: reference to free variable `old-result'
```

`flymake-tldr-lint.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- flymake-tldr-lint.el#L208: No `format` required; `error` takes an f-string
```

Package and license:
- Other (via API)
  - Try to use a standard license file format

**Comment by EmilySeville7cfg** [comment]
It's strange - I've already followed instructions above to replace my license with a standard one.

**Comment by riscy** [comment]
I'm not sure about the environment in which you're running Docker, so I don't think I can help much with that.  melpazoid can also run in CI (e.g. GitHub actions) and if you see such failures in that environment let me know -- that would be much easier for me to debug.

It looks like GitHub is correctly interpreting your license as of at least today, so that issue is behind us (maybe it took a while for their backend to pick up the change you made).

Here are the automatically detected issues that are still salient:

`flymake-tldr-lint.el` with byte-compile using Emacs 28.1:
```
flymake-tldr-lint.el:243:40: Warning: assignment to free variable `result'
flymake-tldr-lint.el:243:40: Warning: reference to free variable `result'
flymake-tldr-lint.el:236:29: Warning: assignment to free variable `old-result'
flymake-tldr-lint.el:241:39: Warning: reference to free variable `old-result'
```
I think these are all because you should be `let`-binding `result`, instead of using `setq` on it; this also keeps that variable from littering the global namespace.

`flymake-tldr-lint.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- flymake-tldr-lint.el#L208: No `format` required; `error` takes an f-string
```

**Comment by EmilySeville7cfg** [comment]
All mentioned issues were fixed in already mentioned PR above in my last comment (code clean up will be done later). I was waiting when melpaziod stop complaining about wrong license... As I didn't want to wait forever I can merge that PR and u can check code flaws again. Please report issue to melpaziod if issue with licensing is still actual. I have no proper internet connection to do it myself. Sorry for inconvenience. It is the worst licensing experience I've ever had.

**Comment by EmilySeville7cfg** [comment]
All mentioned issues were fixed in already mentioned PR above in my last comment (code clean up will be done later). I was waiting when melpaziod stop complaining about wrong license... As I didn't want to wait forever I can merge that PR and u can check code flaws again. Please report issue to melpaziod if issue with licensing is still actual. I have no proper internet connection to do it myself. Sorry for inconvenience. It is the worst licensing experience I've ever had.

**Comment by riscy** [comment]
> Please report issue to melpaziod if issue with licensing is still actual. It is the worst licensing experience I've ever had.

I think the issue was that GitHub itself was slow to resolve the license - apologies for the bad experience you're having and the mistake I made above.  (melpazoid is my own tool, so the good news is I'm aware what this happened. :)

Here's the latest:

`flymake-tldr-lint.el` with byte-compile using Emacs 28.1:
```
flymake-tldr-lint.el:230:25: Warning: global/dynamic var `result' lacks a
    prefix
```

`flymake-tldr-lint.el` with checkdoc 0.6.2:
```
flymake-tldr-lint.el:208: Error messages should *not* end with a period
```

`flymake-tldr-lint.el` with package-lint 20221003.1636:
```
2 issues found:
227:0: error: "result" doesn't start with package's prefix "flymake-tldr-lint".
228:0: error: "old-result" doesn't start with package's prefix "flymake-tldr-lint".
```

These look like they're also because you need to `let`-bind result and `old-result`.  I would change this particular section from:
```elisp
    (defvar result nil)
    (defvar old-result nil)
    (dotimes (i (length new-descriptions)) ;; building descriptions with new mnemonics
      (dolist (option (elt option-lists i))
        (setq result (elt new-descriptions i))
        (setq old-result result)
        ...
```
to
```
    (let (result old-result)
      (dotimes (i (length new-descriptions))  ; building descriptions with new mnemonics
        (dolist (option (elt option-lists i))
          (setq result (elt new-descriptions i))
          (setq old-result result)
          ...
```
(notice also how I changed the end-of-line comment to use `;` instead of `;;` which is conventional for elisp.

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to reach out.

**Comment by EmilySeville7cfg** [comment]
> I'll mark this awaiting-upstream for now, but feel free to reach out.

Thanks for reminding me about this recipe. :) I'm gonna fix extension sooner.

**Comment by EmilySeville7cfg** [comment]
@riscy, this PR can be closed. I don't support this extension any more. You can review other my PRs. Thanks for understanding and sorry for wasting your time.

**Pull request closed without merging**
