### PR TITLE
Add recipe welcome-dashboard

### PR DESCRIPTION
**Pull request by konrad1977**
### Brief summary of what the package does

A simple dashboard for Emacs. Clutter free and focus on what's important.

### Direct link to the package repository

https://github.com/konrad1977/welcome-dashboard

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)

MIT Licence? Do I need to update the license to GPL?

- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
You package file should be `welcome-dashboard.el` and not `welcome.el`.

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`welcome-dashboard.el` with byte-compile using Emacs 28.1:
```
welcome-dashboard.el:18:1: Error: Cannot open load file: No such file or directory, all-the-icons
```
Missing a `Package-Requires` entry I believe.

`welcome-dashboard.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- welcome-dashboard.el#L476: Quoting this lambda may prevent it from being compiled
- welcome-dashboard.el#L331: It's safer to sharp-quote function names; use `#'`
- welcome-dashboard.el#L333: It's safer to sharp-quote function names; use `#'`
- welcome-dashboard.el#L333: It's safer to sharp-quote function names; use `#'`
- welcome-dashboard.el#L377: It's safer to sharp-quote function names; use `#'`
- welcome-dashboard.el#L378: It's safer to sharp-quote function names; use `#'`
- welcome-dashboard.el#L8: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- welcome-dashboard.el#L524: Consider using %R instead of %H:%M in time strings
```

Package and license:
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to welcome-dashboard.el

**Comment by konrad1977** [comment]
Thanks. Ill update.

**Comment by konrad1977** [comment]
Updated. 
- Changed license to GPL
- Added package-requires for async and all-the-icons. Do I need to do the same for built in packages?
- Changed to version instead of package-version.
- Changed time formatter to %R.

I checked with 'package-lint-buffer' and 'checkdoc' but how did you get the other warnings because I don't get any?

**Comment by riscy** [comment]
> I checked with 'package-lint-buffer' and 'checkdoc' but how did you get the other warnings because I don't get any?

Those are "extra" checks I run as part of melpazoid (linked above), gathering some of the small advice and/or common suggestions that I'm able to automate.

Here's the latest --

`welcome-dashboard.el` with byte-compile using Emacs 28.1:
```
welcome-dashboard.el:535:14: Warning: reference to free variable
    `package-activated-list'
In end of data:
welcome-dashboard.el:450:20: Warning: the function `nerd-icons-codicon' is not
    known to be defined.
welcome-dashboard.el:435:35: Warning: the function
    `all-the-icons-octicon-family' is not known to be defined.
welcome-dashboard.el:340:18: Warning: the function `all-the-icons-octicon' is
    not known to be defined.
welcome-dashboard.el:338:20: Warning: the function `nerd-icons-octicon' is not
    known to be defined.
welcome-dashboard.el:312:18: Warning: the function
    `all-the-icons-icon-for-file' is not known to be defined.
welcome-dashboard.el:311:21: Warning: the function `nerd-icons-icon-for-file'
    is not known to be defined.
welcome-dashboard.el:223:8: Warning: the function
    `all-the-icons-icon-for-weather' is not known to be defined.
welcome-dashboard.el:207:10: Warning: the function `nerd-icons-wicon' is not
    known to be defined.
```
Free variables can be sorted out with defvars, e.g. `(defvar package-activated-list)`; use `declare-function` to do bookkeeping on functions that the byte-compiler doesn't know about (and then you can use `check-declare` to ensure on your end that you've correctly matched each pre-declared function with its source file.)

`welcome-dashboard.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- welcome-dashboard.el#L371: It's safer to sharp-quote function names; use `#'`
```
`#'length` in this case.

Package and license:
- Other (via API)
  - Try to use a standard license file format
    See: https://github.com/licensee/licensee
    e.g. https://www.gnu.org/licenses/gpl-3.0.txt (I think you have an HTMLized version in there)
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to welcome-dashboard.el

**Comment by riscy** [comment]
Btw, MIT is a fine license to use if that's your preference.

**Comment by konrad1977** [comment]
I changed to GPL. I usually use MIT for my own projects. Hopefully fixed most of the warnings too.

**Comment by riscy** [comment]
All good re: the choice of license, although you will see below that your LICENSE file (or equivalent) is not machine-readable, and your source file needs license boilerplate as well.  Here's the latest --

`welcome-dashboard.el` with byte-compile using Emacs 28.1:
```
welcome-dashboard.el:535:14: Warning: reference to free variable
    `package-activated-list'
In end of data:
welcome-dashboard.el:450:20: Warning: the function `nerd-icons-codicon' is not
    known to be defined.
welcome-dashboard.el:435:35: Warning: the function
    `all-the-icons-octicon-family' is not known to be defined.
welcome-dashboard.el:340:18: Warning: the function `all-the-icons-octicon' is
    not known to be defined.
welcome-dashboard.el:338:20: Warning: the function `nerd-icons-octicon' is not
    known to be defined.
welcome-dashboard.el:312:18: Warning: the function
    `all-the-icons-icon-for-file' is not known to be defined.
welcome-dashboard.el:311:21: Warning: the function `nerd-icons-icon-for-file'
    is not known to be defined.
welcome-dashboard.el:223:8: Warning: the function
    `all-the-icons-icon-for-weather' is not known to be defined.
welcome-dashboard.el:207:10: Warning: the function `nerd-icons-wicon' is not
    known to be defined.
```

`welcome-dashboard.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- welcome-dashboard.el#L371: It's safer to sharp-quote function names; use `#'`
```

Package and license:
- Other (via API)
  - Try to use a standard license file format
    See: https://github.com/licensee/licensee
    e.g. https://www.gnu.org/licenses/gpl-3.0.txt
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to welcome-dashboard.el

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to reach out.

**Comment by konrad1977** [comment]
I'll try to find time to fix the issues. It's a bit hard because I am relative new to Emacs and Emacs lisp.

**Comment by riscy** [comment]
Friendly ping - if there is anything in particular you're stuck on, I might be able to help out.

**Comment by progfolio** [comment]
@konrad1977 has indicated they'll finish this when they have the time:
https://github.com/konrad1977/welcome-dashboard/issues/1#issuecomment-1871855285

**Comment by riscy** [comment]
This has been over a year - I'll close for now, but feel free to reopen when ready.

**Pull request closed without merging**
