### PR TITLE
Add recipe for ruff-format

### PR DESCRIPTION
**Pull request by scop**
### Brief summary of what the package does

Format Python source with [Ruff](https://docs.astral.sh/ruff/).

### Direct link to the package repository

https://github.com/scop/emacs-ruff-format

### Your association with the package

Maintainer, user.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by scop** [comment]
Caveat: for `package-install-file` I get `Package "reformatter-0.3" is unavailable`. Not sure what's up with that; the dependency seems to be the same in just about all reformatter derived formatter packages around. I'm personally using `straight.el` and haven't really ever looked into `package.el`. I _guess_ this is not a problem -- if I'm wrong, some hand holding needed :)

**Comment by riscy** [comment]
I'm not able to reproduce the issue with installing reformatter, so I suspect we're in the clear.

You are probably aware of [blacken](https://github.com/pythonic-emacs/blacken) and it may be worth making a comparison there. (For instance, blacken has a `blacken-skip-string-normalization` customizable while you have a `ruff-format-command` customizable which can serve the same function).  I think the use of reformatter makes things ultra succinct on your end, though.

**Comment by purcell** [comment]
> Caveat: for package-install-file I get Package "reformatter-0.3" is unavailable. Not sure what's up with that; the dependency seems to be the same in just about all reformatter derived formatter packages around. I'm personally using straight.el and haven't really ever looked into package.el.

You'd need to have MELPA Stable (or regular MELPA) set up as a package source for `reformatter` to appear installable to `package.el`, so you can't really test `package-install-file` with things installed via `straight`.

**Comment by scop** [comment]
Thanks for helping with this! However, I unfortunately only now became aware of apheleia, and that it already has support for formatting with ruff (as well as a number of other things).

I'd rather not add more stuff to take care of the same thing, so what do you think, would it be possible to remove this mode from MELPA for a bit still, while I evaluate whether I'll be using apheleia myself and thus would not have use for this package after all (in that case it would be unmaintained unless someone else picks it up).

**Pull request merged**
