### PR TITLE
Add lsp-intellij

### PR DESCRIPTION
**Pull request by Ruin0x11**
### Brief summary of what the package does

Provides client support for [lsp-intellij-server](https://github.com/Ruin0x11/intellij-lsp-server), in the same vein as other `lsp-mode` packages.

### Direct link to the package repository

https://github.com/Ruin0x11/lsp-intellij

### Your association with the package

Package creator.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks.
- The recipe says "lsp-rust": how did this work locally when you built and installed the package?
- Don't require `cl` - use `cl-lib` instead.
- Prefer `(unless x ...)` to `(when (not x) ...)`
- Avoid "Emacs client for" in the package description: all Emacs packages are for Emacs. Perhaps just "Client for ...".

**Comment by Ruin0x11** [comment]
I fixed things.

**Comment by Ruin0x11** [comment]
Any updates?

**Comment by Ruin0x11** [comment]
@purcell: I added various changes, could I please receive feedback?

**Comment by DamienCassou** [comment]
Some feedback:

- Please run linters specified in CONTRIBUTING.md. They would have told you about:
  - the `Keywords` are incorrect (you have to pick keywords from a list)
  - you have problematic dostrings (e.g., the one of `use-topmost-maven-root` doesn't have a complete sentence on first line, the one `root-top-down-recurring` is longer than 80 characters, the one of `set-config` and `set-temporary-directories` don't reference their arguments)
- please use cl-lib instead of cl
- `file-name` is usually spelled `filename`
- please prefer `expand-file-name` over `concat` to manipulate paths
- instead of using `setenv` which modifies the global environment, you might want to prepend the environment variable in `command`: e.g., (untested) `(compile (format "CLASSPATH=%s %s" (gethash "classpath" command) command-str))`

**Comment by Ruin0x11** [comment]
Ah, that helps, thank you. The issue the environment setting was supposed to solve was the command line being too long if you put the whole classpath on it. I'll see if this works.

**Comment by Ruin0x11** [comment]
I merged some changes, let me know of any issues.

**Comment by purcell** [comment]
Looks good - merging now. Welcome to MELPA! :tada:

**Comment by Ruin0x11** [comment]
Thank you.

**Pull request merged**
