### PR TITLE
add recipe eldoc-overlay-mode

### PR DESCRIPTION
**Pull request by stardiviner**
### Brief summary of what the package does

[Please write a quick summary of the package.]

### Direct link to the package repository

https://github.com/stardiviner/eldoc-overlay-mode

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed***

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- No autoload cookie
- `eldoc-message-function` was introduced at Emacs 24.4. But this package requires Emacs 24.3 or higher versions
- Minor mode lighter should start with space
- URL repository is wrong

**Comment by purcell** [comment]
Additionally, don't define a face with only one of `:background` and `:foreground`. You should always provide both, and ideally two versions for dark and light background classes. Often the best choice is to `:inherit` a built-in face by default, then the user (or themes) can override the face as desired.

**Comment by stardiviner** [comment]
I have updated my code, fixed all of upper issues. Thanks for your reviews.

**Comment by syohex** [comment]
Merged

**Pull request merged**
