### PR TITLE
Add fuzzy-finder recipe

### PR DESCRIPTION
**Pull request by 10sr**
### Brief summary of what the package does

Fuzzy Finder App Integration

`fuzzy-finder` command opens a new window, starts a fuzzy finder process inside of it, and then calls a function with selected items. By default it visits selected files.

### Direct link to the package repository

https://github.com/10sr/fuzzy-finder-el

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This looks cool.  Can you comment on the novelty/difference between this and the existing fzf package?

I think it would be good to add 'fzf' somewhere in your `;;; Commentary` or package summary, since people searching for "fzf" would then be able to discover this package, too.

Beyond this, code and checklist look good -- thanks.

**Comment by 10sr** [comment]
Thanks for reviewing!

fzf.el depends on fzf's `--print-query` argument ([this](https://github.com/bling/fzf.el/blob/master/fzf.el#L64)) so it cannot be used with applications which do not have this (selecta for example). Also, fzf.el does not support multiple item selection and takes only the last item in the output.
This package does not have these limitations.

> I think it would be good to add 'fzf' somewhere in your ;;; Commentary or package summary, since people searching for "fzf" would then be able to discover this package, too.

I added it to Commentary.

**Comment by riscy** [comment]
Thanks!  I'll note this since you may not have compiled yet on Emacs 27.1 -- mostly an fyi:

byte-compile (using Emacs 27.1):
```
fuzzy-finder.el:250:17:Warning: `term-suppress-hard-newline' is an obsolete
    variable (as of 27.1).
```

**Comment by 10sr** [comment]
Thanks 🙌 

> byte-compile (using Emacs 27.1):

I'll check later!

**Pull request merged**
