### PR TITLE
Add recipe for tempel

### PR DESCRIPTION
**Pull request by minad**
### Brief summary of what the package does

Tiny template package, a modernized reimplementation of the Emacs Tempo and Tempo-Snippets template libraries. There are plenty of template/snippet libraries for Emacs. This one is intentionally simple and restricted. The syntax is compatible with the Emacs Tempo syntax. It works well with my [Corfu](https://github.com/minad/corfu) completion UI.

### Direct link to the package repository

https://github.com/minad/tempel

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Very quick first pass over the checklist --

`tempel.el` with package-lint 20211122.1152:
```
2 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
195:0: error: "template--synchronize-fields" doesn't start with package's prefix "tempel".
```

**Comment by minad** [comment]
> 2 issues found: 1:0: warning: Including "Emacs" in the package summary is usually redundant. 195:0: error: "template--synchronize-fields" doesn't start with package's prefix "tempel".

Interesting. I have flymake package-lint setup and it does not warn me.

**Comment by minad** [comment]
@riscy Fixed in https://github.com/minad/tempel/commit/460f8fe8068e111820159071678c4b3845eb56cb.

**Comment by minad** [comment]
@riscy Just fyi, Tempel has been added to [GNU ELPA](http://elpa.gnu.org/packages/tempel.html), but I'd still like to also publish it via MELPA for multiple reasons: Visibility, since I like MELPA and since interested users get quicker access to the lastest version via the nightly MELPA builds and provide feedback earlier. In contrast, almost nobody uses ELPA-devel. Most of my packages live on both ELPA and MELPA.

**Comment by riscy** [comment]
Thank you!

**Pull request merged**
