### PR TITLE
Add recipe: astute

### PR DESCRIPTION
**Pull request by rnkn**
### Brief summary of what the package does

A simple Emacs minor mode to redisplay ASCII punctuation as typographic (or "smart") punctuation without altering file contents.

The following characters are redisplayed:

- `''` -> ‘’ (single quotes)
- `""` -> “” (double quotes)
- `--` -> – (en dash)
- `---` -> — (em dash)

Accounts for special cases such as '90s and 'cause.

### Direct link to the package repository

https://github.com/rnkn/astute

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by ErikPrantare** [comment]
Do you know about `prettify-symbols-mode`?  It is built in and seems to overlap in part with your package.

Also, would the following line not also remove any text display properties provided by other packages when disabling the mode? https://github.com/rnkn/astute/blob/ef0258bee2835f34090357f0f3b805ac3d20e67f/astute.el#L148

**Comment by rnkn** [comment]
> Do you know about `prettify-symbols-mode`? It is built in and seems to overlap in part with your package.

@ErikPrantare `prettify-symbols-mode` works by redisplaying strings as characters, whereas to redisplay smart punctuation you need to use regexps.

> Also, would the following line not also remove any text display properties provided by other packages when disabling the mode? 

Thanks I had forgotten about this. You're right. Will figure out a better way.

**Comment by riscy** [comment]
Thanks both - @rnkn let me know when that's patched.

When we merge this I'm wondering how people will find it by searching.  I feel like there is an overlap here with the notion of ligatures (these are like, what, ad hoc ligatures?) which might provide a useful search keyword - but I'm not sure.

**Comment by meedstrom** [comment]
Nice package. Just FYI, I was curious how it handled edge cases, so I tried the following sentence, and I think the result is not what you intend:

'Twasn't a will-o'the-wisp, 'twas a ne'er-do-well.

**Comment by riscy** [comment]
>  I'd like to support 25.1 but oh well.

It's a laudable goal, but that's an almost 10 year-old piece of software that has been maintained into many newer versions.  I wouldn't count it as a terrible loss!

Thanks again.

**Comment by rnkn** [comment]
Thanks!

**Pull request merged**
