### PR TITLE
Add recipe for anejil

### PR DESCRIPTION
**Pull request by nryotaro**
### Brief summary of what the package does
anejil automatically activates a Python venv with [pyvenv](https://github.com/jorgenschaefer/pyvenv) package.
When you open a file in python-mode, it searches for the venv directory near the file, and activates it.

### Direct link to the package repository

https://github.com/nryotaro/anejil

### Your association with the package

I am the author of the package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi!  Just letting you know I do see this one, but try to limit myself to one PR per author just to distribute time fairly.

**Comment by riscy** [comment]
I feel like this would fit great with the `pyvenv` package itself -- have you considered opening an issue or a PR there?

In the meantime one minor piece of feedback when I look at this is that the package name `anejil` is hard for me to associate with python or pyvenv; this isn't a blocker but could hamper discoverability.

Also minor:
- anejil.el#L81: No `format` required; `message` takes an f-string

**Comment by nryotaro** [comment]
@riscy Thank you for your feedback.

I renamed the name of the package to pyvenv-auto, and removed the function that calls format.

I would like to send a pull request to the pyvenv package repository if this package would get popular.

**Comment by riscy** [comment]
Looks good!

**Pull request merged**
