### PR TITLE
Add recipe for org-notify

### PR DESCRIPTION
**Pull request by jgkamat**
### Brief summary of what the package does

`org-notify` provides notifications using categories to org files.

There are already several org notifications packages in melpa (org-notifications, org-wild-notifier, org-alert) but I think this package should be added to melpa anyway as:

1. This package was packaged via org-contrib for a long time, [but isn't anymore](https://git.sr.ht/~bzg/org-contrib/commit/c6aef31ccfc7c4418c3b51e98f7c3bd8e255f5e6)
2. The other packages are focused at either sending notifications on a schedule/deadline time, or at a manually specified number of minutes before said time. Org-notify lets you specify a property (for example "dr-appt") to attach to an entry, and specify a schedule for notifications according to that property (in this case, a low priority notification 10 days before, medium 5 days before, and urgent 1 hour before deadline). I find that this feature set is more powerful than the existing packages and cannot be replaced by them.

### Direct link to the package repository

https://github.com/p-m/org-notify

### Your association with the package

I am a user of org-notify - the maintainer is still active, but is a little busy at the minute.

### Relevant communications with the upstream package maintainer

https://github.com/p-m/org-notify/issues/4#issuecomment-1175808821
https://github.com/p-m/org-notify/pull/5

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback 
  - (I have addressed all but one - there is a non standard separator but I do not want to change it to avoid backwards compatibility issues at the moment).
- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings 
  - (I haven't tackled this yet - I wanted to minimize changes if possible before submitting)
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`org-notify.el` with checkdoc 0.6.2:
```
org-notify.el:120: First line is not a complete sentence
org-notify.el:120: Argument `orig' should appear (as ORIG) in the doc string
org-notify.el:128: Argument `heading' should appear (as HEADING) in the doc string
org-notify.el:145: Lisp symbol `org-agenda' should appear in quotes
org-notify.el:160: First line is not a complete sentence
org-notify.el:160: Argument `diff' should appear (as DIFF) in the doc string
org-notify.el:167: First line is not a complete sentence
org-notify.el:234: Lisp symbol `org-agenda' should appear in quotes
org-notify.el:235: Name emacs should appear capitalized as Emacs
org-notify.el:253: Argument `plist' should appear (as PLIST) in the doc string
org-notify.el:280: Argument `id' should appear (as ID) in the doc string
org-notify.el:285: Argument `button' should appear (as BUTTON) in the doc string
org-notify.el:292: Argument `buffer' should appear (as BUFFER) in the doc string
org-notify.el:299: Argument `id' should appear (as ID) in the doc string
org-notify.el:303: Argument `plist' should appear (as PLIST) in the doc string
org-notify.el:308: Argument `plist' should appear (as PLIST) in the doc string
org-notify.el:314: Argument `plist' should appear (as PLIST) in the doc string
org-notify.el:325: Argument `plist' should appear (as PLIST) in the doc string
org-notify.el:333: First line is not a complete sentence
org-notify.el:350: Argument `plist' should appear (as PLIST) in the doc string
org-notify.el:384: Argument `plist' should appear (as PLIST) in the doc string
org-notify.el:398: First line is not a complete sentence
org-notify.el:398: Argument `plist' should appear (as PLIST) in the doc string
org-notify.el:399: Name emacs should appear capitalized as Emacs
```
I realize you mentioned in your commentary you wanted to minimize changes so you're probably already aware of these.  Are you okay with fixing these up now that we're in the midst of submission?

`org-notify.el` with package-lint 20220607.738:
```
1 issue found:
397:0: error: `org-notify-action-notify/window' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
```
This may be a good chance to fix this nonstandard separator; you could declare the old version of the function deprecated.

`org-notify.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- org-notify.el#L3: Have you done the paperwork to assign this copyright?
```
Since this was split off org I'm assuming that the copyright is still the FSF's.  If someone's already gone through the trouble, it may (also) be easy to get this package added to ELPA which could make distribution even easier.  Not a blocker, just fyi.

Package and license:
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by jgkamat** [comment]
Sure, I can work on these, although it might take a while (I'm currently on vacation, so I'll try to address these in around 2 weeks). I think the main problem with ELPA is that the sources currently live on github, rather than in the elpa git repository - that was why this package was removed from org-contrib. Since the primary maintainer has kept this repo, I assume they want to remain on github for now. Any thoughts on ELPA @p-m? Otherwise, I'll continue on with this, just on a slight delay

**Comment by riscy** [comment]
Sounds good to me.  Feel free to ping if any more questions come up. :)

**Comment by p-m** [comment]
On Tue, Jul 12 2022, Jay Kamat wrote:

> that was why this package was removed from org-contrib.

Oh, I didn't know, that this was the reason. I got a message, that all
files in org-contrib were removed...


> Any thoughts on ELPA @p-m?

I don't know ELPA, but I can try to move there, if it's useful.

-- 
           Peter

**Comment by riscy** [comment]
MELPA's is probably the better choice if you want to stay on GitHub.

**Comment by jgkamat** [comment]
After a bit of discussion, we were able to put org-notify onto elpa - so this pull is redundant - thanks for the feedback regardless! It turns out elpa can now pull from an arbitrary upstream (incl. github).
https://elpa.gnu.org/packages/org-notify.html

**Comment by p-m** [comment]
On Tue, Jul 12 2022, Jay Kamat wrote:

> that was why this package was removed from org-contrib.

Oh, I didn't know, that this was the reason. I got a message, that all
files in org-contrib were removed...


> Any thoughts on ELPA @p-m?

I don't know ELPA, but I can try to move there, if it's useful.

-- 
           Peter

**Comment by jgkamat** [comment]
Sorry for the confusion here - your package is on elpa at the moment already - 
so I don't think there's anything else that needs to be done!

https://elpa.gnu.org/packages/org-notify.html

**Comment by p-m** [comment]
Hi,
My last message is a Github bug. It was already sent on July the 16th.
I'll delete it.  You can delete your message too.
Cheers, Peter

**Pull request closed without merging**
