### PR TITLE
Add recipe for pip-frame

### PR DESCRIPTION
**Pull request by mz-pdm**
### Brief summary of what the package does

Display and manage a PIP frame.

### Direct link to the package repository

https://git.zamazal.org/pdm/pip-frame

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

I'm the upstream package maintainer.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Very quick first pass --

`pip-frame.el` with checkdoc 0.6.2:
```
pip-frame.el:38: You should have a section marked ";;; Code:"
pip-frame.el:83: All variables and subroutines might as well have a documentation string
pip-frame.el:90: All variables and subroutines might as well have a documentation string
pip-frame.el:109: All variables and subroutines might as well have a documentation string
pip-frame.el:112: All variables and subroutines might as well have a documentation string
pip-frame.el:132: All variables and subroutines might as well have a documentation string
pip-frame.el:139: All variables and subroutines might as well have a documentation string
pip-frame.el:186: All variables and subroutines might as well have a documentation string
pip-frame.el:191: All variables and subroutines might as well have a documentation string
pip-frame.el:197: All interactive functions should have documentation
pip-frame.el:201: All interactive functions should have documentation
pip-frame.el:205: All interactive functions should have documentation
pip-frame.el:209: All interactive functions should have documentation
```

`pip-frame.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- pip-frame.el#L6: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
```

**Comment by mz-pdm** [comment]
> pip-frame.el:38: You should have a section marked ";;; Code:"

I've always been wondering what it is good for but added to silence this.

> pip-frame.el:83: All variables and subroutines might as well have a documentation string
> pip-frame.el:90: All variables and subroutines might as well have a documentation string
> pip-frame.el:109: All variables and subroutines might as well have a documentation string
> pip-frame.el:112: All variables and subroutines might as well have a documentation string
> pip-frame.el:132: All variables and subroutines might as well have a documentation string
> pip-frame.el:139: All variables and subroutines might as well have a documentation string
> pip-frame.el:186: All variables and subroutines might as well have a documentation string
> pip-frame.el:191: All variables and subroutines might as well have a documentation string

I'm not going to add docstrings to internal entities.

> pip-frame.el:197: All interactive functions should have documentation
> pip-frame.el:201: All interactive functions should have documentation
> pip-frame.el:205: All interactive functions should have documentation
> pip-frame.el:209: All interactive functions should have documentation

Not very useful in these cases but added.

> - pip-frame.el#L6: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)

Changed as suggested.

**Comment by riscy** [comment]
> I've always been wondering what it is good for but added to silence this.

I think it's just defensive.  Here's a simple example:
```elisp
;;; Commentary:

;; Package commentary
;; More package commentary.

;; this require is needed because xyz:
(require 'abc)
```
Now the comment is part of the `;;; Commentary` (as determined by `(lm-commentary)`).

> I'm not going to add docstrings to internal entities.

I understand your sentiment and I've thought about raising an issue to discuss which checkdocs we want to start ignoring.  Whether or not it was intentional, the attitude I get from this comment is offputting for me as a reviewer.  Please don't wear me out. :)

I have good reasons for asking authors to cleanly solve all the warnings and errors indicated in the checklist:
- they're a crude but effective quality control check
- you won't get used to disregarding them out of hand, which could cause you to miss real issues in the future
- in the case of byte-compile warnings and errors, you spare users being distracted by them during installation
- *my being strict about them means I spend less bandwidth trying to negotiate grey areas in a fair and consistent way*

**Comment by mz-pdm** [comment]
> I think it's just defensive. Here's a simple example:

I see, thank you for explanation. So it effectively ends the Commentary: section; I moved the label to the right place then.

> I understand your sentiment and I've thought about raising an issue to discuss which checkdocs we want to start ignoring. Whether or not it was intentional, the attitude I get from this comment is offputting for me as a reviewer. Please don't wear me out. :)

I'm sorry that my comment sounded like that. It was of course not intentional, I was just trying to clarify things for both you and me (there are things I simply missed and there are things that I don't fully understand, not everything in instructions and manuals is crystal clear, and I also apply changes based on this feedback in another package I submitted here to make its future review easier).

As for internal object docstrings, I'm not going to add them because:

- It means a significant amount of initial work.
- It creates maintenance burden for future.
- Such docstrings are completely useless in this package (there is nothing tricky to explain there).
- They are even harmful because they may suggest those objects serve as a stable API or are even intended to be used outside the given source file.

> I have good reasons for asking authors to cleanly solve all the warnings and errors indicated in the checklist:

Sure, these are good reasons and I understand why it's needed. I believe I've addressed everything reported except for the internal object docstrings as explained above and which I hope is not a real problem and/or blocker.

**Comment by riscy** [comment]
Makes sense.  I think it's time I actually write up an issue re: private docstrings and other checkdoc noise, and I'll refer to this PR when I do that.  Merging!

**Pull request merged**
