### PR TITLE
add julia-formatter package

### PR DESCRIPTION
**Pull request by FelipeLema**
### Brief summary of what the package does

Use JuliaFormatter.jl for formatting Julia code

### Direct link to the package repository

https://codeberg.org/FelipeLema/julia-formatter.el

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
  * does not, but dunno how to address "this function is not necessary, but if you're going to use it, you would prefer to have it installed first
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this and for your close adherence to the checklist.  I'm unable to replicate your problem with the byte-compile so you seem to be good -- but I'll leave a couple suggestions:

- Regarding the line `I don't trust 'with-temp-buffer', prove me wrong`, I think if you look at the implementation of the function it's fairly unsurprising and handles the cleanup afterward, and its use of `generate-new-buffer-name` would keep you from having to dispatch to a shell to call `openssl` (which may not be installed everywhere) to name the buffer
- Altogether it looks like the intent of this package is similar to that of a minor mode - for example rather than calling the function `julia-formatter-setup-for-save`, a user could just toggle a minor mode called `julia-formatter-mode` on (and off again, if they didn't want it to apply to certain buffers while they edit them).  It's quickest for me to refer my own code for an example -- see here: https://github.com/riscy/elfmt/blob/master/elfmt.el#L93-L100
- It may be a good idea to check out https://github.com/purcell/emacs-reformatter -- this may simplify your implementation (and is something I've been meaning to look at myself)
- julia-formatter.el#L127: It's safer to sharp-quote function names; use `#'`
- julia-formatter.el#L213: It's safer to sharp-quote function names; use `#'`
- julia-formatter.el#L114: Consider using the `+1` function in this case

**Comment by FelipeLema** [comment]
@riscy thanks for the suggestions. Allow me to reply to add more context

The main purpose of this package is to provide an indent function for live indent (this is why `aggressive-indent` is mentioned all over the place), so sometimes partial text is being formatted. From what I read from its tests file, [emacs-formatter](https://github.com/purcell/emacs-reformatter) is meant to be a single-call-formats-all-buffer.

I've addressed the rest of the suggestions in the code

**Comment by riscy** [comment]
Thanks for checking those -- maybe you can give an example of `with-temp-buffer` not working for you?  I still think your random number generation to create buffer names should not be necessary, especially if you take a look at the `generate-new-buffer-name` function.

> The main purpose of this package is to provide an indent function

Ahh, I see now.  I wonder if the name julia-formatter will create confusion, and a more specific name like julia-indenter or even julia-aggressive-indent would be better for a start.  Whenever I think of formatters these days I think of something much more all-encompassing than determining indents.

With that said, I think my comments about using a minor mode still apply, but let me know if I can be more helpful about that.

**Comment by FelipeLema** [comment]
> Thanks for checking those -- maybe you can give an example of `with-temp-buffer` not working for you? I still think your random number generation to create buffer names should not be necessary, especially if you take a look at the `generate-new-buffer-name` function.

let me try using `with-temp-buffer` again... maybe I missed something the first time I tried it

> 
> > The main purpose of this package is to provide an indent function
> 
> Ahh, I see now. I wonder if the name julia-formatter will create confusion, and a more specific name like julia-indenter or even julia-aggressive-indent would be better for a start. Whenever I think of formatters these days I think of something much more all-encompassing than determining indents.
> 
> With that said, I think my comments about using a minor mode still apply, but let me know if I can be more helpful about that.

Let me add a minor mode with the code I already have. End users could either use the minor mode or setup the indenting line functions.

**Comment by riscy** [comment]
Thanks for accommodating!  Feel free to ping here when you're ready again.

**Comment by FelipeLema** [comment]
I believe I'm done complying with requests @riscy

**Comment by riscy** [comment]
Have you given some thought to this:

> I wonder if the name julia-formatter will create confusion, and a more specific name like julia-indenter or even julia-aggressive-indent would be better for a start. Whenever I think of formatters these days I think of something much more all-encompassing than determining indents.

I feel like calling this julia-formatter might be promising too much.

**Comment by FelipeLema** [comment]
@riscy I've fixed the documentation to state that this is a package for _formatting julia code_

I also suggest means of formatting code, one of them being "while typing" using Emacs indentation functions (indentation functionality is means to format julia code)

**Comment by riscy** [comment]
Okay, sounds great to me -- sorry for the delays, the holidays were busier than I thought.

**Pull request merged**
