### PR TITLE
Added receipe for avk-emacs-themes

### PR DESCRIPTION
**Pull request by avkoval**
Hello!
(I am not sure how to reopen https://github.com/melpa/melpa/pull/3281#issuecomment-155384162) so posting it again, hopefully with all required fixes. ;-)

This package contains 3 new themes for Emacs.
I host those themes with https://github.com/avkoval/avk-emacs-themes
Thank you.

### CODE REVIEW

**Comment by purcell** [comment]
That's great, thanks, but would you mind using the `github` fetcher instead, and `:repo "avkoval/avk-emacs-themes"` instead of `:url ...`? You can just push a further commit to the recipe branch and I'll squash them when I merge.

**Comment by syohex** [comment]
You should use `provide-theme` instead of `provide`
- https://github.com/avkoval/avk-emacs-themes/blob/master/avk-darkblue-white-theme.el#L187
- https://github.com/avkoval/avk-emacs-themes/blob/master/avk-darkblue-yellow-theme.el#L193

This line is not necessary.
- https://github.com/avkoval/avk-emacs-themes/blob/master/avk-daylight-theme.el#L176

**Comment by avkoval** [comment]
Fixed fetcher and provide-theme. Won't remove last line (... ends here) until its very necessary as then flycheck shows warning there...

**Comment by purcell** [comment]
> Won't remove last line (... ends here) until its very necessary as then flycheck shows warning there...

The line to be removed was the `(provide ...)` form, which was redundant.

**Comment by purcell** [comment]
Otherwise looks good, so merging now. Thanks!

**Pull request merged**
