### PR TITLE
Add recipe for yasnippet-multiple-key

### PR DESCRIPTION
**Pull request by ShuguangSun**
### Brief summary of what the package does

Parse multiple "# key :" for yasnippet

### Direct link to the package repository

https://github.com/ShuguangSun/yasnippet-multiple-key

### Your association with the package

I'm the author. The package uses a lot of code from yasnippet and includes some patches.

### Relevant communications with the upstream package maintainer

yasnippet.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
> ;; Once those functions are implemented in yasnippet, this package can be retired.

Have you thought about opening a PR or an issue in yasnippet for this?

In the meantime, quick pass:

### yasnippet-multiple-key.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
yasnippet-multiple-key.el:64: Some lines are over 80 columns wide
Warning (emacs): 
yasnippet-multiple-key.el:152: Some lines are over 80 columns wide
Warning (emacs): 
yasnippet-multiple-key.el:154: Lisp symbol `yas-define-snippets' should appear in quotes
Warning (emacs): 
yasnippet-multiple-key.el:204: You should convert this comment to documentation
Warning (emacs): 
yasnippet-multiple-key.el:238: Argument `mode-sym' should appear (as MODE-SYM) in the doc string
Warning (emacs): 
yasnippet-multiple-key.el:240: Lisp symbol `yas--load-directory-1' should appear in quotes
Warning (emacs): 
yasnippet-multiple-key.el:260: Argument `interactive' should appear (as INTERACTIVE) in the doc string
Warning (emacs): 
yasnippet-multiple-key.el:262: Lisp symbol `yas-load-directory' should appear in quotes
Warning (emacs): 
yasnippet-multiple-key.el:315: Some lines are over 80 columns wide
Warning (emacs): 
yasnippet-multiple-key.el:327: Disambiguate yas-snippet-dirs by preceding w/ function,command,variable,option or symbol.
```
There's some flexibility with checkdoc, but those look easy.

package-lint (using version 20200906.512):
```
7 issues found:
63:0: error: "yasmk--parse-template-for-compile" doesn't start with package's prefix "yasnippet-multiple-key".
151:0: error: "yasmk-define-snippets-for-compile" doesn't start with package's prefix "yasnippet-multiple-key".
203:0: error: "yasmk--load-directory-2-for-compile" doesn't start with package's prefix "yasnippet-multiple-key".
237:0: error: "yasmk--load-directory-1-for-compile" doesn't start with package's prefix "yasnippet-multiple-key".
259:0: error: "yasmk-load-directory-for-compile" doesn't start with package's prefix "yasnippet-multiple-key".
314:0: error: "yasmk-compile-directory" doesn't start with package's prefix "yasnippet-multiple-key".
326:0: error: "yasmk-recompile-all" doesn't start with package's prefix "yasnippet-multiple-key".
```

**Comment by ShuguangSun** [comment]
A PR has been submitted meanwhile. However, yasnippet is a quite mature and popular package, and we don't know whether it accepts such new functions and how long it will take the PR. So that a separate package could be solution for those who want the feature of multple keys for one template.

There are some feature request in yasnippet's repo:
https://github.com/joaotavora/yasnippet/pull/1068

**Comment by riscy** [comment]
> So that a separate package could be solution for those who want the feature of multple keys for one template.

That's fair.  Feel free to ping when this is ready for another pass -- here's the latest in the meantime:

### yasnippet-multiple-key.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
yasnippet-multiple-key.el:153: Some lines are over 80 columns wide
Warning (emacs): 
yasnippet-multiple-key.el:155: Lisp symbol `yas-define-snippets' should appear in quotes
Warning (emacs): 
yasnippet-multiple-key.el:206: All variables and subroutines might as well have a documentation string
Warning (emacs): 
yasnippet-multiple-key.el:238: Argument `mode-sym' should appear (as MODE-SYM) in the doc string
Warning (emacs): 
yasnippet-multiple-key.el:240: Lisp symbol `yas--load-directory-1' should appear in quotes
Warning (emacs): 
yasnippet-multiple-key.el:260: Argument `interactive' should appear (as INTERACTIVE) in the doc string
Warning (emacs): 
yasnippet-multiple-key.el:262: Lisp symbol `yas-load-directory' should appear in quotes
Warning (emacs): 
yasnippet-multiple-key.el:328: Disambiguate yas-snippet-dirs by preceding w/ function,command,variable,option or symbol.
```

package-lint (using version 20200906.512):
```
7 issues found:
63:0: error: "yasmk--parse-template-for-compile" doesn't start with package's prefix "yasnippet-multiple-key".
152:0: error: "yasmk-define-snippets-for-compile" doesn't start with package's prefix "yasnippet-multiple-key".
205:0: error: "yasmk--load-directory-2-for-compile" doesn't start with package's prefix "yasnippet-multiple-key".
237:0: error: "yasmk--load-directory-1-for-compile" doesn't start with package's prefix "yasnippet-multiple-key".
259:0: error: "yasmk-load-directory-for-compile" doesn't start with package's prefix "yasnippet-multiple-key".
314:0: error: "yasmk-compile-directory" doesn't start with package's prefix "yasnippet-multiple-key".
327:0: error: "yasmk-recompile-all" doesn't start with package's prefix "yasnippet-multiple-key".
```

**Comment by ShuguangSun** [comment]
Now renamed function names using package prefix "yasnippet-multiple-key".

**Comment by riscy** [comment]
I had a look at that PR https://github.com/joaotavora/yasnippet/pull/1068 where you wrote:

> To avoid introducing bugs, I make a copy of some functions, for example, yas--parse-template to yas--parse-template-for-mulkey, and make changes to those functions.

Just from an outsider's perspective, this feels like an extremely difficult PR for the yasnippet team to merge.  Copying and pasting code with minor modifications will quickly turn their codebase to mush.  You _should_ modify their existing functions, which would make it much clearer to them what you're introducing.

If you do that, that would also help MELPA maintainers make a determination as to whether yasnippet-multiple-key meets the uniqueness threshold.

> The warnings from doccheck are from the code from origin yasnippet, and I don't like to change any of those code.

No, some of them you introduced yourself.

If you're unable to minimize your diff in the aforementioned PR, could you give me (unfamiliar with yasnippet's conventions) a clearer explanation, maybe a screenshot, describing what the difference is?  Your `;;; Commentary` requires a little more knowledge than I have, and seems outdated with respect to the code.

Thanks, and I hope I wasn't too harsh.

**Comment by ShuguangSun** [comment]
The key (and the only) change is the one to funciton `yas--parse-template` as below which changes the structure of retured parsed template.  In yasnippet, `yas--parse-template` is called to parse template for compliling template (for jit), and for load snippet (for non-jit, e.g., `yas-load-snippet-buffer`). This if for compling templates and using JIT yasnippet only. If we want to support non-jit, it needs much more work and tests. It is why I just copied and changed some selected functions.

```
*** c:/Users/SUNSHU~1/AppData/Local/Temp/ediffNMs1nk	Mon Sep 21 11:39:19 2020
--- c:/Users/SUNSHU~1/AppData/Local/Temp/ediffXkIz2x	Mon Sep 21 11:39:19 2020
***************
*** 1,6 ****
! (defun yas--parse-template (&optional file)
    "Parse the template in the current buffer.

  Optional FILE is the absolute file name of the file being
  parsed.

--- 1,9 ----
! (defun yasnippet-multiple-key--parse-template-for-compile (&optional file)
    "Parse the template in the current buffer.

+ This is fork of `yas--parse-template' in yasnippet,
+ and patched for multiple key.
+
  Optional FILE is the absolute file name of the file being
  parsed.

***************
*** 39,45 ****
                       (yas--calculate-group file)))
           expand-env
           binding
!          uuid)
      (if (re-search-forward "^# --\\s-*\n" nil t)
          (progn (setq template
                       (buffer-substring-no-properties (point)
--- 42,49 ----
                       (yas--calculate-group file)))
           expand-env
           binding
!          uuid
!          results)
      (if (re-search-forward "^# --\\s-*\n" nil t)
          (progn (setq template
                       (buffer-substring-no-properties (point)
***************
*** 54,60 ****
                                    'command
                                  'snippet)))
                   (when (string= "key" (match-string-no-properties 1))
!                    (setq key (match-string-no-properties 2)))
                   (when (string= "name" (match-string-no-properties 1))
                     (setq name (match-string-no-properties 2)))
                   (when (string= "condition" (match-string-no-properties 1))
--- 58,64 ----
                                    'command
                                  'snippet)))
                   (when (string= "key" (match-string-no-properties 1))
!                    (cl-pushnew (match-string-no-properties 2) key))
                   (when (string= "name" (match-string-no-properties 1))
                     (setq name (match-string-no-properties 2)))
                   (when (string= "condition" (match-string-no-properties 1))
***************
*** 69,78 ****
        (setq template
              (buffer-substring-no-properties (point-min) (point-max))))
      (unless (or key binding)
!       (setq key (and file (file-name-nondirectory file))))
      (when (eq type 'command)
        (setq template (yas--read-lisp (concat "(progn" template ")"))))
      (when group
        (setq group (split-string group "\\.")))
!     (list key template name condition group expand-env file binding uuid)))

--- 73,87 ----
        (setq template
              (buffer-substring-no-properties (point-min) (point-max))))
      (unless (or key binding)
!       (cl-pushnew (and file (file-name-nondirectory file)) key))
      (when (eq type 'command)
        (setq template (yas--read-lisp (concat "(progn" template ")"))))
      (when group
        (setq group (split-string group "\\.")))
!     (if key
!         (dolist (k key results)
!           ;; (push (list k template name condition group expand-env file binding uuid) results))
!           (push (list k template (format "%s (%s)" name k) condition group expand-env file binding uuid) results))
!       (setq results (list (list key template name condition group expand-env file binding uuid))))
!     results))
```

**Comment by riscy** [comment]
Thanks, I think I see the motivation.

> If we want to support non-jit, it needs much more work and tests. It is why I just copied and changed some selected functions.

I'm inclined to suggest this is the route you take.  The PR you opened in the yasnippet repository does not make it easy for the yasnippet maintainers to understand the scope of the change.  And yes, it's more work to come up with a holistic solution.  But it feels premature for us to throw up our arms and decide that a soft fork with many of the functions copy-pasted is the answer.

Let me know if that sounds fair to you -- and of course if you disagree, we can call in help from another MELPA maintainer with more experience.

**Comment by ShuguangSun** [comment]
Understand. It is fair.

**Comment by riscy** [comment]
Thanks for being understanding.  I'll close here, but I'll keep an eye on yasnippet.

**Pull request closed without merging**
