### PR TITLE
Update org-preview-html recipe, formerly 'Add  recipe for preview-org-html-mode'

### PR DESCRIPTION
**Pull request by jakebox**
### Brief summary of what the package does

This minor mode provides a live side-by-side preview of your org-exported HTML files using the xwidget WebKit browser.

### Direct link to the package repository

https://github.com/jakebox/preview-org-html-mode

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

Thank you very much for your consideration and time, we appreciate it!

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Everything looks great according to the checklist, but very quickly I also noticed:

- preview-org-html-mode.el#L103: It's safer to sharp-quote function names; use `#'`
- preview-org-html-mode.el#L160: Lighter should start with a space
- The url-link under `defgroup` points to the author's GitHub page instead of the repo's GitHub page
- The code and occasional docstring run a little bit wide -- 185 characters in the longest case.  not a blocker, but it can be friendlier to other devs to wrap at something closer to 80.  In the case of docstrings, the Emacs online help doesn't (can't) know where to wrap those strings to fit the user's display, so I find it's best to be conservative
- There might be some unnecessary use of progn under `unless` and `while` and `cond` blocks -- you should check my work, but I believe every single use of progn in the code is not needed

**Comment by jakebox** [comment]
Thank you very much, I'll get to those fixes shortly, much appreciated. Still quite beginner at elisp so the feedback is nice.

**Comment by jakebox** [comment]
Hi @riscy, I've made and pushed those changes to https://github.com/jakebox/preview-org-html-mode, thanks again for the feedback. You were right about the `progn`s.

-Jake

**Comment by alphapapa** [comment]
@jakebox This looks really cool, like a feature someone should have already made!  The demo in the readme is great, too.

Now, if I may engage in my customary bikeshedding: Please consider naming the package with the `org` token first, like `org-html-preview`, or `org-live-html-preview`, something like that.  Most Org-related packages are named with the `org-` prefix, which makes them much easier to discover and organize in package listings.  As well, you could probably omit the `-mode` suffix from the package name (not the mode's name), because that's basically an implementation detail.

I think this will become a very popular package as soon as it's published and announced in the Usual Places!

**Comment by jakebox** [comment]
Hi @alphapapa, thanks for the comment, it means a lot coming from you of course. And you make a good point regarding the name of my package. I went with preview-org-html-mode (which I now see is overly verbose) because org-preview-html is taken by this seemingly unmaintained package: https://github.com/lujun9972/org-preview-html.

I don't love org-html-preview or live-preview because it's quite close to the aforementioned package and don't want to cause confusion. Maybe still too bulky, but how about `org-xwidget-preview-html`? Again thanks for the comment and feedback. I would love for my <soon-to-be-retitled> package to be usefully enjoyed by more people than just myself.

**Comment by jakebox** [comment]
You're right, I didn't look closely enough and was remembering from when I looked at it (which was clearly two months prior).

In any case, I think you're right about combining. I think now I will reach out to the author of `org-preview-html` and see what their thoughts are. I've noticed requests/issues that could be taken care of, and that the author has possibly bigger things to work on (all my conjecture based on GitHub) so maybe we can work something out. Thanks for the comments, I'll reach out and come back here.

**Comment by alphapapa** [comment]
Thanks, that sounds great.  Maybe you could even adopt the package or join him in maintaining it.

**Comment by riscy** [comment]
Thanks both, this might end up being a best case scenario.  I'll mark this PR awaiting upstream, but feel free to comment when there's news.

**Comment by jakebox** [comment]
@lujun9972 Thoughts on all this? I also contacted you at the email listed on your GitHub.

**Comment by lujun9972** [comment]
I think combining those two packages is a good idea.

@jakebox 
Considering my lack of time to maintaining `org-preview-html` ,  I'd love to transfer this repo to you if you wish.

**Comment by jakebox** [comment]
Hi @lujun9972, transferring sounds perfect, same with your comments here: https://github.com/lujun9972/org-preview-html/issues/11#issuecomment-904231264. While you do that I'll confirm compatibility, I'm fairly confident users should see no difference as I've made `eww` default per your request (which I think is very fair).

@riscy, what is the procedure in a situation like this? I'll update my code make it `org-preview-html` and then put it into the transferred repo, is there anything I need to do regarding versioning since this is still the same package? I also guess I need to update the package recipe to point to my Github. Thanks for your help!

**Comment by alphapapa** [comment]
@lujun9972 Thanks for your flexibility and humility. You put the users first, which is what all maintainers should do.

**Comment by riscy** [comment]
Yep, thanks very much @lujun9972.  @jakebox I believe if the repository is explicitly transferred to your GitHub account through the GitHub interface, then GitHub will handle the redirection behind the scenes.  I believe all of the versioning should remain intact.  After that, we could update the recipe to point to your repo, and you can add your new code in.  This would probably be the best option for a seamless transition for users.

**Comment by jakebox** [comment]
Sounds good @riscy – should I close this PR and open a new one or amend it? I am not a git wizard so apologies if there's a standard practice here

**Comment by riscy** [comment]
Either works -- it may be easiest for you to amend this one, and then you'll keep your place in the informal PR queue.

**Comment by jakebox** [comment]
Alright, there we go! I've updated the recipe and deleted my pending one for the old package (`preview-org-html-mode`). At long last, I think we're done here. Apologies this thread went on so long and thank you so much for sticking with it!

**Comment by riscy** [comment]
Looks good!  Thanks everyone on the list.

@jakebox I'll merge for now, but a couple issues you may want to prioritize:

package-lint (using version 20210528.2348):
```
8 issues found:
1:0: warning: The package summary is too long. It should be at most 60 characters.
1:0: warning: The package summary should start with an uppercase letter or a digit.
...
```

- org-preview-html.el#L8: Prefer just `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by jakebox** [comment]
Thank you so much @riscy! I'll be replacing all the files with my repo that was cleared by the linters. Thanks again.

**Pull request merged**
