### PR TITLE
Adding one-time-pad-encrypt package

### PR DESCRIPTION
**Pull request by garvinguan**

### CODE REVIEW

**Comment by garvinguan** [comment]
I fixed the file name conflict. How can I restart the build?

**Comment by purcell** [comment]
A few small issues here:

- The package description on the first line of the .el file is blank
- The filename on the first line of the .el file does not match the actual filename
- The `(provide 'one-time-pad-encrypt)` form is missing after the other code
- The mandatory `;;; one-time-pad-encrypt.el ends here` trailing comment is missing
- You're using camelCase for variable names, when you should be using lisp-case.

Hope that helps!

**Comment by garvinguan** [comment]
Those comments definitely helped. I've just added the above changes. Please let me know how it looks!

Thanks

**Comment by purcell** [comment]
Thanks, sent you a further couple of little fixes in https://github.com/garvinguan/emacs-one-time-pad/pull/2

**Comment by garvinguan** [comment]
I merged the fixes. Great tips, thanks!

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
