### PR TITLE
Add recipe for easysession

### PR DESCRIPTION
**Pull request by jamescherti**
### Brief summary of what the package does

The Emacs package `easysession.el` offers a convenient and effortless way to persist and restore Emacs editing sessions. It can significantly increase productivity and save a lot of time for users who frequently switch between different projects and those who frequently open and close the Emacs editor.

In addition to its automatic session management capabilities, the `easysession.el` Emacs package also offers a variety of useful Emacs commands that allow users to save, load, list and delete session.

### Direct link to the package repository

https://github.com/jamescherti/easysession.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`easysession.el` with byte-compile using Emacs 29.4:
```
easysession.el:33:2: Error: Cannot open load file: No such file or directory, f
```

`easysession.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- easysession.el#L222: You may want to prefer `(derived-mode-p 'xyz)`
```

**Comment by jamescherti** [comment]
I fixed both issues:
```

```

**Comment by riscy** [comment]
Thank you!  This puts the checklist behind us, but on a closer look I wanted to check whether you were aware of some existing packages around maintaining [sessions](https://melpa.org/#/?q=session).  For example,

- https://melpa.org/#/minimal-session-saver
- https://melpa.org/#/save-visited-files
- https://melpa.org/#/sesman (updated recently, with 8 contributors)

Is there any strong feature overlap?  There's always a strong preference to see maintainers join forces when possible, and to push back against having several functionally overlapping packages with a scattering of users each.

**Comment by jamescherti** [comment]
Here is the improved text:

- None of them can restore indirect buffers or clones.
- None of them load the frameset, including the tab-bar, in recent versions of Emacs.
- None of them seem to save and restore frames.
- `minimal-session-saver` and `save-visited-files.el` are no longer maintained.

**Comment by jamescherti** [comment]
`psession` but it does not seem to support indirect buffers (clones). It also overlaps with the built-in `savehist` package, which can save and restore variables, and it cannot switch between sessions quickly, with or without modifying the geometry. This last feature is important in easysession.el because it allows switching between sessions without the annoyance of changing the window position or size.

**Comment by riscy** [comment]
Thanks @jamescherti - I think some of the distinguishing features you've listed above could benefit from being in your `;;; Commentary` (vs. just "Easily persist and restore your editing sessions effortlessly").  Otherwise how would users know about support for indirect buffers (or what that means), your inclination toward a "lightweight" implementation, etc.?  I usually suggest referring to the other packages when doing this, if possible.

In the meantime, the following has come up --

`easysession.el` with byte-compile using Emacs 29.4:
```
easysession.el:480:8: Warning: function `easysession-set-current-session' defined multiple times in this file
```

**Comment by jamescherti** [comment]
Hello @riscy,
Thank you for the update and suggestions. I have fixed all warnings and updated the ;;; Commentary and README.md files. Please check again.

**Comment by riscy** [comment]
That reads excellently - thank you!

**Comment by jamescherti** [comment]
Thank you for the merge, @riscy!

**Pull request merged**
