### PR TITLE
Add harvest.el recipe

### PR DESCRIPTION
**Pull request by kostajh**
Adds the [harvest.el](https://github.com/kostajh/harvest.el) package, of which I'm the author.

### CODE REVIEW

**Comment by kostajh** [comment]
Hmm, the tests didn't run -- apologies if I did something wrong!

**Comment by purcell** [comment]
Thanks. Quick feedback:

- Version number is mandatory in dependencies, so `(swiper)` is invalid.
- Use `(let ...)` rather than `setq` to introduce local vars like `request-url`
- Don't indent subsequent lines of multi-line docstrings
- Don't autoload changes to org-clock hooks: just because somebody has your package installed doesn't mean they want it enabled, just like with all the optional packages in the Emacs standard library.
- Please add a short `Commentary` section to the comment boilerplate describing the package and basic setup/usage

Hope that helps!

**Comment by kostajh** [comment]
Thanks for the feedback, very much appreciated! I'll work on making those changes.

Steve Purcell writes:

> Thanks. Quick feedback:
>
> - Version number is mandatory in dependencies, so `(swiper)` is invalid.
> - Use `(let ...)` rather than `setq` to introduce local vars like `request-url`
> - Don't indent subsequent lines of multi-line docstrings
> - Don't autoload changes to org-clock hooks: just because somebody has your package installed doesn't mean they want it enabled, just like with all the optional packages in the Emacs standard library.
> - Please add a short `Commentary` section to the comment boilerplate describing the package and basic setup/usage
>
> Hope that helps!
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/melpa/melpa/pull/3623#issuecomment-188072771


-- 
@kostajh | kosta@kostaharlan.net

**Comment by kostajh** [comment]
@purcell thanks so much for your review & suggestions. I've made some updates, please let me know what you think!

**Comment by purcell** [comment]
Looking good! Couple of little things I picked up still:

- `alist-get` should be called `harvest-alist-get`
- Consider using the built-in `user-emacs-directory` instead of hard-coding `~/.emacs.d`
- You check for `"~/.emacs.d/.harvest/auth.el"` and mention `"~/.emacs.d/harvest/auth.el"` (missing dot) in a message: maybe use a variable so that they always match up?

**Comment by kostajh** [comment]
OK, I've addressed those issues. I really appreciate your code review, it's been helpful!

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
