### PR TITLE
Add evil-ledger

### PR DESCRIPTION
**Pull request by atheriel**
### Brief summary of what the package does

`evil-ledger` provides text objects and motions (in the `evil` sense) for working with transactions in a `ledger-mode` buffer, making it easy to select/copy/delete/change them as a unit when `evil-ledger-mode` is active. It also provides some conveniences for navigation, alignment, and sorting.

### Direct link to the package repository

https://github.com/atheriel/evil-ledger

### Your association with the package

I am the author and maintainer of the package.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Mostly looks great, but `with-eval-after-load` is meant more for end-user configs, and should generally not be used in packages. Are you sure you need to wrap those forms like that for them to work that way?

Also, you should likely autoload `evil-ledger-mode`, so that users can add it to `ledger-mode-hook` without needing to explicitly `require` this file first.

**Comment by atheriel** [comment]
Nice catch on the `autoload`. I had intended to use `with-eval-after-load` to provide "optional" functionality, although it turns out that the appropriate keymap is loaded by `ledger-mode.el` anyway, so the form wasn't actually accomplishing anything -- it's been removed.

But I do have a general question: what's the idiomatic way to include optional support for other packages (e.g. `helm`)? I'd seen some advice that `with-eval-after-load` was the way to go, but is that not your view?

**Comment by purcell** [comment]
> But I do have a general question: what's the idiomatic way to include optional support for other packages (e.g. helm)? I'd seen some advice that with-eval-after-load was the way to go, but is that not your view?

The best way is to provide that as a separate little package with proper dependencies. It's pretty trivial to do that these days. Any other approach has downsides.

Merging this recipe now, in any case.

**Comment by atheriel** [comment]
Thanks!

**Pull request merged**
