### PR TITLE
Add recipe for MLScroll — a fast mode line scroll bar

### PR DESCRIPTION
**Pull request by jdtsmith**
### Brief summary of what the package does

MLScroll provides an interactive scroll bar in the mode line. 

### Direct link to the package repository

https://github.com/jdtsmith/mlscroll

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, here's a quick first pass --

### mlscroll.el ###

byte-compile (using Emacs 27.1):
```
mlscroll.el:271:11:Warning: assignment to free variable `which-func-format'
In mlscroll-shortfun-setup:
mlscroll.el:279:47:Warning: reference to free variable `which-func-format'
mlscroll.el:284:42:Warning: reference to free variable `which-func-current'
```
I think these just need a dependency to be declared `(require 'which-func)` but flycheck or byte-compiling from a fresh Emacs session will let you double-check.

checkdoc (using version 0.6.2):
```
Warning (emacs): 
mlscroll.el:95: Lisp symbol `which-function-mode' should appear in quotes
Warning (emacs): 
mlscroll.el:254: All variables and subroutines might as well have a documentation string
Warning (emacs): 
mlscroll.el:269: All variables and subroutines might as well have a documentation string
Warning (emacs): 
mlscroll.el:274: All variables and subroutines might as well have a documentation string
Warning (emacs): 
mlscroll.el:277: Messages should start with a capital letter
Warning (emacs): 
mlscroll.el:277: Error messages should *not* end with a period
Warning (emacs): 
mlscroll.el:106: White space found at end of line
```

package-lint (using version 20210425.3):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- mlscroll.el#L8: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)

**Comment by jdtsmith** [comment]
Thanks for the feedback.  I pushed fixes which I believe address these.  I only need to load `which-func` if an option to shorten the which-function name is configured, and by default it isn't, so I just used `defvar` to quiet the compiler.

**Comment by riscy** [comment]
> so I just used defvar to quiet the compiler.

Yeah, that makes sense to me.  This looks pretty cool.  :)

There is one last package-lint but I figure it's not blocking:

package-lint (using version 20210511.2055):
```
1 issue found:
38:10: warning: This file is not in the `cl-lib' ELPA compatibility package: require `cl-lib' instead.
```
The fix here is to `(require 'cl-lib)` instead, which is the standard way to bring in stuff from `cl-seq` and its siblings.

**Comment by jdtsmith** [comment]
Great thanks.  Switched to `cl-lib`.  I appreciate your efforts.

**Pull request merged**
