### PR TITLE
Create underline-with-char

### PR DESCRIPTION
**Pull request by marcowahl**
### Brief summary of what the package does

Underline with a char

### Direct link to the package repository

https://github.com/marcowahl/underline-with-char

### Your association with the package

maintainer - contributor - enthusiastic user

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is _almost_ happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. This looks useful. I feel like one command should be enough, and would be tidier: why not just provide `underline-with-char`, and have it prompt for a char when given a prefix argument?

**Comment by marcowahl** [comment]
Thanks.  Good idea.

I implemented the interface following your suggestion.

**Comment by purcell** [comment]
Great, merged!

**Comment by marcowahl** [comment]
Thanks!

**Pull request merged**
