### PR TITLE
Add recipe for ttl-mode

### PR DESCRIPTION
**Pull request by ptrv**
ttl-mode is a major mode for editing Turtle (RDF) files.

### CODE REVIEW

**Comment by purcell** [comment]
The code needs a bit of cleaning up first:

- No `provide` form or trailing comment line
- `beginning-of-stanza` should be prefixed with `ttl-`

Also the mode declaration is a bit messy. Instead of this:

```el

(defvar ttl-mode-map (make-sparse-keymap))
(define-derived-mode ttl-mode ttl-base
  "Turtle RDF"
  (setq indent-tabs-mode nil)
  (ttl-mode-variables)
;  (define-key ttl-mode-map (kbd "C-M-q")
;    'turtle-indent-block)
  (define-key ttl-mode-map (kbd "\;") 'ttl-electric-semi)
  (define-key ttl-mode-map (kbd "\.") 'ttl-electric-dot)
  (define-key ttl-mode-map [backspace] 'ttl-hungry-delete-backwards)
  (use-local-map ttl-mode-map))
```

it could simply be:

```el
(define-derived-mode ttl-mode ttl-base
  "Turtle RDF"
  (set (make-local-variable 'indent-tabs-mode) nil)
  (ttl-mode-variables))

;  (define-key ttl-mode-map (kbd "C-M-q")
;    'turtle-indent-block)
(define-key ttl-mode-map (kbd "\;") 'ttl-electric-semi)
(define-key ttl-mode-map (kbd "\.") 'ttl-electric-dot)
(define-key ttl-mode-map [backspace] 'ttl-hungry-delete-backwards)
```

Could you maybe submit the corresponding fixes upstream?

**Comment by ptrv** [comment]
@purcell Sure, I'll submit the fixes upstream.

**Comment by purcell** [comment]
Yay, thanks.

**Comment by ptrv** [comment]
Here is a link to the PR: https://bitbucket.org/nxg/ttl-mode/pull-requests/1/clean-ups-for-melpa

**Comment by purcell** [comment]
Nice. Please ping me here when it's merged. :-)

**Comment by ptrv** [comment]
@purcell Changes are applied.

**Comment by purcell** [comment]
Cool, thanks!

**Pull request merged**
