### PR TITLE
Add recipe for lyrics-fetcher

### PR DESCRIPTION
**Pull request by SqrtMinusOne**
### Brief summary of what the package does

A package to fetch song lyrics and album covers, mainly to use with EMMS.

### Direct link to the package repository

https://github.com/SqrtMinusOne/lyrics-fetcher.el

### Your association with the package

I am a maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- looks useful and the checklist looks good!  Comments/suggestions:

- The use of `shell-command-to-string` call in lyrics-fetcher.el is ill-advised (I'm sure I'm guilty of this too).  If you're using shell commands you should run `shell-quote-argument` on [almost all of] the arguments, because who knows if a filename might have a quotation mark (or worse) in it?   I think a better choice might be `call-process`, which takes a list ARGS that don't get interpreted through the shell
- "Take a look at the package README.org for more information." MELPA won't distribute the README with the package, so it might be helpful to include a link inside your commentary for users, and/or mention entrypoints.  NBD, though.
- I always double check this: when you write "Copyright... Free Software Foundation, Inc." in lyrics-fetcher-genius.el, is this deliberate?  (e.g. have you done the paperwork, or perhaps are you including FSF code in that module?)  Otherwise the copyright belongs to the authors

After we hear back about the first point above, I think this is an easy merge.

**Comment by SqrtMinusOne** [comment]
Thanks for the review!

- I've replaced `shell-command-to-string` with `call-process`, seems to work fine.
- Added a link to the repo and references to main functions to the commentary.
- There is [a function](https://github.com/emacs-mirror/emacs/blob/e63705ab9ba9081bcb4ed97e82019aab5a033d0d/lisp/dom.el#L272) copied from the [dom.el](https://github.com/emacs-mirror/emacs/blob/e63705ab9ba9081bcb4ed97e82019aab5a033d0d/lisp/dom.el#L272) version in Emacs 28 to ensure backward compatibility with Emacs 27. I thought I have to preserve the original FSF copyright notice in that case. Or should I put Lars Magne Ingebrigtsen, the dom.el developer instead?

**Comment by riscy** [comment]
Thanks for the first two bulletpoints! For the third: no, I believe only the copyright notice has to be intact -- thanks for your diligence there.

**Comment by riscy** [comment]
And, welcome to MELPA. :)

**Pull request merged**
