### PR TITLE
Add recipe for company-bibtex.

### PR DESCRIPTION
**Pull request by gbgar**
### Brief summary of what the package does

The company-bibtex package provides a bibtex back-end for company mode, which allows for completion of citation keys in pandoc-mode, latex-mode, and org-mode.

### Direct link to the package repository

https://github.com/gbgar/company-bibtex

### Your association with the package

I am the package author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR https://github.com/gbgar/company-bibtex/pull/1.

Could you squash commits ? (And please use topic branch at next time)

BTW Should README be README.md ? It is markdown format but it has not file extension.

**Comment by gbgar** [comment]
@syohex, I am closing this PR and opening up a new one with a different branch, as you suggested, and with a single commit.

**Comment by purcell** [comment]
It's actually easy enough for us to squash commits, when they're all related. But tidy commits in topic branches are always nicer. :-)

**Comment by gbgar** [comment]
@purcell -- cool, I think I got it corrected here: #4325 

However, I'm not a professional git user (or programmer, for that matter), so don't set your bar too high ;D

**Pull request closed without merging**
