### PR TITLE
Add metal-archives-shopping-list recipe

### PR DESCRIPTION
**Pull request by seblemaguer**
### Brief summary of what the package does

Package to generate a shopping list (org file) using the Metal-Archives (http://metal-archives.com/) API

### Direct link to the package repository

https://github.com/seblemaguer/metal-archives.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by seblemaguer** [comment]
This package depends on the metal-archives package whose recipe's PR is #7259

**Comment by alphapapa** [comment]
Since this package's only non-built-in dependency is `metal-archives` itself, is it necessary for this to be a separate package?

**Comment by seblemaguer** [comment]
is `org-ml` built-in as well?

**Comment by alphapapa** [comment]
I missed that `org-ml` is only required by this package.  Nevermind then.

**Comment by riscy** [comment]
I notice you're specifying the branch, but didn't do so with metal-archives.  If that's the default branch, it's usually preferred to leave it out which leaves you free to change its name in the future.  There _is_ an issue https://github.com/raxod502/straight.el/issues/650 with straight.el not detecting these, which some authors have been working around, but it sounds like a fix is happening soon.

**Comment by seblemaguer** [comment]
@riscy just to be sure, you are talking about the PR branch right? If yes it is because I did the PR for both packages at the same time. I have no problem with closing this PR and opening a new one with the same recipe on the master branch this time. Just tell me what is more convenient for you :)

**Comment by riscy** [comment]
Oops, I was probably looking at another PR when I wrote that, which specified `:branch` in the recipe.

I think this is not a blocker, but your summary line should probably hyphenate the package-nam "metal archives"; I'd suggest something like "Shopping list extension for metal-archives"

**Pull request merged**
