### PR TITLE
Recipe: macrostep-geiser

### PR DESCRIPTION
**Pull request by nbfalcon**
A `macrostep` backend powered by `geiser`.

### Brief summary of what the package does

Integrates [macrostep](https://github.com/joddie/macrostep) with the [geiser scheme REPL](https://www.nongnu.org/geiser/).

### Direct link to the package repository

https://github.com/nbfalcon/macrostep-geiser

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by nbfalcon** [comment]
Potential problems: this package relies on internal `geiser` functions to do the macro expansion. However, I don't see how this can be avoided, given that there is no public API that would allow this. (Similar to the various `lsp-*` packages).

**Comment by riscy** [comment]
Checklist look good!

> However, I don't see how this can be avoided, given that there is no public API that would allow this.

Thanks for acknowledging this -- perhaps we can ping @jaor to see if it's possible to expose an appropriate public API, or perhaps even to see if this functionality is a good fit to be incorporated with geiser itself.

**Comment by jaor** [comment]
On Sat, Feb 20 2021, Chris Rayner wrote:

> Checklist look good!
>
>     However, I don't see how this can be avoided, given that there is
>     no public API that would allow this.
>    
> Thanks for acknowledging this -- perhaps we can ping @jaor to see if
> it's possible to expose an appropriate public API, or perhaps even to
> see if this functionality is a good fit to be incorporated with geiser
> itself.

i've taken a quick look and it wouldn't be a big problem to make the
three geiser-eval functions used by this package public.  but i should
then review the full geiser-eval module and think of what else should
also be public, to not promote things at random, so i'll need a bit of
time.  since that could be months, i wouldn't hold this package waiting
for me :)  if that's a showstopper, please feel free to send a PR
defalisasing geiser-eval-send/wait to their private counterparts (but
i'd rather do it the proper way).

(those functions are extremely unlikely to change any time soon, they're
used very heavily all around).

**Comment by nbfalcon** [comment]
@jaor thank you for your time! I think the best approach would be to use the `geiser--eval-send/wait` code as is, and for me to then change my package whenever the new API is finalized, to do things properly. Also, do you think this package would be a good fit in `geiser` itself? For example, `sly` has a separate `sly-macrostep` package. 

As a side note, there is a bug in the macro-expansion of the Racket REPL: forms are macroexpanded to '(actual result), which is due to `pretty-print` printing lists as '(...); quote-depth will need to be passed as 1. I'll make a PR soon.

**Comment by jaor** [comment]
On Sun, Feb 21 2021, Nikita Bloshchanevich wrote:

> @jaor thank you for your time! I think the best approach would be to
> use the geiser--eval-send/wait code as is, and for me to then change
> my package whenever the new API is finalized, to do things properly.

sounds sensible to me...

> Also, do you think this package would be a good fit in geiser itself?

possibly, but i don't think there's anything wrong in a separate package
either, and it has some advantages in that i don't have lots of time for
geiser and i'll probably make things slower if you have to rely on my
reviews or merging.  and also, we're (very slowly) migrating to multiple
packages anyway: https://gitlab.com/emacs-geiser

> As a side note, there is a bug in the macro-expansion of the Racket
> REPL: forms are macroexpanded to '(actual result), which is due to
> pretty-print printing lists as '(...); quote-depth will need to be
> passed as 1. I'll make a PR soon.

do you mean geiser's racket repl?  if so, please consider making the PR
against the separate geiser/racket subpackage
https://gitlab.com/emacs-geiser/racket

(at some point, the point is to close the current "main" geiser at
jaor/geiser... we're almost there, but i haven't found the time to
publish elpa packages for all of them, specially for geiser-core, which
is big and doesn't always follow current melpa policies).

**Comment by riscy** [comment]
Thanks both!  I think this package is fine to include even with its dependency on private functions, but it's something to keep an eye on and maybe build some CI around.

Taking a closer look at the code.

I'm not familiar with macrostep's conventions, but I wonder whether `macrostep-geiser-setup` would make sense as a minor mode that could be toggled off again (turning the mode off would involve, e.g. `(setq-local macrostep-macro-form-p-function (default-value 'macrostep-macro-form-p-function))`.

I also notice you're deliberately not running `(require 'macrostep)` but you do have a `Package-Requires` on it -- instead you're using `declare-function` and a handful of `defvars` to pacify the compiler.  I think it would be better just to use the `require` -- that way the byte-compiler will inform you if these functions/variables don't exist.

**Comment by nbfalcon** [comment]
@riscy the minor-mode idea is possible, but it would involve saving all the `macrostep` variables, since the default value only works for Elisp. I think this is as per the conventions, since [macrostep-c, shipped with it, also does that](https://github.com/joddie/macrostep/blob/424e3734a1ee526a1bd7b5c3cd1d3ef19d184267/macrostep-c.el#L77) (`macrostep-c-turn-off` doesn't restore variables).

As to your second point, `macrostep-expand`, the main interactive entry-point to macrostep, is autoloaded and should be called by the user. Its behavior is driven by the back-end variables (set in `macrostep-geiser-setup`). `macrostep-geiser-expand-all` should maybe require it anyway though - in case users don't have autoloading set-up. (Should packages handle that? E.g. `lsp-mode`'s avy lens function doesn't require `avy` for `avy-read` (autoloaded)).

`require`ing macrostep should be delayed if possible, because the user might not use it, even though `macrostep-geiser` is loaded, since `macrostep-geiser-setup` is intended to be added to `geiser-mode-hook`.

**Comment by riscy** [comment]
Okay, the rationale above sounds reasonable to me.

> macrostep-geiser-expand-all should maybe require it anyway though - in case users don't have autoloading set-up. (Should packages handle that? ...

Yeah, that's a tricky question.  I personally think that packages should be robust to users not having autoloading set up.  There are some nuances listed [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html) and maybe the last point there is relevant, which suggests to me that depending on autoload _comments_ is a bad idea.

**Pull request merged**
