### PR TITLE
Add register-quicknav.

### PR DESCRIPTION
**Pull request by tastytea**
### Brief summary of what the package does

Quickly jump to next/previous register.

### Direct link to the package repository

https://schlomp.space/tastytea/register-quicknav

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```
 register…     1   1 warning         The package summary should not end with a period. (emacs-lisp-package)
 register…    68   1 error           `register-quicknav/buffer-only' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions). (emacs-lisp-package)
 register…    73   1 error           `register-quicknav//current-position-register' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions). (emacs-lisp-package)
 register…    76   1 error           `register-quicknav//sort-position-register-elements' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions). (emacs-lisp-package)
 register…    85   1 error           `register-quicknav//registers' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions). (emacs-lisp-package)
 registe…    98   1 error           `register-quicknav/next-register' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions). (emacs-lisp-package)
 registe…   109   1 error           `register-quicknav/prev-register' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions). (emacs-lisp-package)
 registe…   120   1 error           `register-quicknav/clear-current-register' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions). (emacs-lisp-package)
```

**Comment by tastytea** [comment]
I fixed the summary. `/` as separator is much more clearer that `-` and doesn't seem to be a problem in other MELPA packages.

**Comment by alphapapa** [comment]
> I fixed the summary. `/` as separator is much more clearer that `-` and doesn't seem to be a problem in other MELPA packages.

For better or worse, MELPA strictly enforces this rule now.  It's not retroactively applied to older packages.

**Comment by tastytea** [comment]
> For better or worse, MELPA strictly enforces this rule now. It's not retroactively applied to older packages.

Fixed.

**Comment by conao3** [comment]
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```
 registe…   156   1 warning         the following functions are not known to be defined: register-quicknav/next-register, register-quicknav/prev-register, register-quicknav/clear-current-register (emacs-lisp)
```

**Comment by tastytea** [comment]
Thanks @conao3, fixed.

**Comment by conao3** [comment]
Thanks!
I read your package, a few points I notice.
1. How about define function for a very special and restrictive function.
```diff
modified   register-quicknav.el
@@ -93,27 +93,25 @@
 (defvar register-quicknav--current-position-register 0
   "An index to the current position register.")
 
-(defun register-quicknav--sort-position-register-elements (a b)
-  "Return t if the file name is the same and A < B."
-  (let ((marker-a (cdr a))
-        (marker-b (cdr b)))
-    (and (string= (buffer-file-name (marker-buffer marker-a))
-                  (buffer-file-name (marker-buffer marker-b)))
-         (< (marker-position marker-a)
-            (marker-position marker-b)))))
-
 (defun register-quicknav--registers ()
   "Return all position registers, sorted by file name and position.
 If `register-quicknav-buffer-only' is t, return only registers in
 current buffer."
-  (let (result)
+  (let ((fn (lambda (a b)
+              (let ((marker-a (cdr a))
+                    (marker-b (cdr b)))
+                (and (string= (buffer-file-name (marker-buffer marker-a))
+                              (buffer-file-name (marker-buffer marker-b)))
+                     (< (marker-position marker-a)
+                        (marker-position marker-b))))))
+        result)
     (dolist (item register-alist)
       (when (markerp (cdr item))
         (if register-quicknav-buffer-only
             (when (eq (current-buffer) (marker-buffer (cdr item)))
               (setq result (cons item result)))
           (setq result (cons item result)))))
-    (sort result #'register-quicknav--sort-position-register-elements)))
+    (sort result fn)))
 
 ;;;###autoload
 (defun register-quicknav-next-register ()
```
2. How about use `push` instead of `setq`.
This usage is very common usage in Lisp program. (`let` ~ `push` ~ `nreverse` or somothing like this)
```diff
modified   register-quicknav.el
@@ -111,8 +111,8 @@ current buffer."
       (when (markerp (cdr item))
         (if register-quicknav-buffer-only
             (when (eq (current-buffer) (marker-buffer (cdr item)))
-              (setq result (cons item result)))
-          (setq result (cons item result)))))
+              (push item result))
+          (push item result))))
     (sort result #'register-quicknav--sort-position-register-elements)))
 
 ;;;###autoload
```

3. How about using `cl-incf` instead of `(setq (+ pos 1))`
```diff
modified   register-quicknav.el
@@ -4,7 +4,7 @@
 
 ;; Author: tastytea <tastytea@tastytea.de>
 ;; Version: 0.1.2
-;; Package-Requires: ((emacs "24"))
+;; Package-Requires: ((emacs "24.3"))
 ;; Keywords: convenience
 ;; URL: https://schlomp.space/tastytea/register-quicknav
 
@@ -72,6 +72,8 @@
 
 ;;; Code:
 
+(require 'cl-lib)
+
 (define-obsolete-variable-alias 'register-quicknav/buffer-only
   'register-quicknav-buffer-only "0.1.1")
 (define-obsolete-function-alias 'register-quicknav/next-register
@@ -121,7 +123,7 @@ current buffer."
   (interactive)
   (let ((pos register-quicknav--current-position-register)
         (registers (register-quicknav--registers)))
-    (setq pos (+ pos 1))
+    (cl-incf pos)
     (when (>= pos (length registers))
       (setq pos 0))
     (setq register-quicknav--current-position-register pos)
```

**Comment by tastytea** [comment]
Thanks again! I've applied all you suggestions, but used `cl-flet` for the lambda since I find it clearer and I required `cl-lib` anyway.

**Comment by riscy** [comment]
This looks good and thanks for your close adherence to the checklist -- can you quickly comment on the difference between your package and the following:

- https://melpa.org/#/register-channel
- https://melpa.org/#/iregister

**Comment by tastytea** [comment]
**iregister-channel** is limited to 5 position registers by default, needs a keybinding to be setup for each additional register, can't be restricted to the current buffer and has no ability to jump to the next/previous register.

**iregister** opens a minibuffer on each jump (and thereby requiring an extra keystroke), it doesn't work with file-query registers and it can't be restricted to the current buffer. It is not maintained anymore.

**register-quicknav** jumps to the next/previous marker or file-query register without requiring additional input and can be restricted to the current buffer.

**Comment by riscy** [comment]
Awesome, thank you for the feedback.  I think that would be worth adding to your frontmatter or your README, if you're willing.

Otherwise I see no blockers for this one.  Welcome to MELPA!

(Non-blocking in register-quicknav.el#L157: You can use `not` or `null`)

**Comment by tarsius** [comment]
@tastytea Please consider naming the primary branch `master` (instead of `main`) like everybody else.

**Comment by tastytea** [comment]
@tarsius If the reason for that request is broken software, please consider fixing the software instead.

**Comment by tarsius** [comment]
No software is broken but your pull-request is. If a package's repository doesn't use the `master` branch, then the Melpa recipe must specify the branch using the `:branch` keyword. I'll fix this for you in this case but please do it yourself for any of your own package that you add in the future.

**Comment by tastytea** [comment]
I couldn't find anything about that in the documentation.

**Comment by riscy** [comment]
I'll start checking for this.

**Comment by tarsius** [comment]
> I couldn't find anything about that in the documentation.

I have added a sentence to that effect. Nothing more prominent is needed because hardly anyone uses something other than `master`. I suspect that the test succeeded because at the time this pr was submitted the branch `master` still existed. Usually the test would fail and since @riscy is now looking for this we should be good.

**Comment by tastytea** [comment]
> I have added a sentence to that effect. 

Thanks.

> I suspect that the test succeeded because at the time this pr was submitted the branch `master` still existed.

There never was a branch named `master`.

**Comment by tarsius** [comment]
@tastytea This repository doesn't seem to be accessible anymore. I get a 500 http status code.

**Comment by tastytea** [comment]
> @tastytea This repository doesn't seem to be accessible anymore. I get a 500 http status code.

works for me, maybe it was a glitch?

**Comment by tarsius** [comment]
Seems like it. On the weekend Melpa failed to fetch from this repository, but now it works (see "Build Log" at https://melpa.org/#/register-quicknav). Sorry for the noise.

**Comment by tarsius** [comment]
@tastytea The repository is again not accessible. Visiting it in firefox I learn that you are trying to redirect to a new location, but at least in that browser the redirection doesn't actually work. I could extract `https://router.parklogic.com/tastytea/register-quicknav.git` from the obfuscated javascript, but that url takes me to a broken page.

**Comment by tastytea** [comment]
the forge and the repo are gone, the redirect is from a domain reseller. sorry, i didn't remember that the package was registered here.

**Comment by tarsius** [comment]
So what's the plan? Are you going to publish it elsewhere? Should we keep it in Melpa? etc.

**Comment by tastytea** [comment]
i will not re-publish it, i don't care if it stays in Melpa

**Comment by tarsius** [comment]
Because it has only been downloaded 300 times, I opt to remove it.

**Pull request merged**
