### PR TITLE
Recipe for async-job-queue package

### PR DESCRIPTION
**Pull request by owinebar**
### Brief summary of what the package does

Manages a queue of async jobs by dispatching to a fixed number of slots.

### Direct link to the package repository

https://github.com/owinebar/emacs-async-job-queue

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`async-job-queue.el` with byte-compile using Emacs 28.1:
```
async-job-queue.el:45:1: Warning: custom-declare-variable
    `async-job-queue--default-size' docstring wider than 80 characters
async-job-queue.el:55:1: Warning: custom-declare-variable
    `async-job-queue--default-freq' docstring wider than 80 characters
In async-job-queue-displayable-slot:
async-job-queue.el:179:42: Warning: Unused lexical argument `slot'
async-job-queue.el:182:45: Warning: reference to free variable `tbl'
In async-job-queue-make-job-queue:
async-job-queue.el:280:8: Warning: docstring wider than 80 characters
In async-job-queue--alloc-slot:
async-job-queue.el:332:8: Warning: docstring wider than 80 characters
In async-job-queue--reclaim-slot:
async-job-queue.el:371:8: Warning: docstring wider than 80 characters
async-job-queue.el:385:29: Warning: Unused lexical variable `next-free'
In async-job-queue--dispatch:
async-job-queue.el:414:8: Warning: docstring wider than 80 characters
In async-job-queue-schedule-job:
async-job-queue.el:440:8: Warning: docstring wider than 80 characters
In async-job-queue--dispatch-queued:
async-job-queue.el:482:24: Warning: Unused lexical variable `job'
In async-job-queue--handle-finished-job:
async-job-queue.el:501:59: Warning: Unused lexical argument `tbl'
In async-job-queue--handle-terminated-job:
async-job-queue.el:507:61: Warning: Unused lexical argument `tbl'
In async-job-queue-cancel-job:
async-job-queue.el:518:25: Warning: reference to free variable `slot'
In async-job-queue--ensure-queue-running:
async-job-queue.el:567:8: Warning: docstring wider than 80 characters
async-job-queue.el:567:47: Warning: Unused lexical variable `idx'
async-job-queue.el:590:40: Warning: Unused lexical variable `slots'
async-job-queue.el:595:33: Warning: Unused lexical variable `q'
In async-job-queue--process-queue:
async-job-queue.el:599:8: Warning: docstring wider than 80 characters
async-job-queue.el:623:39: Warning: Unused lexical variable `on-empty'
async-job-queue.el:616:19: Warning: Unused lexical variable `freq'
async-job-queue.el:616:19: Warning: Unused lexical variable `v'
In async-job-queue-deactivate-queue:
async-job-queue.el:627:8: Warning: docstring wider than 80 characters
In async-job-queue-activate-queue:
async-job-queue.el:632:8: Warning: docstring wider than 80 characters
In end of data:
async-job-queue.el:533:24: Warning: the function `async-job-queue-slot-job' is
    not known to be defined.
```

`async-job-queue.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- async-job-queue.el#L45: Customizable variables shouldn't be private
- async-job-queue.el#L55: Customizable variables shouldn't be private
- async-job-queue.el#L175: This double negation can be collapsed
- async-job-queue.el#L200: This double negation can be collapsed
- async-job-queue.el#L201: This double negation can be collapsed
- async-job-queue.el#L202: This double negation can be collapsed
- async-job-queue.el#L203: This double negation can be collapsed
```

**Comment by owinebar** [comment]
Thanks - I didn't see anything when I ran the byte-compiler via the
sandboxed make command.

As far as I can tell, all warnings are resolved, checkdoc and package-lint
find no issues.

The "This double negation can be collapsed" is spurious.  The data
structures are strongly connected, so I wrote some functions to provide
"displayable" summaries that replace non-nil closures with t since I just
want to view whether the callbacks are present.

Lynn

**Comment by progfolio** [comment]
I still get a few byte compilation warnings oin Emacs 30:

<details><summary>Log @2023-04-18 00:11:26 -0400</summary>
search filter: "#latest byte"
<table>
<thead><th>Package</th><th>Status</th><th>Info</th><th>Time</th></thead>
<tbody>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>Byte compiling</td><td>98925.309508</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>Checking /home/n/.emacs.d/elpaca/builds/async-job-queue...</td><td>98925.397303</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>Compiling /home/n/.emacs.d/elpaca/builds/async-job-queue/async-job-queue-autoloads.el...</td><td>98925.397310</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>Compiling /home/n/.emacs.d/elpaca/builds/async-job-queue/async-job-queue-test.el...</td><td>98925.407044</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>In async-job-queue-test--quit-test:</td><td>98925.452780</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>async-job-queue-test.el:182:48: Warning: reference to free variable ‘v’</td><td>98925.452787</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>In async-job-queue-test--make-test-run:</td><td>98925.457038</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>async-job-queue-test.el:210:24: Warning: Unused lexical argument ‘v’</td><td>98925.457044</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>async-job-queue-test.el:213:24: Warning: Unused lexical argument ‘v’</td><td>98925.457048</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>In async-job-queue-test-run-test:</td><td>98925.457051</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>async-job-queue-test.el:222:20: Warning: Unused lexical argument ‘tbl’</td><td>98925.457055</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>async-job-queue-test.el:269:7: Warning: assignment to free variable ‘slot1’</td><td>98925.467272</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>async-job-queue-test.el:270:31: Warning: reference to free variable ‘slot1’</td><td>98925.467278</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>async-job-queue-test.el:270:7: Warning: assignment to free variable ‘job1’</td><td>98925.467282</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>Compiling /home/n/.emacs.d/elpaca/builds/async-job-queue/async-job-queue.el...</td><td>98925.467285</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>Done (Total of 2 files compiled, 1 skipped)</td><td>98925.558409</td></tr>
<tr><td>async-job-queue</td><td>byte-compilation</td><td>Byte compilation complete</td><td>98925.562507</td></tr></tbody>
</table>
</details>

> The "This double negation can be collapsed" is spurious.  The data
structures are strongly connected, so I wrote some functions to provide
"displayable" summaries that replace non-nil closures with t since I just
want to view whether the callbacks are present.

Instead of double negation, why not use `(and object t)`?

**Comment by owinebar** [comment]
On Tue, Apr 18, 2023, 12:12 AM Nicholas Vollmer ***@***.***>
wrote:

> I still get a few byte compilation warnings oin Emacs 30:
> Log @2023-04-18 00:11:26 -0400 search filter: "#latest byte"
> PackageStatusInfoTime
> async-job-queue byte-compilation Byte compiling 98925.309508
> async-job-queue byte-compilation Checking
> /home/n/.emacs.d/elpaca/builds/async-job-queue... 98925.397303
> async-job-queue byte-compilation Compiling
> /home/n/.emacs.d/elpaca/builds/async-job-queue/async-job-queue-autoloads.el...
> 98925.397310
> async-job-queue byte-compilation Compiling
> /home/n/.emacs.d/elpaca/builds/async-job-queue/async-job-queue-test.el...
> 98925.407044
> async-job-queue byte-compilation In async-job-queue-test--quit-test:
> 98925.452780
> async-job-queue byte-compilation async-job-queue-test.el:182:48: Warning:
> reference to free variable ‘v’ 98925.452787
> async-job-queue byte-compilation In async-job-queue-test--make-test-run:
> 98925.457038
> async-job-queue byte-compilation async-job-queue-test.el:210:24: Warning:
> Unused lexical argument ‘v’ 98925.457044
> async-job-queue byte-compilation async-job-queue-test.el:213:24: Warning:
> Unused lexical argument ‘v’ 98925.457048
> async-job-queue byte-compilation In async-job-queue-test-run-test:
> 98925.457051
> async-job-queue byte-compilation async-job-queue-test.el:222:20: Warning:
> Unused lexical argument ‘tbl’ 98925.457055
> async-job-queue byte-compilation async-job-queue-test.el:269:7: Warning:
> assignment to free variable ‘slot1’ 98925.467272
> async-job-queue byte-compilation async-job-queue-test.el:270:31: Warning:
> reference to free variable ‘slot1’ 98925.467278
> async-job-queue byte-compilation async-job-queue-test.el:270:7: Warning:
> assignment to free variable ‘job1’ 98925.467282
> async-job-queue byte-compilation Compiling
> /home/n/.emacs.d/elpaca/builds/async-job-queue/async-job-queue.el...
> 98925.467285
> async-job-queue byte-compilation Done (Total of 2 files compiled, 1
> skipped) 98925.558409
> async-job-queue byte-compilation Byte compilation complete 98925.562507
>
> I didn't realize the testing library would be getting built.  It doesn't
when I run make locally.
I've fixed these issues and added do strings.  I haven't satisfied
package-lint for that file, but it's not intended to be packaged.

The "This double negation can be collapsed" is spurious. The data
> structures are strongly connected, so I wrote some functions to provide
> "displayable" summaries that replace non-nil closures with t since I just
> want to view whether the callbacks are present.
>
> Instead of double negation, why not use (and object t)?
>

Done for both files.

Thanks,
Lynn

**Comment by owinebar** [comment]
I need to make a proper feature branch and resubmit so I can submit more than one package.

**Pull request closed without merging**
