### PR TITLE
Add recipe for casual-suite

### PR DESCRIPTION
**Pull request by kickingvegas**
### Brief summary of what the package does

Casual Suite is an umbrella package to support a single installation point for all Casual porcelains.

### Direct link to the package repository

https://github.com/kickingvegas/casual-suite

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

Ask guidance if a migration plan for casual to casual-calc is needed before approving this PR.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by minad** [comment]
Would it make sense to first rename the casual package to casual-calc and then introduce a new casual instead of casual-suite? Maybe it is now the right moment to do this, before adding the suite to MELPA?

**Comment by kickingvegas** [comment]
@minad Thanks for asking. Initially I didn’t think that renaming a MELPA package was even possible when I made this pull request. That said I think there are caveats:

1.  The old MELPA package name can not be reused, so once I change “casual” to “casual-calc”, I cannot reuse “casual” to be an umbrella package.
    -   This is because “casual” is now referenced in `:old-names` for “casual-calc”.
2.  Multiple pull-requests to MELPA will be required, which given its weekly review cycle will draw this process out for quite some time.
3.  Risk-exposure that links will still be broken, particularly in times of transition.

As much as I’d like to do the renaming, I am reluctant to even consider it because of the risk involved. Here is an initial scope for what would need to happen as I currently understand it:

1.  Rename the package `casual` to `casual-calc` in the `Casual` repository. 
    -   This will force a breaking change to the install procedure for existing users of `casual`.
    -   This will need to be in a temporary separate repository branch to support name change migration (example branch name: `name-change-migration`).
        -   Doing this avoids breaking the existing MELPA recipe while waiting for approval of step (3) below.
2.  Rename `Casual` repository to `casual-calc`. 
    -   GitHub will support redirects with caveat that I can not make another repository named `Casual`.
    -   This step is arguably optional, but ideal for consistency with Casual package repository naming.
3.  Change MELPA recipe for `casual` to `casual-calc` using `:old-names`.
    -   Configure to point to branch `name-change-migration`
    -   This will require a MELPA pull request.
    -   Upon approval this will break existing installs of `casual` as existing users must change their install code.
4.  Synchronize `name-change-migration` branch with `main` in `casual-calc` repository.
5.  Change MELPA `casual-calc` recipe to point to default branch in `casual-calc` recipe.
    -   This will require a MELPA pull request.

A similar punchlist would be required to change `cc-isearch-menu` to `casual-isearch`.

At the time of this writing, I see there are 1,354 installs of `casual` from MELPA, although I imagine the number of uniques being smaller. Regardless, at this point I do not see enough merit to introduce a breaking change for cleaner package naming.

All that said, if there is a way to migrate a package name I’m all ears. My understanding is that `make-obsolete` only applies to functions and variables, not package names. 


# References

-   [Handling full rename of existing MELPA package · Issue #2514 · melpa/melpa](https://github.com/melpa/melpa/issues/2514)
-   [Renaming a repository - GitHub Docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository#)
-   [Obsolete Functions (GNU Emacs Lisp Reference Manual)](https://www.gnu.org/software/emacs/manual/html_node/elisp/Obsolete-Functions.html)

**Comment by minad** [comment]
Thanks for your consideration. 

Tbh I would just go with a hard breaking change. 1000 installs is not that much yet and it is better to do it now than later. As a rough rule I consider packages with 10k installs stable (as long as the package address a general audience and isn't highly specialized) - often before that a lot of details are still sorted out. Iirc you announced your packages only a few weeks ago? Also the landscape has changed considerably after your initial announcement, given that you created a number of additional packages. And I guess you are not going to stop... ;)

If you want a somewhat graceful migration path, it could go along the lines you described. Rename casual -> casual-calc and register it separately on MELPA. Then the casual package could serve as a redirect and simply depend on casual-calc and print a warning. It could finally be removed from MELPA. MELPA could add casual-suite separately as proposed in this PR. Alternatively you could replace casual by the casual-suite code, with the risk of annoying users who only want the calc component, but would then get the full suite.

Also note that MELPA from time to time removes archived packages, so hard breaks are not completely unheard of. Maybe the MELPA maintainers also have some recommendations?

**Comment by kickingvegas** [comment]
Ok, going to scrub this PR and come up with a more structured migration plan that will incorporate breaking changes.

**Comment by riscy** [comment]
Correct me if I'm wrong, but this looks like a package that exists solely to install (and runtime-import) a collection of other packages.

On the one hand, yes, it's a single installation (and runtime-import) point.  And this isn't just *any* collection, but a set of related packages maintained by one author.  But my feeling is that a meta-package collection like this doesn't fit the usual criteria.  Per your own Commentary, "it is highly recommended that a deep reading of the install procedure for each porcelain be done beforehand".   This leaves me hesitant to merge this without understanding the real benefits (?)

I'll also note we tend to push back against packages that are just configuration scripts, which this isn't far off from.

**Comment by kickingvegas** [comment]
Multiple asks from different people is what motivated me to make casual-suite. Upon reflection I think this package is justified as it satisfies the two opposing use cases:

- Users who want on-stop shopping. 
- Users who want a la carte selection. 

I would prefer to cater to both types of users. That said, I leave it with you to determine whether casual-suite should be included in MELPA.

**Comment by riscy** [comment]
Alright, I'll merge this one - thanks!

**Comment by kickingvegas** [comment]
@riscy Thanks likewise!

**Pull request merged**
