### PR TITLE
Add unicad pacakge

### PR DESCRIPTION
**Pull request by ukari**
### Brief summary of what the package does

This pacakge is an Elisp program port from Mozilla universal charset auto detector. 

If I add `(set-language-environment "UTF-8")` in the emacs.d config file, my emacs can't detect some charset like gb18030 successfully. With this package it works.

### Direct link to the package repository

https://github.com/ukari/unicad

### Your association with the package

I am the melpa recipe maintainer, and have been got the publish permission from author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks a lot for taking this on -

> and have been got the publish permission from author.

Is this permission publically readable, or can you get Qichen Huang to give a thumbs up here?  I think at the moment the only other source is the Emacsmirror -- https://github.com/emacsmirror/unicad.git.  If not I don't think this is a blocker, but it would be good to have a record.

Also, the default recipe is equivalent in this case, so you can use it instead: `(unicad :repo "ukari/unicad" :fetcher github)`

Finally, these are non-blocking.  But as this package's new maintainer, it would be great if you could "modernize" it:
- This package seems to fit the pattern of a global minor mode.  Creating a global minor mode would standardize idiosyncratic functions like `unicad-enable`, `unicad-disable`, the defalias on `unicad` (which would become `unicad-mode`), and the auto-disable hook (`(add-hook 'kill-emacs-hook 'unicad-disable)`) which is probably unnecessary -- and in the worst case could interfere with people trying to quit Emacs
- Some of the variable names are camelCased (mConfidence, etc.)
- Some of the links are broken and need an update, e.g. the link to Mozilla Universal Charset Detector, and the link which gives citation to Taiwan's Mandarin Promotion Council

**Comment by riscy** [comment]
Feel free to ping when ready for another look.

**Comment by ukari** [comment]
Riscy, thanks for the checking and suggestions!

### Suggestions
- [ ] permission. I would not like to provide it publicly unless it is important. Or also it can be verified by contacting with unicad.el@gmail.com.
- [x] recipe.
- [x] remove `unicad`, M-x `unicad-enable`, M-x `unicad-disable` and  `kill-emacs-hook`. I changed its behaviour to only works during `find-file-noselect` called and within a temporary variable environment.
- [ ] camelCased.
- [x] link updated.

### Checklist
- [x] `byte-compiles`.
- [x] `checkdoc`, `flycheck`, `package-lint`.
- [x] `make recipes/unicad`.
- [x] `make sandbox INSTALL=unicad`.

**Comment by Silex** [comment]
IMHO you'd squash your commits together with a message like "Add unicad recipe" (with an uppercase at the beggining).

**Comment by ukari** [comment]
squashed

**Comment by riscy** [comment]
Thanks for the changes!  I've emailed the original author with:

> Hello,
>
> I can see you are the original author of an Emacs package called unicad.el
> 
> Someone has offered to step in as maintainer (while indexing the package on MELPA) and I wanted to confirm you're on board, if possible.
>
> The discussion is at https://github.com/melpa/melpa/pull/7110 but you can reply to me and, with your permission, paste > your reply for posterity.
> 
> Thanks!

**Comment by riscy** [comment]
Just posting a small update here: still awaiting a reply from the above email address.  Should we give it another week?

**Comment by ukari** [comment]
Please. What would happen if the author just be unreachable?

**Comment by riscy** [comment]
We can just merge after that week.  You did mention you were able to get a nod from the original author, but you mentioned you didn't want to share it.  When were you in contact?

**Comment by ukari** [comment]
2020.8.31.

**Comment by ukari** [comment]
I get the authorization to publish unicad in melpa with license GPLv3 and maintain it, but I did not ask for the permission to publish the origin email.

**Comment by riscy** [comment]
I'm confused.  Why did you write this?

> I would not like to provide it publicly unless it is important.

**Comment by ukari** [comment]
literally, so that I could keep few contact

**Comment by riscy** [comment]
I don't understand but I still think this is fine. :)  You had me under the impression you were in touch with Qichen Huang but wanted to keep the correspondence private.

I haven't received any response to my email, so let's go ahead with this.  Thanks for taking the helm!

**Pull request merged**
