### PR TITLE
Add pythontest recipe

### PR DESCRIPTION
**Pull request by erickgnavar**
-------

### Brief summary of what the package does

Utility functions to run python tests using unittest and pytest, allow to run a whole test suite, a test file or a test
at point

### Direct link to the package repository

https://github.com/erickgnavar/pythontest.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  There appear to be several packages in this space already - can you take a look at https://melpa.org/#/?q=python%20test and distinguish your package's main features?  It's better for users to not be overwhelmed by multiple basic packages doing essentially the same thing.

Also note:
- Invalid SPDX license id `GNU General Public License v3.0 or later`: see https://spdx.dev/ids/ for a list of valid id's

**Comment by erickgnavar** [comment]
> Thanks for this. There appear to be several packages in this space already - can you take a look at https://melpa.org/#/?q=python%20test and distinguish your package's main features? It's better for users to not be overwhelmed by multiple basic packages doing essentially the same thing.
> 
> Also note:
> 
> * Invalid SPDX license id `GNU General Public License v3.0 or later`: see https://spdx.dev/ids/ for a list of valid id's

Hi, thanks for the response. I fixed the SPDX license. Regarding the existing packages, some of them are not longed maintained(as far I can see by their commits history) and the ones that are still active only work for `pytest`. My package works for other kind of testing libraries like regular `unites` and `django`

**Comment by riscy** [comment]
> some of them are not longed maintained(as far I can see by their commits history) 

I'm just looking at https://github.com/Bogdanp/py-test.el for example - do you consider this one no longer maintained?  I see it lets you customize the test-running command, and it had commits last year.  I think you have some really good features, but I'm pushing on this because there are probably already dozens of Python test runners; maybe there is one of them that you can join forces with and even help maintain.

Take another look, and let me know if you genuinely think that your package stands well apart from the rest (e.g. in terms of implementation quality, ease of use, features).

-------------

In the meantime I can offer a couple suggestions on the code:

At the top-level you `(require 'treesit)` but then in `pythontest--get-test-at-point` you check `(unless (featurep 'treesit) ...` - presumably your package won't even load if the first part fails, so the check is probably unnecessary

`pythontest-test-runner` is global variable; what if the user is working in two projects that use different test libraries?  Consider making these buffer-local with defcustom's `:local` keyword.

In `pythontest-change-test-runner` you're using `completing-read` to let the user choose a test-runner but you should check out the documentation on `completing-read` and see the `REQUIRE-MATCH` argument.

The code is potentially inviting the use of a hash map (q.v.), but I think you can deduplicate some lookups by at least writing reusable helpers, e.g. instead of
```
(defun pythontest-test-all ()
  "Run all the project test suite."
  (interactive)
  (cond ((string-equal pythontest-test-runner "unittest")
         (pythontest--run-compile pythontest-unittest-command))
        ((string-equal pythontest-test-runner "pytest")
         (pythontest--run-compile pythontest-pytest-command))
        ((string-equal pythontest-test-runner "django")
         (pythontest--run-compile pythontest-django-command))
        (t (pythontest--not-valid-runner-print-message))))

;;;###autoload
(defun pythontest-test-file ()
  "Run all file test suite."
  (interactive)
  (let* ((command (cond ((string-equal pythontest-test-runner "unittest")
                         (concat pythontest-unittest-command " " (pythontest--unittest-get-file-path)))
                        ((string-equal pythontest-test-runner "pytest")
                         (concat pythontest-pytest-command " " (pythontest--pytest-get-file-path)))
                        ((string-equal pythontest-test-runner "django")
                         (concat pythontest-django-command " " (pythontest--unittest-get-file-path))))))
    (unless command
      (pythontest--not-valid-runner-print-message))
    (pythontest--run-compile command)))
```
you could write:
```elisp
;;;###autoload
(defun pythontest-test-all ()
  "Run all the project test suite."
  (interactive)
  (pythontest--run-compile (pythontest-test-command)))

;;;###autoload
(defun pythontest-test-file ()
  "Run all file test suite."
  (interactive)
  (pythontest--run-compile
   (concat (pythontest-test-command) " " (pythontest-get-file-path))))
```
with corresponding definitions for `pythontest-test-command` and `pythontest-get-file-path`.

**Comment by riscy** [comment]
One more thing I'll add - you will probably want to look into the use of `shell-quote-argument` to ensure that the filenames you pass through to `compile` are escaped against shell control characters and spaces.  It would be a terrible situation, but Python filenames can technically contain these.

**Comment by erickgnavar** [comment]
Reviewing [py-test.el](https://github.com/Bogdanp/py-test.el), my package has a different approach, in that case you have to define the command per project, in my package it just use generic commands and you only have to set the testing runner.

Anyway there is no problem if it is not included in MELPA, it can be installed directly using GitHub repo, I have it that way in my configuration.

Thanks for you suggestions, I applied them to my code and I learnt a little bit more about emacs-lisp :)

**Comment by riscy** [comment]
Sounds good - I'll merge now.

**Pull request merged**
