### PR TITLE
Add double-saber

### PR DESCRIPTION
**Pull request by dp12**
### Brief summary of what the package does
double-saber is used to filter out unwanted search output by narrowing or deleting with regular expressions. 

At the same time, it preserves parts of the search output buffer such as the search command.

### Direct link to the package repository

https://github.com/dp12/double-saber

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by dp12** [comment]
checkdoc gives me a warning that "changes" should probably be imperative "change". 

But I believe checkdoc is in error, because the `undo' function from `simple.el' (part of emacs) has the docstring "Undo some previous changes."

**Comment by manuel-uberti** [comment]
FWIW I gave it a test, and it works as expected. Nice package!

**Comment by purcell** [comment]
Thanks for this, and sorry for the slow turnaround. Quick notes:

- Don't [require `subr-x` only at compile-time](https://github.com/dp12/double-saber/blob/785e5d85e5e6d2feab1468113f423cd4fe98c7e6/double-saber.el#L36) - you're using `string-trim` at runtime, so this makes no sense.
- Your code for tracking and maintaining the read-only state of the buffer is much more complex than it needs to be: all you need to do is let-bind `inhibit-read-only` to `t` while you modify the buffer.
- The [`double-saber-mode-setup`](https://github.com/dp12/double-saber/blob/785e5d85e5e6d2feab1468113f423cd4fe98c7e6/double-saber.el#L148) function is unidiomatic, and you shouldn't be modifying other modes' keymaps. Instead, define a minor mode called `double-saber-mode`, with its own keymap, and then users can enable it automatically or manually as needed, just like any other minor mode.

Otherwise looks good, and useful!

**Comment by dp12** [comment]
Thanks for the suggestions! I think I've addressed the points you mentioned.

**Comment by dp12** [comment]
Thanks again for the comments! I added the check you suggested and and'ed it with the original fboundp check (because flycheck was complaining about not knowing about `undo-tree-redo` and `undo-tree-undo`)

**Comment by manuel-uberti** [comment]
I used the last version @dp12 has on his repository, and it works as expected. Great stuff. :+1:

**Comment by purcell** [comment]
Thanks - merged now, and sorry for the slow turnaround. Welcome to MELPA! :tada:

**Pull request merged**
