### PR TITLE
add recipes <lacquer>

### PR DESCRIPTION
**Pull request by dingansichKum0**
### Brief summary of what the package does

Lacquer is a util that switches theme/font/font-size and to configure cache ;)
Use both the seletor and the shortcut key to switch themes/font.
Load previous theme/font/font-size after restarting the emacs.
Each theme can be configured individually.
Download unused themes automatically with package.el.
Generate interactive function automatically.

### Direct link to the package repository

https://github.com/dingansichKum0/lacquer

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hello, this is just a very quick pass over the checklist --

### lacquer.el ###

byte-compile (using Emacs 27.1):
```
lacquer.el:374:1:Error: Symbol's value as variable is void: lacquer/theme-list
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
```
21 issues found:
98:0: error: `lacquer/theme-list' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
106:0: error: `lacquer/default-theme' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
111:0: error: `lacquer/font-list' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
119:0: error: `lacquer/default-font' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
124:0: error: `lacquer/default-font-size' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
129:0: error: `lacquer/cache' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
134:0: error: `lacquer/theme-prefix-key' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
139:0: error: `lacquer/font-prefix-key' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
144:0: error: `lacquer/keys-map-index' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
152:0: error: `lacquer/theme-selector-key' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
157:0: error: `lacquer/font-selector-key' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
162:0: error: `lacquer/font-increase-key' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
167:0: error: `lacquer/font-decrease-key' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
172:0: error: `lacquer/current-theme-key' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
177:0: error: `lacquer/current-font-key' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
182:0: error: `lacquer/font-size-step' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
188:0: error: `lacquer/started' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
192:0: error: `lacquer/theme-name-list' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
196:0: error: `lacquer/setting' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
313:3: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
326:3: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

Other [lints](https://github.com/riscy/melpazoid):
- lacquer.el#L192: There is no need to quote lambdas (neither #' nor ')
- lacquer.el#L365: Top-level `define-key` can sometimes overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- lacquer.el#L230: No `format` required; `message` takes an f-string
- lacquer.el#L306: No `format` required; `message` takes an f-string

### setting.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
- No issues!


### utils.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
- No issues!

### Package ###

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to setting.el
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to utils.el

**Comment by dingansichKum0** [comment]
thanks! I've already modified refers to the checklist, however, not yet got any good idea on how to solve errors about byte-compile.
Please kindly advise. Many thanks.

**Comment by riscy** [comment]
Here are the latest --

byte-compile (using Emacs 27.1):
```
lacquer.el:371:1:Error: Symbol's value as variable is void: lacquer-theme-list
```
The Emacs byte compiler attempts to expand/evaluate macros before it gets to anything else (in this case probably your `lacquer-macro-factory` is being expanded before the byte-compiler has a chance to get to bringing the variable in).  I believe this is the result of a [wrong time](https://www.gnu.org/software/emacs/manual/html_node/elisp/Problems-with-Macros.html#Problems-with-Macros) issue, and probably points to a bug (if the user modifies `lacquer-theme-list`, the code won't be updated correspondingly).

And this one's easy :)  -- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible.  See: https://github.com/licensee/licensee

**Comment by dingansichKum0** [comment]
I have resolved this error and added LICENSE.

**Comment by riscy** [comment]
Thank you, that'll put the checklist behind us.  Looking more carefully into the code and what it does I have a couple more high-level comments:

- This looks neat, although there are a number of packages on MELPA that do similar things.  As a matter of course, can you describe how this compares to e.g. [theme-changer](https://melpa.org/#/theme-changer), [circadian](https://melpa.org/#/circadian), and [cycle-themes](https://melpa.org/#/cycle-themes)?  (Adding links to these alternatives in your README is also a good idea.)
- I think calling your helper files `support.el` and `utils.el` is inviting namespace collisions with other packages that make the same (ill advised) choices -- i.e., who knows what `(require 'utils)` might point to on other people's Emacsen?  Naming these files something like `lacquer-support.el` and `lacquer-utils.el` would be a better choice, or even just recombining these into a single file.
- Your summary line "A util that switches theme/font and to configure cache" could probably more succinct, what about something like "Switch theme/font by selecting from a cache"?
- Extremely minor, but you're using `list` as a customization type where I think you want to be using `set` (see [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Composite-Types.html))
- All the machinery around creating your own DSL for a lacquer cache/config file seems extraneous.  It would make more sense to me and require far less parsing logic if you used Elisp itself as a config language.  Alternatively you even use the builtin `customize-save-variable`

**Comment by riscy** [comment]
I'll mark this awaiting upstream, but feel free to ping me.

**Comment by dingansichKum0** [comment]
Sorry for being busy this week...

To be honest, I was doing this package for one's own needs at first, I haven’t noticed some packages own similar functions are there already in MELPA. 
For me, lacquer is more than a combination of circadian and cycle-themes, it has so many new features, such as, allows users to switch themes and fonts in a more convenient way, to customize each theme, also to define specifically when to switch themes automatically.

I think I have done the checklist. Thank you for your time.

**Comment by riscy** [comment]
Apologies for the big delay on seeing this.  

> To be honest, I was doing this package for one's own needs at first, I haven’t noticed some packages own similar functions are there already in MELPA.

I think this is the best approach to writing packages.  MELPA sort of has this aim of originality and novelty and so we encourage people to collaborate on existing packages when possible, but that shouldn't stop you of course.

That said, I think you make a good case for this to be added.  There may have been some changes to the code since I last checked, so apologies for the repetition, but these issues mentioned in my first comment got lost in the shuffle:

- lacquer.el#L252: There is no need to quote lambdas (neither #' nor ')
- lacquer.el#L492: Top-level `define-key` can sometimes overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- lacquer.el#L319: No `format` required; `message` takes an f-string
- lacquer.el#L405: No `format` required; `message` takes an f-string
- lacquer.el#L421: No `format` required; `message` takes an f-string

**Comment by dingansichKum0** [comment]
I'm sorry because the branch was merged from "devlop". 
I think I have completed the list. Thank you for your time.

**Comment by riscy** [comment]
Thank you, looks good.  And, welcome to MELPA. :)

**Pull request merged**
