### PR TITLE
Add a recipe for an i3wm interface package

### PR DESCRIPTION
**Pull request by swflint**
### Brief summary of what the package does

Provides an interface to the i3wm IPC system.

### Direct link to the package repository

https://git.flintfam.org/swflint/emacs-i3wm

### Your association with the package

I am maintaner.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by swflint** [comment]
The TravisCI apparently has issues with my certificate (it's through CACert, so IDK).  My apologies.

**Comment by swflint** [comment]
It looks like the SSL cert issue should be fixed now.  Is there any way to re-trigger a CI check?

**Comment by xuchunyang** [comment]
- [Autoload cookies](https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html) are missing for interactive commands.
- It looks like cl-lib is not actually used, if it is true, then there is no need to declare it as dependency and require it.

**Comment by swflint** [comment]
I forgot about those.  I had it left in, as I thought I was going to need it, turns out I didn't (or at least don't yet).

**Comment by purcell** [comment]
Is the repo not publicly browsable? I just get redirected to the gitlab login, which makes it a fair bit less convenient to review the package.

**Comment by swflint** [comment]
It should be publicly browsable.  What url did you use?

**Comment by xuchunyang** [comment]
> Direct link to the package repository
> 
> https://git.flintfam.org/swflint/emacs-i3wm

@swflint the right one probably is https://git.flintfam.org/swf-projects/emacs-i3 according to your commit.

**Comment by swflint** [comment]
That is correct.

**Comment by tarsius** [comment]
* Please correct URL in the library header.
* Please fill in the Commentary section.

**Comment by swflint** [comment]
Done and done.

**Comment by purcell** [comment]
Quick feedback from me:

I'd suggest that you could improve the docstrings easily by going from
```el
(defun i3wm-tabbed ()
   "I3wm-tabbed.

Switch to a tabbed layout."
   (i3wm-command "layout tabbed"))
```
to
```el
(defun i3wm-tabbed ()
   "Switch to a tabbed layout."
   (i3wm-command "layout tabbed"))
```

Similarly, `"I3wm-command COMMAND &rest ARGUMENTS"` inside a docstring isn't very helpful!

More critically, if you're going to build command lines with code like `(i3wm-command "exec --no-startup-id %s" program)`, you're in for a bad time if (when!) `program` contains spaces or quotes. Use `shell-quote-argument` to escape it first. :-)

And finally, I suspect it might be useful to make all of those command wrapper functions `interactive` so users can invoke them directly if so desired.

Hope that helps!

**Comment by swflint** [comment]
Changes as suggested have been made.

**Comment by syohex** [comment]
You need to specify requirements minimum version. If package requires any versions, you specify like `Package-Requires: ((json "0"))`. However json.el is a standard package so you need not to specify it.

**Comment by swflint** [comment]
So I can just get rid of the package-requires header then?

**Comment by syohex** [comment]
> So I can just get rid of the package-requires header then?

Yes

**Comment by swflint** [comment]
And done!

**Comment by syohex** [comment]
Merged

**Comment by swflint** [comment]
Thanksl

**Comment by tarsius** [comment]
@swflint Are you keeping the old `pushover` and `buffer-sets` repositories on Github up-to-date? If not, then you should probably remove them or provide a link to the new repositories on your Gitlab instance.

**Comment by swflint** [comment]
As of now, I don't plan on it.  That's probably a good point, will do.

**Comment by tarsius** [comment]
@swflint 

I am having issue pulling your repositories again:

```
git clone https://git.flintfam.org/swf-projects/buffer-sets.git
Cloning into 'buffer-sets'...
fatal: unable to access 'https://git.flintfam.org/swf-projects/buffer-sets.git/': server certificate verification failed. CAfile: none CRLfile: none
```

**Comment by swflint** [comment]
Try again?  It should be fixed by now.

**Comment by tarsius** [comment]
Having issues again:

```
jonas@p2:/tmp$ git clone https://git.flintfam.org/swf-projects/buffer-sets.git
Cloning into 'buffer-sets'...
fatal: unable to access 'https://git.flintfam.org/swf-projects/buffer-sets.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
jonas@p2:/tmp$ git clone git@git.flintfam.org:swf-projects/buffer-sets.git
Cloning into 'buffer-sets'...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@       WARNING: POSSIBLE DNS SPOOFING DETECTED!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The ED25519 host key for git.flintfam.org has changed,
and the key for the corresponding IP address 2001:19f0:b001:2fc:5400:2ff:fe81:94f
is unknown. This could either mean that
DNS SPOOFING is happening or the IP address for the host
and its host key have changed at the same time.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:apVhpPvr7T6opOd3FdpqLKYvVGQzoJ0wQYC2QH30eYw.
Please contact your system administrator.
Add correct host key in /home/jonas/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/jonas/.ssh/known_hosts:60
  remove with:
  ssh-keygen -f "/home/jonas/.ssh/known_hosts" -R "git.flintfam.org"
ED25519 host key for git.flintfam.org has changed and you have requested strict checking.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by swflint** [comment]
SSH has changed.

**Comment by swflint** [comment]
Remote host SSH keys have changed.  I thought I had gotten all of the necessary intermediaries, interesting.

**Comment by tarsius** [comment]
So you can confirm that SHA256:apVhpPvr7T6opOd3FdpqLKYvVGQzoJ0wQYC2QH30eYw is the current key?

**Comment by swflint** [comment]
If that matches the SSHFP record, it's correct.

**Comment by tarsius** [comment]
After figuring out how to confirm that, I can report that it does. Unfortunately I am being asked for a password (this is not surprising, but since https isn't working I just thought I would give it a try).

So back to https, which unfortunately still results in the same error.

**Comment by tarsius** [comment]
@swflint These issues persist. Neither Melpa nor the Emacsmirror have been able to pull you packages for a few years. Thank you!

**Comment by swflint** [comment]
It should be fixed now (hopefully).

**Comment by tarsius** [comment]
Seems to work now. Thanks!

**Pull request merged**
