### PR TITLE
Add flycheck-keg recipe

### PR DESCRIPTION
**Pull request by conao3**
### Brief summary of what the package does

Flycheck for Keg project.
This is Keg version of [flycheck-cask](https://github.com/flycheck/flycheck-cask).

### Direct link to the package repository

https://github.com/conao3/keg.el

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Minor, but I wonder if the summary line should be "Flycheck for Keg projects"?  Non-blocking of course.

**Comment by conao3** [comment]
Thanks!

**Comment by akirak** [comment]
@conao3 You may have to update [the recipe for keg](https://github.com/melpa/melpa/blob/master/recipes/keg) to exclude `flycheck-keg.el`, like [this](https://github.com/melpa/melpa/pull/6266) :)

**Comment by akirak** [comment]
@conao3 This would be a solution:

```
(keg :fetcher github :repo "conao3/keg.el"
     :files (:defaults (:exclude "keg-mode.el" "flycheck-keg.el")))
```

Is `keg-ansi` a separate package (or not yet)?

**Comment by conao3** [comment]
Thanks. I should do that, I've forgotten to do that.

**Pull request merged**
