### PR TITLE
Add vale-mode recipe

### PR DESCRIPTION
**Pull request by jaybosamiya**
### Brief summary of what the package does

This package adds support for editing [Vale](https://github.com/project-everest/vale/) (Verified Assembly Language for Everest) files, and interacting with the interactive prover. It adds syntax highlighting, interaction support and also keybindings that help set up relevant tags for quickly moving around the code.

### Direct link to the package repository

https://github.com/jaybosamiya/vale-mode.el

### Your association with the package

I'm the maintainer of this package.

### Relevant communications with the upstream package maintainer

**None Needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by jaybosamiya** [comment]
Thanks @riscy! I too believe defining an `indent-line-function` would be one of the next few steps in improving productivity in this mode, and it is high on my priorities for this mode. I tried writing it earlier but it indeed wasn't as easy as I'd initially thought it'd be, so I decided I'd temporarily postpone implementing that.

The other suggestions also all make sense, and I've updated them based on what you've suggested. Thanks again for doing a review! :)

**Comment by jaybosamiya** [comment]
@riscy : Anything else that I need to do to get this merged in? Thanks!

**Comment by riscy** [comment]
Thanks for your patience - this looks good!  And welcome to MELPA. :)

**Comment by jaybosamiya** [comment]
Thanks a lot! :)

**Pull request merged**
