### PR TITLE
Add recipe for evil-pinyin

### PR DESCRIPTION
**Pull request by laishulu**
### Brief summary of what the package does

Evil search Chinese characters by pinyin

### Direct link to the package repository

https://github.com/laishulu/evil-pinyin

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by laishulu** [comment]
# Lint result
lint

## Clarification
About the prefix issue: it's the proper usage of the `names` package to manage the namespace
```
(define-namespace evil-smart-input-source-
```
together with
```
;; end of namespace
)
```
# Checkdoc Result
doc

# Compile Result
compile

## Clarification
Caused by the usage of the `names` package to manage the namespace

**Comment by riscy** [comment]
Noted about the namespacing, thanks.  Quick first pass with that in mind:

byte-compile (using Emacs 26.3):
```
evil-pinyin.el:152:29:Warning: reference to free variable `evil-snipe-aliases'
evil-pinyin.el:155:28:Warning: reference to free variable `evil-pinyin-mode'
In evil-pinyin--pattern-regex-advice:
evil-pinyin.el:163:14:Warning: reference to free variable `evil-pinyin-mode'
In evil-pinyin-mode:
evil-pinyin.el:208:17:Warning: define-key called with 2 arguments, but
    requires 3
In end of data:
evil-pinyin.el:222:1:Warning: the function `-advice' is not known to be
    defined.
```

Also I see on lines 177/215 you're using `fset` to override a function definition, but this will interfere with that function's definition in other buffers.  I believe it would be more idiomatic to use Emacs's advice utilities (i.e. `:around` advice), and also to check whether the minor mode is active before modifying its behavior.

**Comment by laishulu** [comment]
fixed.
please check again.

**Comment by riscy** [comment]
Thanks -- here's the latest:

byte-compile (using Emacs 26.3):
```
evil-pinyin.el:150:29:Warning: reference to free variable `evil-snipe-aliases'
evil-pinyin.el:220:3:Warning: reference to free variable `evil-pinyin-mode'
In evil-pinyin-evil-snipe--process-key-advice:
evil-pinyin.el:221:3:Warning: reference to free variable `evil-pinyin-mode'
In evil-pinyin-evil-ex-pattern-regex-advice:
evil-pinyin.el:166:23:Warning: reference to free variable `evil-pinyin-mode'
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
evil-pinyin.el:159: Argument `key' should appear (as KEY) in the doc string
Warning (emacs): 
evil-pinyin.el:165: Lisp symbol `evil-ex-pattern-regex' should appear in quotes
```

**Comment by laishulu** [comment]
I forget to recheck after handle some user's feature request.
Sorry for the bothering.

Now, both `checkdoc` and `byte-compile` gives no warnings.
pleas check.

**Comment by laishulu** [comment]
@riscy Any progress?

**Comment by riscy** [comment]
Here's the latest:

### evil-pinyin.el ###

byte-compile (using Emacs 26.3):
```
evil-pinyin.el:195:31:Warning: reference to free variable `evil-snipe-aliases'
```
A `defvar` should solve this warning safely.

checkdoc (using version 0.6.1):
```
Warning (emacs): 
evil-pinyin.el:210: Lisp symbol `evil-ex-pattern-regex' should appear in quotes
```
It's referring to a ``` `/' ``` quote pair.  

I'll trust you to fix these, since they're fairly small.  Thanks!

**Comment by laishulu** [comment]
fixed.

Thanks!

**Pull request merged**
