### PR TITLE
Add info-buffer recipe

### PR DESCRIPTION
**Pull request by llvilanova**
### Brief summary of what the package does

Interactive command (info-display-manual-in-buffer) for showing each info topic on its own buffer. With prefix, always creates a new buffer even if the topic is already opened.

### Direct link to the package repository

https://github.com/llvilanova/info-buffer

### Your association with the package

Author & maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Looks good.

**Comment by purcell** [comment]
Thanks - looks good to me. I've got a couple of quick comments, but I'll go ahead and merge the recipe in the meantime:
- The prompt for `info` says `"Info file name: "`, but you're using `"Manual name: "` -- surely these should match?
- `Display info topics on separate buffers` should be `Display info topics in separate buffers` :-)

**Comment by llvilanova** [comment]
Quick one, how do I manage new versions of the package? Do you detect new tags or should I send a new pull request?

Also, I'm not sure about the prompt. C-u M-x info asks specifically for a file, while info-buffer asks for the name of a registered "info manual", not a file.

**Comment by syohex** [comment]
> Quick one, how do I manage new versions of the package? Do you detect new tags or should I send a new pull request?

You update `info-buffer` repository then melpa updates after some hours. (You add new tag, then melpa-stable updates it too). You need not to send pull request again.

**Pull request merged**
