### PR TITLE
Recipe: Add magit-todos

### PR DESCRIPTION
**Pull request by alphapapa**
### Brief summary of what the package does

This package displays keyword entries from source code comments and Org files in the Magit status buffer. Activating an item jumps to it in its file. 

### Direct link to the package repository

https://github.com/alphapapa/magit-todos

### Your association with the package

Author and maintainer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

Thanks.

### CODE REVIEW

**Comment by matthew-piziak** [comment]
Any updates here?

**Comment by alphapapa** [comment]
Don't worry, it will probably be reviewed soon.  There's a bit of a backlog, and reviewing new packages is mostly done just by Steve.  In the meantime, you can install it using other tools like `straight`, `quelpa`, `el-get`, `borg`, etc.

**Comment by DamienCassou** [comment]
Please run linters on the file. The `Package-Requires` line is incorrect and some docstrings are incomplete.

**Comment by matthew-piziak** [comment]
I've never submitted to MELPA so I don't know how the process works, but I've made a PR to try and fix the linting. Hope it helps! https://github.com/alphapapa/magit-todos/pull/22/files

**Comment by alphapapa** [comment]
@DamienCassou My apologies, when I first submitted the PR there were no package-lint warnings, but I made some changes since then.

**Comment by tarsius** [comment]
> The version of hl-todo I have installed has no version header,

None of my libraries have a version header because that would be incorrect most of the time - it would only be correct for that one commit that actually has been tagged with the same version string. Melpa gets the version from the tag anyway. So you should depend on `1.9.0`.

Of course because all melpa snapshot releases have timestamps as "versions" you cannot really specify the minimal version. For Magit itself I actually depend on a snapshot because it is popular enough for issues to arise every time if I didn't do that (except for tagged commits, those depend on actual releases, which I then revert in the very next commit). But for smaller packages it is not worth the effort.

**Comment by alphapapa** [comment]
Thanks, Jonas.  What I've been doing for version headers is appending `-pre` to it in the untagged commits, so e.g. `1.1.0-pre`.  Then when I tag a version/release, I remove the `-pre`, tag the commit as e.g. `1.1.0`, and then increment the version and append `-pre` again in the next commit, e.g. `1.2.0-pre`.  According to the Emacs version-parsing code, that's a valid specification.  Would that work for Magit?  (Not that I would tell you how to do things. ;)

**Comment by alphapapa** [comment]
@DamienCassou The package should be fit for MELPA now.  Thanks.

**Comment by purcell** [comment]
Looks good, thanks - sorry it's taken a long time for me to get to this.

**Comment by alphapapa** [comment]
No problem, Steve.  I appreciate all you do for MELPA.

**Pull request merged**
