### PR TITLE
Add tron-legacy-theme recipe

### PR DESCRIPTION
**Pull request by ianpan870102**
### Brief summary of what the package does

Tron: Legacy is an original theme inspired by the look and feel of the Tron movie. The use of contrast and colours are also inspired by Base16-Black-Metal, Doom, Grayscale and City Lights.

### Direct link to the package repository

https://github.com/ianpan870102/tron-legacy-emacs-theme

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Cool.  Quick first pass --

### tron-legacy-theme.el ###

byte-compile-file (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200419.406):
```
4 issues found:
38:0: error: "tron-legacy-dark-fg-bright-comments" doesn't start with package's prefix "tron-legacy-theme".
43:0: error: "tron-legacy-vivid-cursor" doesn't start with package's prefix "tron-legacy-theme".
162:5: error: You should depend on (emacs "24.1") if you need `org-date'.
166:5: error: You should depend on (emacs "24.1") if you need `org-block'.
```
I think the `emacs "24.1"` are false positives, but the nags on 38 and 43 should probably fixed (in case someone wants to add a "tron-legacy-mode" :) )

Suggestions/experimental static checks:
- tron-legacy-theme.el#L20: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by ianpan870102** [comment]
Hey Chris @riscy, thanks for getting back! I've fixed the following as per your suggestions (thanks for the links too):

1. Fix start with package prefix "tron-legacy-theme"
2. Incorporate lexical binding (by appending the comment in the first line)
3. Change http to https.

The package is ready for your final review.

**Comment by ianpan870102** [comment]
@riscy friendly ping

**Comment by riscy** [comment]
Looks good to merge.  Non-blocking, but you will want to change "orginal" in your summary line to "original".  Thanks, and welcome to MELPA!

**Comment by ianpan870102** [comment]
> "orginal" in your summary line to "original

Cheers! updated

**Pull request merged**
