### PR TITLE
Add recipe for buffer-watcher

### PR DESCRIPTION
**Pull request by NicolasPetton**
### Brief summary of what the package does

Buffer-watcher makes it easy to run shell scripts per file type/directory when a buffer is saved.

### Direct link to the package repository

https://github.com/nicolaspetton/buffer-watcher

### Your association with the package

I'm the author of the package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
What's different from [firestarter](https://github.com/wasamasa/firestarter) ?

**Comment by NicolasPetton** [comment]
@syohex I didn't about this package, but from what I saw, it's a bit different: to run shell commands for buffers of a specific mode in a project with firestarter, you have to use `.dir-locals.el` in the project directories, while `buffer-watcher` uses a custom var `buffer-watcher-commands` that you can put in `custom.el` or anywhere in your `.emacs.d`.

**Comment by mattiasb** [comment]
FWIW the dir-locals stuff doesn't mandate using actual `.dir-locals.el` files. 

A (modified) example from my config (this sets code style rather than firestarter-settings though):
```elisp
(c-add-style
 "my-style"
 '("stroustrup"
   (c-basic-offset  . 2)
   (c-offsets-alist . ((innamespace       . 0)
                       (substatement-open . 0)
                       (inline-open       . 0)))))

(dir-locals-set-class-variables
 'my-code
 '((c++-mode . ((c-file-style . "my-style")))))

(dir-locals-set-directory-class "~/Code/my-repo/" 'my-code)
```

**Comment by syohex** [comment]
This package sets `buffer-watcher-run-commands` to `after-save-hook` only by loading. I suppose this package provides global minor-mode instead of it.

**Comment by manuel-uberti** [comment]
Any chance of merging this?

**Comment by manuel-uberti** [comment]
Anything? :)

**Comment by purcell** [comment]
@manuel-uberti - this is currently closed, so not on our radar. Is that wrong?

**Comment by manuel-uberti** [comment]
Maybe @NicolasPetton can tell us more.

**Comment by NicolasPetton** [comment]
This PR was closed because firestarter offers similar features. I don't mind but I still use buffer-watcher, and if the package can be useful for others, we could reopen the PR.

**Comment by manuel-uberti** [comment]
Well, I prefer the approach of `buffer-watcher` with a defcustom instead of using dir-locals, but I see your point.

If it's not much of a problem, I'd very much like `buffer-watcher` on MELPA.

**Comment by purcell** [comment]
Added in c8681776. An autoloaded global minor mode would be slightly neater than enabling this by simply calling `require`.

**Comment by manuel-uberti** [comment]
Thank you @purcell. A minor mode would be much appreciated, of course :+1:

**Pull request closed without merging**
