### PR TITLE
Add temporary-persistent recipe please

### PR DESCRIPTION
**Pull request by kostafey**
### Brief summary of what the package does

temporary-persistent - easy way to switch temp buffers and keep them persistent.
Like notes. But simpler ;). No special mode, no timers.

### Direct link to the package repository

https://github.com/kostafey/temporary-persistent

### CODE REVIEW

**Comment by syohex** [comment]
There are too many byte-compile warnings please check them.

**Comment by kostafey** [comment]
@syohex, Thank you, fixed.

**Comment by purcell** [comment]
Please can you add a `Commentary` section so that people might have a clue about how to use this? :-)

Overall I'm not exactly sure why you're reinventing the `buffer-file-name` functionality. Seems like you could use the built-in file/buffer machinery for much of this.

Also, don't use `melpa.milkbox.net` in the MELPA setup instructions, please - melpa.org is the way to go, or - better - refer people to our setup instructions, which will always be up-to-date.

**Comment by kostafey** [comment]
@purcell Ok, fixed. Thank you for code checking.

**Comment by syohex** [comment]
Looks good

**Comment by purcell** [comment]
Thanks, sorry for the slow response. Busy end of year here.

**Pull request merged**
