### PR TITLE
Add recipe for modus-operandi-theme

### PR DESCRIPTION
**Pull request by protesilaos**
### Brief summary of what the package does

Light theme designed for colour-contrast accessibility. Each combination of foreground and background colour values has a minimum contrast ratio of >= 7:1. This complies with the highest accessibility standard: WCAG AAA.

### Direct link to the package repository

https://gitlab.com/protesilaos/modus-themes

### Your association with the package

I am the creator and maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
You might consider combining these themes into a single package, ala `doom-themes`.

**Comment by protesilaos** [comment]
Thanks for the feedback! I just thought it would be preferable to offer them as separate packages because one is not a pre-requisite for the other. Furthermore, and based on feedback I have received, users choose one or the other.

My approach on this was further inspired by the [dired-hacks repo](https://github.com/Fuco1/dired-hacks) that I use, which offers standalone packages like `dired-subtree`, `dired-collapse`…

At any rate, I am perfectly willing to combine them into a single package if the MELPA maintainers feel it is a better choice, for reasons they may provide.

**Comment by riscy** [comment]
That sounds like good reasoning to me.  I have only one comment, but this one is not a blocker:

- modus-operandi-theme.el#L24: Prefer `https` over `http` (if possible)

With that said, welcome to MELPA! :)

**Comment by protesilaos** [comment]
I just addressed that lint. Thank you for this and all the work you are doing.

**Pull request merged**
