### PR TITLE
Add recipe for recall

### PR DESCRIPTION
**Pull request by svaante**
### Brief summary of what the package does

This package uses `add-advice` on `make-process` and friends to store
metadata like; working directory, stdout, start time, end time, exit
code and version control revision for Emacs processes.  It defines
commands to view and manage both currently running processes and
historical processes, accessible via the minibuffer and/or a
specialized `tabulated-list` buffer.

Out of the box `recall` supports (see `recall-buffer-match`):
- `async-shell-command`
- `compile`
- `eshell`
- `dired-do-async-shell-command`

Joining the functionality of bash reverse-i-search with `proced`.

### Direct link to the package repository

https://github.com/svaante/recall

### Your association with the package

maintainer

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
This looks very interesting.  I could imagine it being especially useful for debugging while developing Elisp code related to processes.  It would probably be a good idea to mention a few use case examples in the readme.  :)

**Comment by riscy** [comment]
>  It would probably be a good idea to mention a few use case examples in the readme. :)

Agreed - and if one of them is pithy enough that it makes sense to put in the `;;; Commentary`, all the better!

Here's a quick first pass in the meantime -

⸺ `recall.el` with package-lint 20240923.1044:
```
4 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
53:10: warning: This file is not in the `cl-lib' ELPA compatibility package: require `cl-lib' instead.
702:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
784:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

⸺ `recall.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- recall.el#L371: It's safer to sharp-quote function names; use `#'`
- recall.el#L444: It's safer to sharp-quote function names; use `#'`
- recall.el#L399: It's safer to sharp-quote function names; use `#'`
- recall.el#L509: It's safer to sharp-quote function names; use `#'`
- recall.el#L799: It's safer to sharp-quote function names; use `#'`
- recall.el#L805: It's safer to sharp-quote function names; use `#'`
- recall.el#L796: It's safer to sharp-quote function names; use `#'`
- recall.el#L797: It's safer to sharp-quote function names; use `#'`
- recall.el#L798: It's safer to sharp-quote function names; use `#'`
- recall.el#L802: It's safer to sharp-quote function names; use `#'`
- recall.el#L803: It's safer to sharp-quote function names; use `#'`
- recall.el#L804: It's safer to sharp-quote function names; use `#'`
- recall.el#L3: Have you done the paperwork to assign this copyright?
- recall.el#L66: Use `(temporary-file-directory)` instead of /tmp in code
- recall.el#L265: You may want to prefer `(derived-mode-p 'xyz)`
- recall.el#L474: Loading a package should rarely add hooks (also you probably mean `ansi` intead of `asni`)
- recall.el#L232: Consider using %R instead of %H:%M in time strings
- recall.el#L546: `concat` may be unneeded; `insert` can take multiple arguments
```

⸺ Package and license:
- Please specify `:fetcher` before `:repo` in your recipe

**Comment by svaante** [comment]
Thanks for taking a look, I have updated the none duds from [melpazoid](https://github.com/riscy/melpazoid).
Have also done a new take on the Readme/Commentary.

> This looks very interesting. I could imagine it being especially useful for debugging while developing Elisp code related to processes. It would probably be a good idea to mention a few use case examples in the readme. :)

This has been one if it's usecase, but I manly use it for launching processes and keeping track of them + metadata.  I launch shell commands mainly with compile and shell-command and recall-rerun and recall-rerun-edit lets me rerun stuff and with embark I can kill those process and lookup the stdout of an two week old command etc.. all from the same minibuffer interface.

I hope that makes sense

**Comment by riscy** [comment]
Here's the latest -

⸺ `recall.el` with package-lint 20240923.1044:
```
3 issues found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
710:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
801:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```
I think the second one (line 710) is legitimate.  Will a user who uses embark automatically (and implicitly) want their keybindings modified, just because recall.el is loaded in?  A minor mode for supporting embark would give users a toggle they could turn off and on again, hence the warning (i.e., let the user configure this sort of thing).

I think the third one is legitimate too.  Instead of altering to another completing-read function as soon as a user loads in consult, you could have one function and use `featurep` to dispatch to the two different behaviors.


⸺ `recall.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- recall.el#L378: It's safer to sharp-quote function names; use `#'`
- recall.el#L451: It's safer to sharp-quote function names; use `#'`
- recall.el#L406: It's safer to sharp-quote function names; use `#'`
- recall.el#L518: It's safer to sharp-quote function names; use `#'`
- recall.el#L3: Have you done the paperwork to assign this copyright? Copyright (C) 2023 Free Software Foundation
- recall.el#L272: You may want to prefer `(derived-mode-p 'xyz)`
- recall.el#L481: Loading a package should rarely add hooks
```

I think all of these are still salient - note for the add-hook, the hook is a variable you already control, so you don't need to add to it, you can just specify that as its default value.

**Comment by svaante** [comment]
Sharp quoted the rest in d5dfbb9

> I think the second one (line 710) is legitimate. Will a user who uses embark automatically (and implicitly) want their keybindings modified, just because recall.el is loaded in? A minor mode for supporting embark would give users a toggle they could turn off and on again, hence the warning (i.e., let the user configure this sort of thing).

I am not sure if I agree, `recall` adds embark `category` bindings for
`'recall` so we are not overwrite any other bindings.

I find it to be user hostile to force users to have larger
configurations then necessary.

> I think the third one is legitimate too. Instead of altering to another completing-read function as soon as a user loads in consult, you could have one function and use featurep to dispatch to the two different behaviors.

I see your point that it might be confusing if consult is loaded at a
later point.  But I would argue that this never comes up.  But if
consult is loaded the user most certainly would like the superior
interface that consult enables.

> - recall.el#L3: Have you done the paperwork to assign this copyright? Copyright (C) 2023 Free Software Foundation
Yes

> - recall.el#L481: Loading a package should rarely add hooks
This is common, and should be no issue to add hooks to package owned
vars.

/Pettersson

**Comment by alphapapa** [comment]
@svaante 

> I find it to be user hostile to force users to have larger configurations then necessary.

What's even more user-hostile is to do things that a user didn't ask for or expect, invisibly causing breakage that wastes their time trying to track down the source and fix it.  The old, "What?  It was working fine yesterday!  I haven't made any changes to my config!  All I did was install this package that...oh..." kind of problem.

You should keep in mind that MELPA has been around a long time now, and its policies were developed over time to address real problems.  MELPA is not here to make developers' work harder; MELPA is here to make it easier for developers to distribute their work, and to make it easier for users to find, install, and use hundreds and thousands of packages together without their causing conflicts (since Emacs has no real barriers between packages, we have conventions, policies, and developers' good will--which has worked surprising well).

So when you submit a package to MELPA, please take review comments as intended: not as criticism of you or your work, but as hard-won wisdom, being handed down to colleagues and future stewards, from those who have tread these roads many times before, who want all of this to still be around and working smoothly decades from now.  A reputation is destroyed in merely a moment.

**Comment by svaante** [comment]
@riscy I do see your point but I don't believe that all cases are created equally,  I budged on the consult with after load.  Which now requires `(setopt recall-completing-read-fn #'recall-consult-completing-read)`.

@alphapapa
> So when you submit a package to MELPA, please take review comments as intended: not as criticism of you or your work, but as hard-won wisdom, being handed down to colleagues and future stewards, from those who have tread these roads many times before, who want all of this to still be around and working smoothly decades from now. A reputation is destroyed in merely a moment.

I interpret this as you see my response as being hostile that was not my intention,  I do genuinely appreciate the work that you do in keeping up a standard for melpa. (both @alphapapa and @riscy)

I just didn't agree with all the linting rules upfront, I can see that they are in general good advice they are also in part *just* opinions.  If this package submission jeopardizes the reputation of melpa feel free to remove it, no hard feelings.  I just thought the package was useful enough to share.

**Pull request merged**
