### PR TITLE
Add recipe for hyprlang-ts-mode

### PR DESCRIPTION
**Pull request by Nathan-Melaku**
### Brief summary of what the package does

A treesitter major mode for editing hyprland config files in emacs.

### Direct link to the package repository

https://github.com/Nathan-Melaku/hyprlang-ts-mode

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

⸺ `hyprlang-ts-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- `;;; Commentary` is much wider than 80 characters
```
Easy fix with `M-q` for instance.  The issue being that downstream utilities won't know how to wrap this, and it should be wrapped, so we might as well go with something consistent.

⸺ Package and license:
- Prefer equivalent recipe: `(hyprlang-ts-mode :fetcher github :repo "Nathan-Melaku/hyprlang-ts-mode")`
- hyprlang-ts-mode.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by Nathan-Melaku** [comment]
Thanks for the quick check. I have fixed the problems pointed out by melpazoid.

**Comment by riscy** [comment]
Thanks!

**Comment by riscy** [comment]
And welcome to MELPA :)

**Comment by Nathan-Melaku** [comment]
Thanks. Happy to be here. 😊

**Pull request merged**
