### PR TITLE
Recipe for totp-auth.el - Time-based One Time Password support

### PR DESCRIPTION
**Pull request by fledermaus**
### Brief summary of what the package does

This package generates RFC6238 Time-based One Time Passwords and displays them (as well as optionally copying them to the clipboard/primary selection), updating them as they expire.

### Direct link to the package repository

[fledermaus/totp.el](https://gitlab.com/fledermaus/totp.el/)

### Your association with the package

Author & Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
  - package lint complains about the prefix to my symbols being totp- rather than totp-auth - there turned out to be a more basic package called totp.el which I hadn't spotted because I only looked in melpa stable, and I didn't want to rename everything if the package was going to be rejected anyway. I can adress this if it's important (and the package is otherwise acceptable). 
- [x] My elisp byte-compiles cleanly
  - there's one warning about a deprecated function but I'm looking into it 
- [x] I've used `M-x checkdoc` to check the package's documentation string
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
Byte compilation on Emacs 30 raises the following warnings:

```emacs-lisp
In base32--nth-5bit-get:
base32.el:46:32: Warning: avoid ‘lsh’; use ‘ash’ instead
base32.el:47:32: Warning: avoid ‘lsh’; use ‘ash’ instead
base32.el:56:35: Warning: avoid ‘lsh’; use ‘ash’ instead
In base32--nth-5bit-set:
base32.el:73:34: Warning: avoid ‘lsh’; use ‘ash’ instead
base32.el:74:34: Warning: avoid ‘lsh’; use ‘ash’ instead
base32.el:86:38: Warning: avoid ‘lsh’; use ‘ash’ instead
Compiling /home/n/.emacs.d/elpaca/builds/totp-auth/hmac.el...
In hmac-algo-block-size:
hmac.el:10:2: Warning: docstring has wrong usage of unescaped single quotes (use \=' or different quoting such as `...')
In totp-unwrap-otpauth-url:
totp-auth.el:251:15: Warning: assignment to free variable ‘service’
totp-auth.el:254:20: Warning: reference to free variable ‘service’
In totp-save-secret-to-secrets-source:
totp-auth.el:422:15: Warning: assignment to free variable ‘stored’
totp-auth.el:432:28: Warning: reference to free variable ‘stored’
In totp-hmac-message:
totp-auth.el:484:35: Warning: avoid ‘lsh’; use ‘ash’ instead
In totp-truncate-hash:
totp-auth.el:501:14: Warning: avoid ‘lsh’; use ‘ash’ instead
totp-auth.el:501:26: Warning: avoid ‘lsh’; use ‘ash’ instead
totp-auth.el:501:38: Warning: avoid ‘lsh’; use ‘ash’ instead
In end of data:
totp-auth.el:698:30: Warning: the function ‘notifications-get-server-information’ is not known to be defined.
totp-auth.el:656:6: Warning: the function ‘notifications-notify’ is not known to be defined.
totp-auth.el:647:6: Warning: the function ‘notifications-close-notification’ is not known to be defined.
totp-auth.el:426:27: Warning: the function ‘secrets-get-item-properties’ is not known to be defined.
totp-auth.el:424:29: Warning: the function ‘secrets-get-items’ is not known to be defined.
totp-auth.el:423:23: Warning: the function ‘secrets-collection-path’ is not known to be defined.
Compiling /home/n/.emacs.d/elpaca/builds/totp-auth/totp-interop.el...
In totp-pb-read-varint:
totp-interop.el:60:27: Warning: avoid ‘lsh’; use ‘ash’ instead
In totp-pb-read-tag:
totp-interop.el:73:18: Warning: avoid ‘lsh’; use ‘ash’ instead
In totp-pb-read-raw:
totp-interop.el:84:6: Warning: ‘string-make-unibyte’ is an obsolete function (as of 26.1); use ‘encode-coding-string’.
```

**Comment by fledermaus** [comment]
lsh vs ash is not a wraning in emacs 28.2 - emacs 30 isn't out yet - is it a warning in emacs 29?

The notifications functions are not called excapt in paths wher ethey must first pass through a (require 'notifications) so they should be fine.

The rest should be fixed now.

**Comment by riscy** [comment]
>  is it a warning in emacs 29?

Looks like yes - I will paste the logscroll below.  If you can accommodate the warning in a forward-compatible way in Emacs 28, I'd definitely do so.

> The notifications functions are not called except in paths where they must first pass through a (require 'notifications) so they should be fine.

I expect you're right, but you can pacify the byte-compiler with either a top-level `(require 'notifications)` or `declare-function`.  The less the byte-compiler screams (unnecessarily?) at people while they're installing their packages (sometimes in the hundreds) the better.  And this is also one of MELPA's easiest QA thresholds for us to implement.

Here's a quick automated pass from my end.  I think you're spanning a few different namespaces here, so there is a lot of linter noise about this:

`base32.el` with byte-compile using Emacs 29.1:
```
base32.el:46:32: Warning: avoid `lsh'; use `ash' instead
base32.el:47:32: Warning: avoid `lsh'; use `ash' instead
base32.el:56:35: Warning: avoid `lsh'; use `ash' instead
In base32--nth-5bit-set:
base32.el:73:34: Warning: avoid `lsh'; use `ash' instead
base32.el:74:34: Warning: avoid `lsh'; use `ash' instead
base32.el:86:38: Warning: avoid `lsh'; use `ash' instead
```

`base32.el` with checkdoc 0.6.2 (fix *within reason*):
```
base32.el:12: First line is not a complete sentence
```

`base32.el` with package-lint 20231121.1907 and `package-lint-main-file` = "totp-auth.el":
```
6 issues found:
9:0: error: "base32-dictionary" doesn't start with package's prefix "totp-auth".
17:0: error: "base32-thesaurus" doesn't start with package's prefix "totp-auth".
33:0: error: "base32--nth-5bit-get" doesn't start with package's prefix "totp-auth".
61:0: error: "base32--nth-5bit-set" doesn't start with package's prefix "totp-auth".
93:0: error: "base32-encode" doesn't start with package's prefix "totp-auth".
117:0: error: "base32-decode" doesn't start with package's prefix "totp-auth".
```

`hmac.el` with byte-compile using Emacs 29.1:
```
hmac.el:10:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
```
unfortunately new in Emacs 29 - but we should strive to address these.

`hmac.el` with package-lint 20231121.1907 and `package-lint-main-file` = "totp-auth.el":
```
7 issues found:
10:0: error: "hmac-algo-block-size" doesn't start with package's prefix "totp-auth".
17:0: error: "hmac-xpad" doesn't start with package's prefix "totp-auth".
23:0: error: "hmac-opad" doesn't start with package's prefix "totp-auth".
28:0: error: "hmac-ipad" doesn't start with package's prefix "totp-auth".
33:0: error: "hmac-xor" doesn't start with package's prefix "totp-auth".
46:0: error: "hmac-blockify" doesn't start with package's prefix "totp-auth".
61:0: error: "hmac" doesn't start with package's prefix "totp-auth".
```

`totp-auth.el` with byte-compile using Emacs 29.1:
```
totp-auth.el:485:35: Warning: avoid `lsh'; use `ash' instead
In totp-truncate-hash:
totp-auth.el:502:14: Warning: avoid `lsh'; use `ash' instead
totp-auth.el:502:26: Warning: avoid `lsh'; use `ash' instead
totp-auth.el:502:38: Warning: avoid `lsh'; use `ash' instead
In end of data:
totp-auth.el:703:30: Warning: the function `notifications-get-server-information' is not known to be defined.
totp-auth.el:657:6: Warning: the function `notifications-notify' is not known to be defined.
totp-auth.el:648:6: Warning: the function `notifications-close-notification' is not known to be defined.
```

`totp-auth.el` with checkdoc 0.6.2 (fix *within reason*):
```
totp-auth.el:29: Name emacs should appear capitalized as Emacs
totp-auth.el:12: Name emacs should appear capitalized as Emacs
totp-auth.el:651: All variables and subroutines might as well have a documentation string
```

`totp-auth.el` with package-lint 20231121.1907 and `package-lint-main-file` = "totp-auth.el":
```
43 issues found:
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
61:0: error: "totp-xdg-schema" doesn't start with package's prefix "totp-auth".
63:0: error: "totp-alt-xdg-schemas" doesn't start with package's prefix "totp-auth".
70:0: error: "totp-minimum-ui-grace" doesn't start with package's prefix "totp-auth".
80:0: error: "totp-max-tokens" doesn't start with package's prefix "totp-auth".
85:0: error: "totp-file-import-command" doesn't start with package's prefix "totp-auth".
91:0: error: "totp-secrets-create-item-workaround" doesn't start with package's prefix "totp-auth".
100:0: error: "totp-auto-copy-password" doesn't start with package's prefix "totp-auth".
114:0: error: "totp-display-token-method" doesn't start with package's prefix "totp-auth".
217:0: error: "totp-wrap-otpauth-url" doesn't start with package's prefix "totp-auth".
237:0: error: "totp-unwrap-otpauth-url" doesn't start with package's prefix "totp-auth".
260:0: error: "totp-unwrap-otp-blob" doesn't start with package's prefix "totp-auth".
281:0: error: "totp-storage-backends" doesn't start with package's prefix "totp-auth".
303:0: error: "totp-get-secrets-from-secrets-source" doesn't start with package's prefix "totp-auth".
323:0: error: "totp-get-secrets-from-default-source" doesn't start with package's prefix "totp-auth".
344:0: error: "totp-get-secrets-from-backend" doesn't start with package's prefix "totp-auth".
354:0: error: "totp-same-secret" doesn't start with package's prefix "totp-auth".
362:0: error: "totp-get-backend-for-secret" doesn't start with package's prefix "totp-auth".
375:0: error: "totp-secret-make-label" doesn't start with package's prefix "totp-auth".
386:0: error: "totp-secret-make-label-and-wrapper" doesn't start with package's prefix "totp-auth".
395:0: error: "totp-get-item-attribute" doesn't start with package's prefix "totp-auth".
400:0: error: "totp-save-secret-to-secrets-source" doesn't start with package's prefix "totp-auth".
437:0: error: "totp-save-secret-to-default-source" doesn't start with package's prefix "totp-auth".
464:0: error: "totp-save-secret" doesn't start with package's prefix "totp-auth".
479:0: error: "totp-secrets" doesn't start with package's prefix "totp-auth".
483:0: error: "totp-hmac-message" doesn't start with package's prefix "totp-auth".
491:0: error: "totp-truncate-hash" doesn't start with package's prefix "totp-auth".
504:0: error: "totp-override-time" doesn't start with package's prefix "totp-auth".
507:0: error: "totp-generate-otp" doesn't start with package's prefix "totp-auth".
539:0: error: "totp-display-ttl" doesn't start with package's prefix "totp-auth".
540:0: error: "totp-display-label" doesn't start with package's prefix "totp-auth".
541:0: error: "totp-display-expiry" doesn't start with package's prefix "totp-auth".
542:0: error: "totp-display-secret" doesn't start with package's prefix "totp-auth".
543:0: error: "totp-display-oldpwd" doesn't start with package's prefix "totp-auth".
545:0: error: "totp-update-paste-buffers" doesn't start with package's prefix "totp-auth".
556:0: error: "totp-cancel-this-timer" doesn't start with package's prefix "totp-auth".
574:0: error: "totp-update-token-display" doesn't start with package's prefix "totp-auth".
607:0: error: "totp-display-token-buffer" doesn't start with package's prefix "totp-auth".
629:0: error: "totp-notification-action" doesn't start with package's prefix "totp-auth".
650:0: error: "totp-update-token-notification" doesn't start with package's prefix "totp-auth".
665:0: error: "totp-display-token-notification" doesn't start with package's prefix "totp-auth".
692:0: error: "totp-display-token" doesn't start with package's prefix "totp-auth".
708:0: error: "totp" doesn't start with package's prefix "totp-auth".
```

`totp-auth.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- totp-auth.el#L481: It's safer to sharp-quote function names; use `#'`
```

`totp-interop.el` with byte-compile using Emacs 29.1:
```
totp-interop.el:60:27: Warning: avoid `lsh'; use `ash' instead
In totp-pb-read-tag:
totp-interop.el:73:18: Warning: avoid `lsh'; use `ash' instead
```

`totp-interop.el` with package-lint 20231121.1907 and `package-lint-main-file` = "totp-auth.el":
```
17 issues found:
30:0: error: "totp-pb-types" doesn't start with package's prefix "totp-auth".
32:0: error: "totp-pb-type" doesn't start with package's prefix "totp-auth".
37:0: error: "totp-pb-read-varint" doesn't start with package's prefix "totp-auth".
65:0: error: "totp-pb-read-tag" doesn't start with package's prefix "totp-auth".
77:0: error: "totp-pb-read-raw" doesn't start with package's prefix "totp-auth".
86:0: error: "totp-pb-read-len" doesn't start with package's prefix "totp-auth".
98:0: error: "totp-pb-otpauth-migration-field-map" doesn't start with package's prefix "totp-auth".
101:0: error: "totp-pb-otpauth-migration-translate-field" doesn't start with package's prefix "totp-auth".
122:0: error: "totp-pb-decode-migration-item" doesn't start with package's prefix "totp-auth".
150:0: error: "totp-pb-decode-migration-data" doesn't start with package's prefix "totp-auth".
171:0: error: "totp-unwrap-otpauth-migration-url" doesn't start with package's prefix "totp-auth".
183:0: error: "totp-parse-buffer-otp-urls" doesn't start with package's prefix "totp-auth".
201:0: error: "totp-load-image-file" doesn't start with package's prefix "totp-auth".
210:0: error: "totp-find-hmac-key-by-class" doesn't start with package's prefix "totp-auth".
216:0: error: "totp-find-hmac-key" doesn't start with package's prefix "totp-auth".
223:0: error: "totp-load-file" doesn't start with package's prefix "totp-auth".
247:0: error: "totp-import-file" doesn't start with package's prefix "totp-auth".
```

`totp-interop.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- totp-interop.el#L207: It's safer to sharp-quote function names; use `#'`
- totp-interop.el#L108: You can use `not` or `null`
```

Package and license:
- Avoid specifying `:branch` except in unusual cases
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee
- base32.el -- not in package namespace `totp-auth-`
- hmac.el -- not in package namespace `totp-auth-`
- totp-interop.el -- not in package namespace `totp-auth-`

**Comment by fledermaus** [comment]
Hm. lsh and ash are not necessarily equivalent. 

I'm reluctant to replace lsh with ash until I've properly investigated all the uses of it and determined that the differences don't matter.

**Comment by progfolio** [comment]
> I think the lsh vs ash warning is flat out wrong here.
> 
> I'm manipulating bit fields and I _always_ want the bits shifted in to be 0. I think this warning is assuming the programmer doesn't know what they're doing and guessing they want to preserve the sign bit in an integer.
> 
> Not going to change it as it would be the wrong thing to do.

The NEWS file for Emacs 29 explains the motivation and a workaround if you insist on lsh:

```
** Calling 'lsh' now elicits a byte-compiler warning.
'lsh' behaves in somewhat surprising and platform-dependent ways for
negative arguments, and is generally slower than 'ash', which should be
used instead.  This warning can be suppressed by surrounding calls to
'lsh' with the construct '(with-suppressed-warnings ((suspicious lsh)) ...)',
but switching to 'ash' is generally much preferable.
```

**Comment by fledermaus** [comment]
I'm not "insisting" on lsh, ash would be wrong here. But I'll put in the work around.

**Comment by fledermaus** [comment]
The package is split into two now, so the linter namespace complaints should be gone. lsh is wrapped to shield it from the delicate eyes of the byte-compiler too. I think other warnings should be gone too except:

The interactive command is called totp which isn't in the snamespace totp-auth (I wanted to keep it short)

The keywords aren't in the well -known list because none of the well known keywords seem to apply.

**Comment by riscy** [comment]
Thank you for accommodating @fledermaus -- the base32.el package looks good, but I'd simplify the recipe to remove the `:exclude` part, since you're only specifying one file.  Similarly with the `topt-auth` recipe which could just be `(totp-auth :fetcher gitlab :files ("totp-*.el") :repo "fledermaus/totp.el") `. 

> The interactive command is called totp which isn't in the namespace totp-auth (I wanted to keep it short)

It may feel inconvenient, but a simple and fair way to prevent namespace collisions across MELPA (and hopefully elsewhere) is to ask that the package, variable names, and function names all use the same prefix.  In very rare cases I would make exceptions to this rule (e.g. backward compatibility with a package predating this rule) -- and `package-lint` has some of these exceptions built into it.

On that same note, the filename totp-interop.el is not in package namespace `totp-auth-`.

> The keywords aren't in the well -known list because none of the well known keywords seem to apply.

I agree with you here.  I think `finder-known-keywords` hasn't been revised in a long time.  `comm` may be the closest but I wouldn't fault you for not adding it.

Here's the latest salient issues --

`base32.el` with byte-compile using Emacs 29.1:
```
base32.el:52:32: Warning: avoid `lsh'; use `ash' instead
base32.el:53:32: Warning: avoid `lsh'; use `ash' instead
base32.el:62:35: Warning: avoid `lsh'; use `ash' instead
In base32--nth-5bit-set:
base32.el:79:34: Warning: avoid `lsh'; use `ash' instead
base32.el:80:34: Warning: avoid `lsh'; use `ash' instead
base32.el:92:38: Warning: avoid `lsh'; use `ash' instead
```
(I think these are not suppressed yet, fyi)

`totp-auth-hmac.el` with checkdoc 0.6.2 (fix *within reason*):
```
totp-auth-hmac.el:78: The footer should be: (provide 'totp-auth-hmac)\n;;; totp-auth-hmac.el ends here
```

- totp-interop.el#L209: It's safer to sharp-quote function names; use `#'`
- totp-interop.el#L108: You can use `not` or `null`

**Comment by fledermaus** [comment]
- recipes simplified
- ```M-x totp RET``` is now ```M-x totp-auth RET```
- keyword "comm" added 
- lsh wrapped in base32
- checkdoc footer in totp-auth-hmac fixed
- byte compile warnings about #' and (eq … nil) vs (not …)  addressed

**Comment by riscy** [comment]
I've made another change to the recipe - I hope this fits you.  (If not, this is easy to change.)

In totp-auth-hmac.el you should explicitly `(require cl-lib)` e.g. for your use of `cl-case`.  If the byte-compiler encounters this file first, the cl- macros may not be available to it yet, and users would encounter an error -- 

`totp-auth-hmac.el` with byte-compile using Emacs 29.1:
```
totp-auth-hmac.el:14:7: Warning: `(md5 sha1 sha224 sha256)' is a malformed function
totp-auth-hmac.el:15:7: Warning: `(sha384 sha512)' is a malformed function
```

Once past that, this is looking like a quick merge.

**Comment by fledermaus** [comment]
Replaced the cl-case with a cond - it was a tiny function anyway so not a big deal to make the change.

**Comment by riscy** [comment]
Thank you for your patience - and welcome to MELPA. :)

**Comment by fledermaus** [comment]
Great! Happy to be here.

**Pull request merged**
