### PR TITLE
Add recipe for org-present-remote

### PR DESCRIPTION
**Pull request by duncan-bayne**
### Brief summary of what the package does

Provides a web-based remote control for org-present.

### Direct link to the package repository

https://gitlab.com/duncan-bayne/org-present-remote

### Your association with the package

I am the author and maintainer. 

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
This looks neat.  A screenshot would be nice.  :)

BTW, curious, is `org-present-remote--trim-string` necessary?  Does `string-trim` not do the job?

**Comment by duncan-bayne** [comment]
@alphapapa Actually, `org-present-remote--trim-string` wasn't even used :blush:  I've removed it upstream.

Screenshot below (actual screenshot, rendered onto a mobile device for context):

mobile-screenshot

**Comment by alphapapa** [comment]
LOL, I like the "screenshot".  :)

**Comment by duncan-bayne** [comment]
User seeing mobile screenshot: meh

User seeing mobile screenshot rendered onto device: I COULD BE USING THAT RIGHT NOW, IN MY HAND, TAKE MY MONEY

:)

**Comment by duncan-bayne** [comment]
Any other changes you'd like before this is considered okay to merge?

**Comment by alphapapa** [comment]
Just to be clear, I'm not a MELPA maintainer, just a user who tries to help
out by doing partial reviews of packages ahead of the official ones. The
maintainers will get to your package, but there's always a backlog, and
sometimes it takes a few weeks.

**Comment by duncan-bayne** [comment]
@alphapapa Ah okay, thanks for letting me know :)  I'll wait for feedback from the maintainers then.

**Comment by purcell** [comment]
Thanks, and sorry for the delay. Looks good, but the header is malformatted: you've included the metadata headers in the `Commentary` text. Instead, please stick to the standard header boilerplate layout: to see what that is, try creating an empty .el file and then calling `M-x auto-insert`.

**Comment by duncan-bayne** [comment]
@purcell Thanks, I've fixed that upstream (https://gitlab.com/duncan-bayne/org-present-remote/commit/daebc08c52a599b1bcbdc4e80b1a212a3463fa2b).  You might be interested to know that `M-x auto-insert` didn't work on an empty Emacs Lisp buffer; I had to specifically visit a file in order for it to work.  Slightly confusing.

**Comment by purcell** [comment]
The header is the right shape now, thanks, but you've lost the necessary `;; Package-Requires:` header. If you ping us here once it's added back in, any of us can go ahead and merge this.

**Comment by duncan-bayne** [comment]
@purcell Fixed upstream (and re-linted).

**Comment by DamienCassou** [comment]
If we were using GitLab, I would press the blue button

https://petton.fr/nextcloud/index.php/apps/gallery/s/HwGg5etp6PPQRXC/download

**Pull request merged**
