### PR TITLE
Add srv recipe

### PR DESCRIPTION
**Pull request by legoscia**
### Brief summary of what the package does

srv.el is a library for performing SRV DNS lookups. In an SRV lookup, the client asks for hostnames and ports to use when connecting to a specific service, e.g. IMAP, SMTP or XMPP, for a certain domain.

### Direct link to the package repository

https://github.com/legoscia/srv.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Merged, thanks, particularly for your patience.

**Comment by tarsius** [comment]
@legoscia Please remove `srv.el` from `jabber` now. Not just the recipe but the repository.

**Comment by legoscia** [comment]
Will do! I'll try to find time this weekend.

**Comment by tarsius** [comment]
I was unintentionally a bit pushy above, so... *a shy ping*. :wink:

**Comment by legoscia** [comment]
Now it's finally done! legoscia/emacs-jabber@fff3382

**Comment by tarsius** [comment]
Thanks!

**Pull request merged**
