### PR TITLE
Add recipe gotn

### PR DESCRIPTION
**Pull request by yauhen-l**
### Brief summary of what the package does

Utility tool for Go programming language to run test at point.

### Direct link to the package repository

https://github.com/yauhen-l/gotn

### Your association with the package

Maintainer

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
I believe you can safely use the default recipe (see README.md)

**Comment by yauhen-l** [comment]
@riscy I dropped `:files` in recipe to use defaults.

**Comment by riscy** [comment]
Hi, thanks!

The URL listed in your front matter, https://github.com/yauhenl/gotn, doesn't appear to lead anywhere.

Have you considered adding this behavior to the [gotest](https://github.com/nlamirault/gotest.el/tree/36e09a6bf1face4c56d4a7707935c992786e0076) package?

As for the code itself, one quick thing I see:
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
Per CONTRIBUTING.org, consider [using lexical binding](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems) (and depend on at least (emacs "24"))
(The following assumes lexical binding is enabled)
```
gotn.el:44:1:Warning: Lexical argument shadows the dynamic variable mode-name
```
You can rename the variable to `_mode-name` since it is unused, which fixes that.

In the declaration of your major mode, you have:
```elisp
(define-derived-mode gotn-mode compilation-mode "gotn"
  "Major mode for the gotn compilation buffer."
  (use-local-map gotn-mode-map)
  (setq major-mode 'gotn-mode)
  (setq mode-name "gotn")
  (setq truncate-lines t)
  (font-lock-add-keywords nil nil))
```
But you don't need to `setq` on `major-mode` or `mode-name` -- these should be set automatically when using `define-derived-mode`.

Hope that helps, and let me know your thoughts on `gotest`.

**Comment by yauhen-l** [comment]
Hi @riscy ,
Thank you very much! I've fixed all issues. A funny part with `setq on major-mode or mode-name` that I took it from `gotest`: https://github.com/nlamirault/gotest.el/blob/master/gotest.el#L141
Regarding `gotest`:
`gotest` uses Elisp to parse and identify Go tests names, while `gotn` uses general Go approach of providing simple Go program for this task, so it can be used by any editor and not only Emacs.
Also I am not so experienced Elisp developer to implement same functionality in `gotest`.

**Comment by riscy** [comment]
> gotest uses Elisp to parse and identify Go tests names, while gotn uses general Go approach of providing simple Go program for this task, so it can be used by any editor and not only Emacs.

Ah, interesting.  The ability to support editors besides Emacs is definitely a plus for `gotn`, so I think you've done nice work there, but that seems irrelevant when we're talking about MELPA packages.

> Also I am not so experienced Elisp developer to implement same functionality in gotest

To be honest, you seem experienced enough that I believe it would be within your reach.  Can I recommend you try to open an issue with them?

**Comment by tarsius** [comment]
Closing due to inactivity.
Let us know when you are ready so that we can reopen and finish the review.

**Pull request closed without merging**
