### PR TITLE
Add ivy-spotify recipe

### PR DESCRIPTION
**Pull request by jaor**
### Brief summary of what the package does

Using ivy completion to perform Spotify web searches.

### Direct link to the package repository

https://codeberg.org/jao/espotify

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  If you rebase this branch (or merge the master branch) the build'll work correctly, but this recipe seems to contain consult-spotify and espotify.el.

**Comment by jaor** [comment]
Thanks @riscy... i've rebased and made explicit that only
ivy-spotify.el should be used (espotify will be still installed as a
dep, but not as part of the package).

**Comment by riscy** [comment]
Thanks very much.  Looks good, but I'll quickly note this looks like a `user-error` rather than a lisp `error`: `(error "No album for %s" (alist-get 'name item))`.  Not a blocker, though.

**Comment by jaor** [comment]
On Sun, Mar 28 2021, Chris Rayner wrote:

> Thanks very much. Looks good, but I'll quickly note this looks like a
> user-error rather than a lisp error: (error "No album for %s"
> (alist-get 'name item)).

That's right.  I'll just give a message instead.  Thanks for reviewing.

**Comment by riscy** [comment]
There's also the `user-error` function which may serve similarly.

**Comment by jaor** [comment]
On Sun, Mar 28 2021, Chris Rayner wrote:

> There's also the user-error function which may serve similarly.

Yes, but in this case i think that calling it a user /error/ is a bit
too strong: an empty result looking for the album of search result is a
possible, nominal result, and the user has no sure way of knowing that
just by looking at the result.  Actually, a better interface would
simply deactivate that action (play song's album) when that's the case
(because the elisp side does know it), so one could even argue that it's
closer to an error than to a user error.

A message sounded like a good enough compromise for the time being :)

**Pull request merged**
