### PR TITLE
add baidu-translate

### PR DESCRIPTION
**Pull request by liShiZhensPi**
### Brief summary of what the package does

Translate the text you marked or the whole buffer using baidu-tranlsate api.

### Direct link to the package repository

https://github.com/liShiZhensPi/baidu-translate

### Your association with the package

I am the maintainer and contributor.

### Relevant communications with the upstream package maintainer

The package need the unicode-escape,i send email to him,but not get answer now.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by liShiZhensPi** [comment]
baidu-translate

**Comment by riscy** [comment]
Thank you for this!  There are some problems you should double-check, listed below.  Also, please make sure you answer the questions in your opening comment -- for example "Your association with the package".

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
baidu-translate.el:41: Argument `buffer-or-name' should appear (as BUFFER-OR-NAME) in the doc string
Warning (emacs): 
baidu-translate.el:55: Some lines are over 80 columns wide
Warning (emacs): 
baidu-translate.el:55: Argument `query' should appear (as QUERY) in the doc string
Warning (emacs): 
baidu-translate.el:83: Argument `string' should appear (as STRING) in the doc string
Warning (emacs): 
baidu-translate.el:102: Argument `start' should appear (as START) in the doc string
Warning (emacs): 
baidu-translate.el:46: Messages should start with a capital letter
Warning (emacs): 
baidu-translate.el:3: White space found at end of line
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
7 issues found:

1:1: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:1: error: Package should have a Homepage or URL header.
1:1: error: package.el cannot parse this buffer: Package lacks a "Version" or "Package-Version" header
1:75: warning: You should depend on (emacs "24") if you need lexical-binding.
6:1: warning: You should include standard keywords: see the variable `finder-known-keywords'.
32:1: error: "TRANS_API_HOST" doesn't start with package's prefix "baidu-translate".
40:1: error: "clear-buffer" doesn't start with package's prefix "baidu-translate".
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
baidu-translate.el:32:1:Warning: global/dynamic var `TRANS_API_HOST' lacks a
    prefix
baidu-translate.el:35:1:Warning: global/dynamic var `APPID' lacks a prefix
baidu-translate.el:37:1:Warning: global/dynamic var `SECURITY_KEY' lacks a
    prefix

In clear-buffer:
baidu-translate.el:46:8:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
baidu-translate.el:46:8:Warning: `mark-whole-buffer' is for interactive use
    only.

In baidu-translate-string:
baidu-translate.el:95:33:Warning: assignment to free variable `GBKS'
baidu-translate.el:95:16:Warning: reference to free variable `GBKS'
baidu-translate.el:95:16:Warning: `beginning-of-buffer' is for interactive use
    only; use `(goto-char (point-min))' instead.
```

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
No issues! 🎉

Miscellaneous automated checks:
- baidu-translate.el#L32: Prefer `https` over `http` (if possible)

**Comment by liShiZhensPi** [comment]
thanks,got it

**Comment by liShiZhensPi** [comment]
I have make the warning clean.
捕获

**Comment by liShiZhensPi** [comment]
> Thank you for this! There are some problems you should double-check, listed below. Also, please make sure you answer the questions in your opening comment -- for example "Your association with the package".
> 
> M-x checkdoc (using version 0.6.1):
> 
> ```
> Warning (emacs): 
> baidu-translate.el:41: Argument `buffer-or-name' should appear (as BUFFER-OR-NAME) in the doc string
> Warning (emacs): 
> baidu-translate.el:55: Some lines are over 80 columns wide
> Warning (emacs): 
> baidu-translate.el:55: Argument `query' should appear (as QUERY) in the doc string
> Warning (emacs): 
> baidu-translate.el:83: Argument `string' should appear (as STRING) in the doc string
> Warning (emacs): 
> baidu-translate.el:102: Argument `start' should appear (as START) in the doc string
> Warning (emacs): 
> baidu-translate.el:46: Messages should start with a capital letter
> Warning (emacs): 
> baidu-translate.el:3: White space found at end of line
> ```
> 
> M-x package-lint-current-buffer (using version 20190707.1456):
> 
> ```
> 7 issues found:
> 
> 1:1: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
> 1:1: error: Package should have a Homepage or URL header.
> 1:1: error: package.el cannot parse this buffer: Package lacks a "Version" or "Package-Version" header
> 1:75: warning: You should depend on (emacs "24") if you need lexical-binding.
> 6:1: warning: You should include standard keywords: see the variable `finder-known-keywords'.
> 32:1: error: "TRANS_API_HOST" doesn't start with package's prefix "baidu-translate".
> 40:1: error: "clear-buffer" doesn't start with package's prefix "baidu-translate".
> ```
> 
> M-x byte-compile-file (using Emacs 26.2):
> 
> ```
> baidu-translate.el:32:1:Warning: global/dynamic var `TRANS_API_HOST' lacks a
>     prefix
> baidu-translate.el:35:1:Warning: global/dynamic var `APPID' lacks a prefix
> baidu-translate.el:37:1:Warning: global/dynamic var `SECURITY_KEY' lacks a
>     prefix
> 
> In clear-buffer:
> baidu-translate.el:46:8:Warning: Use `with-current-buffer' rather than
>     save-excursion+set-buffer
> baidu-translate.el:46:8:Warning: `mark-whole-buffer' is for interactive use
>     only.
> 
> In baidu-translate-string:
> baidu-translate.el:95:33:Warning: assignment to free variable `GBKS'
> baidu-translate.el:95:16:Warning: reference to free variable `GBKS'
> baidu-translate.el:95:16:Warning: `beginning-of-buffer' is for interactive use
>     only; use `(goto-char (point-min))' instead.
> ```
> 
> M-x check-declare-file (optional -- not on the MELPA checklist):
> No issues! 🎉
> 
> Miscellaneous automated checks:
> 
> * baidu-translate.el#L32: Prefer `https` over `http` (if possible)

**Comment by liShiZhensPi** [comment]
emmm, I pressed the wrong key

**Comment by liShiZhensPi** [comment]
how could i reopen this pull request

**Comment by riscy** [comment]
You'll need to fork MELPA again, unfortunately.

**Comment by liShiZhensPi** [comment]
It's a dangerous key.

**Pull request closed without merging**
