### PR TITLE
add counsel-bbdb recipe

### PR DESCRIPTION
**Pull request by redguardtoo**
### Brief summary of what the package does

Quick search&input email from BBDB database based on ivy-mode

### Direct link to the package repository

https://github.com/redguardtoo/counsel-bbdb

### Your association with the package
I'm the creator of the package.

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
Looks good.

**Comment by purcell** [comment]
This should be `ivy-bbdb`, rather than `counsel-bbdb`, I think.

**Comment by redguardtoo** [comment]
@purcell , I'm following the creator of counsel/ivy's file naming convention. Ivy provides basic infrastructure and counsel provides utilities people uses.

http://oremacs.com/2015/04/19/git-grep-ivy/

https://github.com/abo-abo/swiper/commit/e9db958

**Comment by purcell** [comment]
> @purcell , I'm following the creator of counsel/ivy's file naming convention. Ivy provides basic infrastructure and counsel provides utilities people uses.

Yes, but this isn't the Counsel package. There are more `ivy-*` packages than `counsel-*` packages, and I expect that the author just chose "counsel" as the name for _his_ package of completion add-ons, not as a community convention. What do you think, @abo-abo?

**Comment by redguardtoo** [comment]
I'm ok with any namespace.

**Comment by abo-abo** [comment]
@purcell My idea was to keep the `ivy-` namespace small, so that the most fundamental and basic customization features are more easily discoverable via completion.  Then `counsel-` would be a large namespace containing also new namespaces like `counsel-bbdb-`.

But looking at MELPA, there are already more 3rd party `ivy-` packages than `counsel-` packages (approx 6 vs 3). So consistency is already gone.

The naming should always be up to the author. My personal preference is `counsel-bbdb`.

**Comment by purcell** [comment]
Cool, thanks.

**Pull request merged**
