### PR TITLE
Add recipe for auto-activating-snippets

### PR DESCRIPTION
**Pull request by tecosaur**
### Brief summary of what the package does

This package implements an engine for auto-expanding snippets. It is done by tracking your inputted chars along a tree until you complete a registered key sequence.

Its like running a long prefix command, but the keys you type are not 'consumed' and appear in the buffer until you complete the whole command --- and then the snippet is triggered!

### Direct link to the package

https://github.com/ymarco/auto-activating-snippets

### Your association with the package

Contributor.

### Relevant communications with the upstream package maintainer

They said it would be nice if I melpa-d it.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
  - not sure what to do about the prefix complaints, I'd silence them if I knew how
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi @tecosaur, there is a relatively new line in CONTRIBUTING.md that gently nudges you toward not opening too many recipe PRs at the same time.  This makes it easier for MELPA maintainers to distribute review time evenly between authors.

**Comment by riscy** [comment]
(You don't have to close any, but it can be helpful to meter your recipe PRs going forward.)

**Comment by tecosaur** [comment]
Ah, cool --- afraid I missed that line. I just had a bit of a 'backlog' of a few packages that people had been saying I should put on MELPA. This PR 'dump' should be a bit of a once-off if that's any consolation :)

**Comment by riscy** [comment]
Quick first pass --

### auto-activating-snippets.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
auto-activating-snippets.el:236: Lisp symbol `org-mode' should appear in quotes
```

package-lint (using version 20210111.341):
```
22 issues found:
29:0: error: "aas-pre-snippet-expand-hook" doesn't start with package's prefix "auto-activating-snippets".
31:0: error: "aas-post-snippet-expand-hook" doesn't start with package's prefix "auto-activating-snippets".
34:0: error: "aas-transient-snippet-key" doesn't start with package's prefix "auto-activating-snippets".
36:0: error: "aas-transient-snippet-expansion" doesn't start with package's prefix "auto-activating-snippets".
38:0: error: "aas-transient-snippet-condition-result" doesn't start with package's prefix "auto-activating-snippets".
41:0: error: "aas--key-is-fully-typed?" doesn't start with package's prefix "auto-activating-snippets".
48:0: error: "aas-global-condition-hook" doesn't start with package's prefix "auto-activating-snippets".
54:0: error: "aas-keymaps" doesn't start with package's prefix "auto-activating-snippets".
57:0: error: "aas-active-keymaps" doesn't start with package's prefix "auto-activating-snippets".
61:0: error: "aas-expand-snippet-maybe" doesn't start with package's prefix "auto-activating-snippets".
95:0: error: "aas-define-prefix-map-snippet" doesn't start with package's prefix "auto-activating-snippets".
108:0: error: "aas-set-snippets" doesn't start with package's prefix "auto-activating-snippets".
135:0: error: "aas--prefix-map" doesn't start with package's prefix "auto-activating-snippets".
138:0: error: "aas--current-prefix-maps" doesn't start with package's prefix "auto-activating-snippets".
143:0: error: "aas-post-self-insert-hook" doesn't start with package's prefix "auto-activating-snippets".
179:0: error: "aas--debug-print-tree-options" doesn't start with package's prefix "auto-activating-snippets".
191:0: error: "aas-activate-keymap" doesn't start with package's prefix "auto-activating-snippets".
202:0: error: "aas-deactivate-keymap" doesn't start with package's prefix "auto-activating-snippets".
210:0: error: "aas-activate-major-mode-snippets" doesn't start with package's prefix "auto-activating-snippets".
215:0: error: "aas--modes-to-activate" doesn't start with package's prefix "auto-activating-snippets".
235:0: error: "aas--format-doc-to-org" doesn't start with package's prefix "auto-activating-snippets".
242:0: error: "aas--format-snippet-array" doesn't start with package's prefix "auto-activating-snippets".
```


### Loadability ###

Verifying ability to #'load each file:
```
Loading auto-activating-snippets.el
Done.
```

### Package ###

- GitHub API found `GNU General Public License v3.0`
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to auto-activating-snippets.el
- auto-activating-snippets.el (unknown license) -- Snippet expansions mid-typing

**Comment by tecosaur** [comment]
I don't see those package-lint complaints going away (unless there's a way to tell i tto treat `aas` as a prefix) because `
auto-activating-snippets-activate-major-mode-snippets` is a bit much compared to `aas-activate-major-mode-snippets`.

Other that that, just seems like we could do with adding a SPDX line and quoting `` `org-mode' `` ( @ymarco ).

**Comment by riscy** [comment]
> I don't see those package-lint complaints going away

Package-lint errors against this because the package name and function/variable name prefixes all have to line up by contemporary MELPA standards.  This lets us mark off the "namespaces" of different packages in a very simple way.  While it's true `auto-activating-snippets-activate-major-mode-snippets` is long, you get used to it.  You could also rename that function to `auto-activating-snippets-on`, or rename the package to something short.

**Comment by ymarco** [comment]
Can I rename the file to `aas.el`, and change the few fully `auto-activating-snippets-`-prefixed functions? Seems like a lot less effort.
I'll refactor it with the prefix if there's a real need, but... the code becomes ugly. And I'll need to re-break a lot of lines.

**Comment by ymarco** [comment]
> we could do with adding a licence snippet / SPDX line and quoting `org-mode'
Done that!

**Comment by riscy** [comment]
> Can I rename the file to aas.el, and change the few fully auto-activating-snippets--prefixed functions? Seems like a lot less effort.  I'll refactor it with the prefix if there's a real need, but... the code becomes ugly. And I'll need to re-break a lot of lines.

Apologies I haven't answered this sooner.  Yes, `aas` would be a valid prefix; basically we ask that your package name and the prefixes (namespace) of your variables and functions all match so that we can proactively avoid naming collisions.

**Comment by ymarco** [comment]
Renamed auto-activating-snippets to aas,
and latex-auto-activating-snippets to laas.

@tecosaur I think the recipes need to be changed.

**Comment by riscy** [comment]
I went ahead and updated the recipe -- all looks good here.  Taking one more look at the code, I'd suggest wrapping some of the docstring lines for `aas-transient-snippet-condition-result` and the others closer to the way the rest of the file is wrapped.  The online help doesn't apply wordwrapping, and actually it can't because it can't know where to sensibly break lines.

Also I'm not entirely sure but should `(error "Unknown keyword: %s" item)` be a `user-error` instead, so that users don't see a backtrace when using unknown keywords?

Neither of those are blocking though, so I'll go ahead and merge.

**Comment by ymarco** [comment]
> I'd suggest wrapping some of the docstring lines for `aas-transient-snippet-condition-result` and the others closer to the way the rest of the file is wrapped.  The online help doesn't apply wordwrapping, and actually it can't because it can't know where to sensibly break lines.

Fixed this, thanks.

> Also I'm not entirely sure but should `(error "Unknown keyword: %s" item)` be a `user-error` instead, so that users don't see a backtrace when using unknown keywords?

I don't think so. Incorrect keywords are 'syntax errors' in the format accepted by aas-set-snippets. To my knowledge, user-errors are mostly for soft-failing in interactive functions - that doesn't apply here. Do correct me if I'm wrong.

**Comment by riscy** [comment]
Nope, sounds completely correct to me.  Thanks. :)

**Pull request merged**
