### PR TITLE
Add ip-address recipe

### PR DESCRIPTION
**Pull request by sean-hut**
### Brief summary of what the package does

IP address lookup.

### Direct link to the package repository

https://github.com/sean-hut/ip-address

### Your association with the package

I am the package author and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by sean-hut** [comment]
I searched for a package with this functionality and did not find one.

I search using:
- `M-x`
- `C-h f`
- `apropos`
I searched these archive:
- MELPA
- gnu archive with `package-list-packages`

Keywords searched for:
- ip
- ip addess
- ip-address

The only thing I found was `geoip` when I searched MELPA for the `ip address`. It has a different purpose than this package.

**Comment by dakra** [comment]
jFYI
I wrote a similar function that uses ipinfo: https://github.com/dakra/ipinfo.el/blob/master/ipinfo.el

I didn't publish it to melpa as it's only one function and a few lines but I find it useful nonetheless.

**Comment by sean-hut** [comment]
@dakra thanks for sharing the link.
It is interesting to see a different implementation.

**Comment by alphapapa** [comment]
@sean-hut This package's Git repo has 17 files totaling 979 lines of text and 676 KB.  Its code comprises a single Elisp function that retrieves a URL, matches a regexp, and prints a string--the equivalent of 3 lines of code.  Its readme is full of boilerplate, refers to nonexistent documentation, and does not explain what the package actually does or how to use it.

MELPA is not NPM.  You need not submit a package for every one-liner function you write, and you need not submit "practice" packages to demonstrate your project skeleton.  This is tantamount to spam.  It wastes the MELPA maintainers' time to have to sort through this in the limited time they have to process submissions.  Please close this PR.

**Comment by sean-hut** [comment]
> Its readme ... refers to nonexistent documentation, and does not
> explain what the package actually does or how to use it.

@alphapapa thank you for bringing to my attention the missing
`DOCUMENTATION.md` file.  It has been added to the repository.  The
beginning of the `README.md` file explains what the package does and
the documentation further explains what the package does and how to
use it.

https://sean-hut.github.io/ip-address/Usage.html#Usage

Further a link to the HTML documentation is provided in the
`ip-address.el` file's commentary header comment.

Also there is an info file in the project repository.

> You need not submit a package for every one-liner function you
> write, and you need not submit "practice" packages

> This is tantamount to spam. It wastes the MELPA maintainers' time to
> have to sort through this in the limited time they have to process
> submissions.

I do not think calling this package submission "spam" is correct.

My intention was to submit a package that has useful functionality.  A
package with this kind of functionality is useful to dakra (see
dakra's comment above) and I.  It is likely other people would also
find it useful.

**Comment by riscy** [comment]
I think @dakra was describing https://github.com/dakra/ipinfo.el/blob/master/ipinfo.el as being useful.

I tend to agree with @alphapapa that this package -- while I can see it being useful myself -- belongs among a larger set of utilities to these sorts of things, or maybe a larger duckduckgo API wrapper.

I'll close for now, but also willing to hear followups.

**Comment by sean-hut** [comment]
> this package -- while I can see it being useful myself -- belongs
> among a larger set of utilities to these sorts of things

Are there any suggestions for existing package that could potentially
be a candidates for adding this kind of functionality?

Alternatively what other complimentary functionality would be
desirable?  Depending on the scope of adding additional functionality
I could consider building out a larger set of utilities with the
intent of submitting it as a package to MELPA.

> or maybe a larger duckduckgo API wrapper.

When I search for a duckduckgo package I do not find anything.
duckduckgo is just an implementation detail.  The rationale was that
duckduckgo looked like a more privacy respecting source of ip address
information compared with other sources.  I am not currently planing
on create a duckduckgo package.

**Comment by riscy** [comment]
Here's the [article](https://www.tecmint.com/find-linux-server-public-ip-address/) where I read about this.  If we're at the command line, we can use the `host` utility e.g. `$ host myip.opendns.com resolver1.opendns.com` (or resolver4 for ipv4).  Otherwise the article lists some other services that can be curled directly.

The package here by contrast is basically a web scraper; it's not accessing any particular API, it's just hoping that the HTML of a search result page will contain some text in a certain place and then hacks out the surrounding markup.  What does the result look like if the service is unavailable?  If duckduckgo changes their page layout?  I think there are packages on MELPA like this, that scrape dictionaries and other things, but based on the aforementioned article I think this isn't a case where we need to do that sort of thing.

By "larger set of utilities" I guess I was thinking of something like an OS-agnostic version of the `dig` or `host` command-line tools that, but maybe I was being overly ambitious.  I don't know if something like that exists.

**Pull request closed without merging**
