### PR TITLE
Add new recipe "org-bookmarks"

### PR DESCRIPTION
**Pull request by stardiviner**
### Brief summary of what the package does

Manage bookmarks in Org mode.

### Direct link to the package repository

https://repo.or.cz/org-bookmarks.git

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`org-bookmarks.el` with byte-compile using Emacs 29.1:
```
org-bookmarks.el:34:2: Error: Cannot open load file: No such file or directory, ivy
```
Possibly a missing `Package-Requires`

`org-bookmarks.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- org-bookmarks.el#L4: Have you done the paperwork to assign this copyright?
```
(I always check for copy-paste errors here)


Package and license:
- Add a GPL-compatible LICENSE file to the repository

**Comment by progfolio** [comment]
Is the ivy dependency necessary?

**Comment by progfolio** [comment]
> > Is the ivy dependency necessary?
> 
> Yes, Ivy is required for minibuffer `completing-read` support "\n" new-line formating in candidates. I updated package dependencies now. Thanks for checking out update.

Interesting. 
For me, multiline candidates have worked for a long time and I've never used ivy.
e.g.

```emacs-lisp
(completing-read "with newlines: " '("One\nTwo" "Three\nFour"))
```

Which versions of Emacs does it not work for?

**Comment by stardiviner** [comment]
`completing-read` "\n" newline is not really displayed good for multi-line candidates.
I use vertico which does not support display like ivy. That's why I require ivy.

**Comment by progfolio** [comment]
> `completing-read` "\n" newline is not really displayed good for multi-line candidates. 

The candidate is highlighted, new lines and all.

> I use vertico which does not support display like ivy. That's why I require ivy.

I, too, use vertico. I've customized `vertico-multiline` similarly to the way the author of [this issue](https://github.com/minad/vertico/issues/285) did. Hasn't let me down yet.

> If I use `completing-read`, then I suppose to use one-line instead of two-line candidates.

Perhaps this limitation could better solved by utilizing `completion-extra-properties`?

Another issue I ran into when trying the package:
This line in org-bookmarks will singal an error:

```emacs-lisp
                       (properties (org-entry-properties element 'standard))
```

`org-entry-properties` expects a POM (point or marker) as the first argument for every version of Org I tested back to Emacs 27.1. Changing the first arg to `nil` worked, as the entry mapping has the current entry at point when this is called.

**Comment by stardiviner** [comment]
> > `completing-read` "\n" newline is not really displayed good for multi-line candidates.
> 
> The candidate is highlighted, new lines and all.
> 
> > I use vertico which does not support display like ivy. That's why I require ivy.
> 
> I, too, use vertico. I've customized `vertico-multiline` similarly to the way the author of [this issue](https://github.com/minad/vertico/issues/285) did. Hasn't let me down yet.
> 
> > If I use `completing-read`, then I suppose to use one-line instead of two-line candidates.
> 
> Perhaps this limitation could better solved by utilizing `completion-extra-properties`?

I tried following code snippet with `completion-extra-properties`:

```elisp
(browse-url
             (substring-no-properties
              (if (and (featurep 'ivy) ivy-mode)
                  (seq-elt (split-string (ivy-read "org-bookmarks: " bookmark-headlines) "\n") 1)
                (let ((completion-extra-properties
                       (list :category 'bookmark
                             :annotation-function (lambda (bookmark-headline)
                                                    (let ((url (cdr (split-string bookmark-headline "\n"))))
                                                      (concat (propertize " " 'display '(space :align-to center))
		                                                      (get-text-property 0 :annotation candidate)
                                                              (format " (%s)" url)))))))
                  (seq-elt (split-string (completing-read "org-bookmarks: " bookmark-headlines) "\n") 1)))))
```
But it's not displaying as two lines for candidate even I tried to search some code examples for reference. Can you improve it? thanks.

> Another issue I ran into when trying the package: This line in org-bookmarks will singal an error:
> 
> ```emacs-lisp
>                        (properties (org-entry-properties element 'standard))
> ```
> 
> `org-entry-properties` expects a POM (point or marker) as the first argument for every version of Org I tested back to Emacs 27.1. Changing the first arg to `nil` worked, as the entry mapping has the current entry at point when this is called.

The first argument `element` is from let-binding variable `(element (or headline (org-element-context)))` which should be the POM node. Can you provide the error? The elment supposed to be non-nil.

**Comment by progfolio** [comment]
> Can you improve it? thanks.

```emacs-lisp
(require 'org-element)

(defgroup org-bookmarks nil
  "The defcustom group of `org-bookmarks'."
  :prefix "org-boomarks-"
  :group 'org)

(defcustom org-bookmarks-file
  (expand-file-name "bookmarks.org" (file-name-directory (or load-file-name (buffer-file-name))))
  "The Org bookmarks filename."
  :type 'string
  :safe #'stringp)

(defcustom org-bookmarks-tag "bookmark"
  "The tag to mark Org headline as bookmark entry."
  :type 'string
  :safe #'stringp)

(defcustom org-bookmarks-browse-function #'browse-url
  "Function called by `org-bookmarks' with selected URL as its sole argument."
  :type 'function)

(defun org-bookmark--candidate (headline)
  "Return candidate string from Org HEADLINE."
  (when-let ((tags (org-element-property :tags headline))
             ((member org-bookmarks-tag tags))
             (url (alist-get "URL" (org-entry-properties headline 'standard) nil nil #'equal))
             (info (concat (unless (= (length tags) 1)
                             (format "[%s]" (string-join (delete org-bookmarks-tag tags) ":")))
                           "\n" (propertize url 'face 'link) "\n")))
    (propertize (org-element-property :raw-value headline) 'url url 'annotation info)))

(defun org-bookmark--candidates (file)
  "Return a list of candidates from FILE."
  (with-temp-buffer
    (insert-file-contents file)
    (delay-mode-hooks
      (org-mode)
      (goto-char (point-min))
      (let ((candidates nil))
        (org-element-map (org-element-parse-buffer 'headline) 'headline
          (lambda (headline) (when-let ((candidate (org-bookmark--candidate headline)))
                                  (push candidate candidates))))
        (nreverse candidates)))))

(defun org-bookmarks--annotator (candidate)
  "Annotate bookmark completion CANDIDATE."
  (concat (propertize " " 'display '(space :align-to center))
          (get-text-property 0 'annotation candidate)))

(defun org-bookmarks (&optional file)
  "Open bookmark read from FILE or `org-bookmarks-file'."
  (interactive)
  (if-let ((file (or file org-bookmarks-file))
           ((file-exists-p file)))
      (if-let ((candidates (org-bookmark--candidates file))
               (minibuffer-allow-text-properties t)
               (completion-extra-properties
                (list :category 'org-bookmark :annotation-function #'org-bookmarks--annotator))
               (choice (completing-read "org-bookmarks: " candidates nil 'require-match))
               (url (get-text-property 0 'url choice)))
          (funcall org-bookmarks-browse-function url)
       (user-error "No bookmarks found in %S" file))
    (user-error "File does not exist: %S" file)))

(provide 'org-bookmarks)

;;; org-bookmarks.el ends here
```

**Comment by progfolio** [comment]
> Wow, I have to say, I'm satisfied with your code totally. I overwrited the source code with your version and list you as co-author. Hope this will not offend you. 

I appreciate that, but I'd prefer not to be listed as a co-author.

A few comment on the latest version:

Binding this in the when-let will remove candidates which have `org-bookmarks-tag` as the only tag.
Since it's optional, it should be let-bound inside the body of the when-let form.

```
             (tags-searchable (remove org-bookmarks-tag tags))
```

Most of the comments I added were for review purposes.
Most of them should be removed.

The dependency on ivy is no longer necessary.

Loading a package should not change user options.
IMO, it would be best to remove all of the org-capture related stuff and document how to do that in the README or documentation. That will remove the dependency on both org-capture and nerd-icons (which some users will not want to use).

**Comment by riscy** [comment]
@progfolio I have to thank you, once again, for offering such great feedback. :)

My automated feedback in the meantime is going to pale in comparison --

- org-bookmarks.el#L4: Have you done the paperwork to assign this copyright?
- Add a GPL-compatible LICENSE file to the repository

**Comment by stardiviner** [comment]
> > Wow, I have to say, I'm satisfied with your code totally. I overwrited the source code with your version and list you as co-author. Hope this will not offend you.
> 
> I appreciate that, but I'd prefer not to be listed as a co-author. Feel free to use the code however you see fit, though.
> 
> A few comment on the latest version:
> 
> Binding this in the when-let will remove candidates which have `org-bookmarks-tag` as the only tag. Since it's optional, it should be let-bound inside the body of the when-let form.
> 
> ```
>              (tags-searchable (remove org-bookmarks-tag tags))
> ```
> 
> Most of the comments I added were for review purposes. Most of them should be removed.

Indeed, I have not noticed this logic bug. I fixed it now.

> The dependency on ivy is no longer necessary.
> 
> Loading a package should not change user options. IMO, it would be best to remove all of the org-capture related stuff and document how to do that in the README or documentation. That will remove the dependency on both org-capture and nerd-icons (which some users will not want to use).

Thanks for this advice, updated already by make it as an user option.

Done by updating code for other your suggestions.

**Comment by stardiviner** [comment]
> @progfolio I have to thank you, once again, for offering such great feedback. :)
> 
> My automated feedback in the meantime is going to pale in comparison --
> 
> * org-bookmarks.el#L4: Have you done the paperwork to assign this copyright?
Yes, I have already done the paperwork of FSF before when I used to contribute to Org mode.

> * Add a GPL-compatible LICENSE file to the repository
I added the GPLv3 LICESE file in the repo now.

**Comment by riscy** [comment]
Thank you!  Following some of the above discussed code changes, here's the latest --

`org-bookmarks.el` with byte-compile using Emacs 29.2:
```
org-bookmarks.el:139:22: Warning: reference to free variable `org-capture-templates'
org-bookmarks.el:141:7: Warning: assignment to free variable `org-capture-templates'
In end of data:
org-bookmarks.el:144:24: Warning: the function `nerd-icons-mdicon' is not known to be defined.
```

I should also let you know that `org-bookmarks-extractor` is in your "namespace", so take care not to write any `extractor` features :) https://melpa.org/#/org-bookmarks-extractor

**Comment by riscy** [comment]
Byte-compiler won't run functions, only compile them - so it will never touch that inlined `(require 'org-capture)`.  Instead you could have `(eval-when-compile (require 'org-capture))` at the top-level.

Regarding `nerd-icons-mdicons` you can pacify the compiler with `(declare-function ...`.

This may be new code, or something I hadn't noticed last time, but at the bottom of the file you have a form starting `(when org-bookmarks-add-org-capture-template ...` and this pattern is requiring users to set `org-bookmarks-add-org-capture-template` *before* they load the package.  When authors do this (anti?)pattern it makes for some fragile/awkward configs, and you should avoid it if you can.

Because you write:
```elisp
(defvar org-bookmarks--candidates-cache (org-bookmarks--return-candidates)
  "A cache variable of org-bookmarks--candidates.")
```
this code will run whenever users load the package, even if they don't have a bookmarks.el file. This causes an error like the following:
```elisp
Loading org-bookmarks.el
  org-bookmarks.el:Error: Emacs 29.2:
  (file-missing "Opening input file" "No such file or directory" "/workspace/pkg/bookmarks.org")
```

I also see `:prefix "org-boomarks-"` (should be booKmarks) in your `defgroup`.

**Comment by riscy** [comment]
Thanks for accommodating - here's the latest --

`org-bookmarks.el` with byte-compile using Emacs 29.2:
```
org-bookmarks.el:36:2: Error: Cannot open load file: No such file or directory, nerd-icons
```

`org-bookmarks.el` with checkdoc 0.6.2 (fix *within reason*):
```
org-bookmarks.el:66: Lisp symbol `org-capture' should appear in quotes
org-bookmarks.el:118: Argument `file' should appear (as FILE) in the doc string
```

`#'load`-check on each file:
```
Loading org-bookmarks.el
  org-bookmarks.el:Error: Emacs 29.2:
  (error "Eager macro-expansion failure: (file-missing \"Cannot open load file\" \"No such file or directory\" \"nerd-icons\")")
```

**Comment by stardiviner** [comment]
> Thanks for accommodating - here's the latest --
> 
> `org-bookmarks.el` with byte-compile using Emacs 29.2:
> 
> ```
> org-bookmarks.el:36:2: Error: Cannot open load file: No such file or directory, nerd-icons
> ```
> 
> `org-bookmarks.el` with checkdoc 0.6.2 (fix _within reason_):
> 
> ```
> org-bookmarks.el:66: Lisp symbol `org-capture' should appear in quotes
> org-bookmarks.el:118: Argument `file' should appear (as FILE) in the doc string
> ```

Fixed on update.

> `#'load`-check on each file:
> 
> ```
> Loading org-bookmarks.el
>   org-bookmarks.el:Error: Emacs 29.2:
>   (error "Eager macro-expansion failure: (file-missing \"Cannot open load file\" \"No such file or directory\" \"nerd-icons\")")
> ```

I changed `nerd-icons` requirement into
```elisp
(eval-when-compile (require 'nerd-icons))
(declare-function 'nerd-icons-mdicon "nerd-icons")
```
Don't know how to correctly solved the problem. In nerd-icons.el, the `nerd-icons-mdicon` is from macro `nerd-icons-define-icon` and `(nerd-icons-define-icon mdicon nerd-icons/mdicon-alist nerd-icons-font-family "Material Design Icons")`. Not a normal function.

I run `elisp-byte-compile-file` on file `org-bookmarks.el`, got no warning. Don't know how this error raised and how to fix it?

**Comment by stardiviner** [comment]
> Thanks for accommodating - here's the latest --
> 
> `org-bookmarks.el` with byte-compile using Emacs 29.2:
> 
> ```
> org-bookmarks.el:36:2: Error: Cannot open load file: No such file or directory, nerd-icons
> ```

I use `(eval-when-compile (require 'nerd-icons nil t))` should fixed the error, I have not tested using minimal clean Emacs environment. Updated in latest commit.

**Comment by riscy** [comment]
> Yes, I have already done the paperwork of FSF before when I used to contribute to Org mode.

My understanding is that this is done on a per-package basis, rather than someone signing copyright papers just for org-mode and then having that apply to any package they write in the future.  Let me know if I'm missing something.  (I'm specifically looking at the language in https://www.fsf.org/bulletin/2022/fall/copyright-assignment-with-the-fsf but I'm open to someone pointing out something more recent or formal.)

Here's the latest -

`org-bookmarks.el` with byte-compile using Emacs 29.2:
```
org-bookmarks.el:132:13: Warning: variable `_' not left unused
In end of data:
org-bookmarks.el:158:24: Warning: the function `nerd-icons-mdicon' is not known to be defined.
```
It looks like you're newly using an `if-let` where you use `_` as a variable name.  The `if-let` macro actually does make use of the variable, and hence the byte-compiler trips over it when it macroexpands.

The `nerd-icons-mdicon` warning can be resolved by replacing `(when (featurep 'nerd-icons) ...` with `(when (fboundp 'nerd-icons-mdicon) ...` which the byte-compiler is better able to understand.

**Comment by stardiviner** [comment]
> > Yes, I have already done the paperwork of FSF before when I used to contribute to Org mode.
> 
> My understanding is that this is done on a per-package basis, rather than someone signing copyright papers just for org-mode and then having that apply to any package they write in the future. Let me know if I'm missing something. (I'm specifically looking at the language in https://www.fsf.org/bulletin/2022/fall/copyright-assignment-with-the-fsf but I'm open to someone pointing out something more recent or formal.)

From my assigned paper, I seems contribute to GNU EMACS.
Maybe I read paper in wrong understanding, seems I don't need to assign a paper for each new Emacs package.
Notice the `(c) For the purposes of this contract, a work “based on the Works'' means any work that in whole or in part incorporates or is
derived from all or part of the Works.`

image

**Comment by stardiviner** [comment]
> Here's the latest -
> 
> `org-bookmarks.el` with byte-compile using Emacs 29.2:
> 
> ```
> org-bookmarks.el:132:13: Warning: variable `_' not left unused
> In end of data:
> org-bookmarks.el:158:24: Warning: the function `nerd-icons-mdicon' is not known to be defined.
> ```
> 
> It looks like you're newly using an `if-let` where you use `_` as a variable name. The `if-let` macro actually does make use of the variable, and hence the byte-compiler trips over it when it macroexpands.
> 
> The `nerd-icons-mdicon` warning can be resolved by replacing `(when (featurep 'nerd-icons) ...` with `(when (fboundp 'nerd-icons-mdicon) ...` which the byte-compiler is better able to understand.

Ok, I removed the variable `_` in `if-let` binding. and use `(fboundp 'nerd-icons-mdicon)` to replace.
I run `[C-c C-f] elisp-byte-compile-file` everytime, have not riased up any byte-compiler warning. can your show how to do this byte-compiler testing?

**Comment by progfolio** [comment]
> I run `[C-c C-f] elisp-byte-compile-file` everytime, have not riased up any byte-compiler warning. can your show how to do this byte-compiler testing?

If you enable flymake-mode, the compilation will take place in a separate Emacs process. Compiling in the same image you're working from can mask errors/warnings because you may have features loaded as a result of the development environment.

**Comment by stardiviner** [comment]
I tried `flymake-mode` and `flycheck-mode`, both no warnings. I guess because as I previous comment mentioned, I'm in my Emacs environment which alread loaded libraries.

**Comment by riscy** [comment]
> From my assigned paper, I seems contribute to GNU EMACS.

I agree with that part.  But you are conflating packages that are on MELPA with "the suite of programs known as GNU EMACS".  When you contributed to org, you were contributing to an Emacs builtin (org comes with Emacs, so you're contributing to Emacs itself, or the suite of programs known as GNU EMACS).  By contrast, when you contribute separate packages to MELPA, you are not contributing directly to the suite of programs known as GNU EMACS.  MELPA is not part of the suite of programs known as GNU EMACS.  MELPA is a separate entity, and Emacs itself has even taken recent steps to remove MELPA from its documentation.  If any of this is unclear, or if someone sees that I am incorrect in my reasoning, feel free to point it out.

>  have not riased up any byte-compiler warning. can your show how to do this byte-compiler testing? ... I asked this three times. no one can give me solution.

Please be patient - I do this on my weekends and the turnaround time can be a week.

Yes, most likely you're not seeing all of the compilation warnings because you're compiling your code in an instance of Emacs that has already loaded the code, or some past version of it at least.  Moreover, your environment (where you're running flycheck) also already has `nerd-icons` installed, but your package is written in such a way that `nerd-icons` is optional.  So if you wanted to test this scenario, you would have to remove `nerd-icons` from your environment.

**Comment by stardiviner** [comment]
> > From my assigned paper, I seems contribute to GNU EMACS.
> 
> I agree with that part. But you are conflating packages that are on MELPA with "the suite of programs known as GNU EMACS". When you contributed to org, you were contributing to an Emacs builtin (org comes with Emacs, so you're contributing to Emacs itself, or the suite of programs known as GNU EMACS). By contrast, when you contribute separate packages to MELPA, you are not contributing directly to the suite of programs known as GNU EMACS. MELPA is not part of the suite of programs known as GNU EMACS. MELPA is a separate entity, and Emacs itself has even taken recent steps to remove MELPA from its documentation. If any of this is unclear, or if someone sees that I am incorrect in my reasoning, feel free to point it out.

What paper should I sign if the FSF paper is not that one for me to contribute to MELPA?
MELPA as a Emacs Package Archive hosting service, Emacs as a program. I don't understand the conflict. For me, it looks like a file hosting server, and a file copyright.

I don't want to discuss the copyright topic under your words which only raise a obscure question but don't give out solution. It's meanless.

> > have not riased up any byte-compiler warning. can your show how to do this byte-compiler testing? ... I asked this three times. no one can give me solution.
> 
> Please be patient - I do this on my weekends and the turnaround time can be a week.
> 
> Yes, most likely you're not seeing all of the compilation warnings because you're compiling your code in an instance of Emacs that has already loaded the code, or some past version of it at least. Moreover, your environment (where you're running flycheck) also already has `nerd-icons` installed, but your package is written in such a way that `nerd-icons` is optional. So if you wanted to test this scenario, you would have to remove `nerd-icons` from your environment.

As I mentioned on previous comment, I also already tried command `emacs -Q` (which should not load installed packages), still same.

**Comment by riscy** [comment]
> What paper should I sign if the FSF paper is not that one for me to contribute to MELPA?

You don't have to sign any papers at all - the copyright is yours unless you sign papers and assign it to someone else.  I'm not a lawyer but my view is that reusing your previous unrelated copyright assignment for this package is incorrect - this package isn't part of GNU EMACS.  It runs on GNU EMACS, yes, but it isn't distributed as part of the core.

> I don't want to discuss the copyright topic under your words which only raise a obscure question but don't give out solution. It's meanless.

The solution here is really simple in case we're accidentally talking in circles - just rewrite `;; Copyright (C) 2020-2021 Free Software Foundation, Inc.` to indicate that you own the copyright (unless you've done the paperwork with GNU).

If you think this will be difficult for you to do, I'll close this PR and I recommend looking at another package repository, like ELPA or non-GNU ELPA.

**Comment by stardiviner** [comment]
> > I don't want to discuss the copyright topic under your words which only raise a obscure question but don't give out solution. It's meanless.
> 
> The solution here is really simple in case we're accidentally talking in circles - just rewrite `;; Copyright (C) 2020-2021 Free Software Foundation, Inc.` to indicate that you own the copyright (unless you've done the paperwork with GNU).
> 
> If you think this will be difficult for you to do, I'll close this PR and I recommend looking at another package repository, like ELPA or non-GNU ELPA.

I see, you mean changed into `Copyright (C) 2024-2025 stardiviner <numbchild@gmail.com>`?

**Comment by riscy** [comment]
That's correct @stardiviner  :)

**Comment by stardiviner** [comment]
Ok, @riscy I updated in latest commit now. The package should be ok now.

**Comment by riscy** [comment]
Thank you @stardiviner for accommodating this process.  Merging!

**Comment by stardiviner** [comment]
Haha, finally got merged, thanks, all of you, guys. Celebrate my another new package.

**Pull request merged**
