### PR TITLE
add org-searcher

### PR DESCRIPTION
**Pull request by beacoder**
### Brief summary of what the package does
Incremental org-search-view

[Please write a quick summary of the package.]
Incremental org-search-view

### Direct link to the package repository
https://github.com/beacoder/org-searcher

### Your association with the package
author

### Relevant communications with the upstream package maintainer
N/A

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this  -- quick first (automated) pass:

### org-searcher.el ###

byte-compile (using Emacs 27.1):
```
org-searcher.el:107:17:Warning: assignment to free variable `files'
org-searcher.el:117:34:Warning: reference to free variable `files'
org-searcher.el:164:19:Warning: assignment to free variable `rtnall'
org-searcher.el:162:39:Warning: assignment to free variable `index'
org-searcher.el:160:33:Warning: assignment to free variable `ee'
org-searcher.el:152:34:Warning: assignment to free variable `beg'
org-searcher.el:155:73:Warning: assignment to free variable `beg1'
org-searcher.el:161:38:Warning: assignment to free variable `end'
org-searcher.el:156:92:Warning: reference to free variable `beg'
org-searcher.el:155:42:Warning: reference to free variable `beg1'
org-searcher.el:158:41:Warning: assignment to free variable `txt'
org-searcher.el:158:41:Warning: reference to free variable `index'
org-searcher.el:160:29:Warning: reference to free variable `txt'
org-searcher.el:163:33:Warning: reference to free variable `ee'
org-searcher.el:163:33:Warning: reference to free variable `end'
org-searcher.el:164:41:Warning: assignment to free variable `rtn'
org-searcher.el:165:11:Warning: reference to free variable `rtnall'
org-searcher.el:165:11:Warning: reference to free variable `rtn'
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210320.438):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- org-searcher.el#L71: It's safer to sharp-quote function names; use `#'`
- org-searcher.el#L184: It's safer to sharp-quote function names; use `#'`
- org-searcher.el#L69: It's safer to sharp-quote function names; use `#'`
- org-searcher.el#L70: It's safer to sharp-quote function names; use `#'`
- org-searcher.el#L182: It's safer to sharp-quote function names; use `#'`
- org-searcher.el#L183: It's safer to sharp-quote function names; use `#'`

**Comment by alphapapa** [comment]
How does this relate to existing Org search tools, like `org-ql` and `org-rifle`?  The readme has no explanation nor screenshots, and the code doesn't make it obvious what advantage it could confer over other tools.

**Comment by beacoder** [comment]
this tool is used to incrementaly search org files.
it utilize ivy to search across the org files.
previewing the org files while you typing keywords.

**Comment by beacoder** [comment]
it's kind of like google searching over your org files.

**Comment by beacoder** [comment]
Just added screenshots.

**Comment by alphapapa** [comment]
Thanks for the screenshots, but you didn't answer my questions.  e.g. `org-rifle` has been around for 5 years now, and is a mature, powerful package.  `org-ql` has been around for 3 years and is an even more powerful searching tool that mostly obsoletes `org-rifle`.

So what purpose does `org-searcher` serve?  Why would a user choose it over these other, more mature, more powerful tools?  Have you even seen them?

**Comment by beacoder** [comment]
I think you got a point, then I'll withdraw my commit.

**Comment by alphapapa** [comment]
Ok.  If you have ideas for improvements to make to org-rifle and/or org-ql, please feel free to suggest them on their trackers.

**Pull request closed without merging**
