### PR TITLE
Add share2computer

### PR DESCRIPTION
**Pull request by tumashu**
### Brief summary of what the package does

an elisp helper of android ShareToComputer app.

### Direct link to the package repository

https://github.com/tumashu/share2computer

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer
 **None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

1. Please add some keywords to `Keywords` header.
2. Please define custom variables group before use.

I pick-up `convenience` keyword for your package, but there is a better keyword maybe.

**Comment by riscy** [comment]
Hello!  Mostly this looks good, just a few quick patches.  First, please use a LICENSE file that GitHub can detect -- see: https://github.com/licensee/licensee.  

Would it be worth adding a `(require 'org)` since org comes with Emacs?  That way you won't have to stub the org functions with these:
```elisp
(declare-function org-back-to-heading "org" (&optional invisible-ok))
(declare-function org-attach-dir "org" (&optional create-if-not-exists-p no-fs-check))
```
if you want to delay pulling in org, you could always inline the require:
```elisp

;;;###autoload
(defun share2computer-org ()
  "Download files shared by Android ShareToComputer to org attach dir."
  (interactive)
  (require 'org)
  (let (c marker)
    (when (eq major-mode 'org-agenda-mode)
      (setq marker (or (get-text-property (point) 'org-hd-marker)
		       (get-text-property (point) 'org-marker)))
      (unless marker
	(error "No task in current line")))
    (save-excursion
      (when marker
	(set-buffer (marker-buffer marker))
	(goto-char marker))
      (org-back-to-heading t)
      (share2computer--internal (org-attach-dir t)))))
```

Truly the license-in-repo is the most important, the rest is for your consideration.  This looks good.

And some non-blockers (for your consideration):
- I noticed @conoa3's comment about additional keywords, and `comm` feels like a nice fit: `(comm . "communications, networking, and remote file access")`
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems

**Comment by tumashu** [comment]
@riscy should fixed

**Comment by riscy** [comment]
I should have tested my suggestion, but it looks like if you inline the `(require 'org)` (which I think you should still do) you still need the `declare-function` lines to resolve compiler warnings:

```
share2computer.el:270:1:Warning: the following functions are not known to be
    defined: org-back-to-heading, org-attach-dir
```

I don't think that's worth blocking on since I know you can fix it -- and apologies for the oversight on my part.

**Pull request merged**
