### PR TITLE
Add recipe for hotfuzz

### PR DESCRIPTION
**Pull request by axelf4**
### Brief summary of what the package does

Implements the `O(MN)` algorithm for sequence alignment used by e.g. fzf as an Emacs completion style.

### Direct link to the package repository

https://github.com/axelf4/hotfuzz

### Your association with the package

I am the author and maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

(There are a few warnings that I consider to be false positives.)

### CODE REVIEW

**Comment by tarsius** [comment]
You need to specify the version for the `cl-lib` dependency. You could use "0.5" or the current version "0.7". For packages that have no release, use "0".

**Comment by manuel-uberti** [comment]
Just an FYI to @minad and @oantolin: you may want to have a look at this one. :)

**Comment by minad** [comment]
@manuel-uberti Thanks for pinging me. This looks indeed very interesting!

@axelf4 Some comments:

* Do you need the `hotfuzz-selectrum-mode`? Selectrum works with completion styles out of the box now. You may also want to take a look/test with Icomplete/Icomplete-vertical or my Vertico package, which is quite similar to Selectrum UI-wise, but is simpler internally and more compliant with the Emacs completion machinery.
* Regarding the sorting I am not sure if the approach you are doing works in every scenario. Completion styles usually do not sort. Either the `display-sort-function` specified by a completion table or the default sorting function used by the completion UI will sort the candidates after the filtering. Only in Selectrum the sorting happens before the filtering. This is actually a Selectrum quirk, which is not strictly correct and causes problems with some completion tables. Because sorting happens usually happens after filtering, the Emacs built-in `flex` completion style uses an ugly mechanism, the `completion--adjust-metadata` hack you can find in minibuffer.el. I am not recommending you to use this metadata adjustment hack, since I think it is a bad design. But for now it seems to be the only way to override the sorting from the side of the completion style ;)
* I think what I am recommending is the following: Decouple the sorting from the filtering (hotfuzz-filter and hotfuzz-sort, you already have the highlighting decoupled - good for efficiency). The filtering should only compute the scores and then the sorting function should be called afterwards and can take the precomputed score into account. Depending on the completion UI, one has to plug the filtering and sorting together. One can either use the `completion--adjust-metadata` trick which works with default completion, Icomplete, Vertico. In Selectrum one can overwrite the `selectrum-refine-function` with a functon which hotfuzz filters and sorts in one go, basically as you have it. In Vertico there is an additional possibility to overwrite the recently introduced `vertico-sort-function`. So there are multiple possibilities and it unfortunately depends on the UI you use. I assume Helm and Ivy have their own additional requirements.

**Comment by minad** [comment]
@tarsius 

> You need to specify the version for the cl-lib dependency. You could use "0.5" or the current version "0.7". For packages that have no release, use "0".

Why not remove the cl-lib dependency, since it is part of Emacs?

**Comment by tarsius** [comment]
If you use `cl-lib`, then you have to either specify `cl-lib` as a dependency or `emacs` >= 24.3 or one of the linters will complain.

**Comment by minad** [comment]
@tarsius hotfuzz requires Emacs 27.1

**Comment by tarsius** [comment]
:blush: well well.
Then the `cl-lib` dependency can of course be dropped.

**Comment by axelf4** [comment]
@tarsius I read [here][Library Headers] that no version specified means that all versions are acceptable, which should be OK? But yes it can be removed as it is only there for explicitness right now.

> Some comments:

@minad `hotfuzz-selectrum-mode` is needed for deferred highlighting and also sorting in Selectrum. I have tried hotfuzz with Vertico and it works well, with the exception of highlighting.

For the implementation of the completion style, I try to reuse as much of the implementation of `flex` as possible (the only difference is the scoring algorithm). It cannot use `hotfuzz-filter`, as that function does not have the entire `all-completions` semantics. The alternative would be to have, as you say, `hotfuzz-filter` only do filtering, using the internal `flex` functions. But it does not sit quite right with me to have one of the main public functions depend on unstable implementation details of Emacs, instead of confining that to the already messy completion style part of the library.

> Is there a possibility to get deferred highlighting with your hotfuzz style if you use `completion-all-completions`?

I looked into this earlier, however because Hotfuzz does not use `completion-hilit-commonality`/etc. but instead `hotfuzz-highlight` I do not think it would be possible without more special-casing.

[Library Headers]: https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html

**Comment by tarsius** [comment]
> I read here that no version specified means that all versions are acceptable, which should be OK? 

Yes, it seems I was wrong about this. Since 25.3 the documentation mentions that an atom is valid. I don't know if that just clarifies something that was always the case or whether in some earlier version this really had to be a list.

**Comment by minad** [comment]
> I looked into this earlier, however because Hotfuzz does not use completion-hilit-commonality/etc. but instead hotfuzz-highlight I do not think it would be possible without more special-casing.

It shouldn't be a problem to add hotfuzz special casing to Vertico/Corfu. I am already doing this for Orderless as long as bug#47711 is not resolved. See https://github.com/minad/vertico/blob/cc213e31c7fe3084e63a0600765e1641361a4b62/vertico.el#L282-L289. I would only wait a bit until your library stabilizes a bit more. Right now, highlighting only works with Selectrum?

Thinking a bit more about it - one problem with flex completion styles is that you copy the candidates to attach the score. The copying of the candidates can be expensive additional to adding the faces. Maybe the best approach is even different:

1. hotfuzz-filter: Filter using `all-completions` with the appropriate flex regexp or via `
2. hotfuzz-sort: Decorate each candidate with the score as a cons cell (candidate . score), without copying the candidate
3. hotfuzz-highlight: Copy the candidate, add highlighting (only the visible candidates!)

The all-completions function calls `hotfuzz-filter`, followed by `hotfuzz-highlight` (not deferred). `hotfuzz-sort` is done via the metadata adjustment ugliness. To defer highlighting one would use only `hotfuzz-filter` on all candidates, but this as of now requires special casing.

What about implementing the metadata adjustment and the all-completions function differently? Don't use flex for the metadata adjustment but your own optimized sorting function, which does the sorting of cons cells? Furthermore don't copy the candidate in all-completions.

**Comment by minad** [comment]
I made a first draft patch set for minibuffer.el adding deferred highlighting - https://github.com/minad/emacs/commits/deferred-highlighting. So hopefully we will get a general solution for deferred highlighting soon.

**Comment by axelf4** [comment]
> What about implementing the metadata adjustment and the all-completions function differently? Don't use flex for the metadata adjustment but your own optimized sorting function, which does the sorting of cons cells?

I tried this now but ran into problems because the adjusted `display-sort-function` cannot know the current search string.

Also, I tried to replace my bespoke `hotfuzz-filter` implementation of `flex` matching with
```elisp
(defun hotfuzz-filter (string candidates)
  (let* ((completion-styles '(hotfuzz))
         (md '(metadata))
         (all (completion-all-completions string candidates nil (length string) md))
         (last (last all)))
    (when last (setcdr last nil)) ; Completions may contain base-size in last cdr
    (funcall (completion-metadata-get md 'display-sort-function) all)))
```
which just calls into `completion-all-completions`. However, it turned out to take ~170% as long when benchmarked which is quite a lot.

**Comment by minad** [comment]
> I tried this now but ran into problems because the adjusted display-sort-function cannot know the current search string.

This is indeed the case. This will be fixed in my deferred-highlighting branch.

**Comment by riscy** [comment]
Thanks @axelf4 for this!

> Yes, it seems I was wrong about this. Since 25.3 the documentation mentions that an atom is valid. I don't know if that just clarifies something that was always the case or whether in some earlier version this really had to be a list.

This was new to me too so I appreciated learning about this.  I think there are still advantages to specifying the version number, mainly reproducibility.  Also, with respect to Emacs and MELPA, being explicit lets package-lint check the version number, including whether it's impossibly high, whether it's a snapshot, that sort of thing.  I agree that technically that package-lint is a false-positive, but in this case I'd just remove it altogether.

The other checklist stuff:

checkdoc (using version 0.6.2):
```
Warning (emacs): 
hotfuzz.el:68: Argument `b' should appear (as B) in the doc string
Warning (emacs): 
hotfuzz.el:90: All variables and subroutines might as well have a documentation string
Warning (emacs): 
hotfuzz.el:152: Argument `string' should appear (as STRING) in the doc string
```
You mentioned these are false positives.  You _may_ want to look at the one on line 68 because it could improve the appearance of the `*Help*` buffer for that function, where arguments are helpfully highlighted:

image

And I'd personally ask that you give in to checkdoc on line 90, at least until we change the guidelines that everyone has to follow about this (admittedly minor) lint.  I agree 152 is a passable false positive. 

package-lint (using version 20210528.2348):
```
3 issues found:
7:0: error: Expected (package-name "version-num"), but found cl-lib.
150:0: warning: Private functions generally should not be autoloaded.
191:2: error: Global minor modes should be autoloaded or, rarely, `:require' their defining file (i.e. ":require 'hotfuzz"), to support the customization variable of the same name.
```

I'm not sure I understand why you consider 150 a false positive here.  Does this need to be available to the user before the package is loaded?  191 _is_ wrapped in an autoload, but it doesn't make sense to me that you'd wrap the defvar in the same progn as the minor mode (why should that variable be autoloaded?)

Beyond those, I see one more Emacs lisp "antipattern" where you're silently modifying Emacs (`completion--adjust-metadata`, `completion-styles-alist`) when someone loads the package.  In most cases such modifications should happen only when the user explicitly requests them, usually by enabling a mode.  Otherwise there's no easy way for users to undo this change and it creates invisible interactions between packages as users load them in.

**Comment by tarsius** [comment]
> error: Expected (package-name "version-num"), but found cl-lib.

Ah, that's where I got that idea from. @purcell, that's not correct. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html.

**Comment by axelf4** [comment]
> Right now, highlighting only works with Selectrum?

Yup. One could probably optimize highlighting such that the overhead is not *too* bad, but it feels wrong since there should be no need to highlight non-visible candidates anyway.

> I agree that technically that package-lint is a false-positive, but in this case I'd just remove it altogether.

Will do. (But would be nice if package-lint got fixed :).)

> You mentioned these are false positives. You may want to look at the one on line 68 because it could improve the appearance of the `*Help*` buffer for that function, where arguments are helpfully highlighted:

Will capitalize the `i` in `row i` and `row i-1`. However, `B` not being highlighted in `Bⱼ` while `A` in `Aᵢ` is has to be something that could be fixed in Emacs, right? The unicode subscript characters ᵢ/ⱼ should be treated the same and at least according to UAX #​29 they both do break words. I also think the subscripts improve the doc more than highlighting ;), so I am hesitant to change this.

> And I'd personally ask that you give in to checkdoc on line 90, at least until we change the guidelines that everyone has to follow about this (admittedly minor) lint.

:+1:

> I'm not sure I understand why you consider 150 a false positive here. Does this need to be available to the user before the package is loaded? [...]
> 
> Beyond those, I see one more Emacs lisp "antipattern" where you're silently modifying Emacs (`completion--adjust-metadata`, `completion-styles-alist`) when someone loads the package. In most cases such modifications should happen only when the user explicitly requests them, usually by enabling a mode. Otherwise there's no easy way for users to undo this change and it creates invisible interactions between packages as users load them in.

I do think this is fine since adding entries to `completion-styles-alist` does not actually change anything (presuming the `hotfuzz` symbol is unique), unless the user explicitly adds the corresponding symbols to `completion-styles`. Orderless does a similar thing: https://github.com/oantolin/orderless/blob/2646dad28c0819fbe9ee521d39efb9ae40e03982/orderless.el#L444-L448

`hotfuzz--all-completions` needs to be autoloaded so that the package can be loaded only once the user first completes something (since it will then be looked up from `completion-styles-alist`).

> 191 *is* wrapped in an autoload, but it doesn't make sense to me that you'd wrap the defvar in the same progn as the minor mode (why should that variable be autoloaded?)

You are right, it did not have to be included. The documentation of `define-minor-mode` did not mention whether disabling a disabled mode would "disable" it and run `BODY`. So what I envisioned was that `(hotfuzz-selectrum-mode 0)` would cause the false-branch of the `if` in the body to run, where `hotfuzz--prev-selectrum-functions` could be undefined. But turns out this does not happen.

**Comment by riscy** [comment]
> I also think the subscripts improve the doc more than highlighting ;), so I am hesitant to change this.

Okay, I won't insist.  Just keep in mind the checklist is (_also_) there to make the MELPA reviewers' jobs easier, so you're doing us a time-saving favor when you can "fix" items that you nevertheless consider non-issues.  En masse MELPA contributors have more time than MELPA reviewers.  And sometimes this might entail some creative rephrasing of docstrings, etc.

> hotfuzz--all-completions needs to be autoloaded so that the package can be loaded only once the user first completes something (since it will then be looked up from completion-styles-alist).

Thanks, I understand now.  I was (am?) fairly ignorant of the completions API.  That said, it strikes me that it should be a public function, since really it's part of your package's public interface.  I think package-lint is correct here, and altogether it looks like you're within reach of a clean package-lint, which has its own benefits (e.g. you won't get used to seeing warnings if a significant issue arises).

> I do think this is fine since adding entries to completion-styles-alist does not actually change anything (presuming the hotfuzz symbol is unique)

I played around with it and I think you're right that it doesn't do any harm as of Emacs 27.  It still seems sloppy to leave it kicking around in case a user runs `unload-feature` (you may want to write a `hotfuzz-unload-function`).  I still think being strict about limiting modifications like this when loading packages is a good thing to do, regardless of what other packages in the MELPA index might be doing.

**Comment by minad** [comment]
@riscy 

> I played around with it and I think you're right that it doesn't do any harm as of Emacs 27. It still seems sloppy to leave it kicking around in case a user runs unload-feature (you may want to write a hotfuzz-unload-function). I still think being strict about limiting modifications like this when loading packages is a good thing to do, regardless of what other packages in the MELPA index might be doing.

I am quite familiar with the completion styles API, I recommend to not add a separate mode for this and allow hotfuzz to modify the alist directly. There won't be any benefit of a mode. Orderless is a good reference for this package.

**Comment by axelf4** [comment]
@riscy I have pushed a commit now with the changes you requested.

**Comment by riscy** [comment]
Hi @axelf4, I suggest you remove the unneeded `progn` wrapping your minor mode's definition.  As a nice side effect of that you'll have a clean package-lint.  I think that's too minor to block on at this point, so this is good to merge.  And, welcome to MELPA. :)

**Pull request merged**
