### PR TITLE
Add recipe for cloud-theme

### PR DESCRIPTION
**Pull request by vallyscode**
### Brief summary of what the package does

Light colored theme, easy on eyes.

### Direct link to the package repository

https://github.com/vallyscode/cloud-theme

### Your association with the package

Author, maintainer, contributor, user

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi!  Please ping if you need any direction on the following.

--------

These checks are semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd>:
No issues! 💯

<kbd>M-x package-lint</kbd> (using version 20190606.2210):
```
3 issues found:

1:1: error: There is no (provide 'cloud-theme) form.
1:50: warning: You should depend on (emacs "24") if you need lexical-binding.
7:1: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```

<kbd>M-x byte-compile-file</kbd>:
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (not on the MELPA checklist):
No issues! 🎉

-------
Minor stuff:
- 24: Prefer `https` over `http` (if possible)

**Comment by vallyscode** [comment]
Hi,
I have a question regarding: 1:1: error: There is no (provide 'cloud-theme) form.
Just checked against other themes, and I see that all of them define like (deftheme leuven .... and export like (provide-theme 'leuven), mine is similar: (deftheme cloud "Cloud light color theme") and export (provide-theme 'cloud), what should be corrected?

Regarding keywords, leuven has ;; Keywords: color theme
should I add the same?

Thanks

**Comment by vallyscode** [comment]
Looks funny, according to package-lint there should be (provide 'cloud-theme) but this is a theme so there must be (provide-theme 'cloud). That tool probably should distinguish the package types, I guess

**Comment by riscy** [comment]
I am no expert at Emacs color themes, but some of them take the approach of splitting the theme's "core library" out from the theme specifics (e.g. see [this popular theme](https://github.com/purcell/color-theme-sanityinc-tomorrow)).  My browsing revealed there are a couple themes that do this even when there's one variant of the theme.

However, it seems to me you could satisfy the linter by ending your file with:
```elisp
(provide-theme 'cloud)
(provide 'cloud-theme)
;;; cloud-theme.el ends here
```
But maybe @purcell can weigh in on what the best choice is here.

--------

To satisfy the linter, what I would do is change your keywords to:
```
;; Keywords: faces, color theme
```
That way you have at least _one_ of the top-level keywords in your list.

**Comment by vallyscode** [comment]
I looked through that theme you provided, lets look into:
https://github.com/purcell/color-theme-sanityinc-tomorrow/blob/master/color-theme-sanityinc-tomorrow.el
and theme is exported as usual: (provide-theme ',name)
But, there are a bunch of functions there and author wanted to export them, so he did it via:
(provide 'color-theme-sanityinc-tomorrow)
In my case I do not export any function at all so why should I add (provide 'cloud-theme), this is not necessary in my case.

Regarding keywords, you suggested:
;; Keywords: faces, color theme

Purcell has:
;; Keywords: faces themes

Which is correct?

**Comment by riscy** [comment]
That's my bad.  I'd go with the latter (and it looks like the standard is to pluralize keywords, so I was way off).  `lm-keywords-list` (the function that extracts the keywords) is happy with you using commas, or no commas if every keyword is a single word, so that's up to you.

**Comment by vallyscode** [comment]
So to summarize:
1:1: error: There is no (provide 'cloud-theme) form.   - **Added** (provide 'cloud-theme)
1:50: warning: You should depend on (emacs "24") if you need lexical-binding. - **Added** (emacs "24")
7:1: warning: You should include standard keywords: see the variable `finder-known-keywords'. - appeared to be fine

Fixed all issues.

Thanks

**Comment by purcell** [comment]
> 1:1: error: There is no (provide 'cloud-theme) form.

I might change `package-lint` to remove this error for theme files, but I also kinda thing it's harmless to provide the feature, since it's still a loadable elisp file.

Anyhow, all looks good, so merging now. Welcome to MELPA! :tada:

**Pull request merged**
