### PR TITLE
Add recipe for ivy-resize.

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Auto resize `ivy' window base on number of candidates

### Direct link to the package repository

https://github.com/jcs-elpa/ivy-resize

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
I see in the readme that you linked to the issue where you posted your code only 13 days ago: https://github.com/abo-abo/swiper/issues/649.  This seems like a simple feature that should be built-in to Ivy, and @abo-abo said about the idea:

> Unfortunately, due to the way Emacs minibuffer works, I currently don't know if it's possible to shrink the minibuffer window. Suggestions welcome.

So he seems amenable to including the feature.  Why don't you wait and see if it can be merged into Ivy instead of publishing another package that users will have to discover and install and configure.

**Comment by jcs090218** [comment]
Sorry I am kind of the guy that are being rush and hoping this feature get implemented! I can do both, and not sure if @abo-abo has the time. I think he is being busy or not available recently?

**Comment by riscy** [comment]
The code looks good, but I tend to agree with @alphapapa here -- this behavior feels like it could be part of `ivy`.

In my opinion, the best path forward for users would probably be for you to open a PR (although I'm sure lots of people appreciate seeing that you posted a solution in the issue as a stop-gap).

**Comment by jcs090218** [comment]
I will go for your suggestion, thanks!

**Comment by jcs090218** [comment]
I will reopen this since @abo-abo has mention that he prefer to avoid extra work in `post-command-hook` at [swiper/2389](https://github.com/abo-abo/swiper/pull/2389#event-2922582638). :scream:

**Comment by alphapapa** [comment]
He said:

> Thanks for the PR. But I prefer to avoid doing extra work in post-command-hook. Please review the referenced commit and see if it works for you.

The commit he referenced seems to implement a feature like this.  You haven't commented on the commit nor explained why your package is still necessary.

**Comment by jcs090218** [comment]
Okay, I just saw the reference commit. I wasn't sure what he meant in the first place. Thanks! :D

**Pull request closed without merging**
