### PR TITLE
Replace the gdscript-mode package with GDQuest/emacs-gdscript-mode

### PR DESCRIPTION
**Pull request by NathanLovato**
### Brief summary of what the package does

This package brings support for the [Godot engine](https://godotengine.org/)'s GDScript programming language in Emacs.

### Direct link to the package repository

https://github.com/GDQuest/emacs-gdscript-mode

### Your association with the package

I'm the maintainer, actively working on the package, and would like

### Relevant communications with the upstream package maintainer

The gdscript-mode package currently available on MELPA is unmaintained and does not work well.

This new package, based on Emacs's built-in `python.el`, covers all the basics to write GDScript code in Godot.

Its largest files, `gdscript-fill-paragraph.el`, `gdscript-indent-and-nav.el`, and `gdscript-syntax.el`, and some more, reuse a lot of code from `python.el`. That is because GDScript has a syntax similar to Python. I just renamed and adapted the corresponding functions, trying to remove everything that was not relevant to GDScript.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by NathanLovato** [comment]
This is my first time creating an Emacs package and working with lisp. I already got two reviews from a reddit user, on r/emacs, and from the maintainer of Doom Emacs, but I really welcome all the feedback you could give me to improve it!

While I ran `checkdoc` and the linter on every file, and generally followed every step in your contributing guide, there is one category of linting error I didn't address in the `gdscript-indent-and-nav.el` package: using the package name as the functions' prefix.

To me, it would make the function names and variables less readable, and the package is self-contained - I've just extracted and group code away from the main package to make the code easier to maintain and contribute to.

Should I fix this linter error for inclusion in MELPA? Or is it fine to leave it as it is?

**Comment by tarsius** [comment]
This proposal is about replacing https://github.com/AdamBark/gdscript-mode/blob/master/gdscript-mode.el.

**Comment by tarsius** [comment]
It might be a good idea to ask @AdamBark for feedback...

**Comment by AdamBark** [comment]
I know it hasn't been updated in a while but I haven't had any contributions either...

**Comment by NathanLovato** [comment]
@AdamBark It's nothing against you. If you don't have the time or will to actively develop the package yourself, or if you don't do GDScript in emacs a lot, it's completely fine. 

> but I haven't had any contributions either...

That's [unfortunately] normal. I contributed a lot more to other projects than I got contributions. In our own projects, even the most popular ones, we have to do the heavy lifting. Sometimes we get great contributions, and that's always a pleasure. But it's occasional. And that's with ~100,000 subscribers on YouTube, ~10,000 followers on Twitter...

I'd personally rather have contributed to an existing gdscript-mode package. In this case, though, yours is small (~70 lines of code), it's not seen much development since its initial release, and it's not under active development: the last commit is from more than 2 years ago.

I saw two alternate packages that aren't up-to-date or maintained anymore. 

From there, it just made sense for me to build a new package. You know how much faster you are working on your own repo, compared to making PRs and waiting for reviews. You can see our project already has a few thousand lines of code and quite a few features. It also supports Godot 3.2.

In any case, for me, it's just a matter of having and providing solid GDScript support in Emacs. We work full-time around free software now, and as an Emacs user and Godot contributor, I'd be able to keep improving GDScript support in Emacs.

So Adam, would you mind if we took care of maintaining the gdscript-mode for Emacs?

**Comment by AdamBark** [comment]
I'm glad to see a working GDScript mode so it's fine with me. I appreciate your work too and backed your krita tutorials, thanks.

**Comment by NathanLovato** [comment]
Thanks! And thanks :)

**Comment by tarsius** [comment]
I did not realize how authoritative the new version really is. :wink: You've got my okay for this move, but now you will also have to wait for the regular regular review, which can take a while.

**Comment by NathanLovato** [comment]
Sure! Thanks.

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings

```diff
diff --git a/Cask b/Cask
new file mode 100644
index 0000000..0d75820
--- /dev/null
+++ b/Cask
@@ -0,0 +1,4 @@
+(source gnu)
+(source melpa)
+
+(package-file "gdscript-mode.el")
```

```shell
$ cask; cask build
Loading package information... done
Package operations: 1 installs, 0 removals
  - Installing [ 1/1] emacs (26.3)... already present
Compiling /home/conao/dev/forks/emacs-gdscript-mode/emacs-rx.el...

In rx--empty:
emacs-rx.el:240:15:Warning: reference to free variable ‘regexp-unmatchable’
Compiling /home/conao/dev/forks/emacs-gdscript-mode/gdscript-completion.el...

In toplevel form:
gdscript-completion.el:35:1:Error: Symbol’s function definition is void: concatenate
Compiling /home/conao/dev/forks/emacs-gdscript-mode/gdscript-customization.el...
Compiling /home/conao/dev/forks/emacs-gdscript-mode/gdscript-fill-paragraph.el...

In toplevel form:
gdscript-fill-paragraph.el:37:1:Error: Symbol’s function definition is void: concatenate
Compiling /home/conao/dev/forks/emacs-gdscript-mode/gdscript-format.el...
Compiling /home/conao/dev/forks/emacs-gdscript-mode/gdscript-imenu.el...

In gdscript-imenu--get-defun-type-name:
gdscript-imenu.el:64:21:Warning: reference to free variable
    ‘gdscript-nav-beginning-of-defun-regexp’

In end of data:
gdscript-imenu.el:187:1:Warning: the function ‘gdscript-nav-backward-defun’ is
    not known to be defined.
Compiling /home/conao/dev/forks/emacs-gdscript-mode/gdscript-indent-and-nav.el...

In toplevel form:
gdscript-indent-and-nav.el:38:1:Error: Symbol’s function definition is void: concatenate
Compiling /home/conao/dev/forks/emacs-gdscript-mode/gdscript-mode.el...

In toplevel form:
gdscript-mode.el:34:1:Error: Symbol’s function definition is void: concatenate
Compiling /home/conao/dev/forks/emacs-gdscript-mode/gdscript-rx.el...
Compiling /home/conao/dev/forks/emacs-gdscript-mode/gdscript-syntax.el...

In end of data:
gdscript-syntax.el:213:1:Warning: the function ‘concatenate’ is not known to
    be defined.
Compiling /home/conao/dev/forks/emacs-gdscript-mode/gdscript-utils.el...
```

**Comment by NathanLovato** [comment]
Thanks. What do you use to get these warnings? I do run the linter on the code, I byte-compiled every file, and I'm not getting these.

**Comment by purcell** [comment]
@conao3 In order to give consistent feedback to contributors, can I ask that you use @riscy's scripts now that he has published them? https://github.com/riscy/melpazoid

Eventually we'll get these things integrated into the CI workflow.

**Comment by conao3** [comment]
@NathanLovato, Please install [Cask](https://github.com/cask/cask/), and place `Cask` file at the package root directory, do `cask; cask build` in terminal generate former output.

And also `gdscript-mode.el` have below warnings,
```emacs-lisp
 gdscript…    29     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 gdscrip…   148   4 warning         `with-eval-after-load' is for use in configurations, and should rarely be used in packages. (emacs-lisp-package)
```
This is should also solved too.

@purcell, I haven't known @riscy had published his review tool. Thanks for letting me know!

**Comment by NathanLovato** [comment]
Thanks, I just installed docker, I'll try melpazoid a bit later.

> `with-eval-after-load' is for use in configurations, and should rarely be used in packages. (emacs-lisp-package)

This line was recommended to me by Henrik, Doom Emacs' maintainer. He told me that without it, you have no guarantee that the hideshow package will be available at loading time so it's required. If it's a problem, how can I change the code to avoid this potential loading issue?

**Comment by purcell** [comment]
> Built-in packages, like Python, provide support for it. If I get it correctly, we can have support for it but the user should be the one activating the feature in their configuration?

The `with-eval-after-load` was misplaced here because in the mode body, it would be evaluated (for global effect) every time a gdscript buffer is opened.

In this particular case, I think you can simply use `setq-local` in the mode body to locally set `hs-special-modes-alist` to a one-element list containing the config you want.

**Comment by riscy** [comment]
Hi!  Here's the scroll from "melpazoid", fyi.  Feel free to ping with questions.

Before I jump into that -- I feel like `emacs-rx` wants to be a separate package?  Alternatively you could inline its code into gdscript-rx.el or similar and make it a separate package later (as time permits).  The main issue is its prefix (emacs-rx) differs from the rest of the files (gdscript).

I think the biggest issue below is to do with the License, so have a quick look at that.  The compiler warnings are the next biggest.  Checkdoc are less important (and there is some flex -- I think since this package is already in MELPA, we want to get you into a place where you can do maintenance sooner rather than later).

### emacs-rx.el ###

byte-compile and load-file (using Emacs 26.3):
```
emacs-rx.el:240:15:Warning: reference to free variable `regexp-unmatchable'
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
emacs-rx.el:152: Argument `sym' should appear (as SYM) in the doc string
Warning (emacs): 
emacs-rx.el:199: All variables and subroutines might as well have a documentation string
Warning (emacs): 
emacs-rx.el:202: First line is not a complete sentence
Warning (emacs): 
emacs-rx.el:202: Argument `left' should appear (as LEFT) in the doc string
Warning (emacs): 
emacs-rx.el:228: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:258: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:305: First line is not a complete sentence
Warning (emacs): 
emacs-rx.el:320: First line is not a complete sentence
Warning (emacs): 
emacs-rx.el:320: Keycode A-Z embedded in doc string.  Use \\<keymap> & \\[function] instead
Warning (emacs): 
emacs-rx.el:474: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:500: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:617: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:622: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:633: All variables and subroutines might as well have a documentation string
Warning (emacs): 
emacs-rx.el:647: All variables and subroutines might as well have a documentation string
Warning (emacs): 
emacs-rx.el:655: All variables and subroutines might as well have a documentation string
Warning (emacs): 
emacs-rx.el:665: All variables and subroutines might as well have a documentation string
Warning (emacs): 
emacs-rx.el:671: All variables and subroutines might as well have a documentation string
Warning (emacs): 
emacs-rx.el:675: All variables and subroutines might as well have a documentation string
Warning (emacs): 
emacs-rx.el:679: All variables and subroutines might as well have a documentation string
Warning (emacs): 
emacs-rx.el:685: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:702: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:709: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:718: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:741: Argument `negated' should appear (as NEGATED) in the doc string
Warning (emacs): 
emacs-rx.el:810: Argument `negated' should appear (as NEGATED) in the doc string
Warning (emacs): 
emacs-rx.el:829: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:840: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:848: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
emacs-rx.el:886: Argument `form' should appear (as FORM) in the doc string
Warning (emacs): 
emacs-rx.el:963: Argument `op' should appear (as OP) in the doc string
Warning (emacs): 
emacs-rx.el:996: Argument `form' should appear (as FORM) in the doc string
Warning (emacs): 
emacs-rx.el:1151: Open parenthesis in column 0 should be escaped
Warning (emacs): 
emacs-rx.el:1173: Keycode A-Z embedded in doc string.  Use \\<keymap> & \\[function] instead
Warning (emacs): 
emacs-rx.el:1259: Argument `name' should appear (as NAME) in the doc string
Warning (emacs): 
emacs-rx.el:1284: All variables and subroutines might as well have a documentation string
Warning (emacs): 
emacs-rx.el:1290: Open parenthesis in column 0 should be escaped
Warning (emacs): 
emacs-rx.el:1316: Open parenthesis in column 0 should be escaped
Warning (emacs): 
emacs-rx.el:1344: Argument `definition' should appear (as DEFINITION) in the doc string
Warning (emacs): 
emacs-rx.el:1375: First line is not a complete sentence
Warning (emacs): 
emacs-rx.el:503: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:648: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:652: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:661: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:711: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:720: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:743: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:812: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:831: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:837: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:842: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:850: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:883: Messages should start with a capital letter
Warning (emacs): 
emacs-rx.el:1388: Messages should start with a capital letter
```

(Skipping package-lint on this file)


### gdscript-completion.el ###

byte-compile and load-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

(Skipping package-lint on this file)

Experimental static checks/suggestions:
- gdscript-completion.el#L26: Prefer `https` over `http` (if possible)

### gdscript-customization.el ###

byte-compile and load-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

(Skipping package-lint on this file)

Experimental static checks/suggestions:
- gdscript-customization.el#L27: Prefer `https` over `http` (if possible)

### gdscript-fill-paragraph.el ###

byte-compile and load-file (using Emacs 26.3):
```
gdscript-fill-paragraph.el:43:36:Warning: assignment to free variable
    `delimiters-style'
In gdscript-fill-paragraph:
gdscript-fill-paragraph.el:65:16:Warning: reference to free variable
    `gdscript-fill-decorator-function'
gdscript-fill-paragraph.el:80:1:Warning: Unused lexical variable
    `multi-line-p'
In gdscript-fill-paragraph-fill-string:
gdscript-fill-paragraph.el:106:46:Warning: reference to free variable
    `gdscript-fill-triple-string-style'
gdscript-fill-paragraph.el:113:19:Warning: reference to free variable
    `delimiters-style'
In end of data:
gdscript-fill-paragraph.el:169:1:Warning: the function
    `gdscript-info-docstring-p' is not known to be defined.
```

checkdoc (using version 0.6.1):
- No issues!

(Skipping package-lint on this file)

Experimental static checks/suggestions:
- gdscript-fill-paragraph.el#L141: Consider `unless ...` instead of `when (not ...)`
- gdscript-fill-paragraph.el#L143: Consider `unless ...` instead of `when (not ...)`
- gdscript-fill-paragraph.el#L27: Prefer `https` over `http` (if possible)

### gdscript-format.el ###

byte-compile and load-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

(Skipping package-lint on this file)


### gdscript-imenu.el ###

byte-compile and load-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

(Skipping package-lint on this file)


### gdscript-indent-and-nav.el ###

byte-compile and load-file (using Emacs 26.3):
```
gdscript-indent-and-nav.el:339:39:Warning: reference to free variable
    `gdscript-indent-def-block-scale'
```

checkdoc (using version 0.6.1):
- No issues!

(Skipping package-lint on this file)

Experimental static checks/suggestions:
- gdscript-indent-and-nav.el#L617: It's safer to sharp-quote function names; use `#'`
- gdscript-indent-and-nav.el#L638: It's safer to sharp-quote function names; use `#'`
- gdscript-indent-and-nav.el#L205: Consider `unless ...` instead of `when (not ...)`
- gdscript-indent-and-nav.el#L1008: Consider `unless ...` instead of `when (not ...)`

### gdscript-mode.el ###

byte-compile and load-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200226.2001):
- No issues!

Experimental static checks/suggestions:
- gdscript-mode.el#L161: There is no need to quote lambdas (neither #' nor ')

### gdscript-rx.el ###

byte-compile and load-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

(Skipping package-lint on this file)


### gdscript-syntax.el ###

byte-compile and load-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
gdscript-syntax.el:34: First line is not a complete sentence
Warning (emacs): 
gdscript-syntax.el:34: Argument `file-path-relative' should appear (as FILE-PATH-RELATIVE) in the doc string
Warning (emacs): 
gdscript-syntax.el:66: All variables and subroutines might as well have a documentation string
```

(Skipping package-lint on this file)


### gdscript-utils.el ###

byte-compile and load-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

(Skipping package-lint on this file)

### License ###

- Use a LICENSE file that GitHub can detect (e.g. no markup).
  See: https://github.com/licensee/licensee
- Please add a LICENSE or COPYING file to the repository

### Similarly named packages ###

- https://melpa.org/#/gdscript-mode

### Package details ###

```elisp
(gdscript-mode :fetcher github :repo "GDQuest/emacs-gdscript-mode" :files (:defaults "data"))
```
  - Prefer the default recipe, especially for small packages
- Package-Requires: emacs "26.3"
- _elisp/emacs-rx.el (GPL) -- S-exp notation for regexps           -
- _elisp/gdscript-completion.el (GPL) -- Autocompletion for GDScript
- _elisp/gdscript-customization.el (GPL) -- Customizable variables for the GDScript language support
- _elisp/gdscript-fill-paragraph.el (GPL) -- GDScript fill paragraph functions
- _elisp/gdscript-format.el (GPL) -- GDScript formatting with gdformat
- _elisp/gdscript-imenu.el (GPL) -- Imenu support for GDScript
- _elisp/gdscript-indent-and-nav.el (GPL) -- Syntax highlighting for GDScript
- _elisp/gdscript-mode.el (GPL) -- Major mode for Godot's GDScript language
- _elisp/gdscript-rx.el (GPL) -- Regex for GDScript
- _elisp/gdscript-syntax.el (GPL) -- Syntax highlighting for GDScript
- _elisp/gdscript-utils.el (GPL) -- Utility functions for gdscript-mode
- _elisp/data -- directory

**Comment by NathanLovato** [comment]
@riscy Thanks. I see there are some issues I don't get as I'm using Emacs 27. Thanks. 

Sorry for the delay, I hired somebody to give me a hand with the package, as I'm busy with work, but haven't heard of the developer in over a week now.

I'll address the reported issues now. 

Regarding emacs-rx, it's a copy of emacs 27's built-in rx package. It makes it much easier to handle the language's syntax, and python.el is using it starting in emacs 27. The reason it is split into its own package is that we only need to run it in Emacs < 27. But I can merge it with the other package if necessary.

Regarding the emacs-rx checkdoc warnings, do I have to address them? Some of Emacs's built-in lisp packages don't use checkdoc at all, hence the dozens of warnings.

**Comment by NathanLovato** [comment]
The first batch of changes is done. I'm getting errors running melpazoid locally, I guess it's due to my install. Gotta leave it there for now but I'll try to get it working and address the remaining issues ASAP.

**Comment by riscy** [comment]
> Regarding emacs-rx, it's a copy of emacs 27's built-in rx package. It makes it much easier to handle the language's syntax, and python.el is using it starting in emacs 27. The reason it is split into its own package is that we only need to run it in Emacs < 27. But I can merge it with the other package if necessary.

Ah, as in rx.el I assume?  I think the functions are good where they are now (in gdscript-rx.el) but you should probably assign them a gdscript prefix, for example `rx--lookup-def` would become `gdscript-rx--lookup-def`.  This is because if someone _is_ using Emacs 27, you don't want your function definitions overwriting the builtin Emacs ones which may get updated with bugfixes and so forth.

A much nicer solution to the checklist might be [makem.sh](https://github.com/alphapapa/makem.sh) or just running the checks individually.  It should catch many of the same issues.  But if it's any help, I'm checking the package with melpazoid using:
```bash
RECIPE='(gdscript-mode :fetcher github :fetcher github :repo "GDQuest/emacs-gdscript-mode" :repo "AdamBark/gdscript-mode") :files (:defaults "data"))' make
```

I'll be happy to provide you with the latest as we go, here, too --

### gdscript-fill-paragraph.el ###

byte-compile-file (using Emacs 26.3):
```
gdscript-completion.el:35:1:Error: Opening input file: No such file or directory, /workspace/_elisp/keywords.txt
```
This looks like merely byte-compiling the file is trying to read in a text file that may not exist?

### gdscript-imenu.el ###

byte-compile-file (using Emacs 26.3):
```
gdscript-imenu.el:64:21:Warning: reference to free variable
    `gdscript-nav-beginning-of-defun-regexp'
In end of data:
gdscript-imenu.el:187:1:Warning: the function `gdscript-nav-backward-defun' is
    not known to be defined.
```

### gdscript-indent-and-nav.el ###

byte-compile-file (using Emacs 26.3):
```
gdscript-indent-and-nav.el:39:1:Error: Opening input file: No such file or directory, /workspace/_elisp/keywords.txt
```
(Similar to above)

Experimental static checks/suggestions:
- gdscript-indent-and-nav.el#L618: It's safer to sharp-quote function names; use `#'`
- gdscript-indent-and-nav.el#L639: It's safer to sharp-quote function names; use `#'`
- gdscript-indent-and-nav.el#L206: Consider `unless ...` instead of `when (not ...)`
- gdscript-indent-and-nav.el#L1008: Consider `unless ...` instead of `when (not ...)`

### gdscript-mode.el ###

byte-compile-file (using Emacs 26.3):
```
gdscript-mode.el:34:1:Error: Opening input file: No such file or directory, /workspace/_elisp/keywords.txt
```

Experimental static checks/suggestions:
- gdscript-mode.el#L161: There is no need to quote lambdas (neither #' nor ')
- gdscript-mode.el#L3: Did you really do the paperwork to assign your copyright?

### gdscript-utils.el ###

byte-compile-file (using Emacs 26.3):
```
gdscript-utils.el:94:1:Warning: the function `gdscript-syntax-context' is not
    known to be defined.
```

One other thing I'm noticing is e.g.
- gdscript-utils.el#L3: Did you really do the paperwork to assign your copyright?

Some people copy/paste the copyright line and may not be aware that some paperwork needs to be done to assign this copyright to the FSF.  If that's been done, ignore me on this one.

**Comment by NathanLovato** [comment]
> A much nicer solution to the checklist might be makem.sh or just running the checks individually.

Thanks. The reason melpazoid isn't working for me is I think it's not compatible with Emacs 27, which is what my `emacs` bin points to by default, although I also have 26.3 installed through apt. May you know how to override a program on the PATH just for one program or shell session?

> Did you really do the paperwork to assign your copyright?
> Some people copy/paste the copyright line and may not be aware that some paperwork needs to be done to assign this copyright to the FSF. If that's been done, ignore me on this one.

I didn't know that, thanks. No, it's just that I copied code from the FSF and modified it, so I thought that as you sometimes do with the GPL license, I had to mention the original author.

> gdscript-fill-paragraph.el
> This looks like merely byte-compiling the file is trying to read in a text file that may not exist?

This should come from the eval-when-compile that's caching a list of keywords and built-in functions for syntax highlighting. It works when installing the package through package-el and others (I use it for production work here already), but I'm not sure why it's giving this error. In `gdscript-syntax.el` I'm even getting an error that this function is not defined:

```elisp
(defun gdscript--get-file-content-as-string (file-path-relative)
  "Return the content of a file in this package as a list of strings.
FILE-PATH-RELATIVE is the path of the data file to parse relative
to this package. Used to retrieve lists of keywords for syntax
highlighting.

If the file isn't available, the function tries to access the
file without the directory path. This is for compatibility with
the Doom Emacs distribution, which flattens the package's
structure."
  (with-temp-buffer
    (let (this-directory requested-path file-path)
      (setq this-directory (file-name-directory (or load-file-name buffer-file-name)))
      (setq requested-path (concat this-directory file-path-relative))
      (setq file-path (if (file-readable-p requested-path)
                          requested-path
                        (concat this-directory
                                (file-name-nondirectory file-path-relative))))
      (insert-file-contents file-path)
      (split-string (buffer-string)
                    "\n"
                    t))))
```

It's called like that, to cache the keywords to an elisp string:

```elisp
(defconst gdscript-keywords (eval-when-compile (gdscript--get-file-content-as-string "data/keywords.txt")))
...
```

Would you have an idea of where the issue comes from? It didn't give me errors a few weeks ago, and I don't remember modifying it. I'll have to investigate.

**Comment by NathanLovato** [comment]
I set up makem.sh, addressed some more issues, but the one above is bogging me right now. I lack experience with elisp, so any pointers would be welcome. With `eval-when-compile`, the function `gdscript--get-file-content-as-string` appears to be undefined, although it's defined right before the call.

At install time though, despite the error, the files do get parsed and the variable's values compiled, so I don't get why it's happening.

**Comment by purcell** [comment]
`gdscript-rx.el` still seems to overwrite the existing definition of the `rx` pcase matcher, [from what I can tell](https://github.com/GDQuest/emacs-gdscript-mode/blob/beb278d10fcd11336c449cbb973004fa89f6fd2a/gdscript-rx.el#L1414).

**Comment by NathanLovato** [comment]
Thanks @purcell! I had missed that one.

I addressed the remaining compile-lint errors, and removed the function above that was causing trouble: anyway, it didn't play nice with some configs. Now the package should work with the default melpa recipe, I'll update the PR straight away.

**Comment by NathanLovato** [comment]
I tested and updated the recipe to use the default one now I removed data/ files from the project.

**Comment by riscy** [comment]
This is getting quite close -- a couple I'll point out:

package-lint-current-buffer (using version 20200313.2338):
```
1 issue found:
1162:0: error: "rx" doesn't start with package's prefix
```
(I think this would clobber the user's existing `rx` macro)

And this small file:
- gdscript-keywords.el has no detectable license boilerplate

**Comment by riscy** [comment]
I think after those two, this is good to replace.

**Comment by NathanLovato** [comment]
I just addressed these two, thanks for pointing them out.

I wonder why I wasn't getting the first one, package-lint usually tells me when functions or macros don't use the package's name.

Anyway, hopefully we're getting there. 🙂

**Comment by NathanLovato** [comment]
I just addressed these two, thanks for pointing them out.

I wonder why I wasn't getting the first one, package-lint usually tells me when functions or macros don't use the package's name.

Anyway, hopefully we're getting there. 🙂

**Comment by riscy** [comment]
I missed one, sorry about that --

```
35:0: error: "regex-maker" doesn't start with package's prefix
```
in gdscript-syntax.el

**Comment by NathanLovato** [comment]
Just fixed this. It's also my bad, I have to clean up my setup so I get these linter reports.

**Comment by purcell** [comment]
Looking good, merged now - welcome to MELPA! :tada:

**Comment by NathanLovato** [comment]
Thank you very much for your time guys :)

**Pull request merged**
