### PR TITLE
Add package jest-test-mode

### PR DESCRIPTION
**Pull request by rymndhng**
### Brief summary of what the package does

This packages adds a mode for executing jest-tests. The design is inspired by ruby-test-mode and cider-test. 

It differs from an existing package named `jest`, specifically the way menus are presented to users. `jest-test-mode` also does not rely on any other packages.

### Direct link to the package repository

https://github.com/rymndhng/jest-test-mode

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

n/a

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```diff
new file   Cask
@@ -0,0 +1,4 @@
+(source gnu)
+(source melpa)
+
+(package-file "jest-test-mode.el")
```
```shell
$ cask; cask build
Loading package information... done
Package operations: 1 installs, 0 removals
  - Installing [ 1/1] emacs (25.1)... already present
Compiling /home/conao/dev/forks/jest-test-mode/jest-test-mode.el...

In jest-test-rerun-test:
jest-test-mode.el:120:28:Warning: reference to free variable
    ‘jest-test-last-test-command’

In jest-test-example-at-point:
jest-test-mode.el:152:8:Warning: ‘(example (match-string 1 text))’ is a
    malformed function
jest-test-mode.el:158:19:Warning: reference to free variable ‘example’
jest-test-mode.el:190:15:Warning: reference to free variable
    ‘compilation-error-regexp-alist’
jest-test-mode.el:190:15:Warning: assignment to free variable
    ‘compilation-error-regexp-alist’
jest-test-mode.el:191:15:Warning: reference to free variable
    ‘compilation-error-regexp-alist-alist’
jest-test-mode.el:191:15:Warning: assignment to free variable
    ‘compilation-error-regexp-alist-alist’

In end of data:
jest-test-mode.el:203:1:Warning: the function ‘when-let’ is not known to be
    defined.
```

**Comment by rymndhng** [comment]
@conao3 Thanks for the feedback! I'm new to emacs packaging 🙇‍♀️. 

I think I've corrected the issues now in my local sandbox, can you give it another try?

Note: I wasn't able to reproduce these errors below and put a best guess at fixing the issue.

```
jest-test-mode.el:190:15:Warning: reference to free variable
    ‘compilation-error-regexp-alist’
jest-test-mode.el:190:15:Warning: assignment to free variable
    ‘compilation-error-regexp-alist’
jest-test-mode.el:191:15:Warning: reference to free variable
    ‘compilation-error-regexp-alist-alist’
jest-test-mode.el:191:15:Warning: assignment to free variable
    ‘compilation-error-regexp-alist-alist’
```

**Comment by alphapapa** [comment]
@rymndhng You can use this to easily test and lint in a local sandbox: https://github.com/alphapapa/makem.sh

**Comment by rymndhng** [comment]
@alphapapa thanks for the tip! I've setup a GitHub action for it 😁

**Comment by riscy** [comment]
I think you can remove these lines:
```elisp
(add-hook 'typescript-mode-hook 'jest-test-enable)
(add-hook 'js-mode-hook 'jest-test-enable)
```
and define a globalized-minor mode that tests for those two modes, e.g.:
```elisp
;;;###autoload
(define globalized-minor-mode jest-test-global-mode jest-test-mode jest-test--global-on :require 'jest-test-mode)

(defun jest-test--global-on ()
    ;;; ONLY turn jest-test-mode on if this is a typescript or js-mode buffer
  (when (or (eq major-mode 'typescript-mode) (eq major-mode 'js-mode))
    (jest-test-mode 1))))))))
```

I think you need to `(require 'seq)` for `seq-concatenate`, and also add the GPL boilerplate above the `;;; Commentary` section of your file.

Experimental static checks/suggestions:
- jest-test-mode.el#L195: It's safer to sharp-quote function names; use `#'`
- jest-test-mode.el#L196: It's safer to sharp-quote function names; use `#'`
- jest-test-mode.el#L212: It's safer to sharp-quote function names; use `#'`
- jest-test-mode.el#L213: It's safer to sharp-quote function names; use `#'`

**Comment by rymndhng** [comment]
Thank you for the feedback @riscy. 

I got a bit lost trying to figure out how I should be setting up my package with `define-globalized-minor-mode`, and I hope you can help me clarify two things:


Is `define-globalized-minor-mode` preferred in the package because it provides more flexibility on how the package could be consumed? i.e. someone can choose to either:

- use the global toggle `(jest-test-global-mode)`
- use `add-hook` if they desire to (manually)


--- 
In `define-globalized-minor-mode`, I have not been able to figure out what `:require 'jest-test-mode`. I took a peek at some other PRS with similar recomendations (see https://github.com/melpa/melpa/pull/6239) and those packages do not have a `:require` key defined. From reading the docs of `defcustom`, I'm not certain why this should be set.

```
:require
	VALUE should be a feature symbol.  If you save a value
	for this option, then when your init file loads the value,
	it does (require VALUE) first.
```

**Comment by riscy** [comment]
> Is define-globalized-minor-mode preferred in the package because it provides more flexibility on how the package could be consumed?

Yeah, exactly.  The fewer packages out there that are automatically adding hooks, advising other functions, redefining functions, etc. merely when they are loaded, the better.  It's not uncommon these days for an Emacs config to make use of hundreds of packages.

The `:require` I believe means that, if your .emacs or equivalent sets that option, then `(require 'jest-test-mode)` will be automatically executed, which will ensure that the `define-globalized-minor-mode` line is executed.  I believe you can also just add an `;;;###autoload` cookie above the declaration.

**Comment by riscy** [comment]
One thing I'm also noticing (maybe this is new) is that your elisp file is missing some license boilerplate above the `;;; Commentary` section -- consider adding that, or even an [SPDX license line](https://spdx.org/licenses/)

**Comment by rymndhng** [comment]
@riscy thanks for following up!

All the improvements are currently on a branch/PR: https://github.com/rymndhng/jest-test-mode/pull/4

I need a bit more time to play around `define-globalized-minor-mode` and to write some configuration docs in README.org before I'm ready to merge the changes to master.

**Comment by rymndhng** [comment]
Alright, the master branch is updated now.

**Comment by purcell** [comment]
This looks great now, and I'll go ahead and merge it.

FWIW, I would recommend you scrap the globalised minor mode machinery. If new javascript modes come along, you'd have to change this file, which is nonsense. Instead, just do the conventional thing: tell people to add your minor mode to their major mode hooks or to add it to their `.dir-locals.el` on a per-project basis.

(Also, mode checks with eq like [this](https://github.com/rymndhng/jest-test-mode/blob/829cfa3b82d88bc1c18617196d47567c9fe0c057/jest-test-mode.el#L236) are generally a code smell: at the very least they should use `derived-mode-p`, to handle derived modes.)

Anyhow, thanks for your patience, and welcome to MELPA! :tada:

**Comment by rymndhng** [comment]
Hurray! 🎉

I've found the overall process of contributing to `melpa` refreshingly helpful. I have really appreciated the feedback as someone new to creating an emacs package.

**Comment by purcell** [comment]
Great, happy it's been helpful for you. We figure that if we help authors learn the right ways to do things, there'll be more good code out there for everyone to read and adapt.

**Pull request merged**
