### PR TITLE
Add recipe for svgo

### PR DESCRIPTION
**Pull request by hupf**
### Brief summary of what the package does

This package uses the Node utility [SVGO](https://github.com/svg/svgo) to optimize SVG files. It provides a command and an optional minor mode to reduce the size of the SVG contents in the current Emacs buffer.

### Direct link to the package repository

https://github.com/hupf/svgo.el/

### Your association with the package

I'm the author of the package.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Quick first pass --

This block:
```
;;; Author: Mathis Hofer <mathis@fsfe.org>
;;; Version: 1.0.0
;;; Package-Requires: ((emacs "26.2"))
;;; Keywords: tools
;;; URL: https://github.com/hupf/svgo.el/
```
should appear at the top of the file, probably even above your license boilerplate.  Where it currently is, it's going to interfere with `;;; Commentary` detection (see `(lm-commentary)` and notice how it includes this block).  Moving this up should also cause the one checkdoc lint to disappear.

Rather than `svgo--shell-which` could the Emacs builtin `executable-find` ?

**Comment by hupf** [comment]
@riscy Thanks very much for your feedback.

> should appear at the top of the file, probably even above your license boilerplate. Where it currently is, it's going to interfere with ;;; Commentary detection (see (lm-commentary) and notice how it includes this block). Moving this up should also cause the one checkdoc lint to disappear.

Sorry for this, I've now moved the section above the license header as you suggested. Interestingly, `M-x checkdoc` did not report any issues and also `(lm-commentary "./svgo.el")` returned the correct contents both with Emacs 29 and 27. Maybe I was doing something wrong?

> Rather than svgo--shell-which could the Emacs builtin executable-find ?

Good point, I've replaced it with `executable-find`. I guess one has to use something like Steve Purcell's `exec-path-from-shell` anyway to get it working in an Emacs session started via launcher icon.

The changes are pushed and tagged.

**Comment by riscy** [comment]
Thanks!

>  I guess one has to use something like Steve Purcell's exec-path-from-shell anyway to get it working in an Emacs session started via launcher icon.

Ahh, I see why you were doing that.  It's a tradeoff, but I dimly remembering hearing about one Linux distribution or another planning to deprecate `/usr/bin/which` in favor of `command -v` -- so you can avoid that risk entirely this way.

`;;; Commentary:` correctly starts with three semicolons, but the blocks underneath typically don't, e.g. you should write:

```elisp
;;; Commentary:

;; This package uses the Node utility SVGO to optimize SVG files.  It
;; provides a command and an optional minor mode to reduce the size
;; of the SVG contents in the current Emacs buffer.
...
```
The triple semicolons are for header sections, and there's some small differences in how `(lm-commentary)` parses lines with triple semicolons (it could mistake some lines as titles and cause the section to break).

And now I notice this block:
```elisp
;;; Author: Mathis Hofer <mathis@fsfe.org>
;;; Version: 1.0.1
;;; Package-Requires: ((emacs "26.2"))
;;; Keywords: tools
;;; URL: https://github.com/hupf/svgo.el/
```
should typically only have two semicolons before each line.  I don't know if this will affect anything, but anything nonconventional carries a risk.  When in doubt, check out how other popular packages are doing things.

With that stuff mostly behind us I took another look at the code.  This is not a blocker, but I think the introduction of the minor mode to support a single keybinding is overkill unless you have future plans to expand.  It's just as much configuration overhead (at this point, anyway) for a user to set up the keybinding themselves in their config, rather than activate a mode, and it makes customization of that keybindings much more straightforward.

I'm also leery of Emacs packages that try to handle installing dependencies, especially from places like npm.  I can see you're installing `svgo` globally and without a prefix, which I think carries the risk of version conflicts with whatever the user currently has installed.  This isn't a blocker either, but I'd recommend just telling users to install svgo themselves, and then you don't have to maintain `svgo--ensure` and all of the various installation edge-cases that might pop up going into the future.

**Comment by hupf** [comment]
Thanks for pointing out all those points!

> The triple semicolons are for header sections, and there's some small differences in how (lm-commentary) parses lines with triple semicolons (it could mistake some lines as titles and cause the section to break).

Sorry for overlooking this. I've removed the triple semicolons where they shouldn't be.

>  This is not a blocker, but I think the introduction of the minor mode to support a single keybinding is overkill unless you have future plans to expand.

You're absolutely right. It was just me wanting to write an Emacs mode ;-) – and it's so easy and cool. I've now removed the minor mode and updated the documentation.

> I'm also leery of Emacs packages that try to handle installing dependencies, especially from places like npm.

If you don't mind, I'd like to keep the installation feature. I personally like the comfort of Emacs handling the installation for me – just like e.g. lsp-mode does it with the language servers. And I hope by having the ability to say "no" and install it manually, this isn't too obtrusive. The message now also mentions that the package is installed globally.

All the changes are pushed and tagged...

**Comment by riscy** [comment]
> If you don't mind, I'd like to keep the installation feature.

Okay, I went ahead and took a closer look at that installation feature in that case to comb.  Some feedback on that code:

- Here's one of the aforementioned edge cases: The function `svgo--ensure` appears designed to return nil/non-nil depending on whether svgo is installed, but if npm isn't installed then `(message "No `svgo' command found and `npm' is not present")` triggers; but `message` will give you a non-nil return value so you should verify that you're returning nil when you want to
- Why not use `yes-or-no-p` for `svgo--prompt-install` (I recommend this over e.g. `y-or-n-p` so that the user actually has to explicitly type `yes` to prevent oopsies)

**Comment by hupf** [comment]
> `message` will give you a non-nil return value so you should verify that you're returning nil

Good point, I've fixed the return value for this case.

> Why not use `yes-or-no-p` for `svgo--prompt-install`

Oh absolutely, I've replaced the custom function with `yes-or-no-p`.

Thank you so much for your high quality review! 🙏 

The changes are again pushed & tagged.

**Comment by riscy** [comment]
Great, thanks for accommodating.  And, welcome to MELPA. :)

**Pull request merged**
