### PR TITLE
Add recipe for arduino-cli-mode

### PR DESCRIPTION
**Pull request by motform**
### Brief summary of what the package does

`arduino-cli-mode` is an Emacs minor mode for using the excellent new [arduino command line interface](https://github.com/arduino/arduino-cli) in an Emacs-native fashion. The mode covers the full range of `arduino-cli` features in an Emacs native fashion. It even leverages the infinite power the GNU to provide fussy-finding of libraries and much improved support for handling multiple boards. The commands that originally require multiple steps (such as first searching for a library and then separately installing it) have been folded into one.

### Direct link to the package repository

https://github.com/motform/arduino-cli-mode

### Your association with the package

I am the maintainer and creator of the package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by motform** [comment]
Am I correct in understanding that the build fails because I require functions from Emacs 25.1? Is there any way I can add a requirement or somehow work around this?

**Comment by riscy** [comment]
Nah, currently our travis build is sensitive to the commit range.

The main thing I see is that your file should be named `arduino-cli-mode.el` to match the package name.  Or you could name the package `arduino-cli` and leave the filename alone.  

Someone'll take a closer look in the next little while, but a couple other quick notes while I'm here:
- arduino-cli.el#L206: There is no need to quote lambdas (neither #' nor ')
- arduino-cli.el#L126: Consider `unless ...` instead of `when (not ...)`

**Comment by motform** [comment]
Thank you for the feedback! I have updated the package name and amended your corrections. Checks are still failing though, but is that only because of the commit-range-thing?

**Comment by riscy** [comment]
> should I re-submit the pull-request?

No need.  As far as I'm aware there's some small flakiness with the CI right now.  All of the checks look good on my end.

Minor, but non-blocking:
- mesesage -> message
- quitet -> quiet
- it is an Arduino -> if it is an Arduino

...and, welcome to MELPA. :)

**Pull request merged**
