### PR TITLE
Add recipe for emacs material candy theme

### PR DESCRIPTION
**Pull request by shaneikennedy**
### Brief summary of what the package does

Emacs port of material-candy theme by [millsp](https://github.com/millsp/material-candy)

### Direct link to the package repository

https://github.com/shaneikennedy/emacs-material-candy

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

### material-candy.el ###

byte-compile (using Emacs 26.3):
- material-candy.el#L728: Don't set `no-byte-compile: t`.
  Byte-compiling is enabled in what follows
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
material-candy.el:708:29:Warning: reference to free variable `color-names'
```
I think this pops up because lexical binding was enabled (by me), but you should be aware that lexical binding is the default in Emacs 27.1.

checkdoc (using version 0.6.1):
```
Warning (emacs): 
material-candy.el:732: The footer should be: (provide 'material-candy)\n;;; material-candy.el ends here
```

package-lint (using version 20200419.406):
```
1 issue found:
1:0: error: There is no (provide 'material-candy-theme) form.
```
Along these lines, you have to change the first line of the file from `material-candy-theme.el --- Material-Candy Theme` to `material-candy.el ...` since that's the correct filename.  Then you can make your footer:
```elisp
(provide-theme 'material-candy)
;; Local Variables:
;; no-byte-compile: t
;; indent-tabs-mode: nil
;; End:

(provide 'material-candy)
;;; material-candy.el ends here
```
which is technically a tiny bit redundant (provide-theme will also provide) but will silence all of the checks.

### Loadability ###

Verifying ability to #'load each file:
```
Loading material-candy.el
Done.
```

You have `Code licensed under the MIT license` in your file, but a GPL license in your repository.  As for the license line in your file (whichever you end up choosing) I would recommend something slightly more formal like an [SPDX-License-Identifier](https://spdx.org/using-spdx-license-identifier).

Thanks!  It looks like a cool theme.

**Comment by shaneikennedy** [comment]
Thanks @riscy , all of your comments have been addressed! Let me know if there's anything else I can do here 👍

**Comment by riscy** [comment]
Apologies for the wait - I'm removing the awaiting label so I see this next time through.

**Comment by riscy** [comment]
Here's the latest -- looks like I'm currently unable to load the file:

### material-candy.el ###

byte-compile (using Emacs 27.1):
```
material-candy.el:75:1:Warning: Unused lexical variable `tty-colors'
material-candy.el:75:1:Warning: Unused lexical variable `term-colors'
material-candy.el:75:1:Warning: Unused lexical variable `graphic-colors'
material-candy.el:75:1:Warning: Unused lexical variable `color-names'
material-candy.el:708:29:Warning: reference to free variable `color-names'
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200901.2204):
```
1 issue found:
9:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```
Minor; adding the "faces" keyword fixes this.

### Loadability ###

Verifying ability to #'load each file:
```
Loading material-candy.el
material-candy.el:Error: Emacs 27.1 errored during load
Done.
```
I think this load error traces back to the byte-compile warnings.  That `apply` block looks quite hefty.

**Comment by shaneikennedy** [comment]
🤦 I unfortunately don't have the time for this anymore, sorry for the back and forth. Closing 👍

**Pull request closed without merging**
