### PR TITLE
Add titlecase.el

### PR DESCRIPTION
**Pull request by duckwork**
### Brief summary of what the package does

Titlecase.el provides facilities for capitalizing titles using a variety of styles in Emacs. It aims to be comprehensive and as accurate as possible given computer constraints and language complexity.

### Direct link to the package repository

<https://github.com/duckwork/titlecase.el>

### Your association with the package

I am the creator and maintainer of this package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback **NOTE that titlecase-data.el makes package-lint angry, but mostly due to naming issues; please let me know if I need to change the variables in titlecase-data.el to titlecase-data-*.**
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by ideasman42** [comment]
Re-lint shows a warning.

```
titlecase.el:77:52: In titlecase-force-cap-after-punc: Duplicated ‘\’ inside character alternative (pos 7)
  "[.?!\\/;\\:\n\r]"
   ........^
relint: 1 error.
```

**Comment by duckwork** [comment]
Are either of those backslashes needed? With my (admittedly minimal) testing, `[.?!\\/;:\n\r]` gives the same result.

**Comment by ideasman42** [comment]
Don't think so, also me-culpa for adding this (it worked but I didn't run the regex through re-lint), so if it works when removed - it should be fine to do so.

**Comment by duckwork** [comment]
No worries, thanks @ideasman42 ! I'll remove that then.

**Comment by riscy** [comment]
Thanks for this -- very solid package -- and for your close adherence to the checklist.

It looks like there already is a `titlecase` package out there somewhere -- you can find it here: https://github.com/emacsmirror/emacswiki.org/blob/master/titlecase.el.  Your package is clearly far more full featured and deserving of this canonical-sounding name, but it may be easier to rename your package before indexing it.

But just in case, I will ping @tarsius for his thoughts on whether it's ever a good idea to rename trivial packages mirrored from Emacswiki?

**Comment by ideasman42** [comment]
Since the packages are so similar, it might makes sense to point to this new package?

`titlecase` is a fairly generic name - when it in fact wraps a perl script the user needs to know to install - which isn't all that convenient.

Checking the perl script, it's not all that advanced - similar to `upcase-initials-region` which ignores some words like `of`.
Although it does have special handling for URL's which this package doesn't have (could be supported I suppose but not sure it's necessary). For reference: https://github.com/ap/titlecase/blob/master/titlecase

**Comment by duckwork** [comment]
Although this doesn't really help the naming thing, I could also include a `titlecase-external-command` functionality into duckwork/titlecase.el, just in case something better comes along (or so I don't break anyone's workflow!). I've been thinking about a `titlecase-api` thing, so refactoring the user-facing functions to use a `titlecase-command` could be a good idea anyway.

For the name: sorry I didn't check for a `titlecase` package before! I do agree that our implementation is more full-featured than the previous package, and would appreciate the canonical name. However, if we do need to change the name I absolutely understand as well. Suggestions?

Wikipedia's page on titlecase has this sentence:

> In text processing, title case usually involves the capitalization of all words irrespective of their part of speech. This simplified variant of title case is also known as start case or initial caps. 

Perhaps also `title-caps`, or `titlize` ? These aren't ideal IMO.

**Comment by tarsius** [comment]
> But just in case, I will ping @tarsius for his thoughts on whether it's ever a good idea to rename trivial packages mirrored from Emacswiki?

That question seems strange to me. Did you mean: Is it ever a good idea to claim a name already in use by an older implementation?

To that my answer is yes, and this is a good example for when doing that makes sense.

In this case it is because this is really editor functionality that ought to be implemented in the editors extension language -- wouldn't it be strange if `upcase-dwim` and such were implemented in Perl? Nothing at all against the old implementation: the author needed that functionality and implemented it in a straight forward way and even went one step further and made it available to others. Its author should still be asked for their opinion and the new algorithm should be as good as the Perl one before the name is claimed.

**Comment by duckwork** [comment]
So what are next steps? I'll reach out to Jason Blevins for his thoughts on this issue, but in the meantime is there anything else I can do?

**Comment by tarsius** [comment]
You could write tests to compare the two implementations.

After checking whether its license would allow you to lift code into your implementation you could also start studying the Perl implementation.

**Comment by jrblevin** [comment]
It’s fine with me to cede the `titlecase` name. My old titlecase.el was just a one-and-done wrapper for Gruber’s script (https://jblevins.org/log/titlecase), not something I planned on turning into anything bigger. I posted it to my website, then it made its way to the EmacsWiki and then to MELPA by way of others.

I’m glad to see someone taking up the idea and implementing it in elisp. I have not compared the implementations, but I assume it is of similar quality?

If so, then the remaining issue would be keeping compatibility for people who have downloaded and configured the old library. Not much of a burden there as mine just exposed three user functions. There was no configuration other than the path to the script, which would be moot now unless people might still want to use it for some reason.

**Comment by duckwork** [comment]
I've now refactored duckwork/titlecase.el to enable the choice of `titlecase-command`, which can take a function (default: our implementation in Elisp), a string, or a list of strings. This should enable those users of Jason's package to nearly seamlessly transition to this one: they'll only have to set `titlecase-command` if they haven't changed it from the default.

**Comment by riscy** [comment]
> If so, then the remaining issue would be keeping compatibility for people who have downloaded and configured the old library.

Maybe @duckwork could add a load-time check to see whether any of the functions from the previous package are defined, and raising a warning if so?  That may be a bit much, but I think it's a reasonable way to acknowledge the existence of the previous package and help users recover.

I think we're safe to merge at least for now -- but let me know if I've missed something.

**Comment by duckwork** [comment]
That sounds like a good compromise, I can do that.

**Pull request merged**
