### PR TITLE
point arduino-mode to a new fork

### PR DESCRIPTION
**Pull request by stardiviner**
original repo is dead.

### CODE REVIEW

**Comment by tarsius** [comment]
Please provide more information. Did you talk to the old maintainer? Etc.

**Comment by stardiviner** [comment]
I used to send email to the author, but no response. yesterday I asked in #emacs IRC channel, said might take a try. But I still send a new email to the author. Said I want to maintain this `arduino-mode`. Hope get response soon.

**Comment by DamienCassou** [comment]
Any news?

**Comment by stardiviner** [comment]
Honestly, I have got his permit. I guess he is busy, and have not updated README yet. If I need to make this PR merged, I guess I need prove. So here is the email screenshot. I don't know whether this should.
image

**Comment by stardiviner** [comment]
@tarsius Do I need to contact the `arduino-mode` maintainer again? Does that email screenshot count?

**Comment by purcell** [comment]
Thanks @stardiviner

**Pull request merged**
