### PR TITLE
Add wallpreview recipe

### PR DESCRIPTION
**Pull request by nryotaro**
### Brief summary of what the package does

Preview and set wallpapers in image-dired.

### Direct link to the package repository

https://github.com/nryotaro/wallpreview

### Your association with the package

I'm the author of the package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  I strongly suggest not having the mode add hooks into anything when it loads, and usually push back when packages try to do this.   So, instead of `(add-hook 'image-dired-thumbnail-mode-hook #'wallpreview--bind-toggle-key)`, maybe it would make sense to implement a very simple minor mode that captured this `add-hook` as well as a `remove-hook` when the mode is toggled off again.

Sometimes I take a quick look for typos in docstrings too, and here are a couple easy ones:
- adivce -> advice
- forcused -> focused
- wallpreivew -> wallpreview

**Comment by riscy** [comment]
Also thank you for your close adherence to all the checklist items.

**Comment by nryotaro** [comment]
Thank you for your feedback.
I fixed the typos and created a minor-mode to avoid calling add-hook when it loads.

**Comment by riscy** [comment]
Thanks, this looks good to merge.  Some minor things I'm catching on this pass, but non-blocking:

- `(message "wallpreview is on.")` (or off) -- these messages are unnecessary since when you toggle the mode on Emacs will will already message "xxx mode enabled|disabled in current buffer"
- Inside the definition of the minor mode, `progn` is unnecessary in the else part of an `if` block, but that's small potatoes
- A variable like `wallpreview--on` shouldn't need to exist -- when you define the minor mode, it will also create a variable called `wallpreview-mode`

**Pull request merged**
