### PR TITLE
Added morgentau-theme

### PR DESCRIPTION
**Pull request by Melchizedek6809**
### Brief summary of what the package does

A simple, dark theme for Emacs.

### Direct link to the package repository

https://github.com/Melchizedek6809/morgentau-theme

### Your association with the package

My personal theme i've been using/customizing for over a year.

### Relevant communications with the upstream package maintainer

I guess **None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This should be a quick merge, and I can see the license is listed in the file, but it may be more formal/machine-detectable to add an [SPDX-License-Identifier](https://spdx.dev/ids/) to morgentau-theme.el instead of what you've got.  Not a blocker though -- welcome to MELPA. :)

**Comment by Melchizedek6809** [comment]
Ah yeah, a SPDX Identifier would be better, fixed that just now. Thank you for noticing :)

**Comment by Compro-Prasad** [comment]
@Melchizedek6809 Website/Homepage link is invalid.

**Comment by Melchizedek6809** [comment]
@Compro-Prasad Thank you for noticing, fixed it just now.

**Pull request merged**
