### PR TITLE
Add sailfish-scratchbox recipe

### PR DESCRIPTION
**Pull request by vityafx**
This recipe provides an easy way to interact with the sailfish sdk from inside the emacs.

### Direct link to the package repository

https://github.com/vityafx/sailfish-scratchbox.el

### Your association with the package

I am the maintainer of this project.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [ ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by tarsius** [comment]
Could you please rebase this onto `master` and then force push? (You branched of `master` during the approximately 10 minutes when it had the bug that causes Travis to fail.)

**Comment by vityafx** [comment]
Yes, of course.

**Comment by vityafx** [comment]
@tarsius I don't quite understand where this error comes from? What it was unable to load?

**Comment by tarsius** [comment]
There was a second related issue, that's fixed too now. Please do the rebase dance again.

**Comment by tarsius** [comment]
Hm....

**Comment by tarsius** [comment]
I am going to push some additional commits onto this branch for testing purposes. I'll remove that again when I am done.

**Comment by tarsius** [comment]
I have pushed another fix to `master` and rebase your branch onto that.

**Comment by tarsius** [comment]
And now for something completely different:

* Please release the package under "GPL v3 or later" by using the standard permission statement (which you can copy from a built-in library). Only packages that are released under a license that is compatible with that of Emacs can be added to Melpa.
* Don't put closing parentheses on their own lines.

**Comment by vityafx** [comment]
@tarsius May I license it under apache 2 license? It is GPL compatible as I can see.

**Comment by tarsius** [comment]
Yes, that is okay too. Please put the respective permission statement and also add the line `;; License: Apache-2.0`.

**Comment by vityafx** [comment]
Done. Check it again please.

**Comment by tarsius** [comment]
Oh, I didn't see the license file before. MIT is also okay.

**Comment by vityafx** [comment]
@tarsius cmon! I wanted it to be MIT... So I am moving it back to MIT, lol.

**Comment by tarsius** [comment]
I would just have reverted the commit to avoid a license flip-flop so early in a projects history. (Of course that also teaches the importance of atomic commits. "Change license & move paretheses from their own lines" does two completely unrelated things, which makes reverting just one of them harder.)

> Review please.

I can confirm that this uses a valid license and that the closing parentheses are no longer on separate lines :wink: Steve might have some other suggestions also.

**Comment by vityafx** [comment]
@tarsius lol. Yes, you are right about atomic commits and so on :) I will do this now.

**Comment by vityafx** [comment]
@tarsius I have rewritten the history by pushing commits with `force`. Their are atomic now and there is not move to `Apache2` license in the history. Is there anything else I need to do?

**Comment by tarsius** [comment]
Looks good to me now (and the license already was good before :roll_eyes:) but Steve might have additional suggestions.

**Comment by vityafx** [comment]
@tarsius okay, thank you for spending time reviewing my code anyway.

**Comment by purcell** [comment]
Basically looks good, but you're manually quoting command arguments with `concat` and `'`, so I suspect there are various things that might explode if the interpolated values contain spaces, backslashes, quotes etc: use `shell-quote-argument` instead. Should be ready to merge when that's fixed. :-)

**Comment by vityafx** [comment]
@purcell Could you suggest me doing anything else please? The reason I did that is because the `sdk` is usually an alias to the script which runs scratchbox. According to the manual of Sailfish HADK it must be set in the `~/.profile` but emacs's internal `shell-command` function does not read it and simply can't found the alias. I googled and found that solution which you saw. I'd do this better if I knew.

**Comment by vityafx** [comment]
@purcell I have done what you have advised to me. However, is this the only way to execute a shell command which reads the `.profile`/`.bashrc` files before running anything?

**Comment by purcell** [comment]
Merged now! Thanks, and welcome to MELPA!

**Comment by purcell** [comment]
> However, is this the only way to execute a shell command which reads the .profile/.bashrc files before running anything?

Yes, you probably need the `-i` flag for `bash` to guarantee that certain startup files will be read. There isn't an easier way afaik.

**Comment by vityafx** [comment]
@purcell okay :) thank you for everything very much!

**Pull request merged**
