### PR TITLE
added exotica theme recipe to melpa

### PR DESCRIPTION
**Pull request by jbharat**
### Brief summary of what the package does

Dark theme with bright colors for emacs

### Direct link to the package repository

https://github.com/jbharat/exotica-theme.git

### Your association with the package

Creator/Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Please change the theme name in `deftheme` from `Exotica emacs theme` to `Exotica theme`, or (better) `A dark theme with vibrant colors`.

Looks good otherwise!

**Comment by purcell** [comment]
Also the licence must be GPL 3, not MIT, and you should include the corresponding info in the header of the file: see the boilerplate that `M-x auto-insert` inserts if you call it in an empty `.el` buffer.

**Comment by jbharat** [comment]
I have done the changes. It has GPL3 now.

**Comment by purcell** [comment]
Great, thanks. Almost there, but as my comment indicated, you should also include the boilerplate for the license info.

**Comment by jbharat** [comment]
Sorry. license info is now in the theme file

**Comment by jbharat** [comment]
auto-insert was not quitting inserting keyword. When I checked further, it seems to be a bug with ivy. I switched to helm and it worked properly. Sorry for the trouble. This is my first time committing to some external project. Thanks.

**Comment by purcell** [comment]
Awesome! Merging now...

Re. the Ivy issue, you can always hit "C-M-j" to tell Ivy "just accept what I've typed": that's the way to get out of the `auto-insert` keyword prompt. :-)

**Comment by jbharat** [comment]
Yes I found about C-M-j later. Thank you.

**Pull request merged**
