### PR TITLE
Add parinfer receipe

### PR DESCRIPTION
**Pull request by DogLooksGood**
### Brief summary of what the package does

Parinfer mode for S-expression edit.

### Direct link to the package repository

https://github.com/DogLooksGood/parinfer-mode

### Your association with the package

I'm maintainer.

### Relevant communications with the upstream package maintainer

None

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR(https://github.com/DogLooksGood/parinfer-mode/pull/5). And there are some byte-compile warnings please check them. (I think `goto-char` + `beginning-of-line` can be replaced with `forward-line`)

**Comment by DogLooksGood** [comment]
Thanks for PR and tips. I've fixed the byte-compile warnings.

**Comment by syohex** [comment]
BTW No window Emacs users(`emacs -nw`) cannot use `C-9`. So I recommend you to use another key binding or bind alternative key binding for such users.

**Comment by DogLooksGood** [comment]
@syohex I've remove the default keybinding to let user customize their own.  The instruction for this has been added to README.

**Comment by syohex** [comment]
Looks good.

**Comment by purcell** [comment]
Thanks. A little more feedback:
- Don't include installation instructions in the `Commentary` section: that text will be displayed on the MELPA package package. Instead, maybe create an `;;; Installation:` comment section.
- Docstrings for (at least) your `(interactive)` functions would be good: `M-x checkdoc` will help you there
- Instead of the package description `Parinfer on Emacs`, which doesn't tell the user anything about what the package does, use `"Simpler Lisp editing"`, since that is how `parinfer` describes itself.

Hope that helps!

**Comment by DogLooksGood** [comment]
@purcell Thanks for the advice. I have done these work and pushed to my repo.

**Comment by syohex** [comment]
Thanks.

**Pull request merged**
