### PR TITLE
Add new package: emacsql-sqlite3

### PR DESCRIPTION
**Pull request by cireu**
### Brief summary of what the package does

Yet another EmacSQL backend for SQlite

### Direct link to the package repository

https://github.com/cireu/emacsql-sqlite3

### Your association with the package

author

### Relevant communications with the upstream package maintainer

none needed 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

For reviewers:

Some methods defined with `cl-defmethod` don't have a docstring, their docstring should be contained in generics

`package-lint` complaint for `with-eval-after-load` usage of my code, it just false positive because `with-eval-after-load` form was in comment.

### CODE REVIEW

**Comment by cireu** [comment]
@riscy 

In fact, emacsql-sqlite3 was created to achieve the goal described in https://github.com/skeeto/emacsql/issues/56

emacsql-sqlite3 was not designed to be a general sqlite database manager, it assume that each slot in your database store a string, created by using `prin1-to-string` on a lisp object.

emacsql-sqlite3 can be a equivalent of emacsql-sqlite. but it prefer official sqlite3 CLI tool than skeeto's sqlite client.

**Comment by cireu** [comment]
https://github.com/cireu/emacsql-sqlite3/commit/02b4a6cf735c29f32517a1a515bcb7477421d9ac

**Comment by riscy** [comment]
Right on, thanks. :)

**Comment by tarsius** [comment]
@cireu Did you also consider linking to the sqlite library instead? I proposed that at https://github.com/skeeto/emacsql/pull/43 but am hoping someone else does the work. :wink:

**Comment by cireu** [comment]
> @cireu Did you also consider linking to the sqlite library instead? I proposed that at [skeeto/emacsql#43](https://github.com/skeeto/emacsql/pull/43) but am hoping someone else does the work. wink

If I find a SQLite binding in Rust, I' ll consider it :)

I just don't want to fiddle around with C language :joy:

**Comment by tarsius** [comment]
Understandable...

**Pull request merged**
