### PR TITLE
Add iscroll recipe

### PR DESCRIPTION
**Pull request by casouri**
### Brief summary of what the package does

This package add smooth scrolling over images.

### Direct link to the package repository

https://github.com/casouri/iscroll

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, looks like a useful package and the checklist looks clear.  We usually ask that you add a LICENSE file that GitHub can detect (e.g. no markup) if possible.

**Comment by casouri** [comment]
Added a license.

**Comment by riscy** [comment]
Thanks.  These aren't a blocker but I'll leave these for your consideration (some people dislike `unless`):

- iscroll.el#L106: Optionally use `unless ...` instead of `when (not ...)`
- iscroll.el#L162: Optionally use `unless ...` instead of `when (not ...)`
- iscroll.el#L245: Optionally use `unless ...` instead of `when (not ...)`
- iscroll.el#L250: Optionally use `unless ...` instead of `when (not ...)`
- iscroll.el#L86: Optionally use `unless ...` instead of `when (null ...)`
- iscroll.el#L153: Optionally use `unless ...` instead of `when (null ...)`

**Comment by casouri** [comment]
Thanks. I don't hate `unless`, but I don't use it whenever I can either. I guess partly because non-native English speakers like me find `unless` conditions harder to comprehend.

**Pull request merged**
