### PR TITLE
Add recipes for project-tasks

### PR DESCRIPTION
**Pull request by TxGVNN**
### Brief summary of what the package does

`Efficient task management for your project`

Base on my workflow, I wrote wrapper functions to provides a convenient interface for accessing those tasks instead of accessing org-mode files and executing org-babel code blocks.

### Direct link to the package repository

https://github.com/TxGVNN/project-tasks

### Your association with the package

A maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.

The first thing I notice is that your `;;; Commentary` only shows how to set this up with `use-package` (not everyone is going to be using that approach) and doesn't describe how this package works, and doesn't mention the (crucial?) tasks.org file, which I'm assuming is a file a user must parametrize in order to make use of the functionality here . Without that being documented, I think it is a little difficult for people to get started with this, and/or see how this works.  In other words, I think your `;;; Commentary` could be improved with entrypoints, a super-simple starter example, etc.

The other issue re: licensing is that this repo should have a LICENSE file added to it that can be detected with common tooling (see: https://github.com/licensee/licensee).

Other that, the code itself looks solid and I think the idea is appropriate.

**Comment by TxGVNN** [comment]
Thank you, @riscy 

I added a LICENSE file, and before I update the Commentary, I would like to ask you to review it first.
Do you think it is clear and enough information?

```
;;; Commentary:
;;`project-tasks' provides efficient task management for your project.
;; It allows you to organize and manage your project's tasks in an
;; Org file. You can quickly jump to the task file, capture new tasks
;; and easily run tasks by name.
;;
;; The main idea is to use Org source blocks as tasks. Each source
;; block is a task and its name is the task name. You can use
;; `project-tasks' to quickly run a task by name.
;;
;; Example:
;; If we want to have a fast way to run `top` command in our project,
;; we can add a source block named `Run top` to `tasks.org` file:
;;
;; #+name: Run top
;; #+begin_src elisp :results none
;; (comint-run "top")
;; #+end_src
;;
;; Then we just need to run `M-x project-tasks` to select and run the task.

```
P/S: I and GH copilot wrote it :D

**Comment by riscy** [comment]
That definitely looks like an improvement.  It looks like you still need to merge that into your default branch, though?

**Comment by riscy** [comment]
The LICENSE issue checks out now, so I'll hit merge on this one.  But I think that new Commentary tells me much more!

**Comment by TxGVNN** [comment]
Thank you, I merged

**Pull request merged**
