### PR TITLE
Add recipe for yeetube

### PR DESCRIPTION
**Pull request by ThanosApollon**
### Brief summary of what the package does

Font-End for YouTube/Invidious

### Direct link to the package repository

https://git.sr.ht/~thanosapollo/yeetube.el/

### Your association with the package

Author & maintainer 

### Relevant communications with the upstream package maintainer

None required

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`yeetube.el` with package-lint 20230605.1550:
```
12 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a Homepage or URL header.
1:48: warning: You should depend on (emacs "24.1") if you need lexical-binding.
28:10: error: You should depend on (emacs "24.1") if you need `url'.
29:10: error: You should depend on (emacs "24.3") if you need `org-element'.
30:10: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-lib'.
88:14: error: You should depend on (emacs "24.3") if you need `org-element-property'.
89:18: error: You should depend on (emacs "24.3") if you need `org-element-context'.
126:9: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-mapcar'.
141:14: error: You should depend on (emacs "24.3") if you need `org-element-property'.
142:18: error: You should depend on (emacs "24.3") if you need `org-element-context'.
178:19: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-mapcar'.
```

`yeetube.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- yeetube.el#L81: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)` in your config
```

Package and license:
- Avoid specifying `:branch` except in unusual cases (MELPA will use whatever's your default branch; you can probably remove the branch specifier)

**Comment by progfolio** [comment]
A few notes:

```emacs-lisp
(defun yeetube-search (arg)
  "Search for ARG."
```

A better name for this parameter would be QUERY.
It's more descriptive and ARG is typically used when the expectation is that a prefix-arg will be used within the command.

```emacs-lisp
(defcustom yeetube-search-for 10
```

```emacs-lisp 
(defcustom yeetube-search-query "https://www.youtube.com/results?search_query="
  "Search URL."
```

Likewise, these options could be `yeetube-results-limit` and `yeetube-query-url` or something similarly descriptive.


```emacs-lisp
(defcustom yeetube-player "mpv"
```

You should ensure the executable is present on the user's system. e.g.


```emacs-lisp
(defcustom yeetube-player (executable-find "mpv")
```

- Since you're using async-shell-command, you'll want to shell-quote-argument any args the user supplies.

- It would be nice to have the yeetube buffer in special-mode unless it is intended to be edited. This allows for quickly dismissing it via `q`.

**Comment by ThanosApollon** [comment]
Thanks for the feedback!

Removed `:branch` from the recipe.

- I'm getting no issues with `package-lint-20230605.1550` now

- With melpazoid:
`yeetube.el` with byte-compile using Emacs 28.1:
```
yeetube.el:232:61: Warning: Unused lexical argument `operation'
yeetube.el:232:61: Warning: Unused lexical argument `where'
```

the arguments `operation` and `where` are required for use with
`add-variable-watcher`.

from `add-variable-watcher` documentation:
```
It will be called with 4 arguments: (SYMBOL NEWVAL OPERATION WHERE).
```
Removing them breaks the package.

@progfolio

Thanks for the "notes"!  I've made some major changes to address them
and add new functionality, if you or anyone has any more feedback I'd
appreciate it!


---
Thanos

**Comment by progfolio** [comment]
> the arguments operation and where are required for use with
add-variable-watcher.

See: https://stackoverflow.com/questions/31870656/what-does-the-underscore-mean-in-elisp

**Comment by riscy** [comment]
Code looks good now -- thank you.  Before I merge, I wanted to make sure you were aware of these packages on MELPA:

- https://melpa.org/#/ytdious
- https://melpa.org/#/ytel

can you check whether these are overlapping with the functionality you propose?

**Comment by riscy** [comment]
Thank you very much for having a close look -- that's hugely appreciated.

@spiderbit and @grastello I think it makes sense for me to mention you here, just so that you're across these issues in case there's some kind of maintenance that needs to be done here.

@ThanosApollon -- welcome to MELPA. :)

**Pull request merged**
