### PR TITLE
Add lab-themes.

### PR DESCRIPTION
**Pull request by MetroWind**
### Brief summary of what the package does

A custom theme for Emacs

### Direct link to the package repository

https://github.com/MetroWind/lab-theme

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! A few comments:

- Please remove the `:files` spec from the recipe, since it is redundant.
- Stick to lower case file and theme names, please.
- The package description, `"A carefully contructed custom theme"` is not terribly helpful.
- The theme files say they're based on flatui - is that accurate?
- Setting `ns-appearance` [like this](https://github.com/MetroWind/lab-theme/blob/master/Lab-Dark-theme.el#L301-L306) is an unreliable and undesirable hack, and should be removed.

Hope that helps. Otherwise everything looks good! :-)

**Comment by DamienCassou** [comment]
What is the status of the PR?

**Comment by purcell** [comment]
Great, looks good now, but needs the same `;;;###autoload` for the `custom-theme-load-path` as mentioned in the `flucui-themes` PR.

**Comment by purcell** [comment]
:tada:

**Comment by purcell** [comment]
P.S. You might be interested in a mode I just published which aims to keep the `ns-appearance` frame parameter in sync with the current theme: https://github.com/purcell/ns-auto-titlebar

**Comment by MetroWind** [comment]
> P.S. You might be interested in a mode I just published which aims to keep the `ns-appearance` frame parameter in sync with the current theme: https://github.com/purcell/ns-auto-titlebar

Hah, that’s interesting~ Thanks for the info~

**Pull request merged**
