### PR TITLE
Add mu4e-conversation

### PR DESCRIPTION
**Pull request by Ambrevar**
### Brief summary of what the package does

Show a complete mu4e thread in a single buffer

### Direct link to the package repository

https://notabug.org/Ambrevar/mu4e-conversation

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer
**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick notes:

- `mu4e` isn't an installable package, so you should drop the `Package-Requires` entry which refers to it.
- Don't arbitrarily set one colour for a face, e.g. `'((t :background "#553333")`. This will be guaranteed to look awful in many themes. Instead, find built-in faces and `:inherit` them wherever possible, e.g. `outline-1` etc.
- Global toggle functions should often be global minor modes, e.g. `mu4e-conversation-toggle-globally`.

Looks good otherwise!

**Comment by Ambrevar** [comment]
Hi Steve!

I've addressed all issues.

Thanks for the review, and thanks for pointing out the outline-* faces,
it's much smarter indeed!  The global toggle is not really needed so
I've removed it altogether.  Hope it's all good now! :)

Cheers!

**Comment by Ambrevar** [comment]
I've just updated the recipe to reflect the move to gitlab.

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
