### PR TITLE
Add github-linguist

### PR DESCRIPTION
**Pull request by akirak**
### Brief summary of what the package does

Run GitHub Linguist on projects and persist the data. Later, you can use the data for various purposes, such as annotating completion candidates, grouping projects, etc.

### Direct link to the package repository

https://github.com/akirak/github-linguist.el

### Your association with the package

I am the author and the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks!  Looks neat -- I'm seeing one byte-compile warning on my end, maybe due to an Emacs version mismatch?:

`github-linguist.el` with byte-compile using Emacs 27.1:
```
github-linguist.el:249:1:Warning: the function `project-known-project-roots'
    is not known to be defined.
```

**Comment by akirak** [comment]
@riscy Thank you for your review!

> maybe due to an Emacs version mismatch?

Even Emacs 27.2 ships a rather old version of `project.el`, so the user needs to install project.el from GNU ELPA for now. Once Emacs 28 is officially released, the built-in version will be sufficient.

Is it acceptable to depend on a package from GNU ELPA? Should I have to wait for the upcoming release of Emacs?

The following description was inaccurate. Fixed:

> It integrates with project.el shipped with Emacs.

**Comment by riscy** [comment]
> Is it acceptable to depend on a package from GNU ELPA?

Definitely!

**Comment by akirak** [comment]
@riscy I think this PR is ready. Is there any blocker?

**Comment by riscy** [comment]
Thank you!  All looks great here.

**Pull request merged**
