### PR TITLE
Add smbc plugin recipie

### PR DESCRIPTION
**Pull request by sakshamsharma**
Plugin to view [SMBC](http://smbc-comics.com) web-comic inside Emacs
[URL for plugin](https://github.com/sakshamsharma/melpa)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:

- This should simply be called `smbc`. "emacs-" is very redundant in an elisp library.
- All top-level symbols should be named `smbc-*`, to conform with the [elisp conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html)
- `with-help-window` isn't appropriate here. It doesn't make sense for the resulting buffer to be in `help-mode`. Instead, create the buffer, then use a function like `display-buffer`, and consider putting the buffer into `special-mode`, which still gives you the handy `q` keybinding.

**Comment by sakshamsharma** [comment]
Hi! Thanks for the tips! I've acted upon all those suggestions, could you please have a look again? [URL](https://github.com/sakshamsharma/emacs-smbc).
Thanks!

**Comment by purcell** [comment]
Looks great, but you'll still need to rename and edit the MELPA recipe so it's for `smbc` and not `emacs-smbc` please.

**Comment by sakshamsharma** [comment]
I've updated it now. Didn't want to force push in a merge request, so I think a squash would be needed. 
Thanks!

**Comment by purcell** [comment]
Thanks, merged. (Force-push would have been okay, btw.)

**Pull request merged**
