### PR TITLE
New package ob-elvish

### PR DESCRIPTION
**Pull request by zzamboni**
### Brief summary of what the package does

New org-babel mode to support writing and running code for the Elvish shell (http://elvish.io)

### Direct link to the package repository

https://github.com/zzamboni/ob-elvish

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by DamienCassou** [comment]
Some feedback:
- Please run linters specified in CONTRIBUTING.md. They would have told you about:
  - some function names don't have the package name as prefix (e.g., `org-babel` instead of `ob-elvish`)
  - some docstrings don't descirbe the function parameters
- There is some commented code in the file. What about deleting it?
- Use `defcustom` to define user-changeable variables such as `ob-elvish-command` and `ob-elvish-command-options`

**Comment by zzamboni** [comment]
Hi @DamienCassou, thanks for your feedback. To address your points:

- I had already ran the linters, and saw the messages. However:
  - The `org-babel-execute:elvish` function is [required to be named like that by `org-babel`](https://code.orgmode.org/bzg/org-mode/src/master/lisp/ob-core.el#L687) for adding new language support - the naming convention allows `org-babel` to call them when a code block for the corresponding language is processed. These come from the [ob-template.el](https://code.orgmode.org/bzg/worg/raw/master/org-contrib/babel/ob-template.el) file.
  - The same reason applied for the "non-standard separator" error.
  - I have fixed the `org-babel-var-to-elvish` function (renamed to `ob-elvish-var-to-elvish`).
- Removed commented code.
- Thanks for the `defcustom` suggestion! Done.

Please let me know if you have additional feedback.

**Comment by purcell** [comment]
Looks good now, so merging. Welcome to MELPA! :tada:

P.S. The "format" call [here](https://github.com/zzamboni/ob-elvish/blob/9552e44996c7251347b25770135773594bd86c36/ob-elvish.el#L124) seem redundant, no?

**Comment by zzamboni** [comment]
@purcell thanks for the welcome! And good call on the `format` call, I'll clean it up.

**Pull request merged**
