### PR TITLE
Added flycheck-vale recipe

### PR DESCRIPTION
**Pull request by abingham**
### Brief summary of what the package does

Add flycheck integration for vale, a natural-language linter.

### Direct link to the package repository

https://github.com/abingham/flycheck-vale

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by marsam** [comment]
Cool! I didn't knew about vale. Would you mind making a pull request to Flycheck upstream to integrate this checker?

**Comment by abingham** [comment]
> Would you mind making a pull request to Flycheck upstream to integrate this checker?

@marsam Do you mean to add `flycheck-vale.el` to the flycheck repository? I think I'd like to keep it separate, at least for now, so that I can continue working on more easily. But if you mean some other form of integration, let me know.

**Comment by purcell** [comment]
Thanks. Quick notes:
- You should add a package dependency on `let-alist`, and probably also explicitly require `cl-lib`.
- Don't use the old `lexical-let` in a package for use with a recent Emacs: instead, declare `lexical-binding: t` in the header line, and lexical references should Just Work.

**Comment by abingham** [comment]
@purcell Thanks. These things should be cleaned up now.

**Comment by purcell** [comment]
Super, thanks.

**Pull request merged**
