### PR TITLE
Add recipe for unicode-math-input.el

### PR DESCRIPTION
**Pull request by astoff**
### Brief summary of what the package does

This package includes a more comprehensive variant of the built in TeX input method (includes all symbols listed in this file: http://ctan.org/tex-archive/macros/latex/contrib/unicode-math/unimath-symbols.pdf)

It also includes an Ivy method to browse and insert math symbols.

### Direct link to the package repository

https://github.com/astoff/unicode-math-input.el

### Your association with the package

I'm the author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by astoff** [comment]
package-lint complains that the command `unicode-math-browse` is not prefixed with the package's name. Is this unacceptable? I could call it `unicode-math-input-ivy`, but that sounds a bit awkward.

**Comment by jcs090218** [comment]
@astoff I think you do have to prefix it with `unicode-math-input-`, I reckon having the variable's name with prefix is ensure not having define the same variable name multiple times. You could rename the variable with prefix and also make you feel less awkward?

**Comment by purcell** [comment]
Hi, and thanks for your patience!

Yes, the symbol prefix must match the package name, so `unicode-math-browse` could be renamed to `unicode-math-input`.

The `ivy` dependency is quite opinionated and I wonder if it's actually necessary: `completing-read` is overridden by `ivy`/`helm` etc. when the user enables them, and `completing-read` (and Ivy) support providing a hash table of completions. I suspect you may be able to just call `completing-read` with a hash table mapping the input strings to the output characters.

Otherwise, this looks great!

**Comment by astoff** [comment]
Thanks for the feedback! I fixed the namespace issue, and I moved from ivy to a simple `completing-read`. Everything should be fine now.

**Pull request merged**
