### PR TITLE
Recipe for cardano-tx from Cardano.el

### PR DESCRIPTION
**Pull request by Titan-C**
### Brief summary of what the package does

A utility function to wrap around CLI commands used for the Cardano blockchain.
This package has 3 dependencies requested for inclusion on #8109 #8110 #8111 
 1 main package and lastly 1 optional package.  

### Direct link to the package repository

https://github.com/Titan-C/cardano.el

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for these.  As a reviewer my personal preference is one recipe per PR (this can be a good idea if there are dependencies between the packages, so that I can test the installation of the dependencies vs. the package end-to-end), but I won't block on that here.  Quick first pass --

## cbor

Checklist look good.

# bech32

Checklist looks good.

## cardano-wallet

`cardano-wallet.el` with byte-compile using Emacs 28.1:
```
cardano-wallet.el:17:1: Error: Cannot open load file: No such file or directory, yaml
```
This dependency may end up being transitively installed, but you shouldn't rely on that.

- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to cardano-wallet.el

## cardano-tx

This one appears to be missing a required `Package-Requires` line which is worth considering when reading the following.

`cardano-address.el` with byte-compile using Emacs 28.1:
```
cardano-address.el:29:1: Error: Cannot open load file: No such file or directory, bech32
```

`cardano-address.el` with package-lint 20220607.738:
```
29 issues found:
37:0: error: "cardano-address" doesn't start with package's prefix "cardano-tx".
43:0: error: "cardano-address--short" doesn't start with package's prefix "cardano-tx".
50:0: error: "cardano-address-new-key" doesn't start with package's prefix "cardano-tx".
66:0: error: "cardano-address-new-key-files" doesn't start with package's prefix "cardano-tx".
77:0: error: "cardano-address-stake-pick" doesn't start with package's prefix "cardano-tx".
84:0: error: "cardano-address-load" doesn't start with package's prefix "cardano-tx".
111:0: error: "cardano-address-payment" doesn't start with package's prefix "cardano-tx".
119:0: error: "cardano-address-staking" doesn't start with package's prefix "cardano-tx".
124:0: error: "cardano-address-from-script" doesn't start with package's prefix "cardano-tx".
133:0: error: "cardano-address-stake-registration-cert" doesn't start with package's prefix "cardano-tx".
145:0: error: "cardano-address-delegation-certificate" doesn't start with package's prefix "cardano-tx".
155:0: error: "cardano-address-named" doesn't start with package's prefix "cardano-tx".
165:0: error: "cardano-address-pick" doesn't start with package's prefix "cardano-tx".
173:0: error: "cardano-address-key-hash" doesn't start with package's prefix "cardano-tx".
183:0: error: "cardano-address-decode" doesn't start with package's prefix "cardano-tx".
204:0: error: "cardano-address-build" doesn't start with package's prefix "cardano-tx".
230:0: error: "cardano-address-command" doesn't start with package's prefix "cardano-tx".
235:0: error: "cardano-address-path->str" doesn't start with package's prefix "cardano-tx".
242:0: error: "cardano-address--validate-hd-path" doesn't start with package's prefix "cardano-tx".
260:0: error: "cardano-address-gen-recovery-phrase" doesn't start with package's prefix "cardano-tx".
278:0: error: "cardano-address-piped" doesn't start with package's prefix "cardano-tx".
287:0: error: "cardano-address-master-key-from-phrase" doesn't start with package's prefix "cardano-tx".
291:0: error: "cardano-address-derive-child" doesn't start with package's prefix "cardano-tx".
297:0: error: "cardano-address-public-key" doesn't start with package's prefix "cardano-tx".
304:0: error: "cardano-address--json-priv-key" doesn't start with package's prefix "cardano-tx".
317:0: error: "cardano-address--json-pub-key" doesn't start with package's prefix "cardano-tx".
326:0: error: "cardano-address-cli-keys" doesn't start with package's prefix "cardano-tx".
352:0: error: "cardano-address-new-hd-key" doesn't start with package's prefix "cardano-tx".
361:0: error: "cardano-address-new-hd-key-files" doesn't start with package's prefix "cardano-tx".
```

`cardano-address.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- cardano-address.el#L198: This double negation can be collapsed (`not` aliases `null`)
```

`cardano-assets.el` with byte-compile using Emacs 28.1:
```
cardano-assets.el:30:1: Error: Cannot open load file: No such file or directory, cbor
```

`cardano-assets.el` with package-lint 20220607.738:
```
5 issues found:
34:0: error: "cardano-assets-parse-token-bundle" doesn't start with package's prefix "cardano-tx".
47:0: error: "cardano-assets-format-tokens" doesn't start with package's prefix "cardano-tx".
61:0: error: "cardano-assets-hexify" doesn't start with package's prefix "cardano-tx".
72:0: error: "cardano-assets-flatten" doesn't start with package's prefix "cardano-tx".
83:0: error: "cardano-assets-merge-alists" doesn't start with package's prefix "cardano-tx".
```

`cardano-cli.el` with package-lint 20220607.738:
```
10 issues found:
35:0: error: "cardano-cli" doesn't start with package's prefix "cardano-tx".
39:0: error: "cardano-cli-command" doesn't start with package's prefix "cardano-tx".
43:0: error: "cardano-cli-node-socket" doesn't start with package's prefix "cardano-tx".
47:0: error: "cardano-cli-network-args" doesn't start with package's prefix "cardano-tx".
51:0: error: "cardano-cli-skip-network-args" doesn't start with package's prefix "cardano-tx".
59:0: error: "cardano-cli" doesn't start with package's prefix "cardano-tx".
71:0: error: "cardano-cli-reply" doesn't start with package's prefix "cardano-tx".
82:0: error: "cardano-cli-pretty-yaml-message" doesn't start with package's prefix "cardano-tx".
92:0: error: "cardano-cli-tip" doesn't start with package's prefix "cardano-tx".
99:0: error: "cardano-cli-version" doesn't start with package's prefix "cardano-tx".
```

`cardano-cli.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- cardano-cli.el#L43: Use `(temporary-file-directory)` instead of /tmp in code
```

`cardano-db.el` with byte-compile using Emacs 28.1:
```
cardano-db.el:21:1: Error: Cannot open load file: No such file or directory, cbor
```

`cardano-db.el` with package-lint 20220607.738:
```
36 issues found:
23:0: error: "cardano-db" doesn't start with package's prefix "cardano-tx".
27:0: error: "cardano-db-keyring-dir" doesn't start with package's prefix "cardano-tx".
31:0: error: "cardano-db-version" doesn't start with package's prefix "cardano-tx".
33:0: error: "cardano-db--table-schema" doesn't start with package's prefix "cardano-tx".
43:0: error: "cardano-db-connection" doesn't start with package's prefix "cardano-tx".
45:0: error: "cardano-db--init" doesn't start with package's prefix "cardano-tx".
52:0: error: "cardano-db" doesn't start with package's prefix "cardano-tx".
64:0: error: "cardano-db-retrieve-datum" doesn't start with package's prefix "cardano-tx".
71:0: error: "cardano-db-save-datum" doesn't start with package's prefix "cardano-tx".
80:0: error: "cardano-db-stake-keys" doesn't start with package's prefix "cardano-tx".
84:0: error: "cardano-db-address--list" doesn't start with package's prefix "cardano-tx".
91:0: error: "cardano-db-insert-address" doesn't start with package's prefix "cardano-tx".
101:0: error: "cardano-db-address-toggle-watch" doesn't start with package's prefix "cardano-tx".
121:0: error: "cardano-db-addresses--refresh" doesn't start with package's prefix "cardano-tx".
135:0: error: "cardano-db-address-copy" doesn't start with package's prefix "cardano-tx".
141:0: error: "cardano-db-address-annotate" doesn't start with package's prefix "cardano-tx".
178:0: error: "cardano-db-addresses-mode-map" doesn't start with package's prefix "cardano-tx".
185:0: error: "cardano-db-addresses-mode" doesn't start with package's prefix "cardano-tx".
194:0: error: "cardano-db-addresses" doesn't start with package's prefix "cardano-tx".
205:0: error: "cardano-db-load-files" doesn't start with package's prefix "cardano-tx".
232:0: error: "cardano-db-files-of-type" doesn't start with package's prefix "cardano-tx".
239:0: error: "cardano-db-dired-load-files" doesn't start with package's prefix "cardano-tx".
246:0: error: "cardano-db-files--refresh" doesn't start with package's prefix "cardano-tx".
259:0: error: "cardano-db-file" doesn't start with package's prefix "cardano-tx".
266:0: error: "cardano-db-file-open" doesn't start with package's prefix "cardano-tx".
272:0: error: "cardano-db-insert-native-script-block" doesn't start with package's prefix "cardano-tx".
282:0: error: "cardano-db-insert-file-annotation-block" doesn't start with package's prefix "cardano-tx".
288:0: error: "cardano-db-file-annotate" doesn't start with package's prefix "cardano-tx".
317:0: error: "cardano-db-files-mode-map" doesn't start with package's prefix "cardano-tx".
323:0: error: "cardano-db-files-mode" doesn't start with package's prefix "cardano-tx".
332:0: error: "cardano-db-typed-files" doesn't start with package's prefix "cardano-tx".
343:0: error: "cardano-db-utxo-reset" doesn't start with package's prefix "cardano-tx".
350:0: error: "cardano-db-utxo--list" doesn't start with package's prefix "cardano-tx".
354:0: error: "cardano-db-utxo-load" doesn't start with package's prefix "cardano-tx".
373:0: error: "cardano-db-utxo-info" doesn't start with package's prefix "cardano-tx".
385:0: error: "cardano-db-utxo-spend" doesn't start with package's prefix "cardano-tx".
```

`cardano-log.el` with package-lint 20220607.738:
```
6 issues found:
32:0: error: "cardano-log-buffer-name" doesn't start with package's prefix "cardano-tx".
35:0: error: "cardano-log-level" doesn't start with package's prefix "cardano-tx".
38:0: error: "cardano-log-buffer" doesn't start with package's prefix "cardano-tx".
46:0: error: "cardano-log--level-number" doesn't start with package's prefix "cardano-tx".
55:0: error: "cardano-log--level-face" doesn't start with package's prefix "cardano-tx".
63:0: error: "cardano-log" doesn't start with package's prefix "cardano-tx".
```

`cardano-log.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- cardano-log.el#L74: Can the `format` and `concat` be combined?
```

`cardano-tx.el` with byte-compile using Emacs 28.1:
```
cardano-tx.el:44:1: Error: Cannot open load file: No such file or directory, cbor
```

`cardano-tx.el` with package-lint 20220607.738:
```
2 issues found:
9:123: error: Package cbor is not installable.
9:138: error: Package bech32 is not installable.
```

`cardano-utils.el` with byte-compile using Emacs 28.1:
```
cardano-utils.el:34:1: Error: Cannot open load file: No such file or directory, cbor
```

`cardano-utils.el` with package-lint 20220607.738:
```
6 issues found:
39:0: error: "cardano-utils-nw-p" doesn't start with package's prefix "cardano-tx".
45:0: error: "cardano-utils-get-in" doesn't start with package's prefix "cardano-tx".
49:0: error: "cardano-utils--reducer-get-in" doesn't start with package's prefix "cardano-tx".
58:0: error: "cardano-utils-pick" doesn't start with package's prefix "cardano-tx".
66:0: error: "cardano-utils-alist-key-string" doesn't start with package's prefix "cardano-tx".
90:0: error: "cardano-utils--parse-response" doesn't start with package's prefix "cardano-tx".
```

`numbers.el` with package-lint 20220607.738:
```
11 issues found:
28:0: error: "numbers" doesn't start with package's prefix "cardano-tx".
32:0: error: "numbers-separator" doesn't start with package's prefix "cardano-tx".
36:0: error: "numbers-separator-interval" doesn't start with package's prefix "cardano-tx".
40:0: error: "numbers-separator-ignore-threshold" doesn't start with package's prefix "cardano-tx".
45:0: error: "numbers-set-overlay-properties" doesn't start with package's prefix "cardano-tx".
54:0: error: "numbers-overlay-p" doesn't start with package's prefix "cardano-tx".
58:0: error: "numbers-make-overlay" doesn't start with package's prefix "cardano-tx".
64:0: error: "numbers-make-unreadable" doesn't start with package's prefix "cardano-tx".
70:0: error: "numbers-make-readable" doesn't start with package's prefix "cardano-tx".
85:0: error: "numbers-change" doesn't start with package's prefix "cardano-tx".
90:0: error: "numbers-separator-mode" doesn't start with package's prefix "cardano-tx".
```

**Comment by Titan-C** [comment]
I'm still not familiar with the emacs namespace convention for large packages.
There is the recurring warning 
```"cardano-utils--parse-response" doesn't start with package's prefix "cardano-tx"```
Do I really must have that prefix even for all auxiliary packages? It feels to me it doesn't make sense. Is there another strategy to deal with library files for the main package?

Finally I get the feeling "numbers.el" should be a separate package. Any comment on that?

**Comment by riscy** [comment]
Before we go too much further, I would recommend in this case that we break this PR down into one PR per recipe so that we can tackle issues incrementally.

> Do I really must have that prefix even for all auxiliary packages? It feels to me it doesn't make sense. Is there another strategy to deal with library files for the main package?

It may feel inconvenient, but a simple and fair way to prevent namespace collisions across MELPA (and hopefully elsewhere) is to ask that the package, variable names, and function names all use the same prefix.  In very rare cases I would make exceptions to this rule (e.g. backward compatibility with a package predating this rule) -- and `package-lint` has some of these exceptions built into it.

For example, your package is colliding with the namespace of this package:

- https://melpa.org/#/numbers

> Finally I get the feeling "numbers.el" should be a separate package. Any comment on that?

I don't have enough context to give you a good answer yet, but note that there already is a package called `numbers` on MELPA.

**Comment by Titan-C** [comment]
I created 3 separate PR for the package dependencies. Yes `numbers.el` is a independent minor mode and is now repackaged as `readable-numbers.el`
The main package cardano-tx now enforces its namespace prefix across all files on the upstream repo and the plugin cardano-wallet is has its own prefix. I kept that recipe in this PR nevertheless.

**Comment by riscy** [comment]
I'm just getting to these now but here's the latest on the two recipes:

`cardano-wallet.el` with byte-compile using Emacs 28.1:
```
cardano-wallet.el:35:1: Error: Cannot open load file: No such file or directory, dash
```

`cardano-wallet.el` with package-lint 20220607.738:
```
1 issue found:
9:53: error: Package cardano-tx is not installable.
```
(Understandable in this case)

`#'load`-check on each file:
```
Loading cardano-wallet.el
  cardano-wallet.el:Error: Emacs 28.1 couldn't load:
  (file-missing "Cannot open load file" "No such file or directory" "dash")
```

`cardano-tx-db.el` with checkdoc 0.6.2:
```
cardano-tx-db.el:203: Lisp symbol `cardano-tx-db' should appear in quotes
cardano-tx-db.el:237: Lisp symbol `cardano-tx-db' should appear in quotes
```

`cardano-tx.el` with byte-compile using Emacs 28.1:
```
cardano-tx.el:42:1: Error: Cannot open load file: No such file or directory, readable-numbers
```

- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to cardano-tx-db.el

**Comment by riscy** [comment]
Thanks - looks good to merge.

I'm just curious about the use of `kill-new` in e.g. `cardano-tx-policyid` -- why would this string need to be on the kill ring after being returned to one of its callers?  I might be missing something but it seems extraneous.  Not a blocker, but that just caught my eye.

**Comment by Titan-C** [comment]
> I'm just curious about the use of `kill-new` in e.g. `cardano-tx-policyid` -- why would this string need to be on the kill ring after being returned to one of its callers? I might be missing something but it seems extraneous. Not a blocker, but that just caught my eye.
In my ignorance and search for convenience, that was my solution for the interactive call. How do I keep the value of the calculation? Probably I should use an extra if statement that only loads the return value on the kill-ring when the function was interactively called.

**Pull request merged**
