### PR TITLE
Add upbo recipe

### PR DESCRIPTION
**Pull request by shiren**
### Brief summary of what the package does

Upbo is javascript test runner integration for emacs
Currently It support Karma but it will support Jest soon.

### Direct link to the package repository

https://github.com/shiren/upbo

### Your association with the package

I wrote this :)

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick feedback:

- Instead of `upbo-git-root-dir`, just use `vc-git-root`, or even `vc-root-dir`, if you don't need to be `git`-specific.
- You have the word `"Emacs"` in the package description line, and you're using [reserved](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html) `C-c u` keybindings -- `package-lint` should have warned you about these issues when you ran it.
- `upbo-mode-hook` calls `upbo-mode` -- that's not what hooks are for. You should just delete that function.
- You don't need to `generate-new-buffer` [here](https://github.com/shiren/upbo/blob/master/upbo.el#L72) - you can just use `(with-current-buffer (get-buffer-create upbo-view-buffer) ...`

Hope that helps.

**Comment by shiren** [comment]
Thank you!
I applied whole your comments :)

**Comment by purcell** [comment]
Thanks. Sent you two further little fixes in https://github.com/shiren/upbo/pull/4 and https://github.com/shiren/upbo/pull/5.

**Comment by purcell** [comment]
Merged now - welcome to MELPA! :tada:

**Pull request merged**
