### PR TITLE
Add coverlay

### PR DESCRIPTION
**Pull request by kytwb**
Test coverage overlay for Emacs

### CODE REVIEW

**Comment by FossiFoo** [comment]
nice. i meant to do this for a while.

**Comment by purcell** [comment]
Thanks. I sent a small fix in https://github.com/twada/coverlay.el/pull/8, but the library also uses the `C-c l` keybinding, which is [reserved for user customisation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html). Would you mind suggesting a new binding to the maintainer?

**Comment by kytwb** [comment]
@purcell the keybindings have been updated in this merged pull-request https://github.com/twada/coverlay.el/pull/9

**Comment by purcell** [comment]
Super, thanks!

**Pull request merged**
