### PR TITLE
Add recipe for clang-format-remote

### PR DESCRIPTION
**Pull request by arteen1000**
### Brief summary of what the package does

It provides a configurable hook into any major-mode that allows for clang-format upon saving a file. It is distinct from the other packages because it also works with tramp/remote files. I created this package through extending my own configuration, which I needed this for.

### Direct link to the package repository

https://github.com/arteen1000/clang-format-remote

### Your association with the package

I am the maintainer/creator. 

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.

There is another PR up https://github.com/melpa/melpa/pull/8762 where we've suggested that incremental features (like this, I believe) be upstreamed into clang-format itself.  Have you thought about seeing if that could be done here?

**Comment by arteen1000** [comment]
My mode is fundamentally quite different and for me negates the usage of `clang-format`. I looked into the code for `clang-format`, and it is drastically more complex. This could be added, but it's a simpler design/implementation that fully replaces the need for the other package + handles a case that the other does not and provides the `on-save` functionality you linked.

If I were to upstream into `clang-format`, I'd simply replace it.

**Comment by riscy** [comment]
I hope I don't sound too pedantic, but since you've taken a look, what makes your mode fundamentally quite different?  I'm not disputing that `clang-format` may be drastically more complex - and very often code can be unnecessarily complex - but the original `clang-format` may have also weathered some trials through use, leading to its complexity.

While I'm here, I'm also noticing in `clang-format-remote-on-disk` that if the relative directory (or the filename itself, I guess) contains spaces or control characters, the `shell-command` callout could do unexpected things - I'd recommend adding `shell-quote-argument` in this case.

**Comment by arteen1000** [comment]
Thanks for the callout. I'll make the fix for filenames with special characters. I hadn't encountered that in my own use.

I believe the mode is fundamentally different because it offloads _all_ of the work to the **clang-format** program, as opposed to the clang-format package, which tries to do a lot in ELisp itself. It essentially boils down to the implementation (which you noted is much simpler), but it solves the problem that clang-format has where the native ELisp doesn't handle remote files with this handoff and ends up in a simple solution that handles all cases and provides some extra convenience hooks for the most common usage, on-save when working in large projects.

**Comment by riscy** [comment]
Thank you for that detailed explanation.  I think [clang-format+](https://github.com/SavchenkoValeriy/emacs-clang-format-plus/tree/master) has similar rationale.

I think the distinguishing feature here isn't only that this enables "remote" formatting, but that it wholly relies on the clang-format binary rather than an elisp implementation.  (To me it seems that the lack of remote formatting in the original clang-format package is an oversight or even a bug that one day should be fixed.)

Therefore I think you should choose a better name and summary, e.g. instead of `clang-format-remote` you might call this `clang-format-lite` for example - and emphasize what distinguishes your package from `clang-format+` as well.

To make your implementation even lighter, have you seen https://melpa.org/#/?q=reformater ? 

And if we merge this PR, maybe #8762 becomes unnecessary.  (@ideasman42 - thoughts?)

**Comment by arteen1000** [comment]
Thanks for the feedback. I made the suggested changes and agree with the reasoning. The link for `reformatter` didn't have any results, but I personally think it's best to not be dependent on other packages if not strictly necessary.

**Comment by riscy** [comment]
> The link for reformatter didn't have any results, but I personally think it's best to not be dependent on other packages if not strictly necessary.

Sorry, here it is - https://melpa.org/#/reformatter - but if you think you're handling everything re: undo behavior and so forth, it's just fyi.

**Pull request merged**
