### PR TITLE
Add recipe for pipewire-zero

### PR DESCRIPTION
**Pull request by mz-pdm**
### Brief summary of what the package does

Interface to PipeWire.

### Direct link to the package repository

https://git.zamazal.org/pdm/pipewire-0

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

I'm the upstream author.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Quick first pass -- on a very quick skim I think the biggest issues are around the package prefix.

`pw-access.el` with checkdoc 0.6.2:
```
pw-access.el:51: Argument `class' should appear (as CLASS) in the doc string
pw-access.el:63: Argument `class' should appear (as CLASS) in the doc string
pw-access.el:79: Argument `class' should appear (as CLASS) in the doc string
pw-access.el:87: Argument `class' should appear (as CLASS) in the doc string
pw-access.el:96: Argument `class' should appear (as CLASS) in the doc string
pw-access.el:104: Argument `class' should appear (as CLASS) in the doc string
pw-access.el:111: Argument `class' should appear (as CLASS) in the doc string
pw-access.el:118: Argument `class' should appear (as CLASS) in the doc string
pw-access.el:126: First line should be capitalized
pw-access.el:129: First line should be capitalized
```

`pw-access.el` with package-lint 20220607.738:
```
22 issues found:
44:0: error: "pw-accessor" doesn't start with package's prefix "pipewire-zero".
50:0: error: "pw-access-objects" doesn't start with package's prefix "pipewire-zero".
62:0: error: "pw-access-properties" doesn't start with package's prefix "pipewire-zero".
78:0: error: "pw-access-set-properties" doesn't start with package's prefix "pipewire-zero".
86:0: error: "pw-access-current-profile" doesn't start with package's prefix "pipewire-zero".
95:0: error: "pw-access-profiles" doesn't start with package's prefix "pipewire-zero".
103:0: error: "pw-access-set-profile" doesn't start with package's prefix "pipewire-zero".
110:0: error: "pw-access-defaults" doesn't start with package's prefix "pipewire-zero".
117:0: error: "pw-access-set-default" doesn't start with package's prefix "pipewire-zero".
125:0: error: "pw-cli-command" doesn't start with package's prefix "pipewire-zero".
128:0: error: "pw-cli-metadata-command" doesn't start with package's prefix "pipewire-zero".
131:0: error: "pw-cli-accessor" doesn't start with package's prefix "pipewire-zero".
137:0: error: "pw-cli--command" doesn't start with package's prefix "pipewire-zero".
141:0: error: "pw-cli--next-line" doesn't start with package's prefix "pipewire-zero".
144:0: error: "pw-cli--parse-list" doesn't start with package's prefix "pipewire-zero".
165:0: error: "pw-cli--read-property" doesn't start with package's prefix "pipewire-zero".
188:0: error: "pw-cli--parse-properties" doesn't start with package's prefix "pipewire-zero".
208:0: error: "pw-cli--format-property-value" doesn't start with package's prefix "pipewire-zero".
217:0: error: "pw-cli--format-property" doesn't start with package's prefix "pipewire-zero".
220:0: error: "pw-cli--format-properties" doesn't start with package's prefix "pipewire-zero".
223:0: error: "pw-cli--set-parameter" doesn't start with package's prefix "pipewire-zero".
246:0: error: "pw-cli--parse-metadata" doesn't start with package's prefix "pipewire-zero".
```

`pw-lib.el` with package-lint 20220607.738:
```
37 issues found:
40:0: error: "pw-lib--accessor" doesn't start with package's prefix "pipewire-zero".
42:0: error: "pw-lib--objects" doesn't start with package's prefix "pipewire-zero".
43:0: error: "pw-lib--bindings" doesn't start with package's prefix "pipewire-zero".
44:0: error: "pw-lib--defaults" doesn't start with package's prefix "pipewire-zero".
46:0: error: "pw-lib-refresh" doesn't start with package's prefix "pipewire-zero".
52:0: error: "pw-lib-objects" doesn't start with package's prefix "pipewire-zero".
70:0: error: "pw-lib-get-object" doesn't start with package's prefix "pipewire-zero".
77:0: error: "pw-lib-object-id" doesn't start with package's prefix "pipewire-zero".
81:0: error: "pw-lib--object-info" doesn't start with package's prefix "pipewire-zero".
84:0: error: "pw-lib-object-value" doesn't start with package's prefix "pipewire-zero".
91:0: error: "pw-lib-properties" doesn't start with package's prefix "pipewire-zero".
98:0: error: "pw-lib-object-type" doesn't start with package's prefix "pipewire-zero".
103:0: error: "pw-lib--profile-name" doesn't start with package's prefix "pipewire-zero".
107:0: error: "pw-lib-current-profile" doesn't start with package's prefix "pipewire-zero".
113:0: error: "pw-lib-profiles" doesn't start with package's prefix "pipewire-zero".
119:0: error: "pw-lib-set-profile" doesn't start with package's prefix "pipewire-zero".
133:0: error: "pw-lib-parent-node" doesn't start with package's prefix "pipewire-zero".
139:0: error: "pw-lib--node" doesn't start with package's prefix "pipewire-zero".
144:0: error: "pw-lib--node-parameters" doesn't start with package's prefix "pipewire-zero".
156:0: error: "pw-lib-default-nodes" doesn't start with package's prefix "pipewire-zero".
176:0: error: "pw-lib--default-node" doesn't start with package's prefix "pipewire-zero".
179:0: error: "pw-lib-bindings" doesn't start with package's prefix "pipewire-zero".
196:0: error: "pw-lib-children" doesn't start with package's prefix "pipewire-zero".
210:0: error: "pw-lib--node-ports" doesn't start with package's prefix "pipewire-zero".
220:0: error: "pw-lib-default-audio-sink" doesn't start with package's prefix "pipewire-zero".
224:0: error: "pw-lib-default-audio-source" doesn't start with package's prefix "pipewire-zero".
228:0: error: "pw-lib-default-playback-ports" doesn't start with package's prefix "pipewire-zero".
232:0: error: "pw-lib-default-capture-ports" doesn't start with package's prefix "pipewire-zero".
236:0: error: "pw-lib--volume-%" doesn't start with package's prefix "pipewire-zero".
240:0: error: "pw-lib--volume-float" doesn't start with package's prefix "pipewire-zero".
243:0: error: "pw-lib--object-parameters" doesn't start with package's prefix "pipewire-zero".
253:0: error: "pw-lib-muted-p" doesn't start with package's prefix "pipewire-zero".
262:0: error: "pw-lib-toggle-mute" doesn't start with package's prefix "pipewire-zero".
276:0: error: "pw-lib-volume" doesn't start with package's prefix "pipewire-zero".
289:0: error: "pw-lib-set-volume" doesn't start with package's prefix "pipewire-zero".
310:0: error: "pw-lib--set-default-node" doesn't start with package's prefix "pipewire-zero".
318:0: error: "pw-lib-set-default" doesn't start with package's prefix "pipewire-zero".
```

`pw-ui.el` with package-lint 20220607.738:
```
45 issues found:
38:0: error: "pipewire" doesn't start with package's prefix "pipewire-zero".
42:0: error: "pipewire-volume-step" doesn't start with package's prefix "pipewire-zero".
47:0: error: "pipewire-osd-enable" doesn't start with package's prefix "pipewire-zero".
53:0: error: "pipewire-osd-timeout" doesn't start with package's prefix "pipewire-zero".
58:0: error: "pipewire-osd-width" doesn't start with package's prefix "pipewire-zero".
63:0: error: "pipewire-osd-volume-on-color" doesn't start with package's prefix "pipewire-zero".
68:0: error: "pipewire-osd-volume-off-color" doesn't start with package's prefix "pipewire-zero".
73:0: error: "pipewire-osd-frame-parameters" doesn't start with package's prefix "pipewire-zero".
80:0: error: "pipewire-label" doesn't start with package's prefix "pipewire-zero".
85:0: error: "pipewire-default-object" doesn't start with package's prefix "pipewire-zero".
90:0: error: "pipewire-muted" doesn't start with package's prefix "pipewire-zero".
95:0: error: "pipewire-volume" doesn't start with package's prefix "pipewire-zero".
100:0: error: "pipewire-buffer" doesn't start with package's prefix "pipewire-zero".
101:0: error: "pipewire-properties-buffer" doesn't start with package's prefix "pipewire-zero".
103:0: error: "pw-ui--label" doesn't start with package's prefix "pipewire-zero".
106:0: error: "pw-ui--object-volume" doesn't start with package's prefix "pipewire-zero".
109:0: error: "pw-ui--object-name" doesn't start with package's prefix "pipewire-zero".
121:0: error: "pw-ui--object-label" doesn't start with package's prefix "pipewire-zero".
145:0: error: "pw-ui--insert-line" doesn't start with package's prefix "pipewire-zero".
148:0: error: "pipewire-refresh" doesn't start with package's prefix "pipewire-zero".
172:0: error: "pw-ui--current-object-id" doesn't start with package's prefix "pipewire-zero".
175:0: error: "pw-ui--current-object" doesn't start with package's prefix "pipewire-zero".
187:0: error: "pw-ui--osd-timer" doesn't start with package's prefix "pipewire-zero".
188:0: error: "pw-ui--osd-frame" doesn't start with package's prefix "pipewire-zero".
189:0: error: "pw-ui--osd-buffer" doesn't start with package's prefix "pipewire-zero".
190:0: error: "pw-ui--osd-buffer-name" doesn't start with package's prefix "pipewire-zero".
192:0: error: "pw-ui--osd-display" doesn't start with package's prefix "pipewire-zero".
235:0: error: "pw-ui--osd" doesn't start with package's prefix "pipewire-zero".
243:0: error: "pw-ui--update" doesn't start with package's prefix "pipewire-zero".
251:0: error: "pw-ui--osd-volume" doesn't start with package's prefix "pipewire-zero".
267:0: error: "pw-ui--update-muted" doesn't start with package's prefix "pipewire-zero".
276:0: error: "pipewire-toggle-muted" doesn't start with package's prefix "pipewire-zero".
287:0: error: "pipewire-toggle-microphone" doesn't start with package's prefix "pipewire-zero".
295:0: error: "pipewire-set-volume" doesn't start with package's prefix "pipewire-zero".
311:0: error: "pw-ui--change-volume" doesn't start with package's prefix "pipewire-zero".
318:0: error: "pipewire-increase-volume" doesn't start with package's prefix "pipewire-zero".
328:0: error: "pipewire-increase-volume-single" doesn't start with package's prefix "pipewire-zero".
337:0: error: "pipewire-decrease-volume" doesn't start with package's prefix "pipewire-zero".
347:0: error: "pipewire-decrease-volume-single" doesn't start with package's prefix "pipewire-zero".
356:0: error: "pipewire-set-default" doesn't start with package's prefix "pipewire-zero".
376:0: error: "pipewire-set-profile" doesn't start with package's prefix "pipewire-zero".
389:0: error: "pipewire-properties" doesn't start with package's prefix "pipewire-zero".
403:0: error: "pipewire-mode-map" doesn't start with package's prefix "pipewire-zero".
416:0: error: "pipewire-mode" doesn't start with package's prefix "pipewire-zero".
425:0: error: "pipewire" doesn't start with package's prefix "pipewire-zero".
```

`pw-ui.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- pw-ui.el#L179: This double negation can be collapsed (`not` aliases `null`)
```

- pipewire-zero-pkg.el -- consider excluding; MELPA creates one (i.e. from a file called pipwire-zero.el)

**Comment by riscy** [comment]
Thanks for accommodating --

> The only way to get rid of these warnings is to rephrase but as a non-native speaker I'm having trouble to find a nice wording. Can you suggest something?

I see - instead of "pw-cli command to use." you could also write "Command to invoke pw-cli." or "Path to pw-cli executable." (if I'm understanding the variable correctly).

> As for the prefixes, I renamed pw-ui.el to pipewire.el to avoid using multiple prefixes there. But it's hard to do anything more. Using super-long prefixes like pipewire-zero-access- wouldn't be a good idea and I don't know how to make checkdoc happy otherwise.

It may feel inconvenient, but a simple and fair way to prevent namespace collisions across MELPA (and hopefully elsewhere) is to ask that the package, variable names, and function names all use the same prefix.  In very rare cases I would make exceptions to this rule (e.g. backward compatibility with a package predating this rule) -- and `package-lint` has some of these exceptions built into it.  Sometimes the fix is to split a package up into two MELPA recipes, especially if a modular piece of it can be neatly factored out.

**Comment by mz-pdm** [comment]
> instead of "pw-cli command to use." you could also write "Command to invoke pw-cli." 

Thank you for the suggestion, applied.

> a simple and fair way to prevent namespace collisions across MELPA (and hopefully elsewhere) is to ask that the package, variable names, and function names all use the same prefix.

OK. Since the only user friendly version of the entry command is `M-x pipewire', it determines the prefix and MELPA package name. I reorganized the package accordingly and all the reported prefix complaints should be hopefully gone.

**Comment by riscy** [comment]
Thank you!  I think this is ready to merge, but I'll leave a last couple of comments here in case they're helpful.

- I don't want to set a precedent here of people using `checkdoc-force-docstrings-flag: nil` to skip checkdoc checks, especially on public functions.  But I have been thinking of raising an issue on relaxing MELPA's checkdoc requirement for a while
- In some cases your `error`s look like they should be `user-error`s, e.g. `(error "Nothing to set a profile for here")` (where `user-error`s wont open a stack trace on the user)

**Comment by mz-pdm** [comment]
> * I don't want to set a precedent here of people using `checkdoc-force-docstrings-flag: nil` to skip checkdoc checks, especially on public functions.  But I have been thinking of raising an issue on relaxing MELPA's checkdoc requirement for a while

I think it would be helpful if checkdoc could be instructed to stop complaining about missing docstrings in private objects. Well, there is probably no formal definition of a private object in Elisp but the `prefix--` convention is used widely enough and is pretty unambiguous so I believe it could be honored.

> * In some cases your `error`s look like they should be `user-error`s, e.g. `(error "Nothing to set a profile for here")` (where `user-error`s wont open a stack trace on the user)

Good remark. Thank you for pointing this out, fixed.

**Pull request merged**
