### PR TITLE
Add helm-code-it-later

### PR DESCRIPTION
**Pull request by ccqpein**
### Brief summary of what the package does

The emacs interactive mode with [code-it-later](https://github.com/ccqpein/code-it-later-rs)

### Direct link to the package repository

https://github.com/ccqpein/code-it-later-mode

### Your association with the package

I am the maker and maintainer, and the user 001.

### Relevant communications with the upstream package maintainer

nil

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

`code-it-later-mode.el` with byte-compile using Emacs 28.1:

```
In code-it-later--prompt:
code-it-later-mode.el:263:85: Warning: Unused lexical argument `candidate'

In end of data:
code-it-later-mode.el:81:10: Warning: the function `helm-highlight-current-line' is not known to be defined.
code-it-later-mode.el:60:18: Warning: the function `helm-grep-split-line' is not known to be defined.
```

`code-it-later-mode.el` with checkdoc (0.6.2)

```
code-it-later-mode.el:117: Argument `keywords' should appear (as KEYWORDS) in the doc string
code-it-later-mode.el:160: Argument `dirs' should appear (as DIRS) in the doc string
code-it-later-mode.el:174: Argument `dirs' should appear (as DIRS) in the doc string
code-it-later-mode.el:196: Argument `ss' should appear (as SS) in the doc string
code-it-later-mode.el:209: Argument `dirs' should appear (as DIRS) in the doc string
code-it-later-mode.el:285: First sentence should end with punctuation
code-it-later-mode.el:285: First line should be capitalized
code-it-later-mode.el:285: Argument `arg' should appear (as ARG) in the doc string
code-it-later-mode.el:246: Messages should start with a capital letter
```

`code-it-later-mode.el` with package-lint (20230905.629)

```
1:0: warning: Including "Emacs" in the package summary is usually redundant.
1:0: warning: The package summary is too long. It should be at most 60 characters.
1:0: warning: The package summary should start with an uppercase letter or a digit.
1:105: warning: You should depend on (emacs "24.1") if you need lexical-binding.
9:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
82:1: warning: Closing parens should not be wrapped onto new lines.
88:2: warning: Closing parens should not be wrapped onto new lines.
113:3: warning: Closing parens should not be wrapped onto new lines.
157:1: warning: Closing parens should not be wrapped onto new lines.
171:1: warning: Closing parens should not be wrapped onto new lines.
202:4: warning: Closing parens should not be wrapped onto new lines.
221:6: warning: Closing parens should not be wrapped onto new lines.
226:4: warning: Closing parens should not be wrapped onto new lines.
264:11: warning: Closing parens should not be wrapped onto new lines.
281:1: warning: Closing parens should not be wrapped onto new lines.
```

Package and license:

- GPLv3

**Comment by riscy** [comment]
Thank you @ccqpein - I concur with @jcs090218 's output up there (but I also see `code-it-later-mode.el:290:16: Warning: the function 'helm-read-file-name' is not known to be defined.` on my byte-compile).  I can also add:

- The summary line for this file (first line of the file) uses markdown, but the summary line should be plaintext
- The `;;; Commentary` for this file is much wider than 80 characters and uses markdown, but markdown is not a common standard for Commentary - prefer plaintext e.g. use Emacs builtin packages as a model
- The fact that you rely on helm (and not a generic completion framework) suggests to me that you should name this `helm-code-it-later`
- Minor, but your indentation scheme is fairly nonstandard; I'd recommend `(setq indent-tabs-mode nil)` in your personal config and to re-indent your source code
- code-it-later-mode.el#L126: It's safer to sharp-quote function names; use `#'`
- code-it-later-mode.el#L135: It's safer to sharp-quote function names; use `#'`
- code-it-later-mode.el#L144: It's safer to sharp-quote function names; use `#'`
- code-it-later-mode.el#L168: It's safer to sharp-quote function names; use `#'`
- code-it-later-mode.el#L54: TODO: check for shell-quote-argument

**Comment by ccqpein** [comment]
@jcs090218 @riscy Thanks for you guys' replies. I fix the lint and documents to erase the warning. And re-indent the buffer. Except there is one error I don't know how to fix it. My emacs keep reminding me `Cannot open load file: No such file or directory, helm` in `(require 'helm)`.  And it gives me kind of `Warning: the function `helm-highlight-current-line' is not known to be defined` when I am trying to compile it. But it runs well in my local. Do you guys know what the problems about `(require 'helm)` ? Thanks!

**Comment by riscy** [comment]
It sounds like helm isn't on your `load-path` at compile time, but may be on your `load-path` during your usual Emacs operations.  You could check the value of that variable to debug.

**Comment by ccqpein** [comment]
@riscy Thanks for your advice. I add some require (`helm-mode` and `helm-grep`). And run 

```shell
emacs -batch -L ~/.emacs.d/straight/build/helm/ -L ~/.emacs.d/straight/build/helm-core/ -L ~/.emacs.d/straight/build/async/ -f batch-byte-compile ./code-it-later-mode.el
```

There are no errors appear anymore. Is this mode good enough to go? Thanks.

**Comment by riscy** [comment]
Thank you for that update.  I think the following still applies:

- The ;;; Commentary for this file is much wider than 80 characters and uses markdown, but markdown is not a common standard for Commentary - prefer plaintext e.g. use Emacs builtin packages as a model

Since your last changes, these also appear to be new issues I'm detecting:

- code-it-later-mode.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)
- Prefer equivalent recipe: `(code-it-later-mode :repo "ccqpein/code-it-later-mode" :fetcher github)` rather then specifying `*.el`

**Comment by ccqpein** [comment]
@riscy Thanks for your feedback. I just made the changes in my branch of melpa and `code-it-later-mode`. (it is the first time I heard the [SPDX-License-Identifier](https://spdx.dev/ids/), good to know).

**Comment by riscy** [comment]
Thank you, that puts the checklist behind us and I'm taking a deeper look at what this actually does.  I have a bit more feedback, hopefully you find it fair --

This looks like a "helm" application, and I think since that is your target you should join the ranks of other helm projects (e.g. have you seen things like [helm-swoop](https://github.com/emacsorphanage/helm-swoop) by considering a name like `helm-code-it-later`.

I'm having trouble understanding the true benefit of something like code-it-later [itself](https://github.com/ccqpein/code-it-later-rs) and its arguably "cryptic" `:=` markup, over writing e.g. `TODO: do this thing later`.  The latter is conventional (among other tags like FIXME, HACK, etc.), human-readable even if you haven't seen it before, [standardized to an extent](https://docs.astral.sh/ruff/rules/#flake8-todos-td), less likely to trip up code formatters (e.g. [E262](https://www.flake8rules.com/rules/E262.html)), and portable (inasmuch as it needs to be ported) to systems that haven't installed your code-it-later binary.  My impression is that a lot of what you're doing with these (listing them, removing them, etc.) could be done with existing tools or within Emacs lisp, and in more standard ways, making this fairly esoteric to me.  Hopefully none of that seems unfair, but I'd like to know what you think before merging this.

Some minor stuff I will add here --
- I neglected to check this after you updated me, but your indentation scheme continues to be nonstandard (a mix of tabs and spaces that go all over the place when one is using the default tab width of 8); I'd once again recommend `(setq indent-tabs-mode nil)` if you haven't done that already
- Minor: "Check the Github Repo `ccqpein/code-it-later-rs` for more details." in your commentary is silly - just give people a link, and they can use builtin editor commands to open the link directly...
- Minor: Trying to sneak past checkdoc by writing docstrings like `"Compare version. Argument FIRST . Argument SECOND."` (and worse) is a waste of everyone's time (yours too); I think you should either genuinely try to address checkdoc's feedback or else you should make a good faith argument that these functions don't need to document their arguments (which could certainly be within reason)

**Comment by ccqpein** [comment]
@riscy Thanks for your reply. Again, sorry for all the extra work on your side. This is my first emacs mode, and it's definitely different from configuring emacs. 

I think your advice about changing the name to helm-code-it-later is good. TBH, the mode I was learning to make this mode is from `helm-ag`. I believe helm-code-it-later is a good name. 

code-it-later was created to help me solve several issues I encounter while coding: 1. I cannot stop having random ideas unrelated to what I'm currently working on, so I jot them down in the code. 2. I sometimes get distracted and forget where I was in the code when I return. I found some of my friends have the same issues, so I created this tool. I use it almost every day in my work and personal time, just like Emacs. Then I realized jumping through files in emacs would be helpful, so I created this mode. 

Regarding other minor things: 
+ I genuinely changed the (setq indent-tabs-mode nil) last week after your advice and reformatted it. Perhaps I did something wrong. Let me research how to do it correctly.
+ You are correct. I’m going to make that change.
+ I will add those as well.

**Comment by riscy** [comment]
I don't doubt that you personally use this tool, and probably find it a great help.  But MELPA's goal is also not necessarily indexing all elisp ever written, and I had a few concerns I wrote above (in the paragraph starting "I'm having trouble understanding the true benefit") -- e.g. convention/standardization, human-readability, portability, incompatibility with code formatters -- that I feel have gone unresponded-to so far.

**Comment by ccqpein** [comment]
Thank you for your prompt response. I've noticed that certain code reformatting tools might modify the positioning of the ":=" character, which initially caused me some concern. It seems that this tool does not align with the conventional "official" markers such as TODO and FIXME. Rather, it serves a less formal purpose, allowing for the spontaneous recording of ideas and the tidying up of loose ends. The keyword functionality is not intended for integration with workplace tools like JIRA or CI/CD scanners, but is instead a personal aid for developers. 

In my opinion, as long as it functions as intended, the reformatting issue can be overlooked, although I realize that this sentiment may not be shared by all—different teams or developers might find it unacceptable.

As for readability, I believe there is little difference from standard comments, aside from their placement after the ":=" symbols. My personal use case involves placing markers within files during debugging to navigate through complex repositories with numerous subpackages, and I remove these markers once the task is completed.

Regarding portability, my comparison was to helm-ag, which acts as an interface for binary execution. Just as I wouldn't install helm-ag without the 'ag' executable on my local machine, I see a similar approach being applicable here.

@riscy, I hope my explanation clarifies my perspective. Your concerns have actually sparked a few ideas for enhancing both the code-it-later and helm-code-it-later tools.

Best regards.

**Comment by riscy** [comment]
> this tool does not align with the conventional "official" markers such as TODO and FIXME. Rather, it serves a less formal purpose, allowing for the spontaneous recording of ideas and the tidying up of loose ends.

Thanks for taking the time for a thoughtful response.  "TODOs" and "FIXMEs" are conventional, but they are by no means "formal" and can easily accommodate your stated use case ("the spontaneous recording of ideas and the tidying up of loose ends").

I think this would be a good addition to the ecosystem if you targeted TODOs, FIXMEs, HACKs, IDEAs, etc.  But if this tool is only going to be about doing bookkeeping over your personal choice of `:=` symbols, then I think we should hold off on merging this into the MELPA index.

**Comment by ccqpein** [comment]
@riscy Thank you for your reply. It is true that this might be more suited for personal use rather than for widespread adoption. I am closing this PR until it is ready for broader and more general application. Thank you for your patience and valuable insights. They have been greatly helpful and enlightening in my progress.

**Comment by riscy** [comment]
Thanks so much for being understanding - and of course when this is ready for broader application I'll be happy to look again. :)

**Pull request closed without merging**
