### PR TITLE
Add recipe for Dired auto readme

### PR DESCRIPTION
**Pull request by amno1**
### Brief summary of what the package does

Display Readme files when available in Dired buffers.

### Direct link to the package repository

https://github.com/amno1/dired-auto-readme

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

 **None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`dired-auto-readme.el` with byte-compile using Emacs 29.1:
```
dired-auto-readme.el:154:10: Warning: the function `gfm-view-mode' is not known to be defined.
dired-auto-readme.el:128:8: Warning: the function `dired-revert' is not known to be defined.
dired-auto-readme.el:82:22: Warning: the function `dired-file-name-at-point' is not known to be defined.
dired-auto-readme.el:81:15: Warning: the function `dired-next-line' is not known to be defined.
dired-auto-readme.el:64:4: Warning: the function `org-fold-initialize' is not known to be defined.
```

`dired-auto-readme.el` with checkdoc 0.6.2 (fix *within reason*):
```
dired-auto-readme.el:73: Argument `v' should appear (as V) in the doc string
```

**Comment by amno1** [comment]
Ok, requires; should have tested in Emacs -q.

See now if it works for you.

Thanks for looking at it.

**Comment by riscy** [comment]
I'm seeing this in the latest --

`dired-auto-readme.el` with byte-compile using Emacs 29.2:
```
dired-auto-readme.el:78:4: Warning: `font-lock-default-fontify-region' called with 2 arguments, but requires 3
```
I guess there's an argument called LOUDLY at the end there. :)

**Comment by amno1** [comment]
Interesting; I was quite sure the thrid argument was optional. But no probs; fixed.

Thanks.

**Comment by riscy** [comment]
No problem.   This is a cool idea - thanks again!

**Comment by amno1** [comment]
Thank you very much for your patience. Sometimes I am just blind and don't see some details, as seen above, so I needed a good review.

**Pull request merged**
