### PR TITLE
fix ordering in builder Dockerfile

### PR DESCRIPTION
**Pull request by milkypostman**
to satisfy the ordering we move curl to the first in the list.

### CODE REVIEW

**Comment by Silex** [comment]
I'm a fan of multilines lile https://github.com/Silex/docker-emacs/blob/master/templates/ubuntu/18.04/Dockerfile for long lists of dependencies :wink: 

I discovered that alphabetically sorting things where it makes sense is quite a time saver, no need to think where to go.

**Comment by Silex** [comment]
p.s. your commit message should start with `Fix` instead of `fix` :stuck_out_tongue_closed_eyes:

**Comment by milkypostman** [comment]
Then I’d have to hit the shift key! I’d rather save some time.

**Comment by Silex** [comment]
I guess you were joking, but just in case some future readers fall on this, here's some lecture :smiley: 

https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html 
https://github.com/erlang/otp/wiki/writing-good-commit-messages
https://chris.beams.io/posts/git-commit/

**Comment by milkypostman** [comment]
I prescribe to this professionally and should take the same care with this project. 

Although in general I’m not a huge fan of capitalization. 

Good links though.

**Pull request merged**
