### PR TITLE
Add vc-msg

### PR DESCRIPTION
**Pull request by redguardtoo**
### Brief summary of what the package does

Show commit message of current line

### Direct link to the package repository

https://github.com/redguardtoo/vc-msg

### Your association with the package

I'm the developer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, and sorry for the slow reply. Quick feedback:
- Missing dependency on `cl-lib`.
- The various `defvar`s that are for end-users to modify should be `defcustoms` instead, with a containing `defgroup`.
- Typo: "messeage"
- Why all the code to determine the current VCS? `vc.el` provides this for you.
- Similarly, doesn't `vc-annotate` give you all the information you need for this library?

**Comment by redguardtoo** [comment]
Thanks. I fixed typo and replace `defvar` with `defcustom`, now `vc-msg` requires `Emacs 24.3` which has `cl-lib` built in.

The purpose of this packages is to give user full freedom to support any VCS (for example, Perforce support is not built into `vc.el`). I have to write new code to support Perforce. Other open source VCS is just one liner like `(locate-dominating-file default-directory algorithm)`, it will not make my code cleaner to use `vc.el`

similar reason for `vc-annotate`. for example, user can customize `git blame` flag like `-M`.

This package is like `git-messenger` but supports any alien VCS.

**Comment by redguardtoo** [comment]
@tarsius , anything else to change before being merged?

**Comment by redguardtoo** [comment]
Thanks

**Pull request merged**
