### PR TITLE
add: rutils

### PR DESCRIPTION
**Pull request by ShuguangSun**
### Brief summary of what the package does

R utilities with transient.

### Direct link to the package repository

https://github.com/ShuguangSun/rutils.el

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, and for your close adherence to the checklist.  Some quick feedback:

- I notice your "main" file is rutils.el, whose summary line says "General stuffs" which would probably not look great in the MELPA package index :) 
- `rutils-send--command-with-project` (for example) should be `rutils--send-command-with-project` -- the double hyphenation marking private functions/variables should always come after the package name, I'm fairly sure
- rutils-site.el appears to serve no purpose -- I suggest deleting it
- The variable `rutils-using-compile-p` doesn't appear to be used anywhere
- This is a non-blocker, but I'd recommend spellchecking your docstrings (e.g. "avalability frist", "non-nill")

**Comment by ShuguangSun** [comment]
Thanks. Well accepted. 

I would like to keep rutile-site.el which is to help those whose don't use melpa, and they can just `(require 'rutils-site)` to install all features.

**Comment by riscy** [comment]
> those whose don't use melpa ... can just (require 'rutils-site) to install all features.

Ah, I see what you're after.  I'm not sure how MELPA/non-MELPA users would come into it, but it would be more consistent/intuitive if the user could just `(require 'rutils)` instead, wouldn't you agree?  As I look over the files, you seem to have set up rutils.el as a collection of private helper functions, which I think is an unusual role for your main file to take.

I'd suggest moving rutils.el to a file called rutils-helpers.el (or rutils-lib.el or whatever you like) and then putting the contents of rutils-site.el in rutils.el.

**Comment by ShuguangSun** [comment]
I refactored the names and followed your suggestion.

**Comment by riscy** [comment]
Thank you for accommodating. :)  I think this is about ready to go, we just have:

byte-compile (using Emacs 27.1):
```
rutils-lib.el:93:1:Warning: the function `rutils-renv--assert' is not known to
    be defined.
```
I suspect in this case rutils-env--assert should be moved into rutils-lib.el too.

checkdoc (using version 0.6.2):
```
Warning (emacs): 
rutils.el:37: The footer should be: (provide 'rutils)\n;;; rutils.el ends here
```

package-lint (using version 20210528.2348):
```
1 issue found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
```
And those last two are just an update of the summary line/boilerplate.

**Comment by ShuguangSun** [comment]
I have question. I have a defgroup in rutils-lib as below which will be used in other files. However, package lint report an error about the name start word of the group. Is there any suggestion about it?

```
(defgroup rutils nil
  "R utilities with transient menu."
  :group 'rutils
  :prefix "rutils")
```

```
rutils-lib.el:39:0: error: "rutils" doesn't start with package's prefix "rutils-lib".
```

**Comment by riscy** [comment]
See the documentation for `package-lint-main-file`.  One way to make use of this variable is to add the following somewhere in each of your secondary files (just make sure that it isn't inside your `;;; Commentary` block):

```elisp
;; Local variables:
;; package-lint-main-file: "my-main-file.el"
;; end:
```

**Comment by ShuguangSun** [comment]
Thanks. Now it is ready.

**Comment by riscy** [comment]
Thanks!  Taking another look now, the byte-compiler's catching a couple funcalls that may be issues:

byte-compile (using Emacs 27.1):
```
rutils-packrat.el:126:4:Warning: rutils-lib--send-command-with-project called
    with 2 arguments, but requires 3-4
In rutils-packrat-disable-run:
rutils-packrat.el:224:4:Warning: rutils-lib--send-command-with-project called
    with 2 arguments, but requires 3-4
```

byte-compile (using Emacs 27.1):
```
rutils-renv.el:175:4:Warning: rutils-lib--send-command-with-project called
    with 2 arguments, but requires 3-4
```

**Comment by ShuguangSun** [comment]
Sorry for my mistake. Now I fixed. I'll add tests in the future.

**Comment by riscy** [comment]
Looks great now.  Thanks for submitting this.

**Pull request merged**
