### PR TITLE
Add tikz package

### PR DESCRIPTION
**Pull request by emiliotorres**
### Brief summary of what the package does

 A minor mode to edit TikZ pictures.

### Direct link to the package repository

https://github.com/emiliotorres/tikz

### Your association with the package

Author. Maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [ x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [ x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x] My elisp byte-compiles cleanly
- [ x] `M-x checkdoc` is happy with my docstrings
- [ x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Looks good.  Mostly just a note below to add a LICENSE file to the repository.

### tikz.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200616.2257):
- No issues!

Suggestions/experimental static checks:
- tikz.el#L222: It's safer to sharp-quote function names; use `#'`
- tikz.el#L209: It's safer to sharp-quote function names; use `#'`

### Loadability ###

Verifying ability to #'load each file:
```
Loading tikz.el
Done.
```

### Package ###

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- Add a LICENSE or COPYING file to the repository

**Comment by emiliotorres** [comment]
Thank you.

Added a LICENSE to github
https://github.com/emiliotorres/tikz/commit/fcd54186bf6e231e17cad4fb94eb347db047f96a

Minor updated in recipe
https://github.com/emiliotorres/melpa/commit/a77cf1a4a7a420b0cfc09a393858daf5ae5a13ab

Best regards.

**Comment by riscy** [comment]
Hi - your PR seems to also add the source code for tikz.el, which is unnecessary.  I removed it in an earlier commit, but then you added it back.  Can you make sure it's removed?

**Comment by emiliotorres** [comment]
I am sorry. I did not know how it works.
I have removed it (file tikz.el)

https://github.com/emiliotorres/melpa/commit/96627bb6158da66d18ae4b3166073fcc5f8cfd7d

**Comment by riscy** [comment]
All good. :)

Here are a handful of minor tips, but nothing worth blocking on in this one:

- 194:18: warning: Closing parens should not be wrapped onto new lines.
- tikz.el#L220: It's safer to sharp-quote function names; use `#'`
- tikz.el#L207: It's safer to sharp-quote function names; use `#'`

Welcome to MELPA. :)

**Pull request merged**
