### PR TITLE
Update recipe for Chronometrist to use GitHub, exclude new optional file

### PR DESCRIPTION
**Pull request by contrapunctus-1**
### Brief summary of what the package does
A time tracker with useful displays of data

### Direct link to the package repository
https://github.com/contrapunctus-1/chronometrist

### Your association with the package
Author

### Relevant communications with the upstream package maintainer
**None needed**

### Checklist
Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
  - false positive in chronometrist-sexp.el
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by contrapunctus-1** [comment]
I'm strongly considering moving the optional package chronometrist-goals (for which I'll soon be submitting a recipe PR) to its own repository, so that it can have versioned releases independently of Chronometrist. The recipe here will probably work all the same, but for sake of elegance I'll change the file specification soon.

**Comment by tarsius** [comment]
@riscy Did you somehow verify that they are who they claim they are?

I usually ask that the person who claims a package in a new location proofs that they also own the old location by linking from the latter to the former or something like that.

**Comment by riscy** [comment]
The same user opened the original recipe, but that would've been more thorough -- good point.

**Comment by contrapunctus-1** [comment]
@tarsius @riscy Done! 😀
https://framagit.org/contrapunctus/chronometrist

**Comment by tarsius** [comment]
Thank you!

**Pull request merged**
