### PR TITLE
Add compiler-explorer recipe

### PR DESCRIPTION
**Pull request by mkcms**
### Brief summary of what the package does

This package provides a simple client for [compiler-explorer](https://godbolt.org/) service

### Direct link to the package repository

https://github.com/mkcms/compiler-explorer.el

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

### compiler-explorer.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
compiler-explorer.el:90: All variables and subroutines might as well have a documentation string
Warning (emacs): 
compiler-explorer.el:93: All variables and subroutines might as well have a documentation string
Warning (emacs): 
compiler-explorer.el:97: Argument `args' should appear (as ARGS) in the doc string
Warning (emacs): 
compiler-explorer.el:229: All variables and subroutines might as well have a documentation string
Warning (emacs): 
compiler-explorer.el:287: All variables and subroutines might as well have a documentation string
Warning (emacs): 
compiler-explorer.el:326: All variables and subroutines might as well have a documentation string
Warning (emacs): 
compiler-explorer.el:456: All variables and subroutines might as well have a documentation string
Warning (emacs): 
compiler-explorer.el:526: All variables and subroutines might as well have a documentation string
Warning (emacs): 
compiler-explorer.el:532: All variables and subroutines might as well have a documentation string
Warning (emacs): 
compiler-explorer.el:559: All variables and subroutines might as well have a documentation string
Warning (emacs): 
compiler-explorer.el:570: All variables and subroutines might as well have a documentation string
```

package-lint (using version 20200906.512):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- compiler-explorer.el#L597: Avoid adding hooks on import; this may belong in your `;;; Commentary`?

**Comment by mkcms** [comment]
I've updated the repository and fixed most of the warnings.

**Comment by riscy** [comment]
Thank you very much.  I realize it sounds pedantic, but the remaining warnings look easy to fix.  Generally it's easier for MELPA maintainers to simply be strict about (most of) the checkdoc lints unless there is a bug with checkdoc or similar.

Otherwise I'm looking at the code and this look good.  Should be an easy merge after.

**Comment by mkcms** [comment]
Chris,

I just pushed a commit which fixes all the checkdoc warnings reported by flymake and `M-x checkdoc` on Emacs 26.3.50:

```
Buffer comments and tags:  Ok
Documentation style:       Ok
Message/Query text style:  Ok
Unwanted Spaces:           Ok
```

>  I realize it sounds pedantic

As a programmer I think documentation is very important, but sometimes it is redundant, e.g. when the programmer follows standard conventions.

**Comment by riscy** [comment]
It may be you're on an earlier version of checkdoc (you can check the variable `checkdoc-version`, which is likely since I'm running Emacs 27.1.  Probably the latest checkdoc is able to recognize `cl-defun` as a defun pattern.  You could just write (respectively):

- "Handle the compilation response contained in DATA."
- "Handle the execution response contained in DATA."

**Comment by mkcms** [comment]
I pushed a commit which adds a docstring to those functions.

> which is likely since I'm running Emacs 27.1

I use a stable version of Debian (Buster), and the Emacs version there is 26.1.
Maybe CONTRIBUTING.org should mention that you need to test with latest Emacs?

**Comment by riscy** [comment]
>  Maybe CONTRIBUTING.org should mention that you need to test with latest Emacs?

That's a good point, although freely adding provisos into that document can reduce its readability.  If it comes up again we definitely should.  It's an ambition that we have CI do these things for us instead.

In any case, thanks for your patience -- looks good to go.

**Pull request merged**
