### PR TITLE
Add recipe for help-find

### PR DESCRIPTION
**Pull request by duncanburke**
### Brief summary of what the package does

Additional help functions for working with keymaps.

This is especially useful when working with a highly customized set of keybindings. It is common both in Emacs itself and in external packages for assumptions to be made about keybinding defaults. This package provides functions to find which keymaps contain bindings for a particular key sequence or to a particular function.

### Direct link to the package repository

https://github.com/duncanburke/help-find

### Your association with the package

Creator

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, works like a charm.  Quick feedback:

- Have you had a chance to compare to [helpful](https://github.com/Wilfred/helpful/tree/7e4b1f0d5572a4e2b8ee7a9b084ef863d0315a73) which I believe also implements some of this? (e.g. `helpful-command`)
- I notice this in my `*Messages*` buffer when I run `help-find-function`: "Invalid face reference: help-key-binding [3 times]"
- When you propertize you set both `face` and `font-lock-face` but I think you can just get away with the latter when the buffer is in `help-mode`

**Comment by riscy** [comment]
One last thing I forgot to mention regarding help-find.el#L3: Have you done the paperwork to assign this copyright?  Otherwise the copyright remains your own.

**Comment by duncanburke** [comment]
Thanks for the feedback.

> Have you had a chance to compare to helpful

I hadn't seen helpful. Thanks for pointing that out. You're right, there does seem to be some overlap with helpful-command. I think this package is still not redundant: firstly because I'm not aware of anything else like `help-find-keybinding` being available; and secondly because I've written it to imitate the style of Emacs' inbuilt help and to integrate well with it. Helpful very much seems to have its own style. For example, `help-find-function` provides links to the keymaps (i.e using `describe-keymap`) rather than just listing them.

> I notice this in my *Messages* buffer when I run help-find-function: "Invalid face reference: help-key-binding [3 times]"

I've fixed this, and two other issues in recent commits. `help-key-binding` and `describe-keymap` are only in emacs master. `describe-keymap` is also available from `help-fns+`, which used to be in ELPA but appears to have been removed from there when it was merged into Emacs. It's still floating around on the Emacs wiki, though. In both cases I've added fallback behavior for when they're not available.

I tested it in emacs-25.2 and have updated `Package-Requires` accordingly.

There was also another spurious message left over from debugging that I've removed.

> When you propertize you set both face and font-lock-face but I think you can just get away with the latter when the buffer is in help-mode

That seems very sensible. I cannot see any good reason for setting both, but that's how it's done in [help-command-keys](https://github.com/emacs-mirror/emacs/blob/54039d721c5b7fd210a79dc641914cba8fc82185/lisp/help.el#L1132).

> One last thing I forgot to mention regarding help-find.el#L3: Have you done the paperwork to assign this copyright? Otherwise the copyright remains your own.

I have not done that yet. I was planning on doing that once -- if -- this was accepted into MELPA. I would like to work towards getting this upstreamed into Emacs, but it seemed like a good first step to get some feedback and make sure it wasn't redundant due to the existence of another package. I didn't want to start the process of registering the copyright assignment until I was sure it would be accepted into a package repository, but I also thought that starting off with the copyright assignment would smooth out the eventual process of upstreaming it.

From what I understand, not having formally registered the copyright assignment simply means that it may or may not have the force of law, which would only actually be relevant if it ended up in court. Obviously, though the FSF would require that paperwork to actually upstream it.

**Comment by riscy** [comment]
>  I've written it to imitate the style of Emacs' inbuilt help and to integrate well with it.

This makes sense, thanks.  In light of that I guess the discussion around `propertize` above is moot as well.

> From what I understand, not having formally registered the copyright assignment simply means that it may or may not have the force of law, which would only actually be relevant if it ended up in court.

I agree, but you could say the same thing about licenses.  I'm only speaking for myself but I'd rather the stuff we index in MELPA is accurate about these things -- at least to the extent we're able to be.  Personally, I'd rather someone not state copyrights in my (or my organization's) name without coordinating with me first.

**Comment by duncanburke** [comment]
All right, I see your point. I've updated the copyright statements accordingly.

**Comment by riscy** [comment]
Thanks for understanding.  And, welcome to MELPA!

**Pull request merged**
