### PR TITLE
Add recipe for bqn-mode

### PR DESCRIPTION
**Pull request by larstvei**
### Brief summary of what the package does

Emacs mode for the [BQN](https://mlochbaum.github.io/BQN/) programming language.

### Direct link to the package repository

https://github.com/museoa/bqn-mode

### Your association with the package

Contributor.

### Relevant communications with the upstream package maintainer

museoa/bqn-mode#1

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`bqn-backslash.el` with checkdoc 0.6.2:
```
bqn-backslash.el:0: The first line should be of the form: ";;; package --- Summary"
bqn-backslash.el:0: You should have a section marked ";;; Commentary:"
bqn-backslash.el:7: You should have a section marked ";;; Code:"
bqn-backslash.el:46: The footer should be: (provide 'bqn-backslash)\n;;; bqn-backslash.el ends here
bqn-backslash.el:24: All variables and subroutines might as well have a documentation string
bqn-backslash.el:36: All variables and subroutines might as well have a documentation string
```

`bqn-backslash.el` with package-lint 20221003.1636:
```
1 issue found:
1:8: warning: You should depend on (emacs "24.1") if you need lexical-binding.
```

`bqn-comint.el` with checkdoc 0.6.2:
```
bqn-comint.el:33: First sentence should end with punctuation
bqn-comint.el:46: Argument `start' should appear (as START) in the doc string
bqn-comint.el:83: Argument `start' should appear (as START) in the doc string
bqn-comint.el:110: First sentence should end with punctuation
bqn-comint.el:115: First sentence should end with punctuation
bqn-comint.el:120: First sentence should end with punctuation
```

`bqn-comint.el` with package-lint 20221003.1636:
```
5 issues found:
1:45: warning: You should depend on (emacs "24.1") if you need lexical-binding.
35:0: error: "*bqn-process-buffer-name*" doesn't start with package's prefix "bqn".
61:0: error: "run-bqn" doesn't start with package's prefix "bqn".
68:5: error: You should depend on (emacs "24.1") if you need `pop-to-buffer-same-window'.
132:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
```

`bqn-comint.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-comint.el#L74: It's safer to sharp-quote function names; use `#'`
- bqn-comint.el#L140: It's safer to sharp-quote function names; use `#'`
- bqn-comint.el#L140: Loading a package should rarely add hooks
```

`bqn-glyphs.el` with package-lint 20221003.1636:
```
2 issues found:
36:0: error: "*bqn-glyphs-buffer-name*" doesn't start with package's prefix "bqn".
70:3: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
```

`bqn-help.el` with checkdoc 0.6.2:
```
bqn-help.el:0: You should have a section marked ";;; Commentary:"
bqn-help.el:105: The footer should be: (provide 'bqn-help)\n;;; bqn-help.el ends here
bqn-help.el:38: First sentence should end with punctuation
bqn-help.el:47: First sentence should end with punctuation
bqn-help.el:55: First sentence should end with punctuation
bqn-help.el:59: First sentence should end with punctuation
bqn-help.el:73: First sentence should end with punctuation
bqn-help.el:83: First sentence should end with punctuation
```

`bqn-help.el` with package-lint 20221003.1636:
```
9 issues found:
1:41: warning: You should depend on (emacs "24.1") if you need lexical-binding.
61:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
62:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
66:0: error: "*bqn-help-documentation-buffer-name*" doesn't start with package's prefix "bqn".
70:3: error: You should depend on (emacs "25.1") or the seq package if you need `seq-filter'.
76:3: error: You should depend on (emacs "26.1") if you need `if-let*'.
86:5: error: You should depend on (emacs "26.1") if you need `if-let*'.
93:11: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
98:11: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
```

`bqn-help.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-help.el#L79: No `format` required; `message` takes an f-string
- bqn-help.el#L80: No `format` required; `message` takes an f-string
- bqn-help.el#L101: No `format` required; `message` takes an f-string
- bqn-help.el#L95: `concat` may be unneeded; `insert` can take multiple arguments
```

`bqn-input.el` with checkdoc 0.6.2:
```
bqn-input.el:0: The first line should be of the form: ";;; package --- Summary"
bqn-input.el:0: You should have a section marked ";;; Commentary:"
bqn-input.el:6: You should have a section marked ";;; Code:"
bqn-input.el:50: The footer should be: (provide 'bqn-input)\n;;; bqn-input.el ends here
bqn-input.el:20: All variables and subroutines might as well have a documentation string
bqn-input.el:25: All variables and subroutines might as well have a documentation string
bqn-input.el:37: Argument `symbol' should appear (as SYMBOL) in the doc string
bqn-input.el:42: Second line should not have indentation
bqn-input.el:42: First line is not a complete sentence
```

`bqn-input.el` with package-lint 20221003.1636:
```
1 issue found:
1:8: warning: You should depend on (emacs "24.1") if you need lexical-binding.
```

`bqn-input.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-input.el#L12: There is no need to quote lambdas (neither #' nor ')
```

`bqn-keyboard.el` with package-lint 20221003.1636:
```
2 issues found:
26:0: error: "*bqn-keymap-buffer-name*" doesn't start with package's prefix "bqn".
61:3: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
```

`bqn-mode.el` with package-lint 20221003.1636:
```
4 issues found:
1:43: warning: You should depend on (emacs "24.1") if you need lexical-binding.
43:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
44:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
45:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
```

`bqn-symbols-doc.el` with checkdoc 0.6.2:
```
bqn-symbols-doc.el:3204: First sentence should end with punctuation
bqn-symbols-doc.el:3208: Second line should not have indentation
bqn-symbols-doc.el:3208: First line is not a complete sentence
bqn-symbols-doc.el:3216: First sentence should end with punctuation
bqn-symbols-doc.el:3220: First sentence should end with punctuation
bqn-symbols-doc.el:3224: First sentence should end with punctuation
bqn-symbols-doc.el:2121: White space found at end of line
```

`bqn-symbols-doc.el` with package-lint 20221003.1636:
```
5 issues found:
1:67: warning: You should depend on (emacs "24.1") if you need lexical-binding.
20:10: error: You should depend on (emacs "24.4") if you need `subr-x'.
3196:0: warning: Closing parens should not be wrapped onto new lines.
3205:3: error: You should depend on (emacs "24.4") if you need `hash-table-keys'.
3210:3: error: You should depend on (emacs "25.1") if you need `when-let'.
```

`bqn-symbols.el` with checkdoc 0.6.2:
```
bqn-symbols.el:0: The first line should be of the form: ";;; package --- Summary"
bqn-symbols.el:0: You should have a section marked ";;; Commentary:"
bqn-symbols.el:3: You should have a section marked ";;; Code:"
bqn-symbols.el:146: The footer should be: (provide 'bqn-symbols)\n;;; bqn-symbols.el ends here
```

`bqn-symbols.el` with package-lint 20221003.1636:
```
2 issues found:
1:8: warning: You should depend on (emacs "24.1") if you need lexical-binding.
144:23: warning: Closing parens should not be wrapped onto new lines.
```

`bqn-syntax.el` with checkdoc 0.6.2:
```
bqn-syntax.el:0: The first line should be of the form: ";;; package --- Summary"
bqn-syntax.el:0: You should have a section marked ";;; Commentary:"
bqn-syntax.el:6: You should have a section marked ";;; Code:"
bqn-syntax.el:106: The footer should be: (provide 'bqn-syntax)\n;;; bqn-syntax.el ends here
```

`bqn-syntax.el` with package-lint 20221003.1636:
```
1 issue found:
1:8: warning: You should depend on (emacs "24.1") if you need lexical-binding.
```

Package and license:
- Other (via API)
  - Try to use a standard license file format
    See: https://github.com/licensee/licensee
- unknown license -- bqn-backslash.el: (no header)
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to bqn-backslash.el
- unknown license -- bqn-comint.el: BQN command interface
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to bqn-comint.el
- unknown license -- bqn-glyphs.el: BQN glyph reference
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to bqn-glyphs.el
- unknown license -- bqn-help.el: Help for BQN mode
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to bqn-help.el
- unknown license -- bqn-input.el: (no header)
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to bqn-input.el
- unknown license -- bqn-keyboard.el: BQN Keyboard Reference
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to bqn-keyboard.el
- bqn-mode-pkg.el -- consider excluding; MELPA creates one
- unknown license -- bqn-mode.el: Emacs mode for BQN
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to bqn-mode.el
- unknown license -- bqn-symbols-doc.el: Documentation table for BQN symbols
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to bqn-symbols-doc.el
- unknown license -- bqn-symbols.el: (no header)
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to bqn-symbols.el
- unknown license -- bqn-syntax.el: (no header)
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to bqn-syntax.el

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out!

**Comment by svmhdvn** [comment]
Committed https://github.com/museoa/bqn-mode/pull/17 which should fix a lot of the above feedback. What's left to do before getting this package ready for MELPA?

**Comment by riscy** [comment]
Thanks for accommodating.  Looking much improved, but there are a couple of outstanding issues, which can happen with big code changes.  Here's the latest --

`bqn-comint.el` with package-lint 20221003.1636:
```
3 issues found:
1:42: warning: You should depend on (emacs "24.1") if you need lexical-binding.
74:5: error: You should depend on (emacs "24.1") if you need `pop-to-buffer-same-window'.
138:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
```

`bqn-comint.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-comint.el#L80: It's safer to sharp-quote function names; use `#'`
- bqn-comint.el#L146: It's safer to sharp-quote function names; use `#'`
- bqn-comint.el#L146: Loading a package should rarely add hooks
```

`bqn-glyph-mode.el` with package-lint 20221003.1636:
```
1 issue found:
79:3: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
```

`bqn-help.el` with package-lint 20221003.1636:
```
8 issues found:
1:42: warning: You should depend on (emacs "24.1") if you need lexical-binding.
65:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
66:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
74:3: error: You should depend on (emacs "25.1") or the seq package if you need `seq-filter'.
80:5: error: You should depend on (emacs "26.1") if you need `if-let*'.
90:5: error: You should depend on (emacs "26.1") if you need `if-let*'.
97:11: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
102:11: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
```

`bqn-help.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-help.el#L83: No `format` required; `message` takes an f-string
- bqn-help.el#L84: No `format` required; `message` takes an f-string
- bqn-help.el#L105: No `format` required; `message` takes an f-string
- bqn-help.el#L99: `concat` may be unneeded; `insert` can take multiple arguments
```

`bqn-key-prefix.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-key-prefix.el#L1: `lexical-binding` must be on the end of the first line
```

`bqn-keymap-mode.el` with package-lint 20221003.1636:
```
1 issue found:
67:3: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
```

`bqn-mode-map.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-mode-map.el#L25: There is no need to quote lambdas (neither #' nor ')
- bqn-mode-map.el#L1: `lexical-binding` must be on the end of the first line
```

`bqn-mode.el` with package-lint 20221003.1636:
```
4 issues found:
1:43: warning: You should depend on (emacs "24.1") if you need lexical-binding.
44:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
45:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
46:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
```

`bqn-symbols-doc.el` with package-lint 20221003.1636:
```
4 issues found:
1:67: warning: You should depend on (emacs "24.1") if you need lexical-binding.
22:10: error: You should depend on (emacs "24.4") if you need `subr-x'.
3206:3: error: You should depend on (emacs "24.4") if you need `hash-table-keys'.
3211:3: error: You should depend on (emacs "25.1") if you need `when-let'.
```

`bqn-symbols.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-symbols.el#L1: `lexical-binding` must be on the end of the first line
```

`bqn-syntax.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-syntax.el#L12: Triple semicolons `;;;` are usually for section headings
- bqn-syntax.el#L13: `lexical-binding` must be on the end of the first line
```

Package and license:
- Other (via API)
  - Try to use a standard license file format
    See: https://github.com/licensee/licensee
    e.g. https://www.gnu.org/licenses/gpl-3.0.txt
- bqn-mode-pkg.el -- consider excluding; MELPA creates one

**Comment by svmhdvn** [comment]
Melpazoid has been added to the project so it should come back clean now. Ready for re-review.

**Comment by riscy** [comment]
Thanks!  I can tell a ton of effort has gone into this.

Merging now, but I'll leave a final very minor note that the variable name `bqn-comint-*process-buffer-name*` feels a bit atypical.  I believe package-lint doesn't nag about this to allow `*` to appear in the special versions of functions like `let*`, or in functions that use `*` as a literal reference (arithmetic, pointers).

**Comment by svmhdvn** [comment]
Committed in https://github.com/melpa/melpa/commit/17711a1d747932e9be1ccd1d0a3adb64fa6cf1ef. This issue can be closed as fixed now.

**Pull request merged**
