### PR TITLE
Add org-superstar-mode recipe

### PR DESCRIPTION
**Pull request by integral-dw**
### Brief summary of what the package does
  Prettify headings and plain lists in org-mode.  This package is a
  direct descendant of [‘org-bullets’](https://github.com/sabof/org-bullets), with most of the code base
  completely rewritten.
  Currently, this package supports:
 * Prettifying org header lines by:
   + replacing trailing bullets by UTF-8 bullets
   + hiding leading stars or customizing their look
   + applying a custom face to the header bullet
   + applying a custom face to the leading bullets
   + using double-bullets for inline tasks (see org-inlinetask.el)
 * Prettifying org plain list bullets by:
   + replacing each bullet type (*, + and -) with UTF-8 bullets
   + applying a custom face to item bullets
 * Gracefully degrading features when viewed from terminal

### Direct link to the package repository
https://github.com/integral-dw/org-superstar-mode

### Your association with the package
I am the author and maintainer, however, the package is based on sabof's org-bullets package

### Relevant communications with the upstream package maintainer
I have contacted sabof about a week ago.  Sadly I have not received a response yet.

Regarding my stance on the subject of adopting org-bullets from the orphanage, please see
[this entry from the org-mode mailing list](https://lists.gnu.org/archive/html/emacs-orgmode/2020-02/msg00076.html)
### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
Cool!

Curious, you mention tests, but I don't see any in the repo.  Did you forget to commit them or something?

**Comment by dw-github-mirror** [comment]
They are currently outside of the repo, but I gladly add them.
However, they are a rather messy, because I have no experience with testing facilities.  My current approach for testing the side effects caused by `compose-region` is a simple .el where I can combinatorically go through plausible configurations of custom variables and compare the result produced with my expectations.  I am not sure that this is generally helpful for other people, so I would be grateful for any pointers.  Should I commit the hacky version for the time being?

**Comment by dw-github-mirror** [comment]
@tarsius Thanks for fixing the title! I noticed that it fell out of line with the other commits, sorry.  Still a bit inexperienced with Git workflow.

**Comment by tarsius** [comment]
No problem.

I was also wondering: why such a strange username?

Are you aware that you can also use a git (or mercurial) repository used elsewhere? You don't have to mirror it to github. But even if you did mirror here for some reason, I would still suggest a more "human" user name. :wink:

**Comment by dw-github-mirror** [comment]
Good question.  
The nigh-verbatim thought process behind that was
> Taken, taken, taken, too specific..
> I still have my reservations about Github anyway, how can I signify that this may not be my main account in the long run?

My main reason to put my stuff on Github first was that it's more likely many people will read my code here. I do consider setting up my own git/SVN server in the long run, however. :sweat_smile:

**Comment by tarsius** [comment]
> how can I signify that this may not be my main account in the long run?

Well for obvious reasons Github doesn't make that easy. :frowning: 

I wouldn't worry about it now and just pick a friendly name. If/when you move you can replace your repositories with stubs that only contain README.md files that point at the new location if you want to maximize the changes of users noticing the migration.

> my own git/SVN server

Melpa doesn't support subversion.

**Comment by dw-github-mirror** [comment]
>Melpa doesn't support subversion

I know, sadly. 
>I wouldn't worry about it now and just pick a friendly name.

I'll try think of one!

Is there anything else I can do to help you guys?  I don't want to cause any more work than necessary.

**Comment by dw-github-mirror** [comment]
I would say the package is ready for prime time.  I have added the following features (on top of the ones listed in the OP):

- The ability to associate `TODO` keywords with special bullets
- Making leading stars invisible, removing indentation caused by them

The package still runs through `package-lint`, `checkdoc` and `flycheck` without issue and compiles without warning.  I have removed the ["work in progress"](https://github.com/dw-github-mirror/org-superstar-mode/commit/f5a258d5243b6f6b2b7a574197e798a8b3a9f37a) [warnings](https://github.com/dw-github-mirror/org-superstar-mode/commit/9a60ffc4cc1a323a583b285c2ef6ff3084f9fab2) and am generally ready to bump the package to it's first truly stable release version **1.0.0**.

**Comment by alphapapa** [comment]
Great work!

Just to be clear:

> * Making leading stars invisible, removing indentation caused by them

Have you tested this with the different combinations of `org-indent-mode`, `org-hide-leading-stars`, `org-hide-leading-stars-before-indent-mode`, etc?

**Comment by lmintmate** [comment]
> Just to be clear:
> 
> > * Making leading stars invisible, removing indentation caused by them
> 
> Have you tested this with the different combinations of `org-indent-mode`, `org-hide-leading-stars`, `org-hide-leading-stars-before-indent-mode`, etc?

I took the liberty of testing these things (since I was the one who asked @dw-github-mirror to add this feature). I observed that `org-indent-mode` indents eveything regardless of the value of `org-superstar-remove-leading-stars` (the setting that removes the indentation).  `org-hide-leading-stars` and `org-hide-leading-stars-before-indent-mode` don't do anything if `org-superstar-remove-leading-stars` is t. On the other hand, if that is nil, and `org-hide-leading-stars` is also nil, the little dot markers used instead of stars remain even after setting `(setq-local org-hide-leading-stars-before-indent-mode t)` and enabling `org-indent-mode` (but maybe that's not a bug - after all given that the before-indent-mode variable doesn't have documentation, maybe it's just intended for internal usage and not for being set by a  user). I should note here though that if someone (like myself) wants to remove all indentation from the stars, they probably won't want any indentation in the text either.
P.S. Are there any other variables that could clash with this feature I should check for?

**Comment by dw-github-mirror** [comment]
>Have you tested this with the different combinations of org-indent-mode, org-hide-leading-stars, org-hide-leading-stars-before-indent-mode, etc?

@lmintmate nailed it, but I should comment to further clarify.
I mostly have, but I should add that to the documentation more thoroughly somewhere.  Generally, if `org-hide-leading-stars` is non-nil, the package keeps it's hands off leading stars.  I was not sure what to do with the undocumented `org-hide-leading-stars-before-indent-mode` so for the time being my package does not respond to it in any particular way.  However, `org-superstar-remove-leading-stars` takes precedence over both, following the logic that it is a "more extreme" version of the above and thus contains their intent semantically.  However, it only removes indentation *caused by leading stars*, meaning any additional indentation that was added purposefully (like that of `org-indent-mode`) should be preserved.

**Comment by integral-dw** [comment]
> I would still suggest a more "human" user name. :wink:

Does that count as a patch? :smile:

**Comment by integral-dw** [comment]
I looked more closely at what `org-hide-leading-stars-before-indent-mode` actually does.  It is essentially a throwaway variable to store, well, `org-hide-leading-stars` before indent mode is enabled.  It seems like it *should* be ignored.  I am [currently asking around on the mailing list](https://lists.gnu.org/archive/html/emacs-orgmode/2020-02/msg00759.html) for further details.

**Comment by alphapapa** [comment]
Nice new username!  :)

**Comment by integral-dw** [comment]
Thanks!  Took me a while to come up with a decent one, but luckily my favorite variable substitution was not taken. :smile:

**Comment by integral-dw** [comment]
Excuse the repost, as I've brought it up [at my repo](https://github.com/melpa/melpa/pull/6675) already, but I think it's good to reiterate here for the sake of completeness.  `org-hide-leading-stars-before-indent-mode` [has been deprecated](https://code.orgmode.org/bzg/org-mode/commit/1b2de14d8444602ec619a0884b8c7cafd08c68d9).

**Comment by integral-dw** [comment]
Is there anything else I can/should do? Just checking.

**Comment by alphapapa** [comment]
Sometimes it takes a few weeks before the next set of package recipes are merged.  In the meantime, I'd be glad to hear any feedback you might have about my new project: https://github.com/alphapapa/bufler.el  :)

**Comment by integral-dw** [comment]
That's reassuring!  Sure, I'll take a look, may take me a bit to get to it, though.

**Comment by riscy** [comment]
Looks great!  Thanks everyone. :)  Welcome to MELPA 🥛 

Minor, fyi:
- depatures -> departures

**Comment by integral-dw** [comment]
Awesome, thanks!
>depatures -> departures
Oh yeah, I really should set up flyspell to work in docstrings.  Thanks!

**Comment by integral-dw** [comment]
Oh darn!
I forgot to change my username in the recipe (`dw-github-mirror` -> `integral-dw`).  Should I open a PR for this or could you guys do a quick edit?

**Pull request merged**
