### PR TITLE
add helm-frame recipe

### PR DESCRIPTION
**Pull request by chee**
### Brief summary of what the package does

it opens your helm buffer in a dedicated frame in the middle of the screen, similar to rofi or Alfred.

### Direct link to the package repository

https://gitlab.com/chee/helm-frame

### Your association with the package

I am the maintainer and contributor and an enthusiastic user.

### Relevant communications with the upstream package maintainer
**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
_**note,** i used a non-standard separator `/` for the commands; there is a potential for conflict with `helm-frame-$command` between `helm-frame` and a possible `helm` command. ie, if i had a command called `dog` and helm added a command called `frame-dog`, both would be called `helm-frame-dog`_
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by chee** [comment]
screenshot of helm-frame working in sandbox
screenshot of `helm-frame` working in sandbox with only `helm` and `helm-frame` installed

**Comment by purcell** [comment]
Thanks. Quick feedback:

- `(if frame frame nil)` is exactly the same as just `frame`.
- There's no need to `autoload` your commands.

Also:

> note, i used a non-standard separator / for the commands; there is a potential for conflict with helm-frame-$command between helm-frame and a possible helm command. ie, if i had a command called dog and helm added a command called frame-dog, both would be called helm-frame-dog

It doesn't matter, you should still use `-` rather than `/`. That's just how the simplistic namespacing in emacs lisp works.

Code like the following will always iterate over every item in a list, even if the first item is the one you want:

```el
  (let (current-monitor)
    (dolist (monitor (display-monitor-attributes-list) current-monitor)
      (if
        (member (or frame (window-frame)) (assoc 'frames monitor))
        (setq current-monitor monitor))))
```

So instead, `(require 'cl-lib)` and use something like `cl-find-if`, or `cl-loop`:

```el
  (cl-loop for monitor in (display-monitor-attributes-list)
    if (member (or frame (window-frame)) (assoc 'frames monitor))  
    return monitor)
```
or
```el
  (cl-find-if (lambda (m) (member (or frame (window-frame)) (assoc 'frames m)) )
              (display-monitor-attributes-list))
```

**Comment by chee** [comment]
thank you for the feedback 

i've made those changes now

lol @ `(if frame frame nil)`

**Comment by purcell** [comment]
Sorry for the long delay in merging - this got lost in the pile of pull requests. :-)

**Pull request merged**
