### PR TITLE
Added cybercafe theme recipe

### PR DESCRIPTION
**Pull request by gboncoffee**
### Brief summary of what the package does

Almost colorless, white-on-black theme.

### Direct link to the package repository

https://github.com/gboncoffee/cybercafe-emacs-theme

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by progfolio** [comment]
How does this compare to the almost-mono-black theme?

https://raw.githubusercontent.com/cryon/almost-mono-themes/master/readme-files/almost-mono-black.png

**Comment by gboncoffee** [comment]
There are a few differences. Cyber Cafe has less use of italics (only in comments), different green, yellow and red colors, a reversed mode-line, brighter strings and comments, and support for different modes (as example, almost-mono doesn't add support for Magit, while Cyber Cafe doesn't add support for Company).

**Comment by riscy** [comment]
Thanks both.  Quick first pass --

`cybercafe-theme.el` with byte-compile using Emacs 28.1:
```
cybercafe-theme.el:38:11: Warning: assignment to free variable
    `cybercafe-cyberpunk'
cybercafe-theme.el:103:17: Warning: reference to free variable
    `cybercafe-cyberpunk'
cybercafe-theme.el:121:32: Warning: reference to free variable
    `doom-modeline-mode'
```

`#'load`-check on each file:
```
Loading cybercafe-theme.el
  cybercafe-theme.el:Error: Emacs 28.1:
  (void-variable doom-modeline-mode)
```

It looks like, unless doom-modeline is installed, this won't be usable.  Maybe a dependency needs to be declared?

**Comment by gboncoffee** [comment]
My bad. When adding doom-modeline support I queryed the variable. Will fix.

**Comment by gboncoffee** [comment]
Just fixed the issues reported by @riscy. Thanks for the reporting.

**Comment by riscy** [comment]
Thanks - merging.  And, welcome to MELPA. :)

**Comment by gboncoffee** [comment]
Thank you!!!

**Pull request merged**
