### PR TITLE
Add recipe for casual-editkit

### PR DESCRIPTION
**Pull request by kickingvegas**
### Brief summary of what the package does

Casual EditKit is a Transient-based user interface library for Emacs editing commands.

### Direct link to the package repository

https://github.com/kickingvegas/casual-editkit

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

`casual-editkit-utils.el` with byte-compile using Emacs 29.4:
```
casual-editkit-utils.el:30:2: Error: Cannot open load file: No such file or directory, magit-status
```

`casual-editkit.el` with byte-compile using Emacs 29.4:
```
casual-editkit.el:47:2: Error: Cannot open load file: No such file or directory, magit-status
```

This may be due to a magit versioning discrepancy?

**Comment by kickingvegas** [comment]
Did not include magit in `Package-Requires`. Will address.

**Comment by kickingvegas** [comment]
Casual EditKit v1.0.4 updated to include `magit 4.0.0` as a requirement. 

https://github.com/kickingvegas/casual-editkit/releases/tag/1.0.4

**Comment by riscy** [comment]
Thanks again - this fixed that issue, but surfaced another one:

`casual-editkit-utils.el` with byte-compile using Emacs 29.4:
```
casual-editkit-utils.el:133:2: Error: Symbol's value as variable is void: casual-editkit-navigation-group
```

Since I've had trouble magit versions in the recent past, I double-checked the versions being installed by my workflow and I have:
```
archives			    magit-20240920.1135
casual-lib-20240827.2223	    magit-section-20240913.1455
casual-symbol-overlay-20240905.129  package-lint-20240919.1647
compat-30.0.0.0			    pkg-info-20150517.1143
compat-30.0.0.0.signed		    symbol-overlay-20240913.1624
dash-20240510.1327		    transient-20240918.1138
epl-20180205.2049		    with-editor-20240831.2230
```
so I believe everything is up to date when running the byte-compile.

**Comment by kickingvegas** [comment]
I'm unable to reproduce the error `Symbol's value as variable is void`. What is puzzling is that `casual-editkit-navigation-group` is [defined](https://github.com/kickingvegas/casual-editkit/blob/057f6651ca319620ab877fd6a776c95943840d3d/lisp/casual-editkit-utils.el#L66) in the same file `casual-editkit-utils.el`. 
 
All the files in `casual-editkit/lisp/` byte-compile clean for me. Perhaps remove any old `.elc` files and retry again?

**Comment by kickingvegas** [comment]
@riscy How significant is the ordering of list items in `Package-Requires`? Would moving `magit` ahead of `casual-lib` address this?

https://github.com/kickingvegas/casual-editkit/blob/057f6651ca319620ab877fd6a776c95943840d3d/lisp/casual-editkit.el#L9

**Comment by riscy** [comment]
Interesting thought - when I'm running checks, I store the requirements in a Python `set` which puts them in an arbitrary order (and in this case it is changing the order to `casual-symbol-overlay`, then `casual-lib`, then `magit`).

If I manually change the order to `magit`, `casual-symbol-overlay`, then `casual-lib`, my .emacs.d/elpa contents look like:
```
archives			    magit-20240920.1135
casual-lib-20240827.2223	    magit-section-20240913.1455
casual-symbol-overlay-20240905.129  package-lint-20240919.1647
compat-30.0.0.0			    pkg-info-20150517.1143
compat-30.0.0.0.signed		    symbol-overlay-20240913.1624
dash-20240510.1327		    transient-20240918.1138
epl-20180205.2049		    with-editor-20240831.2230
```
which looks identical to the above, and this byte-compile error persists:

`casual-editkit-utils.el` with byte-compile using Emacs 29.4:
```
casual-editkit-utils.el:133:2: Error: Symbol's value as variable is void: casual-editkit-navigation-group
```

I thought I'd let you know the result of that experiment, but I can dig in and see if I can help debug this.

> Perhaps remove any old .elc files and retry again?

Every check I run is "from scratch" in a new container - no .elc files persist between runs or anything like that.

**Comment by riscy** [comment]
Oh, of course I know what's going on.  Macros get expanded before `defconst` forms are evaluated - you may be byte-compiling in an Emacs runtime that already has the const defined.

**Comment by kickingvegas** [comment]
@riscy Thanks for the feedback. So to address this should I define the defconst in a separate file and require that file into `casual-editkit-utils.el` here? Or is there other guidance that you have?

**Comment by kickingvegas** [comment]
All good. Will make amendment.

**Comment by kickingvegas** [comment]
@riscy Casual EditKit v1.0.5 with changes to fix byte-compilation ordering ready for MELPA review. 

https://github.com/kickingvegas/casual-editkit/releases/tag/1.0.5

**Comment by riscy** [comment]
Thanks!

**Pull request merged**
