### PR TITLE
scala-mode2 is dead, long live scala-mode

### PR DESCRIPTION
**Pull request by fommil**
this deletes some packages that are now no longer used.

### CODE REVIEW

**Comment by purcell** [comment]
Yay!

**Comment by tarsius** [comment]
@fommil Can you explain in more detail how scala-outline-popup "is no longer used", so that I can determine whether I should move it from the Emacsmirror to the Emacsattic or whether I should remove it completely.

**Comment by fommil** [comment]
@tarsius @ancane abstracted it to work for arbitrary modes, so no longer `scala-outline-popup` but now https://github.com/ancane/popup-imenu

**Comment by tarsius** [comment]
Thanks! In that case I'll remove the old package.

**Pull request merged**
