### PR TITLE
Created recipe for `koopa-mode`

### PR DESCRIPTION
**Pull request by sch0lars**
### Brief summary of what the package does

This package is used to edit Microsoft PowerShell files and includes features such as syntax highlighting, auto-complete, and spawning and sending code to a PowerShell process. 

### Direct link to the package repository

https://github.com/sch0lars/koopa-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Why is this called `koopa-mode` instead of `powershell-mode` or even `ps1-mode` (which [appears](https://stackoverflow.com/questions/12107462/file-extension-for-powershell-3) to be the standard suffix for these files)?  Maybe I am missing some context.

In the meantime here's a quick first pass --

`koopa-mode.el` with byte-compile using Emacs 28.1:
```
koopa-mode.el:247:8: Warning: docstring wider than 80 characters
koopa-mode.el:249:4: Warning: malformed cond form: `nil'
In koopa-company-backend:
koopa-mode.el:439:16: Warning: looking-back called with 1 argument, but
    requires 2-3
koopa-mode.el:439:41: Warning: looking-back called with 1 argument, but
    requires 2-3
In update-koopa-newline-hook:
koopa-mode.el:459:8: Warning: docstring wider than 80 characters
In update-double-colon-hook:
koopa-mode.el:472:10: Warning: looking-back called with 1 argument, but
    requires 2-3
In end of data:
koopa-mode.el:338:10: Warning: the function `comint-send-region' is not known
    to be defined.
koopa-mode.el:324:10: Warning: the function `comint-send-string' is not known
    to be defined.
koopa-mode.el:309:10: Warning: the function `comint-mode' is not known to be
    defined.
```

`koopa-mode.el` with checkdoc 0.6.2:
```
koopa-mode.el:428: Argument `command' should appear (as COMMAND) in the doc string
koopa-mode.el:471: First sentence should end with punctuation
koopa-mode.el:482: White space found at end of line
```

`koopa-mode.el` with package-lint 20230806.1331:
```
3 issues found:
66:54: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
459:0: error: "update-koopa-newline-hook" doesn't start with package's prefix "koopa".
470:0: error: "update-double-colon-hook" doesn't start with package's prefix "koopa".
```

`koopa-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- koopa-mode.el#L164: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
- koopa-mode.el#L307: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L166: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L176: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L198: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L365: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L414: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L400: You can use `not` or `null`
- koopa-mode.el#L476: Loading a package should rarely add hooks
- koopa-mode.el#L478: Loading a package should rarely add hooks
- koopa-mode.el#L479: Loading a package should rarely add hooks
- koopa-mode.el#L481: Loading a package should rarely add hooks
- koopa-mode.el#L483: Loading a package should rarely add hooks
- koopa-mode.el#L484: Loading a package should rarely add hooks
```
Most of these hooks look like they should be added (using the LOCAL flag) when koopa-mode is activated, not at the top-level. 

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

**Comment by sch0lars** [comment]
Thank you for your feedback! I have since updated the code, ran `package-linter`, `checkdoc`, and `byte-compile-file`, and resolved the issues. I have also added a `LICENSE` file to the repo. 

I chose the name `koopa-mode` as a Mario reference (the Power Shell move from Paper Mario). `powershell-mode` is already an Emacs package (no longer in MELPA, as it has not been maintained in over 10 years, but I did not want to take the name) and there is a `powershell` package in MELPA, though this is for the shell itself and not for editing PowerShell files in an IDE-esque fashion.

**Comment by riscy** [comment]
> I chose the name koopa-mode as a Mario reference (the Power Shell move from Paper Mario).

Oh nice!  This is just a suggestion, but maybe you could put that piece of lore into the package's `;;; Commentary`.

Here's the latest --

`koopa-mode.el` with byte-compile using Emacs 28.1:
```
koopa-mode.el:349:10: Warning: the function `comint-send-region' is not known
    to be defined.
koopa-mode.el:335:10: Warning: the function `comint-send-string' is not known
    to be defined.
koopa-mode.el:320:10: Warning: the function `comint-mode' is not known to be
    defined.
```
Looks like these need a (require 'comint)`.

`koopa-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- koopa-mode.el#L176: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
- koopa-mode.el#L318: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L178: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L188: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L210: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L376: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L425: It's safer to sharp-quote function names; use `#'`
- koopa-mode.el#L411: You can use `not` or `null` (e.g. `(not variable)` instead of `(eq variable nil)`)
```

**Comment by sch0lars** [comment]
Thank you for the feedback! I have made the recommended changes. Interestingly, I was not receiving these warnings on Emacs 28.2 on MacOS and Emacs 27.1 on Linux and Windows, nor was the melpazoid workflow I added to the repo throwing any warnings.

**Comment by riscy** [comment]
> I was not receiving these warnings on Emacs 28.2 on MacOS and Emacs 27.1 on Linux and Windows, nor was the melpazoid workflow I added to the repo throwing any warnings.

For the case of your own Emacs runtime, I'm not too surprised -- runtimes always differ.  Melpazoid may not have created any noise for you because it doesn't give a nonzero return code unless errors are detected (as opposed to suggestions and warnings).  This is because some these suggestions and warnings are opinions or false positives much more frequently than actual errors are.

This form:
```elisp
;; Set all indentation to be space-derived
(setq indent-tabs-mode nil)
```
should not appear in your package code.  I was worried my suggestion might cause this to happen and I should rephrase it.  This form should appear in your own personal configuration.

**Comment by sch0lars** [comment]
Thank you! I have removed the reference from the code.

**Comment by riscy** [comment]
Thanks!  Welcome to MELPA. :)

**Pull request merged**
