### PR TITLE
Add recipe for chordpro-mode

### PR DESCRIPTION
**Pull request by josephmturner**
### Brief summary of what the package does

Emacs major mode for editing files in the [ChordPro format](https://www.chordpro.org/chordpro/chordpro-introduction/).

### Direct link to the package repository

https://git.sr.ht/~breatheoutbreathein/chordpro-mode.el/

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

The original author, Howard Ding, [is happy for this fork to become the new main repo](https://github.com/hading/chordpro-mode/issues/5#issuecomment-1503359015) for `chordpro-mode`.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- solid work.  I think there are just a couple of minor things I'll point out:

`chordpro-mode.el` with byte-compile using Emacs 28.1:
```
chordpro-mode.el:101:14: Warning: the function `string-blank-p' might not be
    defined at runtime.
```
For this one you just need a `(require 'subr-x)`

I also notice you're using `cl-pushnew` to add to `auto-mode-alist`.  Technically this is completely fine, but it's conventional to use `add-to-list` to modify `auto-mode-alist` in this way (I haven't ever seen cl-pushnew used).  The reason I recommend (but don't insist on) sticking to convention is that by doing the usual thing you make that form a little more visually recognizable, ultra dumb static analysis tools based on regexps will be able to read your code, and perhaps even avail your mode to future core-Emacs optimizations around this very common pattern.

**Comment by tarsius** [comment]
> I also notice you're using `cl-pushnew` to add to `auto-mode-alist`. Technically this is completely fine, but it's conventional to use `add-to-list` to modify `auto-mode-alist` in this way (I haven't ever seen cl-pushnew used).

The docstring of `add-to-list` instructs to not to use it in "Elisp code" (as opposed to "Elisp configuration", I suppose):

> This is handy to add some elements to configuration variables,
> but please do not abuse it in Elisp code, where you are usually
> better off using `push` or `cl-pushnew`.

Despite that, it is indeed common to use `add-to-list` to add to `auto-mode-alist`, not just in configuration. For some reason the code intended to show a warning about that, doesn't seem to kick in. I don't know what the-right-way™ is, and recommend that you ask for guidance on emacs-devel, before continuing to tell people to not use `cl-pushnew` here.

**Comment by josephmturner** [comment]
Thanks for your feedback! I added `(require 'subr-x)`.

I didn't yet change `cl-pushnew` to `add-to-list`. I'd like to better understand the advantages to using one over the other.

**Comment by riscy** [comment]
Technically what you've got is completely fine.  @tarsius I read this --

> This is handy to add some elements to configuration variables,

-- as not suggesting `add-to-list` is best kept for configuration (like init.el) but for configuration variables, of which `auto-mode-alist` is one.  I actually took your suggestion to heart re: emacs-devel, and I need to look into verifying some of my future assumptions there (including this), but overwhelmingly `add-to-list` is what you see in the builtin Emacs elisp source; and `cl-pushnew` requires the extra step of bringing `cl-lib` at least at compile time.

**Comment by tarsius** [comment]
> I read this --
>
> > This is handy to add some elements to configuration variables,
> 
> -- as not suggesting `add-to-list` is best kept for configuration (like init.el) but for configuration variables,

Now I am having a bit of déjà vu :grinning:

**Comment by josephmturner** [comment]
@riscy  @tarsius Thank you for the review and merge!! :)

**Comment by josephmturner** [comment]
@riscy, @tarsius Looking at the source for `add-to-list`, it looks like it can't add to (some?) lexically-bound lists. Not that this is an issue for adding to `auto-mode-alist`.

**Comment by josephmturner** [comment]
And the [manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/List-Variables.html) says not to use it to add to lexical variables.

**Comment by josephmturner** [comment]
@tarsius @riscy  I was reading [this Chris Wellon's blog post](https://nullprogram.com/blog/2018/02/22/), and I came across this:

> To further assist with lazy loading, an evaluated defvar form will not override an existing global variable binding. This means you can, to a certain extent, configure a package before it’s loaded. The package will not clobber any existing configuration when it loads. This also explains the bizarre interfaces for the various hook functions, like add-hook and run-hooks. These accept symbols — the names of the variables — rather than values of those variables as would normally be the case. The add-to-list function does the same thing. It’s all intended to cooperate with lazy loading, where the variable may not have been defined yet.

In the `chordpro-mode` case, I think `cl-pushnew` is still fine, but this post helped me understand why I'd want to use `add-to-list` in configuration when adding to a list variable which is may not be defined yet.

**Comment by tarsius** [comment]
Yeah, it's not a bad idea to go through those posts every few years. Saying that, I realize it might be time for me to do it again. :grinning:

**Pull request merged**
