### PR TITLE
feat(recipes): add gpt-commit recipe

### PR DESCRIPTION
**Pull request by ywkim**
### Brief summary of what the package does

GPT-Commit is an Emacs package that automatically generates conventional commit messages using the [GPT (Generative Pre-trained Transformer)](https://openai.com/research/gpt-3) model from OpenAI.

### Direct link to the package repository

https://github.com/ywkim/gpt-commit

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  The code looks solid, and I can see that this is GPL-3 licensed which checks out, but we should standardize these licenses.  In particular:

  - Try to use a standard license file format
    See: https://github.com/licensee/licensee
    e.g. https://www.gnu.org/licenses/gpl-3.0.txt
  - Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to gpt-commit.el

Standardizing the repo's LICENSE will allow GitHub to auto-detect the license of all the code therein; and in many cases a system will "only" have the source file, so it's a good idea to have the license be machine-detectable there too.

**Comment by tarsius** [comment]
> Add formal license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to gpt-commit.el

Add formal license boilerplate **and/or** an [SPDX-License-Identifier](https://spdx.dev/ids/) to gpt-commit.el

Adding both (plus the LICENSE file) is best. :smiley:

**Comment by ywkim** [comment]
> > Add formal license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to gpt-commit.el
> 
> Add formal license boilerplate **and/or** an [SPDX-License-Identifier](https://spdx.dev/ids/) to gpt-commit.el
> 
> Adding both (plus the LICENSE file) is best. 😃

Thank you for the advice. I have updated the license and pushed the changes again :)

**Comment by riscy** [comment]
Looks good - thanks!  And welcome to MELPA. :)

**Pull request merged**
