### PR TITLE
Add recipe for timu-line

### PR DESCRIPTION
**Pull request by macownersclub**
### Brief summary of what the package does

This is a very simple mode line... With just the following sections so far (might likely not change):

#### Left side
* Display hint `k` when a kbd macro is running
* Display evil state
* Display buffer/file name
* Display keybinds for org capture in the capture buffer
* Display the vc branch
* Display the python venv
* Display Mu4e context
* Display Elfeed search filter
* Display Elfeed article counts

#### Right side
* Display the major mode
* Display mu4e mail count (works only with `mu` installed)
* Display tab number `current:total`
* Display column number of the point

### Direct link to the package repository

https://gitlab.com/aimebertrand/timu-line

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

`timu-line.el` with byte-compile using Emacs 29.1:

```
timu-line.el:540:34: Warning: the function `elfeed-search--count-unread' is not known to be defined.
timu-line.el:369:16: Warning: the function `evil-visual-state-p' is not known to be defined.
timu-line.el:368:16: Warning: the function `evil-replace-state-p' is not known to be defined.
timu-line.el:367:16: Warning: the function `evil-operator-state-p' is not known to be defined.
timu-line.el:366:16: Warning: the function `evil-normal-state-p' is not known to be defined.
timu-line.el:365:16: Warning: the function `evil-motion-state-p' is not known to be defined.
timu-line.el:364:16: Warning: the function `evil-insert-state-p' is not known to be defined.
timu-line.el:363:16: Warning: the function `evil-emacs-state-p' is not known to be defined.
timu-line.el:295:14: Warning: the function `tramp-tramp-file-p' is not known to be defined.
```

`timu-line.el` with checkdoc (0.6.2)

```
No issues found
```

`timu-line.el` with package-lint (20230905.629)

```
No issues found.
```

**Comment by macownersclub** [comment]
> `timu-line.el` with byte-compile using Emacs 29.1:
>
> ```
> timu-line.el:540:34: Warning: the function `elfeed-search--count-unread' is not known to be defined.
> timu-line.el:369:16: Warning: the function `evil-visual-state-p' is not known to be defined.
> timu-line.el:368:16: Warning: the function `evil-replace-state-p' is not known to be defined.
> timu-line.el:367:16: Warning: the function `evil-operator-state-p' is not known to be defined.
> timu-line.el:366:16: Warning: the function `evil-normal-state-p' is not known to be defined.
> timu-line.el:365:16: Warning: the function `evil-motion-state-p' is not known to be defined.
> timu-line.el:364:16: Warning: the function `evil-insert-state-p' is not known to be defined.
> timu-line.el:363:16: Warning: the function `evil-emacs-state-p' is not known to be defined.
> timu-line.el:295:14: Warning: the function `tramp-tramp-file-p' is not known to be defined.
> ```
>

Hi there,

Thank you for the check. These cases are considered with:

* https://gitlab.com/aimebertrand/timu-line/-/blob/main/timu-line.el?ref_type=heads#L536
* https://gitlab.com/aimebertrand/timu-line/-/blob/main/timu-line.el?ref_type=heads#L361

**Comment by riscy** [comment]
Thanks both.  Re: the warnings, what we should do in these cases (when we want to include optional functionality without stating its dependencies) is some additional `declare-function`s to keep the byte-compiler quiet.  This is nicer for users (no big scroll of warnings/errors at install time) but also lets other devs know you've done the bookkeeping:

```elisp
(declare-function evil-insert-state "ext:evil-states.el" (&optional arg))
...
```

**Comment by macownersclub** [comment]
Applyed suggested fix:

https://gitlab.com/aimebertrand/timu-line/-/commit/f0682223785e2699213e0601ffadbc8a213231c6

```
(declare-function elfeed-search--count-unread "ext:elfeed-search" t t )
(declare-function evil-visual-state-p "ext:evil-states" t t)
(declare-function evil-replace-state-p "ext:evil-states" t t)
(declare-function evil-operator-state-p "ext:evil-states" t t)
(declare-function evil-normal-state-p "ext:evil-states" t t)
(declare-function evil-motion-state-p "ext:evil-states" t t)
(declare-function evil-insert-state-p "ext:evil-states" t t)
(declare-function evil-emacs-state-p "ext:evil-states" t t)
(declare-function tramp-tramp-file-p "tramp" t t)
```

**Comment by riscy** [comment]
Thanks - merging!

**Pull request merged**
