### PR TITLE
Create etd

### PR DESCRIPTION
**Pull request by jasonm23**
### Brief summary of what the package does

Provides an interface layer to ERT which generates ert tests and markdown documentation, from actual / expected comparison test formatted as simple examples.

### Direct link to the package repository

https://github.com/emacsfodder/etd

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

n/a

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

Note the two macros `defexamples` and `def-examples-group` will not be prefixed with `etd-`.

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I'm including some of the "demonstration" code in this, but you may want to exclude these files (if everyone packaged demo elisp files with their packages, there would be more byte-compile noise and possible naming collisions to overcome):

`etd-demonstration.el` with package-lint 20220607.738:
```
4 issues found:
11:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
13:0: error: Package-Requires outside the main file have no effect.
29:0: error: "example-func-1" doesn't start with package's prefix "etd".
33:0: error: "example-func-2" doesn't start with package's prefix "etd".
```

`etd-demonstration.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- etd-demonstration.el#L1: `lexical-binding` must be on the end of the first line
```

`etd-examples.el` with package-lint 20220607.738:
```
3 issues found:
11:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
13:0: error: Package-Requires outside the main file have no effect.
26:0: error: "example-func" doesn't start with package's prefix "etd".
```

`etd-examples.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- etd-examples.el#L1: `lexical-binding` must be on the end of the first line
```

`etd.el` with package-lint 20220607.738:
```
3 issues found:
42:16: warning: Replace deprecated `cl' with `cl-lib'.  The `cl-libify' package can help with this.
144:0: error: "defexamples" doesn't start with package's prefix "etd".
158:0: error: "def-example-group" doesn't start with package's prefix "etd".
```
You mentioned that you will not change these names, but this is (imo) one of the most important standards for us to adhere to as a community using a language with limited namespacing support.  I'd ask you to reconsider, as in most cases I'd consider this a blocker.  Let me know if I can explain further.

`etd.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- etd.el#L236: It's safer to sharp-quote function names; use `#'`
- etd.el#L301: It's safer to sharp-quote function names; use `#'`
- etd.el#L303: It's safer to sharp-quote function names; use `#'`
```

Package and license:
- GNU General Public License v3.0 (via API)
- unknown license -- etd-demonstration.el: Demonstration of ETD
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to etd-demonstration.el
- unknown license -- etd-examples.el: Tests for E.T.D.
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to etd-examples.el
- unknown license -- etd.el: Examples to Tests and Docs
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to etd.el

**Comment by jasonm23** [comment]
This is a testing wrapper, in the same realm as [ert-expectations](https://github.com/emacsorphanage/ert-expectations/blob/master/ert-expectations.el)

Its entire purpose is built around its semantics.

**Comment by riscy** [comment]
Hi!  I'm assuming that's a response to my (admittedly unclear) mention of the "demonstration" code.  What I mean is, if someone installs this package, they will suddenly have `example-func-1` and `example-func-2` and `example-func` in their function namespace.

MELPA prefers to avoid shipping testing code (e.g. etd-examples.el describes itself as "Tests for E.T.D.") and the default recipe will do that when the file is suffixed with -test.el.  READMEs and other ad hoc forms of documentation (except for .info files) are also excluded; but if you need to ship the demonstration code (etd-demonstration.el) with the package, you could change the file extension so that it isn't mistakenly byte-compiled and installed on user machines.

Let me know when this is ready for another look, and feel free to reach out in the meantime too.

**Comment by jasonm23** [comment]
No, that's  not what I was talking about, on that topic. Demonstration code is possible to drop into docs, so I'll get that organised.

What I'm concerned about is the naming of `def-example-groups` & `defexamples`. I'd  entertain renaming them to `group` and `examples`. However, if you take issue with their current names  your toes are probably curling uncomfortably at the thought of something so generic.

Given these current names are already alive and well in every install of Emacs using `s.el` I think your potential concern is, somewhat misplaced.

**Comment by jasonm23** [comment]
For the examples and tests I think the best solution is to add the magic string:

```
;; -*-no-byte-compile: t; -*-
```

**Comment by jasonm23** [comment]
@riscy - any issues?

**Comment by riscy** [comment]
Hi @jasonm23 - I'm usually just here on weekends.

**Comment by riscy** [comment]
Thanks for working at that -- what you suggest will keep it from being byte-compiled, but it will still be installed onto user's machines (e.g., many themes on MELPA are no-byte-compile, but they still get installed and live in the user's namespace).

> However, if you take issue with their current names your toes are probably curling uncomfortably at the thought of something so generic.  Given these current names are already alive and well in every install of Emacs using s.el I think your potential concern is, somewhat misplaced.

I think I need this unpacked for me a little (e.g. why would I be so uncomfortable?).  I don't think the names I'm concerned with are in every install of s.el based on the [source code that MELPA is currently distributing](https://melpa.org/packages/s-20220902.1511.el) -- can you point me to where this is taking place?

**Comment by alphapapa** [comment]
There would seem to be some overlap between this and Emacs 28's `shortdoc` feature.  Maybe, rather than invent another way to define canonical example code and results, the built-in `shortdoc` library could be enhanced or wrapped to provide more of these features.

**Comment by jasonm23** [comment]
@alphapapa - Hi Adam, could you explain more?  https://emba.gnu.org/emacs/emacs/-/blob/master/lisp/emacs-lisp/shortdoc.el has no commentary and appears to have a different purpose/intent.

ETD is an ert testing wrapper, the intent is that you write short form examples, and that also gives you documentation as a side effect.  Pulling in function docstrings an publishing them adjacent to the examples, as markdown text.

**Comment by jasonm23** [comment]
> I think I need this unpacked for me a little (e.g. why would I be so uncomfortable?). I don't think the names I'm concerned with are in every install of s.el based on the [source code that MELPA is currently distributing](https://melpa.org/packages/s-20220902.1511.el) -- can you point me to where this is taking place?

I checked the recipe for [s.el](https://github.com/melpa/melpa/recipes/s) and I see that the other files aren't installed. (I use straight.el, which clones the whole thing.)

So I get your point.  I hope you understand my point though.

We still have `ert-expectations` which has `describe`, `expect` etc. as top level names, which serve a similar purpose to etd's macros.

If it's a viable alternative route, I could adopt that orphaned  package, add features for auto-documenting code from tests, etc.

What do you think?

**Comment by jasonm23** [comment]
@alphapapa 

Looking at the main docstring in shortdoc.el

```
  "Add GROUP to the list of defined documentation groups.
FUNCTIONS is a list of elements on the form:

  (FUNC
   :no-manual BOOL
   :args ARGS
   :eval EVAL
   :no-eval EXAMPLE-FORM
   :no-value EXAMPLE-FORM
   :no-eval* EXAMPLE-FORM
   :result RESULT-FORM
   :result-string RESULT-STRING
   :eg-result RESULT-FORM
   :eg-result-string RESULT-STRING)

FUNC is the function being documented.

NO-MANUAL should be non-nil if FUNC isn't documented in the
manual.

ARGS is optional list of function FUNC's arguments.  FUNC's
signature is displayed automatically if ARGS is not present.
Specifying ARGS might be useful where you don't want to document
some of the uncommon arguments a function might have.

While the `:no-manual' and `:args' property can be used for
any (FUNC ..) form, all of the other properties shown above
cannot be used simultaneously in such a form.

Here are some common forms with examples of properties that go
together:

1. Document a form or string, and its evaluated return value.
   (FUNC
    :eval EVAL)

If EVAL is a string, it will be inserted as is, and then that
string will be `read' and evaluated.

2. Document a form or string, but manually document its evaluation
   result.  The provided form will not be evaluated.

  (FUNC
   :no-eval EXAMPLE-FORM
   :result RESULT-FORM)   ;Use `:result-string' if value is in string form

Using `:no-value' is the same as using `:no-eval'.

Use `:no-eval*' instead of `:no-eval' where the successful
execution of the documented form depends on some conditions.

3. Document a form or string EXAMPLE-FORM.  Also manually
   document an example result.  This result could be unrelated to
   the documented form.

  (FUNC
   :no-eval EXAMPLE-FORM
   :eg-result RESULT-FORM) ;Use `:eg-result-string' if value is in string form

A FUNC form can have any number of `:no-eval' (or `:no-value'),
`:no-eval*', `:result', `:result-string', `:eg-result' and
`:eg-result-string' properties."
```

I can see what you're saying.  However from what I can see, it's too far along in it's development.

There's some overlap, granted.

**Comment by jasonm23** [comment]
I'll make the name changes @riscy so we can move this along.

**Comment by alphapapa** [comment]
@jasonm23 

> the intent is that you write short form examples, and that also gives you documentation as a side effect. Pulling in function docstrings and publishing them adjacent to the examples

As you noted later, that is an apt description of `shortdoc` as well.

> However from what I can see, it's too far along in it's development.

I don't understand what you mean.  It's part of Emacs.  Emacs wasn't too far along in its development to add `shortdoc`--why whould `shortdoc` be too far along in its development to add other features, or to write a library that reuses it?

**Comment by jasonm23** [comment]
@alphapapa I would just like to develop ETD as I use it in a few places already and I'd like to continue that.

Is there some relationship you have with the shortdoc module?

**Comment by alphapapa** [comment]
> Is there some relationship you have with the shortdoc module?

No, we're just friends.

**Comment by riscy** [comment]
Thanks for accommodating the name changes @jasonm23 - let me know when you're ready for a closer look.

> We still have ert-expectations which has describe, expect etc. as top level names, which serve a similar purpose to etd's macros.  If it's a viable alternative route, I could adopt that orphaned package (ert-expectations) and add features for examples-to-tests and auto-documenting the code from tests+docstrings.

It's true there are legacy packages that aren't following the namespace conventions (especially old stuff scraped off of the emacswiki), but it's best to follow these conventions going forward.  Adopting `ert-expectations` feels like an orthogonal issue to me as I'm not familiar with that package -- but if the behavior you're seeking is partly implemented already in that package, that may be a great outcome here.

In the meantime, here's the latest on the files that this recipe specifies:

`etd-demonstration.el` with package-lint 20220913.1226:
```
6 issues found:
11:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
13:0: error: Package-Requires outside the main file have no effect.
28:0: error: Aliases should start with the package's prefix "etd".
29:0: error: Aliases should start with the package's prefix "etd".
32:0: error: "example-func-1" doesn't start with package's prefix "etd".
36:0: error: "example-func-2" doesn't start with package's prefix "etd".
```

`etd-demonstration.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- etd-demonstration.el#L1: `lexical-binding` must be on the end of the first line
```

`etd-examples.el` with package-lint 20220913.1226:
```
5 issues found:
10:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
12:0: error: Package-Requires outside the main file have no effect.
24:0: error: Aliases should start with the package's prefix "etd".
25:0: error: Aliases should start with the package's prefix "etd".
28:0: error: "example-func" doesn't start with package's prefix "etd".
```

`etd.el` with package-lint 20220913.1226:
```
1 issue found:
42:16: warning: Replace deprecated `cl' with `cl-lib'.  The `cl-libify' package can help with this.
```

`etd.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- etd.el#L236: It's safer to sharp-quote function names; use `#'`
- etd.el#L301: It's safer to sharp-quote function names; use `#'`
- etd.el#L303: It's safer to sharp-quote function names; use `#'`
```

Package and license:
- GNU General Public License v3.0 (via API)
- unknown license -- etd-demonstration.el: Demonstration of ETD
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to etd-demonstration.el
- unknown license -- etd-examples.el: Tests for E.T.D.
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to etd-examples.el
- unknown license -- etd.el: Examples to Tests and Docs
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to etd.el

**Comment by jasonm23** [comment]
Ok.

I'll make demonstration a . example to quiet down package lint.

I will sharp quote the function references in etd.

In the meantime please go ahead and merge the recipe now so I'm  not twiddling my thumbs for another week

**Comment by riscy** [comment]
> In the meantime please go ahead and merge the recipe now so I'm not twiddling my thumbs for another week.

I know you're excited to get this indexed, but let's work together to get the feedback items cleaned up before merging.  Here's the latest:

`etd.el` with package-lint 20220913.1226:
```
1 issue found:
42:16: warning: Replace deprecated `cl' with `cl-lib'.  The `cl-libify' package can help with this.
```
This is surprising given you have `Package-Requires: ((emacs "24.4"))`.  I think 24.3 is when `cl-lib` and `cl-reduce` became available, and your code definitely depends on `cl-reduce` being available, so what I would recommend is declaring `Package-Requires: ((emacs "24.3"))` and getting rid of the `(require 'cl)`.  This way the package is accurately declaring its dependency, and you get a clean package-lint as well.

`etd.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- etd.el#L308: It's safer to sharp-quote function names; use `#'`
- etd.el#L310: It's safer to sharp-quote function names; use `#'`
```
Minor; these are non-blocking, but I recommend them because the byte-compiler will check if these functions exist when you sharp-quote them, which can be useful in case you decide to rename one of them.

Package and license:
- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to etd.el

The file etd.el has no indication of its license which is required per CONTRIBUTING.org.  It's also good practice because sometimes someone will *only* have a copy of your elisp file.  A quick, formal, and machine-detectable way to add this is to use an SPDX License Identifier (see the link).

**Comment by jasonm23** [comment]
Ok can do

**Comment by jasonm23** [comment]
Done.

**Comment by riscy** [comment]
Thanks for accommodating - I recommend formal license boilerplate (as you see e.g. in the builtin Emacs lisp files) or an SPDX license identifier, because these are more machine-detectable and unambiguous.  But, happy to get this merged now.

**Comment by tarsius** [comment]
I am tempted to remove this package again because of https://github.com/emacsfodder/kurecolor/issues/17. Doing that feels a bit petty even to myself, but on the other hand Jason makes the "this is FOSS, I don't owe you anything" argument and refuses to engage in a conversation, and I am inclined to use the same argument.

`etd` isn't some random end-user package, it is a testing and documentation generation framework intended for use by maintainers of other elisp packages. As such it should be held to a higher standard than end-user packages. Maintainers who use it will look at how it does things and follow its lead. This is problematic because it does not follow best practices.

Fixing a mistake that has metastasized, can be [a lot](https://github.com/rejeep/ert-runner.el/issues/38) more work than to just fix it when it is first discovered.

Like Jason isn't obligated to take our concerns into account, we are not obligated to distribute his package, if we believe that it promotes bad practices, and (as I do) that distributing/promoting it will cause us (me) additional work, which could be avoided, if he respected our time as much as he values sticking to his timeline.

**Comment by jasonm23** [comment]
Given you can expend so much energy in throwing a tantrum but not push a PR is the main pettiness you're engaged in here.

I have a plan for making the update however it's not a current priority due to a number of health concerns that are of a much higher priority.

I'm disappointed that someone who has disappeared off the net for health reasons can behave in such a way.

Now of course you had no idea.

You just felt that what you want to happen and when ... Isn't.

So either make a PR for kurecolor if you want it done immediately.

Lobbying to remove ETD makes no sense at all in this context.  You just lost your temper.

**Comment by tarsius** [comment]
> health concerns that are of a much higher priority.

I am very sorry to hear that and wish you a quick recovery.

> I'm disappointed that someone who has disappeared off the net for health reasons can behave in such a way.

Had I known about your health issues I would have behaved differently, but I don't think I have behaved in an inappropriate way, that justifies your disappointment. As I see it, I respected your authority over your project, while reserving the right to do the same for a project that I am maintainer of.

> Lobbying to remove ETD makes no sense at all in this context.

I wasn't proposing the (temporary) removal of `etd` as retaliation but because Melpa has a right to enforce certain standards. Whether your package violates these seriously enough to warrant removal is up for discussion; and a technical matter. I was expecting push-back from other maintainers, and wasn't going to insist we take immediate action.

The problem really was that I was missing the context.

Your initial response to my inquiry was to close it as *not planned*. Someone chimed in to mention that it is within Melpa's right to enforce certain standards for packages distributed there, to which you responded by mentioning that this was already being discussed elsewhere. Hoping to learn more, I made an honest effort to find those other discussions, but couldn't. You then ignored my request to point me to such a discussion.

At that point you mentioned the three freedoms, which I now think might have been your way of saying "patches welcome", but that is not how I understood it, it sounded more like "fork off". You then "recommended" that I close the conversation, and immediately proceeded to actually do so yourself, making it impossible for me to reply, e.g., to ask whether a pull-request would be welcome.

Every step along the way I felt my request was being ignored. There was no way for me to know why you were doing that and whether you actually plan to do something about this eventually (closing as "not planned" *really* did not help).

Many times I have done as they suggested, when a maintainer responded to one of my requests by saying that they don't care about the issue but that I was welcome to implement the change myself. I might still do so here as well.

**Comment by jasonm23** [comment]
Sorry that I didn't give you any context.

However it's a private matter.

As I've said all along the changes are planned and will happen.  They were planned from the get go.

Similarly, the relevant changes will be accepted as a PR, if there is some sense urgency.

further conversation on this topic, in particular its delivery schedule or documentation are now shelved.

I don't appreciate the way **this looks like** retaliation for not immediately getting what you want.

Whatever the case, there are better uses of your energy.

**Comment by alphapapa** [comment]
I don't wish to contribute noise, but I feel like I should say something.  

Jason, you may not be aware of the enormous time and effort Jonas has put into the Emacs packaging ecosystem (as well as many other aspects of Emacsland) over the past several years.  We would all be much poorer were it not for his dedication to excellence and servanthood.  It's common for his work and that of other MELPA maintainers to be taken for granted by those who aren't aware of what goes on behind the scenes to produce the resources we enjoy.  

It sounds like you're dealing with some difficult issues, and it's understandable that you may not have a lot of time or patience for what seem like minor problems.  At the same time, you may rest assured that any concerns he brings up are not merely for himself but are on behalf of all Emacs users.

When one of us contributes a package to MELPA, it does not mean only offering a gift of our code, but it also means assuming a measure of responsibility for being a "good citizen" in the package ecosystem.  Since there is no namespacing in Emacs Lisp, and no awareness of packages when it comes to `load-library` and `require` but only of `load-path`, it's up to packages to adhere to certain standards to avoid interference.  It's understandable that you weren't aware of this concern at first, but it's to be expected that the MELPA maintainers would bring it up when discovered and ask for it to be resolved quickly.

There is much to be read in your responses between the lines; and lacking the context (which you certainly have every right to keep private), one can't blame Jonas or anyone else for feeling like "good citizenry" wasn't important to you.  I hope you can understand their perspective.

**Comment by jasonm23** [comment]
Thank you for your time to try and explain things.

I think I need to point out that I understand.  They  were raised in the repo.

The work surely needs to be done.  Unfortunately I am unable to do it at the moment and will not be able to for several weeks.

I am well aware of Jonas contribution to Emacs in general, and I appreciate it every time I use Magit or anything else he's contributed to.

If you wish to spend further energy on this, push a PR to assist.

Otherwise it'll be done when I am able.  I expect I will be able to attend to it around the new year.

**Pull request merged**
