### PR TITLE
Add conner recipe

### PR DESCRIPTION
**Pull request by tralph3**
### Brief summary of what the package does

Conner is a Command Runner. It allows you to define arbitrary commands for each of your projects in a file at the root directory of the project, then run them in a compilation buffer through an easy emacs interface.

### Direct link to the package repository

https://github.com/tralph3/conner

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`conner.el` with byte-compile using Emacs 29.3:
```
conner.el:226:26: Warning: the function `project-root' is not known to be defined.
```
It looks like we need a `(require 'project)` for this one.

`conner.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- conner.el#L10: This may be a copy-paste error?
```

**Comment by tralph3** [comment]
Thanks, I require project at the start now. I don't get the second error tho, should that line not be there? Is it added automatically once installed?

**Comment by riscy** [comment]
That line means your program is part of the core set of packages and builtins that GNU Emacs ships with.  MELPA hosts third-party packages (so it's more typical to see `This file is NOT part of GNU Emacs` or no such line at all)

**Comment by tralph3** [comment]
Got it, removed.

**Comment by riscy** [comment]
Thanks - checklist looks good.  There seem to be a [few packages](https://melpa.org/#/?q=project%20command), at least on MELPA, that do similar things, e.g. `moonshot`, `projector`, and to a lesser extent `test-cockpit` -- have you had a chance to compare to these packages?

**Comment by tralph3** [comment]
No, I saw projector a bit I think, didn't know about the other two. Let me check them out and I'll point out the differences.

**Comment by tralph3** [comment]
`moonshot` seems to have the most overlap with my package. Without exploring it further I can't really tell exactly what it does or how it works, but you seem to be able to define commands in a file and run either elisp or shell? If so, that could make my package obsolete, although it seems to have quite a bit of dependencies and benefits from defining variables in `.dir-locals`.

I consciously abstained from that approach, since defining variables in `.dir-locals` prompts users to confirm if they want to apply them, and I thought it would be annoying for emacs users that don't use the package to be asked to apply these variables if they are exploring a project or something, so I preferred to make my own.

If anything, it could maybe work as a lightweight substitute for `moonshot`.


`projector` allows you to run commands in project directories, but it does not allow you to define these commands beforehand, from what I've seen. It has utilities for running, but not defining. Plus, it has the same issue with `.dir-locals`.

`test-cockpit` is oriented to testing exclusively, and needs to support each language by itself. My package is generalized.

**Comment by riscy** [comment]
Thank you for investigating those.  I think you make a good case for being distinct, even from moonshot.

I have to apologize for the long turnaround time, but I think the latest instance has a couple of remaining issues --

`conner.el` with byte-compile using Emacs 29.3:
```
conner.el:473:2: Warning: docstring wider than 80 characters
In end of data:
conner.el:282:42: Warning: the function `minibuffer-keyboard-quit' is not known to be defined.
```
The first is trivial to fix; the second actually implies a dependency on the builtin `delsel` , strangely enough.

**Comment by tralph3** [comment]
Ok, I fixed those two issues. Should be good now.

**Comment by tralph3** [comment]
I have added a runner for both eat and vterm. Problem now is the byte compiler complains about the functions for these packages to not be defined. That is fine, since the functions check if the packages are loaded beforehand anyway and has a fallback, but I don't want to add them as dependencies since they are entirely optional.

Is this fine? Or should I address this? If so, how.

**Comment by riscy** [comment]
> Is this fine? Or should I address this? If so, how.

Yes, let's see if we can address this.  Here's the byte-compile --

`conner.el` with byte-compile using Emacs 29.3:
```
conner.el:669:15: Warning: Unused lexical variable `vterm-kill-buffer-on-exit'
conner.el:671:15: Warning: Unused lexical variable `vterm-shell'
In end of data:
conner.el:675:10: Warning: the function `vterm-mode' is not known to be defined.
conner.el:655:10: Warning: the function `eat-exec' is not known to be defined.
conner.el:654:10: Warning: the function `eat-mode' is not known to be defined.
conner.el:638:6: Warning: the function `term-exec' is not known to be defined.
conner.el:637:6: Warning: the function `term-mode' is not known to be defined.
```

For lines 669, 671, and 675, you can hint the compiler with:
```
;; bookkeeping for optional vterm dependency:
(defvar vterm-kill-buffer-on-exit)
(defvar vterm-shell)
(declare-function vterm-mode "ext:vterm.el" nil)
```
 and I think you can go from there.

Also note on conner.el#L305: `concat` may be unneeded; `insert` can take multiple arguments

**Comment by tralph3** [comment]
Alright, with this it should be finally read for merge :)

**Comment by riscy** [comment]
Thank you!

**Pull request merged**
