### PR TITLE
remove cask from CI

### LINKED ISSUE #7482: Update to python 3
Cask is dropping support for python 2, so we need to install version 3.

https://github.com/cask/cask/issues/498
https://github.com/cask/cask/pull/524

### PR DESCRIPTION
**Pull request by dickmao**
Fixes #7482

### CODE REVIEW

**Comment by tarsius** [comment]
So using Cask didn't actually accomplish anything anyway?! :grin:

**Comment by tarsius** [comment]
It's a bit silly that we have to do this (I think) but could you please push a temporary recipe change like https://github.com/melpa/melpa/pull/7488/commits/77c96b0f1513ec34699e469007f15e698298fb31 for testing purposes?

**Comment by dickmao** [comment]
I'd already done so at https://github.com/dickmao/melpa/pull/54.  Despite what most think about me, I do some minimal testing *before* submitting PRs.

**Comment by milkypostman** [comment]
I believe unless we see that this works with a temporary recipe change, the CI results are potentially hiding problems.

If you look at the CI run https://github.com/melpa/melpa/runs/2156506407?check_suite_focus=true you can see that when Cask is run it implicitly installs `package-build` and dependencies. I know that some of these packages are needed for `package-build`. Then when the actual test is run, it uses `package-build` from the repository (https://github.com/melpa/melpa/blob/2aae45d7195a93eab44fc5fec2285a5f9d8187de/run-ci.sh#L20) by specifying the `load-path`.

Thus to make this work, I think we will need to run emacs with a `package-install` that pulls in the dependencies.

It would actually be really nice to somehow build all the dependencies FROM the checkout, and then install those packages using `package.el`.

In the future it does mean a bit more maintenance because any dependencies that are incurred by `package-build` will need to be added to the CI script.

Final note: probably our CI should have a list of packages that are built on *every* CI run. This way, changes to `package-build` that are part of merging the subtree will have a set of packages that indicate things (like this change) are working properly. I have filed #7492 to figure out what should be in this set.

**Comment by dickmao** [comment]
> Thus to make this work, I think we will need to run emacs with a package-install that pulls in the dependencies.

Rather than speculate, you should try as I did in https://github.com/dickmao/melpa/pull/54.

Much respect for being the Neil Armstrong who planted the non-GNU flag of the emacs ecosystem, but I think you've been away too long from the nitty-gritty to make these kinds of on-the-ground policy decisions.

**Comment by purcell** [comment]
I committed a variation of this in efd78c6, also removing the Cask file.

Both my change and this PR rely implicitly on the fact that `package-build`'s dependencies are satisfied by Emacs >= 25.1, so it would be good to make that explicit eventually: if package-build were a single-file package, we could trivially install it from the local copy using `package-install-file`. It isn't, though, and the alternatives would be messy. So this compromise is reasonable for now.

**Pull request closed without merging**
