### PR TITLE
Add recipe for mpvi

### PR DESCRIPTION
**Pull request by lorniu**
### Brief summary of what the package does

Integrate MPV, EMMS, Org and others with Emacs, make watching videos conveniently
and taking notes easily. Make EMMS support Windows.

### Direct link to the package repository

https://github.com/lorniu/mpvi

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`mpvi-ps.el` with byte-compile using Emacs 28.1:
```
mpvi-ps.el:32:55: Warning: reference to free variable `mpvi-cache-directory'
In mpvi-bilibili-add-begin-time-to-url:
mpvi-ps.el:83:8: Warning: docstring wider than 80 characters
In end of data:
mpvi-ps.el:94:49: Warning: the function `mpvi-ytdlp-download-subtitle' is not
    known to be defined.
mpvi-ps.el:43:16: Warning: the function `mpvi-call-process' is not known to be
    defined.
mpvi-ps.el:42:8: Warning: the function `mpvi-log' is not known to be defined.
```

`mpvi-ps.el` with checkdoc 0.6.2:
```
mpvi-ps.el:122: All variables and subroutines might as well have a documentation string
mpvi-ps.el:133: All variables and subroutines might as well have a documentation string
```

`mpvi-ps.el` with package-lint 20230315.1052:
```
1 issue found:
7:0: error: Package-Requires outside the main file have no effect.
```

`mpvi.el` with byte-compile using Emacs 28.1:
```
mpvi.el:308:29: Warning: value returned from (format "Waiting %s..." path) is
    unused
In mpvi-insert-attach-link:
mpvi.el:369:33: Warning: Unused lexical variable `org-attach-method'
In mpvi-ytdlp-url-metadata:
mpvi.el:549:10: Warning: Unused lexical variable `err'
In mpvi-ytdlp-pick-format:
mpvi.el:585:42: Warning: Unused lexical argument `pred'
mpvi.el:590:29: Warning: Unused lexical variable `suffix'
In mpvi-open:
mpvi.el:896:87: Warning: reference to free variable `mpvi-open-map'
In mpvi-seek:
mpvi.el:1052:52: Warning: Unused lexical argument `old-len'
In mpvi-emms-add:
mpvi.el:1296:34: Warning: Unused lexical variable `desc'
In mpvi-org-link-init:
mpvi.el:1364:40: Warning: reference to free variable `org-mouse-map'
In end of data:
mpvi.el:1365:4: Warning: the function `org-link-set-parameters' is not known
    to be defined.
mpvi.el:1321:37: Warning: the function `org-open-at-point' is not known to be
    defined.
mpvi.el:1131:55: Warning: the function `org-insert-item' is not known to be
    defined.
mpvi.el:1131:25: Warning: the function `org-at-item-p' is not known to be
    defined.
mpvi.el:999:35: Warning: the function `minibuffer-keyboard-quit' is not known
    to be defined.
mpvi.el:379:4: Warning: the function `org-display-inline-images' is not known
    to be defined.
mpvi.el:372:35: Warning: the function `org-attach-attach' is not known to be
    defined.
mpvi.el:126:23: Warning: the function `org-timer-secs-to-hms' is not known to
    be defined.
mpvi.el:117:37: Warning: the function `org-timer-fix-incomplete' is not known
    to be defined.
mpvi.el:117:14: Warning: the function `org-timer-hms-to-secs' is not known to
    be defined.
mpvi.el:86:36: Warning: the function `org-element-context' is not known to be
    defined.
```

`mpvi.el` with package-lint 20230315.1052:
```
1 issue found:
1371:1: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
```

`mpvi.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- mpvi.el#L323: It's safer to sharp-quote function names; use `#'`
- mpvi.el#L841: It's safer to sharp-quote function names; use `#'`
- mpvi.el#L230: It's safer to sharp-quote function names; use `#'`
- mpvi.el#L375: `concat` may be unneeded; `insert` can take multiple arguments
```

**Comment by lorniu** [comment]
Thanks to your feedback. And sorry, I accidentally set `byte-compile-warning` to nil, so couldn't find any error in byte-compiling before..

Now I updated the code and solved most of the issues, except the dependency of `org`.

> 1371:1: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
> 1132:55: Warning: the function ‘org-insert-item’ is not known to be defined

Besides using `eval-after-load`, is there any good way to delay the loading of `org`? Any suggestion?

Thanks.

**Comment by riscy** [comment]
> Besides using eval-after-load, is there any good way to delay the loading of org? Any suggestion?

There are a couple ways to go about this:
- Create a separate mpvi-org.el file, declare your dependency on org in the normal way here, and (judiciously) mark functions with `;;;###autoload` cookies; the functions will be accessible before they have been loaded in and you won't have to do any extra bookkeeping
- Inline your `(require 'org)` into the functions that actually use org.  This is in fact something that the [elisp manual suggests](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html).  However you should then pre-declare the functions/variables you use to the byte-compiler using `declare-function` and `defvar`.  There is a facility `check-declare-file` that is builtin to check your work.

For example you have in your keymap `(define-key map (kbd ", ,") #'org-open-at-point)`; if I wanted to support this without bringing in org, I'd do something like the following:
```elisp
(declare-function org-open-at-point "org.el" (&optional arg))
(defun mpvi-org-open-at-point (&optional arg)
  "Lazy-load org to call `org-open-at-point' with ARG."
  (interactive "P")
  (require 'org)
  (org-open-at-point arg))
(defvar mpvi-org-link-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd ", ,")   #'mpvi-org-open-at-point)
    map))
```

**Comment by lorniu** [comment]
Thank you for your reply.

But I don't think any of the above methods will achieve the desired effect.

What I most want is to make this code be executed after org loaded (that is, lazy load):
```elisp
(org-link-set-parameters "mpv"
                           :face mpvi-org-link-face
                           :keymap mpvi-org-link-map
                           :follow #'mpvi-org-link-push)
```

Neither `autoload` cookie nor inline `require` can make it work, IMO.

**Comment by riscy** [comment]
I see, I overlooked the call to `org-link-set-parameters` when I was suggesting the above.  I suppose the `with-eval-after-load` is okay, but if I were you I would just bite the bullet and `(require 'org)`; this will also clean up your byte-compile.  But I won't insist on this.

Here is how your byte-compile currently stands, and you can inform the byte-compiler using `defvar` and `declare-function` forms to cover these -- `mpvi.el` with byte-compile using Emacs 28.1:
```
mpvi.el:382:13: Warning: Unused lexical variable `org-attach-method'
In mpvi-org-link-init:
mpvi.el:1377:40: Warning: reference to free variable `org-mouse-map'
In end of data:
mpvi.el:1378:4: Warning: the function `org-link-set-parameters' is not known
    to be defined.
mpvi.el:1333:37: Warning: the function `org-open-at-point' is not known to be
    defined.
mpvi.el:1143:55: Warning: the function `org-insert-item' is not known to be
    defined.
mpvi.el:1143:25: Warning: the function `org-at-item-p' is not known to be
    defined.
mpvi.el:391:4: Warning: the function `org-display-inline-images' is not known
    to be defined.
mpvi.el:384:35: Warning: the function `org-attach-attach' is not known to be
    defined.
mpvi.el:126:23: Warning: the function `org-timer-secs-to-hms' is not known to
    be defined.
mpvi.el:117:37: Warning: the function `org-timer-fix-incomplete' is not known
    to be defined.
mpvi.el:117:14: Warning: the function `org-timer-hms-to-secs' is not known to
    be defined.
mpvi.el:86:36: Warning: the function `org-element-context' is not known to be
    defined.
```
Let me know if I can offer any help here.

Beyond that, a couple of comments following a closer look:

- The `;;; Commentary` for this package is much wider than 80 characters
- mpvi.el#L139: This line (and possibly others) indents with mixed tabs/spaces; see `indent-tabs-mode`
- This is relatively minor but I would recommend not binding keys to lambda functions, e.g. `(define-key map (kbd "k")   (lambda () (interactive) (mpvi-speed 1)))`; if a user were to try to find the "help" on this key, they'd be taken to the documentation (or lack thereof) of an anonymous functions
- mpvi.el seems to have `(require 'mpvi-ps)` at the bottom.  This is unusual and looks like a cyclic import between the two files; I think this points to some re-organization of the code being beneficial in the future
- `mpvi-image-to-clipboard` is passing `image-file` to `mpvi-clipboard-command` unescaped; you should use `shell-quote-argument` on the variable

**Comment by lorniu** [comment]
Thank you very much for your patient and detailed reply.

Sorry, I can't find any byte-compile issues using latest Emacs 30. But I fix most of the them according your response.

> but if I were you I would just bite the bullet and (require 'org)

Yes, this is the easiest and cleanest way. But it's too heavy for those who want to use this package but don't want to take note. The loading of `org` is too slow.

> This is relatively minor but I would recommend not binding keys to lambda functions

I don't want to change this. It is a trade off: writing too many _fragmented_ commands and making code cleaner and more readable. I choose the latter one.

> This is unusual and looks like a cyclic import between the two files

But if `(require mpvi-ps)` is after `(provide mpvi)`, cyclic import will not occur.
This is just a trick to silence linter. 

I know I can 1) seperate the functions used by both two files to another file, or 2) pre-declare the functions/variables using `declare-function` in `mpvi-ps.el`
to achieve the same effect. But above way is cleaner for me. Is it okay?

**Comment by riscy** [comment]
> It is a trade off: writing too many fragmented commands and making code cleaner and more readable.

I'm fine with your decision, but let's be accurate about what the tradeoff is: clearer code for you vs. clearer documentation for users accessing the builtin help.

> This is just a trick to silence linter.

Note we're not talking about the linter, but the compiler.  I have to be honest and admit I have never seen this before, nor have I seen it documented as a way to fix a cyclic import.

If you can point to some documentation or example that shows that this is valid and expected by the byte-compiler, then I won't protest.  Otherwise I would rather not see packages relying on undocumented byte-compiler behavior, when -- especially in this case -- the solution is as straightforward as writing a single `declare-function` form.

**Comment by lorniu** [comment]
> If you can point to some documentation or example that shows that this is valid..

I have indeed seen this kind of writing before.

> the solution is as straightforward as writing a single declare-function form..

However, I admit that it is a little weird. I've updated the code with `declare-function` as your suggestion.

Thanks.

**Comment by riscy** [comment]
> I have indeed seen this kind of writing before.

Thanks for your patience on this - any pointers on where you've seen this before?  This would help me learn from it. :)

Since you have gone with the `declare-function` form, which is probably the more obvious choice anyway, I notice the bottom of the file mpvi.el still contains

```elisp
;;; Miscellaneous

(require 'mpvi-ps) ; optional platform specialized config
```

**Comment by lorniu** [comment]
> I notice the bottom of the file mpvi.el still contains (require ..

I don't understand your meaning. Any other better way to use definitions in `mpvi-ps.el` without `require` it for `mpvi.el`?

**Comment by riscy** [comment]
Unless you can point me to where this is standard practice (and not a quirk of the byte compiler), then inside mpvi.el, add:

```elisp
(declare-function mpvi-convert-danmaku2ass "mpvi-ps.el")
```

And then from the bottom remove the `require` form.

**Comment by lorniu** [comment]
What?

I've removed the cyclic import. Please review the code again.

If you think there is still a problem with this, then ok, I will close this PR.

**Comment by riscy** [comment]
Let me know when that change is in effect - and thanks again for your understanding of my take on this.

**Comment by lorniu** [comment]
> Let me know when that change is in effect - and thanks again for your understanding of my take on this.

It's already OK, no cyclic import any more. I think you should review my code again carefully.

**Comment by riscy** [comment]
You are right that I didn't check your code carefully, and I apologize to that.  But to be fair, your response was "OK" and you haven't answered any questions I've asked about your workaround being standard practice.  Please realize I'm reviewing dozens of packages every weekend.

**Pull request merged**
