### PR TITLE
Mac Classic Theme

### PR DESCRIPTION
**Pull request by codeswish**
TextMate inspired Emacs 24 theme

### CODE REVIEW

**Comment by vyp** [comment]
@codeswish No need for the `'` in the recipe. :)

**Comment by milkypostman** [comment]
would you add a screenshot to the README?

**Comment by syohex** [comment]
This package does not conform Emacs packaging format.

- https://www.gnu.org/software/emacs/manual/html_node/elisp/Packaging-Basics.html#Packaging-Basics
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Simple-Packages.html#Simple-Packages

**Comment by codeswish** [comment]
I'll fix these issues and submit a new pull request.

**Pull request closed without merging**
