### PR TITLE
Add recipe for lsp-vue

### PR DESCRIPTION
**Pull request by cryptomaniac512**
### Brief summary of what the package does

Vue.js support for lsp-mode using [vls](https://github.com/vuejs/vetur/tree/master/server)

### Direct link to the package repository

https://github.com/emacs-lsp/lsp-vue

### Your association with the package

I am the original author and maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, and sorry for the slow response - I'm currently extremely busy! Some quick feedback:

- You shouldn't normally need to `(require 'vue-mode)` inside a function, when the whole module depends on that file. It should be sufficient to `;;;###autoload` the `lsp-define-stdio-client` form and the `lsp-vue-mmm-enable` function, assuming that `lsp-mode` has proper support for deferring those autoloads.
- Please inline some documentation in the `Commentary` section: the elisp file should be self-documenting as far as possible.
- The license is in a separate file which will not be included in the package, so a `License: MIT` header would be appreciated.

Hope that helps!

**Comment by purcell** [comment]
Oh, also: the `:files` form in the recipe is unnecessary here and should be removed.

**Comment by cryptomaniac512** [comment]
Thank you for help!

> when the whole module depends on that file.

Not all module depends on this file, only `lsp-vue-mmm-enable` function.

**Comment by purcell** [comment]
Okay, great - makes sense.

**Pull request merged**
