### PR TITLE
Add org-chef package.

### PR DESCRIPTION
**Pull request by Chobbes**
### Brief summary of what the package does

A package for making a cookbook and managing recipes with org-mode.

### Direct link to the package repository

https://github.com/Chobbes/org-chef

### Your association with the package

I am the creator / maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! This looks good, but doesn't a line like [this](https://github.com/Chobbes/org-chef/blob/master/org-chef-genius-kitchen.el#L96) cause requests to be made every time the library is loaded? This doesn't seem ideal. :-)

**Comment by Chobbes** [comment]
@purcell crap! Serves me right for testing in line.

I've removed the line :).

**Comment by purcell** [comment]
Great - merged! Welcome to MELPA. :tada:

**Comment by Chobbes** [comment]
Haha, thanks :). I'm quite excited about my first little package!

**Pull request merged**
