### PR TITLE
Add recipe for go-tag

### PR DESCRIPTION
**Pull request by brantou**
### Brief summary of what the package does

Modify field tags for golang struct fields.

### Direct link to the package repository

https://github.com/brantou/emacs-go-tag

### Your association with the package

I'm the creator of the package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Sorry for the slow reply - I'm currently extremely busy.

- Please remove the `:files` spec from the recipe. It is not needed here, because the default works fine.
- You haven't included a package dependency on `go-mode`.

**Comment by brantou** [comment]
Thanks! 
- I have removed the **:file** spec
- A function from go-mode is called, the name of the function is **go--apply-rcs-patch**.

**Comment by purcell** [comment]
> A function from go-mode is called, the name of the function is go--apply-rcs-patch.

Yes! So where is the `;; Package-Requires` entry for `go-mode`? That's my question! :-)

**Comment by brantou** [comment]
@purcell I'm sorry, it's my fault. I have added **Go-mode** to **Package-Requires**，please review again.

**Comment by purcell** [comment]
Great, thanks!

**Pull request merged**
