### PR TITLE
Add recipe for biomejs-format

### PR DESCRIPTION
**Pull request by yadex205**
### Brief summary of what the package does

`biomejs-format` provides a minor mode to format JS or supported code with Biome on file save.

### Direct link to the package repository

https://github.com/yadex205/emacs-biomejs-format

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Have you heard of [reformatter](https://melpa.org/#/reformatter)?  It may let you write this package in very few lines - but you may have already considered that.

I also notice that the standard tooling isn't able to parse the LICENSE in your repository and determine the license, which is probably due to its nonstandard format. Maybe you are able to fix this, but if not it isn't a blocker.

**Comment by yadex205** [comment]
@riscy Thank you for checking!

> Have you heard of [reformatter](https://melpa.org/#/reformatter)? It may let you write this package in very few lines - but you may have already considered that.

I didn't know `reformatter` but looks nice (maybe I will use at another place). I also know https://github.com/cxa/lsp-biome has similar feature.

But I still want to provide because this is a replacement of https://github.com/prettier/prettier-emacs and keeps same behaviors and usages. I added why I made this to `README.md` .

> I also notice that the standard tooling isn't able to parse the LICENSE in your repository and determine the license, which is probably due to its nonstandard format. Maybe you are able to fix this, but if not it isn't a blocker.

I had tried to fix but GitHub still doesn't determine (it should be BSD-3-Clause). I noticed that "Portions Copyright" lines cause confusion but I want to respect original so I will not change.

**Comment by riscy** [comment]
Alright - thanks!

**Comment by yadex205** [comment]
@riscy Thank you!

**Pull request merged**
