### PR TITLE
Add recipe for sourcepawn-mode

### PR DESCRIPTION
**Pull request by agrif**
### Brief summary of what the package does

This is an emacs major mode for SourcePawn plugin development. It has Pawn syntax aware code highlighting, in addition to highlighting of SourceMode-specific constants and function names.

### Direct link to the package repository

https://github.com/agrif/sourcepawn-mode

### Your association with the package

I am the original author.

### Relevant communications with the upstream package maintainer

I have cleaned up the docstrings a bit and added autoloads to make installation nicer for the user. I can make more changes as necessary, but I'm reluctant to make large changes as this code is 12 years old and still works fine (somehow).

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I see you're reluctant to make changes, but you should consider trying to modernize this code whenever possible (especially since you're planning on putting it on an index as visible as MELPA's), and these issues don't seem large at all:

`sourcepawn-mode.el` with checkdoc 0.6.2:
```
sourcepawn-mode.el:80: First line is not a complete sentence
sourcepawn-mode.el:85: First line is not a complete sentence
sourcepawn-mode.el:90: First line is not a complete sentence
sourcepawn-mode.el:96: First line is not a complete sentence
sourcepawn-mode.el:101: Argument `limit' should appear (as LIMIT) in the doc string
sourcepawn-mode.el:124: First line is not a complete sentence
sourcepawn-mode.el:147: Argument `column' should appear (as COLUMN) in the doc string
sourcepawn-mode.el:147: Lisp symbol `indent-line-to' should appear in quotes
```
Try to fix these - within reason.

`sourcepawn-mode.el` with package-lint 20230605.1550:
```
3 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: warning: Including "Emacs" in the package summary is usually redundant.
262:4: warning: Closing parens should not be wrapped onto new lines.
```

`sourcepawn-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- sourcepawn-mode.el#L106: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
- sourcepawn-mode.el#L168: This double negation can be collapsed (`not` aliases `null`)
```

**Comment by agrif** [comment]
These sorts of changes I'm quite happy to make!

I've pushed a commit to my repo that should address all of them. `checkdoc` and `package-lint` are happy on my side -- I don't have docker installed so I can't test with melpazoid, but those should be fixed as well.

**Comment by riscy** [comment]
Looks great!  I think there are further instances of mixed tabs/spaces but these are definitely not blockers, e.g.

- sourcepawn-mode.el#L135: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`

(the script that detects these is just searching for a tab followed by a space)

**Comment by riscy** [comment]
And, welcome to MELPA. :)

**Comment by agrif** [comment]
Thanks! Not really sure how I mixed tabs and spaces in here, but I'm not sure about a lot of things I did a decade ago.

Cheers!

**Pull request merged**
