### PR TITLE
Add recipe for consult-todo

### PR DESCRIPTION
**Pull request by liuyinz**
### Brief summary of what the package does

Provide the command `consult-todo' to search and jump between hl-todo keywords.

### Direct link to the package repository

https://github.com/liuyinz/consult-todo

### Your association with the package

author/maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I noticed you've got another PR #8900 already open and per [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org) I try to split my review-time evenly between authors.  I'll get to this one once any earlier ones are resolved.

**Comment by riscy** [comment]
Focusing on #8711 now (the new #8700)

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`consult-todo.el` with byte-compile using Emacs 28.1:
```
consult-todo.el:91:8: Warning: `((consp consult-todo-other))' is a malformed
    function
In end of data:
consult-todo.el:98:52: Warning: the function `group' is not known to be
    defined.
consult-todo.el:95:18: Warning: the function `narrow' is not known to be
    defined.
consult-todo.el:94:8: Warning: the function `if-let*' might not be defined at
    runtime.
```

**Comment by riscy** [comment]
Friendly ping :)

**Comment by liuyinz** [comment]
@riscy hello, sorry for not responding to you for weeks.
I have tested it with 27.1 to 29.1 and appears no problems, please look at [github actions](https://github.com/liuyinz/consult-todo/actions/runs/6399484645/job/17371596999)
Are you sure your environment is fine?

**Comment by riscy** [comment]
Yes, but I think your test environment is not running clean, i.e. it looks like your code needs to `(require 'subr-x)` (or at least `(eval-when-compile 'subr-x)`) in order for the `if-let*` macro to always be available to the compiler.  I suspect the runtime in your github actions script already has brought `subr-x` in as part of its own setup.

**Comment by liuyinz** [comment]
I rember if-let* is defined in subr.el, and subr.el is preloaded by default. why should I need to require 'subr-x ?

**Comment by riscy** [comment]
> subr.el is preloaded by default

Not when running `emacs -Q`, for instance -- which ideally you should be testing your code with anyway.

**Comment by liuyinz** [comment]
So why should I require subr-x when compile? I still cann't figure it out. 

@riscy  require subr-x can help to load subr implicitly or what other mechanism?

**Comment by riscy** [comment]
> So why should I require subr-x when compile?

There are two reasons I'm suggesting this:

The first is that by doing so you can prevent the byte-compiler from warning your users (whose runtime may be different than yours) that something may be wrong.  

The second is because by requiring it when you compile, you allow the compiler to expand the macro, and then compile that macroexpansion.  You can read more here: https://www.gnu.org/software/emacs/manual/html_node/elisp/Compiling-Macros.html

**Comment by liuyinz** [comment]
@riscy I have pushed ther final verison, please check it again.

**Comment by riscy** [comment]
Thank you for accommodating.  This looks like a solid package - merging.

**Pull request merged**
