### PR TITLE
recipe for filetree

### PR DESCRIPTION
**Pull request by knpatel401**
### Brief summary of what the package does

Filetree displays a file list as a directory tree in a special buffer.  The file list can be populated from any list of files.  There are functions to populate from a number of common sources: recentf, files in buffer-list, files in the current directory, and files found recursively in the current directory.  Within the viewer, the file list can be filtered and expanded in various ways and operations can be performed on the filtered file list (e.g., grep over files in list).  Multiple file lists can be saved and retrieved between sessions.  In addition, the package supports (org) file notes that can be shown in a side window when navigating through the files in the tree.

### Direct link to the package repository

https://github.com/knpatel401/filetree

### Your association with the package

It's a new package that I developed and have been using for some time.

### Relevant communications with the upstream package maintainer

None

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hello and welcome. :)  Thanks for your close adherence to the checklist.

The first thing I notice is that your `;;; Commentary` just includes License boilerplate, and ideally the commentary should appear _after_ the boilerplate, and describe what the package is about.

While we're on the topic of that license, your repository is licensed as MIT but the file itself as GPL 3.0 or later boilerplate -- ideally you should make these consistent.

I notice a fair amount of debug messaging throughout the code.  e.g. `filetree-add-filetype` prints the shortcut, which will appear in the user's messages as a scroll of numbers whenever they load the package:
```
0

112

111

101

99

100

109

116
```
but also others during normal operation, like `(message "file list length: %d" (length filetree-currentFileList))`.   Normally a package should operate silently unless debugging is enabled or the message is somehow important to users (but this is also somewhat a matter of opinion).

I also notice you're using a hybrid of camelCase and hyphenated function/variable names, but the community style prefers hyphens.  E.g. `filetree-set-maxDepth3` should be `filetree-set-max-depth-3`

And here are a handful of other [lints](https://github.com/riscy/melpazoid) (mostly automated):
- No `progn` is necessary to wrap the "else" part of an `if` (e.g. in `filetree-toggle-info-buffer`)
- filetree.el#L223: There is no need to quote lambdas (neither #' nor ') (and several other cases)
- filetree.el#L618: It's safer to sharp-quote function names; use `#'`
- filetree.el#L671: It's safer to sharp-quote function names; use `#'`
- filetree.el#L858: It's safer to sharp-quote function names; use `#'`
- filetree.el#L734: It's safer to sharp-quote function names; use `#'`
- filetree.el#L235: `read-string` prompts should often end with a space
- filetree.el#L299: `read-string` prompts should often end with a space
- filetree.el#L348: `read-string` prompts should often end with a space
- filetree.el#L907: `read-string` prompts should often end with a space
- filetree.el#L977: `read-string` prompts should often end with a space
- filetree.el#L657: `concat` may be unneeded; `insert` can take multiple arguments
- filetree.el#L690: `concat` may be unneeded; `insert` can take multiple arguments
- filetree.el#L703: `concat` may be unneeded; `insert` can take multiple arguments
- filetree.el#L816: `concat` may be unneeded; `insert` can take multiple arguments
- filetree.el#L828: `concat` may be unneeded; `insert` can take multiple arguments

**Comment by knpatel401** [comment]
Thanks a lot for the review and corrections--really appreciate it.
  
I think I've addressed these now in [31104b6](https://github.com/knpatel401/filetree/commit/31104b68cd98e09fff6198ebc60d0c989cc4f7cf)

- updated license in LICENSE file to GPL
- resolved lint errors
- removed camelCase usages
- removed unnecessary debug logging
- moved Commentary section and added additional info about package

**Comment by knpatel401** [comment]
Thanks a lot for the review and comments -- really appreciate it.

I think I've resolved all of the above now in [31104b6](https://github.com/knpatel401/filetree/commit/31104b68cd98e09fff6198ebc60d0c989cc4f7cf)
- updated license in LICENSE file to GPL
- resolved lint errors
- removed camelCase usages
- removed unnecessary debug logging
- moved Commentary section and added additional info about package

**Comment by riscy** [comment]
Thanks very much, this looks good to go.  And, welcome to MELPA. :)

**Pull request merged**
