### PR TITLE
habitica recipe

### PR DESCRIPTION
**Pull request by abrochard**
habitica.el is an extension to interact with https://habitica.com/static/front, a RPG style habit tracker.
I like the concept of getting exp and loot when you keep good habits, so I wanted to make it accessible via an org-mode interface.

https://github.com/abrochard/emacs-habitica

Looking forward to your feedback.

### CODE REVIEW

**Comment by syohex** [comment]
- Missing autoload cookie`;;;###autoload`
- You should not use `C-c t` for default binding. It breaks [Emacs key binding convention](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html). It says `C-c letter` is reserved for users.

**Comment by abrochard** [comment]
- Ah! Just added in this [commit](https://github.com/abrochard/emacs-habitica/commit/fc86ce1bdd7440692d8ddde4da37f2da607167f2). Is it the correct location?

- I don't think I am using it? Everything is behind the prefix `C-x t`

**Comment by syohex** [comment]
Oh sorry, I mistook.

**Comment by purcell** [comment]
Thanks!

**Comment by abrochard** [comment]
Thank you!

**Pull request merged**
