### PR TITLE
Add recipe for org-evil

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
Continuation of #4225 (with a new package name).

---
Repo: https://github.com/GuiltyDolphin/org-evil
Summary: Provides Evil integration for Org (including context-sensitive bindings).
Relation: I am the maintainer/creator.

### CODE REVIEW

**Comment by syohex** [comment]
Did you check to byte-compile ? I got following error at byte-compiling.

```
org-evil.el:42:1:Error: Invalid function:
((and (eq major-mode (quote (quote org-mode))) (monitor--expression-value-changed (quote (point)) t)) (quote org-evil--check-org-evil-table-mode) (quote org-evil--check-org-evil-heading-mode))
```

I suppose you mistake to use monitor package API.

```
> (monitor-expression-value (point) 'org-evil--check-org-evil-heading-mode 'org-mode t)

*** Eval error *** 
Invalid function: ((and (eq major-mode (quote (quote org-mode))) (monitor--expression-value-changed (quote (point)) t)) (quote org-evil--check-org-evil-table-mode) (quote org-evil--check-org-evil-heading-mode))
```

**Comment by GuiltyDolphin** [comment]
@syohex Thanks for pointing that out - it was  a combination of a poor call form in `monitor`, and I guess misuse of the API; I've updated `monitor` and it seems to be fine now.

**Comment by syohex** [comment]
I confirmed the error was gone.

**Comment by syohex** [comment]
I have sent PR(https://github.com/GuiltyDolphin/org-evil/pull/3) for suppressing byte-compile warnings at installing.

**Pull request merged**
