### PR TITLE
Add composable.el recipe

### PR DESCRIPTION
**Pull request by paldepind**
My second Emacs package [composable.el](https://github.com/paldepind/composable.el).

Thank you for the great work you do on MELPA.

### CODE REVIEW

**Comment by purcell** [comment]
Interesting, thanks. You probably want to add some `;;;###autoload` cookie comments.

**Comment by paldepind** [comment]
Yes. But I am slightly confused about `;;;###autoload`. Should I add it to _all_ `defun`s or only some? I've looked at other packages and I can't seem to find a clear pattern.

**Comment by purcell** [comment]
Just the symbols that the user might reasonably want to use without having to require the library, ie. usually those ones which kick off the functionality in the package. I'm guessing that might just be `composable-mode` here.

**Comment by paldepind** [comment]
Ok. Thank you. I might understand it now. `require` is for explicitly loading an entire file. But with autoload users can implicitly load a file just by calling an entry point function that will then trigger the loading?

**Comment by purcell** [comment]
Exactly, yes.

**Comment by paldepind** [comment]
Great. I somehow couldn't figure that out from the manual. Thank you for taking the time to explain :smile:

**Pull request merged**
