### PR TITLE
Add recipe for nikki

### PR DESCRIPTION
**Pull request by th994**
### Brief summary of what the package does

Create a simple diary.

### Direct link to the package repository

https://github.com/th994/nikki

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hello and thanks for this.  The byte-compile is smooth, but here is some quick feedback on the checklist --

checkdoc (using version 0.6.2):
```
Warning (emacs): 
nikki.el:152: The footer should be: (provide 'nikki)\n;;; nikki.el ends here
Warning (emacs): 
nikki.el:99: Argument `date' should appear (as DATE) in the doc string
```
(Regarding line 99, I suppose EVENT should appear as well, but checkdoc is sometimes inconsistent.)

package-lint (using version 20210111.341):
```
1 issue found:
118:1: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
```
Two bits of feedback here.  One is that you don't need to wrap the function in a lambda and could just write `(eval-after-load 'calendar #'nikki-assign-calendar-mode-keymap)`; more importantly is that this should not happen when the package is loaded.  You could suggest users run this command in their configuration by mentioning it in your `;;; Commentary`, but the idiomatic way to put down a keymap is to define a minor mode that has that keymap, and which can be easily toggled off/on by users.

And the last couple:
- nikki.el#L102: It's safer to sharp-quote function names; use `#'`
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by th994** [comment]
Thank you for confirming the contents.

I have made changes based on the information you provided.
The following is a list of fixes.

- No more warnings in checkdoc (using version 0.6.2), and included a doc string about EVENT on line 99.
- No more warnings in package-lint (using version 20210127.158).
- Deleted `(eval-after-load 'calendar #'nikki-assign-calendar-mode-keymap)`, and defined a minor mode(nikki-mode) that has that keymap.
- Changed to use sharp-quote function in line 102.
- Added a LICENSE file that GitHub can detect .

**Comment by riscy** [comment]
Looks good, thank you.  Minor but not blocking, I suspect `(error "Not found diary (nikki)")` is a `user-error` and not a full-fledged code error, and it might be rephrased as well: `(user-error "Diary not found at %s (nikki)" file-path)`

**Comment by th994** [comment]
I think you are right about the error message.  I have fixed the relevant part.
Thank you so much.

**Pull request merged**
