### PR TITLE
Add tabby-mode

### PR DESCRIPTION
**Pull request by ragnard**
### Brief summary of what the package does

Emacs support for the [Tabby](https://tabby.tabbyml.com) AI coding assistant.

### Direct link to the package repository

https://github.com/ragnard/tabby-mode

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thank you for this.  I'm just getting unburied, but here's a quick first pass --

`tabby-mode.el` with checkdoc 0.6.2 (fix *within reason*):
```
tabby-mode.el:7: Name emacs should appear capitalized as Emacs
```
This is a "false positive" but you actually want to make this one disappear.  Your `;;; Commentary` section should appear below these metadata.  Check out other packages for examples.

`tabby-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- tabby-mode.el#L98: Could this point/point-max comparison use `eobp`?
```

Package and license:
- tabby-mode.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by ragnard** [comment]
Thank you for this! This is the first package I'm submitting to MELPA, and I don't write that much elisp so very happy for the review. Didn't know MELPA came with such great review service :-)

I think I adressed your comments in https://github.com/ragnard/tabby-mode/commit/f079a81c2040bd21aa7870d9d27f40bf83608569

**Comment by riscy** [comment]
Looks good here.  You're welcome for the review... and welcome to MELPA. :)

**Comment by riscy** [comment]
Ooops --

I just realized as I was closing my window that this package actually isn't implementing a minor mode (or, it does, but the minor mode does not do anything).

I think the easiest thing to do here is just remove the `define-minor-mode tabby-mode` form -- it does nothing right now and might even create confusion.  Alternatively, the minor mode could serve to add a keybinding for the user to use (maybe shift-tab or something that's unlikely to collide.

If you don't figure tabby-mode.el will ever contain a minor mode to toggle off or on, for example, it might be a good idea to just rename the package to `tabby`.

Let me know your thoughts.  I'll get on top of any changes you want to make with higher priority, because this was my mistake.

**Pull request merged**
