### PR TITLE
initial org-change commit

### PR DESCRIPTION
**Pull request by drghirlanda**
### Brief summary of what the package does

org-change is a minor mode that (ab)uses the org-mode link syntax for
a simple "track changes" feature similar to some word processors.

### Direct link to the package repository

https://github.com/drghirlanda/org-change

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`org-change.el` with byte-compile using Emacs 28.1:
```
org-change.el:126:35: Warning: Unused lexical argument `path'
In org-change-add-export-backend:
org-change.el:164:47: Warning: Unused lexical argument `backend'
org-change.el:164:47: Warning: Unused lexical argument `exporter'
In org-change-export-link:
org-change.el:186:11: Warning: assignment to free variable `new-text'
org-change.el:187:11: Warning: assignment to free variable `comment'
org-change.el:189:58: Warning: reference to free variable `new-text'
org-change.el:197:29: Warning: reference to free variable `comment'
org-change.el:211:15: Warning: reference to free variable
    `org-export-filter-final-output-functions'
org-change.el:211:15: Warning: assignment to free variable
    `org-export-filter-final-output-functions'
In end of data:
org-change.el:201:15: Warning: the function `org-export-derived-backend-p' is
    not known to be defined.
org-change.el:151:11: Warning: the function `make-span' is not known to be
    defined.
org-change.el:120:2: Warning: the function `org-link-set-parameters' is not
    known to be defined.
org-change.el:85:25: Warning: the function `org-in-regexp' is not known to be
    defined.
```
Many of these are fixed by actually adding `(require 'org)` at the top of your file.  Some of these appear to be due to stubbing out org-link parameters, e.g. in the case of `org-change-open-link` you can rename the argument to `_path` to clarify to the byte-compiler that the variable isn't used.

And since I'm noticing it, I would personally lean toward calling `org-link-set-parameters` only when the minor mode is activated for the first time.  Simply loading in your package shouldn't cause too many changes to the Emacs runtime.

`org-change.el` with checkdoc 0.6.2:
```
org-change.el:127: All variables and subroutines might as well have a documentation string
org-change.el:130: All variables and subroutines might as well have a documentation string
org-change.el:135: Argument `old-text' should appear (as OLD-TEXT) in the doc string
org-change.el:145: Documentation strings should not start or end with whitespace
org-change.el:145: First sentence should end with punctuation
org-change.el:145: Argument `old-text' should appear (as OLD-TEXT) in the doc string
org-change.el:173: Second line should not have indentation
org-change.el:173: First line is not a complete sentence
org-change.el:177: Argument `old-text' should appear (as OLD-TEXT) in the doc string
org-change.el:179: Lisp symbol `org-mode' should appear in quotes
org-change.el:201: All variables and subroutines might as well have a documentation string
```

`org-change.el` with package-lint 20230315.1052:
```
1 issue found:
146:0: error: "make-span" doesn't start with package's prefix "org-change".
```
Just define this function at the top-level with the correct prefix, e.g. call it `org-change--make-span` (the double-dash `--` indicating that it is a private function and not part of your interface).

`org-change.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- org-change.el#L198: No `format` required; `error` takes an f-string
```

**Comment by drghirlanda** [comment]
Thanks for the feedback! I fixed 95% of these and committed to my repo. Do I need a new pull request to MELPA or will the commit be noticed automatically? The last few commits do not seem to have been picked up by MELPA (in a couple of days).

**Comment by riscy** [comment]
I'm usually here on weekends but can respond to this one quickly -- MELPA won't pull your code until after the package is indexed.  When I do my next round, though, I'll of course look at the latest version of your code. :)

**Comment by drghirlanda** [comment]
Great, thanks for the feedback! I believe I have fixed all these issue.

**Comment by riscy** [comment]
This is a novel idea - thanks again for this.  The last comments I have are non-blocking:

- `org-change-open/store-link` -- I'd recommend replacing the `nil` with a `(warn "Unimplemented")` or `(message "Opening a change link currently does nothing")` just to give the user some small feedback about why an operation might not be working
- Your summary line is "Track changes in org-mode files" and when I saw this my mind immediately went to version control.  Maybe "Annotate changes in org-mode files" would be more telling

But, like I said, non-blocking.  And welcome to MELPA. :)

**Comment by drghirlanda** [comment]
Thanks, I appreciate the suggestions!

**Pull request merged**
