### PR TITLE
Add default-font-presets package

### PR DESCRIPTION
**Pull request by ideasman42**
### Brief summary of what the package does

This package supports user-defined list of font presets.

This is useful since listing all available font's isn't especially useful, developers may want to switch between a handful of high-quality mono-spaced fonts for example.

Functionality:

- Cycle next/previous font.
- Select the font preset (choice or ivy when it's installed).
- Scale the current font.

### Direct link to the package repository

https://gitlab.com/ideasman42/emacs-default-font-presets

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
I think it would be easier to understand what this package does if it were named something like, `switch-font`.

**Comment by ideasman42** [comment]
@alphapapa I used the `default-` prefix to follow `default-text-scale` package, which I was previously using. OTOH, I don't have a strong attachment to this name.

**Comment by alphapapa** [comment]
BTW, this code may also be relevant as a more general case: https://github.com/alphapapa/unpackaged.el#define-a-chooser-command

**Comment by riscy** [comment]
I just notice your `;;; Commentary` gets cut short (try `M-x finder-commentary` on your file and you'll see it gets cut off above `;;; Usage`).  No blockers, though.

**Comment by ideasman42** [comment]
Odd, I can't redo this in `finder-commentary`, I've tried to edit this to avoid the problem.

**Comment by riscy** [comment]
In case it's helpful, I have to run <kbd>M-x load-lib ...</kbd> to get the finder-commentary to refresh -- my usual habit of running eval-buffer doesn't update the parsing of the commentary.

**Comment by riscy** [comment]
Just realized I was wrong about this -- if you'd written `;;; Usage:` it would cut off, but `;;; Usage` without the colon is fine.  Sorry for the noise.

**Pull request merged**
