### PR TITLE
Add recipe for rails-routes

### PR DESCRIPTION
**Pull request by otavioschwanck**
### Brief summary of what the package does

This is a package to help you find and insert rails routes into your code.
Instead of going to the terminal or loading the path in the browser, you just call 'rails-routes-insert',
It will fetch and save on cache all routes used by your application, so you have a reliable and easy way to search
and insert your routes.

### Direct link to the package repository

https://github.com/otavioschwanck/rails-routes.el

### Your association with the package

maintainer

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by otavioschwanck** [comment]
> Just for full transparency, I'm putting my attention into your other PR for now.
> 
> #7752

@riscy fixed the same points on this repo!  Thanks!

**Comment by riscy** [comment]
Thanks, this looks good to me -- I am still confused about the dependency on `(projectile "2.6.0-snapshot")` since the [latest release](https://stable.melpa.org/#/projectile) (at time of writing) is 2.5.0?  I think this time it's worth addressing before we merge.  But let me know if I'm missing something.

- rails-routes.el#L242: It's safer to sharp-quote function names; use `#'`
- I'd also recommend sharp-quoting within `rails-routes-project-root-function` and `rails-routes-project-name-function`
- rails-routes.el#L111: You can use `not` or `null`

**Comment by otavioschwanck** [comment]
> Thanks, this looks good to me -- I am still confused about the dependency on `(projectile "2.6.0-snapshot")` since the [latest release](https://stable.melpa.org/#/projectile) (at time of writing) is 2.5.0? I think this time it's worth addressing before we merge. But let me know if I'm missing something.
> 
> * rails-routes.el#L242: It's safer to sharp-quote function names; use `#'`
> * I'd also recommend sharp-quoting within `rails-routes-project-root-function` and `rails-routes-project-name-function`
> * rails-routes.el#L111: You can use `not` or `null`

@riscy changes made!

**Comment by riscy** [comment]
Looks good now!  I apologize for missing this earlier, but it looks like you've got mismatched licenses between the repository and the file itself:

- GitHub API found `MIT License`
- rails-routes.el has GPL* boilerplate

Folks usually use the full MIT license text e.g. [here](https://spdx.org/licenses/MIT.html) or use an SPDX license identifier (see the same link).

I think there's been enough back and forth that that's not a blocker, but it's a good opportunity to double-check other packages while you're at it.  And I'll think about steps I can take to prevent me from missing that in the future.

**Pull request merged**
