### PR TITLE
added recipe for git-riddance

### PR DESCRIPTION
**Pull request by jjba23**
### Brief summary of what the package does

Added git-riddance package

### Direct link to the package repository

https://github.com/jjba23/git-riddance

### Your association with the package

I am the author, maintainer and enthusiastic user.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by tarsius** [comment]
> Brief summary of what the package does
>
> Added git-riddance package

That's what this pull-request does, not what the package in question does. :grinning:

**Comment by tarsius** [comment]
Frankly this looks like the purpose of this package is you gaining experience using LLM. I don't think it is appropriate to add this to Melpa.

**Comment by jjba23** [comment]
> Frankly this looks like the purpose of this package is you gaining experience using LLM. I don't think it is appropriate to add this to Melpa.

I'm sorry to hear you don't appreciate the use of this package. The Dall-E image is just for making it a more pleasant page to visit, and more memorable.
For me, resetting a git repo is an activity that is repetitive enough to want to automate, and what better place to automate than Emacs itself. @tarsius

**Comment by tarsius** [comment]
So you are saying the code was not generated by having a conversation with a LLM?

**Comment by jjba23** [comment]
> So you are saying the code was not generated by having a conversation with a LLM?
 @tarsius 
I can assure you 100% I wouldn't touch AI for code. I see the damage it does in some companies already. 
I was having actually a really cool session with Prot today where he taught me library best practices, and this is the first time I extract stuff from my Emacs config into a package for more people to use. 
You can see my dotfiles repo and then at users/joe/emacs if you are curious.

**Comment by tarsius** [comment]
> I can assure you 100% I wouldn't touch AI for code. [...] I was having actually a really cool session with Prot today where he taught me library best practices, and this is the first time I extract stuff from my Emacs config into a package for more people to use.

Welcome to the parens! I hope you find this harsher feedback of mine useful too.

You have turned each and every step into a variable and/or function. That's not a best practice. I suppose early in your journey it could be a useful stepping stone. You document all that, which *is* a best practice, but given the excessive number of variables and functions, I found it hard to believe that a human would voluntarily do that.

The extreme verbosity and focus on overspecializing every, in itself "correct", step, along with the AI generated image, lead me to believe that the code was also generated by having a conversation with an AI. Turns out it was the result of a conversation with a human (whom I respect deeply).

My piece of unsolicited advice is this: work smarter not harder. Ask yourself what task exactly is not covered by magit/vc/"the git commands I am fluent with", research the options available to implement just that. Stop, before adding additional functionality, and ask yourself if it really belongs into the same command.

The core functionality can be reduced to:

```elisp
(defun git-riddance (message)
  "Squash the current branch into a new single commit."
  (interactive
   (list (read-string "Squash history into a single commit with message: ")))
  (call-process "git" nil nil nil "reset"
                (car (process-lines "git" "commit-tree" "HEAD^{tree}"
                                    "-m" message))))
```

You could add `(call-process "git" nil nil nil "push" "--force")` at the end to complete the process. I recommend against teaching this command to also rename the branch and add a remote. While these might be closely related tasks in your workflow, they are still distinct tasks. As long as this is only for your own use, it might make sense to merged these tasks into one, but once you publish this command, focusing on its distinct feature increases its usefulness and predictability considerably.

**Comment by jjba23** [comment]
@tarsius thanks for your feedback, coming from a seasoned E-Lisper specially! I am always open to learning and receiving feedback. I will for now keep this as a package for myself, and likely use your suggested snippet to improve it :)

**Comment by tarsius** [comment]
You are welcome, and I am glad you didn't take it the wrong way.

Note that like all seasoned elispers I am highly opinionated. And we certainly don't all have the same opinions an everything.

> I will for now keep this as a package for myself

I think that is a good idea when getting started with a language, which isn't to say that you shouldn't share your code and ask for feedback, but there is no harm in letting one's first package marinate a bit before asking for it to be included in a package archive. I've seen people ask on reddit for feedback.

> and likely use your suggested snippet to improve it

I intentionally only used builtin stuff. In practice I would use functions from magit; likely `magit-git-string` and `magit-run-git`.

**Pull request closed without merging**
