### PR TITLE
Add recipe for lispyville

### PR DESCRIPTION
**Pull request by noctuid**
[lispyville](https://github.com/noctuid/lispyville) is a package written by myself that provides methods for better integrating evil with lispy. It is similar to evil-cleverparens in that it provides "safe" operators (i.e. they won't unbalance parentheses) as well as other commands/motions, but it uses lispy instead of smartparens.

### CODE REVIEW

**Comment by purcell** [comment]
You've got a spurious `elpa.el` in that repository which will get bundled into the package. Can you maybe remove the file, or move it to a subdir?

Also, can you depend on non-zero stable versions of `lispy` and `evil` please? Check on MELPA Stable to find these, e.g. https://stable.melpa.org/#/lispy

**Comment by noctuid** [comment]
I moved it into a subdirectory.

> Also, can you depend on non-zero stable versions of lispy and evil please? 

I can't depend on a stable version for lispy (my package won't work with the latest stable version), but I added a version number for evil.

**Comment by purcell** [comment]
> I can't depend on a stable version for lispy (my package won't work with the latest stable version), but I added a version number for evil.

Cool. You should therefore probably depend on the next planned stable version of lispy, because `0` says that the current stable version will work fine.

**Comment by noctuid** [comment]
Thanks, I will.

**Comment by bpstahlman** [comment]
@noctuid Can you elaborate on the statement, "I can't depend on a stable version for lispy (my package won't work with the latest stable version)". I'm having trouble, documented [here](https://github.com/noctuid/lispyville/issues/15), and I'm wondering whether it could have something to do with this.

Where can I find documentation on lispyville installation and configuration? I assumed I wouldn't need to do anything but load lispyville in a lispy-mode hook. Do I also need to install a specific version of lispy, or is that handled automatically by lispyville package dependencies?

**Pull request merged**
