### PR TITLE
add git-grep

### PR DESCRIPTION
**Pull request by tychoish**
### Brief summary of what the package does

Provides `find-grep` like interface around git-grep

### Direct link to the package repository

https://github.com/tychoish/git-grep.el

### Your association with the package

This is a very small but extremely useful package that I've been using
for years and I wanted to extract it and package it up for general use. 

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! How does this differ from the built-in `vc-git-grep` command?

**Comment by tychoish** [comment]
Mainly: better UX/defaults, and can use projectile run queries repo-wide to avoid getting stuck in the repository.

**Comment by riscy** [comment]
For my sake (and maybe your `;;; Commentary`'s sake, which just says "commentary") can you describe the better UX/defaults in some more detail?

On a quick glance it looks like you want to use the var `git-grep-command` for the string in `git-grep-repo`, too.

**Comment by tychoish** [comment]
I've made these changes! Thanks for spotting those things!

**Comment by riscy** [comment]
Okay, I think the motivation is good.  Thanks for this.

**Pull request merged**
