### PR TITLE
Add receipe for ide.

### PR DESCRIPTION
**Pull request by sthilaid**
**Brief summary of what the package does**
ide: A simple major mode that reads a project/solution file and makes working within it or searching through it a lot easier. (supports and works best when using google codesearch)

**Direct link to the package repository**
https://github.com/sthilaid/ide

**Your association with the package**
Author / maintainer.

**Relevant communications with the upstream package maintainer**
This is a follow up from the pull request: https://github.com/melpa/melpa/pull/8773

I don't know how to fix most of the package lint warnings such as adding depencies on certain version of emacs
There are some docstrings warning/errors that I couldn't care to fix either. Hopefully these are not showstoppers...

Thanks!

Checklist
- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

`ide.el` with byte-compile using Emacs 29.1:

```
In toplevel form:
ide.el:41:2: Warning: custom-declare-variable `ide-custom-get-next-file' docstring wider than 80 characters
ide.el:41:12: Warning: defcustom for `ide-custom-get-next-file' fails to specify type
ide.el:66:2: Warning: custom-declare-variable `ide-additionnal-source-paths' docstring wider than 80 characters
ide.el:71:2: Warning: custom-declare-variable `ide-extensions' docstring wider than 80 characters
ide.el:117:2: Warning: custom-declare-variable `ide-solution-relative-include-path' docstring wider than 80 characters
ide.el:122:2: Warning: custom-declare-variable `ide-solution-include-style' docstring has wrong usage of unescaped single quotes (use \= or different quoting)

In ide-parse-current-solution:
ide.el:350:2: Warning: docstring wider than 80 characters

In ide-get-substrings:
ide.el:375:2: Warning: docstring wider than 80 characters
ide.el:375:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)

In ide-read-with-last-value:
ide.el:433:2: Warning: docstring wider than 80 characters

In ide-get-line-project:
ide.el:466:2: Warning: docstring wider than 80 characters

In ide-parse-additional-folders:
ide.el:499:2: Warning: docstring wider than 80 characters

In ide-parse-vs-project:
ide.el:539:2: Warning: docstring wider than 80 characters

In ide-parse-xcode-project:
ide.el:606:2: Warning: docstring wider than 80 characters

In ide-try-to-parse-text-solution:
ide.el:682:2: Warning: docstring wider than 80 characters
ide.el:682:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)

In ide-find-file:
ide.el:705:2: Warning: docstring wider than 80 characters

In ide-get-next-file:
ide.el:773:2: Warning: docstring wider than 80 characters

In ide-find-and-create-other-file:
ide.el:835:2: Warning: docstring wider than 80 characters

In ide-current-word-or-region:
ide.el:844:2: Warning: docstring wider than 80 characters

In ide-compilation-finish-handler:
ide.el:988:7: Warning: reference to free variable `ide-mode'
ide.el:1147:20: Warning: defcustom for `ide-mode' fails to specify containing group

In ide-mode:
ide.el:1147:2: Warning: docstring wider than 80 characters
```

`ide-browser.el` with byte-compile using Emacs 29.1:

```
In ide-browser-find-file:
ide-browser.el:18:52: Warning: reference to free variable `ide-current-solution'

In ide-browser-mode:
ide-browser.el:24:65: Warning: reference to free variable `ide-current-solution'

In end of data:
ide-browser.el:46:11: Warning: the function `ide-data-size' is not known to be defined.
ide-browser.el:25:24: Warning: the function `ide-data-projects' is not known to be defined.
ide-browser.el:24:89: Warning: the function `ide-data-file-paths' is not known to be defined.
ide-browser.el:23:24: Warning: the function `ide-data-file-names' is not known to be defined.
```

`ide.el` with checkdoc (0.6.2)

```
ide.el:0: You should have a section marked ";;; Commentary:"
ide.el:34: You should have a section marked ";;; Code:"
ide.el:1160: The footer should be: (provide 'ide)\n;;; ide.el ends here
ide.el:87: First line should be capitalized
ide.el:108: First line should be capitalized
ide.el:118: There should be two spaces after a period
ide.el:134: Argument `config-name' should appear (as CONFIG-NAME) in the doc string
ide.el:134: There should be two spaces after a period
ide.el:168: All variables and subroutines might as well have a documentation string
ide.el:171: All variables and subroutines might as well have a documentation string
ide.el:174: All variables and subroutines might as well have a documentation string
ide.el:177: All variables and subroutines might as well have a documentation string
ide.el:180: All variables and subroutines might as well have a documentation string
ide.el:183: All variables and subroutines might as well have a documentation string
ide.el:186: All variables and subroutines might as well have a documentation string
ide.el:189: All variables and subroutines might as well have a documentation string
ide.el:192: All variables and subroutines might as well have a documentation string
ide.el:195: All variables and subroutines might as well have a documentation string
ide.el:198: All variables and subroutines might as well have a documentation string
ide.el:201: All variables and subroutines might as well have a documentation string
ide.el:204: All variables and subroutines might as well have a documentation string
ide.el:230: Probably "Shows" should be imperative "Show"
ide.el:238: All variables and subroutines might as well have a documentation string
ide.el:245: All variables and subroutines might as well have a documentation string
ide.el:248: All variables and subroutines might as well have a documentation string
ide.el:251: All variables and subroutines might as well have a documentation string
ide.el:254: All variables and subroutines might as well have a documentation string
ide.el:257: All variables and subroutines might as well have a documentation string
ide.el:260: All variables and subroutines might as well have a documentation string
ide.el:263: All variables and subroutines might as well have a documentation string
ide.el:266: All variables and subroutines might as well have a documentation string
ide.el:269: All variables and subroutines might as well have a documentation string
ide.el:272: First sentence should end with punctuation
ide.el:272: Probably "Resets" should be imperative "Reset"
ide.el:287: Argument `config-name' should appear (as CONFIG-NAME) in the doc string
ide.el:314: Argument `solution-file' should appear (as SOLUTION-FILE) in the doc string
ide.el:368: Argument `file' should appear (as FILE) in the doc string
ide.el:368: Probably "Returns" should be imperative "Return"
ide.el:376: Some lines are over 80 columns wide
ide.el:376: Argument `str' should appear (as STR) in the doc string
ide.el:392: Argument `file' should appear (as FILE) in the doc string
ide.el:410: Argument `use-buffer-context-as-default?' should appear (as USE-BUFFER-CONTEXT-AS-DEFAULT?) in the doc string
ide.el:434: Argument `id' should appear (as ID) in the doc string
ide.el:434: There should be two spaces after a period
ide.el:450: All variables and subroutines might as well have a documentation string
ide.el:457: First sentence should end with punctuation
ide.el:457: First line should be capitalized
ide.el:457: Argument `msg' should appear (as MSG) in the doc string
ide.el:467: First sentence should end with punctuation
ide.el:467: Argument `line-str' should appear (as LINE-STR) in the doc string
ide.el:479: First sentence should end with punctuation
ide.el:479: Argument `original-path' should appear (as ORIGINAL-PATH) in the doc string
ide.el:479: Probably "Tries" should be imperative "Try"
ide.el:490: First sentence should end with punctuation
ide.el:490: Argument `original-folder' should appear (as ORIGINAL-FOLDER) in the doc string
ide.el:515: All variables and subroutines might as well have a documentation string
ide.el:518: All variables and subroutines might as well have a documentation string
ide.el:522: All variables and subroutines might as well have a documentation string
ide.el:540: Argument `project-file' should appear (as PROJECT-FILE) in the doc string
ide.el:556: All variables and subroutines might as well have a documentation string
ide.el:572: All variables and subroutines might as well have a documentation string
ide.el:584: Argument `project-file-dir' should appear (as PROJECT-FILE-DIR) in the doc string
ide.el:607: Argument `project-file' should appear (as PROJECT-FILE) in the doc string
ide.el:617: All variables and subroutines might as well have a documentation string
ide.el:623: Argument `current-solution' should appear (as CURRENT-SOLUTION) in the doc string
ide.el:623: Probably "Tries" should be imperative "Try"
ide.el:623: There should be two spaces after a period
ide.el:636: All variables and subroutines might as well have a documentation string
ide.el:639: First sentence should end with punctuation
ide.el:639: Argument `solution-dir' should appear (as SOLUTION-DIR) in the doc string
ide.el:653: All variables and subroutines might as well have a documentation string
ide.el:662: All variables and subroutines might as well have a documentation string
ide.el:683: Argument `sln-file' should appear (as SLN-FILE) in the doc string
ide.el:683: Probably "Tries" should be imperative "Try"
ide.el:683: There should be two spaces after a period
ide.el:706: Argument `file-name-arg' should appear (as FILE-NAME-ARG) in the doc string
ide.el:706: There should be two spaces after a period
ide.el:706: There should be two spaces after a period
ide.el:774: First sentence should end with punctuation
ide.el:774: Argument `file' should appear (as FILE) in the doc string
ide.el:774: Probably "Returns" should be imperative "Return"
ide.el:774: There should be two spaces after a period
ide.el:796: Argument `original-file' should appear (as ORIGINAL-FILE) in the doc string
ide.el:830: First sentence should end with punctuation
ide.el:830: Probably "Goes" should be imperative "Go"
ide.el:836: First sentence should end with punctuation
ide.el:836: Probably "Goes" should be imperative "Go"
ide.el:845: First line should be capitalized
ide.el:845: Probably "returns" should be imperative "return"
ide.el:851: First sentence should end with punctuation
ide.el:851: Argument `searched-str' should appear (as SEARCHED-STR) in the doc string
ide.el:866: First sentence should end with punctuation
ide.el:866: First line should be capitalized
ide.el:866: Argument `project' should appear (as PROJECT) in the doc string
ide.el:884: First line should be capitalized
ide.el:884: Argument `searched-str' should appear (as SEARCHED-STR) in the doc string
ide.el:898: First sentence should end with punctuation
ide.el:898: Argument `cmd' should appear (as CMD) in the doc string
ide.el:910: Argument `target' should appear (as TARGET) in the doc string
ide.el:925: All variables and subroutines might as well have a documentation string
ide.el:930: All variables and subroutines might as well have a documentation string
ide.el:944: All variables and subroutines might as well have a documentation string
ide.el:947: All variables and subroutines might as well have a documentation string
ide.el:950: All variables and subroutines might as well have a documentation string
ide.el:970: Argument `project' should appear (as PROJECT) in the doc string
ide.el:987: First sentence should end with punctuation
ide.el:987: First line should be capitalized
ide.el:987: Argument `buffer' should appear (as BUFFER) in the doc string
ide.el:1009: Probably "Returns" should be imperative "Return"
ide.el:1047: Argument `process' should appear (as PROCESS) in the doc string
ide.el:1047: Probably "changes" should be imperative "change"
ide.el:1058: Probably "Returns" should be imperative "Return"
ide.el:1098: Argument `process' should appear (as PROCESS) in the doc string
ide.el:1098: Probably "changes" should be imperative "change"
ide.el:1105: First line should be capitalized
ide.el:1105: Argument `search-flag' should appear (as SEARCH-FLAG) in the doc string
ide.el:1145: First line should be capitalized
ide.el:1148: First line should be capitalized
ide.el:1148: There should be two spaces after a period
ide.el:1148: There should be two spaces after a period
ide.el:460: Messages should start with a capital letter
ide.el:1024: Messages should start with a capital letter
ide.el:1076: Messages should start with a capital letter
ide.el:1113: Messages should start with a capital letter
```

`ide-browser.el` with checkdoc (0.6.2)

```
ide-browser.el:0: The first line should be of the form: ";;; package --- Summary"
ide-browser.el:0: You should have a section marked ";;; Commentary:"
ide-browser.el:1: You should have a section marked ";;; Code:"
ide-browser.el:53: The footer should be: (provide 'ide-browser)\n;;; ide-browser.el ends here
ide-browser.el:2: All interactive functions should have documentation
ide-browser.el:15: All interactive functions should have documentation
ide-browser.el:22: First sentence should end with punctuation
ide-browser.el:44: First sentence should end with punctuation
ide-browser.el:10: Messages should start with a capital letter
ide-browser.el:47: Messages should start with a capital letter
```

`ide.el` with package-lint (20230905.629)

```
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a ;;; Commentary section.
1:0: error: Package should have a Homepage or URL header.
1:0: error: package.el cannot parse this buffer: Search failed: ";;; ide.el ends here"
160:8: warning: Closing parens should not be wrapped onto new lines.
281:1: error: You should depend on (emacs "24.4") if you need `define-error'.
398:6: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
411:20: error: You should depend on (emacs "25.1") or the seq package if you need `seq-uniq'.
412:21: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
423:22: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
438:19: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
470:32: error: You should depend on (emacs "24.4") if you need `string-suffix-p'.
481:13: error: You should depend on (emacs "25.1") or the seq package if you need `seq-empty-p'.
482:13: error: You should depend on (emacs "25.1") or the seq package if you need `seq-some'.
482:37: error: You should depend on (emacs "24.4") if you need `string-suffix-p'.
491:3: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
501:3: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
515:3: error: You should depend on (emacs "24.4") if you need `string-suffix-p'.
517:0: error: "is-line-vs-project?" doesn't start with package's prefix "ide".
572:12: error: You should depend on (emacs "24.4") if you need `string-suffix-p'.
574:9: error: You should depend on (emacs "24.4") if you need `string-suffix-p'.
592:47: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
662:3: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
720:20: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
724:8: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-caddr'.
746:20: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
750:8: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-caddr'.
787:56: error: You should depend on (emacs "24.3") if you need `file-name-base'.
875:24: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
954:26: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-reduce'.
997:28: error: You should depend on (emacs "24.1") if you need `switch-to-next-buffer'.
1023:10: error: You should depend on (emacs "24.1") if you need `process-live-p'.
1075:10: error: You should depend on (emacs "24.1") if you need `process-live-p'.
1140:49: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
1141:54: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
1142:53: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
1147:0: error: Global minor modes should be autoloaded or, rarely, `:require' their defining file (i.e. ":require 'ide"), to support the customization variable of the same name.
```

`ide-browser.el` with package-lint (20230905.629)

```
1:0: error: Error parsing main package file "d:/_workspace/_lang/elisp/ide/ide.el": (search-failed ;;; ide.el ends here)
16:16: error: You should depend on (emacs "24.3") if you need `tabulated-list-get-entry'.
32:57: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
33:57: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
34:57: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-loop'.
36:3: error: You should depend on (emacs "24.1") if you need `tabulated-list-init-header'.
50:7: error: You should depend on (emacs "24.1") if you need `tabulated-list-print'.
```

Package and license:

- None (You might want to add a LICENSE file to your repository)

**Comment by riscy** [comment]
Thanks @sthilaid for this.  Note in @jcs090218 that checkdocs are "within reason".  I also have the following feedback:

`ide.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ide.el#L307: It's safer to sharp-quote function names; use `#'`
- ide.el#L288: It's safer to sharp-quote function names; use `#'`
- ide.el#L725: It's safer to sharp-quote function names; use `#'`
- ide.el#L751: It's safer to sharp-quote function names; use `#'`
- ide.el#L1003: It's safer to sharp-quote function names; use `#'`
- ide.el#L398: Could this point/point-max comparison use `eobp`?
- ide.el#L663: Could this point/point-max comparison use `eobp`?
- ide.el#L1003: Loading a package should rarely add hooks (maybe this should be done as part of toggling the mode on or off)
- ide.el#L131: Top-level `setq` should usually be replaced by `defvar` (note `defvar` takes an initial-value argument which you should be using)
- ide.el#L211: Top-level `setq` should usually be replaced by `defvar`
- ide.el#L214: Top-level `setq` should usually be replaced by `defvar`
- ide.el#L217: Top-level `setq` should usually be replaced by `defvar`
- ide.el#L220: Top-level `setq` should usually be replaced by `defvar`
- ide.el#L223: Top-level `setq` should usually be replaced by `defvar`
- ide.el#L227: Top-level `setq` should usually be replaced by `defvar`
- ide.el#L306: No `format` required; `message` takes an f-string
- ide.el#L858: `concat` may be unneeded; `insert` can take multiple arguments
- ide.el#L1035: `concat` may be unneeded; `insert` can take multiple arguments
- ide.el#L1085: `concat` may be unneeded; `insert` can take multiple arguments
```

`#'load`-check on each file:
```
Loading ide.el
  ide.el:Error: Emacs 28.1:
  (error "Unknown keyword :Type")
```

- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee
- ide-browser.el needs *formal* license boilerplate and/or an [SPDX-License-Identifier](https://spdx.dev/ids/)

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by riscy** [comment]
Hi @sthilaid - it may make sense for us to close this and the subsequent PRs next week if there's no activity.  But don't worry, you can always re-open these PRs when you have the time.

**Comment by riscy** [comment]
Hi @sthilaid - per [this comment](https://github.com/melpa/melpa/pull/8796#issuecomment-1868583863) I'll close this and the PRs with issues you made around the same time.  But do remember that you can always re-open these (preferably one at a time) if you'd like to discuss further, and I'll be happy to help.

**Pull request closed without merging**
