### PR TITLE
Add recipe for ob-deno

### PR DESCRIPTION
**Pull request by taiju**
### Brief summary of what the package does

Babel Functions for Javascript/TypeScript with the [Deno](https://deno.land/)

I was going to write a patch for ob-js, but it felt strange to be able to run typescript in ob-js.

I could have also written a patch to ob-typescript, but I decided to make it a dedicated package, as there are times when I simply write JavaScript.

### Direct link to the package repository

https://github.com/taiju/ob-deno

### Your association with the package

author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass.

### ob-deno.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
ob-deno.el:48: Argument `body' should appear (as BODY) in the doc string
Warning (emacs): 
ob-deno.el:97: Argument `params' should appear (as PARAMS) in the doc string
```

package-lint (using version 20200906.512):
```
17 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:80: warning: You should depend on (emacs "24.1") if you need lexical-binding.
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
33:10: error: You should depend on (emacs "24.1") if you need `ob'.
38:0: error: "org-babel-deno-cmd" doesn't start with package's prefix "ob-deno".
43:0: error: "org-babel-deno-function-wrapper" doesn't start with package's prefix "ob-deno".
53:21: error: You should depend on (emacs "24.1") if you need `org-babel-expand-body:generic'.
55:30: error: You should depend on (emacs "24.1") if you need `org-babel-temp-file'.
63:6: error: You should depend on (emacs "24.1") if you need `org-babel-eval'.
65:8: error: You should depend on (emacs "24.1") if you need `org-babel-process-file-name'.
67:5: error: You should depend on (emacs "24.4") if you need `org-babel-result-cond'.
70:0: error: "org-babel-deno-read" doesn't start with package's prefix "ob-deno".
74:3: error: You should depend on (emacs "24.1") if you need `org-babel-read'.
77:6: error: You should depend on (emacs "24.4") if you need `string-suffix-p'.
78:8: error: You should depend on (emacs "24.1") if you need `org-babel-read'.
88:0: error: "org-babel-deno-var-to-deno" doesn't start with package's prefix "ob-deno".
101:4: error: You should depend on (emacs "26.1") if you need `org-babel--get-vars'.
```

Other possible lints:
- ob-deno.el#L3: Have you done the paperwork or is this copy-pasted?
- ob-deno.el#L9: Copy-paste error?

**Comment by taiju** [comment]
Sorry, the error has been corrected.

**Comment by taiju** [comment]
I have added some features.
I have rechecked the above pointers.

**Comment by riscy** [comment]
No worries.  I think now that you have removed the mistaken copy-pastes, you must (re-)add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to ob-deno.el.

It would also be a good idea to expand your Commentary from `ob-deno is based on ob-js`, although I realize a lot of the `ob-` packages on MELPA have very terse Commentary.  [Here](https://melpa.org/#/ob-dart)'s a good example (although TODO's in Commentary seems sort of gauche to me).

Minor:
- ob-deno.el#L85: There is no need to quote lambdas (neither #' nor ')

**Comment by taiju** [comment]
Thank you for your kindness.  I have responded with the following commits.
- https://github.com/taiju/ob-deno/commit/4ded8c3aa54d82ccf32ef5a82af3e488b6fcc786
- https://github.com/taiju/ob-deno/commit/739ef8379c37e239e63245a8f393861b3edc4f5d
- https://github.com/taiju/ob-deno/commit/3107e2a71b69d32c548cc6bbaef4d1907afa51b3

**Comment by riscy** [comment]
Looks good.  And, welcome to MELPA! :)

**Pull request merged**
