### PR TITLE
Add evil-tex recipe

### PR DESCRIPTION
**Pull request by iyefrat**
### Brief summary of what the package does

An evil-mode oriented minor mode for LaTeX document editing, inspired by the [vimtex](https://github.com/lervag/vimtex) vim plugin.

### Direct link to the package repository

https://github.com/iyefrat/evil-tex

### Your association with the package

I am the co-author and co-maintainer of the package, along with @ymarco

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass.

byte-compile (using Emacs 26.3):
```
evil-tex.el:738:8:Warning: reference to free variable `which-key-idle-delay'
In evil-tex-bind-to-env-map:
evil-tex.el:878:15:Warning: reference to free variable `evil-tex-env-map'
In evil-tex-bind-to-cdlatex-accents-map:
evil-tex.el:932:15:Warning: reference to free variable
    `evil-tex-cdlatex-accents-map'
evil-tex.el:1025:4:Warning: reference to free variable
    `which-key-replacement-alist'
vil-tex.el:1025:4:Warning: assignment to free variable
    `which-key-replacement-alist'
In evil-tex-set-up-surround:
evil-tex.el:1109:52:Warning: reference to free variable
    `evil-surround-pairs-alist'
evil-tex.el:1109:52:Warning: assignment to free variable
    `evil-surround-pairs-alist'
evil-tex.el:1113:19:Warning: reference to free variable
    `evil-surround-local-inner-text-object-map-list'
evil-tex.el:1115:19:Warning: reference to free variable
    `evil-surround-local-outer-text-object-map-list'
evil-tex.el:1114:18:Warning: assignment to free variable
    `evil-surround-local-inner-text-object-map-list'
evil-tex.el:1116:18:Warning: assignment to free variable
    `evil-surround-local-outer-text-object-map-list'
In evil-tex-set-up-embrace:
evil-tex.el:1124:16:Warning: reference to free variable
    `evil-embrace-evil-surround-keys'
evil-tex.el:1124:16:Warning: assignment to free variable
    `evil-embrace-evil-surround-keys'
evil-tex.el:1152:19:Warning: assignment to free variable
    `evil-snipe--last-direction'
In end of data:
evil-tex.el:1215:1:Warning: the following functions are not known to be
    defined: which-key--show-keymap, evil-snipe-t
```

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200616.2257):
```
10 issues found:
822:0: error: `evil-tex-cdlatex-accents:rm' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
825:0: error: `evil-tex-cdlatex-accents:it' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
828:0: error: `evil-tex-cdlatex-accents:sl' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
832:0: error: `evil-tex-cdlatex-accents:bold' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
835:0: error: `evil-tex-cdlatex-accents:emph' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
838:0: error: `evil-tex-cdlatex-accents:tt' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
841:0: error: `evil-tex-cdlatex-accents:sf' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
1022:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
1208:5: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
1210:5: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
```

Suggestions/experimental static checks:
- evil-tex.el#L742: It's safer to sharp-quote function names; use `#'`
- evil-tex.el#L718: Ensure this `fset` isn't being used as a surrogate `defalias`
- evil-tex.el#L723: Ensure this `fset` isn't being used as a surrogate `defalias`
- evil-tex.el#L724: Ensure this `fset` isn't being used as a surrogate `defalias`
- evil-tex.el#L5: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- evil-tex.el#L5: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- evil-tex.el#L29: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading evil-tex.el
Done.
```

**Comment by ymarco** [comment]
I fixed the http links and sharp-quote, but the other errors are somewhat intentional.

All the references to free variables are integrations that evil-tex supports but not require: which-key to help with keymaps we read through lookup-key, evil-surround to surround with our text objects and not only select them, etc. Currently we do these things with `(when (require 'PACKAGE nil t) ...)` or with `eval-after-load`, which generates these free variable reference errors... If there's a better way, please inform us!

The `fset` errors are because we name some lambda functions when inserting them into keymaps, so which-key can show preview of what each lambda does. AUCTeX does this as well, I'm not sure we can evade this. 

Lastly, the `:` in function names: this is used to distinguish functions in special surround keymaps, so we can easily match them with regexps inside `which-key-replacement-alist`, [here](https://github.com/itai33/evil-tex/blob/master/evil-tex.el#L1021-L1025). It makes the which-key popup much more readable. We could probably replace the colons with something like triple hyphens, but is that necessary?

**Comment by riscy** [comment]
> All the references to free variables are integrations that evil-tex supports but not require

Ah, I see.  I think we can still get the elisp to byte-compile cleanly in this case.  For example for `which-key-idle-delay`, you can add a line `(defvar which-key-idle-delay)` at the top of your elisp file.  For a function like `evil-snipe-t` you can use `(declare-function evil-snipe-t "ext:evil-snipe" ...)`.

I think the eval-after-load warnings:
```
1058:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
1180:5: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
1182:5: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
```
are legitimate.  Users should use these, packages typically shouldn't -- and in your case I think you should rely solely on patterns like `(when (require 'which-key nil t) ...`.  I believe this prevents situations like the following contrived example: user installs evil-tex, doesn't like it, unloads the feature.  In the same Emacs instance, user installs which-key, activates it, and now has evil-tex stuff happening that wasn't expected.

> The fset errors are because we name some lambda functions

They were also vague on my part, sorry about that.  This looks okay to me.

> We could probably replace the colons with something like triple hyphens, but is that necessary?

Your case is totally sensical, but I personally try to be pretty strict with these.  It's an elisp coding convention, package-lint (which is essentially the MELPA standard) checks for it.  Most importantly it's just easier for reviewers if the rule is simple ("use hyphens").  Otherwise we'd have to have a more nuanced rule that carefully prohibits specific things like unicode and emojis and other nonsense. 🙂

**Comment by iyefrat** [comment]
I fixed the all the warnings except the ones relating to the `:`'s. Regarding those, are they find to leave as is, or should we replace them with more hyphens?

**Comment by riscy** [comment]
I'd ask you to address the feedback of package-lint in this case.  Sometimes packages can get grandfathered in, but I don't believe that's the case here?

**Comment by iyefrat** [comment]
Done.

**Comment by riscy** [comment]
Thanks a lot for accommodating.  And, welcome to MELPA! :)

**Comment by iyefrat** [comment]
@riscy Thank you for helping!

**Pull request merged**
