### PR TITLE
Add autothemer

### PR DESCRIPTION
**Pull request by jasonm23**
### Brief summary of what the package does

Autothemer provides a facespec wrapper for deftheme.  Essentially it thins down the overhead needed to implement a color-class based theme correctly.  

Face specs and a palette are simpler to write and arbitrary code that also needs to use the palette can be included easily.

### Direct link to the package repository

https://github.com/sebastiansturm/autothemer/

### Your association with the package

Enthusiastic user / interested party.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by jasonm23** [comment]
I should add that I was involved in the original discussion that led to Autothemer.  

I haven't had involvement beyond that.

I did reach out to @sebastiansturm and open an issue for publication to MELPA.

**Comment by syohex** [comment]
I have sent PR.
- https://github.com/sebastiansturm/autothemer/pull/3

**Comment by sebastiansturm** [comment]
thanks, I merged this. Anything else I can/should do?

**Comment by syohex** [comment]
Merged

**Pull request merged**
