### PR TITLE
New package: execline

### PR DESCRIPTION
**Pull request by KAction**
This package provides major mode for editing execline scripts.

### Brief summary of what the package does

This package provides major mode for editing [execline](http://skarnet.org/software/execline/) scripts.

### Direct link to the package repository

https://gitlab.com/KAction/emacs-execline

### Your association with the package
I am maintainer of package.

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
"Page not found"

**Comment by KAction** [comment]
Fixed. gitlab, not github.

**Comment by riscy** [comment]
This looks solid.  Browsing around tells me the `.ex` extension is (also) associated with Elixir as well as another language I just discovered called Euphoria.  Maybe there's nothing to be done about that, but I notice that the execline page you link contains source code with a `.txt` extension!  Even the C repo (https://github.com/skarnet/execline) doesn't seem to have any files with extensions.

So, just to clarify, is `.ex` the standard execline extension?

**Comment by purcell** [comment]
Thanks! Couple of notes:
- You should modify the buffer-local version of `completion-at-point-functions` [here](https://gitlab.com/KAction/emacs-execline/blob/deafc87649fa135e030c1b3bfc11b6488ff3fdba/execline.el#L210) rathter than the global version
- Use `\\'` and not `$` to match end-of-string in the `auto-mode-alist` entry [here](https://gitlab.com/KAction/emacs-execline/blob/deafc87649fa135e030c1b3bfc11b6488ff3fdba/execline.el#L220)
- There's a built-in `bolp` function you could use [here](https://gitlab.com/KAction/emacs-execline/blob/deafc87649fa135e030c1b3bfc11b6488ff3fdba/execline.el#L176)

Hope that helps!

**Comment by KAction** [comment]
[2019-06-29 20:50] Chris Rayner <notifications@github.com>
> So, just to clarify, is `.ex` the standard execline extension?

No. As far as I know, there is no standard extension. If `.ex` conflicts
with other languages, I can use another extension, like `.exec'.

Another approach would be to detect major mode based on shebang. It will
work for editing scripts, but not for freshly-created.
-- 
Note, that I send and fetch email in batch, once in a few days.
Please, mention in body of your reply when you add or remove recepients.

**Comment by KAction** [comment]
[2019-06-30 14:49] Steve Purcell <notifications@github.com>
> Thanks! Couple of notes:
> [...]

Thank you. I applied your suggestions and pushed v0.5 tag.
-- 
Note, that I send and fetch email in batch, once in a few days.
Please, mention in body of your reply when you add or remove recepients.

**Comment by riscy** [comment]
> No. As far as I know, there is no standard extension. If `.ex` conflicts with other languages, I can use another extension, like `.exec'.

I think this'd be a good idea since .ex seems to have been claimed by Elixir. :\  Maybe this is your big chance to claim a unique extension for execline, at least in among Emacs users. :)

**Comment by riscy** [comment]
There's a comment [here](https://gitlab.com/KAction/emacs-execline/blob/master/execline.el#L33) that needs updating re: `.exec` instead of `.ex` files, but that's not a blocker.  Altogether this looks great - welcome to MELPA!

**Comment by KAction** [comment]
[2019-07-04 15:01] Chris Rayner <notifications@github.com>

> > No. As far as I know, there is no standard extension. If `.ex`
> > conflicts with other languages, I can use another extension, like `.exec'.

> I think this'd be a good idea since .ex seems to have been claimed by
> Elixir. :\  Maybe this is your big chance to claim a unique extension
> for execline, at least in among Emacs users. :)

Just did it. .ex -> .exec; pushed as tag v0.6
-- 
Note, that I send and fetch email in batch, once in a few days.
Please, mention in body of your reply when you add or remove recepients.

**Pull request merged**
