### PR TITLE
add noaa

### PR DESCRIPTION
**Pull request by thomp**
### Brief summary of what the package does

An interface for viewing forecast data at api.weather.gov.

### Direct link to the package repository

https://github.com/thomp/noaa

### Your association with the package

Author and maintainer of the package

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Silex** [comment]
Why not `defcustom` for the longitude/latitude?

Also missing autoload cookies for the interactive functions, and also those are not mentionned in the README :wink:

**Comment by thomp** [comment]
Thanks for the time you invest in package reviews. 

No good answer for not using defcustom. https://github.com/thomp/noaa/commit/1170ab59eef7a1df25a4814bdde12726b715224a

Added autoload magic comments https://github.com/thomp/noaa/commit/459f51c7436161351a18b3d524098fdaa330724b and cleaned up the README https://github.com/thomp/noaa/commit/72455cfcbfabbd0d258a1bdfc730ff81a3109200 .

Also realized it wouldn't hurt to define a license. https://github.com/thomp/noaa/commit/1198eed7cf2960a5b91f8750a08c906c716b53ff

**Comment by Silex** [comment]
Good job! :+1: 

I'm not an official reviewer, but it's likely what would have been said. We'll see :-)

**Comment by purcell** [comment]
Thanks, this is nice, and would work nicely with my [osx-location](https://github.com/purcell/osx-location/) package! I'll go ahead and merge this PR, but a couple of small points:

- Perhaps use `special-mode` rather than `text-mode`; not only is it semantically closer to what you want, it provides the `q` binding for free.
- `define-derived-mode` will automatically define the keymap for you, so you can remove its declaration.

**Pull request merged**
