### PR TITLE
new repo and update branch

### PR DESCRIPTION
**Pull request by hexmode**

### CODE REVIEW

**Comment by purcell** [comment]
Re. `holiday-pascha-etc`:
- `provide` form is missing
- `emacs` in the package description is redundant, and should be removed
- Needs a brief `;;; Commentary:` section to describe what the package is and how to use it

The other change looks good. I dislike it when developers hide all their ongoing work in a non-default branch... it rather misses the point of github, which is full of developers rather than end-users.

**Comment by hexmode** [comment]
I'm not sure what you mean by hiding on-going work.  I had the idea for this a year ago, but only now sat down to do it.  All this is just from this mornings work. (But you're probably talking about something I'm completely missing...)

I'll work on the issues you pointed out tomorrow.

**Comment by purcell** [comment]
I'm referring to the `next` branch of `terranpro/magit-gerrit`, not to anything you've done. :-)

**Comment by tarsius** [comment]
`magit-gerrit` has a `next` branch because `magit` did the same for a while. But since `magit`'s `next` branch was merged more than a year ago, it's about time the same happens for `magit-gerrit` now.

/cc @terranpro

**Comment by terranpro** [comment]
D'oh - been out of the loop for awhile, and things change so fast!
Thanks for the ping, will merge up and bid farewell to the `next` branch.

**Comment by hexmode** [comment]
could you re-check now?

**Comment by purcell** [comment]
Looks good, thanks.

**Pull request closed without merging**
