### PR TITLE
Add xwidgete recipe

### PR DESCRIPTION
**Pull request by tuhdo**
The repo is here: https://github.com/tuhdo/xwidgete

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, but `xwidgete.el` isn't formatted with the standard elisp boilerplate, so it isn't a valid package in its current form. In particular, you need the standard `;;; xwidgete.el --- Your short description here` first line, and a trailing `;;; xwidgete.el ends here` trailing line.

**Comment by tuhdo** [comment]
Done.

**Comment by vyp** [comment]
@tuhdo I think it needs three dashes like `;;; xwidgete.el ---` in the header line, instead of two like `;;; xwidgete.el --`. Not sure though.

**Comment by tuhdo** [comment]
Oh yes it's true 3 dashes are needed. Fixed. Thanks.

**Comment by purcell** [comment]
Thanks, merged. You should also add a `;;; Commentary:` section providing an overview of how to use the package. :-)

**Pull request merged**
