### PR TITLE
Add dap-mode recipe

### PR DESCRIPTION
**Pull request by yyoncho**
### Brief summary of what the package does

`dap-mode` is an emacs integration for Debug Adapter Protocol which is the protocol used by VScode/Eclipse Che for integration with the debugger. Together with LSP mode the package aims to provide full IDE experince for Emacs. Currently supports Java debugger.

### Direct link to the package repository

https://github.com/yyoncho/dap-mode

### Your association with the package

Author/Maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

I don't have the expertise to use or review the package, but one suggestion: You probably don't need to autoload so many commands, just the one that would be the entry point into the package.

**Comment by yyoncho** [comment]
@alphapapa Thanks for your comment I will fix it. This is my first package, so feel free to provide any advice.

**Comment by purcell** [comment]
This looks good, but it's more of an interface than a mode as the name implies, so can I please suggest renaming it to `dap`? This would just involve renaming/editing `dap-mode.el` and the recipe.

Also, thanks for your patience.

**Comment by yyoncho** [comment]
@purcell thanks for the feedback I don't mind renaming the file but I would prefer to keep the current name in order to be consistent with the related `lsp-mode` since the code have similar architecture: `dap-mode.el` -> `lsp-mode.el`,  `dap-ui.el` -> `lsp-ui.el`, `dap-java.el` -> `lsp-java.el`, etc. Furthermore, all of the ui related code is in a separate file(`dap-ui.el`) and could potentionally grow into separate package(similar to what has happened to `lsp-mode`). What do you think?

**Comment by purcell** [comment]
Yeah, I think `lsp-mode` is misnamed, so I wouldn't necessarily recommend copying that scheme, but I guess I can live with either name. I'll go ahead and merge now.

**Comment by purcell** [comment]
Done - welcome to MELPA! :tada:

**Comment by prabhu-madanagopal** [comment]
Thanks, can't wait to package-install.

**Pull request merged**
