### PR TITLE
Add chemtable recipe

### PR DESCRIPTION
**Pull request by sergiruiztrepat**
### Brief summary of what the package does

Periodic table of the elements.

### Direct link to the package repository

https://github.com/sergiruiztrepat/chemtable

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x]  I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by purcell** [comment]
This is neat! As a quick initial comment, you should avoid including colour names in the names of your faces: they can be customised to be completely different colours, after all. Instead, give the faces semantic names.

I would also suggest that you make a basic face called something like `chemtable-element-face`, with a `box` of width 1, and then your other faces can `:inherit` that face.

Generally it's best to avoid choosing specific colour combinations, because it clashes with theming, and might therefore look terrible by default in many people's configurations, or on dark/light backgrounds. A better solution is usually to arbitrarily `:inherit` built-in faces, so you could have:

```
(defface chemtable-element-face '((t :inherit button)))

(defface chemtable-noble-gases-face '((t :inherit (chemtable-element-face font-lock-keyword-face)))
...
```
etc.

**Comment by riscy** [comment]
I'll also roll through and very quickly mention these byte-compile warnings:

byte-compile (using Emacs 27.1):
```
chemtable.el:239:1:Warning: Unused lexical variable
    `widget-push-button-suffix'
chemtable.el:239:1:Warning: Unused lexical variable
    `widget-push-button-prefix'
```
I think they're completely unused, so the line(s) could both be removed.

**Comment by sergiruiztrepat** [comment]
Hi @purcell and @riscy ! 

I've made the changes suggested by @purcell about faces.

> I'll also roll through and very quickly mention these byte-compile warnings:
> 
> byte-compile (using Emacs 27.1):
> 
> ```
> chemtable.el:239:1:Warning: Unused lexical variable
>     `widget-push-button-suffix'
> chemtable.el:239:1:Warning: Unused lexical variable
>     `widget-push-button-prefix'
> ```
> 
> I think they're completely unused, so the line(s) could both be removed.

These two variables (set to "") are to avoid the default brackets of widget buttons. I prefer not to have brackets but I don't know how to avoid these byte-compile warnings.

Thanks!

**Comment by riscy** [comment]
> These two variables (set to "") are to avoid the default brackets of widget buttons.

Right, I should have known better. :)

I think those warnings pop up because those variables aren't autoloaded, which seems to be how widget.el depends on wid-edit.el.  I think the best way to pacify the byte-compiler in this case is probably to add `(eval-when-compile (require 'wid-edit))` below `(require 'xwidget)`.

**Comment by sergiruiztrepat** [comment]
Hi @riscy ,
I've added your suggestion (eval-when-compile ...). Can you check if it pacifies the byte-compiler? I cannot see any warning in Emacs 28.
Thanks!

**Comment by riscy** [comment]
Yes, all look good here.  I gave it a try and this looks quite cool. With great luck I discovered Tungsten is missing a space in the data table (`"W "`) but that's not a blocker.  Thanks!

**Pull request merged**
