### PR TITLE
Add say-what-im-doing recipe

### PR DESCRIPTION
**Pull request by Benaiah**
This package makes emacs say the commands you invoke out loud, using text-to-speech.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. You need to put a package description after the `---` on the first line, and you should also add an `;;;###autoload` cookie comment for the `define-minor-mode` form.

**Comment by purcell** [comment]
(Also, running `M-x checkdoc` and fixing the errors reported would be a very good idea.)

**Comment by Benaiah** [comment]
Ok, I've fixed the issues you brought up and corrected the checkdoc errors (there's technically one checkdoc error left, but it's because it thinks the phrase command-line in a docstring is a symbol, when it's just referring to the command line).

**Comment by purcell** [comment]
Great, thanks.

**Pull request merged**
