### PR TITLE
Add recipe for gsnip

### PR DESCRIPTION
**Pull request by kaiwk**
### Brief summary of what the package does

A Gitlab Snippet client, and inspired by [gist.el](https://github.com/defunkt/gist.el).

### Direct link to the package repository

https://github.com/kaiwk/gsnip

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass.

### gsnip.el ###

byte-compile (using Emacs 26.3):
- gsnip.el#L1: Don't set `no-byte-compile: t`.
  Byte-compiling is enabled in what follows
```
gsnip.el:81:23:Warning: reference to free variable `url-http-end-of-headers'
In gsnip--fetch-raw:
gsnip.el:100:22:Warning: reference to free variable `url-http-end-of-headers'
In gsnip--post-snippet:
gsnip.el:155:43:Warning: reference to free variable `url-http-end-of-headers'
In gsnip--show-current-snippet:
gsnip.el:254:13:Warning: assignment to free variable `gsnip-id'
In end of data:
gsnip.el:391:1:Warning: the following functions are not known to be defined:
    json-read-from-string, string-trim, url-http-parse-response, json-encode,
    parse-iso8601-time-string
```

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200616.2257):
- No issues!


### Loadability ###

Verifying ability to #'load each file:
```
Loading gsnip.el
Done.
```

**Comment by kaiwk** [comment]
thank you @riscy, i have fixed the issue above.

**Comment by riscy** [comment]
Apologies for the delay on writing back -- these issues seem to persist:

byte-compile (using Emacs 27.1):
```
gsnip.el:85:23:Warning: reference to free variable `url-http-end-of-headers'
In gsnip--fetch-raw:
gsnip.el:104:22:Warning: reference to free variable `url-http-end-of-headers'
In gsnip--post-snippet:
gsnip.el:159:43:Warning: reference to free variable `url-http-end-of-headers'
In gsnip--show-current-snippet:
gsnip.el:258:13:Warning: assignment to free variable `gsnip-id'
```

**Comment by riscy** [comment]
Looks like you can fix the `gsnip-id` one by defvaring it before you setq it.

The `url-http-end-of-headers` looks like it's being checked by the aio macro before your `require`'s have a chance to be brought in.  You can fix this by adding `(defvar url-http-end-of-headers)` to your file.

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by riscy** [comment]
I was wrong about `url-http-end-of-headers` -- `url-http` only does `(defvar url-http-end-of-headers)` without setting a value.  You can use the same fix I described, but the reason is different.

**Comment by kaiwk** [comment]
thank you, riscy,

It seems I can't reproduce the warning on my emacs (version 27.1), i have set `byte-compile-warnings` to `t`. But if set `byte-compile-error-on-warn` to `t`, there will be an **error** about `url-http-end-of-headers`.

I tried to fix the warning you described anyway:

https://github.com/kaiwk/gsnip/commit/9029177199f491794d9ea97e26bcc498e7833c9e

 is that right?

**Comment by riscy** [comment]
That's got it.  Thanks!

**Pull request merged**
