### PR TITLE
Add recipe for clj-deps-new

### PR DESCRIPTION
**Pull request by jpe90**
### Brief summary of what the package does

It provides an interface to [deps.new](https://github.com/seancorfield/deps-new) using [transient](https://github.com/magit/transient), providing functions to create Clojure projects from templates within Emacs. 

Specifically, it provides actions for creating deps.edn applications, libraries, scratch projects, other templates, and pom.xml files.

### Direct link to the package repository

https://github.com/jpe90/emacs-deps-new

### Your association with the package

I am the author and maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Cool, thank you for this and for your close adherence to the checklist.

I'm not familiar with clj-deps-new, but I wonder if you may want to run `shell-quote-argument` against some of the `opts` that `clj-deps-new--assemble-command` takes -- for example what if the project folder name has a space in it, or a special shell character like `'` or ``` ` ``` in it?  But other than that consideration I don't see any blockers.

**Comment by jpe90** [comment]
Thank you for the review and catching that! I pushed a commit shell-quoting the project `name` argument and the `target-dir` opt, which covers everything the user can type in. Does that look okay to you?

**Comment by riscy** [comment]
Great, looks good to me.  Thanks!

**Comment by jpe90** [comment]
Thank you!

**Pull request merged**
