### PR TITLE
Add recipe for run-command

### PR DESCRIPTION
**Pull request by bard**
### Brief summary of what the package does

Allows picking (via Helm or Ivy) external commands from dynamic, context-dependent lists, and running them via `compile'.

### Direct link to the package repository

https://github.com/bard/emacs-run-command

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

### run-command.el ###

byte-compile (using Emacs 27.1):
```
run-command.el:115:1:Warning: Unused lexical argument `value'
run-command.el:115:1:Warning: Unused lexical variable `project-name'
run-command.el:177:1:Warning: Unused lexical argument `name-of-mode'
In run-command--helm-action:
run-command.el:225:34:Warning: reference to free variable
    `helm-current-prefix-arg'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
run-command.el:143: All variables and subroutines might as well have a documentation string
Warning (emacs): 
run-command.el:147: All variables and subroutines might as well have a documentation string
Warning (emacs): 
run-command.el:160: All variables and subroutines might as well have a documentation string
Warning (emacs): 
run-command.el:178: All variables and subroutines might as well have a documentation string
Warning (emacs): 
run-command.el:210: All variables and subroutines might as well have a documentation string
Warning (emacs): 
run-command.el:214: All variables and subroutines might as well have a documentation string
Warning (emacs): 
run-command.el:224: All variables and subroutines might as well have a documentation string
Warning (emacs): 
run-command.el:235: All variables and subroutines might as well have a documentation string
Warning (emacs): 
run-command.el:249: All variables and subroutines might as well have a documentation string
```

package-lint (using version 20200906.512):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- run-command.el#L210: It's safer to sharp-quote function names; use `#'`
- run-command.el#L147: Optionally use `unless ...` instead of `when (not ...)`
- run-command.el#L149: Optionally use `unless ...` instead of `when (not ...)`
- run-command.el#L152: Optionally use `unless ...` instead of `when (not ...)`
- run-command.el#L154: Optionally use `unless ...` instead of `when (not ...)`
- run-command.el#L156: Optionally use `unless ...` instead of `when (not ...)`
- run-command.el#L24: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by bard** [comment]
Thanks for looking at this @riscy!

> Quick first pass --
> 
> ### run-command.el
> byte-compile (using Emacs 27.1):
> 
> ```
> run-command.el:115:1:Warning: Unused lexical argument `value'
> run-command.el:115:1:Warning: Unused lexical variable `project-name'
> run-command.el:177:1:Warning: Unused lexical argument `name-of-mode'
> ```

I had noticed the ones about arguments (not the second one— fix just pushed), however just removing e.g. `name-of-mode` [here](https://github.com/bard/emacs-run-command/blob/1e84bca6c4824b944844ff774a0543c0aefe0c5b/run-command.el#L186) silences the compiler but later results in a `Wrong number of arguments` when that function is called in `compile.el`. Shall I disable lexical-binding? The code doesn't really need it, but it's enabled to follow MELPA contributing guidelines. Alternatively, is there a way to tell the compiler "I know this argument won't be used", like `_variable` in some languages?

> In run-command--helm-action:
> run-command.el:225:34:Warning: reference to free variable
>     `helm-current-prefix-arg'
> ```

Fixed according to https://www.gnu.org/software/emacs/manual/html_node/elisp/Compiler-Errors.html, "Likewise, you can tell the compiler that a variable is defined using defvar with no initial value. (Note that this marks the variable as special, i.e. dynamically bound, but only within the current lexical scope, or file if at top-level.) See Defining Variables." Hopefully that's the right way.

> checkdoc (using version 0.6.2):
> 
> ```
> Warning (emacs): 
> run-command.el:143: All variables and subroutines might as well have a documentation string
> Warning (emacs): 
> run-command.el:147: All variables and subroutines might as well have a documentation string
> Warning (emacs): 
> run-command.el:160: All variables and subroutines might as well have a documentation string
> Warning (emacs): 
> run-command.el:178: All variables and subroutines might as well have a documentation string
> Warning (emacs): 
> run-command.el:210: All variables and subroutines might as well have a documentation string
> Warning (emacs): 
> run-command.el:214: All variables and subroutines might as well have a documentation string
> Warning (emacs): 
> run-command.el:224: All variables and subroutines might as well have a documentation string
> Warning (emacs): 
> run-command.el:235: All variables and subroutines might as well have a documentation string
> Warning (emacs): 
> run-command.el:249: All variables and subroutines might as well have a documentation string
> ```

I assumed that for internals (`package--*` as opposed to `package-*`), since they're not intended to be called from external code, documentation strings wouldn't be strictly required. Wrong?

> package-lint (using version 20200906.512):
> 
> * No issues!
> 
> Other [lints](https://github.com/riscy/melpazoid):
> 
> * run-command.el#L210: It's safer to sharp-quote function names; use `#'`
> * run-command.el#L147: Optionally use `unless ...` instead of `when (not ...)`
> * run-command.el#L149: Optionally use `unless ...` instead of `when (not ...)`
> * run-command.el#L152: Optionally use `unless ...` instead of `when (not ...)`
> * run-command.el#L154: Optionally use `unless ...` instead of `when (not ...)`
> * run-command.el#L156: Optionally use `unless ...` instead of `when (not ...)`
> * run-command.el#L24: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

Fixed!

**Comment by riscy** [comment]
> Alternatively, is there a way to tell the compiler "I know this argument won't be used", like _variable in some languages?

Exactly that -- prefix with an underscore.

> Hopefully that's the right way.

Yep!

> I had assumed that for internals (package--* as opposed to package-*), since they're not intended to be called from external code, documentation strings wouldn't be strictly required. Wrong?

There's at least one other MELPA maintainer who agrees with you, so you're not alone. :)  However, it is easiest for me to just be a robo-pedant and tell people "make checkdoc green", up to a few very minor exceptions like its nags about proper nouns, wrong voice, and congruence with whatever `sentence-end-double-space` happens to be set to...

I'd say try to make checkdoc green because it's actually not that hard in this case, but you could consider raising an issue that we make that checkdoc unimportant.  Then we'd probably update CONTRIBUTING.org to reflect that.

**Comment by bard** [comment]
> > Alternatively, is there a way to tell the compiler "I know this argument won't be used", like _variable in some languages?
> 
> Exactly that -- prefix with an underscore.

*facepalm* I could swear I had tried that with no success.

> I'd say try to make checkdoc green because it's actually not that hard in this case, but you could consider raising an issue that we make that checkdoc unimportant. Then we'd probably update CONTRIBUTING.org to reflect that.

Yep, made it green, no big deal, I was just wondering about the general reasoning so next time can go smoother.

**Comment by riscy** [comment]
Thanks, look good to go. :)

**Pull request merged**
