### PR TITLE
Add recipe for abs-mode, a major mode for the modeling language Abs

### PR DESCRIPTION
**Pull request by rudi**
### Brief summary of what the package does

A major mode for the modeling language Abs (http://docs.abs-models.org/)

### Direct link to the package repository

https://github.com/abstools/abs-mode/

### Your association with the package

Author, maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
(note: package-lint complains about unversioned dependencies, but these are legal and I don't depend on specific versions for `erlang' and `maude-mode')
- [x] My elisp byte-compiles cleanly
(note: two deprecation warnings wrt flymake on emacs 26.1, but I want to support emacs 25 if possible)
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- Please use versioned dependencies [here](https://github.com/abstools/abs-mode/blob/336719ded3b5320abce3057b8bf932247a636e8a/abs-mode.el#L8), even if you have to use `"0"`. The bare package name format is not understood by older versions of `package.el`, so is to be avoided. `package-lint` should have mentioned this.
- Don't initialize executable paths using `executable-find` like [this](https://github.com/abstools/abs-mode/blob/336719ded3b5320abce3057b8bf932247a636e8a/abs-mode.el#L58) - just use the bare executable name. `executable-find` might lock in a wrong path that is changed later, whereas the bare program name will be looked up using the path that is in effect at the time it is needed.

Looks good otherwise. :-)

**Comment by rudi** [comment]
Many thanks for the review!  Both issues are fixed in e676a02e2b64fe84abaa7360ef4051beb6ea080f

Additionally, 726a1a0f2292779702d905777f1e545033af592f obsoletes `abs-indent`, which was inactive since we switched to cc-mode indenting (existing users have this as a file-local variable so it can't be removed without disrupting their work).

**Comment by rudi** [comment]
Ping - is there something else I should do?  No rush, just want to make sure we're not mutually waiting on each other.
(Should I have removed the "awaiting-upstream" tag somehow?)

**Comment by purcell** [comment]
> Ping - is there something else I should do? No rush, just want to make sure we're not mutually waiting on each other.
> (Should I have removed the "awaiting-upstream" tag somehow?)

Nope, looks good. Merged now - thanks for your patience.

**Pull request merged**
