### PR TITLE
Add dotnet.el

### PR DESCRIPTION
**Pull request by julienXX**
### Brief summary of what the package does

Interact with dotnet CLI tool for .NET Core.

### Direct link to the package repository

https://github.com/julienXX/dotnet.el

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick feedback:
- You'll need to declare a package dependency on `cl-lib`. `package-lint` should have told you about this when you ran it.
- You're doing a lot of `read-string` in your commands: instead, add an arg to the commands and use `(interactive "sPackage name: ")` to have it magically read for you.
- Don't explicitly use `ido-completing-read`: just call `completing-read`. This is then overridden by various completion systems as preferred by the individual user.
- `C-c C-c` is a very common command binding. Instead, perhaps provide a prefix map that the user can bind to their preferred key.
Hope that helps!

**Comment by julienXX** [comment]
> - You'll need to declare a package dependency on cl-lib. package-lint should have told you about this when you ran it.

Removed the dependency as I don't use it yet.

> - You're doing a lot of read-string in your commands: instead, add an arg to the commands and use (interactive "sPackage name: ") to have it magically read for you.

Thanks! That's a lot better.

> - Don't explicitly use ido-completing-read: just call completing-read. This is then overridden by various completion systems as preferred by the individual user.

Cool, I even have swiper completion now :)

> - C-c C-c is a very common command binding. Instead, perhaps provide a prefix map that the user can bind to their preferred key.

Good catch, it's been updated.

Thanks @purcell for the great suggestions!

**Comment by purcell** [comment]
Thanks. Sent you some fixes in https://github.com/julienXX/dotnet.el/pull/1. Once merged, this PR is good to go... :-)

**Comment by julienXX** [comment]
@purcell merged and thanks again for the lesson in emacs lisp :)

**Comment by purcell** [comment]
No worries. Make sure you test it, though, in case I broke something. :-)

**Pull request merged**
