### PR TITLE
Add recipe for mu4e-crypto

### PR DESCRIPTION
**Pull request by meritamen**
### Brief summary of what the package does

Encrypt and decrypt emails for mu4e with GnuPG

### Direct link to the package repository

https://github.com/meritamen/mu4e-crypto

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

You'll have to forgive me because I'm not a mu4e user, but have you considered the approach in [the docs](https://www.djcbsoftware.nl/code/mu/mu4e/Signing-and-encrypting.html)?  Is there a key difference here worth highlighting in your `;;; Commentary`?

In the meantime, `mu4e-crypto.el` with byte-compile using Emacs 29.1:
```
mu4e-crypto.el:59:26: Warning: reference to free variable `mu4e-crypto-pgp-message-begin'
mu4e-crypto.el:60:26: Warning: reference to free variable `mu4e-crypto-pgp-message-end'
In mu4e-crypto-decrypt-message:
mu4e-crypto.el:74:26: Warning: reference to free variable `mu4e--crypto-decrypted-buffer-name'
```
Likely these variables just need to be `defvar`'d at the top of your source file.

**Comment by meritamen** [comment]
@riscy Thank you for the review.

Mu4e-crypto directly replaces messages with ciphertext, the approach in [the docs](https://www.djcbsoftware.nl/code/mu/mu4e/Signing-and-encrypting.html) encrypts messages when sending them. In comparison my package is more straightforward(clumsy), but it somehow guarantees safety. Whatever, encrypting function in mu4e-crypto is the counterpart of decrypting function which help decrypt plain PGP messages, this doesn't seem to be well supported in mu4e.

Just fixed the issues and added some notes in `;;; Commentary`.

**Comment by riscy** [comment]
Gotcha, and thank you for clarifying.

I actually gave you bad advice, and I think these are not `defvar`'s but `defconst`s (you don't want them changed by users, or for users to think they can change them):

```elisp
(defconst mu4e-crypto--pgp-message-begin "-----BEGIN PGP MESSAGE-----")

(defconst mu4e-crypto--pgp-message-end "-----END PGP MESSAGE-----")

(defconst mu4e-crypto--decrypted-buffer-name "*mu4e-decrypted*")
```

And just a couple of minor notes on style -- I'll focus on `mu4e-crypto--mark-constraint`.  Instead of:
```elisp
(defun mu4e-crypto--mark-constraint (begin end)
  "Search and mark region closed by `BEGIN' and `END'.
Argument BEGIN string begin.
Argument END string end."
  (goto-char (point-min))
  (if (search-forward begin nil t)
      (progn
        (beginning-of-line)
        (push-mark (point) nil t)
        (if (search-forward end nil t)
            nil
          (error "%s not matched" end)))
    (error "%s not matched" begin)))
```
I would recommend you write:
```elisp
(defun mu4e-crypto--mark-constraint (begin end)
  "Search and mark region closed by BEGIN and END."
  (goto-char (point-min))
  (if (not (search-forward begin nil t))
      (user-error "%s not matched" begin)
    (beginning-of-line)
    (push-mark (point) nil t)
    (if (not (search-forward end nil t))
        (user-error "%s not matched" end))))
```
So the things I've changed are:
-  No back/front quotes around BEGIN and END, just the capitalization is the expected way to denote variables to the online help.
- The extra docstring content  "Argument BEGIN string begin." is unnecessary (from both a checkdoc and a user-comprehension perspective, imo)
- I prefer to rewrite `if` forms to not use `progn` and not have unnecessarily empty bodies, and in a lot of cases this makes things easier to read (less nesting, early exits, etc.)
- It looks like you want `user-error` instead of `error` for this particular case.  `error` can open a backtrace spool to the user and indicates a bug with YOUR code.  `user-error` just gives the user a message, and indicates the user is doing something wrong/has a wrong setup

I think we should definitely fix the `defconst` stuff (which is my fault, sorry again) and the rest of what I wrote are minor issues (non-blocking) and style tips.  And then this'll look good to go.

**Comment by meritamen** [comment]
Thanks for advice, fixed these problems.

**Comment by riscy** [comment]
Thank you, and sorry to hang you up on this, but I just noticed:
```elisp
    (let* ((secret (buffer-substring-no-properties (region-beginning) (region-end)))
           (temp-dir (expand-file-name "~/.cache/"))
           (temp-file (make-temp-name (expand-file-name "emacs-mu4e-crypto-" temp-dir))))
```
in `mu4e-crypto-decrypt-message`.  Are you expecting `~/.cache` to exist because of something mu4e does? (And excuse my ignorance again).  Or are you manually implementing something akin to `(temporary-file-directory)`?

This looks good to go, but I just wanted to clear that up before I hit merge.

**Comment by meritamen** [comment]
Hi @riscy, I wanted to store ciphertext into temporary files in `~/.cache` so that `call-process` could be executed with the arguments `gpp --decrypt` and `temp-file`.
```
(call-process "gpg" nil "*mu4e-decrypted*" nil
                    "--decrypt" temp-file)
```
And just realized temporary files are not good, so I reimplemented it, looks like more hygienic.
```
;;;###autoload
(defun mu4e-crypto-decrypt-message ()
  "Decrypt email content of current mu4e buffer."
  (interactive)
  (when
      (and (mu4e-crypto--message-p)
           (mu4e-crypto--gpg-exists-p)
           (mu4e-crypto--pgp-message-exists-p))
    (mu4e-crypto--mark-pgp-encrypted-message)
    (let ((secret (buffer-substring-no-properties (region-beginning) (region-end))))
      (switch-to-buffer (get-buffer-create mu4e-crypto--decrypted-buffer-name))
      (insert secret)
      (unless (zerop (shell-command-on-region
                      (point-min) (point-max) "gpg --decrypt"
                      mu4e-crypto--decrypted-buffer-name t))
        (user-error "Decrtption failed")))))
```

**Comment by riscy** [comment]
Thank you!  I will merge this now.  (I notice one typo in that block of code you pasted, where `Decrtption` should be `Decryption`).  I might even write `"Decryption failed: gpg exited with a non-zero return code"` to make it clear what went wrong.

**Pull request merged**
