### PR TITLE
new package: sudoku

### PR DESCRIPTION
**Pull request by zevlg**
### Brief summary of what the package does

sudoku game for GNU Emacs.  

Features:

   * Custom puzzle editor
   * Printing puzzles (TeX source generator)
   * Puzzle Solver (simple heuristics + trial and error)
   * Auto-insert assistance (S1, H1, CC i.e. Constrained Cell)
   * Step-by-step puzzle deduce (using S1, H1 and CC heuristics)
   * Nifty pencils (assist for Nishio, Cycles, Loops)
   * Undo/Redo operations
   * Optimal (single solution) puzzles generator (very
     straightforward, but usable)
   * Board downloader (from websudoku.com and menneske.no)
   * Save/Load puzzles
   * Collection of built-in puzzles

### Direct link to the package repository

https://github.com/zevlg/gnu-emacs-stuff/blob/master/sudoku.el

### Your association with the package

I'm author and maintainer.  I like it a lot ;)

### Relevant communications with the upstream package maintainer

None

### Checklist

- [*] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [*] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by tarsius** [comment]
Could you please put this into its own repository instead of "gnu-emacs-stuff". That doesn't really matter for Melpa, but if you don't do that, then I won't be able to add it to the Emacsmirror.

**Comment by zevlg** [comment]
Done, also checked package building with new repository

**Comment by syohex** [comment]
- Please squash commits
- There are too many byte-compile warnings, please check them.
- No autoload cookie
- Some functions does not have package prefix

**Comment by zevlg** [comment]
will do, but let me first try with simpler package

sudoku.el was adopted from (S)XEmacs, so it has some compatibility stuff that yells warnings

**Comment by tarsius** [comment]
Thanks @zevlg!

**Comment by zevlg** [comment]
will do another, clean pull request later

**Pull request closed without merging**
