### PR TITLE
Add lsp-elixir recipe

### PR DESCRIPTION
**Pull request by Trevoke**
### Brief summary of what the package does

This is a LSP client for Elixir.

### Direct link to the package repository

https://github.com/trevoke/lsp-elixir

### Your association with the package

I am the author and current maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by purcell** [comment]
Looks good - merged, thanks. Sorry for the slow turnaround.

**Comment by Trevoke** [comment]
Hi Steve, thank you for taking the time to look it over and making sure it fit the standards of code quality that help keep emacs great :)

**Comment by tarsius** [comment]
@Trevoke The name of *packages* do not end with ".el". I have fixed this.

**Comment by purcell** [comment]
Thanks @tarsius

**Comment by Trevoke** [comment]
Never mind - guess who forgot how to use `use-package`.

**Pull request merged**
