### PR TITLE
add comby.el recipe

### PR DESCRIPTION
**Pull request by s-kostyaev**
### Brief summary of what the package does

`comby.el` is a simple wrapper around [`comby`](https://comby.dev/).
Comby is a tool for searching and changing code structure.

### Direct link to the package repository

https://github.com/s-kostyaev/comby.el

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

byte-compile (using Emacs 26.3):
```
comby.el:105:47:Warning: assignment to free variable `comby--current-command'
In end of data:
comby.el:159:1:Warning: the following functions are not known to be defined:
    flatten-list, project-root
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
comby.el:65: Argument `&key' should appear (as &KEY) in the doc string
```

package-lint (using version 20200419.406):
- No issues!

Suggestions/experimental static checks:
- comby.el#L78: It's safer to sharp-quote function names; use `#'`
- comby.el#L83: It's safer to sharp-quote function names; use `#'`
- comby.el#L92: It's safer to sharp-quote function names; use `#'`
- comby.el#L97: It's safer to sharp-quote function names; use `#'`
- comby.el#L112: It's safer to sharp-quote function names; use `#'`
- comby.el#L61: You can use `not` or `null`

### Loadability ###

Verifying ability to #'load each file:
```
Loading comby.el
Done.
```

### Package ###

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by s-kostyaev** [comment]
Thank you for review @riscy. Fixed.

**Comment by riscy** [comment]
It seems checkdoc's unable to see that you have documented `&key`
```
Warning (emacs): 
comby.el:65: Argument `&key' should appear (as &KEY) in the doc string
```
and I don't quite understand its role here.  Maybe more importantly, why have you named it this way?  I haven't seen this before, or any use of &key [in the documentation around argument lists](https://www.gnu.org/software/emacs/manual/html_node/elisp/Argument-List.html).

**Comment by s-kostyaev** [comment]
I have emacs 28 with native comp, so I don't see this warning. Maybe it should be `&keys` ? I try to make next argument the named one.

**Comment by s-kostyaev** [comment]
Let it unnamed to make checkdoc happy. Done.

**Comment by riscy** [comment]
Thanks -- comby looks interesting.  Good to merge, but I notice a missing article in the commentary:

> This package is simple wrapper for https://comby.dev/

should be

> This package is a simple wrapper for https://comby.dev/

**Pull request merged**
