### PR TITLE
Remove "asn1-mode" package

### PR DESCRIPTION
**Pull request by sirikid**
This [package](https://github.com/kawabata/asn1-mode) was last updated 5 years ago and just doesn't work.

<details>

<summary>
Figure. 
</summary>

image

</details>

Left window shows error in empty buffer due to incorrect SMIE configuration. Right window shows incorrect indentation with the mode.

### CODE REVIEW

**Comment by riscy** [comment]
Thank you for pointing this out.  I wonder if @yasuyk (who originally opened the PR) or @kawabata might like to comment here.

(Also, raising the issue with the upstream repo would be even better than raising it here, although if this package is abandoned it might have a better home with emacsorphanage for example.)

**Comment by riscy** [comment]
I've raised an issue at the upstream issue (as you can see).  I'll give the authors (of the package itself, or this recipe) another little while to chime in, and then I'll try and confirm that it is not a working package.

@sirikid do you have any specific interest in this package, such as taking it over?  If so, check out https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks which may have some helpful information for you.

**Comment by sirikid** [comment]
> @sirikid do you have any specific interest in this package, such as taking it over? If so, check out https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks which may have some helpful information for you.

No. I've looked at it and I don't see an easy fix. I just don't want people to think that Emacs has an ASN.1 mode, while it is not.

**Comment by tarsius** [comment]
> This [package](https://github.com/kawabata/asn1-mode) was last updated 5 years ago and just doesn't work.

I appreciate that you are doing this to save other users from having to experience the same frustration that you had to go through, but I'm not sure that is actually true.

The first issues concerns `show-paren-mode`. That is optional functionality; if it does not work in one major-mode, then you can just turn it off.

I don't know this language, so I don't know how badly the indentation is broken. Maybe it is only broken for some newer language feature. Even if it is completely broken, the major-mode may still be of use to other users; they would have to indent manually, but might still enjoy the syntax highlighting.

**Comment by sirikid** [comment]
> The first issues concerns `show-paren-mode`. That is optional functionality; if it does not work in one major-mode, then you can just turn it off.

It is enabled by default, I tested the package in `emacs -q`

**Comment by tarsius** [comment]
But have you tried turning it off?

**Comment by sirikid** [comment]
> But have you tried turning it off?

Yes, but that does not make this mode any better.

**Comment by tarsius** [comment]
Let me first repeat something I said earlier:

> I appreciate that you are doing this to save other users from having to experience the same frustration that you had to go through, but I'm not sure that is actually true.

In other words I can see how you are trying to do something for the benefit of other users. But I disagree that the proposed solution is the way to go about it.

As @riscy has done, the first step when encountering a broken package, is to get it fixed upstream, not to have it removed from Melpa. It doesn't look like anything is coming of that, and maybe you anticipated that.

Even so, I think it would be premature to remove this package at this point. I disagree that disabling a broken feature "doesn't make the package better". It makes it usable, and some users may prefer having mostly working syntax highlighting available, over having no support for the language at all.

**Pull request closed without merging**
