### PR TITLE
Update forth-mode.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Hello,

I'm the package author.  This is just a minor update to the existing recipe.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Fixes larsbrinkhoff/forth-mode#57.

**Comment by syohex** [comment]
Package contents are here. No problem ?

```
forth-mode-20161208.742/
forth-mode-20161208.742/backend/
forth-mode-20161208.742/backend/gforth.el
forth-mode-20161208.742/backend/lbforth.el
forth-mode-20161208.742/backend/pforth.el
forth-mode-20161208.742/backend/spforth.el
forth-mode-20161208.742/backend/swiftforth.el
forth-mode-20161208.742/backend/swiftforth.fth
forth-mode-20161208.742/backend/vfxforth.el
forth-mode-20161208.742/forth-block-mode.el
forth-mode-20161208.742/forth-interaction-mode.el
forth-mode-20161208.742/forth-mode-pkg.el ;; <- auto generated
forth-mode-20161208.742/forth-mode.el
forth-mode-20161208.742/forth-parse.el
forth-mode-20161208.742/forth-smie.el
forth-mode-20161208.742/forth-spec.el
forth-mode-20161208.742/forth-syntax.el
```

**Comment by larsbrinkhoff** [comment]
@syohex Is that the package contents before or after this update?

As per MELPA documentation, Lisp files in subdirectores are not included, so I added the `backend` directory.  Also, `build.el` isn't needed in the package; it's just for development.

**Comment by syohex** [comment]
> Is that the package contents before or after this update?

After this update ?

**Comment by larsbrinkhoff** [comment]
Right.  Yes, the content you listed looks good.  I also verified this by building the package before submitting a pull request.

**Comment by syohex** [comment]
Right, thanks.

**Comment by larsbrinkhoff** [comment]
Thank you too.

**Pull request merged**
