### PR TITLE
Add recipe for jc-themes

### PR DESCRIPTION
**Pull request by andreoss**
### Brief summary of what the package does

A theme.

### Direct link to the package repository

https://gitlab.com/andreoss/jc-themes

### Your association with the package

A maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for your patience!  Quick first pass --

`jc-obscure-theme.el` with byte-compile using Emacs 28.1:
- Temporarily ignoring `no-byte-compile` flag
```
jc-obscure-theme.el:22:1: Warning: Package cl is deprecated
```
Prefer `cl-lib` and the functions defined in there.

`jc-random-theme.el` with byte-compile using Emacs 28.1:
- Temporarily ignoring `no-byte-compile` flag
```
jc-random-theme.el:29:7: Warning: assignment to free variable `jc-colors'
jc-random-theme.el:173:36: Warning: reference to free variable `jc-colors'
jc-random-theme.el:171:7: Warning: assignment to free variable
    `jc-color-random'
In jc-color-randomish:
jc-random-theme.el:177:19: Warning: reference to free variable
    `jc-color-random'
```

`jc.el` with byte-compile using Emacs 28.1:
- Temporarily ignoring `no-byte-compile` flag
```
jc.el:185:10: Warning: `reduce' is an obsolete function (as of 27.1); use
    `cl-reduce' instead.
In end of data:
jc.el:102:17: Warning: the function `jc-zip' is not known to be defined.
```
For the undefined `jc-zip`, I'd just define it at the top-level to help the compiler out.

Stderr output while compiling/loading:
```
Warning (files): jc-obscure-theme.el: `lexical-binding' at end of file unreliable
```
You should put `lexical-binding` on the very first line after your summary (see many other packages and how they do it).

Package and license:
- jc-themes-pkg.el -- consider excluding; MELPA creates one
- Package-Requires mismatch between jc-obscure-theme.el and jc-themes-pkg.el!
- Package-Requires mismatch between jc-random-theme.el and jc-themes-pkg.el!
- Package-Requires mismatch between jc-sepia-theme.el and jc-themes-pkg.el!
- Package-Requires mismatch between jc-theme.el and jc-themes-pkg.el!
- Package-Requires mismatch between jc-themes.el and jc-themes-pkg.el!
- Package-Requires mismatch between jc.el and jc-themes-pkg.el!
- Add a GPL-compatible LICENSE file to the repository
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to each elisp file

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to ping for another pass.

**Comment by andreoss** [comment]
@riscy Please, take a look again. The mentioned issues are fixed

**Comment by riscy** [comment]
Thanks for accommodating -- here's the latest:

`jc-obscure-theme.el` with package-lint 20220607.738:
```
4 issues found:
1:0: error: There is no `provide' form.
8:0: error: Package-Requires outside the main file have no effect.
25:0: error: "jc-obscure" doesn't start with package's prefix "jc-themes".
30:0: error: "jc-color-obscure" doesn't start with package's prefix "jc-themes".
```
Note the "There is no 'provide' form" is a false positive; you can disregard this one and those below as long as you're using `provide-theme`.  The `Package-Requires` is not so much of a blocker, imo, but be aware of it.

`jc-obscure-theme.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- jc-obscure-theme.el#L1: `lexical-binding` must be on the end of the first line
```

`jc-random-theme.el` with byte-compile using Emacs 28.1:
- Temporarily ignoring `no-byte-compile` flag
```
jc-random-theme.el:30:7: Warning: assignment to free variable `jc-colors'
jc-random-theme.el:172:36: Warning: reference to free variable `jc-colors'
jc-random-theme.el:170:7: Warning: assignment to free variable
    `jc-color-random'
In jc-color-randomish:
jc-random-theme.el:176:19: Warning: reference to free variable
    `jc-color-random'
```

`jc-random-theme.el` with package-lint 20220607.738:
```
4 issues found:
1:0: error: There is no `provide' form.
8:0: error: Package-Requires outside the main file have no effect.
25:0: error: "jc-random" doesn't start with package's prefix "jc-themes".
174:0: error: "jc-color-randomish" doesn't start with package's prefix "jc-themes".
```

`jc-random-theme.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- jc-random-theme.el#L1: `lexical-binding` must be on the end of the first line
- jc-random-theme.el#L185: `load-file-name` is nil during `eval-buffer`; consider `(or load-file-name buffer-file-name)`
- jc-random-theme.el#L30: Top-level `setq` should usually be replaced by `defvar`
- jc-random-theme.el#L170: Top-level `setq` should usually be replaced by `defvar`
```

`jc-sepia-theme.el` with package-lint 20220607.738:
```
3 issues found:
1:0: error: There is no `provide' form.
8:0: error: Package-Requires outside the main file have no effect.
25:0: error: "jc-sepia" doesn't start with package's prefix "jc-themes".
```

`jc-sepia-theme.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- jc-sepia-theme.el#L1: `lexical-binding` must be on the end of the first line
```

`jc-theme.el` with package-lint 20220607.738:
```
3 issues found:
1:0: error: There is no `provide' form.
8:0: error: Package-Requires outside the main file have no effect.
23:0: error: "jc" doesn't start with package's prefix "jc-themes".
```

`jc-theme.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- jc-theme.el#L1: `lexical-binding` must be on the end of the first line
```

`jc.el` with byte-compile using Emacs 28.1:
- Temporarily ignoring `no-byte-compile` flag
```
jc.el:186:23: Warning: the function `reduce' is not known to be defined.
jc.el:99:17: Warning: the function `jc-zip' is not known to be defined.
jc.el:88:14: Warning: the function `fourth' is not known to be defined.
jc.el:67:68: Warning: the function `third' is not known to be defined.
jc.el:67:48: Warning: the function `second' is not known to be defined.
jc.el:67:27: Warning: the function `first' is not known to be defined.
```
Instead of `reduce`, `first`, `second`, etc. you shoul use `cl-reduce`, `cl-first`, ... (and add `(require 'cl-lib)`).

`jc.el` with package-lint 20220607.738:
```
25 issues found:
7:0: error: Package-Requires outside the main file have no effect.
27:0: error: "jc-color-split" doesn't start with package's prefix "jc-themes".
38:0: error: "jc-color-make" doesn't start with package's prefix "jc-themes".
42:0: error: "jc-color-grayscale" doesn't start with package's prefix "jc-themes".
48:0: error: "jc-color-inverse" doesn't start with package's prefix "jc-themes".
54:0: error: "jc-color-shade" doesn't start with package's prefix "jc-themes".
62:0: error: "jc-color-complement" doesn't start with package's prefix "jc-themes".
69:0: error: "jc-rbg-to-cmyk" doesn't start with package's prefix "jc-themes".
82:0: error: "jc-cmyk-to-rbg" doesn't start with package's prefix "jc-themes".
92:0: error: "jc-color-blend" doesn't start with package's prefix "jc-themes".
94:0: error: "jc-zip" doesn't start with package's prefix "jc-themes".
109:0: error: "jc-color-sepia" doesn't start with package's prefix "jc-themes".
122:0: error: "jc-color-luminance" doesn't start with package's prefix "jc-themes".
131:0: error: "jc-color-identity" doesn't start with package's prefix "jc-themes".
135:0: error: "jc-color-equal-p" doesn't start with package's prefix "jc-themes".
139:0: error: "jc-theme" doesn't start with package's prefix "jc-themes".
143:0: error: "jc-empty" doesn't start with package's prefix "jc-themes".
147:0: error: "jc-background-color" doesn't start with package's prefix "jc-themes".
152:0: error: "jc-red-color" doesn't start with package's prefix "jc-themes".
157:0: error: "jc-yellow-color" doesn't start with package's prefix "jc-themes".
162:0: error: "jc-blue-color" doesn't start with package's prefix "jc-themes".
167:0: error: "jc-green-color" doesn't start with package's prefix "jc-themes".
172:0: error: "jc-foreground-color" doesn't start with package's prefix "jc-themes".
177:0: error: "jc--combine" doesn't start with package's prefix "jc-themes".
186:0: error: "jc--init" doesn't start with package's prefix "jc-themes".
```

`jc.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- jc.el#L115: There is no need to quote lambdas (neither #' nor ')
- jc.el#L116: There is no need to quote lambdas (neither #' nor ')
- jc.el#L45: It's safer to sharp-quote function names; use `#'`
- jc.el#L52: It's safer to sharp-quote function names; use `#'`
- jc.el#L60: It's safer to sharp-quote function names; use `#'`
- jc.el#L129: It's safer to sharp-quote function names; use `#'`
- jc.el#L133: It's safer to sharp-quote function names; use `#'`
- jc.el#L10: `lexical-binding` must be on the end of the first line
- jc.el#L184: Top-level `setq` should usually be replaced by `defvar`
```

**Comment by riscy** [comment]
I'll mark this awaiting upstream, but feel free to reach out.

**Comment by tarsius** [comment]
This pull-request has been open for over half a year. @andreoss could you please get this over the finish line soon, or else close it? If you do the latter but still plan to get this into Melpa eventually, then you might want to add a quick message here. You can ask us to reopen this pull-request when you are ready.

**Comment by andreoss** [comment]
@tarsius 
added a CI pipeline, 
checkdock, package-lint and melpazoid are passing now

**Comment by andreoss** [comment]
@tarsius @riscy ping

**Comment by tarsius** [comment]
Thanks for the ping. @riscy does the reviews, usually on the weekends. Since that is over now and he has not done it in this cycle, he will probably do it next weekend. The ping makes that more likely at least.

**Comment by riscy** [comment]
Apologies for the long turnaround-I should have checked the label on this one sooner!  I’ll work to make sure that doesn’t happen again.

**Comment by riscy** [comment]
Having another look.  I think the aforementioned lexical-binding nags are still an issue.  e.g.
```elisp
;;; jc-themes-grayscale-theme.el --- Random
;; -*- lexical-binding: t -*-
```
should be
```elisp
;;; jc-themes-grayscale-theme.el --- Random -*- lexical-binding: t -*-
```
which I know can be surprising.  This should be fixed in each of the elisp files by the looks of things.

Less importantly, but still an issue, is that the metadata (summary lines, commentary) should be expanded on/filled in.  Most importantly in in jc-themes.el because this is where MELPA takes the index metadata from:
```elisp
;;; jc-themes.el --- Themes -*- lexical-binding: t -*-

;; URL: https://gitlab.com/andreoss/jc-theme
;; Keywords: faces
;; Version: 0.3
;; SPDX-License-Identifier: GPL-3.0-or-later
;; Package-Requires: ((emacs "25"))

;;; Commentary:
;; XXX
```
"Themes"  could at least be expanded to "A collection of themes".  But is there some feature of them that ties them together?  Is it a collection of minimalist themes, or a collection of monochromatic themes?  MELPA also brings the `;;; Commentary` into the index, and "XXX" would benefit from being expanded on.

Lastly - this is very minor, but still worth pointing out:
- jc-themes.el#L33: No `format` required; `error` takes an f-string

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out.

**Comment by riscy** [comment]
(And I promise I'll keep an eye out for replies this time; apologies again for that.)

**Comment by progfolio** [comment]
@andreoss Any interest in finishing this one off?

**Pull request closed without merging**
