### PR TITLE
Add zxc-dev recipe

### PR DESCRIPTION
**Pull request by zxcwindy**
### Brief summary of what the package does

file tag system and sql client

### Direct link to the package repository

https://github.com/zxcwindy/zxc-dev

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi!  Thank you for this.  A quick pass over the checklist follows.  I think there are quite a few checklist items that need to be addressed, but feel free to ask if you need further information on any of these --

### zxc-db-ac.el ###

byte-compile-file (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
zxc-db-ac.el:42:9:Warning: assignment to free variable `zxc-mode-lighter'
In zxc-db-ac-get-tables:
zxc-db-ac.el:50:55:Warning: reference to free variable `zxc-db-host'
In end of data:
zxc-db-ac.el:92:1:Warning: the following functions are not known to be
    defined: deferred:url-get, json-read-from-string
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
zxc-db-ac.el:25: You should have a section marked ";;; Code:"
Warning (emacs): 
zxc-db-ac.el:91: The footer should be: (provide 'zxc-db-ac)\n;;; zxc-db-ac.el ends here
Warning (emacs): 
zxc-db-ac.el:25: First sentence should end with punctuation
Warning (emacs): 
zxc-db-ac.el:25: First line should be capitalized
Warning (emacs): 
zxc-db-ac.el:30: First sentence should end with punctuation
Warning (emacs): 
zxc-db-ac.el:30: First line should be capitalized
Warning (emacs): 
zxc-db-ac.el:32: First sentence should end with punctuation
Warning (emacs): 
zxc-db-ac.el:32: First line should be capitalized
Warning (emacs): 
zxc-db-ac.el:36: First sentence should end with punctuation
Warning (emacs): 
zxc-db-ac.el:36: First line should be capitalized
Warning (emacs): 
zxc-db-ac.el:40: First sentence should end with punctuation
Warning (emacs): 
zxc-db-ac.el:40: First line should be capitalized
Warning (emacs): 
zxc-db-ac.el:40: Argument `alias' should appear (as ALIAS) in the doc string
Warning (emacs): 
zxc-db-ac.el:47: Documentation strings should not start or end with whitespace
Warning (emacs): 
zxc-db-ac.el:46: First line is not a complete sentence
Warning (emacs): 
zxc-db-ac.el:46: First line should be capitalized
Warning (emacs): 
zxc-db-ac.el:67: First sentence should end with punctuation
Warning (emacs): 
zxc-db-ac.el:67: First line should be capitalized
Warning (emacs): 
zxc-db-ac.el:77: First sentence should end with punctuation
Warning (emacs): 
zxc-db-ac.el:77: First line should be capitalized
Warning (emacs): 
zxc-db-ac.el:82: First sentence should end with punctuation
Warning (emacs): 
zxc-db-ac.el:82: First line should be capitalized
Warning (emacs): 
zxc-db-ac.el:60: Messages should start with a capital letter
```

package-lint-current-buffer (using version 20200419.406):
```
11 issues found:
4:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
25:0: error: "zxc-db-ac-tablename-url" doesn't start with package's prefix "zxc-dev".
28:0: error: "zxc-db-ac-db-alias" doesn't start with package's prefix "zxc-dev".
30:0: error: "zxc-db-ac-table-name-candidates" doesn't start with package's prefix "zxc-dev".
32:0: error: "zxc-db-ac-default-sources" doesn't start with package's prefix "zxc-dev".
34:0: error: "zxc-db-ac-source" doesn't start with package's prefix "zxc-dev".
39:0: error: "zxc-db-ac-set-db-alias" doesn't start with package's prefix "zxc-dev".
45:0: error: "zxc-db-ac-get-tables" doesn't start with package's prefix "zxc-dev".
66:0: error: "zxc-db-ac-previous-word" doesn't start with package's prefix "zxc-dev".
76:0: error: "zxc-db-ac-tablename-candidates" doesn't start with package's prefix "zxc-dev".
81:0: error: "zxc-db-ac-toggle" doesn't start with package's prefix "zxc-dev".
```

Suggestions/experimental static checks:
- zxc-db-ac.el#L18: Prefer `https` over `http` (if possible)

### zxc-db.el ###

byte-compile-file (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
zxc-db.el:79:31:Warning: function `getf' from cl package called at runtime
In zxc-db-create-table-buffer:
zxc-db.el:89:24:Warning: function `getf' from cl package called at runtime
In zxc-db-query-callback:
zxc-db.el:111:40:Warning: function `getf' from cl package called at runtime
In zxc-db-exec-callback:
zxc-db.el:123:40:Warning: function `getf' from cl package called at runtime
zxc-db.el:125:50:Warning: function `getf' from cl package called at runtime
In end of data:
zxc-db.el:178:1:Warning: the function `zxc-delete-current-word' is not known
    to be defined.
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
zxc-db.el:177: The footer should be: (provide 'zxc-db)\n;;; zxc-db.el ends here
Warning (emacs): 
zxc-db.el:30: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:30: First line should be capitalized
Warning (emacs): 
zxc-db.el:32: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:32: First line should be capitalized
Warning (emacs): 
zxc-db.el:34: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:34: First line should be capitalized
Warning (emacs): 
zxc-db.el:37: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:37: First line should be capitalized
Warning (emacs): 
zxc-db.el:40: First line is not a complete sentence
Warning (emacs): 
zxc-db.el:40: Argument `uri' should appear (as URI) in the doc string
Warning (emacs): 
zxc-db.el:61: First line is not a complete sentence
Warning (emacs): 
zxc-db.el:61: Argument `uri' should appear (as URI) in the doc string
Warning (emacs): 
zxc-db.el:76: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:82: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:97: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:97: First line should be capitalized
Warning (emacs): 
zxc-db.el:110: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:110: First line should be capitalized
Warning (emacs): 
zxc-db.el:122: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:122: First line should be capitalized
Warning (emacs): 
zxc-db.el:133: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:133: First line should be capitalized
Warning (emacs): 
zxc-db.el:142: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:147: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:152: All variables and subroutines might as well have a documentation string
Warning (emacs): 
zxc-db.el:156: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:161: First sentence should end with punctuation
Warning (emacs): 
zxc-db.el:161: First line should be capitalized
Warning (emacs): 
zxc-db.el:166: First sentence should end with punctuation
```

package-lint-current-buffer (using version 20200419.406):
```
19 issues found:
27:0: error: "zxc-db-host" doesn't start with package's prefix "zxc-dev".
30:0: error: "zxc-db-query-param" doesn't start with package's prefix "zxc-dev".
32:0: error: "zxc-db-exec-param" doesn't start with package's prefix "zxc-dev".
34:0: error: "zxc-db-get-create-sql-url" doesn't start with package's prefix "zxc-dev".
36:0: error: "zxc-db-result" doesn't start with package's prefix "zxc-dev".
39:0: error: "zxc-db-send" doesn't start with package's prefix "zxc-dev".
60:0: error: "zxc-db-get" doesn't start with package's prefix "zxc-dev".
75:0: error: "zxc-db-create-column" doesn't start with package's prefix "zxc-dev".
81:0: error: "zxc-db-create-table-buffer" doesn't start with package's prefix "zxc-dev".
96:0: error: "zxc-db-get-table-name" doesn't start with package's prefix "zxc-dev".
109:0: error: "zxc-db-query-callback" doesn't start with package's prefix "zxc-dev".
121:0: error: "zxc-db-exec-callback" doesn't start with package's prefix "zxc-dev".
132:0: error: "zxc-db-get-callback" doesn't start with package's prefix "zxc-dev".
141:0: error: "zxc-db-send-region-query" doesn't start with package's prefix "zxc-dev".
146:0: error: "zxc-db-send-region-exec" doesn't start with package's prefix "zxc-dev".
151:0: error: "zxc-db-get-data" doesn't start with package's prefix "zxc-dev".
155:0: error: "zxc-db-get-table-sql" doesn't start with package's prefix "zxc-dev".
160:0: error: "zxc-db-get-select-sql" doesn't start with package's prefix "zxc-dev".
165:0: error: "zxc-util-get-region-or-paragraph-string" doesn't start with package's prefix "zxc-dev".
```

Suggestions/experimental static checks:
- zxc-db.el#L77: There is no need to quote lambdas (neither #' nor ')
- zxc-db.el#L14: Prefer `https` over `http` (if possible)
- zxc-db.el#L27: Prefer `https` over `http` (if possible)

### zxc-dev.el ###

byte-compile-file (using Emacs 26.3):
```
zxc-dev.el:134:1:Warning: the function `zxc-util-convert-table-to-sql' is not
    known to be defined.
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
zxc-dev.el:82: First sentence should end with punctuation
Warning (emacs): 
zxc-dev.el:82: First line should be capitalized
Warning (emacs): 
zxc-dev.el:85: First sentence should end with punctuation
Warning (emacs): 
zxc-dev.el:85: First line should be capitalized
Warning (emacs): 
zxc-dev.el:102: First sentence should end with punctuation
Warning (emacs): 
zxc-dev.el:102: First line should be capitalized
Warning (emacs): 
zxc-dev.el:102: Argument `dir-path' should appear (as DIR-PATH) in the doc string
Warning (emacs): 
zxc-dev.el:120: First sentence should end with punctuation
Warning (emacs): 
zxc-dev.el:120: First line should be capitalized
```

package-lint-current-buffer (using version 20200419.406):
```
5 issues found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
9:36: warning: Use a non-snapshot version number for dependency on "ctable" if possible.
9:127: warning: Use a non-snapshot version number for dependency on "page-break-lines" if possible.
122:5: error: You should depend on (emacs "26.1") if you need `make-thread'.
```

Suggestions/experimental static checks:
- zxc-dev.el#L97: There is no need to quote lambdas (neither #' nor ')
- zxc-dev.el#L112: There is no need to quote lambdas (neither #' nor ')
- zxc-dev.el#L115: There is no need to quote lambdas (neither #' nor ')
- zxc-dev.el#L122: There is no need to quote lambdas (neither #' nor ')
- zxc-dev.el#L88: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- zxc-dev.el#L89: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- zxc-dev.el#L90: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- zxc-dev.el#L91: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- zxc-dev.el#L92: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- zxc-dev.el#L93: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- zxc-dev.el#L94: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- zxc-dev.el#L22: Prefer `https` over `http` (if possible)
- zxc-dev.el#L124: You can use `not` or `null`

### zxc-ft.el ###

byte-compile-file (using Emacs 26.3):
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
zxc-ft.el:88:1:Warning: defface for `zxc-ft-action-face-foreground' fails to
    specify containing group
In zxc-ft-query-data:
zxc-ft.el:240:9:Warning: function `getf' from cl package called at runtime
In zxc-ft-create-new-tag:
zxc-ft.el:379:37:Warning: assignment to free variable `short-name'
zxc-ft.el:379:48:Warning: assignment to free variable `tag-name'
zxc-ft.el:383:162:Warning: assignment to free variable `tag-pid'
zxc-ft.el:383:142:Warning: reference to free variable `short-name'
zxc-ft.el:383:153:Warning: reference to free variable `tag-name'
zxc-ft.el:383:153:Warning: reference to free variable `tag-pid'
In zxc-ft-dired-list-tags:
zxc-ft.el:402:11:Warning: assignment to free variable `zxc-ft-dired-file-pos'
In zxc-ft-dired-show-tags:
zxc-ft.el:410:47:Warning: reference to free variable `zxc-ft-dired-file-pos'
zxc-ft.el:470:44:Warning: reference to free variable `dired-mode-map'
In end of data:
zxc-ft.el:475:1:Warning: the following functions are not known to be defined:
    http-get-simple, widget-value-set, -elem-index, dired-current-directory,
    dired-get-file-for-visit, dired-sort-toggle-or-edit
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
zxc-ft.el:474: The footer should be: (provide 'zxc-ft)\n;;; zxc-ft.el ends here
Warning (emacs): 
zxc-ft.el:58: Documentation strings should not start or end with whitespace
Warning (emacs): 
zxc-ft.el:58: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:61: Documentation strings should not start or end with whitespace
Warning (emacs): 
zxc-ft.el:61: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:63: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:63: First line should be capitalized
Warning (emacs): 
zxc-ft.el:69: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:69: First line should be capitalized
Warning (emacs): 
zxc-ft.el:71: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:71: First line should be capitalized
Warning (emacs): 
zxc-ft.el:73: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:73: First line should be capitalized
Warning (emacs): 
zxc-ft.el:75: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:80: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:82: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:84: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:84: First line should be capitalized
Warning (emacs): 
zxc-ft.el:86: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:86: First line should be capitalized
Warning (emacs): 
zxc-ft.el:97: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:97: First line should be capitalized
Warning (emacs): 
zxc-ft.el:100: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:100: Argument `url' should appear (as URL) in the doc string
Warning (emacs): 
zxc-ft.el:106: First line is not a complete sentence
Warning (emacs): 
zxc-ft.el:106: First line should be capitalized
Warning (emacs): 
zxc-ft.el:106: Argument `lst' should appear (as LST) in the doc string
Warning (emacs): 
zxc-ft.el:121: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:121: Argument `url' should appear (as URL) in the doc string
Warning (emacs): 
zxc-ft.el:125: First line is not a complete sentence
Warning (emacs): 
zxc-ft.el:125: Argument `mode-map' should appear (as MODE-MAP) in the doc string
Warning (emacs): 
zxc-ft.el:138: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:138: Argument `arg' should appear (as ARG) in the doc string
Warning (emacs): 
zxc-ft.el:156: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:168: All variables and subroutines might as well have a documentation string
Warning (emacs): 
zxc-ft.el:184: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:184: Argument `top-tags' should appear (as TOP-TAGS) in the doc string
Warning (emacs): 
zxc-ft.el:198: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:198: Argument `tags' should appear (as TAGS) in the doc string
Warning (emacs): 
zxc-ft.el:210: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:210: Argument `arg' should appear (as ARG) in the doc string
Warning (emacs): 
zxc-ft.el:225: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:231: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:231: Argument `pid' should appear (as PID) in the doc string
Warning (emacs): 
zxc-ft.el:237: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:237: Argument `param' should appear (as PARAM) in the doc string
Warning (emacs): 
zxc-ft.el:243: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:243: Argument `sql' should appear (as SQL) in the doc string
Warning (emacs): 
zxc-ft.el:248: All variables and subroutines might as well have a documentation string
Warning (emacs): 
zxc-ft.el:251: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:251: Argument `tags' should appear (as TAGS) in the doc string
Warning (emacs): 
zxc-ft.el:256: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:256: Argument `tag' should appear (as TAG) in the doc string
Warning (emacs): 
zxc-ft.el:264: All variables and subroutines might as well have a documentation string
Warning (emacs): 
zxc-ft.el:272: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:291: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:298: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:320: All variables and subroutines might as well have a documentation string
Warning (emacs): 
zxc-ft.el:341: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:341: First line should be capitalized
Warning (emacs): 
zxc-ft.el:398: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:407: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:407: First line should be capitalized
Warning (emacs): 
zxc-ft.el:407: Argument `tag-infos' should appear (as TAG-INFOS) in the doc string
Warning (emacs): 
zxc-ft.el:420: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:420: First line should be capitalized
Warning (emacs): 
zxc-ft.el:434: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:434: First line should be capitalized
Warning (emacs): 
zxc-ft.el:454: All variables and subroutines might as well have a documentation string
Warning (emacs): 
zxc-ft.el:457: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:457: First line should be capitalized
Warning (emacs): 
zxc-ft.el:463: First sentence should end with punctuation
Warning (emacs): 
zxc-ft.el:463: First line should be capitalized
Warning (emacs): 
zxc-ft.el:463: Argument `arg' should appear (as ARG) in the doc string
```

package-lint-current-buffer (using version 20200419.406):
```
47 issues found:
54:0: error: "zxc-ft-buffer" doesn't start with package's prefix "zxc-dev".
57:0: error: "zxc-ft-query-url" doesn't start with package's prefix "zxc-dev".
60:0: error: "zxc-ft-exec-url" doesn't start with package's prefix "zxc-dev".
63:0: error: "zxc-ft-tag-widget" doesn't start with package's prefix "zxc-dev".
65:0: error: "zxc-ft-action-keys" doesn't start with package's prefix "zxc-dev".
71:0: error: "zxc-ft-tags-all" doesn't start with package's prefix "zxc-dev".
73:0: error: "zxc-ft-tags-search" doesn't start with package's prefix "zxc-dev".
75:0: error: "zxc-ft-begin-ol" doesn't start with package's prefix "zxc-dev".
77:0: error: "zxc-ft-sub-tags-keys" doesn't start with package's prefix "zxc-dev".
82:0: error: "zxc-ft-is-sub-view" doesn't start with package's prefix "zxc-dev".
84:0: error: "zxc-ft-sub-tags-tmp" doesn't start with package's prefix "zxc-dev".
86:0: error: "zxc-ft-current-action" doesn't start with package's prefix "zxc-dev".
95:0: error: "zxc-ft-init-p" doesn't start with package's prefix "zxc-dev".
97:0: error: "zxc-http-data" doesn't start with package's prefix "zxc-dev".
99:0: error: "zxc-http-method" doesn't start with package's prefix "zxc-dev".
105:0: error: "zxc-http-json-2-lisp" doesn't start with package's prefix "zxc-dev".
120:0: error: "zxc-http-post" doesn't start with package's prefix "zxc-dev".
124:0: error: "zxc-mode-action-str" doesn't start with package's prefix "zxc-dev".
137:0: error: "zxc-ft" doesn't start with package's prefix "zxc-dev".
147:0: error: "zxc-ft-mode" doesn't start with package's prefix "zxc-dev".
155:0: error: "zxc-ft-init" doesn't start with package's prefix "zxc-dev".
167:0: error: "zxc-ft-main-view" doesn't start with package's prefix "zxc-dev".
183:0: error: "zxc-ft-view-create-all-tags" doesn't start with package's prefix "zxc-dev".
197:0: error: "zxc-ft-view-create-sub-tags" doesn't start with package's prefix "zxc-dev".
209:0: error: "zxc-ft-reset-main-view" doesn't start with package's prefix "zxc-dev".
224:0: error: "zxc-ft-get-top-tags" doesn't start with package's prefix "zxc-dev".
230:0: error: "zxc-ft-get-child-tags" doesn't start with package's prefix "zxc-dev".
236:0: error: "zxc-ft-query-data" doesn't start with package's prefix "zxc-dev".
242:0: error: "zxc-ft-exec-data" doesn't start with package's prefix "zxc-dev".
247:0: error: "zxc-get-action-key" doesn't start with package's prefix "zxc-dev".
250:0: error: "zxc-ft-add-tags" doesn't start with package's prefix "zxc-dev".
255:0: error: "zxc-ft-build-query" doesn't start with package's prefix "zxc-dev".
263:0: error: "zxc-ft-widget-update" doesn't start with package's prefix "zxc-dev".
271:0: error: "zxc-ft-tag-choose" doesn't start with package's prefix "zxc-dev".
290:0: error: "zxc-ft-tag-action" doesn't start with package's prefix "zxc-dev".
297:0: error: "zxc-ft-tag-query" doesn't start with package's prefix "zxc-dev".
319:0: error: "zxc-ft-result-2-entries" doesn't start with package's prefix "zxc-dev".
327:0: error: "zxc-ft-result-mode" doesn't start with package's prefix "zxc-dev".
340:0: error: "zxc-ft-result-view-open" doesn't start with package's prefix "zxc-dev".
346:0: error: "zxc-ft-create-new-tag" doesn't start with package's prefix "zxc-dev".
397:0: error: "zxc-ft-dired-list-tags" doesn't start with package's prefix "zxc-dev".
406:0: error: "zxc-ft-dired-show-tags" doesn't start with package's prefix "zxc-dev".
419:0: error: "zxc-ft-dired-mark-tags" doesn't start with package's prefix "zxc-dev".
433:0: error: "zxc-ft-dired-make-tags" doesn't start with package's prefix "zxc-dev".
453:0: error: "zxc-ft-query-file-info" doesn't start with package's prefix "zxc-dev".
456:0: error: "zxc-ft-dired-revert-buffer" doesn't start with package's prefix "zxc-dev".
462:0: error: "zxc-ft-dired-sort-buffer" doesn't start with package's prefix "zxc-dev".
```

Suggestions/experimental static checks:
- zxc-ft.el#L150: There is no need to quote lambdas (neither #' nor ')
- zxc-ft.el#L266: There is no need to quote lambdas (neither #' nor ')
- zxc-ft.el#L307: There is no need to quote lambdas (neither #' nor ')
- zxc-ft.el#L320: There is no need to quote lambdas (neither #' nor ')
- zxc-ft.el#L446: There is no need to quote lambdas (neither #' nor ')
- zxc-ft.el#L468: There is no need to quote lambdas (neither #' nor ')
- zxc-ft.el#L367: It's safer to sharp-quote function names; use `#'`
- zxc-ft.el#L147: It is unusual to derive from fundamental-mode; try special-mode
- zxc-ft.el#L423: Consider `unless ...` instead of `when (not ...)`
- zxc-ft.el#L19: Prefer `https` over `http` (if possible)
- zxc-ft.el#L57: Prefer `https` over `http` (if possible)
- zxc-ft.el#L60: Prefer `https` over `http` (if possible)

### Loadability ###

Running #'load on each file:
```
Loading zxc-db-ac.el
Loading zxc-db.el
Loading zxc-dev.el
Loading zxc-ft.el
Done.
```

### Packaging ###

- Prefer the default recipe if possible
- Package-Requires: deferred "0.5.1", http-post-simple "1.0", auto-complete "1.5.1", switch-window "1.6.1", page-break-lines "20181221.2308", emacs "26", ctable "20171006.11"
- Use a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- Please add a LICENSE or COPYING file to the repository
- pkg/zxc-db-ac.el (GPL) -- HTTP client using the url library
- pkg/zxc-db.el (GPL) -- database client
- pkg/zxc-dev.el (GPL) -- file tag system and sql client
- pkg/zxc-ft.el (GPL) -- quick access to files by tags
- pkg/backend -- directory

**Comment by zxcwindy** [comment]
Thanks a lot for the review!

I've solved most of the issues. It has passed the checkdoc, byte-compile-file and package-lint-current-buffer tests.

Remaining issues:
1.(Prefer https over http) It's not necessary
2.(Use a non-snapshot version number for dependency on "page-break-lines" if possible.) page-break-lines don't have a non-snapshot version number.
3.(Suggestions/experimental static checks) I don't know which quality-checking you use, I've solved most of this issues.

**Comment by riscy** [comment]
That's much tidier -- here are a few more:

byte-compile-file (using Emacs 26.3):
```
zxc-dev-db.el:42:1:Warning: Unused lexical argument `response'
zxc-dev-db.el:64:1:Warning: Unused lexical argument `response'
zxc-dev-ft.el:109:1:Warning: Unused lexical variable `err'
zxc-dev-ft.el:109:1:Warning: Unused lexical variable `head'
zxc-dev-ft.el:383:1:Warning: Unused lexical argument `ignore'
zxc-dev-ft.el:383:1:Warning: Unused lexical argument `ignore'
zxc-dev-ft.el:383:1:Warning: Unused lexical argument `ignore'
zxc-dev-ft.el:383:1:Warning: Unused lexical argument `ignore'
```
In these cases, I think you can just use variable names `_response` to indicate to the compiler that they're deliberately unused.

You also have `Package-Requires` defined in all of your elisp files, and they all differ.  As long as `zxc-dev.el` lists the superset you're fine, since MELPA will ignore the non-main files, but it's something to be aware of.  A safe option is to remove the Package-Requires from the non-main files.

>  2.(Use a non-snapshot version number for dependency on "page-break-lines" if possible.) page-break-lines don't have a non-snapshot version number.

It seems to have [0.11](https://stable.melpa.org/#/page-break-lines) on MELPA, but maybe that's a recent development.

>  3.(Suggestions/experimental static checks) I don't know which quality-checking you use, I've solved most of this issues.

Since you're on GitHub, it's very easy to [get the checks -- byte-compile, checkdoc, etc -- to run automatically as a "melpazoid" github action on your master branch](https://github.com/riscy/melpazoid/#add-it-to-github-actions).  melpazoid is a bunch of scripts I wrote to help with reviews, and it also spits out those experimental checks.

**Comment by zxcwindy** [comment]
Hi,I think I solved the rest of the issues :)

**Comment by riscy** [comment]
Great -- now that we have the checklist out of the way I'm taking another look.

First I'd point out [filetags.el](https://github.com/DerBeutlin/filetags.el/tree/01e6a919507a832ee001a2a0fc257657f8b04b72) which I can tell has a significantly different implementation, but is something you should be aware of (and probably compare to, and/or link to in your README).

The second is that jdbc feels like a heavy requirement, or at least writing a custom client and packaging it with your file tagger seems too heavy.  Have you considered using a lighter-weight elisp solution as your backend?  [Here](https://github.com/skeeto/emacsql/blob/a118b6c95af1306f0288a383d274b5dd93efbbda/emacsql.el#L12) may be a good solution, but there are other examples [here](https://melpa.org/#/?q=sqlite), [here](https://melpa.org/#/?q=postgres), [here](https://melpa.org/#/?q=mysql).

I would also recommend decoupling your file tag system and the SQL client you've written and seeing if they make sense as two separate MELPA packages.  The file tag system could be a separate package from, and a lightweight add-on to, your JDBC connector.

Lastly, the package name "zxcv-dev" seems to be a combination of your username and "dev", which (to me) doesn't map to "File tag system and sql client".

**Comment by zxcwindy** [comment]
Ok,I think the better way is to split it into two independent packages. I have closed this pull request,and may restart it later when the refactoring is completed

**Pull request closed without merging**
