### PR TITLE
Add recipe for decide-mode

### PR DESCRIPTION
**Pull request by CestDiego**
Random decisions for emacs, with functions and a minor mode. Roll
various types of dice etc.

I'm not the author of this package, Got consent in
https://github.com/lifelike/decide-mode/issues/1

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Sent @lifelike a small fix in https://github.com/lifelike/decide-mode/pull/3

**Comment by purcell** [comment]
@CestDiego I didn't notice immediately, but this package should be called `decide`, not `decide-mode`, so that it matches the contained filename. Can you amend and force-push the recipe commit please?

**Comment by CestDiego** [comment]
done :)

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
