### PR TITLE
Update the recipe for org-starter

### PR DESCRIPTION
**Pull request by akirak**
This is an update to an existing package (#6262). Thank you for the explanation.

### CODE REVIEW

**Comment by conao3** [comment]
FYI: Please see README at [recipe section](https://github.com/melpa/melpa#recipe-format).
and its source
https://github.com/melpa/melpa/blob/51f8acd2929d5e796c6e9d80bf1fbe5ebebbae59/package-build/package-build.el#L577-L582

Maybe your updated recipe has redundant specifications.

**Comment by akirak** [comment]
I included `org-starter.el` and `org-starter-*.el` explicitly because I plan on adding some helper libraries (`org-starter-utils.el` and `org-starter-menu.el`) which should be part of the main `org-starter` package.

`org-starter-swiper.el` and `org-starter-extras.el` are not part of the main package due to their extra dependencies, so I had to exclude them.

**Comment by conao3** [comment]
I point `"doc/dir" "doc/*.info" "doc/*.texi" "doc/*.texinfo"` is meeningless for recipe if you include `:defaults`.
But this is just information. Your recipe is yours. Ignore me. sorry.

**Comment by akirak** [comment]
Yes, you are right. Because I didn't include `*.el`, I didn't have to keep `".dir-locals.el" "test.el" "tests.el"` in the `:exclude` section.

For now, there is no `doc` directory in the package, but I prefer sticking with the default unless I have a reason. Actually, it doesn't matter, because I have never included info files in any of my elisp packages.

> Your recipe is yours. 

I don't think so. MELPA is for everyone, so I will follow an opinion wherever it makes sense.

**Comment by conao3** [comment]
I thought I was too interference you, so I sent that message.
If I were to create a recipe, I would do this.
```
(org-starter
 :repo "akirak/org-starter"
 :fetcher github
 :files (:defaults
         (:exclude "org-starter-swiper.el" "org-starter-extras.el")))
```
https://github.com/akirak/melpa/pull/1
If you accept it, merge it your branch then my modified recipe will reflect into this PR.

**Comment by purcell** [comment]
Indeed, the preferred fix here would be to simply exclude `org-starter-swiper.el` too, ie.
```el
:files (:defaults
        (:exclude "counsel-org-starter.el" "helm-org-starter.el" "org-starter-swiper.el")))
```
But an even better solution overall would probably be to put those separately-packaged files in either separate directories or repos.

**Comment by akirak** [comment]
I've fixed the recipe, so it's much more concise now. Thanks.

**Comment by conao3** [comment]
Well, why you manually modify with seeing my advice and ignore my PR sent @akirak ?
I mistake recipe first place in the PR but I fix recipe your point and I reach the same goal before you.
This change is certainly small and may not be the type of logic. However, I will warn you that you have distorted the git history with you stole my achievements and belong to you by ignoring the desirable rational solution I have provided.

**Comment by akirak** [comment]
@conao3 I simply didn't notice your latest commit on the PR. I'm sorry for that, but I didn't steal that recipe from you.

**Comment by conao3** [comment]
Then,  you could revert bf47132 and merge my PR. If you like the current recipe format, you could fix format after merge my PR.

**Comment by conao3** [comment]
If without my PR, you should commit bf47132 with below `Co-authored` attribute for @purcell .
https://help.github.com/en/articles/creating-a-commit-with-multiple-authors

That is respect for the person who gave advice and wrote the code.

**Comment by akirak** [comment]
Thanks, I've added a credit.

I still don't think I have to make a co-author commit here, because I borrowed his idea but the recipe file was written by me. You look like a paranoia. Please don't waste time of others.

**Comment by conao3** [comment]
That is not credit you just mention in commit message.
As proof, GitHub doesn't recognize that the commit was made by more than one person.

And I just advised on general respect for OSS activities. Denying someone else's personality and becoming aggressive is not necessary for developer communication and violates the general code of conduct.
You could have ignored my technical advice if it didn't make sense (but it seems that you modified recipe it as I said), but you should be aware of this  note about code of conduct.

**Comment by akirak** [comment]
I think this is a credit. Thanks + his name shows that the change is at least partly due to him.

Am I aggressive? You started the discussion first, and I don't understand why you insist on this topic so much. My first solution was functional (though verbose), and your idea was about aesthetics. I don't think it makes sense to spend so much time on the topic. Everyone here has other projects to work on.

If you really want a credit to you, you can create another branch which contains the recipe update and send a PR directly to this repository, not to my fork. Then Purcell can merge your PR and close this one. MELPA is maintained by Purcell, so his decision takes precedence over general OSS practices here. I don't think it is sane, though.

**Comment by conao3** [comment]
I gave you some advice for you just information. What I point out is the **code** and the **git operations** involved without respect others. Things that suddenly started your attacking **my personality** violate the general code of conduct, so I think it is necessary to apologize to me.

I usually don't point out such a commitment's attribution, but doing halfway with ignoring to my provide methods and schemes that give correct attribution is worse than not touching it at all. Anyway, all my suggestions did not help?

**Comment by akirak** [comment]
Sorry, I didn't get what you meant well (I knew it was redundant but wasn't sure which part you were talking about), and I had to find out my solution (your advice didn't work perfectly). Your initial PR was actually wrong, so I lost respect in your work and didn't care about your further comments there. I'm sorry for that. Now I've got what you intended in this thread.

As I explained in this thread, there could be a possibility of adding another companion package other than `counsel-org-starter` and `helm-org-starter`, so I specified `org-starter-*.el` explicitly, but it probably won't happen soon, so `:default` will be sufficient. 

You really seem to be a good programmer, but somehow I didn't 100% get what you meant here. I didn't totally neglect you though. I responded to you as far as I understand what's written. I don't know anything about your personality but felt uneasy with your behaviour here. I didn't know even a package recipe should be attributed a copyright. That will be a good lesson for me. Thank you.

**Comment by akirak** [comment]
I thought @conao3 would deserve a credit, so I've added his name to the commit message. 

@purcell 
Sorry for bothering you. I am fine with this recipe. If he approves the state, I think it is mergeable.

**Comment by riscy** [comment]
Thanks @canao3 and @akirak for this -- it looks like the discussion has arrived at a technically correct solution, so I can go ahead and merge.

**Comment by akirak** [comment]
@riscy Thanks.

**Pull request merged**
