### PR TITLE
Add jeison recipe

### PR DESCRIPTION
**Pull request by SavchenkoValeriy**
### Brief summary of what the package does

Jeison is a library for a declarative JSON parsing. It maps EIEIO classes' slots onto specific JSON values and constructs these objects from the given JSON objects.

### Direct link to the package repository

https://github.com/SavchenkoValeriy/jeison

### Your association with the package

I am the author and the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ ] My elisp byte-compiles cleanly (there are warnings that don't seem relevant to me)
- [ ] `M-x checkdoc` is happy with my docstrings (there are warnings that don't seem relevant to me)
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

**NOTE 1** `checkdoc` doesn't like mentions of `jeison--slot` in docstrings.
**NOTE 2** Byte compilation produces 4 warnings: "‘name’ is an obsolete variable (as of 25.1); use 'name instead", it doesn't seem relevant to me (or I simply don't understand what it means).

### CODE REVIEW

**Comment by riscy** [comment]
Move this declaration:
```elisp
(defclass jeison--slot nil
...
```
to the top of your file -- before it's referenced -- and that should solve most of your issues.  Ping to let us know if that works out for you.

**Comment by SavchenkoValeriy** [comment]
@riscy done ([71aa36](https://github.com/SavchenkoValeriy/jeison/commit/71aa36af86a1566a5846cae39a47bfb1c160dd27)), but the problems with `checkdoc` and `byte-compile` maintain.

**Comment by purcell** [comment]
Looks good to me in Emacs 26 - merging.

Consider `pcase-let` instead of `-let` from `dash`, though, since `pcase` is built-in. There's not much need for `dash` in Emacs 26 tbh, given built-in `seq`, `cl-lib`, `pcase` etc.

**Comment by SavchenkoValeriy** [comment]
@purcell You are right and I was trying to avoid `dash` for the most part of `jeison`s history, but I needed to use `-separate` and I didn't see a good CL replacement for it.

**Pull request merged**
