### PR TITLE
Add recipe for elsa-lambda-calculus-mode

### PR DESCRIPTION
**Pull request by Kab1r**
### Brief summary of what the package does

Provides basic syntax highlighting for the [Elsa](https://github.com/ucsd-progsys/elsa), the lambda calculus language and evalutator.

### Direct link to the package repository

https://github.com/Kab1r/elsa-lambda-calculus-mode

### Your association with the package

I am the author and maintain the package

### Relevant communications with the upstream package maintainer

None Needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Quick first pass --

- Based on the [docs](https://github.com/ucsd-progsys/elsa) it looks like the language also expects indentation, and you'd therefore usually want to define a function to point `indent-line-function` to.  Have you gotten a chance to look at that?  If you have, I realize indentation can be tricky to implement, and sometimes it can be okay to merge a "first-cut" major mode for a new language
- You have two lines `(provide 'elsa-lambda-calculus-mode)` and conventionally these would go after the `auto-mode-alist` definition
- The strings "\=" and "-\>" are equivalent to "=" and "->" respectively (same with "=[abd*~]\>")
- Syntactically the `;; End` at the end of the file should be `;; End:` (see [manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html))
- The constants `(defconst elsa-lambda-calculus-keywords  '("let" "eval" ":" "\\"))` and `(defconst elsa-lambda-calculus-operators '("\=" "-\>"))` look like they're only used as inputs to define other constants (which are then used to define another constant) -- it may be best to inline the code and not add extraneous variables into the namespace, or to privatize those constants with double-dashes, e.g. `elsa-lambda-calculus--keywords`

**Comment by Kab1r** [comment]
Thank you for your feedback, I have updated the project with the changes.

> Based on the [docs](https://github.com/ucsd-progsys/elsa) it looks like the language also expects indentation, and you'd therefore usually want to define a function to point `indent-line-function` to. Have you gotten a chance to look at that? If you have, I realize indentation can be tricky to implement, and sometimes it can be okay to merge a "first-cut" major mode for a new language

- Indentation and line breaks in Elsa are optional, so I don't think this is required.

> You have two lines `(provide 'elsa-lambda-calculus-mode)` and conventionally these would go after the `auto-mode-alist` definition

- Changes applied.

> The strings "=" and "->" are equivalent to "=" and "->" respectively (same with "=[abd*~]>")

- My understanding is that Elsa does not have the concept of a string.
  Expressions are the only type.
  It's worth noting that these operators are highlighted differently when in comments.

> Syntactically the `;; End` at the end of the file should be `;; End:` (see [manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html))

- Changes applied.

> The constants `(defconst elsa-lambda-calculus-keywords '("let" "eval" ":" "\\"))` and `(defconst elsa-lambda-calculus-operators '("\=" "-\>"))` look like they're only used as inputs to define other constants (which are then used to define another constant) -- it may be best to inline the code and not add extraneous variables into the namespace, or to privatize those constants with double-dashes, e.g. `elsa-lambda-calculus--keywords`

- Changes applied by in-lining.

**Comment by riscy** [comment]
Thanks for accommodating with those --

> Changes applied by in-lining

Much easier for me to parse -- thank you!

> The strings "=" and "->" are equivalent to "=" and "->" respectively (same with "=[abd*~]>")

Sorry about this, it looks like the form swallowed my backslashes.  Your strings (e.g. `"\="`) have unnecessary backslashes in them.  In fact the Emacs lisp font locks should be highlighting those backslashes in the warning color.  Not a blocker, but the backslashes are purely unnecessary.

> Indentation and line breaks in Elsa are optional, so I don't think this is required.

I understand what you're saying, but if you intend to fully support the language I would try to put this on your radar, or solicit the community for help.  (C is another example of a language with optional line breaks, but the value of indentation is obvious.)

As I take a closer look I believe you can take better advantage of `set-syntax-table`; for example with respect to comments, you don't want to syntax color them using `elsa-lambda-calculus-comments-regexp` (and so you should remove that variable); instead you should use:

```elisp
(setq elsa-lambda-calculus-mode-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?- ". 12" table) ; double-dash comments
    (modify-syntax-entry ?\n ">" table)   ; comment ender
    table))
```
and define your major mode with:
```elisp
;;;###autoload
(define-derived-mode elsa-lambda-calculus-mode
  prog-mode
  "Elsa"
  "Major Mode for the tiny lambda calculus evaluator."
  (set-syntax-table elsa-lambda-calculus-mode-syntax-table)
  (setq-local comment-start "-- ")
  (setq-local comment-end "")
  (setq font-lock-defaults '((elsa-lambda-calculus-font-lock-keywords))))
```
and this will enable Emacs to know what is a comment and what is code, which will enable facilities like using M-; (`comment-dwim`) for comments.

I think taking this package just a little bit further -- for example by incorporating the suggestions above re: comments -- would be worth doing before merging this.

**Comment by riscy** [comment]
I'll mark this awaiting upstream in the meantime; feel free to ping.

**Pull request closed without merging**
