### PR TITLE
Modify sage-shell-mode recipe

### PR DESCRIPTION
**Pull request by stakemori**
I set the :files keyword of [sage-shell-mode](https://github.com/stakemori/sage-shell-mode) too strict. Unexpectedly, my package is growing. So I would like to change the :files keyword.

### CODE REVIEW

**Comment by syohex** [comment]
- Could you check whether `:defaults` is available ?
- I suppose documents should be put either top level directory or `doc/`

**Comment by stakemori** [comment]
Thanks for the remark. I use `:default`. I don't understand the second remark. Sorry. The only document in the repo is `README.org` and I copied the default value of :files keyword in the previous commit.

**Comment by stakemori** [comment]
Sorry, I pushed further fix.

**Comment by stakemori** [comment]
I just transferred the repository. So I also changed the `:repo` keyword.

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
