### PR TITLE
Add recipe for selected-window-contrast

### PR DESCRIPTION
**Pull request by Anoncheg1**
### Brief summary of what the package does

Allow to set color of background and text by comparing their brightness. This is useful for changing themes during the daytime and for highlighting selected window. Also working for modeline.
Just loop windows at frame and change brightness.

### Direct link to the package repository

https://github.com/Anoncheg1/selected-window-contrast

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

⸺ `selected-window-contrast.el` with byte-compile using Emacs 29.4:
```
selected-window-contrast.el:149:4: Warning: the function `color-rgb-to-hex' is not known to be defined.
selected-window-contrast.el:137:18: Warning: the function `color-hsl-to-rgb' is not known to be defined.
selected-window-contrast.el:111:6: Warning: the function `color-rgb-to-hsl' is not known to be defined.
```
These need a `(require 'color)` at the top.

⸺ `selected-window-contrast.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- `;;; Commentary` is much wider than 80 characters
- selected-window-contrast.el#L193: It's safer to sharp-quote function names; use `#'`
- selected-window-contrast.el#L194: It's safer to sharp-quote function names; use `#'`
```
I include the note on your Commentary because it might be possible to tighten it back to something closer to the standard 80, even though there are code snippets in there.

**Comment by Anoncheg1** [comment]
I checked package with Melpazoid. 
Everything is fixed.

**Comment by riscy** [comment]
Thanks for the update!  It seems something might have gone wrong when you ran melpazoid and saw that everything appeared fixed - you'd be doing me a favor if you can let me know what went wrong. Here's the latest -

⸺ `selected-window-contrast.el` with package-lint 20241127.1826:
```
2 issues found:
1:0: warning: The package summary is too long. It should be at most 60 characters.
231:26: warning: Closing parens should not be wrapped onto new lines.
```

⸺ `selected-window-contrast.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- `;;; Commentary` is much wider than 80 characters
- selected-window-contrast.el#L194: It's safer to sharp-quote function names; use `#'`
- selected-window-contrast.el#L195: It's safer to sharp-quote function names; use `#'`
- selected-window-contrast.el#L206: It's safer to sharp-quote function names; use `#'`
- selected-window-contrast.el#L213: It's safer to sharp-quote function names; use `#'`
```

**Comment by Anoncheg1** [comment]
I was wrong. I checked log and fixed every warning.

**Comment by riscy** [comment]
Maybe it was the fact that melpazoid doesn't actually throw a CI error unless there is an actual non-error (melpazoid's CI story is pretty weak, admittedly, and hasn't been a big focus).  I do appreciate you using it though!

I will point out a few packages in the same space, mostly fyi -

- https://melpa.org/#/hiwin
- https://melpa.org/#/solaire-mode
- https://melpa.org/#/auto-dim-other-buffers

Merging now, and thanks again!

**Pull request merged**
