### PR TITLE
Add recipe for helm-project

### PR DESCRIPTION
**Pull request by cmccloud**
### Brief summary of what the package does

This package provides a Helm interface for the built in project.el Emacs library. 

### Direct link to the package repository

https://github.com/cmccloud/helm-project

### Your association with the package

Author and maintainer

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`helm-project.el` with package-lint 20230525.1346:
```
1 issue found:
55:70: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
```

`helm-project.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- helm-project.el#L67: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
```

Package and license:
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

Package name:
- `helm-project` already exists: https://github.com/emacsmirror/helm-project (via emacsmirror)

**Comment by cmccloud** [comment]
Thanks for the feedback and I apologize for the issues, I definitely should have caught these, thanks for bearing with me.

> 1 issue found:
> 55:70: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)

Regarding the above issue - I'm adhering to the same keybinding conventions as the base helm package, which also binds `C-C a` when inside `helm-mini` to toggle between a filtered/unfiltered list of buffers, which is conceptually similar to what my own binding does in the context of my package where it toggles between a list of files/buffers in the current project or the list of files/buffers in both the current project and in any `project-external-roots`.

If this is a must fix, let me know and I'll change the binding.

> - helm-project.el#L67: Mixed tab/space indentation, consider `(setq indent-tabs-mode nil)`
Fixed the above issue.

> Package and license:
> 
>     Add a LICENSE file to the repository
>     See: https://github.com/licensee/licensee
Fixed the above issue.

> Package name:
> 
>     helm-project already exists: https://github.com/emacsmirror/helm-project (via emacsmirror)
I searched within MELPA and didn't see the name taken, which is why I believed it to be free.
I'll decide on an appropriate change and update soon.

Thanks again.

**Comment by riscy** [comment]
> I'm adhering to the same keybinding conventions as the base helm package

Confirmed this (helm-buffers.el), and I was dimly aware of this but it's been a while since I've been reminded.  I think given the close integration with helm, this is okay.

> I'll decide on an appropriate change and update soon.

The Emacsmirror has *everything* (ELPA projects, old wiki projects); it's unfortunate when there's a name conflict with one of those old packages.  Ultimately the easiest thing to do is to choose a new name, but arguments have been made in the past to rename the Emacsmirror package; we'd have to reach out for @tarsius to help with this.

**Comment by tarsius** [comment]
The author/maintainer of the previous incarnation, here @shishi, should be given a chance to comment.

In this case it seems appropriate to just reuse the name for the new implementation. From the readme:

> Fork project of anything-project.
> Just replace anything => helm.

Also it hasn't been touched in a decade, doesn't use the appropriate symbol prefix, and most likely is incompatible with contemporary `helm`.

**Comment by shishi** [comment]
Wow I found my legacy. I can do rename repository or something for you, what can I do?

**Comment by tarsius** [comment]
@shishi If your project does not work anymore with the `helm` of today, then you should add a note about that to your `README.md`.

Even if it does still work, you should have a look at the new implementation. If you think that users would be better of migrating from your implementation to this new implementation, then you should also mention that in your `README.md`. (Even if you continue to use your own implementation, you might still want to link to the new implementation.)

At this point, I don't think that there is any need to rename your package and/or repository.

**Comment by shishi** [comment]
@tarsius Thank you. I will edit my README.

**Comment by cmccloud** [comment]
Catching up this morning on this conversation; should I rename my package or leave it as is?

Thanks to everyone for their comments and input.

**Comment by tarsius** [comment]
> Catching up this morning on this conversation; should I rename my package or leave it as is?

Leave it as is.

**Comment by riscy** [comment]
Thanks everyone!  I'm going to go ahead and merge.

**Pull request merged**
