### PR TITLE
rename recipe emacs-eclim to eclim for use-package

### PR DESCRIPTION
**Pull request by stardiviner**
https://github.com/senny/emacs-eclim/issues/277

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. There is no repository https://github.com/emacs-eclim/emacs-eclim - should this be "senny/emacs-eclim"?

Apart from this, the file spec is wrong, because `*.el` will include the files "company-emacs-eclim.el" and "ac-emacs-eclim-source.el", for which additional package dependencies would be necessary. Those should be distributed as separate packages which depend on `company` and `auto-complete` respectively.

/cc @senny

**Comment by stardiviner** [comment]
@purcell I updated my recipe repo address.
I think eclim require on additional packages need to modify in eclim repo file.

**Comment by tarsius** [comment]
> I think eclim require on additional packages need to modify in eclim repo file.

Could you please rephrase that. What's needed?

**Comment by purcell** [comment]
Upstream PR submitted: https://github.com/senny/emacs-eclim/pull/281

We'd then need to adjust the eclim recipe to include only "eclim*.el", and then also add recipes for "ac-emacs-eclim" and "company-emacs-eclim".

**Comment by stardiviner** [comment]
@purcell Ok, I will modify the recipe. and create other two recipe.

**Comment by stardiviner** [comment]
I created two recipes for ac-eclim and company-eclim:
https://github.com/melpa/melpa/pull/4133

**Comment by purcell** [comment]
Great, I'll close this in favour of #4133.

**Comment by dgutov** [comment]
Does anyone know what happened to emacs-eclim/emacs-eclim? Development moved there at some point, and there was some new activity there. Which didn't get merged back.

**Comment by purcell** [comment]
Not sure, sorry.

**Comment by dgutov** [comment]
@kleewho @nloyola @jchochli @gopar Could any of you guys comment?

**Comment by stardiviner** [comment]
@dgutov I have not found emacs-eclim/emacs-eclim on github and google, but found  https://github.com/emacs-eclim, but it does not have any repository.

**Comment by gopar** [comment]
Okay something is horribly wrong. The repo is no longer there. Looks like it some how got deleted. Do you know of anyway of checking what happened and if there is a way to revert back repository?

**Comment by dgutov** [comment]
Someone with access rights deleted it, apparently. You should be able to restore it by creating a new one with the same name and pushing from a local checkout.

**Comment by gopar** [comment]
Fudge! I accidentally deleted the repo thinking it was a fork I made previously

**Comment by gopar** [comment]
@nloyola do you have a local copy of emacs-eclim? I removed emacs-eclim since I don't do much Java anymore. I'll look if I have a local copy of it somewhere on my computer.

**Comment by nloyola** [comment]
I have a copy on my computer back home, but I am on holidays out of the country right now.  I'm travelling back home fist week of September. 

I can ask someone to go and turn on my home computer then I can access it. But, due to time zones, that wont be for around 6 hours.

**Comment by nloyola** [comment]
I checked my GitHub fork and it was up to date with the latest, so I pushed it onto this repo. Hopefully, we did not lose any commits.

**Comment by nloyola** [comment]
The old repository [senny/emacs-eclim](https://github.com/senny/emacs-eclim) has 761 commits, with the last one made on Dec 31, 2015. The new repository [emacs-eclim/emacs-eclim](https://github.com/emacs-eclim/emacs-eclim) has 809 commits, with the last one made on June 17, 2016.

Please use emacs [emacs-eclim/emacs-eclim](https://github.com/emacs-eclim/emacs-eclim).

**Comment by purcell** [comment]
Pending https://github.com/emacs-eclim/emacs-eclim/pull/1.

**Comment by stardiviner** [comment]
I updated `ac-eclim` and `company-eclim` recipes at here: https://github.com/melpa/melpa/pull/4137

**Comment by purcell** [comment]
I'll fix up the recipes once https://github.com/emacs-eclim/emacs-eclim/pull/1 is merged upstream.

**Comment by purcell** [comment]
The corresponding recipe changes have been made: they'll take effect when the package next rebuilds.

**Pull request closed without merging**
