### PR TITLE
Add org-roam-bibtex recipe

### PR DESCRIPTION
**Pull request by zaeph**
### Brief summary of what the package does

Connector between `org-roam` and `helm-bibtex`.

The package allows the creation of `org-roam` notes directly from `helm-bibtex` or `ivy-bibtex`.  It also implements a new mode of template expansion based on `bibtex-completion`.

### Direct link to the package repository

https://github.com/Zaeph/org-roam-bibtex

### Your association with the package

I'm the co-maintainer of this project with @myshevchuk.  I'm a contributor of [`org-roam`](https://github.com/jethrokuan/org-roam) (by @jethrokuan) and a soon-to-be contributor of [`helm-bibtex`](https://github.com/tmalsburg/helm-bibtex) (by @tmalsburg).

### Relevant communications with the upstream package maintainer

See #6833 for rationale behind making this package.  We opted for option 3, which means that I've created a separate package from `org-roam`.
This package combines the efforts in jethrokuan/org-roam#437 and jethrokuan/org-roam#415.

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them (**Sneaky…** 🐍)

### CODE REVIEW

**Comment by Zaeph** [comment]
Oh, sorry for the mistake in the recipe.  I should have paid more attention.

**Comment by riscy** [comment]
Quick run over the checklist --

### org-roam-bibtex.el ###

byte-compile-file (using Emacs 26.3):
```
org-roam-bibtex.el:287:57:Warning: reference to free variable `f'
org-roam-bibtex.el:332:1:Warning: Unused lexical variable `title'
In org-roam-bibtex-mode:
org-roam-bibtex.el:372:16:Warning: assignment to free variable
    `org-ref-notes-function'
In end of data:
org-roam-bibtex.el:488:1:Warning: the following functions are not known to be
    defined: pushnew, org-roam-find, org-roam--get-non-ref-path-completions
```
I'll note at least for `pushnew` you should prefer `cl-pushnew` and `(require 'cl-lib)` instead.  Let me know if any of these are hard to stamp out. :)

checkdoc (using version 0.6.1):
```
Warning (emacs): 
org-roam-bibtex.el:126: Lisp symbol `org-roam-capture-templates' should appear in quotes
Warning (emacs): 
org-roam-bibtex.el:213: Lisp symbol `org-roam' should appear in quotes
Warning (emacs): 
org-roam-bibtex.el:226: Lisp symbol `org-roam' should appear in quotes
Warning (emacs): 
org-roam-bibtex.el:378: Lisp symbol `org-roam' should appear in quotes
Warning (emacs): 
org-roam-bibtex.el:472: Argument `initial-prompt' should appear (as INITIAL-PROMPT) in the doc string
Warning (emacs): 
org-roam-bibtex.el:480: Some lines are over 80 columns wide
Warning (emacs): 
org-roam-bibtex.el:480: Argument `prefix' should appear (as PREFIX) in the doc string
```

package-lint-current-buffer (using version 20200415.606):
```
2 issues found:
471:0: error: "org-roam-find-non-ref-file" doesn't start with package's prefix "org-roam-bibtex".
479:0: error: "org-roam-insert-non-ref" doesn't start with package's prefix "org-roam-bibtex".
```

Hope this helps!

**Comment by Zaeph** [comment]
> Hope this helps!

It does, and thank you for taking the time to do that!

We've kept expanding the package, and since neither of us is really used to that, we forgot to check for byte-compilation and check-doc.  We'll try to do that from now on, and in the meantime, I'll address the issues you've pointed out.

**Comment by riscy** [comment]
It really looks good.  Ping when ready for another look. :)

**Comment by Zaeph** [comment]
> It really looks good. Ping when ready for another look. :)

Thanks, @riscy. :)

I went ahead and stomped everything but some of `checkdoc`'s comments.

For `cl-pushnew`, I've required `cl-lib` only for compilation.  I hope this is all right:
https://github.com/zaeph/org-roam-bibtex/blob/bd4944ee7538d53ce9f1edbf470985a8e99dadb1/org-roam-bibtex.el#L66-L68

`checkdoc` is still giving me some slack for Lisp symbols needing to appear in quotes, but we're not *actually* referencing the symbols associated to them (e.g. `org-roam` the package, *not* the command).

**Comment by Zaeph** [comment]
I've added a keymap for a global-minor-mode, and `checkdoc` isn't too happy about the format:
https://github.com/zaeph/org-roam-bibtex/blob/f8f02108aee7f950818d1f12767fd731012af5ea/org-roam-bibtex.el#L352-L354
> Disambiguate org-roam-bibtex-mode by preceding w/ function,command,variable,option or symbol. (C-h,f,e,n,p,q)

I've checked how `org-mode` does it:
```el
(defvar org-mode-map (make-sparse-keymap)
  "Keymap fo Org mode.")   ; [sic], sent a patch for the typo
```

So yeah, side-stepping the issue.

**Comment by riscy** [comment]
This nag --

byte-compile-file (using Emacs 26.3):
```
org-roam-bibtex.el:377:16:Warning: assignment to free variable
    `org-ref-notes-function'
```
is not worth blocking the merge for, but you should add a `(defvar org-ref-notes-function)` at the top of your module to solve that one -- easy fix.

Docs are good but I ran a quick flyspell:
- bibliorgaphy -> bibliography (unless this is a pun!)
- propmt -> prompt
- bitex -> bibtex
- bibliograpic (bibliographic)
- perspecive -> perspective

And, all that said, welcome to MELPA!

**Comment by zaeph** [comment]
> ```
> org-roam-bibtex.el:377:16:Warning: assignment to free variable
>     `org-ref-notes-function'
> ```
> 
> 
> is not worth blocking the merge for, but you should add a `(defvar org-ref-notes-function)` at the top of your module to solve that one -- easy fix.

Thanks for spotting this.  Through the refactoring, we forgot to `(require 'org-ref)`, so I went ahead and added it.  I've also edited the `;; Package-Requires:` line in the header.

> And, all that said, welcome to MELPA!

Thank you!  🚀

**Comment by zaeph** [comment]
> Thanks for spotting this. Through the refactoring, we forgot to `(require 'org-ref)`, so I went ahead and added it. I've also edited the `;; Package-Requires:` line in the header.

We ended up going for a [different solution](https://github.com/zaeph/org-roam-bibtex/commit/d883b41b6d1e486efa9881e2077694aec47f70f9).

**Pull request merged**
