### PR TITLE
Add recipie for elegant-emacs

### PR DESCRIPTION
**Pull request by NicoloZorzetto**
### Brief summary of what the package does

A minimal yet elegant theme for Emacs. 

### Direct link to the package repository

https://github.com/rougier/elegant-emacs

### Your association with the package

I'm a contributor. I reached out to the author on Reddit and we evolved his code to be package friendly and in line with the Contributing.org guidelines.

### Relevant communications with the upstream package maintainer

This is my Pull request (now merged) [https://github.com/rougier/elegant-emacs/pull/12] where we also discussed briefly and the author clearly gives me the go ahead to make this pull request.

### Checklist

Please confirm with `x`:

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x ] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x ] My elisp byte-compiles cleanly
- [x ] `M-x checkdoc` is happy with my docstrings
- [x ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Here's a quick first pass --

### elegant-emacs-common.el ###

byte-compile (using Emacs 27.1):
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
elegant-emacs-common.el:593:1:Warning: the function `set-fontset-font' is not
    known to be defined.
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
elegant-emacs-common.el:196: White space found at end of line
```

package-lint (using version 20200901.2204):
```
6 issues found:
1:0: warning: The word "emacs" is redundant in Emacs package names.
73:0: error: "set-face" doesn't start with package's prefix "elegant-emacs-common".
150:0: error: "mode-line-render" doesn't start with package's prefix "elegant-emacs-common".
187:0: error: "set-modeline-faces" doesn't start with package's prefix "elegant-emacs-common".
213:0: error: "set-button-faces" doesn't start with package's prefix "elegant-emacs-common".
384:0: error: Define compatibility functions with a prefix, e.g. "elegant-emacs-common--package-make-button", and use `defalias' where they exist.
```

Other possible lints:
- elegant-emacs-common.el#L147: Top-level `define-key` can overwrite user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))` -- but I think this is a theme, so why is it doing this?
- elegant-emacs-common.el#L25: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### elegant-emacs-dark-theme.el ###

byte-compile (using Emacs 27.1):
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
elegant-emacs-dark-theme.el:43:1:Error: Symbol's function definition is void: set-fontset-font
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200901.2204):
```
2 issues found:
1:0: warning: The word "emacs" is redundant in Emacs package names.
1:0: error: There is no (provide 'elegant-emacs-dark-theme) form.
```

Other possible lints:
- elegant-emacs-dark-theme.el#L42: Single-line comments should usually begin with `;;`
- elegant-emacs-dark-theme.el#L25: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### elegant-emacs-light-theme.el ###

byte-compile (using Emacs 27.1):
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
elegant-emacs-light-theme.el:43:1:Error: Symbol's function definition is void: set-fontset-font
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200901.2204):
```
2 issues found:
1:0: warning: The word "emacs" is redundant in Emacs package names.
1:0: error: There is no (provide 'elegant-emacs-light-theme) form.
```

Other possible lints:
- elegant-emacs-light-theme.el#L42: Single-line comments should usually begin with `;;`
- elegant-emacs-light-theme.el#L25: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading elegant-emacs-common.el
elegant-emacs-common.el:Error: Emacs 27.1 errored during load
Loading elegant-emacs-dark-theme.el
elegant-emacs-dark-theme.el:Error: Emacs 27.1 errored during load
Loading elegant-emacs-light-theme.el
elegant-emacs-light-theme.el:Error: Emacs 27.1 errored during load
Done.
```


### Package ###

- No .el file matches the name 'elegant-emacs'
- Prefer the default recipe if possible.
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- elegant-emacs-common.el (GPL) -- A very minimal but elegant and consistent theme
- elegant-emacs-dark-theme.el (GPL) -- A very minimal but elegant and consistent theme
- elegant-emacs-light-theme.el (GPL) -- A very minimal but elegant and consistent theme

**Comment by NicoloZorzetto** [comment]
Hello! We should have solved everything. We'll be in touch if anything else needs to be changed, deleted or added.

Thank you for the patience and opportunity!

**Comment by riscy** [comment]
No, thank you for being accommodating. :) 

Currently I think the recipe is out of date due to the filename changes.  You may want to see if you can make the default recipe work for you with an `:exclude` block for sanity.el, e.g. `(elegance :repo "rougier/elegance" :fetcher github :files (:defaults (:exclude "sanity.el")))` or similar.

**Comment by NicoloZorzetto** [comment]
> No, thank you for being accommodating. :)
> 
> Currently I think the recipe is out of date due to the filename changes. You may want to see if you can make the default recipe work for you with an `:exclude` block for sanity.el, e.g. `(elegance :repo "rougier/elegance" :fetcher github :files (:defaults (:exclude "sanity.el")))` or similar.

File names changed, sorry about that, it slipped my mind. I decided to just change the name of the files in the recipie so to not fill the user's melpa folder with the screenshots etc while keeping it not too long.

As I said, ANYTHING you think we should change we'll look into. Thanks for being a good sport, my mind is a bit full lately

**Comment by riscy** [comment]
>  I decided to just change the name of the files in the recipie so to not fill the user's melpa folder with the screenshots etc while keeping it not too long.

While we're on that topic, you may want to move these screenshots into a separate "screenshots" branch if they're large.  MELPA will scrub them out, but other installers (like straight.el) will check out the entire repo.

Regarding the recipe, you should have an `.el` file that matches the name of the recipe.  So, currently the recipe and the package-name inside the recipe are elegant-emacs, but you don't have an elegant-emacs.el file (preferred) or an element-emacs-pkg.el file.

I'll update you with an abbreviated check, since the above issue is causing some false positives:

### elegance.el ###

byte-compile (using Emacs 27.1):
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
elegance.el:26:7:Warning: assignment to free variable
    `org-display-inline-images'
elegance.el:27:7:Warning: assignment to free variable
    `org-redisplay-inline-images'
elegance.el:30:7:Warning: `org-confirm-elisp-link-function' is an obsolete
    variable (as of Org 9.3); use `org-link-elisp-confirm-function' instead.
elegance.el:70:1:Warning: defface for `fallback' fails to specify containing
    group
elegance.el:91:1:Warning: defgroup for `elegance' fails to specify containing
    group
elegance.el:96:7:Warning: assignment to free variable
    `custom-unlispify-remove-prefixes'
```
For the first two -- and I'm not an expert here -- aren't those functions in org-mode, not variables?

I'm looking a little more closely now and I see a lot of variables being set as soon as this file is loaded, but usually you'd want to put these kinds of configurations behind a mode (so that they can easily be undone).  Let me know if you need some pointers on that.

checkdoc (using version 0.6.2):
```
Warning (emacs): 
elegance.el:0: The first line should be of the form: ";;; package --- Summary"
Warning (emacs): 
elegance.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
elegance.el:24: You should have a section marked ";;; Code:"
Warning (emacs): 
elegance.el:603: The footer should be: (provide 'elegance)\n;;; elegance.el ends here
Warning (emacs): 
elegance.el:81: Argument `face' should appear (as FACE) in the doc string
Warning (emacs): 
elegance.el:151: All variables and subroutines might as well have a documentation string
Warning (emacs): 
elegance.el:181: You should convert this comment to documentation
Warning (emacs): 
elegance.el:231: All variables and subroutines might as well have a documentation string
Warning (emacs): 
elegance.el:255: All variables and subroutines might as well have a documentation string
Warning (emacs): 
elegance.el:278: All variables and subroutines might as well have a documentation string
Warning (emacs): 
elegance.el:89: White space found at end of line
```

Other possible lints:
- elegance.el#L18: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### elegant-dark-theme.el ###

byte-compile (using Emacs 27.1):
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
elegant-dark-theme.el:42:1:Error: Cannot open load file: No such file or directory, elegant
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
```
1 issue found:
1:0: error: There is no (provide 'elegant-dark-theme) form.
```

Other possible lints:
- elegant-dark-theme.el#L24: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### elegant-light-theme.el ###

byte-compile (using Emacs 27.1):
- Consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
elegant-light-theme.el:41:1:Error: Cannot open load file: No such file or directory, elegant
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
```
1 issue found:
1:0: error: There is no (provide 'elegant-light-theme) form.
```

Other possible lints:
- elegant-light-theme.el#L24: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading elegance.el
elegance.el:Error: Emacs 27.1 errored during load
Loading elegant-dark-theme.el
elegant-dark-theme.el:Error: Emacs 27.1 errored during load
Loading elegant-light-theme.el
elegant-light-theme.el:Error: Emacs 27.1 errored during load
Done.
```

### Package ###

- No .el file matches the name 'elegant-emacs'

**Comment by riscy** [comment]
Feel free to ping for another look, or followup with any questions. :)

**Comment by purcell** [comment]
I really like the visuals of this approach, but the `elegant.el` file is not really a package, and is more akin to a starter kit or a very wide set of hard-coded user preferences, given that it toggles all sorts of minor modes. This is typically not the sort of thing we host. The file appears to serve partly as a tool for defining the two themes (which *are* the sort of thing we happily host!) but it all works by using a large number of unprefixed top-level functions and variables instead of the proper `custom-theme-set-faces` and `custom-theme-set-variables` facilities, so they are not really standard Emacs themes at all. In summary, the current state of this is that it is a very interesting visual experiment, but not ready for wider distribution as a package.

**Comment by NicoloZorzetto** [comment]
> I really like the visuals of this approach, but the `elegant.el` file is not really a package, and is more akin to a starter kit or a very wide set of hard-coded user preferences, given that it toggles all sorts of minor modes. This is typically not the sort of thing we host. The file appears to serve partly as a tool for defining the two themes (which *are* the sort of thing we happily host!) but it all works by using a large number of unprefixed top-level functions and variables instead of the proper `custom-theme-set-faces` and `custom-theme-set-variables` facilities, so they are not really standard Emacs themes at all. In summary, the current state of this is that it is a very interesting visual experiment, but not ready for wider distribution as a package.

I understand and will pass along. I will also be sure to keep you informed if anything changes

**Comment by riscy** [comment]
Thanks both (@rougier and @NicoloZorzetto) -- I've been watching this project and enjoying the output.  Also thanks @purcell for contributing some perspective that I was lacking. :)

It makes sense to close this now, although don't hesitate to open another PR if there are spinoff packages that appear ready for MELPA.

**Pull request closed without merging**
