### PR TITLE
Add recipe for flycheck-swiftx

### PR DESCRIPTION
**Pull request by nhojb**
### Brief summary of what the package does

A Swift flycheck backend using the Swift compiler, with support for Xcode projects.

### Direct link to the package repository

https://github.com/nhojb/flycheck-swiftx

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This looks solid.  Some (recent) package-lint nags:

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191122.246):
```
2 issues found:

341:3: error: You should depend on (emacs "26.1") if you need `when-let*'.
394:3: error: You should depend on (emacs "26.1") if you need `when-let*'.
```

**Comment by nhojb** [comment]
Fixed. Thanks.

My version of emacs (26.3 from emacsformacosx.com), does not support the latest version of package-lint due to an incompatible version of `let-alist-1.0.6` (1.0.5 is installed). Maybe I should upgrade to a nightly...

**Comment by purcell** [comment]
> My version of emacs (26.3 from emacsformacosx.com), does not support the latest version of package-lint due to an incompatible version of `let-alist-1.0.6` (1.0.5 is installed). Maybe I should upgrade to a nightly..

That sounds suspicious. `package-lint` works all the way back to Emacs 24.1, and our CI builds are passing. If you're having a problem, please file a `package-lint` issue.

**Comment by nhojb** [comment]
I've checked again and let-alist is at 1.0.5 for both `brew emacs` and the current release build from emacsforosx.com. Both are 26.3. The 20191202 nightly (from emacsforosx.com) does include let-alist 1.0.6, but this is emacs 27.0.50.

I've submitted an issue on `package-lint`.

**Comment by nhojb** [comment]
Just wondered if there are any other issues with this PR?

let-alist issue is resolved (I was missing gnu from my `package-archives` list).

Thanks.

**Comment by riscy** [comment]
Apologies for the delay - my personal computer was having issues.

One non-blocking bit of feedback I have is this:

- flycheck-swiftx.el#L497: Don't quote lambdas; this prevents them from being compiled

But this looks ready to go.  Thanks!

**Pull request merged**
