### PR TITLE
Add recipe for lsp-javascript.

### PR DESCRIPTION
**Pull request by vibhavp**
### Brief summary of what the package does

Javascript and Typescript support for [lsp-mode](https://github.com/emacs-lsp/lsp-mode)

### Direct link to the package repository

https://github.com/emacs-lsp/lsp-javascript

### Your association with the package

Maintainer.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks!
- There's a GPL license in the repo, but there's no license header in the file. Please add one: try `M-x auto-insert` in an empty elisp buffer to get the boilerplate you'll need.
- I note you are not the author, but the listed author is here on `github`. Doesn't he want to maintain this himself?
- Please provide a `Commentary` section in the file.
- Since you're using `javascript-typescript-langserver`, and the package only delegates javascript support to that langserver, I feel like this package should be called `lsp-javascript-typescript` instead. There could be difference langservers for javascript eventually.
- Consider a simple `dolist` iteration across major mode names to avoid the repetition in the file.

Hope that helps!

**Comment by tarsius** [comment]
@vibhavp Friendly ping!

**Comment by vibhavp** [comment]
@tarsius thanks, got stuck in a bunch of other stuff.

> There's a GPL license in the repo, but there's no license header in the file. Please add one: try M-x auto-insert in an empty elisp buffer to get the boilerplate you'll need.

Done

> I note you are not the author, but the listed author is here on github. Doesn't he want to maintain this himself?

Yeah, I've talked to him about this. 

> Please provide a Commentary section in the file.

Done.

> Since you're using javascript-typescript-langserver, and the package only delegates javascript support to that langserver, I feel like this package should be called lsp-javascript-typescript instead. There could be difference langservers for javascript eventually.

Done

> Consider a simple dolist iteration across major mode names to avoid the repetition in the file.

Done

**Comment by purcell** [comment]
Thanks!

**Comment by purcell** [comment]
Sorry, I needed to revert this, because the package is broken: I didn't check carefully enough that everything was actually fixed before merging.

Your filename (and its metadata) must match the package name, so `lsp-javascript.el` should be `lsp-javascript-typescript` and the first and last lines must be fixed, together with the `provide` form and identifier names.

**Comment by vibhavp** [comment]
Fixed, sorry about that.

**Comment by purcell** [comment]
Sent you some fixes in https://github.com/emacs-lsp/lsp-javascript/pull/1 -- these were all as a result of running `package-lint` on the file, which is a required part of the submission guidelines above. :-/

**Pull request merged**
