### PR TITLE
Add recipe for pelican-mode.

### PR DESCRIPTION
**Pull request by joewreschnig**
### Brief summary of what the package does

pelican-mode is an Emacs minor mode for editing pages and posts in
Pelican sites. Pelican is a static site generator which can process a
variety of text file formats. For more information, see URL
https://blog.getpelican.com/.

It's intended to be used alongside a major mode for the Pelican
document. Currently supported formats are Markdown, reStructuredText,
AsciiDoc, and Org.

### Direct link to the package repository

https://git.korewanetadesu.com/pelican-mode.git

### Your association with the package

Maintainer/author/user.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick comments:
- `C-c <letter>` is [reserved for end-user customisation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html), so you should choose different bindings, or simply provide a prefix map that the user can bind to a key of their choice.
- Rather than a global minor mode and `pelican-mode-enable-if-site`, it would be more conventional to provide a minor mode and a globalised minor mode: the latter would use `pelican-mode-enable-if-site` to enable the minor mode only in appropriate buffers.

**Comment by joewreschnig** [comment]
> C-c <letter> is reserved for end-user customisation, so you should choose different bindings, or simply provide a prefix map that the user can bind to a key of their choice.

I've changed it to a prefix map. (I've not done this before, and based it on how Projectile does it.)

> Rather than a global minor mode and `pelican-mode-enable-if-site`, it would be more conventional to provide a minor mode and a globalised minor mode: the latter would use `pelican-mode-enable-if-site` to enable the minor mode only in appropriate buffers.

Unless I've misunderstood, this is exactly how it's implemented. Can you let me know which docs led you astray?

**Comment by purcell** [comment]
> Unless I've misunderstood, this is exactly how it's implemented. Can you let me know which docs led you astray?

Ah, it was the `text-mode-hook` part which confused me. You could alternatively use `define-globalized-minor-mode`, in which case the "enable-if" function would check for `(derived-mode-p 'text-mode)`. It'd be slightly terser that way.

In any case, merging now... :-)

**Comment by joewreschnig** [comment]
Thanks for the feedback and quick merge!

I've also filed some issues with `package-lint` based on it (which I hope to tackle in a couple weeks).

**Comment by purcell** [comment]
Awesome, thanks Joe!

**Pull request merged**
