### PR TITLE
Add recipe for i-ching

### PR DESCRIPTION
**Pull request by zzkt**
### Brief summary of what the package does

A package to consult the I Ching.

### Direct link to the package repository

https://github.com/zzkt/i-ching

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Have you seen this i-ching?: https://github.com/emacsattic/i-ching.git which I believe came from the Emacswiki [here](https://www.emacswiki.org/emacs/i-ching.el) -- in this cases it's a good idea to choose a name that doesn't clash, or (even better) reach out to the original maintainer, if possible, and see if you can't join forces.

Quick first pass in the meantime --

### i-ching.el ###

byte-compile (using Emacs 27.1):
```
i-ching.el:725:1:Warning: Unused lexical variable `i'
i-ching.el:725:1:Warning: Unused lexical variable `i'
i-ching.el:725:1:Warning: Unused lexical variable `i'
i-ching.el:853:1:Warning: Unused lexical argument `method'
In end of data:
i-ching.el:875:1:Warning: the function `coin-toss' is not known to be defined.
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other [lints](https://github.com/riscy/melpazoid):
- i-ching.el#L638: Optionally use `unless ...` instead of `when (not ...)`

**Comment by zzkt** [comment]
changes incorporated as suggested...

**Comment by zzkt** [comment]
I'm aware of the i-ching.el on the emacswiki (there is a mention of it & link in the Readme) and but not reached out to the author yet. The current version takes a slightly different approach, mainly the use of unicode for the hexagrams and potential to use other translations. I've recently updated, documented and packaged it and since there isn't anything with the same name in melpa I assumed the namespace issue wouldn't be a problem.

**Comment by riscy** [comment]
Thanks, code looks good.  We try to look outside MELPA to look for namespace issues as well, and I'm trying to do a better job of it as I go. :)  You can some relevant comments about Emacsmirror in this PR https://github.com/melpa/melpa/pull/6925#issuecomment-633909054 or this one https://github.com/melpa/melpa/pull/7000.

But I think this is a different case because you're creating a whole new package, rather than taking over maintenance of the existing one.  Probably you should rename in this case, unless there's some way you can the original author can team up.

**Comment by zzkt** [comment]
I've been in contact with the author of the emacswiki version, and he isn't planning to revive it. so renaming  this package shouldn't be necessary (see zzkt/i-ching/issues/3 )

**Comment by riscy** [comment]
@tarsius This feels like a grey area that I am not completely comfortable in.  Can we borrow your wisdom? :)

In summary the issue is that emacswiki, and hence emacsmirror, already has a package called i-ching.  @zzkt has been in touch with the author who isn't planning to do more with that i-ching package.  Should MELPA index this new i-ching package?

**Comment by tarsius** [comment]
IMO it is okay to reuse the obvious name in such cases. If the old implementation were a popular package, then the situation might be different.

I would however recommend that the author of the new implementation carefully studied the old implementation and ported any nice features that are still missing. A link to the old implementation would be nice.

Both implementations have messed up whitespace. It would be nice if that could be fixed in the new implementation before we add it. (Mark the whole buffer and do `indent-region`.)

**Comment by zzkt** [comment]
Thanks @tarsius I've fixed the formatting and there is a link to the previously published version in the [readme](https://github.com/zzkt/i-ching/blob/endless/README.org). There are certainly a few features that would be good to incorporate, some are listed at https://github.com/zzkt/i-ching/issues/2

**Comment by riscy** [comment]
Sounds good to me.  Following that, there's just one byte-compile warning:

byte-compile (using Emacs 27.1):
```
i-ching.el:632:1:Warning: Unused lexical argument `number'
```
which you could fix by underscore-prefixing the variable if it's truly meant to be unused.  After that should be a quick merge.

**Comment by zzkt** [comment]
Thanks @riscy I've fixed the warning (unused → feature)

**Comment by riscy** [comment]
Great, thanks.  Merging this now.

**Pull request merged**
