### PR TITLE
Add helm-lxc

### PR DESCRIPTION
**Pull request by montag451**
### Brief summary of what the package does

Helm interface to manage LXC containers

### Direct link to the package repository

https://github.com/montag451/helm-lxc

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by montag451** [comment]
@riscy Thanks for you feedback ! I have updated my repository accordingly. Regarding the license, the text in the source file states that:

> ;; This program is free software; you can redistribute it and/or modify
> ;; it under the terms of the GNU General Public License as published by
> ;; the Free Software Foundation, either version 3 of the License, or
> ;; (at your option) any later version.

So if I understand the text above (I may be wrong, I'm a total newbie regarding this license things :)) the license used is GPL 3 or later no ?

**Comment by riscy** [comment]
You're completely right about the version being in there - sorry about that.  It's subjective, but I think it is still worth adding a copy of the license to your repository (a COPYING file).  After all, your commentary says your users should have received one. :)  It's a small thing, but there is also the additional advantage that GitHub will detect the license file and create an icon for people to look for:
image

**Comment by purcell** [comment]
Thanks, and sorry for the slow turnaround.

One note I have is that you should not [define new faces with only `:foreground`](https://github.com/montag451/helm-lxc/blob/a4e17dda329ec39a3dac5751ddcef1145b3d91c1/helm-lxc.el#L53-L66) -- these will be guaranteed to look bad in many themes. Instead, `:inherit` from built-in faces like `success`, `warning`, `error` etc. by default.

But I'll go ahead and merge this in the meantime. :-)

**Comment by montag451** [comment]
Don't worry about the "slow turnaround", the work you do for the Emacs community is very much appreciated.

Regarding the definition of faces, I will make the changes you requested as soon as possible. 

Thank you again!

**Pull request merged**
