### PR TITLE
added monochromatic theme.

### PR DESCRIPTION
**Pull request by diasbruno**
### Brief summary of what the package does

Simple monochromatic theme.

### Direct link to the package repository

[github:diasbruno/monochromatic-theme](https://github.com/diasbruno/monochromatic-theme)

### Your association with the package

Author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! A few things to address here:

- There are four monochrome themes already in MELPA. What's the difference here? Could you use/extend one of the existing themes?
- It's far from monochrome, so I'm not sure that it's as advertised! Perhaps a better name and/or description is in order.
- Yellow tooltips are not going to work if the background is yellowish.
- You should never set specific fonts in themes: on numerous Emacs platforms, Menlo and/or Arial will not be available, and themes have no business changing the user's font family and size preferences.

**Comment by diasbruno** [comment]
Hi @purcell. In this theme you can choose background and foreground colors, but probably it still needs some fixes for sure (the idea is to highlight only errors and warning). I couldn't find a theme that does this, so I've created this one. 
Those fonts I actually forget to remove (thanks).

**Comment by diasbruno** [comment]
Yeah, probably rename this package is better.

**Comment by diasbruno** [comment]
Fixed the fonts and tooltip.
Should I close this PR and create a new one when I rename the package or should I keep this one opened?

**Comment by purcell** [comment]
> Should I close this PR and create a new one when I rename the package or should I keep this one opened?

Probably just open a fresh one. I'll go ahead and close this, then. :-)

**Pull request closed without merging**
