### PR TITLE
Add bart-mode

### PR DESCRIPTION
**Pull request by mschuldt**
### Brief summary of what the package does

   Display real-time departure information for the Bay Area Rapid Transit (BART) system.

### Direct link to the package repository

   https://github.com/mschuldt/bart-mode

### Your association with the package

  I am the author

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by tarsius** [comment]
The build error is due to an unrelated change, which is fixed now. Please rebase your commit so that the tests can be run for your change. If you use Magit you can do so using <kbd>f u</kbd> to fetch, <kbd>r u</kbd> to rebase, and <kbd>P - f p</kbd> to force push.

**Comment by mschuldt** [comment]
rebased

**Comment by mschuldt** [comment]
Is there a problem with this?

**Comment by tarsius** [comment]
I don't usually perform the actual review and @purcell probably just overlooked this.

**Comment by purcell** [comment]
Yep, this fell between the cracks, sorry: December & Jan have been crazy for me. Some feedback, then:
- Firstly, nice work!
- Don't hard-code completion to use `ido`. Instead, use `completing-read`, which will be overridden automatically by the user's preferred completion system.
- Use `special-mode` as the parent mode rather than `fundamental-mode`.
- You shouldn't need to set the local keymap [here](https://github.com/mschuldt/bart-mode/blob/f857a9e54801bd057ee28c938f8f08e2ca18eb17/bart-mode.el#L297), because `define-derived-mode` will do it *if* the mode name matches up with the map name -- which you could easily arrange: it's not necessary for the mode name to be `bart--mode` instead of `bart-mode`, and indeed that choice is unusual.
- Setting explicit colours and other face attributes is bad practice. You should instead define customisable faces with dark/light background variants, or (better) that `:inherit` built-in faces by default (e.g. `header`, `warning`, `success`) so that they automatically fit in with users' themes. You should particularly avoid setting font sizes and weights.

Hope that helps!

**Comment by purcell** [comment]
Also:
- `cl-lib` has `cl-caddar`, so you don't need to roll your own.
- Don't wrangle windows explicitly for your own preferences: you'll just annoy somebody else. Just use `display-buffer`, which allows customisation of window selection.

**Comment by mschuldt** [comment]
@purcell Thank you very much for you review, I believe I have addressed all the issues.

I've created a new option to enable the window wrangling in the way I like it, but by default it is disabled and uses display-buffer instead

**Comment by purcell** [comment]
Great, merged! Welcome to MELPA. :-)

**Pull request merged**
