### PR TITLE
Add org-redmine

### PR DESCRIPTION
**Pull request by yasuyk**
https://github.com/gongo/org-redmine

/cc @gongo

### CODE REVIEW

**Comment by tarsius** [comment]
@gongo Why was the repository of this package archived? Others might wonder the same, so I recommend you add a note about to the README.md.

Also, should this package be removed from Melpa?

**Comment by gongo** [comment]
@tarsius Hi.

> Why was the repository of this package archived?

The reason is that the motivation to continue development is gone. (Because I no longer use Redmine)

> Others might wonder the same, so I recommend you add a note about that to the README.md.

You are right. I have added a note with [this commit](https://github.com/gongo/org-redmine/commit/7f1cfa0cc4e6eeb076607f501868a7f5690461f4).

> Also, should this package be removed from Melpa?

Don't need to delete it.
However, if continue development in a forked repository by someone, switch to that repository.

**Comment by gongo** [comment]
Thank you for information.

> If you want to do that, then transfer the package to my personal account and I will then transfer it to the orphanage.

I want to do this. Can I transfer it now?

**Comment by tarsius** [comment]
Yes, please go ahead. I think you have to unarchive it first.

**Comment by gongo** [comment]
I sent you a request 💪

**Comment by tarsius** [comment]
The repository has arrived at https://github.com/emacsorphanage/org-redmine and I've updated the Melpa recipe.

Thanks!

**Pull request merged**
