### PR TITLE
Add recipe for recur

### PR DESCRIPTION
**Pull request by ROCKTAKEY**
### Brief summary of what the package does
Tail recursive call optimization for Emacs.

### Direct link to the package repository

https://github.com/ROCKTAKEY/recur

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, I like the implementation.  There are a couple such packages floating around (one is on MELPA), so I wonder if you've had a chance to take a look and see if they're useful:

- https://github.com/Wilfred/tco.el
- https://github.com/emacsmirror/let-recur

The checklist look great, with only one minor lint I'd suggest on recur.el#L131: It's safer to sharp-quote function names; use `#'`.

**Comment by ROCKTAKEY** [comment]
@riscy, thanks for telling similar packages. I hadn't known these packages. I saw these and summarized difference between these packages and `recur`.

| package | call | `let` | `defun` | `&optional` | `&rest`| implementation|
|-|-|-|-|-|-|-|
| recur | `recur` | `recur-let` | `recur-defun`| ✅ | ✅ | `cl-labels` and `cl-symbol-macrolet`|
| tco | itself | - | `defun-tco`| ✅ | ? | ad-hoc |
| let-recur | `:recur` | `let-recur` | - | - | - | ad-hoc |

These two package use ad-hoc implementation (recursively replacement of S expression), while `recur` use `cl-labels` and `cl-symbol-macrolet`, which recognize context. 

`tco` CAN use `&rest`, but it CANNOT optimize tail call using `apply` like `(apply #'sum (+ (car args) (cadr args)) (cddr args))`. It means that tco cannot actually treat `&rest`, because `&rest` arguments should be expanded to call recursively. 

`recur` treat each argument as one argument even if it is `&rest` one, so there is no problem.

```emacs-lisp
(recur-defun sum (init &rest list)
  (if list
      (recur (+ init (car list))
             (cdr list)) ; just pass one argument as `list`
    init))
```

BTW, I cannot get the lint suggestion by `package-lint-curent-buffer`, `checkdoc` and `byte-compile-file`. It might be fixed, but I cannot confirm it. How can I get the lint result? What package?

**Comment by riscy** [comment]
>  I saw these and summarized difference between these packages and recur.

That's a huge help!  Thank you, I think this looks good to merge.

> How can I get the lint result? What package?

That's one of the checks I babysit [here](https://github.com/riscy/melpazoid) but it sometimes throws false positives because it's purely regexp based, so I usually manually verify before passing those along.  Sharp-quotes are well worth it, though, because the byte-compiler will warn you when functions don't exist.

**Comment by ROCKTAKEY** [comment]
Thanks a lot!

>  Sharp-quotes are well worth it

Yes, I strongly agree. I will use melpazoid. Thanks!

**Pull request merged**
