### PR TITLE
Add recipe for basic-mode

### PR DESCRIPTION
**Pull request by dykstrom**
### Brief summary of what the package does

Package basic-mode is a major mode for editing BASIC source code

### Direct link to the package repository

https://github.com/dykstrom/basic-mode

### Your association with the package

I am the creator and maintainer of the package

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick feedback:
- You can use `syntax-ppss` to do [this](https://github.com/dykstrom/basic-mode/blob/1dae06e2b09bd3903643f640badb769f1d50b04a/src/basic-mode.el#L110-L114) much more efficiently.
- IIRC, it's possible to tell `font-lock` to not be case-sensitive w.r.t. keywords etc., which I think would let you tidy things up.
- Instead of listing the (incomplete) bindings list [here](https://github.com/dykstrom/basic-mode/blob/1dae06e2b09bd3903643f640badb769f1d50b04a/src/basic-mode.el#L110-L114), just put `\{basic-mode-map}` in the docstring so that Emacs will do it for you automatically.

None of these are a blocker, so I'm merging now, but they're worth addressing IMO.

**Comment by dykstrom** [comment]
Hi, 

thanks for your comments! Those were things I didn't know, but I'll try to address them in a future version of basic-mode some time soon.

BR, Johan

**Comment by purcell** [comment]
Specifically, `(save-match-data (nth 8 (syntax-ppss)))` returns a non-`nil` value if `point` is in a string or comment, which is pretty convenient. :-)

**Comment by dykstrom** [comment]
I have tried that out, but I experienced one problem. If the point is on the very first character of a string or comment (for elisp that would be the " or ; character), the expression above returns nil. Do you have any good solution for that?

**Comment by purcell** [comment]
> I have tried that out, but I experienced one problem. If the point is on the very first character of a string or comment (for elisp that would be the " or ; character), the expression above returns nil. Do you have any good solution for that?

Ah, yes: what you want is the following instead:
```el
(let ((ppss (syntax-ppss)))
    (or (car (setq ppss (nthcdr 3 ppss)))
        (car (setq ppss (cdr ppss)))
        (nth 3 ppss)))
```

**Pull request merged**
