### PR TITLE
Added org-visibility recipe

### PR DESCRIPTION
**Pull request by nullman**
### Brief summary of what the package does

Org Visibility is an Emacs package that adds the ability to persist (save and load) the state of the visible sections of `org-mode' files.

### Direct link to the package repository

https://github.com/nullman/emacs-org-visibility

### Your association with the package

I am the author and the maintainer.

### Relevant communications with the upstream package maintainer

This is my first MELPA package request.  I believe I have followed all of the instructions.

I'm concerned about my use of save and load hooks.  Please let me know if there is a better way to handle that.  See **org-visibility-enable-hooks** and **org-visibility-disable-hooks**.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Review by riscy — COMMENTED** [review]
Thanks, this is a cool idea and extremely well documented --

Not a blocker or anything but have you experimented with how this interacts with the [STARTUP option and VISIBILITY properties](https://orgmode.org/manual/Initial-visibility.html)?  It strikes me that another way to implement this feature would be to implement a minor mode that dynamically updates VISIBILITY properties on save.

One other thing you may or may not be aware of is that the package Description (e.g. on a page like [this](https://melpa.org/#/magit)) that MELPA will create will exclude everything below `;;; Insallation:` (you can run `(lm-commentary)` to check this); that might be deliberate, but I wanted to check whether you e.g. wanted to exclude the Usage instructions from the Description.

**Comment by nullman** [comment]
> Not a blocker or anything but have you experimented with how this interacts with the [STARTUP option and VISIBILITY properties](https://orgmode.org/manual/Initial-visibility.html)?

I haven't and it might be an interesting way to do the same thing.  I don't think I would want to modify the original file, however, as that would cause an update (in say git) every time a user viewed the file.  But if the VISIBILITY property could be stored elsewhere that might work.

> One other thing you may or may not be aware of is that the package Description (e.g. on a page like [this](https://melpa.org/#/magit)) that MELPA will create will exclude everything below `;;; Insallation:` (you can run `(lm-commentary)` to check this); that might be deliberate, but I wanted to check whether you e.g. wanted to exclude the Usage instructions from the Description.

I wasn't aware of this.  I've added a commit to remove the extra semicolons on those two sections.  Thanks for pointing this out.

**Comment by riscy** [comment]
Thanks!  Looks good to me.  There are a couple other quick things I'll mention -- neither of them blockers -- as I merge this:

- a couple of your calls to the `error` builtin might instead be `user-error` (the former will open a stack trace whereas the latter will not).  For example in `org-visibility-load-internal`
- the functions `org-visibility-enable-hooks` and `org-visibility-disable-hooks` look like great candidates for just bundling into a global minor mode called `org-visibility-mode`, which is the idiomatic way of toggling behavior off/on in Emacs.  Let me know if I can give you more pointers here, because I think that would be a good idea

**Comment by riscy** [comment]
And, welcome to MELPA! :)

**Comment by nullman** [comment]
> And, welcome to MELPA! :)

Thanks!

Your suggestions sound like good ones.  I'll work on making those changes.

**Pull request merged**
