### PR TITLE
Add recipe for samskritam

### PR DESCRIPTION
**Pull request by thapakrish**
### Brief summary of what the package does

This package aims to be a utility tool to interact with Samskrit language. To that end, find word definitions, translate to and from samskrit, augment in-built devanagari inscript

### Direct link to the package repository

https://github.com/thapakrish/samskritam.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`samskritam.el` with byte-compile using Emacs 28.1:
```
samskritam.el:38:1: Error: Cannot open load file: No such file or directory, google-translate
```
This package appears to be missing a `Package-Requires` line (q.v.) to specify a dependency on google-translate, popup, and any others.

`samskritam.el` with checkdoc 0.6.2:
```
samskritam.el:94: Some lines are over 80 columns wide
samskritam.el:130: All variables and subroutines might as well have a documentation string
samskritam.el:142: Argument `choose-service' should appear (as CHOOSE-SERVICE) in the doc string
samskritam.el:205: Argument `regexp' should appear (as REGEXP) in the doc string
samskritam.el:266: Argument `method' should appear (as METHOD) in the doc string
```

`samskritam.el` with package-lint 20220607.738:
```
29 issues found:
1:0: warning: The package summary should not end with a period.
1:0: warning: The package summary should start with an uppercase letter or a digit.
10:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
52:0: error: "google-translate--search-tkk" doesn't start with package's prefix "samskritam".
62:3: warning: Closing parens should not be wrapped onto new lines.
68:0: error: "define-sanskrit-word-limit" doesn't start with package's prefix "samskritam".
78:0: error: "define-sanskrit-word-displayfn-alist" doesn't start with package's prefix "samskritam".
85:0: error: "define-sanskrit-word-displayfn" doesn't start with package's prefix "samskritam".
90:0: error: "define-sanskrit-word-services" doesn't start with package's prefix "samskritam".
93:4: warning: Closing parens should not be wrapped onto new lines.
102:0: error: "define-sanskrit-word-default-service" doesn't start with package's prefix "samskritam".
110:0: error: "define-sanskrit-word--to-string" doesn't start with package's prefix "samskritam".
129:0: error: "define-sanskrit-word--expand" doesn't start with package's prefix "samskritam".
141:0: error: "define-sanskrit-word" doesn't start with package's prefix "samskritam".
163:2: warning: Closing parens should not be wrapped onto new lines.
167:0: error: "define-sanskrit-word-at-point" doesn't start with package's prefix "samskritam".
187:0: error: "define-sanskrit-word-face-1" doesn't start with package's prefix "samskritam".
191:0: error: "define-sanskrit-word-face-2" doesn't start with package's prefix "samskritam".
195:0: error: "define-sanskrit-word--join-results" doesn't start with package's prefix "samskritam".
204:0: error: "define-sanskrit-word--regexp-to-face" doesn't start with package's prefix "samskritam".
212:0: error: "define-sanskrit-word--tag-faces" doesn't start with package's prefix "samskritam".
221:0: warning: Closing parens should not be wrapped onto new lines.
223:0: error: "define-sanskrit-word--convert-html-tag-to-face" doesn't start with package's prefix "samskritam".
233:0: error: "define-sanskrit-word--parse-mw" doesn't start with package's prefix "samskritam".
258:8: warning: Closing parens should not be wrapped onto new lines.
265:0: error: "toggle-alternative-input-method" doesn't start with package's prefix "samskritam".
276:0: error: "reload-alternative-input-methods" doesn't start with package's prefix "samskritam".
304:80: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
305:1: warning: Closing parens should not be wrapped onto new lines.
```

`samskritam.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- samskritam.el#L256: Top-level `setq` should usually be replaced by `defvar`
- samskritam.el#L260: Top-level `setq` should usually be replaced by `defvar`
```

**Comment by thapakrish** [comment]
@riscy these are really helpful, thanks! I thought I had gone through the package-lint step but apparently not (I needed to apply linting on the buffer but was activating the mode. No wonder I did not see any issues). 

I've updated the package repository that recipe points to.

**Comment by riscy** [comment]
Thanks for accommodating those changes.

Apologies for wrongly suggesting `popup` belongs in your `Package-Requires -- it turns out that was a dependency of `google-translate` that wasn't being installed by that package (you can see the linked PR above).  You actually shouldn't have a dependency on `popup`, since you don't explicitly use it.

Beyond fixing that issue that I introduced :) here's the latest:

`samskritam.el` with byte-compile using Emacs 28.1:
```
samskritam.el:86:1: Warning: custom-declare-variable
    `samskritam-word-services' docstring wider than 80 characters
In samskritam-word--parse-mw:
samskritam.el:235:70: Warning: Unused lexical variable `part'
```
Re: the unused lexical variable, you can rename it to `_part` and the compiler will be happy.

`samskritam.el` with checkdoc 0.6.2:
```
samskritam.el:89: Some lines are over 80 columns wide
samskritam.el:125: Argument `regex' should appear (as REGEX) in the doc string
```

`samskritam.el` with package-lint 20220607.738:
```
9:38: warning: Use a non-snapshot version number for dependency on "google-translate" if possible.
10:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
296:1: warning: Closing parens should not be wrapped onto new lines.
```
You can visit https://stable.melpa.org to get the version number for the google-translate dependency (and you should remove the popup dependency as mentioned above).

- Add a LICENSE file to the repository

**Comment by thapakrish** [comment]
@riscy great, thanks for looking into it! I've updated the repo to address remaining issues raised by `checkdoc` and `package-lint`, removed `popup` requirement, and also included license.

**Comment by riscy** [comment]
No problem - that looks like it puts the checklist behind us.  There are a couple other quick issues I see, but they're not major and can be fixed at your convenience:

- The `(defvar samskritam-mode)` is unnecessary -- this forward declaration may be leftover from some earlier version of the code
- When the (global) major-mode is turned on it adds to `google-translate-supported-languages-alist`, but when it's turned off it doesn't remove the same element from the list -- is this intentional?  Ideally it should toggle everything about the mode off

All that said, welcome to MELPA. :)

**Comment by thapakrish** [comment]
Awesome,  thanks for the suggestions. Will address in the future versions (once I become a little more competent in elisp :) ). Glad to have gone through the mechanics of adding recipe,  really excited :)

**Pull request merged**
