### PR TITLE
Added region-occurrences-highlighter recipe

### PR DESCRIPTION
**Pull request by alvarogonzalezsotillo**
### Brief summary of what the package does

This minor mode marks all the occurrences of the current region (selection), like VSCode does.

### Direct link to the package repository
https://github.com/alvarogonzalezsotillo/region-occurrences-highlighter

### Your association with the package

I am the author and the only contributor.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi!  I tested this out and it works great for me.  Some miscellaneous comments/suggestions:
- 4: If possible, prefer `https://` to `http://`
- 22: If possible, prefer `https://` to `http://`
- The double-hyphen in region-occurrences-highlighter--group is probably not necessary -- usually this would signify a "private" function or variable that users/developers shouldn't rely on, but a _group_ should definitely be part of your mode's public interface (e.g. users will want to write `M-x customize-group region...group`)
- Similarly, customizable variables (like region-...max-size) probably shouldn't be "private"
- I believe specifying the `:group` on these customizables isn't strictly necessary -- once you've defined the group earlier in the file, they're automatically a part of it.
- Your `;;;###autoload` line has a leading space before it
- You should add a LICENSE or COPYING file to the repository (this will let GitHub add a nice icon that makes it easier for users to know what they're using).  I think the summarized license in your source file is a little bit too informal.

**Comment by alvarogonzalezsotillo** [comment]
I think I have addressed all your comments in the commit https://github.com/alvarogonzalezsotillo/region-occurrences-highlighter/commit/a781ac6dafa72350c2226c00ae6b768e07008afa

**Comment by purcell** [comment]
Thanks, this mostly looks good, but one thing that stands out is that [this line](https://github.com/alvarogonzalezsotillo/region-occurrences-highlighter/blob/master/region-occurrences-highlighter.el#L75) should be redundant, and the reason you found it isn't is because you are failing to pass the `local` flag to `add-hook`/`remove-hook` [here](https://github.com/alvarogonzalezsotillo/region-occurrences-highlighter/blob/master/region-occurrences-highlighter.el#L63-L65). The current code is effectively a non-global minor mode which modifies the global version of `post-command-hook`. :-)

Hope that helps!

**Comment by alvarogonzalezsotillo** [comment]
Solved in https://github.com/alvarogonzalezsotillo/region-occurrences-highlighter/commit/07be4b8026f6a19ef3811bfe7fdc49e7e4909fb4

I hoped I could manage to publish a recipe before anyone noticed I have no idea about elisp  :)

**Comment by purcell** [comment]
Yeah, so now you can (and should) remove that redundant line as noted above. Merging in any case: welcome to MELPA! :tada:

**Pull request merged**
