### PR TITLE
add js-import recipe

### PR DESCRIPTION
**Pull request by jakoblind**
### Brief summary of what the package does

Automatically import JavaScript files from the current project or dependencies

### Direct link to the package repository

https://github.com/jakoblind/js-import

### Your association with the package

I am creator and maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- What is different from `https://github.com/galooshi/emacs-import-js` ?
- No `Package-Requires` header
 - This package requires `f`, `projectile`, `dash`
 - This package requires Emacs 24.4 or higher version because it uses `subr-x`
- Use `js-import-` prefix instead of `jsi/`.
 - Use `-` separator instead of `/` for emacs lisp coding convention
 - `js-import--` should be used for private functions/global variables
- No autoload cookie

**Comment by jakoblind** [comment]
I have updated the code based on your comments.

The difference between this package and `https://github.com/galooshi/emacs-import-js` is that this package doesn't have dependency on any NPM applications.

**Comment by purcell** [comment]
Thanks. A little more feedback:
- Please depend on stable versions of packages, not snapshot versions. You can generally find the latest stable version by looking on stable.melpa.org.
- Docstring for `js-import` is missing. (`M-x checkdoc` for the win!)
- If you're always assuming a `package.json`, then you almost certainly don't need to depend on and use `projectile` - just use `locate-dominating-file`. :-)

**Comment by jakoblind** [comment]
I have updated the code. 

I also use projectile for getting all files in the project, so I still would need the dependency even if I would use `locate-dominating-file`.

**Comment by purcell** [comment]
Cool, thanks. Merged!

**Pull request merged**
