### PR TITLE
Add docker-compose-mode recipe

### PR DESCRIPTION
**Pull request by meqif**
### Brief summary of what the package does

Major mode for editing docker-compose files, providing completion of keys.

### Direct link to the package repository

https://github.com/meqif/docker-compose-mode

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed** if there is no problem.

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mattiasb** [comment]
Nice! I think this could be made even better by making it a `completion-at-point-functions` backend instead. That way you'd get support for the completion system shipped with vanilla Emacs, other 3rd-party frontends like autocomplete- and ido-at-point in addition to Company (which has a capf-backend).

**Comment by mattiasb** [comment]
Take a look [here](https://github.com/mattiasb/mtg-deck-mode/blob/master/mtg-deck-mode.el#L138-L145) and [here](https://github.com/mattiasb/mtg-deck-mode/blob/master/mtg-deck-mode.el#L186-L187) for an example of how to set it up. :)

**Comment by purcell** [comment]
> Nice! I think this could be made even better by making it a completion-at-point-functions backend instead. That way you'd get support for the completion system shipped with vanilla Emacs, other 3rd-party frontends like autocomplete- and ido-at-point in addition to Company (which has a capf-backend).

Yep, agreed. This would be even better IMO if it were not `company`-specific. (And I say that as a user and fan of `company`!)

**Comment by meqif** [comment]
Thank you for your kind feedback. I took your suggestions to heart and replaced the `company-mode` backend with a capf one, and ended up creating a major mode as well.

**Comment by mattiasb** [comment]
@meqif that's great! :)

**Comment by purcell** [comment]
That rocks! Great outcome, and nice work. Merging now...

**Comment by meqif** [comment]
Awesome, thank you! 🎉

**Comment by tarsius** [comment]
@meqif, you have archived the repositories of `docker-compose-mode` and `flymake-diagnostic-at-point`. Have you moved them elsewhere and Melpa should get them from there? (If so, you should add a note to that effect here on Github.)

Or should these packages be removed from Melpa?

**Comment by meqif** [comment]
Hi @tarsius 👋🏼 It's best to remove them, if you don't mind.

**Comment by tarsius** [comment]
Done. Thanks for the quick response!

**Pull request merged**
