### PR TITLE
Add recipe for Elfeed Related sidecar section

### PR DESCRIPTION
**Pull request by swflint**
### Brief summary of what the package does

This provides a sidecar section to show bibliography entries which may be related to the current elfeed entry.

### Direct link to the package repository

https://git.sr.ht/~swflint/emacs-universal-sidecar

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

See #8604.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
(Just noting that when https://github.com/melpa/melpa/pull/8605 and your other earlier PRs are resolved I'll pick up here.)

**Comment by riscy** [comment]
Thanks again for this. Here's a quick first pass --

`universal-sidecar-elfeed-related.el` with byte-compile using Emacs 28.1:
```
universal-sidecar-elfeed-related.el:94:32: Warning: reference to free variable
    `universal-sidecar-elfeed-related-citation-formatter'
```

`universal-sidecar-elfeed-related.el` with package-lint 20230905.629:
```
2 issues found:
54:0: error: "elfeed-related-papers-citation-formatter" doesn't start with package's prefix "universal-sidecar-elfeed-related".
67:56: error: `authors' was removed in Emacs version 25.1.
```
The `authors` nag is a common one.  Not a blocker, but I recommend `authors_` instead (using the `_` suffix as a universal disambiguator).

`universal-sidecar-elfeed-related.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- universal-sidecar-elfeed-related.el#L69: There is no need to quote lambdas (neither #' nor ')
- universal-sidecar-elfeed-related.el#L77: There is no need to quote lambdas (neither #' nor ')
```
Minor, but fyi -

**Comment by swflint** [comment]
I think I've got those all fixed.  Thanks!

**Comment by riscy** [comment]
Minor, but since you've been diligent with your docstrings --

`universal-sidecar-elfeed-related.el` with checkdoc 0.6.2:
```
universal-sidecar-elfeed-related.el:68: Argument `authors-list' should appear (as AUTHORS-LIST) in the doc string
```
and this is ready to go. :)

**Comment by swflint** [comment]
Thanks!

**Pull request merged**
