### PR TITLE
Add shadowenv recipe

### PR DESCRIPTION
**Pull request by dantecatalfamo**
### Brief summary of what the package does

[Shadowenv](https://github.com/Shopify/shadowenv) integration.

### Direct link to the package repository

https://github.com/Shopify/shadowenv.el/

### Your association with the package

I'm the package author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by dantecatalfamo** [comment]
Fixed, thanks!

**Comment by dantecatalfamo** [comment]
Problems fixed, thanks for the check 👌

**Comment by riscy** [comment]
Taking a deeper look at this now - 

- [Here](https://github.com/Shopify/shadowenv.el/blob/master/shadowenv.el#L64-L66) I believe you can use `defvar-local` -- for this and the others.
- [Here](https://github.com/Shopify/shadowenv.el/blob/master/shadowenv.el#L78), `unless if` could be confusing -- this should be refactored into a single `if`
- [This](https://github.com/Shopify/shadowenv.el/blob/master/shadowenv.el#L194) should use `not` or `null`.
- For [these](https://github.com/Shopify/shadowenv.el/blob/master/shadowenv.el#L157-L161) forms, since you rely on Emacs 24, I believe you can use `setq-local`
- [This](https://github.com/Shopify/shadowenv.el/blob/master/shadowenv.el#L112-L120) appears to be a good case for `pcase`
- Should [this hook](https://github.com/Shopify/shadowenv.el/blob/master/shadowenv.el#L163) be removed in `shadowenv-down`?

**Comment by riscy** [comment]
> Here, unless if could be confusing -- this should be refactored into a single if

Well, maybe not a *single* if :)  What about something like:
```elisp
(defun shadowenv-run (data)
  "Run shadowenv porcelain with DATA."
  (if shadowenv-binary-location
     (file-executable-p shadowenv-binary-location)
    (or (executable-find "shadowenv") (error "Cannot find..."))))
```

**Comment by dantecatalfamo** [comment]
I'm not sure how to use `pcase` in this scenario and get it to evaluate and compare the strings instead of setting `shadowenv--set-exported` to the value of `opcode`

**Comment by riscy** [comment]
I think this works:
```elisp
(pcase opcode
  (shadowenv--set-exported   (setenv variable value))
  (shadowenv--unset          (setenv variable))
  (shadowenv--set-unexported
   (if (string= variable "__shadowenv_data")
       (setq shadowenv-data value)
     (warn "Unrecognized operand for SET_UNEXPORTED operand: %s" variable))))

**Comment by dantecatalfamo** [comment]
I tried that earlier when you suggested it but when I expand the macro it only creates this so I'm not sure if it's working as intended:
```elisp
(let
    ((shadowenv--set-exported opcode))
  (setenv variable value))
```

**Comment by riscy** [comment]
You're totally correct -- I had no experience using pcase with non-literals before and figured it would be similar, but it's not.  Thanks for hearing me out.  I'll take another look later today. :)

**Comment by riscy** [comment]
Checkdoc's telling me you'll have to rely on `((emacs "24.3"))` for `setq-local`, and then I think this is all set.  I should have been more specific.  Thanks. :)

**Comment by dantecatalfamo** [comment]
Dependancy updated, thanks a lot for all your help with this 😄

**Comment by riscy** [comment]
Great!

**Pull request merged**
