### PR TITLE
Add recipe for kana.

### PR DESCRIPTION
**Pull request by chenyanming**
### Brief summary of what the package does

It is a language learning tool that helps users to study Japanese hiragana and katakana.

### Direct link to the package repository

https://github.com/chenyanming/kana

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for your close adherence to the checklist.  Some more quick feedback:

- kana.el#L174: Prefer `define-derived-mode` instead of `defun kana-mode`; this will handle everything from `kill-all-local-variables` to setting the `mode-name` and `major-mode` as well as running the hooks.
- kana.el#L183: Quoting this lambda may prevent it from being compiled
- kana.el#L440: Quoting this lambda may prevent it from being compiled
- kana.el#L453: Quoting this lambda may prevent it from being compiled
- kana.el#L339: It's safer to sharp-quote function names; use `#'`
- kana.el#L347: It's safer to sharp-quote function names; use `#'`
- kana.el#L356: It's safer to sharp-quote function names; use `#'`
- kana.el#L25: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))
- kana.el#L421: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by riscy** [comment]
Feel free to ping when ready for another look.

**Comment by chenyanming** [comment]
Thanks for your patients! Sorry for the late reply. Appreciate that if you can help with a second check!

**Comment by riscy** [comment]
Looks good -- these are non-blockers but should probably be looked into:

- You should probably have an `;;;###autoload` cookie above your `define-derived-mode`
- There is a small warning on a clean compile -- `kana.el:175:29:Warning: assignment to free variable 'hl-line-face'` -- you can fix this with `(require 'hl-line)`

**Pull request merged**
