### PR TITLE
Add recipe for sfz-mode

### PR DESCRIPTION
**Pull request by jpcima**
### Brief summary of what the package does

This is a major mode for editing the SFZ sampled instrument format.

### Direct link to the package repository

https://github.com/sfztools/emacs-sfz-mode

### Your association with the package

I am the author of this package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Looks solid!  Quick run-through:

### sfz-mode.el

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
sfz-mode.el:90:53:Warning: reference to free variable `char'

In end of data:
sfz-mode.el:159:1:Warning: the following functions are not known to be
defined: seq-doseq, char, seq-some, seq-contains, seq-filter, seq-empty-p
```
All fixed with `(require 'seq)` I believe.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
No issues! 💯

Other static checks:
- sfz-mode.el#L107: It's safer to sharp-quote function names; use `#'`

I notice you're manually defining the major mode, but maybe `define-derived-mode` would be more appropriate, since then you could derive from `prog-mode` (this does look like a code mode), e.g. something like:
```elisp
(define-derived-mode sfz-mode prog-mode "SFZ"
  "Major mode for editing SFZ files.
\\{sfz-mode_map}"
  :group 'sfz
  :syntax-table sfz-mode-syntax-table
  (set (make-local-variable 'font-lock-defaults) '(sfz-font-lock-keywords))
  (set (make-local-variable 'indent-line-function) 'sfz-indent-line))
```

**Comment by jpcima** [comment]
Hi @riscy, thanks for review and help. I have updated the upstream as suggested.

- the function `identity` was sharp-quoted;
- the library `seq` was required;
- I have used `define-derived-mode`, and tested.

I run the same Emacs version, somewhat the warnings have escaped me on the first run of `byte-compile-file`.

(also I have assumed the sharp-quoting to not apply to `indent-line-function`, referring to GNU Emacs's own modes I find regular quoting as being common practice about this)

**Comment by riscy** [comment]
> (also I have assumed the sharp-quoting to not apply to indent-line-function, referring to GNU Emacs's own modes I find regular quoting as being common practice about this)

Yeah, `indent-line-function` is in fact a variable, and sharp-quoting is to indicate the names of functions.  Not every codebase will sharp-quote functions, especially a lot of legacy elisp, but it's a [good idea](https://endlessparentheses.com/get-in-the-habit-of-using-sharp-quote.html).

I notice you're distributing under the MIT license which is fine, but you don't write the words "MIT license" anywhere, which you should.  It may also be a good idea to add a LICENSE file to your repository (which GitHub can detect, thus giving your repo a little icon and enabling the API to return your license).

Another couple small nags:
- sfz-mode.el#L118: Single-line comments should (usually) begin with `;;`
- sfz-mode.el#L120: Single-line comments should (usually) begin with `;;`
- sfz-mode.el#L123: Single-line comments should (usually) begin with `;;`
- sfz-mode.el#L125: Single-line comments should (usually) begin with `;;`

Beyond those the code is looking good, so ping when ready!

**Comment by jpcima** [comment]
Hi @riscy, it's ready.
I've applied some changes as you have suggested in the review.
sfztools/emacs-sfz-mode@614506b

**Comment by riscy** [comment]
Apologies for getting so far behind on this.  This looks good to go!

Welcome to MELPA. :)

**Pull request merged**
