### PR TITLE
Add recipe for cwl-mode

### PR DESCRIPTION
**Pull request by tom-tan**
### Brief summary of what the package does

This is a major mode for editing [Common Workflow Language](http://www.commonwl.org).

### Direct link to the package repository

https://github.com/tom-tan/cwl-mode

### Your association with the package

I am a maintainer of the package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- [This line](https://github.com/tom-tan/cwl-mode/blob/a62e038fd7cb7c5a0ee3946e5ddae41af96fcc5e/cwl-mode.el#L84) doesn't do anything, I think.
- The flycheck portion is a bit odd and out of place. First of all, it requires that anyone who uses this major mode must have flycheck installed, which condition is generally not good practice. And secondly, flycheck is enabled by a confusingly-named function `cwl-mode-setup`, which then only enables other checkers. In this case I would probably remove [this line](https://github.com/tom-tan/cwl-mode/blob/a62e038fd7cb7c5a0ee3946e5ddae41af96fcc5e/cwl-mode.el#L92), drop `flycheck` from the `Package-Requires` list, and convert the setup function to an `eval-after-load 'flycheck` block.

**Comment by tom-tan** [comment]
Thank you for the feedback!

> - This line doesn't do anything, I think.

I removed it.

> In this case I would probably remove this line, drop flycheck from the Package-Requires list, and convert the setup function to an eval-after-load 'flycheck block.

I removed flycheck from Package-Requires and used `with-eval-after-load` instead of `cwl-mode-setup`.
I also updated the document for it.

**Comment by purcell** [comment]
Thanks. `with-eval-after-load` is only available in very recent Emacs versions: you should either use `eval-after-load` instead (and quote the contained form) or specific an Emacs version dependency in the `Package-Requires` header.

**Comment by purcell** [comment]
P.S. package-lint would have told you this. :-)

**Comment by tom-tan** [comment]
Thank you for your advice.

I added `(emacs "24.4")` for Package-Requires.

Also I installed flycheck-package and now I can sure my extension is automatically checked by package-lint. :)

**Comment by purcell** [comment]
Great, thanks.

**Comment by tom-tan** [comment]
Thanks!

**Pull request merged**
