### PR TITLE
Add recipe for exwm-modeline

### PR DESCRIPTION
**Pull request by SqrtMinusOne**
### Brief summary of what the package does

A modeline segment to display EXWM workspaces. Very much inspired by the similar functionality of perspective.el.

### Direct link to the package repository

https://github.com/SqrtMinusOne/exwm-modeline

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this!  Very quick first pass --

`exwm-modeline.el` with byte-compile using Emacs 27.1:
```
exwm-modeline.el:66:16:Warning: reference to free variable
    `exwm-modeline-mode'
```

`load`-check on each file:
```
Loading exwm-modeline.el
  exwm-modeline.el:Error: Emacs 27.1 couldn't load:
  (void-variable exwm-modeline-mode)
```
I think this is happening because the compiler hasn't encountered the declaration of the minor mode while it's parsing these `defcustoms`.  You could use `bound-and-true-p` but it seems odd for a variable to have a value dependent on a mode that definitely hasn't been loaded in yet.

**Comment by SqrtMinusOne** [comment]
Thanks, I've wrapped that with `bound-and-true-p`. My idea was that whenever `exwm-modeline-mode` is on, changing these variables in the customize buffer has to trigger `exwm-modeline-update`. Not sure what's the correct way to implement that, but it seems to work.

At any rate, [your script](https://github.com/riscy/melpazoid) seems to pass without errors now if I'm running it correctly.

**Comment by riscy** [comment]
I also seem to have overlooked that was a lambda above.  That's my mistake, sorry about that. :)  Looks good to merge!

**Comment by SqrtMinusOne** [comment]
Thank you!

**Comment by SqrtMinusOne** [comment]
Ouch, how did I miss that?

Thanks for noticing.

**Pull request merged**
