### PR TITLE
add scalariform

### PR DESCRIPTION
**Pull request by zwild**
### Brief summary of what the package does
Format your Scala code with scalariform in Emacs.

### Direct link to the package repository

https://github.com/zwild/scalariform

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]
I'm the author of this project.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
Please install your package using the MELPA sandbox and fix the errors that will occur.

**Comment by zwild** [comment]
Hi, I fix the doc warning by `package-lint', and the doc warning.
Thanks.

**Comment by zwild** [comment]
Hi, is there any problems? Thanks.

**Comment by alphapapa** [comment]
You still haven't tested the package in the MELPA sandbox.

**Comment by zwild** [comment]
screenshot

Hi, I run the command `EMACS_COMMAND=emacs make sandbox INSTALL=recipes/scalariform` and get the result above. I think the result is correct, right?
Thanks for your time.

**Comment by purcell** [comment]
This looks good to me now, and I'll go ahead and merge it, but I suggest that you can make this package more concise, idiomatic and robust by using my `reformatter` package: https://github.com/purcell/reformatter.el

**Pull request merged**
