### PR TITLE
Add recipe for imenu-extra

### PR DESCRIPTION
**Pull request by redguardtoo**
### Brief summary of what the package does

Add extra items into existing imenu items

### Direct link to the package repository

https://github.com/redguardtoo/imenu-extra

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
Quick suggestion: the package would be sorted with other `imenu`-related packages if it were named `imenu-extra`.

**Comment by redguardtoo** [comment]
@alphapapa , I'm not sure about sorting, maybe I've already sorted by item's position. I will double check, it's a good idea to sort all items.

It's a generic package. Not specific to lsp-mode or js2-mode. Could be used with any major or minor mode. I highlight lsp and js2 because they are very popular.

**Comment by alphapapa** [comment]
> I'm not sure about sorting, maybe I've already sorted by item's position. I will double check, it's a good idea to sort all items.

You misunderstand me.  I mean that, if the package were named, e.g. `imenu-extras`, it would be listed with other `imenu-` packages in `package-list-packages`.

**Comment by redguardtoo** [comment]
@alphapapa I updated name and description.

**Comment by riscy** [comment]
Thanks for this.  Just a friendly reminder to add a LICENSE file that GitHub can detect (e.g. no markup) if possible.

Minor:
- Add extra items into exiting -> existing

**Comment by redguardtoo** [comment]
@riscy , thanks. It's fixed.

**Pull request merged**
