### PR TITLE
Added a recipe of audacious.

### PR DESCRIPTION
**Pull request by shishimaru**
### Brief summary of what the package does

This package enables Emacs users to control the music player, Audacious, with the dedicated commands
such as selecting playlists and songs, controlling playback / stop / pause.
Optionally, it provides a function to select songs with helm interface.

### Direct link to the package repository

https://github.com/shishimaru/audacious.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

Please make issues on the github page https://github.com/shishimaru/audacious.el .

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, and apologies for how long it's taken to take a look.  Here's a quick (automated) pass over the checklist:

### audacious.el ###

byte-compile (using Emacs 27.1):
```
audacious.el:89:9:Warning: assignment to free variable `res'
audacious.el:93:34:Warning: reference to free variable `res'
audacious.el:94:25:Warning: assignment to free variable `num'
audacious.el:96:69:Warning: reference to free variable `num'
In helm-audacious-song-goto:
audacious.el:111:73:Warning: assignment to free variable `num'
audacious.el:111:25:Warning: reference to free variable `num'
In audacious-song-show-current-info:
audacious.el:140:36:Warning: assignment to free variable
    `current-playlist-position'
audacious.el:140:62:Warning: assignment to free variable
    `current-playlist-length'
audacious.el:140:86:Warning: assignment to free variable `current-song-title'
audacious.el:140:105:Warning: assignment to free variable
    `current-song-position'
audacious.el:140:127:Warning: assignment to free variable
    `current-song-length'
audacious.el:140:4:Warning: reference to free variable
    `current-playlist-position'
audacious.el:140:4:Warning: reference to free variable
    `current-playlist-length'
audacious.el:140:4:Warning: reference to free variable `current-song-title'
audacious.el:140:4:Warning: reference to free variable `current-song-position'
audacious.el:140:4:Warning: reference to free variable `current-song-length'
In audacious-playlist:
audacious.el:161:9:Warning: assignment to free variable `res'
audacious.el:165:17:Warning: reference to free variable `res'
In audacious-playlist-show-current-info:
audacious.el:173:71:Warning: assignment to free variable
    `current-playlist-name'
audacious.el:173:29:Warning: assignment to free variable
    `current-playlist-position'
audacious.el:173:55:Warning: assignment to free variable `playlist-length'
audacious.el:173:4:Warning: reference to free variable
    `current-playlist-position'
audacious.el:173:4:Warning: reference to free variable `playlist-length'
audacious.el:173:4:Warning: reference to free variable `current-playlist-name'
In audacious-playlist-goto:
audacious.el:186:60:Warning: assignment to free variable `playlist-length'
audacious.el:186:27:Warning: reference to free variable `playlist-length'
audacious.el:187:25:Warning: assignment to free variable `num'
audacious.el:189:76:Warning: reference to free variable `num'
In audacious-playlist-next:
audacious.el:206:79:Warning: assignment to free variable
    `current-playlist-name'
audacious.el:202:36:Warning: assignment to free variable
    `current-playlist-position'
audacious.el:203:36:Warning: assignment to free variable `playlist-length'
audacious.el:206:37:Warning: reference to free variable
    `current-playlist-position'
audacious.el:206:63:Warning: reference to free variable `playlist-length'
audacious.el:209:8:Warning: reference to free variable `current-playlist-name'
In audacious-playlist-prev:
audacious.el:221:76:Warning: assignment to free variable
    `current-playlist-name'
audacious.el:217:36:Warning: assignment to free variable
    `current-playlist-position'
audacious.el:221:60:Warning: assignment to free variable `playlist-length'
audacious.el:221:60:Warning: reference to free variable
    `current-playlist-position'
audacious.el:224:8:Warning: reference to free variable `playlist-length'
audacious.el:224:8:Warning: reference to free variable `current-playlist-name'
In end of data:
audacious.el:236:1:Warning: the following functions are not known to be
    defined: helm, helm-build-sync-source
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
audacious.el:227: All variables and subroutines might as well have a documentation string
Warning (emacs): 
audacious.el:230: All variables and subroutines might as well have a documentation string
```

package-lint (using version 20210528.2348):
```
5 issues found:
1:0: error: Package should have a Homepage or URL header.
101:0: error: "helm-audacious-song-goto" doesn't start with package's prefix "audacious".
110:21: error: You should depend on (emacs "24.4") if you need `string-trim'.
226:0: error: "delete-newline" doesn't start with package's prefix "audacious".
229:0: error: "string-integer-p" doesn't start with package's prefix "audacious".
```

And I see you have a license file which is great, but the file itself could benefit from:
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to audacious.el

**Comment by riscy** [comment]
I'll mark this awaiting upstream, but feel free to ping when ready.

**Comment by shishimaru** [comment]
Hi riscy,

Thank you so much for the review and feedback.
I have fixed all of warnings and errors of byte-compile, checkdoc, package-lint
and added the short version of the license description into the elisp file itself.

Could you review again ?

**Comment by shishimaru** [comment]
@riscy 
Should I take more action to proceed ?
Or just wait for the merging ?

**Comment by riscy** [comment]
I'll very likely be taking a look tomorrow -- sorry again for the long turnaround time.

**Comment by shishimaru** [comment]
@riscy Got it !

**Comment by riscy** [comment]
Taking a closer look at the code now and I have a couple lower-level suggestions:

- The function `audacious-delete-newline` seems unnecessary, why not just use the builtin `string-trim`?
- There's a lot of (long) repeated forms throughout the code that call `audtool`.  For example I see `(setq audacious-playlist-position ...)` repeated in several places, but sometimes the value computed is wrapped in `string-to-number`.  I'd recommend hiving this repeated stuff off into a helper function and being consistent about the variable types.  Ultimately not a blocker, especially for a first-time package
- In the contexts you're calling `audacious-string-integer-p` it strikes me that you probably (?) want a _positive_ integer, not just any integer.  I'm assuming these are absolute positions/song numbers
- I'd suggest using `progn` under `if`s as a last resort.  Instead, Invert the conditional and the progn won't be needed, e.g. `(if (< next-playlist-position 1) (user-error "First playlist") <all your other forms>)`.  This has the nice side effect of getting the simpler (negative) cases out of the way
- Minor but note concat takes multiple arguments (e.g. in `audacious-song-goto`)  -- you can write `(concat x y z)` instead of `(concat x (concat y z))`

None of these block, though.  Welcome to MELPA. :)

**Comment by shishimaru** [comment]
@riscy 
Thank you for providing the feedback for the codes.

If I would like to update and release later, what procedure should I follow ?
If I have updated my GitHub project https://github.com/shishimaru/audacious.el, is the newer one automatically available in public ?

On the melpa page https://melpa.org/#/audacious, the URL of the button **source code** refers to a specific commit and the newer codes couldn't be released in public even if I update my GitHub project.

**Comment by riscy** [comment]
> If I have updated my GitHub project https://github.com/shishimaru/audacious.el, is the newer one automatically available in public ?

That's right, you won't have to do anything special.  On the top-right of melpa.org you can see when the most recent build ran.

**Comment by shishimaru** [comment]
@riscy 

> > If I have updated my GitHub project https://github.com/shishimaru/audacious.el, is the newer one automatically available in public ?
> 
> That's right, you won't have to do anything special. On the top-right of melpa.org you can see when the most recent build ran.

Got it ! Thank you for the advice !

**Pull request merged**
