### PR TITLE
rename old recipe from goldendict to external-dict

### PR DESCRIPTION
**Pull request by stardiviner**
### Brief summary of what the package does

Expand external dictionaries to more scope and more system.

### Direct link to the package repository

https://repo.or.cz/external-dict.el.git

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks -- merging now, but just a couple of quick comments to keep this up to date:

- Add *formal* license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to external-dict.el

`external-dict.el` with byte-compile using Emacs 28.1:
```
external-dict.el:83:6: Warning: the function `ns-do-applescript' is not known
    to be defined.
```
This will only be seen by people running on Emacs without this function, but you can pacify it with `declare-function`.

**Comment by stardiviner** [comment]
> `external-dict.el` with byte-compile using Emacs 28.1:
> 
> ```
> external-dict.el:83:6: Warning: the function `ns-do-applescript' is not known
>     to be defined.
> ```
> 
> This will only be seen by people running on Emacs without this function, but you can pacify it with `declare-function`.

The function `ns-do-applescript` is from macOS version Emacs. I have not noticed that, thanks for pointing it out.
This function is not from a specific elisp source code file, it's from C source code. So can't use `declare-function`.
Maybe need use another way?

> * Add _formal_ license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to external-dict.el

I added a comment line to `external-dict.el`, is this correct?
```
;; SPDX-License-Identifier: GPL-2.0-or-later
```

**Comment by riscy** [comment]
> Is this correct?

Yep, that's right.

>  Maybe need use another way?

Something like `(declare-function ns-do-applescript "file.c" t)` *should* work to quite the byte-compiler.

**Comment by stardiviner** [comment]
Ok, I pushed updates to remote repository. Thanks for helping.

**Pull request merged**
