### PR TITLE
Added recipe for butter-jump

### PR DESCRIPTION
**Pull request by viocost**
### Brief summary of what the package does

The package provides 2 functions for smoother eye pleasant half page jumps

### Direct link to the package repository

https://github.com/viocost/butter-jump

### Your association with the package

Author, Maintainer 

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

```
 kostia@kostia-cs  ~/projects/melpa   master  make recipes/butter-jump
 • Building package butter-jump ...
Package: butter-jump
Fetcher: github
Source:  https://github.com/viocost/butter-jump.git

Cloning https://github.com/viocost/butter-jump.git to /home/kostia/projects/melpa/working/butter-jump/
Checking out 0135861454f1d5d97d7112fa2b24569a3c100f2d
Built butter-jump in 1.548s, finished at 2023-01-05T12:03:06+0000
 ✓ Success:
4.0K -rw-r--r-- 1 kostia kostia 4.0K Jan  5 14:03 packages/butter-jump-20230104.2128.el
4.0K -rw-r--r-- 1 kostia kostia  381 Jan  5 14:03 packages/butter-jump-20230104.2128.entry

```

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

- Add a LICENSE file to the repository
- Your package `;;; Commentary` seems to need to be consolidated (there is an unnecessary "description" section and one sentence seems to terminate before it's complete: "You may also customize the jump distance by editing")
- Minor: the "else" part of an `if` as in `butter-jump-perform-jump-move` does not need to be wrapped in a `progn`
- Minor: `(if (not x) (progn ...)` as in `butter-jump-perform-smooth-jump` can be rewritten as `(unless x ...)`
- Minor documentation typos: deirectly, pleasent, signle

**Comment by viocost** [comment]
@riscy thanks for the review and the comment! All fixed

**Comment by riscy** [comment]
Looks good, thank you!  I appreciate the video on your repository to demonstrate how this works.  Just to make sure there's no duplication of functionality, have you had a chance to compare to some other packages in this same area?  E.g.:

- https://melpa.org/#/scroll-on-jump
- https://melpa.org/#/good-scroll

**Comment by viocost** [comment]
@riscy, I tried searching several times for something like that, I tried both, good scroll produces different results and relies on pixel scrolling, so intention may be the same, but realization and results are different. As for scroll-on-jump, sorry, I could not make it to work.

**Comment by riscy** [comment]
@ideasman42, I hope you don't mind me summoning you to this discussion. :)

@viocost, I think your reasoning re: `good-scroll` is sound and I'd definitely accept that argument.  However, if some aspect of your setup (or the package itself) is preventing `scroll-on-jump` from working, but the functionality is potentially overlapping, it will be a better result for all MELPA users if the issue can be resolved through discussion here.

**Comment by riscy** [comment]
BTW, @viocost -- for the sake of @idesman42, maybe you can explain further what you mean by ""I could not make it work"; was there an error that you can paste?  Or an expected behavior that didn't occur?

**Comment by ideasman42** [comment]
Note that from what I can tell, scroll-on-jump can perform the same functionality as butter-jump. 

For example:
```
(global-set-key (kbd "<next>") (lambda () (interactive) (scroll-on-jump (forward-line 45))))
(global-set-key (kbd "<prior>") (lambda () (interactive) (scroll-on-jump (forward-line -45))))
```

Some notes: 
- This could be made less verbose/more convenient. e.g.

  `(global-set-key (kbd "<next>") (scroll-on-jump-interactive-lambda (forward-line 45)))`

- If there are any important differences in functionality, (details of scrolling behavior for e.g.) I think they could be included as changes/options to scroll-on-jump.

**Comment by ideasman42** [comment]
> @riscy, I tried searching several times for something like that, I tried both, good scroll produces different results and relies on pixel scrolling, so intention may be the same, but realization and results are different. As for scroll-on-jump, sorry, I could not make it to work.

Disable smooth scrolling for line based scrolling:
`(setq scroll-on-jump-smooth nil)`

**Comment by viocost** [comment]
@riscy @ideasman42 , I was able to make scroll-on-jump work, it was a bit trickier to set it up with Doom Emacs and its key macros. I agree, the functionality is overlapping, although scrolling looks a bit different, in butter-jump thanks to logarithmic function, the scrolling looks smoother, less jittery, but I guess this could be an improvement for scroll-on-jump. 

Anyway, feel free to merge or close it. And thanks for the comments.

**Comment by ideasman42** [comment]
@viocost can you show how the keys needed to be bound with doom-emacs? (this would give a hint for how the simplify things). It may be that `scroll-on-jump` necessarily needs to be a little more technical (since it can control any action).

Changing the scrolling curve is fairly simple and am happy to make this optional (a way to select the scroll curve linear/smooth/log... currently there is only linear and ease-in-out).

**Comment by ideasman42** [comment]
> in butter-jump thanks to logarithmic function, the scrolling looks smoother, less jittery

@viocost worked around jittery scrolling, let me know if this now works well for you.

https://codeberg.org/ideasman42/emacs-scroll-on-jump/commit/7b4d7966275bdf8587c62ae9c203dfa068677d2c

**Comment by riscy** [comment]
Friendly ping, @viocost :)

**Comment by viocost** [comment]
Sorry, been a bit swamped. 

@ideasman42 , so indoom emacs there is map! macro to define key bindings, and it looks like this:
```lisp
(map! (:map override
        :ni  "C-d" #'butter-jump-down
        :ni  "C-u" #'butter-jump-up
        :i  "C-f" #'right-char
        :i  "C-b" #'left-char
        ...
       ))
```

I could not directly apply scroll-on-jump inside this macro, so I've ended up defining an interactive function with scroll-on-jump:

```lisp
(defun soft-jump-up()
    (interactive)
  (scroll-on-jump (forward-line -30)))
```

Then, I used this function inside Doom Emacs macro. Probably there is another way.

As for functionality, I think we can close my PR, since it 100% overlaps with scroll-on-jump

**Comment by ideasman42** [comment]
@viocost `butter-jump-up ` / `butter-jump-down`  called `forward-line` with an argument, it's going to be a little more involved to use `scroll-on-jump` to wrap a command that is called with an argument.

This would be the case if you wanted to call `(forward-line -30)` without smooth scrolling too, so I don't think it's fair to fault `scroll-on-jump` for this.

Typically you can in-line the lambda to avoid a function call if you want to.

```
(map! (:map override
        :ni  "C-d" (lambda () (interactive) (scroll-on-jump (forward-line -30)))
        ...
       ))
```
OTOH, defining an interactive function gives nicer feedback in the UI (which-key ... etc).

**Pull request closed without merging**
