### PR TITLE
Add recipe for liquidmetal

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Quicksilver scoring algorithm, essentially LiquidMetal

### Direct link to the package repository

https://github.com/jcs-elpa/liquidmetal

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- checklist looks great.  A couple quick comments:

- Your summary line "Quicksilver scoring algorithm, essentially LiquidMetal" is a bit vague and might make it hard for people to find this if they're looking for fuzzy string matching algorithms
- Does https://melpa.org/#/fuzzy already implement this?
- If you based your implementation on https://github.com/rmm5t/liquidmetal it might be fair to give those authors a nod or a link in your Commentary
- As always, I think it would also be useful to expand the `;;; Commentary` to give some more context (rather than just copy-pasting the summary line).  E.g., this is a string similarity scoring algorithm, the function `liquidmetal-score` is the public interface, etc.

And one more thing: I noticed this is already on the mirror somehow -- https://github.com/emacsmirror/liquidmetal -- that surprised me; do you know how that happened?

**Comment by riscy** [comment]
Maybe that's a better question for @tarsius -- I'm wondering if there's some automatic script that hoovers up Elisp repos into the emacsmirror.

**Comment by tarsius** [comment]
I usually don't go hunting for new packages anymore and just add what is being added to melpa. Occasionally I do add a package that I see mentioned somewhere else, which is probably what has happened here.

**Comment by jcs090218** [comment]
> * Your summary line "Quicksilver scoring algorithm, essentially LiquidMetal" is a bit vague and might make it hard for people to find this if they're looking for fuzzy string matching algorithms

Yeah, I agree with you. I guess I just copied the description from the original repository since I think a group of people do know this tool pretty well since it has 2xx stars? 😕 

> * Does https://melpa.org/#/fuzzy already implement this?

I think there are significant differences by seeing https://github.com/rmm5t/liquidmetal#why.

> * If you based your implementation on https://github.com/rmm5t/liquidmetal it might be fair to give those authors a nod or a link in your Commentary

I had it on my readme file but I would also revise the commentary section.

**Comment by riscy** [comment]
> Yeah, I agree with you. I guess I just copied the description from the original repository since I think a group of people do know this tool pretty well since it has 2xx stars? 😕

I see what you mean, but I think a lot of Emacsers will not necessarily be familiar with a javascript package with 300 stars.  Moreover, you only copied part of the description and left out the "a mimetic poly-alloy of" part, which actually changes the semantics of the sentence.  I realize there's not a lot of space in the summary line, but I'd just write "LiquidMetal similarity scoring algorithm" or similar.

**Comment by riscy** [comment]
Here's another suggested summary line if you want to keep the joke intact: "A mimetic poly-alloy of the Quicksilver scoring algorithm".

**Comment by jcs090218** [comment]
Okay, I have changed the line. Sorry, I am having trouble reading the summary "A mimetic poly-alloy of the Quicksilver scoring algorithm", so I preferred leave it intact. 😓

**Pull request merged**
