### PR TITLE
Add recipe for kubedoc

### PR DESCRIPTION
**Pull request by r0bobo**
### Brief summary of what the package does

kubedoc.el provides Kubernetes API documentation in Emacs.

### Direct link to the package repository

https://github.com/r0bobo/kubedoc.el/

### Your association with the package

I am the maintainer,

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks, looks useful.  Checklist looks great, but here a few suggestions:

- If the k8s cluster can't be reached, `kubectl api-resources` will fail but `kubedoc--resource-completion-table` will turn the error message into a list of resources.  I'd recommend using `call-process-shell-command` and doing something like this:
```elisp
(with-temp-buffer
  (let* ((returncode
          (call-process-shell-command
           "kubectl api-resources --cached --output name" nil t))
         (output (buffer-substring (point-min) (point-max))))
    (if (zerop returncode)
        (split-string output)
      (user-error (string-trim output)))))
```
- The variable names in docstrings typically aren't surrounded by parentheses -- just capitalizing them is the community style, and the Emacs online help knows to look for the capitalized words.
- The front/back quoting style (``` `like this' ```) is normally used to create links between help documents, rather than a form of markup (e.g. where you write ``` `pods/spec/containers' ```)

**Comment by r0bobo** [comment]
> Thanks, looks useful. Checklist looks great, but here a few suggestions:
> 
>     * If the k8s cluster can't be reached, `kubectl api-resources` will fail but `kubedoc--resource-completion-table` will turn the error message into a list of resources.  I'd recommend using `call-process-shell-command` and doing something like this:
> 
> 
> ```emacs-lisp
> (with-temp-buffer
>   (let* ((returncode
>           (call-process-shell-command
>            "kubectl api-resources --cached --output name" nil t))
>          (output (buffer-substring (point-min) (point-max))))
>     (if (zerop returncode)
>         (split-string output)
>       (user-error (string-trim output)))))
> ```
> 
>     * The variable names in docstrings typically aren't surrounded by parentheses -- just capitalizing them is the community style, and the Emacs online help knows to look for the capitalized words.
> 
>     * The front/back quoting style (`` `like this' ``) is normally used to create links between help documents, rather than a form of markup (e.g. where you write `` `pods/spec/containers' ``)

Thanks for the feedback!

I have fixed these issues here https://github.com/r0bobo/kubedoc.el/compare/262eee862293f75b8c140bb88e679211ce979789...d256526f6ea1517f0eabd330d6ff20a4d3d5db58

**Comment by riscy** [comment]
Looks great, thanks.  And, welcome to MELPA! :)

**Comment by r0bobo** [comment]
Awesome! Thanks :D

**Pull request merged**
