### PR TITLE
Add recipe for company-fuzzy.

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Fuzzy matching for `company-mode'

### Direct link to the package repository

https://github.com/jcs090218/company-fuzzy

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
No issues found.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
company-fuzzy.el:203:1:Warning: the function `flx-score' is not known to be
    defined.
```

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
No issues! 🎉

**Comment by jcs090218** [comment]
`flx-score` is from package `flx`, and is an option package for `company-fuzzy`. So I didn't included as a dependency. Just to let you know! :D

**Comment by riscy** [comment]
Ah I gotcha. You should be able to mute the compiler warning with a `declare-function` -- something like:
```elisp
(declare-function flx-score "ext:flx.el")
```

**Comment by jcs090218** [comment]
Nice, one more trick learned! Warning should be fixed for now! :D

**Comment by riscy** [comment]
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
company-fuzzy.el:170:7:Warning: reference to free variable
    `company-fuzzy-mode'
```
You can fix this warning by defining the mode before (above) referencing the variable.

**Comment by jcs090218** [comment]
Fixed! :D

**Comment by purcell** [comment]
Looks good, thanks - merged!

**Pull request merged**
