### PR TITLE
Add math-preview package

### PR DESCRIPTION
**Pull request by matsievskiysv**
### Brief summary of what the package does

Preview math equations inline using MathJax

Demo:

#### Comparison with the existing packages

*Package with similar functionality*: [latex-math-preview](https://gitlab.com/latex-math-preview/latex-math-preview)

*How is math-preview different*: `latex-math-preview` actually use latex engines to produce output. `math-preview` uses MathJax. 
This has several advantages:
- MathJax conversion is faster
- MathJax output is in vector SVG format, so there's no image scale issues
- No Unicode issues

#### Test input

You may use the following input to test the package:
```latex
\[ f(n) =
  \begin{cases}
    n/2       & \quad \text{if } n \text{ is even}\\
    -(n+1)/2  & \quad \text{if } n \text{ is odd}
  \end{cases}
\]

$$\color{gray}\oint_{\color{purple}0}^{\color{green}1}{{\color{red}x}^{\color{yellow}2}}$$

\(\require{\mhchem} \require{enclose} \enclose{circle}{\ce{H2O}}\)

$\oint_0^\infty{\left(x^2 + y_z\right)dS}$
```

The output should look like this (picture from the sandbox):

### Direct link to the package repository

https://gitlab.com/matsievskiysv/math-preview

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

*None needed*

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass.

### math-preview.el ###

byte-compile (using Emacs 27.1):
```
math-preview.el:158:1:Warning: Unused lexical argument `process'
math-preview.el:282:1:Warning: Unused lexical argument `string'
In math-preview--svg-size:
math-preview.el:285:60:Warning: reference to free variable `image'
In end of data:
math-preview.el:417:1:Warning: the function `crd' is not known to be defined.
```
Intentionally unused lexical arguments can be fixed by prefixing them as e.g. `_process`.

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- math-preview.el#L74: There is no need to quote lambdas (neither #' nor ')
- math-preview.el#L82: There is no need to quote lambdas (neither #' nor ')
- math-preview.el#L92: There is no need to quote lambdas (neither #' nor ')
- math-preview.el#L99: There is no need to quote lambdas (neither #' nor ')
- math-preview.el#L106: There is no need to quote lambdas (neither #' nor ')
- math-preview.el#L350: Top-level `define-key` can overwrite existing user bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`

**Comment by matsievskiysv** [comment]
Fixed most warnings, except for `Top-level define-key can overwrite existing user bindings. Try: (defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`.
This command redefines keybindings only for the image overlay, so I think it's fine.

**Comment by matsievskiysv** [comment]
FYI, added a new feature since the last comment.

**Comment by cpitclaudel** [comment]
Any chance to include this in AucTeX instead of having it as a separate package?

> MathJax output is in vector SVG format, so there's no image scale issues

But latex's output is in DVI format, which is scalable as well, isn't it?

**Comment by matsievskiysv** [comment]
> Any chance to include this in AucTeX

This package has nothing to do with AuxTeX. It doesn't use latex engines and can operate on any buffers. Additionally, it requires external `nodejs` program to work.

**Comment by cpitclaudel** [comment]
> This package has nothing to do with AuxTeX.

AucTeX already includes a feature to render equations in the current buffer (`preview-latex`).  It would be nice if the same menus, bindings, etc. could be used with this package instead of having a completely different set of commands.

**Comment by matsievskiysv** [comment]
But some other packages like [markdown-mode](https://melpa.org/#/markdown-mode) or [ein](https://melpa.org/#/ein) might also make use of this package. It's not very practical to add whole AucTeX as a dependency just for one feature.
I think that it's best to make this a standalone package. Other packages may detect it and use an equation preview backend, locally reconfiguring it and adding required key bindings.

**Comment by riscy** [comment]
I can see @matsievskiysv's point -- maybe there's room for an auctex-mathjax package that defines a minor mode that uses the mathjax backend?

> This command redefines keybindings only for the image overlay, so I think it's fine.

It probably is, but if a user does things in the wrong order (customizes this keymap somehow and _then_ loads or reloads your package) then there bindings will inexplicably change.  A `defvar` prevents this from happening:
```el
(defvar math-preview-map
  (let ((keymap (make-sparse-keymap)))
    (define-key keymap (kbd "<C-delete>") #'math-preview-clear-all)
    ...
    keymap)
  ""Key map for math-preview image overlays.")
```

**Comment by matsievskiysv** [comment]
@riscy moved `define-key` to `defvar`

**Comment by riscy** [comment]
Thank you for accommodating. :)

**Pull request merged**
