### PR TITLE
Add recipe for `simple-indention`

### PR DESCRIPTION
**Pull request by semenInRussia**
### Brief summary of what the package does
This package makes writing indentation functions for major modes very easy as piece of cake! 

### Direct link to the package repository
https://github.com/semenInRussia/simple-indention.el/

### Your association with the package

I am maintainer and contributor

### Relevant communications with the upstream package maintainer

Not needed

### Checklist
- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I am add cool stuff [melpazoid](https://github.com/riscy/melpazoid) to CI of my project

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- looks useful.  I like the seventh checklist item. :P   Quick pass --

- It's hard for me to tell exactly what this package does across all six source files -- for example it's unclear what users are supposed to do with functions like `simple-indention-just-compose-with-prev-line`; that's not entirely a blocker but it struck me that the package could improve from a bit more polish/trimming-down
- I think package-lint is rightly complaining about the non-standard symbols in the function/method names (i.e. the colons)
- Regarding the summary line/`;;; Commentary` I would avoid embellishments like "cool", just because all of these words end up being keywords during the search (imagine there was a programming language called "cool" for example).  I might revise to something like `Simplify writing major-mode indentation functions`

**Comment by semenInRussia** [comment]
Thanks! I corrected notes 2 and 3 but I'm not sure if I understood what to correct in the first note, just rename `just` to something other?

**Comment by semenInRussia** [comment]
I merged `functools` and `just` to one file  `utils`, I am think that, less files = clear project

**Comment by riscy** [comment]
Thanks so much for accommodating -- I think that consolidation helps a lot, and this really seems like a useful package (I have reviewed major mode submissions where the indentation functions were absent because they would've been difficult for the author to implement, so this package is something I can point them to to help!)

With regard to the third point, I would still recommend adjusting the summary line (first line of simple-indentation.el) to something plainer like in my example.  That's not strictly a blocker though.

In any case this is very close to an easy merge, but I'll just leave a couple very minor issues here and hope you consider the summary line in the meantime:

`simple-indention-namespace.el` with byte-compile using Emacs 27.1:
```
simple-indention-namespace.el:93:1:Warning: the function `s-concat' is not
    known to be defined.
```
(This just needs a `require 's` in that file)

`simple-indention-rules.el` with checkdoc 0.6.2:
```
simple-indention-rules.el:372: Some lines are over 80 columns wide
```
Also very (!) minor since this includes a longish variable name, but I think your comment lines are overindented compared to the Elisp standard of two spaces which would incidentally fix this.

**Comment by semenInRussia** [comment]
All fixed again

**Comment by purcell** [comment]
Presumably the package name should be fixed by renaming it to `simple-indentation`?

**Comment by riscy** [comment]
I think everything looks good to merge here - a couple more quick comments, non-blocking:

- The word "indention" appears in multiple places even though the package name is "indentation" now, e.g. `clear-old-indention`
- In docstrings, there's no need to backquote the docstrings by convention, e.g. ```"Increment indent level on `N`, defaults to 1."``` is conventionally just written as ```"Increment indent level on N, defaults to 1."```

**Pull request merged**
