### PR TITLE
add lsp-jedi recipe

### PR DESCRIPTION
**Pull request by fredcamps**
### Brief summary of what the package does
A client for Python Jedi Language Server, using lsp-mode api

### Direct link to the package repository

https://github.com/fredcamps/lsp-jedi

### Your association with the package

I am the maintainer of this package

### Relevant communications with the upstream package maintainer

 **None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass, but I recommend you read and check each item on the checklist (hint: one of them isn't supposed to be checked ;) )

### lsp-jedi.el ###

byte-compile-file (using Emacs 26.3):
```
lsp-jedi.el:26:1:Error: Cannot open load file: No such file or directory, lsp-mode
```
This is due to a missing `Package-Requires` line (see package-lint below)

checkdoc (using version 0.6.1):
- No issues!

package-lint-current-buffer (using version 20200419.406):
```
6 issues found:
1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: Package should have a Homepage or URL header.
1:0: warning: The package summary should start with an uppercase letter or a digit.
1:57: warning: You should depend on (emacs "24") if you need lexical-binding.
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
89:0: error: "lsp-clients-python-library-directories" doesn't start with package's prefix "lsp-jedi".
```


### Loadability ###

Running #'load on each file:
```
Loading lsp-jedi.el
lsp-jedi.el:Error: Emacs errored during load
Done.
```

### Package ###

- Prefer the default recipe if possible
  - It is in fact equivalent: `(lsp-jedi :repo "fredcamps/lsp-jedi" :fetcher github)`

**Comment by fredcamps** [comment]
@riscy sorry I forgot to commit my last changes, you're right... but all issues that you mentioned are fixed right now...
I ran the package lint and no issues are found,
I ran the byte-compile function and it works.

**Comment by riscy** [comment]
Great.  Taking a deeper look now.

Your package summary line and `Commentary` both just read "Jedi configuration".  You could improve discoverability on the MELPA package index by including the word "Python" somewhere in your summary, e.g.

`--- LSP client plugin for Python Jedi Language Server`

and your Commentary could be expanded to include some of the small detail from your README, e.g.,

> A Emacs client for Python Jedi Language Server (LSP client plugin for lsp-mode Emacs extension).

because the Commentary will be used to populate the details in your package's entry in the MELPA index.

You should have a second look at your `defcustom` lines.  For example in one case you define `:type 'bolean` (should be `boolean`) and in the case of `lsp-jedi-executable-command` you type something that appears to be a string as a boolean.

Those are minor and I see nothing else, so ping when ready and this should be an easy merge.

A couple other suggestions:
- `non nill` -> `non-nil` (at least a couple places)

**Comment by fredcamps** [comment]
Thanks @riscy, all requested changes have been done.

**Pull request merged**
