### PR TITLE
Add recipe for quick-shell-keybind

### PR DESCRIPTION
**Pull request by eyeinsky**
### Brief summary of what the package does

Interactively make a keybinding to run a sequence of commands in a
shell buffer.

### Direct link to the package repository

<https://github.com/eyeinsky/quick-shell-keybind>

### Your association with the package

I'm the author.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with x:

-   [x] The package is released under a GPL-Compatible Free Software License.
-   [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
-   [X] I've used the latest version of package-lint to check for packaging issues, and addressed its feedback
-   [X] My elisp byte-compiles cleanly (needed to add group to defcustom)
-   [X] M-x checkdoc is happy with my docstrings
-   [X] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Looks good. Quick feedback:
- Don't just add extra custom vars into the `'comint` group: make your own group with `defgroup`, and place it in an appropriate parent group (which probably isn't comint, to be honest).
- Add named args to `quick-shell-keybind` and use `interactive` to call `read-key-sequence` etc. for you. This is more idiomatic, makes the function usable programmatically, and will eliminate some boilerplate.
- You should add an `;;;###autoload` for that command too.

**Comment by eyeinsky** [comment]
I've now pushed the fixes: https://github.com/eyeinsky/quick-shell-keybind/commit/86a19f09262c1b442f783680d2dc947c9bdfd3cf, https://github.com/eyeinsky/quick-shell-keybind/commit/7a68c44fa4a4c1aade0da0fb1a726f7ccf52f5d7, https://github.com/eyeinsky/quick-shell-keybind/commit/5a5b0750eacaac8e82e3855c66d20bf2a38645e5.

Let me know if something could be better still! I.e I couldn't find a way to use interactive code for the key, since the other two arguments need lisp expressions to get them. Also, not sure if `tools` is a good parent group.

I will also squash the fixups when they are good enough!

**Comment by purcell** [comment]
Looks good to me! :-) Merged.

**Comment by purcell** [comment]
(Also: welcome to MELPA!)

**Comment by eyeinsky** [comment]
@purcell Just one more question: from now on if I would like to have code review then it's up to me to find a volunteer? (Since I'm quite new to elisp then even the current pull request taught me a lot by prompting me to read up on what `interactive` actually does and how it works together with the function arguments.)

**Comment by purcell** [comment]
Yeah, you'd have to find a volunteer, sorry, but if you want to @ me on your own commits or PRs then I'll look if I have time. I hear that the Emacs IRC channel is helpful too, and the Emacs subreddit is pretty active.

**Comment by eyeinsky** [comment]
Got it!

**Pull request merged**
