### PR TITLE
Add recipe for humanoid-themes package

### PR DESCRIPTION
**Pull request by tasmo**
### Brief summary of what the package does

A color theme made for coding and working with a dark and a light version.
It works well with true color as well as in a 256 color terminal.

### Direct link to the package repository

https://github.com/humanoid-colors/emacs-humanoid-themes
https://gitlab.com/tasmo/emacs-humanoid-themes

### Your association with the package

I'm the author and the maintainer of the package.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Hi, these look nice.  Some quick thoughts on this:

- Including humanoid-theme-pkg.el is discouraged -- MELPA will create a `-pkg.el` file
- You `provide humanoid-common` in your main file, but most (all?) of your definitions don't use that as a prefix -- they use `humanoid-theme` instead.   Best to choose one.

Some other relevant nags:
<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
1:0: warning: The package summary should not end with a period.
94:0: error: "true-color-p" doesn't start with package's prefix "humanoid-common".
100:0: error: "create-humanoid-theme" doesn't start with package's prefix "humanoid-common".
```

**Comment by tasmo** [comment]
Hi @riscy,
thank you for these very useful hints.
I tried to implement all the mentioned issues.

Afterwards I did `M-x package-lint-current-buffer` again and got just the Emacs version error comments on removed and added features which this theme colorizes as well.

**Comment by riscy** [comment]
Thanks for the patience on this!

These are fyi, but these aren't blockers:
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
(contains `no-byte-compile: t` but checking anyway)
```
humanoid.el:99:1:Warning: Unused lexical variable `head5-bg'
humanoid.el:99:1:Warning: Unused lexical variable `act1'
```

The last thing I notice is that your package is called `humanoid-theme`, but it strikes me that it should be `humanoid-themes` in the plural i.e. [here](
https://github.com/melpa/melpa/pull/6536/files#diff-45233a9eec99b717bdba6213a88d6da5R1).  (I realize I said "humanoid-theme" up above, but the file/package is not itself a single theme.  Apologies for that one.  I'm always a bit rusty when it comes to color themes.)

Similarly, your main file is `humanoid.el`, but now that we're without a `-pkg.el` file we want its name to line up with the name of the package (i.e. `humanoid-themes.el`).

With those names changed we're good to go, so please ping me when ready!

**Comment by tasmo** [comment]
@riscy Just want to ask kindly, if you got the upstream info.

**Comment by riscy** [comment]
Thanks so much for your patience.  I didn't catch the upstream info. :)

Humanoid looks ready to go 🤖 --I'll mention this last thing as a non-blocker so we can get this merged: you're still defining `head5-bg` but not using it.  Maybe you're keeping that for future.

And, welcome to MELPA!

**Pull request merged**
