### PR TITLE
Add recipe for docstr.

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

A document string minor mode.

### Direct link to the package repository

https://github.com/jcs-elpa/docstr

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
The demos in the readme are very helpful, but I can't help but wonder if this use case could be fulfilled by existing packages, like yasnippet.  Could you explain why it can't be?

**Comment by jcs090218** [comment]
> The demos in the readme are very helpful, but I can't help but wonder if this use case could be fulfilled by existing packages, like yasnippet. Could you explain why it can't be?

True. This could be multiple and various of reasons that cause me not to use yasnippet. Following points are something pop out from my mind.

1. `yasnippet` is kind of huge when it first loaded.
2. I don't like how `yasnippet` is implemented; I prefer not to edit external snippet files.
3. I don't want to include `yasnippet` as package dependency.
4. From my personal point of view, I think snippet is snippet and document string is document string. They are kind of similar but different.
5. I don't like to "expand" for document string. I like trigger it by key because it gives me IDE like kind of feeling. (I think you can do it with yasnippet but I guess this isn't necessary and the implementation may be not direct in this case)

**Comment by riscy** [comment]
Quick first pass here.  I think you could easily drop the dependency on `(s-` since you're only using the `s-replace-` functions, which just wrap `replace-regexp-in-string`.  Most of the byte-compilation warnings below are due to splitting this package  into multiple files without a dependency graph in mind.  An easy fix would be to just use one file.

### docstr-faces.el ###

byte-compile with Emacs 27.1:
```
docstr-faces.el:63:1:Warning: the function `docstr-major-modes' is not known
    to be defined.
```

checkdoc 0.6.2:
- No issues!

package-lint 20200906.512:
- No issues!


### docstr-util.el ###

byte-compile with Emacs 27.1:
- No issues!

checkdoc 0.6.2:
- No issues!

package-lint 20200906.512:
- No issues!


### docstr-writers.el ###

byte-compile with Emacs 27.1:
```
docstr-writers.el:205:34:Warning: reference to free variable
    `docstr-default-typename'
In docstr-writers--insert-param:
docstr-writers.el:245:45:Warning: reference to free variable
    `docstr-desc-param'
In docstr-writers--insert-return:
docstr-writers.el:259:52:Warning: reference to free variable
    `docstr-desc-return'
docstr-writers.el:297:1:Warning: Unused lexical variable
    `docstr-format-return'
docstr-writers.el:297:1:Warning: Unused lexical variable `docstr-format-param'
docstr-writers.el:297:1:Warning: Unused lexical variable `docstr-format-var'
In end of data:
docstr-writers.el:461:1:Warning: the following functions are not known to be
    defined: docstr-form-param, docstr-form-return
```

checkdoc 0.6.2:
- No issues!

package-lint 20200906.512:
- No issues!

**Comment by jcs090218** [comment]
> Quick first pass here. I think you could easily drop the dependency on (s- since you're only using the s-replace- functions, which just wrap replace-regexp-in-string.

Would it be fine if I just use `s-replace` function? I like it because it is much shorter name.

>  Most of the byte-compilation warnings below are due to splitting this package into multiple files without a dependency graph in mind. An easy fix would be to just use one file.

```
docstr-writers.el:297:1:Warning: Unused lexical variable
    `docstr-format-return'
docstr-writers.el:297:1:Warning: Unused lexical variable `docstr-format-param'
docstr-writers.el:297:1:Warning: Unused lexical variable `docstr-format-var'
```

I am overwriting these value temporary. Other issues are fixed.

**Comment by riscy** [comment]
> Would it be fine if I just use s-replace function? I like it because it is much shorter name.

Yes, that's fine. :)

> I am overwriting these value temporary. Other issues are fixed.

My byte-compile matches yours, so we're on the same page.  You can fix those by forward-declaring the variables earlier in the file with e.g. `(defvar docstr-format-return)`.

One last thought -- I'm most familiar with Python these days, and I know there are several conventions for docstrings in common use -- pep256, numpy, google; search for "convention" in [this document](http://www.pydocstyle.org/en/stable/usage.html) for more.   I'd suggest you mention which convention you're following for Python, and verify that your convention lints happily against pydocstyle.  I guess there are conventions around e.g. C++ and Java, where (Doxygen-style?) docstrings have to start with a `/**` (or a `///`), but I'm not as familiar with these.

**Comment by jcs090218** [comment]
> My byte-compile matches yours, so we're on the same page. You can fix those by forward-declaring the variables earlier in the file with e.g. (defvar docstr-format-return).

I have fixed the forward-declaring. The warnings I have not fixed is the **Unused** warnings.

> One last thought -- I'm most familiar with Python these days, and I know there are several conventions for docstrings in common use -- pep256, numpy, google; search for "convention" in this document for more. I'd suggest you mention which convention you're following for Python, and verify that your convention lints happily against pydocstyle. I guess there are conventions around e.g. C++ and Java, where (Doxygen-style?) docstrings have to start with a /** (or a ///), but I'm not as familiar with these.

I am actually trying to support all style of docstrings! But I have not got time to dig into each style yet! One reason is that there are just many different styles. I implemented python docstring in 2017, and I have not use python recently. I think the reference what I was looking is pep256?

**Comment by riscy** [comment]
The warnings you have not fixed can be fixed if you forward-declare the unused variables. :)

Documenting the styles would be good, but I think the right thing for a package like this to do is to try to follow at least one _existing_ convention for each language, and patch toward fixing any violations of those conventions that pop up.  This is far better for users than declaring a new convention of your own.

I realize that's a nontrivial amount of work given the number of languages here.  Perhaps the answer is to start by supporting fewer languages and verifying that they work with that language's tooling.

**Comment by jcs090218** [comment]
> The warnings you have not fixed can be fixed if you forward-declare the unused variables. :)

Oh, I didn't notice that! Fixed!

> Documenting the styles would be good, but I think the right thing for a package like this to do is to try to follow at least one existing convention for each language, and patch toward fixing any violations of those conventions that pop up. 

Yeah, this could be the next step for this package. I agreed with you. 

> This is far better for users than declaring a new convention of your own.

I am not letting users to declaring their own convention. I am probably only going to implement few conventions for majority of people. What I am thinking is, 

```el
(setq docstr-python-style 'google)  ; Other value are possible
```

> I realize that's a nontrivial amount of work given the number of languages here. Perhaps the answer is to start by supporting fewer languages and verifying that they work with that language's tooling.

Yeah, I have started this module since 2017. I think this package is a long run package. I don't think I will be able to finish all the styles in the near future for all languages I am attempting to support. At least, for most languages; I think is usable. I think the overall of this package is a framework so I can keep on working under this architecture.

**Comment by riscy** [comment]
> I am not letting users to declaring their own convention.

I probably didn't come through clear -- when I said "declaring a convention of your own", I meant "declaring a convention unique to jcs090218".

> Yeah, this could be the next step for this package.

There is potential here, but I think you should aim to complete these next steps before indexing this on MELPA.  On closer inspection it appears you're not following the Python convention of putting docstrings inside _strings_ (hence the term "docstring"), but you told me above that you thought you were following pep256.

I also notice that the minor mode is enabled on a per-buffer basis, but it adds advice that effects _every_ buffer.

**Comment by jcs090218** [comment]
> I probably didn't come through clear -- when I said "declaring a convention of your own", I meant "declaring a convention unique to jcs090218".

Ah, okay. I must say I didn't come up with these convention. I probably decide the generic convention and let the user customize on it's own. That is why I have set of variable for user to change their style. 

See https://github.com/jcs-elpa/docstr#document-string. Wouldn't this enough? 😕 I feel like I have the way to customize all kind of convention from what I have seen. (I could be wrong)

> There is potential here, but I think you should aim to complete these next steps before indexing this on MELPA. On closer inspection it appears you're not following the Python convention of putting docstrings inside strings (hence the term "docstring"), but you told me above that you thought you were following pep256.

Got it. I think I have a memory corruption. For this package, I didn't follow pep256. You were right about the "my own unique convention". Wouldn't that enough for user to change it their own?

> I also notice that the minor mode is enabled on a per-buffer basis, but it adds advice that effects every buffer.

Yeah, I don't know how to bind a key per buffer using `advice`. And I don't want to use `define-key xxx-mode-map` because some major mode has defined their special feature with these keys. Just in case this package is compatible with those feature.

**Comment by riscy** [comment]
> Wouldn't this enough? 😕 I feel like I have the way to customize all kind of convention from what I have seen. (I could be wrong)

There's no big rush -- I just think this package needs more work.  Here's another example: [doc-comments in Rust](https://doc.rust-lang.org/rust-by-example/meta/doc.html) should start with `///`, block comments are generally not recommended, and they [use markdown internally](https://github.com/rust-lang/rfcs/blob/master/text/1574-more-api-documentation-conventions.md#using-markdown-1).

Yes, users could customize your package to fix this, but that feels like asking them to write the "last 10%" of the code for a supported language.

Here are a couple suggestions, but like I said above there's no big rush.

- Go read the documentation for each language you want to support and implement a standard convention
- Support languages you can confidently support; if that list is focused enough, consider renaming the package to e.g. docstr-js
- Lean on newcomment.el to help users create itemized lists of parameters in an existing docstring or doc-comment

**Comment by jcs090218** [comment]
Thanks for your advice!

> There's no big rush -- I just think this package needs more work. Here's another example: doc-comments in Rust should start with ///, block comments are generally not recommended, and they use markdown internally.

TBH, I am not really familiar with the following languages.

* Groovy
* Scala
* Rust

Do you think maybe I should just consider removing it? I was hoping I could learn the basic then implement these languages but then find out this might be too difficult.

I have work on this more and splitted each language to it's file. First language I have changed is Python, see [jcs-elpa/docstr/clients/docstr-python.el](https://github.com/jcs-elpa/docstr/blob/master/clients/docstr-python.el). What do you think? I think it is more out of box compare to the previous version.

---

I may need some help with finding the style guide for each language. Python is quite easy to find.

**Comment by riscy** [comment]
MELPA maintainers have their own projects they like to work on too.  How about you ping when you're confident you're ready for another look?

**Comment by jcs090218** [comment]
Okay, thanks for the review! ;)

**Pull request closed without merging**
