### PR TITLE
Add tongbu recipe

### PR DESCRIPTION
**Pull request by xuchunyang**
### Brief summary of what the package does

A simple web server for sharing text/file between phone and pc (well, any device with a web browser can work)

### Direct link to the package repository

https://github.com/xuchunyang/tongbu.el

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

The maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

<s>I fixed a warning from `M-x checkdoc`, I don't want to fix other warnings.</s> All checkdoc warnings are now fixed.

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.

I cannot find any issues for this package :tada:

**Comment by riscy** [comment]
This looks great.  Regarding the package summary, I'd recommend:

> A web server to share text or files between two devices

to improve its seachability/discoverability -- especially since the name tongbu might not be known for a lot of people.

While I'm here, a couple typos:
- divices -> devices
- "is inspired Chrome's" -> "is inspired by Chrome's"
- "because it's large than" -> "because it's larger than"

**Comment by xuchunyang** [comment]
Thanks for the check. I've fixed the issue and typos you mentioned.

**Comment by riscy** [comment]
Great!

**Pull request merged**
