### PR TITLE
Add recipe for nntwitter

### PR DESCRIPTION
**Pull request by dickmao**
### Brief summary of what the package does

A Gnus backend for Twitter.

### Direct link to the package repository

https://github.com/dickmao/nntwitter

### Your association with the package

Maintainer

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass -- I think you've got clashing requirements -- some are listed in nntwitter-pkg.el alongside Emacs 25 (see note below), and an Emacs 25.1 requirement is listed in nntwitter.el.

### nntwitter-api.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
```
1 issue found:
83:35: error: You should depend on (emacs "25.1") or the seq package if you need `seq-some'.
```


### nntwitter.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
```
17 issues found:
51:10: error: You should depend on (emacs "25.1") or the seq package if you need `seq'.
136:9: error: You should depend on (emacs "25.1") or the seq package if you need `seq-map'.
218:3: error: You should depend on (emacs "25.1") if you need `if-let'.
299:3: error: You should depend on (emacs "25.1") if you need `when-let'.
337:27: error: You should depend on (emacs "25.1") or the seq package if you need `seq-drop'.
454:5: error: You should depend on (emacs "25.1") if you need `when-let'.
672:13: error: You should depend on (emacs "25.1") if you need `when-let'.
684:39: error: You should depend on (emacs "25.1") or the seq package if you need `seq-find'.
710:32: error: You should depend on (emacs "25.1") or the seq package if you need `seq-filter'.
722:39: error: You should depend on (emacs "25.1") or the seq package if you need `seq-find'.
726:42: error: You should depend on (emacs "25.1") or the seq package if you need `seq-find'.
730:39: error: You should depend on (emacs "25.1") or the seq package if you need `seq-find'.
738:33: error: You should depend on (emacs "25.1") or the seq package if you need `seq-find'.
750:33: error: You should depend on (emacs "25.1") or the seq package if you need `seq-filter'.
769:25: error: You should depend on (emacs "25.1") or the seq package if you need `seq-find'.
776:25: error: You should depend on (emacs "25.1") or the seq package if you need `seq-find'.
826:36: error: You should depend on (emacs "25.1") if you need `string>'.
```


### Loadability ###

Verifying ability to #'load each file:
```
Loading nntwitter-api.el
Loading nntwitter.el
Done.
```

**Comment by dickmao** [comment]
That's odd.  When I run melpazoid I don't get those errors.  I could change the mention of "emacs 25" in nntwitter-pkg.el to "emacs 25.1" but I don't think that will change things on your end since I don't think your melpazoid looks at nntwitter-pkg.el either.

lint

**Comment by riscy** [comment]
I think in this case what's happening is melpazoid is detecting the "main" file as nntwitter-pkg.el, and then passing that into a [package-lint variable](https://github.com/purcell/package-lint/blob/master/package-lint.el#L47-L55).

**Comment by riscy** [comment]
I'm surprised it's not working on your side, that might be a usage gotcha that I need to fix.

**Comment by dickmao** [comment]
Ah, I set the PACKAGE_MAIN env variable to nntwitter-pkg.el, and reproduced those errors.  I've since fallen in line and changed "25" to "25.1" in  https://github.com/dickmao/nntwitter/commit/43ac2d6248b01d980fbaefa02dc6bba927fdc689

**Comment by riscy** [comment]
Thanks!

**Comment by purcell** [comment]
@dickmao Here I'd very strongly advise you to get rid of the `-pkg.el` file and just put the metadata in the primary `.el` file. Having `Package-Requires` headers in the latter is particularly confusing.

**Comment by purcell** [comment]
BTW, you're missing a `defgroup`. You should add one, in order to name the custom group and place it in the overall customisation hierarchy.

**Comment by purcell** [comment]
Plus, it's quite weird to initialise a separate keymap variable as a side-effect here: https://github.com/dickmao/nntwitter/blob/43ac2d6248b01d980fbaefa02dc6bba927fdc689/lisp/nntwitter.el#L84-L87

**Comment by dickmao** [comment]
> @dickmao Here I'd very strongly advise you to get rid of the `-pkg.el` file and just put the metadata in the primary `.el` file. Having `Package-Requires` headers in the latter is particularly confusing.

I hadn't known about PACKAGE_MAIN allowing package-lint to register `-pkg.el`, and added that setenv to my CI (and deleted `Package-Requires` from the primary `.el` files).  Thanks for the heads up.

**Pull request merged**
