### PR TITLE
Add centaur-tabs recipe

### PR DESCRIPTION
**Pull request by ema2159**
### Brief summary of what the package does

This package aims to be an aesthetic, modern looking, functional tabs plugin with lots of useful features. Originally forked from awesome tab (who's author doesn't like MELPA but gave me permission to fork his repo and create a package myself), this package has been heavily modified and has a lot of added features. Posted it in Reddit and it had a considerably positive response: https://www.reddit.com/r/emacs/comments/c4r3wn/centaur_tabs_a_new_customizable_and_aesthetic/

It is heavily documented, it has a really very README and overall works pretty solid.

### Direct link to the package repository

https://github.com/ema2159/centaur-tabs

### Your association with the package

I am the author of the package and currently only maintainer (although I would like if somebody helped me because it's always nice to work as a team)

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly (some warnings are presented, should be easily be fixed)
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by ema2159** [comment]
Done, tell me if there's anything else.

**Comment by riscy** [comment]
Another quick pass of the checklist:

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190621.14):
```
15 issues found:

1:1: error: package.el cannot parse this buffer: End of file during parsing
1:77: warning: You should depend on (emacs "24") if you need lexical-binding.
13:1: error: Couldn't parse "Package-Requires" header: End of file during parsing
587:9: error: You should depend on (emacs "24.4") if you need `add-face-text-property'.
588:9: error: You should depend on (emacs "24.4") if you need `add-face-text-property'.
1141:1: error: "ns-use-srgb-colorspace" doesn't start with package's prefix "centaur-tabs".
1922:29: error: You should depend on (emacs "24.3") if you need `setq-local'.
2013:6: error: You should depend on (emacs "24") if you need `string-prefix-p'.
2014:6: error: You should depend on (emacs "24") if you need `string-prefix-p'.
2015:6: error: You should depend on (emacs "24") if you need `string-prefix-p'.
2016:6: error: You should depend on (emacs "24") if you need `string-prefix-p'.
2019:11: error: You should depend on (emacs "24") if you need `string-prefix-p'.
2058:11: error: You should depend on (emacs "24") if you need `string-prefix-p'.
```
To pacify the compiler around e.g. `ns-use-srgb-colorspace` you can simply write this:
```elisp
(defvar ns-use-srgb-colorspace)
```

<kbd>M-x byte-compile-file</kbd>:
```
centaur-tabs.el:1544:1:Error: Symbol's function definition is void: centaur-tabs-separator-pattern-defun
```

**Comment by ema2159** [comment]
> Another quick pass of the checklist:
> 
> M-x package-lint-current-buffer (using version 20190621.14):
> 
> ```
> 15 issues found:
> 
> 1:1: error: package.el cannot parse this buffer: End of file during parsing
> 1:77: warning: You should depend on (emacs "24") if you need lexical-binding.
> 13:1: error: Couldn't parse "Package-Requires" header: End of file during parsing
> 587:9: error: You should depend on (emacs "24.4") if you need `add-face-text-property'.
> 588:9: error: You should depend on (emacs "24.4") if you need `add-face-text-property'.
> 1141:1: error: "ns-use-srgb-colorspace" doesn't start with package's prefix "centaur-tabs".
> 1922:29: error: You should depend on (emacs "24.3") if you need `setq-local'.
> 2013:6: error: You should depend on (emacs "24") if you need `string-prefix-p'.
> 2014:6: error: You should depend on (emacs "24") if you need `string-prefix-p'.
> 2015:6: error: You should depend on (emacs "24") if you need `string-prefix-p'.
> 2016:6: error: You should depend on (emacs "24") if you need `string-prefix-p'.
> 2019:11: error: You should depend on (emacs "24") if you need `string-prefix-p'.
> 2058:11: error: You should depend on (emacs "24") if you need `string-prefix-p'.
> ```

Done, it was an unclosed parenthesis.

> To pacify the [linter] around e.g. `ns-use-srgb-colorspace` you can simply write this:
> 
> ```emacs-lisp
> (defvar ns-use-srgb-colorspace)
> ```

Done
 
> M-x byte-compile-file:
> 
> ```
> centaur-tabs.el:1544:1:Error: Symbol's function definition is void: centaur-tabs-separator-pattern-defun
> ```

I don't quite understand this one, it is defined right at line 1241

**Comment by ema2159** [comment]
I'm not sure why I'm getting a completely different compiling log, this is what I'm getting:
```
Compiling file /home/emmanuel/.emacs.d/other/centaur-tabs/centaur-tabs.el at Sun Jun 30 17:39:27 2019
centaur-tabs.el:1543:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1543:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1544:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1544:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1545:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1546:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1547:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1547:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1548:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1548:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1549:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1549:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1550:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1550:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1551:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1551:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1552:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1552:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1555:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1555:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1556:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1556:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1557:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1557:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1558:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1558:1:Warning: Unused lexical variable
    ‘second-pattern-height’

In centaur-tabs-monitor-window-scroll:
centaur-tabs.el:1602:42:Warning: reference to free variable
    ‘centaur-tabs-last-sticky-func-name’
centaur-tabs.el:1603:78:Warning: assignment to free variable
    ‘centaur-tabs-last-sticky-func-name’
centaur-tabs.el:1705:1:Warning: Unused lexical variable ‘selected’

In centaur-tabs-move-current-tab-to-right:
centaur-tabs.el:1755:17:Warning: assignment to free variable ‘the-buffer’
centaur-tabs.el:1757:11:Warning: reference to free variable ‘the-buffer’

In centaur-tabs-move-current-tab-to-left:
centaur-tabs.el:1777:15:Warning: assignment to free variable
    ‘not-yet-this-buf’
centaur-tabs.el:1783:19:Warning: reference to free variable ‘not-yet-this-buf’
centaur-tabs.el:1791:1:Warning: Unused lexical argument ‘buffer’

In centaur-tabs-get-extensions:
centaur-tabs.el:1894:37:Warning: reference to free variable
    ‘current-group-name’

In end of data:
centaur-tabs.el:2100:1:Warning: the function ‘helm-build-sync-source’ is not
    known to be defined.
```

**Comment by riscy** [comment]
Yeah -- that about matches my compile log if I have already eval'd the buffer or run e.g. `load-library` with centaur-tabs.el in my load path.  The first time the compiler encounters the file, though, it has trouble parsing the macros.

My advice to you is to see if you can avoid using macros -- I believe they should only be used when they enable clearer code in the form of a domain-specific language, but in a lot of cases they seem to be serving the purpose of obfuscating your code (e.g., you have to look between the different functions and macros to determine which variables are meant to be in scope when the macro is being run, etc.)

I have a few commits up that might help you move in that direction -- watch out for a PR.

A quick note on using the package while I'm here:  if I run `centaur-tabs-mode` and then I run the interactive `centaur-tabs-select-visible-tab` I get an error.

**Comment by ema2159** [comment]
>I have a few commits up that might help you move in that direction -- watch out for a PR.

That I would really appreciate! This is my first time with a package and I want to do it the best I can

**Comment by ema2159** [comment]
> A quick note on using the package while I'm here: if I run centaur-tabs-mode and then I run the interactive centaur-tabs-select-visible-tab I get an error

This function is supposed to work with a "numbered keybinding" so for example if it is binded to "C-2 " it jumps to the second buffer, it shouldn't be interactive but if the (interactive) is removed from the function it doesn't work.

**Comment by riscy** [comment]
I see!  That's my mistake. :) I'll be able to look more during the week.

**Comment by ema2159** [comment]
> I see! That's my mistake. :) I'll be able to look more during the week.

Thanks brother, you're awesome. Let's make this a great package for the community!

**Comment by ema2159** [comment]
@riscy Fixed the macros problem and pacified all linting problems. Now it byte compiles cleanly. I think now it's ready to go!

**Comment by riscy** [comment]
Cool!  I've got this working great for me right now.  Welcome to MELPA! :)

**Comment by ema2159** [comment]
Nice! Thanks for all your help!

**Pull request merged**
