### PR TITLE
added counsel-pydoc recipes.

### PR DESCRIPTION
**Pull request by co-dh**
### Brief summary of what the package does
Run pydoc with counsel

### Direct link to the package repository

https://github.com/co-dh/pydoc_utils

### Your association with the package

maintainer

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Mostly looks good, but please depend on (and `require`) the `ivy` package, not `swiper`.

**Comment by co-dh** [comment]
@purcell  Thanks. I've updated my elisp code.

**Comment by purcell** [comment]
Great, merged - thanks!

**Comment by co-dh** [comment]
Thanks you!

**Pull request merged**
