### PR TITLE
Add 'diff-at-point' package

### PR DESCRIPTION
**Pull request by ideasman42**
### Brief summary of what the package does

Improved diff navigation, using the current context when diffing the current repository.

Demo video: https://youtu.be/bR4czpEqah8

### Direct link to the package repository

https://gitlab.com/ideasman42/emacs-diff-at-point

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Looks cool -- just coming through with a quick pass:

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
2 issues found:

1:0: warning: The package summary should not end with a period.
221:18: warning: Closing parens should not be wrapped onto new lines.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
diff-at-point.el:314:1:Warning: the function `diff-goto-source' is not known
    to be defined.
```

Other:
- diff-at-point.el#L302: It's safer to sharp-quote function names; use `#'`
- diff-at-point.el#L131: You can use `not` or `null`
- diff-at-point.el#L166: You can use `not` or `null`
- diff-at-point.el#L167: You can use `not` or `null`
- diff-at-point.el#L175: You can use `not` or `null`
- diff-at-point.el#L185: You can use `not` or `null`
- diff-at-point.el#L196: You can use `not` or `null`

**Comment by ideasman42** [comment]
Thanks for the hints, applied changes.
(note that I went over these steps but did some changes after :/ so missed the linter error).

**Comment by riscy** [comment]
Thanks!  It feels like this one:

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
diff-at-point.el:305:1:Warning: the function `diff-goto-source' is not known
    to be defined.
```

...could be solved with a `(require 'diff-mode)`

Another small note I see is that `progn` isn't needed for the else part of an if, e.g.:
```elisp
              (if fallback-point-is-begin
                (progn
                  (goto-char fallback-point-begin)
                  (forward-line 1)
                  (forward-char))
                (progn
                  (goto-char (or fallback-point-end current-filename-diff-point-max))
                  (forward-line -1)
                  (forward-char)))
```
could be:
```elisp
(if fallback-point-is-begin
    (progn
      (goto-char fallback-point-begin)
      (forward-line 1)
      (forward-char))
    (goto-char (or fallback-point-end current-filename-diff-point-max))
    (forward-line -1)
    (forward-char))
```

**Comment by ideasman42** [comment]
Thanks, updated.

**Comment by alphapapa** [comment]
@ideasman42 Have you considered submitting this to Emacs itself?  It seems like a basic, useful feature that ought to exist by default.  Why keep it as a separate package?

**Comment by ideasman42** [comment]
@alphapapa yes, I proposed this, I submitted a video with the functionality to see if they were interested to add this but didn't hear back.

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=36526

**Comment by riscy** [comment]
Looking below the surface now, I wonder if this functionality is a part of magit?  e.g. are you familiar with`magit-status-here`?

**Comment by ideasman42** [comment]
> Looking below the surface now, I wonder if this functionality is a part of magit? e.g. are you familiar with`magit-status-here`?

No, I don't use maggit, however I installed it and compared the functionality.

There are some differences:

- Only works with git (I use this with subversion too).
- Doesn't jump to the nearest hunk (this is handy when working in large files).

**Comment by riscy** [comment]
Thanks for checking!  Here's another quick nag:

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
diff-at-point.el:241:15:Warning: `message' called with 1 args to fill 0 format
    field(s)
```

but this is looking close to ready to me.

**Comment by ideasman42** [comment]
> Thanks for checking! Here's another quick nag:
> 
> M-x byte-compile-file (using Emacs 26.3):
> 
> ```
> diff-at-point.el:241:15:Warning: `message' called with 1 args to fill 0 format
>     field(s)
> ```
> 
> but this is looking close to ready to me.

Corrected

**Comment by riscy** [comment]
Ok, great.  These aren't blockers, but I'm just having one last check:
- `When SCROLL-RESET is t `  -> `When SCROLL-RESET is non-nil` (a few places)

Thanks for this!

**Pull request merged**
