### PR TITLE
Add dianyou

### PR DESCRIPTION
**Pull request by redguardtoo**
### Brief summary of what the package does

Search and analyze mails in Gnus

### Direct link to the package repository

https://github.com/redguardtoo/dianyou

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
You have to fix the name of the package inside the recipe.

**Comment by redguardtoo** [comment]
@tarsius , I fixed the package name

**Comment by redguardtoo** [comment]
I updated the pull request.

**Comment by riscy** [comment]
Thanks for checking that out.  I'm not reviewing this in depth yet since I'm still getting:
```
In end of data:
dianyou.el:333:1:Warning: the function ‘gnus-group-topic-name’ is not known to
    be defined.
```
Can you confirm you're getting the same?  I believe you need to `(require 'gnus-topic)` to pull in the elisp where this function is defined.

At a glance, you should also require `ivy` (for `ivy-read`).  But in the case of ivy-read, why not just use a `completing-read` instead?  Then people can use whatever completing-string-read their hooks are set up to use.

**Comment by redguardtoo** [comment]
@riscy , I updated the code. I ran `byte-compile-file` on `dianyou.el` and got no warning/error this time.

 I think `ivy` is necessary to give user better experience out of box.

**Comment by redguardtoo** [comment]
On second thought, removing `ivy` is good idea. It could grow user base to `helm` users. I updated code.

**Comment by riscy** [comment]
Looks good over here.  Thanks!

**Pull request merged**
