### PR TITLE
Add mol-tree-mode recipe

### PR DESCRIPTION
**Pull request by osv**
### Brief summary of what the package does

Major mode for editing [.tree files](https://github.com/nin-jin/tree.d) 

### Direct link to the package repository

https://github.com/osv/mol-tree-mode

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- here's just a very quick pass over the checklist with some other lints snuck in:

### mol-tree-meta-mode.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
mol-tree-meta-mode.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
```
1 issue found:
25:4: warning: Closing parens should not be wrapped onto new lines.
```


### mol-tree-mode.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
mol-tree-mode.el:189: Argument `num' should appear (as NUM) in the doc string
Warning (emacs): 
mol-tree-mode.el:196: Argument `begin' should appear (as BEGIN) in the doc string
Warning (emacs): 
mol-tree-mode.el:212: Argument `begin' should appear (as BEGIN) in the doc string
Warning (emacs): 
mol-tree-mode.el:220: Argument `distance' should appear (as DISTANCE) in the doc string
```

package-lint (using version 20210528.2348):
```
1 issue found:
219:30: error: `distance' was removed in Emacs version 25.1.
```
False positive; ignore, or you could rename it to `distance_` (I think small concessions like this are worth it for having a 100% clean package-lint, but not a blocker)

Other [lints](https://github.com/riscy/melpazoid):
- mol-tree-mode.el#L268: It's safer to sharp-quote function names; use `#'`
- mol-tree-mode.el#L178: Could this point/point-at-bol comparison use `bolp`?

### mol-tree-view-mode.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
mol-tree-view-mode.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### Loadability ###

Verifying ability to #'load each file:
```
Loading mol-tree-meta-mode.el
Loading mol-tree-mode.el
Loading mol-tree-view-mode.el
Done.
```

### Package ###

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to mol-tree-meta-mode.el
- Add license boilerplate or an [SPDX-License-Identifier](https://spdx.dev/ids/) to mol-tree-view-mode.el

**Comment by riscy** [comment]
I'll mark this awaiting upstream for now, but feel free to reach out.

**Comment by osv** [comment]
@riscy Hi, thanks for review! I need to say I run tools for linting listed in PR templated but some issues ignored by me like, Commentary.

 It is good to see how quality check is increased since last time I prepared some PR for melpa!

I will apply changes in few days

**Comment by riscy** [comment]
Friendly ping. :)

**Comment by riscy** [comment]
It's been over a year since we've heard back -- I'll close this PR for now, but please feel welcome to reopen it when you're ready.

**Pull request closed without merging**
