### PR TITLE
Add recipe for decor

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
### Brief summary of what the package does

This library attempts to simplify removal of all frame (window) decorations via two simple functions and possibly some constants later for customization.

### Direct link to the package repository

https://github.com/KeyWeeUsr/decor

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by jcs090218** [comment]
I'm helping MELPA maintainers a little bit here.

Basic tests are good! 🎉 

`decor.el` with checkdoc (0.6.2)

```
No issues found
```

`decor.el` with package-lint (20230905.629)

```
No issues found.
```

**Comment by riscy** [comment]
Thanks for this.  I noticed you've got other PR(s) #8748 already open.  To split my review time evenly between authors, I try to do one PR at a time per author, but I promise I'll get to this when we resolve earlier PRs.

**Comment by riscy** [comment]
Thanks for your patience.  Checklist looks good, but I strongly agree with @mattiasb's suggestion.  Having (X11) in the summary line is useful, but I feel like this package is more clearly described as an `xprop` wrapper (e.g. call it `xprop`, retain the mention of x11 in the summary line, etc.)

Currently what you've implemented is a toggle that switches between a decorated and undecorated frame, but maybe you or contributors would want to implement other `xprop` commands.

Also, while `decor-toggle-single-frame` doesn't fit with Emacs' notion of a global minor mode, `decor-toggle-all-frames` definitely does, and imo adopting the minor mode idiom when possible is usually the better approach. e.g.

```elisp
;;;###autoload
(define-minor-mode xprop-undecorated-mode
  "..."
  (if xprop-undecorated-mode
     [call the (equivalent of decor-toggle-all-frames t)]
   [call the (equivalent of decor-toggle-all-frames nil)]))
```

Let me know your thoughts!

**Comment by KeyWeeUsr** [comment]
@riscy 

> [...] this package is more clearly described as an xprop wrapper [...]

Unfortunately this isn't the idea of the package and while a package for `xprop` would be nice, for now I'd rather keep it within until other (decorating) functionality is required. Then I'd split it into 2 packages and perhaps consider other `xprop` functionality. If somebody has a need, feel free to ping me with the idea and I might hammer something down :relaxed: 

The idea is really just a decoration manipulator and X.org/X11 is just one of its targets. I haven't had proper dev access to Wayland yet because it's been causing issues for other programs I use (hence I disabled it), but there's a support for it planned too and also for other platforms with their desktop environments. For now I hope to throw away `xprop` eventually and just compile against the library `xprop` uses directly (same for other envs), but with `xprop` wrapper it's quite a nice idea, so when the time allows, I might look into that too. Hopefully not with `call-process` though.

For the minor mode, that was the original idea, but I completely forgot about minor modes being non-buffer-local too so I scraped it away :smiling_face_with_tear:  I've added the minor mode part, should work fine now. :+1:

**Comment by riscy** [comment]
I think your arguments are sound.

But you should also entertain the possibility - er, probability - that what the package is right now is what it will always be. These are lofty future plans (Wayland, compiling directly against x11 libs, supporting other window managers).  Maintenance of a package is on its own enduring work, and you have several PRs open right now.  I don't mean to be negative at all with this feedback, but if you're relatively new to this I think there is nothing wrong with saying "this is the xprop wrapper package", and you always have the option to rename it in the future.

All that said, I think you have a couple more compiler nags:

`decor.el` with byte-compile using Emacs 28.1:
```
decor.el:86:1: Warning: defcustom for `decor-mode' fails to specify containing
    group
decor.el:86:1: Warning: defcustom for `decor-mode' fails to specify containing
    group
```

but this is shaping up.

**Comment by KeyWeeUsr** [comment]
> [...] that what the package is right now is what it will always be.

I do understand the doubts, yet I do have Wayland and other machines (VM and physical) and also worked with WinAPI, SDL2 and likes, so I know what I'd be getting into. For some of which I even know the APIs to use, e.g. [`XChangeProperty()`](https://x.org/releases/current/doc/libX11/libX11/libX11.html#XChangeProperty), [`SetWindowLongPtrA()`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptra), [`glfwWindowHint()`](https://www.glfw.org/docs/latest/group__window.html#ga7d9c8c62384b1e2821c4dc48952d2033), etc. It's more of a time/usage thing than not knowing how.

Since Windows is not my primary platform I don't use Emacs on it as heavily, hence the decorations present were either bearable or I've used fullscreen mode. And to do that, I'll need to switch for X11 libs anyway to get the compilation going and then mirror it for Windows, or use, in the very least, VBS or PowerShell+C# to get to WinAPI :man_shrugging:

I've also been maintaining some things in the past, so this wouldn't be something completely new on my plate and if it breaks, I'd need to fix it for myself anyway. :)

I've fixed the compilation issues. For some reason 27.1 doesn't care, but 28.1 does. :thinking:

**Comment by riscy** [comment]
Thank you!  Noted re: the compilation differences, too (and I need to get my checks on Emacs 29).

**Pull request merged**
