### PR TITLE
Added recipe for lastpass

### PR DESCRIPTION
**Pull request by storvik**
### Brief summary of what the package does

A LastPass command line wrapper that uses lpass command line utility to manage passwords in Emacs. 

### Direct link to the package repository

https://github.com/storvik/emacs-lastpass

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
- Current package description is `Elisp LastPASS`.  It should be `lastpass command wrapper` or better description

**Comment by storvik** [comment]
@syohex consider it fixed!

**Comment by purcell** [comment]
Thanks!

The name "elpass" is a bit generic and confusing, particularly since there are other elisp packages which integrate with the "pass" tool. Would you consider renaming this package to simple "lastpass"? (You can still call the containing repo something like "emacs-lastpass" if you prefer.)

Regarding the code, I feel like you should be using `shell-quote-argument` when building those command line strings. Looks good otherwise!

**Comment by storvik** [comment]
@purcell Thanks for the feedback. 

I will rename the package to "lastpass" and update the pull request. 

Didn't know about the `shell-quote-argument` before, but it seems to fit this perfectly. I'll try to get this implemented as soon as possible.

**Comment by storvik** [comment]
@purcell I have updated the pull request and added shell-quote-argument. Hope you find that everything is in order now.

**Comment by purcell** [comment]
Yes, looks great - sorry for the delay!

**Comment by storvik** [comment]
No problem, thank you very much for the feedback. Useful for a new elisp developer!

**Comment by syohex** [comment]
I think `lastpass-location` is not good for users. If users install lastpass command by package manager except homebrew(default configuration), it is installed at `/usr/bin` usually. Such users need to change `lastpass-location` value in current implementation.

It is not necessary to specify full path for executing external command if `PATH` and `execute-path` are set correctly(`/usr/bin`, `/bin`, `/usr/local/bin` are set by default usually). I think that `lastpass-location` should be `"lastpass"`( or `(executable-find "lastpass")`) rather than directory path.

**Comment by storvik** [comment]
That's a valid point. I'll rewrite this part to use executable-find. Thanks!

**Comment by purcell** [comment]
Just `"lastpass"` would be better than using `executable-find`. They're pretty much equivalent, except that the latter "locks-in" the location at the time it is called based on the $PATH at the time. So if someone changes `exec-path` (or $PATH) after `lastpass-location` has been defined using `executable-find`, then it won't work.

**Comment by storvik** [comment]
That's probably the best solution. I think I'll remove the location variable entirely, as it's no need to have this option.

**Pull request merged**
