### PR TITLE
Add recipe for marquee-header.

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Code interface for displaying marquee in header.

### Direct link to the package repository

https://github.com/jcs090218/marquee-header

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
This quick first pass is semi-automated - please forgive any oversights.

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
No issues! 🎊

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
marquee-header.el:177:1:Warning: the function `spaces-string' is not known to
    be defined.
```
(looks like we need a require on `rect`. I didn't know about this little function, neat)

<kbd>M-x check-declare-file</kbd> (optional -- not on the MELPA checklist):
No issues! 🎉

**Comment by jcs090218** [comment]
Thanks for the review! Fixed! :D

**Comment by riscy** [comment]
Looking more closely at this now.  This is really great.

One small thing I notice is that if I run `(marquee-header-notify "Test")` in reasonably rapid succession, then the marquee gets "stuck" after completion (I think the value of `marquee-header--previous-header-line-format` gets overwritten with a marquee string).  It feels like the current marquee should be cleared before another one is allowed to start.

It's a matter of style, but just in case you're not aware you can write blocks like [this](https://github.com/jcs090218/marquee-header/blob/4648b2689d6bb58317b1e515ee2c1da394d3c76a/marquee-header.el#L96-L101) as:
```elisp
    (setq marquee-header--message msg
          marquee-header--direction direction
          marquee-header--frame-counter frame-counter
          marquee-header--message-decoration deco
          ...)
```

Since [this](https://github.com/jcs090218/marquee-header/blob/4648b2689d6bb58317b1e515ee2c1da394d3c76a/marquee-header.el#L150-L151) function is not interactive, any code using it will presumably `(require 'marquee-header)` which makes the autoload cookie [unnecessary](https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html#When-to-Autoload).

I think you only need to check `stringp msg` [here](https://github.com/jcs090218/marquee-header/blob/4648b2689d6bb58317b1e515ee2c1da394d3c76a/marquee-header.el#L155-L156).   If it's nil then it's not a string -- similarly with `time` below that, unless I'm missing something.

**Comment by jcs090218** [comment]
Thanks! I think all problems you pointed out have been fixed right now!

**Comment by riscy** [comment]
Looks great.  Nice work!

**Pull request merged**
