### PR TITLE
Add fifo recipe

### PR DESCRIPTION
**Pull request by mola-T**
https://github.com/mola-T/fifo

I am the author.

The package contains an abstract class to provide first in first out functions for inherited class.

Thank you.

### CODE REVIEW

**Comment by purcell** [comment]
It's unusual in elisp for authors to use eieio classes: anyone wanting to use the `fifo` functionality would need to create a subclass, and very few people would want to do that. So using such a generic name for this package isn't a good choice, and I'd suggest renaming to `fifo-class.el`. (P.S. For an example of a more idiomatic elisp fifo implementation, see https://github.com/commercialhaskell/stack-ide/blob/master/stack-mode/stack-fifo.el)

**Comment by mola-T** [comment]
I will change the package name to `fifo-class`.

**Comment by mola-T** [comment]
You can have a look. Thank you.

**Comment by purcell** [comment]
Nice, thanks.

**Pull request merged**
