### PR TITLE
hvesalai maintains sbt-mode and scala-mode

### PR DESCRIPTION
**Pull request by hvesalai**
See #6443

### CODE REVIEW

**Comment by hvesalai** [comment]
This pr doesn't remove ensime. Is that a problem? Will there be a conflict for sbt-mode and scala-mode that were part of ensime before?

**Comment by hvesalai** [comment]
@tarius this needs to be merged. The emacs-scala-mode repository name was wrong in pull request #6465

**Comment by tarsius** [comment]
Ah crap... I opened a pr in order to run the tests to avoid exactly this kind of mistake and then I didn't wait for the tests to complete?!

**Comment by tarsius** [comment]
Fixed with eb0b5735e9d930502ea7346e29d350ba8068440c.

**Pull request closed without merging**
