### PR TITLE
recipes/helm-selector: Add helm-selector

### PR DESCRIPTION
**Pull request by Ambrevar**
### Brief summary of what the package does

Helm Selector is a collection of [[Https://emacs-helm.github.io/helm/][Helm]] helper functions for convenient buffer
selection.

### Direct link to the package repository

https://github.com/emacs-helm/helm-selector

### Your association with the package

I'm the maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
  (The files other than the main files don't need a commentary.)
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass.

### helm-selector-cider.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-selector-cider.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20200616.2257):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```
(This is not a blocker, but something to be aware of)

### helm-selector-elfeed.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-selector-elfeed.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20200616.2257):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### helm-selector-eww.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-selector-eww.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20200616.2257):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

Suggestions/experimental static checks:
- helm-selector-eww.el#L49: It's safer to sharp-quote function names; use `#'`

### helm-selector-geiser.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-selector-geiser.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20200616.2257):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

Suggestions/experimental static checks:
- helm-selector-geiser.el#L50: It's safer to sharp-quote function names; use `#'`
- helm-selector-geiser.el#L49: It's safer to sharp-quote function names; use `#'`

### helm-selector-info.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-selector-info.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20200616.2257):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### helm-selector-mu4e.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-selector-mu4e.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20200616.2257):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```

Suggestions/experimental static checks:
- helm-selector-mu4e.el#L51: It's safer to sharp-quote function names; use `#'`

### helm-selector-notmuch.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-selector-notmuch.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20200616.2257):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### helm-selector-org.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-selector-org.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20200616.2257):
```
2 issues found:
9:0: error: Package-Requires outside the main file have no effect.
51:34: error: You should depend on (emacs "26.1") if you need `and-let*'.
```


### helm-selector-shell.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-selector-shell.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20200616.2257):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### helm-selector-slime.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-selector-slime.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20200616.2257):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### helm-selector-sly.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
helm-selector-sly.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20200616.2257):
```
1 issue found:
9:0: error: Package-Requires outside the main file have no effect.
```


### helm-selector.el ###

byte-compile (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200616.2257):
- No issues!


### Loadability ###

Verifying ability to #'load each file:
```
Loading helm-selector-cider.el
Loading helm-selector-elfeed.el
Loading helm-selector-eww.el
Loading helm-selector-geiser.el
Loading helm-selector-info.el
Loading helm-selector-mu4e.el
Loading helm-selector-notmuch.el
Loading helm-selector-org.el
Loading helm-selector-shell.el
Loading helm-selector-slime.el
Loading helm-selector-sly.el
Loading helm-selector.el
Done.
```

**Comment by Ambrevar** [comment]
About the lack of commentary in the subfiles: I believe it's not needed, the commentary in the main file explains it all.

**Comment by riscy** [comment]
> I believe it's not needed, the commentary in the main file explains it all.

Yeah, that's fine.  (The commentary in the main file ends up in the MELPA index, so it's important.)  But it's worth noting that the builtin `finder-commentary` function also looks for `;;; Commentary` in various files, so it could be worth adding a simple line along the lines of "Support file for helm-selector."

- 51:34: error: You should depend on (emacs "26.1") if you need `and-let*'.
- helm-selector-eww.el#L49: It's safer to sharp-quote function names; use `#'`

(The first is important, the second one is minor and fyi)

**Comment by Ambrevar** [comment]
Thanks, both issues are now fixed on master.

**Comment by riscy** [comment]
Taking a closer look now -- this looks nice.  A couple more suggestions:

- In helm-selector-mu4e you have `We use 'apply' to avoid the warning about the undefined function.` but a cleaner option might be to `(declare-function mu4e-conversation--buffer-p  ...)` at the outset?
- Related: It looks like that function (`mu4e-conversion--buffer-p`) has been marked as a "private" function by the package author, so you may be on shaky ground by having a dependency on it.  You could reach out to the upstream package maintainer and ask if they'd make the function public and so I believe less likely to disappear
- Similar with `sly-mrepl--find-buffer`, `geiser-repl--repl-name`
- In helm-selector-geiser, you run a `defun` inside a `lambda`.  I believe this means the function is being unnecessarily redefined every time someone calls helm-selector-geiser
- In that same function, I believe you're using `advice-add :override` (and then immediately removing that advice) but what I think you want is something like cl-letf or cl-flet.  The way you have it now could result in the advice being permanent if execution is interrupted before the advice can be removed

**Comment by Ambrevar** [comment]
> - In helm-selector-mu4e you have `We use 'apply' to avoid the warning about the undefined function.` but a cleaner option might be to `(declare-function mu4e-conversation--buffer-p  ...)` at the outset?

Fixed.

> - Related: It looks like that function (`mu4e-conversion--buffer-p`)
> has been marked as a "private" function by the package author, so you
> may be on shaky ground by having a dependency on it.  You could reach
> out to the upstream package maintainer and ask if they'd make the
> function public and so I believe less likely to disappear

I'm the author of mu4e-conversion but I'm not using it anymore, so it's
here to stay until someone else adopts it.

> - Similar with `sly-mrepl--find-buffer`, `geiser-repl--repl-name`

It's unlikely to change.  Let me know if you really want me to ping the
authors about it, I'll do it.

> - In helm-selector-geiser, you run a `defun` inside a `lambda`.  I believe this means the function is being unnecessarily redefined every time someone calls helm-selector-geiser

Fixed.

> - In that same function, I believe you're using `advice-add :override` (and then immediately removing that advice) but what I think you want is something like cl-letf or cl-flet.  The way you have it now could result in the advice being permanent if execution is interrupted before the advice can be removed

Good catch, fixed!

**Comment by riscy** [comment]
I think this last one --

byte-compile (using Emacs 26.3):
```
helm-selector-geiser.el:42:1:Warning: Unused lexical variable
    `geiser-repl-buffer-name'
```
is because you want to use `cl-flet` instead of `cl-letf` (so there may be a bug there) but I won't block -- you've been great about maintaining.

**Comment by Ambrevar** [comment]
Good catch, fixed!

Thanks for your review!

**Pull request merged**
