### PR TITLE
Add cov

### PR DESCRIPTION
**Pull request by AdamNiederer**
### Brief summary of what the package does

Displays gcov data on your code

### Direct link to the package repository

https://github.com/AdamNiederer/cov

### Your association with the package

I am the maintainer of this project.

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
I have sent PR. https://github.com/AdamNiederer/cov/pull/5

**Comment by purcell** [comment]
Thanks. How does this differ from "coverage" and "coverlay"?

**Comment by AdamNiederer** [comment]
Coverage.el only supports a specific coverage tool for Ruby, and coverlay only supports lcov. Both don't have profiling support.
This package is also written to be easily accept other coverage backends without much modification, so it should accept more formats than both of them, eventually.

**Comment by purcell** [comment]
Thanks, and sorry for the delay. Would be nice if you could ping the authors of the other packages and join forces -- having a standard coverage tool which works across languages would be a good outcome, and it would be a shame if `cov` never gained support for additional backends.

**Pull request merged**
