### PR TITLE
added prassee theme 1.0 release

### PR DESCRIPTION
**Pull request by prassee**
### Brief summary of what the package does

A dark-theme based on doom-theme 

### Direct link to the package repository

https://github.com/prassee/prassee-emacs-theme

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]
Maintainer

### Relevant communications with the upstream package maintainer

**None needed** 

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
This package does not conform Emacs Lisp packaging convention.
- Package header position is wrong
- No package footer
- etc

https://www.gnu.org/software/emacs/manual/html_node/elisp/Packaging.html#Packaging

**Comment by prassee** [comment]
Updated please check

**Comment by tarsius** [comment]
You should also add the `;;; Commentary:` and `;;; Code:` headings. The doc-string and the commentary should end with a period.

**Comment by prassee** [comment]
updated by adding ```;;; Commentary:```  and ```;;; Code:``` in the headings.

**Comment by syohex** [comment]
https://github.com/prassee/prassee-emacs-theme/pull/3

`custom-theme-load-path` setting is missing. Please check above PR.

**Comment by prassee** [comment]
@syohex this is my very first theme for emacs and most of the code has been taken from other theme code hence I could not shape this to the conventions expected.  Thanks for sending the PR its been merged. I hope now it can be merged here as well.

**Comment by syohex** [comment]
Merged.

**Pull request merged**
