### PR TITLE
Added recipe for lsp-docker

### PR DESCRIPTION
**Pull request by rnikoopour**
### Brief summary of what the package does
This package runs language servers in a docker container instead of the host

### Direct link to the package repository
https://github.com/emacs-lsp/lsp-docker

### Your association with the package
Maintainer

### Relevant communications with the upstream package maintainer
None needed

### Checklist
Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```
 lsp-dock…     1   1 error           package.el cannot parse this buffer: Search failed: ";;; Lsp-docker.el ends here" (emacs-lisp-package)
 lsp-dock…    56   1 warning         Unused lexical argument ‘docker-image-id’ (emacs-lisp)
 lsp-doc…    56   1 warning         Unused lexical argument ‘path-mappings’ (emacs-lisp)
 lsp-doc…   149   1 warning         the function ‘lsp-docker-launch-new-container’ is not known to be defined. (emacs-lisp)
```

**Comment by conao3** [comment]
This is bad idea I think. Why are you such a customize?

```emacs-lisp
;; Local Variables:
;; flycheck-disabled-checkers: (emacs-lisp-checkdoc)
;; End:
```
https://github.com/emacs-lsp/lsp-docker/blob/1f18e264365a681b1af2ee6f5e48fe7ca4327f0b/lsp-docker.el#L147

**Comment by rnikoopour** [comment]
Thank you for the feedback @conao3!  

I removed 
```
;; Local Variables:
;; flycheck-disabled-checkers: (emacs-lisp-checkdoc)
;; End:
```

When I run `checkdoc` I get:
```
Buffer comments and tags:  Ok
Documentation style:       Ok
Message/Query text style:  Ok
Unwanted Spaces:           Ok
```

And when I run `package-lint-current-buffer` inside `lsp-docker.el` I get:
```
No issues found.

```
How are you generating the warnings you shared?  

The above changes are pending PR here: https://github.com/emacs-lsp/lsp-docker/pull/14

**Comment by conao3** [comment]
Thanks your improvement!

I think, no docstring `cl-defun` does not warn you to add a docstirng, but I think you need to add it like a normal `defun`.

And would you like add dosctring to the defun surrounded by let.
(But must this be a `let`?
I think we can use global variables in the context of Elisp. You defining closures ...?)

---

This is out of topic, but my comments from flycheck warning.
`C-c ! v` shows me below information
```
Syntax checkers for buffer lsp-docker.el in emacs-lisp-mode:

First checker to run:

  emacs-lisp
    - may enable:    yes
    - predicate:     t
    - executable:    Found at /home/conao/.local/bin/emacs
    - next checkers: emacs-lisp-checkdoc, emacs-lisp-package

Checkers that may run as part of the first checker's chain:

  emacs-lisp-package
    - may enable: yes

Checkers that are compatible with this mode, but will not run until properly configured:

  emacs-lisp-checkdoc (disabled)
    - may enable:    Automatically disabled!
    - executable:    Found at /home/conao/.local/bin/emacs
    - next checkers: emacs-lisp-package

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20191126.2142)
Emacs version:    26.3
System:           x86_64-pc-linux-gnu
Window system:    x
```

**Comment by rnikoopour** [comment]
I'll have an update later this week for the feedback! Won't be able to get to it tonight.

I used the closure because I didn't want to add another `defvar` but I will go ahead and change it to a `defvar` with the `lsp-docker` prefix.

This is my output from `C-c ! v`:
```
Syntax checkers for buffer lsp-docker.el in emacs-lisp-mode:

First checker to run:

  emacs-lisp
    - may enable:    yes
    - predicate:     t
    - executable:    Found at /Applications/Emacs.app/Contents/MacOS/Emacs-x86_64-10_14
    - next checkers: emacs-lisp-checkdoc

Checkers that are compatible with this mode, but will not run until properly configured:

  emacs-lisp-checkdoc (disabled)
    - may enable: Automatically disabled!
    - executable: Found at /Applications/Emacs.app/Contents/MacOS/Emacs-x86_64-10_14

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20191126.2142)
Emacs version:    26.3
System:           x86_64-apple-darwin18.2.0
Window system:    ns
```

It looks like I'm missing `emacs-lisp-package`. Could that be the cause for the different output?

**Comment by conao3** [comment]
Maybe. `emacs-lisp-package` is avairable as `flycheck-package` in MELPA ([repo](https://github.com/purcell/flycheck-package))

**Comment by riscy** [comment]
Looks great!  And welcome to MELPA. :)

(I notice you've got a combination of spaces and tab/spaces used for indents; either is fine, but mixing them may be worth avoiding down the road).

**Pull request merged**
