### PR TITLE
adding recipe for emacs-todoist

### PR DESCRIPTION
**Pull request by abrochard**
### Brief summary of what the package does

interface for todoist.com task tracking

### Direct link to the package repository

https://github.com/abrochard/emacs-todoist

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them - ahah

### CODE REVIEW

**Comment by abrochard** [comment]
Hi @riscy thank you for the feedback! I'll tackle this asap.

**Comment by abrochard** [comment]
I just pushed a few commits:

- `url-http-end-of-headers` is defined in the `url-http` package so I required it

**Comment by purcell** [comment]
Thanks! Looks good, and I'll merge it now. Couple of little notes along the way:

- Prefer `string-equal` in cases like [this](https://github.com/abrochard/emacs-todoist/blob/c56a0b0e35f29b91453d9d3b5f58a919f5f6a08d/todoist.el#L80). Also when one branch explicitly returns `nil`, I personally find it clearer to use `unless` or `when`.
- `dolist` would be even clearer than `mapc` [here](https://github.com/abrochard/emacs-todoist/blob/c56a0b0e35f29b91453d9d3b5f58a919f5f6a08d/todoist.el#L336)

**Comment by abrochard** [comment]
Thank you! I'll tackle those asap :)

**Pull request merged**
