### PR TITLE
Add a recipe for org-inline-pdfcomment

### PR DESCRIPTION
**Pull request by swflint**
### Brief summary of what the package does

This package provides a simple way to export inline tasks as pdf comments.

### Direct link to the package repository

https://git.sr.ht/~swflint/org-inline-pdfcomment

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi Samuel,

This sounds very useful.  Have you considered contributing it upstream to Org?  Since `org-inlinetask` is built-in, it would seem like a natural addition.

**Comment by swflint** [comment]
I would *love* to, but I haven't been able to get my employer to complete their side of FSF copyright assignment (they seem to think it's not necessary).

**Comment by alphapapa** [comment]
As in, not necessary because it wouldn't benefit the company, or not necessary because you are free to contribute regardless?  If it's the latter, maybe you could talk to the FSF about it.  (Apologies if I'm rehashing things you've done.)

**Comment by swflint** [comment]
The latter.  I've talked to the FSF about it, as well as the technology transfer office and general counsel of my employer (a university).

**Comment by alphapapa** [comment]
I suppose NonGNU ELPA might be another option, if you wanted it to be installable out-of-the-box.

**Comment by swflint** [comment]
I've never submitted their, but I'd be interested in considering it.

**Comment by riscy** [comment]
Thanks both!  For now I think this is a welcome addition to MELPA.

**Pull request merged**
