### PR TITLE
Add recipe for seen-mode

### PR DESCRIPTION
**Pull request by shiorid**
### Brief summary of what the package does

This package provides a simple syntax highlighting mode for kepago scripts used in the RealLive engine.

### Direct link to the package repository

https://git.sr.ht/~shiorid/seen.el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Very quick first check:

package-lint (using version 20210127.158):
```
1 issue found:
1:0: error: package.el cannot parse this buffer: Search failed: ";;; seen.el ends here"
```
I believe this occurs because your summary line declares the file as "seen.el", but the file is called "seen-mode.el"

- Your `;;; Commentary` should appear underneath your license boilerplate, otherwise your license boilerplate will appear as part of the commentary in the MELPA index.  The builtin function `lm-commentary` can help check this
- seen-mode.el#L109: `progn` is not required at the top level here
- I think default Emacs attaches the .TXT extension to `change-log-mode`, which may be worth documenting in your `;;; Commentary` so users aren't surprised by the overwrite; also auto-mode-alist entries typically should end with `\\'`

**Comment by shiorid** [comment]
Thank you for your feedback, @riscy!
.TXT was being used for the testing framework, the right one is .ke.

The changes you requested were made.

**Comment by riscy** [comment]
Thanks!  A couple more quick things:

- Should you be deriving from `prog-mode` instead of `fundamental-mode`?  That way users who add special setup hooks to `prog-mode-hook` will also get their config applied when working in .ke files
- `"\'\\(.*\\)\'"` could be written `"'\\(.*\\)'"`

No blockers there, though, I think.  Welcome to MELPA! :)

**Comment by tarsius** [comment]
@nueshiorid the repository no longer exists or you made it private. Is it available somewhere else or should this package be removed?

**Pull request merged**
