### PR TITLE
Add ob-napkin recipe

### PR DESCRIPTION
**Pull request by pinetr2e**
### Brief summary of what the package does
A new org-babel source code block support for Napkin tool, which can generate sequence diagram from Python script.

### Direct link to the package repository

https://github.com/pinetr2e/ob-napkin

### Your association with the package

Maintainer of this package.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
I have package-lint (using version 20200419.406):
```
7 issues found:
6:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
45:0: error: "org-babel-napkin-command" doesn't start with package's prefix "ob-napkin".
50:0: error: "org-babel-napkin-plantuml-server-url" doesn't start with package's prefix "ob-napkin".
60:0: error: "org-babel-napkin-out-file" doesn't start with package's prefix "ob-napkin".
65:0: error: "org-babel-expand-body:napkin" doesn't start with package's prefix "ob-napkin".
65:0: error: `org-babel-expand-body:napkin' contains a non-standard separator `:', use hyphens instead (see Elisp Coding Conventions).
94:1: warning: `eval-after-load' is for use in configurations, and should rarely be used in packages.
```
I understand org-babel have their own conventions about prefixes, but the `standard keywords` one is legitimate.

Normally simply loading packages should not alter Emacs's behavior.  But I think the `eval-after-load` isn't a problem in this small instance.  Still, I think it may be a good idea to add a function called `ob-napkin-unload-function` so that unloading the feature actually cleans up after itself (see the help on `unload-feature` to see how this works).

**Comment by pinetr2e** [comment]
First of all, thanks for your comments.
I knew the lint tool warned those but I kind of ignored as all the similar packages(org-babel related) I checked in MELPA were written like that.

Now, I fixed both issues by adding 'tool' as standard keywords and I also simply removed the eval-after-load as the package has "requires 'ob" at the beginning which which exports org-src-lang-modes symbol.

This is my first commit to MELPA and Please let me know if I need to do more.

**Comment by riscy** [comment]
> I also could not find examples of doing that in other org-babel packages.

Here's how I'd do it, in case you're curious:
```
(defun ob-napkin-unload-function ()
  "Pre-cleanup when `unload-feature' is called."
  ;; delete the items we've added to org-src-lang-modes:
  (delete '("napkin" . python) org-src-lang-modes)
  (delete '("napkin-puml" . python) org-src-lang-modes)
  ;; return nil to continue standard unloading:
  nil)
```
but I won't block on it.

I'm also currently seeing
byte-compile (using Emacs 26.3):
```
ob-napkin.el:99:1:Warning: Unused lexical argument `params'
```
This is easy to silence, however -- just name the variable `_params` instead.  That's minor enough, though.

Thanks, and welcome to MELPA!

**Comment by pinetr2e** [comment]
Thank you very much for your review and the nice advice as well.
I will fix as you suggested.

**Pull request merged**
