### PR TITLE
Add recipe for outline-indent

### PR DESCRIPTION
**Pull request by jamescherti**
### Brief summary of what the package does

The `outline-indent.el` Emacs package provides a minor mode for Emacs that enables **code folding and outlining based on indentation levels**.

The `outline-indent.el` leverages the built-in outline-minor-mode to automatically detect and fold sections according to their indentation hierarchy. The built-in outline-minor-mode enables utilizing functions such as demote, move indented blocks up, and move indented blocks down, significantly enhancing the editing experience for indented text. These functions are invaluable for restructuring and reorganizing content within indented sections.

### Direct link to the package repository

https://github.com/jamescherti/outline-indent.el

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I noticed you've got other PR(s) already open #9103 #9104.  To split my review time evenly between authors, I try to do one PR at a time per author, but I promise I'll get to this when we resolve earlier PRs.

**Comment by jamescherti** [comment]
Thank you for letting me know. I'll look forward to your feedback once the earlier PRs are resolved.

**Comment by jamescherti** [comment]
In addition to code folding, `outline-indent.el` can now move indented subtrees up and down, demote and promote (indent/unindent) sections to adjust indentation levels, change the ellipsis, and insert a new line with the same indentation level as the current line to add a new indented block.

**Comment by riscy** [comment]
Thanks!  Looks good to go.  I'm noticing my own emacs init.el has rudimentary code that is similar in concept for a couple of programming languages - I think this is a good idea and better executed here.

**Comment by jamescherti** [comment]
Thank you for merging `outline-indent.el`! 

(I'm glad to hear that you find the approach well-executed. This will provide a good alternative to `origami.el` and `yafolding` on MELPA, which are no longer maintained, slow, and have known bugs. There was no other reliable way to fold indented code, which is why I developed `outline-indent.el`.)

**Pull request merged**
