### PR TITLE
Add transliterate-devanagari

### PR DESCRIPTION
**Pull request by grettke**
### Brief summary of what the package does

Transliterate ASCII 1-9 to their Unicode Devanagari equivalent.

### Direct link to the package repository

https://github.com/grettke/transliterate-devanagari

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

NA

### Checklist

- [X] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [X] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

Summary: Transliterate ASCII 1-9 to their Unicode Devanagari equivalent.
Link: https://github.com/grettke/transliterate-devanagari
Association: Maintainer

Build:

gcr@vela:~/git/github/melpa⮞ make recipes/transliterate-devanagari
 • Building recipe transliterate-devanagari ...
emacs --no-site-file --batch -l package-build/package-build.el --eval "(let ((package-build-stable nil) (package-build-write-melpa-badge-images t) (package-build-archive-dir (expand-file-name \"./packages\" package-build--melpa-base))) (package-build-archive 'transliterate-devanagari))"

;;; transliterate-devanagari

Fetcher: github
Source: grettke/transliterate-devanagari

Cloning https://github.com/grettke/transliterate-devanagari.git to /Users/gcr/git/github/melpa/working/transliterate-devanagari/
Saving file /Users/gcr/git/github/melpa/packages/transliterate-devanagari-20161109.2058.el...
Wrote /Users/gcr/git/github/melpa/packages/transliterate-devanagari-20161109.2058.el
Wrote /Users/gcr/git/github/melpa/packages/transliterate-devanagari-readme.txt
File: /Users/gcr/git/github/melpa/packages/transliterate-devanagari-20161109.2058.entry
Built transliterate-devanagari in 0.685s, finished at Wed Nov  9 21:11:28 2016
 ✓ Wrote 8 -rw-r--r--  1 gcr  staff   1.7K Nov  9 21:11 ./packages/transliterate-devanagari-20161109.2058.el
8 -rw-r--r--  1 gcr  staff   238B Nov  9 21:11 ./packages/transliterate-devanagari-20161109.2058.entry
8 -rw-r--r--  1 gcr  staff   754B Nov  9 21:11 ./packages/transliterate-devanagari-badge.svg
8 -rw-r--r--  1 gcr  staff    64B Nov  9 21:11 ./packages/transliterate-devanagari-readme.txt
 Sleeping for 0 ...
sleep 0

Install:

Generating autoloads for transliterate-devanagari.el...done
Saving file /Users/gcr/.emacs.d/elpa/transliterate-devanagari-20161109.2058/transliterate-devanagari-autoloads.el...
Wrote /Users/gcr/.emacs.d/elpa/transliterate-devanagari-20161109.2058/transliterate-devanagari-autoloads.el
(No changes need to be saved)
(No files need saving)
Checking /Users/gcr/.emacs.d/elpa/transliterate-devanagari-20161109.2058... [2 times]
Showing all blocks ... done
Compiling /Users/gcr/.emacs.d/elpa/transliterate-devanagari-20161109.2058/transliterate-devanagari-pkg.el...done
Wrote /Users/gcr/.emacs.d/elpa/transliterate-devanagari-20161109.2058/transliterate-devanagari-pkg.elc
Checking /Users/gcr/.emacs.d/elpa/transliterate-devanagari-20161109.2058...
Compiling /Users/gcr/.emacs.d/elpa/transliterate-devanagari-20161109.2058/transliterate-devanagari.el...done
Wrote /Users/gcr/.emacs.d/elpa/transliterate-devanagari-20161109.2058/transliterate-devanagari.elc
Checking /Users/gcr/.emacs.d/elpa/transliterate-devanagari-20161109.2058...

### CODE REVIEW

**Comment by Fanael** [comment]
This looks like an input method, so why is it an minor mode and not [an actual input method](https://www.gnu.org/software/emacs/manual/html_node/emacs/Select-Input-Method.html)? Like this:

```emacs-lisp
(require 'quail)

(quail-define-package
 "devanagari-digits" "" "dng" t
 ""
 nil t t nil t nil nil nil nil nil t)

(quail-define-rules
 ("0" "०")
 ("1" "१")
 ("2" "२")
 ("3" "३")
 ("4" "४")
 ("5" "५")
 ("6" "६")
 ("7" "७")
 ("8" "८")
 ("9" "९"))
```

Actually, this is not even needed: Emacs already ships with several Devanagari input methods, all of which cover not only the digits, but also the actual abugida.

**Comment by grettke** [comment]
> This looks like an input method, so why is it an minor mode and not an actual input method?

@Fanael Because I wasn't familiar with input methods :) 

Gotcha and thanks for the link.

**Comment by purcell** [comment]
@grettke are your `fraktur-mode` and `blackboard-bold-mode` the same sort of package? If so, perhaps they'd be worth updating to be input methods.

**Comment by grettke** [comment]
@purcell Good question. 

I was confused about the intersection of an input system and transliteration so I read the documentation on [Input Methods](https://www.gnu.org/software/emacs/manual/html_node/emacs/Input-Methods.html#Input-Methods) and the Wikipedia pages on [Translation](https://en.wikipedia.org/wiki/Translation), [Transcription](https://en.wikipedia.org/wiki/Transcription_(linguistics)) and [Transliteration](https://en.wikipedia.org/wiki/Transliteration). 

Translation attempts to map the words with the same _meaning_ between one language to another. It is subjective. Neither input methods and the two packages I wrote do that.

Transcription lets you _input_ text in one writing system using another writing system. Input methods do this but the two packages I wrote do not. This devanagari package that I wrote was a mistake since it 1) it wasn't implemented as an input method and 2) it duplicated an existing input method.

Transliteration _converts characters in the same system_ from one script to another. Just the characters not the meaning or for input into another text system. For example converting Roman letters from one Roman script (ASCII) into Fraktur or Blackboard bold. Input methods don't do this but those two packages that I wrote do this. 

Here are [two](https://books.google.com/books?id=ospMAgAAQBAJ&pg=PA767&lpg=PA767&dq=fraktur+transliterate&source=bl&ots=9cNxqljTbt&sig=9NvB9nZuY8jmFkyLOkeQjhBc_XI&hl=en&sa=X&ved=0ahUKEwiR_Oi6o73QAhVI5yYKHSacA9wQ6AEISjAI#v=onepage&q=fraktur%20transliterate&f=false) [examples](http://www.omniglot.com/writing/braille.htm) of how transliteration is used. Fraktur made sense to me but Braille did not make sense to me. After reading the page it made sense because Braille represents Roman letters so you can transliterate ASCII (a-z and A-Z and 0-9) to Braille characters. That is why the two packages that I wrote are correctly transliteration. 

Morse code would make sense for transliteration from ASCII to Unicode. Probably Braille too then.

Should those two packages I wrote be converted Quail? No because they are not Input methods if I understand correctly.

**Comment by purcell** [comment]
I'm happy either way, and don't have an opinion, so I just wanted to raise the question. :-)

**Pull request closed without merging**
