### PR TITLE
Add js-react-redux-yasnippets

### PR DESCRIPTION
**Pull request by sooqua**
### Brief summary of what the package does

React-Native/React/Redux Yasnippets for es6/es7

### Direct link to the package repository

https://github.com/sooqua/js-react-redux-yasnippets

### Your association with the package

An enthusiastic user

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x ] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x ] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x ] My elisp byte-compiles cleanly
- [x ] `M-x checkdoc` is happy with my docstrings
- [x ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
`:url` is redundant; please remove that.

**Comment by sooqua** [comment]
Done

**Comment by mattiasb** [comment]
Maybe the package name should reflect that it's for redux and react etc and not just for ES7?

**Comment by sooqua** [comment]
Yeah, I didn't think on the name much. Renamed to js-react-redux-yasnippets. Hope this doesn't break everything.

**Comment by riscy** [comment]
I'd also say you're the maintainer of this project, not just a mere user. :)  Here's a quick pass through the checklist:

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
```
Warning (emacs): 
js-react-redux-yasnippets.el:34: All variables and subroutines might as well have a documentation string
Warning (emacs): 
js-react-redux-yasnippets.el:43: First sentence should end with punctuation
Warning (emacs): 
js-react-redux-yasnippets.el:49: First sentence should end with punctuation
Warning (emacs): 
js-react-redux-yasnippets.el:56: All interactive functions should have documentation
```

<kbd>M-x package-lint-current-buffer</kbd> (using version 20190707.1456):
```
4 issues found:

1:76: warning: You should depend on (emacs "24") if you need lexical-binding.
58:17: error: You should depend on (emacs "24.3") if you need `file-name-base'.
61:1: error: You should depend on (emacs "24.4") if you need `with-eval-after-load'.
61:21: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
js-react-redux-yasnippets.el:30:7:Warning: assignment to free variable
    `js-react-redux-yasnippets-dir'

In js-react-redux-yasnippets-initialize:
js-react-redux-yasnippets.el:34:52:Warning: reference to free variable
    `js-react-redux-yasnippets-dir'
js-react-redux-yasnippets.el:39:7:Warning: assignment to free variable
    `js-react-redux-yasnippets-want-semicolon'

In js-react-redux-yasnippets-toggle-semicolon:
js-react-redux-yasnippets.el:51:9:Warning: assignment to free variable
    `js-react-redux-yasnippets-toggle-semicolon'
```

Added miscellaneous hints (automated):
- js-react-redux-yasnippets.el#L21: Prefer `https` over `http` (if possible)

**Comment by sooqua** [comment]
Fixed whatever I could.

**Comment by riscy** [comment]
Thanks!  I'm able to take a deeper look now.  Bearing in mind I'm not a frequent yasnippet user, so please forgive any oversights below:

I see a lot of autoload that may be unnecessary, unless I'm missing something.  See [when to autoload](https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html#When-to-Autoload).  I believe only your initialize function and eval-after-load block needs to be autoloaded?

It's typical to gather your `defvar`s at the top of the file (e.g. this one [here](https://github.com/sooqua/js-react-redux-yasnippets/blob/c3818c554389ab7e994d135483293721da14bc2d/js-react-redux-yasnippets.el#L41)).  Moreover, it feels like `js-react-redux-yasnippets-want-semicolon` should be a `defcustom`?

[This check](https://github.com/sooqua/js-react-redux-yasnippets/blob/c3818c554389ab7e994d135483293721da14bc2d/js-react-redux-yasnippets.el#L37) seems redundant since we `(require 'yasnippet)`, which will already ensure that variable is bound.

Checking whether a variable that you defined yourself is bound ([here](https://github.com/sooqua/js-react-redux-yasnippets/blob/c3818c554389ab7e994d135483293721da14bc2d/js-react-redux-yasnippets.el#L46), [here](https://github.com/sooqua/js-react-redux-yasnippets/blob/c3818c554389ab7e994d135483293721da14bc2d/js-react-redux-yasnippets.el#L54)) seems unnecessary, unless I'm missing something.

It may be useful to add something to the commentary in [this](https://github.com/sooqua/js-react-redux-yasnippets/blob/c3818c554389ab7e994d135483293721da14bc2d/js-react-redux-yasnippets.el#L43-L47) function to let users know that the function is used within the snippets (at first I thought it was an orphan).  Similarly with `js-react-redux-yasnippets-filename-base`.

**Comment by sooqua** [comment]
Aaaand done! Thanks for the help :+1:

**Comment by riscy** [comment]
Looks like a compiler error -- check out the documentation on [defcustom](https://www.gnu.org/software/emacs/manual/html_node/eintr/defcustom.html).

**Comment by sooqua** [comment]
I fixed it but, can I get some help? I'm using Doom Emacs, which is now using straight.el and I get this error:
```
File mode specification error: (file-missing Opening directory No such file or directory
/home/sooqua/.emacs.d/.local/straight/build/js-react-redux-yasnippets/snippets)
```
Because snippets are located in
```
/home/sooqua/.emacs.d/.local/straight/repos/js-react-redux-yasnippets/snippets
```
How do I specify the correct path?

**Comment by sooqua** [comment]
Nvm, figured it out. The .el file is symlinked to /repos/ path so I used this to get the real path:
```elisp
(defvar js-react-redux-yasnippets-dir
  (file-name-directory
   (file-truename (concat (file-name-sans-extension load-file-name) ".el"))))
```

**Comment by riscy** [comment]
Nice, this looks like it's making good progress.  For this:
```elisp
(defvar js-react-redux-yasnippets-dir
  (file-name-directory
   (file-truename (concat (file-name-sans-extension load-file-name) ".el"))))
```
This feels like it might be excessive - for example, yasnippet just uses:
```elisp
(defconst yas--loaddir
  (file-name-directory (or load-file-name buffer-file-name))
  "Directory that yasnippet was loaded from.")
```
Note that the `(or load-file-name buffer-file-name)` is important because it handles the case where a developer is trying to evaluate the buffer (load-file-name may not exist).

One quick fix here:
<kbd>M-x byte-compile-file</kbd> (using Emacs 26.2):
```
js-react-redux-yasnippets.el:80:1:Warning: the function `yas-load-directory'
    is not known to be defined.
```
You can just add `(require 'yasnippet)` to the top of your code section.

**Comment by sooqua** [comment]
> This feels like it might be excessive

But I had to do this because if the package is byte-compiled (as in my case with Doom Emacs), the `load-file-name` returns path to `.elc` file, which is not sym-linked to the correct directory where the `snippets` directory is located, which leads to an error. Again, Doom Emacs is using `straight.el` as it's package manager and that project is still young, maybe they will start sym-linking `elc` files at some point or come up with other solution, but for now this is the only fix I can think of on my side.

> You can just add `(require 'yasnippet)` to the top of your code section.

It has been there until the last commit, then I removed it because it was underlined red in my buffer, like it can't find yasnippet, although it's installed. And every upgrade I was getting an error and I had to remove the `.emacs.d/.local/straight/repos/js-react-redux-yasnippets` and `.emacs.d/.local/straight/build/js-react-redux-yasnippets` folders. I will look into ways I can fix this, but this is just a warning anyway, the `eval-after-load 'yasnippet` will ensure that function is defined.

**Comment by riscy** [comment]
> but for now this is the only fix I can think of on my side.

When people install your package from MELPA, they'll have the `.el` file but they'll also have the `.elc` file -- so everything should work as expected.  Are you running into issues because you don't have an `.elc` file locally?  In that case you can <kbd>M-x byte-compile-file</kbd> and you'll be good to go.  I'll also underline this point:

> Note that the (or load-file-name buffer-file-name) is important

----------

>  I will look into ways I can fix this, but this is just a warning anyway, the eval-after-load 'yasnippet will ensure that function is defined.

Thanks - I don't have the bandwidth to be super helpful this weekend, but every compile warning we knock out at this phase is one people won't have to see (and possibly be worried about) when they're installing your package onto their machine.  Often a compiler warning is all we get when there's an actual error, as well, so it's good personal practice not to get used to seeing any warnings (imo).

**Comment by sooqua** [comment]
> they'll also have the `.elc` file -- so everything should work as expected. Are you running into issues because you don't have an `.elc` file locally

Sorry, my English is not very good. I don't know how to explain this better but let me try one more time.

1. I **do** have the `.elc` file


- _~/.emacs.d/.local/straight/**build**/js-react-redux-yasnippets/js-react-redux-yasnippets.el_
- is symlinked to
- _~/.emacs.d/.local/straight/**repos**/js-react-redux-yasnippets/js-react-redux-yasnippets.el_

The **repos/js-react-redux-yasnippets** folder contains the `snippets` dir, but there is no `build/js-react-redux-yasnippets/snippets`  


However the `.elc` file:

- _~/.emacs.d/.local/straight/**build**/js-react-redux-yasnippets/js-react-redux-yasnippets.el**c**_ (which is exactly the file that is being loaded, not `js-react-redux-yasnippets.el`)
- is _**not**_ symlinked to
- _~/.emacs.d/.local/straight/**repos**/js-react-redux-yasnippets/js-react-redux-yasnippets.el**c**_ (there is no such file)

Now you see, the only way for me to get to the **repos/js-react-redux-yasnippet/snippets** directory is to follow the symlinked **.el** file using that code.

As for `(require 'yasnippet)`, I already added it, just forgot to edit the post. My bad. I also opened an [issue](https://github.com/hlissner/doom-snippets/issues/9) for the error I'm getting because of it.

As for `buffer-file-name`, it's done.

**Comment by sooqua** [comment]
Found another fix in Doom Emacs' files (using `:files`)
```elisp
(package! js-react-redux-yasnippets
  :recipe (:host github
                 :repo "sooqua/js-react-redux-yasnippets"
                 :files ("*.el" "snippets")))
```

**Comment by riscy** [comment]
Great. I believe this is looking ready to merge.  Thank you for your patience. And, of course, welcome to MELPA! :)

**Pull request merged**
