### PR TITLE
Add neil recipe

### PR DESCRIPTION
**Pull request by borkdude**
### Brief summary of what the package does

Neil is a (babashka) script that can add useful stuff to a Clojure project, like adding a dependency to a `deps.edn` file, etc.
The emacs integrations helps finding Clojure libraries and can automatically update the `deps.edn` file.

### Direct link to the package repository

https://github.com/babashka/neil

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thank you for this -- the main thing that I think needs to be done here is to add a formal license/identifier to the source file, e.g. consider an [SPDX-License-Identifier](https://spdx.dev/ids/) for the MIT license.

Minor stuff (non-blocking):
- The word `Emacs` in the package summary isn't necessary
- suppliying -> supplying
- "When t," in some of the docstrings should probably technically be "When non-nil,"

**Comment by borkdude** [comment]
@riscy Addressed feedback

**Comment by riscy** [comment]
This triggered a package-lint (we try to keep all of the summary lines in the index capitalized when it makes sense) -- fyi:

`neil.el` with package-lint 20220412.1648:
```
1 issue found:
1:0: warning: The package summary should start with an uppercase letter or a digit.
```

This'll be a quick merge right after.  Sorry about all the back and forth.

**Comment by riscy** [comment]
Actually there's no point in stalling this on account of that. :)

**Pull request merged**
