### PR TITLE
Add Recipe for terraform-docs

### PR DESCRIPTION
**Pull request by loispostula**
### Brief summary of what the package does

Integrate terraform-docs with Emacs 

### Direct link to the package repository

https://github.com/loispostula/terraform-docs.el

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

None Needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Code looks mostly good but I notice you are using manual quoting, e.g. `" --output-file=\"\""` before sending a string to the shell.  You should use `shell-quote-argument` instead (because, for example, filenames can indeed include quotation marks and potentially other shell control characters in them).

**Comment by riscy** [comment]
(Actually I take back my sentence about manual quoting - I see what's going on here now.  But I think the point re: `shell-quote-argument` still stands.)

**Comment by loispostula** [comment]
@riscy thanks for the review, as it's to quote `""` there aren't much difference, but it's indeed better with `shell-quote-argument` i've adapted the code :)

**Comment by riscy** [comment]
I am remiss for not pointing this out earlier, but have you seen https://melpa.org/#/terraform-doc ?  Do you know what the differences might be?

**Comment by loispostula** [comment]
Hi @riscy, I've seen it, that package allows you to navigate or open existing terraform documentation of published provider or module on the fly.

This package allows you to call `terraform-docs` and generate documentation from Emacs. So same domain but different part of the process

**Comment by riscy** [comment]
Ah I see now.

I feel like this package (and that) have dangerously similar names!  Yours is also only summarized as "Integrate terraform-docs"; I'd guess people who are familiar with `terraform-docs` wouldn't be (too?) confused, but I think it would help users if your summary said "Generate Terraform modules documentation" or similar.  This would clarify that *your* package is about the generating side of things.

I will tag @TxGVNN here for awareness.

I'll merge for now, but please *do* consider adjusting your summary line to reduce confusion.

**Comment by loispostula** [comment]
Thanks @riscy I've adapted the description in the repo https://github.com/loispostula/terraform-docs.el/compare/lp/nit-doc?expand=1

**Comment by TxGVNN** [comment]
Thanks @riscy for awareness. I've thought I forgot to add `s` ending into terraform-doc package. :joy: 

After looking `terraform-docs` I see this package provide docs by using command line tool instead of getting from website on fly that `terraform-doc` is doing. Both of them are useful. 

Other hand, `terraform-mode` has the docs lookup feature too.  https://github.com/TxGVNN/terraform-doc/issues/4 Perhaps integrating to terraform-mode is the best way for users.

Anyway, that's Emacs.  Users should select the style that best suits their needs.

**Pull request merged**
