### PR TITLE
Add CLEDE recipe

### PR DESCRIPTION
**Pull request by Sasanidas**
### Brief summary of what the package does

Common Lisp Emacs Development Environment (CLEDE) is a collection of utilities and tools for a better CL Emacs experience.

### Direct link to the package repository

https://gitlab.com/sasanidas/clede

### Your association with the package

I am the maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  I think this recipe as-is will distribute the README.org files as well, which MELPA generally excludes.  Maybe we should finetune this recipe to match the defaults?  Beyond that, here's a quick first pass --

`clede-commands.el` with package-lint 20221003.1636:
```
1 issue found:
11:0: error: Package-Requires outside the main file have no effect.
```

`clede-highlight.el` with byte-compile using Emacs 28.1:
```
clede-highlight.el:129:31: Warning: defcustom for
    `global-clede-highlight-minor-mode' fails to specify containing group
clede-highlight.el:129:31: Warning: defcustom for
    `global-clede-highlight-minor-mode' fails to specify containing group
In end of data:
clede-highlight.el:55:24: Warning: the function
    `clede-semantic-util-get-let-context' is not known to be defined.
```

`clede-highlight.el` with package-lint 20221003.1636:
```
1 issue found:
11:0: error: Package-Requires outside the main file have no effect.
```

`clede-highlight.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- clede-highlight.el#L112: It's safer to sharp-quote function names; use `#'`
```

`clede-lisp-interface.el` with byte-compile using Emacs 28.1:
```
clede-lisp-interface.el:72:50: Warning: reference to free variable `command'
```

`clede-lisp-interface.el` with package-lint 20221003.1636:
```
1 issue found:
11:0: error: Package-Requires outside the main file have no effect.
```

`clede-reader.el` with byte-compile using Emacs 28.1:
```
clede-reader.el:93:8: Warning: docstring wider than 80 characters
```

`clede-reader.el` with package-lint 20221003.1636:
```
3 issues found:
11:0: error: Package-Requires outside the main file have no effect.
53:0: error: "*clede-reader-orig-read*" doesn't start with package's prefix "clede".
58:0: error: "*clede-reader-macro-chars*" doesn't start with package's prefix "clede".
```

`clede-refactor.el` with package-lint 20221003.1636:
```
1 issue found:
11:0: error: Package-Requires outside the main file have no effect.
```

`clede-semantic-util.el` with package-lint 20221003.1636:
```
2 issues found:
11:0: error: Package-Requires outside the main file have no effect.
91:7: error: You should depend on (emacs "27.1") if you need `ignore-error'.
```

`clede-semantic.el` with package-lint 20221003.1636:
```
5 issues found:
11:0: error: Package-Requires outside the main file have no effect.
380:7: error: You should depend on (emacs "27.1") if you need `mode-local--overload-docstring-extension'.
521:6: warning: Closing parens should not be wrapped onto new lines.
664:6: warning: Closing parens should not be wrapped onto new lines.
683:4: warning: Closing parens should not be wrapped onto new lines.
```

`clede-semantic.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- clede-semantic.el#L291: It's safer to sharp-quote function names; use `#'`
```

`clede.el` with byte-compile using Emacs 28.1:
```
clede.el:72:20: Warning: Use keywords rather than deprecated positional
    arguments to `define-minor-mode'
```

`clede.el` with checkdoc 0.6.2:
```
clede.el:76: Documentation strings should not start or end with whitespace
```

`clede.el` with package-lint 20221003.1636:
```
1 issue found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
```

Stderr output while compiling/loading:
```
clede.el: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode'
```

**Comment by riscy** [comment]
The earmuffs are (as far as I'm aware) nonstandard in Emacs lisp, although I know some other lisps make use of them.  Generally I'd suggest sticking with package-lint's feedback in this one, if at all possible.

I'm a bit sick so rushing a little bit (apologies for the brevity) but here's the latest --

`clede-highlight.el` with byte-compile using Emacs 28.1:
```
clede-highlight.el:55:24: Warning: the function
    `clede-semantic-util-get-let-context' is not known to be defined.
```

`clede-reader.el` with package-lint 20221003.1636:
```
2 issues found:
52:0: error: "*clede-reader-orig-read*" doesn't start with package's prefix "clede".
57:0: error: "*clede-reader-macro-chars*" doesn't start with package's prefix "clede".
```
(As touched on above)

`clede-refactor.el` with byte-compile using Emacs 28.1:
```
clede-refactor.el:43:1: Warning: defcustom for `clede-refactor-interactive'
    fails to specify type
clede-refactor.el:43:1: Warning: defcustom for `clede-refactor-interactive'
    fails to specify type
clede-refactor.el:111:1: Warning: attempt to let-bind constant `:location'
clede-refactor.el:111:1: Warning: attempt to let-bind constant `:file'
clede-refactor.el:111:1: Warning: attempt to let-bind constant `:position'
clede-refactor.el:111:1: Warning: attempt to let-bind constant `:snippet'
In clede-refactor--clean-references:
clede-refactor.el:122:25: Warning: Unused lexical variable `snip'
In clede-refactor--refactor-symbol:
clede-refactor.el:135:54: Warning: reference to free variable `word'
In end of data:
clede-refactor.el:135:48: Warning: the function `group' is not known to be
    defined.
clede-refactor.el:100:8: Warning: the function `sly-eval' is not known to be
    defined.
```

`clede-semantic.el` with byte-compile using Emacs 28.1:
```
clede-semantic.el:380:12: Warning: `overload-docstring-extension' is an
    obsolete function (as of 27.1); use
    `mode-local--overload-docstring-extension' instead.
```

`clede-semantic.el` with package-lint 20221003.1636:
```
1 issue found:
382:2: error: You should depend on (emacs "27.1") if you need `mode-local--overload-docstring-extension'.
```

`clede.el` with package-lint 20221003.1636:
```
1 issue found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
```

**Comment by Sasanidas** [comment]
Hello @riscy , thanks for the check
Im cheking before if sly is loaded, so I don't call the function when it's not present
```
clede-refactor.el:100:8: Warning: the function `sly-eval' is not known to be
    defined.
```

```
(if (fboundp 'sly)
      (sly-eval
       `(slynk:xref ',type ',symbol))
   (error "This commands requires `sly' to work"))
```


Similar with the last problem, I'm checking the Emacs version and calling the correct function in each case
```
1 issue found:
382:2: error: You should depend on (emacs "27.1") if you need `mode-local--overload-docstring-extension'.
```

```
(if (version< emacs-version "27.1")
	  (funcall 'overload-docstring-extension
		   (intern (semantic-tag-name tag)))
	(funcall 'mode-local--overload-docstring-extension
		 (intern (semantic-tag-name tag))))

```

I fixed the other small problems,

Regards

**Comment by riscy** [comment]
> I don't call the function when it's not present

I see - you can mark these with `declare-function` to let the byte-compiler know that you're aware they might not have been declared when `sly` hasn't been explicitly brought in.  The deprecation warnings can't be helped, but I'd recommend just moving onto Emacs 27.1 in the future, which is already a couple of years old.

I'm noticing some issues about your recipe, which you can see interpreted in the build:
```
    clede.el -> clede.el
    cl-integration/README.org -> cl-integration/README.org
    cl-integration/asdf => cl-integration/asdf
    cl-integration/fiveam => cl-integration/fiveam
    el-integration/README.org -> el-integration/README.org
    el-integration/clede-lisp-interface.el -> el-integration/clede-lisp-interface.el
    el-integration/inferior-lisp => el-integration/inferior-lisp
    el-integration/slime => el-integration/slime
    el-integration/sly => el-integration/sly
    semantic/clede-reader.el -> semantic/clede-reader.el
    semantic/clede-semantic-util.el -> semantic/clede-semantic-util.el
    semantic/clede-semantic.el -> semantic/clede-semantic.el
    semantic/examples => semantic/examples
    utilities/README.org -> utilities/README.org
    utilities/clede-commands.el -> utilities/clede-commands.el
    utilities/clede-highlight.el -> utilities/clede-highlight.el
    utilities/clede-refactor.el -> utilities/clede-refactor.el
```
The use of wildcards is including README.org files -- we usually avoid distributing those unless there's a specific reason to.  Also, you'll notice that some elisp files (cl-integration/asdf/clede-asdf.el, cl-integration/fiveam/clede-fiveam.el, el-integration/slime/clede-slime.el) aren't being specifically detected as elisp source files.  I believe this means they won't appear on the user's load path.  This also meant I wasn't running the linters on those files, and for example clede-asdf.el includes this line: `(require 'clede-lisp-interface)` which appears to not be available with this package.

**Comment by riscy** [comment]
I've marked this awaiting-upstream for now, but feel free to reach out.

**Comment by Sasanidas** [comment]
Umm I'm not sure how to keep the directory structure but exclude the .org files.

Aside from this issue, I'm adding some files to the load-path

```
;; Add subdirectories to the load-path
(let ((default-directory
	(if load-file-name
	    (file-name-directory load-file-name)
	  (file-name-directory (buffer-file-name)))))
  (normal-top-level-add-subdirs-to-load-path))

```

So it shouldn't be a problem

**Comment by riscy** [comment]
> I'm adding the files in the subdirectories to the load-path

I see the form you're referring to in clede.el, where you're invoking `(normal-top-level-add-subdirs-to-load-path)`.  I feel that modifying the load-path should be left to package managers and users.  Let me make a suggestion to modify your recipe as follows:
```elisp
(clede
 :repo "sasanidas/clede"
 :fetcher gitlab
 :files (:defaults
         "utilities/*.el"
         ("semantic" "semantic/*")
         ("cl-integration" "cl-integration/*/*")
         ("el-integration" "el-integration/*" "el-integration/*/*")))
```
This uses `:defaults` which gives you a preferred ruleset (and thus includes clede.el); it brings in all of your utilities, and it preserves the directory structure for your example files.  Altogether the directory tree would look like this for users:
```
.
├── cl-integration
│   └── fiveam
│       └── examples
│           ├── clos_example.lisp
│           ├── example.fasl
│           ├── example.lisp
│           ├── fiveam.lisp
│           └── misc.lisp
├── clede-asdf.el
├── clede-commands.el
├── clede-fiveam.el
├── clede-highlight.el
├── clede-inf-lisp.el
├── clede-lisp-interface.el
├── clede-reader.el
├── clede-refactor.el
├── clede-semantic-util.el
├── clede-semantic.el
├── clede-slime.el
├── clede-sly.el
├── clede.el
├── el-integration
│   ├── inferior-lisp
│   │   └── clede-inf-lisp.el
│   ├── slime
│   │   └── clede-slime.el
│   └── sly
│       └── clede-sly.el
└── semantic
    └── examples
        └── example
            └── reader-example.lisp
```
with all of the elisp files accounted for on the load-path -- thus no modifying the user's load-path required at import-time.

-----------------

When I use this recipe, package-build is able to detect all of your elisp files and I can see the following:

`clede-asdf.el` with package-lint 20230315.1052:
```
1 issue found:
11:0: error: Package-Requires outside the main file have no effect.
```
Not a big deal.

`clede-asdf.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- clede-asdf.el#L50: It's safer to sharp-quote function names; use `#'`
```

`clede-fiveam.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- clede-fiveam.el#L54: It's safer to sharp-quote function names; use `#'`
- clede-fiveam.el#L65: It's safer to sharp-quote function names; use `#'`
```

`clede-inf-lisp.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- clede-inf-lisp.el#L95: Consider `beginning-of-line`
- clede-inf-lisp.el#L99: Consider `end-of-line`
```

`clede-refactor.el` with byte-compile using Emacs 28.1:
```
clede-refactor.el:101:8: Warning: the function `sly-eval' is not known to be
    defined.
```

`clede-semantic.el` with byte-compile using Emacs 28.1:
```
clede-semantic.el:380:21: Warning: `overload-docstring-extension' is an
    obsolete function (as of 27.1); use
    `mode-local--overload-docstring-extension' instead.
```

`clede-semantic.el` with package-lint 20230315.1052:
```
1 issue found:
382:11: error: You should depend on (emacs "27.1") if you need `mode-local--overload-docstring-extension'.
```

`clede-semantic.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- clede-semantic.el#L380: It's safer to sharp-quote function names; use `#'`
- clede-semantic.el#L382: It's safer to sharp-quote function names; use `#'`
```

`clede-slime.el` with byte-compile using Emacs 28.1:
```
clede-slime.el:36:61: Warning: Unused lexical variable `slime-con'
In end of data:
clede-slime.el:56:23: Warning: the function `slime-eval' is not known to be
    defined.
clede-slime.el:50:10: Warning: the function `slime-repl-return' is not known
    to be defined.
clede-slime.el:45:48: Warning: the function `slime-connection' is not known to
    be defined.
clede-slime.el:45:27: Warning: the function `slime-repl-buffer' is not known
    to be defined.
```


`clede-sly.el` with byte-compile using Emacs 28.1:
```
clede-sly.el:62:21: Warning: reference to free variable
    `sly-default-connection'
In end of data:
clede-sly.el:69:10: Warning: the function `sly-mrepl-return' is not known to
    be defined.
clede-sly.el:63:25: Warning: the function `sly-buffer-name' is not known to be
    defined.
clede-sly.el:48:34: Warning: the function `sly-eval' is not known to be
    defined.
clede-sly.el:48:16: Warning: the function `sly-message' is not known to be
    defined.
```

**Comment by riscy** [comment]
Apologies, my directory tree pasting above is probably redundantly listing some files -- this is an artifact of a bug in my own code, not package-lint.  I still think the suggested recipe is what we should be using, however.

**Comment by riscy** [comment]
I'll mark this awaiting-upstream again since it's been a month.  Feel free to reach out.

**Comment by progfolio** [comment]
The upstream repository for this package is archived.
@Sasanidas Is it safe to say this package submission can be closed?

**Pull request closed without merging**
