### PR TITLE
Add sakura theme

### PR DESCRIPTION
**Pull request by jasonm23**
### Brief summary of what the package does

Color theme

### Direct link to the package repository

https://github.com/emacsfodder/emacs-theme-sakura

### Your association with the package

Author

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Minor, but note this package-lint:
```
1:0: warning: Including "Emacs" in the package summary is usually redundant.
```
which I think applies here.

**Comment by jasonm23** [comment]
Agreed will fix

**Comment by riscy** [comment]
Here's the latest package-lint (I hate to sound like a nag :)

```
1:0: warning: The package summary should not end with a period.
1:0: warning: The package summary should start with an uppercase letter or a digit.
```

**Comment by riscy** [comment]
Looks like this was updated in the meantime - merging.

**Comment by jasonm23** [comment]
Thank you

**Pull request merged**
