### PR TITLE
Add speeddating recipe

### PR DESCRIPTION
**Pull request by xuchunyang**
### Brief summary of what the package does

Increase date and time at point. For example, there is a date `1999-12-31` and the point is on `31`, Increase it by one will change it into `2000-01-01`.

### Direct link to the package repository

https://github.com/xuchunyang/emacs-speeddating

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by xuchunyang** [comment]
I can't built my recipe or any other recipe. I suspect it is because a bug of package-build.el, see https://github.com/melpa/package-build/issues/14. I also notice a obvious bug:

https://github.com/melpa/melpa/blob/191ec704d37de2506f7feeaf16e3bb9ebadebe0f/package-build/package-build.el#L866

should be changed to

    (package-build--archive-file-name (assq (intern name) (package-build-archive-alist)))) 

because the key of the alist is symbol, not string.

**Comment by tarsius** [comment]
Thanks! I have pushed that fix.

**Comment by xuchunyang** [comment]
Thanks. Now I can build my recipe successfully.

**Comment by purcell** [comment]
Nice, thanks!

**Pull request merged**
