### PR TITLE
Add recipe for wiki-this

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Simply search in Wikipedia under point.

### Direct link to the package repository

https://github.com/jcs090218/wiki-this

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Suggestions:
- make the language customizable, but not the URL
- use `(interactive "r")` to make region specification more idiomatic
- use `(thing-at-point 'symbol)` so you can use this on e.g. `brother-in-law`
- use `(format ...)` instead of `concat` and various helper functions
- drop `(require 's)` - in fact wikipedia is happy to let you put whitespace in url's
- replace all whitespace , not just `" "`

Roughly something like this:
```elisp
(defvar wiki-this-url "https://%s.wikipedia.org/wiki/%s")
(defcustom wiki-this-language "en" "Language preference." :type 'string)
(defun wiki-this (&optional start end)
  "Open Wikipedia re: the point or from the region from START to END."
  (interactive "r")
  (let ((keyword (if (use-region-p)
                     (buffer-substring start end)
                   (thing-at-point 'symbol))))
    (if keyword
        (browse-url (format wiki-this-url wiki-this-language keyword))
      (message "Nothing to wiki!"))))
```

At that point this becomes quite a small package, albeit useful.  Maybe adding it to the MELPA package manager is overkill, but that's not for me to say.

**Comment by jcs090218** [comment]
@riscy Thank you for those suggestions! It really helps me polishing on lisp and elisp. Indeed, I know this is a small package, and still, this is a small package I often used and I think this could be useful to anyone like me. On the other hand, I think any wiki related actions can be add or expand to this package in the future.

**Comment by DamienCassou** [comment]
Please consider contributing to https://github.com/jozefg/wiki-summary.el instead.

**Comment by jcs090218** [comment]
@DamienCassou I did thought about that, but I do know if that require changing the package name or not. Anyway, I will at least try contact the current maintainer of the package `wiki-summary` and see what he thinks.

**Comment by alphapapa** [comment]
Yes, this package essentially boils down to this function:
```el
(defun wikipedia (term)
  (interactive (list (if (use-region-p)
                         (buffer-substring (region-beginning) (region-end))
                       (read-string "Term: " (thing-at-point 'word)))))
  (browse-url (format "https://wikipedia.org/wiki/%s" (url-hexify-string term))))
```
It should be easy to add that to another package.

**Comment by jcs090218** [comment]
I think I will at least wait until @jozefg get back to me because I do not repeatedly want to open and reopen this PR before seeing a clear direction for this functionality/package. :D

**Comment by alphapapa** [comment]
@jcs090218 What I mean is, we've already established that this shouldn't be a package of its own, because it's essentially just one function.  Even if jozefg doesn't respond, I'm sure you can find some package to contribute it to or another place to publish it, like /r/emacs or something.  So you can close this PR now.

**Comment by jcs090218** [comment]
Okay, since this is so much effort. I’m done.

**Pull request closed without merging**
