### PR TITLE
Added recipe for dir-treeview

### PR DESCRIPTION
**Pull request by tilmanrassy**
### Brief summary of what the package does

A file system navigator and simple file manager. 

* Displays the file system as a tree; subtrees can be folded and unfolded
* A click on a filename loads the file in Emacs
* A right-click opens a context menu with further actions
* Can open files by external programs or Lisp functions
* Can open terminal in directory
* Can copy, delete, and move files
* Works in text mode, too
* Supports file notifications
* Highly customizable
* Themable
* Ships with one theme called "pleasant" using Font Awesome icons

### Direct link to the package repository

https://github.com/tilmanrassy/emacs-dir-treeview

### Your association with the package

Maintainer, contributor (and an enthusiastic user ;-) )

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
I'll wait for the prerequisite package to be merged, but in the meantime:

- dir-treeview-pkg.el -- consider excluding; MELPA creates one

**Comment by tilmanrassy** [comment]
Hi @riscy, I removed dir-treeview-pkg.el from the repository. I also fixed some issues you found in my other package ("treeview") and which occurred in this one, too.

**Comment by riscy** [comment]
Quick pass with a few comments --

### dir-treeview-pleasant-theme.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
```
1 issue found:
1:0: error: There is no `provide' form.
```
You can silence this one by having this at the end of your file (although it is redundant, since `provide-theme` calls `provide` as well):
```
(provide-theme 'dir-treeview-pleasant)
(provide 'dir-treeview-pleasant-theme)
;;; dir-treeview-pleasant-theme.el ends here
```

Other possible lints:
- dir-treeview-pleasant-theme.el#L16: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### dir-treeview.el ###

byte-compile (using Emacs 27.1):
```
dir-treeview.el:1794:1:Warning: the following functions are not known to be
    defined: file-notify-rm-watch, file-notify-add-watch
```
These nags just need a `(require 'filenotify)` I believe, since it may not always be brought in at compile time.

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20200906.512):
- No issues!

Other possible lints:
- dir-treeview.el#L252: Quoting this lambda may prevent it from being compiled
- dir-treeview.el#L1789: It's safer to sharp-quote function names; use `#'`
- dir-treeview.el#L594: Consider `unless ...` instead of `when (not ...)`
- dir-treeview.el#L22: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

**Comment by tilmanrassy** [comment]
Hi @riscy , thank you for your feedback!

I fixed all issues you mentioned.

You were right with the `(require 'filenotify)`. I tested in an Emacs started with the `-q` flag (do not load init files), and byte-compiling complained about the lacking filenotify. Adding `(require 'filenotify)` fixed the problem.

I wondered why I didn't find the ``error: There is no ` provide' form`` myself. It turned out that I called `package-lint-current-buffer` with `package-lint-main-file` set to  `/path/to/dir-treeview-pkg.el`. For some reason it doesn't report the error under these circumstances. Anyway, I fixed the issue in the way you suggested, and it works.

**Comment by riscy** [comment]
Looks good here, thanks!

A quick glance at package-lint suggests it relaxes a lot of checks when `package-lint-main-file` is defined and isn't the file it's checking, so that's definitely what's going on there.  Although maybe it should have complained about the file not existing...

**Comment by tilmanrassy** [comment]
Thank you very much! :-)

**Pull request merged**
