### PR TITLE
Add recipe for latex-auto-activating-snippets

### PR DESCRIPTION
**Pull request by tecosaur**
### Brief summary of what the package does

Make use of the auto-activating-snippets engine to provide an expansive collection of LaTeX snippets. Primarily covering: operators, symbols, accents, subscripts, and a few fraction forms.

### Direct link to the package

https://github.com/tecosaur/LaTeX-auto-activating-snippets

### Your association with the package

Conceptual author*, contributor.
\* _someone else did the brunt of the work_.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
  - not sure what to do about the prefix complaints, I'd silence them if I knew how
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

#### Note

Requires https://github.com/melpa/melpa/pull/7330 to be merged first.

### CODE REVIEW

**Comment by ymarco** [comment]
Suffers from the same prefix issues in `auto-activating-snippets` #7330, having `latex-auto-activating-snippets` shortened to `laas`.

**Comment by riscy** [comment]
This looks like a useful resource, and thanks for accommodating with the rename.   Below is a quick pass -


### laas.el ###

byte-compile (using Emacs 27.1):
```
laas.el:26:1:Error: Cannot open load file: No such file or directory, texmathp
```

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210127.158):
- No issues!

Since this package adds two hooks to `LaTeX-mode` most likely it should be wrapped up in a minor mode that can be toggled off and on.  Users could be instructed to put `(add-hook 'LaTeX-mode-hook #'laas-mode)` in their config.

The hack to get around smartparens is pretty neat.  Obviously the author is more familiar with the issue than I am, but the workaround seems a very risky since it means _none_ of the post-insert-hooks will run on this iteration, which could potentially break other packages that are trying to maintain state.  The other drawback is that it is tightly coupled to the smartparens-mode implementation.  I'm not sure if there is a better answer, but it might be more robust to look backward and just check for mismatched parentheses, maybe adding a warning for the user to see.

**Comment by ymarco** [comment]
> byte-compile (using Emacs 27.1):
> ```
> laas.el:26:1:Error: Cannot open load file: No such file or directory, texmathp
> ```

I thought texmathp was a built-in library in Emacs, turns out it's in auctex. I added auctex as a dependency, should be fixed now.

> Since this package adds two hooks to `LaTeX-mode` most likely it should be wrapped up in a minor mode that can be toggled off and on.  Users could be instructed to put `(add-hook 'LaTeX-mode-hook #'laas-mode)` in their config.

I guess I can do that.

> The hack to get around smartparens is pretty neat.  Obviously the author is more familiar with the issue than I am, but the workaround seems a very risky since it means _none_ of the post-insert-hooks will run on this iteration, which could potentially break other packages that are trying to maintain state.

Yeah. I refactored it to only play around with moving sp--post-self-insert-hook-handler. Should theoretically break less things.

>  The other drawback is that it is tightly coupled to the smartparens-mode implementation.  I'm not sure if there is a better answer, but it might be more robust to look backward and just check for mismatched parentheses, maybe adding a warning for the user to see.

I think temporarily removing the hook is the best solution. Smartparens has other bugs that I'm afraid of, and and disabling the hook temporarily seems like the most bug-independant way.

**Comment by riscy** [comment]
In the latest I see:

### laas.el ###

byte-compile (using Emacs 27.1):
```
laas.el:413:1:Warning: the function `sp--post-self-insert-hook-handler' is not
    known to be defined.
```
so it's possible the latest version of smartparens doesn't have this function in it anymore -- I guess this is always the risk with relying on private functions.

checkdoc (using version 0.6.2):
```
Warning (emacs): 
laas.el:151: All variables and subroutines might as well have a documentation string
```
(Minor, but fyi)

**Comment by ymarco** [comment]
>   laas.el:413:1:Warning: the function `sp--post-self-insert-hook-handler' is not
>       known to be defined.
> so it's possible the latest version of smartparens doesn't have this function in it anymore -- I guess this is always the risk with relying on private functions.
Sandboxed byte compilation would warn about this being undefined
regardless, no? I'll add a declare-function. laas--shut-up-smartparens
should no-op in case the hook isn't there, so it's fine either way. I do
need to check if only the name changed though.

> checkdoc (using version 0.6.2):
>   Warning (emacs):
>   laas.el:151: All variables and subroutines might as well have a documentation string
> (Minor, but fyi)
Fixed.

**Comment by riscy** [comment]
> [regarding creating a minor mode] I guess I can do that. (EDIT: done that)

I wonder if this change hasn't been merged yet -- it seems the package is still adding a hook when it's loaded in.

> Sandboxed byte compilation would warn about this being undefined regardless, no?

You're right, and this is what happened in that case.  My apologies -- my mistake to suggest it wasn't in smartparens anymore.  Let me know when that `declare-function` is ready too.

**Comment by ymarco** [comment]
Forgot to push, sorry. Should be up now.

**Comment by riscy** [comment]
Thanks!  I see the minor mode now.  I quickly checked that the top level add-hooks were removed and ended up giving this block a closer look:
```elisp
(add-hook 'LaTeX-mode-hook
          (defun laas-add-space-after-expand-h ()
            "Hook intelligent space insertion onto snippet expansion."
            (add-hook 'aas-post-snippet-expand-hook
                      #'laas-current-snippet-insert-post-space-if-wanted
                      nil t)))
```
and I'm a bit confused -- why is this function being defined (and frequently redefined) inside a hook, rather than just defined at the top level?  I also couldn't see this function being used anywhere, unless there is some kind of metaprogramming from `aas` going on that I'm unaware of.

In any case, I apologize for all the round trips.  This is close. :)

**Comment by ymarco** [comment]
> I quickly checked that the top level add-hooks were removed and ended up giving this block a closer look:
>   (add-hook 'LaTeX-mode-hook
>             (defun laas-add-space-after-expand-h ()
>               "Hook intelligent space insertion onto snippet expansion."
>               (add-hook 'aas-post-snippet-expand-hook
>                         #'laas-current-snippet-insert-post-space-if-wanted
>                         nil t)))
> ```
> and I'm a bit confused -- why is this function being defined (and frequently redefined) inside a hook, rather than just defined at the top level?  I also couldn't see this function being used anywhere, unless there is some kind of metaprogramming from `aas` going on that I'm unaware of.

The defun is evaluated only once. It's equivalent to

  (defun laas-add-space-after-expand-h () ...)
  (add-hook '... #'laas-add-space-after-expand-h)

Essentially giving it a name to make it easier to remove from the hook.
Perhaps It should be hooked to laas-mode rather than LaTeX-mode now.

**Comment by riscy** [comment]
I think I disagree on it being equivalent but I may be missing something.  In any case whenever the user enters latex-mode, the functions in `LaTeX-mode-hook` will be run, so the `defun` will be rerun every time the user enters latex-mode.

> Perhaps It should be hooked to laas-mode rather than LaTeX-mode now.

Probably this makes sense, although in that case it doesn't need to be a hook anymore, does it?

**Comment by riscy** [comment]
Oh, never mind.  I see now that the `defun` is returning a function of course.

**Comment by ymarco** [comment]
> Probably this makes sense, although in that case it doesn't need to be a hook anymore, does it?
No, I still want a way for users to disable it.

**Comment by riscy** [comment]
> No, I still want a way for users to disable it.

You could create a customizable boolean flag that the mode checks.  It could be true by default.  This way people's latex-mode hooks aren't modified simply by loading your package.

**Comment by ymarco** [comment]
> You could create a customizable boolean flag that the mode checks.  It could be true by default.  This way people's latex-mode hooks aren't modified simply by loading your package.
Yeah, done. That seems like the simplest solution.

**Comment by riscy** [comment]
Looks good -- thanks both.

**Pull request merged**
