### PR TITLE
Add recipe for mise

### PR DESCRIPTION
**Pull request by liuyinz**
### Brief summary of what the package does

A development envrionment manager for cli tool `mise`, another replacement for  `direnv`

### Direct link to the package repository

https://github.com/liuyinz/mise.el

### Your association with the package

creater/maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- minor stuff fyi, but no blockers:

- mise.el#L132: It's safer to sharp-quote function names; use `#'`
- mise.el#L164: It's safer to sharp-quote function names; use `#'`

**Comment by astoff** [comment]
@liuyinz Just FYI, using [this package](https://github.com/astoff/buffer-env) and a small amount of configuration, one can recover the behavior of mise.el. Of course you can maintain your own package, especially if you plan to cover some mise-specific features.

**Comment by liuyinz** [comment]
@astoff wow, I will try that later

**Comment by riscy** [comment]
Thanks for that @astoff.  @liuyinz I think even just adding a "related work" to your README or Commentary could be helpful to users, in the case that we've stumbled into overlapping functionality in the index.

**Pull request merged**
