### PR TITLE
Add recipe for dashboard-ls.

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Display list of files or directories in current directory on Dashboard.

### Direct link to the package repository

https://github.com/jcs-elpa/dashboard-ls

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
The name should probably be something like `dashboard-current-directory`.  When I look at `dashboard-current`, my first thought is, "Current what?"

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please resolve below package-lint/check-doc/byte-compiler warnings
```diff
new file   Cask
@@ -0,0 +1,4 @@
+(source gnu)
+(source melpa)
+
+(package-file "dashboard-current.el")
```

```
Loading package information... done
Package operations: 3 installs, 0 removals
  - Installing [ 1/3] f (0.20.0)... done
  - Installing [ 2/3] dashboard (1.2.5)... done
  - Installing [ 3/3] emacs (24.3)... already present
Compiling /home/conao/dev/forks/dashboard-current/dashboard-current.el...

In end of data:
dashboard-current.el:79:1:Warning: the following functions are not known to be
    defined: all-the-icons-icon-for-dir, all-the-icons-octicon,
    all-the-icons-icon-for-file
```

**Comment by jcs090218** [comment]
>The name should probably be something like dashboard-current-directory. When I look at dashboard-current, my first thought is, "Current what?"

@alphapapa Yes, I do have issue with the name. Please give me a suggestion with something shorter. I want to name the package with shorter name. Thanks!

@conao3 I think those warnings are from `dashboard.el` and not from my package! Thanks!

**Comment by purcell** [comment]
> Please give me a suggestion with something shorter. I want to name the package with shorter name

How about `dashboard-ls`?

Looks good to me otherwise.

**Comment by jcs090218** [comment]
@purcell Name changed! Thanks! :)

**Comment by purcell** [comment]
Great, merged - thanks.

**Pull request merged**
