### PR TITLE
Add recipe for js-auto-format-mode

### PR DESCRIPTION
**Pull request by ybiquitous**
### Brief summary of what the package does

Emacs minor mode for auto-formatting JavaScript code. After saving JavaScript file, its' code will be formatted automatically.

By default, this package uses [ESLint](https://eslint.org/), but it can customize any formatters such as [Prettier](https://github.com/prettier/prettier).

### Direct link to the package repository

https://github.com/ybiquitous/js-auto-format-mode

### Your association with the package

Author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Quick feedback:
- Since you're using the GPL, please use the standard boilerplate throughout, such that the license summary is embedded in the file itself. (Try `M-x auto-insert` in an empty `.el` file to see what I mean.)
- You should add a `defgroup` form to declare the `js-auto-format` customisation group and to place it in the overall customisation hierarchy by setting an appropriate parent group.
- Building shell commands [like this](https://github.com/ybiquitous/js-auto-format-mode/blob/a9edd9ad3aca88cf8f5da681dc3977bd541cdd8e/js-auto-format-mode.el#L53-L58) isn't safe, since your quoting will break if filenames contain certain characters, e.g. quotes (and, generally, spaces, backslashes etc.). Use `shell-quote-argument` to perform escaping/quoting for you.
- Rather than add special handling for the node_modules path, which is likely to lead to surprises, it would be preferable to keep things simple: let the user explicitly set their command to `npx prettier` if they like, or they can use [add-node-modules-path](https://github.com/codesuki/add-node-modules-path). I like that this module is simpler and more general than some of the related packages already in MELPA, so I feel like you should embrace the generality!

Hope that helps. :-)

**Comment by ybiquitous** [comment]
@purcell Thank you so much for detailed reviews! 😄 

I applied your all helpful feedbacks, then many diffs has been produced... 😓 
But I would be grateful if you would review code again! 🙏 

For details of changes, please see below:
https://github.com/ybiquitous/js-auto-format-mode/compare/a9edd9a...master

**Comment by purcell** [comment]
Looks good, thanks! Merging now. Welcome to MELPA!

**Comment by ybiquitous** [comment]
Thanks a lot! 😆

**Pull request merged**
