### PR TITLE
Add recipe for stylua

### PR DESCRIPTION
**Pull request by yuchunzhou**
### Brief summary of what the package does

Format lua code in Emacs

### Direct link to the package repository

https://github.com/yuchunzhou/stylua

### Your association with the package

Author and Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Very quick first pass --

`stylua.el` with package-lint 20221003.1636:
```
6 issues found:
1:0: warning: The package summary should not end with a period.
33:0: error: "lua-format-region" doesn't start with package's prefix "stylua".
38:3: error: You should depend on (emacs "25.1") if you need `if-let'.
43:15: error: You should depend on (emacs "24.4") if you need `string-empty-p'.
45:4: error: You should depend on (emacs "24.4") if you need `with-current-buffer-window'.
52:0: error: "lua-format-buffer" doesn't start with package's prefix "stylua".
```

**Comment by yuchunzhou** [comment]
> Thanks for this. Very quick first pass --
> 
> `stylua.el` with package-lint 20221003.1636:
> 
> ```
> 6 issues found:
> 1:0: warning: The package summary should not end with a period.
> 33:0: error: "lua-format-region" doesn't start with package's prefix "stylua".
> 38:3: error: You should depend on (emacs "25.1") if you need `if-let'.
> 43:15: error: You should depend on (emacs "24.4") if you need `string-empty-p'.
> 45:4: error: You should depend on (emacs "24.4") if you need `with-current-buffer-window'.
> 52:0: error: "lua-format-buffer" doesn't start with package's prefix "stylua".
> ```

**Comment by yuchunzhou** [comment]
Hi @riscy, i have fixed the issues, please review it again, thanks!

**Comment by riscy** [comment]
Thank you for accommodating!  One more lint popped up:

`stylua.el` with byte-compile using Emacs 28.1:
```
stylua.el:43:14: Warning: the function `string-empty-p' is not known to be
    defined.
```
which suggests this just needs a `(require 'subr-x)`.

However, with that out of the way, you may want to take a look at [reformatter](https://melpa.org/#/reformatter) as a dependency for this.  Using it will probably streamline your code, and I believe
```elisp
(erase-buffer) 
(insert output)
```
may be disruptive to the point, but correct me if I'm wrong.  See for example the [current implementation of reformatter-replace-buffer-contents-from-file](https://github.com/purcell/emacs-reformatter/blob/master/reformatter.el#L302) which mentions:
```elisp
  ;; While the function `replace-buffer-contents' exists in recent
  ;; Emacs versions, it exhibits pathologically slow behaviour in many
  ;; cases, and the simple replacement approach we use instead is well
  ;; proven and typically preserves point and markers to a reasonable
  ;; degree.
```

**Comment by yuchunzhou** [comment]
Hi @riscy, i had added the dependency for `string-empty-p` function, but i don't think [reformatter](https://melpa.org/#/reformatter) is suit for this package, because `reformatter` is for buffer save formatting, this package is just for those users who just want to format the code interactively.

**Comment by yuchunzhou** [comment]
@riscy , maybe i will add buffer save formatting in future.

**Comment by yuchunzhou** [comment]
Hi @riscy, i had added the dependency for `string-empty-p` function and remove the buffer erase code, but i don't use [reformatter](https://melpa.org/#/reformatter) for my package, please review it again.

**Comment by yuchunzhou** [comment]
Hi @riscy, i had added the dependency for `string-empty-p` function and remove the buffer erase code, but i don't use [reformatter](https://melpa.org/#/reformatter) for my package, please review it again.

**Comment by riscy** [comment]
I quickly tested this and it appears that it does not actually format the source code in the buffer, but instead creates a new buffer called `*stylua*` with the formatted contents there.  I think it's most useful if a code formatting package actually formats the code.

Beyond reformatter, you could take a look at how [blacken](https://melpa.org/#/blacken) works.  Notice it also comes with a minor-mode for formatting before saving, which I think is another crucial feature this package is missing.

**Pull request closed without merging**
