### PR TITLE
add recipe of company-manually

### PR DESCRIPTION
**Pull request by yanghaoxie**
### Brief summary of what the package does

[This package let you build your own candidate list manually .]

### Direct link to the package repository

https://github.com/yanghaoxie/company-manually

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer
 **None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks.  Here's a quick first pass.

### company-manually.el ###

byte-compile (using Emacs 26.3):
```
company-manually.el:51:1:Warning: Unused lexical argument `end'
company-manually.el:51:1:Warning: Unused lexical argument `start'
company-manually.el:65:1:Warning: Unused lexical argument `end'
company-manually.el:65:1:Warning: Unused lexical argument `start'
In company-manually-cdlatex-sub-superscript:
company-manually.el:137:12:Warning: reference to free variable
    `cdlatex-make-sub-superscript-roman-if-pressed-twice'
company-manually.el:145:21:Warning: reference to free variable
    `cdlatex-sub-super-scripts-outside-math-mode'
company-manually.el:147:62:Warning: reference to free variable
    `company-posframe-buffer'
In end of data:
company-manually.el:187:1:Warning: the following functions are not known to be
    defined: evil-exit-visual-state, cdlatex-number-of-backslashes-is-odd,
    texmathp, cdlatex-ensure-math, ivy-read, ivy-thing-at-point
```

checkdoc (using version 0.6.1):
```
Warning (emacs): 
company-manually.el:83: Disambiguate company-mode by preceding w/ function,command,variable,option or symbol.
Warning (emacs): 
company-manually.el:83: Argument `command' should appear (as COMMAND) in the doc string
```

package-lint (using version 20200616.2257):
- No issues!


### Loadability ###

Verifying ability to #'load each file:
```
Loading company-manually.el
company-manually.el:Error: Emacs 26.3 errored during load
Done.
```
Looks like loading this file immediately causes `(load company-manually-file)` to run, even if that file doesn't exist.

**Comment by yanghaoxie** [comment]
Thank you very much for your help. Followings are my point to point responses.

- byte-compile
  1. Corrected the function definition, and get rid of unused argument.
  2. Use `declare-function` to tell byte-compiler which file defines the functions.
  3. Use `defvar` to suppress `free variable` warnings.

- checkdoc
 1. I read other `company-backend`s's docstring, they have the same convention, e.f. for `company-capf` the docstring is
```
"`company-mode' backend using `completion-at-point-functions'."
```
So, I am kind of not sure how should I write the right docstring. Could you please give me some suggestions.

- Loadability
  1. Now `company-manually` load `company-manully-file` only if this file exists.

**Comment by riscy** [comment]
Regarding the checkdocs (which are minor, I wouldn't block on them): the ``` `' ``` quoting is actually to create hyperlinks in the Emacs online help (e.g. <kbd>M-x help</kbd>).  Since Emacs has no idea whether you mean to refer to the variable company-mode, the function company-mode, etc., it won't be able to create such a hyperlink, and so checkdoc is asking for disambiguation.   You can just use `''` (two apostophes) for quoting instead and avoid the issue entirely.

I'm looking closer at that function, and maybe you can clear up for me what `(interactive (list 'interactive))` does?  I'm unfamiliar with that pattern but I feel like I've seen it before.

**Comment by yanghaoxie** [comment]
- Thank you very much for your help.

- Thank you for your explaining. I found out that if I use `` `' ``, the document provided by `describ-function` presents a link which leads to the definition of `company-mode`. This feature losts if I use `''`. Another point I would like to point out is that there is another docstring issue which is the argument `command` is not in the docstring. However, other official docstrings from `company-mode` also have this issue, e.g. [company-capf](https://github.com/company-mode/company-mode/blob/1f56bec0ba7ce336eb8661b4d34e4b024d7dd04c/company-capf.el#L93), [company-abbrev](https://github.com/company-mode/company-mode/blob/1f56bec0ba7ce336eb8661b4d34e4b024d7dd04c/company-abbrev.el#L37). Therefore, maybe it is more preferable to be consistent with them.
- I actually copied this from official copany backend. I googled it a little, I think the following two blogs explain it very clearly.

   1. Blog explain `(interactive (list 'interactive))` http://ergoemacs.org/emacs/elisp_interactive_form.html.
   2. Blog explain why this is needed http://sixty-north.com/blog/writing-the-simplest-emacs-company-mode-backend.

**Pull request merged**
