### PR TITLE
Add recipe for org-randomnote.

### PR DESCRIPTION
**Pull request by mwfogleman**
### Brief summary of what the package does
Find a random note in your org-mode files

### Direct link to the package repository

https://github.com/mwfogleman/org-randomnote
### Your association with the package
Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mwfogleman** [comment]
Sorry, for the incomplete pull request - haven't submitted a MELPA pull request before! (Exciting!)

How do I make sure the package byte compiles cleanly? I can run byte-compile-file and that doesn't throw any errors (loudly).

Also need to have another look at the make instructions and package install files.

**Comment by mwfogleman** [comment]
I think this recipe should work - let me know if you see any problems or have any suggestions about the code.

**Comment by mwfogleman** [comment]
So, I'm not sure if the package installation is working or not.

**Comment by purcell** [comment]
Thanks! Recipe looks good. Quick feedback:
- `org-randomnote-f-empty?` would more conventionally be named `org-randomnote-f-empty-p`
- You should probably turn the declarations of `org-randomnote-candidates` and `org-randomnote-open-behavior` into `defcustom` forms, with an associated `defgroup`.

In any case, I'll go ahead and merge this now.

**Pull request merged**
