### PR TITLE
Add new recipe for flymake-swi-prolog

### PR DESCRIPTION
**Pull request by eshelyaron**
### Brief summary of what the package does

This package implements a simple Flymake backend for [SWI-Prolog](https://www.swi-prolog.org/), providing diagnostics about Prolog source code in `prolog-mode` buffers.
Under the hood, `flymake-swi-prolog` uses [diagnostics.pl](https://git.sr.ht/~eshel/diagnostics.pl), which is a tiny Prolog package I've written to expose the diagnosis performed by the SWI-Prolog built-in IDE.

### Direct link to the package repository

https://git.sr.ht/~eshel/flymake-swi-prolog

### Your association with the package

I am the author and maintainer of this package.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, and thanks for your close adherence to the checklist!

I think it's okay for `flymake-swi-prolog-ensure-backend` to install your own diagnostics.pl, but (unless I'm missing some nuance here) I'd rename that function to `flymake-swi-prolog-ensure-diagnostics-pl`.  In other words, I'm assuming swipl can work without your specific add-on installed, and there apparently is a [big list](https://www.swi-prolog.org/pack/list) of other add-ons for SWI Prolog that won't be receiving the same treatment.

**Comment by eshelyaron** [comment]
Thanks for the feedback, indeed I originally named the function `flymake-swi-prolog-ensure-diagnostics-pl`, but then decided to generalize the name to convey the function's intent, so that the name still fits even if in the future `flymake-swi-prolog` relies on something else than `diagnostics.pl`.

Anyway, I've changed it back to `flymake-swi-prolog-ensure-diagnostics-pl` for now (pushed).

**Comment by eshelyaron** [comment]
> Anyway, I've changed it back to flymake-swi-prolog-ensure-diagnostics-pl for now (pushed).

I realize I haven't pushed this change when writing that, sorry about that, _now_ I've pushed [the requested changed](https://git.sr.ht/~eshel/flymake-swi-prolog/commit/320977026816d275a3bafdcff7ff182c5eb7ff9b).

**Comment by riscy** [comment]
This looks good to me.  Thanks, and welcome to MELPA!

**Pull request merged**
