### PR TITLE
Add recipe `helm-qiita`

### PR DESCRIPTION
**Pull request by masutaka**
I want to add [`helm-qiita.el`](https://github.com/masutaka/emacs-helm-qiita). This is a helm interface for [Qiita](https://qiita.com/).

Qiita is a Japanese web service like a little http://stackoverflow.com/ .

Thanks :sparkles:

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Quick feedback:
- Please depend on the latest stable version of helm, not the snapshot version
- The `helm-qiita:` symbol prefix should be `helm-qiita-` in order to conform to the [elisp conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html)

**Comment by masutaka** [comment]
@purcell 

Thanks for your review. I've fixed.
https://github.com/masutaka/emacs-helm-qiita/blob/master/helm-qiita.el

**Comment by purcell** [comment]
Perfect, thanks! Merged. :-)

**Comment by masutaka** [comment]
Thanks a lot!

**Pull request merged**
