### PR TITLE
add tzc package

### PR DESCRIPTION
**Pull request by md-arif-shaikh**
### Brief summary of what the package does

`tzc` is a little tool to convert time between different timezones

### Direct link to the package repository
https://github.com/md-arif-shaikh/tzc

### Your association with the package

Author. Maintainer.

### Relevant communications with the upstream package maintainer
**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
On a very quick glance, have you had a chance to read about [Emacs's builtin handling of timezones](https://www.gnu.org/software/emacs/manual/html_node/calc/Time-Zones.html)?  E.g. calc-forms.el has a `calc-time-zone` function and a `math-tzone-names` variable that might be useful in implementing a package like this.  (I'll take a much closer for potential overlaps later -- this is just very quick feedback.)

Some minor stuff: I also notice a combination of camel case and kebab case, like `calcFunc-year` -- conventionally in elisp you would write `calc-func-year`.  And it looks like your use of the `error` function could be replaced with `user-error` so as not to unnecessarily open backtraces on the user.

**Comment by md-arif-shaikh** [comment]
Hi @riscy, thanks for these interesting comments. It seems that `calc-time-zone` takes as an argument a variable from the `math-tzone-names` which are the abbreviations for different time-zones like `CET` or `IST`. On the contrary, I was trying to avoid this and use the `tzdatabase` type time-zone names like `America/New_York` as described here https://www.gnu.org/software/emacs/manual/html_node/elisp/Time-Zone-Rules.html. I can perhaps support this type of time-zone name convention but I am not sure whether the `calc-time-zone` and `math-tzone-names` could replace the current implementations.

The camel case type function naming could be by mistake I will find that one and correct that. Also thanks for the suggestion for using `use-error` instead of `error`

**Comment by md-arif-shaikh** [comment]
I have replace `error` with `user-error` now. On the camelcase names, I think you might be referring to those that contains `timeshift`/`timestring`, I have now replaced those with `time-shift`/`time-string` etc

**Comment by riscy** [comment]
I browsed through the code and I think the timezone handling I mentioned is also specific to `calc` buffers, so there may not be nearly as much overlap as I thought.  I think all the code checks out -- useful package!

**Pull request merged**
