### PR TITLE
Fix version-regexps for inherit-local and nix-buffer

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by purcell** [comment]
Can you not just remove the version regexps altogether? Looks like the defaults would do the trick here, no?

**Comment by shlevy** [comment]
Ah, I didn't realize there is a default, what is it?

**Comment by purcell** [comment]
`"^[rRvV]?\\(.*\\)$"`

**Comment by shlevy** [comment]
@purcell Thanks, updated

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
