### PR TITLE
add recipe for tp

### PR DESCRIPTION
**Pull request by mooseyboots**
### Brief summary of what the package does

Provides utilities to make transient menus that make POST/PATCH/PUT requests.

Used by mastodon.el (in melpa) and fj.el.

### Direct link to the package repository

https://codeberg.org/martianh/tp.el

### Your association with the package

author

### Relevant communications with the upstream package maintainer

none

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass -

⸺ `tp.el` with byte-compile using Emacs 29.4:
```
tp.el:120:13: Warning: Unknown defun property `important-return-value'
```

Stderr output while compiling/loading:
```
tp.el: Warning: Unknown defun property `important-return-value'
```

⸺ Package and license:
- Add a GPL-compatible LICENSE file to the repository

**Comment by mooseyboots** [comment]
sorry about that. i've updated the repo now.

**Comment by mooseyboots** [comment]
hi, would it be poss for this to go through today? i did a few small clean up for it to go into ELPA, which is now has done.

**Comment by riscy** [comment]
No problem - it looks like the issues I've mentioned above are fixed now!

**Pull request merged**
