### PR TITLE
Add recipe for lsp-ivy

### PR DESCRIPTION
**Pull request by sebastiansturm**
### Brief summary of what the package does

`lsp-ivy` is the ivy counterpart to `helm-lsp`. It allows the user to interactively search for, and jump to, symbols offered by the underlying `lsp-mode` workspace

### Direct link to the package repository

https://github.com/emacs-lsp/lsp-ivy

### Your association with the package

maintainer

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback ~~(mostly, but package-lint keeps complaining about the empty Commentary section. May add some content if and when I can come up with something interesting to say)~~
- [x] My elisp byte-compiles cleanly ~~(mostly; there is one unused lexical argument within a lambda passed to `ivy-read` but I don't want to remove that without further testing and I won't do that today. If you wish to hold the PR until that is resolved, that's completely fine with me)~~ Edit: this has been fixed by a PR submitted by @abo-abo
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by sebastiansturm** [comment]
Hi, is there anything blocking inclusion of `lsp-ivy`? Anything I can do to improve the pull request?

**Comment by riscy** [comment]
> Hi, is there anything blocking inclusion of lsp-ivy

Sorry, there are a few other PR's being kept track of.

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191027.20):
```
1 issue found:

25:0: error: Package should have a non-empty ;;; Commentary section.
```
> May add some content if and when I can come up with something interesting to say

Why not the text from your repository? :)

> This package provides an interactive ivy interface to the workspace symbol functionality offered by lsp-mode. For an alternative implementation based on helm, see https://github.com/emacs-lsp/helm-lsp

**Comment by sebastiansturm** [comment]
ah yes, makes sense :) Thanks! I have updated `lsp-ivy.el` accordingly

**Comment by riscy** [comment]
Great, thanks.  Looks good!

**Comment by sebastiansturm** [comment]
thank you!

**Pull request merged**
