### PR TITLE
New package build

### PR DESCRIPTION
**Pull request by milkypostman**
want to pull a new package build but want @tarsius to give a quick look to see if this is going to be fun or not.

### CODE REVIEW

**Comment by milkypostman** [comment]
@tarsius this seems to have the homepage business in it. Didn't this break melpa last time?

**Comment by tarsius** [comment]
I think last time I tried to *remove* that code in favor of `lm-homepage`. This time around I just moved it into a separate function so that it is out of sight. ` package-build--lm-homepage` is a copy of `lm-homepage`. It differs from the removed inline code in that is uses the `lm-with-file` macro. We don't actually pass a file argument, so the only difference is that the buffer is temporarily widened and the search begins at the beginning of the buffer. Looks safe to me.

**Comment by tarsius** [comment]
But it looks like you will have to update mercurial:

```
Cloning https://bitbucket.org/zck/2048.el to /home/travis/build/melpa/melpa/working/2048-game/
Command '(env LC_ALL=C /usr/bin/timeout -k 60 600 hg clone https://bitbucket.org/zck/2048.el /home/travis/build/melpa/melpa/working/2048-game/)' exited with non-zero status 255: warning: connecting to bitbucket.org using legacy security technology (TLS 1.0); see https://mercurial-scm.org/wiki/SecureConnections for more info
abort: error: _ssl.c:510: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
```

**Comment by milkypostman** [comment]
That’s a Travis CI thing. Not sure how I fix what it’s instaling?

**Pull request closed without merging**
