### PR TITLE
Add package Chronometrist

### PR DESCRIPTION
**Pull request by contrapunctus-1**
### Brief summary of what the package does

A time tracker for Emacs with a nice interface and statistics/report displays.

### Direct link to the package repository

https://framagit.org/contrapunctus/chronometrist

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them
 
~(Working on the unchecked items.)~

### CODE REVIEW

**Comment by contrapunctus-1** [comment]
The build descriptor in *package-build-result* doesn't mention any dependencies, but the comment seems to imply that there should be dependency information in it. The package seems to install correctly in an Emacs run as `emacs -q -f 'package-initialize'`

**Comment by contrapunctus-1** [comment]
It's all set now, I think?

**Comment by riscy** [comment]
It looks like you're missing a `Package-Require` on `dash`.  Since this is a multifile package, package lint has a few extra complaints that don't apply### chronometrist-common.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-common.el:8:1:Error: Cannot open load file: No such file or directory, dash
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉



### chronometrist-custom.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
14:41: warning: Use variable `user-emacs-directory' or function `locate-user-emacs-file' instead of a literal path to the Emacs user directory or files.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉



### chronometrist-diary-view.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-diary-view.el:24:1:Error: Cannot open load file: No such file or directory, dash
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉



### chronometrist-events.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯


<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-events.el:6:1:Error: Cannot open load file: No such file or directory, dash
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉



### chronometrist-migrate.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
74:49: warning: Use variable `user-emacs-directory' or function `locate-user-emacs-file' instead of a literal path to the Emacs user directory or files.
76:47: warning: Use variable `user-emacs-directory' or function `locate-user-emacs-file' instead of a literal path to the Emacs user directory or files.
77:67: warning: Use variable `user-emacs-directory' or function `locate-user-emacs-file' instead of a literal path to the Emacs user directory or files.
78:45: warning: Use variable `user-emacs-directory' or function `locate-user-emacs-file' instead of a literal path to the Emacs user directory or files.
79:45: warning: Use variable `user-emacs-directory' or function `locate-user-emacs-file' instead of a literal path to the Emacs user directory or files.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-migrate.el:31:47:Warning: reference to free variable `it'

In chronometrist-migrate-check:
chronometrist-migrate.el:98:34:Warning: reference to free variable
    `chronometrist-file'

In end of data:
chronometrist-migrate.el:112:1:Warning: the following functions are not known
    to be defined: -->, chronometrist-format-time-iso8601,
    chronometrist-common-clear-buffer
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉



### chronometrist-plist-pp.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯


<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-plist-pp.el:31:12:Warning: sort called with 1 argument, but
    requires 2
chronometrist-plist-pp.el:32:12:Warning: `car' called with 0 args, but
    requires 1
chronometrist-plist-pp.el:32:12:Warning: car called with 0 arguments, but
    requires 1

In end of data:
chronometrist-plist-pp.el:93:1:Warning: the function `->' is not known to be
    defined.
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other static checks:
- chronometrist-plist-pp.el#L63: Consider `unless ...` instead of `when (not ...)`


### chronometrist-queries.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-queries.el:30:21:Warning: reverse called with 0 arguments, but
    requires 1
chronometrist-queries.el:22:37:Warning: `cdr' called with 0 args, but requires
    1
chronometrist-queries.el:22:37:Warning: cdr called with 0 arguments, but
    requires 1
chronometrist-queries.el:29:28:Warning: reverse called with 0 arguments, but
    requires 1
chronometrist-queries.el:33:15:Warning: cadr called with 0 arguments, but
    requires 1

In chronometrist-active-time-one-day:
chronometrist-queries.el:43:8:Warning: reference to free variable
    `chronometrist-task-list'
chronometrist-queries.el:44:48:Warning: reference to free variable `it'

In chronometrist-statistics-count-active-days:
chronometrist-queries.el:54:32:Warning: reference to free variable
    `chronometrist-events'

In chronometrist-task-events-in-day:
chronometrist-queries.el:73:29:Warning: reference to free variable
    `chronometrist-events'
chronometrist-queries.el:74:9:Warning: mapcar called with 1 argument, but
    requires 2
chronometrist-queries.el:77:9:Warning: seq-filter called with 1 argument, but
    requires 2

In end of data:
chronometrist-queries.el:83:1:Warning: the following functions are not known
    to be defined: chronometrist-date, ->, ->>,
    chronometrist-format-time-iso8601, chronometrist-events->time-list,
    chronometrist-time-list->sum-of-intervals, chronometrist-seconds-to-hms,
    --map, -reduce, chronometrist-time-add
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉



### chronometrist-report-custom.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯


<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉



### chronometrist-report.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯


<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-report.el:10:1:Error: Cannot open load file: No such file or directory, dash
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other static checks:
- chronometrist-report.el#L246: Consider `unless ...` instead of `when (not ...)`


### chronometrist-sexp.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯


<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-sexp.el:5:1:Error: Cannot open load file: No such file or directory, dash
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other static checks:
- chronometrist-sexp.el#L475: Consider `unless ...` instead of `when (not ...)`
- chronometrist-sexp.el#L476: Consider `unless ...` instead of `when (not ...)`


### chronometrist-statistics-custom.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
No byte-compilation issues! 😎

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉



### chronometrist-statistics.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-statistics.el:12:1:Error: Cannot open load file: No such file or directory, dash
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉

Other static checks:
- chronometrist-statistics.el#L277: Consider `unless ...` instead of `when (not ...)`


### chronometrist-time.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯


<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-time.el:6:1:Error: Cannot open load file: No such file or directory, dash
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉



### chronometrist-timer.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯


<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-timer.el:10:1:Error: Cannot open load file: No such file or directory, dash
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉



### chronometrist.el

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191124.132):
```
11 issues found:

1:0: warning: "Version:" or "Package-Version:" header is missing. MELPA will handle this, but other archives will not.
1:0: error: package.el cannot parse this buffer: Package lacks a "Version" or "Package-Version" header
1:76: warning: You should depend on (emacs "24") if you need lexical-binding.
8:10: error: You should depend on (emacs "24.4") if you need `filenotify'.
9:10: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-lib'.
10:10: error: You should depend on (emacs "24.4") if you need `subr-x'.
190:9: error: You should depend on (emacs "24.1") if you need `tabulated-list-print'.
288:3: error: You should depend on (emacs "24.1") if you need `tabulated-list-init-header'.
377:11: error: You should depend on (emacs "24.3") or the cl-lib package if you need `cl-case'.
402:24: error: You should depend on (emacs "24.4") if you need `hash-table-keys'.
410:19: error: You should depend on (emacs "24.4") if you need `file-notify-add-watch'.
```

<kbd>M-x byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist.el:12:1:Error: Cannot open load file: No such file or directory, dash
```

<kbd>M-x check-declare-file</kbd> (optional):
No issues! 🎉
, which I've tried to remove below:

**Comment by riscy** [comment]
> package-lint says I should depend on Emacs 24.1, which I've tried to declare in two places, to no effect.

Did something like this work in your top-matter?

> ;; Package-Requires: ((emacs "24.4"))

But I think you want 25.1 due to:

```
83:27: error: You should depend on (emacs "25.1") if you need `parse-iso8601-time-string'.
```

When in doubt, you can check out other packages on MELPA's source code (here's one of [my](https://github.com/riscy/shx-for-emacs/blob/master/shx.el) packages for example).

**Comment by contrapunctus-1** [comment]
@riscy thanks for all the pointers! I only recently gained access to a functioning computer again, working on your inputs.

**Comment by contrapunctus-1** [comment]
@riscy I've pushed fixes for most of the messages you pointed out, but I'm not sure why you mention the "Cannot open load file: No such file or directory, dash" errors or what I can do to make them go away.

**Comment by riscy** [comment]
> @riscy I've pushed fixes for most of the messages you pointed out, but I'm not sure why you mention the "Cannot open load file: No such file or directory, dash" errors or what I can do to make them go away.

It looks like framagit is down right now (hopefully this is just a temporary issue) but you need to add a version of dash to your `;; Package-Requires:`  line.

**Comment by riscy** [comment]
I can't check now, but ping when if/when you've done that (and framagit is back online) and I'll have another pass!

**Comment by contrapunctus-1** [comment]
Added and pushed

**Comment by riscy** [comment]
```
;; Package-Requires: ((emacs "25.1") (dash "2.16.0") (cl-lib "1.0") (seq "2.20"))
```
- Looks like this also needs `s`
- Since you depend on emacs > 24.3, I believe you don't need a require on cl-lib?  In any case the latest cl-lib is 0.6.1

When you add the `s` requirement I should be able to run some more checks.

**Comment by contrapunctus-1** [comment]
@riscy done.

**Comment by riscy** [comment]
Thank you for that!  Here's the remaining stuff that pops up:

### chronometrist-report.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-report.el:126:35:Warning: `mapcar' called for effect; use `mapc'
or `dolist' instead
```

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

(Skipping package-lint on this file)

Other static checks/suggestions:
- chronometrist-report.el#L246: Consider `unless ...` instead of `when (not ...)`
### chronometrist-sexp.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-sexp.el:257:12:Warning: `mapcar' called for effect; use `mapc'
or `dolist' instead
```

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

(Skipping package-lint on this file)

Other static checks/suggestions:
- chronometrist-sexp.el#L475: Consider `unless ...` instead of `when (not ...)`
- chronometrist-sexp.el#L476: Consider `unless ...` instead of `when (not ...)`
### chronometrist-statistics.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
- No issues! 💯

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

(Skipping package-lint on this file)

Other static checks/suggestions:
- chronometrist-statistics.el#L277: Consider `unless ...` instead of `when (not ...)`
### chronometrist-time.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-time.el:31:30:Warning: reference to free variable
`chronometrist-report-weekday-number-alist'
In chronometrist-number->day-of-week:
chronometrist-time.el:39:19:Warning: reference to free variable
`chronometrist-report-weekday-number-alist'
In end of data:
chronometrist-time.el:169:1:Warning: the function `chronometrist-day-start' is
not known to be defined.
```

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

(Skipping package-lint on this file)

### chronometrist-timer.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-timer.el:31:30:Warning: reference to free variable
`chronometrist-statistics-buffer-name'
```

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

(Skipping package-lint on this file)

### chronometrist.el
<kbd>byte-compile-file</kbd> (using Emacs 26.3):
- No issues! 💯

<kbd>M-x checkdoc</kbd> (using version 0.6.1):
- No issues! 💯

<kbd>M-x package-lint-current-buffer</kbd> (using version 20191220.419):
```
1 issue found:
1:0: warning: Including "Emacs" in the package summary is usually redundant.
```

**Comment by contrapunctus-1** [comment]
Pushed, thank you for your patience. The mapcar warnings really do seem to be false positives, though...right? 🤔

**Comment by riscy** [comment]
Woops, they may be!  I'll take a closer look soon.

**Comment by riscy** [comment]
Can you double check?

<kbd>byte-compile-file</kbd> (using Emacs 26.3):
```
chronometrist-common.el:12:1:Error: Recursive `require' for feature `chronometrist-time'
```

**Comment by contrapunctus-1** [comment]
Pushed a fix, please take a look.

**Comment by riscy** [comment]
I realize you'd mentioned the mapcars earlier up in this thread and I just lost track. :)  I've poked around with <kbd>emacs-lisp-macroexpand</kbd> and it looks like a false positive.  I need to dig into that warning a bit more to understand why it's being raised, but it's a non-blocker.

One last nag -- none of your source files contain any license boilerplate, which I'm now being a bit better about checking for.  Can you copy the first and perhaps second paragraph of the license as boilerplate: https://choosealicense.com/licenses/unlicense/ above the `;;; Commentary` section in all of your elisp files?

**Comment by contrapunctus-1** [comment]
Thanks for looking into it. I've added the license information.

**Comment by riscy** [comment]
I see what it is -- for example in chronometrist-report.el:
```elisp
    (--map (insert (chronometrist-date it) " ")
           (chronometrist-report-date->week-dates))
```
expands to...
```elisp
(mapcar
     (lambda
       (it)
       (insert
        (chronometrist-date it)
        " "))
     (chronometrist-report-date->week-dates))
```
which is what actually is calling mapcar for effect, although the byte-compiler was reporting a different line number!

**Comment by riscy** [comment]
You can silence the byte compiler in this case with e.g.
```elisp
    (mapconcat #'insert (--map (chronometrist-date it)
                               (chronometrist-report-date->week-dates)) " ")
```
assuming you still want to use dash.

**Comment by riscy** [comment]
(I'll mark this as awaiting since I think we have a path to a clean byte-compile now... :)  At least I believe!)

**Comment by contrapunctus-1** [comment]
@riscy done :slightly_smiling_face:

**Comment by riscy** [comment]
Hey, awesome.  This looks great to me.  And, welcome to MELPA!

**Pull request merged**
