### PR TITLE
Add recipe for flymake-rest

### PR DESCRIPTION
**Pull request by mohkale**
### Brief summary of what the package does

Provide helpers for replacing flycheck with flymake including a flycheck like error parser and several builtin checker definitions.

### Direct link to the package repository

https://github.com/mohkale/flymake-rest

### Your association with the package

Package Author.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

**Note**: I plan to complete these soon.

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [ ] `M-x checkdoc` is happy with my docstrings
- [ ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this -- this is just a very quick first pass over the checklist items.  I think most of the unused lexical variable warnings can be fixed by naming the variables e.g. `_file-name` and `_fmqd-context` for example.

### flymake-rest-awk-gawk.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-awk-gawk.el:33:1:Warning: Unused lexical variable `file-name'
flymake-rest-awk-gawk.el:33:1:Warning: Unused lexical variable `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-awk-gawk.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-clang.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-clang.el:40:1:Warning: Unused lexical variable `file-name'
flymake-rest-clang.el:40:1:Warning: Unused lexical variable `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-clang.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!

### flymake-rest-commands.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-commands.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-define.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-define.el:51: Open parenthesis in column 0 should be escaped
Warning (emacs): 
flymake-rest-define.el:75: Lisp symbol `standard-input' should appear in quotes
```

package-lint (using version 20210528.2348):
```
1 issue found:
35:0: warning: Private functions generally should not be autoloaded.
```


### flymake-rest-eslint.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-eslint.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-gcc.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-gcc.el:43:1:Warning: Unused lexical variable `file-name'
flymake-rest-gcc.el:43:1:Warning: Unused lexical variable `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-gcc.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-hook-use-package.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-hook-use-package.el:29:1:Error: Cannot open load file: No such file or directory, use-package-core
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-hook-use-package.el:0: You should have a section marked ";;; Commentary:"
Warning (emacs): 
flymake-rest-hook-use-package.el:40: All variables and subroutines might as well have a documentation string
Warning (emacs): 
flymake-rest-hook-use-package.el:43: All variables and subroutines might as well have a documentation string
```

package-lint (using version 20210528.2348):
```
4 issues found:
39:0: error: "use-package-normalize/:flymake-hook" doesn't start with package's prefix "flymake-rest".
39:0: error: `use-package-normalize/:flymake-hook' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
42:0: error: "use-package-handler/:flymake-hook" doesn't start with package's prefix "flymake-rest".
42:0: error: `use-package-handler/:flymake-hook' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
```


### flymake-rest-hook.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-hook.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-html-tidy.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-html-tidy.el:33:1:Warning: Unused lexical variable `file-name'
flymake-rest-html-tidy.el:33:1:Warning: Unused lexical variable `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-html-tidy.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-jq.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-jq.el:33:1:Warning: Unused lexical variable `file-name'
flymake-rest-jq.el:33:1:Warning: Unused lexical variable `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-jq.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-jsonlint.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-jsonlint.el:33:1:Warning: Unused lexical variable `file-name'
flymake-rest-jsonlint.el:33:1:Warning: Unused lexical variable `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-jsonlint.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-less.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-less.el:33:1:Warning: Unused lexical variable `file-name'
flymake-rest-less.el:33:1:Warning: Unused lexical variable `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-less.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!

### flymake-rest-markdownlint.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-markdownlint.el:38:1:Warning: Unused lexical variable `file-name'
flymake-rest-markdownlint.el:38:1:Warning: Unused lexical variable
    `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-markdownlint.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-mypy.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-mypy.el:33:1:Warning: Unused lexical variable `file-name'
flymake-rest-mypy.el:33:1:Warning: Unused lexical variable `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-mypy.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!

### flymake-rest-parse-enumerate.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-parse-enumerate.el:0: The first line should be of the form: ";;; package --- Summary"
Warning (emacs): 
flymake-rest-parse-enumerate.el:33: First line is not a complete sentence
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-parse-rx.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-proselint.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-proselint.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!

### flymake-rest-pycodestyle.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-pycodestyle.el:33:1:Warning: Unused lexical variable `file-name'
flymake-rest-pycodestyle.el:33:1:Warning: Unused lexical variable
    `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-pycodestyle.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-pylint.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-pylint.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-rubocop.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-rubocop.el:38:1:Warning: Unused lexical variable `file-name'
flymake-rest-rubocop.el:38:1:Warning: Unused lexical variable `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-rubocop.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-shellcheck.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-shellcheck.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest-xmllint.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-xmllint.el:33:1:Warning: Unused lexical variable `file-name'
flymake-rest-xmllint.el:33:1:Warning: Unused lexical variable `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-xmllint.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!

### flymake-rest-yamllint.el ###

byte-compile (using Emacs 27.1):
```
flymake-rest-yamllint.el:32:1:Warning: Unused lexical variable `file-name'
flymake-rest-yamllint.el:32:1:Warning: Unused lexical variable `fmqd-context'
```

checkdoc (using version 0.6.2):
```
Warning (emacs): 
flymake-rest-yamllint.el:0: You should have a section marked ";;; Commentary:"
```

package-lint (using version 20210528.2348):
- No issues!


### flymake-rest.el ###

byte-compile (using Emacs 27.1):
- No issues!

checkdoc (using version 0.6.2):
- No issues!

package-lint (using version 20210528.2348):
- No issues!

**Comment by mohkale** [comment]
@riscy 

Thanks for taking the time to review this PR.

> I think most of the unused lexical variable warnings can be fixed by naming the variables e.g. _file-name and _fmqd-context for example.

Those variables are actively used in some files for example `flymake-rest-pylint` uses `fmqd-context` through the `flymake-rest-parse-enumerate` macro. Correct me if I'm wrong but `_` is for variables that're never used, personally I think it'd be quite ugly to change where they're used to use `_fmqd-context` instead of `fmqd-context`. Thoughts?

**Comment by riscy** [comment]
That was a quick pass without looking too deeply at the code, but I'm having another look now.  And yeah, you're correct about that.  In fact, the byte-compiler would (also) complain if you used underscore-prefix variables since in some cases they _do_ get used.

I don't think we're completely stuck though.  The macros are beyond my reckoning at the moment, but it might be possible to rewrite them to only let-bind variables they're using.  Another alternative would be to e.g. `(defvar flymake-rest-fmqd-context nil)` at the top of the relevant file(s) which should pacify the byte-compiler.

**Comment by mohkale** [comment]
> The macros are beyond my reckoning at the moment, but it might be possible to rewrite them to only let-bind variables they're using.

That's already done in some places. For example when not using `:write-type 'file`, the temp-dir and temp-file variables are unassigned.

> Another alternative would be to e.g. (defvar flymake-rest-fmqd-context nil) at the top of the relevant file(s) which should pacify the byte-compiler.

That seems like the best approach. The macro was mostly adapted from `flymake-quickdef` and I kept the prefix as fmqd to simplify transitioning existing flymake packages that use flymake-quickdef into flymake-rest. I'll have to change the prefix to prevent the byte-compiler complaining. I'll let you know when that's ready for review.

Thanks again.

**Comment by riscy** [comment]
Friendly ping. :)  I'll mark this awaiting upstream in the meantime.

**Comment by mohkale** [comment]
@riscy 

All right I've added local defvars for all the lexical variables and I can bytecompile everything with no warnings. Apologies for the late update :sweat:.

**Comment by mohkale** [comment]
@riscy 

I'm not getting any compilation warnings but now `let*` closures don't seem to be working causing the checkers to crash. I'll have to debug this for now.

**Comment by mohkale** [comment]
@riscy 

I honestly have no idea why the process sentinel lambda doesn't seem to have the variables in the outer let scope available. But suffice it to say adding `defvars` for the local variables of the lambda is causing the package to crash so I've removed them for now. Do you have any other suggestions for silencing the byte-compiler?

**Comment by riscy** [comment]
> adding defvars for the local variables of the lambda is causing the package to crash so I've removed them for now. Do you have any other suggestions for silencing the byte-compiler?

Hmm.  I'm not sure what's going on, but if you have a backtrace I might be able to be more help.  If it's really hard for you to debug, you might think about seeing if you can simplify this code.

As for suggestions, I'm treading into subjective codestyle territory here, but sometimes it's beneficial _not_ to have a single very large interfaces with lots of "optional" code paths crossing other source files, since it can introduce a whole new class of latent bugs, and is generally harder for others to check.  That was sort of the gist of my first alternative above.

I also wonder why you need to let-bind it so high in the call-stack -- why not closer to where it's actually used, e.g. when you push and pop from it in flymake-rest-parse-enumerate.el?

Another option is just to exercise the variable unconditionally, for example by placing a cl-assert on it somewhere.  This might be a last resort.

**Comment by riscy** [comment]
Friendly ping. :) Maybe the cl-assert is the best solution here?  I realize how pedantic I sound but being strict about these checks is ultimately easier (for me) than negotiating grey areas.

**Comment by mohkale** [comment]
@riscy 

Apologies for the late update. I intended to do the refactoring you suggested but as I imagine it to be quite the undertaking I plan to leave it for a little while. I'll let you know once it's ready :smile:.

**Comment by riscy** [comment]
No worries. :)  I'll mark this awaiting upstream, but feel free to ping when ready.

**Comment by riscy** [comment]
Hi @mohkale I notice you've opened a couple newer PRs in the meantime.  Just to help us keep our plates clear(er) would it make sense to close this PR until you're ready?

**Comment by mohkale** [comment]
@riscy 

Yeah that's all right. This'll require a pretty big refactoring before it can be merged and I'm not sure when I'll be able to commit to that so if it makes things easier feel free to close it. :smile:.

**Pull request closed without merging**
