### PR TITLE
Add new recipe "ffmpeg-utils"

### PR DESCRIPTION
**Pull request by stardiviner**
### Brief summary of what the package does

An interface to provide commands of ffmpeg utilities.

### Direct link to the package repository

https://repo.or.cz/ffmpeg-utils.git

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`ffmpeg-utils.el` with byte-compile using Emacs 28.1:
```
ffmpeg-utils.el:33:1: Error: Cannot open load file: No such file or directory, alert
```
This may point to a missing `Package-Requires` on [alert](https://stable.melpa.org/#/alert).

`ffmpeg-utils.el` with checkdoc 0.6.2:
```
ffmpeg-utils.el:88: Argument `msg' should appear (as MSG) in the doc string
ffmpeg-utils.el:109: Some lines are over 80 columns wide
```

`ffmpeg-utils.el` with package-lint 20221003.1636:
```
7 issues found:
36:0: error: "ffmpeg--output-filename" doesn't start with package's prefix "ffmpeg-utils".
39:0: error: "ffmpeg-notification-function" doesn't start with package's prefix "ffmpeg-utils".
45:0: error: "ffmpeg-notification-default" doesn't start with package's prefix "ffmpeg-utils".
79:0: error: "ffmpeg--run-command" doesn't start with package's prefix "ffmpeg-utils".
87:0: error: "ffmpeg-mode-line-running-indicator" doesn't start with package's prefix "ffmpeg-utils".
96:0: error: "ffmpeg--subtract-timestamps" doesn't start with package's prefix "ffmpeg-utils".
108:0: error: "ffmpeg-cut-clip" doesn't start with package's prefix "ffmpeg-utils".
```

`ffmpeg-utils.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ffmpeg-utils.el#L7: Prefer `;; Version` over `;; Package-Version` (MELPA automatically adds `Package-Version`)
- ffmpeg-utils.el#L77: No `format` required; `message` takes an f-string
```

**Comment by stardiviner** [comment]
Ok, I fixed all upper error and warnings.

**Comment by progfolio** [comment]
I get the following warnings when byte compiling on Emacs 30:

<details><summary>Log @2023-02-06 00:31:32 -0500</summary>
search filter: "ffmpeg||warn"
<table>
<thead><th>Package</th><th>Status</th><th>Info</th><th>Time</th></thead>
<tbody>
<tr><td>ffmpeg-utils</td><td>byte-compilation</td><td>ffmpeg-utils.el:45:53: Warning: Unused lexical argument ‘proc’</td><td>25052.233391</td></tr>
<tr><td>ffmpeg-utils</td><td>byte-compilation</td><td>ffmpeg-utils.el:45:58: Warning: Unused lexical argument ‘event’</td><td>25052.233394</td></tr>
<tr><td>ffmpeg-utils</td><td>byte-compilation</td><td>ffmpeg-utils.el:108:2: Warning: docstring wider than 80 characters</td><td>25052.233400</td></tr>
<tr><td>ffmpeg-utils</td><td>byte-compilation</td><td>ffmpeg-utils.el:64:11: Warning: the function ‘osx-lib-notify2’ is not known to be defined.</td><td>25052.233406</td></tr>
<tr><td>ffmpeg-utils</td><td>byte-compilation</td><td>ffmpeg-utils.el:60:16: Warning: the function ‘ns-do-applescript’ is not known to be defined.</td><td>25052.233408</td></tr></tbody>
</table>
</details>

**Comment by stardiviner** [comment]
The bellowing warning fixed.

ffmpeg-utils | byte-compilation | ffmpeg-utils.el:45:53: Warning: Unused lexical argument ‘proc’ | 25052.233391
-- | -- | -- | --
ffmpeg-utils | byte-compilation | ffmpeg-utils.el:45:58: Warning: Unused lexical argument ‘event’ | 25052.233394

The other warnings I don't know how to fix. Because they are related to macOS system version Emacs.

ffmpeg-utils | byte-compilation | ffmpeg-utils.el:64:11: Warning: the function ‘osx-lib-notify2’ is not known to be defined. | 25052.233406
-- | -- | -- | --
ffmpeg-utils | byte-compilation | ffmpeg-utils.el:60:16: Warning: the function ‘ns-do-applescript’ is not known to be defined. | 25052.233408

I added `osx-lib` to `Package-Requires:` and add `require` already. The `osx-lib-notify2` is only available in macOS version Emacs.

**Comment by riscy** [comment]
> ffmpeg-utils.el:60:16: Warning: the function ‘ns-do-applescript’ is not known to be defined.

For this one you can use `declare-function` so that non-macOS users won't see unnecessary warnings.  e.g. add a line `(declare-function ns-do-applescript "ext:macos-builtin")` might fit.

> ffmpeg-utils.el:64:11: Warning: the function ‘osx-lib-notify2’ is not known to be defined.

I think you should remove `(osx-lib "0.1")` from your `Package-Requires` line so that it's not automatically installed by non-macOS users.  I see your code already makes accommodations for when it's not installed, which is great.

Next you can rewrite your conditional `(and (featurep 'osx-lib) (bound-and-true-p osx-lib-start-terminal))` to `(require 'osx-lib nil t)` which will return non-nil if the package is installed, and use `(declare-function osx-lib-notify3 "osx-lib.el")` (notice I'm not using `ext:` here, so that `M-x check-declare` can actually be used to verify the declaration).

**Comment by stardiviner** [comment]
@riscy Thanks for code snippets. I updated extension code now. [Check it out](https://repo.or.cz/ffmpeg-utils.git/blobdiff/a8f4fabc7e0ff653c15a76b28df9e63e19fc5740..7ae311d235514b7b5bf12dc2c214856856c2c411:/ffmpeg-utils.el)

**Comment by riscy** [comment]
Looks good.  Thanks!

**Pull request merged**
