### PR TITLE
Added autocrypt recipe

### PR DESCRIPTION
**Pull request by phikal**
### Brief summary of what the package does

From the [Autocrypt](https://autocrypt.org/) homepage:

>  Autocrypt is a set of guidelines for developers to achieve convenient end-to-end-encryption of e-mails. It specifies how e-mail programs negotiate encryption capabilities using regular e-mails.

This package implements parts of "Autocrypt Level 1", for multiple Emacs MUAs.

### Direct link to the package repository

https://git.sr.ht/~zge/autocrypt

### Your association with the package

I am the maintainer and creator.

### Relevant communications with the upstream package maintainer

N/A

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by tarsius** [comment]
Please use section headings that are compatible with `outline-minor-mode` by doing:

```diff
- ;; heading
+;;; heading
```

(You already mark up headings differently than regular *comments*, now you just need to replace the first character.)

**Comment by phikal** [comment]
Will this work even though I have a form feed character at the beginning of the line? I never really used outline mode, so I'm not sure of what the intended usecase is.

**Comment by conao3** [comment]
Please read [Emacs-lisp-style-guide; Comment](https://github.com/bbatsov/emacs-lisp-style-guide#comments).

The number of semicolons in Elisp is meaningful, so follow that convention.
You don't need to be familiar with the `outline-minor-mode` in @tarsius example, but many packages work on the basis of the number of semicolons.

Another problem is that you should not place any characters after `^\L`.
If [page-break-lines-mode](https://github.com/purcell/page-break-lines) is used, characters after `^L` disappear outside the window.
Screenshot_2020-03-21_10-12-55

**Comment by conao3** [comment]
And please solve below warnings/errors
```
 autocryp…    29  11 error           You should depend on (emacs "24.3") or the cl-lib package if you need `cl-lib'. (emacs-lisp-package)
 autocryp…    47     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 autocry…    81   2 error           You should depend on (emacs "24.3") or the cl-lib package if you need `cl-defstruct'. (emacs-lisp-package)
 autocry…   121     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 autocry…   128     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 autocry…   134     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 autocry…   138     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 autocry…   155   8 error           You should depend on (emacs "24.3") if you need `user-error'. (emacs-lisp-package)
 autocry…   264     warning         Argument ‘date’ should appear (as DATE) in the doc string (emacs-lisp-checkdoc)
 autocry…   361     warning         Argument ‘gossip-p’ should appear (as GOSSIP-P) in the doc string (emacs-lisp-checkdoc)
 autocry…   363     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 autocry…   364     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 autocry…   393     warning         Argument ‘name’ should appear (as NAME) in the doc string (emacs-lisp-checkdoc)
 autocry…   432   2 error           You should depend on (emacs "24.4") if you need `with-eval-after-load'. (emacs-lisp-package)
 autocry…   432   2 warning         `with-eval-after-load' is for use in configurations, and should rarely be used in packages. (emacs-lisp-package)
 autocry…   449   2 error           You should depend on (emacs "24.4") if you need `with-eval-after-load'. (emacs-lisp-package)
 autocry…   449   2 warning         `with-eval-after-load' is for use in configurations, and should rarely be used in packages. (emacs-lisp-package)
 autocry…   468   2 error           You should depend on (emacs "24.4") if you need `with-eval-after-load'. (emacs-lisp-package)
 autocry…   468   2 warning         `with-eval-after-load' is for use in configurations, and should rarely be used in packages. (emacs-lisp-package)
 autocry…   488   2 error           You should depend on (emacs "24.4") if you need `with-eval-after-load'. (emacs-lisp-package)
 autocry…   488   2 warning         `with-eval-after-load' is for use in configurations, and should rarely be used in packages. (emacs-lisp-package)
 autocry…   515  11 error           You should depend on (emacs "25.1") if you need `mml-secure-is-encrypted-p'. (emacs-lisp-package)
 autocry…   517  11 error           You should depend on (emacs "24.3") or the cl-lib package if you need `cl-every'. (emacs-lisp-package)
 autocry…   530  10 error           You should depend on (emacs "24.3") or the cl-lib package if you need `cl-case'. (emacs-lisp-package)
 autocry…   549  26 error           You should depend on (emacs "25.1") if you need `mml-secure-is-encrypted-p'. (emacs-lisp-package)
 autocry…   596   1 warning         the following functions are not known to be defined: autocrypt-list-recipients, mu4e-view-raw-message, autocrypt-message-setup, autocrypt-message-pre-send, autocrypt-message-list-recipients, autocrypt-message-gossip-p (emacs-lisp)
```

**Comment by phikal** [comment]
Ah, I see. Thanks for the explanation, I'll fix it as soon as possible.

And I created the pull request as a draft, because I didn't yet fix everything. I will mark it as "ready for review" when they are resolved.

**Comment by phikal** [comment]
Regarding the `with-eval-after-load` complaint: Since my package is supposed to be generic, I wouldn't want to add them as real "dependencies". I thought about requiring the necessary features with the `noerror` flag, but that wouldn't really solve this issue. Is there a recommended-MELPA way to solve this issue?

**Comment by conao3** [comment]
I'm just a volunteer, so I recommend following `package-lint`'s suggestions 100% of the time.
The easiest way is to remove the code and comment it out and ask a user to put the code in his init.el.
`eval-after-load` is for user customization and should not be used by package authors.

**Comment by phikal** [comment]
I don't think that's user-friendly behaviour, since ~23% of the code (line-wise) is part of with-eval-after-load blocks. I was considering doing something like BBDB, but that would require reconsidering how well that was implemented.

**Comment by phikal** [comment]
The issues should be fixed now. The only thing I am uncertain about is that I used the autoload function instead of autoload comments to avoid the `with-eval-after-load` blocks.

**Comment by purcell** [comment]
Looks good, thanks! Merging now...

**Pull request merged**
