### PR TITLE
Add switch-buffer-functions recipe

### PR DESCRIPTION
**Pull request by 10sr**
This package provides a hook variable <del>`post-command-current-buffer-changed-functions`</del> `switch-buffer-functions`, which will be run when the current buffer has been changed after each interactive command.

I'm the author of this pckage.

<del>https://github.com/10sr/post-command-current-buffer-changed-functions-el</del>
https://github.com/10sr/switch-buffer-functions-el

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. The package name is longer than the package description! I think we can do better. How about calling this "switch-buffer-hook" or similar?

**Comment by 10sr** [comment]
Thanks! I've changed the name to `switch-buffer-functions`.

**Comment by purcell** [comment]
Nice!

**Comment by 10sr** [comment]
Thank you!

**Pull request merged**
