### PR TITLE
add hippo-theme

### PR DESCRIPTION
**Pull request by kimim**
### Brief summary of what the package does

Three theme colors: hippo-light, hippo-night, hippo-paper

### Direct link to the package repository

https://github.com/kimim/emacs-hippo-theme

### Your association with the package

Author/Maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by tarsius** [comment]
Please rename `hippo-theme.el` to `hippo-themes.el`. Also rename the package accordingly.

See https://github.com/melpa/melpa/issues/8219#issuecomment-1267425604 and other messages in the same thread for why that should be done.

**Comment by riscy** [comment]
Thanks for these.  Quick first pass --

`hippo-light-theme.el` with package-lint 20230315.1052:
```
6 issues found:
1:0: error: Error parsing main package file "hippo-themes.el": (error Package lacks a file header)
1:0: error: There is no `provide' form.
31:0: error: Package-Requires outside the main file have no effect.
41:0: error: "hippo-light" doesn't start with package's prefix "hippo-themes".
128:13: error: You should depend on (emacs "24.1") if you need `org-block'.
130:13: error: You should depend on (emacs "24.1") if you need `org-todo'.
```
I believe the `provide` nag will disappear once you add a properly formatted header to the file (the first line should begin with three semicolons, not two).

Also, while I'm looking, I see you have two "Keywords:" entries in your metadata block; you should also put this metadata block above your license boilerplate, closer to the top of the file.  So altogether the top of this file should look like:

```elisp
;;; hippo-light-theme.el --- Hippo color theme for GNU Emacs.

;; Author: Kimi MA
;; Keywords: faces local color theme
;; URL: http://github.com/kimim/emacs-hippo-theme
;; Version: 0.0.1
;; Package-Requires: ((emacs "24.1"))

;; Permission is hereby granted, free of charge, to any person
;; ......
```


`hippo-light-theme.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- hippo-light-theme.el#L59: It's safer to sharp-quote function names; use `#'`
```

`hippo-night-theme.el` with checkdoc 0.6.2:
```
hippo-night-theme.el:50: Messages should start with a capital letter
```

`hippo-night-theme.el` with package-lint 20230315.1052:
```
6 issues found:
1:0: error: Error parsing main package file "hippo-themes.el": (error Package lacks a file header)
1:0: error: There is no `provide' form.
31:0: error: Package-Requires outside the main file have no effect.
41:0: error: "hippo-night" doesn't start with package's prefix "hippo-themes".
126:13: error: You should depend on (emacs "24.1") if you need `org-block'.
128:13: error: You should depend on (emacs "24.1") if you need `org-todo'.
```

`hippo-night-theme.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- hippo-night-theme.el#L58: It's safer to sharp-quote function names; use `#'`
```

`hippo-paper-theme.el` with package-lint 20230315.1052:
```
6 issues found:
1:0: error: Error parsing main package file "hippo-themes.el": (error Package lacks a file header)
1:0: error: There is no `provide' form.
31:0: error: Package-Requires outside the main file have no effect.
41:0: error: "hippo-paper" doesn't start with package's prefix "hippo-themes".
126:13: error: You should depend on (emacs "24.1") if you need `org-block'.
128:13: error: You should depend on (emacs "24.1") if you need `org-todo'.
```

`hippo-paper-theme.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- hippo-paper-theme.el#L58: It's safer to sharp-quote function names; use `#'`
```

`hippo-themes.el` with package-lint 20230315.1052:
```
1 issue found:
1:0: error: package.el cannot parse this buffer: Package lacks a file header
```

Package and license:
- Prefer equivalent recipe: `(hippo-themes :repo "kimim/emacs-hippo-theme" :fetcher github)`
- Add a LICENSE file to the repository
  See: https://github.com/licensee/licensee

**Comment by riscy** [comment]
Just taking a followup look at this one.  I see many of the issues are fixed (thank you!) but the prefixes are still needing adjustment:

```
40:0: error: "hippo-light" doesn't start with package's prefix "hippo-themes".
40:0: error: "hippo-night" doesn't start with package's prefix "hippo-themes".
40:0: error: "hippo-paper" doesn't start with package's prefix "hippo-themes".
```
So these would ideally be named e.g. `hippo-themes-light`, etc.

**Comment by kimim** [comment]
> So these would ideally be named e.g. `hippo-themes-light`, etc.
I really like to keep `hippo-light`, `hippo-night` theme names.
I found some other package use such kind of names, let me find a solution.

**Comment by riscy** [comment]
One option that many themes use is to put multiple packages on MELPA,  e.g. `hippo-light-theme` and `hippo-night-theme` as distinct recipes.

**Comment by riscy** [comment]
In case it is helpful, there is a (very WIP) FAQ that addresses the naming of theme packages here:
https://github.com/melpa/melpa/blob/4caa9a03cad40d24484fce27fcfcf75b1d08e814/FAQ.md

**Comment by kimim** [comment]
> https://github.com/melpa/melpa/blob/4caa9a03cad40d24484fce27fcfcf75b1d08e814/FAQ.md

Thanks, I updated according to this FAQ.

**Comment by riscy** [comment]
Thanks!  Ready to merge.

**Pull request merged**
