### PR TITLE
add oj recipe

### PR DESCRIPTION
**Pull request by conao3**
### Brief summary of what the package does

Competitive programming tools(oj, oj-template) client for AtCoder, Codeforces...

### Direct link to the package repository

https://github.com/conao3/oj.el

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Code looks good to me -- but why the name oj?  I am guessing "online judge" after scanning the source code but that's not clear yet from the Commentary or the README.

One small nag, I notice the link to the Kattis online judge is broken (probrems -> problems) .

**Comment by conao3** [comment]
It comes from the server command name.

This package description
> Competitive programming tools(oj, oj-template) client for AtCoder, Codeforces...

- oj - https://github.com/online-judge-tools/oj
- oj-template - https://github.com/online-judge-tools/template-generator

And thanks for Kattis online judge URL issue.

**Comment by riscy** [comment]
Ok, I see.  I have a soft recommendation that you [do something similar to the oj cli](https://pypi.org/project/online-judge-tools/) and name the package "online-judge-tools" (or similar).  And then maybe your summary line might be: "Competitive programming with online-judge-tools (oj)" which might be more discoverable.  But let me know what you think about that.

**Comment by conao3** [comment]
How to use a 60-character package summary is a nagging question.
I would choose to include a specific and representative name like AtCoder or Codeforces rather than including the letters online-judge.
Also, I would like to keep the name of the package as `oj`.

**Comment by riscy** [comment]
Fair nuff. :)  Thanks for this.

**Comment by conao3** [comment]
Thanks!

**Pull request merged**
