### PR TITLE
Add the client for the Meyvn build tool.

### PR DESCRIPTION
**Pull request by danielsz**
Meyvn is a Clojure live coding environment & build tool. 

### Brief summary of what the package does

The Meyvn client complements the cider nREPL with additional facilities such as reload on save, teardown and rebuild world, and also the ability to add Clojure dependencies at runtime.

### Direct link to the package repository

https://github.com/danielsz/meyvn-el

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [ x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [ x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [ x] My elisp byte-compiles cleanly
- [ x] `M-x checkdoc` is happy with my docstrings
- [ x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by conao3** [comment]
Hi!
I'm not a MELPA maintainer, but here's some feedback for this package.
I hope below those comments help you and your package.

0. Please test your package ensure build via MELPA clean build see https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#test-your-recipe
  I need to add many dependency packages to ensure build your package.
1. Require `ivy` is not good idea. How about `helm` user? You want to provide ivy integrate feature, please separate package like `meyvn`, `meyvn-ivy`, (`meyvn-helm`) see https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
>     MELPA only looks at the main .el file (or -pkg.el file, if provided, though we discourage that). If you have different optional parts of a large package, each of which has different dependencies, then these should really be published as separate packages.

2. Please consider adding Cask file is good to easy resolve dependency, build, packaging etc.
3. Please add .gitignore file is good to ignore git stage *.elc files and .cask folder.
4. Please indent the whole file because of some of the places broken indent.
5. Please use `expand-file-name` instead of `concat` to create a file path.
6. Please remove top-level sexp.
All packages should not have side-effects just require package for user-experience.
I suggest all packages should have `*-setup` and `*-teardown` function if some setup is needed.

**Comment by danielsz** [comment]
Thank you for the feedback. It is helpful.

**Comment by danielsz** [comment]
I changed the installation instructions to a one-liner. I hope it's alright.

``` emacs-lisp
(add-hook 'cider-mode-hook #'meyvn-setup)
```

**Comment by conao3** [comment]
Good!

But this issue remained.
> Require ivy is not good idea. How about helm user? You want to provide ivy integrate feature, please separate package like meyvn, meyvn-ivy, (meyvn-helm) see https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
>> ELPA only looks at the main .el file (or -pkg.el file, if provided, though we discourage that). If you have different optional parts of a large package, each of which has different dependencies, then these should really be published as separate packages.

Please consider resolving this issue if you have time. (separate core feature and ivy integration feature)

**Comment by danielsz** [comment]
OK, no problem. If you can point to a reference project that implements that well, that can be helpful. If not, no worries. Thank you.

**Comment by conao3** [comment]
Thanks replay!
Please reference related [conversation](https://github.com/melpa/melpa/issues/6262) and the issued [package](https://github.com/akirak/org-starter).

**Comment by riscy** [comment]
Very much appreciate the use of short functions in this code -- nice style.

I agree with @conao3 about the reliance on ivy.  I'm sure helm or ido or icicles users would appreciate generic calls to `completing-read` or specialized sub-packages, but altogether that's not a blocker.

You capitalize Mevyn in your docstrings but not in your package summary line -- maybe capitalize it in the latter?

You make a call to `(parseedn-read)` which is transitively imported by one of your dependencies, but you shouldn't rely on that being the case.  You should `Package-Requires` on [parseedn](https://github.com/clojure-emacs/parseedn) and `(require 'parseedn)` accordingly.

Minor:
- meyvn.el#L83: No `concat` required; messages are already f-strings
- meyvn.el#L118: No `concat` required; messages are already f-strings
- meyvn.el#L267: Consider `unless ...` instead of `when (not ...)`
- meyvn.el#L22: Prefer `https` over `http` (if possible)
- pacakge -> package
- "Does a Mevyn config exists?" -> "exist?"

**Comment by danielsz** [comment]
I took note of all your comments, recommandations and feedback, and will do the work as soon as possible. You guys rock. Thank you so much!

**Comment by danielsz** [comment]
Hi, 

I believe I've integrated all your recommendations. 
The dependency on `ivy` has been removed in favor of a generic `completing-read` implementation without loss of functionality. Please let me know if there is anything else. Thank you!

**Comment by riscy** [comment]
Great, thanks!

**Comment by danielsz** [comment]
It was a pleasure to work with you on this, you provided excellent guidance and in such a good spirit. This means a lot to me. Thanks a lot @riscy and @conao3.

**Pull request merged**
