### PR TITLE
Update recipe chronos due to the absence of the maintainer

### PR DESCRIPTION
**Pull request by DarkBuffalo**
Hi,

First thanks for your work.

I tried to contact the maintainer but without success his email no longer works. I therefore allow this modification to be proposed.

Cordially.

### Direct link to the package repository

https://github.com/DarkBuffalo/chronos

### Your association with the package

Contributor & futur maintainer

### CODE REVIEW

**Comment by tarsius** [comment]
Please make sure you read https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks.

**Comment by DarkBuffalo** [comment]
> Please make sure you read https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks.

Hi @tarsius ,

Thank you, indeed I had not read it but I had put myself in its place in my thinking. this is why when we look at the repo we notice PRs or Issues that have not had an answer for several years, moreover we notice no activity on the github account for several years.

So I said to myself there is an email in the header of the code.
So I tried to send an email.
But the email no longer exists. When trying to send the email there is an error message showing that it no longer exists.

In addition I did some research by typing his name and email on the internet to find a link with any account, without result.

I think I am in the spirit of the instructions.

**Comment by riscy** [comment]
I'll mention @dxknight here just in case the original maintainer might see this.  It may be worth waiting a week or two to see if we get any attention here.

In the meantime, a couple of other important passages from the document @tarsius linked include:

> A rock solid package with an inactive maintainer is a non-issue. Checkdoc warnings and deprecation warnings during a byte-compile are not a big deal. Medium deals are things like namespace violations. Big deals are things like incompatibility with current versions of package dependencies or modern Emacs version, or other compile-time/runtime errors.

Also check out the section on [other things to note](https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks#other-things-to-note) regarding opening PRs that fix issues (e.g. byte-compile warnings, of which there are a few).  Even if they aren't merged, it demonstrates that you've got a plan vs. the existing issues.

**Comment by DarkBuffalo** [comment]
> I'll mention @dxknight here just in case the original maintainer might see this.  It may be worth waiting a week or two to see if we get any attention here.
> 

Yes, of course.

> In the meantime, a couple of other important passages from the document @tarsius linked include:
> 
> > A rock solid package with an inactive maintainer is a non-issue. Checkdoc warnings and deprecation warnings during a byte-compile are not a big deal. Medium deals are things like namespace violations. Big deals are things like incompatibility with current versions of package dependencies or modern Emacs version, or other compile-time/runtime errors.

I have already made an addition as well 77a4ba2 as that of  @thomp  d01f1cb


https://github.com/dxknight/chronos/compare/master...DarkBuffalo:chronos:master

> 
> Also check out the section on [other things to note](https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks#other-things-to-note) regarding opening PRs that fix issues (e.g. byte-compile warnings, of which there are a few).  Even if they aren't merged, it demonstrates that you've got a plan vs. the existing issues.

it's on I'm not an expert like you or tarsius.  from my volunteering i created [ox-report](https://github.com/DarkBuffalo/ox-report) found on melpa.  I'm working on to add a text export.

[Org-verse](https://github.com/DarkBuffalo/org-verse), [gocryptfs.el](https://github.com/DarkBuffalo/gocryptfs.el) not on melpa.

nevertheless if you consider that it is necessary to leave the package in the state and that I work on my fork, I would not be upset.

**Comment by riscy** [comment]
I think it makes sense for you to continue this package -- let's wait another week to hear back from @dxknight, otherwise in my estimation we should pull the pin on this one. :)

**Comment by riscy** [comment]
Thank you for your kind offer to take over maintainership of this package -- I think this is the appropriate move now, and we appreciate it.  I'll merge this update. :)

**Comment by DarkBuffalo** [comment]
Hi @riscy 
thanks to apreciate.

**Pull request merged**
