### PR TITLE
add recipe for vtm

### PR DESCRIPTION
**Pull request by laishulu**
### Brief summary of what the package does

vtm manages vterm buffers with configuration files.

### Direct link to the package repository

https://github.com/laishulu/emacs-vterm-manager

### Your association with the package

maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Did you intend to package toml.el with this?

In the meantime:

### vtm.el ###

byte-compile (using Emacs 26.3):
```
vtm.el:102:1:Warning: the function `toml:read-from-string' is not known to be
    defined.
```
(You probably need to `(require 'toml')`)

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200419.406):
- No issues!


### Loadability ###

Verifying ability to #'load each file:
```
Loading toml.el
Loading vtm.el
Done.
```

### Package ###

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by laishulu** [comment]
@riscy 

fixed. Please verify.

**Comment by riscy** [comment]
A couple points from above:

- Did you intend to package toml.el with this?
- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee

**Comment by laishulu** [comment]
>Did you intend to package toml.el with this?

toml.el is a github project, https://github.com/gongo/emacs-toml
it's not in MELPA.
So I include it with the following codes:
```
;; load feature `toml'
(unless (featurep 'toml)
  (load (expand-file-name "toml" (file-name-directory load-file-name))))
```

>Add a LICENSE file that GitHub can detect (e.g. no markup) if possible

Finished.

**Comment by laishulu** [comment]
update::::

I found toml IS included in MELPA
So I will remove the toml file right now!

**Comment by laishulu** [comment]
Final update, both of the two issues are resolved:

1. self-included toml are removed, now using MELPA version.
2. license file added.

**Comment by riscy** [comment]
Great, taking a closer look now.  The only feedback I've got is, instead of `setq auto-mode-alist` you should use `add-to-list` -- you can refer to e.g. elisp-mode for an example.  Otherwise it will grow the list each time it gets run.

For your summary line I'd recommend the active voice: "Manage vterm buffers with configuration files"

Both are minor enough, though -- I'll go ahead and merge, but please update when you get a chance.  Thanks!

**Pull request merged**
