### PR TITLE
Add info manual to modus-operandi-theme and modus-vivendi-theme recipes

### PR DESCRIPTION
**Pull request by protesilaos**
### Brief summary of what the package does

These are two separate packages that are part of the same project.  They are themes that are designed to be highly accessible (conformance with the WCAG AAA standard).

### Direct link to the package repository

https://gitlab.com/protesilaos/modus-themes

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] `M-x checkdoc` is happy with my docstrings
- [X] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
The [default recipe](https://github.com/melpa/melpa#recipe-format) will catch `*.info` in the repo root if you prefer -- good either way.

**Comment by protesilaos** [comment]
Sorry, I thought my recipes would be interpreted strictly as only containing the file they specify.  I can close this and just move the files to the repo's root, if you will.

**Comment by riscy** [comment]
My mistake - I didn't look closely enough. :)

**Comment by protesilaos** [comment]
Thank you!

**Pull request merged**
