### PR TITLE
Add Treadmill: A Gerbil Scheme development environment

### PR DESCRIPTION
**Pull request by edw**
### Brief summary of what the package does

A Gerbil Scheme development environment

### Direct link to the package repository

https://github.com/thunknyc/emacs-treadmill

### Your association with the package

I am the author.

### Relevant communications with the upstream package maintainer

**Node needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by edw** [comment]
Hey Chris,

Thanks for the feedback. I believe I've addressed all of the issues you brought up in the most recent commit to the repo.

Thanks again,
Edwin

**Comment by purcell** [comment]
Rather than just close this, I sent you some fixes. :-)

**Comment by purcell** [comment]
Bump! :-)

**Comment by tarsius** [comment]
@edw I am closing this now, but let us know when you have made progress. We can reopen then.

**Pull request closed without merging**
