### PR TITLE
Add isolate recipe

### PR DESCRIPTION
**Pull request by casouri**
### Brief summary of what the package does

This is a surrouding tool.
It features powerful and easy customization system.
You can create complex regexp rules easily.

### Direct link to the package repository

https://github.com/casouri/isolate

### Your association with the package

Author

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). 
- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by akirak** [comment]
This looks cool. I am a former vim user, and I have wanted an equivalent to [surround](https://github.com/tpope/vim-surround) **without evil**. This package may fill in the need.

**Comment by casouri** [comment]
Talking about surround without evil, there is embrace:

https://github.com/cute-jumper/embrace.el

Althought I’ll quietly say that mine is better.

**Comment by purcell** [comment]
Thanks, and sorry for the delay. Quick notes:

- "flexable" should be "flexible", "surrouding" should be "surrounding". (Maybe try `flyspell-prog-mode`?)
- Why not write `isolate--append` and `isolate--push` as `defsubst` instead of macros? Your macro expand their arguments multiple times, which could lead to multiple evaluation - read the macros section of Practical Common Lisp (free online) to understand what I mean.

In any case, I'll merge this now, but you should address the above points separately.

**Comment by casouri** [comment]
Thanks! I'll fix those issues. I just got my flyspell back to work again recently... I will scan for any other typos.

**Comment by casouri** [comment]
Fixed.

**Pull request merged**
