### PR TITLE
Add recipe for on.el

### PR DESCRIPTION
**Pull request by paperdigits**
### Brief summary of what the package does

[Please write a quick summary of the package.]

Defer loading things at startup and define when to load them. Extracted from DOOM emacs.

### Direct link to the package repository

https://gitlab.com/ajgrf/on.el

### Your association with the package

Enthusiastic user

### Relevant communications with the upstream package maintainer
None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this - these are definitely cool.  It has also been a couple years since the last update - this is not a blocker, but maybe Doom has even more tricks since then.

There are no blockers on this but I'd like to hear @ajgrf 's take on indexing this.  Here's a couple minor things:

`on.el` with checkdoc 0.6.2 (fix *within reason*):
```
on.el:72: First line is not a complete sentence
on.el:107: All variables and subroutines might as well have a documentation string
on.el:110: All variables and subroutines might as well have a documentation string
```

`on.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- on.el#L102: It's safer to sharp-quote function names; use `#'`
```

**Comment by ajgrf** [comment]
I have no problems with `on.el` getting added to MELPA, but I won't be developing the package further (other than bug fixes). If I circle back to this space in the future I plan on contributing to [once](https://github.com/emacs-magus/once) instead.

**Comment by paperdigits** [comment]
Whatever you decide is good with me, @riscy

**Comment by riscy** [comment]
Ok - I think this is an interesting and complete package on its own.  I'll merge this, but I'll keep an eye out for `once`.

**Comment by riscy** [comment]
I've already hit merge, but maybe this would also be a good opportunity to check whether @paperdigits has any interest in taking over maintainership of this package? (And if @ajgrf would support that, of course.)

**Comment by paperdigits** [comment]
I do not have that interest, sorry. I will also keep an eye on once.

Thanks to both of you for taking the time to discuss, it was a positive first experience for me.

**Pull request merged**
