### PR TITLE
belgian-holidays first commit.

### PR DESCRIPTION
**Pull request by BackFromHellBE**
### Brief summary of what the package does

[Please write a quick summary of the package.]

### Direct link to the package repository

https://github.com/your/awesome_package

### Your association with the package

[Are you the maintainer? A contributor? An enthusiastic user?]

### Relevant communications with the upstream package maintainer

[e.g., `package.el` compatibility changes that you have submitted. Write **None needed** if there is no problem.]

### Checklist

- [] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [] My elisp byte-compiles cleanly
- [] `M-x checkdoc` is happy with my docstrings
- [] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by BackFromHellBE** [comment]
My first contribution

**Comment by riscy** [comment]
Thanks for this, and welcome. :)  Here's a quick first pass --

`belgian-holidays.el` with package-lint 20221003.1636:
```
5 issues found:
1:87: warning: You should depend on (emacs "24.1") if you need lexical-binding.
64:0: error: "holiday-belgian-national-holidays-fr" doesn't start with package's prefix "belgian-holidays".
76:0: error: "holiday-walloon-regional-holidays-fr" doesn't start with package's prefix "belgian-holidays".
81:0: error: "carnaval-carnieres-fr" doesn't start with package's prefix "belgian-holidays".
87:0: error: "belgian-remarkable-days-fr" doesn't start with package's prefix "belgian-holidays".
```

Let me know if you have any questions!

**Comment by riscy** [comment]
I'll mark this awaiting-upstream for now, but feel free to reach out.

**Comment by progfolio** [comment]
@BackFromHellBE  are you still interested in submitting this package to MELPA?

**Pull request closed without merging**
