### PR TITLE
Add acme-theme recipe

### PR DESCRIPTION
**Pull request by ianpan870102**
### Brief summary of what the package does

Acme is an original theme inspired by the look and feel of the the Acme and Sam editor from Plan9.
### Direct link to the package repository

https://github.com/ianpan870102/acme-emacs-theme

### Your association with the package

Author and maintainer

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

### acme-theme.el ###

byte-compile (using Emacs 26.3):
- acme-theme.el#L522: Don't set `no-byte-compile: t`.
  Byte-compiling is enabled in what follows
- Per CONTRIBUTING.org, consider using lexical binding.
  See: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#fixing-typical-problems
- Lexical binding will be used in what follows
```
acme-theme.el:70:1:Error: Symbol's value as variable is void: acme-theme-colors-alist
```

checkdoc (using version 0.6.1):
- No issues!

package-lint (using version 20200419.406):
```
2 issues found:
448:4: error: You should depend on (emacs "24.1") if you need `org-date'.
456:4: error: You should depend on (emacs "24.1") if you need `org-block'.
```
These can be disregarded in themes.

Suggestions/experimental static checks:
- acme-theme.el#L20: Prefer `https` over `http` if possible ([why?](https://news.ycombinator.com/item?id=22933774))

### Loadability ###

Verifying ability to #'load each file:
```
Loading acme-theme.el
Done.
```

### Similarly named ###

- inverse-acme-theme: https://melpa.org/#/inverse-acme-theme
- nofrils-acme-theme: https://melpa.org/#/nofrils-acme-theme

### Package ###

- Add a LICENSE file that GitHub can detect (e.g. no markup) if possible
  See: https://github.com/licensee/licensee
- Package-Requires: n/a
- pkg/acme-theme.el (GPL) -- A color theme based on Acme & Sam from Plan 9

**Comment by ianpan870102** [comment]
Hi Chris @riscy , thanks for the feekback!
In my latest commits I've fixed the URL, the usage of lexical binding, byte-compile errors and more. 
The theme is ready for your final review.

**Comment by riscy** [comment]
Looks good!  I think this is not a blocker, but you should be aware you wrote `elfeed-search-unread-title-facee` (instead of `face`).

**Comment by ianpan870102** [comment]
> you should be aware you wrote elfeed-search-unread-title-facee (instead of face).

Thanks a ton mate, I'll fix it now.

**Pull request merged**
