### PR TITLE
Add anakondo recipe

### PR DESCRIPTION
**Pull request by didibus**
### Brief summary of what the package does

Minor mode for Clojure[Script] completion and editing facilities powered by clj-kondo.

### Direct link to the package repository

https://github.com/didibus/anakondo

### Your association with the package

I am the maintainer.

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### Note
I don't like checkdoc's 80 char rule, so I choose to ignore those warning. All others passed.

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

### anakondo.el ###

byte-compile-file (using Emacs 26.3):
```
anakondo.el:453:1:Warning: the function `hash-table-values' is not known to be
    defined.
```
This one's easy, just add `(require 'subr-x)`.

checkdoc (using version 0.6.1):
```
Warning (emacs): 
anakondo.el:158: Some lines are over 80 columns wide
Warning (emacs): 
anakondo.el:202: Some lines are over 80 columns wide
Warning (emacs): 
anakondo.el:237: Some lines are over 80 columns wide
Warning (emacs): 
anakondo.el:262: Some lines are over 80 columns wide
Warning (emacs): 
anakondo.el:279: Some lines are over 80 columns wide
Warning (emacs): 
anakondo.el:282: Lisp symbol `completion-at-point' should appear in quotes
Warning (emacs): 
anakondo.el:304: Some lines are over 80 columns wide
Warning (emacs): 
anakondo.el:304: Lisp symbol `completion-at-point' should appear in quotes
Warning (emacs): 
anakondo.el:363: Some lines are over 80 columns wide
```
I realize you mentioned you don't like wrapping at 80 columns, but this one actually has a purpose -- the output of describe-function looks like this for your users:
image
so it is something we strive to maintain when it's possible.

package-lint-current-buffer (using version 20200419.406):
```
4 issues found:
1:0: warning: The package summary should not end with a period.
8:0: error: Expected (package-name "version-num"), but found (json).
8:0: error: Expected (package-name "version-num"), but found (projectile).
9:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
```
You'll need to add version-num's to the end of `json` and `projectile`.  An easy finder-known-keywords keyword could be "languages" or "tools".

**Comment by didibus** [comment]
> anakondo.el:453:1:Warning: the function `hash-table-values' is not known to be defined.

Weird, I didn't get this warning myself, when running `EMACS_COMMAND=emacs make sandbox INSTALL=anakondo`. Anyways, I added `(eval-when-compile (require 'subr-x))` which should cover it.

> I realize you mentioned you don't like wrapping at 80 columns, but this one actually has a purpose -- the output of describe-function looks like this for your users

Didn't know that. I made them all 80 columns wide at most.

I also fixed all other checkdoc warnings.

> An easy finder-known-keywords keyword could be "languages" or "tools".

Added both of them as keyword.

> 1:0: warning: The package summary should not end with a period.

Fixed this one.

> 8:0: error: Expected (package-name "version-num"), but found (json).
> 8:0: error: Expected (package-name "version-num"), but found (projectile).

Hum... those are bundled with Emacs 26.3, so I'm not sure how to figure out what versions they are? They're just the version in Emacs 26.3 no?

**Comment by didibus** [comment]
Another question about the package version, I don't really know what the minimum version for projectile is, I am using: 20200329.1908 and could add that. But it probably should work with older and newer versions as well. What exactly happens when I specify a version? Does it pin it down?

**Comment by riscy** [comment]
> Weird, I didn't get this warning myself

Yeah, these can be surprising -- probably the sandbox brings in a library that transitively pulls in subr-x, so you won't see it.

> I made them all 80 columns wide at most.

Thanks so much for accommodating. :)

Since `json` comes with Emacs, you don't have to have it in `Package-Requires` (that didn't occur to me, but you're right).

Altogether I'd write ```;; Package-Requires: ((emacs "26.3") (projectile "2.1.0"))``` -- 2.1.0 is the latest stable version indicated on [MELPA stable](https://stable.melpa.org/#/projectile) but you can also just write `(projectile "0.0")`.

Currently it's preferred to use a "stable" version rather than an unstable timestamp, but the versions don't get pinned.  MELPA doesn't hold more than one version of any package.  [This big discussion on reddit](https://www.reddit.com/r/emacs/comments/etikbz/speaking_as_a_package_maintainer_please_do_not/) will give you a whole lot more context.

**Comment by riscy** [comment]
I guess one advantage of writing a specific version number is that it will help people know what you tested with and, if the dependency is using semantic versioning, breaking changes might be a little easier to diagnose.

**Comment by didibus** [comment]
Alright, everything should be addressed. Pushed latest changes to didibus/anakondo master.

Also, I'm guessing after inclusion into Melpa, I'm in charge of updates. So my plan will be to continue to address checkdoc issues, run package-lint-current-buffer and address all those issues as well, and continnue to run the sandbox to make sure it compiles without errors. Also to tag stable releases with a git tag in my repo.

Does that all make sense?

**Comment by riscy** [comment]
Yep, this all looks good now!

That's correct that you're in charge of updates.  I find a tool like `flycheck` enabled in my Emacs lisp buffers immensely useful, because it will run checkdoc, cleanroom byte-compilation, and can be configured to run package-lint as well.  There are also tools out there like makem.sh, Cask, and [others](https://github.com/alphapapa/makem.sh#comparisons) that can automate this for you.  For what it's worth, when I'm checking MELPA packages, I have my own [bundle of scripts](https://github.com/riscy/melpazoid) I run, but they're heavyweight.

All that said, welcome to MELPA!

**Pull request merged**
