### PR TITLE
Add recipe for fill-page.

### PR DESCRIPTION
**Pull request by jcs090218**
### Brief summary of what the package does

Fill buffer so you don't see empty lines at the end.

### Direct link to the package repository

https://github.com/jcs-elpa/fill-page

### Your association with the package

The maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quickly glancing over the code.

I think there may be opportunities for simplification:
- `(fill-page--recenter-top-bottom 'bottom)` -- is this equivalent to `(recenter -1)`?
- Is the `'top` version equivalent to `(recenter 1)`?
- Both of those functions are implemented in C and so are very snappy

You should be aware that `line-number-at-pos` is (compiled) elisp that literally walks the cursor down from the top of the buffer, and is quite a slow operation on large buffers -- and you're doing it _twice_ in a post-command-hook to calculate the window configuration.  This strongly feels like it should happen once per window configuration change, inside `window-configuration-change-hook`?

**Comment by jcs090218** [comment]
> Quickly glancing over the code.
> 
> I think there may be opportunities for simplification:
> 
> (fill-page--recenter-top-bottom 'bottom) -- is this equivalent to (recenter -1)?
> Is the 'top version equivalent to (recenter 1)?
> Both of those functions are implemented in C and so are very snappy

All fixed! :)

> You should be aware that line-number-at-pos is (compiled) elisp that literally walks the cursor down from the top of the buffer, and is quite a slow operation on large buffers -- and you're doing it twice in a post-command-hook to calculate the window configuration. This strongly feels like it should happen once per window configuration change, inside window-configuration-change-hook?

I have replaced `window-scroll-functions` with `post-command-hook`. In addition, I have `window-configuration-change-hook` to update any window information so it only runs when it neededs to!

**Comment by riscy** [comment]
Have you thought about using `yascroll:window-height` to determine window height?

**Comment by jcs090218** [comment]
> Have you thought about using yascroll:window-height to determine window height?

Oh, yeah. I think this is definitely a better function. I now have extracted `yascroll:window-height` function from `yascroll`!

**Comment by riscy** [comment]
Nice, I'm glad that worked.  Now, it looks like `fill-page--max-window-height` is unused with this change so can probably be removed. :)

What I was thinking is: couldn't `fill-page-fill-p` just call this new `fill-page--window-height` (up to an off-by-1 error) instead of this `con-h` calculation?:
```
    (let* ((first-ln (fill-page--first-display-line))
           (last-ln (fill-page--last-display-line))
           (con-h (- last-ln first-ln)))
```
and then those first/last functions could also disappear.  I'm imagining there could be a noticeable improvement in performance for users if you avoid these calls to line-number-at-pos.

**Comment by jcs090218** [comment]
> couldn't fill-page-fill-p just call this new fill-page--window-height (up to an off-by-1 error)

I am confused by this. What do you mean? 😖

**Comment by riscy** [comment]
Sorry, that wasn't very clear.  What I'm thinking would be something that computed the empty lines by referring directly to `(fill-page--window-height)`, for example:

```elisp
(defun fill-page-empties ()
  (interactive)
  (let* ((available-lines (1- (fill-page--window-height)))
         (full-lines (save-excursion (1+ (move-to-window-line -1)))))
    (message "Empty lines: %s" (- available-lines full-lines))))
```
and you could turn that into a predicate that seems like it would run twice as fast, which I think is something to optimize for in something that runs synchronously in `after-change-functions`.

**Comment by jcs090218** [comment]
> and you could turn that into a predicate that seems like it would run twice as fast

Wow, this function is a lot simplify! Applied! Thank you very much! :)

**Comment by riscy** [comment]
Thanks for that!  Okay, I think these functions can disappear now: `fill-page--first-display-line`, `fill-page--last-display-line`.  Also maybe `fill-page--debug-message`?

I don't think these are blockers though.

**Pull request merged**
