### PR TITLE
Add pkl-mode

### PR DESCRIPTION
**Pull request by sin-ack**
### Brief summary of what the package does

It's a major mode for editing [Pkl](https://pkl-lang.org/) files.

### Direct link to the package repository

https://github.com/sin-ack/pkl-mode

### Your association with the package

I'm the package author.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] I've used `M-x checkdoc` to check the package's documentation strings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`pkl-mode.el` with byte-compile using Emacs 29.3:
```
pkl-mode.el:233:23: Warning: reference to free variable `copilot-indentation-alist'
pkl-mode.el:233:23: Warning: assignment to free variable `copilot-indentation-alist'
In end of data:
pkl-mode.el:224:12: Warning: the function `rainbow-delimiters-mode' is not known to be defined.
```

Stderr output while compiling/loading:
```
pkl-enable-copilot is t but copilot.el is missing.  Please install it or set pkl-enable-copilot to nil.
```

Altogether this handling of optional dependencies seems non-standard and cumbersome (for you).  For instance if users have rainbow-delimiters installed, you should just leave it up to them whether they want to enable it.  Since your `pkl-mode` is derived from prog-mode, users would have the option to `(add-hook prog-mode-hook ...)` or `(add-hook pkl-mode-hook ...)` and enable rainbow delimiters and whatever else they want only in these buffers.

Similarly, I don't know where a user would install copilot.el from today (I don't see it on any of the major package repositories, but maybe I missed it).  I would also delay modifying `copilot-indentation-alist` until activating the mode.  So instead of
```
;; Major mode definition

;;;###autoload
(define-derived-mode pkl-mode prog-mode "Pkl"
  "Major mode for editing Pkl files."
  :syntax-table pkl-mode-syntax-table
  (setq-local comment-start "// ")
  (setq-local comment-start-skip "//+\\s-*")
  (setq-local font-lock-defaults '(pkl-font-lock-keywords))
  (setq-local indent-line-function #'pkl-indent-line)

  ;; Integrations

  (when pkl-enable-rainbow-delimiters
    (if pkl--feature-rainbow-delimiters
        (progn
          (rainbow-delimiters-mode 1))
      (message "pkl-enable-rainbow-delimiters is t but rainbow-delimiters.el is missing.  Please install it or set pkl-enable-rainbow-delimiters to nil."))))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.pkl\\'" . pkl-mode))

(when pkl-enable-copilot
  (if pkl--feature-copilot
      (progn
        (add-to-list 'copilot-indentation-alist '(pkl-mode tab-width)))
    (message "pkl-enable-copilot is t but copilot.el is missing.  Please install it or set pkl-enable-copilot to nil.")))
```
I'd write this all as:
```elisp
(defvar copilot-indentation-alist)

;;;###autoload
(define-derived-mode pkl-mode prog-mode "Pkl"
  "Major mode for editing Pkl files."
  :syntax-table pkl-mode-syntax-table
  (setq-local comment-start "// ")
  (setq-local comment-start-skip "//+\\s-*")
  (setq-local font-lock-defaults '(pkl-font-lock-keywords))
  (setq-local indent-line-function #'pkl-indent-line)

  (when pkl-enable-copilot
    (if (featurep 'copilot)
        (add-to-list 'copilot-indentation-alist '(pkl-mode tab-width))
      (user-error "pkl-enable-copilot is t but copilot.el is missing.  Please install it or set pkl-enable-copilot to nil."))))
```

**Comment by sin-ack** [comment]
Thanks for the review. What would you recommend regarding setting up optional dependencies like this? I thought about leaving it out of the package too, but I didn't want to expose the inner workings of the package to user configuration.

`copilot.el` is here: https://github.com/copilot-emacs/copilot.el

Regarding `copilot-indentation-alist`, wouldn't that re-add to the list with each activation? That's why I put it at top level.

**Comment by sin-ack** [comment]
Bumped `pkl-mode` to 1.0.1. The `rainbow-delimiters` integration has been removed. I've kept the `copilot.el` integration for now since it's a little more hairy. The warnings should now be gone, and we only warn the user if they have explicitly set `pkl-copilot-el` to `t` (we silently do nothing if it's not present otherwise).

**Comment by sin-ack** [comment]
Could you please give this another look? Thank you :)

**Comment by riscy** [comment]
Thank you, that looks good.

> What would you recommend regarding setting up optional dependencies like this?

I think you've done a good job of this, and it looks like the `copilot` integration at least is pretty compiler-friendly.

I'll merge this - and welcome to MELPA. :)

**Pull request merged**
