### PR TITLE
Add oceanic-theme.

### PR DESCRIPTION
**Pull request by terry3**
https://github.com/terry3/oceanic-theme

### CODE REVIEW

**Comment by purcell** [comment]
Sorry, that's not a valid package. It has none of the standard boilerplate with package description and other metadata. Try creating a fresh `oceanic-theme.el` file, then run `M-x auto-insert` -- that will lead you through creating the basic boilerplate you will need. You can then paste the current version into the boilerplate, replacing the `(provide 'oceanic-theme)` that will have been automatically inserted.

**Comment by tarsius** [comment]
@terry3 do you still want to get this into Melpa and intend to add the necessary boilerplate? Or should we close this?

**Comment by terry3** [comment]
@tarsius  Sorry for the late reply, I'll update this pull request by add the necessary stuff.  Thanks!

**Comment by terry3** [comment]
@purcell  @tarsius 
https://github.com/terry3/oceanic-theme Updated, please review this PR again, thanks!

**Comment by syohex** [comment]
https://github.com/terry3/oceanic-theme/pull/1

I have sent PR.

**Comment by terry3** [comment]
Thank you @syohex! [Updated](https://github.com/terry3/oceanic-theme/blob/master/oceanic-theme.el#L1-L6)!
Please help to review this pr again, thanks!

**Pull request merged**
