### PR TITLE
Add recipe for shrface.

### PR DESCRIPTION
**Pull request by chenyanming**
### Brief summary of what the package does

It is a shr faces package that helps users apply their favourite org faces to shr

### Direct link to the package repository

https://github.com/chenyanming/shrface

### Your association with the package

Maintainer

### Relevant communications with the upstream package maintainer

None needed

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Quick first pass --

Around line 468, there's no need to wrap the `else` part of an if in a `progn`, but that's small.

This block:
```elisp
(add-to-list 'shr-external-rendering-functions '(em  . shrface-tag-em))
(add-to-list 'shr-external-rendering-functions '(h1  . shrface-tag-h1))
(add-to-list 'shr-external-rendering-functions '(h2  . shrface-tag-h2))
(add-to-list 'shr-external-rendering-functions '(h3  . shrface-tag-h3))
(add-to-list 'shr-external-rendering-functions '(h4  . shrface-tag-h4))
(add-to-list 'shr-external-rendering-functions '(h5  . shrface-tag-h5))
(add-to-list 'shr-external-rendering-functions '(h6  . shrface-tag-h6))
(add-to-list 'shr-external-rendering-functions '(a   . shrface-tag-a))
(add-to-list 'shr-external-rendering-functions '(p   . shrface-tag-p))
(add-to-list 'shr-external-rendering-functions '(li   . shrface-tag-li))
```
seems to modify Emacs as soon as the package is loaded, without it ever being explicitly enabled by the user.  Except in special cases, this should be avoided, and instead these things should be changed when the user requests them (e.g. by calling a setup function, or enabling a mode, etc.)

I'm not familiar with shr, but would it be possible to redefine your minor mode as:
```elisp

;;;###autoload
(define-minor-mode shrface-mode
  "Toggle shr minor mode.
1. imenu
2. outline-minor-mode
3. org-indent-mode "
  :group 'shrface
  (cond
   (shrface-mode
    (shrface-shr-item-bullet)
    (setq imenu-create-index-function #'shrface-imenu-get-tree)
    (shrface-regexp)
    (outline-minor-mode)
    (org-indent-mode)
    (make-local-variable 'shr-external-rendering-functions)
    (add-to-list 'shr-external-rendering-functions '(em  . shrface-tag-em))
    ;; ...
    (add-to-list 'shr-external-rendering-functions '(li   . shrface-tag-li))
    (run-hooks 'shrface-mode-hook))
   (t
    ;; <somehow remove or restore the old shrface-external-rendering-functions>
    (shrface-shr-item-bullet)
    (setq imenu-create-index-function nil)
    (outline-minor-mode -1)
    (org-indent-mode -1))))
```
and that way, not only keep the effects local to the buffer, but to the minor mode being enabled/disabled as well?

**Comment by chenyanming** [comment]
@riscy Thanks for your user-oriented thinking tips. 

I tried to wrap the `add-to-list` into `shrface-mode`, but it can not work. Since `shr-external-rendering-functions` needed to be setup correctly before loading `eww`/`nov.el`/`dash-docs`. Unfortunally, `shr` does not provide any hooks for me to setup.

The sequences should be 
1. load `shr`
2. Setup `shr-external-rendering-functions`
3. load `eww`/`nov.el`/`dash-docs`.

Therefore, I adapt in a different way:
I create two functions: `shrface-basic` and `shrface-trail` for step 2, and leave it to user to enable, same behaviors as you suggest.

`shrface-mode` provides additional features for user to enable `imenu`, `outline` and `org-indent` support, without it, the users can still benefit from the package - only the faces.

Really appreciate that! 
[commit for fixing melpa pull #6847](https://github.com/chenyanming/shrface/commit/ea17fd28aaa42dbc20354c010bcbcff55885bc36)

**Comment by riscy** [comment]
Apologies for the delay.  Users with hundreds of packages installed thank you everywhere. :)

Here's the latest, and I think some of these are new, but also easy fixes.  I don't see any blockers after these are addressed.

### shrface.el ###

byte-compile-file (using Emacs 26.3):
- No issues!

checkdoc (using version 0.6.1):
```
Warning (emacs): 
shrface.el:87: First sentence should end with punctuation
Warning (emacs): 
shrface.el:92: First sentence should end with punctuation
Warning (emacs): 
shrface.el:151: First sentence should end with punctuation
Warning (emacs): 
shrface.el:592: First line is not a complete sentence
Warning (emacs): 
shrface.el:605: First line is not a complete sentence
Warning (emacs): 
shrface.el:615: First line is not a complete sentence
```
These are mostly easy to fix and so I think worth fixing.    For the "first line is not a complete sentence" checkdocs, this gives each function a nice one-liner that shows up well in documentation, and it's usually an easy fix.  For example:
```elisp
(defun shrface-basic()
  "Enable the shrface faces.
Needs to be called once before loading eww, nov.el, dash-docs,
mu4e, after shr."
  (interactive)
  (shrface-shr-item-bullet)
  (dolist (sub shrface-supported-faces-alist)
    (unless (member sub shr-external-rendering-functions)
      (add-to-list 'shr-external-rendering-functions sub)))
  ;; this setting is still needed to be setup by the user
  ;; (setq nov-shr-rendering-functions '((img . nov-render-img) (title . nov-render-title)))
  ;; (setq nov-shr-rendering-functions (append nov-shr-rendering-functions shr-external-rendering-functions))
  )
```

package-lint-current-buffer (using version 20200408.203):
- No issues!

Suggestions/experimental static checks:
- shrface.el#L449: Consider `unless ...` instead of `when (not ...)`

^ Minor, but for your consideration.

**Comment by chenyanming** [comment]
Thanks for your patient~

One liner is great! I missed that. Sorry about that, all are fixed in my lastest commit 

1. [checkdoc](https://github.com/chenyanming/shrface/commit/466ded61446a00bfc4e54412f482738a44dd2000)
2. [Fix `melpa/melpa#6847`](https://github.com/chenyanming/shrface/commit/761ea7c11dd5042c2e393d33187fae9c3000282b)

**Comment by riscy** [comment]
Apologies for the multiple iterations, but it seems like recent changes have created some byte-compile errors:

byte-compile-file (using Emacs 26.3):
```
shrface.el:578:11:Warning: assignment to free variable `pos'
shrface.el:580:11:Warning: assignment to free variable `end-pos'
shrface.el:581:25:Warning: reference to free variable `pos'
shrface.el:581:29:Warning: reference to free variable `end-pos'
In shrface-links:
shrface.el:650:9:Warning: assignment to free variable `buf-name'
shrface.el:657:19:Warning: reference to free variable `buf-name'
In shrface-href-collect:
shrface.el:765:63:Warning: assignment to free variable `beg'
shrface.el:692:15:Warning: assignment to free variable `end'
shrface.el:762:22:Warning: reference to free variable `beg'
shrface.el:766:63:Warning: reference to free variable `end'
shrface.el:737:53:Warning: assignment to free variable `url'
shrface.el:743:35:Warning: assignment to free variable `string'
shrface.el:762:40:Warning: assignment to free variable `start'
shrface.el:751:35:Warning: reference to free variable `url'
shrface.el:751:23:Warning: reference to free variable `string'
shrface.el:756:25:Warning: assignment to free variable `final'
shrface.el:764:38:Warning: reference to free variable `start'
shrface.el:764:44:Warning: reference to free variable `final'
shrface.el:769:1:Warning: Unused lexical variable `file'
shrface.el:769:1:Warning: Unused lexical variable `pos'
In shrface-mouse-1:
shrface.el:795:22:Warning: reference to free variable
    `compilation-highlight-overlay'
shrface.el:797:1:Warning: Unused lexical variable `pos'
shrface.el:811:1:Warning: Unused lexical variable `pos'
In shrface-ret:
shrface.el:835:20:Warning: reference to free variable
    `compilation-highlight-overlay'
In shrface-flash-show:
shrface.el:858:11:Warning: reference to free variable
    `compilation-highlight-overlay'
shrface.el:860:18:Warning: assignment to free variable
    `compilation-highlight-overlay'
```

And some bonus material :)
- shrface.el#L652: There is no need to quote lambdas (neither #' nor ')
- shrface.el#L657: It's safer to sharp-quote function names; use `#'`
- shrface.el#L865: It's safer to sharp-quote function names; use `#'`
- shrface.el#L620: It's safer to sharp-quote function names; use `#'`
- shrface.el#L863: It's safer to sharp-quote function names; use `#'`
- shrface.el#L726: You can use `not` or `null`

**Comment by chenyanming** [comment]
Thanks @riscy, you help me a lot~ Really appreciate your detail reports. Sorry about that I forget to byte-compile-file check for my new commits. I think 

- package-lint
- checkdoc
- byte-compile-file

are all happy now :)

[48a34c5 * master origin/master Fix `melpa/melpa#6847` byte-compile-file and #.
](https://github.com/chenyanming/shrface/commit/48a34c51815809018d9f64fe197069ca8caa7818)

**Comment by riscy** [comment]
Don't worry about it!  It's something that could be made easier.  One solution for that might be as follows -- I've made it very easy to [add some basic CI checks](https://github.com/riscy/melpazoid#add-it-to-github-actions) to your GitHub repository (basically just adding one file and editing a couple of fields).

On that note, this latest compiler issue may point to a missing `Package-Requires`:

byte-compile-file (using Emacs 26.3):
```
shrface.el:53:1:Error: Cannot open load file: No such file or directory, pcre2el
```

**Comment by chenyanming** [comment]
Oh, sorry about that, since I run it on my emacs, when I use `byte-compile-file` to check, it warns me a missing function which is from`pcre2el.el`, then I added it. But after, I found that it is because I used `ivy-read` and forgot to `require` it. Anyway,

Now I learned that I need to test on a clean emacs. It passed.

* Check [Fix `melpa/melpa#6847` Delete useless pcre2el.](https://github.com/chenyanming/shrface/commit/03988a147a5733ea2e7a442e2860704ebcf24eae)

Besides, thanks for your `melpazoid`, I already added it. And works great~ 
And my latest commit should be happy with `melpazoid`.
* Check [Test recipe](https://github.com/chenyanming/shrface/commit/ee14d4d8c9bf5f89bea97e897700f0af02ba5e28)

**Comment by riscy** [comment]
Great!  (And I'm glad melpazoid was useful :)

This looks good to me.  So, welcome to MELPA!

**Comment by chenyanming** [comment]
Cheers~:)

**Pull request merged**
