### PR TITLE
Add simple-tree recipe

### PR DESCRIPTION
**Pull request by Sasanidas**
### Brief summary of what the package does

It's a dead simple project listing package.

### Direct link to the package repository

https://gitlab.com/sasanidas/simple-tree.el

### Your association with the package

I'm the maintainer

### Relevant communications with the upstream package maintainer

*None needed**

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this, quick pass.

Your `;;; Commentary` seems a bit bare. :)    Your README has good content that you could pull in here, but I'm not entirely sure what this does.  It appears to be a way for one to create an index of directories (corresponding to projects) that can be opened using a side bar, but on a quick first pass I don't see where the notion of a "tree" comes into this?

The way you define `simple-tree-mode-map` using an `if` is a bit unusual, and it looks like you may want to use `defvar` (which won't redefine a variable that's already defined).  E.g. `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`

And some small potatoes:
- simple-tree.el#L131: You can use `not` or `null`
- simple-tree.el#L146: Optionally use `unless ...` instead of `when (not ...)`
- simple-tree.el#L117: No `format` required; `error` takes an f-string
- simple-tree.el#L124: No `format` required; `error` takes an f-string

**Comment by Sasanidas** [comment]
Hey @riscy , thanks for checking my package!

>I don't see where the notion of a "tree" comes into this?

That's the pun, it is a "tree" but it's only the "root" of it, that's why is so simple, I thought the name before starting to work into the package code, but I think it still makes some sense.

I address the other small issues :+1:

**Comment by riscy** [comment]
I now see where the pun is coming from :) but I feel like there's a cost associated with making this pun, which is that it could mislead people not in the know, like I was.  "tree" to me feels like a sort of specific, information-packed term in the context of our computer world, having to do with data structures and subgraphs and hierarchies.  I digress, but in this case I would strongly suggest renaming this package.

I think the main feature that this has over something like <kbd>M-x projectile-switch-project</kbd> or referencing `projectile-relevant-known-projects` is that it displays results in a side bar, so that might go some of the way toward picking a name.

**Comment by riscy** [comment]
I'm still a bit iffy on the name of this package -- I don't want to seem totally inflexible (and we could ask someone else to chime in, too).  I'll mark this awaiting upstream until we hear back.

**Comment by Sasanidas** [comment]
Sorry @riscy that it took me a while to answer.

> I think the main feature that this has over something like M-x projectile-switch-project or referencing projectile-relevant-known-projects is that it displays results in a side bar, so that might go some of the way toward picking a name.

Well, it also doesn't add or need any projectile meaning (AFAIK to detect a project, projectile require certain requirements, but I may be wrong).

That's also the idea, projectile is a big package, and this can extract the functionality of it, so you don't need it.

About the name, I have no idea how to call it, frankly, I know how the name is and I think I make it clear the first line of the README, I understand your position, and if it is a hard requirement for adding the package I will change the name.

Thanks again @riscy

**Comment by riscy** [comment]
> Well, it also doesn't add or need any projectile meaning (AFAIK to detect a project, projectile require certain requirements, but I may be wrong).

Emacs has the builtin function `project-current` -- I think project.el is something to keep an eye on if you see projectile.el as being too heavyweight.

One strategy for your package might be to try to retain compatibility with project.el and projectile.el since I think neither of this packages offer the feature of project side bars.

> About the name, I have no idea how to call it, frankly, I know how the name is and I think I make it clear the first line of the README, I understand your position

Naming things is a hard problem, or so the old saw goes. :)  If you want to retain some punniness in the name you could call it "side-projects", maybe.

**Comment by riscy** [comment]
Friendly ping. :) I think the only outstanding issue is the name.  Naming is of course a subjective thing, so if you're adamant on simple-tree we could ask for a third party to chime in.

I notice one checkdoc regarding this error message: `"Project %s already exist."` which should be `"Project %s already exists"`

**Comment by alphapapa** [comment]
It seems like much of the functionality of this package is provided by Emacs bookmarks.

**Comment by Boruch-Baum** [comment]
> It seems like much of the functionality of this package is provided by Emacs bookmarks.

And by other commands. Lately, I've been using (a customized version of) `magit-list-repositories` (magit PR #4399).

**Comment by Sasanidas** [comment]
Ok, seems like there is a couple of packages that has some similar functionality, so I don't think MELPA lose that much if it is not include, nonetheless, thanks @riscy for reviewing it and for the suggestions :+1:

**Comment by alphapapa** [comment]
@Sasanidas For future reference, looking at the code, I see some simple misunderstandings or knowledge gaps that maybe I can help correct for a fellow Lisper.

* You use the `seq` library to do things that would be much simpler with more basic functions.  For example, in `simple-tree--get-project`, you use `seq-find` to do what `alist-get` could do much more simply (if you also normalized the project names to either symbols or strings in the first place).
* The code of `simple-tree--insert-project` seems to indicate that you don't know how Lisp lists work.  You don't need to test for emptiness and initialize them, and you don't need to use `append` to add a new value.  You can just use, in this case, `cl-pushnew` to add a new value to the list if it doesn't already exist (see its `:test` keyword argument).
* In `simple-tree--delete-project`, you use `seq-filter` where you could simply use `delete`.  And since nil is the same as an empty list, you don't need to then test for nullity and then set it to an empty list if it is, which is effectively a no-op.
* In `simple-tree--save-all-projects`  you write a Lisp list to a file using `(insert (format "%s"...`.  Instead you should use `prin1`, which prints a readable representation to the standard output (see documentation).  As well, you can use `with-temp-file` rather than `with-temp-buffer` and `write-` functions.
* In `simple-tree--get-all-projects` you read the buffer to a string, then trim it, then `read-from-string`.  Instead you can simply `read` in the buffer.
* In `simple-tree-project-add` you use `string=`.  From a little testing and research, I've found that, in Emacs, `equal` is usually faster than `string=`. Not that it matters here, but it's a little bit of information that I think is not widely known.
* In `simple-tree-project-remove`, you use `seq-map` where `mapcar` would do.  `seq` is a generalized library, while `mapcar` is for lists, so the latter is faster (not that it matters, but generally it's better to use `mapcar` unless you need the generalized functionality that `seq` provides).
* In `simple-tree-refresh` you unset and then set again `buffer-read-only`.  Instead you can `let`-bind `inhibit-read-only` around the code that needs to modify the buffer.  Also, you use `seq-map` with a lambda, where `dolist` would be more concise and simpler.
* In `(defvar simple-tree-mode-map...`  you `(setq simple-tree-mode-map map)` as the last expression in the form.  This is bogus; just return `map`, because the `defvar` form assigns the valule.

These are some finer points of Lisp and Elisp that are usually only discovered over a period of time, so I hope this information can be a shortcut for you.  :)

**Comment by Sasanidas** [comment]
Hello @alphapapa , I put this package together in an afternoon without too much thinking, still most of the suggestions are pretty interesting:

> You use the seq library to do things that would be much simpler with more basic functions. For example, in simple-tree--get-project, you use seq-find to do what alist-get could do much more simply (if you also normalized the project names to either symbols or strings in the first place).

When I started learning Emacs, I found the seq library quite intuitive and just stick with it which also simplify the code in some ways (the library is very idiomatic). You are right tho, I should have save everything as a string and all things would be easier.

> The code of simple-tree--insert-project seems to indicate that you don't know how Lisp lists work. You don't need to test for emptiness and initialize them, and you don't need to use append to add a new value. You can just use, in this case, cl-pushnew to add a new value to the list if it doesn't already exist (see its :test keyword argument).

Yes, funny enough, I'm used to use pushnew in Common Lisp but the connexion didn't click until some months ago, again, you are 100% right, this is a bad hack (as suggested by the comment).

> In simple-tree--delete-project, you use seq-filter where you could simply use delete. And since nil is the same as an empty list, you don't need to then test for nullity and then set it to an empty list if it is, which is effectively a no-op.

This is the collateral damage of the other function hack (where I  don't manage empty lists), thanks for the suggestion.

> In simple-tree--save-all-projects you write a Lisp list to a file using (insert (format "%s".... Instead you should use prin1, which prints a readable representation to the standard output (see documentation). As well, you can use with-temp-file rather than with-temp-buffer and write- functions.

Nice! I wasn't aware of the prin1 function, I used with-tem-buffer and insert because I found it more idiomatic (giving that I don't want to write into a temporal file), but it is indeed, more correct. 

> In simple-tree--get-all-projects you read the buffer to a string, then trim it, then read-from-string. Instead you can simply read in the buffer.

:+1: 

> In simple-tree-project-remove, you use seq-map where mapcar would do. seq is a generalized library, while mapcar is for lists, so the latter is faster (not that it matters, but generally it's better to use mapcar unless you need the generalized functionality that seq provides).

Same as the first comment, but yes, mapcar is more accurate :+1: 

> In simple-tree-refresh you unset and then set again buffer-read-only. Instead you can let-bind inhibit-read-only around the code that needs to modify the buffer. Also, you use seq-map with a lambda, where dolist would be more concise and simpler.

I wasn't aware of this, thanks! :+1: 

> In (defvar simple-tree-mode-map... you (setq simple-tree-mode-map map) as the last expression in the form. This is bogus; just return map, because the defvar form assigns the value.

Ops, big mistake, thanks!

> These are some finer points of Lisp and Elisp that are usually only discovered over a period of time, so I hope this information can be a shortcut for you. :)

It is always an honour to get some tips/corrections from @alphapapa , Thanks :+1:

**Pull request closed without merging**
