### PR TITLE
adding my first package, font-man!

### PR DESCRIPTION
**Pull request by shackra**
I did this ridiculously simpler global minor mode to change the font size to default values when needed in situations like screen-casting.

### CODE REVIEW

**Comment by Silex** [comment]
Just curious, do you know about `text-scale-adjust` ? Bound to `C-x C-0`, then +/-/0 to scale font.

**Comment by shackra** [comment]
Because the scale is relative to the current font size where I'm looking to make the change based on absolute values (i.e.: setting the font to 16pt)

El 29 de junio de 2016 1:22:27 GMT-06:00, Philippe Vaucher <notifications@github.com> escribió:
>Just curious, do you know about `text-scale-adjust` ? Bound to `C-x
>C-0`, then +/-/0 to scale font.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/melpa/melpa/pull/4013#issuecomment-229276904

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shackra** [comment]
I mean, I knew about text-scale-adjust (in my first reply I thought you asked why I didn't use it, sorry) 

El 29 de junio de 2016 1:22:27 GMT-06:00, Philippe Vaucher <notifications@github.com> escribió:
>Just curious, do you know about `text-scale-adjust` ? Bound to `C-x
>C-0`, then +/-/0 to scale font.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/melpa/melpa/pull/4013#issuecomment-229276904

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by purcell** [comment]
My existing package `default-text-scale` handles exactly this use case, I think.

**Comment by shackra** [comment]
Question: Do your package have a global minor mode that can change the default text scale to a
default scale and apply the scale to every new frame created after the activation of such global
minor mode?

If not, maybe I could fork your code, make a couple of commits and then do a pull request (and
delete my package) :)

El jueves 30 de junio del 2016 a las 0041 horas, Steve Purcell escribió:

> My existing package `default-text-scale` handles exactly this use case, I think.
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/melpa/melpa/pull/4013#issuecomment-229573206


--
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by purcell** [comment]
It provides two commands for increasing/decreasing the default face height across all current and new frames.

**Comment by shackra** [comment]
It seems both packages does the same thing (by the same means), but in a different way (I guess). However, I'm looking to get something like `text-scale-mode`, and maybe I can achieve that with help from `switch-buffer-functions` package and some Elisp hacking.

**Pull request closed without merging**
