### PR TITLE
Add consult-eglot-embark

### PR DESCRIPTION
**Pull request by mohkale**
### Brief summary of what the package does

Embark integration for consult-eglot.

### Direct link to the package repository

https://github.com/mohkale/consult-eglot

### Your association with the package

Maintainer.

### Relevant communications with the upstream package maintainer

N/A.

### Checklist

- [X] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [X] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [X] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [X] My elisp byte-compiles cleanly
- [X] I've used `M-x checkdoc` to check the package's documentation strings
- [] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Quick first pass --

`consult-eglot-embark.el` with package-lint 20240220.2303:
```
2 issues found:
56:23: error: You should depend on (emacs "29.1") if you need `eglot--dbind'.
75:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.
```

**Comment by mohkale** [comment]
> 56:23: error: You should depend on (emacs "29.1") if you need `eglot--dbind'.

There's an explicit dependency on eglot (through elpa/melpa) so the older emacs requirement should still work. Dbind isn't new to the release of eglot on Emacs mainline. I think this is probably a corner case in the requires resolution logic :disappointed:.

> 75:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be used in packages.

I think the current usage is fair. It's basically a streamlining a configuration everyone who ever tries to install this package will want to do anyways. If they don't then they can not install the package since it is documented as a extension :upside_down_face:. Is this a hard rule or just a recommendation?

**Comment by mattiasb** [comment]
> > 75:1: warning: `with-eval-after-load' is for use in configurations, and should rarely be
> > used in packages.
> 
> I think the current usage is fair. It's basically a streamlining a configuration everyone who
> ever tries to install this package will want to do anyways. If they don't then they can not 
> install the package since it is documented as a extension 🙃. Is this a hard rule or just a 
> recommendation?

It seems to me like this should be made a minor mode instead?

**Comment by mohkale** [comment]
> It seems to me like this should be made a minor mode instead?

I think you're right. Converted to a globalized minor mode :-).

**Comment by riscy** [comment]
Thanks both - merging.

**Pull request merged**
