### PR TITLE
added recipe github-pullrequest

### PR DESCRIPTION
**Pull request by jakoblind**
### Brief summary of what the package does

Emacs package to smoothly create and checkout Github pull requests. Uses the Github access token for authorization to Github.

### Direct link to the package repository

https://github.com/jakoblind/github-pullrequest

### Your association with the package

I am creator/maintainer

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by syohex** [comment]
What is different between this package and [magit-ph-pulls](https://github.com/sigma/magit-gh-pulls) ? It looks magit-ph-pulls provides more features.

Review comment
- No autoload cookies
- Package dependencies are not correct(https://github.com/jakoblind/github-pullrequest/pull/12)

**Comment by jakoblind** [comment]
`magit-ph-pulls` does not support Github access token as authorization. Therefore it is not possible to use with accounts that uses 2f auth.

**Comment by syohex** [comment]
I see.

**Comment by syohex** [comment]
Merged.

**Comment by purcell** [comment]
> magit-ph-pulls does not support Github access token as authorization. Therefore it is not possible to use with accounts that uses 2f auth.

Maybe there's an opportunity to submit this behaviour as an enhancement to that package, though? Seems a shame to duplicate effort in different directions.

**Comment by jakoblind** [comment]
@purcell yes that was my initial thoughts. I worked for a few hours but had to give up because the code for  `magit-ph-pulls` (and `gh` which is uses) was way too complex. I read about others having similar experiences working with that code base. 

So my conclusion was to rewrite it from scratch with code readability as one of the top prioritization.

**Pull request merged**
