### PR TITLE
Add recipe for evil-ReplaceWithRegister

### PR DESCRIPTION
**Pull request by Dewdrops**
### Brief summary of what the package does

Port of vim plugin ReplaceWithRegister.

### Direct link to the package repository

https://github.com/Dewdrops/evil-ReplaceWithRegister

### Your association with the package

I'm the author and maintainer of this package.

### Checklist

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] I've built and installed the package using the instructions in the [README](https://github.com/melpa/melpa/blob/master/README.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks.
- `evil-ReplaceWithRegister` isn't a valid package name: try `evil-replace-with-register` instead. 
- The package description on the first line must not be wrapped
- Your package name in the recipe does not match the `.el` filename: build and test locally before submitting, please.

**Comment by ninrod** [comment]
awesome! I was waiting for this!

**Comment by Dewdrops** [comment]
@purcell 

Thanks for your very quick response and advices, and sorry for my previous horribly broken PR. 

Now I've addressed those mentioned issues, completed the checklist and successfully build this package locally (via `make recipes/evil-replace-with-register`). Is there still something I got wrong ?

**Comment by syohex** [comment]
I have tested your PR on my fork repository. Tests are passed. Could you squash commits and re-run test ?

https://github.com/syohex/melpa/pull/1

**Comment by Dewdrops** [comment]
@syohex Thanks for your help!

I've squashed commits and re-run (and passed) the test.

**Comment by purcell** [comment]
You still have identifiers beginning `evil-ReplaceWithRegister` in the source code. They should all be changed to use `evil-replace-with-register` to match the package name and [elisp conventions](https://www.gnu.org/s/emacs/manual/html_node/elisp/Coding-Conventions.html). Looks good otherwise. :-)

**Comment by Dewdrops** [comment]
Thanks for your help @purcell .

I've changed the function prefix suggested by elisp conventions now.

**Comment by purcell** [comment]
Awesome, thanks.

**Pull request merged**
