### PR TITLE
Add recipe for cue-mode

### PR DESCRIPTION
**Pull request by russell**
### Brief summary of what the package does

This adds the CUE language mode.  CUE is a data definition language like YAML but with support for inline schemas. https://cuelang.org/

### Direct link to the package repository

https://github.com/russell/cue-mode/

### Your association with the package

I'm the maintainer of the package

### Relevant communications with the upstream package maintainer

None needed

### Checklist

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by russell** [comment]
there are a few outstanding issues, but i don't think they are show stoppers

not all private methods are documented, all of which are related to `smie` so I'm not sure documentation will really help them that much.

There is one outstanding package-lint issue `"Version:" or "Package-Version:" header is missing` but it will require some work with my release process.  But the message says not declaring this is supported by MELPA, so I think this is ok

**Comment by riscy** [comment]
Thank you!  Usually when I'm reviewing I (annoyingly) push to get all of the detectable issues fixed -- even checkdocs -- just so that everyone's working to the same minimal standard.  Here's a quick pass --

`cue-mode-autoloads.el` with checkdoc 0.6.2:
```
cue-mode-autoloads.el:0: You should have a section marked ";;; Commentary:"
```
It's unusual for me to see this sort of a file included with a package.  Is it necessary for installation via MELPA?  I'm not sure, but maybe we want to `:exclude` it.

`cue-mode-autoloads.el` with package-lint 20220213.1457:
```
1 issue found:
22:1: error: You should depend on (emacs "26.1") if you need `register-definition-prefixes'.
```

`cue-mode.el` with checkdoc 0.6.2:
```
cue-mode.el:136: All variables and subroutines might as well have a documentation string
cue-mode.el:174: All variables and subroutines might as well have a documentation string
cue-mode.el:192: All variables and subroutines might as well have a documentation string
cue-mode.el:210: All variables and subroutines might as well have a documentation string
cue-mode.el:229: All variables and subroutines might as well have a documentation string
cue-mode.el:238: All variables and subroutines might as well have a documentation string
```
You knew about these.  Sorry to nag. :)

`cue-mode.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- cue-mode.el#L344: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- cue-mode.el#L393: Top-level `define-key` can overwrite bindings.  Try: `(defvar my-map (let ((km (make-sparse-keymap))) (define-key ...) km))`
- cue-mode.el#L132: No `format` required; `message` takes an f-string
```

**Comment by russell** [comment]
I have updated my package to address the errors you have highlighted, could you take another look?

**Comment by riscy** [comment]
Looks good.  Thanks, and welcome to MELPA. :)

**Pull request merged**
