### PR TITLE
add recipe for ini

### PR DESCRIPTION
**Pull request by pgdad**
### Brief summary of what the package does

Conversion of INI-format to Elisp Association Lists
Conversion of an Association List to INI-format string
The value part of the key-value pair may contain a list
of values, each value being on a single line.

### Direct link to the package repository

https://github.com/EsaLaine/ini.el

### Your association with the package

An enthusiastic user

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

- [x ] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses)
- [ x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x ] My elisp byte-compiles cleanly
- [ x] `M-x checkdoc` is happy with my docstrings
- [x ] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by riscy** [comment]
Thanks for this.  Note there is an ini-mode mirrored at https://github.com/emacsmirror/ini-mode.git but it's a major mode for those files.  (Still, it makes sense to be aware of this complementary project; you may want to check if there is an opportunity to collaborate.)  In any case the checklist looks good, but there's a LICENSE file missing --

`ini.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- ini.el#L168: No `format` required; `error` takes an f-string
- ini.el#L185: No `format` required; `error` takes an f-string
- ini.el#L189: No `format` required; `error` takes an f-string
```

Package and license:
- Add a LICENSE file to the repository

You may also want to double-check on your how your `;;; Commentary` is parsing with `M-: (lm-commentary)` -- it may be inadvertently including some of your horizontal separators, and "dependencies" are usually considered part of the `;;; Code` section anyway.

**Comment by pgdad** [comment]
Chris,

Thanks for working on this.

I think I have fixed what I know how to. Also learned about melpazoid as a result of this email.
I pushed changes to the ini.el repo. Please let me know if you have any other suggestions.

Thanks,

Esa

________________________________

**Comment by riscy** [comment]
Thanks for accommodating.  melpazoid still has a lot of rusty corners but people sometimes ask me, "where are you getting these additional warnings?" so that's why I link it, hopefully not reeking too much of self-promotion. :)

Re: my comments on the `;;; Commentary`, currently (lm-commentary) gives text that ends with:
```elisp
;;; ----------------------------------------------------------------------------
;;; Dependencies:
;;
```
so we should do something about this.  I think the best way is to drop the separator and the `;;; Dependencies` section, altogether giving:
```elisp
...

;; The code hierarchy follows:
;;
;; - `ini-decode'
;;   - `ini--add-to-alist'
;;     - `ini--add-to-keys'
;;   - `ini--add-extra-value'
;;
;; - `ini-store'
;;   - `ini-encode'

;;; Code:

(eval-when-compile (require 'subr-x))   ; use: `string-join'

...
```

**Comment by pgdad** [comment]
Thank you again, I made the change you suggested and pushed a new commit.

Thanks,

Esa

________________________________

**Comment by riscy** [comment]
Looks good.  That's a superpower of a regular expression there. :)

And, welcome to MELPA!

**Comment by alphapapa** [comment]
@riscy @pgdad This recipe is pulling from a repo other than the package's author/maintainer, i.e. https://github.com/pierre-rouleau/ini.el.  This PR says that no communication was needed with the maintainer's, but that does not seem to be evident to me.  Was @pierre-rouleau contacted by @pgdad or @EsaLaine?  Is there a reason to make a third fork of the project and use that for MELPA rather than working on it in pierre-rouleau's repo?

As well, I was going to file an issue pointing out a few issues with the API and the readme, but it's unclear which one to use, and neither one has their issue tracker enabled, so it seems like a dead-end for users.

**Pull request merged**
