### PR TITLE
Add recipe for evalator-context-cider package

### PR DESCRIPTION
**Pull request by seanirby**
Hello again,

I'd like to add [evalator-context-cider](https://github.com/seanirby/evalator-context-cider) to MELPA.

This package adds Clojure support to [evalator](https://github.com/seanirby/evalator)

If you want to manually test this then the newest version of evalator is required, which may or may not be built in MELPA yet.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Please can you use `:defaults` rather than `"*.el"`? The former includes the latter, and is preferred when possible. You would ideally amend and force-push the recipe commit to cleanly update the PR.

Apart from that, it all looks good, but you should add info in the `Commentary` section of the header about how to enable/use the package.

**Comment by seanirby** [comment]
Thanks! I will make those changes ASAP and ping you here when it's all ready to go.

**Comment by seanirby** [comment]
*ping* @purcell 

I've addressed your issues.  I also renamed the package and made it depend on the parent evalator package because I needed certain things to autoload correctly.

**Comment by purcell** [comment]
Super, thanks Sean.

**Pull request merged**
