### PR TITLE
Update URL of fish-completion's repository

### PR DESCRIPTION
**Pull request by LemonBreezes**
Hi. Ambrevar has archived his [emacs-fish-completion](https://gitlab.com/ambrevar/emacs-fish-completion) repository and handed the project to me. This is updating MELPA to point to [my repository](https://github.com/LemonBreezes/emacs-fish-completion).

### CODE REVIEW

**Comment by riscy** [comment]
Hi @LemonBreezes -- please make sure you read https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks; since this is your first time here, I should also point you to the [section mentioning the new maintainer should have some experience](https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks#other-things-to-note).

**Comment by riscy** [comment]
(With that said, thank you for volunteering to do this; take a look at that doc and let's see where we go from there.)

**Comment by LemonBreezes** [comment]
> Hi @LemonBreezes -- please make sure you read [Wiki: Unmaintained Packages and Forks ()](https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks); since this is your first time here, I should also point you to the [section mentioning the new maintainer should have some experience](https://github.com/melpa/melpa/wiki/Unmaintained-Packages-and-Forks#other-things-to-note).

Sure. Regarding my experience, I don't maintain any packages on MELPA/ELPA, but I do have direct commit access to several packages on MELPA such as `pcache`, `pcmpl-args`, and `evil-indent-plus`. Furthermore, I have merged 49 PRs to Emacs packages and Doom Emacs, primarily fixing errors in packages. Examples:
[pcre2el: Fix most of the issues and test cases (see description) #46](https://github.com/joddie/pcre2el/pull/46)
[doom-modeline: Allow modeline segments to be natively compiled. #530](https://github.com/seagle0128/doom-modeline/pull/530)
[helm-posframe: Fix window dedicated p error #16](https://github.com/tumashu/helm-posframe/pull/16)
[evil-embrace: fix evil-surround-*-overlay args #10](https://github.com/cute-jumper/evil-embrace.el/pull/10)
[elfeed-org: fix elfeed-org-export-opml error #88](https://github.com/remyhonig/elfeed-org/pull/88)

**Comment by riscy** [comment]
Thanks - I think I had my foot on the gas and missed you stating that the package was explicitly handed to you; apologies for that oversight.

**Pull request merged**
