### PR TITLE
+ config-general-mode: major mode for config files

### PR DESCRIPTION
**Pull request by TLINDEN**
config-general-mode

### Brief summary of what the package does

This major mode can be used to help editing config files parseable by Config::General (http://search.cpan.org/dist/Config-General/), a perl config file parser/writer used by many tools (e.g. Catalyst). 

### Direct link to the package repository

https://github.com/TLINDEN/config-general-mode

### Your association with the package

I am the creator and maintainer.

### Relevant communications with the upstream package maintainer

**None needed**

### Checklist

Please confirm with `x`:

- [x] I've read [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)
- [x] I've used [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.md](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! Sorry for the delay. Some quick feedback:

- Don't use `(if (not cond) (progn ...))`: just use `(unless cond ...)`
- Similarly, use `(when cond ...)` instead of `(if cond ...)` -- `if` is really only for expressions that have both an `if` and and `else` branch.
- `config-general-tab-or-complete` is unusual: rather than overriding completion behaviour (and `TAB` specifically, which not everyone will expect to complete) you should instead provide a `completion-at-point-function`, and then the user's preferred completion mechanism can use that function.
- You're doing a lot of things in `define-derived-mode` that that macro can handle itself, e.g. setting the mode name and symbol, running the hooks, setting the syntax table and keymap etc. So you can - and should - remove the redundant code.
- Unsetting local keybindings in your major mode initialisation code is weird and should be unnecessary.

Hope that helps!

**Comment by TLINDEN** [comment]
Hello Steve,

thanks for your feedback!

- I fixed the `(if` issues (but not in `config-general--try-expand-dabbrev-all-buffers`, which is a patched version of `try-expand-dabbrev-all-buffers`)
- I have a problem with `(setq major-mode 'config-general-mode)`: if I remove this call, then the mode will be loaded but `describe-mode` doesn't mention it (whereas it does when I leave the call in the code)
- Similarly if I disable `(setq mode-name "C::G")` then the modeline displays "Fundamental"

Do you have any idea for the former two issues?


best regards,
Tom

**Comment by TLINDEN** [comment]
PS: the keymap doesn't work as well, if I remove `(use-local-map config-general-mode-map)`. This is really weird.

**Comment by purcell** [comment]
Sent you a bunch of fixes in https://github.com/TLINDEN/config-general-mode/pull/1.

**Comment by TLINDEN** [comment]
Merged, thanks a lot!

**Comment by purcell** [comment]
Merged here too - thanks! :-)

**Pull request merged**
