### PR TITLE
New recipy for kosmos-theme

### PR DESCRIPTION
**Pull request by habamax**
kosmos-theme is a mostly black and lightgray theme with minimal syntax highlighting.

Author: Maxim Kim <habamax@gmail.com>
Url: https://github.com/habamax/kosmos-theme

### CODE REVIEW

**Comment by syohex** [comment]
I sent PR(https://github.com/habamax/kosmos-theme/pull/1) about `custom-theme-load-path`.

**Comment by habamax** [comment]
Thanks, merged

**Comment by purcell** [comment]
Thanks: pending https://github.com/habamax/kosmos-theme/pull/4.

**Comment by habamax** [comment]
Merged. 

Didn't know about versioning.

**Pull request merged**
