### PR TITLE
Add keycaster recipe

### PR DESCRIPTION
**Pull request by chuntaro**
### Brief summary of what the package does

This package is a keystroke visualizer for GUI version Emacs.
This allows you to display keystrokes without relying on external tools when creating screencasts.
There are screencasts in the repositories below to see how this works.

### Direct link to the package repository

https://github.com/chuntaro/emacs-keycaster

### Your association with the package

I am the author and maintainer.

### Relevant communications with the upstream package maintainer

None needed.

### Checklist

Please confirm with `x`:

- [x] The package is released under a [GPL-Compatible Free Software License](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
- [x] I've read [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [x] I've used the latest version of [package-lint](https://github.com/purcell/package-lint) to check for packaging issues, and addressed its feedback
- [x] My elisp byte-compiles cleanly
- [x] `M-x checkdoc` is happy with my docstrings
- [x] I've built and installed the package using the instructions in [CONTRIBUTING.org](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org)
- [ ] I have confirmed some of these without doing them

### CODE REVIEW

**Comment by alphapapa** [comment]
Have you seen https://github.com/tarsius/keycast ?  It would be good if you could contribute to it as an alternate display style.

**Comment by chuntaro** [comment]
Emacs has the ability to capture keystrokes, so most (close to 99%) of the keycaster code is spent displaying.
It should be the same for keycast.
So, since the display method is completely different, I think that there is no problem to say that it is a completely different package.
However, it is not good to have almost the same name, so can I change the package name and PR again?

**Comment by riscy** [comment]
> so can I change the package name and PR again?

You can just update this PR if you like, and update the link to the package repository in your PR description.  It's all good. :)

**Comment by riscy** [comment]
Ping when this is ready for another look.

**Pull request closed without merging**
